### ISSUE TITLE
[BUG] 网站 - 默认站点 配置不完备

### ISSUE THREAD

**Issue by kookyleo** [1Panel-dev/1Panel#1000]
### 1Panel 版本

v1.2.1

### 问题描述

如题，
生成的 nginx conf,  default_server 指令只写了第一行: ipv4:80 (而漏掉了 ipv4:443,  ipv6:*)

### 重现步骤

WebUI /websites 选择 默认站点

**Comment by zhengkunwang223** [comment]
感谢建议 后续我们优化此配置

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
