### ISSUE TITLE
[FEATURE]已安装应用名称显示的问题

### ISSUE THREAD

**Issue by bh1xaq** [1Panel-dev/1Panel#1002]
### 1Panel 版本

v1.2.2

### 请描述您的需求或者改进建议

对于php环境来说，一个php容器会承载多个网站，这样显示不便于管理
这里显示的应用名称为网站名称，感觉很奇怪
![image](https://github.com/1Panel-dev/1Panel/assets/16686956/13acba6f-c3bc-4d3d-9feb-4a8e93456222)

在创建php环境时，我已经指定了php环境的名称，
![image](https://github.com/1Panel-dev/1Panel/assets/16686956/49e68e68-0d2c-478f-8301-d20eea04d037)

是否可以拿这个名称信息

### 请描述你建议的实现方案

应用商店中显示同运行时配置的名称。

### 附加信息

无

**Comment by zhengkunwang223** [comment]
感谢建议 后续支持一个运行环境 对应多个网站的时候优化

**Comment by bh1xaq** [comment]
感谢回复，当前版本已经支持一个运行环境中运行多个网站，：）

**Comment by zhengkunwang223** [comment]
> 感谢回复，当前版本已经支持一个运行环境中运行多个网站，：）

当前是一个运行环境 但是是多个容器 后续会支持一个容器中 多个网站 节省资源

**Comment by bh1xaq** [comment]
> > 感谢回复，当前版本已经支持一个运行环境中运行多个网站，：）
> 
> 当前是一个运行环境 但是是多个容器 后续会支持一个容器中 多个网站 节省资源

好像并不是耶

![image](https://github.com/1Panel-dev/1Panel/assets/16686956/f8cda338-1414-4f62-b372-50befe32dd7c)

实际只有一个php容器支撑

![image](https://github.com/1Panel-dev/1Panel/assets/16686956/f34ae579-7109-4c22-b778-15607d4fbae3)

**Comment by zhengkunwang223** [comment]
> > > 感谢回复，当前版本已经支持一个运行环境中运行多个网站，：）
> > 
> > 
> > 当前是一个运行环境 但是是多个容器 后续会支持一个容器中 多个网站 节省资源
> 
> 好像并不是耶
> 
> ![image](https://user-images.githubusercontent.com/16686956/237646137-f8cda338-1414-4f62-b372-50befe32dd7c.png)
> 
> 实际只有一个php容器支撑
> 
> ![image](https://user-images.githubusercontent.com/16686956/237645921-f34ae579-7109-4c22-b778-15607d4fbae3.png)

嗯 是再新建一个网站 选择这个运行环境 会新建容器

**Comment by bh1xaq** [comment]
> > > > 感谢回复，当前版本已经支持一个运行环境中运行多个网站，：）
> > > 
> > > 
> > > 当前是一个运行环境 但是是多个容器 后续会支持一个容器中 多个网站 节省资源
> > 
> > 
> > 好像并不是耶
> > ![image](https://user-images.githubusercontent.com/16686956/237646137-f8cda338-1414-4f62-b372-50befe32dd7c.png)
> > 实际只有一个php容器支撑
> > ![image](https://user-images.githubusercontent.com/16686956/237645921-f34ae579-7109-4c22-b778-15607d4fbae3.png)
> 
> 嗯 是再新建一个网站 选择这个运行环境 会新建容器

了解了，多谢~：）

**Comment by wanghe-fit2cloud** [comment]
#2405
