### ISSUE TITLE
[BUG]防火墙端口设置问题

### ISSUE THREAD

**Issue by rise9** [1Panel-dev/1Panel#1006]
### 1Panel 版本

1.2.2

### 问题描述

![2023-05-12 01 07 51](https://github.com/1Panel-dev/1Panel/assets/52342969/86b574e3-ea5c-406d-86d6-7165a7f9a2d7)
61916不是合法端口？

### 重现步骤

61916不是合法端口？

**Comment by ssongliu** [comment]
感谢反馈！该问题将在下个小版本修复 。

**Comment by wanghe-fit2cloud** [comment]
v1.2.3 版本已发布。
