### ISSUE TITLE
[FEATURE]建议增加ZFile

### ISSUE THREAD

**Issue by TIkc9** [1Panel-dev/1Panel#1008]
### 1Panel 版本

v1.2

### 请描述您的需求或者改进建议

https://www.zfile.vip/，基于 Java 的在线网盘程序，支持对接 S3、OneDrive、SharePoint、又拍云、本地存储、FTP 等存储源，支持在线浏览图片、播放音视频，文本文件等文件类型。
功能还是比较全的，建议加入应用商店。

**Comment by zhengkunwang223** [comment]
感谢建议 我们测试一下

**Comment by wanghe-fit2cloud** [comment]
#250

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布，应用商店支持了 ZFile。
