### ISSUE TITLE
[FEATURE] 计划任务增加批量暂停

### ISSUE THREAD

**Issue by FoXiMao** [1Panel-dev/1Panel#1010]
### 1Panel 版本

1.2.1

### 请描述您的需求或者改进建议

计划任务增加批量暂停

### 请描述你建议的实现方案

目前只有批量删除 暂停只能一个一个操作比较麻烦

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持批量暂停计划任务的需求。

**Comment by wanghe-fit2cloud** [comment]
v1.3.3 版本已发布。
