### ISSUE TITLE
[FEATURE] 应用商店第三方仓库支持

### ISSUE THREAD

**Issue by guclan** [1Panel-dev/1Panel#1012]
### 1Panel 版本

v1.2.1

### 请描述您的需求或者改进建议

需求：
1、提供第三方应用标签，可以安装第三方的应用。
2、提供所有应用的来源，是否可信（官方认证）。

具体实现：
第一种：页面白屏化实现，可以让用户自行进行创建第三方应用并上传zip安装包，安装包内容格式参考appstore仓库格式进行组织。
第二种：白屏化或后台命令行添加第三方源，页面进行同步所有第三方仓库包或者仅同步某一个第三方包并标记来源。若该实现较为复杂，可以进行后台命令行形式添加，例如1pctl install-app halo.
第三种：项目不做任何更改，使用本地安装代替第三方应用标签，开发脚本后台命令行进行设置第三方源并同步具体的软件包配置到本地，页面点击同步应用即可获取第三方安装包。

### 请描述你建议的实现方案

建议实现第一种和第二种，对用户更友好，若近期无计划，本人可以提pr进行第三种方式的改进。技术栈暂时不会golang和vue~

**Comment by zhengkunwang223** [comment]
您好 appstore 最近要重构 重构的时候会考虑到第三方 或者 离线包的形式，可以等 v1.3 发布之后看一下我们的实现
