### ISSUE TITLE
[FEATURE] 在备份账号中，云存储中设置指定的目录位置

### ISSUE THREAD

**Issue by Shuai-S** [1Panel-dev/1Panel#1013]
### 1Panel 版本

v1.2.2

### 请描述您的需求或者改进建议

<img width="1357" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/52077275/9bde3707-1519-4d9c-adc6-f3a109f8cad7">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会支持用户在创建第三方备份账号时指定目录。

**Comment by Shuai-S** [comment]
最好支持多个同类的第三方账号，比如多个阿里云，或者七牛云账号，可能不通的资源要备份到不同的账号

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
