### ISSUE TITLE
[BUG]左侧边栏区域消失

### ISSUE THREAD

**Issue by spronline** [1Panel-dev/1Panel#1015]
### 1Panel 版本

v1.2.2

### 问题描述

Ubuntu20.4\22.4，使用面板ssh终端时进入全屏模式，按Esc退出全屏后会出现左侧边栏区域消失。刷新、重启面板均不能解决。

面板显示异常情况如图

![Snipaste_2023-05-12_13-39-11](https://github.com/1Panel-dev/1Panel/assets/109900718/e357aa7c-68df-4ee3-93e1-b1fecbbeb692)

### 重现步骤

已实验多次，使用面板ssh终端进入全屏并退出后均出现面板显示异常情况。

**Comment by zyyfit** [comment]
您好，感谢您的反馈，后续版本修复这个问题，现在如果您无法正常操作系统的话，可以先使用以下方法临时解决：
1、进入面板的主机-终端页面，可以直接在地址栏输入地址（将IP和端口号替换成自己的IP和端口），
如 https://172.16.10.91:9999/hosts/terminal
2、点击终端窗口的最大化按钮，然后按esc键退出，导航栏就会显示出来了

**Comment by wanghe-fit2cloud** [comment]
v1.3.1 版本已发布。

**Comment by zjwboy1984** [comment]
> 您好，感谢您的反馈，后续版本修复这个问题，现在如果您无法正常操作系统的话，可以先使用以下方法临时解决： 1、进入面板的主机-终端页面，可以直接在地址栏输入地址（将IP和端口号替换成自己的IP和端口）， 如 https://172.16.10.91:9999/hosts/terminal 2、点击终端窗口的最大化按钮，然后按esc键退出，导航栏就会显示出来了

这个可以，有效果，感谢分享

**Comment by davidLi17** [comment]
目前遇到了同样的bug,现在的时间是2024年10月16日 19:32:12,还没修复吗
![9DBB76BE0A98F5E2922EE3C04EC64156](https://github.com/user-attachments/assets/77f77df7-03a1-4cef-a4ac-891f70e34a2f)

**Comment by wang0yue** [comment]
还没修复，我也遇到了，清理缓存和cookie也可以恢复

**Comment by tcqiuyu** [comment]
我也遇到了，貌似还没修复

**Comment by wanghe-fit2cloud** [comment]
> 我也遇到了，貌似还没修复

修改网页全屏时引出的 bug，会在 v1.10.21 版本修复。
https://github.com/1Panel-dev/1Panel/issues/6889

**Comment by BlueWhale235** [comment]
> hosts/terminal

还没有修复
