### ISSUE TITLE
[BUG]计划任务数据库第三方备份

### ISSUE THREAD

**Issue by MiaoToT** [1Panel-dev/1Panel#1017]
### 联系方式

miaotoot@outlook.com

### 1Panel 版本

v1.2.2

### 问题描述

使用计划任务，备份数据库，备份到第三方MINIO中功能可以执行成功。在执行成功后，进入数据库面板对应数据库备份列表可以查看到对应的备份到MINIO的数据，但是无法进行删除\恢复\下载。提示错误“服务内部错误: no such column: name”。

### 重现步骤

1. 计划任务-创建计划任务。任务类型选择备份数据库，备份到MINIO，取消同时保留本地备份的勾选。
2. 手动点击计划任务的执行，查看计划任务执行报告成功。
3. 进入MINIO，确认备份文件存在。
4. 数据库-MySQL，对应数据库点击备份列表，确认备份文件存在，无法进行删除\恢复\下载操作。

### 期待的正确结果

1. 数据库，MySQL备份列表中可以对备份到第三方的文件进行删除恢复下载操作。
2. 备份列表中的备份按钮，可以设置备份到本地服务器或者是第三方。

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/34637577/b401971a-07b7-4f69-996d-9f57e2d44bce)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述问题将在下周要发布的 v1.2.3 版本中修复。

**Comment by wanghe-fit2cloud** [comment]
v1.2.3 版本已发布。
