### ISSUE TITLE
[FEATURE] 建议优化应用相关操作的报错

### ISSUE THREAD

**Issue by wangzhengkun** [1Panel-dev/1Panel#1018]
### 1Panel 版本

v1.2.2

### 请描述您的需求或者改进建议

1. 安装应用的时候 因为网络原因镜像下载失败 这时候点击启动应用报错找不到容器  
2. 不小心修改了安装目录，报错找不到目录

建议优化为中文，让用户可以快速确认问题

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
