### ISSUE TITLE
[BUG]无法绑定IPV4监听

### ISSUE THREAD

**Issue by maincooss** [1Panel-dev/1Panel#1024]
### 1Panel 版本

v1.2.2

### 问题描述

一键安装后并无报错,但是无法访问.经过排查,发现只监听了iPV6,并通过IPV6可以进入.

### 重现步骤

新版Ununtu 使用最新的Ubuntu脚本安装出现.

### 附加信息

root@ubuntu-vm:~# cat /etc/os-release 
PRETTY_NAME="Ubuntu 23.04"
NAME="Ubuntu"
VERSION_ID="23.04"
VERSION="23.04 (Lunar Lobster)"
VERSION_CODENAME=lunar
ID=ubuntu
ID_LIKE=debian

root@ubuntu-vm:~# uname -r
6.2.0-20-generic

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 3000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 367.0.0.3/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::3/368 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 3500 qdisc pfifo_fast state UP group default qlen 3000
    link/ether 00:0c:61:55:cd:87 brd ff:ff:ff:ff:ff:ff
    altname enp6s3
    inet 316.368.330.630/64 brd 316.368.330.655 scope global noprefixroute ens33
       valid_lft forever preferred_lft forever
    inet6 6401:8a68:a5f:3ff0:a5a0:680e:f6ac:fef0/64 scope global temporary dynamic 
       valid_lft 384866sec preferred_lft 85350sec
    inet6 6401:8a68:a5f:3ff0:333d:fec6:5638:7cde/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 384866sec preferred_lft 18466sec
    inet6 fe80::63bd:16d:5cf3:3633/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 3500 qdisc noqueue state DOWN group default 
    link/ether 06:46:6e:56:3e:f3 brd ff:ff:ff:ff:ff:ff
    inet 376.37.0.3/36 brd 376.37.655.655 scope global docker0
       valid_lft forever preferred_lft forever
4: br-ceed1367fc66: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 3500 qdisc noqueue state DOWN group default 
    link/ether 06:46:bf:d3:74:f3 brd ff:ff:ff:ff:ff:ff
    inet 376.38.0.3/36 brd 376.38.655.655 scope global br-ceed1367fc66
       valid_lft forever preferred_lft forever

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，通常情况下 1Panel 绑定的 tcp6 是 ipv6 和 ipv4 都可以被访问到的。
查看一下 bindv6only 参数：
```shell
sysctl net.ipv6.bindv6only
```
如果值为 1，可以尝试将 net.ipv6.bindv6only 设置为0。

**Comment by Bet5521** [comment]
设置的是8888端口，但是tcp依然只监听v6不监听v4
sysctl net.ipv6.bindv6only
net.ipv6.bindv6only = 0
但是
netstat -nultp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:37597         0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -
tcp6       0      0 :::8888                 :::*                    LISTEN      -
udp        0      0 127.0.0.53:53           0.0.0.0:*                           -
udp        0      0 127.0.0.1:323           0.0.0.0:*                           -
udp6       0      0 ::1:323                 :::*                                -

**Comment by aurorataro** [comment]
同样遇到只绑定ipv6情况，系统是全新安装的debian12

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本支持在面板设置中切换监听IP。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
