### ISSUE TITLE
[QUESTION] 无法创建网站

### ISSUE THREAD

**Issue by TcDhlPro** [1Panel-dev/1Panel#1025]
### 请描述您的问题

升级面板后, 不管是创建网站, 还是删除网站中的域名, 还是停止网站, 都会报类似如下错误, 咋解决?
![image](https://github.com/1Panel-dev/1Panel/assets/100897011/49baea64-e504-4730-97c8-a8be0f7be4a2)

**Comment by zhengkunwang223** [comment]
显示网站日志文件丢失，需要重启 openresty

**Comment by TcDhlPro** [comment]
重启后直接这样了
![image](https://github.com/1Panel-dev/1Panel/assets/100897011/4e59793b-55dd-4ede-b32a-1ffe930b6712)

**Comment by zhengkunwang223** [comment]
> 重启后直接这样了
> 
> ![image](https://github.com/1Panel-dev/1Panel/assets/100897011/4e59793b-55dd-4ede-b32a-1ffe930b6712)
> 
> 

去容器列表那看一下openresty 的日志
