### ISSUE TITLE
[FEATURE]在文件管理页面打开终端，加入ssh配置功能

### ISSUE THREAD

**Issue by miaowuawa** [1Panel-dev/1Panel#1031]
### 1Panel 版本

1.2.2

### 请描述您的需求或者改进建议

文件页面打开终端的功能类似于宝塔的，在文件管理页面打开终端并自动cd当前目录，这样方便很多

ssh配置的功能就是配置服务器ssh端口，验证方式这些，可以顺便加上修改登陆后的motd，也可以加上fail2ban

**Comment by zhengkunwang223** [comment]
您好，后续版本支持文件页面打开终端和SSH管理

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已经支持 SSH 配置功能。

**Comment by wanghe-fit2cloud** [comment]
文件终端功能会在 1.8.0 版本支持，和现有 Issue 重复 #958
