### ISSUE TITLE
[FEATURE]文件夹排序问题

### ISSUE THREAD

**Issue by laoutiao** [1Panel-dev/1Panel#1032]
### 1Panel 版本

1.2.2

### 请描述您的需求或者改进建议

希望文件夹里面按照 -文件夹名-文件名排列，从上到下先排文件夹再排文件
目前的排序是这样的
![image](https://github.com/1Panel-dev/1Panel/assets/54140010/be834338-f51c-4aae-afe3-83bca029a25d)

### 请描述你建议的实现方案

我希望排序是像Win10文件夹那样的排序

**Comment by zhengkunwang223** [comment]
后续版本优化这个问题

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
