### ISSUE TITLE
[BUG] 概览页面推荐应用布局显示异常

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#1033]
### 1Panel 版本

v1.2.2

### 问题描述

概览页面推荐应用布局显示异常

![图片](https://github.com/1Panel-dev/1Panel/assets/15864713/2d9bbdc1-36a7-478a-90f5-fe268b68efc7)

另外应用列表中全部应用 tab 中已安装的页面是否直接显示已安装

### 重现步骤

将浏览器窗口逐渐缩小即可见

**Comment by zhengkunwang223** [comment]
感谢建议 我们会优化首页显示

**Comment by mx2913** [comment]
PR #1080 已解决
