### ISSUE TITLE
【建议】FTP功能

### ISSUE THREAD

**Issue by TomChicken-on-github** [1Panel-dev/1Panel#1035]
### 1Panel 版本
v1.2.2
 建议加上一个快速创建FTP的功能（懒癌.jpg

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持上述功能。

**Comment by TomChicken-on-github** [comment]
我*这么给力，辛苦了

**Comment by maninhill** [comment]
https://github.com/drakkan/sftpgo
可以放到应用商店。
@wanghe-fit2cloud

**Comment by wanghe-fit2cloud** [comment]
> https://github.com/drakkan/sftpgo 可以放到应用商店。 @wanghe-fit2cloud

#250

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布，ftp 教程请参考 [官方文档](https://1panel.cn/docs/user_manual/ftp/)
