### ISSUE TITLE
【新功能建议】自定义主页和远程数据库

### ISSUE THREAD

**Issue by TomChicken-on-github** [1Panel-dev/1Panel#1036]
### 1Panel 版本

1.2.2

### 请描述您的需求或者改进建议

添加自定义主页功能
![image](https://github.com/1Panel-dev/1Panel/assets/98439096/818f88a2-183a-45f5-b78e-fc6557c8622c)
添加连接远程数据库（MySQL）功能
辛苦了

### 附加信息

帮朋友提交的（）

**Comment by TomChicken-on-github** [comment]
> ### 1Panel 版本
> 1.2.2
> 
> ### 请描述您的需求或者改进建议
> 添加自定义主页功能 ![image](https://user-images.githubusercontent.com/98439096/238162777-818f88a2-183a-45f5-b78e-fc6557c8622c.png) 添加连接远程数据库（MySQL）功能 辛苦了

> ### 附加信息
> 帮朋友提交的（）

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，该 issues 中涉及到两个需求：
1、支持添加远程 MySQL 数据库
2、自定义显示、隐藏左侧菜单

上述两个功能我们均已收录，会陆续在后续版本中实现。

**Comment by windsOne** [comment]
求支持 远程数据库
@wanghe-fit2cloud

**Comment by wanghe-fit2cloud** [comment]
> 求支持 远程数据库 @wanghe-fit2cloud

已经纳入迭代计划，近期版本就会支持。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布，支持添加 MySQL 远程数据库。
