### ISSUE TITLE
[BUG] 一键部署问题

### ISSUE THREAD

**Issue by Daiyangcheng** [1Panel-dev/1Panel#1038]
### 联系方式

QQ：3143105972

### 1Panel 版本

1.2.2

### 问题描述

在创建网站时选择选择一键部署模式，选择新装应用安装应用（我安装的是WIKIJS），创建完成后页面提示成功，软件商店也有应用已经安装完成的提示，但却是关闭的，点击启用后提示

`服务内部错误: stderr: service "wiki-AI8V" has no container to start`

打开容器界面管理docker容器，发现没有新建有关于这个应用的docker容器

![image](https://github.com/1Panel-dev/1Panel/assets/48477757/023c951e-3d80-455c-ae5c-b6c8d162fcc7)

![image](https://github.com/1Panel-dev/1Panel/assets/48477757/62ccbffb-815c-405a-bd1c-4ad00e235c85)

![image](https://github.com/1Panel-dev/1Panel/assets/48477757/623d20bf-aa52-4c62-a3a1-cbc1d4d9322a)

### 重现步骤

新建站点->一键部署，勾选新装应用，安装wikijs，填写相关信息后新建即可

### 期待的正确结果

容器成功创建

**Comment by zhengkunwang223** [comment]
您好，尝试重建应用试试

**Comment by wanghe-fit2cloud** [comment]
v1.2.3 版本已发布，建议将 1Panel 升级至最新版本。
还可以设置镜像加速器，[参考文档](https://1panel.cn/docs/user_manual/containers/setting/)
