### ISSUE TITLE
[数据库相关的问题]

### ISSUE THREAD

**Issue by OSNewbie** [1Panel-dev/1Panel#1039]
### 请描述您的问题

MySQL 数据库连接超时问题，再安装新的应用，也会出现这种情况，创建新的数据库，老是显示连接超时，请检查数据库容器，我重启也没用啊，停止启动也一样，希望能彻底解决这个问题，我不知道怎么解决，所以问一下到底怎么办？

**Comment by zhengkunwang223** [comment]
> ### 请描述您的问题
> 
> MySQL 数据库连接超时问题，再安装新的应用，也会出现这种情况，创建新的数据库，老是显示连接超时，请检查数据库容器，我重启也没用啊，停止启动也一样，希望能彻底解决这个问题，我不知道怎么解决，所以问一下到底怎么办？

可能是因为网络原因导致创建数据库命令执行超时，下个小版本会适当优化超时时间，下周发版，到时候可以试一下

**Comment by OSNewbie** [comment]
后续这个容器日志功能，之后可以出一个分享的功能，就是通过生成一个链接，然后别人访问查看一下日志，以便大家能尽快的解决问题，因为复制粘贴那个代码字数有限，粘贴的话很卡， 嗯，数据库超时，这个问题，很让我头疼，我想问下，可以做些哪些设置，反正是在
数据库设置，性能调整那里，我的服务器配置，2G内存1核心40g硬盘 带宽未知，应该是共享带宽，

**Comment by OSNewbie** [comment]
还有一个问题，通过应用商店安装，应用创建的数据库，你再去数据库那边看，是找不到那个通过安装应用的数据库啊，就是没显示，我也不知道什么原因

**Comment by OSNewbie** [comment]
我这个不是连接超时，是执行超时，，啊，头疼一直这样，没法创建数据库

**Comment by OSNewbie** [comment]
啊，好像可能是，因为，已安装应用那里数据库，那里没有点击同步，优化一下安装应用时创建数据库执行超时的问题，还有就是有个提示，创建数据库，但是执行超时之后再点几次，它显示数据库已存在，但是我去数据库那里看了，没有的，嗯，这个提示可能会有点误导
