### ISSUE TITLE
希望添加 mysql5.5

### ISSUE THREAD

**Issue by Alexzzz2008** [1Panel-dev/1Panel#1040]
### 1Panel 版本

1.22

### 请描述您的需求或者改进建议

希望添加 mysql5.5   为了低配置的机器能用上  5.7 内存太高 不适合低配的机器

感谢

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，MySQL 5.6 这个版本我们会在 1Panel 后续发布的版本中支持。

**Comment by wanghe-fit2cloud** [comment]
中短期内我们不会考虑在应用商店中支持 MySQL 5.5，望理解！
不过你可以将自建 MySQL 5.5 服务通过添加远程数据库的方式添加的 1Panel 数据库菜单。
