### ISSUE TITLE
[BUG]不知道这个文件编辑窗口算不算是BUG,还是个别情况

### ISSUE THREAD

**Issue by Alexzzz2008** [1Panel-dev/1Panel#1042]
### 1Panel 版本

1.22

### 问题描述

1,打开文件,编辑的时候  窗口的位置 偏下, 不能显示  确定 按钮, 需要拖拽窗口,不太方便

2,  文件管理 没有剪切功能.

![QQ截图20230514223541](https://github.com/1Panel-dev/1Panel/assets/40814658/884342c9-b535-4bf8-ae29-44727cf4b518)

### 重现步骤

点击 文件后面的打开.

**Comment by Alexzzz2008** [comment]
我测试了一下 只是首屏没有显示完整,要 拖拉右边的窗口滚动条

**Comment by wanghe-fit2cloud** [comment]
> 我测试了一下 只是首屏没有显示完整,要 拖拉右边的窗口滚动条

编辑文件时不能显示 确定 按钮的问题，我们会在下个版本修复。

**Comment by wanghe-fit2cloud** [comment]
文件列表中，有提供移动（剪切）按钮。
<img width="798" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/f875601b-8803-4025-8120-7c1857c54fc2">

**Comment by wanghe-fit2cloud** [comment]
v1.2.4 版本已发布。
