### ISSUE TITLE
[FEATURE]国产操作系统、国产数据库和离线环境支持。

### ISSUE THREAD

**Issue by Rehoni** [1Panel-dev/1Panel#1044]
### 1Panel 版本

v1.2.2

### 请描述您的需求或者改进建议

请问对离线环境/非公网环境支持如何（比如应用商店）？
请问对国产操作系统（凝思、麒麟）、国产数据库（达梦、金仓）的支持如何？

**Comment by zhengkunwang223** [comment]
您好 现在不支持离线环境
国产操作系统和数据库没有做适配

**Comment by u2young** [comment]
这些国产软件很多都不是开源的  得联系他们才能安装  为何还考虑用这种软件处理

**Comment by wanghe-fit2cloud** [comment]
如果是docker 安装失败，这种情况就需要先手动安装好 docker 后再来运行 1Panel 在线安装脚本了。

> 针对不开源的软件，我们目前还不能主动适配。
