### ISSUE TITLE
[FEATURE]有计划做api文档嘛

### ISSUE THREAD

**Issue by Drizzle365** [1Panel-dev/1Panel#1046]
### 1Panel 版本

1.2

### 请描述您的需求或者改进建议

官方打算做面板的的api的文档说明嘛，感觉这个功能很不错，这样我们可以自己去集成面板的功能制作一些第三方的前端

### 请描述你建议的实现方案

类似宝塔的做api密钥，但是bt的功能还是很不完善的只有基础的信息获取和站点数据库ftp的配置，1panel官方可以做一个全套功能的api实现和文档说明

**Comment by zhengkunwang223** [comment]
您好 现在还没有 api 密钥的功能，但是已经在计划中 
api 文档可以访问  IP:端口/1panel/swagger/index.html 地址查看
