### ISSUE TITLE
[BUG]更新到v1.2.2版本导致MFA 认证失败

### ISSUE THREAD

**Issue by davidheartdev** [1Panel-dev/1Panel#1048]
### 1Panel 版本

v1.2.2

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/66203320/18ea2679-b8df-4c61-a4ad-29161d3a6917)

### 重现步骤

1、更新v1.2.2版本
2、重新登录
3、提示：错误的验证信息，请重试

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，可以到面板设置中同步一下服务器时间，然后再试一下 MFA 登录。
或者可以到主机 - 终端，输入命令来取消两步验证
```shell
1pctl reset-mfa
```

**Comment by davidheartdev** [comment]
服务器时间是对的，更新之前都可以的，现在只能先关闭 mfa

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布，麻烦升级到最新版本再试一下上述问题（我们在 v1.3.0 版本中没有复现该问题）。
