### ISSUE TITLE
[BUG]文件搜索搜不到文件

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#1049]
### 1Panel 版本

1.2.3

### 问题描述

在文件的搜索文件时，搜不到文件，只能搜到带关键词的文件夹？
例如下面截图：明确openresty目录下有docker-compose.yaml 但是搜docker时未出现文件。
![image](https://github.com/1Panel-dev/1Panel/assets/19621032/c223fe14-1395-4d14-8c06-5ee2f419ba86)
![image](https://github.com/1Panel-dev/1Panel/assets/19621032/72a7578a-fec3-4008-ab87-e770c34a4126)

试了其他目录都没文件出现，都是文件夹

### 重现步骤

1

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本修复这个问题。

**Comment by zhengkunwang223** [comment]
选择包含子目录搜索时 可以使用 *name 等通配符来进行模糊查询 后续我们会默认模糊查询

**Comment by wanghe-fit2cloud** [comment]
v1.2.4 版本已发布。
