### ISSUE TITLE
[FEATURE]希望有个权限能够自己选择是否要装在容器

### ISSUE THREAD

**Issue by jdnjk** [1Panel-dev/1Panel#1050]
### 1Panel 版本

1.23

### 请描述您的需求或者改进建议

希望有个权限能自己选择是否要安装容器里，而不是强制安装在容器里，在一些情况下docker在ubuntu安装时附带，在安装时没有检查到，重新apt install docker才正常检测

### 请描述你建议的实现方案

点击安装时弹出窗口选择

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，您反馈的是在应用商店安装应用时，可以选择是否容器化安装吗？

**Comment by jdnjk** [comment]
> 感谢反馈，您反馈的是在应用商店安装应用时，可以选择是否容器化安装吗？
是

**Comment by zhengkunwang223** [comment]
> > 感谢反馈，您反馈的是在应用商店安装应用时，可以选择是否容器化安装吗？
> > 是

您好 容器化是我们的根本 暂不考虑其他方式安装应用
