### ISSUE TITLE
[FEATURE]安装的应用可以直接绑定域名

### ISSUE THREAD

**Issue by xinyihl** [1Panel-dev/1Panel#1051]
### 1Panel 版本

1.2.3

### 请描述您的需求或者改进建议

希望应用商店安装的应用可以直接绑定域名，现在的版本想通过相应域名访问需要反向代理

**Comment by zhengkunwang223** [comment]
您好 您的意思是创建应用可以关联创建一个反向代理网站吗

**Comment by xinyihl** [comment]
extra_hosts配置项
https://docs.docker.com/compose/compose-file/compose-file-v2/

**Comment by xinyihl** [comment]
可以这么理解，当然有别的方式当然更好
