### ISSUE TITLE
[FEATURE]请问能否监控k8s集群，以及k8s集群中的mysql、redis、mq等各种信息，类似于prometheus+grafana那种形式？

### ISSUE THREAD

**Issue by cfy3133** [1Panel-dev/1Panel#1052]
### 1Panel 版本

1.2.3

### 请描述您的需求或者改进建议

请问能否监控k8s集群，以及k8s集群中的mysql、redis、mq等各种信息，类似于prometheus+grafana那种形式？

**Comment by maninhill** [comment]
感谢，这个需求和项目定位不太相符，中短期没有支持计划。
