### ISSUE TITLE
网站部署之后重启服务器容器开启失败

### ISSUE THREAD

**Issue by LucasStudioLeo** [1Panel-dev/1Panel#1053]
### 请描述您的问题

网站有关容器重启之后一直无法运行，提示异常并且没有办法在软件商店重新安装，提示关联网站，但是无法进入页面删除，死循环

**Comment by zhengkunwang223** [comment]
贴一下错误截图

**Comment by LucasStudioLeo** [comment]
您好，感谢回复，问题已经在重装系统后得到解决，就是仍然不知道当时出现问题是为啥
