### ISSUE TITLE
[BUG]部分目录扫不出来（我也不知道是不是bug还是我自己问题

### ISSUE THREAD

**Issue by TomChicken-on-github** [1Panel-dev/1Panel#1054]
### 联系方式

qq：2674407845 Tom_Chicken

### 1Panel 版本

1.2.3

### 问题描述

部分目录扫不出来

https://github.com/1Panel-dev/1Panel/assets/98439096/637619e6-1309-45f2-9710-b2de0ead0c89

![A561996A-44D5-449B-9B60-2A062FF69E94](https://github.com/1Panel-dev/1Panel/assets/98439096/3435a1c5-b613-4c84-83e9-2c42e0ecc423)

![74C1396A-72BB-4530-966B-EB3376097118](https://github.com/1Panel-dev/1Panel/assets/98439096/adc6d0a5-27de-4de8-b95b-394a46f050fc)

**Comment by TomChicken-on-github** [comment]
ssh连上去扫的出来这个目录

**Comment by TomChicken-on-github** [comment]
![58017735-3672-4394-84C2-86C782644FCF](https://github.com/1Panel-dev/1Panel/assets/98439096/e2906fae-413c-42f7-9903-061d5a257e80)

**Comment by TomChicken-on-github** [comment]
sftp也扫的出来
![Uploading F0746502-E395-4181-B9A6-397321BC5253.png…]()

**Comment by zhengkunwang223** [comment]
什么操作系统和版本？

**Comment by TomChicken-on-github** [comment]
debian root权限
1.2.3
而且很玄学，我ipad和电脑上面板都扫不出来，ftp和ssh连上去都有，我让山东朋友进面板倒是扫得出

**Comment by zhengkunwang223** [comment]
> debian root权限 1.2.3 而且很玄学，我ipad和电脑上面板都扫不出来，ftp和ssh连上去都有，我让山东朋友进面板倒是扫得出

是不是浏览器开了什么插件？

**Comment by TomChicken-on-github** [comment]
ipad的浏览器是没法开插件的

**Comment by TomChicken-on-github** [comment]
面板连报错日志都没

**Comment by zhengkunwang223** [comment]
可以去微信群加一下我 我远程看一下
