### ISSUE TITLE
[QUESTION]1Panel是准备做 Docker 面板还是 Linux 面板呢？

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#1055]
### 请描述您的问题

还是有点懵，对于应用端我觉得靠docker实现，这样对系统侵入少，我赞成。
但是目前这些应用只是docker现成项目，除了openresty，php等环境外，其他并不能称之为linux面板功能吧
如我之前在群里所言
![image](https://github.com/1Panel-dev/1Panel/assets/19621032/f6066d03-892c-4c33-bf2a-dcec6b37c971)
实在是缺少linux面板所需要的一些基础系统管理的插件，应用商店这些如 @hhun 所言大多数是充数的，系统可视化管理上绝大多数场景依旧离不开bt，目前1p≈阉割portainer+openresty
![image](https://github.com/1Panel-dev/1Panel/assets/19621032/4819b5a6-d080-41ab-ba05-38dac6916c94)

我还是希望1p朝着linux面板做的，至少倒逼着bt现在也做了不少改变了

**Comment by wanghe-fit2cloud** [comment]
感谢你的反馈。由于 1Panel 刚刚发布不久，确实缺少一些 Linux 系统管理插件，但我们会持续迭代几个版本，逐步完善功能。
如果在使用过程中有需求或遇到任何问题，请随时向我们反馈。我们将会不断改进 1Panel，使其功能日益强大。

**Comment by Felmon** [comment]
> 感谢你的反馈。由于 1Panel 刚刚发布不久，确实缺少一些 Linux 系统管理插件，但我们会持续迭代几个版本，逐步完善功能。 如果在使用过程中有需求或遇到任何问题，请随时向我们反馈。我们将会不断改进 1Panel，使其功能日益强大。

假如确实是往linux面板方向发展的话，linux系统管理插件优先级我觉得可以比其他都高。应用商店那些app一旦：基础搭好➡用户增多➡放开审核➡大批的应用会自觉适配进来的(like [tailchat ](https://github.com/1Panel-dev/appstore/pull/89))，那些都是不需要1p开发团队花精力维护的，这样才是健康生态

linux基础没法满足的话，大多数用户就都还是观望，最多双持或者小鸡试用，不会生产采用的，参与开源投入也便是空谈

做面板该做的事吧，docker商店不值得：[runtipi](https://github.com/meienberger/runtipi)   [osa](https://www.opensourcealternative.to/)

看好1p的未来

**Comment by zhengkunwang223** [comment]
> osa

应用商店主要是方便用户 安装 卸载 备份 升级 等操作 ，我们在设计的时候也参考过 runtipi ，我们的容器功能也参考了 portainer，都是必不可少的部分  
应用商店在 v1.3 重构之后，重点会放在 Linux 功能和网站功能上   
感谢建议

**Comment by maninhill** [comment]
一个字：干
三个字：加快干

**Comment by CleMooling** [comment]
#1088 我个人是非常不想使用docker环境，对配置低的机子太不友好了。

**Comment by CleMooling** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/93636342/3165ffcb-2790-4a68-af33-a8bcfece590c)
真是太痛啦

**Comment by Felmon** [comment]
> ![image](https://user-images.githubusercontent.com/93636342/239502112-3165ffcb-2790-4a68-af33-a8bcfece590c.png) 真是太痛啦

换低版本的php吧  php8不太适合低配置机

**Comment by deep-project** [comment]
哈哈哈，你这个问题我也挺有感触的，正所谓成也docker败也docker，如果太多的工具对母系统侵入太多，就缺少容器那味儿了，不侵入，有些功能又不好实现，哎

**Comment by cddqssc** [comment]
同感，目前就是阉割版docker面板，期待后续发展
