### ISSUE TITLE
[FEATURE]希望增加可以连接docker内的redis或者mysql，即 支持篇日志连接远程数据库的功能，现在只能连接内建的

### ISSUE THREAD

**Issue by YMingPro** [1Panel-dev/1Panel#1056]
### 1Panel 版本

v1.2.3

### 请描述您的需求或者改进建议

希望增加可以连接docker内的redis或者mysql，即 支持篇日志连接远程数据库的功能，现在只能连接内建的

**Comment by YMingPro** [comment]
而且希望可以增加对纯nginx的支持

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持添加远程 MySQL 数据库。

**Comment by wanghe-fit2cloud** [comment]
> 而且希望可以增加对纯nginx的支持

这个功能，我们在中短期还没有支持计划，望理解。

**Comment by ssongliu** [comment]
感谢支持！v1.5.1 版本已经支持远程数据库功能，请更新后体验！
