### ISSUE TITLE
[QUESTION]Flarum应用默认安装后打开网页进不去报错

### ISSUE THREAD

**Issue by backunderstar** [1Panel-dev/1Panel#1058]
### 请描述您的问题

![I%UTC((1K_C{GMXW7}T S3O](https://github.com/1Panel-dev/1Panel/assets/89375248/14178185-a833-4507-8753-83c69875f138)
使用面板应用商店默认安装Flarum，除了应用名称自定义外没有改任何配置。
安装完后网页无论是IP:端口，还是反代之后通过域名访问，都会报如图所示错误。
Something went wrong while trying to load the full version of this site. Try hard-refreshing this page to fix the error.
通过官方仓库、论坛、搜索，找到相似问题（自己浏览器问题），但是更换浏览器等方法均无法解决。
日志看起来没有内部报错，只有timeout，如下：
![J5RZZ37D1JMX34OJG )U($1](https://github.com/1Panel-dev/1Panel/assets/89375248/52a62411-db83-4b5e-a38f-df3a20be80c9)

后面用别的镜像（https://hub.docker.com/r/mondedie/flarum/tags）+mariadb，参照部署教程：https://blog.laoda.de/archives/docker-compose-install-flarum 后，**可以非常正常、正确地进入网页**。

后又更换服务器进行测试，仅自定义名称，未更改其他项，通过ip端口访问，仍有相同问题，故来寻求帮助，本人不知是否为个人问题，还是操作配置错误，还是如何。

希望能得到指点。

**Comment by gitzaai** [comment]
同样的问题，看来是镜像有问题
![Snipaste_2023-05-16_23-03-10.jpg](https://cdnjson.com/images/2023/05/16/Snipaste_2023-05-16_23-03-10.jpg)

**Comment by wanghe-fit2cloud** [comment]
删除应用后重新安装，然后将浏览器访问 1Panel 服务的 IP 设置为本机 IP。

**Comment by zhengkunwang223** [comment]
Flarum 配置反向代理访问暂时有问题 我们已复现 正在修复

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。

**Comment by dogeow** [comment]
现在1.7版本了，怎么还是碰到了

**Comment by gitzaai** [comment]
> 现在1.7版本了，怎么还是碰到了

浏览器地址要与config.php文件的url一致

**Comment by liguiqi** [comment]
Flarum 1.85版本，问题依旧

**Comment by liguiqi** [comment]
> Flarum 1.85版本，问题依旧

将安装页面的外部访问地址，localhost改成服务器IP就可以正常登录

**Comment by dogeow** [comment]
> 一致

设计可以设计好一些。
