### ISSUE TITLE
[FEATURE]应用商店安装应用时显示详细安装进度

### ISSUE THREAD

**Issue by zonglin-hub** [1Panel-dev/1Panel#1059]
### 1Panel 版本

dev

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/87891147/6675617a-1cb9-4ae4-9e86-936736c439fe)
详细安装进度，

**Comment by wanghe-fit2cloud** [comment]
安装中说明 1Panel 服务器正在自动拉取镜像，你可以进入 主机 - 终端 菜单后，执行命令手动拉取 mysql:8.0.30 镜像，确认是否会出现超时的情况。
```shell
docker pull mysql:8.0.30
```

**Comment by zonglin-hub** [comment]
ok

**Comment by wanghe-fit2cloud** [comment]
重复 issue #785
