### ISSUE TITLE
[FEATURE]希望能够支持对GOweb应用的监听跟一键配置

### ISSUE THREAD

**Issue by g-mero** [1Panel-dev/1Panel#1061]
### 1Panel 版本

1.2.3

### 请描述您的需求或者改进建议

之前用宝塔有这个功能，能够很轻松的配置go应用，设置好应用的端口，就能一键配置反代跟监听运行，这样会方便很多，希望以后能有这个功能。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持添加 Go 项目。

**Comment by wanghe-fit2cloud** [comment]
可以考虑通过 `工具箱` - `进程守护` 功能来管理 Golang 二进制服务。

运行环境需求的讨论，统一汇总到该 issue #748
