### ISSUE TITLE
php运行环境的用户.用户组?

### ISSUE THREAD

**Issue by Alexzzz2008** [1Panel-dev/1Panel#1063]
### 请描述您的问题

运行用户  现在默认是1000 和 1000

文件列表显示 root  和 root   文件权限 0755 

但是WordPress的后台显示文件没有写入权限,  安装升级插件 都不支持写入

这个权限到底要怎么改?    还是要修改用户和用户组??

**Comment by zhengkunwang223** [comment]
网站设置-网站目录-用户/用户组那 点保存

**Comment by Alexzzz2008** [comment]
> 网站设置-网站目录-用户/用户组那 点保存

新建的站点,必须去点一次保存. 才可以吗

**Comment by zhengkunwang223** [comment]
> > 网站设置-网站目录-用户/用户组那 点保存
> 
> 新建的站点,必须去点一次保存. 才可以吗

是的 因为创建网站之后 上传 PHP 文件的默认权限我们不清楚 所以需要改一下
