### ISSUE TITLE
[FEATURE] 插件机制支持

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#1069]
### 1Panel 版本

v1.2.3

### 请描述您的需求或者改进建议

什么时候能提供插件化机制的支持，部分功能能够以插件的形式进行提供

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，目前您可以以提交 PR 的形式来上传应用到应用商店，[参考教程](https://github.com/1Panel-dev/appstore)

**Comment by mx2913** [comment]
> 感谢反馈，目前您可以以提交 PR 的形式来上传应用到应用商店，[参考教程](https://github.com/1Panel-dev/appstore)

不是这个意思，插件和商店的差别还是有的，商店的是独立应用，插件是面板功能的补充，比如新增一个面板的 Google Drive 备份

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈，目前您可以以提交 PR 的形式来上传应用到应用商店，[参考教程](https://github.com/1Panel-dev/appstore)
> 
> 不是这个意思，插件和商店的差别还是有的，商店的是独立应用，插件是面板功能的补充，比如新增一个面板的 Google Drive 备份

感谢反馈，我们会在大版本更新的时候考虑增加插件机制。

**Comment by wanghe-fit2cloud** [comment]
插件机制等相关需求的讨论，统一汇总到该 issue #1599
