### ISSUE TITLE
[FEATURE]是否可以将云服务商提供的数据库注册到1Panel中？

### ISSUE THREAD

**Issue by Tudongye** [1Panel-dev/1Panel#1071]
### 1Panel 版本

v1.2.3

### 请描述您的需求或者改进建议

就个人而言，对数据库最重要的是需求数据不丢失。在这方面云服务商提供的数据库服务显然有着更大的优势，1Panel当前的“数据库”资源只支持本地创建的Mysql和redis，并且1Panel的很多功能都依赖”数据库“资源。在后续开发中是否可以将云服务商或第三方的数据库服务注册到1Panel的”数据库“资源呢？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持添加远程 MySQL 数据库。

**Comment by ssongliu** [comment]
感谢支持！v1.5.1 版本已经支持远程数据库功能，请更新后体验！
