### ISSUE TITLE
[FEATURE]自己新建的数据，在1Panel中没有展示

### ISSUE THREAD

**Issue by BonjourL** [1Panel-dev/1Panel#1074]
### 1Panel 版本

v1.2.3

### 请描述您的需求或者改进建议

先在1Panel 安装mysql ,远程连接后，自己新建数据库没有在1Panel展示

### 请描述你建议的实现方案

先在1Panel 安装mysql ,远程连接后，自己新建数据库应该在1Panel展示

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，需要在 1Panel 数据库菜单创建数据库。

**Comment by ssongliu** [comment]
感谢支持！ v1.5.1 版本已经支持远程数据库，请更新后体验。
