### ISSUE TITLE
[BUG]1Panel 服务启动出错

### ISSUE THREAD

**Issue by tongsh6** [1Panel-dev/1Panel#1078]
### 联系方式

tongsh6@126.com

### 1Panel 版本

v1.2.3

### 问题描述

[1Panel Log]: 配置 1Panel Service 
Created symlink /etc/systemd/system/multi-user.target.wants/1panel.service → /etc/systemd/system/1panel.service.
[1Panel Log]: 启动 1Panel 服务 
[1Panel Log]: 1Panel 服务启动出错! 

May 18 10:31:24 vultr.guest systemd[1]: 1panel.service: Failed with result 'core-dump'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit 1panel.service has entered the 'failed' state with result 'core-dump'.
May 18 10:31:29 vultr.guest systemd[1]: 1panel.service: Scheduled restart job, restart counter is at 71.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ Automatic restarting of the unit 1panel.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
May 18 10:31:29 vultr.guest systemd[1]: Stopped 1Panel, a modern open source linux panel.
░░ Subject: A stop job for unit 1panel.service has finished
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A stop job for unit 1panel.service has finished.
░░ 
░░ The job identifier is 6927 and the job result is done.
May 18 10:31:29 vultr.guest systemd[1]: Started 1Panel, a modern open source linux panel.
░░ Subject: A start job for unit 1panel.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit 1panel.service has finished successfully.
░░ 
░░ The job identifier is 6927.
May 18 10:31:29 vultr.guest systemd[1]: 1panel.service: Main process exited, code=dumped, status=11/SEGV
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ An ExecStart= process belonging to unit 1panel.service has exited.
░░ 
░░ The process' exit code is 'dumped' and its exit status is 11.
May 18 10:31:29 vultr.guest systemd[1]: 1panel.service: Failed with result 'core-dump'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit 1panel.service has entered the 'failed' state with result 'core-dump'.
May 18 10:31:35 vultr.guest systemd[1]: 1panel.service: Scheduled restart job, restart counter is at 72.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ Automatic restarting of the unit 1panel.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
May 18 10:31:35 vultr.guest systemd[1]: Stopped 1Panel, a modern open source linux panel.
░░ Subject: A stop job for unit 1panel.service has finished
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A stop job for unit 1panel.service has finished.
░░ 
░░ The job identifier is 7011 and the job result is done.
May 18 10:31:35 vultr.guest systemd[1]: Started 1Panel, a modern open source linux panel.
░░ Subject: A start job for unit 1panel.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit 1panel.service has finished successfully.
░░ 
░░ The job identifier is 7011.
May 18 10:31:35 vultr.guest systemd[1]: 1panel.service: Main process exited, code=dumped, status=11/SEGV
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ An ExecStart= process belonging to unit 1panel.service has exited.
░░ 
░░ The process' exit code is 'dumped' and its exit status is 11.
May 18 10:31:35 vultr.guest systemd[1]: 1panel.service: Failed with result 'core-dump'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit 1panel.service has entered the 'failed' state with result 'core-dump'.

### 重现步骤

curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sh quick_start.sh

**Comment by tongsh6** [comment]
操作系统 
CentOS Stream release 9

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。我刚在阿里云申请服务器，成功运行一键安装脚本，没有复现上述问题。
请问你的服务器是在哪里申请的，我复现一下问题。

**Comment by tongsh6** [comment]
https://www.vultr.com/

**Comment by wanghe-fit2cloud** [comment]
> https://www.vultr.com/

麻烦进微信交流群，添加一下好友。
