### ISSUE TITLE
[QUESTION]启用安全入口和auth_basic后，无法进入后台

### ISSUE THREAD

**Issue by gitzaai** [1Panel-dev/1Panel#1082]
### 请描述您的问题

当我开启了安全入口登录，并把1panel反代到一个1panel.example.com域名上，然后开启auth_basic密码功能。
当我打开1panel.example.com/comein，输入auth_basic账号密码后，在页面登入1panel账号，页面跳转一下又返回到这个1panel登入页面。
不知道是不是无法同时启用这2个功能.
请问这个问题怎么解决，恢复正常
Thanks!

报错截图：
![Snipaste_2023-05-19_11-09-41.jpg](https://cdnjson.com/images/2023/05/19/Snipaste_2023-05-19_11-09-41.jpg)

**Comment by zhengkunwang223** [comment]
> ### 请描述您的问题
> 当我开启了安全入口登录，并把1panel反代到一个1panel.example.com域名上，然后开启auth_basic密码功能。 当我打开1panel.example.com/comein，输入auth_basic账号密码后，在页面登入1panel账号，页面跳转一下又返回到这个1panel登入页面。 不知道是不是无法同时启用这2个功能. 请问这个问题怎么解决，恢复正常 Thanks!
> 
> 报错截图： ![Snipaste_2023-05-19_11-09-41.jpg](https://camo.githubusercontent.com/5b962c3875ab18014529faa3e255add43a3f7a26f0e40a2ecda056a94f6091eb/68747470733a2f2f63646e6a736f6e2e636f6d2f696d616765732f323032332f30352f31392f536e6970617374655f323032332d30352d31395f31312d30392d34312e6a7067)

换个浏览器试试 可能是浏览器的原因

**Comment by gitzaai** [comment]
> > ### 请描述您的问题
> > 当我开启了安全入口登录，并把1panel反代到一个1panel.example.com域名上，然后开启auth_basic密码功能。 当我打开1panel.example.com/comein，输入auth_basic账号密码后，在页面登入1panel账号，页面跳转一下又返回到这个1panel登入页面。 不知道是不是无法同时启用这2个功能. 请问这个问题怎么解决，恢复正常 Thanks!
> > 报错截图： ![Snipaste_2023-05-19_11-09-41.jpg](https://camo.githubusercontent.com/5b962c3875ab18014529faa3e255add43a3f7a26f0e40a2ecda056a94f6091eb/68747470733a2f2f63646e6a736f6e2e636f6d2f696d616765732f323032332f30352f31392f536e6970617374655f323032332d30352d31395f31312d30392d34312e6a7067)
> 
> 换个浏览器试试 可能是浏览器的原因

换了浏览器和换个电脑，重启服务器，还是一样问题，看到管理界面一闪而过又回到1panel登入页面，如此循环

**Comment by zhengkunwang223** [comment]
> > > ### 请描述您的问题
> > > 当我开启了安全入口登录，并把1panel反代到一个1panel.example.com域名上，然后开启auth_basic密码功能。 当我打开1panel.example.com/comein，输入auth_basic账号密码后，在页面登入1panel账号，页面跳转一下又返回到这个1panel登入页面。 不知道是不是无法同时启用这2个功能. 请问这个问题怎么解决，恢复正常 Thanks!
> > > 报错截图： ![Snipaste_2023-05-19_11-09-41.jpg](https://camo.githubusercontent.com/5b962c3875ab18014529faa3e255add43a3f7a26f0e40a2ecda056a94f6091eb/68747470733a2f2f63646e6a736f6e2e636f6d2f696d616765732f323032332f30352f31392f536e6970617374655f323032332d30352d31395f31312d30392d34312e6a7067)
> > 
> > 
> > 换个浏览器试试 可能是浏览器的原因
> 
> 换了浏览器和换个电脑，重启服务器，还是一样问题，看到管理界面一闪而过又回到1panel登入页面，如此循环

我们复现一下

**Comment by zhengkunwang223** [comment]
> auth_basic

问题已经复现 下个版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.2.4 版本已发布。
