### ISSUE TITLE
[FEATURE]希望增加宿主机环境的应用支持

### ISSUE THREAD

**Issue by CleMooling** [1Panel-dev/1Panel#1088]
### 1Panel 版本

1.2.3

### 请描述您的需求或者改进建议

希望能够搭建全局OpenResty环境直接运行在主机上，方便主机环境已有下的网站管理和迁移，现有的docker环境下迁移和配置主机已有的网站环境极为困难。
同时希望增加对主机环境下应用的支持与管理，docker环境对宿主机的资源占用可能会很高，在宿主机需要搭建多个项目的时候可能会面临内存不足等困境。

**Comment by zhengkunwang223** [comment]
1Panel 暂时只考虑 docker 部署软件和运行环境
