### ISSUE TITLE
[增加手机端适应]

### ISSUE THREAD

**Issue by jaychoubaby** [1Panel-dev/1Panel#1090]
### 1Panel 版本

v1.2.3

### 请描述您的需求或者改进建议

如题，希望增加手机端适应

**Comment by zhengkunwang223** [comment]
您好，手机端适配正在进行中，可能需要几个版本上线，请耐心等待

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。

**Comment by jaychoubaby** [comment]
> v1.3.0 版本已发布。

nice 已体验上，非常感谢
