### ISSUE TITLE
[QUESTION]如何给正在运行的容器添加映射端口

### ISSUE THREAD

**Issue by miaowuawa** [1Panel-dev/1Panel#1093]
### 请描述您的问题

试了网上的办法，改配置文件改了没有用，面板里也没有找到相关参数的设置，请问怎么做可以加？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，1Panel 也支持不了上述需求。
不过你可以将容器中的数据通过 docker cp 命令拷贝出来，再拷贝进新的容器中。
