### ISSUE TITLE
在面板中加入ftp功能

### ISSUE THREAD

**Issue by fpengziyang** [1Panel-dev/1Panel#1094]
### 1Panel 版本

当前运行版本：v1.2.3

### 请描述您的需求或者改进建议

能否在面板中加入ftp功能，这个功能还是有不少需求的！

### 请描述你建议的实现方案

希望做得比aapanel更好！

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持该需求。

**Comment by wanzhiyu** [comment]
确实，这个功能比较关键，传文件都靠ftp了，目前先用sftp凑活下，但是速度好慢

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布，ftp 教程请参考 [官方文档](https://1panel.cn/docs/user_manual/ftp/)
