### ISSUE TITLE
[QUESTION] docker swarm  支持吗？ 没有的话 有支持计划吗？

### ISSUE THREAD

**Issue by Jengro777** [1Panel-dev/1Panel#1096]
### 请描述您的问题

docker swarm  支持

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，docker swarm 我们中短期内应该不会支持，望理解。

**Comment by heartshare** [comment]
可以先應用商店中加上portainer 管理swarm嗎？

**Comment by wanghe-fit2cloud** [comment]
> 可以先應用商店中加上portainer 管理swarm嗎？

已支持。

**Comment by wanghe-fit2cloud** [comment]
> ### 请描述您的问题
> docker swarm 支持

暂无计划支持。
