### ISSUE TITLE
[FEATURE]docker 内文件编辑功能

### ISSUE THREAD

**Issue by justincnn** [1Panel-dev/1Panel#1097]
### 1Panel 版本

1.2.3

### 请描述您的需求或者改进建议

vps的文件管理功能，目前很完美，请问是否可以增加docker内的文件编辑功能，谢谢

具体位置如下：

![WX20230521-223354@2x.png](https://img1.imgtp.com/2023/05/21/mdw27IQr.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述需求我们会在后续版本中支持。

**Comment by justincnn** [comment]
> 感谢反馈，上述需求我们会在后续版本中支持。

感谢，一直盼望着，

**Comment by wanghe-fit2cloud** [comment]
重复 issue #523

**Comment by chmis8000** [comment]
没完成吧？ 为啥Close了？

**Comment by wanghe-fit2cloud** [comment]
> 没完成吧？ 为啥Close了？

重复 issue https://github.com/1Panel-dev/1Panel/issues/523

**Comment by longtianaowei** [comment]
这个功能实现了吗？
