### ISSUE TITLE
[QUESTION]无法创建PHP运行环境。

### ISSUE THREAD

**Issue by nsfw404** [1Panel-dev/1Panel#1101]
### 请描述您的问题

无法创建PHP

**Comment by nsfw404** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/38856864/8df1cab0-1e7d-4368-8e14-68fded023baa)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述错误是因为 1Panel 服务器不能正常拉取基础镜像导致的。
