### ISSUE TITLE
多个反向代理用同一个端口好像不支持[FEATURE]

### ISSUE THREAD

**Issue by itworkzhang** [1Panel-dev/1Panel#1103]
### 1Panel 版本

1.2.4

### 请描述您的需求或者改进建议

假设我有多个反向代理，端口一样，只是二级域名不同。这个怎么配置啊？

每次去配置，都提示端口被占用。
![image](https://github.com/1Panel-dev/1Panel/assets/42572628/cb8202bb-dda3-4b52-a955-3dc2c7d10d75)

**Comment by itworkzhang** [comment]
但是你去新增的时候，默认是80端口又是没问题的，我这创建了多个反向代理，子域名不同，端口都是默认的80是可以的。
但是如果将80修改为其他的。就不行了。

**Comment by zhengkunwang223** [comment]
您的问题是 多个子域名 代理同一个后端端口 openresty 的配置是 80 的情况下是可以的，但是换成其他端口 就不生效是吗

**Comment by itworkzhang** [comment]
> 
对 也不是不生效 是根本就不能换成相同的端口 提示端口已占用。  例如我配置了一个反向代理，域名为test1.main.com 端口为520.
配置第二个反向代理，域名为test2.main.com 端口为520.这是会提示端口被占用。

**Comment by zhengkunwang223** [comment]
> > 
> 
> 对 也不是不生效 是根本就不能换成相同的端口 提示端口已占用。 例如我配置了一个反向代理，域名为test1.main.com 端口为520. 配置第二个反向代理，域名为test2.main.com 端口为520.这是会提示端口被占用。

好的 我们复现一下这个问题

**Comment by wanghe-fit2cloud** [comment]
可以将 1Panel 升级到最新版本。
