### ISSUE TITLE
[ 1Panel 访问以及网站加载问题]

### ISSUE THREAD

**Issue by OSNewbie** [1Panel-dev/1Panel#1110]
### 1Panel 版本

v1.2.4

### 请描述您的需求或者改进建议

 希望可以增加一点docker 清理工具，可以放在那个应用商店，后续可能你们自行添加吧！，我不确定占用的有哪些，可能是日志或者一些没有用的存储卷啊之类的，尽量减少服务器占用达到访问流畅

目前这个问题存在:服务内部错误: Error response from daemon: No such image:
   我觉得不能蛮盲目删除，得知道存储卷对应的容器，不然删除了可能会丢数据就麻烦了，所以需要通过工具来分辨一下 日志文件我也不知道在哪里，所以我想问一下怎么删除？但不影响使用

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
v1.3 版本我们会支持清理容器日志、网站日志和容器镜像等需求。

**Comment by OSNewbie** [comment]
还有一个问题，就是那个申请证书报错那个问题怎么解决？，无论是DNS验证还是Http解析，他有时候会报错，不知道为什么

**Comment by wanghe-fit2cloud** [comment]
> 还有一个问题，就是那个申请证书报错那个问题怎么解决？，无论是DNS验证还是Http解析，他有时候会报错，不知道为什么

麻烦贴一下日志（面板日志菜单 - 系统日志）

**Comment by OSNewbie** [comment]
> > 还有一个问题，就是那个申请证书报错那个问题怎么解决？，无论是DNS验证还是Http解析，他有时候会报错，不知道为什么
> 
> 麻烦贴一下日志（面板日志菜单 - 系统日志）

好像可以了，应该是修复了这个问题

**Comment by OSNewbie** [comment]
还有就是保存证书第一次的话，为什么会有服务器内部错误的提示？我也不清楚这个问题，为什么会出现的频率很高？

**Comment by OSNewbie** [comment]
就是用域名https的时候，为什么要一定要带端口？ 可能跟那个安全入口路径有关吧

**Comment by OSNewbie** [comment]
为什么数据库和？hlao 占用有点高，数据库是70%的占用，halo 48%多的占用
  希望后续容器 有像数据库有这种性能调整的功能
 我就是觉得占用比较高，还有halo 访问比较慢，可能受带宽的影响，我希望halo是尽量优化 访问速度跟halo 1.6.1的版本差不多就行了 还是喜欢这种1.0版本的访问速度，

**Comment by zhengkunwang223** [comment]
> 为什么数据库和？hlao 占用有点高，数据库是70%的占用，halo 48%多的占用 希望后续容器 有像数据库有这种性能调整的功能 我就是觉得占用比较高，还有halo 访问比较慢，可能受带宽的影响，我希望halo是尽量优化 访问速度跟halo 1.6.1的版本差不多就行了 还是喜欢这种1.0版本的访问速度，

V1.3会增加应用的资源限制

**Comment by zhengkunwang223** [comment]
> 还有就是保存证书第一次的话，为什么会有服务器内部错误的提示？我也不清楚这个问题，为什么会出现的频率很高？

如果是保存网站证书 那么错误的原因是证书格式不对

**Comment by OSNewbie** [comment]
> > 还有就是保存证书第一次的话，为什么会有服务器内部错误的提示？我也不清楚这个问题，为什么会出现的频率很高？
> 
> 如果是保存网站证书 那么错误的原因是证书格式不对

不应该呀，我用的是自动申请证书呀，是就是那个DNS，申请下来，然后开启网站https保存证书的时候会出现这个内部错误的报错，保存第二次就没有任何问题显示保存成功

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
