### ISSUE TITLE
[BUG] WebSite Password Access

### ISSUE THREAD

**Issue by ttimochan** [1Panel-dev/1Panel#1113]
### 1Panel 版本

1.2.4

### 问题描述

I think the feature should be allowed to be enabled only after the user has configured the account and password, otherwise the empty account and password verification will confuse the user.

It leads to circular verification.

![image](https://github.com/1Panel-dev/1Panel/assets/91021824/ef7bd3bf-d3ef-42a8-bfb1-b3197b555932)

### 重现步骤

WebSite -> anyWebSite -> Password Access -> Enable(√)

### 期待的正确结果

Do not allow opening until the user has configured a user and password.

**Comment by wanghe-fit2cloud** [comment]
Thank you for your feedback, we will address the mentioned issues in future versions.

**Comment by wanghe-fit2cloud** [comment]
Version v1.3.0 has been released.
