### ISSUE TITLE
[FEATURE]端口设置的地方是否可以增加一个备注的地方

### ISSUE THREAD

**Issue by justincnn** [1Panel-dev/1Panel#1121]
### 1Panel 版本

1.2.3

### 请描述您的需求或者改进建议

在设置端口的界面是否可以增加一个备注或者说明的地方，
这样在回顾自己端口状态的时候，就不需要ssh查看，直接在1panel里面查询，提升效率

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述需求是要在防火墙菜单 - 端口规则列表增加备注信息吗？

**Comment by justincnn** [comment]
> 感谢反馈，上述需求是要在防火墙菜单 - 端口规则列表增加备注信息吗？

是的，最近开放端口多了，一看list，人瞬间崩溃

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈，上述需求是要在防火墙菜单 - 端口规则列表增加备注信息吗？
> 
> 是的，最近开放端口多了，一看list，人瞬间崩溃

好的，后续版本支持添加端口备注。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
