### ISSUE TITLE
同时创建多个站点会有问题，站点A配置中间件转发后会影响b站点的。导致b站点不正常。宝塔没这个问题期望修复

### ISSUE THREAD

**Issue by 1370339317** [1Panel-dev/1Panel#1122]
### 联系方式

1

### 1Panel 版本

没看，已经换了

### 问题描述

如题，建第二个站后就常卡死。面板都上不去。我不知道是1panel本身有bug还是 资源占用太高导致的。宝塔同样的内容，同样建俩站。CPU很低，内存占用40%、
1panel 长时间维持在内存占用80%以上，不清楚卡死和无响应是占用太高卡了还是有什么问题。无奈换回宝塔了。加油，再接再厉。希望1panel越来越好。

就三问题
1多个站点中间件有问题，互相影响了。A站的抓发正常，但是b站居然被A的转发影响了。
2资源占用高，不知道是不是容器的问题，但是确实高到用不了有点
3占用高后经常卡死连概览都刷不出来。不确定什么原因

### 重现步骤

1

### 期待的正确结果

1

### 相关日志输出

```shell
1
```

### 附加信息

1

**Comment by zhengkunwang223** [comment]
你的服务器是几C几G的？

**Comment by cyril-cheng** [comment]
你这啥都不贴出来，咋个分析问题？

**Comment by cyril-cheng** [comment]
有点离谱
