### ISSUE TITLE
[BUG]制作 PHP 运行环境镜像失败

### ISSUE THREAD

**Issue by OSNewbie** [1Panel-dev/1Panel#1130]
### 联系方式

wzry623090@gmail.com

### 1Panel 版本

v1.2.4

### 问题描述

docker 编译PHP运行环境拉取制作镜像出现错误，现在问题是7.0和8.0，还有5.0都反正就是制作镜像失败，不知道这是什么问题，

镜像 build 失败:failed to solve: php:7.4.33-fpm-alpine: failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://f1361db2.m.daocloud.io/v2/library/php/blobs/sha256:37edad271fae45db83e0506c50a87da66f54cbda29ce8d1197ad61d215def79c?ns=docker.io": dial tcp: lookup f1361db2.m.daocloud.io: Temporary failure in name resolution

### 重现步骤

暂时不行吧我只是猜测，需要测试，或者你可以尝试下创建运行环境，然后是否，制作镜像成功

**Comment by zhengkunwang223** [comment]
拉取镜像失败 检查网络和加速设置

**Comment by OSNewbie** [comment]
> 

> 拉取镜像失败 检查网络和加速设置
我怎么知道是什么原因？，我这边是一拉取镜像就失败，但是正常的拉取镜像是不会出现这种情况，唯独制作PHP镜像就会有这种情况，就是那个运行环境，那里创建那个运行环境，那里就出现这个拉取镜像失败的原因
 那你们倒是给个解决办法，让我试一下，我也不知道怎么办？

**Comment by wanghe-fit2cloud** [comment]
> > 
> 
> > 拉取镜像失败 检查网络和加速设置
> > 我怎么知道是什么原因？，我这边是一拉取镜像就失败，但是正常的拉取镜像是不会出现这种情况，唯独制作PHP镜像就会有这种情况，就是那个运行环境，那里创建那个运行环境，那里就出现这个拉取镜像失败的原因
> > 那你们倒是给个解决办法，让我试一下，我也不知道怎么办？

手动拉取一下日志中提到的基础镜像：
```shell
docker pull php:7.4.33-fpm-alpine
```

**Comment by OSNewbie** [comment]
> > > 
> > 
> > 
> > > 拉取镜像失败 检查网络和加速设置
> > > 我怎么知道是什么原因？，我这边是一拉取镜像就失败，但是正常的拉取镜像是不会出现这种情况，唯独制作PHP镜像就会有这种情况，就是那个运行环境，那里创建那个运行环境，那里就出现这个拉取镜像失败的原因
> > > 那你们倒是给个解决办法，让我试一下，我也不知道怎么办？
> 
> 手动拉取一下日志中提到的基础镜像：
> 
> ```shell
> docker pull php:7.4.33-fpm-alpine
> ```

没问题，镜像加速源的问题，我是设置了多个就没问题，嗯，清华，网易七牛，云

**Comment by OSNewbie** [comment]
嗯，或许可以在后续版本添加多个镜像加速源，嗯，目前的源只有你们那一个，不确，定是那个docker 限制了是什么原因？我也不懂
