### ISSUE TITLE
[BUG] 终端连接时，错误命令没有任何反应

### ISSUE THREAD

**Issue by heyzqq** [1Panel-dev/1Panel#1131]
### 1Panel 版本

v1.2.4

### 问题描述

使用错误命令连接一直都没有任何提示。

例如，容器只支持 `/bin/sh`，用 `/bin/bash` 连接时没有任何反应。

### 重现步骤

1. 点击容器的【终端】选项
2. 勾选【自定义】命令，输入任意不存在的命令，如 `hello`
3. 点击【连接】，页面会一直等待

### 期待的正确结果

连接容器时，希望命令执行错误能给个错误提示。

如果输入如 `ls` 立即退出的命令，是否可以自动断开连接？目前页面是连接状态。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，在测试环境中并没有复现上述问题，如下图：
<img width="755" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/79300f80-13da-49f0-8338-1166d2df4cea">

麻烦提供一下你的测试镜像，我们复现一下问题。

**Comment by heyzqq** [comment]
系统版本：
- 发行版本 centos-7.7.1908
- 内核版本 3.10.0-1062.4.1.el7.x86_64

软件版本：
- 1Panel 版本：v1.2.4，新装的，为面板设置 https 协议访问，不知道不知道有没有关系
- Docker 版本: 19.03.4


Dockerfile 就是使用 nginx 部署了个前端服务（事实上，其他容器也一样）：

```
FROM nginx:alpine

ENV TZ=Asia/Shanghai

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY ./index.html /usr/share/nginx/html

EXPOSE 80
```

任意命令 hello 无任何响应：

![image](https://github.com/1Panel-dev/1Panel/assets/47818994/77cbf545-e88e-44c3-b190-1143aee7dda3)



输入 ls 可以正常显示：

![image](https://github.com/1Panel-dev/1Panel/assets/47818994/35be1c9d-6d27-4f0b-8210-4a9b7712cd30)



@wanghe-fit2cloud

**Comment by wanghe-fit2cloud** [comment]
收到，我先在测试环境复现一下吧。
