### ISSUE TITLE
[FEATURE]文件回收站功能

### ISSUE THREAD

**Issue by xinyihl** [1Panel-dev/1Panel#1137]
### 1Panel 版本

1.2.4

### 请描述您的需求或者改进建议

文件管理功能的删除不应该直接删除，是不是应该提供一个回收站的功能，可以给一个开关是否开启回收站

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，文件回收站功能已经加入迭代计划，后续版本支持。

**Comment by wanghe-fit2cloud** [comment]
重复 #624

**Comment by reddloob** [comment]
> 感谢反馈，文件回收站功能已经加入迭代计划，后续版本支持。

1Panel 版本：
1.8.1

请描述您的需求或者改进建议：
回收站开关应该能够记忆开关状态，现在默认行为是未勾选“永久删除文件”，即使勾选了“永久删除文件”，下一次删除时也是未勾选的状态。
应该修改为“本次更改开关状态后删除文件，下一次删除文件时记住开关状态”。
![image](https://github.com/1Panel-dev/1Panel/assets/46004053/2825bcb1-9201-4ae2-a032-c8783d2b0e7a)
