### ISSUE TITLE
[SUGGESTION] 概览页面布局与功能

### ISSUE THREAD

**Issue by realzolo** [1Panel-dev/1Panel#1138]
### 1Panel 版本

1.2.4

### 请描述您的需求或者改进建议

概览页的这个推荐应用没有什么意义，已经安装过的应用还给我推荐真的没必要。建议增加一项“站点访问记录”功能，比如统计我的网站有多少IP访问，每日新增IP等。或者其他较有意义的功能都行。
<img width="1461" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/63219216/120cf074-0899-42d1-b858-57627eb4418a">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在中短期内不会考虑在概览页增加站点访问记录等内容。
