### ISSUE TITLE
[BUG]PHP所有版本安装ioncube无效

### ISSUE THREAD

**Issue by Mejux07** [1Panel-dev/1Panel#1150]
### 联系方式

mejux@qq.com

### 1Panel 版本

1.2.4

### 问题描述

PHP所有版本安装ioncube无效，按照官方教程来也无效

### 重现步骤

install php74
selected ioncube
save

### 期待的正确结果

网站内容正常显示

**Comment by zhengkunwang223** [comment]
好的 我们复现一下

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。

**Comment by Felmon** [comment]
我这边安装ioncube完重建应用也是无效   1panel 1.3.3 @wanghe-fit2cloud @zhengkunwang223 
![image](https://github.com/1Panel-dev/1Panel/assets/19621032/a2916d6d-f5e9-4671-a26e-27b25cbbab5c)
