### ISSUE TITLE
[FEATURE]希望可以使用域名访问面板

### ISSUE THREAD

**Issue by mfeng057** [1Panel-dev/1Panel#1155]
### 1Panel 版本

1.2.4

### 请描述您的需求或者改进建议

当前使用的是IP加端口的形式，希望可以使用域名访问面板

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，v1.3.0 版本将支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
当前版本你可以这样操作来支持绑定域名：
网站 -> 创建网站 -> 反向代理(反代1Panel服务)

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
