### ISSUE TITLE
[BUG] 网站直接启用密码访问会直接出现拦截域名请求

### ISSUE THREAD

**Issue by newcardriver** [1Panel-dev/1Panel#1157]
### 1Panel 版本

1.2.4

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/44741731/a4267de7-7ce7-4806-b331-3852bb891202)

在没有创建密码访问，但开启密码访问的时候，域名访问会出现拦截。

![image](https://github.com/1Panel-dev/1Panel/assets/44741731/aa0eb821-befa-438f-9bb0-14b0ab2f8937)

上图抹掉的是域名。

### 重现步骤

添加网站-》启用密码访问-》刷新配置好的域名反向代理。

### 期待的正确结果

在没有配置密码访问用户时，应该无法开启密码访问配置。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在 v1.3.0 版本完成上述优化。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
