### ISSUE TITLE
[QUESTION]创建PHP环境失败

### ISSUE THREAD

**Issue by ttwo22** [1Panel-dev/1Panel#1158]
### 请描述您的问题

环境：Debian 10
创建php环境的时候失败了，报错如下：
镜像 build 失败:failed to solve: process "/bin/sh -c apk --no-cache add tzdata && cp \"/usr/share/zoneinfo/$TZ\" /etc/localtime && echo \"$TZ\" > /etc/timezone" did not complete successfully: exit code: 1

**Comment by wanghe-fit2cloud** [comment]
1、容器菜单 - 配置页面，打开 iptables 开关
2、点击保存按钮，输入"立即重启"来重启 Docker
3、网站 - 运行环境页面，重新编辑 PHP 运行环境

**Comment by ttwo22** [comment]
> 
我都iptables一直都是开着的，我重启 Docker，重新创建PHP运行环境还是失败，
然后我尝试开启 IPv4转发功能, 并启用
/etc/sysctl.conf中增加net.ipv4.ip_forward=1, 然后重载文件sysctl -p
还是解决不了这个问题

**Comment by wanghe-fit2cloud** [comment]
查看一下配置文件：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/90bebccf-48c0-4b71-975e-382ec0055723)

**Comment by ttwo22** [comment]
> 
没有这个文件

**Comment by wanghe-fit2cloud** [comment]
进微信群吧，加我好友。

**Comment by ttwo22** [comment]
> 进微信群吧，加我好友。

进了，你是？

**Comment by wanghe-fit2cloud** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/299f5837-95e6-41c0-bd8b-ce002881f8a9)

**Comment by ttwo22** [comment]
问题解决了
