### ISSUE TITLE
[QUESTION]CDN设置443端口回源报502

### ISSUE THREAD

**Issue by Mejux07** [1Panel-dev/1Panel#1159]
CDN设置443端口回源报502，证书都是正确配置的

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，你可以尝试清理浏览器缓存或者无痕模式访问。

还可以参考一下这个 issues：#287，确认一下是不是同样的问题。

**Comment by Mejux07** [comment]
> 感谢反馈，你可以尝试清理浏览器缓存或者无痕模式访问。
> 
> 还可以参考一下这个 issues：#287，确认一下是不是同样的问题。

是差不多的问题
