### ISSUE TITLE
[FEATURE]webhook

### ISSUE THREAD

**Issue by livepu** [1Panel-dev/1Panel#1160]
### 1Panel 版本

1.2.4

### 请描述您的需求或者改进建议

希望有webhook功能。
这样的话，方便git同步，也可以通过Webhook控制防护墙等一些特殊操作。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复 #410

**Comment by livepu** [comment]
什么时候支持呢？

**Comment by wanghe-fit2cloud** [comment]
中短期内还没有计划支持，望理解。
