### ISSUE TITLE
[BUG]部署Halo时 超级管理员用户名大写字母会导致容器一直显示“重启中”。

### ISSUE THREAD

**Issue by Aciudrs** [1Panel-dev/1Panel#1161]
### 1Panel 版本

1.2.4版本

### 问题描述

部署Halo时 超级管理员用户名大写字母会导致容器一直显示“重启中”。

### 重现步骤

![IMG_0699](https://github.com/1Panel-dev/1Panel/assets/56188765/9eec868d-7524-4ae9-81d0-e61989ae0abf)
![IMG_0697](https://github.com/1Panel-dev/1Panel/assets/56188765/145d6796-c113-4040-9312-d55ea2bf5f56)
![e52085a1c2c7db09a86829d076fb61b2](https://github.com/1Panel-dev/1Panel/assets/56188765/2c3a40f2-7ff2-4211-97a2-17c72c5da0a4)

**Comment by zhengkunwang223** [comment]
好的，我们后续版本修复此问题

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
