### ISSUE TITLE
[QUESTION]无法获取应用商店列表

### ISSUE THREAD

**Issue by 2327972001** [1Panel-dev/1Panel#1163]
### 请描述您的问题

无法获取应用商店列表
版本：1.2.4
问题图片：https://s1.ax1x.com/2023/05/27/p9qRzyq.png

**Comment by 2327972001** [comment]
服务器归属地是香港

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，请问服务器是哪家云服务商？
1Panel 应用商店需要通过上述链接来下载应用，我们已经配置了 CDN 全球加速，绝大多数公有云服务器都可以访问。

**Comment by 2327972001** [comment]
> 感谢反馈，请问服务器是哪家云服务商？ 1Panel 应用商店需要通过上述链接来下载应用，我们已经配置了 CDN 全球加速，绝大多数公有云服务器都可以访问。

云服务器商家：http://www.boluoyun.com/

**Comment by yggcwx** [comment]
同样无法进入应用商店，郁闷。Cloudcone
