### ISSUE TITLE
[BUG] 创建php环境 请求超时

### ISSUE THREAD

**Issue by blblank** [1Panel-dev/1Panel#1164]
### 1Panel 版本

1.2.4

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/38033532/6b55f2bb-b56f-4fb8-a046-553b1fddc719)
![image](https://github.com/1Panel-dev/1Panel/assets/38033532/5b44dce4-5333-44a5-ba89-847dbbd446fe)
是我的硬件内存太低的关系吗?
我使用宝塔倒是能正常搭建 php 和 nginx 搭建完就是硬盘几乎没有空间了
所以我才选用 1Panel，但是没想到 无法创建php运行环境

### 重现步骤

无法创建php运行环境，一直提示请求超时

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，使用 512 MB 内存的服务器来构建 PHP 运行环境确实有些吃力，望理解。
