### ISSUE TITLE
[BUG]下载大文件时会出现超时情况

### ISSUE THREAD

**Issue by Muska-Ami** [1Panel-dev/1Panel#1165]
### 联系方式

mail@huahuo-cn.tk

### 1Panel 版本

1.2.4

### 问题描述

服务器位于香港，下载较大文件就会出现超时，小文件则正常

### 重现步骤

下载一个大文件

### 期待的正确结果

正常下载

### 附加信息

视频:
我向你分享了：VID_20230527_170222.mp4 链接：https://pan.ovome.icu/s/PrUa

**Comment by zhengkunwang223** [comment]
已知问题，下个版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
