### ISSUE TITLE
[FEATURE]个人使用的便捷性建议

### ISSUE THREAD

**Issue by swRains** [1Panel-dev/1Panel#1166]
### 1Panel 版本

v1.2.4

### 请描述您的需求或者改进建议

1、关于网站
（1）网站设置，新增域名这里，期望能够批量添加，虽然可以直接改配置文件，但这里能多个选择会更加方便。
（2）创建网站目前包含四个选项，默认是一键部署，但能从1panel一键部署的网站很少，大部分使用场景下都是静态网站或者反向代理，我认为顺序应该改为：静态网站（默认）、反向代理、运行环境、一键部署；
2、证书
（1）在证书页可以手动添加证书；
（2）泛域名ssl证书申请时常失败，我也没日志可以看；
（3）申请证书时显示日志；
3、docker
（1）docker可以像宝塔一样进入直接文件目录；
（2）docker状态可以在那一行启动、重启啥的，不然还得先勾选，再选择停止啥的。比如现在是名称 - 镜像 - 状态 ....  ，我期望能改成  名称 - 状态（按钮，可选择重启）- 镜像  -  容器目录 ... ；
（3）编排还是改成compose吧，我第一次用还愣了下神，没反应过来，或者说改成“模板”或“容器模板”；
（4）如果可以的话可以增加个修改容器配置文件的功能，这样就不用重新找docker run命令了。这个功能可能需要做个像群辉一样的ui界面会更好，可以修改挂载地址、映射端口之类的；
（5）目前大部分的1panel应用都是依托于docker，我认为一些环境还是不用docker会好点比如php、nginx；
（6）1panel添加的应用是以docker运行的，默认情况下应当隐藏或者放到另一页，这样容器页在观感上会好点，不然显得乱糟糟的，docker一多起来就不好找；
（7）添加容器名称排序、添加日期排序、占用排序等；
（8）集成watchtower，在每个docker后面添加一个滑动按钮，能够选择是否自动更新，然后能自定义更新检查时间，不然用户安装的watchtower会更新1panel应用，在应用大版本更新时有概率造成应用失效；
4、主机 - 文件
（1）期望能保留上次打开目录位置，不然每次打开都得从根目录一步一步翻；
（2）添加收藏或者书签，能够快速定位到想要去的目录；
（4）目录多窗口，在多文件编辑时能够方便对照；
5、面板cookies失效时间可自定义，或者添加可信设备，用mac或ip进行区分

目前我已经抛弃宝塔面板使用1Panel，不得不说1Panel的界面确实美观，使用体验也还行，我仅提出了以上的一些建议，能够提升我这类用户的使用体验，期望开发者能够将1Panel打造的越来越好。非常感谢！

**Comment by zhengkunwang223** [comment]
您好 感谢建议 
关于 “我认为一些环境还是不用docker会好点比如php、nginx” ，docker 是我们的基础，在中短期我们没有非容器化的打算
其他的需求大部分都很合理 我们会逐步优化
感谢您的信任 
后期我们完成您提的优化会关联此 issue，不会做的也会说明原因
欢迎您持续关注

**Comment by swRains** [comment]
另外，添加网站、docker等的确认按钮应当在右上角加一个，或者在编辑完设置后紧接着就得有确认按钮，当前版本设计的确认按钮距离操作区域太远，不符合设计逻辑。

**Comment by maninhill** [comment]
感谢这么用心的反馈，一起努力，让 1Panel 越来越好。

**Comment by johanlike** [comment]
本人小白，我也非常喜欢这个面板，但是在一些使用体验上和楼主一样的观点.同样的项目宝塔能配置成功，1panel暂时不行.这面板是好东西.希望后期能改进体验直至能完全替代宝塔.

**Comment by qrekkwijjtx54** [comment]
本人小白，我也非常喜欢这个面板，但是在一些使用体验上和楼主一样的观点.同样的项目宝塔能配置成功，1panel暂时不行.这面板是好东西.希望后期能改进体验直至能完全替代宝塔.

**Comment by maninhill** [comment]
我们会不断改进。大家也帮忙多提一些具体的问题和改进建议，我们改起来更快。

**Comment by zyyfit** [comment]
截止到1.8.0版本，1.1    2.1   3.7（部分）  3.8（部分）  4.1   4.2   已完成

**Comment by wanghe-fit2cloud** [comment]
1、关于网站
（2）创建网站目前包含四个选项，默认是一键部署，但能从1panel一键部署的网站很少，大部分使用场景下都是静态网站或者反向代理，我认为顺序应该改为：静态网站（默认）、反向代理、运行环境、一键部署；
3、docker
（3）编排还是改成compose吧，我第一次用还愣了下神，没反应过来，或者说改成“模板”或“容器模板”；
（6）1panel添加的应用是以docker运行的，默认情况下应当隐藏或者放到另一页，这样容器页在观感上会好点，不然显得乱糟糟的，docker一多起来就不好找；
（8）集成watchtower，在每个docker后面添加一个滑动按钮，能够选择是否自动更新，然后能自定义更新检查时间，不然用户安装的watchtower会更新1panel应用，在应用大版本更新时有概率造成应用失效；
4、主机 - 文件
（4）目录多窗口，在多文件编辑时能够方便对照；

> 截止到 v1.9.2 版本，上述功能还未实现。

**Comment by swRains** [comment]
> 1、关于网站 （2）创建网站目前包含四个选项，默认是一键部署，但能从1panel一键部署的网站很少，大部分使用场景下都是静态网站或者反向代理，我认为顺序应该改为：静态网站（默认）、反向代理、运行环境、一键部署； 3、docker （3）编排还是改成compose吧，我第一次用还愣了下神，没反应过来，或者说改成“模板”或“容器模板”； （6）1panel添加的应用是以docker运行的，默认情况下应当隐藏或者放到另一页，这样容器页在观感上会好点，不然显得乱糟糟的，docker一多起来就不好找； （8）集成watchtower，在每个docker后面添加一个滑动按钮，能够选择是否自动更新，然后能自定义更新检查时间，不然用户安装的watchtower会更新1panel应用，在应用大版本更新时有概率造成应用失效； 4、主机 - 文件 （4）目录多窗口，在多文件编辑时能够方便对照；
> 
> > 截止到 v1.9.2 版本，上述功能还未实现。

感谢各位开发大大的贡献！1Panel现在属实好用👍。
余下这些事实上现在看来并不是很重要，唯一可取的就是第（8）条的这个自动更新。我觉得这个东西可以用cron来实现，如果集成到watchtower的话会有点麻烦，watchtower区分是否更新得在docker run的时候打tag，这种的话或许用cron会更加灵活，还能实现灵活的邮件、微信提醒之类的。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本支持了 3 - 6。
3 - 8 自动更新的需求计划是放到 2.0 大版本重构时支持。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布

**Comment by swRains** [comment]
> v1.9.3 版本已发布

感谢🙏!刚刚更新，very very good👍
