### ISSUE TITLE
[FEATURE]希望能增加一个 PM2 管理器和 node.js 版本管理器

### ISSUE THREAD

**Issue by EdwardWaring** [1Panel-dev/1Panel#1169]
### 1Panel 版本

v1.2.4.1

### 请描述您的需求或者改进建议

希望能增加一个 PM 2 管理器和 node.js 版本管理器

### 请描述你建议的实现方案

增加一个 PM2 管理器和 node.js 版本管理器

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在后续版本中可能会考虑支持上述需求。

**Comment by xiyuvi** [comment]
同求

**Comment by zyyfit** [comment]
1.7.0版本增加了对nodejs环境的支持

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
