### ISSUE TITLE
新增chroot环境部署功能

### ISSUE THREAD

**Issue by dabao1955** [1Panel-dev/1Panel#1170]
### 1Panel 版本

v1.2.4.1

### 请描述您的需求或者改进建议

新增chroot环境部署功能，以便不支持docker功能的设备安装1panel

### 请描述你建议的实现方案

1.使用debootstrap等工具构建最简chroot环境
2.登录chroot环境，部署1panel
3.访问1panel面板

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在后续版本中可能会考虑支持 chroot 环境部署 1Panel。
