### ISSUE TITLE
[BUG]下载备份和文件是出现请求超时

### ISSUE THREAD

**Issue by 3466874615** [1Panel-dev/1Panel#1171]
### 联系方式

3466874615@qq.com

### 1Panel 版本

v1.2.4

### 问题描述

下载文件是出现请求超时或无法下载

### 重现步骤

在备份列表或文件列表下载文件

### 期待的正确结果

可以正常下载文件和网站备份文件

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述问题我们会在近期版本中修复。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
