### ISSUE TITLE
[FEATURE]数据库初始密码长度优化

### ISSUE THREAD

**Issue by Jengro777** [1Panel-dev/1Panel#1174]
### 1Panel 版本

1.2.4

### 请描述您的需求或者改进建议

数据库初始密码长度当前限制不超过30位

### 请描述你建议的实现方案

期望 可以支持长度64 的密码

**Comment by zhengkunwang223** [comment]
感谢反馈，后续版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
