### ISSUE TITLE
[FEATURE] 数据库管理增加postgres 的UI 管理面板

### ISSUE THREAD

**Issue by Jengro777** [1Panel-dev/1Panel#1175]
### 1Panel 版本

1.2.4

### 请描述您的需求或者改进建议

目前数据库界面 只支持mysql和redis 的可视化管理，但 posgres 在开源数据中的占比依然不小，很多开源系统都是基于postgres 数据库开发的，希望增加 postgres 的可视化界面

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复 #758
