### ISSUE TITLE
[FEATURE] 抽屉新增全屏放大功能

### ISSUE THREAD

**Issue by mdddj** [1Panel-dev/1Panel#1176]
### 1Panel 版本

1.2.4

### 请描述您的需求或者改进建议

查看docker日志有内容过多，一行显示不完，要拖动底部横向滚动条不方便

### 请描述你建议的实现方案

建议在如下图，添加一个全屏放大图片，让抽屉占满整个屏幕

<img width="2474" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/29020213/dd1c5a64-dcb5-4997-8302-bee62dae3a5b">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，容器日志查看页面支持全屏放大的需求我们在后续版本中支持。

**Comment by wanghe-fit2cloud** [comment]
v1.3.3 版本已发布。
