### ISSUE TITLE
[BUG]应用商店安装Nexus报data目录不存在

### ISSUE THREAD

**Issue by 1120023921** [1Panel-dev/1Panel#1179]
### 1Panel 版本

1.2.4

### 问题描述

应用商店安装Nexus报data目录不存在

### 重现步骤

<img width="1316" alt="5b252f3394a316d999bc0b8ce07cb8f" src="https://github.com/1Panel-dev/1Panel/assets/22630738/27d3e9d4-17e2-4f4a-8f49-7acf547c8cab">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们已经在本地复现该问题，会在近期发布的版本中修复。
当前版本中，你可以进去 1Panel 安装目录，然后手动创建 data 目录后再创建 nexus 即可正常运行：
```shell
# cd ./resource/apps/nexus/versions/3.47.1
# mkdir data
```
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/0b630ee7-1587-400e-96d5-3883b19410ce)

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
