### ISSUE TITLE
[BUG]Centos9安装失败

### ISSUE THREAD

**Issue by stevenliuit** [1Panel-dev/1Panel#1182]
### 1Panel 版本

最新版

### 问题描述

使用命令在centos9上面安装提示服务启动失败
curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sudo bash quick_start.sh
![image](https://github.com/1Panel-dev/1Panel/assets/4044994/aa43662a-26c0-4527-b761-229b7b543ebf)

### 重现步骤

新安装的centos9 然后安装上面命令

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。我刚在阿里云申请的 CentOS Stream 9 64 位服务器，成功运行一键安装脚本，没有复现上述问题。
请问你的服务器是在哪里申请的，我复现一下问题。

**Comment by stevenliuit** [comment]
> 感谢反馈。我刚在阿里云申请的 CentOS Stream 9 64 位服务器，成功运行一键安装脚本，没有复现上述问题。 请问你的服务器是在哪里申请的，我复现一下问题。

在本地装一个vmware虚拟机 然后通过命令安装的

**Comment by stevenliuit** [comment]
安装的是带界面的CentOS 9
https://mirrors.tuna.tsinghua.edu.cn/centos-stream/9-stream/BaseOS/x86_64/iso/CentOS-Stream-9-latest-x86_64-dvd1.iso
用的这个镜像

**Comment by wanghe-fit2cloud** [comment]
v1.3.5 版本已修复上述问题。
