### ISSUE TITLE
[BUG] 手动导入 Cloudflare Origin 证书，不显示证书域名

### ISSUE THREAD

**Issue by ybw0014** [1Panel-dev/1Panel#1184]
### 联系方式

N/A

### 1Panel 版本

1.2.4

### 问题描述

导入了cf源证书后，面板不会显示证书的域名，只显示 CloudFlare Origin Certificate，有多个域名只能随便选一个，看运气。
<img width="461" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/7105953/34ff6cfb-34c6-4c96-942a-3b9e5bbd6d46">

### 重现步骤

配置https时，导入Cloudflare Origin Certificate

### 期待的正确结果

可以正确显示cf源证书的域名

**Comment by zhengkunwang223** [comment]
这个我们复现一下试试

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
