### ISSUE TITLE
[QUESTION]从宝塔面板上备份下载下来的wordpress怎样上传到1panel

### ISSUE THREAD

**Issue by KAWAKO-in-GAYHUB** [1Panel-dev/1Panel#1186]
### 请描述您的问题

我之前在腾讯云上搭建的wordpress网页，现在想迁移到家里的服务器（装有1panel）。
我从云服务器的宝塔面板上备份下来的是一个wordpress.tar.gz，解压后内部文件结构如下
![image](https://github.com/1Panel-dev/1Panel/assets/54660064/b36f0523-6b86-4071-bc41-d2e4c36b0b7c)
我直接将这个压缩包上传到1panel上提示我压缩包内不包含app.json
我不太懂docker部署，请问我该如何上传，谢谢！

**Comment by zhengkunwang223** [comment]
您好 可以把这个压缩文件上传到 1Panel 创建的 PHP 运行环境类型的网站目录
网站目录入口为 网站设置-网站目录 点击跳转 
把wordpress相关文件放在 index 目录下
如果有  .user.ini 文件，需要删除
