### ISSUE TITLE
[BUG] 无法正常下载Docker备份文件

### ISSUE THREAD

**Issue by OrangeMas** [1Panel-dev/1Panel#1191]
### 1Panel 版本

1.2.4

### 问题描述

从应用商店内安装应用后，进行备份并下载备份文件到本地。会导致服务自动重启并无法下载文件(需要重新登录)
经实验多次均这个样子。系统日志内没有发现Error等错误。
面板本身使用反向代理实现，没有使用安全出口。
日志处显示下载成功，但实际浏览器并未开始下载进程

问题补充：疑似文件超过一定大小就无法下载，经查看备份文件150MB从文件浏览处即无法下载。几MB文件可以正常下载

### 重现步骤

正常安装应用，安装后到应用商店-已安装地方进行备份，备份完成后下载即可复现

### 相关日志输出

```shell
相关日志文件过长无法上传，可能存在无用字段，使用第三方网盘方式上传
https://cloud.189.cn/web/share?code=AnqARv6Z3EZz（访问码：ioh5）
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
