### ISSUE TITLE
[BUG]can not install openresty with error massage docker can not started.

### ISSUE THREAD

**Issue by cloudcache** [1Panel-dev/1Panel#1198]
### 1Panel 版本

v1.2.4

### 问题描述

1panel version: v1.2.4
appstore version: v0.1.27
mode: stable
os:Ubuntu 22.04.1 LTS
after installer,I saw containerd and runc installed .but the panel can not install openrest with error massage docker can not started.
I check the system and found dockerd masked.
and docker.io will conflict with runc.

### 重现步骤

after installer,I saw containerd and runc installed .but the panel can not install openrest with error massage docker can not started.
I check the system and found dockerd masked.
and docker.io will conflict with runc.

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，你可以进入 主机 - 终端，手动执行以下命令来重新安装 Docker：
```shell
bash <(curl -sSL https://linuxmirrors.cn/docker.sh)
```

然后查看 Docker 是否可以正常运行：
```shell
systemctl status docker.service
```

**Comment by cloudcache** [comment]
Failed to start LSB: Create lightweight, portable, self-sufficient containers..
░░ Subject: A start job for unit docker.service has failed
[DONE] 检测到已安装最新版本的 Docker Engine，跳过安装

\n验证安装版本：Docker version 24.0.2, build cb74dfc

[DONE] 安装完成

**Comment by wanghe-fit2cloud** [comment]
[参考这篇文章](https://stackoverflow.com/questions/61397386/issue-starting-docker-failed-to-start-lsb-create-lightweight-portable-self)

**Comment by cloudcache** [comment]
你们自动化安装的docker /usr/bin/dockerd是不存在的。包括bash <(curl -sSL https://linuxmirrors.cn/docker.sh) 
手动安装的docker没有问题。

**Comment by wanghe-fit2cloud** [comment]
1Panel 在线安装脚本中安装 Docker 使用的是官方脚本：
```shell
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
```

<img width="955" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/435c3b4b-b076-4170-a2e6-b745d436e4af">

**Comment by cloudcache** [comment]
May 30 13:55:09 server28 systemd[1]: Starting LSB: Create lightweight, portable, self-sufficient containers....
May 30 13:55:09 server28 docker[2295]:  * /usr/bin/dockerd not present or not executable
May 30 13:55:09 server28 systemd[1]: docker.service: Control process exited, code=exited, status=1/FAILURE
May 30 13:55:09 server28 systemd[1]: docker.service: Failed with result 'exit-code'.
May 30 13:55:09 server28 systemd[1]: Failed to start LSB: Create lightweight, portable, self-sufficient containers..
May 30 14:51:37 server28 systemd[1]: Starting LSB: Create lightweight, portable, self-sufficient containers....
May 30 14:51:37 server28 docker[5647]:  * /usr/bin/dockerd not present or not executable
May 30 14:51:37 server28 systemd[1]: docker.service: Control process exited, code=exited, status=1/FAILURE
May 30 14:51:37 server28 systemd[1]: docker.service: Failed with result 'exit-code'.
May 30 14:51:37 server28 systemd[1]: Failed to start LSB: Create lightweight, portable, self-sufficient containers..
May 30 14:54:30 server28 systemd[1]: Starting LSB: Create lightweight, portable, self-sufficient containers....
May 30 14:54:30 server28 docker[5668]:  * /usr/bin/dockerd not present or not executable
May 30 14:54:30 server28 systemd[1]: docker.service: Control process exited, code=exited, status=1/FAILURE
May 30 14:54:30 server28 systemd[1]: docker.service: Failed with result 'exit-code'.
May 30 14:54:30 server28 systemd[1]: Failed to start LSB: Create lightweight, portable, self-sufficient containers..

手动apt-get install docker-ce 后正常。
