### ISSUE TITLE
[FEATURE] sftp manger

### ISSUE THREAD

**Issue by lujay** [1Panel-dev/1Panel#1201]
### 1Panel 版本

1.2.4

### 请描述您的需求或者改进建议

目前经常隔三岔五需要添加sftp用户，管理目录，是否可以添加这个sftp管理功能咧

### 请描述你建议的实现方案

一般的常用功能，  增删改查权限配置呗

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布，sftp 教程请参考 [官方文档](https://1panel.cn/docs/user_manual/ftp/)
