### ISSUE TITLE
[BUG]解压文件错误

### ISSUE THREAD

**Issue by xinyihl** [1Panel-dev/1Panel#1209]
### 1Panel 版本

1.2.4

### 问题描述

解压文件错误创建的文件夹无法删除，

### 重现步骤

[新建文件夹.zip](https://github.com/1Panel-dev/1Panel/files/11612484/default.zip)
解压该文件后生成乱码文件夹且无法使用面板删除，rm -rf 可以删除

**Comment by zhengkunwang223** [comment]
您好 已复现 下个版本修复
