### ISSUE TITLE
[BUG] Archlinux新装不能初始化商店和更新版本

### ISSUE THREAD

**Issue by OrangeMas** [1Panel-dev/1Panel#1211]
### 1Panel 版本

v1.2.0

### 问题描述

疑似v.1.2.0后续均有问题:
系统为Archlinux，新装后访问后台报错，或其他错误
> dial tcp: lookup resource.fit2cloud.com on [::1]:53: dial udp [::1]:53: socket: address family not supported by protocol

### 重现步骤

全新安装Archlinux并1Panel后即可出现

### 相关日志输出

```shell
当前版本:v1.3.0.2
日志文件过长，使用第三方网盘上传
https://cloud.189.cn/web/share?code=6baimyfaIBFj（访问码：f3ws）
```

**Comment by zhengkunwang223** [comment]
检查一下自己的DNS 防火墙 或者代理的设置

**Comment by OrangeMas** [comment]
> 检查一下自己的DNS 防火墙 或者代理的设置

新装的机子，未开启防火墙，DNS为223.5.5.5其他解析全部正常，手动traceroute等均正常。未配置代理服务。在虚拟机中也无法使用。从源拉取源代码直接调试正常，从官网安装则就不行

**Comment by zhengkunwang223** [comment]
> > 检查一下自己的DNS 防火墙 或者代理的设置
> 
> 新装的机子，未开启防火墙，DNS为223.5.5.5其他解析全部正常，手动traceroute等均正常。未配置代理服务。在虚拟机中也无法使用。从源拉取源代码直接调试正常，从官网安装则就不行

最新的代码有修改 可以等下个版本发布再试一下
