### ISSUE TITLE
[BUG] HTTPS website

### ISSUE THREAD

**Issue by rafalohaki** [1Panel-dev/1Panel#1212]
### 1Panel 版本

Versionv1.2.4

### 问题描述

When i try to use https on the website, its not working. while https is enabled, http still works('http can be accessed directly' option) but https is not working(access automatically jumps to https 'option'). 
I was using https from crt generated from letsencrypt and crt from cloudflare and from import crt option. Not working.
Im using dns behind cloudflare.

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/20607107/70eb3e6a-a59b-458f-b15c-795e97710564)
![image](https://github.com/1Panel-dev/1Panel/assets/20607107/88d75cb4-83d4-4c3a-af45-65f2687af102)

### 期待的正确结果

When importing crt from cloudflare, website should work with https. Thats how i always do in other panel and its working.

**Comment by wanghe-fit2cloud** [comment]
Thank you for your feedback. We will first reproduce the issue in our local environment.

**Comment by zhengkunwang223** [comment]
Please set the SSL/TLS encryption mode to 'Flexible' on the Cloudflare's SSL settings page
