### ISSUE TITLE
[BUG] 使用ufw limit ssh后22端口的状态实际为limited，但面板显示拒绝

### ISSUE THREAD

**Issue by ayanami-desu** [1Panel-dev/1Panel#1215]
### 1Panel 版本

v1.2.4

### 问题描述

使用ufw limit ssh后22端口的状态实际为limited，但面板显示拒绝
![image](https://github.com/1Panel-dev/1Panel/assets/105108444/19f554bc-7835-4201-ad6e-236cbb3cfc40)
![image](https://github.com/1Panel-dev/1Panel/assets/105108444/c2832cb3-a5b1-45ff-b63f-a6310846f2d9)

### 重现步骤

执行命令`ufw limit ssh`

### 期待的正确结果

新增类型“限制”

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持上述需求。

**Comment by zyyfit** [comment]
目前改为不显示limited端口，后续再寻找更好的方式继续进行优化

**Comment by ayanami-desu** [comment]
感谢开发者的努力

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
