### ISSUE TITLE
[FEATURE] 终端链接服务器时，希望是新开页签，而不会影响当前已经打开的页签

### ISSUE THREAD

**Issue by Jengro777** [1Panel-dev/1Panel#1222]
### 1Panel 版本

1.2.4

### 请描述您的需求或者改进建议

如果需要开启多个终端，分别启动前端和后端程序，1panel 目前的终端打开方式 不太友好

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，下个版本优化这里。

**Comment by wanghe-fit2cloud** [comment]
当前版本，你可以将本地服务器添加到主机列表，然后在终端列表选择已添加的主机（支持打开多个窗口）
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/ae860c57-4418-4e71-a6c8-ac6ab449ca77)

**Comment by Jengro777** [comment]
我已经添加了3个相同的主机列表了

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
