### ISSUE TITLE
[FEATURE]系統語言中支持繁體中文

### ISSUE THREAD

**Issue by Arcelibs** [1Panel-dev/1Panel#1235]
### 1Panel 版本

1.2.4

### 请描述您的需求或者改进建议

台灣用戶，之前都是用寶塔或者[Hestia Control Panel](https://hestiacp.com/)

意外發現這個面板不錯，想要詢問下如何在系統語言中支持繁體中文?

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
