### ISSUE TITLE
[为什么1Panel 面板接收不到halo 2.6版本更新]

### ISSUE THREAD

**Issue by OSNewbie** [1Panel-dev/1Panel#1244]
### 1Panel 版本

v1.2.4

### 问题描述

我不清楚是什么原因，我看到别人都更新了，halo2.6版本 
镜像加速:http://xxx.m.daocloud.io
这是我现在在用的，我记得以前有1Panel面板上面有一个默认了镜像加速源，但是那个我不小心删除了问下 ，以前那个那个镜像加速源的地址是在哪里？求告知一下

 请问一下，这个错误怎么解决.:服务内部错误: Error response from daemon: invalid environment variable:

### 重现步骤

不知道，不知道怎么重现

### 期待的正确结果

能正常更新halo 新版本以及应用商店的应用

**Comment by wanghe-fit2cloud** [comment]
- 应用商店已经在适配 Halo 2.6 版本。
- 镜像加速器的配置 [参考文档](https://1panel.cn/docs/user_manual/containers/setting/)，推荐使用个人申请的 DaoCloud 或者阿里云加速器。
- 我将你现在使用的加速器地址打码了(http://xxx.)

**Comment by OSNewbie** [comment]
用了阿里云的镜像加速器，但是，应用商店更新应用列表还是没有变化了，还是？halo2.5.2
![Screenshot_20230603-172347](https://github.com/1Panel-dev/1Panel/assets/85106891/c8532c2d-76e3-4ffc-a1eb-71b2c301356c)
![图叨叨_20230603_172746](https://github.com/1Panel-dev/1Panel/assets/85106891/348c1e9e-1a64-49ce-a1e9-a74e0df12f24)

**Comment by OSNewbie** [comment]
![图叨叨_20230603_173218](https://github.com/1Panel-dev/1Panel/assets/85106891/61ae7647-9116-4b21-8908-9a72d9f5624b)

**Comment by wzry2580** [comment]
容器	
更新 docker daemon.json 配置	
失败	
2023-06-03 17:08:41

**Comment by OSNewbie** [comment]
> 容器 更新 docker daemon.json 配置 失败 2023-06-03 17:08:41

这个是操作日志

**Comment by OSNewbie** [comment]
应用商店更新应用列表状态是成功，就是不显示halo新版本 指的是2.6.0  可升级那里 显示当前应用均为最新版本

**Comment by wanghe-fit2cloud** [comment]
Halo 2.6 版本适配完成后，预计会在下周正式推送。
