### ISSUE TITLE
[BUG] zip文件无法解压

### ISSUE THREAD

**Issue by DongShaoNB** [1Panel-dev/1Panel#1245]
### 联系方式

1964545962@qq.com

### 1Panel 版本

1.2.4

### 问题描述

从MediaWiki下的安装包无法解压(.zip)

### 重现步骤

1.下载MediaWiki安装包
2.主机-文件-解压

### 相关日志输出

```shell
服务内部错误: handling file 0: mediawiki-1.39.3/CODE_OF_CONDUCT.md: open /opt/1panel/apps/openresty/OpenResty/www/sites/******/index/mediawiki-1.39.3/CODE_OF_CONDUCT.md: no such file or directory
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述问题我们会在后续要发布的版本中解决。

**Comment by newcardriver** [comment]
1.3.6版本依然会有这个问题。
![img_v2_249cacf4-2d3c-43f6-89b1-fd6a136c092g](https://github.com/1Panel-dev/1Panel/assets/44741731/2515ceca-14e4-4fb3-b53c-d8f02519c964)
![img_v2_ab5c09bd-2ea0-4b15-968c-2a504b76031g](https://github.com/1Panel-dev/1Panel/assets/44741731/2b2ada95-dc28-49eb-92e9-ca781fe13c7a)

用命令是可以正常解压缩的。
![img_v2_d09e1307-1e86-436b-8b58-1af8b14da93g](https://github.com/1Panel-dev/1Panel/assets/44741731/26dcaa7f-c997-41e1-be94-b5d33d6470c2)

希望能尽快修复。
@wanghe-fit2cloud

**Comment by wanghe-fit2cloud** [comment]
当前版本是通过 SKD 来实现的上述功能，后续版本会针对当前问题修改为命令操作（会在某一个版本统一处理）。

**Comment by newcardriver** [comment]
> 当前版本是通过 SKD 来实现的上述功能，后续版本会针对当前问题修改为命令操作（会在某一个版本统一处理）。


大佬，那目前如果要在线解压ZIP的话，除了用命令，我需要注意哪些才能正常解压额(⊙﹏⊙)？

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
