### ISSUE TITLE
[FEATURE] 建议 内存 磁盘  cpu 等指标设置报警功能 

### ISSUE THREAD

**Issue by gopower** [1Panel-dev/1Panel#1247]
### 1Panel 版本

v1.2.3.3

### 请描述您的需求或者改进建议

 建议 内存 磁盘  cpu 等指标设置报警功能 ，预知到来的风险

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑上述需求。

**Comment by Shazoo** [comment]
磁盘空闲、cpu负载、内存负载的阈值、持续时间报警……类似这样的需求感觉是刚需哦。

刚给几台服务器配置了1Panel，界面清爽，功能也不错。结果发现没这些功能……

建议支持：http requests、telegram bot、微信公帐号、飞书……

**Comment by wanghe-fit2cloud** [comment]
通知、告警相关需求的讨论，统一汇总到该 issue #614
