### ISSUE TITLE
[FEATURE] Letsencrypt 证书生成支持 dns.la

### ISSUE THREAD

**Issue by ailncode** [1Panel-dev/1Panel#1250]
### 1Panel 版本

v1.2.4

### 请描述您的需求或者改进建议

Letsencrypt 证书，DNS 账户支持 dns.la

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
当前版本我们是使用的 [lego](https://github.com/go-acme/lego) 来实现证书申请功能，所以我们会优先支持 [lego](https://github.com/go-acme/lego) 官方支持的 [DNS 服务商](https://go-acme.github.io/lego/dns/)
> dns.la 并不在其中，所以短时间内我们不会支持，望理解。
