### ISSUE TITLE
[BUG] 计划任务 目录备份

### ISSUE THREAD

**Issue by SaintWe** [1Panel-dev/1Panel#1253]
### 1Panel 版本

v1.2.4

### 问题描述

1. 使用计划任务备份目录时，多条排除规则若是意外使用了换行进行间隔，第二条及之后的排除规则可能会被当成命令执行，建议支持使用换行作为排除规则的间隔
2. 在计划任务备份任务的报告中，当查看过往的备份日志时有每隔 5s 的数据刷新(`/api/v1/cronjobs/search/records`)，会导致自动切回最新的任务报告

### 重现步骤

**1. 错误示例**

```
data/.esphome
compose.log
.gitignore
```

**1. 报错内容**

`stderr: tar: Cowardly refusing to create an empty archive Try 'tar --help' or 'tar --usage' for more information. bash: line 2: compose.log: command not found`

**Comment by ssongliu** [comment]
感谢反馈！本周发布的 1.3 版本将优化上述两个问题。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
