### ISSUE TITLE
[FEATURE] 记录文件浏览器最后一次访问的路径

### ISSUE THREAD

**Issue by SaintWe** [1Panel-dev/1Panel#1254]
### 1Panel 版本

v1.2.4

### 请描述您的需求或者改进建议

1. 记录最后一次访问的路径，下一次打开文件浏览器不是直接进入根目录，当在一个多级文件夹内时很有用
2. 每当进入新的目录，在 URL 上进行更新，如 `http://10.0.0.1:8888/hosts/files?path=/root/111/222/333`，当快捷键重载页面时不会自动回到根目录

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本支持此功能

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
