### ISSUE TITLE
[FEATURE] 反向代理的代理地址

### ISSUE THREAD

**Issue by DongShaoNB** [1Panel-dev/1Panel#1257]
### 1Panel 版本

1.2.4

### 请描述您的需求或者改进建议

创建网站选择反向代理时，代理地址处默认填写http://或者没有填写时自动加上

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本优化此功能

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
