### ISSUE TITLE
封装成appimage 或者 static binary [FEATURE]

### ISSUE THREAD

**Issue by newyorkthink** [1Panel-dev/1Panel#1261]
### 1Panel 版本

404

### 请描述您的需求或者改进建议

go 语言本来就是静态，sta binary 可以自由放在任何地方 然后 ln 到 /usr/bin

### 请描述你建议的实现方案

go 语言本来就是静态，sta binary 可以自由放在任何地方 然后 ln 到 /usr/bin

### 附加信息

go 语言本来就是静态，sta binary 可以自由放在任何地方 然后 ln 到 /usr/bin

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本会支持上述需求。
