### ISSUE TITLE
[BUG]1panel面版ui不适配手机浏览器

### ISSUE THREAD

**Issue by XTxiaoting14332** [1Panel-dev/1Panel#1263]
### 联系方式

qq:2125714976

### 1Panel 版本

1.2.4

### 问题描述

面板UI不适配手机浏览器，会以电脑ui缩小显示

### 重现步骤

用手机浏览器打开面板
登录面板
面板ui无法适配手机浏览器

### 期待的正确结果

登录成功后界面在手机浏览器界面完整、无缩放地显示

### 附加信息

![IMG_20230606_084033](https://github.com/1Panel-dev/1Panel/assets/96647974/a74efc64-a581-4ef6-9552-f1c8a125d2da)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本会针对移动端做出优化。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
