### ISSUE TITLE
[FEATURE]应用商店增加应用Umami

### ISSUE THREAD

**Issue by VMCoud** [1Panel-dev/1Panel#1270]
### 1Panel 版本

1.2.3

### 请描述您的需求或者改进建议

增加应用Umami 

Umami 是 Google Analytics 的一款简单、快速、注重隐私的替代品。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中将其添加到应用商店。
当前版本，你可以手动将其添加为本地应用，具体教程参考 [官方文档](https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8)

**Comment by wanghe-fit2cloud** [comment]
#250

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
