### ISSUE TITLE
[FEATURE] 增加登录失败处理功能

### ISSUE THREAD

**Issue by 199-LI** [1Panel-dev/1Panel#1272]
### 1Panel 版本

v1.2.4

### 请描述您的需求或者改进建议

建议增加用户登录失败处理策略模块，防止恶意人员对管理面板进行口令爆破。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by maninhill** [comment]
请问这个问题有进展吗？

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is there any progress on this issue?

**Comment by wanghe-fit2cloud** [comment]
当前版本在首次认证失败后，会强制要求用户输入验证码。
