### ISSUE TITLE
[FEATURE]关于面板数据迁移的建议

### ISSUE THREAD

**Issue by xtiandd** [1Panel-dev/1Panel#1280]
### 1Panel 版本

v1.2.4

### 请描述您的需求或者改进建议

希望增加一个一键打包和迁移面板所有数据的功能，方便用户在更换服务器时迁移数据

(ง •̀_•́)ง

**Comment by maninhill** [comment]
就跟小米换机，苹果换机一样，一键迁移。

**Comment by wanghe-fit2cloud** [comment]
> 就跟小米换机，苹果换机一样，一键迁移。

1Panel 已经支持创建快照到第三方账号。如果存在迁移面板的需求，可以使用同步快照功能。

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/5cebd4f1-083a-4497-be13-907a90f3d3c8)
