### ISSUE TITLE
[BUG] 主机-防火墙-IP规则 添加ip段报错

### ISSUE THREAD

**Issue by jaychoubaby** [1Panel-dev/1Panel#1293]
### 联系方式

356666293@qq.com

### 1Panel 版本

v1.3.0

### 问题描述

主机-防火墙-IP规则 添加ip段报错

服务内部错误: add rich rules failed, err: stderr: Error: INVALID_ADDR: 218.92.0.0/255

### 重现步骤

主机-防火墙-IP规则 添加ip段报错

### 期待的正确结果

成功

### 相关日志输出

```shell
服务内部错误: add rich rules failed, err: stderr: Error: INVALID_ADDR: 218.92.0.0/255
```

**Comment by ssongliu** [comment]
这里应该得写成 218.92.0.0/24

**Comment by jaychoubaby** [comment]
> 这里应该得写成 218.92.0.0/24

可是攻击我服务器的ip 号段从0-255的都有，我需要怎么写呢

**Comment by ssongliu** [comment]
218.92.0.0/24 就包含了 218.92.0.1 到 218.92.0.254

**Comment by jaychoubaby** [comment]
> 

好的 明白了 谢谢
