### ISSUE TITLE
[QUESTION]玩客云docker-compose安装失败，不知道啥原因

### ISSUE THREAD

**Issue by itworkzhang** [1Panel-dev/1Panel#1295]
### 请描述您的问题

![image](https://github.com/1Panel-dev/1Panel/assets/42572628/383d09e3-5e33-47f8-8a0c-c578dbb35e6b)

**Comment by wanghe-fit2cloud** [comment]
可以手动下载官方二进制文件，[下载链接](https://github.com/docker/compose/releases)
再次安装 1Panel 时，会自动跳过。
