### ISSUE TITLE
[BUG] sftp 创建快照，快照文件特别大时会 out of memory

### ISSUE THREAD

**Issue by MignonZhang** [1Panel-dev/1Panel#1296]
### 1Panel 版本

1.3.0

### 问题描述

sftp 创建快照，快照文件特别大时会 out of memory

<img width="1433" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/27415482/64b43a27-86ef-404e-805e-b7596f0d948e">

### 重现步骤

系统里多下载几个docker 镜像，然后创建快照，选择sftp备份账号，创建完上传到sftp时会报错，然后1panel会重启，然后快照状态会卡在 上传中，上传失败，也无法同步和恢复

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期发布的版本中修改上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.3.1 版本已发布。
