### ISSUE TITLE
优化 日志审计-SSH登陆日志列表查询速度太慢了

### ISSUE THREAD

**Issue by jaychoubaby** [1Panel-dev/1Panel#1302]
### 1Panel 版本

v1.3.0

### 请描述您的需求或者改进建议

希望优化一下查询速度

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.3.1 版本已发布。

**Comment by jaychoubaby** [comment]
> v1.3.1 版本已发布。

查询速度稍微快了一些，但是按照请求时间变成了正序不是倒叙展示了，最新请求的要到最后一页查看

**Comment by wanghe-fit2cloud** [comment]
> > v1.3.1 版本已发布。
> 
> 查询速度稍微快了一些，但是按照请求时间变成了正序不是倒叙展示了，最新请求的要到最后一页查看

后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.3.6 版本再次针对 SSH 日志查询逻辑进行了优化。
