### ISSUE TITLE
[FEATURE]建议增加supervisord模块

### ISSUE THREAD

**Issue by Alan0429** [1Panel-dev/1Panel#1305]
### 1Panel 版本

1.2

### 请描述您的需求或者改进建议

建议增加supervisord模块，想从宝塔搬过来，但是很多业务需要supervisord

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持上述需求。

**Comment by ssongliu** [comment]
感谢支持！ 最新的 v1.5.1 已经支持上述功能，请更新后体验。
