### ISSUE TITLE
日志审计-SSH登录日志-失败日志一键加入防火墙黑名单

### ISSUE THREAD

**Issue by jaychoubaby** [1Panel-dev/1Panel#1309]
### 1Panel 版本

v1.3.0

### 请描述您的需求或者改进建议

我使用日志审计-SSH登录日志-失败日志功能看到每天都要遭受全世界各个ip的攻击，目前我只能手动复制这些ip一个一个的添加到ip屏蔽列表中，这个工作太繁琐了，我希望可以在SSH登录日志-失败日志的列表页面可以一键添加到ip屏蔽列表中，这个功能真的迫切需要，希望可以支持，非常感谢。

### 请描述你建议的实现方案

![image](https://github.com/1Panel-dev/1Panel/assets/26641387/981a58c6-56cf-4c58-ab78-076a99180516)
![image](https://github.com/1Panel-dev/1Panel/assets/26641387/940e8541-3cf1-4270-8a3a-ccc447661745)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by yfdoor** [comment]
> 感谢反馈，我们会在后续版本支持上述需求。

另外是否可以按 IP 分组，几千条的失败记录，可能都是来自一个 IP 的攻击，按 IP 分组后，就可以快速查到哪些 IP 在攻击

**Comment by deep-project** [comment]
> 另外是否可以按 IP 分组，几千条的失败记录，可能都是来自一个 IP 的攻击，按 IP 分组后，就可以快速查到哪些 IP 在攻击

其实你把默认的22端口改一下，基本就可以了。如果用默认的端口，互联网上很多发包机器人

**Comment by jaychoubaby** [comment]
> 

可是他们攻击的不是22端口，会把所有端口都扫一遍

**Comment by deep-project** [comment]
我给你加一键屏蔽功能了，等官方审核，下一个版本应该就有了。

**Comment by jaychoubaby** [comment]
> 我给你加一键屏蔽功能了，等官方审核，下一个版本应该就有了。

我再v1.4.3版本上已经体验到这个功能，然后当我分页每页条数选择100的时候，屏蔽功能则会报错，我理解的这个功能应该是先将数据去重之后再添加到屏蔽列表中，请问是否有先去重呢，因为可能一页里面同一个ip会疯狂请求，所以即使每页条数选择100 ，最终要加入屏蔽名单的ip只有一个，如果不去重则很浪费性能，另外如果可以的话，希望这个页面的每页条数可以放开限制到每页1000条，这样全选-屏蔽 的话，不用一页一页翻

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。

**Comment by jaychoubaby** [comment]
> v1.7.0 版本已发布。

原本以为1.6几版本已经做完了，1.7.0用上之后发现 加入黑名单功能好用了不是一点点，还统计了恶意请求失败次数，👍

**Comment by jaychoubaby** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/26641387/dcef9d78-34e8-4ef3-9153-95a2bf1a6b50)
183.236.94.23 丧心病狂
