### ISSUE TITLE
[FEATURE]建议增加升级失败自动回滚功能

### ISSUE THREAD

**Issue by chengjunjian** [1Panel-dev/1Panel#1310]
### 1Panel 版本

1.3

### 请描述您的需求或者改进建议

因为升级1.3 时候出现 1panel 服务 启动失败情况， 这种问题如果在正式环境会造成非常大的麻烦，希望能考虑这个功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已经支持，具体回滚命令如下：
```shell
1pctl restore
```
