### ISSUE TITLE
[QUESTION]希望添加openEuler、Rocky Linux等CentOS代替系统

### ISSUE THREAD

**Issue by liujazz** [1Panel-dev/1Panel#1311]
### 请描述您的问题

希望添加openEuler、Rocky Linux等CentOS代替系统支持，毕竟 CentOS 已经不维护了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，这些操作系统安装 1Panel 失败的主要原因在于不能一键安装 Docker。可以先手动在服务器上安装好 Docker 后再安装 1Panel，这时脚本会自动跳过。

**Comment by DongShaoNB** [comment]
https://1panel.cn/docs/faq/operating_system/
