### ISSUE TITLE
[FEATURE]建议加入自动清理更新包缓存和系统日志

### ISSUE THREAD

**Issue by wenyinos** [1Panel-dev/1Panel#1312]
### 1Panel 版本

1.3.0

### 请描述您的需求或者改进建议

面板升级后缓存和日志体积过大，对于硬盘小的机器不友好。

可在计划任务中加入，自动运行：
`#!/bin/bash

rm -rf /opt/1panel/tmp/*

rm -rf /opt/1panel/cache/*

exit`

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持上述需求。

**Comment by zyyfit** [comment]
1.8.0版本已支持缓存清理计划任务
