### ISSUE TITLE
[FEATURE] 更改SSH端口时自动修改开放新的端口

### ISSUE THREAD

**Issue by DongShaoNB** [1Panel-dev/1Panel#1318]
### 1Panel 版本

1.3.1

### 请描述您的需求或者改进建议

在面板更改SSH端口时自动修改开放新的端口

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持上述需求。

**Comment by ssongliu** [comment]
感谢支持！最新的 v1.5.1 版本已经支持上述功能，请更新后体验。
