### ISSUE TITLE
[BUG]面板启动错误，无法启动

### ISSUE THREAD

**Issue by chengjunjian** [1Panel-dev/1Panel#1321]
### 联系方式

1Panel 交流群2 昵称 “剑”，邮箱 54077055@qq.com

### 1Panel 版本

1.3.1

### 问题描述

启动日志如下
[2023-06-09 21:43:29] [INFO] init logger successfully
[2023-06-09 21:43:29] [INFO] init db successfully
[2023-06-09 21:43:29] [INFO] Migration run successfully
[2023-06-09 21:43:29] [INFO] init cache successfully
[2023-06-09 21:43:29] [INFO] init session successfully
[2023-06-09 21:43:29] [INFO] sync app start...
1panel: dl-call-libc-early-init.c:37: _dl_call_libc_early_init: Assertion `sym != NULL' failed.
SIGABRT: abort
PC=0x2a545bc m=24 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 31 [syscall]:
runtime.cgocall(0x2a3c830, 0xc001b73558)
        runtime/cgocall.go:157 +0x5c fp=0xc001b73530 sp=0xc001b734f8 pc=0x40607c
net._C2func_getaddrinfo(0xc00072ca40, 0x0, 0xc0005e3e00, 0xc0007184d8)
        _cgo_gotypes.go:99 +0x56 fp=0xc001b73558 sp=0xc001b73530 pc=0x6b6156
net._C_getaddrinfo.func1(0x410007?, 0x8?, 0x2cd17a0?, 0xc00072ca01?)
        net/cgo_unix_cgo.go:74 +0x85 fp=0xc001b735c0 sp=0xc001b73558 pc=0x6b6d25
net._C_getaddrinfo(0xc001b73778?, 0x2?, 0xc001b73668?, 0xc00072c580?)
        net/cgo_unix_cgo.go:74 +0x19 fp=0xc001b735f0 sp=0xc001b735c0 pc=0x6b6c59
net.cgoLookupIPCNAME({0x33f022b, 0x3}, {0xc00072c580, 0x19})
        net/cgo_unix.go:153 +0x175 fp=0xc001b73738 sp=0xc001b735f0 pc=0x681915
net.cgoIPLookup(0x0?, {0x33f022b?, 0xc00046eeb0?}, {0xc00072c580?, 0xc00046ee60?})
        net/cgo_unix.go:210 +0x3b fp=0xc001b737a8 sp=0xc001b73738 pc=0x681fdb
net.cgoLookupIP.func1()
        net/cgo_unix.go:220 +0x36 fp=0xc001b737e0 sp=0xc001b737a8 pc=0x682416
runtime.goexit()
        runtime/asm_amd64.s:1598 +0x1 fp=0xc001b737e8 sp=0xc001b737e0 pc=0x4728c1
created by net.cgoLookupIP
        net/cgo_unix.go:220 +0x12a

### 重现步骤

  我是在 amd64 服务器， debian 11, (Debian GLIBC 2.31-13+deb11u6) 2.31,出现这个问题，重装后也是如此，1.2.4 版本正常

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在本地开发环境复现一下该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.3.5 版本已修复上述问题。
