### ISSUE TITLE
mysql管理，不能接管mariadb?

### ISSUE THREAD

**Issue by livepu** [1Panel-dev/1Panel#1322]
### 请描述您的问题

作为mysql分支，在低配的机器里面，mariadb的更快地安装，运行相对没那么严苛。
但安装mariadb之后，mysql管理还提示需要安装mysql。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持在数据库页面来管理 MariaDB。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
