### ISSUE TITLE
[FEATURE]希望增加证书创建可以上传自有证书

### ISSUE THREAD

**Issue by ifacecn** [1Panel-dev/1Panel#1323]
### 1Panel 版本

1.3.1

### 请描述您的需求或者改进建议

希望增加证书创建可以上传自有证书

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持上述需求。

**Comment by ybw0014** [comment]
你可以在域名的https配置里上传自定义证书，不过证书界面确实没有这个功能

**Comment by ybw0014** [comment]
补充一下，希望可以有2种方式：
- 直接粘贴证书内容
- 设置本机证书路径，也许可以搞个软连接（在安装1panel之前就设置过acme.sh这种）

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
