### ISSUE TITLE
[BUG] 创建数据库提示错误，但已创建成功

### ISSUE THREAD

**Issue by DongShaoNB** [1Panel-dev/1Panel#1324]
### 联系方式

1964545962@qq.com

### 1Panel 版本

1.3.1

### 问题描述

创建数据库时提示数据库异常，但是通过root账号查看数据库已创建成功，从面板再次创建提示已存在，但列表并无显示

### 重现步骤

可能是因为面板更新导致出现的问题，无法复现出来

### 期待的正确结果

在面板的数据库界面添加同步数据库按钮，同步数据库到列表里（类似某塔的功能）

### 相关日志输出

```shell
SQL 执行超时，请检查1Panel-mysql-NwUB容器
```

**Comment by wanghe-fit2cloud** [comment]
1、麻烦提供一下 MySQL 数据库版本。
2、数据库同步功能，我们会在后续版本中支持。

**Comment by DongShaoNB** [comment]
> 1、麻烦提供一下 MySQL 数据库版本。 2、数据库同步功能，我们会在后续版本中支持。

MySQL 版本是  8.0.30

**Comment by wanghe-fit2cloud** [comment]
> > 1、麻烦提供一下 MySQL 数据库版本。 2、数据库同步功能，我们会在后续版本中支持。
> 
> MySQL 版本是 8.0.30

1Panel 面板升级至最新版本后才出现的上述问题？

**Comment by DongShaoNB** [comment]
> > > 1、麻烦提供一下 MySQL 数据库版本。 2、数据库同步功能，我们会在后续版本中支持。
> > 
> > 
> > MySQL 版本是 8.0.30
> 
> 1Panel 面板升级至最新版本后才出现的上述问题？

是的，此前未出现过，不确定是不是因为升级导致的

**Comment by wanghe-fit2cloud** [comment]
> > > > 1、麻烦提供一下 MySQL 数据库版本。 2、数据库同步功能，我们会在后续版本中支持。
> > > 
> > > 
> > > MySQL 版本是 8.0.30
> > 
> > 
> > 1Panel 面板升级至最新版本后才出现的上述问题？
> 
> 是的，此前未出现过，不确定是不是因为升级导致的

了解。
麻烦再提供一下服务器操作系统版本、架构和具体配置。
我们在本地环境复现一下问题。

**Comment by DongShaoNB** [comment]
> > > > > 1、麻烦提供一下 MySQL 数据库版本。 2、数据库同步功能，我们会在后续版本中支持。
> > > > 
> > > > 
> > > > MySQL 版本是 8.0.30
> > > 
> > > 
> > > 1Panel 面板升级至最新版本后才出现的上述问题？
> > 
> > 
> > 是的，此前未出现过，不确定是不是因为升级导致的
> 
> 了解。 麻烦再提供一下服务器操作系统版本、架构和具体配置。 我们在本地环境复现一下问题。

系统版本: Rocky Linux 8.8 (Green Obsidian) 
架构: x86_64
Host: KVM/QEMU
Kernel: 4.18.0-477.13.1.el8_8.x86_64
