### ISSUE TITLE
增加存储卷目录快捷入口

### ISSUE THREAD

**Issue by BruceSuen720** [1Panel-dev/1Panel#1325]
### 1Panel 版本

1.3.1

### 请描述您的需求或者改进建议

希望可以在存储卷管理页面增加一个快捷入口，点击即可进入对应存储卷的目录进行文件管理

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述需求我们会在后续版本中支持。

**Comment by wanghe-fit2cloud** [comment]
v1.3.3 版本已发布。
