### ISSUE TITLE
容器管理界面优化

### ISSUE THREAD

**Issue by BruceSuen720** [1Panel-dev/1Panel#1326]
### 1Panel 版本

1.3.1

### 请描述您的需求或者改进建议

希望容器管理界面可以为每个创建的docker应用增加图标显示，增加webui快捷图标，绑定相应的链接地址；
增加存储卷快捷键，点击快捷键可以跳转到存储卷目录进行文件的快速管理；
增加docker应用的检查更新及应用更新选项，方便docker容器快速升级。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中陆续支持上述需求。

**Comment by ssongliu** [comment]
感谢支持，最新版本 v.1.5.1 已经支持了上述功能，请更新后体验。
