### ISSUE TITLE
[FEATURE] 应用商店可忽略应用更新

### ISSUE THREAD

**Issue by DongShaoNB** [1Panel-dev/1Panel#1328]
### 1Panel 版本

1.3.1

### 请描述您的需求或者改进建议

应用商店可以忽略某个应用的更新，例如Jenkins，已经在Jenkins的网页中更新完成，应用商店中仍然显示有新版本，这时候就可以选择忽略1个版本的更新或永久忽略

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
