### ISSUE TITLE
[FEATURE] 文件批量权限管理

### ISSUE THREAD

**Issue by SMGoro** [1Panel-dev/1Panel#1330]
### 1Panel 版本

v1.3.1

### 请描述您的需求或者改进建议

PHP环境下要求使用1000用户组权限，但是1panel自带的文件管理无法批量更改文件权限，建议改进。
另外1000用户组权限会在用户/用户组会显示空值，无法再进行更改权限，似乎自动会更改权限到1000，但是依旧会提示Access denied. 这点希望也改进一下。

### 请描述你建议的实现方案

把更改权限，权限用户/用户组的页面添加到同一个页面，放到更多的按钮里。
另外希望可以添加在文件管理的页面打开shell的功能，方便调试。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持上述需求。

如果需要更改 PHP 运行环境目录权限，可以进入 网站设置 - 网站目录 中修改：
<img width="1035" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/4ea50fbb-8667-4d25-aa42-9f1763756d58">

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
