### ISSUE TITLE
建议官方应用商店的应用把docker数据映射的目录都尽量以数据卷的形式添加，方便管理

### ISSUE THREAD

**Issue by BruceSuen720** [1Panel-dev/1Panel#1331]
### 1Panel 版本

1.3.1

### 请描述您的需求或者改进建议

建议官方应用商店的应用把docker数据映射的目录都尽量以数据卷的形式添加，方便管理
同时，官方安装的应用备份功能是否可以增加定时备份任务

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。我们会在后续版本中考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
最新版本已经支持在计划任务菜单中定时备份应用商店中已安装应用。
> 考虑到备份应用的逻辑，我们在中短期内应该不会考虑 docker volume的方式来管理，望理解。
