### ISSUE TITLE
[QUESTION] php无法安装imagick扩展

### ISSUE THREAD

**Issue by DongShaoNB** [1Panel-dev/1Panel#1332]
### 请描述您的问题

php无法安装imagick扩展，输入了imagick确认后制作完镜像使用php -m查看扩展并没有imagick

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。将 1Panel 更新到最新版本后，进入应用商店点击更新应用列表，之后再重新安装 PHP 运行环境。

**Comment by DongShaoNB** [comment]
> 感谢反馈。将 1Panel 更新到最新版本后，进入应用商店点击更新应用列表，之后再重新安装 PHP 运行环境。

有办法在不重新安装 PHP 的情况下解决嘛
