### ISSUE TITLE
[BUG]MySQL更新版本后面板数据库功能失效

### ISSUE THREAD

**Issue by HaoJun0823** [1Panel-dev/1Panel#1333]
### 联系方式

developer@haojun0823.xyz

### 1Panel 版本

1.3.1

### 问题描述

商店出了新版本MySQL的更新，我点击更新后，从8.0.30更新到8.0.33之后功能一切正常，但是发现数据库面板不能用了。（失败）
点击配置按钮会提示“服务内部错误: Error response from daemon: No such container: 1Panel-mysql-Idii”
在容器界面发现MySQL的容器名称变了，现在是mysql-mysql-A795-1，之前是1Panel-mysql-Idii。

### 重现步骤

无。

### 相关日志输出

```shell
日志更新系统提示：[mysql] 应用 [MySQL] [upgrade] | 成功 | 2023-06-08 20:57:14
```

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/26188180/baca4fac-3801-4252-87a6-f4c4589e1b90)
![image](https://github.com/1Panel-dev/1Panel/assets/26188180/4381c8fa-4d55-468d-b9cc-6d75b39530cc)

**Comment by lehhair** [comment]
我也碰到了这个问题，更新后一切要用到mysql的应用都无法连接了，wordpress，halo，phpmysql都不能访问了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们已经在本地复现该问题，v1.3.2 版本将修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
在当前版本中，可以使用下方临时解决方案：

- 1、应用商店 - 已安装应用
- 2、选择  MySQL，点击参数按钮弹出右侧抽屉，然后点击参数按钮
- 3、打开高级设置选项（不修改任何参数），点击下方确认按钮
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/858f5dd2-4c0a-42c1-a3d2-670af6d8d88d">

**Comment by HaoJun0823** [comment]
> 在当前版本中，可以使用下方临时解决方案：
> 
> * 1、应用商店 - 已安装应用
> * 2、选择  MySQL，点击参数按钮弹出右侧抽屉，然后点击参数按钮
> * 3、打开高级设置选项（不修改任何参数），点击下方确认按钮
> 
> <img alt="image" width="1475" src="https://user-images.githubusercontent.com/46734380/244873680-858f5dd2-4c0a-42c1-a3d2-670af6d8d88d.png">

在您截图的这个页面我发现其他更新的应用（Kuma,Wordpress）也是失败的状态，错误也是找不到对应容器，通过您的方法更新配置以后也全部恢复了，容器名称一切正常，谢谢。

**Comment by wanghe-fit2cloud** [comment]
v1.3.2 版本已发布。
