### ISSUE TITLE
[BUG]v1.3.1版本更新 MySQL 后导致 Halo 博客不能访问了

### ISSUE THREAD

**Issue by lehhair** [1Panel-dev/1Panel#1334]
### 1Panel 版本

1.3.1

### 问题描述

今天更新到最新的面板的时候更新了一下mysql，更新后安装失败，导致halo博客不能访问了，然后我就删除了halo博客和mysql重新安装，重新安装后面板没有提示报错，但是依旧不能访问，并且安装phpmysql也不能访问，wordpress也不能访问

### 重现步骤

重复好几次依旧不能解决

### 期待的正确结果

希望尽快修复

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们已经在本地复现该问题，v1.3.2 版本将修复上述问题。

**Comment by lehhair** [comment]
> 感谢反馈，我们已经在本地复现该问题，v1.3.2 版本将修复上述问题。

另外发现其他版本的mysql也不能被安装成功
![image](https://github.com/1Panel-dev/1Panel/assets/82690391/929675be-2f19-4b45-b29b-bcc9d643ca9a)

**Comment by wanghe-fit2cloud** [comment]
升级 MySQL 至最新版本导致 Halo 不能正常访问的问题，可以使用下方临时解决方案：

- 1、应用商店 - 已安装应用
- 2、选择  MySQL，点击参数按钮弹出右侧抽屉，然后点击参数按钮
- 3、打开高级设置选项（不修改任何参数），点击下方确认按钮
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/858f5dd2-4c0a-42c1-a3d2-670af6d8d88d">

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈，我们已经在本地复现该问题，v1.3.2 版本将修复上述问题。
> 
> 另外发现其他版本的mysql也不能被安装成功 ![image](https://user-images.githubusercontent.com/82690391/244873539-929675be-2f19-4b45-b29b-bcc9d643ca9a.png)

鼠标点击详情按钮，查看一下具体信息。

**Comment by lehhair** [comment]
> > > 感谢反馈，我们已经在本地复现该问题，v1.3.2 版本将修复上述问题。
> > 
> > 
> > 另外发现其他版本的mysql也不能被安装成功 ![image](https://user-images.githubusercontent.com/82690391/244873539-929675be-2f19-4b45-b29b-bcc9d643ca9a.png)
> 
> 鼠标点击详情按钮，查看一下具体信息。


5.7版本是因为我arm64服务器拉取不到镜像8.30是这样的

Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/panel/1panel/apps/mysql/mysql/conf/my.cnf" to rootfs at "/etc/my.cnf": mount /home/panel/1panel/apps/mysql/mysql/conf/my.cnf:/etc/my.cnf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

<img width="567" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/82690391/87bbc155-faa9-4f4f-aff7-8c59cfed2d7f">

**Comment by wanghe-fit2cloud** [comment]
v1.3 版本，应用商店安装应用，端口默认不对外暴露（127.0.0.1:port），可以点击参数按钮 - 高级设置中打开端口外部访问。

**Comment by wanghe-fit2cloud** [comment]
MySQL 5.7 版本，Oracle 官方没有提供 aarch64 架构镜像。

**Comment by lehhair** [comment]
> v1.3 版本，应用商店安装应用，端口默认不对外暴露（127.0.0.1:port），可以点击参数按钮 - 高级设置中打开端口外部访问。

<img width="837" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/82690391/a3e771c3-75f3-425e-bfbc-01ee1379080c">

**Comment by wanghe-fit2cloud** [comment]
进微信群，添加我好友。

**Comment by lehhair** [comment]
> v1.3 版本，应用商店安装应用，端口默认不对外暴露（127.0.0.1:port），可以点击参数按钮 - 高级设置中打开端口外部访问。

卸载后重新安装的时候选开放端口成功安装，正在测试能不能正常使用
<img width="589" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/82690391/7f7bd6ed-0ec3-4ed1-9e03-177258f899a2">

**Comment by lehhair** [comment]
问题已解决

**Comment by lehhair** [comment]
> 进微信群，添加我好友。

微信群是多少

**Comment by wanghe-fit2cloud** [comment]
<img src="https://1panel.cn/img/wechat-group.jpg" width="156" height="156"/>

**Comment by wanghe-fit2cloud** [comment]
v1.3.2 版本已发布。

**Comment by lehhair** [comment]
> v1.3.2 版本已发布。
我发现必须要在应用参数里面设置允许被外部访问，不能在防火墙设置吗，我想只给特定ip开放端口访问怎么弄呢

**Comment by wanghe-fit2cloud** [comment]
> > v1.3.2 版本已发布。
> > 我发现必须要在应用参数里面设置允许被外部访问，不能在防火墙设置吗，我想只给特定ip开放端口访问怎么弄呢

反代解决问题。
