### ISSUE TITLE
[BUG] 创建运行环境界面扩展输入框不展开

### ISSUE THREAD

**Issue by ybw0014** [1Panel-dev/1Panel#1335]
### 联系方式

N/A

### 1Panel 版本

1.3.1

### 问题描述

<img width="720" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/7105953/8d465aec-56ee-45d9-84eb-e784e4365ae5">
如图所示，当扩展填满一行后手动输入字符时，输入框不会展开，内部的元素会反复横跳。
点击列表添加时才会正常展开。

### 重现步骤

在网站-运行环境-创建运行环境中，添加刚好填满一行的扩展，然后手动输入。

### 期待的正确结果

手动输入也可以正确展开

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中持续优化上述问题。

**Comment by zhengkunwang223** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/a3338416-0c3f-4aa7-ba21-3632593982a2)
您好 没有复现此问题 请问是什么浏览器 ？

**Comment by ybw0014** [comment]
chrome 115.0.5790.114
<img width="644" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/7105953/a11f096b-24de-4a66-9081-d3d03a285f07">
调整窗口宽度就有可能出现这样

**Comment by wanghe-fit2cloud** [comment]
可以清空浏览器缓存后再次尝试。
> 我们在本地服务器确实没有复现上述问题。
