### ISSUE TITLE
[BUG] 应用备份后的包无法还原

### ISSUE THREAD

**Issue by lehhair** [1Panel-dev/1Panel#1338]
### 1Panel 版本

1.3.2

### 问题描述

在昨天因为更新后数据库更新失败不知道怎么解决的情况下我是删除了这两个程序的，然后重新安装并且上传备份的包进行还原，但是还原失败，我的解决方法是解压后把halo数据库和目录下的data手动分别导入恢复，还是希望可以解决这个bug，在安装应用程序的时候就提供导入备份安装的方式

### 重现步骤

可以复现

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地开发测试环境复现一下该问题。

**Comment by lehhair** [comment]
> 感谢反馈，我们先在本地开发测试环境复现一下该问题。

<img width="648" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/82690391/3aaf6a7a-aee8-40b6-bfb1-7e29f4a06241">

**Comment by wanghe-fit2cloud** [comment]
v1.3.3 版本已发布。
