### ISSUE TITLE
[FEATURE] 主机-终端 的拷贝粘贴

### ISSUE THREAD

**Issue by SaintWe** [1Panel-dev/1Panel#1340]
### 1Panel 版本

1.3.2

### 请描述您的需求或者改进建议

在当前版本下，终端可使用 `Ctrl + Shift + V` 实现粘贴，但 `Ctrl + Shift + C` 无法实现拷贝，希望 Windows 下能监听此组合键以及 macOS 下的 `⌘ + C` 和 `⌘ + V`

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中持续优化。

**Comment by ssongliu** [comment]
最新版本已经支持了终端的复制粘贴，可以更新到最新版本后重试。

**Comment by mio-lin** [comment]
請問複製貼上的快捷鍵是什麼我都試不出來
