### ISSUE TITLE
[FEATURE]网站日志的切割

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#1342]
### 1Panel 版本

1.3.2

### 请描述您的需求或者改进建议

目前网站日志大于10m就无法直接查看了，我看1.3版本加了容器日志切割而网站日志切割却是计划任务？
能否和容器日志一样自动切割呢？
且查看日志时默认是  last line ≤10m的日志

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持网站日志自动切割功能。

**Comment by Mystery00** [comment]
> 感谢反馈，我们会在后续版本考虑支持网站日志自动切割功能。

目前网站日志切割的定时任务依旧存在问题：
1. access日志超大时压缩失败（看着是 mholt/archiver 上游的问题）
2. 其他未知情况切割失败（系统日志中没有具体错误信息，猜测可能与网站名称特殊符号有关系）

![image](https://github.com/1Panel-dev/1Panel/assets/19162205/0245a1b5-4b6c-4b5a-8d92-7b6d1b25d492)

为了进一步分析问题，我增加了一点详细错误信息打印，详情请见 https://github.com/1Panel-dev/1Panel/pull/1458
