### ISSUE TITLE
建议增加动态dns(ddns)应用

### ISSUE THREAD

**Issue by cnmyn** [1Panel-dev/1Panel#1344]
### 1Panel 版本

1.3.2

### 请描述您的需求或者改进建议

建议增加动态dns应用(dnspod/alidns等)，一般家庭宽带使用电信/联通的可以获取公网IP，上行带宽一般在20-50Mbps，配合arm64/x86放在家做文件下载服务器，还是很香的，毕竟20-50Mbps的服务器带宽还是挺贵的。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。后续版本会考虑支持上述应用。

#250

**Comment by swRains** [comment]
用ddns go就行了

**Comment by Jengro777** [comment]
> 用ddns go就行了

ddns-go 我已经给appstore 提交了pr
https://github.com/1Panel-dev/appstore/pull/165

**Comment by wanghe-fit2cloud** [comment]
应用商店已经支持 ddns-go。
