### ISSUE TITLE
[BUG]无法添加周日的计划任务

### ISSUE THREAD

**Issue by ZhaiSoul** [1Panel-dev/1Panel#1345]
### 联系方式

微信：ZhaiSoul_650

### 1Panel 版本

1.3.2

### 问题描述

计划任务无法添加周日的计划任务

### 重现步骤

打开计划任务，选择创建计划任务，然后周期选择每周，选择周日，然后填写其他内容，最后保存

### 期待的正确结果

能够正常选择为周日

### 附加信息

![b6a3eb1bc7a20e037505d547f8f3c47](https://github.com/1Panel-dev/1Panel/assets/8712438/d13eab31-a74a-43ad-9779-633507d13aed)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本中修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.3.3 版本已发布。
