### ISSUE TITLE
1panel不支持基本方式升级[FEATURE]

### ISSUE THREAD

**Issue by liuhryme** [1Panel-dev/1Panel#1346]
### 1Panel 版本

1.3.2

### 请描述您的需求或者改进建议

建议通过脚本的方式进行升级 可以走批量升级的方式

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
参考论坛中这篇帖子：
https://bbs.fit2cloud.com/t/topic/1610
