### ISSUE TITLE
[FEATURE] ssh 日志记录按IP分组

### ISSUE THREAD

**Issue by yfdoor** [1Panel-dev/1Panel#1348]
### 1Panel 版本

1.3.2

### 请描述您的需求或者改进建议

ssh 日志是否可以增加按 IP 分组，几千条的失败记录，可能都是来自一个 IP 的攻击，按 IP 分组后，就可以快速查到哪些 IP 在攻击

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
