### ISSUE TITLE
[QUESTION]怎么为1panel自身配置域名

### ISSUE THREAD

**Issue by lxtqq** [1Panel-dev/1Panel#1351]
### 请描述您的问题

http://127.0.0.1:15539/dbc9333c44
和
http://127.0.0.1:15539/
配置都不对
![image](https://github.com/1Panel-dev/1Panel/assets/94205527/eeb7502f-7a23-4828-873f-5051e2f78273)
请问，我该如何配置

**Comment by deep-project** [comment]
面板设置里不是有个“域名绑定“么。访问的时候，记得加安全入口

**Comment by lxtqq** [comment]
> 面板设置里不是有个"域名绑定"么。访问的时候，记得加安全入口

好的，谢谢
