### ISSUE TITLE
[FEATURE] 优化Let's Encrypt申请证书流程

### ISSUE THREAD

**Issue by zhiqing0205** [1Panel-dev/1Panel#1353]
### 1Panel 版本

1.3.2

### 请描述您的需求或者改进建议

优化Let's Encrypt申请证书流程，相比与宝塔还是复杂了一些，

### 请描述你建议的实现方案

直接按一下然后自动续期就行了啊

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。申请证书的前提是需要用户输入 Acme 账号，这是必要条件。
目前证书列表中证书支持一键自动续签操作。
