### ISSUE TITLE
[FEATURE] 修改hosts的功能；以及修改网卡的功能

### ISSUE THREAD

**Issue by win9zhanhuaxi0ng** [1Panel-dev/1Panel#1355]
### 1Panel 版本

1.3.2

### 请描述您的需求或者改进建议

修改 hosts 功能可以参考 switchhosts 这个软件的操作，在内网集群中的使用会把其他节点的机器 ip 设置为内网域名，在 1panel 中能设置的话比较便捷。

修改网卡目前还是需要手动去 /etc/sysconfig/network-scripts 中进行修改，希望 1panel 在实现的时候增加 “恢复为DHCP自动获取IP及DNS” 这个功能。
使用场景：我有旁路由的需求，会手动更改网关以及dns，如果面板能够一键恢复dhcp自动获取就很方便

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
`修改 hosts 功能` 目前在 1Panel 最新版本已经支持。

**Comment by pangea86** [comment]
目前没看到修改host的功能。

**Comment by wanghe-fit2cloud** [comment]
> 目前没看到修改host的功能。

`工具箱` - `快速设置` 页面

**Comment by maninhill** [comment]
请问这个问题有进展吗？

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is there any progress on this issue?

**Comment by wanghe-fit2cloud** [comment]
中短期内暂无计划支持修改网卡等功能，望理解。
