### ISSUE TITLE
[BUG] 主机 - 防火墙 开放禁用端口

### ISSUE THREAD

**Issue by SaintWe** [1Panel-dev/1Panel#1359]
### 1Panel 版本

1.3.2

### 问题描述

**以下示例均在已安装 OpenResty 的情况下，系统为 Debian 11**

---

创建端口规则 -> **TCP/UDP** -> `80,443` -> 所有 IP -> 允许

|  协议   | 端口  | 状态  | 策略  | 指定 IP  | 操作  |
|  ----  | ----  |  ----  | ----  |  ----  | ----  |
| **TCP**  | `80,443` | 未使用  | 允许 | 所有 IP | - |
| **UDP**  | `80,443` | 未使用  | 允许 | 所有 IP | - |

无法 **删除** 这两条规则

此时若是编辑其中一条规则，如 TCP 修改为禁用则如下

|  协议   | 端口  | 状态  | 策略  | 指定 IP  | 操作  |
|  ----  | ----  |  ----  | ----  |  ----  | ----  |
| **TCP**  | `80,443` | 未使用  | 允许 | 所有 IP | - |
| **UDP**  | `80,443` | 未使用  | 允许 | 所有 IP | - |
| **TCP**  | `80` | 已使用 ( openresty )  | 拒绝 | 所有 IP | - |
| **TCP**  | `443` | 已使用 ( openresty )  | 拒绝 | 所有 IP | - |

单独的 80 和 443 的规则可删除，但拒绝策略无效

---

创建端口规则 -> **TCP** -> `80,443` -> 所有 IP -> 允许

|  协议   | 端口  | 状态  | 策略  | 指定 IP  | 操作  |
|  ----  | ----  |  ----  | ----  |  ----  | ----  |
| **TCP**  | `80` | 已使用 ( openresty )  | 允许 | 所有 IP | - |
| **TCP**  | `443` | 已使用 ( openresty )  | 允许 | 所有 IP | - |

正常，且可编辑删除

---

创建端口规则 -> **UDP** -> `80,443` -> 所有 IP -> 允许

|  协议   | 端口  | 状态  | 策略  | 指定 IP  | 操作  |
|  ----  | ----  |  ----  | ----  |  ----  | ----  |
| **UDP**  | `80` | 已使用 ( openresty )  | 允许 | 所有 IP | - |
| **UDP**  | `443` | 已使用 ( openresty )  | 允许 | 所有 IP | - |

正常，且可编辑删除

---

其他建议，BT 的防火墙 UI 可为端口规则添加备注，AppNode 的防火墙 UI 可查看具体是哪个进程使用了某个端口即便是 Docker 内的进程以及为具体的网卡配置端口规则

感谢开发，以上

### 重现步骤

创建端口规则 -> **TCP/UDP** -> `80,443`

**Comment by ssongliu** [comment]
感谢反馈！我们先在开发环境复现一下。

**Comment by wanghe-fit2cloud** [comment]
防火墙备注功能会在 v1.6.0 版本支持。
多端口无法删除的问题，我们会在 v1.5.2 修复。

**Comment by wanghe-fit2cloud** [comment]
v1.5.2 版本已发布。
