### ISSUE TITLE
[BUG]优化容器日志加载逻辑

### ISSUE THREAD

**Issue by YangHaoNing-CN** [1Panel-dev/1Panel#1360]
### 联系方式

3476809262

### 1Panel 版本

v1.3.2

### 问题描述

在google chorme 114.0.5735.110中，打开docker项目的日志，日志文件较大时并且开启追踪会导致浏览器内存从100M暴涨到近2G

### 重现步骤

**不确定**

在docker管理页面打开日志，日志大小为60M，开启追踪时，可能会出现该问题

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本优化容器日志加载逻辑。

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
