### ISSUE TITLE
[BUG] 创建反向代理时提示代号已存在

### ISSUE THREAD

**Issue by SaintWe** [1Panel-dev/1Panel#1363]
### 1Panel 版本

1.3.2

### 问题描述

在 OpenResty 创建反向代理时，信息填写完整并提交，但列表并没有刚创建的网站，重新使用相同的信息创建则提示已存在

查看 `/opt/1panel/apps/openresty/OpenResty/conf/conf.d` 目录下确实有 `conf` 文件，删除该配置文件后可正常创建

### 重现步骤

抱歉，没能复现成功

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述问题我们在开发测试环境也没有成功复现。
