### ISSUE TITLE
[BUG]文件上传无法选择文件夹，并且拖拽文件夹到上传框处点上传提示请求失败

### ISSUE THREAD

**Issue by MignonZhang** [1Panel-dev/1Panel#1364]
### 1Panel 版本

1.3.2

### 问题描述

文件上传无法选择文件夹，并且拖拽文件夹到上传框处点上传提示请求失败

### 重现步骤

1.点击上传，不支持选择文件夹，只能选择文件。
2.拖拽上传，可以拖拽多个文件和文件夹，但单击上传，报错。
![图片](https://github.com/1Panel-dev/1Panel/assets/27415482/6d19336c-7c22-4ac6-862d-e053652332fb)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持用户上传文件夹。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
