### ISSUE TITLE
[FEATURE]本地应用可视化配置，以及本地应用申请推送为云端应用

### ISSUE THREAD

**Issue by Jengro777** [1Panel-dev/1Panel#1369]
### 1Panel 版本

1.3.3

### 请描述您的需求或者改进建议

1、目前的本地应用添加很繁琐，希望添加可视化配置本地应用
2、本地应用页面，添加本地应用教程引导
3、可以将正常的本地运营提交审核为云端应用

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑上述需求。
