### ISSUE TITLE
[QUESTION] 计划任务的邮件提醒

### ISSUE THREAD

**Issue by KAWAKO-in-GAYHUB** [1Panel-dev/1Panel#1371]
### 请描述您的问题

希望当计划任务失败时，可以将失败信息以邮件形式发送给提前设置好的邮箱中。
不知道现在有没有这个功能，目前还没找到。。。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，当前版本还不支持设置邮件提醒。
我们会在后续版本中支持该需求。

**Comment by KAWAKO-in-GAYHUB** [comment]
谢谢，期待更新！
