### ISSUE TITLE
[FEATURE]推荐一款应用商店软件-监控域名和ssl证书

### ISSUE THREAD

**Issue by mouday** [1Panel-dev/1Panel#1373]
### 1Panel 版本

1Panel v1.3

### 请描述您的需求或者改进建议

推荐一款应用到应用商店

https://apps.fit2cloud.com/1panel

Domain Admin： 基于Python + Vue3.js 技术栈实现的域名和SSL证书监测平台

https://github.com/mouday/domain-admin

![](https://raw.githubusercontent.com/mouday/domain-admin/master/image/screencapture.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述应用。

#250
