### ISSUE TITLE
[FEATURE]备份账号->对象存储的厂商增加存储类型

### ISSUE THREAD

**Issue by ohmyga** [1Panel-dev/1Panel#1376]
### 1Panel 版本

1.3.2

### 请描述您的需求或者改进建议

例如: 腾讯云 COS
默认的存储类型是:  标准存储  这个类型的存储价格比较贵
建议增加个 归档存储 或者 深度归档存储类型...对与使用者来说至少能便宜30%
🙏

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
