### ISSUE TITLE
iOS移动端没适应好

### ISSUE THREAD

**Issue by Yuncheng77** [1Panel-dev/1Panel#1378]
### 1Panel 版本

1.3.3

### 请描述您的需求或者改进建议

iOS移动端没适应好

### 请描述你建议的实现方案

建议修复一下

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。当前版本移动端只适配了部分页面，后续版本持续优化。

**Comment by ssongliu** [comment]
1. 环境: arm64;
2. 异常界面： 所有容器子菜单 + 终端；
3. 电脑端打开没问题，部分移动端浏览器也能正常打开，ios 上 uc、safari 都显示空白。

**Comment by wanghe-fit2cloud** [comment]
v1.3.4 版本已发布。
