### ISSUE TITLE
[BUG]多个https二级域名使用ssl证书部署后，总是会使用第一个添加的ssl证书。

### ISSUE THREAD

**Issue by pcwhere** [1Panel-dev/1Panel#1379]
### 1Panel 版本

当前运行版本：v1.3.3

### 问题描述

域名1、s1.abc.com 证书s1_abc.crt
域名2、s2.abc.com 证书s2_abc.crt
域名3、s3.abc.com 证书s3_abc.crt
域名4、s4.abc.com 证书s4_abc.crt

当访问https://s1.abc.com 使用证书s1_abc.crt 正确的。
当访问https://s2.abc.com 浏览器同样看到是使用证书s1_abc.crt 。
……
后面的域名依然会使用证书s1_abc.crt

### 重现步骤

直接正常添加域名并开启https，配置好证书即可重现。

**Comment by deep-project** [comment]
我本地没有复现，创建的静态网站，手动导入的证书，你看看你配置文件里ssl_certificate对应的证书文件是否正确

**Comment by pcwhere** [comment]
![1panel-q-1](https://github.com/1Panel-dev/1Panel/assets/136625815/b221bcdc-92f0-4ed2-bd3a-8291c15ca3b2)
证书配置路径已经检查过都是在相应域名下的ssl目录。

![1panel-q-2](https://github.com/1Panel-dev/1Panel/assets/136625815/5fbf6c82-abd4-4143-a5fe-afbaea91fe47)
不论使用acme创建的证书还是手工创建的证书都是一样的效果。

![1panel-q-3](https://github.com/1Panel-dev/1Panel/assets/136625815/1bafcc5f-86fd-4101-acab-db2cd4fc3b7a)
目前已经没有了排查方向，计划准备采用终极方案测试，重装系统，重装1panel，做最终的测试。

**Comment by pcwhere** [comment]
经过终极大招，重装系统，重新不出1panel，问题解决。

**Comment by hnuzhoulin** [comment]
我也碰到这个问题，升级openresty到最新版本也一样。
