### ISSUE TITLE
[BUG]容器日志行数过多时不会渲染颜色

### ISSUE THREAD

**Issue by YangHaoNing-CN** [1Panel-dev/1Panel#1380]
### 联系方式

3476809262

### 1Panel 版本

v1.3.2

### 问题描述

docker容器日志行数过多时不会渲染颜色
![QQ截图20230615054516](https://github.com/1Panel-dev/1Panel/assets/83169812/7c6ea15d-e647-47c4-9155-b38c2a3b59d7)

![QQ截图!(https://github.com/1Panel-dev/1Panel/assets/8316920230615071738](https://github.com/1Panel-dev/1Panel/assets/83169812/e0c02498-cffd-46fe-9083-424fd9cdfdef)

### 重现步骤

行数较多时的日志

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中优化容器日志显示的这个问题。

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
