### ISSUE TITLE
华为云，安装面板后，外部无妨访问应用

### ISSUE THREAD

**Issue by ncpmeplmls0614** [1Panel-dev/1Panel#1384]
### 请描述您的问题

面板安装后，装了redis
安全组都打开了，放行全部端口。
防火墙也打开了。

后来工单咨询，华为云说是因为 面板安装redis的时候，默认地址绑定成了 127.0.0.1，要修改成0.0.0.0
但是我在应用那里，没找到调整的地方。

 
![image](https://github.com/1Panel-dev/1Panel/assets/131928393/ac90614f-c94d-4e8a-9b3a-5ad22771854b)

**Comment by ncpmeplmls0614** [comment]
我另一台机器，老版本就没这个问题

老版本没有锁死ip
![image](https://github.com/1Panel-dev/1Panel/assets/131928393/17e1cd96-dd88-46ed-abad-800f1f3f7909)

**Comment by zyyfit** [comment]
1.3.0及以上的版本，应用安装的时候，高级设置里，外部端口访问默认没有打开，需要勾一下，放开外部端口访问
