### ISSUE TITLE
[FEATURE]几点小建议

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1387]
### 1Panel 版本

1.3.3

### 几点小建议

1. 网站设置增加301重定向和404重定向
2. CC 防护增加封锁IP时间、UA黑白名单
3. 面板设置增加BasicAuth认证

### 附加信息

天下苦宝塔久矣，服务器面板国内市场一直被宝塔垄断，导致各种不好的问题发生，近期终于出了一个又牛逼又好看的面板，让我这种宝塔专业版用户也有转过来的欲望，希望你们继续完善，待我择机转过来。

一花独放不是春，百花齐放春满园！加油！

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布，支持了网站重定向功能。
