### ISSUE TITLE
[FEATURE]啥时候就有 .net环境了

### ISSUE THREAD

**Issue by wuxiaol1981** [1Panel-dev/1Panel#1388]
### 1Panel 版本

1.3

### 请描述您的需求或者改进建议

.NET环境 ，或者商店里加 进程管理器 supervisor

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持 supervisor。

**Comment by wanghe-fit2cloud** [comment]
最新版本已经支持 supervisor 进程守护功能。
> 中短期内我们还不会考虑支持 .NET 运行环境
