### ISSUE TITLE
[BUG] halo从2.6.0更新到2.6.1失败，然后打不开了

### ISSUE THREAD

**Issue by KAWAKO-in-GAYHUB** [1Panel-dev/1Panel#1389]
### 1Panel 版本

1.3.3~1.3.4

### 问题描述

刚才的1panel好像是1.3.3的版本吧，打开之后发现halo有新的更新（2.6.0-2.6.1），果断点击更新。更新一会儿之后显示更新失败，好像是因为没找到容器，我去容器列表里看了确实没有halo的容器。

然后我看到1panel也有更新，想着1panel更新之后会不会就好了（撞运气），就把1panel更新到1.3.4了。但是更新完还是没有好。

现在的结果就是halo更新失败，博客访问不了。

![image](https://github.com/1Panel-dev/1Panel/assets/54660064/2d3e797b-e349-45d8-b547-40be8d8d96f2)

![image](https://github.com/1Panel-dev/1Panel/assets/54660064/762f40b1-d7db-4cc8-8bc5-f1e3e53c8c60)

### 重现步骤

不知道先装一个halo2.6.0，然后再更新它，能不能复现出来

**Comment by KAWAKO-in-GAYHUB** [comment]
镜像还在（halo2.6.0），容器没了

![image](https://github.com/1Panel-dev/1Panel/assets/54660064/872e8179-50ec-479b-a60b-5fdb7e5be2d7)

**Comment by KAWAKO-in-GAYHUB** [comment]
我把docker-compose.yml中的2.6.1改成2.6.0，恢复回来了

![image](https://github.com/1Panel-dev/1Panel/assets/54660064/1ebae54b-0af8-431d-b5f3-3df3bbc654b6)


但是已安装这里还是显示的2.6.1，而且没法再更新到2.6.1了。。。

![image](https://github.com/1Panel-dev/1Panel/assets/54660064/9c1c8ffe-4a72-49ad-9eb4-85abd4bf4065)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下该问题。

**Comment by wanghe-fit2cloud** [comment]
问题原因是因为下载 Halo 最新版本镜像超时导致的。
可以先手动下载好镜像，然后在已安装应用列表点击 `重建` 按钮：

```shell
docker pull halohub/halo:2.6.1
```

拉取 docker hub 镜像超时的问题，可以进入容器菜单 - 配置页面，手动配置镜像加速器。

**Comment by KAWAKO-in-GAYHUB** [comment]
搞定了，谢谢！
