### ISSUE TITLE
[BUG] 无法更新

### ISSUE THREAD

**Issue by benzBrake** [1Panel-dev/1Panel#1390]
### 1Panel 版本

1.3.2

### 问题描述

点击更新提示无法连接外部网络。

### 重现步骤

登录面板，点击更新

### 相关日志输出

```shell
[2023-06-16 11:30:11] [INFO] load latest version failed, err: 无法成功请求最新版本，请检查服务器是否能够连接到外部网络环境。
```

### 附加信息

![无法更新](https://github.com/1Panel-dev/1Panel/assets/11323774/77b10ea1-deed-45d7-b165-fa36c118f71d)
这是部署在云服务器上的，如果真的无法访问网络，我是没有办法访问管理面板的。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1Panel 的资源包在 OSS 上，并开启了 CDN 全球加速。

上述报错是因为点击更新需要到 OSS 上获取最新版本号并下载最新版本离线包，超时了。
目前已知的云服务器厂商中，甲骨文服务器经常出现该问题。

**Comment by benzBrake** [comment]
那有没有离线更新的办法，我手动上传上去更新也行

**Comment by benzBrake** [comment]
PS：我用的的是 https://yecaoyun.com/

**Comment by wanghe-fit2cloud** [comment]
你可以先测试一下，该厂商的云服务器访问阿里 OSS 速度怎么样，有没有被限制。

**Comment by wimdoan** [comment]
阿里云环境,应用商店里都安装不了，提示104.18.125.25:443链接失败，阿里云服务器访问这个地址确实不通
