### ISSUE TITLE
[QUESTION]前端 打包 不能成功 出现 no such file or directory 错误

### ISSUE THREAD

**Issue by oyxeldbmxpr75** [1Panel-dev/1Panel#1392]
### 请描述您的问题

1Panel 版本
dev

## 问题描述
使用 npm run build:dev 打包 出现
no such file or directory

![image](https://github.com/1Panel-dev/1Panel/assets/117249066/b7143afa-62a8-4cb4-b7fe-b8a4dda1b6f2)

## 环境
npm 9.7.1
node 20.3.0

**Comment by wanghe-fit2cloud** [comment]
Makefile 文件中有提供打包相关指令。
