### ISSUE TITLE
[BUG] 无法使用android的chrome打开页面。

### ISSUE THREAD

**Issue by snitfk** [1Panel-dev/1Panel#1395]
### 联系方式

snitfk@gmail.com

### 1Panel 版本

1.3.4

### 问题描述

可以用PC chrome登陆，但使用ANDROID的CHROME打开地址就出现 “暂无权限访问 当前环境已经开启了安全入口登陆”

### 重现步骤

使用android访问就会出现

### 期待的正确结果

能够通过android进行登陆后台

**Comment by wanghe-fit2cloud** [comment]
1Panel 安装成功后，默认强制开启安全入口（entrance），可通过命令查看：
```shell
1pctl user-info
```

`
http://ip:port/entrance
`

**Comment by snitfk** [comment]
好的，明白了。谢谢。
