### ISSUE TITLE
不建站的情况下，添加了证书，请问证书的路径在哪里！

### ISSUE THREAD

**Issue by wfniub** [1Panel-dev/1Panel#1396]
### 请描述您的问题

没有建站只添加了证书，这种情况下证书的路径在哪里？

**Comment by wanghe-fit2cloud** [comment]
添加证书后数据保存在数据库中，可以在证书详情页面查看并复制证书。

**Comment by alexallen1** [comment]
证书文件已经在vps定时同步源站。请问1panel的证书的路径在哪里？

**Comment by wanghe-fit2cloud** [comment]
如图：

![Image](https://github.com/user-attachments/assets/19d3ff93-b467-4655-881d-35a3c4a0d475)
