### ISSUE TITLE
halo 版本 希望增加1.6

### ISSUE THREAD

**Issue by RobKing9** [1Panel-dev/1Panel#1397]
### 1Panel 版本

v1.3.2

### 请描述您的需求或者改进建议

halo 版本 希望增加1.6

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1Panel 应用商店暂时只考虑支持 Halo 2.x 版本，望理解。
如果是要支持 Halo 1.x 版本，推荐您在容器-编排页面，通过创建编排的方式来管理。
