### ISSUE TITLE
能否搞一个将docker的运行命令或者yml文件一键转换为本地应用的功能

### ISSUE THREAD

**Issue by wfniub** [1Panel-dev/1Panel#1398]
### 1Panel 版本

1.3

### 请描述您的需求或者改进建议

能否搞一个将docker的运行命令或者yml文件一键转换为本地应用的功能

### 请描述你建议的实现方案

能否搞一个将docker的运行命令或者yml文件一键转换为本地应用的功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持用户通过可视化页面来创建本地应用。

**Comment by Felmon** [comment]
> 感谢反馈，我们会在后续版本中支持用户通过可视化页面来创建本地应用。

@wanghe-fit2cloud 可否支持docker conpose文件直接转换成本地应用呢？现在大多数应用都是直接提供官方的docker compose或者docker run，作为小白同学也是一键复制粘贴为主，而做成可视化的话小白还得理解一下docker的常识：什么是port,什么是volume，什么是.env

我看目前应用主要是依赖的也是docker compose内容，而docker run也能通过[composerize](https://github.com/magicmark/composerize)转换成docker compose

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈，我们会在后续版本中支持用户通过可视化页面来创建本地应用。
> 
> @wanghe-fit2cloud 可否支持docker conpose文件直接转换成本地应用呢？现在大多数应用都是直接提供官方的docker compose或者docker run，作为小白同学也是一键复制粘贴为主，而做成可视化的话小白还得理解一下docker的常识：什么是port,什么是volume，什么是.env
> 
> 我看目前应用主要是依赖的也是docker compose内容，而docker run也能通过[composerize](https://github.com/magicmark/composerize)转换成docker compose

收到，我们会在后面版本考虑您的需求。

**Comment by Felmon** [comment]
> > > 感谢反馈，我们会在后续版本中支持用户通过可视化页面来创建本地应用。
> > 
> > 
> > @wanghe-fit2cloud 可否支持docker conpose文件直接转换成本地应用呢？现在大多数应用都是直接提供官方的docker compose或者docker run，作为小白同学也是一键复制粘贴为主，而做成可视化的话小白还得理解一下docker的常识：什么是port,什么是volume，什么是.env
> > 我看目前应用主要是依赖的也是docker compose内容，而docker run也能通过[composerize](https://github.com/magicmark/composerize)转换成docker compose
> 
> 收到，我们会在后面版本考虑您的需求。

可行的话，加上将本地应用提交云端审核的功能，1panel的生态化进展会快点

**Comment by wanghe-fit2cloud** [comment]
> > > > 感谢反馈，我们会在后续版本中支持用户通过可视化页面来创建本地应用。
> > > 
> > > 
> > > @wanghe-fit2cloud 可否支持docker conpose文件直接转换成本地应用呢？现在大多数应用都是直接提供官方的docker compose或者docker run，作为小白同学也是一键复制粘贴为主，而做成可视化的话小白还得理解一下docker的常识：什么是port,什么是volume，什么是.env
> > > 我看目前应用主要是依赖的也是docker compose内容，而docker run也能通过[composerize](https://github.com/magicmark/composerize)转换成docker compose
> > 
> > 
> > 收到，我们会在后面版本考虑您的需求。
> 
> 可行的话，加上将本地应用提交云端审核的功能，1panel的生态化进展会快点

感谢建议。

**Comment by wc7086** [comment]
> 感谢反馈，我们会在后续版本中支持用户通过可视化页面来创建本地应用。

1. 建议解析`docker run`命令后将解析内容展示在可视化界面中，再由用户点击确认拉起容器。
2. 可视化界面添加一个按钮，用于展示拉起容器使用的完整docker compose参数。
3. 允许用户直接编辑yaml文件。

**Comment by wc7086** [comment]
关这个 issue 是做好功能了还是没有相关计划啊。

**Comment by zhengkunwang223** [comment]
> 关这个 issue 是做好功能了还是没有相关计划啊。

短期内没有计划，希望理解
