### ISSUE TITLE
[FEATURE] 建议 https 的网站配置文件，默认支持 HTTP/2

### ISSUE THREAD

**Issue by geometryEuclid** [1Panel-dev/1Panel#1401]
### 1Panel 版本

v1.3.5

### 请描述您的需求或者改进建议

建议 https 的网站配置文件，默认支持 HTTP/2

将网站的配置文件，由
```nginx
listen 443 ssl; 
listen [::]:443 ssl; 
```

修改为
```nginx
listen 443 ssl http2; 
listen [::]:443 ssl http2; 
```

### 请描述你建议的实现方案

建议 https 的网站配置文件，默认支持 HTTP/2

将网站的配置文件，由
```nginx
listen 443 ssl; 
listen [::]:443 ssl; 
```

修改为
```nginx
listen 443 ssl http2; 
listen [::]:443 ssl http2; 
```

### 附加信息

我发现最新版的面板，OpenResty 的网站配置文件没有默认支持 HTTP/2 ，所以过来提醒一下。

**Comment by zhengkunwang223** [comment]
好的，感谢建议，后续版本修改

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
