### ISSUE TITLE
Docker 拉取镜像总是超时

### ISSUE THREAD

**Issue by RobKing9** [1Panel-dev/1Panel#1402]
### 联系方式

2768817839@qq.com

### 1Panel 版本

v1.3.2

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/78016475/6f4c434b-43cf-46f9-a354-20dd9d57cc8d)

### 重现步骤

配置镜像加速
![image](https://github.com/1Panel-dev/1Panel/assets/78016475/19dfbbc4-3ce3-4f6d-9408-fd772e743d28)

**Comment by wanghe-fit2cloud** [comment]
使用以下镜像加速配置：
```
https://hub-mirror.c.163.com
https://docker.m.daocloud.io
https://ghcr.io
https://mirror.baidubce.com
https://docker.nju.edu.cn
```
