### ISSUE TITLE
[FEATURE]php切换版本

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#1406]
### 1Panel 版本

1.3.5

### 请描述您的需求或者改进建议

php切换版本

有些应用更新版本后会提高php版本门槛，所以能够切换php版本算是刚需。我看之前也有不少这个需求：[issue1](https://github.com/1Panel-dev/1Panel/issues/671), [issue2](https://github.com/1Panel-dev/1Panel/issues/974)

以及docker容器希望可以加一列显示该容器对应的所创建的网站，容器一多，根本分不清哪个容器对应哪个网站

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述两个需求已经纳入迭代计划，后续版本支持。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
