### ISSUE TITLE
[DNS账户无法使用阿里云子用户]

### ISSUE THREAD

**Issue by FungJL** [1Panel-dev/1Panel#1408]
### 请描述您的问题

DNS账户名称限制在1-30字符，但阿里云子用户格式是@1294677222183217.onaliyun.com，超出限制无法登录

**Comment by zhengkunwang223** [comment]
下个版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。

**Comment by FungJL** [comment]
版本更新了，页面还是提示【长度1-30，名称不能含有/\:*?'"<>|等符号】

**Comment by wanghe-fit2cloud** [comment]
> 版本更新了，页面还是提示【长度1-30，名称不能含有/:*?'"<>|等符号】

实在不好意思，这个需求确实没有在 v1.4.0 版本中支持。

我们会在 v1.4 的小版本中尽快支持。

**Comment by zhengkunwang223** [comment]
> ### 请描述您的问题
> DNS账户名称限制在1-30字符，但阿里云子用户格式是@1294677222183217.onaliyun.com，超出限制无法登录

您好 DNS账户名称 可以随便填 不需要直接填  DNS账户名称

**Comment by wanghe-fit2cloud** [comment]
v1.4.2 版本已发布。

**Comment by FungJL** [comment]
> > ### 请描述您的问题
> > DNS账户名称限制在1-30字符，但阿里云子用户格式是@1294677222183217.onaliyun.com，超出限制无法登录
> 
> 您好 DNS账户名称 可以随便填 不需要直接填 DNS账户名称

感谢！已解决
