### ISSUE TITLE
[FEATURE] 希望计划任务类型增加长期任务选项

### ISSUE THREAD

**Issue by huoxue1** [1Panel-dev/1Panel#1409]
### 1Panel 版本

v1.3.5

### 请描述您的需求或者改进建议

计划任务类型添加长期任务选项,配置项：
+ 工作目录
+ shell命令
+ 日志保留天数
+ 重启策略 （总是重启，次数重启，不重启，策略重启: 当程序执行时间低于多少秒时就不重启）
+ 是否自启动

### 请描述你建议的实现方案

+ 新增一个cronjob.Type的常量类型
+ 新增长期任务时，不调用global.Cron中
+ 在HandleJob方法中判断类型后调用长期任务执行方法
+ 通过cmd的子协程执行方法，设置不超时执行，调用cmd.wait()方法，退出后判断该任务的重启策略进行对应处理
+ 在主程序启动时获取所有需要自启动的长期任务

**Comment by ssongliu** [comment]
感谢反馈！这里是想要增加一种长期任务的类型吗？任务不定时，而是根据前一个任务的执行状态和重启策略来决定下一次是否继续执行，或者说这里有具体的使用场景可以描述一下吗？

也建议加入我们的社区群，有什么需求或者问题方便随时沟通。

**Comment by huoxue1** [comment]
感谢开发者的回复！
+ 使用场景是在服务器上运行一些可执行文件时需要使用。
+ 现在的做法是要么使用系统的systemctl,或者使用类似的pm2等工具，或者直接使用docker.
+ 我希望可以通过一个前端可视化面板更加方便管理这种长期任务。
> 类似alist,虽然可以使用docker部署，但是对于一些小型linux机器来说直接运行二进制文件应该更加节省资源。

**Comment by ssongliu** [comment]
我们后面版本会考虑支持进程管理工具 supervisor ，不知道能不能满足你的需求。

**Comment by huoxue1** [comment]
> 我们后面版本会考虑支持进程管理工具 supervisor ，不知道能不能满足你的需求。

非常感谢，期待后续实现，希望项目越做越好

**Comment by wanghe-fit2cloud** [comment]
麻烦将 1Panel 升级到最新版本。
