### ISSUE TITLE
[BUG]无法启用GD库

### ISSUE THREAD

**Issue by MrDuer** [1Panel-dev/1Panel#1410]
### 联系方式

cqaid@qq.com

### 1Panel 版本

v1.3.5

### 问题描述

无法启用GD库

### 重现步骤

详见这个地方
https://bbs.fit2cloud.com/t/topic/734

### 期待的正确结果

正常使用GD库

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下该问题。

**Comment by cyril-cheng** [comment]
下拉里选GD就行了啊

**Comment by cyril-cheng** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/49748357/8aca5b86-91d8-42d9-af89-034f8cb8ba16)

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
