### ISSUE TITLE
[FEATURE]能否在一个平台对多个不同服务器进行管理。

### ISSUE THREAD

**Issue by snitfk** [1Panel-dev/1Panel#1412]
### 1Panel 版本

1.3.4

### 请描述您的需求或者改进建议

现在手上有多台服务器，要登陆不同的地址进行分别管理，是否可以开发出一个功能对多个服务器进行管理的功能。

### 请描述你建议的实现方案

可以进行切换服务器，统一记录分别管理。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。多服务器管理的需求我们在中短期内暂时还不考虑，望理解。

**Comment by maninhill** [comment]
多服务器管理建议您使用 [JumpServer](https://github.com/jumpserver/jumpserver)。

**Comment by z514987467** [comment]
> 多服务器管理建议您使用 [JumpServer](https://github.com/jumpserver/jumpserver)。

JumpServer没有容器和应用商店模块吧，感觉这两个模块挺好的
