### ISSUE TITLE
[BUG] 备份网站的时候可能会因为日志过大备份错误

### ISSUE THREAD

**Issue by lehhair** [1Panel-dev/1Panel#1413]
### 1Panel 版本

1.3.3

### 问题描述

如题，可以先在计划任务切割再备份

### 重现步骤

可

### 期待的正确结果

自动切割日志后备份

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，网站备份的功能，我们会在后续版本中持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
