### ISSUE TITLE
[FEATURE] .tar 压缩文件解压，提示“无法解压此文件”。

### ISSUE THREAD

**Issue by linye1111** [1Panel-dev/1Panel#1416]
### 1Panel 版本

v1.3.5

### 请描述您的需求或者改进建议

主机->文件
.tar.gz可以点击按钮解压，但.tar不支持点击按钮进行解压，提示“无法解压此文件”。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。我们先在本地环境复现一下该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。

**Comment by sinoserendipity** [comment]
v1.10.18-lts 也同样问题，无法解压！

**Comment by zhengkunwang223** [comment]
> v1.10.18-lts 也同样问题，无法解压！

可以使用命令行解压一下试试
