### ISSUE TITLE
[QUESTION]512内存 10G硬盘可以使用吗?

### ISSUE THREAD

**Issue by liudao01** [1Panel-dev/1Panel#1417]
### 请描述您的问题

512内存 10G硬盘可以使用吗?

**Comment by wanghe-fit2cloud** [comment]
单纯运行 1Panel 没有压力，比如管理主机、容器、计划任务等。

如果有建站和数据库等需求，应该就比较吃力了。

**Comment by liudao01** [comment]
想建站 wordpress  简单的搞个博客网站 ,吃力的话能用吗?

**Comment by liudao01** [comment]
希望能有个轻量化,精简版的面板

**Comment by wanghe-fit2cloud** [comment]
> 想建站 wordpress 简单的搞个博客网站 ,吃力的话能用吗?

这个需求就有些难度了，因为要在服务器上容器化运行 MySQL 数据库和 WordPress 博客。
建议增加一下服务器配置。
