### ISSUE TITLE
[BUG]能否国内镜像

### ISSUE THREAD

**Issue by yujianyue** [1Panel-dev/1Panel#1418]
### 联系方式

bintan@qq.com

### 1Panel 版本

1.35

### 问题描述

安装web服务器
error pulling image configuration: download failed after attempts=6: dial tcp 104.18.124.25:443: i/o timeout

安装mysql
error pulling image configuration: download failed after attempts=6: dial tcp 104.18.121.25:443: i/o timeout

### 重现步骤

安装web服务器
error pulling image configuration: download failed after attempts=6: dial tcp 104.18.124.25:443: i/o timeout

安装mysql
error pulling image configuration: download failed after attempts=6: dial tcp 104.18.121.25:443: i/o timeout

### 附加信息

应该是网络问题，建议建立国内下载镜像

**Comment by cyril-cheng** [comment]
https://hub-mirror.c.163.com
https://docker.m.daocloud.io
https://ghcr.io
https://mirror.baidubce.com
https://docker.nju.edu.cn

**Comment by wanghe-fit2cloud** [comment]
> https://hub-mirror.c.163.com https://docker.m.daocloud.io https://ghcr.io https://mirror.baidubce.com https://docker.nju.edu.cn

进入容器菜单 - 配置页面，添加上述镜像加速地址。

**Comment by yujianyue** [comment]
无法添加，官网文档多行文本框，演示demo.1panel.cn及我们网站一样单行文本框不可改，添加无效

![01114](https://github.com/1Panel-dev/1Panel/assets/12136614/2f022c6a-91ef-4896-afe0-086ef1b56aca)
![0017](https://github.com/1Panel-dev/1Panel/assets/12136614/4c8ded38-659f-48d0-bd54-677a235cd713)

**Comment by wanghe-fit2cloud** [comment]
demo 环境不支持修改操作。

点击右侧设置按钮添加就可以：
<img width="1187" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/4a3bb4fc-4844-4a64-b2be-9fbf7286ac27">

**Comment by yujianyue** [comment]
也已经说了，我们的面板和演示一样，都无法添加。添加JS报错如上图。
