### ISSUE TITLE
[QUESTION]创建的应用都访问不了。

### ISSUE THREAD

**Issue by sucooer** [1Panel-dev/1Panel#1419]
不支持纯ipv6的环境吗？创建的应用都访问不了

**Comment by wanghe-fit2cloud** [comment]
应用端口默认不允许外部访问，需要时可以在高级设置中选择放开。

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/2a05923b-9f61-4016-84fd-fb9c4b5a6750)
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/0d8c1be9-07d7-407a-9801-772f8f6e2e21)

**Comment by sucooer** [comment]
开放了的。。。
