### ISSUE TITLE
[FEATURE] 能够支持用户通过编写配置文件创建应用

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#1420]
### 1Panel 版本

v1.3.5

### 请描述您的需求或者改进建议

能够支持用户通过编写配置文件创建应用

因为很多时候用户内部的应用并不想上传到应用商店。希望能够通过用户自主创建应用的方式将应用托管给 1Panel 进行管理

**Comment by wanghe-fit2cloud** [comment]
1Panel 已经支持添加本地应用，具体教程参考论坛的这篇帖子：

[1Panel 本地应用创建技巧及第三方应用库举例](https://bbs.fit2cloud.com/t/topic/640/2)

**Comment by mx2913** [comment]
> 1Panel 已经支持添加本地应用，具体教程参考论坛的这篇帖子：
> 
> [1Panel 本地应用创建技巧及第三方应用库举例](https://bbs.fit2cloud.com/t/topic/640/2)

嗯好的，这个可以做到，后续会考虑提供面板网页版操作这种更方便的方式吗

**Comment by wanghe-fit2cloud** [comment]
后续版本可能会考虑支持页面话操作。
