### ISSUE TITLE
[BUG]监控中指标被遮挡

### ISSUE THREAD

**Issue by hncboy** [1Panel-dev/1Panel#1422]
### 1Panel 版本

1.3.5

### 问题描述

监控指标展示不全
![image](https://github.com/1Panel-dev/1Panel/assets/27755574/31e16936-fc15-498d-9cae-6a549d2fd9b3)

### 重现步骤

无

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
