### ISSUE TITLE
[QUESTION] 访问80端口自动下载文件，443端口没问题，怎么排查？

### ISSUE THREAD

**Issue by benzBrake** [1Panel-dev/1Panel#1424]
### 请描述您的问题

http://wenda.sheny.in/ 
https://wenda.sheny.in/

https://github.com/1Panel-dev/1Panel/assets/11323774/7140a698-82e7-43ce-9c14-ab8fb72e17e9

**Comment by 13604249613** [comment]
可能是 80 端口被占用到另一个程序上了，可以关闭你这个 web 服务使用 nmap 排除 80 端口是否正在使用。

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
