### ISSUE TITLE
[BUG]容器无法停止并删除

### ISSUE THREAD

**Issue by qxyysh** [1Panel-dev/1Panel#1426]
### 1Panel 版本

v1.3.5

### 问题描述

安装了spug容器，全选，删除，spug-db的容器无法删除。强制停止也无法停止。报错信息：
Error response from daemon: cannot stop container: b330417c9b55: permission denied

### 重现步骤

安装spug容器，全选，删除，留下spug-db的容器无法删除

### 期待的正确结果

spug-db的容器可以删除掉

### 相关日志输出

```shell
操作日志
容器	清理容器 [container]	成功	2023-06-22 15:03:41
容器	容器 [spug-db] 执行 [remove] []	成功	2023-06-22 14:55:22
容器	容器 [spug-db] 执行 [stop] []	失败	2023-06-22 14:53:27
容器	容器 [spug-db] 执行 [restart] []	失败	2023-06-22 14:52:58
容器	容器 [spug-db] 执行 [kill] []	失败	2023-06-22 14:52:36
容器	容器 [spug-db] 执行 [kill] []	失败	2023-06-22 14:51:43
容器	容器 [spug-db] 执行 [stop] []	失败	2023-06-22 14:50:42
容器	容器 [spug-db] 执行 [remove] []	失败	2023-06-22 14:50:21
容器	容器 [spug] 执行 [remove] []	成功	2023-06-22 14:50:11
```

### 附加信息

手动在终端中执行aa-remove-unknown，再执行docker stop <container id>就可以了。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。我在本地环境测试删除容器，没有复现上述问题。
麻烦提供一下 docker 安装命令或者 docker-compose.yaml 文件。
