### ISSUE TITLE
[BUG]无法备份根目录下的文件夹

### ISSUE THREAD

**Issue by powerfullz** [1Panel-dev/1Panel#1427]
### 1Panel 版本

v1.3.5

### 问题描述

如果备份根目录下的文件夹，tar会提示empty directory，但嵌套一层文件夹即可备份：

- `/examples/` 无法备份
- `/examples/data/`可以备份

### 重现步骤

备份一个放在根目录下的文件夹。

### 相关日志输出

```shell
stderr: tar: Cowardly refusing to create an empty archive Try 'tar --help' or 'tar --usage' for more information.
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们将在下个版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.3.6 版本已修复。
