### ISSUE TITLE
[FEATURE]让应用商店中Wordpress 支持 Memcached。

### ISSUE THREAD

**Issue by kuwo2016** [1Panel-dev/1Panel#1428]
### 1Panel 版本

1.3.5

### 请描述您的需求或者改进建议

Memcached， 既能提高访问的速度，同时还减低了数据库的负载，应用商店php8运行环境中，已经支持了 Memcached插件，然后还需要服务器端，要安装Memcached服务端，因为php8和Wordpress都是运行在docker镜像中，因此就算是在本地服务器中安装了Memcached服务端，也访问不到，需要，就是能不能，在Wordpress应用中，或者php8运行环境中，直接集成Memcached服务端。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
> 因此就算是在本地服务器中安装了Memcached服务端，也访问不到

如果 Wordpress 和 Memcached 都是在应用商店中安装，那可以使用服务名称或者容器名称进行连接。
> 如果安装 Memcached 时对外暴露了端口，也可以使用服务器内网 IP。
