### ISSUE TITLE
[BUG]我本地创建了一个应用，但是我明明把两个版本中的一个删除了之后，还是提示有新版本升级？

### ISSUE THREAD

**Issue by itworkzhang** [1Panel-dev/1Panel#1429]
### 1Panel 版本

1.3.5

### 问题描述

我本地创建了一个应用，但是我明明把两个版本中的一个删除了之后，还是提示有新版本升级？
![image](https://github.com/1Panel-dev/1Panel/assets/42572628/75424d6b-ff19-4f45-80e5-8238f746a7ac)

### 重现步骤

创建一个有多个版本的应用，删除其中较高版本的文件夹。
依旧安装时有那个高版本的选项，并且安装完低版本应用之后，提示可以升级。
但是无论安装和升级高版本的那个，报错提示找不到文件夹。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地开发测试环境复现一下该问题。

**Comment by zhengkunwang223** [comment]
删除之后点同步应用了吗？

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
