### ISSUE TITLE
docker 安装失败 

### ISSUE THREAD

**Issue by tornadoSmallPig** [1Panel-dev/1Panel#1430]
### 请描述您的问题

docker 安装失败 
![image](https://github.com/1Panel-dev/1Panel/assets/105829230/8c112d58-5b50-4231-8b8c-374554b17bbf)

**Comment by tornadoSmallPig** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/105829230/dde301b1-51cf-48a0-a3d3-c2d85e6f43b3)

**Comment by wanghe-fit2cloud** [comment]
如果是非 root 用户安装，需要添加 sudo 权限。

**Comment by tornadoSmallPig** [comment]
解决了，要切换到超级用户模式，sudo -i，感谢，没想到微软的服务器不是直接运行的超级用户
