### ISSUE TITLE
[FEATURE]建议安全-授权IP-能添加IP段

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1431]
### 1Panel 版本

1.3.5

### 请描述您的需求或者改进建议

建议安全-授权IP-能添加IP段

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持上述功能。

**Comment by LiXunGuan** [comment]
> 感谢反馈，我们会在后续版本中考虑支持上述功能。

可以考虑跟fail2ban整合

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
