### ISSUE TITLE
[FEATURE]支持通过数据库菜单来管理 PostgreSQL。

### ISSUE THREAD

**Issue by evanlong-me** [1Panel-dev/1Panel#1432]
### 联系方式

github Issue 回复

### 1Panel 版本

v1.3.5

### 问题描述

应用商店安装 `postgresql` 后，在数据库菜单页面中无法显示和管理

### 重现步骤

应用商店安装 `postgresql` 后
![image](https://github.com/1Panel-dev/1Panel/assets/52912949/4d66698d-359c-4bae-a346-5395280ab88c)

在数据库中无法显示和管理
![image](https://github.com/1Panel-dev/1Panel/assets/52912949/4fe62656-c5b2-425b-97ae-2afaa3d8ea7b)

### 期待的正确结果

安装 `postgresql` 成功后，在数据库中显示 `postgresql` 这一项

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持通过数据库菜单来管理 PostgreSQL。

**Comment by Hxina** [comment]
> 感谢反馈，我们会在后续版本中支持通过数据库菜单来管理 PostgreSQL。

MongoDB 也不显示。

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈，我们会在后续版本中支持通过数据库菜单来管理 PostgreSQL。
> 
> MongoDB 也不显示。

是的，当前版本只支持了页面化操作 MySQL 和 Redis 两种数据库。

**Comment by wanghe-fit2cloud** [comment]
重复 #758
