### ISSUE TITLE
[BUG]应用商店没有翻页按钮

### ISSUE THREAD

**Issue by cyril-cheng** [1Panel-dev/1Panel#1433]
### 1Panel 版本

1.3.5

### 问题描述

应用商店没有翻页按钮。我安装了第三方商店之后，应用数量超过了一页的数量，一页后面的应用无法显示，只能通过搜索使用。

### 重现步骤

https://github.com/okxlin/appstore

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.3.6 版本已发布，在应用商店列表支持分页。
