### ISSUE TITLE
镜像加速[BUG]

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1436]
### 1Panel 版本

v1.3.5

### 问题描述

具体问题在 /etc/docker/daemon.json 文件中，回车的那一行被解析成了 “” ，导致json配置失效，进而导致 docker 重启失效

![image](https://github.com/1Panel-dev/1Panel/assets/30285739/4dd031b9-c019-402e-adb4-6a00fbf9793b)

### 重现步骤

镜像加速设置那一栏
填写镜像加速地址
如果最后一个字符是回车，则会出问题（即重新起一行）

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期发布的版本中修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.3.6 版本已修复。
