### ISSUE TITLE
[FEATURE]希望可以直接从文件路径进入对应目录的终端。

### ISSUE THREAD

**Issue by Moon-du** [1Panel-dev/1Panel#1442]
### 1Panel 版本

1.3.5

### 请描述您的需求或者改进建议

主机 - 文件，希望可以直接从文件路径进入对应目录的终端，这个体验很好。

### 请描述你建议的实现方案

![WX20230625-173735](https://github.com/1Panel-dev/1Panel/assets/69743019/9e088da4-61b5-4dbf-8a84-c77176869d8f)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复 #958
