### ISSUE TITLE
[QUESTION] 我现在无法删除应用

### ISSUE THREAD

**Issue by trucyCc** [1Panel-dev/1Panel#1445]
### 请描述您的问题

![image](https://github.com/1Panel-dev/1Panel/assets/126760204/a8938a83-9921-4a76-a43f-a86bb2cb4cbf)
这个错误该怎么解决

**Comment by zhengkunwang223** [comment]
等下个小版本修复此问题

**Comment by wanghe-fit2cloud** [comment]
v1.3.6 版本已修复。
