### ISSUE TITLE
服务正常，但是一直进不去登录界面是怎么回事？[QUESTION]

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1448]
### 请描述您的问题

<img width="667" alt="wecom-temp-c899aca667470bd063b30e2373e03467" src="https://github.com/1Panel-dev/1Panel/assets/30285739/74fd47d9-2e60-4a50-a8a2-6050c4e86873">
<img width="773" alt="wecom-temp-19027c994fc83f8076939b0a4859d8b0" src="https://github.com/1Panel-dev/1Panel/assets/30285739/ff4c38ea-85a1-46a5-8b23-f020ff072304">
<img width="910" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/30285739/a5b8c5ca-19d2-4bb1-9b5f-7df71c858cd2">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在 v1.3.6 版本中修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.3.6 版本已修复。
