### ISSUE TITLE
构建mysql8.0版本报错[BUG]

### ISSUE THREAD

**Issue by NicknamedCoco** [1Panel-dev/1Panel#1451]
### 1Panel 版本

1.3.5在线安装

### 问题描述

在线版本创建的，应该是最新版本，创建mysql8.0版本，但是报错，好像是目录挂载的问题

### 重现步骤

我自定义了1panel的安装目录到本地的一个目录，但是我没有新建这个目录，后来应该是应用自己建好了这个目录，
然后我挂载mysql8.0版本就报错了，但是部署5.0的mysql没问题，不知道啥情况

**Comment by NicknamedCoco** [comment]
![6f72257bbb10f5dcb4694b46f13ce26](https://github.com/1Panel-dev/1Panel/assets/38173260/01893d36-c0bf-495c-af88-0bb3cec0cbb7)
然后我重建wordpress也失败，说找不到这个文件，实际上linux上是有这个docker-compose文件的，，

**Comment by wanghe-fit2cloud** [comment]
> ![6f72257bbb10f5dcb4694b46f13ce26](https://user-images.githubusercontent.com/38173260/248642384-01893d36-c0bf-495c-af88-0bb3cec0cbb7.png) 然后我重建wordpress也失败，说找不到这个文件，实际上linux上是有这个docker-compose文件的，，

根据错误信息来看，就是因为缺失 yml 文件导致的。

你可以进入应用文件夹来确认一下文件是否存在：
```shell
ls -l /linuxPanel/1panel/apps/wordpress/wordpress
```

**Comment by NicknamedCoco** [comment]
这个文件是存在的，但是还是报错了

wanghe ***@***.***> 于2023年6月26日周一 17:21写道：

**Comment by wanghe-fit2cloud** [comment]
应该不是一个共性的问题。进微信交流群添加一下我好友，我远程看一下你的环境。
