### ISSUE TITLE
[BUG] 甲骨文 ARM 创建运行环境 1panel-php-8.2.5 失败

### ISSUE THREAD

**Issue by comdotwww** [1Panel-dev/1Panel#1455]
### 1Panel 版本

v1.3.5

### 问题描述

镜像 build 失败:failed to solve: process "/bin/sh -c apk --no-cache add tzdata && cp \"/usr/share/zoneinfo/$TZ\" /etc/localtime && echo \"$TZ\" > /etc/timezone" did not complete successfully: exit code: 1

## 系统信息
发行版本 ubuntu-20.04
内核版本 5.15.0-1035-oracle
系统类型 aarch64
## 步骤
网站-->运行环境-->创建运行环境，配置信息如图：
![image](https://github.com/1Panel-dev/1Panel/assets/62149924/854ad2c3-d9ae-4fa2-9878-a097b61dd743)
![image](https://github.com/1Panel-dev/1Panel/assets/62149924/8ec042bf-43e2-4eb0-97e0-c3aa1f6d5b73)

## 相应的日志审计
![image](https://github.com/1Panel-dev/1Panel/assets/62149924/3c5470d7-de9c-4c2e-856e-07dbc78bf649)
![image](https://github.com/1Panel-dev/1Panel/assets/62149924/c91a2062-36c1-481c-b241-df23f28fd9a6)

### 期待的正确结果

成功创建运行环境1panel-php-8.2.5

### 相关日志输出

```shell
镜像 build 失败:failed to solve: process "/bin/sh -c apk --no-cache add tzdata && cp \"/usr/share/zoneinfo/$TZ\" /etc/localtime && echo \"$TZ\" > /etc/timezone" did not complete successfully: exit code: 1
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述报错是因为在 PHP 容器内部执行 apk add tzdata 超时导致的（容器内部不能正常访问外网）。

1、可以先检查 `容器菜单` - `配置页面`，iptables 开关是否关闭了。
2、关闭系统防火墙之后，重启网络和 docker，再重新添加 PHP 运行环境。
