### ISSUE TITLE
Ask for increased litespeedtech support

### ISSUE THREAD

**Issue by zining3235** [1Panel-dev/1Panel#1457]
### 1Panel 版本

1.3

### 请描述您的需求或者改进建议

Ask for increased litespeedtech support

### 请描述你建议的实现方案

Ask for increased litespeedtech support

**Comment by wanghe-fit2cloud** [comment]
Thank you for your feedback. We have currently integrated OpenResty and do not plan to consider litespeedtech in the near future. We appreciate your understanding!
