### ISSUE TITLE
[BUG] Composer 无法使用

### ISSUE THREAD

**Issue by Ghost-chu** [1Panel-dev/1Panel#1459]
### 联系方式

@Ghost-chu

### 1Panel 版本

v1.3.6

### 问题描述

通过 1Panel 新创建的 `1panel-php:8.0.28` 和 `1panel-php:8.1.18` 中的 `composer` 命令运行没有任何效果。

### 重现步骤

网站 -> 运行环境 -> 创建运行环境 -> PHP8 -> 选择 `8.0.28` 或 `8.1.18` 其他版本暂未测试 -> 镜像名称默认，创建运行环境。

使用新创建的运行环境创建一个网站，编排->进入对应网站容器，使用 `composer` 命令，没有任何输出。

### 期待的正确结果

应执行 composer 命令并打印默认帮助信息。

### 相关日志输出

```shell
/www # cd sites/discuss.barbatos.club/index/
/www/sites/discuss.barbatos.club/index # composer
/www/sites/discuss.barbatos.club/index # composer --help
/www/sites/discuss.barbatos.club/index # composer --version
/www/sites/discuss.barbatos.club/index # /usr/bin/com
comm      composer
/www/sites/discuss.barbatos.club/index # /usr/bin/com
comm      composer
/www/sites/discuss.barbatos.club/index # /usr/bin/com
comm      composer
/www/sites/discuss.barbatos.club/index # /usr/bin/composer
/www/sites/discuss.barbatos.club/index #
```

![image](https://github.com/1Panel-dev/1Panel/assets/30802565/0850d291-3976-4a6f-b98c-cc878c12972d)

**Comment by zhengkunwang223** [comment]
好的 我们在本地复现一下

**Comment by Ghost-chu** [comment]
补充：PHP7 的镜像不受影响。

似乎是 PHP8 的禁用函数默认参数存在问题，在清空 disable_functions 后，composer 恢复了正常。

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
