### ISSUE TITLE
[BUG]保存防盗链自动下载文件

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1460]
### 1Panel 版本

1.3.6

### 问题描述

保存两次防盗链访问网站就会自动下载文件，日志是正常的

### 重现步骤

创建网站-保存防盗链两次-访问网站

### 期待的正确结果

保存防盗链无问题

### 相关日志输出

```shell
172.18.0.1 -  27/Jun/2023:08:44:46 +0800 "GET /index.php" 200
172.18.0.1 -  27/Jun/2023:08:44:46 +0800 "GET /index.php" 200
172.18.0.1 -  27/Jun/2023:08:44:47 +0800 "GET /index.php" 200
172.18.0.1 -  27/Jun/2023:08:44:47 +0800 "GET /index.php" 200
172.18.0.1 -  27/Jun/2023:08:44:51 +0800 "GET /index.php" 200
```

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/86153432/e9222269-5600-47d2-919b-356ae15b1112)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述问题已复现，我们会在后续版本中修复。

**Comment by benzBrake** [comment]
卧槽，我找了很久，就是这个功能引起的  https://github.com/1Panel-dev/1Panel/issues/1424

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
