### ISSUE TITLE
[BUG] OpenResty环境不全导致部分客户端无法使用ssl

### ISSUE THREAD

**Issue by Huiyicc** [1Panel-dev/1Panel#1461]
### 联系方式

1925473403@qq.com

### 1Panel 版本

v1.3.5

### 环境
系统：Ubuntu 22.04 LTS
1Panel 版本：v1.3.5
OpenResty版本：1.21.4.1
### 问题描述
ssl在大多数情况下都是正常的,但是当使用cpp-netlib库的客户端请求ssl api的时候就会出现"tlsv1 alert internal error"报错,查询日志时看到了如下报错:cannot load certificate "data:": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE) while SSL handshaking  
当我停掉OpenResty容器的nginx使用ubuntu apt安装的nginx时一切正常

### 重现步骤

使用cpp-netlib请求OpenResty创建的ssl就会出现

### 相关日志输出

```shell
cannot load certificate "data:": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE) while SSL handshaking
```

**Comment by zhengkunwang223** [comment]
证书是通过 1Panel 申请的吗

**Comment by Huiyicc** [comment]
> 

最开始确实是使用1Panel 申请的，报这个错误，查了很久，后来发现PEM_read_bio_X509_AUX问题之后换过阿里云申请的证书，机构签发的证书都是这样，最后把OpenResty容器停止然后在系统上用apt安装了nginx手动配置了ssl，发现没有这个问题

**Comment by zhengkunwang223** [comment]
> > 
> 
> 最开始确实是使用1Panel 申请的，报这个错误，查了很久，后来发现PEM_read_bio_X509_AUX问题之后换过阿里云申请的证书，机构签发的证书都是这样，最后把OpenResty容器停止然后在系统上用apt安装了nginx手动配置了ssl，发现没有这个问题

我们怎么能复现呢 能否提供复现步骤

**Comment by Huiyicc** [comment]
> > > 
> > 
> > 
> > 最开始确实是使用1Panel 申请的，报这个错误，查了很久，后来发现PEM_read_bio_X509_AUX问题之后换过阿里云申请的证书，机构签发的证书都是这样，最后把OpenResty容器停止然后在系统上用apt安装了nginx手动配置了ssl，发现没有这个问题
> 
> 我们怎么能复现呢 能否提供复现步骤

应该挺容易复现的，因为这个问题是在服务器上出现的，晚些我试试用电脑看看能不能复现

**Comment by wanghe-fit2cloud** [comment]
> > > > 
> > > 
> > > 
> > > 最开始确实是使用1Panel 申请的，报这个错误，查了很久，后来发现PEM_read_bio_X509_AUX问题之后换过阿里云申请的证书，机构签发的证书都是这样，最后把OpenResty容器停止然后在系统上用apt安装了nginx手动配置了ssl，发现没有这个问题
> > 
> > 
> > 我们怎么能复现呢 能否提供复现步骤
> 
> 应该挺容易复现的，因为这个问题是在服务器上出现的，晚些我试试用电脑看看能不能复现

请问，你那儿是否已经有结果？

**Comment by Huiyicc** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 最开始确实是使用1Panel 申请的，报这个错误，查了很久，后来发现PEM_read_bio_X509_AUX问题之后换过阿里云申请的证书，机构签发的证书都是这样，最后把OpenResty容器停止然后在系统上用apt安装了nginx手动配置了ssl，发现没有这个问题
> > > 
> > > 
> > > 我们怎么能复现呢 能否提供复现步骤
> > 
> > 
> > 应该挺容易复现的，因为这个问题是在服务器上出现的，晚些我试试用电脑看看能不能复现
> 
> 请问，你那儿是否已经有结果？

抱歉最近有些忙,没时间复现,代码环境是公司服务器的,目前只在cpp-netlib这个库上出现了这个问题,我这周末会尝试在虚拟机上复现

**Comment by binaryYuki** [comment]
> > > > 
> > > 
> > > 
> > > 最开始确实是使用1Panel 申请的，报这个错误，查了很久，后来发现PEM_read_bio_X509_AUX问题之后换过阿里云申请的证书，机构签发的证书都是这样，最后把OpenResty容器停止然后在系统上用apt安装了nginx手动配置了ssl，发现没有这个问题
> > 
> > 
> > 我们怎么能复现呢 能否提供复现步骤
> 
> 应该挺容易复现的，因为这个问题是在服务器上出现的，晚些我试试用电脑看看能不能复现

Hi,

我遇见了相同的问题 出现在尝试使用反向代理代理 fastapi 和 gin 项目的时候 

查询log 显示
```
2024/04/17 22:04:17 [error] 261#261: *132 cannot load certificate "data:": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE) while SSL handshaking, client: 172.71.122.127, server: 0.0.0.0:443
2024/04/17 22:04:17 [error] 261#261: *133 cannot load certificate "data:": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE) while SSL handshaking, client: 172.68.92.131, server: 0.0.0.0:443
2024/04/17 22:04:18 [error] 261#261: *134 cannot load certificate "data:": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE) while SSL handshaking, client: 172.70.163.31, server: 0.0.0.0:443
2024/04/17 22:04:18 [error] 261#261: *135 cannot load certificate "data:": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE) while SSL handshaking, client: 172.71.122.143, server: 0.0.0.0:443
2024/04/17 22:04:18 [error] 261#261: *136 cannot load certificate "data:": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE) while SSL handshaking, client: 172.70.162.19, server: 0.0.0.0:443
2024/04/17 22:04:19 [error] 261#261: *137 cannot load certificate "data:": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE) while SSL handshaking, client: 172.71.122.143, server: 0.0.0.0:443
```

这个问题似乎只在使用反向代理的时候出现
