### ISSUE TITLE
[BUG]web项目不兼容firefox浏览器

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#1465]
### 1Panel 版本

1.3.6

### 问题描述

大多数反代网站或自建站在firefox会报错：MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING,看原因是因为ff默认ocsp启用staplping
[https://really-simple-ssl.com/mozilla_pkix_error_required_tls_feature_missing/](https://really-simple-ssl.com/mozilla_pkix_error_required_tls_feature_missing/)
所以最好ssl启用时默认加上以下nginx配置以兼容ff：
   ```
    ssl_stapling on;
    ssl_stapling_verify on;
```

### 重现步骤

1

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述问题我们在下个版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.7.1 版本已发布。
