### ISSUE TITLE
[FEATURE]支持查看备份进度并且支持取消备份。

### ISSUE THREAD

**Issue by hncboy** [1Panel-dev/1Panel#1467]
### 1Panel 版本

1.3.6

### 请描述您的需求或者改进建议

![99b666a436d6ec527efeb659d53176b](https://github.com/1Panel-dev/1Panel/assets/27755574/ee619f39-5719-4b9c-8f0e-c3deef534de6)
备份时不知道备份进度并且无法点击任何按钮也无法关闭。能不能支持查看备份进度并且支持取消备份。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，当前版本在制作快照时是全量备份的，包括了应用到镜像等。
后续版本会持续优化，并支持查看进度、取消备份等操作。

**Comment by wanghe-fit2cloud** [comment]
最新版本已支持查看快照制作进度，并支持失败重试。
