### ISSUE TITLE
[FEATURE] PHP基础扩展

### ISSUE THREAD

**Issue by HuaData** [1Panel-dev/1Panel#1468]
### 1Panel 版本

1.36

### 请描述您的需求或者改进建议

安装PHP容器时应像bt面板那样默认安装些基础的扩展，这样大大提高易用性以及减少一些因为扩展引起的问题

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中持续优化。

**Comment by wanghe-fit2cloud** [comment]
PHP扩展相关需求的讨论，统一汇总到该 issue #1636
