### ISSUE TITLE
[FEATURE] PHP扩展预选过少

### ISSUE THREAD

**Issue by HuaData** [1Panel-dev/1Panel#1469]
### 1Panel 版本

1.36

### 请描述您的需求或者改进建议

建议把PHP扩展预选列表进行完善，很多情况下用户并不能输入完全一样的扩展名从而导致安装扩展未成功

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中持续优化。

**Comment by gitzaai** [comment]
你看看默认已经安装的已经不少了，剩下的就是看自己选择了

**Comment by HuaData** [comment]
你理解错了，我这边的意思是用户去安装扩展时提供的扩展列表不全 贵公司的意思是让用户自行输入扩展名但并非所有客户都能只字不差的输入扩展名从而导致扩展安装失败 我这边的建议呢是让贵公司完善一下预选的扩展列表最好做一个搜索框让用户更方便的去安装扩展

**Comment by zhengkunwang223** [comment]
> 你理解错了，我这边的意思是用户去安装扩展时提供的扩展列表不全 贵公司的意思是让用户自行输入扩展名但并非所有客户都能只字不差的输入扩展名从而导致扩展安装失败 我这边的建议呢是让贵公司完善一下预选的扩展列表最好做一个搜索框让用户更方便的去安装扩展

PHP 扩展列表 https://1panel.cn/docs/user_manual/websites/php/#php_1

**Comment by HuaData** [comment]
好的感谢

**Comment by HuaData** [comment]
建议把这个放安装扩展的那个页面

**Comment by gitzaai** [comment]
1panel直接点击你要补充的扩展就行，不用码字输入了，例如8.2.5内置的扩展如下https://forum.gitzaai.com/d/105  而且1panel是国内为数不多的把fileinfo作为标配的
