### ISSUE TITLE
[FEATURE]期待对Rocky的原生支持

### ISSUE THREAD

**Issue by bh1xaq** [1Panel-dev/1Panel#1471]
### 1Panel 版本

1.3.6

### 请描述您的需求或者改进建议

目前安装脚本不支持Rocky系统，（因为Docker的问题）需要手动安装。

### 请描述你建议的实现方案

修改安装脚本支持，看看是不是可以通过yum方式安装docker？

### 附加信息

![WZ~_ESEYN5ODFDA4PXDN_D7](https://github.com/1Panel-dev/1Panel/assets/16686956/59d67b36-b1cd-4a87-82b7-8bd98631a4e6)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，在线安装脚本不支持 Rocky 系统的问题，可以尝试使用下面的脚本来安装 Docker：
```shell
bash <(curl -sSL https://linuxmirrors.cn/docker.sh)
```

之后再运行 1Panel 在线安装脚本就会跳过安装 Docker。

**Comment by bh1xaq** [comment]
感谢回复，我手动可以安装Docker。只是建议后续可以集成到安装脚本里。：）
