### ISSUE TITLE
不支持  Rocky linux 9

### ISSUE THREAD

**Issue by freedom45678** [1Panel-dev/1Panel#1472]
### 1Panel 版本

安装失败

### 请描述您的需求或者改进建议

[1Panel Log]: ======================= 开始安装 ======================= 
设置 1Panel 安装目录（默认为/opt）：
[1Panel Log]: 您选择的安装路径为 /opt 
[1Panel Log]: ... 在线安装 docker 
# Executing docker install script, commit: c2de0811708b6d9015ed1a2c80f02c9b70c8ce7b

ERROR: Unsupported distribution 'rocky'

[1Panel Log]: ... 启动 docker 
Failed to enable unit: Unit file docker.service does not exist.
Failed to start docker.service: Unit docker.service not found.
[1Panel Log]: docker 安装失败

### 请描述你建议的实现方案

添加 对 Rocky linux 9 的支持

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，在线安装脚本不支持 Rocky 系统的问题，可以尝试使用下面的脚本来安装 Docker：

```shell
bash <(curl -sSL https://linuxmirrors.cn/docker.sh)
```

之后再运行 1Panel 在线安装脚本就会跳过安装 Docker。
