### ISSUE TITLE
[BUG]服务内部错误: disk I/O error

### ISSUE THREAD

**Issue by sshouc** [1Panel-dev/1Panel#1473]
### 联系方式

houshaoshao@foxmail.com

### 1Panel 版本

v1.3.6

### 问题描述

服务内部错误: disk I/O error (4874)

### 重现步骤

安装应用商店的wiki.js后出现。

### 附加信息

![1687921994155](https://github.com/1Panel-dev/1Panel/assets/53165970/84160b2b-eec2-4328-bc86-34c2ce1887c4)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，刚在本地开发环境没有复现上述问题。

你可以先排查一下是不是由于磁盘空间不足或者磁盘故障导致的无法正常写入数据。
如果当前用户没有权限访问数据库文件，也有可能存在上述问题。

**Comment by XiaoWouU** [comment]
希望可以帮助到你https://blog.528688.cn/archives/1705498460869

**Comment by JCVICTORSUN** [comment]
> 希望可以帮助到你https://blog.528688.cn/archives/1705498460869

链接失效啦
