### ISSUE TITLE
[FEATURE]关于SSL证书功能的建议

### ISSUE THREAD

**Issue by okxlin** [1Panel-dev/1Panel#1475]
### 1Panel 版本

v1.3.6

## 1.增加多组织证书签发
希望可以添加如`acme.sh`那样的`ZeroSSL`、`Google`等多组织证书签发；

## 2.增加自签证书功能
本身已经在启用面板`https`访问功能那边有了，这边要是集成一下，感觉也挺好，

而且用自签名`SSL`证书搭配非对应的域名作为默认站点，也可以防止源站`IP`泄漏。

## 3.证书添加备注功能
`cloudflare`导入的15年证书，当导入多个时，在网站功能启用`https`时选择，完全无法知道是哪一个。

还有空白证书也是无法知道哪一个。

## 4.集成导入SSL证书功能
目前导入`SSL`证书只能在站点启用`https`时导入，希望还能够集成到证书管理这个大项里。

## 5.显示证书签发完整日志
经常在群里看到有网友证书签发错误，要是显示完整日志，可能方便排查问题

**Comment by cyril-cheng** [comment]
还是希望能指定申请ECC证书，目前面板只能申请R3证书

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中持续优化。

**Comment by ybw0014** [comment]
本来想提个新的issue，结果发现我要提的就是第四点。

**Comment by wanghe-fit2cloud** [comment]
> 本来想提个新的issue，结果发现我要提的就是第四点。

感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
