### ISSUE TITLE
[FEATURE] 计划任务增加备份容器和快照

### ISSUE THREAD

**Issue by zhiqing0205** [1Panel-dev/1Panel#1480]
### 1Panel 版本

1.3.6

### 请描述您的需求或者改进建议

计划任务增加备份容器和快照的功能，现在容器是只能备份到本地，且需要手动备份

### 请描述你建议的实现方案

在计划任务内加入队容器和系统快照的备份

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
上述需求提到的手动备份容器，是不是可以理解为手动执行 docker commit 命令，将容器保存为镜像？

**Comment by zhiqing0205** [comment]
![](https://img.ziuch.top/i/2023/06/28/202306282259050_649c4ad886f00.png)
这个我不是很清楚，其实我就是看到在应用商店已安装下，就会有这个备份选项，我希望可以直接在计划任务里选择进行备份。还有就是，虽然应用商店内的应用都是docker，自己搭建的容器可不可以也支持备份呢

**Comment by wanghe-fit2cloud** [comment]
1、后续版本可以增加一种计划任务类型：备份应用商店应用。
2、容器如果需要备份（主要涉及到镜像和持久化数据），可以添加类型为备份目录的计划任务，目标设置为自定义的持久化目录即可。然后就是镜像大多会存在于仓库中，可以不考虑。

**Comment by zhiqing0205** [comment]
应用商店内的应用也是docker容器啊，为啥不能和自己的容器一样的流程备份呢

**Comment by wanghe-fit2cloud** [comment]
应用备份的是 docker-compose 相关配置和持久化目录。

**Comment by zhiqing0205** [comment]
原来如此，感谢您的耐心解答

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
