### ISSUE TITLE
[BUG]创建网站（运行环境）提示名称已存在

### ISSUE THREAD

**Issue by gitzaai** [1Panel-dev/1Panel#1482]
### 1Panel 版本

v1.3.6

### 问题描述

创建网站（运行环境）提示名称已存在，其余创建一键部署、反向代理，静态网站均无问题。
我删除了网站，翻开日志也提示成功，打开ssh也没看到openresty/www/sites有相关目录。
但是创建网站（运行环境）提示名称已存在，更换其他域名却没问题

### 重现步骤

重启服务器和openresty问题依旧

**Comment by zhengkunwang223** [comment]
应该是应用重名了 PHP运行环境创建的 PHP 应用 默认为网站域名去掉小数点 后面优化一下这个提示

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
