### ISSUE TITLE
[FEATURE] 增加http2选项开关,并调整keepalive_requests

### ISSUE THREAD

**Issue by a1768623020** [1Panel-dev/1Panel#1483]
### 1Panel 版本

v1.3.6

### 请描述您的需求或者改进建议

目前大多数网站已经使用http2协议用来加载网站,但是在网站的配置里面没有找到H2的开关,建议增加一个,目前想要开启http2协议需要手动在配置文件中添加

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/32887476/862850c1-4c31-409a-bb06-b5b14118d4cf)

**Comment by zhengkunwang223** [comment]
感谢建议，下个版本默认增加http2

**Comment by a1768623020** [comment]
增加http2选项请注意keepalive_requests 1000;这个默认选项,在http1.1上这个值正好够用,开启http2后1000个连接数不够需要将这个值调整成100000,否则会导致反向代理网站出现非常严重的性能下降

**Comment by zhengkunwang223** [comment]
> 增加http2选项请注意keepalive_requests 1000;这个默认选项,在http1.1上这个值正好够用,开启http2后1000个连接数不够需要将这个值调整成100000,否则会导致反向代理网站出现非常严重的性能下降
> 
> 

感谢建议🙏

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
