### ISSUE TITLE
[FEATURE]控制台应用商店 api/v1/apps/search 接口返回的列表数据都快有1M 详情也没有用列表数据 希望可以优化

### ISSUE THREAD

**Issue by nowindexman** [1Panel-dev/1Panel#1485]
### 1Panel 版本

v1.3.6

### 请描述您的需求或者改进建议

接口返回的列表数据都快有1M 详情也没有用列表数据 希望可以优化

### 请描述你建议的实现方案

接口返回的列表数据都快有1M 详情也没有用列表数据 希望可以优化

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/20987893/ac680838-cf56-4c45-9739-c64f95296be9)

**Comment by zhengkunwang223** [comment]
接口返回中包含 icon 的 base64 数据,每个 icon 在 20 KB 左右，所以数据会稍微大一些

**Comment by mx2913** [comment]
icon 可以放到 oss 中或者面版的资源服务器方式加载

**Comment by nowindexman** [comment]
> 接口返回中包含 icon 的 base64 数据,每个 icon 在 20 KB 左右，所以数据会稍微大一些

接口中不建议返回资源类型的东西 可以把 icon 放在项目中当静态文件让他懒加载 现在是主页面一个 1M 的 api 在那阻塞着 这个太恐怖了。。。

**Comment by zhengkunwang223** [comment]
> > 接口返回中包含 icon 的 base64 数据,每个 icon 在 20 KB 左右，所以数据会稍微大一些
> 
> 接口中不建议返回资源类型的东西 可以把 icon 放在项目中当静态文件让他懒加载 现在是主页面一个 1M 的 api 在那阻塞着 这个太恐怖了。。。

我们是前后端不分离的项目 静态文件需要嵌入二进制中 如果放在静态文件 会导致 1Panel 自身的内存占用增加 现在1Panel占用大就是因为静态资源需要读到内存中

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
