### ISSUE TITLE
[FEATURE]优化文件系统排序方式

### ISSUE THREAD

**Issue by Dec-QXY** [1Panel-dev/1Panel#1487]
### 1Panel 版本 优化文件系统排序方式

v1.3.6 优化文件系统排序方式

### 请描述您的需求或者改进建议

希望优化一下文件系统中的排序问题，可以根据修改时间、文件名等选择文件列表排序方式
<img width="1705" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/52747536/c65bc6a1-4aa6-4ac7-86d2-25bd58f431be">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中优化文件管理列表页的排序方式。

**Comment by wanghe-fit2cloud** [comment]
文件列表排序会在v1.8.0 版本支持
和现有 Issue 重复 #1032
