### ISSUE TITLE
能不能兼容mac 😋 ，有计划吗? [FEATURE]

### ISSUE THREAD

**Issue by cczw2010** [1Panel-dev/1Panel#1493]
### 1Panel 版本

1.x

### 请描述您的需求或者改进建议

非常喜欢这个界面，我的本地开发环境也想用这个来处理我所有的网站环境。 [mac m2]

**Comment by wanghe-fit2cloud** [comment]
我们在中短期内不会支持上述需求，望理解。

**Comment by Osub** [comment]
我也想在mac上用于本地环境，暂时装个虚拟机
