### ISSUE TITLE
[QUESTION] 反向代理了两个站点，证书出现错乱。

### ISSUE THREAD

**Issue by WANG-Guangxin** [1Panel-dev/1Panel#1494]
### 请描述您的问题

1panel 版本 1.3.6  
最新版 OpenResty 
首先 反向代理了两个 网站 ，域名分别是  a.xxx.eu.org  和  b.xxx.eu.org

首先部署 a.xxx.eu.org ，并申请了证书，此时访问该网站没有问题，
然后部署 b.xxx.eu.org ，也申请了证书，此时访问 b 没有问题， 访问 a 时，浏览器显示的是 b 的证书，如果继续访问的话，会跳到 b. 

检查了两个网站OpenResty的配置文件，里面的证书路径是对的，这种问题该怎么解决。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地开发测试环境复现一下上述问题。

**Comment by cyril-cheng** [comment]
你直接申请*.xxx.eu.org证书，不香吗？

**Comment by WANG-Guangxin** [comment]
我没找到稳定复现的方法，我把 b 的证书和网站都删除，然后重新申请，又没有问题了

**Comment by WANG-Guangxin** [comment]
> 感谢反馈，我们先在本地开发测试环境复现一下上述问题。

好像和部署的先后顺序没有关系，和证书也没有关系。
反向代理多个网站，其中一个 监听 ipv6 ,  其它不监听 。 
https 访问 其他不监听ipv6的网站 会跳转到这个 监听 ipv6 的网站。
（域名同时作了 A 记录 和 AAAA 记录解析到这个服务器。）
