### ISSUE TITLE
[BUG]openresty 重装失败

### ISSUE THREAD

**Issue by justincnn** [1Panel-dev/1Panel#1496]
### 1Panel 版本

1.3.6

### 问题描述

openresty 

![](https://i.imgur.com/PI8xfzD.png)

 Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/etc/localtime" to rootfs at "/etc/localtime": mount /etc/localtime:/etc/localtime (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

### 重现步骤

在容器的菜单中删除openresty，
然后在应用商店再次安装，就会出现错误，
有的时候可以创建容器，但是无法启动

### 相关日志输出

```shell
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/etc/localtime" to rootfs at "/etc/localtime": mount /etc/localtime:/etc/localtime (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

**Comment by wanghe-fit2cloud** [comment]
1、麻烦提供一下服务器操作系统及架构信息。
2、删除应用后重建，这时点开高级设置 - 编辑 compose 文件，将同步时区的代码注释后点击确认按钮。
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/03fba04b-f20e-4a41-8148-849542508b64">

**Comment by justincnn** [comment]
> 1、麻烦提供一下服务器操作系统及架构信息。
> 2、删除应用后重建，这时点开高级设置 - 编辑 compose 文件，将同步时区的代码注释后点击确认按钮。
> <img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/03fba04b-f20e-4a41-8148-849542508b64">
> 

架构：arm
操作系统：ubuntu 22.04

**Comment by wanghe-fit2cloud** [comment]
第二点有执行吗，是否可以？

**Comment by justincnn** [comment]
> 第二点有执行吗，是否可以？

- 可以了，请问这是什么原因？

![](https://i.imgur.com/AkBU8my.png)

**Comment by wanghe-fit2cloud** [comment]
没有 localtime 文件。

**Comment by motoabc** [comment]
1Panel 版本
v1.5.5

问题描述
openresty
类似问题，全新安装 ，ARM环境 ubuntu 22.04


```
stderr: Container 1Panel-openresty-9nV3 Creating Container 1Panel-openresty-9nV3 Created Container 1Panel-openresty-9nV3 Starting Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/opt/1panel/apps/openresty/openresty/conf/nginx.conf" to rootfs at "/usr/local/openresty/nginx/conf/nginx.conf": mount /opt/1panel/apps/openresty/openresty/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

<img width="586" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/18234691/8398c8ee-b6f8-4f31-91d2-f7cf67dd0a8c">

创建的配置文件都是文件夹啊
