### ISSUE TITLE
[BUG] 防火墙规则不支持IPv6地址

### ISSUE THREAD

**Issue by benzBrake** [1Panel-dev/1Panel#1501]
### 1Panel 版本

1.3.6

### 问题描述

添加防火墙规则，IP地址为 IPv6 时提示 IP地址不合法

### 重现步骤

创建新防火前规则
IP地址填入IPv6地址

### 附加信息

![ipv6](https://github.com/1Panel-dev/1Panel/assets/11323774/c923d01a-918a-4766-abec-e59329ac76d0)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们将在后续版本中持续优化。

**Comment by wanghe-fit2cloud** [comment]
最新版本已支持。
