### ISSUE TITLE
[FEATURE] 监控数据单位建议根据数据量级别做单位转换

### ISSUE THREAD

**Issue by icpd** [1Panel-dev/1Panel#1502]
### 1Panel 版本

v1.3.6

### 请描述您的需求或者改进建议

<img width="612" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/35096485/e8cd2b81-973f-45b8-a88a-654c1b9bf34e">

数据看起来不太友好

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。
