### ISSUE TITLE
[FEATURE] 计划任务增加系统快照功能

### ISSUE THREAD

**Issue by zhiqing0205** [1Panel-dev/1Panel#1503]
### 1Panel 版本

1.3.6

### 请描述您的需求或者改进建议

计划任务增加系统快照功能，要不然每次还得手动备份

### 请描述你建议的实现方案

在计划任务内增加系统快照功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，该需求我们会在后续版本中考虑支持。

**Comment by hllshiro** [comment]
同样需求，事实上开发量很小，希望能尽快集成！

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
