### ISSUE TITLE
[FEATURE] 前端弹出侧边抽屉时可以点击遮罩层关闭

### ISSUE THREAD

**Issue by zhiqing0205** [1Panel-dev/1Panel#1504]
### 1Panel 版本

1.3.6

### 请描述您的需求或者改进建议

侧边抽屉支持点击遮罩层关闭，否则还得点击那个小的返回按钮才能关闭

### 请描述你建议的实现方案

具体到组件部分就是把drawer的wrapperClosable属性设置为true

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
主要是为了防止用户输入部分参数后误点击遮罩层导致表单数据重填，因此禁用了上述反馈的功能。
