### ISSUE TITLE
希望可以增加一键迁移[FEATURE]

### ISSUE THREAD

**Issue by yikwongee** [1Panel-dev/1Panel#1505]
### 1Panel 版本

1.3.6

### 请描述您的需求或者改进建议

把整个1panel及所有数据 迁移到一个新的服务器中，这样换服务器什么的 会方面很多

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

1Panel 已经支持创建快照到第三方账号。如果存在迁移面板的需求，可以使用同步快照功能。

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/5cebd4f1-083a-4497-be13-907a90f3d3c8)
