### ISSUE TITLE
[FEATURE] Add Russian language

### ISSUE THREAD

**Issue by seoeaa** [1Panel-dev/1Panel#1506]
### 1Panel 版本

Add Russian language

### 请描述您的需求或者改进建议

Add Russian language

### 附加信息

[ru.txt](https://github.com/1Panel-dev/1Panel/files/11927301/ru.txt)

**Comment by wanghe-fit2cloud** [comment]
Thank you for your feedback. We will consider supporting the mentioned requirements in future versions.

**Comment by wanghe-fit2cloud** [comment]
We currently have no plans to support the above-mentioned request.  We hope for your understanding.

**Comment by seoeaa** [comment]
maybe there is just an option to make translation functionality inside the panel
