### ISSUE TITLE
[QUESTION]普通用户执行安装脚本导致安装失败

### ISSUE THREAD

**Issue by dabao1955** [1Panel-dev/1Panel#1507]
### 请描述您的问题

OS: Debian GNU/Linux Bookworm amd64，支持docker。
步骤:
- 1.下载安装脚本。
- 2.使用带sudo权限的普通用户执行安装脚本。
- 3.提示docker启动失败。中间提示输入用户密码。
使用root用户执行安装脚本一切正常

**Comment by wanghe-fit2cloud** [comment]
普通用户需要使用sudo才能操作Docker。

**Comment by dabao1955** [comment]
> 普通用户需要使用sudo才能操作Docker。

既然这样，那么有没有考虑在安装脚本添加检测是否是超级用户执行，如果不是就以1的返回值退出脚本呢？
