### ISSUE TITLE
[QUESTION] OpenResty 反向代理的 Websocket 可能有 bug 

### ISSUE THREAD

**Issue by WANG-Guangxin** [1Panel-dev/1Panel#1508]
### 请描述您的问题

1. 首先是反代 code-server ，在宝塔面板下，使用如下nginx配置可以正确反代 code-server。
```
     location / {
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Accept-Encoding gzip;
    proxy_pass http://127.0.0.1:8080;
    }
```
但是在 1.3.6 1Panel 中的 OpenResty 反代code-server 提示

![Screenshot-4](https://github.com/1Panel-dev/1Panel/assets/71872849/4cbf9751-0be6-4e58-a42d-724099b821e6)

2.  使用如下配置（默认的）反代了 minio ，可以正常访问网页，网页上传了个图片也能成功，但是查看桶里的内容时 报错。 

```
location ^~ / {
    proxy_pass http://127.0.0.1:9000; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_http_version 1.1; 
    add_header X-Cache $upstream_cache_status; 
}
```

![image](https://github.com/1Panel-dev/1Panel/assets/71872849/4609c658-d01c-4bd0-a6e9-f6ce8504bc7d)

**Comment by zhengkunwang223** [comment]
您好 我测试反代了 minio 并且开启了 https 没有复现你的问题

**Comment by WANG-Guangxin** [comment]
我好像知道复现方式了。 
反代 minio 开启 https  后，不用 443 端口试试，我的环境下 用的 86 端口。

**Comment by cyril-cheng** [comment]
proxy_set_header Host $host; 改成proxy_set_header Host $http_host;

**Comment by cyril-cheng** [comment]
另外要使用桶，你还需要反代9001端口

**Comment by WANG-Guangxin** [comment]
感谢大佬

**Comment by ghuserbit** [comment]
> proxy_set_header Host $host; 改成proxy_set_header Host $http_host;

这个有效，感谢，搞半天了

**Comment by dnslin** [comment]
> proxy_set_header Host $host; 改成proxy_set_header Host $http_host;

感谢大佬 这个也对我有效

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> proxy_set_header Host $host; Change to proxy_set_header Host $http_host;

Thanks for this, too, for it works for me
