### ISSUE TITLE
[BUG] 应用市场安装MongoDB6.0.6，服务器内存打满，运行堵塞显示360%

### ISSUE THREAD

**Issue by hejojoiu** [1Panel-dev/1Panel#1514]
### 联系方式

13213143620@163.com

### 1Panel 版本

v1.3.6

##### 服务器环境
linux:
发行版本 centos-7.9.2009
内核版本 3.10.0-1160.71.1.el7.x86_64
系统类型 x86_64
##### 问题
应用市场安装MongoDB6.0.6完成之后，web页面显示容器正常，但是navicat无法点击查看数据库详情，然后服务器卡顿，内存占用100%，运行堵塞360%

##### 问题步骤
- 应用市场安装MongoDB6.0.6完成之后，web页面显示容器正常
- navicat testconnect正常，但是navicat无法点击查看数据库详情
- 在服务器通过docker命令查看MongoDB时，服务器直接卡住
- 1Panel web页面也开始卡顿
- 过了十几秒页面正常，概览页面显示服务器异常，内存占用100%，运行堵塞360%
- 通过web 删除容器及其镜像，服务器恢复正常
- 异常
![error](https://github.com/1Panel-dev/1Panel/assets/46958050/c1493b9c-33dc-49e0-a3be-09803e5def2e)
- 正常
![normal](https://github.com/1Panel-dev/1Panel/assets/46958050/090223d6-9a61-48bb-855e-7e9d7f0f339e)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在本地服务器测试并没有复现上述问题，服务器和 MongoDB 状态都正常、可用。
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/62f386eb-4860-486b-bb3a-0e71c985374f)

你可以先 top 查看一下具体是哪些进程导致的服务器负载过高。
