### ISSUE TITLE
[FEATURE] 请求添加社区商店可视化配置

### ISSUE THREAD

**Issue by Jengro777** [1Panel-dev/1Panel#1521]
### 1Panel 版本

1.3.6

### 请描述您的需求或者改进建议

现在没有社区商店

1Panel 可以开放一个社区商店配置的功能，让大家可以自由配置社区商店来源，而且可以支持多个社区商店的配置

### 附加信息

有了社区商店，平台的互动性大大增加；对平台的推广和社区运营有很好的辅助作用

**Comment by wanghe-fit2cloud** [comment]
暂无计划支持应用商店的可视化配置。
