### ISSUE TITLE
[BUG]创建网站，使用中文域名无法生效，需要手动输入转义后的地址才能生效

### ISSUE THREAD

**Issue by mengxunlingxue** [1Panel-dev/1Panel#1522]
### 联系方式

1Panel 交流群1-梦寻凌雪

### 1Panel 版本

v1.3.6

### 问题描述

创建网站，使用中文域名无法生效，需要手动输入转义后的地址才能生效

### 重现步骤

创建网站，使用中文域名无法生效，需要手动输入转义后的地址才能生效

### 期待的正确结果

可以直接输入中文域名，无需手动转义

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。当用户输入包括后缀名都为中文的域名时，会复现上述问题。
在后续版本我们会针对该类域名做出优化。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
