### ISSUE TITLE
[BUG]上传大文件到100%提示超时

### ISSUE THREAD

**Issue by taurusduan** [1Panel-dev/1Panel#1523]
### 1Panel 版本

1.3.6

### 问题描述

反复上传三次大文件都是100%的时候提示超时

### 重现步骤

文件为数据库,暂时无法分享,大小在5.45GB的zip文件,解压后大概9GB左右.

**Comment by zhengkunwang223** [comment]
好的 我们复现一下

**Comment by donghuaxianahehe** [comment]
的确，大文件上传，1.6gb压缩包上传，传了一会儿显示100%点击完成，实际上只上传了三四百兆，多次都是如此。

**Comment by wanghe-fit2cloud** [comment]
我们在 v1.4.0 版本尝试优化了文件上传逻辑，可以升级到最新版本后查看是否还存在上述问题。
