### ISSUE TITLE
[FEATURE] 希望可以統一中英的字體

### ISSUE THREAD

**Issue by HansHans135** [1Panel-dev/1Panel#1524]
### 1Panel 版本

1.3.5

### 请描述您的需求或者改进建议

可以把字體改成 比較粗 且 `我個人覺得還不錯` 的 像是正黑體
因為這個老字體配上這個現代化設計的有點不搭

還是說因為我的面板和demo圖片不一樣是我安裝的問題?

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/94590267/7057fe43-cc38-497d-b5b0-d4e01df5bd84)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.4.3 版本已发布。
