### ISSUE TITLE
树莓派安装应用失败

### ISSUE THREAD

**Issue by WayneLee5991** [1Panel-dev/1Panel#1527]
### 请描述您的问题

树莓派4b
系统信息：
主机名称 raspberrypi
发行版本 raspbian-10.13
内核版本 5.10.103-v7l+
系统类型 armv7l
uname -a
Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

安装mysql失败，报错信息：no matching manifest for linux/arm/v7 in the manifest list entries
安装其他的也基本都是这种错误信息，这个怎么解决啊

**Comment by zhengkunwang223** [comment]
Mysql 是什么版本？ 5.x 版本没有 arm 镜像

**Comment by WayneLee5991** [comment]
> Mysql 是什么版本？ 5.x 版本没有 arm 镜像

我选的8.0.33的版本，安装openresty也是报这个错误

**Comment by zhengkunwang223** [comment]
> > Mysql 是什么版本？ 5.x 版本没有 arm 镜像
> 
> 我选的8.0.33的版本，安装openresty也是报这个错误

mysql 8.0.33 和 openresy 官方只有 arm64/v8 版本

**Comment by wanghe-fit2cloud** [comment]
armv7l 架构服务器，参考下面这篇文章：
https://bbs.fit2cloud.com/t/topic/670/2

**Comment by WayneLee5991** [comment]
> armv7l 架构服务器，参考下面这篇文章： https://bbs.fit2cloud.com/t/topic/670/2

按照这篇文章成功安装了mysql和openresty，但是按照这个方法安装redis失败了
我拉取了arm32v7/redis:6.2.12这个镜像

然后执行修改tag命令
docker tag arm32v7/redis:6.2.12 redis:6.2.12

然后再商店里安装redis，无法启动
报错信息： error containers:/redis

**Comment by wanghe-fit2cloud** [comment]
可以到容器菜单 - 容器列表，查看一下 redis 容器状态和日志。
