### ISSUE TITLE
[BUG]网络IO统计错误

### ISSUE THREAD

**Issue by huxiangquan** [1Panel-dev/1Panel#1534]
### 1Panel 版本

1.3.6

### 问题描述

网络IO统计错误
![image](https://github.com/1Panel-dev/1Panel/assets/52623921/f5cae768-abd2-4f75-9f9a-a40b84516fce)

### 重现步骤

安装k8s过程中出现

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们将会在近期版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
