### ISSUE TITLE
[FEATURE]网站安全防护，CC 保护功能细化等等

### ISSUE THREAD

**Issue by Raxiny** [1Panel-dev/1Panel#1536]
### 1Panel 版本

1.3.6

### 请描述您的需求或者改进建议

网站安全防护 CC保护功能细化 如封锁 IP 时间  封号 IP 列表  解封被封锁的 IP  累计攻击次数统计  封锁惩罚层叠加重 等等

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
CC 防护相关功能的讨论，统一汇总到该 issue #2353
