### ISSUE TITLE
[FEATURE] 希望在面板中的mysql创建数据库无长度限制

### ISSUE THREAD

**Issue by CokeSR** [1Panel-dev/1Panel#1539]
### 1Panel 版本

1.3.6

### 请描述您的需求或者改进建议

在1panel中使用mysql创建库时（我的数据库名为：3command-16dev-config），发现有长度限制，为什么不可以超过16位呢

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本完成上述优化。

**Comment by deep-project** [comment]
我记得宝塔也有这个问题，好像是为了兼容老板的mysql，好像老版本mysql对名字长度有限制

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
