### ISSUE TITLE
[QUESTION]  在安装WordPress的时候，会跳回登录页面，并且报该用户没有权限

### ISSUE THREAD

**Issue by xiaopengzzc** [1Panel-dev/1Panel#1545]
### 请描述您的问题

在安装WordPress的时候，会跳回登录页面，并且报该用户没有权限
![Snipaste_2023-07-05_15-12-58](https://github.com/1Panel-dev/1Panel/assets/136769452/9d9896f5-bfaa-4427-bd19-f650411115a7)

**Comment by zhengkunwang223** [comment]
是 wordpress 应用吗

**Comment by xiaopengzzc** [comment]
就是1panel应用商店里面的

**Comment by zhengkunwang223** [comment]
1Panel 有反向代理过吗
安装的时候填过什么参数
是点安装就报错 还是 安装后报错

**Comment by xiaopengzzc** [comment]
好了，反向代理的问题
