### ISSUE TITLE
[FEATURE] 支持通过玲珑安装 1Panel

### ISSUE THREAD

**Issue by maninhill** [1Panel-dev/1Panel#1547]
### 1Panel 版本

v1.3.6

### 请描述您的需求或者改进建议

如题。

https://baijiahao.baidu.com/s?id=1769293471877135390&wfr=spider&for=pc

**Comment by maninhill** [comment]
https://doc.chinauos.com/content/L7nFinQB_uwzIp6HNV7S

**Comment by maninhill** [comment]
请问这个问题有进展吗？

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is there any progress on this issue?

**Comment by wanghe-fit2cloud** [comment]
中短期内暂无计划支持，先关闭该 issue 了，望理解。
