### ISSUE TITLE
[BUG]终端连接，显示红色的disconnected

### ISSUE THREAD

**Issue by Jiraiya8** [1Panel-dev/1Panel#1552]
### 联系方式

yourpipi@proton.me

### 1Panel 版本

1.3.6

### 问题描述

终端连接，显示红色的disconnected，保存是，点击测试连接是ok的。

我加端口访问是可以正常访问终端的，比如端口是12315，但是使用nginx反代从443端口进入的时候，就出问题了，也会展示，disconnected。问题还是websocket连接失败，因为端口是wss的连接端口是443，而不是我真实的端口12315

### 重现步骤

使用nginx反代从443端口进入，链接终端

### 期待的正确结果

正常连接，不显示disconnected

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下问题。

**Comment by ssongliu** [comment]
可以看一下 nginx 配置里面有没有包含 websocket 的配置：
location / {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}

**Comment by wanghe-fit2cloud** [comment]
> 可以看一下 nginx 配置里面有没有包含 websocket 的配置： location / { proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; }

也可以在 1Panel 系统中新建反向代理网站（反代 1Panel 自身服务），也可以实现上述功能。

**Comment by Jiraiya8** [comment]
感谢回复，添加下面这一段已经解决了我的问题，感谢。
location / {
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
}
