### ISSUE TITLE
[QUESTION] 1Panel 开机自启

### ISSUE THREAD

**Issue by lxtqq** [1Panel-dev/1Panel#1553]
### 请描述您的问题

ipanel好像本身就是开机自启的，
服务状态
```
● 1panel.service - 1Panel, a modern open source linux panel
   Loaded: loaded (/etc/systemd/system/1panel.service; enabled; vendor preset: disabled)
   Active: active (running) since 三 2023-07-05 20:39:58 CST; 1min 51s ago
 Main PID: 1265 (1panel)
    Tasks: 7
   Memory: 106.1M
   CGroup: /system.slice/1panel.service
           └─1265 /usr/bin/1panel
```
但是每次重启服务器后需要重启一下才行。请问，我还缺少哪个命令让他开机自启吗？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦提供一下服务器操作系统具体版本，我们在本地复现一下。

**Comment by lxtqq** [comment]
> 感谢反馈，麻烦提供一下服务器操作系统具体版本，我们在本地复现一下。
好的，谢谢
![image](https://github.com/1Panel-dev/1Panel/assets/94205527/0e865885-384c-4ecc-94d9-8f52b9f1ac67)

 Linux localhost.localdomain 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by wanghe-fit2cloud** [comment]
可以使用下面的命令看一下 1Panel 服务开机自启动有没有生效：
```shell
systemctl is-enabled 1panel.service
```

**Comment by lxtqq** [comment]
> ```shell
> systemctl is-enabled 1panel.service
> ```

![image](https://github.com/1Panel-dev/1Panel/assets/94205527/2cfbb31a-c125-48bb-be89-00893574af09)
已启用

**Comment by wanghe-fit2cloud** [comment]
确认一下是否有截图中 service 文件：
<img width="961" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/4d4d89e6-7821-4bce-8c51-583c98f5e39f">

**Comment by lxtqq** [comment]
> 确认一下是否有截图中 service 文件： <img alt="image" width="961" src="https://user-images.githubusercontent.com/46734380/251187641-4d4d89e6-7821-4bce-8c51-583c98f5e39f.png">
有

![image](https://github.com/1Panel-dev/1Panel/assets/94205527/cb7c6c29-850a-45fc-82ac-5f119d161851)

**Comment by wanghe-fit2cloud** [comment]
> > 确认一下是否有截图中 service 文件： <img alt="image" width="961" src="https://user-images.githubusercontent.com/46734380/251187641-4d4d89e6-7821-4bce-8c51-583c98f5e39f.png">
> > 有
> 
> ![image](https://user-images.githubusercontent.com/94205527/251188287-cb7c6c29-850a-45fc-82ac-5f119d161851.png)

你查看的目录错了。

**Comment by lxtqq** [comment]
> > > 确认一下是否有截图中 service 文件： <img alt="image" width="961" src="https://user-images.githubusercontent.com/46734380/251187641-4d4d89e6-7821-4bce-8c51-583c98f5e39f.png">
> > > 有
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/94205527/251188287-cb7c6c29-850a-45fc-82ac-5f119d161851.png)
> 
> 你查看的目录错了。
有

![image](https://github.com/1Panel-dev/1Panel/assets/94205527/127b1f23-051e-4670-af7b-7e3b27300f20)

**Comment by wanghe-fit2cloud** [comment]
到目前为止，看不出来具体是啥问题。

通过命令查看已经是 enabled，而且该有的配置文件也在。

**Comment by wanghe-fit2cloud** [comment]
可以进微信群，继续讨论一下这个问题。

**Comment by lxtqq** [comment]
> 到目前为止，看不出来具体是啥问题。
> 
> 通过命令查看已经是 enabled，而且该有的配置文件也在。

谢谢了，这么晚了，还帮我看问题，我已经重装过一次。
