### ISSUE TITLE
[FEATURE] logs export

### ISSUE THREAD

**Issue by passwa11** [1Panel-dev/1Panel#1554]
### 1Panel 版本

v1.3.6

### 请描述您的需求或者改进建议

At times, it may be necessary to download logs to the local system for auditing or other operations.
# important: SSH login log

# The following is not as significant.
- Website Log
- Panel logs
- Operation logs
- Login logs

**Comment by wanghe-fit2cloud** [comment]
ssh 日志来源于服务器日志文件：
- Debian / Ubuntu：
<img width="614" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/24b74e51-7bad-46d1-9fdc-90106a98cd24">

- RedHat / CentOS：
<img width="621" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/212da987-26aa-4dab-969b-e8edf109b241">

**Comment by passwa11** [comment]
Website Log ?

**Comment by wanghe-fit2cloud** [comment]
> Website Log ?

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/1bce6b78-e290-488d-b6b8-95eb7e5f594a)
