### ISSUE TITLE
[BUG]容器内存使用率显示或统计错误

### ISSUE THREAD

**Issue by JueLuo99** [1Panel-dev/1Panel#1556]
### 1Panel 版本

v1.3.6

### 问题描述

「容器」页面中，某个容器的内存使用率显示或统计错误

如图所示，在我 32 GiB 的设备上显示占用 91.86%，实际系统总内存使用小于 2 GiB
![image](https://github.com/1Panel-dev/1Panel/assets/25797524/a64ed5aa-9014-4b1b-9658-a10ef35303ec)

- 面板的「概览」页显示当前系统内存使用正常
- 「监控」页面也显示从未有过如此高内存占用
- 该容器的 CPU 占用统计正确，会随时间变化

### 重现步骤

始终存在

### 期待的正确结果

正确显示资源占用

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，1Panel 使用的是 Docker 官方的 SDK 获取到的数据。

可以先在终端手动执行 docker stats 命令，查看输出结果是否和页面一致。

**Comment by JueLuo99** [comment]
> 感谢反馈，1Panel 使用的是 Docker 官方的 SDK 获取到的数据。
> 
> 可以先在终端手动执行 docker stats 命令，查看输出结果是否和页面一致。

并不一致

```
CONTAINER ID   NAME                    CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O        PIDS
927529d1de03   qbittorrent             0.20%     1.104GiB / 31.13GiB   3.55%     158GB / 255.5GB   10.2MB / 151GB   15
f26f6205ea4a   1Panel-openresty-Zc0z   0.00%     4.684MiB / 31.13GiB   0.01%     0B / 0B         0B / 4.1kB       5
```

此时面板内仍然显示占用为 91.86%

**Comment by wanghe-fit2cloud** [comment]
刚在本地环境安装应用后，并没有复现你反馈的问题：
<img width="1290" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/e71b653c-3b7a-4572-b017-d8018d629b62">

如果还有问题的话，可以进微信群添加我好友，远程看一下。

**Comment by JueLuo99** [comment]
在通过面板创建新 docker compose 后，该故障消失，且无法再次复现

若开发者仍有继续研究意向，欢迎继续联系
