### ISSUE TITLE
[FEATURE]硬件温度监控

### ISSUE THREAD

**Issue by backy-1451592168** [1Panel-dev/1Panel#1567]
### 1Panel 版本

1.3.6

### 请描述您的需求或者改进建议

可以加多一个硬件温度监控吗？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
服务器硬件（如 CPU、主板温度等）需求的讨论，统一汇总到该 issue #1614
