### ISSUE TITLE
[QUESTION] 你们这个 star 的增长曲线科学吗 ？！！！

### ISSUE THREAD

**Issue by cxntsh** [1Panel-dev/1Panel#1568]
### 请描述您的问题

你们这个 star 的增长曲线是怎么做到的？我身边都几乎没什么人知道你们这个项目，难道又是玩充值 ？！！

**Comment by maninhill** [comment]
你不知道不代表别人不知道，世界比你想象的大。

**Comment by maninhill** [comment]
欢迎深入监督和检查。

**Comment by chixq** [comment]
这就是科学。The rules always change。

**Comment by zhengkunwang223** [comment]
用心好好做 star 自然多
