### ISSUE TITLE
[BUG]直接编辑应用的参数配置compose,空格按快了会批量复制代码

### ISSUE THREAD

**Issue by cyril-cheng** [1Panel-dev/1Panel#1569]
### 联系方式

在群内

### 1Panel 版本

1.3.6

### 问题描述

在应用的参数配置里编辑compose文件   空格按快了   会无限复制compose代码
这是原始代码
![a0a6f69f8931f40d26670cdaea26e39](https://github.com/1Panel-dev/1Panel/assets/49748357/640b40fa-fc95-4ac8-afbb-1c21f705ccf0)
这是按几下空格之后的代码

![09c76c692abfd053e763079ac596428](https://github.com/1Panel-dev/1Panel/assets/49748357/7b3fd3f2-4a8c-445b-80c6-b3455c10802f)

### 重现步骤

安装应用-->高级设置-->编辑compose文件，快速点按空格键

### 期待的正确结果

正确空格

**Comment by zhengkunwang223** [comment]
本地没有复现，是必现的吗？

**Comment by cyril-cheng** [comment]
必现

**Comment by cyril-cheng** [comment]
我录了个视频，你看看


https://github.com/1Panel-dev/1Panel/assets/49748357/cea53753-bfb2-482b-86fe-ce53c4e260c0

**Comment by zhengkunwang223** [comment]
> 我录了个视频，你看看
> 
>  1Panel.-.Google.Chrome.2023-07-06.22-38-31.mp4

我试了好几个环境 都没有这种情况 我群里联系你

**Comment by zhengkunwang223** [comment]
已解决 chrome 翻译插件导致
