### ISSUE TITLE
[FEATURE]希望文件上传，粘贴的时候可以更改文件名

### ISSUE THREAD

**Issue by XCWQW1** [1Panel-dev/1Panel#1570]
### 1Panel 版本

v1.3.6

### 请描述您的需求或者改进建议

希望文件上传，粘贴的时候可以更改文件名，如果粘贴的时候当前目录有同名则询问是否覆盖或者改名粘贴

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by zyyfit** [comment]
粘贴已支持有重名文件时重命名，上传暂不支持

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
