### ISSUE TITLE
[FEATURE]可否考虑出一个Windows server版本的分支

### ISSUE THREAD

**Issue by sakuno214** [1Panel-dev/1Panel#1574]
### 1Panel 版本

None

### 请描述您的需求或者改进建议

没什么需求，就是单位的机房服务器居然是那种古早纯命令行核心的win serv，平时维护对我来说学习成本太高了，所以后期有没有可能出一个win分支？

**Comment by maninhill** [comment]
感谢你的建议。短期我们没有做 Windows 版本的计划，先聚焦把 Linux 做好。

**Comment by sakuno214** [comment]
> 感谢你的建议。短期我们没有做 Windows 版本的计划，先聚焦把 Linux 做好。

谢谢回复，希望以后能见到win版本的到来
