### ISSUE TITLE
[FEATURE]希望增加支持使用代理安装应用等

### ISSUE THREAD

**Issue by yuanjinwan** [1Panel-dev/1Panel#1578]
### 1Panel 版本

1.3.6

### 请描述您的需求或者改进建议

希望增加支持使用代理安装应用等
有些Linux无法连接到外网，需要使用代理的方式上网，建议增加该设置

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑是否支持上述需求。

**Comment by JinPengGeng** [comment]
这个真的很需要，内网环境下无法升级！！！

**Comment by wanghe-fit2cloud** [comment]
1Panel 官方暂不考虑支持用户设置代理等相关功能。
可以考虑在应用商店中安装第三方本地应用 [v2rayA](https://github.com/okxlin/appstore/tree/localApps/apps/v2raya)
