### ISSUE TITLE
[FEATURE]建议可自定义添加数据库、Redis、网站连接，以便对自定义部署的数据库、Redis、网站进行监控

### ISSUE THREAD

**Issue by yuanjinwan** [1Panel-dev/1Panel#1579]
### 1Panel 版本

1.3.6

### 请描述您的需求或者改进建议

建议可自定义添加数据库、Redis、网站连接，以便对自定义部署的数据库、Redis、网站进行监控

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本会考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已支持添加 MySQL 远程数据库。

**Comment by wanghe-fit2cloud** [comment]
支持外部 Redis 数据库的需求，统一汇总到该 issue #3522
