### ISSUE TITLE
[BUG]检测不到之前就安装了的 mysql 和 redis

### ISSUE THREAD

**Issue by leezhm** [1Panel-dev/1Panel#1583]
### 联系方式

libiver@126.com

### 1Panel 版本

v1.3.6

### 问题描述

系统之前就安装了mysql8和redis，今天安装了1panel，进入面板，检测不到数据库和redis，需要我从新安装。确认数据库和redis正常运行。

### 重现步骤

系统之前就安装了mysql8和redis，今天安装了1panel，进入面板，检测不到数据库和redis，需要我从新安装。确认数据库和redis正常运行。

**Comment by okxlin** [comment]
是容器还存在，但应用管理界面对应的有异常？

点应用的参数，再点高级设置，最后确定，会重建应用。

**Comment by wanghe-fit2cloud** [comment]
> 系统之前就安装了mysql8和redis，今天安装了1panel，进入面板，检测不到数据库和redis，需要我从新安装。确认数据库和redis正常运行。

1Panel 只能识别应用商店安装的数据库应用。
