### ISSUE TITLE
[FEATURE] 支持 docker-compose-plugin

### ISSUE THREAD

**Issue by ty114514** [1Panel-dev/1Panel#1585]
### 1Panel 版本

-

### 请描述您的需求或者改进建议

https://docs.docker.com/compose/install/

Docker 24 已经默认集成 docker-compose-plugin，并且独立的 compose 也被标记为不推荐了
具体区别就是命令从 docker-compose 变成了 docker compose

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，1Panel 的应用商店、容器管理等目前还没有升级为 docker compose，主要是为了兼容用户手动安装的版本较低的 docker 环境。
后续版本我们会考虑上述建议的。

**Comment by JokerQyou** [comment]
安装 1Panel 时提示 docker-compose v1 版本过低，需要 v2，然后我手动安装了 v2，删除了 v1，然后应用商店安装任何应用都失败，因为没有了 `docker-compose` 命令。这是否有点割裂 😓
