### ISSUE TITLE
需要网站流量监控 以及需要PHP随时切换

### ISSUE THREAD

**Issue by lanyani** [1Panel-dev/1Panel#1586]
### 1Panel 版本

1.3.6

### 请描述您的需求或者改进建议

1.类似宝塔的网站监控报表
可以实时监控网站的PV,UV，IP,流量请求等
2.需要可以随时切换PHP的功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述两点需求我们会在后续版本中考虑支持。

**Comment by lanyani** [comment]
> 感谢反馈，上述两点需求我们会在后续版本中考虑支持。

随时切换PHP的功能  这个是必须要支持的吧？

**Comment by zhengkunwang223** [comment]
> > 感谢反馈，上述两点需求我们会在后续版本中考虑支持。
> 
> 
> 
> 随时切换PHP的功能  这个是必须要支持的吧？

切换 PHP 功能已经纳入开发计划 具体哪个版本请关注我们的 milestones https://github.com/1Panel-dev/1Panel/milestones

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
