### ISSUE TITLE
[BUG]搭建好网站打开显示Access denied. 搭建好几个不同的都显示这个

### ISSUE THREAD

**Issue by lanyani** [1Panel-dev/1Panel#1587]
### 联系方式

i335648@outlook.com

### 1Panel 版本

1.3.6

### 问题描述

搭建好网站打开显示Access denied. 搭建好几个不同的都显示这个

### 重现步骤

搭建网站就出现

**Comment by lanyani** [comment]
在环境内重启php也没用

**Comment by lanyani** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/54623653/9af138f2-e18d-4f4f-8900-21c7cd7361e4)

**Comment by zhengkunwang223** [comment]
1.网站设置 网站目录 权限那里点一下保存
2.如果是从其他面板拷贝的php代码，请检查user.ini等文件有没有权限配置

**Comment by lanyani** [comment]
> 

都没用，我看日志发现，所有网站全部get跳转面板地址！根本没有跳转我自己设置的端口

**Comment by lanyani** [comment]
> 1.网站设置 网站目录 权限那里点一下保存 2.如果是从其他面板拷贝的php代码，请检查user.ini等文件有没有权限配置

自建网页，除了静态网页，其余全部显示这个

**Comment by lanyani** [comment]
> 1.网站设置 网站目录 权限那里点一下保存 2.如果是从其他面板拷贝的php代码，请检查user.ini等文件有没有权限配置

确实，我是从宝塔迁移过来的网站都显示这个，安装新的正常，以上你说的方法都试了，没有用！

**Comment by zhengkunwang223** [comment]
> > 1.网站设置 网站目录 权限那里点一下保存 2.如果是从其他面板拷贝的php代码，请检查user.ini等文件有没有权限配置
> 
> 确实，我是从宝塔迁移过来的网站都显示这个，安装新的正常，以上你说的方法都试了，没有用！

正常情况下把 .user.ini 删除之后就可以运行，如果还是无法运行，可以在微信群里联系我，“程会玩”

**Comment by xcdmrCHP** [comment]
我也遇到了相同的问题：
权限都设置了，容器也重启了，没有.user.ini

**Comment by torans** [comment]
> 我也遇到了相同的问题： 权限都设置了，容器也重启了，没有.user.ini

一样问题，你解决了吗
