### ISSUE TITLE
[BUG]安装应用比如mysql redis等，用pycharm软件的连接docker就连接不上去了。

### ISSUE THREAD

**Issue by oneszsm** [1Panel-dev/1Panel#1588]
### 1Panel 版本

1.36

### 问题描述

为什么只要一安装应用比如mysql redis等。用pycharm软件的连接docker就连接不上去了。只能把安装的应用关了。如果从docker镜像用代码安装就没问题，但面板就管理不到了。很难受。

### 重现步骤

没安装应用前可以用pycharm或者webstrom连接docker，通用ssh，一但安装了应用就无法连接一直转圈，ssh是能正常连接的。

**Comment by wanghe-fit2cloud** [comment]
以下几点不是很理解：

- `用 pycharm 软件的连接 docker 就连接不上去了`？
> 1Panel 安装应用，只是通过 docker-compose 来启动相应的服务，不会针对 docker 做出任何修改。

- `如果从 docker 镜像用代码安装就没问题`？
>是在说用 docker run 命令手动安装吗？

**Comment by wanghe-fit2cloud** [comment]
如果是要外部访问 1Panel 应用商店的已安装服务，需要在安装时打开端口外部访问。
具体操作，参考这篇 [论坛文章](https://bbs.fit2cloud.com/t/topic/858/2)
