### ISSUE TITLE
[FEATURE]只是一个建议或者想法啊，就是对最小内存的支持能否再小点，让更多的arm主机能支持？确实好看啊

### ISSUE THREAD

**Issue by YellCatt** [1Panel-dev/1Panel#1589]
### 1Panel 版本

1.3.6

### 请描述您的需求或者改进建议

需求：只是一个建议或者想法啊，就是对最小内存的支持能否再小点，让更多的arm主机能支持？确实好看啊
场景：多数arm主机内存都在1G以下，是否能再小点，界面真的好看啊

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈。
- 当前版本，1Panel 主程序占用服务器两百多兆内存，这一点我们还会持续优化。
- 1Panel 是基于容器来部署、管理应用，对宿主机影响小，安全性高。当然，在性能上势必会有所牺牲，对于 1C1G 这类的小机器压力会比较大。
