### ISSUE TITLE
[FEATURE] 一键更新容器镜像

### ISSUE THREAD

**Issue by conanliuhuan** [1Panel-dev/1Panel#1593]
### 1Panel 版本

1.3.6

### 请描述您的需求或者改进建议

从dockerhub拉取下来的latest镜像启动后，若dockerhub有更新，在1Panel中现有的更新流程基本是：先删除container、再删除image、再重新配置之前的端口文件夹映射，步骤较为繁琐。
建议做一个一键更新image的功能，自动处理上述所有步骤

### 请描述你建议的实现方案

在“容器/镜像”页面的镜像列表中，提供“检查更新”按钮，若检查到该tag的镜像在dockerhub上和本地的 Digest 值不同，则允许用户“一键更新”。

更新时自动从dockerhub中拉取镜像，并将现有的container删除后根据原先的配置重新启动

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述需求已经开发完成，会在 v1.4.0 版本发布。

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
