### ISSUE TITLE
[BUG]来回切换页面 内存会大幅增加，一段时间后也不释放

### ISSUE THREAD

**Issue by wzrove** [1Panel-dev/1Panel#1598]
### 联系方式

wzrove@outlook.com

### 1Panel 版本

v1.3.6-alpha.2

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/88016243/a1bf3d7d-9138-4c01-998e-264a0fef9c8e)

来回切换页面 内存会大幅增加，一段时间后也不释放。
echarts图表在组件销毁的时候没同步销毁。
导致组件在挂载的时候又生成了实例。

```js

onBeforeUnmount(() => {
    window.removeEventListener('resize', changeChartSize);
});



```

### 重现步骤

+ 打开浏览器控制台，切换到`性能监视器`页面。
+ 来回切换[监控页面](https://demo.1panel.cn/hosts/monitor/monitor)和[概览页面](https://demo.1panel.cn/)。
+ 观察控制台性能监视器页面的js堆大小。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述问题。

**Comment by zhengkunwang223** [comment]
v1.4.0 版本已修复此问题
