### ISSUE TITLE
[FEATURE]应用商店增加metersphere的安装和metersphere的数据备份

### ISSUE THREAD

**Issue by YellCatt** [1Panel-dev/1Panel#1613]
### 1Panel 版本

1.3.6

### 请描述您的需求或者改进建议

需求：应用商店增加metersphere的安装和metersphere的数据备份
原因：自家的应用自家也不推广，且从1panel上安装，对用户体验提升比较好

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持在应用商店安装 MeterSphere。

**Comment by wanghe-fit2cloud** [comment]
v3.0.0-beta 版本已经上架 1Panel 应用商店。
