### ISSUE TITLE
[BUG]使用 阿里云DNS 申请证书时，会删除 A 或 CNAME 记录。

### ISSUE THREAD

**Issue by zysam** [1Panel-dev/1Panel#1617]
### 1Panel 版本

1.36

### 问题描述

使用 阿里云DNS 申请证书时，会删除 A 或 CNAME 记录。
看到经常丢失二级域名，就排查下，发现申请证书后，不但删除 TXT 记录，而且把域名记录也删除了（删除的二级域名不一定是申请的二级域名）。

可能是删除记录逻辑有Bug，获取到其他域名ID了。

### 重现步骤

多次测试不同域名和泛域名，可以重现（删除的二级域名不一定是申请的二级域名）

**Comment by zhengkunwang223** [comment]
您好 经过我实际测试 没有发现有删除 A 或者 CNAME 记录的问题
我们用的申请工具为 lego https://github.com/go-acme/lego
如果确实有问题 可以提供具体的视频 阿里云的DNS解析日志  或者 在企业微信群联系 “程会玩”

**Comment by zysam** [comment]
> 您好 经过我实际测试 没有发现有删除 A 或者 CNAME 记录的问题 我们用的申请工具为 lego https://github.com/go-acme/lego 如果确实有问题 可以提供具体的视频 阿里云的DNS解析日志 或者 在企业微信群联系 “程会玩”

开始是看了aliyin 通知邮件才发现被删了域名记录，再次申请新的域名证书（二级域名+二级泛域名）时，果然又删了。aliyun key 操作删除也有记录（只是看不出来具体删哪些记录）

你要具体视频，只是一个操作结果而已。就算提供邮件截图，也只是一个结果。

**Comment by zysam** [comment]
1panel 用的lego版本 4.9，大概看了 lego 的 issue， 关于 alidns 在 >4.9 版本有不少修复。但是我不熟悉 go 开发，无法具体验证。大概看了 1panel ssl 逻辑，问题应该是 lego 库上。

**Comment by zhengkunwang223** [comment]
> 1panel 用的lego版本 4.9，大概看了 lego 的 issue， 关于 alidns 在 >4.9 版本有不少修复。但是我不熟悉 go 开发，无法具体验证。大概看了 1panel ssl 逻辑，问题应该是 lego 库上。

ok 这个我们看一下 升级一下 lego

**Comment by mscststs** [comment]
DNSPOD 同样问题 
![image](https://github.com/1Panel-dev/1Panel/assets/18003247/2c270b8c-cfbe-48c0-ba8a-f05ffa4e5e16)

运行版本：v1.5.5

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
