### ISSUE TITLE
[FEATURE] 申请证书体验优化

### ISSUE THREAD

**Issue by heroixinu** [1Panel-dev/1Panel#1621]
### 1Panel 版本

v1.3.6

### 请描述您的需求或者改进建议

创建证书时如果此域名为已经在1panel登记反向代理的网站申请证书会申请失败

### 请描述你建议的实现方案

建议创建证书的流程增加一个步骤，为已有网站申请证书或输入域名申请证书
此时如果该网站类型为已有网站并且为反向代理的网站，临时取消其反代来应对ACME验证

### 附加信息

1panel面向比较新的容器化场景，反向代理是网站模块里使用频率较高的一个场景，这个场景下为反代网站申请证书更是高频操作，目前如果有此需求，需要在网站模块下取消网站的反代记录，然后重新申请证书，便捷性较差

**Comment by zhengkunwang223** [comment]
“创建证书时如果此域名为已经在1panel登记反向代理的网站申请证书会申请失败”
请问是什么类型的证书？DNS HTTP 还是手动模式呢

**Comment by heroixinu** [comment]
HTTP模式，我没记错的话，HTTP模式其实是在域名目录下增加了一个文件用于验证，但是这个文件在反代的时候显然是访问不到的。

**Comment by heroixinu** [comment]
error: one or more domains had a problem: [xxx] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: xxx: Invalid response from xxx/.well-known/acme-challenge/xxx: 404

**Comment by zhengkunwang223** [comment]
> HTTP模式，我没记错的话，HTTP模式其实是在域名目录下增加了一个文件用于验证，但是这个文件在反代的时候显然是访问不到的。

反代也是可以访问到的 不影响

**Comment by heroixinu** [comment]
> > HTTP模式，我没记错的话，HTTP模式其实是在域名目录下增加了一个文件用于验证，但是这个文件在反代的时候显然是访问不到的。
> 
> 反代也是可以访问到的 不影响

上面给你贴出我刚申请的报错信息了

**Comment by zhengkunwang223** [comment]
> > > HTTP模式，我没记错的话，HTTP模式其实是在域名目录下增加了一个文件用于验证，但是这个文件在反代的时候显然是访问不到的。
> > 
> > 
> > 反代也是可以访问到的 不影响
> 
> 上面给你贴出我刚申请的报错信息了

请问你反代的是什么应用 我测试了几个反代网站 申请证书都没问题

**Comment by heroixinu** [comment]
> > > > HTTP模式，我没记错的话，HTTP模式其实是在域名目录下增加了一个文件用于验证，但是这个文件在反代的时候显然是访问不到的。
> > > 
> > > 
> > > 反代也是可以访问到的 不影响
> > 
> > 
> > 上面给你贴出我刚申请的报错信息了
> 
> 请问你反代的是什么应用 我测试了几个反代网站 申请证书都没问题

操作步骤：
1.创建网站-》反向代理-》主域名a.demo.com-》代理地址http://127.0.0.1:34214
2.证书-》创建证书-》输入a.demo.com -》验证方式HTTP
3.报错，申请失败

其中demo.com 为实例域名，已将此域名泛解析到主机ip

**Comment by zhengkunwang223** [comment]
> > > > > HTTP模式，我没记错的话，HTTP模式其实是在域名目录下增加了一个文件用于验证，但是这个文件在反代的时候显然是访问不到的。
> > > > 
> > > > 
> > > > 反代也是可以访问到的 不影响
> > > 
> > > 
> > > 上面给你贴出我刚申请的报错信息了
> > 
> > 
> > 请问你反代的是什么应用 我测试了几个反代网站 申请证书都没问题
> 
> 操作步骤： 1.创建网站-》反向代理-》主域名a.demo.com-》代理地址http://127.0.0.1:34214 2.证书-》创建证书-》输入a.demo.com -》验证方式HTTP 3.报错，申请失败
> 
> 其中demo.com 为实例域名，已将此域名泛解析到主机ip

你可以申请泛域名证书

**Comment by heroixinu** [comment]
> > > > > > HTTP模式，我没记错的话，HTTP模式其实是在域名目录下增加了一个文件用于验证，但是这个文件在反代的时候显然是访问不到的。
> > > > > 
> > > > > 
> > > > > 反代也是可以访问到的 不影响
> > > > 
> > > > 
> > > > 上面给你贴出我刚申请的报错信息了
> > > 
> > > 
> > > 请问你反代的是什么应用 我测试了几个反代网站 申请证书都没问题
> > 
> > 
> > 操作步骤： 1.创建网站-》反向代理-》主域名a.demo.com-》代理地址http://127.0.0.1:34214 2.证书-》创建证书-》输入a.demo.com -》验证方式HTTP 3.报错，申请失败
> > 其中demo.com 为实例域名，已将此域名泛解析到主机ip
> 
> 你可以申请泛域名证书

得，合着你是和稀泥的，问题还是复现不出来？？？

**Comment by zhengkunwang223** [comment]
> > > > > > > HTTP模式，我没记错的话，HTTP模式其实是在域名目录下增加了一个文件用于验证，但是这个文件在反代的时候显然是访问不到的。
> 
> > > > > > 
> 
> > > > > > 
> 
> > > > > > 反代也是可以访问到的 不影响
> 
> > > > > 
> 
> > > > > 
> 
> > > > > 上面给你贴出我刚申请的报错信息了
> 
> > > > 
> 
> > > > 
> 
> > > > 请问你反代的是什么应用 我测试了几个反代网站 申请证书都没问题
> 
> > > 
> 
> > > 
> 
> > > 操作步骤： 1.创建网站-》反向代理-》主域名a.demo.com-》代理地址http://127.0.0.1:34214 2.证书-》创建证书-》输入a.demo.com -》验证方式HTTP 3.报错，申请失败
> 
> > > 其中demo.com 为实例域名，已将此域名泛解析到主机ip
> 
> > 
> 
> > 你可以申请泛域名证书
> 
> 
> 
> 得，合着你是和稀泥的，问题还是复现不出来？？？

确实无法复现

**Comment by hnuzhoulin** [comment]
我是间歇性失败，过一会可能又好了，对于http方式申请ssl不行的话将
```
location ~ /.well-known/acme-challenge  
#改为
location ^~ /.well-known/acme-challenge
```
试一试，手动模式偶尔也会失败，不纠结了。

**Comment by benzBrake** [comment]
> 我是间歇性失败，过一会可能又好了，对于http方式申请ssl不行的话将
> 
> ```
> location ~ /.well-known/acme-challenge  
> #改为
> location ^~ /.well-known/acme-challenge
> ```
> 
> 试一试，手动模式偶尔也会失败，不纠结了。

我反代 alist，改了也不行，次次复现

**Comment by gee1k** [comment]
> 我是间歇性失败，过一会可能又好了，对于http方式申请ssl不行的话将
> 
> ```
> location ~ /.well-known/acme-challenge  
> #改为
> location ^~ /.well-known/acme-challenge
> ```
> 
> 试一试，手动模式偶尔也会失败，不纠结了。

改完可以了，官方就是嘴硬啊
