### ISSUE TITLE
[BUG] nginx运行状态显示异常

### ISSUE THREAD

**Issue by iLayPark** [1Panel-dev/1Panel#1625]
### 1Panel 版本

v1.4.0

### 问题描述

应用商店显示已停止，但是在容器管理里是正常运行的
![](https://s3.bmp.ovh/imgs/2023/07/12/9844eddf7b6c2893.png)

![](https://s3.bmp.ovh/imgs/2023/07/12/040c82ea286665f9.png)

### 重现步骤

应用商店显示已停止，但是在容器管理里是正常运行的，尝试重建、同步都没用

**Comment by zhengkunwang223** [comment]
同步一下应用看看

**Comment by iLayPark** [comment]
> 同步一下应用看看

没用

**Comment by zhengkunwang223** [comment]
> > 同步一下应用看看
> 
> 没用

可以尝试重建应用

**Comment by iLayPark** [comment]
> 尝试重建、同步都没用

上面说了，尝试重建、同步都没用

**Comment by zhengkunwang223** [comment]
> > 尝试重建、同步都没用
> 
> 
> 
> 上面说了，尝试重建、同步都没用

参数 - 编辑 - 保存

**Comment by iLayPark** [comment]
> 

可以了
