### ISSUE TITLE
[BUG] 网站HTTPS配置，选择对应的证书后保存无效

### ISSUE THREAD

**Issue by icpd** [1Panel-dev/1Panel#1626]
### 1Panel 版本

v1.4.0

### 问题描述

选择对应的证书并保存后，下拉框回填选中始终是第一个值

### 重现步骤

进入站点配置HTTPS，选择证书后点击保存，等待数据刷新或者手动刷新页面

### 期待的正确结果

回填选择的证书

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/35096485/b3d4c2e6-12ed-4daa-a08c-abea86feff94)

**Comment by zhengkunwang223** [comment]
已复现 下个小版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.4.1 版本已发布。
