### ISSUE TITLE
[BUG] docker 镜像的端口列表展开后收起的多语言未翻译

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#1628]
### 1Panel 版本

1.4.0

### 问题描述

docker 镜像的端口列表展开后收起的多语言未翻译

### 重现步骤

docker 镜像的端口列表展开后收起的多语言未翻译

**Comment by mx2913** [comment]
github 无法上传文件，展开后收起按钮变成了 commons.button.shrink

**Comment by ssongliu** [comment]
感谢反馈！下个小版本修改。

**Comment by wanghe-fit2cloud** [comment]
v1.4.2 版本已发布。
