### ISSUE TITLE
[BUG]某些容器的编辑窗口打不开

### ISSUE THREAD

**Issue by csthenry** [1Panel-dev/1Panel#1631]
### 1Panel 版本

1.4.1

### 问题描述

某些容器的编辑窗口打不开，并且gitea也检测不到1.19.4更新。
![屏幕截图 2023-07-12 231249](https://github.com/1Panel-dev/1Panel/assets/32993468/1d90db2e-702a-4650-b720-de7d957eb028)

### 重现步骤

某些容器的编辑窗口打不开

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地测试环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.4.2 版本已发布。
