### ISSUE TITLE
[QUESTION]面板证书配置问题

### ISSUE THREAD

**Issue by micro-CAO** [1Panel-dev/1Panel#1633]
### 请描述您的问题

我记得是能在面板“设置>安全>https”来使用在“网站>证书”中申请到的http证书，
不懂为什么，现在再“选择已有”选项中，只见选择证书时出现“无数据”。我只能另辟蹊径把申请到的证书的公私钥分别复制到“导入”一栏来启用面板访问证书
昨天下午刚装上，经过了一次版本更新，现在是v1.4.1。
不太懂这好产品，希望能有个解决方案吧。
![424EB8C5-C7F3-421C-929D-7F6A825F50F0](https://github.com/1Panel-dev/1Panel/assets/70780880/128b30f1-1da0-4a3d-8575-75afa764f69e)

**Comment by ssongliu** [comment]
感谢反馈！该问题在本地已复现，将在下个小版本解决。

**Comment by wanghe-fit2cloud** [comment]
v1.4.2 版本已发布。
