### ISSUE TITLE
[BUG]首页概览监控刷新会自动把展开的恢复默认

### ISSUE THREAD

**Issue by mengxunlingxue** [1Panel-dev/1Panel#1634]
### 联系方式

1Panel 交流群1-梦寻凌雪

### 1Panel 版本

v1.4.1

### 问题描述

登陆面板后首页概览
监控系统数据在自动定时3s刷新
当我需要展开未展示的监控数据的时候
会自动把展开的恢复默认状态，无法正常查看
3s时间来不及看清就重新隐藏了

https://github.com/1Panel-dev/1Panel/assets/24265178/3ab0b120-1165-4dcf-808a-5a3e1a6fc6ae

### 重现步骤

如图

**Comment by ssongliu** [comment]
感谢反馈！下个小版本修复这个问题。

**Comment by wanghe-fit2cloud** [comment]
v1.4.2 版本已发布。
