### ISSUE TITLE
[BUG]登录日志记录显示异常

### ISSUE THREAD

**Issue by qrekkwijjtx54** [1Panel-dev/1Panel#1635]
### 联系方式

暂无

### 1Panel 版本

1.4.1

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/118114198/a7f71935-6307-41df-87da-a47a394f56c0)
登录日志显示错误，无论是SSH登录还是网站登录均无记录

### 重现步骤

登录即可查看

### 期待的正确结果

修复相关错误

**Comment by ssongliu** [comment]
感谢反馈！ssh 日志我们是直接读取的 /var/log/auth.log 或者 /var/log/secure-xxx 文件。
可以手动输入以下命令尝试获取一下：
cat /var/log/auth.log | grep -a Accepted
cat /var/log/secure | grep -a Accepted

**Comment by qrekkwijjtx54** [comment]
> 感谢反馈！ssh 日志我们是直接读取的 /var/log/auth.log 或者 /var/log/secure-xxx 文件。 可以手动输入以下命令尝试获取一下： cat /var/log/auth.log | grep -a Accepted cat /var/log/secure | grep -a Accepted

@ssongliu  命令获取第一条无问题，第二条报错
![image](https://github.com/1Panel-dev/1Panel/assets/118114198/1e72c3a3-d388-4630-9e95-0df22773fc88)

![image](https://github.com/1Panel-dev/1Panel/assets/118114198/678d1ebd-b626-48e9-8f2f-4a6fd034f502)
我用的系统是Ubuntu23.04
![image](https://github.com/1Panel-dev/1Panel/assets/118114198/d8bf2b33-25e5-4848-a98d-9405d0672962)

但是网站的登录日志均无输出
![image](https://github.com/1Panel-dev/1Panel/assets/118114198/f0f7b773-03ec-4bfe-9503-54e4ad547a0e)

**Comment by ssongliu** [comment]
你好，v1.5.0 版本对这块进行了优化，可以升级后看一下还有没有这个问题

**Comment by jc955** [comment]
@ssongliu  @wanghe-fit2cloud  最新版貌似没解决  /var/log/auth.log ssh登录已写入，1Panel没显示
### 
我的系统是
```bash
root@VM-0-7-debian:~# uname -a
Linux VM-0-7-debian 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux
```

**Comment by jc955** [comment]
@wanghe-fit2cloud
