### ISSUE TITLE
[FEATURE]PHP运行环境功能建议

### ISSUE THREAD

**Issue by qrekkwijjtx54** [1Panel-dev/1Panel#1636]
### 1Panel 版本

1.4.1

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/118114198/cbb89eac-9501-429d-a809-903962688182)
PHP扩展需要一个个选，能否可以通过复制粘贴的方式实现。我重新在创建一个PHP7的环境就不用一个个的选了...

### 请描述你建议的实现方案

同上

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中持续优化。

**Comment by wanghe-fit2cloud** [comment]
近期版本会支持 PHP 扩展的模版管理功能。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
