### ISSUE TITLE
[BUG]运行时dokerd CPU使用率爆表，并且应用无相关占用

### ISSUE THREAD

**Issue by qrekkwijjtx54** [1Panel-dev/1Panel#1637]
### 1Panel 版本

1.4.1

### 问题描述

![7208355619e2f7c0c70ab1e557233a3](https://github.com/1Panel-dev/1Panel/assets/118114198/ce6cbae4-7d6f-4972-8cc0-7d5510ec60b8)
运行网站大概10分钟之后CPU使用率爆表.....

### 重现步骤

在运行一段时间后，网站CPU使用率明显上升，并且查看容器并无相关的应用占用CPU.

**Comment by ssongliu** [comment]
感谢反馈！你有加社区群吗，我远程看一下这个问题。

**Comment by qrekkwijjtx54** [comment]
> 感谢反馈！你有加社区群吗，我远程看看这个问题。

@ssongliu  重装服务器后，现在这个问题似乎没有出现过了。
