### ISSUE TITLE
设置伪静态时面板报错

### ISSUE THREAD

**Issue by micro-CAO** [1Panel-dev/1Panel#1641]
### 联系方式

yidizhihongxia@outlook.com

### 1Panel 版本

1.4.1

### 问题描述

个人认为是面板自身没有配置好openresty服务导致的，详细报错如图
![18C340A0-7794-4A1C-B339-7139D83BDB3D](https://github.com/1Panel-dev/1Panel/assets/70780880/1318406b-638e-477d-aff6-cc3fc860e790)
![0912BFFD-C75A-4AE8-A727-E15C9E1C5DBF](https://github.com/1Panel-dev/1Panel/assets/70780880/bf7f67b2-366f-4c1d-a4bd-6820b57edb37)
![4525F776-2A49-43DB-971D-55FB73088891](https://github.com/1Panel-dev/1Panel/assets/70780880/e11b049d-747c-4e25-bc14-cc50dbe8215c)

### 重现步骤

拿一个Wordpress站点或者静态站点设置伪静态

**Comment by zhengkunwang223** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/987796c1-575d-48e6-84f3-783277286ece)
这个错误显示有 重复的 location / ，看一下反向代理 TAB 页是否有前端请求路径为 / 的代理

**Comment by yggcwx** [comment]
遇到了完全相同的问题

**Comment by wanghe-fit2cloud** [comment]
> 遇到了完全相同的问题

https://bbs.fit2cloud.com/t/topic/998
