### ISSUE TITLE
[FEATURE]建议整个端口备注

### ISSUE THREAD

**Issue by W4J1e** [1Panel-dev/1Panel#1642]
### 1Panel 版本

v1.4.1

### 请描述您的需求或者改进建议

建议给端口备注功能安排上，除了 1panel 和在商店安装的应用外，手动开放的端口没有备注容易记不住。

### 请描述你建议的实现方案

这个不用我多说了吧。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by Satisfy8375** [comment]
同样的需求，没想到已经有人提了

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
