### ISSUE TITLE
[FEATURE]建议商店支持 fail2ban

### ISSUE THREAD

**Issue by W4J1e** [1Panel-dev/1Panel#1643]
### 1Panel 版本

V1.4.1

### 请描述您的需求或者改进建议

昨天才换上 1panel 的轻量鸡目前没出现，但是香港的小鸡已经被扫了 N 遍 ssh 端口和爆破了，请求上 fail2ban。
![image](https://github.com/1Panel-dev/1Panel/assets/74824162/8ce3b2b8-3f0d-434a-8c56-bac05d1b9f06)

### 请描述你建议的实现方案

有一个应用就叫 fail2ban

**Comment by W4J1e** [comment]
#250

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，已经纳入迭代计划，近期版本会支持。

**Comment by maninhill** [comment]
这个抓紧上。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
