### ISSUE TITLE
[BUG] deepin系统上ssh管理显示bug

### ISSUE THREAD

**Issue by JayHaul** [1Panel-dev/1Panel#1646]
### 1Panel 版本

1.4.1

### 问题描述

deepin上ssh管理有关ssh命令应该用 `systemctl status ssh`而非 `systemctl status sshd`

### 重现步骤

ssh管理开启ssh
![截图](https://github.com/1Panel-dev/1Panel/assets/51446245/dfaa47ab-1aca-4ca4-811a-a52ce0a8d2b3)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦提供一下操作系统的具体版本：
```shell
cat /etc/os-release
```

**Comment by JayHaul** [comment]
PRETTY_NAME="Deepin 20.9"

NAME="Deepin"

VERSION_ID="20.9"

VERSION="20.9"

VERSION_CODENAME="apricot"

ID=Deepin

HOME_URL="https://www.deepin.org/"

BUG_REPORT_URL="https://bbs.deepin.org/"


> 感谢反馈，麻烦提供一下操作系统的具体版本：
> 
> ```shell
> cat /etc/os-release
> ```

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
