### ISSUE TITLE
[FEATURE] 建议添加应用的时候可选择ipv6端口映射

### ISSUE THREAD

**Issue by JayHaul** [1Panel-dev/1Panel#1647]
### 1Panel 版本

1.4.1

### 请描述您的需求或者改进建议

![添加应用](https://github.com/1Panel-dev/1Panel/assets/51446245/b3f2cbf0-11ec-474e-94e6-138a06647918)
如图，在以上位置或者高级里面加个ipv6映射设置

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
最新版本已经支持 IPv6 相关配置(`容器` - `配置` 页面)，并支持创建 IPv6 容器网络。
> 配置完成后，在创建应用，选择对外暴露端口，端口就会默认监听 IPv4 和 IPv6 网络。
