### ISSUE TITLE
[BUG]面板SSL证书无法自动导入

### ISSUE THREAD

**Issue by TiaraBasori** [1Panel-dev/1Panel#1648]
### 联系方式

mintabyss233@gmail.com/TG@MintAbys

### 1Panel 版本

1.4.1

### 问题描述

申请完面板域名的SSL证书后再面板HTTPS设置里导入证书显示无，只能手动导入

### 重现步骤

如问题描述

### 期待的正确结果

菜单应该可以被打开且能看到刚刚申请的域名

### 相关日志输出

```shell
/
```

### 附加信息

/

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在 v1.4.2 版本中修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.4.2 版本已发布。
