### ISSUE TITLE
[BUG]docker容器日志有的显示乱码

### ISSUE THREAD

**Issue by x2287711259** [1Panel-dev/1Panel#1655]
### 1Panel 版本

v1.4.0

### 问题描述

我docker安装了一个英雄联盟自动观赛容器，之前一直用portainer来管理docker容器，日志里可以很清楚的看到当前各个赛区哪些赛区正在比赛，有无观赛奖励掉落，是英文显示的，但是用咱们的面板的话，容器日志显示有乱码

### 重现步骤

涉及到的项目：https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/wiki/Advanced-Installation-for-Docker
可以分别用咱们的1panel面板和portainer查看日志，差别还是很明显，希望尽快优化好

### 期待的正确结果

这个项目的日志应该是表格和英文，希望正确显示

### 相关日志输出

```shell
[2K[1A[2K[1A[2K[1A[2K[1A[2K┏━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┓
┃[1m [0m[1mAccount [0m[1m [0m┃[1m [0m[1mStatus[0m[1m [0m┃[1m [0m[1mLive matches[0m[1m [0m┃[1m [0m[1mHeartbeat     [0m[1m [0m┃[1m [0m[1mLast drop           [0m[1m [0m┃[1m [0m[1mSession Drops[0m[1m [0m┃[1m [0m[1mLifetime Drops[0m[1m [0m┃
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
