### ISSUE TITLE
[FEATURE]docker容器排序希望能自定义

### ISSUE THREAD

**Issue by x2287711259** [1Panel-dev/1Panel#1656]
### 1Panel 版本

v1.4.0

### 请描述您的需求或者改进建议

docker容器的管理界面希望能增加docker容器自定义排序的功能，可以把每个docker容器做成一个可拖动的长方块或者在左右两端增加可拖动按钮，鼠标左键长按可以上下拖动进行排序。也可以在每个docker容器框上面加上下箭头，直接点按进行上下排序。
另外目前docker容器管理界面的根据名称和状态进行排序，还有列表设置里的定时刷新无法保存，切到别的界面再切回来设置就失效了，希望这个状态切换能变成永久的.
还有就是目前查看日志，日志是不是无法在查看的界面自动更新啊，好像每次都得重新打开日志才能看到最新的，如果是的话希望能够在查看日志的界面实时更新最新的日志

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by ssongliu** [comment]
1. 自定义排序，我们暂时支持了通过名称和状态排序，和状态的筛选功能；
2. 1.8 版本会支持缓存容器页刷新状态；
3. 查看日志可以勾选日志上面的追踪按钮，实时获取日志输出。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
