### ISSUE TITLE
[BUG] KubePi 应用安装后通过反向代理后，KubePi 无法获取客户端的真实IP

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#1657]
### 1Panel 版本

1.4.1

### 问题描述

[BUG] KubePi 应用安装后通过反向代理后，KubePi 无法获取客户端的真实IP

### 重现步骤

安装 KubePi 后配置反向代理，登陆 KubePi 之后在登陆日志中看到的客户端 IP 为容器的 ip 地址

**Comment by mx2913** [comment]
<img width="1741" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/15864713/652c66f1-3bfd-4f71-b85c-36e58b4d6830">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。我们会在后续版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
我们测试反代其他应用未复现上述问题，建议将问题反馈给 KubePi Issue:
https://github.com/1Panel-dev/KubePi/issues
