### ISSUE TITLE
1pctl 增加回滚功能 [FEATURE]

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1660]
### 1Panel 版本

v1.4.1

### 请描述您的需求或者改进建议

1.3.6 升级到 1.4.0 过程中，升级成功，但是由于数据问题无法启动服务，只能手动修改数据库，就比较麻烦。

### 请描述你建议的实现方案

有看到在升级的时候，会自动在 /opt/1panel/tmp 下面增加原版本的备份，是否可以直接加一个 1pctl 命令使用它进行恢复操作 。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述需求我们会在下个版本支持。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
