### ISSUE TITLE
增加磁盘空间释放 [FEATURE]

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1661]
### 1Panel 版本

1.4.1

### 请描述您的需求或者改进建议

当前版本在容器、镜像等界面都有单独清理功能，希望在概览界面增加一个 1panel 全局的清理。

### 请描述你建议的实现方案

能否增加一个磁盘空间释放操作，提供选项包括且不局限于：
-     镜像、网络、存储卷等；
-     1panel 产生的中间文件，比如说升级过程中产生的备份，安装目录下的各种空文件夹等；
-     各类日志文件、如系统日志、登录日志、面板日志等（仅保留具体天数）；
-     安装过但已卸载的应用文件等。

**Comment by lanyani** [comment]
支持，支持需要这个功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述功能。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
