### ISSUE TITLE
【爱发电】感谢支持 1Panel 项目的朋友们

### ISSUE THREAD

**Issue by maninhill** [1Panel-dev/1Panel#1662]
### 请描述您的问题

大家可以通过「爱发电」支持 1Panel 项目。地址是：https://afdian.net/a/1Panel

**Comment by zhengkunwang223** [comment]
> 感谢以下社区用户的信任和支持（持续更新）：
新昵称
爱发电用户_s9Fd
盐爪
爱发电用户_aekr
爱发电用户_QGt9
薛定谔の饿猫
SKRN_Yukari
爱发电用户_HG9A
爱发电用户_cuw8
爱发电用户_UTSV
nil
爱发电用户_QJnk
爱发电用户_cU4r
TR-M
爱发电用户_8c65f
cmlanche
爱发电用户_c37c6
爱发电用户_de7be
爱发电用户_HJfG
爱发电用户_kYCp
爱发电用户_6ec0b
爱发电用户_329c7
TaoR
爱发电用户_64d4b
爱发电用户_KSB4
爱发电用户_45eb0
爱发电用户_Pn37
爱发电用户_0d727
爱发电用户_3eca6
爱发电用户_83b9e
Frost-ZX
王登登`
木人
谢箫生
timochan
未拥怎弃
爱发电用户_8fa10
爱发电用户_0a2ba
綦桐网络
天启之云
Papklp
爱发电用户_29d9b
爱发电用户_8b6b9
HAPPY MC
爱发电用户_02655
爱发电用户_EkG4
Microi
liming
ivye
yxj
爱发电用户_6fe28
爱发电用户_3KnA
爱发电用户_2ac5b
xiaobai
爱发电用户_6e690
LuvLetter
fang2hou
爱发电用户_0664a
YuanMoe
爱发电用户_28b48
爱发电用户_830f2
爱发电用户_828fa
爱发电用户_8b649
爱发电用户_9b07c
浮心物语
爱发电用户_acf1f
路漫漫其修远兮
bas
爱发电用户_c46d8
Howie
爱发电用户_Hrtc
Frisk
earthjasonlin
爱发电用户_25c92
爱发电用户_c606d
西安爱铭网络科技有限公司
爱发电用户_ae7d4
Etrsun
爱发电用户_a5640
阿涛站长笔记
爱发电用户_43vr
我想从良
爱发电用户_KChd
爱发电用户_19a19
綦桐网络
爱发电用户_97681
DongShaoNB
?? ? ? ? ?
qaz6750
Henry Wu
岱宗夫如何？
Henry Wu
小手搓搓
飞致云黄宗泽
昕宇
建国见过大个坚果
副驾仙人
局座
爱发电用户_be859
MatataYou
爱发电用户_6ea83
爱发电用户_rFXd
爱发电用户_dcea7
爱发电用户_9498a

**Comment by zhengkunwang223** [comment]
> 感谢以下社区用户的信任和支持（持续更新）：
> 
> * [爱发电用户_GNwm](https://afdian.net/u/b63057c821f611eea5fe52540025c377)
> * [梦寻凌雪](https://afdian.net/u/6ea8347a21f611ee992d5254001e7c00)
> * [爱发电用户_rFXd](https://afdian.net/u/0f4aac7421f611ee851552540025c377)
> * [阿巴怪](https://afdian.net/u/dcea74c221f411eebd7c52540025c377)
> * [风の语](https://afdian.net/u/9498a4be21f411eeae5552540025c377)
> * [丹墨汐](https://afdian.net/u/be859f7e21fa11ee86df52540025c377)
> * [局座](https://afdian.net/u/e5b5f08821fc11ee9ec152540025c377)
> * [建国见过大个坚果](https://afdian.net/u/0b822608220a11eebbc152540025c377)
> * [副驾仙人](https://afdian.net/u/a2e8a76621ff11eeaad252540025c377)
> * [Henry Wu](https://afdian.net/u/146082de221811ee92d552540025c377)
> * [小手搓搓](https://afdian.net/u/98675b2a221311eea17552540025c377)
> * [飞致云黄宗泽](https://afdian.net/u/eb6672c6221211ee955d52540025c377)
> * [昕宇](https://afdian.net/u/056a4782ea4711eda73152540025c377)
> * [qaz6750](https://afdian.net/u/23024eb423fb11eeb14c5254001e7c00)
> * [岱宗夫如何？](https://afdian.net/u/526e3bbe18d311eea5885254001e7c00)
> * [DongShaoNB](https://afdian.net/a/minecraft666)
> * [emit](https://afdian.net/u/97681554395611ec88cc52540025c377)
> * [我想从良](https://afdian.net/u/11d093a226f411eebddd52540025c377)
> * [爱发电用户_KChd](https://afdian.net/u/e21c51f6f6c811edbcac52540025c377)
> * [果冻不是布丁](https://afdian.net/u/c606dc7a2b4811eeb1ed5254001e7c00)
> * [西安爱铭网络科技有限公司](https://afdian.net/a/aiming)
> * [风之凯](https://afdian.net/u/ae7d43bc23b211eda4f152540025c377)
> * [Etrsun](https://afdian.net/u/44d40f6a2af811eeb1395254001e7c00)
> * [阿涛站长笔记](https://afdian.net/u/144cd5c82af511eeb5c052540025c377)
> * [bas](https://afdian.net/u/3adb3a642d2e11eeb90f5254001e7c00)
> * [奥德修斯](https://afdian.net/u/c46d89a42d2d11eeb6415254001e7c00)
> * [Howie](https://afdian.net/u/e3f3edfa2d2c11eeaf0052540025c377)
> * [爱发电用户_Hrtc](https://afdian.net/u/2cc67cce249411eea68d52540025c377)
> * [Frisk](https://afdian.net/u/b3a4a1720d6f11ed801352540025c377)
> * [earthjasonlin](https://afdian.net/a/earthjasonlin)
> * [lemon](https://afdian.net/u/25c9290c2c6a11ee965c52540025c377)
> * [指南不是个艺术家](https://afdian.net/u/28b4820a36b111ee95045254001e7c00)
> * [fantasy](https://afdian.net/u/830f26ce36ac11ee848a52540025c377)
> * [无名](https://afdian.net/u/828fa61c366411ee833f52540025c377)
> * [爱发电用户_K8wE](https://afdian.net/u/8b64940632ad11eeab3f52540025c377)
> * [芒果冰](https://afdian.net/u/9b07cc6e9edb11eca0f452540025c377)
> * [浮心物语](https://afdian.net/u/78fa21b8a3fd11ec95ef52540025c377)
> * [全磊](https://afdian.net/u/acf1f8f22b0011eeaca252540025c377)
> * 爱发电用户_KeCX
> * ivye
> * yxj
> * 强
> * 爱发电用户_3KnA
> * 无可奉告
> * xiaobai
> * 尊狐云|idc.gd
> * LuvLetter
> * fang2hou
> * servcer@client[旺柴]💦
> * YuanMoe
> * 未拥怎弃
> * HKGCloud
> * wil-we
> * 綦桐网络
> * 天启之云
> * Papklp
> * Neo_777
> * M
> * HAPPY MC
> * 名字叫啥啊？
> * 爱发电用户_EkG4
> * Microi
> * liming
> * 爱发电用户_45eb0
> * 爱发电用户_Pn37
> * 爱发电用户_0d727
> * 爱发电用户_3eca6
> * 爱发电用户_83b9e
> * Frost-ZX
> * 王登登`
> * 木人
> * 谢箫生
> * timochan
> * 爱发电用户_KSB4
> * 爱发电用户_64d4b
> * TaoR
> * 爱发电用户_329c7
> * 爱发电用户_6ec0b
> * 爱发电用户_kYCp
> * 爱发电用户_HJfG
> * 爱发电用户_de7be
> * 爱发电用户_c37c6
> * cmlanche
> * 爱发电用户_8c65f
> * TR-M
> * 爱发电用户_cU4r
> * 发电用户_QJnk

**Comment by zhengkunwang223** [comment]
12月
![afdian-12月-104粉丝 (1)](https://github.com/1Panel-dev/1Panel/assets/31820853/6e5dd5dc-71e1-4bbd-8297-a4758e414774)

**Comment by zhengkunwang223** [comment]
2024 年 1 月
![afdian-1月-127粉丝](https://github.com/1Panel-dev/1Panel/assets/31820853/4dd0f063-52b7-445b-9123-13c42a681fac)

**Comment by zhengkunwang223** [comment]
2024 年 2 月
![afdian-2月-87粉丝](https://github.com/1Panel-dev/1Panel/assets/31820853/5fd261a3-38a2-459e-b8b1-97ea8966038f)
