### ISSUE TITLE
[BUG]站点启停运行目录问题

### ISSUE THREAD

**Issue by molaina-oiu** [1Panel-dev/1Panel#1665]
### 1Panel 版本

v1.3.1

### 问题描述

停止站点之后，再开启站点，运行目录会重置到根目录，但是站点设置里面还是显示自行设置的运行目录。比如我设置public为运行目录，暂停站点之后，再开启，运行目录会重置到根目录，但是设置里面还是显示public，需要重新选择然后保存重载

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/116413175/8b84c8d8-6e6c-4742-94f4-ed14c87d883d)
![image](https://github.com/1Panel-dev/1Panel/assets/116413175/b4f7aeaa-9209-4b67-a245-3a4a2d4398b4)
![image](https://github.com/1Panel-dev/1Panel/assets/116413175/44f11f54-13fa-4317-905a-583e21e5bd48)
暂停再开启，运行目录显示的是之前设置的，但实际已经到了根目录

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述问题我们会在 v1.4.2 版本修复。

**Comment by wanghe-fit2cloud** [comment]
v1.4.2 版本已发布。
