### ISSUE TITLE
[BUG]面板在 Firefox 浏览器中小字模糊

### ISSUE THREAD

**Issue by likecutie** [1Panel-dev/1Panel#1672]
### 联系方式

1Panel 交流群5 spark

### 1Panel 版本

1.4.1

### 问题描述

面板在 Firefox 浏览器中小字模糊，在 Edge 浏览器和 Google 浏览器中正常。

### 重现步骤

下载安装最新版 Firefox 浏览器，登录面板，页面中 12px 的字体显示模糊。
Firefox 截图：
![图片](https://github.com/1Panel-dev/1Panel/assets/49803345/e67c329b-4c28-483a-a108-e10a32f26d52)

### 期待的正确结果

字体显示清晰。
Google 截图：
![图片](https://github.com/1Panel-dev/1Panel/assets/49803345/bc28ff5c-d60f-4ce1-94e4-263bbb7d04eb)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本优化上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.4.3 版本已发布。
