### ISSUE TITLE
[BUG][BUG]更新后nginx变量有bug

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#1674]
### 1Panel 版本

1.4.2

### 问题描述

更新后，无法操作waf及保存nginx配置，报错如下
![图片](https://github.com/1Panel-dev/1Panel/assets/19621032/319bf573-35ea-4817-a54c-a7a3c9963137)
查看nginx配置后，似乎是变量没被识别
![图片](https://github.com/1Panel-dev/1Panel/assets/19621032/6b85e55a-9044-4218-8620-df366584732f)
之前是在1.3.6配置的，保存、操作都是正常的

### 重现步骤

1

**Comment by zhengkunwang223** [comment]
本次更新没有涉及到 openresty 
openresty 的校验规则是 nginx 的校验，配置文件有错误会报错
根据你的报错信息 你应该查看 proxy_pass 行的参数是否有误

**Comment by Felmon** [comment]
> 本次更新没有涉及到 openresty openresty 的校验规则是 nginx 的校验，配置文件有错误会报错 根据你的报错信息 你应该查看 proxy_pass 行的参数是否有误

第二个截图就是proxy_pass行的，反代这块是粘贴别人的，确定是没错的，之前和现在也是正常生效的，但就是现在没法开启waf也没法修改了

**Comment by Felmon** [comment]
> 本次更新没有涉及到 openresty openresty 的校验规则是 nginx 的校验，配置文件有错误会报错 根据你的报错信息 你应该查看 proxy_pass 行的参数是否有误

不确定是不是更新的问题，因为之前是直接编辑conf文件保存的，能正常生效运行。

**Comment by zhengkunwang223** [comment]
> > 本次更新没有涉及到 openresty openresty 的校验规则是 nginx 的校验，配置文件有错误会报错 根据你的报错信息 你应该查看 proxy_pass 行的参数是否有误
> 
> 
> 
> 不确定是不是更新的问题，因为之前是直接编辑conf文件保存的，能正常生效运行。

如果nginx文件中存在错误，那么很多操作都会报错，你可以先把 proxy pass 相关的代码删掉，然后再尝试，定位一下问题
