### ISSUE TITLE
[FEATURE]可以新增一个进程守护吗？

### ISSUE THREAD

**Issue by liangzad** [1Panel-dev/1Panel#1676]
### 1Panel 版本

v1.4.1-alpha.1

### 请描述您的需求或者改进建议

可以新增一个进程守护吗？？？？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述需求已经纳入迭代计划，近期版本就会支持。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
