### ISSUE TITLE
[QUESTION]定时切割后的网站日志去哪了？

### ISSUE THREAD

**Issue by W4J1e** [1Panel-dev/1Panel#1677]
### 请描述您的问题

在计划任务里添加了网站日志切割，每天0点执行。但是这几天下来在网站目录的 log 文件夹下始终只有 access.log 和 error.log 。
刚看到更新日志里有一项关于网站日志切割的修复，是修复了这个问题吗？

![image](https://github.com/1Panel-dev/1Panel/assets/74824162/8aa74ee4-0dda-4978-9054-473b045bbad8)

![image](https://github.com/1Panel-dev/1Panel/assets/74824162/6e474853-1e1d-434b-93aa-04a3c14e7996)

**Comment by wanghe-fit2cloud** [comment]
创建、编辑计划任务时，可查看提示信息，默认路径为 `/opt/1panel/backup/log/website`：
<img width="551" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/b192f2c5-6fc5-4cca-ac4b-c7baee3124df">
