### ISSUE TITLE
[FEATURE]主机防火墙支持针对服务标签进行设置

### ISSUE THREAD

**Issue by m4d3bug** [1Panel-dev/1Panel#1678]
### 1Panel 版本

v1.4.2

### 请描述您的需求或者改进建议

首先非常感谢你们的付出，想对防火墙的管理功能提一点建议。
cockpit的防火墙面板已经支持对特定的常见服务进行设置了，firewall-cmd自身也有选项支持，希望你们的防火墙也能够除了端口之外也支持针对服务标签进行设置。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中持续优化。

**Comment by wanghe-fit2cloud** [comment]
最新版本已经支持为防火墙端口设置描述信息。
