### ISSUE TITLE
[BUG] 部分已安装应用在新建网站时无法在一键部署中找到已安装的应用

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#1679]
### 1Panel 版本

1.4.2

### 问题描述

部分已安装应用在新建网站时无法在一键部署中找到已安装的应用
![图片](https://github.com/1Panel-dev/1Panel/assets/15864713/68bd5b85-d74d-4c34-bc90-cc636e014aeb)
![图片](https://github.com/1Panel-dev/1Panel/assets/15864713/ff87f13f-db82-48c3-888b-e6769e6ddfad)
![图片](https://github.com/1Panel-dev/1Panel/assets/15864713/ccea8def-c0b1-4e8a-b59e-d309d8eba162)

### 重现步骤

安装的 KubePi 和 Code-Server 都无法在新建网站时使用一键部署功能

**Comment by zhengkunwang223** [comment]
现阶段只有网站类型的可以一键部署，你可以用反向代理处理kubepi等应用
