### ISSUE TITLE
[BUG]  1. SQL恢复报错   2. 超长数据导入接口超时

### ISSUE THREAD

**Issue by cktk** [1Panel-dev/1Panel#1680]
### 联系方式

呆猫

### 1Panel 版本

v1.4.2

### 问题描述

BUG 1: 

<img width="906" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/49108554/5f1e7b3c-c89b-469b-9dd0-e6e406ae236a">

附录SQL 内容

`
-- ----------------------------
-- 表结构: cu_cushion_log 
-- ----------------------------
DROP TABLE IF EXISTS `cu_cushion_log`;
CREATE TABLE `cu_cushion_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `open_id` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '三方系统唯一标识',
  `platform` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '平台',
  `drive_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '设备名称',
  `drive_events` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '事件',
  `start_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '结束时间',
  `total_duration` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '持续时间',
  `create_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `update_id` bigint DEFAULT NULL COMMENT '更新者ID',
  `create_id` bigint DEFAULT NULL COMMENT '创建者ID',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '修改人',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `sort_order` int DEFAULT '0' COMMENT '排序',
  `del_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0' COMMENT '逻辑删除',
  `status` json DEFAULT NULL COMMENT '状态',
  `model_step` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `model_status` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `app_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='设备使用记录';

INSERT INTO `cu_cushion_log` VALUES (32, "oEh975TXaimw6DDyWoLU2aaM1QkI", "WechatMini", "Z1Z", "测试处方", "2022-11-24 12:01:28", "2022-11-24 12:03:28", "2 分钟", "未登录/未拿到", NULL, NULL, "2022-11-24 12:01:29", "未登录/未拿到", "2022-11-24 12:03:29", 0, "0", "[{\"status\": \"成功\", \"createTime\": \"2022-11-24 12:01:28\", \"statusName\": \"写入指令\", \"instruction\": \"AA040A7F0406C0040628010100BB\"}, {\"status\": \"成功\", \"createTime\": \"2022-11-24 12:01:38\", \"statusName\": \"写入指令\", \"instruction\": \"AA150A7F0406C00406281E0100BB\"}, {\"status\": \"成功\", \"createTime\": \"2022-11-24 12:01:48\", \"statusName\": \"写入指令\", \"instruction\": \"AA150A7F0406C00406281E0100BB\"}, {\"status\": \"成功\", \"createTime\": \"2022-11-24 12:01:58\", \"statusName\": \"写入指令\", \"instruction\": \"AA150A7F0406C00406281E0100BB\"}, {\"status\": \"成功\", \"createTime\": \"2022-11-24 12:02:08\", \"statusName\": \"写入指令\", \"instruction\": \"AA150A7F0406C00406281E0100BB\"}, {\"status\": \"成功\", \"createTime\": \"2022-11-24 12:02:18\", \"statusName\": \"写入指令\", \"instruction\": \"AA150A7F0406C00406281E0100BB\"}, {\"status\": \"成功\", \"createTime\": \"2022-11-24 12:02:28\", \"statusName\": \"写入指令\", \"instruction\": \"AA150A7F0406C00406281E0100BB\"}, {\"status\": \"成功\", \"createTime\": \"2022-11-24 12:02:38\", \"statusName\": \"写入指令\", \"instruction\": \"AA150A7F0406C00406281E0100BB\"}, {\"status\": \"成功\", \"createTime\": \"2022-11-24 12:02:48\", \"statusName\": \"写入指令\", \"instruction\": \"AA150A7F0406C00406281E0100BB\"}, {\"status\": \"成功\", \"createTime\": \"2022-11-24 12:02:58\", \"statusName\": \"写入指令\", \"instruction\": \"AA150A7F0406C00406281E0100BB\"}, {\"status\": \"成功\", \"createTime\": \"2022-11-24 12:03:08\", \"statusName\": \"写入指令\", \"instruction\": \"AA150A7F0406C00406281E0100BB\"}, {\"status\": \"成功\", \"createTime\": \"2022-11-24 12:03:18\", \"statusName\": \"写入指令\", \"instruction\": \"AA150A7F0406C00406281E0100BB\"}, {\"status\": \"成功\", \"createTime\": \"2022-11-24 12:03:28\", \"statusName\": \"写入指令\", \"instruction\": \"AA150A7F0406C00406281E0100BB\"}, {\"status\": \"成功\", \"createTime\": \"2022-11-24 12:03:28\", \"statusName\": \"执行完成\", \"instruction\": \"\"}]", "01", "执行成功", NULL);
`

BUG 2
当数据量比较大的时候无法获取返回结果  请求超时  建议通过轮训的形式查询导入的状态

<img width="958" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/49108554/4b186bd1-18ab-4998-bdff-b7bf72ebe865">

### 重现步骤

mysql->管理 备份->恢复 

### 期待的正确结果

应该是读取的时候编码的问题

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本修复上述问题。

**Comment by cktk** [comment]
其实我遇到了很多都是导入错误   包括各种格式上的导入错误      但是sql拿下来用navicat导入就没问题 其实我在想能不能 内置一下mysqldump  用这玩意进行备份恢复是不是会好点 有个项目 https://github.com/sfeng95/mx-db-backup  可以参考一下

**Comment by ssongliu** [comment]
BUG1 应该是 sql 本身的问题，尝试在 navcat 上面导入也是报错
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/8410bf05-5d41-4419-9ebe-0580857ad4e4)

BUG2 测试了一下，虽然超时时间设置的 10 分钟，但是文件比较大的情况下还是会超时。

**Comment by cktk** [comment]
> 

我这个sql是点击备份 你们给备份的 并不是从其他地方导出的sql

**Comment by ssongliu** [comment]
> > 
> 
> 我这个sql是点击备份 你们给备份的 并不是从其他地方导出的sql

有加社区群吗，我加你看一眼

**Comment by ssongliu** [comment]
> > 
> 
> 我这个sql是点击备份 你们给备份的 并不是从其他地方导出的sql

我改成单引号后，导入导出的 sql 都没问题，我们下周会发布 1.6 ，到时候可以更新一下重新试试。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
