### ISSUE TITLE
可否在容器中做个重建的功能？

### ISSUE THREAD

**Issue by GlodenBoy** [1Panel-dev/1Panel#1682]
### 1Panel 版本

最新

### 请描述您的需求或者改进建议

可否在容器中做个重建的功能？不是重启，是重建。

### 请描述你建议的实现方案

现在只有应用可以重建，但是如果自己打包的容器得自己做一个应用才行，有点麻烦，有时候升级了镜像，相关容器要重新新建就麻烦了，可否做一个重建按钮，给个二次提示什么的，因为会清除数据

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持容器重建功能。

**Comment by wanghe-fit2cloud** [comment]
考虑到持久化数据丢失等风险，我们暂无计划支持上述需求，望理解。
