### ISSUE TITLE
[FEATURE]在主机/防火墙/IP规则页面添加自动识别错误日志添加黑名单IP

### ISSUE THREAD

**Issue by licx506** [1Panel-dev/1Panel#1683]
### 1Panel 版本

v1.4.2

### 请描述您的需求或者改进建议

建议在主机/防火墙/IP规则页面添加一键识别错误登陆日志的功能，通过扫描识别错误日志内容，分析暴力破解IP地址后添加至防火墙。

### 请描述你建议的实现方案

通过正则匹配登陆日志中多次失败记录手动或者定时自动添加IP防火墙规则。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
最新版本已经支持 `工具箱` - `Fail2ban`，可自定义拦截规则等。
