### ISSUE TITLE
[BUG]安装部署 U用户管理验证系统，3个环境检测不通过。

### ISSUE THREAD

**Issue by laniv** [1Panel-dev/1Panel#1684]
### 联系方式

阿卡利

### 1Panel 版本

1.42

### 问题描述

安装 U用户管理验证系统，3个环境检测不通过。

PHP版本 --- 异常
MYSQL数据库 --- 异常
服务器系统 --- 异常

### 重现步骤

每次都出现。
开源地址：
http://user.uverif.com/
![2023-7-16 16-9-27](https://github.com/1Panel-dev/1Panel/assets/15064212/249eeb8b-3b9d-4f13-b14d-92dcd8b18ace)

### 期待的正确结果

这个问题，1.3已经有了，现在更新到1.42了，还是这样。
希望作者可以本地测试下，解决下这个问题。
想使用 1paner 来部署网站。

**Comment by zhengkunwang223** [comment]
用的什么版本的php 运行环境，需要的php插件分别是什么

**Comment by laniv** [comment]
> 

php 7.3.33
PHP扩展：pdo、mbstring、gd
mysql 5.7.42

**Comment by zhengkunwang223** [comment]
> > 
> 
> 
> 
> php 7.3.33
> 
> PHP扩展：pdo、mbstring、gd
> 
> mysql 5.7.42

好的我们试一下
