### ISSUE TITLE
[BUG]  OpenResty 异常停止后再容器中点击清理容器 OpenResty被清理后无法启动和重装

### ISSUE THREAD

**Issue by cktk** [1Panel-dev/1Panel#1687]
### 1Panel 版本

v1.4.2

### 问题描述

1  在OpenResty 提交一个错误的配置 使之停止运行

2 异常停止后再容器中点击清理容器 

3 去启动OpenResty 

4 结果 无法启动

5 去重新安装  结果无法安装

### 重现步骤

1  在OpenResty 提交一个错误的配置 使之停止运行

2 异常停止后再容器中点击清理容器 

3 去启动OpenResty 

4 结果 无法启动

5 去重新安装  结果无法安装

**Comment by cktk** [comment]
<img width="646" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/49108554/55711c69-31de-4fa1-81e4-f78c8fe02cad">

<img width="680" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/49108554/632098ce-0e22-4ef0-b1b5-49cf0a0c1434">

**Comment by cktk** [comment]
<img width="552" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/49108554/b084bf3b-5759-412a-a720-07178492cc92">
目前解决方法  在这个目录重新执行的docker-compose up -d

**Comment by wanghe-fit2cloud** [comment]
应用商店 - 已安装应用列表，点击 `重建`
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/7cd230c6-6f1d-480f-b5ff-b76efe04f0ee">
