### ISSUE TITLE
移动端文件列表UI异常

### ISSUE THREAD

**Issue by micro-CAO** [1Panel-dev/1Panel#1688]
### 1Panel 版本

1.4.2

### 问题描述

如图，在移动端访问文件管理，就发现由于每个文件(夹)后面的管理选项占了空间，文件(夹)名称无法被查看
![IMG_20230717_065451](https://github.com/1Panel-dev/1Panel/assets/70780880/77b6eeae-5a4f-4ea7-ac40-5dd4c3b9edee)

### 重现步骤

在移动端访问“文件”，（可能）因为字体调的大。竖屏切换横屏也不行

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
