### ISSUE TITLE
[FEATURE] 内置 OWASP 的规则集

### ISSUE THREAD

**Issue by cdnov** [1Panel-dev/1Panel#1692]
### 1Panel 版本

1

### 请描述您的需求或者改进建议

内置 OWASP 的规则集

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑是否支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
经团队内部讨论，我们暂无计划支持 ModSecurity OWASP 规则集，望理解。
