### ISSUE TITLE
[BUG]配置了跨域表示没有生效

### ISSUE THREAD

**Issue by LyingDoc** [1Panel-dev/1Panel#1699]
### 联系方式

1187691002@qq.com

### 1Panel 版本

v1.4.2

### 问题描述

1.![图片](https://github.com/1Panel-dev/1Panel/assets/131896721/cd6c59ca-75b0-4e88-81ae-535871798dad)
配置了跨域表示没有生效，修复下这个bug
2.
![图片](https://github.com/1Panel-dev/1Panel/assets/131896721/e5fd51cd-a1c5-489b-ad71-96c257cb3ca5)
修改配置包含目录直接报错，获取不到基本状态

### 重现步骤

![图片](https://github.com/1Panel-dev/1Panel/assets/131896721/03e3ce22-f1ec-450e-9a9b-d1f578064620)
浏览器结果

**Comment by zhengkunwang223** [comment]
1. 这个我们测试一下
2. 为什么要修改包含目录？

**Comment by LyingDoc** [comment]
还存在一个问题，就是你这个1panel部署到阿里云的centos strem 9出现拒绝访问的情况不管，前提我设置端口后，然后在阿里云控制台开放了端口，然后就是提示拒绝访问，还有Jenkins的主页提示，初始密码不在提示目录而是在apps/Jenkins里面，还有一个就是nginx那个代理工具可以修改搞成中文的，同时初始密码没有，可以开放可以查看密码设置密码的地方，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月17日(星期一) 晚上10:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [1Panel-dev/1Panel] [BUG] (Issue #1699)





  
这个我们测试一下
 
为什么要修改包含目录？

**Comment by wanghe-fit2cloud** [comment]
- 拒绝访问的情况有很多，比如开了安全端口、域名访问等，我们针对不同情况已经给出了具体命令

<img width="991" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/44eb2764-5166-4503-a389-199d8e175bd8">

> 上图为安全入口错误的情况，拒绝访问。
- Jenkins 等应用都是容器化部署，持久化目录就是应用的安装目录。具体的持久化目录设置可以参考 docker-compose.yml 配置文件。
