### ISSUE TITLE
一些问题和建议 [FEATURE] 

### ISSUE THREAD

**Issue by BleethNie** [1Panel-dev/1Panel#1700]
### 1Panel 版本

v1.4.2

### 请描述您的需求或者改进建议

试用后感觉很多功能使用不起来，以下是一些建议，不知是否有用，如果没用的话直接close这个issues就可以了：

- 应用商店不够开放，无法自定义自己的一些应用，很多想要的应用没有，毕竟官方的精力是有限的，官方添加应用会比较慢，比如运行环境，目前只有PHP的，但其实现在JAVA、Python、NodeJS、Golang等环境安装需求量非常大
- 网站建议可以添加第三方或者本服务器上的一些自定义网站，而不是通过OpenResty 代理的网站
- 运行环境目前仅支持PHP，希望可以扩大到别的环境
- 数据库仅能使用Docker中的数据库和Redis，不能使用本机自己安装的数据库，感觉限制较大
- 容器仅支持Docker，不支持podman,我本地只安装了podman，不想换Docker，如果是这种情况，这个软件基本没啥作用，因为大部分功能都依赖于Docker
- 计划任务，这个也依赖Dokcer,个人认为使用系统自带的crontab会比较好

**Comment by wanghe-fit2cloud** [comment]
麻烦讲一下你在使用过程中遇到的具体问题和建议，我们好在后续版本中优化、支持。

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈。
- 1Panel 是支持自定义应用的，具体教程参考：
  - [如何提交自己想要的应用](https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8)
  - [1Panel 本地应用创建技巧及第三方应用库举例](https://bbs.fit2cloud.com/t/topic/640/4)
- 后续版本我们会陆续支持添加 Java、Golang 等运行环境网站。
- 下个月功能版本我们就会支持添加远程 MySQL 数据库。
- 我们会在后续版本中讨论是否要支持 podman。
- 1Panel 的计划任务是基于 Golang 的定时任务。
