### ISSUE TITLE
[FEATURE]文件管理的一些易用性优化

### ISSUE THREAD

**Issue by auqhjjqdo** [1Panel-dev/1Panel#1701]
### 1Panel 版本

v1.4.2

### 请描述您的需求或者改进建议

1.文件夹优先显示
2.文件或文件夹收藏（快速访问）
3.支持右键显示文件操作菜单
4.保存上次访问位置，刷新网页后不会回到根目录
5.解压选择目录使用和复制粘贴相同的方式，直接在文件管理页面选择解压目录

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈，我们会在后续版本中持续优化。

**Comment by zyyfit** [comment]
1、2、4 已支持

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
