### ISSUE TITLE
[FEATURE]希望能提供docker仓库镜像安装

### ISSUE THREAD

**Issue by gettionhub** [1Panel-dev/1Panel#1702]
### 1Panel 版本

v1.4

### 请描述您的需求或者改进建议

希望能提供docker仓库镜像安装

**Comment by wanghe-fit2cloud** [comment]
请问上述需求是要支持容器化安装 1Panel 吗？

**Comment by gettionhub** [comment]
对，看到社区也有人提过这样的需求

**Comment by wanghe-fit2cloud** [comment]
中短期内我们还会使用二进制方式来部署 1Panel，望理解。
