### ISSUE TITLE
[FEATURE]计划任务建议

### ISSUE THREAD

**Issue by EicHub** [1Panel-dev/1Panel#1706]
### 1Panel 版本

1.4.2

### 请描述您的需求或者改进建议

需求：
计划任务选择日期时，没法选择在一周内指定日期执行
例：每周一至周五执行，周末不执行

### 请描述你建议的实现方案

建议：
计划任务选择每周执行时，可多选
选择每月执行时，可多选

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持上述需求。

**Comment by usjinbao** [comment]
计划任务哪里确实设计不合理

**Comment by wanghe-fit2cloud** [comment]
> 计划任务哪里确实设计不合理

麻烦明确说一下具体不合理的点，我们后续版本优化。

**Comment by wanghe-fit2cloud** [comment]
重复 #1727
