### ISSUE TITLE
【功能建议】网站目录可自定义和精简； 以及文件复制功能的

### ISSUE THREAD

**Issue by AlwaysOnline** [1Panel-dev/1Panel#1712]
### 1Panel 版本

1.4.2

### 请描述您的需求或者改进建议

目前，网站文件的目录过长。

（1）通过 openresty 创建的网站，目录是：
/opt/1panel/apps/openresty/1panel-openresty/www/sites/static.1panel.com

可借鉴宝塔的建站目录   根目录下的/www

（2）文件复制的功能。 如图
![image](https://github.com/1Panel-dev/1Panel/assets/3928525/147cd58e-a4b7-4aa6-a56c-f11b91388658)

### 请描述你建议的实现方案

无

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中持续优化。

**Comment by wanghe-fit2cloud** [comment]
文件复制等操作已优化。
网站目录问题重复 #2783
