### ISSUE TITLE
[FEATURE] 增量备份

### ISSUE THREAD

**Issue by cdnov** [1Panel-dev/1Panel#1714]
### 1Panel 版本

1

### 请描述您的需求或者改进建议

增量备份

**Comment by wanghe-fit2cloud** [comment]
上述需求是要实现增量备份 MySQL 数据库吗？

**Comment by cdnov** [comment]
主要是数据库

**Comment by cdnov** [comment]
> 需求需求是要实现增量备份MySQL数据库吗？

主要是数据库

**Comment by celizi** [comment]
数据库恢复要求：上传文件必须为 10M 以内？

**Comment by wanghe-fit2cloud** [comment]
> 数据库恢复要求：上传文件必须为 10M 以内？

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/e79038af-d695-4228-b087-390224dc9a07)

**Comment by celizi** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/27724598/8b3f8727-954f-41cb-abef-0f2f2c0740e0)
OK 文档更新问题

**Comment by maninhill** [comment]
请问这个问题有进展吗？

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is there any progress on this issue?

**Comment by wanghe-fit2cloud** [comment]
中短期内暂无计划支持 MySQL 增量备份功能，望理解。
