### ISSUE TITLE
[FEATURE]善用防火墙的端口组功能

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [1Panel-dev/1Panel#1715]
### 1Panel 版本

v1.4.3

### 请描述您的需求或者改进建议

在设置防火墙时，只能添加端口，而防火墙规则组可以简化安装部署应用的流程
安装应用->自动根据端口创建防火墙规则组->面板绑定该规则组->完成

### 请描述你建议的实现方案

安装应用->自动根据端口创建防火墙规则组->面板绑定该规则组->完成
firewalld的规则组可以直接利用服务实现。
ufw有类似firewalld的app，也可直接利用。
docker的端口zone在firewalld上是可以直接管理的，zone为docker

### 附加信息

类似于这个效果
![image](https://github.com/1Panel-dev/1Panel/assets/67987607/cc1bb7b1-a26f-4e00-b111-1e80cb5d926f)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中调研上述方案的具体实现。

**Comment by maninhill** [comment]
请问这个问题有进展吗？

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is there any progress on this issue?

**Comment by wanghe-fit2cloud** [comment]
中短期内暂无计划支持该功能，望理解。
