### ISSUE TITLE
服务器 IP 支持域名。

### ISSUE THREAD

**Issue by CMJNB** [1Panel-dev/1Panel#1716]
### 1Panel 版本

1.4.2

### 请描述您的需求或者改进建议

建议可以自定义“服务器ip”为域名，因为家庭公网ip会变动，所以在快捷打开应用地址时，如果可以使用域名就好了。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持 IP 和域名共存的方式。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
