### ISSUE TITLE
[FEATURE] 能否增加waf 验证码或cookie的方式 防御cc

### ISSUE THREAD

**Issue by fenglindubu** [1Panel-dev/1Panel#1717]
### 1Panel 版本

1.4.3

### 请描述您的需求或者改进建议

希望增加waf
防御CC：
1、验证码
2、cookie的方式 
3、屏蔽国外（可以使用ip库）

或者类似cf的五秒盾也可以

期待更新！

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持上述需求。

**Comment by maninhill** [comment]
未来通过集成第三方 WAF 解决。

**Comment by maninhill** [comment]
https://github.com/1Panel-dev/1Panel/issues/2009
