### ISSUE TITLE
[BUG]安装目录设置为 /，系统升级时报错

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1718]
### 1Panel 版本

v1.4.3

### 问题描述

安装目录设置为 /，系统升级时报错
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/958656ca-86a1-452e-b8d8-9bd502762701)

### 重现步骤

安装目录设置为 /，系统升级时报错

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
