### ISSUE TITLE
[FEATURE]希望1panel应用商店里增加 frp内网穿透的服务端和客户端

### ISSUE THREAD

**Issue by qq9688** [1Panel-dev/1Panel#1719]
### 1Panel 版本

1.4.3

### 请描述您的需求或者改进建议

希望1panel应用商店里增加 frp内网穿透的服务端和客户端
https://github.com/fatedier/frp/releases/

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持上述应用。

**Comment by wanghe-fit2cloud** [comment]
最新版本已支持上述应用

**Comment by vpertj** [comment]
应用商店版本没有frp 我更新商店了也没有 2.1.5  2.1.6  2.1.7 我的都没有

**Comment by wanghe-fit2cloud** [comment]
> 应用商店版本没有frp 我更新商店了也没有 2.1.5 2.1.6 2.1.7 我的都没有

你当前可能安装的是国际版本，该版本不包含 frp。
可以进入面板设置页面，修改面板的运行区域。

另外需要注意：
GitHub README 和 1panel.pro 提供的是国际版本安装脚本，而 1panel.cn 提供的是国内版本安装脚本。
