### ISSUE TITLE
[BUG] 在安装lskypro报错

### ISSUE THREAD

**Issue by fenglindubu** [1Panel-dev/1Panel#1720]
### 1Panel 版本

1.4.3

### 问题描述

 在安装lskypro报错，mysql已安装8.0.33

Dropping all tables ............................................... 7ms FAIL
Installation error!

SQLSTATE[HY000] [2002] Connection refused (SQL: SHOW FULL TABLES WHERE table_type = 'BASE TABLE')

### 重现步骤

从应用商店安装，直接使用端口访问，在安装的过程中报错，数据库已创建

**Comment by wanghe-fit2cloud** [comment]
数据库连接信息要使用容器地址，不能使用 127.0.0.1 或者 localhost，
如下图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/0be4a08b-2f6f-42f5-9dd6-9626200d53da)
