### ISSUE TITLE
[FEATURE]希望能增加ftp服务器

### ISSUE THREAD

**Issue by fenglindubu** [1Panel-dev/1Panel#1722]
### 1Panel 版本

1.4.3

### 请描述您的需求或者改进建议

希望能增加ftp服务器

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，近期版本就会支持。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布，ftp 教程请参考 [官方文档](https://1panel.cn/docs/user_manual/ftp/)
