### ISSUE TITLE
[FEATURE] 创建容器时允许用户手动输入未拉取的镜像

### ISSUE THREAD

**Issue by wojiushixiaobai** [1Panel-dev/1Panel#1723]
### 1Panel 版本

v1.4.3

### 请描述您的需求或者改进建议

当前创建容器必须要先手动拉取镜像，但是容器运行时不存在镜像会自动拉取。可以省去先拉取这个过程。

![image](https://github.com/1Panel-dev/1Panel/assets/24326988/73f674c1-4e4e-4f24-b801-14c38a681f43)

### 请描述你建议的实现方案

无

### 附加信息

无

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，当前版本是支持用户手动输入镜像名称的。

提示信息目前还有些问题，下个版本会优化。

**Comment by wendao8469759** [comment]
我当前v1.4.3 在镜像这里只能选择， 不能输入， 输入如：nginx:1.23.1 然后失去焦点后，就没了。 这个下拉列表只能选择。

我觉得可输入可可选择两个并行比较好。

**Comment by wanghe-fit2cloud** [comment]
> 我当前v1.4.3 在镜像这里只能选择， 不能输入， 输入如：nginx:1.23.1 然后失去焦点后，就没了。 这个下拉列表只能选择。
> 
> 我觉得可输入可可选择两个并行比较好。

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/633d4a8f-3631-4d39-bf85-b36ef4f44558)

**Comment by wendao8469759** [comment]
@wanghe-fit2cloud    我实际上想要的效果是， 当没有镜像是， 我在这里输入，可以自动拉去镜像。   跟一楼的想法一致

**Comment by wanghe-fit2cloud** [comment]
> @wanghe-fit2cloud 我实际上想要的效果是， 当没有镜像是， 我在这里输入，可以自动拉去镜像。 跟一楼的想法一致

直接输入选择即可。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
