### ISSUE TITLE
[FEATURE]支持域名跳转入口

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#1725]
### 1Panel 版本

1.4.3

### 请描述您的需求或者改进建议

在容器列表列表的端口列是否可以加已反代的域名跳转：
![图片](https://github.com/1Panel-dev/1Panel/assets/19621032/74f8ebb1-9d39-4ee2-8437-b034ee2ff7ae)
以及网站列表增加域名跳转入口

**Comment by wanghe-fit2cloud** [comment]
1、容器列表支持域名跳转的这个需求，建议是到网站页面内操作
> 如果是在容器列表支持，那还需要用户额外的配置，还是比较麻烦。

2、网站的跳转功能在网站设置 - 域名设置页面，如下图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/d7a212b4-fe9c-4d31-a02d-62f338e9c7ae)
