### ISSUE TITLE
[FEATURE]希望能够指定计划任务的多个固定时间

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1727]
### 1Panel 版本

v1.4.3

### 请描述您的需求或者改进建议

希望能够创建能够指定时间的计划任务，或者能够自己编写corn表达式也行，如图这种本可以通过一个计划就执行的，但我目前没有找到方式能够只创建一条计划任务。
![image](https://github.com/1Panel-dev/1Panel/assets/93708226/defd41ff-bce4-42c3-bb46-bc8c393293fe)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，在后续版本中，创建计划任务 - 选择执行周期时，支持多选就能满足上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
