### ISSUE TITLE
[FEATURE]将切换语言功能放到登录页面

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1728]
### 1Panel 版本

v1.4.3

### 请描述您的需求或者改进建议

希望将切换语言的功能放到登录页面
![image](https://github.com/1Panel-dev/1Panel/assets/93708226/702f8de0-b731-413d-955c-548909ecfdd0)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，下个版本（v1.5.0）将支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
