### ISSUE TITLE
[BUG]修改 docker-compose.yml 文件，导致应用异常

### ISSUE THREAD

**Issue by LyingDoc** [1Panel-dev/1Panel#1729]
### 联系方式

1187691002@qq.com

### 1Panel 版本

1.4.3

### 问题描述

![图片](https://github.com/1Panel-dev/1Panel/assets/131896721/6ce94a4a-2b29-4ca2-8f01-3b65c05da47a)
安装配置目录出错，红色方框修改之后就会报错获取不到状态，同理应该应用市场里面所以所软件安装目录都有问题映射问题，还有就是我修改这个文件，但配置文件include后面不生效，一改获取状态那个就要报错，参数也没同步
![图片](https://github.com/1Panel-dev/1Panel/assets/131896721/166508e1-f8d1-485b-b823-26b804ffcab8)
这是我执行看见跑的nginx不是安装的东西，但是同时目录不存在，很灵异事件，完全没报错

### 重现步骤

![图片](https://github.com/1Panel-dev/1Panel/assets/131896721/c990cfdf-34bc-4098-877a-b24d49f97abd)
这是改了文件之后的错误下成功了，状态报错，没改的话就报404页面，落款是nginx

**Comment by zhengkunwang223** [comment]
修改 docker-compose.yml 文件需要了解 Docker 容器的使用 和 1Panel 的基本实现，一般情况下不建议修改
容器安装openresty 和本地安装的 nginx  很有可能冲突
你是想实现什么呢？

**Comment by LyingDoc** [comment]
更新1.5版本并没有修复此问题，麻烦重视问题修复哦

**Comment by wanghe-fit2cloud** [comment]
> 更新1.5版本并没有修复此问题，麻烦重视问题修复哦

应用商店中提供的 docker-compose.yaml 是官方已经测试通过的配置。如要自行修改，就要确保单独执行 `docker-compose up` 命令能正常运行。
