### ISSUE TITLE
[QUESTION]创建容器报错

### ISSUE THREAD

**Issue by oneszsm** [1Panel-dev/1Panel#1733]
### 请描述您的问题

为什么在创建容器时，容器一直在重启，容器创建不成功，换了好几个系统，一直这样，但是在终端命令创建容器就没什么问题。只有我是这样的吗？镜象没问题，用的刚拉取下来的ubuntu都不行，商店应用可以正常安装。
![image](https://github.com/1Panel-dev/1Panel/assets/65348566/fcc52856-4587-4ffd-99aa-0d9c96b64db2)

**Comment by wanghe-fit2cloud** [comment]
可以先查看一下容器日志。
