### ISSUE TITLE
[FEATURE] 请在数据库管理页面增加 PostgreSQL 数据库 和 MariaDB 数据库的管理，谢谢！

### ISSUE THREAD

**Issue by eulermath066** [1Panel-dev/1Panel#1734]
### 1Panel 版本

v1.4.3

### 请描述您的需求或者改进建议

在数据库管理页面增加 PostgreSQL 数据库 和 MariaDB 数据库的管理，谢谢！

### 请描述你建议的实现方案

请在数据库管理页面增加 PostgreSQL 数据库 和 MariaDB 数据库的管理，谢谢！

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本会优先支持 MariaDB 数据库。
> PostgreSQL 也会在近期版本支持。
