### ISSUE TITLE
[FEATURE]期望防火墙能出个功能，限制、禁默或者拒绝来自某一区域或者某些区域的请求

### ISSUE THREAD

**Issue by swRains** [1Panel-dev/1Panel#1737]
### 1Panel 版本

v1.4.3

### 请描述您的需求或者改进建议

期望防火墙能出个功能，限制、禁默或者拒绝来自某一区域或者某些区域的请求，因为有很多网络攻击来自国外，我期望能够将这些国外的请求直接忽略。不仅仅是安装的软件，向docker的请求也拒绝。类似于cdn里的仅限大陆访问。因为防火墙难以直接根据GeoIP一次性导入这么多国外或者国内ip。
公开的ip划分表应该是足够用的，包括ipv4和ipv6
期望开发者能够考虑我的建议。实在不行我就只能在外面再套一层实体防火墙了。但云服务器难以做这样的功能。

### 请描述你建议的实现方案
https://github.com/iiiiiii1/Block-IPs-from-countries
这个项目可能有类似的功能，期望能有所能帮助
_No response_

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
