### ISSUE TITLE
应用商店中mysql导出备份后，导入到其他服务器上的mysql，数据库丢失[BUG]

### ISSUE THREAD

**Issue by JinLiGame** [1Panel-dev/1Panel#1738]
### 联系方式

553555614@qq.com

### 1Panel 版本

1.4.3

### 问题描述

我想要将一个服务器的mysql迁移到另一个服务器上，在应用商店里mysql导出备份后，将备份文件再导入另一个服务器的mysql中，数据库丢失了

### 重现步骤

我想要将一个服务器的mysql迁移到另一个服务器上，在应用商店里mysql导出备份后，将备份文件再导入另一个服务器的mysql中，数据库丢失了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
1、A 系统：已安装应用列表 - 备份 MySQL 应用 - 下载备份文件
2、B 系统：上传备份文件 - 恢复
3、操作成功

数据丢失，是指 A 系统数据库列表中的数据在 B 系统没有显示吗？

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布，该版本针对应用备份恢复逻辑进行了优化。
可以将系统升级到最新版本。
