### ISSUE TITLE
[FEATURE]能否增加支持Litespeed？

### ISSUE THREAD

**Issue by franklight** [1Panel-dev/1Panel#1739]
### 1Panel 版本

1.4

### 请描述您的需求或者改进建议

做的站点全部都是WordPress，实测下来，Litespeed对WordPress的支持最好

### 请描述你建议的实现方案

支持Litespeed，这样把生成环境切换过来就很踏实了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
