### ISSUE TITLE
[BUG]1panel占用内存很高，是目前用过的面板中占用最高的

### ISSUE THREAD

**Issue by franklight** [1Panel-dev/1Panel#1740]
### 1Panel 版本

1.4

### 问题描述

内存占用很高——在同一个服务器，新安装的情况下。比较小众的面板就不提了，主要是比较宝塔和AMH这种常见的面板。

### 重现步骤

专门做了测试，在同一个机器上，1panel的占用是宝塔、AMH的2.5倍，希望能优化一下。（1panel没有安装其他任何东西，就是默认安装完毕，反倒是AMH还安装了7个面板插件来查看占用情况）

**Comment by wanghe-fit2cloud** [comment]
感谢反馈

- 当前版本 1Panel 主程序占用服务器内存不到两百兆，在这一点上我们还会持续优化。
- 1Panel 是基于容器来部署、管理应用，对宿主机影响小，安全性高。当然，在性能上势必会有所牺牲，对于 1C1G 这类的小机器压力会比较大。
