### ISSUE TITLE
[BUG]OneDrive授权的时候重定向的地址是localhost

### ISSUE THREAD

**Issue by springeye** [1Panel-dev/1Panel#1741]
### 1Panel 版本

1.4.3

### 问题描述

授权成功的时候重定向的地址现在是localhost，应该是1panel的访问地址才对

现在跳转的是这里
<img width="499" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/1314740/df4b0778-c422-4a38-a59e-8ca39318fe09">

### 重现步骤

直接按照界面点击获取code就行

### 期待的正确结果

应该跳转到这里
<img width="536" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/1314740/e6085b6f-0909-4726-bf48-f4f708408741">

**Comment by ssongliu** [comment]
感谢反馈！这里只要关心 code 后面那串就行，localhost 只是一个重定向的地址。

**Comment by kindomLee** [comment]
這不是還沒修正的 bug 嗎，為什麼 close 了？

**Comment by zuilintan** [comment]
> 這不是還沒修正的 bug 嗎，為什麼 close 了？

这并非问题
