### ISSUE TITLE
[BUG]升级alist 失败， 显示超时

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1742]
### 1Panel 版本

v1.4.3

### 问题描述

应用商店中点击升级，一段时间(可能30s 或 60s) 显示请求超时。
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/48650b75-7fc7-49b2-b2b4-95afbbbdef99)

### 重现步骤

我的alist里面放的我常用的东西，内容大概有15G左右。
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/6218a4f0-7c7b-4bfd-ae38-f506c8bdce44)

![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/eabb7e16-eec1-4176-908d-f1c0b46d8b87)

### 期待的正确结果

升级成功。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述问题应该是持久化数据过大而导致的应用备份超时（现在是默认升级之前先备份一次，用于升级失败之后回滚）。

下个版本会针对上述问题进行优化。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
