### ISSUE TITLE
[BUG] 监控日志选择近30天，但开始日期是本月1号

### ISSUE THREAD

**Issue by icpd** [1Panel-dev/1Panel#1743]
### 1Panel 版本

v1.4.3

### 问题描述

如题，并且纵轴值显示有问题

![image](https://github.com/1Panel-dev/1Panel/assets/35096485/accfb077-c85b-42ec-9716-bf34b438a9d0)

### 重现步骤

选择时间近30天

**Comment by wanghe-fit2cloud** [comment]
感谢反馈
1、纵坐标显示问题我们在上个版本进行了优化（可以将 1Panel 更新到最新版本，如果还存在上述问题应该是遗留数据的问题）
2、横坐标日期问题，我刚才在本地环境没有复现，如下图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/849841f4-4e9c-4327-82ba-e48c216d6abe)

**Comment by ghost** [comment]
全局过滤下拉框选择近一个月
1、磁盘和网络 IO 两个图表显示异常（横坐标日期不对）
2、系统报错：请求超时
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/e53b285a-0ea2-40cc-b0df-36c0311a3e12)

**Comment by wanghe-fit2cloud** [comment]
> 全局过滤下拉框选择近一个月 1、磁盘和网络 IO 两个图表显示异常（横坐标日期不对） 2、系统报错：请求超时 ![图片](https://user-images.githubusercontent.com/29944886/255519286-e53b285a-0ea2-40cc-b0df-36c0311a3e12.png)

可能是由于数据量大导致的接口请求超时，我们在下个版本会做出优化。

**Comment by icpd** [comment]
> 感谢反馈 1、纵坐标显示问题我们在上个版本进行了优化（可以将 1Panel 更新到最新版本，如果还存在上述问题应该是遗留数据的问题） 2、横坐标日期问题，我刚才在本地环境没有复现，如下图： ![image](https://user-images.githubusercontent.com/46734380/255518448-849841f4-4e9c-4327-82ba-e48c216d6abe.png)

是因为我没有7月之前的数据导致的吗？不过我不记得是什么时候安装的面板

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
