### ISSUE TITLE
服务器部署遭暴力破解

### ISSUE THREAD

**Issue by Cloak520** [1Panel-dev/1Panel#1746]
### 1Panel 版本

V1.4.3

### 问题描述

![1690195368663](https://github.com/1Panel-dev/1Panel/assets/8164799/0d366cea-ad7d-4883-9473-4d78f01e8239)

服务器部署遭暴力破解

### 重现步骤

无

**Comment by zhengkunwang223** [comment]
暴力破解 跟 1Panel 无关
1Panel 只是读取了 Linux 机器的 SSH 登录日志

**Comment by wanghe-fit2cloud** [comment]
可以尝试如下安全措施：

1、更换默认的 22 端口；
2、禁止 root 账号；
3、高强度密码；
4、禁止 ping；
5、尝试登录次数限制；
6、生成密钥对；
7、限制登录 ssh 的 ip。

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/5f7bb68c-7673-48b9-a946-ae9ae8432491)

**Comment by Cloak520** [comment]
好的，我加一下配置
