### ISSUE TITLE
[FEATURE] 期望增加对MongoDB数据库的管理

### ISSUE THREAD

**Issue by xiaolongyuan** [1Panel-dev/1Panel#1747]
### 1Panel 版本

1.4.2

### 请描述您的需求或者改进建议

增加对mongodb数据库的管理，包含：

- 数据库创建、删除、备份、恢复
- 数据库用户创建、删除

### 请描述你建议的实现方案

应该可以使用mongodb golang 驱动库实现

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈，上述需求我们会在后续版本中支持。

**Comment by wanghe-fit2cloud** [comment]
重复 #399
