### ISSUE TITLE
[FEATURE]Jenkins 访问宿主机 docker 配置提取为变量

### ISSUE THREAD

**Issue by wwtao1024** [1Panel-dev/1Panel#1749]
### 1Panel 版本

1.4.3

### 请描述您的需求或者改进建议

Jenkins访问宿主机docker配置错误
Jenkins默认时区配置

编排文件默认为：
- /usr/local/bin/docker:/usr/local/bin/docker
实则应该为：
-v /usr/bin/docker:/usr/bin/docker

### 请描述你建议的实现方案

环境变量添加：
TZ=Asia/Shanghai

挂载目录配置：
-v /etc/docker/daemon.json:/etc/docker/daemon.json
-v /usr/bin/docker:/usr/bin/docker

**Comment by wanghe-fit2cloud** [comment]
- 这里是为了在 Jenkins 容器能调用宿主机的 docker 所做的映射。
目录可能是 `/usr/bin/docker`，也有可能是 `/usr/local/bin/docker`。

- 当前版本可以先手动修改 compose 文件，后续版本会将其提取为变量。

**Comment by wwtao1024** [comment]
时区还有docker配置文件的可以提前放进去，另外构建多架构的有办法吗

**Comment by wwtao1024** [comment]
docker buildx build 相关的知识

**Comment by wanghe-fit2cloud** [comment]
> 时区还有docker配置文件的可以提前放进去，另外构建多架构的有办法吗

编辑 compose 文件这个功能开放出来，就是为了用户自定义（不能直接添加 TZ 来指定具体时区）。

**Comment by wanghe-fit2cloud** [comment]
> docker buildx build 相关的知识

中短期内暂无计划支持。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
