### ISSUE TITLE
[BUG] 商店中的 rusudesk 服务安装后无法启动

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#1751]
### 1Panel 版本

1.4.3

### 问题描述

使用商店中的 rusudesk 服务安装后无法启动，商店中使用 rustdesk 官方的 docker 镜像启动有问题，换做 `thtom/rustdesk-server:latest` 则是正常的
<img width="1115" alt="图片" src="https://github.com/1Panel-dev/1Panel/assets/15864713/b4e6c704-0b84-43a4-b89a-c7cb3662722e">

### 重现步骤

商店中安装 rusudesk

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我在本地环境没有复现上述问题，你可以先对比一下镜像 ID 是否一致。
<img width="1431" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/10351a99-a6c4-4553-a27e-840965881196">

**Comment by mx2913** [comment]
看了，镜像 ID 是不一致的，可能是我服务器上缓存的镜像标签也是 latest 导致的
不过刚刚发现 restdesk 发了一个新的 rustdesk-server-s6 镜像，这个镜像只需要运行一个容器就够了，感觉还是挺不错的
https://github.com/rustdesk/rustdesk-server#s6-overlay-based-images 可以考虑放进来

**Comment by wanghe-fit2cloud** [comment]
> 看了，镜像 ID 是不一致的，可能是我服务器上缓存的镜像标签也是 latest 导致的 不过刚刚发现 restdesk 发了一个新的 rustdesk-server-s6 镜像，这个镜像只需要运行一个容器就够了，感觉还是挺不错的 https://github.com/rustdesk/rustdesk-server#s6-overlay-based-images 可以考虑放进来

收到。

**Comment by mx2913** [comment]
这个是运行的效果
![图片](https://github.com/1Panel-dev/1Panel/assets/15864713/0cf35f78-a45d-4b8d-80b7-98ef4f5b1aa4)
![图片](https://github.com/1Panel-dev/1Panel/assets/15864713/b3cbb2f9-33b0-4e8c-9c57-8c27d36496d5)
