### ISSUE TITLE
服务内部错误[BUG]

### ISSUE THREAD

**Issue by yuanmu0814** [1Panel-dev/1Panel#1755]
### 联系方式

yuanmu_email@qq.com

### 1Panel 版本

v1.4.3

### 问题描述

全新系统（Debian-12.1）安装1panel后，已安装OpenResty，创建网站时报错“服务内部错误：”，具体什么错误未指明。我目前也没有发现有更详细的报错日志。日志审计中也无法显示更详细的报错。

### 重现步骤

创建网站

**Comment by zhengkunwang223** [comment]
创建的是什么类型的网站？

**Comment by yuanmu0814** [comment]
与创建的网站类别无关，四个选项均尝试过，都失败。

**Comment by yuanmu0814** [comment]
如果有日志或者报错倒可以分析分析，但是我并没有发现日志。

**Comment by zhengkunwang223** [comment]
看一下Openresty状态是否正常

**Comment by yuanmu0814** [comment]
应该正常，日志没有任何报错。

**Comment by johnnyzheng99** [comment]
手工修改网站nginx配置添加lua filter会造成这个问题。这时候无论保存什么都是，服务内部错误。nginx配置验证没问题运行正常。但是从此网站配置再也无法在ui上保存。重启openresty、网站均无效果。
