### ISSUE TITLE
[QUESTION] nextcloud 需要执行服务器本地执行cron.php

### ISSUE THREAD

**Issue by QingmingZi** [1Panel-dev/1Panel#1757]
### 请描述您的问题

# nextcloud 需要执行服务器本地执行cron.php

但是用了“网站”发现结构有点特殊，不知道怎么处理
需要用定时任务执行类似这样的脚本，nextcloud  是容器名，替换了想的2个都不行
```
#！/bin/bash
docker exec --user www-data nextcloud  php /var/www/html/cron.php
```
但是用网站自己的容器或者php环境的容器都不行，这个怎么解决？
还是说只能放弃“网站”，自己使用独立的docker？

**Comment by wanghe-fit2cloud** [comment]
1、如果是定时执行，可以创建计划任务，选择容器后直接输入要执行的 php 等命令即可：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/4d4d9a25-c6bb-4228-aecd-b324936db62c)
2、到容器列表，点击进入终端执行：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/60623134-365c-4c5d-adad-6102aec4f36c)

**Comment by QingmingZi** [comment]
哦，解决了，原来是要/bin/sh
```
#！/bin/sh
docker exec --user www-data 1Panel-php8-k8pS php --define apc.enable_cli=1 /www/sites/nextcloud.qmworld.top/index/cron.php
```
这样就搞定了
