### ISSUE TITLE
[BUG]运行环境配置了imagick扩展，但是PHPinfo却看不到

### ISSUE THREAD

**Issue by QingmingZi** [1Panel-dev/1Panel#1758]
### 1Panel 版本

当前运行版本：v1.4.3

### 问题描述

配置运行环境配置了imagick扩展，但是PHPinfo却看不到

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/12634683/06ac8ff1-8245-4cf4-be87-d49afa23528a)
![image](https://github.com/1Panel-dev/1Panel/assets/12634683/95dbe877-2033-41ad-808d-9b95af72f629)

**Comment by zhengkunwang223** [comment]
重建应用了吗？
进入 PHP 容器 执行 php -m 命令查看是否安装

**Comment by QingmingZi** [comment]
重建过的，其他扩展都是加了就好了，就这个扩展不行
你们的环境容器好像没法用 /bin/bash进入

**Comment by QingmingZi** [comment]
哦解决了，原来要/bin/sh才行
```
#！/bin/sh
docker exec --user www-data 1Panel-php8-k8pS php --define apc.enable_cli=1 /www/sites/nextcloud.qmworld.top/index/cron.php
```
这样就搞定了

**Comment by QingmingZi** [comment]
哦，贴错了问题了

**Comment by QingmingZi** [comment]
重建过的，其他扩展都是加了就好了，就这个扩展不行
你们的环境容器好像没法用 /bin/bash进入
关闭错了咋办 o(╥﹏╥)o

**Comment by zhengkunwang223** [comment]
> 重建过的，其他扩展都是加了就好了，就这个扩展不行 你们的环境容器好像没法用 /bin/bash进入 关闭错了咋办 o(╥﹏╥)o

可以使用 /bin/sh 进入

**Comment by cyril-cheng** [comment]
> 重建应用了吗？ 进入 PHP 容器 执行 php -m 命令查看是否安装

好像确实php8.2.5不显示imagick，下面是我现创建的镜像
![image](https://github.com/1Panel-dev/1Panel/assets/49748357/142e8170-6316-408e-811f-b0ae560e75a4)
![image](https://github.com/1Panel-dev/1Panel/assets/49748357/02306aab-e169-4d10-94a4-dee8d9f6bc5e)
下面是7.4.33的，就是正常的
![image](https://github.com/1Panel-dev/1Panel/assets/49748357/25798a51-73a4-42f5-ba07-a5f159d80248)
![image](https://github.com/1Panel-dev/1Panel/assets/49748357/7162d4cb-ccce-40e1-bc78-aa86d0da2223)
![image](https://github.com/1Panel-dev/1Panel/assets/49748357/1edf9dc5-1a06-4971-9747-517ccecb81ae)

**Comment by QingmingZi** [comment]
嗯，我的nextcloud 27.0.1要求PHP8的，没法用PHP7
那么难道确实是个bug？
重建应用肯定知道了，我一共有10多个扩展，就这一个配置了有问题，其他扩展都可以。

**Comment by QingmingZi** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/12634683/34953a4e-c9b0-4c7e-a16a-49a23fafcaf4)
我还特别重新选了一遍这个扩展，确实不行
```
/www # php -m
[PHP Modules]
apcu
bcmath
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gmp
hash
iconv
intl
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
random
readline
redis
Reflection
session
SimpleXML
sodium
SPL
sqlite3
standard
sysvsem
tokenizer
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by cyril-cheng** [comment]
> Author

找到问题了 
![image](https://github.com/1Panel-dev/1Panel/assets/49748357/740c37d0-538a-40e6-97c7-e7aca521fc08)
php8.2.5的镜像没有phpize，换php8.1吧

**Comment by QingmingZi** [comment]
测试了使用8.1.18确实解决了问题
