### ISSUE TITLE
rabbitmq 应用商店状态与容器状态不符

### ISSUE THREAD

**Issue by wendao8469759** [1Panel-dev/1Panel#1759]
### 联系方式

942837091@qq.com

### 1Panel 版本

1.4.3

### 问题描述

rabbitmq 通过1Panel应用商店安装，安装后发现容器并没有启动， 但是应用商店中显示已启动
![image](https://github.com/1Panel-dev/1Panel/assets/32348566/b6386c7b-2a77-4730-a1bd-4f4efbc41290)

手动在容器中启动rabbitmq的容器后，可以正常访问，  

当我重启服务器时，发现，应用商店中再次显示的是已启动， 但是容器管理中显示的未启动，  通过容器管理重启容器后正常。

我在容器编辑后发现  应该是容器重启规则这里的问题。
![image](https://github.com/1Panel-dev/1Panel/assets/32348566/adf1882d-de36-4924-b478-101c15e7197b)

### 重现步骤

重启服务器时 发现rabbitmq不能启动

### 期待的正确结果

rabbitmq可以随着开机启动

**Comment by wanghe-fit2cloud** [comment]
1、已安装应用提供了同步按钮，可以同步应用状态
2、重启服务器后应用没有自动重启，是容器重启规则没有设置为 Always，后续版本会优化。

**Comment by wendao8469759** [comment]
好的

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
