### ISSUE TITLE
[BUG]Jenkins，docker映射失败

### ISSUE THREAD

**Issue by xkloveme** [1Panel-dev/1Panel#1760]
### 联系方式

xkloveme@gmail.com

### 1Panel 版本

v1.4.3

### 问题描述

Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-78-generic x86_64)

1. 在上述版本中，安装Jenkins，docker映射失败
2. 进入容器报如下错误：
` docker -v
docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by docker)
docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by docker)`

### 重现步骤

1. 

### 期待的正确结果

Docker version 24.0.5, build ced0996

### 相关日志输出

```shell
docker -v
docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by docker)
docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by docker)
```

**Comment by wanghe-fit2cloud** [comment]
1、在宿主机执行命令查看 docker 目录：
```shell
which docker
```
2、应用商店安装 Jenkins，选择高级设置 - 编辑 compose 文件，手动修改 volume 文件路径（和上面命令查询结果保持一致）：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/02798a89-86ea-4977-88a6-f91de4c27e0e)


下个版本我们将该配置提取为变量。

**Comment by xkloveme** [comment]
你好，好像并不生效，并不是docker路径的问题，
如果没有链接到宿主机docker会提示
```
docker -v
bash: /usr/bin/docker: No such file or directory
```
并不是
```
docker -v
docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by docker)
docker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by docker)
```
在Ubuntu 20.04.2 他是生效的可以链接docker，在Ubuntu 22.04.2 LTS，会报上面的错误，我尝试将docker降级，也并没有效果

**Comment by xkloveme** [comment]
可能是Ubuntu 22.04.2 LTS 升级了libc的库造成的

**Comment by SkyAerope** [comment]
应该是宿主机依赖的问题，跟Jenkins关系不大。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
