### ISSUE TITLE
[FEATURE] PHP安装扩展优化

### ISSUE THREAD

**Issue by Daiyangcheng** [1Panel-dev/1Panel#1762]
### 1Panel 版本

1.4.3

### 请描述您的需求或者改进建议

加入引入自定义PHP扩展的功能，有些php扩展并没有在1panel中提供，希望可以增加用户自主上传扩展的功能（.so 文件）

顺便吐槽一下新建运行环境特别玄学，有时候半天都构建不好，希望优化

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本会考虑支持用户自主上传扩展的功能。

创建运行环境慢大概率是网络问题（容器内需要在线获取、安装依赖）

**Comment by zhengkunwang223** [comment]
https://bbs.fit2cloud.com/t/topic/2073  可以参考这个配置自定义 .so 文件

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
