### ISSUE TITLE
[QUESTION]反向代理如何配置WebSocket

### ISSUE THREAD

**Issue by smilecat2788** [1Panel-dev/1Panel#1763]
### 请描述您的问题

![image](https://github.com/1Panel-dev/1Panel/assets/109615952/6044fd41-2210-4e8e-a746-a67024f17d6c)
反向代理后网站报错
DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

**Comment by zhengkunwang223** [comment]
贴一下你的配置文件

**Comment by smilecat2788** [comment]
谢谢，我已经解决了

**Comment by ghost** [comment]
> 谢谢，我已经解决了

铁子，方便贴一下解决方案吗？

**Comment by smilecat2788** [comment]
其实他默认就支持websocket，是我自己搭建的网站不支持wss，我后来和网站作者说让他添加了wss支持
