### ISSUE TITLE
[FEATURE]希望可以保存一下每个页面的状态

### ISSUE THREAD

**Issue by StarsAaron** [1Panel-dev/1Panel#1765]
### 1Panel 版本

1.4.3

### 请描述您的需求或者改进建议

希望可以保存一下每个页面的状态，不用每次跳转之后都要重新点击，例如：分页数量，当前选择的商店标签

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑是否支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
