### ISSUE TITLE
[BUG] 切换时区时执行计划任务可能出现的上一次执行时间无法更新

### ISSUE THREAD

**Issue by allyxmiko** [1Panel-dev/1Panel#1768]
### 联系方式

1713069822@qq.com

### 1Panel 版本

v1.4.3

### 问题描述

在系统切换时区后，再次执行计划任务可能导致上次执行时间不能正确更新，发现的规律如下：
- 当第一次执行计划任务的系统时区为UTC，第二次执行计划任务为Asia/Shanghai时，程序会更新上次执行时间
![072707473429_0Snipaste_2023-07-27_07-23-58](https://github.com/1Panel-dev/1Panel/assets/53589496/38565ed2-0a99-4739-b731-773dfe8f61fc)
- 当第一次执行计划任务的系统时区为Asia/Shanghai，第二次执行计划任务的时区为UTC时，程序不会更新上次执行时间，但是实际上计划任务可以执行，并且报告也可以显示记录
![072707582086_0Snipaste_2023-07-27_07-55-39](https://github.com/1Panel-dev/1Panel/assets/53589496/11147972-1670-4790-b735-40dde0c3f87b)

总结：只有切换的时区后显示的时间早于之前时区显示的时间才不会更新
临时解决方法：清空任务执行记录

### 重现步骤

1. 设置系统时区为Asia/Shanghai
2. 进入计划任务并执行计划任务
3. 切换时区为UTC
4. 再次执行计划任务
5. 发现上次执行时间并不会更新

### 期待的正确结果

根据不同时区的时间做出正确的转换

**Comment by wanghe-fit2cloud** [comment]
计划任务执行时间是记录数据库的，手动修改服务器时区后并不会修改数据库记录。
