### ISSUE TITLE
內網環境部署1panel之後，面板能否增加代理上網功能

### ISSUE THREAD

**Issue by faxx11** [1Panel-dev/1Panel#1769]
### 1Panel 版本

v1.4.3

### 请描述您的需求或者改进建议

內網環境部署1panel，因無法直連外網，需要走代理才行，應用商店等多功能無法使用，嘗試設置系統代理，無效，可否在面板處新增代理功能

### 请描述你建议的实现方案

內網環境部署1panel，因無法直連外網，需要走代理才行，應用商店等多功能無法使用，嘗試設置系統代理，無效，可否在面板處新增代理功能

**Comment by wanghe-fit2cloud** [comment]
感謝反饋，我們會在後續版本考慮支持上述需求。

**Comment by okxlin** [comment]
来试试`v2rayA`

[1panel第三方应用库](https://github.com/okxlin/appstore)
