### ISSUE TITLE
[FEATURE]删除应用的优化

### ISSUE THREAD

**Issue by pengcheng820** [1Panel-dev/1Panel#1771]
### 1Panel 版本

v1.4.3

### 请描述您的需求或者改进建议

在应用商店安装的应用，删除后，镜像和app目录下的应用数据依然存在。删除后再次重装，不是点击重建，会提示端口冲突

### 请描述你建议的实现方案

建议优化下，删除应用可以同步镜像和删除app目录下的应用数据，也麻烦请检查下再次安装造成端口冲突的原因

**Comment by wanghe-fit2cloud** [comment]
1、删除应用，会自动删除 `/安装目录/1panel/apps/应用类别/` 目录下的应用文件夹。
2、删除应用，不会去自动删除镜像（可以到 `容器菜单 - 镜像列表`，点击清理镜像按钮）。
3、端口冲突，可以先确认一下具体的端口占用情况
```shell
netstat -ntlp
```

**Comment by pengcheng820** [comment]
但是实际使用，发现删除应用后，没有自己删除目录下的应用文件夹
发现没删后 ，都是手动去删除的
![image](https://github.com/1Panel-dev/1Panel/assets/12994898/c40f22e6-8f5e-49ad-b5e9-79d79c010327)

**Comment by wanghe-fit2cloud** [comment]
apps 目录下是应用类别目录，不会删除（原因是有些应用支持安装多个）。
1Panel 删除的是类别目录下的应用目录。
