### ISSUE TITLE
mkdir /opt/1panel: read-only file system

### ISSUE THREAD

**Issue by St-ZFeng** [1Panel-dev/1Panel#1779]
### 请描述您的问题

![image](https://github.com/1Panel-dev/1Panel/assets/113660099/0a213fd5-862d-46f8-a142-0eafea2715f2)
啥情况？整了快一下午，迷惑了

**Comment by cyril-cheng** [comment]
mkdir /opt/1panel: read-only file system

**Comment by cyril-cheng** [comment]
翻译一下

**Comment by St-ZFeng** [comment]
> mkdir /opt/1panel: read-only file system

问题解决了，我的docker是很早以前安装的，里面好像都是只读的，卸了用面板自带的安装方法就能用了
