### ISSUE TITLE
[BUG] docker编辑时挂载卷没有正确识别

### ISSUE THREAD

**Issue by g-mero** [1Panel-dev/1Panel#1781]
### 1Panel 版本

1.4.3

### 问题描述

在终端允许docker run ... -v /path/to:/opt/test ... 运行成功后，在管理页面查看配置是成功挂载了的，但是点击编辑是看不到挂载卷的。这导致，如果你编辑时不重新挂载目录，原先挂载的目录就取消挂载了，在编辑界面挂载之后，编辑界面就有挂载信息了。也就是说如果你是在终端运行时挂载的，编辑界面是看不到挂载卷的。
![20230728020652](https://github.com/1Panel-dev/1Panel/assets/62990607/428e1098-3a67-48a6-a53e-18e3fb59f96e)
![20230728020708](https://github.com/1Panel-dev/1Panel/assets/62990607/77c4725f-06a9-41e1-b17a-0e20b99d3e85)

### 重现步骤

在终端docker run一个有挂载卷的容器

在1panel的容器管理页面点击编辑容器，看不到挂载卷

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下问题。

**Comment by zyyfit** [comment]
1.5.0 版本修复了这个问题，请等待版本发布后验证

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布
