### ISSUE TITLE
[BUG] 安装PHP v8运行环境时 出现 http: invalid Host header

### ISSUE THREAD

**Issue by xiaolongyuan** [1Panel-dev/1Panel#1782]
### 1Panel 版本

1.4.3

### 问题描述

安装 PHP v8 ，其他都是默认选项

### 重现步骤

安装 PHP v8 ，其他都是默认选项

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/3142363/8b3fd99a-3c03-4597-bdaa-ba17a2722e0f)

![image](https://github.com/1Panel-dev/1Panel/assets/3142363/3a1674b1-b1f0-4084-8d5b-e73b28b947b7)

**Comment by xiaolongyuan** [comment]
手动执行构建OK的

![image](https://github.com/1Panel-dev/1Panel/assets/3142363/1d11a308-33d1-441d-94a2-36e9e25b0582)

**Comment by zhengkunwang223** [comment]
网络相关的 检查一下自己的网络环境
然后进入方法里面打断点看一下

**Comment by xiaolongyuan** [comment]
[root@localhost ~]# docker-compose version
Docker Compose version v2.20.0
[root@localhost ~]# docker version
Client: Docker Engine - Community
 Version:           24.0.4
 API version:       1.43
 Go version:        go1.20.5
 Git commit:        3713ee1
 Built:             Fri Jul  7 14:52:00 2023
 OS/Arch:           linux/amd64
 Context:           default

**Comment by xiaolongyuan** [comment]
> 网络相关的 检查一下自己的网络环境 然后进入方法里面打断点看一下

@zhengkunwang223 

用1panel的参数手动在机器 执行 docker-compose build 是可以正确构建出镜像的 

用断点调试追到 compose 包

![image](https://github.com/1Panel-dev/1Panel/assets/3142363/29cf2208-6ddd-4a86-a583-4403cff0edaf)

这个步骤出现异常

**Comment by xiaolongyuan** [comment]
@zhengkunwang223 @wanghe-fit2cloud 

兄弟 这应该真的是个 bug 跟go编译环境有关

见：

https://github.com/moby/moby/pull/45962

https://github.com/moby/moby/pull/45990

**Comment by xiaolongyuan** [comment]
The Go client now avoids using UNIX socket paths in the HTTP Host: header, in order to be compatible with changes introduced in go1.20.6. https://github.com/moby/moby/pull/45962, https://github.com/moby/moby/pull/45990

https://github.com/moby/moby/releases/tag/v24.0.5

这个版本的更新说明

**Comment by zhengkunwang223** [comment]
> 

看起来是 go 版本的问题 我们用的 go 1.19

**Comment by xiaolongyuan** [comment]
> > 
> 
> 看起来是 go 版本的问题 我们用的 go 1.19

较新的1.19 就存在这个问题 例如1.19.11

**Comment by xiaolongyuan** [comment]
1.19.10 测试正常 @zhengkunwang223
