### ISSUE TITLE
[BUG]ssh 管理中的登录日志排序问题

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1784]
### 1Panel 版本

v1.4.3

### 问题描述

感觉排序规则是先显示失败的，然后才是按照时间进行排序。
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/3f450a96-0b75-4613-af81-d6aaa424bae7)

### 重现步骤

日志审计 - SSH 登录日志

### 期待的正确结果

按照时间排序，不区分失败和成功记录

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本优化 SSH 登录日志的显示问题。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
