### ISSUE TITLE
[FEATURE]计划任务-任务类型，新增“备份应用”

### ISSUE THREAD

**Issue by so-colorful** [1Panel-dev/1Panel#1788]
### 1Panel 版本

1.4.3

### 请描述您的需求或者改进建议

计划任务-任务类型，新增“备份应用”，这样就可以整体备份halo

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
