### ISSUE TITLE
[FEATURE]添加bot通知功能

### ISSUE THREAD

**Issue by mohan9898** [1Panel-dev/1Panel#1789]
### 1Panel 版本

v1.4.3

### 请描述您的需求或者改进建议

添加bot通知功能

### 请描述你建议的实现方案

添加bot通知功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持告警通知功能。

**Comment by wanghe-fit2cloud** [comment]
通知、告警相关需求的讨论，统一汇总到该 issue #614
