### ISSUE TITLE
[FEATURE]增加umami网站访问监控仪表板

### ISSUE THREAD

**Issue by HLLF-FAN** [1Panel-dev/1Panel#1790]
### 1Panel 版本

v1.4.3

### 请描述您的需求或者改进建议

增加umami网站访问监控仪表板
![image](https://github.com/1Panel-dev/1Panel/assets/107034178/3facf274-6e61-4864-bb2f-79302a85cebd)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会在应用商店中支持。

**Comment by wanghe-fit2cloud** [comment]
#250

**Comment by wanghe-fit2cloud** [comment]
重复 #1270
