### ISSUE TITLE
[FEATURE]备份账号中使用腾讯云 COS 和容器菜单建议

### ISSUE THREAD

**Issue by ZHDTZ** [1Panel-dev/1Panel#1791]
### 1Panel 版本

v1.4.3

### 请描述您的需求或者改进建议

关于在备份账号中使用腾讯云COS中：

1. `Region`添加地区候选栏，形式与`存储类型`相同；
2. 连通性测试。

关于`Docker`拉取镜像中：

1. 镜像名称改为模糊搜索，以网格或列表视图列出候选镜像，并提供其docker hub的外部跳转链接；
2. 创建容器时，列出镜像的内部端口与待填的外部端口，并且`不理解容器的内部端口自填有什么用`。

在操作逻辑上，修改三级标题的弹回形式。以`容器`→`镜像`→`拉取镜像`为例，弹出右部小窗后，其顶部`返回`与`X`具有相同作用且重复。但是单击小窗以外空白区域，无自动缩回的方式，不跟手。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
- 腾讯 COS:
1、后续版本会考虑是否要支持选择区域
2、在获取 Bucket 的时候就相当于做的是连通性测试
- 容器：
1、自动搜索镜像名称的这个功能，后续版本可能会考虑支持（要兼容所有仓库，不一定是 Docker Hub）
2、内部端口必填，1Panel 系统肯定不知道外部端口的对应关系

**Comment by ZHDTZ** [comment]
你好，镜像名称如下所示
[![pP9VbqO.png](https://s1.ax1x.com/2023/07/31/pP9VbqO.png)](https://imgse.com/i/pP9VbqO)
内部及卷映射能否实现一下效果
[![pP9VLZD.png](https://s1.ax1x.com/2023/07/31/pP9VLZD.png)](https://imgse.com/i/pP9VLZD)

**Comment by wanghe-fit2cloud** [comment]
> 你好，镜像名称如下所示

感谢建议，我们中短期内应该不会考虑上述功能，望理解。
