### ISSUE TITLE
[QUESTION]腾讯云COS的快照备份，多次上传失败

### ISSUE THREAD

**Issue by ZHDTZ** [1Panel-dev/1Panel#1792]
### 请描述您的问题

- 腾讯云COS的快照备份，多次上传失败报错，内容为`Put "https:/XXXXXXX.cos.ap-beijing.myqcloud.com/panel%2F1panel%2Fbackup%2Fsystem_snapshot%2F1panel_v1.4.3_20230731094731.tar.gz": write tcp XXXXX:45496->82.156.94.48:443: write: connection reset by peer`（相关XXX已隐藏），上传时间很长且上传无内容。请提供些技术指导
- OneDrive备份，试了自己的edu和随机的E5子账号均要求管理员权限，但这两个账号在起码的`Cloudreve`和`Rclone`中是没有问题的

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
看报错信息似乎是网络问题，你可以尝试重启。
然后再确认一下，制作的快照文件有多大。

**Comment by ZHDTZ** [comment]
你好,，/backup文件夹共约4.2GB，服务器ping到存储桶的域名是没有问题的，也重启了。

**Comment by ZHDTZ** [comment]
你好，更换COS的Region源为HK即可完成上传。注：我的服务器在GB。
请完结此贴。
