### ISSUE TITLE
[BUG] 当数据库密码中包含&时，无法正常添加应用

### ISSUE THREAD

**Issue by miaowuawa** [1Panel-dev/1Panel#1793]
### 联系方式

Q2022505032

### 1Panel 版本

1.4.3

### 问题描述

数据库密码的规则支持&这个字符，但1panel为防止命令注入禁止在命令中包含此字符，从而导致显示密码可用，但是执行不了命令

### 重现步骤

1.安装应用程序（我装的是flarum，其他应用程序也可以）
2.在输入数据库密码区域输入任何包含&的密码
3.出现“命令中含有非法字符”

### 期待的正确结果

建议禁止在数据库密码中写这个字符即可
目前密码下的提示的意思是数据库密码是支持这个特殊字符
很容易误导一些萌新，让他们奇怪，到底出问题在哪里

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
