### ISSUE TITLE
[BUG]网站中文域名支持

### ISSUE THREAD

**Issue by SkyAerope** [1Panel-dev/1Panel#1796]
### 1Panel 版本

v1.4.3

### 问题描述

在添加网站时若使用中文域名，则访问网站时发生404错误，同时网站无日志。若中文域名通过Punycode编码则无此问题。

### 重现步骤

1. 网站>创建网站>主域名直接输入中文域名，
打开该域名出现404错误。查看网站日志发现日志为空。
2. 创建网站时使用通过Punycode编码的中文域名，则没有发生问题。
3. 网站设置>新增域名>新增通过Punycode编码的中文域名，则没有发生问题。

### 期待的正确结果

输入中文域名并创建网站后，自动将网站域名转换为已Punycode编码的域名

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本会考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复 issue #1522
