### ISSUE TITLE
[QUESTION]OpenResty反向代理是否可以指定路径?

### ISSUE THREAD

**Issue by Satisfy8375** [1Panel-dev/1Panel#1798]
### 请描述您的问题

测试用OpenResty反向代理目前只能指定ip+端口，如果加上/路径指向的话，网站无法访问，请问有其他解决方法吗
![3853794913bf9675f325267af7a5d36](https://github.com/1Panel-dev/1Panel/assets/95027599/eb6b7bf8-1aa3-4356-929f-597eda1aee91)

**Comment by wanghe-fit2cloud** [comment]
这取决于要反向代理的服务是否支持二级目录访问。
> Halo、WordPress等应用是不支持的。

**Comment by Satisfy8375** [comment]
> 这取决于要反向代理的服务是否支持二级目录访问。
> 
> > Halo、WordPress等应用是不支持的。

好的谢谢，我目前的应用是uptimer kuma
