### ISSUE TITLE
[FEATURE] 建议增加MySQL数据库多版本共存

### ISSUE THREAD

**Issue by Fcatme** [1Panel-dev/1Panel#1799]
### 1Panel 版本

v1.4.3

### 请描述您的需求或者改进建议

由于部分程序对数据库兼容问题。是否可以增加一个双数据库？（也就是共存）
比如说
我已经安装了MySQL8.0 还可以安装 MySQL 5.7  只要数据库端口不一样就好了

在创建数据库的时候就可以选择在 MySQL 8.0 或者 5.7内 创建数据库

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，关于 MySQL 数据库共存的需求，我们会在近期版本支持。

**Comment by sorshion** [comment]
+1 确实需要

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
