### ISSUE TITLE
[FEATURE] 在线更新和历史版本

### ISSUE THREAD

**Issue by it985** [1Panel-dev/1Panel#1801]
### 1Panel 版本

v1.4.3

### 请描述您的需求或者改进建议

基于docker实现，建议加个在线更新容器和历史版本，而不是等待面板统一更新

### 请描述你建议的实现方案

暂无

### 附加信息

![%9FI~GN1QUT_PWU}RH3L8)9](https://github.com/1Panel-dev/1Panel/assets/62421120/1e630e34-2eb4-405b-9d14-e2ac5312ea53)
![OG 854DMQANS5HOZLHJ0}OP](https://github.com/1Panel-dev/1Panel/assets/62421120/ca3c6772-d545-4aaf-9734-01948ca70e0e)
![%9FI~GN1QUT_PWU}RH3L8)9](https://github.com/1Panel-dev/1Panel/assets/62421120/b6b9d56e-0366-4b72-9dc0-fcedae42b8ca)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，关于应用商店中应用的更新机制，我们会在后续版本中讨论具体的方案。
