### ISSUE TITLE
用1panel自动部署的wordpress，http服务用的是1panel安装的ngxin 开启伪静态报错 [BUG]

### ISSUE THREAD

**Issue by Vinking-Yang** [1Panel-dev/1Panel#1804]
### 1Panel 版本

最新版

### 问题描述

用1panel自动部署的wordpress，http服务用的是1panel安装的nginx
开启伪静态报错

### 重现步骤

用1panel自动部署的wordpress，http服务用的是1panel安装的nginx
开启伪静态报错

**Comment by wanghe-fit2cloud** [comment]
1、麻烦贴一下错误日志。
2、http 服务使用的是 OpenResty 还是 NginxProxyManager?

**Comment by guorenxi** [comment]
同样的问题，提示location / {} 重复

**Comment by wanghe-fit2cloud** [comment]
规则重复导致的。如果必须使用上述伪静态规则， 建议使用 PHP 运行环境来安装 WordPress。

**Comment by yggcwx** [comment]
> 规则重复导致的。如果必须使用上述伪静态规则， 建议使用 PHP 运行环境来安装 WordPress。

怎么用php 安装wp呢？

**Comment by wanghe-fit2cloud** [comment]
> > 规则重复导致的。如果必须使用上述伪静态规则， 建议使用 PHP 运行环境来安装 WordPress。
> 
> 怎么用php 安装wp呢？

创建运行环境网站。
