### ISSUE TITLE
[BUG] 计划任务脚本内容输入框无法伸展

### ISSUE THREAD

**Issue by zhiqing0205** [1Panel-dev/1Panel#1812]
### 联系方式

ziuch0604@gmail.com

### 1Panel 版本

1.4.3

### 问题描述

计划任务脚本内容输入框，将鼠标放到右下角显示可以伸展，拖动后输入框闪烁，松手后复原

### 重现步骤

鼠标放到右下角后拖动

### 期待的正确结果

输入框变长

### 附加信息

谷歌浏览器 PC端

**Comment by wanghe-fit2cloud** [comment]
刚刚在 Chrome、Firefox、Safari 浏览器中均没有复现上述问题。
你那边先清理浏览器缓存、无痕访问、切换其他浏览器等等方法试一下。

**Comment by zhiqing0205** [comment]
尴尬 谷歌和Edge 无痕模式均出现
