### ISSUE TITLE
[BUG] mysql 连接数据库名错误

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#1831]
### 1Panel 版本

1.4.3

### 问题描述

mysql 连接数据名不对
![图片](https://github.com/1Panel-dev/1Panel/assets/15864713/4dd85d08-2038-43b1-acb0-8df08bf63603)
但实际上连接名称是 mysql，每次手动更改 .env 文件之后更新一下应用又恢复到了错误的名字

### 重现步骤

手动更改 .env 文件之后更新一下应用又恢复到了错误的名字

**Comment by wanghe-fit2cloud** [comment]
处于相同网络下的容器使用的 MySQL 数据库连接地址是 service name。
> 在创建 MySQL 应用时 docker-compose.yml 指定，默认 mysql

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/905bb4f9-faa0-45f7-b251-0dec623124d4)

**Comment by mx2913** [comment]
> 处于相同网络下的容器使用的 MySQL 数据库连接地址是 service name。
> 
> > 在创建 MySQL 应用时 docker-compose.yml 指定，默认 mysql
> 
> ![image](https://user-images.githubusercontent.com/46734380/258296706-905bb4f9-faa0-45f7-b251-0dec623124d4.png)

创建的时候 `server name` 的确是 mysql，但是我在新建应用的时候，为啥 .env 环境文件中的 `PANEL_DB_HOST` 这个变量的值反而不是 `mysql` 而是 `mysql-${任意后缀}` 呢，每次新安装应用或者更新应用后都需要手动去修改 .env 文件中的 DB_HOST 之类的变量

**Comment by mx2913** [comment]
修改完之后还需要我手动去执行 docker-compose up -d 去重新加载新的 env 配置
<img width="745" alt="图片" src="https://github.com/1Panel-dev/1Panel/assets/15864713/372e7889-e0a4-41ee-a553-57c5db114770">

**Comment by wanghe-fit2cloud** [comment]
> 每次新安装应用或者更新应用后都需要手动去修改 .env 文件中的 DB_HOST 之类的变

如果你安装 MySQL 应用到时候没有手动修改过 compose 文件中的 service name，那在安装其他应用选择 MySQL 的时候就默认是 mysql

**Comment by wanghe-fit2cloud** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/a3ddc2f0-6734-4891-a61f-f04ab5e2552a)

**Comment by mx2913** [comment]
![图片](https://github.com/1Panel-dev/1Panel/assets/15864713/6eb34a51-ca0b-41b6-93f8-9012adab8fb0)
![图片](https://github.com/1Panel-dev/1Panel/assets/15864713/fd1d283f-9a95-402a-a79d-93f2de889292)
项目都还在安装中

**Comment by mx2913** [comment]
![图片](https://github.com/1Panel-dev/1Panel/assets/15864713/8d6501d7-6d06-4e61-a69b-88ab5a509917)

**Comment by mx2913** [comment]
总不能让我每次都手动改吧

**Comment by wanghe-fit2cloud** [comment]
> 总不能让我每次都手动改吧

上边回复已经提到，如果在安装 MySQL 应用是后没有手动修改过 compose 文件中的 service name，就会默认是 mysql

**Comment by wanghe-fit2cloud** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/6c7c0d6d-c32a-4148-be8b-fe39fb300600)
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/d500ff35-521f-4dfa-aeeb-87f271acf0cb)

**Comment by mx2913** [comment]
你们这个名字是从哪取的，从 sqlite 吗，我去直接改下这个源头试试看

**Comment by mx2913** [comment]
重装 mysql 解决了，怀疑是最初的 service_name 随机后缀导致的
