### ISSUE TITLE
[BUG]多文件上传时 存在 文件夹 项目报错

### ISSUE THREAD

**Issue by iven95** [1Panel-dev/1Panel#1833]
### 联系方式

V：IvenChen95

### 1Panel 版本

new

### 问题描述

BUG反馈： 多文件上传时 存在 文件夹 项目报错
可能原因：观看报文，当文件处理了

### 重现步骤

直接拖文件夹进到上传拖拽区域

### 期待的正确结果

递归里面的文件上传

**Comment by zhengkunwang223** [comment]
已修复 跟随  v1.5 版本发布

**Comment by zhengkunwang223** [comment]
经过我们测试 已有的方案无法解决可以拖入文件夹的问题  
此问题是浏览器无法获取到文件夹 且没有提供接口和返回值去判断是否为此错误 所以暂时无法解决
