### ISSUE TITLE
[BUG]防火墙页面分页问题。

### ISSUE THREAD

**Issue by iven95** [1Panel-dev/1Panel#1834]
### 联系方式

V：IvenChen95

### 1Panel 版本

new

### 问题描述

在防火墙页面分页问题

### 重现步骤

先选 5条/页 然后点击最后一页，再选 100条/页 导致查不到信息（前端开发者忘了将当前页改为1）

### 期待的正确结果

更改分页大小，当前分页 为 1

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述问题我们会在 v1.6 版本修复。

**Comment by wanghe-fit2cloud** [comment]
v1.5.1 版本已发布。
