### ISSUE TITLE
[FEATURE]上传文件 没必要切片上传，直接上传省了很多tcp握手环节

### ISSUE THREAD

**Issue by iven95** [1Panel-dev/1Panel#1836]
### 1Panel 版本

new

### 请描述您的需求或者改进建议

上传文件 没必要切片上传，直接上传省了很多tcp握手环节，上传的时候用 流 本来是可以指定 指针的，所以此处采用传统方式上传就行了。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述建议。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
