### ISSUE TITLE
[BUG] 在安装某些应用的时候会强制要求选择MySQL数据库

### ISSUE THREAD

**Issue by happytbs** [1Panel-dev/1Panel#1842]
### 联系方式

QQ号3026642514

### 1Panel 版本

v1.4.3

### 问题描述

在安装halo应用的时候会强制要求选择MySQL数据库，导致我没法选择我其他面板（例如宝塔）的数据库开安装（因为在高级选项里他是可以改的，但是安装的时候还是要求必须选择才能安装）

### 重现步骤

1. 选择halo，点击安装，
2. 弹出选择菜单，在高级配置里修改数据库的相关选项
3. 在面板提供的现成选项里配置除数据库以外的其他选项
4. 点击安装，发现报错，提示必须选择一个本面板的数据库

![image](https://github.com/1Panel-dev/1Panel/assets/74001578/2a74ea0d-a853-4418-bdd9-df7d0d244f39)

### 期待的正确结果

建议把这个改成可选，来方便在不安装本地数据库的情况下安装应用

### 附加信息

![这里已经在高级配置里对数据库做出了修改](https://github.com/1Panel-dev/1Panel/assets/74001578/c13370fa-9226-4f17-a7b0-71ca6329bf51)
![仍然无法继续安装](https://github.com/1Panel-dev/1Panel/assets/74001578/19e86d1f-71e3-4584-81e7-9cefd11f8f73)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后面版本会考虑上述建议。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
