### ISSUE TITLE
[FEATURE] 1panel 中已安装应用的链接跳转

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#1844]
### 1Panel 版本

1.4.3

#### 目前存在问题的链接跳转
* Docker 容器列表中端口列以及已安装应用的跳转功能目前只能跳到 `${ip}:${port}` 的地址形式
* 数据库中 `mysql` 的管理工具 `phpMyAdmin` 和 `Redis` 的管理工具 `redis-commander` 的跳转也只能跳转到上述的形式

能不能提供可以修改的地方，让他跳转到已经配置的域名上

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本会考虑上述需求。

**Comment by mx2913** [comment]
漏了个 mysql 和 redis 连接信息中的外部连接地址在已经配置服务器 IP 的情况显示 `${ip}:${port}` 而不是 `本机IP:${port}`

**Comment by wanghe-fit2cloud** [comment]
> 漏了个 mysql 和 redis 连接信息中的外部连接地址在已经配置服务器 IP 的情况显示 `${ip}:${port}` 而不是 `本机IP:${port}`

收到，后面版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布，服务器地址栏支持设置域名。

**Comment by mx2913** [comment]
> v1.5.0 版本已发布，服务器地址栏支持设置域名。

这个还是不支持配置的子域名跳转啊，总不能每起一个应用就开放一堆新的端口吧，这样的话还要 OpenResty 有啥用
