### ISSUE TITLE
[QUESTION]有两个问题请教一下

### ISSUE THREAD

**Issue by franklight** [1Panel-dev/1Panel#1847]
### 请描述您的问题

1、只要是涉及到数据库的，比如新建数据库，一键搭建网站，都会提示这个错误，请问这个应该怎么解决？

【服务内部错误: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)】

2、在新建数据库的时候，我发现现在的版本在权限设置那里，已经没有“本地服务器”了，只有所有人%和指定IP了，我是希望搭建一个站点，请问应该是需要选择哪个？

谢谢。

**Comment by wanghe-fit2cloud** [comment]
要注意的一点是：1Panel 是容器化部署的应用。

1、第三方应用访问 MySQL 等数据库时需要使用容器的服务名称，如下图：
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/8f4bf9ca-6789-4122-81a5-65bfa428a249">
2、因为是容器化安装，`本地服务器` 就指的是 MySQL 容器内部，没有任何意义

**Comment by liesauer** [comment]
同问，新安装出来的数据库容器，连1Panel自身都管理不了这个数据库，这算不算一个BUG？点啥都报错
![image](https://github.com/1Panel-dev/1Panel/assets/8676741/9c01a5f6-9c59-4ce6-b464-28eae075f0f5)

**Comment by liesauer** [comment]
另外我安装了phpMyAdmin，也是连不进去MySQL容器，现在属于是完全封闭锁死了
![image](https://github.com/1Panel-dev/1Panel/assets/8676741/71925b4f-241c-4874-8f69-8dd9a9c5408d)

**Comment by wanghe-fit2cloud** [comment]
> 同问，新安装出来的数据库容器，连1Panel自身都管理不了这个数据库，这算不算一个BUG？点啥都报错 !

你这很可能是 MySQL 服务就不正常。
去 `容器` 页面查看 MySQL 容器状态和日志。

**Comment by liesauer** [comment]
> > 同问，新安装出来的数据库容器，连1Panel自身都管理不了这个数据库，这算不算一个BUG？点啥都报错 !
> 
> 你这很可能是 MySQL 服务就不正常。 去 `容器` 页面查看 MySQL 容器状态和日志。

我看了容器状态倒是没问题，我进终端把root的权限重新修复后可以了，1Panel和phpMyAdmin都正常可以了

**Comment by wanghe-fit2cloud** [comment]
> 我进终端把root的权限重新修复后可以了，1Panel和phpMyAdmin都正常可以了

1Panel 是容器化部署的应用，需要开启 root 用户的远程访问等权限。

**Comment by liesauer** [comment]
> > 我进终端把root的权限重新修复后可以了，1Panel和phpMyAdmin都正常可以了
> 
> 1Panel 是容器化部署的应用，需要开启 root 用户的远程访问等权限。

不行，连开关这个选项都报错，所以不知道什么情况，除了命令行终端，都锁死进不去

**Comment by wanghe-fit2cloud** [comment]
> > > 我进终端把root的权限重新修复后可以了，1Panel和phpMyAdmin都正常可以了
> > 
> > 
> > 1Panel 是容器化部署的应用，需要开启 root 用户的远程访问等权限。
> 
> 不行，连开关这个选项都报错，所以不知道什么情况，除了命令行终端，都锁死进不去

`我进终端把root的权限重新修复后可以了`，麻烦提供一下你修复了哪些配置。

**Comment by liesauer** [comment]
> > > > 我进终端把root的权限重新修复后可以了，1Panel和phpMyAdmin都正常可以了
> > > 
> > > 
> > > 1Panel 是容器化部署的应用，需要开启 root 用户的远程访问等权限。
> > 
> > 
> > 不行，连开关这个选项都报错，所以不知道什么情况，除了命令行终端，都锁死进不去
> 
> `我进终端把root的权限重新修复后可以了`，麻烦提供一下你修复了哪些配置。

```
use mysql; update user set host = '%' where user = 'root';

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '密码' WITH GRANT OPTION; FLUSH PRIVILEGES;
```

**Comment by wanghe-fit2cloud** [comment]
> > > > > 我进终端把root的权限重新修复后可以了，1Panel和phpMyAdmin都正常可以了
> > > > 
> > > > 
> > > > 1Panel 是容器化部署的应用，需要开启 root 用户的远程访问等权限。
> > > 
> > > 
> > > 不行，连开关这个选项都报错，所以不知道什么情况，除了命令行终端，都锁死进不去
> > 
> > 
> > `我进终端把root的权限重新修复后可以了`，麻烦提供一下你修复了哪些配置。
> 
> ```
> use mysql; update user set host = '%' where user = 'root';
> 
> GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '密码' WITH GRANT OPTION; FLUSH PRIVILEGES;
> ```

不太好定位，因为我们默认给的就是这个权限。
> 在本地环境尝试创建多个 MySQL 数据库，均未复现上述问题。
首次安装成功后进入容器终端，权限也均正常。
先

**Comment by liesauer** [comment]
> 不太好定位，因为我们默认给的就是这个权限。

我第一次进去终端，发现root默认的host是`localhost`，这是不是不正常的

**Comment by wanghe-fit2cloud** [comment]
> > 不太好定位，因为我们默认给的就是这个权限。
> 
> 我第一次进去终端，发现root默认的host是`localhost`，这是不是不正常的

MySQL root 用户默认会有两个权限，一个是 `%`，一个是 `localhost`

**Comment by liesauer** [comment]
> MySQL root 用户默认会有两个权限，一个是 `%`，一个是 `localhost`

只有一个`localhost`，我刚刚把数据库删了，又重新装了个，一切正常，但是我发现了一个细节，昨晚我创建的那个数据库（现在讨论的这个）是无密码的，终端里直接`mysql`就进去了，我刚刚创建的正常的，是有密码的，就是1Panel默认密码，但是我确定都是没改配置一键安装的，昨晚和`redis`同时安装的，会不会是服务器太卡了，配置没读取到之类的。

**Comment by wanghe-fit2cloud** [comment]
> > MySQL root 用户默认会有两个权限，一个是 `%`，一个是 `localhost`
> 
> 只有一个`localhost`，我刚刚把数据库删了，又重新装了个，一切正常，但是我发现了一个细节，昨晚我创建的那个数据库（现在讨论的这个）是无密码的，终端里直接`mysql`就进去了，我刚刚创建的正常的，是有密码的，就是1Panel默认密码，但是我确定都是没改配置一键安装的，昨晚和`redis`同时安装的，会不会是服务器太卡了，配置没读取到之类的。

不排除这个问题。后续再出现上述问题可以看一下系统日志。

**Comment by youngledo** [comment]
我也出现了，卸载之后重新安装又好了。感觉像是触发了某个场景的bug。
