### ISSUE TITLE
[FEATURE]卸载保留数据

### ISSUE THREAD

**Issue by XCWQW1** [1Panel-dev/1Panel#1848]
### 1Panel 版本

v1.4.3

### 请描述您的需求或者改进建议

希望在后台卸载1panel的时候能选择卸载保留数据
我今天醒来机子抽风了，让后重启我进不去1Panel，让后直接1pctl uninstall了让后发现容器都在但是1Panel提示我没有安装openxxxxx的那些，之前装过的1Panel不会重新识别到吗

**Comment by XCWQW1** [comment]
> ### 1Panel 版本
> v1.4.3 1.4.3 版
> 
> ### 请描述您的需求或者改进建议
> 希望在后台卸载1panel的时候能选择卸载保留数据 我今天醒来机子抽风了，让后重启我进不去1Panel，让后直接1pctl uninstall了让后发现容器都在但是1Panel提示我没有安装openxxxxx的那些，之前装过的1Panel不会重新识别到吗
> 
> ### 请描述你建议的实现方案
> _No response 无响应_
> 
> ### 附加信息
> _No response 无响应_

或者可以增加重装指令

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
上述问题可以尝试使用系统快照功能，具体操作如下：
`面板设置 - 快照 - 同步 - 恢复`

<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/1827e26a-b029-4c32-aea2-79773262a013">
