### ISSUE TITLE
[BUG] 海外服务器无法获取应用列表

### ISSUE THREAD

**Issue by konsheng** [1Panel-dev/1Panel#1849]
### 联系方式

QQ 296907782

### 1Panel 版本

1.4.3

### 问题描述

海外服务器无法获取应用列表

### 重现步骤

海外服务器无法获取应用列表

**Comment by wanghe-fit2cloud** [comment]
1Panel 系统资源统一放在阿里 OSS，是全球加速的 cdn，应该不会慢，除非 cdn 节点有问题了。
