### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 1148260649** [1Panel-dev/1Panel#1851]
### 联系方式

1148260649@qq.com

### 1Panel 版本

1.4.3

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/45970803/f1056fcd-63a2-41f9-a810-15023eec1219)

一直在安装中，已经配置了 docker 的镜像源

### 重现步骤

就直接在商店中下载

### 期待的正确结果

安装完成

**Comment by wanghe-fit2cloud** [comment]
可以先到 `主机 - 终端` 页面，先手动拉取镜像：

```shell
docker pull jenkins/jenkins:2.417
```

> 其他应用也一样的道理，可以在安装页面点击高级设置，编辑 compose 查看 image 名称。

**Comment by 1148260649** [comment]
那我每个镜像是不是都要手动拉取下？

**Comment by wanghe-fit2cloud** [comment]
> 那我每个镜像是不是都要手动拉取下？

只要能确保镜像 pull 成功就可以，无论是自动还是手动。
