### ISSUE TITLE
[FEATURE]希望可以添加CPU，内存，流量等占用高时发送邮件预警

### ISSUE THREAD

**Issue by smilecat2788** [1Panel-dev/1Panel#1853]
### 1Panel 版本

1.4.3

### 请描述您的需求或者改进建议

希望可以添加CPU，内存，流量等占用高时发送邮件预警

### 请描述你建议的实现方案

可以对CPU内存等设置一个占用阈值，超出以后通过smtp邮件服务发送一封邮件
smtp服务和收件人邮箱用户自行配置

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本增加告警通知功能。

**Comment by wanghe-fit2cloud** [comment]
通知、告警相关需求的讨论，统一汇总到该 issue #614
