### ISSUE TITLE
[QUESTION]快照相关问题，怎么手动恢复？

### ISSUE THREAD

**Issue by xu5343** [1Panel-dev/1Panel#1856]
### 请描述您的问题

快照成功上传 OneDrive，另外一台登录该 OneDrive，同步没有看到该快照文件，两边快照保存文件夹设置一样的，OneDrive 
确实有该文件，怎么手动恢复快照？

**Comment by wanghe-fit2cloud** [comment]
1、`同步快照 - 备份账号` 下拉框，只支持面板设置中已添加的备份账号（不支持选择谷歌云盘）。
2、可以先添加备份账号，然后将快照文件上传至支持的备份账号（如阿里云 OSS 等）。

**Comment by ssongliu** [comment]
感谢反馈！本地已经复现了该问题，将在本周发布的 v1.5.0 解决。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
