### ISSUE TITLE
建议添加批量删除未使用端口规则功能[FEATURE]

### ISSUE THREAD

**Issue by qrekkwijjtx54** [1Panel-dev/1Panel#1859]
### 1Panel 版本

1.4.3

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/118114198/9bfb87d9-22c3-4aea-9f65-f81173ea8b5d)
建议添加批量删除未使用端口规则功能[FEATURE]

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本支持根据状态来过滤防火墙规则。
