### ISSUE TITLE
[BUG] 快照创建失败：backup docker data failed, err: stderr: tar

### ISSUE THREAD

**Issue by Dreamail** [1Panel-dev/1Panel#1867]
### 联系方式

dreaillll@outlook.com

### 1Panel 版本

1.4.3

### 问题描述

创建快照时报错：
backup docker data failed, err: stderr: tar: ./overlay2/104b33e16f20497a7d0ce0517882dfc3bbe794ab4b14ff980d961d9694540b3b/diff/run/mysqld/mysqld.sock: socket ignored tar: ./overlay2/104b33e16f20497a7d0ce0517882dfc3bbe794ab4b14ff980d961d9694540b3b/diff/run/mysqld/mysqlx.sock: socket ignored tar: ./overlay2/104b33e16f20497a7d0ce0517882dfc3bbe794ab4b14ff980d961d9694540b3b/merged/run/mysqld/mysqld.sock: socket ignored tar: ./overlay2/104b33e16f20497a7d0ce0517882dfc3bbe794ab4b14ff980d961d9694540b3b/merged/run/mysqld/mysqlx.sock: socket ignored tar: ./overlay2/369f89c00a9db2f31086d660172ce9f728f623130905350e2b67c238207b1278/diff/run/php-fpm.sock: socket ignored tar: ./overlay2/369f89c00a9db2f31086d660172ce9f728f623130905350e2b67c238207b1278/merged/run/php-fpm.sock: socket ignored

### 重现步骤

创建快照

### 附加信息

在应用服务没有停止的情况下和停止了的情况下均无法创建快照

**Comment by Dreamail** [comment]
停止应用后发现应用容器仍在运行

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在这周要发布的 v1.5.0 版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布，针对快照的创建逻辑进行了优化。
