### ISSUE TITLE
[FEATURE] 建议安装应用时支持选择已存在的本地和远程数据库

### ISSUE THREAD

**Issue by xiaolongyuan** [1Panel-dev/1Panel#1878]
### 1Panel 版本

1.4.2

### 请描述您的需求或者改进建议

建议安装应用时支持选择已存在的本地和远程数据库  目前需要手动填写参数实现 比较麻烦

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们计划是在远程数据库功能稳定运行几个版本后，再来支持安装应用时选择远程数据库。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
