### ISSUE TITLE
建议腾讯云的OpenCloudos系统能够适配安装

### ISSUE THREAD

**Issue by fengjisheng** [1Panel-dev/1Panel#1879]
### 请描述您的问题

看腾讯云 opencloudos 是 centos8 优化的,  内核还是centos  希望能够适配

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
请问现在遇到的具体问题是什么？
是在线安装 docker 失败还是运行 1Panel 系统失败。

**Comment by fengjisheng** [comment]
安装的时候 提示这个

ERROR: Unsupported distribution 'opencloudos'

[1Panel Log]: ... 启动 docker
Failed to enable unit: Unit file docker.service does not exist.
Failed to start docker.service: Unit docker.service not found.
[1Panel Log]: docker 安装失败

**Comment by wanghe-fit2cloud** [comment]
可以参考下面的脚本，来提前预装 docker：

```shell
bash <(curl -sSL https://linuxmirrors.cn/docker.sh)
```

**Comment by fengjisheng** [comment]
嗯, 谢谢了
