### ISSUE TITLE
[FEATURE] 增加1Panel本地应用商店订阅助手（应用开发调试小帮手）

### ISSUE THREAD

**Issue by xxxily** [1Panel-dev/1Panel#1880]
### 1Panel 版本

v1.4.3

### 请描述您的需求或者改进建议

建议在应用商店里增加可订阅第三方维护的应用列表的设置选项，以增加应用商店的灵活性和多样性，同时也可以通过设定订阅地址来方便开发调试自己创建的应用

### 请描述你建议的实现方案

目前已通过1Panel的本地应用+计划任务的形式实现了一套1Panel的本地应用商店订阅助手：

### 项目地址

https://github.com/xxxily/local-appstore-for-1Panel

###  实现原理

通过定时任务自动拉取远程仓库编排好的应用配置到本地的`/opt/1panel/resource/apps/local` 目录，以做到自动订阅外部应用或进行1Panel应用的开发调试。

希望官方能在应用商店里直接提供订阅配置的能力，让应用商店变得更加灵活、更强大

### 附加信息

在官方没提供订阅入口前，欢迎大家试用local-appstore-for-1Panel来开发或订阅自己喜欢的应用，集思广益，让1Panel更灵活更好用起来。

[1Panel本地应用商店 / local appstore for 1Panel](https://github.com/xxxily/local-appstore-for-1Panel) 

### 特性

- 可一键更新同步1Panel官网的应用商店应用到本地环境
- 支持将任意第三方仓库的应用同步到1Panel的本地应用商店
- 支持github，gitlab，gitee等公开仓库、私有仓库
- 支持将多个分散的仓库应用同步到1Panel的本地应用商店
- 支持自定义拉取的分支、克隆深度、访问代理等，方便灵活
- 同步脚本源码完全开源，可自行修改、扩展，可放心使用

### 使用场景

- 1Panel官方应用商店的应用更新慢，想要快速更新到本地进行使用
- 1Panel官方应用有BUG，或者版本太低，想要自己修改后使用
- 1Panel官方应用商店没有自己想要的应用，想要自己添加应用
- 由于某些原因没法上架到1Panel官方应用商店，定制自己的专属应用
- 用于快速调试开发1Panel应用，方便本地开发调试
- 想要将多个分散的仓库应用同步到1Panel的本地应用商店

### 效果演示

将1Panel appstore里最近更的应用一键同步到本地应用商店

![read_cron_task_result](https://raw.githubusercontent.com/xxxily/local-appstore-for-1Panel/main/docs/img/read_cron_task_result.png)

**Comment by wanghe-fit2cloud** [comment]
感谢大佬分享。
我们会在后面版本考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
应用商店增加订阅机制的需求，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4935
