### ISSUE TITLE
[FEATURE]建议改进MFA验证体验，快速进入主页

### ISSUE THREAD

**Issue by mengxunlingxue** [1Panel-dev/1Panel#1884]
### 1Panel 版本

v1.4.3

### 请描述您的需求或者改进建议

建议改进MFA验证体验，快速进入主页
<img width="1416" alt="QQ20230808-234608@2x" src="https://github.com/1Panel-dev/1Panel/assets/24265178/6063accd-3f7d-46e1-9167-d6d9f83a2fef">

### 请描述你建议的实现方案

建议输入MFA数字之后自动验证，不需要自己再手动点击验证
现在的MFA管理器基本都自带点击一键复制验证码，所以在登陆过程中，希望支持一键粘贴后自动进入主页，无需手动点击验证

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
