### ISSUE TITLE
[QUESTION]JumpServer上添加 1Panel web 访问资产，1Panel 页面登录的选择器应该如何填?

### ISSUE THREAD

**Issue by guoligg** [1Panel-dev/1Panel#1889]
### 请描述您的问题

jumpserver上添加1panel  web访问资产,1panel页面登录的选择器应该如何填?

**Comment by guoligg** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/29765164/d52fa729-0392-4599-b92d-91b6bb25b864)

**Comment by guoligg** [comment]
1panel版本:v1.4.3
jumpserver版本:v3.5.3

**Comment by wangzhishang0204** [comment]
用户名： css=[placeholder="用户名"]
密码：css=[placeholder="密码"]
确认按钮：xpath=//*[@id="app"]/div/div/div/div[2]/div/div/div/div/form/div[4]/div/button/span

具体的也可以参考JumpServer的官方文档：https://docs.jumpserver.org/zh/v3/guide/system/remoteapp/?h=%E8%BF%9C%E7%A8%8B%E5%BA%94%E7%94%A8#3

**Comment by guoligg** [comment]
多谢,参照过文档但是不会获取元素
还有个问题,自动登录账号密码后,那个同意协议如何设置自动勾选
![image](https://github.com/1Panel-dev/1Panel/assets/29765164/89a779ae-1f4f-48de-ae4b-c62e240ae6a3)

**Comment by wangzhishang0204** [comment]
你先手动勾选，看下次登录会不会记录这个勾选
如果想要通过JumpServer的元素代填，这种高级玩法就需要写自定义的脚本了

**Comment by shangdev** [comment]
@wangzhishang02 @guoligg 借楼问一下用1panel应用商店安装的jumpserver web访问时登录账号和密码是多少啊？参数那里并没有显示

**Comment by wanghe-fit2cloud** [comment]
> @wangzhishang02 @guoligg 借楼问一下用1panel应用商店安装的jumpserver web访问时登录账号和密码是多少啊？参数那里并没有显示

admin/admin

**Comment by shangdev** [comment]
@wanghe-fit2cloud 提示配置文件有问题，无法登录，请联系管理员或查看最新文档
如果你是管理员，可以更新配置文件解决，设置配置项
DOMAINS=xxxxz:8080

这个是安装失败了吗？

**Comment by wanghe-fit2cloud** [comment]
> @wanghe-fit2cloud 提示配置文件有问题，无法登录，请联系管理员或查看最新文档 如果你是管理员，可以更新配置文件解决，设置配置项 DOMAINS=xxxxz:8080
> 
> 这个是安装失败了吗？

先查看一下 JumpServer 官方文档，了解 DOMAINS
> 1Panel 在安装页面支持用户自定义该字段。
