### ISSUE TITLE
[FEATURE]建议安装Redis时不强制设置密码

### ISSUE THREAD

**Issue by vlssu** [1Panel-dev/1Panel#1898]
### 1Panel 版本

1.4.3

### 请描述您的需求或者改进建议

安装 Redis 时密码可以设置为空。
Redis 一般都在本地运行，密码没有什么必要，可以让用户自己选择设不设密码

### 请描述你建议的实现方案

在安装Redis时不强制设置密码

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/43847794/3eede403-9114-4260-9850-d396f7a4fb19)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑是否在安装 Redis 应用时取消密码。

**Comment by vlssu** [comment]
https://github.com/1Panel-dev/appstore/pull/327

**Comment by imfe888** [comment]
确实这个设定有点反人类

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
