### ISSUE TITLE
[BUG]七牛云同步快照，服务内部错误: incorrect snapshot request body: []

### ISSUE THREAD

**Issue by xkloveme** [1Panel-dev/1Panel#1900]
### 联系方式

xkloveme@gmail.com

### 1Panel 版本

v1.4.3

### 问题描述

1. 两台主机连接到同一个七牛云，配置相同位置备份路径，可以创建快照并上传成功，点击同步快照报错
2. 
![image](https://github.com/1Panel-dev/1Panel/assets/29595042/c9736ca3-78dd-4c33-8c47-1794ec3a6d80)
接口：/api/v1/settings/snapshot/import
`{"code":500,"message":"服务内部错误: incorrect snapshot request body: []","data":null}`

### 重现步骤

两台主机连接到同一个七牛云，配置相同位置备份路径，可以创建快照并上传成功，点击同步快照报错

**Comment by ssongliu** [comment]
感谢反馈！今天发布的 v1.5.0 版本对这块进行了处理，可以更新后重试一下。
