### ISSUE TITLE
应用安装时的端口应该做个黑名单，限制不可使用浏览器默认非安全端口

### ISSUE THREAD

**Issue by LiuXin-Developer** [1Panel-dev/1Panel#1907]
### 1Panel 版本

1.4.3

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/48080203/d09776d6-2a4c-4803-9643-fcbbcf8590c7)
## 当软件安装时，填入的端口包含在如下端口列表中
 1,    // tcpmux
  7,    // echo
  9,    // discard
  11,   // systat
  13,   // daytime
  15,   // netstat
  17,   // qotd
  19,   // chargen
  20,   // ftp data
  21,   // ftp access
  22,   // ssh
  23,   // telnet
  25,   // smtp
  37,   // time
  42,   // name
  43,   // nicname
  53,   // domain
  77,   // priv-rjs
  79,   // finger
  87,   // ttylink
  95,   // supdup
  101,  // hostriame
  102,  // iso-tsap
  103,  // gppitnp
  104,  // acr-nema
  109,  // pop2
  110,  // pop3
  111,  // sunrpc
  113,  // auth
  115,  // sftp
  117,  // uucp-path
  119,  // nntp
  123,  // NTP
  135,  // loc-srv /epmap
  139,  // netbios
  143,  // imap2
  179,  // BGP
  389,  // ldap
  465,  // smtp+ssl
  512,  // print / exec
  513,  // login
  514,  // shell
  515,  // printer
  526,  // tempo
  530,  // courier
  531,  // chat
  532,  // netnews
  540,  // uucp
  556,  // remotefs
  563,  // nntp+ssl
  587,  // stmp?
  601,  // ??
  636,  // ldap+ssl
  993,  // ldap+ssl
  995,  // pop3+ssl
  2049, // nfs
  3659, // apple-sasl / PasswordServer
  4045, // lockd
  6000, // X11
  6665, // Alternate IRC
  6666, // Alternate IRC
  6667, // Standard IRC
  6668, // Alternate IRC
  6669, // Alternate IRC

## 浏览器会限制访问这些端口，进行报错，导致安装的软件无法正常使用（报错：ERR_UNSAFE_PORT）
![ca1cfbb14ab0da555fea1a4409e5ad7](https://github.com/1Panel-dev/1Panel/assets/48080203/f4bc5898-ee80-4fc6-8cb8-2d46cd87537a)

### 请描述你建议的实现方案

做一个黑名单，当端口包含限制访问的端口，进行error或者warning提示

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈，我们会在后续版本考虑上述需求。

**Comment by likecutie** [comment]
这个列表不全，但我也找不到全部端口，据我所知至少还有10080端口。

**Comment by yutangbb** [comment]
如果不是浏览器直接访问，则没有影响，对于有些镜像可能会用到特定端口。
不要直接限制这些端口。检测到这些端口可以做出警告或提示，特别是网站和需要外部访问的情况。

以下是我收集的一些端口号，不知是否是最新的，比题主要全一点
1,      // tcpmux
7,      // echo
9,      // discard
11,     // systat
13,     // daytime
15,     // netstat
17,     // qotd
19,     // chargen
20,     // ftp data
21,     // ftp access
22,     // ssh
23,     // telnet
25,     // smtp
37,     // time
42,     // name
43,     // nicname
53,     // domain
69,     // tftp
77,     // priv-rjs
79,     // finger
87,     // ttylink
95,     // supdup
101,    // hostriame
102,    // iso-tsap
103,    // gppitnp
104,    // acr-nema
109,    // pop2
110,    // pop3
111,    // sunrpc
113,    // auth
115,    // sftp
117,    // uucp-path
119,    // nntp
123,    // NTP
135,    // loc-srv /epmap
137,    // netbios
139,    // netbios
143,    // imap2
161,    // snmp
179,    // BGP
389,    // ldap
427,    // SLP (Also used by Apple Filing Protocol)
465,    // smtp+ssl
512,    // print / exec
513,    // login
514,    // shell
515,    // printer
526,    // tempo
530,    // courier
531,    // chat
532,    // netnews
540,    // uucp
548,    // AFP (Apple Filing Protocol)
554,    // rtsp
556,    // remotefs
563,    // nntp+ssl
587,    // smtp (rfc6409)
601,    // syslog-conn (rfc3195)
636,    // ldap+ssl
993,    // ldap+ssl
995,    // pop3+ssl
1719,   // h323gatestat
1720,   // h323hostcall
1723,   // pptp
2049,   // nfs
3659,   // apple-sasl / PasswordServer
4045,   // lockd
5060,   // sip
5061,   // sips
6000,   // X11
6566,   // sane-port
6665,   // Alternate IRC [Apple addition]
6666,   // Alternate IRC [Apple addition]
6667,   // Standard IRC [Apple addition]
6668,   // Alternate IRC [Apple addition]
6669,   // Alternate IRC [Apple addition]
6697,   // IRC + TLS
10080,  // Amanda
