### ISSUE TITLE
[QUESTION]tg群和频道

### ISSUE THREAD

**Issue by kinnrai** [1Panel-dev/1Panel#1908]
### 请描述您的问题

请问现在有官方tg群和频道吗，如果没有是否可以一个方便交流和接收通知消息。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1、微信技术交流群：
<img src="https://1panel.cn/img/wechat-group.jpg" width="156" height="156"/>
2、论坛：
https://bbs.fit2cloud.com/c/1p/7

**Comment by okxlin** [comment]
有个非官方群

https://t.me/+iyw962mKdhVkMDI1
