### ISSUE TITLE
[FEATURE]网站安全，将多次触犯任意 rule 的 IP 自动加入IP黑名单

### ISSUE THREAD

**Issue by refgd** [1Panel-dev/1Panel#1912]
### 1Panel 版本

1.5.0

### 请描述您的需求或者改进建议

网站安全里能不能加一个, 多次触犯任意rule的IP, 自动加入IP黑名单

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
