### ISSUE TITLE
[FEATURE]容器终端弹出框，点击断开按钮后不自动关闭窗口

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1913]
### 1Panel 版本

v1.5.0

### 请描述您的需求或者改进建议

容器终端弹出框，点击 `断开` 按钮后不自动关闭窗口。
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/1e517072-537f-4b0b-8179-fc7965a7efab)

### 请描述你建议的实现方案

在使用容器终端功能时，可能会因为选择或者输入了错误的命令导致进入容器终端失败。
此时点击 `断开` 按钮后会自动关闭当前页面。

建议后续版本针对该问题做出优化。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本针对上述问题做出优化。

**Comment by wanghe-fit2cloud** [comment]
v1.5.1 版本已发布。
