### ISSUE TITLE
[BUG]屏蔽/放通ip段时提示格式错误

### ISSUE THREAD

**Issue by skyhhjmk** [1Panel-dev/1Panel#1914]
### 联系方式

scrsc@qq.com

### 1Panel 版本

v1.4.3-alpha.4

### 问题描述

# 屏蔽censys ip
拉黑ip段时提示格式错误

### 重现步骤

尝试拉黑162.142.125.0/24提示格式错误
尝试拉黑162.142.125.0-162.142.125.255提示格式错误
尝试拉黑162.142.125.0 - 162.142.125.255提示格式错误
尝试拉黑162.142.125.0 162.142.125.255提示格式错误

### 期待的正确结果

能够正确识别并屏蔽：
162.142.125.0/24
167.94.138.0/24
167.94.145.0/24
167.94.146.0/24
167.248.133.0/24
192.35.168.0/23
2620:96:e000:b0cc:e::
（ipv4+v6）

**Comment by ssongliu** [comment]
感谢反馈！这里我直接放行或者屏蔽 ip 段是可以的，162.142.125.0-162.142.125.255 这种形式暂时还不支持。
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/eac7d14b-e77a-4091-be45-204d9bacffa5)
