### ISSUE TITLE
[FEATURE]导入本地证书的文件选择页面无法显示隐藏文件夹

### ISSUE THREAD

**Issue by okxlin** [1Panel-dev/1Panel#1915]
### 1Panel 版本

v1.5.0

### 请描述您的需求或者改进建议

导入本地证书的文件选择页面无法显示隐藏文件夹，

类似`/root/.acme.sh`

希望可以显示，毕竟`acme.sh`脚本还是挺常用的。

![image](https://github.com/1Panel-dev/1Panel/assets/61420215/f4726ba6-bf01-483b-b08e-cdecd671907b)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.5.1 版本已发布。
