### ISSUE TITLE
[FEATURE]添加 MySQL 远程数据库时，地址支持输入域名

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1916]
### 1Panel 版本

v1.5.0

### 请描述您的需求或者改进建议

添加 MySQL 远程数据库时，地址支持输入域名
![image](https://github.com/1Panel-dev/1Panel/assets/93708226/f25157dc-c6fa-40ae-a450-89aa1ef55f40)

### 请描述你建议的实现方案

添加 MySQL 远程数据库时，地址支持输入域名

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本支持在远程数据库地址栏输入域名。

**Comment by wanghe-fit2cloud** [comment]
v1.5.1 版本已发布。
