### ISSUE TITLE
[QUESTION]升级失败

### ISSUE THREAD

**Issue by W4J1e** [1Panel-dev/1Panel#1918]
### 请描述您的问题

刚更新的 v1.5.0 版本，提示有应用可升级，openresty 升级成功了，但是 qinglong 升级失败，提示文件不存在。
![image](https://github.com/1Panel-dev/1Panel/assets/74824162/7fc87a5d-db38-4261-bf7e-08de088d25c4)
进入安装目录可以看到：
![image](https://github.com/1Panel-dev/1Panel/assets/74824162/df9e089b-0fad-43cb-8fc7-8c4d8e8bd0ce)
访问该应用正常，但是我不记得登陆密码了。如果要解决升级失败的问题请问怎么办呢？
补充日志：
![image](https://github.com/1Panel-dev/1Panel/assets/74824162/e8aef967-c267-4f15-9222-c6a2a067a0df)
操作日志里显示的是升级成功：
![image](https://github.com/1Panel-dev/1Panel/assets/74824162/f3ae477b-fcac-4d2a-9685-f7da0d50fa81)

另外催一下下 #1643 ，辛苦有时间安排上。

**Comment by wanghe-fit2cloud** [comment]
青龙升级失败的问题，应该是最新版本镜像 pull 失败的问题。
1、进入 `主机` - `终端` 界面，手动拉取一下最新镜像：
```shell
docker pull whyour/qinglong:2.16.0
```
2、在已安装应用列表，点击一下 `重建` 按钮。
3、`容器` - `配置` 页面，可以添加镜像加速地址。

> 下个版本会针对应用升级到逻辑进行优化。

**Comment by W4J1e** [comment]
升级成功了，但是配置丢失了。
尝试使用升级前的备份恢复后，同样像新安装一样要注册账户。

**Comment by wanghe-fit2cloud** [comment]
> 升级成功了，但是配置丢失了。 尝试使用升级前的备份恢复后，同样像新安装一样要注册账户。

刚刚在本地环境没有复现应用升级后数据丢失的问题。

> 安装应用时，已经做了持久化处理（升级应用不会更改持久化目录内容）。

**Comment by W4J1e** [comment]
我也不清楚问题出在哪里，在还原备份后重新设置了用户名和密码，再次升级一样要重新设置。
`/opt/1panel/apps/qinglong/qinglong/data` 里除了一个空的 `data` 文件夹之外没有其它数据。
![image](https://github.com/1Panel-dev/1Panel/assets/74824162/314449fd-dfda-48f5-b2c3-85596ce94844)

**Comment by wanghe-fit2cloud** [comment]
1、容器内的持久化路径设置的不对，应该是默认的 `/ql/data`
2、当前版本，也不要手动修改宿主机持久化目录，推荐是默认的 `./data`
> 这样能确保在备份应用时数据不丢失（当前的备份逻辑还不会备份应用目录以外的文件夹）
---
<img width="745" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/659ef1b8-1c59-40ed-863c-eae02acc7692">

**Comment by wanghe-fit2cloud** [comment]
v1.5.1 版本已发布。

**Comment by coolmian** [comment]
当前运行版本：v1.6.2
![image](https://github.com/1Panel-dev/1Panel/assets/36444522/4df3b7e5-15ab-4dde-b399-178fd16a2400)
nextcloud也是一样的升级失败提示
手动pull最新镜像后点击重建，还是原来的版本

**Comment by wanghe-fit2cloud** [comment]
> 当前运行版本：v1.6.2 ![image](https://user-images.githubusercontent.com/36444522/273424136-4df3b7e5-15ab-4dde-b399-178fd16a2400.png) nextcloud也是一样的升级失败提示 手动pull最新镜像后点击重建，还是原来的版本

需要点击应用商店右上角的 `更新应用列表` 按钮。

**Comment by coolmian** [comment]
@wanghe-fit2cloud 
![image](https://github.com/1Panel-dev/1Panel/assets/36444522/369d1fe9-4581-4c1a-8318-fe3234f2f180)
点过了，结果还是一样的，版本没有升级
