### ISSUE TITLE
[BUG]OpenResty停止了，清理未使用容器时不小心清理了

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1920]
### 1Panel 版本

v1.5.0

### 问题描述

在应用商店创建的 OpenResty 手动停止了，在容器菜单清理未使用容器时不小心清理该容器，导致应用不能正常使用了。

### 重现步骤

停止 OpenResty 应用，进去容器菜单，点击 `清理容器` 按钮

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
这种情况可以进去 `应用商店` - `已安装` 列表，找到目标应用后，点击 `重建` 按钮。

后续版本我们也会针对上述问题做出优化。

**Comment by wanghe-fit2cloud** [comment]
v1.5.1 版本已发布。
