### ISSUE TITLE
[FEATURE]希望备份页面可看到备份文件的大小。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1922]
### 1Panel 版本

v1.5.0

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/93708226/f4f11f14-75db-42b4-9061-3ebd578398ad)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
