### ISSUE TITLE
[BUG]登录界面切换语言后，提示信息没有切换

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1923]
### 1Panel 版本

v1.5.0

### 问题描述

登录界面切换语言后，提示信息没有切换。
![image](https://github.com/1Panel-dev/1Panel/assets/93708226/30df93d7-20fa-43a9-868f-d8db817358d3)

### 重现步骤

进去系统登录页面，将系统语言切换到英文，输入错误的用户名密码后点击登录即可复现。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.5.1 版本已发布。
