### ISSUE TITLE
[FEATURE]希望远程数据库可以增加测试连接按钮

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1924]
### 1Panel 版本

v1.5.0

### 请描述您的需求或者改进建议

希望远程数据库可以增加测试连接按钮。

### 请描述你建议的实现方案

如 Navicat，输入完成后，有一个测试连接的按钮，验证账号密码是否正确。
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/d08cdf6f-fd4b-4f39-91c0-1caa358b814c)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。我们会在近期版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.5.1 版本已发布。
