### ISSUE TITLE
[BUG]添加远程数据库后，点击`从服务器获取`按钮，好像无法获取到数据库内容

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1925]
### 1Panel 版本

v1.5.0

### 问题描述

数据库版本：5.6.21
- 添加远程数据库后，点击 `从服务器获取` 按钮，好像无法获取到数据库内容，这个如何使用的？

![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/c11f90b8-6c23-45df-9841-8e55767a641b)

### 重现步骤

目前确认用户名和密码正确
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/0548ef64-db3f-4a65-93f6-cba06dc132cf)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
刚刚在本地环境测试了 MySQL 5.6 版本的远程数据库功能，可以将服务器上的数据库同步到系统中来。
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/a6a04b51-756e-492d-b4f4-70a1ad403565)

**Comment by drttcrh** [comment]
###### 我也遇到相同的错误
![image](https://github.com/1Panel-dev/1Panel/assets/13195127/76a97e72-571e-44f7-9b14-4a2d35f0a469)

**Comment by ssongliu** [comment]
> ###### 我也遇到相同的错误
> ![image](https://user-images.githubusercontent.com/13195127/260932255-76a97e72-571e-44f7-9b14-4a2d35f0a469.png)

你好，有添加社区群吗？想远程看一下这个问题。

**Comment by ssongliu** [comment]
问题应该是数据库是否区分大小写的问题，这里都是外部导入的数据库；
在执行 SELECT USER,HOST FROM mysql.DB 时出现错误。

**Comment by wanghe-fit2cloud** [comment]
v1.5.2 版本已发布。
