### ISSUE TITLE
[BUG]数据库管理，新增远程数据库，在安装应用时，选择数据库，只列出来默认的，没有远程的

### ISSUE THREAD

**Issue by liujunzheng** [1Panel-dev/1Panel#1929]
### 联系方式

QQ：823393100

### 1Panel 版本

1.5

### 问题描述

数据库管理，新增远程数据库，在安装应用时，选择数据库，只列出来默认的，没有远程的

### 重现步骤

1，数据库管理，新增远程数据库，
2，在安装应用时，选择数据库，只列出来默认的，没有远程的

**Comment by liujunzheng** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/72662734/dfc6cd42-10ff-43a2-990a-450b0907dbca)
![image](https://github.com/1Panel-dev/1Panel/assets/72662734/cd8a35f7-4c80-4b33-b1ae-e1d596876570)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
当前版本还不支持在创建应用时选择远程数据库。
> 计划是在远程数据库版本稳定运行几个版本后支持

**Comment by nyaasuki** [comment]
关注一下，我有同样的需求，因为我的数据全在远程数据库里没法迁移过来

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
