### ISSUE TITLE
[FEATURE]防火墙规则中，添加端口时候可以同时添加一个备注

### ISSUE THREAD

**Issue by maimai977977** [1Panel-dev/1Panel#1930]
### 1Panel 版本

v1.5.0

### 请描述您的需求或者改进建议

防火墙规则中，添加端口时候可以同时添加一个备注，这样可以方便了解，服务器端口被哪个占用

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
