### ISSUE TITLE
[FEATURE]希望可以增加对 OneDrive for Business 的支持。

### ISSUE THREAD

**Issue by 404gods** [1Panel-dev/1Panel#1931]
### 请描述您的问题

创建备份账号，选择OneDrive，登录授权后，填入 http://localhost/login/authorized?code= 后面的代码，一直报错：服务内部错误: no such access token in response，难道支持的不是OneDrive for business？

**Comment by ssongliu** [comment]
感谢反馈！添加备份账号的时候，勾选上国内版本试试

**Comment by 404gods** [comment]
> 感谢反馈！添加备份账号的时候，勾选上国内版本试试

选了国内版本更不行，直接提示没这个账户，我是微软E5，应该属于OneDrive for business，请看下是什么原因呢？谢谢

**Comment by 404gods** [comment]
补充一下：
用普通版的OneDrive账户可以添加备份账号，但只有5G空间，希望可以增加对OneDrive for business的支持

**Comment by ssongliu** [comment]
好的，我们先本地研究一下

**Comment by larkhover** [comment]
是支持OneDrive for Business，我就用的E5来备份

**Comment by 404gods** [comment]
> 是支持OneDrive for Business，我就用的E5来备份

不会吧，我试了好几个e5账号都不行，官方测试一下吧

**Comment by Gogoworks** [comment]
e5账号 OneDrive 不支持吗？

**Comment by 404gods** [comment]
> e5账号 OneDrive 不支持吗？

我试了是不支持，普通版本的试了支持

**Comment by dudt** [comment]
刚试了下 E5和你的情况一样提示[服务内部错误]: no such access token in response

**Comment by larkhover** [comment]
仔细看返还的token，不能直接复制过去，它有一部分多余的

**Comment by wanghe-fit2cloud** [comment]
> 仔细看返还的token，不能直接复制过去，它有一部分多余的

能截图说明一下就太好了。

**Comment by dudt** [comment]
已解决。

根据大佬说明我看了下code后面&session_state=这个和后面的不用复制，添加成功！

> 仔细看返还的token，不能直接复制过去，它有一部分多余的

**Comment by minyoad** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/115848/0051f4a7-584f-489f-8d05-ef6b919ab712)
无法获取token，登录后跳转，提示需要管理员批准，
对比之下，宝塔并不用，可以直接获取token

**Comment by ssongliu** [comment]
> ![image](https://user-images.githubusercontent.com/115848/262044355-0051f4a7-584f-489f-8d05-ef6b919ab712.png) 无法获取token，登录后跳转，提示需要管理员批准， 对比之下，宝塔并不用，可以直接获取token

有加社区群吗，可以远程看一下这个问题。

**Comment by wanghe-fit2cloud** [comment]
#3255
