### ISSUE TITLE
[BUG] 更改默认的mysql容器名之后，后台的连接信息并没有同步更改

### ISSUE THREAD

**Issue by M1saka10010** [1Panel-dev/1Panel#1932]
### 联系方式

admin@misaka.ren

### 1Panel 版本

1.5.0

### 问题描述

更改默认的mysql容器名之后，后台的连接信息并没有同步更改。安装的时候我把容器名设置成了mysql56。配置php的时候用后台显示的mysql这个地址死活连不上。折腾了半个钟发现用mysql56能直接连上。

### 重现步骤

如上

### 期待的正确结果

面板显示连接信息为mysql56

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
数据库列表中，`连接信息` 页面显示的容器地址是 `service_name:3306`。
> 如果两个容器在同一个 network 中，这时使用容器名称和服务名称均可以正常连接。

**Comment by M1saka10010** [comment]
> 数据库列表中，`连接信息` 页面显示的容器地址是 `service_name:3306`。
> 
> > 如果两个容器在同一个 network 中，这时使用容器名称和服务名称均可以正常连接。

最新版仍显示mysql而非mysql56

**Comment by wanghe-fit2cloud** [comment]
> > 数据库列表中，`连接信息` 页面显示的容器地址是 `service_name:3306`。
> > > 如果两个容器在同一个 network 中，这时使用容器名称和服务名称均可以正常连接。
> 
> 最新版仍显示mysql而非mysql56

是的，容器连接地址默认显示的是 service name

**Comment by M1saka10010** [comment]
> > > 数据库列表中，`连接信息` 页面显示的容器地址是 `service_name:3306`。
> > > > 如果两个容器在同一个 network 中，这时使用容器名称和服务名称均可以正常连接。
> > 
> > 
> > 最新版仍显示mysql而非mysql56
> 
> 是的，容器连接地址默认显示的是 service name

但是实际上确实会出现连接不上的情况，确实在同一个network里的
