### ISSUE TITLE
[FEATURE]远程数据库是否可以添加支持阿里云RDS之类的？

### ISSUE THREAD

**Issue by nyaasuki** [1Panel-dev/1Panel#1933]
### 1Panel 版本

1.5.0

### 请描述您的需求或者改进建议

远程数据库是否可以添加支持阿里云RDS之类的？

### 请描述你建议的实现方案

当前版本数据库地址能输入ip，而云数据库通常都是网址

**Comment by igophper** [comment]
可以提供更多的信息吗？例如在哪里的输入框，方便提供图片信息吗

**Comment by wanghe-fit2cloud** [comment]
> 可以提供更多的信息吗？例如在哪里的输入框，方便提供图片信息吗

<img width="1474" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/a8504681-0f79-48dc-a145-f5fd2f2697c8">

#### 下个版本 `v1.5.1` 就会支持该需求。

**Comment by wanghe-fit2cloud** [comment]
v1.5.1 版本已发布。
