### ISSUE TITLE
1Panel面板安装openresty显示80端口被占用

### ISSUE THREAD

**Issue by 1411430556** [1Panel-dev/1Panel#1940]
### 请描述您的问题

请问在1Panel面板安装openresty显示80端口被占用是怎么回事呢
![image](https://github.com/1Panel-dev/1Panel/assets/67215517/7ad5d091-3555-453f-96fa-ffa53f417174)

**Comment by lalalafff** [comment]
是不是之前安装过，如果安装过没有完全卸载 需要先删除之前的openresty容器

**Comment by 1411430556** [comment]
> 是不是之前安装过，如果安装过没有完全卸载 需要先删除之前的openresty容器

之前没有安装过应该，之前用的宝塔面板，现在就是通过端口号访问halo

**Comment by zhengkunwang223** [comment]
宝塔面板安装的 nginx 会占用 80 和 443 端口 导致冲突

**Comment by 1411430556** [comment]
好的，谢谢！🫡
