### ISSUE TITLE
[FEATURE]是否考虑在创建IP规则那里增加一个备注的描述

### ISSUE THREAD

**Issue by duguyue8** [1Panel-dev/1Panel#1941]
### 1Panel 版本

1.5.0

### 请描述您的需求或者改进建议

现在方向了某些IP，但是只有IP地址，不利于快速识别自己放行了哪些ip。

### 请描述你建议的实现方案

创建IP规则时，增加一个备注描述

**Comment by ssongliu** [comment]
感谢反馈！目前计划在九月份发布的 v1.6.0 版本实现上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
