### ISSUE TITLE
[QUESTION] 备份无法删除

### ISSUE THREAD

**Issue by iwenyi** [1Panel-dev/1Panel#1942]
### 请描述您的问题

从宝塔迁移到 1Panel 后，把之前网站备份内容通过**导入备份**导入，导入失败文件无法删除。
![屏幕截图 2023-08-14 102110](https://github.com/1Panel-dev/1Panel/assets/63294559/1d70ca22-94f8-4397-8d56-d27055346943)

**Comment by ssongliu** [comment]
感谢反馈！可以直接进入 主机 - 文件 菜单中，找到对应的文件手动删除一下。
