### ISSUE TITLE
[FEATURE]希望增加快照备份到本地

### ISSUE THREAD

**Issue by okxlin** [1Panel-dev/1Panel#1944]
### 1Panel 版本

v1.5.0

### 请描述您的需求或者改进建议

希望增加快照备份到本地，方便备份到本地存储块啥的。

内网环境等存在需求。

还有增加谷歌网盘也再好不过。#1041

**Comment by ssongliu** [comment]
感谢反馈！我们会在后续版本中考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
出于安全考虑，我们目前先不考虑支持将快照备份到本地。
> 可以使用 sftp 的方式来实现。
