### ISSUE TITLE
[BUG]应用商店重复应用去重与优化

### ISSUE THREAD

**Issue by okxlin** [1Panel-dev/1Panel#1945]
### 1Panel 版本

v1.5.0

### 1.  首次加载应用列表存在分类未加载

当第一次安装，且连接不上CDN分发的商店应用列表时，应用分类不显现
![image](https://github.com/1Panel-dev/1Panel/assets/61420215/0ffe9707-cd78-480a-8e92-a4d6bd1762ce)

### 2. 应用重复问题
连接不上分发的应用列表，遂从其他机子复制了一份`1panel.json`过来，以为是靠这个文件供应应用数据的，看起来好像不是。

但是当连接上，在线更新应用列表后，产生了应用重复的问题。
![image](https://github.com/1Panel-dev/1Panel/assets/61420215/5ad08344-cccf-4cff-845f-f470c9566053)
### 3. 请教关于如何正确导入官方应用商店列表
不是应用列表导入本地应用，毕竟本地应用不会被识别为正确的服务依赖。

而是如何在连接不上商店CDN的时候正确导入官方应用呢？

### 重现步骤

如上述

**Comment by zhengkunwang223** [comment]
是最新的 1.5.0 版本吗

**Comment by okxlin** [comment]
> 是最新的 1.5.0 版本吗


是的，最新1.5.0
