### ISSUE TITLE
[BUG]dockerd进程 CPU 占用异常

### ISSUE THREAD

**Issue by CyJaySong** [1Panel-dev/1Panel#1946]
### 联系方式

cyjaysong@gmail.com

### 1Panel 版本

1.5.0

### 问题描述

启动了一个RocketMQ 启动后，容器CPU占用正常， 但是dockerd进程的CPU占用一发不可收拾，几乎占满，即便是关闭了RocketMQ容器也这样

### 重现步骤

https://github.com/apache/rocketmq-docker/tree/master/templates/docker-compose

**Comment by ssongliu** [comment]
感谢反馈！当出现以下三种情况时，Docker 自带的日志切割可能会导致 CPU 暴涨：
- 切割过于频繁；
- 日志切割过程中导致文件损坏等；
- 日志增长过快。

可以重启 Docker 解决该问题。
