### ISSUE TITLE
[FEATURE]容器升级功能，如果本地没有将升级镜像的版本，建议自动拉取目标镜像。

### ISSUE THREAD

**Issue by canyanol650** [1Panel-dev/1Panel#1953]
### 1Panel 版本

v1.5.0

### 请描述您的需求或者改进建议

容器模块里容器升级功能，
![image](https://github.com/1Panel-dev/1Panel/assets/42194280/a6e0e950-bd0a-4177-b583-c4d26a5c01fc)

如果本地没有将升级镜像的版本，会报错。

建议自动拉取目标镜像，或者给用户选择先拉取再升级。

**Comment by ssongliu** [comment]
感谢反馈！ 我们在本地复现一下该问题。

**Comment by ssongliu** [comment]
感谢反馈！可以提供一下报错信息吗，这里应该是会自动去拉取新镜像的。

**Comment by ssongliu** [comment]
本地开发环境测试了一下，没有复现。
如果是原镜像是 latest 的话，需要勾选上强制拉取。

**Comment by canyanol650** [comment]
![1692256203043](https://github.com/1Panel-dev/1Panel/assets/42194280/28f37b31-45eb-432e-9337-2004445e34bc)
远程里有33版本,这里报错

然而 我如果是从这里编辑手动将版本改成33 保存. 就能成功更新到33版本.  这里用的是阿里云的容器仓库
![1692256373901](https://github.com/1Panel-dev/1Panel/assets/42194280/0b59916d-7c23-4c92-b026-fcc9f80fcc9b)

**Comment by ssongliu** [comment]
你好，你有加社区群吗？想远程看一下这个问题。

**Comment by clion007** [comment]
镜像版本是latest，勾选强制拉取，如果没有新版本，也会从新拉取镜像的吧？但实际上没有新的镜像，这不太符合升级的逻辑
