### ISSUE TITLE
[FEATURE]增加Nginx 或 Tengine

### ISSUE THREAD

**Issue by 7836246** [1Panel-dev/1Panel#1954]
### 1Panel 版本

v1.5.1

### 请描述您的需求或者改进建议

目前已有Web服务器 OpenResty 建议增加Nginx 或 Tengine
就像你添加了MySQL 也添加了 MariaDB  同样可以后续添加支持

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑是否增加其他类型的 Web 服务器。

**Comment by lifei6671** [comment]
> 感谢反馈，我们会在后续版本中考虑是否增加其他类型的 Web 服务器。

希望可以增加Caddy服务器。

**Comment by wanghe-fit2cloud** [comment]
现阶段会将主要精力放在 OpenResty，望理解。
目前，其他的 Web 服务器可以通过创建本地应用或者容器编排的方式来维护。
