### ISSUE TITLE
[BUG]当对网站设置了密码访问时，进入halo的后台管理页面登陆时出现bug

### ISSUE THREAD

**Issue by duguyue8** [1Panel-dev/1Panel#1955]
### 联系方式

1Panel交流群1

### 1Panel 版本

1.5.1

### 问题描述

可以访问下面的网站实际体验效果，密码验证框反复弹出：
https://llm.asia/console

### 重现步骤

访问上面的链接可以查看错误效果

**Comment by duguyue8** [comment]
上面网站用户名和密码都是admin

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在本地开发环境复现一下上述问题。

**Comment by zhengkunwang223** [comment]
您好 已复现此问题 当前不知道是 halo 的原因 还是 nginx 的原因 正在排查

**Comment by duguyue8** [comment]
> 您好 已复现此问题 当前不知道是 halo 的原因 还是 nginx 的原因 正在排查

好的，优秀！

**Comment by wanghe-fit2cloud** [comment]
当前版本，Halo 项目不支持单独在网站设置中开启密码访问。
