### ISSUE TITLE
[FEATURE] 因新版本移除了默认创建的admin用户, 即 1000:1000,建议在1Panel文档里的功能手册中添加相关说明

### ISSUE THREAD

**Issue by tianxidev** [1Panel-dev/1Panel#1956]
### 1Panel 版本

v1.5.1

### 请描述您的需求或者改进建议

因新版本移除了默认创建的admin用户, 即 1000:1000,建议在1Panel文档里的功能手册中添加相关说明

### 请描述你建议的实现方案

# 检查 www 用户
$ id www
id: www: no such user

# 添加 www 用户组
$ groupadd www
groupadd: group 'www' already exists

# 添加 www 用户
$ useradd -g www -s /sbin/nologin www

# 再次检查 www 用户
$ id www
uid=1001(www) gid=1000(www) 组=1000(www)

**Comment by wanghe-fit2cloud** [comment]
PHP 运行环境网站，容器内 uid gid 1000 是 www-data，如下图：
> issue 中描述的是这里吗？
<img width="1474" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/2f341f9c-5981-492d-a951-53ef561b59eb">

**Comment by tianxidev** [comment]
> PHP 运行环境网站，容器内 uid gid 1000 是 www-data，如下图：
> 
> > issue 中描述的是这里吗？
> 
> <img alt="image" width="1474" src="https://user-images.githubusercontent.com/46734380/260599171-2f341f9c-5981-492d-a951-53ef561b59eb.png">

宿主机 /etc/passwd，刚新建系统的是没有1000:1000的，昨晚生产换1panel对比发现的，旧版貌似会主动创建一个admin账户
![image](https://github.com/1Panel-dev/1Panel/assets/96690444/55f22dd3-b996-4483-b0e1-55365da76fcc)
![5585db1da1f4a15f6b28671b0b6e7ee](https://github.com/1Panel-dev/1Panel/assets/96690444/ff93c7d7-03ae-4cdb-9fee-1aa3a861b88d)

**Comment by tianxidev** [comment]
移除了思路是对的，把用户组交给用户来设置，回过头去看安装文档里没说这回事，我觉得还是有必要在文档中添加说明

**Comment by wanghe-fit2cloud** [comment]
> 移除了思路是对的，把用户组交给用户来设置，回过头去看安装文档里没说这回事，我觉得还是有必要在文档中添加说明

`运行用户/组` 后面的保存按钮是通过 chown -R 命令为持久化目录设置权限（是为了和容器内用户/组保持一致）。
> 不会在宿主机上创建任何用户/组
