### ISSUE TITLE
[FEATURE]希望未来能支持挂载/卸载硬盘

### ISSUE THREAD

**Issue by faruzanCN** [1Panel-dev/1Panel#1957]
### 1Panel 版本

V1.5.0

### 请描述您的需求或者改进建议

希望未来能支持挂载/卸载硬盘，包含本地磁盘和网络磁盘(比如smb)

### 请描述你建议的实现方案

![image](https://github.com/1Panel-dev/1Panel/assets/46319425/80a198af-d807-4797-aca0-2ba5c9ea7f5d)

casaos有类似功能，可以参考一下实现需要的内容或界面

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
磁盘相关需求的讨论，统一汇总到该 issue #1852
