### ISSUE TITLE
[FEATURE] 增加GPU相关的监控表盘，首页右下角的推荐应用可选择关闭

### ISSUE THREAD

**Issue by larkwins** [1Panel-dev/1Panel#1958]
### 1Panel 版本

最新

### 请描述您的需求或者改进建议

1. 增加GPU相关的监控表盘（表盘多了的话，加个分类吧），现在AI/LLM是风口，GPU监控是势在必行啊
2. 首页右下角的推荐应用可选择关闭

**Comment by zhengkunwang223** [comment]
感谢建议 
1.  硬件监控需要调研一下
2. 推荐应用不考虑关闭

**Comment by wanghe-fit2cloud** [comment]
GPU 相关需求的讨论，统一汇总到该 issue #431
