### ISSUE TITLE
建议nginx可以自定义主目录

### ISSUE THREAD

**Issue by wendao8469759** [1Panel-dev/1Panel#1959]
### 1Panel 版本

1.5.0

### 请描述您的需求或者改进建议

建议nginx可以自定义主目录

因为大多数情况下 会把静态的目录跟某一个项目放到一起， 如/opt/project/项目名/web/  

### 请描述你建议的实现方案

建议nginx可以自定义主目录

因为大多数情况下 会把静态的目录跟某一个项目放到一起， 如/opt/project/项目名/web/

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本我们会考虑实现此功能

**Comment by wendao8469759** [comment]
感谢！

**Comment by Muska-Ami** [comment]
不只是openresty，希望所有应用都能支持自定义目录，我手动迁移mysql数据库到另一个磁盘再在应用商店操作就找不到文件了，但是因为是容器所以还能监听运行状态

**Comment by wanghe-fit2cloud** [comment]
自定义目录等相关功能的讨论，统一汇总到该 issue #2783
