### ISSUE TITLE
[FEATURE] 短时间的计划任务导致 SQLite 写锁锁整张表，此时在“网站”选项进行查询网站时会提示写锁

### ISSUE THREAD

**Issue by tianxidev** [1Panel-dev/1Panel#1960]
### 1Panel 版本

v1.5.1

### 请描述您的需求或者改进建议

因项目业务的需要，有一个秒级别（5s）的定时任务, 定期轮询接口
经过简单的排查后，猜测1Panel的计划任务执行的相关状态信息似乎是写在了 SQLite 中，又因SQLite写锁特点是锁整张表而不是锁行，导致查询网站时提示数据库已被锁定
![5767fa944dc65843a2e305e6ae0f0cd](https://github.com/1Panel-dev/1Panel/assets/96690444/e778ef87-1f60-4e73-b20e-2f07346dca50)

一段时间后，面板也会高负载
![ed8dfad0e5c938716e274ecef460f89](https://github.com/1Panel-dev/1Panel/assets/96690444/83cfa55f-aa77-48d9-8d5d-1842994d7850)

放宽该计划任务后，再次查询网站列表之类的选项响应迅速不再提示数据库锁定，负载状态正常

### 请描述你建议的实现方案

建议考虑将计划任务相关状态，脚本等写文件，SQLite 中仅存储计划任务记录基础信息

**Comment by zhengkunwang223** [comment]
我们先在本地复现一下
