### ISSUE TITLE
希望增加java node maven svn服务端和客户端 activeMQ/Kafka等队列应用

### ISSUE THREAD

**Issue by qindeng** [1Panel-dev/1Panel#1961]
### 1Panel 版本

v1.5.1-alpha.4

### 请描述您的需求或者改进建议

希望增加java node maven svn服务端和客户端 activeMQ/Kafka等队列应用

**Comment by Dacong-wu** [comment]
到现在都没有Node，我已经放弃了

**Comment by zhengkunwang223** [comment]
> 到现在都没有Node，我已经放弃了

nodejs 用 PM2 管理可以吗

**Comment by wanghe-fit2cloud** [comment]
> 到现在都没有Node，我已经放弃了

v1.7.0 版本已经支持了 Node.js 运行环境。

**Comment by wanghe-fit2cloud** [comment]
> 希望增加java node maven svn服务端和客户端 activeMQ/Kafka等队列应用

Kafka 等中间件已经上架应用商店。
增加 Java 等运行环境后期版本会支持，重复 #748
