### ISSUE TITLE
[BUG]web服务配置ssl版本无效

### ISSUE THREAD

**Issue by Concises** [1Panel-dev/1Panel#1963]
### 联系方式

844404913@qq.com

### 1Panel 版本

1.5.1

### 问题描述

无论在站点中如何配置ssl_protocols 网站始终会使用TLS1.2
经过排查是00.default.conf配置导致的

### 重现步骤

修改任意一个网站配置中ssl_protocols TLSv1再次访问网站 查看https连接的协议版本

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。

**Comment by zhengkunwang223** [comment]
https://bbs.fit2cloud.com/t/topic/1923 参考这个修复
