### ISSUE TITLE
[BUG]Supervisor 管理器添加新任务后，会激活原来暂停状态的任务。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1964]
### 1Panel 版本

v1.5.1

### 问题描述

Supervisor 管理器添加新任务后，会激活原来暂停状态的任务。

### 重现步骤

Supervisor 管理器添加新任务后，会激活原来暂停状态的任务。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
刚刚在本地环境复现了上述问题，我们会在近期版本中修复。

**Comment by wanghe-fit2cloud** [comment]
v1.5.2 版本已发布。
