### ISSUE TITLE
[QUESTION] 快照恢复仅恢复了有在应用商店里的容器吗？

### ISSUE THREAD

**Issue by dudt** [1Panel-dev/1Panel#1965]
### 请描述您的问题

别的容器不会备份吗？

**Comment by dudt** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/19968269/19296849-1803-4a08-aa4a-dcb34cbb11fc)
还有 恢复快照后PHP环境不会恢复

**Comment by wanghe-fit2cloud** [comment]
> ### 请描述您的问题
> 别的容器不会备份吗？

这里和服务器自身的快照有所不同，该功能目前会备份 1Panel 的数据目录和应用商店中应用所需的镜像

**Comment by wanghe-fit2cloud** [comment]
> 还有 恢复快照后PHP环境不会恢复

只创建了运行环境，并没有创建 PHP 网站和该运行环境关联，是这样子吧？

**Comment by dudt** [comment]
> > ### 请描述您的问题
> > 别的容器不会备份吗？
> 
> 这里和服务器自身的快照有所不同，该功能目前会备份 1Panel 的数据目录和应用商店中应用所需的镜像

对的，别的容器没有备份



> > 还有 恢复快照后PHP环境不会恢复
> 
> 只创建了运行环境，并没有创建 PHP 网站和该运行环境关联，是这样子吧？

是的！

**Comment by wanghe-fit2cloud** [comment]
了解，后续版本支持备份 PHP 运行环境。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
