### ISSUE TITLE
[BUG]面板样式排列有误

### ISSUE THREAD

**Issue by Muska-Ami** [1Panel-dev/1Panel#1966]
### 联系方式

Telegram: @CNYANNTW

### 1Panel 版本

1.5.1

### 问题描述

面板部分显示样式有误 可能是z-index属性设置有误，如下图，正常应该是侧边栏在提示上方

![Screenshot_20230816_100936_com microsoft emmx](https://github.com/1Panel-dev/1Panel/assets/79651409/e1ce63ea-16dc-49ab-8293-90ec84a26e82)

### 重现步骤

打开如网站界面后打开侧边栏

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.5.2 版本已发布。
