### ISSUE TITLE
[BUG]进程守护Supervisor 状态异常

### ISSUE THREAD

**Issue by 7836246** [1Panel-dev/1Panel#1968]
### 联系方式

go7836246@gmail.com

### 1Panel 版本

v1.5.1

### 问题描述

进程守护Supervisor 状态异常 一直在转圈圈 不显示正常状态 导致无法观察状态 和停止某服务

发行版本 debian-12.1
内核版本 6.1.0-10-amd64
系统类型 x86_64

![image](https://github.com/1Panel-dev/1Panel/assets/65436665/dfb16d22-23b2-467a-b78a-9a6c97917a08)

第一次安装时版本 v.1.5.0 正常使用 并且是正常  后面更新v1.5.1 就一直转圈 不显示状态 我无线刷新 刷新N次 有一次会正常显示

![image](https://github.com/1Panel-dev/1Panel/assets/65436665/f5399871-27b4-462c-ba13-e19fdd34645c)

### 重现步骤

第一次安装时版本 v.1.5.0 正常使用 并且是正常  后面更新v1.5.1 就一直转圈 不显示状态 我无线刷新 刷新N次 有一次会正常显示

但是并不能确认是版本问题  只能最开始配置的时候 是正常的

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们会在后续版本中对 Debian 12 操作系统进行适配和优化。

**Comment by wanghe-fit2cloud** [comment]
v1.5.2 版本已发布。
