### ISSUE TITLE
[BUG] Amazon Linux 2/2023 一键安装失败

### ISSUE THREAD

**Issue by ensean** [1Panel-dev/1Panel#1969]
### 1Panel 版本

1.5.1

### 问题描述

通过脚本一键安装时，如下报错提示

```shell
...
设置 1Panel 安装目录（默认为/opt）：
[1Panel Log]: 您选择的安装路径为 /opt
[1Panel Log]: ... 在线安装 docker
# Executing docker install script, commit: c2de0811708b6d9015ed1a2c80f02c9b70c8ce7b

ERROR: Unsupported distribution 'amzn'

[1Panel Log]: ... 启动 docker
Failed to execute operation: No such file or directory
Failed to start docker.service: Unit not found.
[1Panel Log]: docker 安装失败
```

实测手工安装docker后，后续功能正常使用

### 重现步骤

1. 选择Amazon Linux 2/2023启动EC2
2. 运行一键安装脚本

### 期待的正确结果

Amazon Linux 正常安装1Panel。

### 附加信息

Amazon Linux docker安装方式

* Amazon Linux 2: `sudo amazon-linux-extras install docker -y`
* Amazon Linux 2023: `sudo dnf install docker -y`

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述问题是因为 docker 在线安装脚本不支持 Amazon Linux 导致的，这种情况就需要先手动安装好 docker 之后再来运行 1Panel 在线安装脚本（会跳过安装 docker 这步）
