### ISSUE TITLE
[BUG]防火墙里创建端口规则，选tcp/udp，里面放多个端口，面板里删不掉,只能使用命令删除

### ISSUE THREAD

**Issue by 1219ls** [1Panel-dev/1Panel#1970]
### 联系方式

1829861813@qq.com

### 1Panel 版本

1.5.1

### 问题描述

防火墙里创建端口规则，选tcp/udp，里面放多个端口，面板里删不掉,只能使用命令删除
<img width="602" alt="4969cd7df7dd8a8e013a4b455517c4a" src="https://github.com/1Panel-dev/1Panel/assets/125373290/04f5c80f-c848-4f19-ad14-6182677cfc42">

### 重现步骤

防火墙里创建端口规则，选tcp/udp，里面放多个端口，面板里删不掉,只能使用命令删除
<img width="602" alt="4969cd7df7dd8a8e013a4b455517c4a" src="https://github.com/1Panel-dev/1Panel/assets/125373290/04f5c80f-c848-4f19-ad14-6182677cfc42">

**Comment by ssongliu** [comment]
感谢反馈！本地开发环境已复现，下个版本解决该问题。

**Comment by SaintWe** [comment]
#1359  相同，已经存在很久了

**Comment by wanghe-fit2cloud** [comment]
v1.5.2 版本已发布。
