### ISSUE TITLE
[FEATURE]建议优化一下重定向里的目标URL显示。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1971]
### 1Panel 版本

v1.5.1

### 请描述您的需求或者改进建议

建议优化一下重定向里的目标URL显示。

![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/bb0cf094-2a4e-4e79-bda7-a16166646389)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.5.2 版本已发布。
