### ISSUE TITLE
[FEATURE]关于缓存文件优化

### ISSUE THREAD

**Issue by Muska-Ami** [1Panel-dev/1Panel#1972]
### 1Panel 版本

1.5.1

### 请描述您的需求或者改进建议

根据观察发现每次更新会在tmp目录下备份，但是并不会被删除，像小内存服务器面板更新多了服务器磁盘占用会越来越多最后占满，应该做保留最新和定期清理，防止临时文件占满服务器

### 请描述你建议的实现方案

添加一个界面管理缓存或者定期删除

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
当 1Panel 升级成功但新版本启动失败时，就需要使用该备份文件来人为恢复。
我们会在后续版本支持缓存文件清理功能。

**Comment by zyyfit** [comment]
面板设置中增加了缓存清理功能

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
