### ISSUE TITLE
[BUG]反向代理的二次编辑会使后端代理地址path丢失

### ISSUE THREAD

**Issue by okxlin** [1Panel-dev/1Panel#1976]
### 1Panel 版本

v1.5.1

### 问题描述

当后端地址填写带`path`路径时，

可视化界面，二次编辑反向代理，会使`path`丢失，覆盖还原成了`/`路径。

![image](https://github.com/1Panel-dev/1Panel/assets/61420215/167f20d3-9d4f-4715-aac4-16e5a9317ecd)

### 重现步骤

如上述

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.5.2 版本已发布。
