### ISSUE TITLE
[BUG] 应用商店的Halo和Gitea安装时的数据库下拉选择未能正确拾取环境下可用的数据库

### ISSUE THREAD

**Issue by LeavesSky** [1Panel-dev/1Panel#1978]
### 联系方式

1559935142@qq.com

### 1Panel 版本

1.5.1

### 问题描述

1. 安装Halo时，数据库不能选择PostgreSQL，但是编排好像支持选择（MySQL和PostgreSQL）`- --spring.sql.init.platform=${HALO_PLATFORM}`、`- --spring.r2dbc.url=r2dbc:pool:${HALO_PLATFORM}`；

2. 安装Gitea时后，进入其初始配置，可以选择PostgreSQL，但在面板无法选择，且编排文件已经写死`- GITEA__database__DB_TYPE=mysql`

### 重现步骤

Halo：
![image](https://github.com/1Panel-dev/1Panel/assets/32787330/97c2dcd5-404c-45b2-aa97-99076f66f51b)
![image](https://github.com/1Panel-dev/1Panel/assets/32787330/d150ad68-0cc9-45b1-b3c6-9cd898dadfcd)
Gitea：
![image](https://github.com/1Panel-dev/1Panel/assets/32787330/6dd914bd-cf41-4ec8-bd81-45ee935ca05e)
![image](https://github.com/1Panel-dev/1Panel/assets/32787330/f50b210a-a980-47ce-b4bf-fd4fbb8ae01e)

### 期待的正确结果

Halo和Gitea安装时的数据库下拉选择正确拾取环境下可用的数据库

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，目前应用商店中应用是要强依赖 MySQL。
后续版本会支持选择更多数据库。

**Comment by LeavesSky** [comment]
欧克，希望做大做强，这个产品太方便了

**Comment by wanghe-fit2cloud** [comment]
> 欧克，希望做大做强，这个产品太方便了

感谢支持。

**Comment by wc7086** [comment]
> 感谢反馈，目前应用商店中应用是要强依赖 MySQL。 后续版本会支持选择更多数据库。

强依赖 MySQL 不是一个好选择，在 MySQL 被甲骨文收购之后，很多应用都选择优先支持 Mariadb 或 PostgreSQL，希望对这两个数据库的支持能尽快提上日程。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
