### ISSUE TITLE
快照失败

### ISSUE THREAD

**Issue by 404gods** [1Panel-dev/1Panel#1982]
### 请描述您的问题

快照失败，第三方存储是OneDrive，OneDrive设置没问题，计划任务里备份都成功，服务器在国外也不存在网络问题。
经查，快照的文件好好地都躺在本地/opt/1panel/backup/system里，OneDrive上没有。
日志如下：
[ERROR] upload snapshot to OneDrive failed, err: Put "https://此处省略" read tcp [2606:8888:3:c7::a]:44334->[2620:1ec:812::8]:443: read: connection reset by peer

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦看一下快照文件的大小。
我们也在本地环境复现一下上述问题。

**Comment by 404gods** [comment]
> 感谢反馈，麻烦看一下快照文件的大小。 我们也在本地环境复现一下上述问题。

500多m

**Comment by ssongliu** [comment]
1.6 版本对快照进行了优化，可以升级后重试一下。
