### ISSUE TITLE
[FEATURE] 建议监听 Enter 键提交

### ISSUE THREAD

**Issue by SaintWe** [1Panel-dev/1Panel#1984]
### 1Panel 版本

1.5.0

### 请描述您的需求或者改进建议

建议在只有一个输入框时，可以使用 Enter 键直接提交

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们呢会在后续版本持续优化。

**Comment by ssongliu** [comment]
出于系统操作一致性考虑，所有表单都不会支持监听回车键提交，望理解。
