### ISSUE TITLE
[BUG] Docker Compose 创建问题

### ISSUE THREAD

**Issue by SaintWe** [1Panel-dev/1Panel#1985]
### 1Panel 版本

1.5.0

### 问题描述

自定义编排创建时，无法显示日志，点击取消后实际已经完成创建，但会显示为本地应用，而非 1Panel

在对应文件夹查看 compose.log 也是自己完成创建的

### 重现步骤

如上

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们已经在本地环境复现上述问题，将在v1.5.2 版本修复。

**Comment by wanghe-fit2cloud** [comment]
v1.5.2 版本已发布。
