### ISSUE TITLE
建议针对Docker安装1panel进行改进[FEATURE]

### ISSUE THREAD

**Issue by tangger2000** [1Panel-dev/1Panel#1989]
### 1Panel 版本

v1.5.1

### 请描述您的需求或者改进建议

当前的1panel一键式安装脚本，仅支持直接安装在主机上。可能存在部分人士有需求使用docker安装1panel，例如Unraid NAS的玩家。Unraid本身是没有systemctl这个东西的（他基于Slackware）。  
为了能够使用1panel，就只能类似宝塔那样通过Docker安装。但是1panel又是一个管理Docker的面板，因此可以考虑使用Docker out of Docker的方式打包Docker容器。  
我已经尝试性的打包好了一个目前v1.5.1能用的Docker镜像，可以查看[1panel-dood](https://github.com/tangger2000/1panel-dood)经过测试其在群晖和Unraid上运行得不错。  
我的技术能力有限，不能及时的维护该镜像，也恐难以跟上官方的节奏。我的目前的尝试只是提供了一个可行性论证，证明了这种DooD的方式是可行的。特别希望官方能够支持Docker安装的方式。

### 请描述你建议的实现方案

经过我的尝试，实现方法大致是依据DooD的方式实现的：
1. 首先修改install.sh文件
2. 然后编写Dockerfile构造一个基于Ubuntu的镜像，在配置镜像时，配置好相应需要的环境，主要时docker.sock的挂载。
3. 然后编写docker-compose.yml文件启动容器即可。  

关于这三份文件我在附加文件中列出，官方若感兴趣可以查看。

### 附加信息

# 1. install.sh
```sh
#!/bin/bash

CURRENT_DIR=$(
    cd "$(dirname "$0")"
    pwd
)

function log() {
    message="[1Panel Log]: $1 "
    echo -e "${message}" 2>&1 | tee -a ${CURRENT_DIR}/install.log
}

echo
cat << EOF
 ██╗    ██████╗  █████╗ ███╗   ██╗███████╗██╗     
███║    ██╔══██╗██╔══██╗████╗  ██║██╔════╝██║     
╚██║    ██████╔╝███████║██╔██╗ ██║█████╗  ██║     
 ██║    ██╔═══╝ ██╔══██║██║╚██╗██║██╔══╝  ██║     
 ██║    ██║     ██║  ██║██║ ╚████║███████╗███████╗
 ╚═╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝╚══════╝
EOF

log "======================= 开始安装 ======================="

function Prepare_System(){
    if which 1panel >/dev/null 2>&1; then
        log "1Panel Linux 服务器运维管理面板已安装，请勿重复安装"
        1panel
    fi
}

function Set_Dir(){
    if read -t 120 -p "设置 1Panel 安装目录（默认为/opt）：" PANEL_BASE_DIR;then
        if [[ "$PANEL_BASE_DIR" != "" ]];then
            if [[ "$PANEL_BASE_DIR" != /* ]];then
                log "请输入目录的完整路径"
                Set_Dir
            fi

            if [[ ! -d $PANEL_BASE_DIR ]];then
                mkdir -p $PANEL_BASE_DIR
                log "您选择的安装路径为 $PANEL_BASE_DIR"
            fi
        else
            PANEL_BASE_DIR=/opt
            log "您选择的安装路径为 $PANEL_BASE_DIR"
        fi
    else
        PANEL_BASE_DIR=/opt
        log "(设置超时，使用默认安装路径 /opt)"
    fi
}

function Install_Docker(){
    if which docker >/dev/null 2>&1; then
        log "检测到 Docker 已安装，跳过安装步骤"
        # log "启动 Docker "
        # systemctl start docker 2>&1 | tee -a ${CURRENT_DIR}/install.log
    else
    	log "检测到 Docker 未安装，请使用1panel-dood镜像"
    	
        # log "... 在线安装 docker"

        # curl -fsSL https://get.docker.com -o get-docker.sh 2>&1 | tee -a ${CURRENT_DIR}/install.log
        # if [[ ! -f get-docker.sh ]];then
        #     log "docker 在线安装脚本下载失败，请稍候重试"
        #     exit 1
        # fi
        # if [[ $(curl -s ipinfo.io/country) == "CN" ]]; then
        #     sh get-docker.sh --mirror Aliyun 2>&1 | tee -a ${CURRENT_DIR}/install.log
        # else
        #     sh get-docker.sh 2>&1 | tee -a ${CURRENT_DIR}/install.log
        # fi
        
        # log "... 启动 docker"
        # systemctl enable docker; systemctl daemon-reload; systemctl start docker 2>&1 | tee -a ${CURRENT_DIR}/install.log

        # docker_config_folder="/etc/docker"
        # if [[ ! -d "$docker_config_folder" ]];then
        #     mkdir -p "$docker_config_folder"
        # fi

        # docker version >/dev/null 2>&1
        # if [[ $? -ne 0 ]]; then
        #     log "docker 安装失败"
        #     exit 1
        # else
        #     log "docker 安装成功"
        # fi
    fi
}

function Install_Compose(){
    docker-compose version >/dev/null 2>&1
    if [[ $? -ne 0 ]]; then
        log "... 在线安装 docker-compose"
        
        arch=$(uname -m)
		if [ "$arch" == 'armv7l' ]; then
			arch='armv7'
		fi
		curl -L https://resource.fit2cloud.com/docker/compose/releases/download/v2.16.0/docker-compose-$(uname -s | tr A-Z a-z)-$arch -o /usr/local/bin/docker-compose 2>&1 | tee -a ${CURRENT_DIR}/install.log
        if [[ ! -f /usr/local/bin/docker-compose ]];then
            log "docker-compose 下载失败，请稍候重试"
            exit 1
        fi
        chmod +x /usr/local/bin/docker-compose
        ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

        docker-compose version >/dev/null 2>&1
        if [[ $? -ne 0 ]]; then
            log "docker-compose 安装失败"
            exit 1
        else
            log "docker-compose 安装成功"
        fi
    else
        compose_v=`docker-compose -v`
        if [[ $compose_v =~ 'docker-compose' ]];then
            read -p "检测到已安装 Docker Compose 版本较低（需大于等于 v2.0.0 版本），是否升级 [y/n] : " UPGRADE_DOCKER_COMPOSE
            if [[ "$UPGRADE_DOCKER_COMPOSE" == "Y" ]] || [[ "$UPGRADE_DOCKER_COMPOSE" == "y" ]]; then
                rm -rf /usr/local/bin/docker-compose /usr/bin/docker-compose
                Install_Compose
            else
                log "Docker Compose 版本为 $compose_v，可能会影响应用商店的正常使用"
            fi
        else
            log "检测到 Docker Compose 已安装，跳过安装步骤"
        fi
    fi
}

function Set_Port(){
    DEFAULT_PORT=16413
	PANEL_PORT=$DEFAULT_PORT
	
    # while true; do
    #     read -p "设置 1Panel 端口（默认为$DEFAULT_PORT）：" PANEL_PORT

    #     if [[ "$PANEL_PORT" == "" ]];then
    #         PANEL_PORT=$DEFAULT_PORT
    #     fi

    #     if ! [[ "$PANEL_PORT" =~ ^[1-9][0-9]{0,4}$ && "$PANEL_PORT" -le 65535 ]]; then
    #         echo "错误：输入的端口号必须在 1 到 65535 之间"
    #         continue
    #     fi

    #     log "您设置的端口为：$PANEL_PORT"
    #     break
    # done
}

function Set_Firewall(){
    if which firewall-cmd >/dev/null 2>&1; then
        if systemctl status firewalld | grep -q "Active: active" >/dev/null 2>&1;then
            log "防火墙开放 $PANEL_PORT 端口"
            firewall-cmd --zone=public --add-port=$PANEL_PORT/tcp --permanent
            firewall-cmd --reload
        else
            log "防火墙未开启，忽略端口开放"
        fi
    fi

    if which ufw >/dev/null 2>&1; then
        if systemctl status ufw | grep -q "Active: active" >/dev/null 2>&1;then
            log "防火墙开放 $PANEL_PORT 端口"
            ufw allow $PANEL_PORT/tcp
            ufw reload
        else
            log "防火墙未开启，忽略端口开放"
        fi
    fi
}

function Set_Username(){
    DEFAULT_USERNAME=`cat /dev/urandom | head -n 16 | md5sum | head -c 10`
	
	PANEL_USERNAME=1panel
	
    # while true; do
    #     read -p "设置 1Panel 用户名称（默认为$DEFAULT_USERNAME）：" PANEL_USERNAME

    #     if [[ "$PANEL_USERNAME" == "" ]];then
    #         PANEL_USERNAME=$DEFAULT_USERNAME
    #     fi

    #     if [[ ! "$PANEL_USERNAME" =~ ^[a-zA-Z0-9_]{3,30}$ ]]; then
    #         echo "错误：用户名称仅支持字母、数字、下划线，长度 3-30 位"
    #         continue
    #     fi

    #     log "您设置的用户名称为：$PANEL_USERNAME"
    #     break
    # done
}

function Set_Password(){
    DEFAULT_PASSWORD=`cat /dev/urandom | head -n 16 | md5sum | head -c 10`
	
	PANEL_PASSWORD=1panel

    # while true; do
    #     echo "设置 1Panel 用户密码（默认为$DEFAULT_PASSWORD）："
    #     read -s PANEL_PASSWORD

    #     if [[ "$PANEL_PASSWORD" == "" ]];then
    #         PANEL_PASSWORD=$DEFAULT_PASSWORD
    #     fi

    #     if [[ ! "$PANEL_PASSWORD" =~ ^[a-zA-Z0-9_!@#$%*,.?]{8,30}$ ]]; then
    #         echo "错误：用户密码仅支持字母、数字、特殊字符（!@#$%*_,.?），长度 8-30 位"
    #         continue
    #     fi

    #     break
    # done
}

function Init_Panel(){
    log "配置 1Panel Service"

    RUN_BASE_DIR=$PANEL_BASE_DIR/1panel
    mkdir -p $RUN_BASE_DIR
    rm -rf $RUN_BASE_DIR/*

    cd ${CURRENT_DIR}

    cp ./1panel /usr/local/bin && chmod +x /usr/local/bin/1panel
    if [[ ! -f /usr/bin/1panel ]]; then
        ln -s /usr/local/bin/1panel /usr/bin/1panel >/dev/null 2>&1
    fi

    cp ./1pctl /usr/local/bin && chmod +x /usr/local/bin/1pctl
    sed -i -e "s#BASE_DIR=.*#BASE_DIR=${PANEL_BASE_DIR}#g" /usr/local/bin/1pctl
    sed -i -e "s#ORIGINAL_PORT=.*#ORIGINAL_PORT=${PANEL_PORT}#g" /usr/local/bin/1pctl
    sed -i -e "s#ORIGINAL_USERNAME=.*#ORIGINAL_USERNAME=${PANEL_USERNAME}#g" /usr/local/bin/1pctl
    ESCAPED_PANEL_PASSWORD=$(echo "$PANEL_PASSWORD" | sed 's/[!@#$%*_,.?]/\\&/g')
    sed -i -e "s#ORIGINAL_PASSWORD=.*#ORIGINAL_PASSWORD=${ESCAPED_PANEL_PASSWORD}#g" /usr/local/bin/1pctl
    # PANEL_ENTRANCE=`cat /dev/urandom | head -n 16 | md5sum | head -c 10`
    PANEL_ENTRANCE=1panel
    sed -i -e "s#ORIGINAL_ENTRANCE=.*#ORIGINAL_ENTRANCE=${PANEL_ENTRANCE}#g" /usr/local/bin/1pctl
    if [[ ! -f /usr/bin/1pctl ]]; then
        ln -s /usr/local/bin/1pctl /usr/bin/1pctl >/dev/null 2>&1
    fi

    # cp ./1panel.service /etc/systemd/system

    # systemctl enable 1panel; systemctl daemon-reload 2>&1 | tee -a ${CURRENT_DIR}/install.log

    # log "启动 1Panel 服务"
    # systemctl start 1panel | tee -a ${CURRENT_DIR}/install.log
	
    # for b in {1..30}
    # do
    #     sleep 3
    #     # service_status=`systemctl status 1panel 2>&1 | grep Active`
    #     service_status=`service 1panel status 2>&1 | grep Active`
    #     if [[ $service_status == *running* ]];then
    #         log "1Panel 服务启动成功!"
    #         break;
    #     else
    #         log "1Panel 服务启动出错!"
    #         exit 1
    #     fi
    # done
}

function Show_Result(){
    log ""
    log "=================感谢您的耐心等待，安装已经完成=================="
    log ""
    log "请用浏览器访问面板:"
    log "面板地址: http://\$LOCAL_IP:$PANEL_PORT/$PANEL_ENTRANCE"
    log "用户名称: $PANEL_USERNAME"
    log "用户密码: $PANEL_PASSWORD"
    log ""
    log "项目官网: https://1panel.cn"
    log "项目文档: https://1panel.cn/docs"
    log "代码仓库: https://github.com/1Panel-dev/1Panel"
    log ""
    log "如果使用的是云服务器，请至安全组开放 $PANEL_PORT 端口"
    log ""
    log "================================================================"
}

function main(){
    Prepare_System
    Set_Dir
    Install_Docker
    Install_Compose
    Set_Port
    Set_Firewall
    Set_Username
    Set_Password
    Init_Panel
    Show_Result
}
main
```

# 2. Dockerfile
```
# 该Dockerfile用于构建1panel-dood。
# dood是指Docker out of Docker，其本质是在Docker容器内部直接使用主机的Docker而不是使用Docker容器内部的Docker
# dind是指Docker in Docker，其本质是在Docker容器内部进行套娃。

# 对于1panel而言，1panel软件本身是一个编译好的二进制程序文件，可以在任何对于架构的服务器上运行，
# 但在某些情况下[eg:群晖]，官方提供的安装程序不能很好的正常工作，而使用Docker安装就成为一种比较好的方式；
# 因此，我仅修改了官方的安装脚本，并编写了一个玩具式的Dockerfile和docker-compose文件，以供大家在Docker上安装1panel


# 使用ubuntu作为基础镜像
FROM ubuntu:latest

# 维护者信息
LABEL maintainer="2018211556@stu.cqupt.edu.cn"
LABEL description="1panel-dood"
LABEL version="1.5"

# 安装 Docker 及其依赖
RUN apt-get update && apt-get install ca-certificates curl gnupg dpkg wget unzip openssh-server -y && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
	chmod a+r /etc/apt/keyrings/docker.gpg && \
    echo \
	"deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
	"$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
	tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && apt-get install docker-ce-cli -y && \
	apt-get clean && rm -rf /var/lib/apt/lists/*

# 设置工作目录
WORKDIR /app

# 在容器中挂载主机上的 docker.sock
VOLUME /var/run/docker.sock

# 安装1panel
RUN cd /app && wget https://github.com/tangger2000/1panel-dood/raw/main/1panel-v1.5.1-linux-amd64.zip && \
	unzip 1panel-v1.5.1-linux-amd64.zip
```

# 3. docker-compose.yml
```
version: '3'
services:
  1panel-dood:
    image: tangger/1panel-dood:latest
    command: sh -c "echo <your_data_dir> | bash /app/1panel-v1.5.1-linux-amd64/install.sh"
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - <your_data_dir>:<your_data_dir>
    restart: always
```

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈，我们会在团队内部讨论上述方案的可行性。

**Comment by ty114514** [comment]
Good idea, like portainer

**Comment by okxlin** [comment]
> Good idea, like portainer

感谢楼主分享的好想法。

按我自己想法编译的多架构平台镜像已上线：

- https://github.com/okxlin/docker-1panel
- https://hub.docker.com/r/moelin/1panel

还有第三方应商店已上架`1Panel`🤪

- [1Panel 应用商店的非官方应用适配库](https://github.com/okxlin/appstore)

![image](https://github.com/1Panel-dev/1Panel/assets/61420215/5a78cb8b-a84d-43ed-9c1a-32313d6cca84)

**Comment by tangger2000** [comment]
非常好的做法，替换主程序似乎比我打包的方式更好。我准备archive我之前的仓库了。

**Comment by tangger2000** [comment]
我已经使用了docker-1panel，运行得不错。非常感谢 @okxlin 的贡献。同时也很高兴我的想法能够被大佬接受，现在起我就可以稳定使用1panel了。类似于unraid的其他nas用户也可以尝试将宝塔迁移到1panel了。

**Comment by gettionhub** [comment]
目前群晖测试能用，但挂载docker.sock与宿主机和群晖原本docker中的容器很多端口会冲突，不论使用 Docker Compose 和 Docker网络或Docker容器内部的端口隔离都特别繁琐，这并非长久之计，还是希望能有一个简单方便互相独立、互不干扰的Dind方案。

**Comment by okxlin** [comment]
> 目前群晖测试能用，但挂载docker.sock与宿主机和群晖原本docker中的容器很多端口会冲突，不论使用 Docker Compose 和 Docker网络或Docker容器内部的端口隔离都特别繁琐，这并非长久之计，还是希望能有一个简单方便互相独立、互不干扰的Dind方案。

只是类似`potainer`的作用。`docker`版`1panel`安装应用，实际就是相当于在宿主机新建容器呀，应用端口是否冲突，这不是安装应用的时候考虑的么……

**Comment by gettionhub** [comment]
> > 目前群晖测试能用，但挂载docker.sock与宿主机和群晖原本docker中的容器很多端口会冲突，不论使用 Docker Compose 和 Docker网络或Docker容器内部的端口隔离都特别繁琐，这并非长久之计，还是希望能有一个简单方便互相独立、互不干扰的Dind方案。
> 
> 只是类似的作用。版安装应用，实际就是相当于在宿主机新建容器呀，应用端口是否冲突，这不是安装应用的时候考虑的么......`potainer``docker``1panel`

所以采用Docker Compose和bridge隔离，端口映射会特别繁琐，有的一个容器要映射好几个端口，特别是容器多，忘记端口是常事。如果互相独立在，比如群晖的docker里部署宝塔，只需映射面板和WEB端口，宝塔里面再安装docker完全不受影响，宝塔里面需要的依赖用宝塔里面的docker部署，宿主机需要可以直接在宿主机的docker部署互不干扰。当然并非说现在这个方案不好，目前这种相对节省资源开销，我提到的只是应用场景不同，需求不同而已。

**Comment by okxlin** [comment]
> > > 目前群晖测试能用，但挂载docker.sock与宿主机和群晖原本docker中的容器很多端口会冲突，不论使用 Docker Compose 和 Docker网络或Docker容器内部的端口隔离都特别繁琐，这并非长久之计，还是希望能有一个简单方便互相独立、互不干扰的Dind方案。
> > 
> > 
> > 只是类似的作用。版安装应用，实际就是相当于在宿主机新建容器呀，应用端口是否冲突，这不是安装应用的时候考虑的么......`` potainer``docker``1panel ``
> 
> 所以采用Docker Compose和bridge隔离，端口映射会特别繁琐，有的一个容器要映射好几个端口，特别是容器多，忘记端口是常事。如果互相独立在，比如群晖的docker里部署宝塔，只需映射面板和WEB端口，宝塔里面再安装docker完全不受影响，宝塔里面需要的依赖用宝塔里面的docker部署，宿主机需要可以直接在宿主机的docker部署互不干扰。当然并非说现在这个方案不好，目前这种相对节省资源开销，我提到的只是应用场景不同，需求不同而已。

哦哦，你说的是嵌套模式的容器，我感觉这个有点危险，删除了最顶层的，其他底层安装的就全没了。

实际平常安装时`docker`端口冲突，会有提示，`1panel`也有安装时端口冲突检测，`1panel`容器管理页面也可以看现有容器端口桥接映射的状况。

不过确实，嵌套模式也是一种需求。

**Comment by AlanWang2333** [comment]
> > Good idea, like portainer
> 
> 感谢楼主分享的好想法。
> 
> 按我自己想法编译的多架构平台镜像已上线：
> 
> * https://github.com/okxlin/docker-1panel
> * https://hub.docker.com/r/moelin/1panel
> 
> 还有第三方应商店已上架`1Panel`🤪
> 
> * [1Panel 应用商店的非官方应用适配库](https://github.com/okxlin/appstore)
> 
> ![image](https://private-user-images.githubusercontent.com/61420215/261846542-5a78cb8b-a84d-43ed-9c1a-32313d6cca84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDQ3MTcsIm5iZiI6MTcwNTI0NDQxNywicGF0aCI6Ii82MTQyMDIxNS8yNjE4NDY1NDItNWE3OGNiOGItYTg0ZC00M2VkLTljMWEtMzIzMTNkNmNjYTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDE1MDAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZjY5ZGI2NzAyMGZmZmNlNWI5M2NlODVmNmI4YmQyYjYyOTE3NmZkZWMwZjk1ZjEwNmY1OTEzNTMxMzAxZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B38hsFSEHmrTbK-awe6aS4iK8LayrhXMkej8f5TbN_0)

大佬这种方式部署的能看到本地文件目录吗，我的好像读取不到/mnt下面的目录，所以不能使用他的定时备份本地目录文件

**Comment by docker-master** [comment]
> > Good idea, like portainer
> 
> 感谢楼主分享的好想法。
> 
> 按我自己想法编译的多架构平台镜像已上线：
> 
> * https://github.com/okxlin/docker-1panel
> * https://hub.docker.com/r/moelin/1panel
> 
> 还有第三方应商店已上架`1Panel`🤪
> 
> * [1Panel 应用商店的非官方应用适配库](https://github.com/okxlin/appstore)
> 
> ![image](https://private-user-images.githubusercontent.com/61420215/261846542-5a78cb8b-a84d-43ed-9c1a-32313d6cca84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDQ3MTcsIm5iZiI6MTcwNTI0NDQxNywicGF0aCI6Ii82MTQyMDIxNS8yNjE4NDY1NDItNWE3OGNiOGItYTg0ZC00M2VkLTljMWEtMzIzMTNkNmNjYTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDE1MDAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZjY5ZGI2NzAyMGZmZmNlNWI5M2NlODVmNmI4YmQyYjYyOTE3NmZkZWMwZjk1ZjEwNmY1OTEzNTMxMzAxZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B38hsFSEHmrTbK-awe6aS4iK8LayrhXMkej8f5TbN_0)

大佬，我用docker部署了。
你的能看到本地文件目录吗，我的好像读取不到/mnt下面的目录，
所以不能使用他的定时备份本地目录文件，很可惜，想要这个功能
用的x86的openwrt，istoreos，求教
![mnt目录](https://github.com/1Panel-dev/1Panel/assets/58912611/0350632c-7b09-47c9-8a55-233a590c91f4)

**Comment by okxlin** [comment]
> > > Good idea, like portainer
> > 
> > 
> > 感谢楼主分享的好想法。
> > 按我自己想法编译的多架构平台镜像已上线：
> > 
> > * https://github.com/okxlin/docker-1panel
> > * https://hub.docker.com/r/moelin/1panel
> > 
> > 还有第三方应商店已上架`1Panel`🤪
> > 
> > * [1Panel 应用商店的非官方应用适配库](https://github.com/okxlin/appstore)
> > 
> > ![image](https://private-user-images.githubusercontent.com/61420215/261846542-5a78cb8b-a84d-43ed-9c1a-32313d6cca84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDQ3MTcsIm5iZiI6MTcwNTI0NDQxNywicGF0aCI6Ii82MTQyMDIxNS8yNjE4NDY1NDItNWE3OGNiOGItYTg0ZC00M2VkLTljMWEtMzIzMTNkNmNjYTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDE1MDAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZjY5ZGI2NzAyMGZmZmNlNWI5M2NlODVmNmI4YmQyYjYyOTE3NmZkZWMwZjk1ZjEwNmY1OTEzNTMxMzAxZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B38hsFSEHmrTbK-awe6aS4iK8LayrhXMkej8f5TbN_0)
> 
> 大佬，我用docker部署了。 你的能看到本地文件目录吗，我的好像读取不到/mnt下面的目录， 所以不能使用他的定时备份本地目录文件，很可惜，想要这个功能 用的x86的openwrt，istoreos，求教 ![mnt目录](https://private-user-images.githubusercontent.com/58912611/296573125-0350632c-7b09-47c9-8a55-233a590c91f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyNDY4MDksIm5iZiI6MTcwNTI0NjUwOSwicGF0aCI6Ii81ODkxMjYxMS8yOTY1NzMxMjUtMDM1MDYzMmMtN2IwOS00N2M5LThhNTUtMjMzYTU5MGM5MWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDE1MzUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ZjVhYzdkOWVhNDM3NGYxYmE4ZGEwYTU0NTk5MTMyNjk0OTFlOGFjNTFmYTJhNTllODdkMjkxMjg3YjQ4ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iF094KxlmPTH1BtlcUqGc_ZxJ1ee4IayqrDNFVGh2cc)

https://github.com/okxlin/docker-1panel/issues/5
