### ISSUE TITLE
OpenResty反向代理java后端接口，返回502 Bad Gateway

### ISSUE THREAD

**Issue by waves86** [1Panel-dev/1Panel#1990]
### 请描述您的问题

OpenResty反向代理java后端接口，返回502 Bad Gateway

![image](https://github.com/1Panel-dev/1Panel/assets/45849273/d59202c2-9957-4ce3-b8a3-46eef50902d5)

![image](https://github.com/1Panel-dev/1Panel/assets/45849273/d1ea73cd-19d5-444a-9eaa-90816a735760)

![image](https://github.com/1Panel-dev/1Panel/assets/45849273/88a6aaca-9b43-4549-8e82-609da57ffd0e)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，你可以点击编辑按钮，将前端请求路径修改为默认值 `/` 试一下。

**Comment by waves86** [comment]
@wanghe-fit2cloud 没用，我直接域名代理接口返回还是502
![image](https://github.com/1Panel-dev/1Panel/assets/45849273/a612f13b-1dfd-4b41-8b01-bec42f728d24)
![image](https://github.com/1Panel-dev/1Panel/assets/45849273/26651825-89f7-4acf-aaee-36532c8f578e)

**Comment by waves86** [comment]
@wanghe-fit2cloud 这是nginx报错日志 ，ip和域名我隐藏了一下，谢谢您，能否帮忙解决一下
2023/08/17 21:00:15 [error] 10#10: *203 upstream sent invalid header: "Access-Control-Expose-Headers\x20..." while reading response header from upstream, client: 117.*.*.*, server: test111.*.com, request: "GET / HTTP/2.0", upstream: "http://127.0.0.1:10900/", host: "test111.*.com"

**Comment by Muska-Ami** [comment]
上游Java项目返回无效标头了，应该是Java项目的问题

**Comment by waves86** [comment]
@XiaMoHuaHuo-CN 谢谢，我去试试
