### ISSUE TITLE
[BUG] 远端数据库数据没有进行去重

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#1992]
### 1Panel 版本

最新版1.5.2

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/51264840/770ca527-61bd-4107-b4e1-702404c6d361)
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/ca10dee4-8e3d-4926-9389-a6a322e65be4)

获取远程服务器数据重复

### 重现步骤

尝试获取远端数据库失败后， 再次点击获取， 然后还是失败， 然后就没在进行测试， 然后下班回到家中打开面板，神奇的是获取到了远端数据库(这次没有点击从服务器获取 按钮)， 就凭空出现了
获取失败的原因可能是我的服务器是国内的， 我远程的服务器是国外

### 期待的正确结果

对数据进行去重

**Comment by 9a6c** [comment]
我记得在很早之前(2个月前)我使用该用户是可以通过show databases; 来查看有哪些数据库，现在很多数据库都不显示了，不知道为什么
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/047eb667-14dd-4c26-8897-2b49eb22c646)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地开发环境复现一下上述问题。

**Comment by ssongliu** [comment]
同步失败是说超时吗，数据量多大？

**Comment by 9a6c** [comment]
忘记了， 获取的时候转了挺久，然后出来一个错误提示信息

**Comment by 9a6c** [comment]
数据量的话，可能不是很大， 这个数据库是正式服和测试服的部分数据， 游戏数据不多

**Comment by 9a6c** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/67fef983-2dfd-47d6-a336-941914dced5c)
获取的时候会改变用户权限吗？  我之前使用该用户可以正常获取到所有数据库，现在只能获取到部分数据库(使用的navicat)

**Comment by 9a6c** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/5b2d436a-36eb-44f4-b1b5-3476afa7071f)
理论上应该和这个数据库差不多的结构

**Comment by 9a6c** [comment]
我想删除后从新获取复现这个问题， 但是好像用户权限被改变了，很多数据库都看不到了，不知道为什么
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/687c5e70-016a-4b0e-914b-8918fb754bae)

**Comment by 9a6c** [comment]
好像把我数据库给删了
![1](https://github.com/1Panel-dev/1Panel/assets/51264840/1247df7d-bc14-421f-95fc-75cefd81bc29)
![2](https://github.com/1Panel-dev/1Panel/assets/51264840/4d7517f7-ad7e-45c8-83ab-ec2941f398e2)

**Comment by 9a6c** [comment]
丢失的数据库数据量应该都是多的， 丢失了game数据库和game_log数据库， 一共4个， 虽然是测试服的数据库丢了影响不大，但这样感觉不是很好？

**Comment by ssongliu** [comment]
同步数据不会修改用户权限，你有加社区群吗？可以远程看一下这个问题。

**Comment by 9a6c** [comment]
没有社区群，怎么加？

**Comment by ssongliu** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/f8c35d4d-65c1-4a6f-8ae1-199af015ad06)
扫描这个二维码

**Comment by 9a6c** [comment]
加了

**Comment by wanghe-fit2cloud** [comment]
v1.5.3 版本已发布。
