### ISSUE TITLE
[BUG]乌邦图22.0系统部署服务修改端口后无法正常使用

### ISSUE THREAD

**Issue by zorn-zhao** [1Panel-dev/1Panel#1993]
### 1Panel 版本

乌邦图22.0系统

### 问题描述

1、乌邦图22.0系统部署服务修改端口后无法正常使用，只能使用1Panel默认的端口
2、只能监控本地主机吗？其他主机只有SSH连一下的作用？

### 重现步骤

乌邦图22.0系统可复现

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1Panel 安装脚本中，默认给出的端口也是随机生成的，和自己指定的端口是一样的逻辑。
- `1pctl status` 命令查看一下系统运行状态。
- `netstat -ntlp` 命令查看一下端口绑定情况。
- `sysctl net.ipv6.bindv6only` 命令查看 bindv6only 参数值。
