### ISSUE TITLE
[BUG] 创建MINIO备份账号时，不能使用非443端口的MINIO服务

### ISSUE THREAD

**Issue by thlz998** [1Panel-dev/1Panel#1994]
### 联系方式

thlz998@gmail.com

### 1Panel 版本

v1.5.2

### 问题描述

<img width="539" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/36218343/c349df65-85b5-43f4-9389-36ddedecb173">

已有MINIO服务，MINIO的https端口非标准的443端口，Endpoint输入的为域名:端口，例如：baidu.com:2332

则会出现连接错误

### 重现步骤

1、部署一个MINIO服务，端口非80或443，并且保证服务可用可上传文件，其他MINIO客户端或AWS s3服务也都连接正常
2、在1Panel 创建创建备份账号，选择MINIO
3、Access Key ID、Secret Key正常填写
4、Endpoint填写IP或域名:端口，例如：baidu.com:2332
5、选择获取桶，出现错误：服务内部错误: S3 API Requests must be made to API port.

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by cyril-cheng** [comment]
亲测，非标准端口在1panel备份账号是可以用的。halo的s3插件不能用。

**Comment by wanghe-fit2cloud** [comment]
看错误信息，应该是 Endpoint 要使用 API 端口，而不是 Console 控制台的端口。
