### ISSUE TITLE
[FEATURE]建议增加支持自定义编译的加密组件swoole_loader.so

### ISSUE THREAD

**Issue by broommonk** [1Panel-dev/1Panel#1995]
### 1Panel 版本

1.5.2

### 请描述您的需求或者改进建议

很多商业php程序，包括wp的模板，都会使用一个加密组件：swoole_loader，
而且它是分php版本，以及一些授权的特别定制版，
也就是说，这个swoole_loader.so，有些会带多一个授权文件，
在php.ini里面加载这个加密组件和授权文件，
[swoole_loader]
extension = /www/server/php/72/lib/php/extensions/no-debug-non-zts-20170718/swoole_loader72.so
extension = //www/server/php/72/lib/php/extensions/no-debug-non-zts-20170718/swoole_loader72.licxx

授权文件忘了叫啥来的（swoole_loader72.licxx是举例），也是添加到这个php.ini里面的。
如果没有这个加密组件，这些商业程序是无法运行的。

### 请描述你建议的实现方案

我不知道如何实现，在某塔就是拷贝文件进去，修改php.ini，然后重启php-pfm就行了。

### 附加信息

希望早日实现，迁移php站点过来1panel

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在后续版本先调研一下上述需求的可行性方案。

**Comment by zhengkunwang223** [comment]
https://bbs.fit2cloud.com/t/topic/2073 参考这个进行设置
