### ISSUE TITLE
[BUG]绑定其他端口的多个域名，提示端口占用

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#1997]
### 1Panel 版本

v1.5.2

### 问题描述

手动在配置文件里用，88端口多域名可以，用面板新增域名不行。

![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/ab8589ab-f0aa-4eff-9dbd-ee74e298eb36)
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/a725a119-955e-4276-9540-b1fafc27da65)

### 重现步骤

网站设置 - 域名设置
添加域名指定相同端口

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
