### ISSUE TITLE
[BUG]当Redis-Commander停止时在已安装应用页面redis也会错误显示停止

### ISSUE THREAD

**Issue by okxlin** [1Panel-dev/1Panel#1998]
### 1Panel 版本

v1.5.2

### 问题描述

当`Redis-Commander`手动停止时在已安装应用页面`redis`也会错误显示停止；

实际`redis`是正常运行的。

![image](https://github.com/1Panel-dev/1Panel/assets/61420215/26135e3b-3fb7-49f8-aa0b-0235e3fb4e29)

### 重现步骤

如上述

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述问题没有在开发测试环境复现。

**Comment by okxlin** [comment]
重复复现了，都是新环境

![image](https://github.com/1Panel-dev/1Panel/assets/61420215/00182160-cc72-4155-bf4b-d67b539ad870)
<img width="1920" alt="Snipaste_2023-08-23_12-40-03" src="https://github.com/1Panel-dev/1Panel/assets/61420215/7a56f604-8e4d-4edb-8087-3e29b95cf622">

**Comment by ssongliu** [comment]
1.7 版本计划支持多 redis，直接移除 redis 和 redis-commander 之间的关联关系。

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
