### ISSUE TITLE
[BUG]清空容器日志，dockerd进程CPU占用异常

### ISSUE THREAD

**Issue by SH1KRA** [1Panel-dev/1Panel#1999]
### 联系方式

qq2439947537@gmail.com

### 1Panel 版本

v1.5.2

### 问题描述

清空任意容器日志，导致dockerd进程CPU占用异常，手动重启docker服务可恢复。

### 重现步骤

![1](https://github.com/1Panel-dev/1Panel/assets/88370611/1167873b-b3df-4d8c-af34-35395647cd66)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.5.3 版本已发布。
