### ISSUE TITLE
[BUG]在使用自动脚本运行的时候，shell脚本显示exit status 126（已经使用绝对路径），直接用php后面加相对路径则不会报126

### ISSUE THREAD

**Issue by ltzXiaoYanMo** [1Panel-dev/1Panel#2001]
### 联系方式

交流群3，为了碎银几两

### 1Panel 版本

1.5.2

### 问题描述

在使用自动脚本运行的时候，php脚本显示exit status 126（已经使用绝对路径），直接用php后面加相对路径则不会报126

### 重现步骤

新建Shell脚本任务：
在容器中运行
cd /sites/adminvip/index/ && php think version

### 期待的正确结果

若是1Panel自身出现问题改了就完事，若是我们这边自身出问题我们改正就行

### 相关日志输出

```shell
exit status 126
```

**Comment by ssongliu** [comment]
感谢反馈！这里实际上执行的是 docker exec <container> cd /sites/adminvip/index/ && php think version 命令。

而 cd 不是可执行文件，cd 是 shell 的内置命令，无法直接在 exec 中执行。

**Comment by ltzXiaoYanMo** [comment]
感谢提醒！我算也学到了一些
