### ISSUE TITLE
[FEATURE]希望优化下php运行环境

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#2002]
### 1Panel 版本

1.5.2

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/51264840/7ad7e13f-cf0d-4c8d-8a2b-84c88fa4f8db)
最近需要搭建新的服务器，然后它使用的宝塔， 然后我想改成1panel去搭建， 搭建过程中遇到很多问题， 如网站目前只能设置二级目录，并不能自定义设置目录， 然后就是php运行环境需要自己安装扩展，然后我是一个一个尝试，最后才搭建好了网站，而且很繁琐

### 请描述你建议的实现方案

1.希望php环境创建完成后就可以直接使用，自己选扩展太麻烦了， 我一开是手动选了几个如mysql redis等扩展，然后尝试还是不行，然后就在选几个，尝试了几次后还是打不开网站， 就直接将所有扩展全部安装了，整个过程太繁琐麻烦了
2. 希望可以自定义网站目录，或者在原来二级目录的基础上可以在选择里面的子目录，  如: 可以选择 index/gm/gm2   类似这样的
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/bf4692d4-01da-44f6-b632-f83470124d94)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
- 由于 1Panel 是采用容器化方案创建的 PHP 运行环境（每个运行环境对应一个 docker 镜像），因此会因为扩展的多少导致镜像大小不同、构建时间长短不同等问题。
> 我们会在后续版本探讨最优解。
- 设置网站二级目录不支持子目录的问题，我们会在后续版本优化。

**Comment by 9a6c** [comment]
感谢， 希望需求2可以尽快支持， 这样对部署老项目来说比较友好，不需要修改代码

**Comment by wanghe-fit2cloud** [comment]
最新版本已支持设置 index/gm/gm2。
