### ISSUE TITLE
[FEATURE]个人感觉可以新增如下备份协议webdav, smb 这两个协议

### ISSUE THREAD

**Issue by wxhdrsa7** [1Panel-dev/1Panel#2004]
### 1Panel 版本

1.5.2

### 请描述您的需求或者改进建议

个人感觉可以新增如下备份协议

webdav
smb
这两个协议适合内网使用。比如我内网有物理机安装了1panel，就可以备份到同内网的群晖nas上；也有部分支持webdav协议的云盘。

如果可以，感觉支持百度网盘也不是不行

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑是否支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复 #367
