### ISSUE TITLE
[QUESTION]安装失败

### ISSUE THREAD

**Issue by VeryAtao** [1Panel-dev/1Panel#2005]
### 请描述您的问题

[1Panel Log]: ... 启动 docker 
Failed to enable unit: Unit file docker.service does not exist.
Failed to start docker.service: Unit docker.service not found.
[1Panel Log]: docker 安装失败

**Comment by wanghe-fit2cloud** [comment]
上述问题是因为在线安装 docker 失败。
这种情况可以先手动安装 docker，之后再运行 1Panel 在线安装脚本时会跳过安装 docker 步骤。

可以参考这个脚本来安装 docker：
```shell
bash <(curl -sSL https://linuxmirrors.cn/docker.sh)
```
