### ISSUE TITLE
[FEATURE]应用商店里的应用如果支持数据库，最好可以跟数据库链接

### ISSUE THREAD

**Issue by BruceSuen720** [1Panel-dev/1Panel#2006]
### 1Panel 版本

1.5.2

### 请描述您的需求或者改进建议

应用商店中很多应用，例如Bitwarden一类的应用都支持将数据保存在数据库中，建议官方应用商店可以适配使用数据库的版本，以提升性能及数据安全性，目前的备份功能还不能自动进行应用备份，但可以进行数据库备份。将重要数据存在数据库中可以保证数据的安全性
如果应用也可以实现自动备份就更好了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本会支持在计划任务中添加应用备份功能。

**Comment by zyyfit** [comment]
1.6.0已增加应用备份功能

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
