### ISSUE TITLE
[QUESTION]概览面板突然无法访问了

### ISSUE THREAD

**Issue by Fins03** [1Panel-dev/1Panel#2007]
### 请描述您的问题

概览面板突然无法访问了
runtime error: index out of range [0] with length 0
runtime/panic.go:113 (0x45267)
github.com/1Panel-dev/1Panel/backend/app/service/dashboard.go:67 (0x155eb3f)
github.com/1Panel-dev/1Panel/backend/app/api/v1/dashboard.go:31 (0x182f11b)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x1803cdf)
github.com/1Panel-dev/1Panel/backend/middleware/password_expired.go:24 (0x1803ab0)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x1803927)
github.com/1Panel-dev/1Panel/backend/middleware/session.go:36 (0x18038a4)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x18056b3)
github.com/1Panel-dev/1Panel/backend/middleware/jwt.go:15 (0x180558c)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x18054e7)
github.com/1Panel-dev/1Panel/backend/middleware/loading.go:22 (0x1805474)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x1805eab)
github.com/1Panel-dev/1Panel/backend/middleware/bind_domain.go:22 (0x1805d28)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x180599b)
github.com/1Panel-dev/1Panel/backend/middleware/ip_limit.go:23 (0x18057d8)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x18052bf)
github.com/1Panel-dev/1Panel/backend/middleware/operation.go:25 (0x1803de0)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x51687b)
github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x51685c)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x515b5b)
github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x515b38)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x514c9b)
github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x5149c4)
github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x5145c3)
net/http/server.go:2936 (0x34602f)
net/http/server.go:1995 (0x341e07)
runtime/asm_arm64.s:1172 (0x7d6d3)
␛[0m

**Comment by Fins03** [comment]
上面我也不知道错误什么
![vava](https://github.com/1Panel-dev/1Panel/assets/42291925/c9dd053a-fee6-42b4-8ce0-1fc12ec3043e)

**Comment by wanghe-fit2cloud** [comment]
1Panel 服务器是什么操作系统？可以用下面的命令查看一下：
```shell
cat /etc/os-release
```

可以先重启一下 1Panel，看服务是否回复正常：
```shell
suto 1pctl restart
```
