### ISSUE TITLE
[FEATURE]公安备案日志需求：把面板日志，登录日志，网站日志进行备份到OneDrive

### ISSUE THREAD

**Issue by wxhdrsa7** [1Panel-dev/1Panel#2008]
### 1Panel 版本

1.5.2

### 请描述您的需求或者改进建议

这个对于我来说特别需要，因为进行公安备案，有一个安全风险报告需要填写，大概就是需要提供至少180天的日志。
可以查看这篇文章里面的安全评估报告:https://zhuanlan.zhihu.com/p/162909864
有7条需要填写，里面大部分需要提供这些日志

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by maninhill** [comment]
很好的需求。

**Comment by alienwaredream** [comment]
能传输到阿里云日志服务应该更好些

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
