### ISSUE TITLE
[BUG] 因<html lang="en">导致在中文chrome下会触发翻译

### ISSUE THREAD

**Issue by AliusLeeOuO** [1Panel-dev/1Panel#2010]
### 1Panel 版本

1.5.2

### 问题描述

因<html lang="en">导致在中文chrome下会触发翻译

### 重现步骤

进入1panel面板

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.5.3 版本已发布，可以将 1Panel 升级到最新版本后再来验证一下上述问题。
