### ISSUE TITLE
[FEATURE]是否能添加关于单点登录Casdoor的部署

### ISSUE THREAD

**Issue by fon11731** [1Panel-dev/1Panel#2013]
### 1Panel 版本

v1.5.2

### 请描述您的需求或者改进建议

添加关于单点登录Casdoor的部署
起因是我在单独部署此项目，时常报错，并且已经重置系统了。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑将其添加至应用商店。

**Comment by gitzaai** [comment]
我尝试了docker标准镜像失败，只有all in one 那个是正常

**Comment by hsluoyz** [comment]
@gitzaai docker标准镜像失败，是不是因为conf文件路径的问题。需要注意的是，参数里是app.conf所在的文件夹，不包含文件名本身。比如把app.conf文件放在F:/myfolder内，则运行：

`
docker run  -p 8000:8000 -v F:/myfolder:/conf casbin/casdoor:v1.399.0
`

![image](https://github.com/1Panel-dev/1Panel/assets/3787410/652495ae-ea23-42bf-bd68-2588614cdbeb)

**Comment by QYG2297248353** [comment]
> ### 请描述您的需求或者改进建议
> 添加关于单点登录Casdoor的部署 起因是我在单独部署此项目，时常报错，并且已经重置系统了。

[第三方应用商店已支持该应用](https://github.com/QYG2297248353/appstore-1panel?tab=readme-ov-file#%E7%BB%B4%E6%8A%A4%E7%8A%B6%E6%80%81)

![image](https://github.com/user-attachments/assets/2311af4e-118f-4dbc-bb07-0dc0a562d9c8)

**Comment by wanghe-fit2cloud** [comment]
该应用已上架至应用商店。
