### ISSUE TITLE
[BUG] 切换 php 版本， 已安装应用消失

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#2014]
### 联系方式

交流群5   9a6c5fd75f3a

### 1Panel 版本

1.5.2

### 问题描述

切换php版本， 已安装应用消失
![0b703ec6902ed13b41234409a942537](https://github.com/1Panel-dev/1Panel/assets/51264840/291d4d70-29e7-4f48-89e1-515ee8514811)
![a3af6fb7fbc2b8ec5cf43488a49714f](https://github.com/1Panel-dev/1Panel/assets/51264840/39272fe9-8dff-45fb-a1a4-99758a041a93)
![eaba73f328415b7afb651924e1e8e3a](https://github.com/1Panel-dev/1Panel/assets/51264840/b8902e29-9fa0-47e1-bcd2-8e011a6f886f)

### 重现步骤

可能原因：
我首先使用php7搭建了俩个网站， 然后呢在php7的基础上选择安装了几个扩展， 在安装过程中(php7添加扩展并未制作完成)将网站切换到了php5版本，应用消失

现在在镜像完整的情况下进行切换， 如php5(原来是php7搭建的)重新切回php7，应用正常显示
![1692600048525](https://github.com/1Panel-dev/1Panel/assets/51264840/554719bd-947f-4651-ae4a-93b12d413112)
将应用从php7切回php5， 应用不显示
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/278dcdcb-d775-4457-be04-d19cd5882af5)

### 期待的正确结果

切换php版本，一切正常显示

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.5.3 版本已发布。
