### ISSUE TITLE
[BUG]修改容器名称后导致商店应用出现无法找到对应容器问题

### ISSUE THREAD

**Issue by wendao8469759** [1Panel-dev/1Panel#2015]
### 联系方式

942837091@qq.com

### 1Panel 版本

1.5.0

### 问题描述

商店安装的应用，通过容器管理界面修改容器名称后导致商店应用出现无法找到对应容器问题

![image](https://github.com/1Panel-dev/1Panel/assets/32348566/aca698f8-fc81-45d1-b583-8293e65eb5bd)

### 重现步骤

1、安装应用

2、容器管理界面修改容器名称

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
麻烦先查看一下应用镜像是否已经下载成功。
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/2b6f4da0-2652-4248-87aa-cf88630f324e)

> 如果 pull 未成功，可以先到 `主机 - 终端` 页面手动下载镜像。
可以在 `高级设置 - 编辑 compose`  查看 image

**Comment by wendao8469759** [comment]
镜像是成功的， 并且服务也是启动的， 也可以访问，
