### ISSUE TITLE
[BUG]网站设置切换php版本，已安装应用页面里面就会发现没有php网站创建的信息了

### ISSUE THREAD

**Issue by zhangling99** [1Panel-dev/1Panel#2020]
### 联系方式

1562761104@qq.com

### 1Panel 版本

1.5.2

### 问题描述

php8.1创建网站后在应用商店已安装里面会显示php8.1环境创建的网站信息    但我需要更换php7.4版本  更换后应用商店就不在显示php8.1创建的网站信息  这是正常的  但也不会显示php7.4创建网站的信息    我再切换回创建网站时用的php8.1 哪里才会显示 意思就是应用商店已安装哪里只有我这个网站用的是最初创建网站时选择的PHP   才会显示  更换php版本就没有了  这是不正常的  因为我给php添加扩展等操作后需要去重建或重启一下   
![Uploading Screenshot_2023-08-21-14-16-13-399_com.microsoft.emmx-edit.jpg…]()

### 重现步骤

创建php网站后查看去应用商店已安装里面看应该是有一个php创建网站的信息    然后去网站设置切换php版本  然后去应用商店已安装里面就会发现没有php网站创建的信息了

### 期待的正确结果

切换php版本后  应用商店也应该显示切换php版本后的网站信息  比如现在显示的8.1的  等切换到7.4的时候应该显示7.4的信息   而不是什么都不显示了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.5.3 版本已发布。
