### ISSUE TITLE
[BUG]容器管理时，只是改了容器名称没必要重建容器

### ISSUE THREAD

**Issue by CyJaySong** [1Panel-dev/1Panel#2021]
### 联系方式

cyjaysong@gmail.com

### 1Panel 版本

1.5.2

### 问题描述

容器管理时，如果仅仅只是改了容器名称的话，没必要重建容器呀。

### 重现步骤

容器管理-编辑容器名称

**Comment by wanghe-fit2cloud** [comment]
容器列表提供了修改容器名称功能（适用于非应用商店创建的应用），见下图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/b7e3ec8a-8af4-4510-9c0e-9f549438c737)

**Comment by CyJaySong** [comment]
即便是应用商店创建的也可以改吧，会更好点吧。

**Comment by wanghe-fit2cloud** [comment]
> 即便是应用商店创建的也可以改吧，会更好点吧。

会影响应用商店列表功能，不能修改。

**Comment by CyJaySong** [comment]
@wanghe-fit2cloud 应用商店列表跟容器关系应该使用容器id吧
