### ISSUE TITLE
[QUESTION] 为什么设置密码的时候特殊字符不能在首尾

### ISSUE THREAD

**Issue by WANG-Guangxin** [1Panel-dev/1Panel#2022]
### 请描述您的问题

创建 Halo 时（可能也包括其它应用），密码要求特殊字符不能在首尾。
感觉这条规则不是 Halo 所限制的，因为可以在 Halo 的管理面板中将密码修改为特殊字符结尾的情况。
为什么设置初始密码时需要有这条规则
![image](https://github.com/1Panel-dev/1Panel/assets/71872849/298e2c19-be1f-43dc-a520-860721688f28)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
应用商店创建应用时，1Panel 系统针对密码类型字段是有统一的校验规则的，有时确实不能完全匹配到每个应用。
