### ISSUE TITLE
数据库导入失败

### ISSUE THREAD

**Issue by youzhazhu** [1Panel-dev/1Panel#2023]
导入数据库提示如下内容：

服务内部错误: ERROR 1118 (42000) at line 807: Row size too large (> 8126). Changing some columns to TEXT or BLOB or using ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED may help. In current row format, BLOB prefix of 768 bytes is stored inline.

我是从宝塔迁移过来的，其他站点的数据库都能正常导入，不知道为什么这个不行。
如果能帮忙看一下，实在是万分感谢！

**Comment by wanghe-fit2cloud** [comment]
数据库表的引擎换成 MyISAM 即可，参考：

create table p_patent_txt
(
    id                       varchar(32) not null    primary key,
    ....      
)**engine=MyISAM;**

> MySQL 5.5 版本开始 Innodb 已经成为Mysql的默认引擎(之前是MyISAM)。
