### ISSUE TITLE
[FEATURE] 1pctl 可以增加备份数据库的功能

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#2024]
### 1Panel 版本

1.5.2

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/51264840/5ad4a55f-f998-43d3-8b2c-a66100f9de9e)
mysql是基于容器安装的， 所以不能直接使用上述命令备份数据库( 老项目都是自定义脚本 )
我也是随便说说，能支持最好， 不支持影响也不是很大

### 请描述你建议的实现方案

1pctl 可以增加备份数据库的功能
类似这样，我也不清楚是否可行
1pctl mysql -uroot -p***
1pctl mysqldump -uroot -p123456 -h127.0.0.1 -P3306

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1Panel 是支持备份 MySQL 数据库的，如下图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/d4bb8b98-0a2a-4d22-a1b3-f4d1fee06570)

> 近期可能不会考虑支持通过 1pctl 命令来备份 MySQL 数据库，望理解。
