### ISSUE TITLE
[FEATURE]网站域名证书，增加多域名多证书部署

### ISSUE THREAD

**Issue by 357341051** [1Panel-dev/1Panel#2027]
### 1Panel 版本

1.5.2

### 请描述您的需求或者改进建议

比如，一个php网站，绑定了a.com和b.com2个不同的域名，目前只能选中绑定其中一个域名，当开启了强制https，另一个域名就无法正常访问了，

### 附加信息

这个需求是很重要的，很多业务需求上用的到，比如拼多多分享功能，域名很容易被微信红名，禁止访问，则就用到了，不停更换域名去给用户做分享等等

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by zhengkunwang223** [comment]
申请证书的时候可以申请多域名证书
