### ISSUE TITLE
[BUG]反向代理列表看不到添加的反向代理，报服务器内部错误 error。

### ISSUE THREAD

**Issue by hesu-aurora** [1Panel-dev/1Panel#2029]
### 联系方式

1023496783@qq.com

### 1Panel 版本

1.5.2

### 问题描述

反向代理列表看不到添加的反向代理。报服务器内部错误 error。没有其他信息
![QQ截图20230822173908](https://github.com/1Panel-dev/1Panel/assets/95602525/319a3dc2-9a99-46db-a688-178c67b91466)

### 重现步骤

1.51升级到1.52的

**Comment by hesu-aurora** [comment]
![QQ截图20230822173908](https://github.com/1Panel-dev/1Panel/assets/95602525/a07e7447-790b-4438-8608-fe2dea69d120)

**Comment by zhengkunwang223** [comment]
是点击反向代理报这个错吗

**Comment by hesu-aurora** [comment]
> 是点击反向代理报这个错吗

是的

**Comment by zhengkunwang223** [comment]
升级一下版本 再试一下

**Comment by hesu-aurora** [comment]
> 升级一下版本 再试一下

1.5.3了 还是不行。。

在企业微信群里吗 ？ 联系程会玩

**Comment by hesu-aurora** [comment]
> 升级一下版本 再试一下

又试了会，好像是静态网站不行，别的没问题，不影响我用 谢了
