### ISSUE TITLE
[BUG]防火墙规则更新/同步不及时

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#2031]
### 1Panel 版本

1.5.2

### 问题描述

安装应用， 查看防火墙规则， 感觉防火墙规则没有及时更新， 但是可以正常访问应用
如安装nextcloud， 使用端口20069， 防火墙规则里并没有, 但是可以正常访问
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/b27f74d5-5825-43da-8c59-8cbe3fbdf376)

关闭防火墙，在开启，就可以正常看到防火墙规则(不清楚这里是否有其它实现功能)

但是我尝试了几次后（关闭防火墙，打开防火墙），出现该错误
服务内部错误: add port failed, err: stderr: ERROR: Bad port
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/9df99fb8-f086-4452-9f2c-80b1fe16394f)

### 重现步骤

安装应用， 查看防火墙规则

### 期待的正确结果

希望防火墙规则正常显示， 可以正常关闭开启防火墙(多次打开/关闭也不会出现问题)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
ufw 防火墙无法禁用 Docker 端口映射，后续版本会考虑支持添加容器端口规则来限制应用端口。
