### ISSUE TITLE
[FEATURE]容器编排增加添加环境变量的选项

### ISSUE THREAD

**Issue by QAQ5555** [1Panel-dev/1Panel#2033]
### 1Panel 版本

1.5.3

### 请描述您的需求或者改进建议

容器编排增加添加环境变量或者读取环境变量.env文件

**Comment by wanghe-fit2cloud** [comment]
1、在线编辑 compose 内容或者添加 compose 模版时，直接指定 environment: 就能满足需求。
2、选择 compose 文件时，确保 .env 文件和 docker-compose.yml 文件位于同级目录即可。

**Comment by QAQ5555** [comment]
> 1、在线编辑 compose 内容或者添加 compose 模版时，直接指定 environment: 就能满足需求。
> 2、选择 compose 文件时，确保 .env 文件和 docker-compose.yml 文件位于同级目录即可。

因为我平常使用portainer，在编辑compose内容时，下面就有添加env的选项或者直接读取.env文件里的参数并显示出来方便编辑，我认为这样方便一点
设置环境确实有很多方法，在compose指定environment:我确实不知道有这个方法，而且大多数部署教程只提供compose和.env文件，或者直接文字描述环境各个参数名和对应的值，像portainer那样就很方便直接复制填入，也不用创建文件，本身1panel就会保存到自己的文件夹，我认为这样最方便小白用户，复制粘贴再改下参数
如果能做到能识别compose内容显示出端口映射目录映射的之类的内容，直接帮助小白修改参数就更好了

**Comment by wanghe-fit2cloud** [comment]
> > 1、在线编辑 compose 内容或者添加 compose 模版时，直接指定 environment: 就能满足需求。
> > 2、选择 compose 文件时，确保 .env 文件和 docker-compose.yml 文件位于同级目录即可。
> 
> 因为我平常使用portainer，在编辑compose内容时，下面就有添加env的选项或者直接读取.env文件里的参数并显示出来方便编辑，我认为这样方便一点 设置环境确实有很多方法，在compose指定environment:我确实不知道有这个方法，而且大多数部署教程只提供compose和.env文件，或者直接文字描述环境各个参数名和对应的值，像portainer那样就很方便直接复制填入，也不用创建文件，本身1panel就会保存到自己的文件夹，我认为这样最方便小白用户，复制粘贴再改下参数 如果能做到能识别compose内容显示出端口映射目录映射的之类的内容，直接帮助小白修改参数就更好了

感谢反馈，我们在后续版本调研一下具体方案。

**Comment by wanghe-fit2cloud** [comment]
v1.10.16 版本已发布。
