### ISSUE TITLE
[BUG] 清空容器日志，导致容器重启

### ISSUE THREAD

**Issue by CyJaySong** [1Panel-dev/1Panel#2034]
### 联系方式

cyjaysong@gmail.com

### 1Panel 版本

1.5.3

### 问题描述

清空容器日志，导致容器重启

### 重现步骤

清空容器日志，可以看到运行时长变了，日志中也有刚刚启动的日志

**Comment by wanghe-fit2cloud** [comment]
是的，需要在容器停止状态下再来清空容器日志，否则就会触发 dockerd 进程占用 CPU 飙升的 Bug。
<img width="1473" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/2a89bba2-6685-4330-b039-4e9eca2411fb">

**Comment by CyJaySong** [comment]
@wanghe-fit2cloud 
没留意到这个提示，关于清空日志，建议使用，true -> *.log ，这样应该能够避免其他进程异常，不知道你们尝试过没
