### ISSUE TITLE
[BUG]无法删除防火墙端口

### ISSUE THREAD

**Issue by QAQ5555** [1Panel-dev/1Panel#2035]
### 1Panel 版本

1.5.3

### 问题描述

面板使用nginx反代后依旧显示端口占用无法删除 “已使用 ( 1panel )”

### 重现步骤

先使用防火墙开启1panel端口，ip访问安装了OpenResty设置了反代，然后使用其他nginx重新设置了反代，删除了OpenResty所有网站并且卸，重新用域名登录面板依然显示占用无法删除

**Comment by QAQ5555** [comment]
新增一个：防火墙中删除的端口实际仅删除了v4的，v6的规则依然存在，不太安全

**Comment by wanghe-fit2cloud** [comment]
> 新增一个：防火墙中删除的端口实际仅删除了v4的，v6的规则依然存在，不太安全

感谢反馈，我们在本地研发环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
> 先使用防火墙开启1panel端口，ip访问安装了OpenResty设置了反代，然后使用其他nginx重新设置了反代，删除了OpenResty所有网站并且卸，重新用域名登录面板依然显示占用无法删除

可以进入 `主机` - `终端` 页面，执行以下命令来查看一下端口占用情况：
```shell
netstat -ntlp
```

**Comment by wanghe-fit2cloud** [comment]
> 新增一个：防火墙中删除的端口实际仅删除了v4的，v6的规则依然存在，不太安全

https://github.com/1Panel-dev/1Panel/issues/2144

**Comment by wanghe-fit2cloud** [comment]
v1.5.5 版本已发布，支持删除 1Panel 端口

**Comment by ssongliu** [comment]
> 新增一个：防火墙中删除的端口实际仅删除了v4的，v6的规则依然存在，不太安全

这里使用的是 firewalld 还是 ufw，我理解这是在 firewalld 下面，禁用 v4 端口，没有同是禁用 v6 端口，是这个意思吗？
