### ISSUE TITLE
[BUG] wordpress 出现 WordPress needs to access yourweb server 的问题 （FTP）

### ISSUE THREAD

**Issue by mrseawood** [1Panel-dev/1Panel#2037]
### 1Panel 版本

v1.5.3

### 问题描述

安装wordpress安装插件，升级插件，升级系统时提示

Connection Information
To perform the requested action, WordPress needs to access yourweb server. Please enter your FTP credentials to proceed. f you donot remember your credentials, you should contact your web host

### 重现步骤

安装完wordpress后删除插件时会出现以上问题

**Comment by mrseawood** [comment]
官方群里有大神给出了解决方法
终端或者ssh运行
chown -R 1000:1000 网站目录
比如
chown -R 1000:1000 /opt/1panel/apps/openresty/openresty/www/sites/example.com
然后就可以了
好像是系统帮我们创建目录的时候文件夹给的是root的权限，所以我们无法写入，只能读取。用这段代码修改下，使文件成文普通用户组就可以了

**Comment by wanghe-fit2cloud** [comment]
> 官方群里有大神给出了解决方法 终端或者ssh运行 chown -R 1000:1000 网站目录 比如 chown -R 1000:1000 /opt/1panel/apps/openresty/openresty/www/sites/example.com 然后就可以了 好像是系统帮我们创建目录的时候文件夹给的是root的权限，所以我们无法写入，只能读取。用这段代码修改下，使文件成文普通用户组就可以了

因为 1Panel 是采用容器化方案来部署的网站，在创建网站 - 上传网站文件后，需要再次修改持久化目录的权限（容器内运行用户/组为 www-data，uid和gid为1000）

目前1Panel系统已经提供了该功能，可以进入网站设置页面来操作，如下图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/8f1c2694-6c94-4eab-b83e-909ef4cbf850)

**Comment by xichengshouma** [comment]
感谢，我也遇到了这个问题，按你的方法解决了
