### ISSUE TITLE
[FEATURE]希望应用商店官方应用增加支持离线导入

### ISSUE THREAD

**Issue by okxlin** [1Panel-dev/1Panel#2038]
### 1Panel 版本

v1.5.3

### 请描述您的需求或者改进建议

希望应用商店官方应用可以增加离线导入。

- 方便内网环境部署
- 方便官方CDN连接不佳环境

> PS:
>> 不是导入到本地应用，因为本地应用不会被识别为正常运行组件

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
在官方应用商店中下载的安装包还不支持导入到本地应用文件夹中，下个版本支持。

**Comment by kisexu** [comment]
同样需求改功能

**Comment by zhengkunwang223** [comment]
当前已经支持离线导入功能 从官方应用商店 然后制作为本地应用即可
