### ISSUE TITLE
[FEATURE]系统装的CentOS Stream 8，面板这里显示CentOS 8

### ISSUE THREAD

**Issue by 743859910** [1Panel-dev/1Panel#2043]
### 1Panel 版本

v1.5.3

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/84552324/0c795935-e393-46bc-9f5e-faa51646f5a4)
系统装的CentOS Stream 8，面板这里显示CentOS 8
![image](https://github.com/1Panel-dev/1Panel/assets/84552324/20ca01a6-5bef-430c-a45f-aeed95e6397e)
这里显示安装中也没个进度条。。。默认就是编译安装的吗？
还有点说不上来的不适应，另外希望后续也能有个App

### 请描述你建议的实现方案

CentOS Stream系统显示CentOS Stream 8或CentOS Stream 9
给应用商店增加安装进度条，类似宝塔那种也行。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wc7086** [comment]
> 这里显示安装中也没个进度条。。。默认就是编译安装的吗？

#2574 

> 还有点说不上来的不适应，另外希望后续也能有个App

网页对移动端的支持已经足够友好了

**Comment by wc7086** [comment]
这是 https://github.com/shirou/gopsutil 的问题（[相关函数](https://github.com/shirou/gopsutil/blob/4ad4406c032712cc33987428d172b81e459408ae/host/host_linux.go#L177-L319)），一定要显示 `CentOS Stream 8` 的话建议到这个项目提 issue，也许这个 issue 可以关闭了？ @wanghe-fit2cloud

**Comment by wanghe-fit2cloud** [comment]
> 这是 https://github.com/shirou/gopsutil 的问题（[相关函数](https://github.com/shirou/gopsutil/blob/4ad4406c032712cc33987428d172b81e459408ae/host/host_linux.go#L177-L319)），一定要显示 `CentOS Stream 8` 的话建议到这个项目提 issue，也许这个 issue 可以关闭了？ @wanghe-fit2cloud

是的，目前能确定确实是 gopsutil 包的问题。
我们准备在接下来的版本中通过执行命令来解决上述问题。

**Comment by ssongliu** [comment]
https://github.com/shirou/gopsutil/issues/1571
