### ISSUE TITLE
1panel如何安装PHP自定义扩展？

### ISSUE THREAD

**Issue by niceran** [1Panel-dev/1Panel#2044]
### 请描述您的问题

1panel如何安装PHP自定义扩展？
安装定制Swoole版本

**Comment by niceran** [comment]
![Screenshot_2023-08-23-20-16-33-89_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/1Panel-dev/1Panel/assets/22854463/fffa85ec-9169-41e0-838e-102ffa95aab9)

**Comment by wanghe-fit2cloud** [comment]
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/16a81ab1-1b0a-4184-b055-4c5f87103403">

**Comment by niceran** [comment]
> <img alt="图像" width="1475" src="https://user-images.githubusercontent.com/46734380/262706005-16a81ab1-1b0a-4184-b055-4c5f87103403.png">

不行的，试了。可能根本不支持

**Comment by wanghe-fit2cloud** [comment]
> 不行的，试了。可能根本不支持

点击 `查看 PHP 扩展列表`，能获取到扩展和 PHP 版本的对应关系。
