### ISSUE TITLE
[FEATURE]防火墙一键允许CloudFlare IP

### ISSUE THREAD

**Issue by mengzai-c** [1Panel-dev/1Panel#2046]
### 1Panel 版本

v1.5.3

### 请描述您的需求或者改进建议

防火墙可以快速添加多个IP段吗，我需要放行所有cloudflare ip
![image](https://github.com/1Panel-dev/1Panel/assets/140877268/8f527b77-bf71-41c2-ab60-c77f39eba314)
![image](https://github.com/1Panel-dev/1Panel/assets/140877268/996debff-19af-4013-87dc-571dc987e752)

### 请描述你建议的实现方案

就是可以像添加IP一样用逗号隔开添加，或者搞个开关，在来源那里直接加一个开关就可以直接允许CF IP了，不过还要在加一个编辑防止部分用户在局域网无法调试
![image](https://github.com/1Panel-dev/1Panel/assets/140877268/8cae6f6e-255f-4cbf-a81f-1aebef693939)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述需求会在下个版本支持。
