### ISSUE TITLE
[BUG] 应用商店memos无法重启、停止、卸载

### ISSUE THREAD

**Issue by DongShaoNB** [1Panel-dev/1Panel#2047]
### 1Panel 版本

1.5.3

### 问题描述

应用商店memos无法重启、停止、卸载，上述操作后提示 `服务内部错误: stderr: bash:行1: docker-compose：未找到命令` ，返回发现memos状态变为失败，同步状态变成已启动。memos可正常访问。

### 重现步骤

None

### 相关日志输出

```shell
服务内部错误: stderr: bash:行1: docker-compose：未找到命令
```

**Comment by wanghe-fit2cloud** [comment]
> `docker-compose：未找到命令`

要确保 1Panel 服务器上 docker-compose 命令能正常使用。
