### ISSUE TITLE
[BUG] s390x架构无法找到mysql的docker镜像源

### ISSUE THREAD

**Issue by Ajwyunsx** [1Panel-dev/1Panel#2048]
### 联系方式

3427560235@qq.com

### 1Panel 版本

v1.5.3

### 问题描述

安装mysql时，报错stderr: mysql Pulling no matching manifest for linux/s390x in the manifest list entries

### 重现步骤

有点岁

### 期待的正确结果

希望修复

**Comment by wanghe-fit2cloud** [comment]
应用确实对应架构镜像的问题，可以参考论坛置顶的这篇文章：
https://bbs.fit2cloud.com/t/topic/670/2

**Comment by Ajwyunsx** [comment]
> 应用确实对应架构镜像的问题，可以参考论坛置顶的这篇文章： https://bbs.fit2cloud.com/t/topic/670/2

不行，试着教程安装的时候还是那样，同样的结果，重启机器也没用

**Comment by wanghe-fit2cloud** [comment]
这么说吧，所有的操作都是为了替换应用镜像：
首先要在 docker hub 中找到应用对应架构的 docker 镜像，然后通过 tag 命令替换为应用所需的镜像。

**Comment by wanghe-fit2cloud** [comment]
因为有的应用镜像，官方并没有提供 s390x 等架构版本。
这时候就需要人为来查找、替换对于架构镜像了。
