### ISSUE TITLE
[FEATURE]监控有更多的天数保留

### ISSUE THREAD

**Issue by YangHaoNing-CN** [1Panel-dev/1Panel#2050]
### 1Panel 版本

1.5.3

### 请描述您的需求或者改进建议

天数可以自己设置保留时间，30天有点过少，也可以增加天数预估需要的存储大小

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1Panel 系统使用的是 SQLite 数据库，如果将监控数据保存时间设置太久，会严重影响数据库性能并导致频繁锁库等情况。所以暂时先控制了最大保留天数。

> 后续版本可能会考虑将监控数据对接外部存储。

**Comment by mx2913** [comment]
> 感谢反馈。 1Panel 系统使用的是 SQLite 数据库，如果将监控数据保存时间设置太久，会严重影响数据库性能并导致频繁锁库等情况。所以暂时先控制了最大保留天数。
> 
> > 后续版本可能会考虑将监控数据对接外部存储。

可以考虑将更多日志数据写入到文件中，数据中只存储部分

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
