### ISSUE TITLE
[FEATURE]进程守护在没有检测到Supervisor时不报错

### ISSUE THREAD

**Issue by YangHaoNing-CN** [1Panel-dev/1Panel#2051]
### 1Panel 版本

1.5.3

### 请描述您的需求或者改进建议

在 主机-->进程守护内，没有检测到Supervisor时不报"服务内部错误: exec `supervisorctl status` failed, err: stderr: bash: 行 1: supervisorctl: 未找到命令"，因为背景已经检测到了

**Comment by ssongliu** [comment]
感谢反馈！直接执行 supervisorctl status 有返回吗，可以截图看一下。

**Comment by YangHaoNing-CN** [comment]
  root   ~      supervisorctl status                                                                                  in bash at 18:32:15
找不到命令 “supervisorctl”，但可以通过以下软件包安装它：
apt install supervisor

**Comment by YangHaoNing-CN** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/83169812/b2eaffa1-407c-490e-b7c0-16d4f2fb6ac0)
可以将上面的报错删除，因为背景已经说明了没有安装

**Comment by wanghe-fit2cloud** [comment]
v1.5.4 版本已发布。
