### ISSUE TITLE
[BUG]添加仓库的时候，不知道什么原因报错

### ISSUE THREAD

**Issue by CyJaySong** [1Panel-dev/1Panel#2054]
### 1Panel 版本

1.5.3

### 问题描述

不知道什么原因，添加修改仓库，报服务内部错误: stderr: Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

### 重现步骤

添加仓库，修改仓库

**Comment by ssongliu** [comment]
感谢反馈！这里应该是 docker 状态不对，执行一下 systemctl status docker.service 和 journalctl -xe 看看具体错误信息。

**Comment by CyJaySong** [comment]
添加了仓库后，发现daemon.json中多了私有仓库，然后就启动不起来了

**Comment by ssongliu** [comment]
仓库是 http 的吧，http 会在 daemon.json 中添加授信
