### ISSUE TITLE
[FEATURE]容器管理支持分组管理和筛选

### ISSUE THREAD

**Issue by CyJaySong** [1Panel-dev/1Panel#2055]
### 1Panel 版本

1.5.3

### 请描述您的需求或者改进建议

容器，编排，编排模版,  管理支持分组管理和筛选

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
1Panel 的容器、编排、镜像等列表内容是通过 SDK 实时读取的。要实现分组功能，需要对停止的容器打标签并通过标签进行分组。
然而，停止容器可能会影响业务运行。如果通过记录数据库实现分组，还可能导致数据不一致的问题。因此，该功能暂不考虑实现，望理解。
