### ISSUE TITLE
[FEATURE] 设置不用灰色

### ISSUE THREAD

**Issue by YangHaoNing-CN** [1Panel-dev/1Panel#2062]
### 1Panel 版本

1.5.3

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/83169812/093eb54d-9512-4550-aaef-8500b83aa454)
这种设置可以不用灰色，这样会让人觉得此设置不可更改

**Comment by wanghe-fit2cloud** [comment]
输入框灰色是禁止编辑状态
> 用户需要点击右侧设置按钮在右侧抽屉页面修改。
