### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by YangHaoNing-CN** [1Panel-dev/1Panel#2063]
### 1Panel 版本

1.5.3

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/83169812/ac35ab5c-d094-4222-ab94-46460c531fff)
容器里操作里可以将 "编辑 升级 日志" 放入更多，再将启动，停止这些放出来

**Comment by wanghe-fit2cloud** [comment]
启动、停止等操作可以通过行内按钮和列表顶部按钮来实现，但是编辑、升级等不适合批量操作的按钮只能通过行内按钮来展示。

**Comment by YangHaoNing-CN** [comment]
我的意思是编辑升级不常用的可以放到
![image](https://github.com/1Panel-dev/1Panel/assets/83169812/616c9ac2-af73-4b5f-b175-5eeeb3867067)
里，把启动之类从中移出
