### ISSUE TITLE
[FEATURE] 反向代理默认配置增加协议转发

### ISSUE THREAD

**Issue by WankkoRee** [1Panel-dev/1Panel#2064]
### 1Panel 版本

v1.5.3

### 请描述您的需求或者改进建议

有些服务需要从`X-Forwarded-Proto`头中获取外部服务正确的协议名，以更好地实现拼接url等功能。

nginx配置片段如下：

```
    proxy_set_header X-Forwarded-Proto $scheme; 
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本支持持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
