### ISSUE TITLE
[QUESTION] Jenkins更新完后容器没了

### ISSUE THREAD

**Issue by DongShaoNB** [1Panel-dev/1Panel#2065]
### 请描述您的问题

Jenkins更新完后状态显示失败，提示 '1Panel-jenkins-ghtL 容器不存在'

**Comment by wanghe-fit2cloud** [comment]
进入 `容器` - `镜像` 列表查看一下最新版本的 Jenkins 镜像是否已经 pull 成功。
> 最新镜像 应该是 `jenkins/jenkins:2.419`

**Comment by DongShaoNB** [comment]
> 进入 `容器` - `镜像` 列表查看一下最新版本的 Jenkins 镜像是否已经 pull 成功。
> 
> > 最新镜像 应该是 `jenkins/jenkins:2.419`

成功了 现在该怎么恢复呢

**Comment by wanghe-fit2cloud** [comment]
已安装应用列表，重建应用即可。
> 持久化数据都在应用安装目录中。
