### ISSUE TITLE
[FEATURE]文件管理支持查看用户和用户组的id

### ISSUE THREAD

**Issue by WankkoRee** [1Panel-dev/1Panel#2066]
### 1Panel 版本

1.5.3

### 请描述您的需求或者改进建议

现在只能查看用户和用户组的名字，但是容器中的名字可能和宿主机并不一致，或者有些用户在宿主机上压根没有，所以显示用户和用户组的id是有必要的，如root是1，普通用户是1000等。

**Comment by WankkoRee** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/21287731/678578aa-20db-4516-b532-d524626f71a9)

比如上面几个文件夹都是容器挂载出来的，所以权限与宿主机情况不一致。

比如：
- 宿主机中有id为1的用户，叫root，则显示`root(1)`
- 宿主机中没有id为1000的用户，则显示`-(1000)`（也许有更好的显示格式）

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已修复。
