### ISSUE TITLE
[BUG]反向代理未严格实现请求头定义

### ISSUE THREAD

**Issue by WankkoRee** [1Panel-dev/1Panel#2067]
### 1Panel 版本

1.5.3

### 问题描述

当server中和location中都存在add_header时，server的add_header将不生效。

具体可参考： https://serverfault.com/questions/400197/add-header-directives-in-location-overwriting-add-header-directives-in-server

此问题会导致server中的`add_header Strict-Transport-Security "max-age=31536000"; `即`HSTS`配置失效。

可方便地使用此工具检查生效情况：http://web.chacuo.net/nethstscheck

### 重现步骤

1. 配置一个反向代理网站
2. 配置网站的HTTPS
3. 检查HSTS生效情况

**Comment by zhengkunwang223** [comment]
好的 感谢建议 我们复现一下

**Comment by Anyexyz** [comment]
对好像是有这个问题，之前还不知道为什么`HSTS`配置失效，把`add_header Strict-Transport-Security "max-age=31536000";`添加到`location`就生效了，但是在浏览器中是可以读到`strict-transport-security: max-age=31536000 `的配置，[Myssl](https://myssl.com/)的检测过不了

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
