### ISSUE TITLE
[FEATURE]增加更加详细的权限管理

### ISSUE THREAD

**Issue by fuuhoo** [1Panel-dev/1Panel#2069]
### 1Panel 版本

v1.5.3

### 请描述您的需求或者改进建议

完善权限的控制，比如根据不同的角色区分菜单和一些资源。（比如容器）

### 请描述你建议的实现方案

针对不同的用户和角色，可以看到不同的菜单，以及可以看到不同的容器分组。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本增加权限管理功能。

**Comment by wanghe-fit2cloud** [comment]
多用户权限体系需求的讨论，统一汇总到该 issue #638
