### ISSUE TITLE
[FEATURE] 容器列表样式调整建议

### ISSUE THREAD

**Issue by CyJaySong** [1Panel-dev/1Panel#2070]
### 1Panel 版本

1.5.3

### 请描述您的需求或者改进建议

1、资源使用率 CPU和内存希望放在一行显示，字号适当减小，以便进入容器列表后，加载完资源使用率表格高度跳跃，看着不太舒服。
2、容器重命名的时候，输入框默认填入当前容器名称
3、可以锁定列表每页加载数量，以便刷新页面后，列表数量又变成10条。
4、镜像信息鼠标悬浮显示详情很不错，加个点击镜像内容时自动复制到剪切板更爽
5、增加IP地址列，同时也支持点击复制
6、增加刷新列表按钮，而不是刷新整个网页

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈，后续版本持续优化。

**Comment by zyyfit** [comment]
优化了1、3、5，第5点中，增加了 ip 列，但是不考虑复制

**Comment by CyJaySong** [comment]
![WechatIMG155](https://github.com/1Panel-dev/1Panel/assets/29367599/8b7a376d-391a-4e20-a61b-289371ad729f)

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
