### ISSUE TITLE
[BUG] 首页流量界面展示问题

### ISSUE THREAD

**Issue by kawai-aki** [1Panel-dev/1Panel#2073]
### 1Panel 版本

1.5.3

### 问题描述

首页实时流量展示页面，在从后台切至前台时，会将这一段时间内的网络流量显示为一个很大的瞬时流量

### 重现步骤

将首页打开然后放于浏览器后台，一段时间后将页面切换至前台

### 附加信息

<img width="1280" alt="屏幕截图 2023-08-25 193044" src="https://github.com/1Panel-dev/1Panel/assets/92026851/f4b62c34-d52e-4bc8-bb6a-987ed6635952">
<img width="1280" alt="屏幕截图 2023-08-25 193057" src="https://github.com/1Panel-dev/1Panel/assets/92026851/f1486414-e9ad-4898-9c4f-eff887869a6f">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们现在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.5.5 版本已发布。
