### ISSUE TITLE
[BUG] 手动导入证书，验证失败

### ISSUE THREAD

**Issue by liuyiwuqing** [1Panel-dev/1Panel#2074]
### 联系方式

1520431201@qq.com

### 1Panel 版本

v1.5.3

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/52553268/25a37d46-8170-4d58-a4dc-3648f5a225f7)
在阿里云申请免费的证书，下载的是 Nginx 证书格式pem/key
在1panel面板中手动导入，验证失败

### 重现步骤

在1panel面板，网站中设置https，手动导入证书

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
在本地环境均为复现上述问题。
> 麻烦检查一下私钥文件。
