### ISSUE TITLE
[FEATURE] frps服务端希望增加面板端口和用户名密码等参数

### ISSUE THREAD

**Issue by newcardriver** [1Panel-dev/1Panel#2077]
### 1Panel 版本

1.5.3

### 请描述您的需求或者改进建议

商店里面现有的frps只有一个7000端口的参数，看了下配置文件，这个是链接的端口，希望能够增加面板相关的参数设置
![image](https://github.com/1Panel-dev/1Panel/assets/44741731/7f82cd9c-acd0-405a-9e2d-86b9dfed1cdd)
![image](https://github.com/1Panel-dev/1Panel/assets/44741731/3c7ecc6c-f856-4bc8-97cd-5a79c2c05cf5)

**Comment by wanghe-fit2cloud** [comment]
后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
frp 最新版本已经推送，点击更新按钮后部署最新版本，如下图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/761f1087-ae23-4382-99a3-a2ce10e9ecba)
