### ISSUE TITLE
[BUG] redis升级之后会导致容器一直重启

### ISSUE THREAD

**Issue by newcardriver** [1Panel-dev/1Panel#2078]
### 1Panel 版本

1.5.3

### 问题描述

之前通过面板装了redis并设置了密码，一直正常使用
今天把redis升级之后发现问题
猜测是不是因为之前设置了密码导致的？

![image](https://github.com/1Panel-dev/1Panel/assets/44741731/92e7fdfa-5468-4c60-bb51-78c1ecfa1bbf)

### 重现步骤

1. 安装上一个版本的redis启动并设置密码
2. 在面板中升级到最新的redis版本
3. 点击左侧容器查看redis容器的状态。

**Comment by wanghe-fit2cloud** [comment]
Redis 是从哪个版本升级到 7.0.12。

**Comment by newcardriver** [comment]
> Redis 是从哪个版本升级到 7.0.12。

抱歉这个还真没注意，主要是升级完了之后才发现这个问题。
后面我看看下个版本有升级的话会不会还有这个情况，也有可能是跨大版本了吧。
