### ISSUE TITLE
[FEATURE]设置不用灰色 

### ISSUE THREAD

**Issue by YangHaoNing-CN** [1Panel-dev/1Panel#2079]
### 1Panel 版本

1.5.3

### 请描述您的需求或者改进建议

https://github.com/1Panel-dev/1Panel/issues/2062#issue-1864875336

可以将“设置”按钮换成白色，不用灰色

**Comment by wanghe-fit2cloud** [comment]
后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已修复。
