### ISSUE TITLE
[BUG] 前端脚本命令错误

### ISSUE THREAD

**Issue by juukee** [1Panel-dev/1Panel#2080]
### 1Panel 版本

v1.5.3

### 问题描述

"prettier:comment": "自动格式化当前目录下的所有文件",

### 重现步骤

"prettier:comment": "自动格式化当前目录下的所有文件",

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地复现一下问题。

**Comment by ssongliu** [comment]
你好，可以具体的说一下这个问题吗？
