### ISSUE TITLE
[FEATURE]:  ACME ECC Certificate Support

### ISSUE THREAD

**Issue by ttimochan** [1Panel-dev/1Panel#2081]
### 1Panel 版本

1.5.3

### 请描述您的需求或者改进建议

I understand that 1Panel comes with a built-in ACME client. However, based on the certificates I've obtained, they appear to be issued by Let's Encrypt, which supports ECC and RSA certificate issuance. Therefore, I would like to request support for ECC certificate issuance.

### 请描述你建议的实现方案

Perhaps it would be helpful to reference the implementation details regarding this matter from acme.sh?

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，目前支持 Let's Encrypt 颁发的证书，后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
