### ISSUE TITLE
[FEATURE]增添对Suhosin的支持

### ISSUE THREAD

**Issue by skyhhjmk** [1Panel-dev/1Panel#2082]
### 1Panel 版本

v1.5.3

## 增添对Suhosin的支持
[https://cloud.tencent.com/developer/ask/sof/113875](https://cloud.tencent.com/developer/ask/sof/113875)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
可以参考论坛中这篇文章 [1Panel 自定义 PHP 扩展使用教程](https://bbs.fit2cloud.com/t/topic/2073)
