### ISSUE TITLE
[BUG] php 5 环境中，composer 无法正常使用

### ISSUE THREAD

**Issue by WankkoRee** [1Panel-dev/1Panel#2083]
### 1Panel 版本

1.5.3

### 问题描述

如图，按提示降级 composer 也不行。

![image](https://github.com/1Panel-dev/1Panel/assets/21287731/24d1d8c3-0d7c-4f21-9cae-0adb703a3926)

### 重现步骤

安装 php 5 运行环境，并在容器中使用 composer 。

**Comment by zhengkunwang223** [comment]
感谢反馈 我们复现一下

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
