### ISSUE TITLE
[FEATURE] 优化端口规则中的状态展示方式

### ISSUE THREAD

**Issue by allyxmiko** [1Panel-dev/1Panel#2085]
### 1Panel 版本

1.5.3

### 请描述您的需求或者改进建议

对于通过应用商店安装的应用，端口规则的状态中可以正常显示使用此端口的服务，但是对于其他情况部署的服务只显示已使用，鉴于对于自部署服务获取该服务名称很困难，希望可以增加一个可以自己填写端口说明的功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
