### ISSUE TITLE
[FEATURE] 希望优化删除相关的内容显示

### ISSUE THREAD

**Issue by allyxmiko** [1Panel-dev/1Panel#2086]
### 1Panel 版本

1.5.3

### 请描述您的需求或者改进建议

在删除文件（文件夹），容器时只会显示确认删除，希望可以增加显示具体被删除的文件（文件夹）或者容器的名称。

### 请描述你建议的实现方案

对于单个资源示例（仅供布局参考）
![Snipaste_2023-08-28_01-00-49](https://github.com/1Panel-dev/1Panel/assets/53589496/0afc68ac-e223-456c-9a0c-c6bb1bb929e0)

对于多个资源示例（仅供布局参考）
![Snipaste_2023-08-28_01-00-05](https://github.com/1Panel-dev/1Panel/assets/53589496/a1b7686d-087c-44e3-9373-dc2dfc2f98db)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中针对 `主机` - `文件` 功能进行重构、优化。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
