### ISSUE TITLE
[FEATURE]PHP有计划加入添加本地扩展(.so)的功能

### ISSUE THREAD

**Issue by xiexiaosheng** [1Panel-dev/1Panel#2087]
### 1Panel 版本

1.5.3

### 请描述您的需求或者改进建议

PHP有计划加入添加本地扩展(.so)的功能
有些WP的主题，比如说RI主题和B2，都是有加密的，必须得上传一个扩展才能用

### 附加信息

![QQ截图20230828095225](https://github.com/1Panel-dev/1Panel/assets/64482026/9a3db033-d444-48a3-a79d-1f75bf7caba1)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本调研一下上述需求的可行性方案。

**Comment by zhengkunwang223** [comment]
https://bbs.fit2cloud.com/t/topic/2073 参考这个
