### ISSUE TITLE
[BUG]在线升级V1.5.3后无法新建数据库

### ISSUE THREAD

**Issue by q127981** [1Panel-dev/1Panel#2088]
### 1Panel 版本

1.5.3

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/31874319/5072707e-baba-4f21-b2c5-dd02fe478480)
无法新建数据库，不知道为什么，不管写什么数据库名字都无法新建

1Panel 版本 v1.5.3
运行方式 安装包运行 centos7
浏览器版本 谷歌浏览器最新

### 重现步骤

升级至最新版本，新建mysql数据库

### 期待的正确结果

1

### 相关日志输出

```shell
1
```

### 附加信息

1

**Comment by q127981** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31874319/afc60ba3-59eb-4d94-9a4b-a7b220d376d9)

**Comment by ssongliu** [comment]
感谢反馈！可以提供一下添加数据库的接口请求吗？

或者有添加 1Panel 社区群吗？我们远程看一下。

**Comment by q127981** [comment]
> 感谢反馈！可以提供一下添加数据库的接口请求吗？
> 
> 或者有添加 1Panel 社区群吗？我们远程看一下。
我没加社区群、  这个是接口请求


![image](https://github.com/1Panel-dev/1Panel/assets/31874319/4a6abb6c-a911-43cd-92e1-349238d18c4e)

**Comment by q127981** [comment]
> 感谢反馈！可以提供一下添加数据库的接口请求吗？
> 
> 或者有添加 1Panel 社区群吗？我们远程看一下。

我没加社区群、麻烦告知一下加入的渠道。  上面图片已发接口请求

**Comment by ssongliu** [comment]
这里有尝试随机密码，或者直接输入 admin123 作为数据库密码吗？

添加社区群可以扫描下面这个二维码：
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/07da8cbe-5754-44fc-b795-7ba502b5d722)

**Comment by q127981** [comment]
> 这里有尝试随机密码，或者直接输入 admin123 作为数据库密码吗？
> 
> 添加社区群可以扫描下面这个二维码： ![image](https://user-images.githubusercontent.com/73214554/263609239-07da8cbe-5754-44fc-b795-7ba502b5d722.png)

已尝试  还是不行

![image](https://github.com/1Panel-dev/1Panel/assets/31874319/bc8c7837-4747-4dcb-a8c8-8ee0c9db4bcd)

**Comment by ssongliu** [comment]
问题在于 root 用户的数据库密码中包括 & 字符，修改完密码后解决。

**Comment by wanghe-fit2cloud** [comment]
v1.5.4 版本已发布。
