### ISSUE TITLE
[QUESTION]部署后打不开网站是为啥呢

### ISSUE THREAD

**Issue by monobo1989** [1Panel-dev/1Panel#2092]
### 请描述您的问题

这个提示我要怎么办呢？如图：https://pic.rmb.bdstatic.com/bjh/ed81ed8879bcce51f3de0a884af46e479475.png

**Comment by wanghe-fit2cloud** [comment]
安装成功后，控制台会打印面板访问信息，可通过浏览器访问 1Panel：

```
http://目标服务器 IP 地址:目标端口/安全入口
```

> 如果使用的是云服务器，请至安全组开放目标端口。

ssh 登录 1Panel 服务器后，执行 `1pctl user-info` 命令可获取安全入口（entrance）

**Comment by monobo1989** [comment]
> 安装成功后，控制台会打印面板访问信息，可通过浏览器访问 1Panel：
> 
> ```
> http://目标服务器 IP 地址:目标端口/安全入口
> ```
> 
> > 如果使用的是云服务器，请至安全组开放目标端口。
> 
> ssh 登录 1Panel 服务器后，执行 `1pctl user-info` 命令可获取安全入口（entrance）

谢谢，登录进去了。
