### ISSUE TITLE
[FEATURE] 夜间自动切换主题

### ISSUE THREAD

**Issue by RealHeart** [1Panel-dev/1Panel#2093]
### 1Panel 版本

v1.5.3

### 请描述您的需求或者改进建议

亮色暗色根据系统自动切换

### 请描述你建议的实现方案

参考 https://vueuse.org/core/useDark/

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by ssongliu** [comment]
感谢反馈，v1.9.0 版本我们会支持主题跟随系统功能，夜间自动切换主题需求暂时不考虑，望理解。
