### ISSUE TITLE
[FEATURE] 1pctl 添加Tab补全支持

### ISSUE THREAD

**Issue by RealHeart** [1Panel-dev/1Panel#2097]
### 1Panel 版本

v1.5.3

### 请描述您的需求或者改进建议

1pctl 子命令支持tab补全，目前Tab会补全当前目录的文件

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by maninhill** [comment]
请问这个问题有进展吗？

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is there any progress on this issue?

**Comment by wanghe-fit2cloud** [comment]
考虑到 1pctl 本身是 Shell 脚本，部分命令集成了 1Panel 命令，并且存在不同操作系统自动补全适配的问题，我们决定暂时不支持该需求，望理解。
