### ISSUE TITLE
[BUG] 压缩包解压时可能遇到的handling file 错误

### ISSUE THREAD

**Issue by allyxmiko** [1Panel-dev/1Panel#2098]
### 联系方式

1713069822@qq.com

### 1Panel 版本

1.5.3

### 在解压一些压缩包时可能遇到的解压错误
![Snipaste_2023-08-28_19-39-25](https://github.com/1Panel-dev/1Panel/assets/53589496/51fb0fc5-7a2a-4886-87d0-83fe362b8223)
这个问题很奇怪，以`1Panel-1.5.3.tar.gz`源代码压缩包和`go1.21.0.linux-amd64.tar.gz`压缩包为例，1Panel从github release中下载，go语言压缩包从官网下载。

### 通过预览压缩包发现，两个压缩包均是有一级目录
1. 下图为1Panel-1.5.3.tar.gz的压缩包预览
![Snipaste_2023-08-28_19-50-28](https://github.com/1Panel-dev/1Panel/assets/53589496/fc9bce9c-cbf9-4654-aea6-5cdb372c1e5c)
2. 下图为go1.21.0.linux-amd64.tar.gz的压缩包预览
![Snipaste_2023-08-28_19-50-34](https://github.com/1Panel-dev/1Panel/assets/53589496/dc67ffcc-59c1-430e-97c7-dedd7c9f6e91)

### 调试时发现的问题
1. 在解压缩1Panel的压缩包时正确的获取了`archFile.NameInArchive`即`fileName`值为`"1Panel-1.5.3/"`
![Snipaste_2023-08-28_19-56-47](https://github.com/1Panel-dev/1Panel/assets/53589496/7c5038e0-c4c3-4482-9c23-6eea91a007a3)

2. 在解压缩go的压缩包时错误的获取了`archFile.NameInArchive`，`mholt`并没有正确的识别外层的go文件夹，而是`fileName`的值为`"go/CONTRIBUTING.md"`
![Snipaste_2023-08-28_20-04-10](https://github.com/1Panel-dev/1Panel/assets/53589496/cfaea51d-c9a8-4b33-ad40-3b863a94adf9)

3. 由于`go`文件夹不存在，在下面的`f.Fs.OpenFile`抛出了`io/fs.PathError`
![Snipaste_2023-08-28_20-16-21](https://github.com/1Panel-dev/1Panel/assets/53589496/718fd74a-0597-426b-a272-ae0184ba02c9)

4. 没有处理`PathError`，输出错误
![Snipaste_2023-08-28_20-21-06](https://github.com/1Panel-dev/1Panel/assets/53589496/888859cd-0d82-4654-a697-0827ba19fdb3)

### 重现步骤

1. 上传go语言压缩包
2. 点击解压

### 期待的正确结果

能正常解压

**Comment by zhengkunwang223** [comment]
感谢提交代码 赞👍🏻

**Comment by wanghe-fit2cloud** [comment]
v1.5.4 版本已发布。
