### ISSUE TITLE
[FEATURE] 1pctl 添加对非 root 执行的提示

### ISSUE THREAD

**Issue by RealHeart** [1Panel-dev/1Panel#2100]
### 1Panel 版本

v1.5.3

### 请描述您的需求或者改进建议

对 #2096 的延伸建议。

在使用无权限用户执行命令时，引导用户使用sudo执行。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.5.5 版本已发布。
