### ISSUE TITLE
php5.4安装失败[QUESTION]

### ISSUE THREAD

**Issue by dudt** [1Panel-dev/1Panel#2101]
### 请描述您的问题

![image](https://github.com/1Panel-dev/1Panel/assets/19968269/264649d6-2292-4305-aef0-72a89239d108)

**Comment by zhengkunwang223** [comment]
感谢反馈 我们复现一下

**Comment by dudt** [comment]
php5.5也报错

**Comment by wanghe-fit2cloud** [comment]
可以将 1Panel 系统升级到最新版本后，手动点击应用商店列表右上角的更新应用按钮，之后再来创建 PHP 运行环境。
