### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#2107]
### 请描述您的问题

重启服务器，会导致应用自动重启？ 这是docker的问题吗？

关闭防火墙，之前已关闭应用会重启。
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/eed3e904-9cbe-4e2a-bc06-8268b3583049)
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/6b12da37-ec04-4166-9e3c-50ba90615da0)

关闭防火墙后，cpu异常(可能是halo的问题， 因为我把数据库关闭了，它一直在重启)
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/281349d4-403a-402f-bf92-f867e9ecc270)

**Comment by okxlin** [comment]
因为应用商店的应用默认重启策略为`restart: always`

方便备份时会自动重启应用。

可以手动重建应用为`unless-stopped`

**Comment by 9a6c** [comment]
我比较好奇的是，关闭防火墙， 应用会重启

**Comment by wanghe-fit2cloud** [comment]
> 我比较好奇的是，关闭防火墙， 应用会重启

应用重启和关闭防火墙没有直接关系。

**Comment by 9a6c** [comment]
[新建 DOC 文档.zip](https://github.com/1Panel-dev/1Panel/files/12465793/DOC.zip)

我感觉是BUG， 你可以使用我的面板尝试
交流群5    9a6c...

**Comment by wanghe-fit2cloud** [comment]
> [新建 DOC 文档.zip](https://github.com/1Panel-dev/1Panel/files/12465793/DOC.zip)
> 
> 我感觉是BUG， 你可以使用我的面板尝试 交流群5 9a6c...

- 如果使手动执行命令关闭的防火墙，就需要重启 docker 来使容器网络生效。
> 如果没有手动重启 docker 是肯定不会导致 docker 容器重启的

- 如果是通过面板关闭的防火墙（此时会自动重启 docker 来生效容器网络），重启规则为 always 的容器会触发重启。

**Comment by 9a6c** [comment]
哦， 原来如此...
不太明白为什么关闭防火墙时要重启docker生效容器网络？ 防火墙都没了，应该不需要吧， 应该启动防火墙的时候设置吧？

**Comment by wanghe-fit2cloud** [comment]
> 哦， 原来如此... 不太明白为什么关闭防火墙时要重启docker生效容器网络？ 防火墙都没了，应该不需要吧， 应该启动防火墙的时候设置吧？

- docker 启动的时候会自动在 iptables 中注册一个链
- 防火墙停止或者重新启动会将其清除，导致在查询防火墙规则的时候显示不到 docker 的链
- 重启 docker 就会将 iptables 链注册回来
> 所以需要通过重启 docker 来解决该问题

**Comment by 9a6c** [comment]
哦，明白了。 感谢解答
