### ISSUE TITLE
[QUESTION]打开应用商店和新增运行环境时，总是无法显示，提示：网络请求超时

### ISSUE THREAD

**Issue by zyccsnow** [1Panel-dev/1Panel#2113]
### 请描述您的问题

因为公司的业务基本上都是在海外， 所以我们海外服务器用的比较多， 我在日本，香港两个云服务器上安装好后，却一直无法安装相对应的PHP环境。请问是对海外节点没做优化吗？

**Comment by wanghe-fit2cloud** [comment]
1Panel 系统资源统一放在阿里 OSS，是全球加速的 cdn，应该不会慢，除非 cdn 节点有问题了。

**Comment by zyccsnow** [comment]
我是在选择版本的时候出现的这个问题， 选了了大版本，点击右侧的下拉菜单， 却没有出现小版本的选项。 等了一会儿就出现了超时报错。
