### ISSUE TITLE
[QUESTION]询问一下我无论是安装PHP还是mysql都会错误，提示都是大概如下这些

### ISSUE THREAD

**Issue by bandengzex** [1Panel-dev/1Panel#2114]
### 请描述您的问题

镜像 build 失败:The PHP_VERSION variable is not set. Defaulting to a blank string. The CONTAINER_PACKAGE_URL variable is not set. Defaulting to a blank string. The PHP_EXTENSIONS variable is not set. Defaulting to a blank string. The TZ variable is not set. Defaulting to a blank string. The IMAGE_NAME variable is not set. Defaulting to a blank string. The SOURCE_DIR variable is not set. Defaulting to a blank string. The PHP_PHP_CONF_FILE variable is not set. Defaulting to a blank string. The PHP_FPM_CONF_FILE variable is not set. Defaulting to a blank string. The PHP_LOG_DIR variable is not set. Defaulting to a blank string. The DATA_DIR variable is not set. Defaulting to a blank string. Building 1panel-php Service '1panel-php' failed to build: invalid reference format

服务内部错误: stderr: The CONTAINER_NAME variable is not set. Defaulting to a blank string. The CPUS variable is not set. Defaulting to a blank string. The MEMORY_LIMIT variable is not set. Defaulting to a blank string. The PANEL_DB_ROOT_PASSWORD variable is not set. Defaulting to a blank string. The HOST_IP variable is not set. Defaulting to a blank string. The PANEL_APP_PORT_HTTP variable is not set. Defaulting to a blank string. The Compose file '/opt/1panel/apps/mysql/mysql/docker-compose.yml' is invalid because: services.mysql.ports is invalid: Invalid port "::3306", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

**Comment by wanghe-fit2cloud** [comment]
麻烦提供一下 1Panel 版本信息。

**Comment by bandengzex** [comment]
> 麻烦提供一下 1Panel 版本信息。

1.5.3

**Comment by wanghe-fit2cloud** [comment]
是 linux 服务器吗？啥操作系统？我们在本地环境复现一下。
```shell
cat /etc/os-release
```

**Comment by bandengzex** [comment]
> 是 linux 服务器吗？啥操作系统？我们在本地环境复现一下。
> 
> ```shell
> cat /etc/os-release
> ```
![image](https://github.com/1Panel-dev/1Panel/assets/103732230/d65e70cc-24eb-4bc5-a24d-27239375f64a)

**Comment by bandengzex** [comment]
> 是 linux 服务器吗？啥操作系统？我们在本地环境复现一下。
> 
> ```shell
> cat /etc/os-release
> ```

centos linux 7

**Comment by wanghe-fit2cloud** [comment]
1、进入应用安装目录 `/opt/1panel/apps/mysql/mysql/`， 查看一下是否存在 .env 文件
2、在改目录中，可以手动执行启动命令看一下结果：
```shell
docker-compose up -d 
```

**Comment by wanghe-fit2cloud** [comment]
麻烦将 1Panel 升级到最新版本后，点击应用商店页面右上角的更新应用按钮后再来安装。

**Comment by NewTypo** [comment]
为啥商店安装nocodb 报错stdout: Unsupported PANEL_DB_TYPE value: 'mysql' 并且没有.env 文件

**Comment by wanghe-fit2cloud** [comment]
> 为啥商店安装nocodb 报错stdout: Unsupported PANEL_DB_TYPE value: 'mysql' 并且没有.env 文件

应该是和服务器安装 docker 与 docker-compose 版本有关系，可以手动升级至最新版本
