### ISSUE TITLE
[QUESTION]镜像 build 失败:stat /opt/1panel/runtime/php/smp/docker-compose.yml: no such file or directory

### ISSUE THREAD

**Issue by zyccsnow** [1Panel-dev/1Panel#2115]
### 请描述您的问题

在本地创建运行环境时候提示错误，实际上是有这个文件的，内容如下：

version: '3'
services:
  1panel-php:
    build:
      context: ./php
      args:
        PHP_IMAGE: php:${PHP_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        TZ: ${TZ}
    image: ${IMAGE_NAME}
    volumes:
      - ${SOURCE_DIR}:/www/
      - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf
      - ${PHP_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    restart: always
    cap_add:
      - SYS_PTRACE

**Comment by zhengkunwang223** [comment]
企业微信群联系 ”程会玩“ 帮你远程看一下
