### ISSUE TITLE
支持CICD自动部署吗

### ISSUE THREAD

**Issue by SemiThin** [1Panel-dev/1Panel#2117]
### 1Panel 版本

V1

### 请描述您的需求或者改进建议

提交git代码的时候自动部署

### 请描述你建议的实现方案

假设有容器如下
web容器：web1 web2
中间件容器：reids nginx mysql php等
版本控制容器：gitlab或gitea或gogs
提交代码，打包容器，自动部署，github的action,gitlab的runner，gitea或gogs的drone

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
经团队内部讨论，暂时先不考虑支持上述需求，望理解。

**Comment by SemiThin** [comment]
> 经团队内部讨论，暂时先不考虑支持上述需求，望理解。

经过我们的讨论，
1.你们处以研发初期
2.你们没有宝塔投入市场时间长
3.我看不到你们比宝塔的优势在哪里（这是最重要的一点）
暂时先不使用你们的产品。
