### ISSUE TITLE
[BUG]CPU占用率显示不正确+性能问题

### ISSUE THREAD

**Issue by skyhhjmk** [1Panel-dev/1Panel#2118]
### 联系方式

scrsc@qq.com

### 1Panel 版本

v1.5.3

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/78078552/6c7bd941-7ad5-439a-a756-8519b01d7f9f)

CPU占用出现十万甚至更高

高负载状态下打开进程管理面板占用会在90%至100%之间跳动（数据来源：SSH登录后执行htop）

### 重现步骤

疑似在高负载状态下打开进程管理会同时触发两个bug

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
可以进去 `主机` - `终端`，手动执行 top 命令查看一下结果。

**Comment by zhengkunwang223** [comment]
此问题没有复现 暂时关闭 如果有新的情况 可以继续回复
