### ISSUE TITLE
[QUESTION]运行环境中PHP一直显示制作镜像中

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#2119]
### 请描述您的问题

系统:Ubuntu 22.04LTS
架构:x86_64
地区:中国香港
1Panel版本:v1.5.3
PHP镜像:1panel-php:8.1.18
PHP扩展:opcache,mcrypt,exif
重复实验发现无扩展也一样

**Comment by zhengkunwang223** [comment]
设置一下 docker 加速

**Comment by wanghe-fit2cloud** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/82f1c824-0ac3-468b-8f73-3510031f89b6)
