### ISSUE TITLE
[FEATURE]: Enabling OpenResty WAF to Parse Client IP from CDN Headers

### ISSUE THREAD

**Issue by ttimochan** [1Panel-dev/1Panel#2120]
### 1Panel 版本

1.5.3

### 请描述您的需求或者改进建议

Hello,

Upon implementing a CDN in my setup, I've encountered an issue of OpenResty WAF. Upon reviewing the WAF logs, it has come to my attention that the WAF is potentially blocking a CDN IP address instead of the genuine client's IP address. This situation could potentially be troubling when using a CDN.

Thank you!
Cheers🥳

### 请描述你建议的实现方案

In future releases of OpenResty or 1panel, it might be beneficial to incorporate support for accurate parsing of the `X-Forwarded-For` header passed by CDN. This would allow extraction of the true client IP address, enhancing OpenResty WAF's practicality for security and analysis tasks.

### 附加信息

Log Example

```
219.144.89.44 [2023-08-30 14:43:50] "GET www.example.com/?html=<script>alert(1dwadwadwad)</script>" "-"  "curl/8.2.1" "(?:define|eval|file_get_contents|include|require|require_once|shell_exec|phpinfo|system|passthru|char|chr|preg_\w+|execute|echo|print|print_r|var_dump|(fp)open|alert|showmodaldialog)\("
```

`219.144.89.44` is not my ip

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
网站真实 IP 识别相关需求的讨论，统一汇总到该 issue #1028
