### ISSUE TITLE
[BUG] 优化首页推荐应用展示

### ISSUE THREAD

**Issue by allyxmiko** [1Panel-dev/1Panel#2123]
### 联系方式

1713069822@qq.com

### 1Panel 版本

1.5.3

### 问题描述

在首页的推荐应用仍会展示已经安装且只能安装一次的应用

### 重现步骤

1. 安装推荐应用里的只能安装一次的应用
2. 应用推荐仍会推荐该应用的安装

### 期待的正确结果

不展示已安装且只能安装一次的应用推荐

**Comment by wanghe-fit2cloud** [comment]
非常感谢你为 1Panel 项目的贡献！
