### ISSUE TITLE
[BUG] search请求会请求两次

### ISSUE THREAD

**Issue by allyxmiko** [1Panel-dev/1Panel#2125]
### 联系方式

1713069822@qq.com

### 1Panel 版本

1.5.3

### 问题描述

接口`/api/v1/settings/search`会在单击侧边栏不同子项时同时请求两次，两次响应数据一样
![Snipaste_2023-08-30_22-16-06](https://github.com/1Panel-dev/1Panel/assets/53589496/15647b05-d21b-46ec-ae6d-444932ef7e78)

### 重现步骤

1. 打开控制台
2. 刷新页面
3. 发现`/api/v1/settings/search`请求了两次

### 期待的正确结果

只请求一次

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by ssongliu** [comment]
这里是因为概览页需要获取系统是否开启安全入口，如果没开启的话需要显示警告信息，如图中 1
还需要检查系统是否有版本更新，如图中 2
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/36a006a4-2d4c-4a4b-ab7e-1edb5a927985)
