### ISSUE TITLE
[FEATURE]数据库备份这块是否可以多一些自定义的地址 比如多台SERVER 本地NAS 等

### ISSUE THREAD

**Issue by NauhWuun** [1Panel-dev/1Panel#2128]
### 1Panel 版本

1.5.2

### 请描述您的需求或者改进建议

数据库备份这块是否可以多一些自定义的地址 比如多台SERVER 本地NAS 等 或者开放一些同步工具服务也好

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦再详细描述一下上述需求。
比如自定义地址是要当作备份账号吗？等等

**Comment by NauhWuun** [comment]
希望可以出一些自定义备份工具 比如mysql多备，或者直接对nas的工具 主要是数据备份工具多一些选择吧

**Comment by wanghe-fit2cloud** [comment]
经团队内部讨论，暂无计划支持上述需求，望理解。
