### ISSUE TITLE
[FEATURE] 主机计划任务发现

### ISSUE THREAD

**Issue by lbzss** [1Panel-dev/1Panel#2131]
### 1Panel 版本

1.5.3

### 请描述您的需求或者改进建议

主机上已存在的计划任务是否应当跟新建的任务一样落库？这样可以进行主机计划任务统一管理，否则在一台旧主机上初始化1Panel后无法确切知道服务器上是否还有其他任务。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，1Panel 创建的计划任务不是通过 Linux 服务器的 crontab 来实现的。

> 你的意思是要把 crontab 创建的计划任务同步到 1Panel 的计划任务列表吗？

**Comment by lbzss** [comment]
是的，服务器上已经存在的crontab如果能集成到1Panel中会更便于维护。

**Comment by wanghe-fit2cloud** [comment]
> 是的，服务器上已经存在的crontab如果能集成到1Panel中会更便于维护。

了解，我们后续版本研究一下具体方案。

**Comment by wanghe-fit2cloud** [comment]
中短期内暂无支持上述需求的计划，望理解。
