### ISSUE TITLE
防火墙 IP 规则无法删除 [BUG]

### ISSUE THREAD

**Issue by ssongliu** [1Panel-dev/1Panel#2132]
### 1Panel 版本

1.5.3

### 问题描述

防火墙 IP 规则无法删除

### 重现步骤

防火墙 IP 规则无法删除

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述问题会在下个版本修复。

**Comment by wanghe-fit2cloud** [comment]
v1.5.4 版本已发布。
