### ISSUE TITLE
[FEATURE]系统防火墙增加备注信息

### ISSUE THREAD

**Issue by zxwmfcm** [1Panel-dev/1Panel#2135]
### 1Panel 版本

1.5.2

### 请描述您的需求或者改进建议

是否可以在这里增加备注  方便记录端口用途
![image](https://github.com/1Panel-dev/1Panel/assets/30642864/afd067e8-aa57-44b2-a8c0-8e7938113f24)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在 v1.6.0 版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已修复。
