### ISSUE TITLE
应用无法安装

### ISSUE THREAD

**Issue by WyntersN** [1Panel-dev/1Panel#2138]
### 请描述您的问题
主机名称 ecs-02890443
发行版本 debian-10.13
内核版本 4.19.0-16-amd64
系统类型 x86_64
启动时间 2023-09-01 08:01:31
运行时间 45分钟 2秒
当前运行版本：v1.5.4

![image](https://github.com/1Panel-dev/1Panel/assets/27792650/3c864f01-b398-4357-b8aa-b53239bb375e)
![image](https://github.com/1Panel-dev/1Panel/assets/27792650/1dd72327-86a7-4c26-9b7a-cfb409cf1d59)

**Comment by wanghe-fit2cloud** [comment]
应用镜像 pull 未成功，可以先添加一下镜像加速。
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/6773a0bb-8975-4da8-a599-03a319a10c60)
