### ISSUE TITLE
[BUG] docker容器日志无法查看

### ISSUE THREAD

**Issue by d4rw1nz** [1Panel-dev/1Panel#2143]
### 联系方式

zhang1287609286@qq.com

### 1Panel 版本

v1.5.4

### 问题描述

点击容器日志无法查看日志显示docker logs命令 没有-n选项

### 重现步骤

```shell
[root@sunny-core code-server]# docker logs 8ddb54e5ece7 -n
unknown shorthand flag: 'n' in -n
See 'docker logs --help'.
```

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/102583750/04e922d8-388f-4f29-bdd2-10417e801269)
![image](https://github.com/1Panel-dev/1Panel/assets/102583750/c1d678a8-ba7c-4381-8398-5763871a8cc8)

**Comment by wanghe-fit2cloud** [comment]
上述问题应该是服务器上 docker 版本低，不支持 -n 语法导致的。
> docker 是在安装 1Panel 之前，手动安装的吗？

**Comment by d4rw1nz** [comment]
使用的这条命令安装的 curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh &amp;&amp; sh quick_start.sh
推荐的docker版本是多少呢,这是我安装的版本
```shell
[root@sunny-core code-server]# docker info
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 17
 Server Version: 19.03.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 6.2.2-1.el7.elrepo.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.939GiB
 Name: sunny-core
 ID: 7NLD:UUJJ:WAB3:MVDJ:D7QP:ROVI:E7QK:I772:IK6Z:3NVT:G2KJ:6EPA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: 1287609286
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://mirror.ccs.tencentyun.com/
 Live Restore Enabled: false
```

**Comment by wanghe-fit2cloud** [comment]
Client 信息怎么没有呢？

用下面的命令查看一下具体版本：
```shell
docker version
```

**Comment by wanghe-fit2cloud** [comment]
我们下个版本也会针对容器日志查看的问题做出优化。

**Comment by d4rw1nz** [comment]
我解决了,我升级了docker版本,日志限制正常显示
&nbsp;


zhang1287609286
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月5日(星期二) 下午5:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [1Panel-dev/1Panel] [BUG] docker容器日志无法查看 (Issue #2143)





 
我们下个版本也会针对容器日志查看的问题做出优化。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
