### ISSUE TITLE
侧边栏图标宽度不一致 [BUG]

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#2145]
### 1Panel 版本

1.5.4

### 问题描述

如图
![图片](https://github.com/1Panel-dev/1Panel/assets/30285739/8972fd00-b321-4249-9f0a-91c77733cdf9)

### 重现步骤

收缩侧边栏

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.5.5 版本已发布。
