### ISSUE TITLE
[BUG] 使用 MySql 5.7，在计划任务中添加数据库备份操作备份失败

### ISSUE THREAD

**Issue by Daiyangcheng** [1Panel-dev/1Panel#2148]
### 联系方式

QQ：3143105972

### 1Panel 版本

1.5.5

### 问题描述

某一天，我不小心把我数据库玩炸了，想着用自动备份的数据恢复，结果内容呈现如下
![image](https://github.com/1Panel-dev/1Panel/assets/48477757/b01bcb1a-6e6b-4c4a-9983-e3bdc41c316e)

还好当时我留存了数据的 idb 和 frm 文件，不然我的数据就全飞了（1w + 条用户数据）

### 重现步骤

在计划任务中添加数据库备份的任务，数据库版本为应用商店提供的5.7版本

### 期待的正确结果

sql中有正确的数据结构和数据

### 相关日志输出

```shell
![image](https://github.com/1Panel-dev/1Panel/assets/48477757/b01bcb1a-6e6b-4c4a-9983-e3bdc41c316e)
```

**Comment by ssongliu** [comment]
感谢反馈！本地开发环境没有复现，可以添加一下社区群，我远程看一下这个问题。
<img width="214" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/73214554/af6b13ab-4d7d-40f5-be78-6f2171882677">
