### ISSUE TITLE
[BUG]可通过上传-解压的方式强制弄出一个带有空格的文件名导致报错

### ISSUE THREAD

**Issue by skyhhjmk** [1Panel-dev/1Panel#2149]
### 1Panel 版本

v1.5.5

### 问题描述

# 报错如下
![image](https://github.com/1Panel-dev/1Panel/assets/78078552/a5e78499-7a75-42f9-b208-8610ef1afeec)

`
服务内部错误: stderr: chown: cannot access ‘/server/panel/1panel/apps/openresty/openresty/www/sites/host.biliwind.com/index/WHMCS’: No such file or directory chown: cannot access ‘6.1.1’: No such file or directory
`
# 错误分析
出现了带有空格的文件，执行`chowm`时命令拼接出现问题，Linux误认为空格后是下一个参数

### 重现步骤

1. 上传此文件（内含一个文件名带有空格的文件夹和一些无关紧要的文件）
[WHMCS_6.2_cn.zip](https://github.com/1Panel-dev/1Panel/files/12502626/WHMCS_6.2_cn.zip)
2. 解压出带有空格的文件
3. 由于默认的所有者是root:root，需要更改为1000:1000
4. 点击root，更改所有者为1000，用户组为1000
5. 点击确认，出现报错

### 相关日志输出

```shell
服务内部错误: stderr: chown: cannot access ‘/server/panel/1panel/apps/openresty/openresty/www/sites/host.biliwind.com/index/WHMCS’: No such file or directory chown: cannot access ‘6.1.1’: No such file or directory


文件管理	
修改用户/组 [paths] => [1000]/[1000]	
失败	
2023-09-02 10:19:22
文件管理	
修改用户/组 [paths] => [1000]/[1000]	
失败	
2023-09-02 10:18:31
文件管理	
解压 [/server/panel/1panel/apps/openresty/openresty/www/sites/host.biliwind.com/index/WHMCS_6.2_cn.zip]	
成功	
2023-09-02 10:14:37
```

**Comment by ssongliu** [comment]
感谢反馈！我们在开发环境复现一下。

**Comment by wanghe-fit2cloud** [comment]
上传网站文件后修改目录权限，也可以进入 `网站设置` - `网站目录` 页面，点击 `运行用户/组` 后面的保存按钮：
<img width="1166" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/c509c1ce-95f6-4f25-8ea2-026f4bc0dd90">

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
