### ISSUE TITLE
[BUG]安装应用无法选中安装的 MariaDB

### ISSUE THREAD

**Issue by woodchen-ink** [1Panel-dev/1Panel#2150]
### 联系方式

wood@czl.net

### 1Panel 版本

v1.5.5

### 问题描述

安装了mariadb，虽然数据库管理页面可以通过添加远程数据库的方式添加，但是一键创建网站时，无法选中安装的mariadb

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/95951386/5264239c-bf02-4382-b818-b271b3ca9cbc)

### 期待的正确结果

可以显示mariadb，并且能够通过mariadb平替mysql

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，下个版本（v1.6.0）会支持部分应用安装时选择 MariaDB 数据库。
> 你安装的是哪个应用？

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
