### ISSUE TITLE
[FEATURE]建议多个网站可以使用相同的域名(端口号不同)

### ISSUE THREAD

**Issue by jamebal** [1Panel-dev/1Panel#2151]
### 1Panel 版本

v1.5.5

### 请描述您的需求或者改进建议

- 1. 添加网站可以设置非80端口,而不需要去手动修改配置文件
- 2. 多个网站可以使用相同的域名(端口号不同)

### 附加信息

<img width="712" alt="截屏2023-09-02 16 07 23" src="https://github.com/1Panel-dev/1Panel/assets/49510841/d4ed9390-b624-453d-8794-e243adcd8931">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已修复。
