### ISSUE TITLE
[BUG]证书申请时解析域名错乱

### ISSUE THREAD

**Issue by skyhhjmk** [1Panel-dev/1Panel#2152]
### 联系方式

scrsc@qq.com

### 1Panel 版本

v1.5.5

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/78078552/4a76d77e-4187-4a6e-94de-d5245c9d9903)

### 重现步骤

使用www前缀和通配符申请均正常，但尝试到host前缀时出现问题

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by zhengkunwang223** [comment]
您好 没有复现 请问是否在域名 DNS 解析中设置了此域名
