### ISSUE TITLE
[FEATURE]希望增加磁盘管理相关功能，组 RAID，磁盘 S.M.A.R.T. 检测和报警等。

### ISSUE THREAD

**Issue by sanfang0766** [1Panel-dev/1Panel#2153]
### 1Panel 版本

v1.5.5

### 请描述您的需求或者改进建议

希望增加磁盘管理相关功能，组 RAID，磁盘 S.M.A.R.T. 检测和报警等。

### 附加信息

小公司很多时候自己组主机都需要在面板有这些功能。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持上述需求。

**Comment by zhengkunwang223** [comment]
NAS 相关功能不是我们的主要功能点 当前 1Panel 主要围绕网站、容器、linux 运维管理来实现功能 希望理解

**Comment by sanfang0766** [comment]
> NAS 相关功能不是我们的主要功能点 当前 1Panel 主要围绕网站、容器、linux 运维管理来实现功能 希望理解

这并不是 NAS 功能！这只是 Linux 服务器基础功能！任何服务器都需要组 RAID 1 来保证数据的稳定性。

**Comment by zhengkunwang223** [comment]
> 

中短期没有此计划

**Comment by charleypeng** [comment]
这个确实小巧又强大的nas一下子就做出来了。

**Comment by wanghe-fit2cloud** [comment]
磁盘相关需求的讨论，统一汇总到该 issue #1852
