### ISSUE TITLE
[FEATURE] 部分界面样式对齐优化 | 文字样式统一

### ISSUE THREAD

**Issue by HenryWu01** [1Panel-dev/1Panel#2154]
### 1Panel 版本

1.5.3

### 请描述您的需求或者改进建议

# 一. 界面样式对齐
## 1. 主机 -> 文件中的路径地址并未垂直居中对齐
![brave_ARXW8DEmaf](https://github.com/1Panel-dev/1Panel/assets/99880210/411ab79f-d0a9-4fcd-81ca-07ae32d6aad6)
## 2. 主机 -> SSH 管理中 ``SSH`` 和 ``已启动`` 没有垂直居中对齐
![brave_O9KdzUBDkD](https://github.com/1Panel-dev/1Panel/assets/99880210/8bcf74e7-bb05-431f-82ed-ef2b15958c55)
## 3. 面板设置 -> 主题颜色中图标没对齐
![brave_RoL8VPDsvS](https://github.com/1Panel-dev/1Panel/assets/99880210/414743c2-f60c-4a98-b881-40be72490040)
# 二. 文字样式统一
## 1. 面板设置 -> 英文格式不统一
![brave_SVlUElMTvK](https://github.com/1Panel-dev/1Panel/assets/99880210/4809b3a2-855c-4d07-a120-e44b9ccedab8)

例如这里: ``UserName`` 应该是 ``Username``, 下面应该统一如 ``Server Time``, ``Panel Alias`` 而不是混用
## 2. 应用商店 -> 软件名称
![brave_wFcRJgLCVY](https://github.com/1Panel-dev/1Panel/assets/99880210/77188f14-b1b2-4548-8f69-89452cee2871)

软件名称应该统一或者按照官方的命名来, 在 [AList 官方文档](https://alist.nn.ci/zh) 中，这里的 ``alist`` 应该改为 ``AList``
## 3. 应用商店 -> 软件简介
![brave_QICnITrDd8](https://github.com/1Panel-dev/1Panel/assets/99880210/bc0c9fdd-cc34-4ca1-b343-8484776ac65f)

应用介绍里，如果存在中英参杂的情况，应该规定中英文之间空格，或者不空格，而不是混用

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈，我们会在后续版本持续优化。

**Comment by maninhill** [comment]
太细致了，手动点赞👍🏻

**Comment by HenryWu01** [comment]
> 太细致了，手动点赞👍🏻

刚好我最近也在和 ``UI`` 打交道也学习了很多，希望 ``1Panel`` 越来越好，把这些细节也完善一下

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已修复。

**Comment by HenryWu01** [comment]
![brave_K4Jqi5AFcY](https://github.com/1Panel-dev/1Panel/assets/99880210/981c8d7a-6b2f-422c-9842-662dbc66d256)
![brave_jg0UXmUIP8](https://github.com/1Panel-dev/1Panel/assets/99880210/0317de74-d1b1-4016-9545-63034cd806ed)
又发现了两个，麻烦跟进一下啦 @wanghe-fit2cloud

**Comment by wanghe-fit2cloud** [comment]
> 又发现了两个，麻烦跟进一下啦

飞致云官方应用商店的截图，这个具体是什么问题？

**Comment by HenryWu01** [comment]
> > 又发现了两个，麻烦跟进一下啦
> 
> 飞致云官方应用商店的截图，这个具体是什么问题？

是这个问题:  
**应用商店 -> 软件简介**
``应用介绍里，如果存在中英参杂的情况，应该规定中英文之间空格，或者不空格，而不是混用``

这两个应用的中英文之间没有按照别的应用那种规则空格

**Comment by wanghe-fit2cloud** [comment]
> > > 又发现了两个，麻烦跟进一下啦
> > 
> > 
> > 飞致云官方应用商店的截图，这个具体是什么问题？
> 
> 是这个问题: **应用商店 -> 软件简介** `应用介绍里，如果存在中英参杂的情况，应该规定中英文之间空格，或者不空格，而不是混用`
> 
> 这两个应用的中英文之间没有按照别的应用那种规则空格

收到，感谢反馈。
