### ISSUE TITLE
[FEATURE]网站增加复制/模板功能

### ISSUE THREAD

**Issue by xaswq** [1Panel-dev/1Panel#2155]
### 1Panel 版本

v1.5.5

### 请描述您的需求或者改进建议

有时候我们会在服务器上部署多个类似的应用，唯一不同是反代的外部域名和内部端口不一样，这个时候如果可以快速复制/使用模板来建反向代理会很方便，只需要修改下域名/端口，再配置下SSL证书管理即可。

### 请描述你建议的实现方案

配置复制的重命名复制生成对应副本

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持上述需求。

**Comment by zhengkunwang223** [comment]
经过讨论 复制/模版功能需要处理的项太多 而且适用面没有那么广 
所以我们暂时不会增加此需求 谢谢理解
