### ISSUE TITLE
[FEATURE]建议增加reload功能

### ISSUE THREAD

**Issue by xaswq** [1Panel-dev/1Panel#2156]
### 1Panel 版本

v1.5.5

### 请描述您的需求或者改进建议

目前面板只有重启功能，如果改了配置文件，不想重启，加个重载配置的按钮会更好

### 附加信息

<img width="835" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/85377380/cb42fd5d-783b-4fac-8b24-db908be206d0">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持上述需求。

**Comment by zhengkunwang223** [comment]
在设置内修改配置文件选择保存并重载即可
