### ISSUE TITLE
[BUG]主页面-负载显示 280%

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#2157]
### 联系方式

交流群5 - 9a6c***

### 1Panel 版本

1.5.5

### 问题描述

我记得之前版本是正常的，最新版本有问题
代码之前是按照3s， 可能为了修改某个bug，更改了代码，可能计算出现问题？
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/09c60429-5633-4124-bc25-29c70f8d0427)

### 重现步骤

打开主页面

### 期待的正确结果

正确显示

**Comment by 9a6c** [comment]
过了一段时间后（10分钟左右， 中途刷新了几次，都是错误的显示该数值），又正确显示了
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/77bbbdd6-ca74-4016-a99f-19090e7dae4b)

**Comment by ssongliu** [comment]
感谢反馈，可以执行一下 uptime 比较一下数据是否一致

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布，可以升级到最新版本。
