### ISSUE TITLE
域名自动解析

### ISSUE THREAD

**Issue by mycbxzd1** [1Panel-dev/1Panel#2158]
### 1Panel 版本

1.5.5

### 请描述您的需求或者改进建议

可以增加一个功能，绑定域名时候可以选择DNS API直接用CF的api解析到当前服务器，每次创建网站很麻烦

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦再详细描述一下你现在的具体操作？我们也会在后续版本调研一下该需求的具体实现方案。

**Comment by mx2913** [comment]
可以直接泛解析到服务器上，泛解析的优先级比制定解析的优先级低，不影响以前就有的二级解析

**Comment by zhengkunwang223** [comment]
此功能短时间内不考虑实现 希望理解
