### ISSUE TITLE
[FEATURE]前端缓存应用商店的分页参数（pageSize）

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#2159]
### 1Panel 版本

v1.5.5

### 请描述您的需求或者改进建议

应用商店的分页参数（pageSize）在前端缓存一下

> 现状是：每次刷新完页面，就变成默认值的 60 条了。

### 请描述你建议的实现方案

应用商店的分页参数（pageSize）在前端缓存一下

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已经缓存了部分页面的分页条数。
