### ISSUE TITLE
[FEATURE] 网站下建议加一个备份按钮

### ISSUE THREAD

**Issue by xaswq** [1Panel-dev/1Panel#2160]
### 1Panel 版本

v1.5.5

### 请描述您的需求或者改进建议

今天使用的时候想备份网站，但是只找到了导入备份，点击备份列表发现可以在这里备份。但是不太直观。

贵团队可以考虑直接把 备份列表 改成叫 备份，或者加一个备份，点一下就备份了，用户可以去备份列表里面查询明细，不在备份列表里面备份了。现在的操作逻辑不太直观

没有第一个备份，就没有点击备份列表的必要。那么如何进行第一次备份呢？

<img width="1481" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/85377380/f58d9676-b30b-4485-b539-88f7739cc685">

### 附加信息

<img width="1434" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/85377380/29d1cdf7-a516-44b4-a5ea-c6a8d740ef9a">

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈。
目前，我们在中短期内不打算考虑上述建议，网站、数据库、已安装应用的备份将继续沿用现有的操作逻辑，希望您能理解。
