### ISSUE TITLE
[FEATURE] 备份账号希望支持又拍云

### ISSUE THREAD

**Issue by CyJaySong** [1Panel-dev/1Panel#2161]
### 1Panel 版本

1.5.5

### 请描述您的需求或者改进建议

备份账号希望支持又拍云

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
又拍云云存储在自有标准的基础上，增加了针对 S3 v4 协议标准的兼容支持。
具体教程如下：
https://help.upyun.com/knowledge-base/aws-s3%E5%85%BC%E5%AE%B9/

**Comment by CyJaySong** [comment]
@wanghe-fit2cloud 没看懂怎么填写

**Comment by CyJaySong** [comment]
<img width="870" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/29367599/eb9c09a1-cd33-42e1-b877-ddd5ed2bf666">
这个Region 如何填写呢

**Comment by wanghe-fit2cloud** [comment]
刚查看了一下其官方文档的说明：
目前又拍云仅支持文件相关API，不支持配置区域。详情参见「[S3 API](https://help.upyun.com/knowledge-base/s3-api/)」。

**Comment by CyJaySong** [comment]
@wanghe-fit2cloud 所以暂时还是用不了喽
