### ISSUE TITLE
[BUG]PHP扩展安装有问题，慢就不说了，安装经常性的根本没用，探针检查不到已经安装的，选了跟没选一样，那个筛选扩展提示索引也是有问题，就算没有的扩展还是提示索引，根本不能确定是否包含

### ISSUE THREAD

**Issue by wumingpc** [1Panel-dev/1Panel#2164]
### 1Panel 版本

最新版本

### 问题描述

PHP扩展安装有问题，慢就不说了，安装经常性的根本没用，探针检查不到已经安装的，选了跟没选一样，那个筛选扩展提示索引也是有问题，就算没有的扩展还是提示索引，根本不能确定是否包含， 能不能手动的传统安装扩展方法，上传到ext目录，php.ini调用

### 重现步骤

反复多重建安装几次

**Comment by wumingpc** [comment]
> ### 联系方式
> 
> _No response_
> ### 1Panel 版本
> 
> 最新版本
> ### 问题描述
> 
> PHP扩展安装有问题，慢就不说了，安装经常性的根本没用，探针检查不到已经安装的，选了跟没选一样，那个筛选扩展提示索引也是有问题，就算没有的扩展还是提示索引，根本不能确定是否包含， 能不能手动的传统安装扩展方法，上传到ext目录，php.ini调用
> ### 重现步骤
> 
> 反复多重建安装几次
> ### 期待的正确结果
> 
> _No response_
> ### 相关日志输出
> 
> _No response_
> ### 附加信息
> 
> _No response_

**Comment by wumingpc** [comment]
垃圾东西不玩了，呵呵，说bug还踢人真NB呢，什么垃圾玩意，还搞开源笑死我了，怕别人说bug啊，真的搞笑，就这素质态度还搞开源呢，能处理是相应语言开发还问你们真是搞笑，那王贺就是个傻逼笑死我了，还让用户自己找问题，正常操作时好时坏还说别人问题，啥bug都是别人的问题笑死我了，估计没啥用户才出来不久，没什么人反馈就以为上天了呢，产品好的很啥问题都没行了吧，爷爷不用了不用你们伺候，自己折腾自己的去，用个垃圾软件还受气，就这样还收费还想走远笑死我了，人品有问题的素质团队真厉害！祝你们一路顺风

**Comment by wanghe-fit2cloud** [comment]
![iShot_2023-09-04_12 04 39](https://github.com/1Panel-dev/1Panel/assets/46734380/c2bd6f39-d92c-43c1-89c6-f4d0ec68a71d)
![iShot_2023-09-04_12 18 47](https://github.com/1Panel-dev/1Panel/assets/46734380/02c291b1-a5f7-4d6e-a45d-9eef1d34ac32)

**Comment by Satisfy8375** [comment]
> 垃圾东西不玩了，呵呵，说bug还踢人真NB呢，什么垃圾玩意，还搞开源笑死我了，怕别人说bug啊，真的搞笑，就这素质态度还搞开源呢，能处理是相应语言开发还问你们真是搞笑，那王贺就是个傻逼笑死我了，还让用户自己找问题，正常操作时好时坏还说别人问题，啥bug都是别人的问题笑死我了，估计没啥用户才出来不久，没什么人反馈就以为上天了呢，产品好的很啥问题都没行了吧，爷爷不用了不用你们伺候，自己折腾自己的去，用个垃圾软件还受气，就这样还收费还想走远笑死我了，人品有问题的素质团队真厉害！祝你们一路顺风

小丑
