### ISSUE TITLE
[BUG]更新之后出现了上次的问题  守护进程状态丢失

### ISSUE THREAD

**Issue by 7836246** [1Panel-dev/1Panel#2167]
### 联系方式

QQ7836246

### 1Panel 版本

v1.5.5

### 问题描述

发行版本 debian-12.1
上次出现的 守护进程状态丢失

### 重现步骤

发行版本 debian-12.1

更新后出现的

**Comment by zhengkunwang223** [comment]
已复现 下个版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
