### ISSUE TITLE
[BUG] 强迫症优化

### ISSUE THREAD

**Issue by mdddj** [1Panel-dev/1Panel#2175]
### 1Panel 版本

1.5.5

### 问题描述

1. 圆角没对齐,如下图
<img width="836" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/29020213/843859f7-9ff4-4a09-ba1f-ae5054fdcde5">

2.按钮靠太近,如下图
<img width="300" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/29020213/e8bc08bb-0f52-4c72-ac53-d620678929a5">

### 重现步骤

无

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中持续优化。

**Comment by wanghe-fit2cloud** [comment]
最新版本已优化。
