### ISSUE TITLE
[FEATURE]容器端口映射显示太长

### ISSUE THREAD

**Issue by likecutie** [1Panel-dev/1Panel#2181]
### 1Panel 版本

1.5.5

### 请描述您的需求或者改进建议

以sftp-go为例，ftp被动端口有100个，展开后就占据了好几页，且并不能清楚直观地看到哪些端口被映射了。
![图片](https://github.com/1Panel-dev/1Panel/assets/49803345/8ecd0b4d-377e-4c9a-b6e5-231ddb191faf)
端口乱序加上多，根本看不出来。

### 请描述你建议的实现方案

参考docker命令的打印，做成这种段式的，把连续端口只用一行表示。
![图片](https://github.com/1Panel-dev/1Panel/assets/49803345/9ce79a0a-d917-4943-bb69-4175015801d5)

**Comment by CyJaySong** [comment]
这是极端情况

**Comment by wanghe-fit2cloud** [comment]
后续版本会针对上述情况做出优化。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已修复。
