### ISSUE TITLE
[FEATURE]对 podman 增加兼容

### ISSUE THREAD

**Issue by i8sn0w** [1Panel-dev/1Panel#2183]
### 1Panel 版本

1.5.5

### 请描述您的需求或者改进建议

什么时候对podman增加兼容呀，应用商店建议增加一个samba的管理程序或者系统内置一个samba的管理程序

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在中短期内应该还没有精力来兼容 podman，望理解。
