### ISSUE TITLE
[FEATURE]当编排存在多个容器的时候，修改编排信息，只对修改的docker-comps 做一个重新生效的操作

### ISSUE THREAD

**Issue by mccruixi** [1Panel-dev/1Panel#2185]
### 1Panel 版本

最新版本

### 请描述您的需求或者改进建议

当编排存在多个的时候 修改编排信息  整编排的容器都重启了

### 请描述你建议的实现方案

只对修改的docker-comps 做一个重新生效的操作

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
