### ISSUE TITLE
[FEATURE]目前使用v1.5.5产生的一些问题

### ISSUE THREAD

**Issue by carolcoral** [1Panel-dev/1Panel#2187]
### 1Panel 版本

1.5.5

### 请描述您的需求或者改进建议

1. docker compose部署，删除容器会把compose一起删除
2. docker 容器重启（非重新build）会覆盖volume本地修改的文件内容
3. openresty在配置网站的时候默认只能使用80端口开放，即便在“设置”中修改别的端口，返回页面后还是80端口
4. 防火墙端口放行自定义端口无法设置备注（端口太多的情况下无法分清服务）
5. docker容器中点击日志中的“下载”仅能下载当前展示内容，不能下载整个日志文件（既然只能下载当前展示内容我何必下载呢～～）

### 请描述你建议的实现方案

1. docker compose部署正常删除docker容器后应该保留compose设置（不仅仅只是文件保留，应该是在“编排”中保留）
2. docker compose中应该增加“重新build”功能
3. openresty增加自定义端口
4. 防火墙自定义端口增加“备注”
5. docker容器日志“下载”可以下载整个日志文件用于问题排查

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈，我们会在后续版本持续优化。

**Comment by zhengkunwang223** [comment]
openresty增加自定义端口 在 v1.6 版本支持

**Comment by carolcoral** [comment]
部分问题已优化，新issuse地址- https://github.com/1Panel-dev/1Panel/issues/2399
