### ISSUE TITLE
[FEATURE] 希望能增加备份和恢复docker容器的功能

### ISSUE THREAD

**Issue by fenglindubu** [1Panel-dev/1Panel#2194]
### 1Panel 版本

1.5.5

### 请描述您的需求或者改进建议

有些应用自己下载的，不在应用商店内，无法使用应用商店内的备份功能，希望增加备份和恢复功能！

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by ceozero** [comment]
可以加docker commit <container_id> <image_name> 功能？ 每次改好的容器都要手动commit 一下再推送。。。
![image](https://github.com/1Panel-dev/1Panel/assets/22513657/f64f6b95-93f5-413e-bbd7-6981b56c5a77)
portainer  的这个创建功能很方便，建完打标推送。。

**Comment by wanghe-fit2cloud** [comment]
> 可以加docker commit <container_id> <image_name> 功能？ 每次改好的容器都要手动commit 一下再推送。。。 ![image](https://user-images.githubusercontent.com/22513657/285172231-f64f6b95-93f5-413e-bbd7-6981b56c5a77.png) portainer 的这个创建功能很方便，建完打标推送。。

新创建一个 issue 来描述这个需求吧。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
