### ISSUE TITLE
[BUG] OpenResty 的反向代理挂了导致无法启动 也无法查看日志和修改配置

### ISSUE THREAD

**Issue by cktk** [1Panel-dev/1Panel#2203]
### 1Panel 版本

1.5.5

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/49108554/4c20b990-39f4-4d59-82a9-b2000819ef60)

OpenResty 的反向代理挂了以后导致无法启动
问题1 
无法通过点击设置来查看日志
问题2 
既然反代挂了能不能在配置页面直接进行配置 
定位到具体反代的配置页面直接点击禁用 然后重启OpenResty

### 重现步骤

关闭反向代理的服务  
然后重启OpenResty 

### 期待的正确结果

我想能不能在这个OpenResty挂了的情况下去修改反代的配置 查看日志

**Comment by zhengkunwang223** [comment]
感谢反馈 下个版本支持 强制删除 Openresty  和网站
当前可以在 openresty 的安装目录手动修改配置文件

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
