### ISSUE TITLE
[FEATURE]在应用市场中提供长亭科技的雷池 WAF

### ISSUE THREAD

**Issue by safe1ine** [1Panel-dev/1Panel#2205]
### 1Panel 版本

1.5.5

### 请描述您的需求或者改进建议

在应用市场中提供长亭科技的雷池 WAF

https://github.com/chaitin/SafeLine

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，中短期内我们应该不会考虑上架上述应用，望理解。
