### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by github-zhanglei** [1Panel-dev/1Panel#2206]
### 联系方式

1204596109@qq.com

### 1Panel 版本

Debian 12.0

### 问题描述

Debian 12.0安装失败

### 重现步骤

`root@VM-24-3-debian:~# curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && bash quick_start.sh
开始下载 1Panel v1.5.5 版本在线安装包
安装包下载地址： https://resource.fit2cloud.com/1panel/package/stable/v1.5.5/release/1panel-v1.5.5-linux-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 38.8M  100 38.8M    0     0  16.3M      0  0:00:02  0:00:02 --:--:-- 16.3M
Warning: Got more output options than URLs
1panel-v1.5.5-linux-amd64/1panel.service
1panel-v1.5.5-linux-amd64/1pctl
1panel-v1.5.5-linux-amd64/LICENSE
1panel-v1.5.5-linux-amd64/README.md
1panel-v1.5.5-linux-amd64/install.sh
1panel-v1.5.5-linux-amd64/1panel

 ██╗    ██████╗  █████╗ ███╗   ██╗███████╗██╗     
███║    ██╔══██╗██╔══██╗████╗  ██║██╔════╝██║     
╚██║    ██████╔╝███████║██╔██╗ ██║█████╗  ██║     
 ██║    ██╔═══╝ ██╔══██║██║╚██╗██║██╔══╝  ██║     
 ██║    ██║     ██║  ██║██║ ╚████║███████╗███████╗
 ╚═╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝╚══════╝
[1Panel Log]: ======================= 开始安装 ======================= 
设置 1Panel 安装目录（默认为/opt）：/zhanglei
[1Panel Log]: 您选择的安装路径为 /zhanglei 
[1Panel Log]: ... 在线安装 docker 
# Executing docker install script, commit: c2de0811708b6d9015ed1a2c80f02c9b70c8ce7b
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl gnupg >/dev/null
+ sh -c install -m 0755 -d /etc/apt/keyrings
+ sh -c curl -fsSL "https://mirrors.aliyun.com/docker-ce/linux/debian/gpg" | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
+ sh -c chmod a+r /etc/apt/keyrings/docker.gpg
+ sh -c echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://mirrors.aliyun.com/docker-ce/linux/debian bookworm stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-ce-rootless-extras docker-buildx-plugin >/dev/null
E: Failed to fetch https://mirrors.aliyun.com/docker-ce/linux/debian/dists/bookworm/pool/stable/amd64/docker-ce-cli_24.0.6-1%7edebian.12%7ebookworm_amd64.deb  404  Not Found [IP: 180.213.251.232 443]
E: Failed to fetch https://mirrors.aliyun.com/docker-ce/linux/debian/dists/bookworm/pool/stable/amd64/docker-ce_24.0.6-1%7edebian.12%7ebookworm_amd64.deb  404  Not Found [IP: 180.213.251.232 443]
E: Failed to fetch https://mirrors.aliyun.com/docker-ce/linux/debian/dists/bookworm/pool/stable/amd64/docker-ce-rootless-extras_24.0.6-1%7edebian.12%7ebookworm_amd64.deb  404  Not Found [IP: 180.213.251.232 443]
E: Failed to fetch https://mirrors.aliyun.com/docker-ce/linux/debian/dists/bookworm/pool/stable/amd64/docker-compose-plugin_2.21.0-1%7edebian.12%7ebookworm_amd64.deb  404  Not Found [IP: 180.213.251.232 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
[1Panel Log]: ... 启动 docker 
Failed to enable unit: Unit file docker.service does not exist.
Failed to start docker.service: Unit docker.service not found.
[1Panel Log]: docker 安装失败  `

### 期待的正确结果

修复
![image](https://github.com/1Panel-dev/1Panel/assets/47292701/b6532d5a-1011-4529-a259-46dd9540f553)

### 相关日志输出

```shell
重现步骤中已经给出
```

### 附加信息

重现步骤中已经给出

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述问题是由于 docker 官方的在线安装脚本还未支持该操作系统导致的。
> 需要 ssh 到服务器，手动安装并运行 docker 后，再来执行 1Panel 的安装脚本（此时会跳过安装 docker）。
