### ISSUE TITLE
Fill2ban支持

### ISSUE THREAD

**Issue by zeuson** [1Panel-dev/1Panel#2209]
### 1Panel 版本

1.5.5

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/16475706/18913364-cb0b-40f6-ad5a-420a68063e59)
宝塔自带 fail2ban 的支持。刚看到 gitea 的文档中(https://docs.gitea.com/zh-cn/administration/fail2ban-setup)，也支持 fail2ban，说明是各方都通用解决方案，建议官方可以加上，对暴力破解 ssh/web密码的，都可以提高安全性
openresty与应用商店里的南墙似乎不能共存，安全性方面看还能怎么做？
![image](https://github.com/1Panel-dev/1Panel/assets/16475706/313b4e4f-4397-4d22-985b-716ed2201aa4)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复 #1643
