### ISSUE TITLE
[FEATURE] 建议加入防火墙功能

### ISSUE THREAD

**Issue by Peterzhangnoise** [1Panel-dev/1Panel#221]
### 1Panel 版本

V1

### 请描述您的需求或者改进建议

可以在面板上控制firewalld防火墙，并且支持firewalld富规则

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本就支持系统防火墙（firewalld / ufw）。

**Comment by wanghe-fit2cloud** [comment]
v1.1.0 版本已发布。
