### ISSUE TITLE
[BUG]docker存储名过长，显示不全

### ISSUE THREAD

**Issue by VMCoud** [1Panel-dev/1Panel#2210]
### 1Panel 版本

1.5.5

### 问题描述

docker存储名过长，显示不全

### 重现步骤

创建容器添加卷可见

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/59264435/894da483-d09c-4a8c-abe5-017aedc16364)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，下个版本针对上述问题做出优化。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
