### ISSUE TITLE
wordpress迁移，会导致前端样式莫名丢失

### ISSUE THREAD

**Issue by woodchen-ink** [1Panel-dev/1Panel#2211]
### 请描述您的问题

前两天琢磨宝塔的wordpress迁移到1panel，出现了如下的样式丢失，我研究了挺久，以为是两边文件系统有所不同，后来就放弃了。

今天尝试在测试服务器部署wordpress，新部署没问题，以下是步骤：(这里叫做test1站点)

1. 1panel新建运行环境，安装扩展
2. 新建数据库
3. 新建网站，基于运行环境，然后进入index目录放入全新wordpress安装包，解压
4. 导入数据库
5. 网站目录处理用户和权限，进入安装
6. 从源站点导出xml数据
7. 在新站点导入xml数据，导入插件，导入upload目录
8. 安装主题，然后没问题

然后下面就是出问题的地方了，我以为1panel部署站点没问题了，但是网站名称有点不好看，我就想换一下，于是我做了以下步骤。(这里叫test2站点)

1. 新建站点，还是基于php运行环境
2. 把test1站点的index目录，全部复制到test2站点的index目录
3. 数据库还是使用原来test1的已导入过数据的数据库
4. 配置-网站目录处设置用户和权限
5. 打开test2站点

**然后就又出现了以下如图片里的情况，非常神奇**
我对比了两边文件的权限，基本是一样的，请问为什么会出现这种情况呢？

之前用宝塔面板的时候迁移过几次网站，没有这种奇怪的问题，google了别人的，好像别人也没说过问题。我把wordpress里的缓存插件等全禁用了也没有作用。

目前test1站点被我删了，test2站点还在。对外测试地址是：http://testsh1.czl.net:5005/

![image](https://github.com/1Panel-dev/1Panel/assets/95951386/2fe88367-7143-4a3d-9d30-fe3268607529)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦到容器列表，看一下 test2 网站的容器日志。

**Comment by woodchen-ink** [comment]
> 感谢反馈，麻烦到容器列表，看一下 test2 网站的容器日志。

您好，请见附件

[1Panel-php8-gyGG-20230907114804.log](https://github.com/1Panel-dev/1Panel/files/12544399/1Panel-php8-gyGG-20230907114804.log)

**Comment by woodchen-ink** [comment]
如需登录测试，可以给一下您的邮箱，我把面板地址，账号密码，wordpress地址账号密码发给您看看

**Comment by zhengkunwang223** [comment]
> 如需登录测试，可以给一下您的邮箱，我把面板地址，账号密码，wordpress地址账号密码发给您看看

1. 查看 index 目录下 是否有 user.ini 有的话删掉
2. 重新点击网站目录的权限设置 保存 并且重建 php 应用

**Comment by woodchen-ink** [comment]
> > 如需登录测试，可以给一下您的邮箱，我把面板地址，账号密码，wordpress地址账号密码发给您看看
> 
> 1. 查看 index 目录下 是否有 user.ini 有的话删掉
> 2. 重新点击网站目录的权限设置 保存 并且重建 php 应用

都操作过了，没有效。能搜到的方法都操作过了

**Comment by zhengkunwang223** [comment]
> > > 如需登录测试，可以给一下您的邮箱，我把面板地址，账号密码，wordpress地址账号密码发给您看看
> > 
> > 
> > 
> > 1. 查看 index 目录下 是否有 user.ini 有的话删掉
> > 2. 重新点击网站目录的权限设置 保存 并且重建 php 应用
> 
> 都操作过了，没有效。能搜到的方法都操作过了

尝试新部署一个？

**Comment by woodchen-ink** [comment]
> > > > 如需登录测试，可以给一下您的邮箱，我把面板地址，账号密码，wordpress地址账号密码发给您看看
> > > 
> > > 
> > > 
> > > 1. 查看 index 目录下 是否有 user.ini 有的话删掉
> > > 2. 重新点击网站目录的权限设置 保存 并且重建 php 应用
> > 
> > 
> > 都操作过了，没有效。能搜到的方法都操作过了
> 
> 尝试新部署一个？

新部署没问题，迁移就有问题。
这个网站没几个数据还行，有另一个官网，文章几百篇也能导入，但是有非常多的基于模块化的自定义模板无法导入导出，重新设置是不现实的。
不如研究下看看为什么迁移会导致这种问题呢

**Comment by zhengkunwang223** [comment]
> > > > > 如需登录测试，可以给一下您的邮箱，我把面板地址，账号密码，wordpress地址账号密码发给您看看
> > > > 
> > > > 
> > > > 
> > > > 1. 查看 index 目录下 是否有 user.ini 有的话删掉
> > > > 2. 重新点击网站目录的权限设置 保存 并且重建 php 应用
> > > 
> > > 
> > > 都操作过了，没有效。能搜到的方法都操作过了
> > 
> > 
> > 尝试新部署一个？
> 
> 新部署没问题，迁移就有问题。 这个网站没几个数据还行，有另一个官网，文章几百篇也能导入，但是有非常多的基于模块化的自定义模板无法导入导出，重新设置是不现实的。 不如研究下看看为什么迁移会导致这种问题呢

在企业微信群吗 联系 ”程会玩“ 我远程看一下

**Comment by zhengkunwang223** [comment]
经过验证 为 wordpress 模块化主题兼容问题 此 issue 关闭

**Comment by woodchen-ink** [comment]
补充一下临时解决办法：

![image](https://github.com/1Panel-dev/1Panel/assets/95951386/ed37b55d-c719-49b5-b9ab-3c0678bec922)
