### ISSUE TITLE
[FEATURE]希望有消息通知方案，可以监控服务器日常运营项目。

### ISSUE THREAD

**Issue by sunxiaolong321** [1Panel-dev/1Panel#2213]
### 1Panel 版本

1.5.5

### 请描述您的需求或者改进建议

希望有消息通知方案，可以监控服务器日常运营项目。

希望提供消息通知项目如下：
1. Docker异常通知；
2. 服务器内存，CPU或者负载过大通知；
3. SSL证书过期通知；
4. 数据库异常通知；
5. 其他通知项目。

希望提供如下通知方式中的一中或多种
1. 飞书 2. 钉钉 3. 企业微信 4. onebot 5. telegram 6. google talk 8. 自建IM通知

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
通知、告警相关需求的讨论，统一汇总到该 issue #614
