### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Liurj1995** [1Panel-dev/1Panel#2215]
### 请描述您的问题

在面板上开启SSH后, 会出现大量的登录日志. 不清楚是否是程序问题. 并且貌似存在测试数据. 我是昨天安装的面板. 登录日志是从8月13号开始的. 部署使用的是介绍文档里面的一键脚本. 如下图
![image](https://github.com/1Panel-dev/1Panel/assets/59473785/0933f3aa-fcc0-45dc-aff1-fbf0f1f35668)

**Comment by wanghe-fit2cloud** [comment]
参考：https://bbs.fit2cloud.com/t/topic/1372/9

**Comment by Liurj1995** [comment]
> 参考：https://bbs.fit2cloud.com/t/topic/1372/9

首先十分感谢大佬回复. 小弟还有一点不太清楚. 我这边显示的登录地址都是127.0.0.1. 这意思是有病毒在我电脑上攻击ssh端口吗. 并且还有1点就是在我关闭了面板的ssh之后, 这里就再没有新的登录日志了. 是面板停止记录了吗? 如果是面板停止记录, 那就没办法解释8月13号的登录日志..... 如果没有停止记录.. 小弟怀疑是否是通过面板进行ssh端口的登录.... 个人本身不是特别了解运维与服务器相关的知识. 以上为个人愚见. 如有不当之处, 还请谅解.

**Comment by ssongliu** [comment]
1. 这里 ssh 登陆日志不是由 1panel 记录，而是由系统记录的，这也是为什么能看到安装 1panel 之前的登陆记录；
2. 1panel 只是在系统文件 (/var/log/auth.log) 里面解析出 ssh 登陆记录，所以得查一下，什么情况下系统会记录登陆 ip 为 127.0.0.1 的登陆记录。

**Comment by Liurj1995** [comment]
> 1. 这里 ssh 登陆日志不是由 1panel 记录，而是由系统记录的，这也是为什么能看到安装 1panel 之前的登陆记录；
> 2. 1panel 只是在系统文件 (/var/log/auth.log) 里面解析出 ssh 登陆记录，所以得查一下，什么情况下系统会记录登陆 ip 为 127.0.0.1 的登陆记录。

感谢回复. 我查一下谢谢.
