### ISSUE TITLE
[BUG]使用 1panel 创建容器在 host 网络下无法正常开启 

### ISSUE THREAD

**Issue by aBigChicken** [1Panel-dev/1Panel#2216]
### 1Panel 版本

v1.5.5

### 问题描述

主机环境：
发行版本 debian-12.1
内核版本 6.1.0-11-cloud-amd64
关闭防火墙

在 1panle 面板创建的容器使用 host 模式出现端口不能正常访问，
而直接使用 docker run --network host 或 compose.yml 配置的容器在 host 模式下端口开放正常。

### 重现步骤

未曾测试其它系统，不知是系统问题还是 1panel 配置命令的问题。

**Comment by wanghe-fit2cloud** [comment]
发一下具体命令，我们本地环境复现一下。
