### ISSUE TITLE
[FEATURE]容器列表页的`资源使用率`一栏支持显示详细数值

### ISSUE THREAD

**Issue by WankkoRee** [1Panel-dev/1Panel#2223]
### 1Panel 版本

1.5.5

### 请描述您的需求或者改进建议

`内存`可以显示具体数值而非百分比，有助于在多台不同配置的服务器之间对比占用情况。

### 请描述你建议的实现方案

右上角`列表设置`增加数值/百分比切换选项，另外`资源使用率`这个文本也要应该改为`资源使用情况`。

----

还有一点，现在这个CPU使用率的最大单位是`100%`，而不是Linux运维更熟悉`100%*核心数`，可能需要添加tooltip说明（毕竟docker关于cpu的limit也是与核心数挂钩的）

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
