### ISSUE TITLE
[QUESTION] php项目无法运行

### ISSUE THREAD

**Issue by dudt** [1Panel-dev/1Panel#2224]
### 请描述您的问题

发在论坛没人回复
这个源码我用宝塔可以正常运行，换到了1panel 就无法运行了。
https://bbs.fit2cloud.com/t/topic/1459
试了各种办法，实在无解了
希望可以帮忙测试一下!!

**Comment by wanghe-fit2cloud** [comment]
参考这个 [issue](https://github.com/1Panel-dev/1Panel/issues/2211)，这是其他用户的 PHP 源码部署问题排查过程。
> 我们在论坛中也有回复过你，去参考B 站的教学视频。如果还有问题就提供一下网站日志，只提供一张系统 404 截图没有办法定位问题。
