### ISSUE TITLE
[BUG]debian系统，重启系统以后，ssh管理无法自动开启

### ISSUE THREAD

**Issue by NanShaoa** [1Panel-dev/1Panel#2225]
### 1Panel 版本

v1.5.5

### 问题描述

debian系统，重启系统以后，ssh管理无法自动开启

### 重现步骤

1

**Comment by wanghe-fit2cloud** [comment]
确认一下 sshd 服务是否为 enabled 状态。
> `systemctl enable sshd` 命令可以设置开机自启
<img width="1063" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/48d1b480-25a7-467f-949f-633f08985318">

后续版本会在 ssh 管理页面增加设置自启动按钮。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
