### ISSUE TITLE
[BUG] 一直有新日志产生时网站日志无法切割，zip 压缩功能存在问题

### ISSUE THREAD

**Issue by orilights** [1Panel-dev/1Panel#2230]
### 1Panel 版本

v1.5.5

### 问题描述

破案了，是因为在执行日志切割的时候还有新日志在不停写入

我这个网站后台是一个探针程序，有好几台服务器会24小时不间断上报数据，每秒都会写入好几条日志，我把探针上报和监控全关了，网站日志切割就正常了

个人猜测在压缩日志文件前先把日志移走然后让 nginx 重新创建日志文件，再进行压缩就能解决这个问题

<details>
<summary>原内容</summary>
一直没打开网站日志切割功能，今天查看一个网站访问日志的时候提示 `文件超过10M,无法打开`

于是去计划任务里打开了日志切割功能，并手动执行了多次，任务显示是成功了，其他网站的日志都被正常切割备份了，但这个网站的日志还在原来的目录里面没有被切割

![image](https://github.com/1Panel-dev/1Panel/assets/61224409/9b9b5b4d-bae1-41d2-94b0-ab8a86d86b90)
</details>

另外在尝试对日志进行压缩的过程中发现使用 1Panel 的文件管理对文件进行 zip 压缩时，输出的文件与原文件几乎一样大，其他格式正常

以下是将 `dd if=/dev/zero of=100M.file bs=1M count=100` 命令生成的空文件使用 1Panel 的文件管理进行压缩的结果，可以看到 zip 压缩的结果明显存在问题

![image](https://github.com/1Panel-dev/1Panel/assets/61224409/c30b7c05-ae91-4b45-bf0b-1dc2361ed40f)

### 重现步骤

使用计划任务切割一直有新日志产生的网站日志

使用 1Panel 的文件管理功能压缩 zip 文件

**Comment by ssongliu** [comment]
感谢反馈！我们先在开发环境复现一下这个问题。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布，修复了切割失败的问题。
zip 压缩后文件没有变化的问题，计划在下个版本修复 #3575
