### ISSUE TITLE
[QUESTION] 使用http方式创建证书失败

### ISSUE THREAD

**Issue by MomentDerek** [1Panel-dev/1Panel#2231]
### 请描述您的问题

【论坛已发同名帖子】
版本：v1.5.5
在创建好网站后，使用了反向代理，但是创建证书前已经将反向代理删除

![image](https://github.com/1Panel-dev/1Panel/assets/40252940/4f4a9c86-9e28-4e15-a72a-fcd893dae6fb)

创建证书的入参（已将网站隐去）：
```
{"primaryDomain":"****.com","otherDomains":"","provider":"http","websiteId":0,"acmeAccountId":1,"dnsAccountId":1,"autoRenew":true}
```

服务内部错误: error: one or more domains had a problem:
[ai.momincong.com] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 111.****.184: Fetching http://*****.com/.well-known/acme-challenge/0xbhmzTRQKdh03CxxlHVyvN4kdjZQ4C0XcwR-LEKwNo: Error getting validation data

我看到网站自动创建的配置文件中，.well-known是指向`/usr/share/nginx/html`的，但我看系统里似乎并没有这个目录，是不是有什么bug？证书http申请时的验证文件是放在这里的么？代码里似乎也没找到对应的验证文件生成（可能是我看漏了，不是专业的go程序员）

```nginx
location ~ /.well-known/acme-challenge {
        allow all; 
        root /usr/share/nginx/html; 
    }
```

**Comment by zhengkunwang223** [comment]
HTTP 模式申请证书需要你的网站可访问

**Comment by M1saka10010** [comment]
> HTTP 模式申请证书需要你的网站可访问

遇到了同样的问题，在之前的版本中没有出现过

**Comment by MomentDerek** [comment]
1panel的防火墙没开80和443端口导致，可以在申请前做一次防火墙检查 @zhengkunwang223
