### ISSUE TITLE
[BUG]php环境创建的容器无法通过ip:端口访问

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#2233]
### 1Panel 版本

1.5.5

### 问题描述

因为想试用一下第三方waf，而第三方waf加防护时需要上游服务器，但php站点的ip:端口却用不了。
而在浏览器里尝试访问每个容器所对应的ip:端口时，安装的其他应用都正常访问，但是php创建的容器 无法通过ip:端口访问而php容器绑定的域名是可以正常访问的

### 重现步骤

访问一下php创建网站后 的ip:端口

### 期待的正确结果

php网站正常用第三方waf

**Comment by zhengkunwang223** [comment]
php 运行环境创建的容器为 Fpm 容器，无法对外提供 web 服务， 1.6 版本支持 openresty 设置端口，可以先用 openresty 代理 php 端口，再通过 waf 反代

**Comment by Felmon** [comment]
> php 运行环境创建的容器为 Fpm 容器，无法对外提供 web 服务， 1.6 版本支持 openresty 设置端口，可以先用 openresty 代理 php 端口，再通过 waf 反代

创建php网站的时候域名填ip：端口，然后去waf里反代这个ip：端口？但是这里不让填ip：端口啊
![image](https://github.com/1Panel-dev/1Panel/assets/19621032/c6fc7e99-05b3-4686-82c0-4a4fd2e26138)
有没有具体的教程呀

**Comment by zhengkunwang223** [comment]
> > php 运行环境创建的容器为 Fpm 容器，无法对外提供 web 服务， 1.6 版本支持 openresty 设置端口，可以先用 openresty 代理 php 端口，再通过 waf 反代
> 
> 创建php网站的时候域名填ip：端口，然后去waf里反代这个ip：端口？但是这里不让填ip：端口啊 ![image](https://user-images.githubusercontent.com/19621032/266930224-c6fc7e99-05b3-4686-82c0-4a4fd2e26138.png) 有没有具体的教程呀

已纳入计划 后续版本支持

**Comment by zhengkunwang223** [comment]
已支持
