### ISSUE TITLE
phpmyadmin如何配置ssl

### ISSUE THREAD

**Issue by github-zhanglei** [1Panel-dev/1Panel#2236]
### 请描述您的问题

宝塔是直接沿用面板ssl让后在域名 或者 ip后面加端口号就可以了；docker中怎么配置phpmyadmin ssl

**Comment by wanghe-fit2cloud** [comment]
在应用商店中安装 phpMyAdmin 应用时，还不支持开启 SSL。当前版本可以考虑在高级设置中编辑 compose 文件来设置 SSL。
> 我们会在后续版本考虑支持。

**Comment by github-zhanglei** [comment]
经过这几天刷论坛以及学习，实际上是自己不会操作；想要实现SSL其实很简单，直接在面板-网站-创建网站-选择反向代理-绑定域名证书SSL即可，成功安装请看下图；非常感谢开发出来这么牛逼的面板
![image](https://github.com/1Panel-dev/1Panel/assets/47292701/acced987-d91a-42da-a8dd-cbcbb40baa72)
![image](https://github.com/1Panel-dev/1Panel/assets/47292701/578b3b4c-c369-4321-8df7-9075eaca6c88)
![image](https://github.com/1Panel-dev/1Panel/assets/47292701/34ac6106-252c-4cdf-b3af-5715767e0750)

**Comment by github-zhanglei** [comment]
希望开发团队聚焦重点比如对nodes、java等等的环境支持，我这个就不用优化了。

**Comment by wanghe-fit2cloud** [comment]
> 希望开发团队聚焦重点比如对nodes、java等等的环境支持，我这个就不用优化了。

计划在 1.7 版本开始，支持 pm2 管理器。
