### ISSUE TITLE
[BUG]OpenResty防盗链似乎无效

### ISSUE THREAD

**Issue by fenglindubu** [1Panel-dev/1Panel#2237]
### 1Panel 版本

1.5.5

### 问题描述

通过反向代理到容器，开启https，设置防盗链，测试发现无效

### 重现步骤

通过反向代理到容器，开启https，设置防盗链，测试发现无效

**Comment by zhengkunwang223** [comment]
请问是怎么测试的？

**Comment by fenglindubu** [comment]
> 

就是正常测试啊 允许来源为空 关掉，允许的域名 全部删掉，别的域名 或者直接访问还是有图片啊，浏览器强制刷新的

**Comment by fenglindubu** [comment]
> 请问是怎么测试的？

你们复现成功了吗？

**Comment by zhengkunwang223** [comment]
> > 请问是怎么测试的？
> 
> 你们复现成功了吗？

您好 没有复现   
我在 Halo 创建了一篇文章 然后包含图片 开启防盗链 使用   curl --referer http://baidu.com -I "http://xx.com/upload/logo%20(1).png"  访问 返回 404 关闭防盗链 返回 200

**Comment by fenglindubu** [comment]
> 

你好，我使用一键部署wordpress 发现开启防盗链，js css 返回404，扩展名已经添加 js,css,png,jpg,jpeg,gif,ico,bmp,swf,eot,svg,ttf,woff,woff2

允许的域名 也包含在内，同样返回404.

因为都是容器，商店里lsky pro 通过反向代理使用，发现防盗链无效，请复现一下

**Comment by JsonLYH** [comment]
> > 
> 
> 你好，我使用一键部署wordpress 发现开启防盗链，js css 返回404，扩展名已经添加 js,css,png,jpg,jpeg,gif,ico,bmp,swf,eot,svg,ttf,woff,woff2
> 
> 允许的域名 也包含在内，同样返回404.
> 
> 因为都是容器，商店里lsky pro 通过反向代理使用，发现防盗链无效，请复现一下

我也是通过反向代理的，设置防盗链无效
