### ISSUE TITLE
阿里云快照同步问题[QUESTION]

### ISSUE THREAD

**Issue by micro-CAO** [1Panel-dev/1Panel#2239]
### 请描述您的问题

1panel的快照是如何从阿里云oss拉取的？我在一台服务器上备份了快照到oss，但我从另一台服务器上却拉取不到那个快照，是怎么回事？
![IMG_20230909_002722](https://github.com/1Panel-dev/1Panel/assets/70780880/2694350b-2412-4f3a-91d0-5c284e12ed79)

如果可以，是否能设计一项功能，让我能够手动从oss所有文件中 选择备份的快照？谢谢

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by ssongliu** [comment]
两边备份目录的文件夹选择是否一致呢？是最新的版本吗？

**Comment by ssongliu** [comment]
开发环境暂时没有复现这个问题，先关闭了，后续还有问题可以再打开。
