### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by skyhhjmk** [1Panel-dev/1Panel#2240]
### 1Panel 版本

v1.5.5

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/78078552/be33e658-7daf-415b-a7e2-ba93814975f0)

同步快照时遇到问题

### 重现步骤

使用一台服务器备份快照至OneDrive企业版，重装系统后安装1panel，添加OneDrive备份账号，同步快照时出现问题

# 分析出的可能的原因
1. 备份快照时没有指定备份目录，默认备份在system_snapshot目录下

**Comment by wanghe-fit2cloud** [comment]
#2241
