### ISSUE TITLE
[BUG]OneDrive快照同步失败

### ISSUE THREAD

**Issue by skyhhjmk** [1Panel-dev/1Panel#2241]
### 1Panel 版本

v1.5.5

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/78078552/aeccda1a-5855-4087-b277-1ca9407192b5)

### 重现步骤

备份快照-重装系统-恢复快照时出错

**Comment by skyhhjmk** [comment]
应该是“同步快照时出错”

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by ssongliu** [comment]
两边备份目录的文件夹选择是否一致呢？是最新的版本吗？

**Comment by ssongliu** [comment]
开发环境暂时没有复现这个问题，先关闭了，后续还有问题可以再打开。
