### ISSUE TITLE
[QUESTION]80端口已被openresty占用

### ISSUE THREAD

**Issue by W4J1e** [1Panel-dev/1Panel#2242]
### 请描述您的问题

以前用 nginx 的时候从来没遇到过类似的问题，今天想试试 1panel 最近更新新增的那个 waf，结果就提示这个，这可咋整啊？
![20230909171219](https://github.com/1Panel-dev/1Panel/assets/74824162/8fee3596-eb16-4f54-9b97-b56a6fb30a50)

**Comment by wanghe-fit2cloud** [comment]
下个版本(v1.6.0)将会支持自定义 OpenResty 端口。

**Comment by W4J1e** [comment]
> 下个版本(v1.6.0)将会支持自定义 OpenResty 端口。

其实我有个疑问哈，在我的理解里，waf 要监测网站的流量是否含有恶意请求，所以必然要监控网站使用的端口，是这个样子吗？
如果是，那么 OpenResty 自定义其它端口的话，waf 依然无法监测到那个站点的流量请求；如果不是的话，OR 换成了比如 https 444这个端口，那我访问用OR建的站是不是还得在域名后面加上 444 呢？

**Comment by zhengkunwang223** [comment]
> 

如果是纯反向代理网站 可以直接通过 uuwaf 管理 如果是 PHP 这种需要 openresty 做端口映射的 可以先在 openresty 创建一个带端口的网站 然后通过 uuwaf 的反代功能添加网站

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本安装 OpenResty 应用时，支持修改默认端口。

**Comment by shkouyo** [comment]
如果卸载OpenResty再修改端口重装会删除网站数据吗，如果会有没有办法无损修改端口
