### ISSUE TITLE
[BUG] WordPress一键部署无法查看网站日志

### ISSUE THREAD

**Issue by KwaziBell** [1Panel-dev/1Panel#2243]
### 1Panel 版本

v1.5.5

### 问题描述

WordPress一键部署的网站无法查看日志，提示“请求超时！请您稍后重试”，其他类型的网站正常。OpenResty没有日志输出。

### 重现步骤

网站-网站-配置-日志（加载一会）→提示 “请求超时！请您稍后重试”，日志表显示“当前没有日志...“

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦提供一下服务器操作系统版本和 cpu、内存等配置信息。
> 我们在本地开发环境未复现上述问题。

**Comment by KwaziBell** [comment]
> 感谢反馈，麻烦提供一下服务器操作系统版本和 cpu、内存等配置信息。
> 
> > 我们在本地开发环境未复现上述问题。

**Comment by KwaziBell** [comment]
> 感谢反馈，麻烦提供一下服务器操作系统版本和 cpu、内存等配置信息。
> 
> > 我们在本地开发环境未复现上述问题。

Intel(R) Xeon(R) CPU E5-2660
内存  11976.26 MB
发行版本 ubuntu-20.04
内核版本 5.4.0-110-generic
系统类型 x86_64

**Comment by wanghe-fit2cloud** [comment]
本地环境依旧未能复现上述问题。

可以进一下交流群，加我好友远程看一下问题：
<img src="https://1panel.cn/img/wechat-group.jpg" width="156" height="156"/>
