### ISSUE TITLE
[BUG] 禅道安装后无法访问

### ISSUE THREAD

**Issue by lnlion** [1Panel-dev/1Panel#2244]
### 联系方式

leanclose@126.com

### 1Panel 版本

1.5.5

### 问题描述

禅道安装后无法访问，看容器的日志一直重复提示数据库安装初始化中

### 重现步骤

1. 安装禅道
2. 数据库端口3307
3. 数据库密码，同已安装的MySQL8.1 root的密码
4. 开启了外部端口访问
5. 端口号从8080改为9090

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
刚在本地环境复现了上述问题，具体修复方案可参考：[旧版Docker镜像升级说明](https://www.zentao.net/book/zentaopms/1059.html)

> v1.6.0 版本开始，我们也将会适配新版镜像。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
