### ISSUE TITLE
[BUG]php 无法构建

### ISSUE THREAD

**Issue by maxlee123456** [1Panel-dev/1Panel#2245]
### 1Panel 版本

v1.5.5

### 问题描述

<img width="852" alt="1694321812435" src="https://github.com/1Panel-dev/1Panel/assets/63325897/075f2a28-3f4c-4eae-bc99-9aaccd38e9ac">

构建 php:5.6.40
失败信息：
镜像 build 失败:failed to solve: executor failed running [/bin/sh -c apk add gnu-libiconv libstdc++ --no-cache --repository http://${CONTAINER_PACKAGE_URL}/alpine/edge/community/ --allow-untrusted]: exit code: 139

### 重现步骤

构建7.4.33 和 8.2.5 成功  构建5.6.40 、7.0.33都失败  都是同样报错

- 镜像 build 失败:failed to solve: executor failed running [/bin/sh -c apk add gnu-libiconv libstdc++ --no-cache --repository http://${CONTAINER_PACKAGE_URL}/alpine/edge/community/ --allow-untrusted]: exit code: 139

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by feedeve** [comment]
一样，我还以为是我的问题， 我是所有版本都无法构建。
![1694398210964](https://github.com/1Panel-dev/1Panel/assets/24806368/892501ce-611d-4e07-ab2a-ea496722255c)

**Comment by wanghe-fit2cloud** [comment]
刚在本地环境复现了上述问题，是因为在某些低版本 php 镜像中，镜像源已经停止维护的原因。
> 我们会在 v1.6.0 版本中尝试修复这个问题。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
