### ISSUE TITLE
建议应用商店直接 默认弄几个常用的php版本的应用

### ISSUE THREAD

**Issue by xysemies** [1Panel-dev/1Panel#2246]
### 1Panel 版本

V1.5.5

### 请描述您的需求或者改进建议

因为 创建php运行环境 老是无法成功,一直转啊转.

更换镜像也无法成功.
尝试了海外的服务器也不行...

![Snipaste_2023-09-10_16-53-55](https://github.com/1Panel-dev/1Panel/assets/23214570/6d45ac68-09c8-491e-8189-5f2286f411ff)

### 请描述你建议的实现方案

何不像wordpress那样 直接弄个php 8.2的应用 直接拉你们的镜像.
感觉可以省事很多.

然后 php创建运行环境的时候可以看到日志进度,也知道卡在哪里了.
宝塔一开始创建运行环境的时候 也有这种日志功能,觉得很不错.

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。
> 镜像拉取超时的问题，可以到 `容器` - `配置` 页面添加镜像加速。

**Comment by maninhill** [comment]
最好能有日志进度。

**Comment by godcong** [comment]
是不是节点被墙了,你挂个阿里云docker加速试试看

**Comment by wanghe-fit2cloud** [comment]
最新版本已经支持实施查看运行环境日志。
