### ISSUE TITLE
[FEATURE]希望增加OpenResty的upstream模块支持

### ISSUE THREAD

**Issue by ardenboy** [1Panel-dev/1Panel#2247]
### 1Panel 版本

2.9

### 请描述您的需求或者改进建议

Nginx或OpenResty都支持upstream模块，这个模块做端口转发或负载均衡平时用到都挺多的，用[nginxWebUI ](https://github.com/cym1102/nginxWebUI)被黑过，无奈现在还在使用，希望能增加这个功能!

### 请描述你建议的实现方案

增加tcp协议转发, 反向代理, 负载均衡功能

nginxWebUI
演示地址: http://test.nginxwebui.cn:7070
用户名: admin
密码: admin

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wujunze** [comment]
希望加上 OpenResty的upstream模块支持 
谢谢 @wanghe-fit2cloud

**Comment by wanghe-fit2cloud** [comment]
重复 #2058
