### ISSUE TITLE
[QUESTION]PHP5.2需求

### ISSUE THREAD

**Issue by liufuyou** [1Panel-dev/1Panel#2248]
### 请描述您的问题

使用需求：php5.2，但php最低没有5.2，最低是5.3
看到面板默认不向外暴露端口，想使用5.2。想尝试使用5.2。
请问怎样添加PHP5.2

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们目前不支持用户自定义 PHP 版本。
> 考虑到低版本存在的一些高危漏洞，还是建议使用官方提供的版本（大于等于 5.4）

**Comment by liufuyou** [comment]
请问官方可能会支持PHP5.2吗？
或者有什么快捷的，使用PHP5.2的方法吗？

**Comment by wanghe-fit2cloud** [comment]
经过调研分析，我们在中短期内应该不会考虑支持 PHP 5.2。
当前版本可以考虑使用 `容器` 页面的创建容器或者编排的方式来启动 PHP 容器。
