### ISSUE TITLE
[FEATURE] 希望概览面板增加可自定义域名的主页图标

### ISSUE THREAD

**Issue by 50007** [1Panel-dev/1Panel#2249]
### 1Panel 版本

v1.5.5

### 请描述您的需求或者改进建议

希望概览面板增加可自定义域名的主页图标

### 请描述你建议的实现方案
![image](https://github.com/1Panel-dev/1Panel/assets/143870542/9f78fcad-7284-463f-8c24-766cc2cbcdff)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
目前概览页面的 `推荐应用` 内容为官方内置，暂不支持修改。
