### ISSUE TITLE
1panel在docker中部署的，希望可以改主机默认[FEATURE]

### ISSUE THREAD

**Issue by xkloveme** [1Panel-dev/1Panel#2250]
### 1Panel 版本

1.5.5

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/29595042/bfe795e2-201d-45fa-b37a-05eeab99f6b4)
![image](https://github.com/1Panel-dev/1Panel/assets/29595042/7f0a9a87-94ed-4600-92ee-bbb7bbe86792)
![image](https://github.com/1Panel-dev/1Panel/assets/29595042/6a6ba79d-2a73-42dc-b37e-6040b82eaaea)
![image](https://github.com/1Panel-dev/1Panel/assets/29595042/6ebac4df-74b8-4a4b-9797-aba7b85965b3)

### 请描述你建议的实现方案

如上

**Comment by xkloveme** [comment]
希望主机连接可以改字体，兼容zsh

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们目前还未提供容器化部署 1Panel 的官方解决方案。
> 后续版本可能会考虑支持上述需求。
