### ISSUE TITLE
[FEATURE]增加 Swap内存状态显示

### ISSUE THREAD

**Issue by VMCoud** [1Panel-dev/1Panel#2251]
### 1Panel 版本

1.5.5

### 请描述您的需求或者改进建议

增加 Swap内存状态显示

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，请问上述需求是计划在概览页面的内存状态增加提示框显示吗？

**Comment by VMCoud** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/59264435/2ec2b47b-442f-4307-a080-96d3036d23a7)
可以这样显示

**Comment by wanghe-fit2cloud** [comment]
> 可以这样显示

收到，后续考虑支持。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
