### ISSUE TITLE
[BUG]自带PHP容器无法安装GD扩展

### ISSUE THREAD

**Issue by godcong** [1Panel-dev/1Panel#2254]
### 1Panel 版本

v1.5.5

### 问题描述

安装PD时需要用到相关的lib插件.
libwebp-dev libjpeg-dev libpng-dev libfreetype6-dev
容器没有apt无法安装这些插件.
使用php-ext-install安装GD失败.

另外网站->运行环境中的PHP扩展选中安装后没有效果.
只能进容器一个一个手动安装.

### 重现步骤

1. 进入容器后台
2. 执行 docker-php-ext-install gd

**Comment by wanghe-fit2cloud** [comment]
> 网站 -> 运行环境中的PHP扩展选中安装后没有效果

麻烦提供一下创建 PHP 运行环境的版本。
如果是扩展下拉框中不存在的扩展，也支持手动输入。

**Comment by godcong** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/2727298/a99ef5fa-f5b3-4893-b923-2b8bfd3d1a87)
![image](https://github.com/1Panel-dev/1Panel/assets/2727298/038f5809-4e6d-42ae-8199-2b23730d61d4)
用的商店的PHP7.4, 一开始是按照Mysql扩展,运行环境里面选好以后还是没效果.
后面就直接进容器安装了...

GD是完全安装不上了,少了lib...

**Comment by godcong** [comment]
实在不行有没有啥临时的解决方法...

**Comment by godcong** [comment]
好像找到问题了...容器部署后,再修改运行环境好像不会改变已经部署的容器,所以一直装不上...

**Comment by zhengkunwang223** [comment]
> 好像找到问题了...容器部署后,再修改运行环境好像不会改变已经部署的容器,所以一直装不上...

是的 需要重建 PHP 应用 v1.6 版本会支持编辑之后自动重建
