### ISSUE TITLE
[BUG]openresty 安装失败 创建的nginx 都是文件夹

### ISSUE THREAD

**Issue by motoabc** [1Panel-dev/1Panel#2258]
### 1Panel 版本

v1.5.5

### 问题描述

1Panel 版本

问题描述
openresty
类似问题，全新安装 ，ARM环境 ubuntu 22.04

stderr: Container 1Panel-openresty-9nV3 Creating Container 1Panel-openresty-9nV3 Created Container 1Panel-openresty-9nV3 Starting Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/opt/1panel/apps/openresty/openresty/conf/nginx.conf" to rootfs at "/usr/local/openresty/nginx/conf/nginx.conf": mount /opt/1panel/apps/openresty/openresty/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

![image](https://github.com/1Panel-dev/1Panel/assets/18234691/b0d44834-1dd6-455a-8da4-7336300a7de7)

创建的配置文件都是文件夹啊

### 重现步骤

ARM ubuntu 22.04 全新安装

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述问题已修复。
> 卸载 Openresty 之后，手动更新应用商店，重新安装。

**Comment by motoabc** [comment]
https://1panel.cn/docs/faq/server_architecture/

是这个问题吗？
