### ISSUE TITLE
[BUG]备份到cloudflare R2失败

### ISSUE THREAD

**Issue by iLayPark** [1Panel-dev/1Panel#2260]
### 1Panel 版本

1.5.5

### 问题描述

备份到cloudflare R2失败，且没有错误日志

### 重现步骤

备份到cloudflare R2失败，且没有错误日志

### 相关日志输出

```shell
[2023-09-12 02:30:00] [INFO] start to backup database 备份数据库 to S3  
[2023-09-12 02:30:00] [INFO] start to mysqldump | gzip > /www/1panel/backup/database/mysql/mysql/pay/db_pay_20230912023000.sql.gz.gzip
```

**Comment by ssongliu** [comment]
感谢反馈！请确认一下以下信息：
1. /www/1panel/backup/database/mysql/mysql/pay 这个文件夹下对应的备份文件是否有正确生成；
2. 使用的是计划任务进行备份吗？计划任务报告里面错误信息显示的是啥？
3. 可以提供详细一点的日志输出。

**Comment by iLayPark** [comment]
> 1. /www/1panel/backup/database/mysql/mysql/pay

1、生成了
2、是计划任务
NotImplemented: Header 'x-amz-storage-class' with value 'GLACIER' not implemented status code: 501, request id: , host id:

以前成功过，后来升级了几次，不确定是哪次升级之后开始失败的

**Comment by ssongliu** [comment]
看起来像是 s3 的 sdk 版本太老导致的，我们先在开发环境复现一下。

https://github.com/aws/aws-sdk-go/issues/1379

**Comment by ssongliu** [comment]
没有复现这个问题，可以再检查一下 cloudflare R2 的配置是否有修改，如果还是有问题的话可以重新打开这个 issue 或者添加社区群反馈。
