### ISSUE TITLE
[BUG]no such file or directory

### ISSUE THREAD

**Issue by budou0608** [1Panel-dev/1Panel#2269]
### 联系方式

1769794040@qq.vom

### 1Panel 版本

1.5.5

### 问题描述

本地应用安装报错：stat /opt/1panel/resource/apps/local/wukongim/1.0.0: no such file or directory
![image](https://github.com/1Panel-dev/1Panel/assets/22893139/7e85cc29-6574-4f5e-826c-caaa3fafb4ab)

### 重现步骤

本地应用安装报错：stat /opt/1panel/resource/apps/local/wukongim/1.0.0: no such file or directory
![image](https://github.com/1Panel-dev/1Panel/assets/22893139/e97fb326-77d3-4a46-ae52-756c8aad6bbe)

**Comment by wanghe-fit2cloud** [comment]
本地应用包格式不对吧，到本地应用目录中截图看一下。
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/a330c946-06b0-4972-bd79-10f56e912688)

**Comment by budou0608** [comment]
<img width="339" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/22893139/11bc27d4-16e4-42da-88f4-2b17299d5b65">

**Comment by wanghe-fit2cloud** [comment]
> `pwd` 命令看一下文件夹全路径。

再提供一下本地应用文件夹及子目录权限。

**Comment by budou0608** [comment]
问题解决了，文件夹的名字是`wukong-im`，和`wukong-im/data.yml`的`name`不一致
```yaml
name: wukongim
```
