### ISSUE TITLE
希望备份账号功能下第三方账号功能可以多支持一些云存储厂商

### ISSUE THREAD

**Issue by miaowmint** [1Panel-dev/1Panel#227]
### 1Panel 版本

v1.0.1

### 请描述您的需求或者改进建议

备份账号功能下第三方账号支持的还是太少了，比如就我个人来说用的比较多的腾讯云COS就不支持

### 请描述你建议的实现方案

多支持一些云存储厂商

**Comment by zhengkunwang223** [comment]
感谢建议，我们考虑一下

**Comment by ruibaby** [comment]
理论上只要云厂商兼容 S3 协议，应该就可以用现有的 S3 云存储来备份，可以尝试一下。

<img width="572" alt="image" src="https://user-images.githubusercontent.com/21301288/225285527-65dd4b72-ee4d-4289-9242-d70ddc2376a9.png">

腾讯云 COS 是支持 S3 协议的，请参考：https://cloud.tencent.com/document/product/436/41284

**Comment by miaowmint** [comment]
> 理论上只要云厂商兼容 S3 协议，应该就可以用现有的 S3 云存储来备份，可以尝试一下。
> 
> <img alt="image" width="572" src="https://user-images.githubusercontent.com/21301288/225285527-65dd4b72-ee4d-4289-9242-d70ddc2376a9.png">
> 
> 腾讯云 COS 是支持 S3 协议的，请参考：https://cloud.tencent.com/document/product/436/41284

我试过了，确实是可以的，但是还是希望能够独立出来一个，或者是在`亚马逊 S3 云存储`后面说明一下也支持腾讯云COS，毕竟像我这种第一次用的确实不知道可以兼容

**Comment by ruibaby** [comment]
@wanghe-fit2cloud 可以考虑在界面上提示一下 S3 协议之类的，文档也可以补充一下。目前绝大部分对象存储厂商都是支持 S3 的，没有必要再额外的支持某个厂商。

可以参考：https://github.com/halo-sigs/plugin-s3#%E9%83%A8%E5%88%86%E5%AF%B9%E8%B1%A1%E5%AD%98%E5%82%A8%E6%9C%8D%E5%8A%A1%E5%95%86%E5%85%BC%E5%AE%B9%E6%80%A7

**Comment by wanghe-fit2cloud** [comment]
> @wanghe-fit2cloud 可以考虑在界面上提示一下 S3 协议之类的，文档也可以补充一下。目前绝大部分对象存储厂商都是支持 S3 的，没有必要再额外的支持某个厂商。
> 
> 可以参考：https://github.com/halo-sigs/plugin-s3#%E9%83%A8%E5%88%86%E5%AF%B9%E8%B1%A1%E5%AD%98%E5%82%A8%E6%9C%8D%E5%8A%A1%E5%95%86%E5%85%BC%E5%AE%B9%E6%80%A7

非常中肯的建议，感谢支持。
