### ISSUE TITLE
[BUG] 创建docker容器时，暴露端口添加了之后不填写，切换到暴露所有点击确认还是会进行提示

### ISSUE THREAD

**Issue by leoFitz1024** [1Panel-dev/1Panel#2275]
### 1Panel 版本

1.55

### 问题描述

创建docker容器时，暴露端口添加了之后不填写，切换到暴露所有点击确认还是会进行提示

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/29174699/722d1f4e-3956-415e-bcc7-052ed80756c4)
![image](https://github.com/1Panel-dev/1Panel/assets/29174699/0b210b85-7fda-48a8-a03b-7526513af1cd)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本修复这个问题。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
