### ISSUE TITLE
[FEATURE]建议在应用商店中增加smb、nfs共享的管理应用工具

### ISSUE THREAD

**Issue by 5557965** [1Panel-dev/1Panel#2282]
### 1Panel 版本

1.5.5

### 请描述您的需求或者改进建议

建议在应用商店中增加smb、nfs共享的管理应用工具，方便共享服务器文件给其他机器。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑添加上述应用。

**Comment by wanghe-fit2cloud** [comment]
磁盘相关需求的讨论，统一汇总到该 issue #1852
