### ISSUE TITLE
[FEATURE]增加清除OpenResty反向代理缓存功能

### ISSUE THREAD

**Issue by WankkoRee** [1Panel-dev/1Panel#2288]
### 1Panel 版本

1.5.5

### 请描述您的需求或者改进建议

即删除目录`/opt/1panel/apps/openresty/openresty/www/common/proxy/proxy_cache_dir`中的所有文件。

> 这个路径可能会因为1panel安装目录、容器名等原因存在区别，所以不一定一样，但是容器内路径肯定是`/www/common/proxy/proxy_cache_dir/`（除非修改了配置项`proxy_cache_path`）。

有时候服务端改动了一些文件或者响应策略（如图片处理算法），但由于缓存策略等原因，OpenResty认为文件未发生改变，所以不会去更新缓存，导致提供的文件一直是改动前的。

### 请描述你建议的实现方案

感觉放在设置里面，或者直接在设置后面加个“清除反向代理缓存”都可以。

![image](https://github.com/1Panel-dev/1Panel/assets/21287731/5b8e677b-a40c-424e-8033-25045f842aa8)

**Comment by zhengkunwang223** [comment]
感谢反馈 后续版本优化

**Comment by AeroWang** [comment]
@zhengkunwang223 确实有点问题，需要被反向代理的服务我都手动关闭了，网站还能访问，而且

<img width="1754" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/44799877/cbd1e819-e7a6-44a8-8e33-5ee293acb7f1">

这里我从一开始就没有打开，也给我缓存上了。服务里的文件我都明显修改了，还是缓存上了，我还以为我的服务出了问题。

最后按照 @WankkoRee 在此 issue 中提供的方法解决掉这个迷惑的缓存问题。

另外，手动清除该目录的缓存文件之后，我确信我未开启反向代理缓存，但是网站访问一次后，该文件夹内再次出现了缓存，导致网站获取到的后端（next.js revalidate 之后）的资源文件不是最新（手动更新后验证）。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
