### ISSUE TITLE
【服务内部错误】7个网站5个服务内部错误。。。【加急！】

### ISSUE THREAD

**Issue by taurusduan** [1Panel-dev/1Panel#2289]
### 请描述您的问题

五个网站创建反代全部显示服务内部错误。
![image](https://github.com/1Panel-dev/1Panel/assets/30854760/5e557838-17f1-42c1-b6eb-e61b4c1925c7)
要说有问题吧，其他两个没有问题，要说没有问题吧，其他五个就是创建不了。

**Comment by taurusduan** [comment]
唉~静态页都创建不了。。。
![image](https://github.com/1Panel-dev/1Panel/assets/30854760/95bc79bd-0cbe-400f-8049-6c63c2604ccf)

**Comment by taurusduan** [comment]
全部试了一遍
![image](https://github.com/1Panel-dev/1Panel/assets/30854760/e93d4647-fe11-475f-a92f-c9b5a4dc9b7a)

**Comment by zhengkunwang223** [comment]
在群里吗 联系“程会玩” 给你远程一下

**Comment by seepine** [comment]
最新版还是有这个问题，新的服务器就安装了1panel，新增网站，或者已有网站修改配置或修改ssl，保存都会出现这个错误，有时候一直提交突然可以，有的一直提交一直是这个错误
