### ISSUE TITLE
升级后无法打开

### ISSUE THREAD

**Issue by qq63063** [1Panel-dev/1Panel#2290]
### 请描述您的问题

1.5.5 升级 1.6.0 之后  面板无法打开  
![image](https://github.com/1Panel-dev/1Panel/assets/93641848/9cab205d-237a-4f5a-b435-189802ed4a94)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by ssongliu** [comment]
应该是添加的远程数据库里面，有和应用名称一样的数据库，这样会导致名称冲突。

> 比如添加了名称为 mariadb 的远程数据库，然后在应用商店中也创建了一个名称为 mariadb 的应用。

**Comment by wanghe-fit2cloud** [comment]
### 临时修复方案：

1、通过 `1pctl restore` 命令回滚到上一个稳定版本
2、等待 1Panel 服务启动成功，然后进去 MySQL 数据库列表页，点击 `远程服务器按钮`
3、修改已添加的远程数据库名称
4、点击右下角 `检查更新` 按钮，升级 1Panel 系统

**Comment by wanghe-fit2cloud** [comment]
v1.6.1 版本已发布。
