### ISSUE TITLE
[FEATURE]应用商店列表上部分希望添加翻页

### ISSUE THREAD

**Issue by okxlin** [1Panel-dev/1Panel#2293]
### 1Panel 版本

v1.6.0

### 请描述您的需求或者改进建议

如题

![image](https://github.com/1Panel-dev/1Panel/assets/61420215/2be8b0c0-2856-4096-99d7-8338a0a1e0ac)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们计划在 v1.7.0 版本完成上述优化。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
