### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by fzlinjianhui** [1Panel-dev/1Panel#2294]
### 请描述您的问题

请问，现在已经装了宝塔的机子上直接再装上1panel，有没有什么影响，想从宝塔换掉，但是又不敢直接卸载宝塔（因为数据库用宝塔在管理），想先再装上1panel后再卸载宝塔

**Comment by wanghe-fit2cloud** [comment]
1Panel 的安装只涉及到二进制文件，在保证端口不冲突的情况下安装是没有问题的。
