### ISSUE TITLE
[FEATURE]增加所在目录打开终端。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#2297]
### 1Panel 版本

v1.6.0

### 请描述您的需求或者改进建议

每次用到目录都有复制下路径再去终端处，很麻烦！建议在文件管理处增加个当前目录打开终端，也挺常用的吧！！！

### 请描述你建议的实现方案

![image](https://github.com/1Panel-dev/1Panel/assets/93708226/2cdcc331-bc43-45d7-bbd6-7255f9a367cc)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本针对 `主机` - `文件` 做一次重构，到时我们会考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复 #958
