### ISSUE TITLE
[BUG] 防火墙端口增加描述信息后端口信息消失

### ISSUE THREAD

**Issue by realzolo** [1Panel-dev/1Panel#2298]
### 联系方式

zolo@onezol.com

### 1Panel 版本

v1.6.0

### 问题描述

从v1.5.5升级v1.6之后，防火墙给已有端口添加描述信息，点击确认之后这个端口就消失了，不会在列表页面展示了。

### 重现步骤

给已有端口增加描述信息
![image](https://github.com/1Panel-dev/1Panel/assets/63219216/9e91b2f6-141a-474c-9eb3-8271e1bf6bfa)
![image](https://github.com/1Panel-dev/1Panel/assets/63219216/c674d75e-e5f6-40aa-9c74-842e512a0019)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们将在下个版本修复上述问题。

**Comment by hnuzhoulin** [comment]
补充一下，在IP规则中用 逗号分隔添加多个IP时，机器上面加了多遍同一个IP，界面上只显示一个IP

![image](https://github.com/1Panel-dev/1Panel/assets/6347012/8113b30e-c978-477c-a36d-4ea2f2ebfc17)
![image](https://github.com/1Panel-dev/1Panel/assets/6347012/7c96648d-b06b-4ebd-9bd2-f3600ace698c)

**Comment by wanghe-fit2cloud** [comment]
> 补充一下，在IP规则中用 逗号分隔添加多个IP时，机器上面加了多遍同一个IP，界面上只显示一个IP

收到，帮忙将问题反馈到新的 issue 吧，后面版本进行排期，感谢。

**Comment by wanghe-fit2cloud** [comment]
v1.6.1 版本已发布。
