### ISSUE TITLE
[BUG]网站日志下载的是下面编辑器里面显示的，而不是完整的

### ISSUE THREAD

**Issue by xiexiaosheng** [1Panel-dev/1Panel#2299]
### 1Panel 版本

1.6.0

### 问题描述

网站日志那块，我点下载按钮，下载的是下面编辑器里面显示的，而不是完整的

### 重现步骤

网站日志那块，点下载按钮

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本针对上述问题做出优化。

**Comment by wanghe-fit2cloud** [comment]
v1.6.1 版本已发布。
