### ISSUE TITLE
[FEATURE]建议增加容器镜像的使用标志

### ISSUE THREAD

**Issue by LicV587** [1Panel-dev/1Panel#2300]
### 1Panel 版本

v1.6.0

### 请描述您的需求或者改进建议

1. 清理镜像时，无法查看哪些镜像正在使用，使用不方便。
2. 同时删除镜像的弹出框没有具体的镜像信息，容易误删。

### 请描述你建议的实现方案

1. 建议在镜像列表添加一个标志镜像是否被使用的字段，可以查看哪些镜像正在被使用
2. 在镜像删除的弹出框中，显示镜像ID和TAG，防止误删。

### 附加信息

no more

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
