### ISSUE TITLE
[BUG]1panel-MYSQL性能调整-自动改变配置文件后-MYSQL不断重启报错

### ISSUE THREAD

**Issue by wesleyqq** [1Panel-dev/1Panel#2301]
### 1Panel 版本

1.6.0

### 问题描述

通过1panel应用市场安装MYSQL后，按照页面提供的性能调整功能，进行了性能调整优化，按照向导选择4-8G后选项保存后，容器中的MYSQL不断重启，报错如图，应该是配置文件配置有误导致；
[1panel-MYSQL性能调整-改变配置文件后-MYSQL不断重启报错.txt](https://github.com/1Panel-dev/1Panel/files/12615318/1panel-MYSQL.-.-MYSQL.txt)
![2](https://github.com/1Panel-dev/1Panel/assets/91269617/ebc51d2d-013a-496e-b716-f7c2e7a6901e)
![1](https://github.com/1Panel-dev/1Panel/assets/91269617/a307b26b-5e84-4bf4-b89a-6521219547b6)

### 重现步骤

MYSQL启动读取配置文件错误，不断重启

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.6.1 版本已发布。

**Comment by wesleyqq** [comment]
Perfect.
tks.


-不懂
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1Panel-dev/1Panel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月16日(星期六) 晚上6:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [1Panel-dev/1Panel] [BUG]1panel-MYSQL性能调整-自动改变配置文件后-MYSQL不断重启报错 (Issue #2301)





 
v1.6.1 版本已发布。
