### ISSUE TITLE
[BUG] 网站日志大于500条时，下拉不加载新日志

### ISSUE THREAD

**Issue by R0A1NG** [1Panel-dev/1Panel#2302]
### 1Panel 版本

1.6.0

### 问题描述

网站日志大于500条时，下拉不加载新日志。
开启追踪后一次500，下拉还是无效。

<img width="1136" alt="1694757257932" src="https://github.com/1Panel-dev/1Panel/assets/66672984/a1ec442e-b56f-42bc-a124-0adaa8cca28a">

### 重现步骤

日志大于500条手动下拉查看

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by zhengkunwang223** [comment]
您好 本地没有复现 浏览器页面 右键-检查 然后查看网络 TAB 页 下拉时是否有请求发出

**Comment by R0A1NG** [comment]
下拉后无网络请求，控制台也没有js报错
