### ISSUE TITLE
[FEATURE] 已安装的OpenResty修改配置时无法修改端口

### ISSUE THREAD

**Issue by R0A1NG** [1Panel-dev/1Panel#2303]
### 1Panel 版本

1.6.0

### 请描述您的需求或者改进建议

已安装的OpenResty修改配置时无法修改端口，建议在修改配置时也可修改默认端口

**Comment by R0A1NG** [comment]
<img width="981" alt="1694757460889" src="https://github.com/1Panel-dev/1Panel/assets/66672984/766cbdeb-66f9-458e-99a4-0d98c8eccf63">

**Comment by zhengkunwang223** [comment]
由于 修改现有 Openresty 端口需要改的配置文件过多
可能导致无法预知的问题 所以已安装的 openresty 不支持修改
