### ISSUE TITLE
[BUG]容器操作按钮点击后显示异常

### ISSUE THREAD

**Issue by 50007** [1Panel-dev/1Panel#2304]
### 1Panel 版本

v1.6.0

### 问题描述

![b22a3be6e79a0e6f7d45104d92b9296](https://github.com/1Panel-dev/1Panel/assets/143870542/32400531-24be-48ad-8bec-2e31087f3054)
**如图 - 点击 启动 停止 重启 强制停止 暂停 后显示删除界面** 
![d925e2584ee071e9cdc1ea67889e7d8](https://github.com/1Panel-dev/1Panel/assets/143870542/f2835bd4-24f1-40bd-8389-f53427833d0a)
**停止后显示删除成功......**

### 重现步骤

![b22a3be6e79a0e6f7d45104d92b9296](https://github.com/1Panel-dev/1Panel/assets/143870542/81419f31-addd-45a2-a5f5-2984024a3c13)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.6.1 版本已发布。
