### ISSUE TITLE
[BUG]从1.5升级到1.6版本后，在设置--安全设置里面设置域名后，无法通过设置的域名访问面板页面了

### ISSUE THREAD

**Issue by rmsto** [1Panel-dev/1Panel#2309]
### 1Panel 版本

1.6

### 问题描述

从1.5升级到1.6版本后，在设置--安全设置里面设置域名后，无法通过设置的域名访问面板页面了，1pctl reset domain 命令重置后，继续使用ip访问

### 重现步骤

1、升级到1.6版本
2、面板设置-安全-域名绑定，设置域名
3、通过域名访问面板服务，无法访问，此时也无法用IP访问，因为设置域名后强制使用域名访问；
4、使用1pctl reset domain 命令重置后使用ip访问面板服务。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
在本地环境未复现上述问题，先关闭该 Issue。

**Comment by youtao531** [comment]
v1.7.4设置域名后访问不了

**Comment by wanghe-fit2cloud** [comment]
> v1.7.4设置域名后访问不了

确认一下是否是域名解析等问题导致的（刚又在测试环境测试，未复现这个问题）。

**Comment by youtao531** [comment]
都是相同的方法配置的解析记录，其它网站都正常访问的，就是1Panel本身在安全中设置域名访问不了

**Comment by youtao531** [comment]
<img width="1114" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/8513513/1cd6e1e2-a37a-4688-ba30-3e41669667bd">

**Comment by youtao531** [comment]
<img width="1089" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/8513513/0034fff5-b51c-4314-91e7-4efe6b5d3096">

**Comment by youtao531** [comment]
<img width="1098" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/8513513/3dcea8e9-a5bc-4012-9ff7-713c99e55f40">

**Comment by youtao531** [comment]
和这个 #287 很像，通过添加反向代理 1panel域名的 网站解决了。没有在安全中设置域名。
