### ISSUE TITLE
希望适配 Almalinux 系统增加支持

### ISSUE THREAD

**Issue by baozishu** [1Panel-dev/1Panel#231]
### 1Panel 版本

1.0.1

### 请描述您的需求或者改进建议

自从Centos系统被宣布在不久之后要被停止维护了，对于企业开发者来说，不得不寻找合适的替代品，以方便在未来继续保持企业项目的稳定开发和维护！

需求即开发的导向！CloudLinux项目团队推陈出新，比如Greg Kurtzer 领衔打造的 Rocky Linux by CentOS 发行版以及CloudLinux Inc.力推的Project Lenix项目。本文主要介绍AlmaLinux，而Rocky Linux将另起一文进行叙述。
目前Lenix项目已经正式发布，为了感谢Linux社区的不懈努力，CloudLinux将Lenix的名字改成了AlmaLinux（拉丁语为“魂”之意）

（来自：CloudLinux官网）

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本支持一波。

**Comment by wanghe-fit2cloud** [comment]
可以使用以下脚本一键安装 Docker：
```shell
bash <(curl -sSL https://linuxmirrors.cn/docker.sh)
```
