### ISSUE TITLE
[BUG]Mysql 8.1.0 安装失败挂载my.cnf

### ISSUE THREAD

**Issue by EmyiaEllen** [1Panel-dev/1Panel#2312]
### 1Panel 版本

1.6.0

### 问题描述

在1Panel的应用商店选择Mysql并安装，其中 8.1.0 版本的MySQL会出现安装失败，而 5.7.43 版本Mysql会安装成功。根据错误信息查看应该是 my.cnf 被视为了文件夹而不是文件

### 重现步骤

进入1Panel，选择MySQL 8.1.0 默认配置，进行安装
![Snipaste_2023-09-15_17-31-00](https://github.com/1Panel-dev/1Panel/assets/82955455/70eba5c6-9f81-4ec8-b76c-7306e8b7fc13)
查看已安装界面
![Snipaste_2023-09-15_17-33-43](https://github.com/1Panel-dev/1Panel/assets/82955455/49c00d69-da4c-439a-a95a-522425b36db1)
查看安装失败的信息
![Snipaste_2023-09-15_17-34-28](https://github.com/1Panel-dev/1Panel/assets/82955455/ed401cce-1ac5-4397-8a31-eee20a0a7d39)

### 期待的正确结果

mysql 8.1 正确安装

### 相关日志输出

```shell
服务内部错误: stderr: Container 1Panel-mysql-vPvx Starting Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/opt/1panel/apps/mysql/mysql_8_1/conf/my.cnf" to rootfs at "/etc/my.cnf": mount /opt/1panel/apps/mysql/mysql_8_1/conf/my.cnf:/etc/my.cnf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

### 附加信息

经查看发现 Mysql 8.1.0 和 Mysql 5.7.43 都将 my.cnf 视为了文件夹，但是只有 Mysql 8.1.0 报告了错误
![mysql_status](https://github.com/1Panel-dev/1Panel/assets/82955455/9d07527e-b1f3-4ab3-83d2-2522c8ef15ae)
Mysql 8
![mysql8](https://github.com/1Panel-dev/1Panel/assets/82955455/014c1f0a-3f47-4b08-ad43-4081a0a16cb1)+
Mysql 5
![mysql5](https://github.com/1Panel-dev/1Panel/assets/82955455/48021ef5-7808-4eb1-af5a-151ca2d586f5)

**Comment by zhengkunwang223** [comment]
先同步应用商店 卸载 Mysql 之后重新安装

**Comment by EmyiaEllen** [comment]
已解决

**Comment by QuincySx** [comment]
mariadb 也有这个问题，更新应用商店无效
