### ISSUE TITLE
php5.6构建失败[BUG]

### ISSUE THREAD

**Issue by dudt** [1Panel-dev/1Panel#2318]
### 1Panel 版本

1.6

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/19968269/275ffde7-1a01-46f2-999f-4370d9f3bac6)

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/19968269/d25c8ed3-9b82-414b-a72c-db54bb000bed)

**Comment by wanghe-fit2cloud** [comment]
到应用商店页面，点击右上角同步应用按钮后，再来创建 PHP 运行环境试一下。

**Comment by dudt** [comment]
> 到应用商店页面，点击右上角同步应用按钮后，再来创建 PHP 运行环境试一下。

同步完在创建还是一样报错

**Comment by wanghe-fit2cloud** [comment]
先尝试取消扩展，再来创建 PHP 运行环境。
> 排查一下是否为某个扩展下载失败导致的。

**Comment by dudt** [comment]
> 先尝试取消扩展，再来创建 PHP 运行环境。
> 
> > 排查一下是否为某个扩展下载失败导致的。

成功了，感谢。
