### ISSUE TITLE
网站设置 -> 安全：功能需求

### ISSUE THREAD

**Issue by yikwongee** [1Panel-dev/1Panel#232]
### 1Panel 版本

1.0.1

### 请描述您的需求或者改进建议

网站设置 -> 安全 -> cc防护
不能调整封锁时间、无法查看被封锁的ip

网站设置 -> 安全
触发任意安全条件【CC 防护、IP 白名单、等等】，自定义页面

**Comment by zhengkunwang223** [comment]
我们讨论一下这个

**Comment by yikwongee** [comment]
第一个：cc防护 禁止ip访问，禁止后现在无法查看或者删除

第二个：自定义安全出发就出现一个禁止访问的页面，这个页面能不能也自定义一下

**Comment by zhengkunwang223** [comment]
已实现
