### ISSUE TITLE
[QUESTION]容器的仓库，添加了国内镜像

### ISSUE THREAD

**Issue by bfqymmt** [1Panel-dev/1Panel#2321]
### 请描述您的问题

拉取镜像失败，换国内其他源也是失败，而使用默认的源是正常的。是什么问题呢？
设置如下：
![image](https://github.com/1Panel-dev/1Panel/assets/12575427/6850c675-0db4-4e5f-aff6-2f608c8daa26)

**Comment by wanghe-fit2cloud** [comment]
要确保手动拉取镜像没有问题。

```shell
docker pull 仓库/镜像名:版本 
```
