### ISSUE TITLE
[BUG]商店相关内容不显示

### ISSUE THREAD

**Issue by xaswq** [1Panel-dev/1Panel#2325]
### 1Panel 版本

v1.6.1

### 问题描述

如图所示。desivps.com 的服务器

### 重现步骤

如图所示

### 附加信息

<img width="1677" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/85377380/5957a2f3-26ec-406f-89d2-e53879ecdef3">

**Comment by xaswq** [comment]
<img width="1678" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/85377380/b5a050e9-f5ad-415c-8c58-8a0542eb9c4f">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1Panel 系统资源统一放在阿里 OSS，是全球加速的 cdn，应该不会慢，除非 cdn 节点有问题了。
