### ISSUE TITLE
[BUG]OpenResty配置预览代码高亮异常

### ISSUE THREAD

**Issue by bh1xaq** [1Panel-dev/1Panel#2326]
### 1Panel 版本

1.6.1

### 问题描述

预览OpenResty的配置文件
下半部分配置文件高亮异常。
![image](https://github.com/1Panel-dev/1Panel/assets/16686956/7bf2bbd3-405a-4b37-b2ef-490edabf6b3b)

### 重现步骤

预览OpenResty的配置文件

### 期待的正确结果

正常颜色高亮

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。上述问题是因为配置文件中出现了多上注释 `/*` 导致的。
我们会在后续版本尝试优化上述显示问题。

**Comment by wanghe-fit2cloud** [comment]
重复 #2182
