### ISSUE TITLE
无法删除存储卷

### ISSUE THREAD

**Issue by Steven-WZH** [1Panel-dev/1Panel#2327]
### 请描述您的问题

无法删除一存储卷
![image](https://github.com/1Panel-dev/1Panel/assets/113268133/a305d993-4091-4016-a5ba-96389b98a2d8)
其他都可以正常删除
重启服务器、容器后依然删不掉，请问是否是系统生成的存储卷？

**Comment by wanghe-fit2cloud** [comment]
进入 `容器` - `存储卷` 页面，点击存储卷名称，可以查看具体是被那个容器使用。

**Comment by Steven-WZH** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/113268133/b8307f35-6776-4b15-9bb7-f54d05231b6d)
请问这个是不是被系统占用导致无法删除
