### ISSUE TITLE
关于一键安装脚本的$LOCAL_IP

### ISSUE THREAD

**Issue by miaowmint** [1Panel-dev/1Panel#233]
### 请描述您的问题

如图可见$LOCAL_IP这个变量现在就是个摆设，每次我安装完都要手动复制一遍服务器IP，
这个是暂时还没实现，以后实现的功能吗

![企业微信截图_16788761124026](https://user-images.githubusercontent.com/58991169/225295009-0d034f96-bd16-49eb-9c9d-11be8a656e25.png)

![企业微信截图_16788761484590](https://user-images.githubusercontent.com/58991169/225295016-bcee8a14-2618-4598-b20e-c3661f9d0e9f.png)

**Comment by zhengkunwang223** [comment]
收到 这个我们后续实现

**Comment by wanghe-fit2cloud** [comment]
LOCAL_IP 只是提示信息，在安装过程中我们不会动态获取服务器的外网和内网 IP。
