### ISSUE TITLE
[QUESTION] 数据库连接信息(容器连接地址)

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#2330]
### 请描述您的问题
v1.6.1

当前版本可以安装多个mysql， 然后连接信息中 容器连接地址都是mysql:3306， 如何确定使用的哪一个？
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/42db3570-fe7a-4104-b277-bf5b36e3f307)
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/88959350-d74f-430a-8465-a1018a8ae3f1)

**Comment by wanghe-fit2cloud** [comment]
麻烦再详细描述一下创建 MySQL 数据库的具体流程。
比如：是否有手动修改应用名称、容器名称、compose 文件等情况。
> 当存在多个版本 MySQL 数据库时，我们已经针对容器 service name 做了处理，理论上不会出现重复的情况。

**Comment by 9a6c** [comment]
mysql57 是之前版本创建的(1.4.x 或1.5.x)， mysql是最近安装的(1.6.1)
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/abaaa6ac-d746-407c-a2b8-a281b497604d)

安装只修改名称、容器名称、端口、外部访问这四个参数，其它都是默认的
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/97595109-a8f9-408d-9161-8a31e990d81b)


安装完成后没有改过参数，当前容器
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/cf87664f-a683-41de-9dd7-4a76e5525f22)

**Comment by wanghe-fit2cloud** [comment]
收到，我们先在本地环境复现一下上述问题。
> 你可以进微信交流群，添加我好友，方便定位问题。
