### ISSUE TITLE
[BUG]反向代理网站新增域名产生的逻辑问题

### ISSUE THREAD

**Issue by bh1xaq** [1Panel-dev/1Panel#2331]
### 1Panel 版本

1.6.1

### 问题描述

见复现步骤

### 重现步骤

# 测试用例
1、创建反向代理网站 域名为 abc.com
2、为该网站增加一个新域名为 cde.com 且端口为 8080
3、查看生成的配置文件

![image](https://github.com/1Panel-dev/1Panel/assets/16686956/f4d3ab60-3004-451a-ba2d-0eb762258127)

![image](https://github.com/1Panel-dev/1Panel/assets/16686956/2340cb7f-d605-463a-8214-dca7defbe540)

### 期待的正确结果

这和我期待的不是很意义，如果按现在的nginx配置。
则产生的配置的结果是 abc.com cde.com 均可以通过 80 8080 访问
而1Panel 配置给我的感觉是 abc.com 可通过 80 访问 cde.com 可通过 8080 访问

目测可能是一个新场景，希望PM判断一下。谢谢

**Comment by zhengkunwang223** [comment]
已复现 后续版本修复

**Comment by zhengkunwang223** [comment]
经过检验 此配置无问题 此 issue 关闭
