### ISSUE TITLE
[BUG]反代模式下HTTP方式申请Let证书失败

### ISSUE THREAD

**Issue by bh1xaq** [1Panel-dev/1Panel#2332]
### 1Panel 版本

1.6.1

### 问题描述

HTTP验证方式申请Let证书失败。

##### 测试用例
1、创建反向代理网站
2、以HTTP方式申请Let证书

##### 额外的测试
访问 Let挑战目录 没有命中1Panel 的 nginx 配置，直接命中了location /

![581091d2f065ecb135fc66adae5ab95](https://github.com/1Panel-dev/1Panel/assets/16686956/0f4a86bc-fca7-48fd-81f7-5230f69176a2)

### 期待的正确结果

最终的结果应该是能正常申请证书下来

### 附加信息

建议的配置

location ^~ /.well-known/acme-challenge {

}

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by zhengkunwang223** [comment]
已优化
