### ISSUE TITLE
[FEATURE]创建反向代理网站时，可自定义端口

### ISSUE THREAD

**Issue by bh1xaq** [1Panel-dev/1Panel#2333]
### 1Panel 版本

1.6.1

### 请描述您的需求或者改进建议

目前创建反向代理网站时无法选择端口，只能默认80，且无法删除。希望可以再创建反代网站时可以选择主端口。

### 请描述你建议的实现方案

RT:
![image](https://github.com/1Panel-dev/1Panel/assets/16686956/ad052aca-40c3-471a-9692-1903b93a64b4)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
