### ISSUE TITLE
文件 复制 粘贴 删除 优化

### ISSUE THREAD

**Issue by baozishu** [1Panel-dev/1Panel#234]
### 1Panel 版本

1.0.1

## 复制 粘贴
![VI1VCN$KCT{ V27M_SXC)P](https://user-images.githubusercontent.com/60163088/225300800-a1d3bca5-3537-4cf7-9e5e-eb619b78e4ce.png)
## 删除文件
![BSZ$UP3MXVCNC44NNYLK1ED](https://user-images.githubusercontent.com/60163088/225301142-e2987148-1dd9-47c6-98e7-cb00e9dfad15.png)

## 希望
希望`复制` `粘贴` 不这么鸡肋（挺喜欢宝塔的复制粘贴）
`删除`只能一个一个删除，增加 `全选删除`

**Comment by miaowmint** [comment]
我刚想提这个来着（

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
