### ISSUE TITLE
[QUESTION]安装ionCube扩展后，网站500

### ISSUE THREAD

**Issue by youzhazhu** [1Panel-dev/1Panel#2342]
### 请描述您的问题

很抱歉打扰您，但我实在找不到解决办法，该网站从宝塔迁移过来，在宝塔上运行是正常的。

我的网站程序需要安装ionCube扩展，使用PHP7.3.33版本。

未安装情况下提示：
`Site error: the [ionCube](http://www.ioncube.com/) PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking. Please visit [get-loader.ioncube.com](http://get-loader.ioncube.com/) for install assistance.`

安装后则变成：
`HTTP ERROR 500`

麻烦您帮忙看一下，谢谢！

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，你在创建 PHP 运行环境时，有安装 `ioncube_loader ` 扩展吗？
> 1Panel 是哪个版本？

**Comment by youzhazhu** [comment]
安装了之后就变成500了。

**Comment by youzhazhu** [comment]
1Panel是最新的1.6.1

**Comment by zhengkunwang223** [comment]
500 需要查看容器日志 或者 PHP 应用的日志

**Comment by youzhazhu** [comment]
您好，容器日志如下：
```
[20-Sep-2023 23:35:25] NOTICE: fpm is running, pid 1
[20-Sep-2023 23:35:25] NOTICE: ready to handle connections
172.18.0.1 -  20/Sep/2023:23:35:28 +0800 "GET /index.php" 500
172.18.0.1 -  20/Sep/2023:23:36:17 +0800 "GET /index.php" 500
172.18.0.1 -  21/Sep/2023:00:03:16 +0800 "GET /index.php" 500
172.18.0.1 -  21/Sep/2023:00:12:29 +0800 "GET /index.php" 500
172.18.0.1 -  21/Sep/2023:00:14:24 +0800 "GET /index.php" 500
172.18.0.1 -  21/Sep/2023:00:14:54 +0800 "GET /index.php" 500
172.18.0.1 -  21/Sep/2023:00:15:24 +0800 "GET /index.php" 500
172.18.0.1 -  21/Sep/2023:00:15:37 +0800 "GET /index.php" 500
172.18.0.1 -  21/Sep/2023:00:17:38 +0800 "GET /index.php" 500
172.18.0.1 -  21/Sep/2023:00:23:59 +0800 "GET /index.php" 500
172.18.0.1 -  21/Sep/2023:00:24:47 +0800 "GET /index.php" 500
172.18.0.1 -  21/Sep/2023:00:25:17 +0800 "GET /index.php" 500
172.18.0.1 -  21/Sep/2023:01:07:54 +0800 "GET /index.php" 500
172.18.0.1 -  21/Sep/2023:02:01:47 +0800 "GET /index.php" 500
172.18.0.1 -  21/Sep/2023:02:17:59 +0800 "GET /index.php" 500
172.18.0.1 -  21/Sep/2023:02:19:00 +0800 "GET /index.php" 500
```
好像看不出什么问题

**Comment by zhengkunwang223** [comment]
> 您好，容器日志如下：
> 
> ```
> [20-Sep-2023 23:35:25] NOTICE: fpm is running, pid 1
> [20-Sep-2023 23:35:25] NOTICE: ready to handle connections
> 172.18.0.1 -  20/Sep/2023:23:35:28 +0800 "GET /index.php" 500
> 172.18.0.1 -  20/Sep/2023:23:36:17 +0800 "GET /index.php" 500
> 172.18.0.1 -  21/Sep/2023:00:03:16 +0800 "GET /index.php" 500
> 172.18.0.1 -  21/Sep/2023:00:12:29 +0800 "GET /index.php" 500
> 172.18.0.1 -  21/Sep/2023:00:14:24 +0800 "GET /index.php" 500
> 172.18.0.1 -  21/Sep/2023:00:14:54 +0800 "GET /index.php" 500
> 172.18.0.1 -  21/Sep/2023:00:15:24 +0800 "GET /index.php" 500
> 172.18.0.1 -  21/Sep/2023:00:15:37 +0800 "GET /index.php" 500
> 172.18.0.1 -  21/Sep/2023:00:17:38 +0800 "GET /index.php" 500
> 172.18.0.1 -  21/Sep/2023:00:23:59 +0800 "GET /index.php" 500
> 172.18.0.1 -  21/Sep/2023:00:24:47 +0800 "GET /index.php" 500
> 172.18.0.1 -  21/Sep/2023:00:25:17 +0800 "GET /index.php" 500
> 172.18.0.1 -  21/Sep/2023:01:07:54 +0800 "GET /index.php" 500
> 172.18.0.1 -  21/Sep/2023:02:01:47 +0800 "GET /index.php" 500
> 172.18.0.1 -  21/Sep/2023:02:17:59 +0800 "GET /index.php" 500
> 172.18.0.1 -  21/Sep/2023:02:19:00 +0800 "GET /index.php" 500
> ```
> 
> 好像看不出什么问题

这种情况需要开启你这个 PHP 程序的 debug ，然后 看这个 PHP 程序的日志输出
