### ISSUE TITLE
[FEATURE]希望增加点击表头可以按文件的 类型、名称、文件大小、文件修改时间、文件创建时间 等进行排序。

### ISSUE THREAD

**Issue by blblank** [1Panel-dev/1Panel#2343]
### 1Panel 版本

v1.6.1

### 请描述您的需求或者改进建议

![QQ截图20230919123046](https://github.com/1Panel-dev/1Panel/assets/38033532/d5a6d0dd-8ce9-439e-b96e-81a4d2311f52)

1、希望增加点击表头可以按文件的 类型、名称、文件大小、文件修改时间、文件创建时间 等进行排序。
2、最好能加上文件或文件夹点击鼠标右键，弹出文件的操作菜单，这个功能会更方便进行操作
3、还有打包压缩文件的文件名，建议采用 当前网站域名或当前文件夹名 加上 随机字符 的格式

例如  当前网站域名为 github.com 或当前文件夹名为 github.com 打包的文件名，则默认为 github.com_随机字符.zip

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后面版本针对文件管理做出一次重构，到时会考虑上述需求。

**Comment by blblank** [comment]
对了，最好能加上文件或文件夹点击鼠标右键，弹出文件的操作菜单，这个功能会更方便进行操作

**Comment by blblank** [comment]
> 感谢反馈，我们会在后面版本针对文件管理做出一次重构，到时会考虑上述需求。

对了，最好能加上文件或文件夹点击鼠标右键，弹出文件的操作菜单，这个功能会更方便进行操作

**Comment by blblank** [comment]
> 感谢反馈，我们会在后面版本针对文件管理做出一次重构，到时会考虑上述需求。

还有打包压缩文件的文件名，建议采用 当前网站域名或当前文件夹名 加上 随机字符 的格式

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈，我们会在后面版本针对文件管理做出一次重构，到时会考虑上述需求。
> 
> 对了，最好能加上文件或文件夹点击鼠标右键，弹出文件的操作菜单，这个功能会更方便进行操作

右键操作我们在中短期内应该还支持不了，望理解。

**Comment by wanghe-fit2cloud** [comment]
文件列表排序功能，我们会在v1.8.0 版本支持，和现有 Issue 重复： #1032

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈，我们会在后面版本针对文件管理做出一次重构，到时会考虑上述需求。
> 
> 还有打包压缩文件的文件名，建议采用 当前网站域名或当前文件夹名 加上 随机字符 的格式

重新开启了一个新 Issue #2611
