### ISSUE TITLE
[FEATURE]希望可以跟随系统自动设置暗色模式

### ISSUE THREAD

**Issue by sunxiaolong321** [1Panel-dev/1Panel#2344]
### 1Panel 版本

1.6.1

### 请描述您的需求或者改进建议

希望可以跟随系统自动设置暗色模式而不是需要手动调节。

### 请描述你建议的实现方案

添加跟随系统自动调节暗色模式选项。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复 #2093
