### ISSUE TITLE
更新系统后，手动修改的nginx配置还原了[FEATURE]

### ISSUE THREAD

**Issue by itworkzhang** [1Panel-dev/1Panel#2345]
### 1Panel 版本

1.6.1

### 请描述您的需求或者改进建议

家庭网络用不了80和443，所以之前的网站配置https时，我手动改了nginx的配置，使用521端口代替443，添加了listen 521 ssl http2 ;配置，但是升级之后，配置全都改了回来，现在又得一个网站一个网站的手动重新修改。
![image](https://github.com/1Panel-dev/1Panel/assets/42572628/2c46219e-18be-4dbb-91e3-e73cc4682939)
![image](https://github.com/1Panel-dev/1Panel/assets/42572628/d509dfc3-f5d3-461b-a66c-ac4c6053251c)

**Comment by wanghe-fit2cloud** [comment]
1Panel 系统升级时，不会涉及到网站的修改。
> 麻烦再详细讲一下上面提到的升级步骤（是系统升级、应用升级还是什么具体的操作流程）

**Comment by itworkzhang** [comment]
复现不出来了，应该不是系统更新，系统我是前些天更新的，当时还能访问。应用OpenResty最近应该也没更新过。我倒是删除过一个没用的证书。 然后这个配置就没了listen 521 ssl http2 ;  
先这样吧 后面再说吧
