### ISSUE TITLE
应用商店提供的应用暂时还是太少了

### ISSUE THREAD

**Issue by miaowmint** [1Panel-dev/1Panel#235]
### 1Panel 版本

v1.0.1

### 请描述您的需求或者改进建议

应用商店提供的应用太少了，就我个人来说常用的Supervisor，nodejs管理器，PHP环境和Nginx1.21和1.22等都是没有的
![image](https://user-images.githubusercontent.com/58991169/225310008-0c875a3d-d6dc-4a4a-bd03-9c545675bb55.png)
![image](https://user-images.githubusercontent.com/58991169/225310092-04d27eec-5df5-427f-b24d-f2f54fc6f027.png)

### 请描述你建议的实现方案

希望后续可以陆续上架一些应用

**Comment by maninhill** [comment]
统一在 #250 进行管理，先关闭这个 Issue。
