### ISSUE TITLE
是否考虑新增进程守护 Supervisor[FEATURE]

### ISSUE THREAD

**Issue by FoXiMao** [1Panel-dev/1Panel#2351]
### 1Panel 版本

1.6.1

### 请描述您的需求或者改进建议

是否考虑新增进程守护 Supervisor

### 请描述你建议的实现方案

<img width="1229" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/41941990/bf469e8f-722c-4498-b4ce-c09cb012d9c8">

**Comment by wanghe-fit2cloud** [comment]
`主机` - `进程守护`
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/7c050c36-c06d-4ce5-b8a5-b07688fffcb8)
