### ISSUE TITLE
[FEATURE]网站CC拦截和php过滤的部分，希望可以再优化一下

### ISSUE THREAD

**Issue by blblank** [1Panel-dev/1Panel#2353]
### 1Panel 版本

1.6.1

### 请描述您的需求或者改进建议

我测试php的时候 把自己给拦截了，完全不知道在哪解除IP封禁 只能等自己解除,
增加封禁管理页面可以看见哪些在封禁中，可以能向宝塔那样，记录拦截的地址请求方式和攻击者的ip地址地区，
可以自己设置 拦截封禁的时间，拦截时间会随着同一个ip地址 拦截次数，增加拦截封禁的时长

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化上述功能。

**Comment by zhengkunwang223** [comment]
当前 IP 封禁列表是缓存在 Openresty 中的，可以通过重启来解禁所有 IP

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
