### ISSUE TITLE
[FEATURE]OpenResty 支持设置自定义 404 403 网站防火墙 php过滤拦截 等错误页面

### ISSUE THREAD

**Issue by blblank** [1Panel-dev/1Panel#2354]
### 1Panel 版本

1.6.1

### 请描述您的需求或者改进建议

**OpenResty 支持设置自定义 404 403 网站防火墙 php过滤拦截 等错误页面**

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
设置404等错误页面相关功能的讨论，统一汇总到该 issue #701
