### ISSUE TITLE
[FEATURE]希望更新一下memos

### ISSUE THREAD

**Issue by BJAny** [1Panel-dev/1Panel#2355]
### 1Panel 版本

1.6.1

### 请描述您的需求或者改进建议

目前memos仓库最新版本是0.15.1，应用商店还在0.14.4，落后两个版本了希望更新一下

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期推送更新。

**Comment by wanghe-fit2cloud** [comment]
最新版本已推送。
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/1855a0cd-9c96-4674-9b71-d207e5271894)
