### ISSUE TITLE
[BUG]自己拉取的docker不能创建容器

### ISSUE THREAD

**Issue by amzayo** [1Panel-dev/1Panel#2356]
### 联系方式

amzayo1026@outlook.com

### 1Panel 版本

1.6.1

### 问题描述

自己拉取的docker不能创建容器，都会报这个错误。我以为是拉取的镜像有问题。于是去拉取了一个hello world镜像，这个hello world镜像在创建容器时也会报错。但是在1panel面板的应用商店安装应用却可以正常创建容器。
报错内容:
服务内部错误: create successful but start failed, err: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "": executable file not found in $PATH: unknown
![image](https://github.com/1Panel-dev/1Panel/assets/55936606/1e74974e-ab37-470a-b04d-8a78db2d9d91)
不知道是不是系统问题，感觉大概率不是，之前用1.5版本没问题，同样的系统同样的机器
面板版本:1.6.1
系统:debian12
我使用debian11系统尝试相同操作问题依旧，下面是用debian11操作的截图，与debian12的报错一致
![image](https://github.com/1Panel-dev/1Panel/assets/55936606/2a55e0e2-1178-4c86-b9be-078df3ac351e)

### 重现步骤

拉取镜像并尝试创建容器

**Comment by ssongliu** [comment]
感谢反馈！该问题已解决，下个版本发布。
这里是因为创建容器的时候，没有给上默认的 command，可以先手动添加一下。

**Comment by jonpostel** [comment]
除去第一个问题还有一个问题，就是我在原生docker+Portainer就正常运行，但是在1Panel运行就是报错，日志，然后直接终止运行提示：
/docker-entrypoint.sh: 47: exec: : Permission denied 

![20230920152516](https://github.com/1Panel-dev/1Panel/assets/30648287/89c3bb74-4de0-4747-aed6-1bf041cebd18)

dockerfile：
FROM nginx
RUN echo 'hello word' > /usr/share/nginx/html/index.html

就这么简单额程序也报错，然后终止运行。@ssongliu @wanghe-fit2cloud

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。

**Comment by wc7086** [comment]
@wanghe-fit2cloud 问题仍然存在，当`command`以`-`开头时无法启动
```log
服务内部错误: create successful but start failed, err: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "-c": executable file not found in $PATH: unknown
```
示例
![image](https://github.com/1Panel-dev/1Panel/assets/74053663/db614806-c469-4593-a317-93e707a91015)

**Comment by wanghe-fit2cloud** [comment]
Command 要输入在容器内可手动执行的具体命令。

**Comment by wc7086** [comment]
> Command 要输入在容器内可手动执行的具体命令。

: ( 默认覆盖掉容器的`ENTRYPOINT`有点不太友好，对于文档写的不好的镜像还得去Dockerfile找`ENTRYPOINT`的命令

~~与此同时我又遇到了一个问题，启动命令是`/watchtower -c --schedule "0 0 3 * * *"`，其中的`"0 0 3 * * *"`应该怎么写？看不到yaml文件我试不出来。我不理解这个可视化界面是怎么转写这条命令的。~~

~~我建议Command直接使用用户的输入格式，而不是重新实现一个转义~~

以上是我的问题，`"0 0 3 * * *"`的双引号用单引号替代即可（如`'-c' '--schedule' '0 0 3 * * *'`）
