### ISSUE TITLE
[BUG]wiki.js安装之后一直重启

### ISSUE THREAD

**Issue by xaswq** [1Panel-dev/1Panel#2358]
### 1Panel 版本

v1.6.1

### 问题描述

应用商店的wiki.js安装之后一直重启，自己用docker compose 装的可以用

### 重现步骤

先安装mysql，然后装wiki.js，选择一键安装，一直重启，无法使用

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期修复上述问题。
> 推送应用商店更新

**Comment by xaswq** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/85377380/56eae0a4-f847-418a-9be6-e366dc9c2a1b)
可以了！
