### ISSUE TITLE
[BUG]自己拉取的docker报错和终止运行

### ISSUE THREAD

**Issue by jonpostel** [1Panel-dev/1Panel#2359]
### 联系方式

自己拉取的docker不能创建容器

### 1Panel 版本

1Panel  1.6.1

### 问题描述

一个问题，debian12 64位，就是我在原生docker+Portainer就正常运行，但是在1Panel运行就是报错，然后直接终止，日志运行提示：
/docker-entrypoint.sh: 47: exec: : Permission denied

这是dockerfile文件内容：
FROM nginx
RUN echo 'hello word' >/usr/share/nginx/html/index.html

### 重现步骤

自己在1Panel  1.6.1中编译运行日志就提示这错误，然后容器直接停止运行

### 相关日志输出

```shell
/docker-entrypoint.sh: 47: exec: : Permission denied
```

**Comment by wanghe-fit2cloud** [comment]
重复问题：https://github.com/1Panel-dev/1Panel/issues/2356
