### ISSUE TITLE
建议应用商店能够提供不使用docker安装的选项

### ISSUE THREAD

**Issue by miaowmint** [1Panel-dev/1Panel#236]
### 1Panel 版本

v1.0.1

### 请描述您的需求或者改进建议

现在应用安装都是基于docker进行的，希望可以像宝塔那样，提供一个docker或本地安装的选项；本地安装的自定义更方便点

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会讨论该需求的可行性。
