### ISSUE TITLE
[QUESTION] 如何对 `wss` 接口进行反向代理？

### ISSUE THREAD

**Issue by evanlong-me** [1Panel-dev/1Panel#2360]
### 请描述您的问题

如何对 `wss` 接口进行反向代理？

或者换句话来说，如何创建 `wss` 的反向代理？

**Comment by wanghe-fit2cloud** [comment]
1Panel 暂时还不支持添加 wss 反向代理网站。
> 可以手动修改配置文件来支持，具体操作可以查看 OpenResty 官方文档。
