### ISSUE TITLE
[FEATURE] 可以新增namesilo.com的DNS账号支持吗？

### ISSUE THREAD

**Issue by pengjianbo** [1Panel-dev/1Panel#2362]
### 1Panel 版本

1.6.1

### 请描述您的需求或者改进建议

1panel中对dns支持的平台太少了，能不能多支持一些平台。我的域名是在namesilo.com上购买的，如果需要namesilo上的api key我可以提供。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
