### ISSUE TITLE
[FEATURE] 需要 `ws` / `wss` 反向代理功能 

### ISSUE THREAD

**Issue by evanlong-me** [1Panel-dev/1Panel#2365]
### 1Panel 版本

最新版

### 请描述您的需求或者改进建议

需要 `ws` / `wss` 反向代理功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑是否支持上述需求。

**Comment by maninhill** [comment]
请问这个问题有进展吗？

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is there any progress on this issue?

**Comment by zhengkunwang223** [comment]
默认已经支持 ws / wss 反向代理功能  如果需要额外配置 可以编辑反向代理部分的源文

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
The ws/wss reverse proxy function is supported by default. If additional configuration is required, you can edit the source text of the reverse proxy part.
