### ISSUE TITLE
[BUG]SSH登录日志似乎在Debian12下不起作用

### ISSUE THREAD

**Issue by amzayo** [1Panel-dev/1Panel#2367]
### 联系方式

amzayo1026@outlook.com

### 1Panel 版本

1.6.1

### 问题描述

我在使用1Panel的时候发现在Debian12系统下，SSH日志不起作用，一直没有数据。我我以为是1Panel是读取/var/log/auth.log文件。正好我的ssh配置没有开启这个文件的记录行为。于是我打开了，但是还是没有在面板的SSH登录日志里面显示，但是在Debian11的机器上这项功能运行完好（密码，密匙登录以及不是默认端口都能被记录到）

### 重现步骤

SSH登录服务器，进入面板查看SSH登录日志并没有被记录

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本适配 Debain 12

**Comment by ssongliu** [comment]
是完全没有读到日志吗，还是说读到的日志文件不正确？
麻烦输入下面这个命令看一下：
cat /var/log/auth.log | grep -aE "(Connection closed by authenticating user|Accepted)" | grep -v 'invalid'

**Comment by amzayo** [comment]
> 是完全没有读到日志吗，还是说读到的日志文件不正确？ 麻烦输入下面这个命令看一下： cat /var/log/auth.log | grep -aE "(Connection closed by authenticating user|Accepted)" | grep -v 'invalid'

感谢！我运行这行命令返回没有这个文件或目录，于是我去找原因。
经过我的了解，debian12已经不默认安装rsyslog，导致没有auth.log文件参考文章：[Enable Rsyslog Logging on Debian 12](https://kifarunix.com/enable-rsyslog-logging-on-debian-12/)，在我手动安装rsyslog之后，1Panel面板可以显示数据，但是表头和列的数据并不能对上（个人猜测是rsyslog版本记录的数据格式不同?）。也许有修改log记录格式为方法，但是我目前还不知道

### 附加信息
我在debian12上安装rsyslog的命令
```
sudo apt install rsyslog
```
debian11的auth.log文件
[auth.log](https://github.com/1Panel-dev/1Panel/files/12679386/auth.log)

debian12的auth.log文件
[auth.log](https://github.com/1Panel-dev/1Panel/files/12679394/auth.log)
debian12的1panel面板显示的SSH登录记录显示
![image](https://github.com/1Panel-dev/1Panel/assets/55936606/e592d24f-172c-4a0b-b416-dacb532db8c5)

**Comment by ssongliu** [comment]
> > 是完全没有读到日志吗，还是说读到的日志文件不正确？ 麻烦输入下面这个命令看一下： cat /var/log/auth.log | grep -aE "(Connection closed by authenticating user|Accepted)" | grep -v 'invalid'
> 
> 感谢！我运行这行命令返回没有这个文件或目录，于是我去找原因。 经过我的了解，debian12已经不默认安装rsyslog，导致没有auth.log文件参考文章：[Enable Rsyslog Logging on Debian 12](https://kifarunix.com/enable-rsyslog-logging-on-debian-12/)，在我手动安装rsyslog之后，1Panel面板可以显示数据，但是表头和列的数据并不能对上（个人猜测是rsyslog版本记录的数据格式不同?）。也许有修改log记录格式为方法，但是我目前还不知道
> 
> ### 附加信息
> 我在debian12上安装rsyslog的命令
> 
> ```
> sudo apt install rsyslog
> ```
> 
> debian11的auth.log文件 [auth.log](https://github.com/1Panel-dev/1Panel/files/12679386/auth.log)
> 
> debian12的auth.log文件 [auth.log](https://github.com/1Panel-dev/1Panel/files/12679394/auth.log) debian12的1panel面板显示的SSH登录记录显示 ![image](https://user-images.githubusercontent.com/55936606/269465243-e592d24f-172c-4a0b-b416-dacb532db8c5.png)

对的，debian12 的日志解析规则不太一样，后续版本我们会持续完善。

**Comment by wanghe-fit2cloud** [comment]
v1.7.2 版本已发布。

**Comment by xbebhxx3** [comment]
ubuntu-22.04 此问题依旧存在
系统默认使用journalctl管理日志，能否兼容journalctl
![图片](https://github.com/1Panel-dev/1Panel/assets/102897690/02783765-d7f2-452c-9603-a73e3c0bf1ed)

**Comment by wanghe-fit2cloud** [comment]
> ubuntu-22.04 此问题依旧存在
> 系统默认使用journalctl管理日志，能否兼容journalctl

收到，我们计划在 v2.0 大版本重构时兼容 Journalctl，当前版本仍需手动安装 rsyslog。
