### ISSUE TITLE
希望可以在控制台中添加账号密码登录网站的功能

### ISSUE THREAD

**Issue by 52lemon6** [1Panel-dev/1Panel#237]
### 1Panel 版本

v1.0.1

### 请描述您的需求或者改进建议

希望可以在控制台中添加账号密码登录网站的功能（auth_basic），实现不需要改动网站代码即可实现账号密码登录功能，比如系统监控，服务展示一类，只希望自己看到，但是源码又没有提供账号密码登录查看功能的场景
↓如图
![Snipaste_2023-03-14_20-58-48](https://user-images.githubusercontent.com/40059643/225348803-84a15c5e-b53f-4d7d-bd9a-64444d65b548.png)

### 请描述你建议的实现方案
在控制台中设置网站使用账号密码访问，自动自动在目录内生成账号密码文件并在Nginx配置文件中配置ngx_http_auth_basic_module

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会支持该需求。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
