### ISSUE TITLE
[FEATURE]建议添加elasticsearch及相关工具包

### ISSUE THREAD

**Issue by skyhhjmk** [1Panel-dev/1Panel#2372]
### 1Panel 版本

v1.6.1

### 请描述您的需求或者改进建议

elasticsearch及工具包建议支持选装（即分开为多个应用，未安装elasticsearch不允许安装工具包，卸载elasticsearch的同时卸载工具包）

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述应用。

**Comment by wanghe-fit2cloud** [comment]
Elasticsearch 已上架应用商店。
