### ISSUE TITLE
[FEATURE]PHP自定义扩展支持

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#2373]
### 1Panel 版本

v1.6.1

### 请描述您的需求或者改进建议

PHP自定义扩展支持，能支持上传比如mingcc.so等等也可能是其它*.so。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by zhengkunwang223** [comment]
https://bbs.fit2cloud.com/t/topic/2073 参考这个进行设置
