### ISSUE TITLE
[BUG]关闭web日志配置不正确

### ISSUE THREAD

**Issue by Godamanga** [1Panel-dev/1Panel#2374]
### 1Panel 版本

1.6.1

### 问题描述

web站点关闭日志，在配置文件中删除了access_log的配置，这样做并不能关闭日志，将会使用了OpenResty默认日志输出文件，所以在OpenResty的日志里面就会看到站点的访问的日志，这个配置方式是不正确的，应该 把access_log 设置为off;或者access_log /dev/null

### 重现步骤

在web管理页面，关闭访问日志，在OpenResty日志中就会出现站点的访问日志

### 期待的正确结果

完全关闭日志

**Comment by zhengkunwang223** [comment]
好的 我们试一下

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
