### ISSUE TITLE
[FEATURE]修改黑夜模式设置记忆为浏览器本地cookie存储

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [1Panel-dev/1Panel#2376]
### 1Panel 版本

v1.6.1

### 请描述您的需求或者改进建议

考虑到多个人员使用面板的情况下,有些人的偏好是不同的,有些人喜欢深色,有些人不喜欢,所以该设置不应该是存储在账号系统里的.

### 请描述你建议的实现方案

直接将该模式设置存储入cookie

**Comment by zhengkunwang223** [comment]
当前 1Panel 主要针对单用户单主机
多用户的需求可能在后续版本讨论

**Comment by wanghe-fit2cloud** [comment]
暂时不考虑将主题设置存本地 Cookie，望理解。
