### ISSUE TITLE
[BUG]服务内部错误: Top-level object must be a mapping

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [1Panel-dev/1Panel#2377]
### 联系方式

x123456789fy@outlook.com

### 1Panel 版本

v1.6.1

### 问题描述

容器编排创建失败

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/67987607/0b70529e-3cec-4294-85ae-5548927f7b61)
![image](https://github.com/1Panel-dev/1Panel/assets/67987607/3c259d24-4666-46f8-b573-9a2a64a67f58)

**Comment by wanghe-fit2cloud** [comment]
应该去 `容器` - `镜像` 菜单构建镜像，而不是创建编排
