### ISSUE TITLE
希望增加绑定域名登录功能

### ISSUE THREAD

**Issue by 52lemon6** [1Panel-dev/1Panel#238]
### 1Panel 版本

v1.0.1

### 请描述您的需求或者改进建议

希望增加绑定域名登录功能，可以尽量服务器被扫描端口后直接就能找到面板登录页面

**Comment by zhengkunwang223** [comment]
好的 后续版本支持

**Comment by bulesky89857** [comment]
直接网站反代一下本地面板端口即可，反代127.0.0.01:面板端口，然后防火墙关闭面板端口，即可只能域名访问。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
