### ISSUE TITLE
[FEATURE] docker 默认网关不能是172开头，尤其是腾讯云的服务器, 当其他内外资源调用会导致网段冲突访问不进来..

### ISSUE THREAD

**Issue by gowy222** [1Panel-dev/1Panel#2382]
### 1Panel 版本

v1.6.1

### 请描述您的需求或者改进建议

echo "修改daemon.json------------------------------------"
sudo sh -c 'cat << EOF > /etc/docker/daemon.json
{
  "log-driver": "json-file",
  "log-opts": {"max-size": "100m", "max-file": "3"},
  "registry-mirrors": ["https://mirror.ccs.tencentyun.com"],
  "bip": "192.168.0.1/24" //这个，当年debug了一周，配合工单最终发现是 服务器默认内外网段和172/10 这些冲突，导致走内网IP请求后端死活请求不到...开始以为是防火墙问题，最后才发现是docker自身的网段导致冲突。所以，强烈建议初始化阶段直接把这个改了!
}
EOF'

手动重新设置了 192网段，重启服务器重启docker发现有个1panel-network 还是172.18.0.0/16 | 172.18.0.1
这个我不知道能不能强行删了???
后期怕影响自身业务!
所以: 1panel-network 这个怎么处理，怎么才能变成192网段？
另外，个人业务的定时调度器会执行 docker network prune -f
也会清除这个？ 有没有影响？？？？

**Comment by wanghe-fit2cloud** [comment]
进入 `容器` - `网络` 页面，删除默认网络后重建即可。

需要注意以下两点：
- 删除目前正在使用默认网络的容器
- 再次创建 1panel-network 容器网络时，需要指定子网和网关

> 执行 prune 命令清理时，会将未被容器使用的网络删除。
