### ISSUE TITLE
[FEATURE]OpenResty在创建新站点时默认引用server的日志格式

### ISSUE THREAD

**Issue by alienwaredream** [1Panel-dev/1Panel#2383]
### 1Panel 版本

v1.6.1

### 请描述您的需求或者改进建议

在http下的logformat 加了一个$request_time，但是具体一个站点的server配置里没有定义log格式，所以站点日志没有改变，必须手动在http站点配置下加入.....access.log main;
![85a5e8e8ac7533c1e6f2be0dee3c1e2](https://github.com/1Panel-dev/1Panel/assets/11944850/33f3f4de-e02e-4b0e-b786-177d3ce41564)
![9cce95b1dd95c0833030e1f02d11fd5](https://github.com/1Panel-dev/1Panel/assets/11944850/060e2423-8ea0-494b-8b36-9bb75b5d616d)
![ba2efed0e6aae734a41d477478853ea](https://github.com/1Panel-dev/1Panel/assets/11944850/94e1ea62-7046-43b1-a3e0-cbc8b9bd372b)

### 请描述你建议的实现方案

能不能在创建站点时就默认引用main格式呢？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述建议。
