### ISSUE TITLE
[BUG]网站界面无法显示任何已添加的网站

### ISSUE THREAD

**Issue by happytbs** [1Panel-dev/1Panel#2384]
### 联系方式

3026642514

### 1Panel 版本

v1.6.1

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/74001578/617432fb-8496-49ef-aeea-93787152eebb)
无法加载任何已经添加的网站

### 重现步骤

我向网站导入了备份，并且选择了恢复。
网页开始加载，加载完毕后我点确定，然后出现此错误

### 期待的正确结果

正常显示我添加的网站

### 相关日志输出

```shell
没有输出任何日志
```

**Comment by zhengkunwang223** [comment]
什么类型的网站？

**Comment by happytbs** [comment]
应用和运行环境的

**Comment by zhengkunwang223** [comment]
现在还有此问题吗
