### ISSUE TITLE
[BUG]安装Katex和ByteMD插件后，在编辑器里可以预览公式，但在网页中就缺失渲染，行内代码块也是如此。

### ISSUE THREAD

**Issue by chugengdu** [1Panel-dev/1Panel#2385]
### 联系方式

gengduc@qq.com

### 1Panel 版本

1Panel版本1.6.1、Halo版本2.9.1

### 问题描述

安装Katex和ByteMD插件后，在编辑器里可以预览公式，但在网页中就缺失渲染，行内代码块也是如此。
Bug网页：[http://101.42.157.148/archives/1695477664310](http://101.42.157.148/archives/1695477664310)
![image](https://github.com/1Panel-dev/1Panel/assets/71617674/a5398582-eb70-42ee-95e3-19f395f094a1)

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/71617674/957155d3-4dff-4c4a-97bb-799dac5a6350)
![image](https://github.com/1Panel-dev/1Panel/assets/71617674/6a47a2cf-19bf-4637-b5fa-e6d612ac39fb)

**Comment by wanghe-fit2cloud** [comment]
建议将问题反馈给 Halo 团队：
- [issue](https://github.com/halo-dev/halo/issues)
- [论坛](https://bbs.halo.run/)
