### ISSUE TITLE
[BUG] OpenResty 默认站点 不设置依然跳到第一个网站

### ISSUE THREAD

**Issue by SIGHTDEEP** [1Panel-dev/1Panel#2386]
### 1Panel 版本

1.6.1

### 问题描述

OpenResty 中默认站点设置成未设置，还是会跳转到第一个 网址上

### 重现步骤

域名解析到主机，但未在OpenResty 中配置，访问会跳到第一个网址

### 期待的正确结果

报错

**Comment by SIGHTDEEP** [comment]
域名是ipv6 解析

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在本地 IPv4 环境未复现上述问题，请问可以使用你的环境远程复现一下问题吗？

**Comment by wanghe-fit2cloud** [comment]
先关闭该 Issue 了，如后续还有问题再继续讨论。
