### ISSUE TITLE
[BUG]南墙一直安装，但是一直安装不上

### ISSUE THREAD

**Issue by xaswq** [1Panel-dev/1Panel#2387]
### 1Panel 版本

v1.6.1

### 问题描述

一直转圈，就是安装不上

### 重现步骤

卸载 OpenResty 后安装南墙

### 期待的正确结果

安装完成，可以进入 4443 进行访问

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/85377380/709ac919-3c2b-4ee6-8dd3-400104143540)

**Comment by xaswq** [comment]
并且无法暂停安装，我现在想恢复原有的 OpenResty  也很难了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述问题大概率是在 pull 应用镜像，你可以到 `容器` - `配置` 页面设置好镜像加速，如下图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/505721c5-efae-42ba-928f-eccc5e2f7045)
