### ISSUE TITLE
[BUG]创建编排，来源 选择路径选定yml，创建编排容器后再删除编排会删除整个文件夹

### ISSUE THREAD

**Issue by VMCoud** [1Panel-dev/1Panel#2391]
### 1Panel 版本

1.6.1

### 问题描述

{Debian12}
创建编排，来源 选择路径选定yml，创建编排容器后再删除编排会删除整个文件夹   把我整个root目录都删了

怎么恢复root目录

### 重现步骤

创建编排，来源 选择路径选定yml，创建编排容器后再删除编排会删除整个文件夹

### 期待的正确结果

应该只删除编排，提示是否删除删除yml源文件

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/59264435/460d7b56-7a37-4b8a-8488-4b21c605ba40)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
用户在删除编排时，我们会提醒用户谨慎操作，如下图：
<img width="458" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/829818ac-bd01-450d-a4e0-3d57694f4cf7">

> 我们会在下个版本优化 `路径选择` 类型编排的删除逻辑。

**Comment by carolcoral** [comment]
@wanghe-fit2cloud  仅仅只是提醒其实用处不大的，用户可能根本不想删除compose配置文件，仅仅可能只是因为容器问题期望重新构建而已。
## 建议
1. 新增“清除”功能。提供删除容器、清空配置功能，但会保留文件夹和compose.yaml文件
2. 原有的删除功能提供警告。执行整个文件夹的删除操作。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
