### ISSUE TITLE
[FEATURE] 容器交互方式

### ISSUE THREAD

**Issue by yuanchaolie** [1Panel-dev/1Panel#2393]
### 1Panel 版本

1.6.0

### 请描述您的需求或者改进建议

像Portainer-CE一样可以设置容器的启动类型
交互终端
1.可以通过在终端页面添加其他连接方式
2.在容器创建时添加容器的是否可交互

另外如果能给停止容器加个发送指定命令到容器的交互终端就更好了
比如某些应用程序运行时需要在终端发送exit才能保存退出

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，能更详细的描述一下上述需求吗？
> 最好是能提供截图说明

**Comment by yuanchaolie** [comment]
> 感谢反馈，能更详细的描述一下上述需求吗？
> 
> > 最好是能提供截图说明

关于交互终端就是Portainer的进入容器内功能
![QQ截图20230926161634](https://github.com/1Panel-dev/1Panel/assets/25658015/362176d5-95d2-4602-af76-0813784aad68)
关于创建容器时的终端类型
![QQ截图20230926161913](https://github.com/1Panel-dev/1Panel/assets/25658015/10531407-5cc1-4e6e-bb24-fce844a2e6e7)
容器功能面板提供挺好的,就差这个交互功能,不然还得装Portainer,麻烦还多余

最后关于停止容器发送自定义指令给容器终端,看能不能在交互终端的基础上实现,我这边比较常用
使用场景:新建容器后,运行sh文件,想停止容器时点击停止容器

ps: 正常情况下需要发送"exit"指令结束本次运行,并且会保存一些文件,但是直接停止容器会直接进程结束,
ps: 这个指令不一定就是exit,毕竟程序不是我做的,所以才需要自定义,希望有望实现
ps: 这个扩展功能可以参考[mcsmanager](https://mcsmanager.com/)的关闭实例,关闭实例发送指定指令
![image](https://github.com/1Panel-dev/1Panel/assets/25658015/bf0c5d62-b200-410a-b93e-6a2b770c4709)

**Comment by wanghe-fit2cloud** [comment]
收到，我们先调研一下上述需求，后续版本考虑支持。

**Comment by wanghe-fit2cloud** [comment]
最新版本已支持设置交互方式，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/9da96dc3-bbf0-49e5-bfe7-b1e8adf1a19a)
