### ISSUE TITLE
通过域名登录后台 日志问题

### ISSUE THREAD

**Issue by SIGHTDEEP** [1Panel-dev/1Panel#2395]
### 1Panel 版本

1.6.1

### 请描述您的需求或者改进建议

通过openresty反向代理登录后台，不知道是没把clent_ip 传过去还是 日志取值有问题，都只显示 127.0.0.1
<img width="812" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/20434364/fbf022c7-9277-4686-bc9c-3d4ca0485cf3">

### 请描述你建议的实现方案

显示客户端真是ip

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。
> 反代地址是填的 ipv4 内网地址还是 127.0.0.1？

**Comment by ssongliu** [comment]
麻烦提供一下反向代理的配置文件，开发环境未能复现该问题，暂时先关闭了，后续还有问题可以重新打开。
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/07ddd676-2729-4bc0-a1bf-e499aca8bbf5)
