### ISSUE TITLE
[BUG] Oracle主机通过一键脚本安装绑定tcp6端口后无法通过ip:port访问

### ISSUE THREAD

**Issue by shangdev** [1Panel-dev/1Panel#2396]
### 1Panel 版本

1.6.1

### 问题描述

Oracle主机通过一键脚本安装后自动绑定了tcp6，但是通过ip:prot访问时无法访问

![d9e0624387ce78842d4cf3a6738f3d4](https://github.com/1Panel-dev/1Panel/assets/15621520/5fa7419b-43c4-4253-a95e-d04433097e2b)

查看系统的netipv6.bindv6only值为0

![8fd7a95f5639de2bce4f5b0b2ceabd3](https://github.com/1Panel-dev/1Panel/assets/15621520/acdbb98b-f032-43fa-92d8-a1e787e960cf)

### 重现步骤

系统：Oracle主机Ubuntu系统（arm架构）

安装步骤：

![image](https://github.com/1Panel-dev/1Panel/assets/15621520/4e697326-bfb0-4a7a-a0f9-7800cc0b2af9)

### 期待的正确结果

可通过ip:port访问

**Comment by wanghe-fit2cloud** [comment]
Oracle 系统的内核是定制过的，原版内核设置 net.ipv6.bindv6only = 0 是支持的
> 可以先自行查询一下官网有没有相关说明。

**Comment by shangdev** [comment]
@wanghe-fit2cloud 不能自定义绑定0.0.0.0:port吗？

**Comment by wanghe-fit2cloud** [comment]
> @wanghe-fit2cloud 不能自定义绑定0.0.0.0:port吗？

v1.8.0 版本支持在面板设置中切换监听IP。
重复 #1024
