### ISSUE TITLE
缓存-无法刷新验证码[BUG]

### ISSUE THREAD

**Issue by fjk0618** [1Panel-dev/1Panel#2397]
### 联系方式

fjk0618@gmail.com

### 1Panel 版本

v1.6.1

### 问题描述

设备：macbook pro m1 pro
浏览器：版本 115.0.5790.170（正式版本） (arm64)
复现过程：

1. 输入错了一次密码后，触发了验证码登录，此时，通过浏览器普通刷新或者强制刷新，都无法刷新出新的验证码，chrome请求看起来发出去了，响应也回来了，但是response的内容，captchaID和imagePath都一模一样。浏览器缓存已关闭。
![image1](https://github.com/1Panel-dev/1Panel/assets/35111141/db0cd14c-df8e-44df-a652-ae983e0113bf)
 
![image2](https://github.com/1Panel-dev/1Panel/assets/35111141/4669fea0-85de-4bba-b6ac-4d36ed90a149)
2. 在同样的环境下，有时候就会出现登录后自动闪退又回到登录页
3. 

https://github.com/1Panel-dev/1Panel/assets/35111141/2079be3b-6ea1-42f4-84ca-a1b9163a4066

![image5](https://github.com/1Panel-dev/1Panel/assets/35111141/ad135fee-65c6-4e86-a10c-75899e349cd5)
![image3](https://github.com/1Panel-dev/1Panel/assets/35111141/1de7ee11-f45e-4742-968e-7d3819b687e2)
![image4](https://github.com/1Panel-dev/1Panel/assets/35111141/4f4add8f-2bdb-466c-84da-e1f2878c31b2)

# 服务器机器详情：甲骨文amd-x86机器
### 重现步骤

设备：macbook pro m1 pro
浏览器：版本 115.0.5790.170（正式版本） (arm64)
复现过程：

1. 输入错了一次密码后，触发了验证码登录，此时，通过浏览器普通刷新或者强制刷新，都无法刷新出新的验证码，chrome请求看起来发出去了，响应也回来了，但是response的内容，captchaID和imagePath都一模一样。浏览器缓存已关闭。
![image1](https://github.com/1Panel-dev/1Panel/assets/35111141/db0cd14c-df8e-44df-a652-ae983e0113bf)
 
![image2](https://github.com/1Panel-dev/1Panel/assets/35111141/4669fea0-85de-4bba-b6ac-4d36ed90a149)
2. 在同样的环境下，有时候就会出现登录后自动闪退又回到登录页
3. 

https://github.com/1Panel-dev/1Panel/assets/35111141/2079be3b-6ea1-42f4-84ca-a1b9163a4066

![image5](https://github.com/1Panel-dev/1Panel/assets/35111141/ad135fee-65c6-4e86-a10c-75899e349cd5)
![image3](https://github.com/1Panel-dev/1Panel/assets/35111141/1de7ee11-f45e-4742-968e-7d3819b687e2)
![Uploading image4.jpg…]()

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
麻烦将 1Panel 更新到最新版本，观察是否还存在上述问题。
> 我们在本地环境始终未能复现上述问题。

如果问题依然存在，我们再继续讨论、交流。
