### ISSUE TITLE
[FEATURE]docker compose优化和nas防火墙兼容

### ISSUE THREAD

**Issue by carolcoral** [1Panel-dev/1Panel#2399]
### 1Panel 版本

v1.6.2

### 请描述您的需求或者改进建议

1. docker compose部署，删除容器会把compose一起删除
2. docker 容器重启（非重新build）会覆盖volume本地修改的文件内容
3. docker容器中点击日志中的“下载”仅能下载当前展示内容，不能下载整个日志文件（既然只能下载当前展示内容我何必下载呢～～）
4. 目前`主机`-`防火墙`中无法查看群晖nas的防火墙。群晖nas已经存在防火墙。
5. 网站环境中无法部署java环境的web服务

### 请描述你建议的实现方案

1. docker compose部署正常删除docker容器后应该保留compose设置（不仅仅只是文件保留，应该是在“编排”中保留）
2. docker compose中应该增加“重新build”功能
3. 提供`主机`-`防火墙`兼容群晖NAS的主机防火墙功能
4. 提供java环境的网站部署场景

**Comment by wanghe-fit2cloud** [comment]
感谢你的反馈，我们会在后续版本针对上述问题持续优化。

**Comment by wanghe-fit2cloud** [comment]
> docker 容器重启（非重新build）会覆盖volume本地修改的文件内容

Docker 容器重启后，不会覆盖挂载在 volume 上的本地文件内容。原因是 Docker 的 volume 是持久化存储的一种机制，专门设计用来保存数据，即使容器重启、停止或删除，volume 中的数据仍然会保留。

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
