### ISSUE TITLE
希望面板可以设置主机ssh端口，和密钥登录ssh设置

### ISSUE THREAD

**Issue by 52lemon6** [1Panel-dev/1Panel#240]
### 1Panel 版本

v1.0.1

### 请描述您的需求或者改进建议

希望面板可以设置主机ssh端口，和密钥登录ssh设置，正好面板上就能解决ssh的后续配置

**Comment by miaowmint** [comment]
已经有二步验证了，issue可以关了（

![image](https://user-images.githubusercontent.com/58991169/225358864-3bd043d3-6e71-4299-b23c-4fa42bf5ca24.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。后续版本会支持 SSH 管理相关功能。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
