### ISSUE TITLE
两步验证使用Microsoft Authenticator时会覆盖[BUG]

### ISSUE THREAD

**Issue by luoye9711** [1Panel-dev/1Panel#2404]
### 联系方式

971100009@qq.com

### 1Panel 版本

v1.6.2

### 问题描述

使用Microsoft Authenticator添加多台服务器，会出现覆盖的情况，主机名都是admin，只能添加一台，添加多台只能覆盖

### 重现步骤

使用Microsoft Authenticator添加多台服务器，会出现覆盖的情况，主机名都是admin，只能添加一台，添加多台只能覆盖

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
