### ISSUE TITLE
[FEATURE]改进面板登录页面

### ISSUE THREAD

**Issue by chumoe** [1Panel-dev/1Panel#2406]
### 1Panel 版本

v1.6.2

### 请描述您的需求或者改进建议

在手机上使用Alook浏览器登录面板时自动填充的账号和密码无法直接登录，会提示请输入账号和密码，需要点击输入框进行输入操作才能进行登录。入下图：
![Screenshot_20230928_032902](https://github.com/1Panel-dev/1Panel/assets/50536453/d08e6523-23c0-4d66-bffb-628efeab9e6b)

### 请描述你建议的实现方案

点击登录按钮时直接判断账号和密码输入框是否有值，而不是对输入框进行输入操作才行。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by Felmon** [comment]
safari也是同样问题

**Comment by chumoe** [comment]
逛了下知乎，看到也有人用这Alook浏览器在其它网站遇到了此问题，看来是浏览器的问题：
--------------------------------------------------------------------------------------------------
![QQ截图20230929100912](https://github.com/1Panel-dev/1Panel/assets/50536453/8331a7d3-2a5b-4ecd-ac85-46b841136065)

**Comment by yutangbb** [comment]
除了以上问题，对于密码填充还存在问题
环境：OS：Windows 11，浏览器：Edge， 密码管理器：KeePassXC

使用密码管理器填充用户名和密码登录后，我的密码管理器会提示我更新密码，说明密码管理器插件检测到了密码发生了改变，由于实际上没有修改密码，不应该更新，否则可能导致原密码丢失
![image](https://github.com/1Panel-dev/1Panel/assets/21243409/3d19bd24-4940-486a-bc3d-87a788256323)
