### ISSUE TITLE
[FEATURE] 希望支持静态转PHP

### ISSUE THREAD

**Issue by bddjr** [1Panel-dev/1Panel#2408]
### 1Panel 版本

v1.6.2

### 请描述您的需求或者改进建议

我创建了静态网页后，发现它不能像宝塔那样直接转PHP。

### 请描述你建议的实现方案

建议网站的“基本配置”里支持将静态转PHP。

**Comment by bddjr** [comment]
对于使用者来说，暂时的解决办法：

使用php运行环境创建一个名为 php.test （反正这个域名不会被使用就行）的网站，并且删除里面的 index.php

然后将下列代码块粘贴到那个想要转php的静态网站的配置文件结尾

```
    location ~ [^/]\.php(/|$) {
        fastcgi_pass 127.0.0.1:9000; 
        include fastcgi-php.conf; 
        include fastcgi_params; 
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; 
    }
```

这样就能跑起来了，但1panel仍然将其识别为静态网站。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
网站类型转换相关功能的讨论，统一汇总到该 issue #2532
