### ISSUE TITLE
[FEATURE]防火墙的端口放行可以新增一个功能，用于区分 ipv6 和 ipv4

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#2409]
### 1Panel 版本

v1.6.2

### 请描述您的需求或者改进建议

关于防火墙的端口放行，可以针对 ipv6 和 ipv4 进行单独放行吗？

### 请描述你建议的实现方案

功能需求如下：
1 、端口放行，可以选择 ipv4 、 ipv6 、全部（新增和编辑）
2 、列表可以读取仅放行的 ipv6 端口（当前无法读取到ipv6 放行的端口）

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。

**Comment by imythu** [comment]
> [v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。

你好啊，v1.10.29-lts没有看到针对ipv6、ipv4是否放行的设置，是还没发布吗

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> [v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) version has been released.

Hello, v1.10.29-lts does not see the settings for whether to release ipv6 and ipv4. Is it not released yet?
