### ISSUE TITLE
[FEATURE]希望面板可以使用ssl访问

### ISSUE THREAD

**Issue by 52lemon6** [1Panel-dev/1Panel#241]
### 1Panel 版本

v1.0.1

### 请描述您的需求或者改进建议

希望面板可以使用ssl访问，毕竟用户登录面板时局域网的环境并不一定是在家里，可能在网吧，大型社区等环境，有会抓包等其他风险存在

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
当前版本，你可以在 1Panel 面板中创建反向代理网站，将 1Panel 自身服务发布出去，然后再为其绑定证书。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。

**Comment by hnuzhoulin** [comment]
有木有教程？

**Comment by wanghe-fit2cloud** [comment]
> 有木有教程？

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/d1251652-81eb-477d-a757-c12ef1890513)

**Comment by hnuzhoulin** [comment]
> > 有木有教程？
> 
> ![image](https://user-images.githubusercontent.com/46734380/256167609-d1251652-81eb-477d-a757-c12ef1890513.png)

非常感谢，我昨天尝试复用443端口，通过网站安装的openresty来反代，也实现了效果，就是entrance还是需要 隔一段时间加上。
