### ISSUE TITLE
[FEATURE]建议同时支持Nginx、Apache

### ISSUE THREAD

**Issue by xushulang** [1Panel-dev/1Panel#2416]
### 1Panel 版本

1.6.2

### 请描述您的需求或者改进建议

建议同时支持Nginx、Apache

应提供Nginx的多个版本，而不是OpenResty

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈
我们在中短期内应该不会考虑支持 Apache，望理解！
> OpenResty = Nginx + Lua

**Comment by xushulang** [comment]
> 感谢您的反馈 我们在中短期内应该不会考虑支持 Apache，望理解！
> 
> > OpenResty = Nginx + Lua

OpenResty 这个我知道是什么，但我更倾向于只使用Nginx，比如宝塔就同时支持，给使用者选择，而不是我们去选择使用者

**Comment by xushulang** [comment]
> 感谢您的反馈 我们在中短期内应该不会考虑支持 Apache，望理解！
> 
> > OpenResty = Nginx + Lua

为的是1panel更好的走向世界，向隔壁的宝塔学习，应该是取其精华，去其糟粕

**Comment by xushulang** [comment]
> 感谢您的反馈 我们在中短期内应该不会考虑支持 Apache，望理解！
> 
> > OpenResty = Nginx + Lua

![image](https://github.com/1Panel-dev/1Panel/assets/52433214/56612b61-68fc-4ef4-b9c6-5b62ff4079cf)
![image](https://github.com/1Panel-dev/1Panel/assets/52433214/d2baf35e-df95-4c11-a0c6-c3ca68236650)
