### ISSUE TITLE
[QUESTION]请问1Panel可以应用在现有服务器上面么？

### ISSUE THREAD

**Issue by alexwenbj** [1Panel-dev/1Panel#2417]
### 请描述您的问题

我的Linux服务器上已经安装并运行Apache/PHP/MySQL等等应用，我如果安装1Panel，1Panel可以认出这些应用/服务么？会不会有什么其他后果？（比如会引起冲突而导致现有服务不可运行等情况）。有什么特别需要注意的地方么？谢谢！

**Comment by wanghe-fit2cloud** [comment]
> 1Panel可以认出这些应用/服务么？

1Panel 是采用容器化安装，要确保应用端口可用、别冲突。
> 全新安装 1Panel 后，不能识别出已运行应用。

**Comment by alexwenbj** [comment]
也就是说要先安装1Panel，再安装其他服务/应用是吧？

**Comment by wanghe-fit2cloud** [comment]
> 也就是说要先安装1Panel，再安装其他服务/应用是吧？

是的，需要在应用商店中安装应用。
