### ISSUE TITLE
支持Nginx和Apache

### ISSUE THREAD

**Issue by xushulang** [1Panel-dev/1Panel#2418]
![image](https://github.com/1Panel-dev/1Panel/assets/52433214/56612b61-68fc-4ef4-b9c6-5b62ff4079cf)
![image](https://github.com/1Panel-dev/1Panel/assets/52433214/d2baf35e-df95-4c11-a0c6-c3ca68236650)

_Originally posted by @xushulang in https://github.com/1Panel-dev/1Panel/issues/2416#issuecomment-1742070692_

**Comment by xushulang** [comment]
取其精华，去其糟粕

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈
我们在中短期内应该不会考虑支持 Apache，望理解！
> OpenResty = Nginx + Lua
