### ISSUE TITLE
[FEATURE]应增加Nginx的多个版本，而不是OpenResty

### ISSUE THREAD

**Issue by xushulang** [1Panel-dev/1Panel#2419]
### 1Panel 版本

1.6.2

### 请描述您的需求或者改进建议

应增加Nginx的多个版本，而不是OpenResty

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑是否支持上述应用。

**Comment by zhengkunwang223** [comment]
请问需要 Nginx 的什么版本？

**Comment by xushulang** [comment]
> 请问需要 Nginx 的什么版本？
![image](https://github.com/1Panel-dev/1Panel/assets/52433214/d1632009-c7c6-4ba8-8d68-5d2a839d0fb0)

**Comment by zhengkunwang223** [comment]
> > 请问需要 Nginx 的什么版本？
> > ![image](https://user-images.githubusercontent.com/52433214/273354403-d1632009-c7c6-4ba8-8d68-5d2a839d0fb0.png)

版本太多了 不好维护 暂时只支持 Openresty
