### ISSUE TITLE
容器管理界面希望能够提供更详细的信息

### ISSUE THREAD

**Issue by miaowmint** [1Panel-dev/1Panel#242]
### 1Panel 版本

v1.0.1

### 请描述您的需求或者改进建议

容器管理界面直接提供的信息太少了

![image](https://user-images.githubusercontent.com/58991169/225360287-61d339f9-2730-4c9b-9234-38213f61279f.png)

### 请描述你建议的实现方案

希望能像这样的，直接多提供一些信息，一眼就能看到，省得进监控里去翻（图里写错了，我本来想写内存使用量的）

![image](https://user-images.githubusercontent.com/58991169/225361196-fb6998f1-97c3-44c6-b18b-555286016a1b.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
