### ISSUE TITLE
[FEATURE]增加docker容器的ssh登录日志

### ISSUE THREAD

**Issue by yukaichao** [1Panel-dev/1Panel#2420]
### 1Panel 版本

v1.6.2

### 请描述您的需求或者改进建议

你好，我在docker上搭建了一个gitlab的服务器，需要向外暴露了ssh端口，我想把dockerd容器的ssh登录日志也添加到宿主机的面板里。（目前是在容器里也安装面板实现）

### 请描述你建议的实现方案

1.可以gitlab里增加一个监控程序，把ssh日志发送到面板。
2.把容器的日志文件挂载到宿主机的一个目录，面板程序设置文件路径解析。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述需求。

**Comment by maninhill** [comment]
请问这个问题有进展吗？

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is there any progress on this issue?

**Comment by wanghe-fit2cloud** [comment]
建议手动将 SSH 文件挂载到宿主机。至于 1Panel 页面解析登录日志文件的功能，中短期内暂无相关支持计划，望理解。
