### ISSUE TITLE
[BUG]添加IP规则无效

### ISSUE THREAD

**Issue by maoball** [1Panel-dev/1Panel#2421]
### 1Panel 版本

v1.6.2

### 问题描述

在主机-防火墙-IP规则中，添加多个IP无效，需要多次添加
输入例: a.b.c.d,e.f.g.h
在列表中只有a.b.c.d，只能重新再次添加e.f.g.h
望管理员修复，谢谢
（我也不知道是不是我的问题但是确实挺麻烦）

### 重现步骤

在主机-防火墙-IP规则中，添加多个IP，例如添加a.b.c.d和e.f.g.h

### 期待的正确结果

在列表中看到a.b.c.d，e.f.g.h

### 相关日志输出

```shell
主机	
添加 ip 规则 [accept] [a.b.0.0/24]	
成功	
2023-10-02 12:59:57
主机	
添加 ip 规则 [accept] [a.b.0.0/24,aa.bb.cc.dd]	
成功	
2023-10-02 12:59:47
主机	
添加 ip 规则 [accept] [a.b.0.0/24,aa.bb.cc.dd,a.bbb.0.0/24]	
成功	
2023-10-02 12:59:40
主机	
添加 ip 规则 [accept] [a.b.0.0/24,127.0.0.1,aa.bb.cc.dd,a.bbb.0.0/24,c.d.0.0/24]	
成功	
2023-10-02 12:59:05

[p.s.如果字母表示一致，例a.bbb.0.0/24反复出现，意为手动添加多次]
```

**Comment by Kenny0521** [comment]
还有一个就是球球了添加（纯）nginx和apache吧（像baota一样的那种谢谢开发者们orz）

**Comment by wanghe-fit2cloud** [comment]
> 在主机-防火墙-IP规则中，添加多个IP无效，需要多次添加

感谢反馈，我们先在本地开发测试环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
> 添加（纯）nginx和apache吧

可以在应用商店安装 OpenResty。
> OpenResty = Nginx + Lua

**Comment by Kenny0521** [comment]
> 可以在应用商店安装 OpenResty。
> OpenResty = Nginx + Lua
【纯nginx（只有nginx）】和apache

**Comment by Kenny0521** [comment]
> 感谢反馈，我们先在本地开发测试环境复现一下上述问题。

还有就是你们提供的样例```多个 IP 或 IP 段 请用 "," 隔开：172.16.10.11,172.16.0.0/24```我粘贴在输入框里都只添加了一个IP，172.16.0.0/24，日志审计里则显示```添加 ip 规则 [accept] [172.16.10.11,172.16.0.0/24] 成功```

**Comment by Kenny0521** [comment]
谢谢开发者们（修完了关）

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
