### ISSUE TITLE
一键安装留下的文件可以删掉或隐藏吗？ [QUESTION]

### ISSUE THREAD

**Issue by eureka6** [1Panel-dev/1Panel#2422]
### 一键安装留下的文件可以删掉或隐藏吗？

在`/root`目录执行了一键安装命令，安装好后这三个文件就出现在目录里了，

`1panel-v1.6.2-linux-amd64`
`1panel-v1.6.2-linux-amd64.tar.gz`
`quick_start.sh`

请问可以删掉或隐藏吗？

**Comment by eureka6** [comment]
安装目录是默认的`/opt`

**Comment by wanghe-fit2cloud** [comment]
> 请问可以删掉或隐藏吗？

可以删除安装文件。
