### ISSUE TITLE
[FEATURE] 轻量级 模块化 安装？容器时代，很多东西压根用不到...

### ISSUE THREAD

**Issue by gowy222** [1Panel-dev/1Panel#2423]
### 1Panel 版本

v1.6.2

### 请描述您的需求或者改进建议

简单来说，一个文件管理+docker+安全管控+cornjob 够了。
网站用不到。。。php环境都用不到。。。数据库更用不到。。。应用商店也用不到。。。
要部署什么全程自己dockefile一个镜像的事情，没必要开局安装所有基础环境。装那么多吃内存啊(Debian 12.0 - 1panel 纯净开机450+MB内存??!!!)。彻底模块化选项mini安装考虑一下？

2. pipeline流水线部署服务器组 安装的时候 支持一下 指定 安装的端口 账密 安全入口？能自动化就别折腾人工了....10个服务器要手动cli操作10次修改基础信息累啊....

**Comment by wanghe-fit2cloud** [comment]
v2 版本重构可能会考虑
