### ISSUE TITLE
[BUG]配置自签证书后，网站无法正常访问

### ISSUE THREAD

**Issue by wwtao1024** [1Panel-dev/1Panel#2424]
### 1Panel 版本

1.6.2

### 问题描述

网站配置ssl为openssl自签证书后无法正常访问，在宝塔中测试正常访问

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/62713172/57ccd8a8-537f-4c67-b016-3e937c3a172e)
![image](https://github.com/1Panel-dev/1Panel/assets/62713172/56f0ff38-d176-4e4a-9af4-5e739bc0b223)

### 相关日志输出

```shell
看网站日志。没有输入任何日志信息
```

**Comment by wanghe-fit2cloud** [comment]
未开启 HTTPS 时，服务可以正常访问的话，可以尝试添加 HTTP 证书试一下。
<img width="1436" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/5cf31a15-7d99-4b44-91f5-7d3c1448104e">

**Comment by wwtao1024** [comment]
这是要在线申请的吧 我的证书是自己使用openssl生成的

**Comment by wanghe-fit2cloud** [comment]
是的。

**Comment by zhengkunwang223** [comment]
HTTP 可以访问吗？

**Comment by wwtao1024** [comment]
普通的http可以访问 配置上openssl 自签的 证书就不可以，奇怪的是1panel配置上自签的ssl就可以 网站不行

**Comment by wwtao1024** [comment]
处理了吗

**Comment by zhengkunwang223** [comment]
> 处理了吗

暂时没有复现
