### ISSUE TITLE
[FEATURE]能加一个Node.js版本控制吗。

### ISSUE THREAD

**Issue by mengzai-c** [1Panel-dev/1Panel#2425]
### 1Panel 版本

v1.6.2

### 请描述您的需求或者改进建议

node换起来比较麻烦，加一个版本切换会方便很多

### 请描述你建议的实现方案

用nvm,主要是用图形界面比较方便
![image](https://github.com/1Panel-dev/1Panel/assets/140877268/700601aa-832a-461b-ad0c-2505403e3454)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑是否支持上述需求。
