### ISSUE TITLE
[BUG]docker容器日志无内容

### ISSUE THREAD

**Issue by mrchenxxx** [1Panel-dev/1Panel#2426]
### 联系方式

834482351@qq.com

### 1Panel 版本

v1.6.2

### 问题描述

刚开始安装后还是有日志的，但是不知道操作了哪里了。日志就看不到了

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/44868578/5ad63871-d492-4561-b9aa-4a94cf685f1e)
全部doushi都是类似于这种暂无数据的

**Comment by wanghe-fit2cloud** [comment]
进入 `主机` - `终端` 页面，使用 `docker logs` 命令查看是否有结果输出。

**Comment by mrchenxxx** [comment]
> 进入 `主机` - `终端` 页面，使用 `docker logs` 命令查看是否有结果输出。

有的，我好多容器呢 ，不可能都没有的

**Comment by wanghe-fit2cloud** [comment]
本地没能复现这个问题。
方便的话进微信交流群添加一下我好友，远程看看这个问题。

**Comment by mrchenxxx** [comment]
> 本地没能复现这个问题。 方便的话进微信交流群添加一下我好友，远程看看这个问题。

没有找到交流群的入口

**Comment by ssongliu** [comment]
> > 本地没能复现这个问题。 方便的话进微信交流群添加一下我好友，远程看看这个问题。
> 
> 没有找到交流群的入口

![image](https://github.com/1Panel-dev/1Panel/assets/73214554/b10c3982-3325-426f-a509-294af6facbd1)

**Comment by ssongliu** [comment]
反代配置中未添加以下 websocket 规则

location / {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}

**Comment by mrchenxxx** [comment]
> 反代配置中未添加以下 websocket 规则
> 
> location / { proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; }

解决了，需要开通websocket
