### ISSUE TITLE
[FEATURE] 增加伪静态模版

### ISSUE THREAD

**Issue by cktk** [1Panel-dev/1Panel#2427]
### 1Panel 版本

1.6.2

### 请描述您的需求或者改进建议

在网站中的伪静态模版中能否增加 vue项目路由模式为 history 的伪静态模版

### 请描述你建议的实现方案

location / {
  root    html;
  index   index.html index.htm;
  try_files $uri $uri/ /index.html
}

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复 #705
