### ISSUE TITLE
[BUG] mysql 数据库备份 如果其中一个数据库我从其他地方删除了 备份的时候会提示找不到该数据库(schema) 就会导致失败

### ISSUE THREAD

**Issue by cktk** [1Panel-dev/1Panel#2428]
### 1Panel 版本

1.6.2

### 问题描述

数据库备份  如果其中一个数据库我从其他地方删除了  备份的时候会提示找不到该数据库(schema)  就会导致失败

### 重现步骤

点击获取远端数据库  然后 从navicat中执行命令  
drop schema xxxx;

定时任务 或者备份中备份的时候整体备份都会失败

**Comment by wanghe-fit2cloud** [comment]
1Panel 不会主动同步远端数据库，需要手动执行同步操作。
