### ISSUE TITLE
新建网站似乎不支持自定义的动态网站

### ISSUE THREAD

**Issue by miaowmint** [1Panel-dev/1Panel#243]
### 1Panel 版本

v1.0.1

### 请描述您的需求或者改进建议

现在只能新建反代站，静态站和wordpress和halo，如果我想直接新建一个自己的动态站似乎是不行的，折中的方法是新建wp然后把文件替换为自己的网站文件（还没测试），但是这又太麻烦了，所以还是希望可以支持普通php网站

### 请描述你建议的实现方案

总之就是希望可以支持普通php网站

还有！！新建反代站的时候这个反代地址我需要手动输入完整的`http://127.0.0.1:8080`，这太麻烦了，希望新建反代的时候输入框里默认就有 http://127.0.0.1:8080 然后我们只需要修改端口号就行了

![image](https://user-images.githubusercontent.com/58991169/225374008-d158417e-693c-4150-aa4d-a8f21da41a0b.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本中持续优化。

**Comment by maninhill** [comment]
#222 与这个重复，v1.1 会支持 php。

**Comment by miaowmint** [comment]
> #222 与这个重复，v1.1 会支持 php。

OK收到
