### ISSUE TITLE
[BUG]防火墙 IP 规则无法批量删除

### ISSUE THREAD

**Issue by youyou-sudo** [1Panel-dev/1Panel#2430]
### 联系方式

JerryYang.XYY@outlook.com

### 1Panel 版本

v1.6.2

### 问题描述

防火墙---IP 规则 界面
使用复选框选中所有，点击删除，只删除了一个规则，并没有删除其他也选中的规则

### 重现步骤

防火墙---IP 规则 界面
使用复选框选中所有，点击删除

### 期待的正确结果

能正常选中并删除选中的 IP 规则

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
