### ISSUE TITLE
[FEATURE] 网站修改主域名 优化

### ISSUE THREAD

**Issue by yutangbb** [1Panel-dev/1Panel#2432]
### 1Panel 版本

v1.6.2

### 请描述您的需求或者改进建议

目前新建网站时设置主域名，会将主域名作为网站的初始域名。
后续添加其它域名后可以删除初始域名，但是即使删除了这个域名，其仍为该网站的主域名。
我的理解，主域名除了作为新建网站的初始域名，其次就是作为这个网站的名称，不与网站配置相关联。
在 "网站设置-其他" 中有主域名设置，但是 "主域名" 输入框为禁用状态，通过浏览器开发者工具去除输入框的 disabled 属性使其可编辑，点保存可以修改成功。
建议后续允许修改主域名。

### 请描述你建议的实现方案

有以下建议可供参考
1. 可以从网站绑定的现有域名中选择一个作为主域名。
2. 可以手动设置主域名，如果这个域名没有绑定该网站，则将域名绑定到网站，或者由用户自行选择是否绑定。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持上述优化。

**Comment by yutangbb** [comment]
v1.7.0 版本中主域名可编辑
