### ISSUE TITLE
[QUESTION]关于守护进程的使用问题

### ISSUE THREAD

**Issue by youzhazhu** [1Panel-dev/1Panel#2433]
您好，想请教下关于守护进程的问题：
1Panel上的Supervisor是部署在宿主机上的，但是网站是以容器形式存在的，所以似乎没法直接执行php命令？

`任务队列命令`
`php /www/sites/xxx.example.com/index/cron/task.php`

想请问下这种情况应该怎么添加守护进程呢？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
通过创建 Shell 类型计划任务（容器）是否可以满足上述需求，如图：
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/1194596b-3745-42fc-8ea4-dfb6df249cd6">

**Comment by Antake2333** [comment]
运行脚本监控容器内进程应该也可以,但是很麻烦呀,有没有更好的办法哦

**Comment by wanghe-fit2cloud** [comment]
> 运行脚本监控容器内进程应该也可以,但是很麻烦呀,有没有更好的办法哦

收到，后续版本调研一下可行性方案。

**Comment by wanghe-fit2cloud** [comment]
重复 #2683
