### ISSUE TITLE
[BUG] 无法启动openrestry

### ISSUE THREAD

**Issue by cddqssc** [1Panel-dev/1Panel#2443]
### 1Panel 版本

1.6.2

### 问题描述

无法启动openrestry
![image](https://github.com/1Panel-dev/1Panel/assets/31430047/79d9a4eb-c64e-4609-9cf1-081b7c7fc5c6)

### 重现步骤

新装的1panel，安装openrestry，无法启动，
实际上是存在该文件的：
![image](https://github.com/1Panel-dev/1Panel/assets/31430047/2c5e25dd-cc88-4550-9e98-eb5ad682f7fd)

**Comment by zhengkunwang223** [comment]
什么操作系统？

**Comment by cddqssc** [comment]
> 什么操作系统？

![image](https://github.com/1Panel-dev/1Panel/assets/31430047/8ec8485b-7e3b-44e4-b0af-c4b45c3ff936)

**Comment by zhengkunwang223** [comment]
看一下 /usr/local/bin 下 1panel 二进制的权限 需要是 root

**Comment by cddqssc** [comment]
> 看一下 /usr/local/bin 下 1panel 二进制的权限 需要是 root

![image](https://github.com/1Panel-dev/1Panel/assets/31430047/1b4d7fd9-20f9-4241-b50b-8834df2ecf93)

**Comment by cddqssc** [comment]
> 看一下 /usr/local/bin 下 1panel 二进制的权限 需要是 root

是在root下安装的：
![image](https://github.com/1Panel-dev/1Panel/assets/31430047/b8f4378e-3b02-43c8-afc6-3df870c94258)

**Comment by zhengkunwang223** [comment]
在群里吗 联系 “程会玩” 帮你看一下

**Comment by cddqssc** [comment]
重装系统就好了，估计是因为系统“不干净”吧
