### ISSUE TITLE
[BUG] 登录成功之后又跳到登录页面

### ISSUE THREAD

**Issue by SIGHTDEEP** [1Panel-dev/1Panel#2448]
### 1Panel 版本

1.6.2

### 问题描述

登录成功之后又跳到 登录页面，输入页面完整路径也能进去，但点别的菜单又跳回登录页；放一会莫名其妙自己又好了

我是ipv6域名解析到openresty，再反向代理到面板的，用的域名访问

### 重现步骤

退出重新登录就会复现

### 期待的正确结果

登录成功

**Comment by ssongliu** [comment]
感谢反馈！直接通过 ip+端口 访问正常吗？

可以扫描下面二维码加入社区群，我们远程看一下这个问题。
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/72681493-b8d8-497d-b10e-af803321c30d)

**Comment by IZRINO** [comment]
我现在也遇到了这个问题

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I'm also encountering this problem now

**Comment by SIGHTDEEP** [comment]
@IZRINO 如果也是反向代理的话，看看是不是开启了缓存

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@IZRINO If it is also a reverse proxy, check if caching is enabled

**Comment by IZRINO** [comment]
在这个问题发生后我重新安装了一次，但是还是不行，而且这个问题只在 edge 上出现，我使用 firefox 可以正常运行。

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I reinstalled it once after this problem occurred, but it still didn't work, and this problem only occurred on edge. I used firefox and it ran normally.

**Comment by thluozw** [comment]
> 在这个问题发生后我重新安装了一次，但是还是不行，而且这个问题只在 edge 上出现，我使用 firefox 可以正常运行。

我也是edge出现点击登录不跳转，后来把相关cookie清了就好了

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> I reinstalled it once after this problem, but it still didn't work, and the problem only appears on edge, I use firefox to work fine.

I also clicked on edge to log in and didn't jump. Later, I just cleared the relevant cookies.

**Comment by ltcsky2000** [comment]
类似的环境，1panel反代自己，套了cloudflare的cdn和域名，问题是用域名访问登录后又跳回登录页面，尝试用ip可以登录，然后关掉反代的缓存，然后域名也可以正常登录了。
