### ISSUE TITLE
[FEATURE]现在一键安装脚本不支持RockyLinux8

### ISSUE THREAD

**Issue by ATiRadeon** [1Panel-dev/1Panel#245]
### 1Panel 版本

1.0.1

### 请描述您的需求或者改进建议

现在一键安装脚本不支持RockyLinux8，CentOS已经被弃，还望支持Rocky，谢谢~！
ERROR: Unsupported distribution 'rocky'

### 附加信息
![image](https://user-images.githubusercontent.com/26919184/225491640-99d68582-e2f5-465f-90a7-5665aa35ca8f.png)

_No response_

**Comment by wanghe-fit2cloud** [comment]
没问题，后续版本支持。

**Comment by wanghe-fit2cloud** [comment]
报错原因是因为 Docker 在线安装脚本不支持 RockyLinux 导致的。
目前最好的解决方案就是先手动在服务器上安装并启动 Docker，然后再安装 1Panel 是可以正常运行的。

### 设置仓库（阿里源）
```shell
sudo yum-config-manager \
    --add-repo \
    http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
```
### 安装 Docker
```shell
sudo yum install docker-ce docker-ce-cli containerd.io docker-compose-plugin
```

**Comment by wanghe-fit2cloud** [comment]
可以使用以下脚本一键安装 Docker：
```shell
bash <(curl -sSL https://linuxmirrors.cn/docker.sh)
```
