### ISSUE TITLE
[FEATURE]postgres面板管理支持

### ISSUE THREAD

**Issue by lcese** [1Panel-dev/1Panel#2450]
### 1Panel 版本

1.6

### 请描述您的需求或者改进建议

目前已经使用到了1.6版本。不知道什么时候开始支持postgres面板管理，这个LSSUUES我看有人已经提及到了
#1175 
#758

**Comment by wanghe-fit2cloud** [comment]
已经纳入迭代计划，近期版本就会支持。
> 重复 Issue，就先关闭了

**Comment by wanghe-fit2cloud** [comment]
重复 #758
