### ISSUE TITLE
[FEATURE]远程数据库是否支持Supabase连接

### ISSUE THREAD

**Issue by 52008** [1Panel-dev/1Panel#2463]
### 1Panel 版本

v1.6.2

### 请描述您的需求或者改进建议

考虑一下服务器内存比较小，安装Mysql后基本就没多少内存了，
是否可以添加远程数据库 https://supabase.com/
我尝试在supabase创建数据库后，再连接返回失败

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在后续版本中先调研一下可行性方案。

**Comment by 52008** [comment]
非常期待

**Comment by maninhill** [comment]
请问这个问题有进展吗？

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is there any progress on this issue?

**Comment by wanghe-fit2cloud** [comment]
中短期内暂无计划支持 Supabase 远程数据库，望理解。
