### ISSUE TITLE
[FEATURE]使用命令直接创建的容器名字略长，通过 1Panel 编辑时受限制，希望加大长度限制。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#2465]
### 1Panel 版本

v1.6.2

### 请描述您的需求或者改进建议

使用命令直接创建的容器名字略长，通过1panel编辑时受限制。

![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/2f15584c-23cf-48dc-bf1a-d76be0fc1822)

**希望加大长度限制**

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
