### ISSUE TITLE
[BUG] 防火墙ufw端口删除不干净

### ISSUE THREAD

**Issue by OrangeMas** [1Panel-dev/1Panel#2469]
### 1Panel 版本

v1.6.2

### 问题描述

系统版本:ArchLinux
在防火墙内添加一个端口，然后删掉此端口。后台显示仍然存在这个端口的v6规则

### 重现步骤

在防火墙内添加一个端口，然后删掉此端口。后台显示仍然存在这个端口的v6规则，v4端口则删除

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们计划在 v1.8 版本完成上述问题优化。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
