### ISSUE TITLE
[FEATURE]希望可以在容器页面的标题栏加上各个状态的容器数量

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#2471]
### 1Panel 版本

v1.6.2

### 请描述您的需求或者改进建议

如题，现在容器数量多的时候要翻页看容器状态

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本支持上述需求。
> 容器列表页面支持用户根据状态筛选。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
