### ISSUE TITLE
Alpine Linux install error[BUG]

### ISSUE THREAD

**Issue by netPokey** [1Panel-dev/1Panel#2472]
### 1Panel 版本

new

### 问题描述

alpine没有使用fedora的systemctl来进行服务管理，使用的是RC系列命令

### 重现步骤

Alpine Linux

### 期待的正确结果

适配

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本可能会考虑支持 Alpine Linux。

**Comment by okxlin** [comment]
没有systemd的可以用docker版将就一下

https://hub.docker.com/r/moelin/1panel
