### ISSUE TITLE
[BUG] DNS 相关问题

### ISSUE THREAD

**Issue by gee1k** [1Panel-dev/1Panel#2473]
### 1Panel 版本

v1.6.2

#### 问题1:

反向代理网站时，使用 HTTP 方式生成证书会报错，类似：
```
服务内部错误: error: one or more domains had a problem: [xxx.xxx.cc] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 146.56.165.8: Invalid response from http://xxx.xxx.cc/.well-known/acme-challenge/bibT_FHJGwh98Ge7lnbjT3fmfrZRxvfTbr-qkCSBHTQ: "<!DOCTYPE html>\n<html>\n <head>\n <meta charset=\"UTF-8\" />\n <link rel=\"icon\" href=\"/assets/png/favicon-abe32304.p"
```

手动修改配置文件中的 `location ~ /.well-known/acme-challenge` 为 `location ^~ /.well-known/acme-challenge` 即可正常生成证书

#### 问题2: 

最开始配置了 Cloudflare 的 DNS 账户，后来我选择采用 HTTP 方式来生成 DNS，完全没有使用到 DNS 账户，但是删除该 DNS 账户时却提示 `账号关联证书，无法删除` 

### 重现步骤

见问题

**Comment by gee1k** [comment]
补充信息：
1.刚刚打开 1panel 的数据库文件查看，发现了 website_ssls 表中。属于 HTTP 类型的证书也关联了 dns_account_id，这是不是不对的？
<img width="507" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/12059800/6237d67e-167e-4c2c-adfb-e3a1c25b122d">

问题猜测，由于我在创建证书前增加了 dns 账户，并且在创建证书的时候，是会默认选中dns模式和第一个 dns 账户的，此时再切换到 HTTP 模式时，虽然 dns 账户选择框没了，但是之前选择的值并没有清理吧


2.顺带发现另一个小问题，dns_account 表中的 created_at 字段时间不对
<img width="262" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/12059800/2d33d803-67eb-4869-bc9d-7b9ac7d1613b">

**Comment by gee1k** [comment]
> 补充信息： 1.刚刚打开 1panel 的数据库文件查看，发现了 website_ssls 表中。属于 HTTP 类型的证书也关联了 dns_account_id，这是不是不对的？ <img alt="image" width="507" src="https://user-images.githubusercontent.com/12059800/273486252-6237d67e-167e-4c2c-adfb-e3a1c25b122d.png">
> 
> 问题猜测，由于我在创建证书前增加了 dns 账户，并且在创建证书的时候，是会默认选中dns模式和第一个 dns 账户的，此时再切换到 HTTP 模式时，虽然 dns 账户选择框没了，但是之前选择的值并没有清理吧
> 
> 2.顺带发现另一个小问题，dns_account 表中的 created_at 字段时间不对 <img alt="image" width="262" src="https://user-images.githubusercontent.com/12059800/273486309-2d33d803-67eb-4869-bc9d-7b9ac7d1613b.png">

https://github.com/1Panel-dev/1Panel/blob/7171c13e3189f581684b0572bd84abca354754fb/frontend/src/views/website/ssl/create/index.vue#L165-L175

**Comment by zhengkunwang223** [comment]
感谢反馈  马上修复

**Comment by gee1k** [comment]
👍速度

> #### 问题1：
> 反向代理网站时，使用HTTP方式生成证书会报错，类似：
> 
> ```
> 服务内部错误: error: one or more domains had a problem: [xxx.xxx.cc] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 146.56.165.8: Invalid response from http://xxx.xxx.cc/.well-known/acme-challenge/bibT_FHJGwh98Ge7lnbjT3fmfrZRxvfTbr-qkCSBHTQ: "<!DOCTYPE html>\n<html>\n <head>\n <meta charset=\"UTF-8\" />\n <link rel=\"icon\" href=\"/assets/png/favicon-abe32304.p"
> ```

这个问题麻烦也看看，不然每次手动改一下挺麻烦

**Comment by zhengkunwang223** [comment]
> 👍速度
> 
> > #### 问题1：
> > 反向代理网站时，使用HTTP方式生成证书会报错，类似：
> > ```
> > 服务内部错误: error: one or more domains had a problem: [xxx.xxx.cc] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 146.56.165.8: Invalid response from http://xxx.xxx.cc/.well-known/acme-challenge/bibT_FHJGwh98Ge7lnbjT3fmfrZRxvfTbr-qkCSBHTQ: "<!DOCTYPE html>\n<html>\n <head>\n <meta charset=\"UTF-8\" />\n <link rel=\"icon\" href=\"/assets/png/favicon-abe32304.p"
> > ```
> 
> 这个问题麻烦也看看，不然每次手动改一下挺麻烦

这个已经提交了 跟随 v1.7.0 一同发布

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
