### ISSUE TITLE
[FEATURE]外部域名访问面板

### ISSUE THREAD

**Issue by zhuozhiyongde** [1Panel-dev/1Panel#2477]
### 1Panel 版本

1.6.2

### 请描述您的需求或者改进建议

如题，希望能类似宝塔一样支持对面板进行域名访问，而非ip访问，同时支持HTTPS协议，现在试用反向代理部署网站代理到面板端口会提示：
<img width="1447" alt="Cleanshot-2023-10-09-at-11 59 14@2x" src="https://github.com/1Panel-dev/1Panel/assets/36695271/569d35ba-a98b-4e38-b9be-5bf47ab1ad3e">

### 请描述你建议的实现方案

允许使用反向代理访问，但我不清楚这么做是否会引发安全上的问题。

**Comment by wanghe-fit2cloud** [comment]
当前版本已经支持上述配置，如下图：
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/aba107b5-5a1c-4224-9327-119ac5f1fa41">

> 添加反向代理网站时，代理地址不要带安全入口。在浏览器第一次访问时，域名后加安全入口。
