### ISSUE TITLE
[BUG]远程数据库不识别

### ISSUE THREAD

**Issue by skyhhjmk** [1Panel-dev/1Panel#2478]
### 联系方式

admin@biliwind.com

### 1Panel 版本

v1.6.2

### 问题描述

应用商店安装软件时无法识别添加的远程数据库
![image](https://github.com/1Panel-dev/1Panel/assets/78078552/28350960-3acb-49f1-9de8-93e3f23e3d70)

![image](https://github.com/1Panel-dev/1Panel/assets/78078552/e493a185-653f-472d-baaa-11bfad486731)

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/78078552/e493a185-653f-472d-baaa-11bfad486731)

很简单，添加一个远程数据库，然后去安装一个需要数据库的应用（如wiki.js）

**Comment by zhengkunwang223** [comment]
v1.7.0 支持此功能

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
