### ISSUE TITLE
[FEATURE]面板需要定期reload证书

### ISSUE THREAD

**Issue by everleek** [1Panel-dev/1Panel#2480]
### 1Panel 版本

1.6.2

### 请描述您的需求或者改进建议

如果面板引用的是内部管理的自动续签的证书，应该添加在自动续签后通知面板reload。（或其他策略，例如定时reload）

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本完成上述功能优化。

**Comment by zhengkunwang223** [comment]
请问是续签之后 reload Nginx 吗 ，现在已经支持

**Comment by everleek** [comment]
续签之后，reload 面板 http web 吧？

**Comment by everleek** [comment]
nginx （openrestry）应该也要 reload 吧。

**Comment by zyyfit** [comment]
1.9.0 版本将会增加 openresty 重载 按钮，面板证书如果续签的话，需要手动重启1panel服务

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
