### ISSUE TITLE
[FEATURE]1panel自签证书同步南墙uuwaf

### ISSUE THREAD

**Issue by vvvsrx** [1Panel-dev/1Panel#2486]
### 1Panel 版本

1.6.2

### 请描述您的需求或者改进建议

1panel的证书同步到南墙中,实现南墙证书自签.

### 请描述你建议的实现方案

我看了下,南墙是mysql保存的证书,1panel可以做一个外挂或者Hook直接在续签时自动同步到南墙.

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本调研一下可行性方案。

**Comment by wanghe-fit2cloud** [comment]
经讨论，在中短期内我们暂时不会支持上述需求，望理解。
