### ISSUE TITLE
[BUG] 防火墙里端口规则中描述无法保存

### ISSUE THREAD

**Issue by zxwmfcm** [1Panel-dev/1Panel#2487]
### 1Panel 版本

v1.6.2

### 问题描述

![1696920422292](https://github.com/1Panel-dev/1Panel/assets/30642864/39fab7a3-a787-4ce3-9430-aa4fb6427dd8)
![image](https://github.com/1Panel-dev/1Panel/assets/30642864/3ac7fe6e-4dd8-420f-833a-9ca2204b9d8c)

选tcp/udp之后 描述就不能保存了

### 重现步骤

在防火墙中添加端口规则 选择tcp/udp  填写描述

**Comment by ssongliu** [comment]
感谢反馈！麻烦确认一下这里防火墙是 ufw 还是 firewalld 呢？在界面上面有一行提示信息

**Comment by zxwmfcm** [comment]
> 感谢反馈！麻烦确认一下这里防火墙是 ufw 还是 firewalld 呢？在界面上面有一行提示信息

ufw

**Comment by ssongliu** [comment]
好的，开发环境已经复现了，本周四发布的 v1.7.0 解决该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
