### ISSUE TITLE
关于网站功能的一些建议

### ISSUE THREAD

**Issue by miaowmint** [1Panel-dev/1Panel#249]
### 1Panel 版本

v1.0.1

### 请描述您的需求或者改进建议

一个是现在不能直接进入网站目录，需要先进入网站设置，点击网站目录，才能点击文件夹图片进入网站的目录

![image](https://user-images.githubusercontent.com/58991169/225503565-d9829950-fb24-4ef1-8488-ee3e95b7a462.png)

另一个是现在不能修改网站运行目录，如果以后1panel支持了php这个功能是非常有必要的
![image](https://user-images.githubusercontent.com/58991169/225504273-2894bd2f-c368-41c9-9349-a4de65a9f0f4.png)

### 请描述你建议的实现方案

关于不能直接进入网站目录的问题，希望在网站页面能够直接放置一个网站目录，点击就可以进入，类似于下面这样
![image](https://user-images.githubusercontent.com/58991169/225505301-b2652716-a1ed-4d15-a928-a00f885a9d7a.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本会持续优化的。

**Comment by maninhill** [comment]
能否提供网页防篡改功能：

https://www.qianxin.com/product/detail/pid/427

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
