### ISSUE TITLE
[BUG]该备份文件与当前网站部分数据不匹配 ssl

### ISSUE THREAD

**Issue by xiexiaosheng** [1Panel-dev/1Panel#2494]
### 1Panel 版本

1.6.2

### 问题描述

导入备份时出现该备份文件与当前网站部分数据不匹配 ssl"

### 重现步骤

备份网站->下载备份->卸载PHP->安装PHP->导入备份->恢复->提示该备份文件与当前网站部分数据不匹配 ssl"

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by zhengkunwang223** [comment]
备份的网站数据包含证书，请先选择原备份网站的证书之后再执行恢复操作。
