### ISSUE TITLE
[FEATURE] 希望能上架paopao-ce的建站应用

### ISSUE THREAD

**Issue by wulintang** [1Panel-dev/1Panel#2496]
### 1Panel 版本

最新

### 请描述您的需求或者改进建议

特意开了一个月一台机子安装1p 测试paopao-ce安装无果，希望官方重视。服务器也马上到期了，所以我再在此处迫切的添加一下我的希望。

### 请描述你建议的实现方案

https://bbs.fit2cloud.com/t/topic/1719/3

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
由于我们应用商店的审查机制仍在不断完善中，因此我们决定在当前阶段不上架该应用。
我看到该应用的官方提供了详细的安装说明，包括通过容器化和编排方式启动服务，1Panel 目前是支持使用 compose 文件来直接运行和管理服务的，建议使用这种方式来管理上述服务。

> 1Panel 也提供了制作本地应用的教程。
[如何提交自己想要的应用](https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8)

**Comment by wulintang** [comment]
教程确实很详细，但完全看不懂。甚至不知道哪一步是做什么。按照他的教程下来，明明1Panel里有mysql、meilisearch、redis，但是他教程一手下来，就重新装了这几个的镜像，也不能升级，也不能管理。那我需要面板的意义又是什么。既然用户都选择用面板了，为何还要用户高度代码，还要自己制作应用什么的，非常不解。

**Comment by wanghe-fit2cloud** [comment]
> 教程确实很详细，但完全看不懂。甚至不知道哪一步是做什么。按照他的教程下来，明明1Panel里有mysql、meilisearch、redis，但是他教程一手下来，就重新装了这几个的镜像，也不能升级，也不能管理。那我需要面板的意义又是什么。既然用户都选择用面板了，为何还要用户高度代码，还要自己制作应用什么的，非常不解。

目前未上架官方应用商店的应用，是要通过自己制作本地应用的方式来解决，或者直接在容器界面通过编排来实现。

> 制作本地应用教程需要有一定的编码能力。
