### ISSUE TITLE
[FEATURE]请问有没有测试版更新渠道

### ISSUE THREAD

**Issue by androidmumo** [1Panel-dev/1Panel#2499]
### 1Panel 版本

1.6.2

### 请描述您的需求或者改进建议

希望可以在面板内选择版本更新渠道（测试版、正式版）。
原因有如下几点：
1.可以让爱好者尝鲜新功能。
2.可以发挥社区的力量一起发现测试版的潜在问题。
3.经过社区的充分验证，可以提高正式版的稳定性。

**Comment by zhengkunwang223** [comment]
当前测试版只开放给核心用户群
核心用户群需要通过爱发电发电一次进入
https://afdian.net/a/1Panel

**Comment by androidmumo** [comment]
> 当前测试版只开放给核心用户群 核心用户群需要通过爱发电发电一次进入 https://afdian.net/a/1Panel

已经加入核心用户群。仅发现体验地址。
不知能否将个人的服务器更新到测试版？

**Comment by zhengkunwang223** [comment]
> > 当前测试版只开放给核心用户群 核心用户群需要通过爱发电发电一次进入 https://afdian.net/a/1Panel
> 
> 已经加入核心用户群。仅发现体验地址。 不知能否将个人的服务器更新到测试版？

不建议这么做 可能会造成不可逆的后果
