### ISSUE TITLE
[BUG] 安装后无法通过ipv4 访问   

### ISSUE THREAD

**Issue by looksimpler** [1Panel-dev/1Panel#2502]
### 1Panel 版本

1.6.2

### 问题描述

Centos 9 Stream 64 Bit
安装后无法通过ipv4 访问   
netstat 查看发现只监听了ipv6

### 重现步骤

netstat -tulnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name  
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      739/sshd: /usr/sbin
tcp6       0      0 :::10618                :::*                    LISTEN      15912/1panel      
tcp6       0      0 :::22                   :::*                    LISTEN      739/sshd: /usr/sbin
udp        0      0 127.0.0.1:323           0.0.0.0:*                           675/chronyd       
udp6       0      0 ::1:323                 :::*                                675/chronyd       

### 相关日志输出

```shell
netstat -tulnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name  
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      739/sshd: /usr/sbin
tcp6       0      0 :::10618                :::*                    LISTEN      15912/1panel      
tcp6       0      0 :::22                   :::*                    LISTEN      739/sshd: /usr/sbin
udp        0      0 127.0.0.1:323           0.0.0.0:*                           675/chronyd       
udp6       0      0 ::1:323                 :::*                                675/chronyd
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
默认情况下，双栈网络服务器 IPv6优先级更高，可以查看一下 bindv6only 参数：
```shell
sysctl net.ipv6.bindv6only
```
如果值为 1，可以尝试将 net.ipv6.bindv6only 设置为0。

**Comment by looksimpler** [comment]
> 感谢反馈。 默认情况下，双栈网络服务器 IPv6优先级更高，可以查看一下 bindv6only 参数：
> 
> ```shell
> sysctl net.ipv6.bindv6only
> ```
> 
> 如果值为 1，可以尝试将 net.ipv6.bindv6only 设置为0。

net.ipv6.bindv6only = 0 
显示为 0

**Comment by looksimpler** [comment]
换个浏览器可以访问了 😂

**Comment by wanghe-fit2cloud** [comment]
重复 #1024
