### ISSUE TITLE
[BUG]v1.6.2面板，dataease无法一键升级

### ISSUE THREAD

**Issue by lifeigtr** [1Panel-dev/1Panel#2511]
### 联系方式

lifeigtr@qq.com

### 1Panel 版本

v1.6.2

### 问题描述

我是用的1P 是v1.6.2，  在1P里面装的dataease是 1.18.9， 但是应用商店 可升级的列表里面没有 dataease， 我去dataease官网看了，最新版是 1.18.11；

### 重现步骤

我是用的1P 是v1.6.2，  在1P里面装的dataease是 1.18.9， 但是应用商店 可升级的列表里面没有 dataease， 我去dataease官网看了，最新版是 1.18.11；

需要截图或者视频什么的 可以联系我邮箱！！！

### 期待的正确结果

让我能升级

**Comment by wanghe-fit2cloud** [comment]
手动更新应用列表，如图：
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/8c90b4e4-d969-4656-843b-6df765613bc7">
<img width="745" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/1d886197-fb9b-4260-8166-b8de8245d85b">

**Comment by lifeigtr** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
