### ISSUE TITLE
[FEATURE]minio版本已经很久没有更新过了

### ISSUE THREAD

**Issue by cyril-cheng** [1Panel-dev/1Panel#2523]
### 1Panel 版本

1.7.0

### 请描述您的需求或者改进建议

商店minio已经5个月没有更新过了。
商店minio现在版本号还是：RELEASE.2023-05-04T21-44-30Z，
官方的minio版本号已经是：RELEASE.2023-10-07T15-07-38Z了。
官方版本更新很快，基本是4-10天就会发布一个新版本。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本支持版本更新。

**Comment by wanghe-fit2cloud** [comment]
已经推送了更新。
进入应用商店列表，点击右上角的 `更新应用列表` 按钮，等待同步成功后再来安装应用。

**Comment by jxpeng98** [comment]
> 已经推送了更新。 进入应用商店列表，点击右上角的 `更新应用列表` 按钮，等待同步成功后再来安装应用。

@wanghe-fit2cloud 
公告显示minIO已经更新。但是已安装列表仍然是之前的版本：
<img width="357" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/83734772/3c5e9757-1adc-4b56-959a-3631bcea1ddb">

并且在可升级列表中也没有minIO
<img width="1463" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/83734772/72626bb1-6a83-4d32-9318-37185debe956">

有什么办法可以解决这个问题然后正常升级吗？
