### ISSUE TITLE
[FEATURE]太多失败了，不能一键全选一次性屏蔽么

### ISSUE THREAD

**Issue by follow2015** [1Panel-dev/1Panel#2524]
### 1Panel 版本

1.70

### 请描述您的需求或者改进建议

太多失败了，不能一键全选一次性屏蔽么这么多页好难操作。还要把成功的IP剔除。

### 附加信息

<img width="728" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/15902098/fd1d40ff-012d-4935-be64-c8d6aea5c62a">

**Comment by ssongliu** [comment]
感谢反馈！这里可以先参考下面的 issue 操作，这样降低爆破风险，不然一键屏蔽后还是会有新的 ip 来攻击。
https://github.com/1Panel-dev/1Panel/issues/1746

这里设置分页的主要原因是，ufw 防火墙增加规则时不支持并发操作，如果直接串行的话，数据量大耗时又会特别长，我们再找找这种情况的解决办法。

**Comment by follow2015** [comment]
这些都知道。不能并发的话，能不能设置失败几次就直接屏蔽。或者等到每天固定的时间点，一次性屏蔽当天多次失败的IP（最后成功了的IP要排除掉）

**Comment by ssongliu** [comment]
计划在 1.9 版本支持 fail2ban，统一管理。

**Comment by wanghe-fit2cloud** [comment]
重复 #1643
