### ISSUE TITLE
[FEATURE] Node.js 创建运行环境中包管理器可以支持 PNPM 吗

### ISSUE THREAD

**Issue by syntroy** [1Panel-dev/1Panel#2527]
### 1Panel 版本

1.7.0

### 请描述您的需求或者改进建议

目前包管理器只有npm或者yarn，可以支持pnpm吗

**Comment by zhengkunwang223** [comment]
我们先调研一下

**Comment by bd-dxg** [comment]
> 我们先调研一下

pnpm如日中天, 这还需要调研吗 现在还有什么项目不用pnpm的 我pnpm都用了2年了

**Comment by Hainess** [comment]
快加~

**Comment by Sectriwind** [comment]
希望Node.js 创建运行环境中包管理器可以支持 PNPM
有没有大佬会弄n8n，我用docker的安装不了拓展的npm包

**Comment by bd-dxg** [comment]
@zhengkunwang223 请问调研完毕了?

**Comment by zhengkunwang223** [comment]
> @zhengkunwang223 请问调研完毕了?

初步的想法是我们维护一个携带 pnmp 的镜像，这个如果快的话，会在最近几个版本完成

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
