### ISSUE TITLE
[FEATURE] 修改 1Panel 域名格式校验规则

### ISSUE THREAD

**Issue by yutangbb** [1Panel-dev/1Panel#2530]
### 1Panel 版本

v1.7.0

### 请描述您的需求或者改进建议

HTTP 协议 URL 格式如下
```
http://host:port/path?query_string
```
1Panel 中的域名概念是指 host，对应 openresty / nginx 中的 server_name
host 可以是域名、IP、主机名
目前 1Panel 新建网站和新增域名，或者面板安全设置域名绑定时 只能设置域名和IP，没有考虑主机名的情况，虽然主机名往往在内网中使用，但这在开发、维护和测试中非常有用。例如我想给 1panel 面板绑定域名访问不使用公网域名而是使用 `1panel`  ，然后自己做 DNS，这样更方便并且提高了安全性。

应该支持如下这样的
一个下滑线：_ ，这表示不绑定域名，一般用于默认站点（只在 openresty / nginx 配置文件中使用）
没有后缀的主机名，例如：localhost、SERVER_A
另外还要考虑 IPv6 情况。

### 请描述你建议的实现方案

修改正则匹配规则

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
建议将主机名定义为标准 `域名` 格式写入 hosts，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/dc689857-df6a-401f-9434-67197221a92a)
