### ISSUE TITLE
1panel最新版本升级后 docker halo  启动失败。一直重启 

### ISSUE THREAD

**Issue by Jehol1983** [1Panel-dev/1Panel#2531]
### 联系方式

1422647137@qq.com

### 1Panel 版本

最新

### 问题描述

1panel最新版本升级后 docker halo  启动失败。一直重启 

### 重现步骤

1panel最新版本升级后 docker halo  启动失败。一直重启 

### 期待的正确结果

1panel最新版本升级后 docker halo  启动失败。一直重启

**Comment by zhengkunwang223** [comment]
https://bbs.halo.run/d/4362-%E9%80%9A%E8%BF%871panel%E5%8D%87%E7%BA%A7280--291%E5%90%8E%E5%90%AF%E5%8A%A8%E5%A4%B1%E8%B4%A5
参考这个
