### ISSUE TITLE
[FEATURE] 能否增加开机启动管理?

### ISSUE THREAD

**Issue by gowy222** [1Panel-dev/1Panel#2533]
### 1Panel 版本

1.7

### 请描述您的需求或者改进建议

本地服务器 涉及到 定时重启和断电重启，这种情况下需要开机运行一个脚本来初始化一些操作，比如检验 ups电池的情况..
宝塔面板有这个功能，
目前1panel没有。

### 请描述你建议的实现方案

方案1. 计划任务里面 加入 [开机启动]，用户填入sh脚本内容，或者填写 sh脚本路径。这种方式的好处是能看到执行log

方案2. 单独学习宝塔面板 有个tab页面可以管理开机启动项. 用户手动编辑 加入新的开机启动项

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
经讨论，我们中短期内不会考虑上述需求，望理解。
