### ISSUE TITLE
在使用Nodejs创建运行环境的时候，是不是要导入node_modules文件夹？

### ISSUE THREAD

**Issue by jxpeng98** [1Panel-dev/1Panel#2534]
### 请描述您的问题

今天我尝试使用Nodejs来部署网站，但是创建运行环境之后直接把服务器卡崩了。
<img width="617" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/83734772/68bfcee3-4c2c-4743-801d-58c29eadb83e">

我首先克隆了GitHub的仓库到服务器，然后在源码目录的位置填上了文件夹地址，启动命令使用了`next dev`。

但是仓库里并没有相应的node_modules文件夹。 我的问题是：我需要先运行`npm install`安装需要的依赖包吗？还是创建运行环境的时候会自动安装？

在点击确认之后，直接把CPU占到了100%，内存也直接拉爆。这个是什么原因呢？

如果我想要正确创建运行环境，还需要进行什么操作？

谢谢！

**Comment by Dacong-wu** [comment]
你看下日志，就知道成功没有，按照我的理解，如果你没有打包，直接从git上拉的，那肯定没有包文件，所以肯定要npm i , 产品逻辑还是有问题，用着总是怪怪的

**Comment by zhengkunwang223** [comment]
创建成功之后会自动执行 npm install
