### ISSUE TITLE
[BUG]在数据库页面添加远程服务器时，用ipv6的域名好像不行

### ISSUE THREAD

**Issue by fayfoxcat** [1Panel-dev/1Panel#2535]
### 联系方式

fayfoxcat@gmail.com

### 1Panel 版本

1.7.0

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/54295055/58499297-0bab-4fa3-8f22-8d14c5256dc2)
在数据库页面添加远程服务器时，只能有ipv4的地址，用ipv6的域名好像不行

### 重现步骤

数据库页面-MySQL-连接远程服务器，添加数据库地址使用ipv6的域名连接不上

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本支持用户输入 IPv6 地址。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
