### ISSUE TITLE
[FEATURE] 建议增加Windows安装

### ISSUE THREAD

**Issue by JaneYork** [1Panel-dev/1Panel#2536]
### 1Panel 版本

1.7

### 请描述您的需求或者改进建议

1. 增加Windows8-10，Windows server服务器安装
2. 增加离线模式安装，局域网安装

**Comment by zhengkunwang223** [comment]
当前还是专注于 Linux 服务器的运维管理

**Comment by wc7086** [comment]
Windows 对 Docker 的支持可以说非常烂，所以 Windows 没有支持的必要，徒增维护成本
