### ISSUE TITLE
[BUG] 网站-证书的详情抽屉面板中其他域名没有正常显示

### ISSUE THREAD

**Issue by gee1k** [1Panel-dev/1Panel#2539]
### 1Panel 版本

1.7.0

### 问题描述

网站-证书的详情抽屉面板中`其他域名`没有正常显示，始终显示为空。在列表中是有显示出其他域名的

### 重现步骤

网站-证书的详情抽屉面板中`其他域名`没有正常显示，始终显示为空。在列表中是有显示出其他域名的

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.7.1 版本已发布。
