### ISSUE TITLE
[FEATURE] 建议为两步验证添加记住设备的功能

### ISSUE THREAD

**Issue by chickun-io** [1Panel-dev/1Panel#2543]
### 1Panel 版本

1.7.0

### 请描述您的需求或者改进建议

我是1Panel的用户，非常感谢您们提供了这么好用的服务器面板。但是，我希望能够在1Panel中添加两步验证（MFA）功能，以增强账户的安全性。目前虽然1Panel支持MFA，但是不能记住设备，每次登录都需要输入MFA验证码，这样使用起来相对不太方便。我建议能够添加一个“记住设备”选项，允许用户在特定设备上登录时不用重复输入MFA验证码，这样不仅提高了安全性，也提供了更好的用户体验。

### 请描述你建议的实现方案

我建议在登录时添加一个复选框，例如：“记住此设备”。当用户勾选了这个选项并成功登录时，将该设备的唯一标识（如UUID或MAC地址）上传到1Panel服务器中。当用户在这台设备上再次登录时，系统会识别该标识，不再要求MFA验证码。这样，用户可以在特定设备上享受更便捷的登录体验，同时保持账户的安全性。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复 Issue #2544
