### ISSUE TITLE
[FEATURE] 登录日志-统计信息屏蔽时可以自动添加或自己输入屏蔽原因

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#2547]
### 1Panel 版本

1.7

### 请描述您的需求或者改进建议

查看防火墙-IP规则，查看ip 不清楚屏蔽的原因

登录日志-统计信息屏蔽时， 是否可以自动添加简单的描述信息
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/3bf80266-b843-445c-b29f-4d440ae4dd28)
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/1a150a51-9050-47ed-bf24-f745cf1e489d)

### 请描述你建议的实现方案

登录日志-统计信息屏蔽时， 自动添加简单的描述信息， 或者自己输入原因

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by ssongliu** [comment]
1.9 版本计划支持 fail2ban，ssh ip 屏蔽的功能从防火墙屏蔽转为 fail2ban。

**Comment by wanghe-fit2cloud** [comment]
重复 #1643
