### ISSUE TITLE
[QUESTION]nginx proxy manager如何使用443端口

### ISSUE THREAD

**Issue by imokgood** [1Panel-dev/1Panel#2548]
### 请描述您的问题

应用商店里nginx proxy manager默认给的端口是30443、30080、30081，请问如何能使用443端口，不然只能是https://域名:30443这种，自行修改443端口提示和openresty冲突

**Comment by wanghe-fit2cloud** [comment]
> 默认给的端口是30443、30080、30081

因为应用是容器化部署，上述三个端口都是对外暴露端口。在确保 1Panel 服务中端口不冲突的情况下可以随意修改。
> nginx proxy manager 具体使用问题，还可以参考其官方文档。
