### ISSUE TITLE
[FEATURE] 增加一键迁移功能

### ISSUE THREAD

**Issue by laxuou** [1Panel-dev/1Panel#2549]
### 1Panel 版本

1.7.0

### 请描述您的需求或者改进建议

希望能增加一个一键迁移功能，方便将数据从一台迁移到另一台。

### 请描述你建议的实现方案

可参考宝塔。
也许可以对快照进行识别添加。

**Comment by wanghe-fit2cloud** [comment]
可以使用 A 服务器的快照在 B 服务器中恢复。
> 在面板设置中添加相同的备份账号。
