### ISSUE TITLE
[BUG] 在面板中创建容器时选择“host”网络，容器启动后，无法访问容器内服务的端口

### ISSUE THREAD

**Issue by Frost-ZX** [1Panel-dev/1Panel#2550]
### 1Panel 版本

v1.7.0

### 问题描述

在 1Panel 面板创建容器时选择“host”网络，容器启动后，无法访问容器内服务的端口。

而直接使用命令 `docker run --network=host` 创建的容器可以正常访问对应的端口。

### 重现步骤

1. 创建容器（使用 `ghcr.io/natfrp/launcher:latest` 镜像，网络选择 `host`）。

   ![image](https://github.com/1Panel-dev/1Panel/assets/30585462/5e191951-be4f-449d-b6d3-d143fcbf27a9)
   ![image](https://github.com/1Panel-dev/1Panel/assets/30585462/eae66eed-6d4d-4115-bc4c-f23532bcb86b)

2. 等待容器启动完成，日志中显示 `Web UI (TLS) 已在 0.0.0.0:4101 启动`。

   ![image](https://github.com/1Panel-dev/1Panel/assets/30585462/d2991039-ef96-47aa-aee1-3ebe4b1e3a52)

3. 使用浏览器访问 `https://<服务器 IP>:4101`，浏览器提示 `ERR_CONNECTION_REFUSED`。

   ![image](https://github.com/1Panel-dev/1Panel/assets/30585462/f655b825-15c5-45ab-b5d3-087542b268a1)

### 附加信息

手动创建时使用的命令：`docker run -d --name=test-2 --net=host --restart=on-failure:5 ghcr.io/natfrp/launcher:latest`

对比容器配置文件，使用面板创建的容器 `NetworkMode` 为 `default`，使用命令创建的容器 `NetworkMode` 为 `host`。

![image](https://github.com/1Panel-dev/1Panel/assets/30585462/a7117825-1eca-4caf-84d0-411ea8c1e945)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wc7086** [comment]
vnstat 无法使用，与这个问题有关
```log
2023-10-16 17:34:42: (../src/server.c.1909) server started (lighttpd/1.4.71)
../src/lighttpd-angel.c.107: child (pid=12) exited normally with exitcode: 0
lighttpd started on *:8685
No interfaces found in database, adding available interfaces...
Nothing to do, exiting.
```

**Comment by gowy222** [comment]
有没有一种可能，iptables-legacy 是不是使用传统的iptables? 很多容器内部都支持特定iptables

**Comment by wanghe-fit2cloud** [comment]
v1.7.2 版本已发布。
