### ISSUE TITLE
[FEATURE]进程守护建议增加一个开机延迟启动功能！！

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#2552]
### 1Panel 版本

最新版本

### 请描述您的需求或者改进建议

我这边没有用官方应用商店的frpc内网穿透，我是自己配置的内网穿透启动文件，然后用的进程守护功能实现的开机启动，但是有一个问题，就是家里断电重启后，因为网络还没分配好IP，服务器的进程守护就启动内网穿透了，然后结果就是启动成功，但日志里提示因为网络问题，跟穿透服务器连接失败，这种情况守护程序也不会自动重启动！！！

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑是否支持上述需求。

**Comment by maninhill** [comment]
请问这个问题有进展吗？

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is there any progress on this issue?

**Comment by wanghe-fit2cloud** [comment]
经过调研发现，supervisord 本身没有直接提供延迟启动的选项，但你可以尝试通过使用 sleep 命令来实现延迟启动。
```
[program:your_program]
command=sleep 30 && /path/to/your_program
```
