### ISSUE TITLE
[FEATURE] 商店的gitea改进

### ISSUE THREAD

**Issue by lchjczw** [1Panel-dev/1Panel#2555]
### 1Panel 版本

v1.7.1

### 请描述您的需求或者改进建议、

![image](https://github.com/1Panel-dev/1Panel/assets/12480676/37370c82-15df-453b-b39e-1552e5dccede)

商店的gitea，不要依赖数据，直接让填数据库类型和数据库地址，这样可以支持gitea原本就支持的数据库

### 请描述你建议的实现方案

商店的gitea，不要依赖数据，直接让填数据库类型和数据库地址，这样可以支持gitea原本就支持的数据库

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑是否支持上述需求。

**Comment by wc7086** [comment]
类似应用都可以做成提供两个选项二选一，自行填写数据库连接信息或直接使用本地数据库

**Comment by wanghe-fit2cloud** [comment]
重复 #1978
