### ISSUE TITLE
[FEATURE] 自动同步iptables的规则

### ISSUE THREAD

**Issue by lchjczw** [1Panel-dev/1Panel#2556]
### 1Panel 版本

v1.7.1

### 请描述您的需求或者改进建议

<img width="1304" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/12480676/25f25d84-b198-4a29-8867-0489cedcc378">

添加自动同步iptables的规则，就是用户手动命令创建的iptabales规则，不然看到的和真实的不一致

### 请描述你建议的实现方案

添加自动同步iptables的规则，就是用户手动命令创建的iptabales规则

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑是否支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
支持 iptables 相关功能的讨论，统一汇总到该 issue #2238
