### ISSUE TITLE
[BUG] phpadmin 无法访问，防火墙开了端口也没用。

### ISSUE THREAD

**Issue by linuxxx** [1Panel-dev/1Panel#2557]
### 1Panel 版本

v1.7.1

### 问题描述

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
[Sun Oct 15 04:18:32.670850 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.57 (Debian) PHP/8.2.11 configured -- resuming normal operations
[Sun Oct 15 04:18:32.670892 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

### 重现步骤

重装面板也没用。

**Comment by wanghe-fit2cloud** [comment]
需要详细描述一下具体是什么操作抛出的错误信息。

**Comment by ssongliu** [comment]
查看一下容器列表，端口前面是否为 127.0.0.1，如果是的话就是在安装应用的时候没有勾选对外暴露端口

可以已安装应用列表，参数 - 编辑 - 勾选高级设置 - 勾选外部端口访问。

如果还有其他的问题，可以再打开这个 issue。
