### ISSUE TITLE
[BUG]文件大小计算错误

### ISSUE THREAD

**Issue by xzxxv** [1Panel-dev/1Panel#2558]
### 1Panel 版本

：v1.7.1

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/67012610/d173e4c1-555a-4ddf-84b6-e226b0cad38a)

### 重现步骤

1

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，当前版本确实存在 `/proc` 目录大小计算错误的问题，我们会在近期版本调研一下具体解决方案。
> 调用系统接口返回的文件夹大小就是错误的值。
后续版本可能会考虑隐藏或者更换第三方sdk。
