### ISSUE TITLE
[FEATURE]可以增加mongodb数据库的创建与管理

### ISSUE THREAD

**Issue by LeeAndPan** [1Panel-dev/1Panel#2560]
### 1Panel 版本

1.7.1

### 请描述您的需求或者改进建议

可以增加像MySQL一样的mongodb数据库的创建与管理

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们将在后续版本考虑支持上述需求。

**Comment by HenryWu01** [comment]
我之前也提了个 issue #399，希望能加入 ``MongoDB`` 的可视化管理功能。``NoSQL`` 里 ``MongoDB`` 还是比较热门的

**Comment by wc7086** [comment]
@wanghe-fit2cloud 重复的 issue 可以考虑在回复中标记更早的 issue 后关闭。

**Comment by wanghe-fit2cloud** [comment]
> @wanghe-fit2cloud 重复的 issue 可以考虑在回复中标记更早的 issue 后关闭。

感谢建议。

**Comment by wanghe-fit2cloud** [comment]
重复 issue #399
