### ISSUE TITLE
[FEATURE]计划任务实时查看 log

### ISSUE THREAD

**Issue by jerryc127** [1Panel-dev/1Panel#2561]
### 1Panel 版本

1.7.1

### 请描述您的需求或者改进建议

现在的计划任务只能在运行完成后才会显示 log
问题是有时候想知道任务运行到哪个步骤或者卡在哪个步骤了
没有 log 查看很不方便

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本增加任务管理功能，到时会同步支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
