### ISSUE TITLE
[FEATURE]加入系统后台自动更新功能

### ISSUE THREAD

**Issue by shellsec** [1Panel-dev/1Panel#2563]
### 1Panel 版本

v1.7.1

### 请描述您的需求或者改进建议

除了面板点击升级，希望加入自动更新
1、可支持命令行检查自动更新-计划任务
2、后台面板直接 打钩自动升级

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，由于存在升级失败导致服务不可用等情况，我们大概率不会开放自动更新的入口，望理解。
> 中短期内还是需要用户手动升级。
后续版本可能会考虑支持批量升级、1pctl 命令行工具升级等等。
