### ISSUE TITLE
[FEATURE]计划任务增加清理缓存类型

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#2564]
### 1Panel 版本

v1.7.1

### 请描述您的需求或者改进建议

v1.7.0 版本，在面板设置中支持了缓存清理功能。
是否可以将其添加到计划任务，自动清理默认筛选出来的缓存文件？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个功能版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
