### ISSUE TITLE
[FEATURE]希望加入移动现有容器所在位置和修改安装容器默认位置的功能

### ISSUE THREAD

**Issue by Lynricsy** [1Panel-dev/1Panel#2568]
### 1Panel 版本

1.7.1

### 请描述您的需求或者改进建议

希望加入移动现有容器所在位置和修改安装容器默认位置的功能，因为大部分云服务器提供商提供的系统盘空间极其有限，如果容器都安装在系统盘那系统盘很快就会满了

**Comment by wanghe-fit2cloud** [comment]
进入 `容器` - `配置` 页面，点击 `全部配置`，然后写入以下内容来修改 docker 数据目录：
```json
{
  "data-root": "/www/docker"
}
```
保存即可。
