### ISSUE TITLE
[BUG]容器列表中的定时刷新不会被记住

### ISSUE THREAD

**Issue by wc7086** [1Panel-dev/1Panel#2569]
### 1Panel 版本

1.7.1

### 问题描述

容器列表设置刷新和刷新频率后切换页面会导致设置被重置

### 重现步骤

1. 打开容器页面
2. 设置定时刷新
3. 单击容器页面中的其他选项

### 附加信息

![bu1](https://github.com/1Panel-dev/1Panel/assets/74053663/a2ee0d5e-5a4f-40f3-b7ff-3a069ee5c98b)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
