### ISSUE TITLE
[FEATURE] 1Panel 中的网站功能同步到防火墙配置中

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#2570]
### 1Panel 版本

1.7.1

### 请描述您的需求或者改进建议

将 1Panel 的网站管理功能与南墙之类的防火墙同步，将这些网站配置信息同步到防火墙的网站配置中

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们后续版本讨论一下上述需求的可行性方案。

**Comment by wanghe-fit2cloud** [comment]
考虑到是完全独立的两款应用，暂时还没有更好的办法实现上述同步功能。
