### ISSUE TITLE
[BUG] 当前用户无权限

### ISSUE THREAD

**Issue by liuyiwuqing** [1Panel-dev/1Panel#2571]
### 1Panel 版本

v1.6.2

### 问题描述

更新v1.6.2之后，在主机-文件，修改文件的时候提示当前用户无权限，并退出1panel面板登录，在更新到v1.7.1之后依旧存在当前问题

### 重现步骤

无，目前三台服务器使用1panel面板，均使用官网一键安装脚本安装，目前仅一台服务器存在当前问题

**Comment by wanghe-fit2cloud** [comment]
文件列表中该文件的具体权限提供一下截图，我们先在本地环境复现一下。

**Comment by liuyiwuqing** [comment]
> 文件列表中该文件的具体权限提供一下截图，我们先在本地环境复现一下。

[演示](https://www.muyin.site/%E6%97%A0%E6%9D%83%E9%99%90.gif)

**Comment by wanghe-fit2cloud** [comment]
> > 文件列表中该文件的具体权限提供一下截图，我们先在本地环境复现一下。
> 
> [演示](https://www.muyin.site/%E6%97%A0%E6%9D%83%E9%99%90.gif)

注意到你关闭了该 Issue，问题是否已解决？

**Comment by liuyiwuqing** [comment]
> > > 文件列表中该文件的具体权限提供一下截图，我们先在本地环境复现一下。
> > 
> > 
> > [演示](https://www.muyin.site/%E6%97%A0%E6%9D%83%E9%99%90.gif)
> 
> 注意到你关闭了该 Issue，问题是否已解决？

已解决
