### ISSUE TITLE
[FEATURE]实时展示安装应用/制作镜像产出的日志

### ISSUE THREAD

**Issue by wc7086** [1Panel-dev/1Panel#2574]
### 1Panel 版本

1.7.1

### 请描述您的需求或者改进建议

安装应用/制作环境镜像时实时输出日志，不然有时候过程失败没回调或者在某个环节卡了很久不好排查原因。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wc7086** [comment]
重复 #1059
