### ISSUE TITLE
[BUG]PHP创建运行环境时，从下拉框选择扩展后，输入的字符未清空

### ISSUE THREAD

**Issue by wc7086** [1Panel-dev/1Panel#2575]
### 1Panel 版本

1.7.1

### 问题描述

PHP创建运行环境时，从下拉框选择扩展后，输入的字符未清空，当需要选择很多扩展时非常烦人

### 重现步骤

1. 创建运行环境
2. 在扩展中输入`redis`
3. 在下拉框中点击`redis`或单击回车键

### 期待的正确结果

在下拉框中点击`redis`或按回车键选择扩展后，用户输入的`redis`字符清空

### 附加信息

![bug2](https://github.com/1Panel-dev/1Panel/assets/74053663/9ad4c9ab-7089-4232-a81a-3994fae8eda7)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
上述下拉框控件确实是会出现这种情况，当下拉框鼠标失去焦点时才会自动消失。

**Comment by wc7086** [comment]
> 感谢反馈。 上述下拉框控件确实是会出现这种情况，当下拉框鼠标失去焦点时才会自动消失。

我的意思是点击下拉框或回车选择一个插件之后，输入的字符仍然存在，这就需要把原来输入的字符删除才能选择其他扩展，如果要选择很多扩展，那就需要按很多次回车清空输入。
![image](https://github.com/1Panel-dev/1Panel/assets/74053663/c3d9fa13-8299-43df-8433-8eaa6bc7eb2d)

**Comment by wc7086** [comment]
#2580
