### ISSUE TITLE
[FEATURE]一键安装支持双栈连接

### ISSUE THREAD

**Issue by swRains** [1Panel-dev/1Panel#2576]
### 1Panel 版本

/

### 请描述您的需求或者改进建议

目前的一键脚本不支持ipv6 only的 vps，如果有可能的话期望能支持下ipv6，这样会比release安装方便一些些。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
上述需求是要支持在双栈系统安装 1Panel 后，IPv4地址能正常访问 1Panel 系统吗？

**Comment by swRains** [comment]
> 感谢反馈。 上述需求是要支持在双栈系统安装 1Panel 后，IPv4地址能正常访问 1Panel 系统吗？

不是，是希望能支持下ipv6，说实话ipv6 only 的vps安装1panel还是有点费劲的，还得套个warp

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈。 上述需求是要支持在双栈系统安装 1Panel 后，IPv4地址能正常访问 1Panel 系统吗？
> 
> 不是，是希望能支持下ipv6，说实话ipv6 only 的vps安装1panel还是有点费劲的，还得套个warp

收到，可以进一下微信技术交流群，添加一下我好友。
> 方便远程看一下环境。

**Comment by wc7086** [comment]
@wanghe-fit2cloud 因为提供安装包下载的网址 https://resource.fit2cloud.com 没有 IPv6 DNS 解析，所以只有 IPv6 的网络不能下载安装包。

**Comment by wc7086** [comment]
解决方案是让 https://resource.fit2cloud.com/ 支持 IPv6。或在 GitHub Release 中提供安装包，当网络环境为 IPv6 only 时从 GitHub Release 下载安装包。

**Comment by wanghe-fit2cloud** [comment]
> 解决方案是让 https://resource.fit2cloud.com/ 支持 IPv6。或在 GitHub Release 中提供安装包，当网络环境为 IPv6 only 时从 GitHub Release 下载安装包。

好的，感谢反馈。

**Comment by liqiang-fit2cloud** [comment]
已支持IPv6。
<img width="824" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/20766823/ca58bd4c-e860-4b89-b251-238ca7dccd2f">

**Comment by swRains** [comment]
> 已支持IPv6。 <img alt="image" width="824" src="https://user-images.githubusercontent.com/20766823/276547744-ca58bd4c-e860-4b89-b251-238ca7dccd2f.png">

感谢！刚测试过，纯ipv6环境下正常丝滑
