### ISSUE TITLE
[FEATURE]创建运行环境时可批量修改扩展栏

### ISSUE THREAD

**Issue by wc7086** [1Panel-dev/1Panel#2580]
### 1Panel 版本

1.7.1

### 请描述您的需求或者改进建议

1.  使用户可以在扩展栏输入以下内容`opcache,fpm,mysql,redis,bcmath,curl,gd,mbstring,xml,bz2,zip,mysqli,pdo_mysql`，当所有扩展都存在时再将扩展转为标签形式，当其中有不存在的扩展时提示错误且不转为标签（或提示某扩展不存在但将存在的扩展转为标签）。
2. 用户双击扩展栏后将扩展栏内的标签转为如`opcache,fpm,mysql,redis,bcmath,curl,gd,mbstring,xml,bz2,zip,mysqli,pdo_mysql`的形式，让用户可以自由编辑。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑是否支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
PHP扩展相关需求的讨论，统一汇总到该 issue #1636
