### ISSUE TITLE
[BUG]在应用商店安装的frps-0.52.1启动异常

### ISSUE THREAD

**Issue by androidmumo** [1Panel-dev/1Panel#2583]
### 1Panel 版本

1.7.1

### 问题描述

<img width="616" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/36179789/5a3248e1-7b31-47dc-8b13-ada2aeb9bfd7">
frps没有正常启动。

### 重现步骤

安装后不做任何操作，点击同步按钮，即可看到异常。

### 附加信息

原因可能是frp更新了版本，不再支持ini配置文件：https://github.com/fatedier/frp/releases/tag/v0.52.0

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们将在近期版本适配新版本。

**Comment by lcese** [comment]
0.52后的版本都有问题。换成0.51版本就可以了。

**Comment by wanghe-fit2cloud** [comment]
> 0.52后的版本都有问题。换成0.51版本就可以了。

是的，近期可以先选择安装 0.51 版本。

**Comment by androidmumo** [comment]
> > 0.52后的版本都有问题。换成0.51版本就可以了。
> 
> 是的，近期可以先选择安装 0.51 版本。

或者可以编辑compose文件，把映射改成`./data/frps.toml:/etc/frp/frps.toml`，然后参照frp官方文档编写配置文件就行了。亲测可以正常使用。

**Comment by wanghe-fit2cloud** [comment]
> > > 0.52后的版本都有问题。换成0.51版本就可以了。
> > 
> > 
> > 是的，近期可以先选择安装 0.51 版本。
> 
> 或者可以编辑compose文件，把映射改成`./data/frps.toml:/etc/frp/frps.toml`，然后参照frp官方文档编写配置文件就行了。亲测可以正常使用。

可以将上述修改提交一个 Pull requests，感谢。
https://github.com/1Panel-dev/appstore

**Comment by androidmumo** [comment]
> https://github.com/1Panel-dev/appstore

已经提交。PR: https://github.com/1Panel-dev/appstore/pull/496
同时我注意到，已经有一个用于修复此问题的类似PR: https://github.com/1Panel-dev/appstore/pull/493
我的PR与此PR的区别是，我保留了两份配置文件，一份full版，一份示例版（正如之前用ini的版本有两份配置文件一样）：
<img width="147" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/36179789/674667cb-118c-4f83-bf2d-29d34f21e4f9">

**Comment by wanghe-fit2cloud** [comment]
> > https://github.com/1Panel-dev/appstore
> 
> 已经提交。PR: [1Panel-dev/appstore#496](https://github.com/1Panel-dev/appstore/pull/496) 同时我注意到，已经有一个用于修复此问题的类似PR: [1Panel-dev/appstore#493](https://github.com/1Panel-dev/appstore/pull/493) 我的PR与此PR的区别是，我保留了两份配置文件，一份full版，一份示例版（正如之前用ini的版本有两份配置文件一样）： <img alt="image" width="147" src="https://user-images.githubusercontent.com/36179789/276050678-674667cb-118c-4f83-bf2d-29d34f21e4f9.png">

手动点赞。

**Comment by wanghe-fit2cloud** [comment]
最新版本已推送，可以点击更新按钮后使用最新版本，如下图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/f37e58cc-21c2-4113-8ea4-a7bdc91ade65)
