### ISSUE TITLE
[FEATURE] 边缘设备添加一个温度监控/展示... 毕竟都支持aarch64架构了...IoT不走一个？

### ISSUE THREAD

**Issue by gowy222** [1Panel-dev/1Panel#2584]
### 1Panel 版本

1.7

### 请描述您的需求或者改进建议

如题，边缘设备 温度 监控还是蛮重要的

### 请描述你建议的实现方案

加个判断看架构
这个作为可选项 开启，来首页 能看到CPU 内存 那边加个栏位 显示 温度。
大多开发板 都是 读取 /sys/class/thermal/thermal_zone0/temp得到温度。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在后续版本先调研一下具体实现方案。

**Comment by zhengkunwang223** [comment]
上次简单看过几个 很多硬件的温度文件位置都不一样 所以可能需要做较多的适配
当前还没有那么多设备可用
所以现阶段可能不太能上这个功能
但是这个功能确实很多人提 
后续我们买几个硬件之后再开始做

**Comment by gowy222** [comment]
> 上次简单看过几个 很多硬件的温度文件位置都不一样 所以可能需要做较多的适配 当前还没有那么多设备可用 所以现阶段可能不太能上这个功能 但是这个功能确实很多人提 后续我们买几个硬件之后再开始做

有个替补方案，让用户自己填 温度文件的路径, 毕竟 自己烧录的固件自己心里得有b数..2333333.

**Comment by wanghe-fit2cloud** [comment]
重复 #1614
