### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JoeMartini** [1Panel-dev/1Panel#2588]
### 补充信息
<img width="550" alt="Screenshot 2023-10-21 at 22 28 29" src="https://github.com/1Panel-dev/1Panel/assets/7817831/c8cc6dc9-26fb-4b66-93b7-adb2ac5a95bf">

问题 1：访问 NFS 挂在的网络存储文件夹，报错（SSH 客户端可以正常访问）

<img width="568" alt="Screenshot 2023-10-21 at 22 30 48" src="https://github.com/1Panel-dev/1Panel/assets/7817831/b0619b24-f0db-4289-b58b-a0b4020f2944">
<img width="687" alt="Screenshot 2023-10-21 at 22 31 02" src="https://github.com/1Panel-dev/1Panel/assets/7817831/c8610100-5f22-4ae7-8a0e-1c27d4aa6fa0">

问题 2：访问 NFS 目录报错之后，在访问其他目录，其他目录会被拼在路径之后，导致报“路径不存在”错误

### 联系方式

joe_martini@msn.com

### 1Panel 版本

1.71

### 问题描述

通过 NFS 挂在了局域网共享文件夹，之前一直没问题，更新到 1.70 后访问报错：
服务内部错误: lstat /mnt/tnas/private: stale NFS file handle

现在更新到 1.71，依然报错

### 重现步骤

使用 nfs-common
sudo mount -t nfs {IP}:{source path} {target path}

**Comment by wanghe-fit2cloud** [comment]
麻烦再详细描述一下上述操作，最好带上截图。

**Comment by JoeMartini** [comment]
<img width="550" alt="Screenshot 2023-10-21 at 22 28 29" src="https://github.com/1Panel-dev/1Panel/assets/7817831/c8cc6dc9-26fb-4b66-93b7-adb2ac5a95bf">

问题 1：访问 NFS 挂在的网络存储文件夹，报错（SSH 客户端可以正常访问）

<img width="568" alt="Screenshot 2023-10-21 at 22 30 48" src="https://github.com/1Panel-dev/1Panel/assets/7817831/b0619b24-f0db-4289-b58b-a0b4020f2944">
<img width="687" alt="Screenshot 2023-10-21 at 22 31 02" src="https://github.com/1Panel-dev/1Panel/assets/7817831/c8610100-5f22-4ae7-8a0e-1c27d4aa6fa0">

问题 2：访问 NFS 目录报错之后，在访问其他目录，其他目录会被拼在路径之后，导致报“路径不存在”错误

> 麻烦再详细描述一下上述操作，最好带上截图。

**Comment by wanghe-fit2cloud** [comment]
上述错误原因大概率是客户端之前挂载的 mnt 目录在没有卸载的情况下，服务器侧把这个目录移除了，才会出现这样的错误提示。

可以尝试一下这个解决办法：
在客户端 umount 一下，在重新挂载就好了。

**Comment by JoeMartini** [comment]
<img width="589" alt="Screenshot 2023-10-21 at 22 41 28" src="https://github.com/1Panel-dev/1Panel/assets/7817831/38a5d833-f6d2-4abe-89d9-26c603f44289">

 好的，我试一下，我补充一个情况，如果跳过这个目录，直接输入子目录路径，居然是可以访问的

**Comment by wanghe-fit2cloud** [comment]
> <img alt="Screenshot 2023-10-21 at 22 41 28" width="589" src="https://user-images.githubusercontent.com/7817831/277114496-38a5d833-f6d2-4abe-89d9-26c603f44289.png">
> 好的，我试一下，我补充一个情况，如果跳过这个目录，直接输入子目录路径，居然是可以访问的

好的。

**Comment by JoeMartini** [comment]
> 上述错误原因大概率是客户端之前挂载的 mnt 目录在没有卸载的情况下，服务器侧把这个目录移除了，才会出现这样的错误提示。
> 
> 可以尝试一下这个解决办法： 在客户端 umount 一下，在重新挂载就好了。

我看了一下我之前的挂载方式，这个目录的子目录是挂载的，这个目录本身不是
