### ISSUE TITLE
[BUG]添加阿里云 mysql for Serverless 数据库无法扫描已有数据库

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [1Panel-dev/1Panel#2589]
### 联系方式

x123456789fy@outlook.com

### 1Panel 版本

v1.7.1

### 问题描述

服务内部错误: sync db from remote server failed, err: create user failed Error 1044 (42000): Access denied for user '*************'@'%' to database '__recycle_bin__'

### 重现步骤

1. 添加阿里云 mysql for Serverless 数据库,使用管理员账号
2. 点击从服务器获取按钮
3. 顶部弹出权限不足提示

**Comment by ssongliu** [comment]
感谢反馈！1.8 版本修复这个问题。

**Comment by wanghe-fit2cloud** [comment]
v1.7.2 版本已发布。
