### ISSUE TITLE
[FEATURE]nodejs环境相关

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [1Panel-dev/1Panel#2590]
### 1Panel 版本

v1.7.1

### 请描述您的需求或者改进建议

只能自动探测启动命令有些过于武断,希望能自定义启动命令

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述需求我们计划在 v1.8.0 版本支持。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
