### ISSUE TITLE
[FEATURE]创建容器当Entrypoint为空时使用镜像默认的Entrypoint启动

### ISSUE THREAD

**Issue by wc7086** [1Panel-dev/1Panel#2593]
### 1Panel 版本

1.7.1

### 请描述您的需求或者改进建议

一些容器使用 ENTRYPOINT 拉起容器内的服务，如果默认为空会导致一些容器的服务启动失败。

目前镜像为空时就会使用空 ENTRYPOINT 启动，这会导致一些没有在说明页给出 ENTRYPOINT 的镜像需要自行去看 Dockerfile ，获得 ENTRYPOINT 并填入可视化界面的 `Entrypoint` 选项中才能正常启动容器。

### 请描述你建议的实现方案

创建容器当 ENTRYPOINT 为空时使用镜像默认的 ENTRYPOINT 启动

系统版本：`Debian 12`和`Archlinux`

**Comment by wanghe-fit2cloud** [comment]
> 创建容器当Entrypoint为空时使用镜像默认的Entrypoint启动

感谢反馈。
麻烦再详细讲一下上述内容，目前不是很清楚。

> 因为在创建容器时，任何命令行参数都会被附加到ENTRYPOINT命令后，并覆盖原有CMD指令。

**Comment by wc7086** [comment]
> 感谢反馈。 麻烦再详细讲一下上述内容，目前不是很清楚。

![image](https://github.com/1Panel-dev/1Panel/assets/74053663/c81366fc-6aa9-46e5-acb0-ed1aa7100b42)

一些容器使用 ENTRYPOINT 拉起容器内的服务，如果默认为空会导致一些容器的服务启动失败。

[ENTRYPOINT 入口点 · Docker 从入门到实践](https://docker-practice.github.io/zh-cn/image/dockerfile/entrypoint.html)

**Comment by ssongliu** [comment]
> > 感谢反馈。 麻烦再详细讲一下上述内容，目前不是很清楚。
> 
> ![image](https://user-images.githubusercontent.com/74053663/276215983-c81366fc-6aa9-46e5-acb0-ed1aa7100b42.png)
> 
> 一些容器使用 ENTRYPOINT 拉起容器内的服务，如果默认为空会导致一些容器的服务启动失败。
> 
> [ENTRYPOINT 入口点 · Docker 从入门到实践](https://docker-practice.github.io/zh-cn/image/dockerfile/entrypoint.html)


我们尝试在开发环境创建了一个 nginx 容器，默认不带任何 ENTRYPOINT 参数，创建完成之后，是会添加上默认的 /docker-entrypoint.sh 。
这里是否有具体的容器可以提供测试呢，

**Comment by wc7086** [comment]
> 这里是否有具体的容器可以提供测试呢

https://hub.docker.com/layers/containrrr/watchtower/latest/images/sha256-5dec6922bb70c19c3a71f2b2758d9e3ccbdd28d3420dc8df45ea2f1eddab2d1a?context=explore

![image](https://github.com/1Panel-dev/1Panel/assets/74053663/12a7a2d1-89f9-48b7-b71a-a4eb0cf7434d)

![image](https://github.com/1Panel-dev/1Panel/assets/74053663/ea554843-3c7e-4d76-a575-a0064fbe2fef)

**Comment by ssongliu** [comment]
如图测试创建的话，是会默认给上 Entrypoint 的，根据容器日志，创建失败的原因应该是 command 输入不正确
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/d644cef4-2a8f-4b8a-8c0a-67c9a8cc39bb)

**Comment by wc7086** [comment]
@ssongliu 测试使用的是目前发布的1.7.1吗？如果是 master 分支最新 commit，也许是这个bug已经被修复了。

我在 command 输入框中填入以下三种形式的命令都无法正确启动，且命令错误的提示是以`-c`开头，我认为这足以表明是`Entrypoint`未被自动识别导致的问题。

`'-c' '--schedule' '0 0 3 * * *'`
`'-c --schedule' '0 0 3 * * *'`
`'-c --schedule ' '0 0 3 * * *'`

**Comment by ssongliu** [comment]
是使用的 1.7.1 版本，通过这种方式可以创建成功，不需要输入 Entrypoint
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/8627728e-dcd4-4170-9886-531cf652758f)

![image](https://github.com/1Panel-dev/1Panel/assets/73214554/8ac78647-5417-46a6-bac7-c62736cb2e2e)

**Comment by wc7086** [comment]
这是在刚刚按照的全新的 archlinux 中使用这条命令安装的 1Panel 测试的，在 Debian 12 中也一样
`curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sudo bash quick_start.sh`

图1是从开始到错误的全过程。
图2是在图1的基础上在 Entrypoint 输入框手动加上 `/watchtower` 后启动，可以表明我的其他输入没有错误。

图1
![图1](https://github.com/1Panel-dev/1Panel/assets/74053663/efb8cb2b-24c1-4313-8381-1b9a723dffa6)

图2
![图2](https://github.com/1Panel-dev/1Panel/assets/74053663/c17d4137-2936-4347-a76e-fc805faa6e8f)

**Comment by wc7086** [comment]
1.7.2在Debian 12中仍然存在此问题

**Comment by wc7086** [comment]
#2641
#2638

**Comment by wanghe-fit2cloud** [comment]
v1.7.3 版本已发布。
