### ISSUE TITLE
[FEATURE]在安全入口错误情况下不显示提示页面

### ISSUE THREAD

**Issue by Any998** [1Panel-dev/1Panel#2594]
### 1Panel 版本

v1.7.1

### 请描述您的需求或者改进建议

1.在错误情况下不显示提示

### 附加信息

![1697619837997](https://github.com/1Panel-dev/1Panel/assets/148327862/cd4466a7-fdeb-45e2-86f9-a27b22fd679f)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wc7086** [comment]
#723

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
