### ISSUE TITLE
[SECURITY]提供安装包哈希值或签名

### ISSUE THREAD

**Issue by wc7086** [1Panel-dev/1Panel#2597]
### 1Panel 版本

1.7.1

### 请描述您的需求或者改进建议

提供安装包 hash 值或签名，以避免安装包被篡改

### 请描述你建议的实现方案

1. 在官网和 GitHub Release 展示安装包的哈希值或签名
2. 在 GitHub Release 中提供 `.sha256` 文件，Linux 下使用 `sha256sum file.tar > file.tar.sha256` 生成

### 附加信息

#723

**Comment by wc7086** [comment]
#723

**Comment by wanghe-fit2cloud** [comment]
目前 1Panel 安装包是在阿里 OSS，我们都有提供哈希文件。
> 后续版本会考虑将哈希文件放到 GitHub release 展示。

**Comment by wc7086** [comment]
> 目前 1Panel 安装包是在阿里 OSS，我们都有提供哈希文件。

哈希文件后缀是啥

**Comment by wanghe-fit2cloud** [comment]
> > 目前 1Panel 安装包是在阿里 OSS，我们都有提供哈希文件。
> 
> 哈希文件后缀是啥

目前没有对外提供该文件，下个功能版本开始会同步 release 到 github。
