### ISSUE TITLE
[FEATURE] 后台登录要求输入验证码（可选项）

### ISSUE THREAD

**Issue by wc7086** [1Panel-dev/1Panel#2598]
### 1Panel 版本

1.7.1

### 请描述您的需求或者改进建议

后台安全功能提供验证码选项，用户登陆时要求输入验证码

### 请描述你建议的实现方案

可使用 `turnstile`

相关文档：https://developers.cloudflare.com/turnstile/

### 附加信息

#723

**Comment by wc7086** [comment]
#723

**Comment by wanghe-fit2cloud** [comment]
目前，在输入用户名密码错误的情况下，是会要求用户输入验证码的。
> 如果是必须要求输入验证码，我们可能会在后续版本考虑支持。
