### ISSUE TITLE
不小心删除了面板里的所有端口，无法登录面板也无法使用22端口ssh

### ISSUE THREAD

**Issue by kevon2019** [1Panel-dev/1Panel#2600]
### 请描述您的问题

不小心删除了面板里的所有端口，无法登录面板也无法使用22端口ssh要咋办，救救孩子吧

**Comment by wanghe-fit2cloud** [comment]
目前还有办法直接进入服务器通过命令来手动放行端口吗？

**Comment by kevon2019** [comment]
> 目前还有办法直接进入服务器通过命令来手动放行端口吗？

对的，22用不了了，又不想重装系统和面板，内容太多了

**Comment by wanghe-fit2cloud** [comment]
> > 目前还有办法直接进入服务器通过命令来手动放行端口吗？
> 
> 对的，22用不了了，又不想重装系统和面板，内容太多了

如果不能想办法进去服务器，这就有些难办了。

**Comment by VMCoud** [comment]
VNC
