### ISSUE TITLE
[FEATURE]PHP扩展配置form优化

### ISSUE THREAD

**Issue by bh1xaq** [1Panel-dev/1Panel#2601]
### 1Panel 版本

1.6.2

### 请描述您的需求或者改进建议

下拉选择很不方便，如果我有一个固定的扩展列表，每次建环境，复制粘贴就很麻烦。显示会不正常。

![image](https://github.com/1Panel-dev/1Panel/assets/16686956/da71b52e-7acc-4dd4-b501-36188005faf6)

例如

![image](https://github.com/1Panel-dev/1Panel/assets/16686956/68d919ad-821a-46ba-8800-1e05e1141d09)

### 请描述你建议的实现方案

换成 textarea 就行，空格或者英文半角逗号分隔。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本完成上述优化。

**Comment by wanghe-fit2cloud** [comment]
PHP扩展相关需求的讨论，统一汇总到该 issue #1636
