### ISSUE TITLE
[QUESTION] 如何重置密码（非查看密码）

### ISSUE THREAD

**Issue by lzc256** [1Panel-dev/1Panel#2602]
### 请描述您的问题

因为觉得 2FA 安全性已经足够，在面板中把密码设置为了六个空格，然后才发现在登录页面无法输入空格，导致无法登录面板

命令行工具未提供重置密码功能。请问如何重置密码？谢谢！

**Comment by ssongliu** [comment]
感谢反馈！暂时还没办法直接通过命令行重置密码。
1. 如果升级不久的话，可以通过 1pctl restore 回滚到升级前的版本，但是会丢失升级后产生的数据；
2. 或者有条件的话，可以直接修改数据库文件 /opt/1panel/db/1Panel.db 中的 settings 表；
3. 或者可以扫描下面二维码加入社区群，联系工作人员远程解决一下。
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/5bcc3a39-2a2c-40f6-a0e4-3d1b92eb236a)


下个版本会优化一下面板设置的密码输入，禁止输入空格。

**Comment by lzc256** [comment]
请问可以详细说一下如何修改settings表吗？谢谢！

**Comment by ssongliu** [comment]
1. 找到 settings 表里面的 EncryptKey 行，这是我们用来加密的盐随机串；
2. 通过随机串生成临时密码，可以直接发 EncryptKey 我帮你生成，或者直接用源码里面的 backend/utils/encrypt/encrypt_test.go 方法进行加密，得到加密临时密码串；
3. 将临时密码串复制到 settings 表的 Password 行中；
4. 重启服务 1pctl restart。

**Comment by ssongliu** [comment]
1. 需要准备两个 db 文件：
    /opt/1panel/db/1Panel.db 当前数据库文件
    /opt/1panel/tmp/upgrade/upgrade_xxxx/original/1Panel.db 升级备份的数据库文件
2. 两个都通过 navicat 打开，然后将升级备份的数据库文件中 settings 表的 Password value 复制到当前数据库的相同位置。
3. 关闭 navicat 当前数据库连接，然后将当前数据库替换 /opt/1panel/db/1Panel.db
4. 1pctl restart 即可

操作过程中记得留好备份，重启后可通过 1pctl user-info 查看登陆信息。

**Comment by wanghe-fit2cloud** [comment]
v1.7.2 版本已发布。
