### ISSUE TITLE
[FEATURE] [非必要] 部分需要手动输入的地方是否可以提供复制功能

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#2603]
### 1Panel 版本

最新

### 请描述您的需求或者改进建议

感觉复制 粘贴，要比自己手动方便
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/37c8d70e-e2a7-41ad-8eb1-d4fd4b062d6f)
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/5a0e468b-337f-4786-bfbf-51ca2d75910b)

### 请描述你建议的实现方案

可以加个复制按钮， 或者双击文字直接 复制

**Comment by wanghe-fit2cloud** [comment]
我们应该不会支持上述需求，望理解。
> 后续版本可能会禁止输入框粘贴操作，目的是为了防止误删等操作。
