### ISSUE TITLE
[QUESTION] 我更改了"data-root"到我挂载的一个硬盘后，所有应用可以正常安装但是全部无法访问

### ISSUE THREAD

**Issue by Lynricsy** [1Panel-dev/1Panel#2609]
### 请描述您的问题

我更改了"data-root"到我挂载的一个硬盘后，所有应用可以正常安装但是全部无法访问，权限设置应该是没有问题的
<img width="360" alt="709c8904605506bc490aacd77957ec0" src="https://github.com/1Panel-dev/1Panel/assets/62173814/02eb362d-0002-420e-8382-033f952c7505">

**Comment by wanghe-fit2cloud** [comment]
可以到 `容器` 列表看一下容器状态和日志是否都正常。

> 安装应用时要选择端口对外暴露，还要确保端口已经放行 防火墙、安全组。

**Comment by wanghe-fit2cloud** [comment]
还可以手动通过命令创建一个 nginx 容器，对外暴露端口后，测试看是否可以正常访问。
可以参考如下命令：
```shell
docker run -ti -d -p 8080:80 nginx
```
测试一下浏览器访问 8080 端口是否正常。

如果还有问题，再在这个 issue 中继续讨论。
