### ISSUE TITLE
离线安装包

### ISSUE THREAD

**Issue by 172151295** [1Panel-dev/1Panel#261]
### 请描述您的问题

需要在离线环境安装，提供一下离线包

**Comment by wanghe-fit2cloud** [comment]
目前只提供在线安装脚本。
在离线环境下，个人建站、应用商店等核心功能是不能正常使用的。

**Comment by BlueSkyXN** [comment]
> 目前只提供在线安装脚本。 在离线环境下，个人建站、应用商店等核心功能是不能正常使用的。

可提供手动镜像应用商店/其他方式的手动安装，实现内网可用吗

**Comment by wanghe-fit2cloud** [comment]
> > 目前只提供在线安装脚本。 在离线环境下，个人建站、应用商店等核心功能是不能正常使用的。
> 
> 可提供手动镜像应用商店/其他方式的手动安装，实现内网可用吗

若是维护一个内网的镜像仓库，是可以解决应用在内网部署的问题的。
但网站申请证书等功能还是不能在内网环境中正常运行的。

**Comment by maninhill** [comment]
短期暂时不考虑离线安装。
