### ISSUE TITLE
[BUG] 添加 OneDrive 账号时提示 no such access token in response

### ISSUE THREAD

**Issue by 3DMXM** [1Panel-dev/1Panel#2610]
### 1Panel 版本

v1.7.1

### 问题描述

创建备份账号-》onedrive 账号 的时候，提示 “no such access token in response”
![20231020141830](https://github.com/1Panel-dev/1Panel/assets/28587093/6762d7ef-dab9-4f9e-8054-20ee4b13cd59)

### 重现步骤

1. 打开面板设置
2. 备份账号
3. 微软 OneDrive
4. 添加 微软 OneDrive
5. 点击获取，登录onedrive账号
6. 复制授权后返回的 code
7. 粘贴到 授权码 里面
8. 然后点确认

**Comment by ssongliu** [comment]
感谢反馈！可以细看一下第六步的返回信息，复制的 code 后面是否还有其他信息，比如说&session_state=xxx，那部分不需要复制

**Comment by 3DMXM** [comment]
> 感谢反馈！可以细看一下第六步的返回信息，复制的 code 后面是否还有其他信息，比如说&session_state=xxx，那部分不需要复制

感谢，解决了，我觉得，可以直接用 [URLSearchParams](https://developer.mozilla.org/zh-CN/docs/Web/API/URLSearchParams) 来处理这些参数

**Comment by ssongliu** [comment]
> > 感谢反馈！可以细看一下第六步的返回信息，复制的 code 后面是否还有其他信息，比如说&session_state=xxx，那部分不需要复制
> 
> 感谢，解决了，我觉得，可以直接用 [URLSearchParams](https://developer.mozilla.org/zh-CN/docs/Web/API/URLSearchParams) 来处理这些参数

嗯，1.8 版本这块会优化一下，加上校验。

**Comment by wanghe-fit2cloud** [comment]
v1.7.2 版本已发布。
