### ISSUE TITLE
[FEATURE]打包压缩文件的文件名，建议采用 当前网站域名或当前文件夹名 加上 随机字符 的格式

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#2611]
### 1Panel 版本

v1.7.1

### 请描述您的需求或者改进建议

打包压缩文件的文件名，建议采用 当前网站域名或当前文件夹名 加上 随机字符 的格式

例如：当前网站域名为 github.com 或当前文件夹名为 github.com 打包的文件名，则默认为 github.com_随机字符.zip

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，当前版本在压缩操作时支持自定义压缩文件名称，并支持选择是否覆盖原文件。
