### ISSUE TITLE
[FEATURE]强烈建议出Python的web运行环境的部署!

### ISSUE THREAD

**Issue by jiayouzl** [1Panel-dev/1Panel#2618]
### 1Panel 版本

1.70

### 请描述您的需求或者改进建议

Python的Django,flask,fastapi等等web框架都非常不错,用的人也多,虽然BT有但不太敢用那玩意.

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持 Python 运行环境的。

**Comment by wanghe-fit2cloud** [comment]
重复 #423
