### ISSUE TITLE
[BUG]进程守护无法正常启动 can't find command 

### ISSUE THREAD

**Issue by 7836246** [1Panel-dev/1Panel#2619]
### 联系方式

go7836246@gmail.com

### 1Panel 版本

v1.7.1

### 问题描述

can't find command 
无法正常使用进程守护启动应用
我手动运行是可以的

### 重现步骤

正常填写参数 无法启动 

发行版本 debian-12.1
--
内核版本 6.1.0-10-amd64
系统类型 x86_64

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦提供一下具体的操作系统版本等信息：
```shell
cat /etc/os-release
```

**Comment by 7836246** [comment]
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by wanghe-fit2cloud** [comment]
> PRETTY_NAME="Debian GNU/Linux 12 (bookworm)" NAME="Debian GNU/Linux" VERSION_ID="12" VERSION="12 (bookworm)" VERSION_CODENAME=bookworm ID=debian HOME_URL="https://www.debian.org/" SUPPORT_URL="https://www.debian.org/support" BUG_REPORT_URL="https://bugs.debian.org/"

收到，接下来会适配 Debian 12。

**Comment by tsaoshuang** [comment]
> > PRETTY_NAME="Debian GNU/Linux 12 (bookworm)" NAME="Debian GNU/Linux" VERSION_ID="12" VERSION="12 (bookworm)" VERSION_CODENAME=bookworm ID=debian HOME_URL="https://www.debian.org/" SUPPORT_URL="https://www.debian.org/support" BUG_REPORT_URL="https://bugs.debian.org/"
> 
> 收到，接下来会适配 Debian 12。

原来是不适配Debian12啊  我弄了一下午都启动不了

**Comment by zhengkunwang223** [comment]
您好 经过我们测试 没有复现这个问题
如果手动可以 你可以对比一下配置文件的区别
