### ISSUE TITLE
[BUG]数据库修改端口出现错误

### ISSUE THREAD

**Issue by youzhazhu** [1Panel-dev/1Panel#2621]
### 1Panel 版本

v1.7.1

### 问题描述

我安装了多个数据库。
当我修改数据库"mysql57"的端口时，结果“mysql”数据库的端口变了，而“mysql57”数据库不变。
尝试多次都是这样，我怀疑是面板BUG。

### 重现步骤

1.安装MySQL8.1.0，并命名为“mysql81”，端口设置为3306。
2.安装MySQL5.7.43，并命名为“mysql57”，端口设置为3307。
3.左侧栏-数据库-选择MySQL57，点击设置-端口。
可以看到此时面板显示的是”mysql57 设置“无疑。
4.将端口设置为3357，点击保存，立即重启。
5.结果mysql57的端口并没有改变，而mysql81的端口变成了3357。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.7.3 版本已发布。
