### ISSUE TITLE
[BUG]Docker创建容器报错

### ISSUE THREAD

**Issue by linlin6688** [1Panel-dev/1Panel#2622]
### 1Panel 版本

1.71

### 问题描述

服务器系统：centos-7.9.2009
内核版本 3.10.0-1160.el7.x86_64
系统类型 x86_64
Docker版本：24.0.6

### 重现步骤

使用终端创建容器一切正常，1Panel也能正常显示，但是在1Panel界面创建容器，报错    服务内部错误: Error response from daemon: No command specified。
无论是手动导入的镜像还是仓库拉取的镜像，都是一样的问题。

![屏幕截图(1)](https://github.com/1Panel-dev/1Panel/assets/46083932/8c38422d-f287-463e-8aae-4574357e3459)

**Comment by ssongliu** [comment]
感谢反馈！在开发环境没有复现这个问题。
1. 请确认一下右下角的版本是 1.7.1 ；
2. 可以简单的创建一个 nginx 容器试试，镜像直接写 nginx，其他都不用改，然后直接创建看看会不会报错。

**Comment by wanghe-fit2cloud** [comment]
v1.7.3 版本已发布。
