### ISSUE TITLE
[BUG]E5账户的授权码无法通过 OneDrive 授权码增加的格式校验 

### ISSUE THREAD

**Issue by black-zero358** [1Panel-dev/1Panel#2626]
### 1Panel 版本

1.7.2

### 问题描述

E5账户的授权码无法通过 OneDrive 授权码增加的格式校验 : `^[A-Za-z0-9_.-]{32,60}$`

下面提供一个E5账户的授权码示例
0.AVUAHhwL-yYidEq5GPK845Aasdk1CQGpGlRIodxuRf5ijGuIAGE.AgABAAIAAAAtyolDdddQQ5VtlI4uGjEPAgDs_wUA9P_Fai_m1zdC2ohYJMhbnEv1234C80bxmno3oEiyOq35zca_SSPlwros_i2w4BAyiTKJCr4vF2FWBh3xZJjVioQk4_AQ4-i3H55zcwju_M16wvRM9ULmVqm9UgpHpZ_5Y17mqTsWZpjt0Yv4gnTEUjEew6tfn4HwdAhts7EyQm6EualrviItVXLqGVP4RratS_n-XRG1dMLbS2wj2O4nZXU55ccixKADP1tnXCDoIlhTJJmIEouonlj9-rGeE_nNjPoHLydGYLm2ZJdQQFH7r3pmM0nNEqBDGHlytPLAz9vSlk8cjScdWm66GL5SO-teFaskhg-uf0SrjMmXu1rMQActp-RKrDUas-JLFO2mZ5MRsss6pcbO2KxtR3yLGiprR-Yi6bIOLhhqxvGEE3QCMxaxMWbLy_8TedCFJ-pPwO_WWoo3cF0c5XVhTMyLsN-xoJvH-vB8lFacbtS0IVUuOSCQ51Ou0MFT46aMAu8TrjN858HYIHqc2eFimRjZ25Oqxp5s_o25xi7OBNEKKBxS64UGTw_MZuo-GDT3rV2jaSYFM00mcvjQbpFX-dZwQu0FR4hjfgfdIYqkv7QEuOAOUv5DhTlLfB3ffXLJbdpJxVJyDaut_HVzCUShzbKULToasdrgdbRl5LwsFQp8v9pqofG5Mx_AW9r-57Vdsj1AXuWSnR2ERIDi42rUsderytAu5pK_xibkM2ba9vvgpQDnM

### 重现步骤

E5账户的授权码无法通过 OneDrive 授权码增加的格式校验 : `^[A-Za-z0-9_.-]{32,60}$`

下面提供一个E5账户的授权码示例
0.AVUAHhwL-yYidEq5GPK845Aasdk1CQGpGlRIodxuRf5ijGuIAGE.AgABAAIAAAAtyolDdddQQ5VtlI4uGjEPAgDs_wUA9P_Fai_m1zdC2ohYJMhbnEv1234C80bxmno3oEiyOq35zca_SSPlwros_i2w4BAyiTKJCr4vF2FWBh3xZJjVioQk4_AQ4-i3H55zcwju_M16wvRM9ULmVqm9UgpHpZ_5Y17mqTsWZpjt0Yv4gnTEUjEew6tfn4HwdAhts7EyQm6EualrviItVXLqGVP4RratS_n-XRG1dMLbS2wj2O4nZXU55ccixKADP1tnXCDoIlhTJJmIEouonlj9-rGeE_nNjPoHLydGYLm2ZJdQQFH7r3pmM0nNEqBDGHlytPLAz9vSlk8cjScdWm66GL5SO-teFaskhg-uf0SrjMmXu1rMQActp-RKrDUas-JLFO2mZ5MRsss6pcbO2KxtR3yLGiprR-Yi6bIOLhhqxvGEE3QCMxaxMWbLy_8TedCFJ-pPwO_WWoo3cF0c5XVhTMyLsN-xoJvH-vB8lFacbtS0IVUuOSCQ51Ou0MFT46aMAu8TrjN858HYIHqc2eFimRjZ25Oqxp5s_o25xi7OBNEKKBxS64UGTw_MZuo-GDT3rV2jaSYFM00mcvjQbpFX-dZwQu0FR4hjfgfdIYqkv7QEuOAOUv5DhTlLfB3ffXLJbdpJxVJyDaut_HVzCUShzbKULToasdrgdbRl5LwsFQp8v9pqofG5Mx_AW9r-57Vdsj1AXuWSnR2ERIDi42rUsderytAu5pK_xibkM2ba9vvgpQDnM

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦提供一下你的 E5 账号下获取到的授权码长度，我们来优化一下正则表达式。

**Comment by black-zero358** [comment]
> 感谢反馈，麻烦提供一下你的 E5 账号下获取到的授权码长度，我们来优化一下正则表达式。

817

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈，麻烦提供一下你的 E5 账号下获取到的授权码长度，我们来优化一下正则表达式。
> 
> 817

收到。

**Comment by wanghe-fit2cloud** [comment]
v1.7.3 版本已发布。
