### ISSUE TITLE
主机 -> 文件 解压出错[BUG]

### ISSUE THREAD

**Issue by yikwongee** [1Panel-dev/1Panel#263]
### 1Panel 版本

1.0.1

### 问题描述

服务内部错误: handling file 2: data/zqoo/backup/demo.txt: flate: corrupt input before offset 1
首先文件没任何问题，都正常打开
不管压缩包带不带密码，都解压出错，但是使用linux的unzip或电脑解压没任何问题

还有一个功能需求：
1、就是在这里增加一个删除，如果要批量删除就会很费劲
2、能否把压缩和解压一起放到上面
![image](https://user-images.githubusercontent.com/77314844/225657888-f32ac5fd-fff6-4932-954a-f4f439739685.png)

### 重现步骤

该压缩包压缩代码https://zhang.ge/5117.html

**Comment by zyyfit** [comment]
您好，方便把您的压缩文件上传一下吗？我们这边解压带密码的文件确实报错了，但是解压不带密码的没有报错，压缩文件是根据您发的 https://zhang.ge/5117.html 这个地址，先mysqldump了一个sql文件，然后用 zip -m 命令进行的压缩

**Comment by yikwongee** [comment]
压缩包没办法上传，里面有数据

备份的数据大致是.sh、.txt、.zip、.yml、还有就是vaultwarden这个密码管理的一些数据

**Comment by yikwongee** [comment]
能不能在加个回收站，总会有些时候会出现误删除的操作

**Comment by wanghe-fit2cloud** [comment]
> 能不能在加个回收站，总会有些时候会出现误删除的操作

后续版本，我们有计划增加文件回收站功能。

**Comment by zyyfit** [comment]
批量删除功能已增加，回收站功能已增加

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
