### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gaoshq7** [1Panel-dev/1Panel#2631]
### 联系方式

yashiro_2022@163.com

### 1Panel 版本

v1.7.1

### 问题描述

由于无法连接公网，所以想通过remote模式下联网的应用商店制作一些常用到的本地app服务。
当在制作mysql本地服务后测试还原备份功能时遇到了该bug：功能界面上一切正常，但docker
中本该还原的mysql服务实例却不存在。

### 重现步骤

1. 在remote模式下的应用商店里面获取到mysql的app安装配置文件。
2. 将上一步获取到的文件放到“/opt/1panel/resource/apps/local”下面。
3. 重启1panel并顺利创建出mysql服务实例且创建一个mysql备份。
4. 还原改备份到mysql服务实例上。
5. web界面上显示mysql服务正常运行。
6. 实际docker中不存在还原备份后的mysql服务实例。

### 期待的正确结果

正常实现mysql的备份功能

### 相关日志输出

```shell
通过部分源码的阅读大概可以了解该bug的主要原因是：本地服务在安装目录中生成app配置文件的模式和remote模式下不同（也许是为了在混合安装模式下区分local服务和remote服务而设计的），但是备份还原策略不管是local模式还是remote模式，使用的都是同一套逻辑，这套逻辑不适用于local模式，所以产生该bug。不清楚在制作其它本地服务的时候是不是也会出现这个备份还原失败的问题，希望修改一下。
```

### 附加信息

谢谢。

**Comment by zhengkunwang223** [comment]
感谢反馈 我们在本地环境复现一下

**Comment by zhengkunwang223** [comment]
您好 经过我们的讨论 当前暂时不支持此种操作 
如果需要迁移 1Panel 请使用 1Panel 的快照功能
