### ISSUE TITLE
[FEATURE]网站管理里的搜索功能优化建议

### ISSUE THREAD

**Issue by xu5343** [1Panel-dev/1Panel#2632]
### 1Panel 版本

v1.5.5

### 请描述您的需求或者改进建议

网站管理里的搜索功能，搜索不到子域名，例如：增加网站时提示域名已经存在，但搜索区搜索不到该域名在哪个网站里增加过了，希望可以优化这个功能，不然只能一个个网站点里翻找了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本完成上述优化。

**Comment by zhengkunwang223** [comment]
v1.8.0 版本优化了提示消息 增加了域名在哪个网站填加的提示

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
