### ISSUE TITLE
[FEATURE]批量增加多个域名建议

### ISSUE THREAD

**Issue by xu5343** [1Panel-dev/1Panel#2633]
### 1Panel 版本

v1.5.5

### 请描述您的需求或者改进建议

网站里增加域名，目前只能一个个增加，希望可以批量增加多个域名，比如一行一个方式。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
