### ISSUE TITLE
[FEATURE]域名可以重复增加问题

### ISSUE THREAD

**Issue by xu5343** [1Panel-dev/1Panel#2636]
### 1Panel 版本

v1.5.5

### 请描述您的需求或者改进建议

在使用中发现，
别的站点已经增加过的域名，其他站点里也可以再次增加该域名，也没有任何提示，这样出现会重复问题，或者站点里已经增加过的域名，同样可以多次再次增加相同的域名，而且也没有任何提示，希望可以修复这些问题

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
