### ISSUE TITLE
[BUG]网站设置勾选了“TLS 1.3”并不生效

### ISSUE THREAD

**Issue by 404gods** [1Panel-dev/1Panel#2639]
### 1Panel 版本

1.7.2

### 问题描述

网站设置——HTTPS——SSL 协议设置——勾选了“TLS 1.3”，但网页查看实际连接还是tls1.2，OpenResty配置文件如下：
server {
    listen 80 ; 
    listen 443 ssl http2 ; 
    server_name www.test.com; 
    index index.php index.html index.htm default.php default.htm default.html; 
    proxy_set_header Host $host; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header X-Forwarded-Host $server_name; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_http_version 1.1; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    access_log /www/sites/www.test.com/log/access.log; 
    error_log /www/sites/www.test.com/log/error.log; 
    access_by_lua_file /www/common/waf/access.lua; 
    set $RulePath /www/sites/www.test.com/waf/rules; 
    set $logdir /www/sites/www.test.com/log; 
    set $redirect on; 
    set $attackLog on; 
    set $CCDeny off; 
    set $urlWhiteAllow off; 
    set $urlBlockDeny off; 
    set $argsDeny off; 
    set $postDeny off; 
    set $cookieDeny off; 
    set $fileExtDeny off; 
    set $ipBlockDeny off; 
    set $ipWhiteAllow off; 
    location ^~ /.well-known/acme-challenge {
        allow all; 
        root /usr/share/nginx/html; 
    }
    include /www/sites/www.test.com/proxy/*.conf; 
    if ($scheme = http) {
        return 301 https://$host$request_uri; 
    }
    ssl_certificate /www/sites/www.test.com/ssl/fullchain.pem; 
    ssl_certificate_key /www/sites/www.test.com/ssl/privkey.pem; 
    ssl_protocols TLSv1.2 TLSv1.1 TLSv1 TLSv1.3; 
    ssl_ciphers EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5; 
    ssl_prefer_server_ciphers on; 
    ssl_session_cache shared:SSL:10m; 
    ssl_session_timeout 10m; 
    add_header Strict-Transport-Security "max-age=31536000"; 
    error_page 497 https://$host$request_uri; 
    proxy_set_header X-Forwarded-Proto https; 
    ssl_stapling on; 

### 重现步骤

网站设置——HTTPS——SSL 协议设置——勾选了“TLS 1.3”，但网页查看实际连接还是tls1.2

### 期待的正确结果

TLS 1.3生效

**Comment by zhengkunwang223** [comment]
您好 感谢反馈 
当前已复现问题 
具体解决方案 https://bbs.fit2cloud.com/t/topic/1923

**Comment by 404gods** [comment]
现在可以了

**Comment by wanghe-fit2cloud** [comment]
v1.7.3 版本已发布。

**Comment by 404gods** [comment]
> v1.7.3 版本已发布。

那我按上面修改了conf/conf.d 目录下的 00.default.conf 文件，要不要改回来？

**Comment by zhengkunwang223** [comment]
> > v1.7.3 版本已发布。
> 
> 那我按上面修改了conf/conf.d 目录下的 00.default.conf 文件，要不要改回来？

不用
