### ISSUE TITLE
[FEATURE]添加自动屏蔽ip规则

### ISSUE THREAD

**Issue by lchjczw** [1Panel-dev/1Panel#2645]
### 1Panel 版本

v1.7.1

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/12480676/56f64a44-88b8-48ee-bb8f-80b490a342dd)

添加自动屏蔽ip规则

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑是否支持上述需求。

**Comment by lchjczw** [comment]
这个有进度吗？登录爆破的太多了

**Comment by lchjczw** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/12480676/91ecb659-a001-4171-bd08-a8ab2f53e228)

最好能自动及时屏蔽掉，不然这个都不安全，没法放心使用呢

**Comment by wanghe-fit2cloud** [comment]
参考 issue:  #1746 给服务器增加安全措施

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
