### ISSUE TITLE
[FEATURE]希望能增加针对磁盘的相关功能。

### ISSUE THREAD

**Issue by gaoshq7** [1Panel-dev/1Panel#2646]
### 1Panel 版本

v1.7.2

### 请描述您的需求或者改进建议

希望能增加针对磁盘的相关功能。

### 请描述你建议的实现方案

比如可以添加：
1. 磁盘格式化、自动挂载功能
2. 磁盘umount功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
磁盘相关需求的讨论，统一汇总到该 issue #1852
