### ISSUE TITLE
计划任务，备份已经存在的数据库

### ISSUE THREAD

**Issue by xieyuhua** [1Panel-dev/1Panel#2647]
如何备份其他已经使用的数据?

**Comment by wanghe-fit2cloud** [comment]
可以将 MySQL 数据库添加为远程服务器，之后再来尝试备份。
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/3d51199a-ff8e-4088-99dd-933520015d12)

**Comment by xieyuhua** [comment]
我尝试了的，这个必须是新建数据库，但是已经在使用的数据库如何添加?

**Comment by wanghe-fit2cloud** [comment]
标红的按钮，就是针对已经存在的 MySQL 数据库。
> 远程数据库添加成功后，点击 `从服务器获取` 按钮同步已经存在的数据。

**Comment by xieyuhua** [comment]
我的意思是比如我想备份远程数据库，ksam库里面的所有表。

但是你说的地方连接就是新建一个db库，再备份db库，不能选择已经存在的ksam库进行备份。

**Comment by wanghe-fit2cloud** [comment]
是添加远程 MySQL 服务，怎么会是添加库呢？
见下图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/20f93b46-12eb-45ef-a99c-62f1d71d1d17)
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/92e26283-0b67-40cc-8b9d-904bc15e5989)

**Comment by xieyuhua** [comment]
同步获取过，没有同步存在的DB，😂😂😂

**Comment by wanghe-fit2cloud** [comment]
> 同步获取过，没有同步存在的DB，😂😂😂

进入日志审计菜单，查看下系统日志，看有没有同步失败的日志：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/966984c1-f1e4-481d-bbd6-0ad65874dce3)

**Comment by ssongliu** [comment]
> 同步获取过，没有同步存在的DB，😂😂😂

select schema_name, default_character_set_name from information_schema.SCHEMATA;

执行这个命令看一下。

**Comment by xieyuhua** [comment]
找到原因了，我刚刚开始新建了一个DB在使用，然后我再去点击同步现有的，所以同步失败，要先获取，再创建就可以了。😂
