### ISSUE TITLE
[FEATURE]1panel使用redis

### ISSUE THREAD

**Issue by QAQ5555** [1Panel-dev/1Panel#2649]
### 1Panel 版本

1.7.3

### 请描述您的需求或者改进建议

1panel使用redis持久化登录信息来保持更新完成后无需重新登陆和锁表问题

### 请描述你建议的实现方案

在SQLite上加一个redis

**Comment by wanghe-fit2cloud** [comment]
感谢您的建议，我们在团队内部也讨论一下上述方案。

**Comment by wanghe-fit2cloud** [comment]
经讨论，我们暂无上述计划，望理解。
