### ISSUE TITLE
[FEATURE]希望增加新增硬盘挂载到xx目录的功能

### ISSUE THREAD

**Issue by 52lemon6** [1Panel-dev/1Panel#265]
### 1Panel 版本

v1.0.1

### 请描述您的需求或者改进建议

希望增加新增硬盘挂载到xx目录的功能,比如，初始硬盘32G ，后期上了一块64G的新硬盘，需要扩容，插上硬盘后，可以直接在面板里选择挂载到哪个目录，数据自动迁移，或者是增加根目录的容量

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会探讨该需求的可行性。

**Comment by wartw** [comment]
希望新增此功能，因為如果是例如R5S這種EMMC容量極少的設備只能掛載外部儲存

**Comment by maninhill** [comment]
请问这个问题有进展吗？

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is there any progress on this issue?

**Comment by wanghe-fit2cloud** [comment]
磁盘相关需求的讨论，统一汇总到该 issue #1852
