### ISSUE TITLE
[BUG] 计划任务中的执行状态的判断优化

### ISSUE THREAD

**Issue by allyxmiko** [1Panel-dev/1Panel#2652]
### 联系方式

1713069822@qq.com

### 1Panel 版本

v1.7.3

### 问题描述

当在计划任务中使用shell执行自己写的程序时，可能会出现的状态判断失误的情况。

### 重现步骤

1. 在go语言中，`log.Println()`会将日志信息输出到stderr中，`fmt.Println()`会将信息输出到stdout中。
2. 在自己写的程序中使用了`log.Println()`就会导致执行过程中虽然成功执行（exit code 0），但由于`log.Println()`会将信息输出到了stderr，导致判断失误。
3. 现版本判断是否执行出错是通过`len(stderr.String()) != 0`来判断的。（文件位置：backend/utils/cmd/cmd.go    Line：94）

### 期待的正确结果

希望可以优化任务执行状态判断方法，比如使用exit code

**Comment by ssongliu** [comment]
感谢反馈！这里是否有具体的执行脚本可供参考呢？

之前我们使用的是 exit code，但是有些脚本退出码是 0，但是里面有异常抛出。

**Comment by allyxmiko** [comment]
#### 举例使用的脚本内容如下
![Snipaste_2023-10-24_10-17-38](https://github.com/1Panel-dev/1Panel/assets/53589496/ec6da46f-069d-4e2b-8634-b18652a209b0)
#### 当代码中使用`log.Println()`进行日志输出时，任务状态必定失败
![Snipaste_2023-10-24_10-18-21](https://github.com/1Panel-dev/1Panel/assets/53589496/a276d055-8dfe-4433-b35c-9f3524ce7402)
使用`log.Println()`的代码在计划任务中的执行结果如下
![Snipaste_2023-10-24_10-19-31](https://github.com/1Panel-dev/1Panel/assets/53589496/fe8baaf6-e578-4941-b017-aa4859846acd)
#### 当代码中使用`fmt.Println()`进行输出时，任务可以执行成功
![Snipaste_2023-10-24_10-20-07](https://github.com/1Panel-dev/1Panel/assets/53589496/2418af1f-98e4-4df7-8bab-e2174fd787b2)
使用`fmt.Println()`的代码在计划任务中的执行结果如下
![Snipaste_2023-10-24_10-21-37](https://github.com/1Panel-dev/1Panel/assets/53589496/6a415849-63f6-467b-b2fa-fee65874ff25)
#### 造成这个问题的原因就是`log.Println()`会将日志信息输出到stderr中，而`fmt.Println()`会将信息输出到stdout中
`log.Println()`将信息输出到了stderr中
![Snipaste_2023-10-24_10-36-20](https://github.com/1Panel-dev/1Panel/assets/53589496/676e9324-f819-44c4-9d40-48596c7b12d1)
使用`log.Println()`输出stdout为空
![Snipaste_2023-10-24_10-37-02](https://github.com/1Panel-dev/1Panel/assets/53589496/6b13e8b2-7c03-42d0-a6e8-619a68edd7a9)
由于判断是通过`stderr.String()`进行判断，，所以出现状态失败
`fmt.Println()`将信息输出到了stdout中
![Snipaste_2023-10-24_10-41-22](https://github.com/1Panel-dev/1Panel/assets/53589496/dac84be1-9e0e-432a-b200-9c6b6a974ec8)
![Snipaste_2023-10-24_10-42-06](https://github.com/1Panel-dev/1Panel/assets/53589496/c40b3670-7b6b-4cbd-ae81-b2d22085ce8e)
此时`stderr.String()`判断可以通过，所以状态成功
@ssongliu

**Comment by ssongliu** [comment]
好的了解了，非常感谢！我们先讨论一下这部分该怎么优化一下。

**Comment by wanghe-fit2cloud** [comment]
v1.7.4 版本已发布。
