### ISSUE TITLE
[BUG]安装halo 2.10.0 失败提示 “文件不存在”

### ISSUE THREAD

**Issue by guomingshan** [1Panel-dev/1Panel#2653]
### 1Panel 版本

1.7.3

### 问题描述

安装halo 2.10.0 失败提示 “文件不存在”
![image](https://github.com/1Panel-dev/1Panel/assets/38829832/0364155a-7d6f-44ec-a614-7802fb2c88c3)

### 重现步骤

正常安装

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
点击应用商店列表右上角的 `更新应用列表` 按钮，等待同步成功后再安装，试一下。

**Comment by guomingshan** [comment]
> 感谢反馈。 点击应用商店列表右上角的 `更新应用列表` 按钮，等待同步成功后再安装，试一下。

好了，谢谢
