### ISSUE TITLE
[FEATURE]更多的web服务器及端口问题

### ISSUE THREAD

**Issue by skyhhjmk** [1Panel-dev/1Panel#2654]
### 1Panel 版本

v1.7.3

### 请描述您的需求或者改进建议

需要 apache，litespeed，openlitespeed，kangle等更多web服务器

建议在面板设置中添加一个“开发者模式”和“开发者强制模式”
在开发者模式下，本不能修改端口的app应变为可修改，若修改后无法启动的或无法正常使用的即拒绝修改
在开发者强制模式下，可以任意修改app端口，即使已知修改后无法正常运行

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述需求。

**Comment by hkbbdx** [comment]
请问什么时候能支持apache？

**Comment by skyhhjmk** [comment]
> 请问什么时候能支持apache？

你可以暂时使用openlitespeed替代

**Comment by vnsur** [comment]
基本上没有启用源码，目前只适用于OpenResty

**Comment by realstephenzhao** [comment]
希望未来的版本能移除面板功能（比如网站模块）对 OpenResty 的依赖，这样才能方便使用不同类型的服务器。

**Comment by realstephenzhao** [comment]
> > 请问什么时候能支持apache？
> 
> 你可以暂时使用openlitespeed替代

我试过了，1Panel 面板的有些模块需要安装 OpenResty 才能使用。即便安装时修改端口也把 OpenLiteSpeed 安装进去了，那些模块还是会使用 OpenResty。所以，当前版本的 1Panel 就没有考虑到去支持其他服务器。

**Comment by wanghe-fit2cloud** [comment]
> > > 请问什么时候能支持apache？
> > 
> > 
> > 你可以暂时使用openlitespeed替代
> 
> 我试过了，1Panel 面板的有些模块需要安装 OpenResty 才能使用。即便安装时修改端口也把 OpenLiteSpeed 安装进去了，那些模块还是会使用 OpenResty。所以，当前版本的 1Panel 就没有考虑到去支持其他服务器。

可以考虑通过应用商店或者容器编排来管理更多 web 服务器。
但是 1Panel 的 `网站` 功能还必须强依赖 OpenResty，暂无适配其他 web 服务器的精力，望理解。
