### ISSUE TITLE
[BUG]在计划任务中，定时备份系统快照，经常性显示文件在我们读入之前被删除了。

### ISSUE THREAD

**Issue by ChishFoxcat** [1Panel-dev/1Panel#2656]
### 1Panel 版本

v1.7.3

### 问题描述

在计划任务中，定时备份系统快照，经常性显示**文件在我们读入之前被删除了**
成功部分都是手动执行的
![image](https://github.com/1Panel-dev/1Panel/assets/76027184/fc0f82e7-b817-444a-bdd7-22002b83f9a2)
![image](https://github.com/1Panel-dev/1Panel/assets/76027184/ca21c2a1-c8be-4d47-ba14-e63faccff18d)

### 重现步骤

设置最近的时间让他自动执行

### 相关日志输出

```shell
最近的一个：
Write 1Panel basic information: Done 
Backup 1Panel system files: Done 
Backup Docker configuration file: Done 
Backup installed apps from 1Panel: Done 
Backup 1Panel data directory: Done 
Backup local backup directory for 1Panel: do handle tar failed, stdout: stderr: tar: ./app/portainer-ce/portainer-ce/app_portainer-ce_20231023030000：文件在我们读入之前被删除了
tar: ./app/openresty/openresty/app_openresty_20231013023000.tar.gz：文件在我们读入之前被删除了
, err: exit status 1 
Create snapshot file: Waiting 
Snapshot size:  
Upload snapshot file: Waiting 

前几天的：
Write 1Panel basic information: Done 
Backup 1Panel system files: Done 
Backup Docker configuration file: Done 
Backup installed apps from 1Panel: Done 
Backup 1Panel data directory: Done 
Backup local backup directory for 1Panel: do handle tar failed, stdout: stderr: tar: ./app/portainer-ce/portainer-ce/app_portainer-ce_20231023030000：文件在我们读入之前被删除了
tar: ./app/openresty/openresty/app_openresty_20231013023000.tar.gz：文件在我们读入之前被删除了
, err: exit status 1 
Create snapshot file: Waiting 
Snapshot size:  
Upload snapshot file: Waiting
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by ssongliu** [comment]
这里是不是有一个定时备份应用 openresty 的计划任务和快照差不多时间执行呢？

**Comment by ChishFoxcat** [comment]
是的，我同时备份了应用，并且在同一时间，是备份应用的时候删除那个包吗？我去调整一下他们的时间

> 我最近发现没有出现错误了
![Screenshot_2023-10-28-02-03-44-020_com.microsoft.emmx.jpg](https://github.com/1Panel-dev/1Panel/assets/76027184/45f978e6-7e83-4d33-a93c-e5ae70e41acd)

**Comment by ssongliu** [comment]
就是这个问题，因为备份的时候有一个保存份数限制，会默认删掉老的加上新的，和快照同一时间操作导致压缩失败。

**Comment by zyyfit** [comment]
快照计划任务执行失败是因为有快照的计划任务和openresty的任务在同一时间执行，openresty的计划任务有设置保留分数，然后执行快照的时候，同时执行了openresty的计划任务，然后把openresty历史计划任务产生的文件删了，然后快照的计划任务就报错了
由于修改难度较大，目前暂时不做修改

**Comment by iLayPark** [comment]
备份和恢复快照时经常提示 
restore original panel data failed, err: do handle tar failed, stdout: stderr: tar: ./db/1Panel.db-wal：文件在我们读入之前被删除了 , err: exit status 1
