### ISSUE TITLE
[BUG]在数据库菜单中导入中文乱码

### ISSUE THREAD

**Issue by 0x76long** [1Panel-dev/1Panel#2657]
### 联系方式

1panel 交流群3 @ᑋᵉᑊᑊᵒ

### 1Panel 版本

1.7.2

### 问题描述

1.7.2版本 
mysq  5.6.51  

### 重现步骤

在数据库菜单中 从导入备份中 直接导入sql 中文乱码，在phpmyadmin 上导入sql没有乱码  
sql文件是UTF8 表也是UTF8

### 期待的正确结果

中文无乱码

**Comment by ssongliu** [comment]
感谢反馈！可以提供一下恢复的 sql 文件吗？

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。

**Comment by 1984anonymous** [comment]
从备份恢复数据  emoji 也会乱码  怀疑是导出跟导入时的数据库编码 不一致    或许应该统一使用  utf8mb4 ？ @wanghe-fit2cloud
