### ISSUE TITLE
[BUG] 阿里云mysql的回收表名为 __recycle_bin__ 

### ISSUE THREAD

**Issue by shaozi17** [1Panel-dev/1Panel#2658]
### 联系方式

706954178@qq.com

### 1Panel 版本

1.7.3

### 问题描述

在使用远程mysql链接ali的rds时, 从服务器同步表的时候, 没有忽略表名为__recycle_bin__ 的表,并且为他创建了权限账户, 默认root是无法操作__recycle_bin__ 表的, 所以会报错, 
我看到1.7.2中有一个commit 加入了表recycle_bin的跳过, 可能需要修改一下 表名为__recycle_bin__

### 重现步骤

使用远程mysql链接ali的rds, 从服务器同步表

### 相关日志输出

```shell
服务内部错误: sync db from remote server failed, err: create user failed Error 1044 (42000): Access denied for user 'root'@'%' to database '__recycle_bin__'
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.7.4 版本已发布。
