### ISSUE TITLE
[FEATURE] 希望应用商店添加 Heimdall，这是一款应用展示仪表盘

### ISSUE THREAD

**Issue by yarin-zhang** [1Panel-dev/1Panel#2662]
### 1Panel 版本

v1.7.3

### 请描述您的需求或者改进建议

希望应用商店添加 Heimdall 的安装和部署功能，这是一款应用展示仪表盘，支持多种工具的数据展示。

官网：https://heimdall.site
Github：https://github.com/linuxserver/Heimdall
Dockerhub：https://hub.docker.com/r/linuxserver/heimdall/

### 请描述你建议的实现方案

通过 Docker 部署

### 附加信息

未来也许可以尝试添加更多功能，例如将目前已安装的应用，自动同步到 Heimdall 中。

![](https://camo.githubusercontent.com/bcfd4f74c93b25bea7b14eacbafd649206bf754a3d4b596329968f0ee569cf3c/68747470733a2f2f692e696d6775722e636f6d2f4d72433451704e2e676966)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述应用。

**Comment by okxlin** [comment]
这里有
- https://github.com/okxlin/appstore

**Comment by wanghe-fit2cloud** [comment]
> 这里有
> 
> * https://github.com/okxlin/appstore

提个 Pull requests 吧：https://github.com/1Panel-dev/appstore/pulls

**Comment by okxlin** [comment]
> > 这里有
> > 
> > * https://github.com/okxlin/appstore
> 
> 提个 Pull requests 吧：https://github.com/1Panel-dev/appstore/pulls

https://github.com/1Panel-dev/appstore/pull/340

很早就提了哈

**Comment by wanghe-fit2cloud** [comment]
> > > 这里有
> > > 
> > > * https://github.com/okxlin/appstore
> > 
> > 
> > 提个 Pull requests 吧：https://github.com/1Panel-dev/appstore/pulls
> 
> [1Panel-dev/appstore#340](https://github.com/1Panel-dev/appstore/pull/340)
> 
> 很早就提了哈

看到了，在之前提的包含很多应用的那个 pr 里，计划在 v1.8.0 版本支持。

**Comment by yarin-zhang** [comment]
> 这里有
> 
> * https://github.com/okxlin/appstore

看了下包含很多常用的，如果能批量上架就太好了。

如果批量上架有审核方面的顾虑（商业、协议之类），建议 1Panel 可以考虑实现一个接入第三方应用源的功能，类似群晖的手动添加应用源，可以让用户按需添加。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
