### ISSUE TITLE
[BUG]开发板arm64，边缘设备，断电移机，通电自起，docker容器全部bug, 已上线时长9个月+???

### ISSUE THREAD

**Issue by gowy222** [1Panel-dev/1Panel#2665]
### 1Panel 版本

1.7.3

### 问题描述

Debian系统

树莓派 R2S Iot等设备 基本上没有一个会正常关机，都是拔掉电源走人，
然后到实际部署设备地点通电自动开机..

等了半天没上线，跑回现场网线接入发现，所有镜像全部莫名其妙 已在线9个月+
网络也有部分影响, 比如 docker 跑的K3S, 内部直接无法启动node节点 各种网络iptable错误, 

目前临时解决方案是, 写了一个sh脚本，开机后，after docker网络 延时1分钟 全部重启docker，和重启 docker-compose.yml
一般我是手写 docker-compose.yml 放在 自定义目录。不是用1panel面板的编排。

还有个bug2，WAN口正常接上游，LAN口 多网卡eth1和eht0桥接br0，docker部署了一个DHCPD给br0分配IP（镜像:anzevalher/dnsmasq:latest），然后docker 创建 macvlan 挂载br0 - >跑其他的容器，1panel一直崩。

### 重现步骤

1.开发办公室docker-compose.yml 部署上线一切正常
2.拔电走人,.....开发板 小设备 别指望sh登录进去正常关机.... 更不可能为了一个5V3A的设备上UPS电源...
3.换个办公室，通电开机..
4.等一会 插根网线进去, 容器已运行，但是 已上线时间全部 已经9个月+ , docker部署的 K3S 几乎不能正常工作...

-----
边缘设备 固件一般都是 overlay 系统分区，docker 是划分到 其他隔离分区， docker-compose.yml 文件位置导致？
ps: 我是先手动装docker 再安装的 1panel。不然 1panel自动安装脚本怕把docker安装到 overlay 系统分区去。
1panel则是默认装在系统分区。

**Comment by wanghe-fit2cloud** [comment]
> 4.等一会 插根网线进去, 容器已运行，但是已上线时间全部 已经9个月+ , docker部署的 K3S 几乎不能正常工作...

1、`已上线时间` 是什么意思。
2、1Panel 只是依赖 docker 环境来部署应用，但 k3s 不能正常工作这要看 k3s 的详细运行日志了。

> 服务器部署的 docker 是通过 systemd 来管理的，支持设置开机自启动。
容器化部署的应用也是可以设置重启规则的。

**Comment by gowy222** [comment]
> > 4.等一会 插根网线进去, 容器已运行，但是已上线时间全部 已经9个月+ , docker部署的 K3S 几乎不能正常工作...
> 
> 1、`已上线时间` 是什么意思。 2、1Panel 只是依赖 docker 环境来部署应用，但 k3s 不能正常工作这要看 k3s 的详细运行日志了。
> 
> > 服务器部署的 docker 是通过 systemd 来管理的，支持设置开机自启动。
> > 容器化部署的应用也是可以设置重启规则的。

1. 已上线时间 ， 尬，就是容器 [ 运行时长 ]
2. k3s [ host 网络部署的 ] 底层依赖 cgroupfs，我目前1panel也设置的 "native.cgroupdriver=cgroupfs"

**Comment by wanghe-fit2cloud** [comment]
1、docker ps 可查看两个时间，要区分 `CREATED` 和 `STATUS`。
2、可自行查看 docker 配置文件 daemon.json（1Panel 配置页面也是操作的这个文件）。

**Comment by gowy222** [comment]
> 1、docker ps 可查看两个时间，要区分 `CREATED` 和 `STATUS`。 2、可自行查看 docker 配置文件 daemon.json（1Panel 配置页面也是操作的这个文件）。

关键我设备到手才1周... 怎么也不会9个月+..
