### ISSUE TITLE
[FEATURE] Node.JS 新增 20.9.0 (LTS) 和 21.1.0 (Current) 版本运行环境

### ISSUE THREAD

**Issue by HenryWu01** [1Panel-dev/1Panel#2666]
### 1Panel 版本

1.7.2

### 请描述您的需求或者改进建议

现在 ``20.9.0`` 已经变成 LTS (Long Term Support) 版本了，``21.1.0`` 成为了当前版本，希望 ``1Panel`` 可以加入这两个版本的运行环境

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本推送更新。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。

**Comment by HenryWu01** [comment]
``20.11.1 LTS`` 和 ``21.6.2`` 已经发布~不知道是否可以更新一下呀 @wanghe-fit2cloud

**Comment by wanghe-fit2cloud** [comment]
> `20.11.1 LTS` 和 `21.6.2` 已经发布~不知道是否可以更新一下呀 @wanghe-fit2cloud

收到，麻烦新开一个 issue，我们后续版本推送更新。

**Comment by HenryWu01** [comment]
> > `20.11.1 LTS` 和 `21.6.2` 已经发布~不知道是否可以更新一下呀 @wanghe-fit2cloud
> 
> 收到，麻烦新开一个 issue，我们后续版本推送更新。

好的，我新开一个 issue: #4041
