### ISSUE TITLE
[FEATURE] 按钮圆角优化

### ISSUE THREAD

**Issue by ioalloc** [1Panel-dev/1Panel#2669]
### 1Panel 版本

1.17.1

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/6737824/f0279a4c-f4c7-48cd-b241-4ef0948888b5)

### 请描述你建议的实现方案

这里看着很难受，希望优化一下

**Comment by wanghe-fit2cloud** [comment]
后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.7.4 版本已发布。
