### ISSUE TITLE
[BUG]日志审计菜单，网站日志没有切换成功，只能显示默认选中的那个网站

### ISSUE THREAD

**Issue by justmd5** [1Panel-dev/1Panel#2670]
### 1Panel 版本

v1.7.2

### 问题描述

日志审计里边，运行日志的网站切换，没有切换成功，只能显示默认选中的那个网站

### 重现步骤

1.日志审计->网站日志->运行日志无法切换网站查看对应网站日志
2.运行日志和错误日志选择切换也没有反应

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
