### ISSUE TITLE
[BUG] 部分页面分页不正常

### ISSUE THREAD

**Issue by lancer-wang** [1Panel-dev/1Panel#2674]
### 1Panel 版本

1.7.3

### 问题描述

域名/.well-known/acme-challenge/
返回404
这里地址手动选择其他位置也不行
![image](https://github.com/1Panel-dev/1Panel/assets/69783837/a993b545-ad41-4276-8595-a795652f3a7d)

### 重现步骤

我是先新建静态网站，然后配置反向代理

**Comment by lancer-wang** [comment]
http方式申请Let's Encrypt的证书

**Comment by zhengkunwang223** [comment]
修改一下 
```
    location ^~ /.well-known/acme-challenge {
        allow all;
        root /usr/share/nginx/html;
    }
```
然后重新申请

**Comment by lancer-wang** [comment]
> 修改一下
> 
> ```
>     location ^~ /.well-known/acme-challenge {
>         allow all;
>         root /usr/share/nginx/html;
>     }
> ```
> 
> 然后重新申请
服务器运营商炸了，等下试试

**Comment by lancer-wang** [comment]
> 修改一下
> 
> ```
>     location ^~ /.well-known/acme-challenge {
>         allow all;
>         root /usr/share/nginx/html;
>     }
> ```
> 
> 然后重新申请

试了下，可以了

**Comment by lancer-wang** [comment]
修改的时候遇到个bug，不开新issue了
![image](https://github.com/1Panel-dev/1Panel/assets/69783837/2b0881fd-dd0e-42fe-a3d0-7a401e339b61)

这里选择20个一页。然后进某个网站的设置，保存并重载之后，返回到列表页，这里实际只有10条
要重新切一下每页个数

**Comment by lancer-wang** [comment]
试了下，改成20条/页面
然后切到其他页面，再切回来，也会复现这个

**Comment by zhengkunwang223** [comment]
已复现 v1.8.0版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.7.4 版本已发布。
