### ISSUE TITLE
PHP等常用扩展加上默认啊

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#2679]
### 1Panel 版本

1.7.3

### 请描述您的需求或者改进建议

php等常用扩展加上默认啊，不然很多人一堆问题也不知道缺啥
比如典型的zip  gd等，甚至连mysqli pdo都要我选填
面板就是用来方便的呀，一堆小白装好了连不了数据库又来叫了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本可能会考虑上述需求。
