### ISSUE TITLE
[QUESTION]php 7.4 安装 swoole 扩展失败。

### ISSUE THREAD

**Issue by xieyuhua** [1Panel-dev/1Panel#2681]
### 请描述您的问题

我选择了这些扩展

![image](https://github.com/1Panel-dev/1Panel/assets/29120060/bb0c9f92-064e-451d-b7c1-6c7f6051c7f8)

容器里面执行查看扩展，不存在呀？如何安装
![image](https://github.com/1Panel-dev/1Panel/assets/29120060/adaf7169-3953-4358-86e2-1632f3c9e209)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，刚在本地环境已经复现上述问题，我们将在近期版本适配完成后推送更新。

**Comment by wanghe-fit2cloud** [comment]
v1.7.4 版本已发布。
