### ISSUE TITLE
[FEATURE] 希望在文件管理界面增加右键唤出菜单功能

### ISSUE THREAD

**Issue by wuhu717373250** [1Panel-dev/1Panel#2684]
### 1Panel 版本

1.7.3

### 请描述您的需求或者改进建议

希望能在 主机 > 文件 这个页面能像windows,右键可以唤出 菜单(复制,移动,重命名这种的),这种在上方操作的不是很习惯

**Comment by zhengkunwang223** [comment]
您好 后续版本持续优化

**Comment by wanghe-fit2cloud** [comment]
经讨论，我们暂无计划支持上述续期，望理解。
