### ISSUE TITLE
[FEATURE] 抽屉关闭的方式不统一,希望能统一

### ISSUE THREAD

**Issue by wuhu717373250** [1Panel-dev/1Panel#2685]
### 1Panel 版本

1.7.3

### 请描述您的需求或者改进建议

希望 这个 Drawer 抽屉的关闭方式能统一,发现有的地方的,点击 Drawer 外面能关闭,有的却又不能要点返回,有的返回按钮却又没有

![image](https://github.com/1Panel-dev/1Panel/assets/148927976/e9aae996-12b4-4dec-ad13-a45e014de7fa)

### 请描述你建议的实现方案

希望能将 element 的 Drawer 这个组件二次封装一下,然后在整个项目中调用这个二次的组件(前端哭死哈哈哈),这样就能统一风格了,不然真的很不习惯,谢谢了

**Comment by zhengkunwang223** [comment]
您好  大部分情况下为了防止用户填写参数之后不小心点了一下鼠标造成数据丢失 这些页面我们都是不允许点击空白返回的
但是只有数据展示的页面 是可以点空白页返回的
