### ISSUE TITLE
[BUG] loading 超出按钮范围

### ISSUE THREAD

**Issue by wuhu717373250** [1Panel-dev/1Panel#2686]
### 联系方式

1panel 交流群 1

### 1Panel 版本

1.7.3

### 问题描述

loading 的图标超出确定按钮

![image](https://github.com/1Panel-dev/1Panel/assets/148927976/24e25e0d-4156-4dc5-b76a-02aab77f138a)

### 重现步骤

任意弹窗

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
