### ISSUE TITLE
希望安装脚本适配coreelec和openwrt系统，文件结构不同于debian和centos

### ISSUE THREAD

**Issue by icezxf** [1Panel-dev/1Panel#2687]
### 1Panel 版本

1.7.3

### 请描述您的需求或者改进建议

希望系统可以适配coreelec和openwrt 安装脚本也是

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
在中短期内我们应该不会优先考虑上述需求，望理解。

> 可以使用第三方提供的 docker 版本（部分功能目前尚不完整），镜像如下：
https://hub.docker.com/r/moelin/1panel

**Comment by okxlin** [comment]
systemctl没有的系统推荐使用dokcer版本1panel凑合用

- https://github.com/okxlin/docker-1panel

![image](https://github.com/1Panel-dev/1Panel/assets/61420215/6d2c3fca-eb2f-4997-8462-e37f78d23d97)

**Comment by wanghe-fit2cloud** [comment]
1Panel 最新版本的安装脚本已兼容 OpenWrt。
