### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RedCarl** [1Panel-dev/1Panel#2688]
### 联系方式

carl030101@icloud.com

### 1Panel 版本

v1.7.3

### 问题描述

我使用应用商店安装uptimekuma提示安装失败，然后卸载不掉，提示找不到安装目录

### 重现步骤

直接安装就失败，然后就删不掉

**Comment by RedCarl** [comment]
补充一下，我安装的时候是旧版本大概是1.6，失败后我升级了1.7，现在可以安装了，但是之前的没法卸载。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
可以进去 `已安装` 应用列表，点击卸载时勾选 `强制删除` 按钮，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/008395f4-eac4-4aee-a6ff-629efdea9758)
