### ISSUE TITLE
[BUG] php网站切换版本之后 compose文件的服务名会被覆盖成php 导致保存失败

### ISSUE THREAD

**Issue by shaozi17** [1Panel-dev/1Panel#2689]
### 联系方式

706954178@qq.com

### 1Panel 版本

1.7.3

### 问题描述

php网站切换php版本之后 compose文件的服务名会被覆盖成php 导致保存失败

### 重现步骤

我的容器使用的都是自定义名称, 比如 testcom, compose的servicename默认会是我设置的容器名称
在切换php版本之后, 再次编辑compose文件的时候,发现servicename被重置成php了, 导致保存失败
![Snipaste_2023-10-26_14-46-35](https://github.com/1Panel-dev/1Panel/assets/22265868/87bc7466-1cc6-4a37-9e48-db531e7f46c5)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们将在近期版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
