### ISSUE TITLE
[FEATURE] 增加“不响应未绑定的域名和IP的访问“功能

### ISSUE THREAD

**Issue by orilights** [1Panel-dev/1Panel#2693]
### 1Panel 版本

1.7.4

### 请描述您的需求或者改进建议

希望能在 [网站] > [默认站点] 设置中提供一个选项 ”不响应未绑定的域名和IP的访问“ 

开启后就不重定向到默认站点也不显示 404 页面了，直接返回 Nginx 的 444 状态码断开连接，增加安全性。

### 请描述你建议的实现方案

对未绑定的域名、IP的访问直接返回 Nginx 的 444 状态码，断开连接而不发送任何响应

```
server {
    listen 80 default_server;
    server_name _;

    return 444;
}

server {
    listen 443 ssl http2 default_server;
    server_name _;

    ssl_reject_handshake on; #防止泄露证书

    return 444;
}
```

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本考虑此功能

**Comment by wanghe-fit2cloud** [comment]
专业版 WAF 功能已支持。
