### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by IF-tiger** [1Panel-dev/1Panel#2694]
### 1Panel 版本

1.7.4

### 请描述您的需求或者改进建议

使用腾讯云轻量云服务器的同学,在服务器面板添加安全组包括docker部署的应用所配置的安全组必须都要在轻量服务器面板里单独配置安全组,docker部署的应用勾选外部访问,同时前往轻量服务器面板单独配置安全组端口.

**Comment by wanghe-fit2cloud** [comment]
麻烦再详细描述一下具体需求或者问题。

**Comment by Mr-Ao-Dragon** [comment]
> 麻烦再详细描述一下具体需求或者问题。

应该是想统一安全组和防火墙

**Comment by wanghe-fit2cloud** [comment]
> > 麻烦再详细描述一下具体需求或者问题。
> 
> 应该是想统一安全组和防火墙

可以通过云厂商提供的 API 来实现上述需求，但是考虑到适配工作量巨大，还是建议单独来配置管理。
