### ISSUE TITLE
[FEATURE] 网站重名时，分不清

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#2695]
### 1Panel 版本

1.7.3

### 请描述您的需求或者改进建议
当我使用ip不同端口创建网站时， 名称是一样的， 查看网站日志时分不出来哪个是哪个
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/87416916-da3c-4ea3-adcd-69b09417e1ca)
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/b76a9745-d274-4c5a-9d86-c2394b537d86)

**Comment by zhengkunwang223** [comment]
我们应该是禁止了重名网站 你这个是怎么创建的呢

**Comment by 9a6c** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/2a0507a9-8c86-4ddb-b522-b541aa0242fe)
上一个版本是直接输入 ip:端口  进行创建的，  现在的版本，这样操作， 一直提示  9000端口已占用

**Comment by zhengkunwang223** [comment]
已复现 v1.8版本修复这个问题

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
