### ISSUE TITLE
[FEATURE]新增对于面板升级时的备份数据的管理功能

### ISSUE THREAD

**Issue by WankkoRee** [1Panel-dev/1Panel#2696]
### 1Panel 版本

v1.7.4

### 请描述您的需求或者改进建议

当前面板的老版本和新版本在更新时分别会将当前版本的相关数据以及新版本的二进制文件存放于`/opt/1panel/tmp/upgrade_yyyyMMddhhmmss`和`/opt/1panel/tmp/upgrade/upgrade_yyyyMMddhhmmss`中，我在看了一下我的备用服务器，历经更新16次，跨度为从今年4月份到今年10月份，总共占用了4.28G磁盘空间。

能否提供对这些版本升级产生的临时文件的管理功能，如手动删除老版本临时文件、自动删除过旧版本临时文件（具体如何界定是否过旧，可以由用户设定时间间隔超过x月或中间版本超过x个）的临时文件。

大致实现可参考`Windows.old`机制。

**Comment by ssongliu** [comment]
感谢反馈！目前在面板设置中有一个清理缓存的功能，可以用来删除这些数据。

**Comment by WankkoRee** [comment]
> 感谢反馈！目前在面板设置中有一个清理缓存的功能，可以用来删除这些数据。

刚发现有这个功能，试了一下基本符合我的功能需求，自动化功能的话倒是不太重要。

但是这个功能当前显示为一个表单项多少有点不合理，我还是找了一会才发现在表单里。

**Comment by wanghe-fit2cloud** [comment]
> 但是这个功能当前显示为一个表单项多少有点不合理，我还是找了一会才发现在表单里。

后续版本会增加工具箱菜单。
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/e58104b0-2863-49c9-afc4-c3c372327e6d)
