### ISSUE TITLE
[BUG] 通过应用商店安装的jumpserver无法通过admin/admin登录

### ISSUE THREAD

**Issue by shangdev** [1Panel-dev/1Panel#2697]
### 1Panel 版本

1.7.4

### 问题描述

通过应用商店安装jumpserver后，无法通过默认用户名密码admin/admin登录，登录时提示：

```
配置文件有问题，无法登录，请联系管理员或查看最新文档
如果你是管理员，可以更新配置文件解决，设置配置项 DOMAINS=
```

然后我去应用商店->已安装->jumpserver参数编辑里，把 DOMAINS 设置为面板访问IP,面板访问IP:port,本机IP,vpn代理IP，均不能登录。

### 重现步骤

1、应用商店安装jumpserver
2、在已安装中点击jumpserver的服务端口：8080按钮访问
3、输入默认用户名密码：admin/admin

**Comment by wanghe-fit2cloud** [comment]
JumpServer v3.8.0 版本确实存在上述问题，详情见下面的 issue:
https://github.com/jumpserver/jumpserver/issues/11935

> 1Panel 也在积极适配最新版本，成功后会及时推送更新。

**Comment by wanghe-fit2cloud** [comment]
JumpServer 最新版本(v3.8.1)已推送。
可以进入 `应用商店` 页面点击右上角的 `更新应用列表` 按钮，等待同步成功后再来安装。

如果 JumpServer 登录页面提示 DOMAINS 等配置错误，可以进入 `应用商店` - `已安装` 列表，点击 `参数` - `编辑`，然后修改具体参数后提交。
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/300de343-2796-424e-b7de-fdb11689ad7f)
