### ISSUE TITLE
[FEATURE] 1Panel 升级时前端轮询一个接口判断升级是否完成

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#2709]
### 1Panel 版本

1.7.4

### 请描述您的需求或者改进建议

建议 1Panel 升级时前端轮询一个接口判断升级是否完成，而不是直接在某个时间段刷新，有时候系统升级比较久，在系统升级完成重启前刷新页面会导致出现页面访问失败，建议通过 API 检测到系统升级完成在进行刷新操作

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
升级时全部页面 loading，主要是为了确保在此期间用户没有其他操作，保证备份、恢复数据一致。
> 就不参考上述建议了，望理解。
