### ISSUE TITLE
容器挂载本机目录权限问题

### ISSUE THREAD

**Issue by jifeiyun** [1Panel-dev/1Panel#2712]
### 请描述您的问题

<img width="932" alt="ba1d67336e5af14e250a6a68c089c15" src="https://github.com/1Panel-dev/1Panel/assets/33753479/2873e341-c8a3-4687-801d-d36191c6817d">
<img width="815" alt="2b1c311eba49c4dbd17706bcdfdf46a" src="https://github.com/1Panel-dev/1Panel/assets/33753479/fcdd1b3d-d372-4d1b-ad5a-ad7b699667b8">
<img width="556" alt="5b6b99ef7283e6093be44e0732d2807" src="https://github.com/1Panel-dev/1Panel/assets/33753479/3913066b-f70b-4944-8d4c-cf8f264aa9ac">
需要手动改0777才行？

**Comment by wanghe-fit2cloud** [comment]
报错信息是容器内用户无法创建文件。
此时，需要修改宿主机挂载目录的 uid 和 gid，和容器内用户保持一致。
