### ISSUE TITLE
[QUESTION]当前无法使用此页面，当前无法处理此请求，HTTP ERROR 502

### ISSUE THREAD

**Issue by shmilyabyy** [1Panel-dev/1Panel#2713]
### 请描述您的问题

但是开启无痕窗口或者更换其他浏览器就可以正常显示。请问应该如何解决此问题。已更新至最新版本了。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦再详细的描述一下具体问题。

**Comment by shmilyabyy** [comment]
就是面板打不开，当前无法使用此页面。但是开无痕就可以正常打开了。

**Comment by wanghe-fit2cloud** [comment]
> 就是面板打不开，当前无法使用此页面。但是开无痕就可以正常打开了。

可以看看是不是浏览器开了 proxy 等原因导致的。
