### ISSUE TITLE
PHP 7.3.33 SSL Version	OpenSSL/1.1.1w 已启用，但是找不到 SM4 加密算法

### ISSUE THREAD

**Issue by BadDeveloper2022** [1Panel-dev/1Panel#2714]
### 请描述您的问题

PHP 7.3.33 SSL Version	OpenSSL/1.1.1w 已启用，但是找不到 SM4 加密算法
![image](https://github.com/1Panel-dev/1Panel/assets/7404699/2dbdf584-3479-4e49-888b-37b21f948ebf)
![image](https://github.com/1Panel-dev/1Panel/assets/7404699/7ee4019e-48cd-4278-b1a5-a0fdc3bf04fd)

**Comment by BadDeveloper2022** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/7404699/7f3efc61-b03a-4db4-967d-168ba979deca)

**Comment by BadDeveloper2022** [comment]
启动PHP 警告
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_openssl.dll' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20180731/php_openssl.dll (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20180731/php_openssl.dll: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20180731/php_openssl.dll.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20180731/php_openssl.dll.so: No such file or directory)) in Unknown on line 0

**Comment by BadDeveloper2022** [comment]
@wanghe-fit2cloud @xiaolongyuan @mx2913 @Mystery00

**Comment by wanghe-fit2cloud** [comment]
系统自带的 openssl 中没有 sm4 加密算法，大概率得重新编译。
