### ISSUE TITLE
[QUESTION]php7.2 扩展支持

### ISSUE THREAD

**Issue by haiwan-xm** [1Panel-dev/1Panel#2715]
### 请描述您的问题

php是否能支持如下扩展呢？
rrdtool  tcping   ipmitool

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前下拉列表中不存在的扩展，可以手动输入之后选择。

**Comment by haiwan-xm** [comment]
我已经安装了发现php扩张依旧没有支持
