### ISSUE TITLE
[FEATURE]请问未来可以集成邮局吗 ？

### ISSUE THREAD

**Issue by haiwan-xm** [1Panel-dev/1Panel#2716]
### 1Panel 版本

1.7

### 请描述您的需求或者改进建议

https://github.com/postalserver/postal

**Comment by wanghe-fit2cloud** [comment]
近期版本会考虑支持上述应用。

**Comment by zyyfit** [comment]
1.8.0集成了 Mailserver 和 Maddy Mail Server 两个邮件服务器

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
