### ISSUE TITLE
[FEATURE] 建议增加其它语言开发部署支持

### ISSUE THREAD

**Issue by TomYule** [1Panel-dev/1Panel#2718]
### 1Panel 版本

1.7.4

### 请描述您的需求或者改进建议

PHP项目
Java项目
Node项目
Go项目
Python项目
其他项目

### 请描述你建议的实现方案

[FEATURE] 建议增加其它语言开发部署支持

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本陆续支持上述运行环境。

**Comment by mccj** [comment]
还有 netcore 项目

**Comment by aladdin-im** [comment]
Go早点安排上哦，这个需求比较大

**Comment by wanghe-fit2cloud** [comment]
> Go早点安排上哦，这个需求比较大

当前版本，可以考虑通过 `主机` - `进程守护` 功能来实现。

**Comment by echohuub** [comment]
> > Go早点安排上哦，这个需求比较大
> 
> 当前版本，可以考虑通过 `主机` - `进程守护` 功能来实现。

然后可以使用 OpenResty 设置反代吗？

**Comment by aladdin-im** [comment]
> > Go早点安排上哦，这个需求比较大
> 
> 当前版本，可以考虑通过 `主机` - `进程守护` 功能来实现。

统一回复：

我自己把 Go 项目构建镜像，然后在 1Panel 创建容器，设置端口映射，也可以挂载主机目录，然后使用 OpenResty 建立反代网站就行了

理论上大家提的所有环境支持都可以通过此方案解决。感觉这也比较符合 1Panel 的设计理念，一切皆容器

**Comment by TomYule** [comment]
我的Java项目就是用docker部署 反向代理配置的

**Comment by ysysdzz** [comment]
> 我的Java项目就是用docker部署 反向代理配置的

请问怎样做相关监控呢，比如Jvm

**Comment by TomYule** [comment]
> > 我的Java项目就是用docker部署 反向代理配置的
> 
> 请问怎样做相关监控呢，比如Jvm

https://daocloud-labs.github.io/DX-DMP-Public-Docs/spec/jvm-docker.html

**Comment by wanghe-fit2cloud** [comment]
运行环境需求的讨论，统一汇总到该 issue #748
