### ISSUE TITLE
[QUESTION]你好再次求证php扩展

### ISSUE THREAD

**Issue by haiwan-xm** [1Panel-dev/1Panel#2720]
### 请描述您的问题

我确实下拉有看到rrdtool 
但是我安装完他没有rrd
版本信息
PHP版本：7.2.34
已安装扩展
Core=7.2.34
date=7.2.34
libxml=7.2.34
openssl=7.2.34
pcre=7.2.34
sqlite3=7.2.34
zlib=7.2.34
ctype=7.2.34
curl=7.2.34
dom=20031129
fileinfo=1.0.5
filter=7.2.34
ftp=7.2.34
hash=1.0
iconv=7.2.34
json=1.6.0
mbstring=7.2.34
SPL=7.2.34
PDO=7.2.34
pdo_sqlite=7.2.34
session=7.2.34
posix=7.2.34
readline=7.2.34
Reflection=7.2.34
standard=7.2.34
SimpleXML=7.2.34
Phar=2.0.2
tokenizer=7.2.34
xml=7.2.34
xmlreader=7.2.34
xmlwriter=7.2.34
mysqlnd=mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $
cgi-fcgi=
snmp=0.1
sodium=7.2.34
ssh2=1.1.2

我使用bt编译的 就 会显示
<html>
<body>

已加载 | Core date libxml openssl pcre sqlite3 zlib bcmath ctype curl dom filter ftp gd gettext hash iconv intl json mbstring SPL session pcntl standard PDO mysqlnd pdo_sqlite Phar posix Reflection pdo_mysql shmop SimpleXML soap sockets mysqli sysvsem tokenizer xml xmlreader xmlrpc xmlwriter zip ssh2 rrd
-- | --

</body>
</html>

**Comment by haiwan-xm** [comment]
镜像 build 失败:failed to solve: process "/bin/sh -c chmod +x install.sh && sh install.sh" did not complete successfully: exit code: 1

**Comment by wanghe-fit2cloud** [comment]
好的，我们在本地环境复现一下该问题。

**Comment by haiwan-xm** [comment]
另外还遇到一个场景问题不知道如何使用
1p是使用docker模式
bt   就是all in one 模式
我在机器内安装的 ipmitool  工具   再 使用1p 下似乎无法调研

**Comment by zhengkunwang223** [comment]
您好 我们支持的扩展列表中没有查到 rrdtool 
https://1panel.cn/docs/user_manual/websites/php/#php_1
