### ISSUE TITLE
[FEATURE]需要方便快捷的设置ipv6绑定访问

### ISSUE THREAD

**Issue by ZhangSir9901** [1Panel-dev/1Panel#2722]
### 1Panel 版本

1.7.4

### 请描述您的需求或者改进建议

需要方便快捷的设置ipv6绑定访问

**Comment by wanghe-fit2cloud** [comment]
可以更详细的再描述一下上述需求。
> 是准备在面板设置中增加 1Panel 端口绑定 IPv6 的设置吗？

**Comment by ZhangSir9901** [comment]
是的。现在ip4动不动就被墙了。很恶心的。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
