### ISSUE TITLE
[QUESTION]能否在文件中找到证书管理的证书文件

### ISSUE THREAD

**Issue by everleek** [1Panel-dev/1Panel#2723]
### 请描述您的问题

现在需要将证书管理里的证书（多个证书）同步到其他服务器，请问哪个文件可以找到所有证书文件？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
当前版本可以进入证书详情页面，查看证书、私钥等。后续版本支持导入、导出证书等需求。

**Comment by everleek** [comment]
最好存放在一个文件夹及子文件夹。这样如果需要使用或者和其他服务器同步，我只需要操作这个文件夹。

另外，你们这面板很多设计都太依赖自己数据库了，耦合太重了，不方便 mod。设计理念应该以应用原生配置为基础，UI只是原生应用可视化表达，非必要不冗余应用数据。不然的话随便 mod 一下应用配置和数据，面板就数据脱节，吃瘪了。

**Comment by liesauer** [comment]
同样有需求，能否能通过api、命令行、直接读取文件的方式获取到呢？
我服务器有一个独立的websocket服务，需要用到证书文件，由于证书是定期续签的，所以我需要一个完全自动化的方式定期获取到证书（或者有一个固定的目录可以直接读取），并更新wss。

**Comment by zyyfit** [comment]
1.9.0 增加了证书下载功能和申请证书时保存证书文件功能

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
