### ISSUE TITLE
希望新增一下命令行管理的分组以及自建docker镜像的分组管理[FEATURE]

### ISSUE THREAD

**Issue by isrun** [1Panel-dev/1Panel#2725]
### 1Panel 版本

v1.7.4

### 请描述您的需求或者改进建议

随着使用时间增多。越来越多的镜像和命令。需要分组管理，才方便赛选查看运行状态与使用。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持命令分组管理。

**Comment by zyyfit** [comment]
1.8.0 版本增加了快速命令分组

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
