### ISSUE TITLE
[BUG]登录成功闪退出来

### ISSUE THREAD

**Issue by fjk0618** [1Panel-dev/1Panel#2726]
### 联系方式

fjk0618@gmail.com

### 1Panel 版本

lastest

### 问题描述

登录的时候，使用了Win11下的chrome、360极速安全浏览器、手机版的Safari，分别通过浏览器保存的密码、手动输入账号密码，均无法登录，一登录进去就闪退回登录页面

### 重现步骤

登录的时候，使用了Win11下的chrome、360极速安全浏览器、手机版的Safari，分别通过浏览器保存的密码、手动输入账号密码，均无法登录，一登录进去就闪退回登录页面。
网络环境：使用了全局VPN，客户端v2ray。

### 附加信息

https://github.com/1Panel-dev/1Panel/assets/35111141/f92e951d-7753-459c-9b31-caa368c4d180

https://github.com/1Panel-dev/1Panel/assets/35111141/c837caea-5c2e-45a8-9aa0-26482cd1ebd1

**Comment by fjk0618** [comment]
继续补充bug。1panel的在线文本编辑器，无法打开GB2312文件，乱码。因现在无法登录1panle，顾无法 提供截图。

**Comment by wanghe-fit2cloud** [comment]
两个问题：
1、使用 ip:port 方式登录是否正常？
2、使用1Panel 自带网站功能，创建 1Panel 反向代理是否正常？

**Comment by fjk0618** [comment]
> 两个问题： 1、使用 ip:port 方式登录是否正常？ 2、使用1Panel 自带网站功能，创建 1Panel 反向代理是否正常？

1、ip:port的时候正常
2、反代看起来正常，毕竟登陆页能打开

**Comment by wanghe-fit2cloud** [comment]
> 反代看起来正常

在本地环境通过 1Panel 的网站功能创建的反向代理，未复现上述问题。
> 你是通过自己的 Nginx 来反代的吗？

**Comment by fjk0618** [comment]
> > 反代看起来正常
> 
> 在本地环境通过 1Panel 的网站功能创建的反向代理，未复现上述问题。
> 
> > 你是通过自己的 Nginx 来反代的吗？

不是，通过1panel里面一键安装的OpenResty来进行的反代。
反代配置信息。
location ^~ / {
    proxy_pass http://127.0.0.1:37473/; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_http_version 1.1; 
    add_header X-Cache $upstream_cache_status; 
    proxy_ignore_headers Set-Cookie Cache-Control expires; 
    proxy_cache proxy_cache_panel; 
    proxy_cache_key $host$uri$is_args$args; 
    proxy_cache_valid 200 304 301 302 10m; 
    if ( $uri ~* "\.(gif|png|jpg|css|js|woff|woff2)$" ) {
        expires 1m; 
    }
}
    
我最开始的配置是proxy_pass http://127.0.0.1:37473; 然后你们最近才改成proxy_pass http://127.0.0.1:37473/;

**Comment by wanghe-fit2cloud** [comment]
暂时先关闭这个 issue 了，如果升级至最新版本仍然有上述问题可以再打开或者回复。

**Comment by xiyaowong** [comment]
这个问题还是存在，时好时坏，玄学。。
