### ISSUE TITLE
[BUG]概览部分展开后的挂载点信息控件大小与其他送显的挂载点控件大小不一致

### ISSUE THREAD

**Issue by lfhy** [1Panel-dev/1Panel#2728]
### 联系方式

821923589@qq.com

### 1Panel 版本

v1.7.4

### 问题描述

# 展开后的控件大小和展开前的控件大小不一致
- 展开前

![1629522872](https://github.com/1Panel-dev/1Panel/assets/17682328/d472a1cd-3d37-4e8a-ba98-db1daf562c6c)
- 展开后

<img width="1999" alt="QQ20231031-082204@2x" src="https://github.com/1Panel-dev/1Panel/assets/17682328/d6f5cd33-9413-492c-a150-f039f60ce6f7">

### 重现步骤

登陆进入面板概览，在状态中点击更多时发现
<img width="2001" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/17682328/c883f2ca-90c5-4ff6-860d-d59c30e4ad1f">

### 期待的正确结果

控件大小一致

### 附加信息

浏览器：Edge  118.0.2088.57 
分辨率：3008x1692
缩放：100%

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们也在本地环境复现一下上述问题。

> 在 Chrome 和 Firefox 等浏览器是否也会出现上述问题？

**Comment by lfhy** [comment]
> 感谢反馈，我们也在本地环境复现一下上述问题。
> 
> > 在 Chrome 和 Firefox 等浏览器是否也会出现上述问题？

在Chrome和Firefox下也会出现哦
- Chrome 版本  118.0.5993.118
![image](https://github.com/1Panel-dev/1Panel/assets/17682328/6b696d40-9633-4134-8fe5-672c1938d94d)
- Firefox 版本 91.12.0esr 
![image](https://github.com/1Panel-dev/1Panel/assets/17682328/c4f541ea-c131-4550-815f-0b1ca43aabfc)

**Comment by wanghe-fit2cloud** [comment]
收到，我们先在本地环境复现一下。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
