### ISSUE TITLE
[FEATURE]建议修改ssh端口时，自动防火墙开放修改的端口

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#2729]
### 1Panel 版本

v1.7

### 请描述您的需求或者改进建议

建议修改ssh端口时，自动防火墙开放修改的端口，不然还得手动去开放一下才能登陆。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个功能版本支持同步修改防火墙端口。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
