### ISSUE TITLE
[FEATURE]希望更新一下memos

### ISSUE THREAD

**Issue by ReidLiao** [1Panel-dev/1Panel#2746]
### 1Panel 版本

v1.7.4

### 请描述您的需求或者改进建议

目前memos仓库最新版本是v0.17.0，应用商店还在v0.16.1，希望更新一下

**Comment by zhengkunwang223** [comment]
已经更新 等待下个版本一并发布

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
