### ISSUE TITLE
部署的应用暴露多个端口后，映射关系显示不全[BUG]

### ISSUE THREAD

**Issue by plateauandsp** [1Panel-dev/1Panel#2748]
### 1Panel 版本

v1.7.4

### 问题描述

采用1P部署了Gitea应用，此应用会暴露3000和222端口。如下：
![fc0ccc23f6f37dca2f995c7334b05d3](https://github.com/1Panel-dev/1Panel/assets/30932762/a2372c1c-3b13-44a8-a18a-a5f646b631bb)
但是在1P的容器管理界面中只显示了暴露222端口。
![Uploading dc1f8455efd98f145efdc036b954478.png…]()

### 重现步骤

无

### 期待的正确结果

能够正确显示所有的端口

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们将在近期版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
