### ISSUE TITLE
[BUG]登录页面出现乱码，登录之后控制台页面也有乱码。

### ISSUE THREAD

**Issue by hsjgit** [1Panel-dev/1Panel#2749]
### 1Panel 版本

v1.7.4-alpha.1

### 问题描述

登录接口判断账号密码正确之后直接更新了使用提交的字符串更新了数据库的Language
```golang
if err = settingRepo.Update("Language", info.Language); err != nil {
		return nil, err
	}
```
登录页面出现乱码，登录之后控制台页面也有乱码。

### 重现步骤

1. 进入https://demo.1panel.cn/
2. 打开网页控制台，填上账号密码
3. 选中https://demo.1panel.cn/api/v1/auth/login然后copy as cURL
4. 将copy的结果导入到postman 修改Body参数，将language改为任何随机的字符串比如"dsadsa"
5. 回到1panel 刷新会看到乱码,如果没有出现就刷新或者退出登录页面也会出现乱码

![image](https://github.com/1Panel-dev/1Panel/assets/32933584/43d91e85-ac86-452a-b601-068fff918b17)

![image](https://github.com/1Panel-dev/1Panel/assets/32933584/70420207-bd4b-4de7-b760-519423967cf8)

**Comment by zyyfit** [comment]
感谢反馈，1.8.0 版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
