### ISSUE TITLE
Docker创建存储卷支持挂载NFS和SMB

### ISSUE THREAD

**Issue by SR810** [1Panel-dev/1Panel#275]
### 1Panel 版本

1.0.1

### 请描述您的需求或者改进建议

Docker创建存储卷支持挂载NFS和SMB，portainer是有这个功能的

### 附加信息

![95679c86e45c81f1a52e18aaad8752d](https://user-images.githubusercontent.com/34358345/225854403-6dc11ae4-71c2-4efb-a094-9a4ffa71389e.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会支持该功能。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
