### ISSUE TITLE
[FEATURE] 建议在压缩文件的页面添加终端执行状态窗口

### ISSUE THREAD

**Issue by TheSmallHanCat** [1Panel-dev/1Panel#2755]
### 1Panel 版本

V1.5.5

### 请描述您的需求或者改进建议

在“文件”一栏中对某些比较大的文件夹执行压缩的时候，会因为长时间未响应弹出超时的警告，无法判断文件的压缩状态，同时也不利于用户查看压缩是否完成或失败。

建议添加在点击压缩“确认”按钮后调用终端窗口，显示压缩过程状态以保证活跃，同时也便于用户查看压缩情况。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本优化上述功能。

**Comment by wanghe-fit2cloud** [comment]
最新版本已经支持在文件列表页面直接跳转到主机终端。
如果是大文件，可以直接跳转到终端后再来手动命令解压缩。
