### ISSUE TITLE
[RESOLVED]反代一直提示：502 bad gateway

### ISSUE THREAD

**Issue by siutung** [1Panel-dev/1Panel#2757]
### 1Panel 版本

1.7.4

### 请描述您的需求或者改进建议

把站点反代到gg，一直提示502 bad gateway.

配置文件内容：
location ^~ / {
    proxy_pass https://www.google.com; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header Cache-Control no-cache; 
}

站点访问日志没发现异常，也没开启WAF功能。

以下是站点访问日志：
1.2.3.4 - - [01/Nov/2023:13:39:32 +0800] "GET / HTTP/2.0" 502 556 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.76"
1.2.3.4 - - [01/Nov/2023:13:39:33 +0800] "GET /favicon.ico HTTP/2.0" 502 556 "https://www.abc.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.76"
1.2.3.4 - - [01/Nov/2023:13:39:36 +0800] "GET / HTTP/2.0" 502 556 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.76"
1.2.3.4 - - [01/Nov/2023:13:39:37 +0800] "GET /favicon.ico HTTP/2.0" 502 556 "https://www.abc.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.76"
1.2.3.4 - - [01/Nov/2023:13:39:39 +0800] "GET / HTTP/2.0" 502 556 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.76"
1.2.3.4 - - [01/Nov/2023:13:39:40 +0800] "GET /favicon.ico HTTP/2.0" 502 556 "https://www.abc.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.76"
1.2.3.4 - - [01/Nov/2023:13:39:42 +0800] "GET / HTTP/2.0" 502 556 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.76"
1.2.3.4 - - [01/Nov/2023:13:39:43 +0800] "GET /favicon.ico HTTP/2.0" 502 556 "https://www.abc.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.76"

是我配置不对，还是本身就不支持反代到gg呢？以前用bt没这个问题的。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by siutung** [comment]
@wanghe-fit2cloud 处理好了，不是1panel的问题。
谢谢！

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
