### ISSUE TITLE
[QUESTION]卡在镜像制作中

### ISSUE THREAD

**Issue by raylenzed** [1Panel-dev/1Panel#2761]
### 请描述您的问题

我使用的PHP环境，新增了PHP扩展，然后重新构建的时候一直卡在镜像制作中。

我搜索了一下，配置了docker加速，依旧是镜像制作中，然后重启服务器，打开1panel还是镜像制作中，这个如何终止？

**Comment by raylenzed** [comment]
![WX20231101-151948@2x](https://github.com/1Panel-dev/1Panel/assets/72650962/4d908436-015c-476c-ad65-2ae7390f5a8c)

**Comment by wanghe-fit2cloud** [comment]
可以进入运行环境目录，查看一下构建日志：
> 也可以执行 `docker-compose build` 命令查看。

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/e6cac3ac-3ff0-47b3-92b6-cb1fff1a6a0e)

我们会在后续版本中持续优化，包括支持在页面中实时查看构建日志等。

**Comment by raylenzed** [comment]
好的，谢谢，我试试

**Comment by humanfans** [comment]
你制作成功了吗

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
