### ISSUE TITLE
[FEATURE]现在应用安装有允许端口外部访问会放开防火墙端口的功能，希望创建容器里也增加一个

### ISSUE THREAD

**Issue by 357341051** [1Panel-dev/1Panel#2762]
### 1Panel 版本

1.7.4

### 请描述您的需求或者改进建议

现在应用安装有允许端口外部访问会放开防火墙端口的功能，希望创建容器里也增加一个

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前 Linux 防火墙 firewalld 或者 ufw 暂无法禁用 Docker 端口映射，我们会在后续版本调研相关方案，看如何支持。
