### ISSUE TITLE
[FEATURE]希望增加hexo应用安装

### ISSUE THREAD

**Issue by ReidLiao** [1Panel-dev/1Panel#2766]
### 1Panel 版本

v1.7.4

### 请描述您的需求或者改进建议

希望增加hexo应用安装,以及Qexo,https://github.com/Qexo/Qexo

**Comment by zhengkunwang223** [comment]
好的 我们先调研一下

**Comment by wanghe-fit2cloud** [comment]
可以通过 [第三方应用商店](https://github.com/okxlin/appstore) 来安装上述应用。
> 经讨论，官方暂无适配上述应用计划，望理解。
