### ISSUE TITLE
[FEATURE]新增SSL证书文件下载

### ISSUE THREAD

**Issue by xaswq** [1Panel-dev/1Panel#2767]
### 1Panel 版本

v1.7.4

### 请描述您的需求或者改进建议

目前证书需要点击详情，然后复制粘贴，无法直接点击下载

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/85377380/4a9dfc7a-5c15-49a9-82e1-5692a8ae2d87)

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本增加此功能

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
