### ISSUE TITLE
[BUG]80端口和443端口有冲突

### ISSUE THREAD

**Issue by 357341051** [1Panel-dev/1Panel#2768]
### 1Panel 版本

1.7.4

### 问题描述

![13db6d37c71d91f0b5622a543cfc3ff](https://github.com/1Panel-dev/1Panel/assets/118408640/43b6454e-1597-435f-9db3-4aa4dec425b3)
首先是本地电脑虚拟机搭建的，我把80和443分别改成了888和999，然后在网站上绑定了888端口的域名，加了https证书，直接访问999端口，访问失败
![ec3fcc82fa9579b72c8e26cd88604e9](https://github.com/1Panel-dev/1Panel/assets/118408640/5275c219-3c9f-424b-80b8-4f4a55ade0f3)
然后，我就去域名增加一个999端口，一直提示端口占用，
![d703275914bd641fc16f3e601781187](https://github.com/1Panel-dev/1Panel/assets/118408640/fc58f0ed-389a-48f6-b9d9-0561529d683c)
![d038c31c15b960a8d9fc6f4e3fc9fec](https://github.com/1Panel-dev/1Panel/assets/118408640/a1745f55-7584-48f0-8f32-93e1096e9412)
现在唯一能解决的是，把999端口直接改成888端口，才能正常访问，
![image](https://github.com/1Panel-dev/1Panel/assets/118408640/0998ef68-7489-428e-b24c-d76b105c9e21)

### 重现步骤

![13db6d37c71d91f0b5622a543cfc3ff](https://github.com/1Panel-dev/1Panel/assets/118408640/43b6454e-1597-435f-9db3-4aa4dec425b3)
首先是本地电脑虚拟机搭建的，我把80和443分别改成了888和999，然后在网站上绑定了888端口的域名，加了https证书，直接访问999端口，访问失败
![ec3fcc82fa9579b72c8e26cd88604e9](https://github.com/1Panel-dev/1Panel/assets/118408640/5275c219-3c9f-424b-80b8-4f4a55ade0f3)
然后，我就去域名增加一个999端口，一直提示端口占用，
![d703275914bd641fc16f3e601781187](https://github.com/1Panel-dev/1Panel/assets/118408640/fc58f0ed-389a-48f6-b9d9-0561529d683c)
![d038c31c15b960a8d9fc6f4e3fc9fec](https://github.com/1Panel-dev/1Panel/assets/118408640/a1745f55-7584-48f0-8f32-93e1096e9412)
现在唯一能解决的是，把999端口直接改成888端口，才能正常访问，
![image](https://github.com/1Panel-dev/1Panel/assets/118408640/0998ef68-7489-428e-b24c-d76b105c9e21)

**Comment by zhengkunwang223** [comment]
检查一下防火墙

**Comment by wanghe-fit2cloud** [comment]
暂时先关闭这个 issue 了，如果升级至最新版本仍然有上述问题可以再打开或者回复。
