### ISSUE TITLE
[BUG] 扫过一眼就关issue？不行咱还用回BT... 确定不是BUG??? #2747

### ISSUE THREAD

**Issue by gowy222** [1Panel-dev/1Panel#2770]
### 1Panel 版本

1.7.4

### 问题描述

https://github.com/1Panel-dev/1Panel/issues/2747
![image](https://github.com/1Panel-dev/1Panel/assets/52201479/6fcecc1f-31f9-4b3a-a66e-26c9a718c95f)
倒是出来解释一下，这个11点半的任务。为何开机执行了？

### 重现步骤

断电开机，就这么简单。

**Comment by wanghe-fit2cloud** [comment]
你上一条 issue 我们已经有人回复、解答，请你查看具体评论后再做回复。
> 至于选择什么软件，这点我们没有权利限制。
