### ISSUE TITLE
[BUG]无法通过DNS账号验证(DnsPod)方式创建三级泛域名SSL证书

### ISSUE THREAD

**Issue by Xiaobin2333** [1Panel-dev/1Panel#2771]
### 1Panel 版本

v1.7.4

### 问题描述

无法通过DNS账号验证(DnsPod)方式创建三级泛域名SSL证书，并遭遇访问1Panel面板域名的解析记录被删除。

1Panel面板域名：hk.demo.com
申请SSL证书域名：*.xxx.demo.com

DnsPod日志：
![image](https://github.com/1Panel-dev/1Panel/assets/59763071/92a431c9-9ec3-4984-b5d3-dfa30eb5d6ff)
DnsPod日志显示添加TXT记录的域名为1Panel面板域名，并不是所申请SSL证书的三级泛域名。

### 重现步骤

1.创建三级泛域名SSL证书，*.xxx.demo.com
2.出现报错：
`服务内部错误: error: one or more domains had a problem: [*.xxx.demo.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: No TXT record found at _acme-challenge.xxx.demo.com
`

### 相关日志输出

```shell
2023/11/02 10:39:26 [INFO] acme: Trying to resolve account by key
2023/11/02 10:39:26 [INFO] [*.xxx.demo.com] acme: Obtaining bundled SAN certificate
2023/11/02 10:39:27 [INFO] [*.xxx.demo.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/xxx
2023/11/02 10:39:27 [INFO] [*.xxx.demo.com] acme: use dns-01 solver
2023/11/02 10:39:27 [INFO] [*.xxx.demo.com] acme: Preparing to solve DNS-01
2023/11/02 10:39:29 [INFO] [*.xxx.demo.com] acme: Trying to solve DNS-01
2023/11/02 10:39:29 [INFO] [*.xxx.demo.com] acme: Checking DNS record propagation using [8.8.8.8:53]
2023/11/02 10:39:31 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2023/11/02 10:39:35 [INFO] [*.xxx.demo.com] acme: Cleaning DNS-01 challenge
2023/11/02 10:39:38 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/xxx
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by zhengkunwang223** [comment]
当前版本 v1.9.2 没有复现此问题
你升级到 v1.9.2 再试一下

**Comment by wanghe-fit2cloud** [comment]
暂时先关闭该 Issue 了，后续如果还有问题再继续讨论。
