### ISSUE TITLE
[FEATURE]文件管理模块

### ISSUE THREAD

**Issue by ozshen** [1Panel-dev/1Panel#2776]
### 1Panel 版本

1.7.4

### 请描述您的需求或者改进建议

个人觉得文件管理模块其实可以统一设计，如果后续有计划增加OSS文件管理就可以统一操作，毕竟站点少有不使用类OSS的功能，某些资源文件也能统一管理，1p用户依赖度会更高。
暗黑模式下这个高亮度bar是什么鬼...
![image](https://github.com/1Panel-dev/1Panel/assets/14324029/22d90c16-1a9e-44c8-aeec-bb6c9f5b4b3e)

### 请描述你建议的实现方案

文件管理nav统一成如下设计后，OSS资源操作就能套用部分文件管理的代码，可参照oss-browser。
![image](https://github.com/1Panel-dev/1Panel/assets/14324029/47a1468d-f054-4331-9972-52a35f9a2614)
再者面板设置中也可以增加云存储id相关的设置，同样也能复用现有的“备份账号”功能使用的云存储curd代码。
![image](https://github.com/1Panel-dev/1Panel/assets/14324029/1df1e9f5-56c2-445c-bc1e-8a10e4844040)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们在中短期应该不会考虑增加 OSS 文件管理功能，望理解。

> 暗黑模式下，文件管理显示问题会在近期版本修复。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
