### ISSUE TITLE
[FEATURE]未来会计划对go部署吗

### ISSUE THREAD

**Issue by haiwan-xm** [1Panel-dev/1Panel#2782]
### 1Panel 版本

1.7.4

### 请描述您的需求或者改进建议

什么时候可以支持下支持下go项目部署

**Comment by qwenode** [comment]
可以使用1p的 supervisor,相当于单文件的网站部署, 也很方便, 或者将go打包docker 一键部署

**Comment by wanghe-fit2cloud** [comment]
> 可以使用1p的 supervisor,相当于单文件的网站部署, 也很方便, 或者将go打包docker 一键部署

正解。
