### ISSUE TITLE
[FEATURE] 希望可以增加 从当前路径打开终端 功能

### ISSUE THREAD

**Issue by qwenode** [1Panel-dev/1Panel#2784]
### 1Panel 版本

1.7.4

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/8974108/2d2dd1bf-9b36-43ce-90a3-843ac6c1c20c)

希望可以增加 从当前路径打开终端 功能,类似appnode 的,这个功能很方便

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本支持上述功能。

**Comment by wanghe-fit2cloud** [comment]
重复 #958
