### ISSUE TITLE
[BUG]终端 - 主机 127.0.0.1 前端限制无法修改或者删除

### ISSUE THREAD

**Issue by wojiushixiaobai** [1Panel-dev/1Panel#2785]
### 1Panel 版本

v1.7.4

### 问题描述

宿主更新密码后，由于 1Panel 无法更新密码或者删除主机，导致无法使用。
![image](https://github.com/1Panel-dev/1Panel/assets/24326988/ec7a7794-47c0-4343-adbf-e966ca0df488)

看了下更新限制只是简单的前端限制，希望去掉这部分限制。或者系统全自动处理这块

### 重现步骤

1. 在 1Panel 面板 终端 - 主机创建 127.0.0.1 主机
2. 修改宿主机密码
3. 在 1Panel 面板 终端连接主机

**Comment by qwenode** [comment]
要先点击 连接测试 ,然后才可以点击 确认 进行保存

**Comment by wojiushixiaobai** [comment]
@qwenode 牛逼，还真是。学会了
