### ISSUE TITLE
[QUESTION]拉取docker失败

### ISSUE THREAD

**Issue by haiwan-xm** [1Panel-dev/1Panel#2787]
### 请描述您的问题

docker pull cloudflare/cloudflared:latest
我想拉取这个docker
提示 pull faile 
请问是我操作不对吗

**Comment by wanghe-fit2cloud** [comment]
应该是你服务器网络问题，可以考虑配置镜像加速。
> 1Panel 的 `容器` - `配置` 页面支持
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/c22a7a84-0534-43ba-bf23-f69d8530a469)

**Comment by haiwan-xm** [comment]
我就是使用的国际网络 我是在1p的面板拉取
