### ISSUE TITLE
[FEATURE]希望增加一种计划任务执行周期，间隔N秒没有收到续期请求时触发执行，谢谢

### ISSUE THREAD

**Issue by isxuew** [1Panel-dev/1Panel#2793]
### 1Panel 版本

1.7.4

### 请描述您的需求或者改进建议

希望增加一种计划任务执行周期，间隔N秒没有收到续期请求时触发执行

### 请描述你建议的实现方案

开启该类型计划任务后提供一个续期接口，由外部心跳进行延期；在指定的时间间隔没有收到外部请求后，触发执行shell等配置的具体操作

### 附加信息

很实用的功能，感激不尽

**Comment by xhwsd** [comment]
这好像是业务吧

**Comment by isxuew** [comment]
> 这好像是业务吧

使用场景的话，比如监测发现自己被墙了，触发更新ip；
比如两个服务器互相监测在线，使用shell告警；

**Comment by wanghe-fit2cloud** [comment]
是否可以通过 `Shell 脚本` 类型计划任务来实现上述需求。

**Comment by gowy222** [comment]
写个sh脚本。dockerfile做个镜像，最多7MB大小...

**Comment by isxuew** [comment]
写个服务当然可以实现，计划任务本身crontab也都可以做，MySQL什么的直接用Docker也都可以装；可更加易用，就是面板的意义啊？
