### ISSUE TITLE
[FEATURE]希望提供cdn配置选项

### ISSUE THREAD

**Issue by shuTwT** [1Panel-dev/1Panel#280]
### 1Panel 版本

1.0.1

### 请描述您的需求或者改进建议

服务器2核2G5M
小水管首屏加载花费3-6s，切换也很慢
前端使用了vue，element-plus,echarts等库，体积偏大。
希望在面板设置或者命令中提供cdn开关或者配置选项，以供外网访问时加速
如果我的服务器太垃圾了，请无视这条issue

### 请描述你建议的实现方案

添加cdn选项

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会讨论该方案等可行性。

**Comment by wanghe-fit2cloud** [comment]
经团队内部讨论，暂无支持上述功能的计划，望理解。
