### ISSUE TITLE
[FEATURE]wordpress主题激活需要引入extension=loader81.so我添加了也没用

### ISSUE THREAD

**Issue by sansejin1206** [1Panel-dev/1Panel#2800]
### 1Panel 版本

v1.7.4

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/64347551/4edabef5-7031-4fce-a2e8-7ee274f26314)
我使用的wordpress主题必须要求修改php.ini文件添加extension=loader81.so才能激活我把它填入到php配置文件不生效。看论坛上有挂载的方法，还有其他方法都试了没用。害卡了三天。真的要重新用回宝塔linux吗？

### 请描述你建议的实现方案

希望能解释下为什么不生效呢？

**Comment by wanghe-fit2cloud** [comment]
论坛中已经有网友提供了相关资料，可以参考：
https://bbs.fit2cloud.com/t/topic/1985

> 要注意的一点是 1Panel 采用容器化方案部署 PHP 网站。

在接下来的版本中，我们会调研如何支持自定义 PHP 扩展到需求。

**Comment by sansejin1206** [comment]
大佬们 有没有能出个教程视频的 我一定三连加关注 这个教程我试了  还是不行

**Comment by zhengkunwang223** [comment]
> 大佬们 有没有能出个教程视频的 我一定三连加关注 这个教程我试了 还是不行

https://bbs.fit2cloud.com/t/topic/2073/5
