### ISSUE TITLE
[BUG] Ubuntu 22.04 防火墙启动失败

### ISSUE THREAD

**Issue by kangfenmao** [1Panel-dev/1Panel#2811]
### 联系方式

kangfenmao@qq.com

### 1Panel 版本

v1.7.4

### 问题描述

防火墙模块点击启动会启动失败，但通过命令行可以正常启动

<img width="923" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/8253512/37f66478-2c96-4638-8d94-eedd1a85ca64">

### 重现步骤

1. 防火墙模块点击启动会启动失败
2. 使用 shell 启动可以启动成功，`ufw enable` 手动确认输入 y 启动成功
3. shell 启动后通过网站可以正常关闭
4. 通过网站关闭后，再次点击启动，启动失败

判断可能是启动命令有误，应该使用 `ufw --force enable` 避免手动确认

### 期待的正确结果

通过网站启动成功

### 相关日志输出

```shell
root@webserver:/home/ubuntu# ufw enable
Command may disrupt existing ssh connections. Proceed with operation (y|n)? y
Firewall is active and enabled on system startup
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地 Ubuntu 22.04 环境复现一下上述问题。

**Comment by ssongliu** [comment]
麻烦提供一下日志审计中的 【日志审计】-【面板日志】-【系统日志】信息。

**Comment by kangfenmao** [comment]
> 麻烦提供一下日志审计中的 【日志审计】-【面板日志】-【系统日志】信息。

操作日志里面有失败记录，系统日志没有这个信息。我刚刚重新操作了一下，系统日志没有输出新的内容。

**Comment by kangfenmao** [comment]
POST: /api/v1/hosts/firewall/operate

```json
{
    "code": 500,
    "message": "服务内部错误: add port failed, err: stderr: ERROR: Bad port\n",
    "data": null
}
```

GET: /api/v1/hosts/firewall/base

```json
{
    "code": 200,
    "message": "",
    "data": {
        "name": "ufw",
        "status": "not running",
        "version": "0.36.1",
        "pingStatus": "Enable"
    }
}
```

<img width="1088" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/8253512/847bd9de-2471-452d-9715-0829cb30b2ca">

**Comment by ssongliu** [comment]
看起来应该是规则冲突了，再执行一下下列操作：
1.  ufw status 截图
2. 截图看一下已启用了哪些应用（启动防火墙的时候，会默认开启端口：22/tcp、1panel 服务端口、80/tcp、443/tcp 以及应用占用端口）
3. 方便的话可以扫码添加一下我微信，我远程看一下这个问题
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/f7442011-5f31-4132-9cb6-19ff4d4f7932)

**Comment by kangfenmao** [comment]
<img width="415" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/8253512/fa019cc5-10db-454f-9baf-ac44dc95512e">

@ssongliu

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
