### ISSUE TITLE
[BUG]数据库备份报错

### ISSUE THREAD

**Issue by whhya** [1Panel-dev/1Panel#2813]
### 联系方式

2458317501@qq.com

### 1Panel 版本

v1.7.4

### 问题描述

设置计划定时备份数据库；备份失败
![image](https://github.com/1Panel-dev/1Panel/assets/28398139/3db439b2-3e3c-4ce1-a567-b15e7917f56a)

### 重现步骤

正常添加计划任务

### 期待的正确结果

备份正常

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们先在本地环境复现一下上述问题（MinIO 备份账号）。
> 备份到本地是否正常？

**Comment by ssongliu** [comment]
这里是备份的远程数据库吧？错误是表结构和表数据没有对应上，方便加一下好友远程看一下吗？

或者导出 sql 后，去掉敏感数据发一下，我们复现一下这个问题。

**Comment by 1984anonymous** [comment]
从备份恢复数据 emoji 会乱码 怀疑是导出跟导入时的数据库编码 不一致 或许应该统一使用 utf8mb4 ？#2657

**Comment by 1984anonymous** [comment]
> 从备份恢复数据 emoji 会乱码 怀疑是导出跟导入时的数据库编码 不一致 或许应该统一使用 utf8mb4 ？#2657

自动备份出来的数据 emoji 就是会变成乱码

**Comment by wanghe-fit2cloud** [comment]
可以将 1Panel 升级到最新版本。
