### ISSUE TITLE
[QUESTION]1p安装我们自己的系统PHP   提示 Access denied.

### ISSUE THREAD

**Issue by haiwan-xm** [1Panel-dev/1Panel#2814]
### 请描述您的问题

我们再1p部署我们自己的系统的时候 
安装提示 Access denied.
也按照教程都处理了  保存了1000:1000权限
可是依旧不行 文件也没有.usr 这类的 
最后直接给了777 就正常了
在bt那边无此现象哦

**Comment by haiwan-xm** [comment]
另外我安装 Mysqli  一直也无法检测到

**Comment by zhengkunwang223** [comment]
既然 777 可以 那 Access denied  就是因为权限问题 ， 你可以截图 或者发到论坛

**Comment by haiwan-xm** [comment]
大家都说提issue的到这里

**Comment by zhengkunwang223** [comment]
> 大家都说提issue的到这里

哪里都行 我的意思是 你发一下截图 或者 视频之类的 方便我们排错

**Comment by haiwan-xm** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/45061573/947de928-66e3-44fe-ab63-f397211176e7)
![image](https://github.com/1Panel-dev/1Panel/assets/45061573/ff6f84cf-ffe2-4ddd-b992-7b3606a65022)
奇怪  又居然好了 
那现在就只剩下这个问题了 
mysqli
![image](https://github.com/1Panel-dev/1Panel/assets/45061573/de89f110-0ca2-4087-9d8a-701359ed8a0a)

**Comment by zhengkunwang223** [comment]
> ![image](https://user-images.githubusercontent.com/45061573/280739628-947de928-66e3-44fe-ab63-f397211176e7.png) ![image](https://user-images.githubusercontent.com/45061573/280739734-ff6f84cf-ffe2-4ddd-b992-7b3606a65022.png) 奇怪 又居然好了 那现在就只剩下这个问题了 mysqli ![image](https://user-images.githubusercontent.com/45061573/280740056-de89f110-0ca2-4087-9d8a-701359ed8a0a.png)

编辑运行环境的时候选一下 mysqli

**Comment by haiwan-xm** [comment]
我编辑php docker的有选择 可是 结果还是没有

**Comment by zhengkunwang223** [comment]
> 我编辑php docker的有选择 可是 结果还是没有

docker 什么版本

**Comment by wanghe-fit2cloud** [comment]
暂时先关闭这个 issue 了，如果升级至最新版本仍然有上述问题可以再打开或者回复。

**Comment by netstat2016** [comment]
最新版本。在openresty 界面設置 1000 1000 也是 Access denied

**Comment by MCWXT** [comment]
使用最新版本依然有这个问题

**Comment by zhengkunwang223** [comment]
> 使用最新版本依然有这个问题

参考 https://bbs.fit2cloud.com/t/topic/1069#h-4php-access-denied-4
