### ISSUE TITLE
[FEATURE] 提供 openresty reload 命令行工具

### ISSUE THREAD

**Issue by ichenhe** [1Panel-dev/1Panel#2815]
### 1Panel 版本

1.7.4

### 请描述您的需求或者改进建议

有时会在外部更新 openresty 配置（比如更新证书），希望更新后能自动重载。但因为 openrestry 运行在容器中，没有可靠的办法取得正确容器 id。

### 请描述你建议的实现方案

提供命令行工具，比如

```bash
1panel app openresty reload
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本支持上述功能。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
