### ISSUE TITLE
[BUG]docker页面的容器内存占用显示的数据好像不准啊, 还是 概览那边统计不准？

### ISSUE THREAD

**Issue by gowy222** [1Panel-dev/1Panel#2818]
### 1Panel 版本

1.7.4

### 问题描述

容器面板那边显示内存使用4.7GIB+(约等于 5.046 GB??), 首页概览显示整个服务器才2G+

![image](https://github.com/1Panel-dev/1Panel/assets/52201479/a37be2d1-081a-4624-b692-6e2c97f9333b)
![image](https://github.com/1Panel-dev/1Panel/assets/52201479/03b75da2-5129-4df6-b39d-03c7ec2257b0)
![image](https://github.com/1Panel-dev/1Panel/assets/52201479/c11198c7-2f24-4c64-9a42-71ab108e37de)

另外, 能不能直接换下docker这边的计量单位MB/GB? 更直观些...

### 重现步骤
直接看图...

**Comment by ssongliu** [comment]
感谢反馈！容器占用可以执行 docker stats 比较，概览页内存占用可以执行 free 比较。
暂时先关闭这个 issue 了，如果输出还是不一致可以再打开或者回复。
