### ISSUE TITLE
[FEATURE] 希望ftp与OpenResty的web路径关联

### ISSUE THREAD

**Issue by static7** [1Panel-dev/1Panel#2820]
### 1Panel 版本

v1.7.4

### 请描述您的需求或者改进建议

我看了一下 sftp 与 web服务器都是容器相互隔离的
我的需求:
再测试环境下
开发本地打包后 直接用ftp上传到web网站某个目录下.
直接上传到web目录的需求

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1Panel 目前采用容器化方案部署应用，不能满足上述需求。
> 可以考虑服务器手动安装 ftp 的方式来解决。
