### ISSUE TITLE
[BUG] 面板设置，安全，开启https后，无法访问

### ISSUE THREAD

**Issue by mi1890** [1Panel-dev/1Panel#2822]
### 1Panel 版本

1.7.4

### 问题描述

https加域名访问1panel，本身已经配置好了
目前https域名和ip均可以进入

开启 【HTTPS为面板设置 https 协议访问，提升面板访问安全性】 功能后后域名访问无效

文档里没找到对这个功能的帮助信息

![image](https://github.com/1Panel-dev/1Panel/assets/5334863/e5b271d3-9c38-473a-9934-34468e71ef83)

### 重现步骤

打开面板-安全-https，选择配置好的证书
之后就无法使用域名进行访问了

**Comment by ssongliu** [comment]
感谢反馈！已经配置好 https 的话，不需要再开启这个，直接在终端上执行 1pctl reset https 可以关闭。
