### ISSUE TITLE
[BUG] 挂载的外部硬盘samba无法访问时,会导致api超时

### ISSUE THREAD

**Issue by qwenode** [1Panel-dev/1Panel#2825]
### 1Panel 版本

1.7.4

### 问题描述

api:  /api/v1/dashboard/current/all/all

### 重现步骤

先挂载网络 samba 到任意目录, 让 1panel ->概览读到此硬盘

然后让外部samba掉线,刷新概览

/api/v1/dashboard/current/all/all 就会超时

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
我们尝试在 v1.8.4 版本增加了超时时间，可以更新 1Panel 版本后查看问题是否已修复。
