### ISSUE TITLE
[FEATURE]升级应用的时候，docker-compose配置增量修改

### ISSUE THREAD

**Issue by everleek** [1Panel-dev/1Panel#2826]
### 1Panel 版本

1.7.4

### 请描述您的需求或者改进建议

升级应用的时候，docker-compose 配置不要覆盖。增量修改。或者其他提示等。

### 请描述你建议的实现方案

不要整个配置覆盖，整个配置覆盖就搞了自己 MOD 后被覆盖了。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述需求。

**Comment by qwenode** [comment]
这个我觉得可以在已安装应用列表上的应用增加个 克隆/复制 功能, 点击后把当前应用复制为本地自制应用(key加个custom后缀等等, app名字后面自动加个自制), 然后支持下载复制后的应用,就解决了自己修改compose的问题,且不影响应用本体(本体可能来自官方,第三方等问题,肯定会被覆盖,或系统迁移后丢失等)

**Comment by zhengkunwang223** [comment]
> 这个我觉得可以在已安装应用列表上的应用增加个 克隆/复制 功能, 点击后把当前应用复制为本地自制应用(key加个custom后缀等等, app名字后面自动加个自制), 然后支持下载复制后的应用,就解决了自己修改compose的问题,且不影响应用本体(本体可能来自官方,第三方等问题,肯定会被覆盖,或系统迁移后丢失等)

现在的想法是在升级的时候给用户一个docker-compose文件前后对比，让用户选择用哪个版本的 docker-compose 文件

**Comment by mobeicanyue** [comment]
> 现在的想法是在升级的时候给用户一个docker-compose文件前后对比，让用户选择用哪个版本的 docker-compose 文件

请问这个进度如何了呢，整一个类似于 git diff 的比较就可以了。

**Comment by wanghe-fit2cloud** [comment]
> > 现在的想法是在升级的时候给用户一个docker-compose文件前后对比，让用户选择用哪个版本的 docker-compose 文件
> 
> 请问这个进度如何了呢，整一个类似于 git diff 的比较就可以了。

已经纳入近期版本迭代计划。

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。

**Comment by mobeicanyue** [comment]
> v1.10.10-lts 版本已发布。

你好，为什么现在更新应用又开始覆盖 compose 文件了，我更新 bitwarden 没有提示 diff 直接就更新了。

社区版
v1.10.23-lts

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> v1.10.10-lts version has been released.

Hello, why is the update application now starting to overwrite the compose file? I updated bitwarden without prompting diff and then updated directly.

Community Edition
v1.10.23-lts

**Comment by wanghe-fit2cloud** [comment]
> > v1.10.10-lts 版本已发布。
> 
> 你好，为什么现在更新应用又开始覆盖 compose 文件了，我更新 bitwarden 没有提示 diff 直接就更新了。
> 
> 社区版 v1.10.23-lts

<img width="754" alt="Image" src="https://github.com/user-attachments/assets/d9998fdb-2923-4ea1-a574-563c8b550371" />
