### ISSUE TITLE
[FEATURE] 暂时没有插件机制的开发提供吗

### ISSUE THREAD

**Issue by imblowsnow** [1Panel-dev/1Panel#283]
### 1Panel 版本

1

### 请描述您的需求或者改进建议

暂时没有插件机制的开发提供吗

**Comment by imblowsnow** [comment]
这边看  貌似 插件页面相关的都是写死在 front 里面了
后续插件的配置信息、页面展示等有木有考虑过

**Comment by zhengkunwang223** [comment]
您好，插件机制在我们的计划中，请关注我们的后续的 ROADMAP
