### ISSUE TITLE
[BUG]甲骨文arm服务器自动安装脚本只能绑定ipv6地址

### ISSUE THREAD

**Issue by XianTanLuoHua** [1Panel-dev/1Panel#2833]
### 联系方式

849317537@qq.com

### 1Panel 版本

v1.7.4

### 问题描述

通过官网安装脚本绑定了8888端口 但是通过ipv4地址:port访问不了
ubuntu@coder-rs:~$ netstat -nultp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::8888                 :::*                    LISTEN      -                   
tcp6       0      0 :::111                  :::*                    LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
udp        0      0 127.0.0.53:53           0.0.0.0:*                           -                   
udp        0      0 10.0.0.150:68           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:111             0.0.0.0:*                           -                   
udp6       0      0 :::111                  :::*                                -                 

### 重现步骤

none

**Comment by XianTanLuoHua** [comment]
net.ipv6.bindv6only = 0

用的ubuntu22.04

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
甲骨文云针对 bindv6only 参数做了加固，单纯修改它确实不能确保 tcp 地址访问。
> 1.8.0 版本会支持切换监听地址（预计本周三发布）

**Comment by XianTanLuoHua** [comment]
> 感谢反馈。 甲骨文云针对bindv6only所做的参数，简单修改确实不能保证tcp地址访问。
> 
> > 1.8.0版本会支持切换监听地址（预计本周三发布）

刚才开了一个x86的小鸡  也是这样的结果希望1.8 能够修复

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。

**Comment by XianTanLuoHua** [comment]
> v1.8.0 版本已发布。

1.8版本 我用arm或者x86的甲骨文小鸡都试了,   提示如下, 用的ubuntu 22.04

ubuntu@coder-rs:~$ curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sh quick_start.sh
quick_start.sh: 5: [[: not found
quick_start.sh: 7: [[: not found
quick_start.sh: 7: [[: not found
quick_start.sh: 9: [[: not found
quick_start.sh: 11: [[: not found
quick_start.sh: 13: [[: not found
暂不支持的系统架构，请参阅官方文档，选择受支持的系统。
