### ISSUE TITLE
[FEATURE]希望网站里能够新增负载均衡的配置

### ISSUE THREAD

**Issue by youtao531** [1Panel-dev/1Panel#2834]
### 1Panel 版本

v1.7.4

### 请描述您的需求或者改进建议

希望网站里能够新增负载均衡的配置。
例如：反向代理可以增加多个端口映射并配置权重；静态网站也可以增加映射到不同目录的权重；其它类型的网站也是同理。

### 请描述你建议的实现方案

反向代理：目前不能增加相同路径不同端口的代理，希望可以增加相同路径不同地址端口路径，并可配置权重。
其它网站类型类似配置。

**Comment by zhengkunwang223** [comment]
感谢建议 我们会考虑实现此功能

**Comment by youtao531** [comment]
这个有计划排期嘛

**Comment by wanghe-fit2cloud** [comment]
重复 #2058
