### ISSUE TITLE
希望终端能够提供颜色渲染，更改字体大小功能

### ISSUE THREAD

**Issue by miaowmint** [1Panel-dev/1Panel#284]
### 1Panel 版本

v1.0.1

### 请描述您的需求或者改进建议

现在的终端颜色太过单调，

而且不知道是字体的问题还是字体大小的问题，总感觉终端内的字有些模糊

![image](https://user-images.githubusercontent.com/58991169/225928562-e5b5db21-2e29-4204-affe-b9f7c0c035d3.png)

### 请描述你建议的实现方案

颜色渲染后的效果差不多是这种感觉
![image](https://user-images.githubusercontent.com/58991169/225929550-77b8ca12-6502-4222-8546-04d7ab440cdf.png)

至于感觉有些模糊的问题希望能够更改终端内的字体和大小

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会持续优化终端功能。

**Comment by wanghe-fit2cloud** [comment]
可以将 1Panel 升级至最新版本。
