### ISSUE TITLE
[BUG] 修改站点信息时 服务内部错误

### ISSUE THREAD

**Issue by forxiucn** [1Panel-dev/1Panel#2844]
### 1Panel 版本

v1.7.4

### 问题描述

创建站点、修改站点都报错，删除站点不报错。

### 重现步骤

创建站点、修改站点都报错，删除站点不报错。

### 相关日志输出

```shell
{"code":500,"message":"服务内部错误: ","data":null}
```

**Comment by zhengkunwang223** [comment]
什么类型的网站？ 操作了什么按钮？openresty 配置文件是否有错误？

**Comment by forxiucn** [comment]
> 什么类型的网站？ 操作了什么按钮？openresty 配置文件是否有错误？

站点类型：反向代理

之前站点都正常运行的，配置文件未见错误。升级面板版本后再来修改站点信息就报这个错误。

**Comment by zhengkunwang223** [comment]
> > 什么类型的网站？ 操作了什么按钮？openresty 配置文件是否有错误？
> 
> 站点类型：反向代理
> 
> 之前站点都正常运行的，配置文件未见错误。升级面板版本后再来修改站点信息就报这个错误。

说具体一点 修改哪个

**Comment by forxiucn** [comment]
> Collaborator



> > > 什么类型的网站？ 操作了什么按钮？openresty 配置文件是否有错误？
> > 
> > 
> > 站点类型：反向代理
> > 之前站点都正常运行的，配置文件未见错误。升级面板版本后再来修改站点信息就报这个错误。
> 
> 说具体一点 修改哪个

1. [网站]-[网站]-[网站列表]页面；
2. 我这里所有站点都是反向代理的，点击任意一个站点的[配置]按钮；
3. 在弹出的页面点击[反向代理]；
4. 在打开的页面再点击[编辑]按钮；
5. 在右侧弹出的抽屉对话框中修改[后端代理地址]，原：http://192.168.100.23:4443  修改为：http://192.168.100.6:4443
6. 点击右下角的[确认]按钮；
7. 5.39s后页面弹出“服务内部错误”消息提示Pop；
8. 这是复制的对应的请求内容：curl 'http://192.168.100.5:16856/api/v1/websites/proxies/update' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: zh' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%2218ae8f9fe1466d-0bf11c4dd181708-26031051-2073600-18ae8f9fe15c34%22%2C%22first_id%22%3A%22%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22url%E7%9A%84domain%E8%A7%A3%E6%9E%90%E5%A4%B1%E8%B4%A5%22%2C%22%24latest_search_keyword%22%3A%22url%E7%9A%84domain%E8%A7%A3%E6%9E%90%E5%A4%B1%E8%B4%A5%22%2C%22%24latest_referrer%22%3A%22url%E7%9A%84domain%E8%A7%A3%E6%9E%90%E5%A4%B1%E8%B4%A5%22%7D%2C%22identities%22%3A%22eyIkaWRlbnRpdHlfY29va2llX2lkIjoiMThhZThmOWZlMTQ2NmQtMGJmMTFjNGRkMTgxNzA4LTI2MDMxMDUxLTIwNzM2MDAtMThhZThmOWZlMTVjMzQifQ%3D%3D%22%2C%22history_login_id%22%3A%7B%22name%22%3A%22%22%2C%22value%22%3A%22%22%7D%2C%22%24device_id%22%3A%2218ae8f9fe1466d-0bf11c4dd181708-26031051-2073600-18ae8f9fe15c34%22%7D; _SSID=7B8fsHHSFWYVmbeiWzjLIgV3PsHZ2Ti4s48cQkqW6yU; stay_login=0; did=HEe7-H9Nj92kKknRhhlfLkNN2oxhyO21DMUGA8xhG6R6dxxw5npTJRo92o_5HcfzkSG9kNNVYwxfi7Q-lvK9ow; _CrPoSt=cHJvdG9jb2w9aHR0cDo7IHBvcnQ9NTAwMDsgcGF0aG5hbWU9Lzs%3D; ___rl__test__cookies=1699407517504; OUTFOX_SEARCH_USER_ID_NCOO=995174405.8005052; psession=542a7d58-1896-4f9f-b27e-8e1e3be1e3f5' \
  -H 'Origin: http://192.168.100.5:16856' \
  -H 'Referer: http://192.168.100.5:16856/websites/13/config/basic' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36' \
  --data-raw '{"id":13,"operate":"edit","enable":true,"cache":false,"cacheTime":0,"cacheUnit":"","name":"root","modifier":"^~","match":"/","proxyPass":"http://192.168.100.6:4443","proxyHost":"$host","content":"location ^~ / {\n    proxy_pass http://192.168.100.6:4443; \n    proxy_set_header Host $host; \n    proxy_set_header X-Real-IP $remote_addr; \n    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; \n    proxy_set_header REMOTE-HOST $remote_addr; \n    proxy_set_header Upgrade $http_upgrade; \n    proxy_set_header Connection \"upgrade\"; \n    proxy_set_header X-Forwarded-Proto $scheme; \n    proxy_http_version 1.1; \n    add_header X-Cache $upstream_cache_status; \n}","filePath":"/home/daoke/1panel/apps/openresty/openresty/www/sites/metabase.316.team/proxy/root.conf","replaces":{},"proxyProtocol":"http://","proxyAddress":"192.168.100.6:4443"}' \
  --compressed \
  --insecure

**Comment by forxiucn** [comment]
我点开其他任意一个站点，即使不修改任何内容点击[确认]按钮也会报这个错误。

**Comment by zhengkunwang223** [comment]
> > Collaborator
> 
> > > > 什么类型的网站？ 操作了什么按钮？openresty 配置文件是否有错误？
> > > 
> > > 
> > > 站点类型：反向代理
> > > 之前站点都正常运行的，配置文件未见错误。升级面板版本后再来修改站点信息就报这个错误。
> > 
> > 
> > 说具体一点 修改哪个
> 
> 1. [网站]-[网站]-[网站列表]页面；
> 2. 我这里所有站点都是反向代理的，点击任意一个站点的[配置]按钮；
> 3. 在弹出的页面点击[反向代理]；
> 4. 在打开的页面再点击[编辑]按钮；
> 5. 在右侧弹出的抽屉对话框中修改[后端代理地址]，原：http://192.168.100.23:4443  修改为：http://192.168.100.6:4443
> 6. 点击右下角的[确认]按钮；
> 7. 5.39s后页面弹出“服务内部错误”消息提示Pop；
> 8. 这是复制的对应的请求内容：curl 'http://192.168.100.5:16856/api/v1/websites/proxies/update' 
>      -H 'Accept: application/json, text/plain, _/_' 
>      -H 'Accept-Language: zh' 
>      -H 'Connection: keep-alive' 
>      -H 'Content-Type: application/json' 
>      -H 'Cookie: sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%2218ae8f9fe1466d-0bf11c4dd181708-26031051-2073600-18ae8f9fe15c34%22%2C%22first_id%22%3A%22%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22url%E7%9A%84domain%E8%A7%A3%E6%9E%90%E5%A4%B1%E8%B4%A5%22%2C%22%24latest_search_keyword%22%3A%22url%E7%9A%84domain%E8%A7%A3%E6%9E%90%E5%A4%B1%E8%B4%A5%22%2C%22%24latest_referrer%22%3A%22url%E7%9A%84domain%E8%A7%A3%E6%9E%90%E5%A4%B1%E8%B4%A5%22%7D%2C%22identities%22%3A%22eyIkaWRlbnRpdHlfY29va2llX2lkIjoiMThhZThmOWZlMTQ2NmQtMGJmMTFjNGRkMTgxNzA4LTI2MDMxMDUxLTIwNzM2MDAtMThhZThmOWZlMTVjMzQifQ%3D%3D%22%2C%22history_login_id%22%3A%7B%22name%22%3A%22%22%2C%22value%22%3A%22%22%7D%2C%22%24device_id%22%3A%2218ae8f9fe1466d-0bf11c4dd181708-26031051-2073600-18ae8f9fe15c34%22%7D; _SSID=7B8fsHHSFWYVmbeiWzjLIgV3PsHZ2Ti4s48cQkqW6yU; stay_login=0; did=HEe7-H9Nj92kKknRhhlfLkNN2oxhyO21DMUGA8xhG6R6dxxw5npTJRo92o_5HcfzkSG9kNNVYwxfi7Q-lvK9ow; _CrPoSt=cHJvdG9jb2w9aHR0cDo7IHBvcnQ9NTAwMDsgcGF0aG5hbWU9Lzs%3D; ___rl__test__cookies=1699407517504; OUTFOX_SEARCH_USER_ID_NCOO=995174405.8005052; psession=542a7d58-1896-4f9f-b27e-8e1e3be1e3f5' 
>      -H 'Origin: http://192.168.100.5:16856' 
>      -H 'Referer: http://192.168.100.5:16856/websites/13/config/basic' 
>      -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36' 
>      --data-raw '{"id":13,"operate":"edit","enable":true,"cache":false,"cacheTime":0,"cacheUnit":"","name":"root","modifier":"^~","match":"/","proxyPass":"[http://192.168.100.6:4443","proxyHost":"$host","content":"location](http://192.168.100.6:4443%22,%22proxyHost%22:%22$host%22,%22content%22:%22location) ^~ / {\n    proxy_pass http://192.168.100.6:4443; \n    proxy_set_header Host $host; \n    proxy_set_header X-Real-IP $remote_addr; \n    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; \n    proxy_set_header REMOTE-HOST $remote_addr; \n    proxy_set_header Upgrade $http_upgrade; \n    proxy_set_header Connection "upgrade"; \n    proxy_set_header X-Forwarded-Proto $scheme; \n    proxy_http_version 1.1; \n    add_header X-Cache $upstream_cache_status; \n}","filePath":"/home/daoke/1panel/apps/openresty/openresty/www/sites/metabase.316.team/proxy/root.conf","replaces":{},"proxyProtocol":"http://","proxyAddress":"192.168.100.6:4443"}' 
>      --compressed 
>      --insecure

好的 我在本地试一下 我们马上发v1.8了 你可以更新一下 然后再看看还有没有这个问题

**Comment by forxiucn** [comment]
> > > Collaborator
> > 
> > 
> > > > > 什么类型的网站？ 操作了什么按钮？openresty 配置文件是否有错误？
> > > > 
> > > > 
> > > > 站点类型：反向代理
> > > > 之前站点都正常运行的，配置文件未见错误。升级面板版本后再来修改站点信息就报这个错误。
> > > 
> > > 
> > > 说具体一点 修改哪个
> > 
> > 
> > 
> > 1. [网站]-[网站]-[网站列表]页面；
> > 2. 我这里所有站点都是反向代理的，点击任意一个站点的[配置]按钮；
> > 3. 在弹出的页面点击[反向代理]；
> > 4. 在打开的页面再点击[编辑]按钮；
> > 5. 在右侧弹出的抽屉对话框中修改[后端代理地址]，原：http://192.168.100.23:4443  修改为：http://192.168.100.6:4443
> > 6. 点击右下角的[确认]按钮；
> > 7. 5.39s后页面弹出“服务内部错误”消息提示Pop；
> > 8. 这是复制的对应的请求内容：curl 'http://192.168.100.5:16856/api/v1/websites/proxies/update'
> >    -H 'Accept: application/json, text/plain, _/_'
> >    -H 'Accept-Language: zh'
> >    -H 'Connection: keep-alive'
> >    -H 'Content-Type: application/json'
> >    -H 'Cookie: sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%2218ae8f9fe1466d-0bf11c4dd181708-26031051-2073600-18ae8f9fe15c34%22%2C%22first_id%22%3A%22%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22url%E7%9A%84domain%E8%A7%A3%E6%9E%90%E5%A4%B1%E8%B4%A5%22%2C%22%24latest_search_keyword%22%3A%22url%E7%9A%84domain%E8%A7%A3%E6%9E%90%E5%A4%B1%E8%B4%A5%22%2C%22%24latest_referrer%22%3A%22url%E7%9A%84domain%E8%A7%A3%E6%9E%90%E5%A4%B1%E8%B4%A5%22%7D%2C%22identities%22%3A%22eyIkaWRlbnRpdHlfY29va2llX2lkIjoiMThhZThmOWZlMTQ2NmQtMGJmMTFjNGRkMTgxNzA4LTI2MDMxMDUxLTIwNzM2MDAtMThhZThmOWZlMTVjMzQifQ%3D%3D%22%2C%22history_login_id%22%3A%7B%22name%22%3A%22%22%2C%22value%22%3A%22%22%7D%2C%22%24device_id%22%3A%2218ae8f9fe1466d-0bf11c4dd181708-26031051-2073600-18ae8f9fe15c34%22%7D; _SSID=7B8fsHHSFWYVmbeiWzjLIgV3PsHZ2Ti4s48cQkqW6yU; stay_login=0; did=HEe7-H9Nj92kKknRhhlfLkNN2oxhyO21DMUGA8xhG6R6dxxw5npTJRo92o_5HcfzkSG9kNNVYwxfi7Q-lvK9ow; _CrPoSt=cHJvdG9jb2w9aHR0cDo7IHBvcnQ9NTAwMDsgcGF0aG5hbWU9Lzs%3D; ___rl__test__cookies=1699407517504; OUTFOX_SEARCH_USER_ID_NCOO=995174405.8005052; psession=542a7d58-1896-4f9f-b27e-8e1e3be1e3f5'
> >    -H 'Origin: http://192.168.100.5:16856'
> >    -H 'Referer: http://192.168.100.5:16856/websites/13/config/basic'
> >    -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'
> >    --data-raw '{"id":13,"operate":"edit","enable":true,"cache":false,"cacheTime":0,"cacheUnit":"","name":"root","modifier":"^~","match":"/","proxyPass":"[http://192.168.100.6:4443","proxyHost":"$host","content":"location](http://192.168.100.6:4443%22,%22proxyHost%22:%22$host%22,%22content%22:%22location) ^~ / {\n    proxy_pass http://192.168.100.6:4443; \n    proxy_set_header Host $host; \n    proxy_set_header X-Real-IP $remote_addr; \n    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; \n    proxy_set_header REMOTE-HOST $remote_addr; \n    proxy_set_header Upgrade $http_upgrade; \n    proxy_set_header Connection "upgrade"; \n    proxy_set_header X-Forwarded-Proto $scheme; \n    proxy_http_version 1.1; \n    add_header X-Cache $upstream_cache_status; \n}","filePath":"/home/daoke/1panel/apps/openresty/openresty/www/sites/metabase.316.team/proxy/root.conf","replaces":{},"proxyProtocol":"http://","proxyAddress":"192.168.100.6:4443"}'
> >    --compressed
> >    --insecure
> 
> 好的 我在本地试一下 我们马上发v1.8了 你可以更新一下 然后再看看还有没有这个问题

好的 感谢~！

**Comment by forxiucn** [comment]
升级了v1.8还是报这个错误

**Comment by zhengkunwang223** [comment]
> 升级了v1.8还是报这个错误
您好 可以添加我的企业微信
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/c3ce39c4-6bbf-4f21-a471-3277f9485d5f)
帮你远程看一下

**Comment by SIGHTDEEP** [comment]
+1
1.8.2
也依然报错
