### ISSUE TITLE
[BUG]使用1Panel查看容器日志后产生僵尸进程

### ISSUE THREAD

**Issue by kny-f** [1Panel-dev/1Panel#2846]
### 1Panel 版本

v1.7.4

### 问题描述

使用面板查看容器日志产生僵尸进程

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/71928941/03f99039-eed6-400a-8cd4-4bcc14ef0e84)
![image](https://github.com/1Panel-dev/1Panel/assets/71928941/d0f5789c-3272-4747-9343-072c7eda7556)
![image](https://github.com/1Panel-dev/1Panel/assets/71928941/bbb14ca1-d1d1-471f-8fc8-d63b755c8b49)

第一步 打开容器日志 然后关闭
第二步 查看系统进程 会多一个僵尸进程

**Comment by ssongliu** [comment]
感谢反馈！1.8 版本解决该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。

**Comment by jackiezzq** [comment]
![image](https://github.com/user-attachments/assets/7b688b29-6651-4d97-842f-c175394398b6)
最新版本还是存在僵尸进程，也是查看日志后

**Comment by wanghe-fit2cloud** [comment]
> 最新版本还是存在僵尸进程，也是查看日志后

可以先查看一下父进程
