### ISSUE TITLE
[QUESTION] 本地应用开发 目录权限问题

### ISSUE THREAD

**Issue by qwenode** [1Panel-dev/1Panel#2853]
### 请描述您的问题

如docker-composer配置
    volumes:
      - "${MOUNT_PATH}:/usr/share/elasticsearch/data"

data.yml配置
        - default: ./data
          edit: true
          envKey: MOUNT_PATH
          labelEn: Mount folder path
          labelZh: 挂载文件夹路径
          required: true
          type: text
         
当后台启动新应用的时候, 系统会自动创建 ./data 目录,但是 docker没有权限读写

此时除手动修改 data 所有权以外,有其他方式让 应用自动修改这个 让容器 可写入这个目录 吗

**Comment by zhengkunwang223** [comment]
> ### 请描述您的问题
> 如docker-composer配置 volumes: - "${MOUNT_PATH}:/usr/share/elasticsearch/data"
> 
> data.yml配置 - default: ./data edit: true envKey: MOUNT_PATH labelEn: Mount folder path labelZh: 挂载文件夹路径 required: true type: text
> 
> 当后台启动新应用的时候, 系统会自动创建 ./data 目录,但是 docker没有权限读写
> 
> 此时除手动修改 data 所有权以外,有其他方式让 应用自动修改这个 让容器 可写入这个目录 吗

应用安装之前支持执行脚本 可以在 版本目录下增加 scripts 目录 然后增加 init.sh 脚本

**Comment by qwenode** [comment]
好,我试试,谢谢

**Comment by qwenode** [comment]
可以了
