### ISSUE TITLE
[BUG] 自建应用备份后,还原失败

### ISSUE THREAD

**Issue by qwenode** [1Panel-dev/1Panel#2854]
### 1Panel 版本

1.7.4

### 问题描述

错误:
stderr: stat /opt/1panel/apps/local/elasticsearch-single/localelasticsearch-single/docker-compose.yml: no such file or directory

![image](https://github.com/1Panel-dev/1Panel/assets/8974108/dfb29867-2633-4c07-abcf-80c239664bb7)

![image](https://github.com/1Panel-dev/1Panel/assets/8974108/2f6ad7a7-a20b-41e7-aed4-c887e1f2c6bb)

同时这个应用也无法卸载了
![image](https://github.com/1Panel-dev/1Panel/assets/8974108/9de38733-6bc6-488a-8eb6-a9a1ce0b08e7)

手动上传备份的数据,点击重启出现这个,不过点击重建成功了
![image](https://github.com/1Panel-dev/1Panel/assets/8974108/f64e4bbc-ad08-421a-92cf-d929769758ea)

### 重现步骤

安装应用 https://github.com/qwenode/1panel-appstore/blob/master/local_appstore_sync_helper.sh

1. 新启动一个应用 [elasticsearch-single](https://github.com/qwenode/1panel-appstore/tree/master/apps/elasticsearch-single)
2. 备份应用,下载
3. 删除应用包括备份
4. 再启动新应用
5. 上传备份的应用并还原
6. 还原成功,但是应用所属的目录被清空了,里面没文件, 也无法重建应用, 容器列表也不见新建的这个容器
7. 备份的文件是有内容

**Comment by qwenode** [comment]
[localelasticsearch-single_20231108043329.tar.gz](https://github.com/1Panel-dev/1Panel/files/13295055/localelasticsearch-single_20231108043329.tar.gz)
备份的应用数据

**Comment by zhengkunwang223** [comment]
好的 我们在本地复现一下

**Comment by qwenode** [comment]
@zhengkunwang223 
根据排查,我估计是因为 backend/app/service/backup_app.go:251 这行更新的时候env.CONTAINER_NAME 被覆盖成旧的,导致重启的时候找不到当前 应用 的CONTAINER 

![image](https://github.com/1Panel-dev/1Panel/assets/8974108/495d8e40-ed20-4b80-8f16-6509a744eac6)


![image](https://github.com/1Panel-dev/1Panel/assets/8974108/dfd8d0cf-c6e4-41b5-80b8-39f65c5ed6bf)

**Comment by wanghe-fit2cloud** [comment]
v1.8.1 版本已发布。
