### ISSUE TITLE
[FEATURE]对群晖系统的支持

### ISSUE THREAD

**Issue by carolcoral** [1Panel-dev/1Panel#2856]
### 1Panel 版本

1.8.0

#### 版本信息
* 群晖DSM:  7.2.1
* 1panel: 1.8.0

#### 目前的面板
1. 无法识别到群晖系统的防火墙
2. 对于SSH的管理也是“假”的（在面板中开启或关闭SSH，实际上服务器并没有成功开启或关闭SSH功能）

#### 相关截图
![image](https://github.com/1Panel-dev/1Panel/assets/8952687/38eac315-1169-42c2-baeb-814383a46416)
![image](https://github.com/1Panel-dev/1Panel/assets/8952687/55cc1cae-04c3-470f-8500-a1a4ca74269c)

![image](https://github.com/1Panel-dev/1Panel/assets/8952687/f1b1dc2e-46d5-4573-a009-21194f98a54c)
![image](https://github.com/1Panel-dev/1Panel/assets/8952687/7db27186-cc1a-4123-8445-c01f18ad7265)

**Comment by ssongliu** [comment]
感谢反馈！后续版本考虑支持上述需求。

**Comment by carolcoral** [comment]
> 感谢反馈！后续版本考虑支持上述需求。

另外还发现一个bug：

> 当群辉系统重启后，虽然1p面板的状态是启动的，但是实际上是无法正常访问的，必须要手动执行 `1pctl restart`

![image](https://github.com/1Panel-dev/1Panel/assets/8952687/a6547659-72af-4255-b517-1d736d5fde73)
![image](https://github.com/1Panel-dev/1Panel/assets/8952687/51941b64-53f0-44c0-9db0-470a22f68bfd)

**Comment by YaKun9** [comment]
> 感谢反馈！后续版本考虑支持上述需求。

期待早日支持

**Comment by carolcoral** [comment]
等一个版本更新😊

**Comment by wanghe-fit2cloud** [comment]
相关问题的讨论，汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4004
