### ISSUE TITLE
[BUG]ubuntu 20版本安装1Panel之后 登陆网址在chrome和safari无法打开，在edge打开提示404错误

### ISSUE THREAD

**Issue by ChanXing2023** [1Panel-dev/1Panel#2857]
### 1Panel 版本

未知

### 问题描述

使用官网提供的命令：curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sudo bash quick_start.sh

获取到
[1Panel Log]: 请用浏览器访问面板: 
[1Panel Log]: 外网地址: http://x:38332/c392dba8cd 
[1Panel Log]: 内网地址: http://x:38332/c392dba8cd 
[1Panel Log]: 用户名称: xxxx 
[1Panel Log]: 用户密码: xxx 
[1Panel Log]:  
[1Panel Log]: 项目官网: https://1panel.cn 
[1Panel Log]: 项目文档: https://1panel.cn/docs 
[1Panel Log]: 代码仓库: https://github.com/1Panel-dev/1Panel 

使用外网地址 提示404错误，阿里云打开了38332的安全端口

### 重现步骤

使用官网提供的命令：curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sudo bash quick_start.sh

获取到
[1Panel Log]: 请用浏览器访问面板: 
[1Panel Log]: 外网地址: http://x:38332/c392dba8cd 
[1Panel Log]: 内网地址: http://x:38332/c392dba8cd 
[1Panel Log]: 用户名称: xxxx 
[1Panel Log]: 用户密码: xxx 
[1Panel Log]:  
[1Panel Log]: 项目官网: https://1panel.cn 
[1Panel Log]: 项目文档: https://1panel.cn/docs 
[1Panel Log]: 代码仓库: https://github.com/1Panel-dev/1Panel 

使用外网地址 提示404错误，阿里云打开了38332的安全端口

**Comment by ssongliu** [comment]
感谢反馈！可以从以下方面检查：
1. 1pctl status 查看 1panel 服务状态是否正常；
2. sudo ufw status 查看防火墙是否有放行 1panel 服务端口；
3. 本地 curl ，如：curl http://172.16.10.111:38332 是否正常返回。

**Comment by Jev121** [comment]
> 感谢反馈！可以从以下方面检查：
> 1. 1pctl status 查看 1panel 服务状态是否正常；
> 2. sudo ufw status 查看防火墙是否有放行 1panel 服务端口；
> 3. 本地 curl ，如：curl http://172.16.10.111:38332 是否正常返回。

我也出现了同样的问题：
从1.7版本在面板内升级到1.8，之后就进不去登录页面了，错误connection refused

1. 服务状态正常；
2. 未安装防火墙；
3. curl本地（localhost）可以正常返回，curl域名或者ip，错误代码（7）connection refused

1pctl restore操作，回滚后又可以正常访问

**Comment by ssongliu** [comment]
> > 感谢反馈！可以从以下方面检查：
> > 
> > 1. 1pctl status 查看 1panel 服务状态是否正常；
> > 2. sudo ufw status 查看防火墙是否有放行 1panel 服务端口；
> > 3. 本地 curl ，如：curl http://172.16.10.111:38332 是否正常返回。
> 
> 我也出现了同样的问题： 从1.7版本在面板内升级到1.8，之后就进不去登录页面了，错误connection refused
> 
> 1. 服务状态正常；
> 2. 未安装防火墙；
> 3. curl本地（localhost）可以正常返回，curl域名或者ip，错误代码（7）connection refused
> 
> 1pctl restore操作，回滚后又可以正常访问

1.8 版本区分了 ipv4 和 ipv6，默认监听 ipv4，可以执行 netstat -tunlp | grep <1Panel 端口> 看看老版本是监听的哪个，新版本用 1pctl listen-ip ipv4/ipv6 手动切换。

**Comment by ChanXing2023** [comment]
我发现一个问题，http://x:38332/ 直接访问，在edge可以正常打开，但是在mac上最新版的chrome的119.0.6045.123，加载比较慢，但是windows电脑edge打开比较快，目前看http://x:38332/c392dba8cd 这种目前还没做适配

**Comment by ssongliu** [comment]
> 我发现一个问题，http://x:38332/ 直接访问，在edge可以正常打开，但是在mac上最新版的chrome的119.0.6045.123，加载比较慢，但是windows电脑edge打开比较快，目前看http://x:38332/c392dba8cd 这种目前还没做适配

直接用 ip + 端口访问是否可以了呢？

**Comment by Jev121** [comment]
> > > 感谢反馈！可以从以下方面检查：
> > > 
> > > 1. 1pctl status 查看 1panel 服务状态是否正常；
> > > 2. sudo ufw status 查看防火墙是否有放行 1panel 服务端口；
> > > 3. 本地 curl ，如：curl http://172.16.10.111:38332 是否正常返回。
> > 
> > 我也出现了同样的问题： 从1.7版本在面板内升级到1.8，之后就进不去登录页面了，错误connection refused
> > 
> > 1. 服务状态正常；
> > 2. 未安装防火墙；
> > 3. curl本地（localhost）可以正常返回，curl域名或者ip，错误代码（7）connection refused
> > 
> > 1pctl restore操作，回滚后又可以正常访问
> 
> 1.8 版本区分了 ipv4 和 ipv6，默认监听 ipv4，可以执行 netstat -tunlp | grep <1Panel 端口> 看看老版本是监听的哪个，新版本用 1pctl listen-ip ipv4/ipv6 手动切换。

解决了，谢谢
