### ISSUE TITLE
[FEATURE] Docker 启停支持指定 docker.sock 位置

### ISSUE THREAD

**Issue by hsjgit** [1Panel-dev/1Panel#2858]
### 1Panel 版本

v1.8.0-alpha.11

### 问题描述

因为我的服务器的docker.sock文件不在/var/run/docker.sock，导致和本地docker失败

### 重现步骤

将/var/run/docker.sock 换个位置然后重新启动

### 期待的正确结果

给让我在配置文件指定或者自动获取到正确位置

**Comment by ssongliu** [comment]
感谢反馈！这里是想在 docker 启停的时候支持指定 docker.sock 位置是吗？

**Comment by hsjgit** [comment]
对，我服务器上的docker.sock不在默认默认路径下

**Comment by ssongliu** [comment]
> 对，我服务器上的docker.sock不在默认默认路径下

好的👌，后续版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
