### ISSUE TITLE
[BUG]刚开机后的MFA认证问题

### ISSUE THREAD

**Issue by okxlin** [1Panel-dev/1Panel#286]
### 1Panel 版本

v1.0.1

### 问题描述

刚开机时，输入账户密码，然后输入二次验证码，

验证成功了，页面刷新，但是又重新载入的是登陆界面。

> 设备背景
>> - 腾讯云香港轻量应用服务器
>> - Debian 11
>> - 全新装的新系统

### 重现步骤

1. 保持登陆状态；
2. 主机 reboot;
3. 等待面板检测请求失败，然后自动进入登录页面;
4. 输入密码账户、二次验证（不能错误）;
5. 发现了需要重复登录的问题;

> 偶然发现，貌似可解决
>> - 假如输入验证错误，
>> - 或者重新载入登录页面后，点击刷新页面

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
在我们的开发测试环境中没有复现该问题。

帮忙提供一下 1Panel 运行日志（/opt/1panel/1Panel.log），来协助定位问题。

**Comment by zyyfit** [comment]
您好，我复现了一下，是mfa验证码快过期的时候，输入验证码登录，会返回到输入用户名密码的页面，请问您那边是同样的问题吗？

**Comment by okxlin** [comment]
> 您好，我复现了一下，是mfa验证码快过期的时候，输入验证码登录，会返回到输入用户名密码的页面，请问您那边是同样的问题吗？

不是MFA码快过期也能复现。

首先停留在1panel主页，终端发出reboot，等待重启完成，页面会加载进入到登录界面。

然后登录、输入MFA码，就大概率出现描述的需要重新登录的问题

**Comment by zyyfit** [comment]
您好，我们在1.0.3版本尝试修复了一下这个问题，您可以升级到1.0.3，然后看看还会不会出现这种情况

**Comment by okxlin** [comment]
> 您好，我们在1.0.3版本尝试修复了一下这个问题，您可以升级到1.0.3，然后看看还会不会出现这种情况

已经解决，谢谢开发团队
