### ISSUE TITLE
[FEATURE] 给1p控制台assets 加浏览器缓存

### ISSUE THREAD

**Issue by qwenode** [1Panel-dev/1Panel#2860]
### 1Panel 版本

1.8.0

### 请描述您的需求或者改进建议

当前每次请求都没有缓存,访问速度很慢,希望能加上浏览器缓存

![image](https://github.com/1Panel-dev/1Panel/assets/8974108/9d900518-b904-4f6e-a5f2-b68f4236fd54)

### 请描述你建议的实现方案

这边我提了个pr,不知道符不符合规范
https://github.com/1Panel-dev/1Panel/pull/2859

**Comment by ssongliu** [comment]
感谢贡献！我们稍后审查一下，没问题就合到主分支。

**Comment by qwenode** [comment]
谢谢

**Comment by wanghe-fit2cloud** [comment]
v1.8.1 版本已发布。
