### ISSUE TITLE
[BUG] DNS申请SSL证书失败

### ISSUE THREAD

**Issue by YaKun9** [1Panel-dev/1Panel#2861]
### 1Panel 版本

1.8.0

### 问题描述

申请一直失败，截图如下：
![image](https://github.com/1Panel-dev/1Panel/assets/131952790/907b3a67-982f-4cf3-9eea-7aff0818cf1f)
![image](https://github.com/1Panel-dev/1Panel/assets/131952790/e5068981-c934-4740-8d62-79e51c55a3d3)

**通过查看DNSPod操作日志发现创建记录到删除记录之前时间只有几十秒，一般来说，记录生效时间可能长达一两分钟甚至更久，所以你们这个验证时间是不是可以适当延长？建议加入重试机制，多次重试检测，并在UI上作出反馈，不然以为卡住了**

![image](https://github.com/1Panel-dev/1Panel/assets/131952790/b1d2f243-fd92-4bd1-8455-062ebb2929df)

### 重现步骤

通过DNS申请证书即可，从11.8下午至今一直无法成功

**Comment by cyril-cheng** [comment]
这个问题我之前也反馈过，最好有重试机制，特别是在域环境中，首次检测是肯定失败的。

**Comment by YaKun9** [comment]
> 这个问题我之前也反馈过，最好有重试机制，特别是在域环境中，首次检测是肯定失败的。

是的，80%都是失败的，因为失败之后会删除记录，所以再一次申请又会创建-失败-删除，搁这无用功

**Comment by ssongliu** [comment]
感谢反馈，后续版本优化。

**Comment by zhengkunwang223** [comment]
感谢反馈 我们打算在 v.1.9.0 版本对证书进行重构

**Comment by YaKun9** [comment]
> 感谢反馈 我们打算在 v.1.9.0 版本对证书进行重构

好的，另外既然都已经可以在证书里面通过api key进行申请证书，建议也考虑一下在创建网站的时候，填写域名也支持通过 api key进行自动解析

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。

**Comment by YaKun9** [comment]
> v1.9.0 版本已发布。

更新1.9过程中,提示连接超时等.现在已经连接不上面板了.一直超时.........

**Comment by wanghe-fit2cloud** [comment]
可以进入 SSH 终端后，手动执行 `suto 1pctl status` 查看一下运行状态。

**Comment by wanghe-fit2cloud** [comment]
> 更新1.9过程中,提示连接超时等.现在已经连接不上面板了.一直超时.........

可以进入 SSH 终端后，手动执行 `1pctl status` 查看一下运行状态。
