### ISSUE TITLE
[BUG]升级1.8后网站设置中出现配置更新错误

### ISSUE THREAD

**Issue by csthenry** [1Panel-dev/1Panel#2862]
### 1Panel 版本

1.8.0

### 问题描述

[BUG]升级1.8后网站设置中出现配置更新错误，如默认文档、流量限制等，点击更新都会出现服务异常错误。
![image](https://github.com/1Panel-dev/1Panel/assets/32993468/fd0c35f0-298a-4409-b510-5cc361cfeb3c)

### 重现步骤

升级1.8后网站设置中出现配置更新错误，如默认文档、流量限制等，点击更新都会出现服务异常错误。

**Comment by csthenry** [comment]
除此之外，网站设置中 安全部分 User-Agent 过滤没有开关？

**Comment by zhengkunwang223** [comment]
> 除此之外，网站设置中 安全部分 User-Agent 过滤没有开关？

默认打开的，其实一直就有，没有放开页面

**Comment by zhengkunwang223** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/959c6e95-46e4-4320-bb4d-ae82f26b4e69)
添加我企业微信 远程看一下

**Comment by csthenry** [comment]
> ![image](https://user-images.githubusercontent.com/31820853/281622603-959c6e95-46e4-4320-bb4d-ae82f26b4e69.png) 添加我企业微信 远程看一下

已添加

**Comment by zhengkunwang223** [comment]
已复现问题 下个小版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.8.1 版本已发布。
