### ISSUE TITLE
[FEATURE]应用商店条件过滤

### ISSUE THREAD

**Issue by jingyuan9527** [1Panel-dev/1Panel#2865]
### 1Panel 版本

v1.8.0

### 请描述您的需求或者改进建议

应用商店导入了本地应用之后，应用列表跟官方应用商店应用有重复。导入应用很多的时候筛选起来很麻烦，可不可以有一个过滤条件【非本地应用】、【本地应用】之类过滤的。

**Comment by zhengkunwang223** [comment]
可以通过标签判断是否是本地应用
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/f2f8fdc9-5e03-4dc0-88b2-c7a8087f7499)

**Comment by jingyuan9527** [comment]
我的意思是能不能加一个筛选条件，【非本地应用】的过滤，只看应用商店里的应用。
【非本地应用】+建站。两个条件同时使用。

**Comment by zhengkunwang223** [comment]
> 我的意思是能不能加一个筛选条件，【非本地应用】的过滤，只看应用商店里的应用。
> 
> 【非本地应用】+建站。两个条件同时使用。

好的，下个大版本加上

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
