### ISSUE TITLE
[BUG] 反向代理 缓存时间不支持选择年

### ISSUE THREAD

**Issue by qwenode** [1Panel-dev/1Panel#2866]
### 1Panel 版本

1.8.0

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/8974108/b7243d4b-9f49-4d6b-9703-ef1bb9836c15)

### 重现步骤

缓存时间不支持选择年,其他正常

**Comment by zhengkunwang223** [comment]
感谢反馈 我们先复现一下

**Comment by wanghe-fit2cloud** [comment]
v1.8.1 版本已发布。
