### ISSUE TITLE
[BUG] 安装MySQL容器失败，“AppArmor enabled”

### ISSUE THREAD

**Issue by liqimore** [1Panel-dev/1Panel#2867]
### 联系方式

i@liqi.link

### 1Panel 版本

v1.8.0

### 问题描述

反错：  
stderr: Container 1Panel-mysql-Fdzg Creating Container 1Panel-mysql-Fdzg Created Container 1Panel-mysql-Fdzg Starting Error response from daemon: AppArmor enabled on system but the docker-default profile could not be loaded: running `/usr/sbin/apparmor_parser apparmor_parser -Kr /var/lib/docker/tmp/docker-default4246559669` failed with output: apparmor_parser: Unable to replace "docker-default". Permission denied; attempted to load a profile while confined? error: exit status 243
备注：  
/var/lib/docker/tmp/ 为空

### 重现步骤

PVE, ubuntu2204 lxc容器，开启nest
关闭apparmor结果一样

### 相关日志输出

```shell
stderr: Container 1Panel-mysql-Fdzg Creating Container 1Panel-mysql-Fdzg Created Container 1Panel-mysql-Fdzg Starting Error response from daemon: AppArmor enabled on system but the docker-default profile could not be loaded: running `/usr/sbin/apparmor_parser apparmor_parser -Kr /var/lib/docker/tmp/docker-default4246559669` failed with output: apparmor_parser: Unable to replace "docker-default". Permission denied; attempted to load a profile while confined? error: exit status 243
```

### 附加信息

在家里的物理机安装了pve7的环境，之后创建的lxc容器，privileged，nesting打开。安装1panel正常，但是无法安装MySQL以及其他镜像，不知道是否是已知问题，谢谢

**Comment by wanghe-fit2cloud** [comment]
安装 apparmor-utils 软件包，应该可以解决这个问题。
参考官方文档：
https://docs.docker.com/engine/release-notes/23.0/#known-issues
