### ISSUE TITLE
[QUESTION] 使用cloudflare 开启cnd ，反代1panel,域名登录1p后网站页消失，无法使用

### ISSUE THREAD

**Issue by bulesky89857** [1Panel-dev/1Panel#287]
### 请描述您的问题

反代127.0.0.1:1p端口，之前一直时这么用，没有问题，后来服务器重装了几次，域名也换了，采用cf cnd，严格加密模式第四项。
但是，如果采用ip登录1p,则不会出现以上问题，不知问题出在哪里。

**Comment by bulesky89857** [comment]
以上问题出现再chrome浏览器，换成edge后一切正常，正在研究。

**Comment by zhengkunwang223** [comment]
可以尝试清理浏览器缓存再访问

**Comment by bulesky89857** [comment]
> 可以尝试清理浏览器缓存再访问

对的，隐私模式正常使用，开始怀疑谷歌插件的问题，禁用后还是不行，最后清楚缓存和cookies ，解决了，谢谢回复。

**Comment by yfdoor** [comment]
> ### 请描述您的问题
> 反代127.0.0.1:1p端口，之前一直时这么用，没有问题，后来服务器重装了几次，域名也换了，采用cf cnd，严格加密模式第四项。 但是，如果采用ip登录1p,则不会出现以上问题，不知问题出在哪里。

我套 cdn 前都反代不成功，我配置文件添加了：
```
    location /p/ {
        proxy_pass http://127.0.0.1:22262/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
```
请问你是怎么修改的配置文件？ 而且我套 cdn 后整个网站都打不开了

**Comment by bulesky89857** [comment]
> > ### 请描述您的问题
> > 反代127.0.0.1:1p端口，之前一直时这么用，没有问题，后来服务器重装了几次，域名也换了，采用cf cnd，严格加密模式第四项。 但是，如果采用ip登录1p,则不会出现以上问题，不知问题出在哪里。
> 

我套 cdn 前都反代不成功，我配置文件添加了：
```
    location /p/ {
        proxy_pass http://127.0.0.1:22262/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
```
请问你是怎么修改的配置文件？ 而且我套 cdn 后整个网站都打不开了

首先用的是cf,cdn需要开启ssl严格模式，就是最后一项，并且需要部署源服务器证书，确定成功代理后，在修改配置文件，添加上述代码 #405

**Comment by yfdoor** [comment]
> > > ### 请描述您的问题
> > > 反代127.0.0.1:1p端口，之前一直时这么用，没有问题，后来服务器重装了几次，域名也换了，采用cf cnd，严格加密模式第四项。 但是，如果采用ip登录1p,则不会出现以上问题，不知问题出在哪里。
> > 
> > 
> > 我套 cdn 前都反代不成功，我配置文件添加了：
> > ```
> >     location /p/ {
> >         proxy_pass http://127.0.0.1:22262/;
> >         proxy_set_header Host $host;
> >         proxy_set_header X-Real-IP $remote_addr;
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 请问你是怎么修改的配置文件？ 而且我套 cdn 后整个网站都打不开了
> 
> 首先用的是cf,cdn需要开启ssl严格模式，就是最后一项，并且需要部署源服务器证书，确定成功代理后，在修改配置文件，添加上述代码 #405
 cdn 是因为这个没有开启ssl严格模式，开了就可以了，多谢

**Comment by 2234839** [comment]
在这描述一下我的现象方便后来踩坑的
我的是浏览器报错 NS_ERROR_REDIRECT_LOOP ，在cloudflare 中开启严格模式后可以正常访问1panel面板了
