### ISSUE TITLE
[BUG] 默认文档编辑提交 提示服务器错误

### ISSUE THREAD

**Issue by icoller** [1Panel-dev/1Panel#2870]
### 1Panel 版本

1.8.0

### 问题描述

![8653426B-E340-4D1C-901F-D3AA9B8AD148](https://github.com/1Panel-dev/1Panel/assets/19677896/ef1437fc-a16b-47be-ac46-921747f9160e)

### 重现步骤

如图所示

**Comment by zhengkunwang223** [comment]
您好 这个已经修复 请等待小版本发布

**Comment by wanghe-fit2cloud** [comment]
v1.8.1 版本已发布。
