### ISSUE TITLE
[BUG]计划任务里执行shell脚本的时候不能正常执行docker run

### ISSUE THREAD

**Issue by springeye** [1Panel-dev/1Panel#2871]
### 1Panel 版本

1.8.0

### 问题描述

我想在计划任务里每天执行一次docker run 来构建vue项目。然后执行的时候它似乎把docker run 命令最后面跟的参数当成了主机上的shell来执行(整个命令在主机上正常执行的)
```bash
docker run --rm --workdir /app -v /home/ubuntu/codes/ssss-sale:/app node:20-slim corepack enable && pnpm install --frozen-lockfile && pnpm run build
```

### 重现步骤

添加计划任务，选择shell脚本，。在脚本内容里填以下内容
```bash
docker run --rm --workdir /app -v /home/ubuntu/codes/ssss-sale:/app node:20-slim corepack enable && pnpm install --frozen-lockfile && pnpm run build
```

### 期待的正确结果

正常执行并退出

### 相关日志输出

```shell
执行日志就下面一行

bash: line 1: pnpm: command not found
```
```


### 附加信息

_No response_

**Comment by ssongliu** [comment]
感谢反馈，我们先在开发环境复现一下。

**Comment by ssongliu** [comment]
要实现这个功能，可以尝试以下三个方法：
1. 写到构建镜像的 Dockerfile 里面去（推荐）；
2. 单独写一个脚本文件 setup.sh，计划任务中写 `docker run --rm --workdir /app -v /home/ubuntu/codes/ssss-sale:/app node:20-slim sh ./setup.sh`；
3. 直接用命令` docker run --rm --workdir /app -v /home/ubuntu/codes/ssss-sale:/app node:20-slim  bash -c "corepack enable && pnpm install --frozen-lockfile && pnpm run build"`
