### ISSUE TITLE
[QUESTION]请问应用备份能在哪里看到？

### ISSUE THREAD

**Issue by youngledo** [1Panel-dev/1Panel#2872]
### 请描述您的问题

<img width="413" alt="企业微信截图_b670a4bc-628b-4abf-a791-2319583d7bc2" src="https://github.com/1Panel-dev/1Panel/assets/68590897/a79cb7cf-8c3a-44f8-8171-faa030a397a2">
找了一圈没也找到应用备份到底在哪里。

**Comment by zhengkunwang223** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/ee6a35a2-e97e-4350-8653-84024e4dd489)
