### ISSUE TITLE
[FEATURE]增加二级路径的反向代理

### ISSUE THREAD

**Issue by springeye** [1Panel-dev/1Panel#2874]
### 1Panel 版本

1.8.0

### 请描述您的需求或者改进建议

比如我的主程序(golang开发，嵌套了静态)是www.car.com
直接访问www.car.com/api是api
直接访问www.car.com/admin 是嵌入的web网站(前后端分离的vue开发的静态网站)
现在我想要添加一个反向代理
admin.car.com 代理的是www.car.com/admin   （不是nginx的网站子目录）

**Comment by zhengkunwang223** [comment]
这个配置如果 nginx 支持  你的后端服务支持 就可以配置
你可以先手动配置 看一下是否能生效
