### ISSUE TITLE
[QUESTION]jump-server安装后，系统疯狂读盘，直接死机，尝试两次都是这样

### ISSUE THREAD

**Issue by redrain-wang** [1Panel-dev/1Panel#2875]
### 请描述您的问题

选择应用商店的jump-server服务，安装后，系统疯狂读盘，直接死机，尝试两次都是这样 系统配置2c2g

**Comment by wanghe-fit2cloud** [comment]
系统配置太低了，JumpServer + MySQL + Redis 这几个容器肯定跑不起来。

JumpServer 官方文档也对服务器配置有相关说明：
https://docs.jumpserver.org/zh/master/install/setup_by_fast/

**Comment by redrain-wang** [comment]
> 系统配置太低了，JumpServer + MySQL + Redis 这几个容器肯定跑不起来。
> 
> JumpServer 官方文档也对服务器配置有相关说明： https://docs.jumpserver.org/zh/master/install/setup_by_fast/

谢谢，确实太低了，那么安装应用的时候是否可以增加一个检测系统配置是否符合要求的功能呢？
