### ISSUE TITLE
[FEATURE] 更新缓存清理

### ISSUE THREAD

**Issue by Simgor001** [1Panel-dev/1Panel#2876]
### 1Panel 版本

v1.8.0

### 请描述您的需求或者改进建议

每一次更新时1Panel都会将更新的文件下载到`/opt/1panel/tmp`，并且在该目录进行解压，但是更新完毕之后并没有对这些临时数据进行清理，导致占用过大，希望下次更新时能自动清理一下，或者提供选项让用户选择是否保留历史版本。

**Comment by wanghe-fit2cloud** [comment]
不自动删除，是因为有系统有提供 `版本回滚` 等功能。
缓存清理功能见下图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/cb95a089-064c-47d1-a934-4b635b119ce2)
