### ISSUE TITLE
[BUG]移动文件错误

### ISSUE THREAD

**Issue by ChishFoxcat** [1Panel-dev/1Panel#2877]
### 1Panel 版本

v1.8.0

### 问题描述

- 移动某一个文件到另一个文件夹下提示没有该文件
![image](https://github.com/1Panel-dev/1Panel/assets/76027184/d993117c-989d-4fcd-b313-1c0af78a73d2)
- 频繁检测文件重复，文件夹下没有这个文件还让我改文件名称操作
- 粘贴就报没有此文件，间歇性能成功粘贴但还是报错
![image](https://github.com/1Panel-dev/1Panel/assets/76027184/4387f022-ba4c-4e6c-9bec-cd1bd9adf7f6)

### 重现步骤

> 主机 -> 文件
- 移动文件或移动整个文件夹

### 相关日志输出

```shell
服务内部错误: error : exit status 1, output: mv: 

（在系统日志中未找到相关日志，仅在面板操作中有操作日志）
```

**Comment by zhengkunwang223** [comment]
我看你移动了多次 你是第一次移动成功了之后 又移动了一次这个文件吗

**Comment by ChishFoxcat** [comment]
> 我看你移动了多次 你是第一次移动成功了之后 又移动了一次这个文件吗

他提示错误，发现这个的时候我尝试再点一下就这样了

并且源文件还存在

**Comment by zhengkunwang223** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/462992bb-2f71-43ec-8515-999e368a460e)
加我企业微信我远程看一下

**Comment by wanghe-fit2cloud** [comment]
v1.8.1 版本已发布。
