### ISSUE TITLE
[FEATURE]希望应用商店里有web的应用可以有按钮直达web页面

### ISSUE THREAD

**Issue by 52lemon6** [1Panel-dev/1Panel#288]
### 1Panel 版本

1.0.1

### 请描述您的需求或者改进建议

希望应用商店里有web的应用可以有按钮直达web页面，点击应用卡片跳转进入web，个人觉得比较符合逻辑，因为我看到卡片我就想点进去进入下一层💦

**Comment by zhengkunwang223** [comment]
好的，感谢建议，后续版本实现

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
