### ISSUE TITLE
[FEATURE]允许配置Axios请求的超时时间或者优化应用商店页面的加载逻辑

### ISSUE THREAD

**Issue by jackytsu** [1Panel-dev/1Panel#2880]
### 1Panel 版本

v1.8.0

### 请描述您的需求或者改进建议

本人使用的是国外VPS，由于线路原因导致国内访问的速度非常感人。当访问应用商店的全部页面时，需要下载全量的应用信息文件，v1.8.0版本大概有~400K左右~500多K，由于网速的问题，导致20秒内无法完成下载，结果就导致前端提示超时。

### 请描述你建议的实现方案

两个方案可以改善这个问题：
1、允许修改Axios请求的超时时间，以达到前端请求可以超过默认的20秒；
2、优化前端的显示逻辑，只加载当前页需要的数据，而不是加载整个json文件；

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述建议。

**Comment by wanghe-fit2cloud** [comment]
参考：https://github.com/1Panel-dev/1Panel/issues/5008
