### ISSUE TITLE
[QUESTION]网站打不开,之前宝塔能打开,现在宝塔环境装不上.同样的操作,就是网站打不开

### ISSUE THREAD

**Issue by wyUshio** [1Panel-dev/1Panel#2882]
### 请描述您的问题

配置文件
server {
    listen 80 ; 
    server_name demo.stream; 
    index index.php index.html index.htm default.php default.htm default.html; 
    proxy_set_header Host $host; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header X-Forwarded-Host $server_name; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_http_version 1.1; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    access_log /www/sites/demo.stream/log/access.log; 
    error_log /www/sites/demo.stream/log/error.log; 
    access_by_lua_file /www/common/waf/access.lua; 
    set $RulePath /www/sites/demo.stream/waf/rules; 
    set $logdir /www/sites/demo.stream/log; 
    set $redirect on; 
    set $attackLog on; 
    set $CCDeny off; 
    set $urlWhiteAllow off; 
    set $urlBlockDeny off; 
    set $argsDeny off; 
    set $postDeny off; 
    set $cookieDeny off; 
    set $fileExtDeny off; 
    set $ipBlockDeny off; 
    set $ipWhiteAllow off; 
    location ^~ /.well-known/acme-challenge {
        allow all; 
        root /usr/share/nginx/html; 
    }
    root /www/sites/demo.stream/index/public; 
    location ~ [^/]\.php(/|$) {
        fastcgi_pass 127.0.0.1:9000; 
        include fastcgi-php.conf; 
        include fastcgi_params; 
        fastcgi_param SCRIPT_FILENAME /opt/1panel/apps/openresty/openresty/www/sites/demo.stream/index/index.php; 
    }
    include /www/sites/demo.stream/rewrite/demo.stream.conf; 
}
伪静态
location / {
    try_files $uri /index.php$is_args$args;
}

错误日志
2023/11/10 17:25:04 [error] 62#62: *7157 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 195.85.19.57, server: demo.stream, request: "GET /mod_mu/nodes/4/info?key=3a7caa4b32ffb47e7bb2d0ec7d097110&muKey=3a7caa4b32ffb47e7bb2d0ec7d097110 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "demo.stream"
2023/11/10 17:25:15 [error] 62#62: *7179 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 195.85.19.57, server: demo.stream, request: "GET /mod_mu/nodes/4/info?key=3a7caa4b32ffb47e7bb2d0ec7d097110&muKey=3a7caa4b32ffb47e7bb2d0ec7d097110 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "demo.stream"
2023/11/10 17:25:18 [error] 62#62: *2559 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 38.59.244.62, server: demo.stream, request: "GET /mod_mu/nodes/5/info?key=3a7caa4b32ffb47e7bb2d0ec7d097119&muKey=3a7caa4b32ffb47e7bb2d0ec7d097119 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "demo.stream"
2023/11/10 17:25:18 [error] 62#62: *2559 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 38.59.244.62, server: demo.stream, request: "POST /mod_mu/users/traffic?key=3a7caa4b32ffb47e7bb2d0ec7d097119&muKey=3a7caa4b32ffb47e7bb2d0ec7d097119&node_id=5 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "demo.stream"
2023/11/10 17:25:25 [error] 62#62: *7190 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 195.85.19.57, server: demo.stream, request: "GET /mod_mu/nodes/4/info?key=3a7caa4b32ffb47e7bb2d0ec7d097110&muKey=3a7caa4b32ffb47e7bb2d0ec7d097110 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "demo.stream"
2023/11/10 17:25:35 [error] 62#62: *7207 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 195.85.19.57, server: demo.stream, request: "GET /mod_mu/nodes/4/info?key=3a7caa4b32ffb47e7bb2d0ec7d097110&muKey=3a7caa4b32ffb47e7bb2d0ec7d097110 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "demo.stream"

**Comment by zhengkunwang223** [comment]
请详细描述你的问题 你这个配置文件是在宝塔中还是在1Panel中？
是从哪配置的网站打不开？

**Comment by wyUshio** [comment]
> 请详细描述你的问题 你这个配置文件是在宝塔中还是在1Panel中？ 是从哪配置的网站打不开？

配置文件是1panel里面的,网站是我从ssplanuim里面拉取的.就正常设置,操作和之前用宝塔是一样的就是配置public里面是主页和伪静态

**Comment by zhengkunwang223** [comment]
> > 请详细描述你的问题 你这个配置文件是在宝塔中还是在1Panel中？ 是从哪配置的网站打不开？
> 
> 配置文件是1panel里面的,网站是我从ssplanuim里面拉取的.就正常设置,操作和之前用宝塔是一样的就是配置public里面是主页和伪静态

你这个配置用的是本地的 PHP ？ fastcgi_param 的配置不对

**Comment by wyUshio** [comment]
> > > 请详细描述你的问题 你这个配置文件是在宝塔中还是在1Panel中？ 是从哪配置的网站打不开？
> > 
> > 
> > 配置文件是1panel里面的,网站是我从ssplanuim里面拉取的.就正常设置,操作和之前用宝塔是一样的就是配置public里面是主页和伪静态
> 
> 你这个配置用的是本地的 PHP ？ fastcgi_param 的配置不对
对,是本地的,这个要咋改?
本地php版本
PHP 8.2.7 (cli) (built: Jun  9 2023 19:37:27) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies

**Comment by zhengkunwang223** [comment]
> > > > 请详细描述你的问题 你这个配置文件是在宝塔中还是在1Panel中？ 是从哪配置的网站打不开？
> > > 
> > > 
> > > 配置文件是1panel里面的,网站是我从ssplanuim里面拉取的.就正常设置,操作和之前用宝塔是一样的就是配置public里面是主页和伪静态
> > 
> > 
> > 你这个配置用的是本地的 PHP ？ fastcgi_param 的配置不对
> > 对,是本地的,这个要咋改?
> > 本地php版本
> > PHP 8.2.7 (cli) (built: Jun  9 2023 19:37:27) (NTS)
> > Copyright (c) The PHP Group
> > Zend Engine v4.2.7, Copyright (c) Zend Technologies
> > with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies

建议不要用本地 PHP ，使用 PHP 运行环境

**Comment by yaoyingkeji** [comment]
https://docs.suitecrm.com/8.x/admin/installation-guide/webserver-setup-guide/#_4_configuring_url_re_writes
宝塔里面好好的，但是在1Panerl里面运行网站是空白的 不会跳转，如何设置RUL重写呢？
