### ISSUE TITLE
[BUG] 全新机器 纯净版本 debian12 默认没有装zip... 1panel 压缩解压缩 zip格式 报错找不到zip command，手动安装了zip，又报写I/O tmp目录失败...

### ISSUE THREAD

**Issue by gowy222** [1Panel-dev/1Panel#2884]
### 1Panel 版本

1.8

### 问题描述

1.搞了个阿里云的新服务器, 如题
2.zip压缩的时候是否支持压缩级别选项？毕竟几个G的文件夹压缩成zip还是吃紧.
3.后来手动ssh登陆进服务器，手动执行zip shell 压缩的..

### 重现步骤

debian12 64 纯净环境 阿里轻量云的默认镜像。不自带zip等工具
1panel 面板安装的时候，可能需要考虑一下 某些功能，系统底层是否已安装了对应的工具。

**Comment by zhengkunwang223** [comment]
截图一下

**Comment by gowy222** [comment]
> 截图一下

![image](https://github.com/1Panel-dev/1Panel/assets/52201479/847cb658-77fd-481b-803b-090f4d28517f)
![image](https://github.com/1Panel-dev/1Panel/assets/52201479/a1ed1dfc-b24d-4a9c-a582-a6fb2c772561)

**Comment by zhengkunwang223** [comment]
好的 我们复现一下这个问题 你的文件是多大？

**Comment by gowy222** [comment]
目标文件夹2.5个G左右..里面上百个mp3

**Comment by zhengkunwang223** [comment]
> 目标文件夹2.5个G左右..里面上百个mp3

好的 我们试一下

**Comment by gowy222** [comment]
> > 目标文件夹2.5个G左右..里面上百个mp3
> 
> 好的 我们试一下

![image](https://github.com/1Panel-dev/1Panel/assets/52201479/1d14585e-b93d-4cf5-987a-e12a27962327)
关键，执行失败，本地却又生成了一个0size的目标zip包..

**Comment by gowy222** [comment]
@wanghe-fit2cloud 哥呀，能不能找人再帮我看看之前那个问题，`https://github.com/1Panel-dev/1Panel/issues/2747`

**Comment by wanghe-fit2cloud** [comment]
v1.8.1 版本已发布。
