### ISSUE TITLE
[BUG] 新安装的 1pane ，点击主机中的防火墙提示 当前未检测到系统 firewalld 或 ufw 服务

### ISSUE THREAD

**Issue by wlq673736503** [1Panel-dev/1Panel#2887]
### 联系方式

无

### 1Panel 版本

1.8.0

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/37679561/d0829973-8fcd-4173-a45c-55b87854df8f)
我是第一次用这个面板，其他的不熟悉

### 重现步骤

点击防火墙，可以直接复现，我用的 腾讯云 debian 11 的系统， 我测试了 debian 12 也是一样， 轻量云服务器

### 期待的正确结果

能正常使用

**Comment by wanghe-fit2cloud** [comment]
需要手动安装防火墙软件，可以参考文档：
https://1panel.cn/docs/user_manual/hosts/firewall/
