### ISSUE TITLE
[FEATURE]关于站点数据文件夹的路径问题，及docker配置

### ISSUE THREAD

**Issue by okxlin** [1Panel-dev/1Panel#289]
### 1Panel 版本

v1.0.1

### 1
网站根目录建议修改个更通用的位置，不然PHP容器需要跨容器读取，

从条理性上看感觉不应该放在openresty目录下，应该放在`./1panel/apps`这一级，方便所需的容器进行读取；

openresty站点现有路径：
- `./1panel/apps/openresty/OpenResty/www`

### 2
另外看了下商店提供的app的docker-compose的配置，感觉现有的理念是将商店提供的容器完全独立开，都是分布在各自的小文件夹下，

关于如果进行改进，这一点我感觉这个项目可以借鉴一下：
- `https://github.com/yeszao/dnmp`

### 3

个人想法，仅供参考，谢谢开发者。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，建议非常中肯，后续版本中我们会持续优化。

**Comment by wanghe-fit2cloud** [comment]
重复 #2783 
> 网站路径问题会集中到上述 issue 中讨论。
