### ISSUE TITLE
[BUG]  应用商店每次请求都很慢

### ISSUE THREAD

**Issue by 1984anonymous** [1Panel-dev/1Panel#2893]
### 1Panel 版本

v1.8.1

### 问题描述

请问请求应用商店的接口  api/v1/apps/search 是转发请求了你们的接口吗 ， 每次打开都要4、5秒 能做个缓存吗

![image](https://github.com/1Panel-dev/1Panel/assets/116975547/20318e69-c43d-4932-ba61-53e4fe202976)

### 重现步骤

访问应用商店

**Comment by zhengkunwang223** [comment]
> ### 联系方式
> 
> _No response_
> 
> ### 1Panel 版本
> 
> v1.8.1
> 
> ### 问题描述
> 
> 请问请求应用商店的接口  api/v1/apps/search 是转发请求了你们的接口吗 ， 每次打开都要4、5秒 能做个缓存吗
> 
> 
> 
> ![image](https://github.com/1Panel-dev/1Panel/assets/116975547/20318e69-c43d-4932-ba61-53e4fe202976)
> 
> 
> 
> ### 重现步骤
> 
> 访问应用商店
> 
> ### 期待的正确结果
> 
> _No response_
> 
> ### 相关日志输出
> 
> _No response_
> 
> ### 附加信息
> 
> _No response_

没有，只是去获取了数据库数据
