### ISSUE TITLE
[BUG]设置网站密码访问报错。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#2894]
### 1Panel 版本

v1.8.1

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/93708226/cc2a089c-a932-45e4-a68b-e7fc50ef16af)

### 重现步骤

网站设置 - 密码访问

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.8.2 版本已发布。
