### ISSUE TITLE
[FEATURE] 记住文件回收站的开关状态

### ISSUE THREAD

**Issue by reddloob** [1Panel-dev/1Panel#2895]
### 1Panel 版本

1.8.1

### 请描述您的需求或者改进建议

回收站开关应该能够记忆开关状态，现在默认行为是未勾选“永久删除文件”，即使勾选了“永久删除文件”，下一次删除时也是未勾选的状态。

应该修改为：“更改开关状态后，下一次删除文件时记住上次的开关状态”。

而且大多数时候删除文件就是需要永久删除，所以初始的开关状态也应该改为永久删除。

![image](https://github.com/1Panel-dev/1Panel/assets/46004053/0e1a3d22-0b04-4485-be29-68d50ff4777e)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本增加是否开启文件回收站功能。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
