### ISSUE TITLE
[BUG]  重启服务器，容器的IP地址都会重新排列，导致数据库链接错误

### ISSUE THREAD

**Issue by icoller** [1Panel-dev/1Panel#2898]
### 1Panel 版本

1.8.1

### 问题描述

![0355098A-C83B-403B-8E68-6B9D6232B68E](https://github.com/1Panel-dev/1Panel/assets/19677896/4863f3c0-1114-46a0-a393-01777bdc8e85)

### 重现步骤

如图

**Comment by wanghe-fit2cloud** [comment]
替换为 service name
> docker 默认采用 bridge 连接，启动容器的时候会按照顺序来获取对应 ip 地址，这就导致容器每次重启后ip都会发生变化。

**Comment by LBC000** [comment]
同问！！！目的是宿主机用容器的mysql服务

**Comment by LBC000** [comment]
> 替换为 service name
> 
> > docker 默认采用 bridge 连接，启动容器的时候会按照顺序来获取对应 ip 地址，这就导致容器每次重启后ip都会发生变化。

是宿主机要用的

**Comment by wanghe-fit2cloud** [comment]
> > 替换为 service name
> > > docker 默认采用 bridge 连接，启动容器的时候会按照顺序来获取对应 ip 地址，这就导致容器每次重启后ip都会发生变化。
> 
> 是宿主机要用的

安装 MySQL 时，选择将端口对外暴露，然后使用宿主机IP+端口

**Comment by LBC000** [comment]
> > > 替换为 service name
> > > > docker 默认采用 bridge 连接，启动容器的时候会按照顺序来获取对应 ip 地址，这就导致容器每次重启后ip都会发生变化。
> > 
> > 
> > 是宿主机要用的
> 
> 安装 MySQL 时，选择将端口对外暴露，然后使用宿主机IP+端口

不太好。不太安全。能不能固定ip？本意是当本地服务使用

**Comment by cli-r** [comment]
可以手动编辑docker composr设置为静态ip，或者映射到127:0.0.1:3306，方便从宿主机使用
