### ISSUE TITLE
[BUG] 进入网站设置报错服务异常

### ISSUE THREAD

**Issue by kangfenmao** [1Panel-dev/1Panel#2903]
### 联系方式

kangfenmao@qq.com

### 1Panel 版本

v1.8.1

### 问题描述

网站 -> 设置，进入后会提示错误

<img width="944" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/8253512/d8a8ec0c-c19f-4be5-a7e2-e7fdcbe87c8a">

<img width="881" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/8253512/872e980e-2fad-4ec3-a4ee-670a95dc57a4">

### 重现步骤

安装 1Panel，不要配置域名的默认解析，不要配置 @ A记录

### 期待的正确结果

点击设置不报错，网站当前状态数据显示正常

### 相关日志输出

```shell
### OpenResty Logs

2023/11/11 16:53:07 [error] 43#43: *94 open() "/usr/share/nginx/html/nginx_status" failed (2: No such file or directory), client: 127.0.0.1, server: _, request: "GET /nginx_status HTTP/1.1", host: "127.0.0.1"
127.0.0.1 - - [11/Nov/2023:16:53:07 +0800] "GET /nginx_status HTTP/1.1" 404 150 "-" "Go-http-client/1.1" "-"
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by kangfenmao** [comment]
> 感谢反馈，我们先在本地环境复现一下上述问题。

有问题的话可以微信联系我，我提供复现环境

**Comment by zhengkunwang223** [comment]
> > 感谢反馈，我们先在本地环境复现一下上述问题。
> 
> 有问题的话可以微信联系我，我提供复现环境

是本地开发环境吗？

**Comment by kangfenmao** [comment]
> > > 感谢反馈，我们先在本地环境复现一下上述问题。
> > 
> > 
> > 有问题的话可以微信联系我，我提供复现环境
> 
> 是本地开发环境吗？

线上环境 @zhengkunwang223，给我一个处理人的微信，我提供帐号密码

**Comment by zhengkunwang223** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/4b29db0f-47d3-40e9-a2f3-09736d50dad5)

**Comment by zhengkunwang223** [comment]
经过定位 为误删配置文件导致 此 Issue 关闭

**Comment by kangfenmao** [comment]
default.conf 文件被删除导致的问题，记录一下

/opt/1panel/apps/openresty/openresty/conf/conf.d/

```nginx
server {
    listen        80 ;
    server_name   127.0.0.1;
    charset       utf-8;
    default_type  text/html;

    location ~ /.well-known/acme-challenge {
        allow all;
        root /usr/share/nginx/html;
    }

    location /nginx_status {
        stub_status   on;
        access_log   off;
    }

    root /usr/share/nginx/html;
}
```
