### ISSUE TITLE
[BUG]应用商店-实用工具-Nginx Proxy Manager安装以后无法实现反向代理

### ISSUE THREAD

**Issue by MUKEMUKE** [1Panel-dev/1Panel#2906]
### 1Panel 版本

1.8.1

### 问题描述

应用商店-实用工具-Nginx Proxy Manager安装以后 无法实现反向代理

用Nginx Proxy Manager 官方方法手动安装能正常使用

### 重现步骤

应用商店-实用工具-Nginx Proxy Manager安装以后 无法实现反向代理

**Comment by wanghe-fit2cloud** [comment]
1Panel 应用商店是采用容器化方案部署的应用，因此需要参考 Nginx Proxy Manager 官方文档 docker 容器部分相关文档。

**Comment by ChrisKong93** [comment]
这个问题怎么解决的，我宿主机里安装的nginx，然后用1panel安装的Nginx Proxy Manager，同样无法实现反向代理
