### ISSUE TITLE
[QUESTION]请问下MailServer应用安装好后要怎么配置呢，使用的是Cloudflare托管的域名。

### ISSUE THREAD

**Issue by youtao531** [1Panel-dev/1Panel#2907]
### 请描述您的问题

请问下MailServer应用安装好后要怎么配置呢，使用的是Cloudflare托管的域名。看官网的教程在搭配1Panel使用有些不太懂。

**Comment by wanghe-fit2cloud** [comment]
1Panel 应用商店是采用容器化方案部署的应用，因此需要参考 MailServer 官方文档 docker 容器部分相关文档。
