### ISSUE TITLE
[FEATURE]PHP运行时运行目录选择器支持手动输入

### ISSUE THREAD

**Issue by bh1xaq** [1Panel-dev/1Panel#2909]
### 1Panel 版本

1.8.1

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/16686956/156ece75-003a-4f7b-b3f6-669e8eece858)

目前这个选择器只能下拉选择，文件目录层级多的情况下找运行目录很麻烦，希望可以优化一下。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
