### ISSUE TITLE
[BUG]首页右上角的重启功能按钮，样式似乎没有对齐

### ISSUE THREAD

**Issue by QuentinHsu** [1Panel-dev/1Panel#2910]
### 1Panel 版本

1.8.1

### 问题描述

首页右上角的重启功能按钮，样式似乎没有对齐

<img width="791" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/21162238/c8280151-1ac5-4e78-9785-5429ed789569">

### 重现步骤

首页右上角的重启功能按钮，样式似乎没有对齐

另外，这个模板似乎有个错别字：“如果” => “如何”？

<img width="219" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/21162238/b24e371e-d690-4c4e-8404-1042b667c772">

### 期待的正确结果

<img width="731" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/21162238/cd634d95-0393-4e08-a694-bca4d3208898">

且依据下方的监控区域样式重新设置了边距

<img width="806" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/21162238/dd9e4f53-0e82-4e3f-b578-d4836404eb87">

**Comment by QuentinHsu** [comment]
我在 #2911 尝试了优化

**Comment by wanghe-fit2cloud** [comment]
v1.8.2 版本已发布。
