### ISSUE TITLE
[QUESTION]dataease能否更新到2.0版本

### ISSUE THREAD

**Issue by yneshefvf740** [1Panel-dev/1Panel#2912]
### 请描述您的问题

最近看dataease已经升级到2.0了，但是在应用商店中还是只能安装1.8版本

**Comment by maninhill** [comment]
我们计划在DataEase 发布 v2.1 时进行上架更新，十二月份第一周。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
