### ISSUE TITLE
[FEATURE]是否考虑增加WINDOW版本

### ISSUE THREAD

**Issue by wwb7700** [1Panel-dev/1Panel#2913]
### 1Panel 版本

1.0

### 请描述您的需求或者改进建议

是否考虑增加WINDOW版本，非常感谢

**Comment by maninhill** [comment]
感谢你的建议，我们中短期还没有 Windows 版的开发计划，还需要时间把 Linux 版做的更好一些。

**Comment by wwb7700** [comment]
> 感谢你的建议，我们中短期还没有 Windows 版的开发计划，还需要时间把 Linux 版做的更好一些。

感谢您的回复，谢谢，支持！
