### ISSUE TITLE
[BUG] Chinese characters cannot be displayed during installation process. 中文字符不能显示

### ISSUE THREAD

**Issue by ZhangChengX** [1Panel-dev/1Panel#2914]
### 1Panel 版本

1.8.1

### 问题描述

在某些VPS预装的默认系统中不支持中文显示，导致安装1Panel过程中无法显示中文字符，但安装后网页一切正常，建议安装过程中的语言改为英文或中英文一起显示。

![image](https://github.com/1Panel-dev/1Panel/assets/9084543/c11339eb-e9af-478d-aa61-a7561fda49ee)

### 重现步骤

在不支持中文字符的系统中安装

**Comment by wanghe-fit2cloud** [comment]
当前版本可以尝试手动修改系统的默认字符集来解决上述问题。

**Comment by ZhangChengX** [comment]
假设某人第一次在不支持中文的服务器上面安装，安装过程中的中文显示为乱码，那么这个人根本不知道是哪个语言出现了乱码，也不知道应该修改系统的默认字符集为什么字符集。
