### ISSUE TITLE
[FEATURE] 管理员密码应该为不可逆的加密方式

### ISSUE THREAD

**Issue by ZhangChengX** [1Panel-dev/1Panel#2915]
### 1Panel 版本

1.8.1

### 请描述您的需求或者改进建议

目前管理员密码虽然是加密储存在sqlite中的，
但还是可以根据1pctl user-info中的源码解密管理员的明文密码，
建议改为类似md5的不可逆加密方式，
提供在terminal中重新设置新密码的命令，而不是获取现有密码明文的命令。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中持续优化。

**Comment by wanghe-fit2cloud** [comment]
最新版本已支持上述需求。
