### ISSUE TITLE
[FEATURE]快照支持WebDAV

### ISSUE THREAD

**Issue by carolcoral** [1Panel-dev/1Panel#2917]
### 1Panel 版本

1.8.1

### 请描述您的需求或者改进建议

目前的快照备份仅能支持第三方备份帐号中没有常用的备份云盘方式，能否增加使用WebDAV帐号的方式进行快照备份

### 请描述你建议的实现方案

第三方备份帐号中新增WebDAV帐号方式，填写对应的 http(s):x.x.x.x:5005(5006) 地址访问webdav服务。

* 注意
webdav需要调试支持本地方式连接

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复 https://github.com/1Panel-dev/1Panel/issues/367
