### ISSUE TITLE
怎么更新磁盘容量

### ISSUE THREAD

**Issue by wangz1yu** [1Panel-dev/1Panel#2918]
### 请描述您的问题

您好，由于目前服务器磁盘已扩容，请问怎么更新1panel面板显示的磁盘大小

**Comment by ssongliu** [comment]
感谢反馈！ 1Panel 磁盘大小获取命令是： `df -hT -P|grep '/'|grep -v tmpfs|grep -v 'snap/core'|grep -v udev` ，可以检查一下对应磁盘是否扩容成功。

**Comment by wangz1yu** [comment]
可以了 谢谢
