### ISSUE TITLE
[FEATURE] 优化关键操作容错

### ISSUE THREAD

**Issue by likecutie** [1Panel-dev/1Panel#2921]
### 1Panel 版本

1.8.1

### 请描述您的需求或者改进建议

![图片](https://github.com/1Panel-dev/1Panel/assets/49803345/325a461d-0da5-452d-8306-5590668f4a79)
建议在关键操作中添加倒计时内不可点击确定的功能，以免误操作。
生产环境重启服务器是很严肃的事情，放面板首页右上角感觉很轻率。

**Comment by maninhill** [comment]
可以优化成：输入特定文案。确认无误后，执行操作。

**Comment by wanghe-fit2cloud** [comment]
v1.8.2 版本已发布。
