### ISSUE TITLE
希望增加防火墙规则选择

### ISSUE THREAD

**Issue by ifacecn** [1Panel-dev/1Panel#2922]
### 1Panel 版本

1.8.1

### 请描述您的需求或者改进建议

希望面板自带防火墙增加一键屏蔽国外ip访问限制，非常完美的一个功能，期待集成

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述需求。

**Comment by zyyfit** [comment]
1.9.0 版本增加了 【工具箱 - fail2ban】工具，可以自动屏蔽登录失败的IP

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
