### ISSUE TITLE
[FEATURE]应用商店增加Supervisor进程管理支持

### ISSUE THREAD

**Issue by yanzzchn** [1Panel-dev/1Panel#2923]
### 1Panel 版本

v1.8.1

### 请描述您的需求或者改进建议

项目基本上都会使用到进程守护，来运行和保持一些后台进程，比如PHP消息队列等等，此需求对程序员来说可以说是逃不掉的工具，一般都回通过命令行进行配置和管理，但是如果使用了面板再到命令行来进行安装和管理，那面板的意义就不大了。此功能在宝塔等面板中都存在很久了，不知为何这么频繁使用的应用在 1panel的应用商店中却找不到，有点匪夷所思。

### 请描述你建议的实现方案

基于Supervisor开发的进程守护工具，可以让进程开机启动，异常关闭自动重启

**Comment by zhengkunwang223** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/d2c8586d-852b-4cc3-bb42-bd3d5a4e5945)
