### ISSUE TITLE
[BUG]上传文件有BUG。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#2927]
### 1Panel 版本

v 1.8.0

### 问题描述

搭建了一个navidrome，然后上传MP3时，我拖动100个Mp3，上传列表会自动减小一部分，可能就只有50个了。
最后我一次拖动四个MP3,有时上传列表也会自动刷新成一个。
最后实在没办法，我只有一个个的上传！

之前版本都没这个问题，自从更新1.8.0版后就出这种问题，希望尽快修复！！！

### 重现步骤

上传多文件

**Comment by wanghe-fit2cloud** [comment]
已知问题，我们将在 v1.8.2 版本修复该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.8.2 版本已发布。
