### ISSUE TITLE
[BUG]镜像删除提示框提示信息有问题。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#2928]
### 1Panel 版本

v1.8.0

### 问题描述

删除标签为空的镜像时，弹框显示有问题，如图：
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/6ad6bd99-a614-4acd-96ab-18fe3e2a6ac6)

### 重现步骤

进入 `容器` - `镜像` 列表，删除部分标签为空的镜像。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们将在 v1.8.2 版本优化上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.8.2 版本已发布。
