### ISSUE TITLE
[BUG] openResty 安装超过一小时，没有停止安装或者安装日志查看方式

### ISSUE THREAD

**Issue by helson-lin** [1Panel-dev/1Panel#293]
### 联系方式

helsonlin@163.com

### 1Panel 版本

v1.0.1

### 问题描述

从应用商店安装 openResty 超过一个小时没有任何反应

cpu:`n5105` 内存：16g 安装过程cpu占用不超过5% 
系统为unbuntu 22.0.4

### 重现步骤

openResty 安装长时间无响应

**Comment by zhengkunwang223** [comment]
是公有云环境吗？

**Comment by helson-lin** [comment]
> 是公有云环境吗？

不是 小主机，目前已经安装了4小时了，我看面板日志没有openResty相关的日志

**Comment by zhengkunwang223** [comment]
> > 是公有云环境吗？
> 
> 
> 
> 不是 小主机，目前已经安装了4小时了，我看面板日志没有openResty相关的日志

一般是网络原因，不过4小时没装下来我们应该判断超时，我们改进一下这里。

**Comment by helson-lin** [comment]
> > > 是公有云环境吗？
> > 
> > 
> > 不是 小主机，目前已经安装了4小时了，我看面板日志没有openResty相关的日志
> 
> 一般是网络原因，不过4小时没装下来我们应该判断超时，我们改进一下这里。

我手动启动了docker 但是服务状态还是正在安装。 建议可以手动终止或者超时自定停止。目前没有方法去解决这个状态了。
我卸载重装试一试

**Comment by helson-lin** [comment]
> > > 是公有云环境吗？
> > 
> > 
> > 不是 小主机，目前已经安装了4小时了，我看面板日志没有openResty相关的日志
> 
> 一般是网络原因，不过4小时没装下来我们应该判断超时，我们改进一下这里。

卸载面板重新安装没有问题了，可以考虑优化一下这个安装超时问题

**Comment by xs-alpha** [comment]
安装不上，什么玩意，操，换宝塔了

**Comment by HaoShuangZ** [comment]
[问题原因和解决方法](https://bbs.fit2cloud.com/t/topic/13693)
如果卡死重启下面板 删除升级或者降低
