### ISSUE TITLE
[FEATURE] 升级nginx-proxy-manager到2.10.4

### ISSUE THREAD

**Issue by jamebal** [1Panel-dev/1Panel#2932]
### 1Panel 版本

1.8.1

### 请描述您的需求或者改进建议

升级nginx-proxy-manager到2.10.4

**Comment by zhengkunwang223** [comment]
好的

**Comment by wanghe-fit2cloud** [comment]
v1.8.2 版本已发布，进入应用商店列表，手动点击右上角的 `更新应用列表` 按钮。
