### ISSUE TITLE
[BUG]首页状态好像不能识别服务器创建的SWAP分区

### ISSUE THREAD

**Issue by youtao531** [1Panel-dev/1Panel#2934]
### 1Panel 版本

v1.8.1

### 问题描述

首页状态好像不能识别服务器创建的SWAP分区

### 重现步骤

RT

**Comment by ssongliu** [comment]
感谢反馈，后续版本考虑通过 sdk 获取。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
