### ISSUE TITLE
[BUG] 可升级列表中无法显示minIO

### ISSUE THREAD

**Issue by jxpeng98** [1Panel-dev/1Panel#2938]
### 1Panel 版本

1.8.2

### 问题描述

公告显示minIO已经更新。已安装列表仍然是之前的版本：
<img width="357" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/83734772/3c5e9757-1adc-4b56-959a-3631bcea1ddb">

但在可升级列表中也没有minIO
<img width="1463" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/83734772/72626bb1-6a83-4d32-9318-37185debe956">

除了重装之外，有什么办法可以解决这个问题然后正常升级吗？

### 重现步骤

应用商店安装，然后去可升级列表查看。 

### 期待的正确结果

能够像其他app一样正常升级。
<img width="1024" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/83734772/7b4d2dbf-a3ba-4122-97f5-bf3aa8715354">

**Comment by wanghe-fit2cloud** [comment]
> 除了重装之外，有什么办法可以解决这个问题然后正常升级吗？

不提示升级是因为第一个版本特殊的版本号导致的。
> 第一个版本之后，我们重新定义了新的 MinIO 版本号，支持应用升级操作。

**Comment by jxpeng98** [comment]
@wanghe-fit2cloud 那就只能重装了吗？

**Comment by wanghe-fit2cloud** [comment]
> @wanghe-fit2cloud 那就只能重装了吗？

是的，目前部署的版本不能直接升级。

**Comment by jxpeng98** [comment]
> > @wanghe-fit2cloud 那就只能重装了吗？
> 
> 
> 
> 是的，目前部署的版本不能直接升级。

了解了，谢谢。
