### ISSUE TITLE
[BUG]创建网站显示超时。

### ISSUE THREAD

**Issue by KKISO574** [1Panel-dev/1Panel#2940]
### 联系方式

2911074976@qq.cok,k

### 1Panel 版本

v1.8.2

### 问题描述

我的OpenResty 无法创建网站，今天没有升级OpenResty 他也创建不了，创建网站显示超时

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/68904107/be9e27c2-ca16-41c8-aeea-ce796a101efc)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by KKISO574** [comment]
1Panel-openresty-TWjL  | 185.220.101.154 - - [13/Nov/2023:22:20:06 +0800] "CONNECT d3sspl5ropfzm8.cloudfront.net:80 HTTP/1.1" 400 154 "-" "-" "-"
创建网站时最新的跟踪日志

**Comment by KKISO574** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/68904107/37061d7d-dace-4ce1-a0af-c112e8d76dfe)
不知道为什么失败

**Comment by KKISO574** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/68904107/eb2e418d-ab38-419d-847a-2f3ffca1e447)
我转了一个ufw并且开启他，在点击防火墙页面也一直也转圈报错。系统debian11 5.10.0-26-amd64

**Comment by zhengkunwang223** [comment]
网络问题吧 检查一下网络
