### ISSUE TITLE
[内存占用过大]通过面板安装常用的数据库和程序，内存占用已达60~70%，如果不用面板只有30%左右

### ISSUE THREAD

**Issue by tyultra** [1Panel-dev/1Panel#2942]
### 请描述您的问题

服务器：阿里云ECS，2核2G，Debian11 64位。
1、重置系统后，用oneinstack一键安装了MySQL5.7，PHP7.4，niginx 1.24，在阿里云控制台查看内存占用不到30%。通过X Prober查看内存占用为26.3%。
![3206659a3000432706e797ca9ac1a3e](https://github.com/1Panel-dev/1Panel/assets/36122504/3dcb6255-53b4-4ad1-9141-b7e9da96c914)

2、重置系统后，安装1Panel，在里面安装MySQL5.7，PHP7.4，OpenResty1.21，phpmyadmin，sftpgo，在阿里云控制台看到内存占用70%左右，在面板看内存占用61~64%。关掉sftpgo，在阿里云控制台看到内存占用仍为71%，在面板看内存占用降到34%。我看容器列表sftpgo的占用内存也就0.95%，不知道是内存占用的检测有误？还是我需要做什么优化/配置？
![1e6513b3455bc9529ed0157ad58e0b1](https://github.com/1Panel-dev/1Panel/assets/36122504/2e3b2182-1875-44ff-ab36-59b090f62f8f)
![image](https://github.com/1Panel-dev/1Panel/assets/36122504/e275f262-b921-4eeb-bb03-2f17fee53874)
![5ddee1eb87630c1f3ba01f7d7c479c4](https://github.com/1Panel-dev/1Panel/assets/36122504/bf8a2b77-ba51-4728-9448-4d10bacf8c0a)
![image](https://github.com/1Panel-dev/1Panel/assets/36122504/921a8d53-00fc-4ef3-b367-85cbc56fed4e)

**Comment by zhengkunwang223** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/37a5ebef-9a35-4b87-be45-496d1e317053)
可以在这查看
