### ISSUE TITLE
[FEATURE] 安装脚本最后的提示信息

### ISSUE THREAD

**Issue by XCWQW1** [1Panel-dev/1Panel#2944]
### 1Panel 版本

v1.8.2

### 请描述您的需求或者改进建议

执行完安装脚本后，如果获取的外网ip地址为IPV6地址没有在IPV6网段两侧添加方括号

### 请描述你建议的实现方案

在IPV6网段两侧添加方括号，实际应为 http://[2**********d]:33836/******

### 附加信息

![图片](https://github.com/1Panel-dev/1Panel/assets/104244911/8818edeb-b17d-4cd2-b673-131a0b3a9b82)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化 IPv6 地址显示问题。

**Comment by wanghe-fit2cloud** [comment]
最新版本已完成上述优化。
