### ISSUE TITLE
[QUESTION]flarum应用数据挂载问题

### ISSUE THREAD

**Issue by gitzaai** [1Panel-dev/1Panel#2946]
### 请描述您的问题

有朋友反馈，创建flarum应用后，
每次重启服务器，flarum的设置都会失效。

附图：默认配置
[![Snipaste_2023-11-14_14-23-07.png](https://cdnjson.com/images/2023/11/14/Snipaste_2023-11-14_14-23-07.png)](https://cdnjson.com/image/6YxJY)

**Comment by wanghe-fit2cloud** [comment]
容器内 `/data` 数据目录已经持久化到宿主机，重启后理论上不会丢失数据。
> 本地测试也没有复现丢失数据的问题。

**Comment by gitzaai** [comment]
早上朋友说到这个问题，我在我机器测试也遇到这个问题。

不知道是不是我们的用法有问题。
我们安装插件是从容器的终端进入，然后执行composer require安装 插件。
进入flarum 后台能正常启用插件。

但是重启服务器后，flarum 站点就会回到刚装完应用那个场景。

**Comment by wanghe-fit2cloud** [comment]
如果是在容器内安装的插件，重启后肯定会丢失的。
你可以基于官方的 Dockerfile 来制作全新的镜像，然后 tag 和应用使用的版本保持一致就可以。
