### ISSUE TITLE
[FEATURE]主机管理中文件上传无法支持批量文件/文件夹上传

### ISSUE THREAD

**Issue by carolcoral** [1Panel-dev/1Panel#2947]
### 1Panel 版本

1.8.2

### 请描述您的需求或者改进建议

在 `主机` - `文件` 中想要批量上传本地的内容，其中包括多个文件和多个文件夹

但是目前无法支持该上传方式，需要手动新建每个文件夹后手动上传文件

### 请描述你建议的实现方案

支持批量上传文件/文件夹
支持上传内容中同时包含文件和文件夹

**Comment by wanghe-fit2cloud** [comment]
当前版本已经支持批量上传文件或文件夹
> 不支持同时包含文件和文件夹（控件限制）

**Comment by carolcoral** [comment]
> 当前版本已经支持批量上传文件或文件夹
> 
> > 不支持同时包含文件和文件夹（控件限制）

在1panel交流群6中和`程会玩`演示过，是你们element拖拽插件的问题，无法支持拖拽上传（内容中同时包含文件及文件夹）
<img width="1418" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/8952687/c77bd805-4943-4f03-8287-e79cd008ee83">

**Comment by carolcoral** [comment]
目前解决提议为：

1. 取消element拖拽控件，等待控件功能修复后再重新放上
2. 变更element拖拽控件为自行开发的拖拽功能实现
