### ISSUE TITLE
[BUG]主机-文件的设置权限页面显示不正确

### ISSUE THREAD

**Issue by lainbo** [1Panel-dev/1Panel#2949]
### 1Panel 版本

1.8.2

### 问题描述

打开权限列表，显示的权限和实际权限不匹配

### 重现步骤

1. 随意点击一个文件的权限，呼出侧边的权限面板
2. 修改权限，增加或减少权限
3. 点击权限面板右上角的“关闭按钮”或者底部的“取消按钮”
4. 再次打开该文件的权限面板，可以观察到，打开后不是改文件的真实权限，而是刚才操作后的改动

### 期待的正确结果

期望重新打开后，显示的是正确的文件权限，而不是刚才操作后的数据残留

### 附加信息

复现GIF

![20231114_165138](https://github.com/1Panel-dev/1Panel/assets/46062895/1b187ec7-15eb-4567-a74e-d468143aec19)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，在没有手动刷新页面的情况下确实存在上述问题，我们会在近期版本修复。

**Comment by wanghe-fit2cloud** [comment]
v1.8.3 版本已发布。
