### ISSUE TITLE
[BUG]远程下载文件，希望忽略不可信证书。

### ISSUE THREAD

**Issue by xiahao90** [1Panel-dev/1Panel#2950]
### 联系方式

xiahao90@qq.com

### 1Panel 版本

1.8.2

### 问题描述

服务内部错误: Get "https://xxxxxx/down/JoXhDkfXDXK5.gz": tls: failed to verify certificate: x509: certificate signed by unknown authority

### 重现步骤

文件管理->远程下载
填写了非信任https的压缩链接提示
服务内部错误: Get "https://xxxxxxx/down/JoXhDkfXDXK5.gz": tls: failed to verify certificate: x509: certificate signed by unknown authority

### 期待的正确结果

希望忽略不可信证书

**Comment by zhengkunwang223** [comment]
您好 麻烦给个链接 我们复现一下

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
