### ISSUE TITLE
导入数据库后mysql一直重启中

### ISSUE THREAD

**Issue by HtOGsaN00** [1Panel-dev/1Panel#2952]
### 请描述您的问题

你好，我的网站在导入过去已备份的数据库后mysql就一直重启中。可以停止，但再启动时无论怎样都是重启中。
1Panel版本：1.8.2，上一个版本也存在这个问题
mysql版本：8.2.0

**Comment by ssongliu** [comment]
感谢反馈，麻烦贴一下容器日志。

**Comment by HtOGsaN00** [comment]
你好，附上所有日志
[1Panel-mysql-vLJf-20231114203600.log](https://github.com/1Panel-dev/1Panel/files/13348787/1Panel-mysql-vLJf-20231114203600.log)

**Comment by ssongliu** [comment]
> 你好，附上所有日志 [1Panel-mysql-vLJf-20231114203600.log](https://github.com/1Panel-dev/1Panel/files/13348787/1Panel-mysql-vLJf-20231114203600.log)

导入的备份文件也是 8.2 版本的吗？

**Comment by HtOGsaN00** [comment]
应该不是，我忘记具体的版本号了...是否可以查询当时的版本？我现在同时放了2个网站，一个新建的，另一个导入的，导入的这个导致2个网站的数据库都崩了，是否有办法挽回？

**Comment by ssongliu** [comment]
大概率是数据库版本的问题，可以重新安装一个之前相同版本的数据库然后恢复。
