### ISSUE TITLE
[FEATURE]面板数据库管理支持PostgreSQL

### ISSUE THREAD

**Issue by Maklith** [1Panel-dev/1Panel#2954]
### 1Panel 版本

1.8.2

### 请描述您的需求或者改进建议

目前数据库管理页面只支持Mysql和Redis,希望增加PostgreSQL的支持.
虽然在应用商店有对应的管理应用,但对于轻量级添加数据库编辑很重要
同时支持对PostgreSQL数据库的备份

**Comment by ssongliu** [comment]
感谢反馈，后续版本支持。

**Comment by wanghe-fit2cloud** [comment]
重复 #758
