### ISSUE TITLE
[QUESTION] 为网站开启 HTTPS 多次提示 "服务器内部错误"

### ISSUE THREAD

**Issue by bakaomg** [1Panel-dev/1Panel#2955]
## 问题描述
为网站启用 HTTPS 时提示 "服务器内部错误"，但未返回任何错误消息，网站配置文件中自动添加了 `listen 443 ssl http2 ;` 字段但没有成功添加 SSL 证书相关的字段。
查看了 OpenResty 的错误日志也并未发现相关的错误。

## 尝试方法
- 删除站点重新添加：无效
- 重新颁发证书：无效

## 相关截图
![image](https://github.com/1Panel-dev/1Panel/assets/40896676/26287056-00e1-43b5-bef8-b66989a6bd34)

## 证书颁发途径
- 1Panel 的证书创建
- 腾讯云/阿里云的免费证书

**Comment by wanghe-fit2cloud** [comment]
进 `日志审计` 页面，查看一下 `系统日志`，如下图：
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/c6cc1eb4-87fb-4f9b-b1c6-d3e33e9f37fb">

**Comment by bakaomg** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/40896676/9952494d-b13b-4b9a-92f2-a3135f8cca68)

好像是没有相关的错误信息，只有 acme 签发成功的信息

**Comment by zhengkunwang223** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/d168daf9-ecd3-4453-a99b-6a784bc7ee05)
加我微信 我远程看一下

**Comment by bakaomg** [comment]
你好，申请好友了，等待通过

**Comment by wanghe-fit2cloud** [comment]
v1.8.3 版本已发布。
