### ISSUE TITLE
[FEATURE] 给应用商店已安装界面的应用添加详情。

### ISSUE THREAD

**Issue by Anyexyz** [1Panel-dev/1Panel#2957]
### 1Panel 版本

v1.8.2

### 请描述您的需求或者改进建议

给应用商店已安装界面的应用添加详情，部分应用的安装配置内容在详情里面就可以直接点开看

### 请描述你建议的实现方案

修改源码`frontend/src/views/app-store/installed/index.vue`，添加类似`frontend/src/views/app-store/apps/index.vue`类似卡片的详情页效果

**Comment by wanghe-fit2cloud** [comment]
收到，我们会在近期版本支持上述需求。

**Comment by Anyexyz** [comment]
> 收到，我们会在近期版本支持上述需求。

~(＾◇^)/

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
