### ISSUE TITLE
database disk image is malformed (11)[QUESTION]

### ISSUE THREAD

**Issue by dudt** [1Panel-dev/1Panel#2958]
### 请描述您的问题

这个是什么错误？应该怎么恢复？现在无法进入网页端后台
![image](https://github.com/1Panel-dev/1Panel/assets/19968269/6ed3e0e5-91d3-4616-a13d-514ba76fc0d1)

**Comment by ssongliu** [comment]
感谢反馈，服务器磁盘空间还剩多少？

**Comment by dudt** [comment]
> 感谢反馈，服务器磁盘空间还剩多少？

![image](https://github.com/1Panel-dev/1Panel/assets/19968269/b6f256ec-3268-4a03-816a-7498990dbf06)

**Comment by wanghe-fit2cloud** [comment]
快照备份、恢复相关问题的讨论，统一汇总到该 issue #3041
