### ISSUE TITLE
[BUG]文件粘贴异常

### ISSUE THREAD

**Issue by lidonglonge** [1Panel-dev/1Panel#2961]
### 联系方式

1Panel交流群2   An

### 1Panel 版本

1.8.2

### 问题描述

文件如果选择复制了，去父文件夹，这个时候可以把复制的文件删除，在点击粘贴按钮，抛异常

### 重现步骤

文件如果选择复制了，去父文件夹，这个时候可以把复制的文件删除，在点击粘贴按钮，抛异常

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在后续版本中持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
