### ISSUE TITLE
[BUG]容器升级

### ISSUE THREAD

**Issue by lidonglonge** [1Panel-dev/1Panel#2962]
### 联系方式

lidonglonge@163.com

### 1Panel 版本

1.8.2

### 问题描述

需要更新现有容器，修改编排文件中镜像的版本，如果容器不存在，会把编排文件删了，容器也删了

### 重现步骤

手动需要更新现有容器，修改编排文件中镜像的版本，如果容器不存在，会把编排文件删了，容器也删了

**Comment by ssongliu** [comment]
感谢反馈，出于一致性考虑，我们没有将编排和容器列表存库，编排列表是根据容器列表筛选出来的，容器不存在时编排列表也不存在，这是正常现象。

但是这些操作并不会去删除编排文件，可以在 【主机】-【文件】中检查一下编排文件是否仍然存在。
