### ISSUE TITLE
[BUG] 升级Nginx Proxy Manager，配置的端口丢失，导致无法域名访问

### ISSUE THREAD

**Issue by mi1890** [1Panel-dev/1Panel#2963]
### 1Panel 版本

1.8.2

### 问题描述

升级Nginx Proxy Manager，配置的端口丢失，导致无法域名访问
同时关闭了ip访问，导致ip也无法访问
只能ssh 连接服务器后 reset domain

### 重现步骤

升级Nginx Proxy Manager

**Comment by wanghe-fit2cloud** [comment]
> 升级Nginx Proxy Manager

麻烦再详细讲一下升级步骤。
> 1Panel 应用商店中目前还不支持自动升级该应用，后续版本会优化。

**Comment by mi1890** [comment]
> > 升级Nginx Proxy Manager
> 
> 麻烦再详细讲一下升级步骤。
> 
> > 1Panel 应用商店中目前还不支持自动升级该应用，后续版本会优化。

在应用商店-> 可升级 界面发现Nginx Proxy Manager 可以升级，升级之后，过一会刷新页面发现无法打开， reset domain 后发现是Nginx Proxy Manager 的端口映射变回了默认的30080：80，30443：443

我是直接把80和443映射到Nginx Proxy Manager 的80和443端口，然后在Nginx Proxy Manager 中配置了域名到1panel控制面板的地址和端口，这样是否是正确用法？？？

**Comment by wanghe-fit2cloud** [comment]
在 `已安装` 应用列表点击 `进入安装目录` 按钮，在文件列表查看一下 .env 文件中的端口号。

**Comment by wanghe-fit2cloud** [comment]
先关闭这个 Issue 了。如在后续的使用过程中依然存在上述问题，我们继续在这个 Issue 中讨论。
