### ISSUE TITLE
[BUG]创建网站时，相同IP地址，只能创建一个

### ISSUE THREAD

**Issue by guandaxia** [1Panel-dev/1Panel#2964]
### 1Panel 版本

v1.8.2

### 问题描述

使用IP地址创建网站时，当创建好一个之后，再使用相同的IP和不同的端口创建时，提示“域名已存在”
![image](https://github.com/1Panel-dev/1Panel/assets/9638813/ef84393f-61aa-47f8-9bd4-39eaec7b88dc)

### 重现步骤

1、使用 8.141.90.1:3467创建网站成功
2、使用 8.141.90.1:1452创建网站，提示“域名已存在”，无法创建

### 期待的正确结果

相同域名不同端口的网站都可以正确创建

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本增加相同域名 不同端口的设置

**Comment by 9a6c** [comment]
之前版本是可以这样创建的，但是查看网站日志时分不清楚，加上端口，应该就可以分清楚了
https://github.com/1Panel-dev/1Panel/issues/2695

**Comment by zhengkunwang223** [comment]
> 之前版本是可以这样创建的，但是查看网站日志时分不清楚，加上端口，应该就可以分清楚了 #2695

现在的网站主配置文件名称是和网站主域名一致的，如果重复，会出现两个网站共用一个主配置文件的情况
所以后续也只能通过创建完修改主域名的方式来支持同 IP 网站

**Comment by zyyfit** [comment]
1.9.0 将会支持相同域名不同端口的情况，不过在创建网站时需要修改代号为不重复的代号

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
