### ISSUE TITLE
[BUG]纯ipv6的vps无法访问面板

### ISSUE THREAD

**Issue by notec-inc** [1Panel-dev/1Panel#2967]
![1](https://github.com/1Panel-dev/1Panel/assets/149647350/21961290-d066-40df-9970-bcb45eb0b9c9)
![2](https://github.com/1Panel-dev/1Panel/assets/149647350/60e63558-f768-47d7-8e0a-e5912e2e31c5)

### 1Panel 版本

当前最新版

### 问题描述

反复安装过两次1panel。
已确认ipv6是通的。
防火墙也放行了端口的tcp和udp。
均无法通过ipv6地址访问面板。
但可以通过nat的方式，通过ipv4的方式访问。
htop看到1panel正运行着。
排查无果后，我又重新开了一台ipv6机器，一摸一样的环境，安装aapanel.
没任何问题，可以通过Ipv6:port进入界面。包括其中的软件安装均无报错。
而1panel。报错php环境失败。

如果不支持ipv6，请在doc注明。

### 重现步骤

反复安装过两次1panel。
已确认ipv6是通的。
防火墙也放行了端口的tcp和udp。
均无法通过ipv6地址访问面板。
但可以通过nat的方式，通过ipv4的方式访问。
htop看到1panel正运行着。
排查无果后，我又重新开了一台ipv6机器，一摸一样的环境，安装aapanel.
没任何问题，可以通过Ipv6:port进入界面。包括其中的软件安装均无报错。
而1panel。报错php环境失败。

如果不支持ipv6，请在doc注明。

**Comment by notec-inc** [comment]
1panel界面和功能体验都很优秀，就是bug有点多，特别是core部分。很难用于生产。希望开发者能应对一些特殊场景。
比如natv4+ipv6only或者ipv6only 的适配。

**Comment by ssongliu** [comment]
感谢反馈，执行` netstat -tunlp ｜ grep 端口` 看一下服务是否监听在 ipv4 上，可以通过 `1pctl listen-ip ipv6` 调整到监听 ipv6。

**Comment by ssongliu** [comment]
> 1panel界面和功能体验都很优秀，就是bug有点多，特别是core部分。很难用于生产。希望开发者能应对一些特殊场景。 比如natv4+ipv6only或者ipv6only 的适配。

具体还有哪些 bug，可以多多反馈一下。

**Comment by notec-inc** [comment]
> 
root@lxc-101:~# netstat -tunlp ｜ grep
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      272/master          
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      104/systemd-resolve 
tcp        0      0 0.0.0.0:12345           0.0.0.0:*               LISTEN      2809/1panel         
tcp6       0      0 :::22                   :::*                    LISTEN      1/init              
tcp6       0      0 ::1:25                  :::*                    LISTEN      272/master          
udp        0      0 127.0.0.53:53           0.0.0.0:*                           104/systemd-resolve

**Comment by ssongliu** [comment]
> tcp 0 0 0.0.0.0:12345 0.0.0.0:* LISTEN 2809/1panel

`tcp 0 0 0.0.0.0:12345 0.0.0.0:* LISTEN 2809/1panel ` 监听的是 ipv4，可以使用上面发的命令调整一下。

**Comment by notecdotcom** [comment]
> > tcp 0 0 0.0.0.0:12345 0.0.0.0:* LISTEN 2809/1panel
> 
> `tcp 0 0 0.0.0.0:12345 0.0.0.0:* LISTEN 2809/1panel ` 监听的是 ipv4，可以使用上面发的命令调整一下。

ipanel对监听端口的设置在哪个路径的哪个文件？

**Comment by notec-inc** [comment]
的确可以了，谢谢，希望这条命令能加入到script中，检查运行。

**Comment by notec-inc** [comment]
> > 1panel界面和功能体验都很优秀，就是bug有点多，特别是core部分。很难用于生产。希望开发者能应对一些特殊场景。 比如natv4+ipv6only或者ipv6only 的适配。
> 
> 具体还有哪些 bug，可以多多反馈一下。

镜像 build 失败:failed to solve: process "/bin/sh -c chmod +x install.sh && sh install.sh && rm -rf /tmp/extensions RUN apk add tzdata && cp \"/usr/share/zoneinfo/$TZ\" /etc/localtime && echo \"$TZ\" > /etc/timezone" did not complete successfully: exit code: 1

这是php8.2.10安装的失败msg
