### ISSUE TITLE
[FEATURE]希望icon图标可以自定义或关闭显示

### ISSUE THREAD

**Issue by 52lemon6** [1Panel-dev/1Panel#297]
### 1Panel 版本

1.0.2

### 请描述您的需求或者改进建议

望icon图标可以自定义或关闭显示，fofa一类资产收集工具可以通过icon图标来查找相关联的网站从而获取ip、端口、域名等信息
↓，icon图标已经在fofa数据库里了
![image](https://user-images.githubusercontent.com/40059643/226108001-a3e8e510-6483-4012-88a0-c0b55ec47f19.png)

**Comment by zhengkunwang223** [comment]
您好 感谢反馈 我们后续处理这个问题

**Comment by maninhill** [comment]
> ### 1Panel 版本
> 1.0.2
> 
> ### 请描述您的需求或者改进建议
> 望icon图标可以自定义或关闭显示，fofa一类资产收集工具可以通过icon图标来查找相关联的网站从而获取ip、端口、域名等信息 ↓，icon图标已经在fofa数据库里了 ![image](https://user-images.githubusercontent.com/40059643/226108001-a3e8e510-6483-4012-88a0-c0b55ec47f19.png)
> 
> ### 请描述你建议的实现方案
> _No response_
> 
> ### 附加信息
> _No response_

老哥专业。

**Comment by bddjr** [comment]
不如把https跨域拒绝握手也做了

我搜到的其中第一页里大多数都是给IP自签证书，并且证书的ca名称写了“1Panel”

有一个不是给IP签，但是暴露了域名

然后还有安全入口页面的命令也暴露是1Panel

**Comment by wanghe-fit2cloud** [comment]
> 不如把https跨域拒绝握手也做了
> 
> 我搜到的其中第一页里大多数都是给IP自签证书，并且证书的ca名称写了“1Panel”
> 
> 有一个不是给IP签，但是暴露了域名
> 
> 然后还有安全入口页面的命令也暴露是1Panel

感谢反馈。
1、预计 5 月份推出的专业版会支持自定义 icon 功能；
2、自定义安全入口页面也会在近期支持。

**Comment by bddjr** [comment]
我建议图标`favicon.ico`以及所有网页资源都挂载在安全入口目录下，防止非安全入口意外加载这些可能带有特征的东西  

非安全入口的页面可以直接返回404

跨域https握手直接拒绝连接，防止证书暴露特征，除非证书包含IP

**Comment by bddjr** [comment]
还有，这个issue给的关键词是“1Panel”，而不是确切的1Panel面板，这导致fofa把openresty搭建的网站也识别到里面了，然后就看到大量的其它图标

我不知道说楼主专业的人怎么想的

**Comment by bddjr** [comment]
总之这个issue有点无厘头，fofa识别1Panel不只是靠图标，还会靠自签证书、响应头。

甚至，使用像issue里示范的模糊搜索，任何可以用1Panel轻松搭建的东西都有可能被识别成1Panel

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
