### ISSUE TITLE
[QUESTION]网站重定向

### ISSUE THREAD

**Issue by Bigzzh2022** [1Panel-dev/1Panel#2970]
### 请描述您的问题

一键部署wordpress，主域名设置为www.bigzzh.top，其它域名设置为bigzzh.top。未设置任何重定向，浏览器地址栏输入www.bigzzh.top会跳转到bigzzh.top。设置重定向，域名为bigzzh.top，目标为http://www.bigzzh.top，浏览器会出现www.bigzzh.top 重定向次数过多报错。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by zhengkunwang223** [comment]
> wordpress

wordpress 的访问地址设置了吗？
清理一下浏览器缓存

**Comment by Bigzzh2022** [comment]
Wordpress访问地址是默认的，没改过。浏览器缓存清理了没用

**Comment by Bigzzh2022** [comment]
修改Wordpress地址和站点地址后问题解决。🙏
