### ISSUE TITLE
[BUG]希望能对ipv6的支持深度一些

### ISSUE THREAD

**Issue by mushokumunou** [1Panel-dev/1Panel#2971]
### 1Panel 版本

v1.8.2

### 问题描述

纯ipv6的机器。进行反代的时候，默认的配置文件是80
而不是[::]:80
导致应用反代后也无法打开。
并且一些应用开放的端口也是指的v4的端口，并非v6。导致很多应用即便选了开放端口，也无法通过v6来访问。

### 重现步骤

同上

**Comment by zhengkunwang223** [comment]
创建网站的时候可以选择 监听 IPV6端口

**Comment by wanghe-fit2cloud** [comment]
目前安装应用暴露的端口默认绑定的是 IPv4 端口，可以尝试手动在 `容器` - `配置` 页面配置 IPv6 相关设置。
> 我们会在近期版本支持容器 IPv6 设置。

**Comment by zyyfit** [comment]
应用开放端口在 1.9.0 版本改为 ipv6和ipv4端口同时开放

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
