### ISSUE TITLE
[BUG]1panel 1.8.2 多台VPS 使用DNS摸式创建证书全部失败。

### ISSUE THREAD

**Issue by beload** [1Panel-dev/1Panel#2972]
### 联系方式

beload@gmail.com

### 1Panel 版本

1.8.2

### 问题描述

1panel 1.8.2 多台VPS 使用DNS摸式创建证书全部失败，出现以下错误：

服务内部错误: error: one or more domains had a problem: [lion.gopass.xyz] time limit exceeded: last error: read udp [2607::::1ef4]:24478->[2606:4700:58::adf5:3b59]:53: i/o timeout

但是在命令行下使用acme.sh 创建证书成功。
同样证书在1.7.2的版本VPS创建成功。

### 重现步骤

多台VPS 使用DNS摸式创建证书全部失败

**Comment by zhengkunwang223** [comment]
i/o timeout 超时 应该是与你的网络环境相关
我在搜索引擎中搜到这个
https://docs.directadmin.com/directadmin/general-usage/managing-ips.html#ipv6-how-to
不知道对你是否有用

**Comment by lifei6671** [comment]
我也是升级到1.8.2后，证书申请总是失败。

**Comment by wanghe-fit2cloud** [comment]
> 我也是升级到1.8.2后，证书申请总是失败。

麻烦提供一下系统日志，如下图：
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/87b72ca2-dade-4983-bd89-1bc2a9aaf5f0">
