### ISSUE TITLE
[FEATURE]应用商店添加多种分发

### ISSUE THREAD

**Issue by okxlin** [1Panel-dev/1Panel#2977]
### 1Panel 版本

v1.8.2

### 请描述您的需求或者改进建议

希望应用商店添加多CDN分发，cloudflare等。

- 当出现第一个获取超时，则使用其他方式获取。

阿里云的最近稳定性好像不太好，且长期以来会有发现国际互联效果不太好，导致应用商店官方应用加载空白。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先尝试增加超时时间等手段来优化用户体验。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
