### ISSUE TITLE
[FEATURE]建议增加系统IP地址设置和系统名称设置

### ISSUE THREAD

**Issue by lcese** [1Panel-dev/1Panel#2978]
### 1Panel 版本

1.8

### 请描述您的需求或者改进建议

一、建议增加系统IP地址设置
新安装的初始化系统IP地址是DHCP分发的，如果面板增加IP地址修改功能，就不需要再一一的去编辑文件了；
二、系统名称设置
有些系统名称时间长了感觉定义不好。面板里面直接修改系统名称会更方便一点。

**Comment by ssongliu** [comment]
感谢反馈，第一点的意思是修改系统监听 ip 地址吗？ 第二点会在 v1.9.0 版本完成。

**Comment by lcese** [comment]
> 感谢反馈，第一点的意思是修改系统监听 ip 地址吗？ 第二点会在 v1.9.0 版本完成。

是的，就是系统监听IP地址

**Comment by zyyfit** [comment]
@lcese 
1.8 版本中已经支持监听IP地址啦
![image](https://github.com/1Panel-dev/1Panel/assets/73461316/27ac9541-9972-420b-a4ac-c5c30f5dba9c)

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
