### ISSUE TITLE
[BUG]构建镜像时/opt/1panel/tmp/docker_logs子文件夹需要手动创建才能继续构建

### ISSUE THREAD

**Issue by youtao531** [1Panel-dev/1Panel#2979]
### 1Panel 版本

v1.8.2

### 问题描述

构建镜像时/opt/1panel/tmp/docker_logs子文件夹需要手动创建才能继续构建

### 重现步骤

RT

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，请问 1Panel 服务器是什么操作系统？

**Comment by youtao531** [comment]
ubuntu-22.04

**Comment by ssongliu** [comment]
如果没有这个文件夹是构建镜像的时候报错吗？能否截图看一下错误信息？

**Comment by youtao531** [comment]
<img width="1435" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/8513513/ad2a91f8-df04-48f5-a973-60124bcede4d">
会缺少子目录，我手动创建后就可以继续构建
