### ISSUE TITLE
不能添加同一ip不同端口的主机

### ISSUE THREAD

**Issue by zxwmfcm** [1Panel-dev/1Panel#2981]
### 1Panel 版本

1.8.2

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/30642864/f700c9bf-ddcf-4d4c-bd23-22528d2568c0)
我添加同一ip不同端口的主机就直接修改原有的主机了   
这里添加主机能不能以标题或者ip+端口的判断是否是同一主机

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我刚在本地测试环境测试未复现上述问题，可以成功添加同一 IP 不同端口的主机，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/74729726-696f-4f24-b559-6d3bb4bd3dfa)
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/329a0303-85f0-42e6-966b-8c5f8f056a05)

**Comment by zxwmfcm** [comment]
没问题了  能加上了
