### ISSUE TITLE
[FEATURE]1Panel间无缝迁移

### ISSUE THREAD

**Issue by carolcoral** [1Panel-dev/1Panel#2984]
### 1Panel 版本

1.8.2

### 新特性
> 支持1p从另外一个1p迁移全部/部分内容

例如我新机器是 test1.cnkj.site 上的1p，想要从我旧机器 test2.cnkj.site 上把数据库、网站、证书全部自动同步过来，不然换机器的话重新同步也太痛苦了

### 请描述你建议的实现方案

1. 实现自助生成 TOKEN 密钥，不同 1Panel 之间可以通过 TOKEN 获得授权执行无缝迁移
2. 不同 1Panel 之间可以控制 A 从 B 中选择某些服务内容进行同步。例如：网站、证书、应用（包括相关关联文件）、设置等
3. 通信协议可以采用 HTTP(S) 进行面板之间的通信

**Comment by okxlin** [comment]
试试 `面板设置` 菜单里的 `快照` 功能？

**Comment by carolcoral** [comment]
> 试试 `面板设置` 菜单里的 `快照` 功能？

快照是整体备份，可是我可能实际上只想要同步 `证书` 和 `网站` 呢，假设我又20个证书需要同步，如果每个都要手动上传和配置也太痛苦了
@wanghe-fit2cloud @okxlin

**Comment by carolcoral** [comment]
例如我两个1Panel面板之间有部分服务其实是不同的，例如 A 面板上存在10个证书，目前想要将即将销毁的服务器上的B面板的20个证书和网站 `增量` 同步过来这种情景呢
