### ISSUE TITLE
[FEATURE]可否升级一下discuz，目前版本还是3.4，希望能尽快升级到3.5

### ISSUE THREAD

**Issue by stillyoung91** [1Panel-dev/1Panel#2985]
### 1Panel 版本

v1.8.2

### 请描述您的需求或者改进建议

应用商店discuz目前版本还是3.4，希望能尽快升级到3.5

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们还未检测到 discuz 官方提供的 v3.5 版本镜像。
> 可以考虑使用创建 PHP 运行环境的方式来安装最新版本。
B 站有建站视频：https://space.bilibili.com/510493147/channel/collectiondetail?sid=1199760
项目源码：https://gitee.com/Discuz/DiscuzX/releases
