### ISSUE TITLE
[FEATURE] 编排容器升级问题

### ISSUE THREAD

**Issue by gee1k** [1Panel-dev/1Panel#2986]
### 1Panel 版本

v1.8.2

### 请描述您的需求或者改进建议

目前无法在编排页面中进行一键升级，只能在容器列表中，对单个容器进行升级。希望能在编排页面中增加一键升级整个编排的容器功能。相当于在对应编排目录执行：
```
docker compose stop
docker compose pull
docker compose up -d
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
推荐使用 `容器编排` 页面的 编辑 功能来实现上述功能。
> 自行修改 compose 文件中涉及到的容器镜像版本。
