### ISSUE TITLE
[QUESTION] 关于一键快速安装脚本中的 Docker 和 Compose

### ISSUE THREAD

**Issue by suiyueou** [1Panel-dev/1Panel#2988]
### 1Panel 版本
v1.8.2

### 请描述您的问题

1. 官网的一键安装命令运行时或许应该加上 `sudo` 前缀, 否则非 root 用户在执行 Docker (Docker-Compose) 安装脚本时可能会因为权限不足而提示失败. 如: `... && sudo bash quick_start.sh`. Docker 官方脚本中也提到了需要 root 和 sudo 权限:

![image](https://github.com/1Panel-dev/1Panel/assets/48700331/52a7861b-885d-4248-b625-89f27b2aa6cc)

错误日志:

![image](https://github.com/1Panel-dev/1Panel/assets/48700331/599a5d46-9909-490d-ac5b-c682fe7ccd9d)

和

![image](https://github.com/1Panel-dev/1Panel/assets/48700331/f9895cbc-aee9-49c6-8b79-01a9f6e90657)

2. Docker 自 Docker Compose 进入 2.x 版本之后 (大概 2021 年)，Docker 便通过 Plugins 原生集成 Compose，不在需要独立安装，只不过命令与独立安装的有所区别，集成的 compose 命令为：`docker compose [OPTIONS] COMMAND`，与独立安装的区别为少了一个连结符 `-`, 更加简洁方便, 使用 `docker info` 可以看到相关信息和版本:

![image](https://github.com/1Panel-dev/1Panel/assets/48700331/b1c2b9ab-4d58-4441-8081-7d82408fd68e)

内置版本甚至比脚本独立进行安装的版本要高:

![image](https://github.com/1Panel-dev/1Panel/assets/48700331/594d817c-7e64-4d45-b0ab-0923715a1e21)

故而强烈推荐 1panel 直接通过内置的 compose 进行容器编排, 省去重复进行独立安装 compose 的相关步骤, 有关 compose 内置的具体信息可点击 [此处](https://docs.docker.com/compose/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2) 跳转官方文档说明进行查看.

3. 一键安装脚本在安装完毕后, 似乎不会自动清理安装过程中下载的安装脚本文件等.

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1、针对不同操作系统和非 root 用户，可以参考官方文档不同的安装脚本：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/1cebc956-f13c-4bf9-84b3-861e43ef2e77)
2、系统中已经集成了 `docker-compose` 的一部分功能，后续版本会考虑统一升级。
3、目前还是需要手动清理安装文件。

**Comment by suiyueou** [comment]
1. 上述的报错信息来自 Debian 系统, 而官方文档中 Debian 的安装脚本没有添加 `sudo` 前缀.
2. 明白了, 持续期待后续升级(~

**Comment by wanghe-fit2cloud** [comment]
> 1. 上述的报错信息来自 Debian 系统, 而官方文档中 Debian 的安装脚本没有添加 `sudo` 前缀.

好的，有一些 Debian 操作系统默认没有安装 sudo，就没有体现在安装脚本中。
> 可以参考 Ubuntu 系统的在线安装脚本手动添加 sudo 。

**Comment by suiyueou** [comment]
> 好的，有一些 Debian 操作系统默认没有安装 sudo，就没有体现在安装脚本中。

原来如此，明白了（~

**Comment by Mr-Ao-Dragon** [comment]
> 3、目前还是需要手动清理安装文件。

直接丢进/tmp
