### ISSUE TITLE
[FEATURE] 上传文件时需要增加允许强制覆盖已经被使用的文件

### ISSUE THREAD

**Issue by qwenode** [1Panel-dev/1Panel#2989]
### 1Panel 版本

1.8.2

### 请描述您的需求或者改进建议

有些单体程序在运行中,更新的时候需要覆盖该文件,目前上传会显示 file is busy 无法覆盖

### 请描述你建议的实现方案
![image](https://github.com/1Panel-dev/1Panel/assets/8974108/409fc2d5-5e44-487e-b449-d23a0dae1bb1)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。
