### ISSUE TITLE
[BUG] UI问题- 主机->监控中每个card中右上角的时间选择器宽度设置太小导致显示不完整

### ISSUE THREAD

**Issue by kebug** [1Panel-dev/1Panel#299]
### 联系方式

kebug

### 1Panel 版本

v1.0.2

### 问题描述

主机->监控中每个card中右上角的时间选择器宽度设置太小导致显示不完整。我看是手动设置了组件的宽度是330px，不同数字宽度存在不同，可以设置大一点。
<img width="1892" alt="image" src="https://user-images.githubusercontent.com/33097400/226115456-39f4ea92-5f15-455a-bd75-e091e2c965e3.png">
<img width="437" alt="image" src="https://user-images.githubusercontent.com/33097400/226115533-620516a8-aed0-42d4-87be-9e3f092e0280.png">

### 重现步骤

不同字体数字宽度存在差异，字体PingFangSC-Regular中一般宽度 1 < 7 < 0,2,3,4,5,6,8,9。可以全部设置为最宽数字确定组件最大宽度。

### 期待的正确结果

完整显示日期时间选择器中的数字。

### 相关日志输出

```shell
样式问题，无代码。
```

### 附加信息

感谢你们的工作，贡献出如此好用的开源工具。

**Comment by zhengkunwang223** [comment]
感谢提出的宝贵建议，我们会在后续版本修复
