### ISSUE TITLE
[BUG] 无法通过ipv6直接访问容器

### ISSUE THREAD

**Issue by notec-inc** [1Panel-dev/1Panel#2990]
### 1Panel 版本

v1.8.2

### 问题描述

尝试了几个容器，发现ddns-go是可以直接ipv6:port 进行访问的。
看了下yaml，其中定义了network_mode: host 
一葫芦画瓢，尝试更改flarum的network 为 host
但始终无法通过ipv6 访问。

大概率应该是flarum这个容器还是需要1panel_bridge这个网卡对其他容器（php,mysql）进行通信，所以取消掉这个不行？

对compose不太了解，面板也没提供选择网卡的选项。所以想问问，官方是否有解决方案？

### 重现步骤

同上

**Comment by notec-inc** [comment]
ipv6 普及，ipv4 耗尽，希望官方能进一步让1panel全面支持ipv6，诸如ipv6整段下发，让容器都能dhcp方式获取到独立的ipv6。这样端口就不需要反代（反代会出现一些问题，比如真实ip无法获取等。）

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们预计在 v1.9.0 版本支持可视化配置容器 IPv6。

**Comment by mushokumunou** [comment]
> 感谢反馈，我们预计在 v1.9.0 版本支持可视化配置容器 IPv6。

可以參考這篇文章：
[https://www.spiritysdx.top/20230829/](https://www.spiritysdx.top/20230829/)

新建一個網橋用作ipv6的自動獲取。還有就是防火墻就不能單獨控制了。希望官方能考慮一下

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈，我们预计在 v1.9.0 版本支持可视化配置容器 IPv6。
> 
> 可以參考這篇文章： https://www.spiritysdx.top/20230829/
> 
> 新建一個網橋用作ipv6的自動獲取。還有就是防火墻就不能單獨控制了。希望官方能考慮一下

是的，需要同步修改 docker 配置文件、容器所用网络等，近期版本会支持。

**Comment by zaqai** [comment]
> > > 感谢反馈，我们预计在 v1.9.0 版本支持可视化配置容器 IPv6。
> > 
> > 
> > 可以參考這篇文章： https://www.spiritysdx.top/20230829/
> > 新建一個網橋用作ipv6的自動獲取。還有就是防火墻就不能單獨控制了。希望官方能考慮一下
> 
> 是的，需要同步修改 docker 配置文件、容器所用网络等，近期版本会支持。

不确定你们说的是不是这个, 在应用商店安装的docker容器默认只监听ipv4, 在安装目录的.env文件里, `HOST_IP="0.0.0.0"`, 希望可以改成都监听

**Comment by wanghe-fit2cloud** [comment]
> > > > 感谢反馈，我们预计在 v1.9.0 版本支持可视化配置容器 IPv6。
> > > 
> > > 
> > > 可以參考這篇文章： https://www.spiritysdx.top/20230829/
> > > 新建一個網橋用作ipv6的自動獲取。還有就是防火墻就不能單獨控制了。希望官方能考慮一下
> > 
> > 
> > 是的，需要同步修改 docker 配置文件、容器所用网络等，近期版本会支持。
> 
> 不确定你们说的是不是这个, 在应用商店安装的docker容器默认只监听ipv4, 在安装目录的.env文件里, `HOST_IP="0.0.0.0"`, 希望可以改成都监听

已完成，下周发布 v1.9.0 版本。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
