### ISSUE TITLE
[BUG] 已安装的应用，无法正确识别。安装按钮显示为可安装。

### ISSUE THREAD

**Issue by CMJNB** [1Panel-dev/1Panel#2995]
### 1Panel 版本

1.8.2

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/53365071/2f04cd39-85c1-4c0d-8f2a-14f3c961b3b3)

问题如图。
具体就是，这个数据库挺早安装了，中间经历过几次版本更新。207多天前安装的。
该应用已是最新版本8.2.0，都是通过面板进行更新的。

### 重现步骤

具体不清楚，可能不影响功能吧，只是微不足道的bug

**Comment by CMJNB** [comment]
补充：该应用已是最新版本8.2.0，都是通过面板进行更新的。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。系统支持同时安装多个 MySQL 数据库。
