### ISSUE TITLE
卸载重装没必要把backup给删除

### ISSUE THREAD

**Issue by ozshen** [1Panel-dev/1Panel#2996]
### 1Panel 版本

1.8.0

### 请描述您的需求或者改进建议

1pctl uninstall时没必要把backup给删除吧，备份文件包括源站点文件都直接被干掉了，重装回来后数据库镜像也不能重新识别回来，还得重装一遍数据库和redis以及openresty，一条命令直接干掉所有辛苦付出啊

**Comment by wanghe-fit2cloud** [comment]
是的，卸载操作会清理掉 1Panel 相关数据，在卸载前可以提前做好 `快照`、上传备份至第三方 `备份账号` 等。
