### ISSUE TITLE
[FEATURE] 建议独立一个小页面做一个监控，这样不用每次打开面板来查看机器运行情况

### ISSUE THREAD

**Issue by mobeicanyue** [1Panel-dev/1Panel#2997]
### 1Panel 版本

v1.8.2

### 请描述您的需求或者改进建议

独立出一个小页面做一个监控，这样不用每次打开面板来查看机器运行情况

域名什么的可以自己反代。

比如说我网站是 example.com，我的1panel面板是 panel.example.com，如果我想看机器内存等情况，我就要每次都登录面板查看
![image](https://github.com/1Panel-dev/1Panel/assets/81098819/10139726-df2a-4b10-94c0-ce9fd4cab206)

建议独立一个小页面，我可以设置成 status.example.com
或者提供一个模板展示机器信息
![image](https://github.com/1Panel-dev/1Panel/assets/81098819/348ea468-d23e-4edd-ad34-8392702d582f)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在中短期内暂不会考虑支持上述需求，望理解。

**Comment by mobeicanyue** [comment]
> 感谢反馈，我们在中短期内暂不会考虑支持上述需求，望理解。

那请问有什么面板api我可以调用吗，我自己写一个试试😂

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈，我们在中短期内暂不会考虑支持上述需求，望理解。
> 
> 那请问有什么面板api我可以调用吗，我自己写一个试试😂

/1panel/swagger/index.html
