### ISSUE TITLE
[BUG] 应用名称已存在 提示问题

### ISSUE THREAD

**Issue by kkssiissbb** [1Panel-dev/1Panel#3005]
### 1Panel 版本

1.8.2

### 问题描述

网站修改域名为别的域名后,如果再用之前的域名创建新网站,会一直提示  **应用名称已存在**
例如用www.baidu.com  解析的网站,然后又添加了域名www.qq.com  然后删除www.baidu.com 
后边如果再用www.baidu.com创建网站,那么就会提示这个问题

### 重现步骤

问题原因
app_installs 表中name名称是域名,
更新网站信息这里,没有更新app_installs表中信息(问题就在这里,缺少更新app_installs表)
![image](https://github.com/1Panel-dev/1Panel/assets/128440458/a7d46a92-cdaa-4e5c-8a06-beb173015fbf)
删除网站信息这里有删除app_installs表中信息
![image](https://github.com/1Panel-dev/1Panel/assets/128440458/9266101a-a1be-4388-8f97-8e459f7910f2)

**Comment by zhengkunwang223** [comment]
当前的逻辑是这样
安装 PHP 网站 -> 创建 PHP 应用 （使用网站主域名去掉小数点作为应用名称），并根据这个名称去创建文件夹   
所以单纯修改应用名称无法解决这个问题  
我们一开始的设计是不允许创建相同主域名的网站的 
所以这块可能暂时无法处理
后续我们支持共享 PHP 容器时，会解决这个问题

**Comment by wanghe-fit2cloud** [comment]
#2405
