### ISSUE TITLE
[QUESTION]证书咨询

### ISSUE THREAD

**Issue by haiwan-xm** [1Panel-dev/1Panel#3006]
### 请描述您的问题

你好 目前1p生成的证书好像默认是NG 的格式
如何能直接生成apa或者IIS 格式呢？

**Comment by zhengkunwang223** [comment]
你可以使用一些证书转换工具转为换你想要的格式

**Comment by haiwan-xm** [comment]
可是我看没有根文件
只有
![image](https://github.com/1Panel-dev/1Panel/assets/45061573/1b0a2bb9-f690-4e9c-ba20-1c8e650e20d6)

**Comment by zhengkunwang223** [comment]
例如你想要 apa 格式的证书
你就搜索 pem 格式转换为 apa 格式
