### ISSUE TITLE
[BUG]拖拽上传文件夹，提示 文件类型错误或为空文件夹，文件夹非空文件夹

### ISSUE THREAD

**Issue by xiexiaosheng** [1Panel-dev/1Panel#3007]
### 1Panel 版本

1.8.2

### 问题描述

拖拽上传文件夹，提示 文件类型错误或为空文件夹，文件夹非空文件夹

### 重现步骤

拖拽上传文件夹，提示 文件类型错误或为空文件夹，文件夹非空文件夹

**Comment by wanghe-fit2cloud** [comment]
在文件上传列表中选择 `上传文件夹`，默认是上传文件。
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/cfb03a5d-c32a-4c69-be18-e88cbfb0b6a4">
