### ISSUE TITLE
应用商店应用添加 docker-compose.yml自定义编辑选项。

### ISSUE THREAD

**Issue by jk110** [1Panel-dev/1Panel#301]
### 1Panel 版本

1.0.2

### 请描述您的需求或者改进建议

应用商店应用添加 docker-compose.yml自定义编辑选项。

### 请描述你建议的实现方案

应用商店应用添加 docker-compose.yml自定义编辑选项。

**Comment by zhengkunwang223** [comment]
是想编辑什么参数呢？是想在安装之前还是安装之后编辑？

**Comment by jk110** [comment]
你的docker-compose.yml不是克隆出来的嘛，就是克隆出来的这个，在安装之前吧，可以自己定义参数，比较方便，之前在群里聊过的。

**Comment by zhengkunwang223** [comment]
> 你的docker-compose.yml不是克隆出来的嘛，就是克隆出来的这个，在安装之前吧，可以自己定义参数，比较方便，之前在群里聊过的。

好的，后续版本支持

**Comment by Ghost-Cavendish** [comment]
还没做啊

**Comment by zhengkunwang223** [comment]
> 还没做啊
> 
> 

下个版本重构应用商店，会增加编辑 yml 功能

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
