### ISSUE TITLE
[BUG]谷歌浏览器添加sftp账号的时候无法填入端口

### ISSUE THREAD

**Issue by ceozero** [1Panel-dev/1Panel#3010]
### 1Panel 版本

1.8.2

### 问题描述

[BUG]谷歌浏览器添加sftp账号的时候无法填入端口

<img width="975" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/22513657/f4a5d886-09c4-4818-9e63-14647fd44a37">

### 重现步骤

面板设置-添加sftp-端口点不了。

Chrome 已是最新版本
版本 119.0.6045.159（正式版本） (x86_64)

### 期待的正确结果

这里可以设置ftp吗？？？为什么没有直接支持ftp备份的？

**Comment by wanghe-fit2cloud** [comment]
本地未复现上述问题。
1、使用无痕模式、清理浏览器缓存或者尝试切换其他浏览器
2、不支持 ftp

**Comment by ssongliu** [comment]
没有复现该问题
<img width="911" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/73214554/29e16d88-303e-4ee8-8562-dbd23dca9d30">
<img width="886" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/73214554/70a6ff59-6144-40a2-bbaa-0013abd18a79">
