### ISSUE TITLE
[QUESTION] 请教如何为 PHP 容器增加进程守护呢？

### ISSUE THREAD

**Issue by jevantang** [1Panel-dev/1Panel#3011]
### 请描述您的问题

计划任务可以选容器，指令可以在容器里执行。

但是进程守护进不了容器，怎么守护一个 PHP 容器呢？

我的指令是 `php artisan queue:work`，需要到 PHP 容器里执行，否则会提示 `can't find command 'php` 无法启用。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本调研上述需求的解决方案。

**Comment by wanghe-fit2cloud** [comment]
重复 #2683
