### ISSUE TITLE
[FEATURE]新版zip压缩失败的文件添加自动删除

### ISSUE THREAD

**Issue by okxlin** [1Panel-dev/1Panel#3012]
### 1Panel 版本

v1.8.2

### 请描述您的需求或者改进建议

新版本需要安装zip才能压缩解压zip文件，旧版本倒是不用。

不过能否自动将压缩失败生成的zip文件删除呢，省去手动一步

![image](https://github.com/1Panel-dev/1Panel/assets/61420215/2e4cd3cf-2642-4b9f-8a6b-7fa64c17b1c6)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化 zip 解压缩代码逻辑。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
