### ISSUE TITLE
[BUG] 创建网站失败

### ISSUE THREAD

**Issue by Virace** [1Panel-dev/1Panel#3013]
### 联系方式

virace@aliyun,com

### 1Panel 版本

1.8.2

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/19266538/310284c4-30e0-4d78-92eb-e4b1d9620afc)

创建第二个php网站时遇到的问题，网站访问502
然后网站无法删除，强制删除勾选也没用。

重启面板重启服务器，都无法删除。

### 重现步骤

创建运行环境   ->  创建网站1 -> 创建网站2  -> 删除网站  -> 再次创建网站2

### 相关日志输出

```shell
service "extensions" has neither an image nor a build context specified: invalid compose project
```

**Comment by wanghe-fit2cloud** [comment]
刚在本地开发环境测试，未复现上述问题。
> 1、麻烦提供一下强制删除网站时的错误日志。
2、如果没有其他网站，可以选择在 `已安装` 应用列表强制卸载 OpenResty，之后再来安装 OpenResty 并创建网站。

**Comment by Virace** [comment]
> 刚在本地开发环境测试，未复现上述问题。
> 
> > 1、麻烦提供一下强制删除网站错误信息。
> > 2、如果没有其他网站，可以选择在 `已安装` 应用列表强制卸载 OpenResty，之后再来安装 OpenResty 并创建网站。

强制删除没有任何提示也没有任何错误信息，只有个网页刷新的动作。 

有其他网站= =

**Comment by zhengkunwang223** [comment]
查看一下 docker-compose 版本

**Comment by Virace** [comment]
> 刚在本地开发环境测试，未复现上述问题。
> 
> > 1、麻烦提供一下强制删除网站时的错误日志。
> > 2、如果没有其他网站，可以选择在 `已安装` 应用列表强制卸载 OpenResty，之后再来安装 OpenResty 并创建网站。

整体重新安装了，问题依旧，唯一说那会有问题的，那就是域名里面有“-”。

**Comment by Virace** [comment]
> 查看一下 docker-compose 版本

差不多能确定是 域名导致的问题， 域名是 xx-xxx.com  有个减号。 其他域名都没有问题。

**Comment by Virace** [comment]
Docker Compose version v2.16.0
![image](https://github.com/1Panel-dev/1Panel/assets/19266538/607779a3-793e-4f55-831a-e779d20c041f)

而且 貌似只有 x-xxxxx 这种格式的域名会遇到问题。

唯一能看到的失败信息 就是这个

`stderr: service "extensions" has neither an image nor a build context specified: invalid compose project`

**Comment by Virace** [comment]
Docker Compose version v2.16.0

**Comment by zhengkunwang223** [comment]
经过检查是 docker-compose 低于 v2.19 版本时会出现的 [BUG](https://github.com/docker/compose/issues/10747)，后续我们会升级一键安装脚本中的 docker-compose 版本。

**Comment by zyyfit** [comment]
新安装 1panel 服务时 docker-compose 会安装新版本的，已安装过docker-compose 的话还是需要手动升级 docker-compose版本

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
