### ISSUE TITLE
[FEATURE]希望数据库页面增加adminer管理

### ISSUE THREAD

**Issue by xiahao90** [1Panel-dev/1Panel#3014]
### 1Panel 版本

v1.8.2

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/11575908/7c92d870-e7ba-4c1e-b4eb-cf11ee874bf1)
希望数据库页面增加adminer管理，phpmyadmin用不习惯

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
