### ISSUE TITLE
希望可以用ufw或者firewalld防火墙可以管控docker映射出来的的端口 [FEATURE]

### ISSUE THREAD

**Issue by r1172464137** [1Panel-dev/1Panel#3015]
### 1Panel 版本

v1.8.2

### 请描述您的需求或者改进建议

用ufw或者firewalld防火墙可以管控docker映射出来的的端口

### 请描述你建议的实现方案

https://github.com/chaifeng/ufw-docker
该方案我在本机上测试了可行，缺点没有ipv6。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本调研上述方案。

**Comment by wanghe-fit2cloud** [comment]
重复 #1846
