### ISSUE TITLE
[QUESTION] 绑定域名有成功的吗

### ISSUE THREAD

**Issue by Doutianbao** [1Panel-dev/1Panel#3018]
### 请描述您的问题

![image](https://github.com/1Panel-dev/1Panel/assets/25342342/b69f9ac3-ecce-47e3-9550-83b423b3c54c)

绑定域名无法访问网站~

**Comment by wanghe-fit2cloud** [comment]
> 上述问题已经在本地环境测试多次未复现。

1、域名是否正确解析到 1Panel 服务器
2、面板端口是否为 80（非 80 端口要使用 `域名:端口`）
3、还可以创建反向代理网站来访问 1Panel
