### ISSUE TITLE
[BUG] 删除文件报错   永久删除才行

### ISSUE THREAD

**Issue by dzcms** [1Panel-dev/1Panel#3020]
### 联系方式

dzcms@qq.com

### 1Panel 版本

v1.8.2

### 问题描述

服务内部错误: rename /opt/1panel/apps/openresty/openresty/www/sites/iot/log/error.log /.1panel_clash/_1p_file_1p_opt_1p_1panel_1p_apps_1p_openresty_1p_openresty_1p_www_1p_sites_1p_iot_1p_log_1p_error.log_p_2976_1700617923: invalid cross-device link

### 重现步骤

任何文件删除 都报这个错误  只有勾选 永久删除才行

**Comment by dzcms** [comment]
![Uploading image.png…]()

**Comment by zhengkunwang223** [comment]
请问是什么操作系统
挂载了哪些盘 分别是什么类型？

**Comment by dzcms** [comment]
> 请问是什么操作系统 挂载了哪些盘 分别是什么类型？

主机名称 VM-4-9-centos
发行版本 centos-8
内核版本 4.18.0-492.el8.x86_64
系统类型 x86_64
启动时间 2023-11-22 09:46:43

挂载腾讯云的云硬盘  
基本信息:
挂载点: /opt
类型: ext4
文件系统: /dev/vdb

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
