### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MyToolMan** [1Panel-dev/1Panel#3022]
### 联系方式

lepneng@gmail.com

### 1Panel 版本

v1.8.2

### 问题描述

起初是因为我的OpenResty重启过服务器之后启动不了了。我就想卸载重装。但是我卸载之后，OpenResty的容器已经不在了，但是应用商店提示已经安装过OpenResty了，不能重复安装。
![屏幕截图 2023-11-22 103150](https://github.com/1Panel-dev/1Panel/assets/69788470/50143356-d4df-4604-8db5-6bf7dcf84c24)

### 重现步骤

不明原因OpenResty无法启动-----卸载重装OpenResty-----应用提示不能重复安装

**Comment by zhengkunwang223** [comment]
卸载需要在1Panel进行 手动删除容器是卸载不掉的 
<img width="689" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/31820853/426b7109-9b9a-48ab-8230-860077b407a8">
