### ISSUE TITLE
开启了安全验证 mfa，结果手机重装了系统，发现无法再接入 1panel 了，咋整啊？

### ISSUE THREAD

**Issue by junxiaotan** [1Panel-dev/1Panel#3023]
### 请描述您的问题

开启了安全验证 mfa，结果手机重装了系统，发现无法再接入 1panel 了，咋整啊？

**Comment by YaKun9** [comment]
SSH登录服务器,通过命令行重置掉

```
1pctl reset mfa
```

文档地址: https://1panel.cn/docs/installation/cli/?h=mfa#2-1pctl-reset

**Comment by junxiaotan** [comment]
好的好的，没仔细看文档，就看了下 一级命令 help，感谢感谢~
