### ISSUE TITLE
[FEATURE] 文件夹上传文件时，整体进度条不动，期望能够体现整体进度。

### ISSUE THREAD

**Issue by YaKun9** [1Panel-dev/1Panel#3030]
### 1Panel 版本

1.8.2

### 请描述您的需求或者改进建议

文件夹上传文件时，整体进度条不动，期望能够体现整体进度。
![image](https://github.com/1Panel-dev/1Panel/assets/131952790/9e638617-838a-4ac3-85f0-e88f1b879594)

**Comment by zhengkunwang223** [comment]
后续版本优化此功能

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
