### ISSUE TITLE
[BUG]MFA验证自动登录

### ISSUE THREAD

**Issue by ozshen** [1Panel-dev/1Panel#3031]
### 1Panel 版本

1.8.2

### 问题描述

启用MFA验证后，输入正确令牌在自动登录跳转的瞬间按enter键会导致菜单无法加载。

### 重现步骤

启用MFA验证后，正确输入令牌后立即按enter键，菜单加载失败。
![image](https://github.com/1Panel-dev/1Panel/assets/14324029/45c6093b-131c-44bd-affb-692aea66e3ec)
![image](https://github.com/1Panel-dev/1Panel/assets/14324029/5f18e885-5148-44a6-9363-cde9cd12e08d)

**Comment by igophper** [comment]
不开mfa，登录的时候，快速双击enter也可以复现BUG

**Comment by wanghe-fit2cloud** [comment]
v1.8.3 版本已发布。
