### ISSUE TITLE
[FEATURE]希望可以同时上传文件和文件夹

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#3034]
### 1Panel 版本

1.8.2

### 请描述您的需求或者改进建议

当前版本只能上传文件或文件夹， 不能同时上传文件和文件夹

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/51264840/96904232-59b4-4a8c-9c40-561f99f98124)

**Comment by zhengkunwang223** [comment]
如果你是说同时选择文件和文件夹
那么HTML 标准的 input 元素不支持同时选择文件和文件夹 所以这个需求暂时无法实现
如果你有方案 欢迎提供给我们

如果是先选择文件 后选择文件夹，然后上传，那么这种我们可以后续版本优化

**Comment by wanghe-fit2cloud** [comment]
最新版本已支持。
