### ISSUE TITLE
[QUESTION]登录日志列表一直是空的

### ISSUE THREAD

**Issue by 50007** [1Panel-dev/1Panel#3036]
### 请描述您的问题

1panel版本：v1.8.2
系统版本： debian-12.2
登录日志一直是空的，重装系统后也是空的，
面板日志正常显示，之前安装Ubuntu有显示登录日志，换debian后就不显示登录日志了，是否跟系统有关？

**Comment by 50007** [comment]
只有在命令下journalctl -u ssh 可以看到日志

**Comment by 50007** [comment]
![asd](https://github.com/1Panel-dev/1Panel/assets/143870542/451744c3-0894-451d-8e16-5fa40302411d)

**Comment by wanghe-fit2cloud** [comment]
重复 #2999
