### ISSUE TITLE
防火墙无法自动生效[BUG]

### ISSUE THREAD

**Issue by cn-specter** [1Panel-dev/1Panel#3037]
### 1Panel 版本

1.8.2

### 问题描述

在防火墙中增加新的端口没自动生效，需要手动开关一下防火墙

### 重现步骤

防火墙 > 新增端口 >保存。然后访问该端口

### 期待的正确结果

能正常访问

**Comment by ssongliu** [comment]
感谢反馈，防火墙是 ufw 还是 firewalld？从页面上添加新端口，不重启的情况下，宿主机命令能查询到添加的端口吗？

**Comment by cn-specter** [comment]
firewalld 新增不生效是我这边操作的问题。删除80和443确认了重启防火墙后会自动添加
