### ISSUE TITLE
防火墙中默认80和443端口无法删除[BUG]

### ISSUE THREAD

**Issue by cn-specter** [1Panel-dev/1Panel#3038]
### 1Panel 版本

1.8.2

### 问题描述

在防火墙中默认放行了80和443端口，手动删除后重启防火墙发现还是默认添加上了

### 重现步骤

在防火墙中删除80 和 443 端口，关闭防火墙，在开启

### 期待的正确结果

80和443端口不见了

**Comment by wanghe-fit2cloud** [comment]
在你提交的上一个 Issue 中统一讨论。
#3037
