### ISSUE TITLE
[QUESTION&BUG?]添加网站安全规则时报错

### ISSUE THREAD

**Issue by Zyilin98** [1Panel-dev/1Panel#3039]
**复现过程** 
![image](https://github.com/1Panel-dev/1Panel/assets/61766598/eceab771-4c9b-4e06-a098-bd6e32c236f3) 
在图片所在页面添加 `^(?!.*Mozilla\/5\.0)(?=.*CensysInspect|zgrab).* `这个规则时，
 发生报错`请求参数错误: Key: 'WebsiteWafFileUpdate.Type' Error:Field validation for 'Type' failed on the 'oneof' tag` 
**环境状态：** 
> 发行版本 debian-10.13 
内核版本 4.19.0-25-amd64 
1panel版本 v1.8.2 
openResty版本 1.21.4.3-0-focal

**Comment by zhengkunwang223** [comment]
好的 我们先在本地复现一下

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
