### ISSUE TITLE
创建快找备份到腾讯云存储[BUG]

### ISSUE THREAD

**Issue by yikwongee** [1Panel-dev/1Panel#304]
### 1Panel 版本

1.0.2

### 问题描述

备份账号：亚马逊 S3 云存储，但是是腾讯云存储
在创建快照时会造成1分钟左右的后台无法访问，快照创建完成后就会恢复正常

### 重现步骤

![image](https://user-images.githubusercontent.com/77314844/226162219-20511a00-8a92-4ba9-9a6e-a6bdd9bcdc85.png)

### 期待的正确结果

修复一下这个问题
如果可以的话能否单独搞一个腾讯云备份，因为存在内网备份的情况
快照创建的时候能否后台创建快照，不要影响到其他操作

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1、备份账号支持腾讯云存储的需求会在后续版本中支持。
2、创建快照过程中涉及到了备份 1Panel 数据目录、Docker 数据目录等操作，为了防止用户操作产生临时数据，就在此过程中禁止了用户操作。
