### ISSUE TITLE
[QUESTION]Alist 开放外部端口后，浏览器不能正常访问。

### ISSUE THREAD

**Issue by bigcat11** [1Panel-dev/1Panel#3040]
### 请描述您的问题

![image](https://github.com/1Panel-dev/1Panel/assets/59407605/d8891367-521c-46eb-8d3b-149052346781)
![image](https://github.com/1Panel-dev/1Panel/assets/59407605/a2ede59c-134e-41f1-804f-a4801596605b)
![image](https://github.com/1Panel-dev/1Panel/assets/59407605/9d61a315-3465-4d25-bdd0-839e69ca03be)
外部端口都开放了，服务器防火墙也管了，这个怎么解决

**Comment by wanghe-fit2cloud** [comment]
可以进入 `主机` - `终端`，看一下 `curl http://127.0.0.1:5244` 的返回结果。
> 5244 修改为安装应用时指定的端口。

**Comment by wanghe-fit2cloud** [comment]
本地未复现上述问题，先关闭这个 Issue 了。
> 如果还有问题可以继续讨论。
