### ISSUE TITLE
[BUG]备份和恢复快照时经常提示1Panel.db-wal被删除

### ISSUE THREAD

**Issue by iLayPark** [1Panel-dev/1Panel#3041]
### 1Panel 版本

1.8.2

### 问题描述

备份和恢复快照时经常提示1Panel.db-wal被删除

### 重现步骤

restore original panel data failed, err: do handle tar failed, stdout: stderr: tar: ./db/1Panel.db-wal：文件在我们读入之前被删除了 , err: exit status 1

**Comment by ssongliu** [comment]
感谢反馈，后续版本优化。

**Comment by qyl27** [comment]
The same issue, it can be reproduced in 1.7.4 and 1.8.3.  
In 1.8.3, the bug appeared to be too frequent to build a snapshot.  
I have tried 5 times, and all failed. The problem may be more serious than described by ilay1678.  
Maybe it shouldn't write or commit the database while backing up?

**Comment by pppfz** [comment]
有同样的问题，在1.9.1中，期待修复。

**Comment by iTofu** [comment]
同样的问题，v1.9.2

**Comment by wanghe-fit2cloud** [comment]
为了更好的使用 [SQLite](https://www.sqlite.org/)  的事务，1Panel 使用的是 WAL 模式，即会将修改操作写入到一个独立的 -wal 文件中，然后定量 checkpoint 到主数据库文件。
而在快照压缩过程中，有可能正好进行 checkpoint 操作，导致 -wal 文件被删除，压缩失败。

如出现上述问题，目前可以尝试重新创建快照。
> 我们目前也正在调研适配其他模式，后续版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
