### ISSUE TITLE
[FEATURE]可以加docker commit <container_id> <image_name> 功能？

### ISSUE THREAD

**Issue by ceozero** [1Panel-dev/1Panel#3042]
### 1Panel 版本

1.8.2

### 请描述您的需求或者改进建议

可以加docker commit <container_id> <image_name> 功能？ 每次改好的容器都要手动commit 一下再推送。。。

开发者可能更注重直接用Dockerfile构建。。。对于用户来说，用别人的镜像，偶尔可能想加点自己的东西。
然后就可以直接从这个容器基础上创建一个自己的镜像然后push到自己的注册表里。

![image](https://github.com/1Panel-dev/1Panel/assets/22513657/f6764629-c04c-4566-97a0-26e86091499e)

portainer 的这个创建功能很方便，建完打标推送。。

### 请描述你建议的实现方案

现在的拉去推送和构建功能都很完善了。

直接在容器后面的更多加一个创建镜像功能。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
docker 容器备份、恢复相关问题的讨论，统一汇总到该 issue #2194
