### ISSUE TITLE
[BUG] 容器仓库编辑失败

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3043]
### 1Panel 版本

v1.8.2

### 问题描述

我在应用商店创建了一个 nexus，有用户名密码，然后我第一次添加仓库的时候忘记选择验证了，能正常添加，然后加上验证的时候反而不行了，下面是错误信息：
<img width="415" alt="图片" src="https://github.com/1Panel-dev/1Panel/assets/30285739/06a34ee5-badd-43d2-9ecc-69ad4a24014c">

删除后直接创建是可以的。

### 重现步骤

希望能够正常编辑

**Comment by wanghe-fit2cloud** [comment]
上述问题将会在近期版本修复。

**Comment by wanghe-fit2cloud** [comment]
v1.8.3 版本已发布。
