### ISSUE TITLE
[BUG] 新装面板，在文件页面滚动时偶发卡顿

### ISSUE THREAD

**Issue by Starsbon** [1Panel-dev/1Panel#3045]
### 1Panel 版本

1.8.3

### 问题描述

新装 1Panel，2C4G 云服务器，OpenCloudOS 系统。在文件页面滚动时会卡顿，如果等待一会可能会正常，但是如果滚动速度快一些也会卡顿，严重的时候滚动直接失效卡死在这里。

### 重现步骤

在 「主机」>「文件」 中滚动页面出现卡顿。

**Comment by zhengkunwang223** [comment]
文件数量多吗
最好是有视频可以看一下
我们也在本地复现一下

**Comment by uluckyXH** [comment]
> 文件数量多吗 最好是有视频可以看一下 我们也在本地复现一下

确实，我昨晚上传一个用于学习的PHP站点，文件有点多，有很多文件夹和文件，打开后会卡顿

**Comment by uluckyXH** [comment]
> 文件数量多吗 最好是有视频可以看一下 我们也在本地复现一下

微信号：hello_you_lucky ，我可以提供面板后台，让你直接上去看，服务器的配置是2h2g 3m 40ssd，买来用来学习的，随便折腾，随时会重置
