### ISSUE TITLE
[BUG] 新版本，纽约服务器打开面板一直处于加载状态。之前正常

### ISSUE THREAD

**Issue by jonpostel** [1Panel-dev/1Panel#3046]
### 联系方式

vocaloid.at@gmail.com

### 1Panel 版本

v1.8.3

### 问题描述

新版本，纽约服务器打开面板一直处于加载状态。之前版本正常

应该是js的加载的资源一直卡着。。

![285357164-53ea8b4b-126a-4247-8ea2-dac751544b83](https://github.com/1Panel-dev/1Panel/assets/30648287/b8ebf884-8568-42ec-a701-ac730e4eba86)

### 重现步骤

新版本，纽约服务器打开面板一直处于加载状态。之前版本正常

应该是js的加载的资源一直卡着。。

**Comment by jonpostel** [comment]
网站和里面的docker服务都是正常的，也不卡，就是面板登录很卡。里面的面板模块也卡.
我猜测是一些js资源加载问题导致的。
![image](https://github.com/1Panel-dev/1Panel/assets/30648287/5d334887-df75-4f77-be17-6eca6ebf8083)

**Comment by jonpostel** [comment]
经过实际测试，就是部分js加载很慢很慢。几分钟。服务器在美国纽约。。

应用商店也无法加载。好像是有些请求失败了。之前也是正常的。

![image](https://github.com/1Panel-dev/1Panel/assets/30648287/d9830099-b582-464a-9a0a-f1a4f8673d36)

![图片](https://github.com/1Panel-dev/1Panel/assets/30648287/0da172b9-870c-48ae-ba76-768f8c99be24)

**Comment by zhengkunwang223** [comment]
感谢反馈 我们复现一下

**Comment by YaKun9** [comment]
同样的问题，国内部署的Debian 12.2 虚拟机，也是这样加载不出来

**Comment by wanghe-fit2cloud** [comment]
建议将 1Panel 升级到最新版本（有针对上述问题作出优化），然后检查问题是否仍然存在。

**Comment by jonpostel** [comment]
> 建议将 1Panel 升级到最新版本（有针对上述问题作出优化），然后检查问题是否仍然存在。

是的新版本问题已解决
