### ISSUE TITLE
[BUG]应用商店里的showdoc默认配置不支持arm架构

### ISSUE THREAD

**Issue by krystal-cao** [1Panel-dev/1Panel#3048]
### 1Panel 版本

1.8.3

### 问题描述

应用商店默认只能选择3.2.2版本的镜像，这个版本只支持amd64架构，arm64的服务器会安装失败
但是docker hub中showdoc是有支持arm架构的版本的，希望这里可以自动判断系统架构安装或者提供版本选择
![WX20231124-154204@2x](https://github.com/1Panel-dev/1Panel/assets/13929955/4caaa8b6-76cf-4663-95f5-23466b773016)

### 重现步骤

同上

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们后续版本会额外增加一个 arm 版本。
> 当前版本可以先手动来修改 compose 镜像版本号来安装。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
