### ISSUE TITLE
[BUG] 防火墙bug？由于我机器上有重要东西在跑，没有做复现 见谅

### ISSUE THREAD

**Issue by lancer-wang** [1Panel-dev/1Panel#3050]
### 1Panel 版本

1.8.3

### 问题描述

今天重启完服务器之后
连接机器上的数据库，提示端口没开
防火墙看了下，开了
然后我删除重新添加，莫名又好了

### 重现步骤

重启之后，pgsql的防火墙没有正确生效

![](https://image.azurebest.eu.org/file/4af112d0cc2470fa6ef3d.png)

### 附加信息

由于没有尝试复现，所以也可能是玄学问题
如果你们有空的话可以试试是不是bug

**Comment by wanghe-fit2cloud** [comment]
收到，我们尝试在本地环境复现一下上述问题。

**Comment by lancer-wang** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/69783837/09796298-b65d-436c-ae45-3be156e7f9c2)

**Comment by wanghe-fit2cloud** [comment]
> ![image](https://user-images.githubusercontent.com/69783837/285427970-09796298-b65d-436c-ae45-3be156e7f9c2.png)

服务器重启后，先去检查一下 PostgreSQL 数据库是否已经正常运行了。

**Comment by lancer-wang** [comment]
> > [![image](https://user-images.githubusercontent.com/69783837/285427970-09796298-b65d-436c-ae45-3be156e7f9c2.png)](javascript:void(0))
> 
> 服务器重启后，先去检查一下 PostgreSQL 数据库是否已经正常运行了。

服务器本地的连接正常（因为这个最开始就是那个服务器要用）

**Comment by wanghe-fit2cloud** [comment]
我在多台服务器均未复现上述问题，先关闭该 Issue 了。后面如果复现该问题再继续讨论。
