### ISSUE TITLE
[FEATURE]建议添加安全功能-fail2ban

### ISSUE THREAD

**Issue by uinv** [1Panel-dev/1Panel#3052]
### 1Panel 版本

1.8.3

### 请描述您的需求或者改进建议

Linux面板通常是linux知识比较少的或者想要容易简单管理的用户使用，但是往往容易忽视安全问题。fail2ban是个功能强大关联防火墙规则的功能，建议添加。

**Comment by wanghe-fit2cloud** [comment]
重复 #1643
