### ISSUE TITLE
[BUG] 创建的404重定向提示重定向次数过多

### ISSUE THREAD

**Issue by W4J1e** [1Panel-dev/1Panel#3054]
### 1Panel 版本

V1.8.2

### 问题描述

貌似 OpenResty 里面没有自定义 404 错误页面的功能，只看到一个创建重定向。
我在重定向里添加了404重定向，重定向的目标地址为我的网站目录下的 404.html 单页面。
我随手访问一个不存在的路径，浏览器响应“重定向次数过多”，在地址栏里域名后面有 N 个 404.html。

### 重现步骤

① 在网站配置里，添加重定向；
② 类型选择404，方式选择301，目标 URL 地址填网站目录下的404静态页面（https://xxx.com/404.html）；
③ 随机访问不存在的路径。

### 期待的正确结果

正确跳转到 404 页面。

### 附加信息

看到 issue 里，四月份就有人提出过这个需求，但是目前为止这个功能还没有开发上线。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
v1.8.4 版本已发布。

**Comment by W4J1e** [comment]
更新版本后还是复现了该问题，访问`https://example.com/test`，跳转后的链接是`https://example.com/404.html(N个)/test`。
查看了一下源文后，我把目标 URL 里的域名去掉，只有 404 页面的路径，能正常 跳转了。
该问题完美解决。

**Comment by igophper** [comment]
> 更新版本后还是复现了该问题，访问`https://example.com/test`，跳转后的链接是`https://example.com/404.html(N个)/test`。 查看了一下源文后，我把目标 URL 里的域名去掉，只有 404 页面的路径，能正常 跳转了。 该问题完美解决。

更新之后可以删掉重新填一下，如果还是跳转过多可能是填错了。
