### ISSUE TITLE
[FEATURE]希望应用商店添加ChatGPT-Next-Web

### ISSUE THREAD

**Issue by 50007** [1Panel-dev/1Panel#3055]
### 1Panel 版本

v1.8.3

### 请描述您的需求或者改进建议

希望应用商店添加ChatGPT-Next-Web
虽然应用商店有ChatGPT Web，
但是ChatGPT-Next-Web的自定义接口等功能更加丰富，方便随时更改，不需要重新部署就可以完成。

### 请描述你建议的实现方案

https://github.com/Yidadaa/ChatGPT-Next-Web

### 附加信息

貌似第三方应用商店有，但是我更希望能上架到1panel商店。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期上架 ChatGPT-Next-Web 到应用商店。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
