### ISSUE TITLE
[BUG] 深圳阿里云安装没有找到containerd.io_1.6.25-1_amd64

### ISSUE THREAD

**Issue by qwenode** [1Panel-dev/1Panel#3057]
### 1Panel 版本

1.8.3

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/8974108/afb8c841-d59f-4fcc-b03a-b18f54809cf0)

![image](https://github.com/1Panel-dev/1Panel/assets/8974108/a3c3656a-7b23-4b9a-84f1-681d060bcce1)

### 重现步骤

新机安装, ecs debian 12.2

### 期待的正确结果
建议换其他源或内置多个备用源 

![image](https://github.com/1Panel-dev/1Panel/assets/8974108/f877387d-bee9-4df0-bcc0-258088643485)

**Comment by qwenode** [comment]
https://mirrors.tuna.tsinghua.edu.cn/help/docker-ce/ 测试清华可用

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们稍后测试一下上述问题。
> 后续版本可能会在安装时让用户选择 docker 源。

**Comment by chenkuicn** [comment]
Debian11、Debian12安装都会报错，因为阿里云Docker CE镜像源中两者的相应目录下，最新的版本文件是containerd.io_1.6.24-1_amd64。1Panel面板的安装引用了Docker官方的脚本，脚本中国内使用的是阿里云的源。实测Ubuntu22.04（jammy）不会报错（目录中有该文件），可以使用1Panel一键部署成功。20.04（focal）没试，但是目录中也有该文件，应该也没问题。其他系统目录就没去看了。
已经给阿里云发了工单，也写了建议反馈的邮件。后续1Panel的一键部署脚本再优化一下，应该会比较完善的解决该问题

**Comment by wanghe-fit2cloud** [comment]
> Debian11、Debian12安装都会报错，因为阿里云Docker CE镜像源中两者的相应目录下，最新的版本文件是containerd.io_1.6.24-1_amd64。1Panel面板的安装引用了Docker官方的脚本，脚本中国内使用的是阿里云的源。实测Ubuntu22.04（jammy）不会报错（目录中有该文件），可以使用1Panel一键部署成功。20.04（focal）没试，但是目录中也有该文件，应该也没问题。其他系统目录就没去看了。 已经给阿里云发了工单，也写了建议反馈的邮件。后续1Panel的一键部署脚本再优化一下，应该会比较完善的解决该问题

感谢 🙏

**Comment by chenkuicn** [comment]
就在刚刚containerd.io_1.6.25-1_amd64文件已经更新在阿里云的Debian11和12的相应目录下了，但是1panel的一键部署出了新的报错，同样还是阿里云那边的问题。出错文件是docker-ce-cli 24.0.7-1-debian.12~bookworm amd64.deb。
![3](https://github.com/1Panel-dev/1Panel/assets/69375568/1e48529a-abbd-4640-94ef-957d4edb9479)

**Comment by chenkuicn** [comment]
刚刚docker-ce-cli 24.0.7-1-debian.12~bookworm amd64.deb 文件已经更新了，并且通过Debian12系统用1Panel的一键部署安装成功了。
![2](https://github.com/1Panel-dev/1Panel/assets/69375568/7e28fb2b-32d1-4700-92ed-bc2a04558654)
![3](https://github.com/1Panel-dev/1Panel/assets/69375568/66e39fc5-d506-45aa-a3bb-2883374e0f9b)


后续，再有类似的问题：
1  可以直接去相关源那里咨询建议更新相关的源文件。
2 1Panel面板官方也说了后续优化一下安装，在安装时让用户选择 docker 源。

**Comment by YaKun9** [comment]
朋友, debian12一键安装之后页面一直加载出不来有遇到过吗

**Comment by chenkuicn** [comment]
> 朋友, debian12一键安装之后页面一直加载出不来有遇到过吗

没有遇到过，这个可以去社区发帖然后贴图请求帮助，估计是网络问题吧
