### ISSUE TITLE
在ESXI上装了几个linux 安装时都提示docker错误。

### ISSUE THREAD

**Issue by LowKeyOnline** [1Panel-dev/1Panel#3059]
### 请描述您的问题

[root@localhost ~]# curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sh quick_start.sh
安装包已存在，跳过下载
1panel-v1.8.3-linux-amd64/1panel.service
1panel-v1.8.3-linux-amd64/1pctl
1panel-v1.8.3-linux-amd64/LICENSE
1panel-v1.8.3-linux-amd64/README.md
1panel-v1.8.3-linux-amd64/install.sh
1panel-v1.8.3-linux-amd64/1panel

 ██╗    ██████╗  █████╗ ███╗   ██╗███████╗██╗     
███║    ██╔══██╗██╔══██╗████╗  ██║██╔════╝██║     
╚██║    ██████╔╝███████║██╔██╗ ██║█████╗  ██║     
 ██║    ██╔═══╝ ██╔══██║██║╚██╗██║██╔══╝  ██║     
 ██║    ██║     ██║  ██║██║ ╚████║███████╗███████╗
 ╚═╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝╚══════╝
[1Panel Log]: ======================= 开始安装 ======================= 
设置 1Panel 安装目录（默认为/opt）：
[1Panel Log]: 您选择的安装路径为 /opt 
[1Panel Log]: ... 在线安装 docker 
# Executing docker install script, commit: e5543d473431b782227f8908005543bb4389b8de
+ sh -c 'dnf install -y -q dnf-plugins-core'
+ sh -c 'dnf config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/fedora/docker-ce.repo'
Adding repo from: https://mirrors.aliyun.com/docker-ce/linux/fedora/docker-ce.repo
+ '[' stable '!=' stable ']'
+ sh -c 'dnf makecache'
Docker CE Stable - x86_64                       7.2 kB/s | 4.6 kB     00:00    
Errors during downloading metadata for repository 'docker-ce-stable':
  - Status code: 404 for https://mirrors.aliyun.com/docker-ce/linux/fedora/39/x86_64/stable/repodata/775d941bd6a8209756c05f48cb187c2ade6fe9a389fad6f159e5df3aa3d51cac-primary.xml.gz (IP: 2409:8c4c:e00:1015:3::3b2)
  - Status code: 404 for https://mirrors.aliyun.com/docker-ce/linux/fedora/39/x86_64/stable/repodata/162eb3faa8c2aa9f18ba9b366329c95363818ef6638864c613d9a6ef27176be2-filelists.xml.gz (IP: 2409:8c4c:e00:1015:3::3b2)
Error: Failed to download metadata for repo 'docker-ce-stable': Yum repo downloading error: Downloading error(s): repodata/775d941bd6a8209756c05f48cb187c2ade6fe9a389fad6f159e5df3aa3d51cac-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/162eb3faa8c2aa9f18ba9b366329c95363818ef6638864c613d9a6ef27176be2-filelists.xml.gz - Cannot download, all mirrors were already tried without success
Fedora 39 - x86_64 - aliyun                      35 kB/s | 6.1 kB     00:00    
Fedora 39 openh264 (From Cisco) - x86_64        5.3 kB/s | 989  B     00:00    
Fedora 39 - x86_64 - Updates - aliyun            24 kB/s | 8.1 kB     00:00    
Ignoring repositories: docker-ce-stable
Metadata cache created.
+ sh -c 'dnf install -y -q docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-ce-rootless-extras docker-buildx-plugin'
Error: Unable to find a match: docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-ce-rootless-extras docker-buildx-plugin
[1Panel Log]: ... 启动 docker 
Failed to enable unit: Unit file docker.service does not exist.
Failed to start docker.service: Unit docker.service not found.
[1Panel Log]: docker 安装失败 
[root@localhost ~]#

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，可以尝试手动安装好 docker 后再来运行 1Panel 在线安装脚本。
> 可以使用如下 docker 安装脚本：
```shell
bash <(curl -sSL https://linuxmirrors.cn/docker.sh)
```

**Comment by LowKeyOnline** [comment]
─ 是否安装最新版本的 Docker Engine? [Y/n] y

 ❖  阿里云                                   1)
 ❖  腾讯云                                   2)
 ❖  华为云                                   3)
 ❖  微软 Azure 中国                          4)
 ❖  网易                                     5)
 ❖  清华大学                                 6)
 ❖  北京大学                                 7)
 ❖  南京大学                                 8)
 ❖  上海交通大学                             9)
 ❖  中国科学技术大学                        10)
 ❖  中国科学院软件研究所                    11)
 ❖  官方                                    12)

└─ 请选择并输入你想使用的 Docker CE 源 [ 1-12 ]：1

 ❖  上海交通大学                                   1)
 ❖  网易                                           2)
 ❖  腾讯云                                         3)
 ❖  道客 DaoCloud                                  4)
 ❖  微软 Azure 中国                                5)
 ❖  阿里云（杭州）                                 6)
 ❖  阿里云（上海）                                 7)
 ❖  阿里云（青岛）                                 8)
 ❖  阿里云（北京）                                 9)
 ❖  阿里云（张家口）                              10)
 ❖  阿里云（呼和浩特）                            11)
 ❖  阿里云（乌兰察布）                            12)
 ❖  阿里云（深圳）                                13)
 ❖  阿里云（河源）                                14)
 ❖  阿里云（广州）                                15)
 ❖  阿里云（成都）                                16)
 ❖  阿里云（香港）                                17)
 ❖  阿里云（日本-东京）                           18)
 ❖  阿里云（新加坡）                              19)
 ❖  阿里云（澳大利亚-悉尼）                       20)
 ❖  阿里云（马来西亚-吉隆坡）                     21)
 ❖  阿里云（印度尼西亚-雅加达）                   22)
 ❖  阿里云（印度-孟买）                           23)
 ❖  阿里云（德国-法兰克福）                       24)
 ❖  阿里云（英国-伦敦）                           25)
 ❖  阿里云（美国西部-硅谷）                       26)
 ❖  阿里云（美国东部-弗吉尼亚）                   27)
 ❖  阿里云（阿联酋-迪拜）                         28)
 ❖  谷歌云                                        29)
 ❖  官方                                          30)

└─ 请选择并输入你想使用的 Docker Registry 源 [ 1-30 ]：13

[*] 开始同步软件源...

Fedora 39 - x86_64 - aliyun                                                                                                                                                                                                                                    77 kB/s | 6.1 kB     00:00    
Fedora 39 openh264 (From Cisco) - x86_64                                                                                                                                                                                                                      1.1 kB/s | 989  B     00:00    
Fedora 39 - x86_64 - Updates - aliyun                                                                                                                                                                                                                          74 kB/s | 8.1 kB     00:00    
Metadata cache created.

[DONE] 软件源同步结束

Last metadata expiration check: 0:00:02 ago on Sun 26 Nov 2023 01:51:15 AM EST.
Package device-mapper-persistent-data-1.0.6-2.fc39.x86_64 is already installed.
Package lvm2-2.03.22-1.fc39.x86_64 is already installed.
Dependencies resolved.
==============================================================================================================================================================================================================================================================================================
 Package                                                                          Architecture                                                   Version                                                                Repository                                                       Size
==============================================================================================================================================================================================================================================================================================
Installing:
 dnf-utils                                                                        noarch                                                         4.4.3-1.fc39                                                           updates                                                          37 k
Upgrading:
 dnf-plugins-core                                                                 noarch                                                         4.4.3-1.fc39                                                           updates                                                          38 k
 python3-dnf-plugins-core                                                         noarch                                                         4.4.3-1.fc39                                                           updates                                                         317 k

Transaction Summary
==============================================================================================================================================================================================================================================================================================
Install  1 Package
Upgrade  2 Packages

Total size: 392 k
Downloading Packages:
[SKIPPED] dnf-utils-4.4.3-1.fc39.noarch.rpm: Already downloaded                                                                                                                                                                                                                              
[SKIPPED] dnf-plugins-core-4.4.3-1.fc39.noarch.rpm: Already downloaded                                                                                                                                                                                                                       
[SKIPPED] python3-dnf-plugins-core-4.4.3-1.fc39.noarch.rpm: Already downloaded                                                                                                                                                                                                               
Fedora 39 - x86_64 - Updates - aliyun                                                                                                                                                                                                                         0.0  B/s |   0  B     00:00    
Curl error (37): Couldn't read a file:// file for file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-x86_64 [Couldn't open file /etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-x86_64]
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
/dev/fd/63: line 472: yum-config-manager: command not found
sed: can't read /etc/yum.repos.d/docker-ce.repo: No such file or directory
No match for argument: docker*
No match for argument: containerd.io
No match for argument: podman*
No match for argument: runc
No packages marked for removal.
Dependencies resolved.
Nothing to do.
Complete!
Last metadata expiration check: 0:00:10 ago on Sun 26 Nov 2023 01:51:15 AM EST.
No match for argument: docker-ce
No match for argument: docker-ce-cli
No match for argument: containerd.io
No match for argument: docker-buildx-plugin
No match for argument: docker-compose-plugin
Error: Unable to find a match: docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

└─ 检测到已备份的 Docker 配置文件，是否跳过覆盖备份? [Y/n] 

[ERROR] 安装失败


[DONE] 脚本执行结束

 ┌───────────────────────────────┐
 │▞▀▖            ▙▗▌      ▗▐     │
 │▚▄ ▌ ▌▛▀▖▞▀▖▙▀▖▌▘▌▝▀▖▛▀▖▄▜▀ ▞▀▖│
 │▖ ▌▌ ▌▙▄▘▛▀ ▌  ▌ ▌▞▀▌▌ ▌▐▐ ▖▌ ▌│
 │▝▀ ▝▀▘▌  ▝▀▘▘  ▘ ▘▝▀▘▘ ▘▀▘▀ ▝▀ │
 └───────────────────────────────┘
    Powered by linuxmirrors.cn
