### ISSUE TITLE
[FEATURE] Some suggestions regarding Docker advice

### ISSUE THREAD

**Issue by Baldur404** [1Panel-dev/1Panel#3061]
### 1Panel 版本

v1.7.4

### 请描述您的需求或者改进建议

- My server's Elasticsearch container frequently crashes due to insufficient memory.
I need to restart manually
- The container manager is unable to alert me

### 请描述你建议的实现方案

- Implement automatic restart functionality for container on abnormal closure
- SMTP can be utilized to send alert emails when the container experiences an exception.

**Comment by wanghe-fit2cloud** [comment]
Thank you for your feedback, we will consider the suggestions mentioned in future versions.

**Comment by wanghe-fit2cloud** [comment]
通知、告警相关需求的讨论，统一汇总到该 issue #614
