### ISSUE TITLE
[BUG]synapse安装失败

### ISSUE THREAD

**Issue by mjsoftking** [1Panel-dev/1Panel#3063]
### 联系方式

1406993111@qq.com

### 1Panel 版本

1.8.3

### 问题描述

synapse安装失败

![image](https://github.com/1Panel-dev/1Panel/assets/23021469/3920dec4-6e13-4242-9ae5-2989e01b38c6)

![image](https://github.com/1Panel-dev/1Panel/assets/23021469/7d21f2db-c45c-4e88-8a3a-257212129e3a)

### 重现步骤

商店中找到synapse，安装时提示失败

**Comment by wanghe-fit2cloud** [comment]
Synapse 持久化文件会放到自建 volume 中，需要提前手动创建 synapse-data。
<img width="664" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/601c0e99-8f74-4832-b831-ef5c30527985">
