### ISSUE TITLE
[QUESTION] 登录日志出现特殊 Failed 行

### ISSUE THREAD

**Issue by EmyiaEllen** [1Panel-dev/1Panel#3067]
### 请描述您的问题

![failed-1](https://github.com/1Panel-dev/1Panel/assets/82955455/fa6748d6-7c85-402b-9c30-18f4c429d3ae)
![failed-2](https://github.com/1Panel-dev/1Panel/assets/82955455/c73590f1-8bd5-4f7f-a8de-ad3194e18daf)
![failed-3](https://github.com/1Panel-dev/1Panel/assets/82955455/209ab73e-e0e0-4c5e-9864-651c881c63dc)
后面的日志还有failed行，重启服务器后该行还是存在，这是意外行输出吗，什么情况会输出该行呢？

**Comment by wanghe-fit2cloud** [comment]
参考该 Issue：#1746 
> v1.9.0 版本也会支持 Fail2ban。

**Comment by wanghe-fit2cloud** [comment]
重复 #1643
