### ISSUE TITLE
面板文件管理zip解压失败

### ISSUE THREAD

**Issue by ifacecn** [1Panel-dev/1Panel#3068]
### 1Panel 版本

1.8.3

### 问题描述

主机安装了unzip，但是在面板里使用文件解压还是提示zip 命令不存在，请先在宿主机安装此命令，但是在命令行使用unzip命令又可以解压

### 重现步骤

就是这样的

**Comment by zhengkunwang223** [comment]
好的 我们先在本地复现一下

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
