### ISSUE TITLE
[FEATURE] 安装OpenResty后的端口问题

### ISSUE THREAD

**Issue by static7** [1Panel-dev/1Panel#3069]
### 1Panel 版本

v1.8.3

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/11241063/9c142865-bf77-4149-8e2f-a24e845b8eaa)
![image](https://github.com/1Panel-dev/1Panel/assets/11241063/bd5ff51e-0b30-4e6b-a6e8-636bc5cef439)

OpenResty后, 新建网站填写其他端口,防火墙默认没有开放, 而且80,443也没有默认开放

### 请描述你建议的实现方案

建议把新建网站的端口单独拆分出来, 新建网站时, 填写的端口 默认同步到防火墙并开放

**Comment by static7** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/11241063/d48804cf-9f62-4d46-9736-fc53f6948810)
监听ipv6端口? ipv6有端口吗? 不是ipv6地址吗?

**Comment by zhengkunwang223** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/0a4d069f-2bb4-44fd-b802-20b14c13490c)
安装的时候会有提醒 host 模式并不会主动放开防火墙端口

**Comment by zhengkunwang223** [comment]
> ![image](https://private-user-images.githubusercontent.com/11241063/285702701-d48804cf-9f62-4d46-9736-fc53f6948810.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNTIzNjQsIm5iZiI6MTcwMTA1MjA2NCwicGF0aCI6Ii8xMTI0MTA2My8yODU3MDI3MDEtZDQ4ODA0Y2YtOWY2Mi00ZDQ2LTk3MzYtZmM1M2Y2OTQ4ODEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDAyMjc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyYjNjOWNlNTVkNDg3ZGUzMzMxMzUxNGM5ZjJmNzc3NjU2Mjc1YjA5ZDU5NTA1MGFmNjE1ZDZhY2RjYjhlNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Twvddx3pDglS21Oylwnc0ZUpVSkz1DOZzRjI6G9o0Jk) 监听ipv6端口? ipv6有端口吗? 不是ipv6地址吗?

地址不能监听

**Comment by static7** [comment]
> ![image](https://private-user-images.githubusercontent.com/31820853/285705447-0a4d069f-2bb4-44fd-b802-20b14c13490c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNTc3NDgsIm5iZiI6MTcwMTA1NzQ0OCwicGF0aCI6Ii8zMTgyMDg1My8yODU3MDU0NDctMGE0ZDA2OWYtMmJiNC00NGZkLWI4MDItMjBiMTRjMTM0OTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDAzNTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZGNjNjNlNjVhYTU4YjJmOGY5NTBkYzk1NjZhMGJhOTFiMDJlOTQ3YzI3Y2RlYzU5Yzc2N2VkMTJhZmQ4YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aFymFUslMITouwiKu9dj7I7nUNAVS0vHWhM0SEr2Ie8) 安装的时候会有提醒 host 模式并不会主动放开防火墙端口

建议再优化一下吧, 或者再次提醒一下.

**Comment by zhengkunwang223** [comment]
> > ![image](https://private-user-images.githubusercontent.com/31820853/285705447-0a4d069f-2bb4-44fd-b802-20b14c13490c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNTc3NDgsIm5iZiI6MTcwMTA1NzQ0OCwicGF0aCI6Ii8zMTgyMDg1My8yODU3MDU0NDctMGE0ZDA2OWYtMmJiNC00NGZkLWI4MDItMjBiMTRjMTM0OTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDAzNTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZGNjNjNlNjVhYTU4YjJmOGY5NTBkYzk1NjZhMGJhOTFiMDJlOTQ3YzI3Y2RlYzU5Yzc2N2VkMTJhZmQ4YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aFymFUslMITouwiKu9dj7I7nUNAVS0vHWhM0SEr2Ie8) 安装的时候会有提醒 host 模式并不会主动放开防火墙端口
> 
> 建议再优化一下吧, 或者再次提醒一下.

当前的提示已经很明显了
