### ISSUE TITLE
[FEATURE] 希望优化 openresty 网站默认请求日志

### ISSUE THREAD

**Issue by jsznb** [1Panel-dev/1Panel#3073]
### 1Panel 版本

v1.8.3

### 请描述您的需求或者改进建议

1、希望在日志配置中加入 $request_time, $upstream_response_time 记录请求响应时间
2、在全局配置中有一条 log_format main, 但是nginx网站使用的是默认日志格式为 combined，希望能统一使用全局配置中的 log_format main

### 请描述你建议的实现方案

1,
```
log_format main '$remote_addr - $remote_user [$time_local] "$request "' '$status $body_bytes_sent "$http_referer"' '"$http_user_agent" "$http_x_forwarded_for"'; 
=>
log_format main '$remote_addr - $remote_user [$time_local] "$request "' '$status $body_bytes_sent "$http_referer" ""$request_time" "$upstream_response_time"' '"$http_user_agent" "$http_x_forwarded_for"'; 
```
2, 
```
access_log /www/sites/dataease/log/access.log
=>
access_log /www/sites/dataease/log/access.log main; 
```

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/106230326/5463e01a-6a10-4813-ad6c-e94ae60d7b09)
![image](https://github.com/1Panel-dev/1Panel/assets/106230326/18b1dfa8-9305-489d-99a4-18c0990f54bd)

**Comment by zhengkunwang223** [comment]
感谢建议 我们先测试一下

**Comment by wanghe-fit2cloud** [comment]
重复 #2383
