### ISSUE TITLE
[FEATURE] 希望1Panel的深色亮色模式能跟随浏览器设置

### ISSUE THREAD

**Issue by AliusLeeOuO** [1Panel-dev/1Panel#3075]
### 1Panel 版本

1.8.3

### 请描述您的需求或者改进建议

希望1Panel的深色亮色模式能跟随浏览器设置。

### 请描述你建议的实现方案

看到前端使用vue3，可以尝试使用vueuse库来实现本需求。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by zyyfit** [comment]
1.9.0 可以设置面板主题跟随系统，会跟随电脑/手机系统的主题色变化

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
