### ISSUE TITLE
[FEATURE] 计划任务希望能添加多个执行周期

### ISSUE THREAD

**Issue by jsznb** [1Panel-dev/1Panel#3077]
### 1Panel 版本

v1.8.3

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/106230326/c57d3d8c-8376-41ea-9f3c-192a2117f129)

**Comment by ssongliu** [comment]
感谢反馈，重复 #1727 ，后续版本优化。
