### ISSUE TITLE
希望官方考虑增加多主机管理

### ISSUE THREAD

**Issue by szzylph** [1Panel-dev/1Panel#308]
### 1Panel 版本

1.0.2

### 请描述您的需求或者改进建议

希望官方考虑增加多主机管理，方便批量管理N多同类型的主机资源！

**Comment by zhengkunwang223** [comment]
感谢反馈 这个我们考虑一下

**Comment by chixq** [comment]
这不是成了云管、或者堡垒机了。

**Comment by maninhill** [comment]
1Panel 会关注在单机 Linux的运维管理。

多主机管理推荐使用 JumpServer 堡垒机来实现。尤其现在 JumpServer 也支持 Web 资产，可以通过Web 可视化连上 1Panel，实现多主机管理。
