### ISSUE TITLE
动不动就CPU占满

### ISSUE THREAD

**Issue by LowKeyOnline** [1Panel-dev/1Panel#3080]
### 联系方式

zhifozhifo@gmail.com

### 1Panel 版本

1.8.3

### 问题描述

用的是阿里云ES服务器，2G 2核，安装后没多就CPU占满，有时重启后部署的网站无法打开要重启DOCKER，才能恢复，没多久后就CPU占满了
![微信截图_20231127174814](https://github.com/1Panel-dev/1Panel/assets/45997524/d8b298af-0bc0-4aea-9e19-0ce6c9772d11)

### 重现步骤

重装过面板后还是这样。

**Comment by zhengkunwang223** [comment]
应该与你安装的应用多少有关系。
> 可以查看一下 `应用商店` - `已安装` 列表，也可以进入 `主机` - `进程管理` 页面查看相关进程。

**Comment by LowKeyOnline** [comment]
![webwxgetmsgimg](https://github.com/1Panel-dev/1Panel/assets/45997524/be74e288-c0d3-40f8-bf32-6fde5aac4083)
又出现了，可以帮忙看看吗？
