### ISSUE TITLE
前几个月就说的要适配Umami

### ISSUE THREAD

**Issue by ACZSHOP** [1Panel-dev/1Panel#3081]
### 1Panel 版本

1.8.3

### 请描述您的需求或者改进建议

能否适配Umami ？这个在前几个月就已经在社区搞过投票了！

### 请描述你建议的实现方案

https://github.com/umami-software/umami

### 附加信息

社区链接https://bbs.fit2cloud.com/t/topic/1021
当时说1.7.0就会更新，结果到现在还没有
![1](https://github.com/1Panel-dev/1Panel/assets/142337549/ac8319ef-2317-4144-b97c-39a461bac828)
![2](https://github.com/1Panel-dev/1Panel/assets/142337549/fc957f44-638e-49de-9b6d-fcbd5886d44e)
![3](https://github.com/1Panel-dev/1Panel/assets/142337549/4a73dcf3-4ce0-4656-aa6b-39dc8575698b)

**Comment by wanghe-fit2cloud** [comment]
目前数据库管理还不支持 PostgreSQL 数据库，所以应用商店中还不能直接添加上述应用。
> 当前版本可以通过 `容器` 菜单中的 `编排` 来管理服务，或者通过 [创建本地应用](https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8) 的方式来管理。

**Comment by wanghe-fit2cloud** [comment]
重复 #1270

**Comment by ACZSHOP** [comment]
> 目前数据库管理还不支持 PostgreSQL 数据库，所以应用商店中还不能直接添加上述应用。
> 
> > 当前版本可以通过  菜单中的  来管理服务，或者通过 [创建本地应用](https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8) 的方式来管理。`容器``编排`

应用商店里面不是已经有PostgreSQL数据库了吗

**Comment by wanghe-fit2cloud** [comment]
> > 目前数据库管理还不支持 PostgreSQL 数据库，所以应用商店中还不能直接添加上述应用。
> > > 当前版本可以通过  菜单中的  来管理服务，或者通过 [创建本地应用](https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8) 的方式来管理。`` 容器``编排 ``
> 
> 应用商店里面不是已经有PostgreSQL数据库了吗

这里指的是 `数据库` 菜单中不支持管理 PostgreSQL。
