### ISSUE TITLE
[BUG]是不支持国际版的的Dnspod.com吗，申请证书时显示token不存在

### ISSUE THREAD

**Issue by jianmaikj** [1Panel-dev/1Panel#3082]
### 1Panel 版本

1.8.3

### 问题描述

证书申请页面，DNS验证，DNSPOD（dnspod.com）无法验证

### 重现步骤

证书申请页面，DNS验证，DNSPOD（dnspod.com）无法验证

**Comment by zhengkunwang223** [comment]
截图提供一下

**Comment by wanghe-fit2cloud** [comment]
先关闭这个 Issue 了。如在后续的使用过程中依然存在上述问题，我们继续在这个 Issue 中讨论。
