### ISSUE TITLE
[BUG]终端全屏后侧边栏丢失，且无法找回

### ISSUE THREAD

**Issue by Cui1518** [1Panel-dev/1Panel#3083]
### 1Panel 版本

v1.8.3

### 问题描述

mac 谷歌浏览器版本 119.0.6045.159（正式版本） (arm64) 终端全屏后侧边栏丢失，且无法找回

### 重现步骤

无法重现，侧边栏还未找回，

### 附加信息

<img width="1422" alt="Snipaste_2023-11-28_09-29-11" src="https://github.com/1Panel-dev/1Panel/assets/63806724/20613da8-cd69-413d-a3dd-cbdcb1ed9ac9">

**Comment by ssongliu** [comment]
感谢反馈，这里应该是全屏时意外退出浏览器导致的，可以尝试输入终端路由，直接访问一下。
如：https://172.16.10.91:9999/hosts/terminal ，ip 端口需要改一下。
