### ISSUE TITLE
[BUG] 拖拽上传文件夹问题

### ISSUE THREAD

**Issue by static7** [1Panel-dev/1Panel#3084]
### 1Panel 版本

v1.8.3

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/11241063/c25de92d-fe3f-4f77-8fec-d494a16438fe)
![image](https://github.com/1Panel-dev/1Panel/assets/11241063/dabaaa6b-d18d-4fed-abfa-0bb6881e66c5)
images文件夹下有文件,明明有图片文件

### 重现步骤

拖拽上传提示错误

**Comment by zhengkunwang223** [comment]
当前控件不支持同时拖拽文件和文件夹
你可以通过点击上传文件夹按钮来上传文件夹

**Comment by static7** [comment]
> 当前控件不支持同时拖拽文件和文件夹 你可以通过点击上传文件夹按钮来上传文件夹

也不能同时上传多个文件夹, 这个功能感觉有待优化. 最好一次性上传完成. 
我也试了上传上一级目录的文件夹, 上传后会多一级目录出来. 这个确实非常不方便, 应当给用户选择要不要保留上级目录

**Comment by static7** [comment]
还有一个问题, 分批上传后, 文件的权限也变了. 导致web无法访问.

**Comment by zhengkunwang223** [comment]
> > 当前控件不支持同时拖拽文件和文件夹 你可以通过点击上传文件夹按钮来上传文件夹
> 
> 也不能同时上传多个文件夹, 这个功能感觉有待优化. 最好一次性上传完成. 我也试了上传上一级目录的文件夹, 上传后会多一级目录出来. 这个确实非常不方便, 应当给用户选择要不要保留上级目录

可以上传多个文件夹 但是当前版本不能多选并上传 只能单个选择

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
