### ISSUE TITLE
构建镜像失败

### ISSUE THREAD

**Issue by ifacecn** [1Panel-dev/1Panel#3086]
### 1Panel 版本

1.8.3

### 问题描述

构建镜像一直停留在这里
![IMG_2191](https://github.com/1Panel-dev/1Panel/assets/43784195/1af0f3a0-9dfb-4829-94e3-5d4b157864a7)

### 重现步骤

一直都是，试了几次

**Comment by Duinks** [comment]
![IMG_2191](https://github.com/1Panel-dev/1Panel/assets/43784195/1af0f3a0-9dfb-4829-94e3-5d4b157864a7)

**Comment by ssongliu** [comment]
感谢反馈，这里使用docker build 手动构建能成功吗？构建任务是会比较耗时，中间大概观察了多久呢？

**Comment by ifacecn** [comment]
20分钟有余

**Comment by ssongliu** [comment]
> 20分钟有余

手动构建试试，排除 Dockerfile 自身原因，如果手动构建没问题的话，麻烦贴一下 Dockerfile 我们开发环境复现一下。

**Comment by ifacecn** [comment]
升级1.8.4后构建成功
