### ISSUE TITLE
[BUG] 官方应用商店 OpenResty Docker host模式无法通过 localhost/127.0.0.1 访问宿主机

### ISSUE THREAD

**Issue by GhostIsWinner** [1Panel-dev/1Panel#3088]
### 1Panel 版本

当前运行版本：v1.8.3

### 问题描述

官方应用商店 OpenResty Docker运行网络模式的问题
通过 `docker inspect NETWORK ID` 查询到
```
[
    {
        "Name": "host",
        "Id": "4b9596f042b40f853294585ad632598b4f6a1b4ee6037b0935f21567cd69aa1d",
        "Created": "2023-11-26T21:24:55.747331968+08:00",
        "Scope": "local",
        "Driver": "host",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "276af4d3bd95c9927362f6712eacee6d145852ed632a7078ab34d34c32253d28": {
                "Name": "1Panel-openresty-KYsu",
                "EndpointID": "60db731c0f68fbd95c992739eb051a0af18cd3955c9efe6fdad7b1990911df3a",
                "MacAddress": "",
                "IPv4Address": "",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

OpenResty 运行在 host 模式，按照正常来说该模式下容器可以直接使用 127.0.0.1, localhost 加上端口来访问宿主机 运行的服务。

结果不行，必须通过Docker brige模式下的网关172.17.0.1，才能在容器内成功访问宿主机。

### 重现步骤

1. 宿主机本地Go运行了一个HTTP API，宿主机通过命令行 `curl http://localhost:8888 / curl http://127.0.0.1:8888` 正常访问接口，返回成功（此时端口并没有对外网开放）

2. OpenResty 运行在 host 模式，部署一个PHP项目，PHP内使用curl 命令访问  宿主机运行的API地址，
     `http://localhost:8888 / http://127.0.0.1:8888`  均失败，返回以下错误  
    `cURL Error: Failed to connect to 127.0.0.1/localhost port 8888 after 0 ms: Connection refused `

期初以为是端口问题，打开端口运行后一样情况。

所以，我就怀疑，是不是host模式出现了问题，于是我使用**Docker brige模式下的网关172.17.0.1对localhost进行替换**，**PHP内使用curl 命令访问 `http://172.17.0.1:8888`**，结果如下：

通过打开防火墙端口8888，外网访问 PHP项目网址，结果成功返回了 宿主机本地HTTP API运行的API内容！

**所以这是否是与host模式出现问题了有关呢，OpenResty 运行在 host 模式，按照正常来说该模式下容器可以直接使用 127.0.0.1, localhost 加上端口来访问宿主机 运行的服务，可是没有成功，反而brige模式下的网关172.17.0.1可以成功访问到宿主机。此Docker host模式下 运行的网站和服务器是可以正常通过外网来访问的，并没有进行任何docker 的端口映射。**

**Comment by zhengkunwang223** [comment]
Openresty 是 Host 模式 主要是为了方便  Openresty 代理非容器安装的应用
PHP 容器 不是 Host 模式，所以在 PHP 内访问 localhost 或者 127.0.0.1  是不能访问到宿主机的服务的

**Comment by GhostIsWinner** [comment]
> Openresty 是 Host 模式 主要是为了方便 Openresty 代理非容器安装的应用 PHP 容器 不是 Host 模式，所以在 PHP 内访问 localhost 或者 127.0.0.1 是不能访问到宿主机的服务的

好的非常感谢您，我以为php是在Openresty 容器内运行的，通过防火墙打开端口 仅允许172.18.0.0/24访问后，已经成功访问到宿主机。

再请问一下，容器内部访问宿主机，应该算是内网访问，为何需要来打开防火墙端口呢？感谢不尽！

**Comment by zhengkunwang223** [comment]
> > Openresty 是 Host 模式 主要是为了方便 Openresty 代理非容器安装的应用 PHP 容器 不是 Host 模式，所以在 PHP 内访问 localhost 或者 127.0.0.1 是不能访问到宿主机的服务的
> 
> 好的非常感谢您，我以为php是在Openresty 容器内运行的，通过防火墙打开端口 仅允许172.18.0.0/24访问后，已经成功访问到宿主机。
> 
> 再请问一下，容器内部访问宿主机，应该算是内网访问，为何需要来打开防火墙端口呢？感谢不尽！

其实不用 在PHP容器内你可以访问 172.18.0.1 :[你的宿主机端口] 来访问你宿主机上的服务
