### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by AKAOOK** [1Panel-dev/1Panel#3089]
### 1Panel 版本

1.82

### 请描述您的需求或者改进建议

希望添加runnerGo自动化测试项目
![runnergo](https://github.com/1Panel-dev/1Panel/assets/84619335/a5f742a2-5a41-409f-8e12-933e6e24382f)
Go

**Comment by zhengkunwang223** [comment]
satr 不多 开源社区不活跃 暂时上不了 请理解
