### ISSUE TITLE
[FEATURE]快照功能能否包括自定义容器及映射目录备份

### ISSUE THREAD

**Issue by miaowmint** [1Panel-dev/1Panel#3094]
### 1Panel 版本

v1.8.4

### 请描述您的需求或者改进建议

我解压了快照包，发现目前的快照功能似乎只囊括了通过应用商店安装的容器，而另一些我自己通过docker run 启动的容器并没有进行备份

### 请描述你建议的实现方案

能否让快照功能实现备份自定义容器，具体的方式我觉得可以参考watchtower；将所有目录映射的文件备份，将容器运行的命令备份；等到恢复的时候将文件恢复至原来的位置，然后用备份的命令重新运行docker容器

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1Panel 早期版本在创建快照时会备份正在运行的容器，但是由于快照文件过大、上传第三方备份账号超时、文件被使用导致创建快照失败等等的问题，经团队内部讨论就就取消了容器的备份，只保留已安装应用的正常备份恢复。

> 可以借助计划任务的功能来实现容器的备份、恢复。
