### ISSUE TITLE
强烈建议在线编辑文档功能可以在左边加个文件树功能

### ISSUE THREAD

**Issue by zekibu99** [1Panel-dev/1Panel#3095]
### 1Panel 版本

1.8.4

### 请描述您的需求或者改进建议

作为喜欢在服务器面板改文件 临时接接口的人，强烈建议在线编辑文档功能可以在左边加个文件树功能，既然右侧的缩略图滚动条都加了(我反而觉得这个功能没啥大用)，为什么不干脆做到底。每次改完一个文件还得关掉然后翻好几层文件夹再打开编辑真的好累。

还有就是希望可以最大化最小化编辑器，一两百行的文件都得往下滑好久😂

为什么PHP环境默认不安装mysqli mysql pdo_mysql 这些基本常用拓展

总结：作为运维可能会很喜欢1panel，但是像我这样的个人或者公司开发者来说好像不太友好

**Comment by zhengkunwang223** [comment]
1. 文件树功能后续版本增加
2. PHP 环境常用拓展太多，无法兼顾所有软件，后续考虑会出扩展模版功能

**Comment by wanghe-fit2cloud** [comment]
> 为什么PHP环境默认不安装mysqli mysql pdo_mysql 这些基本常用拓展

最终还是建议用户自行选择扩展，如果是默认安装上述扩展，build 出来的镜像会非常大。

**Comment by wanghe-fit2cloud** [comment]
最新版本已经支持了PHP扩展模版功能。

**Comment by wanghe-fit2cloud** [comment]
文件编辑器优化的需求，关注该 issue https://github.com/1Panel-dev/1Panel/issues/3624
> 预计会在 v1.10.12 版本支持。
