### ISSUE TITLE
[FEATURE] 建议增加nginx的404自定义页面设置

### ISSUE THREAD

**Issue by static7** [1Panel-dev/1Panel#3098]
### 1Panel 版本

v1.8.4

### 请描述您的需求或者改进建议

如题

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中针对部分类型的网站增加错误页面设置。

**Comment by wanghe-fit2cloud** [comment]
设置404等错误页面相关功能的讨论，统一汇总到该 issue #701
