### ISSUE TITLE
[QUESTION] 一键部署wordpress或者flarum后的默认密码是什么？

### ISSUE THREAD

**Issue by pincman** [1Panel-dev/1Panel#3099]
### 请描述您的问题

一键部署wordpress或者flarum后的默认密码是什么？在哪里查找和设置

**Comment by wanghe-fit2cloud** [comment]
进入应用商店列表，鼠标点击应用可查看应用详情，如下图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/56aabfb3-b7bc-4ed1-85df-179cc6d1172d)

> WordPress 密码是用户首次登录初始化设置的。
