### ISSUE TITLE
[QUESTION]在1Panel上添加备份账号（aliyun oss）的时候，出现签名错误

### ISSUE THREAD

**Issue by alittlehuaji** [1Panel-dev/1Panel#3103]
### 请描述您的问题

报错信息：
oss: service returned error: StatusCode=403, ErrorCode=SignatureDoesNotMatch, ErrorMessage="The request signature we calculated does not match the signature you provided. Check your key and signing method."

在提出此问题之前我已经确认我的AccessKey是正确的

**Comment by wanghe-fit2cloud** [comment]
可以先通过 ossbrowser 工具来校验 AK 和 SK 是否正确，ossbrowser 工具使用方法请参考 [快速使用 ossbrowser](https://help.aliyun.com/zh/oss/developer-reference/use-ossbrowser)。

**Comment by alittlehuaji** [comment]
已解决
