### ISSUE TITLE
镜像删除问题

### ISSUE THREAD

**Issue by ifacecn** [1Panel-dev/1Panel#3109]
### 1Panel 版本

1.8.5

### 问题描述

如果不先删除容器，直接删除镜像，会提示成功，但是ID还在，标签没有，试了试又把容器删掉，还是有，点击删除还是提示成功，但一直都在！

### 重现步骤

1.8.3就已经存在这个问题了

**Comment by ifacecn** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/43784195/1e900542-6556-4f00-85fa-900b9f49f500)

**Comment by wanghe-fit2cloud** [comment]
收到，下个版本优化。

**Comment by chenkuicn** [comment]
我先卸载应用然后删除镜像，但是硬盘空间没有释放，清除缓存重启服务器了还是如此，不知道哪里出问题了。希望能够顺带解决这个问题。

**Comment by chenkuicn** [comment]
> 我先卸载应用然后删除镜像，但是硬盘空间没有释放，清除缓存重启服务器了还是如此，不知道哪里出问题了。希望能够顺带解决这个问题。

先删除容器再操作其他才可以

**Comment by wanghe-fit2cloud** [comment]
> > 我先卸载应用然后删除镜像，但是硬盘空间没有释放，清除缓存重启服务器了还是如此，不知道哪里出问题了。希望能够顺带解决这个问题。
> 
> 先删除容器再操作其他才可以

正在使用中的镜像是不能被删除（释放空间占用）的

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
