### ISSUE TITLE
[FEATURE] QEMU 管理支持

### ISSUE THREAD

**Issue by wojiushixiaobai** [1Panel-dev/1Panel#311]
### 1Panel 版本

v1.0.1

### 请描述您的需求或者改进建议

添加 qemu 虚拟机管理功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会讨论并验证该需求的可行性。

**Comment by guclan** [comment]
从该项目的初衷来看，实现这个功能不太现实。你想要的功能应该是在其之上增加一个libvirt的web版了~~~~

**Comment by wanghe-fit2cloud** [comment]
经过内部讨论，我们暂时不考虑该需求。
