### ISSUE TITLE
[QUESTION]海外服务器安装halo会导致服务不可用     

### ISSUE THREAD

**Issue by cuevven** [1Panel-dev/1Panel#3110]
### 请描述您的问题

我用的是lightsail的轻服务，系统用的Ubuntu。安装halo过程一直提示连接超时，显示安装成功后，会导致1panel服务不可用，刷新页面后直接显示拒绝连接。
SSH服务器uninstall and reinstall 1panel后，依然是拒绝连接。
不清楚是BUG还是环境问题。

**Comment by wanghe-fit2cloud** [comment]
1、首次安装应用会到阿里 OSS 获取应用安装包，提示超时就应该是海外服务器访问国内阿里 OSS 的网络问题。
2、可以进入服务器，执行 `1pctl status` 命令查看 1Panel 运行状态是否正常。

**Comment by cuevven** [comment]
有没有可能针对海外服务器做优化？ssh 1pctl状态是正常的，但是web端确实没法访问

**Comment by wanghe-fit2cloud** [comment]
> 有没有可能针对海外服务器做优化？

1Panel 系统资源是统一放在阿里 OSS 的，是全球加速的 CDN，应该不会慢，除非 CDN 节点有问题了。

**Comment by wanghe-fit2cloud** [comment]
> 1pctl状态是正常的，但是web端确实没法访问

网络问题，检查一下安全组或者防火墙是否放行了 1Panel 系统端口吧
