### ISSUE TITLE
[BUG] 证书自动更新后面板SSL不会自动更新

### ISSUE THREAD

**Issue by DongShaoNB** [1Panel-dev/1Panel#3111]
### 1Panel 版本

1.8.5

### 问题描述

证书自动更新后面板SSL不会自动更新

### 重现步骤

证书过期

**Comment by ssongliu** [comment]
感谢反馈，v.1.9.0 版本支持。

**Comment by zyyfit** [comment]
1.9.0 版本面板选择ssl证书后，证书更新时面板ssl证书会同步更新，不过需要手动重启面板生效

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。

**Comment by wangchaoit** [comment]
v1.10.30-lts 版本还是又这样的问题吗？  我的证书今天到期，还是我手动点击更新才可以用的，好像我用了这么久每次都是需要手动重新申请。

**Comment by wanghe-fit2cloud** [comment]
> v1.10.30-lts 版本还是又这样的问题吗？ 我的证书今天到期，还是我手动点击更新才可以用的，好像我用了这么久每次都是需要手动重新申请。

麻烦再重新提交一个新的 issue，最好能提供相关截图或日志信息，方便我们后续排查和跟进。
