### ISSUE TITLE
[BUG] OpenResty问题

### ISSUE THREAD

**Issue by Kagura-Nanaa** [1Panel-dev/1Panel#3112]
### 1Panel 版本

v1.8.5

### 问题描述

变更OpenResty所属容器的内存限制后，网站页面下显示OpenResty未运行，实际已经启动，并且反代运行正常
![image](https://github.com/1Panel-dev/1Panel/assets/44108528/8960dabc-377c-441a-a1b6-1aad042a712c)

### 重现步骤

1.在应用商店中安装OpenResty
2.创建一个反代网站
3.变更OpenResty所属容器的内存限制

**Comment by zhengkunwang223** [comment]
> ### 联系方式
> _No response_
> 
> ### 1Panel 版本
> v1.8.5
> 
> ### 问题描述
> 变更OpenResty所属容器的内存限制后，网站页面下显示OpenResty未运行，实际已经启动，并且反代运行正常 ![image](https://private-user-images.githubusercontent.com/44108528/286793218-8960dabc-377c-441a-a1b6-1aad042a712c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMTE4NDYsIm5iZiI6MTcwMTMxMTU0NiwicGF0aCI6Ii80NDEwODUyOC8yODY3OTMyMTgtODk2MGRhYmMtMzc3Yy00NDFhLWExYjYtMWFhZDA0MmE3MTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDAyMzIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNjcxOGY1YjVkMmRiMjNhOTNiNDllMDAzMmNhN2ViMDgyYjNjYzI3ZWEyMjhkNGNiOTRiOWI4OGJjY2Y3ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UhO5am5CvyTJT7TzVcsm6E3GQcHTtjDwXefH_ieRCN4)
> 
> ### 重现步骤
> 1.在应用商店中安装OpenResty 2.创建一个反代网站 3.变更OpenResty所属容器的内存限制
> 
> ### 期待的正确结果
> _No response_
> 
> ### 相关日志输出
> _No response_
> 
> ### 附加信息
> _No response_

在已安装那看一下状态日志

**Comment by Kagura-Nanaa** [comment]
> > ### 联系方式
> > _没有反应_
> > ### 1面板版本
> > v1.8.5
> > ### 问题描述
> > 更改OpenResty容器的内存限制后，网站页面下显示OpenResty未运行，实际已经启动，并且反代运行正常![图像](https://private-user-images.githubusercontent.com/44108528/286793218-8960dabc-377c-441a-a1b6-1aad042a712c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMTE4NDYsIm5iZiI6MTcwMTMxMTU0NiwicGF0aCI6Ii80NDEwODUyOC8yODY3OTMyMTgtODk2MGRhYmMtMzc3Yy00NDFhLWExYjYtMWFhZDA0MmE3MTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDAyMzIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNjcxOGY1YjVkMmRiMjNhOTNiNDllMDAzMmNhN2ViMDgyYjNjYzI3ZWEyMjhkNGNiOTRiOWI4OGJjY2Y3ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UhO5am5CvyTJT7TzVcsm6E3GQcHTtjDwXefH_ieRCN4)
> > ### 重置步骤
> > 1.在应用商店中安装OpenResty 2.创建一个反代网站3.更改OpenResty所属容器的内存限制
> > ### 期待的正确结果
> > _没有反应_
> > ### 相关日志 输出
> > _没有反应_
> > ### 附加信息
> > _没有反应_
> 
> 在已安装那看一下状态日志

应该是我重命名容器的原因，重建应用就ok了
