### ISSUE TITLE
[QUESTION]有考虑增加远程桌面RDP功能吗

### ISSUE THREAD

**Issue by zxwmfcm** [1Panel-dev/1Panel#3116]
### 请描述您的问题

有考虑增加远程桌面控制windows  linux功能吗  直接可以在网页上控制windows电脑

**Comment by wanghe-fit2cloud** [comment]
推荐使用我司另外一款开源产品 [JumpServer](https://github.com/jumpserver/jumpserver)。
> 在 1Panel 应用商店中支持一键部署。
