### ISSUE TITLE
[FEATURE]1Panel 使用建议。

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#3117]
### 1Panel 版本

最新

### 请描述您的需求或者改进建议

1.输入完名称，自动填充下面的用户名(和名称相同)
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/79f3eb04-e2bf-481d-8ac0-ffa26cbc3ead)

2.php运行环境真的很麻烦， 不知道缺少什么扩展没有安装

3.上传sql文件： 在a库进行上传，没有上传完成，这个时候切换到b库， 这个时候a库的文件上传完成，好像上传到了b库的备份列表中
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/185047d6-b477-47cc-aa58-333a7d1f81a6)

4.希望网站支持自定义目录，对部署老项目很方便，因为老项目 目录结构相对固定， 不方便抽离更改

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述建议，持续优化。

**Comment by wanghe-fit2cloud** [comment]
1.9.0 版本会优先支持自动填充数据库用户名。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
