### ISSUE TITLE
[FEATURE]希望一键部署Halo时可以选择PostgreSQL数据库

### ISSUE THREAD

**Issue by chenkuicn** [1Panel-dev/1Panel#3119]
### 1Panel 版本

v1.8.5

### 请描述您的需求或者改进建议

如题，实现1Panel一键部署Halo应用时可以选择PostgreSQL数据库。面板数据库中添加PostgreSQL管理

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复 #1978
