### ISSUE TITLE
[FEATURE]希望增加多台服务器监控功能

### ISSUE THREAD

**Issue by kksay2010** [1Panel-dev/1Panel#312]
### 1Panel 版本

1.0.2

### 请描述您的需求或者改进建议

参考：https://github.com/starsliao/Prometheus/tree/master/node_exporter
上述方案部署东西太多，不方便。希望你们的看板能够参考改进
![image](https://user-images.githubusercontent.com/29589474/226254256-6b3edae8-8eaa-4bf6-9665-a3da8a1735ea.png)

**Comment by maninhill** [comment]
https://github.com/louislam/uptime-kuma

我们应用商店会上架这个监控工具，到时你可以试一下。

**Comment by kksay2010** [comment]
> https://github.com/louislam/uptime-kuma
> 
> 我们应用商店会上架这个监控工具，到时你可以试一下。

kuma是网站监控，而非服务器监控
