### ISSUE TITLE
[BUG] openresty 证书问题

### ISSUE THREAD

**Issue by qwenode** [1Panel-dev/1Panel#3121]
### 1Panel 版本

1.8.5

### 问题描述

证书问题报错,还会导致nginx 卡住超时, 卡住时全部请求都超时

证书是通过1p后台一键申请的 Let's Encrypt,还有cf的证书
### 重现步骤

日志出现错误
2023/11/30 21:12:23 [warn] 1#1: "ssl_stapling" ignored, issuer certificate not found for certificate "/www/sit
2023/11/30 21:12:23 [warn] 7#7: no resolver defined to resolve r3.o.lencr.org while requesting certificate status, responder: r3.o.lencr.org, certificate
[error] 7#7: *16 cannot load certificate "data:": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE) while SSL handshaking, client:

检测了容器内可以正常解析dns
![image](https://github.com/1Panel-dev/1Panel/assets/8974108/41a703dd-3b1f-41bd-b12d-c98d8652e4ab)

**Comment by zhengkunwang223** [comment]
日志显示你的证书不完整

**Comment by MiderWong** [comment]
因为这个错误对站点没有影响、不用修复且ISSUES已经关闭，回复只为留作记录，因为我也出现一样的问题。
- 1、**说明：** `错误提示`代表的意思是`证书真实性验证失败`
- 2、**影响：** 不会造成站点不可访问问题
- 3、**原因：** 客户使用`HTTP`初始访问站点，在进行跳转`HTTPS`、下载证书、验证证书时触发此错误
 正常访问且证书正常的域名不会出现此错误，只会出现在服务器被人扫描所有开放域名并且试图访问没有证书或者Web服务器没有配置的域名时才会出现。举例：我常规配置域名DNS只有3条：`www/@/*` ，所以一般情况下访问所有二级域名都会跳转到`*`对应的服务器，比如访问`aaa.xx.com`，但是`*`对应的服务器上没有配置`aaa.xx.com`的解析，就会造成上述错误。
- 4、**修复：** 修改域名DNS配置，不要使用`*`进行泛域名解析
- 5、**其它：** 
  - 使用`fail2ban`防止被爆破
