### ISSUE TITLE
计划任务可以复制，或者直接上传脚本

### ISSUE THREAD

**Issue by yeyudoc** [1Panel-dev/1Panel#3123]
### 1Panel 版本

v1.8.5

### 请描述您的需求或者改进建议

希望计划任务可以复制，或者直接上传脚本，要不然操作太麻烦

### 请描述你建议的实现方案

希望计划任务可以复制，或者直接上传脚本

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复 #2738
