### ISSUE TITLE
进程管加强

### ISSUE THREAD

**Issue by yeyudoc** [1Panel-dev/1Panel#3124]
### 1Panel 版本

v1.8.5

### 请描述您的需求或者改进建议

希望鼠标移动到进程名上时显示完整进程命令，或者再加一列完整进程命令——更加直观
希望进程管理中有筛选器——使进程查找更方便

### 请描述你建议的实现方案

希望鼠标移动到进程名上时显示完整进程命令，或者再加一列完整进程命令——更加直观
希望进程管理中有筛选器——使进程查找更方便

**Comment by zhengkunwang223** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/cdb94c1a-6020-4a51-8a38-da1a49848241)
有状态筛选
后续可以加一个悬浮窗 显示进程命令

**Comment by yeyudoc** [comment]
我是希望有多个名称筛选，只显示特定几个名称的，只有个名称搜索还不太方便

**Comment by zhengkunwang223** [comment]
> 我是希望有多个名称筛选，只显示特定几个名称的，只有个名称搜索还不太方便

当前还没有这种控件和逻辑，如果后面提的人多了，会考虑增加

**Comment by wanghe-fit2cloud** [comment]
经讨论，暂无计划支持上述需求，望理解。
