### ISSUE TITLE
使用PHP8+运行环境建站会导致502

### ISSUE THREAD

**Issue by huangbh1024** [1Panel-dev/1Panel#3125]
### 请描述您的问题

使用PHP8+运行环境建站会导致502，但是用PHP7就不会出现这种情况
![image](https://github.com/1Panel-dev/1Panel/assets/72372968/44617aa8-3dd5-4f98-83f2-c50585b104e7)

**Comment by zhengkunwang223** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/39650934-bee8-4c8e-8d99-3ab33003db7e)
端口被其他进程占用了

**Comment by huangbh1024** [comment]
> ![image](https://private-user-images.githubusercontent.com/31820853/287161081-39650934-bee8-4c8e-8d99-3ab33003db7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MTA0MjMsIm5iZiI6MTcwMTQxMDEyMywicGF0aCI6Ii8zMTgyMDg1My8yODcxNjEwODEtMzk2NTA5MzQtYmVlOC00YzhlLThkOTktM2FiMzMwMDNkYjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA1NTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YjZhZmFjNDA1YWZlNWUzNmViYmI2NmIwNjkzOGEwMjIxMjRmMmQ1MmRjNzA2OWRiZTAyZTA5ZDk1ZWY0OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9SuLLW-KGRSRJ5Yf7KQKsYEjipreVVRXE_LuhyhtBeQ) 端口被其他进程占用了

但是我如果把这个网站删掉，重新使用相同的端口，用php7建站就没有这个问题欸

**Comment by zhengkunwang223** [comment]
> > ![image](https://private-user-images.githubusercontent.com/31820853/287161081-39650934-bee8-4c8e-8d99-3ab33003db7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MTA0MjMsIm5iZiI6MTcwMTQxMDEyMywicGF0aCI6Ii8zMTgyMDg1My8yODcxNjEwODEtMzk2NTA5MzQtYmVlOC00YzhlLThkOTktM2FiMzMwMDNkYjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA1NTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YjZhZmFjNDA1YWZlNWUzNmViYmI2NmIwNjkzOGEwMjIxMjRmMmQ1MmRjNzA2OWRiZTAyZTA5ZDk1ZWY0OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9SuLLW-KGRSRJ5Yf7KQKsYEjipreVVRXE_LuhyhtBeQ) 端口被其他进程占用了
> 
> 但是我如果把这个网站删掉，重新使用相同的端口，用php7建站就没有这个问题欸

可能性很低 你提供一下端口占用截图

**Comment by huangbh1024** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/31820853/287161081-39650934-bee8-4c8e-8d99-3ab33003db7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MTA0MjMsIm5iZiI6MTcwMTQxMDEyMywicGF0aCI6Ii8zMTgyMDg1My8yODcxNjEwODEtMzk2NTA5MzQtYmVlOC00YzhlLThkOTktM2FiMzMwMDNkYjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA1NTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YjZhZmFjNDA1YWZlNWUzNmViYmI2NmIwNjkzOGEwMjIxMjRmMmQ1MmRjNzA2OWRiZTAyZTA5ZDk1ZWY0OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9SuLLW-KGRSRJ5Yf7KQKsYEjipreVVRXE_LuhyhtBeQ) 端口被其他进程占用了
> > 
> > 
> > 但是我如果把这个网站删掉，重新使用相同的端口，用php7建站就没有这个问题欸
> 
> 可能性很低 你提供一下端口占用截图

没事了，是我写错了，对了，我还想问一下，是这么建站没错吧，但是我通过ip+端口访问的话是访问不了的，这是为啥
![image](https://github.com/1Panel-dev/1Panel/assets/72372968/5abe1316-8f98-4224-9764-90a9934e06ff)

**Comment by huangbh1024** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/31820853/287161081-39650934-bee8-4c8e-8d99-3ab33003db7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MTA0MjMsIm5iZiI6MTcwMTQxMDEyMywicGF0aCI6Ii8zMTgyMDg1My8yODcxNjEwODEtMzk2NTA5MzQtYmVlOC00YzhlLThkOTktM2FiMzMwMDNkYjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA1NTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YjZhZmFjNDA1YWZlNWUzNmViYmI2NmIwNjkzOGEwMjIxMjRmMmQ1MmRjNzA2OWRiZTAyZTA5ZDk1ZWY0OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9SuLLW-KGRSRJ5Yf7KQKsYEjipreVVRXE_LuhyhtBeQ) 端口被其他进程占用了
> > 
> > 
> > 但是我如果把这个网站删掉，重新使用相同的端口，用php7建站就没有这个问题欸
> 
> 可能性很低 你提供一下端口占用截图

是我自己的问题，写错了，还有就是端口3000是写在这吧，但是我这样做弄完，用ip+端口访问会502，是还需要其他的配置吗
![image](https://github.com/1Panel-dev/1Panel/assets/72372968/b692d9f2-97d4-436e-92b1-631385d4b47a)

**Comment by wanghe-fit2cloud** [comment]
使用主域名来访问网站。
> PHP-FPM 端口默认是不对外暴露（默认绑定 127.0.0.1）
