### ISSUE TITLE
[FEATURE]增加插件市场

### ISSUE THREAD

**Issue by sandogeek** [1Panel-dev/1Panel#3132]
### 1Panel 版本

1.8.4

### 请描述您的需求或者改进建议

通过增加插件机制，拓宽1Panel的用途，例如用户可以通过插件市场安装nas相关插件，从而获得管理虚拟机，状态面板显示硬盘 cpu温度等功能。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述需求。
> 插件机制，我们可能会在 2.0 版本重构时考虑。

**Comment by wanghe-fit2cloud** [comment]
服务器硬件（如 CPU、主板温度等）需求的讨论，统一汇总到该 issue #1614
