### ISSUE TITLE
[QUESTION] 是否有人遇过大概隔十几个小时，mysql会让磁盘IO读取100%，导致服务器崩了

### ISSUE THREAD

**Issue by seepine** [1Panel-dev/1Panel#3137]
### 请描述您的问题

- ubuntu22
- 1panel 1.8.5
- mysql: 8.2.0

之前服务器使用直装mysql8，没有遇过这种情况，是否是docker装的mysql有问题

![image](https://github.com/1Panel-dev/1Panel/assets/93666053/906df3d4-32e5-4e21-8453-05b2bffdbd56)

**Comment by wanghe-fit2cloud** [comment]
可能是因为 MySQL 日志在每次事务提交时，都会将其写入并刷新到磁盘，造成磁盘 IO 的高占用。
> 可以尝试修改一下 sync_binlog、innodb_flush_log_at_trx_commit 等默认配置（可参考 MySQL 官方文档）。
