### ISSUE TITLE
[BUG] CPU 占用率突然飙升到 100%

### ISSUE THREAD

**Issue by Liruwei** [1Panel-dev/1Panel#314]
### 1Panel 版本

1.0.2

### 问题描述

![image](https://user-images.githubusercontent.com/12146035/226264019-64ada34c-f89d-4a25-b98a-4a36058ac299.png)

突然 CPU 占用 100%，可有解决办法？

### 重现步骤

暂无

**Comment by zhengkunwang223** [comment]
看下安装目录下 log 文件下下面的日志文件
