### ISSUE TITLE
[BUG] 安装了mysql后，无法访问3306端口

### ISSUE THREAD

**Issue by chennest** [1Panel-dev/1Panel#3140]
### 联系方式

517024110@qq.com

### 1Panel 版本

v1.8.5

### 问题描述

在应用商店安装了mysql5.7并且打开了外网访问，但是外网无法访问，使用telnet无法ping通 3306端口，主机的防火墙关闭了，系统为centos7

### 重现步骤

在应用商店安装了mysql5.7并且打开了外网访问

**Comment by wanghe-fit2cloud** [comment]
进入 `容器` 页面，可查看 MySQL 容器状态和日志。

**Comment by wanghe-fit2cloud** [comment]
先关闭该 Issue 了，如果有问题再继续讨论。
> 本地未能复现上述问题。
