### ISSUE TITLE
[FEATURE] 反向代理二级路径

### ISSUE THREAD

**Issue by MrArlong** [1Panel-dev/1Panel#3141]
### 1Panel 版本

1.8.5

### 请描述您的需求或者改进建议

我想问一下，我们现在支持二级路径吗，我有一个需求就是我想一个域名通过路径来跳转不同的项目
例如：https://www.baidu.com  这是我的域名，我反向代理的时候我想在后面加路径来跳转1panel，https://www.baidu.com/1panel，然后我想后面加halo跳转halo首页https://www.baidu.com/halo，
目前前端路径只能配置根路径才能正常访问这些项目，所以现在只能通过创建两个网站来进行反向代理，我多个项目就得创建多个了，就感觉有些许的麻烦了，不知道是不是我配置错误，还是我们目前暂时还不支持这样

**Comment by wanghe-fit2cloud** [comment]
1Panel 当前还不支持，后续版本可能会考虑支持。

二级路径，这个主要看程序是否支持了。
某UI支持二级路径，他有校验，后台设置路径例如/path233/
反向代理原始路径就写ip:端口，然后/path233/

**Comment by wanghe-fit2cloud** [comment]
网站二级域名相关功能的讨论，统一汇总到该 issue #2336
