### ISSUE TITLE
[QUESTION]如何让容器的 IP 地址在重启后不发生变动？

### ISSUE THREAD

**Issue by ShangJixin** [1Panel-dev/1Panel#3143]
### 请描述您的问题

目前所有容器都被分配到了`172.18.0.x`的段，比如说我某个服务的 IP 为`172.18.0.1`，服务器重启后，会变成`.2`或`.3`或其他 IP 地址。造成 Nginx 如果想反代这个服务，服务器一重启，IP 一变，Nginx 那边就 502 了。127 试验过了，不能用，用 127 之后，Nginx 报 502。即便是设置成如下图所示的，也没法用 127+端口 的形式来反代这个服务。
![image](https://github.com/1Panel-dev/1Panel/assets/21075413/4e382388-ccfd-4bcb-8a35-d6fe01af40b2)
不知是我哪里操作有误，还是 1Panel 没有静态 IP 的相关方案，希望可以解决这个问题

**Comment by ShangJixin** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/21075413/9a8be90a-df43-4076-882e-e5f23545ff0e)
补充一下，用127，就是会502

**Comment by LBC000** [comment]
同问！！！目的是宿主机用容器的mysql服务
