### ISSUE TITLE
对Rocky Linux的支持

### ISSUE THREAD

**Issue by LReion** [1Panel-dev/1Panel#3145]
### 1Panel 版本

v1.8.5

### 请描述您的需求或者改进建议

因为CentOS结束支持之后准备转向Rocky Linux，但是安装面板的时候发现没有Rocky的Docker

**Comment by wanghe-fit2cloud** [comment]
1Panel 采用的是 docker 官方提供的在线安装脚本来初始化安装的 docker。
> 对于不支持的操作系统都需要手动安装好 docker 后再来运行 1Panel 的在线安装脚本。

安装 docker，可以参考操作系统其官网提供的解决方案，也可以尝试使用下面的安装脚本：
```shell
bash <(curl -sSL https://linuxmirrors.cn/docker.sh)
```

**Comment by LReion** [comment]
> 1Panel 采用的是 docker 官方提供的在线安装脚本来初始化安装的 docker。
> 
> > 对于不支持的操作系统都需要手动安装好 docker 后再来运行 1Panel 的在线安装脚本。
> 
> 安装 docker，可以参考操作系统其官网提供的解决方案，也可以尝试使用下面的安装脚本：
> 
> ```shell
> bash <(curl -sSL https://linuxmirrors.cn/docker.sh)
> ```

OK，谢谢！
