### ISSUE TITLE
[FEATURE]增加直链 / 外链分享

### ISSUE THREAD

**Issue by YangHaoNing-CN** [1Panel-dev/1Panel#3146]
### 1Panel 版本

v1.8.5

### 请描述您的需求或者改进建议

文件中增加直链 / 外链分享，可以直接在下载器下载

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑是否支持上述需求。

**Comment by ayanami-desu** [comment]
同样需要上述需求

**Comment by BlueNoob** [comment]
不建议上述需求，容易产生安全隐患。

**Comment by sanfang0766** [comment]
这功能最好是自己通过 Nginx 实现，不应该要面板来做。
