### ISSUE TITLE
[FEATURE] 菜单的建议

### ISSUE THREAD

**Issue by soonxf** [1Panel-dev/1Panel#3148]
### 1Panel 版本

1.8.5

### 请描述您的需求或者改进建议

菜单做成可配置就好了,比较难的话可以做成可以配置成隐藏现实的,宝塔都有了是吧哈哈哈

### 请描述你建议的实现方案

无

### 附加信息

无

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复 #696
