### ISSUE TITLE
[FEATURE] 文件管理器

### ISSUE THREAD

**Issue by soonxf** [1Panel-dev/1Panel#3150]
### 1Panel 版本

1.8.5

### 请描述您的需求或者改进建议

希望可以像宝塔一样,在文件管理界面拖拽直接然后询问是否确定上传,然后就直接上传

文件管理界面鼠标右击增加一些常用管理文件菜单选项,复制粘贴删除这些就好了,这样比在顶部点击会方便很多的

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们可能会在 2.x 大版本重构时考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
经讨论，我们暂无支持上述两点建议的计划，望理解。
