### ISSUE TITLE
[FEATURE]关于HSTS

### ISSUE THREAD

**Issue by Kagura-Nanaa** [1Panel-dev/1Panel#3152]
### 1Panel 版本

v1.8.5

### 请描述您的需求或者改进建议

希望可以在网站配置页面中加入一个开启HSTS的开关，免去修改配置文件的麻烦

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
