### ISSUE TITLE
[FEATURE]顶部能否增加标签页

### ISSUE THREAD

**Issue by yyf127** [1Panel-dev/1Panel#3154]
### 1Panel 版本

v1.8.2

### 请描述您的需求或者改进建议

顶部增加标签，不然有时候要网站要文件修改，跳来跳去的，标签省去很多麻烦
![无标题](https://github.com/1Panel-dev/1Panel/assets/66797877/8d357fbc-6bfd-446c-b725-db59bdb2873d)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，中短期内应该不会考虑上述需求，望理解。
