### ISSUE TITLE
[BUG]php5 替换sed 版本错误 导致mirrors 失败

### ISSUE THREAD

**Issue by MCapricorns** [1Panel-dev/1Panel#3155]
### 1Panel 版本

1.8.5

### 问题描述

[1panel-php  2/12] RUN if [ "mirrors.163.com" ]; then sed -i "s|http://dl-cdn.alpinelinux.org/alpine/v3.4|https://mirrors.163.com/alpine/v3.12|g" /etc/apk/repositories; fi

但是下面提示 fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz

3.8 ！=3.4

所以导致替换失败

### 重现步骤

![1701610197203](https://github.com/1Panel-dev/1Panel/assets/22653841/f57212fc-d651-40d6-9857-f79a8aa3630d)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们现在本地环境复现一下上述问题。

**Comment by zhengkunwang223** [comment]
试了一下 没有报错

**Comment by MCapricorns** [comment]
> 试了一下 没有报错

不是报错，是替换失败，导致 mirrors 失效，继续从原地址下，速度很慢。

**Comment by zhengkunwang223** [comment]
> > 试了一下 没有报错
> 
> 不是报错，是替换失败，导致 mirrors 失效，继续从原地址下，速度很慢。

什么 PHP 版本？

**Comment by wanghe-fit2cloud** [comment]
可以尝试进入 `应用商店` 列表点击右上角的 `更新应用列表` 按钮，等待同步成功之后再来创建 PHP 对应版本的运行环境，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/3dc475b1-9c41-4e6c-a17b-8251e7e9e176)

> 本地环境测试的 PHP 版本为：`v5.5.38`，扩展源为：`中国科学技术大学`，未复现上述问题。
163 源安装某些软件会失败。

如果更新后依然存在问题，再继续讨论。
