### ISSUE TITLE
[FEATURE]希望能支持给每个应用添加不同的域名，而非域名加端口的形式。

### ISSUE THREAD

**Issue by Bigzzh2022** [1Panel-dev/1Panel#3156]
### 1Panel 版本

v1.8.5

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/124849169/8944af5f-2397-4be6-a53e-b5a25056d926)
![image](https://github.com/1Panel-dev/1Panel/assets/124849169/6fb4ed3c-8371-49f5-9116-828a9848b11d)
**希望能支持给每个应用添加不同的域名，而非域名加端口的形式**
eg：
- [x] gpt 使用 gpt.bigzzh.top
- [x] kuma 使用 cctv.bigzzh.top

**Comment by wanghe-fit2cloud** [comment]
当前版本可以通过创建反向代理网站的方式来实现上述需求。
> 后续版本我们会考虑上述建议，作出相应的优化。

**Comment by danger-dream** [comment]
> 当前版本可以通过创建反向代理网站的方式来实现上述需求。
> 
> > 后续版本我们会考虑上述建议，作出相应的优化。

创建反向代理网站没有直达功能，不方便

**Comment by wanghe-fit2cloud** [comment]
接下来会支持创建网站时直接选择应用或者容器 #2930
