### ISSUE TITLE
[FEATURE]关于防火墙iptables的需求

### ISSUE THREAD

**Issue by aki66938** [1Panel-dev/1Panel#3157]
### 1Panel 版本

v1.8.5

### 请描述您的需求或者改进建议

能否支持一下iptables。有将流量细分到用户的需求，firewall和ufw都做不到。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们可能会在 2.0 大版本重构时考虑上述续期。

**Comment by wanghe-fit2cloud** [comment]
支持 iptables 相关功能的讨论，统一汇总到该 issue #2238
