### ISSUE TITLE
在【应用商店】中，安装的应用默认没有 IPv6 支持

### ISSUE THREAD

**Issue by fayfoxcat** [1Panel-dev/1Panel#3159]
### 联系方式

fayfoxcat@gmail.com

### 1Panel 版本

1.8.5

### 问题描述

在【应用商店】中，安装的应用默认都没有ipv6支持，即没有办法通过ipv6访问应用，我试图在创建应用时候修改【高级设置】-【编写compose配置】中修改配置文件部分为
`ports：
     -  40021:3002
`
当我保存时候完成应用启动成功，点击参数去看compose文件时候，发现我修改的配置变成了
`ports：
     -  ${HOST_IP}:40021:3002
`
这意味docker端口映射为ipv4的地址，我使用命令创建了同一个服务，在终端中通过`docker ps`命令查看的对比，实际上是猜测的结果一致，【应用商店】直接按照的服务不支持ipv6，且手动修改无效，如图
![image](https://github.com/1Panel-dev/1Panel/assets/54295055/0df5d059-3076-42fd-863b-04f8e6013af9)
![image](https://github.com/1Panel-dev/1Panel/assets/54295055/101fe1c0-4bdc-4b33-8f68-98683bac23bd)

### 重现步骤

【应用商店】安装应用，无法ipv6访问，【高级设置】-【编写compose配置】中修改配置文件无法生效

### 期待的正确结果

修改配置文件生效，或者默认生成的配置文件不指定宿主机ip以提供默认ipv6访问的支持

**Comment by wanghe-fit2cloud** [comment]
当前版本中，对外暴露端口默认绑定的是 IPv4 地址：0.0.0.0，可以进入应用安装目录，修改 .env 文件，将 HOST_IP 修改为空。
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/b0c23c09-9215-4617-9485-e231f07c59f3)
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/391653da-0dfc-49e4-9357-1a894c19a7bb)

> 下周发布的 v1.9.0 版本将支持。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。

**Comment by everett7623** [comment]
我最近测试应该还没解决这个问题吧

**Comment by wanghe-fit2cloud** [comment]
> 我最近测试应该还没解决这个问题吧

需要容器网络正常 IPv6，此时创建的应用会默认监听 IPv4 + IPv6

**Comment by everett7623** [comment]
那里最好搞个大的设置，默认ipv6，毕竟v6的机器，获取的warp v4基本没用的

**Comment by wanghe-fit2cloud** [comment]
> 那里最好搞个大的设置，默认ipv6，毕竟v6的机器，获取的warp v4基本没用的

应用默认就是监听 IPv4 + IPv6，是容器网络需要修改为都支持。

**Comment by everett7623** [comment]
文档的教程还是未能成功搞定

**Comment by wanghe-fit2cloud** [comment]
> 文档的教程还是未能成功搞定

就是要在 `容器` - `网络` 页面，删除 1panel-network 这个默认的容器网络，再次创建时同时指定 IPv4 和 IPv6 参数。
在安装应用时，不需要有任何改动，直接创建。

> 在 docker 官方看一下 IPv6 相关容器教程。

**Comment by everett7623** [comment]
是的，但v4，v6地址新建的不知道是填的不对，还是哪里有问题，依旧不行，后续再试试吧
