### ISSUE TITLE
[FEATURE]应用商店插件化

### ISSUE THREAD

**Issue by guclan** [1Panel-dev/1Panel#316]
### 1Panel 版本

v1.0.2

### 请描述您的需求或者改进建议

改进应用商店，可以让用户自行开发应用并上传至系统内的应用商店。提供统一的驱动化接口接入。

**Comment by zhengkunwang223** [comment]
感谢建议，我们讨论一下这个

**Comment by yyn0210** [comment]
+1

**Comment by guclan** [comment]
[如何提交自己想要的应用](https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8)

该功能已实现，此issue关闭
