### ISSUE TITLE
[QUESTION] 一键部署 WordPress 出现静态资源无法访问

### ISSUE THREAD

**Issue by liqingsong2013** [1Panel-dev/1Panel#3167]
### 请描述您的问题

1、一键部署 WordPress 成功
2、通过 80、443 端口访问 OpenResty 时，遇到访问静态资源   **xxx.css?v=6.1** 这种，直接出现 **404**，直接请求   **xxx.css** 就没问题
3、通过端口直接访问容器，不通过 OpenResty 一切正常

是我配置有问题？一键部署不需要有啥配置吧！

我也无法通过配置反代的方式访问容器，也是同样的问题。

**Comment by zhengkunwang223** [comment]
> ### 请描述您的问题
> 1、一键部署 WordPress 成功 2、通过 80、443 端口访问 OpenResty 时，遇到访问静态资源 **xxx.css?v=6.1** 这种，直接出现 **404**，直接请求 **xxx.css** 就没问题 3、通过端口直接访问容器，不通过 OpenResty 一切正常
> 
> 是我配置有问题？一键部署不需要有啥配置吧！
> 
> 我也无法通过配置反代的方式访问容器，也是同样的问题。

尝试关闭伪静态，关闭防盗链
