### ISSUE TITLE
[FEATURE]面板名称增加长度限制

### ISSUE THREAD

**Issue by hsjgit** [1Panel-dev/1Panel#3174]
### 1Panel 版本

 Versionv1.8.5-alpha.1

### 问题描述

更新面板设置的时候没有数据大小限制，比如跟新更新面板名字我可以传入很长的一段字符串

### 重现步骤

更新面板设置

**Comment by zhengkunwang223** [comment]
感谢反馈 我们后续版本会优化此处

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
