### ISSUE TITLE
[FEATURE]备份加密

### ISSUE THREAD

**Issue by lzq2357** [1Panel-dev/1Panel#3177]
### 1Panel 版本

v1.8.5

### 请描述您的需求或者改进建议

是否考虑支持加密备份

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，请问是要将网站、数据库等备份文件以某种加密方式加密后再上传到第三方备份账号吗？

**Comment by ssongliu** [comment]
重复 #2855
