### ISSUE TITLE
[BUG] 选择快速指令后立刻发送至终端不够灵活

### ISSUE THREAD

**Issue by aki66938** [1Panel-dev/1Panel#3178]
### 1Panel 版本

v1.8.5

### 问题描述

在运维人员使用过程中，常常用到一些发包抓包命令比如ping、telnet、nc、curl、tcpdump等等，但快速命令点击后直接发送到终端，无法对输入ip。如果要ping测试多个远程主机，需要定义多个快速命令。那整个列表都是ping命令，再塞下其他命令，查找起来也很费劲。
ping命令字符和参数都相对较少，运维手输也不费劲，或许不具备参考性。但如果是使用频率相对较低的tcpdump命令，并且假设当前服务器存在多个网卡的情况下，要存储多个设置了不同参数的抓包命令。更甚至需要指定源地址，比如较为特殊应用场景的命令：
`tcpdump -i eth0 -n host 192.168.1.1 and port 8080 -tttt -w output.pcap`
这种情况下快速指令的功能就显得不够灵活。

同样的还有查看iptables规则、查看用户uid之类的命令：
`cat /etc/passwd | grep abc`
获得用户abc的uid（假设1001）后要查看iptables的规则
`iptables -L -n  | grep 1001`

还有诸如使用了复杂度较高的awk指令需求文本名称灵活可输入。
当前的快速指令选择即执行的方式灵活度较低

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/47413858/fa215d81-6d27-4ce2-9ef7-746fbd96a46d)
当选择快速指令，终端会立即执行

### 期待的正确结果

用户选择快速指令后该命令会发送到控制台但不会立刻回车执行，给用户保留修改空间

**Comment by aki66938** [comment]
另外借自己楼提个需求，终端页面如果能设置个开关就好了。
理由是在大项目中，开发和运维往往是分开的，出于某些原因（已有jumpserver堡垒机可用），ssh、终端这些功能运维如果不想放权给开发，可以设置关闭功能，或者设置开启需要密码之类的。提供一个权限窗口

**Comment by wanghe-fit2cloud** [comment]
> 用户选择快速指令后该命令会发送到控制台但不会立刻回车执行，给用户保留修改空间

理解你的意思，但是这个需求我们中短期内应该不会支持，望理解。

**Comment by wanghe-fit2cloud** [comment]
> 可以设置关闭功能，或者设置开启需要密码之类的。提供一个权限窗口

是的，JumpServer 和 1Panel 的不同点在于，1Panel 没有设计用户权限体系（单用户）。
> 2.x 大版本重构时可能会考虑。
