### ISSUE TITLE
使用docker stack deploy 创建的应用    暴露的端口没显示，只显示了容器里的80端口  [BUG]

### ISSUE THREAD

**Issue by ByZhouhang** [1Panel-dev/1Panel#3179]
### 联系方式

17673237815

### 1Panel 版本

1.8.3

### 问题描述

单机，我想实现无感发布，所以使用了 docker swarm ,然后docker stack deploy 创建应用的时候，在1panle 容器哪里 没有显示暴露的端口，不是很方便，每次都得去看配置文件。

### 重现步骤

# 部署
docker stack deploy -c docker-stake.yml myapp
# 部署情况
docker stack ps myapp

然后去容器界面看

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/43258053/4c76c7ce-f890-4c34-909d-696f073a7905)

**Comment by wanghe-fit2cloud** [comment]
1Panel 当前版本暂不支持 docker swarm，后续版本可能会考虑。
