### ISSUE TITLE
[BUG] 容器中删除mysql后，无法重新安装同名的数据库，并且3306端口也提示被占用

### ISSUE THREAD

**Issue by yinyajiang** [1Panel-dev/1Panel#3183]
### 1Panel 版本

v1.8.5

### 问题描述

在容器中删除mysql容器后，在数据库中还能看见，但是无法删除，无法启动，也无法重新安装同名的数据库，并且3306端口也提示被占用
![20231205121527](https://github.com/1Panel-dev/1Panel/assets/32933356/6455b5a4-e39d-409e-bfe2-df08687e8c7c)
![20231205121735](https://github.com/1Panel-dev/1Panel/assets/32933356/702e9564-01de-4e16-b178-b6e789b221fe)
![20231205121618](https://github.com/1Panel-dev/1Panel/assets/32933356/350a0a98-e974-4cc3-8a0f-03fda52fe712)

### 重现步骤

1. 在容器中删除mysql容器
2. 重新安装同名的数据库会失败

**Comment by zhengkunwang223** [comment]
简单来说 就是从哪里安装的 就要从哪里删除
mysql 是从应用商店安装的 就需要去应用商店删除
我们的应用都是用 docker-compose 管理的，容器删掉也能重建
