### ISSUE TITLE
[BUG]使用1Panel升级Halo无法正常启动

### ISSUE THREAD

**Issue by youngledo** [1Panel-dev/1Panel#3184]
### 1Panel 版本

v1.8.5

### 问题描述

在1Panel上升级halo过程正常没有报错，但halo启动后控制台出现异常。原因是缺少环境变量，详见：https://bbs.halo.run/d/4362-%E9%80%9A%E8%BF%871panel%E5%8D%87%E7%BA%A7280--291%E5%90%8E%E5%90%AF%E5%8A%A8%E5%A4%B1%E8%B4%A5/2

### 重现步骤

安装相对低版本的halo，然后升级到最新版本即可复现。

**Comment by wanghe-fit2cloud** [comment]
是的，我们在 1Panel 的中间版本修改过一次 docker-compose 参数。如果是升级上来的 Halo 就需要手动修改一下 .env 文件。

**Comment by youngledo** [comment]
> 是的，我们在 1Panel 的中间版本修改过一次 docker-compose 参数。如果是升级上来的 Halo 就需要手动修改一下 .env 文件。

意思是后续每次都需要手动修改吗，不能兼容处理下。

**Comment by wanghe-fit2cloud** [comment]
> > 是的，我们在 1Panel 的中间版本修改过一次 docker-compose 参数。如果是升级上来的 Halo 就需要手动修改一下 .env 文件。
> 
> 意思是后续每次都需要手动修改吗，不能兼容处理下。

低版本升级才会出现这个问题，手动修改 .env 文件后不需要再次修改。
