### ISSUE TITLE
[FEATURE]希望申请证书时可以选择加密算法

### ISSUE THREAD

**Issue by lainbo** [1Panel-dev/1Panel#3190]
### 1Panel 版本

1.8.5

### 请描述您的需求或者改进建议

在面板中创建证书时，希望可以增加一个证书加密算法的选项，选择申请RSA / ECC

### 请描述你建议的实现方案

我注意到我们使用Let's Encrypt注册证书，他们已经支持了ECC证书的申请，或许我们可以增加一个选项，做到通过1Panel来申请Let's Encrypt的ECC的证书

### 附加信息

Now Supporting ECC for Let's Encrypt Certificates - DNSimple Blog
https://blog.dnsimple.com/2022/12/ecc-support-for-letsencrypt-certificates/

**Comment by zhengkunwang223** [comment]
v1.9.0 支持

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
