### ISSUE TITLE
[BUG]openresty反代minio之后，halo附件上传报错

### ISSUE THREAD

**Issue by cyril-cheng** [1Panel-dev/1Panel#3192]
### 1Panel 版本

1.8.5

### 问题描述

openresty反代minio，在halo的s3插件上传附件会显示内部错误，上传失败。
具体问题请看：
https://github.com/halo-dev/plugin-s3/issues/99
里面有3个案例，都是使用1panel的openresty反代minio报错的。

### 重现步骤

使用openresty反代minio。

**Comment by wanghe-fit2cloud** [comment]
MinIO 官方有提供针对反向代理配置的说明，建议参考后手动修改：
https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html

**Comment by cyril-cheng** [comment]
官方配置有用，我都不提了。。。。

**Comment by fghwett** [comment]
我是有类似的问题，nginx的proxy_cache导致minio的某些接口走了缓存，以至于访问失败，在反向代理中加上`proxy_cache off`就可以了。
