### ISSUE TITLE
[QUESTION] 申请并导入了基于 IP 的 SSL 证书，搭建静态网站无法启用 https

### ISSUE THREAD

**Issue by nobodysclown** [1Panel-dev/1Panel#3194]
### 请描述您的问题

管理面板已经正常开启了https。但是用相同的`http://ip:80` 搭建了一个静态网站无法正常使用证书。

`http://ip:80` 正常访问，网站设置-基本-HTTPS 开启之后，网站自动跳转到 `https://ip`

提示：此网站无法提供安全连接发送的响应无效。ERR_SSL_PROTOCOL_ERROR

请问如何配置？

**Comment by zhengkunwang223** [comment]
把你的 IP 网站设置为默认网站
