### ISSUE TITLE
[FEATURE] 关于面板升级界面的更新日志

### ISSUE THREAD

**Issue by suiyueou** [1Panel-dev/1Panel#3196]
### 1Panel 版本

v1.8.5

### 请描述您的需求或者改进建议

目前, 面板上的升级界面只会显示最新版的更新日志, 不会显示最新版与当前版本之间的所有更新日志, 无法直观的了解新老版本间的具体更新情况.

### 请描述你建议的实现方案

希望可以优化升级界面中的更新日志展示, 可以显示新版本与当前版本之间的所有版本的更新日志.

**Comment by wanghe-fit2cloud** [comment]
全部更新日志可参考 [GItHub releases](https://github.com/1Panel-dev/1Panel/releases) 或者 [官方文档版本迭代说明](https://1panel.cn/docs/changelog/)

**Comment by suiyueou** [comment]
> 全部更新日志可参考 [GItHub releases](https://github.com/1Panel-dev/1Panel/releases) 或者 [官方文档版本迭代说明](https://1panel.cn/docs/changelog/)

我知道可以前往这两个地方进行查看，但是如果可以在升级的界面上直接查看新老版本更新历史可以更加方便（
