### ISSUE TITLE
希望可以增加一个在证书自动续签后执行脚本的功能

### ISSUE THREAD

**Issue by EasierLu** [1Panel-dev/1Panel#3197]
### 1Panel 版本

1.8.5

### 请描述您的需求或者改进建议

希望可以增加一个在证书自动续签后执行脚本的功能，这样在其他需要证书的应用中也能自动部署，比如Maddy Mail Server

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
