### ISSUE TITLE
[BUG]docker容器无法查看日志

### ISSUE THREAD

**Issue by XCWQW1** [1Panel-dev/1Panel#3198]
### 联系方式

xchome233@gmail.com

### 1Panel 版本

v1.8.5

### 问题描述

在 应用商店>已安装 中查看应用容器日志，日志内容是
```
View output from containers.

Usage: logs [options] [--] [SERVICE...]

Options:
    --no-color              Produce monochrome output.
    -f, --follow            Follow log output.
    -t, --timestamps        Show timestamps.
    --tail="all"            Number of lines to show from the end of the logs
                            for each container.
    --no-log-prefix         Don't print prefix in logs.
```

### 重现步骤

在 应用商店>已安装 中点击查看应用容器日志

**Comment by wanghe-fit2cloud** [comment]
进入 `主机` - `终端`，通过 `docker-compose version` 命令查看一下 compose 版本。

**Comment by XCWQW1** [comment]
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.12
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022

**Comment by wanghe-fit2cloud** [comment]
将 `docker-compose` 版本手动升级到最新版本。
> 建议是 >= v2.16.0
