### ISSUE TITLE
[BUG]应用商店安装mysql设置密码时，特殊字符不能在首尾 

### ISSUE THREAD

**Issue by waves86** [1Panel-dev/1Panel#3199]
### 1Panel 版本

1.8.5

### 问题描述

应用商店安装mysql设置密码时，特殊字符不能在首尾 

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/45849273/c6f69a8e-da35-4eb1-80ff-cd4c25c13ac6)

### 期待的正确结果

能够通过

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，这里主要是为了兼容系统和应用商店中其他应用的密码校验规则。
