### ISSUE TITLE
[FEATURE]希望能够可以连接一些其他的数据库

### ISSUE THREAD

**Issue by litianyu-abc** [1Panel-dev/1Panel#320]
### 1Panel 版本

v1.0.2

### 请描述您的需求或者改进建议

1、希望可以增加一些其他的数据库，如：时序数据库(iotdb),oracle等
2、希望增加可以连接外接数据库，如：可以连接其他服务器上安装的数据库进行管理、监控、备份等

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1、可以将您常用的数据库应用反馈到 [应用商店](https://github.com/1Panel-dev/1Panel/issues/250) 的需求中；
2、后续版本我们可能会支持添加远程数据库的功能。

**Comment by wanghe-fit2cloud** [comment]
最新版本已支持管理 MariaDB 数据库和添加远程 MySQL 数据库。
> 后续版本会优先考虑 PostgreSQL 数据库
