### ISSUE TITLE
无法添加cloudflare r2

### ISSUE THREAD

**Issue by maskgo68** [1Panel-dev/1Panel#3201]
### 1Panel 版本

1.8.5

### 问题描述

1panel备份方式中添加cloudflare r2对象存储时，点击“获取桶”会报错:
`服务内部错误: AccessDenied: Access Denied status code: 403, request id: , host id:`
请问如何解决？是我的配置有问题吗？但在alist上测试是成功的
![R2错误](https://github.com/1Panel-dev/1Panel/assets/146368179/55561e39-586d-4cbe-94ed-d5f10c49484c)

### 重现步骤

1panel备份方式中添加cloudflare r2对象存储

**Comment by maskgo68** [comment]
如果将endpoint补全（包含Bucket名称），虽然不报错，但点击“获取桶”之后无法选择bucket，还是无法使用
![image](https://github.com/1Panel-dev/1Panel/assets/146368179/534d8b32-31ae-453d-b214-78cf9595d0c6)

**Comment by ssongliu** [comment]
感谢反馈，这里 Endpoint 的输入方式第一种是正确的，403 的错误可以检查一下 Cloudflare r2 权限以及桶的配置（是否开启CORS ）等。

**Comment by maskgo68** [comment]
感谢。解决了，创建r2 api时要选择“Admin Read & Write”权限
https://community.cloudflare.com/t/r2-token-permissions-not-working-right/550735
