### ISSUE TITLE
[FEATURE] 增加收录O2OA 开源OA系统

### ISSUE THREAD

**Issue by BlueNoob** [1Panel-dev/1Panel#3209]
### 1Panel 版本

*

### 请描述您的需求或者改进建议

增加收录O2OA 开源OA系统
https://www.o2oa.net/download.html
![image](https://github.com/1Panel-dev/1Panel/assets/4169222/fd120db2-15c5-4eab-98ae-db10f1d64580)

**Comment by zhengkunwang223** [comment]
感谢建议 我们看一下

**Comment by maninhill** [comment]
暂时不考虑，感谢推荐。

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I won’t consider it for now, thanks for the recommendation.
