### ISSUE TITLE
[QUESTION]主机 密钥登录不可用

### ISSUE THREAD

**Issue by lujay** [1Panel-dev/1Panel#321]
### 请描述您的问题

不确定是不是我操作问题， 输入 公钥无法连接，
![image](https://user-images.githubusercontent.com/6263244/226292964-62da4730-f04a-445a-b674-2449e1a4de18.png)

**Comment by ossplus** [comment]
遇到相同问题；
你的私钥是带密码的么？
我重设了一个不密码的私钥，就成功了。

**Comment by wanghe-fit2cloud** [comment]
> 遇到相同问题； 你的私钥是带密码的么？ 我重设了一个不密码的私钥，就成功了。

后续版本我们会支持用户输入私钥密码。

**Comment by wanghe-fit2cloud** [comment]
v1.1.0 版本已发布，支持输入私钥密码。
