### ISSUE TITLE
[BUG]反向代理报错只要包含路径/**就报错

### ISSUE THREAD

**Issue by hasspi88** [1Panel-dev/1Panel#3210]
### 1Panel 版本

v1.8.5

### 问题描述

location = /test {
    proxy_pass http://192.168.10.160:6052; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header Cache-Control no-cache; 
}

### 重现步骤

404

### 相关日志输出

```shell
404
```

**Comment by hasspi88** [comment]
2023/12/07 02:05:34 [error] 263#263: *101 open() "/usr/local/openresty/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.10.52, server: 192.168.10.160, request: "GET /favicon.ico HTTP/1.1", host: "192.168.10.160", referrer: "http://192.168.10.160/esphome/"
2023/12/07 02:08:59 [error] 297#297: *108 open() "/usr/local/openresty/nginx/html/static/fonts/material-icons/material-icons.css" failed (2: No such file or directory), client: 192.168.10.52, server: 192.168.10.160, request: "GET /static/fonts/material-icons/material-icons.css?hash=ead4c276 HTTP/1.1", host: "192.168.10.160", referrer: "http://192.168.10.160/"
2023/12/07 02:08:59 [error] 297#297: *110 open() "/usr/local/openresty/nginx/html/static/fonts/material-icons/MaterialIcons-Regular.woff2" failed (2: No such file or directory), client: 192.168.10.52, server: 192.168.10.160, request: "GET /static/fonts/material-icons/MaterialIcons-Regular.woff2?hash=570eb838 HTTP/1.1", host: "192.168.10.160", referrer: "http://192.168.10.160/"
2023/12/07 02:08:59 [error] 297#297: *108 open() "/usr/local/openresty/nginx/html/static/css/esphome-2.css" failed (2: No such file or directory), client: 192.168.10.52, server: 192.168.10.160, request: "GET /static/css/esphome-2.css?hash=c222cb3b HTTP/1.1", host: "192.168.10.160", referrer: "http://192.168.10.160/"
2023/12/07 02:08:59 [error] 297#297: *111 open() "/usr/local/openresty/nginx/html/static/js/esphome/index-6rBAfUo5.js" failed (2: No such file or directory), client: 192.168.10.52, server: 192.168.10.160, request: "GET /static/js/esphome/index-6rBAfUo5.js HTTP/1.1", host: "192.168.10.160", referrer: "http://192.168.10.160/"
2023/12/07 02:08:59 [error] 297#297: *111 open() "/usr/local/openresty/nginx/html/static/images/favicon.ico" failed (2: No such file or directory), client: 192.168.10.52, server: 192.168.10.160, request: "GET /static/images/favicon.ico?hash=2655a073 HTTP/1.1", host: "192.168.10.160", referrer: "http://192.168.10.160/"
2023/12/07 02:09:04 [error] 297#297: *111 open() "/usr/local/openresty/nginx/html/static/fonts/material-icons/material-icons.css" failed (2: No such file or directory), client: 192.168.10.52, server: 192.168.10.160, request: "GET /static/fonts/material-icons/material-icons.css?hash=ead4c276 HTTP/1.1", host: "192.168.10.160", referrer: "http://192.168.10.160/"
2023/12/07 02:09:04 [error] 297#297: *108 open() "/usr/local/openresty/nginx/html/static/fonts/material-icons/MaterialIcons-Regular.woff2" failed (2: No such file or directory), client: 192.168.10.52, server: 192.168.10.160, request: "GET /static/fonts/material-icons/MaterialIcons-Regular.woff2?hash=570eb838 HTTP/1.1", host: "192.168.10.160", referrer: "http://192.168.10.160/"
2023/12/07 02:09:04 [error] 297#297: *110 open() "/usr/local/openresty/nginx/html/static/css/esphome-2.css" failed (2: No such file or directory), client: 192.168.10.52, server: 192.168.10.160, request: "GET /static/css/esphome-2.css?hash=c222cb3b HTTP/1.1", host: "192.168.10.160", referrer: "http://192.168.10.160/"
2023/12/07 02:09:04 [error] 298#298: *112 open() "/usr/local/openresty/nginx/html/static/js/esphome/index-6rBAfUo5.js" failed (2: No such file or directory), client: 192.168.10.52, server: 192.168.10.160, request: "GET /static/js/esphome/index-6rBAfUo5.js HTTP/1.1", host: "192.168.10.160", referrer: "http://192.168.10.160/"
2023/12/07 02:09:13 [error] 298#298: *112 open() "/usr/local/openresty/nginx/html/essphome" failed (2: No such file or directory), client: 192.168.10.52, server: 192.168.10.160, request: "GET /essphome HTTP/1.1", host: "192.168.10.160"
2023/12/07 02:09:16 [error] 298#298: *112 open() "/usr/local/openresty/nginx/html/essphome" failed (2: No such file or directory), client: 192.168.10.52, server: 192.168.10.160, request: "GET /essphome HTTP/1.1", host: "192.168.10.160"

**Comment by zhengkunwang223** [comment]
> ### 联系方式
> _No response_
> 
> ### 1Panel 版本
> v1.8.5
> 
> ### 问题描述
> location = /test { proxy_pass http://192.168.10.160:6052; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header REMOTE-HOST $remote_addr; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; proxy_set_header X-Forwarded-Proto $scheme; proxy_http_version 1.1; add_header Cache-Control no-cache; }
> 
> ### 重现步骤
> 404
> 
> ### 期待的正确结果
> _No response_
> 
> ### 相关日志输出
> ```shell
> 404
> ```
> 
> ### 附加信息
> _No response_

你的后端不支持 /** 反代，只支持 /

**Comment by hasspi88** [comment]
如何修改？我装宝塔的时候都支持？

**Comment by hasspi88** [comment]
> > ### 联系方式
> > _没有回应_
> > ### 1Panel 版本
> > 1.8.5 版
> > ### 问题描述
> > location = /test { proxy_pass http://192.168.10.160:6052; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header REMOTE-HOST $remote_addr; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection “upgrade”; proxy_set_header X-Forwarded-Proto $scheme; proxy_http_version 1.1; add_header Cache-Control no-cache; }
> > ### 重现步骤
> > 404
> > ### 期待的正确结果
> > _没有回应_
> > ### 相关日志输出
> > ```shell
> > 404
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 附加信息
> > _没有回应_
> 
> 你的后端不支持 /** 反代，只支持 /

？如何使后端支持，我是一键安装的

**Comment by chenlei9907** [comment]
我也有同样的问题， 之前用宝塔都没事。 后端是Django。本来应该用OpenResty 处理静态文件，但是一直有问题，只能把静态文件让Django 处理。后台始终报： open() "/opt/sites/joy456/media/xxxxx.jpg" failed (2: No such file or directory)的错误

只要是反向代理的静态文件都不好使。
