### ISSUE TITLE
[FEATURE] 建议增加RPA类的软件

### ISSUE THREAD

**Issue by duguyue8** [1Panel-dev/1Panel#3214]
### 1Panel 版本

1.8.5

### 请描述您的需求或者改进建议

在我们日常的工作和生活中，有很多繁琐但重复性的工作，如果全部通过人来做的话，是比较耗时且没有成长性的，RPA类的软件就能很好的解决这个问题，再一个固定的流程标准化，定期去执行就完了。非常实用的一个工具

### 请描述你建议的实现方案

目前RPA类的软件开源的有 [n8n](https://github.com/n8n-io/n8n) 等

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述应用。

**Comment by wanghe-fit2cloud** [comment]
已上架。可以进入应用商店，点击右上角的【更新应用列表】按钮，待同步完成后即可安装应用。
