### ISSUE TITLE
[FEATURE] redis支持快速命令

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#3220]
### 1Panel 版本

1.8.5

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/51264840/8f90e43b-e0b9-473d-b64b-cc120a942007)

### 请描述你建议的实现方案

如：终端里的快速命令

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
