### ISSUE TITLE
[FEATURE]一键脚本不够完善缺少检测&机制报错信息不清晰

### ISSUE THREAD

**Issue by gimgoo** [1Panel-dev/1Panel#3222]
### 1Panel 版本

无关版本

### 请描述您的需求或者改进建议

CentOS9干净系统，刚重装完的，执行一键脚本报错 quick_start.sh: line 66: tar: command not found，实际上就是 缺少 tar需要先执行 yum install -y tar。脚本没有在开头或者执行命令前检测是否有安装相应组件，也不会提示缺少什么，只提示命令没找到，下载安装包失败，不打开脚本去看66行都不知道是缺少tar

**Comment by wanghe-fit2cloud** [comment]
错误信息：
```
quick_start.sh: line 66: tar: command not found
```
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/bd80d79c-bab7-4b93-8421-9a42e21801ef)

手动安装 tar 命令后，再来重新执行安装脚本（安装包已下载完成，不会重复下载）。
> 鉴于需要适配多种操作系统版本和架构，目前不会在安装阶段安装 `curl` `tar`等基础命令。

**Comment by vocaloidat** [comment]
还是错误。你们的命令不是先执行下载quick_start.sh，然后在执行吗？
手动安装 tar 命令是什么？
