### ISSUE TITLE
容器日志问题

### ISSUE THREAD

**Issue by yn-zxj** [1Panel-dev/1Panel#3224]
### 请描述您的问题

面板后台 使用ip登录 可以查看正常的容器日志，但是当我使用域名的方式打开面板后台，容器日志就看不到了，请问这是需要做什么配置吗？
<img width="803" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/44137601/7d8f2e1a-66dd-4d2d-9289-f24c115e94c7">

**Comment by ssongliu** [comment]
感谢反馈，可以域名方式先看看容器终端和面板终端是否能够正常访问。

**Comment by yn-zxj** [comment]
我试了下  终端访问不了   是不是要做什么配置    另外 我在官网的1Panel演示站点  也是看不到容器日志的  但是这个不太清楚是不是你们故意这么设置的

**Comment by ssongliu** [comment]
nginx 配置里面需要加上下面这段配置，支持 websocket：
```
location / {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```

**Comment by yn-zxj** [comment]
非常感谢！ 解决了！谢谢！
