### ISSUE TITLE
[BUG]强制拉取镜像问题

### ISSUE THREAD

**Issue by xxvolvo** [1Panel-dev/1Panel#3226]
### 1Panel 版本

1.8.5

### 问题描述

镜像仓库（阿里云ACR）中的镜像升级后，前后标签均为latest，在容器面板中升级时，勾选了强制拉取镜像，但是并不生效，依然用本地镜像进行了重新部署。

### 重现步骤

见问题描述。

**Comment by xxvolvo** [comment]
目前的操作方式似乎只有在镜像面板中重新拉一个镜像，然后去编辑容器才能相对平滑的升级。是使用姿势不对吗？还是哪里出了什么问题。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们现在本地环境复现一下上述问题。

**Comment by xxvolvo** [comment]
> 感谢反馈，我们现在本地环境复现一下上述问题。

感谢回复，如果需要复现场景的话可以随时联系我。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布，建议升级到最新版本。

**Comment by xxvolvo** [comment]
出现了新的问题，从容器强制升级拉镜像的时候，提示了`repository does not exist or may require 'docker login': denied: requested access to the resource is denied`。弹窗中的镜像地址是正确的。在镜像Tab中拉取镜像也是正常的。在仓库Tab已经维护过了对应仓库地址和用户名密码。

**Comment by ssongliu** [comment]
> 出现了新的问题，从容器强制升级拉镜像的时候，提示了`repository does not exist or may require 'docker login': denied: requested access to the resource is denied`。弹窗中的镜像地址是正确的。在镜像Tab中拉取镜像也是正常的。在仓库Tab已经维护过了对应仓库地址和用户名密码。

是一个问题，之前的版本如果镜像拉取失败时会触发回滚操作，但是没有显式的返回错误，这个版本改成了镜像拉取失败直接返回。

强制拉取镜像时，输入的镜像信息是包括完成的仓库链接吗？可以截图看一下。

**Comment by xxvolvo** [comment]
> > 出现了新的问题，从容器强制升级拉镜像的时候，提示了`repository does not exist or may require 'docker login': denied: requested access to the resource is denied`。弹窗中的镜像地址是正确的。在镜像Tab中拉取镜像也是正常的。在仓库Tab已经维护过了对应仓库地址和用户名密码。
> 
> 是一个问题，之前的版本如果镜像拉取失败时会触发回滚操作，但是没有显式的返回错误，这个版本改成了镜像拉取失败直接返回。
> 
> 强制拉取镜像时，输入的镜像信息是包括完成的仓库链接吗？可以截图看一下。

是的，输入的是完整的镜像地址。截图如下
![image](https://github.com/1Panel-dev/1Panel/assets/16984534/3beddce1-62ec-428d-8068-b8859ec039df)
另外发现在镜像Tab中拉取镜像时，勾选掉镜像仓库选项，直接输入镜像地址时，控制台一直处于一个无反应的状态。

**Comment by xxvolvo** [comment]
> > > 出现了新的问题，从容器强制升级拉镜像的时候，提示了`repository does not exist or may require 'docker login': denied: requested access to the resource is denied`。弹窗中的镜像地址是正确的。在镜像Tab中拉取镜像也是正常的。在仓库Tab已经维护过了对应仓库地址和用户名密码。
> > 
> > 
> > 是一个问题，之前的版本如果镜像拉取失败时会触发回滚操作，但是没有显式的返回错误，这个版本改成了镜像拉取失败直接返回。
> > 强制拉取镜像时，输入的镜像信息是包括完成的仓库链接吗？可以截图看一下。
> 
> 是的，输入的是完整的镜像地址。截图如下 ![image](https://private-user-images.githubusercontent.com/16984534/290142164-3beddce1-62ec-428d-8068-b8859ec039df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjA2MDIsIm5iZiI6MTcwMjQ2MDMwMiwicGF0aCI6Ii8xNjk4NDUzNC8yOTAxNDIxNjQtM2JlZGRjZTEtNjJlYy00MjhkLTgwNjgtYjg4NTllYzAzOWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA5MzgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNTcyNzliN2ZhNjk5OTdlZDA5MjdlYjhhMmY3YzEzNDI3NjA3Yzk5ZWVlMDYzZWQ5ZmVjOWQ4ZmFlMTZiNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._hSHC1te5pukwmHZiG0PQOM7l6z-fl1KLrMTCrmEmIE) 另外发现在镜像Tab中拉取镜像时，勾选掉镜像仓库选项，直接输入镜像地址时，控制台一直处于一个无反应的状态。

这个是在1.9版本下的错误。

**Comment by ssongliu** [comment]
> > > > 出现了新的问题，从容器强制升级拉镜像的时候，提示了`repository does not exist or may require 'docker login': denied: requested access to the resource is denied`。弹窗中的镜像地址是正确的。在镜像Tab中拉取镜像也是正常的。在仓库Tab已经维护过了对应仓库地址和用户名密码。
> > > 
> > > 
> > > 是一个问题，之前的版本如果镜像拉取失败时会触发回滚操作，但是没有显式的返回错误，这个版本改成了镜像拉取失败直接返回。
> > > 强制拉取镜像时，输入的镜像信息是包括完成的仓库链接吗？可以截图看一下。
> > 
> > 
> > 是的，输入的是完整的镜像地址。截图如下 ![image](https://private-user-images.githubusercontent.com/16984534/290142164-3beddce1-62ec-428d-8068-b8859ec039df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjA2MDIsIm5iZiI6MTcwMjQ2MDMwMiwicGF0aCI6Ii8xNjk4NDUzNC8yOTAxNDIxNjQtM2JlZGRjZTEtNjJlYy00MjhkLTgwNjgtYjg4NTllYzAzOWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA5MzgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNTcyNzliN2ZhNjk5OTdlZDA5MjdlYjhhMmY3YzEzNDI3NjA3Yzk5ZWVlMDYzZWQ5ZmVjOWQ4ZmFlMTZiNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._hSHC1te5pukwmHZiG0PQOM7l6z-fl1KLrMTCrmEmIE) 另外发现在镜像Tab中拉取镜像时，勾选掉镜像仓库选项，直接输入镜像地址时，控制台一直处于一个无反应的状态。
> 
> 这个是在1.9版本下的错误。

直接在终端手动执行 docker pull 完整的镜像名能拉取下来吗？

**Comment by xxvolvo** [comment]
> docker pull

可以，所以就觉得很奇怪。

**Comment by ssongliu** [comment]
> > docker pull
> 
> 可以，所以就觉得很奇怪。

麻烦加一下我，我看一下这个问题
<img src="https://github.com/1Panel-dev/1Panel/assets/73214554/13314235-ef8f-474b-8694-11064bf85cd9" width="186px" height="156px">

**Comment by xxvolvo** [comment]
> > > docker pull
> > 
> > 
> > 可以，所以就觉得很奇怪。
> 
> 麻烦加一下我，我看一下这个问题 <img alt="" width="186px" height="156px" src="https://private-user-images.githubusercontent.com/73214554/290161115-13314235-ef8f-474b-8694-11064bf85cd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NjQ5NDksIm5iZiI6MTcwMjQ2NDY0OSwicGF0aCI6Ii83MzIxNDU1NC8yOTAxNjExMTUtMTMzMTQyMzUtZWY4Zi00NzRiLTg2OTQtMTEwNjRiZjg1Y2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDEwNTA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNDM5ZmMwZWRkZGU2NWQ3MmFjOTQ1NDRjOGIyYTA0MTliY2U1NzI5ZDMxNzNkY2E0NjU3MTQ5NzE0NzNhNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mf32MId2HCHUxdiGggb12leA10EAAJsYu9fdCD3qifY">

加了

**Comment by catsonkeyboard** [comment]
我也出现了这个问题，我在仓库里面配置了私有仓库的账号密码，然后强制拉取我个人仓库镜像的时候，还是报：
服务内部错误: pull image xxx failed, err: Error response from daemon: pull access denied for xxx, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by wanghe-fit2cloud** [comment]
> 我也出现了这个问题，我在仓库里面配置了私有仓库的账号密码，然后强制拉取我个人仓库镜像的时候，还是报： 服务内部错误: pull image xxx failed, err: Error response from daemon: pull access denied for xxx, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

已知问题，我们会在近期发布小版本来修复。

**Comment by wanghe-fit2cloud** [comment]
v1.9.1 版本已发布。

**Comment by demonyins** [comment]
1.9.2系统还是报错强制错误，为什么不优先使用本地镜像呢?

**Comment by wanghe-fit2cloud** [comment]
> 1.9.2系统还是报错强制错误，为什么不优先使用本地镜像呢?

提供一下具体操作和错误日志。
