### ISSUE TITLE
[FEATURE] 终端可以在左侧加一个资产树吗？看起来更清晰，操作也方便

### ISSUE THREAD

**Issue by liufei20151013** [1Panel-dev/1Panel#3229]
### 1Panel 版本

v1.8.3

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/15103510/3960b24f-1781-494f-b9f0-4f0fd59a382f)

### 请描述你建议的实现方案

终端可以在左侧加一个资产树吗？看起来更清晰，操作也方便。

**Comment by zhengkunwang223** [comment]
后续版本持续优化

**Comment by wanghe-fit2cloud** [comment]
经过评审，我们决定暂时不增加左侧资产树。
选择资产按钮在最新版本中已经进行了优化，建议您将 1Panel 升级至最新版本，然后再查看是否仍然存在飘动的问题。
