### ISSUE TITLE
[FEATURE]网站负载均衡有开发的计划吗，我看很多人提了这个需求但是一直没有排期计划

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3230]
### 1Panel 版本

v1.8.5

### 请描述您的需求或者改进建议

网站负载均衡有开发的计划吗，我看很多人提了这个需求但是一直没有排期计划。特别需要这个功能。

**Comment by zhengkunwang223** [comment]
您好 最近几个版本暂时没有这个计划  
如果您可以提供具体的功能需求或者技术实现 
可能会提前做
当然 如果你先 star 一下我们的项目，就更好了

**Comment by wanghe-fit2cloud** [comment]
重复 #2058

**Comment by LiXunGuan** [comment]
其实可以做docker swarm集群，在里面实现集群的负载均衡

**Comment by ceozero** [comment]
真难等，，等了这么多个版本都没出个负载均衡。现在 要手动编译个fair模块可真费劲。
