### ISSUE TITLE
[QUESTION] jellyfin硬解该如何配置

### ISSUE THREAD

**Issue by TangTangH** [1Panel-dev/1Panel#3233]
### 请描述您的问题

环境：cpu  J1900

开启Intel QuickSync(Qsv)时，播放视频会报错，但是看intel官网，J1900是支持Qsv的，需要怎么配置吗？网上搜，绝大部分都是群晖的帖子，试了几个都没有解决。

**Comment by zhengkunwang223** [comment]
应用问题你可以在论坛里问一下

**Comment by lessthink** [comment]
把显卡映射给容器
