### ISSUE TITLE
安装一直卡在docker

### ISSUE THREAD

**Issue by jiushaba** [1Panel-dev/1Panel#3235]
### 请描述您的问题

安装一直卡在docker
![image](https://github.com/1Panel-dev/1Panel/assets/26453056/b49748ad-85e6-4887-a6c4-604d29427f1d)

**Comment by wanghe-fit2cloud** [comment]
网络问题，尝试手动安装好 docker 后再来运行 1Panel 在线安装脚本。
也可以使用如下脚本：
```shell
bash <(curl -sSL https://linuxmirrors.cn/docker.sh)
```
