### ISSUE TITLE
[FEATURE] 希望应用 多增加一些版本，新老都有的那种

### ISSUE THREAD

**Issue by OuOumm** [1Panel-dev/1Panel#3237]
### 1Panel 版本

v1.8.5

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/43441064/6de0932e-fbec-4bf7-88ad-ed2ccb5d5caf)

这种需求的话，容易满足吗？不容易就算了

### 请描述你建议的实现方案

直接docker镜像塞进来。

**Comment by maninhill** [comment]
如果你对哪个应用有特殊的版本要求，可以提出来。版本太多，维护工作量很大。
