### ISSUE TITLE
[QUESTION]安装好MySQL之后，无法启动，报docker-compose.yml: no such file or directory。但是实际上有这个文件

### ISSUE THREAD

**Issue by lemonGGGit** [1Panel-dev/1Panel#3239]
### 请描述您的问题

错误日志：
`服务内部错误: stderr: stat /opt/1panel/apps/mysql/mysql/docker-compose.yml: no such file or directory`
系统：Ubuntu 22.04.3 LTS

**Comment by wanghe-fit2cloud** [comment]
1、执行 `docker-compose version` 命令查看一下具体版本
2、执行 `ls -l /opt/1panel/apps/mysql/mysql/` 命令查看一下文件夹以及文件权限
3、执行 `cd /opt/1panel/apps/mysql/mysql/` 命令进入应用文件夹，通过 `docker-compose up -d` 命令查看一下运行结果

**Comment by lemonGGGit** [comment]
> 1、执行 `docker-compose version` 命令查看一下具体版本 2、执行 `ls -l /opt/1panel/apps/mysql/mysql/` 命令查看一下文件夹以及文件权限 3、执行 `cd /opt/1panel/apps/mysql/mysql/` 命令进入应用文件夹，通过 `docker-compose up -d` 命令查看一下运行结果

——————————————————不好意思，docker小白——————————————————

-`docker-compose version`的结果：
Docker Compose version v2.17.2

-`ls -l /opt/1panel/apps/mysql/mysql/` 的结果，改成777了：
drwxrwxrwx 2 root root 4096 Dec  9 16:06 conf
-rwxrwxrwx 1 root root  464 Dec  9 16:06 data.yml
-rwxrwxrwx 1 root root  866 Dec  9 16:06 docker-compose.yml

-`docker-compose up -d`的结果：
no configuration file provided: not found

**Comment by wanghe-fit2cloud** [comment]
> `docker-compose up -d`的结果：
> no configuration file provided: not found

是进入 `/opt/1panel/apps/mysql/mysql/` 目录后执行的命令吗，截图看一下。

**Comment by lemonGGGit** [comment]
> > `docker-compose up -d`的结果：
> > no configuration file provided: not found
> 
> 是进入 `/opt/1panel/apps/mysql/mysql/` 目录后执行的命令吗，截图看一下。

![image](https://github.com/1Panel-dev/1Panel/assets/36196725/ef85b00a-0a9b-42ff-a3cf-2d1425760aea)

**Comment by wanghe-fit2cloud** [comment]
本地环境均未能复现上述问题
> 你的 1Panel 服务器是 WSL 的吗？

再进入 `应用商店` - `已安装` 页面卸载 MySQL，重新创建 MySQL 后不要手动修改权限，然后执行以下命令，看一下结果：
```shell
sudo docker-compose -f /opt/1panel/apps/mysql/mysql/docker-compose.yml up -d
```

**Comment by lemonGGGit** [comment]
> 本地环境均未能复现上述问题
> 
> > 你的 1Panel 服务器是 WSL 的吗？
> 
> 再进入 `应用商店` - `已安装` 页面卸载 MySQL，重新创建 MySQL 后不要手动修改权限，然后执行以下命令，看一下结果：
> 
> ```shell
> sudo docker-compose -f /opt/1panel/apps/mysql/mysql/docker-compose.yml up -d
> ```

卸载重装后，执行结果如下，明明有`docker-compose.yml`这个文件，但是就是说没有。我装其他应用也是一样的报错。
![image](https://github.com/1Panel-dev/1Panel/assets/36196725/18aace7a-1e33-447d-9568-39673a2ca1d4)

**Comment by wanghe-fit2cloud** [comment]
1Panel 就是调用的宿主机 `docker-compose` 命令来安装的应用，本地手动执行都有问题，通过 1Panel 来安装肯定也会失败。
> 你服务器可以远程访问吗，远程帮忙你看一下问题。
也可以进微信交流群添加我微信。

**Comment by lemonGGGit** [comment]
> 1Panel 就是调用的宿主机 `docker-compose` 命令来安装的应用，本地手动执行都有问题，通过 1Panel 来安装肯定也会失败。
> 
> > 你服务器可以远程访问吗，远程帮忙你看一下问题。
> > 也可以进微信交流群添加我微信。

暂时无法远程访问。我来加微信交流群吧，谢谢

**Comment by wanghe-fit2cloud** [comment]
参考一下，看是否和论坛中这个问题一样：
https://bbs.fit2cloud.com/t/topic/2397/5

**Comment by QAQpk** [comment]
> 1Panel 就是调用的宿主机 命令来安装的应用，本地手动执行都有问题，通过 1Panel 来安装肯定也会失败。`docker-compose`
> 
> > 你服务器可以远程访问吗，远程帮忙你看一下问题。
> > 也可以进微信交流群添加我微信。

我在创建的时候也出现同样的问题，可以帮一下吗？

**Comment by lmmsoft** [comment]
问题 +1 ， 文件有，就是1panel找不到

**Comment by image72** [comment]
<img width="1427" alt="Image" src="https://github.com/user-attachments/assets/d85bf653-a875-4523-9584-37052c737910" />
still errors in Logs panel: stat /opt/1panel/apps/minio/minio/docker-compose.yml: no such file or directory

```shell
admin@backend0:~/workspace$ docker info
Client:
 Version:    27.2.0
```
