### ISSUE TITLE
[BUG] Onedrive备份出现unauthenticated - Unauthenticated

### ISSUE THREAD

**Issue by Marcus-zh** [1Panel-dev/1Panel#3240]
### 联系方式

marcus-zh@qq.com

### 1Panel 版本

v1.8.5

### 问题描述

按照文档步骤,申请code,然后填进框里,出现"备份账号测试连接失败 unauthenticated - Unauthenticated"弹窗,但是onedrive里有备份路径,且有test文件

### 重现步骤

同文档步骤

### 期待的正确结果

成功设置

### 相关日志输出

```shell
信息
服务内部错误: no such access token in response
```

**Comment by wanghe-fit2cloud** [comment]
可以参考一下这两个 issue
#1931 
#2610

**Comment by Marcus-zh** [comment]
不能解决,授权码返回的是M.C106_BAY.2.7ccccc111-c11c-1ccc-1111-1111c11cc108,而且同个授权码第一次是unauthenticated - Unauthenticated ,第二次是 no such access token in response

**Comment by Marcus-zh** [comment]
@wanghe-fit2cloud 能再看眼吗

**Comment by wanghe-fit2cloud** [comment]
你提供的 OneDrive 账号是国内版还是国际版？

**Comment by Marcus-zh** [comment]
> 你提供的 OneDrive 账号是国内版还是国际版？

国际版

**Comment by ssongliu** [comment]
> > 你提供的 OneDrive 账号是国内版还是国际版？
> 
> 国际版

尝试删除后重新添加一下。

**Comment by Marcus-zh** [comment]
> > > 你提供的 OneDrive 账号是国内版还是国际版？
> > 
> > 
> > 国际版
> 
> 尝试删除后重新添加一下。

都没能添加成功

**Comment by ssongliu** [comment]
重新添加需要重新获取授权码，授权码是一次性的。

**Comment by Marcus-zh** [comment]
这是操作步骤
![录制_2023_12_10_10_53_00_472](https://github.com/1Panel-dev/1Panel/assets/102860926/bbc1b47f-af48-406b-bc04-46b7962d56c6)

**Comment by ssongliu** [comment]
`https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=010935a9-1aa9-4854-a1dc-6e45fe628c6b&redirect_uri=http://localhost/login/authorized&scope=offline_access+Files.ReadWrite.All+User.Read`

获取时候的跳转地址好像不太对，你请求一下这个路径看看

**Comment by Marcus-zh** [comment]
请求后是http://localhost:80/login/authorized?code=M.C106_BAY.2.ef111111-35c9-b0f2-0d09-91111de6d592

**Comment by Marcus-zh** [comment]
不好意思,上周上课去了

**Comment by mobeicanyue** [comment]
我现在有一样的问题，之前是成功添加过 onedrive 账号并且备份成功，现在无法备份，unauthenticated - Unauthenticated。
尝试删除重新添加后 出现楼主上述复现的问题

**Comment by ssongliu** [comment]
> 重新获取授权码，授权码是一次性的。

麻烦添加一下我，我看看这个问题
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/572eb525-f186-4fd6-938b-fa8e501e1154)

**Comment by mobeicanyue** [comment]
> > 重新获取授权码，授权码是一次性的。
> 
> 麻烦添加一下我，我看看这个问题 ![image](https://private-user-images.githubusercontent.com/73214554/296167525-572eb525-f186-4fd6-938b-fa8e501e1154.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDg1NTEsIm5iZiI6MTcwNTA0ODI1MSwicGF0aCI6Ii83MzIxNDU1NC8yOTYxNjc1MjUtNTcyZWI1MjUtZjE4Ni00ZmQ2LTkzOGItZmE4ZTUwMWUxMTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA4MzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2ODI0Njc2NTgyZDA4MmFjZmEwMmZiYjhmZDdkZDFkYmNiNmYzYzBiZjUwNzMyN2VhMDM2NzAxY2M1MGJkMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p4AkQJKwzd7ByLZKnRqOo-fn-gPPwtDE8vsUSwvBZ5Y)

加你了 通过一下

**Comment by Marcus-zh** [comment]
我又来了,onedrive添加成功,但是上传快照又出现
![image](https://github.com/1Panel-dev/1Panel/assets/102860926/8709e94f-2875-49f6-b260-9cd9e5149668)

**Comment by ssongliu** [comment]
> 我又来了,onedrive添加成功,但是上传快照又出现 ![image](https://private-user-images.githubusercontent.com/102860926/306857047-8709e94f-2875-49f6-b260-9cd9e5149668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NzU3OTgsIm5iZiI6MTcwODU3NTQ5OCwicGF0aCI6Ii8xMDI4NjA5MjYvMzA2ODU3MDQ3LTg3MDllOTRmLTI4NzUtNDlmNi1iMjYwLTljZDllNTE0OTY2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQwNDE4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmQxMTVhMmJkMWFiOTcyMzQ5NjExMTg2NTUzZDUwMjRjZGUwMDRhMzU4NWM0MWY5MjgxNTRhZmFjYWRiOTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WjipBfONPjlQ_VxANUnY3-YEG7obAA99AWqmGplm-us)

截图看一下备份账号界面的 onedrive 状态

**Comment by Marcus-zh** [comment]
是正常的,又刷新了一下还是这样
因为急着重装,所有先备份到本地的
