### ISSUE TITLE
[BUG] 安全入口-概况页提醒不生效吗？

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#3241]
### 联系方式

9a6c

### 1Panel 版本

1.8.5

### 问题描述

该功能，我的理解是不开启提醒时， 没有输入安全入口时将不显示以下界面，还是我的理解有问题
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/c9a16fe8-6be7-4a61-8a8c-f783defdc9f7)
当我清理浏览器缓存后该状态被重置 勾选状态
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/50290330-a093-41f3-8973-e89e5962d021)

不是很理解该功能

### 重现步骤

面板设置-安全-安全入口，取消勾选概况页未开启提醒， 输入自己的面板地址不带安全入口

**Comment by wanghe-fit2cloud** [comment]
面板设置中这个复选框是为了屏蔽概览页面未开启安全入口时的提示信息。

> 当前版本，在开启安全入口但浏览器输入不正确的情况下，都会统一跳提示页面，后面版本会做出调整。

**Comment by qwenode** [comment]
@wanghe-fit2cloud 这个我昨晚刚好看到了,测试了一下,这个参数修改并不会发包,也就是只有在客户端记录? 没看到请求中有将这个参数发给服务端记录起来

**Comment by 9a6c** [comment]
> 这个我昨晚刚好看到了,测试了一下,这个参数修改并不会发包,也就是只有在客户端记录?没看到请求中有将这个参数发给服务端记录起来

是的， 清理浏览器缓存这个状态就重置了

**Comment by wanghe-fit2cloud** [comment]
> @wanghe-fit2cloud 这个我昨晚刚好看到了,测试了一下,这个参数修改并不会发包,也就是只有在客户端记录? 没看到请求中有将这个参数发给服务端记录起来

是的，没有记录到服务端。

**Comment by wanghe-fit2cloud** [comment]
#2594
