### ISSUE TITLE
[BUG] Docker in Ubuntu Snap can't be restarted in panel.

### ISSUE THREAD

**Issue by DSYZayn** [1Panel-dev/1Panel#3242]
### 联系方式

1546492103@qq.com

### 1Panel 版本

v1.8.5

### 问题描述

My docker was installed by snap, it use `snap` command to manage applications and actually the proper corresponding command is as follows:
```bash
$ sudo snap restart docker
```

### 重现步骤

After input docker accelerated url and restart it on web panel, it will cause error while the default logic seems to assume that the user's docker was managed by `systemd`.

### 期待的正确结果

If you're encountered with an  error like that, plz try to use `sudo snap restart docker` command and collect the follow-up messages.

### 相关日志输出

```shell
popup is as follows:
服务内部错误: stderr: Failed to restart docker.service: Unit docker.service not found
```

**Comment by zhengkunwang223** [comment]
The current 1Panel is managed through systemd, overseeing processes such as Docker, Supervisor, UFW/Firewalld, and others. Therefore, it may be necessary for you to change the management approach.

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
