### ISSUE TITLE
加密方式为rsa生成的密钥无法使用

### ISSUE THREAD

**Issue by TtBJSH** [1Panel-dev/1Panel#3243]
### 联系方式

ttbjsht@163.com

### 1Panel 版本

1.8.5

### 问题描述

在ssh管理页面生成密钥无法使用

### 重现步骤

ssh管理页面生成密钥，使用xshell连接无法加载秘钥

### 期待的正确结果

ssh管理页面生成的密钥使用xshell可以正常连接

**Comment by wanghe-fit2cloud** [comment]
将 A 服务器公钥内容添加到 B 主机 authorized_keys 文件，然后在使用工具连接时提供的用户密钥为私钥内容。

**Comment by Mr-Ao-Dragon** [comment]
你的密钥泄露了部分，建议码掉
