### ISSUE TITLE
[BUG]网站域名解析错误

### ISSUE THREAD

**Issue by 60999** [1Panel-dev/1Panel#3244]
### 1Panel 版本

1.8.5

### 问题描述

创建二级域名网站后，依然解析到主站上。openresty/openresty:1.21.4.3-0-focal 更新到此版本后依然错误

### 重现步骤

1.创建网站主站 aa.com,其他域名填写*.aa.com，静态网站，申请SSL证书，启用HTTPS，HTTP 选项：访问HTTP自动跳转到HTTPS。
访问aa.com和t1.aa.com为同一个站。
2.创建网站 t1.aa.com，静态网站，http访问，会https跳转，访问内容同主站aa.com一样。
之后。
3.删除主站下域名*.aa.com，检查配置文件，没有*.aa.com绑定
4.访问网站 t1.aa.com，静态网站，http访问，会https跳转，访问内容同主站aa.com一样。

### 期待的正确结果

应该优先解析t1.aa.com，确定域名的网站，再解析泛域名的网站。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by 60999** [comment]
停止主站后，访问t1.aaa.com显示为网站停止，也不正常

**Comment by 60999** [comment]
删除缓存 /opt/1panel/cache 文件；后重启服务也不正常

**Comment by zhengkunwang223** [comment]
> ### 联系方式
> _No response_
> 
> ### 1Panel 版本
> 1.8.5
> 
> ### 问题描述
> 创建二级域名网站后，依然解析到主站上。openresty/openresty:1.21.4.3-0-focal 更新到此版本后依然错误
> 
> ### 重现步骤
> 1.创建网站主站 aa.com,其他域名填写*.aa.com，静态网站，申请SSL证书，启用HTTPS，HTTP 选项：访问HTTP自动跳转到HTTPS。 访问aa.com和t1.aa.com为同一个站。 2.创建网站 t1.aa.com，静态网站，http访问，会https跳转，访问内容同主站aa.com一样。 之后。 3.删除主站下域名*.aa.com，检查配置文件，没有*.aa.com绑定 4.访问网站 t1.aa.com，静态网站，http访问，会https跳转，访问内容同主站aa.com一样。
> 
> ### 期待的正确结果
> 应该优先解析t1.aa.com，确定域名的网站，再解析泛域名的网站。
> 
> ### 相关日志输出
> _No response_
> 
> ### 附加信息
> _No response_

未复现此问题
访问网站，可能会受到浏览器缓存影响，你可以尝试用其他浏览器，或者用命令访问网站
或者重启 OpenResty 来消除缓存影响

**Comment by 60999** [comment]
强制刷新，不受缓存影响，故障依旧
用其他浏览器，故障依旧
命令访问网站，故障依旧
重启 OpenResty ，故障依旧
换新电脑，重装系统，故障依旧。

网站t1.aa.com ，http访问后，跳转到https t1.aa.com,证书用的是 *.aa.com

**Comment by 60999** [comment]
现在升级v1.9.0了，故障依旧

**Comment by 60999** [comment]
大概产生条件找到了：
1 默认站点设置为 aa.com
2 站点aa.com使用了ssl证书，http跳转到https，证书 为aa.com和*.aa.com
3 站点t1.aa.com没有使用ssl证书。

在以上情况，http 访问t1.aa.com 会跳转到https访问，t1.aa.com 并且调用了aa.com的内容（证书错误）
奇怪的是如果关闭t1.aa.com的启用 HTTPS功能，再次访问t1.aa.com会提示“你的连接不是专用连接”然后无法访问；
如果用另一台从未访问过t1.aa.com的电脑访问，则http访问会获得t1.aa.com网站目录下内容,而https访问会获得默认网站目录aa.com下内容。
我另外做了这样的测试，新建一个t1.bb.com的网站，也会出现同样的情况，并且出现的是默认网站内容aa.com。

以上情况可以复现，可以联系我v e2ee1211

**Comment by zhengkunwang223** [comment]
> 大概产生条件找到了： 1 默认站点设置为 aa.com 2 站点aa.com使用了ssl证书，http跳转到https，证书 为aa.com和*.aa.com 3 站点t1.aa.com没有使用ssl证书。
> 
> 在以上情况，http 访问t1.aa.com 会跳转到https访问，t1.aa.com 并且调用了aa.com的内容（证书错误） 奇怪的是如果关闭t1.aa.com的启用 HTTPS功能，再次访问t1.aa.com会提示“你的连接不是专用连接”然后无法访问； 如果用另一台从未访问过t1.aa.com的电脑访问，则http访问会获得t1.aa.com网站目录下内容,而https访问会获得默认网站目录aa.com下内容。 我另外做了这样的测试，新建一个t1.bb.com的网站，也会出现同样的情况，并且出现的是默认网站内容aa.com。
> 
> 以上情况可以复现，可以联系我v e2ee1211

感谢回复 我们测试一下

**Comment by zhengkunwang223** [comment]
经过测试 是由于设置了默认 https 网站 ，而 Nginx 配置中，默认网站 default_server 的优先级是很高的，当存在没有配置 https 的 http 网站的时候，访问这个网站的 https 地址，会匹配到 default_server 中，具体看 Nginx 官方解释 https://nginx.org/en/docs/http/request_processing.html   
解决方案 ：
 1. 把 http 网站配置为 https （推荐）
 2. http 网站的配置文件中手动配置 listen 443; (不推荐)
 3. 取消 https 默认网站
