### ISSUE TITLE
[BUG] 官方的php app, php8.2.10 默认是开启慢查询的,但是有个问题

### ISSUE THREAD

**Issue by qwenode** [1Panel-dev/1Panel#3247]
### 1Panel 版本

1.8.5/ 容器 1panel-php:8.2.10

### 问题描述

在日志中会发现ERROR: failed to ptrace(ATTACH) child 18: Operation not permitted (1) 

### 重现步骤

在日志中会发现ERROR: failed to ptrace(ATTACH) child 18: Operation not permitted (1) 这类的问题,解决方式如下：
https://serverfault.com/questions/704007/php-slowlog-causing-ptrace-error-in-docker-container

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在后续版本调研一下上述问题。
> `重现步骤` 中提供的链接地址打不开。

**Comment by igophper** [comment]
下面是chatgpt的回答，和上面链接内容基本一致
[CHATGPT](https://chat.openai.com/share/2d0c530b-0ec5-4ffb-9307-54f89518f276)

**Comment by wanghe-fit2cloud** [comment]
> 下面是chatgpt的回答，和上面链接内容基本一致 [CHATGPT](https://chat.openai.com/share/2d0c530b-0ec5-4ffb-9307-54f89518f276)

收到。

**Comment by zhengkunwang223** [comment]
经过验证 非 BUG 是 PHP 优化相关问题
