### ISSUE TITLE
[BUG]在网站->域名设置->新增域名中的端口设置无效，新增端口非80/443均无法访问

### ISSUE THREAD

**Issue by 52lemon6** [1Panel-dev/1Panel#325]
### 1Panel 版本

1.0.2

### 问题描述

在网站->域名设置->新增域名中的端口设置无效，新增端口非80/443均无法访问，防火墙已关闭

### 重现步骤

在网站->域名设置->新增域名中的端口设置无效，新增端口非80/443均无法访问

**Comment by newcardriver** [comment]
如果是云服务器的话，看一下有没有打开安全组端口，如果不是的话，等后面作者回吧。

**Comment by 52lemon6** [comment]
> 果是云服务器的话，看一下有没有打开安全组端口，如果不是的话，等后面作者

安全组端口是开的

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
您好，我们没有复现这个问题，您可以先清除浏览器缓存，然后再试一下，如果还不可以的话，请详细描述一下复现步骤

**Comment by zhengkunwang223** [comment]
您好 经过我们测试 是没有放开防火墙端口导致的 下个版本会增加自动放开防火墙端口的功能

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
