### ISSUE TITLE
[FEATURE] 支持创建自定义php运行环境

### ISSUE THREAD

**Issue by qwenode** [1Panel-dev/1Panel#3252]
### 1Panel 版本

1.8.5

### 请描述您的需求或者改进建议

当前根据官方的php app创建自己的php运行环境无法成功,发现是以下代码位置写死了路径检测

![image](https://github.com/1Panel-dev/1Panel/assets/8974108/d15ca2cf-7b2c-41b5-ae98-63ac4657ffa5)

![image](https://github.com/1Panel-dev/1Panel/assets/8974108/34e3fbd6-384e-485f-b40e-93f11db6a187)

### 请描述你建议的实现方案

希望能兼容本地应用,
这个步骤建议放到编译脚本里面实现
download app[PHP 8] from https://apps-assets.fit2cloud.com/stable/1panel/php8/8.1.23/php8-8.1.23.tar.gz

**Comment by qwenode** [comment]
有这个需求主要是1p的php版本有时候更新没那么及时

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
