### ISSUE TITLE
[FEATURE] 备份账号-OneDrive 希望可以自己配置clientid和secret 等信息

### ISSUE THREAD

**Issue by siyuan797** [1Panel-dev/1Panel#3255]
### 1Panel 版本

1.8.5

### 请描述您的需求或者改进建议

希望在添加备份账号-OneDrive可以自己配置clientid和secret等信息，不手动配置才用默认的，如果有其他要调用第三方oauth登录的地方也要支持自己配置

**Comment by ssongliu** [comment]
感谢反馈，考虑到自己配置的话，需要自己先注册 web 应用，然后提供 clientid secret 以及重定向地址 redirect_uri，操作比较麻烦，不够简单易用。

后续版本考虑支持该功能。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
