### ISSUE TITLE
[BUG]申请证书失败，服务内部错误: error: one or more domains had a problem

### ISSUE THREAD

**Issue by hotmop** [1Panel-dev/1Panel#3256]
### 1Panel 版本

1.8.5

### 问题描述

申请证书失败
服务内部错误: error: one or more domains had a problem: [xxx.com] [xxx.com] acme: error presenting token: cloudflare: unexpected response code 'SERVFAIL' for _acme-challenge.xxx.com.

### 重现步骤

通过DNS解析 手动解析 均提示以上错误内容
DNS是最高权限API，无错误

### 期待的正确结果

正确申请证书。

**Comment by zhengkunwang223** [comment]
可能与你的 nameserver  有关，你可以用 HTTP 模式申请证书试一下

**Comment by wanghe-fit2cloud** [comment]
#1948
