### ISSUE TITLE
[BUG]商店里的showdoc不支持arm，需要手动修改

### ISSUE THREAD

**Issue by yinyajiang** [1Panel-dev/1Panel#3257]
### 1Panel 版本

v1.8.5

### 问题描述

arm服务器，安装商店里的showdoc会失败，需要手动将docker-compose.yml中的镜像标签修改为image: star7th/showdoc:arm-latest，就可以了

### 重现步骤

arm服务器，安装商店里的showdoc会失败

**Comment by wanghe-fit2cloud** [comment]
当前版本已经支持 arm 版本， 点击 `应用商店` 列表右上角的 `更新应用列表` 按钮，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/e089eaac-0fe3-4185-a14e-a902e35c5743)
