### ISSUE TITLE
[FEATURE] 升级页面也展示应用官网与文档相关链接

### ISSUE THREAD

**Issue by NHZEX** [1Panel-dev/1Panel#3259]
### 1Panel 版本

1.8.5

### 请描述您的需求或者改进建议

升级页面也展示应用安装页面显示的官网，文档，开源仓库等相关链接，便于直达升级日志。

![image](https://github.com/1Panel-dev/1Panel/assets/14545600/78cc4abb-bb08-4177-b4b4-70f4d1ca4c8c)

![image](https://github.com/1Panel-dev/1Panel/assets/14545600/c377712f-d7b0-4a29-9f37-c55409d3636b)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
