### ISSUE TITLE
[FEATURE]希望创建容器的时候可以设置可以设置cpu限制，内存限制，创建完成的容器也可追加此类限制

### ISSUE THREAD

**Issue by 52lemon6** [1Panel-dev/1Panel#326]
### 1Panel 版本

1.0.2

### 请描述您的需求或者改进建议

希望创建容器的时候可以设置cpu限制，内存限制，创建完成的容器也可追加此限制

**Comment by wanghe-fit2cloud** [comment]
当前版本中，创建容器时支持自定义 CPU 和内存限制：
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/46734380/226373430-2cbe6690-3825-426f-a9db-6307176e6df4.png">

**Comment by 52lemon6** [comment]
但是在应用商店里创建的docker不会有cpu限制和内存限制

**Comment by wanghe-fit2cloud** [comment]
> 但是在应用商店里创建的docker不会有cpu限制和内存限制

了解，后续版本支持。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
