### ISSUE TITLE
[FEATURE] 反向代理不能如nginx般配置

### ISSUE THREAD

**Issue by djy6257** [1Panel-dev/1Panel#3262]
### 1Panel 版本

v1.8.5

### 请描述您的需求或者改进建议

这是我的nginx的代理配置：
```
server {
    listen 80;
    server_name killerwhale.online;

    location /nacos {
        proxy_pass http://172.17.0.1:8848/nacos;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

```
在1Panel的控制台反向代理只能代理域名，不能向上述写法，能否添加上述配置写法

**Comment by Jameszyq** [comment]
你是想要不同的路由走不同的代理吗

**Comment by djy6257** [comment]
是的，比如我后端网关服务的端口是9111，我希望通过http://host/gateway/api,可以直接代理成host:9111，nginx上通过配置可以实现，但我想在1Panel的面板上也轻松实现&nbsp;


残夜．阳痕
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月11日(星期一) 中午12:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [1Panel-dev/1Panel] [FEATURE] 反向代理不能如nginx般配置 (Issue #3262)





 
你是想要不同的路由走不同的代理吗

**Comment by djy6257** [comment]
&nbsp;


残夜．阳痕
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月11日(星期一) 中午12:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [1Panel-dev/1Panel] [FEATURE] 反向代理不能如nginx般配置 (Issue #3262)





 
你是想要不同的路由走不同的代理吗

**Comment by Jameszyq** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/32665975/9f2976dd-d660-4e56-8845-d1400dbbccf1)
可以做到的，你可以在反向代理页面中，设置不同的路由走不同的代理

**Comment by Jameszyq** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/32665975/53b71d5e-6356-4470-a64b-16dd5ed5e592)
![image](https://github.com/1Panel-dev/1Panel/assets/32665975/b853330d-ae2f-45ed-ac36-910e0606bb87)

在网站目录下面点击红框中的按钮，会跳转到对应的配置目录下，在proxy目录中，每个反向代理都是一个配置文件，你可以找到你想要修改的那个，单独去编辑

**Comment by djy6257** [comment]
感谢，配置成功了




残夜．阳痕
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1Panel-dev/1Panel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月11日(星期一) 中午1:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [1Panel-dev/1Panel] [FEATURE] 反向代理不能如nginx般配置 (Issue #3262)





 
image.png (view on web)
 image.png (view on web)
 
在网站目录下面点击红框中的按钮，会跳转到对应的配置目录下，在proxy目录中，每个反向代理都是一个配置文件，你可以找到你想要修改的那个，单独去编辑
