### ISSUE TITLE
[FEATURE]菜单切换时，能不能把已经打开的菜单保存为tab的形式放在页面上

### ISSUE THREAD

**Issue by yshinu** [1Panel-dev/1Panel#3267]
### 1Panel 版本

1.8.5

### 请描述您的需求或者改进建议

菜单切换时，能不能把已经打开的菜单保存为tab的形式放在页面上，有时候打开终端然后再点击其他菜单后，在点击回终端就重新加载了，之前终端的信息就会消失。

### 请描述你建议的实现方案

组件keepalive的效果

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑是否支持上述需求。

**Comment by llanc** [comment]
我有相同的需求，考虑到这个isuue已经存在一段时间并且没有后续更新，所有我抽时间尝试进行了下这个需求的实现： #4510

**Comment by wanghe-fit2cloud** [comment]
> 我有相同的需求，考虑到这个isuue已经存在一段时间并且没有后续更新，所有我抽时间尝试进行了下这个需求的实现： #4510

手动点赞 👍

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
