### ISSUE TITLE
[BUG]建议使用 docker-compose config 来校验，而不是通过文件名，另外 Dockerfile 那也一样

### ISSUE THREAD

**Issue by BBchicken-9527** [1Panel-dev/1Panel#327]
### 1Panel 版本

1.0.0

### 问题描述

建议使用 docker-compose config 来校验，而不是通过文件名，另外 Dockerfile 那也一样
![image](https://user-images.githubusercontent.com/84372766/226365693-2c8deb86-f702-47af-a10c-cc55d6b1918f.png)

### 重现步骤

1

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本会支持优化。
