### ISSUE TITLE
[BUG]数据库同样的文件可以导入多次

### ISSUE THREAD

**Issue by hsjgit** [1Panel-dev/1Panel#3272]
### 1Panel 版本

v1.8.5-alpha.1

### 问题描述

数据库同样的文件可以导入多次

### 重现步骤

数据库---->导入备份----->选择一个文件导入(如果选择多个需要x掉多余的文件，只保留一个)----->上传
浏览器新开一个窗口
数据库---->导入备份----->选择一个文件导入(如果选择多个需要x掉多余的文件，只保留一个)----->上传
![image](https://github.com/1Panel-dev/1Panel/assets/32933584/94aeeb11-7719-4244-8d6e-303a26cea3f1)
<img width="720" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/32933584/c5c12217-21e1-4f6a-be6b-44cf8327f51c">

**Comment by ssongliu** [comment]
感谢反馈，这里操作是打开两个浏览器标签页，同时上传吗？复现了一下，如果是一个文件重复传会显示重复错误。
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/4cc82ba2-5095-4d8f-a064-b01554959d38)

**Comment by hsjgit** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/32933584/f7ed4dda-9508-440c-ba24-453a06ee2f3a)
只要打开两个窗口就可以同时上传同一个文件

**Comment by ssongliu** [comment]
> ![image](https://private-user-images.githubusercontent.com/32933584/289522855-f7ed4dda-9508-440c-ba24-453a06ee2f3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNTM1NzAsIm5iZiI6MTcwMjM1MzI3MCwicGF0aCI6Ii8zMjkzMzU4NC8yODk1MjI4NTUtZjdlZDRkZGEtOTUwOC00NDBjLWJhMjQtNDUzYTA2ZWUyZjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAzNTQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NTAyZjhhZTMzMGYyNTljMjVmYzg4ZTZmMzYwYzU5NjllZDMwNWJlNDNmNDY2NmU4YmQ4NmY2MzM2ZjhlNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SADsMLppk7enrekcKLA-G7PqhadTccCMnqIvof92QzE) 只要打开两个窗口就可以同时上传同一个文件

这个不太好管控，暂时不会支持，望理解。
