### ISSUE TITLE
[BUG] docker 容器升级问题

### ISSUE THREAD

**Issue by kangfenmao** [1Panel-dev/1Panel#3278]
### 联系方式

kangfenmao@qq.com

### 1Panel 版本

v1.8.5

### 问题描述

两个容器使用同样的编排模版的情况下，强制升级一个容器后，会导致另外一个容器升级界面中`目标镜像`丢失

### 重现步骤

1. 创建两个相同的编排模版，容器镜像 tag 都使用 latest
2. 两个容器全部都正常运行
3. 推送新的镜像到 DockerHub，tag 为 latest
4. 在容器列表，刚创建成功的2个容器，先点击菜单升级其中一个，勾选强制升级
5. 如下图所示
<img width="484" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/8253512/fb48c485-9029-41d9-9d4b-9000d3c24dd0">

6. 升级成功后，开始升级另外一个，另外一个目标镜像不再是 latest, 而是变成一个 hash
7. 点击升级，然后就会报错。同时容器丢失，刚刚创建的两个编排也只剩下一个了

### 期待的正确结果

1. 两个同样使用 username/image:latest 景象的容器都能够正常升级到最新的 latest tag
2. 升级镜像出错的情况下，编排列表项目不要丢失

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by okxlin** [comment]
正常情况，容器都用的同一个标签镜像，那么镜像id是相同的，拉取了新镜像，那么对应标签的镜像id就改变了

相当于两个房子基于同一个承重墙。

更新了一个，另外一个自然会丢失老镜像id而异常。重建就好了

**Comment by kangfenmao** [comment]
@okxlin 你说的这个很好理解，这就有了第二个问题。如果删除了一个容器后，对应的编排列表的条目就丢掉了，这会比较麻烦，需要手动再次添加那个 docker-compose 文件，然后生成容器。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
