### ISSUE TITLE
在地化工作有問題，繁體中文的翻譯全是錯的

### ISSUE THREAD

**Issue by Criskeyufon** [1Panel-dev/1Panel#3279]
### 1Panel 版本

1.8.5

### 请描述您的需求或者改进建议

提一嘴，你開發的這個管理後台要麼不提供繁體中文，要麼就把繁體中文的在地化翻譯做好。你是在簡體中文版的基礎上，用 Google 翻譯提供其它語言版本嗎？你看看繁體中文的遣詞造句，跟簡體中文是一樣的不？中國的開發者經常犯這種錯誤，天真地以為把簡體字換成繁體字就完事了，實際上港澳台沒這麼叫的，例如：

「數據庫」➡️「資料庫」
「面板」➡️「控制台」
「設置」➡️「設定」
「登錄」➡️「登入」
「證書」➡️「憑證」
「計畫任務」➡️「定時任務」
「賬戶」➡️「帳戶」
⋯⋯

要改的地方太多了，你自己好好檢查檢查，重新提供一份 zh-tw 的語系檔案吧。

<img width="975" alt="截圖 2023-12-12 02 15 47" src="https://github.com/1Panel-dev/1Panel/assets/48857142/98f55f97-7ef9-4888-a930-f5143413ef33">

**Comment by maninhill** [comment]
感谢您的建议。如果有可能，可否直接提 PR 来纠正我们的翻译问题？

**Comment by Mr-Ao-Dragon** [comment]
可以考虑直接用大模型直接翻译，用另一个大模型校对润色

**Comment by csthenry** [comment]
自己又不参与翻译工作，就别用命令式的语气！本就一个开源项目，本地化工作需要各国、各地区人员参与。

你身为港/澳/台本地人，自然对繁体而言是懂哥，那为什么自己不参与进来尽一份力，而不是丢下一句“要改的地方太多了，你自己好好檢查檢查，重新提供一份 zh-tw 的語系檔案吧。”这种命令语气？

跟老板命令员工似的，开源社区不欢迎这种人。

**Comment by Criskeyufon** [comment]
> 自己又不参与翻译工作，就别用命令式的语气！本就一个开源项目，本地化工作需要各国、各地区人员参与。
> 
> 你身为港/澳/台本地人，自然对繁体而言是懂哥，那为什么自己不参与进来尽一份力，而不是丢下一句“要改的地方太多了，你自己好好檢查檢查，重新提供一份 zh-tw 的語系檔案吧。”这种命令语气？
> 
> 跟老板命令员工似的，开源社区不欢迎这种人。

像你這種玻璃心就別出來做產品了！你作為開源專案的作者，你相當於產品經理，使用者相當於你的客戶，客戶在用你的產品時對你提出意見和批評是再正常不過的事情！別說是獨立開發者，就算是世界上的跨國大公司，他們開源出來的產品有難用的地方還不加以改進也會招來使用者的抱怨。你作為產品經理，不主動收集、整理和改進專案，反而本末倒置，在語氣上大作文章，你要是能把東西做好也是見了鬼！

**Comment by csthenry** [comment]
> > 自己又不参与翻译工作，就别用命令式的语气！本就一个开源项目，本地化工作需要各国、各地区人员参与。
> > 你身为港/澳/台本地人，自然对繁体而言是懂哥，那为什么自己不参与进来尽一份力，而不是丢下一句“要改的地方太多了，你自己好好檢查檢查，重新提供一份 zh-tw 的語系檔案吧。”这种命令语气？
> > 跟老板命令员工似的，开源社区不欢迎这种人。
> 
> 像你這種玻璃心就別出來做產品了！你作為開源專案的作者，你相當於產品經理，使用者相當於你的客戶，客戶在用你的產品時對你提出意見和批評是再正常不過的事情！別說是獨立開發者，就算是世界上的跨國大公司，他們開源出來的產品有難用的地方還不加以改進也會招來使用者的抱怨。你作為產品經理，不主動收集、整理和改進專案，反而本末倒置，在語氣上大作文章，你要是能把東西做好也是見了鬼！

首先，请你分清开源非盈利项目和商业产品。我不是1panel开发者，我的言论和1panel没有任何关系，单纯看你不爽，我也不是产品经理，我没有必要对你客客气气，我只是发表我自己的观点，同时希望你多去看看国内外开源项目，看看人家是怎么提issue，人家是怎么维护开源项目。

你最好能够在各大开源项目下以你同样经典的命令语气去提出你所谓的issue，我相信没有多少开发者会对你客气。

最后，也仅有企业会对你客气，把你当大爷。

提意见/建议很正常，但如果人人都只会在开源社区用一副高高在上的姿态指手画脚，且自己不出一份力，还满满戾气，优秀的开源作品只会越来越少，同时希望你别再污染开源环境。

**Comment by Criskeyufon** [comment]
> > > 自己又不参与翻译工作，就别用命令式的语气！本就一个开源项目，本地化工作需要各国、各地区人员参与。
> > > 你身为港/澳/台本地人，自然对繁体而言是懂哥，那为什么自己不参与进来尽一份力，而不是丢下一句“要改的地方太多了，你自己好好檢查檢查，重新提供一份 zh-tw 的語系檔案吧。”这种命令语气？
> > > 跟老板命令员工似的，开源社区不欢迎这种人。
> > 
> > 
> > 像你這種玻璃心就別出來做產品了！你作為開源專案的作者，你相當於產品經理，使用者相當於你的客戶，客戶在用你的產品時對你提出意見和批評是再正常不過的事情！別說是獨立開發者，就算是世界上的跨國大公司，他們開源出來的產品有難用的地方還不加以改進也會招來使用者的抱怨。你作為產品經理，不主動收集、整理和改進專案，反而本末倒置，在語氣上大作文章，你要是能把東西做好也是見了鬼！
> 
> 首先，请你分清开源非盈利项目和商业产品。我不是1panel开发者，我的言论和1panel没有任何关系，单纯看你不爽，我也不是产品经理，我没有必要对你客客气气，我只是发表我自己的观点，同时希望你多去看看国内外开源项目，看看人家是怎么提issue，人家是怎么维护开源项目。
> 
> 你最好能够在各大开源项目下以你同样经典的命令语气去提出你所谓的issue，我相信没有多少开发者会对你客气。
> 
> 最后，也仅有企业会对你客气，把你当大爷。
> 
> 提意见/建议很正常，但如果人人都只会在开源社区用一副高高在上的姿态指手画脚，且自己不出一份力，还满满戾气，优秀的开源作品只会越来越少，同时希望你别再污染开源环境。

我本來是給作者拋出了一個問題，結果你在這裡瞎參和！

我糾正一下，首先，我不是港澳台的人，你別看到繁體中文就把對方跟港澳台劃上等號。我本人做過國際化工作，瞭解過台灣那邊的習慣用語。其次，「我相信没有多少开发者会对你客气」這句話有依據嗎？我跟 GItHub 上的作者打過不少交道，那些真正牛逼的大佬，為人都很謙虛且低調，在後續的版本更新中採納了使用者的意見。反倒是你這樣的半吊子經常在 issue 的時間線上製造一些令人不爽的聲音！再次，優秀的開源作品跟提意見的方式沒有任何關係。國內有個 GitHub 仿品叫「Gitee」，但是受中共的審查制度的影響，Gitee 上就算完全沒有像我這樣的人，它上面的優秀開源作品也不可能多到哪裡去，這是大環境使然。優秀作品的多寡，不在乎提意見的方式，而在於這個社群是否足夠自由、開放和包容。

最後強調一遍：issue 是用來討論產品問題的，不是來打口水仗的！我不是人民幣，沒有必要讓所有人都看得順眼。你要是看不慣，可以不看，眼不見心不煩！我不想在 issue 的時間線上再看到你這樣的留言，你這樣的使用者就跟國內的小粉紅一樣，不僅玻璃心，而且喜歡到處引戰，張嘴討人嫌。我提 issue，是因為看好這個專案的發展前景，希望作者儘早糾正產品中存在的問題，使其更臻完美。怎麼我提出問題反倒「污染開源環境」了，你說話有腦子嗎？

**Comment by csthenry** [comment]
> > > > 自己又不参与翻译工作，就别用命令式的语气！本就一个开源项目，本地化工作需要各国、各地区人员参与。
> > > > 你身为港/澳/台本地人，自然对繁体而言是懂哥，那为什么自己不参与进来尽一份力，而不是丢下一句“要改的地方太多了，你自己好好檢查檢查，重新提供一份 zh-tw 的語系檔案吧。”这种命令语气？
> > > > 跟老板命令员工似的，开源社区不欢迎这种人。
> > > 
> > > 
> > > 像你這種玻璃心就別出來做產品了！你作為開源專案的作者，你相當於產品經理，使用者相當於你的客戶，客戶在用你的產品時對你提出意見和批評是再正常不過的事情！別說是獨立開發者，就算是世界上的跨國大公司，他們開源出來的產品有難用的地方還不加以改進也會招來使用者的抱怨。你作為產品經理，不主動收集、整理和改進專案，反而本末倒置，在語氣上大作文章，你要是能把東西做好也是見了鬼！
> > 
> > 
> > 首先，请你分清开源非盈利项目和商业产品。我不是1panel开发者，我的言论和1panel没有任何关系，单纯看你不爽，我也不是产品经理，我没有必要对你客客气气，我只是发表我自己的观点，同时希望你多去看看国内外开源项目，看看人家是怎么提issue，人家是怎么维护开源项目。
> > 你最好能够在各大开源项目下以你同样经典的命令语气去提出你所谓的issue，我相信没有多少开发者会对你客气。
> > 最后，也仅有企业会对你客气，把你当大爷。
> > 提意见/建议很正常，但如果人人都只会在开源社区用一副高高在上的姿态指手画脚，且自己不出一份力，还满满戾气，优秀的开源作品只会越来越少，同时希望你别再污染开源环境。
> 
> 我本來是給作者拋出了一個問題，結果你在這裡瞎參和！
> 
> 我糾正一下，首先，我不是港澳台的人，你別看到繁體中文就把對方跟港澳台劃上等號。我本人做過國際化工作，瞭解過台灣那邊的習慣用語。其次，「我相信没有多少开发者会对你客气」這句話有依據嗎？我跟 GItHub 上的作者打過不少交道，那些真正牛逼的大佬，為人都很謙虛且低調，在後續的版本更新中採納了使用者的意見。反倒是你這樣的半吊子經常在 issue 的時間線上製造一些令人不爽的聲音！再次，優秀的開源作品跟提意見的方式沒有任何關係。國內有個 GitHub 仿品叫「Gitee」，但是受中共的審查制度的影響，Gitee 上就算完全沒有像我這樣的人，它上面的優秀開源作品也不可能多到哪裡去，這是大環境使然。優秀作品的多寡，不在乎提意見的方式，而在於這個社群是否足夠自由、開放和包容。
> 
> 最後強調一遍：issue 是用來討論產品問題的，不是來打口水仗的！我不是人民幣，沒有必要讓所有人都看得順眼。你要是看不慣，可以不看，眼不見心不煩！我不想在 issue 的時間線上再看到你這樣的留言，你這樣的使用者就跟國內的小粉紅一樣，不僅玻璃心，而且喜歡到處引戰，張嘴討人嫌。我提 issue，是因為看好這個專案的發展前景，希望作者儘早糾正產品中存在的問題，使其更臻完美。怎麼我提出問題反倒「污染開源環境」了，你說話有腦子嗎？

爬远一点吧，别来污染我的邮箱了，我确实错了，因为和素质低下的人讲道理本身就是一件错误的事情捏，乐。
就你一个仓库空空的人《“8 contributions in the last year”》，还和github大佬打交道，乐死我了，不知道是哪里来的小屁孩，我也没义务替别人管教。
《自由、開放和包容》不是你出言不逊的理由😅

**Comment by 60999** [comment]
能动手别吵吵，上手改啊，提交issues啊

**Comment by W4J1e** [comment]
开源项目本身就是用爱发电，提需求和反馈 bug 是帮助项目进步，这无可厚非。
但是用命令的口吻去要求开发者，确实是一种很失礼的行为。
我接触网络之初就看到各种论坛和社群强调《提问的艺术》，虽然你不是提问，
但是我仍建议（噢，我希望）你去学一学。

**Comment by QAQ000000** [comment]
免费产品都没收你钱还在这里狗叫

> > > 自己又不参与翻译工作，就别用命令式的语气！本就一个开源项目，本地化工作需要各国、各地区人员参与。
> > > 你身为港/澳/台本地人，自然对繁体而言是懂哥，那为什么自己不参与进来尽一份力，而不是丢下一句“要改的地方太多了，你自己好好檢查檢查，重新提供一份 zh-tw 的語系檔案吧。”这种命令语气？
> > > 跟老板命令员工似的，开源社区不欢迎这种人。
> > 
> > 
> > 像你這種玻璃心就別出來做產品了！你作為開源專案的作者，你相當於產品經理，使用者相當於你的客戶，客戶在用你的產品時對你提出意見和批評是再正常不過的事情！別說是獨立開發者，就算是世界上的跨國大公司，他們開源出來的產品有難用的地方還不加以改進也會招來使用者的抱怨。你作為產品經理，不主動收集、整理和改進專案，反而本末倒置，在語氣上大作文章，你要是能把東西做好也是見了鬼！
> 
> 首先，请你分清开源非盈利项目和商业产品。我不是1panel开发者，我的言论和1panel没有任何关系，单纯看你不爽，我也不是产品经理，我没有必要对你客客气气，我只是发表我自己的观点，同时希望你多去看看国内外开源项目，看看人家是怎么提issue，人家是怎么维护开源项目。
> 
> 你最好能够在各大开源项目下以你同样经典的命令语气去提出你所谓的issue，我相信没有多少开发者会对你客气。
> 
> 最后，也仅有企业会对你客气，把你当大爷。
> 
> 提意见/建议很正常，但如果人人都只会在开源社区用一副高高在上的姿态指手画脚，且自己不出一份力，还满满戾气，优秀的开源作品只会越来越少，同时希望你别再污染开源环境。

本身就是免费产品，谁有义务帮你本地化？😅

**Comment by Anyexyz** [comment]
> > > > 自己又不参与翻译工作，就别用命令式的语气！本就一个开源项目，本地化工作需要各国、各地区人员参与。
> > > > 你身为港/澳/台本地人，自然对繁体而言是懂哥，那为什么自己不参与进来尽一份力，而不是丢下一句“要改的地方太多了，你自己好好檢查檢查，重新提供一份 zh-tw 的語系檔案吧。”这种命令语气？
> > > > 跟老板命令员工似的，开源社区不欢迎这种人。
> > > 
> > > 
> > > 像你這種玻璃心就別出來做產品了！你作為開源專案的作者，你相當於產品經理，使用者相當於你的客戶，客戶在用你的產品時對你提出意見和批評是再正常不過的事情！別說是獨立開發者，就算是世界上的跨國大公司，他們開源出來的產品有難用的地方還不加以改進也會招來使用者的抱怨。你作為產品經理，不主動收集、整理和改進專案，反而本末倒置，在語氣上大作文章，你要是能把東西做好也是見了鬼！
> > 
> > 
> > 首先，请你分清开源非盈利项目和商业产品。我不是1panel开发者，我的言论和1panel没有任何关系，单纯看你不爽，我也不是产品经理，我没有必要对你客客气气，我只是发表我自己的观点，同时希望你多去看看国内外开源项目，看看人家是怎么提issue，人家是怎么维护开源项目。
> > 你最好能够在各大开源项目下以你同样经典的命令语气去提出你所谓的issue，我相信没有多少开发者会对你客气。
> > 最后，也仅有企业会对你客气，把你当大爷。
> > 提意见/建议很正常，但如果人人都只会在开源社区用一副高高在上的姿态指手画脚，且自己不出一份力，还满满戾气，优秀的开源作品只会越来越少，同时希望你别再污染开源环境。
> 
> 我本來是給作者拋出了一個問題，結果你在這裡瞎參和！
> 
> 我糾正一下，首先，我不是港澳台的人，你別看到繁體中文就把對方跟港澳台劃上等號。我本人做過國際化工作，瞭解過台灣那邊的習慣用語。其次，「我相信没有多少开发者会对你客气」這句話有依據嗎？我跟 GItHub 上的作者打過不少交道，那些真正牛逼的大佬，為人都很謙虛且低調，在後續的版本更新中採納了使用者的意見。反倒是你這樣的半吊子經常在 issue 的時間線上製造一些令人不爽的聲音！再次，優秀的開源作品跟提意見的方式沒有任何關係。國內有個 GitHub 仿品叫「Gitee」，但是受中共的審查制度的影響，Gitee 上就算完全沒有像我這樣的人，它上面的優秀開源作品也不可能多到哪裡去，這是大環境使然。優秀作品的多寡，不在乎提意見的方式，而在於這個社群是否足夠自由、開放和包容。
> 
> 最後強調一遍：issue 是用來討論產品問題的，不是來打口水仗的！我不是人民幣，沒有必要讓所有人都看得順眼。你要是看不慣，可以不看，眼不見心不煩！我不想在 issue 的時間線上再看到你這樣的留言，你這樣的使用者就跟國內的小粉紅一樣，不僅玻璃心，而且喜歡到處引戰，張嘴討人嫌。我提 issue，是因為看好這個專案的發展前景，希望作者儘早糾正產品中存在的問題，使其更臻完美。怎麼我提出問題反倒「污染開源環境」了，你說話有腦子嗎？

首先作为一名用户，我承认，一个开源产品要是想要提供多语言确实应该把翻译做好，但是这是基于开源社区贡献而来的，您要是嫌弃 1panel 的本地化做的不好，请自己提 Pr 或者邀请别的大佬来做翻译，自己不愿意贡献，那么就请自己开原版的简体中文看。🫥

**Comment by TIkc9** [comment]
绿蛙 你来这叫个毛啊 有本事自己开发嘛  没本事给爱用用 不用就走 这是你们notepad++开发者的态度 不是吗？ 井底之蛙
