### ISSUE TITLE
[FEATURE]希望在首页添加 重启服务器 重启面板 按钮

### ISSUE THREAD

**Issue by rise9** [1Panel-dev/1Panel#328]
### 1Panel 版本

1

### 请描述您的需求或者改进建议

在首页添加 重启服务器 重启面板 按钮

### 请描述你建议的实现方案

easy

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
