### ISSUE TITLE
[FEATURE] 第三方备份账号里任意文件下载功能

### ISSUE THREAD

**Issue by loccen** [1Panel-dev/1Panel#3280]
### 1Panel 版本

1.8.5

### 请描述您的需求或者改进建议

目前第三方备份账号里的文件，只有通过计划任务或者面板快照备份的文件才能进行下载恢复，无法直接使用第三方账号里的其他文件。比如这样的场景：A主机备份了一个应用X到了OneDriver，我如果需要迁移到B主机上，需要在A主机或者OneDriver上将备份压缩包下载到本地，再上传到B主机上进行还原。还有各种其他非典型场景的数据迁移，如果本地是弱网环境，这个过程会非常痛苦。所以希望能实现第三方备份账号的任意备份文件下载，导入，还原的功能。

### 请描述你建议的实现方案

![image](https://github.com/1Panel-dev/1Panel/assets/20043494/a69a7552-01f8-46b9-8003-97679cd0014f)
计划任务里添加类似的“导入”任务，指定备份账号和本地路径以及备份账号中的目录/文件名。
另外，有些任务可能是一次性的，或者不希望当前立即执行，因此还希望在计划任务创建时，支持corn表达式，另外添加两个复选框，可以选择是否立即执行，是否仅执行一次。

**Comment by wanghe-fit2cloud** [comment]
感谢你的建议，我们会在后续版本持续优化。

**Comment by ssongliu** [comment]
应用商店里有一个 zfile 应用，可以管理 1panel 内所有第三方备份账号内容，可以通过他下载然后导入备份恢复。

**Comment by loccen** [comment]
> 应用商店里有一个 zfile 应用，可以管理 1panel 内所有第三方备份账号内容，可以通过他下载然后导入备份恢复。

好的，我试试

**Comment by wanghe-fit2cloud** [comment]
经讨论，我们暂无支持上述需求的计划，望理解。
