### ISSUE TITLE
[BUG] 安装了 OpenLiteSpeed 服务器依然提示我安装 OpenResty

### ISSUE THREAD

**Issue by realstephenzhao** [1Panel-dev/1Panel#3289]
### 1Panel 版本

v1.8.5

### 问题描述

1Panel 商店里面有两种服务器，我选择了安装 OpenLiteSpeed。

但是 1Panel 的网站模块依然提示「未检测到 OpenResty ,请进入应用商店点击安装!」,而这是不可能的。因为 OpenResty 同样需要使用 80/443端口，安装会提示冲突。

请问如何解决？这是 bug 吗？

### 重现步骤

1. 纯净 Ubuntu 22.04 安装 1Panel 并进入
2. 在 1Panel 商店内安装 OpenLiteSpeed
3. 进入左侧的网站模块下的网站选项，会发现提示「未检测到 OpenResty ,请进入应用商店点击安装!」

### 期待的正确结果

OLS 服务器应当可以独立使用，而非依赖 OpenResty。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1Panel 的网站功能是要强绑定 OpenResty 应用。
> 安装 OpenResty 时支持用户自定义端口，这样， OpenLiteSpeed 就可以使用 80/443 端口。

**Comment by realstephenzhao** [comment]
> 感谢反馈。 1Panel 的网站功能是要强绑定 OpenResty 应用。
> 
> > 安装 OpenResty 时支持用户自定义端口，这样， OpenLiteSpeed 就可以使用 80/443 端口。

@wanghe-fit2cloud 但是这种情况怎么办呢？共存，如何共存？ 宝塔/aaPanel 以及 CyberPanel 都可以独立使用 OpenLiteSpeed 服务器的。

**Comment by realstephenzhao** [comment]
本来要使用 OLS 服务器就是为了它的速度和 WP 缓存 插件，如果还来一个 OpenResty 不是虚耗服务器资源吗，那么支持 OLS 还有什么意义？

**Comment by wanghe-fit2cloud** [comment]
> 但是这种情况怎么办呢？共存，如何共存？

当前满足不了这种情况，如果要使用 1Panel 的网站功能，就需要强制安装 OpenResty。

> 可以使用容器菜单来容器化运行你自己的服务（不通过 `网站` - `运行环境` 功能），之后通过 OpenLiteSpeed 来管理。

**Comment by realstephenzhao** [comment]
> > 但是这种情况怎么办呢？共存，如何共存？
> 
> 当前满足不了这种情况，如果要使用 1Panel 的网站功能，就需要强制安装 OpenResty。
> 
> > 可以使用容器菜单来容器化运行你自己的服务（不通过 `网站` - `运行环境` 功能），之后通过 OpenLiteSpeed 来管理。

很可惜，如果最终还要通过 OpenLiteSpeed Admin Panel 来管理，那么使用 1Panel 面板的便利性几乎就没有了。
