### ISSUE TITLE
[BUG]计划任务备份所有数据库显示成功，但没有生成备份文件，下载报错。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3290]
### 1Panel 版本

v1.8.5

### 问题描述

在计划任务中备份所有数据库到服务器磁盘或者SFTP都显示成功，但是没有任务输出，且下载备份文件失败，显示备份路径[]错误，无法下载！
但系统快照却能正常备份到同一个SFTP，也能正常生成备份文件。

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/93708226/12f35435-0462-4c5e-aea1-2df002793e8b)
![image](https://github.com/1Panel-dev/1Panel/assets/93708226/b2771baa-f704-4b81-8d40-da855384788d)
![image](https://github.com/1Panel-dev/1Panel/assets/93708226/a2ec7d33-a9ec-4b56-bd44-b43bd06fd486)
![image](https://github.com/1Panel-dev/1Panel/assets/93708226/0515b42f-79ae-4332-ba6b-3eace9000e09)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
备份数据库时选择 `所有`，我们会给每一个数据库单独生成一份备份文件，所以就需要到数据库列表找到目标数据库，然后点击 `备份列表` 按钮来下载备份文件。

> 下个版本我们会针对上述问题作出优化。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
