### ISSUE TITLE
[BUG]自动关闭ssh无法开启

### ISSUE THREAD

**Issue by TtBJSH** [1Panel-dev/1Panel#3292]
### 联系方式

ttbjsht@163.com

### 1Panel 版本

1.8.5

### 问题描述

面板自动关闭ssh并且无法重新启动

### 重现步骤

重装的新版本

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/46512682/b346f935-08de-4777-8044-628796624b0d)

**Comment by ssongliu** [comment]
感谢反馈，这里是重启 ssh 服务的时候超时吗？可以截图看一下下面命令的返回信息：
1. systemctl restart sshd 
2. systemctl status sshd

**Comment by TtBJSH** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/46512682/f20e9f2e-a9df-46de-affb-c802bf5c127a)


> 感谢反馈，这里是重启 ssh 服务的时候超时吗？可以截图看一下下面命令的返回信息：
> 
> 1. systemctl 重新启动 sshd
> 2. systemctl 状态 sshd
![image](https://github.com/1Panel-dev/1Panel/assets/46512682/6a909b54-41ba-4b5f-8958-6485451d0a50)

**Comment by ssongliu** [comment]
看起来状态是正常的，那个请求超时是什么操作的的时候出现的呢？

**Comment by TtBJSH** [comment]
> 看起来状态是正常的，那个请求超时是什么操作的时候出现的呢？

1panel面板点击开启ssh按钮就会报错或超时

**Comment by ssongliu** [comment]
> > 看起来状态是正常的，那个请求超时是什么操作的时候出现的呢？
> 
> 1panel面板点击开启ssh按钮就会报错或超时

点击重启按钮的时候超时吗

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布，建议升级到最新版本后再复现一下上述问题。
