### ISSUE TITLE
[FEATURE] 增加不同主机文件管理

### ISSUE THREAD

**Issue by zxwmfcm** [1Panel-dev/1Panel#3293]
### 1Panel 版本

1.8.5

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/30642864/fcf241c5-d618-4a6f-a5c3-13eb584e3858)
这里加个文件管理吧  可以切换不同主机操作不同主机文件

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。在后续版本中我们可能会考虑支持多主机管理功能。
目前，您可以使用 [JumpServer](https://github.com/jumpserver/jumpserver) 来管理多台主机实现上述需求。
