### ISSUE TITLE
[FEATURE]切换openregistry的镜像发行版

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [1Panel-dev/1Panel#3294]
### 1Panel 版本

v1.8.5

### 请描述您的需求或者改进建议

将openregistry从focal切换到alpine，可以有效优化占用和镜像大小

### 请描述你建议的实现方案

直接做一个新版本，将tag后面的focal换成alpine可直接搞定

**Comment by okxlin** [comment]
alpine镜像是小很多，但是支持的架构平台没有focal版本多。

**Comment by zhengkunwang223** [comment]
楼上说的对 如果想用 alpine 版本，可以手动编辑应用的 docker-compose.yml 文件
