### ISSUE TITLE
[BUG] 无路径打开后台，先出现网页内容，再出现”无权访问“

### ISSUE THREAD

**Issue by BlueNoob** [1Panel-dev/1Panel#3296]
### 1Panel 版本

v1.8.5

### 问题描述
先出现网页内容，再出现”无权访问“，逻辑判断有问题。
你们网页不卡的话可能无感知，建议跟一下代码。

### 先
![1702393431486](https://github.com/1Panel-dev/1Panel/assets/4169222/8b19a733-347b-41b0-937a-84342dff9b3a)
### 后
![image](https://github.com/1Panel-dev/1Panel/assets/4169222/77540e1a-6dca-4dc5-8c4f-4ca43a559cd5)

**Comment by 9a6c** [comment]
我也经常遇到这个问题， 一闪而过

**Comment by zhengkunwang223** [comment]
感谢反馈 后续版本优化

**Comment by danger-dream** [comment]
权限是前端判断的。。得在后端验证地址才能无感知

**Comment by wanghe-fit2cloud** [comment]
最新版本已优化。
