### ISSUE TITLE
[FEATURE]文件管理页面使用鼠标侧键返回上一个目录

### ISSUE THREAD

**Issue by xinyihl** [1Panel-dev/1Panel#3303]
### 1Panel 版本

1.9.0

### 请描述您的需求或者改进建议

目前使用鼠标侧键返回会返回上一个页面，
期望使用鼠标侧键返回上一个访问的目录，当没有上一个访问的目录时返回上一层目录。

**Comment by zhengkunwang223** [comment]
”返回上一个访问的目录“ 是什么意思？文件页面？

**Comment by xinyihl** [comment]
就比如我现在的目录是 \a\b\ 然后我打开了 \d\c\ 可以返回到我刚刚访问的 \a\b\

**Comment by zhengkunwang223** [comment]
> 就比如我现在的目录是 \a\b\ 然后我打开了 \d\c\ 可以返回到我刚刚访问的 \a\b\

这个实现不了
