### ISSUE TITLE
ipv6 only的vps在应用商店安装应用后用“IP+端口”访问不了，如何解决[QUESTION]

### ISSUE THREAD

**Issue by softmetal66** [1Panel-dev/1Panel#3304]
### 请描述您的问题

看到最新的版本支持应用监听ipv6，但尝试在ipv6 only的vps在应用商店安装应用，安装成功后用“IP+端口”访问不了，如何解决
![image](https://github.com/1Panel-dev/1Panel/assets/112331657/e6dea53c-f12f-44a3-9eee-a908120941c7)

**Comment by softmetal66** [comment]
安装了好几个软件，点击跳转都打不开
已经在面板设置中把服务器地址设为了vps的ipv6地址
![image](https://github.com/1Panel-dev/1Panel/assets/112331657/321297db-60cf-410c-99f9-3deaa2d31d9f)

**Comment by ssongliu** [comment]
感谢反馈，容器配置界面配置完 ipv6 之后，需要重建 1panel-network，勾选上 ipv6，并且正常访问的话，需要客户端也支持 ipv6。
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/584514c9-1d3d-41fb-bf0c-50c20f5dd3bd)

**Comment by wozaitianwai** [comment]
ipv4也不行，但是不通过面板直接去创建docker就行，也不知道怎么查哪里出问题了

**Comment by ssongliu** [comment]
> ipv4也不行，但是不通过面板直接去创建docker就行，也不知道怎么查哪里出问题了

麻烦加一下我，我看一下这个问题
<img src="https://github.com/1Panel-dev/1Panel/assets/73214554/13314235-ef8f-474b-8694-11064bf85cd9" width="186px" height="156px">

**Comment by wozaitianwai** [comment]
> > ipv4也不行，但是不通过面板直接去创建docker就行，也不知道怎么查哪里出问题了
> 
> 麻烦加一下我，我看一下这个问题 <img alt="" width="186px" height="156px" src="https://private-user-images.githubusercontent.com/73214554/290161115-13314235-ef8f-474b-8694-11064bf85cd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjU4NDIsIm5iZiI6MTcwMjUyNTU0MiwicGF0aCI6Ii83MzIxNDU1NC8yOTAxNjExMTUtMTMzMTQyMzUtZWY4Zi00NzRiLTg2OTQtMTEwNjRiZjg1Y2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAzNDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3M2I4MzRkNmRlMDgyNDY1YmQ4NGEwMTdiOTYzNzgyYzNmYzNkYjNkYjk4YmFkODEzZWMyOWExZDZhMDVmNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oI-TcPbhUzWFo4-KuWBfORY1zcxGs_uOYDxcfSb95U8">

趁着午间reboot了下服务器，OK了……

**Comment by everett7623** [comment]
增加ipv6我们搞不定啊，设置，建议说明文档再详细一些，操作，或者更新一下适配。
