### ISSUE TITLE
日志审计模块建议添加个记录导出功能

### ISSUE THREAD

**Issue by ziweiyang20** [1Panel-dev/1Panel#3306]
### 1Panel 版本

v1.9

### 请描述您的需求或者改进建议

日志审计建议添加个导出功能，导出为excel文件

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
日志审计导出日志相关需求，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/3496
