### ISSUE TITLE
[1.9.0] 不要硬编码忽略证书验证选项

### ISSUE THREAD

**Issue by NHZEX** [1Panel-dev/1Panel#3307]
### 1Panel 版本

1.9.0

### 请描述您的需求或者改进建议

关于 PR #3188

应该在UI中给出可选项，硬编码忽略验证有中间人攻击的风险，同时这种风险应该给予明确提示

**Comment by zhengkunwang223** [comment]
感谢建议 后续小版本增加此选项

**Comment by wanghe-fit2cloud** [comment]
v1.9.1 版本已发布。
