### ISSUE TITLE
[QUESTION]是否会添加对华为Euler OS 支持

### ISSUE THREAD

**Issue by ECeternalcat** [1Panel-dev/1Panel#3308]
### 请描述您的问题

目前我在华为云上购买了一台云服务器，尝试部署贵面板时收到了不支持的提示
ERROR: Unsupported distribution 'hce'

[1Panel Log]: ... 启动 docker
Failed to enable unit: Unit file docker.service does not exist.
Failed to start docker.service: Unit docker.service not found.
[1Panel Log]: docker 安装失败

请问是否会添加对Euler OS 的支持？

**Comment by okxlin** [comment]
凑合先手动安装docker和docker-compose环境

或可尝试以下脚本安装初期环境

```
bash <(curl -sSL https://linuxmirrors.cn/docker.sh)
```

```
bash <(wget -qO- --no-check-certificate https://mirror.ghproxy.com/https://github.com/okxlin/ToolScript/raw/main/tools/vps-setup.sh)
````

**Comment by ECeternalcat** [comment]
> 凑合先手动安装docker和docker-compose环境
> 
> 或可尝试以下脚本安装初期环境
> 
> ```
> bash <(curl -sSL https://linuxmirrors.cn/docker.sh)
> ```
> 
> ```
> bash <(wget -qO- --no-check-certificate https://mirror.ghproxy.com/https://github.com/okxlin/ToolScript/raw/main/tools/vps-setup.sh)
> ```

这两个脚本在Euler上运行失败
提示如下：
[root@hcss-ecs-932e ~]# bash <(curl -sSL https://linuxmirrors.cn/docker.sh)

[ERROR] 无法判断当前运行环境，当前系统不在本脚本的支持范围内

[root@hcss-ecs-932e ~]# https://mirror.ghproxy.com/https://github.com/okxlin/ToolScript/raw/main/tools/vps-setup.sh)
-bash: syntax error near unexpected token `)'

我先手动安装试试

**Comment by Anyexyz** [comment]
Euler不在docker官方脚本的支持列表里，得自己装下docker

**Comment by swRains** [comment]
华为的东西到处魔改不兼容很正常，改操作系统就行了

**Comment by GentsunCheng** [comment]
无特殊需求不建议使用各大云厂商的Linux发行版本

**Comment by Anyexyz** [comment]
https://www.anye.xyz/archives/1706504406639
参考这个安装 @ECeternalcat
