### ISSUE TITLE
[BUG] ssh 登陆日志展示有错

### ISSUE THREAD

**Issue by W4J1e** [1Panel-dev/1Panel#3309]
### 1Panel 版本

1.9.0

### 问题描述

在日志审计里，登录日志，“所有”状态下对最近的登陆显示不全；在失败的状态下，ip 内容下可能会显示用户登陆的“用户名”，归属地为空，用户下显示 invalid 。
![image](https://github.com/1Panel-dev/1Panel/assets/74824162/47f12480-4377-4753-b120-269b2ed3571b)

### 重现步骤

日志审计——登录日志——状态选择“失败”

### 期待的正确结果

期待正确显示 ip 归属地和用户名等信息。

### 附加信息

确定错误把登陆用户名显示为 ip 是因为我请朋友测试 fail2ban 的拦截，他说登陆的用户名是 “suiyue”，虽然在“所有”状态下没有他的登陆记录，但是日志文件里能找到，且正确触发了 fail2ban 的拦截规则。

**Comment by ssongliu** [comment]
感谢反馈，是什么操作系统？麻烦提供一下 /var/log/secure 或者 /var/log/auth.log 文件

**Comment by 9a6c** [comment]
> 感谢反馈，是什么操作系统？麻烦提供一下 /var/log/secure 或者 /var/log/auth.log 文件

我的是ubuntu，也出现了这个

**Comment by W4J1e** [comment]
> 感谢反馈，是什么操作系统？麻烦提供一下 /var/log/secure 或者 /var/log/auth.log 文件

debian 11.3，日志文件是直接上传在这里吗还是发送到邮箱里呢？

**Comment by ssongliu** [comment]
> > 感谢反馈，是什么操作系统？麻烦提供一下 /var/log/secure 或者 /var/log/auth.log 文件
> 
> debian 11.3，日志文件是直接上传在这里吗还是发送到邮箱里呢？

发我邮箱吧，里面可能有些敏感信息 liu.song@fit2cloud.com

**Comment by ssongliu** [comment]
> > 感谢反馈，是什么操作系统？麻烦提供一下 /var/log/secure 或者 /var/log/auth.log 文件
> 
> 我的是ubuntu，也出现了这个

ubuntu 什么版本，20.04 没有复现这个问题

**Comment by W4J1e** [comment]
> > > 感谢反馈，是什么操作系统？麻烦提供一下 /var/log/secure 或者 /var/log/auth.log 文件
> > 
> > 
> > debian 11.3，日志文件是直接上传在这里吗还是发送到邮箱里呢？
> 
> 发我邮箱吧，里面可能有些敏感信息 [liu.song@fit2cloud.com](mailto:liu.song@fit2cloud.com)

已发，谢谢

**Comment by ssongliu** [comment]
> > > > 感谢反馈，是什么操作系统？麻烦提供一下 /var/log/secure 或者 /var/log/auth.log 文件
> > > 
> > > 
> > > debian 11.3，日志文件是直接上传在这里吗还是发送到邮箱里呢？
> > 
> > 
> > 发我邮箱吧，里面可能有些敏感信息 [liu.song@fit2cloud.com](mailto:liu.song@fit2cloud.com)
> 
> 已发，谢谢

👌收到

**Comment by 9a6c** [comment]
> > > 感谢反馈，是什么操作系统？麻烦提供一下 /var/log/secure 或者 /var/log/auth.log 文件
> > 
> > 
> > 我的是ubuntu，也出现了这个
> 
> ubuntu 什么版本，20.04 没有复现这个问题

我的是 ubuntu-22.04

**Comment by ssongliu** [comment]
找到问题了，v1.9.1 版本修复。

**Comment by W4J1e** [comment]
> 找到问题了，v1.9.1 版本修复。

辛苦了。

**Comment by wanghe-fit2cloud** [comment]
v1.9.1 版本已发布。
