### ISSUE TITLE
[FEATURE]应用守护和应用管理，类似supervisor

### ISSUE THREAD

**Issue by bugstark** [1Panel-dev/1Panel#331]
### 1Panel 版本

1.02

### 请描述您的需求或者改进建议

不通过docker原生运行的程序，希望可以提供管理面板，类似bt的进程守护管理器（supervisor）

**Comment by zhengkunwang223** [comment]
感谢建议，后续版本支持

**Comment by Mr-Ao-Dragon** [comment]
可以做一个systemd前端接口来实现。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
