### ISSUE TITLE
[BUG] 应用商店 分类header 长度

### ISSUE THREAD

**Issue by BlueNoob** [1Panel-dev/1Panel#3310]
### 1Panel 版本

1.9.0

### 问题描述

![1702474165860](https://github.com/1Panel-dev/1Panel/assets/4169222/a9b6c758-4b20-498c-bc0f-b344ac8249fe)
如图，这部分还有空间的，但是折叠进下拉框了

### 重现步骤

1

**Comment by wanghe-fit2cloud** [comment]
是这样的，我们目前是固定了 6 种应用标签，其余的分类都统一放到了下拉列表中。
