### ISSUE TITLE
[BUG] 通过1Panel创建的koishi无法访问

### ISSUE THREAD

**Issue by Q2297045667** [1Panel-dev/1Panel#3311]
### 1Panel 版本

1.9.0

### 问题描述

通过1Panel创建的koishi无法访问
安装时的应用配置
![image](https://github.com/1Panel-dev/1Panel/assets/42416195/2b372303-9ae6-4eaa-80b2-39b430751f6d)

### 重现步骤

通过1Panel安装的koishi

### 期待的正确结果

正常通过IP:5140访问

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by Q2297045667** [comment]
> 感谢反馈，我们先在本地环境复现一下上述问题。

感谢回复

**Comment by Zeta-ZhaoLi** [comment]
我也遇到了，日志里显示部署好了，但是无法访问

**Comment by wanghe-fit2cloud** [comment]
> 我也遇到了，日志里显示部署好了，但是无法访问

Koishi 官方刚刚发布了最新版本镜像：koishijs/koishi:v1.13.2
> 目前可以编辑镜像版本来手动升级，我们稍后就会推送更新。

**Comment by wanghe-fit2cloud** [comment]
Koishi 官网已经推送了最新版本 v1.13.2，我们刚刚也适配完成。
目前可以卸载原已安装应用，然后手动更新应用商店应用后再来安装最新版本，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/1449a67c-2e2b-44e7-871c-c7ecd583c517)
