### ISSUE TITLE
[BUG] v1.9.0怎么把日志审计-登录日志-统计信息菜单干没了

### ISSUE THREAD

**Issue by jaychoubaby** [1Panel-dev/1Panel#3312]
### 1Panel 版本

v1.9.0

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/26641387/5311ff5a-054b-4c05-8c86-b9e83671f7db)
![image](https://github.com/1Panel-dev/1Panel/assets/26641387/d10b313a-2130-4d5d-a559-5b669b8f1933)

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/26641387/06cb1502-39dc-4ac5-a484-126bd9aedce9)

### 期待的正确结果

这功能挺好用的啊，咋给整没了，希望恢复

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本新增了 Fail2ban 管理功能，可以进入 `工具箱` 页面，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/bcaeee50-7f20-4776-892b-4954c2d09382)

> 配置好规则后自动管理。

**Comment by jaychoubaby** [comment]
> v1.9.0 版本新增了 Fail2ban 管理功能，可以进入 `工具箱` 页面，如图： ![image](https://private-user-images.githubusercontent.com/46734380/290380028-bcaeee50-7f20-4776-892b-4954c2d09382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjEyODgsIm5iZiI6MTcwMjUyMDk4OCwicGF0aCI6Ii80NjczNDM4MC8yOTAzODAwMjgtYmNhZWVlNTAtN2YyMC00Nzc2LTg5MmItNDk1NGMyZDA5MzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAyMjk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1Y2EyMTg5MzUxNmU3MjgzNzI2ZjhhOGQ1ZTkxODQ5MzNkOWUyNWVmNmYyNzI0NzZjODdmODY3NTVmZjk5ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ki2pwzmHeTlM318vKAzG2BPdadTfVNQwfLzXzBuJeLU)
> 
> > 配置好规则后自动管理。

https://1panel.cn/docs/user_manual/toolbox/fail2ban/
按照这个教程安装一直报错：
```
Error: 
 Problem: problem with installed package selinux-policy-targeted-3.14.3-80.el8_5.2.noarch
  - package fail2ban-server-1.0.2-3.el8.noarch requires (fail2ban-selinux if selinux-policy-targeted), but none of the providers can be installed
  - package fail2ban-1.0.2-3.el8.noarch requires fail2ban-server = 1.0.2-3.el8, but none of the providers can be installed
  - conflicting requests
  - nothing provides selinux-policy >= 3.14.3-108.el8_7.1 needed by fail2ban-selinux-1.0.2-3.el8.noarch
  - nothing provides selinux-policy-base >= 3.14.3-108.el8_7.1 needed by fail2ban-selinux-1.0.2-3.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by jaychoubaby** [comment]
> > v1.9.0 版本新增了 Fail2ban 管理功能，可以进入 `工具箱` 页面，如图： ![image](https://private-user-images.githubusercontent.com/46734380/290380028-bcaeee50-7f20-4776-892b-4954c2d09382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjEyODgsIm5iZiI6MTcwMjUyMDk4OCwicGF0aCI6Ii80NjczNDM4MC8yOTAzODAwMjgtYmNhZWVlNTAtN2YyMC00Nzc2LTg5MmItNDk1NGMyZDA5MzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAyMjk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1Y2EyMTg5MzUxNmU3MjgzNzI2ZjhhOGQ1ZTkxODQ5MzNkOWUyNWVmNmYyNzI0NzZjODdmODY3NTVmZjk5ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ki2pwzmHeTlM318vKAzG2BPdadTfVNQwfLzXzBuJeLU)
> > > 配置好规则后自动管理。
> 
> https://1panel.cn/docs/user_manual/toolbox/fail2ban/ 按照这个教程安装一直报错：
> 
> ```
> Error: 
>  Problem: problem with installed package selinux-policy-targeted-3.14.3-80.el8_5.2.noarch
>   - package fail2ban-server-1.0.2-3.el8.noarch requires (fail2ban-selinux if selinux-policy-targeted), but none of the providers can be installed
>   - package fail2ban-1.0.2-3.el8.noarch requires fail2ban-server = 1.0.2-3.el8, but none of the providers can be installed
>   - conflicting requests
>   - nothing provides selinux-policy >= 3.14.3-108.el8_7.1 needed by fail2ban-selinux-1.0.2-3.el8.noarch
>   - nothing provides selinux-policy-base >= 3.14.3-108.el8_7.1 needed by fail2ban-selinux-1.0.2-3.el8.noarch
> (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
> ```

我查到了同样的问题，但是似乎没有办法解决

[https://github.com/fail2ban/fail2ban/issues/3547](https://github.com/fail2ban/fail2ban/issues/3547)

**Comment by ssongliu** [comment]
> > > v1.9.0 版本新增了 Fail2ban 管理功能，可以进入 `工具箱` 页面，如图： ![image](https://private-user-images.githubusercontent.com/46734380/290380028-bcaeee50-7f20-4776-892b-4954c2d09382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjEyODgsIm5iZiI6MTcwMjUyMDk4OCwicGF0aCI6Ii80NjczNDM4MC8yOTAzODAwMjgtYmNhZWVlNTAtN2YyMC00Nzc2LTg5MmItNDk1NGMyZDA5MzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAyMjk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1Y2EyMTg5MzUxNmU3MjgzNzI2ZjhhOGQ1ZTkxODQ5MzNkOWUyNWVmNmYyNzI0NzZjODdmODY3NTVmZjk5ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ki2pwzmHeTlM318vKAzG2BPdadTfVNQwfLzXzBuJeLU)
> > > > 配置好规则后自动管理。
> > 
> > 
> > https://1panel.cn/docs/user_manual/toolbox/fail2ban/ 按照这个教程安装一直报错：
> > ```
> > Error: 
> >  Problem: problem with installed package selinux-policy-targeted-3.14.3-80.el8_5.2.noarch
> >   - package fail2ban-server-1.0.2-3.el8.noarch requires (fail2ban-selinux if selinux-policy-targeted), but none of the providers can be installed
> >   - package fail2ban-1.0.2-3.el8.noarch requires fail2ban-server = 1.0.2-3.el8, but none of the providers can be installed
> >   - conflicting requests
> >   - nothing provides selinux-policy >= 3.14.3-108.el8_7.1 needed by fail2ban-selinux-1.0.2-3.el8.noarch
> >   - nothing provides selinux-policy-base >= 3.14.3-108.el8_7.1 needed by fail2ban-selinux-1.0.2-3.el8.noarch
> > (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
> > ```
> 
> 我查到了同样的问题，但是似乎没有办法解决
> 
> [https://github.com/fail2ban/fail2ban/issues/3547](https://github.com/fail2ban/fail2ban/issues/3547)

服务器、docker 分别是什么版本

**Comment by jaychoubaby** [comment]
> > > > v1.9.0 版本新增了 Fail2ban 管理功能，可以进入 `工具箱` 页面，如图： ![image](https://private-user-images.githubusercontent.com/46734380/290380028-bcaeee50-7f20-4776-892b-4954c2d09382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjEyODgsIm5iZiI6MTcwMjUyMDk4OCwicGF0aCI6Ii80NjczNDM4MC8yOTAzODAwMjgtYmNhZWVlNTAtN2YyMC00Nzc2LTg5MmItNDk1NGMyZDA5MzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAyMjk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1Y2EyMTg5MzUxNmU3MjgzNzI2ZjhhOGQ1ZTkxODQ5MzNkOWUyNWVmNmYyNzI0NzZjODdmODY3NTVmZjk5ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ki2pwzmHeTlM318vKAzG2BPdadTfVNQwfLzXzBuJeLU)
> > > > > 配置好规则后自动管理。
> > > 
> > > 
> > > https://1panel.cn/docs/user_manual/toolbox/fail2ban/ 按照这个教程安装一直报错：
> > > ```
> > > Error: 
> > >  Problem: problem with installed package selinux-policy-targeted-3.14.3-80.el8_5.2.noarch
> > >   - package fail2ban-server-1.0.2-3.el8.noarch requires (fail2ban-selinux if selinux-policy-targeted), but none of the providers can be installed
> > >   - package fail2ban-1.0.2-3.el8.noarch requires fail2ban-server = 1.0.2-3.el8, but none of the providers can be installed
> > >   - conflicting requests
> > >   - nothing provides selinux-policy >= 3.14.3-108.el8_7.1 needed by fail2ban-selinux-1.0.2-3.el8.noarch
> > >   - nothing provides selinux-policy-base >= 3.14.3-108.el8_7.1 needed by fail2ban-selinux-1.0.2-3.el8.noarch
> > > (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
> > > ```
> > 
> > 
> > 我查到了同样的问题，但是似乎没有办法解决
> > [https://github.com/fail2ban/fail2ban/issues/3547](https://github.com/fail2ban/fail2ban/issues/3547)
> 
> 服务器、docker 分别是什么版本

```
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```

`4.18.0-348.7.1.el8_5.x86_64`

`Docker version 24.0.2, build cb74dfc`

**Comment by ssongliu** [comment]
> > > > > v1.9.0 版本新增了 Fail2ban 管理功能，可以进入 `工具箱` 页面，如图： ![image](https://private-user-images.githubusercontent.com/46734380/290380028-bcaeee50-7f20-4776-892b-4954c2d09382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjEyODgsIm5iZiI6MTcwMjUyMDk4OCwicGF0aCI6Ii80NjczNDM4MC8yOTAzODAwMjgtYmNhZWVlNTAtN2YyMC00Nzc2LTg5MmItNDk1NGMyZDA5MzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAyMjk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1Y2EyMTg5MzUxNmU3MjgzNzI2ZjhhOGQ1ZTkxODQ5MzNkOWUyNWVmNmYyNzI0NzZjODdmODY3NTVmZjk5ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ki2pwzmHeTlM318vKAzG2BPdadTfVNQwfLzXzBuJeLU)
> > > > > > 配置好规则后自动管理。
> > > > 
> > > > 
> > > > https://1panel.cn/docs/user_manual/toolbox/fail2ban/ 按照这个教程安装一直报错：
> > > > ```
> > > > Error: 
> > > >  Problem: problem with installed package selinux-policy-targeted-3.14.3-80.el8_5.2.noarch
> > > >   - package fail2ban-server-1.0.2-3.el8.noarch requires (fail2ban-selinux if selinux-policy-targeted), but none of the providers can be installed
> > > >   - package fail2ban-1.0.2-3.el8.noarch requires fail2ban-server = 1.0.2-3.el8, but none of the providers can be installed
> > > >   - conflicting requests
> > > >   - nothing provides selinux-policy >= 3.14.3-108.el8_7.1 needed by fail2ban-selinux-1.0.2-3.el8.noarch
> > > >   - nothing provides selinux-policy-base >= 3.14.3-108.el8_7.1 needed by fail2ban-selinux-1.0.2-3.el8.noarch
> > > > (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
> > > > ```
> > > 
> > > 
> > > 我查到了同样的问题，但是似乎没有办法解决
> > > [https://github.com/fail2ban/fail2ban/issues/3547](https://github.com/fail2ban/fail2ban/issues/3547)
> > 
> > 
> > 服务器、docker 分别是什么版本
> 
> ```
> NAME="CentOS Linux"
> VERSION="8"
> ID="centos"
> ID_LIKE="rhel fedora"
> VERSION_ID="8"
> PLATFORM_ID="platform:el8"
> PRETTY_NAME="CentOS Linux 8"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:centos:centos:8"
> HOME_URL="https://centos.org/"
> BUG_REPORT_URL="https://bugs.centos.org/"
> CENTOS_MANTISBT_PROJECT="CentOS-8"
> CENTOS_MANTISBT_PROJECT_VERSION="8"
> ```
> 
> `4.18.0-348.7.1.el8_5.x86_64`
> 
> `Docker version 24.0.2, build cb74dfc`


这问题确实不太好弄，或许安装低版本的 Docker 可以解决这个问题。

**Comment by jaychoubaby** [comment]
> > > > > > v1.9.0 版本新增了 Fail2ban 管理功能，可以进入 `工具箱` 页面，如图： ![image](https://private-user-images.githubusercontent.com/46734380/290380028-bcaeee50-7f20-4776-892b-4954c2d09382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MjEyODgsIm5iZiI6MTcwMjUyMDk4OCwicGF0aCI6Ii80NjczNDM4MC8yOTAzODAwMjgtYmNhZWVlNTAtN2YyMC00Nzc2LTg5MmItNDk1NGMyZDA5MzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAyMjk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1Y2EyMTg5MzUxNmU3MjgzNzI2ZjhhOGQ1ZTkxODQ5MzNkOWUyNWVmNmYyNzI0NzZjODdmODY3NTVmZjk5ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ki2pwzmHeTlM318vKAzG2BPdadTfVNQwfLzXzBuJeLU)
> > > > > > > 配置好规则后自动管理。
> > > > > 
> > > > > 
> > > > > https://1panel.cn/docs/user_manual/toolbox/fail2ban/ 按照这个教程安装一直报错：
> > > > > ```
> > > > > Error: 
> > > > >  Problem: problem with installed package selinux-policy-targeted-3.14.3-80.el8_5.2.noarch
> > > > >   - package fail2ban-server-1.0.2-3.el8.noarch requires (fail2ban-selinux if selinux-policy-targeted), but none of the providers can be installed
> > > > >   - package fail2ban-1.0.2-3.el8.noarch requires fail2ban-server = 1.0.2-3.el8, but none of the providers can be installed
> > > > >   - conflicting requests
> > > > >   - nothing provides selinux-policy >= 3.14.3-108.el8_7.1 needed by fail2ban-selinux-1.0.2-3.el8.noarch
> > > > >   - nothing provides selinux-policy-base >= 3.14.3-108.el8_7.1 needed by fail2ban-selinux-1.0.2-3.el8.noarch
> > > > > (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
> > > > > ```
> > > > 
> > > > 
> > > > 我查到了同样的问题，但是似乎没有办法解决
> > > > [https://github.com/fail2ban/fail2ban/issues/3547](https://github.com/fail2ban/fail2ban/issues/3547)
> > > 
> > > 
> > > 服务器、docker 分别是什么版本
> > 
> > 
> > ```
> > NAME="CentOS Linux"
> > VERSION="8"
> > ID="centos"
> > ID_LIKE="rhel fedora"
> > VERSION_ID="8"
> > PLATFORM_ID="platform:el8"
> > PRETTY_NAME="CentOS Linux 8"
> > ANSI_COLOR="0;31"
> > CPE_NAME="cpe:/o:centos:centos:8"
> > HOME_URL="https://centos.org/"
> > BUG_REPORT_URL="https://bugs.centos.org/"
> > CENTOS_MANTISBT_PROJECT="CentOS-8"
> > CENTOS_MANTISBT_PROJECT_VERSION="8"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `4.18.0-348.7.1.el8_5.x86_64`
> > `Docker version 24.0.2, build cb74dfc`
> 
> 这问题确实不太好弄，或许安装低版本的 Docker 可以解决这个问题。

/(ㄒoㄒ)/~~ ，那我想接着使用v1.80版本的手动屏蔽功能不知可否

**Comment by wanghe-fit2cloud** [comment]
> 那我想接着使用v1.80版本的手动屏蔽功能不知可否

可以使用 `1pctl restore` 命令恢复至上一个版本。

**Comment by jaychoubaby** [comment]
> > 那我想接着使用v1.80版本的手动屏蔽功能不知可否
> 
> 可以使用 `1pctl restore` 命令恢复至上一个版本。

那不是意味着我以后再也不能体验新版本了/(ㄒoㄒ)/~~ ，不可以两种方式都保留吗，要手动降docker版本实属也有点麻烦，之前已经部署了很多服务在运行了

**Comment by xucr11** [comment]
有没有什么 `Fail2ban` 的替代品
