### ISSUE TITLE
[BUG] fail2ban无法启动，提示：No such file or directory: '/www/server/panel/plugin/fail2ban'

### ISSUE THREAD

**Issue by shangdev** [1Panel-dev/1Panel#3313]
### 1Panel 版本

1.9.0

### 问题描述

使用命令在控制台安装了fail2ban：sudo apt-get install fail2ban

查看fail2ban状态时显示Active: fail

查看日志：
![image](https://github.com/1Panel-dev/1Panel/assets/15621520/d6a6332a-6c07-494d-a3ba-33502207a759)

### 重现步骤

1、安装：sudo apt-get install fail2ban
2、查看状态：sudo systemctl status fail2ban

**Comment by ssongliu** [comment]
感谢反馈，是宝塔转过来的吗？麻烦提供一下 cat /etc/fail2ban/jail.local 截图

**Comment by shangdev** [comment]
@ssongliu 以前好像是安装过宝塔，已经卸载掉了。

![image](https://github.com/1Panel-dev/1Panel/assets/15621520/d05dbbc1-0d0a-4d16-a259-cb9e6967821b)

**Comment by ssongliu** [comment]
> @ssongliu 以前好像是安装过宝塔，已经卸载掉了。
> 
> ![image](https://private-user-images.githubusercontent.com/15621520/290474843-d05dbbc1-0d0a-4d16-a259-cb9e6967821b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDc3MjcsIm5iZiI6MTcwMjU0NzQyNywicGF0aCI6Ii8xNTYyMTUyMC8yOTA0NzQ4NDMtZDA1ZGJiYzEtMGQwYS00ZDE2LWEyNTktY2I5ZTY5Njc4MjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA5NTAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MTgxYTc4MWUzNTBmOTQxMzRmYTFjNDZmNTFhYzM2ZDExYTk4NTc3YWE2NjBhZDc5ZTU5ZTFmMzZiODdjMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.scbRCmTosfEZ6TeynMN08GrlTeq9P5NHdGDqRD2ORbI)

fail2ban 只是用来管理 ssh 的话，可以吧下面这些部分都删掉，然后重启就行了
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/4358326d-e24c-4413-a3ed-2ecd7e3d6455)
