### ISSUE TITLE
[FEATURE]希望可以增加修改镜像标签功能。

### ISSUE THREAD

**Issue by mufengyouyang** [1Panel-dev/1Panel#3316]
### 1Panel 版本

v1.9.0

### 请描述您的需求或者改进建议

docker控制面板中，镜像的标签无法删除和修改，目前只能增加，希望可以增加修改功能

**Comment by mufengyouyang** [comment]
![a](https://github.com/1Panel-dev/1Panel/assets/130118370/fa49e122-25ae-48e0-b10d-9f52237495a7)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.9.2 版本已发布。
