### ISSUE TITLE
[BUG]在不同的机器上安装应用，版本的排序不一样

### ISSUE THREAD

**Issue by zyyfit** [1Panel-dev/1Panel#3317]
### 1Panel 版本

1.9.0

### 问题描述

在机器A上安装minio，版本顺序是 12-02、11-11
在机器B上安装minio，版本顺序是 11-11、12-02

### 重现步骤

在机器A上安装minio，版本顺序是 12-02、11-11
在机器B上安装minio，版本顺序是 11-11、12-02

**Comment by zhengkunwang223** [comment]
感谢反馈 下个小版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.9.1 版本已发布。
