### ISSUE TITLE
希望证书里增加dynv6

### ISSUE THREAD

**Issue by mufengyouyang** [1Panel-dev/1Panel#3319]
### 1Panel 版本

v1.9.0

### 请描述您的需求或者改进建议

希望证书里增加dynv6网站的证书以及ddns

**Comment by mufengyouyang** [comment]
https://dynv6.com/

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by zhengkunwang223** [comment]
当前我们优先支持 https://go-acme.github.io/lego/dns/ 这个列表中的 DNS 厂商 
我看了一下 dynv6 不在其中 所以可能近期无法支持
