### ISSUE TITLE
[BUG]阿里云快照恢复

### ISSUE THREAD

**Issue by xfwlwork** [1Panel-dev/1Panel#3325]
### 1Panel 版本

1.8.5

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/45943421/cfc92540-ca90-453b-82be-14577bc44985)
![image](https://github.com/1Panel-dev/1Panel/assets/45943421/91004ce5-9775-41fe-b80c-5a00da6a4ac1)
![image](https://github.com/1Panel-dev/1Panel/assets/45943421/cb437741-2992-4e83-879c-8782c39ac997)
当我尝试使用【阿里云oss】进行快照备份并恢复的时候出现了异常
从图片来看，应该是没有找到对应的备份的压缩包，但是我可以确保文件是存在的，并且可以正常备份快照，但是在恢复快照的时候，一直提示错误
 `[2023-12-12 19:02:48] [INFO] start to recover panel by snapshot now  
[2023-12-12 19:02:48] [ERROR] recover failed, err: download file 1panel_v1.8.5_20231212184715 from OSS failed, err: oss: service returned error: StatusCode=404, ErrorCode=, ErrorMessage="", RequestId=`

### 重现步骤

使用【阿里云oss】进行快照备份并恢复

### 相关日志输出

```shell
[2023-12-12 19:02:48] [INFO] start to recover panel by snapshot now  
[2023-12-12 19:02:48] [ERROR] recover failed, err: download file 1panel_v1.8.5_20231212184715 from OSS failed, err: oss: service returned error: StatusCode=404, ErrorCode=, ErrorMessage="",
```

**Comment by ssongliu** [comment]
感谢反馈，请问一下 OSS 的备份策略选择的那种
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/79bf3734-89e6-4754-b752-6b07a8e3c53b)

**Comment by whl-xf** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/45943421/48027acc-71e7-4e35-b9a3-5fb4ac1d9eda)
我使用的是标准存储类型

**Comment by xfwlwork** [comment]
> 感谢反馈，请问一下OSS的备份策略选择哪种 ![图像](https://private-user-images.githubusercontent.com/73214554/290441334-79bf3734-89e6-4754-b752-6b07a8e3c53b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1Mzk0NjksIm5iZiI6MTcwMjUzOTE2OSwicGF0aCI6Ii83MzIxNDU1NC8yOTA0NDEzMzQtNzliZjM3MzQtODllNi00NzU0LWI3NTItNmIwN2E4ZTNjNTNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDA3MzI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMzI0MjBjNjI4NDRhNjMzODM1ZGMzYzRhMDFmYzA1ZTkzODdmMjZiNjFjMmYxMTI0MGFiYjI3YWNhZWYzZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WIE_Wn38pAUs1lCKVndbhR7wftkmWtbV803T5oNPlOs)

![image](https://github.com/1Panel-dev/1Panel/assets/45943421/3455b6f7-0009-4122-a936-3012d8ac522e)
我使用的是标准存储类型

**Comment by ssongliu** [comment]
可以先在计划任务中简单备份一个文件夹，然后看看计划任务报告界面能不能正常下载。

**Comment by xfwlwork** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/45943421/233e890f-9f1c-4c68-b0e8-6d7eb5e85c83)
![image](https://github.com/1Panel-dev/1Panel/assets/45943421/3fae0acf-543f-475e-8498-6d40776393c4)

**Comment by ssongliu** [comment]
有 oss 客户端工具吗，截图看一下快照文件列表的状态

**Comment by xfwlwork** [comment]
> 有 oss 客户端工具吗，截图看一下快照文件列表的状态

![image](https://github.com/1Panel-dev/1Panel/assets/45943421/4e4b571d-b8f0-4f6d-99da-016868a7e891)
![image](https://github.com/1Panel-dev/1Panel/assets/45943421/6dee6515-4de1-49b8-be1c-81a85f4eb736)
![image](https://github.com/1Panel-dev/1Panel/assets/45943421/28120ab3-fa3c-498b-b120-872282440202)

**Comment by xfwlwork** [comment]
我想我已经知道问题原因了：
在创建【阿里云 OSS】备份账号的时候，并没有填写目录。我以为已经默认帮我填写了，但实际并没有，从而导致了恢复问题
![image](https://github.com/1Panel-dev/1Panel/assets/45943421/8fa8166f-ac9e-44a8-b5cf-dbbef083127b)
![image](https://github.com/1Panel-dev/1Panel/assets/45943421/88766671-c203-40a3-899d-4b2c53369c2c)

在我修改之后，快照恢复可以正常使用了
![image](https://github.com/1Panel-dev/1Panel/assets/45943421/61a25e86-8ac1-4407-8501-eb18c5d2311e)
