### ISSUE TITLE
[BUG]文件管理的文件上传下载问题

### ISSUE THREAD

**Issue by gitDebianD** [1Panel-dev/1Panel#3326]
### 1Panel 版本

当前运行版本：v1.5.3

### 问题描述

在电脑上使用1panel文件功能上传文件下载均正常，但是当在电脑上使用1panel上传文件后，使用手机登录1panel进行文件下载操作时，任何大小的文件都会下载一个成仅有50b大小的错误文件，手机设备使用的是小米/红米手机均出现这样的问题。

总结：使用1panel电脑上传的文件，用手机1panel下载会出现下载错误。

### 重现步骤

使用电脑上传，使用手机下载文件。

**Comment by wanghe-fit2cloud** [comment]
可能是手机浏览器的问题吧。
> 在其他手机上测试均未复现上述问题。

**Comment by gitDebianD** [comment]
[自动回复]:我设置了自动回复功能，这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by gitDebianD** [comment]
实测关闭浏览器无痕模式后已一切正常。。。

**Comment by gitDebianD** [comment]
> 可能是手机浏览器的问题吧。
> 
> > 在其他手机上测试均未复现上述问题。

实测关闭浏览器无痕模式后已一切正常。。。
