### ISSUE TITLE
[BUG]面板自身SSL不兼容Firefox浏览器

### ISSUE THREAD

**Issue by WankkoRee** [1Panel-dev/1Panel#3327]
### 1Panel 版本

v1.9.0

### 问题描述

与 #1465 类似，只不过我这边是面板自身开启SSL后，Firefox无法访问面板。

错误代码同样为`MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING`，即`OCSP`问题。

### 重现步骤

开启面板的SSL并配置证书，用Firefox访问。

----

由于不确定是否是旧版本升级到新版本的历史遗留问题，所以无法保证全新安装的面板也能复现这个问题。

如果是升级后的遗留bug，希望能给出解决办法，我尝试关闭面板SSL后再重新开启SSL并不能解决。

**Comment by zhengkunwang223** [comment]
感谢反馈 我们测试一下

**Comment by zhengkunwang223** [comment]
经过测试 在 firefox 120.0.1 上是可以访问面板的

**Comment by WankkoRee** [comment]
经测试，自签名证书可以忽略风险提示正常访问，可信签名证书会提示`MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING`，无法跳过。

若测试时使用自签名的`127.0.0.1`，则会无法复现此问题。

**Comment by zhengkunwang223** [comment]
> 经测试，自签名证书可以忽略风险提示正常访问，可信签名证书会提示`MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING`，无法跳过。
> 
> 若测试时使用自签名的`127.0.0.1`，则会无法复现此问题。

我使用的是 Let's Encrypt 颁发的域名证书

**Comment by zhengkunwang223** [comment]
> > 经测试，自签名证书可以忽略风险提示正常访问，可信签名证书会提示`MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING`，无法跳过。
> > 若测试时使用自签名的`127.0.0.1`，则会无法复现此问题。
> 
> 我使用的是 Let's Encrypt 颁发的域名证书

刚才又试了一下 ZeroSSL 颁发的 IP 证书，无提示直接进入登录页面

**Comment by WankkoRee** [comment]
那等我周末有空了全新安装一个环境去测试一下。

**Comment by WankkoRee** [comment]
我本地全新安装可以复现。

环境：
- Debian 12
- 1Panel v1.9.1

步骤：
1. 在 面板设置-安全-域名绑定 中绑定域名
2. 在 网站-证书 中添加上述域名的可信证书
3. 在 面板设置-安全-面板SSL 中打开该选项并使用上述证书

结果：
Edge 120.0.2210.61 访问https面板无问题
Firefox 120.0.1 访问https面板报错`MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING`

![image](https://github.com/1Panel-dev/1Panel/assets/21287731/c88215a5-a499-4614-93d2-c9eba5b9078a)

**Comment by zhengkunwang223** [comment]
> MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING

https://really-simple-ssl.com/mozilla_pkix_error_required_tls_feature_missing/  看一下这个是不是你说的这个问题
https://really-simple-ssl.com/ocsp-stapling/

**Comment by WankkoRee** [comment]
> 看一下这个是不是你说的这个问题

是的，关闭ff中对ocsp的检查后可以正常访问。

此问题曾在 #1465 中通过添加相关 Nginx 配置的方式解决，但是对于面板本身我不太清楚是否容易解决。

**Comment by zhengkunwang223** [comment]
> MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING

我在多个应用的讨论区都看到了此问题 比如  
wordpress https://wordpress.org/support/topic/ssl-not-working-on-firefox/ 
qBittorrent  https://github.com/qbittorrent/qBittorrent/issues/18898
解决方案都是一致的 
我也搜了一下 gin 框架貌似没有这种配置
如果后续有好的解决方案 我们会再打开这个 Issue
