### ISSUE TITLE
[FEATURE]修改主机信息，输入内容后需要点击下测试连接，才能保存

### ISSUE THREAD

**Issue by liufei20151013** [1Panel-dev/1Panel#3329]
### 1Panel 版本

v.1.9.0

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/15103510/f8476b4b-a03f-474a-ba18-f61ff9f5b1d9)
希望可以直接保存更改的内容。

### 附加信息

1panel很好用，在线更新很方便，也很快，祝1panel越来越好用！感谢1panel产品组！

**Comment by 9a6c** [comment]
测试一下为了保证连接可用，我感觉这里挺合理， 可能每个人的需求都不一样吧
