### ISSUE TITLE
[FEATURE] 终端页面优化

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#3330]
### 请描述您的问题

终端这个界面搜索框出去了
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/a31a4038-c14b-4728-95b8-d0efe0ccab02)

终端页面支持更多的条目， 输入命令ps -ef无法查看完整的信息， 估计是只显示100条或200条
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/ba34a39c-337e-44dc-97a3-db0bfe693445)

**Comment by ssongliu** [comment]
感谢反馈，后续版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.9.2 版本已发布。
