### ISSUE TITLE
容器升级没有默认带上上一次的版本[BUG]

### ISSUE THREAD

**Issue by lchjczw** [1Panel-dev/1Panel#3331]
### 1Panel 版本

v1.9.0

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/12480676/05bbb44e-6284-4329-b20f-135b4f6f6d08)

这个位置之前会带上之前的版本，现在也希望带上，尤其是latest的时候

### 重现步骤

升级就可以重现

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本会优化上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.9.2 版本已发布。
