### ISSUE TITLE
[BUG]WordPress自动更新后，1panel应用商店未更新WordPress版本号

### ISSUE THREAD

**Issue by Bigzzh2022** [1Panel-dev/1Panel#3332]
### 联系方式

2896780219@qq.com

### 1Panel 版本

v1.9.1

### 问题描述

如图：WordPress站点已自动更新，但1panel面板的应用商店提示升级wordpress
![screenshot20231214](https://github.com/1Panel-dev/1Panel/assets/124849169/c74efb33-5396-4e8c-b5ce-73813efb96a9)
![screenshot20231214 (1)](https://github.com/1Panel-dev/1Panel/assets/124849169/e7dfb122-ca5d-44d7-aadb-6b69bc98b89d)

### 重现步骤

none

**Comment by zhengkunwang223** [comment]
wordpress 有自己的更新机制， 是直接更新代码，我们的更新判断，是判断有没有新版本的镜像，如果你已经更新过了，可以忽略更新
