### ISSUE TITLE
[QUESTION]为什么一但使用vpn就会链接失败面板，部分资源文件会503

### ISSUE THREAD

**Issue by yinyajiang** [1Panel-dev/1Panel#3334]
如下图所示一旦我使用VPN访问服务器面板，就会失败，遇到部分资源503错误呢，这个属于我知识盲区了！！我访问其它网站是一切正常的，请教一下会是什么原因呢？
![image](https://github.com/1Panel-dev/1Panel/assets/32933356/e4c2623f-2dab-4193-a408-00d4a9762c27)

**Comment by wanghe-fit2cloud** [comment]
还是需要自行排查网络等原因，由于我们这边不能稳定复现上述问题，就先关闭该 issue 了，望理解。

**Comment by NorthernDream** [comment]
应该是服务器问题，我这边也这样，hetzner 1panel 开梯子就连接503，折磨我一天了
