### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by CrazySciurini** [1Panel-dev/1Panel#3336]
### 1Panel 版本

v1.9.0

### 请描述您的需求或者改进建议

网站-证书- DNS账户
希望类型可以支持dns.he.net

**Comment by zhengkunwang223** [comment]
我们会优先支持 https://go-acme.github.io/lego/dns/ 这个列表中存在的 DNS 厂商 
如果不在此列表中 可能暂时无法支持
