### ISSUE TITLE
[BUG] SSH 登陆日志展示有错

### ISSUE THREAD

**Issue by suiyueou** [1Panel-dev/1Panel#3337]
### 1Panel 版本

v1.9.1

### 问题描述

依旧是 #3309 的问题延续，最新版虽然修复了提到的 `失败` 下显示的填充错乱问题，但是非系统用户的其他 `乱码用户` 依旧不会展示

> 这里的其他 `乱码用户` 指的就是 #3309 里提到的那个类似 `suiyue` 的非系统上已存在的用户

ubuntu 20.04 (rsyslogd  8.2001.0) 和 debian 11.3 下 `所有` 和 `失败` 依旧不会显示除 root 外的用户，或者应该是说不显示系统里没有的用户，也就是非系统上已存在用户的其他 `乱码用户` 依旧不会展示

debian 12.2 (rsyslogd  8.2302.0) 下，`所有` 状态下也是一样的问题，但 `失败` 下却可以完整展示所有失败记录，包括系统用户和非系统上已存在的其他 `乱码用户`

### 重现步骤

SSH 管理 => 登录日志 => 状态选择 `所有/失败`

### 期待的正确结果

`所有和失败` 状态下可以完整显示包括系统用户和非系统上已存在的其他 `乱码用户`

### 相关日志输出

```shell
依旧是 #3309 附送的日志输出
```

**Comment by ssongliu** [comment]
感谢反馈，获取 SSH 日志会过滤掉了不存在用户的登录日志，之前的问题是因为查询失败没有过滤导致解析失败。

**Comment by suiyueou** [comment]
> 感谢反馈，获取 SSH 日志会过滤掉了不存在用户的登录日志，之前的问题是因为查询失败没有过滤导致解析失败。

过滤掉不存在的用户是设计上如此还是（？
如果是的话，是否可以选择完整展示，过滤后可能与 fail2ban 自动封禁的 ip 列表造成割裂（

**Comment by ssongliu** [comment]
> > 感谢反馈，获取 SSH 日志会过滤掉了不存在用户的登录日志，之前的问题是因为查询失败没有过滤导致解析失败。
> 
> 过滤掉不存在的用户是设计上如此还是（？ 如果是的话，是否可以选择完整展示（

下个小版本再针对这里优化一下

**Comment by suiyueou** [comment]
> 下个小版本再针对这里优化一下

辛苦了（~

**Comment by wanghe-fit2cloud** [comment]
v1.9.2 版本已发布。
