### ISSUE TITLE
[FEATURE] 建议增加自动更新功能

### ISSUE THREAD

**Issue by waves86** [1Panel-dev/1Panel#3339]
### 1Panel 版本

1.9.1

### 请描述您的需求或者改进建议

建议增加自动更新功能

**Comment by zhengkunwang223** [comment]
是 1Panel 的自动更新吗

**Comment by waves86** [comment]
> 是 1Panel 的自动更新吗

是的，每次都要点击更新

**Comment by wanghe-fit2cloud** [comment]
1Panel 应该不会支持自动更新功能，望理解。
