### ISSUE TITLE
[FEATURE]mysql导入文件大小限制10m

### ISSUE THREAD

**Issue by linuxxx** [1Panel-dev/1Panel#334]
### 1Panel 版本

最新版本

### 请描述您的需求或者改进建议

mysql导入文件大小限制10m，phpadmin 也无法修改php.ini.  无法满足需求。 要么开放php.ini，我可以通过phpadmin导入，要么修改mysql导入的大小限制，至少支持个几百m吧。

**Comment by ssongliu** [comment]
感谢反馈！预计将在本周发布的 v1.0.3 解决该问题。

**Comment by Mr-Ao-Dragon** [comment]
可以的话考虑下支持导入文件URL地址

**Comment by wanghe-fit2cloud** [comment]
> 可以的话考虑下支持导入文件URL地址

感谢反馈，后续版本我们会考虑支持该需求。
