### ISSUE TITLE
[BUG]Nextcloud 安装后后台无法查看日志，空白的，同时三台VPS 都是一样。

### ISSUE THREAD

**Issue by hkbbdx** [1Panel-dev/1Panel#3340]
### 联系方式

szzc1227@gmail.com

### 1Panel 版本

v1.9.1

### 问题描述

VPS 只安装1Panel  全新安装Nexctcloud 后台 
安全检查提示：
158 errors in the logs since 2023年12月8日
后台打开日志选项为空白，到服务器里查看日志有生成
"class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/app/www/public/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"create","class":"OCA\\Files_External\\Controller\\GlobalStoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/app/www/public/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/app/www/public/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/app/www/public/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/app/www/public/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/config/www/nextcloud/apps/files_external/lib/Lib/Storage/SFTP.php","Line":160,"message":"Login failed","exception":{},"CustomMessage":"Login failed"}}
{"reqId":"FXCNVXQVqtx6AhlpZAyB","level":3,"time":"2023-12-15T01:55:01+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Can't get app storage, app files_external, user not logged in","userAgent":"--","version":"28.0.0.11","data":{"app":"core"}}
{"reqId":"FXCNVXQVqtx6AhlpZAyB","level":3,"time":"2023-12-15T01:55:01+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Can't get app storage, app files_external, user not logged in","userAgent":"--","version":"28.0.0.11","data":{"app":"core"}}
修改了目录和日志文件的权限也是一样，请问要怎么修复呢

### 重现步骤

修改了目录和日志文件的权限也是一样，请问要怎么修复呢

### 期待的正确结果

希望能修复日志的问题
158 errors in the logs since 2023年12月8日

### 相关日志输出

```shell
"class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/app/www/public/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"create","class":"OCA\\Files_External\\Controller\\GlobalStoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/app/www/public/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/app/www/public/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/app/www/public/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/app/www/public/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/config/www/nextcloud/apps/files_external/lib/Lib/Storage/SFTP.php","Line":160,"message":"Login failed","exception":{},"CustomMessage":"Login failed"}}
{"reqId":"FXCNVXQVqtx6AhlpZAyB","level":3,"time":"2023-12-15T01:55:01+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Can't get app storage, app files_external, user not logged in","userAgent":"--","version":"28.0.0.11","data":{"app":"core"}}
{"reqId":"FXCNVXQVqtx6AhlpZAyB","level":3,"time":"2023-12-15T01:55:01+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Can't get app storage, app files_external, user not logged in","userAgent":"--","version":"28.0.0.11","data":{"app":"core"}}
```

**Comment by wanghe-fit2cloud** [comment]
在本地环境安装 nextcloud 未复现上述问题，可以正常初始化系统。
> 1Panel 使用的是官方提供的 docker-compose.yaml 容器化安装。若卸载重装后依然存在问题，建议到 [Nextcloud Issues](https://github.com/nextcloud/server/issues) 反馈使用问题。
