### ISSUE TITLE
[BUG]容器页面更改容器名称后， 已安装应用无法同步容器更改

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#3342]
### 联系方式

交流群5 9a6ac...

### 1Panel 版本

1.9.1

### 问题描述

如将容器名称改成php8
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/84399c78-1d84-43a5-b5c8-94f86728bbc2)

![image](https://github.com/1Panel-dev/1Panel/assets/51264840/2420d19e-0218-451f-bea2-ea48d5256ceb)

### 重现步骤

更改容器名称

### 期待的正确结果

希望更改容器名称后，已安装列表可以正确显示

**Comment by wanghe-fit2cloud** [comment]
如果需要修改已安装应用的容器名称，建议到 `已安装` 列表修改，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/0734738b-a505-4087-b624-2a046511d962)

**Comment by 9a6c** [comment]
ok，不知道有这个功能
