### ISSUE TITLE
[FEATURE] 防火墙界面可以增加重启按钮吗

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#3345]
### 1Panel 版本

1.9.1

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/51264840/caef874c-4a77-4706-a481-e1d432d6bdbc)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.9.2 版本已发布。
