### ISSUE TITLE
 概况页负载数值显示异常

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#3347]
### 联系方式

交流群5 9a6ac...

### 1Panel 版本

1.9.1

### 问题描述

删除不使用的容器镜像， 大约10g， 概况页负载数值显示异常， 一段时间后恢复正常(2-3分钟)，不清楚是不是bug，也可能是我服务器太辣鸡了
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/8e50fe66-d3d2-4f1e-93c8-9e1f651d3600)

### 重现步骤

删除不使用的容器镜像， 大约10g， 概况页负载数值显示异常

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
docker 在执行 prune 命令时确实会出现占用大量资源的情况。后续可以在 SSH 终端手动执行 `uptime` 命令来查看具体负载信息。
