### ISSUE TITLE
[FEATURE] 希望提供更丰富的主机安全选项

### ISSUE THREAD

**Issue by Starsbon** [1Panel-dev/1Panel#335]
### 1Panel 版本

1.0.2

## 希望提供更丰富的主机安全选项
如：防火墙 / 端口规则配置、禁 Ping、主机禁止某区域 / IP 段请求、SSH 日志等功能。
另外，面板的入口是否可以修改为指定的路径，当请求路径不正确时可以返回 404 等不同状态码伪装后台入口。

**Comment by zhengkunwang223** [comment]
感谢建议，这个我们讨论一下

**Comment by maninhill** [comment]
安全类别的优化和需求，都很重要。

**Comment by wanghe-fit2cloud** [comment]
v1.1.0 版本已发布，支持系统防火墙配置管理、禁ping等功能。
