### ISSUE TITLE
[BUG]  1Panel无法一体化安装halo

### ISSUE THREAD

**Issue by zhaoyy0513** [1Panel-dev/1Panel#3350]
### 联系方式

neonyuyang@163.com

### 1Panel 版本

V1.9.1

### 问题描述

本来希望创建halo应用，但是提示mysql无法拉取，然后只能服务器拉取mysql，并且安装完后1panel无法找到我安装的mysql8，然后通过远程数据库方式连接上了我的服务器sql，然后开始安装halo，也是提示无法拉取，不知道是什么原因造成的，我的DNS等信息都是配置正确的
https://img.tg/image/OKagzb
https://img.tg/image/OKamJl

### 重现步骤

我使用的是华为云的服务器，不知道是不是需要在1Panel配置什么东西

**Comment by wanghe-fit2cloud** [comment]
参考：https://bbs.fit2cloud.com/t/topic/725/3

**Comment by zhaoyy0513** [comment]
牛的，问题解决了，以前配的镜像加速器 好像都失效了，无法访问，感谢
