### ISSUE TITLE
[FEATURE] 这个小界面可以添加新建文件夹的功能吗

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#3351]
### 1Panel 版本

1.9.1

### 请描述您的需求或者改进建议

这个小界面可以添加新建文件夹的功能吗， 有的时候需要创建文件夹，然后选择它。
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/4516178b-760d-4a7f-951f-0416809c60e6)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本支持。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
