### ISSUE TITLE
[QUESTION]自签证书 根Root CA 在那里下载。

### ISSUE THREAD

**Issue by heyailab** [1Panel-dev/1Panel#3352]
### 请描述您的问题

你好，想了解一下自签证书 根Root CA 在那里下载？想导入本地 “受信任的根证书颁发机构”

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，当前版本创建的 `自签证书` 支持导出证书和密钥文件。
> 后续版本考虑支持下载根证书。

**Comment by zhengkunwang223** [comment]
> ### 请描述您的问题
> 你好，想了解一下自签证书 根Root CA 在那里下载？想导入本地 “受信任的根证书颁发机构”

证书机构的  csr 可以在 证书颁发机构 详情列表中查看

**Comment by heyailab** [comment]
> > ### 请描述您的问题
> > 你好，想了解一下自签证书 根Root CA 在那里下载？想导入本地 “受信任的根证书颁发机构”
> 
> 证书机构的 csr 可以在 证书颁发机构 详情列表中查看

意思用  csr 导入本地“受信任的根证书颁发机构” 就可以了？
试过也不行的。本地用 mkcert 做自签的没问题。

**Comment by zhengkunwang223** [comment]
> > > ### 请描述您的问题
> > > 你好，想了解一下自签证书 根Root CA 在那里下载？想导入本地 “受信任的根证书颁发机构”
> > 
> > 
> > 证书机构的 csr 可以在 证书颁发机构 详情列表中查看
> 
> 意思用 csr 导入本地“受信任的根证书颁发机构” 就可以了？ 试过也不行的。本地用 mkcert 做自签的没问题。

好的 我们看一下

**Comment by zhengkunwang223** [comment]
经过复现 发现是中间证书丢失导致 后续版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.9.2 版本已发布。
