### ISSUE TITLE
[BUG]网站配置中写lua脚本后会导致面板无法控制此网站

### ISSUE THREAD

**Issue by Concises** [1Panel-dev/1Panel#3353]
### 1Panel 版本

1.8.5

### 问题描述

OpenResty服务 网站配置文件里写lua脚本会导致无法再用面板编辑这个网站 点击安全 日志 或者保存配置文件都会提示服务异常

### 重现步骤

在任意一个网站的配置文件中添加
set_by_lua_block $random_index {
                return math.random(1, 3); 
            }

**Comment by zhengkunwang223** [comment]
这个Lua脚本我试了 没有问题

**Comment by Concises** [comment]
> 这个Lua脚本我试了 没有问题



> 这个Lua脚本我试了 没有问题





location / {
    set_by_lua_block $random_index {
                return math.random(1, 3);
            }
    }

**Comment by zhengkunwang223** [comment]
> location / {
> set_by_lua_block $random_index {
> return math.random(1, 3);
> }
> }

这个也没有问题

可以添加我的企业微信，帮你远程看一下
<img src="https://github.com/1Panel-dev/1Panel/assets/31820853/c49c101a-59ac-4e18-9ef9-36b4d5b92bcf" width="156px" height="156px">

> 或者你看一下你的 Openresty 日志是不是有错误
