### ISSUE TITLE
[FEATURE] redis 自定义

### ISSUE THREAD

**Issue by LnameBF** [1Panel-dev/1Panel#3354]
### 1Panel 版本

1.9.1

### 请描述您的需求或者改进建议

是否可以考虑redis也可以自定义配置呢，我看目前仅支持在面板内安装使用
![image](https://github.com/1Panel-dev/1Panel/assets/104903447/32bea2f3-ec74-41fc-adbc-da5086ff3213)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们后续版本可能会考虑支持添加远程 Redis 数据库。

**Comment by wanghe-fit2cloud** [comment]
支持外部 Redis 数据库的需求，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/3522
