### ISSUE TITLE
[BUG] 反向代理被删除

### ISSUE THREAD

**Issue by djy6257** [1Panel-dev/1Panel#3355]
### 1Panel 版本

1.9.1

### 问题描述

反向代理被不正常删除

### 重现步骤

先通过域名建立一个反向代理，再通过同一个域名不同端口建立第二个反向代理，点击删除第二个带端口的反向代理，会报下图的错误，再次删除，提示删除成功。进入第一个反向代理查看子代理，子代理全部消失，查看文件夹，文件夹也不存在了。
![FI~)$R 200WQ3UMN77P} FF](https://github.com/1Panel-dev/1Panel/assets/61313387/1c8d0e3b-50b2-4151-9810-e86aadf07744)

**Comment by zhengkunwang223** [comment]
您好，我们在本地没有复现
> 可以添加我的企业微信，之后远程你环境看一下。

<img src="https://github.com/1Panel-dev/1Panel/assets/31820853/193c6677-8694-47c2-b3db-103ae7f677eb" width="156px" height="156px">

**Comment by zhengkunwang223** [comment]
经过远程 是备份恢复之后导致的 BUG 下个小版本（v1.9.2） 修复

**Comment by wanghe-fit2cloud** [comment]
v1.9.2 版本已发布。
