### ISSUE TITLE
[BUG] 创建数据库失败

### ISSUE THREAD

**Issue by icpd** [1Panel-dev/1Panel#3356]
### 请描述您的问题

<img width="1092" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/35096485/8df1db02-9053-4803-976d-bf39e66b9a2d">
使用非root账户创建数据提示如上。使用root账户则提示不能使用root账户

**Comment by icpd** [comment]
刚开始使用mysql8.2，切换为5.7后正常

**Comment by wanghe-fit2cloud** [comment]
应该是容器状态异常，可以到容器列表查看一下 MySQL 容器状态和日志。
