### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by luoshan5261486** [1Panel-dev/1Panel#3357]
### 1Panel 版本

1.9.1

### 请描述您的需求或者改进建议

安装gitea应用的时候必须要提醒得先装MySQL才行 但是gitea可以用SQLite3 可以改一下安装gitea不强制要求MySQL

**Comment by wanghe-fit2cloud** [comment]
推荐使用 Gitea + MySQL 方式来部署。
> 可以进入 `容器` - `编排` 页面，手动创建 Gieta + SQLite3 服务。
