### ISSUE TITLE
[BUG] 工具箱 Fail2ban 添加 IP 白名单超时。

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#3358]
### 1Panel 版本

1.9.1

### 问题描述

这个界面可以添加ip吗？ 比如输入了 127.0.0.1 点击确定， 然后出现请求超时，这个时候查看ip白名单和ip黑名单，发现显示空白，还以为丢失了， 然后过来一会右正常显示
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/9fd672df-3cd1-4765-8d58-67a7851febe3)

### 重现步骤

工具箱-ip白名单添加127.0.0.1

### 附加信息
删除规则时(删除的ip白名单规则)，也出现超时， ip黑名单显示为空，过了一段时间后才会正常显示
![1702799584901](https://github.com/1Panel-dev/1Panel/assets/51264840/e66b7496-698a-4659-acaf-a12db270ff25)
![1702799584916](https://github.com/1Panel-dev/1Panel/assets/51264840/5396ffb8-2ed7-49f2-b01d-4a385ee61c82)

_No response_

**Comment by ssongliu** [comment]
感谢反馈，这里应该是命令超时导致，后续版本优化。

是虚拟机吗？

**Comment by 9a6c** [comment]
不是虚拟机，阿里云的轻量级服务器

**Comment by ssongliu** [comment]
> 不是虚拟机，阿里云的轻量级服务器

可以手动执行一下 systemctl restart fail2ban.service ，看看是否特别耗时。

**Comment by 9a6c** [comment]
我测试了一下， 这个命令大约需要1分半左右才执行完成

**Comment by 9a6c** [comment]
请问  这里显示的和 Fail2ban禁用的ip是一样的吗
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/a4a215bc-7299-4129-a2be-d6704e37a82c)

**Comment by 9a6c** [comment]
上面的 IP 规则界面方便添加归属地吗？如登陆日志页面
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/1c2477ed-7d69-4a08-a22d-95616aaa3f23)

**Comment by ssongliu** [comment]
> 请问 这里显示的和 Fail2ban禁用的ip是一样的吗 ![image](https://private-user-images.githubusercontent.com/51264840/291141794-a4a215bc-7299-4129-a2be-d6704e37a82c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NzAzMjcsIm5iZiI6MTcwMjg3MDAyNywicGF0aCI6Ii81MTI2NDg0MC8yOTExNDE3OTQtYTRhMjE1YmMtNzI5OS00MTI5LWEyYmUtZDY3MDRlMzdhODJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDAzMjcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NGE5ZDFmNzYzODJhYmNlNTg5MTRmZWEwZGE4NDY1ZGQyZjg0YWY0OWE5MGUxYjM3ZWIwMzhkMjcyZDUwZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WQOxhH_L2QID3UhUIWNMZXisvxDeTlOnIGKbgNC8IfM)

不一样，一个手动禁用，一个自动拦截。

**Comment by wanghe-fit2cloud** [comment]
> 上面的 IP 规则界面方便添加归属地吗？

建议再单独开一个 issues。

**Comment by 9a6c** [comment]
> > 上面的 IP 规则界面方便添加归属地吗？
> 
> 建议再单独开一个 issues。

ok

**Comment by wanghe-fit2cloud** [comment]
v1.9.2 版本已发布。
