### ISSUE TITLE
[FEATURE]SSH 监听端口 IPv4 和 IPv6 不应该二选一

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [1Panel-dev/1Panel#3359]
### 1Panel 版本

v1.9.1

### 请描述您的需求或者改进建议

如题，在ssh配置和面板配置里v4/v6监听地址是互斥的，实际上完全可以共存，完全没必要强迫用户选择v6v4

**Comment by wanghe-fit2cloud** [comment]
是的，1Panel 在安装阶段就会自动获取服务器 IP（IPv4 或者 IPv6） 来绑定系统端口，也支持用户在面板设置页面或者 1pctl 命令来切换监听 IP。
> 系统不支持端口同时绑定 tcp 和 tcp6。

**Comment by Mr-Ao-Dragon** [comment]
> 是的，1Panel 在安装阶段就会自动获取服务器 IP（IPv4 或者 IPv6） 来绑定系统端口，也支持用户在面板设置页面或者 1pctl 命令来切换监听 IP。
> 
> > 系统不支持端口同时绑定 tcp 和 tcp6。

ssh就不要二选一了吧

**Comment by wanghe-fit2cloud** [comment]
> ssh就不要二选一了吧

好的，我们先调研一下 sshd 是否支持。

**Comment by wanghe-fit2cloud** [comment]
v1.9.2 版本已发布。
