### ISSUE TITLE
[FEATURE]可否提供一个定时自动备份到网盘的功能？

### ISSUE THREAD

**Issue by rain-xray** [1Panel-dev/1Panel#3360]
### 1Panel 版本

v1.9.1

### 请描述您的需求或者改进建议

现在比较担心服务器里面的数据库，如果额能够提供一个网盘备份功能就好了。

**Comment by wanghe-fit2cloud** [comment]
目前系统已支持创建备份数据库类型计划任务，并支持上传至第三方备份账号。
> 首先，需要进入 `面板设置` - `备份账号` 页面添加第三方备份账号。
