### ISSUE TITLE
[BUG]无法启用禁Ping功能

### ISSUE THREAD

**Issue by cclucky1** [1Panel-dev/1Panel#3361]
### 联系方式

fade@tom.com

### 1Panel 版本

v1.9.1

### 问题描述

启用禁Ping功能报错
ufw已安装
系统为Armbian
![image](https://github.com/1Panel-dev/1Panel/assets/53963267/1d241483-02bc-425a-8a64-a23c7d985dc4)

### 重现步骤

点击禁Ping

### 相关日志输出

```shell
服务内部错误: update ping status failed, err: stderr: sysctl: cannot stat /proc/sys/net/netfilter/nf_conntrack_helper: No such file or directory ; stdout: kernel.printk = 7 4 1 7 vm.swappiness = 100 vm.max_map_count = 262144 kernel.hung_task_timeout_secs = 0 kernel.msgmax = 65536 kernel.msgmnb = 65536 net.core.default_qdisc = fq net.ipv4.tcp_congestion_control = bbr net.ipv4.ip_local_port_range = 1024 65535 net.ipv4.conf.default.arp_ignore = 1 net.ipv4.conf.all.arp_ignore = 1 net.ipv4.ip_forward = 1 net.ipv4.icmp_echo_ignore_broadcasts = 1 net.ipv4.icmp_ignore_bogus_error_responses = 1 net.ipv4.igmp_max_memberships = 100 net.ipv4.tcp_fin_timeout = 30 net.ipv4.tcp_keepalive_time = 120 net.ipv4.tcp_syncookies = 1 net.ipv4.tcp_timestamps = 1 net.ipv4.tcp_sack = 1 net.ipv4.tcp_dsack = 1 net.ipv6.conf.default.forwarding = 1 net.ipv6.conf.all.forwarding = 1 net.core.rmem_max = 4194304 net.core.wmem_max = 1048576 net.netfilter.nf_conntrack_acct = 1 net.netfilter.nf_conntrack_checksum = 0 net.netfilter.nf_conntrack_max = 65535 net.netfilter.nf_conntrack_tcp_timeout_established = 7440 net.netfilter.nf_conntrack_udp_timeout = 60 net.netfilter.nf_conntrack_udp_timeout_stream = 180 net.ipv4.icmp_echo_ignore_all = 1
```

**Comment by ssongliu** [comment]
感谢反馈，这里是否存在  /proc/sys/net/ipv4/icmp_echo_ignore_all 这个文件呢？暂时还没适配过该系统。

**Comment by cclucky1** [comment]
这个文件是存在的，不知道出现了什么问题
![CleanShot 2023-12-18 at 16 19 45@2x](https://github.com/1Panel-dev/1Panel/assets/53963267/fb84f8ac-c5d8-414d-8482-48c411563d01)

**Comment by ssongliu** [comment]
可以执行一下 lsmod | grep conntrack 
如果返回为空则表示 conntrack 未正常加载，可以执行 modprobe ip_conntrack 重新加载一下，最后重试禁ping

**Comment by ssongliu** [comment]
暂时先关闭该 issue 了，后续还有问题可以继续回复。

**Comment by cclucky1** [comment]
问题仍然存在，执行lsmod | grep conntrack后有输出，尝试重新加载也是之前的状态
![image](https://github.com/1Panel-dev/1Panel/assets/53963267/611f7f7f-0f5b-4763-807e-6b7591f0a40c)

**Comment by wanghe-fit2cloud** [comment]
> 问题仍然存在，执行lsmod | grep conntrack后有输出，尝试重新加载也是之前的状态

应该是 1Panel 未完全适配 Armbian 操作系统的问题（也可以尝试手动升级一下系统 kernel 版本）
> 由于我们暂无计划适配该操作系统，就先关闭该 issue 了，望理解。

**Comment by ssongliu** [comment]
应该是缺少某个依赖，这是 ubuntu 的
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/91fc5d98-cfcb-4b1a-bace-ff46e6434eeb)
