### ISSUE TITLE
[FEATURE] 建议应用商店里的Gitea部署支持使用SQLite数据库

### ISSUE THREAD

**Issue by YaKun9** [1Panel-dev/1Panel#3367]
### 1Panel 版本

1.9.1

### 请描述您的需求或者改进建议

gitea是支持sqlite的,但是应用商店里部署的时候必须要选择一个数据库

### 请描述你建议的实现方案

支持选择sqlite

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们这边推荐使用 Gitea + MySQL 的方式来部署 Gitea 服务。
> 如果要使用 Gieta + SQLite3 方案，可以进入 `容器` - `编排` 页面来手动创建编排。

**Comment by YaKun9** [comment]
> 感谢反馈，我们这边推荐使用 Gitea + MySQL 的方式来部署 Gitea 服务。
> 
> > 如果要使用 Gieta + SQLite3 方案，可以进入 `容器` - `编排` 页面来手动创建编排。

但是最终选择应该交给用户来选择。使用sqlite部署，在备份和迁移的时候非常方便

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈，我们这边推荐使用 Gitea + MySQL 的方式来部署 Gitea 服务。
> > > 如果要使用 Gieta + SQLite3 方案，可以进入 `容器` - `编排` 页面来手动创建编排。
> 
> 但是最终选择应该交给用户来选择。使用sqlite部署，在备份和迁移的时候非常方便

那就通过 `容器` - `编排` 功能来维护吧。

**Comment by gwnpeter** [comment]
顶顶，升级镜像，会覆盖原来手动改的的sqlite3设置。原来已经使用了sqlite3，不方便迁移到mysql
