### ISSUE TITLE
[BUG] ssh终端连接失败

### ISSUE THREAD

**Issue by leochen12-rgb** [1Panel-dev/1Panel#3368]
### 1Panel 版本

v1.9.1

### 问题描述

点击web上主机-终端，直接连接本机127.0.0.1:22，提示Authentication failed.  Please check the host information !
不能正确连接到ssh上

### 重现步骤

不能正确连接到本地主机，也无法修改和删除默认的主机地址连接

### 期待的正确结果

正确识别内网和公网地址，允许修改默认主机的地址

**Comment by wanghe-fit2cloud** [comment]
1、ssh 命令进入 1Panel 服务器，然后手动执行 ssh root@127.0.0.1 命令，是否正常？
2、在 `主机` 页面，添加内网、公网服务器，是否可以正常添加？

**Comment by leochen12-rgb** [comment]
> ssh root@127.0.0.1

[root@R-1-1-1-1 ~]# ssh root@127.0.0.1
The authenticity of host '127.0.0.1 (127.0.0.1)' can't be established.
ED25519 key fingerprint is SHA256:6oKfThmaZf+sy4jKQymbB+sb8AVjpeQ1sR5RUhoE7tI.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '127.0.0.1' (ED25519) to the list of known hosts.
root@127.0.0.1's password: 

ssh root@127.0.0.1可以正常连接，连接前需要输入yes。
新增内网/公网地址配置后可以正常连接ssh
后续能否修复此bug，点击终端后直接连接到本地服务器，类似cockpit

**Comment by wanghe-fit2cloud** [comment]
手动执行 ssh root@127.0.0.1 命令并输入 yes，然后在 1Panel 页面就可以正常使用了，是这个意思吗？

**Comment by leochen12-rgb** [comment]
> 手动执行 ssh root@127.0.0.1 命令并输入 yes，然后在 1Panel 页面就可以正常使用了，是这个意思吗？

不是的，手动执行ssh root@127.0.0.1 命令并输入 yes后只能在shell本地正常登录，在web终端界面依然提示Authentication failed. Please check the host information !

**Comment by wanghe-fit2cloud** [comment]
在 `主机` 页面，添加服务器的内网（非 127.0.0.1），是否可以正常添加？
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/b00544e6-796d-4007-ba5d-39e783a9cac3)

**Comment by leochen12-rgb** [comment]
> 在 `主机` 页面，添加服务器的内网（非 127.0.0.1），是否可以正常添加？

以添加主机的方式可以正常连接到本地服务器，但是点击终端的时候不能把添加的主机设为默认登录shell，需要手动添加连接标签

**Comment by ssongliu** [comment]
可以尝试在 ~/.ssh/known_hosts  文件中写入 127.0.0.1 + key

**Comment by leochen12-rgb** [comment]
> 可以尝试在 ~/.ssh/known_hosts 文件中写入 127.0.0.1 + key

可以了
