### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by heiOneboy** [1Panel-dev/1Panel#3369]
### 请描述您的问题

假设我现在有一个前端项目，使用的是vue编写的，在打包成dist文件之后，上传到panel，这样的项目能使用1panel进行网站前端部署吗，如果可以，是如何操作呢

**Comment by wanghe-fit2cloud** [comment]
可以创建 `Node.js 运行环境` 网站，参考：
https://www.bilibili.com/video/BV1uc411R7NS
