### ISSUE TITLE
[BUG]MinIO更新后无法登录

### ISSUE THREAD

**Issue by lbbit** [1Panel-dev/1Panel#3371]
### 联系方式

790793725@qq.com

### 1Panel 版本

v1.9.1

### 问题描述

1Panel版本：v1.9.1
MinIO更新前版本：RELEASE.2023-05-04T21-44-30Z
MinIO更新后版本：1205版本

### 问题现象：

更新后MiniIO使用之前的用户名密码无法登录，回退到备份的版本后恢复正常

### 重现步骤

- 操作步骤：升级MinIO后尝试登录
- 问题概率：未尝试复现

### 期待的正确结果

可以正常登录

**Comment by zhengkunwang223** [comment]
为了版本升级 RELEASE.2023-05-04T21-44-30Z 之后我们修改了 docker-compose.yml 文件
如果你升级后无法访问 
可以在已安装页面进入 MinIO 的安装目录
修改 .env 文件
MINIO_ROOT_USER 改为 PANEL_MINIO_ROOT_USER
MINIO_ROOT_PASSWORD 改为 PANEL_MINIO_ROOT_PASSWORD
然后重建

**Comment by lbbit** [comment]
@zhengkunwang223 
按照你的提示修改后升级可以正常登录了；
但是已安装应用页面--MinIO--参数--显示的用户密码值不正确

**Comment by zhengkunwang223** [comment]
> @zhengkunwang223 按照你的提示修改后升级可以正常登录了； 但是已安装应用页面--MinIO--参数--显示的用户密码值不正确

这个暂时没办法处理了 毕竟我们修改了一些配置 但是正常用肯定没问题

**Comment by lbbit** [comment]
了解，感谢感谢~
