### ISSUE TITLE
[FEATURE]容器列表展示样式优化

### ISSUE THREAD

**Issue by Jengro777** [1Panel-dev/1Panel#3373]
### 1Panel 版本

1.9.1

### 请描述您的需求或者改进建议

目前 1Panel 的 docker 容器展示完全平铺， 遇到单个应用多容器的时候 不能直观的表达每个容器所属的应用

### 请描述你建议的实现方案

参考 dockerdesktop 展示和管理
![image](https://github.com/1Panel-dev/1Panel/assets/35259040/f976a887-0fb2-4c6e-a534-d01f9a09720c)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，docker-compose 维护的应用可以进入 `容器` - `编排` 页面查看相关服务，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/7b55fb86-24eb-4883-af49-4dff45ee751c)

**Comment by Jengro777** [comment]
> 感谢反馈，docker-compose 维护的应用可以进入 `容器` - `编排` 页面查看相关服务，如图： ![image](https://private-user-images.githubusercontent.com/46734380/291203944-7b55fb86-24eb-4883-af49-4dff45ee751c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODk5NTksIm5iZiI6MTcwMjg4OTY1OSwicGF0aCI6Ii80NjczNDM4MC8yOTEyMDM5NDQtN2I1NWZiODYtMjRlYi00ODgzLWFmNDktNGRmZjQ1ZWU3NTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA4NTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5NzAyOGJjYmI1NTZkOTgyZjZkODk0ZDA5MjAzNjM0NTgzZTVjZDU2MGI2NjNkZDhhYTQwNjM5MGJlYzEwMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sTGA2DyxtlgV5ldhXOjwfL2W6v9tOwp15O4fKNdpvLs)

我的意思是展示样式， 已经截图 看到同一个应用同时使用多个容器的时候的展示样式。 一但部署多个这样的应用， 在 1Panel 看 是很混乱的

**Comment by Jengro777** [comment]
同一个应用应该 有层级展示

**Comment by wanghe-fit2cloud** [comment]
> 同一个应用应该 有层级展示

第一次已经给出了回复，如果应用是通过 docker-compose 维护，可以进入 `编排` 页面查看相关的容器。
