### ISSUE TITLE
[FEATURE]多容器应用，层级列表展示 （未明白意思前请不要关闭，谢谢合作）

### ISSUE THREAD

**Issue by Jengro777** [1Panel-dev/1Panel#3374]
### 1Panel 版本

1.9.1

### 请描述您的需求或者改进建议

请仔细看看 docker desktop 的容器层级展示， 这里确实可以优化

#3373

### 请描述你建议的实现方案

![image](https://github.com/1Panel-dev/1Panel/assets/35259040/355a0adf-a88a-4f5d-85a4-55703365cd75)

**Comment by ssongliu** [comment]
一个应用对应多个容器时，可以通过编排界面查看，点击编排名称可以看到里面对应的容器，也就是你说的分层展示的意思。

容器列表只是单纯的展示所有容器，编排那边才有层级关系。
