### ISSUE TITLE
[FEATURE]建议面板添加一个域名管理功能

### ISSUE THREAD

**Issue by z1073** [1Panel-dev/1Panel#3375]
### 1Panel 版本

1.9.1

### 请描述您的需求或者改进建议

现在的域名供应商基本都有提供API， 有时候添加个二级域名A记录啥的还得去打开不同域名商网站里添加，或者自己弄脚本，如果1panel直接支持就更方便了 ：）

### 请描述你建议的实现方案

在网站管理处增添一个域名管理，可以添加域名商的API信息之类，然后能进行一些常用操作

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑是否支持上述需求。

**Comment by mx2913** [comment]
泛域名解析过来就可以了
