### ISSUE TITLE
[FEATURE] 2FA input type 优化、添加前一组容错设计

### ISSUE THREAD

**Issue by bee10301** [1Panel-dev/1Panel#3377]
### 1Panel 版本

1.9.1

### 请描述您的需求或者改进建议

1. 2FA 手机操作时键盘不友好。
2. 有时使用移动端设备登入，2FA刚好在刷新前几秒，速度不够快切回页面输入时已经过期。

### 请描述你建议的实现方案

1. 输入框设定数字类型，使手机输入时弹出数字键盘
2. 有些网站会采取前一组也能通过的容错设计，觉得可以考虑让前一组code也能过2FA

### 附加信息

再次感谢，团队辛苦了

**Comment by wanghe-fit2cloud** [comment]
> 2. 有些网站会采取前一组也能通过的容错设计，觉得可以考虑让前一组code也能过2FA

1Panel 使用的 SDK 不支持容错校验，不过，你可以在开启两步验证时增加刷新时间，如图：

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/5d2c2464-c415-4258-9988-a2d80ed686c0)
