### ISSUE TITLE
[BUG]暗色模式下，本地连接终端地址看不清

### ISSUE THREAD

**Issue by wangzhishang0204** [1Panel-dev/1Panel#3378]
### 1Panel 版本

v1.9.1

### 问题描述

终端- 127.0.0.1的终端连接，在暗色模式模式下，地址看不清
![image](https://github.com/1Panel-dev/1Panel/assets/63093589/e513449b-4cf3-44af-99d7-55d492cd7a3d)

### 重现步骤

暗色模式，本地终端127.0.0.1的地址看不清

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述终端显示问题。

**Comment by wanghe-fit2cloud** [comment]
v1.9.2 版本已发布。
