### ISSUE TITLE
[FEATURE]面板别名希望能恢复支持中划线和中文

### ISSUE THREAD

**Issue by lainbo** [1Panel-dev/1Panel#3380]
### 1Panel 版本

1.9.1

### 请描述您的需求或者改进建议

面板设置 - 面板别名现在不支持`中文`和`-`中划线了，这给辨认浏览器标签带来了一定的困扰，希望能恢复支持中文和中划线
![image](https://github.com/1Panel-dev/1Panel/assets/46062895/60cf5459-76ad-4d60-aa6b-8ff48f3ce778)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.9.2 版本已发布。
