### ISSUE TITLE
[FEATURE]备份支持阿里云OSS归档直读功能

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [1Panel-dev/1Panel#3383]
### 1Panel 版本

v1.9.1

### 请描述您的需求或者改进建议

阿里云的归档存储类型支持归档直读，希望能兼容该功能

### 请描述你建议的实现方案

详情参阅阿里云oss归档相关章节

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在后续版本先调研一下上述需求的可行性方案。

**Comment by ssongliu** [comment]
归档存储需要先解冻才能下载。

![image](https://github.com/1Panel-dev/1Panel/assets/73214554/bc4c933b-412f-43f7-8fe5-19f4c675c811)

**Comment by Mr-Ao-Dragon** [comment]
> 归档存储需要先解冻才能下载。
> 
> ![image](https://github.com/1Panel-dev/1Panel/assets/73214554/bc4c933b-412f-43f7-8fe5-19f4c675c811)

https://help.aliyun.com/document_detail/2392251.html?spm=5176.8465980.help.dexternal.174a1450ie1Yhzhttps://help.aliyun.com/document_detail/2392251.html?spm=5176.8465980.help.dexternal.174a1450ie1Yhz

**Comment by ssongliu** [comment]
> > 归档存储需要先解冻才能下载。
> > ![image](https://private-user-images.githubusercontent.com/73214554/291525985-bc4c933b-412f-43f7-8fe5-19f4c675c811.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODA5NDMsIm5iZiI6MTcwMjk4MDY0MywicGF0aCI6Ii83MzIxNDU1NC8yOTE1MjU5ODUtYmM0YzkzM2ItNDEyZi00M2Y3LThmZTUtMTlmNGM2NzVjODExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDEwMTA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MDMxMWNmOGE1YWU5NDc4ZGNmMjViY2UxZTlhN2MwYWI4YWQzNDcxNDRiZTA4ODM3ZDczM2MwMTE2ZTQ0ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7-AvHn10ngBhiHVqd_h9HXqPNRGddlq0MESGlqOhtl0)
> 
> https://help.aliyun.com/document_detail/2392251.html?spm=5176.8465980.help.dexternal.174a1450ie1Yhzhttps://help.aliyun.com/document_detail/2392251.html?spm=5176.8465980.help.dexternal.174a1450ie1Yhz

您那边阿里云 OSS 存储里归档存储的文件可以不解冻直接下载吗？

**Comment by Mr-Ao-Dragon** [comment]
> > > 归档存储需要先解冻才能下载。
> > > ![image](https://private-user-images.githubusercontent.com/73214554/291525985-bc4c933b-412f-43f7-8fe5-19f4c675c811.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODA5NDMsIm5iZiI6MTcwMjk4MDY0MywicGF0aCI6Ii83MzIxNDU1NC8yOTE1MjU5ODUtYmM0YzkzM2ItNDEyZi00M2Y3LThmZTUtMTlmNGM2NzVjODExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDEwMTA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MDMxMWNmOGE1YWU5NDc4ZGNmMjViY2UxZTlhN2MwYWI4YWQzNDcxNDRiZTA4ODM3ZDczM2MwMTE2ZTQ0ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7-AvHn10ngBhiHVqd_h9HXqPNRGddlq0MESGlqOhtl0)
> > 
> > 
> > https://help.aliyun.com/document_detail/2392251.html?spm=5176.8465980.help.dexternal.174a1450ie1Yhzhttps://help.aliyun.com/document_detail/2392251.html?spm=5176.8465980.help.dexternal.174a1450ie1Yhz
> 
> 您那边阿里云 OSS 存储里归档存储的文件可以不解冻直接下载吗？

我尝试一下

**Comment by Mr-Ao-Dragon** [comment]
> > > > 归档存储需要先解冻才能下载。
> > > > ![image](https://private-user-images.githubusercontent.com/73214554/291525985-bc4c933b-412f-43f7-8fe5-19f4c675c811.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODA5NDMsIm5iZiI6MTcwMjk4MDY0MywicGF0aCI6Ii83MzIxNDU1NC8yOTE1MjU5ODUtYmM0YzkzM2ItNDEyZi00M2Y3LThmZTUtMTlmNGM2NzVjODExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDEwMTA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MDMxMWNmOGE1YWU5NDc4ZGNmMjViY2UxZTlhN2MwYWI4YWQzNDcxNDRiZTA4ODM3ZDczM2MwMTE2ZTQ0ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7-AvHn10ngBhiHVqd_h9HXqPNRGddlq0MESGlqOhtl0)
> > > 
> > > 
> > > https://help.aliyun.com/document_detail/2392251.html?spm=5176.8465980.help.dexternal.174a1450ie1Yhzhttps://help.aliyun.com/document_detail/2392251.html?spm=5176.8465980.help.dexternal.174a1450ie1Yhz
> > 
> > 
> > 您那边阿里云 OSS 存储里归档存储的文件可以不解冻直接下载吗？
> 
> 我尝试一下

![image](https://github.com/1Panel-dev/1Panel/assets/67987607/cdabd1da-323b-475e-b63a-014c37b4d4da)
![image](https://github.com/1Panel-dev/1Panel/assets/67987607/c5f474a0-294a-430e-8ef6-e4ec0e5a92d5)

**Comment by Mr-Ao-Dragon** [comment]
> > > > > 归档存储需要先解冻才能下载。
> > > > > ![image](https://private-user-images.githubusercontent.com/73214554/291525985-bc4c933b-412f-43f7-8fe5-19f4c675c811.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODA5NDMsIm5iZiI6MTcwMjk4MDY0MywicGF0aCI6Ii83MzIxNDU1NC8yOTE1MjU5ODUtYmM0YzkzM2ItNDEyZi00M2Y3LThmZTUtMTlmNGM2NzVjODExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDEwMTA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MDMxMWNmOGE1YWU5NDc4ZGNmMjViY2UxZTlhN2MwYWI4YWQzNDcxNDRiZTA4ODM3ZDczM2MwMTE2ZTQ0ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7-AvHn10ngBhiHVqd_h9HXqPNRGddlq0MESGlqOhtl0)
> > > > 
> > > > 
> > > > https://help.aliyun.com/document_detail/2392251.html?spm=5176.8465980.help.dexternal.174a1450ie1Yhzhttps://help.aliyun.com/document_detail/2392251.html?spm=5176.8465980.help.dexternal.174a1450ie1Yhz
> > > 
> > > 
> > > 您那边阿里云 OSS 存储里归档存储的文件可以不解冻直接下载吗？
> > 
> > 
> > 我尝试一下
> 
> ![image](https://private-user-images.githubusercontent.com/67987607/291558749-cdabd1da-323b-475e-b63a-014c37b4d4da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODMwOTAsIm5iZiI6MTcwMjk4Mjc5MCwicGF0aCI6Ii82Nzk4NzYwNy8yOTE1NTg3NDktY2RhYmQxZGEtMzIzYi00NzVlLWI2M2EtMDE0YzM3YjRkNGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDEwNDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4N2FmZjBhNjA2MjEyMTk3OGU3YTM1N2I2Y2I3MmNiZmI3MGI3OTlmOWUwY2Y5N2Y4ZWY2MmNmNWM5ZDhjMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ponInHJcGxNRRtKLfBv9v_s3hg9PSI1mlGStpqnVeQ0) ![image](https://private-user-images.githubusercontent.com/67987607/291559343-c5f474a0-294a-430e-8ef6-e4ec0e5a92d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODMwOTAsIm5iZiI6MTcwMjk4Mjc5MCwicGF0aCI6Ii82Nzk4NzYwNy8yOTE1NTkzNDMtYzVmNDc0YTAtMjk0YS00MzBlLThlZjYtZTRlYzBlNWE5MmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDEwNDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OTgzMWNiNmQxZGI2YzIxOGMzYjliMzA0YTExNzMwMDc1Yzg3YTU5YjQyM2E2ODJjODc2MjJhZTk5YjE2N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OMueg2HoAYKurk_Ul_txbYlNNqgr7HWnHRZHyDAHIMw)

这是api
查询有没有开：
https://help.aliyun.com/zh/oss/getbucketarchivedirectread#main-2356191
对这个功能进行开关
https://help.aliyun.com/zh/oss/putbucketarchivedirectread#main-2356189

**Comment by Mr-Ao-Dragon** [comment]
@wanghe-fit2cloud

**Comment by wanghe-fit2cloud** [comment]
感谢，经团队内部讨论，暂时不会考虑针对 `阿里云OSS` 归档存储进行单独处理。
> 建议你考虑使用低频存储。
