### ISSUE TITLE
[FEATURE]添加主机 > 用户/用户组管理功能

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [1Panel-dev/1Panel#3385]
### 1Panel 版本

v1.9.1

### 请描述您的需求或者改进建议

如题，1panel没有该功能，竞品宝塔也没有，做出此功可领先宝塔一步

**Comment by wanghe-fit2cloud** [comment]
麻烦再详细描述一下上述功能点（是多主机管理功能、多用户权限体系还是主机终端中的用户管理等）
> 集成 chown 等效功能可以再单独开一个 issue 并详细描述。

**Comment by Mr-Ao-Dragon** [comment]
> 麻烦再详细描述一下上述功能点（是多主机管理功能、多用户权限体系还是主机终端中的用户管理等）
> 
> > 集成 chown 等效功能可以再单独开一个 issue 并详细描述。

才看到已经有了，已开

**Comment by wanghe-fit2cloud** [comment]
请问，是要做 `/etc/passwd` 和 `/etc/group` 的可视化管理吗？

**Comment by Mr-Ao-Dragon** [comment]
> 请问，是要做 `/etc/passwd` 和 `/etc/group` 的可视化管理吗？

差不多，能做 /etc/sudoers 可视化就更好了

**Comment by wanghe-fit2cloud** [comment]
重复 issue #2648
