### ISSUE TITLE
[QUESTION] 本地数据库迁移

### ISSUE THREAD

**Issue by zhihancn** [1Panel-dev/1Panel#3392]
### 请描述您的问题

使用第三方工具可以正常登录并移植数据。

<img width="306" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/40417178/23abd329-c5b9-49e3-8940-f2f5c0313ca5">

在面板中看不到迁移后的数据

<img width="990" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/40417178/aba58b8b-0619-4da7-91fe-af42f168939b">

尝试在第三方工具下创建数据库。在面板中看不到创建的数据库。

<img width="291" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/40417178/04dedf19-141e-45d1-9899-846edfb00cd3">

没有找到面板刷新的按钮。

希望能得到大佬的回答。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
如果是要将服务端已存在数据库同步到 1Panel 页面，可以点击 `从服务器获取` 按钮。

**Comment by BlueNoob** [comment]
> 感谢反馈。 如果是要将服务端已存在数据库同步到 1Panel 页面，可以点击 `从服务器获取` 按钮。

他问的不清楚，你答的感觉也不对。
感觉不是系统问题，使用问题。

**Comment by BlueNoob** [comment]
你先创建个空数据库，然后再迁移试试？
