### ISSUE TITLE
[BUG]当使用snap安装docker时，1panel无法重启docker进程

### ISSUE THREAD

**Issue by vybfi** [1Panel-dev/1Panel#3394]
### 联系方式

2891489708@qq.com

### 1Panel 版本

v1.9.1

### 问题描述

当使用snap安装docker时，1panel无法重启docker进程。提示报错
`服务内部错误: stderr: Failed to restart docker.service: Unit docker.service not found.`
我猜测是snap版docker的重启命令为`snap restart docker`而不是`service docker start`的原因

### 重现步骤

部署一台ubuntu22的虚拟机，在安装系统时勾选同时安装docker。这时安装的就是snap版本的docker。
然后安装1panel，进入docker设置面板，修改加速地址并确定，然后输入立即重启后确认。
即可看到报错

### 期待的正确结果

应当和使用正常方式安装的docker产生一样的提示。
希望可以添加一个开关用于切换重启命令。

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/52736701/f056c6c0-c219-412f-a0a1-499bee7eac32)

**Comment by vybfi** [comment]
补充：我也没有办法切换cgroup-driver

**Comment by vybfi** [comment]
同时，从应用商店安装软件时都会失败，并提示`stderr: stat /opt/1panel/apps/mysql/mysql/docker-compose.yml: no such file or directory`
![image](https://github.com/1Panel-dev/1Panel/assets/52736701/dc35c1ae-567a-4d33-bc2c-f4207bd3d283)

**Comment by zhengkunwang223** [comment]
当前 1Panel 仅支持 systemctl 管理的 docker 进程
后续可能会考虑支持其他方式

**Comment by wanghe-fit2cloud** [comment]
重复 #3242
