### ISSUE TITLE
[QUESTION]webdav备份账号添加失败

### ISSUE THREAD

**Issue by Drizzle365** [1Panel-dev/1Panel#3395]
### 请描述您的问题

![image](https://github.com/1Panel-dev/1Panel/assets/61527377/8170293b-55d3-43e8-b8c9-4d0a3adbf988)

这是通过alist创建的webdav，本地使用正常，但是在1panel上无法创建
![image](https://github.com/1Panel-dev/1Panel/assets/61527377/154524b6-d07d-474e-96dd-14c0741c0d00)

**Comment by ssongliu** [comment]
感谢反馈，可以先检查一下内容是否正确：
1. 地址（协议）、端口是否正确；
2. 检查 webdav admin 的权限是否允许创建文件夹等操作。

**Comment by benzBrake** [comment]
你地址填错了，不能这么写，200 响应是你没访问到 dav
dav给加到路径里吧，不过我试了一下，改了报错500

**Comment by ssongliu** [comment]
> 你地址填错了，不能这么写，200 响应是你没访问到 dav dav给加到路径里吧，不过我试了一下，改了报错500

可以添加一下我好友，我远程看看这个问题
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/190e2fe8-862b-4e37-83e0-e150cfa5ccb6)
