### ISSUE TITLE
[BUG]使用1panel部署gitea，安全页面报404错误

### ISSUE THREAD

**Issue by CodeVoyagerWgy** [1Panel-dev/1Panel#3397]
### 联系方式

84314589@qq.com

### 1Panel 版本

1.9.1

### 问题描述

使用1panel一键部署部署gitea，打开设置的安全页面，报404错误
<img width="1318" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/54871918/f817ea74-67b3-48c2-b9cf-b277a1d1623a">
下图用docker手动部署的界面
![image](https://github.com/1Panel-dev/1Panel/assets/54871918/8500d22d-9527-4a74-9206-b3b5d4d2b3cd)

### 重现步骤

使用1panel一键部署部署gitea，打开设置的安全页面

### 相关日志输出

```shell
2023/12/20 11:27:45 ...eb/routing/logger.go:102:func1() [I] router: completed GET /user/settings/security for 100.94.210.148:62629, 404 Not Found in 17.9ms @ web/web.go:586(web.registerRoutes.func23.4)
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在本地环境已复现上述问题，近期版本会修复并推送更新。

**Comment by wanghe-fit2cloud** [comment]
Gitea v1.21.3 版本已推送更新。进入 `应用商店` 列表点击右上角的 `更新应用列表` 按钮，等待同步成功后进入 `可升级`  页面一键升级：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/090d9552-5918-437f-b36b-ff3cb963d933)
