### ISSUE TITLE
[FEATURE] 开发计划

### ISSUE THREAD

**Issue by BlueNoob** [1Panel-dev/1Panel#3401]
### 1Panel 版本

0

### 请描述您的需求或者改进建议

参考：
![image](https://github.com/1Panel-dev/1Panel/assets/4169222/43cd4ad7-e4b4-4af6-a780-18b5a860ea98)

**Comment by wanghe-fit2cloud** [comment]
感谢建议。
1Panel 的版本发布计划可以参考 [milestones](https://github.com/1Panel-dev/1Panel/milestones)
