### ISSUE TITLE
[BUG]halo  v2.6.0 升级到 v2.11.2 无法访问服务

### ISSUE THREAD

**Issue by liufei20151013** [1Panel-dev/1Panel#3403]
### 联系方式

liufei@fit2cloud.com

### 1Panel 版本

v1.9.1

### 问题描述

halo  v2.6.0 升级到 v2.11.2 无法访问服务

### 重现步骤

在1panel上安装 halo v2.6.0，然后升级到 v2.11.2

**Comment by wanghe-fit2cloud** [comment]
可以看一下是不是这篇文章中提到的问题：
https://bbs.halo.run/d/4362-%E9%80%9A%E8%BF%871panel%E5%8D%87%E7%BA%A7280--291%E5%90%8E%E5%90%AF%E5%8A%A8%E5%A4%B1%E8%B4%A5/2

**Comment by wanghe-fit2cloud** [comment]
经远程协助定位问题，发现是插件问题导致的，相关问题链接：
https://bbs.halo.run/d/4801-%E4%BD%BF%E7%94%A8%E5%A4%87%E4%BB%BD%E6%81%A2%E5%A4%8D%E5%90%8Eweb%E9%A1%B5%E9%9D%A2%E6%89%93%E4%B8%8D%E5%BC%80/6
