### ISSUE TITLE
[BUG] 登录成功后 跳回登录界面

### ISSUE THREAD

**Issue by BlueNoob** [1Panel-dev/1Panel#3404]
### 1Panel 版本

1.9.1

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/4169222/135e861c-3716-43c1-b3b1-89bc1a24a92d)
提升登录成功后，还是跳转到了登录界面。
之前遇到过，重启服务后正常登录。
到底是什么问题，是磁盘空间问题，导致的redis的问题吗？
如何精准定位相关问题日志？

### 重现步骤

无法复现，不知道什么时候就出问题了

### 附加信息
目前定位到是cf问题，cf是默认配置。
cf上删除缓存后，能够正常登录。
希望1panel能够提供进一步技术支持，定位到根本问题，谢谢

**Comment by zhengkunwang223** [comment]
已经在 cloudflare 部署了一个 1Panel 后续我们会持续观察是否有该问题

**Comment by yuyanlike** [comment]
> 已经在 cloudflare 部署了一个 1Panel 后续我们会持续观察是否有该问题

同遇到该问题，在edge浏览器，更换chrome后登录成功  可以尝试该方法 @BlueNoob
