### ISSUE TITLE
[BUG] 让1pctl 默认== 1pctl help 吧

### ISSUE THREAD

**Issue by BlueNoob** [1Panel-dev/1Panel#3405]
### 1Panel 版本

1.9.1

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/4169222/e9a291e2-a1d6-41b9-9471-de9bc86c8b2c)
[BUG] 让1pctl 默认== 1pctl help 吧
这个设计逻辑，着实有点那啥...

### 期待的正确结果
直接敲1pctl，==  1pctl help

**Comment by wanghe-fit2cloud** [comment]
后续版本优化。
> 也可以尝试给项目提交 pr，installer 项目地址：https://github.com/1Panel-dev/installer

**Comment by BlueNoob** [comment]
> 后续版本优化。
> 
> > 也可以尝试给项目提交 pr，installer 项目地址：https://github.com/1Panel-dev/installer

难怪在1panel界面，我找不到脚本

**Comment by wanghe-fit2cloud** [comment]
> > 后续版本优化。
> > > 也可以尝试给项目提交 pr，installer 项目地址：https://github.com/1Panel-dev/installer
> 
> 难怪在1panel界面，我找不到脚本

是的，我们独立了一个 installer 项目。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
