### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by OffroadOps** [1Panel-dev/1Panel#3408]
### 1Panel 版本

最新版

### 请描述您的需求或者改进建议

能不能让1Panel 支持 openwrt x64 环境  默认这个支持docker 但是语法似乎有变化 推荐个 常用固件
https://openwrt.mpdn.fun:8443/?dir=lede/x86_64/

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们中短期内没有上述计划，望理解。

**Comment by wanghe-fit2cloud** [comment]
1Panel 最新版本的安装脚本已兼容 OpenWrt。
