### ISSUE TITLE
[FEATURE] 离线更新

### ISSUE THREAD

**Issue by BlueNoob** [1Panel-dev/1Panel#3409]
### 请描述您的需求或者改进建议

如何离线更新？

## online:
`1panel upgrade onilne`
## offline
`1panel upgrade /opt/location/1.9.2.tar.gz`

**Comment by BlueNoob** [comment]
https://bbs.fit2cloud.com/t/topic/864

**Comment by wanghe-fit2cloud** [comment]
> https://bbs.fit2cloud.com/t/topic/864

论坛中这篇帖子是开源大佬提供的解决方案，可以参考。
> 官方未提供离线安装、更新相关功能。

**Comment by BlueNoob** [comment]
> > https://bbs.fit2cloud.com/t/topic/864
> 
> 论坛中这篇帖子是开源大佬提供的解决方案，可以参考。
> 
> > 官方未提供离线安装、更新相关功能。

测试过了，正常使用，能够恢复我更新失败的站点。
既然如此，官方为何不加入功能？
![image](https://github.com/1Panel-dev/1Panel/assets/4169222/544467f2-5f4a-4253-aabd-2029fa753d2b)
