### ISSUE TITLE
[QUESTION]前端网站部署

### ISSUE THREAD

**Issue by zhihancn** [1Panel-dev/1Panel#3411]
### 请描述您的问题

为了保护源码，我不太愿意使用1panel自带的nodejs运行环境构建。转而想本地构建后再上传至1panel进行部署。

对于一个已经构建后前端项目(如run build后的vue、react项目。构建后的项目名称为dist)，推荐使用面板中哪一个应用进行部署呢？
<img width="209" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/40417178/9188f060-c13c-474d-9da3-e2c8f037b205">
我尝试使用openResty和NPM管理工具。不知道在哪里配置，希望大佬解惑

**Comment by wanghe-fit2cloud** [comment]
建议手动将项目容器化，然后通过容器菜单的 `创建容器` 或者 `创建编排` 功能来维护服务。
