### ISSUE TITLE
[BUG] 访问日志 IP不正确

### ISSUE THREAD

**Issue by BlueNoob** [1Panel-dev/1Panel#3412]
### 1Panel 版本

1.9.2

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/4169222/33420be7-fe14-43be-8057-7e79681eaa31)

### 重现步骤

1

**Comment by BlueNoob** [comment]
【CF】   https://.com==> 【VPS】 openrestry p:80/443  ==>网站  p:12345

**Comment by wanghe-fit2cloud** [comment]
> 【CF】 https://.com==> 【VPS】 openrestry p:80/443 ==>网站 p:12345

1、IP:Port 直接访问没有复现上述问题。
2、创建 1Panel 反向代理网站（OpenResty）没有复现上述问题。

可能还是 CF 设置问题。

**Comment by BlueNoob** [comment]
> > 【CF】 https://.com==> 【VPS】 openrestry p:80/443 ==>网站 p:12345
> 
> 1、IP:Port 直接访问没有复现上述问题。 2、创建 1Panel 反向代理网站（OpenResty）没有复现上述问题。
> 
> 可能还是 CF 设置问题。
> 
> <img alt="image" width="402" src="https://private-user-images.githubusercontent.com/46734380/291932946-00b167e3-38ae-4969-a65e-29fd1c57db32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDA3NjEsIm5iZiI6MTcwMzE0MDQ2MSwicGF0aCI6Ii80NjczNDM4MC8yOTE5MzI5NDYtMDBiMTY3ZTMtMzhhZS00OTY5LWE2NWUtMjlmZDFjNTdkYjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA2MzQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMjBjMDU4NGMzMTc5MjA3YmM0M2EwYTA0OTQwMDNjZWI1MjNkMDVmZmI1ODhiMzU5OTI5OTI0Njk0YTI2Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WuqHsmLKADqCRR6978EfToLVtV7zGvsH3xYmdIjBybs">

CF是默认配置，你的测试又没用CF，有何意义？

**Comment by BlueNoob** [comment]
open resty 我没用过，nginx 是需要配置realip模块，手动写入waf网段的。
不深入了解，不仔细研究，就close，这责任感，不敢恭维。
我跟你反馈河对面的树倒了，你跟我说你能顺利过河，桥没坏。

**Comment by wanghe-fit2cloud** [comment]
> open resty 我没用过，nginx 是需要配置realip模块，手动写入waf网段的。 不深入了解，不仔细研究，就close，这责任感，不敢恭维。 我跟你反馈河对面的树倒了，你跟我说你能顺利过河，桥没坏。

在上面的回复中已经说的很清楚，不是 1Panel 自身系统的问题（包括通过反向代理网站访问），请不要在这里断章取义。
我们也不会主动适配其他任何上层的第三方系统。

**Comment by BlueNoob** [comment]
> > open resty 我没用过，nginx 是需要配置realip模块，手动写入waf网段的。 不深入了解，不仔细研究，就close，这责任感，不敢恭维。 我跟你反馈河对面的树倒了，你跟我说你能顺利过河，桥没坏。
> 
> 我在上面的回复中已经说的很清楚，不是 1Panel 自身系统的问题（包括通过反向代理网站访问），请不要在这里断章取义。 我们也不会主动适配其他任何上层的第三方系统。

`2、创建 1Panel 反向代理网站（OpenResty）没有复现上述问题。`
请问，你前面套WAF了吗？
这是主动去适配第三方系统吗？
腾讯云WAF，阿里云WAF，CDN
![image](https://github.com/1Panel-dev/1Panel/assets/4169222/fb5c9b5b-bbf4-4bf0-930b-e7e9b9783017)
![image](https://github.com/1Panel-dev/1Panel/assets/4169222/d5e90f01-0f85-4235-a69c-7dcd3a5df530)

**Comment by BlueNoob** [comment]
WAF端，CDN端，是不需要设置的。
要改的，是中间件取IP处的配置参数。

**Comment by BlueNoob** [comment]
> > open resty 我没用过，nginx 是需要配置realip模块，手动写入waf网段的。 不深入了解，不仔细研究，就close，这责任感，不敢恭维。 我跟你反馈河对面的树倒了，你跟我说你能顺利过河，桥没坏。
> 
> 我在上面的回复中已经说的很清楚，不是 1Panel 自身系统的问题（包括通过反向代理网站访问），请不要在这里断章取义。 我们也不会主动适配其他任何上层的第三方系统。

实在是不好意思，看到你说的`适配`，我就很想笑。
