### ISSUE TITLE
[BUG] 网站日志 IP不正确，未忽略WAF IP

### ISSUE THREAD

**Issue by BlueNoob** [1Panel-dev/1Panel#3413]
### 1Panel 版本

1.9.2

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/4169222/4ee8115b-e434-451a-95da-c21e49936ac8)

### 重现步骤

1

**Comment by zhengkunwang223** [comment]
后续版本优化

**Comment by BlueNoob** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/4169222/02355e1f-26a0-487b-ae60-fd5db4b4c41f)

**Comment by zhengkunwang223** [comment]
> ![image](https://private-user-images.githubusercontent.com/4169222/292118414-02355e1f-26a0-487b-ae60-fd5db4b4c41f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDIyNjgsIm5iZiI6MTcwMzE0MTk2OCwicGF0aCI6Ii80MTY5MjIyLzI5MjExODQxNC0wMjM1NWUxZi0yNmEwLTQ4N2ItYWU2MC1mZDVkYjRiNGM0MWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMDY1OTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODcwN2UwNWQ4ZjQ2NWY0YWViNDhlYmM5MGQ1MTIzNTNhODJjYmJiOTQ4ZGZhMTIxOTEwNGQ4OTUwMTdlNTYxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gvEpEqvq7BpD_xWJI76B5Ql1yyIQGNvT1dpqYm2cZo4)

这种情况我们还需要在考虑和实验一下 如果可以的话 后续版本优化

**Comment by wanghe-fit2cloud** [comment]
重复 #
