### ISSUE TITLE
[FEATURE]  需要增加日志投递功能

### ISSUE THREAD

**Issue by BlueNoob** [1Panel-dev/1Panel#3414]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/4169222/19481210-8738-4ea4-8ce1-f611a46ddefb)
图片仅供参考，仅示例网站界面日志
### 需求：

1.  增加日志投递，最好是有统一的日志投递界面，一是方便投递，二是方便知道日志位置。包括但不限于网站1，网站2...N，SSH, FTP, 1panel 登录等。
2. 如果做不到以上，那至少要在单独的网站界面把相应的log投递出去，如access log, err log , 还有大多数网站依赖的sql log, slow sql log 等

**Comment by wanghe-fit2cloud** [comment]
1Panel 目前提供实时查看日志、日志下载等功能，暂不考虑支持数据投递相关功能，望理解。

**Comment by BlueNoob** [comment]
> 1Panel 目前提供实时查看日志、日志下载等功能，暂不考虑支持数据投递相关功能，望理解。

不用急着关闭，
```
最好是有统一的日志界面，
我知道所有的日志位置后，自行安排投递
```

**Comment by wanghe-fit2cloud** [comment]
网站日志，如图：
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/fc1b7856-f613-4d6f-9f6e-c3d562e85f9d">

**Comment by BlueNoob** [comment]
这个位置知道，网站多的话。一个个去翻不太好。
![image](https://github.com/1Panel-dev/1Panel/assets/4169222/d1c3bad4-106c-405d-a8d9-5f6a553cf26f)
