### ISSUE TITLE
[FEATURE]  什么是追踪？？

### ISSUE THREAD

**Issue by BlueNoob** [1Panel-dev/1Panel#3415]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/4169222/b59fee27-915f-484a-a649-063058e60a85)

界面上，需提示，追踪是什么功能？

**Comment by wanghe-fit2cloud** [comment]
<img width="786" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/cfd55561-d004-4400-b3f3-8ea65f56f345">
