### ISSUE TITLE
[FEATURE] 网站界面，增加WAF状态显示

### ISSUE THREAD

**Issue by BlueNoob** [1Panel-dev/1Panel#3416]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/4169222/17327a04-a39f-4930-ab03-7693fc7bbdcd)

**Comment by zhengkunwang223** [comment]
WAF 是默认启动的 没有不启动的配置

**Comment by BlueNoob** [comment]
> WAF 是默认启动的 没有不启动的配置

CC防护开发 等

**Comment by zhengkunwang223** [comment]
> > WAF 是默认启动的 没有不启动的配置
> 
> CC防护开发 等

配置项太多了 直接点 waf 去里面看就行
