### ISSUE TITLE
[FEATURE]希望添加实时日志

### ISSUE THREAD

**Issue by shenshangshang** [1Panel-dev/1Panel#3417]
### 1Panel 版本

v1.9.2

### 请描述您的需求或者改进建议

现在的计划任务只有任务运行完才能看到日志，希望添加像宝塔一样的实时日志

**Comment by wanghe-fit2cloud** [comment]
后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复 issue #2561
