### ISSUE TITLE
[BUG]WebDAV备份失败

### ISSUE THREAD

**Issue by springeye** [1Panel-dev/1Panel#3418]
### 1Panel 版本

v1.9.2

### 问题描述

添加webdav账号成功，测试链接的时候已经成功创建test目录，但是备份快照的时候失败了，403错误
![image](https://github.com/1Panel-dev/1Panel/assets/1314740/84eb61ed-0e01-465e-9781-1e7e8d06d1e4)
![image](https://github.com/1Panel-dev/1Panel/assets/1314740/0875afd8-d64a-44b4-a84c-9544bdd8ef6f)
![image](https://github.com/1Panel-dev/1Panel/assets/1314740/55228fa1-0583-4f7e-8092-6458bba5e9d7)

### 重现步骤

1、成功配置webdav账号（服务器是synology dsm）
2、创建快照，最后异步就失败

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by ssongliu** [comment]
看起来像是权限问题，请确认一下用户有足够的权限。

**Comment by springeye** [comment]
有权限，我用其他客户端测试同样的账号同样的目录可以正常上传

**Comment by wanghe-fit2cloud** [comment]
> 有权限，我用其他客户端测试同样的账号同样的目录可以正常上传

可以到计划任务菜单创建一个备份目录的任务，看是否能上传成功。

**Comment by springeye** [comment]
> > 有权限，我用其他客户端测试同样的账号同样的目录可以正常上传
> 
> 可以到计划任务菜单创建一个备份目录的任务，看是否能上传成功。

计划任务也失败了，
我用了好几个webdav客户端工具同一个账号是可以成功的
<img width="1365" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/1314740/c88a8b21-f9a7-43ec-ad7d-120937106610">

截图是用cadaver测试的

**Comment by ssongliu** [comment]
麻烦添加一下好友，我看看这个问题

<image src="https://github.com/1Panel-dev/1Panel/assets/73214554/b2b4f49d-228e-4047-ae24-91472e6cab2a" width="156px" height="156px">

**Comment by 531014023** [comment]
我遇到了一样的问题，添加webdav账号是成功的，但是计划任务备份到webdav报错403。
社区发帖链接
https://bbs.fit2cloud.com/t/topic/9454
