### ISSUE TITLE
[FEATURE]希望添加Dynadot DNS帐户 ，谢谢

### ISSUE THREAD

**Issue by Faraway2024** [1Panel-dev/1Panel#3419]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

域名是在Dynadot上购买的，希望添加对Dynadot DNS帐户 的支持，谢谢

**Comment by zhengkunwang223** [comment]
当前我们用的 lego https://github.com/go-acme/lego 来实现证书申请
所以我们会优先支持 lego 官方支持的 DNS 服务商 
https://go-acme.github.io/lego/dns/
Dynadot 并不在其中 所以短时间内我们不会支持 希望理解
