### ISSUE TITLE
[FEATURE] 商店安装的时候提供选项：安装完毕不立即启动

### ISSUE THREAD

**Issue by mobeicanyue** [1Panel-dev/1Panel#3420]
### 1Panel 版本

v1.9.2

### 请描述您的需求或者改进建议

商店安装的时候提供选项：安装完毕不立即启动。有些应用不是马上可以用到，或者安装完毕要改一下配置再手动启动

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by mobeicanyue** [comment]
你好？

**Comment by wanghe-fit2cloud** [comment]
经过讨论，目前我们暂无计划支持该需求，感谢理解。
