### ISSUE TITLE
[FEATURE]更新到最新版本证书api换了

### ISSUE THREAD

**Issue by haiwan-xm** [1Panel-dev/1Panel#3423]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

在之前的低版本的时候证书可以正常使用api调度生成证书
新版本不行了 多了一个申请确认的流程 导致流程比较麻烦了

**Comment by zhengkunwang223** [comment]
为了解决超时问题 所以我们拆分了接口 
请求完创建接口之后拿到ID然后去请求申请接口

**Comment by haiwan-xm** [comment]
那我们对接api这边有什么可以简化的吗？不然改动还蛮大的

**Comment by zhengkunwang223** [comment]
> 那我们对接api这边有什么可以简化的吗？不然改动还蛮大的

暂时没有

**Comment by zhengkunwang223** [comment]
> 那我们对接api这边有什么可以简化的吗？不然改动还蛮大的

我刚才看了一眼代码 是这样的 如果你是 DNS 自动模式 那么我们在创建完之后就会自动申请证书
其他模式 需要先创建后申请

**Comment by haiwan-xm** [comment]
目前都是   基于http解析     域名解析 模式在做
![image](https://github.com/1Panel-dev/1Panel/assets/45061573/88c6bb93-2731-4440-897f-53ac3860a649)

**Comment by zhengkunwang223** [comment]
> 目前都是 基于http解析 域名解析 模式在做 ![image](https://private-user-images.githubusercontent.com/45061573/292372849-88c6bb93-2731-4440-897f-53ac3860a649.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjMxNDcsIm5iZiI6MTcwMzIyMjg0NywicGF0aCI6Ii80NTA2MTU3My8yOTIzNzI4NDktODhjNmJiOTMtMjczMS00NDQwLTg5N2YtNTNhYzM4NjBhNjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA1MjcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MzNiYzU3Y2FmZWI1MGQxZDMxZGNjOWQ1ZGJmMTc1NmE5YmU5NjQzMTZmMmRjZmMzYjdhOWRkNmYwYzE0MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OA4j4dlOvuRWE4cd1C2Ahefp7kjLg7g7Y2gyD0-rILQ)

你可以参考一下这个项目 https://github.com/go-acme/lego 我们是基于这个项目做的
