### ISSUE TITLE
[QUESTION]执行中的计划任务怎么停止。

### ISSUE THREAD

**Issue by hsjgit** [1Panel-dev/1Panel#3426]
### 请描述您的问题

执行中的计划任务怎么停止
<img width="1272" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/32933584/fca3d584-259a-4d36-b097-5c19934af300">

**Comment by wanghe-fit2cloud** [comment]
可以尝试重启 1Panel 服务。
`概览页` 右上角点击 `重启面板` 或者执行 `sudo 1pctl restart` 命令。

**Comment by faithererer** [comment]
> 可以尝试重启 1Panel 服务。 `概览页` 右上角点击 `重启面板` 或者执行 `sudo 1pctl restart` 命令。

没有用，只能找进程pid kill，既然这样面板这个功能的意义何在，希望可以添加终止的功能

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> You can try restarting the 1Panel service. `Overview Page` Click `Restart Panel` in the upper right corner or execute the `sudo 1pctl restart` command.

It's useless, you can only find the process pid kill. Since this is the meaning of the panel function
