### ISSUE TITLE
[FEATURE] DNS服务商增加：华为云

### ISSUE THREAD

**Issue by zsbai** [1Panel-dev/1Panel#3427]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

最近刚更换了DNS解析到华为云国际，使用起来相比DNSPOD和阿里云要更加方便，至此希望DNS Provider添加支持华为云国际，感谢！。
https://www.huaweicloud.com/intl/zh-cn/

**Comment by zhengkunwang223** [comment]
当前我们优先支持 https://go-acme.github.io/lego/dns/ 这个列表中的 DNS 厂商 huawei 云不在其中
所以短期内不会增加 希望理解
