### ISSUE TITLE
[FEATURE]文件管理建议增加../返回上级目录

### ISSUE THREAD

**Issue by zxwmfcm** [1Panel-dev/1Panel#3429]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

![1703321474123](https://github.com/1Panel-dev/1Panel/assets/30642864/5a739667-112f-4c4c-a3e2-116ed290ae4f)
建议增加../返回上一级目录    现在每次返回上级目录感觉一点也不顺手

**Comment by zhengkunwang223** [comment]
../是相对目录 如果直接输入../xx/xx 接口是不知道以哪个目录为当前目录的
从逻辑和后端实现的角度来说 这种操作不是很友好

**Comment by zxwmfcm** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/30642864/9837341c-ef4a-4eca-8517-e21132c1b8d9)
不一定非要叫../ 这只是一个标识  也可以直接叫中文上一级目录     如果前端文件列表这里统一默认都加一个按钮或者是虚拟文件   然后用户点击后调用的参数和方法是上边返回按钮是一样的呢

**Comment by wanghe-fit2cloud** [comment]
后续版本会考虑支持返回上一级菜单，如图：
> 我们先调研一下具体实现。

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/7f9a6f93-350a-4154-8ae7-61d8e50404ba)

**Comment by wanghe-fit2cloud** [comment]
我们后续版本还将支持 `回退` 功能，为了保持样式统一，`返回上一级目录` 按钮还是要放置在导航栏处。
重复 issue #3439
