### ISSUE TITLE
[FEATURE]关于php兼容性提升的一个建议

### ISSUE THREAD

**Issue by Anyexyz** [1Panel-dev/1Panel#3430]
### 1Panel 版本

v1.9.2

### 请描述您的需求或者改进建议

在解决群友的各种问题的时候发现，绝大多数的PHP站点问题都是因为PHP扩展不全引起的，项目文档中一般使用宝塔之类的面板进行搭建，而1panel的默认PHP环境中缺乏这些扩展则会导致无法正常启动站点，可以在1panel的文档中添加关于php的FAQ

### 请描述你建议的实现方案

以下是宝塔的默认PHP环境比1panel多出的扩展，当站点从宝塔迁移到1panel的时候出现问题可按需添加：
bcmath,gd,gettext,intl,pcntl,shmop,soap,sockets,sysvsem,xmlrpc,zip

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
PHP 扩展相关需求的讨论，统一汇总到该 issue #1636
