### ISSUE TITLE
[BUG] 关闭面板 SSL 失败

### ISSUE THREAD

**Issue by Cyber-Yin** [1Panel-dev/1Panel#3434]
### 联系方式

ginmiraing@gmail.com

### 1Panel 版本

1.9.2

### 问题描述

关闭面板 SSL 失败，错误信息：

请求参数错误: Key: 'SSLUpdate.SSLType' Error:Field validation for 'SSLType' failed on the 'oneof' tag

我使用的是粘贴代码导入的证书，证书类型 TrustAsia TLS RSA CA

### 重现步骤

在已经开启面板 SSL 的状态下关闭面板 SSL

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by ssongliu** [comment]
历史数据问题，可以先通过 1pctl reset https 关闭 SSL，后面操作就不受影响了，下个小版本解决。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
