### ISSUE TITLE
1Panel面板网站设置CC防护存在BUG

### ISSUE THREAD

**Issue by Havesten** [1Panel-dev/1Panel#3435]
### 联系方式

1319372803@qq.com

### 1Panel 版本

1.9.2

### 问题描述

新建网站并开启防CC，目录放置一个文件，使用脚本进行16线程下载无法拦截并封禁，在宝塔免费waf同样规则进行下载则会封禁IP，希望修复一下这个问题

### 重现步骤

新建网站，开启防cc，存放一个500kb的文件{非html，php}，高频多线程进行下载，无法拦截并封禁，宝塔面板同样操作则可以拦截

### 期待的正确结果

新建网站，开启防cc，存放一个500kb的文件{非html，php}，高频多线程进行下载，对IP进行拦截并封禁

**Comment by wanghe-fit2cloud** [comment]
好的，我们先在本地环境复现一下上述情况。

**Comment by zhengkunwang223** [comment]
感谢建议 我们后续版本会重构 waf 请耐心等待
