### ISSUE TITLE
Bitwarden建议增加官方原版的应用

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3436]
### 1Panel 版本

最新版本

### 请描述您的需求或者改进建议

Bitwarden建议增加官方原版的应用，现在应用商店用的是其他开发者的版本

**Comment by ghost** [comment]
开源项目
https://github.com/bitwarden/server

**Comment by wanghe-fit2cloud** [comment]
是的，我们目前支持的是用 Rust 编写的非官方 Bitwarden，但是与[上游 Bitwarden 客户端](https://bitwarden.com/download/) 兼容，非常适合运行官方资源密集型服务可能不理想的自托管部署。

**Comment by ghost** [comment]
> 是的，我们目前支持的是用 Rust 编写的非官方 Bitwarden，但是与[上游 Bitwarden 客户端](https://bitwarden.com/download/) 兼容，非常适合运行官方资源密集型服务可能不理想的自托管部署。

建议官方版本和Rust 并存 可以自选。另外 在现有的版本上，感觉无法做相关的一些变量配置，例如新用户注册 邮箱服务配置等 ，导致无法做更精细的配置（在默认安装的情况下）。
建议考虑 十分感谢 ~

**Comment by wanghe-fit2cloud** [comment]
好的，我们后续版本考虑一下两个版本共存的方案。

**Comment by ghost** [comment]
十分感谢 希望1panel越来越好 我也捐赠下 支持开源

**Comment by wanghe-fit2cloud** [comment]
> 十分感谢 希望1panel越来越好 我也捐赠下 支持开源

目前，可以参考官方文档中给出的安装教程，链接如下：
https://bitwarden.com/help/install-on-premise-manual/
