### ISSUE TITLE
[FEATURE]文件管理页面，建议增加回退功能

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3439]
### 1Panel 版本

v1.9.2

### 请描述您的需求或者改进建议

目前文件列表导航栏提供了 `上一级` 按钮，希望增加 `后退` 功能，如 Windows 文件管理：
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/206493a3-8243-408a-a2aa-34a122176e82)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
