### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by InfraBackend** [1Panel-dev/1Panel#3440]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

可以支持管理多主机吗，这个应该是只能看当前主机的吧

**Comment by zhengkunwang223** [comment]
当前只能看单主机 后续有计划管理多主机

**Comment by zhengkunwang223** [comment]
重复 https://github.com/1Panel-dev/1Panel/issues/2692
