### ISSUE TITLE
[BUG]面板设置-备份账号-腾讯cos，获取存储桶，区域应该是非必填的

### ISSUE THREAD

**Issue by liufei20151013** [1Panel-dev/1Panel#3441]
### 联系方式

liufei@fit2cloud.com

### 1Panel 版本

v1.9.2

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/15103510/48d9e7e2-7280-4a55-9336-0b7e5f55f73c)
![image](https://github.com/1Panel-dev/1Panel/assets/15103510/af42fec6-3670-4864-b00d-442a1330b67c)

### 重现步骤

获取存储桶，区域应该是非必填的

**Comment by liufei20151013** [comment]
而且这里也没提示写的是region-id 还是region-name

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化创建腾讯 COS 备份账号流程。

**Comment by ssongliu** [comment]
腾讯 COS 的区域是必填字段，不填写的话无法进行文件操作。
https://cloud.tencent.com/document/product/436/31315

![image](https://github.com/1Panel-dev/1Panel/assets/73214554/d37953d7-be58-456b-9b8b-8226ec3e5a14)

**Comment by ssongliu** [comment]
v1.9.4 版本已经支持区域选择。
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/219d8173-36e1-43ad-b4cf-9711affb2fc8)
