### ISSUE TITLE
[BUG]Rocky Linux 9 OpenResty启动不了

### ISSUE THREAD

**Issue by zzs89117920** [1Panel-dev/1Panel#3446]
### 1Panel 版本

1.9.2

### 问题描述

Rocky Linux 9 在应用商店安装完OpenResty之后，启动报错

### 重现步骤

在应用商店安装完OpenResty之后，在网站菜单页的上方点击启动报错
![image](https://github.com/1Panel-dev/1Panel/assets/5515847/8642632b-f6fb-468f-984a-ea8098bc35b1)

![image](https://github.com/1Panel-dev/1Panel/assets/5515847/27245ba3-fb46-4cf2-ab10-6561d1689054)

### 期待的正确结果

OpenResty可以正常启动

### 相关日志输出

```shell
{
    "code": 500,
    "message": "服务内部错误: stderr: service \"openresty\" has no container to start\n",
    "data": null
}
```

**Comment by zhengkunwang223** [comment]
应用商店-已安装-点击重建

**Comment by zzs89117920** [comment]
> 应用商店-已安装-点击重建

点击重建提示1Panel-openresty-sEjS 容器不存在
![image](https://github.com/1Panel-dev/1Panel/assets/5515847/f463a6be-15d2-4dbb-a09c-179c8a11a5b7)

**Comment by wanghe-fit2cloud** [comment]
进入容器列表可查看容器状态，日志等信息。
如果未发现 OpenResty 容器，应该是镜像都没有下载成功。可以进入 `容器` - `配置` 页面手动添加镜像加速地址，之后再来尝试重建应用。
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/1415b14e-0fed-444b-829d-1091926e7ea3)

**Comment by zzs89117920** [comment]
重建报错后没操作任何东西，刚刚发现好使了，不知道什么原因，日志也没有任何记录
![image](https://github.com/1Panel-dev/1Panel/assets/5515847/80589658-8de5-4775-8d5f-26c98c508c4d)
