### ISSUE TITLE
咨询一下这是什么情况

### ISSUE THREAD

**Issue by ifacecn** [1Panel-dev/1Panel#3448]
### 请描述您的问题

{"stream":"Step 1/18 : FROM node:18 as builder"}
{"stream":"\n"}
{"stream":" ---\u003e 638c4f90a264\n"}
{"stream":"Step 2/18 : WORKDIR /usr/src/app"}
{"stream":"\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e 90f13c2cd08a\n"}
{"stream":"Step 3/18 : COPY client/package*.json ./"}
{"stream":"\n"}
{"stream":" ---\u003e 373d83619f84\n"}
{"stream":"Step 4/18 : COPY client/pnpm-lock.yaml ./"}
{"stream":"\n"}
{"stream":" ---\u003e 04a0f1ae9e60\n"}
{"stream":"Step 5/18 : RUN npm install pnpm -g \u0026\u0026 pnpm install"}
{"stream":"\n"}
{"stream":" ---\u003e Running in f5a282eeeff7\n"}
{"stream":"\u001b[91mnpm ERR! code ETIMEDOUT\n\u001b[0m"}
{"stream":"\u001b[91mnpm ERR! syscall connect\n\u001b[0m"}
{"stream":"\u001b[91mnpm ERR! errno ETIMEDOUT\n\u001b[0m"}
{"stream":"\u001b[91mnpm ERR! network request to https://registry.npmjs.org/pnpm failed, reason: connect ETIMEDOUT 2606:4700::6810:323:443\n\u001b[0m"}
{"stream":"\u001b[91mnpm ERR! network This is a problem related to network connectivity.\nnpm ERR! \u001b[0m"}
{"stream":"\u001b[91mnetwork In most cases you are behind a proxy or have bad network settings.\nnpm ERR! network \nnpm\u001b[0m"}
{"stream":"\u001b[91m ERR! network If you are behind a proxy, please make sure that the\nnpm \u001b[0m"}
{"stream":"\u001b[91mERR! \u001b[0m"}
{"stream":"\u001b[91mnetwork 'proxy' config is set properly.  See: 'npm help config'\n\u001b[0m"}
{"stream":"\u001b[91m\nnpm ERR!\u001b[0m"}
{"stream":"\u001b[91m A complete log of this run can be found in: /root/.npm/_logs/2023-12-26T02_55_07_607Z-debug-0.log\n\u001b[0m"}
{"errorDetail":{"code":1,"message":"The command '/bin/sh -c npm install pnpm -g \u0026\u0026 pnpm install' returned a non-zero code: 1"},"error":"The command '/bin/sh -c npm install pnpm -g \u0026\u0026 pnpm install' returned a non-zero code: 1"}
image build failed!

**Comment by zhengkunwang223** [comment]
你这是什么操作？

**Comment by ifacecn** [comment]
> 你这是什么操作？

构建镜像

**Comment by zhengkunwang223** [comment]
> > 你这是什么操作？
> 
> 构建镜像
 
日志里显示是网络问题 访问 https://registry.npmjs.org/pnpm 超时

**Comment by ifacecn** [comment]
> > > 你这是什么操作？
> 
> > 
> 
> > 构建镜像
> 
>  
> 
> 日志里显示是网络问题 访问 https://registry.npmjs.org/pnpm 超时

有什么解决办法吗

**Comment by zhengkunwang223** [comment]
> > > > 你这是什么操作？
> > 
> > 
> > > 
> > 
> > 
> > > 构建镜像
> > 
> > 
> > 日志里显示是网络问题 访问 https://registry.npmjs.org/pnpm 超时
> 
> 有什么解决办法吗

你可以看一下如何在 Dockerfile 中修改  npm 源

可以参考这个文件 https://github.com/1Panel-dev/KubePi/blob/master/Dockerfile

**Comment by ifacecn** [comment]
> > > > > 你这是什么操作？
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 构建镜像
> 
> > > 
> 
> > > 
> 
> > > 日志里显示是网络问题 访问 https://registry.npmjs.org/pnpm 超时
> 
> > 
> 
> > 有什么解决办法吗
> 
> 
> 
> 你可以看一下如何在 Dockerfile 中修改  npm 源
> 
> 
> 
> 可以参考这个文件 https://github.com/1Panel-dev/KubePi/blob/master/Dockerfile

这是我的dockerfile ，请指点

FROM node:18 as builder

WORKDIR /usr/src/app

COPY client/package*.json ./
COPY client/pnpm-lock.yaml ./
RUN npm install pnpm -g && pnpm install

COPY client .
RUN pnpm build

FROM alpine:latest

WORKDIR /usr/src/app

RUN apk add --no-cache --update nodejs npm tzdata
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' > /etc/timezone
COPY server/package*.json ./
COPY server/pnpm-lock.yaml ./
RUN npm install pnpm -g && pnpm install -P

COPY server .

COPY --from=builder /usr/src/app/dist /usr/src/app/dist

EXPOSE 3000

CMD [ "node", "index.js" ]

**Comment by zhengkunwang223** [comment]
> > > > > > 你这是什么操作？
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 构建镜像
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 日志里显示是网络问题 访问 https://registry.npmjs.org/pnpm 超时
> > 
> > 
> > > 
> > 
> > 
> > > 有什么解决办法吗
> > 
> > 
> > 你可以看一下如何在 Dockerfile 中修改  npm 源
> > 可以参考这个文件 https://github.com/1Panel-dev/KubePi/blob/master/Dockerfile
> 
> 这是我的dockerfile ，请指点
> 
> FROM node:18 as builder
> 
> WORKDIR /usr/src/app
> 
> COPY client/package*.json ./ COPY client/pnpm-lock.yaml ./ RUN npm install pnpm -g && pnpm install
> 
> COPY client . RUN pnpm build
> 
> FROM alpine:latest
> 
> WORKDIR /usr/src/app
> 
> RUN apk add --no-cache --update nodejs npm tzdata RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' > /etc/timezone COPY server/package*.json ./ COPY server/pnpm-lock.yaml ./ RUN npm install pnpm -g && pnpm install -P
> 
> COPY server .
> 
> COPY --from=builder /usr/src/app/dist /usr/src/app/dist
> 
> EXPOSE 3000
> 
> CMD [ "node", "index.js" ]

具体问题需要你自己处理
