### ISSUE TITLE
[BUG]查看网站错误日志，页面报错

### ISSUE THREAD

**Issue by liufei20151013** [1Panel-dev/1Panel#3449]
### 联系方式

liufei@fit2cloud.com

### 1Panel 版本

v1.9.2

### 问题描述

日志审计-网站日志-错误日志，页面报错

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/15103510/e32377e2-5fc7-484d-851e-acf8d985a6df)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，在本地环境已复现上述问题，我们会在近期版本修复并推送更新。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
