### ISSUE TITLE
[QUESTION]面板设置-备份账号我对接了 COS，但是不清楚备份的是什么？

### ISSUE THREAD

**Issue by liufei20151013** [1Panel-dev/1Panel#3450]
### 请描述您的问题

面板设置-备份账号 我对接了 COS，但是不清楚备份的是什么？什么时间备份，多久备份一次？我在 COS 的备份目录下没有看到备份的内容，只有一个 test/1panel 备份测试文件。查看了 1panel 官方文档，没有比较清晰的说明，只备份快照吗？
![image](https://github.com/1Panel-dev/1Panel/assets/15103510/ee086a5b-1297-47eb-831e-c4f9f1ee9277)

**Comment by wanghe-fit2cloud** [comment]
在 `面板设置` 添加备份账号后，可以在创建 `快照` 和 `计划任务`时选择备份账号。
> 计划任务中，支持在 备份网站、应用、数据库、目录、日志、快照等任务类型中使用已添加的备份账号。
