### ISSUE TITLE
[QUESTION]php8.2 shell_exec返回为空, php配置里确认没有禁用函数

### ISSUE THREAD

**Issue by egwang186** [1Panel-dev/1Panel#3453]
### 请描述您的问题

php配置里确认没有禁用函数

**Comment by wanghe-fit2cloud** [comment]
进入 `网站设置` - `PHP` 页面，支持手动配置禁用函数。
> issue 内容没有太懂，是这个意思吗？

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/9867b9f5-b8d8-423b-8a73-dcfdb5f16ff4)

**Comment by egwang186** [comment]
不是，宝塔上用shell_exec需要把shell_exec从禁用函数里删除，1panel里禁用函数里没有shell_exec也无法执行shell_exec，不知道哪里的原因

**Comment by egwang186** [comment]
SSH实测过shell命令，正确返回了内容，宝塔里同样的php也是没有问题的

**Comment by egwang186** [comment]
ssh 安装ffmpeg:  sudo apt install ffmpeg

再ssh里面测试shell命令：ffprobe -v quiet -print_format json -show_format -show_streams 'https://m3u.haiwaikan.com/xm3u8/3a3f20b11f372b4ae952c803c2ade17fbffc3394e4f31f7143f678eccfdc189a9921f11e97d0da21.m3u8'

ssh里面返回有json字符{..}就是正确的数据，然后可以使用这个php文件测试

<?php
// 视频地址
$videoUrl = base64_decode($_GET['videourl']);
$videoUrl ="https://m3u.haiwaikan.com/xm3u8/3a3f20b11f372b4ae952c803c2ade17fbffc3394e4f31f7143f678eccfdc189a9921f11e97d0da21.m3u8";

// 使用ffprobe获取视频时长
$command = 'ffprobe -v quiet -print_format json -show_format -show_streams ' . escapeshellarg($videoUrl);
$output = shell_exec($command);
print_r($command.$output.'555');

**Comment by egwang186** [comment]
`<?php
// 视频地址
$videoUrl = base64_decode($_GET['videourl']);
$videoUrl ="https://m3u.haiwaikan.com/xm3u8/3a3f20b11f372b4ae952c803c2ade17fbffc3394e4f31f7143f678eccfdc189a9921f11e97d0da21.m3u8";

// 使用ffprobe获取视频时长
$command = 'ffprobe -v quiet -print_format json -show_format -show_streams ' . escapeshellarg($videoUrl);
$output = shell_exec($command);
print_r($command.$output.'555');`

**Comment by zhengkunwang223** [comment]
你是用的 PHP 的运行环境吗 我们的应用商店运行环境中 不支持 执行 sudo apt install ffmpeg 这个命令

**Comment by egwang186** [comment]
服务器需要安装ffmpeg才能用这个shell命令，在ssh里面执行sudo apt install ffmpeg，不是在面板

**Comment by zhengkunwang223** [comment]
> ffprobe

我们的 PHP 是容器化的 在容器内部执行 ffprobe 是不行的

**Comment by egwang186** [comment]
$command = 'ffprobe -v quiet -print_format json -show_format -show_streams ' . escapeshellarg($videoUrl);
$output = shell_exec($command);  

php有这个shell_exec函数可以执行的，跟容器还有关系？

**Comment by zhengkunwang223** [comment]
> $command = 'ffprobe -v quiet -print_format json -show_format -show_streams ' . escapeshellarg($videoUrl); $output = shell_exec($command);
> 
> php有这个shell_exec函数可以执行的，跟容器还有关系？

是的 容器和宿主机环境是隔离的 宿主机安装 ffmpeg 容器中用不了
