### ISSUE TITLE
[FEATURE]增加应用市场的社区模块

### ISSUE THREAD

**Issue by vybfi** [1Panel-dev/1Panel#3455]
### 1Panel 版本

v1.9.2

### 请描述您的需求或者改进建议

现有的应用商店都是由官方加入docker应用，但是docker应用数量极多，光靠官方进行维护虽稳定但是效率太低了。是否能用某种方式添加社区支持。这样对用户社区的构建也有促进。同时也可以增加用户粘性。

### 请描述你建议的实现方案

比如
1. 添加社区应用商店模块，由用户填写创建docker应用的必要信息（镜像，端口，存储卷映射等），然后官方审核通过后发布到社区商店中
2. 或者添加一个自定义入口，使用户能自行创建类似官方应用的docker应用（即有图标，能出现在已安装列表，有快速跳转对应网页的按钮），然后可以将配置分享给其他用户一键创建。
3. 或者模仿unraid，做docker应用的搬运商

**Comment by wanghe-fit2cloud** [comment]
感谢您的建议。
1Panel 应用商店支持用户 [自定义上传本地应用](https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8)，目前也有一些 [第三方的仓库](https://bbs.fit2cloud.com/t/topic/640)可参考
