### ISSUE TITLE
[FEATURE] 备份账号可以增加 Google Drive 的支持吗？

### ISSUE THREAD

**Issue by syntroy** [1Panel-dev/1Panel#3458]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

希望增加 Google Drive 的备份账号支持

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑是否支持上述需求。

**Comment by rapidacc** [comment]
+1 想要这个功能

**Comment by wanyunr** [comment]
> 感谢反馈，我们会在后续版本考虑是否支持上述需求。

再次请求增加Google Drive

**Comment by ssongliu** [comment]
重复 #1041

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Duplicate #1041
