### ISSUE TITLE
[BUG] 切换计划任务状态时，报告内容会不断追加 

### ISSUE THREAD

**Issue by justmd5** [1Panel-dev/1Panel#346]
### 1Panel 版本

v1.0.2

### 问题描述

<img width="716" alt="image" src="https://user-images.githubusercontent.com/4120960/226569304-20152036-f108-46cf-b755-74fd35072a90.png">
 切换计划任务状态时，报告内容会不断追加，应该是用最新查询结果覆盖才对

### 重现步骤

<img width="716" alt="image" src="https://user-images.githubusercontent.com/4120960/226569304-20152036-f108-46cf-b755-74fd35072a90.png">

**Comment by ssongliu** [comment]
感谢反馈！预计将在本周发布的 v1.0.3 版本完成修复。
