### ISSUE TITLE
[BUG] 添加https反向代理时，生成的配置缺少 proxy_ssl_server_name on;

### ISSUE THREAD

**Issue by bddjr** [1Panel-dev/1Panel#3461]
### 1Panel 版本

1.9.2

### 问题描述

如题，会导致当 proxy_pass 地址协议为https时，无法连接源服务器

### 重现步骤

创建反向代理，协议选择https

### 期待的正确结果

自带 `proxy_ssl_server_name on;` ，配置完直接成功连接

**Comment by zhengkunwang223** [comment]
感谢反馈 我们测试一下

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
