### ISSUE TITLE
[QUESTION]关于Roundcube邮件服务的使用问题

### ISSUE THREAD

**Issue by youzhazhu** [1Panel-dev/1Panel#3462]
### 请描述您的问题

很抱歉打扰您，**我想请问下Roundcube的账号密码是什么**。

我在网上查，说是数据库账号密码，试了无法登录。

**Comment by zhengkunwang223** [comment]
> Roundcube

是你邮箱的账号密码 默认的邮件服务器 是新浪 用新浪的邮箱和密码可以登录
如果你是其他的  需要改邮件服务器 具体的文档 你可以查看文档 https://github.com/roundcube/roundcubemail/wiki
