### ISSUE TITLE
[BUG]快照未完成，日志就显示快照备份成功了

### ISSUE THREAD

**Issue by vybfi** [1Panel-dev/1Panel#3464]
### 联系方式

2891489708@qq.com

### 1Panel 版本

v1.9.2

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/52736701/533e5854-0688-4739-8a2c-4bf6714090af)
![image](https://github.com/1Panel-dev/1Panel/assets/52736701/69516e07-d8b8-497c-8198-963c0cfd55f1)
如题，快照备份未完成，日志就显示快照备份成功了。
sftp快照备份比s3快照备份更加过分，我nas里面都没看到文件，日志和快照页就都显示成功了
s3好歹在快照页还有显示“进行中”

### 重现步骤

建立一个s3/sftp存储。
快照到这个存储
查看日志

### 期待的正确结果

按道理他应该先在快照页显示进行中，成功后再在日志页显示快照成功。
或者
先在快照页显示进行中，在日志页显示开始快照，成功后再在日志页显示快照成功。

### 附加信息

最好是能加入快照的进度条或者正在执行的步骤，和一个中止按钮。
不然看着很不安心，不知道他进行到哪一步了，打包还是上传都不清楚，卡了也不知道。

**Comment by wanghe-fit2cloud** [comment]
后续版本会考虑增加 `任务管理` 功能，支持实时查看任务进度、日志等。

**Comment by vybfi** [comment]
好耶！

**Comment by ssongliu** [comment]
因为快照执行时间比较久是异步进行的，而日志是直接拦截接口返回信息，所以快照还没结束日志就已经显示成功；

然后点击快照列表的进行中按钮可以查看具体到了哪一步。
