### ISSUE TITLE
[FEATURE] 希望增加 WebHook 功能，和宝塔的那个 WebHook 类似

### ISSUE THREAD

**Issue by SeeDLL** [1Panel-dev/1Panel#3466]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

希望增加 WebHook 功能，和宝塔的那个 WebHook 类似，如果可以支持完整的鉴权那就更好了，宝塔的鉴权不太完整。

1. WebHook 可以自定义hook名称，可以默认随即一个字符串，允许用户修改。不要像宝塔那样就只是一串字符串。
2. WebHook 可以自定义hook名称后续可以修改，不要固定死了。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
webhook 相关功能的讨论，统一汇总到该 issue #410
