### ISSUE TITLE
[FEATURE] support for dotnet core

### ISSUE THREAD

**Issue by reach2rv** [1Panel-dev/1Panel#3467]
### 1Panel 版本

 Versionv1.9.2

### 请描述您的需求或者改进建议

Support for dotnet. having support for dotnet core can be added advantage. 

### 请描述你建议的实现方案

user will install dotnet from linux package manager using terminal

in panel there are two ways to enable user to create dotnet website

1. in Create Website > Reverse Proxy add option to set custom command to run, this common will run with website there user can simply add `dotnet app.web.dll` which will run dotnet program
2. in Runtime add option for dotnet in that section user can only set port and custom command and save the runtime. `backend/app/service/runtime_utils.go` we need to add function to handledotnet which will simply run the command entered by user while setting up runtime.

### 附加信息

currently aapanel also enables user to do the above setup under nodejs apps I am attaching the screenshot for reference
![image](https://github.com/1Panel-dev/1Panel/assets/16520558/62fc7fb4-e14c-4a7a-89e6-2cb9a6136137)

**Comment by wanghe-fit2cloud** [comment]
Thank you for your feedback. We currently do not have any plans to support the mentioned requirement in the near term. We hope for your understanding.
