### ISSUE TITLE
[FEATURE]创建计划任务时，建议能一次性选择多个存储方案

### ISSUE THREAD

**Issue by maskgo68** [1Panel-dev/1Panel#3468]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

创建计划任务备份时，希望能一次性选择多个存储方案，现在一次只能选一个，想要备份到多个平台就需要重复操作，很麻烦
![image](https://github.com/1Panel-dev/1Panel/assets/146368179/9435c4d1-96e6-478b-bd51-784db4409022)

**Comment by wanghe-fit2cloud** [comment]
收到，后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
