### ISSUE TITLE
[FEATURE]Node Support?

### ISSUE THREAD

**Issue by rondDev** [1Panel-dev/1Panel#347]
### 1Panel 版本

N/A

### 请描述您的需求或者改进建议

Hey! I don’t know any chinese, but this project seems very cool. I was wondering if you have any support for NodeJS? I looked into the demo, but I couldn’t find anything that looked like NodeJS.

I might just be picky and it could be possible to do via Docker, please let me know if this is the case.

**Comment by wanghe-fit2cloud** [comment]
Thank you for your feedback.
We will support NodeJS in a later release.

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
