### ISSUE TITLE
[QUESTION]关于ShowDoc部署问题

### ISSUE THREAD

**Issue by youzhazhu** [1Panel-dev/1Panel#3476]
### 请描述您的问题

应用商店，部署ShowDoc失败，报错如下：

stderr: showdoc Pulling no matching manifest for linux/amd64 in the manifest list entries

是匹配不到正确的版本吗？我看上面显示拉取的是arm版本的。

**Comment by wanghe-fit2cloud** [comment]
是的，ShowDoc 采用的是官方提供的镜像，分为了两个版本，安装时要根据 1Panel 部署服务器的架构来选择不同的版本，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/5dff679a-dd41-421d-a1b6-ac8d9f507503)
