### ISSUE TITLE
[FEATURE]表格字体样式过粗希望优化

### ISSUE THREAD

**Issue by lainbo** [1Panel-dev/1Panel#3477]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

感觉在表格中, 前端的.table-link这个class是否字重设置的过于大了。

这个class的样式写的font-weight: 700; 这是一个很大的字重, 如果是1080P的Windows可能感觉不出来什么, 因为默认的微软雅黑在这个屏幕ppi下无法展现出相符合的粗细, 但是如果是使用的是可变字体, 或者是更高分辨率的屏幕, 看起来文字会非常的粗。

在看文件列表的时候, 一堆粗体字不太利于用户阅读, 尤其是在Linux这种环境下, 更容易出现比较长的文件名, 导致这个负面效果被放大。
![Screenshot_2023-12-28_23-49-09](https://github.com/1Panel-dev/1Panel/assets/46062895/3775b4c6-e577-4dab-99b0-00842104d3b9)
![image](https://github.com/1Panel-dev/1Panel/assets/46062895/079ce100-d391-411f-b668-48e22d8c2e99)

### 请描述你建议的实现方案

建议的解决方案是将`.table-link`这个class改成600或者更低的字重, 不仅是文件列表, 在项目的其他地方我也观察到了这个现象

因为粗体在设计中等于强调, 但是全都强调 等于全都没有强调, 因为屏幕分辨率的多样化, 导致加粗的字体发生粘连反而可能会与设计初衷相违背

希望项目中慎用font-weight: 700这种将文字设置的非常粗的CSS

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
