### ISSUE TITLE
[FEATURE]计划任务里建议新增python脚本任务

### ISSUE THREAD

**Issue by Shuai-S** [1Panel-dev/1Panel#3478]
### 1Panel 版本

v1.9.2

### 请描述您的需求或者改进建议

在创建计划任务的时候希望可以支持python脚本
python是现在大量使用的脚本语言，使用人员广泛，需求应该比较多一点

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
关于计划任务支持 Python 脚本的需求，统一汇总到该 issue #2738
