### ISSUE TITLE
[BUG] debian12 进程守护无法守护 Go 项目

### ISSUE THREAD

**Issue by 7836246** [1Panel-dev/1Panel#3482]
### 联系方式

go7836246@gmail.com

### 1Panel 版本

v1.9.2

### 问题描述

启动失败一直提示这个 can't find command './main'   从 1.5.1 后版本出现的 
 INFO gave up: ximi_00 entered FATAL state, too many start retries too quickly

### 重现步骤

随便守护一个 Go项目 正常配置 无法正常启动
/

**Comment by wanghe-fit2cloud** [comment]
启动命令处，填写绝对路径，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/e1511ffb-53ac-4d5a-b2d6-d0c3c8df88c8)

**Comment by 7836246** [comment]
好的  已经解决 我以前版本不填写也可 谢谢大哥@wanghe-fit2cloud
