### ISSUE TITLE
[QUESTION] Debian 10 系统无法安装 Openrestry

### ISSUE THREAD

**Issue by benzBrake** [1Panel-dev/1Panel#3484]
### 请描述您的问题

指向感叹号报错信息如下
```
stderr: openresty Pulling error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY` 
```

**Comment by zhengkunwang223** [comment]
可以参考这个 https://www.freshers.in/article/docker/docker-cannot-autolaunch-d-bus-without-x11-display-how-to-resolve/#:~:text=The%20error%20message%20suggests%20that,Docker%20daemon%20is%20running%20properly.

**Comment by benzBrake** [comment]
主要是这 openrestry 是 1panel 自带那个

**Comment by benzBrake** [comment]
不研究了，重装为 debian 12 解决了
