### ISSUE TITLE
对OpenEuler提供一键安装脚本支持

### ISSUE THREAD

**Issue by KelvinZhang512** [1Panel-dev/1Panel#3485]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

使用一键安装脚本时提示docker因不支持的发行版而安装失败，新版本可否提供支持？
![IMG_20231229_200311](https://github.com/1Panel-dev/1Panel/assets/48343945/c1419281-0e8c-4fa5-b32e-2059ad9862a8)

**Comment by zhengkunwang223** [comment]
感谢建议 后续我们会不断优化
当前你可以先手动安装 docker

**Comment by wanghe-fit2cloud** [comment]
重复 issue #3308

**Comment by Anyexyz** [comment]
https://www.anye.xyz/archives/1706504406639
参考这个进行安装 @KelvinZhang512
