### ISSUE TITLE
[BUG]无法申请证书

### ISSUE THREAD

**Issue by romanticgrass** [1Panel-dev/1Panel#3486]
### 1Panel 版本

v1.9.2

### 问题描述

无法申请新的证书,无论是在国外还是在国内服务器上都一样,账户没有修改过,针对已经申请的证书可以手动续签成功,也不知道是从哪一个版本开始就不行了.

### 重现步骤

尝试许多次都不行,同样的账户续签正常,新申请就不可以,都是6003错误.希望开发者修复一下,谢谢,日志文件域名已做乱改处理.

### 相关日志输出

```shell
2023/12/29 20:22:25 开始申请证书,域名 [*.mmycloud.love] 申请方式 [DNS 自动] DNS 账号 [cloudflare] 厂商 [CloudFlare]
2023/12/29 20:22:25 [INFO] [*.mmycloud.love] acme: Obtaining bundled SAN certificate
2023/12/29 20:22:25 [INFO] [*.mmycloud.love] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/298620364426
2023/12/29 20:22:25 [INFO] [*.mmycloud.love] acme: use dns-01 solver
2023/12/29 20:22:25 [INFO] [*.mmycloud.love] acme: Preparing to solve DNS-01
2023/12/29 20:22:26 [INFO] [*.mmycloud.love] acme: Cleaning DNS-01 challenge
2023/12/29 20:22:26 [WARN] [*.mmycloud.love] acme: cleaning up failed: cloudflare: failed to find zone mmycloud.love.: ListZonesContext command failed: Invalid request headers (6003) 
2023/12/29 20:22:27 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/298620364426
2023/12/29 20:22:27 申请  [*.mmycloud.love] 证书失败, error: one or more domains had a problem:
[*.mmycloud.love] [*.mmycloud.love] acme: error presenting token: cloudflare: failed to find zone mmycloud.love.: ListZonesContext command failed: Invalid request headers (6003)
```

**Comment by Zeta-ZhaoLi** [comment]
同样问题，6003，用别的程序就能申，1Panel不行

**Comment by romanticgrass** [comment]
> 问题，6003，用其他程序可以申，1Panel同样不行

以前是可以的,最近大概一两个月升级版本了就不行了,估计是升级证书相关的那个版本之后就不行了

**Comment by zhengkunwang223** [comment]
为了安全 我们修改了 CloudFlare 的认证方式
具体解决方案 请看 https://bbs.fit2cloud.com/t/topic/2541/4

**Comment by d4renk** [comment]
@zhengkunwang223 
CloudFlare 只需要api key 就能编辑dns 无需邮箱
![image](https://github.com/1Panel-dev/1Panel/assets/64531014/3c196897-4a33-4ad4-9cff-7a24b4135d5d)

**Comment by zhengkunwang223** [comment]
> CloudFlare 只需要api key 就能编辑dns 无需邮箱

感谢反馈，我们测试一下。

**Comment by d4renk** [comment]
@zhengkunwang223 
email 乱填能申请证书 (cloudflare api 并不需要email 这个参数)
![IMG_20240302_152032.jpg](https://github.com/1Panel-dev/1Panel/assets/64531014/bba910c1-2065-4c39-a0dc-c813a869ad65)
自动续订面板证书后 可不可以自动重启面板
不重启面板的话 证书不会生效
