### ISSUE TITLE
使用脚本安装后Docker无法启动[BUG]

### ISSUE THREAD

**Issue by HKMV** [1Panel-dev/1Panel#3487]
### 1Panel 版本

1.9.2

### 问题描述

系统版本centos-8.5.2111
内核版本 6.6.1-1.el8.elrepo.x86_64
Docker是之前安装好的,版本24.0.7,之前一直用着没什么问题.
在通过1panel提供的安装脚本,完成安装1panel后发现Docker无法启动
![image](https://github.com/1Panel-dev/1Panel/assets/26456469/42b6b9d2-5039-4e63-9388-9f4d52e558c7)

### 重现步骤

在centos-8.5.2111上使用docker官方提供的安装脚本安装最新版docker,
然后系统1panel脚本进行安装1panel
会导致docker无法启动

### 期待的正确结果

docker可以正常启动使用

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/26456469/42b6b9d2-5039-4e63-9388-9f4d52e558c7)

**Comment by wanghe-fit2cloud** [comment]
1Panel 在线安装脚本会检测服务器是否已安装 docker，如果是已安装则会跳过安装 docker 这一步，并且不会对已安装 docker 做任何修改，[参考代码](https://github.com/1Panel-dev/installer/blob/1cc541638411058a97e2945c878aaa17ab8b7d64/install.sh#L62C1-L62C1)
> 你目前可以执行 `journalctl -u docker.service -exf` 命令来分析具体问题。

**Comment by HKMV** [comment]
> 1Panel 在线安装脚本会检测服务器是否已安装 docker，如果是已安装则会跳过安装 docker 这一步，并且不会对已安装 docker 做任何修改，[参考代码](https://github.com/1Panel-dev/installer/blob/1cc541638411058a97e2945c878aaa17ab8b7d64/install.sh#L62C1-L62C1)
> 
> > 你目前可以执行 `journalctl -u docker.service -exf` 命令来分析具体问题。

但是确实是在安装1panel后无法启动的,会不会是1panel使用或者修改的东西和最新版docker有冲突呢?
详细错误信息为:
```
12月 29 22:42:32 centos8.5 systemd[1]: docker.service: Service RestartSec=2s expired, scheduling restart.
12月 29 22:42:32 centos8.5 systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Automatic restarting of the unit docker.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
12月 29 22:42:32 centos8.5 systemd[1]: Stopped Docker Application Container Engine.
-- Subject: docker.service 单元已结束停止操作
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- docker.service 单元已结束停止操作。
12月 29 22:42:32 centos8.5 systemd[1]: docker.service: Start request repeated too quickly.
12月 29 22:42:32 centos8.5 systemd[1]: docker.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- The unit docker.service has entered the 'failed' state with result 'exit-code'.
12月 29 22:42:32 centos8.5 systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: docker.service 单元已失败
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- docker.service 单元已失败。
--
-- 结果为“failed”。
```

**Comment by HKMV** [comment]
抱歉是我自己的原因,前段时间调整了docker的daemon.json文件当时没注意格式,导致的docker无法启动.
