### ISSUE TITLE
[QUESTION] 提问：如何让面板部署的 PHP 程序访问如 ```/mnt/sda1``` 这样的路径？

### ISSUE THREAD

**Issue by JueLuo99** [1Panel-dev/1Panel#3488]
### 请描述您的问题

1Panel：v1.9.2
操作系统：Ubuntu 22.04 LTS
-----
我正在使用 1Panel 的创建网站功能部署一个 Nextcloud 应用，先后在【应用商店】中安装了 OpenResty 和 PHP 并配置完毕。至此，一切工作正常。

随后，为了扩展存储空间，我添加了一块硬盘，并将其挂载到如 ```/mnt/sda1``` 这样的路径。

我发现 OpenResty 和 PHP 的根目录都是实体机的 ```/opt/1panel/apps/openresty/openresty/www``` 目录，无法直接访问 ```/mnt/sda1``` 这样的路径。

**有什么办法可以让面板部署的 PHP 程序访问 ```/mnt/sda1``` 这样的路径？**

下面是我尝试过，但**失败**的方案：
- 使用软链接（Nextcloud 会将软链接视为一个文件）
- 使用 bind mount（会使 PHP 程序工作不正常，Nextcloud 的回收站等功能无法正常工作）
- 直接使用【应用商店】中的 Nextcloud 应用（其由 ```linuxserver.io``` 提供，维护状况似乎有问题，默认配置下无法使用）

我知道可以使用其他 Docker 镜像来解决这个问题，但此处只是想提出这个问题。

敬请各位不吝赐教！

**Comment by zhengkunwang223** [comment]
你可以通过修改 PHP 应用的 docker-compose.yml 文件来实现此需求
例如 进入应用商店 -已安装-PHP-参数-编辑-高级设置-修改 compose 文件
增加如下的配置 
<img width="581" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/31820853/1433449a-9323-457f-a9a1-351c582a85f9">
然后保存

**Comment by JueLuo99** [comment]
> 你可以通过修改 PHP 应用的 docker-compose.yml 文件来实现此需求 例如 进入应用商店 -已安装-PHP-参数-编辑-高级设置-修改 compose 文件 增加如下的配置 <img alt="image" width="581" src="https://private-user-images.githubusercontent.com/31820853/293454853-1433449a-9323-457f-a9a1-351c582a85f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NTU4MTUsIm5iZiI6MTcwMzk1NTUxNSwicGF0aCI6Ii8zMTgyMDg1My8yOTM0NTQ4NTMtMTQzMzQ0OWEtOTMyMy00NTdmLWE5YTEtMzUxYzU4MmE4NWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDE2NTgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNWUxNzI0MzM0NmJmN2E5MzA2NjZkNjQ0YWQ2NDE2N2IxYjdmNDdiNGU0ZWVkYjIyYWQxYTExM2I2YmI3ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HYp8NNCTekUFsAi7R0-YwpMwH7_6t21XRiCBv20eZcg"> 然后保存

非常感谢指点，如此即可简单方便地实现我的需求
