### ISSUE TITLE
[QUESTION] fail2ban 黑名单报错: exit status 255

### ISSUE THREAD

**Issue by W4J1e** [1Panel-dev/1Panel#3490]
### 请描述您的问题

服务器系统：debian-10.9

按照 1panel 官方的文档安装并启用了 fail2ban，在国内的轻量服务器上一切正常，在我位于 hk 的服务器上出现错误。
复现：点击 1panel 侧边栏的工具箱，点击 fail2ban，点击黑名单，如图所示：

![f2](https://github.com/1Panel-dev/1Panel/assets/74824162/cb5c9df1-4bf2-4a2d-8a10-3c93ec57dc12)

我卸载了 fail2ban 再次按照文档安装后依然如此。尝试在该界面手动添加一个 ip ，再次点击依然报错并且框内不显示该 ip。
通过终端查看状态以及黑名单，发现终端能正确显示我手动添加的 ip：

![f1](https://github.com/1Panel-dev/1Panel/assets/74824162/81e707e2-daf0-4dcc-a5d4-9f6a00685c67)

看到文档有一句：

_如之前已经手动安装过 Fail2ban，需要将 [sshd] 部分的配置信息写入到 jail.local 中，重启 fail2ban 服务，否则可能出现获取黑名单报错的问题；_

于是我查看了 jail.local 文件，内容里已经包含了 sshd 的内容：

![f3](https://github.com/1Panel-dev/1Panel/assets/74824162/a155f440-a01f-4619-b5ca-402792f10190)

目前无法找到报错`exit status 255`的问题所在，请求帮助。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by ssongliu** [comment]
麻烦提供下面两条命令的截图：
1. fail2ban-client get sshd banip
2. fail2ban-client get sshd ignoreip

**Comment by W4J1e** [comment]
> 麻烦提供下面两条命令的截图：
> 
> 1. fail2ban-client get sshd banip
> 2. fail2ban-client get sshd ignoreip


您好，截图如下：
![1](https://github.com/1Panel-dev/1Panel/assets/74824162/8007f96f-040e-482d-825f-7e5ca2c876c2)

**Comment by ssongliu** [comment]
麻烦扫描二维码加一下我，我远程看看
<img width="207" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/73214554/b86f65f6-f9b4-422c-ba95-d91485bf953f">

**Comment by ssongliu** [comment]
fail2ban 0.10.2 版本不支持 fail2ban-client get sshd banip 的命令导致无法获取禁用 ip。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
