### ISSUE TITLE
[BUG] 無法安裝應用

### ISSUE THREAD

**Issue by deventw** [1Panel-dev/1Panel#3491]
### 1Panel 版本

v1.9.2

### 问题描述

安裝應用失敗
stat /opt/1panel/apps/alist/alist/docker-compose.yml: no such file or directory
stat /opt/1panel/apps/memos/memos/docker-compose.yml: no such file or directory
stat /opt/1panel/apps/mysql/mysql/docker-compose.yml: no such file or directory

### 重现步骤

在應用商店點擊安裝任意應用

### 期待的正确结果

安裝成功

### 相关日志输出

```shell
stat /opt/1panel/apps/alist/alist/docker-compose.yml: no such file or directory
stat /opt/1panel/apps/memos/memos/docker-compose.yml: no such file or directory
stat /opt/1panel/apps/mysql/mysql/docker-compose.yml: no such file or directory
```

**Comment by wanghe-fit2cloud** [comment]
刚在本地环境测试安装 Alist v3.29.1，未复现上述问题。
<img width="644" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/2501f5d4-8be6-4401-98c8-b8a5152f7eee">

你可以先点击应用商店右上角的 `更新应用列表` 按钮，等待同步成功之后再来重建应用。
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/3f7e21d4-860b-4c04-933a-0d0a181729a8">

**Comment by deventw** [comment]
<img width="1404" alt="Screenshot 2023-12-31 at 13 46 35" src="https://github.com/1Panel-dev/1Panel/assets/63999575/fa1602a0-6c33-4eaa-a318-b285f9471215">

更新应用列表後依然未能成功安裝

**Comment by deventw** [comment]
重新安裝docker後已解決問題
