### ISSUE TITLE
[QUESTION]phps容器化，无法使用宿主机的ffmpeg,网上搜到的解决办法，不知道怎么在1panel里实现

### ISSUE THREAD

**Issue by egwang186** [1Panel-dev/1Panel#3493]
### 请描述您的问题

![image](https://github.com/1Panel-dev/1Panel/assets/113794160/b67462db-aaad-4070-a45b-f13220789506)

**Comment by egwang186** [comment]
![8e4bd189537312aeb61a6573cf0e5876](https://github.com/1Panel-dev/1Panel/assets/113794160/d2f219c0-3866-4f28-ad22-72d37681391d)

**Comment by zhengkunwang223** [comment]
> ![8e4bd189537312aeb61a6573cf0e5876](https://private-user-images.githubusercontent.com/113794160/293582770-d2f219c0-3866-4f28-ad22-72d37681391d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMDk4OTUsIm5iZiI6MTcwNDEwOTU5NSwicGF0aCI6Ii8xMTM3OTQxNjAvMjkzNTgyNzcwLWQyZjIxOWMwLTM4NjYtNGYyOC1hZDIyLTcyZDM3NjgxMzkxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQxMTQ2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTJhNTFmYTNlMjg1NzAzZTY4MzhjODFhMDc3NjQzYjNkOWNiYzYwYmNmMzFlODlmOWVjOTE3MDE4MjAxYjk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bUFMIL7LdjKZG5Oun9_Q8qNUceSa2XLp8v5nKWTPSws)

使用 /bin/sh

**Comment by egwang186** [comment]
ok，解决了
![187bd3607e850533bc61b953687c96b4](https://github.com/1Panel-dev/1Panel/assets/113794160/b2175f1f-06db-405e-9588-e120df0573b4)
