### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by system-help-solution** [1Panel-dev/1Panel#3494]
### 请描述您的问题

Gostaria de saber aonde eu coloco uma lista de apps ou eu posso incrementar já alguns aplicativos nativamente exemplo eu faço uma lista de app e quando é instalado um painel essa lista vai estar lá com instalar os aplicativos que eu colocar endócrino no caso aqui eu vi que funciona 90% em docker

**Comment by zhengkunwang223** [comment]
可以参考这个
https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8
