### ISSUE TITLE
alist webdav 无法备份

### ISSUE THREAD

**Issue by yeyudoc** [1Panel-dev/1Panel#3495]
### 请描述您的问题

![image](https://github.com/1Panel-dev/1Panel/assets/83936435/c67c7069-8222-4d2c-9c16-2a0394bc2b80)
网址路径哪里错了吗，我在阿里盘上看到了test文件夹，但提示WriteStream dav/185ali/test/1panel: 500

**Comment by ssongliu** [comment]
感谢反馈，test 文件夹下面有内容吗？可以检查一下权限设置。

**Comment by yeyudoc** [comment]
没有其他文件，alist账户权限都给了

**Comment by qwenode** [comment]
路径要 /dav 开头

**Comment by yeyudoc** [comment]
一样 提示500

**Comment by yeyudoc** [comment]
WriteStream /dav/185ali/test/1panel: 500

**Comment by qwenode** [comment]
你在alist 往 test 写入文件夹和文件试试是否正常

**Comment by yeyudoc** [comment]
正常，可以新建文件

**Comment by yeyudoc** [comment]
alist是拉取的最新版docker

**Comment by ssongliu** [comment]
麻烦添加一下我，我看看这个问题
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/a4183c8b-6bdf-4307-a376-7e3a946d2edc)

**Comment by FoLeaf** [comment]
解决了吗我也是这个问题

**Comment by qcmoke** [comment]
使用 alist 的 webdav 备份 1Panel 快照时，系统 CPU、内存占满，最终导致系统崩溃

**Comment by ssongliu** [comment]
> 解决了吗我也是这个问题

麻烦添加一下我好友，我远程看看这个问题
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/4aef02f3-69ca-47e2-9edb-f0e46ca26ecc)

**Comment by zeemanz** [comment]
我也遇到了这个问题

**Comment by zeemanz** [comment]
补充一下，配置反代后使用域名形式可以正常使用，但由于备份文件较大，需要修改 OpenResty 的配置文件，因此还是希望能够修复这个问题。
另外，经本人测试，使用 AList 挂载本机存储时可以正常使用 IP 形式。

**Comment by ssongliu** [comment]
webDav 添加时，应该以 /dav 开头，如下图，配置路径时应该是 /dav/tmp/sftp/xxx
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/8789e320-f8fd-46ba-a4f3-46bd497bab81)
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/d85d9a1d-b34b-44f7-80a8-dc531a20b8b2)

**Comment by wanghe-fit2cloud** [comment]
v1.9.6 版本已发布。

**Comment by almas-x** [comment]
> 补充一下，配置反代后使用域名形式可以正常使用，但由于备份文件较大，需要修改 OpenResty 的配置文件，因此还是希望能够修复这个问题。 另外，经本人测试，使用 AList 挂载本机存储时可以正常使用 IP 形式。

我也遇到域名反代alist备份文件上传失败问题，请教一下具体需要修改 OpenResty 的哪个配置项？

**Comment by muxinxy** [comment]
> > 补充一下，配置反代后使用域名形式可以正常使用，但由于备份文件较大，需要修改 OpenResty 的配置文件，因此还是希望能够修复这个问题。 另外，经本人测试，使用 AList 挂载本机存储时可以正常使用 IP 形式。
> 
> 我也遇到域名反代alist备份文件上传失败问题，请教一下具体需要修改 OpenResty 的哪个配置项？

我是这样改的：

`/opt/1panel/apps/openresty/openresty/conf/nginx.conf` 修改配置项 `client_max_body_size`（根据上传的文件大小进行修改）：
```
    client_max_body_size 500m; 
```
`/opt/1panel/apps/openresty/openresty/www/sites/yourdomain.com/proxy/root.conf` 增加配置项（根据上行带宽和上传的文件大小进行修改）：
```
    proxy_connect_timeout 180;
    proxy_send_timeout 180;
    proxy_read_timeout 180;
```
修改完需要重启 OpenResty 以及重载网站配置。

**Comment by jinweizhao** [comment]
> webDav 添加时，应该以 /dav 开头，如下图，配置路径时应该是 /dav/tmp/sftp/xxx ![image](https://private-user-images.githubusercontent.com/73214554/302239431-8789e320-f8fd-46ba-a4f3-46bd497bab81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MjMzNzcsIm5iZiI6MTcwODQyMzA3NywicGF0aCI6Ii83MzIxNDU1NC8zMDIyMzk0MzEtODc4OWUzMjAtZjhmZC00NmJhLWE0ZjMtNDZiZDQ5N2JhYjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA5NTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNTE5YzJjY2QwMmQ5MmViMDkzNzQxNGE0MDA4OGIyNDVhMmFiYjI3ZTZhOTUzZGU2ZjcyYmU0ZTNkNzBjMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sTDAxRg5-zhENVNuQ9wQQbsjuzWILNXFAALTGg4v_t8) ![image](https://private-user-images.githubusercontent.com/73214554/302239605-d85d9a1d-b34b-44f7-80a8-dc531a20b8b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MjMzNzcsIm5iZiI6MTcwODQyMzA3NywicGF0aCI6Ii83MzIxNDU1NC8zMDIyMzk2MDUtZDg1ZDlhMWQtYjM0Yi00NGY3LTgwYTgtZGM1MzFhMjBiOGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA5NTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YmM0MGUwZGQyMjAxM2U1MGE3ZWFlMmJmZmIzMTIzNTM4NjRkOGY0OTUwNTQwYmI3ZDc3Mjc4YWQ2MDUyMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WyoPcmUOysp8fNaz8d6on5SsuDU8Prs962Q-yHV6EhU)

英文路径是没问题的，中文路径还是报 500，文件夹是新建成功的，应该是 URL 中文编码问题吧

**Comment by AnHeYi** [comment]
今天同样遇到该问题了。请问有什么解决的办法吗？

**Comment by XiaoGe-LiBai** [comment]
/dav//夸克/1panel
我前段时间成功的路径居然多了个/
