### ISSUE TITLE
[BUG]工具箱中 hosts 解析没有忽略注释

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3497]
### 1Panel 版本

v1.9.2

### 问题描述

新出的工具箱里面有 hosts 修改功能，但是这个列表没有忽略 # 开头的注释行。
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/faf133aa-d1df-4ae8-be16-e8c322d0941f)
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/58273342-d5e8-49cd-aa20-f2cb5e070671)

### 重现步骤

/etc/hosts 文件中存在 # 开头的注释行，进入页面即可复现。

### 期待的正确结果

应该更新一下，把 # 开头的行在前端忽略掉。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
