### ISSUE TITLE
[QUESTION]快照恢复提示错误

### ISSUE THREAD

**Issue by xiexiaosheng** [1Panel-dev/1Panel#3498]
### 请描述您的问题

decompress file failed, err: stderr: gzip: stdin: not in gzip format tar: Child returned status 1 tar: Error is not recoverable: exiting now

**Comment by xiexiaosheng** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/64482026/e7f4731d-9cce-41da-83eb-af748ee44c75)

**Comment by ssongliu** [comment]
感谢反馈，错误显示快照压缩包解压失败，可以尝试手动解压看看文件是否有损坏

**Comment by ssongliu** [comment]
没有正常下载到快照文件
