### ISSUE TITLE
[FEATURE]应用商店创建应用时，默认填充没有被占用的端口

### ISSUE THREAD

**Issue by plateauandsp** [1Panel-dev/1Panel#350]
### 1Panel 版本

1.0.2

### 请描述您的需求或者改进建议

1panel在部署web应用的时候，端口默认都是8080

### 请描述你建议的实现方案

建议优化下，比如默认填充没有占用的端口，同时提示现在已经占用了哪些端口。

**Comment by zhengkunwang223** [comment]
您好  感谢建议 这个我们需要讨论一下
