### ISSUE TITLE
[QUESTION]请问这个怎么弄呢，没看到入口呢？

### ISSUE THREAD

**Issue by 1411430556** [1Panel-dev/1Panel#3506]
### 请描述您的问题

![image](https://github.com/1Panel-dev/1Panel/assets/67215517/a80535f1-71ed-4d79-83c0-556e6d206c72)
![image](https://github.com/1Panel-dev/1Panel/assets/67215517/04bf3b67-c524-4a26-b396-242d7cf36bcc)

**Comment by zhengkunwang223** [comment]
你这个版本有点低了 你升级到最新版
entrance 就是面板安全入口 你需要把这个添加到你的访问地址最后面
比如 http://127.0.0.1:9999/entrance

**Comment by 1411430556** [comment]
谢谢
