### ISSUE TITLE
[FEATURE] 请问证书中的 DNS 账户, 有没有支持 "新网帐号" 的计划

### ISSUE THREAD

**Issue by yimaoe** [1Panel-dev/1Panel#3507]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

请问证书中的 DNS 账户, 有没有支持 "新网帐号" 的计划

**Comment by zhengkunwang223** [comment]
https://go-acme.github.io/lego/dns/  
优先支持这个列表中的厂商 感谢理解
