### ISSUE TITLE
[BUG]UFW防火墙端口未拦截

### ISSUE THREAD

**Issue by midsmr** [1Panel-dev/1Panel#3508]
### 联系方式

midsmr@icloud.com

### 1Panel 版本

1.9.2

### 问题描述

<img width="1234" alt="截屏2024-01-03 21 48 21" src="https://github.com/1Panel-dev/1Panel/assets/61633355/a2e4dfc5-6976-4b7b-944c-76a87f1ef007">

<img width="1234" alt="截屏2024-01-03 21 48 46" src="https://github.com/1Panel-dev/1Panel/assets/61633355/5348475b-21fd-48e5-a089-faf6e97185dd">

可见并未放通3000端口为什么可以直接访问呢？

### 重现步骤

安装ufw后，在应用商店安装gitea可以直接跨过ufw防火墙进行访问

**Comment by wanghe-fit2cloud** [comment]
系统防火墙管理容器端口的需求，统一汇总到该 issue #1846
