### ISSUE TITLE
[BUG]应用商店-已安装页面-停止容器但仍在运行

### ISSUE THREAD

**Issue by zhichengroup** [1Panel-dev/1Panel#3509]
### 联系方式

zhichengroup@gmail.com

### 1Panel 版本

v1.9.2

### 问题描述

应用商店-已安装页面，停止容器但实际仍在运行

### 重现步骤

以postgres为例：
1. 在`应用商店-已安装`页面停止postgres，实际`docker ps`中pg进程仍在。
2. 在容器选项卡，`postgres-操作-更多-停止`，`docker ps`中进程消失。回到`应用商店-已安装`页面，显示pg仍在运行，实际pg已经down了。

**Comment by zhengkunwang223** [comment]
已安装的应用需要点击同步获取状态
停止应用不是删除容器 停止应用是 stop 容器 所以 docker ps 还能看到
