### ISSUE TITLE
终端管理支持代理

### ISSUE THREAD

**Issue by plateauandsp** [1Panel-dev/1Panel#351]
### 1Panel 版本

1.0.2

### 请描述您的需求或者改进建议

目前终端管理都是直接连接的主机，需要主机的密码。但是很多主机密码在堡垒机进行托管的

### 请描述你建议的实现方案

建设支持通过代理连接主机，比如支持通过JumpServer连接主机

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会讨论并验证该需求的可行性。

**Comment by wanghe-fit2cloud** [comment]
经团队内部讨论，我们在短期内大概率不会支持该需求。
