### ISSUE TITLE
[FEATURE]增加其他类型数据库管理功能

### ISSUE THREAD

**Issue by YakumoEirin** [1Panel-dev/1Panel#3510]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

postgresql和mariadb都没有类似于mysql的管理页面
希望往后的版本可以添加

**Comment by zhengkunwang223** [comment]
postgresql 下个版本支持 
mariadb 当前版本就支持 mysql 管理页面支持 mariadb

**Comment by 451891358** [comment]
sql server可以添加支持吗

**Comment by wanghe-fit2cloud** [comment]
> sql server可以添加支持吗

目前暂无计划支持，望理解。

**Comment by wanghe-fit2cloud** [comment]
PostgreSQL 需求重复 #758
