### ISSUE TITLE
容器异常停止 无法执行重建、重启、启动操作

### ISSUE THREAD

**Issue by TtBJSH** [1Panel-dev/1Panel#3511]
### 联系方式

ttbjsht@163.com

### 1Panel 版本

v1.8.5

### 问题描述

所有容器异常停止 删除容器新建报错，无法执行重启、启动操作

### 重现步骤

无

### 期待的正确结果

容器重新启动

### 相关日志输出

```shell
服务内部错误: Error response from daemon: driver failed programming external connectivity on endpoint 1Panel-mysql-ovVU (6f86f3fd820d4dd1806a4d859e757c24d898098b0a82dc23c5a5ee1a3320f422): Bind for 0.0.0.0:3307 failed: port is already allocated
```

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/46512682/1fab0953-6d76-4221-b222-3fd1d46baa4f)

**Comment by wanghe-fit2cloud** [comment]
1、可以通过 `systemctl status docker.service` 命令确认一下 docker 服务器状态（是不是因为断电、重启服务器等原因造成的docker服务异常）
2、通过 `journalctl -u docker.service -exf` 命令查看 docker 服务日志
3、部署的容器服务有没有设置重启策略（可以默认给一个 always）
4、看提供的错误信息是端口被占用了，可以查看一下具体是哪些应用占用了端口
5、可以通过 `systemctl restart network` 和 `systemctl restart docker.service` 命令来重启网络和docker服务，然后再手动重启一下docker应用

**Comment by wanghe-fit2cloud** [comment]
本地环境无法复现上述问题，暂时先关闭该 Issue 了。
