### ISSUE TITLE
[BUG] wordpress 6.3.1 文件删除了？

### ISSUE THREAD

**Issue by f2xme** [1Panel-dev/1Panel#3514]
### 1Panel 版本

1.9.2

### 问题描述

wordpress-6.3.1 文件被删除了，无法创建容器！
`
[2024-01-05 12:39:24] [INFO] download app[WordPress] from https://apps-assets.fit2cloud.com/stable/1panel/wordpress/6.3.1/wordpress-6.3.1.tar.gz  

[2024-01-05 12:39:26] [ERROR] download app[WordPress] error 文件不存在  
`

**Comment by wanghe-fit2cloud** [comment]
点击应用商店右上角的 `更新应用列表` 按钮更新应用后再来安装最新版本，如图：
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/5bc68a0a-b13b-498a-9ecf-4929806b4498">

**Comment by f2xme** [comment]
已经更新到了最新了
![1](https://github.com/1Panel-dev/1Panel/assets/42071814/49c5d9f6-efc1-4cf8-90ce-7e711ad901cf)
一键部署-新装应用-应用会创建失败
![2](https://github.com/1Panel-dev/1Panel/assets/42071814/9babd56d-95c0-40fe-947b-00e3e7f5fb4a)
日志显示文件不存在
![3](https://github.com/1Panel-dev/1Panel/assets/42071814/a83ba81c-60bb-4f55-ba90-67a9452c36eb)
只有安装 wordpress 6.3.1 失败，你们 oss 文件不存在，导致的
@wanghe-fit2cloud

**Comment by wanghe-fit2cloud** [comment]
是的，刚确认了一下目前 1Panel 维护的 WordPress 最新版是 v6.4.2，之前的老版本已经在阿里 OSS 上移除，望理解。
