### ISSUE TITLE
[QUESTION] 关于Java项目部署

### ISSUE THREAD

**Issue by stars-one** [1Panel-dev/1Panel#3515]
### 请描述您的问题

之前我使用宝塔管理面板,有时候自己开发个java项目,在服务器创建完mysql和数据库后,之后安装好java环境

通过命令行的方式启动jar文件即可运行java项目

我想知道在1Panel中应该如何实现我上述的类似操作?

**Comment by ichenhe** [comment]
个人感觉你的需求和面板没有什么关系。与曾经一样，通过 1panel 创建好数据库后直接命令行启动你的程序就行了。

1panel 整体都是基于容器的，应该不会提供管理原生 java 程序的支持。

**Comment by wanghe-fit2cloud** [comment]
> 个人感觉你的需求和面板没有什么关系。与曾经一样，通过 1panel 创建好数据库后直接命令行启动你的程序就行了。
> 
> 1panel 整体都是基于容器的，应该不会提供管理原生 java 程序的支持。

是的，目前版本推荐基于容器化方案来运行维护项目。

**Comment by wanghe-fit2cloud** [comment]
Java 需求重复 #748
