### ISSUE TITLE
[FEATURE] 通过命令行重载 openresty

### ISSUE THREAD

**Issue by ichenhe** [1Panel-dev/1Panel#3516]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

参见 #2815 ，但维护者好像理解错我的意思了。

希望能通过***命令行***重载 openresty，而不是在网页面板添加重载按钮。

理由：有时会在外部（不通过 1panel）更新 openresty 配置（比如更新证书），希望更新后能自动重载。但因为 openrestry 运行在容器中，由 1panel 管理，外部没有可靠的办法取得正确容器 id，从而无法直接执行 reload 命令。

### 请描述你建议的实现方案

类似下面的命令行工具：

```bash
1panel app openresty reload
```

**Comment by wanghe-fit2cloud** [comment]
收到，我们近期调研一下上述需求的解决方案。

**Comment by zhengkunwang223** [comment]
使用 docker exec 【你的 OpenResty 容器名称】 nginx -s reload 也能满足你的需求

**Comment by ichenhe** [comment]
@zhengkunwang223 

> 使用 docker exec 【你的 OpenResty 容器名称】 nginx -s reload 也能满足你的需求

理论上是的。但容器名是会变化的，尽管可以通过 `1Panel-openresty-` 的前缀查找，但这里的核心点在于「容器名并不是 public api 的一部分」，更像是 hack 做法。目前的确是这么实现的，不过如果能提供稳定的 api 自然更好。毕竟容器是 1panel 启动的，只有 1panel 可以明确知道容器 id。

这里其实引申出了更多问题：目前 1panel 并没有太多考虑外部操作，比如手动修改 nginx vhost 的配置，有可能导致 1panel 解析失败，可视化面板提示 500。更好的做法也许是识别这种情况，然后禁用可视化编辑，再提供一个一键还原的按钮。不过这些超出本 issue 的讨论范围了。

**Comment by zhengkunwang223** [comment]
> @zhengkunwang223 
> 
> 
> 
> > 使用 docker exec 【你的 OpenResty 容器名称】 nginx -s reload 也能满足你的需求
> 
> 
> 
> 理论上是的。但容器名是会变化的，尽管可以通过 `1Panel-openresty-` 的前缀查找，但这里的核心点在于「容器名并不是 public api 的一部分」，更像是 hack 做法。目前的确是这么实现的，不过如果能提供稳定的 api 自然更好。毕竟容器是 1panel 启动的，只有 1panel 可以明确知道容器 id。

如果你不手动修改容器名，容器名是不会改变的，如果你想多个主机都用一样的容器名，你可以在安装的时候指定容器名称都为openresty，已安装的可以在参数-编辑-高级设置中修改，这样你就可以有统一的脚本。顺道说一句，我们也没有记录容器 id ，我们只记录了容器名称，应用状态也是根据容器名称获取的。

**Comment by ichenhe** [comment]
> 如果你不手动修改容器名，容器名是不会改变的，如果你想多个主机都用一样的容器名，你可以在安装的时候指定容器名称都为openresty，已安装的可以在参数-编辑-高级设置中修改，这样你就可以有统一的脚本。顺道说一句，我们也没有记录容器 id ，我们只记录了容器名称，应用状态也是根据容器名称获取的。

了解，感谢解释。这么看的话的确可以自己与容器交互。
