### ISSUE TITLE
[BUG]清理镜像时，选择清理未使用镜像，只会列出当前页中未使用的镜像

### ISSUE THREAD

**Issue by colinwjd** [1Panel-dev/1Panel#3517]
### 1Panel 版本

1.9.2

### 问题描述

<img width="1383" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/7942918/cd2f04f3-a09b-40e6-8e12-b3e8f36fe789">
<img width="1322" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/7942918/e511ec49-f0f9-4ffa-bf29-78c23a30dfbd">

### 重现步骤

容器 -> 镜像 -> 清理镜像

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
