### ISSUE TITLE
[QUESTION] 使用快照报错

### ISSUE THREAD

**Issue by 12123ads** [1Panel-dev/1Panel#3518]
### 请描述您的问题

![Screenshot_2024-01-07-03-42-06-815_mark via-edit](https://github.com/1Panel-dev/1Panel/assets/69107029/0463a1cd-632f-4db4-8584-77008392113e)

**Comment by wanghe-fit2cloud** [comment]
已知问题 #3041 ，我们会在 v1.9.3 版本尝试修复上述问题。
