### ISSUE TITLE
对阿里云的aksk输入进行格式化

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [1Panel-dev/1Panel#352]
### 1Panel 版本

1.0.2

### 请描述您的需求或者改进建议

在添加阿里云的访问信息时，用户有时候会多复制一个空格，但面板不会检查有效性，可能会导致用户浪费很多时间去排查，这是阿里云页面自身的问题，希望能清除输入时阿里云访问令牌的所有空格。

### 请描述你建议的实现方案

使用一些格式化包进行预处理，或者在输入框内加一些处理规则［推荐，可以节省一点点入口带宽］。

**Comment by zhengkunwang223** [comment]
感谢建议，v1.0.3 优化
