### ISSUE TITLE
[FEATURE] Redis添加`远程服务器`功能

### ISSUE THREAD

**Issue by imJack6** [1Panel-dev/1Panel#3522]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

我使用非容器的Redis，想要使用1Panel管理

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持添加远程 Redis 数据库。

**Comment by dfmjndm** [comment]
+1，现有app都不支持使用远程的数据库部署，希望可以使用远程连接

**Comment by QYG2297248353** [comment]
裸机的Redis不能主动识别，添加远程数据库只支持mysql和postgresql
- [x] 添加远程 `Redis` 数据库支持

**Comment by Kingong** [comment]
+1，什么时候能支持呢？

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
