### ISSUE TITLE
[FEATURE]增加openwrt版本

### ISSUE THREAD

**Issue by Lunafreya-nox** [1Panel-dev/1Panel#3524]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

能否增加适合openwrt使用的1panl，使用别的一键安装，虽然成功了，但全是问题。

**Comment by wanghe-fit2cloud** [comment]
暂无适配计划，望理解。

**Comment by docker-master** [comment]
> ### 1Panel 版本
> 1.9.2
> 
> ### 请描述您的需求或者改进建议
> 能否增加适合openwrt使用的1panl，使用别的一键安装，虽然成功了，但全是问题。
> 
> ### 请描述你建议的实现方案
> _No response_
> 
> ### 附加信息
> _No response_

你怎么安装的？求教程

**Comment by gcsong023** [comment]
修改安装脚本的方式，在openwrt中可以运行。https://github.com/gcsong023/wrt_installer/tree/wrt_1panel

**Comment by wanghe-fit2cloud** [comment]
> 修改安装脚本的方式，在openwrt中可以运行。https://github.com/gcsong023/wrt_installer/tree/wrt_1panel

手动点赞 👍

**Comment by docker-master** [comment]
> 修改安装脚本的方式，在openwrt中可以运行。https://github.com/gcsong023/wrt_installer/tree/wrt_1panel

我这个没有权限写入，请问咋办
[1Panel Log]: 启动 Docker  
install.sh: line 65: systemctl: command not found
[1Panel Log]: ... 在线安装 docker-compose 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to open the file /usr/local/bin/docker-compose: No such file 
Warning: or directory
  0 56.8M    0 27988    0     0   182k      0  0:05:19 --:--:--  0:05:19  229k
curl: (23) Failure writing output to destination
[1Panel Log]: docker-compose 下载失败，请稍候重试

**Comment by gcsong023** [comment]
在OpenWrt系统中，并不存在systemctl命令，这使得依赖该命令的任何功能都无法正常运行，这也正是一些通用脚本无法在OpenWrt上顺利执行的主要原因。针对这个问题，我特地对原有的安装脚本进行了适配修改，将所有原本依赖systemctl命令的地方替换成了OpenWrt兼容的实现方式。

不过，值得注意的是，OpenWrt固件之间的差异性非常大，许多固件版本在内核层面就未提供对Docker的支持。因此，为了确保一键安装脚本的顺利运行，用户的OpenWrt固件必须预先满足对Docker的支持要求。这既是脚本运行的前提条件，也是保障用户体验的必要措施。

**Comment by gcsong023** [comment]
最近，我基于V1.10.1-lts源码，修改tar命令格式适配在busybox中运行，并替换源码中部分systemctl命令为service 的方式，修复了镜像快照及备份功能；打包生成了tar.gz文件，感兴趣的话，可以试试。[https://github.com/gcsong023/wrt1panel](https://github.com/gcsong023/wrt1panel)。

**Comment by docker-master** [comment]
发现有第三方Docker版的，moelin可好用了

**Comment by gcsong023** [comment]
> 发现有第三方Docker版的，moelin可好用了

嗯，我也有用了一段时间的moelin docker版本。

**Comment by tangger2000** [comment]
moelin的docker版本参考我之前的idea进行的实现。但我并无精力维护。

**Comment by neverdead117** [comment]
终于找到这个地方，装的也是moelin的版本，但是SSH和Docker都是失效的
服务内部错误: stderr: bash: line 1: systemctl: command not found

**Comment by wanghe-fit2cloud** [comment]
1Panel 最新版本的安装脚本已兼容 OpenWrt。

**Comment by edwinhuish** [comment]
> 1Panel 最新版本的安装脚本已兼容 OpenWrt。

实测并不行。。

**Comment by wanghe-fit2cloud** [comment]
> > 1Panel 最新版本的安装脚本已兼容 OpenWrt。
> 
> 实测并不行。。

脚本所在项目：https://github.com/1Panel-dev/installer

**Comment by edwinhuish** [comment]
@wanghe-fit2cloud 问题依旧。

使用的安装命令为：
```bash 
bash -c "$(curl -sSL https://raw.githubusercontent.com/1Panel-dev/installer/refs/heads/main/quick_start.sh)" 
```

![Image](https://github.com/user-attachments/assets/591dd9ca-4c76-4df5-aa5f-31a5a083e98e)

**Comment by wanghe-fit2cloud** [comment]
> [@wanghe-fit2cloud](https://github.com/wanghe-fit2cloud) 问题依旧。
> 
> 使用的安装命令为：
> 
> bash -c "$(curl -sSL https://raw.githubusercontent.com/1Panel-dev/installer/refs/heads/main/quick_start.sh)" 
> ![Image](https://github.com/user-attachments/assets/591dd9ca-4c76-4df5-aa5f-31a5a083e98e)

由于设备问题，你可以先自行查看一下 install.sh 脚本文件，看是否能定位到问题。

**Comment by edwinhuish** [comment]
之前使用 `quick_start.sh` 安装的，但它拉取的压缩包不是最新的。
```bash
bash -c "$(curl -sSL https://raw.githubusercontent.com/1Panel-dev/installer/refs/heads/main/quick_start.sh)" 
```

最后直接从github上下载最新的开发源码，安装后如图，还是有问题。`1panel` 命令缺失，网页URL也打不开
![Image](https://github.com/user-attachments/assets/eaf75d59-260d-400e-91d8-5bdb904ab299)

**Comment by wanghe-fit2cloud** [comment]
GitHub 仓库中的 quick_start 脚本在打包时做过修改，与正式文档中的版本有所不同，不能直接使用。

还是要使用 V1 官方文档中提供的脚本，地址：https://1panel.cn/docs/v1/installation/online_installation/
另外，1Panel V2 目前尚未集成 V1 的 OpenWRT 适配部分，暂时仍需使用 1Panel V1。

**Comment by purainity** [comment]
在 OpenWRT 上现在已经可以通过 Docker 方式运行 1Panel V2。
https://github.com/purainity/docker-1panel-v2
