### ISSUE TITLE
[FEATURE]快速命令管理页面中增加关键词筛选，以便于更好地管理命令。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3525]
### 1Panel 版本

v1.9.2

### 请描述您的需求或者改进建议

在【终端】-【快速命令】页面中，在目前分组筛选功能的基础上，能否增加关键词筛选功能。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.10.6-lts 版本已发布。
