### ISSUE TITLE
[QUESTION] PHP Laravel 在 Docker 容器下无法连接到 Redis 服务器

### ISSUE THREAD

**Issue by imJack6** [1Panel-dev/1Panel#3529]
### 请描述您的问题

（我不知道这个问题归终与哪里，是 Docker、Laravel、PHP、Redis 还是 1Panel 部署 PHP Docker 时的问题）总之就是用 Docker 容器下的 PHP Laravel 连接到 Redis 的时候一直会出现 `Redis
Exception` `Connection refused`，并且我在容器内使用 wget 判断 Redis 的端口也是正常打开的，但我把 PHP 部署到宿主机下则可以正常访问，不知道这是什么情况

**Comment by zhengkunwang223** [comment]
链接地址是类似 redis:6379 还是 127.0.0.1:6379 呢
容器中需要使用 类似 redis:6379 的地址链接

**Comment by imJack6** [comment]
> 链接地址是类似 redis:6379 还是 127.0.0.1:6379 呢 容器中需要使用 类似 redis:6379 的地址链接

是的，我在 PHP 容器中就是用的 redis:6379 连接，换了两次 Redis 均不行，一次是面板部署的 Redis 容器，一次是宿主机部署的 Redis，然后把 Nginx 和 PHP 从面板部署的容器更换为宿主机直接部署就可以，不知道是什么问题。

**Comment by zhengkunwang223** [comment]
> > 链接地址是类似 redis:6379 还是 127.0.0.1:6379 呢 容器中需要使用 类似 redis:6379 的地址链接
> 
> 是的，我在 PHP 容器中就是用的 redis:6379 连接，换了两次 Redis 均不行，一次是面板部署的 Redis 容器，一次是宿主机部署的 Redis，然后把 Nginx 和 PHP 从面板部署的容器更换为宿主机直接部署就可以，不知道是什么问题。

看一下论坛这个帖子能否解决你的问题：https://bbs.fit2cloud.com/t/topic/1388/3

**Comment by imJack6** [comment]
> > > 链接地址是类似 redis:6379 还是 127.0.0.1:6379 呢 容器中需要使用 类似 redis:6379 的地址链接
> > 
> > 
> > 是的，我在 PHP 容器中就是用的 redis:6379 连接，换了两次 Redis 均不行，一次是面板部署的 Redis 容器，一次是宿主机部署的 Redis，然后把 Nginx 和 PHP 从面板部署的容器更换为宿主机直接部署就可以，不知道是什么问题。
> 
> 看一下论坛这个帖子能否解决你的问题：https://bbs.fit2cloud.com/t/topic/1388/3

看了一下，我在我 Laravel 的 Redis 抛出异常部分文件没有找到相关类似代码（laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php [异常抛出在此文件的153行 `$client->{($persistent ? 'pconnect' : 'connect')}(...$parameters);`]）

**Comment by zhengkunwang223** [comment]
> > > > 链接地址是类似 redis:6379 还是 127.0.0.1:6379 呢 容器中需要使用 类似 redis:6379 的地址链接
> > > 
> > > 
> > > 是的，我在 PHP 容器中就是用的 redis:6379 连接，换了两次 Redis 均不行，一次是面板部署的 Redis 容器，一次是宿主机部署的 Redis，然后把 Nginx 和 PHP 从面板部署的容器更换为宿主机直接部署就可以，不知道是什么问题。
> > 
> > 
> > 看一下论坛这个帖子能否解决你的问题：https://bbs.fit2cloud.com/t/topic/1388/3
> 
> 看了一下，我在我 Laravel 的 Redis 抛出异常部分文件没有找到相关类似代码（laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php [异常抛出在此文件的153行 `$client->{($persistent ? 'pconnect' : 'connect')}(...$parameters);`]）

连接参数中是否有密码 从 1Panel 安装的 redis 默认创建了密码

**Comment by imJack6** [comment]
> > > > > 链接地址是类似 redis:6379 还是 127.0.0.1:6379 呢 容器中需要使用 类似 redis:6379 的地址链接
> > > > 
> > > > 
> > > > 是的，我在 PHP 容器中就是用的 redis:6379 连接，换了两次 Redis 均不行，一次是面板部署的 Redis 容器，一次是宿主机部署的 Redis，然后把 Nginx 和 PHP 从面板部署的容器更换为宿主机直接部署就可以，不知道是什么问题。
> > > 
> > > 
> > > 看一下论坛这个帖子能否解决你的问题：https://bbs.fit2cloud.com/t/topic/1388/3
> > 
> > 
> > 看了一下，我在我 Laravel 的 Redis 抛出异常部分文件没有找到相关类似代码（laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php [异常抛出在此文件的153行 `$client->{($persistent ? 'pconnect' : 'connect')}(...$parameters);`]）
> 
> 连接参数中是否有密码 从 1Panel 安装的 redis 默认创建了密码

有的，但是不管是有密码的 Redis 容器还是没密码的宿主机部署的 Redis 都无法连接，我感觉应该不是 Redis 的原因

**Comment by zhengkunwang223** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/cdfe065f-c5d2-485e-901a-c21e3755821e)
 加一下我的企业微信 我远程看看

**Comment by imJack6** [comment]
> ![image](https://private-user-images.githubusercontent.com/31820853/294874021-cdfe065f-c5d2-485e-901a-c21e3755821e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MTIxNDQsIm5iZiI6MTcwNDcxMTg0NCwicGF0aCI6Ii8zMTgyMDg1My8yOTQ4NzQwMjEtY2RmZTA2NWYtYzVkMi00ODVlLTkwMWEtYzIxZTM3NTU4MjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDExMDQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MGU1ZjhjOGE5YzFjNWQ5ZWVlYzM5YWE1ZDA2OGYwOGFmOTE0Njk0ZDY0Zjg0ZmVmODkxYzQ1ZDJhNmU2M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ehTksGOexEjGoR7sxFFALVeh-N10HfVSQkamzAopjj8) 加一下我的企业微信 我远程看看

加了
