### ISSUE TITLE
[FEATURE]希望增加对apache，node，java，go程序环境的支持

### ISSUE THREAD

**Issue by 982901760** [1Panel-dev/1Panel#353]
### 1Panel 版本

v1.0.2

### 请描述您的需求或者改进建议

希望增加对node，java，go程序环境的支持，还有进程守护管理器类似Supervisor，以及apache的web服务器

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会考虑以容器的方式支持不同的程序。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布，支持了 Supervisor 进程守护管理器。
后面版本会陆续支持 node，java，go 等运行环境。
