### ISSUE TITLE
[QUESTION]可以在主机->防火墙 设置端口转发吗?

### ISSUE THREAD

**Issue by hsjgit** [1Panel-dev/1Panel#3531]
### 请描述您的问题

可以在主机->防火墙 设置端口转发吗

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
