### ISSUE TITLE
希望有添加多个服务器节点显示基础资源信息的功能？

### ISSUE THREAD

**Issue by zorn-zhao** [1Panel-dev/1Panel#3532]
### 1Panel 版本

https://github.com/1Panel-dev/1Panel/releases/tag/v1.9.2

### 请描述您的需求或者改进建议

1、希望有添加多个服务器(linux\windows server)节点的功能，显示CPU\内存\硬盘空间\网络状态等的仪表盘
2、希望有告警功能，资源到达阈值(可自定义设置)，发送告警(邮件、钉钉、企业微信等)
3、可以20个节点内免费，20个节点以上收费。

**Comment by wanghe-fit2cloud** [comment]
多主机管理相关需求的讨论，统一汇总到该 issue #2692 
通知、告警相关需求的讨论，统一汇总到该 issue #614
