### ISSUE TITLE
[BUG]甲骨文云控制台乱码

### ISSUE THREAD

**Issue by loohalh** [1Panel-dev/1Panel#3533]
### 1Panel 版本

1.9.2

### 问题描述

centos 8 甲骨文云控制台安装log乱码

**Comment by wanghe-fit2cloud** [comment]
造成乱码的原因一般来说是由于服务器没有安装中文语言包或者字符编码不一造成的。
> 1Panel 在线安装脚本中使用了部分中文提示信息，目前还没有全部修改为英文的计划，望理解。
