### ISSUE TITLE
[FEATURE] 网站运行日志功能中新增切换自动刷新功能

### ISSUE THREAD

**Issue by sunist-c** [1Panel-dev/1Panel#3536]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

在『日志审计』->『网站日志』->『运行日志』或者『错误日志』中，会默认调用 `api/v1/files/read` 刷新内容

但是当使用面板反代面板自己，绑定域名的情况下，使用这一功能查看面板本身的运行日志，就会出现循环刷新的情况，希望能能够手动切换自动刷新选项避免

同时在左右滑动日志的时候，也会产生大量的调用请求

这两个情况下甚至能触发CC防护

### 请描述你建议的实现方案

1. 前端新增一个自动刷新按钮，用于切换自动刷新状态
2. 当 网站日志 的域名和面板绑定的域名一致时，停用自动刷新

### 附加信息

1. 自动刷新状况

![image](https://github.com/1Panel-dev/1Panel/assets/46150583/32a4ca0f-a245-4ba6-aafd-0fb4fbe1f552)

2. 左右滑频繁请求状况（滑动一次）

![image](https://github.com/1Panel-dev/1Panel/assets/46150583/52c69666-a408-4758-9068-3caca246cc8e)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
网站日志加载方式优化，计划在 v1.10.12 版本完成，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/3690
