### ISSUE TITLE
终端主机连接时总是红色字体显示Disconnected,打开开发者工具的控制台窗口显示 Could not decode a text frame as UTF-8

### ISSUE THREAD

**Issue by wxf26054** [1Panel-dev/1Panel#354]
### 请描述您的问题

![image](https://user-images.githubusercontent.com/22016320/226769922-f0793c8c-2905-483f-acdb-95cac2b0bd5e.png)

**Comment by wxf26054** [comment]
1. 操作系统：Ubuntu 21.10 (impish)
2. 架构：X64
3. 容器 - 终端 是否能够正常打开：可以打开
4. 终端连接其他服务器是否能正常：正常连接，通过jumpserver的web终端也可以连接到已部署1panel的服务器。
5. 其他使用说明：其他已部署服务器web终端可以正常连接。

**Comment by wxf26054** [comment]
> * 操作系统：Ubuntu 21.10 (impish)
> * 架构：X64
> * 容器 - 终端 是否能够正常打开：可以打开
> * 终端连接其他服务器是否能正常：正常连接，通过jumpserver的web终端也可以连接到已部署1panel的服务器。
> * 其他使用说明：其他已部署服务器web终端可以正常连接。

1. 操作系统：Ubuntu 21.10 (impish)
2. 架构：X64
3. 容器 - 终端 是否能够正常打开：可以打开
4. 终端连接其他服务器是否能正常：正常连接，通过jumpserver的web终端也可以连接到已部署1panel的服务器。
5. 其他使用说明：其他已部署服务器web终端可以正常连接。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已经发布，麻烦升级到最新版本查看一下是否还存在上述问题。

**Comment by wxf26054** [comment]
已解决, 感谢

**Comment by Jiraiya8** [comment]
我是1.3.6的版本，这个问题依然存在。WebSocket链接错误

**Comment by Jiraiya8** [comment]
我加端口访问是可以正常访问终端的，比如端口是12315，但是使用nginx反代从443端口进入的时候，就出问题了，也会展示，disconnected。问题还是websocket连接失败，因为端口是wss的连接端口是443，而不是我真实的端口12315
