### ISSUE TITLE
[BUG] 申请证书使用 手动解析 方法出现的申请窗口解析域名的复制按钮错误

### ISSUE THREAD

**Issue by imJack6** [1Panel-dev/1Panel#3548]
### 1Panel 版本

1.9.2

### 问题描述

申请证书的时候用 `手动解析` 申请会有个窗口，窗口 `解析域名` 那个 `复制按钮` 错误，复制的不是 `解析域名`，是旁边的 `记录值`。

### 重现步骤

[证书]申请证书->[验证方式]手动解析->确认->[操作]申请->单击 `[解析域名]复制按钮`，这时候复制的是旁边的 `记录值` 内容

### 期待的正确结果

复制正确

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，这周发布的 v1.9.3 版本将会修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
