### ISSUE TITLE
[QUESTION] 问一下手动解析DNS有泛域名的怎么解析

### ISSUE THREAD

**Issue by imJack6** [1Panel-dev/1Panel#3549]
### 请描述您的问题

申请证书其他域名写了个泛域名并且手动解析DNS，申请的的时候让我把域名 `_acme-challenge.*.码.cn` 添加到TXT解析，然后我去阿里云解析DNS里面加，给我提示 `*只允许在首位、和"*"后面只允许跟"."`，这不就尬住了，然后我用DNS账号自动申请也失败（阿里云的Key肯定没问题，我申请单个域名不申请泛域名就可以）
```
2024/01/09 23:10:31 [INFO] [码.cn] acme: Cleaning DNS-01 challenge
2024/01/09 23:10:31 [WARN] [码.cn] acme: cleaning up failed: alicloud: zone cn. not found in AliDNS for domain _acme-challenge.码.cn. 
2024/01/09 23:10:31 [INFO] [*.码.cn] acme: Cleaning DNS-01 challenge
2024/01/09 23:10:31 [WARN] [*.码.cn] acme: cleaning up failed: alicloud: zone cn. not found in AliDNS for domain _acme-challenge.码.cn. 
2024/01/09 23:10:32 [INFO] Deactivating auth: https://码EaLA
2024/01/09 23:10:34 [INFO] Deactivating auth: https://码uPKA
2024/01/09 23:10:34 申请  [码.cn] 证书失败, error: one or more domains had a problem:
[*.码.cn] [*.码.cn] acme: error presenting token: alicloud: zone cn. not found in AliDNS for domain _acme-challenge.码.cn.
[码.cn] [码.cn] acme: error presenting token: alicloud: zone cn. not found in AliDNS for domain _acme-challenge.码.cn.
```

**Comment by zhengkunwang223** [comment]
账号权限都对的吗

**Comment by imJack6** [comment]
> 账号权限都对的吗

阿里云的 `AccessKey` 吗

**Comment by zhengkunwang223** [comment]
> > 账号权限都对的吗
> 
> 阿里云的 `AccessKey` 吗

是的 你的 Key 是否有权限操作你的 DNS

**Comment by imJack6** [comment]
> > > 账号权限都对的吗
> > 
> > 
> > 阿里云的 `AccessKey` 吗
> 
> 是的 你的 Key 是否有权限操作你的 DNS

有的，这个 Key 我还用到 DDNSGO 里面

**Comment by zhengkunwang223** [comment]
> > > > 账号权限都对的吗
> > > 
> > > 
> > > 阿里云的 `AccessKey` 吗
> > 
> > 
> > 是的 你的 Key 是否有权限操作你的 DNS
> 
> 有的，这个 Key 我还用到 DDNSGO 里面

DDNSGO 中添加 阿里云 账号的时候 是否需要添加 区域ID RAM权限之类的参数

**Comment by imJack6** [comment]
> > > > > 账号权限都对的吗
> > > > 
> > > > 
> > > > 阿里云的 `AccessKey` 吗
> > > 
> > > 
> > > 是的 你的 Key 是否有权限操作你的 DNS
> > 
> > 
> > 有的，这个 Key 我还用到 DDNSGO 里面
> 
> DDNSGO 中添加 阿里云 账号的时候 是否需要添加 区域ID RAM权限之类的参数

没有，并且运行正常，使用的不是 RAM 子账户 AccessKey

**Comment by zhengkunwang223** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/12ea44c6-b9ca-404d-aa4f-90cfb786d097)
加我企业微信 我看一下

**Comment by zhengkunwang223** [comment]
经查
ZeroSSL 和 Google Cloud 类型的发放证书有问题
Let's Encrypt 没问题 
可能与 DNS 服务器有关

**Comment by imJack6** [comment]
已解决，一共操作了两点，但不知道具体是哪一点解决的
1. 将 `域名 DNS` 从 `阿里云` 转移到了 `CloudFlare`
2. 将 `服务器 DNS` 从 `阿里云DNS` 切换到了 `CloudFlare DNS 和 Google DNS`

现申请证书已正常，但 ZeroSSL 的证书泛域名仍不能申请，没有错误，不知道是不支持还是什么
```
2024/01/10 16:33:43 申请  [域名.cn] 证书失败, error: one or more domains had a problem:
[*.域名.cn] acme: error: 0 ::  :: 
```
