### ISSUE TITLE
关于1panel对docker compose的支持

### ISSUE THREAD

**Issue by FD-AU** [1Panel-dev/1Panel#3550]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

在新版Docker Engine已经集成Docker Compose Plugin，这种情况下或许不必再安装独立的Docker Compose，可以让用户选择使用独立版或插件版。
我观察了一下install.sh，当前的1panel似乎并没有支持插件版的使用。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
最新版本 docker 已经原生支持了 docker compose 命令，但 1Panel 还需要兼容用户自行安装的低版本 docker 的情况，还需要依赖宿主机的 docker-compose 命令。
