### ISSUE TITLE
[FEATURE]  建议兼容 Ali Cloud Linux ,可以在上面装1panel

### ISSUE THREAD

**Issue by ByZhouhang** [1Panel-dev/1Panel#3551]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

现状：我们现在服务器都是debian装的1panel.  我们准备测试环境上托管ACK,然后阿里那边推荐的云主机系统是用Ali Cloud Linux 。 没有 debian  ubuntu，所以想的是 在阿里的这个系统这个上面用1panel，毕竟很熟悉了，而且编辑文本，看文本啥的，部署简单的应用也方便，这样两个环境能共存，也可以用1panel部署，也可以用k8s方式部署测试。

阿里的linux系统兼容  centos RHEL，不太理解为啥1panel 不支持在这个系统上面使用？

![1704848594416](https://github.com/1Panel-dev/1Panel/assets/43258053/37fe2704-4c2f-46e3-98cb-0590c6742083)
![7201c2de6747e3f8210855f0a487806](https://github.com/1Panel-dev/1Panel/assets/43258053/56f75aac-a126-4eb2-9129-d190dc8a6991)

**Comment by wanghe-fit2cloud** [comment]
Ali Cloud Linux 不在 docker 官方脚本的支持列表里，需要自行安装 docker，可参考其 [官方教程](https://help.aliyun.com/zh/ecs/use-cases/deploy-and-use-docker-on-alibaba-cloud-linux-2-instances)

阿里云市场也提供了制作好的 1Panel 镜像，操作系统就是 Ali Cloud Linux。

**Comment by imJack6** [comment]
https://1panel.cn/docs/faq/operating_system/#1-docker-error-unsupported-distribution-xxx
