### ISSUE TITLE
从远程下载文件时 

### ISSUE THREAD

**Issue by 775728212** [1Panel-dev/1Panel#3552]
### 1Panel 版本

1.9.2

### 问题描述

文件-从远程下载 下载的链接返回的状态码是302 下载下来的是一个重定向后的连接 

### 重现步骤

主机-文件-从远程下载 下载一个状态码是302的文件链接

### 期待的正确结果

应该是重定向后的文件

**Comment by zhengkunwang223** [comment]
用 wget + 下载链接能下载到吗

**Comment by 775728212** [comment]
> 用 wget + 下载链接能下载到吗

刚刚试了一下 wget可以使用curl需要加-L

**Comment by zhengkunwang223** [comment]
> > 用 wget + 下载链接能下载到吗
> 
> 刚刚试了一下 wget可以使用curl需要加-L

有具体的下载链接吗 我们试一下

**Comment by 775728212** [comment]
> > > 用 wget + 下载链接能下载到吗
> > 
> > 
> > 刚刚试了一下 wget可以使用curl需要加-L
> 
> 有具体的下载链接吗 我们试一下

抱歉我这个是内网连接

**Comment by wanghe-fit2cloud** [comment]
你可以添加企业微信（备注 `协助定位 1Panel 远程下载文件问题`），我们远程你环境看一下问题。
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/3d435821-46e5-4dbb-8cee-282167348625)
