### ISSUE TITLE
[QUESTION] 网站添加反向代理时代理协议选择其它配置总是无法验证通过

### ISSUE THREAD

**Issue by imJack6** [1Panel-dev/1Panel#3553]
### 请描述您的问题

不知道是我用法不对，还是什么
```
服务内部错误: stderr: 2024/01/10 10:37:31 [emerg] 153#153: invalid URL prefix in /www/sites/example.com/proxy/root.conf:2 nginx: [emerg] invalid URL prefix in /www/sites/example.com/proxy/root.conf:2 nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed
```

**Comment by wanghe-fit2cloud** [comment]
提供一下创建反向代理网站时的代理地址，我们本地也复现一下。

**Comment by imJack6** [comment]
> 提供一下创建反向代理网站时的代理地址，我们本地也复现一下。

是本地运行的服务 127.0.0.1:8088

**Comment by wanghe-fit2cloud** [comment]
> > 提供一下创建反向代理网站时的代理地址，我们本地也复现一下。
> 
> 是本地运行的服务 127.0.0.1:8088

代理地址需要添加上具体的协议，比如：http、https、socket 等

**Comment by imJack6** [comment]
> > > 提供一下创建反向代理网站时的代理地址，我们本地也复现一下。
> > 
> > 
> > 是本地运行的服务 127.0.0.1:8088
> 
> 代理地址需要添加上具体的协议，比如：http、https、socket 等

我是用的 1Panel 的添加反向代理功能，Http 和 Https 均可添加成功，但 其他 怎么都添加不成功

**Comment by wanghe-fit2cloud** [comment]
这样来添加代理地址，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/c4a526c5-923d-49b9-85d5-f5dd3741b841)

**Comment by imJack6** [comment]
> 这样来添加代理地址，如图： ![image](https://private-user-images.githubusercontent.com/46734380/295464190-c4a526c5-923d-49b9-85d5-f5dd3741b841.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjcxNjEsIm5iZiI6MTcwNDg2Njg2MSwicGF0aCI6Ii80NjczNDM4MC8yOTU0NjQxOTAtYzRhNTI2YzUtOTIzZC00OWI5LTg1ZDUtZjVkZDM3NDFiODQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA2MDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MDRiODhhMjZkOGJmNTkwYWVkYjVkYWI3M2YxZjI4YmJjNjNhYzg1YTQyYzc0ODA5NThhZjA4NTk5Y2E0OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XJRpqrtpYnIdujosbTWZ7px30yBQIfUs2hE2yPcLKXo)

收到，感谢
