### ISSUE TITLE
[BUG] 1Panel下 新增图片内容，无法通过域名正常显示

### ISSUE THREAD

**Issue by Pinkyou1** [1Panel-dev/1Panel#3555]
### 1Panel 版本

v1.9.2

### 问题描述

index文件夹下上传.jpg.png，图片无法通过域名正常打开出现（https://域名+/xx.png） 404 Not Found

### 重现步骤

通过BT整体迁移过来的图片是可以正常打开，但再次从1Panel下增加上传内容，就无法通过域名正常浏览内容，已检查文件夹权限：0750 .jpg权限0644

### 期待的正确结果

可以正常通过域名打开查看图片内容

**Comment by zhengkunwang223** [comment]
文件和文件夹权限默认是 1000:1000 了吗

**Comment by Pinkyou1** [comment]
> 文件和文件夹权限默认是 1000:1000 了吗

文件夹  0750  - (1000)	- (1000)	
图片    0644  - (1000)	- (1000)

**Comment by zhengkunwang223** [comment]
> > 文件和文件夹权限默认是 1000:1000 了吗
> 
> 文件夹 0750 - (1000) - (1000) 图片 0644 - (1000) - (1000)

我试了一下 没有复现 
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/3d435821-46e5-4dbb-8cee-282167348625)
你可以加我企业微信 我远程看一下

**Comment by wanghe-fit2cloud** [comment]
先关闭该 Issue 了，后续如有问题再继续讨论。
