### ISSUE TITLE
[FEATURE] 建议为网站和数据库备份还原时添加确认选项

### ISSUE THREAD

**Issue by imJack6** [1Panel-dev/1Panel#3557]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

刚手贱给数据库还原到昨天晚上的备份了，直接就还原了，没有确认，建议先确认是否要还原

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
