### ISSUE TITLE
[QUESTION] SSH 登陆日志适配 CentOS Stream 9

### ISSUE THREAD

**Issue by licx506** [1Panel-dev/1Panel#3566]
### 请描述您的问题

如题，使用lastb命令查看到的登录失败日志有很多，但是在面板的登录日志中看不到这些失败日志，就无法对暴力破解IP进行限制。

**Comment by ssongliu** [comment]
感谢反馈，请问一下你使用的是 1panel 最新版本吗？

**Comment by licx506** [comment]
是的，使用的最新版

**Comment by ssongliu** [comment]
可以麻烦发一下系统日志文件到我邮箱吗？ liu.song@fit2cloud.com
系统日志文件在 /var/log/auth.log* 或者是 /var/log/secure*

**Comment by licx506** [comment]
> 可以麻烦发一下系统日志文件到我邮箱吗？ [liu.song@fit2cloud.com](mailto:liu.song@fit2cloud.com) 系统日志文件在 /var/log/auth.log* 或者是 /var/log/secure*

已发邮件，麻烦了~

**Comment by ssongliu** [comment]
> > 可以麻烦发一下系统日志文件到我邮箱吗？ [liu.song@fit2cloud.com](mailto:liu.song@fit2cloud.com) 系统日志文件在 /var/log/auth.log* 或者是 /var/log/secure*
> 
> 已发邮件，麻烦了~

感谢，明天看一下

**Comment by ssongliu** [comment]
比较了一下，数据是差不多的，只是 lastb 一个错误登陆会显示两条记录
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/c85f5ac0-5bc5-4b90-9402-56a6f2dbadf9)
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/38cf055a-fe5a-43cf-9240-8fb72f858ca2)

**Comment by licx506** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/96540683/6d952265-5fec-4408-a5e4-d77a9c9b2fc5)
 在我自己的系统里，只能看到登陆成功的登陆日志

**Comment by licx506** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/96540683/d0705601-fffe-4fe9-8b96-be0105bae092)
是最新版的

**Comment by ssongliu** [comment]
操作系统和版本是啥？确实你的日志格式不太一致

**Comment by licx506** [comment]
> 操作系统和版本是啥？确实你的日志格式不太一致

**Comment by licx506** [comment]
> 操作系统和版本是啥？确实你的日志格式不太一致

```
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

**Comment by ssongliu** [comment]
> > 操作系统和版本是啥？确实你的日志格式不太一致
> 
> ```
> NAME="CentOS Stream"
> VERSION="9"
> ID="centos"
> ID_LIKE="rhel fedora"
> VERSION_ID="9"
> PLATFORM_ID="platform:el9"
> PRETTY_NAME="CentOS Stream 9"
> ANSI_COLOR="0;31"
> LOGO="fedora-logo-icon"
> CPE_NAME="cpe:/o:centos:centos:9"
> HOME_URL="https://centos.org/"
> BUG_REPORT_URL="https://bugzilla.redhat.com/"
> REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
> REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
> ```

暂时没有适配过该版本，后续版本适配。

**Comment by licx506** [comment]
> > > 操作系统和版本是啥？确实你的日志格式不太一致
> > 
> > 
> > ```
> > NAME="CentOS Stream"
> > VERSION="9"
> > ID="centos"
> > ID_LIKE="rhel fedora"
> > VERSION_ID="9"
> > PLATFORM_ID="platform:el9"
> > PRETTY_NAME="CentOS Stream 9"
> > ANSI_COLOR="0;31"
> > LOGO="fedora-logo-icon"
> > CPE_NAME="cpe:/o:centos:centos:9"
> > HOME_URL="https://centos.org/"
> > BUG_REPORT_URL="https://bugzilla.redhat.com/"
> > REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
> > REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
> > ```
> 
> 暂时没有适配过该版本，后续版本适配。

这个系统的也需要适配

NAME="Oracle Linux Server"
VERSION="8.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://github.com/oracle/oracle-linux"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.9

**Comment by licx506** [comment]
> Oracle Linux Server
CentOS Stream的日志重新放到你邮箱了，昨天发错了昨天发的是Oracle Linux Server的日志。这两个系统都是这样的问题，前几个版本还能正常识别，忘了是哪个版本升级后就不行了

**Comment by ssongliu** [comment]
测试最新的版本 1.10.19 已经解决了该问题，请更新后重试
