### ISSUE TITLE
[QUESTION]面板502

### ISSUE THREAD

**Issue by wonglamho** [1Panel-dev/1Panel#3567]
### 请描述您的问题

甲骨文ARM部署后面板一直Error 502，系统Ubuntu 20.04
端口已开放，正常挂起1Panel服务，防火墙关闭，1Panel状态是Active，日志无报错，但是端口Ping不通
试着用装在同一服务器上的nginx proxy manager反代本地IP也打不开

**Comment by wanghe-fit2cloud** [comment]
1、1pctl status 查看运行状态
2、netstat -ntlp 查看端口绑定情况（1pctl listen-ip 命令可以切换监听 IP）
3、curl 127.0.0.1:服务端口 是否正常

**Comment by wonglamho** [comment]
<img width="1235" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/29705004/58e3854b-643a-4827-b6e6-5d27f26517fe">
<img width="658" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/29705004/831a1132-97d7-4d08-a879-f3da655a3cc9">
<img width="723" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/29705004/b991f6f6-e230-4afe-9b3b-153eedbf2046">

**Comment by wanghe-fit2cloud** [comment]
上述信息来看 1Panel 服务运行正常。
那可能还是需要在 1Panel 服务器所处网络环境来定位问题，比如防火墙、安全组等。

**Comment by wonglamho** [comment]
这要怎么排查，ufw是inactive的状态，安全组全放行

**Comment by Osub** [comment]
me too

**Comment by RayWangQvQ** [comment]
> 上述信息来看 1Panel 服务运行正常。 那可能还是需要在 1Panel 服务器所处网络环境来定位问题，比如防火墙、安全组等。

同样现象，建议重新开启该issue。

我在另外2台amd的机子安装都很顺滑，就这个龟壳的arm鸡不行，现象一样。

但应该也不是服务商的防火墙和安全组设置的问题，因为我停掉1panel后，将同一个端口用nginx反代到我的另一个服务（个人博客），使用ip+端口访问一切正常。

**Comment by WillWilliams012** [comment]
同樣有這個問題，無法排除~ 問問大家如何排除的~ 感恩~

**Comment by WillWilliams012** [comment]
@wanghe-fit2cloud 了解，我有找到這個ISSUE 不過這裡沒有給出解決方案，也沒有提到是OSS CDN 的問題，還是不太懂處理，跟據您在https://github.com/1Panel-dev/1Panel/issues/4747#issuecomment-2080973421 的回覆，主要有問題是甲骨文的ARM 機器用的網路對於1PANEL的CDN 連線不好，換個雲供應商是不是目前最好的解決方案，謝謝您~

**Comment by binaryYuki** [comment]
同 我暂时的解决方案就是用另一台小的实例走内网 NAT 转发
感觉不像是服务商的问题？

**Comment by WillWang2122** [comment]
同問，ARM 炸但AMD 都好

**Comment by kylin17** [comment]
同样问题+1

**Comment by xiaotianxt** [comment]
> 同样问题 +1

哦我这边是因为改了代理策略，tailscale 域名走代理了🤣

**Comment by IpiggyI** [comment]
我不清楚为何这个issue被关闭了，问题似乎并没有被解决

**Comment by fxaxg** [comment]
> > 同样问题 +1
> 
> 哦我这边是因为改了代理策略，tailscale 域名走代理了🤣

我也是，系统代理原因

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> >Same question +1
>
> Oh, because the agency policy has been changed, the tailscale domain name is now an agency. 🤣

Me too, it’s because of the system proxy

**Comment by 0511150** [comment]
还是502
