### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by system-help-solution** [1Panel-dev/1Panel#3568]
### 请描述您的问题

Atualmente a fazer instalação do traefik sempre dá erro geralmente usar a rede overlay ela não aceita  conectar a esse rede usando o modo brid instala porém não consigo usar o traefick. Sendo que sem o 1panel instalado funciona!

**Comment by wanghe-fit2cloud** [comment]
Could you please provide more detailed information about the specific issue or requirement?

**Comment by system-help-solution** [comment]
Certo o traefick dentro do 1panel mesmo estando na mesmo rede ele não consegue expor o programa para web gera certinho o ssl porém. Aí consegue fazer seu Proxy reverso e expor ele para o mundo

**Comment by wanghe-fit2cloud** [comment]
Forneça algumas capturas de tela para nos ajudar a entender melhor o seu significado. Agradecemos a sua cooperação.

> English: Please provide some screenshots to help us better understand your meaning. Thank you for your cooperation.

**Comment by system-help-solution** [comment]
Falo só de isso 
Essa e o traefik 
https://doc.traefik.io/traefik/

No arquivo abaixo 

version: '3.8'

# mais info: https://youtu.be/o7tBbYy-5I4
services:
  traefik:
    image: traefik:latest
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker.exposedbydefault=false
      - --providers.docker.swarmMode=true
      #defina a mesma rede que você criou para o traefik
      - --providers.docker.network=traefik_public
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      # Config para SSL Lets Encrypt
      # altere para seu e-mail
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.email=seu_email@email.com
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      # Global HTTP -> HTTPS
      #- --entrypoints.web.http.redirections.entryPoint.to=websecure
      #- --entrypoints.web.http.redirections.entryPoint.scheme=https
      #- --api
      #- --log.level=DEBUG
    ports:
      - "80:80"
      #- "8080:8080" # porta do painel do traefik, caso queira ver todas as rotas.
      - "443:443"
    volumes:
      - traefik_certificates:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - traefik_public

volumes:
  traefik_certificates:
    external: true

networks:
  traefik_public:
    external: true

Certo ele até cria  eu consigo entrar nele na web certinho porém caso eu fazer um Proxy reverso usando ele ele gera o ssl porém não consegue expor o container que fizer com a configuração dele não vai. Deu para entende ! 


Isso dentro do 1panel fora dele funciona perfeitamente!

**Comment by system-help-solution** [comment]
Aqui tá o exemplo do mínio com traefick.  


version: "3.8"

services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    networks:
      - traefik_public
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: <USUARIO_AQUI>
      MINIO_ROOT_PASSWORD: <SENHA_AQUI>
      MINIO_BROWSER_REDIRECT_URL: https://console.SEU_DOMINIO.com.br
      MINIO_SERVER_URL: https://s3.SEU_DOMINIO.com.br
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
          limits:
            cpus: '0.2'
            memory: 512M
      labels:
        - traefik.enable=true
        #SSL 1 endereço publico do Minio
        - traefik.http.routers.minio_s3.rule=Host(`s3.SEU_DOMINIO.com.br`)
        - traefik.http.routers.minio_s3.tls.certresolver=le
        - traefik.http.routers.minio_s3.entrypoints=websecure
        - traefik.http.routers.minio_s3.tls=true
        - traefik.http.routers.minio_s3.service=minio_s3
        - traefik.http.services.minio_s3.loadbalancer.server.port=9000
        #SSL 2 endereço console do minio
        - traefik.http.routers.minio_console.rule=Host(`console.SEU_DOMINIO.com.br`)
        - traefik.http.routers.minio_console.tls.certresolver=le
        - traefik.http.routers.minio_console.entrypoints=websecure
        - traefik.http.routers.minio_console.tls=true
        - traefik.http.routers.minio_console.service=minio_console
        - traefik.http.services.minio_console.loadbalancer.server.port=9001

volumes:
  minio_data:
    external: true

networks:
  traefik_public:
    external: true
...

O mio sobre porém não consigo aceso na web pelo domínio que eu colocar 

E somente por 1panel tá acontecendo isso. Com portainer .io não acontece e nem com outro projeto baseado em administração de docker  semelhante ao 1panel

**Comment by wanghe-fit2cloud** [comment]
O 1Panel é baseado no comando docker-compose na máquina hospedeira para criar e manter aplicações de contêiner, e a implantação do Traefik é a mesma. Portanto, entendo que isso não deve ter relação com a plataforma 1Panel.

> English: 1Panel is based on the docker-compose command on the host machine to create and maintain container applications, and deploying Traefik is the same.  So, I understand that this should have no relation to the 1Panel platform.

**Comment by system-help-solution** [comment]
Certo como não estou conseguindo além da minha equipe . Poderia trazer o traefik de uma forma que funcione com demais apps pois já fizemos de tudo. . fora do 1panel direto na vps (servidor Linux funciona perfeitamente com as 2 configurações que te enviei ) ou quem sabe uma possível solução para esse erro .
