### ISSUE TITLE
面板设置将服务器地址从 ip 修改为域名之后应用打不开了

### ISSUE THREAD

**Issue by jinhuili-lab** [1Panel-dev/1Panel#3569]
### 1Panel 版本

lastest

### 问题描述

当我在面板设置将服务器地址从ip修改为域名之后，所有应用都打不开了。注意的是，不是面板地址。
重启、同步、重建都没用。
并且当我从域名改回服务器之后，应用又可以打开了。打开方式是点击了应用商店已安装应用的的端口链接

### 重现步骤

如上

**Comment by wanghe-fit2cloud** [comment]
你在服务器地址中设置的域名可以正确解析到 1Panel 服务器吗？
> 应用或者容器列表的跳转功能，就是自动浏览器访问 `服务器地址：端口`。

**Comment by jinhuili-lab** [comment]
重启面板后可以了
