### ISSUE TITLE
[FEATURE] 希望增加一個清理緩存的工具

### ISSUE THREAD

**Issue by HimiCos** [1Panel-dev/1Panel#357]
### 1Panel 版本

1.0.2

### 请描述您的需求或者改进建议

有沒有清理的工具，有些軟件包想要查看有沒有刪除乾淨，緩存之類的。

**Comment by wanghe-fit2cloud** [comment]
感谢建议，后面版本我们会考虑增加清理缓存类的工具。

**Comment by wanghe-fit2cloud** [comment]
如果有相关工具可以继续反馈给我们，看能否集成到应用商店中。
