### ISSUE TITLE
[BUG]zip压缩后文件没变小

### ISSUE THREAD

**Issue by zyyfit** [1Panel-dev/1Panel#3575]
### 1Panel 版本

1.9.3

### 问题描述

相关问题  https://github.com/1Panel-dev/1Panel/issues/2230
在文件列表，压缩文件，产生的zip文件没有变小，这个是页面压缩的，下面的 60k 的是手动压缩的
![图片](https://github.com/1Panel-dev/1Panel/assets/73461316/538200be-3d43-4062-a711-de14669dceaa)
![图片](https://github.com/1Panel-dev/1Panel/assets/73461316/20f39836-8ddd-45de-86e8-83e95e37cd85)

### 重现步骤

同上

**Comment by ssongliu** [comment]
感谢反馈，我们先本地复现一下。

**Comment by wanghe-fit2cloud** [comment]
v1.9.4 版本已发布。
