### ISSUE TITLE
[QUESTION]Redis 当前状态页面 used_memory 的意思是不是错了

### ISSUE THREAD

**Issue by hsjgit** [1Panel-dev/1Panel#3576]
### 请描述您的问题

数据库->redis->设置->当前状态
<img width="307" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/32933584/316f4e12-7e6f-483e-b13a-a1205c823159">
used_memory 的意思是不是错了
版本:v1.9.2

**Comment by ssongliu** [comment]
感谢反馈，后续版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
