### ISSUE TITLE
1panel 1.9.2 安装halo2.11.3 报错

### ISSUE THREAD

**Issue by demonyins** [1Panel-dev/1Panel#3577]
### 请描述您的问题

1panel 1.9.2 安装halo2.11.3 报错，什么原因
halo 安装是报错：halo-2.11.3  | Error: Port Library failed to initialize: -86
halo-2.11.3  | Error: Could not create the Java Virtual Machine.
halo-2.11.3  | Error: A fatal exception has occurred. Program will exit.

**Comment by wanghe-fit2cloud** [comment]
提供一下 1Panel 服务器操作系统版本以及 Docker 版本。

**Comment by wanghe-fit2cloud** [comment]
先关闭该 Issue 了。如果手动升级 docker 后还存在问题，再继续讨论。
