### ISSUE TITLE
[FEATURE]  创建快照时支持选择本地存储 和 从容器跳转到部署的yml 文件目录

### ISSUE THREAD

**Issue by ByZhouhang** [1Panel-dev/1Panel#3579]
### 1Panel 版本

1.9.2

### 请描述您的需求或者改进建议

1、新增备份镜像可以存储在本地
      因为一般服务器挂载了NAS, 放本地，速度块，而且不会走公网流量，挂载到其他主机恢复也快
      
2、容器跳转到部署的yml 文件目录
      容器太多了，找到部署的目录位置，每次都要进目录切换半天，现实中需要常改配置文件，重启容器，希望在容器入口增加一个跳转到部署目录的功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1、想表达的应该是面板设置的备份快照功能吧。

**Comment by ByZhouhang** [comment]
> 感谢反馈。 1、想表达的应该是面板设置的备份快照功能吧。

是的，看着 1panel 越来越好用，加油💪

**Comment by wanghe-fit2cloud** [comment]
收到，我们会在后续版本考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布，支持了快照可以存储在本地磁盘的需求。

**Comment by ByZhouhang** [comment]
> v1.9.5 版本已发布。

从容器跳转到 docker-compose.yml的文件夹功能有嘛？ 没看到啊，这个功能还实用性还挺强的

**Comment by wanghe-fit2cloud** [comment]
> 从容器跳转到 docker-compose.yml的文件夹功能有嘛

该功能其实主要针对应用商店已安装应用，所以要实现跳转功能，可以借助已有功能：
1、点击 `应用` 按钮跳转到已安装应用列表
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/606cee1f-a74c-4970-9a4c-8ac160e6c15b)

2、点击 `目录` 按钮跳转至文件管理页面来管理 yml 和其他配置文件。
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/e1e9619e-1ee5-4ed6-984a-41818ded7b26)

**Comment by ByZhouhang** [comment]
好吧，我指的是不是应用商店，自己docker-compose，启动的容器应用
![image](https://github.com/1Panel-dev/1Panel/assets/43258053/f8970e52-5ce7-49f8-ace7-80cfeb009d2b)

**Comment by wanghe-fit2cloud** [comment]
> 我指的是不是应用商店，自己docker-compose，启动的容器应用

了解，我先把该 Issue 打开了。后续版本会考虑在 `编排` 页面增加跳转到 compose 文件目录的功能。

**Comment by ssongliu** [comment]
1.10.20  版本支持编排跳转

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
