### ISSUE TITLE
[FEATURE]希望增加端口设置功能

### ISSUE THREAD

**Issue by kshdb** [1Panel-dev/1Panel#358]
### 1Panel 版本

v1.0.2

### 请描述您的需求或者改进建议

希望增加端口设置功能，害怕服务器端口被扫描！

**Comment by wanghe-fit2cloud** [comment]
我们将优先在 v1.1.0 版本中支持。

**Comment by wanghe-fit2cloud** [comment]
面板设置 - 安全 菜单中，支持自定义服务端口。

**Comment by kshdb** [comment]
防火墙端口？

**Comment by wanghe-fit2cloud** [comment]
了解，系统防火墙功能预计在下个月的功能版本中发布。

**Comment by wanghe-fit2cloud** [comment]
v1.1.0 版本已发布。

**Comment by kshdb** [comment]
谢谢 very GOOD





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月13日(星期四) 下午4:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [1Panel-dev/1Panel] [FEATURE]希望增加端口设置功能 (Issue #358)






关闭#358如已完成。

—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.
