### ISSUE TITLE
[FEATURE] 优化一下申请证书中 Acme 帐户显示对应账号类型的样式

### ISSUE THREAD

**Issue by imJack6** [1Panel-dev/1Panel#3580]
### 1Panel 版本

1.9.3

### 请描述您的需求或者改进建议

在浏览器窗口开的比较小的时候，申请证书中的 Acme 帐户提示的账号类型就会遮挡部分邮箱（手机端的话后半邮箱后缀基本就看不到了）
![image](https://github.com/1Panel-dev/1Panel/assets/58357771/89c732c4-fd76-4fb1-82db-58d698d55d37)
![image](https://github.com/1Panel-dev/1Panel/assets/58357771/b1476115-fb2f-4ac1-b13c-7ce347366281)

### 请描述你建议的实现方案

可以和网站设置中配置HTTPS时选择 Acme 帐户样式差不多就好了
![image](https://github.com/1Panel-dev/1Panel/assets/58357771/25a263b4-c000-44ed-9afe-285b35e5648a)
![image](https://github.com/1Panel-dev/1Panel/assets/58357771/d3f514b7-923a-4811-b6f9-1f32441f1d64)

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本优化

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
