### ISSUE TITLE
[BUG] php扩展模板

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#3582]
### 联系方式

交流群5 9a6ac...

### 1Panel 版本

1.9.3

### 问题描述

扩展模板， 在切换php版本后就不行了， 只有第一次可以
![ac17015192d15f95e089d73ed812ffc](https://github.com/1Panel-dev/1Panel/assets/51264840/2fdbe4c5-a5cd-472a-b0dc-81b4af2689d9)

### 重现步骤

点击默认的扩展模板后，切换php版本

### 期待的正确结果

切换php版本，也可以选择扩展模板

**Comment by zhengkunwang223** [comment]
感谢反馈 后续版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.9.4 版本已发布。
