### ISSUE TITLE
[QUESTION] for the apps, if I want to change the apps secondly, where is the apps dir.

### ISSUE THREAD

**Issue by jinhuili-lab** [1Panel-dev/1Panel#3583]
### 请描述您的问题

Only the yml/conf file is not enough.

**Comment by jinhuili-lab** [comment]
Where is the truly path of the apps?

**Comment by wanghe-fit2cloud** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/e03fd93c-b16e-45e6-8e17-6b7beaab1df0)
