### ISSUE TITLE
[BUG]WebDAV无法保存

### ISSUE THREAD

**Issue by zuozihan** [1Panel-dev/1Panel#3585]
### 1Panel 版本

v1.9.3

### 问题描述

WebDAV无法保存
![image](https://github.com/1Panel-dev/1Panel/assets/45542784/2051947e-a29e-4a4e-8ca1-b25633b8a0d8)

### 重现步骤

面板设置->账号备份->添加WebDAV

**Comment by ssongliu** [comment]
感谢反馈，下个小版本解决该问题

**Comment by wanghe-fit2cloud** [comment]
v1.9.4 版本已发布。
