### ISSUE TITLE
[BUG]手机浏览docker容器界面遮挡问题

### ISSUE THREAD

**Issue by birdxs** [1Panel-dev/1Panel#3588]
### 联系方式

birdxs@163.com

### 1Panel 版本

1.9.3

### 问题描述

更新1.9.3版本后，手机端查看docker容器界面，默认最右边是容器的操作接口，遮挡操作，不方便

### 重现步骤

进去面板，点击容器就复现了

### 期待的正确结果

容器的操作选项默认隐藏，需要的时候在点击...打开
![Screenshot_20240112_171841_com huawei browser](https://github.com/1Panel-dev/1Panel/assets/36181736/63d8c71e-89fc-410b-b7dd-2ef675705bc7)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。
