### ISSUE TITLE
[FEATURE]建议添加告警通知功能

### ISSUE THREAD

**Issue by xiao-si-qi** [1Panel-dev/1Panel#3589]
### 1Panel 版本

v1.9.2

### 请描述您的需求或者改进建议

建议添加告警通知功能，比如登录告警、内存占用报警、硬盘占用报警等……，可以推送到邮箱、钉钉、企业微信、等平台

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，通知、告警相关需求的讨论，统一汇总到该 issue #614
