### ISSUE TITLE
[FEATURE] Halo建站时添加超级用户名限制提示，否则将导致用户资料无法更改

### ISSUE THREAD

**Issue by yusixian** [1Panel-dev/1Panel#359]
### 1Panel 版本

v1.0.2

### 请描述您的需求或者改进建议

Halo建站时的超级管理员用户名，自动生成的是带下划线的，一般用户也不会去更改，但是建站后会被这个卡住，只能重新创建，体验不佳
![image](https://user-images.githubusercontent.com/43498495/226796262-414cb3dd-7fb2-4f01-9081-c10650415fdf.png)

卡住截图：
![image](https://user-images.githubusercontent.com/43498495/226799995-9cb0512f-17c6-4b86-9047-1994a023680b.png)

### 请描述你建议的实现方案

在Halo的一键部署界面的参数Input框上增加校验

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，该问题预计将在本周发布的 v1.0.3 版本完成修复。
