### ISSUE TITLE
[BUG] Let's Encrypt DNS 签发的问题

### ISSUE THREAD

**Issue by g-mero** [1Panel-dev/1Panel#3591]
### 1Panel 版本

1.9.3

### 问题描述

在DNS账号模式下使用CloudFlare的API进行签发，一直在签发中直至超时，cf那边已经出现了dns记录，后续选择跳过dns校验可以正常签发，不勾选的话会报错说dns记录已经存在，是不是签发中的dns检验部分有问题，能不能再首次签发时就跳过校验步骤，或者直接改为定时向acme请求签发。 对于dns记录已经存在的情况，能否先删除dns记录再添加（api应该是有这个权限的）

### 重现步骤

在DNS账号模式下使用CloudFlare的API进行签发

**Comment by zhengkunwang223** [comment]
当前我们使用了一个 lego 的 sdk 来实现了我们的证书申请， 验证 dns 是为了检验 dns 配置中的 txt 值是否添加成功， 如果跳过，可能会导致证书签发失败。 中间的验证逻辑我们没办法修改，所以暂时只能保持现在的方式，如果后面有很好的方式，我们会更新。感谢你的反馈。

**Comment by g-mero** [comment]
但是为什么超时后再验证就会成功呢，这里没有用您说的那个库吗。 只有首次验证会有这个问题
![image](https://github.com/1Panel-dev/1Panel/assets/62990607/439e8a8e-07c9-40e2-b80e-a88db14628b4)

**Comment by g-mero** [comment]
> > 但是为什么超时后再验证就会成功呢，这里没有用您说的那个库吗。 只有首次验证会有这个问题
> > ![image](https://private-user-images.githubusercontent.com/62990607/296284688-439e8a8e-07c9-40e2-b80e-a88db14628b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzUyMTgsIm5iZiI6MTcwNTA3NDkxOCwicGF0aCI6Ii82Mjk5MDYwNy8yOTYyODQ2ODgtNDM5ZThhOGUtMDdjOS00MGUyLWI4MGUtYTg4ZGIxNDYyOGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1NTUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmODhhOTM1ZjM2ZDQ1MTBjMjA1YzkwOTkxN2RlYjA2ZWI1MDA4NDQyYzllMzQ1Njk4YmEwMjgzNWMxMzI5Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L5xv0-q5J_Y4KIFsZXNXAdnFZgP7vU2IJbi6flKI4lA)
> 
> 是超时之后又申请了一遍吗，有没有勾选跳过 dns 验证

勾选了，所以还是这个库的问题吗

**Comment by ajirocn** [comment]
我也超时了，txt有记录，勾选不勾选都超时，申请不了，不管是let还是zero都一样

**Comment by ajirocn** [comment]
> > 但是为什么超时后再验证就会成功呢，这里没有用您说的那个库吗。 只有首次验证会有这个问题
> > 
> > ![image](https://github.com/1Panel-dev/1Panel/assets/62990607/439e8a8e-07c9-40e2-b80e-a88db14628b4)
> > 
> > 
> 
> 是超时之后又申请了一遍吗，有没有勾选跳过 dns 验证

我也超时了，txt有记录，勾选不勾选都超时，申请不了，不管是let还是zero都一样

**Comment by zhengkunwang223** [comment]
> > > 但是为什么超时后再验证就会成功呢，这里没有用您说的那个库吗。 只有首次验证会有这个问题
> > > 
> > > ![image](https://github.com/1Panel-dev/1Panel/assets/62990607/439e8a8e-07c9-40e2-b80e-a88db14628b4)
> > > 
> > > 
> > 
> > 是超时之后又申请了一遍吗，有没有勾选跳过 dns 验证
> 
> 我也超时了，txt有记录，勾选不勾选都超时，申请不了，不管是let还是zero都一样

以前有问题吗

**Comment by MakesYT** [comment]
检查一下ipv6吧,如果你有ipv6他会使用v6来验证,看来你v6没有网络权限

**Comment by MakesYT** [comment]
@zhengkunwang223 这应该是ipv6的原因,lego库那边也有人发issue说这个问题,感觉可以加一个ipv6接通性的验证,我修了ipv6后申请证书也正常了

**Comment by zhengkunwang223** [comment]
> @zhengkunwang223 这应该是ipv6的原因,lego库那边也有人发issue说这个问题,感觉可以加一个ipv6接通性的验证,我修了ipv6后申请证书也正常了

是禁用了 ipv6 吗

**Comment by MakesYT** [comment]
> > @zhengkunwang223 这应该是ipv6的原因,lego库那边也有人发issue说这个问题,感觉可以加一个ipv6接通性的验证,我修了ipv6后申请证书也正常了
> 
> 是禁用了 ipv6 吗

不是,是有ipv6地址,但是没有网络访问权限

**Comment by zhengkunwang223** [comment]
> > > @zhengkunwang223 这应该是ipv6的原因,lego库那边也有人发issue说这个问题,感觉可以加一个ipv6接通性的验证,我修了ipv6后申请证书也正常了
> 
> > 
> 
> > 是禁用了 ipv6 吗
> 
> 
> 
> 不是,是有ipv6地址,但是没有网络访问权限

没有网络访问权限是被防火墙拦截,还是什么

**Comment by MakesYT** [comment]
> > > > @zhengkunwang223 这应该是ipv6的原因,lego库那边也有人发issue说这个问题,感觉可以加一个ipv6接通性的验证,我修了ipv6后申请证书也正常了
> > 
> > > 
> > 
> > > 是禁用了 ipv6 吗
> > 
> > 
> > 
> > 不是,是有ipv6地址,但是没有网络访问权限
> 
> 没有网络访问权限是被防火墙拦截,还是什么
> 

获取到了错误的ipv6地址，我这边上级是ikuai v6那里设置错了，有ip但是用不了

**Comment by zhengkunwang223** [comment]
> > > > > @zhengkunwang223 这应该是ipv6的原因,lego库那边也有人发issue说这个问题,感觉可以加一个ipv6接通性的验证,我修了ipv6后申请证书也正常了
> > > 
> > > > 
> > > 
> > > > 是禁用了 ipv6 吗
> > > 
> > > 
> > > 
> > > 不是,是有ipv6地址,但是没有网络访问权限
> > 
> > 没有网络访问权限是被防火墙拦截,还是什么
> > 
> 
> 获取到了错误的ipv6地址，我这边上级是ikuai v6那里设置错了，有ip但是用不了

明白，感谢反馈

**Comment by MakesYT** [comment]
> > > > > > @zhengkunwang223 这应该是ipv6的原因,lego库那边也有人发issue说这个问题,感觉可以加一个ipv6接通性的验证,我修了ipv6后申请证书也正常了
> > > > 
> > > > > 
> > > > 
> > > > > 是禁用了 ipv6 吗
> > > > 
> > > > 
> > > > 
> > > > 不是,是有ipv6地址,但是没有网络访问权限
> > > 
> > > 没有网络访问权限是被防火墙拦截,还是什么
> > > 
> > 
> > 获取到了错误的ipv6地址，我这边上级是ikuai v6那里设置错了，有ip但是用不了
> 
> 明白，感谢反馈

lego那边我看关于v6造成验证超时的问题挺多的

**Comment by g-mero** [comment]
> 检查一下ipv6吧,如果你有ipv6他会使用v6来验证,可能你v6没有网络权限

确实，我将debian服务器的ipv6设置为禁用就正常申请了
