### ISSUE TITLE
[BUG] 自带的证书管理无法生成证书，使用nginx-proxy-manage可以成功申请证书

### ISSUE THREAD

**Issue by MarsMan1994** [1Panel-dev/1Panel#3592]
### 1Panel 版本

1.9.3

### 问题描述

cloudflare 同样api-token的配置，使用nginx-proxy-manage可以正常签发证书。使用自带的证书管理总是签发失败。
以下是日志：
2024/01/13 05:43:21 开始申请证书,域名 [xxx.xxx.xxx] 申请方式 [DNS 自动] DNS 账号 [cloudflare] 厂商 [CloudFlare]
2024/01/13 05:43:21 [INFO] [xxx.xxx.xxx] acme: Obtaining bundled SAN certificate
2024/01/13 05:43:22 [INFO] [xxx.xxx.xxx] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3036628xxxxx
2024/01/13 05:43:22 [INFO] [xxx.xxx.xxx] acme: Could not find solver for: tls-alpn-01
2024/01/13 05:43:22 [INFO] [xxx.xxx.xxx] acme: Could not find solver for: http-01
2024/01/13 05:43:22 [INFO] [xxx.xxx.xxx] acme: use dns-01 solver
2024/01/13 05:43:22 [INFO] [xxx.xxx.xxx] acme: Preparing to solve DNS-01
2024/01/13 05:43:22 [INFO] [xxx.xxx.xxx] acme: Cleaning DNS-01 challenge
2024/01/13 05:43:23 [WARN] [xxx.xxx.xxx] acme: cleaning up failed: cloudflare: failed to find zone pro.: zone could not be found 
2024/01/13 05:43:23 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/3036628xxxxx
2024/01/13 05:43:23 申请  [xxx.xxx.xxx] 证书失败, error: one or more domains had a problem:
[xxx.xxx.xxx] [xxx.xxx.xxx] acme: error presenting token: cloudflare: failed to find zone pro.: zone could not be found

### 重现步骤

点击申请

**Comment by zhengkunwang223** [comment]
用的是 global api key 吗

**Comment by MarsMan1994** [comment]
> 用的是 global api key 吗

global api key  和dns apt key 都不行，两个都试过了。我也很郁闷

**Comment by zhengkunwang223** [comment]
> > 用的是 global api key 吗
> 
> 
> 
> global api key  和dns apt key 都不行，两个都试过了。我也很郁闷

看日志是 zone 找不到，你的token权限是给的所有zone吗

**Comment by MarsMan1994** [comment]
> > > 用的是 global api key 吗
> > 
> > 
> > global api key  和dns apt key 都不行，两个都试过了。我也很郁闷
> 
> 看日志是 zone 找不到，你的token权限是给的所有zone吗
是的所有区域权限
![图片](https://github.com/1Panel-dev/1Panel/assets/32359814/90b90775-9484-4e1c-ae1a-e4ef6910e1d3)
![图片](https://github.com/1Panel-dev/1Panel/assets/32359814/893a6235-ecc4-4c71-835f-4e2a7ed298fb)

**Comment by zhengkunwang223** [comment]
> > > > 用的是 global api key 吗
> > > 
> > > 
> > > global api key  和dns apt key 都不行，两个都试过了。我也很郁闷
> > 
> > 
> > 看日志是 zone 找不到，你的token权限是给的所有zone吗
> > 是的所有区域权限

有用户反馈 把 ipv6 关掉就能申请成功 你可以试一下

**Comment by MarsMan1994** [comment]
> > > > > 用的是 global api key 吗
> > > > 
> > > > 
> > > > global api key  和dns apt key 都不行，两个都试过了。我也很郁闷
> > > 
> > > 
> > > 看日志是 zone 找不到，你的token权限是给的所有zone吗
> > > 是的所有区域权限
> > > ![图片](https://private-user-images.githubusercontent.com/32359814/296548785-90b90775-9484-4e1c-ae1a-e4ef6910e1d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDMwMTcsIm5iZiI6MTcwNTMwMjcxNywicGF0aCI6Ii8zMjM1OTgxNC8yOTY1NDg3ODUtOTBiOTA3NzUtOTQ4NC00ZTFjLWFlMWEtZTRlZjY5MTBlMWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA3MTE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhOTQ5MjcxN2MyMzgxYWVhNjZiYmZmMzM5YzgzMzMwOTFjZTc4OTFmYjUzMjlmMmI0Mzg1MWFjODAxNzkzNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7ynPb9PBbZsOUXyQsjlCK9zK3s-PttZmAyBpaHc4ySo)
> > > ![图片](https://private-user-images.githubusercontent.com/32359814/296548831-893a6235-ecc4-4c71-835f-4e2a7ed298fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDMwMTcsIm5iZiI6MTcwNTMwMjcxNywicGF0aCI6Ii8zMjM1OTgxNC8yOTY1NDg4MzEtODkzYTYyMzUtZWNjNC00YzcxLTgzNWYtNGUyYTdlZDI5OGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA3MTE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NWRiNDAzYjQ1NWIxOTRmOTk1ZjYzYzBmOTdlZjczYjdlNTkxMDZhNmY1ZmU2NDQ1YWRmY2FiMjEzMzQyMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-vmeM7yK4d3I8q_OtGN6GdzyJ0gLX73ujqII6_kCbv8)
> 
> 有用户反馈 把 ipv6 关掉就能申请成功 你可以试一下

不知道你说的ipv6是哪个？ cloudflare 现在不支持关闭ipv6，所以我尝试关闭了服务器的ipv6 
![image](https://github.com/1Panel-dev/1Panel/assets/32359814/a4c508a0-45c5-4082-9e38-a72b508b6be7)
貌似还是不行。
![image](https://github.com/1Panel-dev/1Panel/assets/32359814/4aed9c34-2121-4ebf-8afe-aac96f8e1c62)
不知道是不是系统兼容性的问题

**Comment by zhengkunwang223** [comment]
> > > > > > 用的是 global api key 吗
> 
> > > > > 
> 
> > > > > 
> 
> > > > > global api key  和dns apt key 都不行，两个都试过了。我也很郁闷
> 
> > > > 
> 
> > > > 
> 
> > > > 看日志是 zone 找不到，你的token权限是给的所有zone吗
> 
> > > > 是的所有区域权限
> 
> > > > ![图片](https://private-user-images.githubusercontent.com/32359814/296548785-90b90775-9484-4e1c-ae1a-e4ef6910e1d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDMwMTcsIm5iZiI6MTcwNTMwMjcxNywicGF0aCI6Ii8zMjM1OTgxNC8yOTY1NDg3ODUtOTBiOTA3NzUtOTQ4NC00ZTFjLWFlMWEtZTRlZjY5MTBlMWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA3MTE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhOTQ5MjcxN2MyMzgxYWVhNjZiYmZmMzM5YzgzMzMwOTFjZTc4OTFmYjUzMjlmMmI0Mzg1MWFjODAxNzkzNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7ynPb9PBbZsOUXyQsjlCK9zK3s-PttZmAyBpaHc4ySo)
> 
> > > > ![图片](https://private-user-images.githubusercontent.com/32359814/296548831-893a6235-ecc4-4c71-835f-4e2a7ed298fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDMwMTcsIm5iZiI6MTcwNTMwMjcxNywicGF0aCI6Ii8zMjM1OTgxNC8yOTY1NDg4MzEtODkzYTYyMzUtZWNjNC00YzcxLTgzNWYtNGUyYTdlZDI5OGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA3MTE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NWRiNDAzYjQ1NWIxOTRmOTk1ZjYzYzBmOTdlZjczYjdlNTkxMDZhNmY1ZmU2NDQ1YWRmY2FiMjEzMzQyMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-vmeM7yK4d3I8q_OtGN6GdzyJ0gLX73ujqII6_kCbv8)
> 
> > 
> 
> > 有用户反馈 把 ipv6 关掉就能申请成功 你可以试一下
> 
> 
> 
> 不知道你说的ipv6是哪个？ cloudflare 现在不支持关闭ipv6，所以我尝试关闭了服务器的ipv6 
> 
> ![image](https://github.com/1Panel-dev/1Panel/assets/32359814/a4c508a0-45c5-4082-9e38-a72b508b6be7)
> 
> 貌似还是不行。
> 
> ![image](https://github.com/1Panel-dev/1Panel/assets/32359814/4aed9c34-2121-4ebf-8afe-aac96f8e1c62)
> 
> 不知道是不是系统兼容性的问题

只给一个全部区域 dns 编辑权限试试

**Comment by wanghe-fit2cloud** [comment]
> 只给一个全部区域 dns 编辑权限试试

根据上述提示操作后，问题是否已解决？

> 建议将 1Panel 系统升级到最新版本
先关闭该 Issue 了，如果依然存在问题，继续在该 Issue 中讨论

**Comment by seepine** [comment]
1Panel最新版，同样的问题，用两个KEY都不行，zerossl也是一样的错误，用其他软件用同一个APIKey就能申请到
```
cloudflare: failed to find zone deno.dev.: zone could not be found
```
