### ISSUE TITLE
[BUG]hosts修改界面下面的提示错了

### ISSUE THREAD

**Issue by luoshan5261486** [1Panel-dev/1Panel#3593]
### 1Panel 版本

1.9.3

### 问题描述

![屏幕截图 2024-01-13 161014](https://github.com/1Panel-dev/1Panel/assets/135194011/fd1b4411-4dba-4bb7-a4d4-de0db6ba4e4f)
提示错了 不应该是修改时区的吧

### 重现步骤

无

**Comment by ssongliu** [comment]
感谢反馈，下个小版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.9.4 版本已发布。
