### ISSUE TITLE
[BUG]面板ssl开启后,ssl自动续期,但是面板ssl没有续期[BUG]

### ISSUE THREAD

**Issue by lchjczw** [1Panel-dev/1Panel#3596]
### 1Panel 版本

1.9.2

### 问题描述

[BUG]面板ssl开启后,ssl自动续期,但是面板ssl没有续期

### 重现步骤

[BUG]面板ssl开启后,ssl自动续期,但是面板ssl没有续期

**Comment by zhengkunwang223** [comment]
面板 ssl 需要手动重启面板
或者可以在计划任务定时重启

**Comment by lchjczw** [comment]
那是不是在自动续期面板所在证书的时候,就自动重启服务呢,不然时间到了,都登录不进去了,这不不方便嘛

**Comment by lchjczw** [comment]
去配置定时任务,也不知道ssh证书自动续期的时间,假如是80天,那这个定时任务改如何设置呢?80天的周期,还是?

**Comment by zhengkunwang223** [comment]
> 去配置定时任务,也不知道ssh证书自动续期的时间,假如是80天,那这个定时任务改如何设置呢?80天的周期,还是?

我们自动续期是距离到期时间10天开始，你可以根据你的证书过期时间来决定

**Comment by yiGmMk** [comment]
> 去配置定时任务,也不知道ssh证书自动续期的时间,假如是80天,那这个定时任务改如何设置呢?80天的周期,还是?

@zhengkunwang223 @lchjczw 请教下定时任务申请证书功能在哪里,页面上没看到有,还是说需要通过脚本调接口实现
