### ISSUE TITLE
[FEATURE]WebDAV 备份链接设置不合理，端口应该为非必填。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3598]
### 1Panel 版本

v1.9.3

### 请描述您的需求或者改进建议

使用 Cloudreve等网盘程序的webdav时根本无法连接。
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/5cb0d45d-def8-41de-b90e-1598180f7a3f)

### 请描述你建议的实现方案

我的程序是一个 https://yun.ysmj.xyz/dav 这样的 api 接口，如果按照当前的方式填写就变成了 “https://yun.ysmj.xyz/dav:80” ，显然这样是无法连接的，所以端口应该不是必填项。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by qwenode** [comment]
你地址应该填 https://yun.ysmj.xyz
路径填: /dav
端口填: 80

这个如果优化的话,估计要把3个参数合并为一个参数,只要填url

**Comment by wanghe-fit2cloud** [comment]
v1.9.4 版本已发布，目前是取消了必填校验。
