### ISSUE TITLE
[FEATURE]主机-监控保留时长30日 是否过短？

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3599]
### 1Panel 版本

v1.9.3

### 请描述您的需求或者改进建议

主机-监控保留时长30日 是否过短？能否可自定义。方便查询更长的时间监控。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
自定义主机监控时长相关需求的讨论，统一汇总到该 issue #2050
