### ISSUE TITLE
[BUG]130.163.x.x,这个IP号段提示超时

### ISSUE THREAD

**Issue by dike3120** [1Panel-dev/1Panel#360]
### 1Panel 版本

1.0.2

### 问题描述

130.163.x.x,这个IP号段不能下载sh文件，提示超时，我把sh文件从别的vps拷贝过来，也不能下载，
Welcome to Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-144-generic x86_64)
Last login: Wed Mar 22 01:21:40 2023 from 146.56.184.192
root@ubuntu:~# curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sudo bash quick_start.sh
curl: (28) Failed to connect to resource.fit2cloud.com port 443: Connection timed out
root@ubuntu:~# 
用146.56.x.x就能安装成功。

### 重现步骤

Welcome to Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-144-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * Introducing Expanded Security Maintenance for Applications.
   Receive updates to over 25,000 software packages with your
   Ubuntu Pro subscription. Free for personal use.

     https://ubuntu.com/pro
New release '22.04.2 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Last login: Wed Mar 22 01:46:11 2023 from 223.72.130.92
root@ubuntu:~# curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sudo bash quick_start.sh
curl: (28) Failed to connect to resource.fit2cloud.com port 443: Connection timed out
root@ubuntu:~# ./quick_start.sh
-bash: ./quick_start.sh: Permission denied
root@ubuntu:~# chmod 755 quick_start.sh
root@ubuntu:~# ./quick_start.sh
获取最新版本失败，请稍候重试
root@ubuntu:~# 

### 相关日志输出

```shell
curl: (28) Failed to connect to resource.fit2cloud.com port 443: Connection timed out
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会针对境外服务器不能正常下载资源的问题做出优化。
