### ISSUE TITLE
[BUG] 设置失败，当前 firewallcmd 服务不可用，请检查后重试

### ISSUE THREAD

**Issue by dfmjndm** [1Panel-dev/1Panel#3601]
### 联系方式

fmj1161912098@gmail.com

### 1Panel 版本

1.9.3

### 问题描述

fail2ban切换防护策略，显示设置失败，当前 firewallcmd 服务不可用，请检查后重试
切换别的也是一样的情况
但是后台firewallcmd是服务运行状态。
![image](https://github.com/1Panel-dev/1Panel/assets/57401901/3d88ec96-00bf-42f0-9014-421f2ffddc12)

### 重现步骤

fail2ban切换防护策略

### 相关日志输出

```shell
centos8 stream平台
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by dfmjndm** [comment]
![Screenshot_2024-01-16-00-43-43-561_tech.lolli.toolbox.jpg](https://github.com/1Panel-dev/1Panel/assets/57401901/f827f438-c1bd-4fe6-b54a-34fa2760e4ad)

![Screenshot_2024-01-16-00-44-04-459_tech.lolli.toolbox.jpg](https://github.com/1Panel-dev/1Panel/assets/57401901/475832f8-df6d-459d-b795-499ff9f0611a)

![Screenshot_2024-01-16-00-42-31-175_com.android.chrome.png](https://github.com/1Panel-dev/1Panel/assets/57401901/f0524c2e-b2cb-42c8-a077-faf8bff75ead)

**Comment by ssongliu** [comment]
systemctl is-active firewalld 返回信息麻烦也贴一下

**Comment by dfmjndm** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/57401901/6c56dbef-88b5-49dc-bac2-d2ad4a6ec55f)

**Comment by dfmjndm** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/57401901/0dde9a77-0400-4fdb-bf5a-010d237d924c)

**Comment by ssongliu** [comment]
麻烦添加一下我好友，我远程看看这个问题
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/78316f2a-3d85-4ec8-819f-f40f70dc4b47)

**Comment by wanghe-fit2cloud** [comment]
先关闭该 Issue 了，后续如有问题再继续讨论。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
