### ISSUE TITLE
[BUG]手机端网页适配

### ISSUE THREAD

**Issue by Maklith** [1Panel-dev/1Panel#3603]
### 1Panel 版本

1.9.3

### 问题描述

手机网页登录1panel后进入首页后,左上角的菜单点击后无法显示任何选项,1.9.0之前没有这个问题

### 重现步骤

手机网页进入1panel

### 附加信息

浏览器 Edge

**Comment by wanghe-fit2cloud** [comment]
刚刚在安卓、苹果手机使用 Edge、Chrome 浏览器测试都没有未复现上述问题。
> 你更换浏览器或者清理缓存后再尝试一下，看问题是否还存在。

**Comment by Maklith** [comment]
> 刚刚在安卓、苹果手机使用 Edge、Chrome 浏览器测试都没有未复现上述问题。
> > 你更换浏览器或者清理缓存后再尝试一下，看问题是否还存在。

感谢，清理缓存后正常，应该是1.8的某些数据导致的异常
