### ISSUE TITLE
[BUG]yourls存在路径错误

### ISSUE THREAD

**Issue by dfmjndm** [1Panel-dev/1Panel#3604]
### 1Panel 版本

latest

### 问题描述

yourls开放公网安装之后，访问/admin路径
会被重定向到  localhost:port/admin
而不是0.0.0.0:port/admin
建议检查/opt/1panel/apps/yourls/yourls/data/includes/functions-http.php

### 重现步骤

wu

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1Panel 负责应用的安装，至于后期的使用及配置文件的修改，还需要用户手动来维护。
> 应用商店维护的应用会越来越多，现阶段暂无太多精力来适配上述工作，望理解。
