### ISSUE TITLE
docker安装方式都不支持，何以称之为现代？

### ISSUE THREAD

**Issue by baozitao** [1Panel-dev/1Panel#3605]
### 1Panel 版本

不知

### 请描述您的需求或者改进建议

docker安装方式

**Comment by maninhill** [comment]
1Panel 需要直接在root下运行并获得权限，才能实现完整全部的管理控制能力。

**Comment by baozitao** [comment]
也就是说，未来也不会有官方发布的基于docker的安装方式了？

**Comment by maninhill** [comment]
是的。
