### ISSUE TITLE
[BUG]面板设置 - 备份账号 - 服务器磁盘 - 点击编辑按钮无响应。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3607]
### 1Panel 版本

v1.9.3

### 问题描述

![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/e020e657-6340-4db7-bb8d-531f333cacd7)

### 重现步骤

面板设置 - 备份账号 - 服务器磁盘 - 点击编辑按钮

**Comment by wanghe-fit2cloud** [comment]
刚在本地已复现上述问题，会在近期修复并推送 v1.9.4 版本更新。

**Comment by wanghe-fit2cloud** [comment]
v1.9.4 版本已发布。
