### ISSUE TITLE
[FEATURE]计划任务日志目前只能保留300份，对于 1 秒或者 1 分钟执行一次的任务远远是不够的！

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3608]
### 1Panel 版本

v1.9.3

### 请描述您的需求或者改进建议

计划任务日志目前只能保留300份， 对于 1 秒或者 1 分钟执行一次的任务远远是不够的！

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述功能。

**Comment by wanghe-fit2cloud** [comment]
v1.9.4 版本已发布，取消了保留份数限制。
