### ISSUE TITLE
[BUG]SSH配置识别问题

### ISSUE THREAD

**Issue by Anyexyz** [1Panel-dev/1Panel#3609]
### 联系方式

1Panel交流群5

### 1Panel 版本

v1.9.3

### 问题描述

sshd_config文件中PermitRootLogin prohibit-password与PermitRootLogin without-password应该是同等效应，最新版本openssh-server中默认为prohibit-password，但是手动编写配置文件PermitRootLogin prohibit-password后1panel无法识别，XXX/hosts/ssh/ssh页显示为空，设置时显示如下
![1705246290517](https://github.com/1Panel-dev/1Panel/assets/53684988/57bfabfc-5cbe-4a98-8b35-ff1ca94babbb)

### 重现步骤

`sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin prohibit-password/g' /etc/ssh/sshd_config`

### 期待的正确结果

1panel应当可以正确识别出PermitRootLogin prohibit-password的功能并显示、配置

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by igophper** [comment]
without-password 在ssh的新老版本中都支持，prohibit-password则只在新版本中支持。为了兼容老版本就使用without-password代替prohibit-password

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
