### ISSUE TITLE
[QUESTION] 新应用 twikoo

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#3611]
### 请描述您的问题

这俩个版本有什么区别
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/e43884dc-dc73-45a4-aaa9-a0c1375a590a)

安装1.6.29，可升级页面让我升级它
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/8258b41a-9285-41eb-9426-77f1537ccb1d)

**Comment by wanghe-fit2cloud** [comment]
1.6.29 对应 amd64 和 arm64 架构
> 先手动忽略升级。
