### ISSUE TITLE
[BUG]应用一直显示安装中，无法停止

### ISSUE THREAD

**Issue by fitchibing** [1Panel-dev/1Panel#362]
### 1Panel 版本

v1.0.2

### 问题描述

问题：应用因为未知原因一直显示安装中，无法停止，不知道如何重新安装；

### 重现步骤

应用安装中即可复现

### 期待的正确结果

可以停止一直显示为”安装中“的应用

**Comment by zyyfit** [comment]
请问是不是网络不好导致镜像拉取缓慢或者是拉取失败呢？

**Comment by haining-zhn** [comment]
![image](https://user-images.githubusercontent.com/70742886/227093080-eab6dfb4-44aa-4f47-bce0-091f9323d5e3.png)
我的也是，一直安装中，大概1个小时，安装失败。

**Comment by fitchibing** [comment]
> 请问是不是网络不好导致镜像拉取缓慢或者是拉取失败呢？

应该是的，但是不知道这个拉去失败的日志去哪里查呢？
另外这里想反馈的是昨天群里咨询过的问题，给安装中的应用一个停止安装的选项，排除安装失败原因的是另外一个问题了~

**Comment by haining-zhn** [comment]
![image](https://user-images.githubusercontent.com/70742886/227413103-9d6e0a49-b6a9-4bfc-9576-f3a62055548e.png)

**Comment by wanghe-fit2cloud** [comment]
v1.1.0 版本已发布。
