### ISSUE TITLE
[BUG]OpenResty反向代理的文本替换不兼容 "  符号

### ISSUE THREAD

**Issue by d960124** [1Panel-dev/1Panel#3620]
### 1Panel 版本

v1.9.4

### 问题描述

OpenResty 创建反向代理添加文本替换时，如果文本中包含 `"` 保存会报错。
因为 OpenResty 中 `"` 符号是用来包裹参数的，如果参数中存在 `"` 符号就需要用 `\"` 方式转义。
那么在这种情况下面，我在 1Panel 界面中，主动的对 `"` 符号用 `\"` 转义的方式输入能正常保存。但是，问题来了，下一次再编辑的时候，1Panel 界面中的文本替换又变成了 `"` 没有之前的 `\` 转义符号了！
如下：
   `sub_filter "/static/css/style.css" "/static/css/style.css\"> <link rel=\"stylesheet\" href=\"/static/css/zxfzxf/style-sdw.css";`

### 重现步骤

时刻可以重现！

**Comment by d960124** [comment]
![1](https://github.com/1Panel-dev/1Panel/assets/48110764/9cf0ba75-098a-454f-b04c-c12afdbe0e18)
![2](https://github.com/1Panel-dev/1Panel/assets/48110764/7d91e239-1ce4-4222-b450-2769449454c8)
![3](https://github.com/1Panel-dev/1Panel/assets/48110764/c3c99a38-f3b5-4c61-a267-74e8eb4947a2)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在后续版本先调研一下具体优化方案。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
