### ISSUE TITLE
[BUG]工具箱 Fail2ban 没有自动屏蔽 ip

### ISSUE THREAD

**Issue by lchjczw** [1Panel-dev/1Panel#3623]
### 1Panel 版本

1.9.3

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/12480676/6594c69d-2db2-4408-a61e-c637774449c8)
我这是了自动屏蔽ip，但是破解的用的不是22端口，他尝试其他端口进行登录，虽然他不会成功但是他可以一直尝试，并不会被屏蔽

### 重现步骤

我这是了自动屏蔽ip，但是破解的用的不是22端口，他尝试其他端口进行登录，虽然他不会成功但是他可以一直尝试，并不会被屏蔽

**Comment by ssongliu** [comment]
感谢反馈，这里的端口不是 ssh 端口，是有开 fail2ban 自动屏蔽吗？可以贴一下 fail2ban 配置信息。

**Comment by lchjczw** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/12480676/3eec9787-b46b-4030-8cc4-0222d01ebd4d)

发现并没有并屏蔽

**Comment by ssongliu** [comment]
fail2ban 黑名单中有出现上面 172.232.56.7 这个 ip 吗？

**Comment by lchjczw** [comment]
是的

**Comment by ssongliu** [comment]
可以尝试切换为 iptables-allports 禁用方式，然后找个终端测试一下。

**Comment by lchjczw** [comment]
没有出现

**Comment by ssongliu** [comment]
> 没有出现

iptables-allports 禁用方式的时候没出现吗？还是 ufw 的时候？

**Comment by lchjczw** [comment]
iptables-allports这个方式没有，ufw之前就没有嘛

**Comment by ssongliu** [comment]
麻烦添加我好友，我远程看看
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/502ae27b-565c-4b48-b60d-f4b718644aee)

**Comment by lchjczw** [comment]
你图片没上传，我这加不了呢

**Comment by wanghe-fit2cloud** [comment]
> 你图片没上传，我这加不了呢

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/9ed64294-e4d6-4b8d-ab66-c10d090c5ad9)

**Comment by haukuen** [comment]
请问有成功解决吗，我也出现了这个问题 @lchjczw
