### ISSUE TITLE
[FEATURE]文件编辑器功能的建议

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3624]
### 1Panel 版本

v1.9.3

### 请描述您的需求或者改进建议

建议可以窗口最大化和左侧窗口选择目录文件进行多个编辑，例如宝塔的那样很方便实用。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
