### ISSUE TITLE
[BUG] Redis配置修改提示错误

### ISSUE THREAD

**Issue by muzidudu** [1Panel-dev/1Panel#3627]
### 1Panel 版本

v1.9.4

### 问题描述

配置修改后提示 `请求参数错误: Key: 'DBConfUpdateByFile.Database' Error:Field validation for 'Database' failed on the 'required' tag`

### 重现步骤

即使什么都不更改点击保存也是提示这个

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。

**Comment by jhq1911** [comment]
在应用商店 里面 已经安装的 redis 没办法通过参数修改密码，直接通过文件修改 .env里面的密码也不成功，会被重写成原来旧密码。

**Comment by wanghe-fit2cloud** [comment]
> 在应用商店 里面 已经安装的 redis 没办法通过参数修改密码，直接通过文件修改 .env里面的密码也不成功，会被重写成原来旧密码。

修改密码：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/8df3f60c-de78-45f2-8ba3-048f7ba2cb4a)

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
