### ISSUE TITLE
[FEATURE] 容器支持设置字段是否显示

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#3628]
### 1Panel 版本

最新

### 请描述您的需求或者改进建议

当前容器页面显示的字段过多， 在我的笔记本上显示不全，而且部分字段对我来说不是必须的，是否可以增加一个功能， 可以设置字段是否显示
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/670bf05e-ed1a-4e06-9d17-b6acbbe34c21)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
