### ISSUE TITLE
[FEATURE] 添加邮件提醒功能

### ISSUE THREAD

**Issue by vybfi** [1Panel-dev/1Panel#3630]
### 1Panel 版本

v1.9.4

### 请描述您的需求或者改进建议

希望能添加邮件提醒功能，毕竟作为一个linux面板，不能所有功能都由docker提供，还是应该原生提供一些管理功能。
像邮件的必要性就挺大的，我这两天遇到有人使用肉鸡准备暴力破解ssh密码，我部署了fail2ban，效果还行。但是后续还是遭遇了攻击，而我不能时时刻刻守着服务器后台。
所以这个时候我就像，有一个邮件通知是一个必要的事情。
希望能添加一个邮件提醒功能，最好能将各个功能的状态作为一个触发点自由组合。如果可以希望能让用户编写简易的脚本。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，通知、告警相关需求的讨论，统一汇总到该 issue #614
