### ISSUE TITLE
[FEATURE] 对原有docker项目和重复的应用提供合并操作

### ISSUE THREAD

**Issue by vybfi** [1Panel-dev/1Panel#3631]
### 1Panel 版本

v1.9.4

### 请描述您的需求或者改进建议

希望能将原有docker项目和应用里面同一个项目合并。
比如：
我在使用1panel之前部署了gitea，在部署1panel后我发现gitea有gitea应用。
那么是否可以将之前部署的gitea状态同步到应用商店的gitea应用上面。
毕竟两者都是基于docker的，让用户在同一台机器上面迁移一个同样由docker创建的服务显得很抽象。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，您可以参考 [本地应用制作教程](https://bbs.fit2cloud.com/t/topic/640)，将自己的应用发布为本地应用来维护。
如果是其他方式部署的容器服务，我们很难维护到应用商店的已安装应用列表中。主要是因为应用的启停、卸载、备份、恢复等操作做不到完全兼容，所以，如果非应用商店安装的应用还是推荐到容器列表中维护。
