### ISSUE TITLE
[FEATURE] 备份网站时，可配置排除规则

### ISSUE THREAD

**Issue by RealHeart** [1Panel-dev/1Panel#3633]
### 1Panel 版本

v1.9.4

### 请描述您的需求或者改进建议

当前`备份网站`类型的计划任务无法配置排除规则，仅在计划任务类型为`备份目录`时可配置规则

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by RealHeart** [comment]
这个什么时候可以优化，现在本地备份快要把服务器磁盘填满了

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
