### ISSUE TITLE
1.9.2 安装 MongoDB 报错！

### ISSUE THREAD

**Issue by demonyins** [1Panel-dev/1Panel#3635]
### 请描述您的问题

1.9.2 安装 MongoDB 报错！
ERROR: child process failed, exited with 51
To see additional information in this output, start without the "--fork" option.
stat: cannot statx '/proc/1/fd/1': Operation not permitted
warning: initdb logs cannot write to '/proc/1/fd/1', so they are in '/data/db/docker-initdb.log' instead
about to fork child process, waiting until server is ready for connections.

**Comment by wanghe-fit2cloud** [comment]
参考一下官方 issue:
https://github.com/docker-library/mongo/issues/465

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/3b38743e-e9c5-4421-b8fd-924c48720f4f)
