### ISSUE TITLE
[容器卸载后重新安装，不显示原来的备份]

### ISSUE THREAD

**Issue by zaqai** [1Panel-dev/1Panel#3636]
### 1Panel 版本

1.9.3

### 问题描述

容器卸载后重新安装，不显示原来的备份，但是进入备份文件夹，是可以看到新旧备份都在的
![image_83](https://github.com/1Panel-dev/1Panel/assets/56911539/b9da21b7-a2bb-4a45-b180-29728e219bd9)
![image_84](https://github.com/1Panel-dev/1Panel/assets/56911539/2dabb5fa-d932-4339-93dc-dfc12e50fbb3)

### 重现步骤

容器卸载后重新安装

**Comment by ssongliu** [comment]
感谢反馈，卸载应用的时候未选择删除备份文件，这里的文件就不会被删除。备份记录是存入数据库的，重新安装不会进行匹配，可以通过导入备份进行恢复。
