### ISSUE TITLE
应用商店里的 Synapse应用说明介绍里的创建管理员和普通用户的命令代码有缺失[BUG]

### ISSUE THREAD

**Issue by Mask-Vip** [1Panel-dev/1Panel#3639]
### 1Panel 版本

v1.9.4

### 问题描述

应用商店里的 Synapse应用说明介绍里的创建管理员和普通用户的命令代码有缺失.
为啥我知道呢,因为我就是一个面板战士,根本就不会用docker跟着教程安装,怎么也装不上.后来google了别人的教程才知道.

### 重现步骤

register_new_matrix_user  http://localhost:8008 -c /data/homeserver.yaml  -a -u 管理员用户名 -p 密码
这个是详情介绍里的命令.
docker exec -it synapse register_new_matrix_user http://localhost:8008 -c /data/homeserver.yaml -a
这个是google别人的命令
介绍里少了docker exec -it synapse这一部分.可把我这个面板战士难为了一晚上.

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1Panel 在容器页面提供了 `终端` 功能，就不需要手动执行 `docker exec -it` 命令了，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/adb1e1fe-555e-4f3b-851a-167e1cd628c1)

**Comment by Mask-Vip** [comment]
看了上面的回复应该是我理解错误了.我是在安装好项目后,去到工具里的终端操作的.而不是直接在项目后面的终端点进去的.差异应该就出现在这里了.应为上面配置文件的代码就是在工具里的终端中执行的,所以后面的创建账户的代码也就在自然而然的去到工具终端里了.要是能加个注明就好了.
