### ISSUE TITLE
[BUG] 容器资源使用率无法正确刷新显示

### ISSUE THREAD

**Issue by suiyueou** [1Panel-dev/1Panel#3640]
### 1Panel 版本

v1.9.4

### 问题描述

> 开启了 5s/次 刷新
> 与主机执行的 docker stats 结果对比
> 测试机子：Debian 12、Ubuntu 20.04

问题：

容器的 `资源使用率/监控` 似乎只有 cpu 使用率会一直随之 5s/次 刷新，内存使用率多次实测观察后发现只有在容器 `启动/重启` 时会刷新一下，后续数值就好像固定住了一样一动不动。

除 cpu 和内存外的其他数值似乎情况跟内存使用率一样，无法正确刷新显示，最直观的就是监控页显示为长长的一条直线。

此问题实测 [1panel demo](https://demo.1panel.cn/) 上也一样。

最后就是这台 Debian 12 机子上的容器核心数和缓存使用显示为零，面板概览页是有正常显示 cpu 核心相关信息的，但是这个问题我在 Ubuntu 20.04 机子和 1panel demo 上都无法复现，因为其似乎都有显示数值，不为零。

截图：

> 来源于测试机子：Debian 12

- 重启前：
![Screenshot_2024-01-18-08-24-24-593](https://github.com/1Panel-dev/1Panel/assets/48700331/558fa729-3b28-40a0-8d4e-cd6a2e69dd2a)

- 重启后：
![Screenshot_2024-01-18-08-26-34-769](https://github.com/1Panel-dev/1Panel/assets/48700331/aba55dec-f550-4308-896b-09bc665473f5)

- 监控页：
![Screenshot_2024-01-18-08-29-52-048](https://github.com/1Panel-dev/1Panel/assets/48700331/75775303-a0f0-431a-b9ed-b0c2656d1271)

### 重现步骤

重现步骤：

- 左侧菜单栏容器 => 容器 => 资源使用率
- 左侧菜单栏容器 => 容器 => 更多 => 监控

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by ssongliu** [comment]
1. 这里内存是正常刷新的，只是没操作的时候波动比较小，可以试试打开该应用然后做一些操作进行对比
<img width="627" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/73214554/02e44aa8-1e44-4a0e-91da-9b1ba1159f34">

2. 核心数是那台机器上所有容器的核心数都为 0 吗？

**Comment by suiyueou** [comment]
1. 我刚刚又认真观察了一下, 确实会刷新, 不知道为什么我昨天看不到刷新.
2. 是的, 那一台 Debian 12 机子上, 所有容器的核心树和缓存使用都显示为 0, 删除重建和重启, 面板/系统重启都试过.
3. 还是那台 Debian 12 机子, 上面的容器内存使用率跟主机 docker stats 的结果的对不上, 我昨天就是因为感觉面板上显示的容器内存使用跟概览页的主机内存使用率对不上才使用 docker stats 进行查看, 然后才发现看不到刷新, 今天是可以看到刷新了,但是数值还是对不上

截图:

- 面板: 
![image](https://github.com/1Panel-dev/1Panel/assets/48700331/529f29aa-4da7-41e4-ae1b-aac5f5e7c42c)

- 主机: 
![image](https://github.com/1Panel-dev/1Panel/assets/48700331/f305500c-9752-4423-81be-7f634873beea)

截图依旧来自上面的 Debian 12 上的 Gitea 容器, 昨天上面那个容器刚刚重启后是 149.77MiB, 今天已经 5.32GiB (昨天应该就是因为这个数值过大, 波动小, 所以我判断成了不会刷新), 但是主机上显示也就 1.705GiB.

整个机子的内存使用也就不到 1.9 GiB: 
![image](https://github.com/1Panel-dev/1Panel/assets/48700331/bb04dd49-e9d9-4b4a-9288-cf728a26c094)

**Comment by ssongliu** [comment]
> 1. 我刚刚又认真观察了一下, 确实会刷新, 不知道为什么我昨天看不到刷新.
> 2. 是的, 那一台 Debian 12 机子上, 所有容器的核心树和缓存使用都显示为 0, 删除重建和重启, 面板/系统重启都试过.
> 3. 还是那台 Debian 12 机子, 上面的容器内存使用率跟主机 docker stats 的结果的对不上, 我昨天就是因为感觉面板上显示的容器内存使用跟概览页的主机内存使用率对不上才使用 docker stats 进行查看, 然后才发现看不到刷新, 今天是可以看到刷新了,但是数值还是对不上
> 
> 截图:
> 
> * 面板:
>   ![image](https://private-user-images.githubusercontent.com/48700331/297950599-529f29aa-4da7-41e4-ae1b-aac5f5e7c42c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDQwODMsIm5iZiI6MTcwNTY0Mzc4MywicGF0aCI6Ii80ODcwMDMzMS8yOTc5NTA1OTktNTI5ZjI5YWEtNGRhNy00MWU0LWFlMWItYWFjNWY1ZTdjNDJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA1NTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1OWU0NDM3NzAzNGQ0ODU5NmE0MGE3NWI5NGNkMjk0MTRmNWRiYTBhZWVjMjhkMmY5MmQ2MTM0YWFiNWQ3MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.px295lPJ_Frm5FLNdj8DK-W6Jkkbg5kUYlEZCnDW_v0)
> * 主机:
>   ![image](https://private-user-images.githubusercontent.com/48700331/297950669-f305500c-9752-4423-81be-7f634873beea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDQwODMsIm5iZiI6MTcwNTY0Mzc4MywicGF0aCI6Ii80ODcwMDMzMS8yOTc5NTA2NjktZjMwNTUwMGMtOTc1Mi00NDIzLTgxYmUtN2Y2MzQ4NzNiZWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA1NTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNjljMTVhMjJmOWNhNDEwOTU0Y2VmZWRmNjFmNGM1YzlhMmFkNTNhMTJmOWYyYjkwNDdmZDRiNTc3ZWQ3YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-h0Ix87HsmLB2LQy0c6C05J1dV8m8LT7j8nBn3GLHKg)
> 
> 截图依旧来自上面的 Debian 12 上的 Gitea 容器, 昨天上面那个容器刚刚重启后是 149.77MiB, 今天已经 5.32GiB (昨天应该就是因为这个数值过大, 波动小, 所以我判断成了不会刷新), 但是主机上显示也就 1.705GiB.
> 
> 整个机子的内存使用也就不到 1.9 GiB: ![image](https://private-user-images.githubusercontent.com/48700331/297951510-bb04dd49-e9d9-4b4a-9288-cf728a26c094.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDQwODMsIm5iZiI6MTcwNTY0Mzc4MywicGF0aCI6Ii80ODcwMDMzMS8yOTc5NTE1MTAtYmIwNGRkNDktZTlkOS00YjRhLTkyODgtY2Y3MjhhMjZjMDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA1NTYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNGI5ZjcyZTVhNDAzMDhlMjUxNzYzZmRmYjM5NjRhMWZhZDI5ZTA4NjBhYmI5OTQ4OWZmZjVmNzdiNmQ2ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xtJCdYluiCVTWhF_TGfG-Og32SPhzlQQSVay8t-jU74)

容器列表有设置定时刷新吗？默认情况下列表是不刷新的，那个 5.32 GiB 手动刷新界面之后还那么大吗

**Comment by suiyueou** [comment]
> 容器列表有设置定时刷新吗？默认情况下列表是不刷新的

有的, 一直是 5s 每次.

> 那个 5.32 GiB 手动刷新界面之后还那么大吗

是的, 重新加载页面 (Ctrl + F5) 后也是这么大, 它每次 5s 定时刷新也是在这么大的基础上刷新, 截至回复前是: 面板显示 5.63GiB, 主机 docker stats 显示 2.02GiB, 两者之间数据一直相差大概 3.6GiB.

**Comment by ssongliu** [comment]
> > 容器列表有设置定时刷新吗？默认情况下列表是不刷新的
> 
> 有的, 一直是 5s 每次.
> 
> > 那个 5.32 GiB 手动刷新界面之后还那么大吗
> 
> 是的, 重新加载页面 (Ctrl + F5) 后也是这么大, 它每次 5s 定时刷新也是在这么大的基础上刷新, 截至回复前是: 面板显示 5.63GiB, 主机 docker stats 显示 2.02GiB, 两者之间数据一直相差大概 3.6GiB.

这就奇怪了，有起其他的容器吗，其他容器的状态正常吗？

**Comment by suiyueou** [comment]
> 这就奇怪了，有起其他的容器吗，其他容器的状态正常吗？

有的, 其他容器看起来倒是没什么问题.

- 面板: 
![image](https://github.com/1Panel-dev/1Panel/assets/48700331/6874cdd3-9fb5-4880-b93a-66cea1236d39)

- 主机: 
![image](https://github.com/1Panel-dev/1Panel/assets/48700331/29bf97dd-acc0-472e-a75b-07fce5265938)

**Comment by wanghe-fit2cloud** [comment]
无法复现上述问题，先暂时关闭该 issue 了。
