### ISSUE TITLE
[FEATURE] Decouple the update of 1panel and applications in the app store

### ISSUE THREAD

**Issue by woodwm** [1Panel-dev/1Panel#3642]
### 1Panel 版本

1.9.4

### 请描述您的需求或者改进建议

I am not sure why the update of application need to be in the process of update 1panel. Could you add a function to automatically fetch the latest version from the [appstore repositry](https://github.com/1Panel-dev/appstore)?

**Comment by wanghe-fit2cloud** [comment]
The 1Panel service will automatically update the application list upon restart. 
The application store list has a sync button, as shown in the picture:
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/e10d5578-716c-4e66-bb0c-856d3924bcac)
