### ISSUE TITLE
[BUG] 切换默认站点保错

### ISSUE THREAD

**Issue by lidonglonge** [1Panel-dev/1Panel#3644]
### 联系方式

lidonglonge@163.com

### 1Panel 版本

V1.9.4

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/48340309/91aa9aa3-dcef-4168-bbbf-22a75457ae8b)

[31m2024/01/18 16:48:43 [Recovery] 2024/01/18 - 16:48:43 panic recovered:
POST /api/v1/websites/default/server HTTP/1.1
Host: 192.168.1.13:29767
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: zh
Connection: keep-alive
Content-Length: 8
Content-Type: application/json
Cookie: rememberMe=true; username=admin; password=kYUPhjNfjrbQDaNV28hecFx3L/dXWnykbkWWJCnLkeJZ9NbU+5wi3Xax60gFSlIWJxPzoa4Tdpvr7/UfvjciRg==; psession=ff8bfa41-e4ac-4f8a-8d39-1b06374e0097
Origin: http://192.168.1.13:29767
Referer: http://192.168.1.13:29767/websites
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0

runtime error: index out of range [0] with length 0
runtime/panic.go:113 (0x436dbe)
github.com/1Panel-dev/1Panel/backend/app/service/website.go:1041 (0x1ec86e4)
github.com/1Panel-dev/1Panel/backend/app/api/v1/website.go:428 (0x21c8105)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x21832e2)
github.com/1Panel-dev/1Panel/backend/middleware/password_expired.go:24 (0x2183016)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x2182e17)
github.com/1Panel-dev/1Panel/backend/middleware/session.go:36 (0x2182d8e)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x218524d)
github.com/1Panel-dev/1Panel/backend/middleware/jwt.go:15 (0x218513e)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x2185093)
github.com/1Panel-dev/1Panel/backend/middleware/loading.go:22 (0x2185016)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x2185bed)
github.com/1Panel-dev/1Panel/backend/middleware/bind_domain.go:22 (0x2185a47)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x2185642)
github.com/1Panel-dev/1Panel/backend/middleware/ip_limit.go:25 (0x21853c7)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x21842f4)
github.com/1Panel-dev/1Panel/backend/middleware/operation.go:131 (0x21842d1)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x99eda1)
github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x99ed8c)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x99dec6)
github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x99dea9)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x99cf2a)
github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x99cbb1)
github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x99c6dc)
net/http/server.go:2936 (0x7869d5)
net/http/server.go:1995 (0x781ef1)
runtime/asm_amd64.s:1598 (0x470180)
[0m

### 重现步骤

切换默认站点

**Comment by zhengkunwang223** [comment]
感谢反馈，你有手动修改过网站或者 nginx 的配置文件吗？
> 我们在本地环境未复现上述问题。

**Comment by lidonglonge** [comment]
设置性能配置；
这是现在的配置信息：



user root; 

worker_processes auto; 

error_log /var/log/nginx/error.log notice; 

error_log /dev/stdout notice; 

pid /var/run/nginx.pid; 

events {

    worker_connections 1024; 

}

http {

    include mime.types; 

    default_type application/octet-stream; 

    log_format main '$remote_addr - $remote_user [$time_local] "$request" ' '$status $body_bytes_sent "$http_referer" ' '"$http_user_agent" "$http_x_forwarded_for"'; 

    server_tokens off; 

    access_log /var/log/nginx/access.log main; 

    access_log /dev/stdout main; 

    sendfile on; 

    server_names_hash_bucket_size 512; 

    client_header_buffer_size 32k; 

    client_max_body_size 256m; 

    keepalive_timeout 60; 

    keepalive_requests 100000; 

    gzip on; 

    gzip_min_length 1k; 

    gzip_buffers 4 16k; 

    gzip_http_version 1.1; 

    gzip_comp_level 2; 

    gzip_types text/plain application/javascript application/x-javascript text/javascript text/css application/xml; 

    gzip_vary on; 

    gzip_proxied expired no-cache no-store private auth; 

    gzip_disable "MSIE [1-6]\."; 

    lua_code_cache on; 

    lua_shared_dict limit 10m; 

    lua_package_path "/www/common/waf/?.lua;/usr/local/openresty/lualib/?.lua;"; 

    init_by_lua_file /www/common/waf/init.lua; 

    limit_conn_zone $binary_remote_addr zone=perip:10m; 

    limit_conn_zone $server_name zone=perserver:10m; 

    include /usr/local/openresty/nginx/conf/conf.d/*.conf; 

    proxy_temp_path /www/common/proxy/proxy_temp_dir; 

    proxy_cache_path /www/common/proxy/proxy_cache_dir levels=1:2 keys_zone=proxy_cache_panel:20m inactive=1d max_size=5g; 

    client_body_buffer_size 512k; 

    proxy_connect_timeout 60; 

    proxy_read_timeout 60; 

    proxy_send_timeout 60; 

    proxy_buffer_size 32k; 

    proxy_buffers 4 64k; 

    proxy_busy_buffers_size 128k; 

    proxy_temp_file_write_size 128k; 

    proxy_next_upstream error timeout invalid_header http_500 http_503 http_404; 

    proxy_cache proxy_cache_panel; 

}










在 2024-01-18 17:04:52，"zhengkunwang" ***@***.***> 写道：

感谢反馈 我们先在本地复现一下
你手动改过网站或者 nginx 的配置文件吗

**Comment by zhengkunwang223** [comment]
> 设置性能配置； 这是现在的配置信息： user root; worker_processes auto; error_log /var/log/nginx/error.log notice; error_log /dev/stdout notice; pid /var/run/nginx.pid; events { worker_connections 1024; } http { include mime.types; default_type application/octet-stream; log_format main '$remote_addr - $remote_user [$time_local] "$request" ' '$status $body_bytes_sent "$http_referer" ' '"$http_user_agent" "$http_x_forwarded_for"'; server_tokens off; access_log /var/log/nginx/access.log main; access_log /dev/stdout main; sendfile on; server_names_hash_bucket_size 512; client_header_buffer_size 32k; client_max_body_size 256m; keepalive_timeout 60; keepalive_requests 100000; gzip on; gzip_min_length 1k; gzip_buffers 4 16k; gzip_http_version 1.1; gzip_comp_level 2; gzip_types text/plain application/javascript application/x-javascript text/javascript text/css application/xml; gzip_vary on; gzip_proxied expired no-cache no-store private auth; gzip_disable "MSIE [1-6]\."; lua_code_cache on; lua_shared_dict limit 10m; lua_package_path "/www/common/waf/?.lua;/usr/local/openresty/lualib/?.lua;"; init_by_lua_file /www/common/waf/init.lua; limit_conn_zone $binary_remote_addr zone=perip:10m; limit_conn_zone $server_name zone=perserver:10m; include /usr/local/openresty/nginx/conf/conf.d/*.conf; proxy_temp_path /www/common/proxy/proxy_temp_dir; proxy_cache_path /www/common/proxy/proxy_cache_dir levels=1:2 keys_zone=proxy_cache_panel:20m inactive=1d max_size=5g; client_body_buffer_size 512k; proxy_connect_timeout 60; proxy_read_timeout 60; proxy_send_timeout 60; proxy_buffer_size 32k; proxy_buffers 4 64k; proxy_busy_buffers_size 128k; proxy_temp_file_write_size 128k; proxy_next_upstream error timeout invalid_header http_500 http_503 http_404; proxy_cache proxy_cache_panel; } 在 2024-01-18 17:04:52，"zhengkunwang" ***@***.***> 写道： 感谢反馈 我们先在本地复现一下 你手动改过网站或者 nginx 的配置文件吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

这个配置也没问题 你加一下我的微信吧 我远程看一下 
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/179e44a3-04fe-47c4-aa26-37365e772409)

**Comment by zhengkunwang223** [comment]
经过远程 是因为手动修改了配置文件 并且删除了 Listen 字段导致 default_server 无法设置
