### ISSUE TITLE
[FEATURE]建议容器内的IP地址是可以固定的

### ISSUE THREAD

**Issue by lcese** [1Panel-dev/1Panel#3649]
### 1Panel 版本

1.94

### 请描述您的需求或者改进建议

昨天将数据库全部切换成了PGSQL，今天重启发现站点全部无法打开。后经排查是因为系统进行重启，容器内PGSQL的IP地址已经变动，导致网站站点无法打开。建议容器内的IP地址是可以固定的。

**Comment by wanghe-fit2cloud** [comment]
相同容器网络的容器间访问，使用容器连接地址，如图：
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/74837046-a687-4f45-9b3b-494b13b00499">

> 如果必须要使用容器 IP，可以在创建应用时编辑 compose 文件并手动指定。
