### ISSUE TITLE
[BUG]这里是文案写错了吗

### ISSUE THREAD

**Issue by rxxcy** [1Panel-dev/1Panel#365]
### 1Panel 版本

演示站 v1.0.2

### 问题描述

![YWIHF.png](https://i.328888.xyz/2023/03/22/YWIHF.png)

### 重现步骤

-

### 期待的正确结果

延迟？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，该问题在本周要发布的v1.0.3版本修复。
