### ISSUE TITLE
[BUG]特定场景下文件夹压缩失败问题

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#3650]
### 1Panel 版本

v1.9.4

### 问题描述

centos7.9环境

压缩`gitlab-ce`容器挂载文件夹出现错误，不论压缩`zip`格式还是`tar.gz`格式，都会压缩失败。

压缩前`gitlab-ce`容器已经关闭

压缩其他文件夹不存在该问题。而且经过测试：
* 复制其他文件夹，修改文件夹为`gitlab-x.x.x`进行压缩，没有问题
* 复制`gitlab-ce`容器挂载文件夹出，重命名`gitlab`执行压缩，依旧错误
* 文件夹权限全部为`0755`，压缩其他文件夹正常，仅压缩`gitlab-ce`容器挂载文件夹错误

### 重现步骤

错误复现：

![1](https://github.com/1Panel-dev/1Panel/assets/63288007/7f30551e-25d0-44e1-9fa4-6eb121521169)

错误日志：
![2](https://github.com/1Panel-dev/1Panel/assets/63288007/78b81e6f-75e0-4b8a-b826-5293cc95962e)

测试复制文件夹后改名执行压缩：（依旧失败）
![2](https://github.com/1Panel-dev/1Panel/assets/63288007/b36910c2-b133-4e41-8f84-b03e19227576)
![3](https://github.com/1Panel-dev/1Panel/assets/63288007/6d10e14f-2c13-46a2-a3e1-025c4aec7335)

测试复制其他文件夹改相同类型文件夹名执行压缩：（成功）
![3](https://github.com/1Panel-dev/1Panel/assets/63288007/a37335b1-93b4-45c3-a5b4-ff0396b46a15)
![4](https://github.com/1Panel-dev/1Panel/assets/63288007/4002469b-35a9-467a-80ab-a74674eac146)

**Comment by wanghe-fit2cloud** [comment]
上述问题即便是使用 `tar` 或者 `zip` 命令手动压缩目录也会出现同样的问题，是因为该卷很有可能被其他容器使用。
> 与文件夹名称没有关系。

**Comment by JAINKRE** [comment]
压缩和容器本身与其他容器无关，经过测试，即使停止docker服务后压缩，还是存在上述问题。

但是使用系统自带的`tar -zcvf `命令执行`tar.gz`压缩却正常，而且docker容器开启并且`gitlab-ce`容器也开启，压缩正常。

**Comment by wanghe-fit2cloud** [comment]
> 压缩和容器本身与其他容器无关，经过测试，即使停止docker服务后压缩，还是存在上述问题。
> 
> 但是使用系统自带的`tar -zcvf `命令执行`tar.gz`压缩却正常，而且docker容器开启并且`gitlab-ce`容器也开启，压缩正常。

那提供一下压缩失败的具体错误日志。
> 不是操作日志。

**Comment by JAINKRE** [comment]
错误日志从哪里获取？
我只找到了以下提示：

```
服务内部错误: error : exit status 127, output: bash: zip: command not found

服务内部错误: file gitlab-16.7.3/data/gitlab_home/gitlab-rails/sockets/gitlab.socket: creating header: archive/tar: sockets not supported

服务内部错误: file gitlab-16.7.3/data/gitlab_home/gitlab-rails/sockets/gitlab.socket: creating header: archive/tar: sockets not supported
```

如下：
![20240119-121839](https://github.com/1Panel-dev/1Panel/assets/63288007/15243980-e475-490b-b1e8-fb8da670ee87)

第一个问题提示没有安装zip，执行`yum install zip`后尝试压缩`zip`还是不成功，并且在面板日志中错误信息：
```
服务内部错误: error : exit status 18, output: zip warning: No such device or address zip warning: No such device or address zip warning: No such device or address zip warning: No such device or address zip warning: No such device or address zip warning: No such device or address
```

第二三个错误看上去是docker问题，查到了一个相关参考：
https://stackoverflow.com/questions/56215440/docker-build-error-archive-tar-sockets-not-supported

但这个参考好像属于容器build错误的，按道理来说只是执行tar.gz压缩文件夹，应该和这个无关，毕竟使用Linux原生压缩命令可以成功，只是1panel自带的压缩命令失败。

**Comment by JAINKRE** [comment]
以下是使用Linux自带压缩命令录屏，可以看到可以正常压缩

![00](https://github.com/1Panel-dev/1Panel/assets/63288007/d3441f60-e6eb-4bc7-8cec-d8e88997788a)

**Comment by wanghe-fit2cloud** [comment]
提供一下 gitlab 的容器安装命令，本地环境复现一下。

**Comment by JAINKRE** [comment]
```cmd

docker pull gitlab/gitlab-ce:16.7.3-ce.0

docker run -d  \
        -p 80:80 \
        --name gitlab --restart always \
        -v /data_pcie3_nvme1/data/docker_data/gitlab-16.7.3/data/gitlab_conf:/etc/gitlab \
        -v /data_pcie3_nvme1/data/docker_data/gitlab-16.7.3/data/gitlab_logs:/var/log/gitlab \
        -v /data_pcie3_nvme1/data/docker_data/gitlab-16.7.3/data/gitlab_home:/var/opt/gitlab \
        gitlab/gitlab-ce:16.7.3-ce.0
```

**Comment by wanghe-fit2cloud** [comment]
<img width="1297" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/331ec49f-2e49-4c20-a7ba-57be8fdfe042">

**Comment by wanghe-fit2cloud** [comment]
> ```batchfile
> docker pull gitlab/gitlab-ce:16.7.3-ce.0
> 
> docker run -d  \
>         -p 80:80 \
>         --name gitlab --restart always \
>         -v /data_pcie3_nvme1/data/docker_data/gitlab-16.7.3/data/gitlab_conf:/etc/gitlab \
>         -v /data_pcie3_nvme1/data/docker_data/gitlab-16.7.3/data/gitlab_logs:/var/log/gitlab \
>         -v /data_pcie3_nvme1/data/docker_data/gitlab-16.7.3/data/gitlab_home:/var/opt/gitlab \
>         gitlab/gitlab-ce:16.7.3-ce.0
> ```

刚刚在本地环境通过 `zip -r gitlab.zip gitlab-16.7.3/` 命令来压缩上述文件夹，输出了同样的错误，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/82b971c4-968a-4387-ae4d-a72bc93bd778)

**Comment by JAINKRE** [comment]
我没有尝试过使用linux命令压缩`zip`格式，但是我测试使用`tar -zcvf`压缩`tar.gz`格式可以成功。难道这个是gitlab的问题吗？之前我们使用宝塔面板，使用他们面板带的压缩功能包括上述两种压缩格式都没遇到过这种问题（不论gitlab容器开启或关闭），也正因此，我们之前都是先关闭容器在通过这种方法备份gitlab数据的。

目前，在1panel里面我们通过shell命令实现了gitlab官方自带的数据备份方法，从而规避了当前`tar.gz`压缩失败的问题。但还是期望能找出这个奇怪问题的真正原因。

**Comment by JAINKRE** [comment]
> 我没有尝试过使用linux命令压缩`zip`格式，但是我测试使用`tar -zcvf`压缩`tar.gz`格式可以成功。难道这个是gitlab的问题吗？之前我们使用宝塔面板，使用他们面板带的压缩功能包括上述两种压缩格式都没遇到过这种问题（不论gitlab容器开启或关闭），也正因此，我们之前都是先关闭容器在通过这种方法备份gitlab数据的。
> 
> 目前，在1panel里面我们通过shell命令实现了gitlab官方自带的数据备份方法，从而规避了当前`tar.gz`压缩失败的问题。但还是期望能找出这个奇怪问题的真正原因。

明天我测试一下Linux的zip压缩，如果实在找不到原因就算了，好在目前通过编写的shell脚本解决了数据备份的需求，面板能不能正常压缩gitlab不是很重要了，这个bug最奇怪的就是仅仅gitlab文件夹不行，可能是某些文件权限导致的吧。

**Comment by wanghe-fit2cloud** [comment]
好的，暂时先关闭该 Issue 了，后续可以继续讨论上述问题。
