### ISSUE TITLE
备份加密 [FEATURE]

### ISSUE THREAD

**Issue by sinoserendipity** [1Panel-dev/1Panel#3651]
### 1Panel 版本

1.9.4

### 请描述您的需求或者改进建议

通过 1Panel 计划任务备份到各个云平台，缺少加密功能，特别是备份类似 Bitwarden 的数据时候， 没有加密备份，显然有点不安全，看见有人在1.8.0版本的时候提出过这问题，到现在没有解决，希望能尽快增加这功能，期待！！

**Comment by wanghe-fit2cloud** [comment]
备份文件加密相关需求，统一汇总到该 issue #2855
