### ISSUE TITLE
[FEATURE] 上传文件页面优化建议

### ISSUE THREAD

**Issue by DongShaoNB** [1Panel-dev/1Panel#3653]
### 1Panel 版本

1.9.4

### 请描述您的需求或者改进建议

上传文件的页面里的file-item字号建议加大至14，鼠标停留时的颜色建议为灰色或其他，白色有点奇怪

### 请描述你建议的实现方案

上传文件的页面里的file-item字号建议加大至14，鼠标停留时的颜色建议为灰色或其他，白色有点奇怪

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/54093566/a6057e4d-8618-4ca9-a18a-1b4978197995)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本优化显示问题。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
