### ISSUE TITLE
[FEATURE]首次安装OpenResty端口设置了81,后续如何改回80端口呢

### ISSUE THREAD

**Issue by muzidudu** [1Panel-dev/1Panel#3654]
### 1Panel 版本

v1.9.4

### 请描述您的需求或者改进建议

希望后续可以通过参数改回80端口,mysql、redis端口首次设置过以后好像都无法改变了

**Comment by wanghe-fit2cloud** [comment]
OpenResty 的端口涉及到网站等资源，如果修改可能会造成一些不可逆的情况，目前只能是手动删除网站后重新安装。
MySQL、MariaDB、PostgreSQL 和 Redis 可以进入数据库页面，点击顶部状态栏进入设置页面修改端口。
> 2.0 大版本重构时会考虑自定义端口的情况。
