### ISSUE TITLE
[BUG] 文件管理器删除文件名带有 "(", ")" 符号时报错

### ISSUE THREAD

**Issue by DongShaoNB** [1Panel-dev/1Panel#3657]
### 1Panel 版本

1.9.4

### 问题描述

文件管理器删除文件名带有 "(", ")" 符号时报错

### 重现步骤

删除文件名带有 "(", ")" 符号的文件

### 相关日志输出

```shell
服务内部错误: error : exit status 2, output: bash: -c:行1: 未预期的符号“(”附近有语法错误 bash: -c:行1: `mv /opt/mcserver/地图(空中).zip /.1panel_clash/_1p_file_1p_opt_1p_mcserver_1p_地图(空中).zip_p_37639996_1705659439'
```

**Comment by wanghe-fit2cloud** [comment]
麻烦提供一下文件全名（放置在反引号 `` 内）
> 例：`test"(", ")" `

**Comment by DongShaoNB** [comment]
> 麻烦提供一下文件全名（放置在反引号 `` 内）
> 
> > 例：`test"(", ")" `

`主城地图(空中).zip`

**Comment by igophper** [comment]
这个地方的问题有点严重呀，存在命令注入的风险

**Comment by igophper** [comment]
> 这个地方的问题有点严重呀，存在命令注入的风险

暂时只修复了这个问题，其他地方执行命令的时候都要进行处理。否则可能存在命令注入风险

**Comment by wanghe-fit2cloud** [comment]
> > 这个地方的问题有点严重呀，存在命令注入的风险
> 
> 暂时只修复了这个问题，其他地方执行命令的时候都要进行处理。否则可能存在命令注入风险

感谢支持。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
