### ISSUE TITLE
[BUG] PostgreSQL 添加远程数据库页面增加超级用户等提示信息。

### ISSUE THREAD

**Issue by handy-sun** [1Panel-dev/1Panel#3659]
### 联系方式

cheersoon@outlook.com

### 1Panel 版本

1.9.4

### 问题描述

postgres -> 添加远程数据库中比如我要添加一个 名为giteadb, 用户为gitea的数据库。但测试连接失败，看postgresql的日志是
```
FATAL:  no pg_hba.conf entry for host "192.168.100.113", user "gitea", database "gitea", no encryption
```
1panel好像把用户名当成了数据库名进行连接
(使用的环境可以通过其他数据库gui程序进行远程连接，已确保配置无误)
![image](https://github.com/1Panel-dev/1Panel/assets/44354723/7488529e-b14c-4d3d-bd89-e0570bcebd34)

### 重现步骤

postgres -> 添加远程数据库 添加一个数据库名和用户不同的数据库

### 期待的正确结果

可以连接成功

### 附加信息

> postgres --version                                                                                                                                   INT 5m 34s qi@mandevsrv 
postgres (PostgreSQL) 16.1

**Comment by wanghe-fit2cloud** [comment]
根据错误信息提示，应该是 1Panel 访问目标数据库服务的权限问题。
你可以先尝试编辑 `pg_hba.conf` 文件，具体操作可以先自行查看 PostgreSQL 官方文档的说明。

也可以参考下面这篇文章：
https://dba.stackexchange.com/questions/83984/connect-to-postgresql-server-fatal-no-pg-hba-conf-entry-for-host

**Comment by handy-sun** [comment]
我在局域网内的windows电脑是可以成功通过密码连接这个linux设备上的数据库的
若更改为所有地址的权限，但仍然失败
```
FATAL:  database "gitea" does not exist
```
注意我的数据库名称是 **`giteadb`** , 网页上的第一栏名称也是这么填的。我觉得问题在这里，数据库名称不对

**Comment by wanghe-fit2cloud** [comment]
名称是作为要添加的 PostgreSQL 远程数据库的标识，不是具体数据库。
> 添加远程数据库服务成功后，可以在数据库页面同步数据来管理具体数据库。

下面要填写的用户名和密码必须是 PostgreSQL 服务的超级用户。

**Comment by handy-sun** [comment]
好的，这样说我就明白了。 
感谢您的解答，如果界面这里加个提示就好了

**Comment by wanghe-fit2cloud** [comment]
> 好的，这样说我就明白了。 感谢您的解答，如果界面这里加个提示就好了

v1.9.5 版本增加超级用户等提示信息。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
