### ISSUE TITLE
[BUG] 在已登录状态下，访问 `安全入口` 仍需重新登录

### ISSUE THREAD

**Issue by RealHeart** [1Panel-dev/1Panel#3661]
### 1Panel 版本

v1.9.4

### 问题描述

在已登录状态下 (Token 未过期) 再次访问 `安全入口` 时，仍需重新登录

### 重现步骤

登录面板
访问安全入口

### 期待的正确结果

直接跳转首页

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
刚在本地环境已复现上述问题，我们会在近期修复并推送更新。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
