### ISSUE TITLE
[BUG]计划任务脚本输入框前端错误

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#3662]
### 1Panel 版本

1.9.4

### 问题描述

* 输入框组件初始状态下下拉高度无效
*  当输入框被触发时可以改变大小，可一旦输入回车，输入框又变回去了

### 重现步骤

错误演示：
![20240120-135759](https://github.com/1Panel-dev/1Panel/assets/63288007/c4f6536d-71e4-4e76-8972-196a37d17fda)

### 期待的正确结果

* 建议输入框手动改变高度时保持高度不变

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by ssongliu** [comment]
使用的是什么浏览器？

**Comment by JAINKRE** [comment]
> 使用的是什么浏览器？

chrome 120.0.6099.225

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
