### ISSUE TITLE
[FEATURE]增加容器固定ip功能。

### ISSUE THREAD

**Issue by BrkOne** [1Panel-dev/1Panel#3663]
### 1Panel 版本

v1.9.4

### 请描述您的需求或者改进建议

需求增加容器固定ip功能，以下两个使用场景。
1、系统重启，容器内的IP地址会变动，不灵活而且不方便。（暂时解决方法：可以用容器名连接。或者端口映射到宿主机，本机ip连接，但是nginx反代有时候会报错502。）
2、目标：实现容器和宿主机同一个ip段。操作：1panel》容器》网络》创建网络，创建了一条macvlan配置。但是在创建容器的时候，选择了刚刚创建的网络，无法自定义ip，导致自动分配的ip很容易和外界ip产生冲突（暂时无解，修改容器的配置文件，重启docker容器会被覆盖）

### 请描述你建议的实现方案

1、建议创建容器时，增加自定义ip功能。
2、或者建议创建容器时，使用者可追加docker启动参数（可自行追加参数：--ip=192.xxx.xxx.xxx）

### 附加信息

参考：[cnblogs.com/Yogile/p/12944741.html](https://www.cnblogs.com/Yogile/p/12944741.html)

**Comment by xiexiaosheng** [comment]
端口映射后，用localhost:端口号，一般都能使用。不怎么需要固定IP的功能吧

**Comment by wanghe-fit2cloud** [comment]
> 暂时解决方法：可以用容器名连接。或者端口映射到宿主机，本机ip连接，但是nginx反代有时候会报错502。

1、相同容器网络下，肯定是首选容器名称连接。
2、如果担心安全问题，可以将端口映射到 127.0.0.1。但是反代 502 错误要看具体服务了，和连接方式关系不大。

**Comment by BrkOne** [comment]
> > 1、容器名称相同，肯定是首选容器连接。 2、如果担心安全问题，可以将端口映射到127.0.0.1。但是反代502错误不是具体服务了，而且连接方式关系不大。

“2、目标：实现容器和宿主机同一个ip段。操作：1panel》容器》网络》创建网络，创建了一条macvlan配置。但是在创建容器的时候，选择了刚刚创建的网络，无法自定义ip，导致自动分配的ip很容易和外界ip产生冲突（暂时无解，修改容器的配置文件，重启docker容器会被覆盖）”

主要是第2个使用场景，如果部署在内网，创建的多个容器，是需要使用macvlan和宿主机同ip段。自动分配很容易引起ip冲突。

**Comment by wanghe-fit2cloud** [comment]
> 主要是第2个使用场景，如果部署在内网，创建的多个容器，是需要使用macvlan和宿主机同ip段。自动分配很容易引起ip冲突。

了解，后续版本会考虑支持在创建容器时自定义地址。

**Comment by BrkOne** [comment]
> 了解，后续版本会考虑支持在创建容器时自定义地址。

感谢，期待。: )
现在家庭中有nas的用户逐渐增多，1panel配合使用起来很方便。这么好的面板，1panel在内网应该也有更多更好的使用场景。

**Comment by ZQun** [comment]
@wanghe-fit2cloud 强烈建议支持一下docker 指定ip的功能，还有ufw防火墙支持拦截docker端口；现在用的ufw-docker这个插件，有时服务器重启，docker自动分配的ip变了，就需要手动重新设置ufw-docker；所以如果这两项都能够支持一下，那真的就完美了

**Comment by wanghe-fit2cloud** [comment]
> @wanghe-fit2cloud 强烈建议支持一下docker 指定ip的功能，还有ufw防火墙支持拦截docker端口；现在用的ufw-docker这个插件，有时服务器重启，docker自动分配的ip变了，就需要手动重新设置ufw-docker；所以如果这两项都能够支持一下，那真的就完美了

收到，会在近期版本优先支持指定 IP 功能。

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。

**Comment by ZQun** [comment]
@wanghe-fit2cloud 你好，发现个问题，手动设置的ip，在服务器重启之后，设置过的ip会被随机重新分配新的ip，麻烦看下修复一下

**Comment by wanghe-fit2cloud** [comment]
> @wanghe-fit2cloud 你好，发现个问题，手动设置的ip，在服务器重启之后，设置过的ip会被随机重新分配新的ip，麻烦看下修复一下

在本地环境未复现该问题。
> 如果你的环境稳定复现，可以新开一个 issue 详细描述一下具体场景。

**Comment by ZQun** [comment]
@wanghe-fit2cloud 你好，我刚刚用一台新服务器，系统是ubuntu 22.04，安装1panel之后，重启服务器，ip地址还是会重新分配，截图是重启前和重启后的对比，服务器只安装了这几个环境，什么都没部署

<img width="1476" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/12726554/c096a7fc-860b-4049-8b35-a1ad2d42ef97">

**Comment by wartw** [comment]
我也遇到跟 @ZQun 一樣的問題，看起來是文件內沒有寫入固定IP造成系統REBOOT後就會被重新分配
