### ISSUE TITLE
[FEATURE]WebDAV 账号 tls 证书验证出错。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3664]
### 1Panel 版本

v1.9.4

### 请描述您的需求或者改进建议

我在备份账号中添加了一个webdav账号，https的（非默认端口），直接用工具连接正常，域名证书是 Let's Encrypt 的，浏览器中校验正常也没过期。

但是保存账号时提示出错：

> 备份账号测试连接失败 Options "https://xxxx.com:7007/": tls: failed to verify certificate: x509: certificate signed by unknown authority

### 请描述你建议的实现方案

在添加账号页面支持用户选择已有证书或者直接提供忽略证书的选项。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
