### ISSUE TITLE
多域名指向同一目录

### ISSUE THREAD

**Issue by Lwx7832** [1Panel-dev/1Panel#3665]
### 1Panel 版本

v1.5.5

### 请描述您的需求或者改进建议

什么时候可以支持多网站设置同一个目录、搞站群很需要、类似宝塔的多域名指向同目录，很多时候程序和配置都是一样的、所以只需要把域名指向一个目录就可以了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，计划在支持自定义网站目录时支持上述需求 #2783
