### ISSUE TITLE
[BUG]最新的1.9.4版本，创建PHP运行环境失败，

### ISSUE THREAD

**Issue by pdbeta** [1Panel-dev/1Panel#3666]
### 联系方式

pdbeta@qq.com

### 1Panel 版本

1.9.4

### 问题描述

网站，运行环境，创建PHP运行环境，不选择任何扩展，无论选择哪个版本都失败

### 重现步骤

网站，运行环境，创建PHP运行环境，不选择任何扩展，无论选择哪个版本都失败。附件是相关日志。
[build.log](https://github.com/1Panel-dev/1Panel/files/13999872/build.log)

**Comment by pdbeta** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/62172460/79276450-5114-4947-904c-fe6f2df7ca1d)

**Comment by zhengkunwang223** [comment]
你是什么操作系统和架构？
是否尝试过切换源

**Comment by pdbeta** [comment]
已解决，本地DNS服务器的问题。

不过有个建议，这个为啥要设置成每次重启恢复成默认值
![1705826280570](https://github.com/1Panel-dev/1Panel/assets/62172460/70aaa1dd-1fbd-400c-86d3-9967df1670eb)

**Comment by pdbeta** [comment]
> 你是什么操作系统和架构？ 是否尝试过切换源

UBUNTU，尝试过，后面发现是我这台内网的机器没指定本地DNS。

指定后OK了。
