### ISSUE TITLE
[BUG]部署Macms时用模板出现system error

### ISSUE THREAD

**Issue by jinghuashang** [1Panel-dev/1Panel#3667]
### 1Panel 版本

1.9.4

### 问题描述

macms部署完成后使用模板出现System Error
页面显示为
> 模板文件不存在:index/index.html

### 重现步骤

> 模板文件不存在:index/index.html

### 附加信息

猜测可能为伪静态问题

**Comment by wanghe-fit2cloud** [comment]
1Panel 是容器化安装网站，所以创建网站后如果存在上传文件等操作，需要手动修改持久化目录及文件权限，先确认一下是否是这里的问题：
<img width="1136" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/df94316b-f1b5-49ff-b608-9ab3c961d5bb">

> 至于 cms 等项目模板使用等问题，还要参考其官方文档。

**Comment by jinghuashang** [comment]
> 1Panel 是容器化安装网站，所以创建网站后如果存在上传文件等操作，需要手动修改持久化目录及文件权限，先确认一下是否是这里的问题： <img alt="image" width="1136" src="https://private-user-images.githubusercontent.com/46734380/298388948-df94316b-f1b5-49ff-b608-9ab3c961d5bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4OTc5NTYsIm5iZiI6MTcwNTg5NzY1NiwicGF0aCI6Ii80NjczNDM4MC8yOTgzODg5NDgtZGY5NDMxNmItZjFiNS00OWZmLWI2MDgtOWFiM2M5NjFkNWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA0MjczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMTg5Yzk1OGZhMmY3NjYwOTkyYjBjODFhOTI0Y2M1M2YzOTliZmUxOTA5MDgzZDI2NTgzY2MzMTExZGI5MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SU6c0jq-FIAFHUtOWn9nLfbC87FG2Dzi59Jc807uqV0">
> 
> > 至于 cms 等项目模板使用等问题，还要参考其官方文档。

保存了就变成了
> 类型错误: abs(): Argument #1 ($num) must be of type int|float, string given

**Comment by wanghe-fit2cloud** [comment]
上述错误信息应该和具体项目有关系，最好是将问题反馈给 Macms。
不过，你也可以尝试切换几个 PHP 运行环境版本，看是否是版本带来的问题。
> 我们也没有具体项目的搭建经验，望理解。

**Comment by jinghuashang** [comment]
经过测试，是对php版本支持的问题，Maccms建议使用<php8版本的

**Comment by chan-shen** [comment]
是php版本的问题，从php8降到php5.6后解决了
