### ISSUE TITLE
[QUESTION]什么软件都装不上

### ISSUE THREAD

**Issue by gh61514** [1Panel-dev/1Panel#3670]
### 请描述您的问题

stderr: Container 1Panel-mysql Creating Container 1Panel-mysql Created Container 1Panel-mysql Starting Error response from daemon: driver failed programming external connectivity on endpoint 1Panel-mysql (59c91d8d24d3a7db725c13b8fd2fd182a7fed53205d2924697925f8d4f154f65): (COMMAND_FAILED: '/usr/bin/iptables -w10 -t nat -A DOCKER -p tcp -d 127.0.0.1 --dport 3306 -j DNAT --to-destination 172.18.0.2:3306 ! -i br-31d32a8c83a7' failed: iptables: No chain/target/match by that name. )

stderr: Container 1Panel-yesplaymusic-cS1b Creating Container 1Panel-yesplaymusic-cS1b Created Container 1Panel-yesplaymusic-cS1b Starting Error response from daemon: driver failed programming external connectivity on endpoint 1Panel-yesplaymusic-cS1b (87f8286d988ef8555e1bf59e633cb1c4a4fa06007b0f8d6408ab77853cc599c2): (COMMAND_FAILED: '/usr/bin/iptables -w10 -t nat -A DOCKER -p tcp -d 127.0.0.1 --dport 40075 -j DNAT --to-destination 172.18.0.2:80 ! -i br-31d32a8c83a7' failed: iptables: No chain/target/match by that name. )

![Snipaste_2024-01-22_11-07-57](https://github.com/1Panel-dev/1Panel/assets/75356239/fe7896a5-9be9-43b5-98d6-8ad54dd010a7)

系统版本是：
主机名称 archlinux
--
发行版本 arch-
内核版本 6.6.10-arch1-1
系统类型 x86_64

**Comment by zhengkunwang223** [comment]
是防火墙的原因  已经在群里解决
