### ISSUE TITLE
[FEATURE]定时任务，同步服务器时间，什么时候能支持内网时间服务器地址？

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3671]
### 1Panel 版本

v1.9.4

### 请描述您的需求或者改进建议

定时任务，同步服务器时间，什么时候能支持内网时间服务器地址？
![wecom-temp-11156-f68f33beaa4a6845562073bba89fa60c](https://github.com/1Panel-dev/1Panel/assets/29944886/03a1d12d-88c6-4399-b571-2d10b23a7a56)

**Comment by wanghe-fit2cloud** [comment]
需要进入 `工具箱` 页面来设置 NTP 服务器，这里输入内网服务器地址就可以，如图：
![企业微信截图_6ed0e2d2-4698-4e0e-adf8-bfc5c0f91dfe](https://github.com/1Panel-dev/1Panel/assets/46734380/f107235b-842d-48ed-ad6f-3f4a939fc296)

> 后续版本我们也会在创建计划任务页面增加相关提示信息。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
