### ISSUE TITLE
dataease增加Mariadb数据库支持

### ISSUE THREAD

**Issue by ifacecn** [1Panel-dev/1Panel#3677]
### 1Panel 版本

1.9.4

### 请描述您的需求或者改进建议

我以为是dataease不支持，我去问了一下，他们说dataease1.3版本就已经支持了，那就是1panel这边了

**Comment by wanghe-fit2cloud** [comment]
后续版本考虑支持。

**Comment by wanghe-fit2cloud** [comment]
咨询过 DataEase 项目组，目前官方文档中还未正式提供 MariaDB 部署方案，后续补充后 1Panel 也会同步支持。
> 当前版本，如果必须使用 MariaDB 数据库服务，可以考虑使用 `创建编排` 的方式来管理 DataEase。
