### ISSUE TITLE
[BUG] frpc 客户端在服务器重启后，不会按配置参数加载数据连接frps，只会链接127.0.0.1:7000服务端

### ISSUE THREAD

**Issue by Shuai-S** [1Panel-dev/1Panel#3678]
### 1Panel 版本

v1.9.4

### 问题描述

frpc 客户端在服务器重启后，不会按配置参数加载数据连接frps，只会链接127.0.0.1:7000服务端

### 重现步骤

修改挂载配置文件后 重启服务器，没有按配置文件加载配置链接服务端

**Comment by Shuai-S** [comment]
<img width="709" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/52077275/c6b4d491-4658-4369-9028-6ffe55ad35a7">

**Comment by wanghe-fit2cloud** [comment]
1Panel 是容器化安装的应用，安装目录及配置文件所在目录如下图所示：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/2603b9c7-fb0d-4c55-a611-079dc6a6f1b9)

> 应用具体的使用问题，还要参考其官方说明。

**Comment by Shuai-S** [comment]
<img width="902" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/52077275/bc0526df-de61-46cf-aa1a-3a6186758102">

更改的就是该目录配置文件，但是应用重启后不安该配置文件加载数据启动

**Comment by zhengkunwang223** [comment]
> <img alt="image" width="902" src="https://private-user-images.githubusercontent.com/52077275/298834346-bc0526df-de61-46cf-aa1a-3a6186758102.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTQyMTksIm5iZiI6MTcwNTk5MzkxOSwicGF0aCI6Ii81MjA3NzI3NS8yOTg4MzQzNDYtYmMwNTI2ZGYtZGU2MS00NmNmLWFhMWEtM2E2MTg2NzU4MTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA3MTE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNWQwNTMwZjEwNWI2MjJjYWNlNGM0ZTNmYmExN2NkYzk4YWU4YjkzMTY3YzNkZGU0OGUyYTZmNTU3YWMwMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ks4aqpeTu_G5jjHb0aR-6hW3cav5kk0Q_j_xn7vtf4g">
> 更改的就是该目录配置文件，但是应用重启后不安该配置文件加载数据启动

看一下容器日志吧

**Comment by okxlin** [comment]
去除隐私后建议展示一下所写的frpc.toml，

正常都是按照配置文件来运行的，

然后镜像版本有没有改动？

**Comment by Shuai-S** [comment]
<img width="1228" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/52077275/5a187c9c-d015-45f2-96a9-f9d5b72369d0">
我重装后，现在是正常的，安照我配置的参数链接到我的服务端了

我改完配置文件 点击重启后

<img width="1183" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/52077275/99c0686f-8e99-47ad-b6cb-0b6a462c35eb">


frpc  | WARNING: ini format is deprecated and the support will be removed in the future, please use yaml/json/toml format instead!
frpc  | 2024/01/23 07:32:59 [1;34m[I] [root.go:141] start frpc service for config file [/etc/frp/frpc.toml][0m
frpc  | 2024/01/23 07:32:59 [1;34m[I] [service.go:287] try to connect to server...[0m
frpc  | 2024/01/23 07:32:59 [1;33m[W] [service.go:290] connect to server error: dial tcp 0.0.0.0:7000: connect: connection refused[0m
frpc  | 2024/01/23 07:32:59 [1;34m[I] [root.go:159] frpc service for config file [/etc/frp/frpc.toml] stopped[0m
frpc  | login to the server failed: dial tcp 0.0.0.0:7000: connect: connection refused. With loginFailExit enabled, no additional retries will be attempted
frpc  | WARNING: ini format is deprecated and the support will be removed in the future, please use yaml/json/toml format instead!
frpc  | 2024/01/23 07:33:00 [1;34m[I] [root.go:141] start frpc service for config file [/etc/frp/frpc.toml][0m
frpc  | 2024/01/23 07:33:00 [1;34m[I] [service.go:287] try to connect to server...[0m
frpc  | 2024/01/23 07:33:00 [1;33m[W] [service.go:290] connect to server error: dial tcp 0.0.0.0:7000: connect: connection refused[0m
frpc  | 2024/01/23 07:33:00 [1;34m[I] [root.go:159] frpc service for config file [/etc/frp/frpc.toml] stopped[0m
frpc  | login to the server failed: dial tcp 0.0.0.0:7000: connect: connection refused. With loginFailExit enabled, no additional retries will be attempted
frpc  | WARNING: ini format is deprecated and the support will be removed in the future, please use yaml/json/toml format instead!
frpc  | 2024/01/23 07:33:00 [1;34m[I] [root.go:141] start frpc service for config file [/etc/frp/frpc.toml][0m
frpc  | 2024/01/23 07:33:00 [1;34m[I] [service.go:287] try to connect to server...[0m
frpc  | 2024/01/23 07:33:00 [1;33m[W] [service.go:290] connect to server error: dial tcp 0.0.0.0:7000: connect: connection refused[0m
frpc  | 2024/01/23 07:33:00 [1;34m[I] [root.go:159] frpc service for config file [/etc/frp/frpc.toml] stopped[0m
frpc  | login to the server failed: dial tcp 0.0.0.0:7000: connect: connection refused. With loginFailExit enabled, no additional retries will be attempted
frpc  | WARNING: ini format is deprecated and the support will be removed in the future, please use yaml/json/toml format instead!
frpc  | 2024/01/23 07:33:00 [1;34m[I] [root.go:141] start frpc service for config file [/etc/frp/frpc.toml][0m
frpc  | 2024/01/23 07:33:00 [1;34m[I] [service.go:287] try to connect to server...[0m
frpc  | 2024/01/23 07:33:00 [1;33m[W] [service.go:290] connect to server error: dial tcp 0.0.0.0:7000: connect: connection refused[0m
frpc  | 2024/01/23 07:33:00 [1;34m[I] [root.go:159] frpc service for config file [/etc/frp/frpc.toml] stopped[0m
frpc  | login to the server failed: dial tcp 0.0.0.0:7000: connect: connection refused. With loginFailExit enabled, no additional retries will be attempted

**Comment by Shuai-S** [comment]
[common]
serverAddr = "XXXXXXXX"
serverPort = 7600
token = "XXXXXX"

webServer.addr = "0.0.0.0"
webServer.port = 7400
webServer.user = "XXXXX"
webServer.password = "XXXXXX"
webServer.pprofEnable = false


[ESXI-frpc]
type = tcp
local_ip = 10.10.10.4
local_port = 7400
remote_port = 10000


[ESXI-ikuai]
type = tcp
local_ip = 10.10.10.1
local_port = 80
remote_port = 10001


[ESXI-web]
type = tcp
local_ip = 192.168.123.123
local_port = 443
remote_port = 10002

[ESXI-ssh]
type = tcp
local_ip = 10.10.10.2
local_port = 22
remote_port = 10004

[CentOS-ssh]
type = tcp
local_ip = 10.10.10.4
local_port = 22
remote_port = 10005


[CentOS-1Panel-web]
type = tcp
local_ip = 10.10.10.4
local_port = 23180
remote_port = 10006

[CentOS-qinglong-web]
type = tcp
local_ip = 10.10.10.4
local_port = 5700
remote_port = 10007


配置文件内容如上

**Comment by wanghe-fit2cloud** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/7bd2b8db-f9cc-45d4-b7a7-e1a2abba8ba9)

**Comment by okxlin** [comment]
你的写法用的`ini`格式的，应该用新版本的格式来写，

5.2版本以上抛弃ini格式了，

可以参照我的写法

https://github.com/okxlin/appstore

**Comment by Shuai-S** [comment]
解决了，谢谢
