### ISSUE TITLE
[FEATURE] 多台机器上ssl证书的同步

### ISSUE THREAD

**Issue by Mystery00** [1Panel-dev/1Panel#368]
### 1Panel 版本

1.0.2

### 请描述您的需求或者改进建议

期望能够提供一种方案实现多台机器上ssl证书的同步。
例如：某一台机器作为控制机，统一管理ssl证书，其它机器以ssh或者其他方式加入到控制机中，控制机能够通过操作自动或手动将ssl证书同步到其它机器上

**Comment by ChishFoxcat** [comment]
这应该就包括在多主机管理了

**Comment by maninhill** [comment]
请问这个问题有进展吗？

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is there any progress on this issue?

**Comment by wanghe-fit2cloud** [comment]
目前版本可以通过自定义脚本来实现，如图：
![image](https://github.com/user-attachments/assets/ef52b05f-0f90-450a-b3cb-4ea8a60095b7)
