### ISSUE TITLE
[BUG] 网站无法停止nodejs环境

### ISSUE THREAD

**Issue by fuyaoqing** [1Panel-dev/1Panel#3680]
### 1Panel 版本

v1.9.4

### 问题描述

用nodejs运行环境创建的网站停止后依然可以访问

### 重现步骤

1.nodejs运行环境
2.用运行环境创建网站
3.停止网站
4.网站依然可以正常访问

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
刚刚在本地环境已复现上述问题，会在近期版本修复并推送更新。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
