### ISSUE TITLE
[FEATURE] 能否兼容备份快照到nextcloud网盘

### ISSUE THREAD

**Issue by glxaa** [1Panel-dev/1Panel#3682]
### 1Panel 版本

lastest

### 请描述您的需求或者改进建议

能否兼容备份快照到nextcloud网盘

### 请描述你建议的实现方案

能否兼容备份快照到nextcloud网盘，只需要输入一次性的账户密码即可

**Comment by wanghe-fit2cloud** [comment]
中短期内暂无计划支持，望理解。
