### ISSUE TITLE
希望可以适配armv7的商店应用

### ISSUE THREAD

**Issue by mufengyouyang** [1Panel-dev/1Panel#3683]
### 1Panel 版本

v1.9.4

### 请描述您的需求或者改进建议

现在商店拉去的最新版应用，很多都只支持arm v8等64位或者是x86版的应用，很少有支持arm v7 32位的docker应用。而docker hub又因为被墙的原因，导致平时访问寻找对应的32位应用比较麻烦，希望商店可以支持不同版本的系统，默认拉取对应版本的应用。而没有适配版本的应用，则默认不显示。

### 附加信息

![neosmemo_memos Tags](https://github.com/1Panel-dev/1Panel/assets/130118370/ad7488c9-26e0-4383-b882-d8f14b415949)

**Comment by wanghe-fit2cloud** [comment]
当前版本可以参考文档来创建对应架构的应用：https://1panel.cn/docs/faq/server_architecture/

上架应用区分架构的相关问题的讨论，统一汇总到该 issue #3026
