### ISSUE TITLE
[BUG] 快照恢复后已安装应用错乱了

### ISSUE THREAD

**Issue by muzidudu** [1Panel-dev/1Panel#3685]
### 1Panel 版本

v1.9.4

### 问题描述

![QQ](https://github.com/1Panel-dev/1Panel/assets/9375220/e9846768-280c-44f7-8936-774e5e4c1098)

### 重现步骤

1号机子创建快照后,2号机子恢复快照图标乱了,容器也不存在

**Comment by ssongliu** [comment]
感谢反馈，麻烦添加一下我好友，我远程看看这个问题
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/ae161993-6b18-4866-a320-3c0a301b5bd1)

**Comment by muzidudu** [comment]
> 感谢反馈，麻烦添加一下我好友，我远程看看这个问题 ![image](https://private-user-images.githubusercontent.com/73214554/298902943-ae161993-6b18-4866-a320-3c0a301b5bd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTc5MDEsIm5iZiI6MTcwNjAxNzYwMSwicGF0aCI6Ii83MzIxNDU1NC8yOTg5MDI5NDMtYWUxNjE5OTMtNmIxOC00ODY2LWEzMjAtM2MwYTMwMWI1YmQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEzNDY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzODMzZjgwOTlmNjFjNDc3MDhlOTA4OTY3YjY1M2RiZGJmMDFkY2NmYmI5N2Y5N2MzYzU2NzdjZTRhZmVlZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gc-8E85FYqETwrCoVR6YS3E4htcgNk7xQcnctbEsFb0)

已经删除了... 手动重新创建一步一步安装

**Comment by wanghe-fit2cloud** [comment]
> 已经删除了... 手动重新创建一步一步安装

刚在本地环境未复现上述问题。
你可以添加一下 @ssongliu 微信，远程你的环境看一下问题。
