### ISSUE TITLE
[FEATURE] 应用商店内的php是否可以加入uid，gid指定？

### ISSUE THREAD

**Issue by Shazoo** [1Panel-dev/1Panel#3686]
### 1Panel 版本

v1.9.4

### 请描述您的需求或者改进建议

不少云主机1000/1001都占用了的。不是日常操作账号。

目前的docker php 貌似都是顶死了1000了。

**Comment by zhengkunwang223** [comment]
容器内外用户体系是隔离的 宿主机的用户并不影响 PHP 容器内部 
无论宿主机 1000 用户是什么 PHP 容器内都是 www-data
所以确实不需要修改 PHP 的容器内 uid，gid

**Comment by Shazoo** [comment]
嗯。那可能我理解有误。不过，php应用的dockerfile哪里可以看到？我想弄清楚这块。

**Comment by wanghe-fit2cloud** [comment]
> 嗯。那可能我理解有误。不过，php应用的dockerfile哪里可以看到？我想弄清楚这块。

Docker Hub 地址：
https://hub.docker.com/_/php

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/09995ae7-a9dc-4e71-afb4-17820000e0f5)
