### ISSUE TITLE
[FEATURE] 使用自定义命令直接运行js文件

### ISSUE THREAD

**Issue by 2509989976** [1Panel-dev/1Panel#3688]
### 1Panel 版本

1.9.4

### 请描述您的需求或者改进建议

我有一个已经构建好的index.js 单文件，他没有package.json文件，也不依赖node_modules。这个文件我可以直接通过node ./index.js直接运行。但是我使用自定义启动命令时，无法正常启动。
以下是我的配置
![Dingtalk_20240124114934](https://github.com/1Panel-dev/1Panel/assets/100815534/26a6fff8-cac6-4065-9b72-c4390eca9b6d)

### 请描述你建议的实现方案

希望新增一个选项，可以跳过npm安装步骤，并且不使用npm执行自定义命令

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们暂无支持上述需求的计划，望理解。
