### ISSUE TITLE
[FEATURE]现在的网站日志加载方式优化！

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3690]
### 1Panel 版本

v1.9.4

### 请描述您的需求或者改进建议

现在查看网站日志，日志加载是从第1行开始加载的，这样日志多了系统会蹦！
我这时不时就得清空一次日志，不然根本看不到最新的日志系统就蹦了！
我这加载到十几万行的时候就蹦了，不同机器可能蹦的行数不一样，但是这种从第1行开始加载的逻辑肯定是不对的，可以参考一下docker面板里显示日志的方式，只不断的更新显示最新的日志就行了！

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑优化日志加载方案。

**Comment by Shuai-S** [comment]
希望下个版本优化日志读取逻辑🙏🏻

**Comment by wanghe-fit2cloud** [comment]
> 希望下个版本优化日志读取逻辑🙏🏻

已纳入 v1.10.12 版本迭代计划，将于7月份发布。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
