### ISSUE TITLE
[FEATURE]删除 PHP 和 Node.js 运行环境的提示信息可以优化。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3698]
### 1Panel 版本

v1.9.4

### 请描述您的需求或者改进建议

当前版本删除 PHP 或者 Node.js 运行环境时，如果该运行环境有关联网站，点击确认删除后才会有提示信息，如图：
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/dedb0b8d-5427-4c11-8950-2a9f1106187d)

这里可以修改为删除有网站关联的应用时一样的页面，如图：
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/896e32d0-e22c-45bb-80bf-2837643d15fd)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本优化上述提示页面。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
