### ISSUE TITLE
[BUG]计划任务目录备份错误

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#3706]
### 1Panel 版本

1.9.4

### 问题描述

使用`计划任务 》 目录备份`备份文件夹出错，错误演示：
![20240125-183047](https://github.com/1Panel-dev/1Panel/assets/63288007/584f53cc-8b88-4c78-8612-49d1a1183ffb)

错误信息：
```txt
服务内部错误: stat /home/backup/directory/目录备份OpenResty website/directory_1panel_1panel_apps_openresty_openresty_www_20240125182150.tar.gz: no such file or directory
```

### 重现步骤

* `OpenResty`容器的目录网站地址：`/1panel/1panel/apps/openresty/openresty`
* 计划备份文件夹：`/1panel/1panel/apps/openresty/openresty/www`
* 计划备份输出：`/home/backup/directory`

`计划任务 》 目录备份` 计划信息：
![PixPin_2024-01-25_18-37-09](https://github.com/1Panel-dev/1Panel/assets/63288007/97216266-e8c1-48ef-9f2e-6db6536dceb5)

备份执行显示成功后，打开`计划备份输出`：
![PixPin_2024-01-25_18-38-22](https://github.com/1Panel-dev/1Panel/assets/63288007/b9dd7bb8-a834-4506-b34e-3116c56b5d38)

进入`/1panel/1panel/apps/openresty/openresty`路径，手动压缩计划备份目录`www`，则成功：
![PixPin_2024-01-25_18-43-29](https://github.com/1Panel-dev/1Panel/assets/63288007/cd200ba8-5bb8-4dc8-8f11-0306277b869d)

**Comment by JAINKRE** [comment]
这个错误找到原因了，是因为任务名称创建过程中包含空格，当新建一个不包含空格的任务名称执行目录备份则正常。

看来是文件夹路径的问题，希望后续可以优化一下。

比如不支持计划任务名称包含空格，可以通过前端检测提示。但还是希望可以支持空格。

**Comment by wanghe-fit2cloud** [comment]
收到，后续版本持续优化。
> 具体命令通过 `` 特殊字符处理也可以。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
