### ISSUE TITLE
[BUG] docker-compose.yml 文件 注释了一行之后，重建镜像之后，注释会被删除

### ISSUE THREAD

**Issue by mobeicanyue** [1Panel-dev/1Panel#3708]
### 1Panel 版本

v1.9.4

### 问题描述

docker-compose.yml 文件 注释了一行之后，重建镜像之后，注释会被删除。不知道是 docker-compose 的特色还是 1panel 导致的

### 重现步骤

docker-compose.yml 文件 注释了一行之后，重建镜像之后，注释会被删除

**Comment by wanghe-fit2cloud** [comment]
麻烦再贴一下操作截图等信息。

**Comment by mobeicanyue** [comment]
我现在在 vaultwarden 的 environment 加上 `ADMIN_TOKEN` 变量，点击保存后，通过访问 domain/admin 可以正常启动管理页面。
![image](https://github.com/1Panel-dev/1Panel/assets/81098819/17f463ee-0fc0-41e8-8419-8a9810b543b5)

现在 给 `ADMIN_TOKEN` 加上注释
![image](https://github.com/1Panel-dev/1Panel/assets/81098819/dddfce12-3912-4d8c-9ff6-96a2dae165c5)
点击确定
![image](https://github.com/1Panel-dev/1Panel/assets/81098819/665ee1c9-2899-4f90-9649-cf048f74a117)
现在 变量消失了
![image](https://github.com/1Panel-dev/1Panel/assets/81098819/5637d519-8822-42c5-b2b3-af8cd6d1b35a)

**Comment by mobeicanyue** [comment]
你好？

**Comment by wanghe-fit2cloud** [comment]
本地环境已经验证，在后端读取 key 的时候，sdk 会默认忽略掉 # 注释。
> 因此会导致已经被注释的环境变量丢失。

**Comment by mobeicanyue** [comment]
> 本地环境已经验证，在后端读取 key 的时候，sdk 会默认忽略掉 # 注释。
> 
> > 因此会导致已经被注释的环境变量丢失。

sdk 是 1panel 框架的 sdk 吗

**Comment by wanghe-fit2cloud** [comment]
> sdk 是 1panel 框架的 sdk 吗

是的，yaml 转 map 时会忽略被注释的 key。
