### ISSUE TITLE
[BUG]避免日志出现非UTF-8字符导致错误

### ISSUE THREAD

**Issue by lnatpunblhna** [1Panel-dev/1Panel#3715]
### 1Panel 版本

v1.9.1

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/33893697/37647b9d-1869-4d05-a77b-c914fed4f434)
当日志中出现非UTF-8字符时 日志会错误停止

### 重现步骤

日志中出现非UTF-8

### 期待的正确结果

跳过非正常字符

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在 v1.9.5 版本中包含上述内容。
> 先开启该 Issue 了，待测试通过后会关闭 Issue。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
