### ISSUE TITLE
[BUG]上传文件不会计算硬盘容量是否足够并且导致缓存目录被塞满

### ISSUE THREAD

**Issue by stmtc233** [1Panel-dev/1Panel#3719]
### 1Panel 版本

v1.9.4

### 问题描述

我的/data1目录容量是足够的
当我通过面板的上传文件上传一个文件时会先保存到缓存目录
这样就会保存到不是data1的目录下 导致/被塞满
/塞满后面板会出现unable to open database file的错误

到 工具箱-缓存清理 扫描了一下 “临时上传文件” 高达20g 清理后面板恢复正常

### 重现步骤

上传大于缓存目录的文件

### 期待的正确结果

把“临时上传文件”变为上传所在的目录而不是缓存目录
增加上传文件时该目录下容量是否足够

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本优化上述功能。

**Comment by wanghe-fit2cloud** [comment]
上述问题的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/5184
