### ISSUE TITLE
[建议]计划任务-备份在选择所有增加排除选项

### ISSUE THREAD

**Issue by 520svip** [1Panel-dev/1Panel#3720]
### 1Panel 版本

1.9.4

### 请描述您的需求或者改进建议

我十几个应用，有个应用(网站)不想进行备份，所以能不能在选择所有的情况下，增加一个多选的不想备份的应用选择

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述建议。

**Comment by ssongliu** [comment]
考虑备份时直接提供多选操作。

**Comment by hhhguany** [comment]
#4955 同样迫切需要这个优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.12-beta.3 版本中，备份网站、应用、数据库三种任务类型已支持多选。
