### ISSUE TITLE
希望增加docker 容器的配置开机启动

### ISSUE THREAD

**Issue by 534146825** [1Panel-dev/1Panel#3721]
### 1Panel 版本

v1.9.4

### 请描述您的需求或者改进建议

目前在web界面并不能配置docker容器的开机自启动

### 请描述你建议的实现方案

希望未来可以考虑支持配置docker容器的开机自启动

**Comment by wanghe-fit2cloud** [comment]
可以在创建、编辑容器时自定义 `重启策规则`，如图：
<img width="705" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/fef5bfe7-0fc9-49b3-85e5-d2c9ba66624d">
