### ISSUE TITLE
[BUG]如果设置了服务器IP，备份不能被成功恢复

### ISSUE THREAD

**Issue by RedwindA** [1Panel-dev/1Panel#3722]
### 1Panel 版本

v1.9.4

### 问题描述

恢复快照后无法访问1Panel

### 重现步骤

1.在A服务器中的面板设置中设置服务器的IP地址；
2.在1Panel中创建快照到OneDrive
3.在B服务器的1panel中从OneDrive中恢复快照
4.以IP+端口访问1panel，浏览器显示`未发送任何数据`

解决方法：
清空A服务器面板中所设置服务器的IP地址，然后再备份并恢复，即可正常访问

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
刚在本地环境验证均未复现上述问题。

B 服务器 1Panel 使用 A 快照恢复成功后，面板设置中确实会显示 A 服务器 IP。
但是使用 B 服务器 IP + 端口访问没有问题。

**Comment by RedwindA** [comment]
感谢测试和回复，可能是由我没注意到其他异常因素引起的吧。。。。不好意思
