### ISSUE TITLE
[FEATURE]希望证书申请之后可以修改推送目录

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3723]
### 1Panel 版本

v1.9.4

### 请描述您的需求或者改进建议

想要修改推送目录要关闭所有的 HTTPS，然后删除证书重新申请，感觉太麻烦了。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
修改证书推送目录及名称的需求，统一汇总到该 issue #4827
