### ISSUE TITLE
[FEATURE]关于网站命名相同的问题。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3726]
### 1Panel 版本

v1.9.4

### 请描述您的需求或者改进建议

因为设备存在多网卡多网络的情况，使用网站设置反代指向ip的某一端口。
该ip:port形式显示的网站全为ip地址，面板中查看日志十分不便。

请问可否进行优化？

![image](https://github.com/1Panel-dev/1Panel/assets/93708226/46d8bee0-3861-4051-ad3b-d32b02a145ed)
![image](https://github.com/1Panel-dev/1Panel/assets/93708226/f387c56f-042d-4b94-ad3b-996cd33046c9)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
