### ISSUE TITLE
[BUG] 通过Nginx反代管理面板后，无法通过应用商店安装应用

### ISSUE THREAD

**Issue by colinwjd** [1Panel-dev/1Panel#3728]
### 1Panel 版本

1.9.4

### 问题描述

通过Nginx反代管理面板，使用域名访问管理页面时，无法通过应用商店安装应用，确认安装时会自动跳回登录页面，并提示没有权限
<img width="1211" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/7942918/1328cb2f-554d-4d96-a712-3912fda5da6b">

### 重现步骤

使用应用商店的OpenResty，反向代理1panel管理面板，然后进入应用商店安装应用

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们现在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
通过 1Panel 网站菜单创建反向代理网站后访问 1Panel 控制台并安装应用，未复现上述问题。
> 出现上述问题的原因，可能是网站 WAF 拦截的原因导致的。

**Comment by colinwjd** [comment]
<img width="1001" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/7942918/a8d1bb1f-923e-4f81-9a9e-bea1b775baeb">
确实是WAF的原因，把这个POST参数校验关掉就可以了

**Comment by DeSireFire** [comment]
> <img alt="image" width="1001" src="https://private-user-images.githubusercontent.com/7942918/300431680-a8d1bb1f-923e-4f81-9a9e-bea1b775baeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxOTU4NTIsIm5iZiI6MTcwOTE5NTU1MiwicGF0aCI6Ii83OTQyOTE4LzMwMDQzMTY4MC1hOGQxYmIxZi05MjNlLTRmODEtOWE5ZS1iZWExYjc3NWJhZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjlUMDgzMjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjM4Zjg4ZjYwY2RhYzYzNjFkMTJmOGNjOTU4YzQyMmJlNDRkNmY5MmNjMzNkYmFlNzA0NzU0MWMwMGViOTE3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dK78H7WA2dXZYy8HM2sYdsS735Y0SrLqV3qRe3lLCBE"> 确实是WAF的原因，把这个POST参数校验关掉就可以了

你好，我碰到了同样的问题。
使用腾讯轻量云的nginx反代，家里树莓派上的1panel.
我想安装Home Assistant，提示无权限，并弹出到登录页。
使用内网访问树莓派1panel能正常安装。
我找不到楼主你截图中的post参数校验，我用的版本v1.9.6
