### ISSUE TITLE
[FEATURE]能否针对编排(docker compose)提供更多的管理能力

### ISSUE THREAD

**Issue by colinwjd** [1Panel-dev/1Panel#3729]
### 1Panel 版本

1.9.4

### 请描述您的需求或者改进建议

这里能否增加诸如【更新】【重启】【停止】等等功能
<img width="1585" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/7942918/26a71e9a-48b6-4c5f-b894-c8e04dc119d4">

**Comment by wanghe-fit2cloud** [comment]
点击编排名称进入详情页面，是支持启停等操作的。
> 仅支持通过 1Panel 页面创建的编排。
