### ISSUE TITLE
[BUG]反向代理模式下，设置密码访问无效

### ISSUE THREAD

**Issue by percyc** [1Panel-dev/1Panel#3730]
### 联系方式

zhushurui@hotmail.com

### 1Panel 版本

v1.9.4

### 问题描述

# 问题
设置反向代理一个本地的端口，添加了密码访问并开启后，访问web仍然没有密码认证。

### 重现步骤

# 步骤
设置反向代理一个本地的端口，添加了密码访问并开启后，访问web仍然没有密码认证。

### 期待的正确结果

设置成功后，需要验证才能访问我的web

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
刚在本地环境测试（反向代理 1Panel 服务）未复现上述问题。
> 你尝试清除一下浏览器缓存或者更换其他浏览器。

**Comment by percyc** [comment]
我相信描述一下过程吧，麻烦尝试，谢谢！
1、在应用商店安装it-tools，没有勾选外网访问。
2、创建网站，绑定域名，添加https证书
3、密码访问，创建密码
4、是否启用--> 开启
5、通过域名访问，无需密码访问成功。

**Comment by percyc** [comment]
> 感谢反馈。 刚在本地环境测试（反向代理 1Panel 服务）未复现上述问题。
> 
> > 你尝试清除一下浏览器缓存或者更换其他浏览器。

我相信描述一下过程吧，麻烦尝试，谢谢！
1、在应用商店安装it-tools，没有勾选外网访问。
2、创建网站，绑定域名，添加https证书
3、密码访问，创建密码
4、是否启用--> 开启
5、通过域名访问，无需密码访问成功。

**Comment by percyc** [comment]
> 感谢反馈。 刚在本地环境测试（反向代理 1Panel 服务）未复现上述问题。
> 
> > 你尝试清除一下浏览器缓存或者更换其他浏览器。

我详细描述一下过程吧，麻烦尝试，谢谢！
1、在应用商店安装it-tools，没有勾选外网访问。
2、创建网站，绑定域名，添加https证书
3、密码访问，创建密码
4、是否启用--> 开启
5、通过域名访问，无需密码访问成功。

**Comment by percyc** [comment]
> > 感谢反馈。 刚在本地环境测试（反向代理 1Panel 服务）未复现上述问题。
> > > 你尝试清除一下浏览器缓存或者更换其他浏览器。
> 
> 我详细描述一下过程吧，麻烦尝试，谢谢！ 1、在应用商店安装it-tools，没有勾选外网访问。 2、创建网站，绑定域名，添加https证书 3、密码访问，创建密码 4、是否启用--> 开启 5、通过域名访问，无需密码访问成功。

第2个步骤反向代理127.0.0.1的it-tools的端口，另外，我尝试了反代1panel也是成功的。

**Comment by percyc** [comment]
刷新多次后成功了，我也不知道为什么。。。。感谢协助。
