### ISSUE TITLE
[BUG] 扩展模板过长，导致正则验证失败无法保存

### ISSUE THREAD

**Issue by bh1xaq** [1Panel-dev/1Panel#3731]
### 1Panel 版本

v1.9.4

### 问题描述

保存扩展列表报错了。

![1706457977425](https://github.com/1Panel-dev/1Panel/assets/16686956/a187048c-200e-40a0-8fff-d71f202df9e9)

### 重现步骤

复制以下扩展列表(长度>300) 到 扩展模板中，点击保存。

```
bcmath,bz2,calenda,core,ctype,curl,date,dom,exif,fileinfo,filter,gd,hash,iconv,json,libxml,mbstring,memcache,mysqli,mysqlnd,odbc,openssl,pcre,pdo,pdo_mysql,pdo_odbc,pdo_sqlite,phar,readline,redis,reflection,session,simplexml,soap,sockets,sodium,spl,standard,tokenizer,xml,xmlreader,xmlwriter,zip,zlib,swoole
```

### 期待的正确结果

保存成功。

### 相关日志输出

```shell
无
```

### 附加信息

https://github.com/1Panel-dev/1Panel/blob/dev/frontend/src/global/form-rules.ts

```
const reg = /^[a-z0-9,_]{1,300}$/;
```

可能与此有关。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
