### ISSUE TITLE
[BUG]长时间使用终端会中断

### ISSUE THREAD

**Issue by stmtc233** [1Panel-dev/1Panel#3732]
### 1Panel 版本

v1.9.4

### 问题描述

长时间使用终端如果使用时间超过了登录状态超时时间并且没有进行其他操作会导致终端断开连接（登录状态失效）
本人在docker终端中多次出现该问题 本机终端未知

### 重现步骤

长时间使用终端并且不执行其他操作

**Comment by ssongliu** [comment]
感谢反馈，_**超过了登录状态超时时间**_ 这个是指的面板设置里面的超时时间吗？
1Panel 的终端都有一个 10 秒的心跳保活机制，应该不会中断。

**Comment by stmtc233** [comment]
> 感谢反馈，_**超过了登录超时时间**_这个是指面板设置里面的超时时间吗？ 1面板的终端有一个10秒的心率保活机制，应该不会中断。

对的 正常来说终端是不会断的但是如果登录状态没了终端就断了

**Comment by wanghe-fit2cloud** [comment]
> 对的 正常来说终端是不会断的但是如果登录状态没了终端就断了

是的，主机、容器终端会随着 1Panel 系统退出而中断，属于正常现象。

**Comment by stmtc233** [comment]
> > 对正常情况的终端是不会断的但是如果登录状态没有了终端就断了
> 
> 是的，主机、容器终端会随着1Panel系统退出现象而中断，属于正常。

但是我的终端正在运行 如果使用终端的时间超过了**超时时间**那么终端就会断开 这不正常
