### ISSUE TITLE
[FEATURE]建议在网站创建之后支持修改网站类型。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3736]
### 1Panel 版本

v1.9.4

### 请描述您的需求或者改进建议

首先非常感谢开发并开源 1Pabel 的各位伙伴和大师，之前一直用宝塔面板后来发现 1Panel 试了一下就回不去宝塔了。

首先界面很干净，体验好，而且最重要的是 docker 的适配。
虽然宝塔也有 docker 功能，但他对网站管理的优化确实比较擅长的，咱 1Panel 也各个方面都挺好。

但是我发现了关于网站管理中的一个问题，所以今天想在这咨询并且建议。
就是网站类型比如静态网站，运行环境等一旦创建成功后面，再想修改网站类型就找不到更改的设置了所以希望大佬们试一下，要是确实存在这种问题希望加个这么个功能。

**Comment by wanghe-fit2cloud** [comment]
切换网站类型相关的讨论，统一汇总到该 issue #2532
