### ISSUE TITLE
[QUESTION]计划任务卡住了，重启了服务器还是一样，怎么删除这个执行？

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3738]
### 请描述您的问题

![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/acf004a9-7a0a-42dc-aa1b-30e94774652c)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，v1.9.5 版本将会支持 1Panel 重启后重置任务状态。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
