### ISSUE TITLE
[BUG]登录页刷新，先跳到首页再跳到登录页的问题。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3739]
### 1Panel 版本

v1.9.4

### 问题描述

如何解决在登录页刷新，先跳到首页再跳到登录页的问题。

### 重现步骤

登录页面刷新

### 期待的正确结果

想达到的效果是在登录页刷新，直接调回登录页。
> 不然会出现在登录页刷新页面，闪到首页再判断登录状态跳到登录页。

求大神解答。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本优化登录页刷新的问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.1-lts 版本已发布。
