### ISSUE TITLE
[BUG] armbian 下缓存组件 badger 异常 mremap size mismatch 

### ISSUE THREAD

**Issue by qwenode** [1Panel-dev/1Panel#3745]
### 1Panel 版本

1.9.4

### 问题描述

错误日志

`[2024-01-30 02:51:15] [INFO] init logger successfully  
[2024-01-30 02:51:15] [INFO] init db successfully  
[2024-01-30 02:51:15] [INFO] Migration run successfully  
panic: During db.vlog.open error: while truncating last value log file: /opt/1panel/cache/000004.vlog error: mremap size mismatch: requested: 470 got: 134217728

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/init/cache.Init()
	github.com/1Panel-dev/1Panel/backend/init/cache/cache.go:50 +0x130
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:40 +0x70
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func10(0x6a9cdf0, {0x6adbed0, 0x0, 0x0})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0x14
github.com/spf13/cobra.(*Command).execute(0x6a9cdf0, {0x6d0a118, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x73c
github.com/spf13/cobra.(*Command).ExecuteC(0x6a9cdf0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x418
github.com/spf13/cobra.(*Command).Execute(0x6a9cdf0)
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x1c
main.main()
	./main.go:23 +0x20
[2024-01-30 02:51:21] [INFO] init logger successfully  
[2024-01-30 02:51:21] [INFO] init db successfully  
[2024-01-30 02:51:21] [INFO] Migration run successfully  
panic: while opening memtables error: while opening fid: 8 error: while updating skiplist error: mremap size mismatch: requested: 20 got: 67108864

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/init/cache.Init()
	github.com/1Panel-dev/1Panel/backend/init/cache/cache.go:50 +0x130
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:40 +0x70
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func10(0x6a9cdf0, {0x6adbed0, 0x0, 0x0})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:22 +0x14
github.com/spf13/cobra.(*Command).execute(0x6a9cdf0, {0x6c0e140, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x73c
github.com/spf13/cobra.(*Command).ExecuteC(0x6a9cdf0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x418
github.com/spf13/cobra.(*Command).Execute(0x6a9cdf0)
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x1c
main.main()
	./main.go:23 +0x20`

### 重现步骤

系统:
发行版本 debian-12.2
内核版本 6.1.63-current-meson
系统类型 armv7l

安装1p即可
相关问题原因: https://blog.csdn.net/qq_34628724/article/details/123377861
1p这个组件应该是只有session在使用,目前登录未受影响,仅日志报错

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
经团队内部讨论，建议等待 badger 官方修复后再来更新。
