### ISSUE TITLE
redis 重启后设置的RDB 持久化规则回复成默认的

### ISSUE THREAD

**Issue by hsjgit** [1Panel-dev/1Panel#3747]
### 1Panel 版本

v1.9.4

### 问题描述

redis 重启后设置的RDB 持久化规则回复成默认的

### 重现步骤

数据库-->redis-->设置-->持久化
RDB 持久化设置成800 1 300 10 60 10000 保存设置成功
重启redis刚刚的RDB恢复成了900 1 300 10 60 10000。
配置文件没有修改
<img width="965" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/32933584/05fd8cc7-9df3-44d4-8dea-e72a9e24dafc">

**Comment by wanghe-fit2cloud** [comment]
麻烦提供一下安装的 redis 版本。

**Comment by hsjgit** [comment]
6.2.14

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。该问题已经在本地环境 v6.x 版本复现，我们会在近期版本修复并推送更新。
> 7.x 版本未复现。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
