### ISSUE TITLE
计划任务中的任务名称不能修改问题[FEATURE]

### ISSUE THREAD

**Issue by zxwmfcm** [1Panel-dev/1Panel#3752]
### 1Panel 版本

1.9.4

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/30642864/88997836-e20e-4d65-a52f-b0be5be015c5)
任务名称为什么设计成不能修改呢   可以改成能编辑的吗

**Comment by wanghe-fit2cloud** [comment]
备份文件路径等都和任务名称有关，目前暂不支持修改。
