### ISSUE TITLE
[FEATURE]opensuse系统安装不了

### ISSUE THREAD

**Issue by zxtsd-github** [1Panel-dev/1Panel#3753]
### 1Panel 版本

安装不了哪来的版本号

### 请描述您的需求或者改进建议

opensuse系统！！！！安装不了！！！
说实话opensuse相当老牌的服务器系统竟然不做适配真的是......

### 请描述你建议的实现方案

提供opensuse支持

**Comment by wanghe-fit2cloud** [comment]
> 安装不了哪来的版本号

版本号没有可以不提供，但是错误日志、安装截图等信息必须要提供。

> 如果是 docker 安装失败，可以尝试预先手动安装，之后再来执行 1Panel 在线安装脚本（会自动跳过安装 docker）

**Comment by zxtsd-github** [comment]
> > 安装不了哪来的版本号
> 
> 版本号没有可以不提供，但是错误日志、安装截图等信息必须要提供。
> 
> > 如果是 docker 安装失败，可以尝试预先手动安装，之后再来执行 1Panel 在线安装脚本（会自动跳过安装 docker）

问题已解决，手动安装docker,不过加个检测发行版的指令然后用自带的软件包管理器安装docker不行吗

**Comment by wanghe-fit2cloud** [comment]
> > > 安装不了哪来的版本号
> > 
> > 
> > 版本号没有可以不提供，但是错误日志、安装截图等信息必须要提供。
> > > 如果是 docker 安装失败，可以尝试预先手动安装，之后再来执行 1Panel 在线安装脚本（会自动跳过安装 docker）
> 
> 问题已解决，手动安装docker,不过加个检测发行版的指令然后用自带的软件包管理器安装docker不行吗

中短期会一直使用 docker 官方提供的安装脚本，暂时不考虑手动适配。
