### ISSUE TITLE
[BUG] 在redis的控制台中按下ctrl+c会导致浏览器卡死

### ISSUE THREAD

**Issue by XCWQW1** [1Panel-dev/1Panel#3754]
### 联系方式

xchome233@gmail.com

### 1Panel 版本

v1.9.4

### 问题描述

在 数据库>redis 下方的控制台中按下ctrl+c会导致浏览器卡死
使用linux下的firefox 118.0 (64 位) 和 chrome 117.0.5938.132（正式版本） （64 位）测试均会卡死
桌面环境为GNOME
Fedora 38发行版

### 重现步骤

在 数据库>redis 下方的控制台中按下ctrl+c

### 期待的正确结果

在 数据库>redis 下方的控制台中按下ctrl+c不会卡死浏览器

**Comment by ssongliu** [comment]
感谢反馈，这是因为在 redis 里面 ctrl+c 会退出 redis-cli，后续版本看看怎么样优化一下。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
