### ISSUE TITLE
[BUG]清理无法列出未标签镜像

### ISSUE THREAD

**Issue by refgd** [1Panel-dev/1Panel#3756]
### 1Panel 版本

1.9.4

### 问题描述

清理无法列出未标签镜像, 如下图
![image](https://github.com/1Panel-dev/1Panel/assets/2058651/b69d079a-3746-42c5-8c9d-1ec313f6b5d5)
![image](https://github.com/1Panel-dev/1Panel/assets/2058651/2cb8b224-bde9-4e3d-bd38-46307268ab37)

### 重现步骤

有未标签镜像

### 附加信息

另外希望加入显示docker 总大小记录的页面, 就是"docker system df"的输出内容, 还有里面的build cache能一键清理

**Comment by ssongliu** [comment]
感谢反馈，我们先在开发环境复现一下该问题。

> 就是"docker system df"的输出内容, 还有里面的build cache能一键清理  

这两个功能后续版本考虑是否支持。

**Comment by ssongliu** [comment]
感谢反馈，开发环境已经复现该问题，v1.9.5 版本解决。

> 就是 `docker system df` 的输出内容，还有里面的 `build cache` 能一键清理。

这两个功能后续版本考虑是否支持。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
