### ISSUE TITLE
[QUESTION]Node.js运行环境的build和start

### ISSUE THREAD

**Issue by riverai** [1Panel-dev/1Panel#3757]
### 请描述您的问题

我尝试在运行环境中部署一个Node.js项目。
这个项目若是运行，首先需要yarn build，然后是yarn start运行。

在1panel中，我如果选择运行环境，然后启动命令读取自package.jason，选择build，那么1panel很快会直接失去响应，直接卡死了（就是变成了服务器无响应）。

这时候我尝试直接选择start作为开局命令运行，总是会报错，大概是说没发现可用的build...

目前我是这样解决的：首先在后台用独立的Node.js环境完成了build，然后在1panel新建网站-运行环境-目录-直接选择“start”启动。

测试是可行的。

我想问下，是不是没办法从运行环境这里，让1panel完成build，然后切换启动命令，然后start？

我不知道我的理解是否正确？

不管是或者不是，希望下个版本都在1panel前台添加下说明。

**Comment by refgd** [comment]
我建议你写个bash, 判断build目录是否存在, 不存在就build, 存在就start, 执行命令就执行这个bash文件, 

当然你也可以直接用 "yarn build && yarn start" 来达到你的要求, 不过每次启动都要build一下就太多余了, 

而且不建议运行环境里build, 如果build不成功是可能造成无限重复的.
