### ISSUE TITLE
[FEATURE]防火墙需求建议

### ISSUE THREAD

**Issue by little-technician** [1Panel-dev/1Panel#3760]
### 1Panel 版本

1.94

### 请描述您的需求或者改进建议

希望防火墙配置可以支持配置ipset地址池，不然批量的地址配置过于繁琐麻烦。
如果使用了1panel，ufw或者firewall就无法进行自定义配置了，1panel配置的防火墙配置会覆盖掉我们自定义的配置

**Comment by ssongliu** [comment]
感谢反馈，这里的自定义配置指的是？

**Comment by little-technician** [comment]
![Snipaste_2024-01-31_14-46-36](https://github.com/1Panel-dev/1Panel/assets/53454049/843d5b44-e182-4ccd-b3ae-716dd98fe1ac)
像这样的自定义配置

**Comment by ssongliu** [comment]
> ![Snipaste_2024-01-31_14-46-36](https://private-user-images.githubusercontent.com/53454049/301064976-843d5b44-e182-4ccd-b3ae-716dd98fe1ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NTE3MDgsIm5iZiI6MTcwNjc1MTQwOCwicGF0aCI6Ii81MzQ1NDA0OS8zMDEwNjQ5NzYtODQzZDViNDQtZTE4Mi00Y2NkLWIzYWUtNzE2ZGQ5OGZlMWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAxMzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MDhjMzNjNDYxMzU5YjhiZTRiODI5MmE5NTU2YWIzMTc5OWZhNDQyMjc4MGI2Mjc0N2E1MDk5MDE4NzAwMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eZTXbpHZ65gjLQTj-wRx4px5fiwJrQU9_QuiU1v2dsg) 像这样的自定义配置

短期内没有支持的计划，望理解。

**Comment by little-technician** [comment]
好的，那能否先修复下，我们自己加入的规则，被1panel覆盖的问题
