### ISSUE TITLE
[BUG] 创建运行时环境网站，从PHP环境下勾选高级设置后切换到Node环境，高级设置选项输入框依然存在

### ISSUE THREAD

**Issue by 2509989976** [1Panel-dev/1Panel#3762]
### 1Panel 版本

1.9.4

### 问题描述

创建网站-运行环境 从PHP环境下勾选高级设置后切换到Node环境后，高级设置选项输入框依然存
![微信截图_20240131142205](https://github.com/1Panel-dev/1Panel/assets/100815534/22496155-8cda-4b46-9c5c-7a8b20e37378)

### 重现步骤

依次点击 网站-创建网站-运行环境-高级设置-切换类型为Node

### 期待的正确结果

应当保留高级设置选项或者同时清楚高级设置的输入框

**Comment by zhengkunwang223** [comment]
你是没有 `node` 运行环境，然后切换到了 `node` 运行环境是吗？

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
