### ISSUE TITLE
[BUG]创建网站时会卡死

### ISSUE THREAD

**Issue by barryu9** [1Panel-dev/1Panel#3765]
### 1Panel 版本

1.9.4

### 问题描述

阿里云轻量应用服务器 2C1G
Ubuntu 20.04 全新系统安装1Panel
进入面板后安装openresty+mysql （默认配置）
创建网站，一键部署halo（默认配置）
然后在浏览器访问网站后，会出现卡死的现象，远程连接、面板等均无法访问
阿里云重启指令下发也要等十多分钟，重启后情况依旧

### 重现步骤

两次同样的步骤都重现了

**Comment by kobi1108** [comment]
好像有這個情況 我自己用AWS 1c1G 一安裝halo整個就卡死了 ssh也永遠連綫錯誤
試了5次 發現自己用docker下載也會卡死 可能記憶體不夠..? 我換了GWP 2C2G就順利安裝了

**Comment by zhengkunwang223** [comment]
MySQL + Halo 比较吃内存，建议 2c 2g 起步。

**Comment by xllxll** [comment]
我也存在这种问题，安装HALO就死机，ssh也连接错误无法登陆。
这种问题只能升级配置吗？这个状况无法优化修复吗？
