### ISSUE TITLE
[BUG]Centos Stream 9 SSH登录日志为空

### ISSUE THREAD

**Issue by 520svip** [1Panel-dev/1Panel#3767]
### 联系方式

577813810@qq.com

### 1Panel 版本

1.9.4

### 问题描述

阿里云轻量服务器
系统：Centos Stream 9
日志里面的登录日志一直为空，SSH日志已开
图二为执行 journalctl -u sshd | grep "Accepted password for" 查询到SSH密码登录日志

### 重现步骤

腾讯云centos stream 9 每次安装都这样子

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/101090229/6b1697f8-11fd-483d-a73a-0fc88e869b56)
![image](https://github.com/1Panel-dev/1Panel/assets/101090229/3d14e778-be53-42d7-947e-176a784fd5ab)

**Comment by ssongliu** [comment]
感谢反馈，可以尝试手动安装一下  rsyslog 服务

**Comment by 520svip** [comment]
找到问题了，默认有安装rsyslog，但是没有开机自启，手动执行一下启动就好了
