### ISSUE TITLE
[BUG] 服务器支持 ipv4 ipv6 但是在创建面板成功后 无法通过 v6 访问 1panel

### ISSUE THREAD

**Issue by mobeicanyue** [1Panel-dev/1Panel#3779]
### 1Panel 版本

v1.9.4

### 问题描述

服务器支持 ipv4 ipv6 但是在创建面板成功后 无法通过 v6 访问 1panel

### 重现步骤

服务器支持 ipv4 ipv6 但是在创建面板成功后 无法通过 v6 访问 1panel
![image](https://github.com/1Panel-dev/1Panel/assets/81098819/3974c046-2d7a-45f5-9d07-651e75b3006a)

外网显示的是 v6 格式
内网显示为 v4
但其实两个都是服务器提供商处 提供的公网ip。
![image](https://github.com/1Panel-dev/1Panel/assets/81098819/e5f4d24e-5ab3-41fc-8e77-8626dd28d0a9)

### 期待的正确结果

v6 能在浏览器正常访问

**Comment by wanghe-fit2cloud** [comment]
1、`1pctl status` 命令查看 1Panel 服务运行状态并截图。
2、`netstat -ntlp | gerp 替换具体的端口` 命令查看 1Panel 端口绑定情况并截图。
3、`curl http://127.0.0.1:替换具体的端口/替换具体的安全入口` 命令查看具体返回结果并截图。

**Comment by mobeicanyue** [comment]
1.
![image](https://github.com/1Panel-dev/1Panel/assets/81098819/ade4b86e-50d8-48ce-921f-facd609616d5)
2.
![image](https://github.com/1Panel-dev/1Panel/assets/81098819/9325cd6b-b487-42f7-949c-4a227ff56cd0)
3.
![image](https://github.com/1Panel-dev/1Panel/assets/81098819/75528e99-acb3-4183-9121-2aa7206d4156)

其实全部都正常的，就是访问 v6 显示 502

**Comment by mobeicanyue** [comment]
还是我理解不到位。1panel 默认只创建 v4的地址访问，没有默认开启 v6吗

**Comment by wanghe-fit2cloud** [comment]
可以使用 `1pctl listen-ip ipv6` 命令将端口绑定至 tcp6，如图 ：
<img width="863" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/20ee8b75-7b32-4ab9-b353-c9af7621f673">

**Comment by mobeicanyue** [comment]
也就是说在有v4 的情况下 是不会绑定 v6 的吗。除非是纯 v6环境

**Comment by wanghe-fit2cloud** [comment]
是的，需要手动切换端口绑定。

**Comment by CyrusCN** [comment]
老铁，46双栈的机，但是v4是甲骨文的内网路由ip,但是我正常用nginx监听v4 443是能被公网访问的，现在面板通过公网IP进不来，但是通过vscode 端口转发localhost,还能访问。

**Comment by CyrusCN** [comment]
其他通过面板建立的容器正常被访问，就是面板本身不能被外部访问，防火墙没有，甲骨文路由全0

**Comment by wanghe-fit2cloud** [comment]
> 其他通过面板建立的容器正常被访问，就是面板本身不能被外部访问，防火墙没有，甲骨文路由全0

参考 https://github.com/1Panel-dev/1Panel/issues/4394

**Comment by CyrusCN** [comment]
> > 其他通过面板建立的容器正常被访问，就是面板本身不能被外部访问，防火墙没有，甲骨文路由全0
> 
> 参考 #4394

谢谢
