### ISSUE TITLE
[FEATURE] 请在应用商店添加AdGuardHome。Please add AdGuardHome in app store.

### ISSUE THREAD

**Issue by ValentinLiu15** [1Panel-dev/1Panel#3786]
### 1Panel 版本

v1.9.4

### 请描述您的需求或者改进建议

请在应用商店添加AdGuardHome。
AdGuardHome 同时支持 http/https（80/443）上的服务，因此建议在 docker 中运行，同时支持直接和 Web 服务器关联

**Comment by wanghe-fit2cloud** [comment]
该应用已经上架应用商店，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/2ff80f35-a8a3-4150-b14f-f03d892c35c2)
