### ISSUE TITLE
[BUG]网站日志提示服务内部错误: bufio.Scanner: token too long

### ISSUE THREAD

**Issue by R0A1NG** [1Panel-dev/1Panel#3789]
### 联系方式

E0tk1

### 1Panel 版本

v1.9.4

### 问题描述

部分网站点击日志时报错
<img width="835" alt="1706843552450" src="https://github.com/1Panel-dev/1Panel/assets/66672984/a9263258-1cdc-40ba-9995-8ea9eab31f2e">
这里筛选出有问题的日志，日志中存在该文件内的内容就会报错
[access.log](https://github.com/1Panel-dev/1Panel/files/14134470/access.log)

### 重现步骤

部分网站点击日志时报错

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by zhengkunwang223** [comment]
日志中是你接口的请求体吗？用了 Unicode 编码吗？

**Comment by R0A1NG** [comment]
> 日志中是你接口的请求体吗？用了 Unicode 编码吗？

是请求体，这个是搭建的ChatGPT Web的日志，自定义日志加上了请求体

**Comment by zhengkunwang223** [comment]
> > 日志中是你接口的请求体吗？用了 Unicode 编码吗？
> 
> 是请求体，这个是搭建的ChatGPT Web的日志，自定义日志加上了请求体

好的 我们试一下

**Comment by wanghe-fit2cloud** [comment]
v1.10.1-lts 版本已发布。
