### ISSUE TITLE
[FEATURE]是否可以同一版本创建多个PHP运行环境

### ISSUE THREAD

**Issue by linshuboy** [1Panel-dev/1Panel#3791]
### 1Panel 版本

1.9.4

### 请描述您的需求或者改进建议

同一版本创建多个PHP运行环境,需求是我想在同一台主机上部署测试和正式环境,测试环境上使用xdebug,正式环境使用opcache,都使用同一个PHP版本

**Comment by wanghe-fit2cloud** [comment]
网站使用同一个PHP容器的讨论，统一汇总到该 issue #2405

**Comment by linshuboy** [comment]
> 网站使用同一个PHP容器的讨论，统一汇总到该 issue #2405

我这个问题和目标问题不一样,我是想为同一个版本的PHP创建多个环境,比如说一个环境用于生产,一个环境用于测试
