### ISSUE TITLE
[FEATURE]密码的验证规则添加 ")" 

### ISSUE THREAD

**Issue by linshuboy** [1Panel-dev/1Panel#3792]
### 1Panel 版本

1.9.4

### 请描述您的需求或者改进建议

应用安装的时候有一些需要指定密码,密码的验证规则过于简单了,降低了密码的安全性

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，由于我们在后端防止命令注入处有该特殊字符，所有在安装应用设置密码时还不能支持 `)`，望理解。
