### ISSUE TITLE
[BUG]Dark Mode下应用详情的样式问题

### ISSUE THREAD

**Issue by ayuanlmo** [1Panel-dev/1Panel#3793]
### 联系方式

ayuanlmo@outlook.com

### 1Panel 版本

v1.9.5

### 问题描述

如图：
![image](https://github.com/1Panel-dev/1Panel/assets/50331004/40172bc0-b2e9-472a-8f59-ba0daba47b51)

### 重现步骤

主题颜色切换至：暗黑

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本优化上述显示问题。

**Comment by wanghe-fit2cloud** [comment]
v1.9.6 版本已发布。
