### ISSUE TITLE
[QUESTION] 当一个 docker-compose.yml 文件中存在多个 services 时， 1panel 无法正确处理？

### ISSUE THREAD

**Issue by qyl27** [1Panel-dev/1Panel#3794]
### 请描述您的问题

用于复现的样例： [qyl27/1panel-appstore-local+527fd11](https://github.com/qyl27/1panel-appstore-local/blob/527fd11753007f21e2cf84632a525261b9272276/local/forgejo-runner/3.3.0/docker-compose.yml)  
预期行为：按照 docker compose 的依赖关系，`docker-in-docker` 和 `runner-register` 运行成功之后启动 `runner-daemon`。  
实际行为：`docker-in-docker` 被重命名成了我为 app 设定的名称，而其他的服务因为找不到依赖而失败了。

**Comment by wanghe-fit2cloud** [comment]
当前版本为了防止 ServiceName 重复，就把 ServiceName 修改为了应用名称。
> 后续版本会针对单 compose 多服务的场景进行优化，不修改 ServiceName。

**Comment by wanghe-fit2cloud** [comment]
v1.9.6 版本已发布。
