### ISSUE TITLE
[BUG] 设定安全入口后，未登录时访问面板会被自动重定向到安全入口的地址。退出登录并没有完全退出。

### ISSUE THREAD

**Issue by qyl27** [1Panel-dev/1Panel#3795]
### 1Panel 版本

1.9.5

### 问题描述

设定安全入口后，未登录时访问面板会被自动重定向到安全入口的地址。

### 重现步骤

1. 设定安全入口
2. 登出
3. 访问不带安全入口的面板页面

### 期待的正确结果

应显示一个错误页面，或者403。

**Comment by Akizon77** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/64686663/2730e892-f53e-4fb0-9fa4-b15fbd677d73)
因为只要成功登录过，就有cookie，所以 `重现步骤` 中应额外清除Cookies

**Comment by mobeicanyue** [comment]
很简单 浏览器缓存 你换个浏览器或者用手机打开就没有了

**Comment by qyl27** [comment]
所以退出功能未考虑到客户端的浏览器缓存吗？也就是说退出了并没有完全退出？  
那这不就是很严重的安全隐患？

**Comment by mobeicanyue** [comment]
这算不上什么安全隐患吧
你既然有缓存了多半是你信得过的机器登陆的
而你不想留痕就用浏览器无痕模式就行了
就像我们都知道http不安全 但在内网没必要用https

**Comment by ssongliu** [comment]
感谢反馈，这里只是将登陆之后将安全入口那串存到了浏览器缓存，为了方便下次登陆的时候，直接跳到正常的登陆界面而不是需要再次输入安全入口码，退出之后实际上 cookie 那些信息都是清除了的。
