### ISSUE TITLE
[BUG]移动设备视图下，容器名称丢失

### ISSUE THREAD

**Issue by RedwindA** [1Panel-dev/1Panel#3798]
### 1Panel 版本

v1.9.5

### 问题描述

移动设备视图下，容器名称丢失

### 重现步骤

使用手机，或者PC浏览器的开发者工具调整视图为移动端
PC端容器名称的列存在：
![image](https://github.com/1Panel-dev/1Panel/assets/128586631/ac8d0f96-d166-4cef-a500-f9a5c7f3fa16)

移动端视图。容器名称的列消失，第一列变为了镜像名称（滚动条已拉到最左端）：
![image](https://github.com/1Panel-dev/1Panel/assets/128586631/d6a0ecf1-fc21-4961-a707-4384b8bcb12d)

**Comment by ssongliu** [comment]
感谢反馈，开发环境已经复现该问题，下个小版本解决。

**Comment by wanghe-fit2cloud** [comment]
v1.9.6 版本已发布。
