### ISSUE TITLE
[BUG]主机防火墙无法正常显示ipv6规则

### ISSUE THREAD

**Issue by zypluckyphoenix** [1Panel-dev/1Panel#3799]
### 1Panel 版本

v1.9.5

### 问题描述

主机->防火墙->端口规则
![image](https://github.com/1Panel-dev/1Panel/assets/98106970/c18ca9b8-dab6-4e09-8263-83a40723b9ca)

### 重现步骤

ufw shell 显示
![Uploading image.png…]()

**Comment by zypluckyphoenix** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/98106970/c5dca2f6-60e1-4c25-a1e7-567f6dade920)

**Comment by wanghe-fit2cloud** [comment]
防火墙规则是 IPv4 与 IPv6 一起屏蔽的，只是在页面中没有体现出来，可以通过具体的命令查询。

**Comment by zypluckyphoenix** [comment]
我知道，就是这样子看着难受，而且应该归类为ip规则，不应该显示在端口规则里

**Comment by wanghe-fit2cloud** [comment]
目前计划在 v2.0 版本重构时优化。
