### ISSUE TITLE
[BUG]暗黑模式下应用商店应用名颜色不对

### ISSUE THREAD

**Issue by hahaha3542** [1Panel-dev/1Panel#3800]
### 联系方式

a15906646540@163.com

### 1Panel 版本

1.9.5

### 问题描述

![屏幕截图 2024-02-03 163920](https://github.com/1Panel-dev/1Panel/assets/69064412/d103d834-9040-4e2d-b34c-1bf1200acfea)
如图，软件标题依然显示为黑色 ，而不是暗黑模式理应的白色。

### 重现步骤

目前设置是锁定暗黑模式，不自动检测

### 期待的正确结果

以白色显示应用名
![屏幕截图 2024-02-03 164041](https://github.com/1Panel-dev/1Panel/assets/69064412/79986a12-ae2e-45aa-9660-7b95b2522882)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述显示问题。

**Comment by wanghe-fit2cloud** [comment]
v1.9.6 版本已发布。
