### ISSUE TITLE
[BUG] 更新vaultwarden 后 compose 文件的 environment 参数丢失

### ISSUE THREAD

**Issue by mobeicanyue** [1Panel-dev/1Panel#3801]
### 1Panel 版本

v1.9.5

### 问题描述

更新vaultwarden 后 compose 文件的 environment 参数丢失
不知道是vaultwarden还是1panel更新导致的 都是昨天下午更新的

### 重现步骤

更新vaultwarden 后 compose 文件的 environment 参数丢失 就是设置管理员密码那几行

**Comment by wanghe-fit2cloud** [comment]
请问是在安装应用时，手动添加的环境变量吗？
> 当前版本在升级时会覆盖 compose 文件，后续版本会针对上述场景作出优化。

**Comment by mobeicanyue** [comment]
> 请问是在安装应用时，手动添加的环境变量吗？
> 
> > 当前版本在升级时会覆盖 compose 文件，后续版本会针对上述场景作出优化。

对的 因为也没有别的办法添加 只能手动

**Comment by wanghe-fit2cloud** [comment]
> > 请问是在安装应用时，手动添加的环境变量吗？
> > > 当前版本在升级时会覆盖 compose 文件，后续版本会针对上述场景作出优化。
> 
> 对的 因为也没有别的办法添加 只能手动

当前版本还是需要手动修改来添加环境变量等 compose 配置。
计划在后续版本应用升级时支持版本比对功能。

**Comment by mobeicanyue** [comment]
> 当前版本还是需要手动修改来添加环境变量等 compose 配置。 计划在后续版本应用升级时支持版本比对功能。

嗯好，希望可以解决。也可以，在升级的时候，读取用户配置备份然后恢复

**Comment by mobeicanyue** [comment]
或者这个议题应该改成：“支持手动设置 environment”
类似于这样
![image](https://github.com/1Panel-dev/1Panel/assets/81098819/d7ae107b-74db-4189-b0ba-56c734df4f10)
在更新完毕的时候可以覆盖变量，不怕丢失

**Comment by wanghe-fit2cloud** [comment]
应用升级时兼容之前修改的 compose 文件的需求，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/2826
