### ISSUE TITLE
[BUG]备份账号腾讯云COS的编辑无法打开...

### ISSUE THREAD

**Issue by ChishFoxcat** [1Panel-dev/1Panel#3802]
### 联系方式

chish@vip.qq.com

### 1Panel 版本

v1.9.5

### 面板设置 > 备份账号
- 腾讯云COS: 编辑按钮点击后无法唤出编辑菜单
### 计划任务
- 创建计划任务: 计划周期上的每小时上的单位是分钟(不知道是不是就这么写的,但是他有点误导性)
<img width="641" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/76027184/805ff704-b1fa-4419-8c5d-a5ba6590a8ba">

### 重现步骤

- 添加腾讯云COS账号后点击编辑
- 创建计划任务中计划周期上每小时单位

### 期待的正确结果

- 能打开其编辑菜单
- 每小时单位是分钟,对我来说比较误解,希望是小时为单位

**Comment by ssongliu** [comment]
感谢反馈。
1. 本地未能复现备份账号无法打开的问题，可以尝试删除之后重新绑定，再看看是否正常；
2. 每小时指的是每小时多少分钟执行，而不是每隔 N 时，可以根据需要选择。

**Comment by ChishFoxcat** [comment]
> 感谢反馈。
> 
> 1. 本地未能复现备份账号无法打开的问题，可以尝试删除之后重新绑定，再看看是否正常；
> 2. 每小时指的是每小时多少分钟执行，而不是每隔 N 时，可以根据需要选择。

- 删除并重新添加后可以点开编辑
- 每小时多少分钟执行是不是每到一个小时然后隔几分钟去运行,我理解了
