### ISSUE TITLE
[FEATURE]希望增加备份的代理功能

### ISSUE THREAD

**Issue by ChishFoxcat** [1Panel-dev/1Panel#3803]
### 1Panel 版本

v1.9.5

### 请描述您的需求或者改进建议

希望增加备份的代理功能,在使用OneDrive国际版备份,大陆网络下经常显示网络重置,所以希望增加代理功能
更多的还是在设置代理的时候能应用到不同的功能中,不仅是备份

### 请描述你建议的实现方案

- 工具箱
   - 代理
      - HTTP 代理
      - HTTPS 代理
      - 被应用项
         - 全局
         - 主机 - 文件 - 远程下载
         - 应用商店应用
         - 计划任务 (可以选择单个或多个任务)
         - 各种备份/快照备份

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们暂无计划支持在面板中设置代理功能，望理解。
> 如果是存在网络问题，您是否可以手动在 1Panel 服务器上配置上述代理。
