### ISSUE TITLE
[BUG] 1panel在线文本编辑器打开gbk编码文件乱码问题

### ISSUE THREAD

**Issue by zhuzhufen** [1Panel-dev/1Panel#3804]
### 联系方式

zhuzhufenw@foxmail.com

### 1Panel 版本

v1.9.5

### 问题描述

1panel在线文本编辑器打开gbk编码文件乱码

### 重现步骤

打开gbk编码文本文件，中文乱码

### 期待的正确结果

中文正常显示

**Comment by zyyfit** [comment]
您好，这种会显示乱码的文件现在应该是无法打开的，您方便提供一下您的文件和乱码截图吗

**Comment by zhuzhufen** [comment]
[data_tdcrgg.txt](https://github.com/1Panel-dev/1Panel/files/14155214/data_tdcrgg.txt)
![Dingtalk_20240204101457](https://github.com/1Panel-dev/1Panel/assets/45941639/9e7a193e-44ac-4159-8edc-83776b37a849)
![Dingtalk_20240204101543](https://github.com/1Panel-dev/1Panel/assets/45941639/b47ed38a-9463-456b-80a1-b5240906a657)

**Comment by zhuzhufen** [comment]
您好，分别是文件、通过1panel和宝塔面板打开文件的截图

**Comment by zyyfit** [comment]
收到，我们看一下怎么解决这个问题

**Comment by luckylu997** [comment]
同样问题，请教下，这个问题解决了吗

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
