### ISSUE TITLE
[BUG]可升级应用页面中，点击 `忽略升级` 后弹出页面显示异常。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3806]
### 1Panel 版本

v1.9.5

### 问题描述

![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/6ec5812a-b785-466a-b6e8-0313bab96272)

### 重现步骤

应用商店 - 可升级，点击 `忽略升级` 按钮即可复现。

### 期待的正确结果

去掉 `强制拉取镜像` 复选框已经描述信息。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述功能。

**Comment by wanghe-fit2cloud** [comment]
v1.9.6 版本已发布。
