### ISSUE TITLE
[FEATURE]ERROR: Unsupported distribution 'opencloudos'，Implement a solution to this situation

### ISSUE THREAD

**Issue by 2218084076** [1Panel-dev/1Panel#3807]
### 1Panel 版本

v1.9.4

### 请描述您的需求或者改进建议

[FEATURE]ERROR: Unsupported distribution 'opencloudos'，Implement a solution to this situation

**Comment by wanghe-fit2cloud** [comment]
1Panel 提供的安装脚本中，安装 docker 部分是引用的 docker 官方在线安装脚本。
上述报错是因为你使用的操作系统不在 docker 官方在线安装脚本支持的范围内，所以无法直接在线一键安装。

目前你需要先手动在服务器上安装并运行 docker，之后再来运行 1Panel 安装脚本。
此时一键安装脚本会自动忽略安装 docker 这步并继续来安装 1Panel。

**Comment by 2218084076** [comment]
ok，感谢您的回答，我在此后找到了腾讯的opencloudos的文档，上面有介绍该系统中docker的支持，以下是我找到的相关链接。
最后非常感谢您的指导！

https://docs.opencloudos.org/OCS/Virtualization_and_Containers_Guide/Docker_guide/
