### ISSUE TITLE
[BUG] AdGuardHome 安装后识别不到无线网卡

### ISSUE THREAD

**Issue by MC-1997** [1Panel-dev/1Panel#3810]
### 联系方式

1131733741@qq.com

### 1Panel 版本

1.9.5

### 问题描述

安装AdGuardHome后，仅能识别到有线网卡和虚拟网卡，无法识别无线网卡

### 重现步骤

操作环境：树莓派4B 8G，操作系统：debian

### 期待的正确结果

希望能够识别到无线网卡

**Comment by wanghe-fit2cloud** [comment]
应该是应用具体配置问题吧，可以先到 AdGuardHome 官方查询一下相关问题的解决方案。
如果支持在应用安装时配置，我们后续版本会将具体设置推送至正式仓库。
> 上述应用的具体使用与配置问题，我们也不清楚，望理解。

**Comment by MC-1997** [comment]
我通过AdGuardHome官网脚本安装，均可正常识别到所有网卡

**Comment by MC-1997** [comment]
我觉得应该是Docker创建容器导致的找不到网卡

**Comment by wanghe-fit2cloud** [comment]
我们是采用的容器化方案部署的 AdGuardHome 应用。
你可以先采用官方提供的 `docker run` 命令在本地起服务，查看一下是否正常，参考文档：
https://github.com/AdguardTeam/AdGuardHome/wiki/Docker

**Comment by wanghe-fit2cloud** [comment]
先关闭该 issue 了，如果在官方找到相关问题，我们可以在这里继续讨论
