### ISSUE TITLE
[QUESTION]反代1panel 导致 无限转圈

### ISSUE THREAD

**Issue by d4renk** [1Panel-dev/1Panel#3811]
我想要通过auth_basic功能增加一层密码保护，防止被fofa等扫描工具发现。我将1panel反向代理到了1panel.example.com这个域名上。输入密码登录后，出现了无限重定向的问题。
看了下issues https://github.com/1Panel-dev/1Panel/issues/239 老版本似乎是支持的
版本是 v1.9.5

**Comment by wanghe-fit2cloud** [comment]
麻烦再发一下无限重定向问题的录屏。
> 刚在本地环境测试未复现上述问题。

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/c53b470f-6f29-4b84-92de-1794bf30adda)
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/ef54de35-55a8-4a74-9f34-be900b362425)

**Comment by d4renk** [comment]
流量太大了 触发了nginx并发限制 直接丢了这两请求js app-df08109d.js monitor-3183283c.js 配置下白名单就好了

**Comment by hongyf233** [comment]
请问解决方法需要怎么操作，碰到同样的问题，小白选手不会操作
