### ISSUE TITLE
[BUG]文件管理界面使用鼠标滚轮滑动文件列表出现卡顿

### ISSUE THREAD

**Issue by yumumg** [1Panel-dev/1Panel#3812]
### 1Panel 版本

1.9.5

### 问题描述

从1.7.4升级至1.9.5版本后，在文件管理界面使用鼠标滚轮滑动文件列表出现卡顿。约15条左右偶发，约30条以上较频发。等待后有缓解

### 重现步骤

在Windows端的edge浏览器（121.0.2277.9）中，在文件管理界面使用鼠标滚轮滑动条数大于15条的文件列表。

https://github.com/1Panel-dev/1Panel/assets/79494969/c1b39912-4114-49e6-8ca4-9a1557afa0b3

### 期待的正确结果

滑动不卡顿

### 附加信息

在1.7.4及1.5.0未出现此情况

**Comment by wanghe-fit2cloud** [comment]
我们在本地环境暂时无法复现上述问题。
> 文件列表最多支持 100条/页，如果 `滑动不卡顿` 的话，鼠标滚轮理论上也不会出现上述问题。

你目前可以更换一下浏览器，看是否还存在上述反馈的问题。
也可以进入微信交流群添加 `王贺` 好友，我们远程你的环境定位一下问题。
