### ISSUE TITLE
[BUG]应用安装失败

### ISSUE THREAD

**Issue by YangHaoNing-CN** [1Panel-dev/1Panel#3814]
### 联系方式

admin@yserver.ink

### 1Panel 版本

v1.9.5

### 问题描述

系统是ubuntu-server-23.10，初步推测是ubuntu-server安装过程中勾选docker时使用snap安装。https://bbs.fit2cloud.com/t/topic/1334

### 重现步骤

安装系统时勾选docker，到1panel安装软件

### 相关日志输出

```shell
stderr: stat /opt/1panel/apps/openresty/openresty/docker-compose.yml: no such file or directory
```

**Comment by zhengkunwang223** [comment]
当前仅支持 systemd 管理的 docker
