### ISSUE TITLE
[QUESTION]比较疑惑的一个问题，关于Node 运行环境

### ISSUE THREAD

**Issue by Q2297045667** [1Panel-dev/1Panel#3815]
### 请描述您的问题

在已有的应用上创建网站
![image](https://github.com/1Panel-dev/1Panel/assets/42416195/4fb9092b-0716-4372-bc35-056515b72f2b)
选择Node的运行环境提示为空
![image](https://github.com/1Panel-dev/1Panel/assets/42416195/7bc2c04b-b388-4112-8404-b2d75bfd3a18)
那么OK去创建Node的运行环境
![image](https://github.com/1Panel-dev/1Panel/assets/42416195/587f2a02-4ae6-4017-aff8-d430e1152614)
起初我以为是上传源码是Node的，上传之后发现提示《package.json文件不存在》
这时我才意识到是项目的源码，去https://1panel.cn/docs/user_manual/websites/node  看发现果然是
如果使用项目源码那么就不能使用已安装的应用，
那么问题来了：
为什么不能直接在《应用商店》安装的应用上直接使用Node环境？
为什么不能直接在创建网站的时候直接使用以安装的Node版本
或许可以增加一个选择

**Comment by zhengkunwang223** [comment]
我们是容器化安装 应用商店的应用都有自己的环境 不需要 node 
node 运行环境是提供一个 node.js 容器，然后启动你的源码
至于你说的那种 应该是在服务器直接安装 node 环境 
1Panel 不支持这种

**Comment by Q2297045667** [comment]
> 我们是容器化安装 应用商店的应用都有自己的环境 不需要 node node 运行环境是提供一个 node.js 容器，然后启动你的源码 至于你说的那种 应该是在服务器直接安装 node 环境 1Panel 不支持这种

网站创建时只能使用PHP环境，不能使用node，但是实际上还是应用自带的环境是这个意思吗？

**Comment by d4renk** [comment]
他的意思应该
每个应用都是容器 每个容器都是独立的环境(nodejs没有安装在你宿主机上 在容器里)
如果你要创建node应用 应该创建nodejs容器并启动你的源码
再使用反向代理公开你的应用

**Comment by Q2297045667** [comment]
> 他的意思应该 每个应用都是容器 每个容器都是独立的环境(nodejs没有安装在你宿主机上 在容器里) 如果你要创建node应用 应该创建nodejs容器并启动你的源码 再使用反向代理公开你的应用

主要是我不想使用wiki.js的环境自带的node，看了下他直接自带了一个node版本
并非是独立的，而是直接连node环境都打包在一起了，我不想使用他带的node

**Comment by d4renk** [comment]
你用的是源码部署还是docker部署？
源码部署的话 可以直接在宿主机上部署
docker部署 你不想用他的nodejs 你就进容器 手动装一个 添加好环境变量
你如果想docker部署并使用宿主机nodejs 就把宿主机nodejs映射进docker 但这样会出很多问题

**Comment by Q2297045667** [comment]
> 你用的是源码部署还是docker部署？ 源码部署的话 可以直接在宿主机上部署 docker部署 你不想用他的nodejs 你就进容器 手动装一个 添加好环境变量 你如果想docker部署并使用宿主机nodejs 就把宿主机nodejs映射进docker 但这样会出很多问题

呃，我的意思是在安装的时候可以给用户一个选择，可以选择自带的环境或者自己安装的环境
