### ISSUE TITLE
[BUG]创建多周期计划任务，部分周期的初始化值错误。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3818]
### 1Panel 版本

v1.9.5

### 问题描述

创建多周期计划任务，`每月`、`每隔N日`、`每隔N秒`的初始化值错误。
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/a74c8b7c-fad5-4fb6-91fa-b0fbbe06ff00)

### 重现步骤

创建计划任务，周期选择`每月`、`每隔N日`、`每隔N秒`即可复现。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.9.6 版本已发布。
