### ISSUE TITLE
[FEATURE]希望添加反代网站的密码访问功能

### ISSUE THREAD

**Issue by bulesky89857** [1Panel-dev/1Panel#382]
### 1Panel 版本

v1.02

### 请描述您的需求或者改进建议

访问反向代理的网站，希望添加一个密码验证功能。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本会支持 auth_basic 账号密码登录功能。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
