### ISSUE TITLE
[BUG] Umami 安装出错

### ISSUE THREAD

**Issue by mobeicanyue** [1Panel-dev/1Panel#3822]
### 1Panel 版本

v1.9.5

### 问题描述

![image](https://github.com/umami-software/umami/assets/81098819/c4942284-9977-40da-b73a-105e787e558a)
![image](https://github.com/umami-software/umami/assets/81098819/53a20df6-3999-4fd6-ae30-06d9cae53357)

### 重现步骤

我前天通过面板 从 2.4.1升级 umami 到 2.9.0, 完成后发现 首页umami直接无法打开，随后发现了报错
![image](https://github.com/umami-software/umami/assets/81098819/c4942284-9977-40da-b73a-105e787e558a)
![image](https://github.com/umami-software/umami/assets/81098819/53a20df6-3999-4fd6-ae30-06d9cae53357)

我以为是升级导致的数据库崩了还是什么的，随即使用备份进行恢复，遂发现，虽然可以进入 umami.example.com/dashboard
但是 umami.example.com 的报错还是 
![image](https://github.com/umami-software/umami/assets/81098819/c4942284-9977-40da-b73a-105e787e558a)

我想这可能应该不是 umami 本体的问题，因为他们最后一个 commit 已经是两个月前了，而我没有在 open 的 issue 里面发现相关问题。

然后我尝试重新安装。下载了备份并且从面板点击 删除备份来重新安装
最后还是没有解决

**Comment by wanghe-fit2cloud** [comment]
安装 Umami 选择的是 MySQL 8 还是 PostgreSQL 数据库，我们先尝试在本地环境复现一下问题。

**Comment by mobeicanyue** [comment]
> 安装 Umami 选择的是 MySQL 8 还是 PostgreSQL 数据库，我们先尝试在本地环境复现一下问题。

MySQL8，也是在商店安装了

**Comment by wanghe-fit2cloud** [comment]
到容器列表查看一下 Umami 日志，有没有 error 相关内容
> 刚在本地环境没有复现上述问题。

**Comment by mobeicanyue** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/81098819/8648da87-f18f-4b03-966b-062a42f12fff)

容器日志如下
```
yarn run v1.22.19
$ npm-run-all check-db update-tracker start-server
$ node scripts/check-db.js
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database version check successful.
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "umami_5nhd43" at "mysql:3306"

3 migrations found in prisma/migrations

Applying migration `01_init`
Applying migration `02_report_schema_session_data`
Applying migration `03_metric_performance_index`

The following migrations have been applied:

migrations/
  └─ 01_init/
    └─ migration.sql
  └─ 02_report_schema_session_data/
    └─ migration.sql
  └─ 03_metric_performance_index/
    └─ migration.sql
      
All migrations have been successfully applied.

✓ Database is up to date.
$ node scripts/update-tracker.js
$ node server.js
   ▲ Next.js 14.0.4
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000

 ✓ Ready in 172ms
```

**Comment by wanghe-fit2cloud** [comment]
没有查看到任何异常，建议将上述问题反馈到 Umami 官方 Issue。
