### ISSUE TITLE
[FEATURE] 希望增加对 apijson 的深度集成

### ISSUE THREAD

**Issue by obj404** [1Panel-dev/1Panel#3823]
### 1Panel 版本

1.9.5

### 请描述您的需求或者改进建议

开源中国[GVP]项目，[腾讯开源]
https://gitee.com/Tencent/APIJSON
https://github.com/Tencent/APIJSON

🏆 零代码、全功能、强安全 ORM 库 🚀
后端接口和文档零代码，前端(客户端) 定制返回 JSON 的数据和结构

### 请描述你建议的实现方案

对后端的api请求，非常常见，所以希望官方封装支持一下
因为项目只提供源码的方式，对普通用户进行部署有很大的难度

**Comment by obj404** [comment]
这个项目，也是JAVA,官方集成的HALO也是java，应该会比较简单

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1Panel 应用商店所有应用均采用容器化方案，并直接使用应用官方提供的 Docker 镜像。
鉴于团队资源有限，暂不考虑自行维护第三方应用的情况，望理解。
