### ISSUE TITLE
[FEATURE] 关于计划任务

### ISSUE THREAD

**Issue by tianmiao8152** [1Panel-dev/1Panel#3824]
### 1Panel 版本

v1.9.5

### 请描述您的需求或者改进建议

希望在计划任务内添加对容器的控制，如定期重启容器，定时打开容器，定时关闭容器等容器相关功能

**Comment by d4renk** [comment]
这写一个shell 就行
不会的 就问gpt生成shell

**Comment by wanghe-fit2cloud** [comment]
> 这写一个shell 就行 不会的 就问gpt生成shell

是的，可以通过创建 `Shell 类型`计划任务来实现上述需求。
需要结合 `docker start stop` 等具体命令。
