### ISSUE TITLE
[BUG] 备份目录日志错误

### ISSUE THREAD

**Issue by refgd** [1Panel-dev/1Panel#3826]
### 1Panel 版本

1.9.5

### 问题描述

1. 显示的时间有问题. (附图片1)
2. 下面显示7条记录, 但只出现了6条. (附图片1)
3. 那个262G的备份应该是备份出错了, 但是显示262G, 应该显示"失败"或什么 (附图片1)
4. 按照时间推算,应该有两次备份失败, 不知道为什么报告里就显示了一次 (附报告图片)
5. 我查看了失败的报告,只显示了日期, 哪里能查看详细失败原因吗?

图片1:
![image](https://github.com/1Panel-dev/1Panel/assets/2058651/1e528f48-57b7-40e1-9d2f-43cda5c6ef32)

报告截图:
![image](https://github.com/1Panel-dev/1Panel/assets/2058651/b572477f-da7c-4bb0-8b0b-fbe75e6d6c96)

Onedrive 备份目录截图:
![image](https://github.com/1Panel-dev/1Panel/assets/2058651/cba3dab5-e179-4df1-a73a-70d9caca2854)

### 重现步骤

就是日常备份

**Comment by ssongliu** [comment]
感谢反馈，麻烦添加一下我，我远程看看
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/2ee31113-f2c6-4c8e-b139-7fbe6a19a405)

**Comment by wanghe-fit2cloud** [comment]
v1.9.6 版本已发布。
