### ISSUE TITLE
[QUESTION]Mysql安装后IO异常

### ISSUE THREAD

**Issue by IhaveBB** [1Panel-dev/1Panel#3828]
### 请描述您的问题

阿里1H1G 轻量服务器安装Mysql后IO异常
原因不清楚，但可多次复现
![image](https://github.com/1Panel-dev/1Panel/assets/115210411/c645aacb-20a6-4c34-8cf2-3d171b4e9a02)

**Comment by wanghe-fit2cloud** [comment]
小内存等轻量服务器首选 MySQL 5.7.x 或者 MySQL 5.6.x 版本，不推荐 MySQL 8
