### ISSUE TITLE
建议修改 【别名】 后，【左上角的图片名字】也同步进行变更。 以便防止

### ISSUE THREAD

**Issue by gonboy** [1Panel-dev/1Panel#3830]
### 1Panel 版本

1.9.5

### 请描述您的需求或者改进建议

建议修改 【别名】 后，【左上角的图片名字】也同步进行变更。 以便防止误操作

### 请描述你建议的实现方案

建议修改 【别名】 后，【左上角的图片名字】也同步进行变更。 以便防止

**Comment by wanghe-fit2cloud** [comment]
暂不支持自定义左上角图片、文字，望理解。
