### ISSUE TITLE
[BUG]反代到3001端口可以正常訪問，開啟HTTPS無法訪問

### ISSUE THREAD

**Issue by himicoswilson** [1Panel-dev/1Panel#384]
### 联系方式

WeChat Group - BOT

### 1Panel 版本

1.0.2

### 问题描述

證書是用 Acme 申請的，設置如截圖。
Cloudflare 僅僅解析了 DNS ，沒開小雲朵。

### 附加信息

![CleanShot 2023-03-23 at 16 26 54@2x](https://user-images.githubusercontent.com/92566148/227145547-1b4252aa-8544-4823-bb32-9cb6d76a6db9.png)

</br >
</br >
</br >

![CleanShot 2023-03-23 at 16 28 30@2x](https://user-images.githubusercontent.com/92566148/227145826-8eac053c-f49d-4728-acfb-908a6c67a21b.png)

**Comment by bulesky89857** [comment]
挂cdn了吗？

**Comment by HimiCos** [comment]
我是華為雲的機子應該不用掛吧

**Comment by HimiCos** [comment]
443 端口沒開，幹
