### ISSUE TITLE
[FEATURE]应用商店增加支持的系统类型检测

### ISSUE THREAD

**Issue by Whbgz** [1Panel-dev/1Panel#3841]
### 1Panel 版本

1.9.6

### 请描述您的需求或者改进建议

有些镜像无法再其它架构系统使用，希望在应用商店添加支持的系统架构类型显示

### 请描述你建议的实现方案

在应用商店添加支持的系统架构类型显示

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
应用区分架构的相关问题的讨论，统一汇总到该 issue #3026
