### ISSUE TITLE
[BUG]在nginx配置文件中不支持lua模块

### ISSUE THREAD

**Issue by liaoxiansheng** [1Panel-dev/1Panel#3843]
### 联系方式

164418960@qq.com

### 1Panel 版本

v1.9.5

### 问题描述

在nginx配置文件中不支持lua模块，即使删除了也是一直提示服务器错误。只能删除网站 重新添加 才能恢复

### 重现步骤

添加网站，然后在nginx配置文件中添加lua模块   过一会 就提示服务器错误

**Comment by zhengkunwang223** [comment]
感谢反馈 后续版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.10.0-lts 版本已发布。
