### ISSUE TITLE
[FEATURE]应用商品推荐帕鲁服务器管理工具

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3846]
### 1Panel 版本

v1.9.6

### 请描述您的需求或者改进建议

[palworld-server-tool](https://github.com/zaigie/palworld-server-tool)
支持 docker 容器化安装，感觉很配 1Panel，用起来也很方便。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本支持上述应用。

**Comment by wanghe-fit2cloud** [comment]
v1.10.0-lts 版本已发布。
