### ISSUE TITLE
[BUG] 拖拽方式上传文件夹

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#3848]
### 联系方式

交流群5 9a6ac...

### 1Panel 版本

最新

### 问题描述

通过拖拽的方式上传文件夹，当文件夹内容比较多时，上传的内容不全。该文件夹有131个文件，目前只上传了100个文件
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/25893e5d-01d0-4131-840b-5e351d0620e7)
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/df8b07b4-e8bf-4d33-8fbf-ac6364d311b6)

### 重现步骤

如上图

### 期待的正确结果

正确上传所有文件

**Comment by ssongliu** [comment]
感谢反馈，我们先本地复现一下该问题

**Comment by wanghe-fit2cloud** [comment]
刚在本地复现了上述问题，我们会在后续版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.0-lts 版本已发布。
