### ISSUE TITLE
1panel可以自定义背景

### ISSUE THREAD

**Issue by acleverfreebird** [1Panel-dev/1Panel#3849]
### 1Panel 版本

1.9.6

### 请描述您的需求或者改进建议

1panel可以自定义背景，例如png,jpg,gif等。

**Comment by acleverfreebird** [comment]
可以像bt面板一样
https://gitee.com/Vincent1230/BTPanel-beautification

**Comment by ssongliu** [comment]
感谢反馈，我们中短期内暂无支持上述需求的计划，望理解。
