### ISSUE TITLE
[BUG]存量数据库信息不能加载（数据库通过源码包形式安装）

### ISSUE THREAD

**Issue by RebornForPower** [1Panel-dev/1Panel#3850]
### 1Panel 版本

v1.9.6

### 问题描述

在安装1Panel之前服务器已安装了MySQL（源码包安装），在安装1Panel后“数据库”页面读提示“未检测到 数据库服务 (MySQL 或 MariaDB) ,请进入应用商店点击安装！”

1Panel数据库默认的安装形式是容器安装吧，希望能兼容到存量用户通过源码包安装MySQL的需要，让这部分用户的1Panel数据库页面也能显示对应的数据库信息。

### 重现步骤

先通过源码包安装MySQL，再安装1Panel，点击进入“数据库”页面，提示“未检测到 数据库服务 (MySQL 或 MariaDB) ,请进入应用商店点击安装！”

### 期待的正确结果

应该显示通过源码包安装的数据库信息。

### 附加信息

提示未安装MySQL：
![image](https://github.com/1Panel-dev/1Panel/assets/23008582/65c03383-9c23-4c00-8177-1935f4ee2ed4)
实际已安装数据库的（通过源码包形式安装）：
![image](https://github.com/1Panel-dev/1Panel/assets/23008582/f0365f5a-0ad5-417c-bcdc-e6ad33f401b5)

**Comment by ssongliu** [comment]
感谢反馈，当前版本可以通过 数据库 - 远程服务器 管理，或者可以导出本地数据库然后通过应用商店创建数据库导入进来。

比较推荐第二种方式，因为当前版本远程数据库的备份恢复可能在一些情况下会有问题。
