### ISSUE TITLE
[BUG] Docker镜像加速地址 正则效验异常

### ISSUE THREAD

**Issue by QYG2297248353** [1Panel-dev/1Panel#3851]
### 联系方式

@QYG2297248353 

### 1Panel 版本

v1.9.6

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/56836951/346c1b83-a960-4015-98fe-979832158914)

添加如下加速地址效验失败
```sh
https://mirrors.163.com/docker-ce
https://mirrors.ustc.edu.cn/docker-ce
https://mirrors.tuna.tsinghua.edu.cn/docker-ce
```

### 重现步骤

容器 => 配置 => 镜像加速
填写以下任意加速地址均失败
```sh
https://mirrors.163.com/docker-ce
https://mirrors.ustc.edu.cn/docker-ce
https://mirrors.tuna.tsinghua.edu.cn/docker-ce
```

### 附加信息

可以通过编辑源码临时解决

**Comment by ssongliu** [comment]
感谢反馈，已在开发环境复现该问题，下个版本解决。

当前可暂时通过编辑全部配置修改。

![image](https://github.com/1Panel-dev/1Panel/assets/73214554/a2d0e6cb-d8cf-48b6-88c8-ed661f641c2c)

**Comment by QYG2297248353** [comment]
Fix Bug

**Comment by wanghe-fit2cloud** [comment]
我们会在版本发布前，测试通过后再来关闭该 issue。
> 现阶段先将该 issue 打开了。

**Comment by wanghe-fit2cloud** [comment]
v1.10.0-lts 版本已发布。
