### ISSUE TITLE
[BUG]终端不能正常连接的BUG

### ISSUE THREAD

**Issue by PengyuDeng** [1Panel-dev/1Panel#3852]
### 1Panel 版本

1.9.6

### 问题描述

点击终端后显示
![image](https://github.com/1Panel-dev/1Panel/assets/89559616/ad2ebe48-3057-496e-a3b5-4850a4d6c86e)
但是查日志是登录成功了的
![image](https://github.com/1Panel-dev/1Panel/assets/89559616/56cdb535-f856-4f24-8fb5-12185cde50d0)

### 重现步骤

点击终端，然后查看SSH日志

### 期待的正确结果

终端应该正常连接的，我能保证我的登录密钥是正确的。

**Comment by ssongliu** [comment]
感谢反馈，可以先检查一下是否该问题：
https://1panel.cn/docs/faq/system_function/

**Comment by PengyuDeng** [comment]
宿主机是干净的，除了1panel没有任何的其他应用，如果要说nginx，我使用了应用商店里面的nginx-proxy-manager，这个是跑在容器里面的。

**Comment by ssongliu** [comment]
> 宿主机是干净的，除了1panel没有任何的其他应用，如果要说nginx，我使用了应用商店里面的nginx-proxy-manager，这个是跑在容器里面的。

可以尝试以下操作：

1. 容器列表点击终端连接，是否能正常打开
2. 连接一下其他的机器，是否正常

**Comment by PengyuDeng** [comment]
> > 宿主机是干净的，除了1panel没有任何的其他应用，如果要说nginx，我使用了应用商店里面的nginx-proxy-manager，这个是跑在容器里面的。
> 
> 可以尝试以下操作：
> 
> 1. 容器列表点击终端连接，是否能正常打开
> 2. 连接一下其他的机器，是否正常

容器的终端不能打开，连接我的云服务器也不能打开，同样的报错

**Comment by wanghe-fit2cloud** [comment]
> 容器的终端不能打开，连接我的云服务器也不能打开，同样的报错

https://1panel.cn/docs/faq/system_function/
或者使用 1Panel 自身的网站功能创建反向代理网站。

**Comment by PengyuDeng** [comment]
> > 容器的终端不能打开，连接我的云服务器也不能打开，同样的报错
> 
> https://1panel.cn/docs/faq/system_function/ 或者使用 1Panel 自身的网站功能创建反向代理网站。

我使用的应用：nginx proxy manager添加此配置，导致整个panel不能访问了
![image](https://github.com/1Panel-dev/1Panel/assets/89559616/760a27c2-d114-42bc-b621-02be21eeedbc)
![image](https://github.com/1Panel-dev/1Panel/assets/89559616/92ee4039-e521-439b-9897-ffa59c763700)

**Comment by PengyuDeng** [comment]
已解决，在nginx proxy manager里打开ws连接即可
