### ISSUE TITLE
[BUG]docker监控中的网络单位显示BUG

### ISSUE THREAD

**Issue by Zightch** [1Panel-dev/1Panel#3853]
### 联系方式

zightch@163.com

### 1Panel 版本

1.9.6

### 问题描述

坐标轴显示KB/s(包括鼠标悬停时显示的MB/s), 我用tc命令限速10Mbps后, 这让我百思不得其解  
他是怎么做到上行有400Mbps的速度的, 而且还是持续的  
我想应该是网络已传输的总量吧  
另外即使我限速错端口了, 幻兽帕鲁也不可能持续的跑到400Mbps吧
![7fdf328185ab328f2bb19b8863d26e9e](https://github.com/1Panel-dev/1Panel/assets/60181569/d2c3ea76-e371-412e-8094-cf9a9919517b)

### 重现步骤

打开docker的监控即可看到

### 期待的正确结果

修正docker监控中的网络单位, 让他看起来更合理一些

### 附加信息

![7fdf328185ab328f2bb19b8863d26e9e](https://github.com/1Panel-dev/1Panel/assets/60181569/d2c3ea76-e371-412e-8094-cf9a9919517b)

**Comment by ssongliu** [comment]
感谢反馈，这里可以通过 `docker stats` 比较一下。

**Comment by Zightch** [comment]
这是我对比的  
应该就是单位问题了  
docker stats中确实写的是MB, 表示已传输的总量  
另外监控中似乎与docker stats显示的有些误差  
![image](https://github.com/1Panel-dev/1Panel/assets/60181569/21a3bb02-d89e-4b32-b945-1011a9ff0ce6)

**Comment by ssongliu** [comment]
> 这是我对比的 应该就是单位问题了 docker stats中确实写的是MB, 表示已传输的总量 另外监控中似乎与docker stats显示的有些误差 ![image](https://private-user-images.githubusercontent.com/60181569/302879403-21a3bb02-d89e-4b32-b945-1011a9ff0ce6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyODgyNDgsIm5iZiI6MTcwNzI4Nzk0OCwicGF0aCI6Ii82MDE4MTU2OS8zMDI4Nzk0MDMtMjFhM2JiMDItZDg5ZS00YjMyLWI5NDUtMTAxMWE5ZmYwY2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDA2MzkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYjJlNWVlMWExZWFjYTgxYmE2NjRkZjBjZDA2N2YzNDM3ZjU4MGVlN2EyNTI2NzQwZDM3ZmM4YTU3NGQ3ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fx9hHTEEptieqlEg8hNr2ZNvtfRlkuGMdCwa3tVVC44)

噢是的！我这里是传输总量，不该写上 MB/s ，下个版本解决该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.0-lts 版本已发布。
