### ISSUE TITLE
[FEATURE]增加复制当前路径和复制包含路径的文件名功能

### ISSUE THREAD

**Issue by QAQ5555** [1Panel-dev/1Panel#386]
### 1Panel 版本

1.0.2

### 请描述您的需求或者改进建议

改进
增加复制当前路径和复制包含路径的文件名功能

### 请描述你建议的实现方案

地址栏添加复制路径按钮
文件更多里添加复制含路径的文件名按钮

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，该需求会在后续版本中支持。

**Comment by zhengkunwang223** [comment]
v1.2 版本已支持
