### ISSUE TITLE
[FEATURE] 应用商店请求添加《简单图床》

### ISSUE THREAD

**Issue by liufuyou** [1Panel-dev/1Panel#3864]
### 1Panel 版本

：v1.9.6

### 请描述您的需求或者改进建议

应用商店请求添加《简单图床》，简单好用的图床，无数据库。自带压缩，API管理，鉴黄等等。对于安装环境要求极低
GitHub 项目地址：https://github.com/icret/EasyImages2.0
Docker 镜像：https://hub.docker.com/r/ddsderek/easyimage
在线管理图片，支持上传图片转换为指定格式

**Comment by zhengkunwang223** [comment]
我们先调研一下

**Comment by liufuyou** [comment]
> 我们先调研一下

嗯嗯，Thanks

**Comment by w366813640** [comment]
lsky太吃内存了，建议添加对easyimage的支持

**Comment by wanghe-fit2cloud** [comment]
应用商店中已上架。
