### ISSUE TITLE
[FEATURE] 反向代理配置匹配规则优化问题

### ISSUE THREAD

**Issue by percyc** [1Panel-dev/1Panel#3868]
### 1Panel 版本

v1.9.6

## 存在问题
目前添加反向代理，默认的匹配规则是`^~`，前端请求路径是`/`，而且匹配规则为必填项。因为`^~`比正则表达式的匹配规则`~`优先级要高，导致增加的正则表达式匹配全部失效。
## 目前解决方案
只能通过反向代理中的`源文`移除`^~`，变成以下模式才能使得正则表达式匹配生效，在编辑模式中无法完成操作，建议优化
```
location / {
    ...
}
```
## 优化建议
让`匹配规则`项成为可选项，或者可以填写空格。

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本优化

**Comment by wanghe-fit2cloud** [comment]
最新版本已支持。
