### ISSUE TITLE
[BUG]终端主机添加私钥认证方式连接测试超时

### ISSUE THREAD

**Issue by Yurunsoft** [1Panel-dev/1Panel#3869]
### 1Panel 版本

v1.9.6

### 问题描述

在 SSH 管理里生成的密钥，用finalshell可以连。
到 1panel 的终端-主机里测试必超时。
还有个现象就是，输入错的私钥会立即返回失败，输入对的必超时。
![image](https://github.com/1Panel-dev/1Panel/assets/20104656/818b982a-5d8b-4f3e-840e-a6d9355bf237)

### 重现步骤

我的环境100%重现

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，请问是否是将 A 服务器公钥内容添加到 B 主机 authorized_keys 文件，然后在使用 `主机` - `终端` 功能连接时提供的是私钥内容。
> 刚刚在本地环境未复现上述问题。

**Comment by Yurunsoft** [comment]
我就一台服务器，需要改 `authorized_keys` 吗？

**Comment by wanghe-fit2cloud** [comment]
> 我就一台服务器，需要改 `authorized_keys` 吗？

一台服务器也需要将公钥内容添加到authorized_keys文件。
<img width="676" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/a18666af-dd0b-4dcb-8b22-8ebbf4cf8dde">
