### ISSUE TITLE
[FEATURE]Docker容器的Config的Env修改支持

### ISSUE THREAD

**Issue by HaoJun0823** [1Panel-dev/1Panel#387]
### 1Panel 版本

1.0.2

### 请描述您的需求或者改进建议

例子：1Panel应用商店的WordPress在容器配置的Config下的Env中设定"WORDPRESS_DEBUG=1"，这会启用WordPress的DEBUG模式，可能造成安全隐患，考虑到面板的集成性希望能提供相关办法来修改避免多个配置之间的不同步。

### 请描述你建议的实现方案

在应用商店的参数配置那边提供配置修改器。
或者提供修改容器配置的相关功能。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在 v1.1.0 版本中实现上述优化。
