### ISSUE TITLE
面板域名支持二级目录访问

### ISSUE THREAD

**Issue by YeJoe** [1Panel-dev/1Panel#3870]
### 请描述您的问题

希望面板域名可以支持支持二级目录访问，例如www.xxx.com/1panel

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们后续版本可能会考虑上述需求。
> 网站二级域名相关功能的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/2336
