### ISSUE TITLE
[BUG] 本机的MySQL，通过远程服务器管理无法添加

### ISSUE THREAD

**Issue by Liang-Dongxing** [1Panel-dev/1Panel#3871]
### 1Panel 版本

1.9.6

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/19583575/52cd3e86-e9bf-48c4-814d-f705590be2f1)

我通过navicat可以连接上

### 重现步骤

MySQL添加远程服务器，测试连接无法连接上

**Comment by wanghe-fit2cloud** [comment]
进入 `日志审计` 菜单，提供一下点击 `连接测试` 按钮后的系统日志。

**Comment by ssongliu** [comment]
是否有开启 ssl ？可以截图看一下连接信息。

**Comment by wanghe-fit2cloud** [comment]
先关闭该 issue 了，后续有问题继续在该 issue 中讨论。
