### ISSUE TITLE
[QUESTION]应用商店应用升级时是否无法保留修改的compose文件

### ISSUE THREAD

**Issue by 2Loong6** [1Panel-dev/1Panel#3872]
### 请描述您的问题

在使用中发现安装应用时修改`compose`中`volume`文件，之后升级时无法保留信息，这个之后有没有修改的计划呢？

**Comment by zhengkunwang223** [comment]
这个有计划，后续版本会增加升级时文件对比

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/2826
