### ISSUE TITLE
[QUESTION] 通过 Compose 安装的 Redis 能被 1Panel 识别吗？

### ISSUE THREAD

**Issue by wuhang2003** [1Panel-dev/1Panel#3873]
### 请描述您的问题

通过 Compose 文件开了个附属的 Redis 容器，但在 1Panel 的数据库管理功能上显示并没有检测到 Redis，想问一下目前这个功能是只能管理在 1Panel 面板上安装的 Redis 吗？
![image](https://github.com/1Panel-dev/1Panel/assets/108316419/9abe615c-d42a-48f2-8327-9fb8dda1dd20)
![image](https://github.com/1Panel-dev/1Panel/assets/108316419/d8d9e6c3-3582-4463-bf73-168d7e89ab0a)

**Comment by zhengkunwang223** [comment]
识别不了，只能识别通过1panel安装的

**Comment by wuhang2003** [comment]
> 识别不了，只能识别通过1panel安装的

所以后期是否会考虑加上这些对非 1Panel 途径安装的对应数据库容器的识别？
还是说也是通过（后期更新）的远程数据库功能对这些在本地的数据库容器进行管理？

**Comment by zhengkunwang223** [comment]
> > 识别不了，只能识别通过1panel安装的
> 
> 所以后期是否会考虑加上这些对非 1Panel 途径安装的对应数据库容器的识别？ 还是说也是通过（后期更新）的远程数据库功能对这些在本地的数据库容器进行管理？

识别不会 我们的数据库都有远程数据库导入功能 是靠这个管理已有的数据库 后续可能会更新 redis 模块来实现管理本地 redis

**Comment by wanghe-fit2cloud** [comment]
支持外部 Redis 数据库的需求，统一汇总到该 issue [#3522](https://github.com/1Panel-dev/1Panel/issues/3522)
