### ISSUE TITLE
[BUG]更改ssh日志等级之后面板登录日志不记失败记录

### ISSUE THREAD

**Issue by BJAny** [1Panel-dev/1Panel#3874]
### 1Panel 版本

1.9.6

### 问题描述

系统debian12，在更改ssh日志等级之后再改回去原来的，面板的登录日志里面只记录成功不记录失败

### 重现步骤

ssh日志等级默认等级为info更改为VERBOSE之后再更改回去info，测试失败登录ssh面板无记录新增失败登录，auth.log能看得到新增的跟之前一样的认证记录

**Comment by BJAny** [comment]
![QQ截图20240211145128](https://github.com/1Panel-dev/1Panel/assets/6690619/3a7143e8-7207-4885-859e-f887943aa2a4)
![QQ截图20240211143505](https://github.com/1Panel-dev/1Panel/assets/6690619/d13fda86-0bc7-442c-9b8d-828579d0e5db)
忘记附图了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by ssongliu** [comment]
可以尝试一下用错误的密码登陆，可能是日志解析规则不全导致的。

**Comment by BJAny** [comment]
现在有失败记录了，服务器天天被肉鸡扫ssh，fail2ban设置失败5次自动封禁，但是登录记录那里只显示一两次失败甚至不显示，fail2ban黑名单正常封禁ip

**Comment by ssongliu** [comment]
麻烦发一下日志文件到我邮箱 liu.song@fit2cloud.com，我看看这个问题

**Comment by wanghe-fit2cloud** [comment]
先关闭该 issue 了，后续如有问题继续讨论。
