### ISSUE TITLE
 [QUESTION] 快照是不是不会备份自己独立安装的docker持久化数据文件 

### ISSUE THREAD

**Issue by Mask-Vip** [1Panel-dev/1Panel#3875]
### 请描述您的问题

在看过官方文档后,只是知道了快照会备份opt/1panel文件夹,这个文件夹就包括了apps文件夹,也就是应用商店里安装的应用的持久化数据都保存在这里,应该是一起会被快照备份.

而自己创建的docker项目的持久化数据(储存卷)一般是/var/lib/docker/volumes文件夹下,在说明文档里没有看到这个位置会不会被快照备份.

现在的问题是,不明确自己创建的docker项目和持久化数据会不会被快照备份.现在看到的说明文档,我的理解是,只备份1panel自己的数据,其他的个人docker相关,1panel是不管的.

**Comment by wanghe-fit2cloud** [comment]
是的，创建快照不会备份 docker 数据目录。
> 推荐创建 `Shell 脚本` 类型计划任务来手动备份 docker 数据目录。

**Comment by Mask-Vip** [comment]
> 是的，创建快照不会备份 docker 数据目录。
> 
> > 推荐创建 类型计划任务来手动备份 docker 数据目录。`Shell 脚本`

那,自己创建的docker项目也是不会备份的吗?

**Comment by wanghe-fit2cloud** [comment]
> > 是的，创建快照不会备份 docker 数据目录。
> > > 推荐创建 类型计划任务来手动备份 docker 数据目录。`Shell 脚本`
> 
> 那,自己创建的docker项目也是不会备份的吗?

备份 docker 数据目录（默认 `/var/lib/docker`），就已经包括了 `自己创建的 docker 项目`

**Comment by Mask-Vip** [comment]
> > > 是的，创建快照不会备份 docker 数据目录。
> > > > 推荐创建 类型计划任务来手动备份 docker 数据目录。`Shell 脚本`
> > 
> > 
> > 那，自己创建的docker项目也是不会备份的吗？
> 
> 备份 docker 数据目录（默认 ），就已经包括了`/var/lib/docker``自己创建的 docker 项目`

好的,明白了.只有自己创建的docker项目的持久化数据不会被备份,其他的都会备份,如果需要重建系统的话也就是说,安装ubuntu系统,然后安装1Panel面板,然后上载快照文件并且恢复快照,上载自己备份的docker数据.这样就可以完全恢复整个系统了么???

可是面板设置>>快照 里面没有上载快照文件这个功能呢,是把快照文件放到哪里就可以显示出来了么?

**Comment by wanghe-fit2cloud** [comment]
> 可是面板设置>>快照 里面没有上载快照文件这个功能呢,是把快照文件放到哪里就可以显示出来了么?

`面板设置` - `快照`，同步快照时选择相同的备份账号即可。

**Comment by Mask-Vip** [comment]
> > 可是面板设置>>快照 里面没有上载快照文件这个功能呢,是把快照文件放到哪里就可以显示出来了么?
> 
> `面板设置` - `快照`，同步快照时选择相同的备份账号即可。

如果选服务器磁盘的话，那需要把备份文件上传到哪个目录啊？真的麻烦您细细说一下呢？

**Comment by wanghe-fit2cloud** [comment]
> > > 可是面板设置>>快照 里面没有上载快照文件这个功能呢,是把快照文件放到哪里就可以显示出来了么?
> > 
> > 
> > `面板设置` - `快照`，同步快照时选择相同的备份账号即可。
> 
> 如果选服务器磁盘的话，那需要把备份文件上传到哪个目录啊？真的麻烦您细细说一下呢？

1、进入 `面板设置` - `备份账号` 页面，查看 `服务器磁盘` - `当前路径`
2、将快照文件上传到 `服务器磁盘` - `当前路径` 下的 `system_snapshot` 文件夹即可

**Comment by Mask-Vip** [comment]
> > > > 可是面板设置>>快照 里面没有上载快照文件这个功能呢,是把快照文件放到哪里就可以显示出来了么?
> > > 
> > > 
> > > `面板设置` - `快照`，同步快照时选择相同的备份账号即可。
> > 
> > 
> > 如果选服务器磁盘的话，那需要把备份文件上传到哪个目录啊？真的麻烦您细细说一下呢？
> 
> 1、进入 - 页面，查看 - 2、将快照文件上传到 - 下的 文件夹即可`面板设置``备份账号``服务器磁盘``当前路径``服务器磁盘``当前路径``system_snapshot`

现在新版本是不是改成/opt/1panel/backup了?明白了,原来是先在备份账号里指定服务器磁盘路径,然后就可以在快照-同步快照里找到上传的快照文件了.收到,谢谢呢.
