### ISSUE TITLE
[FEATURE]添加在线预览图片的功能

### ISSUE THREAD

**Issue by anewinstance** [1Panel-dev/1Panel#3876]
### 1Panel 版本

v.19.3

### 请描述您的需求或者改进建议

建议添加在线预览图片的功能，包括常见的图片格式，这样可能会方便一点，不需要用FTP传下来再打开

**Comment by zhengkunwang223** [comment]
感谢建议，后续版本可能会考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/9dba9555-c76c-448b-b01d-62b568da4b01)
