### ISSUE TITLE
[FEATURE] 建议添加对GPU相关信息和主板各设备温度的实时监控显示

### ISSUE THREAD

**Issue by wqshmzh** [1Panel-dev/1Panel#3879]
### 1Panel 版本

1.9.6

### 请描述您的需求或者改进建议

目前的版本只能查看CPU、内存和外存的相关实时信息，无法查看显卡实时监控信息，以及主板各设备的温度信息。希望能够添加对GPU信息的实时监控，包括核心温度、显存温度、核心使用率、显存使用率、核心频率、显存频率、整体功耗等信息，以及CPU各核心、内存和外存等主板设备的温度信息实时显示

### 请描述你建议的实现方案

调用相应API显示相应信息

**Comment by wanghe-fit2cloud** [comment]
GPU相关需求的讨论，统一汇总到该 issue #431
