### ISSUE TITLE
[BUG]从反向代理后的域名访问面板phpMyAdmin会报404

### ISSUE THREAD

**Issue by HaoJun0823** [1Panel-dev/1Panel#388]
### 联系方式

developer@haojun0823.xyz

### 1Panel 版本

1.0.2

### 问题描述

为了使用ssl提高面板访问的安全性，个人通过反向代理来实现从域名访问面板这一功能。
反代实现以后发现没有办法从域名的方式通过面板访问phpMyAdmin。

因为面板目前没有绑定域名访问的功能，所以不知道算不算是个BUG。

### 重现步骤

设定一个域名，通过nginx反向代理1Panel。（我有设置SSL，我的面板端口是2083，反向代理http:127.0.0.1:2083）
通过反向代理后的域名访问1Panel。（https://域名/）
从应用商店安装phpMyAdmin。
从数据库菜单中的phpMyAdmin按钮访问phpMyAdmin。

新标签页会跳转到https://域名/databases/mysql:8089
因为服务无法访问，再次跳转到https://域名/error/404

### 期待的正确结果

其实通过域名反向代理8089这个端口也能访问到phpMyAdmin，但个人不赞成通过任何外部地址访问phpMyAdmin，这会提高数据库安全风险，可以考虑增加Basic Auth，或者提供phpMyAdmin的访问开关器用于在临时访问时开启端口避免平时被扫。

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈，我们会在后面版本中支持用户自定义 phpMyAdmin 访问路径。

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
