### ISSUE TITLE
[FEATURE]退出终端界面不关闭终端

### ISSUE THREAD

**Issue by mhdy2233** [1Panel-dev/1Panel#3881]
### 1Panel 版本

1.9.6

### 请描述您的需求或者改进建议

目前从终端界面出去后会直接关闭终端，能否不关闭终端或者是当网页关闭后再关闭终端？
这样如果没用其他的ssh软件的话会方便很多

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们暂时不会考虑支持上述需求，望理解。

**Comment by mhdy2233** [comment]
> 感谢反馈，我们暂时不会考虑支持上述需求，望理解。

好的好的
