### ISSUE TITLE
[FEATURE]新增一个商店应用：2FAuth

### ISSUE THREAD

**Issue by hadis898** [1Panel-dev/1Panel#3882]
### 1Panel 版本

v1.9.6

### 请描述您的需求或者改进建议

新增一个商店应用：2FAuth
作用：谷歌二步验证 web程序，可以搭建自己的私有或者多用户
文档：https://docs.2fauth.app/

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本上架 [2FAuth](https://github.com/Bubka/2FAuth)

**Comment by mobeicanyue** [comment]
可以考虑自托管 vaultwarden，支持 2FA。就是应用商店里面的 Bitwarden，后端是 Rust 重写版

**Comment by wanghe-fit2cloud** [comment]
已上架。可以进入应用商店，点击右上角的【更新应用列表】按钮，待同步完成后即可安装应用。

**Comment by tocha688** [comment]
默认账户密码是多少
