### ISSUE TITLE
在服务部署方面的一些建议

### ISSUE THREAD

**Issue by swt1me** [1Panel-dev/1Panel#3884]
### 1Panel 版本

1.9.6

### 请描述您的需求或者改进建议

添加部署应用商店内以外的服务
在部署服务式提供直接部署在本机和部署在容器的选项

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈。
中短期内我们将继续采用容器化部署方案。至于直接部署在本机的方案，目前我们暂无支持计划，望理解。

**Comment by swt1me** [comment]
希望以后能有计划吧毕竟有些服务不适合部署在容器上

**Comment by wanghe-fit2cloud** [comment]
> 希望以后能有计划吧毕竟有些服务不适合部署在容器上

收到，非常感谢您的建议。
