### ISSUE TITLE
[FEATURE] 面板配置https后，浏览器使用http协议访问自动重定向到https协议

### ISSUE THREAD

**Issue by bddjr** [1Panel-dev/1Panel#3886]
### 1Panel 版本

1.9.6

### 请描述您的需求或者改进建议

面板配置https后，使用http协议打开会显示一串英文，而不是自动重定向，这不太友好。
```
Client sent an HTTP request to an HTTPS server.
```

希望浏览器使用http协议访问面板的时候，自动重定向到https协议

### 请描述你建议的实现方案

使用mod https://github.com/bddjr/hlfhr

### 附加信息

go官方仓库相关issue  
https://github.com/golang/go/issues/49310

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by bddjr** [comment]
先别急，我先给go语言标准库发PR，等合并了之后，你们更新go版本，然后按照新的标准实现这个功能

**Comment by bddjr** [comment]
先别急，我先给go语言标准库发PR，等合并了之后，你们更新go版本，然后按照新的标准实现这个功能

![image](https://github.com/1Panel-dev/1Panel/assets/109646559/90fdc675-d7f3-47e3-89c0-cd7b90c89055)

**Comment by bddjr** [comment]
[那个PR](https://github.com/golang/go/pull/65769) 还没人审核，有个暂时的缓解措施就是添加 HSTS 响应头
```
Strict-Transport-Security: max-age=31536000
```
然后如果已经用https访问过了，会产生HSTS缓存，下次用http访问会直接重定向。  
但是如果没有缓存，那么还是会出现 `Client sent an HTTP request to an HTTPS server.`

**Comment by hcllmsx** [comment]
手贱点了一下面板SSL，现在面板打不开了，也提示这个

**Comment by wanghe-fit2cloud** [comment]
> 手贱点了一下面板SSL，现在面板打不开了，也提示这个

`1pctl reset https` 命令可以取消 https 登录

**Comment by bddjr** [comment]
我做了个 go mod 劫持 `net.Conn` 实现了这个功能。  

https://github.com/bddjr/hlfhr

使用的时候只需要在 `&http.Server{}` 外面套一层 `hlfhr.New()` ，然后修改一下变量类型就可以了  

```go
var srv *hlfhr.Server

func main() {
	srv = hlfhr.New(&http.Server{
		Addr:              ":5678",
		Handler:           http.HandlerFunc(httpResponseHandle),
		ReadHeaderTimeout: 10 * time.Second,
		IdleTimeout:       10 * time.Second,
	})
	err := srv.ListenAndServeTLS("localhost.crt", "localhost.key")
	if err != nil && err != http.ErrServerClosed {
		fmt.Println(err)
	}
}
```

**Comment by bddjr** [comment]
go标准库的提案issue被提出issue的人关了，因为[我写的mod](https://github.com/bddjr/hlfhr)已经实现了😂  

现在mod已经有6个star了，版本更新到v1.0.1了，功能比之前的完善多了，修了connection was reset的bug，使用标准库的`http.ReadRequest`读取请求，使用标准库`http.Handler`处理请求。  

mod文件公开透明，经过vscode自动格式化，如果担心有见不到的空格可以按 Ctrl+A 再审查，我保证没有藏任何恶意代码，保证没有安全漏洞，我自己也在用。  

@wanghe-fit2cloud 我知道这辈子都见不到1panel重写，请问我现在提交PR会被接受吗？还要等到哪年哪月？可以给个准确的答复吗？

**Comment by wanghe-fit2cloud** [comment]
> go标准库的提案issue被提出issue的人关了，因为[我写的mod](https://github.com/bddjr/hlfhr)已经实现了😂
> 
> 现在mod已经有6个star了，版本更新到v1.0.1了，功能比之前的完善多了，修了connection was reset的bug，使用标准库的`http.ReadRequest`读取请求，使用标准库`http.Handler`处理请求。
> 
> mod文件公开透明，经过vscode自动格式化，如果担心有见不到的空格可以按 Ctrl+A 再审查，我保证没有藏任何恶意代码，保证没有安全漏洞，我自己也在用。
> 
> @wanghe-fit2cloud 我知道这辈子都见不到1panel重写，请问我现在提交PR会被接受吗？还要等到哪年哪月？可以给个准确的答复吗？

计划在明年的 v2 版本中调研并支持这一需求。至于你提到的自行实现的库，我们暂时先不考虑合并，望理解。

**Comment by bddjr** [comment]
@wanghe-fit2cloud 另一个消息你有看到吗？那个bug与这个bug没有关系，是前端需要解决的bug，请重新打开它。 https://github.com/1Panel-dev/1Panel/issues/6573#issuecomment-2415848928

**Comment by Anyexyz** [comment]
> go标准库的提案issue被提出issue的人关了，因为[我写的mod](https://github.com/bddjr/hlfhr)已经实现了😂
> 
> 现在mod已经有6个star了，版本更新到v1.0.1了，功能比之前的完善多了，修了connection was reset的bug，使用标准库的`http.ReadRequest`读取请求，使用标准库`http.Handler`处理请求。
> 
> mod文件公开透明，经过vscode自动格式化，如果担心有见不到的空格可以按 Ctrl+A 再审查，我保证没有藏任何恶意代码，保证没有安全漏洞，我自己也在用。
> 
> @wanghe-fit2cloud 我知道这辈子都见不到1panel重写，请问我现在提交PR会被接受吗？还要等到哪年哪月？可以给个准确的答复吗？

我想提一个问题，发送到 https 端口的 http 请求是否应该被允许重定向到 https，这种操作是否合乎常规？

**Comment by bddjr** [comment]
@Anyexyz 1Panel生成的OpenResty配置文件里有这么一行
```nginx
error_page 497 https://$host$request_uri; 
```
它的作用就是让网站的 443 端口在接收 http 请求时跳转到 https 。  
我部署后的效果：http://q8p.cc:443

然而1panel本身配置 https 之后，没有这个自动跳转。如果浏览器按照之前的历史记录推荐访问，或者用户访问时没有加上`https://`协议头然后还超过3秒没反应，浏览器会使用 http 协议访问，导致显示 `Client sent an HTTP request to an HTTPS server.` 或 `connection was reset` 。  

这个issue的目的就是解决这个bug，优化使用体验。

**Comment by Anyexyz** [comment]
> @Anyexyz 1Panel生成的OpenResty配置文件里有这么一行
> ```nginx
> error_page 497 https://$host$request_uri; 
> ```
> 它的作用就是让网站的 443 端口在接收 http 请求时跳转到 https 。  
> 我部署后的效果：http://q8p.cc:443
> 
> 然而1panel本身配置 https 之后，没有这个自动跳转。如果浏览器按照之前的历史记录推荐访问，或者用户访问时没有加上`https://`协议头然后还超过3秒没反应，浏览器会使用 http 协议访问，导致显示 `Client sent an HTTP request to an HTTPS server.` 或 `connection was reset` 。  
> 
> 这个issue的目的就是解决这个bug，优化使用体验。

建议提个feature看看😂

**Comment by bddjr** [comment]
🤔这个就是feature

**Comment by bddjr** [comment]
还有几个逆天的问题我都懒得提了，我刚刚在某云售后1群里讨论了，不知道这次有没有人转发

**Comment by devhaozi** [comment]
> 我做了个 go mod 劫持 `net.Conn` 实现了这个功能。
> 
> https://github.com/bddjr/hlfhr
> 
> 使用的时候只需要在 `&http.Server{}` 外面套一层 `hlfhr.New()` ，然后修改一下变量类型就可以了
> 
> ```go
> var srv *hlfhr.Server
> 
> func main() {
> 	srv = hlfhr.New(&http.Server{
> 		Addr:              ":5678",
> 		Handler:           http.HandlerFunc(httpResponseHandle),
> 		ReadHeaderTimeout: 10 * time.Second,
> 		IdleTimeout:       10 * time.Second,
> 	})
> 	// Then just use it like &http.Server .
> 
> 	err := srv.ListenAndServeTLS("localhost.crt", "localhost.key")
> 	if err != nil && err != http.ErrServerClosed {
> 		fmt.Println(err)
> 	}
> }
> ```

牛，刚准备自己研究写307重定向就看到这个，感谢。
