### ISSUE TITLE
[FEATURE]请求添加NetBird和zitadel

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3888]
### 1Panel 版本

v1.9.6

### 请描述您的需求或者改进建议

[NetBird](https://github.com/netbirdio/netbird/) 是一个建立在 WireGuard 之上的开源网络管理平台，它允许计算机、设备和服务器通过快速加密隧道直接连接，无需配置或中央服务器。
可以容器部署 [run-docker-compose](https://docs.netbird.io/selfhosted/selfhosted-guide#step-6-run-docker-compose)

[ZITADEL](https://github.com/zitadel/zitadel) 是一个用 Go 编写的云原生身份和访问管理解决方案 (IAM)。
也支持容器部署 [docker-compose](https://zitadel.com/docs/self-hosting/deploy/compose)

> NetBird 需要 ZITADEL 用于前置

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑是否上架上述应用。

**Comment by wanghe-fit2cloud** [comment]
出于合规考虑，我们决定不上架上述应用，望理解。
