### ISSUE TITLE
[QUESTION]端口问题

### ISSUE THREAD

**Issue by Ling1992** [1Panel-dev/1Panel#389]
### 请描述您的问题

如果修改随机生成的端口号 ？ 让其固定一个值

**Comment by wanghe-fit2cloud** [comment]
登录 1Panel Web 控制台，在【面板设置】菜单中实现自定义端口功能。

![image](https://user-images.githubusercontent.com/46734380/227412172-47b93dfd-67cd-4b3c-85ea-aa7e212d7c61.png)

**Comment by Ling1992** [comment]
> 登录 1Panel Web 控制台，在【面板设置】菜单中实现自定义端口功能。
> 
> ![image](https://user-images.githubusercontent.com/46734380/227412172-47b93dfd-67cd-4b3c-85ea-aa7e212d7c61.png)

不能通过配置文件修改吗？ 我这边端口限制严格，端口开通需要申请。

**Comment by Ling1992** [comment]
> > 登录 1Panel Web 控制台，在【面板设置】菜单中实现自定义端口功能。
> > ![image](https://user-images.githubusercontent.com/46734380/227412172-47b93dfd-67cd-4b3c-85ea-aa7e212d7c61.png)
> 
> 不能通过配置文件修改吗？ 我这边端口限制严格，端口开通需要申请。

@wanghe-fit2cloud

**Comment by wanghe-fit2cloud** [comment]
后续版本会提供通过 1pctl 修改端口的功能。

**Comment by wanghe-fit2cloud** [comment]
v1.0.4 版本已支持用户在 1Panel 初始化时自定义端口。
