### ISSUE TITLE
[FEATURE]支持管理 Docker 构建缓存

### ISSUE THREAD

**Issue by WankkoRee** [1Panel-dev/1Panel#3890]
### 1Panel 版本

v1.9.6

### 请描述您的需求或者改进建议

通过`docker system df`可以查看`Build Cache`。

![image](https://github.com/1Panel-dev/1Panel/assets/21287731/ddf36599-07a7-4035-8e85-f7d98d7130eb)

通过`docker builder prune`可以清理。

![image](https://github.com/1Panel-dev/1Panel/assets/21287731/ade653bd-38fa-412c-b0d5-b64f0cad7571)

![image](https://github.com/1Panel-dev/1Panel/assets/21287731/d6fe5266-fe34-47ef-8822-f39cb0dee1f4)

### 请描述你建议的实现方案

在**容器**-**镜像**页面添加**清理构建缓存**按钮，或者作为**工具箱**-**缓存清理**的新特性。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
