### ISSUE TITLE
[BUG]supervisor进程守护容器里的php进程有错误

### ISSUE THREAD

**Issue by muzidudu** [1Panel-dev/1Panel#3892]
### 1Panel 版本

v1.9.6

### 问题描述

守护进程停止后状态显示的已经停止,但查看进程还是存在的,必须重启进程所属的容器后才会有效果

### 重现步骤

docker exec tolafa php sites/abc.com/index/artisan queue:listen --queue=down

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
PHP 容器内部进程守护相关问题的讨论，统一汇总到该 issue #2683

**Comment by muzidudu** [comment]
> 感谢反馈。 
> PHP 容器内部进程守护相关问题的讨论，统一汇总到该 issue #2683

停止命令可以先判断如果是docker exec
，先搜索进程pid然后进入容器kill进程呢

是否可以参考[参考链接](https://m.php.cn/faq/519988.html?share_token=BAF0AF8D-F4F9-494D-B59C-A187D0C83EDD&tt_from=copy_link&utm_campaign=client_share&utm_medium=toutiao_ios&utm_source=copy_link docker进程无法停止怎么办-Docker-PHP中文网 - 今日头条)
