### ISSUE TITLE
[BUG]Debian12.4系统PHP无法安装swoole扩展

### ISSUE THREAD

**Issue by 520svip** [1Panel-dev/1Panel#3893]
### 联系方式

577813810@qq.com

### 1Panel 版本

1.9.6

#### 系统：Debian12.4
`Linux Debian12 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
`
#### 问题一：
PHP版本：8.1.27、8.2.15
PS：建议增加docker builder  prune清除缓存，测试发现重复安装会使用缓存进行build
<img width="982" alt="d4806602b4275de357eda2ca9b08641" src="https://github.com/1Panel-dev/1Panel/assets/101090229/7826c521-12d4-4583-80f0-d0b708248cec">
#### 问题二：
PHP版本：8.1.23
<img width="1121" alt="47b77ddd141b8221ac0bd23d21dbbc8" src="https://github.com/1Panel-dev/1Panel/assets/101090229/4aae8c83-30b8-4625-a90d-2386aeb07605">

#### 问题一重现步骤：
扩展模板：`bcmath,gd,gettext,intl,pcntl,shmop,soap,sockets,sysvsem,xmlrpc,zip,opcache,redis,swoole,imap,pgsql,pdo_pgsql,mysqli,pdo_mysql,mbstring,curl`
安装提示成功后可以去看日志，里面显示swoole安装失败，也可以在容器里面执行`php --ri swoole`查询是否成功安装swoole扩展

#### 问题二重现步骤：
直接安装，每次都提示这个

**Comment by zhengkunwang223** [comment]
我们先复现一下

**Comment by 520svip** [comment]
> 我们先复现一下

然后swoole官方好像最新版本已经是5.1.1了，现在安装扩展还是5.0.2的，能否也更新一下最新版的swoole呢，最好是支持一下扩展选择版本进行安装，毕竟不同用户有不同的需求

**Comment by 520svip** [comment]
> 我们先复现一下

centos stream 9也出现一样的错误，无法安装swoole扩展，群里“程会玩”远程调试过，使用的是VMware虚拟机安装的，镜像使用的是清华大学镜像源下载的ISO
https://mirrors.tuna.tsinghua.edu.cn/centos-stream/9-stream/BaseOS/x86_64/iso/
下载的是这个镜像：CentOS-Stream-9-latest-x86_64-dvd1.iso
![513ca157571e49650300555fad68858](https://github.com/1Panel-dev/1Panel/assets/101090229/46fa4b89-6254-4bd5-95dd-c105280720a0)

**Comment by wanghe-fit2cloud** [comment]
问题一：关注该 issue #4039

**Comment by zhengkunwang223** [comment]
当前  swoole 扩展安装有问题 当前你可以先在容器中执行 install-php-extensions  swoole 来安装

**Comment by wanghe-fit2cloud** [comment]
v1.10.1-lts 版本已发布。
