### ISSUE TITLE
[BUG]Fail2ban设置ip黑名单失效为空

### ISSUE THREAD

**Issue by xiaohange** [1Panel-dev/1Panel#3894]
### 联系方式

532167805@qq.com

### 1Panel 版本

当前运行版本：v1.9.6

### 问题描述

fail2ban 版本号：0.11.2
问题：
设置好ip黑名单后，隔一段时间（大约3分钟），再来点开看就变成空的了。

### 重现步骤

设置好ip黑名单后，隔一段时间（大约3分钟），再来点开看就变成空的了。

### 期待的正确结果

修复问题

**Comment by xiaohange** [comment]
<img width="1673" alt="截屏2024-02-17 11 14 34" src="https://github.com/1Panel-dev/1Panel/assets/14025157/ca7412f6-badb-4527-87b9-20bccdba92fe">
明明设置了，点击确认后重新打开还有，过一会儿打开就成空的了。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by ssongliu** [comment]
请问一下使用的是什么屏蔽方式，可以截图看一下这个界面
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/23b3f4f0-59cf-4a00-a167-92c062aa8030)

**Comment by xiaohange** [comment]
> 请问一下使用的是什么屏蔽方式，可以截图看一下这个界面 ![image](https://private-user-images.githubusercontent.com/73214554/305679381-23b3f4f0-59cf-4a00-a167-92c062aa8030.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzE3NTIsIm5iZiI6MTcwODIzMTQ1MiwicGF0aCI6Ii83MzIxNDU1NC8zMDU2NzkzODEtMjNiM2Y0ZjAtNTljZi00YTAwLWExNjctOTJjMDYyYWE4MDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA0NDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiODIzM2RhODJkODI4OTdjN2RjOTU4ZmZiODc4ZWE1NDFlYjI3MGY5ODJhZDYxODIxZmU5YWU1OTk2ZjM5ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W8YMhu9r0rRSOdYzviLi6Px0ZjDXRjJhPeADNDPYCRY)

<img width="736" alt="截屏2024-02-18 12 44 47" src="https://github.com/1Panel-dev/1Panel/assets/14025157/5a898494-f3fb-40f8-b4c1-f40d1eee93f0">

跟进了一下，第二天发现，黑名单会将昨晚攻击的ip列入到黑名单，我也没再去尝试将之前的几十个添加进去，怕再被清空了。

**Comment by ssongliu** [comment]
> > 请问一下使用的是什么屏蔽方式，可以截图看一下这个界面 ![image](https://private-user-images.githubusercontent.com/73214554/305679381-23b3f4f0-59cf-4a00-a167-92c062aa8030.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzE3NTIsIm5iZiI6MTcwODIzMTQ1MiwicGF0aCI6Ii83MzIxNDU1NC8zMDU2NzkzODEtMjNiM2Y0ZjAtNTljZi00YTAwLWExNjctOTJjMDYyYWE4MDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA0NDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiODIzM2RhODJkODI4OTdjN2RjOTU4ZmZiODc4ZWE1NDFlYjI3MGY5ODJhZDYxODIxZmU5YWU1OTk2ZjM5ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W8YMhu9r0rRSOdYzviLi6Px0ZjDXRjJhPeADNDPYCRY)
> 
> <img alt="截屏2024-02-18 12 44 47" width="736" src="https://private-user-images.githubusercontent.com/14025157/305685397-5a898494-f3fb-40f8-b4c1-f40d1eee93f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMDY4NzcsIm5iZiI6MTcwODMwNjU3NywicGF0aCI6Ii8xNDAyNTE1Ny8zMDU2ODUzOTctNWE4OTg0OTQtZjNmYi00MGY4LWI0YzEtZjQwZDFlZWU5M2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAxMzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MWEzNDBjNTY1ZmE3NjBiMGJlZmJlZDI2NzBhNGFiZGJiNTIwNjVkYThmMTU1MTkyYmIwYWZhMzkzYzcyYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yBBGNRmRi2pg6A_wKO1dzgHs6iMPxf9iPH6fDN1FOzw">
> 跟进了一下，第二天发现，黑名单会将昨晚攻击的ip列入到黑名单，我也没再去尝试将之前的几十个添加进去，怕再被清空了。

自动拦截的添加进黑名单不会被删除，手动添加后，才会有失效的情况吗？

**Comment by xiaohange** [comment]
> > > 请问一下使用的是什么屏蔽方式，可以截图看一下这个界面 ![image](https://private-user-images.githubusercontent.com/73214554/305679381-23b3f4f0-59cf-4a00-a167-92c062aa8030.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzE3NTIsIm5iZiI6MTcwODIzMTQ1MiwicGF0aCI6Ii83MzIxNDU1NC8zMDU2NzkzODEtMjNiM2Y0ZjAtNTljZi00YTAwLWExNjctOTJjMDYyYWE4MDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA0NDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiODIzM2RhODJkODI4OTdjN2RjOTU4ZmZiODc4ZWE1NDFlYjI3MGY5ODJhZDYxODIxZmU5YWU1OTk2ZjM5ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W8YMhu9r0rRSOdYzviLi6Px0ZjDXRjJhPeADNDPYCRY)
> > 
> > 
> > <img alt="截屏2024-02-18 12 44 47" width="736" src="https://private-user-images.githubusercontent.com/14025157/305685397-5a898494-f3fb-40f8-b4c1-f40d1eee93f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMDY4NzcsIm5iZiI6MTcwODMwNjU3NywicGF0aCI6Ii8xNDAyNTE1Ny8zMDU2ODUzOTctNWE4OTg0OTQtZjNmYi00MGY4LWI0YzEtZjQwZDFlZWU5M2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAxMzYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MWEzNDBjNTY1ZmE3NjBiMGJlZmJlZDI2NzBhNGFiZGJiNTIwNjVkYThmMTU1MTkyYmIwYWZhMzkzYzcyYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yBBGNRmRi2pg6A_wKO1dzgHs6iMPxf9iPH6fDN1FOzw">
> > 跟进了一下，第二天发现，黑名单会将昨晚攻击的ip列入到黑名单，我也没再去尝试将之前的几十个添加进去，怕再被清空了。
> 
> 自动拦截的添加进黑名单不会被删除，手动添加后，才会有失效的情况吗？

是的，自动加进的不会被删除，手动添加的就会被清空。

**Comment by ssongliu** [comment]
开发环境没有复现这个问题，可以尝试禁用方式到 iptables-allports 后重试

**Comment by xiaohange** [comment]
> 开发环境没有复现这个问题，可以尝试禁用方式到 iptables-allports 后重试

我使用的是centos7.9 的 firewalld ，可以使用  iptables-allports这种模式吗？

**Comment by xiaohange** [comment]
> 开发环境没有复现这个问题，可以尝试禁用方式到 iptables-allports 后重试

目前已禁用了密码登录ssh，采用秘钥登录，已基本解决了这种攻击行为，并且新发现的黑名单ip在firewallcmd-ipset模式下是生效的。

**Comment by ssongliu** [comment]
> > 开发环境没有复现这个问题，可以尝试禁用方式到 iptables-allports 后重试
> 
> 我使用的是centos7.9 的 firewalld ，可以使用 iptables-allports这种模式吗？

可以的

先关闭这个 issue 了，后续有问题可以重新打开。

**Comment by xiaohange** [comment]
> > > 开发环境没有复现这个问题，可以尝试禁用方式到 iptables-allports 后重试
> > 
> > 
> > 我使用的是centos7.9 的 firewalld ，可以使用 iptables-allports这种模式吗？
> 
> 可以的
> 
> 先关闭这个 issue 了，后续有问题可以重新打开。

好的，感谢！

**Comment by AliveNeko** [comment]
遇到了相同的问题，fail2ban的IP黑名单设置之后过一段时间自己就没了，版本：v1.10.20-lts，Debian12系统

**Comment by AliveNeko** [comment]
![1panel-fail2ban](https://github.com/user-attachments/assets/bc54b33f-cb40-4db1-b10b-7421387cb464)

被这个俄罗斯IP尝试登录了四千多页，最后使用ufw才给禁了🤮

**Comment by ssongliu** [comment]
> ![1panel-fail2ban](https://private-user-images.githubusercontent.com/38039224/384864850-bc54b33f-cb40-4db1-b10b-7421387cb464.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTIxNzUsIm5iZiI6MTczMTM5MTg3NSwicGF0aCI6Ii8zODAzOTIyNC8zODQ4NjQ4NTAtYmM1NGIzM2YtY2I0MC00ZGIxLWIxMGItNzQyMTM4N2NiNDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA2MTExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNThlNGVlMGMxZjk2NTFhYjNlNDk2ZTI0NjBhZmRlODUwN2Q4YjY5YzQxMjI5OTM3ZmI5MmYzZTg1NGM2NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BlQKSAyFopqaa6JQgZpxOwEzexi-5gRXcS77rkPeeX0)
> 
> 被这个俄罗斯IP尝试登录了四千多页，最后使用ufw才给禁了🤮

麻烦加一波好友，我看看这个问题
![image](https://github.com/user-attachments/assets/c8d6be0d-a13e-4dca-a2e9-170d655c1b91)

**Comment by AliveNeko** [comment]
> > ![1panel-fail2ban](https://private-user-images.githubusercontent.com/38039224/384864850-bc54b33f-cb40-4db1-b10b-7421387cb464.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTIxNzUsIm5iZiI6MTczMTM5MTg3NSwicGF0aCI6Ii8zODAzOTIyNC8zODQ4NjQ4NTAtYmM1NGIzM2YtY2I0MC00ZGIxLWIxMGItNzQyMTM4N2NiNDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA2MTExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNThlNGVlMGMxZjk2NTFhYjNlNDk2ZTI0NjBhZmRlODUwN2Q4YjY5YzQxMjI5OTM3ZmI5MmYzZTg1NGM2NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BlQKSAyFopqaa6JQgZpxOwEzexi-5gRXcS77rkPeeX0)
> > 被这个俄罗斯IP尝试登录了四千多页，最后使用ufw才给禁了🤮
> 
> 麻烦加一波好友，我看看这个问题 ![image](https://private-user-images.githubusercontent.com/73214554/385161500-c8d6be0d-a13e-4dca-a2e9-170d655c1b91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTIyNjcsIm5iZiI6MTczMTM5MTk2NywicGF0aCI6Ii83MzIxNDU1NC8zODUxNjE1MDAtYzhkNmJlMGQtYTEzZS00ZGNhLWEyZTktMTcwZDY1NWMxYjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA2MTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNjAwM2E2NzU4OTAwMGY1NjQ0Y2Q3ZDAyZWFlMWI3MmJlZThlMjhjM2MyNTZkNmY4ZmNjMTNhMjQ4N2JkNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hb4FzyOT4tToUJOZqfx7Ncb3MgkPyMvVKG3RP5L6Xx8)

加你了，情况和#7007中的一样， iptables-allports禁用方式下IP黑名单会丢失，~~使用ufw貌似可以~~，刚上去看了下ufw禁用方式添加的IP没名单也没了

---

后续更新：
1. IP会消失是因为fail2ban中的黑名单是临时的（默认设置下），如果没有设置成永久封禁，那么时间到了就放出来了。
2. iptables-allports模式下不生效可能是因为我环境问题导致找不到iptables命令，但是root下是有的并且fail2ban使用的是root启动（题外话：DMIT默认镜像的sudo好像有点问题）

禁用模式切换成ufw了，反正现在可以正常禁用了（还没找到iptables全端口禁用模式不生效的原因）。
