### ISSUE TITLE
[BUG]新建的halo网站，在网站管理里启用密码访问后，进后台无限弹窗

### ISSUE THREAD

**Issue by cyril-cheng** [1Panel-dev/1Panel#3896]
### 1Panel 版本

1.9.6

### 问题描述

我在1panel里用halo新建了一个网站。
然后我在“网站”里启用密码访问，这时候我进halo后台会无限弹窗。
![image](https://github.com/1Panel-dev/1Panel/assets/49748357/de929222-160c-4020-bf18-e3764801482d)
在弹窗里输入账号密码并点击登录后，又会重新弹窗，根本进不去后台。

### 重现步骤

我在1panel里用halo新建了一个网站。
然后我在“网站”里启用密码访问，这时候我进halo后台会无限弹窗。
![image](https://github.com/1Panel-dev/1Panel/assets/49748357/de929222-160c-4020-bf18-e3764801482d)
在弹窗里输入账号密码并点击登录后，又会重新弹窗，根本进不去后台。

**Comment by zhengkunwang223** [comment]
换浏览器试试呢

**Comment by cyril-cheng** [comment]
> 换浏览器试试呢

我用的是chrome，刚换了edge也是这样。前台鉴权是正常的，进后台就无限弹。

**Comment by d4renk** [comment]
点下f12 抓下网络 开关密码前后 是不是有什么请求失败
或者清除下缓存试试

**Comment by cyril-cheng** [comment]
> 点下f12 抓下网络 开关密码前后 是不是有什么请求失败 或者清除下缓存试试

f12显示401鉴权失败

**Comment by cyril-cheng** [comment]
https://github.com/halo-dev/halo/issues/5408

**Comment by wanghe-fit2cloud** [comment]
> [halo-dev/halo#5408](https://github.com/halo-dev/halo/issues/5408)

了解，我们先关闭该 Issue 了
