### ISSUE TITLE
[FEATURE] 反向代理在代理https源站时，支持可选的`回源 SNI`

### ISSUE THREAD

**Issue by WankkoRee** [1Panel-dev/1Panel#3898]
### 1Panel 版本

v1.9.6

### 请描述您的需求或者改进建议

`proxy_ssl_server_name on | off;`

默认不开启，即`proxy_ssl_server_name off;`

### 附加信息

技术细节见：[Nginx反向代理，当后端为Https时的一些细节和原理 - XniLe - Ops 2.0](https://blog.dianduidian.com/post/nginx%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86%E5%BD%93%E5%90%8E%E7%AB%AF%E4%B8%BAhttps%E6%97%B6%E7%9A%84%E4%B8%80%E4%BA%9B%E7%BB%86%E8%8A%82%E5%92%8C%E5%8E%9F%E7%90%86/)

**Comment by WankkoRee** [comment]
通常在反代源站为CDN时需要开启。

**Comment by zhengkunwang223** [comment]
感谢反馈 我们测试一下

**Comment by bddjr** [comment]
这与我之前提的issue重复了
#3461
