### ISSUE TITLE
[FEATURE]商店增加gitea的action- art_runner

### ISSUE THREAD

**Issue by vybfi** [1Panel-dev/1Panel#3900]
### 1Panel 版本

v1.9.6

### 请描述您的需求或者改进建议

希望增加gitea的action的支持
毕竟有gitea的一键部署,  没有相应的runner的一键部署, 就很奇怪hhh
是否考虑添加一下, 毕竟都可以docker部署

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持。

**Comment by wanghe-fit2cloud** [comment]
已经上架至正式仓库。
