### ISSUE TITLE
[FEATURE]应用商店添加sakuraFrp

### ISSUE THREAD

**Issue by vybfi** [1Panel-dev/1Panel#3901]
### 1Panel 版本

v1.9.6

### 请描述您的需求或者改进建议

希望能添加sakuraFrp内网穿透软件
sakuraFrp支持docker部署
其官网为: https://www.natfrp.com/

**Comment by wanghe-fit2cloud** [comment]
基于合规考虑，我们暂时不打算将 SakuraFrp 应用列入上架计划，望理解。
> 你可以考虑创建本地应用，或者向第三方应用商店提供需求反馈。

**Comment by vybfi** [comment]
啊, 可惜了. 能告诉我为什么Sakurafrp可能不合规吗?
