### ISSUE TITLE
[QUESTION] 安装失败后卸载或者重建，都会显示安装目录不存在

### ISSUE THREAD

**Issue by huangbh1024** [1Panel-dev/1Panel#3902]
### 请描述您的问题

![image](https://github.com/1Panel-dev/1Panel/assets/72372968/afb4a3dc-ecdd-45fa-abe7-3cd615a3bd6c)
![image](https://github.com/1Panel-dev/1Panel/assets/72372968/38c93fe6-4d63-493f-b10d-3fe20197518d)

**Comment by zhengkunwang223** [comment]
这是下载应用安装包失败 所以不会去创建安装目录 强制删除即可

**Comment by huangbh1024** [comment]
> 这是下载应用安装包失败 所以不会去创建安装目录 强制删除即可

怎么强制删除

**Comment by zhengkunwang223** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/ac82a2ad-4740-4268-832d-16b0dffa52c7)

**Comment by huangbh1024** [comment]
> ![image](https://private-user-images.githubusercontent.com/31820853/305704248-ac82a2ad-4740-4268-832d-16b0dffa52c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTA1NjYsIm5iZiI6MTcwODI1MDI2NiwicGF0aCI6Ii8zMTgyMDg1My8zMDU3MDQyNDgtYWM4MmEyYWQtNDc0MC00MjY4LTgzMmQtMTZiMGRmZmE1MmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA5NTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ZmVjYjE2MjdlOWUzZjJiODdlMDdjZjY2OWE0Yjc2MjY3ZmRkY2RiNDQ3NDg4MmZjZGYwNTJlZTFjMzNiZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p_gunKqB_gNjnqnsx2XjzfwfGwJgH0-vKm9aZf73PXg)

哈哈，谢谢，没注意到
