### ISSUE TITLE
[QUESTION]请问适配应用的时候, 配置文件应该放在哪个地方

### ISSUE THREAD

**Issue by vybfi** [1Panel-dev/1Panel#3903]
### 请描述您的问题

开发者你好!
我在适配一个obsidian同步的应用到应用商店
但是其启动过程需要一个配置文件(local.ini)
请问我应该将配置文件放在应用目录的哪个位置呢?
![image](https://github.com/1Panel-dev/1Panel/assets/52736701/a3d1b7ea-5e8b-48fe-85dc-734015711fc0)
是应该全部统一放在docker compose同目录下的data目录,  还是直接和docker compose文件放在一起?
同时docker compose目录下的挂载卷的参数是否应该修改呢?

还是说我应该写一个脚本将其拷贝到安装后的目录呢?
如果我需要写脚本, 请问脚本的运行目录在哪个位置, 我应该如何定位当前1panel的应用安装目录呢?

谢谢!

**Comment by vybfi** [comment]
还有就是, 请问pr到应用商店 dev分支的应用, 需要怎样才能上架呢

**Comment by vybfi** [comment]
还有就是, 网络模式能不能使用host而不是桥接到1panel-network呢

**Comment by vybfi** [comment]
请问开发文档能不能更新一下呢, 文档中的tag 已经缺少了好几个了🥲

**Comment by wanghe-fit2cloud** [comment]
> 请问我应该将配置文件放在应用目录的哪个位置呢?

参考 [MySQL](https://github.com/1Panel-dev/appstore/blob/dev/apps/mysql/8.2.0/docker-compose.yml) 配置文件 my.cnf

**Comment by wanghe-fit2cloud** [comment]
> 网络模式能不能使用host而不是桥接到1panel-network

host 模式参考 [OpenResty](https://github.com/1Panel-dev/appstore/blob/dev/apps/openresty/1.21.4.3-0-focal/docker-compose.yml)

**Comment by vybfi** [comment]
> > 
> 
> host 模式参考 [OpenResty](https://github.com/1Panel-dev/appstore/blob/dev/apps/openresty/1.21.4.3-0-focal/docker-compose.yml)

也就是说可以不使用1panel-network 是吗?
那我是否应该在readme中标注?

**Comment by wanghe-fit2cloud** [comment]
> 还有就是, 请问pr到应用商店 dev分支的应用, 需要怎样才能上架呢

<img width="293" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/dcf96310-d6ab-4286-bef2-b4ea4ab0107f">

**Comment by wanghe-fit2cloud** [comment]
> 也就是说可以不使用1panel-network 是吗?
> 那我是否应该在readme中标注?

在应用能正常部署、启动的前提下，使用哪种网络模式都可以。
是否应在 readme 中标注没有强制要求。

**Comment by vybfi** [comment]
> > 还有就是, 请问pr到应用商店 dev分支的应用, 需要怎样才能上架呢
> 
> <img alt="image" width="293" src="https://private-user-images.githubusercontent.com/46734380/305719902-dcf96310-d6ab-4286-bef2-b4ea4ab0107f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNjQ5MjQsIm5iZiI6MTcwODI2NDYyNCwicGF0aCI6Ii80NjczNDM4MC8zMDU3MTk5MDItZGNmOTYzMTAtZDZhYi00Mjg2LWJlZjItYjRlYTRhYjAxMDdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDEzNTcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZjY4YjlmODgyYzNhOGUyYzc5ZjUzMjAxNDk1ZWNmZWYxYTQ0ODBjZThiMDk1MTQ1NDhiMjAxOTM5NTRkMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ELPUzMUtHOldphV4pGOs8mYAEINfkFh-ckgPhJNgrgc">

请问是否考虑降低一下标准
因为很多软件并无官方支持,  也不一定非常知名.
但是功能是很好用的.
如果为了安全性和权威性而牺牲掉这部分生态, 是否有点可惜了

**Comment by vybfi** [comment]
而且有些应用其实不太需要维护, 只要有一个版本就可以了, 其实也不会增加你们的工作量

**Comment by wanghe-fit2cloud** [comment]
如果是官方审核未通过的应用，优先考虑制作本地应用或者给第三方仓库提交 pr：
https://bbs.fit2cloud.com/t/topic/640

**Comment by vybfi** [comment]
ok
