### ISSUE TITLE
[FEATURE]关于supervisor守护容器进程的建议

### ISSUE THREAD

**Issue by muzidudu** [1Panel-dev/1Panel#3904]
### 1Panel 版本

v1.9.6

### 请描述您的需求或者改进建议

停止命令可以先判断如果是docker exec的容器进程
，可以先搜索进程pid然后进入容器kill进程呢,这样就解决了通过面板停止无效果的痛点

参考[参考链接](https://m.php.cn/faq/519988.html?share_token=BAF0AF8D-F4F9-494D-B59C-A187D0C83EDD&tt_from=copy_link&utm_campaign=client_share&utm_medium=toutiao_ios&utm_source=copy_link docker进程无法停止怎么办-Docker-PHP中文网 - 今日头条)

**Comment by wanghe-fit2cloud** [comment]
重复 issue #2683
