### ISSUE TITLE
[QUESTION]应用商店安装失败问题

### ISSUE THREAD

**Issue by ymyguang** [1Panel-dev/1Panel#3905]
### 问题描述：
在1panel中的应用商店中安装任意应用均报错权限**拒绝错误**，以redis为例，下面是报错的信息：
stderr: open /etc/1panel/1panel/apps/redis/redis/.env: permission denied

但是应用商店显示**已安装**
![image](https://github.com/1Panel-dev/1Panel/assets/34205471/aac39f65-9a61-48d4-9e29-6bf670b5e5ed)点击**进入安装目录**后，下载了以下文件：
![image](https://github.com/1Panel-dev/1Panel/assets/34205471/c2834a61-1dd0-45fd-b936-cfed25ed3af9)

### 主机信息
发行版本 ubuntu-22.04
内核版本 5.15.0-94-generic
系统类型 x86_64

### 1panel权限信息
不知道如何直接验证1panel是否为root权限。通过间接验证：在1panel面板-主机-文件页面中，可以创建、修改、打开、删除/home文件下的任意用户文件及文件夹。（由此推断出获取了root权限）

### 期望结果
正常安装应用

**Comment by wanghe-fit2cloud** [comment]
查看一下 docker-compose 版本

**Comment by ymyguang** [comment]
Docker Compose version v2.20.3

**Comment by wanghe-fit2cloud** [comment]
是使用 snap 安装的 docker 吗？
docker 版本是多少？

**Comment by ymyguang** [comment]
对，snap安装的docker
Docker version 24.0.5, build ced0996

**Comment by wanghe-fit2cloud** [comment]
> 对，snap 安装的 docker

就是这里的问题，目前需要卸载重装 docker，使用 systemd 管理

**Comment by wanghe-fit2cloud** [comment]
可以尝试使用下面的脚本来安装 docker：
```shell
bash <(curl -sSL https://linuxmirrors.cn/docker.sh)
```

**Comment by ymyguang** [comment]
好的

**Comment by ArtIsLong** [comment]
不用卸载docker，重新安装1panel就行了，将1panel安装到用户目录下就可以，目前用的root，安装到/root目录下没问题，普通用户还有待验证
