### ISSUE TITLE
[BUG] Debian 11 面板显示的 ban 时间和配置中并不一致

### ISSUE THREAD

**Issue by mobeicanyue** [1Panel-dev/1Panel#3908]
### 1Panel 版本

v1.9.6

### 问题描述

Debian 11 面板显示的 ban 时间和配置中并不一致，配置里修改了但是面板的显示并不正确

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/81098819/b9fdd9cf-4294-4965-ba45-d92052e338c9)
![image](https://github.com/1Panel-dev/1Panel/assets/81098819/355bcf09-4473-4d9e-9437-95d9cb7cb1fb)

**Comment by ssongliu** [comment]
感谢反馈，需要修改 sshd 部分的配置而不是 Default 的

**Comment by mobeicanyue** [comment]
还有一个问题，文档中提到
https://1panel.cn/docs/user_manual/toolbox/fail2ban/
![image](https://github.com/1Panel-dev/1Panel/assets/81098819/eadac147-abaa-4b16-b8c6-04aa8f947722)
我还有一台 

![image](https://github.com/1Panel-dev/1Panel/assets/81098819/e632acce-88bb-49d9-978c-f072516a324c)

但是我直接 apt install fail2ban 的，
1panel 好像也能正常识别

请问这个 rsyslog 的 作用是什么呢

**Comment by ssongliu** [comment]
Fail2ban 依赖于日志文件 /var/log/auth.log 来屏蔽攻击 IP，Debian12 默认未安装 rsyslog 导致没有 auth.log 文件，所以部分机器需要手动安装一下
