### ISSUE TITLE
[FEATURE] 希望能添加对龙芯的支持loongarch

### ISSUE THREAD

**Issue by DawnMagnet** [1Panel-dev/1Panel#3909]
### 1Panel 版本

*

### 请描述您的需求或者改进建议

*

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们中短期内暂无计划支持，望理解。
> 1Panel 应用商店所有应用均采用容器化方案安装，目前大部分应用也是需要适配 Loongarch 后才可以正常使用。
