### ISSUE TITLE
进入面板时一直显示加载中，进不去[BUG]

### ISSUE THREAD

**Issue by nexus181** [1Panel-dev/1Panel#391]
### 联系方式

2133926859@qq.com

### 1Panel 版本

1.0.2

### 问题描述

开始使用这几天以来，到了晚上11多进入面板就一直显示加载中，等待多时也没有改变，现今天中午也是如此，更换别的浏览器或者使用别人电脑也无法打开

### 重现步骤

搜索面板地址

**Comment by bulesky89857** [comment]
什么环境，本地还是vps？

**Comment by nexus181** [comment]
> 什么环境，本地还是vps？

vps, 一台centos一直加载，一台Ubuntu刚安装面板直接打不开

**Comment by bulesky89857** [comment]
首先vps防火墙开放面板端口，看你描述难道是海外白嫖或者廉价vps？可能就是vps本身的原因了。

**Comment by nexus181** [comment]
> 首先vps防火墙开放面板端口，看你描述难道是海外白嫖或者廉价vps？可能就是vps本身的原因了。

阿里云国内的vps,安装宝塔面板就能打开，就是加载不出1panel

**Comment by zyyfit** [comment]
您好，目前最新版是1.0.5版本，修复了几个登录问题和ubuntu系统的问题，您可以安装一下最新版看看是否正常
如果还是有这种问题的话，可以提供一下1panel的日志文件，或者加入我们的企业微信交流群咨询一下
