### ISSUE TITLE
[QUESTION]无法申请ZeroSSL证书

### ISSUE THREAD

**Issue by Concises** [1Panel-dev/1Panel#3910]
### 请描述您的问题

ZeroSSL证书一直申请失败 换用Let's Encrypt申请就没问题
然后还发现Acme账户里添加ZeroSSL账号类型也不行了
是面板的问题还是ZeroSSL的问题呢

**Comment by zhengkunwang223** [comment]
ZeroSSL 访问不太稳定 大概率是网络问题

**Comment by wanghe-fit2cloud** [comment]
先关闭该 Issue 了，后续如果还有问题继续在该 Issue 中讨论。
> 本地环境未能复现上述问题
