### ISSUE TITLE
请问有没有支持多服务器节点部署的打算？

### ISSUE THREAD

**Issue by milo-container** [1Panel-dev/1Panel#3913]
### 1Panel 版本

1.0

### 请描述您的需求或者改进建议

请问有没有支持内网多服务器节点部署的打算？

**Comment by zhengkunwang223** [comment]
有的 2.0 计划搞多主机 但是大概率是专业版功能

**Comment by wanghe-fit2cloud** [comment]
多主机管理相关需求的讨论，统一汇总到该 issue [#2692](https://github.com/1Panel-dev/1Panel/issues/2692)
