### ISSUE TITLE
[BUG]UI界面问题

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3916]
### 1Panel 版本

v1.9.6

### 问题描述

安装中图标没有对齐
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/70c55d60-23e3-47b0-acd1-ac5f914e8a14)

### 重现步骤

进入应用商店页面安装应用

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.0-lts 版本已发布。
