### ISSUE TITLE
[BUG] 无法删除不存在的数据库备份列表

### ISSUE THREAD

**Issue by glxaa** [1Panel-dev/1Panel#3919]
### 1Panel 版本

v1.9.6

### 问题描述

数据库的备份列表中，无法删除不存在的备份
![image](https://github.com/1Panel-dev/1Panel/assets/119774429/65a6526f-88c9-41a7-8ff2-8fdb8eb4ac2c)

### 重现步骤

1.备份账号设置中添加WebDav选项
2.执行WebDav备份，成功
3.在备份账号删除WebDav配置
4.已备份的数据因为无法连接WebDav导致无法删除

### 期待的正确结果

正确删除

### 相关日志输出

```shell
删除备份记录 [db_nextcloud_20240220100948h61u1.sql.gz]	
失败	
2024-02-20 13:27:57
信息
服务内部错误: record not found
```

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/119774429/27f0e262-ea7d-4972-b5bc-6a353383b1f1)

**Comment by glxaa** [comment]
将删除的WebDav重新配置，删除不存在的备份列表不再报错。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述删除逻辑。

**Comment by wanghe-fit2cloud** [comment]
先把该 issue 打开了，因为在正式版本发布前，还需要测试团队来回归上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.0-lts 版本已发布。
