### ISSUE TITLE
[FEATURE] 希望能保存主机密码或者密钥信息

### ISSUE THREAD

**Issue by bambuo** [1Panel-dev/1Panel#392]
### 联系方式

845586878@qq.com

### 1Panel 版本

v1.0.2

### 问题描述

主机登录认证方式为密钥输入，界面上无法保存密钥信息，终端无法正确连接

### 重现步骤

切换到主机-终端页面即可重现

### 期待的正确结果

可以保存主机连接信息，例如密码/密钥

### 附加信息

![image](https://user-images.githubusercontent.com/44076708/227455293-e39c289f-6d2c-4c87-9acb-4edeb81ae643.png)

**Comment by bambuo** [comment]
无法连接的问题已解决，原因是 nginx 配置中未配置如下信息

```
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";
proxy_buffers 4 128k;
proxy_busy_buffers_size 128k;
```
希望能保存密码或者密钥信息，目前发现不会保存

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会支持是否保存主机密码、密钥的功能。

**Comment by wanghe-fit2cloud** [comment]
v1.1.0 版本已发布。
