### ISSUE TITLE
[FEATURE] 应用商店添加 OnlyOffice

### ISSUE THREAD

**Issue by glxaa** [1Panel-dev/1Panel#3920]
### 1Panel 版本

v1.9.6

### 请描述您的需求或者改进建议

应用商店添加 OnlyOffice 

### 请描述你建议的实现方案

1.依赖数据库（MySQL、postgresql、mariadb），依赖redis，依赖rabbitmq，可通过应用商店配置
2.编排docker-compose.yml 模板如下：
version: '2'
services:
  onlyoffice-documentserver:
    build:
      context: .
      dockerfile: /opt/temp/production.dockerfile
    container_name: onlyoffice-documentserver
    deploy:
            resources:
                limits:
                    cpus: '4'
                    memory: 16G
    environment:
      - DB_TYPE=mariadb
      - DB_HOST=10.10.2.6
      - DB_PORT=3306
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - DB_PWD=xxxxxx
      - AMQP_URI=amqp://rabbitmq:rabbitmq@10.10.2.6:5672
      - JWT_SECRET=1122
      - USE_UNAUTHORIZED_STORAGE=true
      - REDIS_SERVER_HOST=10.10.2.6
      - REDIS_SERVER_PORT=6379
      - REDIS_SERVER_PASS=xxxxxx
    ports:
      - '1122:80'
      - '1123:443'
    stdin_open: true
    restart: always
    stop_grace_period: 60s
    volumes:
       - /opt/1panel/apps/onlyOffice/ssl/:/var/www/onlyoffice/Data/certs

### 附加信息

社区完整的OnlyOffice还具有邮箱等功能，对这个的需求不大，未列出。

**Comment by wanghe-fit2cloud** [comment]
近期版本会基于 [onlyoffice/documentserver](https://hub.docker.com/r/onlyoffice/documentserver) 镜像来构建应用程序并上架到应用商店。

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/3863
