### ISSUE TITLE
[QUESTION] 使用nextcloud 的WebDav作为备份账号时，无法正常上传备份文件

### ISSUE THREAD

**Issue by glxaa** [1Panel-dev/1Panel#3921]
### 请描述您的问题

使用nextcloud 的WebDav作为备份账号时，无法正常上传备份文件
nextcloud版本：27.1.6
WebDav配置如下：
![image](https://github.com/1Panel-dev/1Panel/assets/119774429/9fad8cab-da9c-4328-9a2d-c03797d91835)
上传后结果如下：
![image](https://github.com/1Panel-dev/1Panel/assets/119774429/d0a6b5a5-96e0-4e53-a35f-290d8da27739)
使用alist作为WebDav没有任何问题，alist使用nextcloud 的WebDav也没有问题，但是当1panel使用nextcloud 的WebDav就会出现无法正确的上传备份文件的问题。
请问是我哪里出了差错？

**Comment by ssongliu** [comment]
感谢反馈，正常添加 webdav 的时候，会在目标目录下生成一个 test/1panel 文件，麻烦检查一下是否存在
