### ISSUE TITLE
[QUESTION]定时 备份系统快照 快照大小成二倍数增长

### ISSUE THREAD

**Issue by d4renk** [1Panel-dev/1Panel#3923]
### 请描述您的问题

正常情况 应该每天备份快照大小差不多 但实际过程中快照大小成二倍数增长
发行版本 ubuntu-22.04 内核版本 5.15.0-73-fips 系统类型 x86_64 1panel版本：v1.9.6
开启计划时系统还剩余12G 空间
![image](https://github.com/1Panel-dev/1Panel/assets/64531014/bf20ef59-dcc3-4e49-a65c-375230125870)
![image](https://github.com/1Panel-dev/1Panel/assets/64531014/65c80bbe-2693-4269-a6f1-ccd20d6dd94b)
![image](https://github.com/1Panel-dev/1Panel/assets/64531014/4091ea65-9b45-4557-a78d-b55252fa6e75)
![image](https://github.com/1Panel-dev/1Panel/assets/64531014/1e55e1ad-6e3a-47c8-b3fe-00557ae0ab59)
![image](https://github.com/1Panel-dev/1Panel/assets/64531014/34368581-02a1-4717-9636-7539248470d3)
然后硬盘容量满了
![image](https://github.com/1Panel-dev/1Panel/assets/64531014/8e81f622-4235-4813-a739-1156d0c4a65c)

**Comment by wanghe-fit2cloud** [comment]
需要进入 `备份账号` 页面，将服务器磁盘路径修改为 `非 1Panel 安装目录`。
> 因为创建快照时，会备份 `1Panel 安装目录`

**Comment by d4renk** [comment]
> 需要进入 `备份账号` 页面，将服务器磁盘路径修改为 `非 1Panel 安装目录`。
> 
> > 因为创建快照时，会备份 `1Panel 安装目录`

默认服务器磁盘路径是/opt/1panel/backup
这个backup路径是存放备份的 正常的逻辑不应该是 备份快照时候 排除这个路径嘛

**Comment by wanghe-fit2cloud** [comment]
> > 需要进入 `备份账号` 页面，将服务器磁盘路径修改为 `非 1Panel 安装目录`。
> > > 因为创建快照时，会备份 `1Panel 安装目录`
> 
> 默认服务器磁盘路径是/opt/1panel/backup 这个backup路径是存放备份 正常的逻辑不应该是 备份快照时候 排除这个路径嘛

你先按照上面的提示操作，后面版本优化。

**Comment by d4renk** [comment]
![IMG_20240221_010724.jpg](https://github.com/1Panel-dev/1Panel/assets/64531014/0258b466-c17b-4334-9e81-8e66231989e5)

我有一个疑问，为什么没有将 服务器磁盘路径的变量传递到这个地方，而是直接将路径硬编码为"/opt/1panel/backup"
这可能导致当用户将服务器磁盘路径修改为"/opt/1panel/example"时出现重复打包的情况。

**Comment by ssongliu** [comment]
> ![IMG_20240221_010724.jpg](https://private-user-images.githubusercontent.com/64531014/306355986-0258b466-c17b-4334-9e81-8e66231989e5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0Nzk3OTcsIm5iZiI6MTcwODQ3OTQ5NywicGF0aCI6Ii82NDUzMTAxNC8zMDYzNTU5ODYtMDI1OGI0NjYtYzE3Yi00MzM0LTllODEtOGU2NjIzMTk4OWU1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAxMzgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MzE2YTQyOGI0ODEyOWYzYTYzODEyZjc5NzM2M2MwMGJlZjE0MzIwNWE0MDY3NDkyM2E5MWIzNmUzMDIzMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XJR4y20mJeLtJI-fsEAVe-ikuUDPvoxnfs3zLT1_MCI)
> 
> 我有一个疑问，为什么没有将 服务器磁盘路径的变量传递到这个地方，而是直接将路径硬编码为"/opt/1panel/backup" 这可能导致当用户将服务器磁盘路径修改为"/opt/1panel/example"时出现重复打包的情况。

这里直接用的相对目录而不是绝对目录，不是硬编码 /opt/1panel/backup

**Comment by wanghe-fit2cloud** [comment]
v1.10.0-lts 版本已发布。
