### ISSUE TITLE
[QUESTION]OpenResty反代MinIO的API端口无法进行上传等操作

### ISSUE THREAD

**Issue by GeekF0rum** [1Panel-dev/1Panel#3924]
### 请描述您的问题

使用S3 Browser以及Halo的S3服务时，MinIO的API端口反代的域名无法进行上传等操作，但是源站IP+端口的方式一切正常。
1、服务器版本
发行版本 ubuntu-22.04
内核版本 5.15.0-76-generic
系统类型 x86_64
2、环境版本
OpenResty版本 1.21.4.3-0-focal
MinIO版本 2023-01-05
![image-20240220154806402](https://github.com/1Panel-dev/1Panel/assets/153544876/e64f6352-52a7-44a3-a3a7-a87b934044e0)
![image-20240220154824608](https://github.com/1Panel-dev/1Panel/assets/153544876/3b9876e6-2336-430a-baf3-a29d47f3bb4e)
![image-20240220155107571](https://github.com/1Panel-dev/1Panel/assets/153544876/843b117a-caff-4f5a-9494-3fc26bf76e6b)
![image-20240220155133981](https://github.com/1Panel-dev/1Panel/assets/153544876/88a4b7ef-2b95-4cae-9959-afe30ac6f8aa)
![image-20240220155211965](https://github.com/1Panel-dev/1Panel/assets/153544876/e149791a-9116-4986-b80e-d7efe36ae1e7)
![image-20240220155230873](https://github.com/1Panel-dev/1Panel/assets/153544876/1e62722c-47aa-4ff8-beae-1b7d9df86e02)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
在 MinIO 官方有提供针对反向代理配置的说明，建议参考后进入`网站设置`页面，手动修改配置：
https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html

> 1Panel作为一个平台，不会专门针对单个项目进行独立配置。
同时，1Panel 也支持通过手动修改配置文件来进行优化。

**Comment by GeekF0rum** [comment]
但是在反向代理中不是已经监测了9001
`location ^~ / {
    proxy_pass http://127.0.0.1:9001; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header X-Cache $upstream_cache_status; 
}`

**Comment by GeekF0rum** [comment]
> 感谢反馈。 在 MinIO 官方有提供针对反向代理配置的说明，建议参考后进入`网站设置`页面，手动修改配置： https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html
> 
> > 1Panel作为一个平台，不会专门针对单个项目进行独立配置。
> > 同时，1Panel 也支持通过手动修改配置文件来进行优化。
不是在反向代理中已经监测了吗？
location ^~ / {
    proxy_pass http://127.0.0.1:9001; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header X-Cache $upstream_cache_status; 
}

**Comment by GeekF0rum** [comment]
反向代理中不是已经检测了9001
```
location ^~ / {
    proxy_pass http://127.0.0.1:9001; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header X-Cache $upstream_cache_status; 
}
```

**Comment by GeekF0rum** [comment]
反向代理源文
```
location ^~ / {
    proxy_pass http://127.0.0.1:9001; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header X-Cache $upstream_cache_status; 
}
```
OpenResty配置文件
```
server {
    listen 80 ; 
    server_name example.com; 
    index index.php index.html index.htm default.php default.htm default.html; 
    proxy_set_header Host $host; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header X-Forwarded-Host $server_name; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_http_version 1.1; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    access_log /www/sites/MinIO/log/access.log; 
    error_log /www/sites/MinIO/log/error.log; 
    access_by_lua_file /www/common/waf/access.lua; 
    set $RulePath /www/sites/MinIO/waf/rules; 
    set $logdir /www/sites/MinIO/log; 
    set $redirect on; 
    set $attackLog on; 
    set $CCDeny off; 
    set $urlWhiteAllow off; 
    set $urlBlockDeny off; 
    set $argsDeny off; 
    set $postDeny off; 
    set $cookieDeny off; 
    set $fileExtDeny off; 
    set $ipBlockDeny off; 
    set $ipWhiteAllow off; 
    location ^~ /.well-known/acme-challenge {
        allow all; 
        root /usr/share/nginx/html; 
    }
    include /www/sites/MinIO/proxy/*.conf; 
}
```

**Comment by wanghe-fit2cloud** [comment]
MinIO 官方文档已经给出了具体配置，需要参考后手动修改 1Panel 反代网站配置。

**Comment by GeekF0rum** [comment]
已经尝试修改过，但是并没有效果，翻了一下lssues，也有其他人遇到这个问题，是否在论坛输出相关问题的文档呢？

**Comment by miyling** [comment]
多番排查，OpenResty默认配置了反代缓存，而反代缓存会将HEAD请求转换为GET请求进行缓存，导致HEAD请求403从而引发问题点

只需要在反代站点加入以下配置即可解决
```
proxy_cache_convert_head off;
```

相关链接：
https://github.com/minio/minio/issues/4120
https://github.com/minio/minio/discussions/17097

以下是我使用的站点配置
```
server {
    listen 80 ; 
    listen 443 ssl ; 
    server_name xxx.com; 
    access_log /www/sites/xxx.com/log/access.log main; 
    error_log /www/sites/xxx.com/log/error.log; 
    if ($server_port !~ 443) {
        rewrite ^(/.*)$ https://$host$1 permanent; 
    }
    ssl_certificate /www/sites/xxx.com/ssl/fullchain.pem; 
    ssl_certificate_key /www/sites/xxx.com/ssl/privkey.pem; 
    ssl_protocols TLSv1.3 TLSv1.2 TLSv1.1 TLSv1; 
    ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:!aNULL:!eNULL:!EXPORT:!DSS:!DES:!RC4:!3DES:!MD5:!PSK:!KRB5:!SRP:!CAMELLIA:!SEED; 
    ssl_prefer_server_ciphers on; 
    ssl_session_cache shared:SSL:10m; 
    ssl_session_timeout 10m; 
    add_header Strict-Transport-Security "max-age=31536000"; 
    ignore_invalid_headers off; 
    client_max_body_size 0; 
    proxy_buffering off; 
    proxy_request_buffering off; 
    proxy_cache_convert_head off;
    include /www/sites/xxx.com/proxy/*.conf; 
}
```

**Comment by cli-r** [comment]
> 多番排查，OpenResty默认配置了反代缓存，而反代缓存会将HEAD请求转换为GET请求进行缓存，导致HEAD请求403从而引发问题点
> 
> 只需要在反代站点加入以下配置即可解决
> 
> ```
> proxy_cache_convert_head off;
> ```
> 
> 相关链接： [minio/minio#412](https://github.com/minio/minio/pull/412) [minio/minio#17097](https://github.com/minio/minio/discussions/17097)
> 
> 以下是我使用的站点配置
> 
> ```
> server {
>     listen 80 ; 
>     listen 443 ssl ; 
>     server_name xxx.com; 
>     access_log /www/sites/xxx.com/log/access.log main; 
>     error_log /www/sites/xxx.com/log/error.log; 
>     if ($server_port !~ 443) {
>         rewrite ^(/.*)$ https://$host$1 permanent; 
>     }
>     ssl_certificate /www/sites/xxx.com/ssl/fullchain.pem; 
>     ssl_certificate_key /www/sites/xxx.com/ssl/privkey.pem; 
>     ssl_protocols TLSv1.3 TLSv1.2 TLSv1.1 TLSv1; 
>     ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:!aNULL:!eNULL:!EXPORT:!DSS:!DES:!RC4:!3DES:!MD5:!PSK:!KRB5:!SRP:!CAMELLIA:!SEED; 
>     ssl_prefer_server_ciphers on; 
>     ssl_session_cache shared:SSL:10m; 
>     ssl_session_timeout 10m; 
>     add_header Strict-Transport-Security "max-age=31536000"; 
>     ignore_invalid_headers off; 
>     client_max_body_size 0; 
>     proxy_buffering off; 
>     proxy_request_buffering off; 
>     proxy_cache_convert_head off;
>     include /www/sites/cloudoss.dg-school.com/proxy/*.conf; 
> }
> ```

非常感谢，这个解决方案完美的解决了我的问题，之前翻阅了很多issue都没有解决。在minio官方文档中并未提及这一点，在此之前我还怀疑是ssl的问题，试错了方向。
