### ISSUE TITLE
[FEATURE] 请求redis支持重复安装

### ISSUE THREAD

**Issue by maxbad** [1Panel-dev/1Panel#3927]
### 1Panel 版本

v1.9.6

### 请描述您的需求或者改进建议

同一个服务器需要2个redis的时候,一个是可写的,一个是从服务同步其他服务器数据

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by MiderWong** [comment]
+1,同求

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
