### ISSUE TITLE
[FEATURE] mysql备份指定表

### ISSUE THREAD

**Issue by maxbad** [1Panel-dev/1Panel#3929]
### 1Panel 版本

v1.9.6

### 请描述您的需求或者改进建议

mysql备份的时候,支持勾选指定的数据表.

### 附加信息

bt的实现
![image](https://github.com/1Panel-dev/1Panel/assets/37558406/b4d0c28c-b42f-4eb6-b0d3-22a16649af65)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们中短期内暂不考虑支持上述需求，望理解。
