### ISSUE TITLE
[BUG]缺少监控宿主机硬盘

### ISSUE THREAD

**Issue by ChungyuCheung** [1Panel-dev/1Panel#393]
### 1Panel 版本

1.0.3

### 问题描述

宿主机有多块硬盘，但从概览的状态来看， 只识别到第一块硬盘（通常是系统盘）

### 重现步骤

可尝试挂载多块硬盘来看结果

### 期待的正确结果

显示全部的硬盘状态

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，只识别到系统硬盘的问题我们会在后续版本中解决。

**Comment by wanghe-fit2cloud** [comment]
v1.0.4 版本已修复。
