### ISSUE TITLE
[BUG] 无法从应用商店安装 ChatGPT-Next-Web

### ISSUE THREAD

**Issue by muxinxy** [1Panel-dev/1Panel#3931]
### 1Panel 版本

v1.9.6

### 问题描述

无法从应用商店安装 ChatGPT-Next-Web，报错：

> docker-compose.yml 文件获取失败！<?xml version="1.0" encoding="UTF-8"?> <Error> <Code>NoSuchKey</Code> <Message>The specified key does not exist.</Message> <RequestId>65D495B1BFA7DB11EE616ECD</RequestId> <HostId>apps-assets.fit2cloud.com</HostId> <Key>stable/1panel/chatgpt-next-web/2.10.1/docker-compose.yml</Key> </Error>

### 重现步骤

从应用商店安装 ChatGPT-Next-Web

### 期待的正确结果

正常安装

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/32673109/80a0d819-598d-401b-ac80-0a25fd73d4cb)

**Comment by zhengkunwang223** [comment]
点击同步应用商店 然后再安装
