### ISSUE TITLE
[BUG] 添加webdav时验证超时时间太短，导致无法添加云盘类存储

### ISSUE THREAD

**Issue by wzcsimon123** [1Panel-dev/1Panel#3932]
### 1Panel 版本

v1.9.6

### 问题描述

alist webdav分别挂载本地磁盘和阿里云盘，添加webdav存储时，选择webdav中的本地存储可以正常添加，但由于阿里云盘进行写入时反应较慢（经测试写入文件要等待5-10s才会开始），所以添加阿里云盘时就会提示备份账号测试连接失败` WriteStream /dav/al/test/1panel: 500`，但实际已经成功创建了test文件夹。

**Comment by ssongliu** [comment]
感谢反馈，test 文件夹创建完了，下面的 1panel 文件有正常上传吗？

**Comment by wzcsimon123** [comment]
> 感谢反馈，test 文件夹创建完了，下面的 1panel 文件有正常上传吗？

没有

**Comment by ssongliu** [comment]
> > 感谢反馈，test 文件夹创建完了，下面的 1panel 文件有正常上传吗？
> 
> 没有

麻烦贴一下创建 webdav 的截图

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/3915

**Comment by almas-x** [comment]
也遇到同样的问题，能创建出 1panel /test 文件夹，然后就提示 `备份账号测试连接失败 WriteStream /dav/aliyun/1panel/test/1panel: 423`
