### ISSUE TITLE
将文件夹大小改为文件夹内所有文件的总大小而不是单文件夹的大小

### ISSUE THREAD

**Issue by swt1me** [1Panel-dev/1Panel#3934]
### 1Panel 版本

1.9.6

### 请描述您的需求或者改进建议

将文件夹大小改为文件夹内所有文件的总大小而不是单文件夹的大小
![屏幕截图 2024-02-21 121553](https://github.com/1Panel-dev/1Panel/assets/122451668/d19a383e-e3a4-463d-916b-202cb5986785)

![屏幕截图 2024-02-21 121858](https://github.com/1Panel-dev/1Panel/assets/122451668/47b1b536-a900-4f75-890c-1fdf23dc0b22)
这两个分辨是Windows和1panel显示的hexo的大小

**Comment by zhengkunwang223** [comment]
好的 后续版本优化

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
