### ISSUE TITLE
[FEATURE]登录日志小功能改进

### ISSUE THREAD

**Issue by ayuanlmo** [1Panel-dev/1Panel#3935]
### 1Panel 版本

v1.9.6

### 请描述您的需求或者改进建议

在登录日志里，是否可以直接通过列表操作进行屏蔽IP，甚至多选。

![image](https://github.com/1Panel-dev/1Panel/assets/50331004/9ea31a72-9191-45e9-b15c-dc6838d540eb)

(此需求仅为本人实际使用时考虑，仅个人观点)

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本新增了 Fail2ban 管理功能，可以进入 `工具箱` 页面，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/bcaeee50-7f20-4776-892b-4954c2d09382)

> 配置好规则后自动管理。

**Comment by ayuanlmo** [comment]
我的意思是在日志里，一键加入黑名单就不用一个一个来了

**Comment by wanghe-fit2cloud** [comment]
> 我的意思是在日志里，一键加入黑名单就不用一个一个来了

收到，我们后续版本考虑一下这个建议。

**Comment by ayuanlmo** [comment]
感谢🙏

取得 iOS 版 Outlook<https://aka.ms/o0ukef>
________________________________
寄件者: wanghe ***@***.***>
寄件日期: Wednesday, February 21, 2024 1:46:06 PM
收件者: 1Panel-dev/1Panel ***@***.***>
副本: ayuanlmo ***@***.***>; Author ***@***.***>
主旨: Re: [1Panel-dev/1Panel] [FEATURE]登录日志小功能改进 (Issue #3935)


我的意思是在日志里，一键加入黑名单就不用一个一个来了

收到，我们后续版本考虑一下这个建议。
