### ISSUE TITLE
[FEATURE]关于添加 MySQL 远程服务器的问题

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3936]
### 1Panel 版本

v1.9.6

### 请描述您的需求或者改进建议

添加 MySQL 远程服务器并勾选 SSL，需要客户端证书和密钥。
但是 Azure MySQL 只提供 CA 证书，无法自行添加客户端证书和密钥。

### 请描述你建议的实现方案

希望能够将客户端证书和密钥设为可选

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本优化上述功能。

**Comment by wanghe-fit2cloud** [comment]
v1.10.0-lts 版本已发布。
