### ISSUE TITLE
[BUG]数据库备份等相关使用问题

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3937]
### 1Panel 版本

v1.9.6

### 问题描述

版本： v1.9.6
问题一：数据库备份的时候，如果远程数据库有多个实例，里面有相同的数据库的时候，在选贼备份数据库的时候，无法区分出备份的是哪个远程实例的库；
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/66b698ef-c75d-4c21-a273-50ffb483a427)

问题二：数据库备份失败，看不到任何失败相关的日志，这块能否展示出来；
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/7302d25e-5b76-4166-bc99-fde3b81bc5b8)

### 重现步骤

创建 `备份数据库` 类型计划任务

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.0-lts 版本已发布。
