### ISSUE TITLE
[BUG]Windows docker下 安装1panel  无法生成账号密码，而且不能修改端口号

### ISSUE THREAD

**Issue by leeaikong** [1Panel-dev/1Panel#394]
### 1Panel 版本

1.03

### 问题描述

[BUG]我是在本地环境下测试的。
window10是 安装 Docker Desktop， wsl子系统方式运行的
然后添加 centos7.9
然后进容器 安装1panel  
**问题1： 无法生成账号密码，
问题2 ：不能修改端口号**
发现安装成功后 没有显示账号密码    用user info 也没查到

run容器的时候 我只添加了几个常用的端口映射，但是安装面板生成的端口号是是随机的，所以无法登陆面板，最好可以1pctl命令修改端口号
 
![2023-3-24 18-34-10](https://user-images.githubusercontent.com/40814658/227498476-8e929218-1052-4cc8-ab7f-1fd77588ac54.png)
![2023-3-24 18-38-37](https://user-images.githubusercontent.com/40814658/227499725-4e363074-034a-4569-a661-f33ea1d22059.png)

### 重现步骤

以上。

**Comment by leeaikong** [comment]
![2023-3-24 18-38-37](https://user-images.githubusercontent.com/40814658/227499409-5aa1947b-a0d9-4235-bef2-74d1cde306e8.png)

**Comment by wanghe-fit2cloud** [comment]
1、1panel 初始化账号密码是用户在 Web 页面自定义生成的。
2、1pctl 修改端口的需求，我们会在后续版本中支持。
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/46734380/227566109-626c32b4-8187-4ff5-b5a5-60e402198bf2.png">

**Comment by wanghe-fit2cloud** [comment]
v1.0.4 版本已支持用户在安装 1Panel 时自定义端口。
