### ISSUE TITLE
[FEATURE] 建议：添加多个WebDav的配置选项

### ISSUE THREAD

**Issue by glxaa** [1Panel-dev/1Panel#3940]
### 1Panel 版本

v1.9.6

### 请描述您的需求或者改进建议

目前只能添加一个WebDav用于备份，当用户想切换备份到不同的目的地时需要重新修改WebDav，稍许麻烦：
![image](https://github.com/1Panel-dev/1Panel/assets/119774429/9921ae62-f79d-4bf0-8d46-922e43a4eecb)

### 请描述你建议的实现方案

![image](https://github.com/1Panel-dev/1Panel/assets/119774429/8cfecd2c-72ff-4e54-bc2a-392077eeb929)
这里可以添加动态条目，用户选择 + 时可配置第二个WebDav
或者其他可实现该功能的设计

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持添加多个相同类型的备份账号。

**Comment by wanghe-fit2cloud** [comment]
支持添加同类型多个备份账号的需求统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4796
