### ISSUE TITLE
[QUESTION]ssh会话出现问题

### ISSUE THREAD

**Issue by 0Evo** [1Panel-dev/1Panel#3947]
### 请描述您的问题

1panel版本:v1.9.6

问题:

ssh管理->会话 没有显示任何会话
进程管理->进程 搜索名称ssh或者sshd可以正常显示进程

如图:

![{8819EB35-7988-4c27-9FEE-23EA9084AB96}](https://github.com/1Panel-dev/1Panel/assets/102132588/54c7ddbf-7c3a-47a5-941b-bd85976ccad7)

![{E2D3268F-300E-4c49-A862-F4C4A8C94DC5}](https://github.com/1Panel-dev/1Panel/assets/102132588/75276510-1d8b-4b42-a394-d3fbcc769eea)

系统日志显示正常

**Comment by wanghe-fit2cloud** [comment]
你是已经 `ssh ewall@服务器IP` 登录成功，然后切换到会话页面发现没有显示记录吗？
> 刚刚在本地环境测试，也未能复现问题。

**Comment by 0Evo** [comment]
> 你是已经 `ssh ewall@服务器IP` 登录成功，然后切换到会话页面发现没有显示记录吗？
> 
> > 刚刚在本地环境测试，也未能复现问题。

是的，我是ssh连接后在切换到会话页面的，登录日志中也显示了我的一切信息，除了归属地，另外，我使用的是ipv6的方式ssh连接到服务器的，不知道和这个有没有关系，在终端里连接或者用ipv4连接可以在登录里正确显示归属地

**Comment by 0Evo** [comment]
> > 你是已经 `ssh ewall@服务器IP` 登录成功，然后切换到会话页面发现没有显示记录吗？
> > > 刚刚在本地环境测试，也未能复现问题。
> 
> 是的，我是ssh连接后在切换到会话页面的，登录日志中也显示了我的一切信息，除了归属地，另外，我使用的是ipv6的方式ssh连接到服务器的，不知道和这个有没有关系，在终端里连接或者用ipv4连接可以在登录里正确显示归属地

我刚刚尝试用局域网ipv4方式ssh连接，还是没有会话显示，应该与ipv6无关

**Comment by wanghe-fit2cloud** [comment]
你使用的是哪款 ssh 客户端软件，我本地看一下能不能复现问题。
> 你浏览器打开两个窗口，`主机` - `终端` 和 `主机` - `SSH 管理` - `会话`，观察一下是否正常。

**Comment by 0Evo** [comment]
> 你使用的是哪款 ssh 客户端软件，我本地看一下能不能复现问题。
> 
> > 你浏览器打开两个窗口，`主机` - `终端` 和 `主机` - `SSH 管理` - `会话`，观察一下是否正常。

![4c2cdfc89c01236eb783cdfe77d31554](https://github.com/1Panel-dev/1Panel/assets/102132588/36e569aa-0dbf-4b16-8a98-c807c30c0d6b)
![8f5a95aea64ac8b9c361cb0f08053d96](https://github.com/1Panel-dev/1Panel/assets/102132588/010fd6f0-8ced-4c50-b025-b9f3a00576bd)

用的PuTTY，浏览器终端连接也没能显示,重启面板依旧但进程管理中搜索ssh正常

**Comment by wanghe-fit2cloud** [comment]
没有能复现问题。

**Comment by wanghe-fit2cloud** [comment]
1Panel 服务器操作系统是？

**Comment by 0Evo** [comment]
> 1Panel 服务器操作系统是？

archlinux arm64

**Comment by wanghe-fit2cloud** [comment]
> > 1Panel 服务器操作系统是？
> 
> archlinux arm64

在本地 arch 开发机测试仍未复现问题。

你可以进微信交流群添加 `王贺` 好友，远程你环境定位一下问题。
> 先关闭该 issue 了，后续有问题再继续讨论。
