### ISSUE TITLE
[QUESTION] mysql安装的时候开启了端口外部访问，但外部通过服务器公网ip加3306的端口还是访问不到数据库

### ISSUE THREAD

**Issue by huangbh1024** [1Panel-dev/1Panel#3954]
### 请描述您的问题

![image](https://github.com/1Panel-dev/1Panel/assets/72372968/c7b2f7a9-ae84-408a-930b-35f9b16a8be7)
![image](https://github.com/1Panel-dev/1Panel/assets/72372968/2dd6aff4-78c8-4eed-aba0-526e9c5ccb6a)

**Comment by wanghe-fit2cloud** [comment]
去 `容器` 页面查看一下 MySQL 容器运行状态和日志。
如果是公有云服务器，要去安全组打开 3306 端口

**Comment by huangbh1024** [comment]
> 去 `容器` 页面查看一下 MySQL 容器运行状态和日志。 如果是公有云服务器，要去安全组打开 3306 端口

安全组3306端口是有放行的，服务器内部使用127.0.01是能访问得到数据库的，容器状态已启动，日志看不出啥问题

**Comment by wanghe-fit2cloud** [comment]
`netstat -ntlp | grep 3306`  命令截图

**Comment by huangbh1024** [comment]
> `netstat -ntlp | grep 3306` 命令截图

![image](https://github.com/1Panel-dev/1Panel/assets/72372968/2ef008c2-d2e9-45f4-b520-79f4abc2a7e3)

**Comment by wanghe-fit2cloud** [comment]
> 服务器内部使用127.0.01是能访问得到数据库的，容器状态已启动，日志看不出啥问题

MySQL 服务没有问题，可能还是你 1Panel 服务器所在网络环境导致的吧，先自行排查一下。

**Comment by huangbh1024** [comment]
> > 服务器内部使用127.0.01是能访问得到数据库的，容器状态已启动，日志看不出啥问题
> 
> MySQL 服务没有问题，可能还是你 1Panel 服务器所在网络环境导致的吧，先自行排查一下。

重启防火墙正常了
