### ISSUE TITLE
[FEATURE]Jenkins 安装的时候，请给予 LTS 版本与 Weekly 版本，让用户选择安装

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3956]
### 1Panel 版本

v1.9.6

### 请描述您的需求或者改进建议

Jenkins 安装的时候，可以区分 lts 版本与 Regular releases (Weekly）让用户选择安装，Weekly 在生产环境经常有问题
后面在终端自己通过命令 docker pull jenkins/jenkins:lts下载了 lts 稳定版本以后才得以解决

希望商店改进下，支持拉去两种镜像进行部署

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
已经支持 2.440.1-lts 版本。
> 进入 `应用商店` 页面，手动点击右上角的 `更新应用列表` 按钮获取最新版本即可。
