### ISSUE TITLE
[QUESTION]运行环境扩展模块问题

### ISSUE THREAD

**Issue by sanqiy** [1Panel-dev/1Panel#3957]
### 请描述您的问题

我在编辑运行环境时候，扩展模块选择了xloader，但是在网站依然无法使用，查询了PHP 扩展列表没有发现这个模块
希望可以增加xloader模块，及其他模块，或者为用户提供添加模块的地方和方法
可参考
https://zhuanlan.zhihu.com/p/635196100?utm_id=0

**Comment by wanghe-fit2cloud** [comment]
参考论坛中这篇文章：
https://bbs.fit2cloud.com/t/topic/2073

**Comment by wanghe-fit2cloud** [comment]
PHP运行环境支持自定义扩展相关需求，统一汇总到该 issue #3943
