### ISSUE TITLE
[BUG]开启IPV6解析后，商店和检测更新会无法访问

### ISSUE THREAD

**Issue by 4867896** [1Panel-dev/1Panel#3958]
### 1Panel 版本

1.9.6

### 问题描述

- 开启IPV6后，设备获取IPV6地址后无法进行更新和访问应用商店。会提示
   请求失败 Get "https://apps-assets.fit2cloud.com/stable/1panel.json.version.txt": net/http: TLS handshake timeout
- 通过ping 服务器的IPV6地址，可以ping通，但是访问资源会超时。
- 关闭IPV6DNS解析后，使用IPV4地址服务正常。

### 重现步骤

开启设备IPV6地址解析，即可复现。

**Comment by wanghe-fit2cloud** [comment]
1Panel 系统资源均统一放置在阿里 OSS，是全球加速的 CDN。
还有，`apps-assets.fit2cloud.com` 地址也已支持 IPv6 DNS 解析，如图：
<img width="956" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/c35e5262-5b62-4ffc-8324-e594ec42408d">

**Comment by 4867896** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/32392205/58c5979c-7b47-464c-b063-f6764186bf86)
能够ping上但是无法下载

**Comment by wanghe-fit2cloud** [comment]
我们未能在本地和阿里云服务器复现上述问题，暂时不能提供解决方案，望理解。
