### ISSUE TITLE
[BUG] 创建php网站失败

### ISSUE THREAD

**Issue by muzidudu** [1Panel-dev/1Panel#3959]
### 1Panel 版本

v1.9.6

### 问题描述

创建php8.2.1网站 提示创建成功了,但是容器没有创建查看日志
`[2024-02-22 20:26:16] [INFO] download app[PHP 8] from https://apps-assets.fit2cloud.com/stable/1panel/php8/8.2.10/php8-8.2.10.tar.gz  
[2024-02-22 20:26:17] [ERROR] download app[PHP 8] error 文件不存在  
`

### 重现步骤

创建网站->运行环境->php8.2.10

**Comment by muzidudu** [comment]
从新创建运行环境 发现也没法选择php8.2.10了 提示不存在了

**Comment by muzidudu** [comment]
是不是每次创建网站都需要从https://apps-assets.fit2cloud.com 拉取镜像包

**Comment by wanghe-fit2cloud** [comment]
目前 PHP 8.2 最新版本为 8.2.15（官方已下架 8.2.10 版本）
你需要进入应用商店页面同步一下应用列表，之后再来创建 8.2.15 版本的运行环境，如下图所示：
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/8da355d0-11cf-40ce-aa32-8adefdab7e03">

**Comment by muzidudu** [comment]
> 目前 PHP 8.2 最新版本为 8.2.15（官方已下架 8.2.10 版本） 你需要进入应用商店页面同步一下应用列表，之后再来创建 8.2.15 版本的运行环境，如下图所示： <img alt="image" width="1475" src="https://private-user-images.githubusercontent.com/46734380/307028497-8da355d0-11cf-40ce-aa32-8adefdab7e03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MTI3MjEsIm5iZiI6MTcwODYxMjQyMSwicGF0aCI6Ii80NjczNDM4MC8zMDcwMjg0OTctOGRhMzU1ZDAtMTFjZi00MGNlLWFhMzItOGFkZWZkYWI3ZTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE0MzM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMTZhNjFhOGJkMTk2YTljNjVlMzAzZjc5MmY1NzUwYTUzNTM5MzVlNTNjNjQ3ZDgxZTY4ODE3OWUyYzc4OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Oh8rvbAfNvezt5Sak3wgF9KxZPozrIVq5FnhucsYSlE">

下架了,后续如果恢复快照找不到相同版本的镜像怎么处理了

**Comment by wanghe-fit2cloud** [comment]
> 下架了,后续如果恢复快照找不到相同版本的镜像怎么处理了

快照文件中包含运行环境网站以及docker镜像。

**Comment by muzidudu** [comment]
> > 下架了,后续如果恢复快照找不到相同版本的镜像怎么处理了
> 
> 快照文件中包含运行环境网站以及docker镜像。

👌好的 知道了
