### ISSUE TITLE
[BUG]Stirling-PDF 安装不上

### ISSUE THREAD

**Issue by exfanc** [1Panel-dev/1Panel#3960]
### 1Panel 版本

v1.9.6

### 问题描述

Stirling-PDF 首次尝试安装，全部默认，30分钟过去了还在安装中，以为是我的问题重启服务器，卸载干净文件重新安装，更换端口，又一个30分钟过去了... 点日志没有，点目录只有3个文件 .env data.yml docker-compose.yml，感觉是拉不下来东西。

### 重现步骤

直接安装就不行

**Comment by wanghe-fit2cloud** [comment]
你这是因为应用镜像下载超时导致的。
可以尝试进入 `容器` - `配置` 页面添加镜像加速地址，之后再来重新安装应用
也可以预先手动拉取应用镜像，比如：`docker pull frooodle/s-pdf:0.21.0`
