### ISSUE TITLE
[BUG] instalação via código fonte

### ISSUE THREAD

**Issue by HOOUVPN** [1Panel-dev/1Panel#3963]
### 联系方式

installation via source code 

### 1Panel 版本

installation via source code

### 问题描述

Could you leave the commands and a mini TUTORIAL to install 1panel from the source code! because I already tried with the make builde_all command, it always failed 

### 重现步骤

Could you leave the commands and a mini TUTORIAL to install 1panel from the source code! because I already tried with the make builde_all command, it always failed 

### 期待的正确结果

Could you leave the commands and a mini TUTORIAL to install 1panel from the source code! because I already tried with the make builde_all command, it always failed 

### 相关日志输出

```shell
Could you leave the commands and a mini TUTORIAL to install 1panel from the source code! because I already tried with the make builde_all command, it always failed
```

**Comment by wanghe-fit2cloud** [comment]
请查阅我们的官方文档中的开发手册，以了解如何在本地运行 1Panel：
https://1panel.cn/docs/dev_manual/dev_manual/

**Comment by HOOUVPN** [comment]
Bom achei confuso isso também funciona usando o  visual code ?
