### ISSUE TITLE
[QUESTION]Halo升级报错

### ISSUE THREAD

**Issue by GeekF0rum** [1Panel-dev/1Panel#3964]
### 请描述您的问题

2.12.2升级2.12.3，提示invalid project name "Halo": must consist only of lowercase alphanumeric characters, hyphens, and underscores as well as start with a letter or number，为什么针对这个大小写还有限制吗？

**Comment by wanghe-fit2cloud** [comment]
这是 `docker-compose` 抛出来的错误信息，是要求服务名称不能够包含大写字母。
刚刚在本地环境已验证，`docker-compose version` v2.16.0 版本是允许存在大写字母的。
> 你检查一下 1Panel 服务器上 `docker-compose` 版本，看是否是由于版本原因导致的。

**Comment by GeekF0rum** [comment]
服务器环境的Docker是根据1Panel的安装一起的，刚才看了下是Docker Compose version v2.22.0

**Comment by wanghe-fit2cloud** [comment]
> 服务器环境的Docker是根据1Panel的安装一起的，刚才看了下是Docker Compose version v2.22.0

进入 Halo 安装目录确认一下服务名称是不是大写的 `Halo`，再手动执行 `docker-compose up -d` 命令看一下结果

**Comment by wanghe-fit2cloud** [comment]
先关闭该 issue 了，如果依然存在上述问题，继续在该 issue 中讨论。
