### ISSUE TITLE
[BUG]CPU核心数较多时，CPU核心状态信息会超出页面范围

### ISSUE THREAD

**Issue by xiaoboishere** [1Panel-dev/1Panel#3966]
### 1Panel 版本

v1.9.6

### CPU核心数较多时，CPU核心状态信息会超出页面范围
![6d683e0a9fdd50d14314add610d4634](https://github.com/1Panel-dev/1Panel/assets/115374510/4bc7d83c-eb6e-4e6a-863d-a78cf5135804)

**Comment by igophper** [comment]
这核心数也太离谱了吧

**Comment by 9a6c** [comment]
真牛

**Comment by ghost** [comment]
大佬

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by xiaohange** [comment]
大佬啊！

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
