### ISSUE TITLE
[BUG]快照恢复错误问题

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#3968]
### 1Panel 版本

1.9.6

## 错误演示
![20240223-194559](https://github.com/1Panel-dev/1Panel/assets/63288007/778d25ee-6a17-49e6-86f3-4c0e1e2956db)

### 重现步骤

从使用的主机上执行快照备份策略，如下：
![screenshot-20240223-195944](https://github.com/1Panel-dev/1Panel/assets/63288007/4ab5e6d9-0d56-448f-bf05-83c83b431432)

在全新主机上同步该快照备份文件，执行恢复，出现错误！

且当尝试重启主机后，访问面板地址拒绝访问：
![screenshot-20240223-200840](https://github.com/1Panel-dev/1Panel/assets/63288007/93291a05-3d03-451c-98aa-a0f2134d4067)

### 期待的正确结果

希望排查解决该问题！
如果在不知情情况下执行备份却无法恢复，容易造成重大损失！

快照文件如下：
![screenshot-20240223-201059](https://github.com/1Panel-dev/1Panel/assets/63288007/b5f7a8f3-7b7c-48bc-9ddb-bd0531b7158d)

备注：
恢复快照面板与备份快照面板版本一致，且恢复快照面板为新安装面板，内容全部为空

**Comment by ssongliu** [comment]
感谢反馈，麻烦提供一下日志截图 /opt/1panel/log/1Panel.log 以及服务状态 1pctl status

**Comment by xiexiaosheng** [comment]
正确访问地址，应该是新IP:旧端口/旧安全入口

**Comment by JAINKRE** [comment]
> 感谢反馈，麻烦提供一下日志截图 /opt/1panel/log/1Panel.log 以及服务状态 1pctl status

恢复失败后主机重启面板直接无法打开了，楼上说的新ip+旧端口不成立，网络环境没有改变。

昨晚服务器被重装系统了，今晚我在复刻一下这个问题，到时候提供日志

**Comment by JAINKRE** [comment]
复现后该问题又出现，查看` /opt/1panel/log/1Panel.log`如下：
![20240224-142532](https://github.com/1Panel-dev/1Panel/assets/63288007/48884ba2-ecd6-4d2a-b80b-727ebbe136e0)

显示没空间导致。并且日志没有写完就被迫停止了

1panel默认安装在`/`根目录下，该目录本机默认只有50GB，而导入的快照备份文件（位于home路径且该路径独立空间）为26.2GB 结果拷贝解压全部转移到了`/`根目录，导致空间被占完出错。

尝试linux命令验证，同样报错无空间：
![screenshot-20240224-143109](https://github.com/1Panel-dev/1Panel/assets/63288007/88cc480c-3ac6-44e1-8f83-db86a6810153)

**Comment by ssongliu** [comment]
可以考虑扩容一下 /opt 安装目录，或者修改一下 1panel 安装目录。

**Comment by JAINKRE** [comment]
请问如何修改1panel安装目录目录呢？

**Comment by wanghe-fit2cloud** [comment]
> 请问如何修改1panel安装目录目录呢？

暂不支持修改安装目录。
