### ISSUE TITLE
[FEATURE] 增加对 Node.JS 的项目支持

### ISSUE THREAD

**Issue by HenryWu01** [1Panel-dev/1Panel#397]
### 1Panel 版本

1.0.3

### 请描述您的需求或者改进建议

在宝塔面板 (aaPanel) 中，添加网站时可以选择 Node 项目进行部署，并且可以指定 node 版本并一键安装和管理 package.json 的依赖，对于使用 Node.JS 的网站和后端服务十分友好。希望 1Panel 也支持添加 Node 网站。

### 请描述你建议的实现方案

aaPanel 添加 Node 项目网站
![firefox_eM0GpzxODZ](https://user-images.githubusercontent.com/99880210/227523142-9354d93e-e736-4a1e-a601-b7aae1e35057.png)

aaPanel 管理 Node 版本
![firefox_2xFKdtRxfN](https://user-images.githubusercontent.com/99880210/227523355-1cd077ed-c77e-4212-bf08-b2af6d613a9f.png)

aaPanel 全局依赖管理
![firefox_s0ElgKvVdu](https://user-images.githubusercontent.com/99880210/227523461-877ec697-ff8f-4daa-a2e4-7e721c1d6b86.png)

aaPanel 网站项目级别依赖管理
![DW3412iVTW](https://user-images.githubusercontent.com/99880210/227523600-dc50b7d8-6541-4aba-8931-5481dc955385.png)

aaPanel 项目负载状态
![firefox_3fPnL0z747](https://user-images.githubusercontent.com/99880210/227523736-10d5349b-48f4-4e00-9e0c-e3f9962ec73e.png)

### 附加信息

aaPanel 需要安装一个叫 Node.js version manager 的插件才能够实现此功能，希望 1Panel 也可以将他做成类似应用 (插件) 的形式？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本中我们会陆续支持多种开发语言建站。

**Comment by Jengro777** [comment]
node 环境比php 重要多了，php环境都3个了  nodejs的环境什么时候有啊！ 最好有 nodejs16.xx 的版本

**Comment by Dacong-wu** [comment]
确实需要Node环境，个人很多项目后端都是基于Node的

**Comment by zclzone** [comment]
万人血书，确实需求node环境

**Comment by Dacong-wu** [comment]
到现在也没有，说了下一个大版本会增加🤣，不知道等到啥时候呢

**Comment by zclzone** [comment]
> 万人血书，确实需求node环境

其实没有也行啦，装个pm2也很方便

**Comment by Lrunlin** [comment]
最好内置pm2管理器，可以对单个项目使用pm2管理，不需要单独的pm2JSON文件

**Comment by maninhill** [comment]
> 到现在也没有，说了下一个大版本会增加🤣，不知道等到啥时候呢

v1.17 （10月份发布）肯定支持，立下 flag 了。

**Comment by Dacong-wu** [comment]
期待一波，到时候就可以不用bt了，苦bt久已

**Comment by evanlong-me** [comment]
其实只需要一个 `Node` 项目管理，其他自己来也挺好的，自由一点，基本都是 `pm2` 一把梭

**Comment by Lrunlin** [comment]
> node 环境比php 重要多了，php环境都3个了 nodejs的环境什么时候有啊！ 最好有 nodejs16.xx 的版本

这样感觉可视化一个nvm插件好一点

**Comment by Dacong-wu** [comment]
还有2天，我看官方的测试版，已经支持了

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
