### ISSUE TITLE
[BUG]应用市场中Halo软件上传附件

### ISSUE THREAD

**Issue by cheng896911036** [1Panel-dev/1Panel#3970]
### 联系方式

896911036@163.com

### 1Panel 版本

1.9.6

### 问题描述

![2](https://github.com/1Panel-dev/1Panel/assets/23022025/c9723638-6f5f-423a-8c37-3de57e6edb1d)

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/23022025/143bf35c-db95-4ba9-84ab-2407a1ffb7c0)

**Comment by wanghe-fit2cloud** [comment]
需要将问题反馈给 [Halo 团队](https://github.com/halo-dev/halo/issues)

**Comment by cheng896911036** [comment]
已反馈halo



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年02月24日 21:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [1Panel-dev/1Panel] [BUG]应用市场中Halo软件上传附件 (Issue #3970) |

需要将问题反馈给 Halo 团队
