### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by sanqiy** [1Panel-dev/1Panel#3972]
### 1Panel 版本

1.9.6

### 请描述您的需求或者改进建议

Docker 干预 iptables 导致异常暴露端口的问题

### 请描述你建议的实现方案

方案一
安装 Docker 后, 务必编辑 /etc/docker/daemon.json(没有就新建一个), 设置 ip 为 127.0.0.1, 防止 docker 自己修改了 iptable 导致 ufw 失效. 修改完毕后执行 systemctl daemon-reload && systemctl restart docker 重启 Docker 服务.
注意, /etc/docker/daemon.json 应当是有效的 json. 下面是个参考(更多地: 开启了 IPv6 支持, 配置了 DNS. 国外服务器自行替换为 1.1.1.1, 8.8.8.8):

{
    "dns":[
        "119.29.29.29",
        "223.5.5.5"
    ],
    "ipv6":true,
    "fixed-cidr-v6":"fd00:db8:1::/64",
    "experimental":true,
    "ip6tables":true,
    "ip":"127.0.0.1"
}
注意: 亲测不能修改 /lib/systemd/system/docker.service 加上 --iptables=false, 否则 Docker 无法启动. 修改 /etc/docker/daemon.json 加上 { "iptables" : false } 本质一样.

或者参考这篇文章https://blog.liqiye.com/posts/919176895/

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1、我们目前支持进入 `容器` - `配置` 页面，可视化管理 docker iptables，如图：
<img width="1115" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/785575c4-b37b-4cb4-857e-7cf02a888058">
2、创建运行环境网站、安装应用时，默认端口绑定时 127.0.0.1，也支持按需选择对外暴露端口
3、后续版本我们也计划通过支持 ufw-docker 等服务来支持防火墙管理容器端口
