### ISSUE TITLE
[QUESTION]增加管理app和移动手机页面美化

### ISSUE THREAD

**Issue by sanqiy** [1Panel-dev/1Panel#3973]
### 请描述您的问题

1.宝塔推出了自己app方便快捷查看自己的服务器
希望1panel也可以推出
2.1panel在移动手机页面操作面板编辑网站代码十分不方便，希望可以针对手机端进行页面优化

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1、我们暂无推出手机 app 的计划，望理解。
2、关于移动端页面适配的问题，可以再展开描述一下具体问题，我们后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
我们会在后续版本中持续优化移动端适配。
先关闭此 issue，如果发现具体页面有问题，请继续反馈。
