### ISSUE TITLE
[FEATURE] 备份时可以选择备份到的文件夹

### ISSUE THREAD

**Issue by DongShaoNB** [1Panel-dev/1Panel#3975]
### 1Panel 版本

1.9.6

### 请描述您的需求或者改进建议

备份时可以选择备份到的文件夹，服务器挂载了nfs，可以选择备份到里面

**Comment by wanghe-fit2cloud** [comment]
1、进入 `面板设置` - `备份账号` 页面，编辑 `服务器磁盘` - `当前路径`（修改为 nfs 挂载路径）
2、创建计划任务选择备份账号时，选择 `服务器磁盘` 即可
