### ISSUE TITLE
[FEATURE] 优化网站主域名和其他设置里的主域名的提示

### ISSUE THREAD

**Issue by static7** [1Panel-dev/1Panel#3976]
### 1Panel 版本

v1.9.6

### 请描述您的需求或者改进建议

网站主域名删除后
![image](https://github.com/1Panel-dev/1Panel/assets/11241063/5653f7d8-5f1a-4ef1-a4e0-24ba94ecd8e2)
再其他选项里
![image](https://github.com/1Panel-dev/1Panel/assets/11241063/a50651c7-576f-4474-b932-a3f848a52e55)
主域名还存在

### 请描述你建议的实现方案

主域名列表里增加主域名的提示,设置为不可删除状态
再其他选项里, 增加拉下选择主域名的列表. 
也就是说, 必定有一个域名是不可删除的.

**Comment by zhengkunwang223** [comment]
主域名可以看做网站名称 创建完网站之后 不会影响生效网站域名
在域名列表里面 域名都是可以删除的 仅剩一个的情况下不能删除 因为会影响 nginx 配置文件
