### ISSUE TITLE
[BUG]PHP7.3可以连接SQL2008,而PHP8.2不能连接SQL2008

### ISSUE THREAD

**Issue by chmis8000** [1Panel-dev/1Panel#3977]
### 联系方式

444831568@qq.com

### 1Panel 版本

1.9.6

### 问题描述

PHP7.3可以连接SQL2008,而PHP8.2不能连接SQL2008
而宝塔的PHP8.2、PHP8.3启用SQL Server扩展,并且使用下面连接代码 是可以连接SQL2008的。

### 重现步骤

$connectionInfo = array(
        "UID" => "sa",
        "PWD" => "xxxxxx",
        "Database" => 'zzz02',
        "APP" => 'WEI', "LoginTimeout" => 5,
        "Encrypt"=>"0",
        "TrustServerCertificate"=>1
); //PHP8.2用ODBC Driver 18.0，默认加密是开的，需要关闭，否则报错 SSL routines::certificate verify failed
$msdb = sqlsrv_connect("192.168.0.10,1433", $connectionInfo);
if (!$msdb) {
        echo "connect sqlserver error <br />";
        die(print_r(sqlsrv_errors(), true));
}else{
   echo 'OK';
}

### 期待的正确结果

能够连接SQLServer2008

### 附加信息

在centos下，/etc/crypto-policies/back-ends/opensslcnf.config 
要检查配置项是否是： MinProtocol=TLSv1
如果不是，PHP8.2仍旧无法连接SQL2008

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
> 在centos下，/etc/crypto-policies/back-ends/opensslcnf.config
> 要检查配置项是否是： MinProtocol=TLSv1
> 如果不是，PHP8.2仍旧无法连接SQL2008

刚在本地环境测试安装 `sqlsrv ` 和 `pdo_sqlsrv ` 扩展成功，没有发现问题。
由于 1Panel 是 docker 容器化部署的 PHP 网站，如需上述配置还需要进入 `容器` - `终端` 内执行。

**Comment by chmis8000** [comment]
@wangdan-fit2cloud  你只提了安装扩展成功，我没说扩展安装不成功，你确认测试能连上sql2008？

**Comment by wanghe-fit2cloud** [comment]
> 你只提了安装扩展成功，我没说扩展安装不成功，你确认测试能连上sql2008？

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/592f2adf-65ca-4fac-8a32-6eeebc2b531f)
