### ISSUE TITLE
[FEATURE] 【网站-基本-密码访问】添加路径配置，允许跳过后台自带验证的路径

### ISSUE THREAD

**Issue by QYG2297248353** [1Panel-dev/1Panel#3979]
### 1Panel 版本

v1.9.6

### 请描述您的需求或者改进建议

当网站部署在二级目录时，又不想给主站点配置密码访问，配置就存在巨大问题。
例如：
baidu.com/                  为网站主目录 允许访问
baidu.com/admin        为网站的后台或者其他目录 需要添加密码验证
baidu.com/api        为网站的后端服务，有自己的验证方法，不需要验证
如果使用二级域名解决，修改的配置太多，我希望官方能支持，不同路径的验证

![Snipaste_2024-02-26_10-11-55](https://github.com/1Panel-dev/1Panel/assets/56836951/ee177a3e-f8b2-4e2d-8fce-21f391eafe2d)

### 请描述你建议的实现方案

新增路径与验证方式选项

路径：
允许使用通配符或正则，扩大路径范围

验证方式：
密码验证
允许访问(配合主站点开启密码访问，允许白名单路径)
禁止访问(完全堵死)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先调研一下具体实现方案，后续版本考虑支持。
