### ISSUE TITLE
[BUG]内网穿透或端口映射https会提示此网站无法提供安全连接（ERR_SSL_PROTOCOL_ERROR）

### ISSUE THREAD

**Issue by 52lemon6** [1Panel-dev/1Panel#398]
### 联系方式

微信私我免费看环境

### 1Panel 版本

1.0.3

### 问题描述

内网穿透或端口映射https会提示此网站无法提供安全连接（ERR_SSL_PROTOCOL_ERROR）,穿透环境，Socat/frp，使用Socat同等环境下群晖的https就可正常访问，域名和端口啥的也不好直接放出来了，可以微信私我

### 重现步骤

Socat使用openwrt ipv4端口映射到ipv6，使用同等方法映射的群晖https可以正常访问

**Comment by TcDhlPro** [comment]
用zt做穿透, 一点问题都没有

**Comment by YaKun9** [comment]
这个问题是否还没有解决?

**Comment by QIAOYANGvg** [comment]
这么久了 这个bug还不修复吗

![Image](https://github.com/user-attachments/assets/a363062d-321c-4d7d-bba6-290ed3a85128)

**Comment by FrancisChuh** [comment]
这个问题解决了么？
