### ISSUE TITLE
[FEATURE]添加mongodb数据库支持

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#3988]
### 1Panel 版本

1.9.6

### 请描述您的需求或者改进建议

数据库页面支持mongodb
web管理工具：https://github.com/mongo-express/mongo-express

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述应用。

**Comment by wanghe-fit2cloud** [comment]
已支持。
