### ISSUE TITLE
[FEATURE] 应用商店 增加 verdaccio 应用

### ISSUE THREAD

**Issue by van-chin** [1Panel-dev/1Panel#3994]
### 1Panel 版本

1.9.6

### 请描述您的需求或者改进建议

根据 https://github.com/verdaccio/verdaccio 
将 verdaccio 增加进 应用商店中

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上架 Verdaccio。

**Comment by wanghe-fit2cloud** [comment]
应用已上架。
进入应用商店列表，点击右上角的【更新应用列表】按钮，待同步完成后即可安装应用。
