### ISSUE TITLE
[BUG]重复访问容器内部时，终端内容可显示宽度异常

### ISSUE THREAD

**Issue by QuentinHsu** [1Panel-dev/1Panel#3995]
### 1Panel 版本

v1.9.6

### 问题描述

重复访问容器内部时，终端内容可显示宽度异常。
1. 先选择 `/bin/bash`，连接终端，终端内容显示宽度正常（能撑满可用宽度）
2. 依旧选择 `/bin/bash`，断开终端，再连接当前终端类型，终端内容显示宽度异常（未能撑满可用宽度）

https://github.com/1Panel-dev/1Panel/assets/21162238/984e9e21-ec6c-453b-8bcf-5d08fd1f16cf

### 重现步骤

如上

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
v1.10.0-lts 版本已发布。
