### ISSUE TITLE
[BUG]上传文件夹会丢失部分文件

### ISSUE THREAD

**Issue by liusuchao** [1Panel-dev/1Panel#3997]
### 联系方式

yjvijfhvk@gmail.ccom

### 1Panel 版本

v1.9.6

### 问题描述

首先感觉感谢有1Panel的软件。这里我发现了一个问题。
我在创建静态网站时，需要上传文件夹，文件夹中有351个文件。上传的使用会丢失部分文件。 

### 重现步骤

1.解压文件
2.部署静态网站
3.使用文件夹的方式上传到index目录下。（注意只上传index.html 和 assets）
4.检测assets上传文件是否有351个
[dist.tar.gz](https://github.com/1Panel-dev/1Panel/files/14415470/dist.tar.gz)

### 相关日志输出

```shell
地
```

### 附加信息

![Pasted image 20240226141523](https://github.com/1Panel-dev/1Panel/assets/15273205/12dd18b9-da5a-4141-934e-231fd062f3cf)
![Pasted image 20240226151414](https://github.com/1Panel-dev/1Panel/assets/15273205/2b289557-00b7-4893-b82b-0baeb0230022)

**Comment by zhengkunwang223** [comment]
您好 经过我们测试 没有复现该问题
当前是拖拽上传会丢失部分文件 这个我们在下个版本修复
你可以等到我们 1.10 版本发布之后测试一下

**Comment by wanghe-fit2cloud** [comment]
v1.10.0-lts 版本已发布。

**Comment by liusuchao** [comment]
已完成。
