### ISSUE TITLE
[BUG]终端链接里边主机链接信息无法主动保存错误

### ISSUE THREAD

**Issue by AKAOOK** [1Panel-dev/1Panel#3998]
### 联系方式

奥德修斯

### 1Panel 版本

v1.9.6

### 问题描述

1.本地链接地址无法删除
2.主机链接信息需要通过链接测试后才能确认保存

### 重现步骤

保存主机链接信息时出现

### 期待的正确结果

填写部分主机链接信息可以通过‘确定’按钮正常保存

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1、系统需要使用本地链接地址来访问终端，不支持删除操作。
2、需要确保服务器可正常访问的前提下才支持添加服务器。
