### ISSUE TITLE
[FEATURE] 建议在备份等操作之后，删除过程中产生的临时文件

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#3999]
### 1Panel 版本

v1.10.0.lts

### 请描述您的需求或者改进建议

建议在备份等操作之后，删除过程中产生的临时文件

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
可以更新 1Panel 至最新版本。
