### ISSUE TITLE
[FEATURE] 创建容器-端口支持更多形式

### ISSUE THREAD

**Issue by Mystery00** [1Panel-dev/1Panel#400]
### 1Panel 版本

1.0.3

### 请描述您的需求或者改进建议

- [ ] 创建容器 - 端口 - 暴露端口 支持设置多个端口、ip:port等多种形式
- [ ] #401
- [ ] 创建容器 - 端口 不在镜像expose列表的端口似乎不能暴露出来，例如：镜像仅暴露了443，但是内部有80端口，通过设置81:80出来之后，本机的81端口并没有监听

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本中我们会持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
