### ISSUE TITLE
[FEATURE]优化下页面样式

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4000]
### 1Panel 版本

v1.10.0-lts

### 请描述您的需求或者改进建议

1. 刷新页面时候右下角的 版本号 会出现 undefined ,加个默认值 null 吧.
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/0e0005c7-c5e6-443a-bb7a-323a6b4ee0b7)

2. 网站 菜单 加载时 会先出现未检测的情况,提前做个判断进入 loading ,避免这种情况出现吧(已经安装 OpenResty).
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/d8f29f60-3ef3-4f4d-9d69-266dfac35924)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
1、已完成。
2、后续版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.1-lts 版本已发布。
