### ISSUE TITLE
[BUG] Umami 对应 Docker 参数与官方不一致

### ISSUE THREAD

**Issue by mobeicanyue** [1Panel-dev/1Panel#4002]
### 1Panel 版本

1.10

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/81098819/9c463090-df69-4175-91c5-db88aafcb210)

![image](https://github.com/1Panel-dev/1Panel/assets/81098819/da68d808-5620-4d84-8594-23ec138994cd)

且并没有在appstore仓库看到有对应的变量名转化

### 重现步骤

查看仓库

**Comment by mobeicanyue** [comment]
https://github.com/1Panel-dev/appstore/blob/6ceb5520c3272ec1c56dc82b4f306d42bd6186cf/apps/umami/2.9.0/docker-compose.yml

https://github.com/umami-software/umami/blob/master/docker-compose.yml#L11

**Comment by wanghe-fit2cloud** [comment]
> https://github.com/1Panel-dev/appstore/blob/6ceb5520c3272ec1c56dc82b4f306d42bd6186cf/apps/umami/2.9.0/docker-compose.yml
> 
> https://github.com/umami-software/umami/blob/master/docker-compose.yml#L11

欢迎给我们的 [appstore](https://github.com/1Panel-dev/appstore) 项目提交 Pull requests，测试通过后我们也会推送到正式仓库中。

**Comment by wanghe-fit2cloud** [comment]
已推送更新。
