### ISSUE TITLE
[QUESTION] 如何获取1Panel安装位置

### ISSUE THREAD

**Issue by QYG2297248353** [1Panel-dev/1Panel#4006]
### 请描述您的问题

我想将应用商店的配置放入本地应用指定位置，但是部分用户修改了安装位置，无法准确的定位到指定位置，官方提供的指令 `1panel` 与 `1pctl` 均没有获取安装位置的指令，现在只能依靠特点目录路径查询 `1Panel/resource` 很不友好。

希望官方增加：
- [ ] 安装路径的查询指令

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述命令。

也欢迎关注我们的 [脚本项目](https://github.com/1Panel-dev/installer)，随时给我们提交 pr 和 issue。

**Comment by zhangyz189** [comment]
结合linux命令看看
`
which 1pctl|xargs grep '^BASE_DIR='| cut -d'=' -f2
`

**Comment by QYG2297248353** [comment]
> 结合linux命令看看 `which 1pctl|xargs grep '^BASE_DIR='| cut -d'=' -f2`

是的，很好的解决我的问题，非常感谢
