### ISSUE TITLE
[FEATURE] 应用商店添加zerotier内网穿透软件

### ISSUE THREAD

**Issue by glxaa** [1Panel-dev/1Panel#4007]
### 1Panel 版本

v1.10.0-lts

### 请描述您的需求或者改进建议

应用商店添加zerotier的自建根服务器内网穿透软件
zerotier相较于frp，个人觉得更好用而且稳定，是基于p2p技术实现的，当p2p走不通才会走转发，通常来说，只要一方的nat类型不是特别严格的，就可以p2p打洞成功跑满带宽，而不是走服务器的低带宽。

### 请描述你建议的实现方案

建议使用xubiaolint大佬的镜像，可以自定义端口，自带管理界面，项目地址： [xubiaolin/docker-zerotier-planet](https://github.com/xubiaolin/docker-zerotier-planet)

**Comment by wanghe-fit2cloud** [comment]
以下项目是否能满足需求呢
https://github.com/Jonnyan404/zerotier-planet
> 官方已经提供了 `docker-compose.yml` 文件

**Comment by lobmoo** [comment]
我建议加入nps 更现代化更好用 
https://github.com/ehang-io/nps

**Comment by wanghe-fit2cloud** [comment]
> 我建议加入nps 更现代化更好用 https://github.com/ehang-io/nps

该项目已经不再维护、存在安全漏洞，已经在 1Panel 应用商店下架。
