### ISSUE TITLE
[QUESTION]请教一个问题，关于反代的二级域名匹配跳转问题

### ISSUE THREAD

**Issue by gasment** [1Panel-dev/1Panel#4012]
### 请描述您的问题

使用相同顶级域名和相同非标端口，以二级域名区分反代多个网站，当访问未绑定的二级域名时，会跳转到最后添加的反代站点后端上。
比如：
新建的站点(https)：111.test.com:6666，222.test.com:6666，333.test.com:6666
                      以上使用相同的泛域名证书，手动修改的配置 listen 6666 ssl http2 ; 
访问已绑定反代域名时一切正常，访问未绑定域名如444.test.com:6666时，会跳转到333.test.com:6666的后端（已绑定其他静态页为默认站点），使用过隔壁BT也是一样的问题，是否需要特别配置？

**Comment by zhengkunwang223** [comment]
访问未绑定域名 是什么操作？
怎么定义的未绑定域名

**Comment by gasment** [comment]
> 访问未绑定域名 是什么操作？ 怎么定义的未绑定域名

未在1panel中创建的二级域名网点。DNS解析是泛域名，*.test.com:6666都会进到1panel所在服务器，访问已经创建的反代站点如111.test.com:6666会正常转发到对应后端，但是访问未创建的站点（打错二级域名什么的）如444.test.com:6666，则会跳到其中一个已创建的反代站点（本意是希望返回不存在或响应超时之类的）

**Comment by zhengkunwang223** [comment]
> > 访问未绑定域名 是什么操作？ 怎么定义的未绑定域名
> 
> 未在1panel中创建的二级域名网点。DNS解析是泛域名，*.test.com:6666都会进到1panel所在服务器，访问已经创建的反代站点如111.test.com:6666会正常转发到对应后端，但是访问未创建的站点（打错二级域名什么的）如444.test.com:6666，则会跳到其中一个已创建的反代站点（本意是希望返回不存在或响应超时之类的）

这个可能需要你自己修改配置文件实现
