### ISSUE TITLE
[BUG]更新到最新lts版本后无法登录进页面

### ISSUE THREAD

**Issue by godcong** [1Panel-dev/1Panel#4013]
### 1Panel 版本

v1.10.0-lts

### 问题描述

无法进入面板页面

### 重现步骤

1. 在登录页面登录后,跳转到面板页面.
2. 面板页面出现一瞬,然后又退回到了登录页面.

### 期待的正确结果

可以进登录页面

**Comment by wanghe-fit2cloud** [comment]
浏览器访问系统时，是通过 `IP+端口` 还是 `创建的反向代理网站`

ssh 进入服务器，再查看一下系统日志，文件路径为：`/opt/1panel/log/1Panel.log`

**Comment by godcong** [comment]
配置了域名,并通过反向代理访问的.且开启了https.
一台机器老版本好的,更新到新版本就不行了.
还有一台机器全新安装的.配置好以后域名和ip都访问不了了...

看了下 `/opt/1panel/log/1Panel.log`,登录多次,但是后台没有输出任何日志...

**Comment by wanghe-fit2cloud** [comment]
> 配置了域名,并通过反向代理访问的.且开启了https.

浏览器通过 `IP+端口` 方式访问，是否正常？

**Comment by godcong** [comment]
> > 配置了域名,并通过反向代理访问的.且开启了https.
> 
> 浏览器通过 `IP+端口` 方式访问，是否正常？

一台从老版本更新的机器`IP+端口` 正常.
另一台全新安装的和域名访问的问题一样,一登录就又跳回到登录页面.

![image](https://github.com/1Panel-dev/1Panel/assets/2727298/ca947f5c-3b4f-4aee-a642-03341577afff)

我通过`IP+端口`修改了上面的选项,我发现如果选择`HTTP自动跳转HTTPS`,然后通过域名访问会显示`重定向次数过多`
而选择HTTP就可以通过域名正常打开面板,但打开的网页也会自动跳转到HTTPS
不知道和这个有没有关系

**Comment by zhengkunwang223** [comment]
> 我通过`IP+端口`修改了上面的选项,我发现如果选择`HTTP自动跳转HTTPS`,然后通过域名访问会显示`重定向次数过多` 而选择HTTP就可以通过域名正常打开面板,但打开的网页也会自动跳转到HTTPS 不知道和这个有没有关系

清除浏览器缓存试一下

**Comment by wanghe-fit2cloud** [comment]
先关闭该 issue 了，如后续仍有问题再继续讨论。
