### ISSUE TITLE
[BUG] 搜索框重复请求问题

### ISSUE THREAD

**Issue by igophper** [1Panel-dev/1Panel#4017]
### 1Panel 版本

1.10.0

### 问题描述

项目中很多地方使用了下面这部分代码，可以搜索`search-button`进行查看。
当在输入框输入完数据时，按下`enter`键，keyup.enter事件和change事件 都会被触发，导致了两次请求。
关于`chang`事件，[element-plus](https://element-plus.org/zh-CN/component/input.html#events)官网 介绍：`
change 事件，仅当 modelValue 改变时，当输入框失去焦点或用户按Enter时触发`

也许这里的`chang`事件最开始是想要使用`input`事件

```vue
<div class="search-button">
    <el-input
        clearable
        v-model="searchName"
        @clear="search()"
        suffix-icon="Search"
        @keyup.enter="search()"
        @change="search()"
        :placeholder="$t('commons.button.search')"
    ></el-input>
</div>
```

关于修复：
我尝试修复这个问题，写完代码感觉写的不是很好，所以没提PR。希望和`TableSetting`组件一样，封装成`<TableSearch v-model="searchName" @search="search()" />`这种。

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/34326532/288beda4-5a80-4a34-b5c5-55c9de0425db)

在`列表设置`旁的搜索框进行输入，按下enter按键后，可以观察到网络选项卡中的网络请求。

### 期待的正确结果

不再进行两次重复请求，封装成组件。

**Comment by ssongliu** [comment]
感谢反馈，后续版本优化该组件

**Comment by wanghe-fit2cloud** [comment]
v1.10.1-lts 版本已发布。
