### ISSUE TITLE
[BUG]幻兽帕鲁服务端构建的端口8211 无法检测出来

### ISSUE THREAD

**Issue by git-Ander** [1Panel-dev/1Panel#4018]
### 联系方式

947453372@qq.com

### 1Panel 版本

v1.10.0-lts

### 问题描述

幻兽帕鲁服务端构建的端口8211 无法检测出来

### 重现步骤

端口 | 8211
RCON 端口 | 25575
Query 端口 (用于与 Steam 服务器通信的查询端口) | 27015
玩家数量限制 | 32
是否启用 CPU 多线程优化 (true / false) | true
是否将服务器设置为社区服务器 (true / false) | false
服务器 IP (留空自动检测) |  
服务器端口 (留空自动检测) |  
是否每次启动都更新服务器 (true / false) | true
服务器名 | Default Palworld Server
管理员密码 | 123456
服务器密码 | 123456
是否启用 RCON (true / false) | false

### 期待的正确结果

正常8211端口服务

**Comment by git-Ander** [comment]
1Panel-palworld-Yrfu  | [1;36m****EXECUTING USERMOD****[0m
1Panel-palworld-Yrfu  | usermod: no changes
1Panel-palworld-Yrfu  | [1;36m****Checking for new update****[0m
1Panel-palworld-Yrfu  | [0;37mCurrent Version: 3750364703337203431[0m
1Panel-palworld-Yrfu  | [1;32mThe Server is up to date![0m
1Panel-palworld-Yrfu  | [1;36m****GENERATING CONFIG****[0m
1Panel-palworld-Yrfu  | [0;37mUsing Env vars to create PalWorldSettings.ini[0m
1Panel-palworld-Yrfu  | [1;36m****Compiling PalWorldSettings.ini****[0m
1Panel-palworld-Yrfu  | [1;32mCompiling PalWorldSettings.ini done![0m
1Panel-palworld-Yrfu  | [1;36m****GENERATING CRONTAB****[0m
1Panel-palworld-Yrfu  | [0;37mBACKUP_ENABLED=true[0m
1Panel-palworld-Yrfu  | [0;37mAdding cronjob for auto backups[0m
1Panel-palworld-Yrfu  | [0;37mCronjobs started[0m
1Panel-palworld-Yrfu  | [1;36m****Starting Server****[0m
1Panel-palworld-Yrfu  | ./PalServer-arm64.sh -port=8211 -queryport=27015 -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
1Panel-palworld-Yrfu  | time="2024-02-28T15:52:52Z" level=info msg="read crontab: /home/steam/server/crontab"
1Panel-palworld-Yrfu  | [S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
1Panel-palworld-Yrfu  | Shutdown handler: initalize.
1Panel-palworld-Yrfu  | Increasing per-process limit of core file size to infinity.
1Panel-palworld-Yrfu  | - Existing per-process limit (soft=18446744073709551615, hard=18446744073709551615) is enough for us (need only 18446744073709551615)
1Panel-palworld-Yrfu  | CAppInfoCacheReadFromDiskThread took 7 milliseconds to initialize
1Panel-palworld-Yrfu  | Setting breakpad minidump AppID = 2394010
1Panel-palworld-Yrfu  | [S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
1Panel-palworld-Yrfu  | [S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
1Panel-palworld-Yrfu  | [S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
1Panel-palworld-Yrfu  | [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
1Panel-palworld-Yrfu  | Killed
1Panel-palworld-Yrfu  | [1;36m****EXECUTING USERMOD****[0m
1Panel-palworld-Yrfu  | usermod: no changes
1Panel-palworld-Yrfu  | [1;36m****Checking for new update****[0m
1Panel-palworld-Yrfu  | [0;37mCurrent Version: 3750364703337203431[0m
1Panel-palworld-Yrfu  | [1;32mThe Server is up to date![0m
1Panel-palworld-Yrfu  | [1;36m****GENERATING CONFIG****[0m
1Panel-palworld-Yrfu  | [0;37mUsing Env vars to create PalWorldSettings.ini[0m
1Panel-palworld-Yrfu  | [1;36m****Compiling PalWorldSettings.ini****[0m
1Panel-palworld-Yrfu  | [1;32mCompiling PalWorldSettings.ini done![0m
1Panel-palworld-Yrfu  | [1;36m****GENERATING CRONTAB****[0m
1Panel-palworld-Yrfu  | [0;37mBACKUP_ENABLED=true[0m
1Panel-palworld-Yrfu  | [0;37mAdding cronjob for auto backups[0m
1Panel-palworld-Yrfu  | [0;37mCronjobs started[0m
1Panel-palworld-Yrfu  | [1;36m****Starting Server****[0m
1Panel-palworld-Yrfu  | ./PalServer-arm64.sh -port=8211 -queryport=27015 -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
1Panel-palworld-Yrfu  | time="2024-02-28T15:54:18Z" level=info msg="read crontab: /home/steam/server/crontab"
1Panel-palworld-Yrfu  | [S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
1Panel-palworld-Yrfu  | Shutdown handler: initalize.
1Panel-palworld-Yrfu  | Increasing per-process limit of core file size to infinity.
1Panel-palworld-Yrfu  | - Existing per-process limit (soft=18446744073709551615, hard=18446744073709551615) is enough for us (need only 18446744073709551615)
1Panel-palworld-Yrfu  | CAppInfoCacheReadFromDiskThread took 3 milliseconds to initialize
1Panel-palworld-Yrfu  | Setting breakpad minidump AppID = 2394010
1Panel-palworld-Yrfu  | [S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
1Panel-palworld-Yrfu  | [S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
1Panel-palworld-Yrfu  | [S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
1Panel-palworld-Yrfu  | [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
1Panel-palworld-Yrfu  | Killed
1Panel-palworld-Yrfu  | [1;36m****EXECUTING USERMOD****[0m
1Panel-palworld-Yrfu  | usermod: no changes
1Panel-palworld-Yrfu  | [1;36m****Checking for new update****[0m
1Panel-palworld-Yrfu  | [0;37mCurrent Version: 3750364703337203431[0m
1Panel-palworld-Yrfu  | [1;32mThe Server is up to date![0m
1Panel-palworld-Yrfu  | [1;36m****GENERATING CONFIG****[0m
1Panel-palworld-Yrfu  | [0;37mUsing Env vars to create PalWorldSettings.ini[0m
1Panel-palworld-Yrfu  | [1;36m****Compiling PalWorldSettings.ini****[0m
1Panel-palworld-Yrfu  | [1;32mCompiling PalWorldSettings.ini done![0m
1Panel-palworld-Yrfu  | [1;36m****GENERATING CRONTAB****[0m
1Panel-palworld-Yrfu  | [0;37mBACKUP_ENABLED=true[0m
1Panel-palworld-Yrfu  | [0;37mAdding cronjob for auto backups[0m
1Panel-palworld-Yrfu  | [0;37mCronjobs started[0m
1Panel-palworld-Yrfu  | [1;36m****Starting Server****[0m
1Panel-palworld-Yrfu  | ./PalServer-arm64.sh -port=8211 -queryport=27015 -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
1Panel-palworld-Yrfu  | time="2024-02-28T15:55:47Z" level=info msg="read crontab: /home/steam/server/crontab"
1Panel-palworld-Yrfu  | [S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
1Panel-palworld-Yrfu  | Shutdown handler: initalize.
1Panel-palworld-Yrfu  | Increasing per-process limit of core file size to infinity.
1Panel-palworld-Yrfu  | - Existing per-process limit (soft=18446744073709551615, hard=18446744073709551615) is enough for us (need only 18446744073709551615)
1Panel-palworld-Yrfu  | CAppInfoCacheReadFromDiskThread took 9 milliseconds to initialize
1Panel-palworld-Yrfu  | Setting breakpad minidump AppID = 2394010
1Panel-palworld-Yrfu  | [S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
1Panel-palworld-Yrfu  | [S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
1Panel-palworld-Yrfu  | [S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
1Panel-palworld-Yrfu  | [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
1Panel-palworld-Yrfu  | Killed
1Panel-palworld-Yrfu  | [1;36m****EXECUTING USERMOD****[0m
1Panel-palworld-Yrfu  | usermod: no changes
1Panel-palworld-Yrfu  | [1;36m****Checking for new update****[0m
1Panel-palworld-Yrfu  | [0;37mCurrent Version: 3750364703337203431[0m
1Panel-palworld-Yrfu  | [1;32mThe Server is up to date![0m
1Panel-palworld-Yrfu  | [1;36m****GENERATING CONFIG****[0m
1Panel-palworld-Yrfu  | [0;37mUsing Env vars to create PalWorldSettings.ini[0m
1Panel-palworld-Yrfu  | [1;36m****Compiling PalWorldSettings.ini****[0m
1Panel-palworld-Yrfu  | [1;32mCompiling PalWorldSettings.ini done![0m
1Panel-palworld-Yrfu  | [1;36m****GENERATING CRONTAB****[0m
1Panel-palworld-Yrfu  | [0;37mBACKUP_ENABLED=true[0m
1Panel-palworld-Yrfu  | [0;37mAdding cronjob for auto backups[0m
1Panel-palworld-Yrfu  | [0;37mCronjobs started[0m
1Panel-palworld-Yrfu  | [1;36m****Starting Server****[0m
1Panel-palworld-Yrfu  | ./PalServer-arm64.sh -port=8211 -queryport=27015 -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
1Panel-palworld-Yrfu  | time="2024-02-28T15:57:17Z" level=info msg="read crontab: /home/steam/server/crontab"
1Panel-palworld-Yrfu  | [S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
1Panel-palworld-Yrfu  | Shutdown handler: initalize.
1Panel-palworld-Yrfu  | Increasing per-process limit of core file size to infinity.
1Panel-palworld-Yrfu  | - Existing per-process limit (soft=18446744073709551615, hard=18446744073709551615) is enough for us (need only 18446744073709551615)
1Panel-palworld-Yrfu  | CAppInfoCacheReadFromDiskThread took 10 milliseconds to initialize
1Panel-palworld-Yrfu  | Setting breakpad minidump AppID = 2394010
1Panel-palworld-Yrfu  | [S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
1Panel-palworld-Yrfu  | [S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
1Panel-palworld-Yrfu  | [S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
1Panel-palworld-Yrfu  | [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
1Panel-palworld-Yrfu  | Killed
1Panel-palworld-Yrfu  | [1;36m****EXECUTING USERMOD****[0m

**Comment by git-Ander** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/12371291/e6719250-1ca7-44d7-bd0e-5a2d4e456165)

**Comment by wanghe-fit2cloud** [comment]
应用的 8211 是  udp 端口，telnet 只支持测试 tcp 端口（可以考虑使用 nc 等命令）。

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/5c30e690-f49d-4556-ad37-643793a3d9a4)
