### ISSUE TITLE
[FEATURE]希望网卡监控可以默认eth0或者记住上次选择的网卡

### ISSUE THREAD

**Issue by 52lemon6** [1Panel-dev/1Panel#4019]
### 1Panel 版本

v1.10.0-lts

### 请描述您的需求或者改进建议

希望首页的监控流量中的网卡和主机-监控-网络 IO中这些流量统计的功能，可以默认eth0（物理网卡）或者记住上次选择的网卡，这样可以直观的看到物理网卡的速率而不是docker和lo之类的内部流量

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
进入 `面板设置` 页面，支持设置默认网卡，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/461e49ed-8e32-4417-b6b6-314559ea8616)
