### ISSUE TITLE
[FEATURE]增加统一调整主机监控时间的功能

### ISSUE THREAD

**Issue by QAQ5555** [1Panel-dev/1Panel#402]
### 1Panel 版本

1.0.2

### 请描述您的需求或者改进建议

主机监控的时间增加统一调整功能

### 请描述你建议的实现方案

主机监控最上方增加统一调整时间的选项，避免调整时间时要一个一个调

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
