### ISSUE TITLE
[FEATURE]希望主机->监控可以记录docker的负载

### ISSUE THREAD

**Issue by 52lemon6** [1Panel-dev/1Panel#4021]
### 1Panel 版本

v1.10.0-lts

### 请描述您的需求或者改进建议

希望主机->监控可以记录docker的历史负载

**Comment by wanghe-fit2cloud** [comment]
目前 `容器` 列表页面支持查看容器的实时资源使用率。
至于要支持查看容器历史负载这个需求，我们暂时先不考虑支持，望理解。
