### ISSUE TITLE
[BUG] 容器资源使用率获取错误

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4022]
### 1Panel 版本

v1.10.0.lts

### 问题描述

![图片](https://github.com/1Panel-dev/1Panel/assets/30285739/fbe74c58-e106-4d10-8811-e216d64ccb81)

### 重现步骤

暂时不知道怎么复现，只有这个容器有问题，重启后会恢复，但是过一两天又出现这个情况。

**Comment by ssongliu** [comment]
感谢反馈，下个小版本解决该问题

**Comment by wanghe-fit2cloud** [comment]
v1.10.1-lts 版本已发布。
