### ISSUE TITLE
快照恢复后docker-compose文件不会加载到列表[BUG]

### ISSUE THREAD

**Issue by zxwmfcm** [1Panel-dev/1Panel#4027]
### 1Panel 版本

v1.10.0-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/30642864/4db54e57-40de-4573-8a45-94c052a2ff14)

![image](https://github.com/1Panel-dev/1Panel/assets/30642864/f8159c93-f372-4340-bb56-2d2fe37bc4ce)

我从A机器备份快照到B机器恢复 容器->编排列表不会加载 /opt/1panel/docker/compose下配置文件  还需要手动添加才能出现

### 重现步骤

我从A机器备份快照到B机器恢复 容器->编排列表不会加载 /opt/1panel/docker/compose下配置文件

**Comment by ssongliu** [comment]
感谢反馈，容器编排列表是根据当前运行容器自动获取的，目前快照恢复时只会拉起应用商店起的容器，所以导致这个问题。

下个小版本解决。

**Comment by wanghe-fit2cloud** [comment]
v1.10.1-lts 版本已发布。
