### ISSUE TITLE
[FEATURE]设置密码时的限制字符

### ISSUE THREAD

**Issue by iwvw** [1Panel-dev/1Panel#4029]
### 1Panel 版本

v1.10.0-lts

### 请描述您的需求或者改进建议

希望设置密码的特殊字符限制不那么死，例如```.```没法输入

**Comment by ssongliu** [comment]
感谢反馈，这里是针对的面板密码吗？

**Comment by iwvw** [comment]
> 感谢反馈，这里是针对的面板密码吗？

是这里的密码，只要是输入框都不行，例如导入原有数据库时密码带```.```就无法输入：
![image](https://github.com/1Panel-dev/1Panel/assets/81206855/d72acdab-f314-45d4-93e9-e630cfc7f438)

**Comment by ssongliu** [comment]
> > 感谢反馈，这里是针对的面板密码吗？
> 
> 是这里的密码，只要是输入框都不行，例如导入原有数据库时密码带`.`就无法输入： ![image](https://private-user-images.githubusercontent.com/81206855/308861761-d72acdab-f314-45d4-93e9-e630cfc7f438.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxOTc4MzAsIm5iZiI6MTcwOTE5NzUzMCwicGF0aCI6Ii84MTIwNjg1NS8zMDg4NjE3NjEtZDcyYWNkYWItZjMxNC00NWQ0LTkzZTktZTYzMGNmYzdmNDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA5MDUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZTgwNTdlZTg2M2U5NmIzZDk1Yjc3ZjJhMzdiZGEyNzgwYmRhNTE4MjVhZWEwZmIyMjg3YWY1NWZjZWRkMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q9EReuQ8Nj10NlJJ_mVgdX_5ajD6l3mLwOq2RHS8Ze0)

🫡 收到，后面版本优化

**Comment by NyaDoo** [comment]
是的我也遇到了，另外补充一下，面板的密码，在命令行情况下（首次设置），也是部分特殊字符无法使用的，在后续web端面板里面设置可以正常设置没有相关限制。

**Comment by ssongliu** [comment]
> > 感谢反馈，这里是针对的面板密码吗？
> 
> 是这里的密码，只要是输入框都不行，例如导入原有数据库时密码带`.`就无法输入： ![image](https://private-user-images.githubusercontent.com/81206855/308861761-d72acdab-f314-45d4-93e9-e630cfc7f438.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzY5NTYsIm5iZiI6MTcwOTI3NjY1NiwicGF0aCI6Ii84MTIwNjg1NS8zMDg4NjE3NjEtZDcyYWNkYWItZjMxNC00NWQ0LTkzZTktZTYzMGNmYzdmNDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA3MDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMjIxOGU3ODc0ZTA3ZDFkOTZhYzFmNzEwNTA0MjgyMzg0YjM4MDNhYzM5NGZjNjY1YmViZWRmYjVmYTlmYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EWjO2Klr6ijrk-qrUBOrzCxgEoSV8KkSztzv5PkqlX0)

这里限制不是因为 `.` 而是特殊字符不能在首尾

**Comment by ssongliu** [comment]
> 是的我也遇到了，另外补充一下，面板的密码，在命令行情况下（首次设置），也是部分特殊字符无法使用的，在后续web端面板里面设置可以正常设置没有相关限制。

安全起见，安装面板时，密码强度与开启下面选项时的校验保持一致：
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/d6776a51-d93b-44aa-9403-0ac57fc13c7a)

**Comment by NyaDoo** [comment]
> > 是的我也遇到了，另外补充一下，面板的密码，在命令行情况下（首次设置），也是部分特殊字符无法使用的，在后续web端面板里面设置可以正常设置没有相关限制。
> 
> 安全起见，安装面板时，密码强度与开启下面选项时的校验保持一致： ![image](https://private-user-images.githubusercontent.com/73214554/309178679-d6776a51-d93b-44aa-9403-0ac57fc13c7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODk1NzMsIm5iZiI6MTcwOTI4OTI3MywicGF0aCI6Ii83MzIxNDU1NC8zMDkxNzg2NzktZDY3NzZhNTEtZDkzYi00NGFhLTk0MDMtMGFjNTdmYzEzYzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDEwMzQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNTVlYjlkNjYzYzQ1MzQyZTJkMWZkMzk3MjNlZDNmZDA2NDFiNzdjODZlMGIwYTRmYzAzZGRkZDgzMmU3MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DuEL2Jffr6xyBWWgPKIbXyiE2oSd1fwONgp-Q6P0Dzk)

不是因为强度不够，而是部分特殊字符在安装面板时是不被接受的，web端设置时可以被接受，例如&字符

**Comment by wanghe-fit2cloud** [comment]
> 不是因为强度不够，而是部分特殊字符在安装面板时是不被接受的，web端设置时可以被接受，例如&字符

如果是这种情况，建议安装完成之后进入系统来手动修改密（也可以是用 1pctl 命令来重置密码）
> 安装时是 shell 的校验规则，与 Web 端校验规则不一致。

**Comment by MG5921MY** [comment]
> > > 感谢反馈，这里是针对的面板密码吗？
> > 
> > 
> > 是这里的密码，只要是输入框都不行，例如导入原有数据库时密码带就无法输入：`.`![image](https://private-user-images.githubusercontent.com/81206855/308861761-d72acdab-f314-45d4-93e9-e630cfc7f438.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxOTc4MzAsIm5iZiI6MTcwOTE5NzUzMCwicGF0aCI6Ii84MTIwNjg1NS8zMDg4NjE3NjEtZDcyYWNkYWItZjMxNC00NWQ0LTkzZTktZTYzMGNmYzdmNDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA5MDUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZTgwNTdlZTg2M2U5NmIzZDk1Yjc3ZjJhMzdiZGEyNzgwYmRhNTE4MjVhZWEwZmIyMjg3YWY1NWZjZWRkMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q9EReuQ8Nj10NlJJ_mVgdX_5ajD6l3mLwOq2RHS8Ze0)
> 
> 🫡 收到，后面版本优化

这个怎么还是不能设置特殊符号结尾 我redis 密码最后一位是英文符号 但是新建容器选择redis 缓存 没有办法设置密码

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > > Thanks for the feedback, is this the panel password for the target?
> >
> >
> > It is the password here, as long as it is an input box, for example, when importing the original database, the password cannot be entered: `.`![image](https://private-user-images.githubusercontent.com/81206855/308861761-d72acdab-f314-45d4-93e9-e630cfc7f438.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRod WIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxOTc4MzAsIm5iZiI6MTcwOTE5NzUzMCwicGF0aCI6Ii84MTIwNjg1NS8zMDg4NjE3NjEtZDcyYWNkYWItZjMxNC00NWQ0LTkzZTktZTYzMGNmYzdmNDM4LnBuZz9YLUFtei 1BbGdvcmml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA5MDUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2l nbmF0dXJlPWE5ZTgwNTdlZTg2M2U5NmIzZDk1Yjc3ZjJhMzdiZGEyNzgwYmRhNTE4MjVhZWEwZmIyMjg3YWY1NWZjZWRkMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q9EReuQ8Nj10NlJJ_mVgdX_5ajD6l3mLwOq2RHS8Ze0)
>
> 🫡 Received, the subsequent version is optimized

Why can't you set the end of special symbols? My redis password last digit is an English symbol. But if you create a new container, you can select the redis cache. There is no way to set the password.
