### ISSUE TITLE
[FEATURE] 1Panel 与 应用商店解耦和

### ISSUE THREAD

**Issue by mobeicanyue** [1Panel-dev/1Panel#4032]
### 1Panel 版本

1.10

### 请描述您的需求或者改进建议

建议 1Panel 与 应用商店解耦和
好处： 
根据我的观察，应用商店只是简单的 docker-compose.yml，经过测试即可使用
但是 1panel 稳定版发布却需要一段时间，在这段时间内如果有来自应用商店的更新 用户无法立即更新。

### 请描述你建议的实现方案

应用商店 docker-compose.yml 更新之后，1Panel 面板可以收到并更新

**Comment by zhengkunwang223** [comment]
当前已经是解耦的 我们会不定时更新  基本是按周

**Comment by mobeicanyue** [comment]
看了一下 appstore 的 acions 流程，不太理解
[renovate-app-version.sh](https://github.com/1Panel-dev/appstore/blob/dev/.github/workflows/renovate-app-version.sh)
好像只是从本地获取版本并命名，那么新版本号从哪里来，没看到 fetch 的部分

**Comment by mobeicanyue** [comment]
看了一下好像是每天八点更新（utc0）的 但是好像Umami 2.10 发版两天了 并没有在appstore 里看到 bot 推送 pr 更新

**Comment by wanghe-fit2cloud** [comment]
> 但是好像Umami 2.10 发版两天了 并没有在appstore 里看到 bot 推送 pr 更新

是的，脚本检测不到 GitHub 镜像仓库的更新，我们近期会手动更新并推送

**Comment by mobeicanyue** [comment]
> 是的，脚本检测不到 GitHub 镜像仓库的更新，我们近期会手动更新并推送

请问更新操作是这个文件进行的吗
https://github.com/1Panel-dev/appstore/blob/dev/.github/workflows/renovate.yml

**Comment by wanghe-fit2cloud** [comment]
> > 是的，脚本检测不到 GitHub 镜像仓库的更新，我们近期会手动更新并推送
> 
> 请问更新操作是这个文件进行的吗 https://github.com/1Panel-dev/appstore/blob/dev/.github/workflows/renovate.yml

已更新，本地适配成功后会推送。
https://github.com/1Panel-dev/appstore/commit/027a50f8643d51d16daf688b97eb87b375085f23

**Comment by mobeicanyue** [comment]
好像应用商店推送了1panel 但是App Store并不能更新哦，得更新1panel 版本
![1000057590](https://github.com/1Panel-dev/1Panel/assets/81098819/a9c3f7b9-cb52-4ccd-892e-ab303ceb6574)

**Comment by zhengkunwang223** [comment]
> 好像应用商店推送了1panel 但是App Store并不能更新哦，得更新1panel 版本 ![1000057590](https://private-user-images.githubusercontent.com/81098819/310434376-a9c3f7b9-cb52-4ccd-892e-ab303ceb6574.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTY5NTEsIm5iZiI6MTcwOTcxNjY1MSwicGF0aCI6Ii84MTA5ODgxOS8zMTA0MzQzNzYtYTljM2Y3YjktY2I1Mi00Y2NkLTg5MmUtYWIzMDNjZWI2NTc0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA5MTczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YWVkMTE2M2JlMmVjN2UxMTQxM2U1OTU0Nzg4OTA5YmI2YTVhYTBlZGMwNTBlZmFiYjYwMDgwYWRhMDBmZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l9R62cJ65T5lRzCony8Mcd2iN9sAgSQ1-aa5oS2BwDo)

需要手动点击更新应用列表
默认是 晚上 12 点自动同步

**Comment by mobeicanyue** [comment]
> 需要手动点击更新应用列表 默认是 晚上 12 点自动同步

收到 感谢你们的付出
