### ISSUE TITLE
在网站访问限制中增加选型[FEATURE]

### ISSUE THREAD

**Issue by Newzealcoin** [1Panel-dev/1Panel#4033]
### 1Panel 版本

v1.10.0

### 请描述您的需求或者改进建议

1. IP限制，中国内地IP可以/不可以访问网站，外贸站很怕遭到同行的DDOS，大部分都有这个需求。
2. 需要密码访问中可否增加口令访问，无需账号和密码即可登录。

**Comment by zhengkunwang223** [comment]
1. IP 地理位置限制会在专业版中做
2. 这个还得看 nginx 是否支持

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
网站地域限制相关需求的讨论，统一汇总到该  issue #1737
