### ISSUE TITLE
(请求超时)页面错误弹出[BUG]

### ISSUE THREAD

**Issue by DB-lost** [1Panel-dev/1Panel#4034]
### 1Panel 版本

v1.10.0-lts

### 问题描述

在界面老是会弹出请求超时的提示框，f12发现似乎是某一个文件请求超时
![1709255228696](https://github.com/1Panel-dev/1Panel/assets/32891752/25f37bc5-c949-4bdd-8adc-75663d1ae610)

### 重现步骤

打开在页面一会就会有这个提示

### 期待的正确结果

消除这个提示

**Comment by DB-lost** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/32891752/191de464-6b83-46de-8bb5-8ddfe681d3a9)

**Comment by DB-lost** [comment]
发现是这个接口请求超时![image](https://github.com/1Panel-dev/1Panel/assets/32891752/72b84880-1ee2-4f95-b5d2-ecabfd6b1d6b)
似乎是检查面板升级的接口请求超时了

**Comment by zhengkunwang223** [comment]
首页会请求阿里云的OSS来获取更新的版本 
你的服务器可能请求不到

**Comment by DB-lost** [comment]
好的，是我服务器没有配置出站规则，现在已经可以了
