### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by imumu233** [1Panel-dev/1Panel#4035]
### 联系方式

yke_hao@163.com

### 1Panel 版本

1.10.0-lts

### 问题描述

原应用在compose增加了挂载目录     应用升级后挂载路径丢失了

### 重现步骤

1.alist目录旧版本修改compose文件新增挂载路径
2.升级应用
3.查看应用挂载路径，发现新增的挂载路径丢失，需要重新添加

**Comment by wanghe-fit2cloud** [comment]
应用升级时兼容之前修改的 compose 文件的需求，统一汇总到该 issue #3801
