### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by linshuboy** [1Panel-dev/1Panel#4037]
### 1Panel 版本

1.9.4-1.10.0

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/20389206/0fa6e796-3d57-4d78-9de1-25c5c9e1ee63)
内存缓慢堆积

### 重现步骤

装了网站 计划任务 容器,然后放几天就会这样

### 期待的正确结果

解答问题的原因,并修复

**Comment by wanghe-fit2cloud** [comment]
`主机` - `监控` 页面是实时获取的主机内存等资源使用情况，并将历史数据入库，不存在堆积、修复问题。

**Comment by ssongliu** [comment]
可以检查一下是什么东西在占用内存

**Comment by linshuboy** [comment]
> 可以检查一下是什么东西在占用内存

检查过了,所有的都不高
![image](https://github.com/1Panel-dev/1Panel/assets/20389206/da425398-2ee4-418a-9b23-6a2bd60d6d83)

**Comment by ssongliu** [comment]
> > 可以检查一下是什么东西在占用内存
> 
> 检查过了,所有的都不高 ![image](https://private-user-images.githubusercontent.com/20389206/309193523-da425398-2ee4-418a-9b23-6a2bd60d6d83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODE1MDQsIm5iZiI6MTcwOTI4MTIwNCwicGF0aCI6Ii8yMDM4OTIwNi8zMDkxOTM1MjMtZGE0MjUzOTgtMmVlNC00MThhLTliMjMtNmEyYmQ2MGQ2ZDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA4MjAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZWQ1MGQ5MGYyMWY2MzY1NGFhN2RjMTc4NTNkODBiNGFiZjViYWQ1ZTRkMDljNTNiMmJiODNmNTAzYWIyNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8i7tM_ZNwL9kgd8ciuIcfhpXQbleMpIYyaakMpqhLVw)

重启一下 1panel 服务，看看是否会降下来

**Comment by linshuboy** [comment]
> > > 可以检查一下是什么东西在占用内存
> > 
> > 
> > 检查过了,所有的都不高 ![image](https://private-user-images.githubusercontent.com/20389206/309193523-da425398-2ee4-418a-9b23-6a2bd60d6d83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODE1MDQsIm5iZiI6MTcwOTI4MTIwNCwicGF0aCI6Ii8yMDM4OTIwNi8zMDkxOTM1MjMtZGE0MjUzOTgtMmVlNC00MThhLTliMjMtNmEyYmQ2MGQ2ZDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA4MjAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZWQ1MGQ5MGYyMWY2MzY1NGFhN2RjMTc4NTNkODBiNGFiZjViYWQ1ZTRkMDljNTNiMmJiODNmNTAzYWIyNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8i7tM_ZNwL9kgd8ciuIcfhpXQbleMpIYyaakMpqhLVw)
> 
> 重启一下 1panel 服务，看看是否会降下来

现在我已经重启主机了,降下来了.重启1panel服务应该是降不下来,因为中间经历过版本升级,那时候肯定重启过了

**Comment by ssongliu** [comment]
> > > > 可以检查一下是什么东西在占用内存
> > > 
> > > 
> > > 检查过了,所有的都不高 ![image](https://private-user-images.githubusercontent.com/20389206/309193523-da425398-2ee4-418a-9b23-6a2bd60d6d83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODE1MDQsIm5iZiI6MTcwOTI4MTIwNCwicGF0aCI6Ii8yMDM4OTIwNi8zMDkxOTM1MjMtZGE0MjUzOTgtMmVlNC00MThhLTliMjMtNmEyYmQ2MGQ2ZDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA4MjAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZWQ1MGQ5MGYyMWY2MzY1NGFhN2RjMTc4NTNkODBiNGFiZjViYWQ1ZTRkMDljNTNiMmJiODNmNTAzYWIyNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8i7tM_ZNwL9kgd8ciuIcfhpXQbleMpIYyaakMpqhLVw)
> > 
> > 
> > 重启一下 1panel 服务，看看是否会降下来
> 
> 现在我已经重启主机了,降下来了.重启1panel服务应该是降不下来,因为中间经历过版本升级,那时候肯定重启过了

那就不是 1panel 服务的问题，观察观察吧

**Comment by linshuboy** [comment]
> > > > > 可以检查一下是什么东西在占用内存
> > > > 
> > > > 
> > > > 检查过了,所有的都不高 ![image](https://private-user-images.githubusercontent.com/20389206/309193523-da425398-2ee4-418a-9b23-6a2bd60d6d83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODE1MDQsIm5iZiI6MTcwOTI4MTIwNCwicGF0aCI6Ii8yMDM4OTIwNi8zMDkxOTM1MjMtZGE0MjUzOTgtMmVlNC00MThhLTliMjMtNmEyYmQ2MGQ2ZDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA4MjAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZWQ1MGQ5MGYyMWY2MzY1NGFhN2RjMTc4NTNkODBiNGFiZjViYWQ1ZTRkMDljNTNiMmJiODNmNTAzYWIyNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8i7tM_ZNwL9kgd8ciuIcfhpXQbleMpIYyaakMpqhLVw)
> > > 
> > > 
> > > 重启一下 1panel 服务，看看是否会降下来
> > 
> > 
> > 现在我已经重启主机了,降下来了.重启1panel服务应该是降不下来,因为中间经历过版本升级,那时候肯定重启过了
> 
> 那就不是 1panel 服务的问题，观察观察吧

好的,感谢解答
