### ISSUE TITLE
[FEATURE]建议增加 docker builder prune 清除构建缓存功能

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4039]
### 1Panel 版本

v1.10.0-lts

### 请描述您的需求或者改进建议

测试发现，重复安装 PHP 运行环境时，会使用缓存进行 Build

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

会体现在下面的两个页面中：

- `网站` - `运行环境`
- `容器` - `镜像`

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/3890
