### ISSUE TITLE
[QUESTION] 概览-监控-磁盘IO的读写延迟没有变化

### ISSUE THREAD

**Issue by newcardriver** [1Panel-dev/1Panel#404]
### 请描述您的问题

我观察了好一会好像一直是这个值。
![image](https://user-images.githubusercontent.com/44741731/227682635-d68be8a8-ae07-4969-b7dd-627349aee33a.png)

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈，我们会在下个版本修复该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.0.4 版本已修复。
