### ISSUE TITLE
[BUG] armv7l系统上，内存限制为负数，导致编辑容器等操作无法成功确认

### ISSUE THREAD

**Issue by BetterAndBetterII** [1Panel-dev/1Panel#4040]
### 联系方式

betteryz@qq.com

### 1Panel 版本

1.10.0 latest

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/141388234/99aa730d-63d9-4177-b42d-dc1319326361)

在应用商店内安装任何软件（高级设置）、编辑容器配置等操作时，会因为内存限制选项无法进行任何操作

### 重现步骤

主机名称raspberrypi 发行版本raspbian-10.13 内核版本5.10.103-v7l+系统类型armv7l

在应用商店内安装任何软件，点开高级设置，不做任何编辑

此时无法进行安装，提示内存显示错误

最大内存限制为负数（如上图所示），即使默认为0，不限制内存

### 期待的正确结果

修改内存限制的读取机制，针对不同内核做适配

**Comment by wanghe-fit2cloud** [comment]
> 在应用商店内安装任何软件，点开高级设置，不做任何编辑
此时无法进行安装，提示内存显示错误

麻烦提供一下点击安装按钮后的错误信息、截图。

**Comment by BetterAndBetterII** [comment]
> > 在应用商店内安装任何软件，点开高级设置，不做任何编辑
> > 此时无法进行安装，提示内存显示错误
> 
> 麻烦提供一下点击安装按钮后的错误信息、截图。

![image](https://github.com/1Panel-dev/1Panel/assets/141388234/bc039d39-d834-486f-a407-2851da00b564)
开启高级配置后会出现

**Comment by wanghe-fit2cloud** [comment]
再提供一下概览页面截图信息（查看一下内存、cpu等获取是否正常）

**Comment by BetterAndBetterII** [comment]
> 再提供一下概览页面截图信息（查看一下内存、cpu等获取是否正常）

![image](https://github.com/1Panel-dev/1Panel/assets/141388234/6190b8c0-15ad-4199-b12f-d23256fff621)
正常

**Comment by wanghe-fit2cloud** [comment]
好的，我们在本地环境复现一下问题。

**Comment by ssongliu** [comment]
麻烦添加一下好友，我看看这个问题
<img width="196" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/73214554/04ca7b2d-7701-4768-9545-9c108c46539c">

**Comment by wanghe-fit2cloud** [comment]
v1.10.1-lts 版本已发布。
