### ISSUE TITLE
[FEATURE] 更新 Node.JS 环境版本

### ISSUE THREAD

**Issue by HenryWu01** [1Panel-dev/1Panel#4041]
### 1Panel 版本

1.10.0

### 请描述您的需求或者改进建议

目前 ``20.11.1 LTS`` 和 ``21.6.2`` 版本已经发布，希望 ``1Panel`` 可以更新到最新版本的运行环境~  
感谢**飞致云团队**开发出来一款如此好用的服务器管理面板。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本推送更新。

**Comment by wanghe-fit2cloud** [comment]
v1.10.1-lts 版本已发布。

**Comment by HenryWu01** [comment]
> v1.10.1-lts 版本已发布。

收到~辛苦了
