### ISSUE TITLE
[FEATURE] 左侧菜单可以加一个固定操作吗，每次都要先点展开很麻烦

### ISSUE THREAD

**Issue by SunsetSail** [1Panel-dev/1Panel#4042]
### 1Panel 版本

v1.10.0-lts

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/52393675/aa09ff60-64e7-44ba-8042-b5728a6422a4)

对于大屏来说 折叠真的没必要

**Comment by wanghe-fit2cloud** [comment]
手动清理浏览器缓存或者更换其他浏览器。
> 默认就是展开状态。
