### ISSUE TITLE
[FEATURE] 设置 SSH 端口后，应修改主机-终端的本地服务器端口

### ISSUE THREAD

**Issue by RealHeart** [1Panel-dev/1Panel#4043]
### 1Panel 版本

v1.10.0

### 请描述您的需求或者改进建议

在 `主机-SSH管理` 中设置 SSH 端口后，应修改 `主机-终端` 中 `本地服务器` 的端口设置

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.2-lts 版本已发布。
