### ISSUE TITLE
[BUG] 终端编辑时，需要重新填入私钥信息

### ISSUE THREAD

**Issue by RealHeart** [1Panel-dev/1Panel#4044]
### 1Panel 版本

v1.10.0

### 问题描述

在 `主机-终端` 编辑终端配置时, 需要重新输入私钥

### 重现步骤

在 `主机-终端` 编辑终端配置

### 期待的正确结果

编辑时，如已有信息无需校验，仅修改端口也可保存成功

**Comment by igophper** [comment]
看了是必须连接测试成功才能点击确定保存。可以改为，如果没填私钥，就拿已经存在的私钥进行连接测试。
测试成功，然后就点击保存。

**Comment by wanghe-fit2cloud** [comment]
添加主机时，我们提供了 `记住密码` 功能。
> 如果勾选该选项，在编辑主机时会默认回显密码及私钥。
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/60afb815-3b36-4bd4-ab29-890631837461">
