### ISSUE TITLE
求增加alpinelinux系统的安装支持

### ISSUE THREAD

**Issue by kof8855** [1Panel-dev/1Panel#4047]
### 1Panel 版本

求增加alpinelinux系统的支持

### 请描述您的需求或者改进建议

求增加alpinelinux系统的安装支持

### 请描述你建议的实现方案

求增加alpinelinux系统的安装支持

### 附加信息

求增加alpinelinux系统的安装支持

**Comment by wanghe-fit2cloud** [comment]
alpine 没有使用 fedora 的 systemctl 来进行服务管理，使用的是 RC 系列命令。

> 我们近期暂无适配计划
没有 systemctl 的可以使用社区用户提供的 [docker 版](https://hub.docker.com/r/moelin/1panel)

**Comment by xiahao90** [comment]
求增加alpinelinux系统的支持
