### ISSUE TITLE
[BUG] 创建 PHP 运行环境网站时 PHP 创建失败

### ISSUE THREAD

**Issue by imJack6** [1Panel-dev/1Panel#4049]
### 1Panel 版本

v1.10.0-lts

### 问题描述

我在网站中创建一个运行环境为 PHP 的网站时，创建时没有错误，但当我去访问创建后的网站时提示 `502 Bad Gateway`，然后我前往容器中查看，发现没有刚刚创建的 PHP 容器，又前往应用商店的已安装中查看，发现了那个 PHP 容器创建失败，感叹号显示的是 `1Panel-php8-wF3Z 容器不存在`，日志里面显示的是 `stat /opt/1panel/apps/php8/server/docker-compose.yml: no such file or directory`，我尝试重建 PHP8.2 运行环境，完成后其它的 PHP 网站也已经被重建，但是我再次尝试重新创建网站时 PHP 仍然创建失败。

### 重现步骤

创建网站-运行环境-确认

**Comment by zhengkunwang223** [comment]
你的网站名称是server吗？

**Comment by imJack6** [comment]
> 你的网站名称是server吗？

不，我把一级域名删了（server.xxx.xx）

**Comment by zhengkunwang223** [comment]
正常的目录应该是 /opt/1panel/apps/php8/<网站域名>/docker-compose.yml 
你可以先重新创建一个 然后看一下是不是这个目录

**Comment by imJack6** [comment]
> 正常的目录应该是 /opt/1panel/apps/php8/<网站域名>/docker-compose.yml 你可以先重新创建一个 然后看一下是不是这个目录

我之前看了，没有域名的那个文件夹，以前的是有

**Comment by cli-r** [comment]
需要更新php环境，因为php被更新到了8.2.15，而8.2.10的镜像不存在，我在之前也遇到了同样的问题，后来重新构建镜像后恢复
