### ISSUE TITLE
[FEATURE] 容器终端增加attach功能

### ISSUE THREAD

**Issue by yuanchaolie** [1Panel-dev/1Panel#4051]
### 1Panel 版本

v1.10.0-lts

### 请描述您的需求或者改进建议

如题,可不可以直接使用面板访问容器运行的终端,上次提了交互的需求,就只加了-it

### 请描述你建议的实现方案

docker attach

**Comment by wanghe-fit2cloud** [comment]
推荐使用 1Panel 面板已经提供的 `docker exec` 终端功能，因为它更灵活，并且可以在容器内执行任意命令。

**Comment by yuanchaolie** [comment]
> 推荐使用 1Panel 面板已经提供的 终端功能，因为它更灵活，并且可以在容器内执行任意命令。`docker exec`

可是直接用exec进去,还得创建命名管道才能访问正在运行的bash,比我用ssh远程访问使用docker attach更麻烦
