### ISSUE TITLE
未檢測到系統防火墻-ufw

### ISSUE THREAD

**Issue by oaxtudio** [1Panel-dev/1Panel#4053]
### 请描述您的问题

![IMG_5526](https://github.com/1Panel-dev/1Panel/assets/103622777/eb28b6f4-70d9-4cad-9db1-26da236f932c)
![IMG_5525](https://github.com/1Panel-dev/1Panel/assets/103622777/40cc96e5-f2d9-4307-9483-0ebc96062298)

我已依照官方文檔正確安裝ufw
且正常運行中
但面板始終無法使用防火牆管理功能

面板版本 v1.10.0-lts
發行版本 ubuntu-22.04
內核版本 6.5.0-21-generic
系統類型 x86_64

Btw 希望論壇能增加海外用戶註冊功能

**Comment by wanghe-fit2cloud** [comment]
点击页面状态栏的 `开启` 按钮。
如果依然是未开启状态，就先尝试进入 `主机` - `终端`，手动执行命令来查看、启用 ufw 防火墙：

> 查看状态：`ufw status`
启用：`ufw enable`

**Comment by oaxtudio** [comment]
> 点击页面状态栏的 `开启` 按钮。 如果依然是未开启状态，就先尝试进入 `主机` - `终端`，手动执行命令来查看、启用 ufw 防火墙：
> 
> > 查看状态：`ufw status`
> > 启用：`ufw enable`

感謝您的回覆
您提及的解決方案我在提issue前就嘗試過了
我還嘗試過：
>`apt purge ufw`
>`reboot`
>`apt install ufw`
>重啟面版
>面板點擊`防火牆`>`開啟`
ufw還是檢測不到

我也在終端中使用 `sudo ufw status` 
防火牆的確是啟用狀態
問題也依舊

**Comment by ssongliu** [comment]
什么操作系统？是否存在 /usr/sbin/ufw 该文件？

**Comment by oaxtudio** [comment]
![IMG_5537](https://github.com/1Panel-dev/1Panel/assets/103622777/b3ac0776-01d4-4d7b-b1c4-3e1941448bd5)
![IMG_5539](https://github.com/1Panel-dev/1Panel/assets/103622777/97997790-f6b4-4e6f-bb01-b39678efb6b3)

1.Ubuntu Desktop 22.04 lts 
2.有的

**Comment by oaxtudio** [comment]
1.Ubuntu Desktop 22.04 lts

2.有的 

> 我使用以下命令：
> >  `find /usr/sbin -name ufw`

> 返回訊息
> >  `/usr/sbin/ufw`

**Comment by ssongliu** [comment]
麻烦添加我好友，我看看这个问题
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/889e2bee-0c8e-4712-b384-a5fe044a7921)
