### ISSUE TITLE
[QUESTION]提交编排模板时提示当前用户无权限的一种情况

### ISSUE THREAD

**Issue by lanqiguoguo** [1Panel-dev/1Panel#4054]
### 请描述您的问题

使用OpenResty代理面板时并开启waf的POST 参数校验会拦截包含 data:/ 的编排模板

例如编辑编排模板并确定时提交的参数：
```
{"id":1,"createdAt":"2024-02-28T23:08:27.607131007+08:00","name":"gotify","description":"","content":"version: \"3\"\n\nservices:\n  gotify:\n    image: gotify/server:2.4.0\n    container_name: gotify\n    restart: unless-stopped\n    ports:\n      - 80:80\n    environment:\n      - GOTIFY_DEFAULTUSER_NAME=xxx\n      - GOTIFY_DEFAULTUSER_PASS=xxx\n    volumes:\n      - \"./data:/app/data\"\n    networks:\n      - 1panel-network\nnetworks:\n    1panel-network:\n        external: true"}
```
waf的POST 参数校验：
```
(gopher|doc|php|glob|^file|phar|zlib|ftp|ldap|dict|ogg|data)\:\/  PHP流协议过滤1
```
如图：
![image](https://github.com/1Panel-dev/1Panel/assets/24531655/7572ddcc-59b7-4929-af13-50715597df43)

参考[wangzhengkun](https://bbs.fit2cloud.com/u/wangzhengkun)回答论坛的相关问题：
[安装halo报错“当前用户权限不足” 并提出到登录页](https://bbs.fit2cloud.com/t/topic/2322)
[使用管理员账号安装redis会提示当前用户无权限并跳转到登录页面](https://bbs.fit2cloud.com/t/topic/1702)

**Comment by wanghe-fit2cloud** [comment]
是的，就是因为开启了 WAF 的 POST 参数校验。

> 应用商店创建应用、添加编排模版等都涉及到 yaml、json 等类型的数据
