### ISSUE TITLE
[BUG] 快照恢復跨平臺問題。1pctl 命令 arm 機器無法使用

### ISSUE THREAD

**Issue by RUTHDOMINGUEZ8216** [1Panel-dev/1Panel#4056]
### 联系方式

WX: willywang8216

### 1Panel 版本

v1.10.0-lts

### 问题描述

用amd 機器的快照在arm機器上無法恢復

### 重现步骤

在原來的機器amd 上面 ，加入一些應用程式 並且綁定域名開啟ssl等。。。快照，然後備份到amz s3 ， 然後在新的機器上arm64 面登入到同樣的備份帳號 ，取得備份檔案之後 ，使用恢復功能 ，然後錯誤就產生了

### 期待的正确结果

正常快照恢復

### 相关日志输出

```shell
1panel 一直restarting


 1panel.service - 1Panel, a modern open source linux panel
     Loaded: loaded (/etc/systemd/system/1panel.service; enab>     Active: activating (auto-restart) (Result: exit-code) si>    Process: 3987945 ExecStart=/usr/bin/1panel (code=exited, >   Main PID: 3987945 (code=exited, status=203/EXEC)
        CPU: 1ms
```

所有1pctl命令無法使用，產生如下錯誤

```
/usr/local/bin/1pctl: line 70: /usr/local/bin/1panel: cannot execute binary file: Exec format error
```
```


### 附加信息

_No response_

**Comment by wanghe-fit2cloud** [comment]
不能跨服务器架构来进行恢复操作。
> 后续版本我们会增加快照文件架构信息，以确保不会出现跨服务器架构的情况。

**Comment by RUTHDOMINGUEZ8216** [comment]
好的。謝謝告知，另外也感謝你們團隊對1panel的付出真的非常的好用，感恩，祝事事順心如意。

**Comment by RUTHDOMINGUEZ8216** [comment]
@wanghe-fit2cloud 
您好。今天用相同架構的服務器。進行遷移，作業結果快照遷移看來是成功的，不過因為面板綁定的是原本機器的IP位置，那在命令行工具列中沒有辦法改綁定IP位置（不是監聽ip) 請問這個要怎麼把舊的IP改成新的，當遷移到新的機器之後可用。謝謝您

**Comment by wanghe-fit2cloud** [comment]
> @wanghe-fit2cloud 您好。今天用相同架構的服務器。進行遷移，作業結果快照遷移看來是成功的，不過因為面板綁定的是原本機器的IP位置，那在命令行工具列中沒有辦法改綁定IP位置（不是監聽ip) 請問這個要怎麼把舊的IP改成新的，當遷移到新的機器之後可用。謝謝您

进入面板设置页面，手动修改服务器地址即可。
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/26561af8-9cf6-4c76-871a-7d14a95591f9)

**Comment by RUTHDOMINGUEZ8216** [comment]
> > @wanghe-fit2cloud 您好。今天用相同架構的服務器。進行遷移，作業結果快照遷移看來是成功的，不過因為面板綁定的是原本機器的IP位置，那在命令行工具列中沒有辦法改綁定IP位置（不是監聽ip) 請問這個要怎麼把舊的IP改成新的，當遷移到新的機器之後可用。謝謝您
> 
> 进入面板设置页面，手动修改服务器地址即可。 ![image](https://private-user-images.githubusercontent.com/46734380/309960298-26561af8-9cf6-4c76-871a-7d14a95591f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDU0ODIsIm5iZiI6MTcwOTYwNTE4MiwicGF0aCI6Ii80NjczNDM4MC8zMDk5NjAyOTgtMjY1NjFhZjgtOWNmNi00Yzc2LTg3MWEtN2QxNGE5NTU5MWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAyMTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNDdhOTkzMDY3ZDQ4YjM2OWU5YjkzN2M5YjAyNjc5ZTI2MzE2N2Y1ZmM3NzM3MDA1YmIwOTQ3ZDFlNGU3MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MTdK-3QMS7t5Vg_FdJqsqgpMzi5TnygLBwHCwmbdHDE)

面板進入不了， 因為我快照恢復的是其他機器的，假設我現在有一個A機器綁定了a機器的IP，然後我進行的快照，我把這個快照在B機器恢復，那這個綁定的IP還是A機器的，我沒辦法在B機器上面進到面板頁面來改這個IP

**Comment by wanghe-fit2cloud** [comment]
`1pctl status` 确认一下服务运行状态。
如果状态正常的话，使用 `新服务器 IP + 端口` 访问即可。
成功进入面板之后，再去 `面板设置` 页面修改 `服务器地址`，之后再使用 `1pctl user-info` 命令查询就是更新之后的 IP 地址了

> `netstat -ntlp` 查看一下服务端口绑定 IP 情况（可以区分是 tcp 还是 tcp6）

**Comment by wanghe-fit2cloud** [comment]
v1.10.1-lts 版本已发布。
