### ISSUE TITLE
简化重装后 恢复快照逻辑

### ISSUE THREAD

**Issue by d4renk** [1Panel-dev/1Panel#4063]
### 1Panel 版本

v1.10.0-lts

### 请描述您的需求或者改进建议

在机器重装后，需要先手动配置面板，然后再进入面板手动上传快照，希望可以通过安装脚本并指定快照链接或本地快照路径，实现一键恢复系统快照的功能。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们暂无支持上述需求的计划，望理解。

**Comment by d4renk** [comment]
@wanghe-fit2cloud 你们是否欢迎 我写的恢复快照脚本 提交到你们仓库

**Comment by wanghe-fit2cloud** [comment]
> @wanghe-fit2cloud 你们是否欢迎 我写的恢复快照脚本 提交到你们仓库

欢迎分享你的项目地址，以支持其他社区成员满足类似需求。
> 目前暂不考虑将其合并至主分支，望理解。
