### ISSUE TITLE
Gitea使用的是国内的镜像源[FEATURE]

### ISSUE THREAD

**Issue by Moriaty911** [1Panel-dev/1Panel#4065]
### 1Panel 版本

1.9.6

### 请描述您的需求或者改进建议

Gitea在拉取镜像时使用的是gitea.cn的镜像源，国外主机下载速度很慢。希望能让用户选择从哪个源进行下载。

**Comment by zhangyz189** [comment]
自定义下docker-compose应该能解决你的问题
“安装”=>“编辑 compose 文件”=>"image: gitea.cn/gitea/gitea:1.21.7"
[示例](https://img.mtdxx.com/images/202403050903211709600601.jpg)
