### ISSUE TITLE
[FEATURE] 希望MySQL远程服务器在连接时能支持指定数据库

### ISSUE THREAD

**Issue by inwinter04** [1Panel-dev/1Panel#4066]
### 1Panel 版本

v1.10.0-lts

### 请描述您的需求或者改进建议

MySQL远程服务器目前仅能指定几个参数：`数据库地址`，`数据库版本`，`端口`，`用户名`，`密码`。
这就导致只能使用**root 用户或者拥有 root 权限的数据库用户**才能够正常正常使用。
非root权限用户进行从服务器获取时出现错误：
```
服务内部错误: Error 1142 (42000): SELECT command denied to user '用户名'@'我的1Panel IP' for table 'db'
```

### 请描述你建议的实现方案

在创建MySQL远程服务器时指定数据库名，保证非root用户也能访问到自己有权限的数据库

### 附加信息

我添加的MySQL远程数据库为**SQL Pub**提供的免费数据库，用于日常的测试。故分配到的数据库用户只有对应数据库的使用权限。

**Comment by wanghe-fit2cloud** [comment]
由于在页面上添加了远程数据库，后续许多操作需要使用 MySQL root 用户权限，例如在部署应用时创建应用数据库等。
因此，目前我们暂时不支持导入非 root 用户，望谅解。
