### ISSUE TITLE
[FEATURE] 增加一个类似于 aaPanel 的防火墙系统和大屏面板

### ISSUE THREAD

**Issue by HenryWu01** [1Panel-dev/1Panel#407]
### 1Panel 版本

1.0.3

### 请描述您的需求或者改进建议

aaPanel (宝塔国际版) 有一个 Nginx WAF 防火墙插件，这个插件我感觉做的很好的一点就是他针对 nginx 添加了很多的防火墙配置，并且有拦截实时统计大屏，感觉很炫酷，一目了然的感觉。

除了插件的控制面板逻辑是使用 Cython 编译无法查看，其他的类似 Nginx WAF 的配置都是 lua 和别的文件，可以参考一下。希望 1Panel 也能加入这种防火墙 Tab，比如在左侧菜单加一个防火墙的标签卡。

![firefox_Pk90GGTgYq](https://user-images.githubusercontent.com/99880210/227729872-126fc6aa-3f93-49c6-b13c-d4fd274609ac.png)

### 请描述你建议的实现方案

aaPanel WAF 面板主页:
![firefox_aTt5bBrdAu](https://user-images.githubusercontent.com/99880210/227729914-851f7745-1531-41e2-a57b-02bb6e9876ae.png)

aaPanel WAF 报告页面:
![firefox_2qjeoXv8n2](https://user-images.githubusercontent.com/99880210/227729933-08c71527-45f1-4645-9d3f-025f8cb135d9.png)

aaPanel WAF 设置页面:
![firefox_pyuJBXV4hA](https://user-images.githubusercontent.com/99880210/227729950-df48ccf2-5cb3-4e8d-a558-7d832b4584e3.png)

aaPanel WAF 网站页面:
![firefox_Qy54Z4OPnr](https://user-images.githubusercontent.com/99880210/227729963-ab96c518-c862-4c14-97c0-fa0b2b0eda5e.png)

aaPanel WAF 封锁页面:
![firefox_8urVKriB0H](https://user-images.githubusercontent.com/99880210/227729982-4779da98-058b-413b-b69d-66287943d749.png)

以及操作日志界面:

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会考虑增加应用防火墙概览功能。

**Comment by maninhill** [comment]
未来通过集成第三方 WAF 解决。

**Comment by maninhill** [comment]
https://github.com/1Panel-dev/1Panel/issues/2009
