### ISSUE TITLE
安装数据库失败

### ISSUE THREAD

**Issue by qingsongxi** [1Panel-dev/1Panel#4072]
### 请描述您的问题

![image](https://github.com/1Panel-dev/1Panel/assets/31014574/244ca33a-f586-4aad-b27b-f4ab36cc3983)

**Comment by wanghe-fit2cloud** [comment]
进入 `主机` - `终端`，查询一下 MySQL 应用镜像是否已拉取成功：
```shell
docker images | grep mysql
```

**Comment by wanghe-fit2cloud** [comment]
先关闭该 issue 了，如果不是镜像拉取超时的问题，再继续讨论。
