### ISSUE TITLE
[BUG]安装dosgame失败, 日志:  1Panel-dosgame-KcD4  | exec /bin/sh: exec format error

### ISSUE THREAD

**Issue by git-Ander** [1Panel-dev/1Panel#4073]
### 1Panel 版本

v1.10.0-lts

### 问题描述

日志:   1Panel-dosgame-KcD4  | exec /bin/sh: exec format error

### 重现步骤

安装dosgame失败

**Comment by wanghe-fit2cloud** [comment]
该应用只支持 x86_64 架构服务器。

**Comment by git-Ander** [comment]
能支持吗

**Comment by wanghe-fit2cloud** [comment]
<img width="1198" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/16ad4406-3c49-4fdc-a23e-010bd646b359">
