### ISSUE TITLE
[BUG] 每次升级halo都需要重新配置一次.ENV文件的参数添加一次PANEL_DB_TYPE="mysql"

### ISSUE THREAD

**Issue by XM2510136957** [1Panel-dev/1Panel#4074]
### 联系方式

2510136957@qq.com

### 1Panel 版本

v1.10.0-lts

### 问题描述

每次升级halo都需要重新配置一次.ENV文件的参数添加一次PANEL_DB_TYPE="mysql"

### 重现步骤

每次升级halo都需要重新配置一次.ENV文件的参数添加一次PANEL_DB_TYPE="mysql"

### 期待的正确结果

每次升级halo都需要重新配置一次.ENV文件的参数添加一次PANEL_DB_TYPE="mysql"

**Comment by wanghe-fit2cloud** [comment]
我们在 v1.9.3 版本增加了 `PANEL_DB_TYPE` 参数（安装 Halo 时支持 MySQL、MariaDB 和 PostgreSQL 数据库）
后续版本如果再次升级 Halo 就不会出现上述情况。
> v1.9.3 版本之后在本地和社区均未复现问题。

你也可以通过 1Panel 来全新安装 Halo，成功后再导入 Halo 备份（Halo 自身有提供备份恢复功能）
之后再来观察是否还存在问题。
> 可以进入微信交流群，添加 `王贺` 好友，远程来看看问题。
