### ISSUE TITLE
[FEATURE] 快照功能希望可以设置排除文件夹

### ISSUE THREAD

**Issue by Ben-Huang** [1Panel-dev/1Panel#4076]
### 1Panel 版本

v1.10.0-lts

### 请描述您的需求或者改进建议

alist应用在上传文件时会在/opt/1panel/apps/alist/alist/data/data/temp 文件夹内写入临时文件,上传完成后才会删除,
如果在alist应用上传文件期间创建快照,alist应用的临时文件会被打包进快照里面,导致快照文件过大,
希望快照希望可以设置排除文件夹,被排除的文件夹不会打包进快照文件.

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by mobeicanyue** [comment]
在计划任务中的备份功能中，可以备份单个文件吗？比如说 vaultwarden 的 db.sqlite3，目前只发现了备份文件夹
![image](https://github.com/1Panel-dev/1Panel/assets/81098819/050a2809-3986-4f5b-9a66-e53d6da7d895)

**Comment by wanghe-fit2cloud** [comment]
> 在计划任务中的备份功能中，可以备份单个文件吗？比如说 vaultwarden 的 db.sqlite3，目前只发现了备份文件夹 !

暂不支持备份单个文件。

**Comment by wanghe-fit2cloud** [comment]
v1.10.2-lts 版本已发布。
