### ISSUE TITLE
[BUG]cloudflared docker bridge 配置问题

### ISSUE THREAD

**Issue by HO3OH** [1Panel-dev/1Panel#4079]
### 1Panel 版本

v1.10.0-lts

### 问题描述

appstore 的 cloudflared 应用无法使用

### 重现步骤

在初次 commit 记录种网络模式是 host，后续又补了个 commit 改成了 1panel-network
实际测试，发现 1panel-network 下配置 127.0.0.1:port 亦或者 172.18.0.1:port、docker子网 ip:port 均无法访问服务
修改为 host 模式后，配置 127.0.0.1:port 可正常访问

### 相关日志输出

```shell
2024-03-05T09:10:10Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp 127.0.0.1:9100: connect: connection refused" connIndex=3 event=1 ingressRule=0 originService=http://127.0.0.1:9100
2024-03-05T16:31:47Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp 172.18.0.15:80: connect: connection refused" connIndex=1 event=1 ingressRule=0 originService=http://172.18.0.15
```

**Comment by Anyexyz** [comment]
在 1panel-network网络下建议使用 **服务容器IP:服务容器内部端口** 或者是 **服务容器名:服务容器内部端口**来穿透

**Comment by Anyexyz** [comment]
> ### 联系方式
> _No response_
> 
> ### 1Panel 版本
> v1.10.0-lts
> 
> ### 问题描述
> appstore 的 cloudflared 应用无法使用
> 
> ### 重现步骤
> 在初次 commit 记录种网络模式是 host，后续又补了个 commit 改成了 1panel-network 实际测试，发现 1panel-network 下配置 127.0.0.1:port 亦或者 172.18.0.1:port、docker子网 ip:port 均无法访问服务 修改为 host 模式后，配置 127.0.0.1:port 可正常访问
> 
> ### 期待的正确结果
> _No response_
> 
> ### 相关日志输出
> ```shell
> 2024-03-05T09:10:10Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp 127.0.0.1:9100: connect: connection refused" connIndex=3 event=1 ingressRule=0 originService=http://127.0.0.1:9100
> 2024-03-05T16:31:47Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp 172.18.0.15:80: connect: connection refused" connIndex=1 event=1 ingressRule=0 originService=http://172.18.0.15
> ```
> 
> ### 附加信息
> _No response_

可以提供一下具体操作的端口号，以及容器的端口映射情况

**Comment by Anyexyz** [comment]
![mmexport1709694364149_edit_299762633115717](https://github.com/1Panel-dev/1Panel/assets/53684988/254ebd6e-486b-472d-a8c5-8c3b32ea1866)
![mmexport1709694367887](https://github.com/1Panel-dev/1Panel/assets/53684988/2aa64275-bd24-4d55-972d-cbf70cae659d)
![mmexport1709694366083](https://github.com/1Panel-dev/1Panel/assets/53684988/c7811656-2975-4d4f-a0ce-9235fe464c18)
参考这个配置

**Comment by HO3OH** [comment]
> 在 1panel-network网络下建议使用 **服务容器IP:服务容器内部端口** 或者是 **服务容器名:服务容器内部端口**来穿透

已验证，可正常穿透。
我错误的理解成了与 Nginx 反代逻辑相同，使用的容器外部映射端口。
感谢解答。
