### ISSUE TITLE
[FEATURE] 添加一个类似于 aaPanel 网站统计的插件

### ISSUE THREAD

**Issue by HenryWu01** [1Panel-dev/1Panel#408]
### 1Panel 版本

1.0.3

### 请描述您的需求或者改进建议

aaPanel (宝塔国际版) 有一个网站统计插件，在这个插件中你可以看到网站的统计信息，PV, UV, 请求数，实时流量等等

希望 1Panel 可以加入这个插件，就比如在左侧的栏中集成这个插件，类似于我上一个 issue 提到的 Nginx WAF。

我看了下宝塔的实现，应该也是基于 nginx 的 lua 插件？

### 请描述你建议的实现方案

aaPanel 网站统计插件截图:

主页:
![firefox_WVU8ZzKaPx](https://user-images.githubusercontent.com/99880210/227730224-05023e5b-d020-4d4d-aa2e-5bdd72c5845f.png)

网站列表:
![firefox_es4HfhZfFC](https://user-images.githubusercontent.com/99880210/227730250-be36fd08-ed0c-4c73-ac52-98b490bde9ed.png)

爬虫分析:
![firefox_mOGaVEYn7h](https://user-images.githubusercontent.com/99880210/227730265-7e31d308-fa7d-46f7-9a84-961b8ee8d7d6.png)

客户端分析:
![firefox_ngKHO6fZ51](https://user-images.githubusercontent.com/99880210/227730278-52c42713-f24a-492f-8017-c4621325e7c6.png)

网站统计:
![firefox_jGJhsfJZcD](https://user-images.githubusercontent.com/99880210/227730294-29a0b320-0db2-4747-92e8-0795310d634f.png)

请求 URI 统计:
![firefox_AALrZdABCV](https://user-images.githubusercontent.com/99880210/227730312-7af77a1a-496d-4ceb-9c4e-83e2b6b22e86.png)

错误日志:
![firefox_zeoxY0aGo1](https://user-images.githubusercontent.com/99880210/227730324-4233dd98-e56b-460b-8918-23aefe8f7b45.png)

网站日志:
![firefox_GYhOcHB2V2](https://user-images.githubusercontent.com/99880210/227730337-b68eb852-6929-4376-a180-8083e725d0f6.png)

全局设置:
![firefox_Py47fdpwru](https://user-images.githubusercontent.com/99880210/227730354-2bdc5341-f08b-4963-ace7-026be91d6533.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会考虑增加网站统计功能。

**Comment by DT27** [comment]
有没有其他项目能实现类似功能？搜了一圈没找到。

**Comment by wanghe-fit2cloud** [comment]
> 有没有其他项目能实现类似功能？搜了一圈没找到。

进入应用商店列表，搜索并安装 Umami。

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
