### ISSUE TITLE
[BUG]左侧菜单栏变白

### ISSUE THREAD

**Issue by zephyrcicd** [1Panel-dev/1Panel#4081]
### 联系方式

klaus.cicd@gmail.com

### 1Panel 版本

v1.10.0-lts

### 问题描述

进入控制面板大概3s后，左侧菜单栏变成纯白色，刷新或强制删除缓存无效，退出重新登陆后恢复。
出现时机：导入远程MySQL数据库后

### 重现步骤

刷新页面

### 附加信息

<img width="229" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/81892709/a5e1bed2-77d5-40f3-bff2-0f7d40945fa3">

**Comment by wanghe-fit2cloud** [comment]
尝试一下更换浏览器或者清理浏览器缓存。
> 本地未能复现上述问题，先关闭该 issue 了。
如果你环境稳定复现，可以进入微信群添加 `王贺` 好友，我远程看一下你环境。
