### ISSUE TITLE
[FEATURE] 终端或者日志控制台打印二维码排版会出现问题！怎么解决这个问题！

### ISSUE THREAD

**Issue by XM2510136957** [1Panel-dev/1Panel#4085]
### 1Panel 版本

v1.10.0-lts

### 请描述您的需求或者改进建议

终端或者日志控制台打印二维码排版会出现问题！怎么解决这个问题！

### 请描述你建议的实现方案

终端或者日志控制台打印二维码排版会出现问题！怎么解决这个问题！

**Comment by wanghe-fit2cloud** [comment]
发一下具体问题。

刚在本地环境测试结果，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/c1e02301-532c-4334-ab01-9b2911f32a49)

**Comment by XM2510136957** [comment]
排版行列可以自己控制就好了

**Comment by wanghe-fit2cloud** [comment]
> 排版行列可以自己控制就好了

我们需要调研一下内嵌的编辑器是否支持。
> 先关闭该 issue 了，后续如果调研结果我们再继续讨论。
