### ISSUE TITLE
[BUG] Node.js运行环境运行项目后仍然显示构建中/已停止

### ISSUE THREAD

**Issue by shuTwT** [1Panel-dev/1Panel#4094]
### 1Panel 版本

v1.10.1-lts

### 问题描述

Node.js运行环境运行项目后仍然显示构建中/已停止
![屏幕截图 2024-03-06 200019](https://github.com/1Panel-dev/1Panel/assets/95295076/de0ceeda-1ff5-4432-9e22-5e46b0733c81)
![屏幕截图 2024-03-06 200032](https://github.com/1Panel-dev/1Panel/assets/95295076/c9a8c104-0690-41be-8967-5369a742f22d)
node项目已经运行，但运行环境处状态为构建中/已停止,容器处状态为已启动
![image](https://github.com/1Panel-dev/1Panel/assets/95295076/4d3a83cc-fa8e-4b82-b423-9d00006dc42d)

### 重现步骤

运行koa + ts + prisma 项目

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本增加运行环境同步功能。

**Comment by wanghe-fit2cloud** [comment]
v1.10.2-lts 版本已发布。
