### ISSUE TITLE
[BUG]切换英文后切换会中文，容器列表页面不能正确显示

### ISSUE THREAD

**Issue by zzreador** [1Panel-dev/1Panel#4095]
### 1Panel 版本

v1.10.0-lts

### 问题描述

不小心切换成英文之后，再切会中文，容器列表不能显示。看上去表的选择列都变成英文了。
![Snipaste_2024-03-06_22-01-36](https://github.com/1Panel-dev/1Panel/assets/39107274/ad98ea6a-4a8d-4436-9fe3-af86857932ac)

### 重现步骤

1.面板选项的系统语言选择为 English。
2.面板选项的系统语言选择为 中文（简体）
3.打开容器列表页面

### 期待的正确结果

容器列表正确显示

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。

**Comment by ssongliu** [comment]
可以通过删除 FU-T-contanerColumn 缓存暂时解决
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/b4476f2b-dffc-4128-9863-ba2dafaa0c2d)

**Comment by wanghe-fit2cloud** [comment]
v1.10.2-lts 版本已发布。
