### ISSUE TITLE
[QUESTION]计划任务功能中，任务列表的“备份账号”列是什么含义

### ISSUE THREAD

**Issue by Zeen-x** [1Panel-dev/1Panel#4096]
### 请描述您的问题

![image](https://github.com/1Panel-dev/1Panel/assets/49156890/89c9c9e0-3296-4ac7-a5c3-b3692e7541b1)
如图，“备份账号”列出现了“服务器磁盘”，具体指什么，这里任务类型为“shell脚本”

**Comment by wanghe-fit2cloud** [comment]
备份数据库、应用、网站等类型的计划任务会将备份文件上传到指定的 `备份账号`，但 `Shell 脚本` 类型计划任务是不需要定义该字段的。
> 我们会在后续版本优化计划任务列表显示。

**Comment by wanghe-fit2cloud** [comment]
v1.10.2-lts 版本已发布。
