### ISSUE TITLE
[FEATURE]希望 计划任务 功能的 计划报告 部分支持 ANSI 转义序列

### ISSUE THREAD

**Issue by Zeen-x** [1Panel-dev/1Panel#4097]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/49156890/3ebd3e6e-c205-4e16-a663-ab23898230e9)
当前效果
![image](https://github.com/1Panel-dev/1Panel/assets/49156890/3a2998b4-3eb9-4734-aa5a-c897bfe5f068)
期望效果

当前大部分软件和编程语言都支持ANSI转义序列格式的日志输入，如根据不同日志等级显示不同颜色、使用不同颜色区分时间戳和内容，当前显示效果并未对其正确解析

**Comment by Zeen-x** [comment]
补充
![当前效果](https://github.com/1Panel-dev/1Panel/assets/49156890/5793fb0e-3516-4d76-8a2d-a43df86ca1b8)
当前效果
![期望效果](https://github.com/1Panel-dev/1Panel/assets/49156890/9b5a123e-8eaa-48de-b41b-e23d8818dc8e)
期望效果


同时，当前在程序运行中查看日志时，手动滚动到顶部查看日志时，如果有新日志打印，会自动滚动到底部，影响查看日志

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先调研一下具体实现方案。

**Comment by wanghe-fit2cloud** [comment]
v1.10.2-lts 版本已发布。
