### ISSUE TITLE
[QUESTION]请教，设置sftp账号的“备份目录”是什么？怎么设置?

### ISSUE THREAD

**Issue by orochimaksim77002** [1Panel-dev/1Panel#4098]
### 请描述您的问题

![image](https://github.com/1Panel-dev/1Panel/assets/154217524/8f1deb95-8f46-4977-ba12-bde08d83d10a)
请问“面板设置”里面设置sftp账号时，要求的这个备份目录是什么？我怎么设置都不对。

**Comment by zhangyz189** [comment]
你输入地址“85.208.104.43”机器上的某个目录即可

**Comment by ssongliu** [comment]
必须先保证 地址、端口、用户名、密码能正常 ssh 到 “85.208.104.43” 这台机器。

目录并没有特定的要求
