### ISSUE TITLE
希望能在1panel的应用商店里增加blossom应用

### ISSUE THREAD

**Issue by Daibo-Baby** [1Panel-dev/1Panel#4099]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

希望能在1panel的应用商店里增加blossom应用：
https://www.wangyunf.com/blossom-doc/index

### 请描述你建议的实现方案

Blossom是一个云端双链笔记，感觉UI很好看，具体网址如下：
https://www.wangyunf.com/blossom-doc/index
希望能在应用商店里面增加该应用

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前该项目尚未达到上架应用商店的要求。因此，暂时无法接受这个 pull request。
再次感谢您对我们项目的关注和支持。
![image](https://github.com/1Panel-dev/appstore/assets/46734380/5a04a7b1-0a31-46a1-b4a2-c0a93d5d3663)

该项目官方提供了详细的安装文档，也包括容器化方案，可以参考：
https://github.com/blossom-editor/blossom/blob/dev/docker/compose/blossom-mysql8.yaml
> 通过 `容器` - `编排` 来维护项目
