### ISSUE TITLE
问一个特别小白的问题,终端的命令行文字怎么调整大小啊? [QUESTION]

### ISSUE THREAD

**Issue by Mask-Vip** [1Panel-dev/1Panel#4100]
### 请描述您的问题

我用的终端感觉文字有些小,咋调整大小呢?实在是官方文档里也没找到呢.麻烦了.

**Comment by RealHeart** [comment]
`Ctrl` + `鼠标滚轮`

**Comment by zhangyz189** [comment]
源码里面有写
“Support for Ctrl+MouseWheel to scaling fonts”

**Comment by Mask-Vip** [comment]
> `Ctrl` + `鼠标滚轮`

谢谢，麻烦了。

**Comment by Mask-Vip** [comment]
> 源码里面有写 “Support for Ctrl+MouseWheel to scaling fonts”

谢谢呢，我就一个面板战士实在是不会看源码。麻烦了。
