### ISSUE TITLE
[FEATURE] 计划任务执行shell脚本，增加用户模式

### ISSUE THREAD

**Issue by wang-qa** [1Panel-dev/1Panel#4103]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

计划任务》》shell类型
希望增加用户模式，当前是root模式

使用root用户执行计划时，会有异常，需要使用普通用户模式执行

**Comment by wanghe-fit2cloud** [comment]
可以使用这种方式来实现上述需求：

```shell
su ubuntu -c '
echo "user: " `whoami`
'
```
