### ISSUE TITLE
[BUG] 应用数据有unix套接字文件时创建快照失败

### ISSUE THREAD

**Issue by Ausli** [1Panel-dev/1Panel#4104]
### 联系方式

a532089051@outlook.com

### 1Panel 版本

v1.10.1-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/70201547/4a8d3393-e48f-485d-bdd1-aa3123174e00)

### 重现步骤

安装qBittorrent docker镜像并启动，保存快照，错误重现。

### 期待的正确结果

忽略unix套接字保存快照

### 附加信息

Refs https://github.com/1Panel-dev/1Panel/issues/2702
Refs https://github.com/1Panel-dev/1Panel/issues/2706

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持用户自定义排除规则。

相关问题的讨论，汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4076
