### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Maybe404** [1Panel-dev/1Panel#4105]
### 联系方式

tomorrow0047@gmail.com

### 1Panel 版本

v1.10.1

### 问题描述

面板应用商店直接安装的 neginx proxy manager 可以打开管理面板但是添加的反代无法生效，重装面板与系统也无法解决

### 重现步骤

，

### 期待的正确结果

，

### 相关日志输出

```shell
，
```

### 附加信息

，

**Comment by wanghe-fit2cloud** [comment]
1Panel 是容器化安装的应用，添加反代网站要注意后端地址不要使用 `127.0.0.1` 和 `localhost` 等（要确保容器内部能正常访问到后端服务）。

> 应用安装成功之后的使用问题，可以到相关应用官方找一下教程。
