### ISSUE TITLE
[FEATURE]typecho 应用增加 php-8.2 版本

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4106]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

typecho 应用增加 php-8.2 版本

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持。

**Comment by wanghe-fit2cloud** [comment]
已增加 1.2.1-php8.0 正式版本。
