### ISSUE TITLE
[BUG]watchtower 自定义命令安转出错

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4107]
### 1Panel 版本

v1.10.1-lts

### 问题描述

watchtower自定义命令安转出错，
自定义命令为
`--cleanup -s "0 0 4 * * *"`
错误日志为
failed to read /opt/1panel/apps/watchtower/watchtower/.env: line 1: unexpected character "*" in variable name "0 0 4 * * *\"\""

### 重现步骤

应用商店安装 watchtower，自定义命令。

**Comment by wanghe-fit2cloud** [comment]
需要将自定义命令中的双引号 `""` 修改为单引号 `''`
