### ISSUE TITLE
[FEATURE]文档不全

### ISSUE THREAD

**Issue by geekyouth** [1Panel-dev/1Panel#411]
### 1Panel 版本

在线安装

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/12899262/227750695-f5c05638-afa2-4e5d-b31d-6368e58dbfa8.png)

以 centos 为例安装实测，安装环境需要满如如下：
1、sudo 命令；
2、service 命令；

### 附加信息

![image](https://user-images.githubusercontent.com/12899262/227750770-ec204b2a-7c93-4e05-ac9c-cf4e6f296ae8.png)

![image](https://user-images.githubusercontent.com/12899262/227750768-2b8198e3-9bfd-4205-9f91-517f641e54f5.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
最新版本的安装脚本中已经取消了 sudo，service 等依赖命令。
