### ISSUE TITLE
[BUG]存在gitea时，安装umami会出现安装失败问题

### ISSUE THREAD

**Issue by youdiandongxi-com** [1Panel-dev/1Panel#4110]
### 1Panel 版本

v1.10.1-lts

### 问题描述

机器上已经安装了gitea，之后数次执行安装umami都是失败。

![屏幕截图 2024-03-07 211211](https://github.com/1Panel-dev/1Panel/assets/159420829/1db95216-69da-467b-b057-4f6fdef1e2dc)

经过排查似乎是两者都使用到了3000端口导致的。

![111](https://github.com/1Panel-dev/1Panel/assets/159420829/b602be4b-9e85-458c-be39-d67e859b0d11)

### 解决办法

当我进行以下操作后，重建umami成功。

1. 修改umami的docker-compose.yaml中的3000端口

```
# 调整前
- ${HOST_IP}:${PANEL_APP_PORT_HTTP}:3000

# 调整后
- ${HOST_IP}:${PANEL_APP_PORT_HTTP}:3001
```

2. 重启docker服务
3. 再次重建umami应用

### 重现步骤

1、先在应用市场安装**gitea**
2、再在应用市场安装**umami**，会一直处于创建中，然后失败。

### 期待的正确结果

两者可以共存，或者针对存在重复端口占用的应用，进行调整或者安装前提示？

**Comment by Anyexyz** [comment]
3000是容器内部端口，怎么会冲突🤣

**Comment by wanghe-fit2cloud** [comment]
应该是 Umami 应用镜像未拉取成功导致的创建失败。
> Umami 镜像在 github 仓库，可能是网络原因导致。
可以进入 `容器` - `配置` 页面手动添加镜像加速
