### ISSUE TITLE
[BUG] MongoDB 安装失败

### ISSUE THREAD

**Issue by liesauer** [1Panel-dev/1Panel#4113]
### 1Panel 版本

v1.10.1-lts

### 问题描述

显示容器不存在
![image](https://github.com/1Panel-dev/1Panel/assets/8676741/523545f4-7db8-45d5-a6b3-6c4b330aba6c)

### 重现步骤

1. 应用商店直接安装，全默认配置

### 相关日志输出

```shell
第一次安装时只有一行日志

stat /opt/1panel/apps/mongodb/mongodb/docker-compose.yml: no such file or directory

后续重建等操作，就完全空日志
```

### 附加信息

环境：win10 + Docker Desktop + wsl2

**Comment by wanghe-fit2cloud** [comment]
参考论坛中这篇文章 https://bbs.fit2cloud.com/t/topic/412

**Comment by liesauer** [comment]
> 参考论坛中这篇文章 https://bbs.fit2cloud.com/t/topic/412

参考了文中的方法，将docker for windows卸载了，在wsl2中安装docker，现在反而什么都装不上了，mysql、redis都失败了

**Comment by liesauer** [comment]
```
➜  ~ docker -v
Docker version 24.0.2, build cb74dfc
➜  ~ docker-compose -v
Docker Compose version v2.24.7
```
