### ISSUE TITLE
[FEATURE] ]typecho 应用增加正式版版本

### ISSUE THREAD

**Issue by YaKun9** [1Panel-dev/1Panel#4114]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

目前安装的是dev的版本，请求支持正式版，正式版相对于dev版本更加稳定。dev版本很多主题更新不及时，无法使用

### 请描述你建议的实现方案

目前安装的是dev的版本，请求支持正式版，正式版相对于dev版本更加稳定。dev版本很多主题更新不及时，无法使用

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本推送 typecho 最新的稳定版本（v1.2.1）

**Comment by wanghe-fit2cloud** [comment]
已经支持 v1.2.1-php8.0 正式版本。
> 进入 `应用商店` 页面，手动点击右上角的 `更新应用列表` 按钮获取最新版本即可。
