### ISSUE TITLE
[FEATURE] 能否支持迁移功能，对不同服务器的1pannel进行迁移

### ISSUE THREAD

**Issue by somnifex** [1Panel-dev/1Panel#4123]
### 1Panel 版本

latest

### 请描述您的需求或者改进建议

现有的快照、恢复的方式会全部镜像迁移，但是不够灵活，能否做到增量、覆盖、自定义迁移等形式

**Comment by wanghe-fit2cloud** [comment]
1Panel 快照会迁移 `已安装应用`、`运行环境` 和 `容器编排` 涉及到的容器镜像。
> 自己通过命令等方式创建的容器不会备份。

如果要实现增量迁移，可以优先考虑 1Panel 提供的 `网站`、`应用` 和 `数据库` 备份恢复功能。
快照暂不考虑自定义、增量等形式的备份。
