### ISSUE TITLE
[BUG] v1.10.1-lts 版本 面板web页面滚动错误

### ISSUE THREAD

**Issue by mwoldlee** [1Panel-dev/1Panel#4124]
### 联系方式

2953523271@qq.com

### 1Panel 版本

v1.10.1-lts

### 问题描述

![Snipaste_2024-03-08_13-46-23](https://github.com/1Panel-dev/1Panel/assets/44468855/d45f453d-fa9d-4a88-bcd9-69a101a044b9)
鼠标在红框位置（顶部就向上滚动、底部向下） 即可出现白框 此时页面的按钮已经错位如下图
![image](https://github.com/1Panel-dev/1Panel/assets/44468855/0c721857-9734-4581-b86e-480eae74cab0)
鼠标位置和hover样式错位

### 重现步骤

重现步骤见问题描述

**Comment by ssongliu** [comment]
感谢反馈，请问用的是什么浏览器，有尝试过无痕模式吗？
可以简单录个屏看一下。

**Comment by mwoldlee** [comment]
> 感谢反馈，请问用的是什么浏览器，有尝试过无痕模式吗？ 可以简单录个屏看一下。

你好 edge 浏览器122.0.2365.63 目前无法在无痕模式复现
录屏如下
![PixPin_2024-03-08_14-20-46](https://github.com/1Panel-dev/1Panel/assets/44468855/54ae5bbe-369d-45ef-9663-2902b8bfb9ad)

**Comment by ssongliu** [comment]
建议使用谷歌或者火狐浏览器，暂时没有对 edge 进行兼容性测试
