### ISSUE TITLE
[FEATURE]关于一些安全需求

### ISSUE THREAD

**Issue by Newzealcoin** [1Panel-dev/1Panel#4127]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

能不能在面板里添加禁止22端口登陆的功能，或是对22面板登陆次数的检测和限制，以及1Panel历史登陆IP和次数检测（如果一个检测到有人尝试多次登陆能不能通过阿里的云短信进行通知？或者配置邮件服务器进行通知），暂时想到就这么多，有机会在BB。

**Comment by zhangyz189** [comment]
主机=>SSH管理=>SSH 关闭即可
