### ISSUE TITLE
[BUG]Supervisor 进程守护页面刷新问题

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4129]
### 1Panel 版本

v1.10.1-lts

### 问题描述

通过 `工具箱` - `进程守护` 页面添加了多个需要守护的进程后，所有的进程都不见了，但任务是存在的。
`/opt/1panel/tools/supervisord/supervisor.d` 的子进程配置文件下查看所有的配置文件都存在。

![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/a39d8049-e320-43a4-b180-3509c97ec77a)

### 重现步骤

创建多个守护进程之后手动刷新页面。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈 。
列表数据消失应该是接口请求时间较长，页面上也没有 loading 效果导致的。
> 我们会在后续版本中增加 loading 效果，优化上述体验。

**Comment by wanghe-fit2cloud** [comment]
v1.10.2-lts 版本已发布。
