### ISSUE TITLE
[FEATURE]无法修改默认的WEBUI端口

### ISSUE THREAD

**Issue by geekyouth** [1Panel-dev/1Panel#413]
### 1Panel 版本

1panel version: v1.0.3  | appstore version: v0.0.89

### 请描述您的需求或者改进建议

无法修改默认的webui 端口号，因为安全原因，服务器只开放某些特定端口，该项目的端口号默认为 16143 无法在部署时提前修改，所以只能间接使用 nginx 反向代理

```shell
sudo yum install epel-release
sudo yum install nginx
```

vim "/etc/nginx/nginx.conf"
```conf
    server {
        listen       20000;
   
        include /etc/nginx/default.d/*.conf;

        location / {
            proxy_pass http://127.0.0.1:16143;
        }
    }
```

```
service nginx start
```

**Comment by wanghe-fit2cloud** [comment]
1、端口是在 1Panel 初始化的时候随机生成的（确保所有用户的初始化端口不一致）
2、后续我们会支持用户在初始化 1Panel 时自定义端口。

**Comment by wanghe-fit2cloud** [comment]
v1.0.4 版本已支持用户在初始化 1Panel 时自定义端口。
