### ISSUE TITLE
[BUG]特殊符号不包含“=”

### ISSUE THREAD

**Issue by railzen** [1Panel-dev/1Panel#4132]
### 1Panel 版本

V1.10.0

### 问题描述

设置复杂密码时，“=”没有被作为特殊符号，只有关闭密码复杂度验证才可以设置含有“=”的密码

### 重现步骤

一键安装脚本安装时，输入密码，无法使用带有“=”的密码

### 期待的正确结果

期望密码校验把“=“也识别为特殊符号

**Comment by wanghe-fit2cloud** [comment]
1、首次安装系统时，先按照提示信息成功设置好密码后，进入控制台面板设置页面修改密码
2、通过 `1pctl update password` 重置密码
