### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 1487879421888** [1Panel-dev/1Panel#4133]
### 联系方式

1

### 1Panel 版本

1

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/47622641/e232f1e8-2b2c-43ff-90b5-9075f418dc2c) 还有怎么改掉端口呢
这里一直显示安装中。

### 重现步骤

1

### 期待的正确结果

1

### 相关日志输出

```shell
41
```

**Comment by wanghe-fit2cloud** [comment]
1、需要在安装应用前指定端口。
2、安装中是因为应用镜像下载超时，可以手动配置镜像加速。
