### ISSUE TITLE
[FEATURE]关于快照与用户数据问题

### ISSUE THREAD

**Issue by meng-plus** [1Panel-dev/1Panel#4135]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

建议增加一个数据保存地址全局和指定切换，在使用快照时发现，app中所有数据都将被打包 但是 
![image](https://github.com/1Panel-dev/1Panel/assets/37764731/e9fdf0ba-4c69-48d0-a728-91b50f3fc82a)

### 请描述你建议的实现方案

大量的用户数据 不应该被打包进去 ，虽然可以手动指定地址，我感觉过于繁琐，希望支持一个变量去进行全局的配置，比如可以指定用户数据都存档在 新增的硬盘路径下

**Comment by wanghe-fit2cloud** [comment]
后续版本会支持设置排除规则。

**Comment by wanghe-fit2cloud** [comment]
https://github.com/1Panel-dev/1Panel/issues/4076

**Comment by wanghe-fit2cloud** [comment]
v1.10.2-lts 版本已发布。
