### ISSUE TITLE
[FEATURE]日志能否加个全屏查看或下载功能，现在的半屏效率有点低

### ISSUE THREAD

**Issue by iwvw** [1Panel-dev/1Panel#4136]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

如题：
![image](https://github.com/1Panel-dev/1Panel/assets/81206855/2377c1c9-032c-4540-8d41-290b0e9a3cd3)

**Comment by zhengkunwang223** [comment]
是应用日志吗？

**Comment by iwvw** [comment]
> 是应用日志吗？

我才发现有些页面的不一样
是应用守护的日志：
![image](https://github.com/1Panel-dev/1Panel/assets/81206855/e9aac6de-1e16-49af-a5cb-0956e60b6ad5)

**Comment by zhengkunwang223** [comment]
> > 是应用日志吗？
> 
> 我才发现有些页面的不一样 是应用守护的日志： ![image](https://private-user-images.githubusercontent.com/81206855/311501770-e9aac6de-1e16-49af-a5cb-0956e60b6ad5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMjQ0NjIsIm5iZiI6MTcxMDEyNDE2MiwicGF0aCI6Ii84MTIwNjg1NS8zMTE1MDE3NzAtZTlhYWM2ZGUtMWUxNi00OWFmLWE1Y2ItMDk1NmU2MGI2YWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDAyMjkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMGQzYWRhOWMzMDFlMmVmNWZjZjg1NDQ2ODQ0MTc5ZGRlMmY4MTliNTcyZmE1ZDhiNjkxOTE1OWY2NjZjZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kay-iJpqVIIfraTWqmW3YxNNZnODTsVJcEAj6bCRVNA)

好的 后续版本我们优化一下

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
