### ISSUE TITLE
[BUG] docker容器内存使用计算不准确

### ISSUE THREAD

**Issue by realzolo** [1Panel-dev/1Panel#4138]
### 联系方式

zolo@onezol.com

### 1Panel 版本

v1.10.1-lts

### 问题描述

容器sftpgo显示资源占用18.76GiB，明显错误，在概览页面显示正常占用。

<img width="1920" alt="微信图片_20240309155218" src="https://github.com/1Panel-dev/1Panel/assets/63219216/afbceaaa-c3af-47bb-9775-e7e81e9b2e89">
<img width="1920" alt="微信图片_20240309155223" src="https://github.com/1Panel-dev/1Panel/assets/63219216/422b4dc0-1ff0-4d7f-84a5-44ebe5abcaf6">
<img width="1920" alt="微信图片_20240309155225" src="https://github.com/1Panel-dev/1Panel/assets/63219216/f2dba3d3-43e8-4aef-a129-3bf0ff5edccf">

### 重现步骤

重现：使用sftpgo传输大文件

**Comment by wanghe-fit2cloud** [comment]
可以进入 `主机` - `终端`，手动执行 `docker stats` 命令查看输出结果和 1Panel 页面显示是否一致。

**Comment by realzolo** [comment]
> 可以进入 `主机` - `终端`，手动执行 `docker stats` 命令查看输出结果和 1Panel 页面显示是否一致。

页面显示和docker stats输出结果不一致。
<img width="1920" alt="微信图片_20240310150334" src="https://github.com/1Panel-dev/1Panel/assets/63219216/ae8e458b-6554-4886-8fba-ef4bf4c08169">

**Comment by wanghe-fit2cloud** [comment]
> 页面显示和docker stats输出结果不一致。

好的，我们在本地环境也复现一下问题。

**Comment by ssongliu** [comment]
麻烦添加我好友，我看看这个问题
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/37ac9cca-18aa-4896-81f9-d1639b3c96ae)

**Comment by QYG2297248353** [comment]
我依旧遇见此问题 ，重启容器虽然会解决，但是这是一个Bug
@wanghe-fit2cloud 

![image](https://github.com/1Panel-dev/1Panel/assets/56836951/64313bad-e110-417e-a7ed-ae2a676e6b7e)
![image](https://github.com/1Panel-dev/1Panel/assets/56836951/9aa30605-17f9-456c-b674-0ea45498af86)

**Comment by QYG2297248353** [comment]
补充一点
容器>>更多>>监控
![image](https://github.com/1Panel-dev/1Panel/assets/56836951/bd6c8abc-3b46-4b3b-b96f-793e38937b67)

**Comment by ssongliu** [comment]
> 补充一点 容器>>更多>>监控 ![image](https://private-user-images.githubusercontent.com/56836951/320436535-bd6c8abc-3b46-4b3b-b96f-793e38937b67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzA3NzIsIm5iZiI6MTcxMjU3MDQ3MiwicGF0aCI6Ii81NjgzNjk1MS8zMjA0MzY1MzUtYmQ2YzhhYmMtM2I0Ni00YjNiLWI5NmYtNzkzZTM4OTM3YjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEwMDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZjExMWNhYmY2ZWUyMzk1MjliZWFjZTU4OTcxMmJkYjJmYTQ1NWQwYTNiNTc0ZjZhNjhjMTlmNjQwZWZkZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XTj6sxLIHLmCfK_w-4RY6dyDxqk7jtTSMHMxYHa8Qok)

可以扫码加一下好友，我看看

**Comment by moriecho** [comment]
2025年了，这个问题还是没得到解决。今天我也遇到了，用1panel装transmission下载，动不动就占比96.35%

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
It’s 2025 and this problem still has not been solved. I also encountered this today. When I installed transmission download on 1panel, the share was 96.35%.

**Comment by moriecho** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> It’s 2025 and this problem still has not been solved. I also encountered this today. When I installed transmission download on 1panel, the share was 96.35%.

经过我一段时间的研究，我猜测这并不是1panel的问题，而是transmission的问题。
以下是我的猜想：
transmission为了实现更低的物理内存占用，使用了硬盘作为虚拟内存，而这部分的虚拟内存也算在了docker界面的资源使用率中。导致主页看到的只是物理内存占用，而docker界面看到的是物理内存占用+虚拟内存
