### ISSUE TITLE
[FEATURE]增加一个内部api密钥功能，类似宝塔API密钥

### ISSUE THREAD

**Issue by 357341051** [1Panel-dev/1Panel#414]
### 1Panel 版本

v1.0.3

### 请描述您的需求或者改进建议

增加一个内部api密钥功能，类似宝塔API密钥

### 请描述你建议的实现方案

参考现有宝塔面板的API密钥功能，也需要ip白名单，开关，
![image](https://user-images.githubusercontent.com/118408640/227755591-134ab003-1033-4445-b40d-4f304405b2cd.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本支持。

**Comment by wanghe-fit2cloud** [comment]
v1.10.22 版本已发布。
