### ISSUE TITLE
建议应用新增immich

### ISSUE THREAD

**Issue by charlie-ch** [1Panel-dev/1Panel#4143]
### 1Panel 版本

1.93.3

### 请描述您的需求或者改进建议

建议新增应用mimich  25k星 一款非常好用的照片管理工具，https://github.com/immich-app/immich

### 请描述你建议的实现方案

新增app

**Comment by zhengkunwang223** [comment]
感谢建议 我们调研一下

**Comment by QYG2297248353** [comment]
你可以临时选择第三方应用商店
```
#!/bin/bash

# 定义脚本URL
script_url="https://github.com/QYG2297248353/appstore-1panel/releases/download/install/install.sh"

# 执行脚本
echo "Downloading and executing script from $script_url..."
bash <(curl -sL "$script_url")

# 输出执行结果
echo "Script execution completed."
```
[第三方仓库](https://github.com/QYG2297248353/appstore-1panel.git)

**Comment by wanghe-fit2cloud** [comment]
> 你可以临时选择第三方应用商店
> 
> ```
> #!/bin/bash
> 
> # 定义脚本URL
> script_url="https://github.com/QYG2297248353/appstore-1panel/releases/download/install/install.sh"
> 
> # 执行脚本
> echo "Downloading and executing script from $script_url..."
> bash <(curl -sL "$script_url")
> 
> # 输出执行结果
> echo "Script execution completed."
> ```
> 
> [第三方仓库](https://github.com/QYG2297248353/appstore-1panel.git)


感谢分享。
考虑到 Immich 应用维护的复杂性，我们暂时先不考虑将其上架到正式版本应用商店，望理解。
