### ISSUE TITLE
开源笔记应用Blossom

### ISSUE THREAD

**Issue by yggcwx** [1Panel-dev/1Panel#4144]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

此笔记开源免费，支持docker部署，支持markdown语法，可以多端同步、WEB应用。

### 请描述你建议的实现方案

在应用商店中添加此项目。

### 附加信息
https://github.com/blossom-editor/blossom

![Screenshot_20240310-125938_Browser](https://github.com/1Panel-dev/1Panel/assets/90705180/9a44dfa6-10b0-4b62-9ab2-fa9d5fd3d4e3)

**Comment by zhengkunwang223** [comment]
感谢建议 我们先调研一下

**Comment by wanghe-fit2cloud** [comment]
第三方仓库已支持，地址如下：
https://github.com/okxlin/appstore
