### ISSUE TITLE
部分应用图标无法正常显示[BUG]

### ISSUE THREAD

**Issue by eanznj** [1Panel-dev/1Panel#4148]
### 1Panel 版本

v1.10.1-lts

### 问题描述

使用一段时间后，部分应用图标无法显示。之前遇到过这个问题重装后恢复正常了，现在又出现这种情况了。
![微信截图_20240310222211](https://github.com/1Panel-dev/1Panel/assets/48092687/9e54bef7-dc49-400e-ba79-4159202a8f69)
![微信截图_20240310221021](https://github.com/1Panel-dev/1Panel/assets/48092687/3f9516d8-001d-4f2e-99ee-5b32a99567ed)

### 重现步骤

无

**Comment by wanghe-fit2cloud** [comment]
1Panel 应用商店安装包等资源统一存放在 `阿里 OSS`，是全球加速的 cdn，出现上述问题除非是 cdn 节点有问题了。

**Comment by eanznj** [comment]
应该不是CDN节点的问题，其它安装1Panel的都正常显示的。同一台服务器卸载重装后也能正常显示图标

**Comment by eanznj** [comment]
@wanghe-fit2cloud 应该不是CDN节点的问题，其它安装1Panel的都正常显示的。同一台服务器卸载重装后也能正常显示图标

**Comment by eanznj** [comment]
@wanghe-fit2cloud 
![111](https://github.com/1Panel-dev/1Panel/assets/48092687/7d77a9e0-7cb9-4bfd-8df5-8ae7a646925d)
之前那个应用图标无法正常显示是部署在本地的，现在有一个部署在阿里云的1Panel部分应用图标也无法显示。

**Comment by wanghe-fit2cloud** [comment]
好的，我们在本地环境先验证一下该问题。

**Comment by zhengkunwang223** [comment]
是什么设备和操作系统？

**Comment by eanznj** [comment]
> 是什么设备和操作系统？

你问的是我的电脑还是装1Panel的服务器

**Comment by zhengkunwang223** [comment]
> > 是什么设备和操作系统？
> 
> 你问的是我的电脑还是装1Panel的服务器

服务器 以前有 NAS 用户也碰到这个问题

**Comment by eanznj** [comment]
本地是ubuntu-22.04虚拟机，阿里云是centos-7.9.2009，都遇到这种情况了

**Comment by eanznj** [comment]
@zhengkunwang223 本地是ubuntu-22.04虚拟机，阿里云是centos-7.9.2009，都遇到这种情况了

**Comment by zhengkunwang223** [comment]
> @zhengkunwang223 本地是ubuntu-22.04虚拟机，阿里云是centos-7.9.2009，都遇到这种情况了

![image](https://github.com/1Panel-dev/1Panel/assets/31820853/b9222675-3120-4fa7-89ce-361c32a65843)
加一下我微信 我远程一下

**Comment by eanznj** [comment]
> > @zhengkunwang223 本地是ubuntu-22.04虚拟机，阿里云是centos-7.9.2009，都遇到这种情况了
> 
> ![image](https://private-user-images.githubusercontent.com/31820853/311611000-b9222675-3120-4fa7-89ce-361c32a65843.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDEyMzEsIm5iZiI6MTcxMDE0MDkzMSwicGF0aCI6Ii8zMTgyMDg1My8zMTE2MTEwMDAtYjkyMjI2NzUtMzEyMC00ZmE3LTg5Y2UtMzYxYzMyYTY1ODQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA3MDg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZDUzOTViZGRiMDI2MjEzYTQxMmJlZGFmMzAyYWI0ZjM3ZWExMDBjZTQ4YmE4NzhiZDQzNDFkNjI1Y2RiN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SuMFhrzEcjON_Svc-zamKlFLRkaEjCpk2MliSa1dJ3Q) 加一下我微信 我远程一下

家了，麻烦通过下

**Comment by wanghe-fit2cloud** [comment]
优化了应用同步逻辑，可以将 1Panel 升级至最新版本，然后确认一下是否还存在上述问题。
