### ISSUE TITLE
应用商店新增杀毒软件

### ISSUE THREAD

**Issue by liuyiwuqing** [1Panel-dev/1Panel#415]
### 1Panel 版本

v1.0.3

### 请描述您的需求或者改进建议

希望可以集成一些杀毒软件，或者可以实现对病毒文件的查杀

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本有计划支持。

**Comment by Mr-Ao-Dragon** [comment]
关于杀毒软件，建议在安装和使用的时候重点打上一个标语：
没有绝对安全的系统，所有安全措施都是在和入侵来源拖延时间

**Comment by wanghe-fit2cloud** [comment]
> 关于杀毒软件，建议在安装和使用的时候重点打上一个标语： 没有绝对安全的系统，所有安全措施都是在和入侵来源拖延时间

赞

**Comment by wanghe-fit2cloud** [comment]
@liuyiwuqing 
您那边有推荐的杀毒软件吗？

**Comment by liuyiwuqing** [comment]
> @liuyiwuqing 您那边有推荐的杀毒软件吗？

很抱歉，我也没有可推荐的

**Comment by ossplus** [comment]
https://hub.docker.com/r/mkodockx/docker-clamav/

**Comment by wanghe-fit2cloud** [comment]
> https://hub.docker.com/r/mkodockx/docker-clamav/

建议通过 `容器菜单` 的 `创建容器` 或 `创建编排` 功能来维护该应用。
