### ISSUE TITLE
[BUG]waf两次重定向造成URL path叠加到不存在页面

### ISSUE THREAD

**Issue by byhgj** [1Panel-dev/1Panel#4150]
### 联系方式

byhgj@163.com

### 1Panel 版本

v1.10.1-lts

### 问题描述

在部署zblog时，第一次需要302重定向到zb_install页面（./zb_install/index.php），疑似waf再次重定向页面，造成URL变成./zb_install/zb_install/index.php，这个页面不存在，报404。
这个情况之前在部署其他类似页面时也遇到过。

### 重现步骤

部署zblog，浏览页面，进入install时重现

### 期待的正确结果

正常部署

**Comment by wanghe-fit2cloud** [comment]
https://github.com/1Panel-dev/1Panel/discussions/4147
