### ISSUE TITLE
[FEATURE] 安全更新 OpenResty  版本的方法

### ISSUE THREAD

**Issue by NHZEX** [1Panel-dev/1Panel#4151]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

当前环境已经安装`openresty/openresty:1.21.4.3-0-focal`，官方仓库已经发布 [v1.25.3.1](https://github.com/openresty/openresty/tree/v1.25.3.1)。面板界面没有找到可直接更新的入口，请问如何安全升级？

**Comment by zhengkunwang223** [comment]
1.25.3.1 对现有逻辑有影响 我们需要适配一下

**Comment by wanghe-fit2cloud** [comment]
关于 OpenResty 支持 HTTP/3 需求的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/3641

目前，可以在安装应用时，手动修改 compose 文件中的镜像版本，如图：
> 升级操作还不支持
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/dea1e12e-af96-4fc6-9a16-bd9ce8c43adb)
