### ISSUE TITLE
[BUG]showdoc更新失败，更新前选择了备份，但好像并没有备份

### ISSUE THREAD

**Issue by yinyajiang** [1Panel-dev/1Panel#4153]
### 1Panel 版本

v1.10.1-lts

### 问题描述

在可升级页面，选择升级showdoc，并且选择备份。完成后发现更新失败，并且没有办法重新启动，备份也没有发现有。
<img width="534" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/32933356/3d30ba11-9f6b-4a66-ac0b-a16fcaa485f5">

### 重现步骤

无

**Comment by yinyajiang** [comment]
选择重建也会失败

**Comment by yinyajiang** [comment]
发现系统日志是成功的，但实际是失败
![image](https://github.com/1Panel-dev/1Panel/assets/32933356/2ea44898-75a2-4b35-94ff-a76449523f94)

**Comment by yinyajiang** [comment]
系统日志如下：
<img width="1207" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/32933356/363ed739-f0a8-4bfd-a3a6-565ccf3af856">

**Comment by wanghe-fit2cloud** [comment]
手动拉取一下应用最新镜像，pull 成功之后再来试一下重建应用操作
```shell
docker pull star7th/showdoc:v3.2.5
```

**Comment by yinyajiang** [comment]
> 手动拉取一下应用最新镜像，pull 成功之后再来试一下重建应用操作
> 
> ```shell
> docker pull star7th/showdoc:v3.2.5
> ```

拉取了，重建还是会失败

**Comment by wanghe-fit2cloud** [comment]
提供一下应用商店已安装应用截图和镜像列表截图（过滤 showdoc）

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/7c35bd04-786b-4a6e-818b-781c6a96b374)
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/ff1b7be9-ef53-4c1c-ae58-53c9a2190996)

**Comment by yinyajiang** [comment]
> 提供一下应用商店已安装应用截图和镜像列表截图（过滤 showdoc）

只能用手机截图了，确实没有发现3.2.5的镜像，我手动拉去过一次的。是否和服务器是arm的相关

**Comment by yinyajiang** [comment]
![Uploading IMG_20240311_182826.jpg…]()

**Comment by yinyajiang** [comment]
![IMG_20240311_182826](https://github.com/1Panel-dev/1Panel/assets/32933356/3f27f03d-ed6e-413f-94f1-e1482142c46f)
![IMG_20240311_182814](https://github.com/1Panel-dev/1Panel/assets/32933356/ec089e7c-33ac-4ba0-93e0-b700553bfb77)

**Comment by wanghe-fit2cloud** [comment]
showdoc 在安装页面，1Panel 提供了 3.2.5 和 arm 两个版本的镜像
而 3.2.5 不支持 arm 版本
所以，你的 1Panel 服务器架构如果是 arm，就只能选择 arm 版本。下图为 docker hub 截图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/d28510cd-772b-4921-9119-8e268662d519)

**Comment by yinyajiang** [comment]
> showdoc 在安装页面，1Panel 提供了 3.2.5 和 arm 两个版本的镜像 而 3.2.5 不支持 arm 版本 所以，你的 1Panel 服务器架构如果是 arm，就只能选择 arm 版本。下图为 docker hub 截图： ![image](https://private-user-images.githubusercontent.com/46734380/311670337-d28510cd-772b-4921-9119-8e268662d519.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTM0ODUsIm5iZiI6MTcxMDE1MzE4NSwicGF0aCI6Ii80NjczNDM4MC8zMTE2NzAzMzctZDI4NTEwY2QtNzcyYi00OTIxLTkxMTktOGUyNjg2NjJkNTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEwMzMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkN2QzNjU5NDZkNzhhOGIxNzZhN2QyZjU1NjVmODRiMGMyYTQ2ZWZiM2M3Y2ExMTQ5NDU5MjIwM2EzMmRmYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-S0u-c5ehqghxeVkUVuLuz-FnPg5j0-4lvWQTqL3kTk)

好的，那现在有没有办法恢复呢？并且在这种情况下建议就不要提示更新了，不然更新就挂了😭

**Comment by wanghe-fit2cloud** [comment]
> 好的，那现在有没有办法恢复呢？并且在这种情况下建议就不要提示更新了，不然更新就挂了😭

1、应用恢复列表中有备份数据吗？可以尝试手动恢复。
2、目前是安装 arm 版本后，在可升级页面提示了更新吗？
