### ISSUE TITLE
[BUG]制作快照文件过大空间不足导致失败问题

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#4155]
### 1Panel 版本

v1.10.1-lts

### 问题描述

使用快照功能创建失败：
![PixPin_2024-03-11_17-29-42](https://github.com/1Panel-dev/1Panel/assets/63288007/da124046-e495-4e7b-b430-8e4437876c6f)

错误提示：
```
file 1panel_v1.10.1-lts_amd64_20240311165007/1panel/1panel_backup.tar.gz: writing data: write /1panel/1panel/tmp/system/1panel_v1.10.1-lts_amd64_20240311165007.tar.gz: no space left on device
```

创建的快照文件达到42GB，而`\`根目录所挂载的空间默认50GB，可用33.7GB，从而导致快照创建失败。

---

这个问题其实之前提交过多次issue，根源还是初始安装1panel时默认安装在`\`所在目录，而该目录安装系统时默认分配50GB空间。而之前回复是暂不支持修改1panel安装路径。那么现在解决这个问题就很棘手，毕竟如果重装面板的话面板上的所有运行的数据全部需要迁移，代价比较大。

希望可以修复这个问题，我很好奇为什么制作快照文件的过程中要从目标文件所在路径把数据拷贝至1panel所在根目录下执行，直接在目标所在路径中执行不可以吗？

如果这个问题涉及底层实现的历史遗留不容易修复，还是希望可以提供一些解决方案的。比如可以提供面板的shell命令，允许自行编写脚本触发创建快照文件，后续的文件压缩之类工作可以通过shell脚本自行实现等

因为如果执行的文件都必须拷贝至面板所在路径执行，而在初始安装面板的过程中又没有足够的风险提示，那么对于后期使用过程中体验就很痛苦，毕竟根目录所挂载空间是有限的，而服务器中动辄几十GB的数据并不罕见。

真心希望可以解决这个问题，也希望1panel越来越好！

### 重现步骤

执行 `创建快照`

**Comment by wanghe-fit2cloud** [comment]
> 希望可以修复这个问题，我很好奇为什么制作快照文件的过程中要从目标文件所在路径把数据拷贝至1panel所在根目录下执行，直接在目标所在路径中执行不可以吗？

目标文件就是容器镜像 + 1Panel 安装目录，不存在 `直接在目标所在路径中执行不可以吗？`

> 而之前回复是暂不支持修改 1Panel 安装路径。

是的，当前版本不支持修改 1Panel 安装目录。
还是推荐你手动扩容根目录来解决上述问题。

> 比如可以提供面板的shell命令，允许自行编写脚本触发创建快照文件，后续的文件压缩之类工作可以通过shell脚本自行实现等

创建快照的操作是通过后端代码实现，不是单纯的 Shell 脚本。

> 而在初始安装面板的过程中又没有足够的风险提示，那么对于后期使用过程中体验就很痛苦。

制作出来的快照文件大，说明已安装应用数量多（我们在创建快照时，会备份全部已安装应用、运行环境的容器镜像）
我们也没有办法提供具体的预留空间要求（1Panel 自身大小只有 100MB）

**Comment by JAINKRE** [comment]
> 目标文件就是容器镜像 + 1Panel 安装目录，不存在 `直接在目标所在路径中执行不可以吗？`

好的，理解。

我们自行想办法解决吧，但还是希望在后续大版本更新的时候可以考虑这种场景。

**Comment by wanghe-fit2cloud** [comment]
> 还是希望在后续大版本更新的时候可以考虑这种场景。

收到， 后续版本持续优化。
