### ISSUE TITLE
[BUG]应用商店安装Halo失败

### ISSUE THREAD

**Issue by liuyiwuqing** [1Panel-dev/1Panel#416]
### 联系方式

1520431201@qq.com

### 1Panel 版本

使用应用商店安装Halo失败

### 问题描述

![image](https://user-images.githubusercontent.com/52553268/227766477-7d54c55a-1d67-4c64-8f92-91261ab2731a.png)
安装halo容器一直重启，实际测试halo2.3.2、2.2.0均显示以上报错，linux系统已重新安装，面板也重新安装过，均为成功，通过应用商店安装其他软件则正常，目前面板版本V1.0.3。当前服务器为：腾讯云轻量服务器，2核8g，操作系统：OpenCloud OS 8.6，系统镜像：OpenCloudOS8.6-Docker20

### 重现步骤

使用的是OpenCloud OS 8.6内置docker，可能是兼容问题

**Comment by wanghe-fit2cloud** [comment]
根据错误日志来看，可能是由于系统内存不足或进程数过多导致的。

**Comment by ruibaby** [comment]
Docker 版本不兼容，参见：https://github.com/halo-dev/halo/issues/2503

**Comment by liuyiwuqing** [comment]
> Docker 版本不兼容，参见：[halo-dev/halo#2503](https://github.com/halo-dev/halo/issues/2503)

好的，谢谢

**Comment by liuyiwuqing** [comment]
> 根据错误日志来看，可能是由于系统内存不足或进程数过多导致的。

感谢回复
