### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by isinvon** [1Panel-dev/1Panel#4163]
### 联系方式

2021469084@qq.com

### 1Panel 版本

v1.10.1-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/123001648/1eb03d6a-a2d0-4c33-83ae-82fd9683ff8c)
ip地址未正确显示

### 重现步骤

输入sudo 1pctl user-info的时候显示的url面板地址依旧是携带$LOCAL_IP
重启依旧.

### 期待的正确结果

因为我用的是局域网, 希望$LOCAL_IP能显示为正确的内网ip, 例如192.168.1.193

### 相关日志输出

```shell
键入sudo 1pctl user-info 时 journalctl -u 1panel -e 无日志输出
```

**Comment by wanghe-fit2cloud** [comment]
需要进入 `面板设置` 页面，手动添加 `服务器地址`，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/3ae744d9-aef3-4287-a2a1-3281f50fd099)
