### ISSUE TITLE
[BUG] 在计划任务中创建的自动备份数据库经常出错

### ISSUE THREAD

**Issue by ChishFoxcat** [1Panel-dev/1Panel#4164]
### 联系方式

Chish

### 1Panel 版本

v1.10.1-lts

### 问题描述

创建的备份数据库任务自动执行经常出错，手动执行则没问题

![image](https://github.com/1Panel-dev/1Panel/assets/76027184/5472736e-505f-4c57-bdb8-d808ca469c3a)

![image](https://github.com/1Panel-dev/1Panel/assets/76027184/e22b8105-5496-44a2-b863-b1d3ffef8c26)
> 成功的是手动执行的结果

其他类型自动执行偶尔会出现错误，待定

### 重现步骤

创建备份数据库计划，等待自动执行

### 期待的正确结果

成功备份，自动执行不会出现错误

### 相关日志输出

```shell
do request for file id failed, err: InvalidAuthenticationToken - IDX14100: JWT is not well formed, there are no dots (.). The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'. (2024-02-22T23:00:01)


do request for file id failed, err: InvalidAuthenticationToken - IDX14100: JWT is not well formed, there are no dots (.). The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'. (2024-03-07T23:00:01)

do request for file id failed, err: InvalidAuthenticationToken - IDX14100: JWT is not well formed, there are no dots (.). The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'. (2024-03-10T23:00:01)
```

### 附加信息

这是我创建的几个计划，参考是否为冲突

![image](https://github.com/1Panel-dev/1Panel/assets/76027184/025565fa-af72-4550-8d3d-23ef4b34aca8)

还有几个错误日志是：
```
do request for file id failed, err: unauthenticated - Must be authenticated to use '/drive' syntax (2024-02-29T23:00:01)
```
在onedrive-api-docs的提问中看到 https://github.com/OneDrive/onedrive-api-docs/issues/845

我可能会在后续更改为 webdav (alist) 进行备份

**Comment by ssongliu** [comment]
感谢反馈，请问一下这边数据库的备份文件大概是多大，超过 50M 了吗？

**Comment by ChishFoxcat** [comment]
> 感谢反馈，请问一下这边数据库的备份文件大概是多大，超过 50M 了吗？

![image](https://github.com/1Panel-dev/1Panel/assets/76027184/e76190f4-3ddb-4edf-b5ad-e004ee895428)
查看了一下，所有加起来不超过 5M

**Comment by ssongliu** [comment]
> > 感谢反馈，请问一下这边数据库的备份文件大概是多大，超过 50M 了吗？
> 
> ![image](https://private-user-images.githubusercontent.com/76027184/311980592-e76190f4-3ddb-4edf-b5ad-e004ee895428.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjkwNzgsIm5iZiI6MTcxMDIyODc3OCwicGF0aCI6Ii83NjAyNzE4NC8zMTE5ODA1OTItZTc2MTkwZjQtM2RkYi00ZWRmLWI1YWQtZTAwNGVlODk1NDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA3MzI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMzAzYzc1MTgyMjg2NmVkNGI0N2M2MzVmZGRjYjhjOTUyZDg5NjE0OWZkMjE3MDE1N2YwM2YwMWMzMDM1MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gV8sfi6X7vnuAhouFoniuwFg_xFIVj_x8waUVSnlwG0) 查看了一下，所有加起来不超过 5M

再麻烦截图看一下备份账号界面，因为 onedrive token 是每十分钟刷新一次，看起来是和计划任务冲突了

**Comment by ChishFoxcat** [comment]
> > > 感谢反馈，请问一下这边数据库的备份文件大概是多大，超过 50M 了吗？
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/76027184/311980592-e76190f4-3ddb-4edf-b5ad-e004ee895428.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjkwNzgsIm5iZiI6MTcxMDIyODc3OCwicGF0aCI6Ii83NjAyNzE4NC8zMTE5ODA1OTItZTc2MTkwZjQtM2RkYi00ZWRmLWI1YWQtZTAwNGVlODk1NDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDA3MzI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMzAzYzc1MTgyMjg2NmVkNGI0N2M2MzVmZGRjYjhjOTUyZDg5NjE0OWZkMjE3MDE1N2YwM2YwMWMzMDM1MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gV8sfi6X7vnuAhouFoniuwFg_xFIVj_x8waUVSnlwG0) 查看了一下，所有加起来不超过 5M
> 
> 再麻烦截图看一下备份账号界面，因为 onedrive token 是每十分钟刷新一次，看起来是和计划任务冲突了

![image](https://github.com/1Panel-dev/1Panel/assets/76027184/d1863778-4e2b-4caa-a59b-eb8a6cee5c2b)

**Comment by ssongliu** [comment]
可以修改一下计划任务的执行时间，让他错开 onedrive 的刷新时间

**Comment by ChishFoxcat** [comment]
> 可以修改一下计划任务的执行时间，让他错开 onedrive 的刷新时间

错开整时吗，我尝试一下，后续我会来继续反馈

**Comment by ssongliu** [comment]
> > 可以修改一下计划任务的执行时间，让他错开 onedrive 的刷新时间
> 
> 错开整时吗，我尝试一下，后续我会来继续反馈

对的，暂时先关闭了，后续有问题可以再打开
