### ISSUE TITLE
[BUG] PostgreSQL 数据库 从服务器获取不会删除已删除数据库

### ISSUE THREAD

**Issue by QYG2297248353** [1Panel-dev/1Panel#4165]
### 联系方式

qyg2297248353@163.com

### 1Panel 版本

v1.10.1-lts

### 问题描述

数据库 >> PostgreSQL >> 从服务器获取
如果数据库已从服务器手动删除，点击获取后列表并不会删除已删除数据库。
1. 如果可以要么换成从服务器同步，删除已删除数据库。
2. 增加标签，已删除数据库显示标签注明已删除

### 重现步骤

数据库 >> PostgreSQL >> 从服务器获取

**Comment by wanghe-fit2cloud** [comment]
> 增加标签，已删除数据库显示标签注明已删除

感谢反馈，后续版本会考虑增加 `已删除` 标签。

**Comment by wanghe-fit2cloud** [comment]
v1.10.2-lts 版本已发布。
