### ISSUE TITLE
任意文件读取漏洞

### ISSUE THREAD

**Issue by cmd-shell** [1Panel-dev/1Panel#4170]
### 联系方式

3156936021@qq.com

### 1Panel 版本

v1.10.1-lts以及之前版本

### 问题描述

在后台文件查看处可以查看任意文件，包括敏感文件

### 重现步骤

在后台点击文件，抓包，将路径修改为想要查看文件的路径即可
![image](https://github.com/1Panel-dev/1Panel/assets/103316762/bc930475-7347-4b6d-90f9-fbad3827d809)

**Comment by wanghe-fit2cloud** [comment]
1Panel 提供文件管理功能，用户登录后可以查看 Linux 服务器上的所有文件，包括文件夹、文件、图片、视频等。
用户还可以对文件进行上传、下载、删除、重命名等操作。
