### ISSUE TITLE
[BUG] openresty 保存反向代理配置时主配置文件 map 部分内容丢失

### ISSUE THREAD

**Issue by LightningRS** [1Panel-dev/1Panel#4171]
### 1Panel 版本

1.10.1-lts

### 问题描述

在 1Panel 中保存 openresty 反向代理配置时，若网站的主配置文件中有 map 块，其中以正则表达式开头的配置行会丢失。

### 重现步骤

1. 创建一个反向代理类型的网站
2. 编辑网站的配置文件，在 `server {` 块之前加入 map 块，点击【保存并重载】
  ```conf
  map $http_scheme $real_scheme {
      default $scheme;
      "~(?P<up_scheme>.*)" $up_scheme;
  }
  map $upstream_http_location $new_location {
      "~^(\S+)://([^/]+)/(?P<u>.*)$" $real_scheme://$http_host/$u;
  }
  server {
  // ...
  ```
  ![image](https://github.com/1Panel-dev/1Panel/assets/54468001/72992984-82d0-44d1-8148-69cc804cf36d)

3. 切换到【反向代理】，编辑反向代理 `root` 的配置源文件，修改任意内容（如添加 `# test` 注释）后，点击【确认】
  ![image](https://github.com/1Panel-dev/1Panel/assets/54468001/9910eb20-1574-4e59-a8ef-9246cda3923c)

4. 再次点击【配置文件】编辑网站主配置文件，可以看到两个 map 块中的正则表达式开头行丢失。
  ![image](https://github.com/1Panel-dev/1Panel/assets/54468001/a69bb412-bbde-4dbd-8e94-0fae897eb970)

### 期待的正确结果

保存反向代理配置时，网站主配置文件中的 map 块不应受到影响

**Comment by zhengkunwang223** [comment]
我们先复现一下

**Comment by zhengkunwang223** [comment]
已复现 后续版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.10.2-lts 版本已发布。
