### ISSUE TITLE
[FEATURE]设置容器静态ip

### ISSUE THREAD

**Issue by cli-r** [1Panel-dev/1Panel#4172]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

因为容器的ip默认未设置静态ip，所以每次重启都会自动变化，建议添加静态ip设置，方便一些如反向代理，或mysql权限设置等功能的使用。

### 请描述你建议的实现方案

修改原：
networks:
            - 1panel-network
为：
networks:
            1panel-network:
                ipv4_address: 172.18.XX.XX
不一定是最佳方法，希望未来能支持。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持自定义容器 IP 功能。

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/3663
