### ISSUE TITLE
[FEATURE] 建议增加API接口

### ISSUE THREAD

**Issue by BuTingBa** [1Panel-dev/1Panel#4174]
### 1Panel 版本

v1.10.1-alpha.5

### 请描述您的需求或者改进建议

建议增加 api接口，便于我直接调接口实现面板管理

**Comment by ssongliu** [comment]
1panel地址+端口/1panel/swagger/index.html
当前已经提供接口文档，登陆之后访问上面路径

**Comment by ssongliu** [comment]
为啥你用的是 alpha 版本，这是我们的测试版本，建议使用正式版本。
