### ISSUE TITLE
[BUG]计划任务->报告页面，查看日志会自动滚动到底部

### ISSUE THREAD

**Issue by Zeen-x** [1Panel-dev/1Panel#4175]
### 联系方式

mail：3253636314@qq.com

### 1Panel 版本

v1.10.1-lts

### 问题描述

在“计划任务”功能中，进入任意任务的“报告页面”，当前计划任务并未在运行中，没有日志实时打印。查看某项日志，当某次日志长度大于一页时，停留在日志顶部，大概3-5秒后日志自动滚动到底部。即使手动滚动到顶部查看，也会在3-5秒内自动滚动到底部。
![image](https://github.com/1Panel-dev/1Panel/assets/49156890/92c9f1f2-f979-40a6-86cc-4bef890764f6)

### 重现步骤

进入“计划任务”功能中，进入任意任务的“报告页面”，当某次日志长度大于一页时，停留在日志顶部，大概3-5秒后日志自动滚动到底部。即使手动滚动到顶部查看，也会在3-5秒内自动滚动到底部。

### 期待的正确结果

在没有实时打印日志时，日志内容不应当自己滚动，影响查看日志

**Comment by ssongliu** [comment]
感谢反馈，报告界面定时 5 秒刷新获取一次日志信息，这个问题下个小版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.10.2-lts 版本已发布。
