### ISSUE TITLE
支持mongo数据库备份

### ISSUE THREAD

**Issue by beautifulBoys** [1Panel-dev/1Panel#4178]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

急需mongo数据库的定时备份。

### 请描述你建议的实现方案

mongo数据库的使用量也不小，请增加数据库备份功能。

**Comment by wanghe-fit2cloud** [comment]
目前 1Panel 还不支持可视化管理 MongoDB 数据库，安装、备份等具体需求的讨论统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/399
