### ISSUE TITLE
[BUG]导入https证书，选择本地时，显示服务器的内容

### ISSUE THREAD

**Issue by sorshion** [1Panel-dev/1Panel#4184]
### 1Panel 版本

1.10.1-lts

### 问题描述

![Snipaste_2024-03-14_16-40-00](https://github.com/1Panel-dev/1Panel/assets/12489667/7ad5ed3e-5ed3-493d-9306-e74eeeb0520f)

### 重现步骤

如上

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前支持的 `选择本地文件` 是要在 1Panel 服务器上选择证书文件，后续版本会优化这里的描述信息。
