### ISSUE TITLE
[BUG]nodejs创建时无法获取启动命令

### ISSUE THREAD

**Issue by hezens** [1Panel-dev/1Panel#4189]
### 联系方式

wcbiubiu@gmail.com

### 1Panel 版本

1.10.1

#### nodejs创建时无法获取启动命令
任意版本的nodejs创建，都无法自动获取启动命令

### 重现步骤

新建nodejs环境

**Comment by zhengkunwang223** [comment]
nodejs 需要依赖源码 建议先去 B 站看一下教程
https://www.bilibili.com/video/BV1uc411R7NS/?spm_id_from=333.999.0.0&vd_source=64804a3460449c08b745b7e98809df36
