### ISSUE TITLE
[FEATURE] 计划任务-数据库备份 支持选择备份所有数据库

### ISSUE THREAD

**Issue by Mystery00** [1Panel-dev/1Panel#419]
### 1Panel 版本

1.0.3

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/19162205/227773119-e5869d65-49ea-4ef9-8815-51da81392314.png)
增加一个All选项

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本支持该需求。

**Comment by wanghe-fit2cloud** [comment]
v1.1.0 版本已发布。
