### ISSUE TITLE
[FEATURE]云容器镜像仓库拉取

### ISSUE THREAD

**Issue by georgeJzzz** [1Panel-dev/1Panel#4191]
### 1Panel 版本

1.10.1-tls

### 请描述您的需求或者改进建议
阿里云容器镜像仓库里的镜像拉取繁琐， 需要命令登录后才可以拉取

### 请描述你建议的实现方案

经常使用， 阿里云容器镜像仓库里的镜像服务
但是直接拉取不了，需要登录。 是否有配置项可以配置login 

### 附加信息
 
感谢

**Comment by wanghe-fit2cloud** [comment]
进入 `容器` - `仓库` 页面，添加 阿里云 仓库，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/f2c8df58-9581-4849-90ed-95b28c858ef7)
