### ISSUE TITLE
[FEATURE]应用商店能否添加一个ffmpeg插件

### ISSUE THREAD

**Issue by imxcy** [1Panel-dev/1Panel#4192]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

需要插件支持网站解析音视频

### 请描述你建议的实现方案

添加一个ffmpeg管理器安装不同版本

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

可以先了解一下上架规则，看是否已满足上架标准？
https://github.com/1Panel-dev/appstore
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/a9a7cd21-9777-42b8-aa77-6782b64d46be)

**Comment by imxcy** [comment]
> 感谢反馈。
> 
> 可以先了解一下上架规则，看是否已满足上架标准？ https://github.com/1Panel-dev/appstore ![image](https://private-user-images.githubusercontent.com/46734380/311567948-a9a7cd21-9777-42b8-aa77-6782b64d46be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NzI5NTMsIm5iZiI6MTcxMDU3MjY1MywicGF0aCI6Ii80NjczNDM4MC8zMTE1Njc5NDgtYTlhN2NkMjEtOTc3Ny00MmI4LWFhNzctNjc4MmI2NGQ0NmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDA3MDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YTcxNzFlOTNiODE1MTIyNWI3OWRlZDAxODk3Mjk5ZDcxNjA4MWJiOWFlY2RlNjY2NmJhZTNjYmVmMjQwY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L_hruwxVMugwmajnigkVGd3LGSuos2wx5IBi2b7cT5U)

满足的

**Comment by imxcy** [comment]
https://ffmpeg.org/

**Comment by wanghe-fit2cloud** [comment]
> https://ffmpeg.org/

推荐下载官方提供的安装包和可执行文件，地址如下：
https://ffmpeg.org/download.html

> 经过评估，该应用不适用于上架 1Panel 应用商店。
