### ISSUE TITLE
[FEATURE] 备份恢复

### ISSUE THREAD

**Issue by ByZhouhang** [1Panel-dev/1Panel#4196]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

<img width="556" alt="0d555ca72fca78824b3d87af7afa9c0" src="https://github.com/1Panel-dev/1Panel/assets/43258053/76524a18-9b42-4d43-86b7-3e9da58163b7">

### 请描述你建议的实现方案

备份的时候，希望给出备份选项，选择性的备份，这样能保证部署的docker应用能百分百迁移，不会因为一些其他配置导致恢复失败，特别是在切换服务器的时候。

**Comment by ssongliu** [comment]
感谢反馈，麻烦提供一下系统日志 /opt/1panel/log/1Panel.log

**Comment by wanghe-fit2cloud** [comment]
先关闭该 issue 了，如后续仍有问题请继续讨论。
