### ISSUE TITLE
[BUG]挂载在 /mnt/b 盘的文件删除，被移动到了系统根目录

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4199]
### 1Panel 版本

v1.10.1-lts

### 问题描述

挂载在 /mnt/b 盘的文件删除被移动到了系统根目录

### 重现步骤

进入挂载盘删除文件即可复现。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.2-lts 版本已发布。
