### ISSUE TITLE
[FEATURE]Answer 已经更新到 v1.2.5

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4200]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

Answer 现在被 Apache 收编了，官方镜像仓库修改为了 apache/answer:1.2.5
1Panel 应用也需要同步修改一下。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期推送更新。

**Comment by wanghe-fit2cloud** [comment]
v1.10.2-lts 版本已发布。
