### ISSUE TITLE
[BUG]面板快照还原失败

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4206]
### 1Panel 版本

v1.10.1-lts

### 问题描述

如题，系统：debian-12.0 , centos-7.9.2009
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/d7aa060a-61e7-4085-972c-00dc2446aacd)

### 重现步骤

快照 - 恢复

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。

**Comment by kndxhz** [comment]
请尽快更新，我转移服务器卡在这痛苦死了

**Comment by wanghe-fit2cloud** [comment]
v1.10.2-lts 版本已发布。
