### ISSUE TITLE
[FEATURE]首页监控数据希望能自动根据大小格式化

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4207]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

如题，
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/9dc74196-a9ca-4a3f-a55f-8c7c4efc26b9)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.8-lts 版本已发布。
