### ISSUE TITLE
[FEATURE]能不能像宝塔那样添加一个go项目啊

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4208]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

因网站需要添加go项目，不想用宝塔，但是1p又没有，能不能添加一个像宝塔那样的go啊

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前可以使用 工具箱 提供的进程守护功能来管理您的 Go 项目。
也可以考虑将自己的项目容器化之后，通过 容器 页面提供的 创建容器或者编排功能来管理。

我们也会考虑在后续版本支持 Golang 运行环境。

**Comment by zhengkunwang223** [comment]
v1.10.12 已支持 go  项目
