### ISSUE TITLE
[BUG]DNS申请SSL证书等待时间太短，导致永远申请证书都是超时

### ISSUE THREAD

**Issue by xiaoxinpro** [1Panel-dev/1Panel#4209]
### 联系方式

zhangzejin3883@163.com

### 1Panel 版本

v1.10.1-lts

### 问题描述

如下图，TXT添加记录30秒后被删除，1Panel提示无法找到TXT记录，重新申请证书时使用跳过DNS校验也是无效的，因为TXT记录已经被删除了，我这边使用腾讯云和DNSPod的Token都是一样的现象。

![image](https://github.com/1Panel-dev/1Panel/assets/11443745/76f2727c-7bf5-4b5c-bf64-901f9e7d5095)

### 重现步骤

目前无法重现，因为多次申请失败提示：
```
too many failed authorizations recently: see https://letsencrypt.org/docs/failed-validation-limit/
```

### 期待的正确结果

增加自定义超时时间，或者增加重试次数，只单纯等待30秒就直接判定超时有些太草率了。

### 相关日志输出

```shell
等待5小时后补充
```

**Comment by zhengkunwang223** [comment]
你用的什么模式？

**Comment by xiaoxinpro** [comment]
> 你用的什么模式？

DNS模式，用腾讯云和DNSPod的现象是一样的。

**Comment by zhengkunwang223** [comment]
> > 你用的什么模式？
> 
> DNS模式，用腾讯云和DNSPod的现象是一样的。

DNS 模式的原理是去 DNS 解析新增 TXT 记录 ，然后验证完之后就删除 
你可以尝试用一下手动 DNS 模式

**Comment by xiaoxinpro** [comment]
> > > 你用的什么模式？
> > 
> > 
> > DNS模式，用腾讯云和DNSPod的现象是一样的。
> 
> DNS 模式的原理是去 DNS 解析新增 TXT 记录 ，然后验证完之后就删除 你可以尝试用一下手动 DNS 模式

我明白你的意思了，等letsencrypt解封后我试一下。

**Comment by xiaoxinpro** [comment]
原因找到了，可能因为我的域名记录是：

| 记录 | 类型 | 记录值 |
|-----------------|-------|-------------------------------------|
| *               | CNAME | www.xxx.com.              |
| www             | A     | 1.2.3.4                      |

的原因，我需要增加一条`_acme-challenge`的CNAME记录才能申请证书成功。

| 记录 | 类型 | 记录值 |
|-----------------|-------|-------------------------------------|
| _acme-challenge | CNAME | www.xxx.com.              |

目前问题已经解决，感谢 @zhengkunwang223 的提示让我找到了解决问题的原因。
