### ISSUE TITLE
权限管理[FEATURE]

### ISSUE THREAD

**Issue by jackphang** [1Panel-dev/1Panel#421]
### 1Panel 版本

v1.0.3

### 请描述您的需求或者改进建议

我希望有些功能不想展示出来，能做成配置开关显示隐藏吗？比如 应用商店和网站这两个功能 我不想展示出来，我改如何配置？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，当前版本还不支持左侧菜单的动态显示与隐藏，后续版本我们会考虑实现该需求。

**Comment by wanghe-fit2cloud** [comment]
菜单项隐藏功能与该 issue 重复 #696
