### ISSUE TITLE
[FEATURE]建议添加自定义界面的接口

### ISSUE THREAD

**Issue by desthon** [1Panel-dev/1Panel#4211]
### 1Panel 版本

4.1.10

### 请描述您的需求或者改进建议

可不可以添加一个自定义界面（就像alist那样的）的接口啊！每次自定义后有新版本又要重新搞

**Comment by zhengkunwang223** [comment]
没看懂 自定义什么界面 前端界面吗？

**Comment by desthon** [comment]
> 没看懂 自定义什么界面 前端界面吗？

例如登录的界面

**Comment by zhengkunwang223** [comment]
> > 没看懂 自定义什么界面 前端界面吗？
> 
> 例如登录的界面

暂时没有计划增加这样的接口
