### ISSUE TITLE
[BUG]应用商店安装MongoDB时yaml文件报错

### ISSUE THREAD

**Issue by Amwidtf** [1Panel-dev/1Panel#4217]
### 1Panel 版本

v1.10.1-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/43975782/f65e3eed-ee5e-42a1-90ee-6dc0b77bfabc)

### 重现步骤

安装MongoDB

### 相关日志输出

```shell
服务内部错误: yaml: unmarshal errors: line 1: cannot unmarshal !!str `<?xml v...` into map[string]interface {}
```

**Comment by wanghe-fit2cloud** [comment]
进入 `主机` - `终端`，先手动拉取一下 MongoDB 容器镜像，看是否 pull 成功：
```shell
docker pull mongo:7.0.6
```

**Comment by wanghe-fit2cloud** [comment]
我们先关闭此 issue 了，后续如问题或需要进一步讨论，请随时提出。

**Comment by Chen017** [comment]
> 进入 `主机` - `终端`，先手动拉取一下 MongoDB 容器镜像，看是否 pull 成功：
> 
> ```shell
> docker pull mongo:7.0.6
> ```

成功了 然后呢 然后我忽略服务器镜像再次安装还是照样报错 只能手动安装吗

**Comment by wanghe-fit2cloud** [comment]
进入 MongoDB 安装目录，手动执行 `docker-compose up -d` 命令，看一下命令执行结果。
