### ISSUE TITLE
[FEATURE] 新增防火墙配置功能

### ISSUE THREAD

**Issue by jackphang** [1Panel-dev/1Panel#422]
### 1Panel 版本

v1.0.3

### 请描述您的需求或者改进建议

能否增加防火墙配置功能？可在系统中配置防火墙规则，这样就不需要用第三方软件或者通过命令行来进行处理了，谢谢。

**Comment by maninhill** [comment]
感谢反馈，该功能正在开发中，v1.1 发布。

**Comment by xxianzf** [comment]
我刚想上来建议增加防火墙的功能

**Comment by wanghe-fit2cloud** [comment]
v1.1.0 版本已发布。
