### ISSUE TITLE
[FEATURE]增加重新安装功能

### ISSUE THREAD

**Issue by wang-qa** [1Panel-dev/1Panel#4220]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

场景：定制化系统安装

1. 安装1panel ，可以正常启动
2. 升级系统后，系统会自动清除不在指定路径下的配置文件
3. 当前保留 安装在$HOME/1panel

预期：
可以手动复制 service等配置文件到指定路径，获取保留旧数据并重新安装（如端口号、安装路径），以便service等重新生成

### 请描述你建议的实现方案

生成配置好的 service，1pctl，直接使用软连接链接到指定路径下
并能正常启动

**Comment by wanghe-fit2cloud** [comment]
在操作系统升级之前，进入 `面板设置` 页面制作一个 1Panel 快照，然后用快照恢复就可以满足你的需求吧。
