### ISSUE TITLE
[FEATURE] 添加一个类似于 aaPanel python项目管理器。

### ISSUE THREAD

**Issue by HankMo** [1Panel-dev/1Panel#423]
### 1Panel 版本

1.0.3

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/60347960/227857981-ee7f2b83-fb58-4a28-bd18-9555a29bf318.png)

### 请描述你建议的实现方案

类似于这样的。我目前用python语言比较多。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会考虑以容器的方式运维 Python 项目。

**Comment by wanghe-fit2cloud** [comment]
运行环境需求的讨论，统一汇总到该 issue #748
