### ISSUE TITLE
[FEATURE]应用商店，添加Aria2 ，可以下载磁力链接

### ISSUE THREAD

**Issue by wang-qa** [1Panel-dev/1Panel#4230]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

应用商店，添加Aria2 下载工具及web管理页面`Aria2NG`
https://github.com/aria2/aria2
https://github.com/mayswind/AriaNg

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/3971
