### ISSUE TITLE
网站自定义目录

### ISSUE THREAD

**Issue by 3419912225** [1Panel-dev/1Panel#4238]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

现在网站不能自定义目录所在位置
例如我的第一个网站的目录是xxx
我的第二个网站的目录想在第一个网站目录的基础上，就是xxx/ppp这样
但是现在只能通过修改配置文件实现，可是网站显示的目录却还是原来的

### 请描述你建议的实现方案

建议在新建站点的时候，那个代号，直接可以设置网站的所在目录，现在的代号仅仅只是目录的名字，不能自由实现

**Comment by wanghe-fit2cloud** [comment]
自定义网站目录相关功能的讨论，统一汇总到该 issue #2783
