### ISSUE TITLE
[FEATURE]增加容器镜像清理功能

### ISSUE THREAD

**Issue by wan92hen** [1Panel-dev/1Panel#424]
### 1Panel 版本

v1.0.2

### 请描述您的需求或者改进建议

参考 Docker Desktop，增加容器镜像清理功能，可以选择清理掉 Dangling 或未被使用的镜像。
![image](https://user-images.githubusercontent.com/27671436/227915278-00c2c017-77d0-45ad-902d-dc674da34236.png)

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
