### ISSUE TITLE
OpenLiteSpeed的1panel集成

### ISSUE THREAD

**Issue by LReion** [1Panel-dev/1Panel#4240]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

希望在应用商店中OpenResty之外的OpenLiteSpeed在面板中。小小的提一下建议。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1Panel 的网站功能是要强绑定 OpenResty 应用，近期暂无计划支持 OpenLiteSpeed，望理解。
