### ISSUE TITLE
[FEATURE]像宝塔面板一样可以指定域名到某个文件目录

### ISSUE THREAD

**Issue by HereNoAg300L** [1Panel-dev/1Panel#4241]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

像宝塔面板一样可以指定域名到某个文件目录

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
自定义网站目录相关功能的讨论，统一汇总到该 issue #2783
