### ISSUE TITLE
屏蔽选择网站运行目录中，辅助开发包目录

### ISSUE THREAD

**Issue by lizundao** [1Panel-dev/1Panel#4242]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

屏蔽选择网站运行目录中，辅助开发包目录，如 /node_modules、/vendor 目录
![微信截图_20240320094825](https://github.com/1Panel-dev/1Panel/assets/58964527/d2be99c9-1522-4f67-a6ee-cede3750698c)

### 请描述你建议的实现方案

无

### 附加信息

无

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
