### ISSUE TITLE
[FEATURE] 建议加一个向导模式创建本地应用

### ISSUE THREAD

**Issue by maxbad** [1Panel-dev/1Panel#4246]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

自己的项目容器化, 有镜像包了, 要做成本地应用,

**Comment by QYG2297248353** [comment]
本地应用不提供创建，你可以直接在服务器运行打包的容器，在容器页面管理。
应用商店的本地分类是按照 `docker-compose` 格式创建的
不过你可以在 `容器` >> `镜像`  >> `导入镜像` 导入你的镜像包
然后在容器创建容器。

**Comment by zhengkunwang223** [comment]
https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8 参考这个

**Comment by maxbad** [comment]
> https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8 参考这个

谢谢
