### ISSUE TITLE
[FEATURE] 增加更新应用提前拉取

### ISSUE THREAD

**Issue by QYG2297248353** [1Panel-dev/1Panel#4248]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

应用更新，拉取时间贼长，导致的升级失败
JumpServer 升级 3.10.6时出现的问题：
2024年3月19日发布JumpServer 3.10.6，今天在升级应用时提示容器不存在，找了类似升级失败的Issue，使用手动拉取，发现拉取时间非常长，达半小时左右，都未能拉取完成(声明不是网络带宽的原因，其他设备拉取都是相似情况，耗时长)，大概率原因是发布时间较短，之前手动拉取刚发布的应用确实存在时间过长的问题，还不能断开 SSH。
![image](https://github.com/1Panel-dev/1Panel/assets/56836951/25636d55-11cd-4991-bcb1-e61bfa8db62a)

所以希望增加更新应用的提前镜像拉取，定期清除镜像就能解决占用问题，以及以前版本的镜像删除

- [ ] 更新应用的镜像提前量拉取

其次Docker网络与面板网络检查机制不一样
如果给 `Docker` 设置了代理,但是出现网络不可达，面板没有任何提示，升级应用或安装应用，直接提示容器不存在。建议增加Docker的网络检查，面板给与友好提示

- [ ] 面板网络检查的同时，对 `Docker` 的网络检查

**Comment by wanghe-fit2cloud** [comment]
1、提示容器不存在的问题，我们会在接下来的 1.10.2-lts 版本优化。
2、定时清理镜像的需求，建议创建 `Shell 脚本` 类型计划任务来定时清理镜像
> 提供一个清理全部 docker 垃圾的命令，仅供参考 `docker system prune --volumes --all -f`

3、应用升级逻辑会在后续后续版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.2-lts 版本已优化提示信息（今天会推送版本更新）。
应用更新逻辑会在后续大版本重构时考虑。

**Comment by wanghe-fit2cloud** [comment]
v1.10.2-lts 版本已发布。
