### ISSUE TITLE
[BUG] php7.4 构建脚本问题导致字符集错误

### ISSUE THREAD

**Issue by ayuayue** [1Panel-dev/1Panel#4249]
### 联系方式

1401262639@qq.com

### 1Panel 版本

v1.10.1-lts

### 问题描述

WARN: Empty continuation line found in: RUN apk --no-cache add tzdata     && cp "/usr/share/zoneinfo/$TZ" /etc/localtime     && echo "$TZ" > /etc/timezone RUN apk add --no-cache --repository http://${CONTAINER_PACKAGE_URL}/alpine/v3.13/community/ gnu-libiconv=1.15-r3

命令未正确结束，导致跟后面的 RUN apk 一起执行了，导致 /etc/timezone  的内容不对，并且 没有执行安装gnu-libiconv，导致容器内中文字符集乱码

### 重现步骤

重新安装 php 环境

### 期待的正确结果

脚本调整，支持中文字符集

### 相关日志输出

```shell
WARN: Empty continuation line found in: RUN apk --no-cache add tzdata     && cp "/usr/share/zoneinfo/$TZ" /etc/localtime     && echo "$TZ" > /etc/timezone RUN apk add --no-cache --repository http://${CONTAINER_PACKAGE_URL}/alpine/v3.13/community/ gnu-libiconv=1.15-r3
```

**Comment by wanghe-fit2cloud** [comment]
麻烦提供一下全部日志。

**Comment by ayuayue** [comment]
完整的启动日志：

#0 building with "default" instance using docker driver

#1 [1panel-php internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.20kB done
#1 WARN: Empty continuation line found in: RUN apk --no-cache add tzdata     && cp "/usr/share/zoneinfo/$TZ" /etc/localtime     && echo "$TZ" > /etc/timezone RUN apk add --no-cache --repository http://${CONTAINER_PACKAGE_URL}/alpine/v3.13/community/ gnu-libiconv=1.15-r3
#1 DONE 0.0s

#2 [1panel-php internal] load metadata for docker.io/library/php:7.4.33-fpm-alpine
#2 DONE 2.0s

#3 [1panel-php internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [1panel-php  1/11] FROM docker.io/library/php:7.4.33-fpm-alpine@sha256:0aeb129a60daff2874c5c70fcd9d88cdf3015b4fb4cc7c3f1a32a21e84631036
#4 DONE 0.0s

#5 [1panel-php internal] load build context
#5 transferring context: 6.47MB 0.1s done
#5 DONE 0.1s

#6 [1panel-php  3/11] ADD ./extensions/install-php-extensions  /usr/local/bin/
#6 CACHED

#7 [1panel-php  4/11] RUN chmod uga+x /usr/local/bin/install-php-extensions
#7 CACHED

#8 [1panel-php  5/11] COPY ./extensions /tmp/extensions
#8 CACHED

#9 [1panel-php  6/11] WORKDIR /tmp/extensions
#9 CACHED

#10 [1panel-php  9/11] RUN chmod +x install-composer.sh     && sh install-composer.sh     && rm -rf /tmp/extensions
#10 CACHED

#11 [1panel-php  8/11] RUN apk --no-cache add tzdata     && cp "/usr/share/zoneinfo/Asia/Shanghai" /etc/localtime     && echo "Asia/Shanghai" > /etc/timezone RUN apk add --no-cache --repository http://mirrors.ustc.edu.cn/alpine/v3.13/community/ gnu-libiconv=1.15-r3
#11 CACHED

#12 [1panel-php 10/11] RUN apk --no-cache add shadow && usermod -u 1000 www-data && groupmod -g 1000 www-data
#12 CACHED

#13 [1panel-php  2/11] RUN if [ mirrors.ustc.edu.cn ] ; then sed -i "s/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g" /etc/apk/repositories ; fi
#13 CACHED

#14 [1panel-php  7/11] RUN chmod +x install.sh     && sh install.sh
#14 CACHED

#15 [1panel-php 11/11] WORKDIR /www
#15 CACHED

#16 [1panel-php] exporting to image
#16 exporting layers done
#16 writing image sha256:841151561e0138f9841349015ee1997be9b59bb0d85cb10e000b8b6840bd2631 done
#16 naming to docker.io/library/1panel-php:7.4.33 done
#16 DONE 0.0s

定位问题处

![image](https://github.com/1Panel-dev/1Panel/assets/44837611/f9d50379-291d-470b-b078-9478001fdebf)

**Comment by zhengkunwang223** [comment]
感谢建议 我们优化一下
也可以直接给我们提 Pr

**Comment by ayuayue** [comment]
已提交 pr 
https://github.com/1Panel-dev/appstore/pull/1124
