### ISSUE TITLE
应用商店安装数据库选择问题

### ISSUE THREAD

**Issue by ifacecn** [1Panel-dev/1Panel#4252]
### 1Panel 版本

1.10

### 请描述您的需求或者改进建议

为何安装建站应用或是需要使用数据库的应用在安装时不能选择外部数据库呢？必须安装本机数据库才可以使用吗？

### 请描述你建议的实现方案

希望改进可供选择

**Comment by wanghe-fit2cloud** [comment]
你也可以进入 `数据库` 页面，添加远程数据库。
