### ISSUE TITLE
[FEATURE]应用商店添加Zblog

### ISSUE THREAD

**Issue by cli-r** [1Panel-dev/1Panel#4253]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

应用商店添加Zblog博客程序，有官方Docker镜像https://github.com/zblogcn/zblogphp-docker-image

## 使用 Docker Compose 部署「推荐」

wdssmq/zbp-docker-compose: 使用 Docker Compose 快捷部署 Z-BlogPHP + MySQL；：

[https://github.com/wdssmq/zbp-docker-compose](https://github.com/wdssmq/zbp-docker-compose "wdssmq/zbp-docker-compose: 使用 Docker Compose 快捷部署 Z-BlogPHP + MySQL；")

## 实际可用镜像及 TAG

- `wdssmq/zblogphp`
    - `wdssmq/zblogphp:latest` - Nginx + PHP 7.4
- `wdssmq/zblogphp-nginx`
    - `wdssmq/zblogphp-nginx:latest` - 同 8.2
    - `wdssmq/zblogphp-nginx:8.2`    - Nginx + PHP 8.2
    - `wdssmq/zblogphp-nginx:8.1`    - Nginx + PHP 8.1
    - `wdssmq/zblogphp-nginx:8.0`    - Nginx + PHP 8.0
    - `wdssmq/zblogphp-nginx:7.4`    - Nginx + PHP 7.4

**Comment by wanghe-fit2cloud** [comment]
目前，我们主要以项目的 star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有约 1 万 star 的开源项目，望理解。
