### ISSUE TITLE
[BUG]使用OpenResty创建运行环境时，会报错

### ISSUE THREAD

**Issue by 0x1233333** [1Panel-dev/1Panel#4254]
### 1Panel 版本

v1.10.1-lts

### 问题描述

使用OpenResty创建运行环境时，会报错，提示：`服务内部错误: yaml: unmarshal errors: line 1: cannot unmarshal !!str `<?xml v...` into map[string]interface {}`
尝试过重启，重新安装php，无法解决问题

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/54734393/6eb45ee0-2a8d-4d52-b5af-a2fe27748a98)

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/54734393/b2d39339-21e0-4f2b-baeb-426f6b25b6e0)

**Comment by wanghe-fit2cloud** [comment]
可以先确认一下创建网站时选择的运行环境镜像是不是存在：

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/083d2725-4e41-4b75-8ae9-6e39e5f4b0a3)

> `容器` - `镜像列表` 页面可以查看目标镜像

**Comment by 0x1233333** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/54734393/104858ea-6f53-42c1-a3e8-afd62a72ce44)

**Comment by 0x1233333** [comment]
确实是安装了

**Comment by 0x1233333** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/54734393/4e734f5c-c717-4377-addb-f5934a28c8b9)

**Comment by 0x1233333** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/54734393/ec8d1741-5124-48ae-8213-2e458df7a565)

**Comment by wanghe-fit2cloud** [comment]
> 尝试过重启，重新安装php，无法解决问题。

1、是重启 1Panel 服务器吗？
2、手动执行 `docker-compose version` 命令，查看一下 docker-comopse 版本。

**Comment by 0x1233333** [comment]
是的，直接重启服务器也是如此
Docker Compose version v2.16.0

**Comment by 0x1233333** [comment]
反代网站，一键部署都没有问题。这个运行环境就是不行

**Comment by wanghe-fit2cloud** [comment]
我们在本地环境无法重现上述问题。
建议删除当前的运行环境并重新创建，然后再关联运行环境网站，查看是否仍然存在该问题。

> 先关闭该 issue 了，如后续仍有问题请随时讨论。
