### ISSUE TITLE
[FEATURE] 在首页添加时区和时间显示

### ISSUE THREAD

**Issue by mobeicanyue** [1Panel-dev/1Panel#4261]
### 1Panel 版本

1.10.2

### 请描述您的需求或者改进建议

在首页详细信息添加服务器设定的时区和时间显示，方便管理人员维护 判断
因为并不是所有服务器都在东八区，
或者管理员尚未修改系统时区可以及时发现

![1000059913](https://github.com/1Panel-dev/1Panel/assets/81098819/bf788409-d6eb-4000-bb19-46865e28e43e)

### 请描述你建议的实现方案

添加时区和时间显示

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，系统时区和服务时间可以进入 `工具箱` 页面设置并查看，当前版本由于概览页面空间限制，先不考虑增加上述内容。
