### ISSUE TITLE
[FEATURE]文本编辑框的主题能否记住我的选择？

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4266]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

每次打开文本编辑框，总是自动选择黑色主题，改完之后，下次登录面板又恢复原样，能否记住我的选择？
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/e7929d6d-6f60-4618-be3c-e17b1a9f8b7b)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
