### ISSUE TITLE
[BUG] 语言展示不正确

### ISSUE THREAD

**Issue by lqllife** [1Panel-dev/1Panel#4269]
### 1Panel 版本

1.10.2-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/23254569/d583bf9b-de97-4be9-a892-eee019515dc5)

更新到最新本后，右下角的“使用手册”，“册”这个字是繁体的。

看了代码，
doc2 在 /frontend/src/lang/modules/zh.ts 中显示的是“使用手册”
doc2 在 /frontend/src/lang/modules/tw.ts 中显示的是“使用手冊”

语言包应该默认就是 zh，所以应该不会展示繁体才对。

### 重现步骤

登录 1Panel Web 控制台，在页面右下角查看。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，该问题已经修复，会在下个版本推送更新。
https://github.com/1Panel-dev/1Panel/commit/44445aca936694ffb097c9b3452356e47fe2dcbe

**Comment by lqllife** [comment]
👍

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
