### ISSUE TITLE
[FEATURE]两步验证支持字符串选项以及应用商店应用支持更多的自定义参数

### ISSUE THREAD

**Issue by muyunil** [1Panel-dev/1Panel#427]
### 1Panel 版本

1.0.3

### 请描述您的需求或者改进建议

对两步验证提供处二维码之外的字符串选项，以供部分不支持识别二维码录入的应用使用。

对Halo应用的部署提供更多的选择，如使用数据卷，选择网络，可以添加创建时的自定义参数，还有数据库的选择，h2，sqlite，mysql，mariadb，等等。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。两步验证支持字符串选项以及应用自定义参数的需求，我们会在后续版本中支持。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
