### ISSUE TITLE
[FEATURE] 应用商店恢复RssHub应用

### ISSUE THREAD

**Issue by lqllife** [1Panel-dev/1Panel#4270]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

能恢复RssHub吗，算是小众软件，不过挺实用的。
谢谢。

**Comment by wanghe-fit2cloud** [comment]
刚查看了一下官方文档，有提供完整的 [docker-compose.yml](https://github.com/DIYgod/RSSHub/blob/master/docker-compose.yml) 文件，然后可以通过 `容器` 页面提供的 `创建编排` 功能来管理 RssHub 应用。

> 由于该应用安装涉及到不同的服务，通过 1Panel 应用商店维护比较复杂，暂时就先不考虑上架该应用了，望理解。
