### ISSUE TITLE
[FEATURE]建议完善下文件编辑器的功能

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4272]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

现在的文件编辑器使用不是太方便，建议可以窗口最大化，并能选择文件目录，现在使用要先打开目录再进行编辑，完成后又要找目录。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
重复问题 https://github.com/1Panel-dev/1Panel/issues/3624
