### ISSUE TITLE
[BUG] MongoDB安装失败

### ISSUE THREAD

**Issue by YaKun9** [1Panel-dev/1Panel#4274]
### 1Panel 版本

v1.10.1-lts

### 问题描述
![image](https://github.com/1Panel-dev/1Panel/assets/131952790/35cf4940-dbd3-4723-b3e4-4fd68381e809)

### 重现步骤

MongoDB  | 
MongoDB  | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
MongoDB  |   see https://jira.mongodb.org/browse/SERVER-54407
MongoDB  |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
MongoDB  |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
MongoDB  | 
MongoDB  | /usr/local/bin/docker-entrypoint.sh: line 416:    27 Illegal instruction     "${mongodHackedArgs[@]}" --fork
MongoDB  | 

### 相关日志输出

```shell
MongoDB  | 
MongoDB  | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
MongoDB  |   see https://jira.mongodb.org/browse/SERVER-54407
MongoDB  |   see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
MongoDB  |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
MongoDB  | 
MongoDB  | /usr/local/bin/docker-entrypoint.sh: line 416:    27 Illegal instruction     "${mongodHackedArgs[@]}" --fork
MongoDB  |
```

**Comment by wanghe-fit2cloud** [comment]
> MongoDB | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!

看这段错误信息，可能与服务器架构有关系，可以去 MongoDB 官方找一下具体解决方案。
