### ISSUE TITLE
[BUG] 应用商店不规范图标的Logo变形

### ISSUE THREAD

**Issue by QYG2297248353** [1Panel-dev/1Panel#4276]
### 联系方式

qyg2297248353@163.com

### 1Panel 版本

v1.10.2-lts

### 问题描述

Jenkins
![image](https://github.com/1Panel-dev/1Panel/assets/56836951/71bded30-9ff3-45b4-a661-bd0a6b8a3469)
![image](https://github.com/1Panel-dev/1Panel/assets/56836951/6ec6908b-8f31-4c56-8f35-dd1e1e29d871)
详情正常
![image](https://github.com/1Panel-dev/1Panel/assets/56836951/d24eda34-103e-4ff7-983b-94cce66166bc)

Minio
![image](https://github.com/1Panel-dev/1Panel/assets/56836951/7ce04a47-64f7-49c1-864b-a6e5ccda2288)
![image](https://github.com/1Panel-dev/1Panel/assets/56836951/18ec2fa1-9f6c-48c2-b8cf-24b69cf48327)
详情正常
![image](https://github.com/1Panel-dev/1Panel/assets/56836951/8bc66543-d709-43ec-b176-a3b74f7ca72e)

### 重现步骤

升级至 `v1.10.2-lts` 对图标有优化与规范

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本优化图标显示问题。

**Comment by wanghe-fit2cloud** [comment]
已修复。
