### ISSUE TITLE
[BUG]应用一直在安装中

### ISSUE THREAD

**Issue by youyi0218** [1Panel-dev/1Panel#4278]
### 联系方式

youyi0718@outlook.com

### 1Panel 版本

v1.10.2-lts

### 问题描述

在自带的应用市场安装软件，一直在安装中，主页的网卡监控上下行只有kb/s
![image](https://github.com/1Panel-dev/1Panel/assets/135406843/6fc91fbe-070e-4ea2-8291-469ee3b112d3)
![image](https://github.com/1Panel-dev/1Panel/assets/135406843/536e6291-33bd-4570-b254-858818490ce1)
![image](https://github.com/1Panel-dev/1Panel/assets/135406843/d3963c5c-38f6-41d7-891c-dd8e8a95303f)
已经配置好镜像加速
使用win11 wsl2 ubuntu

### 重现步骤

直接下载

### 期待的正确结果

在宝塔面板下载速度是正常的，电脑的网速也没有问题，下载速度跑不满也不至于kb/s吧
![image](https://github.com/1Panel-dev/1Panel/assets/135406843/16e73cc0-f842-4515-acd9-074a9362d290)

**Comment by wanghe-fit2cloud** [comment]
如果设置镜像加速后 pull 应用镜像依然超时，那就先手动将应用镜像拉取到本地吧。
> 或者考虑配置 docker 代理。

**Comment by youyi0218** [comment]
他不是拉取镜像超时，他又在下载，只是速度龟速，有没有什么办法能让这个下载速度恢复正常
![image](https://github.com/1Panel-dev/1Panel/assets/135406843/75f73fb4-8a7a-4e16-a0c2-c78849a69444)
![image](https://github.com/1Panel-dev/1Panel/assets/135406843/4e009da3-74ed-4bab-91ea-1b08b05d4298)

**Comment by wanghe-fit2cloud** [comment]
1Panel 系统也是调用的 docker sdk。
这是网络问题，也没有太好的办法。

**Comment by taurusduan** [comment]
> 1Panel 系统也是调用的 docker sdk。 这是网络问题，也没有太好的办法。

请问一下，那么要如何停止呢？
![image](https://github.com/1Panel-dev/1Panel/assets/30854760/99d45bd7-f80a-4bdb-b012-beb8306230c5)

**Comment by wanghe-fit2cloud** [comment]
> 请问一下，那么要如何停止呢？

重启 1Panel 服务，会重置应用安装状态。之后可以强制卸载已安装应用。
