### ISSUE TITLE
[BUG]运行目录显示有问题

### ISSUE THREAD

**Issue by heyailab** [1Panel-dev/1Panel#4280]
### 1Panel 版本

v1.10.2-lts

### 问题描述

运行目录没有正确显示
![bug](https://github.com/1Panel-dev/1Panel/assets/1612740/201a336f-f4f4-478c-9837-84e7329a0ac5)

### 重现步骤

网站设置 -  网站目录 -运行目录

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦提供一下 index 目录截图。

**Comment by heyailab** [comment]
![index](https://github.com/1Panel-dev/1Panel/assets/1612740/e722f821-5ee0-4f1d-820d-9a2be7ab951b)
> 感谢反馈，麻烦提供一下 index 目录截图。

目录没有动过的，之前的版本是没问题的
![微信截图_20240324223659](https://github.com/1Panel-dev/1Panel/assets/1612740/cfe1244b-2e32-4d00-91d3-ba469100151a)

**Comment by wanghe-fit2cloud** [comment]
> 目录没有动过的，之前的版本是没问题的

收到，我们在本地环境复现一下问题。

**Comment by zhengkunwang223** [comment]
后续版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
