### ISSUE TITLE
[FEATURE] 网站 四层端口转发的需求

### ISSUE THREAD

**Issue by 20has** [1Panel-dev/1Panel#4282]
### 1Panel 版本

v1.9.4

### 请描述您的需求或者改进建议

虽然可以在主配置文件里面添加 如下配置的 四层端口转发，当时不够优雅，希望可以在网站-创建网站-类型里面加入四层端口转发的功能。

stream {
    server {
        listen 444;
        proxy_pass 10.0.0.10:555;
    }
}

**Comment by wanghe-fit2cloud** [comment]
是的，我们在面板设置页面开放了自定义配置的功能。
关于可视化配置，我们也会在后续版本考虑支持。

**Comment by wanghe-fit2cloud** [comment]
网站端口转发相关需求的讨论，我们统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/5135
