### ISSUE TITLE
[BUG]手机版页面编辑网站不方便

### ISSUE THREAD

**Issue by meng-plus** [1Panel-dev/1Panel#4284]
### 1Panel 版本

v1.10.2-lts

### 问题描述

见截图 手机版几乎无法操作，横屏勉强可用
![image](https://github.com/1Panel-dev/1Panel/assets/37764731/2ce996bb-b4a5-49a8-b44b-0bbc6df6efde)

### 重现步骤

网页版F12 切换网页手机模式 即可浮现

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，关于兼容移动端的问题，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
最新版本优化了移动端体验，建议将 1Panel 升级至最新版本。
