### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by shanku-rm-rf** [1Panel-dev/1Panel#4285]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

是否可以考虑对1panel的监控开放API，以便于多台1panel性能监测

### 请描述你建议的实现方案

如上

### 附加信息

![微信图片_20240323154205](https://github.com/1Panel-dev/1Panel/assets/164454282/9f97c951-67a9-4f85-814d-e6034cb5dba2)
![微信图片_20240323154254](https://github.com/1Panel-dev/1Panel/assets/164454282/733ebd94-381c-4815-87a1-92244a7fb2b2)

**Comment by wanghe-fit2cloud** [comment]
你好，我们当前已经提供了接口文档，地址如下：
`1Panel IP 地址:端口`/1panel/swagger/index.html

**Comment by MillerFour** [comment]
> 你好，我们当前已经提供了接口文档，地址如下： `1Panel IP 地址:端口`/1panel/swagger/index.html

你好，请问下 swagger文档中的 EntranceCode 字段是什么？ 官网及论坛中并没有发现这个是出处
