### ISSUE TITLE
[QUESTION]能否在1Panel中，安装arthas插件来跟踪K8s里面pod的代码，这种可以吗？

### ISSUE THREAD

**Issue by cfy3133** [1Panel-dev/1Panel#429]
### 请描述您的问题

能否在1Panel中，安装arthas插件来跟踪K8s里面pod的代码，这种可以吗？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，请问您目前是否已经有可行方案，麻烦详细说明一下具体实施过程。

**Comment by cfy3133** [comment]
谢谢回复，我这边没有，因为我看到有些k8s平台是又这种插件的，但是具体我也不知道要怎么做

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，经团队内部讨论，我们短期内不会支持上述需求。
