### ISSUE TITLE
[BUG]超时判断过短

### ISSUE THREAD

**Issue by refgd** [1Panel-dev/1Panel#4291]
### 1Panel 版本

1.10.2

### 问题描述

如果文件夹里文件和子目录很多的情况下，修改用户组和用户，总是不成功，显示超时

### 重现步骤

文件和子目录很多的情况下

### 期待的正确结果

能够完成命令

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
