### ISSUE TITLE
[FEATURE]请求: 应用商店增加discourse

### ISSUE THREAD

**Issue by woodchen-ink** [1Panel-dev/1Panel#4292]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

discourse的安装非常困难, 期待能在应用商店支持安装, 谢谢

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上架 discourse。

**Comment by mmw1984** [comment]
会在下一个版本增加吗？

**Comment by wanghe-fit2cloud** [comment]
根据调研结果，Discourse 官方提供了安装脚本，链接如下：https://github.com/discourse/discourse/blob/main/docs/INSTALL-cloud.md#6-install-discourse。
鉴于安装过程复杂（不方便通过 1Panel 应用商店来管理）且后期运维管理存在不确定性，建议用户使用官方提供的脚本进行安装。

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/b9431560-cece-40a8-ac2d-459bf2d9a57b)

**Comment by wanghe-fit2cloud** [comment]
应用已上架。
进入应用商店列表，点击右上角的【更新应用列表】按钮，待同步完成后即可安装应用。

**Comment by woodchen-ink** [comment]
> 应用已上架。 进入应用商店列表，点击右上角的【更新应用列表】按钮，待同步完成后即可安装应用。

谢谢
