### ISSUE TITLE
安装1panel之前安装的软件，是无法扫描到的吗

### ISSUE THREAD

**Issue by Debug0258** [1Panel-dev/1Panel#4294]
安装1panel之前安装的软件，是无法扫描到的吗
![image](https://github.com/1Panel-dev/1Panel/assets/163090268/388d3a96-0752-4de9-935c-d9db6ebe3c63)
![image](https://github.com/1Panel-dev/1Panel/assets/163090268/b874a002-9e03-4155-8af2-eff20edd015b)

_Originally posted by @Debug0258 in https://github.com/1Panel-dev/1Panel/issues/250#issuecomment-2016463837_

**Comment by wanghe-fit2cloud** [comment]
> 安装1panel之前安装的软件，是无法扫描到的吗

是的，不能直接管理。
> 你可以将自己安装的数据库服务添加为远程服务器。
