### ISSUE TITLE
[BUG]面板首页内存占用显示不准确

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#4296]
### 1Panel 版本

v1.10.2-lts

### 问题描述

本地运行模型，通过`top`命令查看内存显示占用`80%`左右，而面板显示的内存占用不准确：

![20240325-140340](https://github.com/1Panel-dev/1Panel/assets/63288007/ed11ae3c-dd99-4545-a116-7eef2bc1f52b)

### 重现步骤

本地运行70b aigc模型

**Comment by ssongliu** [comment]
感谢反馈，麻烦执行 free -m 看一下返回信息

**Comment by JAINKRE** [comment]
返回：
```cmd
[root@localserver-a01 ~]# free -m
              total        used        free      shared  buff/cache   available
Mem:          47734       12715         272         115       34746       34415
Swap:          7871         595        7276
```

执行录屏如下：
![20240326-150204](https://github.com/1Panel-dev/1Panel/assets/63288007/7d0c91ef-3f26-4eea-aecb-c38419017ed0)

**Comment by JAINKRE** [comment]
出现这个问题是使用ollama运行70b模型，模型正常运行了，但是看不到内存占用信息，free -m 好像也没有检测到ollama容器占用情况

**Comment by ssongliu** [comment]
usedPercent := 100 * float64(totalCount-availableCount) / float64(totalCount)

我们使用的是 shirou/gopsutil/v3 这个第三方依赖，内存是通过上面这个公式计算的，他排除了 buff/cache 部分

**Comment by JAINKRE** [comment]
好的，了解，感谢说明。但不知可否考虑优化一下这部分呢？毕竟也是实际占用了。

**Comment by ssongliu** [comment]
缓存实际上是不占用内存的，所以暂时不考虑修改这边逻辑。
