### ISSUE TITLE
[BUG]一键部署Halo网站访问502

### ISSUE THREAD

**Issue by NyaDoo** [1Panel-dev/1Panel#4299]
### 1Panel 版本

v1.10.2-lts

### 问题描述

通过1Panel一键部署Halo，网站访问出现502错误，具体如下截图：
![image](https://github.com/1Panel-dev/1Panel/assets/65238336/bdfc60c8-a853-4c2d-8687-6c59f3a763bb)
网站部署了腾讯云的免费SSL证书，并接入了阿里云的DCDN全站加速。
观察OpenResty容器日志可见如下报错：
2024/03/25 16:15:23 [error] 54#54: *243 cannot load certificate "data:": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE) while SSL handshaking, client: 58.105.196.137, server: 0.0.0.0:443

### 重现步骤

干净系统全新安装1Panel（Ubuntu22.04），通过一键部署安装JHalo，配置腾讯云免费SSL证书，并配置阿里云DCDN全站加速，CDN加速回源端口443。

**Comment by NyaDoo** [comment]
也去除阿里云DCDN加速，直接解析服务器测试过，依旧会出现502报错，具体情况如下：
1、未开启HTTPS，绑定服务器IP，并且使用IP直接访问，可稳定正常访问。
2、未开启HTTPS、绑定域名并通过域名访问，开启HTTPS、绑定域名并通过域名访问，502无法正常访问。

**Comment by zhengkunwang223** [comment]
是 IP 类型的网站吗？IP 类型的网站要设置为默认网站

**Comment by NyaDoo** [comment]
> 是 IP 类型的网站吗？IP 类型的网站要设置为默认网站

不是，目前的情况是将IP绑定至该网站，可以正常访问。将域名绑定至该网站，如上图502错误。

**Comment by NyaDoo** [comment]
> 是 IP 类型的网站吗？IP 类型的网站要设置为默认网站

刚刚试了一下，设置成默认站点确实可以解决我遇到的问题。不过我还是有点疑惑，为什么套了阿里云DCDN之后就要设置成默认站点才可以正常访问呢？CDN回源应该都会带域名的吧？

**Comment by zhengkunwang223** [comment]
> > 是 IP 类型的网站吗？IP 类型的网站要设置为默认网站
> 
> 刚刚试了一下，设置成默认站点确实可以解决我遇到的问题。不过我还是有点疑惑，为什么套了阿里云DCDN之后就要设置成默认站点才可以正常访问呢？CDN回源应该都会带域名的吧？

这个可能需要你检查一下 CDN 配置 正常都是没问题的
