### ISSUE TITLE
[FEATURE]希望守护进程名称支持 `-`  

### ISSUE THREAD

**Issue by hh-Ink** [1Panel-dev/1Panel#4303]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

[FEATURE]希望守护进程名称支持 `-`

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
