### ISSUE TITLE
[BUG] openEuler系统上安装出现问题

### ISSUE THREAD

**Issue by yukaichao** [1Panel-dev/1Panel#4304]
### 1Panel 版本

安装 1Panel v1.10.2-lts

### 问题描述

在openEuler在线安装1Panel面板出现
![image](https://github.com/1Panel-dev/1Panel/assets/38757894/08e52775-21a0-4f57-b5d0-e0e54bbbf34b)
安装tar后再次尝试安装出现
![image](https://github.com/1Panel-dev/1Panel/assets/38757894/a151431c-72f6-4172-987a-1acf1902f525)

### 重现步骤

在树莓派4b上安装openEuler-22.03-LTS-SP3-raspi-aarch64
（https://repo.openeuler.org/openEuler-22.03-LTS-SP3/raspi_img/openEuler-22.03-LTS-SP3-raspi-aarch64.img.xz）
启动后直接安装面板就可以重现

**Comment by wanghe-fit2cloud** [comment]
参考这个issue https://github.com/1Panel-dev/1Panel/issues/3308
