### ISSUE TITLE
[FEATURE]希望应用商店上架aliyundrive-webdav

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4306]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

[messense/aliyundrive-webdav - Docker Image | Docker Hub](https://hub.docker.com/r/messense/aliyundrive-webdav)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上架上述应用。

**Comment by maninhill** [comment]
Alist 能够代替这个项目吗？
