### ISSUE TITLE
[FEATURE]希望1panel能有一个和宝塔一样的服务器迁移功能

### ISSUE THREAD

**Issue by RebellionAQG** [1Panel-dev/1Panel#4308]
### 1Panel 版本

1.10.2

### 请描述您的需求或者改进建议

希望1panel能有一个和宝塔一样的服务器迁移功能，方便换服务器的时候整个迁移过去，现在没有这样的功能，服务器搬家比较困难，很多群友也面临着这个问题

### 请描述你建议的实现方案

建议参考宝塔的服务器迁移方案，只需要填写服务器IP，域名，API等信息就能直接一键迁移到新服务器上面去

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
可以进入 `面板设置` - `快照` 页面创建快照。
> 快照文件包括 1Panel 自身数据目录、应用商店已安装应用、创建的容器编排等内容。

**Comment by Shaogxhaha** [comment]
> 感谢反馈。 可以进入 - 页面创建快照。`面板设置``快照`
> 
> > 快照文件包括 1Panel 自身数据目录、应用商店已安装应用、创建的容器编排等内容。

docker的挂载目录都有吗 还是说要手动创建好对应的挂载路径呢
