### ISSUE TITLE
[FEATURE]在监控页面加上GPU信息

### ISSUE THREAD

**Issue by bai0012** [1Panel-dev/1Panel#431]
### 1Panel 版本

1.0.3

### 请描述您的需求或者改进建议

希望可以检测服务器是否含有GPU，如果有，就在监控页面显示GPU的使用量，显存使用大小等等

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会考虑支持上述需求。

**Comment by tensorboy** [comment]
有更新吗这个需求

**Comment by wanghe-fit2cloud** [comment]
> 有更新吗这个需求

好的，我们先调研一下具体方案。

**Comment by larkwins** [comment]
同求

**Comment by Daydream0929** [comment]
+1
https://github.com/XuehaiPan/nvitop

**Comment by YHSI5358** [comment]
怎么没动静了，急需

**Comment by TaroXin** [comment]
一年了，没个后续吗

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。

**Comment by larkwins** [comment]
> v1.10.3-lts 版本已发布。
@wanghe-fit2cloud 

还要专业版啊才能看GPU啊，不至于吧

**Comment by KleinerSource** [comment]
gpu又不止nvidia才有  建议 igpu 也支持现实   利用 intel_gpu_top

**Comment by adaaaaaa** [comment]
@wanghe-fit2cloud 
社区版看不到GPU相关的信息吗？
