### ISSUE TITLE
[BUG]OpenResty网站不能修改配置

### ISSUE THREAD

**Issue by Monkey-xu** [1Panel-dev/1Panel#4310]
### 联系方式

raty_xu@outlook.com

### 1Panel 版本

v1.10.2-lts

### 问题描述

![ebfb13a946d3bdcd581e6478047a9e9](https://github.com/1Panel-dev/1Panel/assets/18133858/71162d70-5312-4176-8b5f-ea913fe3c1c8)
当在OpenResty配置里面添加upstream，新建的网站将不能再被修改、查看日志和安全功能都会报错。

### 重现步骤

安装OpenResty应用，新建网站，修改配置，添加upstream

**Comment by zhengkunwang223** [comment]
后续版本修复

**Comment by wanghe-fit2cloud** [comment]
重复issue https://github.com/1Panel-dev/1Panel/issues/4258
该问题会在下个版本修复。
