### ISSUE TITLE
[BUG]OpenResty

### ISSUE THREAD

**Issue by GunnmF** [1Panel-dev/1Panel#4312]
### 联系方式

moumou.v1@foxmail.com

### 1Panel 版本

v1.10.2-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/101814544/537831fd-180a-4ba7-a803-bf3344c0688a)

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/101814544/680d5203-d959-4720-9806-de10d9747950)

**Comment by zhengkunwang223** [comment]
下个版本优化
