### ISSUE TITLE
OpenRestry版本切换

### ISSUE THREAD

**Issue by LReion** [1Panel-dev/1Panel#4313]
### 1Panel 版本

v1.10.2-lts

### 问题描述

我发现应用商店提供的openrestry的版本是：Version:1.21.4.3-0-focal，官网最新的docker镜像版本是openresty/openresty:1.25.3.1-0-focal，官网描述focal这个是在ubuntu上面构建的，然后我想换成openresty/openresty:1.25.3.1-0-bookworm-fat，也就是在debian上面构建的，但是在容器那里强制拉取镜像之后，在面板那里的版本并没有修改，保存配置也会报错。
![image](https://github.com/1Panel-dev/1Panel/assets/78899198/c642193b-0384-4203-9777-d7da692c22b8)
希望后续能够自行更换openrestry的镜像，然后能内嵌在面板里面。
![image](https://github.com/1Panel-dev/1Panel/assets/78899198/8e0f3794-73e2-4bc1-a407-eaf91a61402b)

### 重现步骤

在编排里面更换docker镜像，然后重启拉取。

**Comment by zhengkunwang223** [comment]
需要去修改应用的 docker-compose 文件
应用商店-已安装-参数-高级设置中修改

**Comment by LReion** [comment]
> 需要去修改应用的 docker-compose 文件 应用商店-已安装-参数-高级设置中修改

修改了之后显示还是原来的版本，但是实际上已经修改了吗

**Comment by LReion** [comment]
> > 需要去修改应用的 docker-compose 文件 应用商店-已安装-参数-高级设置中修改
> 
> 修改了之后显示还是原来的版本，但是实际上已经修改了吗

发现网站可以反代，但是在修改配置里面会报错。
![image](https://github.com/1Panel-dev/1Panel/assets/78899198/e5be5c4d-a82a-4309-a0b6-076eb4b9c867)

**Comment by LReion** [comment]
> > > 需要去修改应用的 docker-compose 文件 应用商店-已安装-参数-高级设置中修改
> > 
> > 
> > 修改了之后显示还是原来的版本，但是实际上已经修改了吗
> 
> 发现网站可以反代，但是在修改配置里面会报错。 ![image](https://private-user-images.githubusercontent.com/78899198/316755880-e5be5c4d-a82a-4309-a0b6-076eb4b9c867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MzYyMTIsIm5iZiI6MTcxMTQzNTkxMiwicGF0aCI6Ii83ODg5OTE5OC8zMTY3NTU4ODAtZTViZTVjNGQtYTgyYS00MzA5LWEwYjYtMDc2ZWI0YjljODY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA2NTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZjVhYTkzMTQ5NGZlMjViNzFlNTdlZjA2ZmRiMjdhMjdiYmM4NDAwYjVkY2MyMzE1YTMyNTlhMTA4MmNkMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sAxmfVPjqD1pDIkyLFddz7JrxMQ054PM1tyzAJjSyq8)

我尝试了别的docker镜像，vmware发布的bitnami/openresty:latest会报错，openresty/openresty:1.25.3.1-0-bookworm-fat这个不会报错

**Comment by wanghe-fit2cloud** [comment]
> 修改了之后显示还是原来的版本，但是实际上已经修改了吗

是的。
你可以进入 `容器` 页面查看 openresty 镜像关联的镜像，如果是最新版本就没有问题。
