### ISSUE TITLE
[FEATURE] Dataease application synchronize Clickhouse / MariaDB / PostgreSQL etc.

### ISSUE THREAD

**Issue by FangyangJz** [1Panel-dev/1Panel#4318]
### 1Panel 版本

1.10.2

### 请描述您的需求或者改进建议

请同步 Dataease 官方支持的其他常用数据库

**Comment by wanghe-fit2cloud** [comment]
这些是 DataEase 内部支持的数据源，并不是安装 DataEase 时支持 ClickHouse 等。
