### ISSUE TITLE
[BUG]1panel-v1.10.2-lts安装脚本安装不成功

### ISSUE THREAD

**Issue by ucnice** [1Panel-dev/1Panel#4319]
### 1Panel 版本

1panel-v1.10.2-lts

### 问题描述

安装脚本安装不成功

### 重现步骤

[1Panel Log]: ======================= 开始安装 =======================
设置 1Panel 安装目录（默认为/opt）：
[1Panel Log]: 您选择的安装路径为 /opt
[1Panel Log]: ... 在线安装 docker
选择延迟最低的源 https://mirrors.163.com/docker-ce，延迟为 0.445413 秒
# Executing docker install script, commit: e5543d473431b782227f8908005543bb4389b8de
+ sh -c apt-get update -qq >/dev/null
E: The repository 'http://apt.armbian.com lunar Release' does not have a Release file.
[1Panel Log]: ... 启动 docker
Failed to enable unit: Unit file docker.service does not exist.
Failed to start docker.service: Unit docker.service not found.
[1Panel Log]: docker 安装失败

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/3235
