### ISSUE TITLE
[BUG]安装应用后无法打开,界面显示界面

### ISSUE THREAD

**Issue by mokern** [1Panel-dev/1Panel#4321]
### 联系方式

1692598276@qq.com

### 1Panel 版本

v1.10.2-lts

### 问题描述

wsl debian 安装jellyfin应用，设置默认所有网卡，IP为界面登录IP，但跳转界面无法登录，显示无法访问，拒绝连接。目前排查服务器时间是上海，容器时间是美国，这个是否影响，怎么做可以正常跳转到应用界面。

### 重现步骤

暂无

**Comment by wanghe-fit2cloud** [comment]
和时区没有关系。
你可以先进入容器页面，确认一下 jellyfin 应用的容器状态和日志是否都正常。

参考社区用户提供的教程：
https://bbs.fit2cloud.com/t/topic/412

**Comment by mokern** [comment]
感谢答复
昨晚最后测试发现只能用localhost登录，检查/etc/hosts没有添加本机IP名，这个是否要添加上。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1Panel-dev/1Panel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月27日(星期三) 上午10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [1Panel-dev/1Panel] [BUG]安装应用后无法打开,界面显示界面 (Issue #4321)





 
和时区没有关系。
 你可以先进入容器页面，确认一下 jellyfin 应用的容器状态和日志是否都正常。
 
参考社区用户提供的教程：
 https://bbs.fit2cloud.com/t/topic/412
