### ISSUE TITLE
[FEATURE]请求应用商店添加即时视频聊天会议(类似腾讯会议)应用JitsiMeet

### ISSUE THREAD

**Issue by RebellionAQG** [1Panel-dev/1Panel#4324]
### 1Panel 版本

1.10.2

### 请描述您的需求或者改进建议

希望应用商店能添加类似腾讯会议的即时视频聊天应用JitsiMeet
项目地址：https://github.com/jitsi/jitsi-meet 
> 官方也放出docker部署方法

### 请描述你建议的实现方案

https://github.com/jitsi/jitsi-meet

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
官方提供的容器化项目仓库地址：https://github.com/jitsi/docker-jitsi-meet/
由于该应用部署涉及到更多的关联容器，不建议在 1Panel 应用商店中来维护。
> 可以通过 `容器` - `编排` 页面提供的创建编排功能来维护上述应用。
