### ISSUE TITLE
请测试一下php加密扩展XLoad是否能安装成功

### ISSUE THREAD

**Issue by ifacecn** [1Panel-dev/1Panel#4326]
### 1Panel 版本

1.10.2

### 问题描述

按照https://bbs.fit2cloud.com/t/topic/2073教程上传，extensions = /php/extensions/no-debug-non-zts-2019090/XLoader_Lin_php7.4_x64.so保存重载后依旧未生效，容器日志[27-Mar-2024 13:31:27] NOTICE: Finishing ...
[27-Mar-2024 13:31:27] NOTICE: exiting, bye-bye!
[27-Mar-2024 13:31:29] NOTICE: fpm is running, pid 1
[27-Mar-2024 13:31:29] NOTICE: ready to handle connections

### 重现步骤

昨天用的arm，后面发现扩展不支持arm架构，今天换了amd机器，依旧和昨天一样

### 期待的正确结果

希望官方测试一下是哪里的问题

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/4314

建议先到 XLoad 官方查找一下容器化安装方案。

先关闭该 issue 了，后续有进展再继续讨论。
