### ISSUE TITLE
[BUG] 服务器时间无法同步,报错io timeout

### ISSUE THREAD

**Issue by Radiation-pi** [1Panel-dev/1Panel#4329]
### 联系方式

1243039811@qq.com

### 1Panel 版本

v1.10.2-lts

### 问题描述

服务器时间一直不怎么准确，然后我发现面板内有时间同步功能，但点击后转圈很久跳出报错。
![8b0e6330ac139d42b4d63e5129dae10b](https://github.com/1Panel-dev/1Panel/assets/96102795/9be9c585-cdcb-49ae-a3f3-9ed352788333)
![77b4df6de4ac4fd878aa96c644b9e18e](https://github.com/1Panel-dev/1Panel/assets/96102795/cf16d609-00eb-4197-a2fe-0b845ead8bda)

### 重现步骤

应该是个人问题，点击同步即可复现

### 期待的正确结果

将面板时间与服务器时间同步

### 附加信息

![QQ截图20240327152356](https://github.com/1Panel-dev/1Panel/assets/96102795/6861d091-1643-465c-948c-8d3ed9df065b)

**Comment by wanghe-fit2cloud** [comment]
`工具箱` 页面设置的 NTP 服务器有问题，可以试一下公网的阿里服务。
