### ISSUE TITLE
[BUG]使用七牛云计划任务上传大文件夹失败，报错：token expired 7 seconds ago

### ISSUE THREAD

**Issue by lssdo12** [1Panel-dev/1Panel#4330]
### 联系方式

lssdo60@gmail.com

### 1Panel 版本

v1.10.2-lts

### 问题描述

![七牛云token过期](https://github.com/1Panel-dev/1Panel/assets/59727014/9ebae595-b19e-4885-8b24-4caf1540e610)
七牛云默认token时间太短了，长时间上传会失败。希望增加选项调整token过期时间

### 重现步骤

上传大文件，上传到七牛云的时间超过1小时

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
