### ISSUE TITLE
[FEATURE]希望建站系统新增ZBlog

### ISSUE THREAD

**Issue by itpoo** [1Panel-dev/1Panel#4335]
### 1Panel 版本

v1.10.2-lts

### 需求

很多个版本更新后依旧未见建站程序有ZBlog的身影，推荐新增Zblog能让更多ZBlog的用户更快速便捷的使用1Panel，也能帮助新手快速使用1Panel创建ZBlog

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/4253
