### ISSUE TITLE
[FEATURE]应用商店上架 supabase

### ISSUE THREAD

**Issue by CryUshio** [1Panel-dev/1Panel#4336]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

希望应用商店上架 supabase，建站必备
https://github.com/supabase/supabase/blob/master/i18n/README.zh-cn.md

**Comment by CryUshio** [comment]
此工具是鉴权和数据库管理工具，包含各种平台的 OAuth，官方已有 docker 方案，可在仓库 docker 目录下查看

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
官方提供的容器化部署方案：
https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml

由于该应用部署涉及到更多的关联容器，不建议在 1Panel 应用商店中来维护。
> 可以通过 `容器` - `编排` 页面提供的创建编排功能来维护上述应用。
