### ISSUE TITLE
[FEATURE]商城内有的应用，部署特别方便，怎么快速添加其他应用？

### ISSUE THREAD

**Issue by AlwaysOnline** [1Panel-dev/1Panel#4343]
### 1Panel 版本

V1.10.2

### 请描述您的需求或者改进建议

目前Appstore内已有的应用，部署起来特别方便。

但不在商城内的应用，怎么部署方便？

希望给个操作手册。

**Comment by wanghe-fit2cloud** [comment]
- [官方文档 - 添加你想要的应用](https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8)
- [论坛求助 - 1Panel 本地应用创建技巧及第三方应用库举例](https://bbs.fit2cloud.com/t/topic/640)
