### ISSUE TITLE
[BUG] 安装jenkins, 命名校验不正确

### ISSUE THREAD

**Issue by liufei20151013** [1Panel-dev/1Panel#435]
### 联系方式

liufei@fit2cloud.com

### 1Panel 版本

v1.0.3

### 问题描述

安装jenkins, 命名校验不正确: 不支持中划线

### 重现步骤

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/15103510/228409573-53d9ef3e-073b-458e-b542-69e40af81911.png">

**Comment by zhengkunwang223** [comment]
中划线支持 不支持小数点
