### ISSUE TITLE
[FEATURE]希望增加openResty代理转发tcp/udp等功能

### ISSUE THREAD

**Issue by meng-plus** [1Panel-dev/1Panel#4351]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

http代理很方便添加，但是有些需求我想添加tcp转发功能，确无从下手
我对他不太熟悉，查阅资料  看他是完全支持的，有没有建议方便我在当前情况下添加

**Comment by wanghe-fit2cloud** [comment]
当前版本可以进入 `网站设置` 页面来手动修改配置，是支持的。
我们也会在后续版本考虑是否支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
网站端口转发相关需求的讨论，我们统一汇总到该 issue [#5135](https://github.com/1Panel-dev/1Panel/issues/5135)
