### ISSUE TITLE
[FEATURE] 新修改的重启服务器按钮位置似乎太隐蔽了？

### ISSUE THREAD

**Issue by lyimoexiao** [1Panel-dev/1Panel#4352]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

看到PR有提交修改重启服务器按钮的位置，但是放到工具箱的右上角内也未必太隐蔽了吧。。。而且貌似对于需要快速登录面板重启服务器的情况貌似不是很友好（虽然一般是直接ssh上去直接reboot的），但是加回去貌似体验更好？

### 请描述你建议的实现方案

建议重新在首页加入重启服务器、重启面板按钮

### 附加信息

#4221

**Comment by wanghe-fit2cloud** [comment]
是的，我们将重启面板和服务器的按钮放到了 `工具箱` 页面，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/96019bdc-a952-4e8a-994f-5eec0888d206)

> 移动位置抽主要原因：主要是考虑到重启是低频操作，也存在一定的风险。
