### ISSUE TITLE
[FEATURE]新增可迁移安装目录功能

### ISSUE THREAD

**Issue by Monkey-xu** [1Panel-dev/1Panel#4353]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

希望能够增加一个可以迁移1Panel的功能。

**Comment by wanghe-fit2cloud** [comment]
- A 主机：进入 `面板设置` - `快照` 页面，创建快照；
- B 主机：进入 `面板设置` - `快照` 页面，同步快照，选择创建快照时相同的备份账号；
- 选择目标文件进行恢复操作即可。
