### ISSUE TITLE
[BUG]在文件管理中上传文件夹时，文件夹权限被设置为0750

### ISSUE THREAD

**Issue by zdzym** [1Panel-dev/1Panel#4362]
### 1Panel 版本

v1.10.2-lts

### 问题描述

在文件管理中上传文件夹时，文件夹权限被设置为0750，这会导致php-fpm等应用无法访问这些文件夹，花费大量时间进行排错。在文件管理中直接新建文件夹，默认权限为0755.

### 重现步骤

主机--文件--上传--上传文件夹，上传后文件夹权限为0750

### 期待的正确结果

和创建文件夹的行为一致，即0755

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
目前版本确实存在上述问题，我们会在近期版本优化此处功能（上传文件夹权限与父目录权限保持一致）。

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
