### ISSUE TITLE
[BUG]定时计划 shell脚本，选择“在容器中执行”，然后选择了某个容器，但是发现脚本并没有在容器内执行。

### ISSUE THREAD

**Issue by beautifulBoys** [1Panel-dev/1Panel#4363]
### 联系方式

1298947916@qq.com

### 1Panel 版本

v1.10.2-lts

### 问题描述

<img width="822" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/24930325/16bae6f3-a566-4396-a8f9-48e3dc4653b5">
如图配置，ls后发现只有2个log文件，并不是在我的mongo容器里。
<img width="981" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/24930325/d0585b23-995d-47f5-bf3b-e2956227a81b">

### 重现步骤

1. 配置定时计划，选择shell，并选择在容器内执行，选择好容器。
2. 手动触发一下即可，查看执行日志。

### 期待的正确结果

脚本正确的在容器内运行。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by ssongliu** [comment]
在容器中执行等价于增加了 docker exec contanerxx 命令，所以想要实现上面这种效果，可以使用下面这个命令
bash -c 'pwd && ls'

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
