### ISSUE TITLE
[FEATURE] 后台使用命令行开启面板https

### ISSUE THREAD

**Issue by bddjr** [1Panel-dev/1Panel#4365]
### 1Panel 版本

1.10.2

### 请描述您的需求或者改进建议

我希望能做到使用1pctl直接开启https，而不是经过明文http登录了再开启。  

这可能是一个安全问题，但面板默认明文http，因此可能还不至于登记为安全问题。  

### 请描述你建议的实现方案

用户首先在 `/opt/1panel/secret` 下放置 `server.crt` 与 `server.key` ，然后运行命令

```
1pctl enable https
```

### 附加信息

我看官方文档没有这个，看源码发现改这东西要操作数据库，甚至不能直接修改conf文件（恼）

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by maifuwa** [comment]
请问这个功能加上了吗？

**Comment by wanghe-fit2cloud** [comment]
> 请问这个功能加上了吗？

还未添加到近期迭代计划。
可以随时关注 milestone，会包含每个版本的大概内容。

**Comment by bddjr** [comment]
能不能别什么都往数据库里写，这又不是同一个服务器多个用户的单独配置文件

**Comment by bddjr** [comment]
这个功能是不是也要等到v2

**Comment by wanghe-fit2cloud** [comment]
后续版本不再考虑支持该需求。
