### ISSUE TITLE
[BUG]无法安装PHP56

### ISSUE THREAD

**Issue by fjk0618** [1Panel-dev/1Panel#4369]
### 联系方式

fjk0618@gmail.com

### 1Panel 版本

全版本

### 问题描述

香港服务器、安装PHP5环境失败

### 重现步骤

默认没选什么杂七杂八的扩展
[build.log](https://github.com/1Panel-dev/1Panel/files/14818668/build.log)

**Comment by wanghe-fit2cloud** [comment]
尝试切换一下 `PHP 扩展源`
> 本地测试环境使用 `中国科学技术大学` 源没有复现问题。
