### ISSUE TITLE
[BUG] 手动导入的证书请求一直不成功

### ISSUE THREAD

**Issue by aarcore** [1Panel-dev/1Panel#4379]
### 1Panel 版本

v1.10.2-lts

### 问题描述

手动导入的证书443一直不成功

1: 在轻量应用服务器，使用Let's Encrypt生成证书；
2: 1Panel 安装wordpress，然后安装openresty，关联wordpress网站；
3: 网站中设置https，手动导入 1 生成的证书；
4: curl http可以正常访问，https 一直不通报错“curl: (7) Failed to connect to aicete.com port 443 after 16 ms: Couldn't connect to server”；

### 重现步骤

如问题描述中步骤

**Comment by zhengkunwang223** [comment]
443 端口放开了吗

**Comment by aarcore** [comment]
> 443 端口放开了吗

🙏 解决了，1panel忘记开放了。
