### ISSUE TITLE
[FEATURE]希望增加容器更新的功能

### ISSUE THREAD

**Issue by tsylqw** [1Panel-dev/1Panel#438]
### 1Panel 版本

1.0.3

### 请描述您的需求或者改进建议

容器创建后无法升级，只能删除后重新创建，希望增加一个检查最新镜像并一键重建的功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持该需求。

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
