### ISSUE TITLE
关于网站名称的显示建议。[FEATURE]

### ISSUE THREAD

**Issue by RuiKylin** [1Panel-dev/1Panel#4383]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

本地服务器有**多个网络**出口，部分web服务需要 **指定ip和端口**。
在创建网站为 **ip:port** 形式，网站选项卡显示内容都为 ip，无法直接看到端口。使用备注的方法会有显示不全的情况。
当服务多起来后管理查看困难。

### 请描述你建议的实现方案

请求添加自定义显示网站名称或者显示端口，或者增加信息显示标签以显示完整内容。

### 附加信息

![截屏2024-04-01 20.22.21.png](https://s1.locimg.com/2024/04/01/24d0dd7983219.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/3726
