### ISSUE TITLE
二次验证登录问题[BUG]

### ISSUE THREAD

**Issue by Amigo-x** [1Panel-dev/1Panel#4385]
### 1Panel 版本

v1.10.2

### 问题描述

登录输入二次验证码时，正确的验证码输入完验证失败，
多输入几位再按回退键删除到6位时，又能验证通过，频率还挺高（前提：6位的验证码是正确的）
有时输入完6位自动校验失败，多点击按钮就又能验证通过（前提：6位的验证码正确的）

### 重现步骤

最明显的是，输入较快时，更容易复现

### 期待的正确结果

建议优化

**Comment by ssongliu** [comment]
感谢反馈，可以同步一下服务器时间后重试。

**Comment by Amigo-x** [comment]
谢谢，刚检查了下服务器时间，好像确实有时差，我更新下再观察观察哈
