### ISSUE TITLE
[FEATURE]增加指定容器固定IP的功能

### ISSUE THREAD

**Issue by beijingtl** [1Panel-dev/1Panel#4386]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

无论是基于应用商店，还是自定义docker安装的容器。在“容器”的管理面板中，都能配置固定IP。

### 请描述你建议的实现方案

在容器的配置界面中，网络下面，增加一个配置输入框即可。
![QQ截图20240402110425](https://github.com/1Panel-dev/1Panel/assets/5467039/59a81f00-a6c6-4b12-8ecc-e2837cc92cfa)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
重复 #3663
