### ISSUE TITLE
[FEATURE] 增加对其它数据库的管理支持

### ISSUE THREAD

**Issue by 7980963** [1Panel-dev/1Panel#439]
### 1Panel 版本

1.03

### 请描述您的需求或者改进建议

我在安装MariaDB后，发现无论是应用商店中的phpMyAdmin目前无法选择MariaDB导致无法安装，1Panel提供的数据库管理也看不到MariaDB，希望在之后的版本中添加对MariaDB等其它数据库的兼容。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
