### ISSUE TITLE
[FEATURE]docker编排希望显示运行状态

### ISSUE THREAD

**Issue by lssdo12** [1Panel-dev/1Panel#4395]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

容器能看到状态显示“已运行”之类的，编排没有状态显示。现在基本都是docker compose运行了，很少看容器部分，都是直接看编排的

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
可以点击 `编排列表` - `名称`，进入二级页面来查看包含容器状态。

> 由于存在单个编排包含多个容器的情况，会导致无法界定编排的具体状态。
因此，还是需要用户进入二级页面查看具体容器状态。
