### ISSUE TITLE
[BUG] 文件编辑 自动换行 设定无效

### ISSUE THREAD

**Issue by JinyuZhang** [1Panel-dev/1Panel#4397]
### 联系方式

18943657893@163.com

### 1Panel 版本

v1.10.2-lts

### 问题描述

文件编辑 自动换行 设定无效

### 重现步骤

打开文件进行编辑,将自动换行选择为禁用,点击确定按钮之后再打开,自动换行选项仍为禁用,但是显示内容自动换行了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
