### ISSUE TITLE
[FEATURE]docker编排希望显示运行状态，同时展开显示对应容器，类似 Docker Desktop

### ISSUE THREAD

**Issue by lssdo12** [1Panel-dev/1Panel#4404]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

希望能和 Docker Desktop 一样，能显示编排未运行、不完全运行、完全运行等状态。最好能在编排页面显示容器而不需要点进去
![docker编排](https://github.com/1Panel-dev/1Panel/assets/59727014/35c6fdbb-a5f4-4db9-b003-de597bddf784)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述建议。

**Comment by wanghe-fit2cloud** [comment]
v1.10.16 版本已发布。
