### ISSUE TITLE
[BUG]把之前的网站强制删除之后重新部署出现的代号已存在

### ISSUE THREAD

**Issue by RebellionAQG** [1Panel-dev/1Panel#4406]
### 联系方式

1084164236@qq.com

### 1Panel 版本

v1.10.2-lts

### 问题描述

把之前的网站强制删除之后重新部署出现的代号已存在，这个代号没办法删除吗，我看文件夹已经没有了这个网站的文件夹了，怎么还是显示代号以存在，要怎么样才能让之前的代号删除干净
![QQ截图20240405010732](https://github.com/1Panel-dev/1Panel/assets/126437353/1fbc9ca5-77d0-46ae-afd1-8b766a5ce265)

### 重现步骤

强制删除了之前部署的网站，现在准备搭建回去，但是就显示代号已存在

**Comment by RebellionAQG** [comment]
我把/opt/1panel/apps/openresty/openresty/conf/conf.d/box.molei.fun.conf路径下的conf文件删除了还是不行
![image](https://github.com/1Panel-dev/1Panel/assets/126437353/44d8d713-1284-4449-9ea6-031ba04ff3b2)

**Comment by RebellionAQG** [comment]
我参考了  https://github.com/1Panel-dev/1Panel/issues/1363     的方法。

把/opt/1panel/apps/openresty/openresty/conf/conf.d/路径下对应网站代号名字conf文件删除了还是不行，还是提示代号已存在，
![image](https://github.com/1Panel-dev/1Panel/assets/126437353/bc22e5b1-3f65-4344-b189-bb2701588096)

**Comment by zhengkunwang223** [comment]
代号是网站用来创建文件夹的名称 不能重复
代号已存在 是你已经有网站用了这个代号 一般是域名 你检查你的其他网站 
在网站设置-基本-其他里面查看

**Comment by RebellionAQG** [comment]
那这个代号就没有办法再重新设置一模一样的吗，就算网站删除了和文件夹删除了，都创建不了了只能另起一个代号了嘛？

**Comment by zhengkunwang223** [comment]
> 那这个代号就没有办法再重新设置一模一样的吗，就算网站删除了和文件夹删除了，都创建不了了只能另起一个代号了嘛？

每个网站一个代号 
出现这个错误 是因为你现在还有网站用了这个代号
检查你现有的网站  或者新建网站的时候改个代号

**Comment by xiaoxinpro** [comment]
> > 那这个代号就没有办法再重新设置一模一样的吗，就算网站删除了和文件夹删除了，都创建不了了只能另起一个代号了嘛？
> 
> 每个网站一个代号 出现这个错误 是因为你现在还有网站用了这个代号 检查你现有的网站 或者新建网站的时候改个代号

@zhengkunwang223 确实是有网站代号重复导致的问题，是不是可以在“代号已存在”的提示中添加跟哪个网站代号重复了，因为网站比较多，而且列表中没有显示代号，查找起来比较难。

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> > Then there is no way to reset this codename to be exactly the same. Even if the website is deleted and the folder is deleted, it cannot be created and I can only create a new codename?
>
> One codename for each website. This error occurs because you still have a website using this codename. Check your existing website or change the codename when creating a new website.

@zhengkunwang223 It is indeed a problem caused by duplicate website code names. Is it possible to add which website code is duplicated in the "code name already exists" prompt? Because there are many websites and the code names are not displayed in the list, it is difficult to find.
