### ISSUE TITLE
[BUG] 创建网站使用运行环境时容器提示文件不存在

### ISSUE THREAD

**Issue by Daiyangcheng** [1Panel-dev/1Panel#4407]
### 联系方式

QQ：3143105972

### 1Panel 版本

v1.10.2-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/48477757/b1c94599-6f4a-42c5-a52a-6ebe92bc6d67)
![image](https://github.com/1Panel-dev/1Panel/assets/48477757/a167faaf-6b85-455a-a788-636e30125c69)

### 重现步骤

在创建网站时选择运行环境类型，进行正常的创建流程

**Comment by zhengkunwang223** [comment]
是什么版本的运行环境呢？

**Comment by Daiyangcheng** [comment]
PHP 8.1.23

**Comment by wanghe-fit2cloud** [comment]
> PHP 8.1.23

在 `应用商店` 页面中，点击右上角的 `更新应用列表` 按钮，等待同步完成后，转到 `运行环境` 页面，并创建 `8.1.27` 版本。
