### ISSUE TITLE
[BUG] port external access failure

### ISSUE THREAD

**Issue by M0dred** [1Panel-dev/1Panel#4409]
### 1Panel 版本

v1.10.2-lts

### 问题描述

Can not enable MySQL port external access, docker running failure

### 重现步骤

<img width="717" alt="Screenshot 2024-04-06 at 10 48 00 am" src="https://github.com/1Panel-dev/1Panel/assets/10797376/e8934a6e-90e1-4157-81a6-de6c0b469ff4">

### 相关日志输出

```shell
stderr: The Compose file '/opt/1panel/apps/mysql/mysql/docker-compose.yml' is invalid because: services.mysql.ports contains an invalid type, it should be a number, or an object
```

**Comment by zhengkunwang223** [comment]
Check your docker-compose version 
<img width="509" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/31820853/43ab1390-3e71-4c31-aa1d-e9750d629d89">

**Comment by wanghe-fit2cloud** [comment]
Upgrade the docker-compose on the 1Panel server to the latest version. 
Here is the download link: 
https://github.com/docker/compose/releases
