### ISSUE TITLE
[BUG]应用商店打开时弹出服务异常，已安装页面显示为空（已安装页面下分类页面可以显示安装软件）

### ISSUE THREAD

**Issue by spyfamily** [1Panel-dev/1Panel#4412]
### 1Panel 版本

v1.10.2-lts

### 问题描述

应用商店中安装reader时，修改了docker-compose导致安装失败。再次进入应用商店是弹出服务异常，点击已安装，页面显示为空，已安装页面下细分除了reader所在分类均可显示已安装应用。浏览器日志如下，面板操作日志仅显示安装【appkey】-【reader】失败。此外在商店中安装reader副本（和原来命名不同，端口不同（原端口被占用），可安装，但无法在商店显示，容器等均正常启动）

### 重现步骤

无

### 相关日志输出

```shell
index-d1c15487.js:169 
        
        
POST https://192.168.10.9:34304/api/v1/apps/installed/search 500 (Internal Server Error)
（匿名） @ index-d1c15487.js:169
xhr @ index-d1c15487.js:169
pv @ index-d1c15487.js:171
Promise.then（异步）
_request @ index-d1c15487.js:172
request @ index-d1c15487.js:171
（匿名） @ index-d1c15487.js:172
（匿名） @ index-d1c15487.js:167
post @ index-998447b5.js:1
g @ app-6248dc7a.js:1
B @ index-07b0a200.js:1
G @ index-07b0a200.js:1
a.onClick.h.<computed>.h.<computed> @ index-07b0a200.js:1
Oo @ index-d1c15487.js:16
Hu @ index-d1c15487.js:16
QA @ index-d1c15487.js:16
handleClick @ index-d1c15487.js:51
Oo @ index-d1c15487.js:16
Hu @ index-d1c15487.js:16
n @ index-d1c15487.js:28


installed:1 Uncaught (in promise) jt {message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}
XMLHttpRequest.send（异步）
（匿名） @ index-d1c15487.js:169
xhr @ index-d1c15487.js:169
pv @ index-d1c15487.js:171
Promise.then（异步）
_request @ index-d1c15487.js:172
request @ index-d1c15487.js:171
（匿名） @ index-d1c15487.js:172
（匿名） @ index-d1c15487.js:167
post @ index-998447b5.js:1
g @ app-6248dc7a.js:1
B @ index-07b0a200.js:1
G @ index-07b0a200.js:1
a.onClick.h.<computed>.h.<computed> @ index-07b0a200.js:1
Oo @ index-d1c15487.js:16
Hu @ index-d1c15487.js:16
QA @ index-d1c15487.js:16
handleClick @ index-d1c15487.js:51
Oo @ index-d1c15487.js:16
Hu @ index-d1c15487.js:16
n @ index-d1c15487.js:28
index-d1c15487.js:169
```

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/103571476/338c5c7b-6fa2-4a3c-a0d5-50201c06f152)
![image](https://github.com/1Panel-dev/1Panel/assets/103571476/2172bfdd-48e9-4926-b4c7-fd57fc047fc8)
![image](https://github.com/1Panel-dev/1Panel/assets/103571476/8ca1498e-1c5a-48ee-b63b-a11c56b16955)
![image](https://github.com/1Panel-dev/1Panel/assets/103571476/a93b015f-2a00-4047-8013-51ab712e37a0)

**Comment by spyfamily** [comment]
系统重启 面板重启均无作用，也尝试过1panel自带的垃圾清理清空缓存也无用

**Comment by zhengkunwang223** [comment]
修改了那些参数呢？

**Comment by spyfamily** [comment]
环境变量添加了时区，指定了容器ip
networks:
    1panel-network:
        ipv4_address: 172.18.0.100
environment:
    TZ: Asia/Shanghai

**Comment by spyfamily** [comment]
安装时创建了应用目录/opt/1panel/apps/reader/reader
docker镜像好像（不确定）也没有下载成功，但不是网络问题，因为已经配置了镜像加速，且可以安装其他应用
另外修改时有报错，后续我忘了是在   TZ: Asia/Shanghai  前加-还是直接删了...

**Comment by zhengkunwang223** [comment]
Refs https://github.com/1Panel-dev/1Panel/pull/4431
经过验证 是 docker-compose v2.24 版本的 BUG 
后续版本修复 
你可以先升级 docker-compose 版本到 v2.26.1

**Comment by spyfamily** [comment]
好的，感谢，辛苦了。
另外目前升级docker-compose最新版本仍然无法解决服务错误问题。若有其他朋友遇到相同问题，可进行操作
目前暂时处理可修改1panel.db文件中的相关数据
1panel.db文件目录：/opt/1panel/db
删除库中数据表app_installs中的相关数据即可（删前请备份1panel.db）

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
