### ISSUE TITLE
[FEATURE]能不能增加 MongoDB 低版本，目前版本太新了。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4413]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

如题。
起码有个 6 的。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本考虑支持。

**Comment by wanghe-fit2cloud** [comment]
已经推送 6.0.14 版本。
> 同时支持 6.x 和 7.x 版本。
