### ISSUE TITLE
【FEATURE】能够支持一下upstream的配置

### ISSUE THREAD

**Issue by cc4dogman** [1Panel-dev/1Panel#4416]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

目前控制台无法配置负载均衡，直接修改源文件增加upstream配置，不管加在哪个地方，都会报服务器错误

### 请描述你建议的实现方案

建议增加源文件配置方式，解析不报错

**Comment by zhengkunwang223** [comment]
重复 https://github.com/1Panel-dev/1Panel/issues/4258
