### ISSUE TITLE
[BUG]通过应用商店安装应用，升级覆盖原有配置文件

### ISSUE THREAD

**Issue by wang-qa** [1Panel-dev/1Panel#4423]
### 1Panel 版本

v1.10.2-lts

### 问题描述

1. 应用商店容器更新覆盖原配置

### 重现步骤

1. 安装portainer，修改配置文件为，指定数据卷
![image](https://github.com/1Panel-dev/1Panel/assets/58168764/46987e24-27b3-4bc8-8131-271324c888ed)
2. 从商店更新该容器
3. 重新登录portainer

### 期待的正确结果

更新容器应保留用户配置，或以用户配置重建应用

### 附加信息

无法从外部配置存储卷，只能从yaml中修改
或者建立docekr后修改docker配置

![image](https://github.com/1Panel-dev/1Panel/assets/58168764/1aea5b9f-3f5b-4646-a724-c74ca9f18a0d)

![image](https://github.com/1Panel-dev/1Panel/assets/58168764/bd6ad4a6-65ac-48f6-960a-e0a1d73f6a6d)

**Comment by wang-qa** [comment]
且在商店的配置中指定 容器卷，
在容器页面，编辑该容器，未自动识别该挂载卷

**Comment by wanghe-fit2cloud** [comment]
> 且在商店的配置中指定 容器卷，
> 在容器页面，编辑该容器，未自动识别该挂载卷

https://github.com/1Panel-dev/1Panel/issues/4387

**Comment by wanghe-fit2cloud** [comment]
> 更新容器应保留用户配置，或以用户配置重建应用

应用升级时兼容之前修改的 compose 文件的需求，统一汇总到该 issue [#3801](https://github.com/1Panel-dev/1Panel/issues/3801)
