### ISSUE TITLE
[FEATURE] 文档过时

### ISSUE THREAD

**Issue by DSLZL** [1Panel-dev/1Panel#4425]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

1panel官方文档太旧了，例如我在[基础设置](https://1panel.cn/docs/user_manual/websites/website_config_basic/)里查找有关防盗链的相关信息时，不仅没有此说明，而且还只有几个基础介绍，其他更新的功能一个没有，配图也是很久以前的

### 请描述你建议的实现方案

那肯定是实时更新文档到最新啊，为什么你们更新程序却不更新相关的使用文档？

**Comment by wanghe-fit2cloud** [comment]
目前暂时无法投入足够的精力来维护文档，后续可能会进行同步更新。
如果你在使用过程中遇到问题，可以通过 GitHub Issue 反馈。

文档项目地址为：https://github.com/1Panel-dev/docs，也欢迎你提交 Pull Request。
