### ISSUE TITLE
[FEATURE]1pctl user-info 命令返回实际 IP

### ISSUE THREAD

**Issue by wan92hen** [1Panel-dev/1Panel#4432]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

建议 `1pctl user-info` 命令返回的面板地址，像安装脚本那样直接返回动态获取的内、外网地址，便于用户直接复制地址进行访问。

![image](https://github.com/1Panel-dev/1Panel/assets/27671436/6697d11b-47e5-4ff9-8c66-aa4a3fbe5c00)

**Comment by wanghe-fit2cloud** [comment]
需要在 `面板设置` 页面手动设置 `服务器地址`。
> 系统初始化后没有将服务器地址记录数据库。
