### ISSUE TITLE
[BUG]urgent：openresty升级之后无法启动

### ISSUE THREAD

**Issue by justincnn** [1Panel-dev/1Panel#4433]
### 1Panel 版本

v1.10.2-Its

### 问题描述

在应用商店升级openresty之后，发现无法启动，

![](https://s2.loli.net/2024/04/08/9X6tuVnxpqS2COc.png)

### 重现步骤

在应用商店升级openresty之后，发现无法启动，

### 期待的正确结果

正常运行

**Comment by wanghe-fit2cloud** [comment]
1、提供一下 OpenResty 升级前后的具体版本号。
> 应用商店近期没有推送过 OpenResty 版本更新，你是通过编辑参数手动修改的镜像版本吗？

2、容器列表可以查看容器状态和日志。

**Comment by justincnn** [comment]
> 1、提供一下 OpenResty 升级前后的具体版本号。
> 
> > 应用商店近期没有推送过 OpenResty 版本更新，你是通过编辑参数手动修改的镜像版本吗？
> 
> 2、容器列表可以查看容器状态和日志。

你好，感谢回复，目前的版本为：：1.21.4.3-0-focal

系统日志为空，无法查看，

我删除重新安装也不行，请问，除了重装1panel外，有其他的方案么？

![](https://s2.loli.net/2024/04/09/QG8ldI6T7BYumyA.png)

**Comment by wanghe-fit2cloud** [comment]
> 系统日志为空，无法查看，

可以进入容器列表，查看 OpenResty 的日志。如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/b95ac15a-0cf6-441b-8e61-12fd7d579c68)

**Comment by justincnn** [comment]
> > 系统日志为空，无法查看，
> 
> 可以进入容器列表，查看 OpenResty 的日志。

你好，这里的日志就是空的：

![](https://s2.loli.net/2024/04/09/SQkpjFWiZlBcOGT.png)

**Comment by wanghe-fit2cloud** [comment]
> ![](https://camo.githubusercontent.com/59453545874f37572ea70c8854651d60d32ef4c704ae66a38f35238b9ecb965d/68747470733a2f2f73322e6c6f6c692e6e65742f323032342f30342f30392f5147386c64493654374259756d79412e706e67)

将鼠标悬浮至 `异常` 右侧到错误图标上，有提示信息吗？

**Comment by justincnn** [comment]
> > ![](https://camo.githubusercontent.com/59453545874f37572ea70c8854651d60d32ef4c704ae66a38f35238b9ecb965d/68747470733a2f2f73322e6c6f6c692e6e65742f323032342f30342f30392f5147386c64493654374259756d79412e706e67)
> 
> 将鼠标悬浮至 `异常` 右侧到错误图标上，有提示信息吗？

只是说，查看日志，但是日志又没有内容：

![](https://s2.loli.net/2024/04/09/Hx3BgRMhCfWJkrF.png)

**Comment by wanghe-fit2cloud** [comment]
麻烦提供一下邮箱，我们远程看一下你的环境：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/7a71aaf1-dbc7-4b4d-ad22-25c42cf52877)

**Comment by justincnn** [comment]
你好，我的邮箱是justincnn@gmail.com.谢谢

**Comment by wanghe-fit2cloud** [comment]
进入 1Panel 服务器，通过 `docker inspect` 命令得到错误信息，是因为服务器没有 `/etc/localtime` 文件导致的挂载失败。
可以在安装应用时手动删除该挂载项，也可以尝试软链等方式生成 localtime 文件。
