### ISSUE TITLE
[BUG]修改运行目录后未完整展示目录名称

### ISSUE THREAD

**Issue by itpoo** [1Panel-dev/1Panel#4434]
### 1Panel 版本

v1.10.2-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/165099803/f8456ab3-d902-4755-8503-920650d571cb)

### 重现步骤

网站目录-运行目录-选择目录后-保存并加载-未显示目录名称

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
已知问题 https://github.com/1Panel-dev/1Panel/issues/4280 ，我们会在近期版本修复。
