### ISSUE TITLE
[BUG]监控功能，不展示流量

### ISSUE THREAD

**Issue by meng-plus** [1Panel-dev/1Panel#4436]
### 1Panel 版本

v1.10.2-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/37764731/df1faf18-e07e-410b-aa0f-bfe5649598c4)
数据全是0

### 重现步骤

打开任意docker 的监控均可看到

### 期待的正确结果

正常显示流量数值

**Comment by wanghe-fit2cloud** [comment]
1Panel 使用的 docker 官方 sdk 获取的监控数据，在本地测试环境未复现上述问题，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/aa8caa1e-0a47-40e7-ac18-489f4595f77d)

你可以进入 `主机` - `终端` 页面，手动执行 `docker stats` 命令查看具体结果。
