### ISSUE TITLE
[FEATURE]  能提供解压加密压缩包功能

### ISSUE THREAD

**Issue by qingpx** [1Panel-dev/1Panel#4437]
### 1Panel 版本

1.10.2 lts

### 请描述您的需求或者改进建议

我没找到在服务器支持web ui 解压加密压缩包的软件，本身是把1Panel当作半个网盘来用的，所以建议。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，在文件列表解压文件时，给用户提供一个密码输入框是不是就能满足上述需求？

**Comment by qingpx** [comment]
对，就是类似win  7z 解压那样，有密码，弹出密码窗口后输入密码解压，无密码，直接解压就行,

**Comment by wanghe-fit2cloud** [comment]
> 对，就是类似win 7z 解压那样，有密码，弹出密码窗口后输入密码解压，无密码，直接解压就行,

收到，我们后续版本先调研一下可行性方案。

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
