### ISSUE TITLE
[FEATURE]建议增加 sso 单点登录应用

### ISSUE THREAD

**Issue by keheran520** [1Panel-dev/1Panel#4447]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

能增加一个maxkey的sso单点登录系统的应用嘛

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，我们主要以项目的 star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有约 1 万 star 的开源项目，望理解。

**Comment by wanghe-fit2cloud** [comment]
可以参考论坛中这篇文章，将应用制作为本地应用使用：
https://bbs.fit2cloud.com/t/topic/640/

**Comment by TURBOyan** [comment]
建议增加 sso 单点登录应用，比如 https://github.com/authelia/authelia ，star 超过2万+；
或者 https://github.com/keycloak/keycloak ，star也超过2w+
建议 1Panel 也支持 sso 单点登录

**Comment by wanghe-fit2cloud** [comment]
> 建议增加 sso 单点登录应用，比如 https://github.com/authelia/authelia ，star 超过2万+； 或者 https://github.com/keycloak/keycloak ，star也超过2w+ 建议 1Panel 也支持 sso 单点登录

感谢反馈，我们会在后续版本考虑上架。
