### ISSUE TITLE
.1panel_clash 回收站文件夹删除文件增加提示信息。

### ISSUE THREAD

**Issue by hsjgit** [1Panel-dev/1Panel#4450]
### 1Panel 版本

v1.10.2-lts

### 问题描述

进入到/.1panel_clash这个文件夹，删除其中一个文件之后，打开回收站，恢复刚刚删除的问价返回源目录不存在

### 重现步骤

主机》文件 /.1panel_clash 这个里面随便删除一个文件，打卡回收站恢复刚刚删除的文件

### 期待的正确结果

删除 /.1panel_clash 这个文件夹里的文件的时候提一下这个是回收站文件夹，删除后无法灰度。或者可以让我恢复

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述功能。

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
