### ISSUE TITLE
[BUG]  创建php运行环境时，提示 服务内部错误: yaml: unmarshal errors:\n line 1: cannot unmarshal !!str \u003c?xml v... into map[string]interface {}

### ISSUE THREAD

**Issue by LintonGo** [1Panel-dev/1Panel#4451]
### 1Panel 版本

v1.10.2-lts

### 问题描述

创建php运行环境，提示 
{
    "code": 500,
    "message": "服务内部错误: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `\u003c?xml v...` into map[string]interface {}",
    "data": null
}

### 重现步骤

已经有一个运行环境在正常运行，想再创建一个网站的运行环境，无法创建成功
已经尝试过：升级1Panel版本，重启服务器都不行 
                     新建一个其他php版本的运行环境（这个可以成功），但只要切换到已经在用的版本，就无法再创建成功

**Comment by LintonGo** [comment]
也无法切换php版本，切换后提示切换成功，再刷新后还是老版本

**Comment by zhengkunwang223** [comment]
有一些 PHP 旧的版本已经不维护了 这时候再去创建那个版本会获取不到文件
