### ISSUE TITLE
[FEATURE]  docker run 命令 转换为compose.yaml

### ISSUE THREAD

**Issue by qingpx** [1Panel-dev/1Panel#4452]
### 1Panel 版本

1.10.2 lts

### 请描述您的需求或者改进建议

应用商店已经有类似功能的docker了（Dockge),但是这需要多安装一个docker ，所以能自带那就很方便了。

**Comment by wanghe-fit2cloud** [comment]
是的，在应用商店中已经上架了 Dockge。
我们也会在后续版本考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
`docker run` 命令可视化相关需求的讨论，统一汇总到该 issue #3463
