### ISSUE TITLE
[BUG]删除$0命名的目录会删除上级目录无法还原

### ISSUE THREAD

**Issue by freewebcode** [1Panel-dev/1Panel#4453]
### 1Panel 版本

v1.10.2-lts

### 问题描述

面板文件管理里，如果目录下有$0  $1 之类命名的文件夹，删除该类文件夹会报错，多点几次删除会连上级目录一并删除，并且回收站无法还原，实际确实进入回收站目录了，可以手动移过去

### 重现步骤

按照说明操作100%复现

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
已复现上述问题，我们会在近期版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
