### ISSUE TITLE
[FEATURE] 网站配置里面可以新增添加FTP账号密码吗?

### ISSUE THREAD

**Issue by maxbad** [1Panel-dev/1Panel#4455]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

网站配置里面可以直接添加FTP账号密码, 登录FTP就是网站的index目录,这样可以直接上传网站代码了.

**Comment by wanghe-fit2cloud** [comment]
可以参考论坛中这篇帖子，结合应用商店中的 SFTPGo 来搭配网站一起使用：
https://bbs.fit2cloud.com/t/topic/4039

> 由于 1Panel 系统不支持 FTP 管理功能，所以近期暂未规划上述功能。
