### ISSUE TITLE
Ollama WebUI 安装过慢

### ISSUE THREAD

**Issue by XiangwanGuan** [1Panel-dev/1Panel#4457]
### 1Panel 版本

v1.10.2-lts

### 问题描述

Ollama WebUI 安装过慢，甚至无法安装，加速地址已配置，更换Image地址为ghcr.nju.edu.cn/open-webui/open-webui:main后迅速安装完成。

### 重现步骤

重建Ollama WebUI即可，腾讯云。

**Comment by wanghe-fit2cloud** [comment]
是因为 1Panel 服务器 pull 镜像超时导致的，可以先手动拉取镜像，之后再来安装应用。
> 不建议修改应用镜像，后续可能出现由于镜像不同导致升级失败等情况。

```shell
docker pull ghcr.io/open-webui/open-webui:main
```

**Comment by XiangwanGuan** [comment]
> 是因为 1Panel 服务器 pull 镜像超时导致的，可以先手动拉取镜像，之后再来安装应用。
> 
> > 不建议修改应用镜像，后续可能出现由于镜像不同导致升级失败等情况。
> 
> ```shell
> docker pull ghcr.io/open-webui/open-webui:main
> ```

拉不动，所以才换的。
