### ISSUE TITLE
[FEATURE]自动快照功能

### ISSUE THREAD

**Issue by ossplus** [1Panel-dev/1Panel#4458]
### 1Panel 版本

lts

### 请描述您的需求或者改进建议

建议增加服务器快照功能：
1.让用户选择所使用的云服务商（例如，阿里云，腾讯云），机器类型
2.设置api
3.设置创建快照的周期，和保存周期。

例如： 腾讯轻量云可以免费2个快照；可以自动化，当备份使用。

下面是一个其他面板的类似功能截图
![screenshot-1712729734538](https://github.com/1Panel-dev/1Panel/assets/1935044/f42f8c56-7380-46f5-bcb5-c0f7f92ba49a)
![Snipaste_2024-04-10_14-16-38](https://github.com/1Panel-dev/1Panel/assets/1935044/911babaf-9958-4e7d-993c-e5b27f33dc17)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
上述需求是准备通过 1Panel 面板来管理云服务器快照吗？

> 1Panel 目前支持手动、定时创建自身系统快照（包括 1Panel 数据目录、已安装应用镜像等）

**Comment by ossplus** [comment]
是的，在1panel后台直接管理，自身所在主机的快照。
比如，我有腾讯轻量云安装了1panel， 1panel后台可以设置api方式每日自动生成快照，及快照保存周期

**Comment by ossplus** [comment]
国外 cloudpanel面板里，有类似实现，但它只有国外主机，aws等支持，无国内阿里，腾讯。
下面是它的相关功能文档。
https://www.cloudpanel.io/docs/v2/admin-area/cloud-features/amazon-web-services/

**Comment by wanghe-fit2cloud** [comment]
收到，但是针对 1Panel 面板而言，我们可能暂时不会支持上述功能，望理解。
