### ISSUE TITLE
[BUG] 1Panel restart causes the task to terminate

### ISSUE THREAD

**Issue by fred913** [1Panel-dev/1Panel#4463]
### 联系方式

mailto:fredtools999@gmail.com

### 1Panel 版本

v1.10.2-lts

### 问题描述

应用更新时重启面板，然后就不能再操作应用了，显示错误：1Panel restart causes the task to terminate

### 重现步骤

如上。

**Comment by ssongliu** [comment]
感谢反馈，麻烦贴一下日志 `/opt/1panel/log/1Panel.log` 以及错误截图

**Comment by wanghe-fit2cloud** [comment]
可以进入 `应用商店` - `已安装` 应用列表，找到目标应用后点击 `重建` 按钮。

**Comment by fred913** [comment]
> 可以进入 `应用商店` - `已安装` 应用列表，找到目标应用后点击 `重建` 按钮。

@wanghe-fit2cloud 感谢解答，重建解决问题。

**Comment by fred913** [comment]
想起来当时1pctl restart的原因了，那天好像是1panel卡死在更新过程，这段时间我会尝试复现卡死的状态，如复现成功我再提交一个issue哈
