### ISSUE TITLE
[BUG]1panel 安装的jumpserver挂载目录问题

### ISSUE THREAD

**Issue by zydudu** [1Panel-dev/1Panel#4471]
### 联系方式

378395322@qq.com

### 1Panel 版本

v1.10.2-lts

### 问题描述

我用1panel 安装的jumpserver ,
容器中/opt/jumpserver/data/ops/playbook 这个目录没有被默认挂载出来，将来升级版本的时候，里面的playbook文件是不是会丢失？
还有会话审计-》会话回放中回放按钮能打开页面，但是不能播放回放

### 重现步骤

安装最新版1panel 和jumpserver ，查看宿主机/opt/1panel/apps/jumpserver/jumpserver/data目录下文件，好像很多文件都没写出来；回放是不是也是因为某些文件没写出来导致的不能播放

### 期待的正确结果

建议和jumpserver开发联合确认一下挂载和打包的配置是否有问题，确认一下升级版本不会丢失数据和功能是否正常

**Comment by wojiushixiaobai** [comment]
有持久化，你的问题并非持久化导致。
- https://github.com/1Panel-dev/appstore/blob/dev/apps/jumpserver/3.10.7/docker-compose.yml#L33

升级不会导致数据丢失

**Comment by zydudu** [comment]
> 有持久化，你的问题并非持久化导致。
> 
> * https://github.com/1Panel-dev/appstore/blob/dev/apps/jumpserver/3.10.7/docker-compose.yml#L33
> 
> 升级不会导致数据丢失

持久化的目录不包含playbook的存储目录，playbook在容器内的地址是/opt/jumpserver/data/ops/playbook

**Comment by wojiushixiaobai** [comment]
仔细看了下，确实路径不对，多了个 jumpserver，等我修复下

**Comment by wanghe-fit2cloud** [comment]
更新已推送至应用商店。
