### ISSUE TITLE
[FEATURE]运行目录的选择栏太窄了

### ISSUE THREAD

**Issue by godcong** [1Panel-dev/1Panel#4472]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

如图: 网站目录->运行目录的选择栏太窄了,看不到路径的文字了.
好像是新版本才出现的问题

### 请描述你建议的实现方案

建议适当增加宽度

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/2727298/b66e2835-a344-4d3a-84e7-9f523c6753db)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。
已知问题：https://github.com/1Panel-dev/1Panel/issues/4280
