### ISSUE TITLE
[BUG] Nginx Proxy Manager，无法实现反向代理

### ISSUE THREAD

**Issue by ChrisKong93** [1Panel-dev/1Panel#4491]
### 1Panel 版本

v1.10.2-lts

### 问题描述

Nginx Proxy Manager，无法实现反向代理

### 重现步骤

宿主机里安装的nginx，然后用1panel安装的Nginx Proxy Manager，同样无法实现反向代理

**Comment by ChrisKong93** [comment]
宿主机不安装nginx也不行，直接使用官方提供的方法部署就可以代理成功

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1Panel 是采用容器化方案安装的应用，应用具体使用问题建议参考应用官方文档。
> 注：容器化教程。
