### ISSUE TITLE
[FEATURE] OpenResty 1.25.3.1 新增了 http/3 支持

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#4494]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

OpenResty 1.25.3.1 新增了 http/3 支持，是否有准备更新支持

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/3641
