### ISSUE TITLE
[BUG]安装失败

### ISSUE THREAD

**Issue by Q2297045667** [1Panel-dev/1Panel#4495]
### 1Panel 版本

最新安装脚本

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/42416195/4fb538ed-6ccf-4d08-8719-387bde7c08b9)

### 重现步骤

使用乌班图服务器版本安装

### 相关日志输出

[1Panel Log]: ======================= 开始安装 ======================= 
[1Panel Log]: 您选择的安装路径为 /opt 
[1Panel Log]: ... 在线安装 docker 
# Executing docker install script, commit: e5543d473431b782227f8908005543bb4389b8de
+ sh -c apt-get update -qq >/dev/null
E: 无法下载 https://ppa.launchpadcontent.net/maas/3.5/ubuntu/dists/lunar/InRelease  403  Forbidden [IP: 2620:2d:4000:1::81 443]
E: 仓库 “https://ppa.launchpadcontent.net/maas/3.5/ubuntu lunar InRelease” 没有数字签名。
[1Panel Log]: ... 启动 docker 
Failed to start docker.service: Unit docker.service not found.
[1Panel Log]: docker 安装失败 

### 附加信息
内核版本
Linux missinglove 6.2.0-39-generic #40-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:18:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
乌班图版本
Ubuntu 23.04 \n \l

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
参考：
https://github.com/1Panel-dev/1Panel/issues/2616
