### ISSUE TITLE
[FEATURE] 请增加应用商店 Z-Blog

### ISSUE THREAD

**Issue by mia0x75** [1Panel-dev/1Panel#4496]
### 1Panel 版本

1.10.2

### 请描述您的需求或者改进建议

一个较老的PHP Blog代码。官方镜像：https://github.com/zblogcn/zblogphp-docker-image

试了一下emlog，这个还需要注册码才行。

### 请描述你建议的实现方案

无

### 附加信息

无

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/4253
