### ISSUE TITLE
[BUG] OpenResty 修改默认端口后，页面提示变形

### ISSUE THREAD

**Issue by arch3rPro** [1Panel-dev/1Panel#4497]
### 1Panel 版本

v1.10.2-lts

### 问题描述

修改默认HTTPS端口为1443后，面板-网站-网站页面会有以下提示：OpenResty 默认 HTTP 端口：80 HTTPS 端口 ：1443，可能影响网站域名访问和 HTTPS 强制跳转。 但是页面显示变形。

![image](https://github.com/1Panel-dev/1Panel/assets/30855883/56d0a7a0-25e6-4654-866a-3c81c5e230e7)

### 重现步骤

修改默认HTTPS端口为1443

### 期待的正确结果

页面正确显示

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
