### ISSUE TITLE
[FEATURE] MariaDB 能升级到11.3.2吗？

### ISSUE THREAD

**Issue by mia0x75** [1Panel-dev/1Panel#4499]
### 1Panel 版本

1.10.2

### 请描述您的需求或者改进建议

官方的镜像：https://hub.docker.com/_/mariadb/tags

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑同时维护 10.x 和 11.x 多个版本。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
