### ISSUE TITLE
[BUG]使用文件-创建-设置权限功能时，无法正确设置权限

### ISSUE THREAD

**Issue by DoshideDK** [1Panel-dev/1Panel#4500]
### 1Panel 版本

v1.10.2-lts

### 问题描述

用1panel自带的文件管理器，创建文件时设置权限时，无法正确设置权限。

### 重现步骤

点击文件-创建-设置权限，设置为777，保存，发现还是755

### 相关日志输出

无

### 附加信息

无

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，刚在本地环境未复现上述问题。
也麻烦上传一下操作视频或者在微信群添加 `王贺` 好友，远程看一下问题。

**Comment by DoshideDK** [comment]
Uploading iShot_2024-04-14_13.37.09.mp4…

**Comment by DoshideDK** [comment]
https://github.com/1Panel-dev/1Panel/assets/105574972/782aac2c-6178-4939-8bb4-f0b47a3addf2

**Comment by wanghe-fit2cloud** [comment]
收到，在新建文件夹页面同时修改权限，确实存在上述问题，我们会在近期版本修复。

**Comment by wanghe-fit2cloud** [comment]
v1.10.3-lts 版本已发布。
