### ISSUE TITLE
[BUG] 设置网站时，部分功能点击后超时

### ISSUE THREAD

**Issue by Shazoo** [1Panel-dev/1Panel#4501]
### 1Panel 版本

v1.10.2-lts

### 问题描述

设置网站目录为子目录时超时。

显示的时候也不正常。
![image](https://github.com/1Panel-dev/1Panel/assets/3198471/587842fb-fb3d-47c3-8504-7ca1fbd38abf)

### 重现步骤

静态网站的根目录，选择子目录的时候，超时。

### 期待的正确结果

希望告知类似api的日志路径。我看看是哪里错误。

点击多次后，内存会慢慢涨。估计哪里卡死了。

**Comment by Shazoo** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/3198471/fb2bd266-2a97-45d1-8f40-d30956f2be5f)
这个api。

刚才发现还有设置 basicauth的api有问题。无resp，导致浏览器超时。

**Comment by wanghe-fit2cloud** [comment]
> 显示的时候也不正常。

重复 issue https://github.com/1Panel-dev/1Panel/issues/4280

**Comment by wanghe-fit2cloud** [comment]
> 这个api。
> 
> 刚才发现还有设置 basicauth的api有问题。无resp，导致浏览器超时。

我们先在本地环境复现一下上述问题。

**Comment by zhengkunwang223** [comment]
提示超时 可能是因为从请求到执行 reload 命令的时间过长
考虑可能是 1. 服务器网络响应时间长 2.服务器配置太低

**Comment by Shazoo** [comment]
> 提示超时 可能是因为从请求到执行 reload 命令的时间过长 考虑可能是 1. 服务器网络响应时间长 2.服务器配置太低

和服务器网络相应和配置无关。因为其他操作都是秒完成。

目前就是更改目录以及设置basic auth会出现这个问题。

多次点击后，整个1panel的占用内存就占用到1.7G（重启1panel的时候，service status的显示）

我已经开始备份准备重装了……

能否告知1panel的http操作日志路径？我重装前可以保留下来贴出来。

**Comment by zhengkunwang223** [comment]
> > 提示超时 可能是因为从请求到执行 reload 命令的时间过长 考虑可能是 1. 服务器网络响应时间长 2.服务器配置太低
> 
> 和服务器网络相应和配置无关。因为其他操作都是秒完成。
> 
> 目前就是更改目录以及设置basic auth会出现这个问题。
> 
> 多次点击后，整个1panel的占用内存就占用到1.7G（重启1panel的时候，service status的显示）
> 
> 我已经开始备份准备重装了……
> 
> 能否告知1panel的http操作日志路径？我重装前可以保留下来贴出来。

/opt/1panel/log/1Panel.log 默认是这个  /opt 是安装目录

**Comment by Shazoo** [comment]
> > > 提示超时 可能是因为从请求到执行 reload 命令的时间过长 考虑可能是 1. 服务器网络响应时间长 2.服务器配置太低
> > 
> > 
> > 和服务器网络相应和配置无关。因为其他操作都是秒完成。
> > 目前就是更改目录以及设置basic auth会出现这个问题。
> > 多次点击后，整个1panel的占用内存就占用到1.7G（重启1panel的时候，service status的显示）
> > 我已经开始备份准备重装了……
> > 能否告知1panel的http操作日志路径？我重装前可以保留下来贴出来。
> 
> /opt/1panel/log/1Panel.log 默认是这个 /opt 是安装目录

当时看过这个日志。没有什么有效信息。

已经重装了……

close掉吧
