### ISSUE TITLE
[BUG] 手动修改 vaultwarden 的 docker-compose.yml 后商店报错

### ISSUE THREAD

**Issue by mobeicanyue** [1Panel-dev/1Panel#4505]
### 1Panel 版本

v1.10.2-lts

### 问题描述

浏览器显示500
![image](https://github.com/1Panel-dev/1Panel/assets/81098819/3737cfe1-0649-47df-8b1c-a8434d5efb8c)

查看日志并没有发现什么异常
![image](https://github.com/1Panel-dev/1Panel/assets/81098819/3b93de68-afd1-4577-87a3-1f1d0cd74ac5)

### 重现步骤

修改 vaultwarden docker-compose 后出错

`1pctl restart` 重启面板后也会报错

### 期待的正确结果

正常使用

**Comment by wanghe-fit2cloud** [comment]
SSH 进入 1Panel 服务器，在 vaultwarden 应用安装目录执行 `docker-compose up -d` 命令，查看一下结果。
> 应用安装目录为：`/opt/1panel/apps/vaultwarden/vaultwarden` （需要根据1Panel安装目录和应用名称自行修改）

`docker-compose version` 命令也查看一下 1Panel 服务器 docker-compose 版本

**Comment by mobeicanyue** [comment]
好像是我密码的报错
![图片1](https://github.com/1Panel-dev/1Panel/assets/81098819/f2fd6816-57af-428c-b3cb-85c42cf179f4)

![image](https://github.com/1Panel-dev/1Panel/assets/81098819/112409b9-7d92-4e48-a539-5cb6119bf923)

去除 `ADMIN_TOKEN` 后正常

![image](https://github.com/1Panel-dev/1Panel/assets/81098819/ef593ebe-0fcb-4969-b1b9-d77ac20ba9cc)

但是服务器 `1pctl restart` 仍然异常

![image](https://github.com/1Panel-dev/1Panel/assets/81098819/4eb7d92f-316f-4dec-a93f-077ca4f70380)

**Comment by mobeicanyue** [comment]
改配置导致的 1p数据库崩溃，解析的时候导致服务 panic 了。已解决，感谢开发者排查！

**Comment by mobeicanyue** [comment]
可不可以在`工具箱`里，增加个尝试修复的功能。因为一个应用导致 1Panel.db 不对，应用商店会直接崩溃

**Comment by wanghe-fit2cloud** [comment]
> 可不可以在`工具箱`里，增加个尝试修复的功能。因为一个应用导致 1Panel.db 不对，应用商店会直接崩溃

收到，麻烦再新开一个 issue 吧，我们后续版本支持。
