### ISSUE TITLE
[FEATURE] 证书允许后续修改信息

### ISSUE THREAD

**Issue by yyyytawa** [1Panel-dev/1Panel#4506]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

有时候证书需要修改后续信息,例如说dns账户.
现在版本只能删了重新申请,希望可以直接修改信息

### 请描述你建议的实现方案

允许编辑dns账户,acme账户等信息,
本地自签证书允许修改域名等信息

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
