### ISSUE TITLE
[FEATURE]建议添加sonarqube

### ISSUE THREAD

**Issue by git-Ander** [1Panel-dev/1Panel#4509]
### 1Panel 版本

v1.10.0-lts

### 请描述您的需求或者改进建议

建议添加sonarqube

### 请描述你建议的实现方案

建议添加sonarqube

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上架 SonarQube。

**Comment by wanghe-fit2cloud** [comment]
已支持。

**Comment by benhailong** [comment]
现在的版本有点儿老，希望可以更新一下

**Comment by wanghe-fit2cloud** [comment]
> 现在的版本有点儿老，希望可以更新一下

https://github.com/1Panel-dev/appstore/pull/7533
