### ISSUE TITLE
[FEATURE]关于增加了禅道 能不能增加一个maxkey单点登录

### ISSUE THREAD

**Issue by keheran520** [1Panel-dev/1Panel#4511]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

能不能增加一个maxkey单点登录https://gitee.com/dromara/MaxKey

### 请描述你建议的实现方案

能不能增加一个maxkey单点登录https://gitee.com/dromara/MaxKey

### 附加信息

能不能增加一个maxkey单点登录https://gitee.com/dromara/MaxKey

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
目前，我们主要以项目的 star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有约 1 万 star 的开源项目，望理解。

**Comment by wanghe-fit2cloud** [comment]
该应用官方提供了 [compose.yml 文件](https://maxkey.top/zh/conf/deploy_docker.html)，建议使用 `容器` - `编排` 功能来维护应用。
