### ISSUE TITLE
[FEATURE]应用商店, 希望可以根据用户的环境, 例如arm来隐藏部分应用

### ISSUE THREAD

**Issue by woodchen-ink** [1Panel-dev/1Panel#4514]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

有部分应用是不支持arm机器的, 但是会显示, 这样会安装失败.
希望可以根据"系统类型"来进行判断展示
![image](https://github.com/1Panel-dev/1Panel/assets/95951386/c6ccf40e-55e9-408a-9d53-a91b27db273f)
![image](https://github.com/1Panel-dev/1Panel/assets/95951386/6b2b34ce-0e23-474e-9547-fdf2fa9fe54e)
![image](https://github.com/1Panel-dev/1Panel/assets/95951386/3da10552-3143-4ffe-8e15-032fa7a1f0dd)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/3026
