### ISSUE TITLE
[BUG]创建进程守护错误问题

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#4516]
### 1Panel 版本

v1.10.2

### 问题描述

创建进程守护和删除进程守护报错

![PixPin_2024-04-15_14-13-25](https://github.com/1Panel-dev/1Panel/assets/63288007/9d6ad5f6-ef70-413e-9793-133b698ce871)

弹出提示错误：
```txt
服务内部错误: error: <class 'xmlrpclib.Fault'>, <Fault 10: u'BAD_NAME: qbittorrent\u79cd\u5b50\u670d\u52a1\u5668'>: file: /usr/lib64/python2.7/xmlrpclib.py line: 794
```

删除该进程守护也报错(可以正常删除但会报错)，新建名称`test`其余不变也报错

![屏幕截图 2024-04-15 141745](https://github.com/1Panel-dev/1Panel/assets/63288007/54b5ba69-6f58-45b9-b7af-36248dc8de04)

### 重现步骤

1.新建`qbittorrent-enhanced-nox_x86_64-linux-musl_static`进程守护
2.点击界面`原文`修改第一行`[program:qbittorrent]`程序名称
3.刷新进程守护页面，看不到这个进程守护
4.打开`/home/1panel/tools/supervisord/supervisor.d`路径下对应进程守护ini文件，恢复新建进程守护时名称
5.触发bug

应该是没有supervisord进程守护`supervisord.conf`导致，重启进程守护依旧报错

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by zhengkunwang223** [comment]
修改名称可能影响删除等操作 所以建议不要修改
