### ISSUE TITLE
[BUG]概览将snap和docker挂载盘都全部显示出来了

### ISSUE THREAD

**Issue by ChungyuCheung** [1Panel-dev/1Panel#452]
### 1Panel 版本

1.0.4

### 问题描述

概览将snap和docker挂载盘都全部显示出来了

### 重现步骤

登录系统即可见到

### 期待的正确结果

只显示物理层面的磁盘信息

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后面版本中修复该问题。
