### ISSUE TITLE
一个安全访问入口的问题

### ISSUE THREAD

**Issue by lrsu** [1Panel-dev/1Panel#4524]
### 1Panel 版本

1.10.2

### 请描述您的需求或者改进建议

如果直接访问面板后台 ip:port 会报一个没有权限访问的界面，安全性降低了，建议在没有正确输入访问目录的时候可以直接返回一个状态码供用户选择，比如404,500
![IMG_20240415_203125](https://github.com/1Panel-dev/1Panel/assets/105852378/ecf9d41f-f41e-46b9-bac8-5bd68e12ea01)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们将在下个版本支持用户自定义返回状态码及页面。

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/2594
