### ISSUE TITLE
[FEATURE]计划任务建议增加系统开机时和关机时触发条件

### ISSUE THREAD

**Issue by huangye123** [1Panel-dev/1Panel#4525]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

目前有个场景系统开机完成后，需要执行docker compose up把众多微服务按配置文件进行启动。

### 请描述你建议的实现方案

增加系统开机时和关机时触发条件，开机完成后，可执行相关应用的启动，关机时，执行相关服务的正常退出。对运维比较实用。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，系统开关机时增加触发条件的需求，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/3858
