### ISSUE TITLE
对非标准docker login 的仓库，允许定义参数命令配置

### ISSUE THREAD

**Issue by huangye123** [1Panel-dev/1Panel#4526]
### 联系方式

381538764@qq.com

### 1Panel 版本

v1.10.1-lts

### 问题描述

服务内部错误: stdout: stderr: WARNING! Using --password via the CLI is insecure. Use --password-stdin. Error response from daemon: login attempt to http://www.myhuangye.com:8443/v2/ failed with status: 400 Bad Request , stderr: exit status 1

![image](https://github.com/1Panel-dev/1Panel/assets/28778519/7aebb386-f5f8-4180-9abc-c7080fa14b26)

### 重现步骤

Harbor 版本 v2.10.2-1a741cb7
在1panel容器仓库中添加私有Docker仓库Harbor，执行同步命令时，会报错误信息，情况跟在SSH命令执行一致

密码参数采用 -p 就登录失败
![image](https://github.com/1Panel-dev/1Panel/assets/28778519/4c6eda55-6177-4aa6-ac41-52a9ad383fe8)

密码参数采用 -passord-stdin 就登录正常
![image](https://github.com/1Panel-dev/1Panel/assets/28778519/f711ffa1-2044-45ef-951a-95486e1e0c74)

### 期待的正确结果

对非标准docker login 的仓库，允许定义参数命令配置

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化，如：添加镜像仓库时忽略上述警告信息使仓库正常添加。

**Comment by huangye123** [comment]
经过排查是Harbor参数配置有误造成的异常，感谢！

**Comment by xkloveme** [comment]
> 经过排查是Harbor参数配置有误造成的异常，感谢！

遇到了，怎么解决的？

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> After troubleshooting, it is an exception caused by the incorrect configuration of Harbor parameters, thank you!

If you encounter it, how to solve it?

**Comment by WillieOng-HK** [comment]
+1
