### ISSUE TITLE
[BUG]计划任务挂了

### ISSUE THREAD

**Issue by springeye** [1Panel-dev/1Panel#453]
### 1Panel 版本

v1.0.4

### 问题描述

刚才打开看计划任务全部停止了。

### 重现步骤

不知道什么原因。就刚才去看计划任务的日志突然发现，很多1分钟执行一次的任务已经一整天没有执行了。

我猜测有可能是中途我手动重启过(手动执行1pctl命令)，也有可能是在线更新的原因，因为我手动把每个任务挨个禁用再启用一次就好了。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中修复该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.0.5 版本已修复。
