### ISSUE TITLE
[BUG] nodejs运行环境修改相应docker网络不生效

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4531]
### 联系方式

ruinb0w@qq.com

### 1Panel 版本

v1.10.2-lts

### 问题描述

我有一个docker-mongodb数据库, 通过命令行创建的, 网络是bridge. 我在1panel上创建了一个nodejs运行环境, 发现访问不到数据库, 后在1panel-docker中修改nodejs运行环境docker的网络, 修改后不生效, 重启运行环境后变回1-panelnetwork

### 重现步骤

1. 创建任意nodejs运行环境
2. 修改对应docker的网络
3. 网络配置不生效

### 期待的正确结果

运行环境docker网络配置生效

**Comment by wanghe-fit2cloud** [comment]
基于 PHP 或者 Node.js 运行换环境创建网站时会默认使用 1panel-network 这个容器网络。
> 如果容器间需要使用容器名称互相访问，建议将 MongoDB 的容器网络修改为 1panel-network。
