### ISSUE TITLE
应用商店增加AFFINE

### ISSUE THREAD

**Issue by LIHAQ** [1Panel-dev/1Panel#4533]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

AFFINE是个比较好用的开源笔记软件，目前个人经常使用AFFINE来记录笔记，但是现在应用商店没有，希望可以增加这个软件。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先调研一下上述应用的容器化部署方案。

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/5017
