### ISSUE TITLE
[FEATURE] 多个网站使用同一个域名不同端口时，名称增加显示端口号，或者显示别名

### ISSUE THREAD

**Issue by mia0x75** [1Panel-dev/1Panel#4537]
### 1Panel 版本

1.10.2

### 请描述您的需求或者改进建议

目前是这样，所有网站名称相同

![截图 2024-04-16 19-47-27](https://github.com/1Panel-dev/1Panel/assets/5111356/26ba589c-2ff4-4d42-abbc-6698a1b9e7a3)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/3726
我们将在 v1.10.3-lts 版本支持上述需求。
