### ISSUE TITLE
[BUG] 竖屏时部分情况会出现显示异常

### ISSUE THREAD

**Issue by alittlehuaji** [1Panel-dev/1Panel#4539]
### 联系方式

huajibenji@outlook.com

### 1Panel 版本

v1.10.2-lts

### 问题描述

部分情况下出现显示异常

### 重现步骤

首先F12控制台打开竖屏模式。重现步骤：1p主页->网站->设置(OpenResty)
这种问题似乎只会在显示数值比较大的情况下出现

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/119058504/7c7fc47a-09b2-46c4-94e6-06ac966b5a89)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
移动端适配相关问题的讨论，我们统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4284
