### ISSUE TITLE
[FEATURE] 容器仓库配置地址，增加有效性校验

### ISSUE THREAD

**Issue by huangye123** [1Panel-dev/1Panel#4542]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/28778519/2f8591d7-7f05-46ef-b0e4-14a903174110)

问题1：
配置仓库地址时，带了https,造成后续操作失败，配置时没有校验提醒

问题2：
地址带上https，点击同步按钮，没有异常报错

### 请描述你建议的实现方案

经过几天排查才发现，建议在前端增加地址不需要http或https的校验，减少不必要的错误。

**Comment by ssongliu** [comment]
感谢反馈，后续版本优化

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
