### ISSUE TITLE
有没有可能在概览页中状态栏中显示CPU或服务器工作温度，最好能做到显示内容自己定义

### ISSUE THREAD

**Issue by ocoj** [1Panel-dev/1Panel#4543]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

有没有可能在概览页中状态栏中显示CPU或服务器工作温度，最好能做到显示内容自己定义,

**Comment by ssongliu** [comment]
感谢反馈，后续版本持续优化

**Comment by wanghe-fit2cloud** [comment]
服务器硬件（如 CPU、主板温度等）需求的讨论，统一汇总到该 issue #1614
