### ISSUE TITLE
能否增加安全访问入口的长度？

### ISSUE THREAD

**Issue by shawnwu2022** [1Panel-dev/1Panel#4545]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

安全访问入口长度限制太短导致无法直接迁移bt面板

### 请描述你建议的实现方案

增加安全访问入口长度限制

**Comment by ssongliu** [comment]
感谢反馈，麻烦再具体描述一下使用场景

**Comment by shawnwu2022** [comment]
bt面板的安全入口支持长度6-117，1panel支持6-10，假如将bt管理面板直接替换为1panel，那么就会出现原有的入口地址超长不可用的情况，哎，也不是很重要，就是觉得很麻烦

**Comment by wanghe-fit2cloud** [comment]
收到，我们会在近期版本支持上述建议。

**Comment by wanghe-fit2cloud** [comment]
v1.10.5-lts 版本已发布。
