### ISSUE TITLE
SSH 连接列表显示优化[FEATURE]

### ISSUE THREAD

**Issue by Murasame233** [1Panel-dev/1Panel#4546]
### 1Panel 版本

1.10.2-lts

### 请描述您的需求或者改进建议

ssh加号选单下面，把鼠标放上去后显示遮罩层把上一条给遮到了，

### 请描述你建议的实现方案

建议往右边移动，漏出上一条

### 附加信息

<img width="169" alt="截屏2024-04-17 14 00 57" src="https://github.com/1Panel-dev/1Panel/assets/87534732/828c7bc7-79a7-44b9-9e64-a9e0c64e1af3">

**Comment by ssongliu** [comment]
感谢反馈，后续版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.10.6-lts 版本已发布。
