### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by miniwater** [1Panel-dev/1Panel#4551]
### 联系方式

1456441157@qq.com

### 1Panel 版本

v1.10.2-lts

### 问题描述

无法创建站点。
已有PHP82环境 以及一个 PHP82环境的站点。
再多建一个PHP82站点时遇到问题，提示站点新建成功，但是并没有该站点容器，打开报502 Bad Gateway，修改站点配置文件时提示php.ini 文件不存在。

### 重现步骤

PHP82
应用商店	
8.2.10
1panel-php:8.2.10

### 相关日志输出

```shell
[2024-04-17 17:54:35] [INFO] download app[PHP 8] from https://apps-assets.fit2cloud.com/stable/1panel/php8/8.2.10/php8-8.2.10.tar.gz  
[2024-04-17 17:54:35] [ERROR] download app[PHP 8] error 文件不存在
```

**Comment by wanghe-fit2cloud** [comment]
目前 1Panel 应用商店中维护的 PHP 8.2 最新版本为 8.2.15。
解决办法参考：
https://github.com/1Panel-dev/1Panel/issues/4049

**Comment by miniwater** [comment]
> 目前 1Panel 应用商店中维护的 PHP 8.2 最新版本为 8.2.15。 解决办法参考： #4049

额，下一个8.2新版出来后也会像这样一刀切吗
