### ISSUE TITLE
[FEATURE]希望在设置亚马逊 S3 时能够支持Virtual Hosted Style和Path Style两种访问模式切换

### ISSUE THREAD

**Issue by chenxv399** [1Panel-dev/1Panel#4553]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

1panel的备份账号功能默认是使用Virtual Hosted Style方式访问S3存储桶的。但包括Oracle Cloud在内的厂商逐渐要求用户使用Path Style访问来代替Virtual Hosted Style，甚至禁止使用Virtual Hosted Style访问存储桶。希望1panel在用户配置S3时能够允许自行选择使用哪一种方式访问存储桶，否则就会使那些只允许使用Path Style的厂商的存储桶S3访问失败。
另外，1panel的[文档](https://1panel.cn/docs/user_manual/settings/#s3)里对于Oracle Cloud与Amazon S3的兼容性的说明有误，根据Oracle Cloud的[文档](https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm#usingAPI)，"Virtual host-style access isn't supported."。

### 请描述你建议的实现方案

提供一个选择框，允许用户在设置亚马逊 S3 云存储时，在`Virtual Hosted Style`和`Path Style`两种访问方式中自由选择。

### 附加信息

* 1Panel文档截图![image](https://github.com/1Panel-dev/1Panel/assets/92201935/313337f2-6e4c-4350-8ce8-6b077d725e76)
* Oracle Cloud doc截图![image](https://github.com/1Panel-dev/1Panel/assets/92201935/3a4fdee0-a2ce-4ab4-a3cb-4f9fefe15f73)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述需求。

**Comment by dushu8** [comment]
催办一下,我也想用oracle

**Comment by wanghe-fit2cloud** [comment]
> 催办一下,我也想用oracle

请问，手动输入 Bucket 是否能满足要求呢？
![image](https://github.com/user-attachments/assets/9a3b1417-f1c7-415e-b7bc-ba8c47b9cbc2)

**Comment by dushu8** [comment]
oracle 访问方式是  https://{namespace}.compat.objectstorage.{region}.oraclecloud.com/{存储桶名称}
1panel 拼接逻辑是  https://{存储桶名称}.{namespace}.compat.objectstorage.{region}.oraclecloud.com
你提到的手动输入或者自动获取只是拿到存储桶名称而已,所有参数填写完毕后,能自动能获取到存储桶名称

**Comment by ssongliu** [comment]
> oracle 访问方式是 https://{namespace}.compat.objectstorage.{region}.oraclecloud.com/{存储桶名称} 1panel 拼接逻辑是 https://{存储桶名称}.{namespace}.compat.objectstorage.{region}.oraclecloud.com 你提到的手动输入或者自动获取只是拿到存储桶名称而已,所有参数填写完毕后,能自动能获取到存储桶名称

麻烦加下我，我适配一下
![image](https://github.com/user-attachments/assets/7ffc41a5-289c-477d-a6ec-ebcd7a84973f)

**Comment by wanghe-fit2cloud** [comment]
v1.10.16 版本已发布。
