### ISSUE TITLE
[FEATURE] 清理docker编译缓存

### ISSUE THREAD

**Issue by likesrt** [1Panel-dev/1Panel#4555]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

一键清理手动docker build后产生的缓存文件

**Comment by likesrt** [comment]
docker builder prune

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/3890
