### ISSUE TITLE
[FEATURE]流量监控显示优化建议

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#4558]
### 1Panel 版本

v1.10.2-lts

### 请描述您的需求或者改进建议

发现首页流量监控显示在网卡默认为`所有`状态下，为实际流量的2倍，录屏如下：
![20240418-090726](https://github.com/1Panel-dev/1Panel/assets/63288007/9d9f1f43-83e7-4dd9-b6bc-6e49f8b19ba8)

当网卡更改为`docker0`时，状态与脚本计算的流速一致。

运行的服务器板载双网卡，不知道是这个原因导致的还是1panel本身设计如此。建议优化一下这个小问题，毕竟既然是流量监控，就应该是实际的进出站流量吧。

当然，如果显示策略仅为服务器内部的所有流量叠加，那么建议可以优化一下显示细分，毕竟在默认情况下，很容易把流量监控理解为实际进出站的流量。

**Comment by ssongliu** [comment]
感谢反馈，可以在面板设置中设置默认显示的网卡
