### ISSUE TITLE
[BUG] 亚马逊光帆ubuntu 20.04 概览页异常

### ISSUE THREAD

**Issue by bulesky89857** [1Panel-dev/1Panel#456]
### 1Panel 版本

1.04

### 问题描述

亚马逊光帆ubuntu 20.04  概览页异常
![wx_camera_1680183792046](https://user-images.githubusercontent.com/50124044/228860112-8016a25b-a89d-4d4c-aec8-f6f0fe25d2a4.jpg)

### 重现步骤

重启不能解决问题

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们明天会发布修复该问题的版本。

**Comment by wanghe-fit2cloud** [comment]
v1.0.5 版本已修复。

**Comment by bulesky89857** [comment]
> v1.0.5 版本已修复。
已更新，问题解决。666.
