### ISSUE TITLE
[BUG] 应用商店界面小问题

### ISSUE THREAD

**Issue by mia0x75** [1Panel-dev/1Panel#4562]
### 1Panel 版本

1.10.2

### 问题描述

![截图 2024-04-18 10-24-05](https://github.com/1Panel-dev/1Panel/assets/5111356/28c7e64d-f06b-46ac-8bd6-5151bf13bdad)

卡片有些错位，不是描述信息过长造成的挤压。

### 重现步骤

查看应用列表即可见。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
