### ISSUE TITLE
[FEATURE]专业版waf功能建议

### ISSUE THREAD

**Issue by shane654** [1Panel-dev/1Panel#4567]
### 1Panel 版本

v1.10.3-lts

### 请描述您的需求或者改进建议

waf能否增加一个全局关闭的开关（方便用户自由调整是否开启waf，目前安装后就无法关闭了）
另外，能否添加一个设置，用于选择获取用户IP的方式？例如如果前端使用了cdn，从cdn的header字段里获取访客的ip，并用于waf和网站监控报表

**Comment by zhengkunwang223** [comment]
全局配置-配置-总开关 可以关闭全局 WAF 
CDN 适配那个后续更新吧 
感谢你的建议

**Comment by zhengkunwang223** [comment]
v1.10.10-lts 已发布
