### ISSUE TITLE
[BUG]在竖屏模式下部分排版出现问题

### ISSUE THREAD

**Issue by alittlehuaji** [1Panel-dev/1Panel#4570]
### 联系方式

huajibenji@outlook.com

### 1Panel 版本

v1.10.3-lts

### 问题描述

在竖屏模式下，waf的概览两张统计表无法正常显示，另外在waf拦截记录这里两个搜索框也一样

### 重现步骤

F12打开控制台，切换为竖屏模式。步骤：高级功能->WAF->概览/拦截记录

### 附加信息

![1](https://github.com/1Panel-dev/1Panel/assets/119058504/29fe9aee-0deb-44ae-a348-84b9561b2b71)
![2](https://github.com/1Panel-dev/1Panel/assets/119058504/3cd010de-8aa8-405b-84f2-cc4e5ae51215)

**Comment by zhengkunwang223** [comment]
好的 后续版本优化

**Comment by zhengkunwang223** [comment]
v1.10.10-lts 已发布
