### ISSUE TITLE
[FEATURE] 界面统一一下，建议都不要文字

### ISSUE THREAD

**Issue by mia0x75** [1Panel-dev/1Panel#4571]
### 1Panel 版本

1.10.3

### 请描述您的需求或者改进建议

![截图 2024-04-18 21-03-50](https://github.com/1Panel-dev/1Panel/assets/5111356/579f7105-3fe3-4283-9d73-2083f42d7c6c)
![截图 2024-04-18 21-04-10](https://github.com/1Panel-dev/1Panel/assets/5111356/7783e1dc-ff9b-46d1-8b48-f3c72308eda3)

**Comment by zhengkunwang223** [comment]
好的 感谢反馈 后续版本持续优化

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
