### ISSUE TITLE
[BUG]专业版waf未授权域名访问功能出现500

### ISSUE THREAD

**Issue by likesrt** [1Panel-dev/1Panel#4572]
### 联系方式

yuyan@Broue.cn

### 1Panel 版本

专业版：v1.10.3-lts

### 问题描述

开启专业版waf后 访问解析但是未绑定到面板的域名出现500错误
未授权域名访问功能出现500

### 重现步骤

参考视频 ： https://blog.likesrt.com/upload/2024-04-18_22-17-34.mp4

### 期待的正确结果

正确返回 网站不存在，请检查域名

### 相关日志输出

```shell
1Panel-openresty-P9VK  | stack traceback:
1Panel-openresty-P9VK  | coroutine 0:
1Panel-openresty-P9VK  | 	./lib/action.lua: in function 'exec_action'
1Panel-openresty-P9VK  | 	./waf.lua:179: in main chunk, client: 39.144.192.23, server: _, request: "POST /8/secret HTTP/1.1", host: "api.likesrt.com"
1Panel-openresty-P9VK  | 39.144.192.23 - - [18/Apr/2024:21:01:58 +0800] "POST /8/secret HTTP/1.1" 500 174 "-" "com.byyoung.setting/182851713445317998Androidv3.8.13" "-"
```

**Comment by zhengkunwang223** [comment]
我们先复现一下

**Comment by likesrt** [comment]
> 我们先复现一下

我尝试了一下 在本地虚拟机 开启waf后 修改了一下waf设置 成功复现了

**Comment by likesrt** [comment]
> 我们先复现一下

使用 出现问题后使用1pctl restore回退后仍旧存在该问题。在旧版网站管理打开waf设置会报错服务异常

[31m2024/04/18 21:58:31 [Recovery] 2024/04/18 - 21:58:31 panic recovered:
POST /api/v1/websites/waf/config HTTP/2.0
Host: 192.168.1.201:29758
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: zh
Content-Length: 43
Content-Type: application/json
Cookie: LOBE_LOCALE=zh-CN; reader.session=77c4d7db88df17048681776beedac16e; SESSION=7269eade-2bf6-4bb0-aa05-edb9d02e376c; XSRF-TOKEN=30048e88-575a-42ce-a029-932242cfd1ef; psession=9b318a9f-7ff8-4e21-bf61-39068f1b10fb
Origin: https://192.168.1.201:29758
Referer: https://192.168.1.201:29758/websites/1/config/safety
Sec-Ch-Ua: "Microsoft Edge";v="123", "Not:A-Brand";v="8", "Chromium";v="123"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Windows"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
X-Xsrf-Token: 30048e88-575a-42ce-a029-932242cfd1ef


runtime error: index out of range [0] with length 0
runtime/panic.go:114 (0x439dbb)
github.com/1Panel-dev/1Panel/backend/app/service/website.go:869 (0x2c0d764)
github.com/1Panel-dev/1Panel/backend/app/api/v1/website.go:321 (0x2f239b7)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc6098a)
github.com/1Panel-dev/1Panel/backend/middleware/password_expired.go:24 (0x2f3fc69)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc6098a)
github.com/1Panel-dev/1Panel/backend/middleware/session.go:36 (0x2f3f81a)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc6098a)
github.com/1Panel-dev/1Panel/backend/middleware/jwt.go:15 (0x2f3f528)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc6098a)
github.com/1Panel-dev/1Panel/backend/middleware/loading.go:22 (0x2f79b44)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc6098a)
github.com/1Panel-dev/1Panel/backend/middleware/bind_domain.go:22 (0x2f79930)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc6098a)
github.com/1Panel-dev/1Panel/backend/middleware/ip_limit.go:25 (0x2f79524)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc6098a)
github.com/1Panel-dev/1Panel/backend/middleware/operation.go:67 (0x2f77b7d)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc6d899)
github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0xc6d887)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc6ca3d)
github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0xc6ca00)
github.com/gin-gonic/gin@v1.9.1/context.go:174 (0xc6bafa)
github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0xc6b78d)
github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0xc6b2bc)
net/http/server.go:2938 (0x87944d)
net/http/server.go:3546 (0x87b430)
net/http/h2_bundle.go:6193 (0x84ce7a)
runtime/asm_amd64.s:1650 (0x472080)
[0m

**Comment by likesrt** [comment]
> 我们先复现一下

复现步骤可参考视频
https://blog.likesrt.com/upload/2024-04-18_22-17-34.mp4

**Comment by zhengkunwang223** [comment]
感谢反馈 已经复现 后续版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.10.5-lts 版本已发布。
