### ISSUE TITLE
[FEATURE]专业版WAF允许从自定义的Header头获取IP地址

### ISSUE THREAD

**Issue by unknown-o** [1Panel-dev/1Panel#4574]
### 1Panel 版本

1.10.3 LTS

### 请描述您的需求或者改进建议

很多情况下，并不是主机直接对外服务，而是套了一层CDN
目前的WAF设置似乎是直接取客户端IP，当触发拦截规则时，可能将CDN IP加入到黑名单中，导致CDN回源异常

### 请描述你建议的实现方案

允许两个方案
1.当检测到指定Header头的参数为yes时，则信任X-Forwarded-For中的IP
2.直接自定义从指定Header头中获取IP
如果可以的话，希望WAF取到IP后，覆盖REMOTE_ADDR、HTTP_CLIENT_IP等HTTP头，以使后端程序无需特殊设置也能适应CDN

**Comment by zhengkunwang223** [comment]
好的 感谢建议 后续版本支持

**Comment by ZhangYuci** [comment]
期待新版本😀

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
