### ISSUE TITLE
[BUG]更新后显示File not found

### ISSUE THREAD

**Issue by gzy318** [1Panel-dev/1Panel#4575]
### 联系方式

1PanelVIP七群：xinglingsui

### 1Panel 版本

v1.10.3-tls

### 问题描述

升级新版本（专业版）：
网站显示File not found的
已经尝试：
（关闭waf和
or恢复升级之前备份）
依然显示File not found的

### 重现步骤

升级新版本，新建网站

**Comment by zhengkunwang223** [comment]
您好 下个版本修复

**Comment by Daiyangcheng** [comment]
临时解决方案，找到网站对应的目录（*/1panel/apps/openresty/openresty/www/sites/ 下的目录）将权限改成 0755，勾选“同时修改子文件夹属性”

**Comment by wanghe-fit2cloud** [comment]
v1.10.4-lts 版本已发布。

**Comment by gzy318** [comment]
v1.10.4-lts好像还是这样

**Comment by wanghe-fit2cloud** [comment]
> v1.10.4-lts好像还是这样

需要新建运行环境网站，试一下。
