### ISSUE TITLE
[FEATURE]文件管理里能否添加全类型文件编辑功能?

### ISSUE THREAD

**Issue by jeefyang** [1Panel-dev/1Panel#4576]
### 1Panel 版本

v1.10.3-lts

### 请描述您的需求或者改进建议

文件管理里很多冷门文件类型的文件不能直接编辑,导致每次修改文件都需要通过终端进入进行编辑,很是麻烦,希望社区能够提供任意类型编辑功能,不胜感激

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在后续版本调研下具体方案。

**Comment by lan-yonghui** [comment]
@jeefyang 可以具体描述一下哪些文件类型不支持吗？附带指定类型的文件附件会更好！

**Comment by lan-yonghui** [comment]
这问题目前可以查看下 issue https://github.com/1Panel-dev/1Panel/issues/5722 ，看是否解决，有其他问题可以再次反馈。
