### ISSUE TITLE
[BUG]升级最新版本后上传文件夹报错

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4579]
### 1Panel 版本

v1.10.3-lts

### 问题描述

如题。
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/e6c3f17f-eae1-4ad9-b805-7c55174ec413)

### 重现步骤

如图,上传单个文件是可以的
已经清理过缓存,所有东西都是最新版本

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.4-lts 版本已发布。
