### ISSUE TITLE
[FEATURE] 可否修改概览中内存的单位

### ISSUE THREAD

**Issue by Canary233** [1Panel-dev/1Panel#4580]
### 1Panel 版本

1.10.4-lts

### 请描述您的需求或者改进建议

能否提供选项来修改概览中内存的单位，如GB?

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本优化。
重复 issue https://github.com/1Panel-dev/1Panel/issues/4207
