### ISSUE TITLE
[BUG] OpenResty 1.21.4.3-2-1-focal  配置重载不生效，必须重启

### ISSUE THREAD

**Issue by hipi** [1Panel-dev/1Panel#4581]
### 1Panel 版本

1.0.4-lts 版本 

### 问题描述

OpenResty 1.21.4.3-2-1-focal  配置重载不生效，必须重启

### 重现步骤

OpenResty 1.21.4.3-2-1-focal  配置重载不生效，必须重启

### 期待的正确结果

重载生效

**Comment by hipi** [comment]
```bash
[error] 31#31: *2016 cannot load certificate "data:": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE) while SSL handshaking,
```
还报证书错误

**Comment by zhengkunwang223** [comment]
是手动修改 nginx 配置吗？

**Comment by hipi** [comment]
是的，手动改配置，保存后不生效，访问会出现 `err_http2_protocol_error` 错误。
重启 OpenResty 后，才可访问，而且时不时也会出现 `err_http2_protocol_error` 错误。

**Comment by qiaohs** [comment]
1.0.5-lts, 未更改配置正常访问期间，今天突然出现`err_http2_protocol_error`错误，重启OpenResty后才恢复，目前只遇到了这一次

**Comment by TriVectorX** [comment]
我也是遇到很多次同樣的問題了，不過沒有修改過Nginx配置。
正常使用期間，更新WP blog post就會觸發**err_http2_protocol_error**錯誤，只能重啟OpenResty才能恢復。而且也出現證書錯誤
Cannot load certificate "data:": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE) while SSL handshaking,

1Panel version: v1.10.5-lts
OpenResty version: 1.21.4.3-2-1-focal

**Comment by zhengkunwang223** [comment]
err_http2_protocol_error 可能是被 WAF 拉黑了 
可以关闭 WAF 试一下

**Comment by TriVectorX** [comment]
感謝！我關了一個規則後目前沒有繼續出現err_http2_protocol_error

**Comment by makerjackie** [comment]
重启只能临时解决问题，后面还是会报错。我使用的是腾讯云，腾讯云防火墙 WAF 的什么规则呢？ @TriVectorX

**Comment by makerjackie** [comment]
这是个常见问题..... 解决方法见： https://bbs.fit2cloud.com/t/topic/4540 hmmmm

**Comment by TriVectorX** [comment]
> 重启只能临时解决问题，后面还是会报错。我使用的是腾讯云，腾讯云防火墙 WAF 的什么规则呢？ @TriVectorX

我是在1Panel的 高级功能 -> WAF -> 全局设置 里面关闭了一两个规则，就解决了；我觉得规则应该是因程序而异的，我关闭规则之前和WP默认的api request冲突，会禁止传输尖括号

**Comment by makerjackie** [comment]
thx 另外。 思源笔记（使用 1panel 安装的）我关闭 WAF 才能正常使用.... 具体应该关闭什么规则我其实也不太清楚....

**Comment by TriVectorX** [comment]
> thx 另外。 思源笔记（使用 1panel 安装的）我关闭 WAF 才能正常使用.... 具体应该关闭什么规则我其实也不太清楚....

的确，官方要是能提供WAF的log就好了。

**Comment by wanghe-fit2cloud** [comment]
应用白名单的需求，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4636
