### ISSUE TITLE
[BUG] 昨天升级v-1.10.3-lts 版本后好像一直在刷日志

### ISSUE THREAD

**Issue by hjdyzy** [1Panel-dev/1Panel#4582]
### 联系方式

207581543@qq.com

### 1Panel 版本

v-1.10.3-lts

### 问题描述

昨天升级v-1.10.3-lts 版本后到今天磁盘就用完了，如截图

### 重现步骤

就更新了 v-1.10.3-lts 版本 并没有做其他操作

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/71299416/b3faf581-a2b6-475a-a04c-660ad3fd5683)

**Comment by ssongliu** [comment]
感谢反馈，下个小版本解决该问题，暂时先重启一下 1panel 服务

**Comment by hjdyzy** [comment]
好的，刚才我把这两个日志文件删了重启1panel 了，现在没在刷日志了

**Comment by ssongliu** [comment]
> 好的，刚才我把这两个日志文件删了重启1panel 了，现在没在刷日志了

有进行啥特殊操作吗，比如说打开容器日志没有正常关闭之类的

**Comment by hjdyzy** [comment]
这个我没什么印象了，我看了一个日志文件里面全是这种：
![image](https://github.com/1Panel-dev/1Panel/assets/71299416/828ca116-1b26-402a-901a-aadcc1d1721f)

我能确定昨天更新版本后一直没有在服务器做过操作，都是通过面板点了几下看看有什么变化没，面板操作日志：
![image](https://github.com/1Panel-dev/1Panel/assets/71299416/65aca8ee-c1fc-413e-acc2-718c6f1daccc)

**Comment by hjdyzy** [comment]
想起来个服务器做的操作：昨天升级v-1.10.3-lts 版本过程中挺长时间都没有更新成功，然后我想通过ip+端口访问的，执行了这个命令：
![image](https://github.com/1Panel-dev/1Panel/assets/71299416/73b86c4d-a0ac-4919-bf60-722c16d3f3a0)

**Comment by ssongliu** [comment]
> 想起来个服务器做的操作：昨天升级v-1.10.3-lts 版本过程中挺长时间都没有更新成功，然后我想通过ip+端口访问的，执行了这个命令： ![image](https://private-user-images.githubusercontent.com/71299416/323806447-73b86c4d-a0ac-4919-bf60-722c16d3f3a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTE4NzIsIm5iZiI6MTcxMzQ5MTU3MiwicGF0aCI6Ii83MTI5OTQxNi8zMjM4MDY0NDctNzNiODZjNGQtYTBhYy00OTE5LWJmNjAtNzIyYzE2ZDNmM2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAxNTI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZjgzZDY1OWI2YzEwNWNmMmIzMTY1ZjczZjBkZDczYjI4NTIwZjA0NDQ3MGM0N2Y5YjZlMTI1MGNkYjljYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E4QMxUPWqMRZjT2-LTqY6Un8wErbwERq3bY6YUL5ILo)

和这个关系不大，主要是查看日志之类的，比如说安装或者重建应用过程中查看日志这些

**Comment by hjdyzy** [comment]
还有这个，负载是从这时间开始突然变很高的：
![image](https://github.com/1Panel-dev/1Panel/assets/71299416/fbacdfbd-1e0c-416c-91da-14afad4fbfe6)

查看容器日志的话有在面板中点击过，升级openresty时升级了挺久都没成功，我应该是点了下这里，当时没有日志能查看
![image](https://github.com/1Panel-dev/1Panel/assets/71299416/13dd9989-c828-4d85-88db-451d63c0183f)

还有安装coder的时候应该也点过这个按钮
![image](https://github.com/1Panel-dev/1Panel/assets/71299416/6720d5e4-3147-48c9-8a87-e289b7266de6)

详细操作我只真的没啥印象了😂

**Comment by ssongliu** [comment]
> 还有这个，负载是从这时间开始突然变很高的： ![image](https://private-user-images.githubusercontent.com/71299416/323807615-fbacdfbd-1e0c-416c-91da-14afad4fbfe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTI3MTgsIm5iZiI6MTcxMzQ5MjQxOCwicGF0aCI6Ii83MTI5OTQxNi8zMjM4MDc2MTUtZmJhY2RmYmQtMWUwYy00MTZjLTkxZGEtMTRhZmFkNGZiZmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAyMDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNjhhMjVhYTE1ODNiMGJlZTQxZjY5ZWQ1ZjEzNTBjMTkwZmRlMjQ2ZTViNjk1YmNmZmIwZjM1ZjJlYzVkZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lk9K31a15UghOwFwYEIFZ8c8P-_IN7dKLr2qKrQ0qRg)
> 
> 查看容器日志的话有在面板中点击过，升级openresty时升级了挺久都没成功，我应该是点了下这里，当时没有日志能查看 ![image](https://private-user-images.githubusercontent.com/71299416/323809003-13dd9989-c828-4d85-88db-451d63c0183f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTI3MTgsIm5iZiI6MTcxMzQ5MjQxOCwicGF0aCI6Ii83MTI5OTQxNi8zMjM4MDkwMDMtMTNkZDk5ODktYzgyOC00ZDg1LTg4ZGItNDUxZDYzYzAxODNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAyMDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZjY2OThlZjNiMGQ2Njg4MzM2MDg0NzEwZDg2NWE0NmVlY2E4MDNhZDljYWIwM2JiODgzZjQ3NTdkMjYxOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VIEOVD8s93m2-wt6s81m1Y-BgKd1f7F-MRbujguHKMA)
> 
> 还有安装coder的时候应该也点过这个按钮 ![image](https://private-user-images.githubusercontent.com/71299416/323809193-0adcfa29-89e7-4023-b129-b9fcf061789e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTI3MTgsIm5iZiI6MTcxMzQ5MjQxOCwicGF0aCI6Ii83MTI5OTQxNi8zMjM4MDkxOTMtMGFkY2ZhMjktODllNy00MDIzLWIxMjktYjlmY2YwNjE3ODllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAyMDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNDFjOGM1MmE4NzU2N2NmMmMzOTZkMzI3MTM2NGYzNDcyNzNlZmZlZWVkMjExOWRkOWJkZjhkYTZhZGU1Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oUgB-GKJNxgRTrLKhpUrv6LsKswaRFd3i8xR4w8jhpI)
> 
> 详细操作我只真的没啥印象了😂

好的好的，感谢

**Comment by avsba001** [comment]
> > 想起来个服务器做的操作：昨天升级v-1.10.3-lts 版本过程中挺长时间都没有更新成功，然后我想通过ip+端口访问的，执行了这个命令： ![image](https://private-user-images.githubusercontent.com/71299416/323806447-73b86c4d-a0ac-4919-bf60-722c16d3f3a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTE4NzIsIm5iZiI6MTcxMzQ5MTU3MiwicGF0aCI6Ii83MTI5OTQxNi8zMjM4MDY0NDctNzNiODZjNGQtYTBhYy00OTE5LWJmNjAtNzIyYzE2ZDNmM2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAxNTI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZjgzZDY1OWI2YzEwNWNmMmIzMTY1ZjczZjBkZDczYjI4NTIwZjA0NDQ3MGM0N2Y5YjZlMTI1MGNkYjljYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E4QMxUPWqMRZjT2-LTqY6Un8wErbwERq3bY6YUL5ILo)
> 
> 和这个关系不大，主要是查看日志之类的，比如说安装或者重建应用过程中查看日志这些

同出现日志写爆服务器问题。。。
起因：
因是vps，只反代了1panel本身，升级10.3之前删除了本站代理，升级后启用高级功能，docker无限重启，几分钟后服务器就爆了。
结局：
删除log后，句柄未释放，空间没有实际腾出，误操作删除了系统.......没有日志能反馈了

**Comment by wanghe-fit2cloud** [comment]
v1.10.5-lts 版本已发布。
