### ISSUE TITLE
[FEATURE]希望支持RockyLinux安装

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#4584]
### 1Panel 版本

v1.10.4

### 请描述您的需求或者改进建议

尝试对RockyLinux安装1panel，报错
![PixPin_2024-04-19_10-56-23](https://github.com/1Panel-dev/1Panel/assets/63288007/49fba199-c81d-4a4c-8f4d-f54d79e2dc07)

显示不支持，使用安装命令：
```cmd
curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sh quick_start.sh
```

希望可以支持RockyLinux，RockyLinux作为与Red Hat Enterprise Linux®100% 1:1兼容的社区系统，也是centos的延续。

目前尝试宝塔安装是成功的，新的机器只能先用宝塔了，期待1panel早日跟进，感谢！

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述错误是由于 docker 官方提供的安装脚本不支持该操作系统导致，可以参考：

https://github.com/1Panel-dev/1Panel/issues/2616

**Comment by JAINKRE** [comment]
好的，感谢及时反馈！
