### ISSUE TITLE
[BUG] OpenResty反向代理home-assistant出错

### ISSUE THREAD

**Issue by mia0x75** [1Panel-dev/1Panel#4587]
### 1Panel 版本

1.10.3 1.10.4

### 问题描述
登录先显示登录错误，刷新就是下面

![截图 2024-04-19 11-33-32](https://github.com/1Panel-dev/1Panel/assets/5111356/37b98ae3-e792-48a7-bf5f-e4d35eab0c24)

再次开新Tab访问首页就是无法访问，服务端日志，http 444错误：

[19/Apr/2024:11:57:06 +0800] "GET / HTTP/2.0" 444

### 重现步骤

1，安装ha
2，新建网站（域名+端口，应该跟端口无关），代理地址127.0.0.1:8123，IPv6
3，配置证书，和调整配置文件（之前提过的BUG，如果不是端口模式则不需要调整），只监听第2步中端口号 ssl http2（真机只有IPv6，只配置了IPv6地址上的监听）
4，访问https://域名:端口，可以访问，但登录出错，初始化操作也应该会有一样的错误

还有一个1.10.2的主机，重复上面的操作，仅仅域名不同，没有任何问题。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
应用自身需要特殊配置，可以参考这篇文章：[HomeAssistant反向代理后访问出现400 BadRequest处理](https://www.guojiangbo.com/2021/12/28/homeassistant%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86%E5%90%8E%E8%AE%BF%E9%97%AE%E5%87%BA%E7%8E%B0400-badrequest%E5%A4%84%E7%90%86/)

**Comment by mia0x75** [comment]
> 感谢反馈。 应用自身需要特殊配置，可以参考这篇文章：[HomeAssistant反向代理后访问出现400 BadRequest处理](https://www.guojiangbo.com/2021/12/28/homeassistant%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86%E5%90%8E%E8%AE%BF%E9%97%AE%E5%87%BA%E7%8E%B0400-badrequest%E5%A4%84%E7%90%86/)

这个是做了处理，反馈的是1.10.2可以，后续版本nginx.conf改了一些东西，还有waf之类的，具体还没去比较，1.10.3/1.10.4都不行。OpenResty日志显示错误是444。
