### ISSUE TITLE
[BUG] 未授权访问授权许可证信息

### ISSUE THREAD

**Issue by R0A1NG** [1Panel-dev/1Panel#4589]
### 联系方式

Dooi

### 1Panel 版本

v1.10.4-lts

### 问题描述

面板接口未授权访问，可获取许可证名称和许可证对应用户名等信息

### 重现步骤

访问1panel面板/api/v1/licenses/get接口
![image](https://github.com/1Panel-dev/1Panel/assets/66672984/764abc97-565a-440e-adfd-2fce65367119)

**Comment by ssongliu** [comment]
感谢反馈，麻烦提供一下日志信息 `/opt/1panel/log/1Panel.log`

**Comment by R0A1NG** [comment]
> 感谢反馈，麻烦提供一下日志信息 `/opt/1panel/log/1Panel.log`

需要这日志哪些信息呢

**Comment by ssongliu** [comment]
> > 感谢反馈，麻烦提供一下日志信息 `/opt/1panel/log/1Panel.log`
> 
> 需要这日志哪些信息呢

噢 看错问题了，我们优化一下

**Comment by wanghe-fit2cloud** [comment]
v1.10.5-lts 版本已发布。
