### ISSUE TITLE
[BUG] WAF设置地区访问限制不生效

### ISSUE THREAD

**Issue by R0A1NG** [1Panel-dev/1Panel#4590]
### 联系方式

Dooi

### 1Panel 版本

v1.10.4-lts

### 问题描述

设置禁止访问后，使用国内IP仍能正常访问
![image](https://github.com/1Panel-dev/1Panel/assets/66672984/16a464a4-92f4-4f10-a6b6-28d14a0f3d06)

![image](https://github.com/1Panel-dev/1Panel/assets/66672984/fcd8173f-4994-4448-959a-c4f88998fabe)

### 重现步骤

网站开启waf，开启地区访问限制，再访问网站

**Comment by zhengkunwang223** [comment]
前端挂 CDN 了吗

**Comment by R0A1NG** [comment]
没挂cdn

**Comment by zhengkunwang223** [comment]
换 IP 也没有被拦截吗？

**Comment by R0A1NG** [comment]
> 换 IP 也没有被拦截吗？

我自己换了几个IP都能访问，但是在拦截记录里能看到公网其他IP的拦截记录了

**Comment by R0A1NG** [comment]
> 换 IP 也没有被拦截吗？

换IP也是没有拦截，不过其他类型规则是有拦截

**Comment by Alexzzz2008** [comment]
> 换 IP 也没有被拦截吗？
复议，  禁止 大陆地区 访问， 无效。   开启后 ，国内IP还是可以正常访问网站

**Comment by zhengkunwang223** [comment]
好的 我们复现一下

**Comment by zhengkunwang223** [comment]
我们在多个环境都没有复现此问题
可以在网站日志查看一下 IP 然后 去一些 IP 地址查询平台看一下 IP 的地址信息

**Comment by Alexzzz2008** [comment]
> 我们在多个环境都没有复现此问题 可以在网站日志查看一下 IP 然后 去一些 IP 地址查询平台看一下 IP 的地址信息

IP没有问题，是国内IP，有没有可能是从低版本升级上来的 遗留的问题？

**Comment by R0A1NG** [comment]
> > 我们在多个环境都没有复现此问题 可以在网站日志查看一下 IP 然后 去一些 IP 地址查询平台看一下 IP 的地址信息
> 
> IP没有问题，是国内IP，有没有可能是从低版本升级上来的 遗留的问题？

我觉得也是，日志中的IP确实是国内IP，还是能访问。

**Comment by zhengkunwang223** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/9bd44d34-0cda-4d4d-b0ef-0422a5bb8b90)
加一下我 然后我远程看一下

**Comment by R0A1NG** [comment]
> Referenc

同意下

**Comment by zhengkunwang223** [comment]
经过排查 是 WAF 全局设置的地区访问限制的开关没有开启

**Comment by Alexzzz2008** [comment]
> 经过排查 是 WAF 全局设置的地区访问限制的开关没有开启

为什么要全局开启  单独网站开启不行吗？   这种逻辑不合适吧， 我里面有几十个站，只需要个别站开启这项功能呢
