### ISSUE TITLE
[BUG]OpenResty 网站管理防盗链无法启用

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4592]
### 1Panel 版本

v1.10.4-lts

### 问题描述

如题。

### 重现步骤

1Panel 专业版 v1.10.4-lts
OpenResty 1.21.4.3-2-1-focal
网站开启防盗链会有报错提示：
服务内部错误: stderr: 2024/04/19 00:14:10 [emerg] 73#73: unknown directive “valid_referrers” in /usr/local/openresty/nginx/conf/conf.d/viimg.com.conf:39 nginx: [emerg] unknown directive “valid_referrers” in /usr/local/openresty/nginx/conf/conf.d/viimg.com.conf:39 nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.5-lts 版本已发布。
