### ISSUE TITLE
[FEATURE] 1Panel 专业版 WAF 显示各网站的请求概况 

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4595]
### 1Panel 版本

v1.10.4-lts

### 请描述您的需求或者改进建议

- 目前在用 v1.10.4-Its 专业版
- 注意到 WAF 可以查看请求概况
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/d277fc5e-a890-49a1-9456-d2ba2a3faf66)

- 但是这是整个服务器上所有网站的概况，**希望支持显示 每个网站 的概况**

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本优化

**Comment by zhengkunwang223** [comment]
网站监控功能已实现
