### ISSUE TITLE
[FEATURE]专业版 WAF CC 防御建议

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4597]
### 1Panel 版本

v1.10.4-lts

### 请描述您的需求或者改进建议

是否可以提供URL级CC防御规则。开启后，只对被攻击URL进行人机认证，不影响其它页面访问提高体验。
这样大大改善用户访问体验还可以很好的防御攻击请求
类似触摸云 [CDNWAF 文档介绍](https://wdk0pwf8ul.feishu.cn/wiki/HLycwDcEQigPCKkqlcgcPG0In4f?from=from_parent_docs)
URL 级防御，不需要复杂设置，仅被攻击的URL自动启动人机验证策略，其它未被攻击URL无需人机验证

### 请描述你建议的实现方案

![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/3a6c0991-5f49-43b7-850d-15bee7a40d41)

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
