### ISSUE TITLE
[FEATURE]添加 `禁止访问地区` 打开网页后的状态码，比如 403、502、404 等，并支持编辑页面内容

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4598]
### 1Panel 版本

v1.10.4-lts

### 请描述您的需求或者改进建议

如题。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
文件内容可以在 `全局设置` - `配置` - `拦截页面` 中修改，状态码会在后续版本优化。
