### ISSUE TITLE
[QUESTION]在用aapanel，是否可以平替？

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#460]
### 请描述您的问题

小白一枚，在用aa,想知道换用1panel是否可以直接安装并完整迁移数据到1panel？是否需要卸载aa再安装aapanel?
有必要的话是否可以出个无缝平替教程，毕竟里面1panel一些东西和宝塔挺像的，应该也是想吸引更多宝塔用户过来吧

**Comment by wanghe-fit2cloud** [comment]
由于 1Panel 底层是基于容器实现的，和 aa 在部分功能实现上可能会存在差异。
当前版本中，可以将 MySQL 数据库迁移到 1Panel，如果要实现 PHP 网站的迁移，还需要等下月即将发布的 v1.1 版本。

当前您可以参考 [B 站的视频教程](https://space.bilibili.com/510493147/channel/collectiondetail?sid=1199760)。

**Comment by hhun** [comment]
1Panel没这么差
`平替`可是贬义词喔！
