### ISSUE TITLE
[BUG]GPU 界面多网卡编号显示异常

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4600]
### 1Panel 版本

1.10.4-lts

### 问题描述

![图片](https://github.com/1Panel-dev/1Panel/assets/30285739/68c4c35f-d2da-4d3c-95a5-a5c360cd3a2a)

### 重现步骤

如图

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们将在下个版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.5-lts 版本已发布。
