### ISSUE TITLE
[BUG] 创建网站->静态网站->服务内部错误

### ISSUE THREAD

**Issue by yqchilde** [1Panel-dev/1Panel#4601]
### 联系方式

yqchilde@gmail.com

### 1Panel 版本

社区版：v1.10.5-tls

### 问题描述

创建网站时报错
服务内部错误: open /opt/1panel/apps/openresty/openresty/1pwaf/data/conf/sites.json: no such file or directory

<img width="1032" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/36953759/89c8a3c3-223f-46bd-bdae-663289959698">

### 重现步骤

1. 创建网站
2. 静态网站
3. 确认

**Comment by zhengkunwang223** [comment]
更新 1Panel 到最新版本 
更新 OpenResty

**Comment by yqchilde** [comment]
看到应用中心可更新了，已解决👍🏻

**Comment by boommanpro** [comment]
1panel挂载openresty下，当前openresty更新失败后无法访问了，不想使用nginx重新配置，如何手动拉起或者恢复openresty
