### ISSUE TITLE
[BUG]it-tools切换中文下有问题，官方的是正常的

### ISSUE THREAD

**Issue by youngledo** [1Panel-dev/1Panel#4604]
### 1Panel 版本

1.10.5

### 问题描述

安装的it-tools发现切换到中文有问题，但it-tools官网（[https://it-tools.tech/](https://it-tools.tech/)）却正常，我看两者版本都一样的。
![image](https://github.com/1Panel-dev/1Panel/assets/68590897/5737e13e-5c1d-471c-b4d8-cb5800122ddf)

### 重现步骤

安装最新版本的it-tools即可复现

### 期待的正确结果

![image](https://github.com/1Panel-dev/1Panel/assets/68590897/1095cec8-538a-4630-94c3-50573d8a1dce)
中文显示正常

**Comment by wanghe-fit2cloud** [comment]
经验证，使用官方提供的安装命令安装应用，和 1Panel 应用商店结果一致。
> 可以将问题反馈到 it-tools 官方。
