### ISSUE TITLE
[BUG] 更新至新版后无法启动和回滚

### ISSUE THREAD

**Issue by dtapps** [1Panel-dev/1Panel#4606]
### 1Panel 版本

已无法查看

### 问题描述

4月19日通过后台更新至新版（[v1.10.4-lts](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.4-lts)）后无法启动和回滚程序，都提示异常！！！

### 重现步骤

1、登录后台面板点击更新（每次更新都是一会就刷新后台，版本没有变化）
2、尝试更新几次后查看日志显示更新成功
3、手动停止面板（1pctl stop）

### 期待的正确结果

恢复程序

### 相关日志输出

```shell
# 1pctl version
/usr/local/bin/1pctl: line 97:   927 Segmentation fault      1panel version


# 1pctl start
* 1panel.service - 1Panel, a modern open source linux panel
     Loaded: loaded (/etc/systemd/system/1panel.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: signal) since Sat 2024-04-20 09:41:41 CST; 2ms ago
    Process: 917 ExecStart=/usr/bin/1panel (code=killed, signal=SEGV)
   Main PID: 917 (code=killed, signal=SEGV)
        CPU: 946us

Apr 20 09:41:41 1Panel systemd[1]: 1panel.service: Main process exited, code=killed, status=11/SEGV
Apr 20 09:41:41 1Panel systemd[1]: 1panel.service: Failed with result 'signal'.

# 1pctl restore
1Panel 将会恢复至上一个稳定版本，是否继续 [y/n] : y

/usr/local/bin/1pctl: line 84:   733 Segmentation fault      1panel restore
* 1panel.service - 1Panel, a modern open source linux panel
     Loaded: loaded (/etc/systemd/system/1panel.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: signal) since Sat 2024-04-20 09:35:49 CST; 7ms ago
    Process: 755 ExecStart=/usr/bin/1panel (code=killed, signal=SEGV)
   Main PID: 755 (code=killed, signal=SEGV)
        CPU: 1ms

/usr/local/bin/1pctl: line 84:   758 Segmentation fault      1panel version
```

**Comment by DoyoDia** [comment]
https://github.com/1Panel-dev/1Panel/issues/4614 
你的磁盘占用正常吗，会不会跟我一样磁盘爆了

**Comment by maninhill** [comment]
v1.10.5 已经解决该问题，请升级一下。

**Comment by maninhill** [comment]
<img width="771" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/41712985/84ef4a94-a21c-47a2-af18-13dc0d1cf80f">

**Comment by dtapps** [comment]
> v1.10.5 已经解决该问题，请升级一下。

执行那个命令升级？？？

`
# 1pctl      
1Panel 控制脚本

Usage: 
  ./1pctl [COMMAND] [ARGS...]
  ./1pctl --help

Commands: 
  status              查看 1Panel 服务运行状态
  start               启动 1Panel 服务
  stop                停止 1Panel 服务
  restart             重启 1Panel 服务
  uninstall           卸载 1Panel 服务
  user-info           获取 1Panel 用户信息
  listen-ip           切换 1Panel 监听 IP
  version             查看 1Panel 版本信息
  update              修改 1Panel 系统信息
  reset               重置 1Panel 系统信息
  restore             恢复 1Panel 服务及数据
`

文档里是 [在线升级](https://1panel.cn/docs/installation/online_upgrade/) ，都进不去了....

**Comment by DoyoDia** [comment]
使用du -a -h /opt/1panel/log 看你哪个日志文件最大给你磁盘干爆了，就给那个文件删了，然后reboot之后就可以进面板正常升级了

**Comment by dtapps** [comment]
> 使用du -a -h /opt/1panel/log 看你哪个日志文件最大给你磁盘干爆了，就给那个文件删了，然后reboot之后就可以进面板正常升级了

额，不是日志问题呢 /opt/1panel/log 目录才72k
`
# du -sh
72K     .
`

**Comment by wanghe-fit2cloud** [comment]
```shell
journalctl -u 1panel.service -exf
```
上述命令查看一下 1Panel 详细日志，重点关注一下 ERROR。

**Comment by dtapps** [comment]
> ```shell
> journalctl -u 1panel.service -exf
> ```
> 
> 上述命令查看一下 1Panel 详细日志，重点关注一下 ERROR。

没有error，只有重复这两个
`
1Panel systemd[1]: 1panel.service: Main process exited, code=killed, status=11/SEGV
1Panel systemd[1]: 1panel.service: Failed with result 'signal'.
1panel.service has entered the 'failed' state with result 'signal'.
`

**Comment by wanghe-fit2cloud** [comment]
> 没有error，只有重复这两个
> `1Panel systemd[1]: 1panel.service: Main process exited, code=killed, status=11/SEGV 1Panel systemd[1]: 1panel.service: Failed with result 'signal'. 1panel.service has entered the 'failed' state with result 'signal'.`

无法正确定位问题。
你在微信交流群中添加一下 `王贺` 企业微信，远程你环境看一下。
