### ISSUE TITLE
[FEATURE]添加对数据库MongoDB的支持

### ISSUE THREAD

**Issue by Angelhellwolf** [1Panel-dev/1Panel#4607]
### 1Panel 版本

1.10.5-lts

### 请描述您的需求或者改进建议

现在可以管理Redis和MySQL，但是无法方便的管理MongoDB。

### 请描述你建议的实现方案

NULL

### 附加信息

NULL

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/399
