### ISSUE TITLE
[BUG] <Sites / SSL> 改进泛域名证书通过手动 DNS 解析申请时的 DNS 修改提示

### ISSUE THREAD

**Issue by Minoricew** [1Panel-dev/1Panel#4609]
### 1Panel 版本

v1.10.5-lts

### 问题描述

如果尝试在 1Panel 中通过手动 DNS 解析的方式申请一个泛域名证书, 1Panel 提示的 DNS 修改指向将不正确, 这会引发用户误解并导致证书申请失败。

### 重现步骤

1. 尝试在 1Panel 中使用 "**手动解析**" 的验证方式提交一个**泛域名证书**申请, 例如:
<img src="https://s2.loli.net/2024/04/20/57HpstG3DnIAuyE.png" height="677" width="345"></img>
2. 单击"确认", 回到证书列表, 单击 "申请". 此时 1Panel 会弹出解析提示:
<img src="https://s2.loli.net/2024/04/20/GjpVm73AbYXoUlc.png"></img>
3. 尝试前往 DNS 提供商侧修改 **_acme-challenge.\*** 上的 TXT 记录值:
<img src="https://s2.loli.net/2024/04/20/PGCZKiwxL5Yq8bs.png"></img>
4. 返回查看 1Panel 申请日志, 发现申请失败, 错误日志应类似如图所示:
<img src="https://s2.loli.net/2024/04/20/cshDITaW7YxOV8p.png"></img>

### 期待的正确结果

事实上, 观察 ACME 日志可知, 应修改的目标解析不是 `_acme-challenge.*`, 而是 `_acme-challenge`。

<img src="https://s2.loli.net/2024/04/20/AY5R9wszDbKUi4N.png"></img>

因此, DNS 修改弹框中的"解析域名"也应该是 **_acme-challenge.example.org**, 不包含 `*`。建议 1Panel 针对泛域名证书申请的情况增加额外判定, 在泛域名证书申请时优化相关显示, 避免造成误解。

### 附加信息

针对同时申请泛域名和根域名证书的情况, 举个例子:
<img src="https://s2.loli.net/2024/04/20/ZJ2y9uzTerj7LPI.png" ></img>
需要先将域名 `_acme-challenge` TXT 记录指向 ACME 第一个开始检查的域名所对应的值 (例如首先被检查的是 *.example.org, 那么此时先指向的应该就是 1Panel 提示中 `_acme-challenge.*` 的一项所对应的值)。等待第一个域名检查完成后, 再将 TXT 记录修改至第二个域名对应的值。

例如, 这样的情况中:
<img src="https://s2.loli.net/2024/04/20/wMa3SQG1ojl2zDf.png" ></img>
ACME 应该会先检查 *.example.org 的值, 此时 `_acme-challenge` 上的 TXT 值就应该为 `wIC51IAbvazviJ4ZhmGEvrqiiNb-w85U3mrWQAf_rAk`。
等待至申请日志中显示 *.example.org 检查通过, 开始检查 example.org 时, 此时应该再将值改为 `AgVdr7VJddNEHT3g4TTGA6dP-QsAv4ptk-I_myC8f2I`。

如果没有任何引导, 用户可能无法理解如何在此种状况下完成证书申请。建议 1Panel 同时也增加此种情况下的引导。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by Beelkic** [comment]
已经过去3-4个月了，1panel还是无任何优化及缓解措施，很失望

**Comment by Minoricew** [comment]
> 已经过去3-4个月了，1panel还是无任何优化及缓解措施，很失望

大概是被遗忘了吧 (((

**Comment by Beelkic** [comment]
> > 已经过去3-4个月了，1panel还是无任何优化及缓解措施，很失望
> 
> 大概是被遗忘了吧 (((

我现在换成宝塔了，起码功能正常，1panel连这点基础的都做不好

**Comment by Minoricew** [comment]
> > > 已经过去3-4个月了，1panel还是无任何优化及缓解措施，很失望
> > 
> > 
> > 大概是被遗忘了吧 (((
> 
> 我现在换成宝塔了，起码功能正常，1panel连这点基础的都做不好

宝塔广告有点多, 用开心版容易被塞后门。

**Comment by 129duckflew** [comment]
> > 已经过去3-4个月了，1panel还是无任何优化及缓解措施，很失望
> 
> 大概是被遗忘了吧 (((

多谢大佬的提醒，如果我没有搜索到这里的话，可能也被误导了直接就是配置了错误的泛域名解析了，希望官方能尽快修复这个问题

**Comment by zhengkunwang223** [comment]
感谢用户们的建议 解析域名和记录值是从证书发行商处获取 泛域名可能得特殊处理一下

**Comment by xvus** [comment]
解决了这个问题，还是继续用1p，不用BT了

**Comment by AlrclyGit** [comment]
我是宝塔用户，想着来尝试 1Panel 没想到就遇到这个问题了。其实有问题很正常，就是这个处理速度让我对 1Panel 的好感大打折扣。

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
