### ISSUE TITLE
[FEATURE]希望增加对LDAP的支持

### ISSUE THREAD

**Issue by duxdyu** [1Panel-dev/1Panel#4612]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

希望增加对LDAP的支持，比方说这个项目可能就可以https://github.com/osixia/docker-openldap
对应的其他支持ldap认证的应用也增加ldap的选项
希望禅道安装的时候能增加更多选项，比如配置数据库

**Comment by wanghe-fit2cloud** [comment]
> 希望增加对LDAP的支持，比方说这个项目可能就可以https://github.com/osixia/docker-openldap

重复 issue https://github.com/1Panel-dev/1Panel/issues/768

**Comment by wanghe-fit2cloud** [comment]
> 希望禅道安装的时候能增加更多选项，比如配置数据库

应用官方有支持其他数据库的说明吗？

**Comment by duxdyu** [comment]
> > 希望禅道安装的时候能增加更多选项，比如配置数据库
> 
> 应用官方有支持其他数据库的说明吗？

官方用的是mysql，内置在容器里了，想用统一的数据库服务器。官方文档的环境是这么写的
1. 禅道安装部署环境推荐使用 Linux + Apache + PHP7.0以上版本+ MySQL5.5以上版本/MariaDB的组合。Nginx其次，不推荐IIS + PHP组合。

2. 禅道需要使用PHP的这些扩展：pdo、pdo_mysql、json、filte、openssl、mbstring、zlib、curl、gd、iconv，企业版旗舰版还需要安装： zip、xml、ldap、bcmath扩展，请大家确保PHP环境安装加载以上扩展模块。

**Comment by wanghe-fit2cloud** [comment]
> > > 希望禅道安装的时候能增加更多选项，比如配置数据库
> > 
> > 
> > 应用官方有支持其他数据库的说明吗？
> 
> 官方用的是mysql，内置在容器里了，想用统一的数据库服务器。官方文档的环境是这么写的
> 
> 1. 禅道安装部署环境推荐使用 Linux + Apache + PHP7.0以上版本+ MySQL5.5以上版本/MariaDB的组合。Nginx其次，不推荐IIS + PHP组合。
> 2. 禅道需要使用PHP的这些扩展：pdo、pdo_mysql、json、filte、openssl、mbstring、zlib、curl、gd、iconv，企业版旗舰版还需要安装： zip、xml、ldap、bcmath扩展，请大家确保PHP环境安装加载以上扩展模块。

了解，可以通过创建 `PHP 运行环境` 网站来实现。
> 通过 `应用商店+容器镜像` 的方式就支持不了了。

**Comment by duxdyu** [comment]
> > > > 希望禅道安装的时候能增加更多选项，比如配置数据库
> > > 
> > > 
> > > 应用官方有支持其他数据库的说明吗？
> > 
> > 
> > 官方用的是mysql，内置在容器里了，想用统一的数据库服务器。官方文档的环境是这么写的
> > 
> > 1. 禅道安装部署环境推荐使用 Linux + Apache + PHP7.0以上版本+ MySQL5.5以上版本/MariaDB的组合。Nginx其次，不推荐IIS + PHP组合。
> > 2. 禅道需要使用PHP的这些扩展：pdo、pdo_mysql、json、filte、openssl、mbstring、zlib、curl、gd、iconv，企业版旗舰版还需要安装： zip、xml、ldap、bcmath扩展，请大家确保PHP环境安装加载以上扩展模块。
> 
> 了解，可以通过创建 `PHP 运行环境` 网站来实现。
> 
> > 通过 `应用商店+容器镜像` 的方式就支持不了了。

其实还是挺好配置的，配置数据库的文件在这里/opt/1panel/apps/zentao/zentao/data/zentao/config，手动改了一下还行，如果能像其他应用那样，在外面配参数就更好了。不过这个必须用root账号登录才能使用
`<?php
$config->installed       = true;
$config->debug           = false;
$config->requestType     = 'PATH_INFO';
$config->timezone        = 'Asia/Shanghai';
$config->db->driver      = 'mysql';
$config->db->host        = '1Panel-mysql-QKz5';
$config->db->port        = '3306';
$config->db->name        = 'zentao';
$config->db->user        = 'root';
$config->db->encoding    = 'UTF8';
$config->db->password    = 'mysql_AY8B6H';
$config->db->prefix      = 'zt_';
$config->webRoot         = getWebRoot();
$config->default->lang   = 'zh-cn';`

**Comment by ysicing** [comment]
https://github.com/quicklyon/zentao-docker?tab=readme-ov-file#%E4%BA%94%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F @duxdyu  是支持环境变量配置的
