### ISSUE TITLE
[BUG]未知原因造成的log文件过大，撑爆系统硬盘

### ISSUE THREAD

**Issue by DoyoDia** [1Panel-dev/1Panel#4614]
### 1Panel 版本

大概是1.10.3-lts 或1.10.4-lts

### 问题描述

未知原因造成的log文件爆炸，达到54g（因为只有54G可用空间，而不是只会产生54G）
![4318fc269379d57457df79ae867a2f64](https://github.com/1Panel-dev/1Panel/assets/79502694/bde84e67-8056-45be-86f5-58ac9f547295)
事发前的操作可能包含：将1panel版本从1.10.3升级至1.10.4
但现在1pctl版本查询值为空，且web界面打不开，所以无法确定
![image](https://github.com/1Panel-dev/1Panel/assets/79502694/ac6ad0c1-43d5-42fc-bb69-e801e2bc59f0)
可以确定进行过的操作：打开azure的见解功能，其会在机器上部署一个agent用于监控系统各项指标
等我登录上机器的时候这个服务正在不断的CPU占用100%然后被重启
不过不能确定是硬盘满了造成的，还是这玩意在这台机器上会一直重启

btop观察占用可见1panel和openssl CPU占用交替达到100%（重启后只有openssl的占用不时达到100%）

### 重现步骤

打开azure 见解
可能：将1panel版本从1.10.3升级至1.10.4

### 相关日志输出

```shell
54G的日志我下不下来啊（
```

**Comment by DoyoDia** [comment]
我试了下vim直接打开那个51G的log文件，机器直接卡死了（）

**Comment by DoyoDia** [comment]
![9a1decb875b7ecb9245ddec95c589cfa](https://github.com/1Panel-dev/1Panel/assets/79502694/9ce6dba8-acd3-479e-8005-144e070b274d)
![250d9e495f6e332687e3cb9804616bd6](https://github.com/1Panel-dev/1Panel/assets/79502694/58d92df8-8df8-44d6-b41b-9f1ddd62c7ea)
感觉应该后面就是同样的内容了，滑了五千多行都是这样

**Comment by DoyoDia** [comment]
版本确定1.10.4-tls

**Comment by maninhill** [comment]
v1.10.5-lts 已经修复该问题，请升级解决。

**Comment by maninhill** [comment]
<img width="771" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/41712985/1b8e91c6-4269-45b2-9a38-7ed5191c2ce6">

**Comment by DoyoDia** [comment]
更新后已解决 感谢 @maninhill
