### ISSUE TITLE
[BUG] 面板突然无法访问

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#4615]
### 1Panel 版本

v1.10.2-lts

### 问题描述

面板无法访问，也无法进行更新操作
<img width="1116" alt="图片" src="https://github.com/1Panel-dev/1Panel/assets/15864713/a7a50108-f8aa-4ad5-92f3-f5048105cce8">

### 重现步骤

更新 openresty 后出现的

**Comment by wanghe-fit2cloud** [comment]
是在网站页面创建的 `反向代理网站` 来访问的 1Panel 吗？
可以先尝试将 1Panel 服务器的 IP 地址添加到 WAF IP 白名单

**Comment by mx2913** [comment]
已经无法访问了，尝试备份数据然后重新安装 1panel，将数据目录复制后依然无法访问

**Comment by wanghe-fit2cloud** [comment]
> 已经无法访问了，尝试备份数据然后重新安装 1panel，将数据目录复制后依然无法访问

`1pctl status` 命令查看服务运行状态。
`1pctl restore` 命令可以回滚只上一个稳定版本。

**Comment by mx2913** [comment]
回退后重新升级可以，但是在社区版中开启了 waf 之后，所有的网站都无法访问，关闭 waf 也是同样的结果

**Comment by mx2913** [comment]
目前是面板通过域名访问之后就会出现跟前面类似的问题，
目前域名是通过页面创建的 `反向代理网站`来访问的，没有开启面板的 `https` 功能
<img width="920" alt="图片" src="https://github.com/1Panel-dev/1Panel/assets/15864713/01e2c696-e44e-4d15-a656-92ccd0d0ed48">

**Comment by zhengkunwang223** [comment]
> 目前是面板通过域名访问之后就会出现跟前面类似的问题， 目前域名是通过页面创建的 `反向代理网站`来访问的，没有开启面板的 `https` 功能 <img alt="图片" width="920" src="https://private-user-images.githubusercontent.com/15864713/324191097-01e2c696-e44e-4d15-a656-92ccd0d0ed48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NjYzMDYsIm5iZiI6MTcxMzY2NjAwNiwicGF0aCI6Ii8xNTg2NDcxMy8zMjQxOTEwOTctMDFlMmM2OTYtZTQ0ZS00ZDE1LWE2NTYtOTJjY2QwZDBlZDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDAyMjAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NDZkMzZkMmRlOGZkMDVkMjk2MGJjMzNkNTNkZTlhN2MxNzdkMjQzMDQwMzU0NDZiMzEyMDViYzZmOTA1Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zm9taTuUgwUeItWjmWAq2344SKKqgRyT0MpXXKqlwyw">

你没有开启 https 但是看你的控制台中有很多 https 请求
考虑是浏览器缓存 清除浏览器缓存 或者 换个浏览器试试

**Comment by mx2913** [comment]
> > 目前是面板通过域名访问之后就会出现跟前面类似的问题， 目前域名是通过页面创建的 `反向代理网站`来访问的，没有开启面板的 `https` 功能 <img alt="图片" width="920" src="https://private-user-images.githubusercontent.com/15864713/324191097-01e2c696-e44e-4d15-a656-92ccd0d0ed48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NjYzMDYsIm5iZiI6MTcxMzY2NjAwNiwicGF0aCI6Ii8xNTg2NDcxMy8zMjQxOTEwOTctMDFlMmM2OTYtZTQ0ZS00ZDE1LWE2NTYtOTJjY2QwZDBlZDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDAyMjAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NDZkMzZkMmRlOGZkMDVkMjk2MGJjMzNkNTNkZTlhN2MxNzdkMjQzMDQwMzU0NDZiMzEyMDViYzZmOTA1Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zm9taTuUgwUeItWjmWAq2344SKKqgRyT0MpXXKqlwyw">
> 
> 你没有开启 https 但是看你的控制台中有很多 https 请求 考虑是浏览器缓存 清除浏览器缓存 或者 换个浏览器试试

这个 `https` 是通过 `openresty` 反向代理的，面板本身没有开启 https 访问，主要的问题是 mime 类型出错了

**Comment by zhengkunwang223** [comment]
> > > 目前是面板通过域名访问之后就会出现跟前面类似的问题， 目前域名是通过页面创建的 `反向代理网站`来访问的，没有开启面板的 `https` 功能 <img alt="图片" width="920" src="https://private-user-images.githubusercontent.com/15864713/324191097-01e2c696-e44e-4d15-a656-92ccd0d0ed48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NjYzMDYsIm5iZiI6MTcxMzY2NjAwNiwicGF0aCI6Ii8xNTg2NDcxMy8zMjQxOTEwOTctMDFlMmM2OTYtZTQ0ZS00ZDE1LWE2NTYtOTJjY2QwZDBlZDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDAyMjAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NDZkMzZkMmRlOGZkMDVkMjk2MGJjMzNkNTNkZTlhN2MxNzdkMjQzMDQwMzU0NDZiMzEyMDViYzZmOTA1Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zm9taTuUgwUeItWjmWAq2344SKKqgRyT0MpXXKqlwyw">
> > 
> > 
> > 你没有开启 https 但是看你的控制台中有很多 https 请求 考虑是浏览器缓存 清除浏览器缓存 或者 换个浏览器试试
> 
> 这个 `https` 是通过 `openresty` 反向代理的，面板本身没有开启 https 访问，主要的问题是 mime 类型出错了

IP  端口可以直接访问吗

**Comment by mx2913** [comment]
> > > > 目前是面板通过域名访问之后就会出现跟前面类似的问题， 目前域名是通过页面创建的 `反向代理网站`来访问的，没有开启面板的 `https` 功能 <img alt="图片" width="920" src="https://private-user-images.githubusercontent.com/15864713/324191097-01e2c696-e44e-4d15-a656-92ccd0d0ed48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NjYzMDYsIm5iZiI6MTcxMzY2NjAwNiwicGF0aCI6Ii8xNTg2NDcxMy8zMjQxOTEwOTctMDFlMmM2OTYtZTQ0ZS00ZDE1LWE2NTYtOTJjY2QwZDBlZDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDAyMjAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NDZkMzZkMmRlOGZkMDVkMjk2MGJjMzNkNTNkZTlhN2MxNzdkMjQzMDQwMzU0NDZiMzEyMDViYzZmOTA1Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zm9taTuUgwUeItWjmWAq2344SKKqgRyT0MpXXKqlwyw">
> > > 
> > > 
> > > 你没有开启 https 但是看你的控制台中有很多 https 请求 考虑是浏览器缓存 清除浏览器缓存 或者 换个浏览器试试
> > 
> > 
> > 这个 `https` 是通过 `openresty` 反向代理的，面板本身没有开启 https 访问，主要的问题是 mime 类型出错了
> 
> IP 端口可以直接访问吗

通过 `ip:port` 可以访问，但是通过面板配置的代理就无法访问了，一直出现前面截图的问题

**Comment by mx2913** [comment]
发现是反向代理默认配置的限流有问题，把原有的 `limit_conn perserver` 从 10 改成 20 就行了
![图片](https://github.com/1Panel-dev/1Panel/assets/15864713/27b86fd6-3bb6-4264-bff0-23ebe801b0d5)

**Comment by zhengkunwang223** [comment]
> 发现是反向代理默认配置的限流有问题，把原有的 `limit_conn perserver` 从 10 改成 20 就行了 ![图片](https://private-user-images.githubusercontent.com/15864713/325886203-27b86fd6-3bb6-4264-bff0-23ebe801b0d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTcyNDAsIm5iZiI6MTcxNDExNjk0MCwicGF0aCI6Ii8xNTg2NDcxMy8zMjU4ODYyMDMtMjdiODZmZDYtM2JiNi00MjY0LWJmZjAtMjNlYmU4MDFiMGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA3MzU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NzY4MTAyNmFiYjIyZDYwOGMxNjg0MjMzNmJjZjY4MmUwYzZhNzI4ZWMwOGVmZTczNWJiZmEwZjJkMTQ1NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.owv6X-Eak_6uOYU0Mf3ZlEMr1l0m5DMz92MqWBsxyQY)

我们默认的配置为 
    limit_conn perserver 300; 
    limit_conn perip 25; 
    limit_rate 512k;

**Comment by mx2913** [comment]
> > 发现是反向代理默认配置的限流有问题，把原有的 `limit_conn perserver` 从 10 改成 20 就行了 ![图片](https://private-user-images.githubusercontent.com/15864713/325886203-27b86fd6-3bb6-4264-bff0-23ebe801b0d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTcyNDAsIm5iZiI6MTcxNDExNjk0MCwicGF0aCI6Ii8xNTg2NDcxMy8zMjU4ODYyMDMtMjdiODZmZDYtM2JiNi00MjY0LWJmZjAtMjNlYmU4MDFiMGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA3MzU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NzY4MTAyNmFiYjIyZDYwOGMxNjg0MjMzNmJjZjY4MmUwYzZhNzI4ZWMwOGVmZTczNWJiZmEwZjJkMTQ1NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.owv6X-Eak_6uOYU0Mf3ZlEMr1l0m5DMz92MqWBsxyQY)
> 
> 我们默认的配置为 limit_conn perserver 300; limit_conn perip 25; limit_rate 512k;

这一块并没有配置过，暂时不清楚是怎么变成的，不知道是不是之前尝试了 waf 功能导致的
