### ISSUE TITLE
[BUG] 更新后 waf 有点问题,有个网站访问不了,被拦截了

### ISSUE THREAD

**Issue by soonxf** [1Panel-dev/1Panel#4620]
### 联系方式

soonxf@dingtalk.com

### 1Panel 版本

1.10.5

### 问题描述

网站被拦截
![image](https://github.com/1Panel-dev/1Panel/assets/43446813/66f7f67b-9487-4e8d-8790-2759871174bd)

### 重现步骤

容器内部署 chatgpt-next-web
然后通过 OpenResty 反向代理
就不能访问了,关闭 waf 总开关就能访问

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
你可以先尝试将 你自己的 IP 地址添加到 WAF IP 白名单。

**Comment by zhengkunwang223** [comment]
可以看一下这个
https://bbs.fit2cloud.com/t/topic/4540/2
