### ISSUE TITLE
[BUG]升级最新版本的openresty之后，导致反代都用不了

### ISSUE THREAD

**Issue by mzhifu** [1Panel-dev/1Panel#4622]
### 1Panel 版本

v1.10.5-lts

### 问题描述

升级最新版本的openresty之后，导致反代都用不了。openresty容器内部报错：init_by_lua_file error: cannot open /usr/local/openresty/1pwaf/init.lua: No such file or directory，我手动在本地./1pwaf/data下边创建init.lua，也是无法正常启动

### 重现步骤

升级最新版本的openresty之后，导致反代都用不了。openresty容器内部报错：init_by_lua_file error: cannot open /usr/local/openresty/1pwaf/init.lua: No such file or directory，我手动在本地./1pwaf/data下边创建init.lua，也是无法正常启动

**Comment by zhengkunwang223** [comment]
应该是镜像没有拉下来

docker pull 1panel/openresty:1.21.4.3-2-1-focal

手动拉取一下，然后重建

**Comment by fonlan** [comment]
我也遇到了，手动docker pull也报错，所有反代全瘫痪了：
```
root@nginx:~# docker pull 1panel/openresty:1.21.4.3-2-1-focal
1.21.4.3-2-1-focal: Pulling from 1panel/openresty
a40f6c662dc5: Extracting [==================================================>]  24.43MB/24.43MB
2d61095701d4: Download complete 
1748521bb80d: Download complete 
19e4c50a7343: Download complete 
c27e6986b764: Download complete 
1453160b3d05: Download complete 
cabadf8df30d: Download complete 
813df452028f: Download complete 
9836b4e58e4d: Download complete 
d3ce61880f8e: Download complete 
44b32a3443e6: Download complete 
add95d98e1ea: Download complete 
31cba18d92f6: Download complete 
fe5e2bfa3b13: Download complete 
73510737ea11: Download complete 
70d1e3658d7d: Download complete 
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: archive/tar: invalid tar header
``` 
能否在升级失败的时候回滚老版本？毕竟老版本的image本地还是在的

**Comment by mzhifu** [comment]
我是centos机器，pull镜像 抱着个错，后边我在windows pull了下，手动上传到了服务器，才好了……

**Comment by fonlan** [comment]
OK，我这儿解决了。原因是之前用的docker是docker.io里带的docker 20.10.24。按官方的guide卸载安装最新的docker 26.0.2后问题解决。
https://docs.docker.com/engine/install/debian/
