### ISSUE TITLE
[BUG]开启防篡改一直加载，最后请求超时和添加排除目录保存无效也请求超时，好像防篡改拦截了没统计

### ISSUE THREAD

**Issue by 7457994** [1Panel-dev/1Panel#4623]
### 联系方式

7457994@qq.com

### 1Panel 版本

v1.10.5-lts

### 问题描述

开启防篡改一直加载，最后请求超时和添加排除目录保存无效也请求超时，好像防篡改拦截了没统计
![微信图片_20240421204609](https://github.com/1Panel-dev/1Panel/assets/41111860/cbfdabd9-2567-4e1f-87e6-fe305e209c46)

### 重现步骤

开启防篡改一直加载，最后请求超时和添加排除目录保存无效也请求超时，好像防篡改拦截了没统计
![微信图片_20240421204609](https://github.com/1Panel-dev/1Panel/assets/41111860/cbfdabd9-2567-4e1f-87e6-fe305e209c46)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本优化上述功能。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
