### ISSUE TITLE
[FEATURE] 优化  创建网站可以使用相同域名

### ISSUE THREAD

**Issue by likesrt** [1Panel-dev/1Panel#4624]
### 1Panel 版本

专业版：V1.10.5-Its

### 请描述您的需求或者改进建议

创建网站的时候主域名和其他域名填写相同域名可以成功创建。创建成功后打开网站管理感觉很抽象

### 附加信息

![Clip_2024-04-21_21-22-37](https://github.com/1Panel-dev/1Panel/assets/31208912/759b05b1-13cb-480f-8a02-082b7079c07e)
![f959cc3b0763cebe5b247559de77beb](https://github.com/1Panel-dev/1Panel/assets/31208912/17203aba-567b-47b8-91f3-a7188075ed51)

**Comment by zhengkunwang223** [comment]
感谢反馈 后续版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.10.6-lts 版本已发布。
