### ISSUE TITLE
[BUG] v1.10.5-lts版本 安装应用时提示用户无权限，然后自动退出登录；

### ISSUE THREAD

**Issue by arvin-up** [1Panel-dev/1Panel#4625]
### 1Panel 版本

v1.10.5-lts

### 问题描述

安装应用时提示用户无权限，然后自动退出登录；mysql可安装成功，安装redis或其他应用时出现上述问题

### 重现步骤

应用商店 -》 redis 安装 -》确认

### 期待的正确结果

redis安装成功

**Comment by ifdelete** [comment]
这个问题之前好像遇到过，如果你是用域名访问的话，可以换成IP+端口试试看，或者把面板的二级域名里的拦截全部放开应该就可以了，如果不是的话当我没说过，主要是之前遇到过类似的，也有人提过这个问题。

**Comment by MiderWong** [comment]
- 1、换成ip和端口能正常访问，因为`ip+端口`   `不受WAF规则限制`，同时可能会遇见其他诸如 `突然之间所有的域名都不可访问`、`使用自带编辑器编辑网站源代码提示无权限`、`安装应用提示无权限` 等提示，都是 `WAF规则导致的`，如果是本地运行，建议`关闭所有WAF规则`使用，`运行环境部署完整后正常使用时` 几乎不会复现。
- 2、这个问题在1.10.5发布后，在一台全新的服务器上部署时很容易复现，我是重装了三四次WSL2并且排查了所有问题之后才确定是WAF导致的。
### 以下使用场景都会大概率触发：
- 1、连续安装多个应用，如OpenResty、MySQL、Redis、MongoDB等常用应用同时安装
- 2、本机使用、使用hosts配置本地域名并且连续大量刷新网站(无reload模式的实时本地调试)，比如前后端同时开发，然后都配置了类似`xxx.local.test`这种本地域名，就很容易触发  `突然之间所有的域名都不可访问` 的情况
