### ISSUE TITLE
[BUG]无法启动面板

### ISSUE THREAD

**Issue by jsjdjdf** [1Panel-dev/1Panel#4627]
### 1Panel 版本

最新版本

### 问题描述

我从上一个版本1.10.4更新后，面板打不开，然后我去论坛看了后回滚，回滚几次都打不开面板，相关日志没截图，然后我卸载重新安装最新版本的1panel面板，但还是启动不起来，看论坛说日志log文件过大的问题，我去看了没有这个问题，所以我尝试重启机子，面板还是打不开，我查看端口命令，发现8080端口有打开，这是我选择启动1panel的端口

### 重现步骤

none

### 期待的正确结果

none

### 相关日志输出

```shell
none
```

### 附加信息

none

**Comment by ssongliu** [comment]
感谢反馈，麻烦提供一下 1pctl status 状态信息

**Comment by jsjdjdf** [comment]
> 感谢反馈，麻烦提供一下1pctl status状态信息

1panel.service - 1Panel, a modern open source linux panel
     Loaded: loaded (/etc/systemd/system/1panel.service; enabled; vendor >     Active: active (running) since Sun 2024-04-21 22:13:03 UTC; 3h 39min>   Main PID: 693763 (1panel)
     CGroup: /system.slice/1panel.service
             └─693763 /usr/bin/1panel
Apr 21 22:14:46 6660365905hax.localdomain 1panel[693763]: [2024-04-21 22:>Apr 22 00:00:00 6660365905hax.localdomain 1panel[693763]: [2024-04-22 00:>Apr 22 00:00:00 6660365905hax.localdomain 1panel[693763]: [2024-04-22 00:>Apr 22 00:00:00 6660365905hax.localdomain 1panel[693763]: [2024-04-22 00:>Apr 22 00:00:00 6660365905hax.localdomain 1panel[693763]: [2024-04-22 00:>Apr 22 00:00:00 6660365905hax.localdomain 1panel[693763]: [2024-04-22 00:>Apr 22 00:00:00 6660365905hax.localdomain 1panel[693763]: [2024-04-22 00:>Apr 22 00:00:01 6660365905hax.localdomain 1panel[693763]: [2024-04-22 00:>Apr 22 00:00:03 6660365905hax.localdomain 1panel[693763]: [2024-04-22 00:>Apr 22 
我记得第一次重装没弹啥ipv6的关键信息，第二次弹了下就没了

**Comment by ssongliu** [comment]
日志也麻烦提供一下，看看是不是监听到了 ipv4，服务器是 ipv6  吗？

**Comment by jsjdjdf** [comment]
> 日志也麻烦提供一下，看看是不是监听到了 ipv4，服务器是 ipv6 吗？

[2024-04-22 00:00:00] [INFO] AppStore scheduled task in progress ...  
[2024-04-22 00:00:00] [INFO] Starting synchronization with App Store...  
[2024-04-22 00:00:00] [INFO] Website scheduled task in progress ...  
[2024-04-22 00:00:00] [INFO] Website scheduled task has completed  
[2024-04-22 00:00:00] [INFO] The scheduled certificate update task is currently in progress ...  
[2024-04-22 00:00:00] [INFO] The scheduled certificate update task has completed  
[2024-04-22 00:00:01] [INFO] [AppStore] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
[2024-04-22 00:00:03] [INFO] The App Store is at the latest version  
[2024-04-22 00:00:03] [INFO] AppStore scheduled task has completed  
服务器是ipv6的，没有ipv4

**Comment by jsjdjdf** [comment]
感觉怎么看都没有问题，但就是打不开
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      693763/1panel
还有防火墙服务我也给关了

**Comment by ssongliu** [comment]
> 感觉怎么看都没有问题，但就是打不开 tcp 0 0 0.0.0.0:8080 0.0.0.0:* LISTEN 693763/1panel 还有防火墙服务我也给关了

加我一下
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/8ea04890-7efe-48e8-b88b-f15b822ac5ba)

**Comment by ssongliu** [comment]
服务监听的 ipv4，切换后服务正常启用

**Comment by BioLaoXu** [comment]
亲测发现1pctl 默认绑定的确实是ipv4，此时用`1pctl listen-ip ipv4`进行监听模式切换还是无法登录，此时试试`netstat -ntlp`看看1pctl 默认绑定的8090端口是否开放使用，如果没有，可能是防火墙的问题了，我这面是腾讯云的云服务器，去自己的云服务器的控制台》防火墙中将8090进行开放就可以访问1Panel的网页控制台了，出现类似问题可以试试，不保证成功/(ㄒoㄒ)/~~
![image](https://github.com/1Panel-dev/1Panel/assets/13416926/21fbc72c-ed74-4a5c-a319-81f56174a864)
