### ISSUE TITLE
[FEATURE] 希望数据库页面支持更多功能

### ISSUE THREAD

**Issue by LeviMarvin** [1Panel-dev/1Panel#463]
### 1Panel 版本

v1.0.4

### 请描述您的需求或者改进建议

现在的数据库页面只支持 MySQL 数据库，希望后续可以添加对 MariaDB 等数据库的支持。
希望增加数据库用户管理页面，可以查看某一数据库的用户并修改相关信息（如该用户密码等）。

**Comment by ValentinLiu15** [comment]
v1.4.3了，啥时候加这个呀

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
