### ISSUE TITLE
[BUG] SSL证书推送本地相关问题

### ISSUE THREAD

**Issue by liesauer** [1Panel-dev/1Panel#4630]
### 1Panel 版本

v1.10.5-lts

### 问题描述

1. 创建网站时，明明已经自动生成了ssl目录，而且在创建ssl证书时绑定了这个网站，生成的证书不会自动同步一份在ssl目录（不确定是不是BUG，前几个版本中，应该是会自动同步过去的，因为我有一个网站，ssl目录是有证书的）
2. 我主动勾选了推送到本地目录，选了任何目录都没法选进去，只能自己填

### 重现步骤

1. 创建网站
2. 新建SSL证书，并绑定域名

### 期待的正确结果

1. 创建SSL证书且绑定网站时，应该自动同步一份证书到网站ssl目录下（硬编码逻辑，不受推送到本地目录功能影响）
2. 修复推送到本地目录选不了目录的BUG

**Comment by zhengkunwang223** [comment]
1. 创建证书的时候选择网站并不是绑定网站 只是从网站获取域名用于申请证书
2. 这个没有复现

**Comment by liesauer** [comment]
edge 和 chrome 都试了选不进去，win10 和 win11 都一样，控制台没发现报错。

![GIF 2024-4-22 21-25-37](https://github.com/1Panel-dev/1Panel/assets/8676741/4a97ea70-78f4-4872-80cc-bba7981759e8)

![image](https://github.com/1Panel-dev/1Panel/assets/8676741/019cfa92-3368-4c94-987c-db4de996260a)

**Comment by liesauer** [comment]
懂了，这是需要自己手动点前面的勾选框才行啊，我还以为像windows对话框一样，最后那个确定就是选中的。
