### ISSUE TITLE
[BUG] 创建 PHP 8.2 运行环境失败

### ISSUE THREAD

**Issue by nuoling99** [1Panel-dev/1Panel#4631]
### 1Panel 版本

v1.10.2-lts、v1.10.5-lts

### 问题描述

尝试及更换了几次镜像，都卡在了如下错误：
镜像 build 失败:failed to solve: process "/bin/sh -c apk --no-cache add tzdata && cp \"/usr/share/zoneinfo/$TZ\" /etc/localtime && echo \"$TZ\" > /etc/timezone" did not complete successfully: exit code: 1

### 重现步骤

正常创建运行环境，选php 8.2.环境参数如下：
CONTAINER_PACKAGE_URL="mirrors.tuna.tsinghua.edu.cn"
DATA_DIR="./data"
IMAGE_NAME="1panel-php:8.2.15"
INSTALL_SUPERVISOR=0
PHP_EXTENSIONS="mysqli,pdo_mysql,zip,gd,redis,memcache,memcached,apcu,igbinary,imagick,msgpack,pcntl,pcre,posix,readline,sqlite3,opcache"
PHP_FPM_CONF_FILE="./php/php-fpm.conf"
PHP_LOG_DIR="./logs/php"
PHP_PHP_CONF_FILE="./php/php.ini"
PHP_VERSION="8.2.15"
SOURCE_DIR="./www"
TZ="Asia/Shanghai"
 

### 期待的正确结果

能够顺利安装

### 相关日志输出

```shell
镜像 build 失败:failed to solve: process "/bin/sh -c apk --no-cache add tzdata && cp \"/usr/share/zoneinfo/$TZ\" /etc/localtime && echo \"$TZ\" > /etc/timezone" did not complete successfully: exit code: 1
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
可以先在论坛中查找一下上述问题，如：
https://bbs.fit2cloud.com/t/topic/2286/
