### ISSUE TITLE
[BUG]日志审计的SSH登录日志，并没有清空日志功能，在工具箱里的缓存清理也并不能清理掉这个日志

### ISSUE THREAD

**Issue by hgc357341051** [1Panel-dev/1Panel#4632]
### 1Panel 版本

v1.10.5-lts

### 问题描述

日志审计的SSH登录日志，并没有清空日志功能，在工具箱里的缓存清理也并不能清理掉这个日志

### 重现步骤

日志审计的SSH登录日志，并没有清空日志功能，在工具箱里的缓存清理也并不能清理掉这个日志

**Comment by wanghe-fit2cloud** [comment]
SSH 登录日志是读取到服务器的日志文件，具体文件路径如下：
```
Ubuntu: /var/log/auth.log.*
CentOS: /var/log/secure*
```

如需删除、清空 SSH 登录日志，可以自行删除。
> 1Panel 暂不支持页面可视化清空记录功能。
