### ISSUE TITLE
[FEATURE]专业版既然都改界面和配置了，那就贯彻到底，希望隐藏一下这些

### ISSUE THREAD

**Issue by hgc357341051** [1Panel-dev/1Panel#4633]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/149741823/281dfa9e-c9e0-4205-b5f0-254b9ca34b38)
隐藏这些，至于飞致云版权这个，根据你们需要，可以留和不留，其他的隐藏一下，谢谢，我专业版已买，发电也支持了，希望在登录背景图，也增加一个图片链接设置，自定义登录背景，

**Comment by wanghe-fit2cloud** [comment]
后续版本可能会考虑支持用户自定义登录背景图。
> 文档、论坛等信息暂无计划支持用户自定义。
