### ISSUE TITLE
[BUG] 编译后的二进制文件内含一大堆网吧跟会所

### ISSUE THREAD

**Issue by YufengSoft** [1Panel-dev/1Panel#4635]
### 1Panel 版本

1Panel-1.10.5-lts

### 问题描述

分析 1Panel 的二进制文件，在 .noptrdata 段中存在大量网吧跟会所名称

### 重现步骤

分析 1Panel 的二进制文件，在 .noptrdata 段中存在大量网吧跟会所名称

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
`日志审计` - `面板日志` - `访问日志` 模块使用到了 纯真IP库 来解析登录地址。
