### ISSUE TITLE
[BUG]计算文件夹大小超时

### ISSUE THREAD

**Issue by fyzhu** [1Panel-dev/1Panel#4639]
### 1Panel 版本

1.10.5

### 问题描述

如果要计算大小的文件夹包含很多文件，耗时很长，会导致请求超时报错

### 重现步骤

计算大文件夹大小

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本针对计算文件夹大小超时问题持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.12-beta.3版本中，计算文件夹大小功能已优化为局部加载。
