### ISSUE TITLE
[FEATURE] 希望 Docker 容器页面支持修改操作

### ISSUE THREAD

**Issue by LeviMarvin** [1Panel-dev/1Panel#464]
### 1Panel 版本

v1.0.4

### 请描述您的需求或者改进建议

希望 Docker 容器页面支持修改操作，包括修改运行时的环境变量等设置，现在只要创建完容器后便无法修改容器。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本会支持该需求。

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
