### ISSUE TITLE
[BUG] WAF 界面显示错误

### ISSUE THREAD

**Issue by OuOumm** [1Panel-dev/1Panel#4640]
### 联系方式

issue联系

### 1Panel 版本

v1.10.5-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/43441064/2d640e71-636f-42fa-88fd-bcc2d15ea4bd)
![image](https://github.com/1Panel-dev/1Panel/assets/43441064/3421227a-e2b4-4b92-a5e8-e0909a170cb3)

还有为啥你们版本号不让复制了？反馈变难了

### 重现步骤

直接就是这样显示了

**Comment by zhengkunwang223** [comment]
感谢反馈 后续版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.10.6-lts 版本已发布。
