### ISSUE TITLE
[BUG]1Panel设置openresty反代崩溃

### ISSUE THREAD

**Issue by duyaTech** [1Panel-dev/1Panel#4644]
### 1Panel 版本

1.10.5

### 问题描述

使用应用商店安装emqx和openresty，openresty配置反向代理到emqx后台管理页面，一访问emqx页面就会导致1Panel崩溃，服务器重启后恢复，再次访问继续崩溃，烦请复现下，刚升级1Panel版本后出现的BUG。

### 重现步骤

1. 使用应用商店安装emqx和openresty
2. emqx后台管理端口为18083，通过openresty配置反向代理到emqx后台
3. 访问emqx后台即崩溃1Panel
4. 重启后恢复，再次访问继续崩溃
5. 升级前是正常的

### 期待的正确结果

可以正常进行emqx的反向代理

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/31816340/bd6b2859-4428-4b38-9fbf-a5a6d4710f6f)

**Comment by wanghe-fit2cloud** [comment]
建议参考 [EMQX 官方文档](https://www.emqx.io/docs/zh/latest/) 中关于 Nginx 配置相关描述。
> 1Panel 提供的是通用配置，关于应用自身的适配问题可以进入 `网站配置` - `配置文件` 中自行修改。
