### ISSUE TITLE
[BUG]面板磁盘IO监控显示问题

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#4647]
### 1Panel 版本

v1.10.5

### 问题描述

录屏如下：
![20240423-095021](https://github.com/1Panel-dev/1Panel/assets/63288007/3c30055e-52ac-42f4-95b7-2d74d9afa7e1)

如上所示，点击按钮后，过个几秒就自动刷新了

### 重现步骤

面板 > 磁盘IO监控

### 期待的正确结果

修复按钮错误

### 附加信息

Chrome 已是最新版本
版本 124.0.6367.61（正式版本） （64 位）

**Comment by JAINKRE** [comment]
测试了一下，流量监控也存在相同问题

**Comment by ssongliu** [comment]
感谢反馈，开发环境已经复现该问题，下个小版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.10.6-lts 版本已发布。
