### ISSUE TITLE
[FEATURE]应用异常状态时，支持导入备份文件进行恢复。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4649]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

如图。
升级、编辑应用等场景可能会造成启动异常，这时要放开备份和导入备份按钮
支持用户恢复或者自行上传文件进行恢复。
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/c7f0fccf-37ad-4cd7-b859-935f7903f5b1)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本完成上述功能优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
