### ISSUE TITLE
[BUG]升级专业版后容器内 supervisor 无法持久运行

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4653]
### 1Panel 版本

v1.10.5-lts

### 问题描述

在升级专业版之前是ok的，升级了专业版出现的，在容器终端连接某个容器后点返回、关闭、断开，都会导致supervisor进程退出，命令exit退出终端就没有这问题，
然后上个工单我不知道是不是我没说清楚，我大概介绍下情况：目前运行中的PHP容器，然后我需要在PHP容器内运行一些PHP cli常驻脚本，这些脚本只能在指定的PHP项目内运行，
然后我在PHP容器内安装了supervisor来保活这些脚本进程，未升级专业版之前，我已经正常运行很久了，正常理解只要我不重启这个容器都不会导致supervisor退出，
我看了最近的升级，https://github.com/1Panel-dev/1Panel/pull/4588 不知道和这个修复有没有关系

### 重现步骤

在升级专业版之前是ok的，升级了专业版出现的，在容器终端连接某个容器后点返回、关闭、断开，都会导致supervisor进程退出，命令exit退出终端就没有这问题，
然后上个工单我不知道是不是我没说清楚，我大概介绍下情况：目前运行中的PHP容器，然后我需要在PHP容器内运行一些PHP cli常驻脚本，这些脚本只能在指定的PHP项目内运行，
然后我在PHP容器内安装了supervisor来保活这些脚本进程，未升级专业版之前，我已经正常运行很久了，正常理解只要我不重启这个容器都不会导致supervisor退出，
我看了最近的升级，https://github.com/1Panel-dev/1Panel/pull/4588 不知道和这个修复有没有关系

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。

**Comment by MiderWong** [comment]
#### 补充当前BUG场景
- 1、社区版，运行环境的`PHP7`、`PHP8`中的`php命令`不管是否以`daemon`模式运行，都会在退出容器时关闭进程
- 2、社区版，运行环境的`PHP7`、`PHP8`中的`nohup命令`都会在退出容器时关闭进程
#### 需求
- 1、期待尽快发布新版本，因为我刚好有使用场景是`IM通信的负载均衡部署`，结果以下两个BUG全都卡在关键点上了，现在只能通过不用你们`自带的OpenResty`和`自带的`PHP运行环境`来部署。
- 2、解决BUG1：当前BUG
- 3、解决BUG2：使用`OpenResty`的`upstream`时会导致`OpenResty`无法使用(不知道这个bug是否修复，这里连带提一下)

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
