### ISSUE TITLE
[FEATURE]WordPress 应用支持修改 php 参数

### ISSUE THREAD

**Issue by wan92hen** [1Panel-dev/1Panel#466]
### 1Panel 版本

v1.0.4

### 请描述您的需求或者改进建议

默认安装的 WordPress 应用 upload_max_filesize 配置只有 2M，当上传大一点的文件时需要对这个参数进行修改，目前只能进到容器中修改 php 配置文件，但是这种修改方式不能持久化，当容器重建之后便会失效。

希望提供一种方式可以对 php 的配置项进行修改。

### 请描述你建议的实现方案

可以参考 phpMyAdmin 应用的处理方式，在 compose 文件中挂载额外的 php 配置文件。
![77daa27107a33e31799d6aeb6f9cd82](https://user-images.githubusercontent.com/27671436/229051139-d4306485-39fe-4eba-8c92-f638dec84802.png)

**Comment by zhengkunwang223** [comment]
感谢建议 我们会在后续版本支持

**Comment by wanghe-fit2cloud** [comment]
v1.1.3 版本已发布。
