### ISSUE TITLE
通过面板上传jar包，会导致jar包损坏[BUG]

### ISSUE THREAD

**Issue by waves86** [1Panel-dev/1Panel#4663]
### 联系方式

waves7178@gmail.com

### 1Panel 版本

1.10.5

### 问题描述

1.文件夹里存在jar包，在上传同名jar包，jar包运行显示损坏，其他文件没有测试
2.上传过一次文件后，再次点击上传选择该文件，无法上传

### 重现步骤

重复上传同一jar包

### 期待的正确结果

覆盖原有jar包

**Comment by zhengkunwang223** [comment]
好的 我们复现一下

**Comment by zhengkunwang223** [comment]
您好 经过我们测试 上传前后的 md5 并没有改变
能提供出问题的 jar 包吗？

**Comment by waves86** [comment]
刚刚我在重新试了一次又没有问题了，不好意思。但是重复上传是有问题的（第二条）

**Comment by wanghe-fit2cloud** [comment]
> 但是重复上传是有问题的（第二条）

文件上传成功后不手动关闭上传窗口页面，再次上传相同的文件不能点击右下角 `确认` 按钮吗？
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/c472ff32-ff1f-4b3b-b3a2-8e7bb4e840ba)

**Comment by waves86** [comment]
> > 但是重复上传是有问题的（第二条）
> 
> 文件上传成功后不手动关闭上传窗口页面，再次上传相同的文件不能点击右下角 按钮吗？`确认` ![图像](https://private-user-images.githubusercontent.com/46734380/325456407-c472ff32-ff1f-4b3b-b3a2-8e7bb4e840ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMTM5NDMsIm5iZiI6MTcxNDAxMzY0MywicGF0aCI6Ii80NjczNDM4MC8zMjU0NTY0MDctYzQ3MmZmMzItZmYxZi00YjNiLWIzYTItOGU3YmI0ZTg0MGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDAyNTQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NGY4ZGUxMjY5YTA2NTYxODllZjQyNTMzMTNmNzAyNThjNmIyZTJiZTNmNjc3MWRhYjdjYTA0NmVmYTBiZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-m-QzdYDHymtjGkiH8TiMjOHcW5QsZiD-vpTNhsLrEk)

是的

**Comment by wanghe-fit2cloud** [comment]
这里应该是上传控件限制了，我们后续看一下如何优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.6-lts 版本已发布。
