### ISSUE TITLE
[BUG]权限问题

### ISSUE THREAD

**Issue by jamsw1** [1Panel-dev/1Panel#4664]
### 联系方式

abc3900158@gmail.com

### 1Panel 版本

v1.10.5-tls

### 问题描述

编辑静态网站html文件会导致退出登录

### 重现步骤

创建静态网站后，编辑index里的html文件，点击保存后提示无权限并退出登录，已经给了文件777权限

**Comment by zhengkunwang223** [comment]
您好 可能是被 WAF 拦截了
参考 https://bbs.fit2cloud.com/t/topic/4540/2
1Panel 自身可以不开启 xss 和 参数规则
