### ISSUE TITLE
[BUG]网站设置中的安全按钮消失

### ISSUE THREAD

**Issue by lainbo** [1Panel-dev/1Panel#4666]
### 1Panel 版本

1.10.5-lts

### 问题描述

在网站设置中，顶部的“安全”按钮没有了，我知道我们的专业版中有更完善的waf，这是否意味着这个功能转为收费项目了

### 重现步骤

菜单-网站-打开任意一个网站

### 期待的正确结果

![image](https://github.com/1Panel-dev/1Panel/assets/46062895/f67d16cc-198d-4a12-83db-fd493871373a)

**Comment by zhengkunwang223** [comment]
您好 WAF 转移到了高级功能中 
依然是免费功能
具体可以查看 https://bbs.fit2cloud.com/t/topic/4407/14

**Comment by lainbo** [comment]
> 您好 WAF 转移到了高级功能中 依然是免费功能 具体可以查看 [bbs.fit2cloud.com/t/topic/4407/14](https://bbs.fit2cloud.com/t/topic/4407/14)

针对单个网站的 参数规则 是不是没有办法设置了呢？我看WAF - 网站设置 - 默认规则 - 参数规则，只能开/关，没有找到如何添加自己的参数规则，烦请指点
