### ISSUE TITLE
[BUG]主机终端滚动问题

### ISSUE THREAD

**Issue by sagezhj** [1Panel-dev/1Panel#4667]
### 联系方式

zhjah@163.com

### 1Panel 版本

v1.10.5-lts

### 问题描述

使用主机——》终端时，使用鼠标滚轮翻页过快，试过Firefox和edge都有这个问题，触摸板滚动没有问题

### 重现步骤

打开主机下面的终端页面，连接任意主机，运行屏显较多的命令，比如apt update，使用滚轮向上滚动会直接滚到第一页

### 期待的正确结果

使用滚轮应该类似触摸板，一次一页，或少于一页

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/3406
