### ISSUE TITLE
[FEATURE] 建议增加面板https

### ISSUE THREAD

**Issue by xiahao90** [1Panel-dev/1Panel#467]
### 1Panel 版本

1.0.4

### 请描述您的需求或者改进建议

建议增加面板https，并支持自定义证书。这样自己可以上传双向认证证书，面板端口的安全级别将非常高。

### 请描述你建议的实现方案

可以上传自定义证书，可以随机生成证书

**Comment by zhengkunwang223** [comment]
好的 感谢建议 我们会在后续版本支持

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
