### ISSUE TITLE
[BUG]网站备份保留数与实际不符

### ISSUE THREAD

**Issue by motao123** [1Panel-dev/1Panel#4671]
### 1Panel 版本

专业版： v1.10.5-lts

### 问题描述

因服务器磁盘不足，从而检查文件占用情况，发现备份保留文件与实际不相符

计划任务备份网站/数据库，保留2份

实际没有删除过期文件，导致服务器磁盘被占用

![微信截图_20240423194200.png](https://img.imotao.com/i/2024/04/23/66279f953dd74.png)
![微信截图_20240423194326.png](https://img.imotao.com/i/2024/04/23/66279f95da37b.png)

### 重现步骤

![微信截图_20240423194200.png](https://img.imotao.com/i/2024/04/23/66279f953dd74.png)
![微信截图_20240423194326.png](https://img.imotao.com/i/2024/04/23/66279f95da37b.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.6-lts 版本已发布。
