### ISSUE TITLE
[BUG]备份账号编辑信息显示错误

### ISSUE THREAD

**Issue by duyaTech** [1Panel-dev/1Panel#4675]
### 1Panel 版本

1.10.5

### 问题描述

配置1Panel备份账号SFTP，验证通过后sftp磁盘已增加文件，但是再次去重新编辑SFTP账号信息的时候，显示出来的用户名和密码值不是SFTP用户账号的对应信息，而是1Panel登陆的账号信息，是专门设计的吗还是异常，求教。

### 重现步骤

1.面板设置
2.备份账号
3.SFTP 编辑
4.用户名和密码不是SFTP的用户账号信息而是1Panel登录账号信息，很迷惑

### 期待的正确结果

显示SFTP的账号信息

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/31816340/d547b0a9-74be-4bec-be78-32fb3fa1f7cc)

**Comment by wanghe-fit2cloud** [comment]
编辑备份账号页面，系统不回显用户密码。
> 应该是浏览器记住了 1Panel 密码，然后面板设置这里使用的也是密码控件。
