### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by tqrj** [1Panel-dev/1Panel#4676]
### 1Panel 版本

当前运行版本：v1.9.6

### 请描述您的需求或者改进建议

有个小的建议，像一些基础容器 mysql 之类的 可以在安装的时候直接配置 日志级别，甚至是提供几个选项 类似生产 或者开发

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1Panel 在安装 MySQL 应用的时候，提供了标准的 my.cnf 配置文件，用户在安装成功后可以进入设置页面自行修改，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/2e6df12a-7b84-4365-aa41-85da1ba0a0a3)

> 由于 1Panel 应用商店应用采用封装模块儿化安装，暂不考虑在安装页面直接支持配置文件中参数的配置，望理解。
