### ISSUE TITLE
[FEATURE] waf拦截日志 清理与导出功能

### ISSUE THREAD

**Issue by meng-plus** [1Panel-dev/1Panel#4680]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/37764731/27c53284-ed35-4c80-8984-9293af74ce52)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本支持上述需求。

**Comment by zyyfit** [comment]
清理功能已添加

**Comment by wanghe-fit2cloud** [comment]
WAF 日志导出功能的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4940

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
