### ISSUE TITLE
计划任务建议增加自动更新应用选择和自动更新应用列表选择

### ISSUE THREAD

**Issue by cnxsu** [1Panel-dev/1Panel#4683]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

1.计划任务建议增加自动更新应用选择
2.自动更新应用列表选择

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，自动更新应用的需求可以考虑应用商店中的 `watchtower`。
