### ISSUE TITLE
[BUG] /opt/1panel/apps/openresty/openresty/1pwaf/data/conf/sites.json: no such file or directory

### ISSUE THREAD

**Issue by 0xddy** [1Panel-dev/1Panel#4684]
### 联系方式

111

### 1Panel 版本

v1.10.5-lts

### 问题描述

创建运行环境站点异常

服务内部错误: open /opt/1panel/apps/openresty/openresty/1pwaf/data/conf/sites.json: no such file or directory

### 重现步骤

原先创建了2个静态网站没有问题，今天1.10.2-lts 升级上来后 首次创建PHP站点就报错了

**Comment by wanghe-fit2cloud** [comment]
将 1Panel 和 OpenResty 同时升级到最新版本试一下。

**Comment by imkratos** [comment]
经测试，如果1p不是最新版本，安装最新版本的 OpenResty 就会提示这个错误，升级1p到最新版可以解决。
