### ISSUE TITLE
[FEATURE]能否出一个使用GIT源码打包部署的教程？

### ISSUE THREAD

**Issue by MiderWong** [1Panel-dev/1Panel#4686]
### 1Panel 版本

1.10.5

#### 需求原因
- 1、业务场景：`PHP项目IM的负载均衡部署，IM是在PHP环境运行后，执行`php xxx.php start -d`命令启动`
- 2、之前的BUG：`OpenResty`配置`Upstream`导致系统异常 ，只能通过自配置宿主机`OpenResty`使用，在`v1.10.3`版本已经修复解决：[#4438](https://github.com/1Panel-dev/1Panel/pull/4438)
- 3、升级后的BUG：`退出容器后，容器运行的命令也会退出`，之前这个功能是正常的，升级后才出现的这个BUG，目前只能通过宿主机的`PHP运行`，BUG地址：[#4563](https://github.com/1Panel-dev/1Panel/issues/4653#issue-2257884989)，虽然这个BUG已经修复了，但是只会在`v1.10.6`版本发布：[#4660](https://github.com/1Panel-dev/1Panel/pull/4660)

#### 需求建议
如果有一份**使用GIT源码打包部署的教程**，就可以在出现类似[#4563](https://github.com/1Panel-dev/1Panel/issues/4653#issue-2257884989)这种已经修复但是还未发布新版本并且影响实际业务运行的BUG时，通过本地打包部署来临时解决，而且我依稀记得之前官网的安装文档里有这个说明，因为我曾经安装过一个开发版本，但是现在找不到了。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前在 1Panel 官方文档中是有提供本地环境搭建教程的，地址如下：
https://1panel.cn/docs/dev_manual/dev_manual/

> 上述几点问题，我们会在近期版本推送更新。

**Comment by MiderWong** [comment]
#### dev安装
- 1、下载`quick_start.sh`后使用命令`export INSTALL_MODE=dev && bash quick_start.sh`可以安装`alpha版本`，就比如现在执行安装的是`v1.10.5-alpha.1`版本
- 2、`alpha版本`具体打包了什么内容，修复了什么BUG没有找到说明
#### git源码安装
- 1、如果`alpha版本`是通过`CI/CD`对`dev`分支自打包的，那就不需要额外的文档了
- 2、如果有地方可以看到`alpha版本`以及`对应的修复记录`，就更好了

**Comment by wanghe-fit2cloud** [comment]
> #### dev安装
> * 1、下载`quick_start.sh`后使用命令`export INSTALL_MODE=dev && bash quick_start.sh`可以安装`alpha版本`，就比如现在执行安装的是`v1.10.5-alpha.1`版本
> * 2、`alpha版本`具体打包了什么内容，修复了什么BUG没有找到说明
> 
> #### git源码安装
> * 1、如果`alpha版本`是通过`CI/CD`对`dev`分支自打包的，那就不需要额外的文档了
> * 2、如果有地方可以看到`alpha版本`以及`对应的修复记录`，就更好了

下个版本我们支持用户在面板设置中开启 `内测模式`，支持从正式版本升级至 `内测版本`。

**Comment by MiderWong** [comment]
好的，非常感谢。
