### ISSUE TITLE
[FEATURE] 将本地证书自动上传到各个云平台

### ISSUE THREAD

**Issue by ChishFoxcat** [1Panel-dev/1Panel#4687]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

因为腾讯云的 `TrustAsia` 的免费证书调整到了 3 个月，所以想将本地证书上传其平台上，少量还好，但是大量证书和域名导致我很难去一点一点续签。（不单单是腾讯云一家平台）
需求就是：在证书选项上增加上传证书
1. 添加各平台的的 secretkey
2. 选项列表选择需要上传的证书（自动更新上传证书）

或是在申请证书上添加自动同步（指上传和更新）证书

### 请描述你建议的实现方案

发现很多我需求相似的项目：
- https://github.com/zfb132/qcloud-ssl-cdn
- https://github.com/ZingLix/qcloud_cdn_upload_ssl_cert

但都是基于 `acme.sh` 的

### 附加信息

看看愿不愿意加吧，我还有其他曲线救国的方法：
1. 证书我默认都没保存到本地目录，但是证书还是存在开启 HTTPS 的网站的目录下 `/www/site/..../ssl`
2. 然后脚本定时上传

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
我们会在后续版本中支持 `证书自动续签后执行脚本的功能`
相关需求的讨论，我们统一放到这个 issue https://github.com/1Panel-dev/1Panel/issues/3197

**Comment by ChishFoxcat** [comment]
> 我们会在后续版本中支持 `证书自动续签后执行脚本的功能` 相关需求的讨论，我们统一放到这个 issue #3197

其实我的需求与此 issue https://github.com/1Panel-dev/1Panel/issues/920 相同，看版本号好像都比较久远了

**Comment by wanghe-fit2cloud** [comment]
> > 我们会在后续版本中支持 `证书自动续签后执行脚本的功能` 相关需求的讨论，我们统一放到这个 issue #3197
> 
> 其实我的需求与此 issue #920 相同，看版本号好像都比较久远了

收到，后续版本考虑支持。

**Comment by swift-fs** [comment]
同需要，现在我是把证书保存到本地，监听文件变更，有变更了就立即推到云服务器去部署到cdn，oss

**Comment by wanghe-fit2cloud** [comment]
> 同需要，现在我是把证书保存到本地，监听文件变更，有变更了就立即推到云服务器去部署到cdn，oss

v1.10.12-beta 版本已经支持在申请证书后执行脚本的功能。要升级到 beta 版本，需进入【面板设置】页面，启用【预览体验计划】。如图所示：
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/d4f4260f-dc70-4cc9-bf49-bf93dd087ddf">
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/96334639-7999-4441-bd94-d08ad6122892">
