### ISSUE TITLE
[增加DNS账户中支持的平台]

### ISSUE THREAD

**Issue by TcDhlPro** [1Panel-dev/1Panel#469]
### 1Panel 版本

v1.0.5.2

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/100897011/229204745-e28dca48-6559-4712-96dc-55aeba0ac65b.png)
目前就这三个, 能不能再加个www.namesilo.com这个平台

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持该需求。

**Comment by wanghe-fit2cloud** [comment]
v1.9.0 版本已发布。
