### ISSUE TITLE
[BUG]专业版waf请求趋势显示不完整

### ISSUE THREAD

**Issue by motao123** [1Panel-dev/1Panel#4693]
### 1Panel 版本

专业版： v1.10.5-lts

### 问题描述

![微信图片_20240425105108.png](https://img.imotao.com/i/2024/04/25/6629c540c8313.png)

### 重现步骤

![微信图片_20240425105108.png](https://img.imotao.com/i/2024/04/25/6629c540c8313.png)

**Comment by zhengkunwang223** [comment]
感谢反馈 后续版本优化
