### ISSUE TITLE
建议添加拦截记录导出

### ISSUE THREAD

**Issue by fxln** [1Panel-dev/1Panel#4694]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

建议在高级功能-WAF-拦截记录-添加拦截记录导出
![image](https://github.com/1Panel-dev/1Panel/assets/72055650/52507698-66c9-4292-87b1-02bc467844ad)
建议在高级功能-WAF-封锁记录-添加封锁记录导出
![image](https://github.com/1Panel-dev/1Panel/assets/72055650/01d6c884-974a-4a89-b2aa-44b9177420f4)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们会在后续版本支持上述功能。
重复 issue https://github.com/1Panel-dev/1Panel/issues/4680
