### ISSUE TITLE
[BUG]快照状态一直为“进行中”

### ISSUE THREAD

**Issue by motao123** [1Panel-dev/1Panel#4695]
### 1Panel 版本

专业版： v1.10.5-lts

### 问题描述

![微信截图_20240425112938.png](https://img.imotao.com/i/2024/04/25/6629ce3c68d34.png)
![微信截图_20240425113038.png](https://img.imotao.com/i/2024/04/25/6629ce7ba9210.png)

### 重现步骤

![微信截图_20240425112744.png](https://img.imotao.com/i/2024/04/25/6629cdd46ffb8.png)

**Comment by wanghe-fit2cloud** [comment]
上述问题的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4618

**Comment by ssongliu** [comment]
麻烦提供一下日志文件 /opt/1panel/log/1Panel.log

**Comment by wanghe-fit2cloud** [comment]
执行以下命令，查看一下是否存在 Error 相关日志：
```shell
journalctl -u 1panel.service -exf
```

**Comment by motao123** [comment]
> 执行以下命令，查看一下是否存在Error 相关日志：
> 
> ```shell
> journalctl -u 1panel.service -exf
> ```
只有我本地IP请求成功的数据，没有任何error

**Comment by motao123** [comment]
> > 执行以下命令，查看一下是否存在Error 相关日志：
> > ```shell
> > journalctl -u 1panel.service -exf
> > ```
> 
> 只有我本地IP请求成功的数据，没有任何error

Apr 25 11:27:33 imotao-jp 1panel[502467]: [GIN] 2024/04/25 - 11:27:33 | 200 |   10.359557ms |   我的IP | POST     "/api/v1/settings/snapshot/status"
Apr 25 11:27:34 imotao-jp 1panel[502467]: [GIN] 2024/04/25 - 11:27:34 | 200 |   10.446324ms |   我的IP | POST     "/api/v1/settings/snapshot/status"
Apr 25 11:27:34 imotao-jp 1panel[502467]: [GIN] 2024/04/25 - 11:27:34 | 200 |   15.089095ms |   我的IP | POST     "/api/v1/settings/snapshot/status"
