### ISSUE TITLE
关于应用列表中的应用问题

### ISSUE THREAD

**Issue by null0034** [1Panel-dev/1Panel#4696]
### 1Panel 版本

v 1.10.5-lts

### 请描述您的需求或者改进建议

# 关于应用的问题
之前咱们的应用列表中上架了 `ZeroTier Planet`、`ZeroTier One` 等应用，今天日常维护发现应用已经被下架，请问：
- 后期是否还会重新上架
- 如果后期不再考虑上架，我将如何更新目前我正在运行的应用，重新 pull 镜像吗
- 有点好奇为什么应用会被下架，感觉这几款应用是个不错的工具，目前也正在使用

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
确实是下架了上述三款 VPN 相关应用，暂不考虑重新上架。

> 可以使用 [第三方仓库](https://github.com/okxlin/appstore)

**Comment by null0034** [comment]
> 感谢反馈。 确实是下架了上述三款 VPN 相关应用，暂不考虑重新上架。
> 
> > 可以使用 [第三方仓库](https://github.com/okxlin/appstore)

好的感谢
