### ISSUE TITLE
[BUG] 设置英语后，攻击地图全为蓝色

### ISSUE THREAD

**Issue by ipangbo** [1Panel-dev/1Panel#4697]
### 1Panel 版本

v1.10.5-lts

### 问题描述

设置英语后，攻击地图全为蓝色，但是切换到中文可以看到实际上只有部分国家有攻击记录。

### 重现步骤

将语言设置为英语，点击WAF

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们也在本地环境复现了上述问题，会在近期版本修复。

**Comment by wanghe-fit2cloud** [comment]
v1.10.6-lts 版本已发布。
