### ISSUE TITLE
[FEATURE]it-tools目前使用的的汉化有问题，建议换成另一个版本，有个新版本

### ISSUE THREAD

**Issue by duxdyu** [1Panel-dev/1Panel#4698]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

应用商店里默认装的it-tools插件的汉化基本上没做，用的是这个镜像corentinth/it-tools:2023.12.21-5ed3693
可以换成更新的

### 请描述你建议的实现方案

corentinth/it-tools:nightly
这个版本的镜像汉化的更全面一点，用起来方便多了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

目前 1Panel 使用的镜像就是 latest 稳定版本，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/a7db35df-10a9-4e51-849a-8de91d38c05a)


而 Nightly 它不是正式版，暂时不考虑将默认的镜像版本修改为 nightly。
> 不过，可以在安装应用时，手动修改镜像版本。
