### ISSUE TITLE
[BUG] E：无法获取containerd.io_1.6.20-1_amd64.deb 404

### ISSUE THREAD

**Issue by weizhishu233** [1Panel-dev/1Panel#470]
### 联系方式

none

### 1Panel 版本

没法登录

### 问题描述

E: Failed to fetch https://mirrors.aliyun.com/docker-ce/linux/debian/dists/bullseye/pool/stable/amd64/containerd.io_1.6.20-1_amd64.deb  404  Not Found

### 重现步骤

curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sudo bash quick_start.sh

### 期待的正确结果

[1Panel Log]: ... 启动 docker

### 相关日志输出

```shell
[1Panel Log]: ======================= 开始安装 ======================= 
设置 1Panel 安装目录（默认为/opt）：
[1Panel Log]: 您选择的安装路径为 /opt 
[1Panel Log]: ... 在线安装 docker 
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c mkdir -p /etc/apt/keyrings && chmod -R 0755 /etc/apt/keyrings
+ sh -c curl -fsSL "https://mirrors.aliyun.com/docker-ce/linux/debian/gpg" | gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg
+ sh -c chmod a+r /etc/apt/keyrings/docker.gpg
+ sh -c echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://mirrors.aliyun.com/docker-ce/linux/debian bullseye stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-scan-plugin docker-compose-plugin docker-ce-rootless-extras docker-buildx-plugin >/dev/null
E: Failed to fetch https://mirrors.aliyun.com/docker-ce/linux/debian/dists/bullseye/pool/stable/amd64/containerd.io_1.6.20-1_amd64.deb  404  Not Found [IP: 47.246.16.231 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
[1Panel Log]: ... 启动 docker 
Failed to enable unit: Unit file docker.service does not exist.
Failed to start docker.service: Unit docker.service not found.
[1Panel Log]: docker 安装失败
```

### 附加信息

嗯… 无法访问此页面网址为https://mirrors.aliyun.com/docker-ce/linux/debian/dists/bullseye/pool/stable/amd64/containerd.io_1.6.20-1_amd64.deb 的页面可能存在问题，或者已永久移动到新的网址。
ERR_INVALID_RESPONSE
添加个备用镜像站
https://mirrors.tuna.tsinghua.edu.cn/docker-ce

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。我们在 Debian 11 操作系统中测试安装没有发现问题，请问您安装 1Panel 的服务器是什么操作系统？

**Comment by wanghe-fit2cloud** [comment]
您现在可以在服务器上先手动安装 Docker，然后再运行 1Panel 的在线安装脚本。

**Comment by weizhishu233** [comment]
是的,我的系统是Debian11. 手动安装后问题得以解决。https://mirrors.aliyun.com/docker-ce/linux/debian/dists/bullseye/pool/stable/amd64/ 这个路径下截止到[containerd.io_1.6.19-1_amd64.deb]而不是[containerd.io_1.6.20-1_amd64.deb],这很奇怪

**Comment by weizhishu233** [comment]
2023-04-01 05:55更新了,有延迟,之前空缺了一段时间,问题得以解决,感谢！

**Comment by liu7015463** [comment]
2023-11-1 也出现类似的问题
Failed to fetch https://mirrors.aliyun.com/docker-ce/linux/debian/dists/bullseye/pool/stable/amd64/docker-ce-cli_24.0.7-1%7edebian.11%7ebullseye_amd64.deb  404  Not Found [IP: 140.249.32.204 443]
在https://mirrors.aliyun.com/docker-ce/linux/debian/dists/bullseye/pool/stable/amd64/ 下看最新的是 [docker-ce-cli_24.0.6-1~debian.11~bullseye_amd64.deb](https://mirrors.aliyun.com/docker-ce/linux/debian/dists/bullseye/pool/stable/amd64/docker-ce-cli_24.0.6-1~debian.11~bullseye_amd64.deb)
