### ISSUE TITLE
[BUG]配置docker加速镜像后重启docker报错误

### ISSUE THREAD

**Issue by fxln** [1Panel-dev/1Panel#4701]
### 联系方式

1Panel VIP 交流群7 Domain

### 1Panel 版本

v1.10.5-lts

### 问题描述

使用openEuler / 其他
第一步：安装 docker
bash <(curl -sSL https://linuxmirrors.cn/docker.sh)
第二步：安装 1Panel
curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && bash quick_start.sh
通过浏览器访问 1Panel：
http://目标服务器 IP 地址:目标端口/安全入口
配置docker加速镜像后重启docker报错误
![image](https://github.com/1Panel-dev/1Panel/assets/72055650/f3d460bf-bc7a-48ef-ab1d-9c293b297219)
停止了docker后启动docker报错误
![image](https://github.com/1Panel-dev/1Panel/assets/72055650/3553bc45-5d7a-46e8-8040-deca9f127f5e)

### 重现步骤

配置docker加速镜像后重启docker报错误
![image](https://github.com/1Panel-dev/1Panel/assets/72055650/f3d460bf-bc7a-48ef-ab1d-9c293b297219)

### 期待的正确结果

可以正常启动docker

### 相关日志输出

```shell
服务内部错误: stderr: Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xeu docker.service" for details.


更新 docker daemon.json 配置 [Mirrors]=>[https://registry.cn-guangzhou.aliyuncs.com,,https://hub-mirror.c.163.com,https://docker.m.daocloud.io,https://ghcr.io,https://mirror.baidubce.com,https://docker.nju.edu.cn]
```

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/72055650/09f576e6-e2b7-4285-bf4a-e14a066b6b61)

![image](https://github.com/1Panel-dev/1Panel/assets/72055650/d4e56ff5-86cd-4ecb-9c65-eda967ac0ac3)

**Comment by wanghe-fit2cloud** [comment]
进入 `主机` - `终端` 页面，删除 `/etc/docker/daemon.json` 文件中的空行，最后通过 `systemctl restart docker` 命令重启 docker，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/3f1f8ee5-33bb-4afb-9861-63e4f01f1da9)

> 近期版本我们也会针对上述空行问题作出优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.6-lts 版本已发布。

**Comment by lipanpan-hub** [comment]
报错还有的
