### ISSUE TITLE
[BUG]错误日志长到离谱

### ISSUE THREAD

**Issue by 1728643928** [1Panel-dev/1Panel#4702]
### 1Panel 版本

v1.10.5-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/78271184/c04406a6-86a5-40e8-9eeb-c57a0f83ec79)
![image](https://github.com/1Panel-dev/1Panel/assets/78271184/37c7a363-5212-41aa-90b6-c137d81faa32)

### 重现步骤

就是更新pdf报错了，然后看日志，直接长到起飞

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
