### ISSUE TITLE
[FEATURE]概览-状态栏 CPU 核心全部显示不友好

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4706]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

状态这里的 cpu 不要默认全部展开，很占空间而且很容易随手路过，就把这个页面呼出。

![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/9e22aa64-e7c9-4e68-a4df-e40d5fef2157)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.6-lts 版本已发布。
