### ISSUE TITLE
[BUG]typecho在自建环境安装后登录后台会被拦截

### ISSUE THREAD

**Issue by MemoryCollection** [1Panel-dev/1Panel#4709]
### 1Panel 版本

社区版:v1.10.5-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/27777606/85db9cec-0535-4d5e-ab51-ca8f7d812238)

### 重现步骤

后台登录账户密码就拦截

### 期待的正确结果

希望能提供下白名单具体怎么写，本人不是很懂

**Comment by wanghe-fit2cloud** [comment]
建议参考：https://github.com/1Panel-dev/1Panel/issues/4636

> 先关闭该 issue 了。

**Comment by MemoryCollection** [comment]
> 建议参考：#4636
> 
> > 先关闭该 issue 了。

就是因为看不懂，才提问的。。。。。

**Comment by MemoryCollection** [comment]
> 建议参考：#4636
> 
> > 先关闭该 issue 了。

![image](https://github.com/1Panel-dev/1Panel/assets/27777606/b60a845a-4cc7-4b24-aaf4-afa92f537360)
这样吗  没生效

**Comment by wanghe-fit2cloud** [comment]
在网站设置中，在 `URL 规则` 列表中找到被拦截的规则，将状态修改为关闭。
然后再可以进入 `黑白名单` - `URL 黑名单` 页面，手动添加除那些不被拦截的正常规则。
因为每个应用的拦截规则都不一样，需要自定义。

**Comment by MemoryCollection** [comment]
> 在网站设置中，在 `URL 规则` 列表中找到被拦截的规则，将状态修改为关闭。 然后再可以进入 `黑白名单` - `URL 黑名单` 页面，手动添加除那些不被拦截的正常规则。 因为每个应用的拦截规则都不一样，需要自定义。

是SQL 注入防御，我把他给关了，没找到该怎么修改。

谢谢了，就这样凑合用，反正网站也没什么特殊的

**Comment by wanghe-fit2cloud** [comment]
> > 在网站设置中，在 `URL 规则` 列表中找到被拦截的规则，将状态修改为关闭。 然后再可以进入 `黑白名单` - `URL 黑名单` 页面，手动添加除那些不被拦截的正常规则。 因为每个应用的拦截规则都不一样，需要自定义。
> 
> 是SQL 注入防御，我把他给关了，没找到该怎么修改。
> 
> 谢谢了，就这样凑合用，反正网站也没什么特殊的

可以统计一下 typecho 这个应用都有哪些特殊的配置被拦截，后期我们可以考虑针对该应用出一个白名单模版。
