### ISSUE TITLE
一点疑问，安装应用时候 填写 名称？

### ISSUE THREAD

**Issue by leeaikong** [1Panel-dev/1Panel#471]
### 请描述您的问题

有一个疑问，安装应用的时候 为什么要填写 名称？ 这个是啥目的？
比如我安装 OpenResty  安装页面 名称还是填写 《OpenResty 》   我再看一下路径，  2个同名的文件夹了。。

这个是为啥，为什么不能省略这个名称？

**Comment by zhengkunwang223** [comment]
名称是存放这个应用的文件夹名称，因为有些应用可能安装不止一个，所以需要填写。我们后续会考虑自动填写或者默认。

**Comment by hhun** [comment]
> 名称是存放这个应用的文件夹名称，因为有些应用可能安装不止一个，所以需要填写。我们后续会考虑自动填写或者默认。

后期目录能修改吗？

**Comment by wanghe-fit2cloud** [comment]
> > 名称是存放这个应用的文件夹名称，因为有些应用可能安装不止一个，所以需要填写。我们后续会考虑自动填写或者默认。
> 
> 后期目录能修改吗？

修改目录后会影响到备份等一系列功能，所以还不支持修改。
