### ISSUE TITLE
[FEATURE]1panel安装了code-server后 能在文件夹选项里添加快捷打开方式吗

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4712]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

安装后能否在文件夹菜单选项里添加 “通过vode-server打开” 快捷方式，像宝塔面板这样。
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/d0d70485-695a-48fd-9b8c-28d185537627)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1Panel 是容器化安装的 code-server，如果要实现上述需求就需要挂载宿主机目录。
我们先调研一下具体方案吧。

**Comment by wanghe-fit2cloud** [comment]
重复 https://github.com/1Panel-dev/1Panel/issues/4729
