### ISSUE TITLE
[FEATURE]希望kkFileView能加入应用商店 

### ISSUE THREAD

**Issue by wxyShine** [1Panel-dev/1Panel#4717]
### 1Panel 版本

专业版：v1.10.5-alpha.1

### 请描述您的需求或者改进建议

应用商店建议   上架 https://github.com/kekingcn/kkFileView

相关文档 https://kkview.cn/zh-cn/docs/production.html

### 附加信息

kkFileView为文件文档在线预览解决方案，该项目使用流行的spring boot搭建，易上手和部署，基本支持主流办公文档的在线预览，如doc,docx,xls,xlsx,ppt,pptx,pdf,txt,zip,rar,图片,视频,音频等等

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上架上述应用。

**Comment by wanghe-fit2cloud** [comment]
重复 https://github.com/1Panel-dev/1Panel/issues/3142
