### ISSUE TITLE
[FEATURE]黑白名单中url白名单的格式是什么？

### ISSUE THREAD

**Issue by MemoryCollection** [1Panel-dev/1Panel#4718]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/27777606/c0257772-d781-4c3a-89e5-c81833d7d5ea)

**Comment by zhengkunwang223** [comment]
<域名> <URL>
例如：你想给 wp 的/wp-admin 加白名单
那么你的规则可以写为 wp-admin

**Comment by MemoryCollection** [comment]
> 写为 wp-admin

好的，我试试
