### ISSUE TITLE
[QUESTION]openresty 一直安装中。。

### ISSUE THREAD

**Issue by leeaikong** [1Panel-dev/1Panel#472]
### 请描述您的问题

环境  win10系统 安装docker  然后安装centos系统  安装1panel  
 
发行版本 centos-7.9.2009
内核版本 5.10.16.3-microsoft-standard-WSL2
系统类型 x86_64

 安装openresty  一个多小时了 一直是安装中，也没有办法取消，也不提示错误，就卡在这里
最好能够取消，关键是能看到安装运行代码，可以看到哪里出错了，就一直无休止的安装中，搞不清楚哪里的问题
![2023-4-1 15-19-3](https://user-images.githubusercontent.com/40814658/229271762-66b5edd4-36e0-4ba0-ae0e-82c54048a31c.png)

**Comment by zhengkunwang223** [comment]
应该是没有镜像导致的，现在可以通过重启1panel 来同步异常应用，后续我们会优化这种情况

**Comment by Shiguang-coding** [comment]
![Snipaste_2023-12-17_15-40-23](https://github.com/1Panel-dev/1Panel/assets/75553284/0276dc81-009b-4a0b-bdc2-dc81c8f85bc6)
