### ISSUE TITLE
[FEATURE] podman 到底什么时候能支持

### ISSUE THREAD

**Issue by koaqiu** [1Panel-dev/1Panel#4720]
### 1Panel 版本

v1.10-5-lts

### 请描述您的需求或者改进建议

搜索了一下，发现2023年就有不少issuer是关于支持podman的。
现在已经2024了，是不是还没有任何相关的支持计划？

### 附加信息

顺便说一下：右下角那个版本号
即不能复制也不能选择，什么神仙交互。。。。。。。。。。。。。

**Comment by wanghe-fit2cloud** [comment]
v2.0 可能会考虑，近期没有计划支持。
