### ISSUE TITLE
[BUG]数据库添加远程服务器未使用填写的地址，直接使用本机ip

### ISSUE THREAD

**Issue by lranxi** [1Panel-dev/1Panel#4722]
### 联系方式

zichuansany@163.com

### 1Panel 版本

v1.10.5-lts

### 问题描述

服务器A安装mysql数据库，服务器B通过1panel中的数据库菜单中的远程服务器添加A的mysql，提示"连接不可用，请检查连接信息"。系统日志中打印的数据库地址为本机（服务器B）的IP;
安全组已经放行，本地环境下通过navicat可以正常连接。

相关配置和日志如下：

![image](https://github.com/1Panel-dev/1Panel/assets/95736010/f2994b6c-0aeb-4ab4-81d4-4007efaea744)

[2024-04-26 11:41:20] [ERROR] test mysql conn failed, err: Error 1045 (28000): Access denied for user 'root'@'x.x.16.7' (using password: YES)  

x.x.4.3 为服务器A内网IP
x.x.16.7为服务器B内网IP

### 重现步骤

1. 在服务器A创建mysql，安全组添加放行
2. 服务器B，数据库-> 远程服务器 -> 添加远程服务器 -> 链接测试

**Comment by ssongliu** [comment]
感谢反馈，A 服务数据库有打开外部端口访问吗

**Comment by lranxi** [comment]
A 服务数据库外部端口访问已经打开，安全组3306已经放行。使用navicat可以正常连接

**Comment by lranxi** [comment]
> 感谢反馈，A 服务数据库有打开外部端口访问吗

A 服务数据库外部端口访问已经打开，安全组3306已经放行。使用navicat可以正常连接

**Comment by lranxi** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/95736010/373c7d37-f8c6-44e9-abdc-c6b18ee83b71)
可以通过容器中显示的IP地址连接
