### ISSUE TITLE
[BUG]反向代理网站创建失败后 OpenResty 直接崩溃

### ISSUE THREAD

**Issue by vicat47** [1Panel-dev/1Panel#4724]
### 联系方式

vicat47@qq.com

### 1Panel 版本

v1.10.5-lts

### 问题描述

创建网站失败后配置文件出错导致无法启动 openresty

### 重现步骤

在创建网站时，在提交之前会验证反向代理是否正常，此时 `OpenResty` 配置文件已经存在目录下，但实际目录尚未创建，导致服务报错。

### 期待的正确结果

配置正确回滚

**Comment by link2fun** [comment]
刚刚新机子 安装 OpenResty  就直接启动不了

**Comment by vicat47** [comment]
> 刚刚新机子 安装 OpenResty 就直接启动不了

这个你看看论坛或者新提个 bug 吧。原因是 docker 版本有点低
解决方案也有，手动把镜像拉进去

**Comment by link2fun** [comment]
> > 刚刚新机子 安装 OpenResty 就直接启动不了
> 
> 这个你看看论坛或者新提个 bug 吧。原因是 docker 版本有点低 解决方案也有，手动把镜像拉进去

升级docker 后确实可以了, 多谢
我是ubuntu 这里参照的是官方文档
先卸载旧版本
https://docs.docker.com/engine/install/ubuntu/#uninstall-old-versions
再安装新版本
https://docs.docker.com/engine/install/ubuntu/#installation-methods

其他的系统也可以参照(选择对应系统)
https://docs.docker.com/engine/install/

**Comment by vicat47** [comment]
上面说的不是同一个 bug，我说的这个是创建网站时候的 bug，别 close 呀
@wanghe-fit2cloud

**Comment by link2fun** [comment]
> 上面说的不是同一个 bug，我说的这个是创建网站时候的 bug，别 close 呀 @wanghe-fit2cloud

大大的~惨~字， 再次感谢老哥提醒

**Comment by zhengkunwang223** [comment]
> 上面说的不是同一个 bug，我说的这个是创建网站时候的 bug，别 close 呀 @wanghe-fit2cloud

配置贴一下

**Comment by vicat47** [comment]
```
[2Kopenresty  | 2024/04/25 20:16:29 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | 2024/04/25 20:16:29 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | 2024/04/25 20:16:30 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | 2024/04/25 20:16:30 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | 2024/04/25 20:16:31 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | 2024/04/25 20:16:33 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | 2024/04/25 20:16:37 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | 2024/04/25 20:16:43 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | 2024/04/25 20:16:56 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | 2024/04/25 20:17:22 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | 2024/04/25 20:18:14 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
[2Kopenresty  | 2024/04/25 20:19:14 [notice] 1#1: [lua] config.lua:74: ini_waf_info(): Load 1Panel WAF Version:1.0.0
```
现在复现不了了，当时添加网站的时候说无法连接后端，然后报了个错。之后就只有配置文件没有目录了，启动报错

**Comment by zhengkunwang223** [comment]
> ```
> 
> [2Kopenresty  | 2024/04/25 20:16:29 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | 2024/04/25 20:16:29 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | 2024/04/25 20:16:30 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | 2024/04/25 20:16:30 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | 2024/04/25 20:16:31 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | 2024/04/25 20:16:33 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | 2024/04/25 20:16:37 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | 2024/04/25 20:16:43 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | 2024/04/25 20:16:56 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | 2024/04/25 20:17:22 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | 2024/04/25 20:18:14 [emerg] 1#1: open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | nginx: [emerg] open() "/www/sites/chatgpt_proxy/log/access.log" failed (2: No such file or directory)
> 
> [2Kopenresty  | 2024/04/25 20:19:14 [notice] 1#1: [lua] config.lua:74: ini_waf_info(): Load 1Panel WAF Version:1.0.0
> 
> ```
> 
> 现在复现不了了，当时添加网站的时候说无法连接后端，然后报了个错。之后就只有配置文件没有目录了，启动报错

我刚才试了几次，没有复现，你可以再试几次，看看怎么复现。
