### ISSUE TITLE
docker容器启动应用问题

### ISSUE THREAD

**Issue by touchixiaobinggan** [1Panel-dev/1Panel#4728]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

我现有应用redis,已经停止了,但是服务器宕机或者重启后,redis应用会重新启动,希望重启后应用可以保持原有启动状态

### 请描述你建议的实现方案

希望可以针对所有容器进行配置,可以设置重启后启不启动配置

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/49968136/e0106f4c-f7fa-448e-8b86-732c6b72916c)

**Comment by wanghe-fit2cloud** [comment]
- 应用商店创建的应用：
将重启规则修改为 no，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/b602cabf-f2c5-4884-a179-5530b6e26cc1)

- 容器页面创建的容器：
`重启规则` 选择 `不重启`，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/f242ddd5-d5fb-41ee-95df-67c18373b022)

> 针对已经运行的容器或者应用，可以在容器列表页找到目标容器，编辑，将 `重启规则` 修改为 `不重启`。
