### ISSUE TITLE
[FEATURE]主机目录/文件支持使用本地 vscode 打开

### ISSUE THREAD

**Issue by wan92hen** [1Panel-dev/1Panel#4729]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

在主机文件管理功能中增加使用 vscode 打开的功能，通过 vscode 的 ssh remote 机制，用户可以通过 SSH 连接 1Panel 所在服务器，并打开选定的目录或文件。

### 请描述你建议的实现方案

选择特定的目录或文件进行打开时，构造类似这样的 URL 地址进行跳转：
```
vscode://vscode-remote/ssh-remote+[USER@]HOST[:PORT]/path/to/dir
vscode://vscode-remote/ssh-remote+[USER@]HOST[:PORT]/path/to/file:ROW:COL
```
通过浏览器访问该地址时，会提示是否使用 vscode 打开，vscode 需安装 ssh remote 插件。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先调研一下上述需求的可行性方案。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
