### ISSUE TITLE
[FEATURE]主机，希望多文件上传

### ISSUE THREAD

**Issue by 2710455359** [1Panel-dev/1Panel#473]
### 1Panel 版本

1.0.5

### 请描述您的需求或者改进建议

菜单栏->主机
目前：上传功能，只允许上传一个文件
希望：上传功能，能一次性上传多个文件

### 请描述你建议的实现方案

elementui：https://element.eleme.io/#/zh-CN/component/upload，组件添加multiple
elementplus：https://element-plus.gitee.io/zh-CN/component/upload.html#%E6%8B%96%E6%8B%BD%E4%B8%8A%E4%BC%A0，也是添加multiple
抖音看到的一个方法：https://www.douyin.com/video/7202169544683638072

**Comment by zhengkunwang223** [comment]
感谢建议，我们后续版本支持

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
