### ISSUE TITLE
[FEATURE] ChatWoot is a pretty good self-hosted app for chatting with customers and I hope it will be added to 1panel's Apps Store.

### ISSUE THREAD

**Issue by royzxje** [1Panel-dev/1Panel#4731]
### 1Panel 版本

Community Edition:  v1.10.5-lts

### 请描述您的需求或者改进建议

ChatWoot is a pretty good self-hosted app for chatting with customers and I hope it will be added to 1panel's Apps Store.
Github: https://github.com/chatwoot/chatwoot

### 请描述你建议的实现方案

Documentation for deploying ChatWoot on Docker: https://www.chatwoot.com/docs/self-hosted/deployment/docker

### 附加信息

Customer engagement suite, an open-source alternative to Intercom, Zendesk, Salesforce Service Cloud etc.
Chatwoot is an open-source, self-hosted customer engagement suite. Chatwoot lets you view and manage your customer data, communicate with them irrespective of which medium they use, and re-engage them based on their profile.

**Comment by wanghe-fit2cloud** [comment]
Thank you for your feedback. 
Considering the complexity of deploying Chatwoot (involving multiple containers), which is not conducive to later maintenance in a store setting, we recommend using the `Container` - `Compose` feature provided by 1Panel for more convenient application maintenance.
