### ISSUE TITLE
[BUG]面板所在的服务器能连外网但是许可证提示失联

### ISSUE THREAD

**Issue by duxdyu** [1Panel-dev/1Panel#4733]
### 1Panel 版本

v1.10.5-lts

### 问题描述

面板能ping通外网，但是提示 许可证需要定时同步是否可用，请保证正常外网访问，失联三次后将解除许可证绑定

### 重现步骤

具体不太清楚，我在esxi部署了1panel，配了双网卡一个内网一个外网，今天提示失联*2

### 附加信息

![微信图片2](https://github.com/1Panel-dev/1Panel/assets/84559061/cc5080a1-47fb-4bc5-821e-8726d4ddd483)
![微信图片1](https://github.com/1Panel-dev/1Panel/assets/84559061/49f33f38-8f28-4e7f-828f-202a059ffec5)

**Comment by ssongliu** [comment]
感谢反馈，这个问题会在节后的版本优化，暂时可以通过同步许可证来修改状态

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
