### ISSUE TITLE
[BUG]1panel文档里面安装部署的在线安装，ubuntu的指令没法用

### ISSUE THREAD

**Issue by duxdyu** [1Panel-dev/1Panel#4734]
### 1Panel 版本

v1.10.5-lts

### 问题描述

ubuntu22.04不用root账户直接执行下列代码会报错
`curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sudo bash quick_start.sh`
测试和询问大佬后知道这是因为安装使用的账户的问题，同时sudo bash这个命令本身也有问题，应该进到root账户执行
建议改成以下指令，就不会报错了
`sudo su`
`curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && bash quick_start.sh`

### 重现步骤

安装ubuntu系统，不使用root账户登录执行代码就会报错

### 附加信息

![微信图片3](https://github.com/1Panel-dev/1Panel/assets/84559061/b7553698-48da-4889-8720-347826f932cf)
顺便提一下用wget装会报另外的奇怪错误，检查发现下载的文件内容和curl下载的不太一样，也不知道是什么原因
![微信图片4](https://github.com/1Panel-dev/1Panel/assets/84559061/95242c79-3e16-412c-8bfd-b37b42c0c390)

**Comment by wanghe-fit2cloud** [comment]
在开发测试环境未能复现上述问题。
> curl tar 等命令需要自行安装，脚本中安装 docker docker-compose 等需要 sudo 权限，但不需要给到 curl。
