### ISSUE TITLE
[FEATURE] 建议计划任务还有其他一些地方的报错日志啥的，直接给详细日志，不要遮遮掩掩

### ISSUE THREAD

**Issue by OuOumm** [1Panel-dev/1Panel#4736]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

这种的日志直接不要了吧
![image](https://github.com/1Panel-dev/1Panel/assets/43441064/65232f5a-cad5-4b1d-be30-f13b6cd6a64d)

改成下面这种就挺好
![image](https://github.com/1Panel-dev/1Panel/assets/43441064/729a8283-623e-47ae-bdb4-924068206a40)

同时补充一个问题，这个地方为啥不能复制了，能不能改改，改成可以复制的，不然每次填写版本号都得F12
![image](https://github.com/1Panel-dev/1Panel/assets/43441064/243e3399-1d5f-41d6-9798-e1e29ab6a63f)

### 请描述你建议的实现方案

就直接改过去就好了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，节后发布的版本优化这两部分

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
