### ISSUE TITLE
[BUG] 专业版,修改拦截页面后,必须要重启OpenResty服务才生效

### ISSUE THREAD

**Issue by maxbad** [1Panel-dev/1Panel#4738]
### 1Panel 版本

专业版v1.10.5-lts

### 问题描述

修改拦截页面后,必须要重启OpenResty服务才生效

### 重现步骤

修改拦截页面后

### 期待的正确结果

立即生效

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述功能。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
