### ISSUE TITLE
[BUG] 在WSL里面使用命令 1pctl restart 提示：Failed to connect to bus: Host is down

### ISSUE THREAD

**Issue by hhun** [1Panel-dev/1Panel#474]
### 1Panel 版本

1.0.5

### 问题描述

在WSL2里面使用命令 1pctl restart 提示：Failed to connect to bus: Host is down

1pctl restart
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

### 重现步骤

我的WSL2版本用的是 `Debian` 和 `Ubuntu 22.04`都测试了，都会提示这个错误。
好像是因为WSL2不支持 `esystemctl`

**Comment by gengxiaoxiaoxin** [comment]
WSL2目前已支持`systemd`，参阅以下内容自行打开即可。
- https://learn.microsoft.com/zh-cn/windows/wsl/wsl-config
- https://devblogs.microsoft.com/commandline/a-preview-of-wsl-in-the-microsoft-store-is-now-available/

**Comment by hhun** [comment]
感谢，通过 `/etc/wsl.conf` 里增加
```
[boot]
systemd=true
```
然后重启就解决了
