### ISSUE TITLE
[FEATURE] 自定义logo功能范围可以再增加一些吗？

### ISSUE THREAD

**Issue by hjdyzy** [1Panel-dev/1Panel#4740]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

高级功能 > 界面设置 可以增加以下这两处的自定义功能吗？

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/71299416/587be596-0304-42b2-b8ba-b225e76dff35)

**Comment by wanghe-fit2cloud** [comment]
1、面板设置页面修改别名，如图：
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/a5e684d9-0679-412d-9374-4b762d85cad9">

2、自定义登录图片后续版本可能会考虑。

**Comment by hjdyzy** [comment]
非常感谢！
