### ISSUE TITLE
[BUG] 本地安装的 docker 应用，UFW 端口管理失效

### ISSUE THREAD

**Issue by yfdoor** [1Panel-dev/1Panel#4741]
### 1Panel 版本

1.10.5

### 问题描述

1panel 默认安装的 docker 应用都是定义在 1panel-network （172.18.0.1）这个网络里，但是一些本地安装的应用可能安装在其他的网段，例如下表的 172.19.0.1，此时，本地安装的应用端口就是失去了 ufw 的保护，即使不开端口，外边也可以通过 IP+端口的方式访问。
![image](https://github.com/1Panel-dev/1Panel/assets/32769281/89132443-aaf7-4c0d-9f96-5392057f4f29)

### 重现步骤

如上

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
重复 issue https://github.com/1Panel-dev/1Panel/issues/1846

**Comment by yfdoor** [comment]
> 感谢反馈。 重复 issue #1846

安全问题，不应该放在最高优先级安排吗？我看这个issue 还是去年八月提出来的。。。希望可以尽快修复，谢谢

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈。 重复 issue #1846
> 
> 安全问题，不应该放在最高优先级安排吗？我看这个issue 还是去年八月提出来的。。。希望可以尽快修复，谢谢

出现上述现象是 docker 默认的 iptables 机制导致，并不是 1Panel 的漏洞。
后续 1Panel 会考虑支持 ufw-docker 这个第三方实现，但不是修复。

在防火墙页面也给出了提示，进入容器配置页面控制 iptables 开关，或者将容器端口绑定至 127.0.0.1，然后通过反向代理网站来实现。
还可以手动集成 ufw-docker 作者给出的方案等等，可行的方法有很多。

**Comment by yfdoor** [comment]
> > > 感谢反馈。 重复 issue #1846
> > 
> > 
> > 安全问题，不应该放在最高优先级安排吗？我看这个issue 还是去年八月提出来的。。。希望可以尽快修复，谢谢
> 
> 出现上述现象是 docker 默认的 iptables 机制导致，并不是 1Panel 的漏洞。 后续 1Panel 会考虑支持 ufw-docker 这个第三方实现，但不是修复。
> 
> 在防火墙页面也给出了提示，进入容器配置页面控制 iptables 开关，或者将容器端口绑定至 127.0.0.1，然后通过反向代理网站来实现。 还可以手动集成 ufw-docker 作者给出的方案等等，可行的方法有很多。

我清楚 ufw-docker 的解决方案，我是想说既然 1panel 是一个以 docker 安装应用为基础的面板，那么应该把 docker 端口管理的安全问题放在一个重要的位置来提前解决，给用户一个可行而简单的方案。希望没有给你带来困扰，谢谢。
