### ISSUE TITLE
[FEATURE]目前好像不能像宝塔那样直接管理springboot项目

### ISSUE THREAD

**Issue by luoxiaofeng1029** [1Panel-dev/1Panel#4742]
### 1Panel 版本

1.10.5

### 请描述您的需求或者改进建议

希望能像宝塔那样直接上传一个包自动就能管理springboot服务

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前可以考虑应用商店中提供的 Tomcat 应用来管理 Java 项目。

**Comment by wanghe-fit2cloud** [comment]
我们也会在后续版本考虑支持 Java 运行环境。
运行环境需求的讨论，统一汇总到该 issue #748
