### ISSUE TITLE
[BUG]你们面板登录页面不能在搜狗浏览器11上正常显示,手机低版本chrome也不能正常显示

### ISSUE THREAD

**Issue by issmile** [1Panel-dev/1Panel#4744]
### 联系方式

25818754@qq.com

### 1Panel 版本

v1.10.5-Its

### 问题描述

你们面板登录页面不能在搜狗浏览器11上正常显示,手机低版本chrome也不能正常显示

### 重现步骤

你们面板登录页面不能在搜狗浏览器11上正常显示,手机低版本chrome也不能正常显示

### 期待的正确结果

正常显示登录页面

### 附加信息

![搜狗截图24年04月27日1920_2](https://github.com/1Panel-dev/1Panel/assets/20268011/62d0315a-db72-47f9-8fd7-fa1e35b545d2)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
建议采用 Chrome 和 Firefox 浏览器，我们暂未针对其他浏览器进行过兼容性测试。
> 移动端部分页面可能会出现兼容问题，会在后续版本持续优化。
