### ISSUE TITLE
[BUG]文件上传拖拽栏上传多文件失败

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#4746]
### 1Panel 版本

v1.10.5

### 问题描述

文件上传时，可以选择`多个文件`或`多个文件与文件夹`，但是只显示第一个文件：
![PixPin_2024-04-27_20-53-01](https://github.com/1Panel-dev/1Panel/assets/63288007/06e485aa-e08a-481e-8791-b1eb9575fd17)

### 重现步骤

拖拽多个文件至上传框，只显示第一个文件

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，在本地环境已经复现上述问题，我们会在近期版本修复。
> 当前版本可以通过上传按钮来多文件上传。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
