### ISSUE TITLE
[BUG]面版502 

### ISSUE THREAD

**Issue by WillWilliams012** [1Panel-dev/1Panel#4747]
### 联系方式

WX:willywang8216

### 1Panel 版本

v1.10.5-lts

### 问题描述

甲骨文ARM部署后面板三不五時就來個Error 502，系统Ubuntu 20.04 (Linux Main-WP-Oracle424-U 5.15.0-102-generic #112-Ubuntu SMP Tue Mar 5 16:49:56 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux)
端口已开放，正常挂起1Panel服务，防火墙关闭，1Panel状态是Active，日志无报错

1、1pctl status 查看运行状态OK
2、netstat -ntlp 查看端口绑定情况OK
3、curl 127.0.0.1:服务端口 正常

### 重现步骤

用官方一鍵安裝，然後一鍵裝WORDPRESS，但是常來個 error 502 過一下又可以訪問，然後又不行...

### 期待的正确结果

不502

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1Panel 的资源包在 OSS 上，并开启了 CDN 全球加速。

上述报错可能是因为系统或者应用版本更新需要到 OSS 上获取最新版本号并下载最新版本离线包，超时了。
目前已知的云服务器厂商中，甲骨文服务器经常出现该问题。

**Comment by wanghe-fit2cloud** [comment]
也可以参考这个 [issue](https://github.com/1Panel-dev/1Panel/issues/3567)，继续讨论甲骨文 arm 服务器相关问题。

**Comment by RootieButler** [comment]
有同樣問題。所以跟arm amd 沒有關係的樣子。。。另外您說的issue是哪個issue沒看到連結

> 也可以参考这个 issue，继续讨论甲骨文 arm 服务器相关问题。

有同樣問題。原來是這樣子。那這樣子的話那跟機器的架構沒有關係。 是甲骨文會自動屏蔽某些cdn 連線？？

另外您說的issue是哪個。沒看到連結。
這樣時常斷線失聯無法用於production 有解決方案嗎？ 還是換個雲廠商就可以解決

**Comment by wanghe-fit2cloud** [comment]
已发。

**Comment by WillWilliams012** [comment]
> 已发。

好的，我在您發的那個ISSUE 裡討教留言，謝謝您

**Comment by lbrsy** [comment]
> 已发。

curl: (7) Failed to connect to 127.0.0.1 port 80 after 0 ms: Couldn't connect to server
请问这个怎么解决

**Comment by jingrandev** [comment]
遇到了同样的问题，1panel接口频繁502，出现一个502就跳回了登录页

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I encountered the same problem. The 1panel interface frequently received 502. When a 502 appeared, it jumped back to the login page.
