### ISSUE TITLE
[BUG] 网站备份还原错误

### ISSUE THREAD

**Issue by qwenode** [1Panel-dev/1Panel#4748]
### 1Panel 版本

v1.10.2-lts v1.10.5-lts

### 问题描述

备份网站环境:
v1.10.2-lts
nginx版本:1.21.4.3-0-focal
debian11
网站有ssl

还原目标的环境
v1.10.5-lts
nginx版本:1.21.4.3-2-1-focal
debian12
第一次 还原, 新建了同域名的网站,还原时提示源网站有ssl, 则修改目标网站配置,增加了ssl, 
第二次还原成功,但是刷新后,报错,同时 目标环境所有的网站都看不到了,都空了

![image](https://github.com/1Panel-dev/1Panel/assets/8974108/05d5d46e-294f-4e2c-9ef2-4401f8eb3a4e)

![image](https://github.com/1Panel-dev/1Panel/assets/8974108/15b25dc1-eb2e-4423-9cdb-bdc71d52ce76)

### 重现步骤

同上

**Comment by wanghe-fit2cloud** [comment]
上述操作涉及到了不同 1Panel 上创建的不同网站，目前系统暂不支持这种场景（相当于网站导入功能）。
我们会在近期版本先增加后端限制，也计划在 v2.0 版本中增加网站导入功能。

**Comment by zhengkunwang223** [comment]
还原前后是不是分组不一样？

**Comment by qwenode** [comment]
> 还原前后是不是分组不一样？

分组没有特意修改过,都是默认的

**Comment by zhengkunwang223** [comment]
恢复的是什么类型的网站？

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
