### ISSUE TITLE
[BUG]面板突然打不开了  下午正常，什么都没动，重启也没用

### ISSUE THREAD

**Issue by Alexzzz2008** [1Panel-dev/1Panel#4749]
### 1Panel 版本

1.10.5

### 问题描述

[BUG]面板突然打不开了  下午正常，什么都没动，重启也没用

### 重现步骤

[BUG]面板突然打不开了  下午正常，什么都没动，重启也没用

**Comment by wanghe-fit2cloud** [comment]
`1pctl status` 和 `journalctl -u 1panel.service -exf` 两条命令可以查看 1Panel 系统日志。

**Comment by Alexzzz2008** [comment]
> `1pctl status` 和 `journalctl -u 1panel.service -exf` 两条命令可以查看 1Panel 系统日志。

用了命令  啥也看不出来， 不知道什么情况啊，麻烦你帮我看看

**Comment by wanghe-fit2cloud** [comment]
提供一下截图，比如：
<img width="1434" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/8c5b1a5c-9b1b-4d1e-b0f1-dbf4c468f211">

**Comment by Alexzzz2008** [comment]
> <img alt="image" width="1434" src="https://private-user-images.githubusercontent.com/46734380/326187119-8c5b1a5c-9b1b-4d1e-b0f1-dbf4c468f211.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMzEwNTMsIm5iZiI6MTcxNDIzMDc1MywicGF0aCI6Ii80NjczNDM4MC8zMjYxODcxMTktOGM1YjFhNWMtOWIxYi00ZDFlLWIwZjEtZGJmNGM0NjhmMjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDE1MTIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NzMyMTY2NTAzZTZjZmY5MjhkYjcwODAxMGJiNDcyZDM2ZmYyNzQ4NWVjN2QwYTVjOTA3NmZiMzE0OWVlYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z4y14kQLpiyQRpv8Nd1_xUBk1mIypXrEPwDsM6IeWJE">

是的 跟你一样，面板是 running。  里面的网站打开也没问题， 我现在的绑定域名和加了ssl了， 怎么使用命令行去除域名和ssl，我测试一下，因为现在进不去面板啊，我也不知道是哪的问题，我只能排除一下，

**Comment by wanghe-fit2cloud** [comment]
参考：
https://1panel.cn/docs/installation/cli/
<img width="968" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/02c72e10-f61d-4be4-b14f-c9119c1510f8">

> 取消域名绑定、https访问，使用 `ip:port ` 方式登录即可。

**Comment by Alexzzz2008** [comment]
> 参考： https://1panel.cn/docs/installation/cli/ <img alt="image" width="968" src="https://private-user-images.githubusercontent.com/46734380/326187365-02c72e10-f61d-4be4-b14f-c9119c1510f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMzEzNjYsIm5iZiI6MTcxNDIzMTA2NiwicGF0aCI6Ii80NjczNDM4MC8zMjYxODczNjUtMDJjNzJlMTAtZjYxZC00YmU0LWIxNGYtYzkxMTljMTUxMGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDE1MTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmY2Q5YTc4NTk3YTdiMTg0ZjRiZmU0ODQ3Njg5ZDYwZTIzYzU2NzAxOGIxODMzODA1NTk0MGRkYzk4MDg1NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cl-p0nZK-uGX0KSiKANCQPPqrGQEvKAT-rJUKpJofr4">
> 
> > 取消域名绑定、https访问，使用 `ip:port ` 方式登录即可。

全部取消以后 ，打开面板  502错误

**Comment by wanghe-fit2cloud** [comment]
> 全部取消以后 ，打开面板 502错误。

操作都提供一下截图。

**Comment by wanghe-fit2cloud** [comment]
> 是的 跟你一样，面板是 running。 里面的网站打开也没问题

`curl 127.0.0.1:端口` 看一下结果，提供截图。

**Comment by Alexzzz2008** [comment]
curl: (7) Failed to connect to 127.0.0.1 port 22490: Connection refused

**Comment by wanghe-fit2cloud** [comment]
`netstat -ntlp` 截图

**Comment by wanghe-fit2cloud** [comment]
`cat /opt/1panel/log/1Panel.log` 截图

**Comment by Alexzzz2008** [comment]
> `cat /opt/1panel/log/1Panel.log` 截图

大哥能不能加个微信， 远程看一下。   太多东西 不知道怎么排查了

**Comment by wanghe-fit2cloud** [comment]
先根据上面的提示信息发截图，如果在微信群里直接添加 `王贺` 好友。

**Comment by Alexzzz2008** [comment]
> 先根据上面的提示信息发截图，如果在微信群里直接添加 `王贺` 好友。

我是专业版啊，但是你们群的那个二维码加不上， 所以没进到群里。

**Comment by wanghe-fit2cloud** [comment]
先发一下那两条命令截图

**Comment by wanghe-fit2cloud** [comment]
然后，可以给我邮箱发你的微信二维码
wanghe@fit2cloud.com

**Comment by leeaikong** [comment]
![Uploading 2024-04-27_23-40-56.png…]()

**Comment by Alexzzz2008** [comment]
![2024-04-27_23-40-56](https://github.com/1Panel-dev/1Panel/assets/40814658/be5a7f91-ffa7-43eb-82f7-4ac6678dbd45)

**Comment by wanghe-fit2cloud** [comment]
手动安装一下 netstat 命令，需要确认端口绑定情况。

**Comment by leeaikong** [comment]
![2024-04-27_23-45-45](https://github.com/1Panel-dev/1Panel/assets/40814658/1839e998-00d2-4f67-b5f9-d92b168132c9)

**Comment by Alexzzz2008** [comment]
> 手动安装一下 netstat 命令，需要确认端口绑定情况。

![2024-04-27_23-45-45_看图王](https://github.com/1Panel-dev/1Panel/assets/40814658/23158ef7-d433-496a-8c70-4d489769fa3b)

**Comment by wanghe-fit2cloud** [comment]
1Panel 设置的端口有通过 `netstat` 命令查询到吗？
`journalctl -u 1panel.service -exf` 获取一下详细日志，看是否有 error 相关日志，截图或者发日志文件。

**Comment by Lucasliu666666** [comment]
我和这位同学有同样的问题，已经正常使用一个多月，突然有天无法登录1panel面板，无法正常使用了，请指教，谢谢
![image](https://github.com/user-attachments/assets/d8450ed6-0cd1-4c5e-b5c5-ef902a04aaf5)

**Comment by bai-jifei** [comment]
我也是同样的问题，某天突然无法登录1panel面板，无法正常使用了，使用命令重启1panel服务也没有用，但halo网站都能正常进入，求助，谢谢。
![image](https://github.com/user-attachments/assets/73782d0c-7ee5-4dcc-adf7-b541d311c721)

**Comment by PCQ1N** [comment]
试了Ubuntu，Debian和RockyLinux，都有这个问题。最后尝试在Ubuntu中修改了/etc/systemd/system/1panel.service文件解决，目前面板正常运行。
ExecStartPre=/bin/sleep 10
ExecStart=screen -dmS 1panel /usr/bin/1panel
或者
ExecStartPre=/usr/bin/tmux kill-session -t 1panel
ExecStart=/usr/bin/tmux new-session -d -s 1panel /usr/bin/1panel
ExecStop=/usr/bin/tmux kill-session -t 1panel
#ExecStart=/usr/bin/1panel
#ExecReload=/bin/kill -s HUP $MAINPID
