### ISSUE TITLE
[BUG] redis commander无法登录

### ISSUE THREAD

**Issue by linbet-2024** [1Panel-dev/1Panel#4752]
### 联系方式

linbetklin@163.com

### 1Panel 版本

1.0.0.5-lts

### 问题描述

抱歉只能在GitHub上面提交问题，因为还不能收验证码登录论坛
# 不能使用应用商店的redist commander 登录
![image](https://github.com/1Panel-dev/1Panel/assets/155411928/f26494ba-32ed-450a-b9bf-bea2cadd966b)
无法找到Username:的值

### 重现步骤

安装redist commander 

### 期待的正确结果

登录redis
并为wordpress配置redis缓存

### 相关日志输出

```shell
none
```

**Comment by wanghe-fit2cloud** [comment]
刚在本地环境测试，无法复现上述问题，如图：
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/99b51731-f0f1-4b59-ace1-474d0a523844">

> 登录信息是在安装时自定义的，可以点击 `参数` 按钮获取，如图：
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/f1ea3929-29ba-4f43-83a2-a9a855da9df4">

**Comment by linbet-2024** [comment]
自己解决了，网上无任何方法，
解决办法如下
进入redis commander安装目录，查看.env
吐槽一下，贵面面板的垃圾问档

**Comment by linbet-2024** [comment]
抱歉，是我不小心了，没看，带给你们打扰了，抱歉
