### ISSUE TITLE
[BUG] 许可证状态异常

### ISSUE THREAD

**Issue by zhimaxu** [1Panel-dev/1Panel#4753]
### 1Panel 版本

v1.10.5-lts

### 问题描述

许可证激活信息丢失，有许可证id，但高级功能全部失效，提示需要许可证

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/32806611/e02de344-0a91-4fb4-ad0e-1ef6fcab94d4)

**Comment by ssongliu** [comment]
感谢反馈，已知问题，节后会发布新版本解决

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
