### ISSUE TITLE
[FEATURE] 建议拦截记录增加 URL 加白功能

### ISSUE THREAD

**Issue by wangzhengkun** [1Panel-dev/1Panel#4755]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

由于某些接口携带 sql  和 html 指令，导致被 WAF 拦截
建议直接在拦截记录增加 URL 加白 按钮，不用手动去 黑白名单添加了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本支持。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
