### ISSUE TITLE
[FEATURE]希望可以为社区版添加简单的WAF拦截日志

### ISSUE THREAD

**Issue by IcyBlue17** [1Panel-dev/1Panel#4756]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

前几天用chatgpt-nextweb和更新wordpress主题设置的时候1panel waf错误地拦截了请求。但是我不知道是哪条规则误报了，后台也没有具体的日志说明是哪条规则拦截了哪个ip的请求，希望可以为社区版增加一个非常简单的waf拦截日志

### 请描述你建议的实现方案

在日志审计中网站日志增加一栏WAF拦截日志

**Comment by zhengkunwang223** [comment]
您好 暂时没有计划
可以关闭 1Panel WAF 并且安装应用商店的南墙 WAF

**Comment by xiexiaosheng** [comment]
我觉得社区版应该默认关闭waf
