### ISSUE TITLE
[FEATURE] 封锁记录增加永久拉黑 IP 功能

### ISSUE THREAD

**Issue by wangzhengkun** [1Panel-dev/1Panel#4757]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

当前的 CC 防御等功能 拉黑 IP 只是临时封禁
建议增加添加 IP 到黑名单功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本支持。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
