### ISSUE TITLE
[BUG] 手动编辑默认黑白名单的 IP 组导致错误

### ISSUE THREAD

**Issue by wangzhengkun** [1Panel-dev/1Panel#4759]
### 1Panel 版本

v1.10.5-lts

### 问题描述

手动编辑了一下 IP 的黑白名单 导致 OpenResty 报错
查看一下是手动拉黑 IP ，添加到默认的黑名单，多个 IP 在同一行

### 重现步骤

编辑默认的 黑名单 IP 组之后在拦截记录拉黑 IP

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本修复。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
