### ISSUE TITLE
[BUG] 专业版 WAF 数据库文件打开过多 导致内存占用

### ISSUE THREAD

**Issue by wangzhengkun** [1Panel-dev/1Panel#4760]
### 1Panel 版本

v1.10.5-lts

### 问题描述

1Panel 内存升高，在进程管理查看，是 1Panel 的 WAF 数据库文件打开没有释放

### 重现步骤

多点击几次拦截记录和封锁记录
然后查看进程管理中 1Panel 的文件打开

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.6-lts 版本已发布。
