### ISSUE TITLE
/usr/bin/1pctl: 行 349: 未预期的记号 ")" 附近有语法错误

### ISSUE THREAD

**Issue by adaaaaaa** [1Panel-dev/1Panel#4762]
### 1Panel 版本

1.10.5

### 问题描述

/usr/bin/1pctl: 行 349: 未预期的记号 ")" 附近有语法错误
/usr/bin/1pctl: 行 349: `        echo -e "1) 停止 1Panel 服务进程..."'

### 重现步骤

输入命令：1pctl

### 附加信息

重装过也不行

**Comment by wanghe-fit2cloud** [comment]
提供一下操作系统等信息。

**Comment by adaaaaaa** [comment]
@wanghe-fit2cloud 
archlinux 
kernel:6.6.28
zsh
KDE
python 3.12

AUR安装的，是不是aur有问题？

**Comment by wanghe-fit2cloud** [comment]
切换 `bash` 或者 `sh` 看一下命令执行效果

**Comment by adaaaaaa** [comment]
@wanghe-fit2cloud 
已经删了，装1panel-bin了，但是那个包不能更新到1.10.5
提示：无法成功请求最新版本，请检查服务器是否能够连接到外部网络环境。
哪个aur包是你维护的吗？

**Comment by wanghe-fit2cloud** [comment]
> @wanghe-fit2cloud 已经删了，装1panel-bin了，但是那个包不能更新到1.10.5 提示：无法成功请求最新版本，请检查服务器是否能够连接到外部网络环境。 哪个aur包是你维护的吗？

不是。
建议使用官方提供的安装脚本。你上面的问题应该就是 zsh 导致的语法不兼容。

**Comment by adaaaaaa** [comment]
@wanghe-fit2cloud 
> 你上面的问题应该就是 zsh 导致的语法不兼容。

我试过了，一样的报错。。。
您能打个包传到AUR上去吗？

**Comment by wanghe-fit2cloud** [comment]
> 您能打个包传到AUR上去吗？

先基于官方脚本手动适配吧，中短期内我们暂无支持计划，望理解。
