### ISSUE TITLE
[FEATURE] 应用商店上架 Headscale，Bird2，PowerDNS，PowerAdmin

### ISSUE THREAD

**Issue by Muska-Ami** [1Panel-dev/1Panel#4763]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

- Headscale: 自建Tailscale组网方案 https://headscale.net/
  - 建议同时上架官方文档中的Headscale网页管理面板 https://headscale.net/web-ui/
- Bird2: 开源网络路由软件 https://bird.network.cz/
  - 建议为该项目添加PowerDNS容器绑定
- PowerDNS: 领先的权威DNS服务器 https://www.powerdns.com/
- PowerAdmin: 友好的PowerDNS网页管理面板 https://www.poweradmin.org/

### 请描述你建议的实现方案

虽然上述软件并非全部提供了官方Docker部署方式，但以上项目均为较为出名的项目，建议添加至应用商店

**Comment by wanghe-fit2cloud** [comment]
应用商店中所有应用必须要求官方有提供 docker 部署方式。
> 可以先自行统计一下上述项目代码仓库是否开源、是否支持容器化部署。

**Comment by Muska-Ami** [comment]
Headscale 官方仓库中有一个docker部署方法，但标注了"社区文档": https://github.com/juanfont/headscale/blob/main/docs%2Frunning-headscale-container.md
Bird未找到官方的docker部署方法（很遗憾Bird2不满足条件，但如果可以的话还是希望能被加入应用商店）
PowerDNS 官方仓库中的docker部署方法:  https://github.com/PowerDNS/pdns/blob/master/Docker-README.md
PowerAdmin 也没有找到官方docker部署方法，类似的 PowerDNS-Admin 提供了docker部署方法
PowerDNS-Admin https://github.com/PowerDNS-Admin/PowerDNS-Admin

提及的项目均为开源项目

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述开源项目我们都有查看，基本上都不满足 star 要求。

目前，我们主要以项目的 star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有约 1 万 star 的开源项目，望理解。

部分应用官方也提供了 docker 安装教程或者 compose.yml 文件，建议使用 `容器` 功能来维护应用。
