### ISSUE TITLE
[BUG] 在应用商店 安装应用的时候，闪退到登录页面提示 当前用户无权限

### ISSUE THREAD

**Issue by 350226401** [1Panel-dev/1Panel#4765]
### 联系方式

350226401@qq.com

### 1Panel 版本

v1.10.5-lts

### 问题描述

在应用商店 安装应用的时候，闪退到登录页面提示 当前用户无权限

![微信图片_20240428150058](https://github.com/1Panel-dev/1Panel/assets/33481513/dfcce8e9-57c0-4535-8a4f-ba1a39fb71b5)

### 重现步骤

1、点击应用商店
2、安装应用，点击安装
3、之后就闪退到 登录页面，提示报错

### 附加信息

![微信图片_20240428150058](https://github.com/1Panel-dev/1Panel/assets/33481513/19ca2987-13a2-4511-b643-8d6f82ee4dd3)

**Comment by MiderWong** [comment]
原因是触发了WAF机制，解决方案：
1、通过ip:端口形式访问1P面板
2、暂时关闭WAF功能，等所有网站运行环境安装完成之后，再打开WAF

**Comment by 350226401** [comment]
***@***.***】的邮箱。您的邮件，我已经收到。

**Comment by 350226401** [comment]
但是我们根本就没开启WAF

![image](https://github.com/1Panel-dev/1Panel/assets/33481513/0e378fd1-cd11-447f-a4d8-19543ce65803)

**Comment by wanghe-fit2cloud** [comment]
通过 `IP:端口` 方式访问控制台，安装应用是否存在上述问题。

**Comment by 350226401** [comment]
通过IP访问时，问题未再出现

**Comment by wanghe-fit2cloud** [comment]
> 通过IP访问时，问题未再出现

域名访问 1Panel 系统是通过 1Panel 添加的反向代理网站还是自己搭建的 Nginx 反向代理。

**Comment by 350226401** [comment]
通过  应用商店 的 OpenResty来处理的

**Comment by wanghe-fit2cloud** [comment]
> 通过 应用商店 的 OpenResty来处理的

在不开启 WAF 时，未能复现问题。
> 进入 `高级功能` - `WAF`，再去检查一下全局设置和网站设置是否有开启某些规则开关。

**Comment by 350226401** [comment]
好的   感谢

**Comment by 350226401** [comment]
***@***.***】的邮箱。您的邮件，我已经收到。
