### ISSUE TITLE
[FEATURE] 应用商店增加 Firefly III 应用

### ISSUE THREAD

**Issue by HenryWu01** [1Panel-dev/1Panel#4767]
### 1Panel 版本

N/A

### 请描述您的需求或者改进建议

Firefly III 是一款开源，完全自托管和隔离的个人记账系统，支持中文、多币种，拥有清晰的视图、跟踪支出和收入，功能丰富，支持自动化处理记账 （介绍来自小众软件）。

官方的 Docker 地址: https://hub.docker.com/r/fireflyiii/core

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上架上述应用。
> 官方提供了 docker 安装方式，目前版本可以通过 `容器` 功能来管理应用。

**Comment by HenryWu01** [comment]
PR 已提交: https://github.com/1Panel-dev/appstore/pull/1328

**Comment by HenryWu01** [comment]
该应用已经添加到 ``1Panel`` 官方应用商店，故关闭此 issue
