### ISSUE TITLE
[BUG]专业版开启防篡改，影响面板访问，会掉面板端口

### ISSUE THREAD

**Issue by Alexzzz2008** [1Panel-dev/1Panel#4768]
### 1Panel 版本

1.10.5

### 问题描述

[BUG]专业版开启防篡改，影响面板访问，会掉面板端口
![2024-04-27_23-45-45_看图王](https://github.com/1Panel-dev/1Panel/assets/40814658/39e7d2a7-5f30-40d7-865b-50373d2ddd1f)

面板端口查不到了，也打不开面板了

### 重现步骤

[BUG]专业版开启防篡改，影响面板访问，会掉面板端口

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，已经复现上述问题，会在下个版本修复。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
