### ISSUE TITLE
[FEATURE] 建议增加地址栏里面输入路径访问

### ISSUE THREAD

**Issue by hhun** [1Panel-dev/1Panel#477]
### 1Panel 版本

1.0.5

### 请描述您的需求或者改进建议

1. 文件管理里面，地址栏输入路径访问，例如：`/usr/lib/systemd/system`
2. 目前文件搜索只能搜索当前目录，不能搜索子目录，**建议增加搜索子目录**，不能搜索子目录搜索意义不大。

**Comment by zhengkunwang223** [comment]
感谢建议，后续版本会支持这两个功能

**Comment by wanghe-fit2cloud** [comment]
v1.1.0 版本已发布，支持输入URL直接访问。
搜索子目录的需求会在 v1.2.0 版本支持。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
