### ISSUE TITLE
[BUG]备份文件夹路径出错

### ISSUE THREAD

**Issue by Alexzzz2008** [1Panel-dev/1Panel#4770]
### 1Panel 版本

1.10.5

### 问题描述

使用挂载硬盘 作为备份硬盘，执行计划任务，自动生成了套娃文件夹。
[
![2024-04-28_15-38-35](https://github.com/1Panel-dev/1Panel/assets/40814658/57d97b50-7b90-4a96-a294-52d661e1d785)
](url)

这里设置的路径是挂载的硬盘，计划任务执行后，会在设置的路径下  自动又成了空文件夹

![2024-04-28_15-46-36](https://github.com/1Panel-dev/1Panel/assets/40814658/b95fcdff-c2b7-4b96-8e01-bd84e5a07d52)
![2024-04-28_15-47-36](https://github.com/1Panel-dev/1Panel/assets/40814658/114867cb-7bc5-4997-8f88-aafa639f06f9)

### 重现步骤

使用挂载硬盘 作为备份硬盘，执行计划任务，自动生成了套娃文件夹。

**Comment by ssongliu** [comment]
感谢反馈，我们开发环境复现一下

**Comment by ssongliu** [comment]
麻烦升级到 1.10.17 最新版本，确认一下问题是否仍然存在
