### ISSUE TITLE
[BUG] 无法删除openresty某一个site的proxy

### ISSUE THREAD

**Issue by hnuzhoulin** [1Panel-dev/1Panel#4771]
### 联系方式

hnuzhoulin@163.com

### 1Panel 版本

v1.10.5-tls

### 问题描述

删除某一个反向代理时报错，无法删除

![image](https://github.com/1Panel-dev/1Panel/assets/6347012/b56aa5d8-a32c-45d5-9945-4bedbc0c358e)

### 重现步骤

不知道如何能复现，我是一路升级过来的，很久以前添加的proxy

### 期待的正确结果

能正确删除proxy

### 相关日志输出

请求参数错误: Key: 'WebsiteProxyConfig.Modifier' Error:Field validation for 'Modifier' failed on the 'required' tag

**Comment by zhengkunwang223** [comment]
截图看一下源文

**Comment by zhengkunwang223** [comment]
已复现 是删除匹配规则导致的 后续把匹配规则改为非必填

**Comment by wanghe-fit2cloud** [comment]
v1.10.6-lts 版本已发布。
