### ISSUE TITLE
[FEATURE]将降级、无权限、自动退出、突然无法访问等通用或常见问题及解决方案设置为置顶

### ISSUE THREAD

**Issue by MiderWong** [1Panel-dev/1Panel#4772]
### 1Panel 版本

1.10.5

### 请描述您的需求或者改进建议

比如把以下三个问题置顶，可以减少很多升级后问题的issues：
#### `已解决，已发布版本` 问题列表
- 1、提示无权限，原因及解决方案参考：#4625 
- 2、无法降级的原因和降级方案，参考：#4670 
#### `已解决，未发布版本` 问题列表(可能影响业务)
> 1、升级1.10.3版本后，容器内自定义命令会在退出容器时也关闭
>> - 关联问题：#4653 
>> - 解决方案：#4660 

### 附加信息

置顶效果：
![效果](https://github.com/1Panel-dev/1Panel/assets/7487008/470afa01-79c3-401c-87e2-03e8ebfa0ec1)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们后面维护一个常见问题列表。
