### ISSUE TITLE
[BUG]应用商店安装应用全部超时

### ISSUE THREAD

**Issue by youngledo** [1Panel-dev/1Panel#4773]
### 1Panel 版本

1.10.5

### 问题描述

<img width="656" alt="图片" src="https://github.com/1Panel-dev/1Panel/assets/68590897/2b566464-9e66-4ffa-8153-663fc095a606">

不管安装哪个应用都是如此，已经配置了镜像加速，还是不行：
<img width="910" alt="图片" src="https://github.com/1Panel-dev/1Panel/assets/68590897/5ac54956-d799-4cc4-a0e8-8abe77998275">

### 重现步骤

本地部署，不知道怎么重现。

**Comment by wanghe-fit2cloud** [comment]
根据错误信息显示，就是应用镜像拉取超时导致的。

可以替换为 1Panel 官方文档中提供的镜像加速地址（点击 `快速跳转` 按钮）。
也可以预先手动拉取应用镜像，成功之后再来安装应用。
