### ISSUE TITLE
1Panel 的侧边栏"高级功能"按功能分类到其他区域

### ISSUE THREAD

**Issue by Muska-Ami** [1Panel-dev/1Panel#4774]
### 1Panel 版本

v1.10.5-lts

### 请描述您的需求或者改进建议

所有高级功能混在一起显得很突兀，希望能分类到正确的位置而不是全部集中到一个列表内

### 请描述你建议的实现方案

在某IDC群内讨论时一个问题及建议方案
> 这样不好统一关闭/开启

为列表选项添加一个高级功能的属性，根据属性判断是否开关

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前专业版功能菜单的布置旨在保持对社区版本的独立性，并实现功能集中管理的最佳效果。
> 后续版本我们还会陆续推出更多专业版功能，所有独立的菜单均支持在面板设置页面控制显示、隐藏。
