### ISSUE TITLE
[BUG] 1panel ip 显示问题

### ISSUE THREAD

**Issue by mobeicanyue** [1Panel-dev/1Panel#4778]
### 1Panel 版本

1.10.5

### 问题描述

当一台服务器同时拥有 ipv4 v6 时，1panel 会显示

```
[1Panel Log]: 请用浏览器访问面板: 
[1Panel Log]: 外网地址: http://ipv6:port/random 
[1Panel Log]: 内网地址: http://ipv4:port/random 
[1Panel Log]: 面板用户:  
[1Panel Log]: 面板密码: 
```

然而 1panel 默认绑定的是 v4，访问 外网地址无相应

### 重现步骤

安装 1panel 日志显示

### 期待的正确结果

当一台服务器同时拥有 ipv4 v6 时，1panel 显示正确的绑定的外网地址

**Comment by wanghe-fit2cloud** [comment]
1Panel 端口只支持绑定 IPv4 或者 IPv6，支持在面板设置页面或者 `1pctl listen-ip` 命令切换绑定。
刚查看了安装脚本，如果 `curl -s https://api64.ipify.org` 命令判断服务器支持 IPv6，是会触发端口绑定至 IPv6 的命令。

> 问题描述中说 `然而 1panel 默认绑定的是 v4`，可以通过 `netstat -ntlp` 命令查看端口具体绑定情况。

**Comment by mobeicanyue** [comment]
我的意思是 ip 绑定的是 v4，访问 v6 无反应。
应该将默认的外网地址设为 v4 的。内网地址应为 10.0.x.x 或者 192.168.x.x 之类的

**Comment by wanghe-fit2cloud** [comment]
> 我的意思是 ip 绑定的是 v4，访问 v6 无反应。

这点正常，1Panel 系统就是只绑定 IPv4 或者是 IPv6，可以在面板设置页面或者 `1pctl listen-ip` 命令切换。
可以通过 `netstat -ntlp` 命令查看。

> 应该将默认的外网地址设为 v4 的。内网地址应为 10.0.x.x 或者 192.168.x.x 之类的

具体的端口绑定逻辑是根据 `curl -s https://api64.ipify.org` 命令的返回值来判断的，你可以自行执行命令查看一下。

**Comment by mobeicanyue** [comment]
> 具体的端口绑定逻辑是根据 curl -s https://api64.ipify.org 命令的返回值来判断的
但是返回的结果，和绑定的ipv4/6栈并不对应。

`curl -s https://api64.ipify.org` 返回了 v6 但是实际绑定却为 v4，很容易造成误解

建议更换

https://ipw.cn/doc/ipv6/user/cmd_getip.html

`访问IPv4/IPv6双栈站点，如果返回IPv6地址，则IPv6访问优先，否则为 IPv4 地址。`
`curl test.ipw.cn`

**Comment by wanghe-fit2cloud** [comment]
> 建议更换
> 
> https://ipw.cn/doc/ipv6/user/cmd_getip.html
> 
> `访问IPv4/IPv6双栈站点，如果返回IPv6地址，则IPv6访问优先，否则为 IPv4 地址。` `curl test.ipw.cn`

好的，麻烦提供一下以下两条命令的截图：
- `curl -s https://api64.ipify.org`
- `curl test.ipw.cn`

**Comment by mobeicanyue** [comment]
这两个好像都是 ipv6

要不这样，直接读服务器的网卡参数
`ip addr show eth0 | grep -oP 'inet \K[0-9.]+(?=\/.*)'`
这个查 v4

如果没有就 fallback 到 v6
`ip addr show eth0 | grep -oP 'inet6 \K[0-9a-fA-F:]+(?=/\d+)' | head -n 1`

**Comment by wanghe-fit2cloud** [comment]
多网卡服务器也不太好确定具体的网卡，eth0 网卡名也不一定。
> 脚本先不修改吧，然后通过面板设置页面或者 1pctl listen-ip 命令切换吧。
