### ISSUE TITLE
[FEATURE] 网站本地目录太深，能直接放到/www/wwwroot/ 吗？

### ISSUE THREAD

**Issue by hhun** [1Panel-dev/1Panel#478]
### 1Panel 版本

1.0.5

### 请描述您的需求或者改进建议

网站本地目录`/opt/1panel/apps/openresty/OpenResty/www/sites/`太深，能直接放到 `/www/wwwroot/` 吗？
一个问题是目录太少，还有个问题是网站创建后目录不能修改。

**Comment by zhengkunwang223** [comment]
1. 网站目录放在在 openresty 下面方便备份和修改网站文件操作 
2. 由于 docker 容器的特性，所以我们固定了网站目录，后续可以考虑修改

**Comment by hhun** [comment]
> 1. 网站目录放在在 openresty 下面方便备份和修改网站文件操作
> 2. 由于 docker 容器的特性，所以我们固定了网站目录，后续可以考虑修改

通过创建软连接  `ln -s /opt/1panel/apps/openresty/OpenResty/www/sites /www/wwwroot` 就可以解决这个问题了

**Comment by wanghe-fit2cloud** [comment]
重复 #2783
