### ISSUE TITLE
[FEATURE]将frps的auth.token参数加在可视化UI中可供方便修改

### ISSUE THREAD

**Issue by lizina66** [1Panel-dev/1Panel#4780]
### 1Panel 版本

1.10.5

### 请描述您的需求或者改进建议

frps(服务端)可视化的参数列表里缺少一个token参数，这个token参数导致有些时候忘记有它。除了1P面板的同宗客户端是同样默认外，在其他类型的客户端不输入token是无法连接的

### 请描述你建议的实现方案

将frps/data/frps.toml的auth.token参数加在可视化UI中可供方便修改。谢谢
![PixPin_2024-04-28_21-36-47](https://github.com/1Panel-dev/1Panel/assets/121975413/b3940316-c8ef-4905-b09c-fff9196caf8c)
![PixPin_2024-04-28_21-36-59](https://github.com/1Panel-dev/1Panel/assets/121975413/6d1c8897-fed6-422c-8311-6ee959319c6f)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持。

**Comment by wanghe-fit2cloud** [comment]
已更新。
进入应用商店，点击右上角的【更新应用列表】按钮，待同步完成后，在安装服务端和客户端时即可自定义密钥。
