### ISSUE TITLE
[FEATURE]反向代理的源文件编辑窗口太小了

### ISSUE THREAD

**Issue by xuiam** [1Panel-dev/1Panel#4783]
### 1Panel 版本

1.10.5-lts

### 位置内容

![image](https://github.com/1Panel-dev/1Panel/assets/42964379/1be211f5-0440-4a43-b9e8-d5975b36a60c)

### 建议

反向代理的源文件编辑窗口太小了，希望可以改大，或者可以拖动边缘放大，或者可以有全屏按钮。
还有内容，希望可以增加按钮设置为是否自动换行，目前是一行内容一直往后，希望可以切换模式。或者直接默认换行。本来窗口就小，不换行后面看的很麻烦。望优化，谢谢。

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本优化

**Comment by zyyfit** [comment]
目前将源文编辑窗口调大了一些，宽度由 40% 调整到 50% 了，移动端也调整为全部显示了。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
