### ISSUE TITLE
[BUG]Ubuntu系统无权限装Gitea

### ISSUE THREAD

**Issue by motao123** [1Panel-dev/1Panel#4786]
### 1Panel 版本

专业版 v1.10.5-lts

### 问题描述

查看了用户是root，别的都可以，就是无法装Gitea

### 重现步骤

https://github.com/1Panel-dev/1Panel/assets/30110326/d47ef432-3f49-4282-a932-f5e89af6eff7

**Comment by MiderWong** [comment]
问题可能与 #4772 中提到的一样
#### 可能有效的方案
- 1、使用ip:port访问1P面板，执行应用安装
- 2、使用域名访问1p面板时，不要太频繁，避免触发WAF

**Comment by zhengkunwang223** [comment]
被 WAF 拦了 后续版本会优化 
https://bbs.fit2cloud.com/t/topic/4540
可以看一下这个

**Comment by skyytor** [comment]
实测没开waf，但是反代后也会遇到这个
