### ISSUE TITLE
[FEATURE] 通过路由器的 UPnP / NAT-PMP 功能来转发1panel的端口

### ISSUE THREAD

**Issue by bai0012** [1Panel-dev/1Panel#4787]
### 1Panel 版本

1.10.5-lts

### 请描述您的需求或者改进建议

建议在面板设置页面里加入“路由器的 UPnP / NAT-PMP 功能来转发端口”的选项，这样就可以在路由器具有公网ip的时候通过路由器的ip和设定的端口访问1panel了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们暂无支持上述需求的计划，望理解。
