### ISSUE TITLE
[FEATURE] 增加更改Disk image location 目录的功能

### ISSUE THREAD

**Issue by cktk** [1Panel-dev/1Panel#4788]
### 1Panel 版本

1.10.5-lts

### 请描述您的需求或者改进建议

能否增加更改Disk image location 目录的功能 根目录磁盘满了 /home还有很多
如果能增加  修改根目录磁盘大小的的功能就更好了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

目前版本先考虑软链的方式来实现 docker 数据目录的迁移。

**Comment by wanghe-fit2cloud** [comment]
重复问题 https://github.com/1Panel-dev/1Panel/issues/2173
