### ISSUE TITLE
Podman支持

### ISSUE THREAD

**Issue by Nova4718** [1Panel-dev/1Panel#4789]
### 1Panel 版本

1.10

### 请描述您的需求或者改进建议

docker必须要有root权限才能进行安装，如果能够基于podman，是否可以实现非root用户安装1panel

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们可能会在后续 v2.x 版本考虑支持上述需求。
重复问题 https://github.com/1Panel-dev/1Panel/issues/1070
