### ISSUE TITLE
[FEATURE] 请问证书申请为什么不继续支持 dnspod 账户

### ISSUE THREAD

**Issue by W4J1e** [1Panel-dev/1Panel#4792]
### 1Panel 版本

v1.10.5-Its

### 请描述您的需求或者改进建议

请问证书申请功能中，为什么不继续支持 dnspod 账户，而是已经停止维护，将来可能废弃？
使用腾讯云子账户的话，配置权限好麻烦，如果权限梭哈，又担心不小心泄露了 ID 和 key 不安全。

**Comment by wanghe-fit2cloud** [comment]
<img width="610" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/95bc7fa8-ab59-46a6-ad43-61e85b1df4bb">
