### ISSUE TITLE
[BUG] WAF拦截记录与网站不匹配

### ISSUE THREAD

**Issue by ImAmelie** [1Panel-dev/1Panel#4793]
### 1Panel 版本

v1.10.5-lts

### 问题描述

我有 2 个网站分别是（域名做了替换）：

- example.com:65530
- example.com:65531

我给两个网站都设置了 WAF 拦截。但是 65531 的拦截记录都显示在 65530 中

### 重现步骤

不清楚如何复现

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
