### ISSUE TITLE
[BUG] IP归属地不正确

### ISSUE THREAD

**Issue by ImAmelie** [1Panel-dev/1Panel#4795]
### 1Panel 版本

v1.10.5-lts

### 问题描述

WAF 拦截记录中显示的 IP 归属地不正确

### 重现步骤

无

**Comment by wanghe-fit2cloud** [comment]
麻烦再提供一下详细的 IP 及归属地等信息，方便后续定位。

**Comment by ImAmelie** [comment]
@wanghe-fit2cloud 你们的 geoip 文件在哪？我找几个跟我同地区的 IP

**Comment by zhengkunwang223** [comment]
> @wanghe-fit2cloud 你们的 geoip 文件在哪？我找几个跟我同地区的 IP

五一之后的版本会更新一部分 ip 信息，可以关注一下

**Comment by zhengkunwang223** [comment]
已发布 可以测试一下
