### ISSUE TITLE
[FEATURE]docker升级会丢失用户配置的路径信息

### ISSUE THREAD

**Issue by meng-plus** [1Panel-dev/1Panel#4798]
### 1Panel 版本

专业版v1.10.6-lts

### 请描述您的需求或者改进建议

应用商店检测到应用升级，点击更新后，成功升级
但是，我对容器的docker-compose里的路径有所修改，避免镜像打包过大
以及opt路径在系统中，有系统崩溃丢失数据的风险，因此我将路径设定到外部，可是每次app升级都要再次手动修改路径

### 请描述你建议的实现方案

希望更新app 只更新镜像 其它的别动，顶多加个恢复默认配置
真的别动配置
要么你给个选项，能够指定数据保存的位置全局修改

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复问题 https://github.com/1Panel-dev/1Panel/issues/2826
