### ISSUE TITLE
[BUG]数据库管理，不能设置复杂密码

### ISSUE THREAD

**Issue by springeye** [1Panel-dev/1Panel#4799]
### 1Panel 版本

v1.10.6-lts

### 问题描述

数据库管理设置密码的时候不能设置复杂的密码,
比如用这个密码
```
FlR7[5WW2Px$DcAfB&3F*ei@jt)(m%RKjy
```
![image](https://github.com/1Panel-dev/1Panel/assets/1314740/22264d7a-2407-4955-8b98-e8ac4828775a)

### 重现步骤

一次进入数据库->从服务器同步->无法获取密码,请修改
然后点击修改密码输入密码"FlR7[5WW2Px$DcAfB&3F*ei@jt)(m%RKjy"

### 期待的正确结果

正常设置密码

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述建议。

**Comment by wanghe-fit2cloud** [comment]
密码复杂度相关问题的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4290
