### ISSUE TITLE
[FEATURE] 数据库权限，除了【所有人】、【指定IP】，还应该加一个【本地】

### ISSUE THREAD

**Issue by hhun** [1Panel-dev/1Panel#480]
### 1Panel 版本

1.0.5

### 请描述您的需求或者改进建议

数据库权限，除了【所有人】、【指定IP】，还应该加一个【本地】

**Comment by zhengkunwang223** [comment]
容器中的 MySQL ，设置 本地 数据库权限意义不大，设置完毕之后，无法访问。
