### ISSUE TITLE
[BUG]SSL Let's Encrypt账号添加失败

### ISSUE THREAD

**Issue by fxln** [1Panel-dev/1Panel#4800]
### 1Panel 版本

v1.10.6-tls

### 问题描述

![Screenshot_2024-04-30-11-20-48-578_mark via](https://github.com/1Panel-dev/1Panel/assets/72055650/2dece431-9dab-4fab-a46c-0c598d7a3c23)

SSL证书Let's Encrypt账号添加失败

### 重现步骤

Let's Encrypt账号添加

**Comment by wanghe-fit2cloud** [comment]
先检查一下你的 1Panel 服务器是否能正常访问外部网络。
> 本地开发测试环境未能复现上述问题。
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/fac6298e-1766-4466-b7d7-50bd9bfebc75)

**Comment by fxln** [comment]
能正常访问网络，添加另一个证书账号，可以正常添加

**Comment by fxln** [comment]
识别不到报错的域名
![mmexport1714459879965](https://github.com/1Panel-dev/1Panel/assets/72055650/50479d62-2132-4dee-a88d-dbd67fe61a36)

**Comment by fxln** [comment]
![mmexport1714459879965](https://github.com/1Panel-dev/1Panel/assets/72055650/05dcca0d-feb7-427b-bb4a-89e899c57ca1)

**Comment by wanghe-fit2cloud** [comment]
> 能正常访问网络，添加另一个证书账号，可以正常添加

进入 `日志审计` 菜单，查看一下系统日志。
> 目前根据页面的错误提示信息来看，就是服务器网络问题导致的 1Panel 申请 acme-v02 外部网络不通

**Comment by fxln** [comment]
![mmexport1714459995517](https://github.com/1Panel-dev/1Panel/assets/72055650/f70d9224-08f5-408e-af07-882c95fd928a)

**Comment by fxln** [comment]
看得到图片吗

**Comment by wanghe-fit2cloud** [comment]
检查一下服务器网络，要确保能正常访问 acme 外部网络。

**Comment by fxln** [comment]
ping那个域名报错

**Comment by wanghe-fit2cloud** [comment]
> ping那个域名报错

`ping acme-v02.api.letsencrypt.org` 或者 `ping baidu.com` 试一下
> 如果不通，应该是服务器 dns 解析异常

**Comment by fxln** [comment]
![mmexport1714460796667](https://github.com/1Panel-dev/1Panel/assets/72055650/728096f8-04eb-4698-bdbc-9024b5138dbe)
本地也是ping不通

**Comment by fxln** [comment]
百度还有我的其他服务器的域名都ping得通
