### ISSUE TITLE
[FEATURE] NAS产品的安装教程

### ISSUE THREAD

**Issue by QYG2297248353** [1Panel-dev/1Panel#4802]
### 1Panel 版本

v1.10.6-lts

### 请描述您的需求或者改进建议

群晖、威联通、绿联、极空间、华为等Nas产品的支持，虽说说是Nas，大多数都支持 Docker，性能也比2c2g的轻量服务器好很多，底层也是个Linux系统。希望更新一下官网安装教程，对这类产品的安装说明。

### 请描述你建议的实现方案

增加安装文档分类 [Nas产品](https://1panel.cn/docs/installation/online_installation/)
如果能上架应用商店也不是不可以，可以研究研究

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

相关问题的讨论，汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4004
