### ISSUE TITLE
[BUG] Supervisor无法选择运行运行目录，选择文件窗口关闭逻辑错误

### ISSUE THREAD

**Issue by likesrt** [1Panel-dev/1Panel#4805]
### 联系方式

yuyan@broue.cn

### 1Panel 版本

专业版：V1.10.6-Its
1.10.5版本也有此问题

### 问题描述

~~工具箱中 Supervisor 创建守护进程 ，选择运行目录时不能有效选中运行目录~~

同时 使用ESC或者点击取消  取消创建守护进程时  选择运行目录弹窗 未正常关闭。

### 重现步骤

~~安装 Supervisor 创建守护进程~~

### 期待的正确结果

~~正常选中目录并展示到输入框~~

使用取消或者esc关闭窗口时按照正常逻辑关闭文件选择窗口

### 附加信息

https://github.com/1Panel-dev/1Panel/assets/31208912/12bcaae2-b0a7-4bae-a584-7a5bcea9b72a

**Comment by MiderWong** [comment]
#### 用法
你点击前面的选中框就可以选中了。
#### 选中框点击效果
![选中框点击效果](https://github.com/1Panel-dev/1Panel/assets/7487008/ecaff6f2-7dc2-4db2-ab85-f3d3a0d3e275)
#### 文件夹选中效果
![文件夹选中效果](https://github.com/1Panel-dev/1Panel/assets/7487008/f97fb667-1784-4f59-89ba-2f6de0c40e8f)

**Comment by likesrt** [comment]
感谢告知 关闭文件窗口时是否可以优化一下

**Comment by MiderWong** [comment]
文件窗口关闭优化以及右侧半边弹窗优化之前已经有FETURE提到，后续会有优化。
