### ISSUE TITLE
[BUG] 采用腾讯EdgeOne 加速之后，提示网站不存在，请检查域名

### ISSUE THREAD

**Issue by aimdotsh** [1Panel-dev/1Panel#4806]
### 1Panel 版本

1.10.5

### 问题描述

采用腾讯EdgeOne 加速之后，提示 网站不存在，请检查域名。
<img width="353" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/27554033/340f6653-1559-4277-86e2-2b07ea291150">

### 重现步骤

腾讯 EdgeOne 加速之后，加速域名是 a.abc.com，源站 IP/域名 是通过 1Panel 搭建的 网站（反向代理）「sg.abc.com 。然后通过加速域名访问 a.abc.com 之后提示  网站不存在，请检查域名。

### 期待的正确结果

应该可以正常浏览网站。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by zhengkunwang223** [comment]
1Panel 的 waf 会检测网站是否在 1Panel 的网站列表中，如果访问的域名不在，就会拦截
所以可能需要你在 1Panel 添加你要访问的网站域名

**Comment by aimdotsh** [comment]
可以了。
