### ISSUE TITLE
[FEATURE] 有考虑支持 docker swarm 吗

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#4809]
### 1Panel 版本

社区版 v1.10.6-lts

### 请描述您的需求或者改进建议

有考虑支持 docker swarm 吗，使用 docker swarm 来管理应用，这样升级时是无缝的，不会出现 docker-compose 升级重启时服务不可用的情况

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/1096
