### ISSUE TITLE
[关于面板Https访问]

### ISSUE THREAD

**Issue by TcDhlPro** [1Panel-dev/1Panel#481]
### 1Panel 版本

v1.0.5

### 请描述您的需求或者改进建议

面板目前是http> 公网+自定义端口 的方式访问.

利用OpenResty
比如面板的访问端口是: 6666
将面板的访问端口(6666), 设在localhost, localhost:6666
然后在OpenResty中对localhost:6666进行反向代理, 这样能满足Https, 自动更新证书, 添加访问域名

快点说什么时候更新!!!

**Comment by zhengkunwang223** [comment]
您好 这个我们已经在规划中了 后续版本实现 请耐心等待

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
