### ISSUE TITLE
[BUG]防火墙关闭某个小项， 无效。

### ISSUE THREAD

**Issue by Alexzzz2008** [1Panel-dev/1Panel#4811]
### 1Panel 版本

1.10.6

### 问题描述

waf防火墙 关闭某个 参数规则 ，无效
![2024-04-30_18-58-23](https://github.com/1Panel-dev/1Panel/assets/40814658/e3a82b86-cc49-4868-a873-c5251c89ec73)
![2024-04-30_18-58-50](https://github.com/1Panel-dev/1Panel/assets/40814658/df4b505a-4e77-4235-80df-7e0fea3c978f)
![2024-04-30_18-56-21](https://github.com/1Panel-dev/1Panel/assets/40814658/c1fc55a3-5056-426e-9c45-030109c08f6c)

如图，在全局里 关闭了。在网站设置里也关闭了。 但是实际操作还是被拦截了，也有拦截记录。

最后关闭了 全局设置里的 总开关，才解决了。

### 重现步骤

waf防火墙 关闭某个 参数规则 ，无效

**Comment by Alexzzz2008** [comment]
另外 希望添加  修改全局配置后，批量应用到全部网站   ，不然要一个个去设置。

**Comment by zhengkunwang223** [comment]
需要去网站中设置，后续会增加应用到网站功能

**Comment by Alexzzz2008** [comment]
> 需要去网站中设置，后续会增加应用到网站功能

我发的图片里，不是已经在网站里设置了么？  还要去哪设置？

**Comment by zhengkunwang223** [comment]
> > 需要去网站中设置，后续会增加应用到网站功能
> 
> 
> 
> 我发的图片里，不是已经在网站里设置了么？  还要去哪设置？

不好意思看错了，我们先复现一下

**Comment by Alexzzz2008** [comment]
> > > 需要去网站中设置，后续会增加应用到网站功能
> > 
> > 
> > 我发的图片里，不是已经在网站里设置了么？  还要去哪设置？
> 
> 不好意思看错了，我们先复现一下

有没有复现啊  这个问题挺急的 一直要用到的

**Comment by zhengkunwang223** [comment]
> > > > 需要去网站中设置，后续会增加应用到网站功能
> > > 
> > > 
> > > 我发的图片里，不是已经在网站里设置了么？  还要去哪设置？
> > 
> > 
> > 不好意思看错了，我们先复现一下
> 
> 有没有复现啊 这个问题挺急的 一直要用到的

我测试了一下 没有复现

**Comment by zhengkunwang223** [comment]
经过远程调试，是使用问题，需要同时关闭 SQL 注入防御和 SQL 注入的小项
