### ISSUE TITLE
[FEATURE]《开源的palworld》

### ISSUE THREAD

**Issue by skyhhjmk** [1Panel-dev/1Panel#4812]
### 1Panel 版本

1

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/78078552/1021b9d6-99e9-443e-864a-bfe158ae9e4b)
![image](https://github.com/1Panel-dev/1Panel/assets/78078552/bcea98a4-fd3c-4c10-abbb-9b9757393727)
![image](https://github.com/1Panel-dev/1Panel/assets/78078552/e17d5c9c-80fb-4e31-8f6a-45972f625983)
![image](https://github.com/1Panel-dev/1Panel/assets/78078552/cf65c009-17e2-4757-836b-4d358749b4e2)

**Comment by wanghe-fit2cloud** [comment]
目前应用商店正式仓库中已经支持该游戏。

**Comment by skyhhjmk** [comment]
《知名且活跃**的~~开源~~项目**》
