### ISSUE TITLE
[BUG]防火墙过滤了mcsm的正常请求

### ISSUE THREAD

**Issue by kndxhz** [1Panel-dev/1Panel#4814]
### 联系方式

kndxhz@163.com

### 1Panel 版本

v1.10.6-lts

### 问题描述

反代的mcsm会导致触发1panel防火墙
经排查，是SQL过滤导致
![image](https://github.com/1Panel-dev/1Panel/assets/113306265/76fcd2f9-e92c-45d2-a013-a4fc65d48374)
![image](https://github.com/1Panel-dev/1Panel/assets/113306265/bc86780f-eac3-4d55-98bb-b19002d608dd)
![image](https://github.com/1Panel-dev/1Panel/assets/113306265/a963b198-67f1-4404-8e47-7102a2c7fe0d)

### 重现步骤

自建一个mcsm v10 （不要用应用商店docker的，那是旧版本）
反代mcsm web端口
连接远程节点（我这里使用的是openfrp穿透的家里云）
![image](https://github.com/1Panel-dev/1Panel/assets/113306265/b8a0490b-dbc5-4a43-86d4-84119fbaa5f9)
修改任意实例的文件

**出现403报错**
![image](https://github.com/1Panel-dev/1Panel/assets/113306265/3fd6e5fc-a6eb-4e3d-854d-12d46d992773)

### 期待的正确结果

正确保存文件，并且不报错

### 相关日志输出

```shell
mcsm的web端日志
2024-04-30T17:16:10.358 INFO [HTTP] IP: ::ffff:127.0.0.1 USER: admin UUID: 1f876c521d3245ea83904159ab104c22
2024-04-30T17:16:13.475 INFO [HTTP] PUT: http://mcsm.k****z.cn/api/files?daemonId=259******d80d0e6cfe759647d&uuid=7a4fe09a9ac*****650acc&token=cce315f407cb435*****14468551897
```

**Comment by wanghe-fit2cloud** [comment]
参考该 issue https://github.com/1Panel-dev/1Panel/issues/4636
