### ISSUE TITLE
[FEATURE] 一键安装halo默认关闭防火墙WAF的部分设置

### ISSUE THREAD

**Issue by makerjackie** [1Panel-dev/1Panel#4815]
### 1Panel 版本

1.10.5-lts

### 请描述您的需求或者改进建议

我发现在 1panel 中一键安装 halo 并且配置 https 网站后必须关闭部分防火墙。否则会出现如下的 issue

https://github.com/halo-dev/halo/issues/5834
https://github.com/1Panel-dev/1Panel/issues/4557 => 最终我是关闭防火墙解决的

这对新手可能会不太友好，我也是搜索了蛮久才知道解决方案的。建议将关闭防火墙（的部分规则？）写在文档中。或者一键安装的时候就默认关闭。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
后续版本会考虑通过应用模版等方式来优化上述体验，相关问题统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4636
