### ISSUE TITLE
[BUG]主页-概览-磁盘挂载点路径带空格无法正常显示

### ISSUE THREAD

**Issue by Kx-Y** [1Panel-dev/1Panel#4818]
### 1Panel 版本

1.10.6

### 问题描述

![图片](https://github.com/1Panel-dev/1Panel/assets/86878459/d87b4358-09be-414a-b8e0-25a93155a822)

### 重现步骤

磁盘挂载路径带有空格时出现

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by ssongliu** [comment]
麻烦提供一下执行返回： `df -hT -P|grep '/'|grep -v tmpfs|grep -v 'snap/core'|grep -v udev `

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
