### ISSUE TITLE
[FEATURE] 应用参数配置 halo 数据库选择

### ISSUE THREAD

**Issue by HowieHz** [1Panel-dev/1Panel#4821]
### 1Panel 版本

v1.10.6-lts

### 请描述您的需求或者改进建议

halo 数据库使用 mariadb 现在是完全无法 work 的 https://github.com/halo-dev/halo/issues/5534#issuecomment-2011499798
得换成 mysql 的驱动才能运行

目前每次更新都要先 error 启动一次，之后再手动编辑改为 mysql 驱动，这样非常不方便

可否在高级设置里增加一项，让用户可以手动指定为 mysql 的驱动，而不是仅仅遵从`${PANEL_DB_TYPE}`
![image](https://github.com/1Panel-dev/1Panel/assets/94725606/e0022db5-89b4-4a27-9289-7317c9acf49a)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by ruibaby** [comment]
关于 Halo 的 MariaDB 驱动问题，将在 https://github.com/halo-dev/halo/pull/6133 修复，并发布到 2.17.0。
