### ISSUE TITLE
[FEATURE] 应用参数配置 `umami 哈希盐 (随机字符串)` 变更为可修改项

### ISSUE THREAD

**Issue by HowieHz** [1Panel-dev/1Panel#4822]
### 1Panel 版本

v1.10.6-lts

### 请描述您的需求或者改进建议

每当 token 泄漏，哈希盐 (随机字符串) 就要进行修改

但是参数配置这一项是被锁定的，必须要去 .env 文件里修改，非常不方便

已经和作者确认过修改哈希盐不会影响已有数据
另外从代码中可以看到如果`哈希盐`为空，就会把`数据库地址`作为`哈希盐`的取值，也可以看出修改这个值并不是一个具有破坏性的操作
![image](https://github.com/1Panel-dev/1Panel/assets/94725606/dcdc8847-73d0-46fd-b725-e1527c0da7cf)

https://github.com/umami-software/umami/discussions/2696#discussioncomment-9175430

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by QYG2297248353** [comment]
> ### 1Panel 版本
> v1.10.6-lts
> 
> ### 请描述您的需求或者改进建议
> 每当 token 泄漏，哈希盐 (随机字符串) 就要进行修改
> 
> 但是参数配置这一项是被锁定的，必须要去 .env 文件里修改，非常不方便
> 
> 已经和作者确认过修改哈希盐不会影响已有数据 另外从代码中可以看到如果`哈希盐`为空，就会把`数据库地址`作为`哈希盐`的取值，也可以看出修改这个值并不是一个具有破坏性的操作 ![image](https://private-user-images.githubusercontent.com/94725606/327032660-dcdc8847-73d0-46fd-b725-e1527c0da7cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTY4ODIsIm5iZiI6MTcyMTI5NjU4MiwicGF0aCI6Ii85NDcyNTYwNi8zMjcwMzI2NjAtZGNkYzg4NDctNzNkMC00NmZkLWI3MjUtZTE1MjdjMGRhN2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA5NTYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNGYyNDIwZWU2YWMyOGE4Yjk2YTM1NGFjMDA2NzcwOWZkYjZjOTVmNzNlMTE4MjFkZTMyZjYzNmEzMDUxOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OS6_ahYqyhYBnqAmIREloA3tH1TCB5vEDAQHVYJ-Y1c)
> 
> [umami-software/umami#2696 (reply in thread)](https://github.com/umami-software/umami/discussions/2696#discussioncomment-9175430)
> 
> ### 请描述你建议的实现方案
> _No response_
> 
> ### 附加信息
> _No response_

第三方应用商店已上线更多可配置项目

https://github.com/QYG2297248353/appstore-1panel

![image](https://github.com/user-attachments/assets/47cd973c-7d71-4c56-87fc-4cedae549c1a)

**Comment by wanghe-fit2cloud** [comment]
已支持。
