### ISSUE TITLE
[FEATURE] 希望添加新版OpenResty对于低版本Docker的支持

### ISSUE THREAD

**Issue by koch3092** [1Panel-dev/1Panel#4823]
### 1Panel 版本

v1.10.6-lts

### 请描述您的需求或者改进建议

1Panel升级成v1.10.6-lts之后，为了试用新版WAF功能，直接按照说明升级了OpenResty 1.21.4.3-2-1-focal，但是如 #4605 相同的问题。但是目前的机器不太方便对Docker版本进行升级，而且也无法正常回退，现在就挺难受的。

### 请描述你建议的实现方案

目前应该有蛮多的系统自带的或者从自带软件仓库安装的Docker版本仍然是20.10.x，建议添加单独的Docker镜像版本进行适配，哪怕是有个镜像可选也好。

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/108793340/fc29a6d9-2aff-45fb-b809-4decd10db628)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境调研一下上述问题的可行性方案。

**Comment by wanghe-fit2cloud** [comment]
近期版本会发布最新版本 OpenResty 镜像，适配低版本 Docker。

**Comment by koch3092** [comment]
请问有个大概的时间吗？

**Comment by wanghe-fit2cloud** [comment]
> 请问有个大概的时间吗？

v1.10.7-lts 版本已经提测，测试通过后就会发布。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
