### ISSUE TITLE
[FEATURE]希望添加1键升级所有docker按钮

### ISSUE THREAD

**Issue by badtot** [1Panel-dev/1Panel#4824]
### 1Panel 版本

v1.10.6-lts

### 请描述您的需求或者改进建议

多docker更新，逐项升级起来太繁琐，希望添加1键升级所有docker按钮

**Comment by ssongliu** [comment]
感谢反馈。
目前可以在应用商店中部署 `watchtower` 应用来实现上述需求。
> 我们中短期内暂无支持上述需求的计划，望理解。
