### ISSUE TITLE
[FEATURE] halo 社区版被升级成专业版

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#4826]
### 1Panel 版本

社区版 v1.10.6-lts

### 请描述您的需求或者改进建议

halo 社区版被强行升级成专业版，能否在升级的时候做个区分，原社区版只升级社区版，原专业版升级专业版。

* 若是为了专业版推广，可提供一键切换到专业版的需求

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，在 1Panel 应用商店中上架的是专业版。如需切换版本，可以在安装时手动修改 compose 文件中 image 信息（已安装应用也可以点击 `参数` 按钮编辑），数据都是兼容的，不影响服务正常使用。
> 后续版本可能会考虑版本切换功能。
