### ISSUE TITLE
[FEATURE]   MySql没有【关闭日志】功能，没有【清除日志】功能。

### ISSUE THREAD

**Issue by hhun** [1Panel-dev/1Panel#483]
### 1Panel 版本

1.0.5

### 请描述您的需求或者改进建议

MySql没有【关闭日志】功能，没有【清除日志】功能。

**Comment by wanghe-fit2cloud** [comment]
MySQL是容器化部署，日志来源于 docker log api，目前版本你可以进入docker 数据目录手动删除日志相关文件。
后续版本我们可能会考虑增加清除日志的功能。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
