### ISSUE TITLE
[FEATURE] 计划任务能否在整点整时执行

### ISSUE THREAD

**Issue by chshouyu** [1Panel-dev/1Panel#4831]
### 1Panel 版本

v1.10.6-lts

### 请描述您的需求或者改进建议

目前计划任务执行时间看起来是在任务修改完之后的一个时间点：

<img width="279" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/1304342/57ad7307-c2d8-452e-87b1-323c4b1400e7">

能否像 crontab 或者群晖一样在一个整数时间执行，这样看起来比较好看、整洁
比如，一个任务设置为每 10 分钟执行一次，期望执行时间是：
```
12:00:00
12:10:00
12:20:00
...
```

如果每小时执行一次，期望执行时间是：
```
12:00:00
13:00:00
14:00:00
...
```
以此类推

另外，希望增加一列显示下次执行时间，比如群晖的

<img width="607" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/1304342/3e0e46eb-350b-4000-a3f5-c4c201c1395c">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by ssongliu** [comment]
可以直接设置每 N 时执行：
<img width="640" alt="image" src="https://github.com/user-attachments/assets/70c1fb31-3930-4bf3-9d16-d2878cbd0cfb" />
