### ISSUE TITLE
[BUG] 无法创建MariaDB11.3.2数据库

### ISSUE THREAD

**Issue by expliyh** [1Panel-dev/1Panel#4832]
### 联系方式

expliyh@outlook.com

### 1Panel 版本

v1.10.6-lts

### 问题描述

新建MariaDB数据库出错：服务内部错误: OCI runtime exec failed: exec failed: unable to start container process: exec: "mysql": executable file not found in $PATH: unknown

进入容器尝试执行 `mysql` 命令提示 `/bin/sh: 1: mysql: not found`，执行 `mariadb` 没有问题

### 重现步骤

新建MariaDB数据库,MariaDB版本为1.3.2

### 相关日志输出

```shell
服务内部错误: OCI runtime exec failed: exec failed: unable to start container process: exec: "mysql": executable file not found in $PATH: unknown
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，在本地环境已经复现上述问题，会在近期版本修复。
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/e257df80-7c80-437f-bc97-4a0e4fba4b46">

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
