### ISSUE TITLE
[FEATURE] 建議修改HTTPS加密算法

### ISSUE THREAD

**Issue by JY-DB** [1Panel-dev/1Panel#4835]
### 1Panel 版本

v1.10.6-lts

### 请描述您的需求或者改进建议

> 算法差異比較：

**原始配置：**
`EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5`

**修改後的配置：**
`ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:!aNULL:!eNULL:!EXPORT:!DSS:!DES:!RC4:!3DES:!MD5:!PSK:!KRB5:!SRP:!CAMELLIA:!SEED`

> 原始配置：

1. 使用了較舊、較不安全的加密算法，包括3DES和RC4，這些算法已被視為不安全，容易受到攻擊。
2. 包含不安全的雜湊函式MD5，MD5已經被廣泛證明存在碰撞攻擊和弱點。
3. 未使用現代的密鑰協商算法，僅依賴於RSA加密，而缺乏Perfect Forward Secrecy (PFS)。
4. 使用了DES算法，DES已經被認為是不安全的，易受到暴力破解。

> 修改後配置：

1. 使用了更現代、更安全的加密套件，如ECDHE 和 DHE，這些套件提供了更好的安全性和性能。
2. 排除了不安全的加密套件，如3DES和RC4，以避免可能的攻擊。
3. 移除了不安全的雜湊函式MD5，以提高安全性。
4. 強調了使用更安全的密鑰協商算法，如AES256-GCM 和 AES128-GCM，這些算法提供了更強的安全性和性能。
5. 指定了現代的加密協定，如SHA384，提供了更高的安全性等級。

> SSL Report v2.3.0：
![image](https://github.com/1Panel-dev/1Panel/assets/54165457/c66a0e86-8991-414d-a21b-f22d8f53114e)

**Comment by zhengkunwang223** [comment]
感谢建议，我们先调研一下

**Comment by JY-DB** [comment]
謝謝您們，辛苦了！

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
