### ISSUE TITLE
希望支持nextcloud全套一键部署

### ISSUE THREAD

**Issue by swysgh** [1Panel-dev/1Panel#4837]
### 1Panel 版本

v1.10.6-Its

### 请描述您的需求或者改进建议

之前用bt的时候nextcloud能够连mysql一起部署，truenas也能一键部署。希望能够支持nextcloud一键部署nextcloud+mysql+redis，如果能够支持ffmpeg和onlyoffice一起就更好了

**Comment by wanghe-fit2cloud** [comment]
目前应用商店中已经支持了 nextcloud 和 onlyoffice 两款应用。
如果需要更复杂的安装模式（这种方式不利于应用的维护），可以考虑通过 `容器` 菜单提供的 `编排` 功能来实现。

> nextcloud 官方提供了 docker-compose.yml 文件。

<img width="1289" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/a2787b09-e981-475a-b688-568c4c8cb90d">
<img width="1286" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/9a4f9cb6-0cd1-4202-8e16-8b5649e03f6b">
