### ISSUE TITLE
建议增加rsyslog和iptables的的配置[FEATURE]

### ISSUE THREAD

**Issue by aiaiduo** [1Panel-dev/1Panel#484]
### 1Panel 版本

1.0.5

### 请描述您的需求或者改进建议

建议在web中增加对rsyslog和iptables的配置

**Comment by wanghe-fit2cloud** [comment]
v1.1.0 版本，我们将支持可视化配置系统防火墙。

**Comment by wanghe-fit2cloud** [comment]
v1.1.0 版本已发布，支持系统防火墙配置管理功能。
