### ISSUE TITLE
[FEATURE]docker日志下载

### ISSUE THREAD

**Issue by YangHaoNing-CN** [1Panel-dev/1Panel#4841]
### 1Panel 版本

1.10.5-lts

### 请描述您的需求或者改进建议

docker容器想下载所有日志时，切换日志选项至全部，需要等待所有日志显示出来才能下载所有的，不然显示到哪里就会只下载到哪里，日志过多会导致chrome oom，望修改

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
