### ISSUE TITLE
[FEATURE] 支持 MySQL Community Server 8.4.0 LTS

### ISSUE THREAD

**Issue by mobeicanyue** [1Panel-dev/1Panel#4844]
### 1Panel 版本

v1.10.5

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/81098819/28a1729e-106e-4abe-8db7-4e4c17ffc5c6)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在本地环境适配成功后推送更新。

**Comment by wanghe-fit2cloud** [comment]
MySQL 8.4.2 已经上架到应用商店。
点击应用商店右上角的【更新应用列表】按钮，等待同步完成后即可安装该版本。
