### ISSUE TITLE
[BUG] 在拦截记录里点击加白, OpenResty直接蹦掉

### ISSUE THREAD

**Issue by jamebal** [1Panel-dev/1Panel#4849]
### 联系方式

jmalx@jmalx.com

### 1Panel 版本

v1.10.6-Its

### 问题描述

在拦截记录里点击加白, 然后OpenResty就蹦了

### 重现步骤

1. 在拦截记录里点击加白
<img width="864" alt="截屏2024-05-04 23 14 08" src="https://github.com/1Panel-dev/1Panel/assets/49510841/d033b75a-b425-47c7-99c4-dc8eb7bad128">

2. 然后在白名单里这两个IP连在一起了, OpenResty就蹦掉了

<img width="1063" alt="截屏2024-05-04 23 14 38" src="https://github.com/1Panel-dev/1Panel/assets/49510841/c2ce0bce-43fc-4df8-8540-d3ad02340eb5">

手动编辑白名单,ip中间加上换行符,才恢复正常,

### 期待的正确结果

还有编辑IP要优化下, 最后的换行可以自动去掉
<img width="517" alt="截屏2024-05-04 23 23 27" src="https://github.com/1Panel-dev/1Panel/assets/49510841/d60c073a-836a-4cc8-8f7d-35bb113aa8c1">
<img width="409" alt="截屏2024-05-04 23 23 43" src="https://github.com/1Panel-dev/1Panel/assets/49510841/8b7bab99-7981-43d0-9f01-a27000ebfe17">

**Comment by zhengkunwang223** [comment]
CDN 兼容会在后面的版本支持

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
