### ISSUE TITLE
关于网站页面新增功能需求

### ISSUE THREAD

**Issue by Dengpr** [1Panel-dev/1Panel#485]
### 1Panel 版本

v1.0.5

### 请描述您的需求或者改进建议

在网站页面新增【操作】功能新增功能
1.新增克隆功能，克隆现有的配置，可大幅度提高管理人员的工作效率。
2.新增配置【文件对比】功能，可以对比修改前与修改后的差异
2.新增配置【文件校验】功能，在配置文件生效前进行测试，防止配置错误导致的页面不可访问。

**Comment by zhengkunwang223** [comment]
感谢建议 我们后续版本会考虑实现  【克隆 】【文件对比】 需求
【文件校验】 功能我们已经默认处理 会在修改 nginx.conf 配置之前先校验 (nginx -t ) 生效之后才会真正写入

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已支持 `文件对比` 功能。
`网站克隆`和`文件校验`这两个功能，我们中短期内应该不会支持，望理解。
