### ISSUE TITLE
[FEATURE] 关于应用商店的应用配置文件，能支持xiaoya这样的镜像吗？

### ISSUE THREAD

**Issue by mia0x75** [1Panel-dev/1Panel#4851]
### 1Panel 版本

1.10.6

### 请描述您的需求或者改进建议

小雅需要3个配置文件，open token/refresh token/temp folder id，保存在/etc/xiaoya下面的三个文件中，应用商店中data.yml可以增加这几个配置项，但是安装时怎么生成对应目录下的文件呢？有没有可能做类似docker-compose.yml中的占位符的替换？

**Comment by zhengkunwang223** [comment]
可以看一下第三方应用商店 
https://github.com/okxlin/appstore

**Comment by mia0x75** [comment]
我是指能不能根据安装页面的参数信息，生成配置文件，xiaoya只是举例。

**Comment by wanghe-fit2cloud** [comment]
> 我是指能不能根据安装页面的参数信息，生成配置文件，xiaoya只是举例。

可以考虑在 `scripts/init.sh` 脚本中实现 `生成对应目录下的文件` 的需求。
> 具体用法可以参考 `OceanBase`

**Comment by mia0x75** [comment]
所以 scripts 目录，init.sh / uninstall.sh 文件名称都是固定的，系统会自动调用，对吗？

**Comment by wanghe-fit2cloud** [comment]
> 所以 scripts 目录，init.sh / uninstall.sh 文件名称都是固定的，系统会自动调用，对吗？

是的，固定的文件名称。
还包括应用升级脚本 `upgrade.sh`
