### ISSUE TITLE
[BUG] 1panel的waf，拦截IP可伪造

### ISSUE THREAD

**Issue by R0A1NG** [1Panel-dev/1Panel#4853]
### 1Panel 版本

v1.10.6-lts

### 问题描述

未使用cdn，本地直连。请求数据包增加X-Forwarded-For伪造IP
![image](https://github.com/1Panel-dev/1Panel/assets/66672984/447d392a-82cf-4643-ab74-3ef117bef2a7)
![image](https://github.com/1Panel-dev/1Panel/assets/66672984/64bd1ee1-0527-48e4-baeb-4b8d86509b69)

### 重现步骤

使用X-Forwarded-For头伪造IP

**Comment by zhengkunwang223** [comment]
当前是从多个 header 头中获取的 ip，后续会支持从自定义 header 获取 ip

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
