### ISSUE TITLE
[BUG]WAF无法新增或修改IP组内容

### ISSUE THREAD

**Issue by itpoo** [1Panel-dev/1Panel#4854]
### 1Panel 版本

v1.10.6-lts

### 问题描述

![screenshot-1714890855269](https://github.com/1Panel-dev/1Panel/assets/165099803/a73b1900-6447-45d7-b5e4-a6787ac1b881)

### 重现步骤

WAF--全局设置--黑名单--IP组--修改或新增

**Comment by zhengkunwang223** [comment]
已复现 后续版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
