### ISSUE TITLE
[FEATURE] 面板样式优化

### ISSUE THREAD

**Issue by realzolo** [1Panel-dev/1Panel#4858]
### 1Panel 版本

v1.10.6-lts

### 请描述您的需求或者改进建议

1. WAF-拦截记录: “域名”列太窄、"URL"列太宽
![image](https://github.com/1Panel-dev/1Panel/assets/63219216/346bfcba-ec14-4d86-8bb9-c1cbaff3f412)
2. 数据分页
大部分列表页面，默认分页应该为20条/页, 10条/页导致页面下半部分空白
![image](https://github.com/1Panel-dev/1Panel/assets/63219216/f1a9cdea-a43e-4895-b8cf-e3b07fbee4c7)
3. WAF模块中的SWITCH组件
![image](https://github.com/1Panel-dev/1Panel/assets/63219216/dfce16bc-3f1a-4c55-bc00-2b1200e83a2b)

**Comment by zhengkunwang223** [comment]
感谢建议，我们后续版本优化一下

**Comment by wanghe-fit2cloud** [comment]
- 1、2 两点会在 v2 大版本重构时优化列表展示；
- SWITCH 组件在 v1.10.12 版本中已统一 https://github.com/1Panel-dev/1Panel/issues/4571

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
