### ISSUE TITLE
关于网站开启安全CC防护,IP封锁后在黑名单展示

### ISSUE THREAD

**Issue by chizp** [1Panel-dev/1Panel#486]
### 1Panel 版本

V1.03

### 请描述您的需求或者改进建议

希望飞致云的产品和研发同学评估下，网站-网站设置-安全，开启CC防护后，某些IP触发该设置后被封锁，封锁的IP可以在IP黑名单查看到。这个功能是否可以加入后续版本。目前本人使用的是腾讯云轻量应用服务器管理工具，同时也在体验1Panl产品

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持该功能。

**Comment by maninhill** [comment]
未来通过第三方WAF集成解决。

**Comment by maninhill** [comment]
https://github.com/1Panel-dev/1Panel/issues/2009
