### ISSUE TITLE
[BUG] php8 安装 ssh2扩展失败

### ISSUE THREAD

**Issue by rex5652** [1Panel-dev/1Panel#4865]
### 1Panel 版本

v1.10.6-Its

### 问题描述

安装运行环境时，php8添加ssh2扩展后无法成功安装。

### 重现步骤

安装PHP环境时手动输入ssh2，在 https://1panel.cn/docs/user_manual/websites/php/#php_1 这里看到是支持的。实际上安装失败

### 相关日志输出

```shell
#11 204.6 ---------- Install ssh2 ----------
#11 204.6 fetch https://mirrors.aliyun.com/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
#11 205.1 fetch https://mirrors.aliyun.com/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
#11 206.2 (1/2) Installing libssh2 (1.11.0-r1)
#11 206.4 (2/2) Installing libssh2-dev (1.11.0-r1)
#11 206.7 OK: 331 MiB in 122 packages
#11 211.2 pecl/ssh2 requires PHP (version >= 7.0.0, version <= 8.0.0), installed version is 8.2.15
#11 211.2 No valid packages found
#11 211.2 install failed
#11 211.2 error: 'ssh2' does not exist
#11 211.2 
#11 211.2 usage: /usr/local/bin/docker-php-ext-enable [options] module-name [module-name ...]
#11 211.2    ie: /usr/local/bin/docker-php-ext-enable gd mysqli
#11 211.2        /usr/local/bin/docker-php-ext-enable pdo pdo_mysql
#11 211.2        /usr/local/bin/docker-php-ext-enable --ini-name 0-apc.ini apcu apc
#11 211.2 
#11 211.2 Possible values for module-name:
#11 211.2 bcmath.so bz2.so gd.so gettext.so imagick.so intl.so memcached.so mysqli.so opcache.so pcntl.so shmop.so soap.so sockets.so sodium.so sysvsem.so
#11 211.2 
#11 211.2 Some of the above modules are already compiled into PHP; please check
#11 211.2 the output of "php -i" to see which modules are already loaded.
```

**Comment by MiderWong** [comment]
错误提示已经说明白了不能安装SSH2的原因了啊：
![错误提示说了安装不上的原因啊](https://github.com/1Panel-dev/1Panel/assets/7487008/59cc2512-9668-4349-a1f5-c6a5946f88ba)

**Comment by rex5652** [comment]
错误日志我看得懂，文档里写8.2支持啊 https://1panel.cn/docs/user_manual/websites/php/#php_1

而且在市场上能安装的最低PHP8也是8.0.30，依然安装不了

#11 216.9 ---------- Install ssh2 ----------
#11 216.9 fetch https://mirrors.aliyun.com/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
#11 217.4 fetch https://mirrors.aliyun.com/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
#11 218.3 (1/2) Installing libssh2 (1.11.0-r0)
#11 218.5 (2/2) Installing libssh2-dev (1.11.0-r0)
#11 218.7 OK: 424 MiB in 136 packages
#11 222.9 pecl/ssh2 requires PHP (version >= 7.0.0, version <= 8.0.0), installed version is 8.0.30
#11 222.9 No valid packages found
#11 222.9 install failed
#11 222.9 error: 'ssh2' does not exist
#11 222.9 
#11 222.9 usage: /usr/local/bin/docker-php-ext-enable [options] module-name [module-name ...]
#11 222.9    ie: /usr/local/bin/docker-php-ext-enable gd mysqli
#11 222.9        /usr/local/bin/docker-php-ext-enable pdo pdo_mysql
#11 222.9        /usr/local/bin/docker-php-ext-enable --ini-name 0-apc.ini apcu apc
#11 222.9 
#11 222.9 Possible values for module-name:
#11 222.9 bcmath.so bz2.so gd.so gettext.so imagick.so intl.so memcached.so mysqli.so opcache.so pcntl.so shmop.so soap.so sockets.so sodium.so sysvsem.so
#11 222.9 
#11 222.9 Some of the above modules are already compiled into PHP; please check
#11 222.9 the output of "php -i" to see which modules are already loaded.

**Comment by MiderWong** [comment]
嗯，我知道，我的意思是php本身是支持的，但是1P提供的docker环境不支持快捷安装`ssh2`扩展。
当前php环境容器支持快捷安装的扩展如下：
![image](https://github.com/1Panel-dev/1Panel/assets/7487008/f193364c-5fc4-4037-8975-e4836001351f)

**Comment by MiderWong** [comment]
虽然官方自带的镜像不支持快捷安装ssh2扩展，但是可以在站点对应的容器中手动安装，具体步骤如下：
### 1、找到站点对应的容器，选择"终端"
![image](https://github.com/1Panel-dev/1Panel/assets/7487008/66f71b6d-ab07-4c84-9853-87ef065a22bd)
### 2、安装`libssh2`及`ssh2`扩展
在“终端”中执行如下命令：
```shell
apk add libssh2-dev
pecl install ssh2
```
> 安装`ssh2`扩展时有输入`prefix`的提示，直接按 **"回车"** 即可。

> 1、安装过程如下图所示：
![image](https://github.com/1Panel-dev/1Panel/assets/7487008/509fa1fb-cb03-4792-bfc0-c17d21e6956b)

> 2、安装成功如下图所示：
![image](https://github.com/1Panel-dev/1Panel/assets/7487008/a3b272fd-7b93-4cdd-9978-d8c89c60c220)

### 3、修改`php.ini`配置
**PS. 以下两种方案任选其一皆可。**
#### 1)、常规
在配置文件`/usr/local/etc/php/php.ini`中新增如下内容：
```shell
[ssh2]
extension=ssh2.so
```
如下图所示:
![image](https://github.com/1Panel-dev/1Panel/assets/7487008/b3a5331a-850b-4324-924b-17bc20a988dc)

#### 2)、其它
> - 在目录`/usr/local/etc/php/conf.d/`中新建`docker-php-ext-ssh2.ini`文件
- 文件内容如下：
 ```
extension=ssh2
 ```
### 4、重启容器
![image](https://github.com/1Panel-dev/1Panel/assets/7487008/6ead0d7e-8b2f-4e4e-bae3-8db1925e8797)

### 5、扩展校验
![image](https://github.com/1Panel-dev/1Panel/assets/7487008/f9d46510-e182-47b8-abd0-b4290a77e520)

### 6、其它
需要注意的是：如果你在操作`站点容器关联的镜像`后选择了`重建PHP应用`选项，会把`当前镜像关联的容器中的自定义操作都初始化`，导致`手动安装的扩展丢失`，所以建议`为有手动修改容器扩展需求的站点建立单独的运行环境(容器)`。容器扩展被初始化如下图所示：
![image](https://github.com/1Panel-dev/1Panel/assets/7487008/63c65168-ecce-4260-99da-a9363820cd7e)
![image](https://github.com/1Panel-dev/1Panel/assets/7487008/24bf1905-71b0-414b-b7b5-b279807a8d8c)

**Comment by rex5652** [comment]
按这个方法已经安装成功

**Comment by wanghe-fit2cloud** [comment]
关于在容器终端手动安装扩展，重建PHP应用会导致扩展丢失的问题，统一汇总到该 issue #4871
