### ISSUE TITLE
[BUG] 计算文件大小的线程没有释放

### ISSUE THREAD

**Issue by wangzhengkun** [1Panel-dev/1Panel#4867]
### 1Panel 版本

v1.10.6-lts

### 问题描述

文件管理中 计算文件夹大小的线程没有释放

### 重现步骤

文件管理中点击计算按钮 观察进场管理中 1panel 进程的线程数量

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
