### ISSUE TITLE
[BUG] 使用 default 作为代号创建网站会有问题

### ISSUE THREAD

**Issue by wangzhengkun** [1Panel-dev/1Panel#4868]
### 1Panel 版本

v1.10.6-lts

### 问题描述

创建网站使用 default 作为代号，删除的时候会删掉默认的 default.conf  配置文件

### 重现步骤

创建网站使用 default 作为代号，然后删除网站

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
