### ISSUE TITLE
[FEATURE]mysql安装的时候增加一个主从复制选择

### ISSUE THREAD

**Issue by 357341051** [1Panel-dev/1Panel#487]
### 1Panel 版本

1.0.5

### 请描述您的需求或者改进建议

mysql安装的时候增加一个主从复制选择，来保证容灾

### 请描述你建议的实现方案

就是在创建一个mysql容器作为从服务器，来复制主mysql的副本，起到容灾，主从复制和主从切换

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本讨论该需求的可行性方案。

**Comment by wanghe-fit2cloud** [comment]
中短期内，我们暂时是不会支持上述需求，望理解。
