### ISSUE TITLE
[FEATURE]PHP运行环境支持`pecl-xxx`扩展快捷安装

### ISSUE THREAD

**Issue by MiderWong** [1Panel-dev/1Panel#4871]
### 1Panel 版本

1.10.6

### 场景
官方自带镜像的支持的快捷扩展有限，让需要安装额外扩展时，需要进入站点对应的镜像进行手动安装，如：#4865 ，但是安装完成之后，如果镜像本身扩展有变更时，会在 **`重建PHP应用`** 时把 **`站点容器初始化`** ，导致 **`站点容器中手动安装的扩展丢失`** 。
### 需求
可以在安装扩展的地方输入`pecl-xxx`进行扩展安装，如：
![image](https://github.com/1Panel-dev/1Panel/assets/7487008/62814d52-3807-4182-b907-75ad136e2088)

### 请描述你建议的实现方案

用户输入扩展名称为`pecl-xxx`时，执行`pecl`安装，并为特殊扩展做依赖环境安装。如`ssh2`扩展需要`libssh2`支撑，需要额外使用`apk add libssh2-dev`安装`libssh2`。
> 1、安装扩展
 ```shell
 pecl install xxx
 ```
> 2、修改`php.ini`配置，启用扩展
```shell
[xxx]
extension=xxx.so
```

### 附加信息

常见支持使用`pecl`安装的扩展如下:
![image](https://github.com/1Panel-dev/1Panel/assets/7487008/9a7640ff-1c78-47b4-8b09-5622166db5c9)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述场景。

**Comment by rex5652** [comment]
到今天还没支持和更新，刚刚升级了一下结果应用重建了。。。又搞了一次

**Comment by zhengkunwang223** [comment]
> 到今天还没支持和更新，刚刚升级了一下结果应用重建了。。。又搞了一次

如果更新，我们会有更新日志，请耐心等待

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
