### ISSUE TITLE
[FEATURE]增加应用和容器的web入口快捷按钮，编排页和编排模板页增加排序功能

### ISSUE THREAD

**Issue by lvxj11** [1Panel-dev/1Panel#4872]
### 1Panel 版本

社区版v1.10.6

### 请描述您的需求或者改进建议

1. 大部分应用或容器都有web管理页，给每个应用和容器添加一个可设置的web入口按钮
2. 目前只有容器页表格有排序功能，希望编排页和编排模板页也可以排序
3. 我在定时任务脚本里对编排有一些操作，导致被操作过的编排不再被面板管理。这个可以改进么？

**Comment by wanghe-fit2cloud** [comment]
`1 和 2` 这两点，我们会在后续版本考虑支持。
`3` 这一点，麻烦再详细描述一下具体操作，我们在本地环境复现一下该问题。

**Comment by zyyfit** [comment]
编排页和编排模板页增加了按照名称排序的功能

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
