### ISSUE TITLE
[BUG]工具箱的进程守护，守护进程名称问题

### ISSUE THREAD

**Issue by iisyw** [1Panel-dev/1Panel#4873]
### 联系方式

yongwei.si@qq.com

### 1Panel 版本

v1.10.6-lts

### 问题描述

创建守护进程时，名称长度1-128位，填写1位时验证不通过

![image](https://github.com/1Panel-dev/1Panel/assets/71065669/30912d5f-bb68-4854-9da8-f227c3e4815a)

### 重现步骤

直接填写就可以复现

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
