### ISSUE TITLE
[BUG]错别字，Cloudflare

### ISSUE THREAD

**Issue by lainbo** [1Panel-dev/1Panel#4875]
### 1Panel 版本

1.10.6

### 问题描述

DNS账户中，有一些地方将Cloudflare写为了CloudFlare，F不应该大写

### 重现步骤

1. 打开证书菜单
2. 点击顶部“DNS账户”
3. 创建账户
4. 观察类型下拉选项
![image](https://github.com/1Panel-dev/1Panel/assets/46062895/81ae0d6c-88ef-4262-8172-f60e3a7f461f)

### 期待的正确结果

写成正确的Cloudflare，f小写

### 附加信息

twitter上Cloudflare员工说的f是小写
![image](https://github.com/1Panel-dev/1Panel/assets/46062895/424443d8-85bc-4113-98cb-7a8a83d252d4)
![image](https://github.com/1Panel-dev/1Panel/assets/46062895/cd069d81-0388-4d28-9c77-4eaa49720178)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
