### ISSUE TITLE
[FEATURE]应用商店添加开源低代码平台-nocobase

### ISSUE THREAD

**Issue by eiloogs** [1Panel-dev/1Panel#4879]
### 1Panel 版本

v1.10.6

### 请描述您的需求或者改进建议

添加开源项目nocobase-低代码平台。
项目地址：https://github.com/nocobase/nocobase

### 请描述你建议的实现方案

version: "3"
networks:
  1panel-network:
      external: true
services:
  app:
    image: nocobase/nocobase:latest
    networks:
      - 1panel-network
    environment:
      - APP_KEY=6z@GkJK67R /*/
      - DB_DIALECT=mysql
      - DB_HOST=1Panel-mysql-****
      - DB_DATABASE=nocobase-****
      - DB_UNDERSCORED=true
      - DB_USER=nocobase-****
      - DB_PASSWORD=*************
      - DB_TIMEZONE=+08:00
    volumes:
      - ./storage:/app/nocobase/storage
    ports:
      - "13000:80"

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，我们主要以项目的 star 数量作为重要的上架指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有约 1 万 star 的开源项目，望理解。

> 可以将上述应用反馈给 [第三方仓库（由社区用户维护）](https://github.com/okxlin/appstore)。
该应用官方也提供了 [docker-compose.yml](https://github.com/nocobase/nocobase/blob/main/docker-compose.yml)，也可以使用 `容器` - `编排` 功能来维护应用。

**Comment by eiloogs** [comment]
目前该项目已经超过11k。

**Comment by chengliang4810** [comment]
目前该项目已经超过12k。

**Comment by wanghe-fit2cloud** [comment]
应用已上架，进入 `应用商店` 列表，点击右上角的【更新应用列表】按钮，待同步完成后即可安装应用。
