### ISSUE TITLE
[BUG]容器里的日志，无限增大问题

### ISSUE THREAD

**Issue by 357341051** [1Panel-dev/1Panel#488]
### 1Panel 版本

1.0.5

### 问题描述

每个容器里的日志，目前没有清理或者删除的功能，又或者可以增加一个计划任务，来批量删除容器内的日志，不然无限增大，不可控

### 重现步骤

容器的日志

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会支持容器日志清理功能。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。支持在容器配置页面开启日志清理功能。
