### ISSUE TITLE
[BUG]WAF拦截记录加白地址管理

### ISSUE THREAD

**Issue by sagezhj** [1Panel-dev/1Panel#4884]
### 联系方式

zhjah@163.com

### 1Panel 版本

v1.10.6-lts

### 问题描述

WAF功能中 ，拦截记录里对IP A加白后，无法找到默认白名单，无法进行查看和删除

### 重现步骤

某IP访问触发任意WAF规则，在拦截记录中新增一条记录，点击该记录加白完成IP加入白名单操作。加入后无法找到已加入白名单IP清单

### 期待的正确结果

加白后按钮显示为移出白名单，在拦截记录上方增加白名单和黑名单按钮，点击查看和管理已拉黑IP和已加白IP
另外该黑白名单是针对网站还是全局也没有说明，只提示是默认黑白名单

**Comment by realzolo** [comment]
拉黑/加白IP后，这个IP会被加到默认的IP组里面。
![image](https://github.com/1Panel-dev/1Panel/assets/63219216/2479ed5e-5ec1-4993-9571-ee12c7d00a21)
虽然目前可以管理拉黑/加白的IP, 但是在拦截记录里面点击拉黑/加白后页面没有及时响应渲染，此处需要优化。
