### ISSUE TITLE
[BUG] MySQL 8.4 升级失败

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#4887]
### 1Panel 版本

社区版 v1.10.6-lts

### 问题描述

升级 MySQL 8.4 失败，日志中提示 `[Server] unknown option '--skip-host-cache'.`

### 重现步骤

手动删除 `my.conf` 中的上述配置用 `host_cache_size = 0` 替换后，
重新启动又提示 `unknown variable ‘default_authentication_plugin=mysql_native_password` 
无法一键升级成功

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，本地环境已经复现该问题，你可以先回滚至 8.2.0 版本。
> 我们已经在正式仓库下架了 8.4.0 版本

**Comment by muhanstudio** [comment]
我也遇见了，这个太要命了啊，直接数据库宕机

**Comment by wanghe-fit2cloud** [comment]
https://github.com/1Panel-dev/1Panel/issues/4844
