### ISSUE TITLE
[BUG] 进程守护-找不到命令

### ISSUE THREAD

**Issue by chuixifeng** [1Panel-dev/1Panel#4888]
### 联系方式

li721693059@163.com

### 1Panel 版本

v1.10.6-lts

### 问题描述

[BUG] 进程守护-找不到命令

### 重现步骤

添加或者编辑，在启动命令栏填入命令后加空格保存查看进程状态为启动失败。

### 期待的正确结果

可以过滤掉空格。

### 附加信息

比较容易复现，期待确认是否为问题进行修复。

**Comment by chuixifeng** [comment]
详细点是命令行的后面加空格。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，问题已复现，如下图：
<img width="1291" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/1207471a-204e-4849-8abf-5e99d431628a">

> 我们会在近期版本优化上述功能。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
