### ISSUE TITLE
[FEATURE]应用商店增加自动部署Windows容器

### ISSUE THREAD

**Issue by Zevo77** [1Panel-dev/1Panel#4889]
### 1Panel 版本

v1.10.6-lts

### 请描述您的需求或者改进建议

应用商店增加自动部署Windows容器，自动部署Windows容器，就是把Windows打包成容器并自动部署到容器中。

### 请描述你建议的实现方案

Windows容器参考：https://zhuanlan.zhihu.com/p/686351917

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们后续版本考虑一下是否上架该应用。

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/4283
