### ISSUE TITLE
[BUG]文件打开很慢

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#489]
### 1Panel 版本

1.0.5

### 问题描述

点击文件这个tab一直在转圈没法加载出来，其他tab打开加载都很快，就文件这个打开很慢

btw,可以支持导航栏（所有链接）右键打开吗？

### 重现步骤

点击文件tab

**Comment by Felmon** [comment]
1
```
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
``` 
2 
```
[2023-04-04 00:00:00] [INFO] website cron job start...  
[2023-04-04 00:00:00] [INFO] website cron job end...  
[2023-04-04 00:00:00] [INFO] ssl renew cron job start...  
[2023-04-04 00:00:00] [INFO] ssl renew cron job end...  
[2023-04-04 10:00:38] [INFO] get current version from [https://resource.fit2cloud.com/1panel/package/stable/v1.0.5/appstore/apps.json]  
``` 
点击完文件tab一直转圈圈没有加载出来，日志里也没记录
f12看了下似乎是这个报错：
![image](https://user-images.githubusercontent.com/19621032/229669379-08afa968-189d-4e79-8bed-71411c863445.png)

**Comment by Felmon** [comment]
@wanghe-fit2cloud 帮忙看下上面的报错，应该怎么优化呀

**Comment by gengxiaoxiaoxin** [comment]
> 1
> 
> ```
> NAME="CentOS Stream"
> VERSION="8"
> ID="centos"
> ID_LIKE="rhel fedora"
> VERSION_ID="8"
> PLATFORM_ID="platform:el8"
> PRETTY_NAME="CentOS Stream 8"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:centos:centos:8"
> HOME_URL="https://centos.org/"
> BUG_REPORT_URL="https://bugzilla.redhat.com/"
> REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
> REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
> ```
> 
> 2
> 
> ```
> [2023-04-04 00:00:00] [INFO] website cron job start...  
> [2023-04-04 00:00:00] [INFO] website cron job end...  
> [2023-04-04 00:00:00] [INFO] ssl renew cron job start...  
> [2023-04-04 00:00:00] [INFO] ssl renew cron job end...  
> [2023-04-04 10:00:38] [INFO] get current version from [https://resource.fit2cloud.com/1panel/package/stable/v1.0.5/appstore/apps.json]  
> ```
> 
> 点击完文件tab一直转圈圈没有加载出来，日志里也没记录 @wanghe-fit2cloud f12看了下似乎是这个报错： ![image](https://user-images.githubusercontent.com/19621032/229669379-08afa968-189d-4e79-8bed-71411c863445.png)
> 
> > 感谢反馈。 1、请用下面的命令查看一下服务器是什么操作系统：
> > ```shell
> > cat /etc/os-release
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 2、麻烦提供一下系统运行日志：面板日志菜单 - 系统日志。

此错误一般与前端缓存相关，请尝试清除缓存后重试。
> 打开A页面，之后部署新的版本，此时从A页面（旧的缓存）继续获取动态模块，会触发这种错误。
- [https://github.com/vitejs/vite/issues/11804](https://github.com/vitejs/vite/issues/11804)
