### ISSUE TITLE
[BUG]首页推荐应用安装状态展示有误

### ISSUE THREAD

**Issue by wxyShine** [1Panel-dev/1Panel#4890]
### 1Panel 版本

专业版： v1.10.7-alpha.2

### 问题描述

已安装应用如图 
![image](https://github.com/1Panel-dev/1Panel/assets/42802152/c159f14d-14a7-407d-9c6a-f758176d117a)

首页推荐应用如图，OpenResty 是已安装这个展示没问题
![image](https://github.com/1Panel-dev/1Panel/assets/42802152/0d640679-ce67-4731-b36d-c04320e46616)

gitea 也是已安装 这里展示的有问题
![image](https://github.com/1Panel-dev/1Panel/assets/42802152/38572bf6-77ba-4dc6-8a8c-3b6d11855097)

### 重现步骤

问题描述

**Comment by wxyShine** [comment]
是因为有些应用可重复安装吗？   不可重复的安装的安装按钮才是灰色

**Comment by zhengkunwang223** [comment]
> 是因为有些应用可重复安装吗？ 不可重复的安装的安装按钮才是灰色

是的
