### ISSUE TITLE
[BUG]`容器` - `编排` 页面跳转到 `主机` - `文件` 列表后，创建文件或文件夹报错

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#4895]
### 1Panel 版本

v1.10.6-lts

### 问题描述

`容器` - `编排` 页面跳转到 `主机` - `文件` 列表后，第一次创建文件提示成功（但是列表中未发现文件）。
再次创建同名文件，则提示文件已存在，如图：
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/f2a10116-5875-4a08-968d-1746eb63f3a3)

经排查发现，系统中没有 `./1panel/docker/compose` 目录。

### 重现步骤

如题。

### 期待的正确结果

在 `容器` - `编排` 页面跳转到 `主机` - `文件` 列表前，判断该目录是否存在。
> 不存在的情况下，先自动创建文件夹。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述功能。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
