### ISSUE TITLE
[FEATURE]需要teamspeak服务端的部署服务

### ISSUE THREAD

**Issue by KurumiRin** [1Panel-dev/1Panel#4896]
### 1Panel 版本

v1.10.6-lts

### 请描述您的需求或者改进建议

需要teamspeak的服务端部署服务。该语音为私人语音服务，在游戏职业赛场和游戏玩家中常用，相比discord等语音平台来说更私密，相对国内各类语音软件来说更简洁更低占用。
官方docker：[teamspeak](https://hub.docker.com/_/teamspeak/tags) 
[ts官网](https://www.teamspeak.com/en/)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑是否上架该应用。

**Comment by lingdiansr** [comment]
支持，很需要

**Comment by cinyan10** [comment]
支持, 需要

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
