### ISSUE TITLE
[FEATURE]waf防火墙批量设置。。防火墙的网站设置自动按字母排序，或者添加查找网站

### ISSUE THREAD

**Issue by Alexzzz2008** [1Panel-dev/1Panel#4899]
### 1Panel 版本

1.10.6

### 请描述您的需求或者改进建议

waf防火墙批量设置。。
在全局里设置 开启或者关闭某项， 后面添加一个设置， 应用到全部网站。
防火墙的网站设置自动按字母排序，或者添加查找网站

### 请描述你建议的实现方案

waf防火墙批量设置。。
在全局里设置 开启或者关闭某项， 后面添加一个设置， 应用到全部网站。
防火墙的网站设置自动按字母排序，或者添加查找网站

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本优化

**Comment by zyyfit** [comment]
目前在 WAF-网站设置 的网站下拉框中增加了输入搜索网站的功能
![图片](https://github.com/1Panel-dev/1Panel/assets/73461316/9e7b9d36-9253-4c56-ae93-7379d85691d4)

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
