### ISSUE TITLE
[BUG] 文件上传成功后再次点击“确认”会重新上传一遍

### ISSUE THREAD

**Issue by WankkoRee** [1Panel-dev/1Panel#490]
### 1Panel 版本

1.0.5

### 问题描述

文件上传完成后，待上传的文件列表会被清空，但是此时点击“确认”依旧会上传一遍上一次的文件列表，推测是前端显示层清空了但是数据层没清空。

![image](https://user-images.githubusercontent.com/21287731/229539888-ca02a378-f5b6-49ac-bff8-97a3c588d1a7.png)

### 重现步骤

上传完成文件后再次点击“确认”按钮即可触发。

**Comment by WankkoRee** [comment]
对于其他一些右侧弹出抽屉的功能，也存在这个问题，比如容器编排功能，编排完成后应当将“确认”改为“完成”或者“关闭”（关闭可能存在歧义）。现在也是点击”确认“后重新编排一遍。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本中我们会持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。

**Comment by WankkoRee** [comment]
> 对于其他一些右侧弹出抽屉的功能，也存在这个问题，比如容器编排功能，编排完成后应当将“确认”改为“完成”或者“关闭”（关闭可能存在歧义）。现在也是点击”确认“后重新编排一遍。

此问题仍然存在，比如编排功能，编排添加成功后，点击"确认"会重新启动编排。

希望改进整个项目中的右侧弹出抽屉的设计逻辑。
