### ISSUE TITLE
[BUG]WAF数据表的的数字显示不全

### ISSUE THREAD

**Issue by fxln0** [1Panel-dev/1Panel#4902]
### 1Panel 版本

1.10.6-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/168253884/ca130064-ea77-43cb-bc6f-7b892b97981c)

![image](https://github.com/1Panel-dev/1Panel/assets/168253884/515db9d4-f44f-4826-a6ae-8ad2a5c49cee)
这个数据表的的数字超过999显示不全

### 重现步骤

登录查看waf

### 期待的正确结果

期待数据表能显示1-100000的量，可以使用中文代表10000000=1千万
![image](https://github.com/1Panel-dev/1Panel/assets/168253884/ca130064-ea77-43cb-bc6f-7b892b97981c)
![image](https://github.com/1Panel-dev/1Panel/assets/168253884/515db9d4-f44f-4826-a6ae-8ad2a5c49cee)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述体验。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
