### ISSUE TITLE
[BUG] 网站管理->单独设置WAF规则

### ISSUE THREAD

**Issue by littlesleep** [1Panel-dev/1Panel#4904]
### 1Panel 版本

1.10.6 lts

### 问题描述

针对单个网站WAF设置更新后没有了。
但是在WAF中又提示在网站里面可以设置，却没有看到。
![image](https://github.com/1Panel-dev/1Panel/assets/8597130/785321fd-41a0-457d-a888-d66ba2ea4f88)
![image](https://github.com/1Panel-dev/1Panel/assets/8597130/acb00bb5-4bce-4979-a940-2b6156079cf3)

### 重现步骤

如问题描述图片所示

### 期待的正确结果

之前版本设置都挺方便的，如果说了可以设置 应该是能找到的。

**Comment by realzolo** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/63219216/3caef3a5-6766-4dc7-a950-5014ca9f6ec3)

**Comment by littlesleep** [comment]
@realzolo  所以意思是：   之前版本免费用的，必须得开专业版的会员对吧？
![image](https://github.com/1Panel-dev/1Panel/assets/8597130/658da3a6-f8ef-4d18-8063-407fec4acbd3)

**Comment by wan92hen** [comment]
> @realzolo 所以意思是： 之前版本免费用的，必须得开专业版的会员对吧？ ![image](https://private-user-images.githubusercontent.com/8597130/328728635-658da3a6-f8ef-4d18-8063-407fec4acbd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzQ4NDksIm5iZiI6MTcxNTEzNDU0OSwicGF0aCI6Ii84NTk3MTMwLzMyODcyODYzNS02NThkYTNhNi1mOGVmLTRkMTgtODA2My00MDdmZWM0YWNiZDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMDIxNTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGU5MDMxM2YwOTc2Yzg2MzY4MTgwZGJkYThhMTQzNDIwOWU4OTQ3OWYzZDEwZmE2ZTg5ZmRiOTg3Y2YyNmZjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.F7MY1nX4qBpPUooJyVeT7LbDsYbDneMzPptMFxbVuLI)

在你截图页面 `全局设置` 右边的 `网站设置` 就是针对单个网站进行 WAF 配置的。
