### ISSUE TITLE
[FEATURE]上传文件希望支持断点续传

### ISSUE THREAD

**Issue by Alexzzz2008** [1Panel-dev/1Panel#4905]
### 1Panel 版本

1.10.6

### 问题描述

站点目录里 上传大压缩包，断了，然后重新开始，希望支持断点续传

### 重现步骤

站点目录里 上传大压缩包，断了，然后重新开始，希望支持断点续传

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复问题 https://github.com/1Panel-dev/1Panel/issues/3709
