### ISSUE TITLE
[BUG]新版本重新安装OpenResty后无法访问WAF设置

### ISSUE THREAD

**Issue by HaoJun0823** [1Panel-dev/1Panel#4908]
### 联系方式

email@haojun0823.xyz

### 1Panel 版本

v1.10.6-lts

### 问题描述

今天重新安装了一下OpenResty，然后发现新安装的青龙面板上传不了python脚本，看了一下是面板拦截了，然后想去调整WAF，结果发现全局设置和网站设置都打不开：
服务内部错误: open /opt/1panel/apps/openresty/OpenResty/1pwaf/data/conf/global.json: no such file or directory

### 重现步骤

直接在新面板里安装一个默认配置的openresty。

### 期待的正确结果

1.能正常访问WAF内容。
2.应用商店的一些App需要调整WAF规则，避免正常业务被通用配置拦截。

### 相关日志输出

```shell
面板访问的是：/opt/1panel/apps/openresty/OpenResty/1pwaf/data/conf/
文件实际路径是：/opt/1panel/apps/openresty/openresty/1pwaf/data/conf/

好像大小写错了？
```

### 附加信息

WAF面板错误截图：
![image](https://github.com/1Panel-dev/1Panel/assets/26188180/8330e7ee-626d-4dcc-bf05-58a88cb77d7b)

服务器文件截图：(/opt/1panel/apps/openresty/openresty/1pwaf/data/conf)
![image](https://github.com/1Panel-dev/1Panel/assets/26188180/7d7eaa27-dc21-40bd-b74e-9d2cf21566d3)

青龙面板前端请求截图：
![ddb88e50ef50c6f29f6da9cfacc080be](https://github.com/1Panel-dev/1Panel/assets/26188180/39fa11a4-c7a3-42be-8806-139fdf5fbd70)

**Comment by zhengkunwang223** [comment]
/opt/1panel/apps/openresty/openresty/1pwaf/data/conf/
第二个 openresty 是你安装应用时候的名称 
截图看一下名称是啥

**Comment by HaoJun0823** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/26188180/1f3eadf7-3419-4e09-a298-09f2121e93ba)
默认安装，没有改过配置和名字。

**Comment by zhengkunwang223** [comment]
你安装的 openresty 是什么版本？

**Comment by HaoJun0823** [comment]
> 你安装的 openresty 是什么版本？

image: 1panel/openresty:1.21.4.3-2-1-focal

**Comment by zhengkunwang223** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/aaf23278-1eaf-44ff-b522-f0dd0f0184f0)
加我企业微信 我远程看一下
