### ISSUE TITLE
[FEATURE]容器编排的整体删除功能

### ISSUE THREAD

**Issue by WankkoRee** [1Panel-dev/1Panel#491]
### 1Panel 版本

1.0.5

### 请描述您的需求或者改进建议

现在编排无法直接删除。

虽然删除编排内所有容器后编排会消失，但是编排的网络依旧会存在，不会自动删除。

希望增加编排的管理功能，如删除、暂停、停止、重启等。

**Comment by WankkoRee** [comment]
另外，不建议学aapanel的删除编排顺带给yml文件给删了的特性。被坑了很多次，建议删除时加个打勾的可选项。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前版本是只有在编排页面直接创建的应用，才支持启、停、删除等操作

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/46734380/229549248-8fc9021e-06f6-452c-8f23-d8f483db7992.png">

**Comment by WankkoRee** [comment]
![image](https://user-images.githubusercontent.com/21287731/229554606-4271334b-310a-4a62-9452-9ae0f1334368.png)

![image](https://user-images.githubusercontent.com/21287731/229554660-f26591e9-4993-4300-9dcb-16213ba57756.png)

那可能在特定环境下存在bug，需要提供哪些信息以供复现呢？

**Comment by wanghe-fit2cloud** [comment]
不能编辑的原因是：来源标签为“本地”。
如果是在编排菜单创建的应用，会打“1Panel”的标签（nexus是我刚创建的应用）：
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/46734380/229555803-b0a8be5c-009e-40fa-abe8-2cd29aa16e37.png">

**Comment by wanghe-fit2cloud** [comment]
docker-compose.yml 或者 .env 是否有手动设置 project name？

**Comment by WankkoRee** [comment]
有设置project name，这会影响判定吗？

```yaml
version: "3"
name: transmission
services:
  ....
```

**Comment by wanghe-fit2cloud** [comment]
> 有设置project name，这会影响判定吗？
> 
> ```yaml
> version: "3"
> name: transmission
> services:
>   ....
> ```

经确认就是这里的问题，您先手动将 yaml 文件中的 name 字段删除了吧，我们后续版本解决这个问题。

**Comment by WankkoRee** [comment]
另外，刚才尝试删除编排后，发现其特性与aapanel一样，都会把相关文件也删除，甚至 1Panel 删除地更彻底，连目录也删了，这是非常有问题的。如果我只是打算关掉容器进行数据迁移，那我随手点个删除岂不是相同目录下的数据映射目录也没了？

**Comment by wanghe-fit2cloud** [comment]
> 另外，刚才尝试删除编排后，发现其特性与aapanel一样，都会把相关文件也删除，甚至 1Panel 删除地更彻底，连目录也删了，这是非常有问题的。如果我只是打算关掉容器进行数据迁移，那我随手点个删除岂不是相同目录下的数据映射目录也没了？

好的，后面版本在删除编排时会增加用户选项。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
