### ISSUE TITLE
[BUG]直接访问特定链接会去到概览页

### ISSUE THREAD

**Issue by wan92hen** [1Panel-dev/1Panel#4912]
### 1Panel 版本

v1.10.6-lts

### 问题描述

#4643 中提到的第一个问题，因为原 issue 内容较多这边单独创建 issue 进行跟踪。
浏览器登录面板后，在新标签页直接打开特定页面的地址会进入到概览页，或者在特定功能页面刷新后会自动跳转到概览页

### 重现步骤

1. 登录面板；
2. 在新标签页访问类似 http://172.16.10.154:14426/databases/mysql 这样的地址
3. 预期的页面一闪而过后自动去掉概览页
4. 进入到功能页面后刷新页面，也会自动跳转到概览页

该问题为出现概率较高的偶现问题，目前还没有找到可以稳定复现的方法。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，目前在浏览器 `无痕模式` 下，稳定复现上述问题，我们会在近期版本修复。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
