### ISSUE TITLE
[FEATURE]文件管理添加收藏功能

### ISSUE THREAD

**Issue by WankkoRee** [1Panel-dev/1Panel#492]
### 1Panel 版本

1.0.5

### 请描述您的需求或者改进建议

可以收藏一些路径和文件，路径的话直接跳转，文件的话直接预览或者编辑或者提示不支持预览。

另外，建议记住上次使用后的路径，每次从根出发挺难受的。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
