### ISSUE TITLE
[FEATURE] 默认提供开源版的 OpenRestry 和集成闭源组件的 OpenRestry

### ISSUE THREAD

**Issue by HenryWu01** [1Panel-dev/1Panel#4920]
### 1Panel 版本

N/A

### 请描述您的需求或者改进建议

目前 1Panel 专业版推出后，应用商店只有自带了闭源组件的 OpenRestry。希望 1Panel 可以维护一个版本的开源 OpenRestry 不带有任何闭源组件。

### 请描述你建议的实现方案

可以从版本名称进行区分，比如官方带有 WAF 组件的后缀有 ``-waf``

**Comment by zhengkunwang223** [comment]
短期内没有此计划
可以通过修改 docker-compose 配置文件来使用官方 openresty
