### ISSUE TITLE
[BUG] 自签证书在火狐浏览器报错 SEC_ERROR_REUSED_ISSUER_AND_SERIAL

### ISSUE THREAD

**Issue by wangzhengkun** [1Panel-dev/1Panel#4927]
### 1Panel 版本

v1.10.6-lts

### 问题描述

1. 在面板安全中指定了用openssl产生的私钥和证书，面板重启后，火狐浏览器出现SEC_ERROR_REUSED_ISSUER_AND_SERIAL 错误，无法继续进入面板

### 重现步骤

在面板安全中指定了用openssl产生的私钥和证书，面板重启后，火狐浏览器出现SEC_ERROR_REUSED_ISSUER_AND_SERIAL 错误，无法继续进入面板

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述功能。

**Comment by ckblau** [comment]
any workaround here?

**Comment by zhengkunwang223** [comment]
> any workaround here?

已经修复了 这两天发新版

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本已发布。
