### ISSUE TITLE
[FEATURE]建议增加网站访问统计功能

### ISSUE THREAD

**Issue by luckylu997** [1Panel-dev/1Panel#4928]
### 1Panel 版本

1.10.5

### 请描述您的需求或者改进建议

网站访问统计功能，最好做成类似之前的cnzz的。这样比较实用

**Comment by zhengkunwang223** [comment]
网站监控报表为专业版功能 预计 6 月份发布

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/408
