### ISSUE TITLE
[FEATURE] 界面优化建议

### ISSUE THREAD

**Issue by ChishFoxcat** [1Panel-dev/1Panel#4929]
### 1Panel 版本

v1.10.6-lts

### WAF 功能建议：
1. 增加独立访客数和独立IP数统计，并添加到请求趋势上，添加可更换查看选项
![image](https://github.com/1Panel-dev/1Panel/assets/76027184/5db92efb-37f1-4583-b289-4db1a34a15bc)
![image](https://github.com/1Panel-dev/1Panel/assets/76027184/361b83fe-b317-409b-802b-02bfe473a286)
2. 增加访问量地图
![image](https://github.com/1Panel-dev/1Panel/assets/76027184/5157ae1a-ed32-4d98-857c-1dc87ab464e8)
3. 增加客户端统计（饼图）：
    - 系统
    - 浏览器
4. 增加响应码统计（饼图）
5. 增加访问域名次数统计（横向条形图）
6. 可更改统计时间范围
### 概览界面建议：
- 增加图标使其明显
![image](https://github.com/1Panel-dev/1Panel/assets/76027184/d8467d6c-2d0f-461e-b1c4-d97b445c5f86)
- 推荐应用区可修改为 `WAF 概览` 或 `某一个软件的快捷跳转`
### 界面设置建议：
- 可修改主题色
### 界面功能选项优化建议：
- `主机` 选项中的 `终端` 迁移到主功能上
- `主机` 选项中的 `SSH管理` 迁移到工具箱中，会话选项可参考 `Fail2ban`的 IP 黑白名单选项，登录日志可以整合到日志审查中的登录日志
![image](https://github.com/1Panel-dev/1Panel/assets/76027184/6f65ec7a-0e96-4f6a-b17e-996bb1d93ad1)
![image](https://github.com/1Panel-dev/1Panel/assets/76027184/a96a311f-16c6-4af2-92ab-d00e1c325c9e)
- `高级功能` 选项中 `WAF` 和 `网站防篡改` 迁移到 `网站` 选项中
- `高级功能` 选项中 `GPU 监控` 迁移到 `主机` 选项中
- `高级功能` 选项中 `界面设置` 迁移到 `面板设置` 中

### 附加信息

- 仅个人建议
- 不知我的建议是否合理

**Comment by zhengkunwang223** [comment]
感谢建议
你说的这些统计项目 我们会放在网站监控报表中实现
WAF 等高级功能我们是为了不影响社区版用户 并且方便我们功能实现 所以统一到一个菜单中

**Comment by wanghe-fit2cloud** [comment]
网站监控 issue https://github.com/1Panel-dev/1Panel/issues/408
