### ISSUE TITLE
[FEATURE]反向代理支持同站多条代理功能

### ISSUE THREAD

**Issue by WankkoRee** [1Panel-dev/1Panel#493]
### 1Panel 版本

1.0.5

### 请描述您的需求或者改进建议

在同个`server`内，可以根据`location`设置不同url走不同代理，当前的一个网站只能设置一个代理的功能无法满足实际需求。

~~如果采取同站多代理的话，`proxy_`开头的配置都应该放在`location`内，而不是现在的大部分直接在`server`内。~~ 仔细想了下，现在的`proxy_`开头的配置放在`server`内应该没啥问题。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by zhengkunwang223** [comment]
> ### 1Panel 版本
> 1.0.5
> 
> ### 请描述您的需求或者改进建议
> 在同个`server`内，可以根据`location`设置不同url走不同代理，当前的一个网站只能设置一个代理的功能无法满足实际需求。
> 
> ~如果采取同站多代理的话，`proxy_`开头的配置都应该放在`location`内，而不是现在的大部分直接在`server`内。~ 仔细想了下，现在的`proxy_`开头的配置放在`server`内应该没啥问题。
> 
> ### 请描述你建议的实现方案
> _No response_
> 
> ### 附加信息
> _No response_

在群里吗？在群里的话加一下我 有问题问一下

**Comment by WankkoRee** [comment]
> 在群里吗？在群里的话加一下我 有问题问一下

刚加5群

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
