### ISSUE TITLE
[FEATURE] 1pctl 和 1panel 二进制路径固定，不要使用软链接

### ISSUE THREAD

**Issue by wojiushixiaobai** [1Panel-dev/1Panel#4930]
### 1Panel 版本

All

### 请描述您的需求或者改进建议

代码里面调用这两个文件使用两种不同的路径
- `/usr/bin/1pctl`
- `/usr/local/bin/1pctl`
- `/usr/bin/1panel`
- `/usr/local/bin/1panel`

其中一个是软链接，一个是实际二进制文件，考虑在某个版本之后固定路径。

比如统一使用 `/usr/local/bin`
如果我们后续需要发行仓库包，deb rpm 等，二进制存储目录可以和其他应用一样，存储在 `/usr/bin/` 和 `/lib/systemd/system/`，
以便于区分用户的安装方式。

涉及到其他应用的，可以使用相对路径，比如 
- `/usr/sbin/ufw` --> `ufw`
- `/usr/sbin/firewalld` --> `firewalld`

### 请描述你建议的实现方案

如上

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在近期版本统一上述二进制路径。

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
