### ISSUE TITLE
[FEATURE] 应用商店新增 RocketMQ

### ISSUE THREAD

**Issue by VxRain** [1Panel-dev/1Panel#4931]
### 1Panel 版本

v1.10.6-lts

### 请描述您的需求或者改进建议

希望应用商店上架 `RocketMQ`。
虽然也能自己部署，但是感觉 `RocketMQ` 用的场景还是挺多的，应用商店可以考虑上架一下。
目前应用商店里只有 `RabbitMQ` 和 `Kafka`。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
最好是能提供一下你本地部署的 `docker-compose.yml` 文件，我们后续版本适配后就推送到正式仓库。

**Comment by VxRain** [comment]
> 感谢反馈。 最好是能提供一下你本地部署的 `docker-compose.yml` 文件，我们后续版本适配后就推送到正式仓库。

官方有对应的 Docker 仓库：https://github.com/apache/rocketmq-docker
这个是 RocketMQ 5.x 的 `docker-compose` 文件：https://github.com/apache/rocketmq-docker/blob/master/templates/docker-compose/rmq5-docker-compose.yml

**Comment by wanghe-fit2cloud** [comment]
已推送至正式仓库。
> 在应用商店菜单中，点击右上角的【更新应用列表】按钮。

**Comment by ChewJ404** [comment]
> 已推送至正式仓库。
> 
> > 在应用商店菜单中，点击右上角的【更新应用列表】按钮。

@wanghe-fit2cloud   RocketMQ  的  Docker Compose 有点问题 broker启动顺序有时候比  namesrv 快导致 启动失败 ，最好还是  broker  depends_on: - namesrv  下  不然开机自启大概率 遇到部分容器启动失败 的情况

**Comment by wanghe-fit2cloud** [comment]
> > 已推送至正式仓库。
> > > 在应用商店菜单中，点击右上角的【更新应用列表】按钮。
> 
> @wanghe-fit2cloud RocketMQ 的 Docker Compose 有点问题 broker启动顺序有时候比 namesrv 快导致 启动失败 ，最好还是 broker depends_on: - namesrv 下 不然开机自启大概率 遇到部分容器启动失败 的情况

建议直接向应用提交 Pull Request，感谢！
https://github.com/1Panel-dev/appstore/pulls
