### ISSUE TITLE
[BUG]升级v1.10.6-lts后，计划任务rename存在问题

### ISSUE THREAD

**Issue by wen-gg** [1Panel-dev/1Panel#4933]
### 1Panel 版本

v1.10.6-lts

### 问题描述

计划任务rename命令存在问题

### 重现步骤

无

**Comment by wen-gg** [comment]
![微信截图_20240509105900](https://github.com/1Panel-dev/1Panel/assets/17865026/d59a4e55-9329-4f02-90ba-27b1be31a159)

**Comment by ssongliu** [comment]
感谢反馈，手动执行这条命令可行吗？
麻烦贴一下计划任务脚本内容

**Comment by wen-gg** [comment]
按照提示我使用mv是可以的，rename应该是你们语法写错了，任务脚本就是备份目录

**Comment by wen-gg** [comment]
> 感谢反馈，手动执行这条命令可行吗？ 麻烦贴一下计划任务脚本内容

按照提示我使用mv是可以的，rename应该是你们语法写错了，任务脚本就是任务类型中的备份目录

**Comment by ssongliu** [comment]
明白了，是执行的备份目录的计划任务，这里确实用到了 rename 命令，可以尝试手动执行一下错误信息里 rename /mnt/share... 那条命令

**Comment by wen-gg** [comment]
> 明白了，是执行的备份目录的计划任务，这里确实用到了 rename 命令，可以尝试手动执行一下错误信息里 rename /mnt/share... 那条命令

手动执行错误里面的命令不行，还是报错（rename语法使用错误）。不过rename换成mv就可以

**Comment by wen-gg** [comment]
> 明白了，是执行的备份目录的计划任务，这里确实用到了 rename 命令，可以尝试手动执行一下错误信息里 rename /mnt/share... 那条命令

这个还是有问题哦，我备份的目录是挂载硬盘
![微信截图_20240511092215](https://github.com/1Panel-dev/1Panel/assets/17865026/9b27df77-fbea-427d-90a3-cb2da2fa1e10)

**Comment by ssongliu** [comment]
先看看为啥这个文件一直正在使用中吧。

**Comment by wen-gg** [comment]
> 先看看为啥这个文件一直正在使用中吧。

自动备份才创建的文件，根本就没使用。找到问题了，备份目录改为系统内的其他目录可以正常备份，如果备份目录是单独挂载硬盘中的目录就备份不了。不过之前版本是可以备份的，几天前升级就不行了
