### ISSUE TITLE
[FEATURE] 应用商店的data.yml参数增加多行文本类型

### ISSUE THREAD

**Issue by mia0x75** [1Panel-dev/1Panel#4937]
### 1Panel 版本

1.10.6

### 请描述您的需求或者改进建议

在做小雅应用的是否，发现目前 type 字段，只有单行文本，且有长度限制，阿里云盘的Open Token有几百个字符。

### 请描述你建议的实现方案

增加一个多行文本输入，可以输入长字符串或者多行字符串

**Comment by okxlin** [comment]
不设置rule规则，用text类型就好了

https://github.com/okxlin/appstore/tree/localApps/apps/xiaoya

**Comment by wanghe-fit2cloud** [comment]
> 不设置rule规则，用text类型就好了
> 
> https://github.com/okxlin/appstore/tree/localApps/apps/xiaoya

如下图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/e2195eb4-7476-40d7-86a7-69ded3785704)

![image](https://github.com/1Panel-dev/1Panel/assets/46734380/03ebb35b-1e8c-4531-8c59-1239c5033ad8)
