### ISSUE TITLE
[FEATURE]一些命令执行的进度展示

### ISSUE THREAD

**Issue by WankkoRee** [1Panel-dev/1Panel#494]
### 1Panel 版本

1.0.5

### 请描述您的需求或者改进建议

如编排功能，当前显示是直接从”开始“阶段直接到”完成“阶段，并没有中间的”过程“阶段，如果因为网络带宽等原因，将会显示很久的等待结果中的状态。

![image](https://user-images.githubusercontent.com/21287731/229553424-34c97c89-fdae-4a62-a7ec-9051208cd07b.png)

希望通过WebSocket或者轮询的方式展示命令执行的过程，如download进度或者build进度等等。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
可以将 1Panel 升级只最新版本。
