### ISSUE TITLE
[FEATURE]建议加一个阿里云盘的备份账号

### ISSUE THREAD

**Issue by WSXYT** [1Panel-dev/1Panel#4943]
### 1Panel 版本

v1.10.6-lts

### 请描述您的需求或者改进建议

建议加一个阿里云盘的备份账号，实现备份到阿里网盘

### 请描述你建议的实现方案

注册阿里云盘官方开发者（这样还能推广自己，因为一般会在详情页展示）（www.alipan.com/developer）然后通过阿里云盘官方api（www.yuque.com/aliyundrive/zpfszx/btw0tw?spm=aliyundrive.developer.0.0.67314f48TTWjFD）实现备份到资源盘或者备份到备份盘，这很实用，而且并不需要费很多力气甚至违法去使用非官方的api，我相信会有很多人需要的，没有发送可能只是暂时的（提一嘴：我用官方教程使用alist的时候，备份数据库成功了，但是备份网页并不成功，也许是因为alist上传大文件会报错）

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
重复 issue https://github.com/1Panel-dev/1Panel/issues/3393
