### ISSUE TITLE
無中國手機號如何購買1panel專業版

### ISSUE THREAD

**Issue by oaxtudio** [1Panel-dev/1Panel#4945]
### 1Panel 版本

latest

### 请描述您的需求或者改进建议

我是海外用戶，沒有手機號、也無法獲取優惠，請問有提供海外用戶專用的購買方式嗎？

### 请描述你建议的实现方案

無法手機號簡訊認證（改採信箱認證之類的）

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前 1Panel 官方只支持通过手机号码认证的方式来购买专业版许可证。
> 支付环节也只支持 `微信` 和 `支付宝` 支付。
