### ISSUE TITLE
[FEATURE] 计划任务增加网站日志切割

### ISSUE THREAD

**Issue by Mystery00** [1Panel-dev/1Panel#495]
### 1Panel 版本

1.0.5

### 请描述您的需求或者改进建议

计划任务里面增加一种任务类型
能够在每天凌晨的时候归档前一天的openresty日志，存放到日期对应的目录中，同时创建一个新的日志文件存放当天的日志。
保留份数应用到openresty日志保存天数上。

### 请描述你建议的实现方案

通过shell脚本进行切割与自动清理

### 附加信息

界面上建议也加一个大小限制，超过多少的直接报错，不去读文件了，避免因为文件过大导致机器短时间卡住（面板会504，同时整个openresty也会卡住，影响具体的请求）

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持该需求。

**Comment by Mystery00** [comment]
附问题截图：

![企业微信截图_2c545c0b-16a8-4dd6-a831-1d48697bca10](https://user-images.githubusercontent.com/19162205/230636995-99e6be2a-ea95-4849-ad4b-7416051577f5.png)


![企业微信截图_6d9cf11c-5d53-4b04-87a4-e05a48305792](https://user-images.githubusercontent.com/19162205/230637013-9baacce9-4167-4fc1-beb4-73cac3b173a7.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期发布的版本中完成上述内容的优化。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
