### ISSUE TITLE
[FEATURE] 希望进程守护可以直接跳转到目录.

### ISSUE THREAD

**Issue by maxbad** [1Panel-dev/1Panel#4953]
### 1Panel 版本

v1.10.6-lts

### 请描述您的需求或者改进建议

希望可以直接跳转,如图:
![image](https://github.com/1Panel-dev/1Panel/assets/37558406/fff399cc-ed4d-45aa-a261-c793819a4b61)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by maxbad** [comment]
麻烦再多加一个备注,谢谢啦,.

**Comment by wanghe-fit2cloud** [comment]
> 麻烦再多加一个备注,谢谢啦,.

收到，届时一起支持。

**Comment by wanghe-fit2cloud** [comment]
> 麻烦再多加一个备注,谢谢啦,.

收到，麻烦再新开一个 issue。
> 跳转功能已经实现，会在近期推送更新。

**Comment by wanghe-fit2cloud** [comment]
v1.10.8-lts 版本已发布。
