### ISSUE TITLE
[BUG] 应用备份提示 record not found

### ISSUE THREAD

**Issue by hhhguany** [1Panel-dev/1Panel#4955]
### 1Panel 版本

v1.10.7-Its

### 问题描述

最近看我的备份所有应用任务一直失败，通过定位，是备份 JumpServer 出现了错误。

当我执行单独备份 JumpServer 时，会提示 “record not found”。

另外关于【计划任务】，备份所有应用功能也有一个实现逻辑上的问题，就是备份所有应用时，目前是按照顺序，一个一个应用备份的。当 JumpServer 备份失败后，排在其之前备份的所有应用都成功备份了，但是排在其之后的应用又不会继续执行备份，这容易造成误解（我之前就一直没有发现备份任务失败了，因为常用的应用可能排序比较靠前，都备份成功了）。

因此，建议按照错误逻辑，要不把已经备份成功的应用数据回滚；要不就是忽略备份错误的应用，继续把其他应用备份完，最后提示有哪些没有备份成功。

### 重现步骤

【应用商店】-【已安装】-【JumpServer】-【备份】-【备份】

### 相关日志输出

```shell
[2024-05-10 16:00:16] [DEBUG] tar --warning=no-file-changed --ignore-failed-read -zcf /opt/1panel/backup/app/jumpserver/jumpserver/jumpserver_20240510160016epz66/app.tar.gz  --exclude *.sock -C /opt/1panel/apps/jumpserver jumpserver
```

**Comment by wojiushixiaobai** [comment]
尽量关闭 JumpServer  应用后备份，JumpServer 用到特权，可能是部分文件被占用导致无法完成备份。

**Comment by hhhguany** [comment]
> 尽量关闭 JumpServer 应用后备份，JumpServer 用到特权，可能是部分文件被占用导致无法完成备份。

当我停止 JumpServer 应用后，【备份】按钮时灰色的，无法执行备份。这是正常的吗？或者是通过其他方式备份？

![image](https://github.com/1Panel-dev/1Panel/assets/12447542/26dc7c1c-959e-445a-a883-5ffb88257d0c)

**Comment by wojiushixiaobai** [comment]
我们先尝试复现下运行时无法备份的这个现象，稍后我们如果复现了我们看看问题

**Comment by hhhguany** [comment]
> 我们先尝试复现下运行时无法备份的这个现象，稍后我们如果复现了我们看看问题

好的

**Comment by wanghe-fit2cloud** [comment]
> 当我停止 JumpServer 应用后，【备份】按钮时灰色的，无法执行备份。这是正常的吗？或者是通过其他方式备份？

是的，只有应用状态为 `已启动` 时才支持备份操作。

**Comment by hhhguany** [comment]
还有一点建议，就是【计划任务】中，备份应支持多选应用进行备份。目前只提供备份所有应用和备份单个应用的选项。当特定应用备份存在问题的时候，且应用特别多的情况时，不太方便一个一个去创建应用备份任务。

**Comment by hhhguany** [comment]
请问这个问题有解决吗？

我目前有两个需求：
1. 我需要定时运行备份所有应用的计划任务。
2. 由于JumpServer应用内有生产数据，且能正常使用，故不想卸载该应用。

但是由于JumpServer应用备份失败，会导致备份所有应用时，备份进行到一半就失败了，有部分应用始终无法进行备份。同时由于应用数量过多，手动逐一配置每个应用的备份任务过于复杂。

因此希望官方在确定 JumpServer 备份 bug 前，能够提供优化备份所有应用的流程（#3720）。谢谢！

**Comment by wanghe-fit2cloud** [comment]
计划在 v1.10.13 版本支持，具体进度跟踪 #3720
