### ISSUE TITLE
[BUG]应用更新后没有反应，更新界面无变化。

### ISSUE THREAD

**Issue by itpoo** [1Panel-dev/1Panel#4958]
### 1Panel 版本

v1.10.7-lts

### 问题描述

更新应用界面，点击更新/升级后未提示更新成功，且应用还处于未更新提示状态。

![image](https://github.com/1Panel-dev/1Panel/assets/165099803/53da9ab6-0378-4fbb-b41b-105bdc52f8d2)

### 重现步骤

应用商店-可升级-升级

**Comment by zhengkunwang223** [comment]
可以看一下系统日志 升级失败的应用会回滚的

**Comment by itpoo** [comment]
#4986 已找出原因
