### ISSUE TITLE
[BUG]面板设置删除快照实际文件没有被删除

### ISSUE THREAD

**Issue by ayoulx** [1Panel-dev/1Panel#4962]
### 联系方式

youink@foxmail.com

### 1Panel 版本

v1.10.7-lts专业版

### 问题描述

#面板设置-快照-删除快照，实际没有删除文件
![日志查看](https://github.com/1Panel-dev/1Panel/assets/54100440/e4a7f6bf-12f2-407c-9a77-2eb445f686f4)
日志显示删除文件操作
![文件管理界面](https://github.com/1Panel-dev/1Panel/assets/54100440/c24ed13c-2584-4395-9046-c98561562e76)
快照文件依然存在

### 重现步骤

面板设置-快照-删除快照

**Comment by ssongliu** [comment]
感谢反馈，暂时都没有删除快照文件，后续考虑在删除快照时增加是否删除原文件的选项。

**Comment by ayoulx** [comment]
> 感谢反馈，暂时都没有删除快照文件，后续考虑在删除快照时增加是否删除原文件的选项。

好吧，我还以为是bug

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
