### ISSUE TITLE
希望添加容器镜像更新的提示

### ISSUE THREAD

**Issue by li-peifeng** [1Panel-dev/1Panel#4963]
### 1Panel 版本

1.10.7

### 请描述您的需求或者改进建议

希望添加容器镜像更新的提示，这样能方便更新容器镜像

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，目前我们暂无计划支持该需求，感谢理解。

> 当前版本，可以考虑部署应用商店中上架的 `watchtower ` 应用。

**Comment by heartacker** [comment]
很需要，
