### ISSUE TITLE
[BUG] 网站管理,网站域名多端口情况,导航链接错误,应该是域名端口访问形式.

### ISSUE THREAD

**Issue by AtlantisDe** [1Panel-dev/1Panel#4964]
### 1Panel 版本

v1.10.7-lts

### [BUG] 网站管理,网站域名多端口情况,导航链接错误,应该是域名端口访问形式.

![image](https://github.com/1Panel-dev/1Panel/assets/39150678/fab53aa6-eb6f-44df-9239-6c6a4f8cb768)

### 重现步骤

----

### 期待的正确结果

域名:端口
IP:端口
如果有ssl 应该加上判断.

**Comment by wanghe-fit2cloud** [comment]
提供一下 1Panel 版本。
> 在开发测试环境未能复现上述问题。

**Comment by AtlantisDe** [comment]
> 提供一下 1Panel 版本。
> 
> > 在开发测试环境未能复现上述问题。

上面不写了吗? 老版本 v1.10.7-lts  新版 都存在这个问题.

**Comment by zhengkunwang223** [comment]
您好 经过验证 是 https 模式下跳转有问题
后续版本优化

**Comment by zhengkunwang223** [comment]
由于我们暂时还没有标记添加的 域名：端口 中是否为 https 
所以跳转的时候 只能跳转到 http:域名:端口

**Comment by AtlantisDe** [comment]
等你们发布新版了我验证下 是否修复了 我在关闭这个 issue

**Comment by AtlantisDe** [comment]
已经 检查还是有小问题. 如果能修下更好了.
https 判断下 端口如果包含443 默认就不要添加端口
否者 https 是其它端口 还是 保持  https://:端口 形式 进行导航.
#4998

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
