### ISSUE TITLE
[FEATURE]网站设置密码访问建议

### ISSUE THREAD

**Issue by bushanhuo** [1Panel-dev/1Panel#4966]
### 1Panel 版本

v1.10.7-lts

### 请描述您的需求或者改进建议

设置网站密码访问的时候，不能指定某个路径下。
比如说我想设置在访问/admin 这个路径才需要密码，就无法设置。
只能默认全站密码访问。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
上述需求统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4855
