### ISSUE TITLE
[FEATURE]添加或者更改配置的时候，element-ui的DRAWER能不能加入esc关闭窗口=false?

### ISSUE THREAD

**Issue by neatstudio** [1Panel-dev/1Panel#4968]
### 1Panel 版本

最新版

### 请描述您的需求或者改进建议

每次辛辛苦苦在线改了半天，一个不小心，按了esc，里面编辑的内容就全没了。。。太痛苦了

### 请描述你建议的实现方案

要求不高，只要加入：close-on-press-escape=false 就行啦！！！

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在近期版本优化上述体验。

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
