### ISSUE TITLE
[FEATURE]几点刚需需求

### ISSUE THREAD

**Issue by cyril-cheng** [1Panel-dev/1Panel#497]
### 1Panel 版本

1.0.5

### 请描述您的需求或者改进建议

1、端口自助管理
2、备份数据到OSS（OSS挂载）
3、PM2管理器

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1、麻烦详细讲一下端口自助管理的具体使用场景哈
2、目前已经支持在面板设置中添加备份账号（目前已支持 s3、oss等）。
计划任务创建数据库、网站等备份，创建快照等是支持备份到备份账号的
3、是要支持 nodejs 运行环境吗？

**Comment by FW27623** [comment]
> 感谢反馈。 1、麻烦详细讲一下端口自助管理的具体使用场景哈 2、目前已经支持在面板设置中添加备份账号（目前已支持 s3、oss等）。 计划任务创建数据库、网站等备份，创建快照等是支持备份到备份账号的 3、是要支持 nodejs 运行环境吗？

可以支持OneDrive备份吗

**Comment by cyril-cheng** [comment]
> 
感谢回复
1、nginx的stream代理，负载均衡等等可能会用到非常用端口
2、我在面板设置-备份账号标签下找到了第三方备份选项，目前oss只支持阿里云，s3只支持亚马逊，还有许多其他厂商有待支持，比如腾讯云，Azure，Oricle Cloud等等
3、是的nodejs环境，目前有项目使用nodejs环境和PM2管理器

**Comment by wanghe-fit2cloud** [comment]
理论上只要云厂商兼容 S3 协议，应该就可以用现有的 S3 云存储来备份，可以尝试一下。
#227

**Comment by cyril-cheng** [comment]
> 理论上只要云厂商兼容 S3 协议，应该就可以用现有的 S3 云存储来备份，可以尝试一下。 #227

好的，我试试，谢谢

**Comment by 445022889** [comment]
PM2管理器 确实需求，没有的话 有点难受

**Comment by wanghe-fit2cloud** [comment]
> PM2管理器 确实需求，没有的话 有点难受

可以，后面版本支持。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本也已经支持了创建 Node.js 运行环境。
