### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by dark2star** [1Panel-dev/1Panel#4970]
### 1Panel 版本

v1.10.7-lts

### 请描述您的需求或者改进建议

你们制作的应用docker镜像大小普遍偏大，例如：1panel/openresty 镜像610MB，即便使用Ubuntu这样的比较大的底包制作都不应该这么大，这种现象普遍存在于大多数镜像

### 请描述你建议的实现方案

建议使用Alpine制作小体积镜像，减少镜像构建过程中不需要的文件占用

**Comment by wanghe-fit2cloud** [comment]
1Panel 自己维护的 OpenResty 镜像是在官方镜像的基础之上增加了 WAF 相关内容，比原镜像大了 100MB 左右。
> OpenResty 官方镜像：openresty/openresty:1.21.4.3-2-focal（选择该版本的原因是同时支持 amd64、arm64、s390x三种架构）

至于 PHP 运行环境的基础镜像，目前使用的就是 alpine 作为基础镜像。
