### ISSUE TITLE
[FEATURE]开启CDN后网站日志只显示CDN回源IP

### ISSUE THREAD

**Issue by bushanhuo** [1Panel-dev/1Panel#4971]
### 1Panel 版本

v1.10.7-lts

### 请描述您的需求或者改进建议

如题，开启CDN以后网站日志就变成下面这样的内容：
163.181.146.187 - - [10/May/2024:14:20:12 +0000] "GET /admin/?m=admin HTTP/1.1" 200 1895 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

前面的163.181.146.187就是阿里云CDN的回源IP，而并非访问用户IP。

### 请描述你建议的实现方案

真实的用户IP都在这个HTTP头中：
set_real_ip_from 0.0.0.0/0;
real_ip_header X-Forwarded-For;

1Panel可以先获取一下存不存在这个HTTP头信息，如果存在则在网站日志中显示real ip。
如果HTTP头中不存在上面那些参数，则就按照标准信息返回。

就类似BT一样。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述建议。

**Comment by zhengkunwang223** [comment]
<img width="830" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/31820853/bd534c25-bd75-4e89-8ff1-a4b191afe657">
可以增加一下这个配置 保存之后访问 网站然后查看 每行日志的最后的 IP 是不是真实 IP
如果是 可以修改 OpenResty 配置文件 
<img width="1105" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/31820853/9567bb4c-3d83-4979-813c-f2c6006a6267">
log_format 来调整日志中真实 IP 的位置

**Comment by bushanhuo** [comment]
> <img alt="image" width="830" src="https://private-user-images.githubusercontent.com/31820853/329630439-bd534c25-bd75-4e89-8ff1-a4b191afe657.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNTQ4MDIsIm5iZiI6MTcxNTM1NDUwMiwicGF0aCI6Ii8zMTgyMDg1My8zMjk2MzA0MzktYmQ1MzRjMjUtYmQ3NS00ZTg5LThmZjEtYTRiMTkxYWZlNjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDE1MjE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiOWJhOGYxYmZmY2Y5MjdiNzY3ZGFiZThlNjM1MTE1NmY0NzgwNmIxZWZiYzk4ZmViMTNlM2M0MTdmY2I1ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P7c_QPMUYU6N_pdypbuUKioIctpTcrAXf5tDqUF3N-Q"> 可以增加一下这个配置 保存之后访问 网站然后查看 每行日志的最后的 IP 是不是真实 IP 如果是 可以修改 OpenResty 配置文件 <img alt="image" width="1105" src="https://private-user-images.githubusercontent.com/31820853/329630859-9567bb4c-3d83-4979-813c-f2c6006a6267.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNTQ4MDIsIm5iZiI6MTcxNTM1NDUwMiwicGF0aCI6Ii8zMTgyMDg1My8zMjk2MzA4NTktOTU2N2JiNGMtM2Q4My00OTc5LTgxM2MtZjJjNjAwNmE2MjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDE1MjE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMzgwNTM3YmQ2ZDY0MDE5MWFkMTllZjUxOTEwOWZjMTY3ZTUwZDk1NmNmYTU0MTBiYjg0Y2Y2YTY5OGJlMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VJPxMtbiuF1y-IF79USho-2gExfFsKUS4U_wcGh4nAk"> log_format 来调整日志中真实 IP 的位置

嗯，主要是想像BT一样。
存在CDN就获取真实IP，然后日志就显示真实的IP。
不存在真实IP，就按照标准格式来显示。
这样弄也行，就是不符合正常阅读习惯。
如果把真实IP改到前面，没开CDN的站点就直接获取不到IP了，很麻烦。
不如1Panel内置给改了。

**Comment by zhengkunwang223** [comment]
能否贴一下 宝塔 的设置页面

**Comment by bushanhuo** [comment]
> 能否贴一下 宝塔 的设置页面

宝塔里面，只需要修改一下Nginx设置，在Nginx中加上这样一段代码就可以实现：
![2](https://github.com/1Panel-dev/1Panel/assets/43093839/09bd489c-ca56-4551-946f-0496b3f3afa3)

这样就是开启CDN以后会自动显示真实的IP地址。
如果网站没有开启CDN也不会显示空白信息，显示的还是用户的访问IP地址。

**Comment by zhengkunwang223** [comment]
> > 能否贴一下 宝塔 的设置页面
> 
> 宝塔里面，只需要修改一下Nginx设置，在Nginx中加上这样一段代码就可以实现： ![2](https://private-user-images.githubusercontent.com/43093839/329948918-09bd489c-ca56-4551-946f-0496b3f3afa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDY2ODAsIm5iZiI6MTcxNTYwNjM4MCwicGF0aCI6Ii80MzA5MzgzOS8zMjk5NDg5MTgtMDliZDQ4OWMtY2E1Ni00NTUxLTk0NmYtMDQ5NmIzZjNhZmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEzMTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MWNkNDMyNWE2NGQ3MTNiNDA5ZmU1ZGQ3M2VmMzM5MGIzYmMxOTcwYmExNGM0MzJjZDc0YzQ4ZDY4NTZkOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.12dJnbbOjqondaYcc13bK1IvQPpbNCklaJ8G_Eeycz0)
> 
> 这样就是开启CDN以后会自动显示真实的IP地址。 如果网站没有开启CDN也不会显示空白信息，显示的还是用户的访问IP地址。

在 1Panel 中增加这段配置 IP 会空白是吗

**Comment by bushanhuo** [comment]
> > > 能否贴一下 宝塔 的设置页面
> > 
> > 
> > 宝塔里面，只需要修改一下Nginx设置，在Nginx中加上这样一段代码就可以实现： ![2](https://private-user-images.githubusercontent.com/43093839/329948918-09bd489c-ca56-4551-946f-0496b3f3afa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDY2ODAsIm5iZiI6MTcxNTYwNjM4MCwicGF0aCI6Ii80MzA5MzgzOS8zMjk5NDg5MTgtMDliZDQ4OWMtY2E1Ni00NTUxLTk0NmYtMDQ5NmIzZjNhZmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEzMTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MWNkNDMyNWE2NGQ3MTNiNDA5ZmU1ZGQ3M2VmMzM5MGIzYmMxOTcwYmExNGM0MzJjZDc0YzQ4ZDY4NTZkOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.12dJnbbOjqondaYcc13bK1IvQPpbNCklaJ8G_Eeycz0)
> > 这样就是开启CDN以后会自动显示真实的IP地址。 如果网站没有开启CDN也不会显示空白信息，显示的还是用户的访问IP地址。
> 
> 在 1Panel 中增加这段配置 IP 会空白是吗

不会是空白，但是有个问题就是。
每次更新或者重载，再或者更新1P的时候会导致配置丢失。
如果能内置一个开启功能会方便很多，不用每次手动加进去。
手动加有点麻烦。

**Comment by zhengkunwang223** [comment]
> > > > 能否贴一下 宝塔 的设置页面
> > > 
> > > 
> > > 宝塔里面，只需要修改一下Nginx设置，在Nginx中加上这样一段代码就可以实现： ![2](https://private-user-images.githubusercontent.com/43093839/329948918-09bd489c-ca56-4551-946f-0496b3f3afa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDY2ODAsIm5iZiI6MTcxNTYwNjM4MCwicGF0aCI6Ii80MzA5MzgzOS8zMjk5NDg5MTgtMDliZDQ4OWMtY2E1Ni00NTUxLTk0NmYtMDQ5NmIzZjNhZmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEzMTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MWNkNDMyNWE2NGQ3MTNiNDA5ZmU1ZGQ3M2VmMzM5MGIzYmMxOTcwYmExNGM0MzJjZDc0YzQ4ZDY4NTZkOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.12dJnbbOjqondaYcc13bK1IvQPpbNCklaJ8G_Eeycz0)
> > > 这样就是开启CDN以后会自动显示真实的IP地址。 如果网站没有开启CDN也不会显示空白信息，显示的还是用户的访问IP地址。
> > 
> > 
> > 在 1Panel 中增加这段配置 IP 会空白是吗
> 
> 不会是空白，但是有个问题就是。 每次更新或者重载，再或者更新1P的时候会导致配置丢失。 如果能内置一个开启功能会方便很多，不用每次手动加进去。 手动加有点麻烦。

不同 CDN 的配置可能不一样，所以暂时还是需要手动配置的
