### ISSUE TITLE
关于个人使用中累计的问题/优化建议集中的一个Issue

### ISSUE THREAD

**Issue by Muska-Ami** [1Panel-dev/1Panel#4972]
### 1Panel 版本

社区版 v1.10.7-lts

### 请描述您的需求或者改进建议

1. WAF 我发现1Panel最新版本已经彻底移除了社区版的所有WAF功能 尽管做高级版WAF不错 但是请不要完全移除社区版的WAF，毕竟谁都不想在没有需求的情况下安装雷池那种体积庞大的WAF软件
2. 证书申请
  - #2617 可以考虑支持自定义ACME证书申请地址 我这里有向DN42的ACME申请证书的需求
  - 我发现1Panel一直有一个BUG，就是DNS账户中，Cloudflare账户并不能使用Global API令牌，建议适配或提示不支持，以免产生歧义
3. 请实现 #614 ，我们很需要这个功能，主要是计划任务是否成功这里 不可能每天都上去看
4. 部分界面回车按键问题 这个问题其实没什么大影响 主要是部分界面回车会导致页面刷新，比如应用商店确认删除会下意识的按Enter确认，而事实上Enter会导致整个页面刷新，而不是确定的效果，请修复这个问题
5. 移动端适配 目前移动端显示又开始错位了，最大的问题是文件管理页面和应用商店页面，希望官方在更新的同时记得适配移动端，我用1Panel很大一部分原因也是有移动端适配
6. 自动获取跳转地址 目前累死phpMyAdmin这种一键打开的按钮都要手动设置跳转地址，而我经常需要从不同的几个设备地址访问1Panel，所以希望能直接通过获取当前浏览器访问地址的host字段自动跳转，而不是需要手动指定
7. 更好的终端 目前移动端上终端无法发送组合键或者Esc等按键，导致使用vim等部分程序无法正常保存退出等问题，请添加发送组合键的选项
8. 应用商店应用状态 我发现手动启动停止容器并不会对应用商店的应用状态产生影响，这会导致一定程度上的误导，希望能修复这个问题
9. 支持修改应用安装目录 目前都是安装在1Panel目录底下的apps文件夹，虽然可以用ln创建软连接来解决这个问题，但是每次都要手动ln不觉得很麻烦吗，希望能添加安装位置的选项
10. 自签证书申请页面超时问题 这个主要是在一些性能较弱的设备上操作容易发生，由于创建证书机构和签发证书所需的时间长于设定的请求超时时间，这会导致出现超时的意外报错，事实上稍等一会又创建好了，希望能够优化
11. 保留官方openresty的支持 这个主要是在玩客云等armv7之类的架构上会产生问题，由于1Panel自行构建的镜像并不支持armv7等架构，导致无法正常安装Openresty，这个问题在论坛应该有人提过了，使用官方镜像会因为找不到WAF的lua脚本而失败，请修复这个问题
12. 使用service命令 目前应该都是在使用systemctl命令来管理服务，推荐使用service命令替代systemctl命令，可以增强对一部分设备的支持，比如我使用Docker在OpenWrt设备中部署了1Panel，但是由于OpenWrt并不使用systemd管理服务，所以没有systemctl命令，面板部分操作需要重启必须手动重启容器才可以生效 而几乎所有的发行版上都有service命令，不必担心这个问题（这样做也可以使得1Panel兼容Alpine系统）

**Comment by zhengkunwang223** [comment]
1. WAF 在社区版中也有 也能使用大多数功能
2.  1. 可以放开 2. 已经有提示了
3. 纳入规划了 预计 2.0 
4. 这个我们复现一下
5. 移动端适配一直在做 如果哪里错误或者不合适 请提交Issue
6. 这个暂时改不了
8. 我们做了同步的 所以停止容器 然后再打开应用商店 状态是会改变的 如果没有 请再提一个 issue 详细描述一下
9. 这个我们看一下
10. 新版本有跳过 DNS 验证的选项，可以缩短时间。至于性能 1Panel 推荐最低 1c 1g , 低于此配置的优化短期内不会做
11. 这个可以自己修改 docker-compose.yaml 文件 和 conf 配置文件来解决，我们暂时不会考虑适配 v7

**Comment by Muska-Ami** [comment]
社区版WAF是内置到镜像里了? 使用最新版的社区版+OpenResty并不会产生 `waf` 文件夹，也没有看到网站配置里面有WAF选项，旧版是有的

至于 6. 怎么会暂时无法实现呢 只需要在前端获取当前域即可 <https://www.runoob.com/jsref/prop-doc-domain.html>

以及期望关于 11. 和 12. 的更多信息

**Comment by zhengkunwang223** [comment]
> 社区版WAF是内置到镜像里了? 使用最新版的社区版+OpenResty并不会产生 `waf` 文件夹，也没有看到网站配置里面有WAF选项，旧版是有的
> 
> 至于 6. 怎么会暂时无法实现呢 只需要在前端获取当前域即可 https://www.runoob.com/jsref/prop-doc-domain.html
> 
> 以及期望关于 11. 和 12. 的更多信息

社区版 WAF 换了位置 换到了高级功能-WAF 中
11. 我们暂时没有精力去维护 armv7 版本的 Openresty, 你可以使用官方的 armv7
