### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by dark2star** [1Panel-dev/1Panel#4974]
### 1Panel 版本

v1.10.7-lts

### 请描述您的需求或者改进建议

OpenResty镜像不可以灵活定制，比如增加webdav模块，已看到issue中有多人反馈，宝塔面板中是允许自己编译安装的从而添加想要的模块，比如流媒体、webdav这些模块，我现在遇到的问题是OpenResty容器无法直接配置webdav，同样也无法反代webdav服务，同样把之前宝塔面板中的反代配置抄过来也不行，需抓包才能确定什么问题

### 请描述你建议的实现方案

建议可灵活配置增减模块

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本持续优化

**Comment by wanghe-fit2cloud** [comment]
上述需求的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4861
