### ISSUE TITLE
[FEATURE]网站访问控制功能建议

### ISSUE THREAD

**Issue by bushanhuo** [1Panel-dev/1Panel#4975]
### 1Panel 版本

v1.10.7-lts

### 请描述您的需求或者改进建议

现在有一个密码访问，前面有提到要求加上指定路径才触发密码访问。
能不能再加上一个IP访问，设置访问某个指定路径时，只有允许的IP才能访问。
这样可以绝对安全的方式防破解。

注意事项：
这样弄的话，需要考虑到开启CDN的问题。
需要默认把CDN的回源节点设置白名单，然后识别用户的真实IP。

### 请描述你建议的实现方案

CoudFlare的所有回源节点：
https://www.cloudflare.com/ips-v4
https://www.cloudflare.com/ips-v6

阿里云需要给客服发送工单获取：
https://help.aliyun.com/zh/cdn/product-overview/pop-distribution

腾讯云获取回源节点：
https://cloud.tencent.com/document/product/228/57844

华为云应该也是需要给客服提交工单的。

然后可以加一个开启CDN模式，那些用小厂CDN的用户自己把CDN回源节点IP加进去就完事了。

**Comment by zhengkunwang223** [comment]
这个可以在我们的专业版 WAF 中 使用  自定义规则实现
