### ISSUE TITLE
[BUG]上传的证书状态显示错误

### ISSUE THREAD

**Issue by wxip** [1Panel-dev/1Panel#4976]
### 1Panel 版本

v1.10.7-lts

### 问题描述

上传的证书状态显示错误
![image](https://github.com/1Panel-dev/1Panel/assets/25923931/8f3a159b-9335-4e98-9954-0e14f359d160)

### 重现步骤

证书-上传证书

**Comment by zhengkunwang223** [comment]
已复现 后续版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.10.8-lts 版本已发布。
