### ISSUE TITLE
[FEATURE] 容器管理页面可否将已启动的容器排在前面

### ISSUE THREAD

**Issue by hexWars** [1Panel-dev/1Panel#498]
### 1Panel 版本

1.0.5.2

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/61684793/229746637-ed9310eb-d339-493d-bcef-2c0da60e9cec.png)

可以考虑将所有的已启动的容器默认置于前面

且可以增加排序方式，按照创建时间排序，按照容器大小排序，活跃程度排序等

我简单看了一下，没有类似的issue(如果有,I am sorry)

感谢你们的开源贡献

**Comment by Felmon** [comment]
借楼：
1 增加容器的端口显示，单个容器的管理操作（目前是勾选后操作），夜间模式的启动/暂停操作按钮颜色区分不明显）
2 增加文件的排序方式，及默认排序（目前默认是字母排序但是文件夹混在一起而不是文件夹和文件分别排序）

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持该需求。

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
