### ISSUE TITLE
[FEATURE]目录权限修改时若选择"同时修改子文件属性"时，同时修改"子文件所有者:组信息"

### ISSUE THREAD

**Issue by MiderWong** [1Panel-dev/1Panel#4981]
### 1Panel 版本

1.10.7-lts

### 问题描述

修改目录权限时，选中了"同时修改子文件属性"，只会修改"子文件的权限值"，不会修改"子文件的所有者:组信息"。

#### 1、文件夹及子文件权限属性，如下图
![文件夹权限](https://github.com/1Panel-dev/1Panel/assets/7487008/4f215a0c-ea48-45d8-ac6b-0d2fceac3a26)
![子文件权限](https://github.com/1Panel-dev/1Panel/assets/7487008/e1e2f218-786c-4808-9daa-ea47196379ed)
#### 2、在文件夹目录操作权限修改，并选中"同时修改子文件属性"，如下图
![目录及子文件权限修改](https://github.com/1Panel-dev/1Panel/assets/7487008/c60bd4ba-cebc-43f1-a6e6-b6711e1b8edd)
#### 3、修改后的文件夹及子文件权限属性，如下图
![文件夹权限](https://github.com/1Panel-dev/1Panel/assets/7487008/4ebcb341-b5e5-41d5-a0aa-b81227ea8701)
![子文件权限](https://github.com/1Panel-dev/1Panel/assets/7487008/60799c2f-2135-470e-b248-2837fe29f311)

### 期待的正确结果

修改文件夹权限时，若选中"同时修改子文件属性"，在修改子文件权限值时**同时修改子文件所有者:组信息** ，如下图：
![修改子文件所有者:组信息](https://github.com/1Panel-dev/1Panel/assets/7487008/057add8e-4ebf-4ba7-864d-5436d170b96c)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，目前版本可以使用列表顶部的 `权限` 按钮来实现上述功能，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/03df7875-774c-4552-8a35-3041d5f0c84b)

> 近期版本会在行内 `权限` 按钮中增加上述功能。

**Comment by MiderWong** [comment]
很👍

**Comment by wanghe-fit2cloud** [comment]
先打开该 issue 了，等下个版本发布并测试通过后再来关闭该 issue。

**Comment by wanghe-fit2cloud** [comment]
v1.10.8-lts 版本已发布。
