### ISSUE TITLE
[FEATURE] WAF无法获取真实IP

### ISSUE THREAD

**Issue by R0A1NG** [1Panel-dev/1Panel#4988]
### 1Panel 版本

v1.10.7

### 请描述您的需求或者改进建议

cdn传来的真实IP在X-Forwarded-For中，而值是这种1.1.1.1, x.x.x.x, 127.0.0.1

有真实IP在倒数第二个或倒数第三个的情况。
现在没法获取到真实IP，而是只获取了第一个IP作为真实IP

真实IP只在X-Forwarded-For字段中，所以只能指定X-Forwarded-For

需要能获取X-Forwarded-For指定位置的IP
例如：获取X-Forwarded-For倒数第一个IP
获取X-Forwarded-For倒数第二个IP
··················

**Comment by zhengkunwang223** [comment]
感谢建议，后续版本支持

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
