### ISSUE TITLE
[FEATURE] 面板容器服务显示端口

### ISSUE THREAD

**Issue by hexWars** [1Panel-dev/1Panel#499]
### 1Panel 版本

v1.0.5.2

### 请描述您的需求或者改进建议

我想着，在容器面板增加一列，用来显示容器的端口，这样子更方便易用，如果可以的话将其设置为超链接，点击直接跳转更好

搜索了好像没有类似的issue(如果有,I am sorry)

感谢你们的开源贡献

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持该需求。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
