### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by dylansealive** [1Panel-dev/1Panel#4990]
### 1Panel 版本

v1.10.6

### 请描述您的需求或者改进建议

终端界面连接远程服务器的时候可以提供管理远程服务器文件功能

### 请描述你建议的实现方案

JumpServer 中的文件管理功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在 v2.x 版本支持多主机管理功能，会通过多主机的形式来支持 `主机` - `文件管理` 功能。

**Comment by wanghe-fit2cloud** [comment]
相关问题的讨论，会议汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/2692
