### ISSUE TITLE
希望后续能上架 Stable Diffusion WebUI

### ISSUE THREAD

**Issue by fundgao** [1Panel-dev/1Panel#4995]
### 1Panel 版本

v1.10.7-lts

### 请描述您的需求或者改进建议

AI大模型MaxKB已经用上了，Ollama也安装玩上了。
希望后续能上架 Stable Diffusion WebUI。
1Panel 真是牛逼的开源项目。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地调研一下该应用的容器化部署方案。

**Comment by wanghe-fit2cloud** [comment]
重复问题 https://github.com/1Panel-dev/1Panel/issues/4251
