### ISSUE TITLE
openresty反向代理delete方法返回405

### ISSUE THREAD

**Issue by dark2star** [1Panel-dev/1Panel#4996]
### 1Panel 版本

v1.10.7-lts

### 问题描述

openresty反向代理delete方法返回405
<img width="842" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/9655248/c21d60a3-3f3c-4798-9152-7c6ca67c7c78">

### 重现步骤

使用openresty反向代理后端webdav服务，服务经过测试可以正常使用，但使用openresty delete方法返回405，openresty容器日志："DELETE xxxxx HTTP/1.1" 405 18 "-" "Proxyscotch/1.1"

### 期待的正确结果

可以正常代理后端webdav服务，支持delete等方法

### 相关日志输出

```shell
"DELETE xxxxx HTTP/1.1" 405 18 "-" "Proxyscotch/1.1"
```

**Comment by zhengkunwang223** [comment]
看一下是不是被 WAF 影响了
先关闭 WAF 试试

**Comment by dark2star** [comment]
> 看一下是不是被 WAF 影响了 先关闭 WAF 试试

确实是waf的问题，我用的是社区版，一直以为waf不可以用，已经关掉了该站点的waf，可以正常使用了，另外即便是在waf里允许delete方法也不行

**Comment by zhengkunwang223** [comment]
> > 看一下是不是被 WAF 影响了 先关闭 WAF 试试
> 
> 确实是waf的问题，我用的是社区版，一直以为waf不可以用，已经关掉了该站点的waf，可以正常使用了，另外即便是在waf里允许delete方法也不行

感谢反馈 我们排查一下

**Comment by zhengkunwang223** [comment]
已更新 请升级到最新版再试试

**Comment by dark2star** [comment]
> 已更新 请升级到最新版再试试

[12/Jun/2024:11:56:26 +0800] "DELETE /xxxx/2_1_b4f0a26eb9c24485aef1c0f458bec48f.json HTTP/1.1" 405 18 "-" "VV/1.0"

看起来没修好这个bug
