### ISSUE TITLE
希望能优化应用商店部分接口的响应速度

### ISSUE THREAD

**Issue by jamebal** [1Panel-dev/1Panel#5008]
### 1Panel 版本

v1.10.7-lts

### 问题描述

在多个虚拟机里面安装1panel测试发现: 
1. 系统里docker容器越多(多于30个),`/v1/apps/installed/check`, `/v1/apps/installed/search`这两个接口就慢, 不总是很慢, 有时几百毫秒,有时几秒, 慢的程度基本和docker容器数量成正比
2. 系统里docker容器少(少于10个), `/v1/apps/installed/check`, `/v1/apps/installed/search`这两个接口就很快, 总是很快, 200毫秒以内
3. 以上测试来自同一物理机里的多个虚拟机测试, 虚拟机配置相同, 所以能排除网络和硬件配置性能的问题

### 重现步骤

不是用1panel安装多个docker容器

### 期待的正确结果

希望能优化这两个接口的响应速度

**Comment by MiderWong** [comment]
我猜测是网络并发响应原因，因为[Search、Check]是向服务器请求[AppList、UpdateList]，我添加了本地第三方仓库，一次[Search]要[10s+]。

你提到这个，其实我一直想提一个[FEATURE]，我看大家都没提过：
**[FEATURE]应用商店页面，默认展示[已安装]标签，标签顺序改为[已安装]、[可升级]、[全部(市场)]**
这样修改之后，不必每次打开[应用商店]时必须先等待[应用商店服务器有响应之后才能操作]，如下图:
> ![image](https://github.com/1Panel-dev/1Panel/assets/7487008/12ab3255-faca-4759-8e4e-fef8f843f82d)

**Comment by jamebal** [comment]
我没有添加第三方库, 而且我抓包了, Search、Check并没有向外部请求

**Comment by MiderWong** [comment]
逻辑好像是下面这样：
1、先同步到本地，后续做Sync和Update的时候向服务器做版本号请求及对比
2、同步本地之后是查数据库

我的这个很慢原因是：
1、我用了第三方库，大概几百个App
2、MySQL用的是Docker部署的

**Comment by jamebal** [comment]
`/v1/apps/installed/search`该接口24小时检测结果, 时快时慢,没发现规律
<img width="908" alt="截屏2024-05-16 09 26 05" src="https://github.com/1Panel-dev/1Panel/assets/49510841/240a0926-ae62-4d5f-87c3-4cf8807477ec">

**Comment by jamebal** [comment]
### 同一个物理下两个配置相同的虚拟机对`/v1/apps/installed/search`的监控, 其中192.168.0.192有54个容器, 192.168.0.104有3个容器

<img width="955" alt="截屏2024-05-17 10 32 26" src="https://github.com/1Panel-dev/1Panel/assets/49510841/1c2353d7-215a-46dd-9e7e-76c2472efa62">
<img width="957" alt="截屏2024-05-17 10 33 00" src="https://github.com/1Panel-dev/1Panel/assets/49510841/374904c9-34e9-4997-92e9-29a3945dc17a">

**Comment by jamebal** [comment]
### 同一个物理下三个配置相同的虚拟机对/v1/apps/installed/search的监控, 容器数量不同对其响应时间的影响
<img width="968" alt="截屏2024-05-20 09 15 00" src="https://github.com/1Panel-dev/1Panel/assets/49510841/3916588c-0e87-4a38-9491-8e98ad336327">
<img width="976" alt="截屏2024-05-20 09 15 17" src="https://github.com/1Panel-dev/1Panel/assets/49510841/465f6e32-b82a-46fb-b823-4d9dcebfbfb0">
<img width="964" alt="截屏2024-05-20 09 15 37" src="https://github.com/1Panel-dev/1Panel/assets/49510841/3d364796-9ea1-495a-bdb5-402cb469da6d">

**Comment by zhengkunwang223** [comment]
🙏感谢反馈，应该是调用 docker SDK 获取容器状态这个方法导致的，后续版本考虑优化成两个接口

**Comment by jamebal** [comment]
好的谢谢

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
