### ISSUE TITLE
[FEATURE] Docker容器挂载建议

### ISSUE THREAD

**Issue by pinetrick** [1Panel-dev/1Panel#5009]
### 1Panel 版本

v1.10.7-lts

### 请描述您的需求或者改进建议

当将网站部署到Docker容器时，建议仅挂载当前网站所需的特定目录，而非整个sites目录。这样一来，即使某个网站被攻击，也不会波及到其他网站，避免了连带影响。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们会在 v2.0 版本中考虑上述建议。

**Comment by wanghe-fit2cloud** [comment]
重复问题 https://github.com/1Panel-dev/1Panel/issues/1240

**Comment by pinetrick** [comment]
麻烦问一下 有ETA 什么时候能出2.0版本吗
