### ISSUE TITLE
[FEATURE]增加modsecurity coreruleset支持

### ISSUE THREAD

**Issue by ossplus** [1Panel-dev/1Panel#501]
### 1Panel 版本

1.0.5

### 请描述您的需求或者改进建议

希望web服务能集成 https://github.com/SpiderLabs/ModSecurity modsecurity模块， 并且防火墙模块能预置 coreruleset https://github.com/coreruleset/coreruleset
可以在waf处加coreruleset开关

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本中我们会讨论并验证该方案。

**Comment by ezjbc** [comment]
https://waf-ce.chaitin.cn/
也可以考虑集成社区版雷池WAF

**Comment by maninhill** [comment]
未来通过集成第三方 WAF 解决。

**Comment by maninhill** [comment]
https://github.com/1Panel-dev/1Panel/issues/2009
