### ISSUE TITLE
[FEATURE] 建议添加磁盘配额管理功能

### ISSUE THREAD

**Issue by pinetrick** [1Panel-dev/1Panel#5010]
### 1Panel 版本

v1.10.7-lts

### 请描述您的需求或者改进建议

为某个目录或网站添加磁盘配额管理功能。该功能可以限制指定目录或网站的磁盘使用量，确保系统资源的合理分配和使用。
需求:

定义磁盘配额:
能够为特定目录或网站设置磁盘使用限额。
支持以MB、GB等单位定义限额。

监控和报警:
实时监控目录或网站的磁盘使用情况。
当使用量接近或超出设定限额时，发送警报通知。

管理界面:
提供友好的用户界面，方便管理员查看和管理磁盘配额。
支持按目录或网站查看当前的磁盘使用情况及限额设置。

日志记录:
记录磁盘配额的设定、修改和使用情况。
提供详细的日志报告，帮助管理员审计和分析磁盘使用情况。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
磁盘相关需求的讨论，统一汇总到该 issue #1852

**Comment by wanghe-fit2cloud** [comment]
通知、告警相关需求的讨论，统一汇总到该 issue #614
