### ISSUE TITLE
[FEATURE]应用商店增加 Affine 

### ISSUE THREAD

**Issue by Jengro777** [1Panel-dev/1Panel#5017]
### 1Panel 版本

1.10.7

### 请描述您的需求或者改进建议

https://docs.affine.pro/docs/self-host-affine

### 附加信息

AFFiNE 是一个包含完全合并的文档、白板和数据库的工作区。
完成更多的事情，你的创造力不会单调。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上架上述应用。

**Comment by mia0x75** [comment]
@Avey777 你本地搭建的时候，会不会老是提醒你要转到云账号，就是官方网站账号

**Comment by wanghe-fit2cloud** [comment]
已上架应用商店。

**Comment by leioukupo** [comment]
> 已上架应用商店。

66月份说要解决affine安装时的临时容器问题，现在解决了吗？
