### ISSUE TITLE
[BUG]Debian12 安装mysql8.2报错，安装就没有成功

### ISSUE THREAD

**Issue by Coflys** [1Panel-dev/1Panel#5019]
### 1Panel 版本

v1.10.7-lts

### 问题描述

服务内部错误: stderr: Container mysql Restarting Error response from daemon: Cannot restart container 6d9aa9103ca1019cf62a8c3cb224edafcb78ea02def6f91a9e51ddf4f5255ac4: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/etc/localtime" to rootfs at "/etc/localtime": mount /etc/localtime:/etc/localtime (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

### 重现步骤

我这边一安装就是这个错误。。

**Comment by Coflys** [comment]
经过测试，删除 /etc/localtime 就正常了，说明映射有问题
![image](https://github.com/1Panel-dev/1Panel/assets/4775343/49463d3c-42e6-48be-afa7-4ae0bd3aedfe)

**Comment by wanghe-fit2cloud** [comment]
是因为 1Panel 服务器上没有改文件导致的。
可以在安装应用时编辑 compose 删除该文件等挂载，也可以通过软链等方式在 1Panel 服务器中添加 localtime 文件。

**Comment by Coflys** [comment]
请问你这边说的改文件是什么意思，需要执行某个命令修改吗
在服务器上我看到有这个文件的，是下面截图这样吗
![image](https://github.com/1Panel-dev/1Panel/assets/4775343/f8ade9be-d58a-4052-b4b6-1d3265fb4295)

**Comment by wanghe-fit2cloud** [comment]
> 请问你这边说的改文件是什么意思，需要执行某个命令修改吗
> 在服务器上我看到有这个文件的，是下面截图这样吗

是一个指向具体时区的文件，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/bd633c6c-157a-4750-8379-153332c66fcd)

**Comment by Coflys** [comment]
添加localtime软连接
![image](https://github.com/1Panel-dev/1Panel/assets/4775343/dba91857-b3b4-408a-85cc-768849c7897c)
结果
![image](https://github.com/1Panel-dev/1Panel/assets/4775343/fe662e08-f420-47dc-b72d-549a3c4e5541)
修改mysql映射
![image](https://github.com/1Panel-dev/1Panel/assets/4775343/f5a74d3a-7277-415f-8d3e-94228c2eca3c)

感谢大佬解惑
