### ISSUE TITLE
[FEATURE] 网站反代的集中化

### ISSUE THREAD

**Issue by yfdoor** [1Panel-dev/1Panel#502]
### 1Panel 版本

1.0.5

### 请描述您的需求或者改进建议

比如我有 a.xxx.com; b.xxx.com; c.xxx.com 分别指向不同的应用，现在的方法是先把这些域名分别做好解析，然后在面板中依次添加，需要添加三次反代。
其实他们都共享相同的主域名，证书也是一套，是否可以做成这样  *.xxx.com 里面分别设置不同三级域名指向不同的应用，网站记录里就只有一条，不知是否可行。

再者，是否可以添加域名后加路径方式的反代设置？例如主域名 xxx.com, 可以分别反代  xxx.com/aaa; xxx.com/bbb 到不同的应用，这样域名解析处只需要做好主域名的解析就可以了。

**Comment by zhengkunwang223** [comment]
您好，感谢建议，我们会在后续版本支持

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
