### ISSUE TITLE
[BUG] Jenkins 从 v2.448 升级到 v.2452.1-lts 变成全新安装的了 没有保留之前的数据  

### ISSUE THREAD

**Issue by augusl** [1Panel-dev/1Panel#5029]
### 联系方式

phpvalue@yahoo.com

### 1Panel 版本

v1.10.7-lts

### 问题描述

Jenkins 从  v2.448 升级到  v.2452.1-lts 变成全新安装的了  没有保留之前的数据

### 重现步骤

升级Jenkins

**Comment by augusl** [comment]
[feat: Jenkins 修改为 LTS 版本](https://github.com/1Panel-dev/appstore/commit/e3beea2a60babb8bad40bdba9cd2c8ba08e7e3dd)  这次修改导致的

**Comment by wanghe-fit2cloud** [comment]
停止 Jenkins 服务，然后进入 Jenkins 应用安装目录，将原有的 jenkins 目录重命名为 data（可以提前删除最新生成的 data 目录），最后重启 Jenkins。
