### ISSUE TITLE
希望能支持chroot容器的一键安装脚本[FEATURE]

### ISSUE THREAD

**Issue by guc325** [1Panel-dev/1Panel#503]
### 1Panel 版本

1.05

### 请描述您的需求或者改进建议

希望能支持arm chroot容器的一键安装脚本
支持多个架构如
墙裂建议支持arm架构

### 请描述你建议的实现方案

无

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1、当前版本我们是支持了 amd64 和 arm64，后续还会持续适配更多架构。
2、chroot 在线安装 docker 失败的问题，你可以先手动安装 docker，然后再运行 1Panel 的在线安装脚本（docker 正常运行的情况下会跳过安装）。我们在后续版本中可能会考虑支持 chroot。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布，新增支持 armv7l、ppc64le、s390x 三种架构。
