### ISSUE TITLE
[BUG]新增证书状态提示问题 新增证书后修改证书名称问题

### ISSUE THREAD

**Issue by itpoo** [1Panel-dev/1Panel#5030]
### 1Panel 版本

v1.10.7-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/165099803/8905d34f-bb53-4605-b557-114f33f05a9a)
新增证书状态提示：`commons.status.`
添加成功证书之后修改证书名称提示：`请求参数错误: Key: 'WebsiteSSLUpdate.AcmeAccountID' Error:Field validation for 'AcmeAccountID' failed on the 'required' tag`

### 重现步骤

证书-->新增证书-->状态提示：`commons.status.`
证书-->新增证书-->修改证书名称-->提示错误：`请求参数错误: Key: 'WebsiteSSLUpdate.AcmeAccountID' Error:Field validation for 'AcmeAccountID' failed on the 'required' tag`

**Comment by zhengkunwang223** [comment]
手动上传的证书请使用更新按钮，编辑按钮后续版本会禁用

**Comment by wanghe-fit2cloud** [comment]
v1.10.8-lts 版本已发布。
