### ISSUE TITLE
[BUG]备份的站点上传回复提示文件不匹配？

### ISSUE THREAD

**Issue by itpoo** [1Panel-dev/1Panel#5032]
### 1Panel 版本

v1.10.7-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/165099803/b1c61b84-3779-4679-bf15-d991d33cb26e)

### 重现步骤

备份站点-->重装1Panel-->导入备份-->提示文件不匹配

**Comment by zhengkunwang223** [comment]
当前网站备份恢复，仅支持本机
从其他 1panel 导入网站备份会在后续版本支持
