### ISSUE TITLE
[FEATURE] 应用安装时将输出镜像拉取日志

### ISSUE THREAD

**Issue by wojiushixiaobai** [1Panel-dev/1Panel#5033]
### 1Panel 版本

All

### 请描述您的需求或者改进建议

目前的日志只能看到应用启动时的日志，建议加入拉取镜像的即时日志方便用户知晓任务进行到什么步骤（国内网络可能并不能正确访问 Docker Hub）。

### 请描述你建议的实现方案

略

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本优化

**Comment by wanghe-fit2cloud** [comment]
重复问题 https://github.com/1Panel-dev/1Panel/issues/785
