### ISSUE TITLE
[FEATURE] 应用商店的搜索能否支持编程语言搜索

### ISSUE THREAD

**Issue by Jaylenwa** [1Panel-dev/1Panel#5036]
### 1Panel 版本

v1.10.7-lts

### 请描述您的需求或者改进建议

1Panel的应用商店内有大量的优质开源项目，让人忍不住想学习一些开源项目的源码。
但是没有直观的页面看到这个开源项目主要用的前后端开发语言是什么。需要每个都点到github地址去查看。

### 请描述你建议的实现方案

![Snipaste_2024-05-17_13-49-11](https://github.com/1Panel-dev/1Panel/assets/65205528/d62840f8-7b17-4878-8ece-c9348d963eea)

### 附加信息

这需求只是针对我个人场景觉得有帮助的场景、具体是否合理希望1panel团队评估一下

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，经过讨论，目前我们暂无计划支持该需求，感谢理解。
