### ISSUE TITLE
[FEATURE]openresty无法修改默认的404页面

### ISSUE THREAD

**Issue by bushanhuo** [1Panel-dev/1Panel#5040]
### 1Panel 版本

v1.10.7-lts

### 请描述您的需求或者改进建议

目前1Panel无法修改OpenResty默认的404的页面。
建议后续可自定义设置404页面返回的内容。
如果能包含其它错误的页面更好了！

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
设置 404 等错误页面相关功能的讨论，统一汇总到该 issue #701

**Comment by li-peifeng** [comment]
从提出申请到现在都1年了，还没加上，太丑了
