### ISSUE TITLE
[BUG]WAF清空拦截记录后概览页面数据未同步

### ISSUE THREAD

**Issue by itpoo** [1Panel-dev/1Panel#5041]
### 1Panel 版本

v1.10.7-lts

### 问题描述

清空WAF拦截日志后概览界面数据未同步更新。

### 重现步骤

WAF-->拦截记录-->清空日志-->概览页面-->数据未同步更新

### 期待的正确结果

清空拦截日志后建议概览页面数据能够同步。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
