### ISSUE TITLE
[BUG] 防火墙无法添加v6规则

### ISSUE THREAD

**Issue by Fantasy135** [1Panel-dev/1Panel#5042]
### 联系方式

zhao.h2018@gmail.com

### 1Panel 版本

1.1.07-alpha.8

### 问题描述
![Screenshot_2024-05-17-23-57-34-679_com chrome beta](https://github.com/1Panel-dev/1Panel/assets/57759754/a609bf4c-53b4-4ef6-b7b1-802633517844)

### 重现步骤

firewalld 防火墙无法添加 ipv6 规则

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
关于 `主机` - `防火墙` 设置 IPv6 规则相关的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/2409
