### ISSUE TITLE
[FEATURE]反代面板后终端连接提示disconnected

### ISSUE THREAD

**Issue by ayoulx** [1Panel-dev/1Panel#5043]
### 1Panel 版本

v1.10.7-lts专业版

### 请描述您的需求或者改进建议

![本地终端连接](https://github.com/1Panel-dev/1Panel/assets/54100440/363c751f-58df-4a1a-9009-e49b0fa6065c)
![测试连通](https://github.com/1Panel-dev/1Panel/assets/54100440/f00de30b-35ba-44d4-9dc5-55452d791fa2)
![容器终端连接](https://github.com/1Panel-dev/1Panel/assets/54100440/5a16d425-acd9-475a-b419-88823725e131)
用1panel反代了
[系统功能相关 - 1Panel 文档](https://1panel.cn/docs/faq/system_function/)
![网站配置文件](https://github.com/1Panel-dev/1Panel/assets/54100440/9657498f-237c-419a-804c-771370f14523)
文档提示的配置也有

### 请描述你建议的实现方案

希望解决该问题

**Comment by MiderWong** [comment]
#### 1、宿主机终端
第二张截图保存的是宿主机的连接方式，实际执行命令是
```shell
ssh root@127.0.0.1 -p
```
按照toast提示说明宿主机连接宿主机ip、端口、用户、密码信息校验通过，第一张图的效果大概率是因为ssh配置没有开放keeplive并且长时间未操作。
顺便可以检查一下宿主机SSH配置，如下图：
![image](https://github.com/1Panel-dev/1Panel/assets/7487008/ae6034a9-6444-4fdd-939d-9cbcf90e6996)

#### 2、容器终端
第三张截图是容器终端的连接配置，实际执行命令是
```shell
docker exec -it --user root(你指定的用户) 1Panel-qinglong-xxx(你的容器名称) /bin/sh(你选择的shell) 
```
具体配置如下图
![image](https://github.com/1Panel-dev/1Panel/assets/7487008/d4fadf2f-584c-4427-bccd-5de9bacbbad2)

第四张截图的效果是从第一张图上又截取了一下吗？
#### 3、其它图
其它图的配置与当前终端连接无关

**Comment by ayoulx** [comment]
> #### 1、宿主机终端
> 第二张截图保存的是宿主机的连接方式，实际执行命令是
> 
> ```shell
> ssh root@127.0.0.1 -p
> ```
> 
> 按照toast提示说明宿主机连接宿主机ip、端口、用户、密码信息校验通过，第一张图的效果大概率是因为ssh配置没有开放keeplive并且长时间未操作。 顺便可以检查一下宿主机SSH配置，如下图： ![图像](https://private-user-images.githubusercontent.com/7487008/331769267-ae6034a9-6444-4fdd-939d-9cbcf90e6996.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMTIxOTgsIm5iZiI6MTcxNjAxMTg5OCwicGF0aCI6Ii83NDg3MDA4LzMzMTc2OTI2Ny1hZTYwMzRhOS02NDQ0LTRmZGQtOTM5ZC05Y2JjZjkwZTY5OTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MThUMDU1ODE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTBhNDI2Y2U0YmRmOWUzNGNlYWUyMWFhNTgyYTUyZjkzYmZiNDhkNjRiMjNkNTQxMmJiYzMyODkxOTM0OGJmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lsyHgdC1JAY1x0CqTp0ztQ5CBODo2_qqyyqZ8535k7s)
> 
> #### 2、容器终端
> 第三张截图是容器终端的连接配置，实际执行命令是
> 
> ```shell
> docker exec -it --user root(你指定的用户) 1Panel-qinglong-xxx(你的容器名称) /bin/sh(你选择的shell) 
> ```
> 
> 具体配置如下图 ![图像](https://private-user-images.githubusercontent.com/7487008/331768797-d4fadf2f-584c-4427-bccd-5de9bacbbad2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMTIxOTgsIm5iZiI6MTcxNjAxMTg5OCwicGF0aCI6Ii83NDg3MDA4LzMzMTc2ODc5Ny1kNGZhZGYyZi01ODRjLTQ0MjctYmNjZC01ZGU5YmFjYmJhZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MThUMDU1ODE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2NmY2ZiMDJhM2MyZTVlZjY2Y2M0Mjg1MmJjYzNiZTdiZjY1ZThlOGRmMmRiZWU3MjE4ZGZiYzZkYTcxOGI5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IthymSn2oOSIfdlxEpZB1OqgKNf_OBgo4HLwtpO-dvY)
> 
> **第四张截图的效果是从第一张图上又截取了一下吗？**
> 
> > 因为在默认SSH配置（宿主机和Docker容器内，两个是单独的，互不影响）下，如果终端长时间不操作，都会自动中断连接
> 
> #### 3、其它图
> 其它图的配置与当前终端连接无关

![image](https://github.com/1Panel-dev/1Panel/assets/54100440/72bb7dc4-f3cd-4b46-a55f-fcc829b6c5fb)
这个是SSH配置的
![image](https://github.com/1Panel-dev/1Panel/assets/54100440/2d7cf49b-4e04-404b-aa5f-59ae4207d6fe)
第四张图是从网站的配置文件截取的
![image](https://github.com/1Panel-dev/1Panel/assets/54100440/a31e7dea-d70d-4c28-9458-64eebb6b98d8)
在1panel文档里有说明这个问题，但是我这里配置了
我是反代面板后用面板的终端连接不上，没有长时间不操作

**Comment by MiderWong** [comment]
1、我的理解是不管Docker容器中的SSH连接还是你宿主机的SSH连接，跟你网站没有关系，两边八竿子打不着。
2、既然通过1P面板的Web连接不上，可以试试通过SSH终端连接，如果SSH终端能连接，而Web配置正确的情况下还不能连接，请把所有配置截图发出来，而不是发网站配置，**再次说一遍，没有关系，没有关系，没有关系，**那是网站，是由OpenResty代理的，终端是SSH是两个不同的应用，针对宿主机可以试试
```
ssh root ip:2211 
```
3、针对Docker的连接，可以在宿主机中执行
```
docker exec -it 容器名称 /bin/sh
```

**Comment by GD2021** [comment]
我也是连不上

**Comment by GD2021** [comment]
咱俩一言的问题

**Comment by GD2021** [comment]
咱俩一样的问题

**Comment by GD2021** [comment]
另外容器日志也是空白
![image](https://github.com/1Panel-dev/1Panel/assets/81171294/b70b03cf-2a45-43ba-8ccc-a0fca2327518)

**Comment by ayoulx** [comment]
> 咱俩一样的问题

有没有套cdn？套了cdn的话，大概就是cdn的问题

**Comment by GD2021** [comment]
套了呀

**Comment by GD2021** [comment]
你的解决了吗

**Comment by ayoulx** [comment]
> 你的解决了吗

我不跟你说了吗？
![image](https://github.com/1Panel-dev/1Panel/assets/54100440/cd87a3e2-5d8d-486f-9626-522c9ada3af7)
