### ISSUE TITLE
[FEATURE]应用商店增加 Hydro

### ISSUE THREAD

**Issue by shkouyo** [1Panel-dev/1Panel#5044]
### 1Panel 版本

v1.10.7-lts

### 请描述您的需求或者改进建议

应用商店增加 [Hydro](https://hydro.js.org)
[https://hydro.js.org](https://hydro.js.org)
[https://github.com/hydro-dev/Hydro](https://github.com/hydro-dev/Hydro)

### 附加信息

Hydro 是一个高效的信息学在线测评系统。特点：易于部署（且提供安装脚本），轻量，功能强大且易于扩展。

**Comment by wanghe-fit2cloud** [comment]
推荐使用官方提供的脚本来安装该应用（进入 `主机` - `终端` 执行脚本），脚本内容如下：
```shell
LANG=zh . <(curl https://hydro.ac/setup.sh)
```

还有，注意到目前官方对 docker 容器化部署支持的不是很好，如下图所示：
<img width="826" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/ffa87704-efe8-475e-baca-ff143353e405">
