### ISSUE TITLE
[BUG]申请证书失败

### ISSUE THREAD

**Issue by Ben-Huang** [1Panel-dev/1Panel#5046]
### 1Panel 版本

v1.10.7-lts

### 问题描述

2024-03-05申请过一次证书,是可以正常申请的,2024-06-03证书到期
目前再次申请证书全部失败

### 重现步骤

尝试"禁用 CNAME"和"跳过 DNS 校验" 也都失败
查看腾讯云解析日志,没发现任务操作日志

### 相关日志输出

```shell
2024/05/19 12:08:33 开始申请证书,域名 [*.domain] 申请方式 [DNS 自动] DNS 账号 [domain] 厂商 [TencentCloud]
2024/05/19 12:08:33 [INFO] [*.domain] acme: Obtaining bundled SAN certificate
2024/05/19 12:08:34 [INFO] [*.domain] acme: use dns-01 solver
2024/05/19 12:08:34 [INFO] [*.domain] acme: Preparing to solve DNS-01
2024/05/19 12:48:45 [INFO] [*.domain] acme: Cleaning DNS-01 challenge
2024/05/19 13:28:55 [WARN] [*.domain] acme: cleaning up failed: tencentcloud: failed to get hosted zone: could not find zone for FQDN "_acme-challenge.domain." : could not find the start of authority for _acme-challenge.domain.: read udp 192.168.2.6:51974->119.29.29.29:53: i/o timeout 
2024/05/19 13:28:59 申请  [*.domain] 证书失败, error: one or more domains had a problem:
[*.domain] [*.domain] acme: error presenting token: tencentcloud: failed to get hosted zone: could not find zone for FQDN "_acme-challenge.domain." : could not find the start of authority for _acme-challenge.domain.: read udp 192.168.2.6:46860->119.29.29.29:53: i/o timeout
```

**Comment by zhengkunwang223** [comment]
可以编辑证书，使用8.8.8.8这个dns服务器

**Comment by Ben-Huang** [comment]
> 可以编辑证书，使用8.8.8.8这个dns服务器

试过,一样的错误
我觉得问题在于 acme: cleaning up failed: could not find zone for FQDN "_acme-challenge.domain.": could not find the start of authority for _acme-challenge.domain.: ,以前申请没有 ".",正常应该是"_acme-challenge.domain"

**Comment by zhengkunwang223** [comment]
> > 可以编辑证书，使用8.8.8.8这个dns服务器
> 
> 
> 
> 试过,一样的错误
> 
> 我觉得问题在于 acme: cleaning up failed: could not find zone for FQDN "_acme-challenge.domain.": could not find the start of authority for _acme-challenge.domain.: ,以前申请没有 ".",正常应该是"_acme-challenge.domain"

看日志是访问超时了,119.29.29.29 是 dnspod 的 api 服务器，你可以尝试在你的机器上请求一下

**Comment by Ben-Huang** [comment]
> > > 可以编辑证书，使用8.8.8.8这个dns服务器
> > 
> > 
> > 试过,一样的错误
> > 我觉得问题在于 acme: cleaning up failed: could not find zone for FQDN "_acme-challenge.domain.": could not find the start of authority for _acme-challenge.domain.: ,以前申请没有 ".",正常应该是"_acme-challenge.domain"
> 
> 看日志是访问超时了,119.29.29.29 是 dnspod 的 api 服务器，你可以尝试在你的机器上请求一下

无论是使用哪个dns,都会这样超时

```
2024/05/19 20:28:53 申请  [*.domain] 证书失败, error: one or more domains had a problem:
[*.domain] [*.domain] acme: error presenting token: could not find zone for FQDN "_acme-challenge.domain.": could not find the start of authority for _acme-challenge.domain.: read udp 192.168.2.6:54490->8.8.8.8:53: i/o timeout
```

尝试用手动dns方式申请,会要求解析"_acme-challenge.*.domain." ,直接复制填写到腾讯云解析后台无法保存,会提示`主机记录的 "." 之间不能为空`,如果主机记录直接填写"_acme-challenge",最后证书也会申请失败

**Comment by Ben-Huang** [comment]
![Uploading 微信图片_20240519212248.png…]()

**Comment by Ben-Huang** [comment]
![微信图片_20240519212248](https://github.com/1Panel-dev/1Panel/assets/15009374/ab3117ac-4bbf-41b8-84f0-f858ab2942b6)

**Comment by zhengkunwang223** [comment]
> ![微信图片_20240519212248](https://github.com/1Panel-dev/1Panel/assets/15009374/ab3117ac-4bbf-41b8-84f0-f858ab2942b6)
> 
> 

看一下你的防火墙有没有限制呢？

**Comment by Ben-Huang** [comment]
> > ![微信图片_20240519212248](https://private-user-images.githubusercontent.com/15009374/331874858-ab3117ac-4bbf-41b8-84f0-f858ab2942b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjc1MDksIm5iZiI6MTcxNjEyNzIwOSwicGF0aCI6Ii8xNTAwOTM3NC8zMzE4NzQ4NTgtYWIzMTE3YWMtNGJiZi00MWI4LTg0ZjAtZjg1OGFiMjk0MmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDE0MDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNGMwZTQ4MDQzZDQ3ZGE0ZTU4ZDg5M2Y3MTUxYzE2YjRmZGI5MjQxN2U5OGJjNzAwYmRjMmZlZWU5MDlkOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M5DloRlL2FosKradTV4Unn16NeZVTRgqj3NWwA8EBXs)
> 
> 看一下你的防火墙有没有限制呢？

具体看哪方面?防火墙出站不会有限制

**Comment by zhengkunwang223** [comment]
> > > ![微信图片_20240519212248](https://private-user-images.githubusercontent.com/15009374/331874858-ab3117ac-4bbf-41b8-84f0-f858ab2942b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjc1MDksIm5iZiI6MTcxNjEyNzIwOSwicGF0aCI6Ii8xNTAwOTM3NC8zMzE4NzQ4NTgtYWIzMTE3YWMtNGJiZi00MWI4LTg0ZjAtZjg1OGFiMjk0MmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDE0MDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNGMwZTQ4MDQzZDQ3ZGE0ZTU4ZDg5M2Y3MTUxYzE2YjRmZGI5MjQxN2U5OGJjNzAwYmRjMmZlZWU5MDlkOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M5DloRlL2FosKradTV4Unn16NeZVTRgqj3NWwA8EBXs)
> 
> > 
> 
> > 看一下你的防火墙有没有限制呢？
> 
> 
> 
> 具体看哪方面?防火墙出站不会有限制

出站没有限制的话，你编辑证书，不要选 cname 也不要选跳过 dns 验证，只增加 dns 8.8.8.8

**Comment by wan92hen** [comment]
可以在命令行指定 DNS 服务器手动测试下
```
dig @8.8.8.8 _acme-challenge.1panel.cn txt
```

**Comment by Ben-Huang** [comment]
问题找到了因为 v2rayA 导致全部dns TXT类型查询全部超时

**Comment by Anemone220** [comment]
> 问题找到了因为 v2rayA 导致全部dns TXT类型查询全部超时

请问一下最后是如何解决的

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> The problem was found because v2rayA caused all dns TXT type queries to time out

How to solve it in the end
