### ISSUE TITLE
[FEATURE]为啥应用商店的zerotier系列的应用下架了？

### ISSUE THREAD

**Issue by RebellionAQG** [1Panel-dev/1Panel#5048]
### 1Panel 版本

1.10.7

### 请描述您的需求或者改进建议

为啥应用商店的zerotier系列的应用下架了？

### 请描述你建议的实现方案

还能上架否？

**Comment by wanghe-fit2cloud** [comment]
参考 https://github.com/1Panel-dev/1Panel/issues/4696
