### ISSUE TITLE
[BUG] openresty 配置反代文件，404 Not Found

### ISSUE THREAD

**Issue by waves8116** [1Panel-dev/1Panel#5052]
### 联系方式

waves7178@gmail.com

### 1Panel 版本

1.10.7

### 问题描述

openresty 配置反代文件，404 Not Found

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/168502621/ab932293-c024-45c9-85c8-0c8245861a8e)
![image](https://github.com/1Panel-dev/1Panel/assets/168502621/a692450c-4c35-497d-8c43-1629c2fe702d)
![image](https://github.com/1Panel-dev/1Panel/assets/168502621/71dd1a71-514e-4bd4-95d9-b24ad5d0ed28)

**Comment by wan92hen** [comment]
可以使用 `alias` 进行配置，使用 `root` 的方式最终的文件路径会是 `nf/nf/index.html` 这样，所以会 404。
https://stackoverflow.com/questions/10631933/nginx-static-file-serving-confusion-with-root-alias
