### ISSUE TITLE
[FEATURE] 能否把应用离线安装提上日程

### ISSUE THREAD

**Issue by yfdoor** [1Panel-dev/1Panel#5070]
### 1Panel 版本

 v1.10.7-lts

### 请描述您的需求或者改进建议

服务器的部署情况千差万别，但是应该也有一部分应该是部署在局域网内，因此将 1panel 部署进入局域网应该也是一个刚需。还请考虑是否可以尽快将离线部署安排一下。。

### 请描述你建议的实现方案

1panel 的离线有教程可以实现，但是应用的离线安装现在除了修改数据库，似乎没有太好的方法，还请官方考虑一下。。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
重复问题 https://github.com/1Panel-dev/1Panel/issues/4935
