### ISSUE TITLE
[FEATURE]建议将密码访问的对话框改为登录页

### ISSUE THREAD

**Issue by yggcwx** [1Panel-dev/1Panel#5074]
### 1Panel 版本

v1.10.7-lts

### 请描述您的需求或者改进建议

给网站设置了密码访问后，bitwarden无法识别、填写登录用户名和密码。建议以后改为生成一个登录页面，而不是弹出式对话框，这样，bitwarden就可以识别了。

### 请描述你建议的实现方案

建议将密码访问改为登录页，而不是对话框。就像南墙、雷池那样，生成一个简单的登录页面

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们是基于 OpenResty 默认的 HTTP 基本身份验证（Basic Authentication）来实现资源的保护，这种方式不支持自定义的登录页面。

> 我们可能会在后续版本考虑基于 lua 脚本来实现上述功能。
