### ISSUE TITLE
[FEATURE]应用商店umami的docker地址更新

### ISSUE THREAD

**Issue by xiaobaozi233** [1Panel-dev/1Panel#5075]
### 1Panel 版本

V1.10.6

### 请描述您的需求或者改进建议

umami的地址已经变成了
`docker.umami.is/umami-software/umami`
应用商店里的是
`ghcr.io/umami-software/umami`
ghcr这阿里云实在没速度

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本适配上述仓库地址。
