### ISSUE TITLE
[BUG]  清空伪静态配置报错

### ISSUE THREAD

**Issue by likesrt** [1Panel-dev/1Panel#5086]
### 联系方式

yuyan@broue.cn

### 1Panel 版本

专业版：v1.10.7-lts

### 问题描述

设置伪静态后，清空伪静态配置。保存时会报错。
请求参数错误: Key: 'NginxRewriteUpdate.Content' Error:Field validation for 'Content' failed on the 'required' tag

经查看默认伪静态配置中有一个空格。
直接清空报存会报错。建议增加提示说明。

### 重现步骤

如上

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述体验。

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
