### ISSUE TITLE
从应用商店一键部署的应用会在应用内部出现网络问题

### ISSUE THREAD

**Issue by yucrushme** [1Panel-dev/1Panel#5087]
### 联系方式

2992576917

### 1Panel 版本

v1.10.7-lts

### 问题描述

从应用商店一键部署的应用会在应用内部出现网络问题，比如dosgame应用里面的所有游戏显示无法下载，koishi会显示插件市场无法连接至网络。我从dockerhub中搜索并部署这两个应用却没有此问题。本人技术水平较低无法进一步排查网络问题。
![屏幕截图 2024-05-21 232516](https://github.com/1Panel-dev/1Panel/assets/77479694/b47acb7d-75cc-4457-adc4-0ab0c5c0448a)
![屏幕截图 2024-05-21 232548](https://github.com/1Panel-dev/1Panel/assets/77479694/9c70f5b2-460a-46e7-974e-90537f3ef0db)

### 重现步骤

可以一直重现，删干净重建也不可以。

### 期待的正确结果

第一次提issue，感谢

**Comment by wanghe-fit2cloud** [comment]
错误原因是因为容器内访问不到外网导致的，可以尝试以下几种方法，看是否生效：

1、关闭服务器防火墙，然后重启网络、重启 docker。
2、进入 `容器` - `配置` 页面，确保 iptables 一定是打开状态。
