### ISSUE TITLE
[FEATURE]收藏夹悬浮框显示文件夹全路径

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#5094]
### 1Panel 版本

v1.10.7-lts

### 请描述您的需求或者改进建议

通过鼠标移动到收藏夹按钮弹出跳转菜单列，菜单列只会显示目录名称，不会显示路径。
如果出现 `/apps/folder` 和 `/apps2/folder` 两个目录时都显示名称 folder，不知道是哪个目录的

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
