### ISSUE TITLE
[FEATURE]关于网速单位显示优化的建议

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#5095]
### 1Panel 版本

v1.10.7-lts

### 请描述您的需求或者改进建议

目前网速只能按照 `KB/s` 显示不太合理，应当按照 bt 那样可以显示多种单位维度，如图：
![图片](https://github.com/1Panel-dev/1Panel/assets/29944886/552eb324-9e9d-48cb-b9dd-ae2b161d6fc4)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上述建议。
