### ISSUE TITLE
[FEATURE] 请支持 docker-compose down

### ISSUE THREAD

**Issue by Calcifer97** [1Panel-dev/1Panel#5099]
### 1Panel 版本

v1.10.7-lts

### 请描述您的需求或者改进建议

查看日志得知，下面三个按钮分别对应:
docker-compose up
docker-compose stop
docker-compose down
![image](https://github.com/1Panel-dev/1Panel/assets/37408196/0b1444d7-dd6b-458a-956c-164aeb347dd5)
![image](https://github.com/1Panel-dev/1Panel/assets/37408196/839ebe91-703f-4401-bc40-982e8f6b26ac)

现在不能做到的功能：
我想要停用这个编排应该对应down，但是目前只能点击删除。这样编排文件被删除掉了

我想要的效果：
无论怎么操作，不应该删除编排条目，除非明确指定

### 请描述你建议的实现方案

第一种：仿造portainer
把现有的停止按钮对应docker-compose down，不做docker-compose stop功能。删除按钮对应删除编排条目
![image](https://github.com/1Panel-dev/1Panel/assets/37408196/8c420092-cad4-4094-8397-c309975014cd)

第二种：
条目内的删除按钮，只负责down，不要删除条目，改名叫做“销毁”等
这个界面的按钮，可以down并且删除条目
![image](https://github.com/1Panel-dev/1Panel/assets/37408196/48e476a1-f7b6-49af-abe8-cc53de7f258a)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.10.16 版本已发布。
