### ISSUE TITLE
[BUG] 计划任务 备份 pgsql 数据库

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#5103]
### 1Panel 版本

最新

### 问题描述

pgsql数据库在停止的情况，计划任务还是显示成功，这是不合理的
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/b5e56f1d-006a-4c03-9c3a-3098bbb95826)

### 重现步骤

安装pgsql数据库，创建计划任务备份pgsql数据库，停止数据库，手动执行任务即可看见

### 期待的正确结果

和mysql行为一致
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/399923ac-b35a-4f8d-8405-2e656e8d7288)

**Comment by ssongliu** [comment]
感谢反馈，我们本地验证一下这个问题

**Comment by ssongliu** [comment]
> 感谢反馈，我们本地验证一下这个问题

已确认，1.10.10 修复该问题

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
