### ISSUE TITLE
[BUG] docker仓库创建私有仓库，因密码有特殊字符无法确定提交

### ISSUE THREAD

**Issue by georgeJzzz** [1Panel-dev/1Panel#5106]
### 1Panel 版本

v1.10.8-lts

### 问题描述

docker仓库创建私有仓库，因密码有特殊字符无法确定

### 重现步骤

docker仓库创建私有仓库，因密码有特殊字符无法确定

![image](https://github.com/1Panel-dev/1Panel/assets/42543889/ac49899f-b4b7-4e3c-a8c0-15e16e3ad524)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述校验是为了防止后端命令注入添加的。
> 发一下密码包含的所有特殊字符。

**Comment by georgeJzzz** [comment]
> 感谢反馈，上述校验是为了防止后端命令注入添加的。
> 
> > 发一下密码包含的所有特殊字符。

我这边密码特殊字符有【#$】

**Comment by wanghe-fit2cloud** [comment]
是 `$` 字符被拦截了，由于涉及到 docker 命令的执行，所以只能考虑将仓库密码种包含的 `$` 去掉，之后再来添加仓库。

**Comment by georgeJzzz** [comment]
@wanghe-fit2cloud 

密码中确定存在`$`,  1panel中密码输入框中`存在不合法字符的校验`, 我这边无法`确定`操作，也就无法添加仓库了。 
在linux终端中含有`$`的密码是可login success的。 
这块是否可以去除对`$`的校验  或者 有其他临时办法

**Comment by wanghe-fit2cloud** [comment]
> @wanghe-fit2cloud
>
> 密码中确定存在`$`, 1panel中密码输入框中`存在不合法字符的校验`, 我这边无法`确定`操作，也就无法添加仓库了。 
在linux终端中含有`$`的密码是可login success的。
这块是否可以去除对`$`的校验 或者 有其他临时办法

去除 `$` 字符的校验会存在命令注入的风险，因此目前你先尝试手动修改一下仓库密码。

**Comment by georgeJzzz** [comment]
> > @wanghe-fit2cloud
> > 密码中确定存在`$`, 1panel中密码输入框中`存在不合法字符的校验`, 我这边无法`确定`操作，也就无法添加仓库了。
> > 在linux终端中含有`$`的密码是可login success的。
> > 这块是否可以去除对`$`的校验 或者 有其他临时办法
> 
> 去除 `$` 字符的校验会存在命令注入的风险，因此目前你先尝试手动修改一下仓库密码。

> 明白了，非常感谢。

**Comment by georgeJzzz** [comment]
再次叨唠，这边修改密码有点繁琐，有临时改文件的方法使得可以确定登录仓库吗？

感谢 ~

**Comment by wanghe-fit2cloud** [comment]
> 再次叨唠，这边修改密码有点繁琐，有临时改文件的方法使得可以确定登录仓库吗？
> 
> 感谢 ~

docker 仓库密码是存储在数据库中，手动修改失败状态的仓库密码也是不可行的，因为创建、编辑仓库都需要用户手动输入用户密码
