### ISSUE TITLE
[BUG] 快照点击删除后，实际快照文件不会删除。

### ISSUE THREAD

**Issue by OuOumm** [1Panel-dev/1Panel#5114]
### 联系方式

issue联系

### 1Panel 版本

v1.10.7-lts

### 问题描述

1.快照使用完毕后，点击删除，只是删除了面板显示，并没有删除快照文件。

2.恢复快照后，在恢复快照前会备份当前环境，也就是新建一个快照，该快照不会显示在面板上，需要手动去目录里删除。

### 重现步骤

1.备份快照，随后删除快照，实际快照文件不会删除，依旧占用存储空间

2.恢复快照后，默认创建了恢复前的快照。

### 期待的正确结果

1.给出选项，是否删除快照文件

2.显示在面板上

**Comment by ssongliu** [comment]
重复 #4962
