### ISSUE TITLE
[BUG]创建应用时，redis密码不能带有其他特殊符号，但是安装redis时缺可以设置

### ISSUE THREAD

**Issue by montrovcom** [1Panel-dev/1Panel#5115]
### 1Panel 版本

 专业版v1.10.8-lts

### 问题描述

[BUG]创建应用时，redis密码不能带有其他特殊符号，但是安装redis时缺可以设置。导致创建应用时表单报错

### 重现步骤

安装redis时，密码带有！@等字符。然后再安装jumpserver表单验证失败

### 附加信息

![redis](https://github.com/1Panel-dev/1Panel/assets/144432284/9450ea7e-02cb-4c6e-b919-f4130bb634de)

**Comment by montrovcom** [comment]
![Uploading redis.jpg…]()

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
密码复杂度相关问题的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4290
