### ISSUE TITLE
[BUG]启动1panel面板，服务器cpu99.99%

### ISSUE THREAD

**Issue by motao123** [1Panel-dev/1Panel#5117]
### 1Panel 版本

专业版v1.10.8-lts

### 问题描述

#5805 
上说“建议将 IP 类型的网站设置为默认网站。”
但是我没ip类型网站

![微信截图_20240522151812.png](https://img.imotao.com/i/2024/05/22/664d9c720bab2.png)

### 重现步骤

还是更新OpenResty失败后，导致1panel占用CPU99.99%

**Comment by wanghe-fit2cloud** [comment]
重复问题 https://github.com/1Panel-dev/1Panel/discussions/5085
