### ISSUE TITLE
[FEATURE]自签证书显示问题

### ISSUE THREAD

**Issue by bushanhuo** [1Panel-dev/1Panel#5118]
### 1Panel 版本

v1.10.8-lts

### 请描述您的需求或者改进建议

在网站---证书栏里，使用自签证书状态里面会显示：commons.status.
包括使用CloudFlare的证书也会显示这个。

如图：
![状态](https://github.com/1Panel-dev/1Panel/assets/43093839/9b475f42-2dd7-424b-a044-97fb60deceb9)

### 请描述你建议的实现方案

希望可以修正一下显示的内容。
自签的证书可以正常显示自签证书状态。

**Comment by zhengkunwang223** [comment]
你是手动上传的证书吧 我们最新版本应该是修复的
你升级成功了吗？看一下右下角

**Comment by bushanhuo** [comment]
> 你是手动上传的证书吧 我们最新版本应该是修复的 你升级成功了吗？看一下右下角

v1.10.8-lts
还是一样的问题。

**Comment by zhengkunwang223** [comment]
<img width="940" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/31820853/22fed172-b93d-4f27-bb1b-1f9eb2829192">
你可能没有更新成功 
你去文件列表那 点击这个按钮 看看有没有用户和用户组的配置

**Comment by mingzaily** [comment]
一样的问题
手动上传的证书
![image](https://github.com/1Panel-dev/1Panel/assets/44798713/c6eec23b-d74b-401c-87bc-e8dd0b89b3ac)

**Comment by bushanhuo** [comment]
> <img alt="image" width="940" src="https://private-user-images.githubusercontent.com/31820853/333201087-22fed172-b93d-4f27-bb1b-1f9eb2829192.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzkyNDAsIm5iZiI6MTcxNjQ3ODk0MCwicGF0aCI6Ii8zMTgyMDg1My8zMzMyMDEwODctMjJmZWQxNzItYjkzZC00ZjI3LWJiMWItMWY5ZWIyODI5MTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE1NDIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MzQ0YTQ0ODAyMjYwOTcwYjc1ZjhhYTZjMDY1ZGJmMDgyYmU5MzYzZjVmYmFhMzBmNGViYjNjNDllMDA2ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0umSmBgZyzS7KZA7KfH5vcM8RbK8h5haaR5RI6w7ef0"> 你可能没有更新成功 你去文件列表那 点击这个按钮 看看有没有用户和用户组的配置

![55](https://github.com/1Panel-dev/1Panel/assets/43093839/751cbd01-1740-464f-bd54-be176bc3f7f9)

**Comment by mingzaily** [comment]
我也有

![image](https://github.com/1Panel-dev/1Panel/assets/44798713/bfb43005-80cd-48cb-8e0a-4f593630310b)

**Comment by zhengkunwang223** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/6a348563-cae8-4f47-8ccb-0fb9f6c3c615)
加我企业微信我远程看一下

**Comment by bushanhuo** [comment]
> ![image](https://private-user-images.githubusercontent.com/31820853/333434322-6a348563-cae8-4f47-8ccb-0fb9f6c3c615.png) 加我企业微信我远程看一下

已添加。

**Comment by mingzaily** [comment]
> > ![image](https://private-user-images.githubusercontent.com/31820853/333434322-6a348563-cae8-4f47-8ccb-0fb9f6c3c615.png) 加我企业微信我远程看一下
> 
> 已添加。

老哥，你的解决了吗

**Comment by bushanhuo** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/31820853/333434322-6a348563-cae8-4f47-8ccb-0fb9f6c3c615.png) 加我企业微信我远程看一下
> > 
> > 
> > 已添加。
> 
> 老哥，你的解决了吗

解决了，就把旧的证书删除，更新系统，重启机器。
再上传就完事了。
