### ISSUE TITLE
[BUG]Swap设置不对

### ISSUE THREAD

**Issue by jian308** [1Panel-dev/1Panel#5122]
### 1Panel 版本

v1.10.7-lts

### 问题描述

Swap修改大小后点保存，会增加这个大小而不是改成这个大小。
按说明设置为0，点保存，提示成功，但是还是不变。

### 重现步骤

如描述

### 期待的正确结果

修改多少就变多少，设置为0就关闭。

### 附加信息

发行版本 debian
内核版本 6.8.4-2-pve
系统类型 x86_64

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by ssongliu** [comment]
这里只支持管理 1Panel 创建 swap 分区，其他的分区增删风险比较大，需要手动操作，望理解。
