### ISSUE TITLE
[FEATURE] 添加 peergos 云存储

### ISSUE THREAD

**Issue by qingpx** [1Panel-dev/1Panel#5128]
### 1Panel 版本

1.10.8

### 请描述您的需求或者改进建议

官方  github docker      https://github.com/orgs/Peergos/packages/container/package/web-ui

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，我们主要以项目的 star 数量作为重要的上架指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有约 1 万 star 的开源项目，望理解。

> 可以将上述应用反馈给 [第三方仓库（由社区用户维护）](https://github.com/okxlin/appstore)。
也可以考虑使用 `容器` - `编排` 功能来维护应用。

**Comment by qingpx** [comment]
有1.9k 星   https://github.com/Peergos/Peergos
