### ISSUE TITLE
[FEATURE] 用户体验优化。

### ISSUE THREAD

**Issue by kevin-morgan** [1Panel-dev/1Panel#5138]
### 1Panel 版本

v1.10.9-lts

### 请描述您的需求或者改进建议

![WechatIMG3189](https://github.com/1Panel-dev/1Panel/assets/869317/9b5887b7-c1dd-4403-8e6a-8d80310aadff)
![WechatIMG3190](https://github.com/1Panel-dev/1Panel/assets/869317/d1445fe7-192e-4636-9e1d-7b53db07d2ea)

### 请描述你建议的实现方案

1、1Panel 后台登录界面下，『同意飞致与社区软件许可协议』默认自动勾选上，避免每次登录都需要手动点击，提高登陆效率。
2、切换到MFA认证界面的时候自动focus到输入框，避免每次都需要鼠标手动点击输入框聚焦，提高登陆效率。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by maninhill** [comment]
很有道理，很实用。

**Comment by kevin-morgan** [comment]
![WX20240528-150923@2x](https://github.com/1Panel-dev/1Panel/assets/869317/b7ee7ca4-3897-44c3-95d7-4f0d9140016a)
关于许可协议的建议方案颗参照截图中阿里云的许可协议。

**Comment by wanghe-fit2cloud** [comment]
v1.10.10 版本将优化移动端登录体验。

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
