### ISSUE TITLE
java的支持

### ISSUE THREAD

**Issue by liuzhiliu** [1Panel-dev/1Panel#5145]
### 1Panel 版本

v1.10.9-lts

### 请描述您的需求或者改进建议

什么时候可以支持java，期待好久了

**Comment by zhengkunwang223** [comment]
关于 JAVA 环境的部署，你可以先使用应用商店的 Tomcat 
关注此 issue https://github.com/1Panel-dev/1Panel/issues/748
由于我们需求实在太多 所以短时间可能还没有办法支持 请理解一下
