### ISSUE TITLE
[主机-文件-回收站] 支持批量恢复文件(夹)

### ISSUE THREAD

**Issue by QingFeng-awa** [1Panel-dev/1Panel#5148]
### 1Panel 版本

1.10.9-TLS

### 请描述您的需求或者改进建议

允许回收站批量选择并恢复文件/文件夹。

**Comment by zhengkunwang223** [comment]
感谢建议 我们会在后续版本中优化此处

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
