### ISSUE TITLE
[FEATURE] 主机-文件   图片文件不支持预览

### ISSUE THREAD

**Issue by Alexzzz2008** [1Panel-dev/1Panel#5151]
### 1Panel 版本

1.10.9

### 请描述您的需求或者改进建议

主机-文件   图片文件不支持预览

**Comment by zhengkunwang223** [comment]
感谢建议 我们会在后续版本不断优化

**Comment by wanghe-fit2cloud** [comment]
重复问题 https://github.com/1Panel-dev/1Panel/issues/5431
