### ISSUE TITLE
[FEATURE] 应用商店增加 Verdaccio 应用

### ISSUE THREAD

**Issue by HenryWu01** [1Panel-dev/1Panel#5153]
### 1Panel 版本

N/A

### 请描述您的需求或者改进建议

Verdaccio 是一个基于 Node.js 的轻量级私有仓库，类似于 npmjs.com

开源地址: https://github.com/verdaccio/verdaccio
Docker 镜像: https://hub.docker.com/r/verdaccio/verdaccio

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本考虑上架上述应用。

**Comment by wanghe-fit2cloud** [comment]
重复 https://github.com/1Panel-dev/1Panel/issues/3994

**Comment by wanghe-fit2cloud** [comment]
应用已上架。
进入应用商店列表，点击右上角的【更新应用列表】按钮，待同步完成后即可安装应用。
