### ISSUE TITLE
添加已有应用的面板

### ISSUE THREAD

**Issue by db-root** [1Panel-dev/1Panel#5154]
### 1Panel 版本

v1.10.9-lts

### 请描述您的需求或者改进建议

1、已安装应用能不能添加一个功能，讲服务器上已有的容器添加为应用，或直接添加应用功能，将图标和url加上来
2、最好能加上一个原生的DNS功能，或者支持应用里有个DNS应用也可以

**Comment by wanghe-fit2cloud** [comment]
1、由于容器的安装方式和配置文件等存在差异，因此仍需通过容器列表进行管理。
2、可以提供一份容器化部署 DNS 方案，我们计划在后续版本中将其上架到应用商店。

**Comment by db-root** [comment]
> 1、由于容器的安装方式和配置文件等存在差异，因此仍需通过容器列表进行管理。 
2、可以提供一份容器化部署 DNS 方案，我们计划在后续版本中将其上架到应用商店。

无法直接在应用管理去添加面板的功能嘛

**Comment by db-root** [comment]
还有一点就是安装了AdGuardHome这个服务，这个服务的端口为初始化的端口，在初始完成之后就无法再点击这个服务端口进行访问了，还需要再浏览器内手动输入IP+Ports进行访问，如果是可以增加面板的话，那这个端口应该也就可以改了吧
![image](https://github.com/1Panel-dev/1Panel/assets/90075706/af0566bf-29bb-4d7e-855f-92ace025b1cd)

![image](https://github.com/1Panel-dev/1Panel/assets/90075706/6440ed20-86b3-45f4-82bc-70d4e4eace30)

**Comment by wanghe-fit2cloud** [comment]
> 还有一点就是安装了AdGuardHome这个服务，这个服务的端口为初始化的端口，在初始完成之后就无法再点击这个服务端口进行访问了，还需要再浏览器内手动输入IP+Ports进行访问，如果是可以增加面板的话，那这个端口应该也就可以改了吧

后续版本会考虑部分应用端口的编辑功能。
