### ISSUE TITLE
[FEATURE]建议优化下文件编辑器

### ISSUE THREAD

**Issue by zitengxinmitu** [1Panel-dev/1Panel#5155]
### 1Panel 版本

v1.10.9-lts

### 请描述您的需求或者改进建议

建议优化下文件编辑器，目前修改文件只能打开一个文件修改完关闭才能修改其他的文件
可以参考bt上的
![QQ截图20240527094236](https://github.com/1Panel-dev/1Panel/assets/44016669/6ddefbb4-6678-4f22-84b0-4cb35f766961)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑优化文件编辑器功能。

**Comment by godcop** [comment]
> 感谢反馈，我们会在后续版本考虑优化文件编辑器功能。

可以考虑在应用商店增加一个vscode online应用，用户安装后可以绑定本地目录，也可以单独绑定自定义的工作空间

**Comment by wanghe-fit2cloud** [comment]
> 可以考虑在应用商店增加一个vscode online应用

感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
文件编辑器左侧目录相关问题的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/3624
