### ISSUE TITLE
[FEATURE] 多角色多用户登录 和 API 接口

### ISSUE THREAD

**Issue by maxbad** [1Panel-dev/1Panel#5156]
### 1Panel 版本

v1.10.9-lts

### 请描述您的需求或者改进建议

希望增加多角色多用户登录,不同用户登录看到的界面是不一样的.
 通过API接口,达到快速登录,无需填写账号密码验证码.

### 请描述你建议的实现方案

无

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
多用户权限体系需求的讨论，统一汇总到该 issue #638
