### ISSUE TITLE
[FEATURE] 安装应用输入框不支持特殊字符

### ISSUE THREAD

**Issue by vlssu** [1Panel-dev/1Panel#5160]
### 1Panel 版本

1.10.9-lts

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/43847794/483a8dd4-0d48-430c-bcd3-da94f683da45)
有时一些比较重要的密码需要复杂点来保证安全性

### 请描述你建议的实现方案

支持如@等特殊字符

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
重复问题 https://github.com/1Panel-dev/1Panel/issues/4290
