### ISSUE TITLE
[FEATURE]数据库账号不拥有创建数据库权限时，无法继续操作

### ISSUE THREAD

**Issue by onekb** [1Panel-dev/1Panel#5165]
### 1Panel 版本

v1.10.9-lts

### 请描述您的需求或者改进建议

路径：
数据库-远程服务器-添加远程RDS（该账号为普通账号，拥有指定数据库读写权限，但是不能创建数据库）
应用商店-One API-选择RDS数据库-填写数据名oneapi，提示无权限创建；或者我在超管创建后，就提示数据库已存在

### 请描述你建议的实现方案

希望对非超管数据库用户有好些，不强制要求由这个用户创建数据库

**Comment by wanghe-fit2cloud** [comment]
在应用商店创建应用时，可以选择使用 `远程数据库`，这时需要具备创建数据库的权限。
