### ISSUE TITLE
[FEATURE]应用商店新增plane(JIRA开源替代)

### ISSUE THREAD

**Issue by MiderWong** [1Panel-dev/1Panel#5168]
### 1Panel 版本

1.10.9-lts

### 请描述您的需求或者改进建议

应用商店中新增`plane`,
plane是用TS + Python实现的 类似 JIRA的轻量版BUG追踪软件，
git仓库地址:[plane](https://github.com/makeplane/plane)
希望可以在应用商店中加入该软件.

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们了解到该应用的维护较为复杂，因此暂时不考虑将其上架到正式版本的应用商店，望理解。
应用官方提供了 docker-compose.yml，你可以考虑通过‘容器’ - ‘编排’功能来维护该应用。
