### ISSUE TITLE
[文本编辑器] 支持更多语言

### ISSUE THREAD

**Issue by QingFeng-awa** [1Panel-dev/1Panel#5169]
### 1Panel 版本

1.10.9-LTS

### 请描述您的需求或者改进建议

为1Panel自带的文本编辑器增加更多语言。
目前个人期望以下语言:

- TypeScript
- Vue

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。

**Comment by QingFeng-awa** [comment]
`v1.10.12-beta.1`已更新,此issue关闭。
