### ISSUE TITLE
[BUG] WS测试,转发本地一个ws 出现添加不成功引发,整个1Panel-openresty服务无法启动.

### ISSUE THREAD

**Issue by AtlantisDe** [1Panel-dev/1Panel#5171]
### 1Panel 版本

v1.10.9-lts

## 反向代理 WS 测试 

ws://localhost:8447

添加不成功,导致整个 整个1Panel-openresty服务无法启动.

当前未启动 OpenResty 服务
 

## 反向代理站点配置信息

```bash
/www/sites/WsTest

# 实际这个站点都没建立启动成功,我不知道为啥 重新启动 1Panel-openresty服务 怎么会关联到 旧操作.
# 从开始就没建立成功过这个反向代理
```

### 重现步骤

1 . 添加 反向代理指向 ws://localhost:8447 失败
2. 重启动   OpenResty 服务 --- 失败了.

### 期待的正确结果

希望,能给到用户一个功能,可以给用户自行配置文件,
因为目前你们自动化配置 配置文件实在不稳定.
一直出问题.

我希望就是 我们固定好的配置文件能不被你们进行维护修改.

### 相关日志输出

```shell
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/www/sites/www.TestApp.com/ssl/fullchain.pem"
2024/05/28 00:58:35 [warn] 1#1: conflicting server name "test.com" on 0.0.0.0:80, ignored
nginx: [warn] conflicting server name "test.com" on 0.0.0.0:80, ignored
2024/05/28 00:58:35 [emerg] 1#1: open() "/www/sites/WsTest/log/access.log" failed (2: No such file or directory)
nginx: [emerg] open() "/www/sites/WsTest/log/access.log" failed (2: No such file or directory)
```

**Comment by AtlantisDe** [comment]
手动维护解决了 启动问题了.

```Shell
/opt/1panel/apps/openresty/openresty/conf/conf.d
```

进来这里，把未能成功创建的网站、刚刚创建失败的配置文件删除，再手动修改下其它网站配置文件，就恢复正常了

所以,这里操作的逻辑应该是: 当创建网站不成功,应该要把刚刚创建的站点配置文件信息进行自动化删除

细节逻辑流程 --- 需要修正吧 --- 仅仅提供你们参考

**Comment by AtlantisDe** [comment]
原本我配置是这样的 配置文件 问题 希望能在下一个版本中 进行修复, 同时希望 添加 ws 反向代理.

```yaml
server {
    listen 1000 ssl http2 ;
    server_name dem
```

停止 启动后  被自动添加这些端口,这不是我希望的.

```yaml
server {
    listen 1000 ssl http2 ; 
    listen 443 ssl http2 ; 
    listen 80 ; 
    server_name dem
```

**Comment by zhengkunwang223** [comment]
如果是在 1Panel 的配置页面增加的 会有 nginx -t 来校验是否成功
后续版本会优化 即使 OpenResty 配置失败 也能编辑配置文件
