### ISSUE TITLE
[BUG] 仪表盘对Linux挂载的硬盘无法识别

### ISSUE THREAD

**Issue by QYG2297248353** [1Panel-dev/1Panel#5174]
### 联系方式

qyg2297248353@gmail.com

### 1Panel 版本

v1.10.9-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/56836951/75432c31-f8a5-46e9-a694-727cfc1a4677)

![image](https://github.com/1Panel-dev/1Panel/assets/56836951/05d241ff-bdf2-4ca6-9cfa-d9b49b783ed6)

### 重现步骤

Linux 挂载 sda 硬盘 无法正常识别容量与大小

### 期待的正确结果

修复对不同类型磁盘的识别
![image](https://github.com/1Panel-dev/1Panel/assets/56836951/df21dee6-ea29-41e9-a168-93b1c1c6e1ec)

### 相关日志输出

```shell
[root@localhost ~]# df -l
文件系统                       1K-块      已用      可用 已用% 挂载点
devtmpfs                        4096         0      4096    0% /dev
tmpfs                        3881744         0   3881744    0% /dev/shm
tmpfs                        1552700     64044   1488656    5% /run
/dev/mapper/almalinux-root  83820544   6294152  77526392    8% /
/dev/mapper/almalinux-var   41877504   2144260  39733244    6% /var
/dev/sdb3                     983040    423632    559408   44% /boot
/dev/sdb1                     613184      7184    606000    2% /boot/efi
/dev/mapper/almalinux-home 352309172   2875296 349433876    1% /home
tmpfs                         776348        52    776296    1% /run/user/42
tmpfs                         776348       104    776244    1% /run/user/0
/dev/sda1                  488384508 157297956 331086552   33% /run/media/root/希捷 H作品
[root@localhost ~]# lsblk
NAME               MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda                  8:0    0 465.8G  0 disk 
└─sda1               8:1    0 465.8G  0 part /run/media/root/希捷 H作品
sdb                  8:16   0 465.8G  0 disk 
├─sdb1               8:17   0   600M  0 part /boot/efi
├─sdb2               8:18   0    16M  0 part 
├─sdb3               8:19   0     1G  0 part /boot
└─sdb4               8:20   0 464.2G  0 part 
  ├─almalinux-root 253:0    0    80G  0 lvm  /
  ├─almalinux-swap 253:1    0     8G  0 lvm  [SWAP]
  ├─almalinux-var  253:2    0    40G  0 lvm  /var
  └─almalinux-home 253:3    0 336.2G  0 lvm  /home
sr0                 11:0    1  1024M  0 rom  
sr1                 11:1    1  1024M  0 rom
```

**Comment by ssongliu** [comment]
反感谢反馈，麻烦提供一下这个命令输出
`df -hT -P|grep '/'|grep -v tmpfs|grep -v 'snap/core'|grep -v udev`

**Comment by QYG2297248353** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/56836951/49fb7714-6cf5-4c3f-b32d-fbfb7625b0fd)

**Comment by ssongliu** [comment]
> ![image](https://private-user-images.githubusercontent.com/56836951/334255579-49fb7714-6cf5-4c3f-b32d-fbfb7625b0fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NDg2MDAsIm5iZiI6MTcxNjk0ODMwMCwicGF0aCI6Ii81NjgzNjk1MS8zMzQyNTU1NzktNDlmYjc3MTQtNmNmNS00YzNmLWIzMmQtZmJmYjc2MjViMGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDAyMDUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YWFjMTNiOTc0MjliM2MwMWFiZDllNzA2NjFjNzUwZWVjY2NmNzdlMDdkNDU0OWM2ZWE0ZjRkNTE4MjIwZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YJiBYaOM6i1P9Q1QSuu3xuJA9pTtnHO19GBum8S9LZA)

确实有这个问题，1.10.10 版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
