### ISSUE TITLE
[FEATURE]GPU 建议增加 iGPU 信息展示

### ISSUE THREAD

**Issue by KleinerSource** [1Panel-dev/1Panel#5178]
### 1Panel 版本

1.10.9

### 请描述您的需求或者改进建议

目前只有 nvidia支持 不支持igpu(intel核显 或者arc显卡)

### 请描述你建议的实现方案

利用 intel-gpu-tools 中的 intel_gpu_top 可以显示igpu信息
加入-J参数可以直接输出json格式
![image](https://github.com/1Panel-dev/1Panel/assets/920875/f627c2a8-308e-4cac-acb7-1c260ae6bc57)

![image](https://github.com/1Panel-dev/1Panel/assets/920875/a9c74639-792b-4c26-9c83-764d38b1c9e4)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。
> 可以进入微信交流群添加 `王贺` 好友，以便后续远程适配你的环境。

**Comment by KleinerSource** [comment]
微信交流群是哪个

**Comment by ssongliu** [comment]
> 微信交流群是哪个

可以直接添加我
![image](https://github.com/1Panel-dev/1Panel/assets/73214554/f5aba64f-1204-4c5b-901c-93616415c1d3)

**Comment by wanghe-fit2cloud** [comment]
v1.10.15-lts 版本已发布。
