### ISSUE TITLE
需求：希望增加cmdb功能，能对指定主机或者主机组进行应用部署和监控

### ISSUE THREAD

**Issue by liukuo0411** [1Panel-dev/1Panel#5183]
### 1Panel 版本

v1.10.9-lts

### 请描述您的需求或者改进建议

希望增加cmdb功能，能对指定主机或者主机组进行应用部署和监控 若有版本支持，麻烦告知

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，重复需求 https://github.com/1Panel-dev/1Panel/issues/2692
