### ISSUE TITLE
[BUG]上传大文件时导致面板空间占完错误

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#5184]
### 1Panel 版本

v1.10.9-tls

### 问题描述

rocky linux8.9，挂载512GB固态，其中`/`路径70GB，剩余空间全部挂载`/home`，1panel安装在`/home`中

---

在home路径中上传一个167GB单文件，且home路径已经使用200多GB，

发现问题：
* 使用面板上传完成后，显示完成但文件并没有直接出现，刷新文件列表看到上传的文件在一点点出来（比如第一次刷新看见1GB，过一会刷新看见2GB）
* 过一会home路径所在空间全部占完（并不是立即占完的，中间有段时间），刷新面板出现错误：
  
![PixPin_2024-05-28_17-06-03](https://github.com/1Panel-dev/1Panel/assets/63288007/cd4ece53-8707-4f68-b29d-bd697b9597fd)

这个问题应该是面板处理机制导致的，先把上传的内容放在后端，然后在通过某种方法处理在前端显示，但不管是何种具体逻辑，事实上出现了占用2倍空间的问题

### 重现步骤

假设home可用空间为200GB，上传任意单个大小超过150GB的文件，就会造成这个情况

### 期待的正确结果

我们之前上传这种大文件都是本地启动nginx服务然后1panel面板打开终端通过wget下载。今天本地服务器IO繁忙，就直接这样上传了，然后出现了这个问题。

希望可用优化一下这块的逻辑，如果因为容器化原因不好修改，也应该进行必要的提示，否则导致服务器空间占满，面板连接不上，ssh也登录不上，修复就比较麻烦。

记得之前也提过类似问题issue，那时候是删除大文件但保留也出现了类似空间占满问题。

**Comment by JAINKRE** [comment]
这次幸好`/`挂载空间没有占用，使用ssh登录后查看1panel路径，验证了猜想的问题
![PixPin_2024-05-28_17-24-49](https://github.com/1Panel-dev/1Panel/assets/63288007/76c63401-b227-4b28-bab6-c476ad58707c)

**Comment by JAINKRE** [comment]
我好像明白了，不知道猜的对不对，是先分块上传，上传完成后，但是合并文件的时候，已合并的块没有同步删除，导致合并的文件体积不断增大，出现了占用2倍空间的问题。

如果是这样，我想解决就应该很容易了。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑优化大文件上传的场景。

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
