### ISSUE TITLE
[FEATURE] 支持修改计划任务的名称

### ISSUE THREAD

**Issue by mobeicanyue** [1Panel-dev/1Panel#5188]
### 1Panel 版本

v1.10.9-lts

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/81098819/b5b199df-01c1-4995-92e1-5dd31f006386)
如图 计划任务不支持修改名称，较为不便

### 请描述你建议的实现方案

支持修改计划任务名称

**Comment by wanghe-fit2cloud** [comment]
由于计划任务生成的备份文件和日志等需要与任务名称关联，如果修改任务名称，备份到第三方账户的文件等将会失去关联性。因此，目前暂不提供修改任务名称的功能。

**Comment by mobeicanyue** [comment]
可以生成内置一个 id，然后只更改显示的名称，如何

**Comment by tianyunperfect** [comment]
让我想起了当初百度的用户名不能修改的事，设计真的一言难尽

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
It reminds me of the time when Baidu’s username couldn’t be changed. The design is really hard to describe.
