### ISSUE TITLE
[BUG]安装应用时，有概率会一直卡在安装中状态

### ISSUE THREAD

**Issue by leunghope** [1Panel-dev/1Panel#5204]
### 1Panel 版本

v1.10.9-lts

### 问题描述

在应用商店安装应用时，有概率会一直卡在安装中状态，取消不了，也看不到日志。

### 重现步骤

从应用商店安装ollama-webui

### 附加信息

<img width="673" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/31916850/18531752-966b-4032-8355-90670c844cfb">
<img width="811" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/31916850/8a9743c9-a425-45d4-b3ba-0ca6740d6602">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
上述状态是在下载应用镜像，目前可以通过重启 1Panel 来实现停止应用安装的目的。

**Comment by wanghe-fit2cloud** [comment]
关于上述问题的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/785
