### ISSUE TITLE
[BUG]服务器同步时间问题

### ISSUE THREAD

**Issue by LyingDoc** [1Panel-dev/1Panel#5208]
### 1Panel 版本

1.10.9

### 问题描述

使用面板同步时间时候会出现超时情况，时而成功时而失败

### 重现步骤

需要多次才能同步成功

**Comment by wanghe-fit2cloud** [comment]
1、检查一下 1Panel 服务器与 NTP 服务器之间的网络连接，确保没有防火墙或路由器阻止 NTP 流量
2、查看一下  NTP 日志，日志文件的位置可能因操作系统不同而异，如 `/var/log/ntp.log` 或 `/var/log/syslog`
3、添加的 NTP 服务器可能负载过高或不稳定，可以尝试使用其他公共 NTP 服务器或专用 NTP 服务器

**Comment by 1265578519** [comment]
1panel是不是会自动同步时间？经常导致服务器时间不正确的现象
我怀疑是1panel自动同步导致的bug，换成阿里云试试

<img width="821" height="200" alt="Image" src="https://github.com/user-attachments/assets/e0c13ff2-ee27-4c63-a81b-280f2480b329" />

<img width="574" height="253" alt="Image" src="https://github.com/user-attachments/assets/7d85ab4e-e746-435f-8638-1af95cd66ef5" />

<img width="279" height="232" alt="Image" src="https://github.com/user-attachments/assets/98ab3a30-677c-4d34-a399-d29d4409aec8" />

<img width="422" height="153" alt="Image" src="https://github.com/user-attachments/assets/37bb2c0d-ac54-477a-ad83-1354392dc21e" />

**Comment by wanghe-fit2cloud** [comment]
可以先看下计划任务页面，确认是否已经创建了 `同步服务器时间` 类型的任务。

**Comment by 1265578519** [comment]
计划任务里面是空的，看起来是其它原因了，估计是vps云服务器的系统内置插件导致的吧
猜测是和宿主机同步，然后宿主机时间是错的，就同步到vps也错了，我想个版本把服务商内置的插件卸载看看
