### ISSUE TITLE
[FEATURE] 适配已经安装环境的主机

### ISSUE THREAD

**Issue by easydowork** [1Panel-dev/1Panel#5210]
### 1Panel 版本

适配已经安装环境的主机

### 请描述您的需求或者改进建议

非常好的项目，提个建议。对于已经安装的环境（比如我的主机已经安装了nginx mysql redis等软件），能不能做一个配置文件或者在面板里输入这些已经存在的软件目录，相当于在套个1Panel的外壳，方便管理。

### 请描述你建议的实现方案

可输入已经安装的软件目录及配置文件进行管理

**Comment by zhengkunwang223** [comment]
适配环境需要做的工作很多 也很复杂 我们暂时没有此计划
