### ISSUE TITLE
[BUG]开启防篡改后，面板会无限退出

### ISSUE THREAD

**Issue by Alexzzz2008** [1Panel-dev/1Panel#5214]
### 1Panel 版本

1.10.9

### 问题描述

开启了几个网站的防篡改，然后登陆面板做一些操作，然后就会退出面板，再登陆，自动退出面板，如此反复，
然后关闭所有防篡改，清空面板缓存，正常了

### 重现步骤

如上

**Comment by ssongliu** [comment]
感谢反馈，已知问题，可以先停一下防篡改，下个版本修复该问题

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
