### ISSUE TITLE
[BUG]SSL证书申请出错

### ISSUE THREAD

**Issue by Dearanlan** [1Panel-dev/1Panel#5217]
### 联系方式

dearanlan@gmail.com

### 1Panel 版本

v1.10.9-lts

## SSL证书申请出错，接口报错
```json
{"code":500,"message":"服务内部错误: record not found","data":null}
```

### 重现步骤

**配置如图**

![image](https://github.com/1Panel-dev/1Panel/assets/50802482/54a73be9-23c4-41d7-8768-96dc32601f10)

**报错之后，显示等待申请**

![image](https://github.com/1Panel-dev/1Panel/assets/50802482/dab09229-1914-4c5f-928f-330c171af8a6)

**日志显示为空**

![image](https://github.com/1Panel-dev/1Panel/assets/50802482/e15f2996-2fc5-490c-bf86-41b91df2b153)

**但是能够下载到证书，不过证书大小为0**

![image](https://github.com/1Panel-dev/1Panel/assets/50802482/7c9aa884-c1d7-4fee-9b49-8b9c26116329)

### 期待的正确结果

1. 能够申请证书成功
2. 能够推送到指定目录

**Comment by zhengkunwang223** [comment]
安装 openresty 了吗

**Comment by Dearanlan** [comment]
没，用的nginx😂

**Comment by zhengkunwang223** [comment]
> 没，用的nginx😂

需要安装 openresty

**Comment by Dearanlan** [comment]
好
