### ISSUE TITLE
[FEATURE]首页推荐应用显示建议

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#5220]
### 1Panel 版本

v1.10.9-lts

### 请描述您的需求或者改进建议

建议首页`推荐建议`中已经安装的应用不显示而不是设置禁用状态：
![PixPin_2024-05-30_15-04-14](https://github.com/1Panel-dev/1Panel/assets/63288007/7b336c32-9bac-4d46-be8b-12a56ecd5a1c)

或者改变一下禁用状态按钮的颜色，都是蓝色看着就怪怪的。

而且，这个推荐栏一直感觉怪怪的，像小广告墙一样，需要的应用都安装了，不需要的应用推荐也不会安装。我觉得如果换掉这块会更好，比如替换为当前服务器`计划任务`中只启用的运行状态表，比如显示下面信息会不会更好一点？

|  任务名称  |       执行周期       |    上次执行时间     | 执行状态 |
| :--------: | :------------------: | :-----------------: | :------: |
| 任务名称11 | 每隔 6小时, 00 执行  | 2024-05-30 12:00:00 |  `成功`  |
| 任务名称22 | 每周 周五 11:30 执行 | 2024-05-30 12:00:00 |  `失败`  |
| 任务名称33 |   每天 00:00 执行    | 2024-05-30 12:00:00 |  `成功`  |

这样子感觉就非常实现而且也很专业。实现难度也不大，前端渲染一下element plus虚拟表格就行

**Comment by JAINKRE** [comment]
而且现在这个显示安装或没安装的状态也不准，比如MySQL已经安装了却还显示`安装`

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
关于概览页推荐应用栏显示相关问题的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4862
