### ISSUE TITLE
[FEATURE] 希望一些面板的页面之间能够开新标签页跳转

### ISSUE THREAD

**Issue by jsznb** [1Panel-dev/1Panel#5223]
### 1Panel 版本

v1.10.9-lts

### 请描述您的需求或者改进建议

一些页面之间希望能在新标签页中跳转而不是页内跳转，只是前端的一些小改动，但是能显著提升使用体验，因为页内跳转不会保存状态，比如我终端中在某个路径执行了命令，然后要跳转到工具箱或者防火墙重启服务或者开放端口，然后还要回到终端中继续操作，但是现在这些全部是页内跳转，甚至连在新标签页中打开的选项都没有，而页内跳转到其他页面回来之后，又相当于重新打开了一遍，状态全丢失了，又要重新执行命令进到路径下，操作连贯性很差，特别是那种状态很重要的页面，比如**网站配置**跳**文件夹**之后回跳，**终端**跳**其他页面**后回跳
虽然面板实现了页内标签页，但是页内标签页不保存状态，希望这些页面默认就是在新标签页打开

### 请描述你建议的实现方案

最好最方便就是默认在新标签页中打开，状态还是很重要的，慎用页内跳转，除非页内跳转实现了状态保存

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本尝试上述优化。

**Comment by wanghe-fit2cloud** [comment]
上述问题的讨论，我们统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4596
