### ISSUE TITLE
[BUG]计划任务执行周期定时不准

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#5252]
### 1Panel 版本

v1.10.9-lts

### 问题描述

设置计划定时每隔2个小时30分钟执行一次，实际每隔2个小时就执行一次

![20240603-084527](https://github.com/1Panel-dev/1Panel/assets/63288007/036d224f-66ef-4814-8113-908fdc8444e7)

### 重现步骤

设置计划定时每隔2个小时30分钟

**Comment by ssongliu** [comment]
这里是描述不太准确，正确描述应该是 每隔 2 小时，第三十分执行，而不是每隔两个半小时执行一次。

后面版本考虑在创建时，显示出最近几次执行时间

**Comment by JAINKRE** [comment]
哦哦 原来如此！建议在后续版本提示一下创建规则的准确含义

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
