### ISSUE TITLE
[BUG]第三方应用编排更新后，在应用商店刷新不出来

### ISSUE THREAD

**Issue by cyril-cheng** [1Panel-dev/1Panel#5256]
### 1Panel 版本

v1.10.9-lts

### 问题描述

在使用 [okxlin 大佬的第三方应用商店](https://github.com/okxlin/appstore) 更新编排以后，在应用商店里刷新不出更新。

### 重现步骤

1、download 第三方商店应用；
2、更新应用列表；
2、在更新 safeline 的可升级选项中只有 newnet-6.0.1，没有6.0.1；
![image](https://github.com/1Panel-dev/1Panel/assets/49748357/aa46ed9f-1f56-47a4-9026-005856a3fbcd)
我安装的是5.6.2，不是newnet版本
![image](https://github.com/1Panel-dev/1Panel/assets/49748357/652af6f7-91c0-4be8-abcc-ba76e8fb0208)
下载的编排列表中，是有6.0.1的
![image](https://github.com/1Panel-dev/1Panel/assets/49748357/272052fd-3c11-4ac9-b2be-1bbdeade1f65)

### 期待的正确结果

能正确刷新6.0.1和latest的更新选项。

**Comment by zhengkunwang223** [comment]
已经复现，后续版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
