### ISSUE TITLE
[FEATURE] 应用可以在关闭状态下升级

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#5262]
### 1Panel 版本

1.10.9

### 请描述您的需求或者改进建议

应用是否能在关闭的情况下进行升级？
![image](https://github.com/1Panel-dev/1Panel/assets/51264840/0090a0e9-1a81-48ff-acf1-534dc0afa69d)

### 请描述你建议的实现方案

期望关闭的应用也可以升级

### 附加信息

我想升级某个应用 ，在应用关闭的情况下，我需要返回到已安装页面， 把应用启动，然后在返回到可升级页面，点击升级，感觉繁琐了(需要切换不同的页面)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
为了确保应用升级后的可用性，首先需要确保应用处于运行状态。
此外，对于需要关联其他应用（如数据库）的应用，必须确保这些关联应用处于运行状态，否则备份将失败。
