### ISSUE TITLE
[BUG]应用商店不支持外部数据库

### ISSUE THREAD

**Issue by MrJiaGe** [1Panel-dev/1Panel#5264]
### 联系方式

3060669380@qq.com

### 1Panel 版本

v1.10.9-lts

### 问题描述

安装例如GITEA应用时仅扫描应用商店安装到mysql和PGSQL，不能正确识别MariaSQL和其他通过容器/Compose启用的数据库。

### 重现步骤

应用商店安装应用（Gitea）

### 期待的正确结果

自动扫描1panel-Network网络下的3306或者按照特征/compose特征/容器特征确定是数据库类型的实例

**Comment by wanghe-fit2cloud** [comment]
添加远程数据库即可。
