### ISSUE TITLE
[BUG] 端口范围异常

### ISSUE THREAD

**Issue by QYG2297248353** [1Panel-dev/1Panel#5268]
### 联系方式

qyg2297248353@gmail.com

### 1Panel 版本

v1.10.9-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/56836951/ebbc1c3f-2ab6-4751-b329-602b3b54cdbf)

![image](https://github.com/1Panel-dev/1Panel/assets/56836951/6890fd5f-6cd6-4b92-9bc0-ff20eda03a96)

### 重现步骤

填写只能填写 1-65535
很别扭，其他设备都是0-65535，包括阿里云，腾讯云的云防火墙，所有端口显示的都是 0到65535

**Comment by wanghe-fit2cloud** [comment]
上述校验规则没有问题。在阿里云控制台添加安全组时，端口范围也校验为 1-65535，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/5287f4fe-6eac-4fef-adcf-a9e19c6fea8f)
