### ISSUE TITLE
[BUG] 概览页数据库个数统计错误

### ISSUE THREAD

**Issue by yfdoor** [1Panel-dev/1Panel#5280]
### 1Panel 版本

v1.10.9

### 问题描述

概览页面数据库统计错误，数据库只显示 mysql 的 数据库个数，不包括其他的数据库，例如：postgres 等等。。。
![image](https://github.com/1Panel-dev/1Panel/assets/32769281/67ba2fc9-8043-4deb-8d81-e8ceed5dab39)

### 重现步骤

。。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
