### ISSUE TITLE
[FEATURE] 完善 PGSQL 的功能设置页面

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#5284]
### 1Panel 版本

社区版v1.10.9-lts

### 请描述您的需求或者改进建议

发现在同样的配置下，`PGSQL` 的资源占用比 `MySQL` 更低，准备切换到 `PGSQL` 上，但是 `PGSQL` 的设置页面没有 `MySQL` 的设置完善，是否有计划将 `MySQL` 设置页面的一些配置同步到 `PGSQL` 的设置页面上

![图片](https://github.com/1Panel-dev/1Panel/assets/15864713/9e93208f-5051-4389-bfc0-7830a14d88fe)

**Comment by zhengkunwang223** [comment]
感谢建议 我们会在后续版本不断优化

**Comment by wanghe-fit2cloud** [comment]
PostgreSQL 设置相关需求的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/5037
