### ISSUE TITLE
[FEATURE]增加docker日志管理功能，如控制日志大小

### ISSUE THREAD

**Issue by maskgo68** [1Panel-dev/1Panel#5291]
### 1Panel 版本

1.10.8

### 请描述您的需求或者改进建议

docker项目日志累积过多，硬盘逐渐被占满
建议增加docker日志管理功能，如控制日志大小，自动删除日志 

### 请描述你建议的实现方案

在安装应用商店内置的应用时，就可以直接设置日志大小
在 日志审计或docker管理页 添加 日志控制 页签

### 附加信息

日积月累，overlay占用硬盘过大
`overlay          22G   19G  1.5G  93% /var/lib/docker/overlay2/f191b28146ad6c8cfb5362b27dcf3988480312c47c124c69e053640c2e59d9de/merged
`

**Comment by wanghe-fit2cloud** [comment]
已支持容器日志切割功能，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/46fcfe2e-441a-4947-afd8-f31a91e9db63)
