### ISSUE TITLE
[BUG]快照排除目录冲突

### ISSUE THREAD

**Issue by dark2star** [1Panel-dev/1Panel#5292]
### 1Panel 版本

v1.10.9-lts

### 问题描述

排除本地备份目录无效在快照时依然做进了快照： <img width="464" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/9655248/8c45cd16-150b-4135-800a-999df87eb852">
<img width="759" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/9655248/77c47ff7-fcb7-4803-a975-a521788fb38e">

当这两个选项冲突时，排除本地备份目录是无效的，页面也未给出说明。

### 重现步骤

按上述步骤复现

**Comment by dark2star** [comment]
经过排除目录的几次测试，如指定：排除本地备份目录的子目录或所有文件*，都无效，就是说做快照必须包含所有的本地备份，这么做是否有必要，我目前本地备份目录文件较多，且备份比较多，造成最后的备份文件较大，且备份和恢复速度很慢，且面板在恢复大的快照时出现了恢复不了的bug，导致不断的创建压缩文件和解压缩直到tar命令奔溃，如果命令不出错后果会造成磁盘被完全占满然后奔溃，是否有必要单独指定是否在快照时打包本地备份目录到快照？

**Comment by wanghe-fit2cloud** [comment]
统一在这里讨论：
https://github.com/1Panel-dev/1Panel/discussions/5290
