### ISSUE TITLE
[FEATURE]建议计划任务增加执行状态的详细信息

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#5293]
### 1Panel 版本

v1.10.9-lts

### 请描述您的需求或者改进建议

`计划任务`  > `xx备份任务` ， 如下：
![PixPin_2024-06-05_12-37-48](https://github.com/1Panel-dev/1Panel/assets/63288007/29480d6c-512b-4fa9-9ac4-d2b600edfae4)

问题：
* 现在报告页面显得过于空旷，只有最基础的时间信息，连备份的文件名都没有显示，当需要查询备份文件时，不容易定位文件。

建议：
1. 报告页面增加详细的信息，`成功状态`至少包括：
* 文件名
* 文件哈希
* 文件大小
* 文件保存地址：比如本地路径，用户自定义对象存储等
> 添加上述必要的备份详细信息，可以更好的定位文件和进行校验等工作

2. `失败状态`包括:
* 失败原因

3. 优化备份名称：
* 比如当前备份`/data_n_nssd1/Jainkre_Data/Docker_Data/Calibre-web`路径至Minio，备份名称`directory_data_n_nssd1_Jainkre_Data_Docker_Data_Calibre-web_20240604091500t5x5a.tar` 显得过于臃肿了，针对不同用户需求或场景，最好可以允许自定义备份名称的结构，或者指定多种备份名称结构可供选择

5. 确保备份名称的格式化统一：
* 不要随着1panel的升级随意更改备份名称。因为针对某些特定需求，比如把数据备份至本地minio，在对minio里的数据读取加密，当涉及依赖备份名的正则表达式解析实现某些功能时，如果随意更改，就会造成没必要的工作量。
> 这也是一个建议，因为最初的1panel备份文件名称和现在的不一致，希望可以始终保持格式的一致性

### 附加信息

希望1panel越做越好！

**Comment by wanghe-fit2cloud** [comment]
1、有备份文件产生的任务，在外层列表有展示具体文件信息（保留份数和具体任务相关联，不方便在报告页面展示）
2、Shell 脚本等任务是有展示脚本执行输出的，备份任务是 1Panel 后端通过 sdk 来实现，v2.x 版本支持了任务管理后，会考虑增加状态展示。
3、该需求暂不考虑支持了。
5、由于中间版本出现过bug，v1.0 至今有过一次修改备份文件名称。
> 后续版本 1Panel 也会支持备份加密的需求。
