### ISSUE TITLE
自动生成证书时，指定密钥算法不生效

### ISSUE THREAD

**Issue by TIkc9** [1Panel-dev/1Panel#5299]
### 1Panel 版本

v1.10.9-lts

### 问题描述

如图，修改密钥算法后，实际不生效，还是EC256
![image](https://github.com/1Panel-dev/1Panel/assets/17921262/cbe4fa01-7830-4714-8158-6f6b51366e3a)

### 重现步骤

必复现

**Comment by zhengkunwang223** [comment]
感谢反馈 已经复现 后续版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
