### ISSUE TITLE
没有安装docker环境时自动安装失败[BUG]

### ISSUE THREAD

**Issue by codingriver** [1Panel-dev/1Panel#5308]
### 1Panel 版本

1.10.9

### 问题描述

![IM_截圖_2024-06-05-21-23-57](https://github.com/1Panel-dev/1Panel/assets/24895796/37b45162-72aa-4a1b-9515-af6fda394bcb)

### 重现步骤

直接出现

**Comment by zhengkunwang223** [comment]
日志显示获取 docker 超时，你可以稍后再试一下，或者使用离线方式安装 docker 和 docker-compose

**Comment by blinlincom** [comment]
我也出现这个了

**Comment by wanghe-fit2cloud** [comment]
参考官方文档提供的 `其他类型脚本` 如图：
<img width="995" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/e0afe648-b198-4da5-b040-7439906662da">

https://1panel.cn/docs/installation/online_installation/

**Comment by blinlincom** [comment]
难搞哦，解决没

**Comment by blinlincom** [comment]
CentOS Linux 8 - AppStream                                                               91  B/s |  38  B     00:00
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist

[ERROR] 生成软件源缓存出错，请先确保软件包管理工具可用！
