### ISSUE TITLE
[FEATURE] 数据库绑定后无法删除

### ISSUE THREAD

**Issue by hexWars** [1Panel-dev/1Panel#531]
### 1Panel 版本

1.0.5.2

### 请描述您的需求或者改进建议

使用了应用市场里的halo2进行建站，但是在我删除了halo2容器之后，halo2数据库点击删除显示关联了应用halo2而无法删除

![image](https://user-images.githubusercontent.com/61684793/230545196-b7f00f73-eb13-466b-9047-deb467142820.png)

可否增加强制删除按钮，或者如何解除关联的提示

或者这干脆就是个需要修复的bug

**Comment by zhengkunwang223** [comment]
需要在 1panel 应用商店-已安装 里删除创建的 halo 应用

**Comment by hexWars** [comment]
OK，已经删除，感谢你们的开源贡献，建议添加提示信息
