### ISSUE TITLE
[BUG]【php环境创建】【系统快照】故障反馈

### ISSUE THREAD

**Issue by defeatedperson** [1Panel-dev/1Panel#5312]
### 联系方式

2068983900@qq.com

### 1Panel 版本

1.10.9

### 问题描述

php环境页面，显示php正常，创建php网站也正常，但应用商店提示这个php网站失败，容器页面也找不到这个php容器。

硬盘空间不足的情况下，【设置当中的快照功能】依然可以备份+还原，没有进行磁盘剩余空间检查，导致备份/还原的文件有问题，以及磁盘爆满。

### 重现步骤

【php】在php环境页面，创建php的过程中，删除正在创建的php镜像，等几分钟，就会自动出现已经被删除的php环境。这时候，去创建网站，应用商店就会提示失败错误，容器页面也找不到php容器和镜像。(并且，此时删除php环境，重新安装php，会立刻安装完成，但建站之后应用商店依然提示失败，反复尝试4次之后，才运行正常)

【快照】磁盘剩余空间不足的情况下，也会进行备份/还原操作。

### 期待的正确结果

【php】在创建镜像的时候，不能直接删除，但为了避免因为创建过程卡住导致一直创建，可以加一个计时器，30分钟后若还在创建，就提示失败并允许用户删除。对于已经创建的php环境，希望能加一个检测，确定这个php环境运行正常。

【快照】在备份之前，先确认磁盘剩余空间是否足够，并且在"快照文件"当中，加入还原之后的文件大小信息。
还原的时候，先获取还原之后的文件大小，再判断本机剩余磁盘空间是否足够，最后在进行还原操作

### 相关日志输出

```shell
服务内部错误 diskI/Oerror (4874)

还原之后的程序错误(Wordpress)
[2K1Panel-wordpress-bx2n  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to suppress this message
```

### 附加信息

php创建过程删除的原因，是因为安装时间过长，怀疑是卡住了(或者选择的源有问题)，就需要删除重装

**Comment by zhengkunwang223** [comment]
PHP 运行环境问题已经修复，下个版本发布
