### ISSUE TITLE
[FEATURE]ssl 证书续签不更新秘钥，只更新日期的一个入口

### ISSUE THREAD

**Issue by woainiee520** [1Panel-dev/1Panel#5314]
### 1Panel 版本

v1.10.1-lts

### 请描述您的需求或者改进建议

ssl 证书续签不更新秘钥，只更新日期的一个入口

### 附加信息

<img width="888" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/32295902/ff384b8e-87f7-46a7-b0d2-e32fdd69ec74">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
