### ISSUE TITLE
[FEATURE]  网站目录跳转直接跳转到  index 文件夹

### ISSUE THREAD

**Issue by zhengkunwang223** [1Panel-dev/1Panel#5316]
### 1Panel 版本

1.10.10 

### 请描述您的需求或者改进建议

https://github.com/1Panel-dev/1Panel/issues/5134
从此 Issue 中独立出来 
网站目录跳转直接跳转到 index 目录，防止其他目录被误删

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
