### ISSUE TITLE
[FEATURE] 建议网站配置文件中的 access_log 直接使用主配置文件中的格式

### ISSUE THREAD

**Issue by wangzhengkun** [1Panel-dev/1Panel#5317]
### 1Panel 版本

v1.10.10

### 请描述您的需求或者改进建议

现在的 access_log 没有使用主配置文件中的 main 配置，自行修改增加 main 之后，关闭开启会丢失 main 配置
建议直接使用 main 配置

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.10.10-lts 版本已发布。
