### ISSUE TITLE
[BUG] mysql 创建新的数据库用指定的用户名无法登录

### ISSUE THREAD

**Issue by yfdoor** [1Panel-dev/1Panel#5333]
### 1Panel 版本

1.10.9

### 问题描述

安装 mysql 8.2 后，在数据库管理界面，创建新的数据库，并设定用户名和密码。然后用数据库工具无法使用该用户名登录，提示: access denied..但是使用安装mysql 时设定的root 账户可以登录。

### 重现步骤

。。

**Comment by wanghe-fit2cloud** [comment]
进入 `容器` 页面找到 MySQL 容器，点击右侧 `终端` 按钮进入容器内部，执行 `mysql -u 用户名 -p 密码` 命令确认下是否能成功登录。

**Comment by yfdoor** [comment]
> 进入 `容器` 页面找到 MySQL 容器，点击右侧 `终端` 按钮进入容器内部，执行 `mysql -u 用户名 -p 密码` 命令确认下是否能成功登录。

一样的，还是提示 错误
![IMG_20240607_114416](https://github.com/1Panel-dev/1Panel/assets/32769281/58df3800-be5e-48c3-905b-1df7ee5a46ad)

**Comment by wanghe-fit2cloud** [comment]
在容器列表，看看一下 MySQL 容器日志吧。

**Comment by yfdoor** [comment]
> 在容器列表，看看一下 MySQL 容器日志吧。

暂时不能上网，拍个照片吧
![IMG_20240607_115948](https://github.com/1Panel-dev/1Panel/assets/32769281/8f3f72a6-e74b-4270-89c0-7b656dda0330)
