### ISSUE TITLE
[FEATURE] 希望能添加一个面板的基础路径配置

### ISSUE THREAD

**Issue by ltxhhz** [1Panel-dev/1Panel#5334]
### 1Panel 版本

v1.10.9-lts

### 请描述您的需求或者改进建议

希望添加一个关于页面基础路径的配置，方便反向代理到子路径
#5311

**Comment by zhengkunwang223** [comment]
暂时不支持 后续版本看一下要不要实现

**Comment by yinyuncan** [comment]
+1 我也遇到了这个问题，因为有多个服务器，不想配置多个域名
