### ISSUE TITLE
[FEATURE] 能否添加对riscv64架构的支持

### ISSUE THREAD

**Issue by DingliZhang** [1Panel-dev/1Panel#5338]
### 1Panel 版本

v1.10.9-lts

### 请描述您的需求或者改进建议

RISC-V作为一种开放源代码的指令集架构，近年来获得了迅速的发展和广泛的关注，特别是在高性能计算、嵌入式系统以及数据中心等领域展现出巨大的潜力和应用前景。随着越来越多的硬件厂商开始生产基于RISC-V的处理器，用户群体也在持续增长。
希望1Panel可以提供对riscv64的支持，谢谢！

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈，我们在中短期内暂无适配计划，望理解。

**Comment by libiunc** [comment]
如果需要适配riscv 我能做些什么？ 制作riscv64的docker镜像之类的？

**Comment by wanghe-fit2cloud** [comment]
已有社区用户适配了 [riscv64 架构支持](https://github.com/1Panel-dev/1Panel/pull/8369)，我们会优先在 V1 版本中集成。
