### ISSUE TITLE
优化下“日志”菜单展示

### ISSUE THREAD

**Issue by TIkc9** [1Panel-dev/1Panel#5344]
### 1Panel 版本

v1.10.10-beta.2

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/17921262/2c58cc1c-6804-437e-9653-0a72e8d79ba9)

**Comment by wanghe-fit2cloud** [comment]
请详细描述具体的优化方案。

**Comment by TIkc9** [comment]
![546f31bbe1fc4ce882cef399cc8baa9](https://github.com/1Panel-dev/1Panel/assets/17921262/a056a822-96b7-433f-ba3b-32d09b178aa5)
简单画了下  这样子展示合理点

**Comment by wanghe-fit2cloud** [comment]
目前的逻辑是：
1、面板日志（包含 3 部分）
- 操作日志
- 访问日志
- 系统日志

2、1Panel 服务器的 SSH 登录日志
3、所有网站的日志

**Comment by TIkc9** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/17921262/0d8d7291-c385-4e0a-ad1a-d9667beef69b)
我的意思是 这里的设计不美观   感觉我那种展示美观合理一些 当然 其他日志类别也可以合并进来 仅仅提个视觉美观上的建议

**Comment by wanghe-fit2cloud** [comment]
在 v2.0 版本重构时，我们可能会考虑优化这一点。
