### ISSUE TITLE
[BUG]创建网站时在“一键部署”的“已装应用”中没有列出已经安装的应用

### ISSUE THREAD

**Issue by godcop** [1Panel-dev/1Panel#5346]
### 联系方式

823300425@qq.com

### 1Panel 版本

v1.10.10-beta.2

### 问题描述

“网站”-“一键部署”-“已装应用”中无法列出已经安装的应用。实际上已经安装了许多应用，仍然无法列出。

### 重现步骤

ubuntu22.04，全新安装，docker需要手动安装，使用curl的安装命令会安装失败，手动安装docker后就没问题

### 附加信息

![1](https://github.com/1Panel-dev/1Panel/assets/18001513/6846acce-6b9c-4a36-8659-dcfce99d215a)
![2](https://github.com/1Panel-dev/1Panel/assets/18001513/99317279-b4cd-4c94-b789-cdb584c704cf)

**Comment by wanghe-fit2cloud** [comment]
1、在线安装失败的情况下，可以考虑采用 [安装包方式](https://1panel.cn/docs/installation/package_installation/) 安装
2、创建 `一键部署` 类型网站时，支持建站类型的应用。

> 也可以参考该 issue #2930
