### ISSUE TITLE
[FEATURE]建议做一个手机客户端，方便在手机上进行管理

### ISSUE THREAD

**Issue by godcop** [1Panel-dev/1Panel#5348]
### 1Panel 版本

v1.10.10-beta.2

### 请描述您的需求或者改进建议

当前的网页版在手机上样式可用，但操作极不方便，可以考虑用跨端技术做一个手机客户端（宝塔有手机客户端，比较方便）。如果官方精力有限暂不考虑自己做，建议整理下相关接口文档，由第三方自行适配。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
重复问题 https://github.com/1Panel-dev/1Panel/issues/3973
