### ISSUE TITLE
[BUG]面板首页状态监控自动刷新问题

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#5349]
### 1Panel 版本

v1.10.10-beta.2

### 问题描述

面板首页`状态`和`监控`自动刷新失效：
![11](https://github.com/1Panel-dev/1Panel/assets/63288007/c725ffac-dd60-4c9a-aeab-3e60dfdf3950)
> 录屏可以看到`监控`最后刷新时间`21:36` 实际时间`21:37` 没有实时刷新，以及`状态`信息也没有刷新

当鼠标点击面板任意地方时，可以看到又能刷新了。

### 重现步骤

浏览器打开面板首页，不操作等待几分钟

### 附加信息

浏览器 chrome最新版本

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们现在本地环境复现一下上述问题。

**Comment by ssongliu** [comment]
这里是有意这么设计的，为了节省开销。
perf: 浏览器失去焦点停止查询、节省开销 https://github.com/1Panel-dev/1Panel/pull/1256

**Comment by JAINKRE** [comment]
> 这里是有意这么设计的，为了节省开销。 perf: 浏览器失去焦点停止查询、节省开销 #1256

原来如此，但建议最好可以在设置里手动选择是否需要节省开支。定时刷新的资源开支并不是都不能接受的
