### ISSUE TITLE
[FEATURE]在应用商店安装应用时，可以支持远程MySQL服务器

### ISSUE THREAD

**Issue by panluoyant** [1Panel-dev/1Panel#5350]
### 1Panel 版本

v1.10.9-lts

### 请描述您的需求或者改进建议

尊敬的服务器管理面板开发团队：
首先，衷心感谢您开发和维护了一款功能强大且易于使用的服务器管理面板。我在使用过程中，深深感受到了您团队的专业和用心。
在此，我想提出一个小小的建议，希望能够得到您团队的关注与支持。目前，在应用商店安装应用时，仅支持连接本地安装的数据库服务器。随着我们业务的发展，我发现支持远程 MySQL 服务器连接对于我们来说是非常必要的。
建议原因：
1.灵活性和扩展性：
支持远程 MySQL 服务器可以让用户更灵活地管理和扩展数据库。尤其对于企业用户来说，能够将数据库部署在专用的数据库服务器上，而不仅仅局限于本地服务器，这将极大提高应用的扩展性和可靠性。
2.资源优化：
远程数据库服务器通常拥有更高的性能和存储能力，可以为应用提供更快的响应时间和更稳定的服务。尤其在数据量大且需要频繁访问的场景下，远程数据库能够显著提高系统的整体性能。
3.数据安全性：
通过远程 MySQL 服务器，用户可以更好地实现数据的备份和恢复，确保数据的安全性。同时，许多企业级数据库服务器具备高级的安全防护措施，能够更有效地保护数据不受未经授权的访问。
4.数据可以进行统一管理
诚挚请求：
我们诚挚地请求您团队考虑在未来的版本中加入对远程 MySQL 服务器的支持。这不仅能满足我们当前的业务需求，也能够帮助更多用户更好地利用和管理他们的数据库资源。
再次感谢您团队为我们提供了如此出色的管理面板。期待您的回复，并衷心希望这个建议能为您的产品带来更多的用户满意度和市场竞争力。
![image](https://github.com/1Panel-dev/1Panel/assets/104615547/4b33d883-2d45-4695-986b-b99091a8ed23)

### 请描述你建议的实现方案

针对远程 MySQL 服务器支持的建议，我提供以下实现方案，希望能为您团队提供一些参考。
### 实现方案：

1. **前端配置界面**：
   - **新增配置选项**：在应用商店安装界面或数据库管理设置中，新增“远程 MySQL 服务器”选项。用户可以输入远程数据库服务器的地址、端口、用户名、密码等信息。
   - **验证机制**：在用户输入配置信息后，增加一个验证按钮，允许用户在保存配置之前验证远程数据库连接是否成功。

2. **后端逻辑处理**：
   - **连接管理模块**：在后端增加一个远程数据库连接管理模块，该模块负责接收前端传来的远程数据库配置信息，并管理连接。
   - **配置存储与加密**：确保用户的远程数据库配置信息安全存储，建议使用加密方式存储敏感信息如用户名和密码。

3. **数据传输安全**：
   - **SSL/TLS 支持**：在远程数据库连接模块中，增加对 SSL/TLS 加密连接的支持，以确保数据在传输过程中的安全性。
   - **防火墙设置**：建议用户在其数据库服务器上配置防火墙，允许特定 IP 地址或子网访问数据库，增加安全性。

4. **错误处理与日志记录**：
   - **错误处理机制**：在连接远程数据库时，增加详细的错误处理机制，捕获并记录连接失败的原因（如网络问题、认证失败等）。
   - **日志记录**：记录所有连接尝试和操作日志，方便管理员在需要时进行排查和分析。

5. **文档与用户指引**：
   - **用户手册更新**：在用户手册或帮助文档中，详细说明如何配置和使用远程 MySQL 服务器，包括配置步骤、常见问题解答和注意事项。
   - **视频教程**：制作简短的视频教程，演示如何配置和使用远程数据库功能，以便用户更直观地了解和使用该功能。

### 实现步骤：

1. **需求分析与设计**：
   - 确定详细的需求和设计文档，定义前端界面修改、后端逻辑实现和数据安全策略。

2. **前端开发**：
   - 修改现有的应用安装界面，添加远程 MySQL 服务器配置选项和验证功能。

3. **后端开发**：
   - 实现远程数据库连接管理模块，处理前端传来的配置数据，并进行连接验证和数据传输。

4. **安全性测试**：
   - 对新增加的功能进行全面的安全性测试，确保数据传输和存储的安全性。
### 总结：
通过上述实现方案，我们相信能够有效满足用户对远程 MySQL 服务器支持的需求，提升产品的灵活性和用户满意度。再次感谢您团队的辛勤付出，期待能够在未来的版本中看到这一功能的实现。

### 附加信息

再次感谢1panel团队！！！

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
在当前版本中，1Panel 已支持添加远程数据库功能，并在安装应用时支持使用已添加的远程数据库，如图所示：
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/4f35575b-d01e-4483-b77c-72f7b4ab082d">
<img width="1474" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/d540d714-0ff1-4b9b-82fe-afb92871d205">
> 点击数据库列表的 `远程服务器` 按钮，即可进入添加远程数据库页面。

**Comment by panluoyant** [comment]
感谢你的解答，但是是否可以将“去安装”改为去添加，我认为去安装会引起一些误解
感谢！
![image](https://github.com/1Panel-dev/1Panel/assets/104615547/94f19f52-2424-4129-81e8-a4ae42db0fa1)

**Comment by wanghe-fit2cloud** [comment]
> 感谢你的解答，但是是否可以将“去安装”改为去添加，我认为去安装会引起一些误解 感谢！ 

经过调研，发现`去添加`跳转到对应依赖服务的远程添加页面目前无法实现。
> 暂时先关闭该 issue。
