### ISSUE TITLE
[BUG] 面板设置-安全页面错误

### ISSUE THREAD

**Issue by R0A1NG** [1Panel-dev/1Panel#5353]
### 1Panel 版本

v1.10.10-beta.2

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/66672984/82e067b1-da4a-410b-a711-ba75a99bda31)

### 重现步骤

这个版本访问

**Comment by R0A1NG** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/66672984/dd3083c0-ad0d-44fe-a409-8d0fa06df494)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
该问题已修改 https://github.com/1Panel-dev/1Panel/issues/5339 ，测试通过后会推送更新 beta 升级包。
