### ISSUE TITLE
[文件编辑器] 退出前保存提示

### ISSUE THREAD

**Issue by QingFeng-awa** [1Panel-dev/1Panel#5356]
### 1Panel 版本

1.10.9-TLS

### 请描述您的需求或者改进建议

文件编辑器在退出时,如果发现用户有没有保存的内容则进行确认是否保存所做更改。

### 附加信息

最近使用1Panel的文件编辑器比较频繁,这是我无数次不小心按到`Esc`就要重新开始才来提的issue……

**Comment by zhengkunwang223** [comment]
感谢建议，后续版本优化

**Comment by lan-yonghui** [comment]
建议退出前提示保存并关闭编辑器窗口，点击保存的时候只是做保存操作，保持窗口不变，可以操作其他文件！

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
