### ISSUE TITLE
[文件编辑器] 支持网页全屏

### ISSUE THREAD

**Issue by QingFeng-awa** [1Panel-dev/1Panel#5357]
### 1Panel 版本

1.10.9-TLS

### 请描述您的需求或者改进建议

如标题,希望文件编辑器支持网页全屏编辑。

**Comment by zhengkunwang223** [comment]
感谢建议，后续版本优化

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
