### ISSUE TITLE
[BUG]尝试多次失败，无法在线安装~

### ISSUE THREAD

**Issue by xhwsd** [1Panel-dev/1Panel#5359]
### 1Panel 版本

在线安装脚本

### 问题描述

[BUG]尝试多次失败，无法在线安装~

### 重现步骤

![QQ截图20240608100217](https://github.com/1Panel-dev/1Panel/assets/22850174/7aa5cd4c-5e6e-4601-94aa-dd8583290f1f)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1Panel 最近支持了通过安装包进行安装，该安装包内置了 docker 和 docker-compose。
如果在执行在线安装脚本时遇到 docker 安装失败的问题，可以考虑使用安装包进行安装。

参考文档：https://1panel.cn/docs/installation/package_installation/
