### ISSUE TITLE
[BUG] 登录时图形验证码校验被绕过

### ISSUE THREAD

**Issue by R0A1NG** [1Panel-dev/1Panel#5361]
### 1Panel 版本

v1.10.10-beta.4

### 问题描述

在登录页面输入多次错误账号密码后弹出图形验证码
图形验证码错误的情况下无法通过后端校验
![image](https://github.com/1Panel-dev/1Panel/assets/66672984/196cc81d-7872-412f-96ad-6726efb4b9e5)

将captchaID字段输入任意字符，captcha字段置空，即可绕过图形验证码限制
![image](https://github.com/1Panel-dev/1Panel/assets/66672984/dc690952-8feb-4739-9fba-89ac325e09da)
![image](https://github.com/1Panel-dev/1Panel/assets/66672984/a901382f-af37-4bf6-a8d7-e37a2d6da4d6)

### 重现步骤

登录请求包，将captchaID字段输入任意字符，captcha字段置空

**Comment by wanghe-fit2cloud** [comment]
需求是用户在首次登录时不输入验证码，如果存在用户名密码错误的情况，此时会强制校验验证码。
> 在 1Panel v1.0 版本发布时，是强制要求用户强制输入验证码的，但后来我们参考了社区中多数用户的建议，修改为首次登录时不再强制此操作。

经过与 CNVD 团队的讨论，暂时认为手动修改请求后输入正确登录信息返回 200 的情况并不构成安全漏洞，望理解。

**Comment by R0A1NG** [comment]
> 需求是用户在首次登录时不输入验证码，如果存在用户名密码错误的情况，此时会强制校验验证码。
> 
> > 在 1Panel v1.0 版本发布时，是强制要求用户强制输入验证码的，但后来我们参考了社区中多数用户的建议，修改为首次登录时不再强制此操作。
> 
> 经过与 CNVD 团队的讨论，暂时认为手动修改请求后输入正确登录信息返回 200 的情况并不构成安全漏洞，望理解。

所以现在的图形验证码跟没有一样吧，加个图形验证码的目的是啥呢

**Comment by yyyytawa** [comment]
> 需求是用户在首次登录时不输入验证码，如果存在用户名密码错误的情况，此时会强制校验验证码。
> 
> > 在 1Panel v1.0 版本发布时，是强制要求用户强制输入验证码的，但后来我们参考了社区中多数用户的建议，修改为首次登录时不再强制此操作。
> 
> 经过与 CNVD 团队的讨论，暂时认为手动修改请求后输入正确登录信息返回 200 的情况并不构成安全漏洞，望理解。

建议改成只要输错密码超过指定次数就直接锁定30分钟,拒绝任何登入请求.然后提示用户用1pctl手动取消锁定
