### ISSUE TITLE
[BUG] 许可证状态接口未授权访问漏洞

### ISSUE THREAD

**Issue by R0A1NG** [1Panel-dev/1Panel#5362]
### 1Panel 版本

v1.10.10-beta.4

### 问题描述

接口：/api/v1/licenses/get/status
存在许可证（专业版）
![image](https://github.com/1Panel-dev/1Panel/assets/66672984/54a944e7-0761-4942-8503-ea9c77ebfbe7)
不存在许可证（社区版）
![image](https://github.com/1Panel-dev/1Panel/assets/66672984/53175db8-5619-437b-8bd1-32f5188b6b5e)

### 重现步骤

/api/v1/licenses/get/status

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
上述接口是用于检测是否为专业版本的 GET 接口，不构成未授权访问漏洞。
> 系统需要在启动等阶段查询。
