### ISSUE TITLE
[FEATURE] 文件夹的共享功能管理

### ISSUE THREAD

**Issue by yfdoor** [1Panel-dev/1Panel#5363]
### 1Panel 版本

1.10.9

### 请描述您的需求或者改进建议

似乎 1panel 没有关于文件夹的共享管理。比如 samba 的设置之类的。。希望可以支持，thanks

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
重复问题 https://github.com/1Panel-dev/1Panel/issues/4608
