### ISSUE TITLE
[BUG]网站配置-HTTPS-启用和关闭HTTPS时生成的nginx配置错误

### ISSUE THREAD

**Issue by righthan** [1Panel-dev/1Panel#5364]
### 1Panel 版本

v1.10.9-lts

### 问题描述

在如下图的网站配置页面启用HTTPS时，自动生成的nginx配置文件错误
![image](https://github.com/1Panel-dev/1Panel/assets/87489458/963c367d-f086-4645-ad30-66cd29116290)
**1. 启用HTTPS生成的配置文件错误**
没有启用HTTPS之前，自动生成的配置文件为
```nginx
server {
    listen 2096 ; 
    ...
}
```
在面板启用HTTPS之后，配置文件变成了
```nginx
server {
    listen 2096 ; 
    listen 443 ssl http2 ; 
    listen 80 ; 
    ...
}
```
自动生成的配置是给443端口添加了ssl和http2，并且还添加了80端口，而不是在原来的2096端口配置ssl。期望的是生成如下的配置
```nginx
server {
    listen 2096 ssl http2; 
    ...
}
```
**2. 面板中关闭HTTPS后删除的配置错误**
上面生成的错误配置自动添加了不期望的443和80端口，在面板中关闭HTTPS之后，nginx配置文件只删除了listen 443 ssl http2 ，还保留了一行 listen 80未删除
```nginx
server {
    listen 2096 ; 
    listen 80;
    ...
}
```
期待的结果是
```nginx
server {
    listen 2096 ; 
    ...
}
```

### 重现步骤

1. 新建一个非80和443端口的网站
2. 在面板的网站配置中启用HTTPS，查看生成的配置文件中对监听端口的改动
3. 在面板的网站配置中关闭HTTPS，查看生成的配置文件删除的改动

**Comment by zhengkunwang223** [comment]
HTTPS 的启用逻辑在这 https://github.com/1Panel-dev/1Panel/issues/4536#issuecomment-2122161720
listen 80 确实不应该生成 我们会在后续版本优化
https 端口暂时没有好的解决方案

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
