### ISSUE TITLE
[FEATURE] 创建网站和启用 `HTTPS` 流程优化

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#5365]
### 1Panel 版本

社区版v1.10.9-lts

### 请描述您的需求或者改进建议

目前创建网站并启用 `HTTPS` 的流程是先需要创建网站，然后再去申请证书，最后才是去网站设置页面开启 `HTTPS` 访问

能否修改为
> 创建网站时能否同时勾选是否启用 `HTTPS` 选项，并且在证书不存在的时候同时能自动申请 `SSL` 证书。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑是否支持上述需求。

**Comment by Zeta-ZhaoLi** [comment]
确实，创建的时候如果能直接选择证书会方便些

**Comment by wanghe-fit2cloud** [comment]
关于优化网站启用 HTTPS 的流程，统一汇总到该 Issue #4462
