### ISSUE TITLE
[FEATURE] 网站监控支持排除 特定来源IP/本机来源IP/特定User-Agent 的记录

### ISSUE THREAD

**Issue by gggxbbb** [1Panel-dev/1Panel#5367]
### 1Panel 版本

v1.10.10-beta.5

### 请描述您的需求或者改进建议

如 Uptime Kuma和 Wordpress 等程序可能会对本机服务进行周期性的访问，这些请求被记录在访问统计和请求日志中可能导致数据失真。
![image](https://github.com/1Panel-dev/1Panel/assets/39845709/ae6fcf31-f4eb-471f-a560-f380aa34ed99)
如图所示的请求，访问"/"的来自 Uptime Kuma，访问 "/wp-corn" 的来自 wordpress，该类请求的 来源 IP/User-Agent 通常已知且固定或来自于本机，可否添加排除 特定来源IP/本机来源IP/特定User-Agent 的功能以便于在记录中排除这些内容？

### 请描述你建议的实现方案

为网站监控加入 排除 特定来源IP/本机来源IP/特定User-Agent 的记录 的功能

**Comment by zhengkunwang223** [comment]
感谢建议，后续版本支持此需求

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
