### ISSUE TITLE
1Panel 未提供已修复漏洞的最新 PHP 版本

### ISSUE THREAD

**Issue by ShangJixin** [1Panel-dev/1Panel#5368]
### 1Panel 版本

v1.10.9-lts

### 请描述您的需求或者改进建议

PHP紧急更新漏洞，可1Panel里并未提供已修复漏洞的最新版本PHP可供下载
![image](https://github.com/1Panel-dev/1Panel/assets/21075413/4a5b0e80-090d-42b1-a30d-1c1d18c84c86)
1Panel这边最新的就是8.2.15了，但修复漏洞的版本在8.2.20版本中
![image](https://github.com/1Panel-dev/1Panel/assets/21075413/d70c7e47-4c83-4868-b6e4-2b7ddf53eef2)

### 请描述你建议的实现方案

希望及时更新PHP版本的下载与更新方式

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本推送新版本。

**Comment by zhengkunwang223** [comment]
您好，受影响的漏洞是 php-cgi ，并且需要运行在 windows 平台，1panel 提供的是 php-fpm 并且只能运行在 linux ，不受影响。
