### ISSUE TITLE
[BUG] 深色模式下会导致版本无法显示

### ISSUE THREAD

**Issue by QingFeng-awa** [1Panel-dev/1Panel#5370]
### 联系方式

qingfeng@xtreme.net.cn

### 1Panel 版本

1.10.10-LTS

### 问题描述

在深色模式下'版本'会因为字体颜色为黑色导致无法被辨认。
下方图片为对比图。
![浅色模式](https://github.com/1Panel-dev/1Panel/assets/151742581/3f7afc17-a706-4447-ad32-3c8bffbb8d09)
![深色模式](https://github.com/1Panel-dev/1Panel/assets/151742581/13670afc-cbc0-443f-b71b-7ba0c956dc31)

### 重现步骤

在设置中将主题颜色切换为暗色。

### 期待的正确结果

正常来说这个字体颜色不应该是根据主题颜色自动切换为合适色么?

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
