### ISSUE TITLE
[BUG] 应用升级页面，链接点击无法跳转

### ISSUE THREAD

**Issue by hhhguany** [1Panel-dev/1Panel#5371]
### 1Panel 版本

v1.10.10-lts

### 问题描述

如图所示，这部分按钮点击后均不会正常跳转。

<img width="2197" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/12447542/8f73aaf3-9ac0-4471-920d-549d8e7e1dbf">

### 重现步骤

进入【应用商店】，【可升级】，选择具体应用点击【升级】，点击【官方网站】、【文档说明】、【开源社区】。

**Comment by zhengkunwang223** [comment]
感谢反馈 后续版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
