### ISSUE TITLE
[BUG]因为网站代号的原因  计划任务备份网站不成功

### ISSUE THREAD

**Issue by Alexzzz2008** [1Panel-dev/1Panel#5372]
### 1Panel 版本

1.10.9

### 问题描述

网站代号为  new.123.com
绑定域名为  123.com和  www.123.com
 
计划任务报告  

失败   error : exit status 1, output: cp: cannot stat '/opt/1panel/apps/openresty/openresty/conf/conf.d/123.com.conf': No such file or directory
备注   实际的conf文件是 new.123.com.conf 存在

conf文件有出入  所以备份失败

### 重现步骤

同上

**Comment by Alexzzz2008** [comment]
![微信图片_20240608215840](https://github.com/1Panel-dev/1Panel/assets/40814658/07fc44ac-e89d-4370-a6cb-ab9e22b44fcd)

**Comment by wanghe-fit2cloud** [comment]
麻烦提供一下网站列表和 `conf.d` 文件夹截图。
> 刚在本地环境未能复现问题。

<img width="1197" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/2968ca93-3e67-466a-ab76-f70a9f2b4fb3">
<img width="1194" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/aa827465-aaae-4822-afce-c6c0bcd22f82">
<img width="1028" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/5add744d-4397-4d06-8128-bd784530f7aa">
<img width="1295" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/7aee0cc0-8682-450f-909a-00232803f543">

**Comment by Alexzzz2008** [comment]
> 麻烦提供一下网站列表和 `conf.d` 文件夹截图。
> 
> > 刚在本地环境未能复现问题。
 
 

我也没复现  先关闭issue吧
