### ISSUE TITLE
[BUG]部分文件在文本编辑器中，中文显示为乱码

### ISSUE THREAD

**Issue by pzcn** [1Panel-dev/1Panel#5374]
### 1Panel 版本

1.10.10-lts

### 问题描述

更新到1.10.10-lts后，在文本管理器打开部分文件后显示为乱码，更新前能正常显示。
编码同为utf-8，有的文件正常显示，有的文件就不行

### 重现步骤

python3的logging产生的日志，中文无法正常显示

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦提供一下上述显示异常的文件，我们在本地复现一下该问题。

**Comment by pzcn** [comment]
> 感谢反馈，麻烦提供一下上述显示异常的文件，我们在本地复现一下该问题。

能否提供邮箱或者其他渠道？由于是log我不想公开发送。

尝试通过本地编辑来移除敏感内容，但是保存后再上传就正常了。同时如果我在1panel内进行编辑，保留乱码部分，然后下载到本地以后，就变成真乱码了。所以我只可以私发未修改的原文件

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈，麻烦提供一下上述显示异常的文件，我们在本地复现一下该问题。
> 
> 能否提供邮箱或者其他渠道？由于是log我不想公开发送。
> 
> 尝试通过本地编辑来移除敏感内容，但是保存后再上传就正常了。同时如果我在1panel内进行编辑，保留乱码部分，然后下载到本地以后，就变成真乱码了。所以我只可以私发未修改的原文件

理解，麻烦您将日志文件发送至 `wanghe@fit2cloud.com`，谢谢。

**Comment by pzcn** [comment]
> > > 感谢反馈，麻烦提供一下上述显示异常的文件，我们在本地复现一下该问题。
> > 
> > 
> > 能否提供邮箱或者其他渠道？由于是log我不想公开发送。
> > 尝试通过本地编辑来移除敏感内容，但是保存后再上传就正常了。同时如果我在1panel内进行编辑，保留乱码部分，然后下载到本地以后，就变成真乱码了。所以我只可以私发未修改的原文件
> 
> 理解，麻烦您将日志文件发送至 `wanghe@fit2cloud.com`，谢谢。

已发送 请查收

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
