### ISSUE TITLE
[BUG] 升级后，新装应用失败

### ISSUE THREAD

**Issue by QYG2297248353** [1Panel-dev/1Panel#5376]
### 联系方式

qyg2297248353@gmail.com

### 1Panel 版本

v1.10.10-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/56836951/741cd77b-d3d7-4264-b500-a66e4cfb191c)

### 重现步骤

升级后新装应用出现Bug

**Comment by QYG2297248353** [comment]
解决方案
手动创建 .env 文件，无需填写内容，路径与报错路径一致

**Comment by wanghe-fit2cloud** [comment]
安装的是哪款应用。
> 本地环境未能复现上述问题。

**Comment by QYG2297248353** [comment]
数据库 Postgreql和immich
