### ISSUE TITLE
Some panel menu functions are not useful, so a hidden and displayed menu function should be added, or multiple users should be given viewing permissions

### ISSUE THREAD

**Issue by 592774447** [1Panel-dev/1Panel#5380]
### 1Panel 版本

*

### 请描述您的需求或者改进建议

Some panel menu functions are not useful, so a hidden and displayed menu function should be added, or multiple users should be given viewing permissions

### 请描述你建议的实现方案

Some panel menu functions are not useful, so a hidden and displayed menu function should be added, or multiple users should be given viewing permissions

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
自定义、隐藏主菜单相关需求，统一汇总到该 issue #696
