### ISSUE TITLE
[BUG]无法安装

### ISSUE THREAD

**Issue by aimineng** [1Panel-dev/1Panel#5382]
### 联系方式

3591536127@qq.com

### 1Panel 版本

未知

### 问题描述

因为Docker，在线安装失败

### 重现步骤

-

### 期待的正确结果

-

### 相关日志输出

```shell
-
```

**Comment by panluoyant** [comment]
最近国内的docker源被墙了，请尝试更换镜像源

**Comment by zhengkunwang223** [comment]
bash <(curl -sSL https://linuxmirrors.cn/docker.sh) 试一下用这个脚本安装

**Comment by aimineng** [comment]
这样安装Docker在线安装的curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sudo bash quick_start.sh怎么办，不是还卡着

**Comment by panluoyant** [comment]
`#安装必要工具
sudo yum install -y yum-utils device-mapper-persistent-data lvm2
#添加docker源
sudo yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo`
然后再执行
sudo yum install docker-ce
待docker安装完成后，再次使用安装脚本。脚本应该会跳过安装docker，直接安装面板

**Comment by aimineng** [comment]
我是ubuntu没有yum欸

**Comment by panluoyant** [comment]
> 我是ubuntu没有yum欸

那就使用
sudo apt install docker.io
即可

**Comment by aimineng** [comment]
谢谢
