### ISSUE TITLE
[BUG]v1.10.10-lts社区版OpenResty开启反向代理后访问网站报错500

### ISSUE THREAD

**Issue by auqhjjqdo** [1Panel-dev/1Panel#5384]
### 联系方式

auqhjjqdo@qq.com

### 1Panel 版本

v1.10.10-lts

### 问题描述

自从WAF独立出来成高级功能后，OpenResty如果给网站加了反向代理且WAF是全局打开状态时，访问网站会报500错误
v1.10.10-lts之前的版本在全局关闭WAF的情况下可以恢复正常访问，但更新到v1.10.10-lts后，无论WAF是否全局开启都会报错

### 重现步骤

1.OpenResty添加反向代理
2.升级到v1.10.10-lts
3.打开网站报错500

### 相关日志输出

```shell
[error] 536#536: *1771 lua entry thread aborted: runtime error: ./waf.lua:57: bad argument #1 to 'ipairs' (table expected, got userdata)
stack traceback:
coroutine 0:
	[C]: in function 'ipairs'
	./waf.lua:57: in function 'get_website_key'
	./waf.lua:68: in function 'common_init'
	./waf.lua:212: in main chunk, client: 127.0.0.1, server: example.com, request: "GET /index HTTP/1.1", host: "127.0.0.1:1234"
```

### 附加信息

论坛有人反馈该问题但无人解决
https://bbs.fit2cloud.com/t/topic/4739
https://bbs.fit2cloud.com/t/topic/4760

**Comment by auqhjjqdo** [comment]
经排查是OpenResty新版本`1.21.4.3-3-1-focal`的问题，降级回`1.21.4.3-2-2-focal`后恢复正常

**Comment by zhengkunwang223** [comment]
好的 我们排查一下

**Comment by csthenry** [comment]
+1，同样的问题

**Comment by inkss** [comment]
me too,现在是开关与否都会出 500 错误，相同的报错。

我现在是通过注释 waf 强制取消的才正常：

```conf
#include /usr/local/openresty/1pwaf/data/conf/waf.conf; 
```

**Comment by zhengkunwang223** [comment]
1panel/openresty:1.21.4.3-3-2-focal 已发布 可以升级 
https://bbs.fit2cloud.com/t/topic/5998/4
