### ISSUE TITLE
镜像拉取失败[BUG]

### ISSUE THREAD

**Issue by aimineng** [1Panel-dev/1Panel#5387]
### 联系方式

3591536127@qq.com

### 1Panel 版本

v1.10.10-lts

### 问题描述

MySQL,Redis,phpMyAdmin安装失败，都是在应用商店下载的

### 重现步骤

-

### 期待的正确结果

-

### 相关日志输出

```shell
-
```

**Comment by zhengkunwang223** [comment]
临时解决方案  https://bbs.fit2cloud.com/t/topic/5886/14
