### ISSUE TITLE
[FEATURE]能否添加功能文件同步工具

### ISSUE THREAD

**Issue by panluoyant** [1Panel-dev/1Panel#5388]
### 1Panel 版本

v1.10.10-lts

### 请描述您的需求或者改进建议

尊敬的 1Panel 开发团队，您好！
首先，非常感谢你们开发并维护 1Panel，使其成为一个功能强大且易于使用的服务器管理面板。我希望提出一个功能请求，希望能够进一步提升 1Panel 的实用性。
在日常使用服务器管理面板的过程中，文件同步是一个非常重要的功能，它能够极大地简化多服务器间文件同步的操作，提高工作效率。目前，宝塔面板已经提供了付费功能的文件同步工具，它具有以下几个特点：

多服务器文件同步：支持多台服务器间的文件和目录同步，确保数据的一致性。
定时任务：可以设置定时任务，定期进行文件同步，避免人为操作失误。
实时同步：实时监控文件变化，并立即同步到目标服务器。
多种同步策略：支持全量同步、增量同步等多种策略，满足不同的同步需求。
我希望 1Panel 也能够考虑添加类似的文件同步工具功能。具体需求如下：
跨服务器文件同步：能够在多台服务器之间自动同步文件和目录。
同步计划：支持设置定时同步计划，自动化同步任务。
实时同步选项：提供实时同步的功能，确保数据的即时一致性。
多策略支持：提供多种同步策略，用户可以根据实际需求选择全量同步或增量同步。
界面友好：提供直观的界面，便于用户管理和监控同步任务。
这个功能将大大提升 1Panel 的实用性和用户体验，特别是对于管理多台服务器的用户来说，将能够显著提高工作效率。

### 请描述你建议的实现方案

开发一个文件同步工具，集成到1Panel中，支持在多台服务器之间同步文件和目录。主要功能包括定时同步、实时同步和多种同步策略。使用SFTP或rsync协议进行安全、高效的文件传输。
核心模块包括：
用户界面：提供任务创建、管理和查看功能。
任务调度：支持定时任务和实时文件系统监控。
文件传输：实现基于SFTP和rsync的文件同步。
日志与监控：记录同步任务执行情况，支持异常通知。
实现步骤包括需求分析、前后端开发、测试优化和文档编写，确保工具稳定、安全、易用。
以下是宝塔面板的界面截图,可以作为参考
![image](https://github.com/1Panel-dev/1Panel/assets/104615547/a083c235-02c5-4398-b966-f4799b672cdb)
![image](https://github.com/1Panel-dev/1Panel/assets/104615547/d436898a-caa0-4df3-b5bb-d6c33a9f154f)
![image](https://github.com/1Panel-dev/1Panel/assets/104615547/fb39bb2f-b402-4961-b484-935b2a78ca64)
![image](https://github.com/1Panel-dev/1Panel/assets/104615547/c2f1fa90-2d4c-469e-a836-4b8ae2436086)

**Comment by wanghe-fit2cloud** [comment]
感谢您的建议，我们会在后续版本考虑支持上述需求。
文件同步相关问题的讨论，我们统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4608
