### ISSUE TITLE
[BUG] 进程守护运行目录选择问题

### ISSUE THREAD

**Issue by percyc** [1Panel-dev/1Panel#5389]
### 联系方式

530723372@qq.com

### 1Panel 版本

v1.10.6-lts

### 问题描述

配置进程守护时候，选择目录无效
- 工具箱
- 进程守护
- 创建进程守护
- 选择目录（选择后空白，只能粘贴路径）

### 重现步骤

配置进程守护时候
- 工具箱
- 进程守护
- 创建进程守护
- 选择目录（选择后空白，只能粘贴路径）

### 期待的正确结果

选择目录后能够有正确的回填

**Comment by wanghe-fit2cloud** [comment]
需要选中目标文件夹前面的复选框，如图：
<img width="842" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/0acafb67-c121-4019-b027-e12b1c2c8908">

**Comment by percyc** [comment]
我知道了，是如果选到最后一级目录，就不能勾选了，这时候点确认，就没有结果了。
