### ISSUE TITLE
[FEATURE][网站监控] 忽略 IP

### ISSUE THREAD

**Issue by Zeta-ZhaoLi** [1Panel-dev/1Panel#5394]
### 1Panel 版本

v1.10.10-lts

### 请描述您的需求或者改进建议

建议添加一个忽略 IP 列表，现在 uptime kuma 这种监控产生的日志也会统计进去，这个是没必要进入统计数据的

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
