### ISSUE TITLE
[FEATURE]应用商店增加nsfwjs鉴黄api的自动docker部署

### ISSUE THREAD

**Issue by Zevo77** [1Panel-dev/1Panel#5395]
### 1Panel 版本

v1.10.10-lts

### 请描述您的需求或者改进建议

应用商店增加nsfwjs鉴黄api的自动docker部署
原项目地址：https://github.com/infinitered/nsfwjs

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
应用官方是否已支持容器化安装。

**Comment by Zevo77** [comment]
支持

**Comment by wanghe-fit2cloud** [comment]
> 支持

最好提供一下 docker-compose.yml 文件，更有利于后期的适配工作。

**Comment by Zevo77** [comment]
官方那边好像有
原项目地址：https://github.com/infinitered/nsfwjs

**Comment by Zevo77** [comment]
怎么样 多久能出来

**Comment by wan92hen** [comment]
我这边没有找到这个项目官方提供的 Docker 镜像。

**Comment by Zevo77** [comment]
https://cloud.tencent.com/developer/article/2076782

**Comment by wan92hen** [comment]
> https://cloud.tencent.com/developer/article/2076782

这个文章里用到的是其他用户构建的镜像，最后一次更新是三年前，看起来没有继续维护了。

**Comment by Zevo77** [comment]
那你们搞一个吧😂

**Comment by wanghe-fit2cloud** [comment]
> 那你们搞一个吧😂

经评审，我们暂无计划上架该应用，望理解。
> 可以考虑将需求提交给 [第三方应用商店](https://github.com/okxlin/appstore)。
