### ISSUE TITLE
[FEATURE] 请添加在应用商店一键安装 Discourse

### ISSUE THREAD

**Issue by ysn2382617094wsw** [1Panel-dev/1Panel#5397]
### 1Panel 版本

v1.10.10-lts

### 请描述您的需求或者改进建议

请添加在应用商店一键安装 Discourse，Discourse蛮火的，希望可以支持

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
重复 issue https://github.com/1Panel-dev/1Panel/issues/4292

**Comment by ysn2382617094wsw** [comment]
我想知道这个在未来的更新计划么？或者说哪个版本可能会上？

**Comment by mmw1984** [comment]
> 我想知道这个在未来的更新计划么？或者说哪个版本可能会上？

+1

**Comment by wanghe-fit2cloud** [comment]
应用已上架。
进入应用商店列表，点击右上角的【更新应用列表】按钮，待同步完成后即可安装应用。
