### ISSUE TITLE
[BUG] 无法升级问题，

### ISSUE THREAD

**Issue by LyingDoc** [1Panel-dev/1Panel#5398]
### 1Panel 版本

1.10,10

### 问题描述

目前出现docker无法更新，应用docker应用无法更行情况

### 重现步骤

就是yum update,升级应用

**Comment by wanghe-fit2cloud** [comment]
docker 官方提供了 [离线安装包](https://download.docker.com/linux/static/stable/x86_64/)，可以尝试使用。
应用镜像下载失败导致的无法升级问题，可以参考论坛置顶的帖子。
