### ISSUE TITLE
[BUG] v1.10.7-lts版本，在线升级后，版本没有变化 

### ISSUE THREAD

**Issue by yus1977** [1Panel-dev/1Panel#5399]
### 联系方式

yus1977@qq.com

### 1Panel 版本

v1.10.7-lts

### 问题描述

使用在线升级功能，点击“立即更新后”，界面正常显示了升级。
但升级完成后，版本没有变化 。

### 重现步骤

使用在线升级功能，点击“立即更新后”，界面正常显示了升级。
但升级完成后，版本没有变化 。

**Comment by wanghe-fit2cloud** [comment]
v1.10.7-lts 版本升级失败的临时解决方案：https://bbs.fit2cloud.com/t/topic/5579
