### ISSUE TITLE
[BUG]计划任务执行shell脚本计时问题

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#5404]
### 1Panel 版本

v1.10.10-lts

### 问题描述

创建计划任务 shell脚本 `每3小时`执行一次，实际：
* 每4小时执行一次
* 执行时间貌似建议可以在创建任务中添加提示，系统开机时间8点多，按理来说正常应该`03:10` `06:10` `09:10` 分别触发执行，但实际并没有
 > 如果按照4小时计时，等会`12:10`看一下日志验证一下

![111](https://github.com/1Panel-dev/1Panel/assets/63288007/d9c56c59-2957-4e5e-95df-374bb34de368)

### 重现步骤

创建计划任务 > shell脚本 > 执行周期 每隔3小时10分钟

**Comment by ssongliu** [comment]
感谢反馈，确实是存在这个问题，下个小版本解决。

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
