### ISSUE TITLE
网站不存在，请检查域名[BUG]

### ISSUE THREAD

**Issue by czqasngit** [1Panel-dev/1Panel#5407]
### 1Panel 版本

v1.10.5-lts

### 问题描述

访问1panel管理面板提示"网络不存在，请检查域名"
![image](https://github.com/1Panel-dev/1Panel/assets/15681141/bbbd648d-d87a-462c-9263-506d0cc177a0)

### 重现步骤

过了几天没访问就这样了，不知道怎么复现

**Comment by zhengkunwang223** [comment]
访问的域名在网站列表中吗？

**Comment by czqasngit** [comment]
> 访问的域名在网站列表中吗？

我是使用IP地址直接访问的，http://47.120.58.228/

**Comment by zhengkunwang223** [comment]
> > 访问的域名在网站列表中吗？
> 
> 我是使用IP地址直接访问的，http://47.120.58.228/

无论你是什么访问 只要这个地址不在网站列表 就会拦截
