### ISSUE TITLE
[BUG] 更新到最新版之后，Firefox 浏览器自动填充账密功能失效了

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#5410]
### 1Panel 版本

社区版v1.10.10-lts

### 问题描述

更新到最新版之后，Firefox 浏览器自动填充账密功能失效了，需要手动点按用户输入框选择

### 重现步骤

旧版本是支持直接填充的

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，刚在本地环境测试未复现上述问题。
> 可以提供一下录屏
