### ISSUE TITLE
[BUG]升级到1.10.10-lts后，计划任务不会自动实行

### ISSUE THREAD

**Issue by ZHIN** [1Panel-dev/1Panel#5414]
### 1Panel 版本

1.10.10-lts

### 问题描述

在面板右下角点击升级后，升级到1.10.10-lts后，计划任务不会执行。任务的状态是有效的，需要手动停止计划任务再开始会可以恢复定时执行
设置的计划任务执行记录，中间空了的那段是没有升级后没有执行的。
![image](https://github.com/1Panel-dev/1Panel/assets/5432462/4d7236c7-02ff-45ce-bb6c-8418df802d85)

### 重现步骤

在面板右下角提示有新版，点击升级后出现

**Comment by ssongliu** [comment]
感谢反馈，开发环境没有复现这个问题，请问是所有的计划任务都没正常执行吗？

**Comment by heyailab** [comment]
我也发现有这个问题，确实是存在

**Comment by imumu233** [comment]
> 感谢反馈，开发环境没有复现这个问题，请问是所有的计划任务都没正常执行吗？

我看了我的，发现更新后计划任务确实就没执行过了，然后昨天点开编辑直接保存，今早看记录是都开始执行了。
![屏幕截图 2024-06-12 094623](https://github.com/1Panel-dev/1Panel/assets/30177419/18455be8-9c41-4208-9826-4415512733cd)

**Comment by ZHIN** [comment]
> 感谢反馈，开发环境没有复现这个问题，请问是所有的计划任务都没正常执行吗？

是的，当时是1.10.7lts 升级到1.10.10lts

**Comment by ssongliu** [comment]
> > 感谢反馈，开发环境没有复现这个问题，请问是所有的计划任务都没正常执行吗？
> 
> 是的，当时是1.10.7lts 升级到1.10.10lts

在 1.10.10 lts 版本重启 1panel 服务，计划任务能正常执行吗？麻烦添加一下我，我远程看看。

**Comment by ZHIN** [comment]
> > > 感谢反馈，开发环境没有复现这个问题，请问是所有的计划任务都没正常执行吗？
> > 
> > 
> > 是的，当时是1.10.7lts 升级到1.10.10lts
> 
> 在 1.10.10 lts 版本重启 1panel 服务，计划任务能正常执行吗？麻烦添加一下我，我远程看看。

使用1pctl restart是正常的，仅是版本升级时出现，面板自动重新启动后出现的。抱歉，不方便远程

**Comment by JAINKRE** [comment]
这个问题我好像也遇到过，好像手动执行一次后，后续就自动执行了。

**Comment by ssongliu** [comment]
> > > 感谢反馈，开发环境没有复现这个问题，请问是所有的计划任务都没正常执行吗？
> > 
> > 
> > 是的，当时是1.10.7lts 升级到1.10.10lts
> 
> 在 1.10.10 lts 版本重启 1panel 服务，计划任务能正常执行吗？麻烦添加一下我，我远程看看。

**Comment by wzqwwq** [comment]
确实有这个问题出现

**Comment by ssongliu** [comment]
> 确实有这个问题出现

开了 3 个计划任务从 1.10.7 升级到 1.10.10，还是没能够复现。
可以提供一下日志文件吗？选择的哪种计划任务类型，执行周期写的什么？

**Comment by wzqwwq** [comment]
> > 确实有这个问题出现
> 
> 开了 3 个计划任务从 1.10.7 升级到 1.10.10，还是没能够复现。 可以提供一下日志文件吗？选择的哪种计划任务类型，执行周期写的什么？

shell的脚本，有多个计划任务，shell的都没有运行，运行周期是一天定时运行一次，别的例如选择的数据库备份运行了，更新完毕后的日志能够看到`add shelljob successfully`的日志，但是实际没有运行。

**Comment by ssongliu** [comment]
> 实

add shell job successfully 后面有没有 start cronjob entryID 这个日志

**Comment by ssongliu** [comment]
> > > 确实有这个问题出现
> > 
> > 
> > 开了 3 个计划任务从 1.10.7 升级到 1.10.10，还是没能够复现。 可以提供一下日志文件吗？选择的哪种计划任务类型，执行周期写的什么？
> 
> shell的脚本，有多个计划任务，shell的都没有运行，运行周期是一天定时运行一次，别的例如选择的数据库备份运行了，更新完毕后的日志能够看到`add shelljob successfully`的日志，但是实际没有运行。


add shell job successfully 后面有没有 start cronjob entryID 这个日志

**Comment by wzqwwq** [comment]
> > > > 确实有这个问题出现
> > > 
> > > 
> > > 开了 3 个计划任务从 1.10.7 升级到 1.10.10，还是没能够复现。 可以提供一下日志文件吗？选择的哪种计划任务类型，执行周期写的什么？
> > 
> > 
> > shell的脚本，有多个计划任务，shell的都没有运行，运行周期是一天定时运行一次，别的例如选择的数据库备份运行了，更新完毕后的日志能够看到`add shelljob successfully`的日志，但是实际没有运行。
> 
> add shell job successfully 后面有没有 start cronjob entryID 这个日志

有的

**Comment by ZHIN** [comment]
我的是访问url的任务，全部任务都不执行 周期有多个
<img width="572" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/5432462/aa32a2ac-518d-4902-8db2-e7079a175e08">
数据库备份的任务也是不执行的。
升级后，面板的日志
[2024-06-11 11:16:06] [INFO] add curl job xxxxx successful  
[2024-06-11 11:16:06] [INFO] start cronjob entryID: 13  
是有重新添加cronjob的，但是就是不执行

[2024-06-11 11:14:51] [INFO] start to handle remove expired, retain copies: 7  
[2024-06-11 11:14:51] [INFO] start to handle remove expired, retain copies: 100  
[2024-06-11 11:14:51] [INFO] start to handle remove expired, retain copies: 7  
[2024-06-11 11:14:51] [INFO] start to handle remove expired, retain copies: 7  
[2024-06-11 11:14:51] [INFO] start to handle remove expired, retain copies: 7  
[2024-06-11 11:14:53] [INFO] start to handle remove expired, retain copies: 100  
[2024-06-11 11:16:01] [INFO] start to upgrade now...  
[2024-06-11 11:16:01] [INFO] download all file successful!  
[2024-06-11 11:16:01] [DEBUG] tar zxvfC /opt/1panel/tmp/upgrade/upgrade_20240611111601/downloads/1panel-v1.10.10-lts-linux-amd64.tar.gz /opt/1panel/tmp/upgrade/upgrade_20240611111601/downloads  
[2024-06-11 11:16:02] [DEBUG] tar --warning=no-file-changed --ignore-failed-read -zcf /opt/1panel/tmp/upgrade/upgrade_20240611111601/original/db.tar.gz  --exclude db/1Panel.db-* --exclude *.sock -C /opt/1panel db  
[2024-06-11 11:16:02] [INFO] backup original data successful, now start to upgrade!  
[2024-06-11 11:16:03] [INFO] upgrade successful!  
[2024-06-11 11:16:03] [INFO] init logger successfully  
[2024-06-11 11:16:03] [INFO] init monitor db successfully  
[2024-06-11 11:16:03] [INFO] init db successfully  
[2024-06-11 11:16:03] [INFO] Migration run successfully  
[2024-06-11 11:16:03] [INFO] init cache successfully  
[2024-06-11 11:16:03] [INFO] init session successfully  
[2024-06-11 11:16:03] [DEBUG] synchronize system time with [pool.ntp.org] successful!  
[2024-06-11 11:16:06] [INFO] add curl job ***** successful  
[2024-06-11 11:16:06] [INFO] start cronjob entryID: 6  
[2024-06-11 11:16:06] [INFO] add curl job ***** successful  
[2024-06-11 11:16:06] [INFO] start cronjob entryID: 7  
[2024-06-11 11:16:06] [INFO] add curl job ***** successful  
[2024-06-11 11:16:06] [INFO] start cronjob entryID: 8  
[2024-06-11 11:16:06] [INFO] add curl job ***** successful  
[2024-06-11 11:16:06] [INFO] start cronjob entryID: 9  
[2024-06-11 11:16:06] [INFO] add curl job ***** successful  
[2024-06-11 11:16:06] [INFO] start cronjob entryID: 10  
[2024-06-11 11:16:06] [INFO] add curl job ***** successful  
[2024-06-11 11:16:06] [INFO] start cronjob entryID: 11  
[2024-06-11 11:16:06] [INFO] add database job ***** successful  
[2024-06-11 11:16:06] [INFO] start cronjob entryID: 12  
[2024-06-11 11:16:06] [INFO] add curl job ***** successful  
[2024-06-11 11:16:06] [INFO] start cronjob entryID: 13  
[2024-06-11 11:16:06] [INFO] add cutWebsiteLog job 分割日志 successful  
[2024-06-11 11:16:06] [INFO] start cronjob entryID: 14  
[2024-06-11 11:16:06] [INFO] [xpack] init db successfully  
[2024-06-11 11:16:06] [INFO] [xpack] migration run successfully  
[2024-06-11 11:16:06] [INFO] listen at https://0.0.0.0:xxxxx [tcp4]  
[2024-06-11 11:16:06] [INFO] Starting synchronization with App Store...  
[2024-06-11 11:16:06] [INFO] [AppStore] download file from https://apps-assets.fit2cloud.com/stable/1panel.json.zip  
[2024-06-11 11:16:06] [INFO] The App Store is at the latest version

**Comment by JAINKRE** [comment]
今天检查也发现了这个问题，上次是手动执行了一次，然后到现在就没有自动执行过了，这个问题很奇怪，有的时候正常有的时候不正常，好像没什么规律

![PixPin_2024-06-16_12-56-05](https://github.com/1Panel-dev/1Panel/assets/63288007/2d696d38-c42b-46b2-9afa-e3487c8ebd79)

 ---

这个问题应该是后端计时导致的，由于不熟悉go没办法帮社区查看后端实现的问题，正好我们之前用python实现过类似需求：
* 每天指定时间触发（可指定最多执行n次）
* 每隔n天指定时间触发（可指定最多执行n次）
* 每周第几天指定时间触发（可指定最多执行n次）
* 每隔n秒触发一次（可指定最多执行n次）

贴下python实现框架，这个验证过的：（唯一的问题是计时依赖系统时间）
```python
import threading
import time
import os
from loguru import logger as loguru_logger
from datetime import datetime, timedelta

def logmakedirs(log_file_path):
    """
    确保日志文件所在的目录存在
    """
    log_dir = os.path.dirname(log_file_path)
    if not os.path.exists(log_dir):
        os.makedirs(log_dir)
    return log_file_path


# 使用 loguru 自定义 sink 来处理多进程日志输出
def configure_loguru(task_name):
    log_file_path = logmakedirs(f"./log_{task_name}.log")
    loguru_logger.remove()  # 移除默认的 stderr 输出
    loguru_logger.add(log_file_path, format="{time} | {level} | {message}", level="INFO", rotation="10 MB")

class DynamicTimer:
    def __init__(self, callback=None, task_name="", max_executions=None):
        self.running = threading.Event()
        self.trigger_time = None
        self.interval_seconds = None
        self.interval_days = None
        self.weekday = None
        self.callback = callback
        self.task_name = task_name
        self.thread = None
        self.executions_left = max_executions if max_executions is not None else float('inf')

    def start(self, trigger_time=None, interval_seconds=None, interval_days=None, weekday=None):
        if self.running.is_set():
            raise RuntimeError("定时器正在运行.")
        
        self.trigger_time = self.parse_trigger_time(trigger_time)
        self.interval_seconds = interval_seconds
        self.interval_days = interval_days
        self.weekday = weekday

        self.running.set()  # 设置事件，允许线程运行
        self.thread = threading.Thread(target=self._timer_task)
        self.thread.start()

    @staticmethod
    def parse_trigger_time(trigger_time):
        if trigger_time is not None:
            try:
                return datetime.strptime(trigger_time, '%H:%M:%S').time()
            except ValueError:
                print(f"无效触发时间格式，请使用'%H:%M:%S'格式：{trigger_time}")
                return None
        return None

    def stop(self):
        self.running.clear()  # 清除事件，停止线程
        if self.thread:
            # 给线程一些时间来响应停止请求
            self.thread.join(1)
            self.running.clear()  # 清除事件，停止线程
            # 如果线程仍在运行，打印警告
            if self.thread.is_alive():
                print(f"警告：线程 {self.task_name} 未能响应停止请求！正在尝试关闭下一次触发...")
                self.running.clear()  # 清除事件，停止线程

    def _timer_task(self):
        while self.running.is_set() and self.executions_left > 0:
            next_trigger = self._calculate_next_trigger()
            print(f"{self.task_name} | 定时器下次触发：{next_trigger.strftime('%Y-%m-%d %H:%M:%S %A')}")
            delay = max(0, (next_trigger - datetime.now()).total_seconds())
            time.sleep(delay)
            if self.callback:
                if self.executions_left > 0:
                    self.callback(self.task_name)
                    self.executions_left -= 1

    def _calculate_next_trigger(self):
        now = datetime.now()
        today = now.date()

        if self.interval_seconds is not None:
            return self.calculate_next_trigger_by_seconds(now)

        if self.interval_days is not None:
            return now + timedelta(days=self.interval_days)

        if self.weekday is not None:
            return self.calculate_next_trigger_by_weekday(today)

        if self.trigger_time is not None:
            return self.calculate_next_trigger_by_time(today)

        raise ValueError('没有设置有效的触发条件')

    def calculate_next_trigger_by_seconds(self, now):
        midnight = now.replace(hour=0, minute=0, second=0, microsecond=0)
        current_seconds = (now - midnight).seconds
        next_trigger_seconds = ((current_seconds // self.interval_seconds + 1) * self.interval_seconds)
        return midnight + timedelta(seconds=next_trigger_seconds)

    def calculate_next_trigger_by_weekday(self, today):
        days_ahead = self.weekday - today.weekday()
        if days_ahead <= 0:
            days_ahead += 7
        return datetime.combine(today + timedelta(days=days_ahead), datetime.min.time())

    def calculate_next_trigger_by_time(self, today):
        trigger_date = datetime.combine(today, self.trigger_time)
        if trigger_date < datetime.now():
            trigger_date += timedelta(days=1)
        return trigger_date

if __name__ == '__main__':
    version = "v1.0.0"
    print(f"剑客公司定时器框架-多线程 {version}")

    # 定义定时器回调函数
    def task1(task_name):
        print(f"{task_name} 触发:{datetime.now()}")
        configure_loguru("task1")
        loguru_logger.info(f"{task_name} 触发: {datetime.now()}")
        loguru_logger.info(f"{task_name} 结束: {datetime.now()}")
    
    def task2(task_name):
        print(f"{task_name} 触发:{datetime.now()}")
        configure_loguru("task2")
        loguru_logger.info(f"{task_name} 触发: {datetime.now()}")
        loguru_logger.info(f"{task_name} 结束: {datetime.now()}")
    
    def task3(task_name):
        print(f"{task_name} 触发:{datetime.now()}")
        configure_loguru("task3")
        loguru_logger.info(f"{task_name} 触发: {datetime.now()}")
        loguru_logger.info(f"{task_name} 结束: {datetime.now()}")
    
    def task4(task_name):
        print(f"{task_name} 触发:{datetime.now()}")
        configure_loguru("task4")
        loguru_logger.info(f"{task_name} 触发: {datetime.now()}")
        loguru_logger.info(f"{task_name} 结束: {datetime.now()}")
    
    def task5(task_name):
        print(f"{task_name} 触发:{datetime.now()}")
        configure_loguru("task5")
        loguru_logger.info(f"{task_name} 延时2秒 触发: {datetime.now()}")
        time.sleep(2)
        loguru_logger.info(f"{task_name} 延时2秒 结束: {datetime.now()}")

    # 创建并启动定时器实例
    # 每天12:00:00触发
    TODOtimer_1 = DynamicTimer(callback=task1,task_name="每天触发任务")
    TODOtimer_1.start(trigger_time='12:00:00')
    # 每隔3天10:00:00触发
    TODOtimer_2 = DynamicTimer(callback=task2,task_name="间隔每天任务")
    TODOtimer_2.start(trigger_time='10:00:00', interval_days=3)
    # 每周一20:00:00触发
    TODOtimer_3 = DynamicTimer(callback=task3,task_name="每周触发任务")
    TODOtimer_3.start(trigger_time='20:00:00', weekday=0)
    # 每隔10秒执行一次
    TODOtimer_4 = DynamicTimer(callback=task4,task_name="间隔多次任务-1")
    TODOtimer_4.start(interval_seconds=10)
    # 每隔2秒执行一次，最多执行10次
    TODOtimer_5 = DynamicTimer(callback=task5,task_name="间隔多次任务-2", max_executions=10)
    TODOtimer_5.start(interval_seconds=2)

    try:
        while True:
            # 主线程不退出，以便观察定时任务的执行情况
            time.sleep(1)  
    except KeyboardInterrupt:
        print("捕获Ctrl+C按键，触发停止定时器线程...")
        TODOtimer_1.stop()
        TODOtimer_2.stop()
        TODOtimer_3.stop()
        TODOtimer_4.stop()
        TODOtimer_5.stop()
```

希望可以提供一些解决思路，下面是用ai翻译的go。供社区参考：

---

将上述Python代码翻译为Go语言需要考虑以下几个方面：文件操作处理、日志记录、线程管理（Go中使用goroutines而非线程）、日期/时间操作以及动态计时器逻辑。以下是将你提供的Python代码直接翻译成Go语言的示例：

首先，需要导入Go语言的标准库和第三方包：

```go
package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/sirupsen/logrus"
	"github.com/robfig/cron/v3"
)
```

然后，实现`logmakedirs`函数以确保日志文件所在的目录存在：

```go
func logmakedirs(logFilePath string) {
	logDir := filepath.Dir(logFilePath)
	if _, err := os.Stat(logDir); os.IsNotExist(err) {
		err := os.MkdirAll(logDir, os.ModePerm)
		if err != nil {
			log.Fatal(err)
		}
	}
}
```

接下来，配置日志记录器：

```go
func configureLoguru(taskName string) {
	logFile := fmt.Sprintf("./log_%s.log", taskName)
	logmakedirs(logFile)

	file, err := os.OpenFile(logFile, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0666)
	if err != nil {
		log.Fatal(err)
	}

	logrus.SetOutput(file)
	logrus.SetFormatter(&logrus.TextFormatter{
		TimestampFormat: "2006-01-02 15:04:05",
	})
	logrus.SetLevel(logrus.InfoLevel)
}
```

由于Go中没有直接与Python的`threading.Event`相对应的概念，我们使用`sync.WaitGroup`和`sync.Mutex`来替代。现在，让我们创建一个动态计时器类：

```go
type DynamicTimer struct {
	running       sync.WaitGroup
	triggerTime   time.Time
	intervalSecs  int
	intervalDays  int
	weekday       int
	callback      func(string)
	taskName      string
	executionsLeft int
}

func NewDynamicTimer(callback func(string), taskName string, maxExecutions int) *DynamicTimer {
	return &DynamicTimer{
		running:       sync.WaitGroup{},
		callback:      callback,
		taskName:      taskName,
		executionsLeft: maxExecutions,
	}
}

func (dt *DynamicTimer) Start(triggerTime string, intervalSecs int, intervalDays int, weekday int) {
	dt.running.Add(1)
	go func() {
		defer dt.running.Done()
		for dt.executionsLeft > 0 {
			nextTrigger := dt.calculateNextTrigger(triggerTime, intervalSecs, intervalDays, weekday)
			fmt.Printf("%s | 定时器下次触发：%s\n", dt.taskName, nextTrigger.Format("2006-01-02 15:04:05 Mon"))
			delay := nextTrigger.Sub(time.Now())
			if delay > 0 {
				time.Sleep(delay)
			}
			if dt.callback != nil {
				if dt.executionsLeft > 0 {
					dt.callback(dt.taskName)
					dt.executionsLeft--
				}
			}
		}
	}()
}

func (dt *DynamicTimer) Stop() {
	dt.running.Wait()
}

func (dt *DynamicTimer) calculateNextTrigger(triggerTime string, intervalSecs int, intervalDays int, weekday int) time.Time {
	now := time.Now()
	today := now.Local().Truncate(24 * time.Hour)

	if intervalSecs > 0 {
		return dt.calculateNextTriggerBySeconds(now, intervalSecs)
	} else if intervalDays > 0 {
		return now.AddDate(0, 0, intervalDays)
	} else if weekday >= 0 && weekday <= 6 {
		return dt.calculateNextTriggerByWeekday(today, weekday)
	} else if triggerTime != "" {
		return dt.calculateNextTriggerByTime(today, triggerTime)
	}

	panic("没有设置有效的触发条件")
}

// 其他计算触发时间的函数省略...
```

注意，Go中的日期/时间操作略有不同，因此需要相应地调整`calculateNextTriggerBySeconds`, `calculateNextTriggerByWeekday`, 和 `calculateNextTriggerByTime`等函数。

最后，主函数和任务函数也需要进行相应的转换：

```go
func main() {
	version := "v1.0.0"

	// 定义定时器回调函数
	task1 := func(taskName string) {
		fmt.Printf("%s 触发:%s\n", taskName, time.Now())
		configureLoguru("task1")
		logrus.Infof("%s 触发: %s", taskName, time.Now())
		logrus.Infof("%s 结束: %s", taskName, time.Now())
	}

	// 其他任务函数省略...

	// 创建并启动定时器实例
	// 每天12:00:00触发
	timer1 := NewDynamicTimer(task1, "每天触发任务", -1)
	timer1.Start("12:00:00", 0, 0, 0)

	// 其他定时器实例省略...

	// 主循环等待中断信号
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)
	<-c
	fmt.Println("捕获Ctrl+C按键，触发停止定时器线程...")

	// 停止所有定时器
	timer1.Stop()
	// 其他定时器停止调用省略...
}
```

以上就是将你的Python代码转换为Go语言的大致过程。请注意，Go语言的并发模型和错误处理方式与Python有所不同，因此在实际应用中可能需要进一步调整和优化。例如，Go中的错误处理通常通过返回错误值和使用`if err != nil`来检查错误，而不是抛出异常。此外，Go中的goroutine和channel机制提供了更强大的并发工具，可以用于构建更高效、更安全的并发程序。

**Comment by qwenode** [comment]
同样出现这个问题, 10个计划任务都没执行

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
