### ISSUE TITLE
[FEATURE]网站日志加载过慢，请优化，谢谢

### ISSUE THREAD

**Issue by Shuai-S** [1Panel-dev/1Panel#5420]
### 1Panel 版本

v1.10.10-lts

### 请描述您的需求或者改进建议

查看网站日志的时候，加载太慢了，是正序加载的，可以倒序加载不，按需加载，不需要一次性加载完

<img width="576" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/52077275/ca1056a2-271e-4e23-aed8-83ca634de00c">

### 请描述你建议的实现方案

倒序加载，按需加载，不需要一次性加载完

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
网站日志加载优化相关的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/3690
