### ISSUE TITLE
[BUG]面板设置里设置默认网卡无法生效

### ISSUE THREAD

**Issue by godcop** [1Panel-dev/1Panel#5422]
### 1Panel 版本

v1.10.10-lts

### 问题描述

![1](https://github.com/1Panel-dev/1Panel/assets/18001513/fa8d17ad-bed2-4427-80f6-d88d59d309c8)
![2](https://github.com/1Panel-dev/1Panel/assets/18001513/e3f03416-6680-4993-9c42-b12bc67be4f4)
如图，在面板设置里设置了指定网卡，但是在概览页仍然还是显示所有

### 重现步骤

刚设置时没问题，概览页能显示指定网卡，但退出后重新进入面板，概览页就又回到了显示所有，已在多台服务器上部署后存在相同的问题

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们已在本地环境复现该问题，将在近期版本中修复并推送更新。

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
