### ISSUE TITLE
[FEATURE] 增加多用户支持

### ISSUE THREAD

**Issue by QingFeng-awa** [1Panel-dev/1Panel#5426]
### 1Panel 版本

1.10.10-LTS

### 请描述您的需求或者改进建议

增加多个用户,并且支持设定谁是管理员。
管理员可以设定其它用户的访问/操作权限。

### 附加信息

建议1Panel安装时创建的用户默认设定为管理员。

**Comment by wanghe-fit2cloud** [comment]
多用户权限体系需求的讨论，统一汇总到该 issue #638
