### ISSUE TITLE
[BUG] 深色模式下，版本号看不清

### ISSUE THREAD

**Issue by 8x48** [1Panel-dev/1Panel#5428]
### 1Panel 版本

1.10.10

### 问题描述

<img width="543" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/35218536/79b6deb0-374a-421d-b156-077181c172d7">

### 重现步骤

<img width="528" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/35218536/e679739a-165c-4ace-a6a8-b929f602d9cd">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化并推送更新。

**Comment by wanghe-fit2cloud** [comment]
重复问题 https://github.com/1Panel-dev/1Panel/issues/5370
