### ISSUE TITLE
[BUG]概览页数据库数量显示为0

### ISSUE THREAD

**Issue by fxln** [1Panel-dev/1Panel#5430]
### 联系方式

fxln8@foxmail.com

### 1Panel 版本

v1.10.10-lts

### 问题描述

概览页数据库数量显示为0，可是我的PostgreSQL数据库里都有两条数据信息，我的两台服务器都是这样
![afde8e1cb144b8fc0587c64a18bb4dd](https://github.com/1Panel-dev/1Panel/assets/72055650/293849bc-00ea-4e57-aaef-2f6f6b2936b0)
![e14cc0d29f5f7c63390486c49bbdf0c](https://github.com/1Panel-dev/1Panel/assets/72055650/e252fe5d-236b-473d-b23c-fe27fc4ae6bb)

### 重现步骤

升级为v1.10.10-lts

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。我们会在后续版本优化。

**Comment by wanghe-fit2cloud** [comment]
重复问题 https://github.com/1Panel-dev/1Panel/issues/5280

**Comment by fxln** [comment]
重复问题但是版本一样，还以为修复了呢

**Comment by wanghe-fit2cloud** [comment]
是 v1.10.10 版本引入的 bug，会在下个版本修复。
