### ISSUE TITLE
[FEATURE]在面板的文件中支持预览常见文件格式

### ISSUE THREAD

**Issue by yuanmoe** [1Panel-dev/1Panel#5431]
### 1Panel 版本

 v1.10.10-lts

### 请描述您的需求或者改进建议

在面板的文件中支持预览常见文件格式，方便日常使用：
图片(JPG，PNG，WEBP，GIF，SVG 等)
音频(MP3，WMA，WAV，APE，FLAC，OGG，AAC 等)
视频(MP4，MOV，WMV，FLV，MKV，AVI 等)

### 请描述你建议的实现方案

无

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
