### ISSUE TITLE
[BUG] 新机器无法安装最新版

### ISSUE THREAD

**Issue by juukee** [1Panel-dev/1Panel#5433]
### 1Panel 版本

v1.10.10-lts

### 问题描述

安装界面无响应

### 重现步骤

以腾讯云轻量机器为例。测试了各种版本均无法正常安装运行

**Comment by wanghe-fit2cloud** [comment]
尝试一下使用安装包安装，参考文档：
https://1panel.cn/docs/installation/package_installation/
