### ISSUE TITLE
[BUG] 小部分界面优化

### ISSUE THREAD

**Issue by ChishFoxcat** [1Panel-dev/1Panel#5435]
### 1Panel 版本

v1.10.10-lts

### 面板设置
- 主题颜色：从 `亮色` 或 `暗色` 或 `跟随系统` 切换到 `黑金` 时，强调色块并未跳转到黑金上，而是继续呆在上个主题色的文字上。切换到黑金时需要再次点击黑金，强调色块才会切换到黑金上<br>
![image](https://github.com/1Panel-dev/1Panel/assets/76027184/f6d3e2ac-a6d5-4123-b2aa-972322c44f14)

### 主机
- 终端：`暗色` 或 `黑金` 主题状态下，全屏按钮呈现白块

|暗色|黑金|
|:--:|:--:|
|![image](https://github.com/1Panel-dev/1Panel/assets/76027184/c5e2875f-64db-412e-8c8f-65c927b6aaed)|![image](https://github.com/1Panel-dev/1Panel/assets/76027184/6d120980-8b09-452e-bc4c-f0868d2b091b)|

### 重现步骤

- 在专业版下，从任意主题切换到黑金
- 在暗色或黑金状态下，查看

**Comment by ssongliu** [comment]
感谢反馈，问题一在开发环境没有复现，可以录个屏看一下吗？问题二在下个小版本优化。

**Comment by ChishFoxcat** [comment]
> 感谢反馈，问题一在开发环境没有复现，可以录个屏看一下吗？问题二在下个小版本优化。


https://github.com/1Panel-dev/1Panel/assets/76027184/8dc4e5a1-b716-452d-ab9e-e569d2a1216b

因为我就买了一个授权，其他机子没黑金测不出来，虽然说不影响使用，但是注意到还是挺闹心

**Comment by ssongliu** [comment]
> > 感谢反馈，问题一在开发环境没有复现，可以录个屏看一下吗？问题二在下个小版本优化。
> 
>  QQ2024613-13624-HD.mp4 
> 因为我就买了一个授权，其他机子没黑金测不出来，虽然说不影响使用，但是注意到还是挺闹心

麻烦加一下我，我看看这个问题

![image](https://github.com/1Panel-dev/1Panel/assets/73214554/943cb637-2a11-47aa-a8bc-e5d2f3fe108e)

**Comment by ChishFoxcat** [comment]
<details>
<summary>历史内容</summary>

> > > 感谢反馈，问题一在开发环境没有复现，可以录个屏看一下吗？问题二在下个小版本优化。
> > 
> > 
> > QQ2024613-13624-HD.mp4
> > 因为我就买了一个授权，其他机子没黑金测不出来，虽然说不影响使用，但是注意到还是挺闹心
> 
> 麻烦加一下我，我看看这个问题
> 
> ![image](https://private-user-images.githubusercontent.com/73214554/339229524-943cb637-2a11-47aa-a8bc-e5d2f3fe108e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNTg1NTEsIm5iZiI6MTcxODI1ODI1MSwicGF0aCI6Ii83MzIxNDU1NC8zMzkyMjk1MjQtOTQzY2I2MzctMmExMS00N2FhLWE4YmMtZTVkMmYzZmUxMDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA1NTczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMmRhMjQ5NTkwMWU2NGY3MTcyNGE5ODIyNDI2YzA1OWRhNTVkYWQ1YzAwY2UxYzFjMGRiZjFjMTE3M2Q1MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R_wdBc2zRk3qF_M4Iyt6N-Y8FKzG91CDG_4nGaFOTSk)
</details>

加上了

**Comment by ChishFoxcat** [comment]
哦对，还有登录页面是不会生效主题的吗，后续会打算吗

**Comment by wanghe-fit2cloud** [comment]
> 哦对，还有登录页面是不会生效主题的吗，后续会打算吗

由于登录页面的背景和图片都是亮色，不太适合暗色和黑金配色，所以就先不进行适配了。

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
