### ISSUE TITLE
[FEATURE]排序问题

### ISSUE THREAD

**Issue by KleinerSource** [1Panel-dev/1Panel#5437]
### 1Panel 版本

1.10.10

### 请描述您的需求或者改进建议

建议 网站域名列表  WAF 网站设置 网站监控等地方 的网站列表 按照 名称顺序排列 而不是添加顺序
这样方便查找  而且建议 所有可排序的项目 记忆排序逻辑 每次 切换页面回来 又得重新排序.

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
