### ISSUE TITLE
[BUG]所有的应用，安装后，容器会新增一个无关联的默认网络

### ISSUE THREAD

**Issue by adams549659584** [1Panel-dev/1Panel#544]
### 1Panel 版本

1.1.0

### 问题描述

1.1.0 及后续的安装应用时，都会新增一个无关联的默认网络
![image](https://user-images.githubusercontent.com/10492939/230733313-4d5fd623-f85c-4d11-b6e5-59a2d6170839.png)

### 重现步骤

1.1.0 之后的版本直接安装都可以重现，安装时容器名称使用大写字母也会报错

### 期待的正确结果

正常安装，移除无关网络

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在 v1.1.0 版本正式发布前修复该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.1.0 版本已发布。
