### ISSUE TITLE
[BUG] 使用域名：端口网站 日志显示异常

### ISSUE THREAD

**Issue by R0A1NG** [1Panel-dev/1Panel#5441]
### 1Panel 版本

v1.10.10-lts

### 问题描述

使用非标准端口的域名，伪造IP访问后，日志显示异常

![image](https://github.com/1Panel-dev/1Panel/assets/66672984/5612e89d-c163-45dc-bc59-a9d587112c64)
![image](https://github.com/1Panel-dev/1Panel/assets/66672984/73794999-3566-4047-97b7-dde352c5b340)

### 重现步骤

使用非标准端口的域名伪造IP访问

**Comment by zhengkunwang223** [comment]
感谢反馈 已复现 后续版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
