### ISSUE TITLE
[FEATURE] 网站日志支持管理任何一个nginx的日志文件

### ISSUE THREAD

**Issue by maasengit** [1Panel-dev/1Panel#5444]
### 1Panel 版本

 v1.10.9-lts

### 请描述您的需求或者改进建议

支持打开一个nginx运行日志文件或错误日志文件

### 请描述你建议的实现方案

界面上设置日志文件的路径

**Comment by zhengkunwang223** [comment]
是要打开其他 nginx 的日志文件吗？

**Comment by maasengit** [comment]
对，1panel能够管理其他nginx的日志和配置文件是一个很好的功能

**Comment by zhengkunwang223** [comment]
> 对，1panel能够管理其他nginx的日志和配置文件是一个很好的功能

工作量大 要适配的情况太多 暂时不会考虑
