### ISSUE TITLE
[BUG]应用商店中的Focalboard应用默认参数部署失败

### ISSUE THREAD

**Issue by wan92hen** [1Panel-dev/1Panel#5456]
### 1Panel 版本

v1.10.10

### 问题描述

![1cee13e48f6bc1d244a35d46b9b9434](https://github.com/1Panel-dev/1Panel/assets/27671436/fc965d56-0004-4f97-b49e-892ec5750f54)
容器挂载了 ./data/data 目录，但实际没有这个目录。

### 重现步骤

使用默认配置参数可以直接部署成功。

**Comment by wanghe-fit2cloud** [comment]
已修复。
请进入 `应用商店` 列表，点击右上角的 `更新应用列表` 按钮。同步成功后，再来安装应用。
