### ISSUE TITLE
[BUG] 群晖系统重启Docker报错  stderr: Failed to restart docker.service: Unit docker.service failed to load: No such file or directory.

### ISSUE THREAD

**Issue by YaKun9** [1Panel-dev/1Panel#5462]
### 1Panel 版本

v1.10.10-lts

### 问题描述

 stderr: Failed to restart docker.service: Unit docker.service failed to load: No such file or directory.
 
通过终端执行 `systemctl status docker` 显示不存在这个服务。群晖系统的docker容器服务名不是 docker

我通过查找 docker关键词，锁定群晖的 服务名应该是 `pkg-ContainerManager-dockerd.service` 。

建议做个兼容哈。

我的设备是 DS920+，系统是群晖的DMS 7.2

```shell

sudo systemctl status docker
Password: 
● docker.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

systemctl list-unit-files --type=service | grep docker
pkg-ContainerManager-dockerd.service                     static        

systemctl status pkg-ContainerManager-dockerd.service
● pkg-ContainerManager-dockerd.service - Docker Application Container Engine
   Loaded: loaded (/usr/local/lib/systemd/system/pkg-ContainerManager-dockerd.service; static; vendor preset: disabled)
   Active: active (running) since Wed 2024-06-12 10:56:59 CST; 2 days ago
     Docs: https://docs.docker.com
 Main PID: 21029 (dockerd)

```

### 重现步骤

同问题描述

### 期待的正确结果

也就是说群晖系统的 ContainerManager 套件，也就是Docker，默认的服务名不是 docker，而是 `pkg-ContainerManager-dockerd.service` 期望做一下兼容

**Comment by YaKun9** [comment]
```
uname -a
Linux DS920plus 4.4.302+ #69057 SMP Fri Jan 12 17:02:28 CST 2024 x86_64 GNU/Linux synology_geminilake_920+
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
由于目前精力有限，我们将在后续版本中单独适配群晖。相关问题的讨论，我们将统一汇总到该 issue: https://github.com/1Panel-dev/1Panel/issues/4004

**Comment by YaKun9** [comment]
@wanghe-fit2cloud 

通过创建一个别名可以暂时解决这个问题

```
sudo vim /etc/systemd/system/docker.service


添加以下内容

[Unit]
Description=Docker Service Alias
After=network.target

[Service]
Type=oneshot
ExecStart=/bin/systemctl start pkg-ContainerManager-dockerd.service
ExecStop=/bin/systemctl stop pkg-ContainerManager-dockerd.service
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target

最后重启

sudo systemctl daemon-reload
sudo systemctl enable docker.service
sudo systemctl start docker.service


```

这样就可以了，但是有一个问题，你们的超时时间有点短，执行docker重启，尤其是运行的容器比较多的时候，是会超时的。
这个跟群晖关系不大，其他系统如果容器过多应该也有这个问题。这个命令超时时间总可以优化一下吧。我这个解决方案你们也可以参考一下。

**Comment by YaKun9** [comment]
不过这个倒也无所谓，反正不影响主流用户  @wanghe-fit2cloud

**Comment by YaKun9** [comment]
自己 fork 了一份去适配解决了
[https://github.com/YaKun9/1Panel_For_Synology](https://github.com/YaKun9/1Panel_For_Synology)

**Comment by iwhisper1011** [comment]
> 自己 fork 了一份去适配解决了 https://github.com/YaKun9/1Panel_For_Synology

适配的有什么改进呢，黑群可以用吗918

**Comment by YaKun9** [comment]
> > 自己 fork 了一份去适配解决了 https://github.com/YaKun9/1Panel_For_Synology
> 
> 适配的有什么改进呢，黑群可以用吗918

不确定黑群是否可以使用，仅在自己的白群920+使用过。主要修改了docker操作使用的服务。其他都是同步主分支更新
