### ISSUE TITLE
[FEATURE]面板监控主机硬件温度及实现

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#5465]
### 1Panel 版本

v1.10.10-lts

### 请描述您的需求或者改进建议

希望1panel可以集成对主机硬件的监控，主要是各个硬件的参数。这样就可以直接了解服务器各个核心运行的状态，没必要总是远程登录bmc查看了

### 请描述你建议的实现方案

现在我们通过脚本的方法实现，但是各个参数展现不是很直观，希望可以考虑集成到面板中，以下是具体实现方法：

## 实现
1. 安装：`lm-sensors` 针对不同系统：
```shell
sudo apt-get install lm-sensors # Debian/Ubuntu
sudo yum install lm_sensors    # CentOS/RHEL
sudo dnf install lm_sensors    # Fedora
```
2. 加载传感器模块：
```shell
sudo sensors-detect
```
> 首次运行需要设置启动的传感器
4.查看温度：
```shell
sensors
```
5.查看磁盘温度，安装smartmontools：
```shell
sudo apt-get install smartmontools # Debian/Ubuntu
sudo yum install smartmontools     # CentOS/RHEL
sudo dnf install smartmontools     # Fedora
```
6.查看指定磁盘温度：
```shell
sudo smartctl -A /dev/sdb | grep Temperature
```
7.定期更新传感器支持：
```shell
sudo sensors-detect --auto
```

## 参数
1.查询硬件温度：
```shell
[root@LocalServer-A02 ~]# sensors
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +52.0°C  (high = +80.0°C, crit = +100.0°C)
Core 0:        +52.0°C  (high = +80.0°C, crit = +100.0°C)
Core 1:        +52.0°C  (high = +80.0°C, crit = +100.0°C)

acpitz-virtual-0
Adapter: Virtual device
temp1:        +27.8°C  (crit = +105.0°C)
temp2:        +29.8°C  (crit = +105.0°C)

nouveau-pci-0100
Adapter: PCI adapter
GPU core:     +0.91 V  (min =  +0.80 V, max =  +1.19 V)
temp1:        +39.0°C  (high = +95.0°C, hyst =  +3.0°C)
(crit = +105.0°C, hyst =  +5.0°C)
(emerg = +135.0°C, hyst =  +5.0°C)
```
说明：
* coretemp-isa-0000: 这部分显示的是CPU的温度信息，具体来说是Intel处理器的温度。Adapter: ISA adapter表示这是一个通过ISA总线适配器连接的传感器，但实际上这里的描述可能是默认的，因为现代系统很少使用ISA总线。

* Package id 0:  表示整个CPU封装的温度，这里是+52.0°C。
* Core 0: 表示CPU的第一个核心的温度，同样是+52.0°C。
* Core 1: 表示CPU的第二个核心的温度，依然是+52.0°C。
这里的high和crit值分别表示警告温度和临界温度。如果温度达到high值，系统会发出警告；如果达到crit值，则可能会触发更严重的响应，如自动关机，以防止硬件损坏。

* acpitz-virtual-0: 这部分显示的是与ACPI（Advanced Configuration and Power Interface）相关的温度信息，通常反映的是主板或其他非CPU组件的温度。

* temp1: 显示为+27.8°C，这可能代表主板或某个芯片的温度。
* temp2: 显示为+29.8°C，可能代表另一个主板区域或组件的温度。
同样的，这里也有一个crit值，表示如果温度超过+105.0°C，系统可能会采取紧急措施。

* nouveau-pci-0100: 这部分显示的是NVIDIA图形卡的温度和电压信息。
* Adapter: PCI adapter表明这是通过PCI总线连接的传感器。

* GPU core: 显示GPU核心的电压，这里是+0.91V，同时给出了电压的最小值和最大值。
* temp1: 显示GPU的温度，这里是+39.0°C，同样有high、crit和emerg值，分别表示警告、临界和紧急温度。

2.查询硬盘温度
```shell
[root@LocalServer-A02 ~]# sudo smartctl -A /dev/sdb | grep Temperature
194 Temperature_Celsius     0x0022   047   047   000    Old_age   Always       -       47 (Min/Max 32/54)
```
说明：
* 194 Temperature_Celsius：这是SMART属性的ID号，表示当前硬盘的温度属性。
* 0x0022：这是属性的标志位，用于标识该属性的类型和状态。具体含义依赖于SMART标准，但通常包含了是否支持预警、是否可恢复、是否可预测故障等信息。
* 047：这是属性值（Value），在这个上下文中，这个数值并不直接对应温度值，而是反映了与健康状况相关的评分。在这个例子中，评分为47，通常情况下，数值越接近100越好。
* 047：这是最差值（Worst），即自上次重置以来记录的最低分数。同样地，这个数值也反映了硬盘健康状况的评分。
* 000：这是阈值（Threshold），当属性值低于这个阈值时，系统会认为存在潜在的故障风险。
* Old_age：这是属性的有效性，表明此属性随时间自然变化，而不是由于故障引起的。
* Always：这表示属性是否在设备运行时持续监测。
* -：这通常表示没有附加信息。
* 47 (Min/Max 32/54)：这部分直接给出了硬盘的实际温度，即47°C。括号中的32/54分别代表自硬盘启动以来记录的最低温度和最高温度。

---

以上只是获取cpu、存储、显卡等温度，这些参数具有普遍适用性。其他参数因为不同机器硬件不同适配会比较麻烦，可以不考虑

**Comment by wanghe-fit2cloud** [comment]
感谢大佬建议。
服务器硬件（如 CPU、主板温度等）需求的讨论，统一汇总到该 issue #1614
