### ISSUE TITLE
[FEATURE]建议添加批量反代、复制已有反代、添加ipv6监听开关等功能

### ISSUE THREAD

**Issue by sq113** [1Panel-dev/1Panel#547]
### 1Panel 版本

v1.0.5

### 请描述您的需求或者改进建议

建议添加批量反代(或者复制现有反代修改),添加ipv6监听开关,能在创建网站时可以直接开启HTTPS

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已支持添加批量反代功能。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本将支持用户在面板设置中绑定监听IP。

**Comment by wanghe-fit2cloud** [comment]
> 在创建网站时可以直接开启HTTPS

近期版本还是需要用户在创建完网站后手动设置 HTTPS，望理解。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
