### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by phris** [1Panel-dev/1Panel#5470]
### 1Panel 版本

v1.10.10

### 请描述您的需求或者改进建议

什么时候可以支持API密钥啊？有些操作希望通过API接口和我们现有内部系统连接在一起

**Comment by phris** [comment]
看这个issue里面，去年已经在计划中，但是目前还是没有API密钥：https://github.com/1Panel-dev/1Panel/issues/1046

**Comment by wanghe-fit2cloud** [comment]
在下半年进行v2.0版本重构期间，我们可能会优先考虑。
