### ISSUE TITLE
[BUG]安装phpmyadmin时，出现了异常

### ISSUE THREAD

**Issue by Subdue0** [1Panel-dev/1Panel#5471]
### 联系方式

1374700812@qq.com

### 1Panel 版本

v1.10.10-lts

### 问题描述

查看phpmyadmin日志，显示暂无日志。

### 重现步骤

只要安装就会显示异常

### 相关日志输出

```shell
查看phpmyadmin日志，显示暂无日志。
```

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/32565151/6dcb3225-9180-480b-91b5-3ca4624fbfad)

**Comment by wanghe-fit2cloud** [comment]
进入 `容器` - `配置` 页面，添加镜像加速，要确保应用镜像能正常拉取成功。
