### ISSUE TITLE
[FEATURE]复制文件、解压文件会刷新文件的时间戳

### ISSUE THREAD

**Issue by hoshi-fx** [1Panel-dev/1Panel#5474]
### 1Panel 版本

v1.10.10-lts

### 请描述您的需求或者改进建议

![20240616122301](https://github.com/1Panel-dev/1Panel/assets/107205460/debc9932-ef17-48ba-b3b0-b77e8e6f2778)
前几天把东西搬到1panel的时候发现，解压压缩包，复制文件，会直接刷新文件的“修改时间”，能不能保留原始的“修改时间”呢？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述功能。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。

**Comment by hoshi-fx** [comment]
> [v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
@zhengkunwang223 @wanghe-fit2cloud 
我升级后问题还存在哦

**Comment by zhengkunwang223** [comment]
> > [v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
> 
> @zhengkunwang223 @wanghe-fit2cloud 
> 
> 我升级后问题还存在哦

需要你在主机上装一下zip依赖

**Comment by hoshi-fx** [comment]
> > > [v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
> > 
> > 
> > @zhengkunwang223 @wanghe-fit2cloud
> > 我升级后问题还存在哦
> 
> 需要你在主机上装一下zip依赖

好的谢谢 解决了
