### ISSUE TITLE
[BUG]http网站串到https网站

### ISSUE THREAD

**Issue by clover1420** [1Panel-dev/1Panel#5476]
### 联系方式

748883120@qq.com

### 1Panel 版本

v1.10.10-lts

### 问题描述

网站开启https其中一个不开，访问没开启https的网站会串到开了https的网站。

### 重现步骤

创建多个网站打开https其中一个网站不打开https，访问没打开https的网站。

### 期待的正确结果

没打开https的网站能正常访问。

**Comment by zhengkunwang223** [comment]
是不是浏览器缓存的原因？无痕模式打开看看

**Comment by clover1420** [comment]
> 是不是浏览器缓存的原因？无痕模式打开看看

用无痕模式打开还是一样的。

**Comment by MiderWong** [comment]
#### 测试结果
经过测试，场景没有复现，**建议楼主排查域名DNS服务商的设置**，比如说Cloudflare中有一个强制http转为https的设置，如下图所示：
![image](https://github.com/1Panel-dev/1Panel/assets/7487008/cd757c29-5ac5-4436-8fdb-d4f89b30f10f)


#### 测试过程
##### 测试Ⅰ
本地自定义域名xxx.local.test，域名历史没有任何证书，本地也没申请该域名的证书，直接使用 “快速访问” 按钮，跳转的是`HTTP`
##### 测试Ⅱ
1、真实域名，域名申请了通配符证书，但是没申请该二级域名证书，也没开启过https，直接使用 “快速访问” 按钮，跳转的是`https`，并且会提示"域名不存在"，证书和提示内容如下：
![证书列表](https://github.com/1Panel-dev/1Panel/assets/7487008/cbbaf7e9-bae0-488d-b5d5-b98d80d20c53)
![HTTPS访问提示](https://github.com/1Panel-dev/1Panel/assets/7487008/aeadf5d3-3d60-40fe-9c98-53a278db81ca)
2、**手动在浏览器把https协议改为http协议**，成功访问http站点
3、上一步骤执行成功后**再点击“快速访问” 按钮，成功跳转至`http`协议**，正常访问http站点，具体效果如下：
![HTTP网站列表](https://github.com/1Panel-dev/1Panel/assets/7487008/0f0cad7d-c196-4a43-8771-3cae13e15867)
![HTTP访问效果](https://github.com/1Panel-dev/1Panel/assets/7487008/a2067abb-d3c4-4402-ac63-3f33675dfac3)
