### ISSUE TITLE
[FEATURE] 应用商店增加Harbor容器镜像服务

### ISSUE THREAD

**Issue by jason-fit2cloud** [1Panel-dev/1Panel#5477]
### 1Panel 版本

v1.10.10

### 请描述您的需求或者改进建议

应用商店增加Harbor容器镜像服务

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
由于 Harbor 应用涉及多个容器，通过 1Panel 应用商店安装和后续更新维护不便，建议通过 `容器` 菜单来创建编排。
