### ISSUE TITLE
[BUG]关于docker ce无法更新问题

### ISSUE THREAD

**Issue by LyingDoc** [1Panel-dev/1Panel#5478]
### 1Panel 版本

1.1.10

### 问题描述

中国不是关闭了docker镜像了，无法更新

### 重现步骤

这有什么解决方案，现在很困扰

**Comment by wanghe-fit2cloud** [comment]
应用商店拉取镜像，参考：
https://bbs.fit2cloud.com/t/topic/5886

服务器全新安装 1Panel，参考：
https://1panel.cn/docs/installation/package_installation/
