### ISSUE TITLE
[BUG] 文件功能打开文件中文显示乱码

### ISSUE THREAD

**Issue by Shuai-S** [1Panel-dev/1Panel#5481]
### 1Panel 版本

v1.10.10-lts

### 问题描述

<img width="975" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/52077275/409d468c-ad36-4f4f-8bce-4a717b7870bc">

### 重现步骤

<img width="975" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/52077275/87665c72-6eca-4fbc-8bfd-f2f6ded5aac8">

### 期待的正确结果

希望显示正确的中文

**Comment by zhengkunwang223** [comment]
重复 https://github.com/1Panel-dev/1Panel/issues/5374
