### ISSUE TITLE
[BUG] SFTPGo样式显示异常

### ISSUE THREAD

**Issue by youngledo** [1Panel-dev/1Panel#5487]
### 1Panel 版本

最新版本

### 问题描述

样式显示异常
<img width="1420" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/68590897/1426d94c-1260-4435-8458-406986981b70">

### 重现步骤

应用商店安装的即可复现

**Comment by wanghe-fit2cloud** [comment]
可以尝试更换其他浏览器或者清除浏览器缓存再试一次（在本地环境安装后未复现上述问题）。
> 如果问题依然存在，建议反馈给应用官方。
