### ISSUE TITLE
[BUG]升级应用时勾选备份在已安装页面的备份列表中不出现，只能在本地/opt/1panel/backup找到

### ISSUE THREAD

**Issue by Xalaok** [1Panel-dev/1Panel#5492]
### 1Panel 版本

1.10.10-lts

### 问题描述

在应用商店的可升级页面升级应用时勾选“升级前备份应用”可以成功备份，但只能在本地/opt/1panel/backup找到，在已安装页面的备份列表中不会出现

### 重现步骤

升级应用时勾选备份，再到已安装页面的同个应用的备份列表查看，备份记录为空

### 期待的正确结果

在已安装页面的备份列表中出现升级该应用时勾选备份所产生的备份记录

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/74130512/9bf18106-7eac-46e4-9068-b67c511a91fb)
![image](https://github.com/1Panel-dev/1Panel/assets/74130512/28231ed6-9717-4564-9f07-81437ac2d5eb)
![image](https://github.com/1Panel-dev/1Panel/assets/74130512/446ccaea-cbad-4fbd-a08e-8d15baf89314)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述功能。

**Comment by wanghe-fit2cloud** [comment]
在 `已安装` 列表点击 `备份` 按钮，如图：
<img width="1475" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/2d2b5a30-c821-45bb-be09-5a7612b21ee0">
