### ISSUE TITLE
[FEATURE] 应用商店emlog安装增加MariaDB支持

### ISSUE THREAD

**Issue by SCX-snow** [1Panel-dev/1Panel#5495]
### 1Panel 版本

1.10.10-lts

### 请描述您的需求或者改进建议

emlog项目标记可以使用MariaDB 10.3及以上作为数据库，但1panel应用商店只支持使用MySQL安装，虽然可以自行安装docker版但毕竟不如官方支持更加方便，希望能在emlog安装选项中添加MariaDB选项。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
已完成更新。可以进入应用商店，点击右上角的【更新应用列表】按钮，待同步完成后即可在安装 emlog 应用时选择 MariaDB 数据库。
