### ISSUE TITLE
[BUG] 404 频率拦截设置白名单无效

### ISSUE THREAD

**Issue by wangzhengkun** [1Panel-dev/1Panel#5499]
### 1Panel 版本

v1.10.10-lts

### 问题描述

设置了 IP 白名单 但还是被 404 频率拦截了

### 重现步骤

设置了 IP 白名单，然后访问可以触发 404 的 URL

**Comment by zhengkunwang223** [comment]
感谢反馈 后面版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
