### ISSUE TITLE
[FEATURE] 为部分的功能增加代理服务器

### ISSUE THREAD

**Issue by ChishFoxcat** [1Panel-dev/1Panel#5506]
### 1Panel 版本

v1.10.10-lts

### 网站
- 证书：申请证书增加代理连接

每次申请都跟玄学一样的，时好时坏。
![image](https://github.com/1Panel-dev/1Panel/assets/76027184/14508e43-dc33-42ce-a608-d439a33ff949)

### 容器
- 配置：基础配置增加代理服务器

### 请描述你建议的实现方案

在 DockerCE v23.0 版本后，`daemon.json` 已支持添加代理
> 原文: https://docs.docker.com/config/daemon/systemd/

### Container 代理
```json
{
  "proxies": {
    "http-proxy": "http://proxy.example.com:3128",
    "https-proxy": "https://proxy.example.com:3129", 
    "no-proxy": "*.test.example.com,.example.org,127.0.0.0/8"
  }
}
```

### Dockerd 代理
1.  为服务创建 systemd 插入目录：`docker`
```
sudo mkdir -p /etc/systemd/system/docker.service.d
```
2. 创建一个名为添加环境变量的文件：`/etc/systemd/system/docker.service.d/http-proxy.conf`
```
[Service]
Environment="HTTP_PROXY=http://proxy.example.com:3128"
Environment="HTTPS_PROXY=https://proxy.example.com:3129"
Environment="NO_PROXY=localhost,127.0.0.1,docker-registry.example.com,.corp"
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

1. 当前版本需要手动设置 Docker 代理，后续版本将支持自动配置 Docker 设置。
2. 关于申请证书代理，我们将调研 Lego 的支持情况。

**Comment by wanghe-fit2cloud** [comment]
第2点，关于申请证书使用代理服务器的需求，汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/7059

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。

**Comment by upn369** [comment]
家庭服务器呢？建议直接在1p面板里做个代理设置，有需要上外网的时候就设置链接到局域网临时用下。

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
What about home servers? It is recommended to make proxy settings directly in the 1p panel. When you need to access the external network, set up a link to the LAN for temporary use.
