### ISSUE TITLE
[FEATURE]希望应用商店增加Screego屏幕共享项目

### ISSUE THREAD

**Issue by RebellionAQG** [1Panel-dev/1Panel#5515]
### 1Panel 版本

1.10.10-lts

### 请描述您的需求或者改进建议

希望应用商店增加Screego屏幕共享项目，这个工具能非常方便的提供用户屏幕分享功能，用户之前协同工作时会经常用到屏幕分享功能

### 请描述你建议的实现方案

官方GitHub项目地址：https://github.com/screego/server
官方文档：https://screego.net/#/
官方提供的docker部署文档：https://screego.net/#/install?id=docker

**Comment by zhengkunwang223** [comment]
感谢建议 我们先调研一下

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
