### ISSUE TITLE
[FEATURE] 应用商店Gitea求更

### ISSUE THREAD

**Issue by stardemo** [1Panel-dev/1Panel#5516]
### 1Panel 版本

v1.10.10-lts

### 请描述您的需求或者改进建议

应用商店Gitea求更，新版的优化了CI相关的功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在新版本适配成功后推送更新。

**Comment by QYG2297248353** [comment]
第三方应用商店

https://github.com/QYG2297248353/appstore-1panel

Gitea 支持更多配置，优化部分配置
你值得拥有🥰

**Comment by stardemo** [comment]
v1.10.13-lts 还没有更新

**Comment by wanghe-fit2cloud** [comment]
> v1.10.13-lts 还没有更新

是由于 Gitea 官方还未将最新版本推送至 `gitea.cn/gitea/gitea` 仓库

**Comment by stardemo** [comment]
没有使用gitea.com的镜像么😂

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: wanghe ***@***.***>
发送时间: Wednesday, August 14, 2024 2:35:22 PM
收件人: 1Panel-dev/1Panel ***@***.***>
抄送: star liu ***@***.***>; Author ***@***.***>
主题: Re: [1Panel-dev/1Panel] [FEATURE] 应用商店Gitea求更 (Issue #5516)


v1.10.13-lts 还没有更新

是由于 Gitea 官方还为推送最新版本到 gitea.cn/gitea/gitea 仓库

**Comment by wanghe-fit2cloud** [comment]
Gitea 最新版本已经上架到应用商店。
点击应用商店右上角的【更新应用列表】按钮，等待同步完成后即可安装该版本。

**Comment by stardemo** [comment]
<img width="576" alt="image" src="https://github.com/user-attachments/assets/b45076bb-6ce7-4de7-98f5-ec6fe2757676">
换成了EE企业版？

**Comment by wanghe-fit2cloud** [comment]
> <img alt="image" width="576" src="https://private-user-images.githubusercontent.com/20634646/367573610-b45076bb-6ce7-4de7-98f5-ec6fe2757676.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDY5NDgsIm5iZiI6MTcyNjQwNjY0OCwicGF0aCI6Ii8yMDYzNDY0Ni8zNjc1NzM2MTAtYjQ1MDc2YmItNmNlNy00ZGU3LTk4ZjUtZWM2ZmUyNzU3Njc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDEzMjQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlOTMxYzU5MjM1NTZiZTc0YTJhMDBhMjNiZTFmNzU2MmNiZTAyNjBlZGU0MmIxMmE1YWJiYjkzZWFjOGU1NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.czhaHJeKhtE6olsSope6HqFgyCLRfuDpOfT942Ope90"> 换成了EE企业版？

1Panel 商店中提供的依然是专业版，之前的版本也是专业版镜像，本次更新更换了仓库地址。

**Comment by wanghe-fit2cloud** [comment]
该版本与社区最新版保持一致。在不导入 License 的情况下，功能与社区版相同。
不过，EE 版的 iFix 发布频率更高，缺陷修复也更及时。
此外，如果需要导入 License 进行试用，也可以无缝切换，无需替换镜像。
