### ISSUE TITLE
[BUG]安装 MaxKB，无法拉取镜像

### ISSUE THREAD

**Issue by mfanoffice** [1Panel-dev/1Panel#5520]
### 联系方式

yumin.fan@fit2cloud.com

### 1Panel 版本

v1.10.10-lts

### 问题描述

安装 MaxKB，无法拉取镜像，看报错返回的IP是美国的
![图片](https://github.com/1Panel-dev/1Panel/assets/48307752/8eead86d-ba06-48de-86be-16f0ec38cfc7)

### 重现步骤

安装MaxKB 即可复现

### 期待的正确结果

希望在国内搭建 1panel 镜像库

**Comment by wanghe-fit2cloud** [comment]
参考：https://bbs.fit2cloud.com/t/topic/5886
