### ISSUE TITLE
[BUG] 容器编排 UI 逻辑问题

### ISSUE THREAD

**Issue by Anyexyz** [1Panel-dev/1Panel#5523]
### 联系方式

anyexyz@foxmail.com

### 1Panel 版本

v1.10.10-lts

### 问题描述

在 `容器` - `编排` - `创建编排`，编辑后点击确认会开始部署，此时有两个按钮 `取消`，`确认`，此时再按确认会重新执行 `docker-compose up` 操作（也就是说确认按钮的逻辑没变），这里的逻辑是不是有点问题。

### 重现步骤

如上

### 期待的正确结果

应该是第一个确认是保存编辑的 compose 文件，第二次点击确认是进行部署，同时展示日志。

### 附加信息

![0edec7fdae7c23f5608395ab0673d71](https://github.com/1Panel-dev/1Panel/assets/53684988/3ba20209-bdcb-458c-a387-92d25b927b3c)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化编排创建逻辑。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
