### ISSUE TITLE
[BUG] 一键部署,  不要填写名称 (直接选择PHP版本)

### ISSUE THREAD

**Issue by Alexzzz2008** [1Panel-dev/1Panel#5526]
### 1Panel 版本

1.10.10

### 问题描述

一键部署,  不要填写名称 (直接选择PHP版本)
并且  如果是一键部署 没办法切换PHP版本

### 重现步骤

1

**Comment by wanghe-fit2cloud** [comment]
> 一键部署, 不要填写名称。

由于名称作为应用编排的标识，且需遵循特定规则，因此仍需用户手动输入。

> 并且 如果是一键部署 没办法切换PHP版本

只有建站类型的应用支持一键部署。
如果要创建 PHP 网站，需要选择运行环境。
