### ISSUE TITLE
[BUG] 主题无法自动切换主题

### ISSUE THREAD

**Issue by QingFeng-awa** [1Panel-dev/1Panel#5527]
### 联系方式

qingfeng@xtreme.net.cn

### 1Panel 版本

1.10.10-LTS

### 问题描述

主题无法自动跟随系统切换深浅色主题。
在`1.10.10LTS`版本之前是可以正常切换的,并且是实时的(只要切换主题1Panel就会立即跟随),但在新版本这个功能似乎是失效了,并且刷新也不能更新,需要到设置里主动切换主题颜色模式才会更新。

### 重现步骤

将1Panel主题颜色设置为`跟随系统`,随后在Windows设置中切换`色彩模式`。

### 期待的正确结果

1Panel可以正常随系统色彩模式自动切换主题颜色。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。刚在本地环境已复现该问题，我们会在近期版本修复并推送更新。

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
