### ISSUE TITLE
[BUG]在宝塔中已经安装了mysql和mongodb，但是在应用商店中检测不到他们的存在

### ISSUE THREAD

**Issue by 13531446481** [1Panel-dev/1Panel#5529]
### 1Panel 版本

v1.10.10-lts

### 问题描述

在宝塔中已经安装了mysql和mongodb，但是在应用商店中检测不到他们的存在

### 重现步骤

打开1panel的应用商店，打开宝塔的应用商店，可以看见宝塔里面是有mysql和mongodb，但是1panel里面没有

**Comment by 9a6c** [comment]
哥们，你看看你这是在说什么？

**Comment by 0xddy** [comment]
逗乐了

**Comment by panluoyant** [comment]
宝塔安装的是直接在系统上安装，并非容器，而这个面板大部分依托容器

**Comment by panluoyant** [comment]
所以检查不出并非BUG，如果想添加MySQL服务器到1panel，请添加远程服务器至127.0.0.1:3306
