### ISSUE TITLE
[FEATURE] Nginx 的编译问题 

### ISSUE THREAD

**Issue by 0xddy** [1Panel-dev/1Panel#5531]
### 1Panel 版本

v1.10.10-lts

### 请描述您的需求或者改进建议

目前openresty镜像环境里面基础的模块都有了，但是如果想编译第三方的，没有相关的教程，无法找到Nginx源码位置，能否在面板上设置一些外部编译的模块安装。然后就是比如 看到 ngx_http_geoip_module 是动态编译模块，但是真的找不到 ngx_http_geoip_module.so 在哪里....  这方面的文档是否能完善细致一些。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
OpenResty 编译相关问题的讨论，我们统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/3283

**Comment by 0xddy** [comment]
@wanghe-fit2cloud  感觉该问题优先级比较高，没有提供完善的傻瓜式操作，也没有提供详细的文档让人手动diy，却是实际阻拦替换宝塔到1panel 非常大的阻碍。

**Comment by wanghe-fit2cloud** [comment]
> @wanghe-fit2cloud 感觉该问题优先级比较高，没有提供完善的傻瓜式操作，也没有提供详细的文档让人手动diy，却是实际阻拦替换宝塔到1panel 非常大的阻碍。

该需求我们会在 v2.0 版本重构期间优先考虑（近期开始 v2.0 的技术方案调研）。
