### ISSUE TITLE
[FEATURE]建议支持站点模式切换

### ISSUE THREAD

**Issue by KleinerSource** [1Panel-dev/1Panel#5532]
### 1Panel 版本

1.10.10

### 请描述您的需求或者改进建议

目前的情况是 如果建站的时候选了 反代 之后想改成 静态 或者 运行环境 就只能删除 重建

### 请描述你建议的实现方案

建议支持切换 或者 将所有模式的选项都集中到一起 让用户选择是否启用
例如 静态和运行环境中都包含 反代 都可以实现反代功能
 运行环境也可以跑静态。但是反过来就不行了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
网站类型转换相关功能的讨论，统一汇总到该 issue #2532
