### ISSUE TITLE
[BUG]php似乎装不上maxminddb扩展？

### ISSUE THREAD

**Issue by miaowmint** [1Panel-dev/1Panel#5534]
### 1Panel 版本

1.10.10

### 问题描述

为php添加了maxminddb扩展，但是在php里看不到这个扩展

![image](https://github.com/1Panel-dev/1Panel/assets/58991169/2b1e42ff-8ff2-49df-bea8-28f9e160f010)

![image](https://github.com/1Panel-dev/1Panel/assets/58991169/02812b86-6c17-4fb6-abe4-4f57741fcffd)

### 重现步骤

我尝试了8.2和8.1都是不好使的

**Comment by zhengkunwang223** [comment]
感谢反馈 我们先在本地环境复现一下

**Comment by zhengkunwang223** [comment]
已复现 后续版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
