### ISSUE TITLE
[FEATURE]创建反向代理时如协议为HTTPS默认启用回源SNI

### ISSUE THREAD

**Issue by unknown-o** [1Panel-dev/1Panel#5535]
### 1Panel 版本

1.10.10

### 请描述您的需求或者改进建议

部分网站回源时会验证SNI，如SNI不匹配可能导致反向代理失败（502）
![image](https://github.com/1Panel-dev/1Panel/assets/51825113/4fffc03e-4e6f-4cd4-ba79-588a5c520cac)

### 请描述你建议的实现方案

创建反向代理配置文件时，如协议为https，默认开启SNI，即在反代配置文件中加入proxy_ssl_server_name on;

**Comment by zhengkunwang223** [comment]
此配置非所有网站都需要 所以默认增加此配置可能不是一个好主意

**Comment by unknown-o** [comment]
> 此配置非所有网站都需要 所以默认增加此配置可能不是一个好主意

是否可以作为高级设置中的开关呢？因为部分网站确实会验证sni
