### ISSUE TITLE
[BUG] 在 VMware 中，配置镜像后，应用商店里的 openresty 一直在安装中

### ISSUE THREAD

**Issue by paul-tanwh** [1Panel-dev/1Panel#5536]
### 1Panel 版本

v1.10.10-lts

### 问题描述

在 VMware 中，配置镜像后，应用商店里的 openresty 一直在安装中。在 【容器】-【镜像】 中可以可以快速拉取，例如 openresty/openresty:1.25.3.1-4-focal

### 重现步骤

正常操作步骤安装就会出现

**Comment by zhengkunwang223** [comment]
安装中就是在拉取镜像
