### ISSUE TITLE
[BUG] 私有仓库已经在服务器登录过了，通过1Panel页面创建容器依然提示报错: 请输入账密..

### ISSUE THREAD

**Issue by gowy222** [1Panel-dev/1Panel#5537]
### 1Panel 版本

v1.10.10-lts

### 问题描述

整个服务器底层环境已经登录私有docker和git仓库了(长期token那种), 正常在ssh里面docker pull push都不需要帐密了, 在/containers/container UI页面创建容器 输入私有docker镜像地址，会确认会报错 需要提供账密... 我记得老版本没有这个bug得,..

### 重现步骤

ssh链接服务器,
docker login XXX先登录到私有的仓库

然后在1panel得/containers/container UI页面创建容器 -> 容器地址 -> 手动:输入下私有镜像地址 -> 确定 就会报错要账密得dialog..

### 期待的正确结果

服务器ssh底层登录过私有仓库了, 1Panel这边单纯docker pull 不应该异常还需要账密..

**Comment by zhengkunwang223** [comment]
感谢反馈 我们先在本地复现一下

**Comment by wanghe-fit2cloud** [comment]
将私有仓库添加到 `容器` - `仓库` 中，然后进入 `镜像` 页面拉取镜像是否成功。

**Comment by gowy222** [comment]
> 将私有仓库添加到 `容器` - `仓库` 中，然后进入 `镜像` 页面拉取镜像是否成功。

这样可以，但是服务器装机部署的时候，和1Panel一样，
都是通过sh脚本统一部署的(一般在面板安装完毕之后，统一部署docker网络网段 加速源和私有仓库token)。
所以, 除非每次部署每次都人工一个个在UI录入, 否则大多情况还是会选择sh脚本一键登录私有仓库...
毕竟批量管理多个服务器还是统一远程脚本方便..

**Comment by wanghe-fit2cloud** [comment]
> > 将私有仓库添加到 `容器` - `仓库` 中，然后进入 `镜像` 页面拉取镜像是否成功。
> 
> 这样可以，但是服务器装机部署的时候，和1Panel一样， 都是通过sh脚本统一部署的(一般在面板安装完毕之后，统一部署docker网络网段 加速源和私有仓库token)。 所以, 除非每次部署每次都人工一个个在UI录入, 否则大多情况还是会选择sh脚本一键登录私有仓库... 毕竟批量管理多个服务器还是统一远程脚本方便..

1Panel 是调用的后端 Golang SDK。
我们在后续版本调研一下是否能兼容本地已有的登录配置。

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
