### ISSUE TITLE
[FEATURE]应用商店增加harbor

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#5539]
### 1Panel 版本

v1.10.10-lts

### 请描述您的需求或者改进建议

最近国内docker镜像全部被封了，建议上架这个应用，可以提供企业级的私有镜像管理同步等功能：
* GitHub：https://github.com/goharbor/harbor

我们用了一段时间，感觉非常棒，比docker官方的Registry好很多，建议社区考虑支持。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
由于 Harbor 应用涉及多个容器，通过 1Panel 应用商店安装和后续更新维护不便，建议通过 `容器` 菜单来创建编排。
