### ISSUE TITLE
[BUG]文件解压编码问题

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#5540]
### 1Panel 版本

v1.10.10-lts

### 问题描述

解压`tar.gz`后文本编码错误：
![PixPin_2024-06-23_17-52-59](https://github.com/1Panel-dev/1Panel/assets/63288007/bc2c8b48-09a2-4204-b192-f8a062ad5914)

### 重现步骤

该文件是个js文件，通过gitlab源码下载，在gitlab中正常（全部默认utf8）

![PixPin_2024-06-23_18-04-07](https://github.com/1Panel-dev/1Panel/assets/63288007/57c747e7-ee67-48b5-af5e-9ed51d79ddaf)

1panel中解压该文件，中文乱码，而且乱码写死了，vscode打开也没办法修改：
![PixPin_2024-06-23_18-05-51](https://github.com/1Panel-dev/1Panel/assets/63288007/1ef8ef11-210f-46b8-99bf-c42d2645320f)

### 期待的正确结果

* 修复乱码问题（目前测试，`zip`、`tar.gz`全部会乱码）
* 1pane自带的编辑器可以支持`选择编码`

**Comment by JAINKRE** [comment]
问题应该是用的编辑器导致的，本地上传utf8文件，编辑器一打开就乱码了

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
已知问题，我们会在近期版本修复该问题 https://github.com/1Panel-dev/1Panel/issues/5374
