### ISSUE TITLE
应用升级失败，原来的容器被删掉

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#5550]
### 1Panel 版本

v1.10.10-lts

### 问题描述

应用升级失败，原来的容器被删掉

### 重现步骤

升级应用

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本修复该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.11 版本已发布。
