### ISSUE TITLE
[FEATURE]运行环境缺失

### ISSUE THREAD

**Issue by Subdue0** [1Panel-dev/1Panel#5558]
### 1Panel 版本

v1.10.10-lts

### 请描述您的需求或者改进建议

我选择了php环境，但是我在php环境中又调用了bash脚本、python脚本，但是这个php是在一个容器中运行的，这个容器只是简易的busybox加php环境，并没有bash环境和python环境，这样的话，就无法正常运行项目。

### 请描述你建议的实现方案

有没有集成了多种语言的运行环境使用呢？我使用了本地运行环境，但是配置上有诸多问题，目前找不到合适的解决方法。

**Comment by wanghe-fit2cloud** [comment]
- PHP 扩展相关问题，可以参考：
https://bbs.fit2cloud.com/t/topic/5201
https://bbs.fit2cloud.com/t/topic/2073

- 运行环境需求的讨论，统一汇总到该 issue #748
