### ISSUE TITLE
[FEATURE] 增加API输出1panel的各项信息，或者提供一个集成所有1panel主机信息的统一hub

### ISSUE THREAD

**Issue by beijingtl** [1Panel-dev/1Panel#5567]
### 1Panel 版本

v1.10.10-lts

### 请描述您的需求或者改进建议

当前的1panel是针对单个主机进行管理和运维，但当主机多了，尤其是跨机房、跨集群场景下，依靠工程师人工查看每个机器的1panel是不可行的。是否可以提供一个能够统一查看或者输出所有1panel主机信息的方式，便于在一个地方统一查看和管理所有集群？

### 请描述你建议的实现方案

实现该方式有2种方案：
1. 提供1panel接口，在接口中输出常见的单个服务器的信息。最开始可以先做查看类接口（比如查看主机性能、进程、各项日志等），后期可以按资源再开发增、删、改接口。这样，通过输出1panel的能力，由工程师做二次开发实现统一集群监控和管理（另，jumpserver可以统一集群管理，但缺少1panel这种详细的监控以及各项运维的功能）。
2. 提供统一的1panel hub，通过在一台机器上安装一个hub，来统一从各个1panel主机上调取、查看信息，以及分发管理任务。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在 v2.0 版本支持多主机管理。

**Comment by wanghe-fit2cloud** [comment]
多主机管理相关需求的讨论，统一汇总到该 issue [#2692](https://github.com/1Panel-dev/1Panel/issues/2692)
