### ISSUE TITLE
[FEATURE]备份应用计划任务支持多选应用或排除应用

### ISSUE THREAD

**Issue by wan92hen** [1Panel-dev/1Panel#5570]
### 1Panel 版本

v1.10.10-lts

### 请描述您的需求或者改进建议

创建备份应用类型的计划任务时，目前只支持选择全部应用或单选某个应用。当总应用较多，大部分想定时备份，个别不需要备份时，只能创建多个计划任务实现。
希望可以支持多选应用或者排除应用。

### 请描述你建议的实现方案

可以考虑以下两种方案：
1. 在当前应用选择的基础上，支持下拉多选，可以一次性选择多个应用进行备份；
2. 额外增加排除应用配置项，配合选择全部应用使用。

**Comment by wanghe-fit2cloud** [comment]
备份类型计划任务支持多选的需求，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/3720
