### ISSUE TITLE
[BUG] 急需将应用恢复到原有状态

### ISSUE THREAD

**Issue by QYG2297248353** [1Panel-dev/1Panel#5574]
### 联系方式

qyg2297248353@gmail.com

### 1Panel 版本

v1.10.10-lts

### 问题描述

v1.10.10-lts 回退到 v1.10.9-lts，再通过Web面板升级到 v1.10.10-lts
![image](https://github.com/1Panel-dev/1Panel/assets/56836951/790911af-eed4-4cc2-990a-fbe3abc36171)
全部失败，我需要恢复到正常状态，容器中应用确实存在，只是容器名称不一致

### 重现步骤

v1.10.10-lts 回退到 v1.10.9-lts，再通过Web面板升级到 v1.10.10-lts

### 期待的正确结果

拯救所有应用，重装参数都不知道，打开参数报错

**Comment by zhengkunwang223** [comment]
你是在哪修改的容器名称呢？

**Comment by QYG2297248353** [comment]
整件事情是 v1.10.9-lts  升级到 v1.10.10-lts 后，我发现部分应用都变成了失败，那没办法，我只能卸载重装。后续又遇到 不能指定.env的情况，没办法想卸载重装，但是你们命令行提示，会删除所有服务与数据，那只好退回上一个版本用的命令行工具：
```sh
1pctl restore
```
回到 v1.10.9-lts 然后，登录面板，我就直接升级到 v1.10.10-lts，打开应用面板就全部提示失败，但是我去容器里搜索应用名称，容器里面全部都存在，比对了一下，都是应用名称结尾不一样

**Comment by zhengkunwang223** [comment]
> 整件事情是 v1.10.9-lts 升级到 v1.10.10-lts 后，我发现部分应用都变成了失败，那没办法，我只能卸载重装。后续又遇到 不能指定.env的情况，没办法想卸载重装，但是你们命令行提示，会删除所有服务与数据，那只好退回上一个版本用的命令行工具：
> 
> ```shell
> 1pctl restore
> ```
> 
> 回到 v1.10.9-lts 然后，登录面板，我就直接升级到 v1.10.10-lts，打开应用面板就全部提示失败，但是我去容器里搜索应用名称，容器里面全部都存在，比对了一下，都是应用名称结尾不一样

重建应用试过吗

**Comment by QYG2297248353** [comment]
> > 整件事情是 v1.10.9-lts 升级到 v1.10.10-lts 后，我发现部分应用都变成了失败，那没办法，我只能卸载重装。后续又遇到 不能指定.env的情况，没办法想卸载重装，但是你们命令行提示，会删除所有服务与数据，那只好退回上一个版本用的命令行工具：
> > ```shell
> > 1pctl restore
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 回到 v1.10.9-lts 然后，登录面板，我就直接升级到 v1.10.10-lts，打开应用面板就全部提示失败，但是我去容器里搜索应用名称，容器里面全部都存在，比对了一下，都是应用名称结尾不一样
> 
> 重建应用试过吗

重建立即失败

**Comment by zhengkunwang223** [comment]
> > > 整件事情是 v1.10.9-lts 升级到 v1.10.10-lts 后，我发现部分应用都变成了失败，那没办法，我只能卸载重装。后续又遇到 不能指定.env的情况，没办法想卸载重装，但是你们命令行提示，会删除所有服务与数据，那只好退回上一个版本用的命令行工具：
> > > ```shell
> > > 1pctl restore
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 回到 v1.10.9-lts 然后，登录面板，我就直接升级到 v1.10.10-lts，打开应用面板就全部提示失败，但是我去容器里搜索应用名称，容器里面全部都存在，比对了一下，都是应用名称结尾不一样
> > 
> > 
> > 重建应用试过吗
> 
> 重建立即失败

报什么错呢？

**Comment by QYG2297248353** [comment]
> > > > 整件事情是 v1.10.9-lts 升级到 v1.10.10-lts 后，我发现部分应用都变成了失败，那没办法，我只能卸载重装。后续又遇到 不能指定.env的情况，没办法想卸载重装，但是你们命令行提示，会删除所有服务与数据，那只好退回上一个版本用的命令行工具：
> > > > ```shell
> > > > 1pctl restore
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 回到 v1.10.9-lts 然后，登录面板，我就直接升级到 v1.10.10-lts，打开应用面板就全部提示失败，但是我去容器里搜索应用名称，容器里面全部都存在，比对了一下，都是应用名称结尾不一样
> > > 
> > > 
> > > 重建应用试过吗
> > 
> > 
> > 重建立即失败
> 
> 报什么错呢？

没报错，就是提示容器不存在，重建后也是提示容器不存在

**Comment by zhengkunwang223** [comment]
> > > > > 整件事情是 v1.10.9-lts 升级到 v1.10.10-lts 后，我发现部分应用都变成了失败，那没办法，我只能卸载重装。后续又遇到 不能指定.env的情况，没办法想卸载重装，但是你们命令行提示，会删除所有服务与数据，那只好退回上一个版本用的命令行工具：
> > > > > ```shell
> > > > > 1pctl restore
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 回到 v1.10.9-lts 然后，登录面板，我就直接升级到 v1.10.10-lts，打开应用面板就全部提示失败，但是我去容器里搜索应用名称，容器里面全部都存在，比对了一下，都是应用名称结尾不一样
> > > > 
> > > > 
> > > > 重建应用试过吗
> > > 
> > > 
> > > 重建立即失败
> > 
> > 
> > 报什么错呢？
> 
> 没报错，就是提示容器不存在，重建后也是提示容器不存在

能远程吗？
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/b0e35fd7-c6ce-4704-a755-6ba83d97a455)
加我企业微信

**Comment by QYG2297248353** [comment]
> > > > > > 整件事情是 v1.10.9-lts 升级到 v1.10.10-lts 后，我发现部分应用都变成了失败，那没办法，我只能卸载重装。后续又遇到 不能指定.env的情况，没办法想卸载重装，但是你们命令行提示，会删除所有服务与数据，那只好退回上一个版本用的命令行工具：
> > > > > > ```shell
> > > > > > 1pctl restore
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 回到 v1.10.9-lts 然后，登录面板，我就直接升级到 v1.10.10-lts，打开应用面板就全部提示失败，但是我去容器里搜索应用名称，容器里面全部都存在，比对了一下，都是应用名称结尾不一样
> > > > > 
> > > > > 
> > > > > 重建应用试过吗
> > > > 
> > > > 
> > > > 重建立即失败
> > > 
> > > 
> > > 报什么错呢？
> > 
> > 
> > 没报错，就是提示容器不存在，重建后也是提示容器不存在
> 
> 能远程吗？ ![image](https://private-user-images.githubusercontent.com/31820853/343625625-b0e35fd7-c6ce-4704-a755-6ba83d97a455.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NjY3MDQsIm5iZiI6MTcxOTQ2NjQwNCwicGF0aCI6Ii8zMTgyMDg1My8zNDM2MjU2MjUtYjBlMzVmZDctYzZjZS00NzA0LWE3NTUtNmJhODNkOTdhNDU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA1MzMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NjU5YTI3OTZhODE2ODk4NDk5ZDk0MTZmZTc4YzJiY2FjOGM1ZWU3Yzk1ODhhNjUxOTE3OWEzMmFjMTE3YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JGxNV6ff4Y-u_AIa_nmCzp3XerM2OrcyyOdqHFpe09c) 加我企业微信

我已经卸载所有应用和1panel，准备进行重装，并且直接指定应用名称，不在随机生成
