### ISSUE TITLE
[FEATURE] 计划任务备份网站或数据库希望能支持多选

### ISSUE THREAD

**Issue by ilay1678** [1Panel-dev/1Panel#558]
### 1Panel 版本

1.0.5

### 请描述您的需求或者改进建议

计划任务备份网站或数据库希望能支持多选，同时备份多个网站或数据库

**Comment by wanghe-fit2cloud** [comment]
v1.1.0 版本会支持备份全部网站或者数据库。

**Comment by wanghe-fit2cloud** [comment]
v1.1.0 版本已发布。
