### ISSUE TITLE
[BUG] mariadb 10.11.7 数据库同步失败

### ISSUE THREAD

**Issue by lettimepassby** [1Panel-dev/1Panel#5591]
### 联系方式

86416409@qq.com

### 1Panel 版本

v1.10.11-lts

### 问题描述

升级mariadb11后，面板无法同步数据库中的表，并显示删除
![QQ截图20240627152410](https://github.com/1Panel-dev/1Panel/assets/52483607/9947622a-3499-481c-9005-0da79923a167)
![QQ截图20240627155647](https://github.com/1Panel-dev/1Panel/assets/52483607/892ca56a-a7ba-4db8-bed0-b39d278a681a)

### 重现步骤

升级至mariadb11

**Comment by ssongliu** [comment]
感谢反馈，下个版本修复该问题

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
