### ISSUE TITLE
[FEATURE]升级的时候 忽略升级变灰

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#5593]
### 1Panel 版本

最新

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/51264840/81b25ebc-190b-4cef-a096-352b612ec667)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。上述需求是希望在应用处于 `升级中` 状态时禁用 `忽略升级` 按钮吗？

**Comment by 9a6c** [comment]
是的

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
