### ISSUE TITLE
[BUG] 预览.txt 的日志文件时中文乱码

### ISSUE THREAD

**Issue by canyanol650** [1Panel-dev/1Panel#5607]
### 1Panel 版本

v1.10.10-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/42194280/06494797-ce98-4cf4-b12c-3b23a2f359f7)

### 重现步骤

下载在本地用vs code  utf-8打开正常. 用GB2312打开乱码

### 期待的正确结果

正常显示中文

**Comment by wanghe-fit2cloud** [comment]
麻烦提供一下源文件，我们在本地环境复现一下该问题。

**Comment by canyanol650** [comment]
[logs-20240617.txt](https://github.com/user-attachments/files/16026269/logs-20240617.txt)
340行

**Comment by wanghe-fit2cloud** [comment]
> [logs-20240617.txt](https://github.com/user-attachments/files/16026269/logs-20240617.txt) 340行

上传的 文件有问题，如图：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/a450230e-e8bc-4d98-9dc6-de7d870eb06f)

**Comment by canyanol650** [comment]
[logs-20240617.txt](https://github.com/user-attachments/files/16026467/logs-20240617.txt)

**Comment by wanghe-fit2cloud** [comment]
将 1Panel 版本升级至 v1.10.11-lts 版本，再试一下打开该文件。

**Comment by canyanol650** [comment]
升级后可以了
