### ISSUE TITLE
[FEATURE] “功能菜单隐藏”增强

### ISSUE THREAD

**Issue by rdself** [1Panel-dev/1Panel#5613]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

应用商店对轻度使用者或者新手是个很好的功能，但是应用商店实际上相当于替代了用户来管理数据持久化和环境变量等配置，比较熟悉Docker的用户可能还是更加倾向于自己写Compose方便管理和从平台迁移。

此外，数据库的用户大多也有自己熟悉的GUI管理方式，1Panel的面板也很好但是有点冗余。

所以希望能把“高级功能菜单隐藏”改成“功能菜单隐藏”，允许更多的自定义隐藏项目，比如上面说到的边栏和首页的应用商店、边栏的数据库等。

感谢！

**Comment by zhengkunwang223** [comment]
感谢建议 我们会在后续版本不断优化

**Comment by QingFeng-awa** [comment]
这个issue是不是与很久很久以前提出的issue重复了。
#696

**Comment by wanghe-fit2cloud** [comment]
> 这个issue是不是与很久很久以前提出的issue重复了。 #696

是的，会在近期版本考虑支持。
