### ISSUE TITLE
[FEATURE]docker镜像加速地址不能添加带端口的地址

### ISSUE THREAD

**Issue by hanlihanshaobo** [1Panel-dev/1Panel#5618]
### 1Panel 版本

1.10.11

### 请描述您的需求或者改进建议

自建的镜像加速地址带有端口，但是面板的镜像加速地址不能添加带端口的地址

**Comment by zhengkunwang223** [comment]
感谢建议 我们会在后续版本优化

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
