### ISSUE TITLE
[FEATURE] 运行环境是否有添加 `Java 运行环境` 的计划

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#5619]
### 1Panel 版本

社区版 v1.10.11-lts

### 请描述您的需求或者改进建议

运行环境是否有添加 `Java 运行环境` 的计划，比较方便运行 Java 项目，目前使用 `Docker` 编排模版的功能实现的

**Comment by zhengkunwang223** [comment]
已完成，下个版本发

**Comment by wanghe-fit2cloud** [comment]
运行环境需求的讨论，统一汇总到该 issue #748
