### ISSUE TITLE
[FEATURE]商店集成 kkfileview

### ISSUE THREAD

**Issue by yfdoor** [1Panel-dev/1Panel#5634]
### 1Panel 版本

1.0.10

### 请描述您的需求或者改进建议

商店能否收录 在线预览 kkfileview
https://github.com/kekingcn/kkFileView

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上架该应用。

**Comment by wanghe-fit2cloud** [comment]
重复 https://github.com/1Panel-dev/1Panel/issues/4717

**Comment by yfdoor** [comment]
> 重复 #4717

看了下最早23年的时候就有人提出了，希望可以近期更新上，谢谢
