### ISSUE TITLE
[FEATURE]希望应用商店能增加webdav应用

### ISSUE THREAD

**Issue by duxdyu** [1Panel-dev/1Panel#5649]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

希望能增加webdav应用，这个感觉也是常用应用

### 请描述你建议的实现方案

使用bytemark/webdav镜像，compose大概这么写一下就好了，安装的时候就只需要配一下端口、用户名和密码
services:
  webdav:
    image: bytemark/webdav
    container_name: webdav
    restart: always
    ports:
      - "${ports}:80"
    environment:
      USERNAME: ${username}
      PASSWORD: ${password}
    volumes:
      - /opt/1panel/apps/webdav/webdav/data:/var/lib/dav

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，我们主要以项目的 star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有超1万 Star 的开源项目，感谢您的理解。

> 你可以将 pr 反馈给 [第三方仓库（由社区用户维护）](https://github.com/okxlin/appstore)。
