### ISSUE TITLE
[BUG]网站监控排除 IP 无效

### ISSUE THREAD

**Issue by taoya7** [1Panel-dev/1Panel#5650]
### 联系方式

 itaolaity@gmail.com

### 1Panel 版本

专业版 v1.10.11-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/36183969/db39d6d1-8e5c-471c-a056-abcf7da822aa)

已经设置排除，但是没有效果还是被记录下来了

![image](https://github.com/1Panel-dev/1Panel/assets/36183969/328c36d3-6dd0-49dd-b500-bede5b3c8e45)

### 重现步骤

升级最新版

**Comment by zhengkunwang223** [comment]
网站设置中存在吗

**Comment by taoya7** [comment]
存在的  默认是勾选状态

**Comment by zhengkunwang223** [comment]
> 存在的  默认是勾选状态
> 
> 
> 
> 

截图看一下

**Comment by taoya7** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/36183969/f0051833-ad05-4eb5-bf22-772633bbc475)
![image](https://github.com/1Panel-dev/1Panel/assets/36183969/c41f9447-c17b-4d6a-b783-ea195e39e084)

**Comment by zhengkunwang223** [comment]
> ![image](https://github.com/1Panel-dev/1Panel/assets/36183969/f0051833-ad05-4eb5-bf22-772633bbc475)
> 
> ![image](https://github.com/1Panel-dev/1Panel/assets/36183969/c41f9447-c17b-4d6a-b783-ea195e39e084)
> 
> 

openresty 什么版本？

**Comment by taoya7** [comment]
registry.cn-hangzhou.aliyuncs.com/t-mirror/openresty:1.21.4.3-3-2-focal

**Comment by taoya7** [comment]
我升级最新版试试 1.21.4.3-3-3-focal

**Comment by taoya7** [comment]
更新最新版本 可以了 @zhengkunwang223
