### ISSUE TITLE
希望能增加lucky容器

### ISSUE THREAD

**Issue by 818net** [1Panel-dev/1Panel#5661]
### 1Panel 版本

1.10.11

### 请描述您的需求或者改进建议

地址如下https://github.com/gdy666/lucky

**Comment by wanghe-fit2cloud** [comment]
我们暂时先不考虑上架该应用：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/8dd2f91a-9109-40b7-b189-8a50e054099a)

**Comment by 818net** [comment]
原来如此，谢谢你发自我的手机-------- 原始邮件 --------发件人： wanghe ***@***.***>日期： 2024年7月3日周三 17:57收件人： 1Panel-dev/1Panel ***@***.***>抄送： 818net ***@***.***>, Author ***@***.***>主    题： Re: [1Panel-dev/1Panel] 希望能增加lucky容器 (Issue #5661)
我们暂时先不考虑上架该应用：
image.png (view on web)
