### ISSUE TITLE
[FEATURE]添加西部数码域名解析接口DNS的支持

### ISSUE THREAD

**Issue by Wuqiyang312** [1Panel-dev/1Panel#5667]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

在**证书 -> DNS 账户**中添加添加西部数码域名解析接口的支持类型的支持。
西部数码域名解析的接口地址： https://api.west.cn/API/v2/domain/dns/
详细文档： https://console-docs.apipost.cn/preview/bf57a993975b67e0/7b363d9b8808faa2?target_id=001

### 请描述你建议的实现方案

在**证书 -> DNS 账户**中添加添加西部数码域名解析接口的支持类型的支持。

### 附加信息

西部数码域名解析的接口地址： https://api.west.cn/API/v2/domain/dns/
详细文档： https://console-docs.apipost.cn/preview/bf57a993975b67e0/7b363d9b8808faa2?target_id=001

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。目前我们会优先支持 `https://go-acme.github.io/lego/dns/` 列表中的 DNS 厂商。由于西部数码暂不在该列表中，因此短期内不会增加对此的支持，敬请谅解。
