### ISSUE TITLE
[FEATURE] 1panel 专业版防火墙 自定义  建议加入不包含的选项

### ISSUE THREAD

**Issue by fenglindubu** [1Panel-dev/1Panel#5668]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

1panel 专业版防火墙 自定义  建议加入不包含的选项
不然没法通过ua屏蔽非自己设置的ua

**Comment by fenglindubu** [comment]
同时 希望增加 网站监控 点击 独立ip 下面ui地图会变的样式，下载站访客数一直为0

**Comment by fenglindubu** [comment]
然后希望能参考腾讯cdn的样式，把每个小时段的 ip数 和流量也加进去最好

**Comment by wanghe-fit2cloud** [comment]
> 同时 希望增加 网站监控 点击 独立ip 下面ui地图会变的样式，下载站访客数一直为0

> 然后希望能参考腾讯cdn的样式，把每个小时段的 ip数 和流量也加进去最好

请再新开两个 issue，分别描述具体需求。
