### ISSUE TITLE
建议增加【修复面板】功能，以及像宝塔小窗打开配置菜单

### ISSUE THREAD

**Issue by 0ui0** [1Panel-dev/1Panel#5670]
### 1Panel 版本

1.10

### 请描述您的需求或者改进建议

1. 有时候面板会莫名奇妙地坏掉或者是人为导致的异常，我发现我找不到修复面板本体的功能，也不能覆盖安装。以及docker容器升级导致映射到宿主机的文件丢失，也无法修复，无论修复多少次应用都没用（不知道为什么我更新了openrestry以后出现了无法追加域名，提示配置文件丢失，怎么都无法修复，卸了重装也没用，好像映射的目录里的文件就是不能被修复）
2. 宝塔的小窗很好用，不需要多次跳转页面，希望1p能够跟进。1p几个页面切来切去有时候会眼花，如果能有类似phpwind后台那种多标签功能就更好了
3. 文件管理比宝塔难用的多，不支持直接拖拽上传，要另外点开一个菜单，而且这个菜单还不支持同时拖拽多个文件，拖了多个文件只能上传第一个

**Comment by wanghe-fit2cloud** [comment]
1、面板修复相关需求，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4540
2、`面板设置` - `菜单标签页`，点击启用
3、v1.10.12 版本会优化文件管理，发布后可以升级尝试。
