### ISSUE TITLE
[BUG]数据过大  操作会提示超时

### ISSUE THREAD

**Issue by Alexzzz2008** [1Panel-dev/1Panel#5671]
### 1Panel 版本

1.10.11

### 问题描述

/opt/1panel/apps/openresty/openresty/www
这个目录 计算  sites 文件夹大小  提示超时  (大小在800多G)

waf 拦截记录  30多万条 清空记录 提示超时

应该还有其他地方,只要过大就会超时,包括防篡改   文件数据量多,体积大的网站,开启关闭篡改 就会超时 缓慢
### 重现步骤

1

**Comment by zhengkunwang223** [comment]
感谢反馈 目前开启 WAF 和 网站日志 在数据量大的情况下确实容易超时 
可以手动删除 /opt/1panel/apps/openresty/openresty/1pwaf/data/db 下的数据文件
可以在定时任务开启网站的日志切割

**Comment by wanghe-fit2cloud** [comment]
文件夹大小计算超时问题，计划在 v1.10.13 版本优化 https://github.com/1Panel-dev/1Panel/issues/4639
