### ISSUE TITLE
[FEATURE]希望可以在应用商店中添加“Ghost”博客

### ISSUE THREAD

**Issue by Winner365-China** [1Panel-dev/1Panel#5673]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

希望可以在应用商店中添加“Ghost”博客
Ghost官网：[ghost.org](https://ghost.org/)

### 请描述你建议的实现方案

在应用商店中添加“Ghost”博客

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上架该应用。

**Comment by wanghe-fit2cloud** [comment]
第三方仓库已支持，地址如下：
https://github.com/QYG2297248353/appstore-1panel
