### ISSUE TITLE
[FEATURE]前端开源后端加密的项目如何上架appstore？

### ISSUE THREAD

**Issue by udyk-dev** [1Panel-dev/1Panel#5679]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

比如我公司开发的产品，是前端代码全部开源，后端代码是加密了之后做成了docker镜像，也就是说跟开源项目一样的可以直接通过docker hub拉取进行镜像进行部署， 那么这类型的应用能上架到appstore吗？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。建议使用 1Panel 本地应用形式来维护此类应用。具体教程请参考 [GitHub Wiki](https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8) 或 [论坛置顶教程](https://bbs.fit2cloud.com/t/topic/640/)。
