### ISSUE TITLE
防火墙增加ipv6管理功能[FEATURE]

### ISSUE THREAD

**Issue by ocean-99** [1Panel-dev/1Panel#5682]
### 1Panel 版本

v1.10.9-lts

### 请描述您的需求或者改进建议

希望能在防火墙功能中可以管理ipv6相关的规则, 类似于阿里云的安全组.
![image](https://github.com/1Panel-dev/1Panel/assets/109708840/5117d0d8-22a1-479d-a3d6-7901b1bf0677)

**Comment by ssongliu** [comment]
感谢反馈，1.10.12 版本将支持管理 ipv6

**Comment by wanghe-fit2cloud** [comment]
[v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta) 版本已发布。
