### ISSUE TITLE
[FEATURE] 应用商店里的ntfy安装优化

### ISSUE THREAD

**Issue by larkhover** [1Panel-dev/1Panel#5685]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

ntfy的安装目录里有一个名为"[server.yml.sample:Zone.Identifier](https://github.com/1Panel-dev/appstore/blob/dev/apps/ntfy/2.11.0/data/ntfy/server.yml.sample%3AZone.Identifier)"的空文件，似乎是和WSL相关的一个文件错误，上传时没删干净目录

**Comment by ssongliu** [comment]
感谢反馈，我们先在开发环境复现一下该问题
