### ISSUE TITLE
[FEATURE] 我们已经有了ONLYOFFICE DocS应用了,是时候添加ONLYOFFICE DocSpace应用了!

### ISSUE THREAD

**Issue by Mask-Vip** [1Panel-dev/1Panel#5687]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

ONLYOFFICE DocSpace和ONLYOFFICE Doc的关系就像是厂房和机器的关系.
现在我们的应用商店里已经有了ONLYOFFICE Doc就像是拥有了机器,可以开始处理各种文档了.
可是现在还没有厂房,根本找不到机器的入口.机器处理的文档也没有一个存放和整理的地方.
那么ONLYOFFICE DocSpace就是干这个的.在ONLYOFFICE他们叫ONLYOFFICE DocSpace是一个连接器,顾名思义ONLYOFFICE Doc这台机器需要连接到ONLYOFFICE DocSpace才是一个完整的,处理文档的方案.

### 请描述你建议的实现方案

https://helpcenter.onlyoffice.com/installation/docspace-community-install-script.aspx
这是ONLYOFFICE DocSpace的wiki他也是一款拥有开源社区版的文档管理空间.
只有两个都搭配部署起来了,才能真正完整的部署出一个文档处理 储存 共享 的私有空间!

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上架该应用。

**Comment by wanghe-fit2cloud** [comment]
相关需求的讨论，我们统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/3863
