### ISSUE TITLE
[FEATURE] 请求在商城上架duckdb数据库

### ISSUE THREAD

**Issue by yyh357** [1Panel-dev/1Panel#5701]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

请求在商城上架duckdb数据库

https://github.com/duckdb/duckdb

**Comment by zhengkunwang223** [comment]
我们先调研一下

**Comment by wanghe-fit2cloud** [comment]
> 请求在商城上架duckdb数据库

查阅了官方文档后，发现该应用似乎不支持 Docker 容器化安装。
> 你之前有这方面的经验吗？

**Comment by cwr31** [comment]
duckdb是binary不是service，何来部署一说

**Comment by wanghe-fit2cloud** [comment]
> duckdb是binary不是service，何来部署一说

这种情况将无法支持在 1Panel 应用商店上架。
