### ISSUE TITLE
[BUG]1panel面板绑定域名后未开启安全入口情况下，无法通过ui界面进入docker容器

### ISSUE THREAD

**Issue by ethanz-code** [1Panel-dev/1Panel#5703]
### 联系方式

57878778@qq.com

### 1Panel 版本

v1.10.11-lts

### 问题描述

1panel面板绑定域名后未开启安全入口情况下，无法通过ui界面进入docker容器

### 重现步骤

<img width="933" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/63432395/e29ddaa8-02c7-4351-9478-1f0ea6b5c64e">

### 期待的正确结果

不能正常进入容器内部

### 相关日志输出

```shell
disconnected
The connection has been disconnected.

index-5d62cb8e.js:7 WebSocket connection to 'wss://1panel.demo.cn/api/v1/containers/exec?cols=80&rows=24&containerid=fcc0f301c6f0223cd75bc4c5149c44b863a20812d57c03642e7ef078e8d1b6f3&user=&command=/bin/sh' failed: 

Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
```

### 附加信息

命令行进入没问题
<img width="673" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/63432395/2f00573a-2fde-4340-a49b-b72d77275af1">

**Comment by zhengkunwang223** [comment]
是否开了 CDN ？ CDN 是否开启 ws ?

**Comment by ethanz-code** [comment]
好像知道原因了，我域名访问配置了waf，通过ip功能可以正常用

**Comment by ethanz-code** [comment]
<img width="1237" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/63432395/ae0994ef-b42a-4ed9-bb90-0944b63e93af">
waf那边误把连接当成攻击拦截了
