### ISSUE TITLE
[FEATURE]希望应用商店列表支持添加自定义源，或添加更多的Docker应用

### ISSUE THREAD

**Issue by sunnyhmz7010** [1Panel-dev/1Panel#5708]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

希望应用商店列表支持添加自定义源，或添加更多的Docker应用
这是一个包含了很多Docker应用的第三方源
[https://github.com/Cp0204/CasaOS-AppStore-Play](https://github.com/Cp0204/CasaOS-AppStore-Play)或可以参考该仓库内包含的应用并将其添加到官方源中

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈！我们将在后续版本中持续上架更多优质应用。
