### ISSUE TITLE
[FEATURE]优化手机UI-开发手机管理APP

### ISSUE THREAD

**Issue by aibll** [1Panel-dev/1Panel#572]
### 1Panel 版本

1

### 请描述您的需求或者改进建议

优化一下面板在手机端显示的UI，如果可以还可以开发一个手机APP，绑定面板，来达成更好的使用体验！

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们可能会支持手机端。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
