### ISSUE TITLE
[BUG] 在甲骨文服务器上安装成功后无法访问

### ISSUE THREAD

**Issue by ithou** [1Panel-dev/1Panel#5725]
### 1Panel 版本

1Panel v1.10.11-lts

### 问题描述

[BUG]在甲骨文服务器上安装成功后无法访问，bug一直未修复。 #4384

在oracle上，所有协议、端口全部开放，同样的一个端口，nginx、qinglong都可以访问，只有1panle访问不了，可以肯定是1panle的某个BUG，不知能否解决？

### 重现步骤

见 #4384

### 期待的正确结果

http://ip:port 方式访问

**Comment by wanghe-fit2cloud** [comment]
参考：https://github.com/1Panel-dev/1Panel/discussions/4388
