### ISSUE TITLE
[FEATURE]增加全局代理

### ISSUE THREAD

**Issue by iZiwer** [1Panel-dev/1Panel#5728]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

目前的代理仅支持：系统许可证的验证和同步，
在不可直接访问外部网络的场景下，应用商店无法加载应用列表。
相关错误内容：
[ERROR] load latest version from oss failed, err: Get "https://resource.fit2cloud.com/1panel/package/stable/latest": dial tcp 163.181.140.233:443: i/o timeout 

### 请描述你建议的实现方案

建议增加全局生效的代理服务。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，应用商店的安装包下载与同步以及系统版本升级和获取更新说明这两个功能属于专业版功能，需导入 License 后才可正常使用。
