### ISSUE TITLE
[FEATURE]能够通过界面直接设置系统全局代理

### ISSUE THREAD

**Issue by tianxia0079** [1Panel-dev/1Panel#5729]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

Linux系统设置全局代理很麻烦，希望可以通过界面可以直接设置代理信息，然后有个开关控制生效或者不生效，需要代理的时候打开开关就可以。

### 请描述你建议的实现方案

可以放到系统设置那里，可以保存代理信息，然后有个开启和关闭按钮。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。目前版本的面板设置页面已经支持部分功能的代理。至于全局代理功能，我们在中短期内暂无计划支持，望理解。
