### ISSUE TITLE
[BUG] 没有启用IPV6, 容器自动映射了ipv6

### ISSUE THREAD

**Issue by static7** [1Panel-dev/1Panel#5736]
### 1Panel 版本

v1.10.11-lts

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/11241063/f2692e75-23d8-42e2-a645-5ab8fff4e2a2)
我没有启动ipv6
但是我装gitea的时候 自动给我映射了ipv6的地址
![image](https://github.com/1Panel-dev/1Panel/assets/11241063/8801c868-ac45-4bc4-85cf-d557c35b07c9)

### 重现步骤

关闭ipv6, 默认是关闭ipv6(从开始使用到现在都没有启动过ipv6)
从商店里安装gitea
安装成功后就自动映射了ipv6

### 期待的正确结果

不需要ipv6的地址

**Comment by wanghe-fit2cloud** [comment]
在应用安装时，勾选端口外部访问选项后，默认会绑定所有地址，即 IPv4 的 0.0.0.0 和 IPv6 的 :::。容器配置页面的 IPv6 开关与此设置无关，具体内容请参阅 Docker 官方描述。
