### ISSUE TITLE
[FEATURE?] 添加 http.cat 响应

### ISSUE THREAD

**Issue by Pigeonszz** [1Panel-dev/1Panel#5747]
### 1Panel 版本

略

### 请描述您的需求或者改进建议

https://http.cat/

### 请描述你建议的实现方案

https://http.cat/[status_code]

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/133509962/46336e93-79b2-424f-97a6-251808b1c0fc)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈！请问该项目是开源的吗？是否支持 Docker 容器化安装？如果支持，能否提供 docker-compose.yml 文件？

**Comment by Pigeonszz** [comment]
[github](https://github.com/httpcats/http.cat)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，我们主要以项目的 Star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有超1万 Star 的开源项目，感谢您的理解。

> 你可以将 pr 反馈给 [第三方仓库（由社区用户维护）](https://github.com/okxlin/appstore)。
