### ISSUE TITLE
[FEATURE]远程下载：没有下载列表，窗口关了之后就不知道下载状态了

### ISSUE THREAD

**Issue by zhengjianyang** [1Panel-dev/1Panel#5750]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

文件->远程下载：没有下载列表，窗口关了之后就不知道下载状态了
可以在下载界面下面空白处增加下载列表或者下载记录，管理下载项

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
重复问题 https://github.com/1Panel-dev/1Panel/issues/5013
