### ISSUE TITLE
[FEATURE] 建议容器模块下,表格里面增加一栏 安装目录的快速跳转的入口

### ISSUE THREAD

**Issue by static7** [1Panel-dev/1Panel#5758]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

![image](https://github.com/1Panel-dev/1Panel/assets/11241063/c4693a9a-63ad-4637-b59a-cf8a45517ac8)
建议增加一个安装目录的入口? 也就是配置文件的入口的快速跳转,
![image](https://github.com/1Panel-dev/1Panel/assets/11241063/5badbc63-2bae-4fdd-991a-527b5d55b3de)
每次都要跑到应用商店里进入安装目录, 感觉挺麻烦的

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by ssongliu** [comment]
1.10.20 版本支持编排跳转

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
