### ISSUE TITLE
[Feat:文件编辑器] 支持隐藏右侧略缩图

### ISSUE THREAD

**Issue by QingFeng-awa** [1Panel-dev/1Panel#5768]
### 1Panel 版本

v1.10.12-beta.1

### 请描述您的需求或者改进建议

希望文件编辑器支持隐藏编辑文件时显示在右侧的略缩图。

### 请描述你建议的实现方案

略缩图开关可以直接像自动换行的开关一样摆放。
> 也可以像左侧的文件夹树状图一样,提供一个类似的左右箭头用于显示/隐藏。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后面版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
最新预览版已经支持隐藏缩略图。
