### ISSUE TITLE
clamav 问题反馈

### ISSUE THREAD

**Issue by TIkc9** [1Panel-dev/1Panel#5769]
### 1Panel 版本

v1.10.12-beta.1

### 问题描述

clamav 版本信息不显示
任务执行异常，提示已执行，报告无内容，也看不到执行结果。
![image](https://github.com/1Panel-dev/1Panel/assets/17921262/4df55808-5dcb-4453-b10a-bce5a069b3ea)
![image](https://github.com/1Panel-dev/1Panel/assets/17921262/4586d184-b2dc-4ffc-85d2-51d42352a4bb)

### 重现步骤

必复现

**Comment by wanghe-fit2cloud** [comment]
手动执行 `clamdscan --version` 命令查看一下版本信息。
> 1Panel 服务器是什么操作系统？

**Comment by TIkc9** [comment]
> `clamdscan --version`

-bash: clamdscan: command not found
提示找不到这个命令，但是执行扫描任务的时候提示执行成功

系统版本为 Debian 12
![e8d4bcd56fbf1c5b8a67fe6c6240631](https://github.com/1Panel-dev/1Panel/assets/17921262/84369f7c-3e4d-475d-9e8a-b1cbcb803561)

**Comment by wanghe-fit2cloud** [comment]
> > `clamdscan --version`
> 
> -bash: clamdscan: command not found 提示找不到这个命令，但是执行扫描任务的时候提示执行成功
> 
> 系统版本为 Debian 12 

收到，我们先在本地环境的 Debian 12 服务器中复现一下上述问题。

**Comment by wanghe-fit2cloud** [comment]
可以先尝试更换官方软件源后，手动执行 `sudo apt-get install clamdscan` 命令来安装 `clamdscan`。

**Comment by TIkc9** [comment]
不知道啥情况 今天又恢复正常了  版本号 扫描日志都有了

**Comment by wanghe-fit2cloud** [comment]
最新预览版本已经针对 clamdscan 二进制文件缺失问题进行了优化。
