### ISSUE TITLE
[BUG]高级功能-GPU监控提示：当前系统未检测到 NVIDIA-SMI 指令，请检查后重试！

### ISSUE THREAD

**Issue by liufei20151013** [1Panel-dev/1Panel#5770]
### 联系方式

liufei@fit2cloud.com

### 1Panel 版本

v1.10.11-lts

### 问题描述

在腾讯云申请了一台 GPU 服务器，可以正常执行 nvidia-smi 指令，但是 高级功能-GPU监控 提示：当前系统未检测到 NVIDIA-SMI 指令，请检查后重试！
![image](https://github.com/1Panel-dev/1Panel/assets/15103510/57813dfd-17b5-4723-bcf1-80efd2f46c8b)
![image](https://github.com/1Panel-dev/1Panel/assets/15103510/8130d732-0c84-4367-ac58-44b3c25857b0)
 

### 重现步骤

在腾讯云申请了一台 GPU 服务器，可以正常执行 nvidia-smi 指令，但是 高级功能-GPU监控 提示：当前系统未检测到 NVIDIA-SMI 指令，请检查后重试！ 

### 期待的正确结果

希望 高级功能-GPU监控 页面可以看到 GPU 使用详情。

**Comment by zhengkunwang223** [comment]
能远程吗？
![image](https://github.com/1Panel-dev/1Panel/assets/31820853/fec34b95-dd59-4e86-83aa-4cece8d537c7)
加我一下

**Comment by wanghe-fit2cloud** [comment]
1Panel 最新预览版本已优化。

**Comment by liufei20151013** [comment]
> 1Panel 最新预览版本已优化。

是支持对接CUDA 11还是优化了什么呢

**Comment by wanghe-fit2cloud** [comment]
>> 1Panel 最新预览版本已优化。

> 是支持对接CUDA 11还是优化了什么呢

指令判断逻辑优化。
