### ISSUE TITLE
[BUG]文件列表弹窗问题

### ISSUE THREAD

**Issue by GunnmF** [1Panel-dev/1Panel#5771]
### 联系方式

moumou.v1@foxmail.com

### 1Panel 版本

v1.10.12-beta.1

### 问题描述

![image](https://github.com/1Panel-dev/1Panel/assets/101814544/21156f14-673b-41fa-adab-145ef953b37f)

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/101814544/4a7b7cb5-140a-472a-aa47-a1f9b0ac6330)

### 期待的正确结果

点击文件列表以外的区域关闭  或者  关闭Drawer的时候一起关闭

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本完成上述优化。

**Comment by wanghe-fit2cloud** [comment]
最新预览版已修复上述问题。
