### ISSUE TITLE
[FEATURE] 证书申请成功后自定义执行命令

### ISSUE THREAD

**Issue by icjs-cc** [1Panel-dev/1Panel#5772]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

证书申请后自定义执行命令，证书申请之后需要重启自建NGINX

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，该功能在 [v1.10.12-beta](https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.12-beta)  版本已支持，如图：
<img width="1472" alt="image" src="https://github.com/1Panel-dev/1Panel/assets/46734380/35866a93-314c-4178-bff7-63d1737ce96c">
