### ISSUE TITLE
[FEATURE]测试一个月，有部分优化建议。盼采纳！！！

### ISSUE THREAD

**Issue by WuPanFeng** [1Panel-dev/1Panel#5773]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

1.建议容器增加分组功能
2.建议OpenResty加入负载均衡配置
3.建议加入容器组合启动停止（按顺序启停）

### 请描述你建议的实现方案

1.比如我在1panel搭建一个7个节点的mysql集群。其中数据节点4个，api节点2个，管理节点1个。7个容器可以加入统一个小组，折叠起来。这样会看着很清爽。
![image](https://github.com/1Panel-dev/1Panel/assets/8175717/70b4f666-5e21-4581-83b6-ffc8ff0b42ea)
感觉界面不够直观，建议加入小图标预览功能

2.目前OpenResty的负载均衡需要改代码实现，容易出错，建议可视化界面配置。

**Comment by wanghe-fit2cloud** [comment]
感谢您的反馈，我们会在后续版本考虑支持上述需求。

**Comment by wan92hen** [comment]
这个场景用 compose 编排是不是更合适一些

**Comment by WuPanFeng** [comment]
可视化编排不是更好吗

**Comment by li-peifeng** [comment]
为什么不使用compose？

**Comment by wan92hen** [comment]
> 可视化编排不是更好吗

compose 在编排方面的能力已经比较完善了，即使做可视化编排，大概率也是基于 compose 来做，不太会另起炉灶。
所以在目前还没有这样能力的情况下，可以先考虑把 compose 给用上。

**Comment by WuPanFeng** [comment]
好的，刚开始接触。不是很懂，感谢两位大佬的指导！！

**Comment by wanghe-fit2cloud** [comment]
- 1、3 参考 `容器` - `编排`
- 网站负载均衡研发进度，参考：网站设置负载均衡需求的讨论，统一汇总到该 issue #2058

**Comment by WuPanFeng** [comment]
收到，感谢回复！
