### ISSUE TITLE
[BUG]升级升不上去，提示成功但还是原来的版本

### ISSUE THREAD

**Issue by itworkzhang** [1Panel-dev/1Panel#5783]
### 1Panel 版本

1.10.7

### 问题描述

![image](https://github.com/user-attachments/assets/0a034b90-ebc0-4b27-a6da-719abc6ae2b4)

### 重现步骤

点升级，提示成功，但是还是原来的版本

**Comment by itworkzhang** [comment]
突然又可以了

**Comment by linshuboy** [comment]
这个问题依然存在 v1.10.14-lts 升级 v1.10.19 v1.10.20 都不行

**Comment by linshuboy** [comment]
![image](https://github.com/user-attachments/assets/bb4b91f1-d10d-4236-a0e1-458007517d30)

**Comment by ssongliu** [comment]
> ![image](https://private-user-images.githubusercontent.com/20389206/379642315-bb4b91f1-d10d-4236-a0e1-458007517d30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTE4ODEsIm5iZiI6MTcyOTc1MTU4MSwicGF0aCI6Ii8yMDM4OTIwNi8zNzk2NDIzMTUtYmI0YjkxZjEtZDEwZC00MjM2LWEwZTEtNDU4MDA3NTE3ZDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA2MzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1OTU5ZWQyNTg3ZTlmMDAxYjViMTcxNWYwZjg0NzU3NWJjZTViOWI2ZWI5ZjQ1Y2U0YjM0NGE5ODhkMzIwYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.y-RNj6bYP0FxwnSVdE6tQk5iTbtCDm_0Xw_3teKvV2Q)

能获取到新版本内容，但是无法升级成功吗，日志是否已经截全？

**Comment by linshuboy** [comment]
> > ![image](https://private-user-images.githubusercontent.com/20389206/379642315-bb4b91f1-d10d-4236-a0e1-458007517d30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTE4ODEsIm5iZiI6MTcyOTc1MTU4MSwicGF0aCI6Ii8yMDM4OTIwNi8zNzk2NDIzMTUtYmI0YjkxZjEtZDEwZC00MjM2LWEwZTEtNDU4MDA3NTE3ZDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA2MzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1OTU5ZWQyNTg3ZTlmMDAxYjViMTcxNWYwZjg0NzU3NWJjZTViOWI2ZWI5ZjQ1Y2U0YjM0NGE5ODhkMzIwYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.y-RNj6bYP0FxwnSVdE6tQk5iTbtCDm_0Xw_3teKvV2Q)
> 
> 能获取到新版本内容，但是无法升级成功吗，日志是否已经截全？

是的，截图是全的，也是最新的

**Comment by linshuboy** [comment]
通过 https://bbs.fit2cloud.com/t/topic/5579 这个方法升级也升不上去 系统是aws lightsail centos 9 镜像

**Comment by wanghe-fit2cloud** [comment]
是下载的 v1.10.20-lts 版本吗？
安装包下载地址：`wget https://resource-fit2cloud-com.oss-cn-hangzhou.aliyuncs.com/1panel/package/stable/v1.10.20-l
ts/release/1panel-v1.10.20-lts-linux-amd64.tar.gz`

**Comment by linshuboy** [comment]
> 是下载的 v1.10.20-lts 版本吗？ 安装包下载地址：`wget https://resource-fit2cloud-com.oss-cn-hangzhou.aliyuncs.com/1panel/package/stable/v1.10.20-l ts/release/1panel-v1.10.20-lts-linux-amd64.tar.gz`

是的

**Comment by wanghe-fit2cloud** [comment]
> > 是下载的 v1.10.20-lts 版本吗？ 安装包下载地址：`wget https://resource-fit2cloud-com.oss-cn-hangzhou.aliyuncs.com/1panel/package/stable/v1.10.20-l ts/release/1panel-v1.10.20-lts-linux-amd64.tar.gz`
> 
> 是的

可以看一下 `日志审计` - `系统日志` 有没有错误信息。
> 本地未能复现这个问题
