### ISSUE TITLE
[FEATURE] 变量名小建议

### ISSUE THREAD

**Issue by maoball** [1Panel-dev/1Panel#5790]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

<img width="1320" alt="截屏2024-07-12 20 36 51" src="https://github.com/user-attachments/assets/4c43a7d4-ac65-4784-a8b2-cabe102b163c">

如上图，对`ErrFileIsExit`的定义是文件已存在，漏打了s (`ErrFileIsExist`)，并且在翻译文件内同样存在该问题。希望开发者们把这里改一下，谢谢

### 请描述你建议的实现方案

把`ErrFileIsExit`改为`ErrFileIsExist`

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
可以考虑给项目提交一个 Pull request
https://github.com/1Panel-dev/1Panel/pulls

**Comment by maoball** [comment]
@wanghe-fit2cloud 提交了，您看可以吗

**Comment by wanghe-fit2cloud** [comment]
> @wanghe-fit2cloud 提交了，您看可以吗

感谢支持 👍

**Comment by maoball** [comment]
> > @wanghe-fit2cloud 提交了，您看可以吗
> 
> 感谢支持 👍

https://github.com/1Panel-dev/1Panel/pull/5792
又提交了一个pr，您看ok吗

**Comment by wanghe-fit2cloud** [comment]
1Panel 最新预览版本已优化。
