### ISSUE TITLE
希望添加面板BasicAuth认证功能

### ISSUE THREAD

**Issue by Junehck** [1Panel-dev/1Panel#5793]
### 1Panel 版本

10.1+

### 请描述您的需求或者改进建议

类似于
![image](https://github.com/user-attachments/assets/e95c20fb-e19c-4a2d-a918-7847bfbd5564)
![image](https://github.com/user-attachments/assets/7b073fd0-008d-4340-a890-a6731edadcee)

让面板更安全一点

**Comment by KWEOO** [comment]
有道理

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
BasicAuth 相关需求的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/2198
