### ISSUE TITLE
[FEATURE]概览页面增加自定义入口（收藏夹）

### ISSUE THREAD

**Issue by sunnyhmz7010** [1Panel-dev/1Panel#5800]
### 1Panel 版本

v1.10.12-beta.1

### 请描述您的需求或者改进建议

建议在概览页面增加一个板块可以添加自定义快捷入口
![655e7b16d673b1475b335f2df3757b2](https://github.com/user-attachments/assets/ae341d0d-d68f-489d-9e30-e64864c3d5c2)
填写以下内容
![1720926702247](https://github.com/user-attachments/assets/886fb2f6-bf49-4517-b138-08b2bbad20aa)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑是否支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
概览页自定义入口的需求，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/5167
