### ISSUE TITLE
meilisearch 应用商店 `开启` 值优化

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#5802]
### 1Panel 版本

最新

### 问题描述

关闭可以显示出来， 选择开启， 文字却显示的请选择
![image](https://github.com/user-attachments/assets/a7e75479-94db-4e21-96f5-f7340bd62531)
![image](https://github.com/user-attachments/assets/3f1f9424-c03a-4c01-b216-26fde6ece6bf)

### 重现步骤

应用商店-安装meilisearch

**Comment by wanghe-fit2cloud** [comment]
根据应用官方提供的 compose 文件，`开启` 对应的值为空字符串。由于在 1Panel 当前版本中只能使用 `''`，该值对应了 `请选择` 这个空值。在 v2.0 版本重构期间，可能会考虑对此进行优化。

**Comment by wanghe-fit2cloud** [comment]
已完成更新。可以进入应用商店，点击右上角的【更新应用列表】按钮，待同步完成后即可安装最新版本。
