### ISSUE TITLE
[BUG] node低版本没有镜像

### ISSUE THREAD

**Issue by wzy-wangge** [1Panel-dev/1Panel#5813]
### 1Panel 版本

v1.10.11-lts

### 问题描述

安装 运行环境-> node.js  -> 16.20.2
出现错误，无法拉取镜像
![image](https://github.com/user-attachments/assets/68dedce3-bced-4a8d-9afc-58482664e715)

### 重现步骤

https://hub.docker.com/r/1panel/node/tags
发现并没有 16.20.2 及低版本镜像

**Comment by zhengkunwang223** [comment]
感谢反馈 我们修改一下镜像的地址 
1Panel 当前仅维护 18 20 21 22 版，其他版本应该用官方镜像

**Comment by wanghe-fit2cloud** [comment]
进入应用商店页面，点击右上角的【更新应用列表】按钮，等待同步成功后再来安装 Node.js 运行环境。
> 新版本已推送。
