### ISSUE TITLE
数据库性能调优table_open_cache

### ISSUE THREAD

**Issue by hsjgit** [1Panel-dev/1Panel#5818]
### 1Panel 版本

v1.10.11-lts

### 问题描述

mysql 新能调优将table_open_cache 设为10000，重启mysql，mysql服务异常
查看配置文件table_open_cache=9.765625K

### 重现步骤

数据库->mysql->性能调优。将table_open_cache设置成10000，保存重启

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下该问题。

**Comment by wanghe-fit2cloud** [comment]
1Panel 最新预览版本已修复该问题。
