### ISSUE TITLE
[FEATURE]删除数据库远程连接提示相关

### ISSUE THREAD

**Issue by Couleur-Share** [1Panel-dev/1Panel#5819]
### 1Panel 版本

v1.10.12-beta.1

### 请描述您的需求或者改进建议

你好，我有个疑问，远程服务器操作界面中的删除操作，是删除这个远程连接吧？应该不是删除我远程服务器里的数据库吧？这个提示信息看得我很害怕。

### 请描述你建议的实现方案
如果这个操作是“取消远程连接”，希望能优化一下提示信息和操作逻辑，非常感谢

_No response_

### 附加信息

![远程连接数据库](https://github.com/user-attachments/assets/ec6c7a85-5cc0-4827-ad32-77856e6ce4fe)

**Comment by wanghe-fit2cloud** [comment]
好的，我们会在近期版本中优化该提示信息。

**Comment by wanghe-fit2cloud** [comment]
1Panel 最新预览版本已优化。
