### ISSUE TITLE
[FEATURE]希望修改文件权限的时候有一个选项是不是要递归到目录下的文件，和可以批量选择然后修改权限的功能

### ISSUE THREAD

**Issue by 52lemon6** [1Panel-dev/1Panel#582]
### 1Panel 版本

1.1.0

### 请描述您的需求或者改进建议

希望修改文件权限的时候有一个选项是不是要递归到目录下的文件，和可以批量选择然后修改权限的功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后面版本我们会支持这两个需求

1、权限是否应用到子目录
2、批量修改文件权限

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
