### ISSUE TITLE
[BUG] 无法安装java环境 服务内部错误: invalid spec: :/app: empty section between colons

### ISSUE THREAD

**Issue by carve-myself** [1Panel-dev/1Panel#5822]
### 1Panel 版本

v1.10.11-lts

### 问题描述

![image](https://github.com/user-attachments/assets/c209f832-077d-43e2-9e6a-1e6c7ff6f446)
![image](https://github.com/user-attachments/assets/316a77f6-f4ca-4421-869e-9c323dd8beea)

### 重现步骤

VMware运行，使用的是ubuntu22.04系统，镜像从官网下载的

应用商店安装java运行环境失败 服务内部错误: invalid spec: :/app: empty section between colons

**Comment by zhengkunwang223** [comment]
请升级到 v1.10.12-beta 版本使用

**Comment by wanghe-fit2cloud** [comment]
<img width="984" alt="image" src="https://github.com/user-attachments/assets/2694e535-87cd-4043-889d-c1b1f6212db1">
> 开启后，点击右下角的【检查更新】，即可升级至 beta 版本。
