### ISSUE TITLE
[FEATURE]希望添加数据库的时候可以选择仅本机模式

### ISSUE THREAD

**Issue by 52lemon6** [1Panel-dev/1Panel#583]
### 1Panel 版本

1.1.0

### 请描述您的需求或者改进建议

希望添加数据库的时候可以选择仅本机模式，位置如图
![image](https://user-images.githubusercontent.com/40059643/231173722-fe266f11-1c05-4228-8378-add718b475bd.png)

**Comment by zhengkunwang223** [comment]
容器中 mysql 数据库，设置本地权限意义不大，设置完毕后无法访问

**Comment by cyril-cheng** [comment]
直接填宿主机IP地址就可以了。

**Comment by wanghe-fit2cloud** [comment]
> 直接填宿主机IP地址就可以了。

是的，权限选择指定IP，然后填写宿主机地址就相当于是本机模式。
