### ISSUE TITLE
[FEATURE]应用商店建议支持casdoor

### ISSUE THREAD

**Issue by pengjianbo** [1Panel-dev/1Panel#5832]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

应用商店建议支持casdoor
网站：https://casdoor.org/docs/basic/try-with-docker/

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/2013

**Comment by QYG2297248353** [comment]
> ### 请描述您的需求或者改进建议
> 应用商店建议支持casdoor 网站：https://casdoor.org/docs/basic/try-with-docker/



[第三方应用商店已支持该应用](https://github.com/QYG2297248353/appstore-1panel?tab=readme-ov-file#%E7%BB%B4%E6%8A%A4%E7%8A%B6%E6%80%81)

![image](https://github.com/user-attachments/assets/2311af4e-118f-4dbc-bb07-0dc0a562d9c8)
