### ISSUE TITLE
[BUG] 文件-属性

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#5842]
### 1Panel 版本

最新

### 问题描述

查看文件属性， 文件大于10M就无法查看，我认为这是不合理的
![image](https://github.com/user-attachments/assets/1a018ea8-8903-4e96-8820-d9bae2746e19)

### 重现步骤

文件页面 => 任意大于10M的文件 => 点击更多-属性

### 期待的正确结果

可以查看文件属性

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述功能。

**Comment by wanghe-fit2cloud** [comment]
v1.10.12-beta.3 版本已修复。
