### ISSUE TITLE
[FEATURE]建议新增已安装应用地址主页

### ISSUE THREAD

**Issue by git-Ander** [1Panel-dev/1Panel#5845]
### 1Panel 版本

v1.10.12-beta.1

### 请描述您的需求或者改进建议

建议在概览中新增已安装应用地址主页, 便于统一入口, 包括应用商城应用地址和手动添加的应用地址, 可自定义图标和简介什么的

**Comment by wanghe-fit2cloud** [comment]
概览页自定义入口的需求，统一汇总到该 issue [#5167](https://github.com/1Panel-dev/1Panel/issues/5167)
