### ISSUE TITLE
需要重置防火墙。误设置1panel端口仅允许本地ip，导致1panel面板无法访问[BUG]

### ISSUE THREAD

**Issue by pureages** [1Panel-dev/1Panel#5852]
### 1Panel 版本

最新版本 专业版

### 问题描述

需要重置防火墙。误设置1panel端口仅允许本地服务器ip（原本是想设置另一个端口），导致1panel面板无法访问。

我也无法通过在服务器上挂VPN去登录1panel（因为防火墙没有放开端口）

请问如何重置防火墙的ip放行策略？

### 重现步骤

1、我的1panel面板端口是46666。
2、打开防火墙。
3、设置46666仅允许ip：aaa.b.c.d（这个是我1panel服务器的ip地址）
4、1panel再也无法访问，但上面部署的halo应用还是一切正常。

### 期待的正确结果

重置1panel防火墙端口放行策略的命令

**Comment by pureages** [comment]
问题已经解决，我输入了以下命令搞定！
```
iptables -P INPUT ACCEPT
iptables -F
```

**Comment by pureages** [comment]
还是出现了新的问题，防火墙重启后，导致1panel直接炸了，所有应用都无法访问。

算了，我直接重装了。

**Comment by li-peifeng** [comment]
1pctl reset ips
不行么？

**Comment by pureages** [comment]
> 1pctl reset ips 不行么？

昨天试过，应该没有用，我昨天把1pctl里能试的命令都试了
