### ISSUE TITLE
[BUG] 更新版本后无法访问网站配置页面

### ISSUE THREAD

**Issue by QingFeng-awa** [1Panel-dev/1Panel#5853]
### 联系方式

qingfeng@xtreme.net.cn

### 1Panel 版本

社区版1.10.12-beta.3

### 问题描述

更新新版本后无法访问网站的配置页面。
具体症状表现为点击`配置`按钮后一直加载。
- [x] **我确认不是因为网络问题造成的异常。**

### 重现步骤

升级到`1.10.12-beta.3`。

### 附加信息

非常奇怪,我在更新前是可以正常访问的,但更新后就出现问题了,更新过程前后还不超过5分钟。
我希望尽快修复这个问题,否则我作为一名普通用户根本没法配置网站。

**Comment by wanghe-fit2cloud** [comment]
进入 `日志审计` - `系统日志`页面，查看详细日志是否有相关错误信息。
尝试清除浏览器缓存或更换浏览器。
