### ISSUE TITLE
[BUG]查看文件属性，字段值太长时表格显示异常

### ISSUE THREAD

**Issue by MignonZhang** [1Panel-dev/1Panel#5855]
### 1Panel 版本

1.10.12

### 问题描述

![图片](https://github.com/user-attachments/assets/dcc2eb8a-42d8-4589-a73c-84702e3355a3)

### 重现步骤

文件路径特别长

### 期待的正确结果

建议固定字段名称列的宽度，字段值太长的话换行显示

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述功能。

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
