### ISSUE TITLE
[BUG] 文件用户和用户组不显示

### ISSUE THREAD

**Issue by wangzhengkun** [1Panel-dev/1Panel#5858]
### 1Panel 版本

v1.10.12

### 问题描述

![image](https://github.com/user-attachments/assets/7d91ebbb-4772-471f-9d48-8c1906a60ea9)
当文件的用户和用户组只有 id 没有 name 的情况下
点击权限 用户和用户组为空 点击保存报错
![image](https://github.com/user-attachments/assets/286ed692-adbd-4102-92ea-b3d9737cdee4)

### 重现步骤

![image](https://github.com/user-attachments/assets/7d91ebbb-4772-471f-9d48-8c1906a60ea9)
当文件的用户和用户组只有 id 没有 name 的情况下
点击权限并保存

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.10.19-lts 版本已发布。
