### ISSUE TITLE
[FEATURE]关于避免面板被识别的安全建议

### ISSUE THREAD

**Issue by xiahao90** [1Panel-dev/1Panel#5859]
### 1Panel 版本

v1.10.12-lts

### 请描述您的需求或者改进建议

建议在【未认证设置】功能时，设置自定义的html和header信息，或者设置401的密码认证。 这个功能的作用是避免服务器被扫描空探程序识别成为1panel，避免出0day的时候被别人从fofa，daydaymap等网站直接搜索到我们的服务器利用。

现在已有的【未认证设置】，可以设置各种返回状态码，但是返回的网页中还是有什么B8BKwXuP.js这种具有唯一性的字符串，这中还是可能被识别成1panel

### 附加信息

bt面板有个401功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.10.22 版本已发布。
