### ISSUE TITLE
[FEATURE]建议支持通过命令行的方式操作定时任务

### ISSUE THREAD

**Issue by SwingFrog** [1Panel-dev/1Panel#5860]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

有这样的场景，通过脚本的形式自动化新增服务，但备份数据库的计划任务需要手动创建，目前来说不太方便。
希望能支持命令行的方式【创建、启用、禁用、删除】计划任务。

### 请描述你建议的实现方案

例如备份数据库的命令
1pctl plan db mysql 数据库名 cron表达式 3份

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在 v2 版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
经过团队内部讨论，我们决定暂不支持该功能，敬请谅解。
