### ISSUE TITLE
[FEATURE] 是否有考虑和宝塔一样将FTP直接添加到面板上呢？或者添加到应用商店。

### ISSUE THREAD

**Issue by Lrunlin** [1Panel-dev/1Panel#5861]
### 1Panel 版本

v1.10.12-lts

### 请描述您的需求或者改进建议

在应用商店添加FTP

**Comment by wanghe-fit2cloud** [comment]
已支持，如图：
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/530ab69a-a05a-4432-b623-ce7cb6452c7f">
> 新建 PHP 等运行环境时，也支持直接创建 FTP 账号。

**Comment by Lrunlin** [comment]
希望的是可以直接在面板内安装不在使用命令行， 因为产品用户应该是以方便为主，直接集成进去比较合适

**Comment by wanghe-fit2cloud** [comment]
> 希望的是可以直接在面板内安装不在使用命令行， 因为产品用户应该是以方便为主，直接集成进去比较合适

了解，这一点会在 v2 版本中考虑支持。

**Comment by Lrunlin** [comment]
> > 希望是可以直接在面板内安装不使用命令行，因为产品用户应该方便主，直接集成进去比较合适
> 
> 了解，这一点将在 v2 版本中考虑支持。

好的谢谢，最好是和宝塔一样，插件无需使用命令行安装，由面板代执行安装和拆卸，集成到面板或者应用商店
