### ISSUE TITLE
[BUG] 从网站配置页上传的SSL状态显示错误

### ISSUE THREAD

**Issue by QingFeng-awa** [1Panel-dev/1Panel#5867]
### 联系方式

qingfeng@qingfengawa.me

### 1Panel 版本

社区版1.10.12-LTS

### 问题描述

![Issue Image](https://github.com/user-attachments/assets/ba4c9a83-5bb9-4b16-abac-bb8ba17bb272)

### 重现步骤

升级到`v1.10.12-LTS`,在安装OpenResty并创建网站后,在网站的HTTPS配置页选择`手动导入证书`,完成后在`/websites/ssl`查看。

### 附加信息

我怎么记得之前有人提过跟这个差不多的issue

**Comment by zhengkunwang223** [comment]
是用的  cloudflare 证书吗？

**Comment by QingFeng-awa** [comment]
是的

**Comment by QingFeng-awa** [comment]
但这个跟CloudFlare证书没关系 *(也许?)*

**Comment by QingFeng-awa** [comment]
![issue image](https://github.com/user-attachments/assets/a42f5605-ae46-4c89-8db1-8112408a8067)

**Comment by zhengkunwang223** [comment]
> ![issue image](https://private-user-images.githubusercontent.com/151742581/350301071-a42f5605-ae46-4c89-8db1-8112408a8067.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzQ1NTAsIm5iZiI6MTcyMTM3NDI1MCwicGF0aCI6Ii8xNTE3NDI1ODEvMzUwMzAxMDcxLWE0MmY1NjA1LWFlNDYtNGM4OS04ZGIxLTgxMTI0MDhhODA2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwNzMwNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmNjMGFlZDc1NzBmNmY3YjBmMmIyNDM1N2RmMjM3OGEyYmJiYTliZjZkMjc4MTdmYmFlNDdiNDNhYWU0NzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hfjaBrqHSUrfm-x1TBF4xMpkPxHvN9lbAU2hc2BtkdI)

好的 感谢反馈 我复现一下

**Comment by zhengkunwang223** [comment]
已复现 后续版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.10.13-lts 版本已发布。
