### ISSUE TITLE
[FEATURE]能否加入对kvm的支持和管理

### ISSUE THREAD

**Issue by imJack6** [1Panel-dev/1Panel#587]
### 1Panel 版本

1.0.5

### 请描述您的需求或者改进建议

能否加入对kvm的支持和管理

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。麻烦再详细描述一下您对于 kvm 的需求。

**Comment by imJack6** [comment]
> 感谢反馈。麻烦再详细描述一下您对于 KVM 的需求。
一些基本的操作（添加 删除 更改虚拟机配置 开关机 等），可以管理镜像 虚拟硬盘 虚拟网卡等，VNC。（如果可以，还可以加个免密登录系统和安全组啥的）

**Comment by wojiushixiaobai** [comment]
- Link: #587

**Comment by wanghe-fit2cloud** [comment]
经过内部讨论，我们暂时不会考虑该需求。
