### ISSUE TITLE
[BUG]软连接被识别为文件

### ISSUE THREAD

**Issue by mengy822** [1Panel-dev/1Panel#5871]
### 1Panel 版本

v1.10.12-lts

### 问题描述

arm debain系统 最新版本1panel 文件夹的软连接被识别为文件

### 重现步骤

arm debain系统 最新版本1panel 文件夹的软连接被识别为文件

**Comment by wanghe-fit2cloud** [comment]
脚本类型的软链接可以点击编辑，但二进制等类型文件有编辑限制。
<img width="1176" alt="image" src="https://github.com/user-attachments/assets/b99ebcb5-aaa9-4fa6-acb3-ab033d12e218">
