### ISSUE TITLE
[Feat] 希望将日志页全屏改为网页全屏

### ISSUE THREAD

**Issue by QingFeng-awa** [1Panel-dev/1Panel#5873]
### 1Panel 版本

1.10.12-LTS

### 请描述您的需求或者改进建议

日志页全屏个人认为改成网页全屏更好一点,现在的全屏个人感觉不太好。

### 附加信息

这里指的日志页是`/toolbox/supervisor`的日志。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本可能会考虑优化上述功能。

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
