### ISSUE TITLE
[BUG]同一版本PHP容器仅允许新建一个，不符合实际需求

### ISSUE THREAD

**Issue by lopins** [1Panel-dev/1Panel#5876]
### 1Panel 版本

1.10.12-lts

### 问题描述

同一版本PHP容器仅允许新建一个,不符合实际需求：

如果需要多个相同版本的PHP版本,但是不同拓展的PHP环境（比如两个PHP7.4），则无法满足

### 重现步骤

如果需要多个相同版本的PHP版本,但是不同拓展的PHP环境（比如两个PHP7.4），则无法满足

**Comment by wanghe-fit2cloud** [comment]
重复 #2405
