### ISSUE TITLE
文件夹的软链接被识别为文件

### ISSUE THREAD

**Issue by wanghe-fit2cloud** [1Panel-dev/1Panel#5879]
### Discussed in https://github.com/1Panel-dev/1Panel/discussions/5872

<div type='discussions-op-text'>

<sup>Originally posted by **mengy822** July 19, 2024</sup>

### 1Panel 版本

v1.10.12-lts

### 问题描述

arm debain系统 最新版本1panel 文件夹的软连接被识别为文件

### 重现步骤

arm debain系统 最新版本1panel 文件夹的软连接被识别为文件

### 附加信息

_No response_</div>

**Comment by wanghe-fit2cloud** [comment]
近期版本优化上述功能。

**Comment by gowy222** [comment]
这个问题在第一个开源版本其实就存在，
因为压缩文件夹的时候会出现异常...好久之前了，第一次宝塔迁移到1panel的时候，
记得手动备份一个项目目录的时候发现压缩不了，在宝塔的时候则能压缩，

建议，同时检查一下，能不能压缩文件夹成功。

**Comment by wanghe-fit2cloud** [comment]
v1.10.15-lts 版本已发布。
