### ISSUE TITLE
[FEATURE]容器界面记录上次是否勾选了显示应用商店容器

### ISSUE THREAD

**Issue by HongJunShan** [1Panel-dev/1Panel#5885]
### 1Panel 版本

v1.10.12-lts

### 请描述您的需求或者改进建议

每次打开容器界面都会默认勾上显示应用商店容器，能否记录上一次是否勾选作为默认展示？

**Comment by wanghe-fit2cloud** [comment]
好的，近期版本优化上述功能。

**Comment by HongJunShan** [comment]
希望在容器-->日志界面显示条数和是否开启追踪也能记录上一次选项作为默认展示，谢谢！

**Comment by wanghe-fit2cloud** [comment]
v1.10.19-lts 版本已发布。
