### ISSUE TITLE
[FEATURE]容器推送前端性能优化

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#5887]
### 1Panel 版本

v1.10.12-lts

### 请描述您的需求或者改进建议

使用 容器 > 镜像 > 推送 功能，导致浏览器（chrome最新版）卡死，电脑也卡的不能动：
![PixPin_2024-07-21_11-52-56](https://github.com/user-attachments/assets/3b5c9c35-6e71-4ca7-ba1b-b2c50015c074)

推送完成后一切恢复正常，因此这个不像是电脑性能问题，任务管理器（并不是占比峰值截图，因为电脑卡的动不了了）：
![PixPin_2024-07-21_11-53-13](https://github.com/user-attachments/assets/cfe39a63-e5f1-4008-a1eb-431eed2a6c49)

电脑参数：
![PixPin_2024-07-21_11-53-30](https://github.com/user-attachments/assets/9855707f-0401-4cec-ad31-4bcd6a40fe3a)

### 请描述你建议的实现方案

建议优化容器推送的前端数据加载，虽说这个问题算不上是bug，但比较影响使用体验。

**Comment by zhengkunwang223** [comment]
感谢建议 我们先复现一下

**Comment by JAINKRE** [comment]
本地仓库用的是harbor 测试拉取gitlab ce（2.74GB）和ee（3GB）：
```cmd
docker pull gitlab/gitlab-ce:17.2.0-ce.0
```
推送都出现了这个情况。怀疑是不是推送的容器过大，前端显示的日志状态导致的问题？

测试的时候到了浏览器内存占用3500MB最高，CPU占用30%最高，浏览器无响应。

**Comment by wanghe-fit2cloud** [comment]
> 本地仓库用的是harbor 测试拉取gitlab ce（2.74GB）和ee（3GB）：
> 
> ```batchfile
> docker pull gitlab/gitlab-ce:17.2.0-ce.0
> ```
> 
> 推送都出现了这个情况。怀疑是不是推送的容器过大，前端显示的日志状态导致的问题？
> 
> 测试的时候到了浏览器内存占用3500MB最高，CPU占用30%最高，浏览器无响应。

是的，后续版本针对大镜像推送功能进行优化。

**Comment by JAINKRE** [comment]
但这个问题好像被修复了，最近推送大镜像没有出现卡死的问题。包括 gitlab

**Comment by ssongliu** [comment]
这里是确实是因为日志显示导致的问题，中间某个版本优化了该功能。
