### ISSUE TITLE
[FEATURE]类似宝塔面板的告警通知功能

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#5890]
### 1Panel 版本

v1.10.12-lts

### 请描述您的需求或者改进建议

希望1panel可以考虑在之后的版本中实现类型宝塔面板中的告警通知功能：
![PixPin_2024-07-21_13-12-04](https://github.com/user-attachments/assets/c76e2cd6-c141-45d8-af23-7645305e25e3)

这个功能对自动化运维来说提供了极大的便捷性，当服务器一多如果需要每台挨个登录查看，显得过于繁琐。而且登录服务器查看一般来说也只是关心几个核心的运行状态，完全可以通过此类告警功能实现第一时间通知。

### 请描述你建议的实现方案

建议实现过程中可以考虑更广泛的兼容性而不仅仅是局限于固定的通知泛式，可以考虑通知事件做成类似钩子函数的功能，不仅可以第一时间触发固定的通知，也可以触发自定义的运行脚本。因为有些工作，其实是不完全需要人操作的，完全可以通过脚本自动解决。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，通知、告警相关需求的讨论，统一汇总到该 issue #614
