### ISSUE TITLE
[FEATURE]改进文件管理器终端cd指令中的路径

### ISSUE THREAD

**Issue by WittF** [1Panel-dev/1Panel#5891]
### 1Panel 版本

v1.10.12-lts

### 请描述您的需求或者改进建议

请求改进面板-文件打开终端时自动输入的 cd 指令，
使其为路径添加双引号，变为路径整体，避免因路径中的空格而导致的`too many arguments`错误
![error](https://github.com/user-attachments/assets/33a34e16-da69-46d5-b0e6-b877767d5116)

### 请描述你建议的实现方案

cd "path".

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述功能。

**Comment by wanghe-fit2cloud** [comment]
v1.10.15-lts 版本已发布。
