### ISSUE TITLE
[FEATURE]希望增加sql审计平台 主流的有 Yearning   Archery Bytebase

### ISSUE THREAD

**Issue by augusl** [1Panel-dev/1Panel#5895]
### 1Panel 版本

v1.10.12-lts

### 请描述您的需求或者改进建议

[Yearning](https://github.com/cookieY/Yearning)
[Archery](https://github.com/hhyo/Archery)
[Bytebase](https://github.com/bytebase/bytebase)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本优先考虑上架 [Bytebase](https://github.com/bytebase/bytebase)
> 前两个项目的 star 数量不足 1万，尚未达到上架要求。

**Comment by wanghe-fit2cloud** [comment]
[Bytebase](https://github.com/bytebase/bytebase) 已上架应用商店。
