### ISSUE TITLE
[FEATURE] 能否提供对离线环境的支持?

### ISSUE THREAD

**Issue by xiaojueshi** [1Panel-dev/1Panel#5898]
### 1Panel 版本

v1.10.12-lts

### 请描述您的需求或者改进建议

能否提供对离线环境的支持?
我现在需要在内网环境中，大量的使用 1Panel。
或者有什么离线的解决方案？

**Comment by wanghe-fit2cloud** [comment]
目前我们提供了 x86_64 的离线安装包，应用商店中的应用暂时还不支持离线使用。我们将在 v2 版本中考虑支持离线环境。

**Comment by wan92hen** [comment]
你好，方便的话可以加下微信具体沟通下。
<img width="84" alt="1721639481058" src="https://github.com/user-attachments/assets/6668f517-e32e-438b-a84c-b3234378826f">
