### ISSUE TITLE
[BUG] 应用商店中的 Go 和 Java 点击详情页面的安装后，应跳转到运行环境页面，而不是应用安装页面

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#5900]
### 1Panel 版本

v1.10.12-lts

### 问题描述

应用商店中的 Go 和 Java 点击详情页面的安装后，应跳转到运行环境页面，而不是应用安装页面

### 重现步骤

应用列表选择 Java 或者 Go，点击图标进入右侧抽屉页面，点击 安装 按钮。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.13-lts 版本已发布。

**Comment by swordman20** [comment]
这个问题，我也存在，我的版本是v.1.10.14，也是在商店点击安装Java运行环境就跳转到，运行环境页面，而不是应用安装页面，无法安装Java、Node、Go，这是为什么

**Comment by wanghe-fit2cloud** [comment]
> 这个问题，我也存在，我的版本是v.1.10.14，也是在商店点击安装Java运行环境就跳转到，运行环境页面，而不是应用安装页面，无法安装Java、Node、Go，这是为什么

运行环境相关应用，都会统一跳转到 `网站` - `运行环境` 页面安装。
> 无法安装的问题，可以新建 discussion 或者 issue，提供错误截图、日志。
