### ISSUE TITLE
[BUG] Gitea安装的时候选择安装PG数据库报错

### ISSUE THREAD

**Issue by Anyexyz** [1Panel-dev/1Panel#5902]
### 联系方式

anyexyz@foxmail.com

### 1Panel 版本

v1.10.12-lts

### 问题描述

在安装 Gitea 的时候选择安装PG数据库报 `服务内部错误: record not found` 错误。

### 重现步骤

在安装 Gitea 的时候选择安装 PG 数据库报 `服务内部错误: record not found` 错误，经查看 URL 为 `/apps/all?install=postgres`，推测未作别名访问。

### 期待的正确结果

正常跳转 `/apps/all?install=postgresql` 并显示 PG 安装界面。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们已在本地环境复现了该问题，并将在近期版本中修复。
<img width="1288" alt="image" src="https://github.com/user-attachments/assets/a1389a65-f182-40cd-bb6b-195cfdc181ab">

**Comment by QYG2297248353** [comment]
> ### 问题描述
> 在安装 Gitea 的时候选择安装PG数据库报 `服务内部错误: record not found` 错误。

可以尝试使用 第三方应用商店，没有强制依赖数据库，有更多自定义选项，你值得拥有🥰
https://github.com/QYG2297248353/appstore-1panel?tab=readme-ov-file#%E7%BB%B4%E6%8A%A4%E7%8A%B6%E6%80%81


![image](https://github.com/user-attachments/assets/a432c4ca-9c85-4a43-a869-25f143369c2f)

**Comment by wanghe-fit2cloud** [comment]
v1.10.13-lts 版本已发布。
