### ISSUE TITLE
[BUG] 安装 OpenResty后不能安装南墙 waf，提示端口冲突如何解决

### ISSUE THREAD

**Issue by 1nformation** [1Panel-dev/1Panel#5907]
### 联系方式

misare.main@gmail.com

### 1Panel 版本

v1.10.12-lts

### 问题描述

安装 OpenResty后不能安装南墙 waf，提示端口冲突如何解决

### 重现步骤

安装 OpenResty后不能安装南墙 waf，提示端口冲突如何解决

**Comment by zhengkunwang223** [comment]
Openresty 和 南墙都是 Nginx 所以会有冲突
现在 Openresty 只有安装的时候可以指定端口
安装完之后因为配置文件中都使用了默认的 80 和 443 所以无法修改
