### ISSUE TITLE
[BUG]无法配置访问本地终端

### ISSUE THREAD

**Issue by ZACKLZ** [1Panel-dev/1Panel#5912]
### 联系方式

zacklz@163.com

### 1Panel 版本

v1.10.12-lts

### 问题描述

如下图报错
![image](https://github.com/user-attachments/assets/2bff4dd0-68bb-48b0-bd9d-30053d97aba2)

### 重现步骤

打开主机选项，点击终端，无论是配置现有主机127.0.0.1，还是新增局域网ip，都无法登录本地终端，也尝试去面板设置设置了服务器地址，依旧无效

### 期待的正确结果

可以正常使用终端功能访问本地服务器终端

**Comment by wanghe-fit2cloud** [comment]
https://github.com/1Panel-dev/1Panel/discussions/5286
