### ISSUE TITLE
[FEATURE]建议在应用商店上架Keyclock

### ISSUE THREAD

**Issue by daishengli** [1Panel-dev/1Panel#5915]
### 1Panel 版本

v1.10.12-lts

### 请描述您的需求或者改进建议

目前商店还没有一款单点登录应用，可以上架一下 https://github.com/keycloak/keycloak 方便一键部署

### 请描述你建议的实现方案

在应用商店中添加 Keycloak

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上架 Keyclock

**Comment by wanghe-fit2cloud** [comment]
单点登录相关应用，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4447
