### ISSUE TITLE
[FEATURE]主机文件相关的两个优化建议

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#5916]
### 1Panel 版本

v1.10.12-lts

### 请描述您的需求或者改进建议

优化1：在`主机` > `文件` 中解压文件时，希望可以支持win上一般解压软件都有的`解压到xxx中`功能（xxx指该压缩文件名称）。因为有的时候可能是直接对文件夹压缩，如果默认解压到当前路径中会和路径下其他文件混在一起

优化2：在`主机` > `文件` 中新建文件或文件夹时，可以在输入完名称之后直接按回车完成创建，每次都要移动鼠标点`确定`在需要创建较多对象时效率较低。

希望可以考虑支持！

**Comment by wanghe-fit2cloud** [comment]
1. 解压操作支持手动修改路径（默认是当前路径）。如果想将文件解压到 xxx 目录，就需要手动来编辑解压路径了。
2. 在 v2 版本重构时，我们会考虑为部分表单添加回车提交事件。
