### ISSUE TITLE
[BUG]文件编辑器序号问题

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#5918]
### 1Panel 版本

v1.10.12-lts

### 问题描述

日志超过10000行，显示宽度过短问题：
![PixPin_2024-07-23_16-00-56](https://github.com/user-attachments/assets/04775a1d-fc0f-44e3-b577-0b07ecdad92b)

### 重现步骤

超过10000行

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本优化上述体验。

**Comment by wanghe-fit2cloud** [comment]
v1.10.15-lts 版本已发布。
