### ISSUE TITLE
[FEATURE]: go运行环境可以指定goproxy

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [1Panel-dev/1Panel#5923]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

在私有环境时，go构建会比较难用,希望在新建go环境时，可以指定goproxy

### 请描述你建议的实现方案

在创建时，编译容器内执行go env -w goproxy=${proxy_address}

**Comment by zhengkunwang223** [comment]
感谢建议 我们会在后续版本优化此处

**Comment by wanghe-fit2cloud** [comment]
创建运行环境支持环境变量需求，参考：https://github.com/1Panel-dev/1Panel/issues/4262
