### ISSUE TITLE
登录日志怎么删除 今天打开一看 60万条

### ISSUE THREAD

**Issue by PromiseAll** [1Panel-dev/1Panel#5924]
### 1Panel 版本

1.10.13

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/9e1a11c8-31b1-4044-b04f-1914e1083333)

**Comment by zhengkunwang223** [comment]
登录日志是从你的机器上读取的 
/var/log/secure 或者  /var/log/auth.log 
建议了解相关知识之后 谨慎删除
