### ISSUE TITLE
[需求提交] 1PANEL OpenResty

### ISSUE THREAD

**Issue by garrettdo** [1Panel-dev/1Panel#5928]
### 1Panel 版本

专业版：v1.10.13-lts

### 请描述您的需求或者改进建议

1、OpenResty的网站配置支持负载均衡
2、OpenResty的网站配置支持stream配置
3、OpenResty的网站配置upstream支持域名解析自动刷新

### 请描述你建议的实现方案

1、upstream负载均衡
2、交互式配置stream
3、nginx可以新增模块实现
```
# nginx-upstream-dynamic-servers
    resolver 8.8.8.8 1.1.1.1 valid=10s;
    resolver_timeout 30s;
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，关于网站设置负载均衡需求的讨论，统一汇总到该 issue #2058

**Comment by garrettdo** [comment]
新增 stream 有安排下个版本吗

**Comment by garrettdo** [comment]
upstream 如果配置了域名，可以支持对域名做动态解析吗？

**Comment by garrettdo** [comment]
单个网站的黑白名单什么时候可以加上 IP 组呢

目前规则一个一个加 IP 好繁琐
