### ISSUE TITLE
[BUG]提示框会撑高界面

### ISSUE THREAD

**Issue by GunnmF** [1Panel-dev/1Panel#5929]
### 联系方式

moumou.v1@foxmail.com

### 1Panel 版本

v1.10.13-lts

### 问题描述

![image](https://github.com/user-attachments/assets/3f46dd5b-8b43-4caf-a231-9d67899cd6a2)

### 重现步骤

![image](https://github.com/user-attachments/assets/5f51e5a5-a9cb-4fe2-ad62-904a5ffa33ce)

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
