### ISSUE TITLE
[BUG]OpenResty修改配置文件，重启后配置文件会被还原

### ISSUE THREAD

**Issue by liu-yfeng** [1Panel-dev/1Panel#5930]
### 1Panel 版本

v1.10.13-lts

### 问题描述

从这里修改的配置文件：
![image](https://github.com/user-attachments/assets/7d319abf-56b0-4bca-b4e3-06945a0567a2)
从这里点停止，再启动：
![image](https://github.com/user-attachments/assets/f9368436-8224-40fb-9ef7-76ef2c6fd8a0)
配置文件会被还原
但是在这个地方重启就没有问题
![image](https://github.com/user-attachments/assets/806bb5d6-98bc-4c54-bcbd-3d9c64a7d3a5)

PHP 运行环境是本地的
![image](https://github.com/user-attachments/assets/0959bc10-06db-40bf-99a6-8397c4471630)

### 重现步骤

修改配置文件后，重启站点，配置文件会被还原

**Comment by zhengkunwang223** [comment]
感谢建议 我们先复现一下

**Comment by wanghe-fit2cloud** [comment]
请提供具体修改了哪些配置。
我们在本地环境中尝试了一键部署和 PHP 运行环境两种类型的网站进行配置修改，但未能复现配置被还原的问题。

**Comment by liu-yfeng** [comment]
![image](https://github.com/user-attachments/assets/86ddfbec-56e2-46bc-951e-745d2b7291cb)
这部分是后面加的，重启后这部分内容就没了

**Comment by liu-yfeng** [comment]
![image](https://github.com/user-attachments/assets/97c90bd1-c76d-4de5-8f88-28e5e5be0b24)
这部分是新加的，重启后这部分内容就没了

**Comment by wanghe-fit2cloud** [comment]
> ![image](https://private-user-images.githubusercontent.com/8706840/353728011-97c90bd1-c76d-4de5-8f88-28e5e5be0b24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTAwMjcsIm5iZiI6MTcyMjQwOTcyNywicGF0aCI6Ii84NzA2ODQwLzM1MzcyODAxMS05N2M5MGJkMS1jNzZkLTRkZTUtOGY4OC0yOGU1ZTViZTBiMjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMDcwODQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTdhZjRmOTI5NTc1YzI4ODg0NjVkZTY2OGRlYTkzODRlYmQ4YjQ3ODY4YWY3NjRmODliMzVjYmY1MzJkNTcwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DG6yswJ2pH-TkfA3tNCrlUjAbc7Rcef2QW_WflzhU-A) 这部分是新加的，重启后这部分内容就没了

这是什么类型的网站？
> 你截图中标红的部分是 PHP 运行环境网站默认提供的配置。

**Comment by liu-yfeng** [comment]
![image](https://github.com/user-attachments/assets/5473decb-3047-478a-841b-5f3ae594edb9)
PHP ，重启后变成这样了，这个才是默认的

**Comment by liu-yfeng** [comment]
PHP环境是手动启动的，不是从应用商店安装的

**Comment by zhengkunwang223** [comment]
> PHP环境是手动启动的，不是从应用商店安装的

停止网站是会删除配置 然后把 root 目录指向网站停止页面 所以你的配置会丢失
停止再启动并不是重启网站 是关闭网站首页再打开 
你这种情况 建议使用重载

**Comment by liu-yfeng** [comment]
好吧
