### ISSUE TITLE
反向代理默认 Connection 请求头固定为 "upgrade"

### ISSUE THREAD

**Issue by wan92hen** [1Panel-dev/1Panel#5937]
### 1Panel 版本

v1.10.13-lts

### 问题描述

默认生成的反向代理配置文件，使用了如下配置，导致在非预期的情况下升级了 websocket 连接。
```
proxy_set_header Connection "upgrade";
```

### 重现步骤

创建网站，查看网站配置文件，或者查看添加的反向代理规则配置文件。

### 期待的正确结果

配置文件中使用变量，保留客户端传入的 Connection 请求头
```
proxy_set_header Connection $http_connection;
```

**Comment by wanghe-fit2cloud** [comment]
后续版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
