### ISSUE TITLE
[FEATURE]应用支持配置版本说明

### ISSUE THREAD

**Issue by wan92hen** [1Panel-dev/1Panel#5946]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

希望可以在升级应用界面查看到目标版本的发行日志或其他说明信息，方便应用发布者进行相关注意事项的说明。

**Comment by wanghe-fit2cloud** [comment]
重复需求 https://github.com/1Panel-dev/1Panel/issues/5874
