### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mengbuxiu** [1Panel-dev/1Panel#5947]
### 1Panel 版本

v1.10.13-lts

### 问题描述

系统设置，选择供应商>添加 Ollama，点击添加报错
![image](https://github.com/user-attachments/assets/a43f784f-cad0-48d2-8bf6-a3703dc12fff)

### 重现步骤

系统设置，选择供应商>添加 Ollama，点击添加报错
![image](https://github.com/user-attachments/assets/a43f784f-cad0-48d2-8bf6-a3703dc12fff)

**Comment by wanghe-fit2cloud** [comment]
MaxKB 项目组已经给出了答案，参考 https://github.com/1Panel-dev/MaxKB/issues/879
