### ISSUE TITLE
[FEATURE]  应用商店增加 Tdengine 时序数据库

### ISSUE THREAD

**Issue by 129duckflew** [1Panel-dev/1Panel#5952]
### 1Panel 版本

1.10.13-lts

### 请描述您的需求或者改进建议

应用商店增加 Tdengine 时序数据库

**Comment by wanghe-fit2cloud** [comment]
重复需求 https://github.com/1Panel-dev/1Panel/issues/5207

**Comment by wanghe-fit2cloud** [comment]
已上架到 1Panel 应用商店。
