### ISSUE TITLE
[FEATURE]自定义应用配置

### ISSUE THREAD

**Issue by superen7527** [1Panel-dev/1Panel#5956]
### 1Panel 版本

最新版

### 请描述您的需求或者改进建议

希望docker应用重建可以自定义修改部分配置。
就比如nexus里面你们内置的应用是需要多次开放多个端口，但是创建以后就不能改端口映射
我进容器主页改compose文件重新up是可以了
但是下次更新你们又把compose默认了。我改的配置全部失效清空变成默认的了。。

### 请描述你建议的实现方案

1.添加自定义的配置 快速重建或编辑应用
2.如果短时间没办法实现 那么更新应用则考虑增量修改compose文件而不是全部覆盖

**Comment by wanghe-fit2cloud** [comment]
1、我们会在 v2 版本中考虑是否支持编辑应用端口的需求。目前，你可以通过手动编辑 `docker-compose` 文件来实现。
2、升级应用时，新版本的 `docker-compose` 文件不会默认覆盖旧版本，你可以手动生成新版本的文件，具体操作如下图所示：
<img width="1474" alt="image" src="https://github.com/user-attachments/assets/7f35e11b-b84d-4cd4-b9df-9a54ba065ce0">
