### ISSUE TITLE
[FEATURE]建议回收站文件按时间排序选项 

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#5957]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

目前回收站文件是按名称排序，想找最近删除的一系列文件很不方便，希望能够增加按时间排序的功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
