### ISSUE TITLE
[BUG] 日志面板无法显示正确的 error log

### ISSUE THREAD

**Issue by realskyrin** [1Panel-dev/1Panel#5958]
### 1Panel 版本

v1.10.13-lts

### 问题描述

部分应用安装失败的情况下，控制台无法正常显示错误日志

系统：Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-1055-oracle aarch64)

### 重现步骤

从应用商店或自行安装应用出现异常的情况下

### 期待的正确结果

在日志面板看到正确的 error log

### 相关日志输出

```shell
exec ./docker-entrypoint.sh: exec format error
```

### 附加信息

<img width="730" alt="image" src="https://github.com/user-attachments/assets/3652891d-00da-4740-9f6b-49ba7949390e">

**Comment by wanghe-fit2cloud** [comment]
你提供的截图显示的是应用容器运行后的错误，1Panel 面板系统日志不会记录具体的应用日志。
> 这个错误是因为容器与你的服务器架构不兼容导致的。
