### ISSUE TITLE
[FEATURE] 外观样式建议

### ISSUE THREAD

**Issue by realzolo** [1Panel-dev/1Panel#596]
### 1Panel 版本

v1.0.5.2

### 请描述您的需求或者改进建议

开发者您好，我想提个小建议。能否在设置里面增加一个样式CSS自定义输入框，能够满足使用者对某些样式的覆盖。我是一个对外观很敏感的人，1Panel这个面板总的来说还是很好看的，但是某些点可能没有达到预期。如果开发者看到此条issue，请考虑一下能否增加这个功能！感谢🙏

**Comment by zhengkunwang223** [comment]
目前没有增加这个功能的计划，你可以给我们提 pr ，谢谢

**Comment by Felmon** [comment]
+1

> ### 1Panel 版本
> v1.0.5.2
> 
> ### 请描述您的需求或者改进建议
> 开发者您好，我想提个小建议。能否在设置里面增加一个样式CSS自定义输入框，能够满足使用者对某些样式的覆盖。我是一个对外观很敏感的人，1Panel这个面板总的来说还是很好看的，但是某些点可能没有达到预期。如果开发者看到此条issue，请考虑一下能否增加这个功能！感谢🙏
> 
> ### 请描述你建议的实现方案
> _No response_
> 
> ### 附加信息
> _No response_

+1   css算是个性化了，提pr必然又会导致众口难调，加个CSS自定义输入框算是目前开源项目个性化常见解决方案了
