### ISSUE TITLE
[FEATURE] 关于反向代理添加SNI的一个小问题

### ISSUE THREAD

**Issue by cli-r** [1Panel-dev/1Panel#5960]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

在 #3898 和 #5535 中提到添加 `proxy_ssl_server_name on | off;` 参数用以反向代理HTTPS的网站，但是在实际测试中只添加本参数并不能正确的加载网站，还应添加 `proxy_ssl_name example.com` 参数，否则会出现502错误。

### 附加信息

复现方法：反向代理1panel创建的https网站，未开启1panel面板中的回源 SNI选项，开启回源SNI但是未添加proxy_ssl_name，开启回源SNI并添加proxy_ssl_name，前两者均为502。

**Comment by wanghe-fit2cloud** [comment]
感谢你的反馈，我们会在后续版本中考虑你的建议。

**Comment by wanghe-fit2cloud** [comment]
v1.10.19-lts 版本已发布。
