### ISSUE TITLE
[BUG] 应用商店中已安装MySQL 但安装按钮仍然可点击

### ISSUE THREAD

**Issue by doveppp** [1Panel-dev/1Panel#5964]
### 1Panel 版本

v1.10.13-lts

### 问题描述

![image](https://github.com/user-attachments/assets/edc387af-5454-4405-974a-2d536f980a8d)

F12中这个button并没有被disable
![image](https://github.com/user-attachments/assets/56a9fcae-9c11-4314-9496-93c06726ddae)

后台接口返回的数据是对的
![image](https://github.com/user-attachments/assets/88858a02-8680-4271-b659-0765f0a399ea)

### 重现步骤

正常从应用商店安装MySQL  版本:8.2.0

**Comment by 9a6c** [comment]
一台机器可以安装多个mysql是正常的，你可以翻一翻前面需求。 你总不能限制一台机器只能安装一个mysql吧
