### ISSUE TITLE
新建文件夹支持添加空格

### ISSUE THREAD

**Issue by AcoFork** [1Panel-dev/1Panel#5975]
### 联系方式

hazalita@acofork.cn

### 1Panel 版本

社区版：v1.10.13-lts

### 问题描述

新建文件夹不能添加空格，但是已有的文件夹可以重命名后添加空格。比如新建文件夹不能命名为"Season 1“。只能是"Season1”

### 重现步骤

默认就可以复现

### 期待的正确结果

创建的时候就能添加空格

### 附加信息

plex等影音库软件需要规范命名，比如"Season 1"

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
