### ISSUE TITLE
[FEATURE]WAF 拦截记录支持通过动作进行筛选

### ISSUE THREAD

**Issue by wan92hen** [1Panel-dev/1Panel#5979]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

WAF 中的拦截记录，支持通过动作进行筛选。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
