### ISSUE TITLE
[BUG]创建Nodejs运行环境时报错

### ISSUE THREAD

**Issue by lijing-2008** [1Panel-dev/1Panel#5986]
### 联系方式

huyispider@gmail.com

### 1Panel 版本

v1.10.13-lts

### 问题描述

在创建nodejs运行时环境时  报错: 服务器内部错误：gzip: invalid header
![error](https://github.com/user-attachments/assets/92441fda-b770-4a95-b1aa-6cf3748868c2)

### 重现步骤

就是简单的创建一个运行时环境而已

**Comment by wanghe-fit2cloud** [comment]
进去 `主机` - `终端` 页面，执行 `tar --version` 命令检查一下 tar 命令版本
