### ISSUE TITLE
[BUG] 安装时，会有一次需要多输入一次回车

### ISSUE THREAD

**Issue by Shazoo** [1Panel-dev/1Panel#5994]
### 1Panel 版本

last

### 问题描述

![image](https://github.com/user-attachments/assets/6a6448f2-a501-4df9-a680-55620e728e1c)

在这里，必须每次都多敲一个回车才会继续。

（安装了大概10多台了，都是如此）

### 重现步骤

ubuntu 22.04
curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sudo bash quick_start.sh

**Comment by wanghe-fit2cloud** [comment]
这一步是输入用户密码（不会明文显示），完成后按回车继续。如果不自定义密码，直接回车则使用默认密码。

**Comment by Shazoo** [comment]
> 这一步是输入用户密码（不会明文显示），完成后按回车继续。如果不自定义密码，直接回车则使用默认密码。

嗯。我也有过这个猜测。建议加点提示。

**Comment by wanghe-fit2cloud** [comment]
> > 这一步是输入用户密码（不会明文显示），完成后按回车继续。如果不自定义密码，直接回车则使用默认密码。
> 
> 嗯。我也有过这个猜测。建议加点提示。

好的，我们在后续版本中优化。
