### ISSUE TITLE
[BUG]WAF设置内时间单位不对

### ISSUE THREAD

**Issue by luoshan5261486** [1Panel-dev/1Panel#5998]
### 1Panel 版本

1.10.13

### 问题描述

![微信截图_20240801153301](https://github.com/user-attachments/assets/5d27d68d-4445-4fe8-a815-a6d03698c51b)
![微信截图_20240801153336](https://github.com/user-attachments/assets/f7dc2f5e-3e0a-400d-83a2-be96d7edabfc)
攻击频率限制和404频率限制时间单位有问题

### 重现步骤

1

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
