### ISSUE TITLE
[FEATURE]计划任务能否增加恢复应用备份选项

### ISSUE THREAD

**Issue by maogeddd** [1Panel-dev/1Panel#6001]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

能否在计划任务增加定期或定时从服务器磁盘或sftp恢复应用备份的选项

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。考虑到自动恢复操作本身可能带来一些风险，因此我们目前不打算支持这个功能，望理解。

**Comment by maogeddd** [comment]
那能否在1panel app 命令行中增加备份恢复功能
