### ISSUE TITLE
希望官方应用商店支持一下nocodb

### ISSUE THREAD

**Issue by allyn0303** [1Panel-dev/1Panel#6004]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

希望官方应用商店支持一下https://github.com/nocodb/nocodb

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上架该应用。

**Comment by QYG2297248353** [comment]
好东西，好东西，我试试

**Comment by QYG2297248353** [comment]
> 希望官方应用商店支持一下https://github.com/nocodb/nocodb

可在第三方应用商店提前尝试使用，经过测试已通过安装测试

https://github.com/QYG2297248353/appstore-1panel?tab=readme-ov-file#%E7%BB%B4%E6%8A%A4%E7%8A%B6%E6%80%81

## 安装预览

![image](https://github.com/user-attachments/assets/eea9b102-56b5-4e16-897d-53a02154e952)

**Comment by wanghe-fit2cloud** [comment]
应用已上架。
进入应用商店列表，点击右上角的【更新应用列表】按钮，待同步完成后即可安装应用。
