### ISSUE TITLE
[BUG]网站反向代理，开启https时，非443端口，配置文件默认是443端口

### ISSUE THREAD

**Issue by PrestarLin** [1Panel-dev/1Panel#6005]
### 1Panel 版本

v1.10.13-lts

### 问题描述

我用1panel新建反向代理网站，代理群晖5001 https端口，网站里设置开启https，发现配置文件里监听的还是443端口，导致需要手动修改配置文件。
新建网站的界面需要完善，比如需要一开始就开启https的，没有直接的设置向导。

问题和 #5982一样，我认为是一个bug，不开启https则可以正确设置监听端口

### 重现步骤

可以试一下，反向代理开启https

**Comment by PrestarLin** [comment]
#5982

**Comment by wanghe-fit2cloud** [comment]
> #5982

该 issue 已重新打开，我们将在后续版本中支持。
