### ISSUE TITLE
[FEATURE]网站域名设置和端口设置分开

### ISSUE THREAD

**Issue by wan92hen** [1Panel-dev/1Panel#6008]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

建议将网站的域名设置和端口设置分开，即在现在的域名设置中，不再配置及显示端口，仅要求用户输入域名即可。
端口配置提供额外的设置项，可以设置监听端口及是否启用 SSL。

目前的配置存在几个问题：
1. 用户期望使用自定义的 HTTPS 端口时，只能通过修改配置文件的方式处理；
2. 配置 a.domain.com:80 和 b.domain.com:8080，这两条域名记录，实际上 a.domain.com:8080 和 b.domain.com:80 也是可以访问的，跟展示出来的配置并不完全匹配；

将域名和端口分开配置后可以比较好地解决上面两个问题，同时也可以更好地跟原始配置文件 `listen` 和 `server_name` 两项配置对应起来。

**Comment by wanghe-fit2cloud** [comment]
参考 #5982
