### ISSUE TITLE
[FEATURE]文件夹选择控件，进入目录的最后一层后，点击右下角确定按钮应该直接选中该文件夹

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#6012]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

如题。

当前版本，点击确定按钮会报错 `目录不存在`，如图：
![图片](https://github.com/user-attachments/assets/ee767825-74e3-45ff-be60-b9b096ce3436)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
