### ISSUE TITLE
[BUG]从 JetBrains IDE 中拖拽文件进行上传报错

### ISSUE THREAD

**Issue by WankkoRee** [1Panel-dev/1Panel#6016]
### 1Panel 版本

v1.10.13-lts

### 问题描述

此问题在`v1.10.12-lts`后可复现，猜测与 #5655 的某些改动有关。

从文件资源管理器中拖拽上传正常，但是从 JetBrains IDE 的左侧文件树中拖拽上传就会在控制台中报错。

```js
index-BueaJKS8.js:14
TypeError: Cannot read properties of null (reading 'isFile')
    at pn (index-B6GgAEgO.js:1:17346)
    at index-B6GgAEgO.js:1:16997
    at Array.map (<anonymous>)
    at Mt (index-B6GgAEgO.js:1:16989)
    at Yr (index-BueaJKS8.js:14:1344)
    at xo (index-BueaJKS8.js:14:1415)
    at HTMLDivElement.n (index-BueaJKS8.js:18:8250)
```

### 重现步骤

打开拖拽上传面板，从 JetBrains IDE 的左侧文件树拖拽文件进行上传。

**Comment by zhengkunwang223** [comment]
感谢反馈，我们先复现一下

**Comment by QYG2297248353** [comment]
确实是，上传文件，拖拽没反应

![image](https://github.com/user-attachments/assets/bdd5b69b-9fe6-4bcf-87ef-2e4814acbddd)

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
