### ISSUE TITLE
[FEATURE]希望官方支持一下FreshRSS

### ISSUE THREAD

**Issue by 46fafa** [1Panel-dev/1Panel#6019]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

希望官方应用商店能够上架[FreshRSS](https://github.com/FreshRSS/FreshRSS)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上架该应用。

**Comment by 46fafa** [comment]
> 感谢反馈，我们会在后续版本考虑上架该应用。

谢谢回复，祝越来越好。

**Comment by wanghe-fit2cloud** [comment]
应用已上架。
进入应用商店列表，点击右上角的【更新应用列表】按钮，待同步完成后即可安装应用。
