### ISSUE TITLE
[BUG] 应用商店SFTPGo的文档说明链接失效

### ISSUE THREAD

**Issue by alittlehuaji** [1Panel-dev/1Panel#6025]
### 联系方式

huajibenji@outlook.com

### 1Panel 版本

v1.10.13-lts

### 问题描述

SFTPGo的文档说明链接404

### 重现步骤

应用商店 -> SFTPGo -> 文档说明

### 期待的正确结果

跳转到https://sftpgo.github.io/latest/

### 附加信息

![image](https://github.com/user-attachments/assets/494b320c-cf56-40fe-a0b6-a9bec5b6d088)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
已更新并推送至正式仓库。可以进入应用商店列表，点击右上角的【更新应用列表】按钮，待同步完成后再来查看文档说明。
