### ISSUE TITLE
[BUG] `1panel-network` 删除造成的容器无法启动

### ISSUE THREAD

**Issue by QYG2297248353** [1Panel-dev/1Panel#6029]
### 联系方式

qyg2297248353@gmail.com

### 1Panel 版本

v1.10.13-lts

### 问题描述

根据配置容器IPV6
https://1panel.cn/docs/user_manual/containers/setting/?h=ipv6#2-ipv6

最后一步创建 1panel-network 网络
但是已经存在，因此只好删除
删除提示正在使用
那我停止了所有容器
再去删除
删除成功后我就创建了一样的网络，启用 ipv6
问题是在 新创建的 1panel-network 网络中启用v6并填写 bridge 的一样的 v6子网地址
![image](https://github.com/user-attachments/assets/94832c73-e301-4f9c-a66d-03198e688945)

提示失败
```
服务内部错误: Error response from daemon: Pool overlaps with other one on this address space
```
![image](https://github.com/user-attachments/assets/89d0324d-9c27-47c3-b055-48802b06a106)

那好吧，不搞了，就没有启用v6,创建了网络
再去启动所有停止的容器
结果 所有容器都起不来了

提示 网络 id 不存在 (都删除新建了，肯定不一样)

### 重现步骤

停止所有容器

删除 1panel-network 网络

创建新 1panel-network 网络 (目的是，启用v6)

启动所有容器

### 期待的正确结果

我希望，配置 v6 网络应该简单点

容器配置 开启v6后，就应该给所有桥接网络配置v6子网，配置太麻烦了

容器绑定的应该是网络id ，启动时不存在时，就根据网络名称查询，找到了就更新网络id 后继续执行启动任务

为了解决网络id不存在，30多个容器，一个个手动修改到桥接网络，累死人

**Comment by wanghe-fit2cloud** [comment]
- 容器配置 IPv6 也是参考的 docker 官网，应该没有太简单的办法，就是需要指定子网等信息。
- 容器在启动时会引用网络的 ID，而不是网络的名称，这点也没有太好的办法。在生产环境中，尽量避免删除网络。
