### ISSUE TITLE
[BUG] 检查更新提示当前已是最新版本

### ISSUE THREAD

**Issue by ariakeumi** [1Panel-dev/1Panel#6034]
### 1Panel 版本

v1.10.6-lts

### 问题描述

1panel v1.10.6-lts ，检查更新提示当前已是最新版本。

![QQ截图20240806084217](https://github.com/user-attachments/assets/bfef4de1-17c6-415a-984e-2938d1530b85)

### 重现步骤

.

**Comment by ssongliu** [comment]
感谢反馈，参考下面链接手动升级一下
https://bbs.fit2cloud.com/t/topic/5579
