### ISSUE TITLE
[BUG] OpenResty 反向代理设置的配置问题

### ISSUE THREAD

**Issue by JHPZ** [1Panel-dev/1Panel#6037]
### 联系方式

1014733907@qq.com

### 1Panel 版本

v1.10.13-lts

### 问题描述

不确定是不是BUG，但手动修改配置后的确好了。
反向代理的网站，添加了新的监听端口，新的监听端口不监听ssl http2
![image](https://github.com/user-attachments/assets/49b4457c-2252-4374-af1e-ae3f7cfb093a)

### 重现步骤

步骤:
1.配置网站反向代理后，给网站添加HTTPS。

2.给网站添加新的监听端口。
![image](https://github.com/user-attachments/assets/cdb4c72b-b6f9-4b98-af59-c0fe62886683)

3. 此时，新的端口不监听ssl

### 期待的正确结果

如果配置了ssl，并且用户配置了其他监听端口，支持让用户选择此端口是否是ssl监听模式

**Comment by zhengkunwang223** [comment]
这个我们会放在 V2 版本优化
