### ISSUE TITLE
[BUG] 收藏夹的目录不存在无法删除

### ISSUE THREAD

**Issue by deleteDB** [1Panel-dev/1Panel#6045]
### 1Panel 版本

v1.10.13

### 问题描述

收藏夹的收藏的目录如果不存在没办法删除
![image](https://github.com/user-attachments/assets/67376f7b-3abf-4bf3-bd22-92c9c6e44913)

### 重现步骤

创建一个目录然后收藏 ，使用命令行删除文件夹，然后点击收藏的目录显示目录不存在，主要是没办法取消收藏，还得创建回原来的目录才可以取消收藏.

**Comment by deleteDB** [comment]
建议可以在收藏目录  那里有加一个删除图标之类的 怕误触就加个询问框啥的 也就解决了这个尴尬的问题
![QQ_1722953970588](https://github.com/user-attachments/assets/e56bd81f-d087-4bef-9bda-d22e7903b072)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
点击 `收藏夹` 按钮，进入右侧抽屉页面，可以进行删除操作，如图：
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/0ac92a20-3ee4-491c-9a6c-6bded37f29e8">
<img width="753" alt="image" src="https://github.com/user-attachments/assets/e451da82-5d2d-4bf8-aa61-9a57f2bb990d">
