### ISSUE TITLE
[BUG]WAF关闭，openresty卸载，接口一直被拦截403，试尽各种办法，确定是这边问题

### ISSUE THREAD

**Issue by hanjunchen** [1Panel-dev/1Panel#6046]
### 1Panel 版本

社区版：v1.10.13-lts

### 问题描述

因为是自定义表单设计，页面会写js代码提交，同一个接口请求参数body中含有document.getElementsByClassName等字样提交时，就会报错：网络异常，请检查您的网络连接是否正常! 返回403，
![image](https://github.com/user-attachments/assets/c298cf1f-fea8-4607-9001-2dc26848074b)
![image](https://github.com/user-attachments/assets/e6520629-be4c-46b9-894e-6374bdf2ad49)

只要含有这一段就无法提交
![image](https://github.com/user-attachments/assets/b852054e-6b44-4a3b-83b7-82f5417daa22)

可以肯定是被waf之类的拦截了，本地接口怎么都能提交，放到服务器上出现js方法就不行，关闭waf以及里面所有子项，能关的都关了还是不行，甚至openresty都卸载了，装了个nginx跑项目仍然被拦截，还有个环境用的是宝塔部署也没问题，大佬帮帮忙，实在解决不了

### 重现步骤

post接口请求字符串参数中，带有如下字样时就无法提交，把这段注释掉或删掉就能提交
![image](https://github.com/user-attachments/assets/b4b8728c-0712-427b-ac29-6e6a114773d2)

### 期待的正确结果

怎么才能关闭该防御

**Comment by zhengkunwang223** [comment]
高级功能-WAF-全局设置 关闭了吗？

**Comment by hanjunchen** [comment]
> 高级功能-WAF-全局设置 关闭了吗？

关闭了的，里面每一个大小项都关了，后来索性把openresty也卸载了
![image](https://github.com/user-attachments/assets/f5ce85a1-f2a6-46fe-a504-c5f1bf26f8fd)

**Comment by zhengkunwang223** [comment]
> > 高级功能-WAF-全局设置 关闭了吗？
> 
> 关闭了的，里面每一个大小项都关了，后来索性把openresty也卸载了 ![image](https://private-user-images.githubusercontent.com/19944029/355650478-f5ce85a1-f2a6-46fe-a504-c5f1bf26f8fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTczMjIsIm5iZiI6MTcyMjk5NzAyMiwicGF0aCI6Ii8xOTk0NDAyOS8zNTU2NTA0NzgtZjVjZTg1YTEtZjJhNi00NmZlLWE1MDQtYzVmMWJmMjZmOGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAyMTcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZjFjZDJiNzY5NTljOGIxMDg4YWQ5ZTBlNzUzMzYyMzgwMGE5ZGVlOWZiMmE5MGM4ZGNiNWYxNDYzYzQ5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HDAcdAThSc4ZC8MQbCGapGC9UlFPlz3Zob5S6-awS7o)

openresty 卸载了那就不是 1panel 这边的问题了，看看你应用或者是 CDN 之类的

**Comment by hanjunchen** [comment]
> > > 高级功能-WAF-全局设置 关闭了吗？
> > 
> > 
> > 关闭了的，里面每一个大小项都关了，后来索性把openresty也卸载了 ![image](https://private-user-images.githubusercontent.com/19944029/355650478-f5ce85a1-f2a6-46fe-a504-c5f1bf26f8fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTczMjIsIm5iZiI6MTcyMjk5NzAyMiwicGF0aCI6Ii8xOTk0NDAyOS8zNTU2NTA0NzgtZjVjZTg1YTEtZjJhNi00NmZlLWE1MDQtYzVmMWJmMjZmOGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAyMTcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZjFjZDJiNzY5NTljOGIxMDg4YWQ5ZTBlNzUzMzYyMzgwMGE5ZGVlOWZiMmE5MGM4ZGNiNWYxNDYzYzQ5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HDAcdAThSc4ZC8MQbCGapGC9UlFPlz3Zob5S6-awS7o)
> 
> openresty 卸载了那就不是 1panel 这边的问题了，看看你应用或者是 CDN 之类的

应用也不会拦截，这个接口完整的curl放到postman是可以通的，检查了下项目也没用到CDN，还有其他可能性吗，大佬提供个思路呢
![image](https://github.com/user-attachments/assets/1aea69ae-fac8-4df0-9962-a89197a71970)

**Comment by hanjunchen** [comment]
> > > > 高级功能-WAF-全局设置 关闭了吗？
> > > 
> > > 
> > > 关闭了的，里面每一个大小项都关了，后来索性把openresty也卸载了 ![image](https://private-user-images.githubusercontent.com/19944029/355650478-f5ce85a1-f2a6-46fe-a504-c5f1bf26f8fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTczMjIsIm5iZiI6MTcyMjk5NzAyMiwicGF0aCI6Ii8xOTk0NDAyOS8zNTU2NTA0NzgtZjVjZTg1YTEtZjJhNi00NmZlLWE1MDQtYzVmMWJmMjZmOGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAyMTcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZjFjZDJiNzY5NTljOGIxMDg4YWQ5ZTBlNzUzMzYyMzgwMGE5ZGVlOWZiMmE5MGM4ZGNiNWYxNDYzYzQ5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HDAcdAThSc4ZC8MQbCGapGC9UlFPlz3Zob5S6-awS7o)
> > 
> > 
> > openresty 卸载了那就不是 1panel 这边的问题了，看看你应用或者是 CDN 之类的
> 
> 应用也不会拦截，这个接口完整的curl放到postman是可以通的，检查了下项目也没用到CDN，还有其他可能性吗，大佬提供个思路呢 ![image](https://private-user-images.githubusercontent.com/19944029/355654261-1aea69ae-fac8-4df0-9962-a89197a71970.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTgxMjAsIm5iZiI6MTcyMjk5NzgyMCwicGF0aCI6Ii8xOTk0NDAyOS8zNTU2NTQyNjEtMWFlYTY5YWUtZmFjOC00ZGYwLTk5NjItYTg5MTk3YTcxOTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAyMzAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NDVlN2RhMjg2NDNkOGNiZjhlZGZkZDU2ZTk0YTM1NDA1OWUzOGYwNThhMDYwMGI4MDM0YTMxNjMzYjczNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W1okRAiDPuwpqw30b65ICdcYO-CArPMPLWO7DLc5ABA)

**Comment by hanjunchen** [comment]
> > > > 高级功能-WAF-全局设置 关闭了吗？
> > > 
> > > 
> > > 关闭了的，里面每一个大小项都关了，后来索性把openresty也卸载了 ![image](https://private-user-images.githubusercontent.com/19944029/355650478-f5ce85a1-f2a6-46fe-a504-c5f1bf26f8fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTczMjIsIm5iZiI6MTcyMjk5NzAyMiwicGF0aCI6Ii8xOTk0NDAyOS8zNTU2NTA0NzgtZjVjZTg1YTEtZjJhNi00NmZlLWE1MDQtYzVmMWJmMjZmOGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAyMTcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZjFjZDJiNzY5NTljOGIxMDg4YWQ5ZTBlNzUzMzYyMzgwMGE5ZGVlOWZiMmE5MGM4ZGNiNWYxNDYzYzQ5NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HDAcdAThSc4ZC8MQbCGapGC9UlFPlz3Zob5S6-awS7o)
> > 
> > 
> > openresty 卸载了那就不是 1panel 这边的问题了，看看你应用或者是 CDN 之类的
> 
> 应用也不会拦截，这个接口完整的curl放到postman是可以通的，检查了下项目也没用到CDN，还有其他可能性吗，大佬提供个思路呢 ![image](https://private-user-images.githubusercontent.com/19944029/355654261-1aea69ae-fac8-4df0-9962-a89197a71970.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTkyNDQsIm5iZiI6MTcyMjk5ODk0NCwicGF0aCI6Ii8xOTk0NDAyOS8zNTU2NTQyNjEtMWFlYTY5YWUtZmFjOC00ZGYwLTk5NjItYTg5MTk3YTcxOTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAyNDkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1Y2U0MGUxZjA0Y2Q0NTVjMzE0MGFmYjRjNDQ0NDI4MWMyNGQwOGQzZDU1ODQ2YjM4ZTFiYjM3MzNjNWZmNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hfk8Jm-ieJrlecerNwMY_BzOerP8WonVe5rUSoa5QUE)

感谢大佬提供思路，好像因为设置了域名被路由器还是dns拦截了
