### ISSUE TITLE
[FEATURE] DNS账户添加对华为云的支持

### ISSUE THREAD

**Issue by Maklith** [1Panel-dev/1Panel#6047]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

证书申请的DNS账户中没有对华为云的支持

**Comment by zhengkunwang223** [comment]
当前我们优先支持 https://go-acme.github.io/lego/dns/ 这个列表中的 DNS 厂商 huawei 云不在其中
所以短期内不会增加 希望理解

**Comment by zhengkunwang223** [comment]
华为云提的小伙伴有点多 我们考虑实现 具体时间应该在 v2 版本发布之后的某个版本 请大家耐心等待

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
