### ISSUE TITLE
[BUG]创建nodejs环境失败

### ISSUE THREAD

**Issue by lijing-2008** [1Panel-dev/1Panel#6050]
### 联系方式

huyispider@gmail.com

### 1Panel 版本

v1.10.13-lts

### 问题描述

启动失败: node Pulling c6cf28de8a06 Pulling fs layer 891494355808 Pulling fs layer 6582c62583ef Pulling fs layer bf2c3e352f3d Pulling fs layer cd446f1fa464 Pulling fs layer 66434d5476a1 Pulling fs layer ed6379725fdf Pulling fs layer f30bb8632938 Pulling fs layer 45d4f82735ba Pulling fs layer cf6e47a2487d Pulling fs layer a36b1563fe38 Pulling fs layer bf2c3e352f3d Waiting cd446f1fa464 Waiting 66434d5476a1 Waiting ed6379725fdf Waiting f30bb8632938 Waiting 45d4f82735ba Waiting cf6e47a2487d Waiting a36b1563fe38 Waiting 6582c62583ef Retrying in 5 seconds c6cf28de8a06 Retrying in 5 seconds 891494355808 Retrying in 5 seconds 6582c62583ef Retrying in 4 seconds c6cf28de8a06 Retrying in 4 seconds 891494355808 Retrying in 4 seconds 6582c62583ef Retrying in 3 seconds c6cf28de8a06 Retrying in 3 seconds 891494355808 Retrying in 3 seconds 6582c62583ef Retrying in 2 seconds c6cf28de8a06 Retrying in 2 seconds 891494355808 Retrying in 2 seconds 6582c62583ef Retrying in 1 second c6cf28de8a06 Retrying in 1 second 891494355808 Retrying in 1 second 6582c62583ef Retrying in 10 seconds c6cf28de8a06 Retrying in 10 seconds 891494355808 Retrying in 10 seconds 6582c62583ef Retrying in 9 seconds c6cf28de8a06 Retrying in 9 seconds 891494355808 Retrying in 9 seconds 6582c62583ef Retrying in 8 seconds c6cf28de8a06 Retrying in 8 seconds 891494355808 Retrying in 8 seconds 6582c62583ef Retrying in 7 seconds c6cf28de8a06 Retrying in 7 seconds 891494355808 Retrying in 7 seconds 6582c62583ef Retrying in 6 seconds c6cf28de8a06 Retrying in 6 seconds 891494355808 Retrying in 6 seconds 6582c62583ef Retrying in 5 seconds c6cf28de8a06 Retrying in 5 seconds 891494355808 Retrying in 5 seconds 6582c62583ef Retrying in 4 seconds c6cf28de8a06 Retrying in 4 seconds 891494355808 Retrying in 4 seconds 6582c62583ef Retrying in 3 seconds c6cf28de8a06 Retrying in 3 seconds 891494355808 Retrying in 3 seconds 6582c62583ef Retrying in 2 seconds c6cf28de8a06 Retrying in 2 seconds 891494355808 Retrying in 2 seconds 6582c62583ef Retrying in 1 second c6cf28de8a06 Retrying in 1 second 891494355808 Retrying in 1 second error pulling image configuration: download failed after attempts=6: dial tcp 69.63.178.13:443: i/o timeout

### 重现步骤

不管创建什么样的nodejs环境都是一样，日志里也是什么都没有

### 期待的正确结果

希望能正确创建nodejs环境

### 相关日志输出

```shell
启动失败: node Pulling c6cf28de8a06 Pulling fs layer 891494355808 Pulling fs layer 6582c62583ef Pulling fs layer bf2c3e352f3d Pulling fs layer cd446f1fa464 Pulling fs layer 66434d5476a1 Pulling fs layer ed6379725fdf Pulling fs layer f30bb8632938 Pulling fs layer 45d4f82735ba Pulling fs layer cf6e47a2487d Pulling fs layer a36b1563fe38 Pulling fs layer bf2c3e352f3d Waiting cd446f1fa464 Waiting 66434d5476a1 Waiting ed6379725fdf Waiting f30bb8632938 Waiting 45d4f82735ba Waiting cf6e47a2487d Waiting a36b1563fe38 Waiting 6582c62583ef Retrying in 5 seconds c6cf28de8a06 Retrying in 5 seconds 891494355808 Retrying in 5 seconds 6582c62583ef Retrying in 4 seconds c6cf28de8a06 Retrying in 4 seconds 891494355808 Retrying in 4 seconds 6582c62583ef Retrying in 3 seconds c6cf28de8a06 Retrying in 3 seconds 891494355808 Retrying in 3 seconds 6582c62583ef Retrying in 2 seconds c6cf28de8a06 Retrying in 2 seconds 891494355808 Retrying in 2 seconds 6582c62583ef Retrying in 1 second c6cf28de8a06 Retrying in 1 second 891494355808 Retrying in 1 second 6582c62583ef Retrying in 10 seconds c6cf28de8a06 Retrying in 10 seconds 891494355808 Retrying in 10 seconds 6582c62583ef Retrying in 9 seconds c6cf28de8a06 Retrying in 9 seconds 891494355808 Retrying in 9 seconds 6582c62583ef Retrying in 8 seconds c6cf28de8a06 Retrying in 8 seconds 891494355808 Retrying in 8 seconds 6582c62583ef Retrying in 7 seconds c6cf28de8a06 Retrying in 7 seconds 891494355808 Retrying in 7 seconds 6582c62583ef Retrying in 6 seconds c6cf28de8a06 Retrying in 6 seconds 891494355808 Retrying in 6 seconds 6582c62583ef Retrying in 5 seconds c6cf28de8a06 Retrying in 5 seconds 891494355808 Retrying in 5 seconds 6582c62583ef Retrying in 4 seconds c6cf28de8a06 Retrying in 4 seconds 891494355808 Retrying in 4 seconds 6582c62583ef Retrying in 3 seconds c6cf28de8a06 Retrying in 3 seconds 891494355808 Retrying in 3 seconds 6582c62583ef Retrying in 2 seconds c6cf28de8a06 Retrying in 2 seconds 891494355808 Retrying in 2 seconds 6582c62583ef Retrying in 1 second c6cf28de8a06 Retrying in 1 second 891494355808 Retrying in 1 second error pulling image configuration: download failed after attempts=6: dial tcp 69.63.178.13:443: i/o timeout
```

**Comment by zhengkunwang223** [comment]
拉取镜像超时，参考 https://bbs.fit2cloud.com/t/topic/5886
