### ISSUE TITLE
[BUG]1p重启后  计划任务中断，能不能重启后继续计划任务

### ISSUE THREAD

**Issue by Alexzzz2008** [1Panel-dev/1Panel#6052]
### 联系方式

1

### 1Panel 版本

1.10.13

### 问题描述

1p重启后  计划任务中断，能不能重启后继续计划任务
![PixPin_2024-08-07_13-51-37](https://github.com/user-attachments/assets/73c1c558-324b-4ca1-9269-9e3cc8d81964)

### 重现步骤

1

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，由于我们的计划任务是通过 1Panel 系统控制的，且任务类型多样，我们无法控制每个任务的中间状态，系统目前无法自动恢复中断的任务。
> 建议你可以手动点击失败任务来重新启动执行。
