### ISSUE TITLE
[FEATURE] 可自定义容器(应用)安装目录

### ISSUE THREAD

**Issue by BuTingBa** [1Panel-dev/1Panel#6054]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

应用市场里面很多关于文件储存的应用，或者手动安装类似的应用时，容器的储存位置默认在/opt或/var/lib/docker目录下，而系统分区本就不大，如果要储存大量的文件，需要其他硬盘。

所以希望增加可以可以**自定义容器储存位置**以及**磁盘管理工具**。

### 请描述你建议的实现方案

所以希望增加可以可以**自定义容器储存位置**以及**磁盘管理工具**。

### 附加信息

![image](https://github.com/user-attachments/assets/90752c2b-b628-48fe-89aa-d35bea0b906a)

**Comment by wanghe-fit2cloud** [comment]
1. 应用商店中安装的应用如果具有持久化数据，其默认存储路径为应用安装目录下的 `./data` 文件夹。可以通过编辑 Compose 文件中的 volume 属性来自定义持久化目录。

2. `/var/lib/docker` 是 Docker 的默认工作目录，其中包含镜像、容器、数据卷等。可以通过修改 Docker 的配置文件来更改此目录。
