### ISSUE TITLE
[FEATURE]买后因为无法实现类似群晖向代功能，一直没激活专业版，特来请教

### ISSUE THREAD

**Issue by tyr100417188** [1Panel-dev/1Panel#6055]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

请问怎么【简单实现】如附件图中所示类似群晖这样的反向代理服务器需求：
1.单一域名支持多个端口，且自定义对应协议【现版本好像有相同代号（共享主目录）的限制】
2.自动匹配证书多域名(www.1.com或www.2.com)到对应设置端口
3.批量管理删除或编辑，最好能TXT或者CSV形式导出导入自行编辑(群晖可以自行编辑ReverseProxy文件)，不然条目太多重复操作太过麻烦
4.额外需求:希望V2版本双机联动能支持自动切换热备宕机模式
群晖大概操作流程：
1.添加证书
2.多次重复添加来源协议及端口，设置目的地协议及端口

**Comment by tyr100417188** [comment]
如果，只是创建多个反向代理类型的网站来实现的话，这样需要针对每个域名的多个端口设置反代，有多个域名，操作就是域名数量的倍数，比如我设置了200个端口有5个域名，就要添加1000个反向代理类型的网站【且这些网址还需要单独设置代号（共享主目录）】，太花时间了。希望能批量编辑或者其它简单实现的方案。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，相关问题的讨论可以关注论坛中这篇帖子，链接如下：
https://bbs.fit2cloud.com/t/topic/7283
