### ISSUE TITLE
[特点]自定义WAF规则的匹配增加UA匹配

### ISSUE THREAD

**Issue by Zevo77** [1Panel-dev/1Panel#6057]
### 1Panel 版本

v1.10.13

### 请描述您的需求或者改进建议

自定义WAF规则的匹配增加UA匹配，我想只有一个页面屏蔽搜索引擎蜘蛛。单单的robots.txt只是限制他索引，但是不能限制他爬取。

**Comment by zhengkunwang223** [comment]
![image](https://github.com/user-attachments/assets/b2d8e50e-6892-4dce-abd6-3b0d5180f9c0)
当前版本已经支持
