### ISSUE TITLE
[FEATURE] 主机-文件-搜索框加长

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#6063]
### 1Panel 版本

1.10.13

### 请描述您的需求或者改进建议

当前搜索框太短

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by Mr-Ao-Dragon** [comment]
让搜索框能自动加长如何？

**Comment by see-more** [comment]
@Mr-Ao-Dragon 抱歉我没看懂你的提议 ，自动加长是什么意思？

**Comment by Mr-Ao-Dragon** [comment]
> @Mr-Ao-Dragon 抱歉我没看懂你的提议 ，自动加长是什么意思？

就是说，我输了多少内容，搜索框就延长相应内容的宽度

**Comment by see-more** [comment]
> > @Mr-Ao-Dragon 抱歉我没看懂你的提议 ，自动加长是什么意思？
> 
> 就是说，我输了多少内容，搜索框就延长相应内容的宽度

我并不认为这是一个好注意，你可以提交一个新issue试试或者一个pr来实现

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
