### ISSUE TITLE
[BUG]运行环境网站删除后，关联的应用没有移除

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#6064]
### 1Panel 版本

v1.10.13-lts

### 问题描述

如题。

### 重现步骤

删除运行环境网站。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
