### ISSUE TITLE
[BUG]1Panel检测不到进程守护Supervisor的存在

### ISSUE THREAD

**Issue by 532763233** [1Panel-dev/1Panel#6071]
### 联系方式

532763233@qq.com

### 1Panel 版本

v1.10.13-lts

### 问题描述

在deepin系统上无法通过sudo apt-get install supervisor来安装Supervisor，于是便通过pip安装了Supervisor，且安装后将配置文件也更改至/etc/supervisor/supervisord.conf，成功启动后也能通过web访问Supervisor，但是1Panel的进程守护始终显示【未检测到 Supervisor，请参考官方文档进行安装】。想知道1Panel是怎么检测supervisor服务的。

### 重现步骤

通过pip安装Supervisor启动后1Panel的进程守护显示【未检测到 Supervisor，请参考官方文档进行安装】

### 期待的正确结果

1Panel的进程守护显示Supervisor的相关配置页面

### 附加信息

![image](https://github.com/user-attachments/assets/49be7e27-7464-44a5-a830-725023a2fb59)
![image](https://github.com/user-attachments/assets/96238e0c-2584-4c89-8761-99540545869e)

**Comment by see-more** [comment]
```go
if !cmd.Which(constant.Supervisord) {
	supervisorConfig.IsExist = false
	res.Config = supervisorConfig
	return res, nil
}
```
```go
func Which(name string) bool {
	stdout, err := Execf("which %s", name)
	if err != nil || (len(strings.ReplaceAll(stdout, "\n", "")) == 0 && strings.HasPrefix(stdout, "/")) {
		return false
	}
	return true
}
```
通过调用which命令检测supervisor服务

**Comment by wanghe-fit2cloud** [comment]
> 于是便通过pip安装了Supervisor 

尝试使用 apt-get 来全新安装
```shell
sudo apt-get install supervisor
```

**Comment by 532763233** [comment]
> 在deepin系统上无法通过sudo apt-get install supervisor来安装Supervisor

就是因为无法使用 apt-get 来安装才选择的pip安装，只能使用apt-get安装的才能使用吗，能否增加一下检测pip安装的服务的逻辑呢

**Comment by wanghe-fit2cloud** [comment]
> > 在deepin系统上无法通过sudo apt-get install supervisor来安装Supervisor
> 
> 就是因为无法使用 apt-get 来安装才选择的pip安装，只能使用apt-get安装的才能使用吗，能否增加一下检测pip安装的服务的逻辑呢

你也可以手动将 `supervisord` 添加到 `PATH` 中，因为 1Panel 使用 `which supervisord` 命令进行检测。不过，后续的重启等操作也需要通过 `systemd` 来管理。
> 如果不能使用 `apt-get` 安装应用，是否可以考虑使用 `.deb` 包进行安装？
