### ISSUE TITLE
[BUG]Openresty conf/mime.types 文件未挂载到容器，导致修改文件后配置不生效

### ISSUE THREAD

**Issue by wan92hen** [1Panel-dev/1Panel#6073]
### 1Panel 版本

v1.10.13-lts

### 问题描述

在 Openresty 安装目录中存在 mime.types 文件，但是该文件没有挂载到容器中，导致在该文件修改配置后配置不生效。

### 重现步骤

1. 修改 Openresty 安装目录 conf/mime.types 文件内容；
2. 重载 Openresty 配置；
3. 测试修改后特定文件后缀的 mime type 是否生效。

### 期待的正确结果

mime.types 文件挂载到容器目录，修改该文件配置重载 Openresty 后配置可以生效。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，近期版本会推送更新。

**Comment by wanghe-fit2cloud** [comment]
应用商店已推送更新。
