### ISSUE TITLE
[FEATURE] i访问日志pv6支持

### ISSUE THREAD

**Issue by clover1420** [1Panel-dev/1Panel#6076]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

纯真ip库社区版已支持ipv6，1Panel的访问日志的获取ip地理位置能否支持ipv6。

**Comment by zhengkunwang223** [comment]
纯真 IP 库社区版并没有说是否允许商用
而且需要在产品中嵌入广告才能获得授权
并且 社区版 ipv6 基本只精确到国家 
所以我们不会继续使用 会寻找其他的替代方案
