### ISSUE TITLE
[BUG]运行环境中启动命令包含`"`时无法正常启动

### ISSUE THREAD

**Issue by wan92hen** [1Panel-dev/1Panel#6079]
### 1Panel 版本

v1.10.13-lts

### 问题描述

创建运行环境，启动命令中包含`"`时，应用无法正常启动。

### 重现步骤

1. 创建 Java 运行环境
2. 启动命令使用 `sleep "100"`
3. 启动运行环境报错

**Comment by wanghe-fit2cloud** [comment]
感谢支持，近期会推送更新。

**Comment by wanghe-fit2cloud** [comment]
应用商店已推送更新。
