### ISSUE TITLE
[FEATURE]希望官方上架[AFFiNE]

### ISSUE THREAD

**Issue by dididaguai** [1Panel-dev/1Panel#6083]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

希望官方应用商店能够上架[AFFiNE](https://github.com/toeverything/AFFiNE?tab=readme-ov-file)

**Comment by wanghe-fit2cloud** [comment]
重复需求 https://github.com/1Panel-dev/1Panel/issues/5017

**Comment by wanghe-fit2cloud** [comment]
已上架应用商店。
