### ISSUE TITLE
[BUG] OpenResty设置页面-当前状态页接口错误

### ISSUE THREAD

**Issue by R0A1NG** [1Panel-dev/1Panel#6085]
### 1Panel 版本

v1.10.13-lts

### 问题描述

点击此页面错误，服务器纯ipv6环境
![1723295294526](https://github.com/user-attachments/assets/777e4217-f365-4dba-837e-f0a4e243b24e)

![1723295381715](https://github.com/user-attachments/assets/aea3401b-a499-464b-a163-620abf2f26d0)

### 重现步骤

点击OpenResty设置页面-当前状态页

**Comment by zhengkunwang223** [comment]
是不是有127.0.0.1的网站？

**Comment by R0A1NG** [comment]
> 是不是有127.0.0.1的网站？

额，真是，改了没问题了
