### ISSUE TITLE
[BUG] 容器监控中的网络监控显示不正确

### ISSUE THREAD

**Issue by Dec-QXY** [1Panel-dev/1Panel#609]
### 联系方式

admin@xiangyubizhi.com

### 1Panel 版本

1.0.5

### 问题描述

发行版本 ubuntu-20.04
内核版本 5.4.0-126-generic
系统类型 x86_64

容器监控中的网络监控显示不正确，实际网速很低，但随着时间的增加该数值会一直变大。

### 重现步骤

点击容器监控-查看网络监控，保持一段时间后会出现。

### 期待的正确结果

可参考宝塔docker监控

### 附加信息

![image](https://user-images.githubusercontent.com/52747536/231642053-8b2eadb4-6e1a-4f5a-96cb-cd0878de447c.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在开发测试环境复现一下上述问题。如果确定为 bug，会在近期发布的版本中修复。

**Comment by ssongliu** [comment]
感谢反馈，1Panel 和宝塔获取监控参数的方式不一致导致的这个问题，其中
1Panel 使用的是 Docker 官方的 SDK 获取到的数据，与命令行中执行 docker stats <containerID> 显示输入保持一致；
而宝塔使用的应该是自己的监控机制计算。

**Comment by Dec-QXY** [comment]
所以会解决这个问题吗，docker提供的感觉是累积的。
