### ISSUE TITLE
[BUG] Flarum容器重启后网站的扩展消失

### ISSUE THREAD

**Issue by anewinstance** [1Panel-dev/1Panel#6091]
### 1Panel 版本

v1.10.13-lts

### 问题描述

Flarum容器重启后网站的扩展消失

### 重现步骤

安装flarum，添加一些扩展，重启容器

### 期待的正确结果

添加的扩展保保留

**Comment by zhengkunwang223** [comment]
容器是这样的  扩展添加之后会丢失 建议使用 PHP 运行环境来创建 Flarum

**Comment by wanghe-fit2cloud** [comment]
在 1Panel 应用商店中安装的 Flarum 将 `./data` 目录设置为持久化目录。如果遇到扩展丢失的问题，可能是由于扩展目录未被正确持久化所致。建议查阅 Flarum 官方文档，了解是否有相关说明。
![image](https://github.com/user-attachments/assets/698a0320-89de-49e4-8be1-9f483667e2cf)

**Comment by wanghe-fit2cloud** [comment]
在 1Panel 应用商店中安装的 Flarum 将 `./data` 目录设置为持久化目录。如果遇到扩展丢失的问题，可能是由于扩展目录未被正确持久化所致。建议查阅 Flarum 官方文档，了解是否有相关说明。
![image](https://github.com/user-attachments/assets/698a0320-89de-49e4-8be1-9f483667e2cf)
