### ISSUE TITLE
[FEATURE]创建备份应用类型计划任务，应用应该为必填。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#6099]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

备份应用 - 应用
备份网站 - 网站
备份数据库 - 数据库
切割网站日志 - 网站

上述四种类型计划任务都需要设置为必填项。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
