### ISSUE TITLE
[FEATURE]编排模板支持声明引用变量

### ISSUE THREAD

**Issue by wan92hen** [1Panel-dev/1Panel#610]
### 1Panel 版本

v1.0.5

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/27671436/231668829-de6f2056-8944-4f68-98ac-d5f82f1b2a77.png)
建议在配置编排模板时可以定义一些变量并在内容中进行引用，这样使用这个模板创建时，可以方便地对一些特定参数进行修改。

例如将对外暴露的端口声明为变量，在部署时可以自定义端口值，避免与现有端口冲突。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本实现该功能。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
