### ISSUE TITLE
[BUG]病毒扫描 ClamAV 服务已经关闭，但是定时扫描任务未关闭。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#6100]
### 1Panel 版本

v1.10.13-lts

### 问题描述

如题。
<img width="1280" alt="图片" src="https://github.com/user-attachments/assets/7bd69e0c-ef3c-4a45-a256-34541a180acf">

<img width="1047" alt="图片" src="https://github.com/user-attachments/assets/29443dbd-0be0-46b5-9108-922ab6f0bc50">

### 重现步骤

如题。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
