### ISSUE TITLE
[FEATURE]推荐几个docker应用

### ISSUE THREAD

**Issue by nexus181** [1Panel-dev/1Panel#6101]
### 1Panel 版本

v1.10.13-lts

### 发现几个还不错的docker项目，希望能够上架到应用商店，方便使用

1、 个人主页
[https://github.com/imsyy/home](https://github.com/imsyy/home)

![image](https://raw.githubusercontent.com/imsyy/home/dev/screenshots/main.jpg)

2、六零导航页
[https://github.com/LyLme/lylme_spage](https://github.com/LyLme/lylme_spage)

![image](https://github.com/user-attachments/assets/cde65854-773e-4ca0-bd9f-a02cb667b31b)

3、BookBrowser图书浏览器
[https://github.com/uparrows/BookBrowser](https://github.com/uparrows/BookBrowser)

![image](https://user-images.githubusercontent.com/38988286/154710906-3b1d5caa-f1d6-4be6-a2fe-07cc069c5625.png)

4、smanga漫画浏览器
[https://github.com/lkw199711/smanga](https://github.com/lkw199711/smanga)

![image](https://raw.githubusercontent.com/lkw199711/smanga/master/src/assets/readme/smanga-media-list.PNG)

5、tachidesk_cn漫画管理器
[https://hub.docker.com/r/dezhao/tachidesk_cn](https://hub.docker.com/r/dezhao/tachidesk_cn)

![image](https://user-images.githubusercontent.com/38988286/180903573-4f007172-86e7-41eb-ac4e-1d19c054b8f5.jpg)

6、花森导航页
[https://github.com/huasenjio/huasenjio-compose](https://github.com/huasenjio/huasenjio-compose)

![image](https://github.com/user-attachments/assets/333c4c8a-af8b-44ac-8094-a164825d7f51)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，我们主要以项目的 Star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有超1万 Star 的开源项目，感谢您的理解。

> 你可以将需求反馈给 [第三方仓库（由社区用户维护）](https://github.com/okxlin/appstore)。
