### ISSUE TITLE
网站日志提示服务内部错误: bufio.Scanner: token too long

### ISSUE THREAD

**Issue by zhengkunwang223** [1Panel-dev/1Panel#6102]
### Discussed in https://github.com/1Panel-dev/1Panel/discussions/6097

<div type='discussions-op-text'>

<sup>Originally posted by **R0A1NG** August 11, 2024</sup>

### 1Panel 版本

v1.10.13-lts

### 问题描述

日志文件26MB，访问网站日志接口报错
![1723364210307](https://github.com/user-attachments/assets/d4300b5a-ab32-490d-9d06-37328480dff9)

### 重现步骤

访问网站日志接口

### 附加信息

_No response_</div>

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
