### ISSUE TITLE
[BUG]应用商店中的应用在升级成功后不会自动删除旧的备份文件

### ISSUE THREAD

**Issue by rainpaper-bs** [1Panel-dev/1Panel#6107]
### 1Panel 版本

v1.10.13-lts

### 问题描述

我在应用商店升级了一个应用，在应用升级完成正常运行时我看到“/opt/1panel/backup/app”文件夹下仍然有之前升级的应用的备份文件，在成功后应该删除旧的备份，可是旧的备份没有删除

### 重现步骤

在应用商店升级一个应用，打开"/opt/1panel/backup/app”可以看到没删除的备份文件

### 期待的正确结果

应用升级成功后应自动删除之前为了防止升级失败的备份

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本将默认保留三份升级应用的备份文件。

**Comment by rainpaper-bs** [comment]
手滑了点错了🤣

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
