### ISSUE TITLE
[FEATURE]推荐一个17.4k star的应用

### ISSUE THREAD

**Issue by nexus181** [1Panel-dev/1Panel#6109]
### 1Panel 版本

v1.10.13-lts

### Koodo Reader
一个跨平台的电子书阅读器
https://github.com/koodo-reader/koodo-reader

![inage](https://camo.githubusercontent.com/efcdadca7e6c7870c475909d97ba4b3cc915f4fb342480809dcb867b46e2dc2d/68747470733a2f2f646c2e6b6f6f646f7265616465722e636f6d2f73637265656e73686f74732f312e706e67)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本上架该应用。

**Comment by wanghe-fit2cloud** [comment]
应用已上架。
进入应用商店列表，点击右上角的【更新应用列表】按钮，待同步完成后即可安装应用。
