### ISSUE TITLE
[BUG] 1panel 使用OpenResty cloudflare 不能自动添加A记录

### ISSUE THREAD

**Issue by MoonIRL** [1Panel-dev/1Panel#6118]
### 1Panel 版本

v1.10.13-lts

### 问题描述

1panel cloudflare 不能自动添加A记录

### 重现步骤

1panel  安装了 OpenResty。ssl   添加了  cloudflare 的 DNS 账户 申请了域名的 ssl。 网站 反向代理 添加二级域名 比如说绑定域名 "x.abc.com"
不能自动的 在 cloudflare 添加 二级域名的dns记录 。比如说前面绑定域名 "x.abc.com" 在 cloudflare  就有`A x 服务器IP` 。

### 期待的正确结果

绑定域名  "x.abc.com"  就在 cloudflare  就有 `A x 服务器IP` 的记录

**Comment by zhengkunwang223** [comment]
当前版本不支持此功能 暂时也没有计划增加此功能

**Comment by toohandsome** [comment]
> 当前版本不支持此功能 暂时也没有计划增加此功能

请问这个是基于什么考虑的呢？我也碰到了这个问题；需要分别在服务器建立网站，再去dns服务商设置解析，操作有点割裂，为什么不弄成一站式的呢？

**Comment by Wang-Mer** [comment]
> 当前版本暂时不支持此功能也不计划增加此功能

以后会支持吗？
