### ISSUE TITLE
[FEATURE] 站点 HTTPS 优化建议

### ISSUE THREAD

**Issue by Anyexyz** [1Panel-dev/1Panel#6129]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

为站点开启 HTTPS 时，当前策略是默认跳转的手动创建的证书位置：
![image](https://github.com/user-attachments/assets/493df41f-fdd7-4fb8-8640-9ba77782cf78)

是否可以检测证书夹后默认匹配一个合适的证书，减少点击次数。

### 请描述你建议的实现方案

如上

**Comment by zhengkunwang223** [comment]
V2 版本会支持用户在创建网站直接选择证书 减少操作

**Comment by Anyexyz** [comment]
👍👍👍

**Comment by wanghe-fit2cloud** [comment]
关于优化网站启用 HTTPS 的流程，统一汇总到该 Issue https://github.com/1Panel-dev/1Panel/issues/4462
