### ISSUE TITLE
[FEATURE] 希望工具箱里的工具可以一键安装

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#6131]
### 1Panel 版本

最新

### 请描述您的需求或者改进建议

希望工具箱中的进程守护、FTP等工具可以一键安装，简化操作流程

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，工具箱工具支持一键安装的需求，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/5149
