### ISSUE TITLE
[FEATURE] 应用商店:数据库添加oracle 数据库类型支持

### ISSUE THREAD

**Issue by lzfgit-byte** [1Panel-dev/1Panel#6134]
### 1Panel 版本

v1.10.11-lts

### 请描述您的需求或者改进建议

数据库添加 oracle 数据库类型支持

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
最好是能提供一下你之前容器化部署 Oracle 数据库的经验，比如使用的 `docker run` 命令或 `docker-compose.yml` 文件。还有对 Oracle 数据库版本的具体要求。

**Comment by lzfgit-byte** [comment]
我是根据这个[镜像](https://hub.docker.com/r/oracleinanutshell/oracle-xe-11g)部署了一版
附件列表是我的Dockerfile 和  docker-compose.yml文件。比较简陋的一版。希望对你们有帮助
[oracle.zip](https://github.com/user-attachments/files/16623468/oracle.zip)

**Comment by wanghe-fit2cloud** [comment]
> 我是根据这个[镜像](https://hub.docker.com/r/oracleinanutshell/oracle-xe-11g)部署了一版 附件列表是我的Dockerfile 和 docker-compose.yml文件。比较简陋的一版。希望对你们有帮助 [oracle.zip](https://github.com/user-attachments/files/16623468/oracle.zip)

该镜像非官方版本，且长期未维护，版本较低。Oracle 官方提供了 Dockerfile 文件，链接如下：  
[OracleDatabase/SingleInstance/dockerfiles](https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/dockerfiles)

你可以自行构建官方镜像，并使用官方提供的 `docker-compose.yaml` 文件来进行应用的管理与维护（可在 `容器` - `编排` 页面操作）。

**Comment by lzfgit-byte** [comment]
> > 我是根据这个[镜像](https://hub.docker.com/r/oracleinanutshell/oracle-xe-11g)部署了一版 附件列表是我的Dockerfile 和 docker-compose.yml文件。比较简陋的一版。希望对你们有帮助 [oracle.zip](https://github.com/user-attachments/files/16623468/oracle.zip)
> 
> 该镜像非官方版本，且长期未维护，版本较低。Oracle 官方提供了 Dockerfile 文件，链接如下： [OracleDatabase/SingleInstance/dockerfiles](https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/dockerfiles)
> 
> 你可以自行构建官方镜像，并使用官方提供的 `docker-compose.yaml` 文件来进行应用的管理与维护（可在 `容器` - `编排` 页面操作）。

也就是说当前【应用商店】是没有添加oracle数据库的计划了？

**Comment by wanghe-fit2cloud** [comment]
> > > 我是根据这个[镜像](https://hub.docker.com/r/oracleinanutshell/oracle-xe-11g)部署了一版 附件列表是我的Dockerfile 和 docker-compose.yml文件。比较简陋的一版。希望对你们有帮助 [oracle.zip](https://github.com/user-attachments/files/16623468/oracle.zip)
> > 
> > 
> > 该镜像非官方版本，且长期未维护，版本较低。Oracle 官方提供了 Dockerfile 文件，链接如下： [OracleDatabase/SingleInstance/dockerfiles](https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/dockerfiles)
> > 你可以自行构建官方镜像，并使用官方提供的 `docker-compose.yaml` 文件来进行应用的管理与维护（可在 `容器` - `编排` 页面操作）。
> 
> 也就是说当前【应用商店】是没有添加oracle数据库的计划了？

是的，由于Oracle官方未提供容器镜像（需要自行构建），且1Panel也不支持这种单独构建并运行容器的方式，因此暂时不考虑支持该需求了。
