### ISSUE TITLE
[BUG] 容器的command参数回显应该使用 text area而不是text input,且不应该过滤\n

### ISSUE THREAD

**Issue by ihipop** [1Panel-dev/1Panel#6138]
### 1Panel 版本

v1.10.13-lts

### 问题描述

某些容器的command 是multiline的, 你们使用text input回显,过滤换行,导致换行信息丢失

### 重现步骤

- 商店安装一下 redis 7 容器,启动容器,并在参数里面记下密码
- 容器管理里面,点开容器名称,查看到 command 是 miltiline的 正确的显示了 `\n`, 密码也是正确的和 `fi` 切割开来的
![image](https://github.com/user-attachments/assets/b71cbc0b-aeae-4b9e-ade9-2d88f017032d)
- 同样在此处,点容器的编辑,查看 command 项目, 可以看到所有的换行符都没有了, `\n` 也没有了, 密码显示和 shell的 `if` `fi` 结构块粘连到了一起,也就是没法正常的输入 multiline 的command的
![image](https://github.com/user-attachments/assets/e5654684-9bac-4326-a993-1b4285c06fa2)

### 期待的正确结果

此处使用text area且正确处理换行符

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
