### ISSUE TITLE
编辑应用，显示的数据库服务器名称不正确

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#6140]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

点击 `参数`，显示的服务名称不正确：
![图片](https://github.com/user-attachments/assets/2354ee66-fa31-4c59-abab-f50ccca5e9e6)

查看 `.env` 文件，服务名称是正确的：
![图片](https://github.com/user-attachments/assets/033132c4-131a-4b82-a6de-5a9ce037291a)

### 请描述你建议的实现方案

需求：点击 `参数` 显示正确的服务名称。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
