### ISSUE TITLE
[FEATURE]OpenResty面板请问什么时候支持TCP/UDP呢

### ISSUE THREAD

**Issue by cocoyamnut** [1Panel-dev/1Panel#6141]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

OpenResty面板请问什么时候支持TCP/UDP呢

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述需求统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/5135
> 目前已经开始调研具体实现方案。
