### ISSUE TITLE
[BUG]mysql升级到8.4后，数据库管理 - 当前状态 查询会出错

### ISSUE THREAD

**Issue by mjsoftking** [1Panel-dev/1Panel#6148]
### 1Panel 版本

v1.10.13-lts

### 问题描述

![image](https://github.com/user-attachments/assets/790dbaa5-0d09-40a4-b800-911e95070824)
mysql升级到8.4后，数据库管理 - 当前状态 查询会出错，错误如上图

### 重现步骤

数据库管理 - 当前状态

### 相关日志输出

```shell
服务内部错误: ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'master status' at line 1
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们已经在本地环境复现该问题，会在近期版本修复。

**Comment by ArcaneWhispers** [comment]
> 感谢反馈，我们已经在本地环境复现该问题，会在近期版本修复。

mysql8.4 进入mysql配置页面 马上会提示：ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'master status' at line 1

数据库都是干净的。进入就报错。

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
