### ISSUE TITLE
[BUG]MySQL默认配置文件没有设置时区

### ISSUE THREAD

**Issue by rainpaper-bs** [1Panel-dev/1Panel#6152]
### 1Panel 版本

v1.10.13-lts

### 问题描述

我通过1Panel安装了一个MySQL8，在上面配置了一个计划任务，死活不执行，排查两小时后发现时区是UTC+0而不是中国时间，我建议修改MySQL的my.conf配置文件，加上`default-time_zone = '+8:00'`，也可以根据用户语言自动修改对应时区

### 重现步骤

1.安装MySQL
2.查看MySQL时区

### 期待的正确结果

安装MySQL时可以根据用户地区自动设置合适的时区

**Comment by wanghe-fit2cloud** [comment]
MySQL 安装时有挂载服务器 `/etc/timezone`，如图：
![image](https://github.com/user-attachments/assets/2c8a8c5f-08a5-400c-a634-aa2db0a2d064)

![image](https://github.com/user-attachments/assets/37fffbe6-35d2-4d7f-9d32-2f719cd3b4d6)
