### ISSUE TITLE
[BUG] 計畫任務的時區跟伺服器的時區不同

### ISSUE THREAD

**Issue by seriaati** [1Panel-dev/1Panel#6155]
### 联系方式

Discord: https://discord.com/users/410036441129943050 或是 seria.ati@gmail.com

### 1Panel 版本

v1.10.13-lts

### 问题描述

面板計畫任務所使用的時區與伺服器的時區不同。

### 重现步骤

1. 創建一個新的計畫任務，腳本內容輸入 `date`，其他維持預設
2. 手動執行該任務
3. 進入該任務的「報告」頁面

### 期待的正确结果

可以看到如下，面板所使用的時間跟伺服器的時間不同。
![image](https://github.com/user-attachments/assets/f64d034b-b8a5-41b2-b49f-a81fadcf737b)
這會導致我在面板裡設定的計畫任務在錯誤的時間執行，例如設定了 2:00 PM，但這個 2:00 PM 會在 **面板時間** 的 2:00 PM 時執行，而非預期的 2:00 PM **伺服器時間** 時執行。

### 附加信息

![image](https://github.com/user-attachments/assets/4ee08d13-4723-4725-80c6-6074ee337e30)
這是「工具箱」頁面的截圖，可以看到時區確實顯示 Asia/Tokyo，但是時間顯示的是 CEST。
另外這裡顯示的「伺服器時間」其實是「面板時間」，伺服器的時間已經是 JST 時區了。

**Comment by wanghe-fit2cloud** [comment]
进入 `主机` - `终端` 页面，手动执行 `timedatectl` 和 `date` 命令，并查看这两个命令的输出。麻烦提供截图信息，谢谢！

**Comment by seriaati** [comment]
![Screenshot_2024-08-17-07-44-46-816_com.server.auditor.ssh.client-edit.jpg](https://github.com/user-attachments/assets/1f186225-4322-493f-9104-751a4fda28ce)

**Comment by seriaati** [comment]
重啟面板後時區同步了
