### ISSUE TITLE
创建网站可以自定义默认目录

### ISSUE THREAD

**Issue by Jimmy-Effe** [1Panel-dev/1Panel#6157]
### 1Panel 版本

v1.10.12-lts

### 请描述您的需求或者改进建议

希望在创建网站时可以自定义目录地址
比如创建example.com为主网站，网站文件地址是/opt/1panel/apps/openresty/openresty/www/sites/example/index/
我又创建了login.example.com为子网站，子网站的默认运行目录希望是在/opt/1panel/apps/openresty/openresty/www/sites/example/index/login/login.php

项目结构：
example.com/
│
├── login/
│   └── login.php
│
├── mainApp/
│   └── index.php
│
└── css/
    ├── main.css
    └── login.css

**Comment by zhengkunwang223** [comment]
v2版本支持多个网站使用一个目录，或者目录中的子目录

**Comment by wanghe-fit2cloud** [comment]
重复问题 https://github.com/1Panel-dev/1Panel/issues/2336
