### ISSUE TITLE
[FEATURE]未使用镜像列表显示，升级自动删除孤立镜像

### ISSUE THREAD

**Issue by clion007** [1Panel-dev/1Panel#6159]
### 1Panel 版本

v1.10.13

### 请描述您的需求或者改进建议

在容器管理的镜像界面列表，不会显示未使用的镜像，另外，在容器镜像升级后，原来的孤立镜像不会自动删除，需要在清理管理那里扫描清除，建议增加升级后自动清除原来的孤立镜像功能及在容器的镜像列表显示所有未使用镜像功能。

**Comment by zhengkunwang223** [comment]
感谢建议 我们会在 V2 版本优化应用升级和卸载之后删除镜像的操作

**Comment by wanghe-fit2cloud** [comment]
重复问题 https://github.com/1Panel-dev/1Panel/issues/5785
