### ISSUE TITLE
[BUG] 登陆界面样式异常

### ISSUE THREAD

**Issue by realzolo** [1Panel-dev/1Panel#616]
### 联系方式

zolo@onezol.com

### 1Panel 版本

v1.1.0

### 问题描述

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/63219216/231686992-86b1782f-cfb4-4f1c-869d-4a5f06cde47f.png">

1. 输入框背景与上面用户名密码不统一
2. 文本超出未换行

### 重现步骤

切换英文状态登陆界面

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复
