### ISSUE TITLE
[BUG] 凌霄软件登陆后不能查看自己的信息

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#6160]
### 联系方式

交流群5

### 1Panel 版本

v1.10.13

### 问题描述

点击个人中心，页面只显示几秒就变成下面这个页面
![image](https://github.com/user-attachments/assets/288bcda0-0791-42a5-ae90-1c2b8ee78be4)
![image](https://github.com/user-attachments/assets/a6758828-1cb3-46c1-ac1e-afa5cc4dda06)

### 重现步骤

登陆后，就会出现

### 期待的正确结果

能正常使用，查看信息、查看许可证、解锁许可证等操作。

### 相关日志输出

```shell
无
```

### 附加信息

edge浏览器

**Comment by wan92hen** [comment]
你好，这边测试是正常的。可以看下浏览器有没有装什么插件，禁用下所有插件再试下。

**Comment by 9a6c** [comment]
没有装扩展， 现象是显示了页面，但是过了3s左右就变成截图中的那个样子

**Comment by 9a6c** [comment]
安装了谷歌浏览器，一切正常。 还是希望可以兼容edge
