### ISSUE TITLE
[FEATURE] Gitea不支持设置ssl, 导致我来回切http和https, 浏览器缓存后还没发切, 希望改进

### ISSUE THREAD

**Issue by NilServer404** [1Panel-dev/1Panel#6164]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

Gitea不支持设置ssl, 导致我来回切http和https, 浏览器缓存后还没发切, 希望改进

**Comment by wanghe-fit2cloud** [comment]
关于应用的 HTTPS 使用问题，可以参考官方文档：https://docs.gitea.cn/administration/https-setup。  
你也可以通过 1Panel 的网站功能创建反向代理站点。
