### ISSUE TITLE
[BUG] PHP的FPM容器网站之间不应该共享所有代码目录的挂载,这种共享只应该发生在resty容器而不是FPM容器

### ISSUE THREAD

**Issue by ihipop** [1Panel-dev/1Panel#6165]
### 1Panel 版本

v1.10.13-lts

### 问题描述

Resty容器由于有静态文件访问的需求,共享所有FPM容器的代码目录是,可以理解的,但是网站之间的FPM容器之间是不应该这样做的,这样一旦一个FPM容器有马,能删掉和访问其他容器的文件系统.

### 重现步骤

![image](https://github.com/user-attachments/assets/8e0945f4-7dbb-43fc-9b9f-253961c1f922)
比如,对FPM容器A,此处应该挂载 
`/opt/1panel/apps/openresty/openresty/www/sites/A` 到容器内的 `/www/sites/A`

### 期待的正确结果

FPM容器应该只挂载自己的代码目录而,而不是整个resty的WWW目录

**Comment by wanghe-fit2cloud** [comment]
感谢反馈！该功能将在 v2 版本中支持，具体进展请关注：https://github.com/1Panel-dev/1Panel/issues/1240
