### ISSUE TITLE
[FEATURE]请求添加：AFFINE 一个注重隐私、本地优先、开源、即用型的Notion&Miro替代品

### ISSUE THREAD

**Issue by toohandsome** [1Panel-dev/1Panel#6168]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

AFFINE 是 一个注重隐私、本地优先、开源、即用型的Notion&Miro替代品。

官网：https://affine.pro/
github: https://github.com/toeverything/AFFiNE
docker-compose: https://github.com/toeverything/AFFiNE/blob/stable/.github/deployment/self-host/compose.yaml
私有部署：
https://docs.affine.pro/docs/self-host-affine
https://docs.affine.pro/docs/self-host-affine/run-affine-with-custom-options

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上架 [AFFiNE](https://github.com/toeverything/AFFiNE)

**Comment by wanghe-fit2cloud** [comment]
已上架应用商店。
