### ISSUE TITLE
[BUG] 防火墙

### ISSUE THREAD

**Issue by TcDhlPro** [1Panel-dev/1Panel#617]
### 1Panel 版本

v1.1.0

### 问题描述

![image](https://user-images.githubusercontent.com/100897011/231703481-ef9ad2a9-a5b8-47d9-a4f0-8b48648ca7c3.png)

点击开启防火墙出现这个, 没办法开启

### 重现步骤

左侧面板:主机/防火墙
右侧内容: 单机<开启>按钮, 就能出现这个错误

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by TcDhlPro** [comment]
防火墙的解决了
apt install ufw
然后面板中开启防火墙就成功
----------------------------------

端口规则中希望后面可以增加`端口是绑定在服务器的哪个IP上的`
![image](https://user-images.githubusercontent.com/100897011/232096380-15ce2bdd-7198-4f39-a432-98c7ce1df4a8.png)
