### ISSUE TITLE
[FEATURE] Gitea无法配置ssl, 导致每次访问浏览自自动将http转为httpps时无法访问, 已尝试反向代理依旧报错

### ISSUE THREAD

**Issue by NilServer404** [1Panel-dev/1Panel#6170]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

[FEATURE] Gitea无法配置ssl, 导致每次访问浏览自自动将http转为httpps时无法访问, 已尝试反向代理依旧报错

![image](https://github.com/user-attachments/assets/331add0f-2acf-4c3b-902e-52b9e8c649ad)

**Comment by wanghe-fit2cloud** [comment]
具体应用的使用问题，建议反馈至应用官方。
> 1Panel 是采用容器化方案部署的 Gitea。
