### ISSUE TITLE
[BUG] 安装 JumpServer 应用时，切换 Redis 数据库时如果 Redis 数据库的密码为空，切换后密码不会自动随数据库联动。

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#6174]
### 1Panel 版本

v1.10.13-lts

### 问题描述

安装 JumpServer 应用时，切换 Redis 数据库时如果 Redis 数据库的密码为空，切换后密码不会自动随数据库联动。

### 重现步骤

安装 JumpServer 应用时，切换 Redis 数据库时如果 Redis 数据库的密码为空，切换后密码不会自动随数据库联动。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
