### ISSUE TITLE
在网站-》证书-》的DNS账户里面增加华为云的api支持

### ISSUE THREAD

**Issue by FOXBALL-ONE** [1Panel-dev/1Panel#6176]
### 1Panel 版本

专业版v1.10.13-lts

### 请描述您的需求或者改进建议

在网站-》证书-》的DNS账户里面，什么时候支持华为云的api？

**Comment by wanghe-fit2cloud** [comment]
参考 https://github.com/1Panel-dev/1Panel/issues/6047
