### ISSUE TITLE
[BUG]离线情况下无法使用

### ISSUE THREAD

**Issue by BianShuHeng** [1Panel-dev/1Panel#6178]
### 1Panel 版本

v1.10.13-lts

### 问题描述

离线情况下无法使用，会调用 /api/v1/settings/upgrade， 然后页面404

### 重现步骤

点击主页面板

**Comment by BianShuHeng** [comment]
aaa

**Comment by wanghe-fit2cloud** [comment]
1Panel 的系统升级、应用商店同步等接口需要请求外网，不支持离线环境使用。
