### ISSUE TITLE
[BUG]为啥我打开数据库设置的时候报错

### ISSUE THREAD

**Issue by liuzedong-hub** [1Panel-dev/1Panel#6179]
### 联系方式

17861503053

### 1Panel 版本

1.10.13

### 问题描述

![微信图片_20240820092037](https://github.com/user-attachments/assets/eb6da96a-65b9-4757-951b-4b4ff6ab08a2)

### 重现步骤

点击左侧数据库，点击设置

**Comment by ssongliu** [comment]
重复 #6148
