### ISSUE TITLE
[BUG] PHP运行环境

### ISSUE THREAD

**Issue by TcDhlPro** [1Panel-dev/1Panel#618]
### 1Panel 版本

v1.1.0

### 问题描述

![image](https://user-images.githubusercontent.com/100897011/231703877-ca0e735f-3fb2-4e75-99fb-a9dbf39f31aa.png)
![image](https://user-images.githubusercontent.com/100897011/231703964-d15de280-00ae-41a3-a57c-79e822b74ca4.png)

提示要更新, 点击后又显示全部都是最新的

### 重现步骤

看截图

**Comment by zhengkunwang223** [comment]
需要更新应用列表

**Comment by TcDhlPro** [comment]
可以了, 但怎么把运行环境配置到网站上呢?

**Comment by TcDhlPro** [comment]
![image](https://user-images.githubusercontent.com/100897011/231737265-63b80dfd-2bf9-4a96-b510-d7b04e5a8a83.png)
PHP8和PHP7都是这样失败

**Comment by TcDhlPro** [comment]
容器设置页面中的 iptables 是已打开状态, 依旧是失败
![image](https://user-images.githubusercontent.com/100897011/231813300-17daf7ed-feff-4789-b5ba-093e98538223.png)
![image](https://user-images.githubusercontent.com/100897011/231813371-d930d290-8676-4694-9055-1d7bab65ccc9.png)

**Comment by TcDhlPro** [comment]
@zhengkunwang223 
@wanghe-fit2cloud 
这个咋解决......

**Comment by TcDhlPro** [comment]
![image](https://user-images.githubusercontent.com/100897011/231940816-6163db3c-05a0-49b7-89c5-7eff70d08128.png)
![image](https://user-images.githubusercontent.com/100897011/231940840-7d51993c-4ba0-4edc-8d1a-626e0b53360e.png)

**Comment by wanghe-fit2cloud** [comment]
帮忙提供一下 docker 配置文件内容：cat /etc/docker/daemon.json

**Comment by wanghe-fit2cloud** [comment]
> > 帮忙提供一下 docker 配置文件内容：cat /etc/docker/daemon.json
> 
> 我也编译失败了，这个文件是空的。怎么办？

可以直接删除该文件，然后执行如下命令：
```sh
systemctl daemon-reload
```
```sh
systemctl restart docker
```

**Comment by TcDhlPro** [comment]
> 帮忙提供一下 docker 配置文件内容：cat /etc/docker/daemon.json

/etc/docker的目录下是空的

**Comment by wanghe-fit2cloud** [comment]
重启 docker 后，再次创建运行环境，看是否创建成功。

**Comment by TcDhlPro** [comment]
> 重启 docker 后，再次创建运行环境，看是否创建成功。

刚刚试过, 不能创建成功
快要哭了,呜呜呜呜

**Comment by TcDhlPro** [comment]
![image](https://user-images.githubusercontent.com/100897011/232027700-67274bed-5208-4331-83e4-86d21266a1f5.png)
debian-10.13

**Comment by wanghe-fit2cloud** [comment]
> > 重启 docker 后，再次创建运行环境，看是否创建成功。
> 
> 刚刚试过, 不能创建成功 快要哭了,呜呜呜呜

reboot 重启服务器，试一下。

**Comment by wanghe-fit2cloud** [comment]
当前的问题，就是 docker 容器内不能访问外网导致的。

**Comment by TcDhlPro** [comment]
> 当前的问题，就是 docker 容器内不能访问外网导致的。

1Panel-openresty-Oxrf是这个容器无法访问外网?

**Comment by wanghe-fit2cloud** [comment]
创建运行环境：基于 PHP 基础镜像创建运行环境的 Docker 镜像时，访问外网失败了。

**Comment by TcDhlPro** [comment]
服务器重启以后:
![image](https://user-images.githubusercontent.com/100897011/232028972-d031e771-d778-48c4-bf50-74a042e9d496.png)
![image](https://user-images.githubusercontent.com/100897011/232028989-c34b78e1-bc96-4354-8d91-90b5e677d1ce.png)
然后我把`iptables`勾选上, 保存, 输入立即重启:
![image](https://user-images.githubusercontent.com/100897011/232029171-9b69f12e-4d49-4d5a-8763-4a7bd0e33b23.png)
![image](https://user-images.githubusercontent.com/100897011/232029186-4c64e9e1-9ae2-4f54-99d7-46ca2487952c.png)

**Comment by TcDhlPro** [comment]
![image](https://user-images.githubusercontent.com/100897011/232029523-5c5aaaae-6c12-481d-854a-fee527c1d5b1.png)

**Comment by TcDhlPro** [comment]
我自己用命令创建过一个容器, 没有通过面板创建容器, 因为通过面板创建的容器无法正常启动, 然后我就自己用命令创建, 能成功创建, 也能成功运行, 面板中的容器界面也能正常读到我自己创建的容器
    会不会跟这个有关系?
    我自己创建的命令如下(忽略我故意在命令中写的中文):
docker run  -d \
-e TZ=Asia/Shanghai \
-e V2RAYA_ADDRESS=127.0.0.1:端口\
-v 路径映射:ro \
-v 路径映射 \
-v 路径映射 \
--restart always \
--privileged \
--network=host \
--name v2rayA \
mzz2017/v2raya

**Comment by TcDhlPro** [comment]
也有可能是iptables的问题, 因为我还有个issues是提了防火墙无法打开
#617

**Comment by TcDhlPro** [comment]
![image](https://user-images.githubusercontent.com/100897011/232034003-5af9f60f-5de1-431c-8f83-7d01a0978508.png)
打开防火墙会提示这个

**Comment by TcDhlPro** [comment]
是需要我在系统中先 `apt install iptables` 这样装一下?

**Comment by TcDhlPro** [comment]
**我在安装1panel面板之前, 执行过如下命令:**
`iptables -F: 该命令用于清空当前 iptables 中所有的规则，即删除所有已定义的 IP 包过滤规则和 NAT 规则。

iptables -X: 该命令用于删除所有自定义的链（Chain），包括用户自定义的链和默认创建的链，但保留预定义的链如：INPUT、OUTPUT 和 FORWARD 等。通过该命令可以快速清除无用的链。

iptables -P INPUT ACCEPT: 该命令用于设置默认策略（policy）为接受（ACCEPT），对于没有匹配到任何规则的数据包，都将被接受并传递给目标节点。

iptables -P FORWARD ACCEPT: 该命令用于设置转发（FORWARD）数据包的默认策略为接受（ACCEPT），即允许主机作为网关将数据包从一台网络节点传递到另一个网络节点。

iptables -P OUTPUT ACCEPT: 该命令用于设置输出（OUTPUT）数据包的默认策略为接受（ACCEPT），即允许主机向外发送数据包。

iptables-save > /etc/iptables/rules.v4: 该命令用于将当前 iptables 的规则保存到文件 /etc/iptables/rules.v4 中。这样做的好处是，当系统重启后，可以使用 iptables-restore < /etc/iptables/rules.v4 命令重新加载之前保存的规则，使之前设置的规则不丢失。`

**Comment by TcDhlPro** [comment]
我提供的够详细了吧, 问题是不是主要在防火墙没办法开启, 然后导致容器这边也会有点问题, 再导致PHP 基础镜像无法成功创建?

**Comment by TcDhlPro** [comment]
我Debian10的系统, 有`nftables` 木有`iptables`
![image](https://user-images.githubusercontent.com/100897011/232036868-050e78d5-7aa4-4ab9-b373-5085e8644fc3.png)

**Comment by TcDhlPro** [comment]
能不能给一点点反应, 如果你们下一版会兼容`nftables`那我就不动, 等你们更新,  如果你们就用`iptables`的话, 那我安装一下,再试试从面板启动防火墙是否正常

**Comment by TcDhlPro** [comment]
> 进微信群加我好友。

进群了

**Comment by TcDhlPro** [comment]
解决(Debian10.13)
开启 IPv4转发功能, 并启用
`/etc/sysctl.conf`中增加`net.ipv4.ip_forward=1`,  然后重载文件`sysctl -p`
`sysctl net.ipv4.ip_forward` 执行的结果如果是1

**Comment by ttwo22** [comment]
> 

我和你出现了一样的问题，我也是debian 10 ，有详细一点的解决方法妈

**Comment by TcDhlPro** [comment]
> > 
> 
> 我和你出现了一样的问题，我也是debian 10 ，有详细一点的解决方法妈

上面解决方案已经说的很详细了, 但我后来又用回宝塔了, 1Panel还是等他们再优化段时间再用好了
