### ISSUE TITLE
希望可以加一个自建镜像的hook升级

### ISSUE THREAD

**Issue by the-content** [1Panel-dev/1Panel#6194]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

比如我本地构建了镜像，推送到了dockerhub或者阿里云的镜像，有一个触发器，主动出发一个接口，让服务器容器自动拉取升级

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑增加 webhook 功能，参考 issue #410
自动更新镜像的需求，可以参考 issue https://github.com/1Panel-dev/1Panel/issues/4963
