### ISSUE TITLE
[FEATURE] 请问v1.x与v2.x兼容吗

### ISSUE THREAD

**Issue by maoball** [1Panel-dev/1Panel#6198]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

如题，可想到例如
1.v1.x能否直接升级到v2.x（是否需要卸载重装）
2.v1.x中安装的应用在v2.x中能否直接用
3.v1.x的备份v2.x能否恢复
谢谢开发者们😄

**Comment by wanghe-fit2cloud** [comment]
前两点我们会尽量做到兼容。
第三点，v1 版本的快照无法在 v2 版本中使用，但应用、网站、数据库等的备份我们会尽量实现兼容。
