### ISSUE TITLE
[FEATURE]postgresql 支持选择多个版本

### ISSUE THREAD

**Issue by ChanXing2023** [1Panel-dev/1Panel#6202]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

postgresql 目前只支持选择16.4版本，其他版本不可以选择

### 请描述你建议的实现方案

1. 可以选择不同版本postgresql安装

**Comment by wanghe-fit2cloud** [comment]
收到，后续版本会同时支持 12.x、13.x、14.x、15.x、16.x 版本的安装。

**Comment by wanghe-fit2cloud** [comment]
应用已上架。进入应用商店列表，点击右上角的【更新应用列表】按钮，待同步完成后即可安装应用。
![image](https://github.com/user-attachments/assets/6a773def-562e-41c7-904c-6af1607c323e)

**Comment by wwtao1024** [comment]
管理远程的不能管理PostgreSQL 9.6.15 on x86_64-pc-linux-gnu (Debian 9.6.15-1.pgdg90+1), compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit的吗

**Comment by wanghe-fit2cloud** [comment]
是的，不支持导入 v9.6 版本。
目前 PostgreSQL 官方也是支持了四个大版本，如图：
![image](https://github.com/user-attachments/assets/aa89266c-edd5-4c06-a742-eabc7fe2c07b)
