### ISSUE TITLE
新增docker run命令传读取值到配置里

### ISSUE THREAD

**Issue by MuYoungx** [1Panel-dev/1Panel#6207]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

希望1panel推出一个类似casaos的一键读取docker run 命令的功能，直接复制docker run的那一串命令 自动取值到容器的配置里

### 请描述你建议的实现方案

希望1panel推出一个类似casaos的一键读取docker run 命令的功能，直接复制docker run的那一串命令 自动取值到容器的配置里

**Comment by wanghe-fit2cloud** [comment]
docker run 命令可视化相关需求的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/3463
