### ISSUE TITLE
[BUG]在面板中关闭然后重新启动防火墙后会无条件增加应用端口

### ISSUE THREAD

**Issue by cli-r** [1Panel-dev/1Panel#6215]
### 1Panel 版本

v1.10.13-lts

### 问题描述

系统为centos 9，在面板的主机-防火墙中关闭然后重新启动防火墙，在卡顿一段时间后会在防火墙配置中增加已安装应用的端口和1panel的面板端口，来源为所有IP，即使应用并未开放端口外部访问，事实上通过docker映射的端口也不用在防火墙中打开端口。

### 重现步骤

在面板的主机-防火墙中关闭然后重新启动防火墙

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述功能。

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
