### ISSUE TITLE
[BUG] 1Panel 1.1.0不能再ArchLinux中禁用Ping

### ISSUE THREAD

**Issue by OrangeMas** [1Panel-dev/1Panel#622]
### 1Panel 版本

1.1.0

### 问题描述

1Panel 1.1.0不能再ArchLinux中禁用Ping 问题为在Archlinux中对sysctl配置文件的位置修改路径，不存在/etc/sysctl.conf文件 并且新安装Archlinux中对于sysctl.conf默认也是无文件。
可以参阅此文档https://wiki.archlinuxcn.org/wiki/Sysctl
![Dingtalk_20230413172653](https://user-images.githubusercontent.com/26352614/231716444-437d325a-8056-4459-8d8d-16a363860497.jpg)

### 重现步骤

正常安装ArchLinux，开启Ping禁用即出现问题

**Comment by wanghe-fit2cloud** [comment]
如果服务器不存在 /etc/sysctl.conf 文件，我们是在页面上隐藏了禁 ping 开关。
后续版本我们可能会针对 ArchLinux 这种服务器做出针对性的优化。
