### ISSUE TITLE
[FEATURE]删除网站把项目也删除

### ISSUE THREAD

**Issue by iygwei** [1Panel-dev/1Panel#6222]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

如题为什么删除网站要删除代码啊.我只是取错了域名想换个直接删除代码都给删了 没一点点的防备

**Comment by wanghe-fit2cloud** [comment]
如需变更域名，可进入 `网站设置` 中的 `域名设置` 页面进行维护。
