### ISSUE TITLE
安装好1panel以后,使用时候 有点懵...

### ISSUE THREAD

**Issue by leeaikong** [1Panel-dev/1Panel#623]
### 1Panel 版本

1.10

### 请描述您的需求或者改进建议

新建网站,   各种需要填写的东西,   

还有就是应用端口  php端口.... 跟网站的80端口啥区别, 完全不知道干嘛的....

有点蒙圈

**Comment by leeaikong** [comment]
![2023-4-13 17-58-4](https://user-images.githubusercontent.com/40814658/231724661-6f5d0755-2ed2-4c4f-9771-ca460a63a466.png)

咱也不懂  ,什么情况,新建网站装个WordPress ,十分钟都搞不定..... 还有那个应用端口到底是个啥意思

**Comment by realzolo** [comment]
不会用、看不懂是你自己的问题啊，不是人家的问题，多去学习。。。。这是提问题的地方

**Comment by hhun** [comment]
这是容器内部的端口，不需要管，系统好像会自动映射好。
容器和BT有很多理念不一样，很多地方比BT更麻烦，但是BT窃取用户隐私。

**Comment by WankkoRee** [comment]
可能，先了解一下容器化应用部署的概念会比较好上手？

**Comment by maninhill** [comment]
我们会持续优化交互体验和产品文档。
