### ISSUE TITLE
[FEATURE]可否暴露一个webhook的功能

### ISSUE THREAD

**Issue by GunnmF** [1Panel-dev/1Panel#6230]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

应用场景：比如自己在家搭建的服务器  一般家庭宽带是不开放一些关键的端口的   比如 80 443    然后我需要自己写个小程序跑一跑   但是小程序需要 80 443 的端口    我就像通过比如阿里云这样的服务商  中转一下   当我 ip变了  阿里云的服务器跑的OpenResty又有缓存   就会连不上   所以我需要收到 webhook后  重启OpenResty  或者执行命令干点其他事  

### 请描述你建议的实现方案

比如对外开放一个接口  [ip]:[port]/webhook?token=xxxxxx     当服务器收到这个请求   使用 token 去匹配对应需要执行的命令或者逻辑   感觉这个功能应该还是有需要的

**Comment by see-more** [comment]
支持

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，webhook 相关功能的讨论，统一汇总到该 issue #410
