### ISSUE TITLE
[FEATURE]支持自定义网站总目录,防止系统盘撑爆

### ISSUE THREAD

**Issue by lopins** [1Panel-dev/1Panel#6231]
### 1Panel 版本

13

### 请描述您的需求或者改进建议

[FEATURE]支持自定义网站总目录,防止系统盘撑爆

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们将在 v2 版本中支持该需求。
关于相关问题的讨论，将统一汇总到 issue #2783。

**Comment by zsoon-cn** [comment]
期待！
