### ISSUE TITLE
[FEATURE] 没有回收站功能，误删了文件会哭

### ISSUE THREAD

**Issue by hhun** [1Panel-dev/1Panel#624]
### 1Panel 版本

1.1

### 请描述您的需求或者改进建议

没有回收站功能，误删了文件会哭

![微信图片_20230413183316](https://user-images.githubusercontent.com/19625243/231733287-96865c27-c8e3-4947-adca-681ee29afc3e.png)
删除确定对话框里面应该显示**删除的是哪个文件**

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持文件回收站功能。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
