### ISSUE TITLE
[BUG] 貌似waf的真实ip获取不正常

### ISSUE THREAD

**Issue by W4J1e** [1Panel-dev/1Panel#6241]
### 1Panel 版本

v1.10.13-lts

### 问题描述

我此前在 openresty 的配置里写的获取客户端真实 ip 的方式，服务器上网站日志记录正常。
今天启用了 1panel 的 waf ，在自定义规则下的 CDN 处选择了打开，真实 ip 获取方式尝试了“从header列表获取”，无效，于是选择“从 HTTP Header中获取”，值为“X-Forwarded-For”，还是无效，服务器网站日志记录的 IP 是 CDN 的节点 IP。已向 CDN 那边确认传递真实客户端 ip 的方式是在 header 中使用 X-Forwarded-For。

### 重现步骤

WAF——自定义规则——CDN——打开——真实 IP 获取方式

**Comment by zhengkunwang223** [comment]
在网站那设置的，还是在全局那设置的

**Comment by W4J1e** [comment]
> 在网站那设置的，还是在全局那设置的

都设置过，全局和网站同时打开的

**Comment by zhengkunwang223** [comment]
> 服务器网站日志记录

你说的是 网站那边的 OpenResty 的 access.log 是吧
那个需要在  OpenResty 配置文件修改配置才能支持
WAF 的真实 IP 仅用于 WAF 的拦截日志

**Comment by W4J1e** [comment]
> > 服务器网站日志记录
> 
> 你说的是 网站那边的 OpenResty 的 access.log 是吧 那个需要在 OpenResty 配置文件修改配置才能支持 WAF 的真实 IP 仅用于 WAF 的拦截日志

懂了，我还想着访问都会先经过 WAF，在 WAF 这里获取了真实 IP 后传递给 openresty 记录在网站访问日志里的就直接是真实 IP。

昨晚已经再次使用手动配置了，非常感谢。
