### ISSUE TITLE
[BUG] docker中暴露范围性端口过大的情况下会导致页面卡死 例如暴露10000-20000给某个frp代理工具

### ISSUE THREAD

**Issue by cktk** [1Panel-dev/1Panel#6245]
### 1Panel 版本

v1.10.13-lts

### 问题描述

端口暴露方式
<img width="948" alt="image" src="https://github.com/user-attachments/assets/7dd3e55d-cefa-4eff-9919-f53832a95291">

列表展示
<img width="1146" alt="image" src="https://github.com/user-attachments/assets/72f05689-bd19-429e-ab71-ab7b05cbf735">

### 重现步骤

端口暴露方式添加 
<img width="948" alt="image" src="https://github.com/user-attachments/assets/7dd3e55d-cefa-4eff-9919-f53832a95291">
点击编辑页面会卡住不动弹

### 期待的正确结果

列表中如果是范围暴露的话  编辑里面也范围展示就解决问题

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们已在本地环境复现该问题，会在后续版本中优化这一功能。

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
