### ISSUE TITLE
[FEATURE] 希望在应用市场添加 Snail Job 定时任务调度平台

### ISSUE THREAD

**Issue by m-xlsea** [1Panel-dev/1Panel#6247]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

希望在应用市场能够一键安装 Snail Job 定时任务调度平台
项目地址: https://gitee.com/aizuda/snail-job
文档地址:  https://snailjob.opensnail.com/docs/quickstart/server.html#%E4%B8%89%E3%80%81%E6%9C%8D%E5%8A%A1%E9%83%A8%E7%BD%B2-service-deployment

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，我们主要以项目的 Star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有超1万 Star 的开源项目，感谢您的理解。

> 你可以将需求反馈给 [第三方仓库（由社区用户维护）](https://github.com/okxlin/appstore)。
