### ISSUE TITLE
应用备份恢复失败

### ISSUE THREAD

**Issue by rf11291** [1Panel-dev/1Panel#6252]
### 1Panel 版本

v1.10.13-lts

### 问题描述

将R2的备份应用文件下载到本地后再上传至服务器，然后进行恢复会出现`服务内部错误: the wrong recovery package does not have app.json or app.tar.gz files`这个提示，但是我去目录中检查发现，压缩文件已经被解压成功了，文件夹里也有app.json，app.tar.gz这两个文件，但就是一直提示失败

### 重现步骤

在其他服务器的面板上操作亦是如此

### 期待的正确结果

如暂时无法解决便请告诉我如何手动恢复应用，例如`openresty`，谢谢！

**Comment by rf11291** [comment]
![PixPin_2024-08-27_03-08-43](https://github.com/user-attachments/assets/4c836349-68ba-440f-b118-f0ad3934297f)

**Comment by zhengkunwang223** [comment]
OpenResty 恢复，网站列表中不会出现网站，只是把文件恢复了 这个你要先知道
你先手动解压你的备份文件 然后截图看一下都有什么

**Comment by rf11291** [comment]
> OpenResty 恢复，网站列表中不会出现网站，只是把文件恢复了 这个你要先知道 你先手动解压你的备份文件 然后截图看一下都有什么
解压后两个文件，我将app.tar.gz压缩文件解压覆盖了openresty的应用目录,但是怎么将app.json中的应用配置参数恢复？
![PixPin_2024-08-27_10-22-23](https://github.com/user-attachments/assets/48b212af-f877-4e97-9a2b-4196b3b724ee)
![PixPin_2024-08-27_10-26-44](https://github.com/user-attachments/assets/c40e8c7c-1a3d-4cb4-8d89-d5da5cb53369)

**Comment by zhengkunwang223** [comment]
> > OpenResty 恢复，网站列表中不会出现网站，只是把文件恢复了 这个你要先知道 你先手动解压你的备份文件 然后截图看一下都有什么
> > 解压后两个文件，我将app.tar.gz压缩文件解压覆盖了openresty的应用目录,但是怎么将app.json中的应用配置参数恢复？
> > ![PixPin_2024-08-27_10-22-23](https://private-user-images.githubusercontent.com/140233162/361630375-48b212af-f877-4e97-9a2b-4196b3b724ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjYxMzIsIm5iZiI6MTcyNDcyNTgzMiwicGF0aCI6Ii8xNDAyMzMxNjIvMzYxNjMwMzc1LTQ4YjIxMmFmLWY4NzctNGU5Ny05YTJiLTQxOTZiM2I3MjRlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwMjMwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYThhMGU1OWJhY2UxNjA5MTk1MjYyNjY0NTlhODk0MTg2MGEzMzgwODhkYTA1MzdiZTNhOTM0YjFkNjlkYjYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IelAlKT4F0Gd2B2oU1m_FcLKan07HScmUzeh3GdhZOY)
> > ![PixPin_2024-08-27_10-26-44](https://private-user-images.githubusercontent.com/140233162/361631248-c40e8c7c-1a3d-4cb4-8d89-d5da5cb53369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjYxMzIsIm5iZiI6MTcyNDcyNTgzMiwicGF0aCI6Ii8xNDAyMzMxNjIvMzYxNjMxMjQ4LWM0MGU4YzdjLTFhM2QtNGNiNC04ZDg5LWQ1ZGE1Y2I1MzM2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwMjMwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWM3MGIwNjFkYmE2MjNlOWZjMmI1OWVmMmM4ZDI3MjI5OGM4ZGUyOTM1N2IyNzVlODQ2MTlmMmE4NjExYzExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4DjmYMnL9smNBlMN9TZFESYIgj0bctHGbFPQKjgkeIQ)
应用的目录在 app.tar.gz 中 但是你手动操作可能会带来问题 需要自行处理

**Comment by rf11291** [comment]
> > > OpenResty 恢复，网站列表中不会出现网站，只是把文件恢复了 这个你要先知道 你先手动解压你的备份文件 然后截图看一下都有什么 解压后两个文件，我将app.tar.gz压缩文件解压覆盖了openresty的应用目录，但是怎么将app.json中的配置参数恢复， ![PixPin_2024-08-27_10-22-23](https://private-user-images.githubusercontent.com/140233162/361630375-48b212af-f877-4e97-9a2b-4196b3b724ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjYxMzIsIm5iZiI6MTcyNDcyNTgzMiwicGF0aCI6Ii8xNDAyMzMxNjIvMzYxNjMwMzc1LTQ4YjIxMmFmLWY4NzctNGU5Ny05YTJiLTQxOTZiM2I3MjRlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwMjMwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYThhMGU1OWJhY2UxNjA5MTk1MjYyNjY0NTlhODk0MTg2MGEzMzgwODhkYTA1MzdiZTNhOTM0YjFkNjlkYjYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IelAlKT4F0Gd2B2oU1m_FcLKan07HScmUzeh3GdhZOY) ![PixPin_2024-08-27_10-26-44](https://private-user-images.githubusercontent.com/140233162/361631248-c40e8c7c-1a3d-4cb4-8d89-d5da5cb53369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjYxMzIsIm5iZiI6MTcyNDcyNTgzMiwicGF0aCI6Ii8xNDAyMzMxNjIvMzYxNjMxMjQ4LWM0MGU4YzdjLTFhM2QtNGNiNC04ZDg5LWQ1ZGE1Y2I1MzM2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QwMjMwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWM3MGIwNjFkYmE2MjNlOWZjMmI1OWVmMmM4ZDI3MjI5OGM4ZGUyOTM1N2IyNzVlODQ2MTlmMmE4NjExYzExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4DjmYMnL9smNBlMN9TZFESYIgj0bctHGbFPQKjgkeIQ) 应用的目录在 app.tar.gz 中 但是你手动操作可能会带来问题 需要自行处理

现在就是将应用目录的文件恢复了，但是现在怎么从app.json恢复应用的配置参数等，不然就会出现下面这张图的情况

![PixPin_2024-08-27_10-33-29](https://github.com/user-attachments/assets/01802e80-88a7-40ab-b53b-c8686d60f931)
