### ISSUE TITLE
[BUG]空网站，流量监控异常

### ISSUE THREAD

**Issue by geekgao** [1Panel-dev/1Panel#6254]
### 1Panel 版本

v1.10.13-lts

### 问题描述

Image: https://ibb.co/P9Bmsn7
如图

### 重现步骤

新创建一个虚拟机，然后部署了1Panel

### 期待的正确结果

不太可能有这么大的流量

**Comment by geekgao** [comment]
系统是版本为Ubuntu  24.04

**Comment by ssongliu** [comment]
感谢反馈，可以执行 `ifconfig` 获取比较一下，找到对应的网卡
![image](https://github.com/user-attachments/assets/ab12f10a-fbc2-4cf9-8c44-b38ba1f9e61d)
