### ISSUE TITLE
[FEATURE]增加一些备份账号

### ISSUE THREAD

**Issue by Zevo77** [1Panel-dev/1Panel#6256]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

增加一些备份账号，阿里云盘，百度云盘，123盘什么的。我自己是使用阿里云盘，阿里云盘开发文档：https://www.yuque.com/aliyundrive/zpfszx/btw0tw?spm=aliyundrive.developer.0.0.75a34f48sfgbIn

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，重复问题 https://github.com/1Panel-dev/1Panel/issues/3393
