### ISSUE TITLE
[FEATURE]WAF功能支持对单网站设置IP黑白名单

### ISSUE THREAD

**Issue by auth007** [1Panel-dev/1Panel#6266]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

当前只能设置全局黑白名单，如果网站比较多可能出现冲突问题。建议支持对单个网站设置IP黑白名单

**Comment by zhengkunwang223** [comment]
![image](https://github.com/user-attachments/assets/eb329443-49d6-4c56-963a-8bc8180a211e)
专业版支持
