### ISSUE TITLE
[FEATURE]php增加一个伪静态功能，很多php程序都涉及到伪静态文件设置

### ISSUE THREAD

**Issue by 357341051** [1Panel-dev/1Panel#627]
### 1Panel 版本

v1.1

### 请描述您的需求或者改进建议

php增加一个伪静态功能，很多php程序都涉及到伪静态文件设置，不然无法正常使用，相当于裤子脱了，跟我说不行一样！难受

**Comment by zhengkunwang223** [comment]
您好 1.1.1版本就会支持此功能

**Comment by maninhill** [comment]
1Panel 团队加油。在裤子穿上之前就必须得发布这个功能。
