### ISSUE TITLE
MySQL 8.4.2版本无法查看当前状态

### ISSUE THREAD

**Issue by rf11291** [1Panel-dev/1Panel#6270]
### 1Panel 版本

v1.10.13-lts

### 问题描述

在使用MySQL 8.4.2版本时会出现无法查看当前状态的问题，每次进入MySQL设置界面时会弹出一个错误提示，疑似是版本问题导致的命令不同，在用5.x.x版本时则不会出现此类问题

![PixPin_2024-08-27_22-27-06](https://github.com/user-attachments/assets/afbf9358-22da-480d-aebb-edf56f83366a)

### 重现步骤

同上

### 相关日志输出

```shell
服务内部错误: ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'master status' at line 1
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，已知问题 https://github.com/1Panel-dev/1Panel/issues/6148 ，会在近期版本修复。
