### ISSUE TITLE
[BUG] postgresql 使用自定义外部端口时 连接信息 提供了错误的连接信息 

### ISSUE THREAD

**Issue by ArthurGXY** [1Panel-dev/1Panel#6274]
### 联系方式

arthurgxy@outlook.com

### 1Panel 版本

v1.10.13-lts

### 问题描述

前情提要：postgresql 数据库通过 1panel 安装，并使用了非默认的端口
在需要手动填写数据库连接信息的（docker）应用中，如果按照提供的连接信息则会无法连接。
![图片](https://github.com/user-attachments/assets/7fac3450-c5c0-4fb2-ad53-5d5ed02ab163)

### 重现步骤

- 在 1panel 中 数据库 页面上 安装 postgresql 数据库， 使用非默认端口 如 20432
- 安装一个需要自行连接数据库的应用 如 pgAdmin4 或 FreshRSS
- 使用 docker 内部hostname连接 如 1Panel-postgresql-VaBl，并按照提供的信息填写 20432 端口

### 期待的正确结果

1panel 中 数据库内部连接信息 显示内部端口 （5432） 而非服务器暴露端口

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.14-lts 版本已发布。
