### ISSUE TITLE
[FEATURE] 服务器流量控制

### ISSUE THREAD

**Issue by realzolo** [1Panel-dev/1Panel#628]
### 1Panel 版本

v1.1.0

### 请描述您的需求或者改进建议

功能描述：
    对服务器总流出流量进行监控，当流量流出在一定时间范围内超过设定值时，开启保护状态（如关闭某些服务的对外端口）。设置保护时间，保护时间过后恢复正常服务状态。

功能使用场景：
    作为文件服务器或者按流量计费时防止恶意刷流量。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中调研该需求的可行性方案。

**Comment by wanghe-fit2cloud** [comment]
经团队内部讨论，暂无支持上述功能的计划，望理解。
