### ISSUE TITLE
[FEATURE] 在1Panel创建的编排，当容器不存在时仍然显示编排文件，而不是隐藏编排文件

### ISSUE THREAD

**Issue by Ausli** [1Panel-dev/1Panel#6280]
### 1Panel 版本

1.10.13-lts

### 请描述您的需求或者改进建议

如题，容器删除或不存在时仍然显示编排文件

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
相同 issue https://github.com/1Panel-dev/1Panel/issues/5099
