### ISSUE TITLE
[FEATURE]希望能提供编辑在线编辑shell的功能，且支持定时任务。

### ISSUE THREAD

**Issue by YellCatt** [1Panel-dev/1Panel#6288]
### 1Panel 版本

1

### 请描述您的需求或者改进建议

希望能提供编辑在线编辑shell的功能，且支持定时任务。
用来开发做自动化部署

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦再详细描述一下具体的使用场景。

**Comment by YellCatt** [comment]
开发环境，不想用jenkins 了，就编辑个shell 脚本，就可以做devops 了。用的组件更少，效率更高。

**Comment by YellCatt** [comment]
> 感谢反馈，麻烦再详细描述一下具体的使用场景。

开发环境，不想用jenkins 了，就编辑个shell 脚本，就可以做devops 了。用的组件更少，效率更高。

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈，麻烦再详细描述一下具体的使用场景。
> 
> 开发环境，不想用jenkins 了，就编辑个shell 脚本，就可以做devops 了。用的组件更少，效率更高。

`主机` - `文件列表` 已经支持编辑文件，`计划任务` 页面也支持创建 `Shell 脚本` 类型任务。
> 如果是完整的 CI/CD，中短期内暂无计划。
