### ISSUE TITLE
[BUG]创建php环境后，访问php文件会提示Access denied.，响应代码为403

### ISSUE THREAD

**Issue by 52lemon6** [1Panel-dev/1Panel#629]
### 1Panel 版本

1.1.0

### 问题描述

创建php环境后，访问php文件会提示Access denied.，响应代码为403
![image](https://user-images.githubusercontent.com/40059643/231767983-d6a9f19a-679f-47d0-a99c-8b1e525a1693.png)

### 重现步骤

创建php环境网站后，将文件上传到index目录即会提示

**Comment by hhun** [comment]
我也遇到过这个问题，请你确定下根目录里面有没有 `.user.ini` 这个文文件

如果有这个文件，那么是这个文件里面的配置的路径错误导致的，这个文件是限制目录的。
要么删除这个文件，要么把这个文件里面的路径改成正确的。

**Comment by nexus181** [comment]
> 刚创建网站不能执行PHP文件，访问PHP文件会提示`Access denied`，访问静态文件能正常显示。 重启容器后，php文件就能正常访问了，这算是一个BUG

我的重启容器访问PHP文件还是会提示Access denied

**Comment by cyril-cheng** [comment]
> > 刚创建网站不能执行PHP文件，访问PHP文件会提示`Access denied`，访问静态文件能正常显示。 重启容器后，php文件就能正常访问了，这算是一个BUG
> 
> 我的重启容器访问PHP文件还是会提示Access denied

我使用了chown -R 1000:1000 index，然后也重启了容器，依然显示Access denied

**Comment by cyril-cheng** [comment]
搞定了

**Comment by l-c01** [comment]
> 刚创建网站不能执行PHP文件，访问PHP文件会提示`Access denied`，访问静态文件能正常显示。 重启容器后，php文件就能正常访问了，这算是一个BUG

这个问题似乎依然存在，刚刚迁移wordpress到1panel也出现此问题，需要重启php docker

**Comment by lchjczw** [comment]
thinkphp 依然存在这个问题 v1.9.2
