### ISSUE TITLE
[FEATURE]希望能提供docker中的服务的cpu和内存的使用率。

### ISSUE THREAD

**Issue by YellCatt** [1Panel-dev/1Panel#6293]
### 1Panel 版本

1.10.14

### 请描述您的需求或者改进建议

希望能提供docker中的服务的cpu和内存的使用率。跟群晖的类似，能在页面上直观的看到使用率，主要是docker容器的服务太多了，我是开发使用。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，目前版本已支持在容器列表和容器监控中查看使用率。
![image](https://github.com/user-attachments/assets/fd04de07-25b3-4f70-a38b-fbcb3542d603)
