### ISSUE TITLE
期望证书手动创建时选择本地文件可自动化更新

### ISSUE THREAD

**Issue by jiuyue52** [1Panel-dev/1Panel#6298]
### 1Panel 版本

专业版 v1.10.14-lts

### 请描述您的需求或者改进建议

由于1panel暂无精力适配华为云dns账号，因此使用certd程序自动化申请证书，可以推送到服务器本地

**1panel这边也能选择本地文件，但是当本地证书文件更新，1panel要想更新还需要再次选择证书路径才能获取最新证书信息，不能自动获取本地新的证书文件**
![image](https://github.com/user-attachments/assets/a50f6b97-ea88-44b0-9eaa-b0e1025d6553)

需求&改进建议：
**在选择手动上传且选择为本地文件时，此更新按钮点击后可立即获取新的本地证书文件**
![image](https://github.com/user-attachments/assets/795fec7f-bcbc-4cf2-a239-d27eaafe9867)
**在证书详情界面显示本地证书路径，以及可以配置 自动化任务：定时自动获取本地证书文件，以达到自动更新**
![image](https://github.com/user-attachments/assets/abfafb42-40a7-4dec-9e18-974926d97e8f)

### 请描述你建议的实现方案

**在选择手动上传且选择为服务器文件时，更新按钮点击后可立即获取新的本地证书文件**
**在证书详情界面显示本地证书路径，以及可以配置 自动化任务：定时自动获取本地证书文件，以达到自动更新**

**Comment by zhengkunwang223** [comment]
你用了证书自动申请证书 可以直接推送到网站证书目录吧 这样就省去了这些中间步骤

**Comment by jiuyue52** [comment]
> 你用了证书自动申请证书 可以直接推送到网站证书目录吧 这样就省去了这些中间步骤

有理，也不是不行hhh（ 但这样网站多的话，要添加好多推送任务，想着推送一遍一劳永逸，后边新增网站也不用重新添加推送任务😂😂
