### ISSUE TITLE
[FEATURE]希望增加磁盘挂载，以及容器启动条件限制

### ISSUE THREAD

**Issue by dididaguai** [1Panel-dev/1Panel#6304]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

目前手动挂载数据盘后，安装应用时修改docker-compose文件将配置文件或存储路径改到了挂载盘里面，但是服务器重启后，由于容器先于nfs挂载启动，导致容器服务异常，必须手动重启一次容器才行。

### 请描述你建议的实现方案

希望在安装应用时默认可以选择挂载目录，并且对于挂载目录的容器设置限定条件，必须在挂载目录存在时才能启动啥的
工具箱中增加磁盘挂载、扩容、共享

**Comment by wanghe-fit2cloud** [comment]
1、应用的默认重启策略是 `restart: always`，所以服务异常时会自动重启，通常不需要手动干预。
至于你提到的启动顺序问题，可以尝试手动修改 1Panel 服务器上 Docker 服务的依赖配置，例如：
```
[Unit]
After=nfs-client.target
Requires=nfs-client.target
```
2、磁盘挂载相关需求的讨论，统一汇总到该 issue #1852

**Comment by dididaguai** [comment]
> 1、应用的默认重启策略是 ，所以服务异常时会自动重启，通常不需要手动干预。 至于你提到的启动顺序问题，可以尝试手动修改 1Panel 服务器上 Docker 服务的依赖配置，例如：`restart: always`
> 
> ```
> [Unit]
> After=nfs-client.target
> Requires=nfs-client.target
> ```
> 
> 2、磁盘挂载相关需求的讨论，统一汇总到该 issue #1852

请问修改服务依赖配置，是每个应用单独修改吗？

**Comment by wanghe-fit2cloud** [comment]
> > 1、应用的默认重启策略是 ，所以服务异常时会自动重启，通常不需要手动干预。 至于你提到的启动顺序问题，可以尝试手动修改 1Panel 服务器上 Docker 服务的依赖配置，例如：`restart: always`
> > ```
> > [Unit]
> > After=nfs-client.target
> > Requires=nfs-client.target
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 2、磁盘挂载相关需求的讨论，统一汇总到该 issue #1852
> 
> 请问修改服务依赖配置，是每个应用单独修改吗？

<img width="921" alt="image" src="https://github.com/user-attachments/assets/3ccafcd9-967e-47f5-b3d6-b45058d9dcb5">
