### ISSUE TITLE
[BUG]面板概览页面以及短信告警 CPU 使用率不精准，导致不能告警

### ISSUE THREAD

**Issue by lan-yonghui** [1Panel-dev/1Panel#6309]
### 1Panel 版本

v1.10.14

### 问题描述

配置一条 CPU 大于80的告警，然后手动使用 stress-ng 对 cpu 进行满载（100%）测试10分钟，没有收到任何告警，监控页面看到 CPU 确实持续 10 分钟满载

### 重现步骤

使用压测工具或其他手段使 CPU 持续增高

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们将会在近期的版本中优化 CPU 使用率告警不精确的问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.15-lts 版本已发布。
