### ISSUE TITLE
[FEATURE] 设置权限不能给子目录批量设置权限，这个要完善。

### ISSUE THREAD

**Issue by hhun** [1Panel-dev/1Panel#631]
### 1Panel 版本

1.1

### 请描述您的需求或者改进建议

设置权限不能给子目录批量设置权限，这个要完善。
还要设置权限时，不能勾选是给 www 用户还是 root 用户权限。
BT会在文件里面显示该文件是哪个用户有权限

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
