### ISSUE TITLE
[BUG]文件路径bug

### ISSUE THREAD

**Issue by Jaffoo** [1Panel-dev/1Panel#6310]
### 1Panel 版本

v1.10.14-lts

### 问题描述

文件路径bug

### 重现步骤

在主机-文件的路径栏直接输入一个非文本文件，例如/home/own/1.png，如果这个文件是存在的，那么会提示此文件无法预览，此时点击更多-重命名当前文件夹中任何文件或文件夹会提示路径不存在。还有，点击own下的任何文件夹都无法打开，路径栏会无限叠加点击的文件夹。
如果是文本文件也不能成功预览，而是打开了一个未知路径目录

### 期待的正确结果

就算文件无法预览，也能正常操作当前目录下的文件和文件夹

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述体验。

**Comment by wanghe-fit2cloud** [comment]
v1.10.15-lts 版本已发布。
