### ISSUE TITLE
[BUG]使用挂载路径，应用创建文件类型错误

### ISSUE THREAD

**Issue by dididaguai** [1Panel-dev/1Panel#6315]
### 1Panel 版本

v1.10.14-lts

### 问题描述

默认路径都是./data啥的，如果修改为挂载的绝对路径后，创建.conf、.db类型文件直接变为了文件夹，而不是文件，导致应用异常报错。

### 重现步骤

默认路径都是./data啥的，如果修改为挂载的绝对路径后，创建.conf、.db类型文件直接变为了文件夹，而不是文件，导致应用异常报错。
应用：Cloudreve

**Comment by wanghe-fit2cloud** [comment]
出现这种情况，是因为你修改后的持久化目录中没有包含具体文件。
> 在当前版本中，如果你修改了持久化目录，应用备份功能将不会备份自定义的持久化目录。
<img width="494" alt="image" src="https://github.com/user-attachments/assets/8095ae65-b6a7-42a7-bce3-e5e950ce0221">

**Comment by dididaguai** [comment]
> 出现这种情况，是因为你修改后的持久化目录中没有包含具体文件。
> 
> > 在当前版本中，如果你修改了持久化目录，应用备份功能将不会备份自定义的持久化目录。
> 
> <img alt="图像" width="494" src="https://private-user-images.githubusercontent.com/46734380/363383091-8095ae65-b6a7-42a7-bce3-e5e950ce0221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxOTU3NTMsIm5iZiI6MTcyNTE5NTQ1MywicGF0aCI6Ii80NjczNDM4MC8zNjMzODMwOTEtODA5NWFlNjUtYjZhNy00MmE3LWJjZTMtZTVlOTUwY2UwMjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDEyNTczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4YWI4NjMzZmI1ZWEwZjJiNjIyM2M3NGE4MjNkZjY2Y2U5MTc2MDkyMjQ5Y2ZkMzQwNDM3YjQzMWZjYzE1YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E60PRxhLNHexvzabp1vME1xc72CnhSNgzQwNBcSo3j4">

意思是要手动在对应目录创建文件才行吗？

**Comment by wanghe-fit2cloud** [comment]
> > 出现这种情况，是因为你修改后的持久化目录中没有包含具体文件。
> > > 在当前版本中，如果你修改了持久化目录，应用备份功能将不会备份自定义的持久化目录。
> > 
> > 
> > <img alt="图像" width="494" src="https://private-user-images.githubusercontent.com/46734380/363383091-8095ae65-b6a7-42a7-bce3-e5e950ce0221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxOTU3NTMsIm5iZiI6MTcyNTE5NTQ1MywicGF0aCI6Ii80NjczNDM4MC8zNjMzODMwOTEtODA5NWFlNjUtYjZhNy00MmE3LWJjZTMtZTVlOTUwY2UwMjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDEyNTczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4YWI4NjMzZmI1ZWEwZjJiNjIyM2M3NGE4MjNkZjY2Y2U5MTc2MDkyMjQ5Y2ZkMzQwNDM3YjQzMWZjYzE1YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E60PRxhLNHexvzabp1vME1xc72CnhSNgzQwNBcSo3j4">
> 
> 意思是要手动在对应目录创建文件才行吗？

是的，挂载相关教程可以先参考官方文档：https://docs.docker.com/engine/storage/volumes/
