### ISSUE TITLE
[FEATURE]应用商店新增weblate

### ISSUE THREAD

**Issue by ji233-Sun** [1Panel-dev/1Panel#6318]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

https://docs.weblate.org/zh-cn/latest/admin/install/docker.html
这是官方的docker部署文档
weblate是一个十分常见的可以自部署的本地化翻译平台

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，我们主要以项目的 Star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有超1万 Star 的开源项目，感谢您的理解。

> 你可以将需求反馈给 [第三方仓库（由社区用户维护）](https://github.com/okxlin/appstore)。
