### ISSUE TITLE
[BUG]关于编辑网站主域名后关联配置文件均未改名的错误

### ISSUE THREAD

**Issue by chnjyxz** [1Panel-dev/1Panel#6319]
### 1Panel 版本

 v1.10.13-lts

### 问题描述

官方不推荐建立后再修改包名或主域名， 但在网站配置中存在此功能，修改主域名后，会导致去读去不存在的新配置文件。
这就导致，配置文件面板中是空的，但起作用的配置文件依然是旧名字。

### 重现步骤

在已经建立的网站中，设置项 其它项 修改主域名
然后网站的配置文件面板内是空的，因为系统依新的主域名去读取新的不存在的配置文件。
但是起作用的配置文件名是旧的，因为改名这一步并不去修改配置文件中的关联。
这就导致，配置文件面板中是空的，但起作用的配置文件依然是旧名字。

### 期待的正确结果

合理的方式，应该是允许修改主域名和包名，但这一步应该像新建一样，检查所有生成的配置文件，并将这些配置文件改为新的命名。

**Comment by zhengkunwang223** [comment]
请问有具体的错误截图吗？

**Comment by chnjyxz** [comment]
抱歉因为修改主域名导致配置文件混乱后我重装了服务器，并且也没有出错信息，因此无截图。
总之只要修改了主域名后，网站的配置文件查看页面内就是空的，这较容易复现，在此页面内修改配置文件并不会生效——同时生效的还是老文件名的配置文件。

**Comment by zhengkunwang223** [comment]
> 抱歉因为修改主域名导致配置文件混乱后我重装了服务器，并且也没有出错信息，因此无截图。 总之只要修改了主域名后，网站的配置文件查看页面内就是空的，这较容易复现，在此页面内修改配置文件并不会生效——同时生效的还是老文件名的配置文件。

我没有复现此问题 先关闭了 如果有具体的复现步骤 可以告诉我 再重新打开
