### ISSUE TITLE
建议商店增加  dbswitch  ，方便异构数据库之间迁移

### ISSUE THREAD

**Issue by ByZhouhang** [1Panel-dev/1Panel#6324]
### 1Panel 版本

xx

### 请描述您的需求或者改进建议

gitee链接：  https://gitee.com/dromara/dbswitch

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，我们主要以项目的 Star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有超1万 Star 的开源项目，感谢您的理解。

> 你可以将需求反馈给 [第三方仓库（由社区用户维护）](https://github.com/okxlin/appstore)。
