### ISSUE TITLE
[FEATURE]应用商店增加garnet

### ISSUE THREAD

**Issue by ji233-Sun** [1Panel-dev/1Panel#6326]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

https://github.com/microsoft/garnet
是微软对redis的一个fork，拥有比redis和keydb更优的性能
目前10.1k stars，已破w
项目根目录下有docker-compose文件可供参考

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上架 [Garnet](https://github.com/microsoft/garnet)

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/5396
