### ISSUE TITLE
[FEATURE]上架应用 AppFlowy

### ISSUE THREAD

**Issue by TIkc9** [1Panel-dev/1Panel#6330]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

新增应用
应用名称：AppFlowy
介绍：将项目、Wiki 和团队与 AI 结合在一起。AppFlowy 是一个 AI 协作工作区，您可以在其中实现更多目标，而不会失去对数据的控制。Notion的最佳开源替代品。
github：https://github.com/AppFlowy-IO/AppFlowy
官方支持docker部署，且一直在维护、更新

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本上架该应用。

**Comment by QYG2297248353** [comment]
Outline 也是一个不错的选择

https://github.com/outline/outline

**Comment by wanghe-fit2cloud** [comment]
重复 https://github.com/1Panel-dev/1Panel/issues/4347
