### ISSUE TITLE
[BUG]容器编辑后保存端口丢失

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#6333]
### 1Panel 版本

v1.10.14-lts

### 问题描述

容器如果停止后在启动，映射的端口正常

但是，如果容器停止后编辑任意内容，在启动，映射的端口丢失

### 重现步骤

复现
![20240902-141156](https://github.com/user-attachments/assets/7a03c05b-fd4a-4917-8e18-d216e577032e)

端口丢失
![PixPin_2024-09-02_14-15-17](https://github.com/user-attachments/assets/b1e094d3-d841-4508-b57f-eb0369faa2a2)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，目前确实存在在编辑停止状态的容器时，端口配置丢失的问题。我们会在近期版本修复。

**Comment by see-more** [comment]
https://github.com/1Panel-dev/1Panel/blob/228e3d9ae3216995ab0add7be75b0dedf178fc15/backend/app/service/container.go#L1305-L1312

```go
containers, err := client.ContainerList(context.Background(), container.ListOptions{
    All:ture
}) 
 if err != nil { 
 	return nil, err 
 } 
 samePortMap := make(map[string]dto.PortHelper) 
 for _, container := range containers { 
 	if container.ID == id { 
                //output:[]
                fmt.Println(container.Ports)
 		ports := loadContainerPort(container.Ports) 
```
docker引擎无法返回停止状态的容器端口配置，建议禁止编辑停止状态容器配置，或者将容器配置持久化到数据库中

**Comment by wanghe-fit2cloud** [comment]
> docker引擎无法返回停止状态的容器端口配置，建议禁止编辑停止状态容器配置，或者将容器配置持久化到数据库中

停止状态的容器可以通过 `inspect` 命令查看其端口信息，是否可以通过这种方式来获取：
![image](https://github.com/user-attachments/assets/1f2718de-740e-4daa-b04d-982d7e98b62d)

**Comment by wanghe-fit2cloud** [comment]
v1.10.15-lts 版本已发布。
