### ISSUE TITLE
[FEATURE]是否可以出一个多盘同步(备份)文件的功能

### ISSUE THREAD

**Issue by Lrunlin** [1Panel-dev/1Panel#6335]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

添加一个用于多盘备份的功能，因为部分用户时在家里搭建小型服务器可能需要一个固态硬盘读一个机械硬盘备份所以如果有一个功能可以自动把数据写到机械应该里面作为备份的话很方便

### 请描述你建议的实现方案

https://www.ruanyifeng.com/blog/2020/08/rsync.html

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持该需求 https://github.com/1Panel-dev/1Panel/issues/3895
