### ISSUE TITLE
[BUG]网站菜单中同一个网站配置两个域名删除一个出现网站不存在，请检查域名

### ISSUE THREAD

**Issue by yyg-max** [1Panel-dev/1Panel#6336]
### 联系方式

2144935044@qq.com

### 1Panel 版本

v1.10.14-lts

### 问题描述

网站菜单中同一个网站配置两个域名删除一个出现网站不存在，请检查域名

### 重现步骤

打开网站菜单随便选一个网站进行配置点击域名设置配置两个域名删除其中一个domains就为null了

**Comment by zhengkunwang223** [comment]
已复现 后续版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.10.15-lts 版本已发布。
