### ISSUE TITLE
[BUG] docker 无法使用本地镜像构建容器

### ISSUE THREAD

**Issue by realzolo** [1Panel-dev/1Panel#634]
### 联系方式

zolo@onezol.com

### 1Panel 版本

v1.1.0

### 问题描述

本地使用Dockerfile构建出的镜像，无法使用面板启动容器。
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/63219216/231828252-256a476e-cd45-46c9-9ada-0fe85cdb26d8.png">
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/63219216/231828966-91eef548-8c30-41ef-955d-a46cfec7929c.png">

### 重现步骤

使用本地构建的镜像启动容器应该可重现

<img width="1657" alt="image" src="https://user-images.githubusercontent.com/63219216/231829681-90da759d-dc66-4923-b6e4-b8ffdd84debc.png">

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by zyyfit** [comment]
感谢反馈，后续版本修复

**Comment by wanghe-fit2cloud** [comment]
建议升级到 v1.1.3 版本，查看是否还存在该问题。
