### ISSUE TITLE
[FEATURE]讲真的，登陆界面好丑，建议增加一个自定义

### ISSUE THREAD

**Issue by QingXuan2000** [1Panel-dev/1Panel#6340]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

讲真的，登陆界面好丑，建议增加一个自定义

**Comment by see-more** [comment]
🤔自定义登陆界面？

**Comment by QingXuan2000** [comment]
怎么说呢，自定义背景图片也行，当然能自定义更多会更好
