### ISSUE TITLE
[FEATURE]优化容器界面在不同设备下的样式布局

### ISSUE THREAD

**Issue by see-more** [1Panel-dev/1Panel#6347]
### 1Panel 版本

1.10.13

### 请描述您的需求或者改进建议

容器页面样式为
![unchange moblile](https://github.com/user-attachments/assets/ffab0e15-042c-4fe3-a3b0-faa44926ba4a)
![unchange](https://github.com/user-attachments/assets/cf6a30fd-bbdc-494b-971f-72105f871f4c)

### 请描述你建议的实现方案

修改样式为
![changeed-display](https://github.com/user-attachments/assets/2914e7f9-75d2-499e-974a-ebbc5a235664)
![changefd-display](https://github.com/user-attachments/assets/008ea4ab-b3e0-4a7d-975f-f1b32541da4e)

**Comment by wanghe-fit2cloud** [comment]
感谢支持。

**Comment by wanghe-fit2cloud** [comment]
待测试验证通过后会标记为 `已完成` 标签，并在版本发布后关闭该 issue。

**Comment by wanghe-fit2cloud** [comment]
v1.10.15-lts 版本已发布。
