### ISSUE TITLE
[FEATURE]nexus官方镜像不支持arm64,建议换成社区版镜像

### ISSUE THREAD

**Issue by IsQiao** [1Panel-dev/1Panel#6350]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

官方镜像没有arm架构
https://hub.docker.com/r/sonatype/nexus3/tags

### 请描述你建议的实现方案

建议换成社区版
https://hub.docker.com/r/sonatypecommunity/nexus3/tags

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们暂时仍会采用官方镜像。对于 arm64 服务器，我们建议在安装应用时手动替换 compose 文件中的镜像，望理解。
