### ISSUE TITLE
[BUG]PHP8.3.8无法安装Snuffleupagus拓展

### ISSUE THREAD

**Issue by ji233-Sun** [1Panel-dev/1Panel#6351]
### 1Panel 版本

v1.10.14-lts

### 问题描述

我在PHP中安装Snuffleupagus拓展时发现，该拓展无法正常被安装
![image](https://github.com/user-attachments/assets/4d551bea-8205-4686-adac-95425cb6eaea)
查阅build.log也发现，该拓展并无安装进程（正常被安装的拓展除了这一个匹配项还会有---------- Install zip ----------这样子的字符串被匹配）
在phpinfo中，也没有找到该拓展
![image](https://github.com/user-attachments/assets/7879c7bb-b152-4817-8c6a-f9fdfa238acc)
build.log:
[build.log](https://github.com/user-attachments/files/16845257/build.log)

### 重现步骤

PHP8.3.8容器中安装Snuffleupagus拓展即可复现

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们已在本地环境复现该问题，将在近期版本中进行修复。

**Comment by wanghe-fit2cloud** [comment]
该问题已修复，请点击应用商店右上角的【更新应用列表】按钮，更新完成后重新安装 PHP 运行环境即可。
