### ISSUE TITLE
[BUG]halo升级时的自动备份恢复弹窗无法关闭

### ISSUE THREAD

**Issue by TIkc9** [1Panel-dev/1Panel#6355]
### 1Panel 版本

v1.10.14-lts

### 问题描述

恢复halo更新时的自动备份，密码弹窗无法关闭，见图
![image](https://github.com/user-attachments/assets/3deffda9-15a9-497b-b314-66a8192be1c2)

### 重现步骤

halo-备份-恢复

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.15-lts 版本已发布。
