### ISSUE TITLE
[FEATURE] 短信告警功能支持自定义通知手机号

### ISSUE THREAD

**Issue by RealHeart** [1Panel-dev/1Panel#6357]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

支持在面板自定义手机号，而不是使用凌霄账号绑定手机号

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持该需求。

**Comment by wanghe-fit2cloud** [comment]
v1.10.22 版本已发布。
