### ISSUE TITLE
[BUG]移动端网站页面和数据库页面样式

### ISSUE THREAD

**Issue by see-more** [1Panel-dev/1Panel#6359]
### 1Panel 版本

latest

### 问题描述

- /websites
![图片](https://github.com/user-attachments/assets/d8737bb0-79f3-4464-8dfe-528bcca2d635)
- /database/*
![图片](https://github.com/user-attachments/assets/2b109043-7fd5-4c21-ab9f-392a2e917fec)

### 重现步骤

切换页面大小

### 期待的正确结果

- /websites
![图片](https://github.com/user-attachments/assets/772b4f31-e359-414c-8354-779ea004d607)
- /database/*
![图片](https://github.com/user-attachments/assets/d68f576f-c206-485f-801f-8982a4aa0b2f)

**Comment by wanghe-fit2cloud** [comment]
感谢支持 👍

**Comment by wanghe-fit2cloud** [comment]
v1.10.15-lts 版本已发布。
