### ISSUE TITLE
[FEATURE]nginx的访问日志和错误日志过滤一些无用的静态资源记录

### ISSUE THREAD

**Issue by 357341051** [1Panel-dev/1Panel#636]
### 1Panel 版本

1.1

### 请描述您的需求或者改进建议

加一个过滤静态资源的日志记录，别啥都记录，静态资源记录没啥用啊，比如css,js,图片这些：
![9bdc1db79de431d553f164ed5d562a5](https://user-images.githubusercontent.com/118408640/231919102-973d8d2d-f5ee-414f-a606-658669559018.png)
浪费空间和审查时间，提升io性能

### 请描述你建议的实现方案

Nginx 解决error.log和access.log日志的改善总结，参考：https://mp.weixin.qq.com/s/hLXAE8jgVhj4zR2yJREdjw

**Comment by zhengkunwang223** [comment]
感谢建议 我们看一下怎么实现

**Comment by maninhill** [comment]
请问这个问题有进展吗？

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is there any progress on this issue?

**Comment by zhengkunwang223** [comment]
这个需求我们更建议您直接编辑配置文件来实现

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
We recommend that you directly edit the configuration file to achieve this requirement.
