### ISSUE TITLE
[FEATURE] 创建备份账号时，OSS 获取 Bucket 列表希望增加手动输入

### ISSUE THREAD

**Issue by lyujp** [1Panel-dev/1Panel#6378]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

创建备份账号，使用 S3 或阿里云填写信息时，需要系统获取 Bucket 列表。在使用阿里云 OSS 时，配置 Bucket 授权访问策略时，完全控制也无法获取 Bucket 列表，使用较为麻烦，且获取列表功能在后续使用过程中完全不再需要。

### 请描述你建议的实现方案

建议这里同时允许手动填写。在实际使用中，列 Bucket 不是必要权限

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.10.15-lts 版本已发布。
