### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by li7355608** [1Panel-dev/1Panel#6383]
### 1Panel 版本

v1.10.14-lts

### 问题描述

应用商店的应用备份功能，点击备份后弹出密码框，此时如果点击取消，抽屉会收缩并且提示框卡死，无论是取消还是右上角叉号都没用

### 重现步骤

进入应用商店，选择备份已安装的应用，点击备份后弹出是否加密的提示框，此时点击取消

### 期待的正确结果

密码对话框消失，同时右侧的抽屉并不收回，仍保留在备份列表页面

### 附加信息

![image](https://github.com/user-attachments/assets/3f44c9ab-86c9-464c-8201-5437f3bbef89)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，已知问题 https://github.com/1Panel-dev/1Panel/issues/6355
