### ISSUE TITLE
[BUG]移动端文件页面样式和防火墙页面样式

### ISSUE THREAD

**Issue by see-more** [1Panel-dev/1Panel#6385]
### 1Panel 版本

latest

### 问题描述

- hosts/files
![unchange_file](https://github.com/user-attachments/assets/fd19a3c1-eb51-4016-9ff7-cddda269feec)
- hosts/firewall/*
![图片](https://github.com/user-attachments/assets/7f3a2018-ed2f-42b5-9bd7-49bd929a5290)

### 重现步骤

移动端页面

### 期待的正确结果

![changed_file](https://github.com/user-attachments/assets/cfe758dc-600e-4e82-90b7-89207a5596fe)

![图片](https://github.com/user-attachments/assets/64aeffe5-e6f9-4d9b-99d7-a1797296d887)

**Comment by zhengkunwang223** [comment]
感谢支持

**Comment by wanghe-fit2cloud** [comment]
v1.10.15-lts 版本已发布。
