### ISSUE TITLE
[BUG]1panel在商店点击安装Java运行环境就跳转到，运行环境页面，而不是应用安装页面，无法安装Java、Node、Go，这是为什么

### ISSUE THREAD

**Issue by swordman20** [1Panel-dev/1Panel#6388]
### 联系方式

xiaweifeng@live.cn

### 1Panel 版本

v.1.10.14

### 问题描述

1panle在商店点击安装Java运行环境就跳转到，运行环境页面，而不是应用安装页面，无法安装Java、Node、Go，这是为什么。浏览Issues，有人反应这个问题，有人回复v.1.10.13已经解决了。可是我升级了，也还是这样的问题，不知道是不是bug

### 重现步骤

我本想在，网站->运行环境->创建Java、Node.js运行环境，创建完成启动总是失败，并且无日志描述。然后看论坛反应，应该需要从应用商店安装对应环境的Java和Node.js版本，才能创建运行环境。
我在1panle在商店点击安装Java运行环境就跳转到，运行环境页面，导致无法安装Java、Node.js。

### 期待的正确结果

1panle在商店点击安装Java，可以选择安装Java版本。并成功安装。

### 附加信息

![WX20240906-090905@2x](https://github.com/user-attachments/assets/0e1d9493-17fa-4a8b-b2fe-f2c169f8a678)
![WX20240906-091032@2x](https://github.com/user-attachments/assets/52e46cd3-7a5c-451c-a542-6b42fa5173e8)

**Comment by zhengkunwang223** [comment]
逻辑就是这样 可以先看一下我们的文档 https://1panel.cn/docs/user_manual/websites/node/

**Comment by swordman20** [comment]
> 逻辑就是这样可以先看一下我们的文档https://1panel.cn/docs/user_manual/websites/node/

我看了你们的文档，但是，首先是不是要在应用商店安装了对于的Java版本，才能运行环境里面的Java。问题一，我在应用商店里面无法安装Java。问题二，即使我无法安装Java、Node，我直接创建运行环境，确定后，启动直接报错。服务器内部错误，启动失败！

![WX20240906-095245@2x](https://github.com/user-attachments/assets/6847580e-4604-45e2-8f04-566036f77a01)

**Comment by zhengkunwang223** [comment]
> > 逻辑就是这样可以先看一下我们的文档https://1panel.cn/docs/user_manual/websites/node/
> 
> 我看了你们的文档，但是，首先是不是要在应用商店安装了对于的Java版本，才能运行环境里面的Java。问题一，我在应用商店里面无法安装Java。问题二，即使我无法安装Java、Node，我直接创建运行环境，确定后，启动直接报错。服务器内部错误，启动失败！
> 
> ![WX20240906-095245@2x](https://private-user-images.githubusercontent.com/7270004/365003436-6847580e-4604-45e2-8f04-566036f77a01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1ODgzOTMsIm5iZiI6MTcyNTU4ODA5MywicGF0aCI6Ii83MjcwMDA0LzM2NTAwMzQzNi02ODQ3NTgwZS00NjA0LTQ1ZTItOGYwNC01NjYwMzZmNzdhMDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMDIwMTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGMwZDcyNTBlYWM4YmI1OTEwYmYwMGVhNzdjMWZmY2EyODBiNTIyZmVhMmQ3ZDJkNTA0NWM0ODIwZTQxY2QyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zU4uY8Rd_Ju_gG6WM6PYCV0LrT0rzx2Ck0XzJoTNvBY)

1. Java Go Node PHP 等运行环境 都是要在运行环境页面安装的
2. 创建运行环境失败 需要看日志和错误信息 鼠标移动到失败状态上 可以看报错信息 点击日志按钮 也可以看运行中的报错信息

**Comment by swordman20** [comment]
> > > 逻辑就是这样可以先看一下我们的文档https://1panel.cn/docs/user_manual/websites/node/
> > 
> > 
> > 我看了你们的文档，但是，首先是不是要在应用商店安装了Java版本，才能在Java里面运行环境。问题一，我在应用商店里面安装无法Java。问题二，即使我无法安装Java 、Node，我直接创建运行环境，确定后，启动直接报错。服务器内部错误，启动失败！
> > ![WX20240906-095245@2x](https://private-user-images.githubusercontent.com/7270004/365003436-6847580e-4604-45e2-8f04-566036f77a01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1ODgzOTMsIm5iZiI6MTcyNTU4ODA5MywicGF0aCI6Ii83MjcwMDA0LzM2NTAwMzQzNi02ODQ3NTgwZS00NjA0LTQ1ZTItOGYwNC01NjYwMzZmNzdhMDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMDIwMTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGMwZDcyNTBlYWM4YmI1OTEwYmYwMGVhNzdjMWZmY2EyODBiNTIyZmVhMmQ3ZDJkNTA0NWM0ODIwZTQxY2QyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zU4uY8Rd_Ju_gG6WM6PYCV0LrT0rzx2Ck0XzJoTNvBY)
> 
> 1. Java Go Node PHP 等运行环境都是要在运行环境页面安装的
> 2. 创建运行环境失败 需要看日志和错误信息 鼠标移动到失败状态上 可以看报错信息 点击日志按钮 也可以看运行中的报错信息

感谢您的回复。
[我再次概述一下我的问题。相同类型问题[#5900](https://github.com/1Panel-dev/1Panel/issues/5900)。
**1.Java Go Node PHP 等运行环境都是要在运行环境页面安装的。**
答：我无法安装，它会直接跳转到，网站->运行环境的页面。

**2.创建运行环境失败 需要看日志和错误信息 鼠标移动到失败状态上 可以看报错信息 点击日志按钮 也可以看运行中的报错信息**
答：创建运行环境成功，但是启动失败，无任何错误日志。

![WX20240906-100945@2x](https://github.com/user-attachments/assets/913c1dfc-e99a-438c-8081-128986329d81)
![WX20240906-101029@2x](https://github.com/user-attachments/assets/d78e90d1-63f3-4073-89a6-5717fa1010e7)

您能理解了吗？我看过文档，也看过#5900反应的问题。我的问题和他的一样，我不知道为什么关闭了那个issues。我的1panle版本已经是最新的了。

**Comment by zhengkunwang223** [comment]
> > > > 逻辑就是这样可以先看一下我们的文档https://1panel.cn/docs/user_manual/websites/node/
> > > 
> > > 
> > > 我看了你们的文档，但是，首先是不是要在应用商店安装了Java版本，才能在Java里面运行环境。问题一，我在应用商店里面安装无法Java。问题二，即使我无法安装Java 、Node，我直接创建运行环境，确定后，启动直接报错。服务器内部错误，启动失败！
> > > ![WX20240906-095245@2x](https://private-user-images.githubusercontent.com/7270004/365003436-6847580e-4604-45e2-8f04-566036f77a01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1ODgzOTMsIm5iZiI6MTcyNTU4ODA5MywicGF0aCI6Ii83MjcwMDA0LzM2NTAwMzQzNi02ODQ3NTgwZS00NjA0LTQ1ZTItOGYwNC01NjYwMzZmNzdhMDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMDIwMTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGMwZDcyNTBlYWM4YmI1OTEwYmYwMGVhNzdjMWZmY2EyODBiNTIyZmVhMmQ3ZDJkNTA0NWM0ODIwZTQxY2QyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zU4uY8Rd_Ju_gG6WM6PYCV0LrT0rzx2Ck0XzJoTNvBY)
> > 
> > 
> > 
> > 1. Java Go Node PHP 等运行环境都是要在运行环境页面安装的
> > 2. 创建运行环境失败 需要看日志和错误信息 鼠标移动到失败状态上 可以看报错信息 点击日志按钮 也可以看运行中的报错信息
> 
> 感谢您的回复。 [我再次概述一下我的问题。相同类型问题[#5900](https://github.com/1Panel-dev/1Panel/issues/5900)。 **1.Java Go Node PHP 等运行环境都是要在运行环境页面安装的。** 答：我无法安装，它会直接跳转到，网站->运行环境的页面。
> 
> **2.创建运行环境失败 需要看日志和错误信息 鼠标移动到失败状态上 可以看报错信息 点击日志按钮 也可以看运行中的报错信息** 答：创建运行环境成功，但是启动失败，无任何错误日志。
> 
> ![WX20240906-100945@2x](https://private-user-images.githubusercontent.com/7270004/365008149-913c1dfc-e99a-438c-8081-128986329d81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1ODkxODgsIm5iZiI6MTcyNTU4ODg4OCwicGF0aCI6Ii83MjcwMDA0LzM2NTAwODE0OS05MTNjMWRmYy1lOTlhLTQzOGMtODA4MS0xMjg5ODYzMjlkODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMDIxNDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDU1NjU0YmRjZjkxMWEwMTA3MGU4MDdiZDczMDI2YzdmMTRhZjAxNGRiM2QxMTJjZTcwZWQyZWY2YTA3YjhiOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6eng5vVnj2XO-5trWyXxOclqg9KNGbqVydNs2tElIdM) ![WX20240906-101029@2x](https://private-user-images.githubusercontent.com/7270004/365008186-d78e90d1-63f3-4073-89a6-5717fa1010e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1ODkxODgsIm5iZiI6MTcyNTU4ODg4OCwicGF0aCI6Ii83MjcwMDA0LzM2NTAwODE4Ni1kNzhlOTBkMS02M2YzLTQwNzMtODlhNi01NzE3ZmExMDEwZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMDIxNDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGY2YjU2ZmU0OGQyY2I3YTY1Nzc4ZDY5MjQ1YWVlN2FkOTc2ZGY3NTJjZjI1YmNkMGZkNDY3YjNhNTQ4NTQxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Hl1bolcvxSMSyJSAc86ogH4sszIdfn4DGyEWdfkTOM0)
> 
> 您能理解了吗？我看过文档，也看过#5900反应的问题。我的问题和他的一样，我不知道为什么关闭了那个issues。我的1panle版本已经是最新的了。

1.  逻辑就是这么设计的 必须从 运行环境菜单安装 Java Node Go PHP 等运行环境
2. 没有日志和错误不太常见 启动的时候选 Node 项目的目录了吗

**Comment by swordman20** [comment]
> > > > > 逻辑就是这样可以先看一下我们的文档https://1panel.cn/docs/user_manual/websites/node/
> > > > 
> > > > 
> > > > 我看了你们的文档，但是，首先是不是要在应用商店里面安装了Java版本，才能在Java里面运行环境。问题一，我在应用商店里面安装无法Java。问题二，即使我无法安装Java、Node ，我直接创建运行环境，确定后，启动直接报错。服务器内部错误，启动失败！
> > > > ![WX20240906-095245@2x](https://private-user-images.githubusercontent.com/7270004/365003436-6847580e-4604-45e2-8f04-566036f77a01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1ODgzOTMsIm5iZiI6MTcyNTU4ODA5MywicGF0aCI6Ii83MjcwMDA0LzM2NTAwMzQzNi02ODQ3NTgwZS00NjA0LTQ1ZTItOGYwNC01NjYwMzZmNzdhMDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMDIwMTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGMwZDcyNTBlYWM4YmI1OTEwYmYwMGVhNzdjMWZmY2EyODBiNTIyZmVhMmQ3ZDJkNTA0NWM0ODIwZTQxY2QyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zU4uY8Rd_Ju_gG6WM6PYCV0LrT0rzx2Ck0XzJoTNvBY)
> > > 
> > > 
> > > 
> > > 1. Java Go Node PHP 等运行环境都是要在运行环境页面安装的
> > > 2. 创建运行环境失败 需要看日志和错误信息 鼠标移动到失败状态上 可以看报错信息 点击日志按钮 也可以看运行中的报错信息
> > 
> > 
> > 感谢您的回复。 [我再次概述了一下我的问题。相同类型问题[#5900](https://github.com/1Panel-dev/1Panel/issues/5900)。**1.Java Go Node PHP 等运行环境都是要在运行环境页面安装的。**答：我无法安装，它会直接跳转到，网站->运行环境的页面。
> > **2.运行环境失败 需要看日志和错误信息 鼠标移动到失败状态上 可以看报错信息 点击日志按钮 也可以看创建运行中的报错信息**答：创建运行环境成功，但是启动失败，无任何错误日志。
> > ![WX20240906-100945@2x](https://private-user-images.githubusercontent.com/7270004/365008149-913c1dfc-e99a-438c-8081-128986329d81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1ODkxODgsIm5iZiI6MTcyNTU4ODg4OCwicGF0aCI6Ii83MjcwMDA0LzM2NTAwODE0OS05MTNjMWRmYy1lOTlhLTQzOGMtODA4MS0xMjg5ODYzMjlkODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMDIxNDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDU1NjU0YmRjZjkxMWEwMTA3MGU4MDdiZDczMDI2YzdmMTRhZjAxNGRiM2QxMTJjZTcwZWQyZWY2YTA3YjhiOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6eng5vVnj2XO-5trWyXxOclqg9KNGbqVydNs2tElIdM) ![WX20240906-101029@2x](https://private-user-images.githubusercontent.com/7270004/365008186-d78e90d1-63f3-4073-89a6-5717fa1010e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1ODkxODgsIm5iZiI6MTcyNTU4ODg4OCwicGF0aCI6Ii83MjcwMDA0LzM2NTAwODE4Ni1kNzhlOTBkMS02M2YzLTQwNzMtODlhNi01NzE3ZmExMDEwZTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMDIxNDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGY2YjU2ZmU0OGQyY2I3YTY1Nzc4ZDY5MjQ1YWVlN2FkOTc2ZGY3NTJjZjI1YmNkMGZkNDY3YjNhNTQ4NTQxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Hl1bolcvxSMSyJSAc86ogH4sszIdfn4DGyEWdfkTOM0)
> > 您能理解吗？我看过文档，也看过#5900反应的问题。我的问题和他的一样，我不知道为什么关闭了那个问题。我的1panle版本已经是最新的了。
> 
> 1. 逻辑就是这么设计的 必须从运行环境菜单安装 Java Node Go PHP 等运行环境
> 2. 没有日志和错误不太常见 启动的时候选择 Node 项目的目录了吗

我作为一名程序员，我来回答一下你的回复，并重复提出我的问题。
**1. 逻辑就是这么设计的 必须从运行环境菜单安装 Java Node Go PHP 等运行环境**
答：你应该说，“1panle，运行环境，依赖于应用商店安装的各版本，Java、Node.js、Go。你首先需要从应用商店安装对应的程序。才能在网站->运行环境里面，创建已经下载的程序，运行。”
**我的问题是，我压根无法在应用商店安装运行环境的程序。Java、Go、Node.js都无法安装**

**2. 没有日志和错误不太常见 启动的时候选择 Node 项目的目录了吗**
答：这个可以理解成，你连应用程序都没安装，就创建运行指令，那肯定失败。至于没有日志，那肯定是，1panle设计，只输出Java、Node应用程序的日志。你连应用程序都没有，那里来的错误日志。
当然这个1panle可以优化一下，如果判断没有，下载对应的Java、Node等软件，就无法创建运行环境指令。

您好，请不要复制粘贴回复，“逻辑就是这么设计的，你看一下文档 ”之类的话语，我表示，看过文档。如果您这边不知道问题为什么这样。请让其他人来回复一下。
