### ISSUE TITLE
[QUESTION] 国外的vps 1.05在线更新 提示错误

### ISSUE THREAD

**Issue by bulesky89857** [1Panel-dev/1Panel#639]
### 请描述您的问题

服务内部错误: Get "https://resource.fit2cloud.com/1panel/package/stable/latest": x509: certificate signed by unknown authority
改如何升级？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，1Panel 的安装包在国内阿里云 oss，可能是网络原因导致的升级失败。
你可以下载[最新版本离线包](https://resource.fit2cloud.com/1panel/package/stable/v1.1.0/release/1panel-v1.1.0-linux-amd64.tar.gz)，试一下全新安装。

**Comment by bulesky89857** [comment]
> 感谢反馈，1Panel 的安装包在国内阿里云 oss，可能是网络原因导致的升级失败。 你可以下载[最新版本离线包](https://resource.fit2cloud.com/1panel/package/stable/v1.1.0/release/1panel-v1.1.0-linux-amd64.tar.gz)，试一下全新安装。

原数据会丢失吗
