### ISSUE TITLE
[BUG]添加docker仓库时，可能密码输错了点击了确认添加，整个服务挂掉，无法访问

### ISSUE THREAD

**Issue by Shuai-S** [1Panel-dev/1Panel#6392]
### 1Panel 版本

v1.10.14-lts

### 问题描述

添加阿里云个人私有仓库，密码可能输入错误，服务直接中断响应，因为是内网穿透访问，不确定是docker挂了还是整个1Panel服务挂掉

### 重现步骤

添加阿里云个人私有仓库，输入账号密码
点击确定添加
服务直接中断响应了

### 期待的正确结果

如果密码正确则添加成功，密码错误则提示响应，不应该直接服务中断

**Comment by wanghe-fit2cloud** [comment]
1、整个服务挂掉是指的 1Panel 还是通过容器化运行的其他服务？
2、通过 `systemctl status docker` 和 `1pctl status` 命令确认一下是 docker 和 1Panel 的服务状态。
