### ISSUE TITLE
增加数据库管理工具DBeaver CE

### ISSUE THREAD

**Issue by TIkc9** [1Panel-dev/1Panel#6398]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

多种数据库管理工具DBeaver
项目地址：https://github.com/dbeaver/dbeaver
dockerhub地址：https://hub.docker.com/r/dbeaver/cloudbeaver

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上架 [DBeaver](https://github.com/dbeaver/dbeaver)

**Comment by wanghe-fit2cloud** [comment]
应用已上架，进入 `应用商店` 列表，点击右上角的【更新应用列表】按钮，待同步完成后即可安装应用。
