### ISSUE TITLE
[FEATURE] 在webui上的ufw防火墙上兼容ipv6地址段填写

### ISSUE THREAD

**Issue by jkfujr** [1Panel-dev/1Panel#6399]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

在webui上的ufw防火墙上兼容ipv6地址段填写

![截图_2024-09-06_16-34-07](https://github.com/user-attachments/assets/026cd817-b83e-40d3-8fd7-54a966db71fa)

### 请描述你建议的实现方案

当前只能在ssh上用命令添加

![截图_2024-09-06_16-35-07](https://github.com/user-attachments/assets/44453670-6bc2-4a4f-9b75-db4ac94ff985)

添加后也能正常显示

![截图_2024-09-06_16-36-13](https://github.com/user-attachments/assets/7bbfb734-9785-4645-a7b5-10b8cc5b38c8)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本兼容 IPv6 地址段。

**Comment by wanghe-fit2cloud** [comment]
v1.10.15-lts 版本已发布。
