### ISSUE TITLE
[FEATURE] Docker下载全部日志的时候会耽误很多时间

### ISSUE THREAD

**Issue by cktk** [1Panel-dev/1Panel#6403]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

比如我需要下载全部docker的日志   那肯定是docker日志特别多 
目前的逻辑是先加载全部日志 加载完了再下载 所需时间就很长 如果可以在后台把日志打包成tar 既能压缩 又能快速的下载

### 请描述你建议的实现方案

推荐加上个进度条 使用异步进行下载  如果走nginx的情况下可能会因为超时时间短而导致超时
先后台压缩好文件 推送给前端  点击链接下载 

![image](https://github.com/user-attachments/assets/39663ae4-3bf0-40af-88e0-141e7c158878)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
