### ISSUE TITLE
[BUG] 在1panel 部署java 项目的时候 无法设置 容器的时区，导致与服务器环境差了八小时

### ISSUE THREAD

**Issue by yoke0104x** [1Panel-dev/1Panel#6406]
### 联系方式

2480790748@qq.com

### 1Panel 版本

v1.10.14-lts

### 问题描述

在1panel 部署java 项目的时候 无法设置 容器的时区，导致与服务器环境差了八小时

### 重现步骤

无法设置容器的时区

### 期待的正确结果

在1panel 部署java 项目的时候 可自定义挂载目录

### 相关日志输出

```shell
无
```

### 附加信息

无

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，重复 issue https://github.com/1Panel-dev/1Panel/issues/5984
