### ISSUE TITLE
[FEATURE] 通过面板访问应用网页

### ISSUE THREAD

**Issue by Dr-TSNG** [1Panel-dev/1Panel#6408]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

目前应用只能通过 服务器ip/域名+服务端口 访问，开放端口会存在很大的安全风险（如果应用本身有安全漏洞）。某竞品对 phpmyadmin 提供通过面板访问的功能，希望 1panel 也加入这样的功能，而且可以不限于 phpmyadmin，其他应用也可以加上。

### 请描述你建议的实现方案

假设面板通过 `example.com:15041` 访问，则可以通过类似 `example.com:15041/apps/installed/phpmyadmin` 来访问应用的网页接口，这样可以避免开放外部访问。

**Comment by maninhill** [comment]
这个有道理。

**Comment by zhengkunwang223** [comment]
在以前的版本有过测试 由于我们是容器模式  
OpenResty 反代 phpmyadmin 二级目录的情况下访问会异常
Go 完全代理 phpmyadmin 的前后端这个暂时也没找到好的方案
我们会在后续版本继续找解决方案

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，v2 版本会支持自定义应用跳转链接功能，参考：https://github.com/1Panel-dev/1Panel/issues/6367
