### ISSUE TITLE
[FEATURE] 应用商店增加Prometheus采集器node-exporter

### ISSUE THREAD

**Issue by Tky2022** [1Panel-dev/1Panel#6414]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

Prometheus采集器node-exporter
项目地址：https://github.com/prometheus/node_exporter
dockerhub地址：https://hub.docker.com/r/prom/node-exporter

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上架该应用。

**Comment by wanghe-fit2cloud** [comment]
已上架。
