### ISSUE TITLE
[FEATURE] 建议应用商店增加第三方/私有应用源配置

### ISSUE THREAD

**Issue by Tky2022** [1Panel-dev/1Panel#6416]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

目前自建了一些个人常用的应用，使用的脚本同步更新和获取官方应用列表进行去重，建议应用商店可以增加第三方应用源配置，类似docker源配置功能

### 请描述你建议的实现方案

1、增加应用商店配置功能（官方源、第三方源/私有源）
2、建议配置支持第三方/私有源和优先级（github、gitee、gitlab、本地路径、smb/sftp），并校验内容格式是否正确（应用结构）
3、配置了第三方源/私有源后，会自动与应用商店和配置的优先级去重
可能在配置的时候得弄个声明，就像隐私协议一样勾一下

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，关于应用商店支持第三方源的需求，可以跟踪该 issue https://github.com/1Panel-dev/1Panel/issues/4935
