### ISSUE TITLE
[BUG]  【高级功能菜单隐藏】 新版本升级后,新功能子菜单在总菜单关闭状态下默认开启

### ISSUE THREAD

**Issue by gowy222** [1Panel-dev/1Panel#6429]
### 1Panel 版本

含有高级功能之后所有版本

### 问题描述

当【总菜单】处于关闭状态时,升级到包含新功能的版本后,这些新功能对应的【子菜单】会自动开启,这与预期的行为不符。
新功能的【子菜单】自动开启,不受【总菜单】关闭状态的影响

建议修复:
在版本升级过程中,检查【总菜单】的状态。
如果【总菜单】处于关闭状态,确保所有新功能的【子菜单】也保持关闭状态。
实现一个统一的菜单状态管理机制,确保【子菜单】始终遵循【总菜单】的状态。

### 重现步骤

确保当前老版本的【总菜单】处于关闭状态
升级到包含新功能的最新版本
检查新功能的【子菜单】状态

### 期待的正确结果

新功能的【子菜单】应该遵循【总菜单】的状态,保持关闭

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化上述功能。

**Comment by wanghe-fit2cloud** [comment]
后续版本会在新增高级子菜单时来判断菜单状态。
