### ISSUE TITLE
[FEATURE]计划任务——执行周期，希望可以支持cron表达式

### ISSUE THREAD

**Issue by pooneyy** [1Panel-dev/1Panel#6430]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/634f5508-d10a-49da-b441-0296f99d9f00)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，计划任务 Cron 表达式相关的需求，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/3796
