### ISSUE TITLE
[FEATURE]【应用商店】推荐应用CompreFace，免费、开源的人脸识别系统

### ISSUE THREAD

**Issue by 7FreezingPoint** [1Panel-dev/1Panel#6436]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

该项目提供了用于人脸识别、检测、验证、头部姿势检测、性别和年龄识别的 REST API 服务，不用懂机器学习就能轻松集成到任何系统中。它后端采用 Java 编写，人脸识别是基于 FaceNet 和 InsightFace 实现，同时支持 Docker 部署。
开源地址：https://github.com/exadel-inc/CompreFace
官网：https://exadel.com/accelerator-showcase/compreface/

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，我们主要以项目的 Star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有超1万 Star 的开源项目，感谢您的理解。

> 你可以将需求反馈给 [第三方仓库（由社区用户维护）](https://github.com/okxlin/appstore)。
