### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by zyk121381** [1Panel-dev/1Panel#6438]
### 1Panel 版本

 v1.10.14-lts

### 请描述您的需求或者改进建议

【应用商店】希望应用商店可以新增Casdoor。

### 请描述你建议的实现方案

Casdoor是一个基于OAuth 2.0、OIDC、SAML 和 CAS 的，UI-first的[身份和访问管理(IAM)](https://en.wikipedia.org/wiki/Identity_management)/[单点登录(SSO)](https://en.wikipedia.org/wiki/Single_sign-on)平台。在数字身份管理至关重要的时代，像Casdoor这样的单点登录（SSO）解决方案正在改变用户与多个应用程序的交互方式。 Casdoor的SSO通过允许用户只需进行一次认证就可以访问多个服务，简化了登录过程。 这不仅增强了用户便利性，还提高了参与度和满意度。

对于企业来说，Casdoor的SSO简化了用户凭证管理，增强了安全性，简化了新用户的入职流程。 它通过集中用户管理，抵消了与弱密码或重复使用密码相关的风险。

[官网地址](https://casdoor.org/zh/)

**Comment by wanghe-fit2cloud** [comment]
参考 https://github.com/1Panel-dev/1Panel/issues/2013
