### ISSUE TITLE
[BUG]设置移动端界面

### ISSUE THREAD

**Issue by see-more** [1Panel-dev/1Panel#6442]
### 1Panel 版本

latest

### 问题描述

移动端设置界面

### 重现步骤

![setting-unchange](https://github.com/user-attachments/assets/32fe0306-7524-422b-b9bc-14da3b92d12d)
![secure](https://github.com/user-attachments/assets/97e1d3ca-83e1-48ec-aaed-37a20fd71b01)

### 期待的正确结果

![setting](https://github.com/user-attachments/assets/99f95204-8ac2-45f2-a2fa-4d2884ed53ad)
![securestate](https://github.com/user-attachments/assets/02c78f1a-68b2-4ce1-b216-aaf5ad10e2bf)

**Comment by wanghe-fit2cloud** [comment]
感谢支持 👍

**Comment by wanghe-fit2cloud** [comment]
v1.10.15-lts 版本已发布。
