### ISSUE TITLE
[BUG] 检查授权太频繁了

### ISSUE THREAD

**Issue by qwenode** [1Panel-dev/1Panel#6453]
### 1Panel 版本

v1.10.14-lts

### 问题描述

![image](https://github.com/user-attachments/assets/916317af-e3c8-4b84-be38-088a7d012373)

### 重现步骤

日志

**Comment by wanghe-fit2cloud** [comment]
该问题已经修复，可以在面板设置中开启 【预览体验计划】，然后升级到 v1.10.15-beta.1 版本。
https://github.com/1Panel-dev/1Panel/issues/6349
