### ISSUE TITLE
在iPad设备上文件打不开

### ISSUE THREAD

**Issue by ZeroAry** [1Panel-dev/1Panel#6454]
### 联系方式

526666505@qq.com

### 1Panel 版本

1.10.15-beta.1

### 问题描述

在 ipad 设备上文件打不开，手机和电脑可以正常访问，手动输入files路径显示404

### 重现步骤

在iPad设备上点击文件

**Comment by see-more** [comment]
文件路径为`/hosts/files`而不是`/files`
![image](https://github.com/user-attachments/assets/3a70590f-c668-49fc-bd1e-5c2efe54cd42)

**Comment by ZeroAry** [comment]
> 文件路径为`/hosts/files`而不是`/files`
> ![图像](https://private-user-images.githubusercontent.com/107225647/366382260-3a70590f-c668-49fc-bd1e-5c2efe54cd42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDYyNDcsIm5iZiI6MTcyNjA0NTk0NywicGF0aCI6Ii8xMDcyMjU2NDcvMzY2MzgyMjYwLTNhNzA1OTBmLWM2NjgtNDlmYy1iZDFlLTVjMmVmZTU0Y2Q0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQwOTEyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTU1MWY5MTgxYzJiNTQ1NWUwMTlmYmFkYjQwMmU3MDA3YjM2ZGNiOWYzYjU3MGY4ZDk2ZjFjZWIxNGU5OGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FG-_991Jpq3l9_8Zxm50KRutRO0UwkruuDPXobAqlT8)

输入的就是hosts/files，问题只在iPad设备上，其他设备正常

**Comment by wanghe-fit2cloud** [comment]
刚刚在 iPad 上测试，未能复现上述问题；在 mac 的 Chrome 浏览器中模拟 iPad 也同样未复现问题。
