### ISSUE TITLE
[BUG] 1panel内置的运行环境，启动，报错。服务内部错误: 启动失败。并且无错误日志。

### ISSUE THREAD

**Issue by swordman20** [1Panel-dev/1Panel#6459]
### 1Panel 版本

v1.10.15-beta. 1

### 问题描述

1panel内置的运行环境，启动，报错。服务内部错误: 启动失败。并且无错误日志。
<img width="1635" alt="Snipaste_2024-09-11_19-24-07" src="https://github.com/user-attachments/assets/c3c70e69-fc1d-4b7c-8ff8-02eac2c4f14d">

<img width="1095" alt="Snipaste_2024-09-11_19-24-26" src="https://github.com/user-attachments/assets/a32ac5f5-08ca-451a-bd8b-f1f0c7356cac">

### 重现步骤

运行环境，除了Node.js，报错。服务内部错误: 启动失败。Java环境也是报错，服务内部错误: 启动失败。
这个问题，不仅在v1.10.15-beta. 1版本，之前版本上也是这样。我始终无法使用运行环境的应用。我一路升级1panel，都没有找到解决办法。

### 期待的正确结果

能够正常使用运行环境使用指令。

**Comment by wanghe-fit2cloud** [comment]
重复问题 https://github.com/1Panel-dev/1Panel/discussions/6391

**Comment by swordman20** [comment]
这个问题根本没有找到解决方法，为什么不这个问题关闭了。#6391也没人回复解决方法。
