### ISSUE TITLE
[QUESTION]创建证书失败

### ISSUE THREAD

**Issue by nexus181** [1Panel-dev/1Panel#646]
### 请描述您的问题

创建证书时显示：服务内部错误：error:one or more domains had a problem:[1p.auroracloud.top]
[1p.auroracloud.top]acme:error presenting token:API call failed:could not get domains:表为空

dns账户和acme账户都申请了

**Comment by nexus181** [comment]
访问phpmyadmin也加载失败

**Comment by wanghe-fit2cloud** [comment]
> ### 请描述您的问题
> 创建证书时显示：服务内部错误：error:one or more domains had a problem:[1p.auroracloud.top] [1p.auroracloud.top]acme:error presenting token:API call failed:could not get domains:表为空
> 
> dns账户和acme账户都申请了

感谢反馈，麻烦提供一下创建 dns 账户时使用的是哪家提供商，我们在开发环境复现一下该问题。
<img width="610" alt="image" src="https://user-images.githubusercontent.com/46734380/232010650-be6f4c84-6f81-476a-912a-dd53837d0214.png">

**Comment by wanghe-fit2cloud** [comment]
> 访问phpmyadmin也加载失败

1、容器列表确认一下该容器的运行状态
2、系统防火墙是否开启（端口是否放开）

**Comment by nexus181** [comment]
> 

容器已运行，端口也开放了

**Comment by nexus181** [comment]
> > ### 请描述您的问题
> > 创建证书时显示：服务内部错误：error:one or more domains had a problem:[1p.auroracloud.top] [1p.auroracloud.top]acme:error presenting token:API call failed:could not get domains:表为空
> > dns账户和acme账户都申请了
> 
> 感谢反馈，麻烦提供一下创建 dns 账户时使用的是哪家提供商，我们在开发环境复现一下该问题。 <img alt="image" width="610" src="https://user-images.githubusercontent.com/46734380/232010650-be6f4c84-6f81-476a-912a-dd53837d0214.png">

**Comment by nexus181** [comment]
![image](https://tu.lefu.men/file/8e443f0e09a1c40b62299.png)

**Comment by nexus181** [comment]
> 本地访问没有问题的话，那大概率还是服务器所处网络环境的问题。

行吧，我又打不开面板了~~
