### ISSUE TITLE
还没使用, 想问一下, 是否支持安装多版本的MySQL, 开发环境会安装多个版本的MySQL, 没办法的刚需

### ISSUE THREAD

**Issue by xiaokentrl** [1Panel-dev/1Panel#6464]
### 1Panel 版本

1 & 2

### 请描述您的需求或者改进建议

还没使用, 想问一下, 是否支持安装多版本的MySQL, 开发环境会安装多个版本的MySQL, 没办法的刚需

### 请描述你建议的实现方案

支持安装多版本的MySQL, MySQL5.6  &  MySQL5.7  &  MySQL8.0

**Comment by wanghe-fit2cloud** [comment]
1Panel 是采用容器化方案部署的 MySQL 应用，支持安装多个。

**Comment by wanghe-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/e3ce8427-36d6-49e6-87f9-f0a3069801f1)
