### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by iygwei** [1Panel-dev/1Panel#6466]
### 联系方式

iygwei@qq.com

### 1Panel 版本

v1.10.14-lts

### 问题描述

Key: 'MysqlVariablesUpdate.Type' Error:Field validation for 'Type' failed on the 'required' tag Key: 'MysqlVariablesUpdate.Database' Error:Field validation for 'Database' failed on the 'required' tag 
![image](https://github.com/user-attachments/assets/912ed2aa-860a-41c5-a868-b86d9912399b)
开启sql慢日志的时候报错

### 重现步骤

再sql卡其慢日志的时候报错的

**Comment by ssongliu** [comment]
感谢反馈，在 1.10.14-lts 版本上暂时未复现该问题，可以加我提供一下远程环境，我看看
![image](https://github.com/user-attachments/assets/f780ade6-ca83-4783-805a-e33e63d31a93)
