### ISSUE TITLE
[FEATURE] 磁盘清理功能

### ISSUE THREAD

**Issue by li7355608** [1Panel-dev/1Panel#6483]
### 1Panel 版本

v1.10.15-lts

### 请描述您的需求或者改进建议

能否增增添磁盘分析功能分析磁盘占用，目前自带的缓存清理功能对于清理存储空间而言有些力不从心

### 请描述你建议的实现方案

类似wintree这种树状图分析软件，能迅速分析文件夹占用状态识别出那些占用空间巨大

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
磁盘相关需求的讨论，统一汇总到该 issue #1852
