### ISSUE TITLE
[FEATURE] 希望应用商店能够增加 NocoBase 开源、私有部署的轻量级无代码和低代码开发平台

### ISSUE THREAD

**Issue by allyn0303** [1Panel-dev/1Panel#6484]
### 1Panel 版本

v1.10.15-lts

### 请描述您的需求或者改进建议

希望应用商店能够增加 NocoBase 开源、私有部署的轻量级无代码和低代码开发平台
https://github.com/nocobase/nocobase
https://github.com/nocobase/nocobase/blob/main/README.zh-CN.md
https://www.nocobase.com/cn/

### 请描述你建议的实现方案

希望应用商店能够增加 NocoBase 开源、私有部署的轻量级无代码和低代码开发平台
https://github.com/nocobase/nocobase
https://github.com/nocobase/nocobase/blob/main/README.zh-CN.md
https://www.nocobase.com/cn/

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，重复需求 https://github.com/1Panel-dev/1Panel/issues/4879
