### ISSUE TITLE
[FEATURE] phpMyAdmin非root账户最好是隐藏 information_schema

### ISSUE THREAD

**Issue by hhun** [1Panel-dev/1Panel#649]
### 1Panel 版本

1.1

### 请描述您的需求或者改进建议

phpMyAdmin非root账户最好是隐藏 information_schema

### 隐藏方法：
复制根目录下的`config.sample.inc.php`为`config.inc.php`
修改`config.inc.php`在第33行，添加一行内容
``` php
$cfg['Servers'][$i]['hide_db'] = 'information_schema|performance_schema';
```
有多个库，就用管道符号 `|` 隔开

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后面版本优化。

**Comment by hhun** [comment]
@wanghe-fit2cloud 

**我找到隐藏方法了**

建议用此方法 https://github.com/1Panel-dev/appstore/pull/766
或者用下面的方法

分布式版本的phpMyAdmin不是修改 `/libraries/config.inc.php` 而是需要修改 `/etc/phpmyadmin/config.inc.php`

**修改方法：**
在 `/etc/phpmyadmin/config.inc.php` 第80行 $cfg['Servers'][$i]['host'] = $hosts[$i -1];
**前面**增加 $cfg['Servers'][$i]['hide_db'] = 'information_schema|performance_schema';

![information_schema](https://github.com/1Panel-dev/1Panel/assets/19625243/87f4b16b-b1eb-445b-bf1b-4d03d60ce96a)

**Comment by wanghe-fit2cloud** [comment]
> 我找到隐藏方法了

感谢，我先在本地环境验证一下上述方案。

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
