### ISSUE TITLE
[BUG]Nginx反代的文本替换，缺少一个配置项，导致某些响应类型不会进行替换

### ISSUE THREAD

**Issue by miaowmint** [1Panel-dev/1Panel#6490]
### 1Panel 版本

1.14

### 问题描述

缺少`sub_filter_types *;`配置项 导致 比如RSS订阅的xml响应类型不会进行替换

### 重现步骤

1

**Comment by zhengkunwang223** [comment]
感谢反馈，后续版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.10.19-lts 版本已发布。
