### ISSUE TITLE
[BUG]docker容器日志过长会导致页面卡顿/无响应

### ISSUE THREAD

**Issue by Rovniced** [1Panel-dev/1Panel#6492]
### 1Panel 版本

v1.10.15-lts

### 问题描述

在面板 容器-日志 这个功能中，如果容器打印的日志过长，会导致网页卡顿或者无响应。
日志大概只有40行左右，因为打印了请求和响应信息，每一行的字符大约有5k-1w个。

或许可以考虑自动换行或者日志过长就省略掉一部分？

### 重现步骤

点击面板-容器-日志，出现卡顿。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by ssongliu** [comment]
同 #6642

**Comment by jackiezzq** [comment]
最新版本还存在
