### ISSUE TITLE
[FEATURE] 支持 openrety的日志轮转

### ISSUE THREAD

**Issue by ihipop** [1Panel-dev/1Panel#6494]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

目前的Openrety的网站日志统一写一个目录单个文件无轮转,网站访问量大的话,没几天就会被塞满

### 请描述你建议的实现方案

期望能在openesty镜像里面增加 [logrotate](https://linux.die.net/man/8/logrotate) 自动压缩和保留 N天的日志 

### 附加信息

![image](https://github.com/user-attachments/assets/57a78f06-073c-4db9-b6f9-eb4f6b2db32e)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述需求可以通过创建 `切割网站日志` 类型计划任务实现，如图：
![image](https://github.com/user-attachments/assets/a25fe282-93fb-4403-a9f5-ebddb566d3e6)
