### ISSUE TITLE
[BUG]新建网站和反向代理访问失败

### ISSUE THREAD

**Issue by nexus181** [1Panel-dev/1Panel#650]
### 1Panel 版本

1.1

### 问题描述

新建的网站访问时没有出现默认界面，反向代理没有出现网页，地址栏显示的它们协议是https而非http，我并没有使用证书和开启https
![](https://telegraph-image.pages.dev/file/4d6bc558033e9acefd0a1.png)

### 重现步骤

新建php网站或反向代理，访问网页

**Comment by zhengkunwang223** [comment]
如果访问域名自动跳转到https，可能是浏览器的缓存，尝试用无痕模式打开看看

**Comment by nexus181** [comment]
> 如果访问域名自动跳转到https，可能是浏览器的缓存，尝试用无痕模式打开看看

解决了，再请教一下，之前我部署的网站目录是/home/www/wwwroot/xxx，且www及之后的用户都是www，现在网站的目录必须在/opt/1panel/apps/openresty/OR/www/sites/xxx/index下，该怎么修改用户呢？

**Comment by wanghe-fit2cloud** [comment]
后续版本中，文件列表会支持设置文件夹用户。
当前版本先通过命令来设置文件夹用户：chown -R 1000:1000 index

**Comment by nexus181** [comment]
> chown -R 1000:1000 index

访问域名还是显示Access denied.。我之前创建过一个用户为abc，现在设置index用户和组为1000后，显示都是abc

**Comment by cyril-cheng** [comment]
> > chown -R 1000:1000 index
> 
> 访问域名还是显示Access denied.。我之前创建过一个用户为abc，现在设置index用户和组为1000后，显示都是abc

在容器里执行。。。
