### ISSUE TITLE
[BUG]编辑器编辑XML文件会导致文件编码变更

### ISSUE THREAD

**Issue by TuringTrail** [1Panel-dev/1Panel#6500]
### 联系方式

微信交流1群；Turng

### 1Panel 版本

v1.10.15-lts

### 问题描述

编辑器编辑XML文件会导致文件编码强制变更为UTF-8 行尾符选择无效

### 重现步骤

[Test.zip](https://github.com/user-attachments/files/17001509/Test.zip)
测试文件一个;这个文件为ANSI编码 只要再编译器里面更改保存就会强制保存为UTF-8

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们将在后续版本中优化文件编码功能。

**Comment by wanghe-fit2cloud** [comment]
文件编码相关问题的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/5697
