### ISSUE TITLE
[BUG] 有时候页面切换会报错、无法跳转到某个页面

### ISSUE THREAD

**Issue by zhengjianyang** [1Panel-dev/1Panel#6502]
### 1Panel 版本

v1.10.15-lts

### 问题描述

<img width="1490" alt="image" src="https://github.com/user-attachments/assets/741035c1-9924-4479-b77d-d09dbb11291f">
我点 文件 按钮、就会出现下面的错误
TypeError: Importing a module script failed.
不会跳转页面

### 重现步骤

不知道怎么出现的、放一会或许就出现了
用的 safari 浏览器

### 期待的正确结果

正常跳转页面

### 附加信息

如果删除掉缓存再重新登录就正常了

**Comment by ssongliu** [comment]
感谢反馈，safari 浏览器已本地复现该问题，下个小版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.16 版本已发布。
