### ISSUE TITLE
[BUG] 频繁重命名文件可能会导致文件被另一个文件覆盖

### ISSUE THREAD

**Issue by ArsiIksait** [1Panel-dev/1Panel#6505]
### 1Panel 版本

v1.10.14-lts

### 问题描述

我在使用1Panel的文件管理器重命名图片的时候，发现有时候重命名会被覆盖成另一个文件，好像是缓存的原因？把这个文件的名字改回去又显示原来的图片了
![image](https://github.com/user-attachments/assets/dec4c69d-6980-4d00-9750-2c59f87c7eb1)
![image](https://github.com/user-attachments/assets/7fa7f967-5e85-4cd3-aa9e-544474ebb596)
![image](https://github.com/user-attachments/assets/43918ddf-7473-4cd4-9012-7ac17ae32a18)
![image](https://github.com/user-attachments/assets/717da356-6d01-449c-8f5b-2ee7e1f89609)
![image](https://github.com/user-attachments/assets/69b40a48-2df4-421f-90ed-f82132258a99)
![image](https://github.com/user-attachments/assets/5f4b0937-7bb8-49c1-b43f-0b6ef4852023)
![image](https://github.com/user-attachments/assets/fb76ff8b-fec8-42f5-95c7-75eaad9ab3d8)
![image](https://github.com/user-attachments/assets/f591bae8-4657-493b-af99-99c61ebece09)
![image](https://github.com/user-attachments/assets/2949b372-ecb0-4409-976e-3fed4d7fe3f1)

### 重现步骤

![image](https://github.com/user-attachments/assets/dec4c69d-6980-4d00-9750-2c59f87c7eb1)
![image](https://github.com/user-attachments/assets/7fa7f967-5e85-4cd3-aa9e-544474ebb596)
![image](https://github.com/user-attachments/assets/43918ddf-7473-4cd4-9012-7ac17ae32a18)
![image](https://github.com/user-attachments/assets/717da356-6d01-449c-8f5b-2ee7e1f89609)
![image](https://github.com/user-attachments/assets/69b40a48-2df4-421f-90ed-f82132258a99)
![image](https://github.com/user-attachments/assets/5f4b0937-7bb8-49c1-b43f-0b6ef4852023)
![image](https://github.com/user-attachments/assets/fb76ff8b-fec8-42f5-95c7-75eaad9ab3d8)
![image](https://github.com/user-attachments/assets/f591bae8-4657-493b-af99-99c61ebece09)
![image](https://github.com/user-attachments/assets/2949b372-ecb0-4409-976e-3fed4d7fe3f1)

### 期待的正确结果

感觉这个bug和[issues#6502](https://github.com/1Panel-dev/1Panel/issues/6502)有点像，不知道有没有被修复

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，刚在本地环境复现了该问题，我们将在近期版本中进行修复。

**Comment by wanghe-fit2cloud** [comment]
v1.10.16 版本已发布。
