### ISSUE TITLE
在面板里安装halo之后进不去halo后台

### ISSUE THREAD

**Issue by IshuaWang** [1Panel-dev/1Panel#6509]
### 联系方式

佚名

### 1Panel 版本

v1.10.15-lts

### 问题描述

设置halo的端口，然后访问localhost:8080,出现下面的错误
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

### 重现步骤

就是再腾讯云上添加1panel的镜像，然后依次安装openresty， mysql和halo 2.19.3，就出现了这种情况，搞了很久不知道为啥。

### 期待的正确结果

起码能进入halo的后台吧

**Comment by Anyexyz** [comment]
[1Panel 安装 Halo——视频教程](https://search.bilibili.com/all?keyword=1panel%E5%AE%89%E8%A3%85halo)
[1Panel 安装 Halo——文档教程](https://docs.halo.run/getting-started/install/1panel/)
