### ISSUE TITLE
[FEATURE] phpMyAdmin不能绑定域名，不能添加证书，管理起来相当于是在裸奔。

### ISSUE THREAD

**Issue by hhun** [1Panel-dev/1Panel#651]
### 1Panel 版本

1.1

### 请描述您的需求或者改进建议

phpMyAdmin不能绑定域名，不能添加证书，管理起来相当于是在裸奔。
面板也不能绑定域名，不能添加证书。

最好是能添加扫码登录，现在谷歌都在推无密码登录，输入密码管理总感觉不安全。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1、是要实现数据库列表中点击 phpmyadmin 时，支持设置域名和证书然后访问吗？
2、面板 ssl 会在 v1.2.0 版本支持。

**Comment by kuwo2016** [comment]
面板，我二次登录验证，用的是Authenticator 进行认证的，面板ssl问题，我是用，网站功能中的，反向代理来，然后搭配ssl证书，也可以实现面板绑定ssl证书的需求，但是，如果面板本身支持绑定ssl证书，就更方便一些。

**Comment by wanghe-fit2cloud** [comment]
> phpMyAdmin不能绑定域名，不能添加证书，管理起来相当于是在裸奔。

建议在网站设置中创建反向代理网站。

`无密码登录` 这个需求我们暂无计划支持，望理解。
