### ISSUE TITLE
[FEATURE] 社区版的WAF

### ISSUE THREAD

**Issue by wanyunr** [1Panel-dev/1Panel#6511]
### 1Panel 版本

v1.10.15-lts

### 请描述您的需求或者改进建议

1pwaf 没有日志，还是默认开启，网站莫名其妙报错 `ERR_HTTP2_PROTOCOL_ERROR` ，排查很久，才发现被waf拦截了,很闹心

### 请描述你建议的实现方案

有简单日志，或者直接写入到单独txt文件（非db中），不在面板显示也行

**Comment by wanyunr** [comment]
而且不给日志，都不知道是触发了哪条规则

**Comment by zhengkunwang223** [comment]
您好 我检查了一下配置 
<img width="710" alt="image" src="https://github.com/user-attachments/assets/9545d62d-c14e-447f-87ee-1fd3455fc299">
默认是关闭的 您是新装的 还是旧版本升级上来的

**Comment by wanyunr** [comment]
> 您好 我检查了一下配置 <img alt="image" width="710" src="https://private-user-images.githubusercontent.com/31820853/367579666-9545d62d-c14e-447f-87ee-1fd3455fc299.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDE4NjgsIm5iZiI6MTcyNjQwMTU2OCwicGF0aCI6Ii8zMTgyMDg1My8zNjc1Nzk2NjYtOTU0NWQ2MmQtYzE0ZS00NDdmLTg3ZWUtMWZkMzQ1NWZjMjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDExNTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZTIxZjRmZjVhMDYxOGExZDdiY2E0Y2E2YjgxOWM4MjRkZDI4OTQ0MTJlMzgzNWFjMmU4OGM5NjJhMjE3MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PPNMuNKNBVmxQEQoiwJs2f78vwQU5VcfdOtSQPz6GSc"> 默认是关闭的 您是新装的 还是旧版本升级上来的

升级上来的，主要是不知道为什么被拦截了

**Comment by zhengkunwang223** [comment]
> > 您好 我检查了一下配置 <img alt="image" width="710" src="https://private-user-images.githubusercontent.com/31820853/367579666-9545d62d-c14e-447f-87ee-1fd3455fc299.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MDE4NjgsIm5iZiI6MTcyNjQwMTU2OCwicGF0aCI6Ii8zMTgyMDg1My8zNjc1Nzk2NjYtOTU0NWQ2MmQtYzE0ZS00NDdmLTg3ZWUtMWZkMzQ1NWZjMjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDExNTkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZTIxZjRmZjVhMDYxOGExZDdiY2E0Y2E2YjgxOWM4MjRkZDI4OTQ0MTJlMzgzNWFjMmU4OGM5NjJhMjE3MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PPNMuNKNBVmxQEQoiwJs2f78vwQU5VcfdOtSQPz6GSc"> 默认是关闭的 您是新装的 还是旧版本升级上来的
> 
> 升级上来的，主要是不知道为什么被拦截了

比较旧的版本是默认开启的 一般被拦截都会有提示 除了触发 CC 是直接被拉黑的
