### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by astonisingHSR** [1Panel-dev/1Panel#6512]
### 1Panel 版本

v1.10.13-lts

### 请描述您的需求或者改进建议

应用商店可以添加“overleaf服务器搭建”应用吗？

### 请描述你建议的实现方案

官方的overleaf服务器搭建也是通过docker-compose实现，是否可以迁移过来

### 附加信息

overleaf toolkit的项目地址：https://github.com/overleaf/toolkit

**Comment by wanghe-fit2cloud** [comment]
重复需求 https://github.com/1Panel-dev/1Panel/issues/5972
