### ISSUE TITLE
[FEATURE]docker容器内文件管理

### ISSUE THREAD

**Issue by haibiao-gu** [1Panel-dev/1Panel#6521]
### 1Panel 版本

v1.10.15-lts

### 请描述您的需求或者改进建议

docker容器内如果需要对某个文件查看，比如说历史日志，需要通过命令进入，拷贝等，非常麻烦，建议学习一下隔壁宝塔，可以直接在界面上对docker内文件进行操作

**Comment by wanghe-fit2cloud** [comment]
容器文件管理相关系统，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/523
