### ISSUE TITLE
[BUG]1panel在ubuntu server系统下,无法停止ssh服务

### ISSUE THREAD

**Issue by Mask-Vip** [1Panel-dev/1Panel#6524]
### 1Panel 版本

社区版 v1.10.15-lts

### 问题描述

新装的ubuntu server的esxi虚拟机,全新安装的1panel.还是遇到了之前老版本的问题,就是ssh服务不受面板的控制.

在面板内停止ssh后,显示的是已关闭.可是用其他的机器或是面板自带的终端,仍然能连接上ssh

### 重现步骤

在面板内停止ssh后,显示的是已关闭.可是用其他的机器或是面板自带的终端,仍然能连接上ssh

### 附加信息

sudo systemctl stop ssh.service

在手动停止ssh服务的时候报错:
Stopping ‘ssh.service’, but its triggering units are still active:ssh.socket

然后执行:
sudo systemctl disable ssh.socket
sudo systemctl stop ssh.sock

之后ssh终于是被关闭了,并且1panel也可以控制打开关闭ssh服务了.又恢复到受控状态了.

**Comment by wanghe-fit2cloud** [comment]
请提供一下 Ubuntu 的操作系统版本和内核版本，我们将在本地环境中复现该问题。

**Comment by Mask-Vip** [comment]
> 请提供一下 Ubuntu 的操作系统版本和内核版本，我们将在本地环境中复现该问题。

<html>
<body>

发行版本 ubuntu serve 24.04
--
内核版本 6.8.0-45-generic
系统类型 x86_64

这个问题在之前的版本上也曾经发生过.

</body>
</html>

**Comment by ssongliu** [comment]
这里和 docker.socket 一样，包括两个服务 .socket 和 .service

当需要停止服务时，直接停 .service ，服务会被 .socket 重新拉起，应该直接停 .socket

下个版本解决该问题

**Comment by wanghe-fit2cloud** [comment]
v1.10.16 版本已发布。
