### ISSUE TITLE
[FEATURE] k8s 安装

### ISSUE THREAD

**Issue by Jengro777** [1Panel-dev/1Panel#6526]
### 1Panel 版本

1.10.15

### 请描述您的需求或者改进建议

我不是很懂 k8s 哈，所以想了解下是否可以通过可视化的方案进行 k8s 集群部署

**Comment by wanghe-fit2cloud** [comment]
1Panel 团队自研 K8s 管理面板：https://github.com/1Panel-dev/KubePi
目前已经上架到 1Panel 应用商店中，如图：
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/4cf1c000-1382-4bc9-82f8-37fef4f4931d">

> 不支持可视化部署 K8s 集群。
