### ISSUE TITLE
[FEATURE]希望增加Docsify

### ISSUE THREAD

**Issue by dididaguai** [1Panel-dev/1Panel#6527]
### 1Panel 版本

v1.10.15-lts

### 请描述您的需求或者改进建议

https://github.com/docsifyjs/docsify/

### 请描述你建议的实现方案

https://github.com/docsifyjs/docsify/

**Comment by wanghe-fit2cloud** [comment]
由于 Docsify 官方未提供 Docker 镜像且需自行构建，因此暂无法上架到应用商店中。
官方容器化部署教程：https://docsify.js.org/#/deploy?id=docker
