### ISSUE TITLE
[FEATURE]希望增加雷池WAF

### ISSUE THREAD

**Issue by dididaguai** [1Panel-dev/1Panel#6528]
### 1Panel 版本

v1.10.15-lts

### 请描述您的需求或者改进建议

https://github.com/chaitin/SafeLine

### 请描述你建议的实现方案

https://github.com/chaitin/SafeLine

**Comment by wanghe-fit2cloud** [comment]
第三方应用商店已支持 https://github.com/okxlin/appstore/tree/localApps/apps/safeline

**Comment by dididaguai** [comment]
不能官方支持吗
