### ISSUE TITLE
[FEATURE]希望应用商店增加排序

### ISSUE THREAD

**Issue by dididaguai** [1Panel-dev/1Panel#6529]
### 1Panel 版本

v1.10.15-lts

### 请描述您的需求或者改进建议

希望应用商店增加例如时间之类的排序（想看最新添加的应用是什么）

### 请描述你建议的实现方案

希望应用商店增加例如时间之类的排序（想看最新添加的应用是什么）

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们将在后续版本中考虑增加按上架时间、名称等条件排序的功能。

**Comment by wanghe-fit2cloud** [comment]
重复需求 https://github.com/1Panel-dev/1Panel/issues/5127
