### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by han201379873** [1Panel-dev/1Panel#653]
### 联系方式

201379873@qq.com

### 1Panel 版本

1.1.0

### 问题描述

docker创建容器的端口映射有问题

### 重现步骤

下载的容器，创建后，新建容器，设置存储位置，设置端口映射，启动会发现端口其实没有被映射出来，可以在docker ps -a查看到自己启动的容器端口映射是空的，需要参考[教程](https://blog.csdn.net/guorui_java/article/details/115187780)修改容器，才能正常映射

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我这里不是很清楚你要表达的意思，不过我刚才在开发环境创建了 kubepi 容器，对外暴露的端口为 8080，看起来是正常的。
![image](https://user-images.githubusercontent.com/46734380/232087690-0843eb17-a08a-4208-abeb-286fb5eae869.png)
![image](https://user-images.githubusercontent.com/46734380/232087728-236a397d-ce2d-43f5-8e33-be8b12897ab2.png)

**Comment by han201379873** [comment]
![1681553655602](https://user-images.githubusercontent.com/52527278/232207838-3455d4f0-688e-496d-9f69-fbafe64a5f0c.png)
![1681553599871](https://user-images.githubusercontent.com/52527278/232207842-bbbf2c68-9bdd-491f-a235-f8f279c416d9.jpg)
这是我现在的情况，我使用的是腾讯轻量服务器，debian系统，我这个终端页面是直接连接服务器的ssh

**Comment by wanghe-fit2cloud** [comment]
你提供的这 python 镜像有暴露（EXPOSE） 8003 端口吗？

**Comment by han201379873** [comment]
我直接拉取的官方镜像，没有处理过暴露端口的事，只在创建的时候选择了暴露8003端口，下面那个python3.9能正常暴露8000是我前面提到的修改文件后才暴露出来，我昨晚查看是config.v2.json文件下，没有ExposedProts，后面加了这个参数和值，才能正常暴露8000端口

**Comment by wanghe-fit2cloud** [comment]
你要确保镜像在构建时已经 expose 暴露了端口，之后在创建容器时再对外暴露容器内端口。
