### ISSUE TITLE
[FEATURE] 给应用商店的应用添加反向代理支持

### ISSUE THREAD

**Issue by Dr-TSNG** [1Panel-dev/1Panel#6530]
### 1Panel 版本

v1.10.15-lts

### 请描述您的需求或者改进建议

目前很多应用商店里的应用（比如 sftpgo，nextcloud 等）对反向代理的支持很差，在 openresty 里添加到对应 web 端口的反代绝大部分都打不开。

### 请描述你建议的实现方案

为应用商店里的应用提供 web 端口开箱即用的反代支持。

**Comment by wanghe-fit2cloud** [comment]
后续版本会支持创建网站时直接选择应用或者容器 https://github.com/1Panel-dev/1Panel/issues/2930
