### ISSUE TITLE
[FEATURE] 商店上架  rancher 

### ISSUE THREAD

**Issue by Jengro777** [1Panel-dev/1Panel#6531]
### 1Panel 版本

1.10.15

### 请描述您的需求或者改进建议

https://github.com/rancher/rancher

**Comment by wanghe-fit2cloud** [comment]
- Rancher 官方文档：https://ranchermanager.docs.rancher.com/v2.8/getting-started/quick-start-guides/deploy-rancher-manager
- quickstart 项目：https://github.com/rancher/quickstart

经过评估，Rancher 项目不建议上架到 1Panel 应用商店。
![image](https://github.com/user-attachments/assets/76534b95-25d1-48b2-a1af-47a2c598900f)

**Comment by Jengro777** [comment]
> - Rancher 官方文档：https://ranchermanager.docs.rancher.com/v2.8/getting-started/quick-start-guides/deploy-rancher-manager
> 
> - quickstart 项目：https://github.com/rancher/quickstart
> 
> 
> 
> 经过评估，Rancher 项目不建议上架到 1Panel 应用商店。
> 
> ![image](https://github.com/user-attachments/assets/76534b95-25d1-48b2-a1af-47a2c598900f)
> 
> 

kubepi 不支持可视化安装k8s ，rancher 有不能上架应用商店！ 怎么都不行
