### ISSUE TITLE
[BUG]PHP安装OCI扩展无效

### ISSUE THREAD

**Issue by TuringTrail** [1Panel-dev/1Panel#6535]
### 联系方式

微信交流1群；Turng

### 1Panel 版本

v1.10.15-lts

### 问题描述

![image](https://github.com/user-attachments/assets/85e3caaf-289a-4efa-acbd-4572856930e5)
PHP7.4安装OCI扩展后不生效

### 重现步骤

PHP7.4安装OCI扩展后不生效

**Comment by zhengkunwang223** [comment]
感谢反馈 我们试一下

**Comment by zhengkunwang223** [comment]
已经复现 后续随应用商店更新修复

**Comment by wanghe-fit2cloud** [comment]
该问题已修复，请点击应用商店右上角的【更新应用列表】按钮，更新完成后重新安装 PHP 运行环境即可。

**Comment by TuringTrail** [comment]
> 该问题已修复，请点击应用商店右上角的【更新应用列表】按钮，更新完成后重新安装 PHP 运行环境即可。

经过测试，问题依旧，还是没解决。

**Comment by zhengkunwang223** [comment]
> > 该问题已修复，请点击应用商店右上角的【更新应用列表】按钮，更新完成后重新安装 PHP 运行环境即可。
> 
> 经过测试，问题依旧，还是没解决。

需要新建 PHP 运行环境

**Comment by TuringTrail** [comment]
> > > 该问题已修复，请点击应用商店右上角的【更新应用列表】按钮，更新完成后重新安装 PHP 运行环境即可。
> > 
> > 
> > 经过测试，问题依旧，还是没解决。
> 
> 需要新建 PHP 运行环境

还有问题;pdo_oci是可以了；但是oci8扩展还是无效
