### ISSUE TITLE
[FEATURE] 应用升级，可以保留挂载信息

### ISSUE THREAD

**Issue by 9a6c** [1Panel-dev/1Panel#6536]
### 1Panel 版本

1.10.15

### 请描述您的需求或者改进建议

alist升级后，挂载信息丢失。

### 请描述你建议的实现方案

手动添加的挂载信息，是否可以在升级后保留？

**Comment by zhengkunwang223** [comment]
升级时会替换 docker-compose.yml 文件  
可以勾选 自定义 docker-compose 文件来保存你的挂载信息
![image](https://github.com/user-attachments/assets/cc9be73d-63c5-4d86-9835-3d0ed83d3c5d)

**Comment by 9a6c** [comment]
我点击这个按钮的时候，它里面什么也没显示

**Comment by zhengkunwang223** [comment]
> 我点击这个按钮的时候，它里面什么也没显示

![image](https://github.com/user-attachments/assets/9f4254c8-08e2-43d9-9fec-e3f219fb8b7a)
点这个呢

**Comment by 9a6c** [comment]
查看对比，只有alist的版本那里是不一样的（拉取的镜像）。这个不是很重要，我手动添加以下也行

**Comment by mjsoftking** [comment]
> 查看对比，只有alist的版本那里是不一样的（拉取的镜像）。这个不是很重要，我手动添加以下也行

你修改配置，在应用商店已安装对应应用的compose文件中修改，这样下次对比的时候就有差异了，容器那边修改没啥用

**Comment by wanghe-fit2cloud** [comment]
> > 查看对比，只有alist的版本那里是不一样的（拉取的镜像）。这个不是很重要，我手动添加以下也行
> 
> 你修改配置，在应用商店已安装对应应用的compose文件中修改，这样下次对比的时候就有差异了，容器那边修改没啥用

<img width="1475" alt="image" src="https://github.com/user-attachments/assets/4403513a-0124-41e5-8746-6bce188dbbe2">

**Comment by mjsoftking** [comment]
> > > 查看对比，只有alist的版本那里是不一样的（拉取的镜像）。这个不是很重要，我手动添加以下也行
> > 
> > 
> > 你修改配置，在应用商店已安装对应应用的compose文件中修改，这样下次对比的时候就有差异了，容器那边修改没啥用
> 
> <img alt="image" width="1475" src="https://private-user-images.githubusercontent.com/46734380/369625888-4403513a-0124-41e5-8746-6bce188dbbe2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NTcxMDQsIm5iZiI6MTcyNjk1NjgwNCwicGF0aCI6Ii80NjczNDM4MC8zNjk2MjU4ODgtNDQwMzUxM2EtMDEyNC00MWU1LTg3NDYtNmJjZTE4OGRiYmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDIyMTMyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkZWRmNWU0Yjg2NjM0ZmQzYTVlMWZkY2JlZWNlNWJjODczNWM5ZmQ4N2YwMWE3NzVjZjZkYTExOTVmYTdlMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g7nbsbX9X1BPQtpHeUim8AuOCXVYjYDdXbjKA-jnDmk">

我的halo就是在应用中添加的redis相关配置，现在每次升级都可对比出来，我想说的是容器那边修改的下次再应用升级的时候是对比不出来的，应该是没有同步到配置文件中
![image](https://github.com/user-attachments/assets/364b8fdb-b109-42fd-afbc-c21a0d69ce17)
