### ISSUE TITLE
[BUG] 页脚显示

### ISSUE THREAD

**Issue by yfdoor** [1Panel-dev/1Panel#654]
### 1Panel 版本

1.1.0

### 问题描述

页脚 Copyright @2014-2023 FIT2CLOUND 飞致云，这个不应该写错吧，你们不是一个专业的公司在做吗？

Copyright © 2014-2023 FIT2CLOUND 飞致云

### 重现步骤

yes

**Comment by ssongliu** [comment]
感谢反馈！已修改
