### ISSUE TITLE
[BUG] 查看快照报错

### ISSUE THREAD

**Issue by cktk** [1Panel-dev/1Panel#6540]
### 1Panel 版本

v1.10.15-lts

### 问题描述

<img width="1808" alt="image" src="https://github.com/user-attachments/assets/2f903aea-30c1-4585-818c-a7027e0eb2b9">
<img width="1150" alt="image" src="https://github.com/user-attachments/assets/cd93069d-f1ca-460a-859a-661d407b4511">

### 重现步骤

快照点击查看 一直在加载 然后提示超时

**Comment by ssongliu** [comment]
感谢反馈，这里主要是获取快照文件大小比较消耗时间，下个版本改成异步请求

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
