### ISSUE TITLE
[BUG] /opt/1panel/apps/openresty/openresty/docker-compose.yml: no such file or directory

### ISSUE THREAD

**Issue by sinlov** [1Panel-dev/1Panel#6542]
### 1Panel 版本

v1.10.15-lts

### 问题描述

应用商店安装 `openresty` 失败，错误日志 根实际表现不一致

![image](https://github.com/user-attachments/assets/81092da7-ae8e-4e16-855e-b68e7221f830)

而显示文件其实是存在的

![image](https://github.com/user-attachments/assets/4824a4f1-9efd-49b4-b229-0fddec9803ea)

### 重现步骤

应用商店卸载后，再安装 openresty 仍然复现

安装 1Panel 脚本为 在 root 用户下执行

```bash
curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && bash quick_start.sh
```

`1pctl status` 反馈信息

```log
● 1panel.service - 1Panel, a modern open source linux panel
     Loaded: loaded (/etc/systemd/system/1panel.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2024-09-20 08:30:58 UTC; 1min 32s ago
   Main PID: 256501 (1panel)
      Tasks: 7 (limit: 525)
     Memory: 123.2M
        CPU: 2.573s
     CGroup: /system.slice/1panel.service
             └─256501 /usr/bin/1panel
```

系统信息

```bash
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Linux vultr 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
```

### 期待的正确结果

可以通过 1Panel 商店安装，或者管理容器

**Comment by sinlov** [comment]
补充一下， 通过 1Panel 应用商店安装都是一样错误， 通过 ssh 编排服务 1Panel 可以看到

![image](https://github.com/user-attachments/assets/b13ecb5f-ab7e-4d5d-b1d7-935c0cac1f96)

gcc 信息，在 安装 1Panel 前就有

```log
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.1-6' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Debian 10.2.1-6)
```

**Comment by sinlov** [comment]
确认 该版本 无法通过商店 管理容器，只能作为 观察面板，查看容器状态

**Comment by wanghe-fit2cloud** [comment]
进入 `主机` - `终端` 页面，执行 `docker-compose version` 命令查看当前 `docker-compose` 版本。
注意：`docker-compose` 需使用 v2 版本，下载地址：https://github.com/docker/compose/releases

**Comment by sinlov** [comment]
> 进入 `主机` - `终端` 页面，执行 `docker-compose version` 命令查看当前 `docker-compose` 版本。 注意：`docker-compose` 需使用 v2 版本，下载地址：https://github.com/docker/compose/releases

```bash
$ docker-compose version
Docker Compose version v2.17.3
```

**Comment by wanghe-fit2cloud** [comment]
是使用 snap 安装的 docker 吗？
docker 版本是多少？

**Comment by sinlov** [comment]
@wanghe-fit2cloud 

fix by install docker-compose

```bash
$ docker-compose version
Docker Compose version v2.29.7
```
can close this 🐛, thx

**Comment by sinlov** [comment]
> 是使用 snap 安装的 docker 吗？ docker 版本是多少？

install from `https://github.com/docker/compose/releases` by script

use latest version 2.29.7

**Comment by G1ume** [comment]
版本v1.10.29-lts 复现该issue
docker-compose version: v2.32.4
文件实际存在，抛出no such file or directory错误

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Version v1.10.29-lts reproduces this issue
docker-compose version: v2.32.4
The file actually exists, throwing no such file or directory error

**Comment by zhengkunwang223** [comment]
> 版本v1.10.29-lts 复现该issue
> docker-compose version: v2.32.4
> 文件实际存在，抛出no such file or directory错误

提供一下 docker-compose version 的执行截图

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Version v1.10.29-lts reproduces this issue
> docker-compose version: v2.32.4
> The file actually exists, throwing no such file or directory error

Provide a screenshot of the execution of docker-compose version

**Comment by G1ume** [comment]
![Image](https://github.com/user-attachments/assets/dd724eee-bc01-44e7-86e3-08cb341ffbd5)
通过修改默认安装路径(不为/opt/1panel)之后，可以成功安装软件。

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
![Image](https://github.com/user-attachments/assets/dd724eee-bc01-44e7-86e3-08cb341ffbd5)
After modifying the default installation path (not /opt/1panel), the software can be installed successfully.
