### ISSUE TITLE
[FEATURE]SSL证书希望支持通过SSH部署到其他服务器上并且支持上传成功后执行命令

### ISSUE THREAD

**Issue by icjs-cc** [1Panel-dev/1Panel#6545]
### 1Panel 版本

v1.10.15-lts

### 请描述您的需求或者改进建议

SSL证书希望支持通过SSH部署到其他服务器上并且支持上传成功后执行命令
主要解决1panel部署到一台服务器上统一管理其他服务器上的证书

**Comment by wanghe-fit2cloud** [comment]
可以通过自定义 scp 命令实现上述需求，`申请证书之后执行脚本` 功能，如下图：
<img width="1474" alt="image" src="https://github.com/user-attachments/assets/46d629be-d1e0-4e4c-83b5-1b55df946f75">
