### ISSUE TITLE
[FEATURE]希望应用商店增加Emby

### ISSUE THREAD

**Issue by hp9014** [1Panel-dev/1Panel#6546]
### 1Panel 版本

xxx

### 请描述您的需求或者改进建议

Emby是一个媒体服务器软件，用于组织、管理和共享个人的音乐、电影、电视节目和其他媒体文件。
官网：https://emby.media/index.html
Docker地址：
Install Emby Server - X64
Emby Docker instructions can be found on Docker Hub:
https://hub.docker.com/r/emby/embyserver

Install Emby Server - Arm64 (aarch64)
Emby Docker instructions can be found on Docker Hub:
https://hub.docker.com/r/emby/embyserver_arm64v8

Install Emby Server - Armv7 (armhf)
Emby Docker instructions can be found on Docker Hub:
https://hub.docker.com/r/emby/embyserver_arm32v7

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，目前第三方仓库已支持，地址如下：
https://github.com/okxlin/appstore/tree/localApps/apps/embyserver

由于该项目的 star 数量暂未达到 1 万，暂时建议通过本地应用方式管理该应用。
