### ISSUE TITLE
[BUG]java运行环境pull Java启动报错，看似没有使用镜像加速

### ISSUE THREAD

**Issue by dawnflyc** [1Panel-dev/1Panel#6548]
### 联系方式

dawnflyc@gmail.com

### 1Panel 版本

v1.10.15-lts

### 问题描述

启动失败:java Pulling java Error Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
看上面的get镜像，和docker的镜像加速设置不一致
是不是因为我安装的时候就已经有docker了

### 重现步骤

新建java运行环境，启动

### 期待的正确结果

正常运行

### 相关日志输出

```shell
启动失败:java Pulling java Error Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by dawnflyc** [comment]
我按照论坛上的改了个镜像，然后重启了，之后忽然正常了，但是出现新问题了，因为之前数据库改了，于是java报错，但是他并没有停止，启动-报错-再次启动-再次报错 这样一直循环，但是没有找到按钮终止循环，我手动停止后，日志直接就没了，怎么点也找不到

**Comment by wanghe-fit2cloud** [comment]
参考：https://bbs.fit2cloud.com/t/topic/5886
只需要进入 `容器` - `配置` 页面，添加镜像加速，不需要修改任何镜像。
