### ISSUE TITLE
[BUG]PHP环境安装OCI8扩展失败问题

### ISSUE THREAD

**Issue by TuringTrail** [1Panel-dev/1Panel#6549]
### 联系方式

微信交流1群；Turng

### 1Panel 版本

v1.10.15-lts

### 问题描述

[#6535](https://github.com/1Panel-dev/1Panel/issues/6535)解决了 pdo_oci 失败的问题 但是oci8扩展安装了还是无法使用

![image](https://github.com/user-attachments/assets/93ceb703-57ea-459e-a02f-9c44b614cc9b)

### 重现步骤

已重新新建运行环境

**Comment by zhengkunwang223** [comment]
感谢反馈 近期版本修复

**Comment by wanghe-fit2cloud** [comment]
该问题已修复，请点击应用商店右上角的【更新应用列表】按钮，更新完成后全新安装 PHP 运行环境即可。
