### ISSUE TITLE
[BUG]openresty安装失败

### ISSUE THREAD

**Issue by wgy1122** [1Panel-dev/1Panel#6554]
### 1Panel 版本

V1.10.15-lts

### 问题描述

![image](https://github.com/user-attachments/assets/ee2501c3-9d05-435b-837f-5d038fa8eb09)

stderr: service "openresty" has no container to start

<html>
<body>

发行版本 alibaba
--
内核版本 5.10.134-17.2.al8.x86_64
系统类型 x86_64

</body>
</html>

### 重现步骤

直接安装显示已安装 但是失败

**Comment by wanghe-fit2cloud** [comment]
参考：https://bbs.fit2cloud.com/t/topic/5886/
