### ISSUE TITLE
创建证书超时是什么原因？

### ISSUE THREAD

**Issue by itworkzhang** [1Panel-dev/1Panel#656]
### 请描述您的问题

![image](https://user-images.githubusercontent.com/42572628/232210553-ef63741f-c3b5-4fea-80eb-41af1248bf43.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦提供一下系统日志。
【面板日志】 - 【系统日志】菜单中查看，也可以到安装目录中查看 1Panel.log 文件。

**Comment by 31CFDC30** [comment]
> 感谢反馈，麻烦提供一下系统日志。 【面板日志】 - 【系统日志】菜单中查看，也可以到安装目录中查看 1Panel.log 文件。

我遇到了同样的问题，这是我的日志
`[2023-04-18 18:39:54] [INFO] init logger successfully  
[2023-04-18 18:39:54] [INFO] init db successfully  
[2023-04-18 18:39:54] [INFO] Migration run successfully  
panic: Cannot acquire directory lock on "/opt/1panel/cache".  Another process is using this Badger database. error: resource temporarily unavailable

goroutine 1 [running]:
github.com/1Panel-dev/1Panel/backend/init/cache.Init()
	github.com/1Panel-dev/1Panel/backend/init/cache/cache.go:50 +0x17f
github.com/1Panel-dev/1Panel/backend/server.Start()
	github.com/1Panel-dev/1Panel/backend/server/server.go:37 +0x85
github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func1(0x6d20d40?, {0x321ada7?, 0x0?, 0x0?})
	github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:17 +0x17
github.com/spf13/cobra.(*Command).execute(0x6d20d40, {0xc00004e230, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x6d20d40)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	./main.go:23 +0x25
2023/04/18 18:40:54 [INFO] acme: Trying to resolve account by key
2023/04/18 18:40:55 [INFO] [*.xxxxxxxxxxx.xxx] acme: Obtaining bundled SAN certificate
2023/04/18 18:40:56 [INFO] [*.xxxxxxxxxxx.xxx] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/220451417137
2023/04/18 18:40:56 [INFO] [*.xxxxxxxxxxx.xxx] acme: use dns-01 solver
2023/04/18 18:40:56 [INFO] [*.xxxxxxxxxxx.xxx] acme: Preparing to solve DNS-01
2023/04/18 18:43:58 [INFO] cloudflare: new record for xxxxxxxxxxx.xxx, ID 7b9d70c30f21*********************
2023/04/18 18:43:58 [INFO] [*.xxxxxxxxxxx.xxx] acme: Trying to solve DNS-01
2023/04/18 18:44:00 [INFO] [*.xxxxxxxxxxx.xxx] acme: Checking DNS record propagation using [8.8.8.8:53]
2023/04/18 18:44:02 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
2023/04/18 18:44:15 [INFO] [*.xxxxxxxxxxx.xxx] The server validated our request
2023/04/18 18:44:15 [INFO] [*.xxxxxxxxxxx.xxx] acme: Cleaning DNS-01 challenge
2023/04/18 18:44:16 [INFO] [*.xxxxxxxxxxx.xxx] acme: Validations succeeded; requesting certificates
2023/04/18 18:44:18 [INFO] [*.xxxxxxxxxxx.xxx] Server responded with a certificate.`

**Comment by zhengkunwang223** [comment]
> > 感谢反馈，麻烦提供一下系统日志。 【面板日志】 - 【系统日志】菜单中查看，也可以到安装目录中查看 1Panel.log 文件。
> 
> 我遇到了同样的问题，这是我的日志 `[2023-04-18 18:39:54] [INFO] init logger successfully [2023-04-18 18:39:54] [INFO] init db successfully [2023-04-18 18:39:54] [INFO] Migration run successfully panic: Cannot acquire directory lock on "/opt/1panel/cache". Another process is using this Badger database. error: resource temporarily unavailable
> 
> goroutine 1 [running]: github.com/1Panel-dev/1Panel/backend/init/cache.Init() github.com/1Panel-dev/1Panel/backend/init/cache/cache.go:50 +0x17f github.com/1Panel-dev/1Panel/backend/server.Start() github.com/1Panel-dev/1Panel/backend/server/server.go:37 +0x85 github.com/1Panel-dev/1Panel/cmd/server/cmd.glob..func1(0x6d20d40?, {0x321ada7?, 0x0?, 0x0?}) github.com/1Panel-dev/1Panel/cmd/server/cmd/root.go:17 +0x17 github.com/spf13/cobra.(_Command).execute(0x6d20d40, {0xc00004e230, 0x0, 0x0}) github.com/spf13/cobra@v1.6.1/command.go:916 +0x862 github.com/spf13/cobra.(_Command).ExecuteC(0x6d20d40) github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc github.com/spf13/cobra.(_Command).Execute(...) github.com/spf13/cobra@v1.6.1/command.go:968 main.main() ./main.go:23 +0x25 2023/04/18 18:40:54 [INFO] acme: Trying to resolve account by key 2023/04/18 18:40:55 [INFO] [_.xxxxxxxxxxx.xxx] acme: Obtaining bundled SAN certificate 2023/04/18 18:40:56 [INFO] [_.xxxxxxxxxxx.xxx] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/_************ 2023/04/18 18:40:56 [INFO] [_.xxxxxxxxxxx.xxx] acme: use dns-01 solver 2023/04/18 18:40:56 [INFO] [_.xxxxxxxxxxx.xxx] acme: Preparing to solve DNS-01 2023/04/18 18:43:58 [INFO] cloudflare: new record for xxxxxxxxxxx.xxx, ID 7b9d70c30f21********************* 2023/04/18 18:43:58 [INFO] [_.xxxxxxxxxxx.xxx] acme: Trying to solve DNS-01 2023/04/18 18:44:00 [INFO] [_.xxxxxxxxxxx.xxx] acme: Checking DNS record propagation using [8.8.8.8:53] 2023/04/18 18:44:02 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s] 2023/04/18 18:44:15 [INFO] [_.xxxxxxxxxxx.xxx] The server validated our request 2023/04/18 18:44:15 [INFO] [_.xxxxxxxxxxx.xxx] acme: Cleaning DNS-01 challenge 2023/04/18 18:44:16 [INFO] [_.xxxxxxxxxxx.xxx] acme: Validations succeeded; requesting certificates 2023/04/18 18:44:18 [INFO] [_.xxxxxxxxxxx.xxx] Server responded with a certificate.`

日志没有错误 可能就是单纯网络原因超时 尝试先重启 1panel,1pctl restart ，再重试

**Comment by wanghe-fit2cloud** [comment]
麻烦将 1Panel 升级到最新版本 v1.1.3，确认是否还存在上述问题。

**Comment by heyzqq** [comment]
> 麻烦将 1Panel 升级到最新版本 v1.1.3，确认是否还存在上述问题。

目前是 v1.1.3 了，也遇到同样的问题，有概率，重试几次可以成功。

创建了三个证书，两次遇到，感觉错误概率较大。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已经发布，麻烦升级到最新版本查看一下是否还存在上述问题。

**Comment by M1saka10010** [comment]
同样的问题 1.5版本还在
