### ISSUE TITLE
[BUG] SSH配置对 /* 识别有误, 导致后面内容被识别为注释

### ISSUE THREAD

**Issue by zuilintan** [1Panel-dev/1Panel#6560]
### 1Panel 版本

v1.10.15-lts

### 问题描述

![QQ_1727151370640](https://github.com/user-attachments/assets/8c5f25ad-9e44-4425-8ceb-b1a98f3f7687)

因为没有识别到显式指定的端口, GUI那里显示的端口就是默认的
![QQ_1727151232126](https://github.com/user-attachments/assets/eedcecf2-f893-495f-8c3b-cb95b85ec5ad)

### 重现步骤

必现

### 期待的正确结果

正常解析配置

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，重复问题 https://github.com/1Panel-dev/1Panel/issues/6496
