### ISSUE TITLE
[BUG]代码编辑python语法高亮解析错误

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#6567]
### 1Panel 版本

v1.10.16-lts

### 问题描述

python高亮解析错误：

![PixPin_2024-09-24_18-51-59](https://github.com/user-attachments/assets/a255b02b-720d-404d-9b21-e5226f89fcdc)

![PixPin_2024-09-24_18-55-17](https://github.com/user-attachments/assets/fc595c94-262f-49ce-a026-4b3617c098ad)

### 重现步骤

下面是一个正常代码：
```python

txt = """
{a}
"""

txt = f"""
{a}10
"""
print(123)

```

解析错误：

![image](https://github.com/user-attachments/assets/02450a3b-1d68-43b8-9bb8-28b461fb51ae)

**Comment by JAINKRE** [comment]
这个感觉是编辑器的问题，不知道1panel用的是哪一个，建议提个issue

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，关于代码编辑器高亮问题，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/6496
