### ISSUE TITLE
[BUG]容器构建停止后编辑重启Command解析错误

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#6568]
### 1Panel 版本

v1.10.16-lts

### 问题描述

dockerfile中构建容器命令：
```
CMD ["sh", "-c", "uwsgi --ini uwsgi.ini & nginx -g 'daemon off;'"]
```

构建成功后启动容器无误

但是，停止容器后编辑容器任意内容，重启容器，启动失败

通过排除发现，Command启动命令被解析错误

### 重现步骤

自行构建docker镜像：
```cmd
docker run -d -p 8127:443 --name DevBuild.jainkre_python3flask-fk.4ddfc9aa jainkre_python3flask-fk:dev-build.4ddfc9aa
```
简单来说容器是一个flask项目，使用uwsgi作为服务，nginx作为反向代理。

构建产物直接输出在目标机器上，机器由1panel管理

此时，启动该容器成功：

![image](https://github.com/user-attachments/assets/68f929ac-5f91-4387-aa60-844a77c2511e)

容器状态一切正常：

![image](https://github.com/user-attachments/assets/b121034e-0127-453d-a3a8-bf5611820b46)

停止容器，进行任意操作，比如修改容器名称：

![image](https://github.com/user-attachments/assets/85921b2f-bb0f-4e2c-87b3-be75c3a21858)

此时Command显示：
```
'sh' '-c' 'uwsgi --ini uwsgi.ini & nginx -g 'daemon off;''
```

![image](https://github.com/user-attachments/assets/f1572382-cd86-48b9-b8c1-4356feb1b97c)

然后重启容器，失败，报错：

![image](https://github.com/user-attachments/assets/22712960-1633-456f-92f3-0f12dee8c661)

查看容器Command

![image](https://github.com/user-attachments/assets/e7347f8c-2b98-4309-9bb5-4d5fa6c1255d)

而容器构建正确启动命令为：
![image](https://github.com/user-attachments/assets/40c06c53-4694-4876-bcb9-b656ef091118)

### 期待的正确结果

赶紧修复一下吧，应该是转义符的问题

一直以为是构建和命令问题，反复排除了几个小时，才发现是面板导致的。。。。

**Comment by ssongliu** [comment]
感谢反馈，麻烦提供容器 inspect Cmd 部分的截图，方便的话可以加一下我

![image](https://github.com/user-attachments/assets/4622d80e-8642-4ba5-b293-976497e984c7)

**Comment by JAINKRE** [comment]
> 感谢反馈，麻烦提供容器 inspect Cmd 部分的截图，方便的话可以加一下我

已申请

**Comment by JAINKRE** [comment]
@wanghe-fit2cloud 这个问题好像没有解决，今天又遇到了。

**Comment by wanghe-fit2cloud** [comment]
> @wanghe-fit2cloud 这个问题好像没有解决，今天又遇到了。

收到，我们本地环境再验证一下。

**Comment by JAINKRE** [comment]
> > @wanghe-fit2cloud 这个问题好像没有解决，今天又遇到了。
> 
> 收到，我们本地环境再验证一下。

好的，希望可以尽快定位解决，十分感谢！

**Comment by wanghe-fit2cloud** [comment]
v1.10.22 版本已发布。
