### ISSUE TITLE
[BUG]【数据库】-【MySQL】[描述信息]编辑后通过回车键离开编辑框无法触发保存

### ISSUE THREAD

**Issue by 7FreezingPoint** [1Panel-dev/1Panel#6569]
### 1Panel 版本

v1.10.16-lts

### 问题描述

【数据库】-【MySQL】[描述信息]编辑后通过回车键退出编辑框后无法触发保存，只有鼠标点击离开编辑框时可以触发保存

### 重现步骤

编辑后不通过鼠标点击离开编辑框，通过回车键离开编辑框

### 期待的正确结果

回车也可以触发保存
另外其它页面相关操作希望也可以排查一下是否存在该问题

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，关于回车键保存的需求讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/6562
