### ISSUE TITLE
[BUG]页面下面出现一条白色的横向滚动线

### ISSUE THREAD

**Issue by XF-Store** [1Panel-dev/1Panel#6570]
### 1Panel 版本

v1.10.16-lts

### 问题描述

使用edge浏览器进入1panel面板后概况、网站、证书、数据库等等这些有数据的页面的下面都会出现一条白色的横向滚动线，换谷歌浏览器就没有，看下图，我用两个电脑只试验过edge和谷歌浏览器，目前就edge浏览器出现这个问题
![微信截图_20240925082846](https://github.com/user-attachments/assets/5f6c0ea1-78c3-4aa2-8bcd-7a114fffadb7)

### 重现步骤

使用edge浏览器进入1panel服务器面板，首页就能看到

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期修改该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.17 版本已发布，修复了上述问题。
