### ISSUE TITLE
[BUG] 【高级功能】-【WAF】今日状态显示错乱

### ISSUE THREAD

**Issue by djx30103** [1Panel-dev/1Panel#6572]
### 1Panel 版本

v1.10.16-lts

### 问题描述

今日状态显示错乱

### 重现步骤

只要是直接从【概览】页面直接切换到【WAF】页面，就会出现错乱问题，需要在【WAF】页面刷新才会正常

### 附加信息

![image](https://github.com/user-attachments/assets/650f1b9c-056e-40a8-bbe3-4845538be684)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期修复该问题。

**Comment by wanghe-fit2cloud** [comment]
相同问题：https://github.com/1Panel-dev/1Panel/issues/6570

**Comment by wanghe-fit2cloud** [comment]
v1.10.17 版本已发布，修复了上述问题。
