### ISSUE TITLE
[FEATURE] 证书更新时，可以自动推送到网站目录下，避免手动更新

### ISSUE THREAD

**Issue by Zhuoyuan1** [1Panel-dev/1Panel#6579]
### 1Panel 版本

v1.10.16-lts

### 请描述您的需求或者改进建议

证书更新时，可以自动推送到网站目录（/opt/1panel/apps/openresty/openresty/www/sites/******/index）下，避免证书到期总是手动更新

### 请描述你建议的实现方案

copy一份到目录下

**Comment by wanghe-fit2cloud** [comment]
可以通过自定义 `scp` 命令实现上述需求，`申请证书之后执行脚本` 功能，如下图：
![image](https://github.com/user-attachments/assets/1e79434d-0691-4f30-8aa5-856a2d05164e)
