### ISSUE TITLE
[FEATURE] 不要乱改docker compose格式

### ISSUE THREAD

**Issue by rdself** [1Panel-dev/1Panel#6581]
### 1Panel 版本

v1.10.17-lts

### 请描述您的需求或者改进建议

在1.10.16版本开始，docker compose文件如果从1panel的“编排”功能内进行了编辑，即使没有使用新增的环境变量功能，依然会导致compose文件内各个服务的排版被强制重写，对于有多个docker在一个compose内的情况下的可读性非常不友好。

希望多考虑一下有一定技术基础的用户的需求，不要强制为用户重新排版。感谢！

**Comment by wanghe-fit2cloud** [comment]
重复问题 https://github.com/1Panel-dev/1Panel/issues/6584
