### ISSUE TITLE
[BUG] 【容器】-【编排】docker compose文件内容异常

### ISSUE THREAD

**Issue by djx30103** [1Panel-dev/1Panel#6584]
### 1Panel 版本

v1.10.17-lts

### 问题描述

docker compose内容错乱

### 重现步骤

编排成功后，再次修改当前编排内容，docker compose内容就错乱了

### 附加信息

第一次成功后，内容正常：
![image](https://github.com/user-attachments/assets/0d17f79b-a635-493c-a7ee-d8c99dd82434)

修改端口后：
![image](https://github.com/user-attachments/assets/6d6c8dac-79e4-4d43-b460-320e0ca2f948)

**Comment by wanghe-fit2cloud** [comment]
> 编排成功后，再次修改当前编排内容，docker compose 内容就错乱了

1、是指的 compose 文件内容顺序错乱吗？
2、compose 服务是通过 1Panel 页面创建还是应用商店等其他途径？

**Comment by djx30103** [comment]
1: 顺序乱了，指定的networks也乱了，所以没有走1panel-network了，而是新建了一个network
2: 页面点击的创建编排

**Comment by wanghe-fit2cloud** [comment]
> 1: 顺序乱了，指定的networks也乱了，所以没有走1panel-network了，而是新建了一个network 2: 页面点击的创建编排

收到，我们在本地环境先验证一下该问题，后续版本修复。

**Comment by rdself** [comment]
同样问题

**Comment by muhanstudio** [comment]
同样，通过编排模版编排的容器组，在编排界面出现一个额外的同名的无法删除的编排，点击删除会删除所有编排容器，但是自己还存在，可能与这个pr有关
https://github.com/1Panel-dev/1Panel/pull/6447

**Comment by zuilintan** [comment]
我这边的问题是二次编辑失败, 提示:
`服务内部错误: update failed when handle compose up, err: stderr: time="2024-09-27T03:07:56+08:00" level=warning msg="/volume1/opt/1panel/docker/compose/scrutiny/docker-compose.yml: `version` is obsolete" service "app" refers to undefined volume config: invalid compose project`

**Comment by wanghe-fit2cloud** [comment]
> 同样，通过编排模版编排的容器组，在编排界面出现一个额外的同名的无法删除的编排，点击删除会删除所有编排容器，但是自己还存在，可能与这个pr有关 #6447

如果未勾选 `彻底删除`，则会执行 `docker-compose down` 命令移除容器，但编排记录将被保留。
![image](https://github.com/user-attachments/assets/d989d16d-218c-47bb-980e-843ae9da9327)

**Comment by LilligantMatsuri** [comment]
### 系统信息

- **发行版**：Debian 12 (bookworm)
- **1Panel**：v1.10.17-lts (社区版)

### 复现过程

1. 在 _容器-编排_ 选项卡手动创建一个名称为“test”的编排，并为该编排中的每个容器指定一个 apps 网络下的有效 IPv4 地址（“apps”为手动创建的容器网络）
  
2. 完成创建，编排下各容器正常启动
  
3. 点击 _编辑_，对 docker-compose.yml 中的内容进行任意(?)修改，点击确认保存，发生以下错误：
  
  > 服务内部错误: update failed when handle compose up, err: stderr: Network test_apps Creating Network test_apps Created Container nginx Recreate Container test Recreate Container mysql Created Error response from daemon: invalid config for network test_apps: invalid endpoint settings: user specified IP address is supported only when connecting to networks with user configured subnets
  

4. 此时，发现在 _容器-网络_ 选项卡中异常创建了一个名称为“test_apps”的网络，而没有使用现有的“apps”网络
  
5. 删除容器网络“test_apps”，再次尝试第 3 步的修改，能够保存并启动，但 docker-compose.yml 的内容被改写，即上面提到的内容错乱
  
6. 名称为“test_apps”的网络在上一步中再次被创建，将其删除，并将编排中的所有容器也一并删除（在 _容器_ 选项卡逐一勾选并删除，未直接删除编排本身）
  
7. 编排“test”依然存在，但此时点击 _编辑_，内容显示为空，尝试输入内容并保存时，发生以下错误：
  
  > 请求参数错误: Key: 'ComposeUpdate.Path' Error:Field validation for 'Path' failed on the 'required' tag
  
8. 点击 _删除_，在未勾选“彻底删除”的情况下尝试删除该编排，同样得到第 7 步中的错误（如下图所示）
  
![截图](https://github.com/user-attachments/assets/f4a37b85-d292-40d2-a0ec-e11f0f01c1a5)

**注**：在先前的版本中（v1.10.15-lts 及以前），执行第 6 步的操作会删除编排本身（条目从 *容器-编排* 选项卡消失，但编排文件夹下的数据文件依然存在）

**Comment by wanghe-fit2cloud** [comment]
节前会发布 Bug 修复版本。

**Comment by wanghe-fit2cloud** [comment]
v1.10.18 版本已发布。

**Comment by lssdo12** [comment]
我也发现了compose删不掉的问题，应该是旧版本搞的bug，新版本虽然解决了新创建的compose删除问题，但是旧版本残留的还是删不掉。我抓包发现了请求的差别
正常删除compose的请求：
```
{
	"name": "ssl-certificates-alpine",
	"path": "/dockerfile/ssl-certificates-alpine/docker-compose.yml",
	"operation": "delete",
	"withFile": false
}
```
删不掉的compose的请求：
```
{
	"name": "nuxt3-home",
	"path": "",
	"operation": "delete",
	"withFile": false
}
```
可以发现 path 内容不见了，我用 Charles 修改请求补充路径后就能正常删除compose了
