### ISSUE TITLE
快照应支持备份本地应用

### ISSUE THREAD

**Issue by rf11291** [1Panel-dev/1Panel#6587]
### 1Panel 版本

v1.10.14-lts

### 请描述您的需求或者改进建议

当前的快照的功能无法备份本地应用，实属难受，应当支持

**Comment by wanghe-fit2cloud** [comment]
对于容器化部署的应用，建议创建 `Shell 脚本` 类型的计划任务，直接备份 Docker 数据目录即可。1Panel 的自动备份功能在遇到进程占用等情况时可能导致快照任务失败，因此短期内暂不考虑支持自动快照。

获取 Docker 数据目录的命令如下：
```shell
docker info --format '{{ .DockerRootDir }}'
```
