### ISSUE TITLE
[FEATURE] 每个容器对应哪个网站不好区分

### ISSUE THREAD

**Issue by hhun** [1Panel-dev/1Panel#659]
### 1Panel 版本

1.1

### 请描述您的需求或者改进建议

每个容器对应哪个网站不好区分，最好是容器页面里面注明换关联哪个域名。
目前还只是两个，如果网站多了真的没法区分。

### 请描述你建议的实现方案

![微信图片_20230416135825](https://user-images.githubusercontent.com/19625243/232274571-5fcb4747-38f4-43cf-b9bf-44422a70622b.png)

**Comment by zhengkunwang223** [comment]
感谢建议，我们后续版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布
