### ISSUE TITLE
[FEATURE] 部署Docker容器配置页面, 自动填充Env, Ports, Volumes等预置信息

### ISSUE THREAD

**Issue by zuilintan** [1Panel-dev/1Panel#6590]
### 1Panel 版本

v1.10.17-lts

### 请描述您的需求或者改进建议

RT, 
镜像中已有必须的端口等信息, 
但部署时尚需手动填写

**Comment by wanghe-fit2cloud** [comment]
如需设置对外暴露端口或持久化存储等，需自定义添加。
