### ISSUE TITLE
[FEATURE]数据库密码策略

### ISSUE THREAD

**Issue by MrChenSH** [1Panel-dev/1Panel#6591]
### 1Panel 版本

v1.10.17-lts

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/5601085d-6cea-4ef7-8ada-ed1d0235ffaf)
密码策略不够开放，导致某些特殊字符无法输入

### 请描述你建议的实现方案

建议校验长度和是否包含特殊字符等复杂度，不校验固定的特殊字符

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，密码复杂度相关问题的讨论，统一汇总到该 issue [#4290](https://github.com/1Panel-dev/1Panel/issues/4290)
