### ISSUE TITLE
[FEATURE]metersphere升级到3.3.0版本

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#6595]
### 1Panel 版本

v1.10.17-lts

### 请描述您的需求或者改进建议

v3.2.0版本出现的一个影响使用的bug：https://github.com/metersphere/metersphere/issues/33260

在3.3.0版本已经解决，但当前面板还不支持更新

希望尽早提供升级

**Comment by wanghe-fit2cloud** [comment]
已推送更新。点击应用商店右上角的【更新应用列表】按钮，等待同步完成后即可安装、升级该版本。
