### ISSUE TITLE
证书延期丢失其它域名的问题

### ISSUE THREAD

**Issue by li-peifeng** [1Panel-dev/1Panel#6596]
### 1Panel 版本

1.10.17

### 问题描述

dns验证证书自动延期后丢失其它域名，只有一个主域名， 我的证书包含 a.com *.a.com  b.com *.b.com 这几个域名和泛域名，延期后只有一个a.com了，其它域名丢失，编辑后重新申请又可以的。

### 重现步骤

无

### 期待的正确结果

希望能正常使用

**Comment by zhengkunwang223** [comment]
目前证书申请和续期用的是一个接口，你是通过什么方式检查了证书文件中的域名？

**Comment by li-peifeng** [comment]
> 目前证书申请和续期用的是一个接口，你是通过什么方式检查了证书文件中的域名？

证书延期后打开网站提示不可信，查看证书只有一个裸域名，证书里查看详情也只有一个，其它域名丢失

**Comment by zhengkunwang223** [comment]
> > 目前证书申请和续期用的是一个接口，你是通过什么方式检查了证书文件中的域名？
> 
> 证书延期后打开网站提示不可信，查看证书只有一个裸域名，证书里查看详情也只有一个，其它域名丢失

我刚才手动测试了一下没问题 等到期续期了再看一下 如果有问题 再打开这个 issue

**Comment by li-peifeng** [comment]
> > > 目前证书申请和续期用的是一个接口，你是通过什么方式检查了证书文件中的域名？
> 
> > 
> 
> > 证书延期后打开网站提示不可信，查看证书只有一个裸域名，证书里查看详情也只有一个，其它域名丢失
> 
> 
> 
> 我刚才手动测试了一下没问题 等到期续期了再看一下 如果有问题 再打开这个 issue 

手动没问题，我也测试过，下次延期再看吧
