### ISSUE TITLE
[FEATURE]站点waf支持UA过滤及兼容CDN

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#660]
### 1Panel 版本

1.1.0

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/19621032/232275923-60bcad40-290a-4afd-b527-a4766828dc43.png)
支持UA过滤及兼容CDN，可以的话支持“禁止国内/外访问”

### 请描述你建议的实现方案

抄一下bt的免费waf最好，但bt的waf不支持禁止国内只支持禁止国外，希望可以国内国外分别设置禁止

**Comment by zhengkunwang223** [comment]
感谢建议，后续版本会支持UA过滤

**Comment by maninhill** [comment]
未来通过集成第三方 WAF 解决。

**Comment by maninhill** [comment]
https://github.com/1Panel-dev/1Panel/issues/2009
