### ISSUE TITLE
[FEATURE]任务管理器

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#661]
### 1Panel 版本

1.1.0

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/19621032/232276551-cf0b04b9-1fa3-4126-a7cb-6c09f9a1ae7c.png)
![image](https://user-images.githubusercontent.com/19621032/232276659-12e080f4-7f42-47cf-bfbf-cacdf6804178.png)

感觉任务管理器是刚需，有时候需要它找阻塞的进程，截图是bt的，点击进程有详情且可以操作

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会支持任务中心。

**Comment by wanghe-fit2cloud** [comment]
建议将 1Panel 升级到最新版本，体验全新新增功能。
