### ISSUE TITLE
[FEATURE]支持postgresql17

### ISSUE THREAD

**Issue by zhengchalei** [1Panel-dev/1Panel#6612]
### 1Panel 版本

v1.10.17-lts

### 请描述您的需求或者改进建议

postgresql 17 版本支持

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们将在后续版本中考虑支持该版本。

**Comment by wanghe-fit2cloud** [comment]
已推送更新。点击应用商店右上角的【更新应用列表】按钮，等待同步完成后即可安装、升级该版本。
