### ISSUE TITLE
[FEATURE]【应用商店】-Nacos能否支持选择数据库

### ISSUE THREAD

**Issue by 7FreezingPoint** [1Panel-dev/1Panel#6617]
### 1Panel 版本

v1.10.17-lts

### 请描述您的需求或者改进建议

加入Mysql数据库的支持

**Comment by wanghe-fit2cloud** [comment]
官方提供了一个 MySQL 的 Compose 文件，但使用的并非标准版本的 MySQL。建议通过 1Panel 的 `容器` - `编排` 功能来管理该 MySQL 版本。
更多信息可参考 Nacos 项目文档：[文档链接地址](https://github.com/nacos-group/nacos-docker/tree/master/example)。
