### ISSUE TITLE
[BUG]在我安装应用时报错

### ISSUE THREAD

**Issue by ThismanisnotmansurnamedSu** [1Panel-dev/1Panel#662]
### 1Panel 版本

1.1.0

### 问题描述

当我安装Halo和其他应用时候，它显示“来自守护程序的错误响应：创建挂载源路径“/opt/1panel/apps/mysql/Dawn/data”时出错：mkdir /opt/1panel：权限被拒绝。”

### 重现步骤

安装Halo和其他应用时

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，该路径（/opt/1panel/apps/mysql/Dawn/data）为 mysql 持久化目录，进服务器手动创建有问题吗？
还有，您部署 1Panel 使用的是什么操作系统（cat /etc/os-release）？登录用户是否为 root？

**Comment by ThismanisnotmansurnamedSu** [comment]
> 感谢反馈，该路径（/opt/1panel/apps/mysql/Dawn/data）为 mysql 持久化目录，进服务器手动创建有问题吗？ 还有，您部署 1Panel 使用的是什么操作系统（cat /etc/os-release）？登录用户是否为 root？

我使用的系统是ubuntu，版本：22.04，且登录账号为root

**Comment by wanghe-fit2cloud** [comment]
我们在本地开发测试服务器没有复现该问题。
接下来你可以将 1Panel 升级到最新版本 v1.1.3，查看是否还存在相同的问题。
