### ISSUE TITLE
[BUG]v1.10.17-lts版本中使用docker compose问题

### ISSUE THREAD

**Issue by XF2886** [1Panel-dev/1Panel#6622]
### 1Panel 版本

v1.10.18-lts

### 问题描述

在v1.10.17-lts碰到了docker compose删不掉模板的问题 , 于是我直接从 /opt/1panel/docker/compose 删掉了相关目录 , 但是编排中仍然显示 , 看到issue中有反馈该问题的 , 等到了 v1.10.18-lts 更新后 , 还是删不掉编排中的记录 , 我手动加回了 /opt/1panel/docker/compose  下的文件夹和docker-compose.yml文件 , 仍无法删除 , 目前编排中有一条僵尸记录 , 无论是否勾选 `删除文件` , 删除都提示 `请求参数错误: Key: 'ComposeOperation.Path' Error:Field validation for 'Path' failed on the 'required' tag` , 直接创建新的同名编排会提示 `记录已存在` , 我该如何解决 ?

### 重现步骤

见描述

**Comment by wanghe-fit2cloud** [comment]
已知问题，v1.10.18 版本已修复。
