### ISSUE TITLE
[BUG]无法自签IPv6证书

### ISSUE THREAD

**Issue by PoisonGZ** [1Panel-dev/1Panel#6623]
### 1Panel 版本

v1.10.18-lts

### 问题描述

无法签发IPv6的自签证书，
![屏幕截图 2024-09-29 175345](https://github.com/user-attachments/assets/cedefb1d-5104-4a36-9cbd-a53c3d65b7e5)
![屏幕截图 2024-09-29 175402](https://github.com/user-attachments/assets/ecc4864a-e04d-4b7c-8d05-6d6b87524dc5)

### 重现步骤

生成CA证书以后，点击签发证书，只要填写IPv6地址就无法签发

**Comment by zhengkunwang223** [comment]
感谢反馈 我们会在后续版本优化此处

**Comment by PoisonGZ** [comment]
> 感谢反馈 我们会在后续版本优化此处

每天都来看看版本更新了么，心急QvQ

**Comment by PoisonGZ** [comment]
> 感谢反馈 我们会在后续版本优化此处

你们的预览版为什么没看到什么更新呀

**Comment by zhengkunwang223** [comment]
> > 感谢反馈 我们会在后续版本优化此处
> 
> 
> 
> 你们的预览版为什么没看到什么更新呀

本月底更新版本

**Comment by wanghe-fit2cloud** [comment]
v1.10.19-lts 版本已发布。
