### ISSUE TITLE
[FEATURE] 添加 sqlynx 专业版

### ISSUE THREAD

**Issue by Jengro777** [1Panel-dev/1Panel#6624]
### 1Panel 版本

1.10.17

### 请描述您的需求或者改进建议

https://www.sqlynx.com/zh-cn/download/

docker 方案
https://www.bilibili.com/read/cv26742238/

### 请描述你建议的实现方案

下载带 SDK 的linux 专业版，打包成 docker 镜像。

**Comment by wanghe-fit2cloud** [comment]
由于该项目非开源，且容器镜像并非官方提供，因此暂时无法上架到应用商店。
