### ISSUE TITLE
[FEATURE] 通过cli命令升级系统

### ISSUE THREAD

**Issue by rdself** [1Panel-dev/1Panel#6630]
### 1Panel 版本

v1.10.18-lts

### 请描述您的需求或者改进建议

有部署多台服务器的情况下，每次版本升级需要打开网页一个个升级，有点繁琐，希望增加一个通过cli升级的命令，这样就可以通过探针等工具批量下发升级指令，谢谢！

**Comment by wanghe-fit2cloud** [comment]
感谢反馈！我们计划在 v2 版本中引入多主机管理功能，届时将支持可视化升级所有节点。
至于通过 1pctl 命令实现升级的功能，我们会在 v2 版本的开发过程中考虑是否添加。

**Comment by wanghe-fit2cloud** [comment]
多主机管理相关需求的讨论，统一汇总到该 issue [#2692](https://github.com/1Panel-dev/1Panel/issues/2692)
