### ISSUE TITLE
[BUG]证书过期后，手动重启1Panel后 面板管理域名仍然显示不安全

### ISSUE THREAD

**Issue by Ausli** [1Panel-dev/1Panel#6634]
### 1Panel 版本

v1.10.18-lts

### 问题描述

如题

### 重现步骤

面板管理域名过期，Let's Encrypt重新获取到面板管理域名，进入显示1Panel面板管理页面显示网页不安全
必须先关掉管理面板的ssl开关，重新开启后恢复正常

### 期待的正确结果

重启1panel服务ssl正常运行

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，该问题可能与此 `话题讨论` 相关，您可以参考以下链接继续跟进相关话题：https://github.com/1Panel-dev/1Panel/discussions/5113。
