### ISSUE TITLE
[FEATURE] 首页的文件系统用量排除 overlay 类型

### ISSUE THREAD

**Issue by moonheart** [1Panel-dev/1Panel#6637]
### 1Panel 版本

v1.10.18-lts

### 请描述您的需求或者改进建议

![image](https://github.com/user-attachments/assets/6a2ac166-4360-4f2b-812e-1907a57e566c)

安装 k3s 后，几十个 overlay 挂载点，影响显示和查看，而且不是默认收起。

### 请描述你建议的实现方案

方案1：排除 overlay
方案2：默认收起

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by ssongliu** [comment]
麻烦提供一下 overlay 挂载点的具体路径

**Comment by moonheart** [comment]
挂载点: /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/1772162011ae6cbae6972049637681d4831bb26fc8d6117ade12336f78b204e2/rootfs

**Comment by wanghe-fit2cloud** [comment]
v1.10.19-lts 版本已发布。
