### ISSUE TITLE
[FEATURE]应用商店添加Zdir

### ISSUE THREAD

**Issue by sunnyhmz7010** [1Panel-dev/1Panel#6638]
### 1Panel 版本

v1.10.18-lts

### 请描述您的需求或者改进建议

[官网：https://www.zdir.pro/zh/](https://www.zdir.pro/zh/)
使用Docker Compose安装
version: '3.3'
services:
    zdir:
        container_name: zdir
        privileged: true
        volumes:
            - '/opt/zdir/data:/opt/zdir/data'
            - '/data/public:/opt/zdir/data/public'
            - '/data/private:/opt/zdir/data/private'
        ports:
            - '6080:6080'
        restart: always
        image: 'helloz/zdir:4'

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，该应用已经在 [第三方应用商店](https://github.com/okxlin/appstore/tree/localApps/apps/clouddrive) 支持，可以以本地应用的方式来部署该应用。
