### ISSUE TITLE
[BUG] 查看日志时卡死

### ISSUE THREAD

**Issue by Sunwuyuan** [1Panel-dev/1Panel#6642]
### 联系方式

***

### 1Panel 版本

v1.10.18-lts

### 问题描述

![IMG_20241004_174527](https://github.com/user-attachments/assets/b363c2fd-20d1-485a-962f-1415b278533a)
![IMG_20241004_174521](https://github.com/user-attachments/assets/2869d0ae-143c-49db-bdeb-43b4f14d2186)
为什么拍屏？因为彻底卡死了完全用不了

复现：edge浏览器找个日志多点的容器点进去，等待几秒直接卡死，是那种占用过大的卡，鼠标直接罢工，CtrlAltDel界面要卡几分钟，进去了也用不了。
重点是网页依然在更新数据，怀疑代码渲染有问题。

用户端卡死，服务器内存充足，运行正常

https://bbs.fit2cloud.com/t/topic/7263
https://bbs.fit2cloud.com/t/topic/6595
https://bbs.fit2cloud.com/t/topic/2798

### 重现步骤

查看日志或者使用docker-compose部署容器，极大概率触发，我十次九次触发

### 相关日志输出

```shell
服务端正常，用户端要么就是没有日志，要么就是控制台也卡死了
```

### 附加信息

半年前（我第一次用1panel）就出现过

**Comment by zhengkunwang223** [comment]
感谢反馈，我们先复现一下

**Comment by Muska-Ami** [comment]
同样的问题，日志很多的情况下会导致设备非常卡顿。。。甚至会导致浏览器未响应

**Comment by ltzXiaoYanMo** [comment]
同遇，主要复现需要日志文件内很多日志在里面，少一点的不会遇见。

能否修一修这个逆天渲染，放以前的都不会出现的问题放这几个版本就会出现，有点影响了吧

**Comment by ltzXiaoYanMo** [comment]
> 同遇，主要复现需要日志文件内很多日志在里面，少一点的不会遇见。
> 
> 能否修一修这个逆天渲染，放以前的都不会出现的问题放这几个版本就会出现，有点影响了吧

再次尝试复现，加入其他内核浏览器。

发现基于 Gecko（Firefox）的浏览器不会导致卡死，但日志文件过大会导致 Gecko 内核的浏览器闪退（概率性问题），基于Chromium（Microsoft Edge）会出现卡死问题。

**Comment by ltzXiaoYanMo** [comment]
> > 同遇，主要复现需要日志文件内很多日志在里面，少一点的不会遇见。
> > 能否修一修这个逆天渲染，放以前的都不会出现的问题放这几个版本就会出现，有点影响了吧
> 
> 再次尝试复现，加入其他内核浏览器。
> 
> 发现基于 Gecko（Firefox）的浏览器不会导致卡死，但日志文件过大会导致 Gecko 内核的浏览器闪退，基于Chromium（Microsoft Edge）会出现卡死问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
