### ISSUE TITLE
[BUG]PHP环境连接Oracle 出现中文乱码问题

### ISSUE THREAD

**Issue by TuringTrail** [1Panel-dev/1Panel#6644]
### 联系方式

微信交流1群；Turng

### 1Panel 版本

v1.10.18-lts

### 问题描述

通过issues反馈无果[#6608](https://github.com/1Panel-dev/1Panel/issues/6608#event-14440425301)
PHP容器环境引起连接Oracle数据库charset编码参数设置无效，然后导致数据库中文输出乱码
后自行发现，PHP容器环境缺少NLS_LANG环境变量，使用环境变量配置NLS_LANG=.AL32UTF8或者NLS_LANG=AMERICAN_AMERICA.AL32UTF8均可解决此问题，建议如果安装pdo_oci和oci8扩展增加此环境变量

### 重现步骤

暂未发现是什么引起的charset编码参数设置无效

**Comment by wanghe-fit2cloud** [comment]
创建运行环境支持环境变量需求，参考：https://github.com/1Panel-dev/1Panel/issues/4262
