### ISSUE TITLE
[FEATURE] 给应用商店的 PostgreSQL 添加带 pgroonga 扩展的分支版本

### ISSUE THREAD

**Issue by wuhang2003** [1Panel-dev/1Panel#6646]
### 1Panel 版本

v1.10.18-lts

### 请描述您的需求或者改进建议

> [PGroonga](https://github.com/pgroonga/pgroonga) 是一个 PostgreSQL 扩展，它使用 Groonga 作为索引。PGroonga 让 PostgreSQL 成为所有语言的快速全文搜索平台！
由于 PGroonga 不方便在使用 Docker 容器托管的 PostgreSQL 安装，希望能直接添加[带 PGroonga 的 PostgreSQL 镜像](https://github.com/pgroonga/docker)。

### 请描述你建议的实现方案

由于带 PGroonga 的镜像基于 PostgreSQL 构建（Those images based on [postgres](https://hub.docker.com/_/postgres) and could use as same as postgres images），所以也能和正常的 PostgreSQL 配置兼容，不需要修改原有的配置文件。所以更倾向于在下拉列表提供分支版本的选择而不是单开一个应用。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，建议优先使用本地应用的方式来管理 [PGroonga](https://github.com/pgroonga/pgroonga)。
此外，项目中也提供了 `docker-compose.yml` 文件，还可以考虑通过 `容器` - `编排` 功能来管理该应用。
