### ISSUE TITLE
[应用商店]上架excalidraw

### ISSUE THREAD

**Issue by TIkc9** [1Panel-dev/1Panel#6649]
### 1Panel 版本

v1.10.18-lts

### 请描述您的需求或者改进建议

上架开源画板excalidraw
github地址：https://github.com/excalidraw/excalidraw
dockerhub地址：https://hub.docker.com/r/excalidraw/excalidraw
活跃度高且持续更新，也确实挺好用的

**Comment by JAINKRE** [comment]
看到群里有人讨论要加这个，但excalidraw官方默认不支持中文手写字体，因此实际效果不是很友好。

如果社区要支持，我可以分享我们二次修改后的版本，支持中文手写字体：（手写体可商用）

![image](https://github.com/user-attachments/assets/07b8a44a-d75a-4ad1-845f-503f68a1319f)

直接docker部署的。

如果有需要到时候联系，看看怎么提供镜像，因为这个项目在我们内部fork

![image](https://github.com/user-attachments/assets/fddcb102-4c37-48c3-a3bc-f891e596e1ec)

**Comment by wanghe-fit2cloud** [comment]
应用已上架，进入 `应用商店` 列表，点击右上角的【更新应用列表】按钮，待同步完成后即可安装应用。
