### ISSUE TITLE
[FEATURE]几点小小建议

### ISSUE THREAD

**Issue by shenshangshang** [1Panel-dev/1Panel#6655]
### 1Panel 版本

v1.10.18-lts

### 请描述您的需求或者改进建议

1. 数据库能否管理能否增加mongodb
2. openresty什么时候能更新到支持http3
3. 快照备份能否备份所有的docker容器或者改为可以选择

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1、数据库支持的 MongoDB 需求（近期暂无计划支持），汇总到该 issue #399
2、1Panel v2 版本时将支持，参考该 issue #3641
3、备份所有容器的需求，参考该 issue #6587
