### ISSUE TITLE
[BUG] 概览-监控 下行流量显示不准确,

### ISSUE THREAD

**Issue by maxbad** [1Panel-dev/1Panel#6668]
### 1Panel 版本

v1.10.18-lts

### 问题描述

这里的上行,下行是这样的吗?
上行: 是用户从服务器下载文件
下行: 是用户上传文件到服务器或者服务器从网络下载文件

![image](https://github.com/user-attachments/assets/9456f2b9-0d9b-44cc-b922-973d0b864ee7)

### 重现步骤

我程序是在容器内跑,提供下载服务,
这里显示的上行应该是正确的,但是下行肯定是错的,.服务器都没这么大的带宽,
看上去是容器内的上传,累加到所有网卡的下载了.

**Comment by ssongliu** [comment]
感谢反馈，这里的上行下行都是所有的流量，包括容器间的，可以下拉框筛选特定的网卡，也可以在面板设置中设置默认显示的网卡

**Comment by maxbad** [comment]
下拉筛选的时候, 可以关联容器吗. 显示容器名称
