### ISSUE TITLE
[FEATURE]容器界面中属于同一docker compose的折叠起来，这样界面清爽很多

### ISSUE THREAD

**Issue by jasperjiasc** [1Panel-dev/1Panel#6673]
### 1Panel 版本

v1.10.18-lts

### 请描述您的需求或者改进建议

容器页面显示docker compose + docker container, docker compose 可以展开其中的containers，这样界面清爽很多，可以参考docker desktop的设计。

**Comment by wanghe-fit2cloud** [comment]
`容器` - `编排` 页面已支持分组查看容器，如图：
![image](https://github.com/user-attachments/assets/5642e049-0769-4352-ae05-1c28e64579b6)

> 容器列表暂无计划再支持 compose 分组，望理解。
