### ISSUE TITLE
[FEATURE]建议添加禁止容器访问外网选项

### ISSUE THREAD

**Issue by dididaguai** [1Panel-dev/1Panel#6674]
### 1Panel 版本

v1.10.18-lts

### 请描述您的需求或者改进建议

建议添加禁止容器访问外网选项；
实现外部可以通过映射的端口访问容器服务，但是容器无法主动访问互联网！

**Comment by dididaguai** [comment]
添加过nano或者自己创建一个bridge网络，无法实现上述需求。

**Comment by wanghe-fit2cloud** [comment]
在这个 issue 中讨论 https://github.com/1Panel-dev/1Panel/issues/6665
