### ISSUE TITLE
[FEATURE] 是否可以支持第三方插件

### ISSUE THREAD

**Issue by QYG2297248353** [1Panel-dev/1Panel#6686]
### 1Panel 版本

v1.10.18-lts

### 请描述您的需求或者改进建议

不知道是否会提供一个，类似 `插件市场` 的模块。
用户可以通过 url 或者 压缩包 的形式上传插件。
插件市场的插件，可以结合 1Panel API 做一些事情，丰富1Panel 的能力。

比如，我就想通过插件进行应用导入(用户可以自己选择需要导入哪些应用，而不是全部导入)，应用列表更新(应用导入后触发)，创建计划任务(插件提供的标准化任务直接导入)。 

### 请描述你建议的实现方案

类似 `插件市场` 的模块

**Comment by zhengkunwang223** [comment]
Golang 的插件功能比较难用 比较难实现
如果你有更好的方案 可以告诉我们

**Comment by QYG2297248353** [comment]
> Golang 的插件功能比较难用 比较难实现 如果你有更好的方案 可以告诉我们

前端就足够了，js/ts + vue 类似 halo 的插件页面一样，
js 足够调用API了，只要 API 足够丰富

**Comment by zhengkunwang223** [comment]
> > Golang 的插件功能比较难用 比较难实现 如果你有更好的方案 可以告诉我们
> 
> 
> 
> 前端就足够了，js/ts + vue 类似 halo 的插件页面一样，
> 
> js 足够调用API了，只要 API 足够丰富

有可行的技术方案吗

**Comment by QYG2297248353** [comment]
> 有可行的技术方案吗

我认为 https://github.com/halo-dev/plugin-starter/tree/main/ui 中的 UI  管理这一套就可以

通过注册路由的形式,展示页面
```
{
  components: {},
  routes: [
    {
      parentName: "Root",
      route: {
        path: "/example",
        name: "Example",
        component: HomeView,
        meta: {
          title: "示例页面",
          searchable: true,
          menu: {
            name: "示例页面",
            group: "示例分组",
            icon: markRaw(IconPlug),
            priority: 0,
          },
        },
      },
    },
  ],
  extensionPoints: {},
}
```
配合 `/1panel/swagger/index.html` API SDK 就足够了

**Comment by zhengkunwang223** [comment]
> > 有可行的技术方案吗
> 
> 我认为 https://github.com/halo-dev/plugin-starter/tree/main/ui 中的 UI 管理这一套就可以
> 
> 通过注册路由的形式,展示页面
> 
> ```
> {
>   components: {},
>   routes: [
>     {
>       parentName: "Root",
>       route: {
>         path: "/example",
>         name: "Example",
>         component: HomeView,
>         meta: {
>           title: "示例页面",
>           searchable: true,
>           menu: {
>             name: "示例页面",
>             group: "示例分组",
>             icon: markRaw(IconPlug),
>             priority: 0,
>           },
>         },
>       },
>     },
>   ],
>   extensionPoints: {},
> }
> ```
> 
> 配合 `/1panel/swagger/index.html` API SDK 就足够了

看起来可以 你可以尝试提交一个 pr

**Comment by QYG2297248353** [comment]
> 看起来可以 你可以尝试提交一个 pr

我只在 Halo 中使用此方法开发过插件，虽然都是Vue，但是应该是有一套插件的加载和卸载的逻辑

**Comment by zhengkunwang223** [comment]
> > 看起来可以 你可以尝试提交一个 pr
> 
> 我只在 Halo 中使用此方法开发过插件，虽然都是Vue，但是应该是有一套插件的加载和卸载的逻辑

经过讨论 我们短期内还是注重核心功能的开发和优化 这个第三方插件可能还得后面再看看

**Comment by QYG2297248353** [comment]
> 经过讨论 我们短期内还是注重核心功能的开发和优化 这个第三方插件可能还得后面再看看

谢谢，已了解
