### ISSUE TITLE
[BUG]配置docker加速地址了但是还是通过docker官方仓库下载

### ISSUE THREAD

**Issue by Shuai-S** [1Panel-dev/1Panel#6689]
### 1Panel 版本

v1.10.18-lts

### 问题描述

<img width="583" alt="image" src="https://github.com/user-attachments/assets/a4640aac-55fe-47be-83a2-c3ee049e5705">
<img width="771" alt="image" src="https://github.com/user-attachments/assets/b0dabf76-a4f4-43f8-ad11-734a204d0169">

### 重现步骤

安装it-tools，拉取镜像一直失败

**Comment by wanghe-fit2cloud** [comment]
国内 Docker 服务状态 & 镜像加速监控

👌 https://status.1panel.top

✅ 进去后找到 `Docker 镜像加速` 标签的网址，即是加速源。

💡 使用方法1：1Panel左边菜单栏>容器>配置>镜像加速。

💡 使用方法2：按格式编辑 `/etc/docker/daemon.json` 文件。

⚠️ 假如 `Cloudflare` 标签的无法正确加速，可以尝试 `Nginx` 标签的加速源。

**Comment by wanghe-fit2cloud** [comment]
可以多添加几个可用的加速地址。
