### ISSUE TITLE
[FEATURE]希望可以创建完php网站后，可以修改php环境

### ISSUE THREAD

**Issue by 52lemon6** [1Panel-dev/1Panel#669]
### 1Panel 版本

1.1.0

### 请描述您的需求或者改进建议

希望可以创建完php网站后，可以在网站设置中修改php环境，如果创建完php应用后，发现少了php中的某个环境，就需要把整个网站给全部删掉，然后再重新创建，又或者再开发php应用的时候，有新功能需要增加，需要用到新的php环境，也同样需要把整个网站全部删掉

**Comment by zhengkunwang223** [comment]
1.如果是扩展没有安装，可以重新编辑运行环境，然后重建应用
2.这个功能可以加 后续版本支持

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。
