### ISSUE TITLE
[FEATURE]请求支持发布证书到自定义位置

### ISSUE THREAD

**Issue by ColinZeb** [1Panel-dev/1Panel#6694]
### 1Panel 版本

v1.10.18-lts

### 请描述您的需求或者改进建议

目前我没有使用网站管理功能，证书这块申请完了发现没啥用，所以希望有个证书更新后发布/同步证书的功能。

### 请描述你建议的实现方案

简单设想：
1.发布到本地目录，支持自定义目录和自定义文件名
2.支持自定义脚本，用户自己实现发布逻辑
3.发布到ftps、webdav、ssh等，这个不重要，没有的话暂时可以自定义脚本实现

**Comment by zhengkunwang223** [comment]
当前版本已经支持推送目录和自定义脚本

**Comment by ColinZeb** [comment]
v1.10.18有吗，我在界面和文档里都没找到

**Comment by zhengkunwang223** [comment]
![image](https://github.com/user-attachments/assets/ef52b05f-0f90-450a-b3cb-4ea8a60095b7)

**Comment by ColinZeb** [comment]
thanks ,我看其他issue里已经提到自定义文件名了，我就先关了
