### ISSUE TITLE
[FEATURE] 建议支持host_network部署

### ISSUE THREAD

**Issue by IsQiao** [1Panel-dev/1Panel#6701]
### 1Panel 版本

master

### 请描述您的需求或者改进建议

有些服务可能随时新增占用多个端口，比如nexus，如果只配置一个或几个端口会非常麻烦

### 请描述你建议的实现方案

支持部署服务的选项为host_network

**Comment by wanghe-fit2cloud** [comment]
感谢反馈！目前 1Panel 应用商店在部署应用时，已经支持通过 `高级设置` - `修改 compose 文件` 进行编辑和调整。至于动态可视化切换网络功能，由于基于当前应用框架实现难度较高，短期内暂时不考虑支持，望理解。

修改网络部分可以参考 OpenResty：
```shell
network_mode: host
```
