### ISSUE TITLE
[BUG] 按钮组按钮边距不一致

### ISSUE THREAD

**Issue by mdddj** [1Panel-dev/1Panel#6704]
### 1Panel 版本

v1.10.18-lts

### 问题描述

<img width="993" alt="image" src="https://github.com/user-attachments/assets/ca405e19-65cb-4181-b4cc-91027f917c04">

### 重现步骤

无

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
`文件管理` 和 `计划任务` 页面也存在该样式问题，近期版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.19-lts 版本已发布。
