### ISSUE TITLE
[FEATURE]伪静态方案希望增加自定义功能，或者增加CI4的方案，感谢

### ISSUE THREAD

**Issue by qdbu** [1Panel-dev/1Panel#6707]
### 1Panel 版本

所有版本

### 请描述您的需求或者改进建议

伪静态方案希望增加自定义功能，或者增加CI4的方案，感谢

### 请描述你建议的实现方案

location / {
    try_files $uri $uri/ /index.php$is_args$args;
}

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持该需求。

**Comment by wanghe-fit2cloud** [comment]
自定义伪静态方案的需求，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/705
