### ISSUE TITLE
[FEATURE]php版本切换问题建议，以及防跨站功能需求

### ISSUE THREAD

**Issue by okxlin** [1Panel-dev/1Panel#671]
### 1Panel 版本

v1.1.0

### 请描述您的需求或者改进建议

- 1.PHP功能建议
现有的网站需要事先创建PHP环境才能使用PHP，对已经创建的网站不是非常友好，需要删除再添加，

且后续如果需要更换PHP版本也不是非常方便。

如果仅仅修改openresty配置，监听不同的php-fpm端口来更换不同版本，然后php配置修改独立出来，可能会更加方便。

- 2.防跨站功能
希望可以增加防跨站功能。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布，支持了 PHP 版本切换功能。
