### ISSUE TITLE
[BUG]页面点击，js代码报错

### ISSUE THREAD

**Issue by 357341051** [1Panel-dev/1Panel#672]
### 1Panel 版本

1.1

### 问题描述

![65bb0c37a8a051ccd7d36a375d31fe7](https://user-images.githubusercontent.com/118408640/232414315-d2aa44d3-3aa9-46fd-94ee-2876a65fffb1.png)
![d4a7dba54bd8303531e139ee6ae4018](https://user-images.githubusercontent.com/118408640/232414340-ee80fa8f-c4ba-4754-b8e0-31e3741acc84.png)

### 重现步骤

上面已截图，可能还有存在其他的报错，我就不一一尝试了，强迫症患者，哈哈

**Comment by zhengkunwang223** [comment]
感谢，后续版本解决此问题

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
