### ISSUE TITLE
[BUG]创建快照状态一直是进行中

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#6723]
### 1Panel 版本

v1.10.18-lts

### 问题描述

![图片](https://github.com/user-attachments/assets/bc34b6a3-e0e1-4fa6-9817-b8a5ec1fc9a0)

### 重现步骤

如题。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
