### ISSUE TITLE
[Feat] 镜像拉取失败时允许用户重新拉取

### ISSUE THREAD

**Issue by QingFeng-awa** [1Panel-dev/1Panel#6726]
### 1Panel 版本

1.10.19-LTS

### 请描述您的需求或者改进建议

在`/containers/image`手动拉取镜像时,我可能会因为各种各样的原因想要重新拉取镜像(比如说我镜像名输错了),但是在第一次拉取后拉取按钮就会被禁用,无法进行第二次拉取。
我想要重新拉取镜像只能退出重新打开页面才能拉取,对于我们~~这群懒人~~来说肯定是不方便的。
我希望能在镜像拉取出现问题时允许用户直接在当前页面重新拉取,而不是退出重进。

### 请描述你建议的实现方案

检测日志中的`image pull failed`等提示拉取出现问题的字样,在出现问题后允许重新拉取。

**Comment by wanghe-fit2cloud** [comment]
后续版本可能会考虑支持镜像重新拉取。

**Comment by ssongliu** [comment]
目前是拉取出现错误后， 修改容器名称可以直接重新拉取
