### ISSUE TITLE
[BUG]修改私有仓库配置项后会导致docker无法启动。

### ISSUE THREAD

**Issue by jesns** [1Panel-dev/1Panel#6730]
### 联系方式

jesns@vip.qq.com

### 1Panel 版本

v1.10.19-lts

### 问题描述

修改私有仓库配置项后会导致docker无法启动。

### 重现步骤

修改私有仓库配置项后会导致docker无法启动。

**Comment by ssongliu** [comment]
感谢反馈，麻烦贴点截图以及日志信息

**Comment by wanghe-fit2cloud** [comment]
最新版本已支持在修改 Docker 配置后、重启 Docker 前增加对 daemon.json 文件的校验，建议升级至最新版本再试。
