### ISSUE TITLE
firewalld和ufw同时存在无法增删改查规则

### ISSUE THREAD

**Issue by Lihy6472** [1Panel-dev/1Panel#6734]
### 联系方式

w254378584@163.com

### 1Panel 版本

1.10.19

### 问题描述

* 服务器同时存在firewalld和ufw防火墙，在主机-防火墙下无法对已有规则增删改查

![image](https://github.com/user-attachments/assets/7653306b-9ad7-4c45-b0dc-6c55bd3b47cd)

![image](https://github.com/user-attachments/assets/d7ad4aba-bfa0-4e92-b449-ed9c10a27f2a)

### 重现步骤

升级到最新版1panel，服务器同时安装ufw和firewalld，访问1panel页面下的主机-防火墙

### 期待的正确结果

同时存在ufw和firewalld以那个防火墙启动使用那个为准(老版本逻辑)

**Comment by wanghe-fit2cloud** [comment]
是的，我们在 v1.10.19 版本中增加了判断功能，如果检测到同时存在 ufw 和 firewalld，就会提示用户只能保留其中一个。
请问，在什么场景下会需要同时安装这两种防火墙呢？

**Comment by Lihy6472** [comment]
> 是的，我们v1.10.19版本中增加了判断功能，如果检测到同时存在ufw和firewalld，就会提示用户只能保留一个。 请问，在哪些场景下需要同时安装这两种防火墙呢？

ubuntu系统，默认ufw防火墙，但是对firewalld比较熟悉。

**Comment by wanghe-fit2cloud** [comment]
> > 是的，我们v1.10.19版本中增加了判断功能，如果检测到同时存在ufw和firewalld，就会提示用户只能保留一个。 请问，在哪些场景下需要同时安装这两种防火墙呢？
> 
> ubuntu系统，默认ufw防火墙，但是对firewalld比较熟悉。

了解，后续版本我们可以考虑在这种情况下，允许用户自定义选择使用哪种防火墙。

**Comment by Lihy6472** [comment]
> > > 是的，我们v1.10.19版本中增加了判断功能，如果检测到同时存在ufw和firewalld，就会提示用户只能保留一个。请问，在哪些场景下需要同时安装这两个防火墙呢？
> > 
> > 
> > ubuntu系统，ufw默认防火墙，但是对firewalld比较熟悉。
> 
> 了解，后续版本我们可以考虑在这种情况下，允许用户自定义选择使用哪种防火墙。

好的，那当前版本来说的话，只能卸载一个？大概需要什么时间发布该版本？

**Comment by wanghe-fit2cloud** [comment]
> > > > 是的，我们v1.10.19版本中增加了判断功能，如果检测到同时存在ufw和firewalld，就会提示用户只能保留一个。请问，在哪些场景下需要同时安装这两个防火墙呢？
> > > 
> > > 
> > > ubuntu系统，ufw默认防火墙，但是对firewalld比较熟悉。
> > 
> > 
> > 了解，后续版本我们可以考虑在这种情况下，允许用户自定义选择使用哪种防火墙。
> 
> 好的，那当前版本来说的话，只能卸载一个？大概需要什么时间发布该版本？

是的，当前版本你可以先手动卸载 ufw，之后就能正常使用 firewalld。
> 近期版本可能会考虑优先支持。

**Comment by ssongliu** [comment]
> > > > 是的，我们v1.10.19版本中增加了判断功能，如果检测到同时存在ufw和firewalld，就会提示用户只能保留一个。请问，在哪些场景下需要同时安装这两个防火墙呢？
> > > 
> > > 
> > > ubuntu系统，ufw默认防火墙，但是对firewalld比较熟悉。
> > 
> > 
> > 了解，后续版本我们可以考虑在这种情况下，允许用户自定义选择使用哪种防火墙。
> 
> 好的，那当前版本来说的话，只能卸载一个？大概需要什么时间发布该版本？

可以暂时重命名一下 /usr/sbin/ufw 这个文件，mv /usr/sbin/ufw /usr/sbin/ufw.bak

**Comment by Lihy6472** [comment]
> > > > > 是的，我们v1.10.19版本中增加了判断功能，如果检测到同时存在ufw和firewalld，就会提示用户只能保留一个。请问，在哪些场景下需要同时安装这两个防火墙呢？
> > > > 
> > > > 
> > > > ubuntu系统，ufw默认防火墙，但是对firewalld比较熟悉。
> > > 
> > > 
> > > 了解，后续版本我们可以考虑在这种情况下，允许用户自定义选择使用哪种防火墙。
> > 
> > 
> > 好了，那当前版本说完的话只能卸载一个？大概需要什么时间发布该版本？
> 
> 可以暂时重命名一下 /usr/sbin/ufw 这个文件，mv /usr/sbin/ufw /usr/sbin/ufw.bak

我试下，谢谢，
