### ISSUE TITLE
[FEATURE]应用商店添加node-red

### ISSUE THREAD

**Issue by eiloogs** [1Panel-dev/1Panel#6737]
### 1Panel 版本

v1.10.19-lts

### 请描述您的需求或者改进建议

项目地址[node-red](https://github.com/node-red/node-red)

### 请描述你建议的实现方案

建议添加node-red
docker run -it -p 1880:1880 -v node_red_data:/data --name mynodered nodered/node-red

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑上架该应用。

**Comment by wanghe-fit2cloud** [comment]
该应用已上架至应用商店。
