### ISSUE TITLE
[FEATURE]能否让那个代码编辑支持多tab

### ISSUE THREAD

**Issue by Lockartist** [1Panel-dev/1Panel#6738]
### 1Panel 版本

v1.10.19-lts

### 请描述您的需求或者改进建议

能否让那个代码编辑支持多tab,有时候线上调整个问题，来回找文件太麻烦了
![20241016-162955](https://github.com/user-attachments/assets/026b0f8b-be96-4aec-8231-3eab7685ba5e)

希望V1和V2都支持这个

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，同时编辑多文件的需求，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/6283
