### ISSUE TITLE
[BUG]网站根目录/.well-known下的其它验证文件不可被读取、访问

### ISSUE THREAD

**Issue by yggcwx** [1Panel-dev/1Panel#6742]
### 联系方式

yggcwx@outlook.com

### 1Panel 版本

v1.10.19-lts

### 问题描述

如题。最近部署一个应用，要求在网站根目录/.well-known下放置名为server的验证文件。经实测，1panel面板此目录下的server文件不可被读取、访问。

### 重现步骤

1panel群中的朋友帮忙改了nginx配置文件后，可以通过web页访问此文件，但治标不治本，我要部署的那个应用在验证此文件时失败。不得以，换其它运维面板后一切正常，无需用户进行任何额外操作。

### 期待的正确结果

希望用户层面在无需额外操作的情况下，此目录下的其它应用验证文件能正常访问，并能验证成功。

**Comment by zhengkunwang223** [comment]
是什么应用？
你可以先试一下在 网站的配置文件增加

   location ~ \.well-known{
        allow all;
    } 这个配置

**Comment by yggcwx** [comment]
> 是什么应用？ 你可以先试一下在 网站的配置文件增加
> 
> location ~ .well-known{ allow all; } 这个配置

谢谢！是Matrix。之前登录时会是图片里显示的情况。您说的修改，是指单个网站的nginx配置，而不是nginx的全局配置吧？
详情已微[wanghe-fit2cloud](https://github.com/wanghe-fit2cloud)
![webwxgetmsgimg](https://github.com/user-attachments/assets/3c403782-aa6c-4235-8385-aab0cf9095c2)

**Comment by zhengkunwang223** [comment]
> > 是什么应用？ 你可以先试一下在 网站的配置文件增加
> > location ~ .well-known{ allow all; } 这个配置
> 
> 谢谢！是Matrix。之前登录时会是图片里显示的情况。您说的修改，是指单个网站的nginx配置，而不是nginx的全局配置吧？ 详情已微[wanghe-fit2cloud](https://github.com/wanghe-fit2cloud) ![webwxgetmsgimg](https://private-user-images.githubusercontent.com/90705180/377320706-3c403782-aa6c-4235-8385-aab0cf9095c2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDU5MDUsIm5iZiI6MTcyOTE0NTYwNSwicGF0aCI6Ii85MDcwNTE4MC8zNzczMjA3MDYtM2M0MDM3ODItYWE2Yy00MjM1LTgzODUtYWFiMGNmOTA5NWMyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA2MTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNDNiZmE1ZWQ1MzBiODBjM2FiMTE2YjVlNmZkOWRkMGI4NjVmNWM3ZWY4MWNhZTgwZWQzMzU5M2YxYjg2NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ztxd4vurwG39Qf_kHa6XNFO5xXDhmgeA2aS9glmrbA4)

是这个网站的配置 不是全局的

**Comment by yggcwx** [comment]
> 是这个网站的配置 不是全局的

好的。谢谢！

**Comment by yggcwx** [comment]
> 是什么应用？ 你可以先试一下在 网站的配置文件增加
> 
> location ~ .well-known{ allow all; } 这个配置

可否麻烦您在本地测试下？我这里没有测试环境了，因为已经暂时换其它面板了

**Comment by zhengkunwang223** [comment]
> > 是什么应用？ 你可以先试一下在 网站的配置文件增加
> > location ~ .well-known{ allow all; } 这个配置
> 
> 可否麻烦您在本地测试下？我这里没有测试环境了，因为已经暂时换其它面板了

我们和其他面板的区别就是这里 后面有时间我测一下吧 先关闭这个 issue 了
