### ISSUE TITLE
[FEATURE] postgresql 支持17, 所有远程数据库支持实时延迟?

### ISSUE THREAD

**Issue by gowy222** [1Panel-dev/1Panel#6743]
### 1Panel 版本

v1.10.19-lts

### 请描述您的需求或者改进建议

/databases/postgresql界面

1. postgresql 支持17，目前添加的选择里面最高只有16
2. 远程数据库 (服务器外部的 比如supabase) 支持显示数据库延迟, 不过从节约性能角度，5秒一次更新延迟数值策略? 好处是这样方便知道远程数据库延迟高的时候后续维护选择迁移或者其他..而且哪个远程数据库连接断了，或者密码后期不对连接不通了，一眼就能看出，不用傻乎乎的通过PGAdmin4才能知道数据库是否还在线

**Comment by wanghe-fit2cloud** [comment]
1、下个版本支持。
2、在远程数据列表中增加“当前数据库连接是否可用”的列，是否可以满足需求？

**Comment by gowy222** [comment]
> 1、下个版本支持。 2、在远程数据列表中增加“当前数据库连接是否可用”的列，是否可以满足需求？

期望偏向于 5秒一次更新延迟数值策略，
"当前数据库连接是否可用 " 不够直观，

不可用就显示-1数值，可用就显示正数延迟，这样会好一点，等于双功能

**Comment by wanghe-fit2cloud** [comment]
> > 1、下个版本支持。 2、在远程数据列表中增加“当前数据库连接是否可用”的列，是否可以满足需求？
> 
> 期望偏向于 5秒一次更新延迟数值策略， "当前数据库连接是否可用 " 不够直观，
> 
> 不可用就显示-1数值，可用就显示正数延迟，这样会好一点，等于双功能

好的，后续版本我们先调研一下相关的解决方案。

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
