### ISSUE TITLE
在MySQL数据库页面，切换MySQL和MariaDB这两个类型的数据库，会大概率出现服务未启动的提示

### ISSUE THREAD

**Issue by zero-dream** [1Panel-dev/1Panel#6755]
### 联系方式

qq：2732630594

### 1Panel 版本

v1.10.19-lts

### 问题描述

安装了MariaDB和mysql数据库，3306和3307端口，在数据库页面，切换这2个类型的数据库，会大概率出现服务未启动的提示，这2个服务是正常运行和启动的。要刷新多次页面，概率性显示正常。
![2f308266ade483cdae3543bdd4ee493](https://github.com/user-attachments/assets/d0f39d54-b787-4e6e-a190-9499c41aecce)

### 重现步骤

查看问题描述。

### 期待的正确结果

期待你们能解决问吧。

### 相关日志输出

```shell
这里是相关日志输出。
```

### 附加信息

这里是附加信息。

**Comment by wanghe-fit2cloud** [comment]
本地已复现该问题，会在近期版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
