### ISSUE TITLE
[FEATURE]支持应用商店应用判断CPU架构是否支持，或者过滤不支持的应用

### ISSUE THREAD

**Issue by IsQiao** [1Panel-dev/1Panel#6767]
### 1Panel 版本

master

### 请描述您的需求或者改进建议

* 支持应用商店应用判断CPU架构是否支持，或者过滤不支持的应用
* 我用的是arm机器，有很多应用不支持，但是只有在安装之后才会发现，而且排查相对麻烦

**Comment by wanghe-fit2cloud** [comment]
应用区分架构的需求，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/3026
> 1Panel v2 版本会支持该功能。
