### ISSUE TITLE
[BUG]手机视图下多文件删除报错

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#6768]
### 1Panel 版本

v1.10.19-lts

### 问题描述

手机视图下多文件删除报错，如下图：
![图片](https://github.com/user-attachments/assets/15819c44-1284-4b3c-9980-14e565154239)

### 重现步骤

手机视图下多文件删除报错

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
