### ISSUE TITLE
[FEATURE] 添加应用 中微子代理  neutrino-proxy 

### ISSUE THREAD

**Issue by cktk** [1Panel-dev/1Panel#6770]
### 1Panel 版本

v1.10.19-lts

### 请描述您的需求或者改进建议

这个有服务端也有客户端  希望能都加上
官网 https://neutrino-proxy.dromara.org/neutrino-proxy
开源地址 https://gitee.com/dromara/neutrino-proxy

### 请描述你建议的实现方案

官网中的使用docker容器化部署文章中 服务端的配置不全  需要添加上 [服务端配置] 这个文档中的这些参数

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，我们主要以项目的 Star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有超 1 万 Star 的开源项目，感谢您的理解。

> 你可以将需求反馈给 [第三方仓库（由社区用户维护）](https://github.com/okxlin/appstore)。
