### ISSUE TITLE
[BUG]网站默认404页面默认配置失效问题

### ISSUE THREAD

**Issue by caixiaohaier** [1Panel-dev/1Panel#6776]
### 1Panel 版本

v1.10.19-lts

### 问题描述

在网站栏目新建一个新的静态网站，发现默认配置是有引用默认的404页面的配置条目（error_page 404 /404.html），在对网站进行配置HTTPS后，发现配置文件里面error_page 404 /404.html配置条目消失了，导致站点内的默认404页面无法生效。

### 重现步骤

1.新建一个静态网站。
2.对该网站配置HTTPS相关配置。

**Comment by zhengkunwang223** [comment]
感谢反馈 后续版本修复

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
