### ISSUE TITLE
[BUG]ipv6无法访问

### ISSUE THREAD

**Issue by toywl** [1Panel-dev/1Panel#678]
### 联系方式

toywl666@163.com

### 1Panel 版本

1.1.0

### 问题描述

ipv6无法访问

### 重现步骤

ipv6无法访问

### 期待的正确结果

ipv6无法访问

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本会考虑支持。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本将支持用户在面板设置中绑定监听IP。

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
