### ISSUE TITLE
[BUG]使用cname记录无法正常申请单域名证书

### ISSUE THREAD

**Issue by kkqy** [1Panel-dev/1Panel#6780]
### 1Panel 版本

v1.10.19-lts

### 问题描述

我有一个域名www.xxx.com 解析到服务器的，服务器上使用的1panel
然后我还有一个域名 xxx.net 设置了别名记录 *.xxx.net 到 www.xxx.com

以前用宝塔面板的时候，我在面板里通过HTTP验证给xyz.xxx.net申请let's Encrypt的证书是没问题的。

但是现在用1panel以后，貌似必须要设置A记录，而不能通过cname记录来申请。
不知道是bug还是故意这么做的。这样很不方便。

### 重现步骤

1. 假设我有域名www.xxx.com解析了A记录到服务器
2. 同时另外一个域名泛解析了*.xxx.net的别名记录到www.xxx.com
3. 在1panel里通过HTTP方式申请xyz.xxx.net的证书无法通过，提示 `acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for xyz.xxx.net - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for xyz.xxx.net - check that a DNS record exists for this domain`
4. 申请的时候勾选了 “跳过 DNS 校验” 仍然报上述错误。（注意，虽然我解析是泛解析，但我申请的证书**不是**泛证书，而是普通的单域名证书）

### 期待的正确结果

既然宝塔能通过别名记录使用HTTP的方式申请到Let's Encrypt的证书，1panel也应该是可以的吧，不能跳过那个DNS校验吗？
我勾选了 ”跳过DNS校验“ 怎么还会校验A记录和AAAA记录呢？
因为我的子域名比较多，每个都设置A记录很麻烦，所以泛解析别名记录是一个很常见的做法。

**Comment by zhengkunwang223** [comment]
感谢反馈，我们复现一下

**Comment by mjsoftking** [comment]
正常申请证书的时候填写  `主域名：xxx.com` 和 `其他域名：*.xxx.com` 申请就可以，不用添加解析记录，就是需要使用 `DNS账号` 方式申请

**Comment by kkqy** [comment]
> 正常申请证书的时候填写 `主域名：xxx.com` 和 `其他域名：*.xxx.com` 申请就可以，不用添加解析记录，就是需要使用 `DNS账号` 方式申请

如果域名所在账号所有权不在我这，就没法添加DNS账户，只能通过HTTP的方式申请。

**Comment by zhengkunwang223** [comment]
您好 我刚才试了一下 
我在 cloudflare 有一个域名 xx.1panel.xx 指向了我的 服务器
腾讯云 泛解析 *.2panel.xx CANE 到 1panel.xx  
在 1panel 创建了一个 ssl.2panel.xx 的网站
使用 http 模式申请 没有勾选跳过 DNS 验证 
证书申请成功

**Comment by kkqy** [comment]
> 您好 我刚才试了一下 我在 cloudflare 有一个域名 xx.1panel.xx 指向了我的 服务器 腾讯云 泛解析 *.2panel.xx CANE 到 1panel.xx 在 1panel 创建了一个 ssl.2panel.xx 的网站 使用 http 模式申请 没有勾选跳过 DNS 验证 证书申请成功

奇怪，现在又正常了，因为这个问题不只出现过一次，而且有几个服务器都出现过这个问题，每次我都是要去添加A记录才行。我再观察看看。先暂时关闭这个issue，如果我发现触发条件，再重开。
