### ISSUE TITLE
[FEATURE] 能否支持一下只托管二级域名的DNSpod申请证书

### ISSUE THREAD

**Issue by xueba0458** [1Panel-dev/1Panel#6781]
### 1Panel 版本

v1.10.19-lts

### 请描述您的需求或者改进建议

我的主域名xxx.com托管在cloudflare，我为aaa.xxx.com添加了两条NS记录，以便将aaa.xxx.com托管到DNSpod。
现在的情况是cloudflare管理xxx.com这个主域名，DNSpod管理aaa.xxx.com这个子域名！！！
我在1panel的 **SSL证书** 功能界面中添加了**DNSpod**的DNS账户，现在我使用 **DNS账户** 验证方式，并使用刚添加的DNSpod账户申请SSL证书，但是会出现以下错误：
```
cleaning up failed: tencentcloud: failed to get hosted zone: zone xxx.com. not found in dnspod for domain _acme-challenge.aaa.xxx.com. 
```
```
[aaa.xxx.com] [aaa.xxx.com] acme: error presenting token: tencentcloud: failed to get hosted zone: zone xxx.com. not found in dnspod for domain _acme-challenge.aaa.xxx.com.
```

**Comment by zhengkunwang223** [comment]
这种情况没测试过，我们先测试一下

**Comment by xueba0458** [comment]
> 这种情况没测试过，我们先测试一下

lucky动态域名解析工具将这个功能定义为“自定义多级域名后缀”，也就是下图所示的配置界面。只要将主域名添加到了“自定义多级域名后缀”中，那么就能够正常管理只托管了二级域名(aaa.xxx.com)的DNSpod的解析记录，否则就会像1panel一样，出现找不到zone的情况！！！

![Screenshot_2024-10-21-04-32-57-687.png](https://github.com/user-attachments/assets/b09e72e3-683d-4f02-83fd-09448328cc60)

**Comment by zhengkunwang223** [comment]
我测试了一下 申请的时候勾选跳过 DNS 验证 是可以成功的

**Comment by xueba0458** [comment]
> 我测试了一下 申请的时候勾选跳过 DNS 验证 是可以成功的

啊？？？这是什么原理？？？我一直以为那个功能是用于本地DNS死活过不了验证的情况！

**Comment by zhengkunwang223** [comment]
> > 我测试了一下 申请的时候勾选跳过 DNS 验证 是可以成功的
> 
> 啊？？？这是什么原理？？？我一直以为那个功能是用于本地DNS死活过不了验证的情况！

从报错来看 应该是去腾讯云那验证报的错 跳过这个验证 就没问题了

**Comment by xueba0458** [comment]
> > > 我测试了一下 申请的时候勾选跳过 DNS 验证 是可以成功的
> > 
> > 啊？？？这是什么原理？？？我一直以为那个功能是用于本地DNS死活过不了验证的情况！
> 
> 从报错来看 应该是去腾讯云那验证报的错 跳过这个验证 就没问题了

也就是说，DNS记录添加成功了，但是清理DNS记录的时候出现了报错？？？那DNS验证这个功能的作用是啥？？？

**Comment by zhengkunwang223** [comment]
> > > > 我测试了一下 申请的时候勾选跳过 DNS 验证 是可以成功的
> > > 
> > > 
> > > 啊？？？这是什么原理？？？我一直以为那个功能是用于本地DNS死活过不了验证的情况！
> > 
> > 
> > 从报错来看 应该是去腾讯云那验证报的错 跳过这个验证 就没问题了
> 
> 也就是说，DNS记录添加成功了，但是清理DNS记录的时候出现了报错？？？那DNS验证这个功能的作用是啥？？？

按照 lego 官方的解释是验证你对这个域名的所有权 但是从使用上确实有疑问 内部的具体实现还没研究

**Comment by xueba0458** [comment]
> > > > > 我测试了一下 申请的时候勾选跳过 DNS 验证 是可以成功的
> > > > 
> > > > 
> > > > 啊？？？这是什么原理？？？我一直以为那个功能是用于本地DNS死活过不了验证的情况！
> > > 
> > > 
> > > 从报错来看 应该是去腾讯云那验证报的错 跳过这个验证 就没问题了
> > 
> > 也就是说，DNS记录添加成功了，但是清理DNS记录的时候出现了报错？？？那DNS验证这个功能的作用是啥？？？
> 
> 按照 lego 官方的解释是验证你对这个域名的所有权 但是从使用上确实有疑问 内部的具体实现还没研究

还真行……真离谱，那这个选项的意义是什么？？？为什么不是默认勾选的呀？？？甚至不需要添加DNS记录用于验证……

**Comment by zhengkunwang223** [comment]
> > > > > > 我测试了一下 申请的时候勾选跳过 DNS 验证 是可以成功的
> > > > > 
> > > > > 
> > > > > 啊？？？这是什么原理？？？我一直以为那个功能是用于本地DNS死活过不了验证的情况！
> > > > 
> > > > 
> > > > 从报错来看 应该是去腾讯云那验证报的错 跳过这个验证 就没问题了
> > > 
> > > 
> > > 也就是说，DNS记录添加成功了，但是清理DNS记录的时候出现了报错？？？那DNS验证这个功能的作用是啥？？？
> > 
> > 
> > 按照 lego 官方的解释是验证你对这个域名的所有权 但是从使用上确实有疑问 内部的具体实现还没研究
> 
> 还真行……真离谱，那这个选项的意义是什么？？？为什么不是默认勾选的呀？？？甚至不需要添加DNS记录用于验证……

默认是必须要验证的 90%  的情况都没问题，特殊情况需要关闭

**Comment by wan92hen** [comment]
域名校验会有个 SOA 记录的递归校验过程，依次查询每一层域名的 SOA 记录，成功查到了就用当前域名去跟 DNS 服务商 API 查到的域名记录进行匹配。
你说的这个场景，应该只能查询到 xxx.com 的 SOA 记录，但是 DNSpod 查到的域名是 aaa.xxx.com 的，匹配不上所以会有这个报错。
