### ISSUE TITLE
[FEATURE] 希望增加 虚拟 nas 工具 - virtual-dsm

### ISSUE THREAD

**Issue by soonxf** [1Panel-dev/1Panel#6783]
### 1Panel 版本

1.10.19

### 请描述您的需求或者改进建议

希望增加新的 docker 工具

开源地址 [virtual-dsm](https://github.com/vdsm/virtual-dsm)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，我们主要以项目的 Star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有超 1 万 Star 的开源项目，感谢您的理解。

> 你可以将需求反馈给 [第三方仓库（由社区用户维护）](https://github.com/okxlin/appstore)。
