### ISSUE TITLE
Docker IPv6优化

### ISSUE THREAD

**Issue by feewg** [1Panel-dev/1Panel#6786]
### 1Panel 版本

v1.10.19-lts

### 请描述您的需求或者改进建议

- [ ] 安装的时候希望可以默认配置好docker的v6设置，或者安装完成以后可以有自动识别当前环境，并且配置的脚本

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，关于容器 IPv6 功能的讨论汇总至此处：https://github.com/1Panel-dev/1Panel/discussions/6766
