### ISSUE TITLE
[FEATURE] 防火墙端口增加描述

### ISSUE THREAD

**Issue by realzolo** [1Panel-dev/1Panel#679]
### 1Panel 版本

v1.1.0

### 请描述您的需求或者改进建议

希望能增加一个输入项(限制输入字符数)，可手动记录端口被谁使用了。当端口过多时可能就分不清哪个端口对应哪个服务了。
<img width="1450" alt="image" src="https://user-images.githubusercontent.com/63219216/232474788-6f5149cc-e4b7-449e-be22-94b4403920de.png">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by cyril-cheng** [comment]
啊这。。。。你防火墙是如何打开的。。。我根本就用不了。。。

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已发布。
