### ISSUE TITLE
[FEATURE] 安装脚本建议检查一下 Docker 的版本

### ISSUE THREAD

**Issue by ruibaby** [1Panel-dev/1Panel#6795]
### 1Panel 版本

v1.10.18-lts

### 请描述您的需求或者改进建议

目前发现使用脚本安装 1Panel 时仅检查了 Docker Compose 插件的版本，并没有检查 Docker 版本，这可能导致运行时的 Docker 版本过低，无法和 1Panel 的部分功能兼容。尤其是现在不少 Linux 发行版的软件源更新缓慢，所以期望添加检测提醒用户或者直接更新。

![image](https://github.com/user-attachments/assets/a13a55b7-4408-4d5f-aedc-74f861d6d6a6)
![image](https://github.com/user-attachments/assets/91167140-1f2a-40c9-9f2e-768f8932e3cf)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本会考虑在安装脚本中检查Docker版本。

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
