### ISSUE TITLE
[BUG] 市场忽略应用版本BUG

### ISSUE THREAD

**Issue by tenyon61** [1Panel-dev/1Panel#6796]
### 联系方式

meettyj@163.com

### 1Panel 版本

v1.10.19-lts

### 问题描述

mysql8.0.39显示可升级，只显示可忽略8.0.40，可升级那里还是有mysql。

### 重现步骤

1、点击应用商店->可升级
2、忽略升级->选择版本
3、刷新

### 期待的正确结果

可升级应用消失

### 附加信息

![1729575521821](https://github.com/user-attachments/assets/97829165-e3ee-43c4-8106-7e6a1f91f5e6)
忽略后
![image](https://github.com/user-attachments/assets/5d756c55-8d6d-4f78-8509-0aff2363a290)
在选择升级
![image](https://github.com/user-attachments/assets/2332ee28-463e-4438-8b61-3db03aff3e8d)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，刚在本地环境复现了该问题，是由于 MySQL 跨版本升级限制导致的，近期版本会修复。

**Comment by tenyon61** [comment]
感谢修复`Nice 1p`

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
