### ISSUE TITLE
[BUG]网站/websites/runtimes 硬绑定了1panel-network，则应该自动补全重建网络，当没有的时候

### ISSUE THREAD

**Issue by gowy222** [1Panel-dev/1Panel#6804]
### 1Panel 版本

v1.10.19-lts

### 问题描述

![image](https://github.com/user-attachments/assets/77dbfab6-9276-4cdd-984e-196c89b13664)

### 重现步骤
1.先去/websites/runtimes/node 停止网站

2.去/containers/network 这边清理掉所有未使用的网络
(有时候定时任务也会有自己的脚本清除所有未使用的网络)，也可能手动删除了1panel默认的网络

3.然后去/websites/runtimes/node点击启动网站，就会报错 network 1panel-network not found

所以, 机制存在一点问题，/websites这边是硬绑定的 1panel-network，那么是不是应该自动尝试修复+自动重建 1panel-network呢?
不然手动建立可能配置错网络..

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
