### ISSUE TITLE
[BUG] 串站

### ISSUE THREAD

**Issue by lopins** [1Panel-dev/1Panel#6808]
### 1Panel 版本

1.10.19

### 问题描述

访问id为3的站点的域名会定位到id为2的站点内容上

### 重现步骤

![image](https://github.com/user-attachments/assets/51f4b939-2aae-4234-a60c-98b8b5ab03d1)

![image](https://github.com/user-attachments/assets/6fe3a67e-8513-41fc-97bf-82fbcf422311)

---

![image](https://github.com/user-attachments/assets/6a626ab8-6d08-4696-a2fe-420e878c698a)

![image](https://github.com/user-attachments/assets/99a9a41f-f61d-45fe-906c-88f88c13e488)

**Comment by zhengkunwang223** [comment]
无痕模式试一下呢

**Comment by QingFeng-awa** [comment]
遇到同样问题
我的是站点B会跳转到被设置为默认站点的站点A。
站点B未启用SSL,而站点A启用了SSL并开启了HSTS。

**Comment by QingFeng-awa** [comment]
> 遇到同样问题 我的是站点B会跳转到被设置为默认站点的站点A。 站点B未启用SSL,而站点A启用了SSL并开启了HSTS。

解决方法是两个站点都开启SSL

**Comment by QYG2297248353** [comment]
如果您的站点最近发生窜站请参考：
https://github.com/1Panel-dev/1Panel/discussions/6837

仅供参考

**Comment by lopins** [comment]
> 遇到同样问题 我的是站点B会跳转到被设置为默认站点的站点A。 站点B未启用SSL,而站点A启用了SSL并开启了HSTS。

和HTTPS无关，我是WSL里面的，都没有SSL
