### ISSUE TITLE
希望验证码输错之后自动清除输入框

### ISSUE THREAD

**Issue by bai0012** [1Panel-dev/1Panel#681]
### 1Panel 版本

1.1.0

### 请描述您的需求或者改进建议

希望在面板登录时，如果输错了验证码，当验证码更换的时候，自动清除文本框里已经输错的验证码

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.1.3 版本已发布。
