### ISSUE TITLE
[BUG] 快照列表排序报错

### ISSUE THREAD

**Issue by realzolo** [1Panel-dev/1Panel#6810]
### 联系方式

zolo@onezol.com

### 1Panel 版本

v1.10.19-lts

### 问题描述

![image](https://github.com/user-attachments/assets/4c9df58a-eb58-4264-852b-0a8e85d8ef0c)

### 重现步骤

点击快照列表时间排序![image](https://github.com/user-attachments/assets/4c9df58a-eb58-4264-852b-0a8e85d8ef0c)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，刚在本地环境已复现上述问题，我们会在近期版本修复。

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
