### ISSUE TITLE
[BUG] 开启https后访问网页报错

### ISSUE THREAD

**Issue by Kevin-liang05** [1Panel-dev/1Panel#6811]
### 联系方式

17722389205

### 1Panel 版本

1.10.19

### 问题描述

openresty创建反向代理后使用http://域名+端口可以正常访问，在配置-https启用https选择对应证书后，使用https://域名+端口无法访问，浏览器提示错误信息“此网站无法提供安全连接”&“ERR_SSL_PROTOCOL_ERROR”，在排查问题过程中发现在配置文件第一和第二个listen 端口后面添加小写ssl，保存并重载才能正常使用https://域名+端口访问，在论坛中有反馈过这个问题：“开启https后访问网页报错 

### 重现步骤

在配置文件第一和第二个listen 端口后面添加小写ssl，保存并重载才能正常使用https://域名+端口访问，在论坛中有反馈过这个问题：“开启https后访问网页报错

**Comment by zhengkunwang223** [comment]
你的 https 是非 443 端口是吗？
这个问题我们会在 v2 版本处理
请关注这个 Issue https://github.com/1Panel-dev/1Panel/issues/5982

**Comment by Kevin-liang05** [comment]
用443端口或者非443端口都有同样的状况

**Comment by zhengkunwang223** [comment]
> 用443端口或者非443端口都有同样的状况

443 端口不用添加 当你启用网站的时候是默认增加的 并且 ssl 也会写在 listen 443 后端
如果有问题 可以尝试用无痕模式
或者给我们提供一下视频或者 配置 访问情况截图
