### ISSUE TITLE
[BUG]应用商店安装容器，运行时修改映射端口重建后，在应用商店使用原始端口安装其他容器时提示端口被占用

### ISSUE THREAD

**Issue by EmyiaEllen** [1Panel-dev/1Panel#6819]
### 1Panel 版本

v1.10.19-lts

### 问题描述

在应用商店安装应用并启动容器后，在容器列表可以看到该容器的映射端口（如8080），如果在容器列表编辑容器的端口，并重建容器，那么在容器列表中该容器的映射端口会改变（如9090），但在应用商店的【已安装】页面，可以看到该容器使用的仍是安装时的端口（8080）

此时在应用商店安装其他容器，使用该容器第一次使用的端口（8080），提示该端口已被占用

### 重现步骤

1. 在应用商店任选一个应用，使用默认安装，端口40116
![image](https://github.com/user-attachments/assets/5f818d39-4624-4b89-a7ca-d2f415a3299a)
![image](https://github.com/user-attachments/assets/8ce9a6ba-50d3-4c1c-bd94-b1265d51a3c8)
2. 在应用启动后进入容器列表，修改该容器的映射端口为40126
![image](https://github.com/user-attachments/assets/87c8cb3f-c124-478a-9504-f81524c57134)
修改完毕在容器列表显示当前映射端口（40126），然而应用列表仍显示第一次的映射端口（40116）
![image](https://github.com/user-attachments/assets/ff070365-3a3c-4926-a0f7-122e6f2ed798)
![image](https://github.com/user-attachments/assets/2f076c3f-1157-41f3-8e45-639e74a207fb)
3. 在应用商店选择一个未安装的应用，并在映射端口输入上面安装的应用第一次使用的映射端口（40116）
此时提示该端口已被占用
![image](https://github.com/user-attachments/assets/a35995be-094e-4076-8d99-299f47883a4a)

### 期待的正确结果

容器在修改端口重建后，其他安装的容器可以使用该容器的原始端口

### 附加信息

在容器列表中，已安装应用的容器是可以任意修改端口的（只要不发生事实上的端口冲突）

此外，我尝试了在应用商店安装应用时使用不通过1Panel安装部署的应用使用的端口（9090），1Panel同样会检测出来端口占用并且给予提示

因此猜测通过应用商店安装的应用第一次端口信息被缓存起来且重建时没有修改，其他在应用商店安装的应用会去查找这个缓存文件而不是通过 netstat 等方式判断端口实际是否被使用

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，应用商店中的应用均通过 docker-compose 部署，而容器页面使用的是 docker SDK。

因此，如果在容器页面编辑修改部分内容，无法同步到已安装应用。同理，如果在应用商店中修改了应用配置，也会覆盖之前在容器页面的编辑。

因此，对于通过应用商店安装的应用，建议统一在 `应用商店` - `已安装` 页面进行修改。

> 近期版本将在用户编辑容器时，增加更加明显的确认提示。

**Comment by wanghe-fit2cloud** [comment]
v1.10.20 版本已发布。
