### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by seth-shi** [1Panel-dev/1Panel#6821]
### 1Panel 版本

Ubuntu 24.04 64位

### 问题描述

root@10-23-63-156:~# curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sudo bash quick_start.sh
开始下载 1Panel v1.10.19-lts 版本在线安装包
安装包下载地址： https://resource.fit2cloud.com/1panel/package/stable/v1.10.19-lts/release/1panel-v1.10.19-lts-linux-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 40.8M  100 40.8M    0     0  6745k      0  0:00:06  0:00:06 --:--:-- 5848k
Warning: Got more output options than URLs
1panel-v1.10.19-lts-linux-amd64/1panel.service
1panel-v1.10.19-lts-linux-amd64/1pctl
1panel-v1.10.19-lts-linux-amd64/LICENSE
1panel-v1.10.19-lts-linux-amd64/README.md
1panel-v1.10.19-lts-linux-amd64/install.sh
1panel-v1.10.19-lts-linux-amd64/1panel

 ██╗    ██████╗  █████╗ ███╗   ██╗███████╗██╗     
███║    ██╔══██╗██╔══██╗████╗  ██║██╔════╝██║     
╚██║    ██████╔╝███████║██╔██╗ ██║█████╗  ██║     
 ██║    ██╔═══╝ ██╔══██║██║╚██╗██║██╔══╝  ██║     
 ██║    ██║     ██║  ██║██║ ╚████║███████╗███████╗
 ╚═╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝╚══════╝
[1Panel Log]: ======================= 开始安装 ======================= 
设置 1Panel 安装目录（默认为/opt）：
[1Panel Log]: 您选择的安装路径为 /opt 
[1Panel Log]: ... 在线安装 docker 
[1Panel Log]: 选择延迟最低的源 https://mirrors.aliyun.com/docker-ce，延迟为 0.062872 秒 
[1Panel Log]: 尝试从备选链接 https://get.docker.com 下载 Docker 安装脚本... 
curl: (35) Recv failure: Connection reset by peer
[1Panel Log]: 从 https://get.docker.com 下载安装脚本失败，尝试下一个备选链接 
[1Panel Log]: 尝试从备选链接 https://testingcf.jsdelivr.net/gh/docker/docker-install@master/install.sh 下载 Docker 安装脚本... 
[1Panel Log]: 成功从 https://testingcf.jsdelivr.net/gh/docker/docker-install@master/install.sh 下载安装脚本 
# Executing docker install script, commit: 
+ sh -c apt-get -qq update >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get -y -qq install ca-certificates curl >/dev/null
+ sh -c install -m 0755 -d /etc/apt/keyrings
+ sh -c curl -fsSL "https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg" -o /etc/apt/keyrings/docker.asc
+ sh -c chmod a+r /etc/apt/keyrings/docker.asc
+ sh -c echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://mirrors.aliyun.com/docker-ce/linux/ubuntu noble stable" > /etc/apt/sources.list.d/docker.list
sh: 1: cannot create /etc/apt/sources.list.d/docker.list: Directory nonexistent

### 重现步骤

root@10-23-63-156:~# curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sudo bash quick_start.sh
开始下载 1Panel v1.10.19-lts 版本在线安装包
安装包下载地址： https://resource.fit2cloud.com/1panel/package/stable/v1.10.19-lts/release/1panel-v1.10.19-lts-linux-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 40.8M  100 40.8M    0     0  6745k      0  0:00:06  0:00:06 --:--:-- 5848k
Warning: Got more output options than URLs
1panel-v1.10.19-lts-linux-amd64/1panel.service
1panel-v1.10.19-lts-linux-amd64/1pctl
1panel-v1.10.19-lts-linux-amd64/LICENSE
1panel-v1.10.19-lts-linux-amd64/README.md
1panel-v1.10.19-lts-linux-amd64/install.sh
1panel-v1.10.19-lts-linux-amd64/1panel

 ██╗    ██████╗  █████╗ ███╗   ██╗███████╗██╗     
███║    ██╔══██╗██╔══██╗████╗  ██║██╔════╝██║     
╚██║    ██████╔╝███████║██╔██╗ ██║█████╗  ██║     
 ██║    ██╔═══╝ ██╔══██║██║╚██╗██║██╔══╝  ██║     
 ██║    ██║     ██║  ██║██║ ╚████║███████╗███████╗
 ╚═╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝╚══════╝
[1Panel Log]: ======================= 开始安装 ======================= 
设置 1Panel 安装目录（默认为/opt）：
[1Panel Log]: 您选择的安装路径为 /opt 
[1Panel Log]: ... 在线安装 docker 
[1Panel Log]: 选择延迟最低的源 https://mirrors.aliyun.com/docker-ce，延迟为 0.062872 秒 
[1Panel Log]: 尝试从备选链接 https://get.docker.com 下载 Docker 安装脚本... 
curl: (35) Recv failure: Connection reset by peer
[1Panel Log]: 从 https://get.docker.com 下载安装脚本失败，尝试下一个备选链接 
[1Panel Log]: 尝试从备选链接 https://testingcf.jsdelivr.net/gh/docker/docker-install@master/install.sh 下载 Docker 安装脚本... 
[1Panel Log]: 成功从 https://testingcf.jsdelivr.net/gh/docker/docker-install@master/install.sh 下载安装脚本 
# Executing docker install script, commit: 
+ sh -c apt-get -qq update >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get -y -qq install ca-certificates curl >/dev/null
+ sh -c install -m 0755 -d /etc/apt/keyrings
+ sh -c curl -fsSL "https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg" -o /etc/apt/keyrings/docker.asc
+ sh -c chmod a+r /etc/apt/keyrings/docker.asc
+ sh -c echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://mirrors.aliyun.com/docker-ce/linux/ubuntu noble stable" > /etc/apt/sources.list.d/docker.list
sh: 1: cannot create /etc/apt/sources.list.d/docker.list: Directory nonexistent

### 附加信息

手动创建目录就可以安装成功  /etc/apt/sources.list.d/

**Comment by wanghe-fit2cloud** [comment]
1. 在 1Panel 文档中选择 Ubuntu 安装脚本；
2. 该问题可能由服务器权限引起，本地环境未能复现；
3. 也可以选择离线安装包来安装。
