### ISSUE TITLE
[BUG]多次联系进交流群都加不了，从2024年4月到现在也赞助了也买了1p的课，就是不让加交流群，到底能不能解决，不能解决麻烦把钱退来，这点问题都解决不了再好的软件没运维有什么用？

### ISSUE THREAD

**Issue by shaodj** [1Panel-dev/1Panel#6823]
### 联系方式

1Panel 202411 期学习班交流群 少东家

### 1Panel 版本

1.10.18-lts

### 问题描述

[BUG]多次联系进交流群都加不了，从2024年4月到现在也赞助了也买了1p的课，就是不让加交流群，到底能不能解决，不能解决麻烦把钱退来，这点问题都解决不了再好的软件没运维有什么用？要么都别让进，怎么jumpserver群我在2群，maxkb群我在6群，dataease群我在14群

### 重现步骤

赞助的收据 报课的收据都已提交过很多次，就是解决不了

### 期待的正确结果

进交流群正常交流

**Comment by wanghe-fit2cloud** [comment]
添加我微信
<img width="223" alt="image" src="https://github.com/user-attachments/assets/e48b9175-241d-463c-ac3e-498d5d081abf">
