### ISSUE TITLE
[BUG]token expired 14 seconds ago

### ISSUE THREAD

**Issue by seth-shi** [1Panel-dev/1Panel#6826]
### 1Panel 版本

v1.10.19-lts

### 问题描述

![image](https://github.com/user-attachments/assets/180fed76-a9bf-4ea4-8e28-84718580642f)
快照备份提示: token expired 14 seconds ago

### 重现步骤

![image](https://github.com/user-attachments/assets/180fed76-a9bf-4ea4-8e28-84718580642f)
快照备份提示: token expired 14 seconds ago

**Comment by seth-shi** [comment]
[2024-10-23 19:03:44] [DEBUG] tar --warning=no-file-changed --ignore-failed-read --exclude-from=<(find /opt/1panel/backup/system/snapshot_1panel_v1.10.19-lts_amd64_20241023190143ba7c3 -type s -printf '%P
' | sed 's|^|./|') -zcf /opt/1panel/tmp/system/snapshot_1panel_v1.10.19-lts_amd64_20241023190143ba7c3.tar.gz  -C /opt/1panel/backup/system/snapshot_1panel_v1.10.19-lts_amd64_20241023190143ba7c3 .  
[2024-10-23 19:04:13] [DEBUG] compress successful! size of file: 588.27M  
[2024-10-23 19:04:13] [DEBUG] remove snapshot file /opt/1panel/backup/system/snapshot_1panel_v1.10.19-lts_amd64_20241023190143ba7c3  
[2024-10-23 19:04:13] [DEBUG] start upload snapshot to KODO, path: 1panel/system_snapshot/snapshot_1panel_v1.10.19-lts_amd64_20241023190143ba7c3.tar.gz  
2024/10/23 19:08:07 http: TLS handshake error from 104.152.52.42:40958: read tcp4 10.23.63.156:8888->104.152.52.42:40958: read: connection reset by peer
2024/10/23 19:08:17 http: TLS handshake error from 104.152.52.42:56052: tls: first record does not look like a TLS handshake
2024/10/23 19:08:17 http: TLS handshake error from 104.152.52.42:56056: tls: first record does not look like a TLS handshake
2024/10/23 19:08:22 http: TLS handshake error from 104.152.52.42:56068: unexpected EOF
2024/10/23 19:08:23 http: TLS handshake error from 104.152.52.42:34792: tls: unsupported SSLv2 handshake received
2024/10/23 19:46:56 http: TLS handshake error from 64.62.197.213:53385: tls: first record does not look like a TLS handshake
2024/10/23 19:46:59 http: TLS handshake error from 64.62.197.219:35067: tls: first record does not look like a TLS handshake
[2024-10-23 20:15:43] [DEBUG] upload to KODO failed, err: token expired 14 seconds ago

**Comment by ssongliu** [comment]
感谢反馈，看起来是七牛token 过期了，重试能成功吗？

**Comment by seth-shi** [comment]
不行, 一直都是这个错误, 是否可以加一个上传进度条?

**Comment by seth-shi** [comment]
现在快照缺少一个阶段进度条, 现在有一个全局进度条, 但是没有每一步的进度条. 比如压缩的进度条, 上传的进度条

**Comment by seth-shi** [comment]
![image](https://github.com/user-attachments/assets/86190093-1fe2-4d22-9253-b8e6d95509cf)
![image](https://github.com/user-attachments/assets/f267a8a1-2847-43ed-a880-8a2053237e5c)

**Comment by seth-shi** [comment]
bug 必现, 去备份单独的小文件可以, 比如在计划任务 (没做切片上传?)
![image](https://github.com/user-attachments/assets/8b74f5b2-47dc-4ad7-aa15-dca7b19df35c)

**Comment by wanghe-fit2cloud** [comment]
在添加备份账号时，尝试设置一个较长的过期时间，如图：
![image](https://github.com/user-attachments/assets/59db5c88-e75f-4a7f-9089-7d94eef1d183)

**Comment by seth-shi** [comment]
后续是否打算增加一个上传进度条? 这种镜像很大

**Comment by seth-shi** [comment]
感觉可以在`CloudStorageClient`再抽象一个进度条参数进去, 基本大多数存储都支持, 然后外部监听进度条写到日志, 这样子也好排查一下问题

**Comment by wanghe-fit2cloud** [comment]
> 感觉可以在`CloudStorageClient`再抽象一个进度条参数进去, 基本大多数存储都支持, 然后外部监听进度条写到日志, 这样子也好排查一下问题

可以的，后续版本考虑支持一下。

**Comment by seth-shi** [comment]
thx

**Comment by wanghe-fit2cloud** [comment]
> 后续是否打算增加一个上传进度条? 这种镜像很大

先确认下修改过期时间后是否能成功创建快照。

**Comment by seth-shi** [comment]
我已经改成 6 个小时, 在备份中, 有结果我回复

**Comment by wanghe-fit2cloud** [comment]
> > 感觉可以在`CloudStorageClient`再抽象一个进度条参数进去, 基本大多数存储都支持, 然后外部监听进度条写到日志, 这样子也好排查一下问题
> 
> 可以的，后续版本考虑支持一下。

进度条的需求，可以跟踪这个 issue https://github.com/1Panel-dev/1Panel/issues/4651

**Comment by seth-shi** [comment]
![image](https://github.com/user-attachments/assets/53e5a2e6-fd32-4724-9db9-72097117fae2)
加大时间可以
