### ISSUE TITLE
[FEATURE]很适合小白用，但没有交流解答群。QQ群271977815

### ISSUE THREAD

**Issue by laoma2053** [1Panel-dev/1Panel#6829]
### 1Panel 版本

1.0

### 请描述您的需求或者改进建议

很适合小白用，但没有交流解答群。QQ群271977815

### 请描述你建议的实现方案

很适合小白用，但没有交流解答群。QQ群271977815

**Comment by QingFeng-awa** [comment]
[GitHub discussion](https://github.com/1Panel-dev/1Panel/discussions)和[论坛](https://bbs.fit2cloud.com/c/1p/7)很难用么,非要加第三方交流群

**Comment by wanghe-fit2cloud** [comment]
参考：https://github.com/1Panel-dev/1Panel/discussions/6828
