### ISSUE TITLE
[BUG]创建Java类型的运行环境后，应用无法访问

### ISSUE THREAD

**Issue by long-dotcom** [1Panel-dev/1Panel#6832]
### 联系方式

a199810112837@dingtalk.com

### 1Panel 版本

v1.10.19-lts

### 问题描述

创建Java类型的运行环境后，应用无法访问。

### 重现步骤

网站->运行环境->Java下创建运行环境后，当应用端口与外部映射端口一致时，服务能正常部署，内网访问正常，外网访问失败（已开放端口）当修改外部端口号后能正常访问。

### 期待的正确结果

当应用端口和映射端口一致，应用能正常访问。
如果这里不能一致，当用户输入时给出提示

**Comment by zhengkunwang223** [comment]
没有这个限制的 截图一下你的配置吧

**Comment by long-dotcom** [comment]
![image](https://github.com/user-attachments/assets/2bfe64e5-4294-4ae3-a3b0-730e71a64ace)
两个端口一致时试了其他服务器也能稳定触发

**Comment by long-dotcom** [comment]
> 没有这个限制的 截图一下你的配置吧

![image](https://github.com/user-attachments/assets/ffebe15a-f438-4ac6-9eb2-69af5171ed6e)
试了另一台服务器，能稳定触发

**Comment by zhengkunwang223** [comment]
> > 没有这个限制的 截图一下你的配置吧
> 
> ![image](https://private-user-images.githubusercontent.com/72112301/379647755-ffebe15a-f438-4ac6-9eb2-69af5171ed6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTUwODQsIm5iZiI6MTcyOTc1NDc4NCwicGF0aCI6Ii83MjExMjMwMS8zNzk2NDc3NTUtZmZlYmUxNWEtZjQzOC00YWM2LTllYjItNjlhZjUxNzFlZDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA3MjYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MWJhMTljY2YxYmM1YzYzMmZkYjBiNWQwNGFkYTI0N2Q5ZTYwYTBlZGVhYjM5ZGM3YjM4NDc1YzZkY2M3NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L_tGgHx8nlhbvSqlKrLRS_GsM4d-BMTBuAGbonitF14) 试了另一台服务器，能稳定触发

只要修改远程端口就无法访问吗？ 
安全组开了没
Docker 配置页面的配置看一下

**Comment by long-dotcom** [comment]
> > > 没有这个限制的 截图一下你的配置吧
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/72112301/379647755-ffebe15a-f438-4ac6-9eb2-69af5171ed6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NTUwODQsIm5iZiI6MTcyOTc1NDc4NCwicGF0aCI6Ii83MjExMjMwMS8zNzk2NDc3NTUtZmZlYmUxNWEtZjQzOC00YWM2LTllYjItNjlhZjUxNzFlZDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA3MjYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MWJhMTljY2YxYmM1YzYzMmZkYjBiNWQwNGFkYTI0N2Q5ZTYwYTBlZGVhYjM5ZGM3YjM4NDc1YzZkY2M3NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L_tGgHx8nlhbvSqlKrLRS_GsM4d-BMTBuAGbonitF14) 试了另一台服务器，能稳定触发
> 
> 只要修改远程端口就无法访问吗？ 安全组开了没 Docker 配置页面的配置看一下

乌龙了，恰好两台服务器的的服务商那边安全组都没开到那个端口，
