### ISSUE TITLE
[BUG]1.10.20 进程守护无法点开日志

### ISSUE THREAD

**Issue by kuilei0926** [1Panel-dev/1Panel#6834]
### 1Panel 版本

1.10.20

### 问题描述

![微信截图_20241024143932](https://github.com/user-attachments/assets/f203c122-6a99-4258-9d6f-13f54baba74b)

### 重现步骤

![微信截图_20241024143932](https://github.com/user-attachments/assets/4dc7f277-4775-4bd6-96fb-3ff1a583863b)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下这个问题。

**Comment by wanghe-fit2cloud** [comment]
## 本地已复现并修复了该问题，修复后的安装包下载地址和修复步骤如下：

### 1. 下载修复后的安装包

```shell
cd /usr/local/bin
wget https://resource.fit2cloud.com/1panel/package/stable/v1.10.20-lts/release/1panel-v1.10.20-lts-linux-amd64.tar.gz
tar zxvf 1panel-v1.10.20-lts-linux-amd64.tar.gz
```

### 2. 替换1panel二进制文件

```shell
mv 1panel 1panel.bak
cp 1panel-v1.10.20-lts-linux-amd64/1panel .
```

### 3. 重启1panel

```shell
1pctl restart 
```

### 4. 查看1panel状态

```shell
1pctl status
```

**Comment by wanghe-fit2cloud** [comment]
也可以使用 `1pctl restore` 命令恢复到上一个稳定版本，再来升级 1Panel。
