### ISSUE TITLE
[BUG] 終端 ssh 連線時填入訊息錯誤

### ISSUE THREAD

**Issue by Kayxue** [1Panel-dev/1Panel#6835]
### 1Panel 版本

1.10.20 lts

### 问题描述

繼 https://github.com/1Panel-dev/1Panel/discussions/6830
外部 ssh 可以登入，但從 1Panel 終端登入頻頻出錯
經檢查 SSH 管理裡面的登入日誌，才發現本面板的終端疑似在連 ssh 時完全無視使用者填寫的使用者名稱，並永遠以 user 為使用者名稱進行連線，故提此 issue 請求修正

### 重现步骤

1. 於 Ubuntu Server 24.04.1 上安裝 1Panel
2. 設定 SSH 使外部可以連線
3. 使用外部終端確認可以連上後，回到 1Panel 內建終端，並輸入使用者名稱與密碼進行連線
4. 面板會提示「連接不可用」，前往 SSH 管理 -> 登入日誌就可以看到了

### 期待的正确结果

可以以指定使用者名稱與密碼進行連線

### 附加信息

在該 Discussion 能提供的已經提供了

**Comment by wanghe-fit2cloud** [comment]
> 才发现本面板的终端疑似在连ssh时完全无视用户填写的用户名称，并永远以用户为用户名称进行连线，故提此问题 请求修改

本地未复现这个问题。
先关闭该 issue 了，继续在 [Discussion](https://github.com/1Panel-dev/1Panel/discussions/6830) 中讨论该问题。
