### ISSUE TITLE
[BUG] 编辑Docker仓库导致Docker卡死

### ISSUE THREAD

**Issue by xihan123** [1Panel-dev/1Panel#6839]
### 联系方式

srxqzxs@vip.qq.com

### 1Panel 版本

v1.10.20-lts

### 问题描述

stderr: Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xeu docker.service" for details.

出现该问题后要手动把容器-仓库里面以及配置中的私有仓库同时删除并重启服务器才可以恢复Docker

### 重现步骤

1.容器-仓库，随便添加一个自定义私有仓库
2.编辑刚刚创建的仓库并保存

### 期待的正确结果

正常保存并且Docker状态正常

**Comment by wanghe-fit2cloud** [comment]
最新版本已支持对 daemon.json 文件的校验，如果配置文件异常，将不会重启 Docker。

可以贴一下异常的 daemon.json 文件内容，并使用 `dockerd --validate` 命令手动检查是否存在配置问题。
> 刚刚在本地环境添加 Harbor 仓库未复现该问题。

**Comment by xihan123** [comment]
我添加的是"xxx/xihan123"后面带了用户名，第一次添加进去的可以正常用，但是一编辑就会出问题

**Comment by wanghe-fit2cloud** [comment]
> 我添加的是"xxx/xihan123"后面带了用户名，第一次添加进去的可以正常用，但是一编辑就会出问题

编辑后的 daemon.json 文件内容麻烦提供一下。
> 使用 `dockerd --validate` 命令有提示异常吗？

**Comment by xihan123** [comment]
> > 我添加的是"xxx/xihan123"后面带了用户名，第一次添加进去的可以正常用，但是一编辑就会出问题
> 
> 编辑后的 daemon.json 文件内容麻烦提供一下。
> 
> > 使用 `dockerd --validate` 命令有提示异常吗？

使用 `dockerd --validate` 提示`configuration OK`
```json
{
	"insecure-registries": [
		"xxx/xihan123"
	],
	"registry-mirrors": [
		"https://docker.1panel.live"
	]
}
```

补充一下是修改后点确认的时候就已经提示异常并且docker卡死了
![0](https://github.com/user-attachments/assets/4d469a5a-a96a-4ec0-9368-3c98202a9510)

**Comment by xihan123** [comment]
重新试了一下发现是点那个编辑后修改的内容会直接作用到私有仓库去，但是没有保存成功内容却过去了

**Comment by wanghe-fit2cloud** [comment]
麻烦添加一下企业微信，远程你环境定位一下这个问题。
![image](https://github.com/user-attachments/assets/297648cc-94fe-4544-bf12-aceebae786d9)

**Comment by xihan123** [comment]
> 麻烦添加一下企业微信，远程你环境定位一下这个问题。 ![image](https://private-user-images.githubusercontent.com/73214554/378290047-297648cc-94fe-4544-bf12-aceebae786d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODI5NTUsIm5iZiI6MTcyOTc4MjY1NSwicGF0aCI6Ii83MzIxNDU1NC8zNzgyOTAwNDctMjk3NjQ4Y2MtOTRmZS00NTQ0LWJmMTItYWNlZWJhZTc4NmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDE1MTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMzA4YmRlYzUxN2E0MGVkNzZlMzgwZmZmNGM4MzAwMGQzODg3NzAyMDYyYWRmOWQ2NmIyZTgyNjkzODIxOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ORmHUxzA8LUXGBSMujlCpxypvh_LLA17Pt_iHeRu1W0)

加了

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
