### ISSUE TITLE
[BUG] WAF默认规则错误拦截了Halo请求

### ISSUE THREAD

**Issue by QingFeng-awa** [1Panel-dev/1Panel#6840]
### 1Panel 版本

专业版 1.10.20LTS

### 问题描述

1Panel专业版的默认规则错误拦截Halo保存页面的操作。
比如这里的图片是错误拦截了Halo保存自定义页面的操作。
![错误拦截的请求](https://github.com/user-attachments/assets/51d13b96-d1b6-4a1b-bb9c-43deaa6320ca)

### 重现步骤

在对应Halo站点已开启WAF的情况下编辑Halo站点中的自定义页面,随后保存。

**Comment by wanghe-fit2cloud** [comment]
后续版本将考虑支持应用模板白名单等功能。
具体问题的讨论已汇总至此 issue：https://github.com/1Panel-dev/1Panel/issues/4636
