### ISSUE TITLE
[BUG] 日志显示内容不正确

### ISSUE THREAD

**Issue by QingFeng-awa** [1Panel-dev/1Panel#6841]
### 1Panel 版本

专业版 1.10.20LTS

### 问题描述

运行环境删除日志显示被删除运行环境的名称不正确。
![image](https://github.com/user-attachments/assets/0cc2ada3-c505-479f-b6f7-6a0cac585d9a)
如图,这里被删除的运行环境名称是`Flarum`。
并且我删除的是运行环境,也不是网站。

### 重现步骤

新建运行环境,关联网站,删除网站,删除运行环境。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本修复上述问题。
> 删除运行环境网站时，会在 `应用商店` - `已安装` 页面移除对应应用，但不会删除已创建的运行环境。

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
