### ISSUE TITLE
[FEATURE] 我安装了最新版1panel docker版本是20.10.9 导致我使用镜像ubuntu22.04出问题

### ISSUE THREAD

**Issue by ChanXing2023** [1Panel-dev/1Panel#6844]
### 1Panel 版本

v1.10-19-lts

### 请描述您的需求或者改进建议

1panel如何操作才可以让docker版本升级到最新版本。

### 请描述你建议的实现方案

想要可以控制docker版本号

**Comment by wanghe-fit2cloud** [comment]
> 1Panel 如何操作才可以让 docker 版本升级到最新版本。

1、如果服务器是新环境，可先手动卸载 Docker，再安装 1Panel，此时脚本会自动安装最新版本。
2、也可以尝试使用下面的脚本来升级 docker
```shell
bash <(curl -sSL https://linuxmirrors.cn/docker.sh)
```
