### ISSUE TITLE
[BUG] 终端显示滚轮滚动优化

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#6847]
### 1Panel 版本

v1.10.20-lts

### 问题描述

终端滚动问题：

![20241025-220256](https://github.com/user-attachments/assets/54de72b1-bc1c-48e9-bcfc-c9b6a93074f5)

### 重现步骤

当前终端如果显示内容超过一页，鼠标滚轮滚动却只有最上和最下两种状态，精细控制滚动条只能用鼠标，较为不便。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们计划在 v2 版本支持终端设置功能，相关问题的讨论统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/3406
