### ISSUE TITLE
[Feat] 期望将左上Logo背景换成黑金色或允许自定义

### ISSUE THREAD

**Issue by QingFeng-awa** [1Panel-dev/1Panel#6848]
### 1Panel 版本

专业版 1.10.20LTS

### 请描述您的需求或者改进建议

目前黑金主题左侧导航栏有一个蓝色的背景
![image](https://github.com/user-attachments/assets/d3eb8cd3-3eb6-4ca1-ad50-6b0a39fe0c98)
我认为这个颜色与黑金主题的主题色有些不搭,期望将这块换成黑金色或允许用户自定义。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，顶部 Logo 目前为带蓝黑色背景的定制图片，后续版本可能会考虑支持用户自定义。

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
