### ISSUE TITLE
[BUG]代码编辑器修改后保存不了

### ISSUE THREAD

**Issue by sancome** [1Panel-dev/1Panel#6852]
### 联系方式

QQ

### 1Panel 版本

v1.10.20-lts

### 问题描述

用代码编辑器修改文件后点击没有反应，在控制台看到有个报错，如图。
尝试重启服务器，重启后第一次修改可以正常保存，第二次修改就又报错了。
![编辑器报错](https://github.com/user-attachments/assets/7be03f60-fb84-4d1e-b0cc-75615cd772a2)

### 重现步骤

可能是最新版本引入的bug

**Comment by QingFeng-awa** [comment]
`err_connection_reset`是你网络问题
