### ISSUE TITLE
[FEATURE]OpenResty安装不上，无法管理网站

### ISSUE THREAD

**Issue by 365v** [1Panel-dev/1Panel#6856]
### 1Panel 版本

v1.10.20-lts

### 请描述您的需求或者改进建议

折腾了半天，OpenResty安装不上。
![image](https://github.com/user-attachments/assets/ff6e02af-1643-4ce5-bd52-97e5bef4b248)
![image](https://github.com/user-attachments/assets/daab7dfa-4bc5-4e90-9fc2-2c80133429d9)
![image](https://github.com/user-attachments/assets/eada32ea-1738-4ed8-a9da-d394d78a3d6b)
![image](https://github.com/user-attachments/assets/f291b111-19dc-4adc-87f6-53a595c8d9fd)

**Comment by QingFeng-awa** [comment]
这不应该作为功能建议类型的issue发布
https://bbs.fit2cloud.com/t/topic/5065
