### ISSUE TITLE
[Feat] 更简洁的登录页面

### ISSUE THREAD

**Issue by QingFeng-awa** [1Panel-dev/1Panel#6859]
### 1Panel 版本

专业版 1.10.20LTS

### 请描述您的需求或者改进建议

提供一个更简洁的登录页面,可在`/xpack/setting`决定是否启用。

### 请描述你建议的实现方案

将登录页面表单移动至中间,移除图片并将背景改为纯色(颜色参考:默认主题#DBE4F8,黑金主题#EFD3C1)。
可以参考一下宝塔那种样式。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，关于登录页面的需求，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/6858
