### ISSUE TITLE
[BUG]OpenResty安装不上

### ISSUE THREAD

**Issue by 365v** [1Panel-dev/1Panel#6860]
### 1Panel 版本

v1.10.20-lts

### 问题描述

折腾了半天，OpenResty安装不上。
![image](https://github.com/user-attachments/assets/ff6e02af-1643-4ce5-bd52-97e5bef4b248)
![image](https://github.com/user-attachments/assets/daab7dfa-4bc5-4e90-9fc2-2c80133429d9)

### 重现步骤

![image](https://github.com/user-attachments/assets/eada32ea-1738-4ed8-a9da-d394d78a3d6b)
![image](https://github.com/user-attachments/assets/f291b111-19dc-4adc-87f6-53a595c8d9fd)

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/6856
