### ISSUE TITLE
[BUG]面板域名访问已经配置了证书，但是配置页面展示相关信息不正确

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#6863]
### 联系方式

niujinkai@vip.qq.com

### 1Panel 版本

v1.10.20-lts

### 问题描述

![image](https://github.com/user-attachments/assets/e152bc91-9f70-47ca-a2e6-1f000de5bff8)
如上图，实际上配置了域名对应的证书，可是此处现实的还是异常。

### 重现步骤

配置SSL证书 之后存在
![image](https://github.com/user-attachments/assets/d225530c-5951-4a43-b85f-f48962d18507)

### 期待的正确结果

正常应该现实域名和IP 包括证书到期时间

**Comment by ssongliu** [comment]
感谢反馈，麻烦在 【面板设置 - 安全】 截图看看下面接口的返回信息

api/v1/settings/ssl/info

**Comment by ghost** [comment]
> 感谢反馈，麻烦在 【面板设置 - 安全】 截图看看下面接口的返回信息
> 
> api/v1/settings/ssl/info

![image](https://github.com/user-attachments/assets/ab34fdd3-6752-446f-9f66-25b66afc0cc7)

如图 返回的数据为空

**Comment by ghost** [comment]
> > 感谢反馈，麻烦在 【面板设置 - 安全】 截图看看下面接口的返回信息
> > api/v1/settings/ssl/info
> 如图 返回的数据为空

@ssongliu

**Comment by ssongliu** [comment]
感谢，下个版本优化导入证书过期时间显示

**Comment by ghost** [comment]
> 感谢，下个版本优化导入证书过期时间显示

好的 十分感谢

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
