### ISSUE TITLE
[FEATURE] 证书申请增加ip证书申请功能

### ISSUE THREAD

**Issue by maoxianfly** [1Panel-dev/1Panel#6869]
### 1Panel 版本

v1.10.15-lts

### 请描述您的需求或者改进建议

证书申请的时候，增加ip证书申请功能，详细见：
https://github.com/acmesh-official/acme.sh/wiki/ipcert

### 请描述你建议的实现方案

实现见：https://github.com/acmesh-official/acme.sh/wiki/ipcert

**Comment by zhengkunwang223** [comment]
支持 Ip 证书的发行商已经停服 目前 acme.sh 支持的 CA 证书不包含 IP 证书 
![image](https://github.com/user-attachments/assets/86a68e47-ccbf-40e8-b6e5-85c99b35794c)
https://github.com/acmesh-official/acme.sh/wiki/CA
