### ISSUE TITLE
[FEATURE] 编辑器 请支持 以何种编码保存.

### ISSUE THREAD

**Issue by AtlantisDe** [1Panel-dev/1Panel#6875]
### 1Panel 版本

v1.10.20-lts

### 编辑器 请支持 以何种编码保存.

<img width="574" alt="8a67798498eee830b79ee741930abf0" src="https://github.com/user-attachments/assets/564ef3b7-dc33-419a-a48a-41445b831a2f">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复需求 https://github.com/1Panel-dev/1Panel/issues/5697
