### ISSUE TITLE
[FEATURE]系统监控是否能增加进程的占用

### ISSUE THREAD

**Issue by seth-shi** [1Panel-dev/1Panel#6885]
### 1Panel 版本

v1.10.20-lts

### 请描述您的需求或者改进建议

监控有时候死机了重启, 想排查是哪个进程占用, 但是现在只能看到 CPU 占用,无法查看具体是哪个进程

**Comment by wanghe-fit2cloud** [comment]
上述需求是希望在 1Panel 系统中增加查看历史进程占用的功能吗？

**Comment by seth-shi** [comment]
嗯嗯
可以有一个几秒一次快照

**Comment by wanghe-fit2cloud** [comment]
> 嗯嗯 可以有一个几秒一次快照

我们先在本地调研一下，看看是否有可行的方案。

**Comment by seth-shi** [comment]
好的, 感谢
