### ISSUE TITLE
[BUG] web页面进入容器日志后全屏查看后关闭页面，左侧导航栏消失

### ISSUE THREAD

**Issue by joker1911** [1Panel-dev/1Panel#6889]
### 1Panel 版本

v1.10.20-lts

### 问题描述

 web页面进入容器日志后全屏查看后关闭页面，左侧导航栏消失

### 重现步骤

 web页面进入容器日志后全屏查看后关闭页面，左侧导航栏消失

### 期待的正确结果

关闭页面重新打开后，导航栏不消失

**Comment by ssongliu** [comment]
感谢反馈，后续版本优化

**Comment by QingFeng-awa** [comment]
有什么临时解决方法吗,我也遇到这个问题了,重启面板也不行

**Comment by wanghe-fit2cloud** [comment]
> 有什么临时解决方法吗,我也遇到这个问题了,重启面板也不行

试一下更换其他浏览器或者清空浏览器缓存。

**Comment by joker1911** [comment]
> 有什么临时解决方法吗，我也遇到了这个问题，重启面板也行

进入1panel的
/containers/container这个网址，然后打开个容器全屏展示一下就好了

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
