### ISSUE TITLE
[QUESTION]创建访问URL的计划任务，执行之后全部提示：监控密钥不正确

### ISSUE THREAD

**Issue by cyril-cheng** [1Panel-dev/1Panel#689]
### 请描述您的问题

创建访问URL的计划任务，执行之后全部提示：监控密钥不正确。
用宝塔执行一切正常。
![image](https://user-images.githubusercontent.com/49748357/232722028-ec7a64c1-bad8-4d20-b54e-b260b416b14a.png)
![image](https://user-images.githubusercontent.com/49748357/232722415-3abd5957-d798-4b26-bf4f-8d1f52475130.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，能简单描述一下您输入的 url 吗？我们在本地环境复现一下该问题。

**Comment by cyril-cheng** [comment]
> 感谢反馈，能简单描述一下您输入的 url 吗？我们在本地环境复现一下该问题。

项目的监控任务，统计每日订单的。结构大概是这样"https://www.a.com/cron.php?do=order&key=监控密钥"

**Comment by cyril-cheng** [comment]
> 可以在机器上面手动 curl [https://www.a.com/cron.php?do=order&key="监控密钥](https://www.a.com/cron.php?do=order&key=%22%E7%9B%91%E6%8E%A7%E5%AF%86%E9%92%A5)" 试一下吗

在本机手动试显示：监控密钥不正确；换一台其他的VPS试就是：执行成功。就像主题的两张图片显示的那样。

**Comment by ssongliu** [comment]
宝塔和 1panel 是装在同一个机器上面吗？ 手动 curl 不行，宝塔可以正常执行吗？

**Comment by cyril-cheng** [comment]
> 宝塔和 1panel 是装在同一个机器上面吗？ 手动 curl 不行，宝塔可以正常执行吗？

不是一个机器上，但都是在终端curl试了的，网站是部署在1panel上的。同时copy的网址，绝对保证执行语句一模一样。

**Comment by ssongliu** [comment]
> > 宝塔和 1panel 是装在同一个机器上面吗？ 手动 curl 不行，宝塔可以正常执行吗？
> 
> 不是一个机器上，但都是在终端curl试了的，网站是部署在1panel上的。同时copy的网址，绝对保证执行语句一模一样。

你在 1panel 的群里吗？在的话加一下我吧
![image](https://user-images.githubusercontent.com/73214554/233885498-ae35b357-a183-49d4-b3af-1e50d6c12c7f.png)

**Comment by cyril-cheng** [comment]
> > > 宝塔和 1panel 是装在同一个机器上面吗？ 手动 curl 不行，宝塔可以正常执行吗？
> > 
> > 
> > 不是一个机器上，但都是在终端curl试了的，网站是部署在1panel上的。同时copy的网址，绝对保证执行语句一模一样。
> 
> 你在 1panel 的群里吗？在的话加一下我吧 ![image](https://user-images.githubusercontent.com/73214554/233885498-ae35b357-a183-49d4-b3af-1e50d6c12c7f.png)

找到原因了

root@xxx:~# curl https://www.example.com/cron.php?do=order&key=xxxxxx
[1] 338532
root@xxx:~# 监控密钥不正确
[1]+  Done                    curl https://www.example.com/cron.php?do=order
root@xxx:~# 
root@xxx:~# curl "https://www.example.com/cron.php?do=order&key=xxxxxx"
订单统计与清理任务今日已完成
root@xxx:~# 

curl后的网址如果不用引号括起来，系统会把后面的key给删除掉，应该是linux系统的原因 。但是有点奇怪  我1panel和宝塔都是debian11的系统，为啥宝塔可以完整执行？
