### ISSUE TITLE
[FEATURE] 建议简化反代操作并添加一个在安装应用的时候直接添加反代和申请证书的功能

### ISSUE THREAD

**Issue by yanglinzhi** [1Panel-dev/1Panel#6898]
### 1Panel 版本

v1.10.20-lts

### 请描述您的需求或者改进建议

之前用过雷池的反代，然后使用专业版反代的时候老是出现各种问题，但是雷池直接一步到位，建议优化一下反代逻辑，另外老是反代443端口时老是提示被占用，雷池则不会出现，希望可以在安装应用的时候可以添加反代和申请证书的选项，一步到位，省去一些步骤

**Comment by zhengkunwang223** [comment]
1.什么情况需要反代 443 端口呢 如果是要反代其他 web 服务 可以直接反代 https://IP地址
2.后续会增加多个 web 项目的一键部署 和 创建网站直接选择证书

**Comment by yanglinzhi** [comment]
比如我有一个域名，我希望只通过开放443端口，就可以访问到我机器内的全部应用，通过不同的子域名来实现，但是当我在代理的主域名加端口填写xxx.xxxx.com:443时，它会提示被占用，无法直接在反代界面选择证书，只能先创建http协议，然后在配置里开启https，步骤略有繁琐，我觉得可以借鉴一下其他的反代配置，我自己想的修改方案是这样的
![image](https://github.com/user-attachments/assets/00a9288f-3f2c-4972-a7e2-060a75e6be5a)

**Comment by zhengkunwang223** [comment]
> 比如我有一个域名，我希望只通过开放443端口，就可以访问到我机器内的全部应用，通过不同的子域名来实现，但是当我在代理的主域名加端口填写xxx.xxxx.com:443时，它会提示被占用，无法直接在反代界面选择证书，只能先创建http协议，然后在配置里开启https，步骤略有繁琐，我觉得可以借鉴一下其他的反代配置，我自己想的修改方案是这样的 ![image](https://private-user-images.githubusercontent.com/106936942/381483831-00a9288f-3f2c-4972-a7e2-060a75e6be5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyODE2OTMsIm5iZiI6MTczMDI4MTM5MywicGF0aCI6Ii8xMDY5MzY5NDIvMzgxNDgzODMxLTAwYTkyODhmLTNmMmMtNDk3Mi1hN2UyLTA2MGE3NWU2YmU1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQwOTQzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjlkMGY1MmE1M2I4ZWZkNzM1ZmY1YjU3MzU0OTZjZTBkMzQxZTEyM2VhMTA2MWFjNTZjMTMzMjU5NTY1N2YyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Q7BZi24sjWqhoCtttD_FNA11hbTtpro3DNsPE6qh7fo)

你说的这个 我们会在 v2 版本做，创建网站的时候可以直接选择证书并开启 https

**Comment by zhengkunwang223** [comment]
关注这个 issue https://github.com/1Panel-dev/1Panel/issues/4462

**Comment by chixq** [comment]
这个功能我觉得挺好的。
我现在就是有个根域名 *.test.cn ，做了泛域名解析到 1Panel 服务器。

我应用市场的应用安装后，可以直接一键配置 app1.test.cn，申请绑定 ssl 证书。

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I think this function is quite good.
I currently have a root domain name *.test.cn and have done pan-domain name resolution to the 1Panel server.

After the application in my app market is installed, you can directly configure app1.test.cn with one click and apply to bind the SSL certificate.
