### ISSUE TITLE
[BUG]清空网站日志时的闪烁问题

### ISSUE THREAD

**Issue by igophper** [1Panel-dev/1Panel#6904]
### 1Panel 版本

v1.10.20-lts

### 问题描述

https://github.com/user-attachments/assets/22114a05-2006-47f9-a445-eadffe6ee67f

### 重现步骤

日志审计-》网站日志-》清空日志

### 期待的正确结果

无闪烁

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
