### ISSUE TITLE
[FEATURE]应用商店希望增加FreeIPA

### ISSUE THREAD

**Issue by Lotusrootsoup** [1Panel-dev/1Panel#6906]
### 1Panel 版本

v1.10.20-lts

### 请描述您的需求或者改进建议

应用商店希望增加FreeIPA，这是由红帽开发LDAP系统支持WEB面板管理，虽然现在应用商店有OpenLDAP，但是OpenLDAP不支持WEB面板管理真的很难用。
GitHub：https://github.com/freeipa/freeipa
Docker：https://hub.docker.com/r/freeipa/freeipa-server/
Docs：https://github.com/freeipa/freeipa-container

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，我们主要以项目的 Star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有超 1 万 Star 的开源项目，感谢您的理解。

> 你可以将需求反馈给 [第三方仓库（由社区用户维护）](https://github.com/okxlin/appstore)。
