### ISSUE TITLE
[FEATURE] 开机启动任务

### ISSUE THREAD

**Issue by Await-d** [1Panel-dev/1Panel#6907]
### 1Panel 版本

v1.10.20-lts

### 请描述您的需求或者改进建议

之前看到论坛里面提到，开机自启动任务，说后续会添加，快半年了 ，这个功能还会不会加上去

**Comment by wanghe-fit2cloud** [comment]
近期暂无计划支持此需求，目前的重点仍放在用户反馈较多、使用频率较高的功能上，望理解。
如有针对开机启动任务的有效实现方案，欢迎分享，以便后续适配。

**Comment by wanghe-fit2cloud** [comment]
同 issue https://github.com/1Panel-dev/1Panel/issues/3969
