### ISSUE TITLE
[FEATURE] 希望商店多增加点 除logto外 单点登录提供商的应用

### ISSUE THREAD

**Issue by ByZhouhang** [1Panel-dev/1Panel#6913]
### 1Panel 版本

xx

### 请描述您的需求或者改进建议

在小公司，不知道外面公司都用的啥，那个比较好，群里有人回复说有用了  MaxKey      keycloak 这种

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，关于单点登录应用的需求，统一反馈到该 issue https://github.com/1Panel-dev/1Panel/issues/2013
