### ISSUE TITLE
[FEATURE] 概览-状态页面，磁盘状态数量重复太多了

### ISSUE THREAD

**Issue by YaKun9** [1Panel-dev/1Panel#6917]
### 1Panel 版本

v1.10.20-lts

### 请描述您的需求或者改进建议

设备是群晖DS920+，基本上是把每个应用的挂载都展示出来了。
建议：**去重** 或者 默认收起

![image](https://github.com/user-attachments/assets/d1b789ec-0b9e-472a-acde-b0b3404da384)
![image](https://github.com/user-attachments/assets/688ba428-2611-4e99-999b-b6daf9561d7e)

### 请描述你建议的实现方案

**去重** 或者 默认收起

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，目前我们确实尚未完全适配群晖系统，但会在后续版本中持续优化。

在当前版本中，你可以添加一下好友，协助我们远程查看你的环境。
![image](https://github.com/user-attachments/assets/297648cc-94fe-4544-bf12-aceebae786d9)

**Comment by YaKun9** [comment]
默认收起就可以了。

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
