### ISSUE TITLE
[FEATURE] 希望添加Caddy作为网站服务器

### ISSUE THREAD

**Issue by XZB-1248** [1Panel-dev/1Panel#692]
### 1Panel 版本

1.1.0

### 请描述您的需求或者改进建议

如题，我的网站目前使用的就是caddy，运行一直都很正常
个人感觉caddy已经具备了作为网站服务器的资质，可以考虑将caddy添加为可用的网站服务器

### 附加信息

https://caddyserver.com/

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。我们后续版本可能会考虑上述需求。
