### ISSUE TITLE
[FEATURE]  增加dotnet  core 运行环境，方便C#  开发人员从 windows系统迁移linux ，docker不熟

### ISSUE THREAD

**Issue by ByZhouhang** [1Panel-dev/1Panel#6920]
### 1Panel 版本

xx

### 请描述您的需求或者改进建议

增加dotnet  core 运行环境，方便C#  开发人员从 windows系统迁移linux ，docker不熟，一时半会不会用docker-compose
也方便我在群里给群友安利

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，关于运行环境需求的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/748
