### ISSUE TITLE
[FEATURE]应用商店添加Huginn-自动化工作流工具

### ISSUE THREAD

**Issue by eiloogs** [1Panel-dev/1Panel#6927]
### 1Panel 版本

v1.10.20

### 请描述您的需求或者改进建议

Github 43.3K 
项目地址https://github.com/huginn/huginn

### 请描述你建议的实现方案

建议添加

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期上架该应用。

**Comment by wanghe-fit2cloud** [comment]
应用已上架，进入 `应用商店` 列表，点击右上角的【更新应用列表】按钮，待同步完成后即可安装应用。
