### ISSUE TITLE
[FEATURE]多台主机批量配置问题

### ISSUE THREAD

**Issue by feeops** [1Panel-dev/1Panel#6935]
### 1Panel 版本

1.20

### 请描述您的需求或者改进建议

我有60台主机，想批量安装1Panel，并统一设置访问端口、用户名、密码，docker仓库凭据等~
1Panel支持命令行配置，或者配置文件统一所有实例的配置么？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈！后续版本计划支持多主机管理功能，详见 [issue #2692](https://github.com/1Panel-dev/1Panel/issues/2692)。

至于批量安装和配置的需求，可能在中短期内暂不考虑，感谢理解。

**Comment by feeops** [comment]
那现在1Panel的配置是放在哪里？有配置文件吗？

**Comment by wanghe-fit2cloud** [comment]
> 那现在1Panel的配置是放在哪里？有配置文件吗？

1Panel 正式版本没有外部配置文件，安装仅涉及 1panel 二进制文件、1pctl 命令行工具和 1panel.service 三个文件。

**Comment by feeops** [comment]
> > 那现在1Panel的配置是放在哪里？有配置文件吗？
> 
> 1Panel 正式版本没有外部配置文件，安装仅涉及 1panel 二进制文件、1pctl 命令行工具和 1panel.service 三个文件。

那重启机器的时候怎么保证配置不会丢失呢？

**Comment by wanghe-fit2cloud** [comment]
> > > 那现在1Panel的配置是放在哪里？有配置文件吗？
> > 
> > 
> > 1Panel 正式版本没有外部配置文件，安装仅涉及 1panel 二进制文件、1pctl 命令行工具和 1panel.service 三个文件。
> 
> 那重启机器的时候怎么保证配置不会丢失呢？

为了实现配置在 `面板设置` 页面的可视化操作，数据记录在了数据库中。

**Comment by feeops** [comment]
> > > > 那现在1Panel的配置是放在哪里？有配置文件吗？
> > > 
> > > 
> > > 1Panel 正式版本没有外部配置文件，安装仅涉及 1panel 二进制文件、1pctl 命令行工具和 1panel.service 三个文件。
> > 
> > 
> > 那重启机器的时候怎么保证配置不会丢失呢？
> 
> 为了实现配置在 `面板设置` 页面的可视化操作，数据记录在了数据库中。

找到了，是这个文件/opt/1Panel.db

**Comment by JAINKRE** [comment]
> > > > > 那现在1Panel的配置是放在哪里？有配置文件吗？
> > > > 
> > > > 
> > > > 1Panel 正式版本没有外部配置文件，安装仅涉及 1panel 二进制文件、1pctl 命令行工具和 1panel.service 三个文件。
> > > 
> > > 
> > > 那重启机器的时候怎么保证配置不会丢失呢？
> > 
> > 
> > 为了实现配置在 `面板设置` 页面的可视化操作，数据记录在了数据库中。
> 
> 找到了，是这个文件/opt/1Panel.db

朋友解决多主机安装的问题了吗？我最近也有好多台要统一安装，挺麻烦的。如果直接修改db然后复制到不同的机器上会不会生效呢？

**Comment by feeops** [comment]
> > > > > > 那现在1Panel的配置是放在哪里？有配置文件吗？
> > > > > 
> > > > > 
> > > > > 1Panel 正式版本没有外部配置文件，安装仅涉及 1panel 二进制文件、1pctl 命令行工具和 1panel.service 三个文件。
> > > > 
> > > > 
> > > > 那重启机器的时候怎么保证配置不会丢失呢？
> > > 
> > > 
> > > 为了实现配置在 `面板设置` 页面的可视化操作，数据记录在了数据库中。
> > 
> > 
> > 找到了，是这个文件/opt/1Panel.db
> 
> 朋友解决多主机安装的问题了吗？我最近也有好多台要统一安装，挺麻烦的。如果直接修改db然后复制到不同的机器上会不会生效呢？

理论上是生效的，我目前是通过操作系统镜像功能来实现的
