### ISSUE TITLE
[BUG]面板地址突然无法访问

### ISSUE THREAD

**Issue by lightzero** [1Panel-dev/1Panel#6938]
### 1Panel 版本

V1.10.20-lts

### 问题描述

部署环境，本地局域网虚拟机服务器
启动服务器后，过一会儿，面板网址无法访问，ssh也登录不上。
查看面板服务正常，docker容器正常，但局域网无法访问。
增加了一个网站也无法访问。
此时，ping服务器正常，将防火墙关闭后，也无法访问。重启面板服务也不行

### 重现步骤

暂未发现，自动重现

### 期待的正确结果

正确访问

### 附加信息

![image](https://github.com/user-attachments/assets/950f50d7-956f-41b0-8823-53ea0f4db8c4)

**Comment by wanghe-fit2cloud** [comment]
1、`1pctl status` 和 `journalctl -u 1panel.service -exf` 两条命令可以查看 1Panel 系统日志
2、`netstat -ntlp` 看一下截图
3、`curl 127.0.0.1:端口` 看一下结果，提供截图
