### ISSUE TITLE
[BUG]SQL 注入防御错误识别参数值

### ISSUE THREAD

**Issue by ITsPro-CN** [1Panel-dev/1Panel#6945]
### 联系方式

凌霞News5微信群-Pro

### 1Panel 版本

1.10.20

### 问题描述

WAF-默认规则-其他-SQL 注入防御，错误的识别了参数值后拦截了请求
命中规则：SQL 注入
匹配值：(2024-2025-1)-00272003-TD0177-2
这个值本身应该也达不到SQL注入的参数要求吧？也没有等号和分号。排查了一下参数规则里的正则不会匹配到这个值，通过测试确定是“其他-SQL 注入防御”这里进行了拦截。

### 重现步骤

任意POST请求携带任意一个参数值为(2024-2025-1)-00272003-TD0177-2

### 期待的正确结果

排查SQL注入的拦截规则，该参数值不能匹配SQL注入拦截规则，应不拦截请求

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by zhengkunwang223** [comment]
没有复现 能否提供环境？

**Comment by zhengkunwang223** [comment]
已复现 由于是触发了 SQL 注入特征 暂时无法处理
