### ISSUE TITLE
[FEATURE]应用商店里面没有zabbix可以用！！！！

### ISSUE THREAD

**Issue by 15281143266** [1Panel-dev/1Panel#6948]
### 1Panel 版本

v1.10.18-lts

### 请描述您的需求或者改进建议

虽然现在很多都用普罗米修斯了，但是zabbix还是有需求的，希望官方在应用商店能够上架zabbix

### 请描述你建议的实现方案

虽然现在很多都用普罗米修斯了，但是zabbix还是有需求的，希望官方在应用商店能够上架zabbix

### 附加信息

虽然现在很多都用普罗米修斯了，但是zabbix还是有需求的，希望官方在应用商店能够上架zabbix

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。目前 [第三方商店](https://github.com/okxlin/appstore/tree/localApps/apps/zabbix-server) 已支持 Zabbix，由于 Zabbix 涉及 server 和 agent 组件，每个组件包含多个容器，不便于后期在应用商店中维护，建议通过第三方商店以本地应用方式使用。
