### ISSUE TITLE
[FEATURE]备份的时候不需要填压缩密码，改成填备注就好了

### ISSUE THREAD

**Issue by docker-master** [1Panel-dev/1Panel#6952]
### 1Panel 版本

v1.10.20-lts

### 请描述您的需求或者改进建议

备份的时候，填一个备注，方便知道自己的应用备份了什么，应用太多了有时候记不住，把填压缩密码那个改了也行，好像不太需要
![image](https://github.com/user-attachments/assets/4292224d-fefe-47c5-88b2-1808dc5fc7e9)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持该需求。

**Comment by wanghe-fit2cloud** [comment]
重复 https://github.com/1Panel-dev/1Panel/issues/4735
