### ISSUE TITLE
[BUG]openResty的端口不是默认80和443的时候的提示造成页面布局不美观

### ISSUE THREAD

**Issue by dengxiwang** [1Panel-dev/1Panel#6953]
### 1Panel 版本

v1.10.20-lts

### 问题描述

这个提示，OpenResty 默认 HTTP 端口：8080 HTTPS 端口 ：8443，可能影响网站域名访问和 HTTPS 强制跳转，这一块区域没有垂直居中！
![20241105140640](https://github.com/user-attachments/assets/8ba34646-3d63-4673-beef-e3c509809202)

### 重现步骤

如图所示

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
