### ISSUE TITLE
[FEATURE]关于自动部署的问题

### ISSUE THREAD

**Issue by swift-fs** [1Panel-dev/1Panel#6958]
### 1Panel 版本

1.10.20

### 请描述您的需求或者改进建议

现在能支持代码变更后自动构建镜像，然后运行容器吗？或者说，镜像推到私有仓库之后，能否在 1panel 上监听到触发自动部署？

**Comment by liqiang-fit2cloud** [comment]
不支持，现在只支持通过应用商店更新。

**Comment by wanghe-fit2cloud** [comment]
应用商店中提供了 Jenkins 和 Watchtower 两款应用。
可以使用 Jenkins 实现代码仓库更新后自动构建镜像并推送到镜像仓库，再通过 Watchtower 自动更新应用镜像。

**Comment by swift-fs** [comment]
> 应用商店中提供了 Jenkins 和 Watchtower 两款应用。 可以使用 Jenkins 实现代码仓库更新后自动构建镜像并推送到镜像仓库，再通过 Watchtower 自动更新应用镜像。

啊哈！解决了！我用1panel管理日常运维工作~~代码丢到云效去处理CI/CD了！！！
