### ISSUE TITLE
[FEATURE]专业版许可证检验时间和服务器关机时间有冲突

### ISSUE THREAD

**Issue by yushuiguozhi** [1Panel-dev/1Panel#6960]
### 1Panel 版本

1.10.20

### 请描述您的需求或者改进建议

专业版激活，过几天需要重新导入激活，问客服说检验时间和我关机时间有冲突，希望解决下，是不是这个原因导致的。

### 请描述你建议的实现方案

如果激活检验不影响程序运行，可以放白天检验。具体是不是这个原因，过两天我再看下。

**Comment by wanghe-fit2cloud** [comment]
> 问客服说检验时间和我关机时间有冲突

请问 1Panel 服务器是否每天有定时关机操作？如果有，关机时间段是何时？

**Comment by yushuiguozhi** [comment]
每天11点半关机。




雨
***@***.***



&nbsp;

**Comment by wanghe-fit2cloud** [comment]
> 每天11点半关机。 雨 ***@***.*** &nbsp;

好的，近期版本会优化许可证同步逻辑。

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
