### ISSUE TITLE
[BUG] docker 环境变量在应用商店入口重启后会丢失

### ISSUE THREAD

**Issue by finallycc** [1Panel-dev/1Panel#6966]
### 1Panel 版本

v1.10.20-lts

### 问题描述

运行环境Java,配置时区后，重启失效。

### 重现步骤

![image](https://github.com/user-attachments/assets/2638e584-6d04-459e-bd2b-e8a727d1b58b)
![image](https://github.com/user-attachments/assets/89961054-236f-4f0b-8e93-479d27ac043f)

增加上述环境变量，如果是在容器列表重启没有问题
![image](https://github.com/user-attachments/assets/cffcef49-4400-482e-9379-22438ff2b70e)
如果是在  运行环境/Java 列表重启，会丢失
![image](https://github.com/user-attachments/assets/9f2bd7b0-07d8-4fe6-912f-4b379db40cc8)

### 期待的正确结果

重启应用不会丢失自定义配置

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，目前版本在用户提交容器参数修改时会显示提示信息，如图所示：
![image](https://github.com/user-attachments/assets/b186b441-fb29-410d-837d-e8731eff2d6b)

后续版本将支持用户在创建或编辑运行环境时自定义设置环境变量 https://github.com/1Panel-dev/1Panel/issues/4262
