### ISSUE TITLE
[BUG]端口转发报错

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#6968]
### 1Panel 版本

v1.10.20-lts

### 问题描述

阿里云新开的 debian12.7 装上 ufw 后，端口转发页面报错，且错误信息不明显

![图片](https://github.com/user-attachments/assets/3a07a8a9-fe68-433b-bb85-d88b94e1447e)

### 重现步骤

debian 12.7，打开端口转发

**Comment by ssongliu** [comment]
感谢反馈，下个版本优化该错误信息

**Comment by mjsoftking** [comment]
目前的办法就是重启服务器就好了

**Comment by ssongliu** [comment]
> 目前的办法就是重启服务器就好了

你服务器也是 debian12 吗？麻烦帮忙执行一下 iptables --version 看看返回

**Comment by mjsoftking** [comment]
@ssongliu 
iptables v1.8.9 (nf_tables)

**Comment by ssongliu** [comment]
> @ssongliu iptables v1.8.9 (nf_tables)

重启服务器之后就不报错了吗？

**Comment by mjsoftking** [comment]
> > @ssongliu iptables v1.8.9 (nf_tables)
> 
> 重启服务器之后就不报错了吗？

我遇到的情况是，迁移镜像恢复后，重新安装防火墙，然后必须重启一次服务器，否则一直提示那个错误，也是看社区有人给的建议

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
