### ISSUE TITLE
[FEATURE] 伪静态目录不合理

### ISSUE THREAD

**Issue by hhun** [1Panel-dev/1Panel#697]
### 1Panel 版本

1.1.1

### 请描述您的需求或者改进建议

伪静态目录感觉有点乱
> /www/sites/**abc.com**/rewrite/**abc.com**.conf

第一个 abc.com 应该改为创建网站设置的代号
假设我创建网站时，设置的网站代号是 abc ，域名是 abc.com
网站目录为 **/www/sites/abc/index/**
伪静态文件路径为 **/www/sites/abc.com/rewrite/abc.com.conf**

伪静态文件和网站没有在同一个父目录里面

### 请描述你建议的实现方案

![微信图片_20230418200537](https://user-images.githubusercontent.com/19625243/232772148-8ed6d8fb-e671-4c78-a5eb-d32e24e3c8c2.png)

**Comment by zhengkunwang223** [comment]
感谢建议，我们后续版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.1.3版本已发布。
