### ISSUE TITLE
[FEATURE] 运行环境希望添加环境变量的添加

### ISSUE THREAD

**Issue by Anyexyz** [1Panel-dev/1Panel#6981]
### 1Panel 版本

v1.10.20-lts

### 请描述您的需求或者改进建议

运行环境有的时候需要添加自己的环境变量，希望在新建运行环境的页面增加`环境变量`的添加的选项

**Comment by zhengkunwang223** [comment]
我们会在v2版本增加此功能

**Comment by wanghe-fit2cloud** [comment]
https://github.com/1Panel-dev/1Panel/issues/4262
