### ISSUE TITLE
[BUG]settings/backupaccount中点击 腾讯云 COS 配置的编辑按钮报错

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#6982]
### 联系方式

niujinkai@vip.qq.com

### 1Panel 版本

v1.10.20-lts

### 问题描述

![image](https://github.com/user-attachments/assets/b5ef5027-9e7f-4f21-9f5f-f3837a5dca04)
如上图，在已经配置了 腾讯云 COS 的情况下，在settings/backupaccount中点击 腾讯云 COS 的编辑按钮报错。
报错如下：
![image](https://github.com/user-attachments/assets/3af1d4c6-90f5-42f7-b191-42af243205e1)
![image](https://github.com/user-attachments/assets/279e1e49-0434-40cb-906e-a9a6ad9d4b6a)
请协助看下

### 重现步骤

已经有配置 腾讯云 COS 的情况下，点击旁边的编辑按钮

### 期待的正确结果

正常应该打开编辑配置界面

### 相关日志输出

```shell
无日志报错
```

### 附加信息

![image](https://github.com/user-attachments/assets/ef3fb64d-d90a-4df3-a5a2-f449d2edfe64)
![image](https://github.com/user-attachments/assets/3af1d4c6-90f5-42f7-b191-42af243205e1)
![image](https://github.com/user-attachments/assets/279e1e49-0434-40cb-906e-a9a6ad9d4b6a)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by ssongliu** [comment]
这里是历史脏数据的问题，可以删除后重新添加一下

**Comment by wanghe-fit2cloud** [comment]
参考：https://github.com/1Panel-dev/1Panel/issues/3802

**Comment by ghost** [comment]
已经解决了
