### ISSUE TITLE
[BUG] jumpserver将web端口从8080修改为38080

### ISSUE THREAD

**Issue by liuxiaoy** [1Panel-dev/1Panel#6984]
### 1Panel 版本

v1.10.20-lts

### 问题描述

从商店安装 jumpserver，将web端口从8080修改为38080，公开访问端口。启动后查看日志里面还是一直访问 http://127.0.0.1:8080 和 http://localhost:8080 。尝试过在配置文件加入环境变量 JUMPSERVER_SERVER=http://127.0.0.1:38080 后，web端可以访问了，不过日志里还是使用 http://127.0.0.1:8080 。

### 重现步骤

1.从商店安装 jumpserver，将web端口从8080修改为38080，公开访问端口。
2. 启动后查看日志里面还是一直访问 http://127.0.0.1:8080 和 http://localhost:8080 。此时无法访问web端。
3. 从商店修改参数，编辑配置文件加入环境变量 JUMPSERVER_SERVER: 'http://127.0.0.1:38080' ，重新启动。web端可以访问了，不过日志里还是使用http://127.0.0.1:8080 。

### 期待的正确结果

可以修改端口后，功能正常，健康检查访问正确的端口

**Comment by wanghe-fit2cloud** [comment]
1Panel 应用商店中部署的 JumpServer all-in-one 版本，容器内部的 gunicorn 服务端口为8080（不需要对外暴露）。
至于后期使用问题，可以反馈给 JumpServer 团队，https://github.com/jumpserver/jumpserver/issues
