### ISSUE TITLE
[BUG]应用商店安装 Ollama WebUI 未提示超时

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#6985]
### 1Panel 版本

v1.10.20-lts

### 问题描述

如题，安装7个多小时了，还一直显示的安装中

### 重现步骤

应用商店安装 Ollama WebUI

### 期待的正确结果

能提示应用镜像拉取超时。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
