### ISSUE TITLE
[BUG]OpenResty日志过大无法加载

### ISSUE THREAD

**Issue by stmtc233** [1Panel-dev/1Panel#6987]
### 1Panel 版本

v1.10.20-lts

### 问题描述

![img](https://github.com/user-attachments/assets/a3b70a0a-8d4b-4a37-9a42-8af731612291)
日志文件大小3.8GB

### 重现步骤

日志文件过大

**Comment by wanghe-fit2cloud** [comment]
感谢反馈！关于日志功能优化的建议，我们已统一汇总至该 [issue](https://github.com/1Panel-dev/1Panel/issues/6915)，欢迎进一步讨论。
