### ISSUE TITLE
[FEATURE] 日志文件删除后，再创建也不会写入日志

### ISSUE THREAD

**Issue by hhun** [1Panel-dev/1Panel#699]
### 1Panel 版本

1.1.1

### 请描述您的需求或者改进建议

日志文件删除后，再创建也不会写入日志

长期积累日期文件会过大，写入会占用很大的内存，而且文件过大不便于查看。
建议日志文件用 202004/18.log 这样按日期生成文件。

**Comment by hhun** [comment]
关闭日志，再开启日志。这样日志会正常写入

**Comment by hhun** [comment]
*87 open() "/www/sites/www/index/favicon.ico"

`favicon.ico`文件不存在不应该写入到错误日志里面，这样会造成过多的冗余日志。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中优化网站的日志。
