### ISSUE TITLE
[BUG]防火墙IP规则批量删除无效

### ISSUE THREAD

**Issue by ITsPro-CN** [1Panel-dev/1Panel#6991]
### 联系方式

凌霞News5微信群-Pro

### 1Panel 版本

1.10.20

### 问题描述

主机-防火墙-IP规则中，勾选多个ip，点击上方的“删除”按钮，能正确弹出要删除的ip列表，点击确认后显示删除成功，但是删除的ip仍在，刷新后也仍在。

### 重现步骤

主机-防火墙-IP规则中，勾选多个ip，点击上方的“删除”按钮，并点击确认。

**Comment by ITsPro-CN** [comment]
突然发现单个删除也无效
94.156.167.158
172.104.165.105
109.123.251.5
178.215.224.113
87.120.115.93
91.92.242.212

这几个是内置的删不掉？其他我创建的可以正常删除

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境复现一下上述问题。

**Comment by ssongliu** [comment]
ufw 还是firewalld ？

**Comment by maninhill** [comment]
无法复现，暂时先关闭。

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Unable to reproduce, temporarily closed.
