### ISSUE TITLE
[BUG] 如果证书过期而且设置了不允许非ssl登陆，会把自己锁在外面无法登陆

### ISSUE THREAD

**Issue by asdf2adsfad** [1Panel-dev/1Panel#6995]
### 1Panel 版本

all

### 问题描述

如果证书过期而且设置了不允许非ssl登陆，会把自己锁在外面无法登陆

### 重现步骤

1. 导入证书
2. 设置面板强制ssl
3. 证书过期
4. 上不去

### 期待的正确结果

1pctl允许关闭tls登陆

**Comment by asdf2adsfad** [comment]
而且建议把更新软件的功能也加进去

比如就算1pctl允许关闭了ssl登陆，现在也没法用上这个新功能

**Comment by ssongliu** [comment]
> 而且建议把更新软件的功能也加进去
> 
> 比如就算1pctl允许关闭了ssl登陆，现在也没法用上这个新功能

1pctl reset https 关闭 ssl 登陆也上不去吗？

**Comment by asdf2adsfad** [comment]
我的锅，我看command描述里面的reset的描述是“重置 1Panel 系统信息”，以为是重置所有东西的意思，所以没点
