### ISSUE TITLE
[FEATURE]防火墙firewalld只显示默认zone，不显示全部zone的规则

### ISSUE THREAD

**Issue by wuliaozhiyuan** [1Panel-dev/1Panel#6998]
### 1Panel 版本

0.6.3

### 请描述您的需求或者改进建议

[FEATURE]防火墙firewalld只显示默认zone，不显示全部zone的规则
比如我有两个网卡，一个对外，一个对内，会配置到两个zone上

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持该需求。

**Comment by wanghe-fit2cloud** [comment]
相同 issue https://github.com/1Panel-dev/1Panel/issues/2945
