### ISSUE TITLE
[FEATURE] PHP终端默认目录应该为 /www/sites/代号 而不是 /www

### ISSUE THREAD

**Issue by hhun** [1Panel-dev/1Panel#700]
### 1Panel 版本

1.1.1

### 请描述您的需求或者改进建议

PHP终端默认目录应该为 `/www/sites/网站代号` 而不是 `/www`

既然每一个网站是单独的容器，进入终端后，应该只能操作对应的PHP网站，而不是可以操作所有网站。

**Comment by zhengkunwang223** [comment]
此处是为了多 PHP 应用共用一个容器做预留处理
