### ISSUE TITLE
[BUG] 安全问题：面板地址出错的404等页面不是真正的404

### ISSUE THREAD

**Issue by asdf2adsfad** [1Panel-dev/1Panel#7000]
### 1Panel 版本

all

### 问题描述

如果在面板中设置登陆URL为A，错误代码404（或者别的），然后去访问不存在的URL B，页面上看上去是会显示404

但是！http代码仍然是200！！这个是骗不过扫描器的

而且这个404页面全都是特征，一堆1panal的js，扫描器一看就是面板后台

甚至都不需要扫描器，这个404页面甚至在页面顶部还有蓝色加载进度条！网速慢的话肉眼都能看得出来

解决办法也很简单，换成真正的404或者其他错误页面就好，最简单最蠢那种就行

**顺便报一个bug，旧版1panel升级新1panel之后，这个404 200之类的页面不会被升级到，还是原状**

### 重现步骤

我觉得不写这个也行

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在本地环境确实复现了该问题，将在近期版本中进行修复。

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已经发布，修复了状态码一直是 200 的问题。
> js 文件加载的问题，可能是因为我们将静态文件和后端二进制一起打包导致的，后面版本我们再继续调研一下具体方案。

**Comment by wanghe-fit2cloud** [comment]
> 顺便报一个bug，旧版1panel升级新1panel之后，这个404 200之类的页面不会被升级到，还是原状

麻烦将这个问题再开一个新的 issue，最好是有相关的截图等详细信息。
