### ISSUE TITLE
[BUG]Redis一直提示服务内部错误

### ISSUE THREAD

**Issue by lazyfish88** [1Panel-dev/1Panel#7003]
### 联系方式

232048843@qq.com

### 1Panel 版本

v1.10.10-lts

### 问题描述

系统正常运行了2个月了，现在打开Redis面板，点性能调整、商品、持久化，都提示服务内部错误，无法操作，然后重启后也是一样。这个我要怎么去查是什么问题？
另外还有个问题，如下图，我服务器是8G内容，显示占用30%，然后docker这边。redis也是默认给满内存的，显示用了90%+。这是什么情况 ？是docker的计算问题？我是在想是不是redis内存满了导致的？
![1731321706681](https://github.com/user-attachments/assets/4715232f-ce11-4f08-a70e-d89f6e139228)

![1731321706686](https://github.com/user-attachments/assets/bf6e8648-f4cb-4cf8-a511-e7de89ffb93c)

### 重现步骤

打开Redis面板，点性能调整、商品、持久化，都提示服务内部错误

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，你可以先在容器页面查看一下redis容器日志。
> 还有就是可以尝试将redis升级至最新版本（升级前备份）

**Comment by lazyfish88** [comment]
> 感谢反馈，你可以先在容器页面查看一下redis容器日志。
> 
> > 还有就是可以尝试将redis升级至最新版本（升级前备份）

有升级了，下面是容器的日志，
有一条警告“WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see”。貌似是因为内存满了？不过我服务器的内存才用了30%，容器这边给的也是8G。却显示用了90%+。。这是什么情况？


1:C 11 Nov 2024 14:52:07.230 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:C 11 Nov 2024 14:52:07.230 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 11 Nov 2024 14:52:07.230 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 11 Nov 2024 14:52:07.230 * Configuration loaded
1:M 11 Nov 2024 14:52:07.230 * monotonic clock: POSIX clock_gettime
1:M 11 Nov 2024 14:52:07.231 # Failed to write PID file: Permission denied
1:M 11 Nov 2024 14:52:07.231 * Running mode=standalone, port=6379.
1:M 11 Nov 2024 14:52:07.231 * Server initialized
1:M 11 Nov 2024 14:52:07.232 * Loading RDB produced by version 7.2.4
1:M 11 Nov 2024 14:52:07.232 * RDB age 8099 seconds
1:M 11 Nov 2024 14:52:07.232 * RDB memory usage when created 3.51 Mb
1:M 11 Nov 2024 14:52:07.240 * Done loading RDB, keys loaded: 1095, keys expired: 6.
1:M 11 Nov 2024 14:52:07.240 * DB loaded from disk: 0.008 seconds
1:M 11 Nov 2024 14:52:07.240 * Ready to accept connections tcp
1:C 11 Nov 2024 14:53:30.196 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:C 11 Nov 2024 14:53:30.197 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 11 Nov 2024 14:53:30.197 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 11 Nov 2024 14:53:30.197 * Configuration loaded
1:M 11 Nov 2024 14:53:30.197 * monotonic clock: POSIX clock_gettime
1:M 11 Nov 2024 14:53:30.197 # Failed to write PID file: Permission denied
1:M 11 Nov 2024 14:53:30.197 * Running mode=standalone, port=6379.
1:M 11 Nov 2024 14:53:30.198 * Server initialized
1:M 11 Nov 2024 14:53:30.198 * Loading RDB produced by version 7.2.4
1:M 11 Nov 2024 14:53:30.198 * RDB age 8182 seconds
1:M 11 Nov 2024 14:53:30.198 * RDB memory usage when created 3.51 Mb
1:M 11 Nov 2024 14:53:30.204 * Done loading RDB, keys loaded: 1095, keys expired: 6.
1:M 11 Nov 2024 14:53:30.204 * DB loaded from disk: 0.006 seconds
1:M 11 Nov 2024 14:53:30.204 * Ready to accept connections tcp
1:C 11 Nov 2024 14:53:32.458 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:C 11 Nov 2024 14:53:32.459 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 11 Nov 2024 14:53:32.459 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 11 Nov 2024 14:53:32.459 * Configuration loaded
1:M 11 Nov 2024 14:53:32.459 * monotonic clock: POSIX clock_gettime
1:M 11 Nov 2024 14:53:32.459 # Failed to write PID file: Permission denied
1:M 11 Nov 2024 14:53:32.459 * Running mode=standalone, port=6379.
1:M 11 Nov 2024 14:53:32.460 * Server initialized
1:M 11 Nov 2024 14:53:32.460 * Loading RDB produced by version 7.2.4
1:M 11 Nov 2024 14:53:32.460 * RDB age 8184 seconds
1:M 11 Nov 2024 14:53:32.460 * RDB memory usage when created 3.51 Mb
1:M 11 Nov 2024 14:53:32.467 * Done loading RDB, keys loaded: 1095, keys expired: 6.
1:M 11 Nov 2024 14:53:32.467 * DB loaded from disk: 0.007 seconds
1:M 11 Nov 2024 14:53:32.467 * Ready to accept connections tcp
1:C 11 Nov 2024 14:53:37.758 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:C 11 Nov 2024 14:53:37.759 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 11 Nov 2024 14:53:37.759 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 11 Nov 2024 14:53:37.759 * Configuration loaded
1:M 11 Nov 2024 14:53:37.759 * monotonic clock: POSIX clock_gettime
1:M 11 Nov 2024 14:53:37.759 # Failed to write PID file: Permission denied
1:M 11 Nov 2024 14:53:37.759 * Running mode=standalone, port=6379.
1:M 11 Nov 2024 14:53:37.760 * Server initialized
1:M 11 Nov 2024 14:53:37.760 * Loading RDB produced by version 7.2.4
1:M 11 Nov 2024 14:53:37.760 * RDB age 8189 seconds
1:M 11 Nov 2024 14:53:37.760 * RDB memory usage when created 3.51 Mb
1:M 11 Nov 2024 14:53:37.767 * Done loading RDB, keys loaded: 1095, keys expired: 6.
1:M 11 Nov 2024 14:53:37.767 * DB loaded from disk: 0.008 seconds
1:M 11 Nov 2024 14:53:37.767 * Ready to accept connections tcp
