### ISSUE TITLE
[FEATURE]希望短信告警增加自定义屏蔽时间段功能，减少短信额度浪费

### ISSUE THREAD

**Issue by wp778** [1Panel-dev/1Panel#7005]
### 1Panel 版本

v1.10.20-lts

### 请描述您的需求或者改进建议

现短信告警界面，“指定时间”无法自定义，如“CPU 占用过高”告警，时间只可为5分钟。希望可以自定义时间。
另可否增加屏蔽、排除告警时间段，因为服务器可能设定有定时备份等可预知任务，在凌晨x点时备份会导致CPU短时间内高占用，但其实是预知事件，无需告警，即将此时间段内的告警进行排出或屏蔽，不进行推送动作。

### 附加信息

![PixPin_2024-11-12_09-12-05](https://github.com/user-attachments/assets/ef94071e-1b71-41cf-9cc4-84f02b9ffcdb)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈！目前我们默认采集监控数据的时间间隔为5分钟，后续版本可能会考虑开放自定义设置。
关于 `增加屏蔽、排除告警时间段` 的需求，我们也会在后续版本中予以支持。

**Comment by wanghe-fit2cloud** [comment]
v1.10.22 版本已发布。
