### ISSUE TITLE
[BUG]fail2ban 中配置的黑名单莫名其妙就丢失了

### ISSUE THREAD

**Issue by mfanoffice** [1Panel-dev/1Panel#7007]
### 联系方式

yumin.fan@fit2cloud.com

### 1Panel 版本

v1.10.20-lts

### 问题描述

工具箱--fail2ban 中配置的黑名单莫名其妙就丢失了。
上午 9 点配置了 6 条黑名单 IP，并确认已经生效，11 点再看看黑名单中只剩一条 IP。

### 重现步骤

配置 fail2ban 黑名单 IP，过4 个小时再看看是否正常

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，可以先参考一下这个 [issue](https://github.com/1Panel-dev/1Panel/issues/3894)，看是否能解决问题。

**Comment by ssongliu** [comment]
麻烦贴一下 fail2ban 配置信息

**Comment by AliveNeko** [comment]
IP会消失是因为fail2ban中的黑名单是临时的（默认设置下10分钟），如果没有设置成永久封禁，那么时间到了就放出来了。
你看看是不是这个原因。

想要永久禁用需要在防火墙中设置IP规则来禁用。

**Comment by mfanoffice** [comment]
> 麻烦贴一下 fail2ban 配置信息

<img width="1948" alt="iShot2024-11-12 16 43 30" src="https://github.com/user-attachments/assets/591f703b-9f95-42be-b439-c62bece7b683">
<img width="1126" alt="iShot2024-11-12 16 42 34" src="https://github.com/user-attachments/assets/5bea4723-d82f-4127-8ed6-43f6eaf76fd0">
fail2ban 的配置好像并没有生效，同一个 IP 一直在试探

**Comment by AliveNeko** [comment]
> > 麻烦贴一下 fail2ban 配置信息
> 
> <img alt="iShot2024-11-12 16 43 30" width="1948" src="https://private-user-images.githubusercontent.com/48307752/385205528-591f703b-9f95-42be-b439-c62bece7b683.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDE0MjQsIm5iZiI6MTczMTQwMTEyNCwicGF0aCI6Ii80ODMwNzc1Mi8zODUyMDU1MjgtNTkxZjcwM2ItOWY5NS00MmJlLWI0MzktYzYyYmVjZTdiNjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA4NDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNTI5ZWQ0ZjM2NWRlYjk5MWU3ODQ2ZGM2ZDUxODZjYTU2NDk5YzdkYWRmMjljM2RiYmIzMGFjNGRlZDYzYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lxy6_PpowZra3_dWTE0l8RmHNZHiLAYIGW2ZLY1MgDk"> <img alt="iShot2024-11-12 16 42 34" width="1126" src="https://private-user-images.githubusercontent.com/48307752/385205561-5bea4723-d82f-4127-8ed6-43f6eaf76fd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDE0MjQsIm5iZiI6MTczMTQwMTEyNCwicGF0aCI6Ii80ODMwNzc1Mi8zODUyMDU1NjEtNWJlYTQ3MjMtZDgyZi00MTI3LThlZDYtNDNmNmVhZjc2ZmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA4NDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYzY3YjU0YjcxMTMzZDljNDc3MjVhN2I4MjE5MWI0MmFkODc3N2E1YzQ5NDM3YTBhMmRkY2ZiYmNjNzBjMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.05vPVUwHrgHa5xoN2Iw7rxGQvLoIoKthDk1ovKm16vo"> fail2ban 的配置好像并没有生效，同一个 IP 一直在试探

---
根据你这个配置，发现周期是300秒（也就是5分钟），看日志它七八分钟重试2次，确实不会触发ban ip
主动配置IP黑名单的话600秒（也就是10分钟）就自动放出来了。

所以想ban这个IP要么fail2ban里面设置成永久封禁，要么ufw里面设置IP规则。

和我在 #3894 中是同一个问题

**Comment by ssongliu** [comment]
直接把禁用时间改成永久

**Comment by mfanoffice** [comment]
感谢各位大佬支持，加入防火墙 IP 规则可以解决，并且把 ban 的封禁改为永久，IP 黑名单会自动增加触发规则的 IP。
