### ISSUE TITLE
[FEATURE]1panel安装目录文件夹禁止删除

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#7008]
### 1Panel 版本

v1.10.20-lts

### 请描述您的需求或者改进建议

昨天因为误删1panel安装文件夹且阴差阳错的勾选了`永久删除文件`导致面板被删，等反应过来已经来不及了，重装了一整天才恢复。

因此，希望后续版本希望增加`1panel`安装文件夹不可删除判定

至少，在面板层面不能直接删除1panel文件夹，以防因为意外造成损失

同时，建议对于1panel文件夹中重要的运行文件，在1panel面板中同样不可修改，以防误操作

或者，直接在面板层面隐藏整个1panel安装文件夹。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本优化。

**Comment by QYG2297248353** [comment]
这应该是增加二次确认吧，不允许删除，那不就违背文件管理的意义了？

应该是争对危险目录，在删除的基础上增加二次确认
/bin
/bin
/dev
/etc
/usr

对于危险目录下的文件还是可以安装原有逻辑

**Comment by JAINKRE** [comment]
> 这应该是增加二次确认吧，不允许删除，那不就违背文件管理的意义了？
> 
> 应该是争对危险目录，在删除的基础上增加二次确认 /bin /bin /dev /etc /usr
> 
> 对于危险目录下的文件还是可以安装原有逻辑

这个问题在于只争对1panel面板中对于1panel安装文件夹来说，问题是删除之后整个面板就没了，包括面板里的数据。

如果在1panel中允许删除，是有误操作风险的，尤其是数据/配置没有备份的前提下。

至于非要删除，使用linux命令任意文件都可以强制删掉面板层面也拦不住，我考虑的的不允许删除建议是指面板中选择文件点击删除的操作，尽量在UI层面降低误操作风险。

**Comment by QYG2297248353** [comment]
> 至于非要删除，使用linux命令任意文件都可以强制删掉面板层面也拦不住，我考虑的的不允许删除建议是指面板中选择文件点击删除的操作，尽量在UI层面降低误操作风险。

那不是增加操作的复杂度，面板操作的好好的，结果不行，然后打开ssh终端，在操作一遍，那面板还有啥意义

所以增加二次确认，用户确认就是要删除，后果自己承担就完了。

就好比:
```
rm -rf /xxx
```

```
rm -rf ./xxx
```
手快的人，敲完，都懒得确认， `.` 也是会造成大问题的

你也说了 是你自己选到了
> 1panel安装文件夹

你当时坑定完全相信自己操作没问题

**Comment by JAINKRE** [comment]
> > 至于非要删除，使用linux命令任意文件都可以强制删掉面板层面也拦不住，我考虑的的不允许删除建议是指面板中选择文件点击删除的操作，尽量在UI层面降低误操作风险。
> 
> 那不是增加操作的复杂度，面板操作的好好的，结果不行，然后打开ssh终端，在操作一遍，那面板还有啥意义
> 
> 所以增加二次确认，用户确认就是要删除，后果自己承担就完了。
> 
> 就好比:
> 
> ```
> rm -rf /xxx
> ```
> 
> ```
> rm -rf ./xxx
> ```
> 
> 手快的人，敲完，都懒得确认， `.` 也是会造成大问题的
> 
> 你也说了 是你自己选到了
> 
> > 1panel安装文件夹
> 
> 你当时坑定完全相信自己操作没问题

你可能还是没理解我的意思，我是说针对`1panel安装文件夹`这个前提，禁止删除操作。而非针对所有文件夹。你可以尝试一下假设误删安装文件夹后会发生什么。

面板对于文件管理来说只是套了一层壳，本质还是linux命令。假设有人故意要删除1panel文件夹，就算面板挡住了终端里还是可以强行删除，这属于恶意破坏行为并不在讨论范围内。

我说的是仅针对面板的安装文件夹，设置为不可删逻辑确实增加了复杂度。但考虑一下如果面板里有大量配置却被误删的后果。

而且，对于线上的服务器来说，更多的可能是针对shell连接和root权限有严格的控制。现在面板的问题是仅通过面板删除安装文件夹就可以造成面板瘫痪。

**Comment by QYG2297248353** [comment]
> 我说的是仅针对面板的安装文件夹，设置为不可删逻辑确实增加了复杂度。但考虑一下如果面板里有大量配置却被误删的后果。

你应该理解一下这句话 `1Panel 是新一代的 Linux 服务器运维管理面板`

你晓得什么是 `运维管理面板` 吗，不是我在更你抠字眼。这不是面向大众的产品，这又不是一个saas产品，防的那么死，运维看了都头疼。

其次，运维面板本就不应该放到公网，但凡有个漏洞，那就是分分钟的事情。

**Comment by JAINKRE** [comment]
> > 我说的是仅针对面板的安装文件夹，设置为不可删逻辑确实增加了复杂度。但考虑一下如果面板里有大量配置却被误删的后果。
> 
> 你应该理解一下这句话 `1Panel 是新一代的 Linux 服务器运维管理面板`
> 
> 你晓得什么是 `运维管理面板` 吗，不是我在更你抠字眼。这不是面向大众的产品，这又不是一个saas产品，防的那么死，运维看了都头疼。
> 
> 其次，运维面板本就不应该放到公网，但凡有个漏洞，那就是分分钟的事情。

1panel安装文件夹被删除的后果就是面板直接没了，里面配置的东西全部都没了。如果这个可以在面板里被随意删除，那么使用面板的意义在哪？使用面板就是为了解决原生运维的复杂性，但也应该考虑起码的安全性。

这就像面板里面删除操作默认是放到一个`回收站`里，说白了就是暂存在一个文件夹下给用户一个反悔和防止误操作的空间。按照你这个逻辑，为什么1panel还要多此一举做回收站呢？

而且，我一直在强调是针对1panel安装文件夹这个前提不允许面板层面删除。从产品角度来说，linux和面板应该是两个独立的系统，只是linux的优先级大于面板。既然以root权限登录终端了，当然拥有最高权限。但在面板里面，就应该接受默认情况下面板的安全优先级大于普通操作逻辑。

到此为止，这个问题不在和你争论了。

**Comment by QYG2297248353** [comment]
> 到此为止，这个问题不在和你争论了。

明明是讨论，哪来的争论😂

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
