### ISSUE TITLE
[BUG]OpenResty和PostgreSQL应用导入备份错误

### ISSUE THREAD

**Issue by JAINKRE** [1Panel-dev/1Panel#7010]
### 1Panel 版本

v1.10.20-lts

## OpenResty报错
![image](https://github.com/user-attachments/assets/6b2897dd-2195-4379-a3fa-9f7769d4ebd9)

OpenResty正常应用商店里安装且未执行任何操作，恢复数据的数据源为计划任务中`备份应用`自动创建且为执行任何操作

进入恢复的目录，可以看到文件夹下是已经存在恢复的路径：
![image](https://github.com/user-attachments/assets/25e41c6b-0a8f-43f6-8204-e3529a719eb8)

但是应用中没有：
![image](https://github.com/user-attachments/assets/2ae0389e-9c04-4f27-9890-86e6d094fd4d)

## PostgreSQL报错
![image](https://github.com/user-attachments/assets/41e810a9-a9a3-48df-9787-c824753f7f97)

PGSQL数据源和恢复过程与OpenResty一致

### 重现步骤

应用商店 > 已安装 > 导入备份

**Comment by wanghe-fit2cloud** [comment]
感谢反馈！可以先按以下步骤进行验证：

1. 进入 容器 页面，检查是否存在 OpenResty 容器。
2. 在 已安装 页面，点击 重建 按钮，确认是否能够成功重建。

**Comment by JAINKRE** [comment]
> 感谢反馈！可以先按以下步骤进行验证：
> 
> 1. 进入 容器 页面，检查是否存在 OpenResty 容器。
> 2. 在 已安装 页面，点击 重建 按钮，确认是否能够成功重建。

确定容器存在，且尝试重建了，还是不行。

而且，我重新删除了OpenResty，重新安装导入，依旧同样的问题。

**Comment by JAINKRE** [comment]
并且，OpenResty容器在安装错误提示之后，过了几秒自动刷新显示已启动，但OpenResty里面没有网站数据。

**Comment by wanghe-fit2cloud** [comment]
![image](https://github.com/user-attachments/assets/e177116d-8ff1-4aaf-92a6-488813cbf6ac)
![image](https://github.com/user-attachments/assets/cb33cd27-3576-4878-883c-1e13ba305a23)

通过命令操作一下应用。
1、启动 `docker-compose up -d`
2、关闭 `docker-compose down -v`
3、查看服务 `docker-compose ps`
4、查看日志 `docker-compose logs -f`

**Comment by JAINKRE** [comment]
> 通过命令操作一下应用。 1、启动 `docker-compose up -d` 2、关闭 `docker-compose down -v` 3、查看服务 `docker-compose ps` 4、查看日志 `docker-compose logs -f`

![image](https://github.com/user-attachments/assets/96336f71-7917-4532-a215-2a165c48c5f1)

**Comment by JAINKRE** [comment]
被四个命令给误导了，这是新安装的
![image](https://github.com/user-attachments/assets/2052e736-e46a-4375-a6ec-f09e33ecf337)

这是重新导入后的：
![image](https://github.com/user-attachments/assets/8653ee17-d5c4-46ee-a0e0-5ed174b12c1e)

**Comment by JAINKRE** [comment]
这个路径好像是存在的

![image](https://github.com/user-attachments/assets/7f825309-efa8-4094-8422-aded1c12d2fb)

**Comment by wanghe-fit2cloud** [comment]
进入 `192.168.3.88` 网站设置页面，在 `网站目录` 页下方是否有提示权限问题？

**Comment by wanghe-fit2cloud** [comment]
点击 `保存` 按钮，设置一下 `运行用户/组` 权限（PHP 容器内部用户 UID 和 GID 默认都是 1000），如图：
![image](https://github.com/user-attachments/assets/5588c6d6-0da8-41ff-aab8-338fd13a8467)

**Comment by JAINKRE** [comment]
> 点击 `保存` 按钮，设置一下 `运行用户/组` 权限（PHP 容器内部用户 UID 和 GID 默认都是 1000），如图： ![image](https://private-user-images.githubusercontent.com/46734380/385243814-5588c6d6-0da8-41ff-aab8-338fd13a8467.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MDc4ODAsIm5iZiI6MTczMTQwNzU4MCwicGF0aCI6Ii80NjczNDM4MC8zODUyNDM4MTQtNTU4OGM2ZDYtMGRhOC00MWZmLWFhYjgtMzM4ZmQxM2E4NDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDEwMzMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MzNhZWZkYjE4ZDAwZjM0M2ZhZDdhNDA0ZmZjOWQ2MTdkNDU5OWQzODQ4ZGM1YmUzYTA3NzgwNDNlNjQwOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u7I__Hs0wW1KAEdUMa_-wfZjclDT15YiZUScaCsg4BE)

现在的问题是页面直接是空的：

![image](https://github.com/user-attachments/assets/890daae7-df09-4aaa-ba2c-279e9e026836)

安装路径`/home/1panel/apps/openresty/openresty/www/sites`却存在网站信息

![image](https://github.com/user-attachments/assets/e87586ae-1175-41c7-b81a-32a52099983d)

**Comment by wanghe-fit2cloud** [comment]
结论：
通过 OpenResty 备份恢复应用时，网站列表不会随之恢复。

	如需恢复网站，可使用网站备份或面板快照功能。
