### ISSUE TITLE
[FEATURE] 应用安装，希望可以自定义 1panel 里面的应用的存储地方

### ISSUE THREAD

**Issue by heartacker** [1Panel-dev/1Panel#7013]
### 1Panel 版本

newest

### 请描述您的需求或者改进建议

```
/opt/1panel/apps
```
默认是这个，

### 请描述你建议的实现方案

希望有一个地方可以设置这个位置，
比如 nas，希望存在 存储盘，而不是系统盘里面

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。应用的安装目录默认与 1Panel 的系统安装目录一致，以便于后续快照等操作的管理。建议在安装 1Panel 时支持自定义安装目录。
