### ISSUE TITLE
[BUG] 面板里面设置 1000用户组，提示 exit status 1错误

### ISSUE THREAD

**Issue by hhun** [1Panel-dev/1Panel#702]
### 1Panel 版本

1.1.1

### 问题描述

面板里面设置 1000用户组，提示 `exit status 1` 错误

### 重现步骤

用 1.1.1版本新创建的网站也不能设置权限

**Comment by wanghe-fit2cloud** [comment]
进入到网站主目录，手动给 index 文件夹授权，执行以下命令：
```shell
chown -R 1000:1000 index
```
观察一下是否能执行成功。

**Comment by wanghe-fit2cloud** [comment]
v1.1.2 版本已修复。
