### ISSUE TITLE
[BUG]界面设置不能二次更换 Logo

### ISSUE THREAD

**Issue by oralzd** [1Panel-dev/1Panel#7020]
### 1Panel 版本

v1.10.20-lts  专业版

### 问题描述

界面设置不能二次更换logo

### 重现步骤

界面设置不能二次更换logo

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，在本地环境中未复现该问题。
> 多次上传 Logo（带文字）、Logo（不带文字）和网站图标后，点击保存按钮均成功更新。

最好能提供一个视频或者动图，来帮助我们更好的定位问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
