### ISSUE TITLE
[FEATURE]应用商城增加SteamCmd一键部署

### ISSUE THREAD

**Issue by Zevo77** [1Panel-dev/1Panel#7021]
### 1Panel 版本

v1.10.20-lts

### 请描述您的需求或者改进建议

应用商城增加SteamCmd一键部署

### 请描述你建议的实现方案

应用商城增加SteamCmd一键部署
https://developer.valvesoftware.com/wiki/SteamCMD#Linux
https://hub.docker.com/r/cm2network/steamcmd/

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，我们主要以项目的 Star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有超 1 万 Star 的开源项目，感谢您的理解。

> 你可以将需求反馈给 [第三方仓库（由社区用户维护）](https://github.com/okxlin/appstore)。
