### ISSUE TITLE
[FEATURE]封锁次数达到N次后自动永久封禁该ip

### ISSUE THREAD

**Issue by kuilei0926** [1Panel-dev/1Panel#7022]
### 1Panel 版本

专业版 v1.10.20-lts

### 请描述您的需求或者改进建议

可以设置封锁次数达到N次后自动永久封禁该ip

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
IP 封锁是临时存储在 OpenResty 中的，重启后会解除封锁。若需永久封禁，可使用拉黑功能。
> 自动封禁虽然可以实现，但会对 OpenResty 和网站性能产生较大影响，建议使用手动拉黑方式来实现。
