### ISSUE TITLE
[BUG]docker驱动程序识别有误

### ISSUE THREAD

**Issue by yyg-max** [1Panel-dev/1Panel#7032]
### 1Panel 版本

v1.10.20-lts

### 问题描述

我终端查看的是systemd而选择的确是cgroupfs
![image](https://github.com/user-attachments/assets/31ef188d-804e-4634-a4f8-8e1c770c3d6a)
![image](https://github.com/user-attachments/assets/71626400-d49c-44e0-818f-85ad4731e157)

### 重现步骤

我终端查看的是systemd而选择的确是cgroupfs
![image](https://github.com/user-attachments/assets/31ef188d-804e-4634-a4f8-8e1c770c3d6a)
![image](https://github.com/user-attachments/assets/71626400-d49c-44e0-818f-85ad4731e157)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦提供一下 `docker version` 版本信息和 `cat /etc/docker/daemon.json` 内容。

**Comment by yyg-max** [comment]
![image](https://github.com/user-attachments/assets/fa66a7a3-9074-43bb-bf13-0e12cfcf467b)

**Comment by wanghe-fit2cloud** [comment]
本地环境还是未能复现该问题。

可以加一波好友，我们远程看看
<img width="259" alt="image" src="https://github.com/user-attachments/assets/975932d5-f7c8-4418-98d6-c46956d4ae2f">

**Comment by yyg-max** [comment]
好怪我现在重新输入命令查询的和我上次反馈的不一样

**Comment by wanghe-fit2cloud** [comment]
> 好怪我现在重新输入命令查询的和我上次反馈的不一样

`systemd` 是怎么设置的，还清楚吗？

**Comment by yyg-max** [comment]
我啥都没设置和服务器都没动过就默认的，前几天查询的是systemd ，现在又不是 systemd 。好怪

**Comment by wanghe-fit2cloud** [comment]
> 我啥都没设置和服务器都没动过就默认的，前几天查询的是systemd ，现在又不是 systemd 。好怪

因为 Docker 默认使用的是 cgroupfs，而 1Panel 会从 daemon.json 文件中读取具体配置。
由于你提供的 daemon.json 文件中未包含相关设置，因此 1Panel 默认显示为 cgroupfs。
![image](https://github.com/user-attachments/assets/0aa97236-43b3-4fbe-858c-5f4f6f0a2a1f)

**Comment by yyg-max** [comment]
我记得Docker从1.5后吧默认是systemd 的 但是我系统不知道为啥今天查的和前天查的不一样，前天查到是支持systemd的现在又不支持systemd了

**Comment by wanghe-fit2cloud** [comment]
先关闭该 issue 了，后续如果稳定复现该问题，再继续讨论。

**Comment by yyg-max** [comment]
可以
