### ISSUE TITLE
[BUG]語言選擇繁體 但由些還是簡體

### ISSUE THREAD

**Issue by SWXDC** [1Panel-dev/1Panel#7033]
### 联系方式

xuczxc100@gmail.com

### 1Panel 版本

v1.10.20-lts

### 问题描述

![image](https://github.com/user-attachments/assets/5ee01d68-c759-4136-8bd6-7976cde86bc2)
應用的簡介和名稱
![image](https://github.com/user-attachments/assets/4f35d19b-5823-49e6-827c-9d31d1f7dfac)
![image](https://github.com/user-attachments/assets/ffae51f0-b6a8-4ac6-a41a-26030f372837)
Docker的選項
![image](https://github.com/user-attachments/assets/3db77836-3153-49b0-a986-2fc86c3b8778)

### 重现步骤

改成繁體中文

### 期待的正确结果

改成繁體中文

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

1、目前版本中，应用商店的应用描述和 readme 部分，只支持了简体中文和英文。
> 我们会在v2 版本考虑应用是否支持更多的语言。

2、容器列表中 `选择列` 未翻译的问题将会在近期版本中修复。
> 如果有其他翻译不准确的地方，欢迎继续反馈给我们。

**Comment by SWXDC** [comment]
謝謝

**Comment by SWXDC** [comment]
![image](https://github.com/user-attachments/assets/84ef6e38-d853-434b-aa45-082ee8216e34)
![image](https://github.com/user-attachments/assets/95f94692-0d7d-43cc-8add-2c1e0f9ace72)

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
