### ISSUE TITLE
[FEATURE] DNS账户添加对CloudDNS的支持

### ISSUE THREAD

**Issue by lousong** [1Panel-dev/1Panel#7038]
### 1Panel 版本

v1.10.20-lts

### 请描述您的需求或者改进建议

建议证书申请的DNS账户增加对CloudDNS https://www.cloudns.net/ 的支持

### 请描述你建议的实现方案

https://github.com/go-acme/lego 已支持CloudDNS
https://go-acme.github.io/lego/dns/cloudns/index.html

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持该需求。

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。

**Comment by magiccode1412** [comment]
> v1.10.21 版本已发布。

今天我想申请证书，域名在clouNDS，尝试之后，一直提示用户不存在；后找到这个issue，才发现，1panel错把`cloudDNS`当成`clouDNS`，根据上面的记录，需求应该是对`clouDNS`的支持，也就是`https://www.cloudns.net/`的支持，甚至发issue的大佬自己也把服务商名字弄混了，希望1panel可以计划支持`clouDNS`，非常感谢

![Image](https://github.com/user-attachments/assets/4c2329af-9894-4367-a8ab-e3ebd530b26b)

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> v1.10.21 version has been released.

Today I want to apply for a certificate. The domain name is in clouNDS. After trying it, I kept prompting the user that it does not exist. After finding this issue, I found that 1panel mistakenly regards `cloudDNS` as `clouDNS`. According to the above records, the requirement should be `clouDNS`. The support, that is, the support of `https://www.cloudns.net/`, and even the big guy who sent the issue himself confused the name of the service provider. I hope 1panel can plan to support `clouDNS`. Thank you very much

![Image](https://github.com/user-attachments/assets/4c2329af-9894-4367-a8ab-e3ebd530b26b)

**Comment by sunskyhsh** [comment]
> ### 1Panel 版本
> v1.10.20-lts
> 
> ### 请描述您的需求或者改进建议
> 建议证书申请的DNS账户增加对CloudDNS https://www.cloudns.net/ 的支持
> 
> ### 请描述你建议的实现方案
> https://github.com/go-acme/lego 已支持CloudDNS https://go-acme.github.io/lego/dns/cloudns/index.html
> 
> ### 附加信息
> _No response_

根据这里的网址，DNS账户提供商应为ClouDNS，而不是CloudDNS。希望可以重新开启下issue @wanghe-fit2cloud

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> ### 1Panel version
> v1.10.20-lts
>
> ### Please describe your needs or make suggestions for improvement
> It is recommended to add support for CloudDNS https://www.cloudns.net/ for DNS accounts for certificate applications
>
> ### Please describe your suggested implementation plan
> https://github.com/go-acme/lego CloudDNS is supported https://go-acme.github.io/lego/dns/cloudns/index.html
>
> ### Additional information
> _No response_

According to the URL here, the DNS account provider should be CloudDNS, not CloudDNS

**Comment by wanghe-fit2cloud** [comment]
> > ### 1Panel 版本
> > v1.10.20-lts
> > ### 请描述您的需求或者改进建议
> > 建议证书申请的DNS账户增加对CloudDNS https://www.cloudns.net/ 的支持
> > ### 请描述你建议的实现方案
> > https://github.com/go-acme/lego 已支持CloudDNS https://go-acme.github.io/lego/dns/cloudns/index.html
> > ### 附加信息
> > _No response_
> 
> 根据这里的网址，DNS账户提供商应为ClouDNS，而不是CloudDNS。希望可以重新开启下issue [@wanghe-fit2cloud](https://github.com/wanghe-fit2cloud)

可以再来一个新的 issue，感谢。
![Image](https://github.com/user-attachments/assets/668a800f-664d-4040-9c32-c93ac6aa31d5)

**Comment by sunskyhsh** [comment]
@wanghe-fit2cloud 提交了PR，辛苦review: https://github.com/1Panel-dev/1Panel/pull/8207

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@wanghe-fit2cloud Submitted PR, work hard to review: https://github.com/1Panel-dev/1Panel/pull/8207
