### ISSUE TITLE
[FEATURE]关于创建计划任务后的短信告警的小建议

### ISSUE THREAD

**Issue by chenkuicn** [1Panel-dev/1Panel#7039]
### 1Panel 版本

v1.10.20-lts

### 请描述您的需求或者改进建议

![wechat_2024-11-13_211236_643](https://github.com/user-attachments/assets/e427c29d-82ca-4ccc-90d0-7dc6ab2a5a3a)
![wechat_2024-11-13_211305_557](https://github.com/user-attachments/assets/1be5d972-2bf0-4438-a498-ed39c826520d)
当前版本中，创建计划任务后就算没有勾选短信告警，也会创建短信告警。

### 请描述你建议的实现方案

是不是直接不创建这个短信告警比较好一点

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。刚在本地环境成功复现了该问题：在编辑计划任务（未勾选创建短信告警任务）时，系统仍新增了一条短信告警任务。我们将在近期版本中修复此问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
