### ISSUE TITLE
[BUG]通过应用商店安装的jumpserver4.2.0无法通过admin/ChangeMe登录

### ISSUE THREAD

**Issue by mr-nealon** [1Panel-dev/1Panel#7054]
### 1Panel 版本

1.1.20

### 问题描述

通过应用商店安装的jumpserver4.2.0无法通过admin/ChangeMe登录

### 重现步骤

通过应用商店安装的jumpserver4.2.0无法通过admin/ChangeMe登录

**Comment by wanghe-fit2cloud** [comment]
可以先进入 `容器` 页面，查看 JumpServer 容器的运行状态和容器日志。

**Comment by wanghe-fit2cloud** [comment]
刚刚在本地环境测试，应用运行正常且可访问。
