### ISSUE TITLE
[FEATURE]Nginx内置隐藏版本号和标识，增加服务器安全性，不会被针对Nginx和版本号进行漏洞提权

### ISSUE THREAD

**Issue by 357341051** [1Panel-dev/1Panel#706]
### 1Panel 版本

1.1.1

### 请描述您的需求或者改进建议

Nginx内置隐藏版本号和标识，增加服务器安全性，不会被针对Nginx和版本号进行漏洞提权
![image](https://user-images.githubusercontent.com/118408640/232947056-0df2eab0-37e6-4e73-9045-275d4b7edda2.png)

### 请描述你建议的实现方案

好像伪静态里就可以配置

**Comment by 357341051** [comment]
还有php的版本
![image](https://user-images.githubusercontent.com/118408640/232947918-8607bb17-f466-4196-9a23-7626d7e1d8d4.png)

**Comment by 357341051** [comment]
openresty标识也要去掉或者伪装成Apache也是可以的

**Comment by 357341051** [comment]
宝塔面板是去掉的

**Comment by zhengkunwang223** [comment]
感谢反馈 后续版本支持

**Comment by maninhill** [comment]
安全第一。

**Comment by heyzqq** [comment]
可以先手动修改下 OpenResty 的配置，在 OpenResty -> 设置 -> 配置修改，添加 `server_tokens off; ` 关闭版本号显示：

```
......

http {
    # 关闭版本号
    server_tokens off; 
    ......
}
```

**Comment by zyyfit** [comment]
1.2.2 版本已经隐藏了版本号
