### ISSUE TITLE
[BUG] 应用商店中的 maxkb 应用的 compose 文件容器名为 ollama

### ISSUE THREAD

**Issue by XCWQW1** [1Panel-dev/1Panel#7062]
### 1Panel 版本

v1.10.6-lts

### 问题描述

![image](https://github.com/user-attachments/assets/662930f9-59f9-4e50-87bf-03e98f67cc53)
应用商店中的 maxkb 应用的 compose 文件 maxkb 容器名为 ollama，这个不应该是maxkb吗

### 重现步骤

应用商店》maxkb》编辑compose文件

### 期待的正确结果

将容器名由 ollama 更改为 maxkb

**Comment by zhengkunwang223** [comment]
感谢反馈 这个是 serviceName 不是容器名称  不过也得改一下

**Comment by maninhill** [comment]
已经修改了代码，感谢。
