### ISSUE TITLE
[FEATURE] 请问以后设置文件权限，是否会添加选择所有者？

### ISSUE THREAD

**Issue by hhun** [1Panel-dev/1Panel#707]
### 1Panel 版本

1.1.1

### 请描述您的需求或者改进建议

请问以后设置文件权限，是否会添加选择所有者？

就像这样，还有设置的权限应用到子目录。
![360截图20230419102625886](https://user-images.githubusercontent.com/19625243/232950818-1e160daa-b5bc-4eae-bc18-c36031856690.png)

**Comment by zhengkunwang223** [comment]
感谢反馈 后续版本支持

**Comment by zhengkunwang223** [comment]
v1.2 版本已经支持设置文件所有者 并且应用到子目录
