### ISSUE TITLE
[FEATURE]查看详情时esc可以关闭侧板，或者点击mask可以关闭侧板

### ISSUE THREAD

**Issue by heweixiang** [1Panel-dev/1Panel#7072]
### 1Panel 版本

v1.10.20-lts

### 请描述您的需求或者改进建议

查看详情时esc可以关闭侧板，或者点击mask可以关闭侧板

### 请描述你建议的实现方案

-

### 附加信息

-

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持该需求。

**Comment by wanghe-fit2cloud** [comment]
重复需求 https://github.com/1Panel-dev/1Panel/issues/5408
