### ISSUE TITLE
[Feat] 高级功能的部分功能也跟随主题色变色

### ISSUE THREAD

**Issue by QingFeng-awa** [1Panel-dev/1Panel#7082]
### 1Panel 版本

专业版 1.10.20 Beta1

### 请描述您的需求或者改进建议

目前在专业版的WAF,站点监控功能中的`拦截地图`,`请求趋势`,`拦截趋势`,`访客地图`,`访客趋势`的颜色仍是默认主题色,期望在未来也跟随自定义主题色自动切换。
![WAF概览](https://github.com/user-attachments/assets/b2985b6c-1e37-41f8-8f5c-643fcf0b2c89)
![访客地图](https://github.com/user-attachments/assets/0af41c6a-9f0a-46ba-a591-4d35cabb5333)
![访客趋势](https://github.com/user-attachments/assets/2952f988-c07e-4344-92be-71fb5face20e)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
