### ISSUE TITLE
[FEATURE]期望应用商店可以增加Tracca开源的 GPS 跟踪系统

### ISSUE THREAD

**Issue by BI7ALG** [1Panel-dev/1Panel#7088]
### 1Panel 版本

v1.10.20-lts

### 请描述您的需求或者改进建议

Traccar 是一个开源的 GPS 跟踪系统，支持 200多种GPS 协议和 2000 多种型号的 GPS 跟踪设备，其中就包括我们目前使用的iOS/Android 这样的手机设备，也就是说，小伙伴们按照我今天的教程在NAS上部署好Traccar应用之后，就可以在手机上安装Traccar APP，就能实时实现在线追踪功能。

官网地址：https://www.traccar.org/

功能与用途：

这个程序主要是满足：

出租车，货车，卡车/拖车
农用设备，车队，集装箱，船舶，全地形车
专人跟踪，个人车辆，手机
等多种行业以及个人的追踪定位需求。

### 请描述你建议的实现方案

集成到应用商店，实现一键部署服务。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，我们主要以项目的 Star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有超 1 万 Star 的开源项目，感谢您的理解。

> 你可以将需求反馈给 [第三方仓库（由社区用户维护）](https://github.com/okxlin/appstore)。
