### ISSUE TITLE
[BUG]应用安装后显示异常，各个文件夹以及文件都不存在

### ISSUE THREAD

**Issue by heweixiang** [1Panel-dev/1Panel#7089]
### 联系方式

touchfish.cc@outlook.com

### 1Panel 版本

v1.10.20-lts

### 问题描述

估计是文件权限问题，但看到的都是777，请开发者排查一下，谢谢

### 重现步骤

nas中docker安装1panel随便

docker run -d \
    --name 1panel \
    --restart always \
    --network host \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /volume2/docker/volumes:/var/lib/docker/volumes \
    -v /volume2/docker/opt:/opt \
    -v /volume2/docker/root:/root \
    -e TZ=Asia/Shanghai \
    moelin/1panel:latest

### 期待的正确结果

应用能正常的使用

### 相关日志输出

```shell
服务内部错误: stderr: Container 1Panel-openresty-FYFo Starting Error response from daemon: Bind mount failed: '/opt/1panel/apps/openresty/openresty/conf/fastcgi_params' does not exists
```

**Comment by zhengkunwang223** [comment]
当前还没有完全适配 nas 我们会在后续版本不断优化

**Comment by wanghe-fit2cloud** [comment]
NAS 相关问题的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4004
