### ISSUE TITLE
[BUG]网站设置php版本后，选项显示的php版本无法及时更新

### ISSUE THREAD

**Issue by leaphy-dev** [1Panel-dev/1Panel#7097]
### 1Panel 版本

v1.10.21-beta.1

### 问题描述

如题，设置php版本后，提示更新成功，但"更新"按钮仍不为灰显。并且在设置页面内切换到其他的设置项后再切换回php版本设置页面，显示的设置项仍为更新前的php版本。必须要完全关闭整个设置页重进才可以正常显示。

### 重现步骤

网站-php设置-更新php版本

**Comment by zhengkunwang223** [comment]
感谢反馈，我们先看一下

**Comment by wanghe-fit2cloud** [comment]
确实存在上述问题。
保存成功后，在标红菜单中切换，仍显示更新前的 php 版本，如图：
<img width="778" alt="image" src="https://github.com/user-attachments/assets/ea5d58b1-7292-40c1-8f36-5699170a4712">

**Comment by wanghe-fit2cloud** [comment]
补充：如果切换到不存在 PHP 镜像的版本，系统会提示超时（建议检查本地是否存在对应的 PHP 镜像）。

**Comment by wanghe-fit2cloud** [comment]
v1.10.22 版本已发布。
