### ISSUE TITLE
[BUG] 编辑端口转发规则时不能保存

### ISSUE THREAD

**Issue by ltxhhz** [1Panel-dev/1Panel#7099]
### 1Panel 版本

v1.10.20-lts

### 问题描述

修改了已有规则的端口或协议后不能保存
![image](https://github.com/user-attachments/assets/87655047-d644-49a5-ab41-d186e797c5d3)

### 重现步骤

对一个已有的规则点击编辑并保存

**Comment by ltxhhz** [comment]
如果已有一条tcp的规则，要再添加一条udp的规则，也会不能保存

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本修复并推送更新。

**Comment by Hawkli0777** [comment]
端口转发请尽快支持ipv6吧

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
