### ISSUE TITLE
[FEATURE]游戏服务器希望增加一个pvpgn.pro

### ISSUE THREAD

**Issue by 873578156** [1Panel-dev/1Panel#7107]
### 1Panel 版本

专业版 v1.10.20-lts

### 请描述您的需求或者改进建议

游戏服务器希望增加一个pvpgn.pro

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，请问该游戏官方是否提供了 Docker 镜像？
如果有，麻烦提供一下之前部署该游戏时使用的 docker run 命令或者 docker-compose.yml 文件，以便我们后续适配并上架。

**Comment by 873578156** [comment]
似乎官方没有镜像，

**Comment by wanghe-fit2cloud** [comment]
> 似乎官方没有镜像，

这可能无法满足上架要求，因为 1Panel 商店中的所有应用都采用 Docker 容器化方案部署，敬请理解。
