### ISSUE TITLE
[BUG]负载显示有问题，一直显示120%+

### ISSUE THREAD

**Issue by Beipiaoxiaoyang** [1Panel-dev/1Panel#711]
### 联系方式

675119154@qq.com

### 1Panel 版本

1.1.1

### 问题描述

平台为海思麒麟3798mv200处理器，arm64位，负载显示有问题，一直显示120%+
![截图_20230419113851](https://user-images.githubusercontent.com/122436907/232961190-da91deb0-f2dc-4920-acc6-2f3f645484a7.png)
finalshell 显示正常
![c3a1a8ac4616733b126368c9ca89022](https://user-images.githubusercontent.com/122436907/232961266-93404389-6e7a-4bd0-a533-d53501727a8b.png)

### 重现步骤

负载显示有问题，一直显示120%+

**Comment by Beipiaoxiaoyang** [comment]
![截图_20230419151939](https://user-images.githubusercontent.com/122436907/232999163-899385f7-1d08-48e7-b5f0-ffa10090a6a5.png)

**Comment by ssongliu** [comment]
图中 7.03、7.12、7.15 分别对应主机 1、5、15分钟的平均负载，没有问题。
然后计算机负载百分比我们是用了一个 load1 / (cpu*2) * 0.75) * 100 的公式来计算：
![image](https://user-images.githubusercontent.com/73214554/233002350-d6dab466-ea1e-4376-b098-8a95a71013c1.png)

**Comment by Beipiaoxiaoyang** [comment]
谢谢您的解答，谢谢
