### ISSUE TITLE
[FEATURE] 增加.NET Core环境支持

### ISSUE THREAD

**Issue by lujiex** [1Panel-dev/1Panel#7119]
### 1Panel 版本

v1.10.20-lts

### 请描述您的需求或者改进建议

增加.NET Core环境一键部署

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
关于运行环境需求的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/748
