### ISSUE TITLE
[FEATURE] 集成第三方漏扫应用进行安全漏洞扫描

### ISSUE THREAD

**Issue by maninhill** [1Panel-dev/1Panel#712]
### 1Panel 版本

1.1.0

### 请描述您的需求或者改进建议

如题。安全是大家最关注的，1Panel 的优势是基于容器来部署各种应用，可以对这些容器暴露出来的端口进行漏洞扫描，有利于提前发现安全隐患。

对于扫描出来的安全问题，直接显示在面板的概览页面。

### 请描述你建议的实现方案

https://github.com/projectdiscovery/nuclei

Fast and customizable vulnerability scanner based on simple YAML based DSL.

这个项目很活跃，漏洞库更新也及时，可以集成这个产品进行扫描。

**Comment by zhengkunwang223** [comment]
感谢建议，我们后续版本支持

**Comment by maninhill** [comment]
请问这个问题有进展吗？

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is there any progress on this issue?

**Comment by wanghe-fit2cloud** [comment]
中短期内暂无相关支持计划，先关闭该 issue 了，望理解。
