### ISSUE TITLE
[FEATURE]BT迁移1P

### ISSUE THREAD

**Issue by ossplus** [1Panel-dev/1Panel#7123]
### 1Panel 版本

1.x

### 请描述您的需求或者改进建议

希望可以出个教程：BT的站如何迁移1p；

**Comment by wanghe-fit2cloud** [comment]
感谢你的建议！
目前，1Panel 官方暂时没有支持 BT 站点迁移的计划。不过，在 [1Panel 论坛](https://bbs.fit2cloud.com/c/1p/7) 中，已经有社区用户针对这一需求编写了相关教程，你可以参考其中的内容。

非常感谢你对 1Panel 的关注和支持！如果有其他建议，也欢迎随时反馈！
