### ISSUE TITLE
[BUG] 反向代理默认值转发到 $host 而不是 $host:$server_port

### ISSUE THREAD

**Issue by Seele0oO** [1Panel-dev/1Panel#7124]
### 1Panel 版本

v1.10.20-lts

### 问题描述

使用面板创建反向代理时应该将转发目标设置为 $host:$server_port，这样将使得非标准端口网站可以被正确转发。

### 重现步骤

+ 创建一个反向代理网站
+ 为该网站绑定非标准端口
+ 发现网站router认为自己的host是不带端口的，导致无法访问。

### 期待的正确结果

反向代理转发后 默认将转发目标设置为 $host:$server_port

**Comment by QYG2297248353** [comment]
![image](https://github.com/user-attachments/assets/0c4fd0b3-c276-4bc3-b009-7fb8cf96709a)
没有问题呀

域名本就不携带端口
```nginx
proxy_set_header X-Forwarded-Proto $scheme;
```
$scheme 传递了请求协议，程序也能读取实际协议 80/443

非标准端口网站 本就是特例，自己改了不就完了？

**Comment by Seele0oO** [comment]
好的，谢谢。
