### ISSUE TITLE
[Bug] 应用升级-查看对比, 控制台报错, 对比文件不显示

### ISSUE THREAD

**Issue by realzolo** [1Panel-dev/1Panel#7128]
### 联系方式

zolo@onezol.com

### 1Panel 版本

v1.10.21-beta.2

### 问题描述

![image](https://github.com/user-attachments/assets/423fd16d-97f2-42ba-a7a5-67a131a446c4)

### 重现步骤

点击应用升级-文件对比

**Comment by zhengkunwang223** [comment]
感谢反馈，我们先复现一下

**Comment by wanghe-fit2cloud** [comment]
v1.10.21 版本已发布。
