### ISSUE TITLE
[Bug] 面板开启https，证书续签后未更新

### ISSUE THREAD

**Issue by GentsunCheng** [1Panel-dev/1Panel#7129]
### Contact Information

oriimiku@gmail.com

### 1Panel Version

v1.10.19-lts

### Problem Description

面板开启https，证书续签后未更新
![8A50BEC99BAB3A3C1425B862827A604B](https://github.com/user-attachments/assets/b69959d8-371a-466b-9f4e-539864e8539d)
![D8AD8AF2A9CAB1B5E976F46B2A5E6B55](https://github.com/user-attachments/assets/b33ee7e5-f11e-4935-b779-e91012f51623)
![PixPin_2024-11-19_20-05-23](https://github.com/user-attachments/assets/37bf3fa9-72e6-411f-ac50-756cf6bb26c1)
在从未进入过面板后台的浏览器环境下依旧如此，可以排除浏览器缓存原因

### Steps to Reproduce

面板开启ssl
选择打开续签的证书
等待证书过期
面板证书选择页面的日期正常
进入面板提示ssl证书过期

**Comment by GentsunCheng** [comment]
补充，使用1pctl restart命令重启面板依旧显示过期，在 **面板设置-安全-面板SSL-详情** 重新点击确认后，面板的SSL证书才能正确刷新

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在本地环境复现以上上述问题。

**Comment by ssongliu** [comment]
麻烦看一下这个推送目录是啥
![image](https://github.com/user-attachments/assets/4a4a7ccb-ee25-442d-bc27-b2d9363967ba)

**Comment by GentsunCheng** [comment]
> 麻烦看一下这个推送目录是啥 ![image](https://private-user-images.githubusercontent.com/73214554/387897267-4a4a7ccb-ee25-442d-bc27-b2d9363967ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjk1NDgsIm5iZiI6MTczMjE2OTI0OCwicGF0aCI6Ii83MzIxNDU1NC8zODc4OTcyNjctNGE0YTdjY2ItZWUyNS00NDJkLWJjMjctYjJkOTM2Mzk2N2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA2MDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYTUxYmQ0MTNkOWZiYTA1MTZkNzZkOTc3M2VhZGNiNGMxMmQxNzk3ZGU5ZjQ4ZWQ1NjZiY2NmOTE5NmI1MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ORn-OxwAZSVQQ5NE2_zeyVPjLMZqy0TBagWtrhVdiWs)

推送目录是 /etc/ssl/orii.top

**Comment by ssongliu** [comment]
> > 麻烦看一下这个推送目录是啥 ![image](https://private-user-images.githubusercontent.com/73214554/387897267-4a4a7ccb-ee25-442d-bc27-b2d9363967ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjk1NDgsIm5iZiI6MTczMjE2OTI0OCwicGF0aCI6Ii83MzIxNDU1NC8zODc4OTcyNjctNGE0YTdjY2ItZWUyNS00NDJkLWJjMjctYjJkOTM2Mzk2N2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA2MDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYTUxYmQ0MTNkOWZiYTA1MTZkNzZkOTc3M2VhZGNiNGMxMmQxNzk3ZGU5ZjQ4ZWQ1NjZiY2NmOTE5NmI1MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ORn-OxwAZSVQQ5NE2_zeyVPjLMZqy0TBagWtrhVdiWs)
> 
> 推送目录是 /etc/ssl/orii.top

看起来是证书更新后没有正确推送到指定目录，能远程看看吗？
![image](https://github.com/user-attachments/assets/1546ecb7-1895-4514-ad4e-e8f9833ac2c3)

**Comment by GentsunCheng** [comment]
> > > 麻烦看一下这个推送目录是啥 ![image](https://private-user-images.githubusercontent.com/73214554/387897267-4a4a7ccb-ee25-442d-bc27-b2d9363967ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjk1NDgsIm5iZiI6MTczMjE2OTI0OCwicGF0aCI6Ii83MzIxNDU1NC8zODc4OTcyNjctNGE0YTdjY2ItZWUyNS00NDJkLWJjMjctYjJkOTM2Mzk2N2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA2MDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYTUxYmQ0MTNkOWZiYTA1MTZkNzZkOTc3M2VhZGNiNGMxMmQxNzk3ZGU5ZjQ4ZWQ1NjZiY2NmOTE5NmI1MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ORn-OxwAZSVQQ5NE2_zeyVPjLMZqy0TBagWtrhVdiWs)
> > 
> > 
> > 推送目录是 /etc/ssl/orii.top
> 
> 看起来是证书更新后没有正确推送到指定目录，能远程看看吗？ ![image](https://private-user-images.githubusercontent.com/73214554/388377204-1546ecb7-1895-4514-ad4e-e8f9833ac2c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjk5MTUsIm5iZiI6MTczMjE2OTYxNSwicGF0aCI6Ii83MzIxNDU1NC8zODgzNzcyMDQtMTU0NmVjYjctMTg5NS00NTE0LWFkNGUtZThmOTgzM2FjMmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA2MTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMmJlMDg1ZjllNzA4OTM2NDhhMmZjMjVkMjk3NTcyMmY5NmVmMWVhYTgyYmYwYmEyNTQ4YmY0MjFlZjUzM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HOPpxNWLHewMl-Ww1NIc5xVFH1iO4K_eQy3JfA3IsCQ)

可能暂时验证不了，昨天在证书选择界面重新确认后恢复正常了，大概有哪些可能，下次更新证书的时候我验证验证吧

**Comment by ssongliu** [comment]
> > > > 麻烦看一下这个推送目录是啥 ![image](https://private-user-images.githubusercontent.com/73214554/387897267-4a4a7ccb-ee25-442d-bc27-b2d9363967ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjk1NDgsIm5iZiI6MTczMjE2OTI0OCwicGF0aCI6Ii83MzIxNDU1NC8zODc4OTcyNjctNGE0YTdjY2ItZWUyNS00NDJkLWJjMjctYjJkOTM2Mzk2N2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA2MDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYTUxYmQ0MTNkOWZiYTA1MTZkNzZkOTc3M2VhZGNiNGMxMmQxNzk3ZGU5ZjQ4ZWQ1NjZiY2NmOTE5NmI1MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ORn-OxwAZSVQQ5NE2_zeyVPjLMZqy0TBagWtrhVdiWs)
> > > 
> > > 
> > > 推送目录是 /etc/ssl/orii.top
> > 
> > 
> > 看起来是证书更新后没有正确推送到指定目录，能远程看看吗？ ![image](https://private-user-images.githubusercontent.com/73214554/388377204-1546ecb7-1895-4514-ad4e-e8f9833ac2c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjk5MTUsIm5iZiI6MTczMjE2OTYxNSwicGF0aCI6Ii83MzIxNDU1NC8zODgzNzcyMDQtMTU0NmVjYjctMTg5NS00NTE0LWFkNGUtZThmOTgzM2FjMmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA2MTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMmJlMDg1ZjllNzA4OTM2NDhhMmZjMjVkMjk3NTcyMmY5NmVmMWVhYTgyYmYwYmEyNTQ4YmY0MjFlZjUzM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HOPpxNWLHewMl-Ww1NIc5xVFH1iO4K_eQy3JfA3IsCQ)
> 
> 可能暂时验证不了，昨天在证书选择界面重新确认后恢复正常了，大概有哪些可能，下次更新证书的时候我验证验证吧

/etc/ssl 这个目录是你设置的推送目录吗？

**Comment by GentsunCheng** [comment]
> > > > > 麻烦看一下这个推送目录是啥 ![image](https://private-user-images.githubusercontent.com/73214554/387897267-4a4a7ccb-ee25-442d-bc27-b2d9363967ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjk1NDgsIm5iZiI6MTczMjE2OTI0OCwicGF0aCI6Ii83MzIxNDU1NC8zODc4OTcyNjctNGE0YTdjY2ItZWUyNS00NDJkLWJjMjctYjJkOTM2Mzk2N2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA2MDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYTUxYmQ0MTNkOWZiYTA1MTZkNzZkOTc3M2VhZGNiNGMxMmQxNzk3ZGU5ZjQ4ZWQ1NjZiY2NmOTE5NmI1MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ORn-OxwAZSVQQ5NE2_zeyVPjLMZqy0TBagWtrhVdiWs)
> > > > 
> > > > 
> > > > 推送目录是 /etc/ssl/orii.top
> > > 
> > > 
> > > 看起来是证书更新后没有正确推送到指定目录，能远程看看吗？ ![image](https://private-user-images.githubusercontent.com/73214554/388377204-1546ecb7-1895-4514-ad4e-e8f9833ac2c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjk5MTUsIm5iZiI6MTczMjE2OTYxNSwicGF0aCI6Ii83MzIxNDU1NC8zODgzNzcyMDQtMTU0NmVjYjctMTg5NS00NTE0LWFkNGUtZThmOTgzM2FjMmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA2MTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMmJlMDg1ZjllNzA4OTM2NDhhMmZjMjVkMjk3NTcyMmY5NmVmMWVhYTgyYmYwYmEyNTQ4YmY0MjFlZjUzM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HOPpxNWLHewMl-Ww1NIc5xVFH1iO4K_eQy3JfA3IsCQ)
> > 
> > 
> > 可能暂时验证不了，昨天在证书选择界面重新确认后恢复正常了，大概有哪些可能，下次更新证书的时候我验证验证吧
> 
> /etc/ssl 这个目录是你设置的推送目录吗？

对，我自己设置的目录

**Comment by zhengkunwang223** [comment]
我们会在下个版本支持证书的热更新

**Comment by wanghe-fit2cloud** [comment]
v1.10.22 版本已发布。
