### ISSUE TITLE
服务内部错误: stat /opt/1panel/resource/apps/mysql/versions/8.0.30: no such file or directory

### ISSUE THREAD

**Issue by mabaoguo1** [1Panel-dev/1Panel#713]
### 请描述您的问题

安装mysql8.0.30报错这个是什么原因呢

**Comment by zhengkunwang223** [comment]
您好，是不是误删1panel目录下面的文件夹了

**Comment by mabaoguo1** [comment]
apps&nbsp; backup&nbsp; cache&nbsp; db&nbsp; log&nbsp; resource&nbsp; runtime
1panel目录下目前有这些文件夹




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1Panel-dev/1Panel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月19日(星期三) 中午1:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [1Panel-dev/1Panel] 服务内部错误: stat /opt/1panel/resource/apps/mysql/versions/8.0.30: no such file or directory (Issue #713)





 
您好，是不是误删1panel目录下面的文件夹了

**Comment by mabaoguo1** [comment]
> 您好，是不是误删1panel目录下面的文件夹了
下面是1panel目录下所有文件信息，麻烦帮忙看下是不是少了东西
apps  backup  cache  db  log  resource  runtime

**Comment by mabaoguo1** [comment]
不好意思刚发错目录了，这是/opt/1panel/resource/apps/ 目录下的所有文件
dataease         gitlab  jenkins  kodbox     mariadb  mongodb  openresty  php7  phpmyadmin  redis            uptime-kuma  wordpress
docker-registry  halo    kafka    list.json  minio    nexus    php5       php8  postgresql  redis-commander  wikijs

**Comment by zhengkunwang223** [comment]
> 不好意思刚发错目录了，这是/opt/1panel/resource/apps/ 目录下的所有文件，**缺少mysql** dataease gitlab jenkins kodbox mariadb mongodb openresty php7 phpmyadmin redis uptime-kuma wordpress docker-registry halo kafka list.json minio nexus php5 php8 postgresql redis-commander wikijs

看起来很奇怪 你重新同步一下应用试试

**Comment by mabaoguo1** [comment]
> > 不好意思刚发错目录了，这是/opt/1panel/resource/apps/ 目录下的所有文件，**缺少mysql** dataease gitlab jenkins kodbox mariadb mongodb openresty php7 phpmyadmin redis uptime-kuma wordpress docker-registry halo kafka list.json minio nexus php5 php8 postgresql redis-commander wikijs
> 
> 看起来很奇怪 你重新同步一下应用试试
我卸载重装后好了，谢谢
