### ISSUE TITLE
改端口6666进不去面板

### ISSUE THREAD

**Issue by yho2ds** [1Panel-dev/1Panel#7132]
服务运行和端口绑定均正常，且通过 `curl 127.0.0.1:端口` 测试也正常，说明问题可能出在 1Panel 所在服务器的网络配置。你可以重点检查一下主机防火墙和安全组设置，确保没有阻塞该端口。

_Originally posted by @wanghe-fit2cloud in https://github.com/1Panel-dev/1Panel/issues/7103#issuecomment-2485872795_
![{D3CE39D4-3D41-4EEC-A14F-EB67E1718818}](https://user-images.githubusercontent.com/120007008/387732515-541f7357-fc9a-4e37-b9c7-d028bf49b883.png)
这个是新开的虚拟机 直接新装的1panel 然后设置的6666没办法进入 设置3000可以进入
![{2317267B-5BD9-4E9E-8A22-A6F67C601AE6}](https://user-images.githubusercontent.com/120007008/387734662-ddf199ce-2083-47fe-8558-3389395233df.png)
直接新装的1panel 然后设置的6666没办法进入 设置3000可以进入 貌似
就6666进不去 查看iptables也是没有问题 但是新开的1panel也是进不去
            
![{7E6DCEA7-4B64-4673-9D94-2A900DBE185B}](https://user-images.githubusercontent.com/120007008/387735691-0f359eeb-1544-4647-b051-e2c63d41738c.png)
上一个issue

**Comment by yho2ds** [comment]
看上面的图片好像不正常我就再发一次吧 
新开的虚拟机 和它的iptables 看起来都没问题
![image](https://github.com/user-attachments/assets/346dd2c1-d196-47b0-ae95-df3637ee3235)
![image](https://github.com/user-attachments/assets/1f750874-ac2d-4409-b2a9-008695c5dd36)
一开始设置的是6666进不去 后面修改了端口号为3000确认端口没问题 就改回6666 发现还是进不去
又试了其他的端口 好像就只有6666这个端口没办法用
![image](https://github.com/user-attachments/assets/6e0351e2-c2b8-46c9-a500-749519a0a90a)
服务器curl能获取到内容 电脑curl也能获取内容 但是浏览器就是打不开 能确认防火墙和内网都没有禁用这个端口
![{A7200E99-9E36-4537-9915-BE37BF7265B0}](https://github.com/user-attachments/assets/9d35858c-9771-4902-ae3b-5b52b4da674d)

**Comment by yho2ds** [comment]
![{0996627A-5F5A-4E7E-A440-746432B29C3E}](https://github.com/user-attachments/assets/cb85776d-40fb-4afa-9d35-c2522ab8565d)
1pctl listen-ip ipv4和6都试了不行

**Comment by wanghe-fit2cloud** [comment]
这种非系统性问题，建议在 Discussion 中讨论，先关闭该 issue。
