### ISSUE TITLE
[Bug]旧版1panel升级新1panel之后，这个404 200之类的页面不会被升级到，还是原状

### ISSUE THREAD

**Issue by asdf2adsfad** [1Panel-dev/1Panel#7134]
### 1Panel Version

社区版： v1.10.21-lts

### Problem Description

旧版1panel升级新1panel之后，这个404 200之类的页面不会被升级到，还是原状
![1732083422453](https://github.com/user-attachments/assets/aa6c9734-f0e7-48dd-9ac4-25a1ab860604)

### Steps to Reproduce

1. 老版本，带bug
2. 升级到最新版本
3. 如图

**Comment by asdf2adsfad** [comment]
@wanghe-fit2cloud

**Comment by asdf2adsfad** [comment]
不太了解1panel的结构，不过这些404 500之类的页面也许可以考虑在代码里写死掉，直接不带多余header地返回掉body，毕竟这个页面结构太简单了。这样也许解决起来比较简单，而且也不留破绽

**Comment by wanghe-fit2cloud** [comment]
新版本已修复鉴权接口返回状态码 200 的问题（与用户设置的错误状态码保持一致）。
> 对于 JS 等文件加载的问题，目前尚未找到理想的解决方案，我们正在本地进行尝试修复。

**Comment by wanghe-fit2cloud** [comment]
v1.10.22 版本已发布。
