### ISSUE TITLE
[Bug] 私有容器仓库无法拉取容器镜像（阿里云）

### ISSUE THREAD

**Issue by skys-mission** [1Panel-dev/1Panel#7135]
### Contact Information

微信：skys-mission

### 1Panel Version

v1.10.21-lts

### Problem Description

1. 首先我在一个v1.10.21-lts之前的版本（我不记得），配置了一个阿里云的私有容器镜像仓库，给出了一个报错（我未截图）
报错内容：stdout: stderr: WARNING! Using --password via the CLI is insecure. Use --password-stdin. Error response from daemon...
2. 之后我更新到了v1.10.21-lts版本
3. 添加了这个仓库成功了，于是我开始拉取镜像
4. 拉取镜像报错
![拉取报错](https://github.com/user-attachments/assets/74f5c1c7-41f3-4b20-91d5-467a9557a316)
报错内容：image pull failed!image “我的镜像” pull failed, err: Error response from daemon: Get "https://*****.cn-guangzhou.personal.cr.aliyuncs.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
5. 我回到仓库页面，看到一个同步按钮，我点了一下，又回到1.的报错
![仓库页报错](https://github.com/user-attachments/assets/3dd20bf8-d4cc-4337-b87e-e6119b5cd4d2)
报错内容同1.：stdout: stderr: WARNING! Using --password via the CLI is insecure. Use --password-stdin. Error response from daemon: Get "https://************.cn-guangzhou.personal.cr.aliyuncs.com/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) , stderr: exit status 1

其它
我不知道应该设置http/https阿里云那边的文档也没写于是我视图设置http，结果
![选择http报错](https://github.com/user-attachments/assets/5ee3645f-538b-49c9-a0f0-3001dad8e2d4)
仓库是正常的
![正常](https://github.com/user-attachments/assets/3326aa7d-92a8-4e72-9a0a-c9906f86939f)

### Steps to Reproduce

如描述所示

**Comment by skys-mission** [comment]
我在机器上试了下，不能登录，可能不是1panel的问题[狗头]

**Comment by wanghe-fit2cloud** [comment]
刚测试了阿里云镜像仓库，添加和拉取镜像均正常，如图：
![image](https://github.com/user-attachments/assets/e5f8a35a-8d2b-4720-a5dc-cb7173288f94)
