### ISSUE TITLE
[Feature] 建议网站功能支持启用，停用

### ISSUE THREAD

**Issue by sunkolin** [1Panel-dev/1Panel#7138]
### 1Panel 版本

v1.10.21-lts

### 请描述您的需求或者改进建议

建议网站功能支持启用，停用；目前没有好的办法停用网站，只能先删除。

<img width="972" alt="image" src="https://github.com/user-attachments/assets/bb3d5923-c560-48c5-8d31-59819f0e730a">

### 请描述你建议的实现方案

希望在操作中增加一个启用，停用按钮
<img width="1090" alt="image" src="https://github.com/user-attachments/assets/5ef394da-b70f-4968-a164-17e76f8e7dba">

**Comment by wanghe-fit2cloud** [comment]
点击状态列按钮，可以实现网站的启停，如图：
![image](https://github.com/user-attachments/assets/86ad2785-48e8-48be-bb2f-b80c65e950e0)
