### ISSUE TITLE
[Feature] 希望支持Vercel的DNS账户申请免费证书

### ISSUE THREAD

**Issue by 005001** [1Panel-dev/1Panel#7139]
### 1Panel 版本

v1.10.21-lts

### 请描述您的需求或者改进建议

使用namesilo解析很慢, 将namesilo的域名托管到 Vercel 后, 使用namesilo的api就无法申请证书, 所以希望支持Vercel的DNS账户申请免费证书

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，重复需求  https://github.com/1Panel-dev/1Panel/issues/2025
