### ISSUE TITLE
[FEATURE] 建议增加面板的域名配置入口

### ISSUE THREAD

**Issue by MeditatorV** [1Panel-dev/1Panel#714]
### 1Panel 版本

v1.1.1

### 请描述您的需求或者改进建议

当前使用的是IP加端口的形式，希望可以使用域名访问面板

**Comment by realzolo** [comment]
> ### 1Panel 版本
> v1.1.1
> 
> ### 请描述您的需求或者改进建议
> 当前使用的是IP加端口的形式，希望可以使用域名访问面板
> 
> ### 请描述你建议的实现方案
> _No response_
> 
> ### 附加信息
> _No response_

当前版本支持绑定域名。 网站 -> 创建网站 -> 反向代理(反代1Panel服务)

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本将支持在面板设置中开启 https。

**Comment by maninhill** [comment]
加油干

**Comment by cyril-cheng** [comment]
> > ### 1Panel 版本
> > v1.1.1
> > ### 请描述您的需求或者改进建议
> > 当前使用的是IP加端口的形式，希望可以使用域名访问面板
> > ### 请描述你建议的实现方案
> > _No response_
> > ### 附加信息
> > _No response_
> 
> 当前版本支持绑定域名。 网站 -> 创建网站 -> 反向代理(反代1Panel服务)

这种方法是可以实现，但是有个问题你得考虑：假如你nginx正在升级，你反代就挂了，要是升级失败启动不起来，就进不去了。因为你得杜绝直接从IP访问后台，所以反代的端口或者说中转的端口肯定不能和后台端口一样，后台端口还得限制成只能允许本机访问。

**Comment by cyril-cheng** [comment]
> > > ### 1Panel 版本
> > > v1.1.1
> > > ### 请描述您的需求或者改进建议
> > > 当前使用的是IP加端口的形式，希望可以使用域名访问面板
> > > ### 请描述你建议的实现方案
> > > _No response_
> > > ### 附加信息
> > > _No response_
> > 
> > 
> > 当前版本支持绑定域名。 网站 -> 创建网站 -> 反向代理(反代1Panel服务)
> 
> 这种方法是可以实现，但是有个问题你得考虑：假如你nginx正在升级，你反代就挂了，要是升级失败启动不起来，就进不去了。因为你得杜绝直接从IP访问后台，所以反代的端口或者说中转的端口肯定不能和后台端口一样，后台端口还得限制成只能允许本机访问。

因此给后台用单独的进程绑定域名非常有必要。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
