### ISSUE TITLE
[Feature] 我希望出一个jar包或者环境可直接用原生命令的可视化操作，例如启动，停止等

### ISSUE THREAD

**Issue by chendong0801** [1Panel-dev/1Panel#7140]
### 1Panel 版本

v1.10.21-lts

### 请描述您的需求或者改进建议

现在的面板环境，有点严重依赖于docker，在很多因素下，配置ip地址相关来说比较麻烦，反而不利于简化开发，可否增加一个需求，用于直接在可视化面板上 用 java -jar 启动jar包 而不是一定要依赖于docker

### 请描述你建议的实现方案

现在的面板环境，有点严重依赖于docker，在很多因素下，配置ip地址相关来说比较麻烦，反而不利于简化开发，可否增加一个需求，用于直接在可视化面板上 用 java -jar 启动jar包 而不是一定要依赖于docker

### 附加信息

现在的面板环境，有点严重依赖于docker，在很多因素下，配置ip地址相关来说比较麻烦，反而不利于简化开发，可否增加一个需求，用于直接在可视化面板上 用 java -jar 启动jar包 而不是一定要依赖于docker

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述需求是希望直接使用 1Panel 服务器上手动安装的 Java 环境，启动已构建的 JAR 包吗？

**Comment by songzixian** [comment]
> 感谢反馈，上述需求是希望直接使用 1Panel 服务器上手动安装的 Java 环境，启动已构建的 JAR 包吗？

是的,类似宝塔一样,手动安装的 Java 环境,然后直接管理jar包的启动和停止,不依赖于docker

**Comment by chendong0801** [comment]
是的，1panel我个人感觉目前系统太过意依赖docker，这样面板其实次要还是在docker正常情况下运行，我希望的建议是，后期可以通过自己主动选择是否docker 还是本地jar运行，能够保证安全性和稳定性，也能灵活切换docker容器或本地的执行发布部署策略

**Comment by zhengkunwang223** [comment]
目前的运行环境逻辑我们短期内不会改
跟 OpenResty 等应用一样 如果我们要管理 二进制或者编译部署 需要做大量的系统适配工作
我们目前的工作重点还是在功能的丰富和优化上
感谢理解
