### ISSUE TITLE
[Bug] 在Almalinux无法在线安装面板

### ISSUE THREAD

**Issue by tyultra** [1Panel-dev/1Panel#7144]
### 1Panel 版本

1.10.21

### 问题描述

[1Panel Log]: ======================= 开始安装 ======================= 
设置 1Panel 安装目录（默认为/opt）：
[1Panel Log]: 您选择的安装路径为 /opt 
[1Panel Log]: ... 在线安装 docker 
[1Panel Log]: 非中国大陆地区，无需更改源 
# Executing docker install script, commit: 711a0d41213afabc30b963f82c56e1442a3efe1c

ERROR: Unsupported distribution 'almalinux'

[1Panel Log]: ... 启动 docker 
Failed to enable unit: Unit file docker.service does not exist.
Failed to start docker.service: Unit docker.service not found.
[1Panel Log]: docker 安装失败
您可以尝试使用安装包进行安装，具体安装步骤请参考以下链接：https://1panel.cn/docs/installation/package_installation/ 

### 重现步骤

在Almalinux8服务器运行：
curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sh quick_start.sh

### 期待的正确结果

能正常在线安装，或者通过安装包安装后能正常使用。

### 相关日志输出

```shell
[1Panel Log]: ======================= 开始安装 ======================= 
设置 1Panel 安装目录（默认为/opt）：
[1Panel Log]: 您选择的安装路径为 /opt 
[1Panel Log]: ... 在线安装 docker 
[1Panel Log]: 非中国大陆地区，无需更改源 
# Executing docker install script, commit: 711a0d41213afabc30b963f82c56e1442a3efe1c

ERROR: Unsupported distribution 'almalinux'

[1Panel Log]: ... 启动 docker 
Failed to enable unit: Unit file docker.service does not exist.
Failed to start docker.service: Unit docker.service not found.
[1Panel Log]: docker 安装失败
您可以尝试使用安装包进行安装，具体安装步骤请参考以下链接：https://1panel.cn/docs/installation/package_installation/
```

**Comment by wanghe-fit2cloud** [comment]
- 使用 `其他` 脚本试一下能否再现安装好 Docker，链接：https://1panel.cn/docs/installation/online_installation/
![image](https://github.com/user-attachments/assets/546a1b6a-5f4a-41dd-bacd-20a44f8f533f)

- 也可以选择离线包安装，链接：https://1panel.cn/docs/installation/package_installation/
![image](https://github.com/user-attachments/assets/928f43ae-a546-4d6c-901c-2ed1b8ef9d24)
