### ISSUE TITLE
[Bug] 安装PHP8失败，提示“状态说明：中断-系统重启导致状态获取失败”

### ISSUE THREAD

**Issue by tyultra** [1Panel-dev/1Panel#7145]
### 1Panel 版本

v1.10.21-lts

### 问题描述

在应用商店安装php8或者php7，都失败，提示“状态说明：中断-系统重启导致状态获取失败”。
![Uploading image.png…]()

### 重现步骤

在应用商店安装php8或者php7，都失败，提示“状态说明：中断-系统重启导致状态获取失败”。

**Comment by zhengkunwang223** [comment]
失败日志发一下
