### ISSUE TITLE
[Bug] 无法删除网站

### ISSUE THREAD

**Issue by wanyunr** [1Panel-dev/1Panel#7148]
### 1Panel 版本

社区版： v1.10.21-lts

### 问题描述

反代时若设置了sni，此时删除反代的上游网站，则会导致无法删除反代服务器上的网站
表现未以下报错，但是在配置文件目录查看，配置文件已被删除，但是面板上还是显示有网站
报错：
`服务内部错误: stderr: 2024/11/21 20:59:29 [emerg] 210#210: unknown "sni" variable nginx: [emerg] unknown "sni" variable`
![Clip_2024-11-21_21-07-36](https://github.com/user-attachments/assets/4c2a9a2f-2084-4af3-af9d-5955a0148c25)

反代配置
```
location ^~ / {
    set $sni "xxx.com; 
    proxy_pass https://1.1.1.1:443;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header X-Cache $upstream_cache_status; 
    add_header Cache-Control no-cache; 
    proxy_ssl_server_name on;
    proxy_ssl_name $sni;
    proxy_ssl_verify off; 
    add_header Strict-Transport-Security "max-age=31536000"; 
}
```

### 重现步骤

设置了sni，此时删除反代的上游网站，则会导致无法删除反代服务器上的网站

**Comment by zhengkunwang223** [comment]
能否贴一下你 sni 的网站完整配置

**Comment by wanyunr** [comment]
> 能否贴一下你 sni 的网站完整配置

已经没了，OpenResty删除重装了
配置就是使用默认的反代配置，没有手动添加配置，仅修改了反代配置
几个网站都是这样，都是使用的这个的反代配置
![Clip_2024-11-21_22-15-25](https://github.com/user-attachments/assets/46d9be14-75e9-4e87-bc71-931cc007b12d)

```
location ^~ / {
    set $sni "xxx.com; 
    proxy_pass https://1.1.1.1:443;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header X-Cache $upstream_cache_status; 
    add_header Cache-Control no-cache; 
    proxy_ssl_server_name on;
    proxy_ssl_name $sni;
    proxy_ssl_verify off; 
    add_header Strict-Transport-Security "max-age=31536000"; 
}
```

**Comment by zhengkunwang223** [comment]
如果是这种配置 应该是添加的时候就不支持的
<img width="1105" alt="image" src="https://github.com/user-attachments/assets/3a39a01e-5324-4b9b-b345-af55ef894b05">

**Comment by wanyunr** [comment]
> 如果是这种配置 应该是添加的时候就不支持的 <img alt="image" width="1105" src="https://private-user-images.githubusercontent.com/31820853/388559429-3a39a01e-5324-4b9b-b345-af55ef894b05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMDAyODgsIm5iZiI6MTczMjE5OTk4OCwicGF0aCI6Ii8zMTgyMDg1My8zODg1NTk0MjktM2EzOWEwMWUtNTMyNC00YjliLWIzNDUtYWY1NWVmODk0YjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDE0Mzk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNmVhMjc3N2U3ZTQwZTNiZGVlOWIyM2IxMDVlNmJjNjhkYTBiMTliOTk2NTQ0YTkyNjc5NWM1ZjNiOGVhYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c9lhuYnzxgCSSXGfXk6ZD_gt4Krk1AjK7iTCJ6nOkM8">

先添加普通反代配置，再修改反代配置

**Comment by zhengkunwang223** [comment]
<img width="654" alt="image" src="https://github.com/user-attachments/assets/67718def-5bd4-470d-be55-1493abb53f62">
我这样添加的源文 是可以删除的

**Comment by wanyunr** [comment]
> <img alt="image" width="654" src="https://private-user-images.githubusercontent.com/31820853/388564933-67718def-5bd4-470d-be55-1493abb53f62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzMwNjcsIm5iZiI6MTczMjI3Mjc2NywicGF0aCI6Ii8zMTgyMDg1My8zODg1NjQ5MzMtNjc3MThkZWYtNWJkNC00NzBkLWJlNTUtMTQ5M2FiYjUzZjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDEwNTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMDYxZGM0YmQ2NGUxYmMzM2E2MTBmMTM3NjJiY2U1MDgzMmRjZWUyY2YyMjNlOTI0ZGE3ZDYzN2Q4OTI3MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A8tdLfylUcYaHSIf_C0OQWpJU719WQiaLkciV2e6_Vw"> 我这样添加的源文 是可以删除的

把上游 8080端口的服务关了之后呢
