### ISSUE TITLE
[FEATURE]ssl证书增加一个多个不同域名ssl证书部署

### ISSUE THREAD

**Issue by 357341051** [1Panel-dev/1Panel#715]
### 1Panel 版本

1.1.1

### 请描述您的需求或者改进建议

很多站点，业务需求需要不同域名绑定证书，比如，用于腾讯分享时，防止主域名被封，一般都用于其他域名绑定，作为分享对象，还有类似业务需求店铺商店，每个店铺单独绑定域名的，并且加入证书，等等

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持该需求。

**Comment by zhengkunwang223** [comment]
经过我们讨论 建议你申请多个域名的证书 或者 泛域名证书
当然 如果你有好的实现方式 可以再与我们进行讨论
