### ISSUE TITLE
[Feature]  后续希望应用商店增加 casdoor  ，单点登录不错的项目 （10k star）

### ISSUE THREAD

**Issue by ByZhouhang** [1Panel-dev/1Panel#7151]
### 1Panel 版本

XX

### 请描述您的需求或者改进建议

https://github.com/casdoor/casdoor

![image](https://github.com/user-attachments/assets/155a8aa5-518b-42a8-bf43-f8c9980fba24)

**Comment by QYG2297248353** [comment]
### 第三方应用商店已支持
https://github.com/QYG2297248353/appstore-1panel/tree/custom/apps/casdoor

### 自动化安装脚本
一键式安装，无需手动操作，自动完成 1Panel应用 上架应用商店。

每三小时自动更新一次应用列表。
```sh
curl -sSL https://install.lifebus.top/auto_install.sh | bash
```

### 应用预览
![image](https://github.com/user-attachments/assets/2a67b2da-8168-441d-9a18-665c126ca97f)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，目前可以通过第三方仓库以本地应用的形式进行维护。
我们会在近期考虑将该应用上架。
重复 issue https://github.com/1Panel-dev/1Panel/issues/2013
