### ISSUE TITLE
[FEATURE]希望有docker pull 1panel

### ISSUE THREAD

**Issue by Fins03** [1Panel-dev/1Panel#716]
### 1Panel 版本

1.1.2

### 请描述您的需求或者改进建议

希望有docker pull 1panel:latest

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，您这是要制作 Docker 镜像并容器化运行 1Panel ？

**Comment by Fins03** [comment]
是的，如果可以的话

**Comment by SAENE** [comment]
同样希望

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们近期还是会以二进制方式来运行 1Panel，暂时不考虑容器化运行。
