### ISSUE TITLE
[Bug] Nginx 的 error_log 并不支持设置为 off

### ISSUE THREAD

**Issue by Xeath** [1Panel-dev/1Panel#7161]
### 联系方式

None

### 1Panel 版本

1.10.21-lts

### 问题描述

[Nginx 官方文档](https://nginx.org/en/docs/ngx_core_module.html#error_log)中关于 error_log 并未说明支持 off，并且直接写入日志到 nginx 所在工作目录下的 off 文件。
<img width="1141" alt="截屏2024-11-23 18 06 07" src="https://github.com/user-attachments/assets/ed87f5a7-4b91-46f9-8d23-f8a056851839">

### 重现步骤

创建一个站点，然后进去站点设置，点击日志，在左侧菜单中进入错误日志，关闭日志记录功能。

### 期待的正确结果

改用 `error_log /dev/null` 或者不指定该配置。

### 相关日志输出

```shell
无
```

### 附加信息

无

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们先在本地环境调研一下该需求。

**Comment by zhengkunwang223** [comment]
感谢反馈 我们下个版本优化

**Comment by wanghe-fit2cloud** [comment]
v1.10.22 版本已发布。
