### ISSUE TITLE
[Bug] `1pctl update port` 不会自动更新防火墙规则

### ISSUE THREAD

**Issue by WankkoRee** [1Panel-dev/1Panel#7164]
### 1Panel 版本

v1.10.21-lts

### 问题描述

在终端使用命令`1pctl update port`更新面板端口后，防火墙(`ufw`)规则依旧是旧端口。

### 重现步骤

`1pctl update port`

### 期待的正确结果

自动更新防火墙规则

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，经测试确认存在该问题，我们将在后续版本中进行优化。

**Comment by wanghe-fit2cloud** [comment]
v1.10.22 版本已发布。
