### ISSUE TITLE
[Bug] PasswordAuthentication no 在一些vps上可能失效

### ISSUE THREAD

**Issue by qwenode** [1Panel-dev/1Panel#7165]
### 1Panel Version

all

### Problem Description

有些vps会在 /etc/ssh/sshd_config.d/ 下写入配置
![image](https://github.com/user-attachments/assets/f4aae122-fdcd-42f9-acd4-882f4cdc9725)
然后
![image](https://github.com/user-attachments/assets/cae83cec-0e37-44d6-875c-731c208b630a)

如果配置是 
Include /etc/ssh/sshd_config.d/*.conf
PasswordAuthentication no #这行在include之后,则会无效

如果 
PasswordAuthentication no #则有效
Include /etc/ssh/sshd_config.d/*.conf

可能需要增加对/etc/ssh/sshd_config.d/ 下的配置检测

### Steps to Reproduce

如上

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，目前版本确实未同步 `/etc/ssh/sshd_config.d/*.conf` 目录下的配置，我们会在后续版本中考虑支持。

**Comment by wanghe-fit2cloud** [comment]
重复问题 https://github.com/1Panel-dev/1Panel/issues/4011
