### ISSUE TITLE
[Feature] 商店postgresql增加可添加postgis拓展的选项

### ISSUE THREAD

**Issue by ariwori** [1Panel-dev/1Panel#7175]
### 1Panel 版本

v1.10.21-lts

### 请描述您的需求或者改进建议

[Feature] 商店postgresql增加可添加postgis拓展的选项

**Comment by ariwori** [comment]
地信人急需，现在的方案是直接docker-compose替换镜像

**Comment by wan92hen** [comment]
感觉通过不同的应用版本来区分会合适些。

**Comment by wanghe-fit2cloud** [comment]
> 地信人急需，现在的方案是直接docker-compose替换镜像

建议以本地应用的形式进行维护。
参考 [1Panel 本地应用创建技巧及第三方应用库举例](https://bbs.fit2cloud.com/t/topic/640/)
