### ISSUE TITLE
[Bug] 进入端口转发功能界面提示：“端口转发功能依赖于 iptables 服务，暂不兼容 nftables 操作！”

### ISSUE THREAD

**Issue by Forensax** [1Panel-dev/1Panel#7177]
### 1Panel Version

 社区版： v1.10.21-lts

### Problem Description

[Bug] 进入端口转发功能界面提示：“端口转发功能依赖于 iptables 服务，暂不兼容 nftables 操作！”
系统自带 iptables 服务，nftables已禁止使用

### Steps to Reproduce

进入端口转发功能界面

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦提供一下 1Panel 服务器所运行操作系统的具体版本信息。

**Comment by Forensax** [comment]
> 感谢反馈，麻烦提供一下 1Panel 服务器所运行操作系统的具体版本信息。

```
机器一：Oracle amd64
ubuntu@docker1:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
ubuntu@docker1:~$ uname -a
Linux docker1 6.8.0-1013-oracle #13-Ubuntu SMP Mon Sep  2 11:35:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
机器二：Oracle arm64
ubuntu@arm1:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
ubuntu@arm1:~$ uname -a
Linux arm1 6.8.0-1016-oracle #17-Ubuntu SMP Wed Nov  6 23:29:36 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

```
以前没有问题，最近删机器重建出现了此问题

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈，麻烦提供一下 1Panel 服务器所运行操作系统的具体版本信息。
> 
> ```
> 机器一：Oracle amd64
> ubuntu@docker1:~$ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 24.04.1 LTS
> Release:        24.04
> Codename:       noble
> ubuntu@docker1:~$ uname -a
> Linux docker1 6.8.0-1013-oracle #13-Ubuntu SMP Mon Sep  2 11:35:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
> 机器二：Oracle arm64
> ubuntu@arm1:~$ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 24.04.1 LTS
> Release:        24.04
> Codename:       noble
> ubuntu@arm1:~$ uname -a
> Linux arm1 6.8.0-1016-oracle #17-Ubuntu SMP Wed Nov  6 23:29:36 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
> ```
> 
> 以前没有问题，最近删机器重建出现了此问题

收到，我们近期版本修复一下该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.10.22 版本已发布。
