### ISSUE TITLE
[Feature] 有计划更新运行net项目吗？以及支持通用项目。

### ISSUE THREAD

**Issue by mimimiaomiao1** [1Panel-dev/1Panel#7184]
### 1Panel Version

1

### Please describe your needs or suggestions for improvements

请问计划日期有不。。。

**Comment by wanghe-fit2cloud** [comment]
将在下个版本 v1.10.22 中支持。

**Comment by wan92hen** [comment]
通用项目指的是什么意思呢？

**Comment by mimimiaomiao1** [comment]
> 通用项目指的是什么意思呢？

不好意思，我说错了，是其他项目。。
例如我发布一个netcore的控制台程序，放到系统上之后，我直接就dotnet命令就能启动这个程序。
选择路径，输入启动命令。

**Comment by zhengkunwang223** [comment]
> > 通用项目指的是什么意思呢？
> 
> 不好意思，我说错了，是其他项目。。 例如我发布一个netcore的控制台程序，放到系统上之后，我直接就dotnet命令就能启动这个程序。 选择路径，输入启动命令。

supervisor 也行吧

**Comment by wanghe-fit2cloud** [comment]
v1.10.22 版本已发布。
