### ISSUE TITLE
是不是看不懂问题？我说的是安装和编辑的时候，那个界面上显示默认不要显示明文，应该显示*

### ISSUE THREAD

**Issue by persiliao** [1Panel-dev/1Panel#7187]
这个配置是要写到应用的配置文件的 
而且密码也要方便查看
所以只能用明文

_Originally posted by @zhengkunwang223 in https://github.com/1Panel-dev/1Panel/issues/7180#issuecomment-2499445301_

**Comment by persiliao** [comment]
再者，有这样处理问题吗？回一下直接就关了issue?

**Comment by zhengkunwang223** [comment]
> 再者，有这样处理问题吗？回一下直接就关了issue?

我们只是把这个问题转移到讨论中，你具体是哪个应用的密码呢？

**Comment by persiliao** [comment]
我试了好几个应用，像frps这种需要配置密钥之类的

**Comment by persiliao** [comment]
![image](https://github.com/user-attachments/assets/01d99cee-5727-466f-a0eb-ce14294840ac)

**Comment by persiliao** [comment]
因为现在很多应用会读取屏幕，这样很容易造成泄漏

**Comment by zhengkunwang223** [comment]
> 因为现在很多应用会读取屏幕，这样很容易造成泄漏

![image](https://github.com/user-attachments/assets/d1a9c813-aa15-4d25-bbee-c4407cd371d2)

大部分应用填写的时候是有密码组件控制的，可能有一些没有加，我们会在后续不断更新，至于查看，作用就是为了查看密码，全搞成*也不好

**Comment by persiliao** [comment]
那可能刚好是我用的那几个都没有加吧。。。

**Comment by wanghe-fit2cloud** [comment]
https://github.com/1Panel-dev/1Panel/discussions/7182
