### ISSUE TITLE
[Feature] 关于应用升级对自定义参数的保留

### ISSUE THREAD

**Issue by yfdoor** [1Panel-dev/1Panel#7188]
### 1Panel 版本

1.10.21

### 请描述您的需求或者改进建议

应用升级的时候提供对比，这个非常好，但是当选择使用自定义版本后，下面的  docker-compose.yml 文件却没有把自定义的内容带过来，比如：Alist 我修改了UID/GID，但是文件中却还是 0/0
![image](https://github.com/user-attachments/assets/71f196ac-48f3-4cdb-8402-a827893b0cec)

![image](https://github.com/user-attachments/assets/740355bd-77df-4739-b978-47b7ab754888)

### 请描述你建议的实现方案

希望当选择使用自定义后，可以把修改多的内容带过来，只是把镜像版本改为最新版

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
使用自定义版本时，首先要求用户在对比界面中将旧版本中的修改内容有选择地迁移到新版本的 Compose 文件中，完成后再点击 `使用自定义版本`，如图：
<img width="1328" alt="image" src="https://github.com/user-attachments/assets/e03d8113-c06a-44d3-9c96-661b84cf92e9">
