### ISSUE TITLE
[FEATURE]计划任务可自定义超时时间

### ISSUE THREAD

**Issue by moonotes** [1Panel-dev/1Panel#719]
### 1Panel 版本

v1.1.1

### 请描述您的需求或者改进建议

shell 计划任务执行时间超过5分钟默认状态为失败，且无日志记录。

希望在创建计划任务时新增超时时间配置。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会优化上述上述需求。

**Comment by wanghe-fit2cloud** [comment]
最新版本中，创建 Shell 类型的计划任务超时时间已经默认为 24h，建议将系统升级到最新版本。
