### ISSUE TITLE
[Feature] 请商店支持DeepLX,私有化 DeepLX 服务的部署

### ISSUE THREAD

**Issue by 46fafa** [1Panel-dev/1Panel#7190]
### 1Panel 版本

v1.10.21-lts

### 请描述您的需求或者改进建议

希望能上线[DeepLX](https://github.com/OwO-Network/DeepLX)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈！
目前，我们主要将项目的 Star 数量作为重要参考指标。
由于团队资源有限，我们暂时专注于维护 Star 数超过 1 万的开源项目，感谢您的理解。

该应用已在 [第三方商店](https://github.com/okxlin/appstore/tree/localApps/apps/deeplx) 上架，建议您通过本地应用的方式进行安装。
