### ISSUE TITLE
[Feature] 希望应用商店支持DooTask的一键安装部署

### ISSUE THREAD

**Issue by allyn0303** [1Panel-dev/1Panel#7193]
### 1Panel 版本

v1.10.21-lts

### 请描述您的需求或者改进建议

希望应用商店支持DooTask的一键安装部署。
开源地址：https://github.com/kuaifan/dootask/tree/pro
目前4.7k星星，网上反馈挺不错的，挺受欢迎的一款开源项目管理工具
DooTask是一款开源在线项目任务管理工具，提供各类文档协作工具、在线思维导图、在线流程图、项目管理、任务分发、即时IM，文件管理等工具；同时消息功能使用非对称加密技术让你的沟通更安全。

**Comment by allyn0303** [comment]
它还有一个普通版，希望也能同时支持
https://github.com/kuaifan/dootask/blob/v0.13.0/README_CN.md
支持普通版和pro版本部署

**Comment by allyn0303** [comment]
它的官网：https://www.dootask.com/site/zh/product.html

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，我们主要以项目的 Star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有超 1 万 Star 的开源项目，感谢您的理解。

> 你可以将需求反馈给 [第三方仓库（由社区用户维护）](https://github.com/okxlin/appstore)。
