### ISSUE TITLE
[Bug] 应用商店重复数越来越多，如何解决？

### ISSUE THREAD

**Issue by chun-all** [1Panel-dev/1Panel#7199]
### 1Panel 版本

专业版v1.10.21-lts

### 问题描述

![Snipaste_2024-11-27_16-20-24](https://github.com/user-attachments/assets/16fa593f-0486-49c6-b497-8615f5902991)
![Snipaste_2024-11-27_15-53-07](https://github.com/user-attachments/assets/40169d80-fec8-48bb-b0fa-24ec04109678)
首页及应用商店重复数越来越多，如何解决？

### 重现步骤

应该是机子重启后，个数就会增多，重启一次加一个重复的。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈！上述问题确实存在于 NAS 产品中，但由于尚未在相关设备上进行测试，目前暂无法提供解决方案，敬请谅解。

**Comment by wanghe-fit2cloud** [comment]
重复 issue https://github.com/1Panel-dev/1Panel/issues/4004
