### ISSUE TITLE
[FEATURE] 希望网站的默认文档可以设置为子目录的文件

### ISSUE THREAD

**Issue by orilights** [1Panel-dev/1Panel#720]
### 1Panel 版本

v1.1.2

### 请描述您的需求或者改进建议

希望网站的默认文档可以设置为子目录的文件，目前带斜杠的话默认文档的配置无法保存，要使用h5ai之类的程序只能手动改配置

![image](https://user-images.githubusercontent.com/61224409/233125105-e18b169f-f0ac-4f25-af57-63c1e8482a06.png)

**Comment by 357341051** [comment]
这个貌似已经有运行目录更改了吧

**Comment by orilights** [comment]
> 这个貌似已经有运行目录更改了吧

不是一个功能吧，h5ai是一个目录列表程序，需要在子文件夹没有默认文档的时候显示h5ai的界面列出子文件夹的文件，只改运行目录做不到这一点，而且运行目录也只能选二级目录，h5ai这个在三级

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
