### ISSUE TITLE
[Feature] Request to add English translation for apps' README in the App Store

### ISSUE THREAD

**Issue by JohnNiang** [1Panel-dev/1Panel#7201]
### 1Panel Version

v1.10.21-lts

### Please describe your needs or suggestions for improvements

![image](https://github.com/user-attachments/assets/349dd1ca-391c-4cb5-b274-e6bf533d94ea)

### Please describe the solution you suggest

 I'm not sure what we should do exactly. But at least, `README_en.md` file might be able to be added for every app data in <https://github.com/1Panel-dev/appstore>.

**Comment by wanghe-fit2cloud** [comment]
We can start by providing a README_en.md file for the initial batch of applications to be listed in the store. The planned applications for the first batch include:

- [x] OpenResty
- [x] MySQL
- [x] Redis
- [x] AList
- [x] WordPress
- [x] phpMyAdmin
- [x] Nginx Proxy Manager
- [x] PostgreSQL
- [x] Ollama
- [x] Gitea
- [x] Act Runner
- [x] MariaDB
- [x] MinIO
- [x] RustDesk
- [x] Bitwarden
- [x] Uptime Kuma
- [x] MongoDB
- [x] Nextcloud
- [x] code-server
- [x] JumpServer
- [x] Memos
- [x] Home Assistant
- [x] IT-Tools
- [x] Jellyfin
- [x] AdGuardHome
- [x] SFTPGo
- [x] Stirling-PDF
- [x] Draw.io
- [x] Jenkins
- [x] Ollama WebUI
- [x] Adminer
- [x] PgAdmin4
- [x] Portainer-CE
- [x] PHP 8
- [x] PHP 7
- [x] PHP 5
- [x] Java
- [x] Node.js
- [x] Go
- [x] Python
- [x] Palworld Server
- [x] Palworld Server Tool
- [x] Metabase
- [x] Mailserver
- [x] Maddy Mail Server
- [x] Roundcube

**Comment by JohnNiang** [comment]
I'm going to close this issue as completed.
