### ISSUE TITLE
[Feature] 希望支持xiaomusic

### ISSUE THREAD

**Issue by sunkolin** [1Panel-dev/1Panel#7202]
### 1Panel 版本

v1.10.21-lts

### 请描述您的需求或者改进建议

希望支持xiaomusic，项目地址是https://github.com/hanxi/xiaomusic

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
目前，我们主要以项目的 Star 数量作为重要的指标。
鉴于团队资源有限，我们目前只专注于维护那些拥有超 1 万 Star 的开源项目，感谢您的理解。

> 你可以将需求反馈给 [第三方仓库（由社区用户维护）](https://github.com/okxlin/appstore)。

**Comment by wanghe-fit2cloud** [comment]
感谢 @Anyexyz 
https://github.com/1Panel-dev/appstore/pull/5626
