### ISSUE TITLE
[Bug] 终端新建连接，同一个主机地址会覆盖

### ISSUE THREAD

**Issue by web222vip** [1Panel-dev/1Panel#7204]
### 联系方式

g_2007@qq.com

### 1Panel 版本

v1.10.21-lts

### 问题描述

IP地址：127.0.0.1
端口：22 33 44 这是三个主机，通过端口转发连接。
但是目前的终端 1个主机ip地址，只能新增一个，后面新增的会被覆盖掉

如图所示
![image](https://github.com/user-attachments/assets/6acd664a-db89-4a59-8cca-5e8b26297661)

### 重现步骤

很容易实现。

### 期待的正确结果

ip地址+端口 形成一个新的连接

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
由于 `127.0.0.1` 是系统默认用于连接本地服务器终端的特殊 IP，因此只能保留一个实例。
在主机页面中添加其他主机时，支持为同一 IP 配置不同的 SSH 端口，如下图所示：
![image](https://github.com/user-attachments/assets/f01ffd05-522f-47fc-a58f-65ef77a1301e)
