### ISSUE TITLE
[Feature] 应用商店建议新增teslamate 这款应用。

### ISSUE THREAD

**Issue by 582911658** [1Panel-dev/1Panel#7209]
### 1Panel 版本

社区版： v1.10.21-lts

### 请描述您的需求或者改进建议

应用商店建议新增teslamate 这款应用。项目地址如下：https://github.com/teslamate-org/teslamate

### 请描述你建议的实现方案

建议新增，支持一键部署。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，重复 issue https://github.com/1Panel-dev/1Panel/issues/4947
