### ISSUE TITLE
[Bug] Set the security entrance to "login" during installation and cannot access it normally.

### ISSUE THREAD

**Issue by nightx521** [1Panel-dev/1Panel#7219]
### Contact Information

2964749837@qq.com

### 1Panel Version

v1.10.21-lts

### Problem Description

首次安装1panel时提示设置安全入口，将其设置成"login"提示设置成功，但是无法正常通过安全入口访问。在网址栏输入http://$LOCAL_IP:8888/login 会自动跳转到http://$LOCAL_IP:8888，并提示暂无权限访问。

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/6a6f72aa-1bf6-4352-8ae1-1956d28d6536)
![image](https://github.com/user-attachments/assets/9666b7fc-71c4-485a-b151-61c973adcad8)

### The expected correct result

正常通过安全入口进入登录页。

**Comment by wanghe-fit2cloud** [comment]
当前，`login` 是系统默认的登录接口，因此暂时不支持将其设置为安全入口。
你可以使用 `1pctl reset entrance` 命令删除当前的安全入口，登录系统后进入面板设置中的 `安全` 页面，再次配置安全入口。
