### ISSUE TITLE
[FEATURE] 文件管理里面，编辑文件时，标题栏应该显示当前文件的文件名

### ISSUE THREAD

**Issue by hhun** [1Panel-dev/1Panel#722]
### 1Panel 版本

1.1.2

### 请描述您的需求或者改进建议

文件管理里面，编辑文件时，标题栏应该显示当前文件的文件名

最好是再加个保存按键，虽然现在可以通过快捷键保存，有按钮会更直观。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by zyyfit** [comment]
最新版 1.2.2 已经修改了标题显示，另外，窗口右下方的确认按钮可以保存并关闭文件
