### ISSUE TITLE
[Bug] In X-Pack WAF function, interception record, action, hit rule, data display is empty, hope to optimize

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#7223]
### Contact Information

niujinkai@vip.qq.com

### 1Panel Version

专业版： v1.10.21-lts

### Problem Description

[Bug] X-Pack WAF 功能中 拦截记录 动作 和 命中规则 数据展示为空 希望优化
在halo博客中，安装了瞬间插件，发布瞬间的时候，提交的数据是带有html格式的，应该是出发了waf拦截，拦截记录中的 动作 和 命中规则没显示。
详情见附件
![image](https://github.com/user-attachments/assets/d764ccd8-1c57-4a80-bf5c-28d3bf0d63ec)
![image](https://github.com/user-attachments/assets/3a6d6a1f-42d6-4c98-97c9-9330555cf4d8)

### Steps to Reproduce

在halo博客中，安装了瞬间插件，发布瞬间的时候，提交的数据是带有html格式的，应该是出发了waf拦截，拦截记录中的动作没显示。

### The expected correct result

正常展示拦截动作和命中规则。
类似于：
![image](https://github.com/user-attachments/assets/9513b057-4b1b-411b-b3a0-7c2555b8800a)

### Additional Information

![image](https://github.com/user-attachments/assets/d764ccd8-1c57-4a80-bf5c-28d3bf0d63ec)
![image](https://github.com/user-attachments/assets/3a6d6a1f-42d6-4c98-97c9-9330555cf4d8)

**Comment by wanghe-fit2cloud** [comment]
Thanks for your feedback. Future versions will consider supporting WAF application whitelists. 
Specific requirements will be consolidated in issue #4636.
