### ISSUE TITLE
[Feature] Support API for everything in the future

### ISSUE THREAD

**Issue by asdf2adsfad** [1Panel-dev/1Panel#7230]
### 1Panel Version

all

### Please describe your needs or suggestions for improvements

This enables integration with softwares like terraform and batch management.

**Comment by wanghe-fit2cloud** [comment]
The current version now supports Swagger. You can access it at: `your-panel-address/1panel/swagger/index.html`

In upcoming versions, API keys will also be supported. For more details, see: https://github.com/1Panel-dev/1Panel/issues/414.
