### ISSUE TITLE
[Bug] Unable to access using ipv6 address

### ISSUE THREAD

**Issue by joney888999** [1Panel-dev/1Panel#7231]
### 1Panel Version

v1.10.21-lts

### Problem Description

使用ipv6地址加端口无法访问，我已经关闭了安全入口

### Steps to Reproduce

使用ipv4可以访问
![image](https://github.com/user-attachments/assets/7c61d2e5-2b56-4217-b9e0-9766d0814425)
使用ipv6无法访问
![image](https://github.com/user-attachments/assets/545b5a29-861f-4d91-a7a5-d98893fbde4c)

**Comment by wanghe-fit2cloud** [comment]
Thanks for your feedback! You can try using `1pctl listen-ip ipv6` to switch to IPv6 mode, then access 1Panel through your browser.

	You can use `netstat -tunlp` to check if 1Panel is already listening on an IPv6 address.

**Comment by joney888999** [comment]
可以了，谢谢

**Comment by joney888999** [comment]
刚刚能访问过了一会又访问不了，执行netstat -tunlp输出如下：
![image](https://github.com/user-attachments/assets/0757e8d4-34dd-4884-85d9-1c58092f6995)
![image](https://github.com/user-attachments/assets/f6c35630-38c0-4ec6-84da-ba1238fd62b7)
![image](https://github.com/user-attachments/assets/336c7ed3-7d4b-4b69-a37c-5a5e9f2b5f0b)

**Comment by wanghe-fit2cloud** [comment]
可以使用 1pctl status 命令查看系统运行状态。如果显示为 running 且端口正常绑定，建议优先排查服务器的网络环境是否存在问题。
