### ISSUE TITLE
[Feature] Can you provide the dockerfile used to compile the 1panel source code?

### ISSUE THREAD

**Issue by ganyu123456** [1Panel-dev/1Panel#7233]
### 1Panel Version

1.0.22

### Please describe your needs or suggestions for improvements

能否提供dockerfile是用来编译1panel源码，我想定制化前端页面，比如修改图标之类的，但是无法编译成镜像放在docker里运行

### Please describe the solution you suggest

能否提供dockerfile是用来编译1panel源码，我想定制化前端页面，比如修改图标之类的，但是无法编译成镜像放在docker里运行

**Comment by wanghe-fit2cloud** [comment]
1Panel only provides a Makefile for compiling binary files and does not recommend running it in a containerized environment, as some features may not work properly.

**Comment by wanghe-fit2cloud** [comment]
If you need to deploy using containers, you can refer to this project: https://github.com/okxlin/docker-1panel.
