### ISSUE TITLE
[Feature]Automatically clean up leftover installation packages

### ISSUE THREAD

**Issue by Jasonzhu1207** [1Panel-dev/1Panel#7234]
### 1Panel Version

1.10.21

### Please describe your needs or suggestions for improvements

一键脚本新安装或面板内点击更新后会残留一个安装包再root里，希望可以自动删除安装包残留或将安装包残留这一项添加到工具箱的缓存清理这一功能的扫描范围之内

### Please describe the solution you suggest

安装或更新后自动删除安装包残留或将安装包残留这一项添加到工具箱的缓存清理这一功能的扫描范围之内

**Comment by wanghe-fit2cloud** [comment]
1、安装完成后，安装日志等信息会存放在解压后的安装包目录中，建议手动删除这些安装文件。
2、点击右下角的升级系统时，备份文件和升级文件将存放在 1Panel 安装目录的临时目录中，这部分资源可以通过工具箱中的缓存清理功能进行清理。
