### ISSUE TITLE
[Bug] Accessing a specific link returns 403

### ISSUE THREAD

**Issue by hhrensheng** [1Panel-dev/1Panel#7235]
### 1Panel Version

v1.10.21-lts

### Problem Description

PHP网站 ，网站如果链接包含`runtime`关键字，openresty 返回链403，关闭waf无效

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/6026b713-0ded-4c94-8d09-eb0d56df4e2f)

### The expected correct result

![image](https://github.com/user-attachments/assets/eb3637c5-b269-4815-87fc-f55a44ade061)

**Comment by zhengkunwang223** [comment]
看你的代码 是应该返回 404 是吗？

**Comment by hhrensheng** [comment]
> 看你的代码 是应该返回 404 是吗？

是的，应该返回“404方法不存在”才是正确的

**Comment by zhengkunwang223** [comment]
> > 看你的代码 是应该返回 404 是吗？
> 
> 是的，应该返回“404方法不存在”才是正确的

麻烦提供一下网站的日志 和 OpenResty 的日志

**Comment by hhrensheng** [comment]
[网站日志.log](https://github.com/user-attachments/files/17974693/default.log)
[OpenResty日志.txt](https://github.com/user-attachments/files/17974695/OpenResty.txt)

**Comment by zhengkunwang223** [comment]
看日志没有什么异常 你重建一下 OpenResty 再试试
你的 nginx 或者 php-fpm 配置文件中有包含deny runtime 路径的配置吗？

**Comment by hhrensheng** [comment]
> 看日志没有什么异常 你重建一下 OpenResty 再试试 你的 nginx 或者 php-fpm 配置文件中有包含deny runtime 路径的配置吗？

没有单独安装nginx，PHP都是默认安装的，只多装了几个扩展，但是都是常用的在其他环境没有这个问题。

**Comment by zhengkunwang223** [comment]
![image](https://github.com/user-attachments/assets/4295c110-931a-43d0-bb97-250d0bfe07e4)
添加我的企业微信 我远程看一下

**Comment by hhrensheng** [comment]
> ![image](https://private-user-images.githubusercontent.com/31820853/391464316-4295c110-931a-43d0-bb97-250d0bfe07e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjgwNjYsIm5iZiI6MTczMzEyNzc2NiwicGF0aCI6Ii8zMTgyMDg1My8zOTE0NjQzMTYtNDI5NWMxMTAtOTMxYS00M2QwLWJiOTctMjUwZDBiZmUwN2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDA4MjI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZGYyY2RhNTU3YzJhZjQyZTgwMThkMDE4ZDU1MDdmZmIyNjdiOWVlNDA3Zjg5ZjM4MDcwMDdlZTljODIxMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ew4tQ1y0LjqUz-VvzDJnXZ9wjtKgHoGgqzNTAzxoszk) 添加我的企业微信 我远程看一下

已加

**Comment by zhengkunwang223** [comment]
经过远程 是因为伪静态中配置了禁止访问目录 并返回 403 状态码的问题
