### ISSUE TITLE
[Feature] Website default page, is it possible to distinguish website settings? Can internationalization be supported?

### ISSUE THREAD

**Issue by ByZhouhang** [1Panel-dev/1Panel#7237]
### 1Panel Version

xx

### Please describe your needs or suggestions for improvements

1、网站默认停止页，如果不同的站点，想不同的页面，目前无法做到
2、比如网站停止页，想根据用户的请求，显示中文 或者英文停止页，目前无法做到

**Comment by zhengkunwang223** [comment]
1. 可以修改配置文件来实现
2. 这个面板是不适合做的 “根据用户请求” 这个就是个很广泛的东西 需要有通用切具体的参数 才行
