### ISSUE TITLE
armbian system installation failed

### ISSUE THREAD

**Issue by IsDreame** [1Panel-dev/1Panel#7240]
### Contact Information

3497440533@qq.com

### 1Panel Version

1.10.21

### Problem Description

![image](https://github.com/user-attachments/assets/9abcd7de-288c-4836-955f-1fb8fdb40f20)
![image](https://github.com/user-attachments/assets/2c442de8-7455-4ac3-b314-2b45866d03bb)

### Steps to Reproduce

根据图片命令

### The expected correct result

安装之后，没有端口，用户名，密码输入操作，直接显示已经安装，但是输入 1pctl 没有任何反应

### Related log output

```shell
[1Panel Log]: ======================= 开始安装 ======================= 
[1Panel Log]: 1Panel Linux 服务器运维管理面板已安装，请勿重复安装 
root@armbian:~/1panel-v1.10.21-lts-linux-arm64#
```

### Additional Information

![image](https://github.com/user-attachments/assets/0b683a6b-e51b-42a4-bb82-2679a3e068c0)

**Comment by wanghe-fit2cloud** [comment]
安装脚本通过 which 1panel 命令来判断是否已安装。如果确定是首次安装 1Panel，可以先注释掉 install.sh 脚本中的判断逻辑，如图所示：
![image](https://github.com/user-attachments/assets/569e8e71-a01f-4f57-bb64-a06efbdf7a76)
