### ISSUE TITLE
[Bug] An error will be reported when the scheduled task executes the command of the httpie package

### ISSUE THREAD

**Issue by Firfr** [1Panel-dev/1Panel#7241]
### 1Panel Version

社区版： v1.10.21-lts

### Problem Description

在计划任务中执行命令
```
http -f POST "${gotify_url}" title="PC-PVE温度调试" message="当前CPU温度: ${temperature}" priority="0"
```
httpie 会报错,提示格错误
但是将计划任务中的内容写在一个脚本中,在终端中手动执行没有问题,正常执行
我重启1panel后还会遇到,我该成curl了,是1panel的问题还是httpie的问题

### Steps to Reproduce

在计划任务中执行命令
```
http -f POST "${gotify_url}" title="PC-PVE温度调试" message="当前CPU温度: ${temperature}" priority="0"
```
httpie 会报错,提示格错误
但是将计划任务中的内容写在一个脚本中,在终端中手动执行没有问题,正常执行

**Comment by wanghe-fit2cloud** [comment]
> httpie 会报错，提示格错误

麻烦提供一下具体的错误信息，方便排查问题。也可以尝试使用 `/usr/bin/http` 全路径测试一下。

**Comment by Firfr** [comment]
下面两个代码是一样的,一个在计划任务中执行,一个在ssh登录后手动执行
![2024-12-03_15-26-35](https://github.com/user-attachments/assets/9208a2af-172b-4bf1-94ce-5cfe14e94ff9)
![2024-12-03_15-27-00](https://github.com/user-attachments/assets/d3731304-725d-4586-bc80-aa1e9cab6f72)

**Comment by ssongliu** [comment]
这里是环境变量的问题，计划任务执行使用的是 bash -c，建议脚本里面的 http 使用全路径，如 /usr/bin/http

**Comment by ssongliu** [comment]
因为太久没有回复，暂时关闭该 issue，如果仍有问题可以再次打开

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Because there has been no reply for a long time, I have temporarily closed this issue. If you still have problems, you can open it again.
