### ISSUE TITLE
[Feature] When executing a command with a progress bar in a scheduled task, the log is abnormal.

### ISSUE THREAD

**Issue by Firfr** [1Panel-dev/1Panel#7242]
### 1Panel Version

社区版： v1.10.21-lts

### Please describe your needs or suggestions for improvements

在计划任务中执行 例如 `docker pull xhofe/alist:latest` 时,在报告记录中,其中进度条的部分显示不正常

**Comment by wanghe-fit2cloud** [comment]
麻烦提供一下相关的截图或其他信息，帮忙我们更好地定位问题。

**Comment by Firfr** [comment]
我模拟了一个输出进度条的代码
```bash
#!/bin/bash

# 进度条函数
print_progress_bar() {
    local percent=$1
    local width=50  # 进度条的宽度
    local filled=$((percent * width / 100))
    local bar=""

    for ((i=0; i<filled; i++)); do
        bar+="█"
    done

    for ((i=filled; i<width; i++)); do
        bar+=" "
    done

    echo -ne "\r[ ${bar} ] ${percent}%"
}

# 模拟进度
for percent in $(seq 0 1 100); do
    print_progress_bar $percent
    sleep 0.05  # 模拟进度的延迟
done

echo  # 最后换行
```
在计划任务中的输出
![2024-12-03_15-35-06](https://github.com/user-attachments/assets/7e1b4883-a430-47e1-ac9a-dfe7a1561946)

手动执行后的输出
![2024-12-03_15-35-23](https://github.com/user-attachments/assets/25d4cf29-157e-4fa6-9dc2-1f2959ed79f7)

**Comment by ssongliu** [comment]
感谢反馈，这里初步判断是编码的问题，但是经测试发现，Go 语言的 exec.Command 执行外部命令时，进度条通常不会输出到 标准输出（stdout）和标准错误（stderr），从而导致执行日志文件内不存在进度条内容。
