### ISSUE TITLE
[Feature] [Website]-[Running Environment] The pnpm version of the Node.js environment is too old

### ISSUE THREAD

**Issue by 7FreezingPoint** [1Panel-dev/1Panel#7244]
### 1Panel Version

v1.10.21-lts

### Please describe your needs or suggestions for improvements

![image](https://github.com/user-attachments/assets/657190e0-bdf1-4d0c-8acb-d8e07df5725b)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈！目前，1panel/node 镜像已完成更新并推送至 docker hub，可以重新拉取所需的目标版本镜像。以 20.14.0 版本为例：
```shell
docker pull 1panel/node:20.14.0
```
