### ISSUE TITLE
[Bug] App store metabase startup exception

### ISSUE THREAD

**Issue by huyi-work** [1Panel-dev/1Panel#7245]
### 1Panel Version

v1.10.21-lts

### Problem Description

<img width="540" alt="截屏2024-12-03 15 48 50" src="https://github.com/user-attachments/assets/e8cb08e8-5412-4770-8dbb-bffb2bed077b">
<img width="660" alt="截屏2024-12-03 15 49 07" src="https://github.com/user-attachments/assets/b3db9c3d-7ff0-4a01-8947-d45b48ffcce1">
<img width="1218" alt="截屏2024-12-03 15 49 18" src="https://github.com/user-attachments/assets/72c58eac-691a-4516-8012-845a2d2f120f">

### Steps to Reproduce

在linux arm 环境下，安装metabase

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。目前，Metabase 官方尚未支持 ARM 架构，具体情况如下图所示。
![image](https://github.com/user-attachments/assets/eeb0b05b-af80-40d8-9776-1cc95c7eed19)
