### ISSUE TITLE
[FEATURE]建议在数据库选项卡中增加同步数据库按钮，将所有库同步到面板中管理

### ISSUE THREAD

**Issue by iucvcom** [1Panel-dev/1Panel#725]
### 1Panel 版本

v1.1.2

### 请描述您的需求或者改进建议

当我创建计划任务备份全库时，只有在面板中的库才会被备份。但其实我的mysql中还有很多库没被同步。这些库是使用其他客户端工具创建或导入的。

### 请描述你建议的实现方案

在数据库选项卡中增加同步数据库按钮，点击后将所有库的信息同步到面板中统一管理。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持该需求。

**Comment by Ghost-chu** [comment]
同样非常需要这个功能

**Comment by ssongliu** [comment]
v1.5.0 已支持上述功能。
