### ISSUE TITLE
[Feature] Optimize the error messages for modifying or deleting website files with anti-tamper functionality enabled

### ISSUE THREAD

**Issue by wan92hen** [1Panel-dev/1Panel#7258]
### 1Panel Version

v1.10.21

### Please describe your needs or suggestions for improvements

Optimize the error messages for modifying or deleting website files with anti-tamper functionality enabled, so that users can understand that it is due to the activation of anti-tamper features.

![image](https://github.com/user-attachments/assets/220183c2-f6fd-4fbb-b1fc-bcef139e17ce)
![image](https://github.com/user-attachments/assets/38b36554-53f6-4169-a3c9-140017bb343f)

**Comment by wanghe-fit2cloud** [comment]
duplicate issue https://github.com/1Panel-dev/1Panel/issues/4710
