### ISSUE TITLE
[Bug] When saving the password in the database interface, it prompts that special characters cannot be saved.

### ISSUE THREAD

**Issue by KingOfGitH** [1Panel-dev/1Panel#7259]
### 1Panel Version

v1.10.21-lts

### Problem Description

数据库密码保存界面，特殊字符无法保存
/apps/all?install=postgresql
![image](https://github.com/user-attachments/assets/894d77a1-ef60-4ab7-8c24-3b9d562e8f0f)
/databases/postgresql
![image](https://github.com/user-attachments/assets/a83571fa-7424-4c95-81e3-5af768cd900f)

### Steps to Reproduce

在填写密码出填入特殊字符即可

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。由于可能存在注入等安全风险，目前仅支持部分特殊字符。
关于密码复杂度的相关问题，统一集中到 [#4290](https://github.com/1Panel-dev/1Panel/issues/4290) 进行讨论。
