### ISSUE TITLE
[FEATURE] docker 安装的应用映射端口会绕过 firewalld ufw 防火墙

### ISSUE THREAD

**Issue by zhengkunwang223** [1Panel-dev/1Panel#726]
### 1Panel 版本

v1.1.2

### 描述
docker 启动容器的时候，如果映射了外部端口，并且是0.0.0.0:port 模式，会自动在 iptables 添加规则，放开端口  
绕过 firewalld 和 ufw ，如果宿主机没有安全组，会带来安全隐患
docker issue https://github.com/moby/moby/issues/4737

### 解决方案
1Panel 安装的应用提供设置本地访问选项，增加安全性

### 请描述你建议的实现方案

从 1Panel 应用上商店安装软件，填写参数增加可选择项 ：限制仅本地访问

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。

**Comment by KamiPasi** [comment]
这个修复了吗, 现在好像docker映射的端口, 还是会开放, 关不掉
