### ISSUE TITLE
[Bug] After downloading and decompressing the pg backup database, the .sql file is garbled.

### ISSUE THREAD

**Issue by jeepc** [1Panel-dev/1Panel#7265]
### 1Panel Version

 v1.10.21-lts

### Problem Description

![微信截图_20241205161903](https://github.com/user-attachments/assets/97a12c9e-6a4c-461a-8d72-b41753ce01a0)

### Steps to Reproduce

使用计划任务备份postgresql数据库，在备份列表下载文件，解压缩，查看.sql文件乱码

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们已在本地环境复现了该问题（不影响数据库的正常恢复）。
> 我们先在本地环境尝试修复一下该问题。

**Comment by ssongliu** [comment]
感谢反馈，因为 pg_restore 恢复的时候仅支持下面三种格式，不支持直接从 sql 文件恢复，所以备份的时候也是采用的 -F c
![image](https://github.com/user-attachments/assets/f86f16f3-b848-45f0-9d1e-1a9279c33975)

如果想要导出 sql 文件，可以手动执行下面命令：
`docker exec ${container_name} pg_dump -F p -U ${username} -d ${db_name}   > pg_backup.sql`

**Comment by jeepc** [comment]
感谢
