### ISSUE TITLE
[Bug]Error occurred while setting up the Node.js runtime environment.

### ISSUE THREAD

**Issue by iygwei** [1Panel-dev/1Panel#7270]
### Contact Information

node环境

### 1Panel Version

v1.10.21-lts

### Problem Description

![image](https://github.com/user-attachments/assets/eca15060-44f2-47bd-a2e5-f609624e2beb)
我在容器执行npm run dev一直这个错 但是我在物理机是正常的node的版本都是一模一样的

### Steps to Reproduce

就是直接在容器没打包运行

**Comment by zhengkunwang223** [comment]
是通过 node 运行环境创建的吗？

**Comment by iygwei** [comment]
> 是通过 node 运行环境创建的吗？

是的 直接运行启动以后就用npm run dev

**Comment by iygwei** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > Is it created through the node runtime environment?
> 
> Yes, just run it directly and use npm run dev after startup.

![image](https://github.com/user-attachments/assets/d3e83344-b2cc-474b-8d5b-81de7b331aa7)
zh这样创建的

**Comment by zhengkunwang223** [comment]
> > > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> > 
> > 
> > > Is it created through the node runtime environment?
> > 
> > 
> > Yes, just run it directly and use npm run dev after startup.
> 
> ![image](https://private-user-images.githubusercontent.com/17736664/393111900-d3e83344-b2cc-474b-8d5b-81de7b331aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjM5OTgsIm5iZiI6MTczMzQ2MzY5OCwicGF0aCI6Ii8xNzczNjY2NC8zOTMxMTE5MDAtZDNlODMzNDQtYjJjYy00NzRiLThkNWItODFkZTdiMzMxYWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA1NDEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YjAyOThmYjQ4NTQzOGViZTRlYjRiNjAwZDhmMWUwODFjNjYyYzkyOWEyMjZlOWQ4ZGQ1NjE5MjQxNWM5MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hfnx9FjyvbbKny2aUgnLu0oOBQ1lJOgA76qfl29T1MU) zh这样创建的

看起来像是依赖的问题，尝试过编辑吗？编辑之后发一下全量的运行环境日志

**Comment by iygwei** [comment]
> > > > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> > > 
> > > 
> > > > Is it created through the node runtime environment?
> > > 
> > > 
> > > Yes, just run it directly and use npm run dev after startup.
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/17736664/393111900-d3e83344-b2cc-474b-8d5b-81de7b331aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjM5OTgsIm5iZiI6MTczMzQ2MzY5OCwicGF0aCI6Ii8xNzczNjY2NC8zOTMxMTE5MDAtZDNlODMzNDQtYjJjYy00NzRiLThkNWItODFkZTdiMzMxYWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA1NDEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YjAyOThmYjQ4NTQzOGViZTRlYjRiNjAwZDhmMWUwODFjNjYyYzkyOWEyMjZlOWQ4ZGQ1NjE5MjQxNWM5MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hfnx9FjyvbbKny2aUgnLu0oOBQ1lJOgA76qfl29T1MU) zh这样创建的
> 
> 看起来像是依赖的问题，尝试过编辑吗？编辑之后发一下全量的运行环境日志

依赖都安装了 他就是无法识别@/components/textStyle/timeframe_Edit
![image](https://github.com/user-attachments/assets/5f2a8327-e394-4cf8-a82a-3b974a11edb2)

**Comment by zhengkunwang223** [comment]
> > > > > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> > > > 
> > > > 
> > > > > Is it created through the node runtime environment?
> > > > 
> > > > 
> > > > Yes, just run it directly and use npm run dev after startup.
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/17736664/393111900-d3e83344-b2cc-474b-8d5b-81de7b331aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjM5OTgsIm5iZiI6MTczMzQ2MzY5OCwicGF0aCI6Ii8xNzczNjY2NC8zOTMxMTE5MDAtZDNlODMzNDQtYjJjYy00NzRiLThkNWItODFkZTdiMzMxYWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA1NDEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YjAyOThmYjQ4NTQzOGViZTRlYjRiNjAwZDhmMWUwODFjNjYyYzkyOWEyMjZlOWQ4ZGQ1NjE5MjQxNWM5MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hfnx9FjyvbbKny2aUgnLu0oOBQ1lJOgA76qfl29T1MU) zh这样创建的
> > 
> > 
> > 看起来像是依赖的问题，尝试过编辑吗？编辑之后发一下全量的运行环境日志
> 
> 依赖都安装了 他就是无法识别@/components/textStyle/timeframe_Edit ![image](https://private-user-images.githubusercontent.com/17736664/393114432-5f2a8327-e394-4cf8-a82a-3b974a11edb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjQ3MjAsIm5iZiI6MTczMzQ2NDQyMCwicGF0aCI6Ii8xNzczNjY2NC8zOTMxMTQ0MzItNWYyYTgzMjctZTM5NC00Y2Y4LWE4MmEtM2I5NzRhMTFlZGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA1NTM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNmIyYzE5ZjhlZDIwZDA0OTg1YzdlZjUyYTJjNzc1ZDNiMTQ1YzUyYjg1Y2RhMjdjYjMwYjM4M2NhZTAyMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7fWJeLQ57UwlCvHVX2VmXqpn_UnDEOCcKrnG-nB3lbk)

容器日志发一下

**Comment by iygwei** [comment]
> > > > > > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> > > > > 
> > > > > 
> > > > > > Is it created through the node runtime environment?
> > > > > 
> > > > > 
> > > > > Yes, just run it directly and use npm run dev after startup.
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/17736664/393111900-d3e83344-b2cc-474b-8d5b-81de7b331aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjM5OTgsIm5iZiI6MTczMzQ2MzY5OCwicGF0aCI6Ii8xNzczNjY2NC8zOTMxMTE5MDAtZDNlODMzNDQtYjJjYy00NzRiLThkNWItODFkZTdiMzMxYWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA1NDEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YjAyOThmYjQ4NTQzOGViZTRlYjRiNjAwZDhmMWUwODFjNjYyYzkyOWEyMjZlOWQ4ZGQ1NjE5MjQxNWM5MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hfnx9FjyvbbKny2aUgnLu0oOBQ1lJOgA76qfl29T1MU) zh这样创建的
> > > 
> > > 
> > > 看起来像是依赖的问题，尝试过编辑吗？编辑之后发一下全量的运行环境日志
> > 
> > 
> > 依赖都安装了 他就是无法识别@/components/textStyle/timeframe_Edit ![image](https://private-user-images.githubusercontent.com/17736664/393114432-5f2a8327-e394-4cf8-a82a-3b974a11edb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjQ3MjAsIm5iZiI6MTczMzQ2NDQyMCwicGF0aCI6Ii8xNzczNjY2NC8zOTMxMTQ0MzItNWYyYTgzMjctZTM5NC00Y2Y4LWE4MmEtM2I5NzRhMTFlZGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA1NTM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNmIyYzE5ZjhlZDIwZDA0OTg1YzdlZjUyYTJjNzc1ZDNiMTQ1YzUyYjg1Y2RhMjdjYjMwYjM4M2NhZTAyMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7fWJeLQ57UwlCvHVX2VmXqpn_UnDEOCcKrnG-nB3lbk)
> 
> 容器日志发一下

![image](https://github.com/user-attachments/assets/1d26c278-2705-4d47-856e-7b85912c7d24)
这个吗

**Comment by zhengkunwang223** [comment]
> > > > > > > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> > > > > > 
> > > > > > 
> > > > > > > Is it created through the node runtime environment?
> > > > > > 
> > > > > > 
> > > > > > Yes, just run it directly and use npm run dev after startup.
> > > > > 
> > > > > 
> > > > > ![image](https://private-user-images.githubusercontent.com/17736664/393111900-d3e83344-b2cc-474b-8d5b-81de7b331aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjM5OTgsIm5iZiI6MTczMzQ2MzY5OCwicGF0aCI6Ii8xNzczNjY2NC8zOTMxMTE5MDAtZDNlODMzNDQtYjJjYy00NzRiLThkNWItODFkZTdiMzMxYWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA1NDEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YjAyOThmYjQ4NTQzOGViZTRlYjRiNjAwZDhmMWUwODFjNjYyYzkyOWEyMjZlOWQ4ZGQ1NjE5MjQxNWM5MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hfnx9FjyvbbKny2aUgnLu0oOBQ1lJOgA76qfl29T1MU) zh这样创建的
> > > > 
> > > > 
> > > > 看起来像是依赖的问题，尝试过编辑吗？编辑之后发一下全量的运行环境日志
> > > 
> > > 
> > > 依赖都安装了 他就是无法识别@/components/textStyle/timeframe_Edit ![image](https://private-user-images.githubusercontent.com/17736664/393114432-5f2a8327-e394-4cf8-a82a-3b974a11edb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjQ3MjAsIm5iZiI6MTczMzQ2NDQyMCwicGF0aCI6Ii8xNzczNjY2NC8zOTMxMTQ0MzItNWYyYTgzMjctZTM5NC00Y2Y4LWE4MmEtM2I5NzRhMTFlZGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA1NTM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNmIyYzE5ZjhlZDIwZDA0OTg1YzdlZjUyYTJjNzc1ZDNiMTQ1YzUyYjg1Y2RhMjdjYjMwYjM4M2NhZTAyMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7fWJeLQ57UwlCvHVX2VmXqpn_UnDEOCcKrnG-nB3lbk)
> > 
> > 
> > 容器日志发一下
> 
> ![image](https://private-user-images.githubusercontent.com/17736664/393116006-1d26c278-2705-4d47-856e-7b85912c7d24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjUxNTMsIm5iZiI6MTczMzQ2NDg1MywicGF0aCI6Ii8xNzczNjY2NC8zOTMxMTYwMDYtMWQyNmMyNzgtMjcwNS00ZDQ3LTg1NmUtN2I4NTkxMmM3ZDI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA2MDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZTFhYjUxZGQxYWY5MDY5OWY5YzcwODY4Y2ViNGI1ZjgyMjQ1MDM5YzI0N2JjYzM1YTY0ZWU0OWVlYzdiNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._cDwvK3uHxKYWVvJjQ5uVazOdb8aTF_Z8JiFEoO8os8) 这个吗

没有启动日志  应用没启动 容器状态正常吗？

**Comment by iygwei** [comment]
[_home_1panel_runtime_node_qyly-web_docker-compose.yml-20241206141042.log](https://github.com/user-attachments/files/18033469/_home_1panel_runtime_node_qyly-web_docker-compose.yml-20241206141042.log)
kanakn看看是不是这个

**Comment by zhengkunwang223** [comment]
> _home_1panel_runtime_node_qyly-web_docker-compose.yml-20241206141042.log

看起来像是 @ 开头的模块找不到 是不是没配置好路径别名呢？ 类似这种
```
module.exports = {
  configureWebpack: {
    resolve: {
      alias: {
        '@': path.resolve(__dirname, 'src')
      }
    }
  }
};
```

**Comment by iygwei** [comment]
> configureWebpack: {

![image](https://github.com/user-attachments/assets/72323d6a-28ab-47e7-bad8-5cf0752dc1be)
我配置了的

**Comment by zhengkunwang223** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > configureWebpack: {
> 
> ![image](https://private-user-images.githubusercontent.com/17736664/393121137-72323d6a-28ab-47e7-bad8-5cf0752dc1be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjY4NDAsIm5iZiI6MTczMzQ2NjU0MCwicGF0aCI6Ii8xNzczNjY2NC8zOTMxMjExMzctNzIzMjNkNmEtMjhhYi00N2U3LWJhZDgtNWNmMDc1MmRjMWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA2MjkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwOTUyYTI5ZTY3ODFjYjRhZmVlNDQzMGFjNjQ3ODkxYzI0NTBiNDRlYjU2ZDBiNTU5N2U5YTQ3ZDNhODBhM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t-Bi33XfmAFN0Fpa8UzjwyrgNny5N1WU-JDl2myyKGQ) I configured it

我看你的挂载目录是 data 这个目录下的文件和文件夹可以看一下吗

**Comment by iygwei** [comment]
> > > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> > 
> > 
> > > configureWebpack: {
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/17736664/393121137-72323d6a-28ab-47e7-bad8-5cf0752dc1be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0NjY4NDAsIm5iZiI6MTczMzQ2NjU0MCwicGF0aCI6Ii8xNzczNjY2NC8zOTMxMjExMzctNzIzMjNkNmEtMjhhYi00N2U3LWJhZDgtNWNmMDc1MmRjMWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA2MjkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwOTUyYTI5ZTY3ODFjYjRhZmVlNDQzMGFjNjQ3ODkxYzI0NTBiNDRlYjU2ZDBiNTU5N2U5YTQ3ZDNhODBhM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t-Bi33XfmAFN0Fpa8UzjwyrgNny5N1WU-JDl2myyKGQ) I configured it
> 
> 我看你的挂载目录是 data 这个目录下的文件和文件夹可以看一下吗

![image](https://github.com/user-attachments/assets/b5866f6f-e03d-4c9d-88a3-112021c43f57)

**Comment by zhengkunwang223** [comment]
![image](https://github.com/user-attachments/assets/b28ffe19-fa46-4909-821a-231c7dac4104)
加我企业微信 我远程看一下

**Comment by iygwei** [comment]
> ![image](https://private-user-images.githubusercontent.com/31820853/393124607-b28ffe19-fa46-4909-821a-231c7dac4104.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0Njg5NzksIm5iZiI6MTczMzQ2ODY3OSwicGF0aCI6Ii8zMTgyMDg1My8zOTMxMjQ2MDctYjI4ZmZlMTktZmE0Ni00OTA5LTgyMWEtMjMxYzdkYWM0MTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDA3MDQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZDE5MzFjMmQyNDIxYjk5N2RmODNmNjQ2YWVmYzE5NDIzMTNiOTI2YjU3MGI1NjdiYjgwYjAyYjMzOWNlMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.unuRYmuW0jXy74NkOFl1Mkt1vs-3ivykXdwO6qU3eWk) 加我企业微信 我远程看一下
加你了
