### ISSUE TITLE
[Bug] English translation of the Container Manager's Images tab

### ISSUE THREAD

**Issue by ruibaby** [1Panel-dev/1Panel#7271]
### 1Panel Version

dev branch(873bba92db58844a714a6a3c8bdfa536de80c8a4)

### Problem Description

<img width="862" alt="image" src="https://github.com/user-attachments/assets/77f0d425-5943-4b72-86d8-7e0c6cbe7d8c">

Should this be 'Image' or 'Images'?

### Steps to Reproduce

None

**Comment by JohnNiang** [comment]
/assign

This is caused by <https://github.com/1Panel-dev/1Panel/pull/7247/files#diff-67a27bad9e3b64cc9c7d2246fe95c7eb2273a063e785de7d2d64b110736c28f5R709>. I will fix it later. 

For consistent, I prefer `Image`.

**Comment by wanghe-fit2cloud** [comment]
v1.10.22 版本已发布。
