### ISSUE TITLE
[Feature] Optimized interface operation | Quickly exit the editing pop-up box by pressing the key

### ISSUE THREAD

**Issue by vvvsrx** [1Panel-dev/1Panel#7273]
### 1Panel Version

 v1.10.21-lts

### Please describe your needs or suggestions for improvements

右侧编辑弹出框可以通过ESC按键快捷退出
![image](https://github.com/user-attachments/assets/c7305840-cf3f-42a0-8d66-bc08c9f5a4df)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复需求 #5408
