### ISSUE TITLE
[Bug] Docker compose editing window shortcut comment error

### ISSUE THREAD

**Issue by vvvsrx** [1Panel-dev/1Panel#7274]
### 1Panel Version

 v1.10.21-lts

### Problem Description

<img width="547" alt="image" src="https://github.com/user-attachments/assets/d7a27fa1-1338-4cf4-87d1-4ed9eb517d82">

编辑时,使用[command + / ]或者[alt + /]快捷注释,编辑器默认使用//

实际应该是#

使用起来非常不方便

### Steps to Reproduce

同上

**Comment by wanghe-fit2cloud** [comment]
Thanks for your feedback. We will resolve this issue in a future version.

**Comment by wanghe-fit2cloud** [comment]
The v1.10.22 version has been released.
