### ISSUE TITLE
[Bug] Inconsistency between Swagger license annotation and repo license

### ISSUE THREAD

**Issue by ruibaby** [1Panel-dev/1Panel#7275]
### 1Panel Version

dev branch(d2da7e2ea5dd9a6440dd082f819cccf4109daf97)

### Problem Description

The license specified in Swagger documentation shows Apache 2.0, which differs from the repository's actual license.

<img width="481" alt="image" src="https://github.com/user-attachments/assets/b9761ced-b570-4677-9c3b-f80c9d167e1a">

### Steps to Reproduce

None

**Comment by wanghe-fit2cloud** [comment]
Thanks for your feedback. We will resolve this issue in an upcoming version.

**Comment by wanghe-fit2cloud** [comment]
The v1.10.22 version has been released.
