### ISSUE TITLE
[QUESTION]安装结束直接提示：1Panel 服务启动出错! 

### ISSUE THREAD

**Issue by justincnn** [1Panel-dev/1Panel#728]
### 请描述您的问题

[root@new-start ~]# 1pctl status
● 1panel.service - 1Panel, a modern open source linux panel
   Loaded: loaded (/etc/systemd/system/1panel.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: signal) since Thu 2023-04-20 11:50:42 CST; 2s ago
  Process: 1020485 ExecStart=/usr/bin/1panel (code=killed, signal=SEGV)
 Main PID: 1020485 (code=killed, signal=SEGV)

**Comment by wanghe-fit2cloud** [comment]
**1Panel 版本：**
```shell
1pctl version
```
**服务器操作系统：**
```shell
cat /etc/os-release
```
**查看错误日志：**
```shell
journalctl -u 1panel -exf
```
