### ISSUE TITLE
[Bug] Improve password action buttons styling in database connection info

### ISSUE THREAD

**Issue by ruibaby** [1Panel-dev/1Panel#7284]
### 1Panel Version

dev branch(b73dcc9388805c1e1f61ad757da226e9060ab59a)

### Problem Description

Found two styling issues with password field buttons:

1. Both Copy and Random buttons highlight simultaneously on hover
2. Missing separator between adjacent buttons

<img width="426" alt="image" src="https://github.com/user-attachments/assets/c1987484-23be-4302-ae44-ad41d52a95a1">
<img width="417" alt="image" src="https://github.com/user-attachments/assets/25359d73-6eb2-4233-8c2b-5e5412bd628c">

### Steps to Reproduce

Database -> Connection info

**Comment by wanghe-fit2cloud** [comment]
Thanks for your feedback. We will optimize this in an upcoming version.

**Comment by wanghe-fit2cloud** [comment]
The v1.10.22 version has been released.
