### ISSUE TITLE
[Bug] Docker Network for IPV6 setup

### ISSUE THREAD

**Issue by yfdoor** [1Panel-dev/1Panel#7285]
### 1Panel Version

1.10.21

### Problem Description

I want to use IPV6 for docker, and setup it following the https://1panel.cn/docs/user_manual/containers/setting/,
but it seems some thing wrong when I create a network with IPV6

![image](https://github.com/user-attachments/assets/3145a03d-662f-46b0-9f1f-6f51caab8adb)

### Steps to Reproduce

same issue with double confirm

**Comment by wanghe-fit2cloud** [comment]
Docker SDK 返回的错误信息提示：创建 IPv6 容器网络时，指定的地址范围与现有网络存在冲突。
你可以使用以下命令手动创建网络，确认地址范围是否可用：
```shell
docker network create \
  --ipv6 \
  --subnet=fd00:dead:beef::/48 \
  my_ipv6_network
```

**Comment by yfdoor** [comment]
> Docker SDK 返回的错误信息提示：创建 IPv6 容器网络时，指定的地址范围与现有网络存在冲突。 你可以使用以下命令手动创建网络，确认地址范围是否可用：
> 
> ```shell
> docker network create \
>   --ipv6 \
>   --subnet=fd00:dead:beef::/48 \
>   my_ipv6_network
> ```

折腾了半天还是不行，只能把docker ipv6 关了，直接容器换成 host 了，可不可以在文档中把这部分写的详细些啊，我看论坛中也有人在讨论这部分，感觉文档的介绍还是有一些不太清楚的地方，感谢

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> The error message returned by Docker SDK prompts: When creating an IPv6 container network, the specified address range conflicts with the existing network. You can manually create a network and confirm whether the address range is available using the following command:
>
> ```shell
> docker network create \
> --ipv6 \
> --subnet=fd00:dead:beef::/48 \
> my_ipv6_network
> ```

After struggling for a long time, it still doesn't work. I can only turn off docker ipv6 and directly replace the container with the host. Can you write this part in more detail in the document? I see that some people are discussing this part in the forum. I feel that the introduction of the document is There are still some things that are not clear about, thank you

**Comment by 2tof** [comment]
我照着说明，设置好饿了/80段，主机的网络直接崩溃了。无非上网了。那个文档写的非常粗糙，看起来是要设置公网的v6，但两种我都试了。

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
I followed the instructions and set up the hungry/80 segment, and the host's network crashed directly. It's nothing more than surfing the Internet. The document is very rough and seems to be setting up v6 for the public network, but I tried both.
