### ISSUE TITLE
[Bug] Google Chrome cannot log in to the panel

### ISSUE THREAD

**Issue by laoma2053** [1Panel-dev/1Panel#7286]
### 1Panel Version

v1.10.21

### Problem Description

Google浏览器登录面板，输入账号密码后，提示登录成功，返回的页面依然是登录界面。

火狐浏览器可以正常登录

Google浏览器，清除 了缓存；卸载重新安装浏览器，都试过了。 依然不行
Chrome 已是最新版本
版本 131.0.6778.109（正式版本） （64 位）
![image](https://github.com/user-attachments/assets/0be215c7-87f2-4f07-b509-e402962e1894)

补充：在无痕模式下，可以登录面板后台

### Steps to Reproduce

希望登录成功

**Comment by wanghe-fit2cloud** [comment]
你可以参考 [issue #4785](https://github.com/1Panel-dev/1Panel/issues/4785)，看看是否能解决你的问题。

**Comment by laoma2053** [comment]
那边说了半天，也不知道怎么解决啊~

最后的办法是重置浏览器设置

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
After talking for a long time, I don’t know how to solve it~

The last resort is to reset your browser settings
