### ISSUE TITLE
[Feature] Modify macos

### ISSUE THREAD

**Issue by codylib** [1Panel-dev/1Panel#7287]
### 1Panel Version

v1.10.21-lts

### Please describe your needs or suggestions for improvements

I want to use mac mini m4 as my server, but there is currently no adapted version of 1plane. Are there any related plans?

**Comment by zhengkunwang223** [comment]
Managing Docker containers on macOS is a hassle and requires a lot of work. We currently have no plans to adapt for macOS.

**Comment by gentrydeng** [comment]
Hi,

Since you have no plans to support macOS, it stands to reason that you have no plans to support FreeBSD either.
So I won’t create a new issue and waste everyone’s time; I’ll just mention it here.

CC: #1493
