### ISSUE TITLE
[Feature] The professional version has set the panel domain name, but the panel cannot be opened.

### ISSUE THREAD

**Issue by laoma2053** [1Panel-dev/1Panel#7289]
### 1Panel Version

v1.10.21

### Please describe your needs or suggestions for improvements

专业版，在面板设置里，设置了域名访问，点击绑定后，不能打开面板

域名解析在CF，使用代理，不开启代理都试过，依然打不开。

现在面板进不去，也不知道怎么设置回来？
![image](https://github.com/user-attachments/assets/bf81526c-4744-4884-a90f-37007b4d740e)

**Comment by zhengkunwang223** [comment]
这是被waf拦截了，可以先把waf关了

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
This is intercepted by waf. You can turn off waf first.

**Comment by laoma2053** [comment]
> 这是被waf拦截了，可以先把waf关了

进不去面板，怎么关waf。
关了waf进入面板后，怎么设置，才能在waf开启的状态下，使用域名访问面板？

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> This is intercepted by waf. You can turn off waf first.

How to turn off waf if I can't enter the panel.
After turning off waf and entering the panel, how can I set it up so that I can use the domain name to access the panel when waf is on?

**Comment by zhengkunwang223** [comment]
![image](https://github.com/user-attachments/assets/d3c43573-d591-44b8-a4c4-046b5c90f41d)
可以先去掉域名绑定

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
![image](https://github.com/user-attachments/assets/d3c43573-d591-44b8-a4c4-046b5c90f41d)
You can remove the domain name binding first
