### ISSUE TITLE
[FEATURE]防火墙范围端口使用情况及应用

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#729]
### 1Panel 版本

1.1.2

### 请描述您的需求或者改进建议

防火墙可以增加范围端口设置，但是当使用了范围端口里一部分端口后这个范围端口还是显示未使用，能否显示[部分使用中]
并这个[部分使用中]点击或者悬停可以显示已使用的端口及应用名称：如2001[已使用(mysql)],2002[已使用(phpmyadmin)]
![image](https://user-images.githubusercontent.com/19621032/233276381-a8293e61-e611-4e4e-b4ec-12de4447b0f4.png)

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
