### ISSUE TITLE
[Feature] Delete login log

### ISSUE THREAD

**Issue by gitlsl** [1Panel-dev/1Panel#7291]
### 1Panel Version

v1.10.21-lts

### Please describe your needs or suggestions for improvements

ssh端口被人暴力破解, 登录记录好几千页,  但找不到清空记录的地方, 

### Please describe the solution you suggest

希望增加这个功能[其他日志考虑是否也增加清空功能]

**Comment by wanghe-fit2cloud** [comment]
SSH 登录日志是读取到服务器的日志文件，具体文件路径如下：
```
Ubuntu: /var/log/auth.log.*
CentOS: /var/log/secure*
```

目前版本，如需删除、清空 SSH 登录日志，可以自行删除。
> 我们将在后续版本中评估是否支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
The SSH login logs are retrieved from the server’s log files, located at the following paths:

Ubuntu: /var/log/auth.log.*  
CentOS: /var/log/secure*  

In the current version, you can manually delete or clear SSH login logs if needed.

	We will evaluate whether to support this requirement in future versions.
