### ISSUE TITLE
[Bug] Unable to delete the DNS account under the certificate option

### ISSUE THREAD

**Issue by lyujp** [1Panel-dev/1Panel#7300]
### Contact Information

lyujunpeng@outlook.com

### 1Panel Version

 v1.10.21-lts

### Problem Description

I previously used the DNS method to obtain an SSL certificate, but now I want to switch to the HTTP method.

However, even after switching, the DNS account is still being used, and I can't delete it. 

I no longer want to use the DNS method, but I am unable to remove the DNS account.

![image](https://github.com/user-attachments/assets/faf7211d-ac2c-404a-9dcf-a8dc13510e71)

![image](https://github.com/user-attachments/assets/12ddff49-6012-474d-83f5-8186548aba3e)

![image](https://github.com/user-attachments/assets/513c10e2-ff00-4465-bf9f-66bfb715aed6)

### Steps to Reproduce

The same as problem description.

### The expected correct result

When I switch to the HTTP method ,the DNS account can be removed.

**Comment by zhengkunwang223** [comment]
The issue has been reproduced and will be fixed in future versions.

**Comment by wanghe-fit2cloud** [comment]
The v1.10.22 version has been released.
