### ISSUE TITLE
[FEATURE]支持第三方登录、登录安全提醒、手机端

### ISSUE THREAD

**Issue by dakaitong** [1Panel-dev/1Panel#731]
### 1Panel 版本

v1.1.2

### 请描述您的需求或者改进建议

- 可以增加面板的第三方登录、例如：微信、QQ、钉钉等
- 可以集成企业微信、钉钉、短信的登录安全提醒功能。类如备份策略异常或者服务器运行异常
- 如果可以的话 希望应用市场再丰富一些，集成常见的服务器监控组件。类如：普罗米修斯、zazbbix
- 后期可以推出一个小程序管理端或者手机端（可以适当收费、分摊成本）
- 总的来说、还是很好用~加油！已经star

### 请描述你建议的实现方案

- 可以增加面板的第三方登录、例如：微信、QQ、钉钉等
- 可以集成企业微信、钉钉、短信的登录安全提醒功能。类如备份策略异常或者服务器运行异常
- 如果可以的话 希望应用市场再丰富一些，集成常见的服务器监控组件。类如：普罗米修斯、zazbbix
- 后期可以推出一个小程序管理端或者手机端（可以适当收费、分摊成本）
- 总的来说、还是很好用~加油！已经star

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中讨论上述需求的可行性方案。
应用商店的需求，可以统一汇总到这里#250

**Comment by TcDhlPro** [comment]
三方登录功能没必要增加

**Comment by wanghe-fit2cloud** [comment]
通知、告警相关需求的讨论，统一汇总到该 issue #614
