### ISSUE TITLE
[Feature] I hope to add the function of restricting external port access for self-built containers

### ISSUE THREAD

**Issue by mylo114514** [1Panel-dev/1Panel#7312]
### 1Panel Version

社区版： v1.10.21-lts

### Please describe your needs or suggestions for improvements

目前似乎只有从应用商店下载的镜像才能关闭外部端口访问
自建的容器似乎没有这个选项，我尝试使用防火墙功能关闭该端口，提示“Linux 防火墙 ufw 无法禁用 Docker 端口映射”。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈！目前，无论是 ufw 还是 firewalld，Linux 主机的防火墙都不支持禁用 Docker 容器端口。
对于应用商店安装的应用，是因为端口绑定到 127.0.0.1，因此无法从外部访问。如果是自建容器，也可以参考此方法，将端口绑定到 127.0.0.1 来实现相同的效果。
