### ISSUE TITLE
[Bug] Mysql installation failed in the app store

### ISSUE THREAD

**Issue by test19850** [1Panel-dev/1Panel#7319]
### 1Panel Version

v1.10.21-lts

### Problem Description

应用商店中Mysql安装失败，多次尝试均失败，已设置镜像加速。

### Steps to Reproduce

应用商店中Mysql安装失败，多次尝试均失败，已设置镜像加速。

**Comment by test19850** [comment]
stderr: Get "https://registry-1.docker.io/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) ; stdout: 8.0.40: Pulling from library/mysql 8.0.40: Pulling from library/mysql 8.0.40: Pulling from library/mysql 8.0.40: Pulling from library/mysql 8.0.40: Pulling from library/mysql

**Comment by wanghe-fit2cloud** [comment]
从报错信息来看，问题仍然是镜像拉取超时。建议参考论坛中的相关帖子，配置一个有效的镜像加速地址：
https://bbs.fit2cloud.com/t/topic/5886/
