### ISSUE TITLE
[FEATURE]几点建议

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#732]
### 1Panel 版本

v1.1.2

### 请描述您的需求或者改进建议

1、能否支持本地原本已经安装的 nginx 或者 openresty，就有就不需要再进行一次网站迁移工作
2、面板只能支持直接配置通过子域名 https 访问
3、能够提供直接免费的 https 证书方案，支持一键续签
4、对于数据库方面能否支持原本已经通过 yum/apt 或者 docker 安装的数据，不用重新启动一个 1Panel-mysql-xxx 容器

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。针对您提出的上述 4 点建议，我们会在后续版本中考虑支持的。

**Comment by vlssu** [comment]
> 感谢反馈。针对您提出的上述 4 点建议，我们会在后续版本中考虑支持的。

可以增加迁移比如宝塔面板的工具，否则迁移成本比较大

**Comment by iucvcom** [comment]
这几点建议搞起来感觉有点费劲，感觉还是需要新机来安装1panel好一些。

**Comment by mx2913** [comment]
> 这几点建议搞起来感觉有点费劲，感觉还是需要新机来安装1panel好一些。

如果一开始自然是新机最好，但是这个产品出来的比较晚，很多人已经有了原有的运行环境，很多上面已经有好几个网站环境之类的，不过不能直接支持已有的这种，那就网站环境迁移也是个问题的

**Comment by wanghe-fit2cloud** [comment]
1、能否支持本地原本已经安装的 nginx 或者 openresty，就有就不需要再进行一次网站迁移工作
> 我们在中短期内应该不会考虑支持。

2、面板只能支持直接配置通过子域名 https 访问
> 最新版本已经支持在面板设置菜单中设置

3、能够提供直接免费的 https 证书方案，支持一键续签
> `网站` - `证书` 列表，已经支持证书一键自动续签

4、对于数据库方面能否支持原本已经通过 yum/apt 或者 docker 安装的数据，不用重新启动一个 1Panel-mysql-xxx 容器
> 最新版本已经支持添加远程 MySQL 数据库
