### ISSUE TITLE
[Bug] After the App Store installs OpenResty and the container is deleted, the App Store still displays OpenResty as installed and cannot be reinstalled in the App Store.

### ISSUE THREAD

**Issue by Kirito520Asuna** [1Panel-dev/1Panel#7320]
### Contact Information

doutianmianxia@qq.com

### 1Panel Version

1.10.21

### Problem Description

应用商店安装OpenResty  容器删除后 应用商店OpenResty 依旧显示已安装并且无法在应用商店重新安装 

### Steps to Reproduce

应用商店安装OpenResty  在docker 容器处删除容器

**Comment by zhengkunwang223** [comment]
需要从应用商店-已安装处卸载

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Need to uninstall from App Store - Installed

**Comment by Kirito520Asuna** [comment]
> 需要从应用商店-已安装处卸载
容器已经删除 从应用商店-卸载 报错哦老哥

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Need to uninstall from App Store - Installed
The container has been deleted. Uninstall it from the app store. Report an error, bro.

**Comment by Kirito520Asuna** [comment]
安装目录不存在

> > Bot 检测到 issue body 的语言不是英文，自动翻译。👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > 需要从 App Store 卸载 - 已安装 容器已被删除。从 App Store 卸载它。报告错误，兄弟。
安装目录不存在

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
The installation directory does not exist

> > Bot detects that the language of the issue body is not English and automatically translates it. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
>
> > Need to uninstall from App Store - installed container has been removed. Uninstall it from the App Store. Report a bug, bro.
The installation directory does not exist

**Comment by zhengkunwang223** [comment]
> 安装目录不存在
> 
> 
> 
> > > Bot 检测到 issue body 的语言不是英文，自动翻译。👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > 
> 
> > > 需要从 App Store 卸载 - 已安装 容器已被删除。从 App Store 卸载它。报告错误，兄弟。
> 
> 安装目录不存在
> 
> 

强制删除

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> The installation directory does not exist
>
>
>
> > > Bot detects that the language of the issue body is not English and automatically translates it. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
>
>>
>
> > > Need to uninstall from App Store - installed container has been removed. Uninstall it from the App Store. Report a bug, bro.
>
> The installation directory does not exist
>
>

force delete

**Comment by Kirito520Asuna** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > The installation directory does not exist
> > > > Bot detects that the language of the issue body is not English and automatically translates it. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> > 
> > 
> > > 
> > 
> > 
> > > > Need to uninstall from App Store - installed container has been removed. Uninstall it from the App Store. Report a bug, bro.
> > 
> > 
> > The installation directory does not exist
> 
> force delete
有效
