### ISSUE TITLE
[Bug] When installing halo, the string concatenation in compose is incorrect.

### ISSUE THREAD

**Issue by duminghan23** [1Panel-dev/1Panel#7323]
### Contact Information

1844907684@qq.com

### 1Panel Version

v1.10.21-lts

### Problem Description

在compose中的 --spring.r2dbc.url 拼接不正确，没有拼接panel_db_ip、panel_db_port、panel_db_name 这三个变量

### Steps to Reproduce

直接在应用商店安装halo，选择MySQL，使用默认生成的数据库、账号、密码，等待halo启动完成，查看日志，显示连接mysql失败。
经过检查，在compose中的  --spring.r2dbc.url 拼接不正确，没有拼接panel_db_ip、panel_db_port、panel_db_name 这三个变量。
解决方法：手动编写compose文件，把使用$符号拼接的参数手动拼接上，如下，点击确定后就可以正常安装了。
--spring.r2dbc.url=r2dbc:pool:mysql://192.168.2.201:3306/halo_k2csjn

### The expected correct result

正确拼接参数

**Comment by wanghe-fit2cloud** [comment]
Compose 的变量定义在 .env 文件中，你可以进入应用的安装目录，修改相应的变量值后再试一下。
