### ISSUE TITLE
[Bug] abnormal log request

### ISSUE THREAD

**Issue by igophper** [1Panel-dev/1Panel#7339]
### 1Panel Version

v1.10.21-lts

### Problem Description

![image](https://github.com/user-attachments/assets/7d954d91-7c79-4c33-b15c-94de15417f46)

点击查看日志，选中`追踪`，关闭日志界面后，网络还在不停请求日志

### Steps to Reproduce

网站 => 运行环境 => 创建运行环境 => 创建后弹出日志窗口，选中`追踪`，关闭日志窗口 网络还在请求日志

### The expected correct result

 关闭日志界面，网络不再请求日志

**Comment by zhengkunwang223** [comment]
感谢提出问题并解决 手动点赞 👍🏻

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Thanks for raising the issue and solving it. Like it manually 👍🏻

**Comment by wanghe-fit2cloud** [comment]
The v1.10.22 version has been released.
