### ISSUE TITLE
[BUG]系统不存在 sudo 命令时，无法使用 ufw 防火墙

### ISSUE THREAD

**Issue by MignonZhang** [1Panel-dev/1Panel#734]
### 1Panel 版本

v1.1.1

### 问题描述

系统不存在 sudo 命令时，无法使用 ufw 防火墙

### 重现步骤

进入防火墙页面，提示错误：
服务内部错误: load the firewall status failed, err: stderr: bash: line 1: sudo: command not found

**Comment by realzolo** [comment]
> ### 联系方式
> _No response_
> 
> ### 1Panel 版本
> v1.1.1
> 
> ### 问题描述
> 系统不存在 sudo 命令时，无法使用 ufw 防火墙
> 
> ### 重现步骤
> 进入防火墙页面，提示错误： 服务内部错误: load the firewall status failed, err: stderr: bash: line 1: sudo: command not found
> 
> ### 期待的正确结果
> _No response_
> 
> ### 相关日志输出
> _No response_
> 
> ### 附加信息
> _No response_

没有sudo你就安装呀

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在 v1.1.3 版本中增加服务器是否已安装 sudo 命令的判断。

**Comment by wanghe-fit2cloud** [comment]
v1.1.3 版本已发布。
