### ISSUE TITLE
[Bug] When importing database, if the data package is large, the panel will be exited during the import process, and you need to log in again.

### ISSUE THREAD

**Issue by Alexzzz2008** [1Panel-dev/1Panel#7347]
### 1Panel Version

1.10.21

### Problem Description

1 导入数据库，数据包大的情况下 会在导入过程中 退出面板，要重新登录
2，解压，超过15G （具体数据不明，反正压缩包比较大的情况下） 也会在解压过程中，退出面板，需要重新登录

### Steps to Reproduce

1

**Comment by wanghe-fit2cloud** [comment]
感谢反馈！我们将在后续版本中增加支持选择服务器数据库备份文件的功能。
> 对于上传、解压大文件超时的问题，也会在后续版本中尝试优化。

**Comment by wanghe-fit2cloud** [comment]
相关问题的讨论，统一汇总到该 issue #7030
