### ISSUE TITLE
[BUG]ubuntu 桌面版无法使用 ufw

### ISSUE THREAD

**Issue by MignonZhang** [1Panel-dev/1Panel#735]
### 1Panel 版本

v1.1.1

### 问题描述

ubuntu 桌面版无法使用 ufw ， 中文插件的问题

### 重现步骤

ubuntu 桌面版无法使用 ufw ， 中文插件的问题

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，这个问题会在1.1.3版本修复。

**Comment by wanghe-fit2cloud** [comment]
v1.1.3 版本已发布。
