### ISSUE TITLE
[Bug] mysql8.4 prompts error when modifying database account permissions

### ISSUE THREAD

**Issue by mjsoftking** [1Panel-dev/1Panel#7364]
### 1Panel Version

1.10.21

### Problem Description

![image](https://github.com/user-attachments/assets/4ad48150-6f9f-4db9-815d-2a89149f2d80)
 mysql8.4 修改数据库账号权限提示错误

### Steps to Reproduce

mysql8.4 直接修改数据库账号权限，不调整，还是选择 所有人，点击确定

**Comment by wanghe-fit2cloud** [comment]
如果需要调整 MySQL 用户权限，可以尝试指定具体的 IP。报错信息是由于数据库中已存在针对所有用户（%）的权限设置。
