### ISSUE TITLE
[Bug] Log audit=》Incomplete login log

### ISSUE THREAD

**Issue by nick938** [1Panel-dev/1Panel#7367]
### 1Panel Version

 社区版 v1.10.22-beta.2

### Problem Description

登录日志只显示九月份以前的，到现在十二月份中间三个月的日志都没了
![image](https://github.com/user-attachments/assets/f343e417-fce8-4498-b6c3-814c9b4d31e0)

### Steps to Reproduce

点击日志审计=》登录日志不全

**Comment by ssongliu** [comment]
感谢反馈，可以执行下面命令看一下返回信息
`cat /var/log/secure | grep -a Accepted`
`cat /var/log/auth.log| grep -a Accepted`

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Thanks for the feedback. You can execute the following command to see the return information.
`cat /var/log/secure | grep -a Accepted`
`cat /var/log/auth.log| grep -a Accepted`

**Comment by nick938** [comment]
> 感谢反馈，可以执行下面命令看一下返回信息 `cat /var/log/secure | grep -a Accepted` `cat /var/log/auth.log| grep -a Accepted`

![image](https://github.com/user-attachments/assets/179c34f3-fec7-4f7b-b892-66ab4a1e5661)

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Thanks for the feedback, you can execute the following command to see the return information `cat /var/log/secure | grep -a Accepted` `cat /var/log/auth.log| grep -a Accepted`

![image](https://github.com/user-attachments/assets/179c34f3-fec7-4f7b-b892-66ab4a1e5661)

**Comment by ssongliu** [comment]
日志里面没有发现有这段时间的日志，麻烦再提供一下下面命令返回
`cat auth.log* | grep -aE "(Failed password for|Connection closed by authenticating user|Accepted)"`

**Comment by ssongliu** [comment]
由于太久没有回复，暂时先关闭该 issue，如果还有问题可以重新打开

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Since there has been no reply for a long time, I will close this issue for now. If there are still questions, you can reopen it.
