### ISSUE TITLE
[BUG]下载网站备份超时

### ISSUE THREAD

**Issue by whfay** [1Panel-dev/1Panel#737]
### 1Panel 版本

v1.1.2

### 问题描述

下载网站备份超时
![图片](https://user-images.githubusercontent.com/29944886/233396420-89a9f4fc-bc21-4bfb-a299-f44c7f377c77.png)
![图片](https://user-images.githubusercontent.com/29944886/233396497-18da351c-98fe-4f32-b758-f6ff9f31d34e.png)

### 重现步骤

下载网站备份文件

**Comment by wanghe-fit2cloud** [comment]
v1.1.3 版本已发布。
