### ISSUE TITLE
[Bug] There are front-end display issues when the 1Panel App Store is not loaded

### ISSUE THREAD

**Issue by Anyexyz** [1Panel-dev/1Panel#7370]
### Contact Information

Anye

### 1Panel Version

Pro v1.10.21-lts

### Problem Description

There are front-end display issues when the 1Panel App Store is not loaded.
Like this
<img width="539" alt="3800f4e988f7d1c81f90f7a224ffb735" src="https://github.com/user-attachments/assets/9b4baad2-dbf1-494d-ada7-e8f56578e713" />

### Steps to Reproduce

After installing 1Panel, disconnect from the Internet and the front-end bug can be triggered stably.

**Comment by wanghe-fit2cloud** [comment]
Thanks for your feedback! We’ll optimize this in an upcoming version.

**Comment by wanghe-fit2cloud** [comment]
v1.10.22 版本已发布。
