### ISSUE TITLE
[Feature] add app  dolphinscheduler    13.1k star

### ISSUE THREAD

**Issue by ByZhouhang** [1Panel-dev/1Panel#7373]
### 1Panel Version

xx

### Please describe your needs or suggestions for improvements

 https://github.com/apache/dolphinscheduler?tab=readme-ov-file
 
 Apache DolphinScheduler is the modern data orchestration platform. Agile to create high performance workflow with low-code. It is also provided powerful user interface, dedicated to solving complex task dependencies in the data pipeline and providing various types of jobs available out of the box

**Comment by wanghe-fit2cloud** [comment]
The official [docker-compose.yml](https://github.com/apache/dolphinscheduler/blob/dev/deploy/docker/docker-compose.yml) deployment method includes too many containers, making it less suitable for use in the 1Panel App Store and challenging for future application maintenance.

**Comment by wanghe-fit2cloud** [comment]
The official all-in-one deployment option is available but not recommended for production environments.

## Using standalone-server Docker Image

Start DolphinScheduler with standalone-server Docker images is the easiest way to experience and explode it. In this way, you can learn DolphinScheduler's concepts and usage, with minimal cost.

```shell
$ DOLPHINSCHEDULER_VERSION=3.1.5
$ docker run --name dolphinscheduler-standalone-server -p 12345:12345 -p 25333:25333 -d apache/dolphinscheduler-standalone-server:"${DOLPHINSCHEDULER_VERSION}"
```

> Note: Do not use apache/dolphinscheduler-standalone-server Docker image in production, it should only for you to taste DolphinScheduler at the first time. Not only because it runs all services in one single process, but also it uses H2 as its database which will lose metadata after it stops (could be changed to another database to avoid it). In addition,apache/dolphinscheduler-standalone-server only contains DolphinScheduler core services, some tasks such as Spark and Flink, require external components or environment to run it.
