### ISSUE TITLE
[Feature] Environmental requirements

### ISSUE THREAD

**Issue by LiJoeAllen** [1Panel-dev/1Panel#7379]
### 1Panel Version

1.10

### Please describe your needs or suggestions for improvements

需要rast运行环境，希望有更新

**Comment by wanghe-fit2cloud** [comment]
请问 issue 中提到的 rast 运行环境是否是指的 Rust 语言？

**Comment by LiJoeAllen** [comment]
嗯嗯，就是rast语言的运行环境
![image](https://github.com/user-attachments/assets/89d88edb-41cc-45d4-910b-73f9c9b35594)
加个rast

**Comment by wanghe-fit2cloud** [comment]
中短期内暂无计划支持该运行环境，望理解。

**Comment by wanghe-fit2cloud** [comment]
可以考虑自己维护 Docker 镜像，然后利用 1Panel 的容器或容器编排功能，实现应用的发布和维护。
