### ISSUE TITLE
[Feature] SSL push function suggestion

### ISSUE THREAD

**Issue by tangyuanhaoyuan** [1Panel-dev/1Panel#7383]
### 1Panel Version

 v1.10.21-lts

### Please describe your needs or suggestions for improvements

证书申请自动推送目录，建议增加匹配网站域名，还有cdn，我申请*.xxx.com通配域名证书可以推送所有网站了。

**Comment by zhengkunwang223** [comment]
你可以通过执行脚本来实现这个功能

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
You can achieve this function by executing the script
