### ISSUE TITLE
[Feature] Add user manage and disk quota functionality

### ISSUE THREAD

**Issue by Fsiyuetian** [1Panel-dev/1Panel#7408]
### 1Panel Version

 v1.10.21

### Please describe your needs or suggestions for improvements

want to have host user management and can specify the user home directory and home directory disk restrictions, which are suitable for multiple people using a single host scene

### Please describe the solution you suggest

You can use the "quota" tool

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
多用户权限体系需求的讨论，统一汇总到该 issue #638
磁盘相关需求的讨论，统一汇总到该 issue #1852
