### ISSUE TITLE
[FEATURE] 增加网站日志的审计

### ISSUE THREAD

**Issue by zhengkunwang223** [1Panel-dev/1Panel#743]
### 1Panel 版本

v1.1.1

### 请描述您的需求或者改进建议

统一网站日志页面，在一个页面中展示所有的网站日志
网站日志包括
1.网站操作日志 - 1Panel 操作网站的日志
2.网站运行日志 - openresty access.log
3.网站错误日志- openresty error.log
4.网站攻击日志 - WAF 拦截日志

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
