### ISSUE TITLE
[Bug] Duplicate tasks

### ISSUE THREAD

**Issue by ang0318** [1Panel-dev/1Panel#7438]
### 1Panel Version

v1.10.22-lts

### Problem Description

设置了任务执行时间实际上会在一个时间点重复两次相同的任务

### Steps to Reproduce

设置计划任务设置执行周期为每n时 设置好多个时间点后就出现每一个时间点重复两次任务了

### The expected correct result

应该每一个时间点执行一次即可

**Comment by ang0318** [comment]
![Screenshot_2024-12-19-18-48-11-050_com android chrome](https://github.com/user-attachments/assets/9f9cf8cf-fdd9-47aa-b061-4958c57010ce)
![Screenshot_2024-12-19-18-48-17-274_com android chrome](https://github.com/user-attachments/assets/72e61258-8c7c-4db8-be7b-1207541208fe)

**Comment by ssongliu** [comment]
感谢反馈，当前计划任务执行周期设置是有重合时间点的：
<img width="887" alt="image" src="https://github.com/user-attachments/assets/dc98bdde-1183-4338-a55c-01b5974fc81f" />
<img width="942" alt="image" src="https://github.com/user-attachments/assets/68f68874-83b2-4e9a-ad8e-d75aea5d125d" />
<img width="854" alt="image" src="https://github.com/user-attachments/assets/2ffc796c-3a1c-439f-ab70-be28807f7703" />

上面这种需求建议使用每天几点执行。
