### ISSUE TITLE
[Feature] ensure page positioning after refresh using route parameters

### ISSUE THREAD

**Issue by LIlGG** [1Panel-dev/1Panel#7446]
### 1Panel Version

v1.10.22-r2-alpha.19

### Please describe your needs or suggestions for improvements

希望前端页面中，子路由能够使用路由参数的形式跟在主路由后，或者采用其他的方式，例如：

`https://demo.1panel.hk/apps/all/website`
或
`https://demo.1panel.hk/apps/all?category=website`

这样做的优点是，可以在刷新页面后，定位至上一次所打开的页面。或者携带更多的数据来对此页面进行初始化，保持状态。

<img width="769" alt="image" src="https://github.com/user-attachments/assets/a6f96eca-16f6-435f-b3c3-5af62066ff5a" />

**Comment by zhengkunwang223** [comment]
感谢你的建议，我们一般是通过浏览器本地缓存来记住上次的选项，配置等信息

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Thank you for your suggestion. We usually remember the last options, configuration and other information through the browser's local cache.

**Comment by LIlGG** [comment]
> 感谢你的建议，我们一般是通过浏览器本地缓存来记住上次的选项，配置等信息

感谢积极的回复。但目前似乎刷新页面之后，页面会被重置为初始状态。即刷新前分类 -> Website。刷新后 -> all。

这类信息不需要保存在 localstore 中，所以使用路由进行判断应该是比较好的方案。算是一个比较小的优化点。

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
> Thanks for your suggestion. We usually remember the last options, configuration and other information through the browser's local cache.

Thanks for the positive reply. But currently it seems that after refreshing the page, the page will be reset to its initial state. That is, category -> Website before refreshing. After refresh -> all.

This kind of information does not need to be stored in localstore, so using routing to make judgments should be a better solution. This is a relatively small optimization point.
