### ISSUE TITLE
[QUESTION] 海外服务器执行不了一键安装脚本

### ISSUE THREAD

**Issue by Star-tears** [1Panel-dev/1Panel#747]
### 请描述您的问题

我试图在我的海外服务器安装1panel，系统ubuntu，用以下命令：
`curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sudo bash quick_start.sh`
但由于ping不通resource.fit2cloud.com，并不能成功下载脚本并执行，国内服务器可以成功执行。
那么如果我手动安装，后续的在线升级应该也不可行，能提供一下手动安装和后续手动升级的方法吗？

**Comment by Star-tears** [comment]
通过观察安装脚本，我已成功安装1panel，不出所料，检查更新及应用商店功能皆请求超时，无法使用。
是否有考虑官方站点建设镜像站点？

**Comment by cyril-cheng** [comment]
确实是这样，目前官方的安装脚本用的都是国内的镜像地址。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会针对境外服务器不能正常下载资源的问题做出优化。
