### ISSUE TITLE
【运行环境】各种语言的运行环境需求汇总

### ISSUE THREAD

**Issue by maninhill** [1Panel-dev/1Panel#748]
### 请描述您的问题

快速部署各种 Web 应用，是 1Panel 的一个重要目标。我们会优先支持 PHP 运行环境，后续再逐步增加对各类语言的相应运行环境的支持。我们通过这个 Issue 来跟踪我们对各类运行语言的支持进度。

- [x] PHP 运行环境 
- [x] Node.js 运行环境 #397
- [x] Java 运行环境
- [x] Golang 运行环境
- [x] Python 运行环境
- [ ] .NET 运行环境

Node 运行环境支持排期在 v1.7 版本，十月份发布，敬请期待。

**Comment by itpleb** [comment]
.net7

**Comment by JohnnyZhang0628** [comment]
> .net7

+1

**Comment by ht0222** [comment]
Java/Tomcat 运行环境

**Comment by cyril-cheng** [comment]
nodejs刚需，既可以做运行环境也可以做守护进程

**Comment by smanx** [comment]
node环境

**Comment by wuxiaol1981** [comment]
.net6  .net7

**Comment by sunxiaolong321** [comment]
python环境

**Comment by fanfanxhf** [comment]
node

**Comment by E8A281E6ACA2** [comment]
node+Java都要有

**Comment by Azir-11** [comment]
Java环境，spring boot项目的启动管理

**Comment by betgar** [comment]
rust环境

**Comment by q127981** [comment]
python很需要的

**Comment by caikun-cc** [comment]
希望能尽快加入Java和Node

**Comment by youliaoxia** [comment]
希望加入golang build后单文件运行环境 还有mongodb4.4版本下载 现在用到6.0的很少

**Comment by SillyDay** [comment]
Java/Tomcat 运行环境

**Comment by Jengro777** [comment]
Clojure     源码编译metabse的时候需要Clojure 语言环境

**Comment by zzmzaizai** [comment]
.net 运行环境

**Comment by canyanol650** [comment]
.net 6

**Comment by aidevjoe** [comment]
Go

**Comment by Jengro777** [comment]
v

**Comment by ht0222** [comment]
> ### 请描述您的问题
> 快速部署各种 Web 应用，是 1Panel 的一个重要目标。我们会优先支持 PHP 运行环境，后续再逐步增加对各类语言的相应运行环境的支持。我们通过这个 Issue 来跟踪我们对各类运行语言的支持进度。
> 
> * [x] PHP 运行环境
> * [ ] Java/Tomcat 运行环境
> * [ ] Node 运行环境[[功能] 增加对 Node.JS 的项目支持 #397](https://github.com/1Panel-dev/1Panel/issues/397)
> * [ ] Go 运行环境
> 
> 如果大家有建议，请在这个 Issue 下面留言。
java，node，go，python，一个一个来

**Comment by Jengro777** [comment]
wasmtime

wasmer

wasmedge

**Comment by Jengro777** [comment]
Miniconda

**Comment by maxbad** [comment]
golang 编译出来的单文件,能开机自动启动, 期待一下

**Comment by Jengro777** [comment]
> ### 请描述您的问题
> 快速部署各种 Web 应用，是 1Panel 的一个重要目标。我们会优先支持 PHP 运行环境，后续再逐步增加对各类语言的相应运行环境的支持。我们通过这个 Issue 来跟踪我们对各类运行语言的支持进度。
> 
> * [x]  PHP 运行环境
> * [ ]  Java/Tomcat 运行环境
> * [ ]  Node 运行环境 [[FEATURE] 增加对 Node.JS 的项目支持 #397](https://github.com/1Panel-dev/1Panel/issues/397)
> * [ ]  Go 运行环境
> 
> 如果大家有建议，请在这个 Issue 下面留言。

python环境其实安装不同版本还是有可能影响系统的，可以使用Miniconda

**Comment by Jengro777** [comment]
k8s 和 helm 算不算

**Comment by Dacong-wu** [comment]
Nodejs

**Comment by Jaffoo** [comment]
.net 6以及更高版本

**Comment by mingyangzhu** [comment]
.net5 +

**Comment by boommanpro** [comment]
java

**Comment by ghost** [comment]
.Net环境这个在计划中么

**Comment by wanghe-fit2cloud** [comment]
> .Net环境这个在计划中么

中短期内有没支持计划，望理解。

**Comment by Nardo021** [comment]
啥时候会考虑增加python

**Comment by yyn0210** [comment]
java tomcat  springboot

**Comment by mikemoi** [comment]
宝塔企业版用户，如果有python管理器，换过来毫不犹豫

**Comment by jsrcode** [comment]
有python的需求

**Comment by xiamuqingyu** [comment]
需要golang

**Comment by liShuangQ** [comment]
需要java，java也是个人建站占比较大的一种选择

**Comment by BruceLee569** [comment]
需要Python

**Comment by szylmzs** [comment]
python

**Comment by felix8070** [comment]
golang

**Comment by wanghe-fit2cloud** [comment]
目前可以使用 `Tomcat` 托管 `Java Web 应用程序`。
详细的使用教程请参考我们的论坛文章：[论坛文章链接](https://bbs.fit2cloud.com/t/topic/3723)

**Comment by aikeep** [comment]
Java

**Comment by mccj** [comment]
.net 运行环境

**Comment by 451891358** [comment]
.net 6 和.net 7

**Comment by qiutian110** [comment]
Java 运行环境

**Comment by clstech** [comment]
Java 运行环境

**Comment by JAINKRE** [comment]
非常需要python环境，感谢！我们目前生产端几乎都使用python-flask框架，如果可以支持，我们会选择从宝塔迁移。

**Comment by liuzhiliu** [comment]
java springboot

**Comment by gzxy0102** [comment]
golang和python

**Comment by andywu188** [comment]
.net6 .net7 .net8 .net9

**Comment by leo-yi** [comment]
Java 运行环境

**Comment by zhengkunwang223** [comment]
> Java 运行环境

Java Go 运行环境将在v1.10.12版本发布

**Comment by chongzi** [comment]
golang  python

**Comment by piscesmax** [comment]
Python!!!!!

**Comment by maninhill** [comment]
Go 和 Java， v1.10.12-lts 已经支持。

**Comment by dexiaoly** [comment]
python环境

**Comment by fengci** [comment]
python环境

**Comment by xaoyaoo** [comment]
python环境

**Comment by xaoyaoo** [comment]
python环境

**Comment by shoval-dev** [comment]
催更一下python运行环境，一年多了

**Comment by Flames1217** [comment]
请问python环境预计什么时候会上线

**Comment by fenxw** [comment]
python

**Comment by mlosun** [comment]
> 请问python环境预计什么时候会上线

+1

**Comment by 2939293859** [comment]
请问python环境预计什么时候会上线

+1

**Comment by songpy97** [comment]
python 催一下下

**Comment by cinyan10** [comment]
> 请问python环境预计什么时候会上线

+1

**Comment by kuilei0926** [comment]
催更python

**Comment by xhanglizhu** [comment]
催更.net 8

**Comment by sealoyal2018** [comment]
催更.net

**Comment by QYG2297248353** [comment]
php 如何添加 git 应用

**Comment by BruceLee569** [comment]
自编译nginx或openresty，以支持更多c模块。

**Comment by mimimiaomiao1** [comment]
请问啥时候支持netcore

**Comment by wanghe-fit2cloud** [comment]
v1.10.22 版本已发布。

**Comment by porter2019** [comment]
.net环境下，我自己构建了一个asp.net8.0的镜像放在阿里云上，容器镜像我中我已经把这个自定义的镜像拉下来了，创建.NET运行环境能否支持我这个自定义的镜像？

**Comment by Fangfang2468** [comment]
可以支持rust的运行环境吗
