### ISSUE TITLE
[QUESTION] 无法在Rocky Linux 9.1 启动

### ISSUE THREAD

**Issue by sunyong01** [1Panel-dev/1Panel#750]
### 请描述您的问题

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/43025602/233681003-f14abe08-535e-42a4-a2ff-225b3c6e4539.png">
能够正常安装，但无法在Rocky Linux 9.1 启动，使用一般的账户和root账户都不行
<img width="802" alt="image" src="https://user-images.githubusercontent.com/43025602/233681870-7da315d7-634d-45cc-9e23-ec6f17018ad8.png">

**Comment by wanghe-fit2cloud** [comment]
1、手动执行命令停止服务: 
```shell
1pctl stop
```
2、直接运行 1panel 二进制文件，看一下错误日志:
```shell
/usr/local/bin/1panel
```

**Comment by sunyong01** [comment]
<img width="790" alt="image" src="https://user-images.githubusercontent.com/43025602/233762180-511b7b9d-1b46-44e4-81a2-a0e2e88efd53.png">
段错误（核心已转储）

> 1、手动执行命令停止服务：
> 
> ```shell
> 1pctl stop
> ```
> 
> 2、直接运行1panel二次制作文件，看一下错误日志：
> 
> ```shell
> /usr/local/bin/1panel
> ```

**Comment by exfanc** [comment]
RockyLinux，我遇到相同故障，全默认安装，但 OPT/1panel 是个空文件夹，它只是在下载文件夹里面自己解压缩了，另外 dump 里面和 1panel 有关的日志 是不是这个 “1panel[940]: segfault at 7f0b9bc81a0f ip 00007f0b9bc81a0f sp 00007ffee4e06ca0 error 15 in 1panel[7f0b990d2000+2bb1000]” 这种错误出现了一大堆，都长一个样，这里只复制了一行。

**Comment by sunyong01** [comment]
> RockyLinux，我遇到相同故障，全默认安装，但 OPT/1panel 是个空文件夹，它只是在下载文件夹里面自己解压缩了，另外 dump 里面和 1panel 有关的日志 是不是这个 “1panel[940]: segfault at 7f0b9bc81a0f ip 00007f0b9bc81a0f sp 00007ffee4e06ca0 error 15 in 1panel[7f0b990d2000+2bb1000]” 这种错误出现了一大堆，都长一个样，这里只复制了一行。

是的，和我的情况是一样的，文件夹是空的，我不知道怎么去查看dump，可能是调试器的配置错误
<img width="721" alt="image" src="https://user-images.githubusercontent.com/43025602/233789389-7e261d67-0b96-4343-87e5-5f9ed924de8b.png">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后面版本中适配一下该操作系统。

**Comment by sunyong01** [comment]
确定了原因，可能与SELinux有关，在cockpit中的SELinux中点击了应用方案后，面板可以正常启动
![image](https://user-images.githubusercontent.com/43025602/233941299-0c0fd0b9-778b-4125-9b51-c769aeecac6e.png)
