### ISSUE TITLE
[BUG]防火墙管理无法区分allow和route allow

### ISSUE THREAD

**Issue by QAQ5555** [1Panel-dev/1Panel#751]
### 1Panel 版本

1.1.3

### 问题描述

防火墙管理无法区分allow和route allow规则,显示两个相同规则,导致误认为规则重复最终导致规则误删除

### 重现步骤

新建allow和route allow规则,在防火墙管理显示完全一样

### 期待的正确结果

正确显示规则为allow或者为route allow
建议增加v6端口的显示

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by maninhill** [comment]
请问这个问题有进展吗？

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Is there any progress on this issue?

**Comment by wanghe-fit2cloud** [comment]
目前 v1 最新版本已经支持了 IPv6 端口的显示。

**Comment by wanghe-fit2cloud** [comment]
无法区分 allow 和 route allow 规则的问题，我们会在近期版本优化。

**Comment by ssongliu** [comment]
经过检查，早期版本已经完成该问题的修改，暂时先关闭这个 issue，后续如果还有问题可以重新打开

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
After inspection, the earlier version has completed the modification of this issue. This issue will be closed temporarily. If there are still problems later, you can reopen it.
