### ISSUE TITLE
[FEATURE]流量监控默认网卡选择

### ISSUE THREAD

**Issue by QAQ5555** [1Panel-dev/1Panel#752]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

概览流量监控默认选择为实际的流量出口网卡如eth0而不是all,docker内部流量导致all流量比实际出口流量大

### 请描述你建议的实现方案

概览流量监控默认选择为实际的流量出口网卡如eth0

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
