### ISSUE TITLE
[Feature] Hope to add support for GPU load display on the monitoring page

### ISSUE THREAD

**Issue by wukaka155** [1Panel-dev/1Panel#7523]
### 1Panel Version

 v1.10.2-lts

### Please describe your needs or suggestions for improvements

在监控页面增加对 GPU负载情况支持

**Comment by zhengkunwang223** [comment]
GPU 使用率是专业版功能，当前已经支持

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
GPU usage is a professional version feature and is currently supported
