### ISSUE TITLE
[Bug] mfa cannot log in after upgrading v1.10.22-lts

### ISSUE THREAD

**Issue by whhya** [1Panel-dev/1Panel#7524]
### 1Panel Version

v1.10.22-lts

### Problem Description

![image](https://github.com/user-attachments/assets/089ad7b9-4ddd-472a-9b60-9b59d89f0ff0)
单纯点击升级系统，升级后重新打开页面登录没办法再次登录

### Steps to Reproduce

更新操作

### The expected correct result

正常登录

### Additional Information

操作系统版本: Debian GNU/Linux 12 (bookworm)
内核版本: 6.1.0-25-cloud-amd64
系统架构:x86_64
CPU 信息:  Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz
BIOS Model name:                      3.0  CPU @ 2.0GHz

**Comment by whhya** [comment]
进入服务器手动重启后恢复正常

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Enter the server and manually restart it to return to normal.
