### ISSUE TITLE
[Feature] I hope to add a database backup of sqlserver

### ISSUE THREAD

**Issue by yyg-max** [1Panel-dev/1Panel#7528]
### 1Panel Version

v1.10.22-lts

### Please describe your needs or suggestions for improvements

目前只有mysql、redis等可以备份，希望加一个sqlserver的备份我需要弄一台服务器定时每天备份生产的数据库，还有就是我生产的是window，需要把备份的下载下来手动进行恢复不能直接在1p上进行恢复，有时候也会把生产的同步到本地。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈！我们将在后续版本中考虑在数据库页面增加对 SQL Server 的管理支持。
届时，我们也将在计划任务页面增加对 SQL Server 数据库备份类型的支持。

**Comment by wanghe-fit2cloud** [comment]
统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/2229
