### ISSUE TITLE
[Bug] 数据库备份翻页加载时间过长

### ISSUE THREAD

**Issue by cktk** [1Panel-dev/1Panel#7531]
### 1Panel Version

v1.10.22-lts

### Problem Description

前8页翻页很快没问题  到了后面的一直在loading

![image](https://github.com/user-attachments/assets/dba2cc10-d2ce-454b-8d32-63a5311ffeb2)

![image](https://github.com/user-attachments/assets/ec4cf219-f21d-4d1b-80b0-27fbd2ddb061)

jia'z加载成功所需时间很长
![image](https://github.com/user-attachments/assets/93259fb8-a7bb-4c23-84c8-b0a49f0c4dbc)

### Steps to Reproduce

可以复现

**Comment by cktk** [comment]
为啥github输入的中文都变成英文了 真烦人啊

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Why do the Chinese input on GitHub change to English? It’s so annoying.

**Comment by wanghe-fit2cloud** [comment]
重复 https://github.com/1Panel-dev/1Panel/issues/7530
