### ISSUE TITLE
[Feature] I hope the app store can adapt to the Lilishhop mall system

### ISSUE THREAD

**Issue by allyn0303** [1Panel-dev/1Panel#7534]
### 1Panel Version

v1.10.22-lts

### Please describe your needs or suggestions for improvements

希望应用商店能够适配 Lilishop 商城系统
https://gitee.com/beijing_hongye_huicheng/lilishop

### Please describe the solution you suggest

希望应用商店能够适配 Lilishop 商城系统
https://gitee.com/beijing_hongye_huicheng/lilishop

**Comment by wanghe-fit2cloud** [comment]
注意到该应用依赖的服务较多，不建议在应用商店中进行维护。推荐通过容器编排功能进行实现。
