### ISSUE TITLE
[Feature] It is recommended to add a temporary password and maintained account, set permissions, and operate the screen recording function

### ISSUE THREAD

**Issue by tangyuanhaoyuan** [1Panel-dev/1Panel#7535]
### 1Panel Version

v1.10.22-lts

### Please describe your needs or suggestions for improvements

有时候需要开发者或维护人员排查问题，每次给面板账号密码有些不放心，建议增加临时密码和账号权限管理，录屏审计功能。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈！目前我们暂无计划支持该需求。

**Comment by wanghe-fit2cloud** [comment]
你可以参考一下 [JumpServer](https://github.com/jumpserver/jumpserver)，它应该能满足你的需求。
