### ISSUE TITLE
[FEATURE]项目组能提供进程守护功能吗

### ISSUE THREAD

**Issue by cyril-cheng** [1Panel-dev/1Panel#754]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

最近正在将之前的宝塔面板的项目陆续搬迁到1panel。
宝塔面板的传统管理模式和1panel的全容器管理模式差别还是挺大的。
php项目运行之后，开启queue队列服务，在宝塔直接用pm2或者supervisor都可以管理，请问在1pannel如何管理容器项目的队列服务呢？官方能提供个pm2或者supervisor管理器，还是有其他的方法来管理哇？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们在后续版本中会考虑支持 pm2 以及 supervisor 管理器。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布。

**Comment by jevantang** [comment]
> v1.5.0 版本已发布。

请问 `php artisan queue:work` 这样的命令，怎么守护进程呢？这个 PHP 是容器。
