### ISSUE TITLE
[BUG]数据库中的phpMyAdmin访问出错

### ISSUE THREAD

**Issue by yikwongee** [1Panel-dev/1Panel#755]
### 1Panel 版本

1.1.3

### 问题描述

在安装了phpMyAdmin后，并且通过反代的访问面板后，在去点击访问【数据库---phpMyAdmin】就会通过该反代地址去访问phpMyAdmin的地址

### 重现步骤

![image](https://user-images.githubusercontent.com/77314844/233782839-322d3085-9cf6-466e-8488-551c7baaae46.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中修复该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
