### ISSUE TITLE
[Bug] SSL certificate of panel cannot be updated by '1pctl restart' command or 'restart panel' button in toolbox of web panel

### ISSUE THREAD

**Issue by ITsPro-CN** [1Panel-dev/1Panel#7555]
### Contact Information

凌霞News5-Pro

### 1Panel Version

1.10.20-lts

### Problem Description

I did double check the SSL certificate configuration in security tab of panel setting page, the expired date is 2025-03-03. Chrome shows that the SSL certificate of panel port expired in 2024-12-15, which means it still use the old SSL certificate. The panel use the same SSL certificate with my website, which function normally at the same time. 

I tried the '1pctl restart' command and 'restart panel' button in toolbox of web panel, both didnot work. 

Finally, when i enter the 'detail' page of panel SSL certificate in security tab of panel setting, and click 'confirm' button with nothing changed, the SSL certificate of panel have been updated.

### Steps to Reproduce

Server and 1panel service have not been restarted after the SSL certificate be renewed manully, then SSL certificate expired, and try to fix this.

### The expected correct result

The '1pctl restart' command and 'restart panel' button in toolbox show reload the SSL certificate.

### Additional Information

我三台服务器都遇到了这个问题。简单来说就是服务器重启导致SSL证书自动续期掉了，我就手动续了，续完没重启。网站是更新过SSL证书了，但面板还没有重启过，所以证书过期后浏览器访问面板就提示证书过期了。这时候理论上我重启面板应该就能更新SSL证书了，但事实上我试了面板重启命令和工具箱里的重启面板按钮，SSL证书都没有被更新，也就是说这两种方法不会重载SSL证书。最后是到面板设置的SSL证书详情里面，重新确认了一边，通过确认后自带的重启，才更新了SSL证书。

**Comment by wanghe-fit2cloud** [comment]
我们已在最新版本中尝试修复了该问题，建议将 1Panel 升级至最新版本后再确认一下问题是否仍然存在。
https://github.com/1Panel-dev/1Panel/releases/tag/v1.10.22-lts
