### ISSUE TITLE
[QUESTION]安装部署1Panel的时候，是否会影响到服务器原本的环境?

### ISSUE THREAD

**Issue by okFancy** [1Panel-dev/1Panel#756]
### 请描述您的问题

请教安装部署1Panel的时候，是否会影响到服务器原本的环境?_（ps: 之前安装过宝塔，要求必须是全新环境的机器）_

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，1Panel 是基于 Docker 来部署管理其他应用，对系统的侵入影响非常小。
