### ISSUE TITLE
[FEATURE]建议添加同时支持php7.4/php7.2/php7.1三种版本

### ISSUE THREAD

**Issue by broommonk** [1Panel-dev/1Panel#757]
### 1Panel 版本

v1.1.3

### 请描述您的需求或者改进建议

两种场景，需要php多个版本共存的。

第一种：
比如A站点是：php7.1
B站点是：php7.2
C站点是：php7.4
这种情况就需要多个php7.x版本共存。

第二种：
还有一种情况，同一个站点，需要两种以上的php版本。
比如，运行主程序，需要版本的是php5.6
但是，绑定多一个域名到这个站点的目录，需要的版本是php7.1，运行的是这个主程序里面的一个子应用。

### 请描述你建议的实现方案

二选一：
1、在环境那里，支持多次安装不同版本的php，而不是现在安装完一次就提示已经安装不能重复安装。
2、在环境那里，每种版本增加一个应用，比如php7.4一个，php7.2一个，php7.1一个。

### 附加信息

很多php程序，很挑版本，甚至同一个程序里面，有不同的应用，需要不同的php版本的。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续的版本中考虑您提的上述需求。

**Comment by zhengkunwang223** [comment]
v1.2 版本已经支持
