### ISSUE TITLE
[FEATURE]希望支持postgres管理。

### ISSUE THREAD

**Issue by cddqssc** [1Panel-dev/1Panel#758]
### 1Panel 版本

1.1.2

### 请描述您的需求或者改进建议

希望支持postgres管理，目前在数据库功能里只有mysql和redis可以管理

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持 pg 数据库的可视化管理。

**Comment by cddqssc** [comment]
> 

感谢，今天又体验了一天的pg数据库，目前看来支持的东西很少，只是运行了一下docker，无法利用UI管理，备份也会失败，也不支持PG的一些重要参数配置

**Comment by Mr-Ao-Dragon** [comment]
请求支持外来postgresql数据库管理

**Comment by Mr-Ao-Dragon** [comment]
> 请求支持外来postgresql数据库管理

换个思路嘛，pgsql虽然不推荐使用dcoker但不妨碍面板连进去，并且我知道一个orm https://github.com/uptrace/bun/

**Comment by wanghe-fit2cloud** [comment]
v1.9.3 版本已发布

**Comment by hibem** [comment]
> v1.9.3 版本已发布

只有一个版本可以选择，无法切换版本

**Comment by wanghe-fit2cloud** [comment]
> > v1.9.3 版本已发布
> 
> 只有一个版本可以选择，无法切换版本

目前应用商店中默认安装最新版本，你具体需要哪个版本？
> 也可以尝试添加远程 PostgreSQL 数据库（目前支持多个版本）
