### ISSUE TITLE
[Bug] Advanced settings are missing

### ISSUE THREAD

**Issue by JasonWu55** [1Panel-dev/1Panel#7585]
### Contact Information

woowujasonwu@gmail.com

### 1Panel Version

v1.10.22-lts

### Problem Description

![image](https://github.com/user-attachments/assets/fcd26996-1ed5-4e86-8d95-e64143d4dff4)
原本左邊的高級設置不見了，設定也沒有隱藏選項

### Steps to Reproduce

安裝1panel後

**Comment by zhengkunwang223** [comment]
海外版暂时还没有高级功能，可以使用 https://1panel.cn 中的安装脚本

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
The overseas version does not have advanced features yet, you can use the installation script in https://1panel.cn
