### ISSUE TITLE
[FEATURE] 一键迁移其他面板的数据

### ISSUE THREAD

**Issue by vlssu** [1Panel-dev/1Panel#759]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

就像宝塔有一键迁移api，如果能支持迁移宝塔等一系列面板的数据（数据库，站点）到1panel，让用户迁移更方便点

### 附加信息

![image](https://user-images.githubusercontent.com/43847794/233813199-5f00774e-a89b-420f-af11-ffd06578a4bf.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
我们近期大概率是不会支持一键迁移功能。
