### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by lazydog28** [1Panel-dev/1Panel#7590]
### Contact Information

yun981128@gmail.com

### 1Panel Version

v1.10.22-lts

### Problem Description

应用商店内one-api镜像版本0.6.9已经无法拉取，请更新至0.6.10

### Steps to Reproduce

安装应用商店内one-api镜像版本0.6.9版本

**Comment by zhengkunwang223** [comment]
感谢反馈 我们检查一下

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Thanks for the feedback, let’s check it out

**Comment by wanghe-fit2cloud** [comment]
版本已更新至 v0.6.10
