### ISSUE TITLE
[Feature] Hope 1panel supports container grouping and group application start-stop management

### ISSUE THREAD

**Issue by vss80p585** [1Panel-dev/1Panel#7592]
### 1Panel Version

v1.10.21-lts

### Please describe your needs or suggestions for improvements

需求背景：
引导客户使用部署了1panel作为底层，由于客户有多个，同时客户计划将1panel作为GPU主环境，由于无容器分组管理，客户运行了商店较多的应用，CPU被负载挤爆，向我们1panel代理商提出了改进需求，希望1panel 支持容器分组，以及分组应用化启停管理。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
重复需求，容器分组相关需求的讨论，统一汇总到该 issue https://github.com/1Panel-dev/1Panel/issues/4219
