### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Moon-du** [1Panel-dev/1Panel#760]
### 联系方式

qm2737@gmail.com

### 1Panel 版本

1.1.3

### 问题描述

Chrome版本 112.0.5615.137（正式版本） (arm64)中面板不显示左侧菜单栏，换成Edge可以正常显示
![WX20230423-103722](https://user-images.githubusercontent.com/69743019/233816567-44b1ecd5-beee-42a8-bb22-48cd28c2d5ed.png)

### 重现步骤

![WX20230423-103701@2x](https://user-images.githubusercontent.com/69743019/233816571-f6bdb601-2c39-4a96-8905-88403eb62076.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我在本机 mac m2 上没有复现该问题，大概率还是浏览器的问题。

**Comment by cyril-cheng** [comment]
是不是装了什么拦截插件或者脚本插件

**Comment by Moon-du** [comment]
> 感谢反馈，我在本机 mac m2 上没有复现该问题，大概率还是浏览器的问题。

可能是吧 我研究下，开了无痕访问是正常的
