### ISSUE TITLE
[Bug] The container interface is misaligned and blank

### ISSUE THREAD

**Issue by tangyuanhaoyuan** [1Panel-dev/1Panel#7609]
### 1Panel Version

v1.10.22-lts

### Problem Description

用的笔记本14寸吧，比较小的屏幕上，容器比较多，上面几排点击更多滑动下面按，底部会出现空白

### Steps to Reproduce

<img width="627" alt="333" src="https://github.com/user-attachments/assets/bc40bf20-ad12-425e-bd07-aec35a0c824c" />

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，已在本地复现该问题，具体进度可参考该 issue https://github.com/1Panel-dev/1Panel/issues/7288
