### ISSUE TITLE
[FEATURE] 对NGINX，APACHE，MYSQL，PHP 等的负载信息有更详细的显示和修改

### ISSUE THREAD

**Issue by Daiyangcheng** [1Panel-dev/1Panel#761]
### 1Panel 版本

v1.1.3.2

### 请描述您的需求或者改进建议

在宝塔面板中，点击NGINX等软件的设置都可以看到负载信息和各种配置项的快捷修改

这有助于运维改善服务器配置项和运行环境

以及能否添加更多的软件，例如原生NGINX，tengine，kangle等主流web服务器软件

### 请描述你建议的实现方案

可以通过检索系统负载等方式获取数据，百度上都有方法，就是需要将数据进行格式化呈现

**Comment by wanghe-fit2cloud** [comment]
网站 - openresty
数据库 - mysql、redis
点击设置按钮，支持查看负载信息或修改配置文件等操作
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/46734380/233844241-cf5584ec-54e9-416a-8c9e-f34c9e9d89bd.png">
