### ISSUE TITLE
[FEATURE]网站批量创建,数据备份计划支持云盘

### ISSUE THREAD

**Issue by zhangye151** [1Panel-dev/1Panel#764]
### 1Panel 版本

v1.1.3.2

### 请描述您的需求或者改进建议

1. 需要网站批量创建，有利于从环境迁移
2. 需要数据备份计划支持云盘，如onedrive或NAS盘
3. 可向宝塔借鉴，显示根目录备注

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
我们暂无计划支持批量创建网站的计划，望理解。
环境迁移可以考虑使用 `面板设置` - `快照` 功能。
最新版本已经支持 OneDrive
