### ISSUE TITLE
[FEATURE]数据库软件

### ISSUE THREAD

**Issue by gracelsy** [1Panel-dev/1Panel#765]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

安装应用自定义数据库，这样方便点

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
考虑到应用备份、恢复功能不好统一管理，我们应该不会支持用户在创建应用时自定义数据库。
> 如果是 MySQL 或者 MariaDB 数据库，可以将其添加为远程数据库。
