### ISSUE TITLE
[FEATURE]MYSQL增加5.5版本

### ISSUE THREAD

**Issue by bufanblog** [1Panel-dev/1Panel#766]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

1H1G低配VPS服务器安装MYSQL 5.6以上版本，占用内存大然后服务器可能会死机。
1Planel+OpenResty+PHP8.2+MYSQL5.7，占用内存超过80%，还没运行站点就死机了。
宝塔面板+NGINX1.18+PHP8.0+MYSQL5.5，内存占用不到45%，搭建的nextcloud，已稳定运行半年多。
MYSQL5.5占用内存小，望增加5.5版本，谢谢。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1、内存占用的问题，我们会在后续版本中持续优化。
2、我们会在后续版本中考虑支持 MySQL 5.5 版本。

**Comment by wanghe-fit2cloud** [comment]
最新版本支持了 MySQL 5.6。
至于 MySQL 5.5，我们近期版本暂无支持计划，望理解。
