### ISSUE TITLE
[FEATURE]希望容器管理增加一个CPU权重比的设定选项

### ISSUE THREAD

**Issue by iamyangyiok** [1Panel-dev/1Panel#767]
### 1Panel 版本

1.1

### 请描述您的需求或者改进建议

希望容器管理增加一个CPU权重比的设定选

### 请描述你建议的实现方案

可以每个容器单独设定CPU响应优先级 高 中 低三档，让主要业务响应更快速，占用更多CPU 时间。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，您是想通过 cpu-shares 来设置 CPU 利用率权重吗？

**Comment by wanghe-fit2cloud** [comment]
最新版本已支持在创建容器时设置 CPU 权重。
