### ISSUE TITLE
[FEATURE]新增个ldap应用

### ISSUE THREAD

**Issue by cncentoscn** [1Panel-dev/1Panel#768]
### 1Panel 版本

v1.1.3.2

### 请描述您的需求或者改进建议

ldap使用的还是比较多

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑在应用商店中支持 openldap。

**Comment by wanghe-fit2cloud** [comment]
【应用商店】收集大家对常见应用的需求 #250

**Comment by wanghe-fit2cloud** [comment]
正式仓库已上架 OpenLDAP。
