### ISSUE TITLE
[BUG]文件搜索不存在的资源后，点击下面存在的目录也会提示资源不存在

### ISSUE THREAD

**Issue by CementWork** [1Panel-dev/1Panel#769]
### 1Panel 版本

1.1.3

### 问题描述

文件搜索不存在的资源后，点击下面存在的目录也会提示资源不存在。应该是出现资源不存在情况没有清理掉输入的内容导致。

### 重现步骤

在文件输入框中搜索不存在的资源，然后在点击下方存在的目录。

### 期待的正确结果

正常跳转，失败后清理掉搜索框记录的内容

**Comment by CementWork** [comment]
这个可以指定给我修复

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
在文件列表搜索不存在的资源时，列表会显示暂无数据。
我这里还不清楚您反馈的资源不存在是不是指的这里？
![image](https://user-images.githubusercontent.com/46734380/233914940-07ca3c84-9679-46de-975b-dc40450261b3.png)

**Comment by wanghe-fit2cloud** [comment]
> 这个可以指定给我修复

手动点赞 👍

**Comment by CementWork** [comment]
> 感恩反馈。 在文件列表搜索不存在的资源时，列表会显示暂无数据。 我这里还不清楚您反馈的资源不存在是不是指的在这里？ ![图像](https://user-images.githubusercontent.com/46734380/233914940-07ca3c84-9679-46de-975b-dc40450261b3.png)
![1682317741616_23FFF692-8394-4930-88E2-3614DDAAD9C4](https://user-images.githubusercontent.com/44991286/233916964-0375ef58-f844-400f-9fed-633de4974d01.png)
![1682317759152_E2FBC4B4-3C78-4711-9CF5-3ACD88039E4D](https://user-images.githubusercontent.com/44991286/233916986-29d9f9b9-4725-4142-a894-633f182d5958.png)
![1682317782479_AB4808D4-FBEE-43b5-88A4-8FC2B22C6208](https://user-images.githubusercontent.com/44991286/233917004-f6f540ad-bf7c-4ab5-96d8-d7152040c310.png)
![1682317893630_4C3BEBC4-8588-420d-8110-D7B3A2312FB2](https://user-images.githubusercontent.com/44991286/233917020-efa9a696-510a-4aa8-9d6a-e34d0a10700d.png)
大概就是这个现象

**Comment by xinkeng0** [comment]
我认为原因在于搜索一个不存在的目录之后，我们需要还原req的数据，放弃这次请求。
鉴于对整体代码的最小改动，我认为这样处理：
1. 记录原始Req
2. 进行此次搜索
3. 如果失败，还原原始Req
https://github.com/1Panel-dev/1Panel/blob/34e84081e311a958a6c75aee091fa41f80c04ccc/frontend/src/views/host/file-management/index.vue#L333-L343
@CementWork 欢迎PR

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
