### ISSUE TITLE
[BUG] 登录双重认证无法重置

### ISSUE THREAD

**Issue by faruzanCN** [1Panel-dev/1Panel#770]
### 1Panel 版本

V1.1.3

### 问题描述

登录双重验证那个码 要是我换手机或者APP卸载了怎么办   建议可以在服务器重置
![image](https://user-images.githubusercontent.com/46319425/233913628-2cae19f1-0f19-44e6-ae39-5f16917a31ad.png)

### 重现步骤

开启双重认证后重新登录

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中增加通过 1pctl 命令关闭动态口令认证的功能。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。

**Comment by Martinxux** [comment]
已经登不上的该咋办呢，我现在就卡在这

**Comment by Martinxux** [comment]
![Snipaste_2023-12-25_13-46-08](https://github.com/1Panel-dev/1Panel/assets/90446788/7a110ad6-3a73-4740-8dd2-37a78b9ea159)
看到解决方案了
