### ISSUE TITLE
[FEATURE]容器日志无限增大，需要有一个清空和关闭日志功能

### ISSUE THREAD

**Issue by 357341051** [1Panel-dev/1Panel#772]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

每个容器日志无限增大，需要有一个清空和关闭日志功能，最好最好还要有关闭写入日志的功能
![e04206d4ff594d29f32f16baf7a0b02](https://user-images.githubusercontent.com/118408640/233919672-72693cf6-c406-4eb1-9799-39ec73a17e55.png)
还有openresty生成的容器，点击日志，被火绒安全软件拦截请求了，报毒，哈哈，

![20cb45afffd506ff83350f600216251](https://user-images.githubusercontent.com/118408640/233919801-8e9fbf2b-6bb6-48fe-96fb-403b33d8be50.png)

**Comment by zhengkunwang223** [comment]
感谢反馈 后续版本支持此功能

**Comment by heyzqq** [comment]
> 感谢反馈 后续版本支持此功能

是否可以添加自定义的 docker 参数，这样不仅可以添加其他自定义参数，也可以添加限制日志大小的参数

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈 后续版本支持此功能
> 
> 是否可以添加自定义的 docker 参数，这样不仅可以添加其他自定义参数，也可以添加限制日志大小的参数

可以的，后续版本支持。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
