### ISSUE TITLE
容器网络 1panel-network 子网自定义修改

### ISSUE THREAD

**Issue by luweijun1992** [1Panel-dev/1Panel#776]
### 1Panel 版本

v1.1.3

### 请描述您的需求或者改进建议

当前1Panel安装完成后默认创建一个1panel-network，且子网无法自定义，跟现网存在冲突。
建议增加自定义该子网的参数。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
1、1panel-network 是应用商店创建应用时使用的默认网络，后续版本我们会支持用户用户自定义参数
2、跟现有网络存在冲突的情况，肯定是不存在的。
因为 docker 已经是处于正常运行状态，1panel-network 采用桥接模式创建，所用网段肯定不会和当前已有网段冲突。

**Comment by luweijun1992** [comment]
> 感谢反馈。 1、1panel-network 是应用商店创建应用时使用的默认网络，后续版本我们会支持用户用户自定义参数 2、跟现有网络存在冲突的情况，肯定是不存在的。 因为 docker 已经是处于正常运行状态，1panel-network 采用桥接模式创建，所用网段肯定不会和当前已有网段冲突。

冲突指的是跟现网办公网段或者服务器业务网段相同了。

**Comment by caixiaohaier** [comment]
我也是需要这个功能，我现网是学校的网络，学校网络服务器网段用了这个172.16.网段，会导致我无法访问到现网这个网段的资源。

**Comment by wanghe-fit2cloud** [comment]
我们会在下个版本支持上述需求。

**Comment by wanghe-fit2cloud** [comment]
v1.5.4 版本已发布，支持删除 1panel-network。

**Comment by luweijun1992** [comment]
> v1.5.4 版本已发布，支持删除 1panel-network。

只是删除而不是修改网段吗?

**Comment by wanghe-fit2cloud** [comment]
> > v1.5.4 版本已发布，支持删除 1panel-network。
> 
> 只是删除而不是修改网段吗?

是，不支持修改，可以删除后重建同名网络。
> 在容器使用该网络的情况下，也是不支持修改、删除等操作的。

**Comment by luweijun1992** [comment]
> > > v1.5.4 版本已发布，支持删除 1panel-network。
> > 
> > 
> > 只是删除而不是修改网段吗?
> 
> 是，不支持修改，可以删除后重建同名网络。
> 
> > 在容器使用该网络的情况下，也是不支持修改、删除等操作的。

是的，但是可以通过将所有引用1panel-network的容器删了后，修改1pannel某个配置文件里面的容器网段参数。
然后重启1panel服务重建这个。
或者在1panel软件安装时候提供向导输入，类似安装时候的端口、账号、密码等参数。
