### ISSUE TITLE
[FEATURE]数据库功能支持外部数据库

### ISSUE THREAD

**Issue by NoWhereMee** [1Panel-dev/1Panel#778]
### 1Panel 版本

v1.1.3

### 请描述您的需求或者改进建议

1. 现状：目前的1Panel Web 控制台仅支持系统内建数据库，无法支持外部数据库，如需在商店内安装halo、wiki.js等应用，均需当前服务器内构建数据库。
2. 建议：支持非当前服务器构建的数据库。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本考虑支持该需求。

**Comment by seagullz4** [comment]
忘记了端口怎么办

**Comment by wanghe-fit2cloud** [comment]
> 忘记了端口怎么办

查看 1Panel 用户信息：
```shell
1pctl user-info
```

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布，支持添加 MySQL 远程数据库。
目前版本在安装应用商店应用时还不支持选择远程数据库（计划是远程数据库稳定几个版本后再支持）。
