### ISSUE TITLE
[BUG]对于已经安装 lnmp 的主机，无法检测到 mysql 和 nginx

### ISSUE THREAD

**Issue by tonyzhou1890** [1Panel-dev/1Panel#783]
### 1Panel 版本

1.1.3

### 问题描述

主机已经安装 lnmp。
但在 1panel 的面板里没有检测到 mysql 和 nginx。
网站菜单里提示“未检测到 OpenResty ,请进入应用商店点击安装!”

### 重现步骤

1. 安装 lnmp
2. 安装 1panel

**Comment by zhengkunwang223** [comment]
1panel 的 OpenResty 和其他应用都是基于 docker 的，无法同步机器已经安装的 lnmp
