### ISSUE TITLE
[BUG] 首页流量监控显示错误

### ISSUE THREAD

**Issue by kawai-aki** [1Panel-dev/1Panel#787]
### 1Panel 版本

1.1.3

### 问题描述

在首页显示的流量监控上下行速度显示错误（颠倒了上下行的流量数据）

### 重现步骤

![屏幕截图 2023-04-25 225724](https://user-images.githubusercontent.com/92026851/234322285-62c7c96f-825e-4450-ac0e-630c0b0e9010.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在近期要发布的版本中修复该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
