### ISSUE TITLE
[BUG]文件更改失效

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#799]
### 1Panel 版本

1.1.3

### 问题描述

在1panel内更改文件内容后不生效，而且通过sftp或者bt更改内容后，1panel也没更新
sftp/bt:
![image](https://user-images.githubusercontent.com/19621032/234552586-03065044-9437-47df-b270-9a5c7a60762f.png)
![image](https://user-images.githubusercontent.com/19621032/234552841-25c108a7-9d12-4275-bb8e-375f04cf88a4.png)
1panel:
![image](https://user-images.githubusercontent.com/19621032/234552997-1dbf6821-d270-4e5e-8ad5-4675bb7a81ae.png)
但1panel日志显示更改内容成功
![image](https://user-images.githubusercontent.com/19621032/234554009-ad334011-5380-426d-b5d5-da2b6db5f472.png)

### 重现步骤

在1panel “主机-文件”内更改文件内容。
目前发现多次刷新后重新多次更改后会生效
是不是文件这块有什么缓存逻辑？

**Comment by zhengkunwang223** [comment]
您好 文件这块没有缓存逻辑 都是实时从宿主机取的 应该是修改文件之后没有自动刷新页面导致的

**Comment by Felmon** [comment]
> 您好 文件这块没有缓存逻辑 都是实时从宿主机取的 应该是修改文件之后没有自动刷新页面导致的

但是我手动刷新过好几次没有生效，只有当我多次刷新及重新编辑内容后才会生效。而且也不是每次编辑内容都不会生效，偶发性的

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
