### ISSUE TITLE
[BUG]dup_write_windows.go:3:21: undefined: os when build in windows

### ISSUE THREAD

**Issue by langrybird** [1Panel-dev/1Panel#800]
### 联系方式

1269616645@qq.com

### 1Panel 版本

dev

### 问题描述

在 window 下go build 报错 dup_write_windows.go:3:21: undefined: os
import “os” 后解决问题

### 重现步骤

在windows 下go build

**Comment by zhengkunwang223** [comment]
windows 下  build  1Panel linux 版本需要交叉编译 现在暂时没有测试在 WIndows 上编译的情况
可以参考 Makefile 中 build_backend_on_darwin 指令编写  build_backend_on_windows 指令
