### ISSUE TITLE
[FEATURE] 容器的管理缺少更新镜像并重启的功能

### ISSUE THREAD

**Issue by yfdoor** [1Panel-dev/1Panel#801]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

现在的容器管理，在编排页面只有编辑和删除的功能，缺少一个更新镜像然后重启容器的功能。容器界面也没有更新镜像的功能

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持更新容器镜像的功能。

**Comment by ssongliu** [comment]
感谢支持！v1.5.0 已经支持了容器镜像升级。
