### ISSUE TITLE
[QUESTION]Can I Set Up Basic HTTP Authentication in 1panel?可以配置HTTP基本认证？

### ISSUE THREAD

**Issue by gitzaai** [1Panel-dev/1Panel#802]
### 请描述您的问题

I access 1panel through a domain name. Some people say that configuring HTTP basic authentication for Nginx will be more secure, but I don’t know whether the use of the 1panel is the same as the normal LEMP environment.

我通过域名访问1panel，有人说为Nginx配置HTTP基本认证，会更安全，但是我不懂有关1panel的使用方法跟普通的LEMP环境是否一样

**Comment by zhengkunwang223** [comment]
您好 auth_basic 功能已经在测试中 v1.2 版本支持 感谢建议
