### ISSUE TITLE
[FEATURE]1panel是否有海外节点？

### ISSUE THREAD

**Issue by bufanblog** [1Panel-dev/1Panel#805]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

我买了一台美国地区的VPS，安装1panel成功，进入后台再打开“应用商店”，加载很慢，然后提示“请求超时！请您稍后重试”。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，目前境外服务器安装、升级 1Panel，以及更新应用等操作可能有超时的可能。

**Comment by cyril-cheng** [comment]
可以自己把docker的源替换成源站的源，1panel用的是阿里云的源

**Comment by bufanblog** [comment]
不会操作，我暂时先用着宝塔面板，等1panel完善了再说

**Comment by docker-master** [comment]
> 可以自己把docker的源替换成源站的源，1panel用的是阿里云的源

请问大佬怎么替换docker源，没有做1panel里面找到

**Comment by wanghe-fit2cloud** [comment]
> > 可以自己把docker的源替换成源站的源，1panel用的是阿里云的源
> 
> 请问大佬怎么替换docker源，没有做1panel里面找到

安装包中有提供 `install.sh` 脚本。
> 也可以考虑通过下载安装包安装。
