### ISSUE TITLE
[FEATURE]建议状态面板优化兼容性

### ISSUE THREAD

**Issue by iucvcom** [1Panel-dev/1Panel#807]
### 1Panel 版本

v1.1.3

### 请描述您的需求或者改进建议

优化挂载路径及内存、磁盘容量的显示
![image](https://user-images.githubusercontent.com/37103190/234745005-70867eb4-877c-4c59-bb16-7e18fa43bace.png)

### 请描述你建议的实现方案

建议方案：
1、路径截取前几位，后面的用...代替，当鼠标放上去的时候再显示完整路径。
2、硬盘容量超过1024MB用GB显示，超过1024GB用TB显示。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
