### ISSUE TITLE
一些不重要的问题

### ISSUE THREAD

**Issue by seagullz4** [1Panel-dev/1Panel#809]
### 请描述您的问题

请问这个面板是否支持纯ipv6，如果不支持，后续版本会不会支持ipv6，谢谢回答🙏

**Comment by seagullz4** [comment]
Okok
我测试了一下，的确支持纯ipv6
例如     [ipv6地址]:端口
的确可以进入面板进行正常管理，具体正在测试

**Comment by zhengkunwang223** [comment]
感谢反馈 ，我们没有测试过 ipv6 ，暂时也没有计划支持 ipv6 ，如果有问题 请继续在这个 issue 下回复，后续可能会支持

**Comment by seagullz4** [comment]
![Screenshot_20230427_153222_com.lemurbrowser.exts.jpg](https://user-images.githubusercontent.com/96653729/234791961-8ecbf223-65e8-4f54-ae6a-5328d55a4812.jpg)

实际测试使用ipv6搭建本面板，使用基本正常 没有什么无法使用的bug，使用方法和ipv4一样，基本没有区别

**Comment by zhengkunwang223** [comment]
感谢反馈

**Comment by seagullz4** [comment]
❤❤❤❤
