### ISSUE TITLE
docker部署mysql时区问题

### ISSUE THREAD

**Issue by 1549199364** [1Panel-dev/1Panel#815]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

挂载宿主机的时区

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本安装 MySQL 数据库时，容器内时间会和宿主机时间保持同步。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。

**Comment by hkbbdx** [comment]
docker 时区不是上海的，怎么改？

**Comment by hkbbdx** [comment]
我是昨天刚安装的 发现时间不对，请问什么时候可以修复呢？

**Comment by wanghe-fit2cloud** [comment]
MySQL 8 安装文件：
![image](https://github.com/1Panel-dev/1Panel/assets/46734380/28506c83-767b-4252-9f4a-8f3083266634)
