### ISSUE TITLE
[FEATURE] 建议面板前端资源添加缓存

### ISSUE THREAD

**Issue by binge6** [1Panel-dev/1Panel#828]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

现在面板前端刷新所有js和css文件都要重新下载未命中缓存

### 请描述你建议的实现方案

建议在返回的response 添加缓存相关 header

**Comment by zhengkunwang223** [comment]
好的 这个我们试一下 没问题的话可以加

**Comment by binge6** [comment]
感谢回复，我通过反向代理用域名访问面板，在nginx配置里增加缓存配置可解决
![uTools_1682698030533](https://user-images.githubusercontent.com/40023013/235201684-f018fa4f-f209-4341-89e5-06e29ae34ce9.png)
，同样再提个相关的建议，宝塔在新建网站的配置里默认会有静态文件缓存相关配置，1panel 或许也可以考虑加一下 或者 增加可选项
<img width="608" alt="image" src="https://user-images.githubusercontent.com/40023013/235200708-48bf8b36-fe34-4872-a84a-102c58b7e7d9.png">

**Comment by zhengkunwang223** [comment]
> 感谢回复，我通过反向代理用域名访问面板，在nginx配置里增加缓存配置可解决
> 
> ![uTools_1682698030533](https://user-images.githubusercontent.com/40023013/235201684-f018fa4f-f209-4341-89e5-06e29ae34ce9.png)
> 
> ，同样再提个相关的建议，宝塔在新建网站的配置里默认会有静态文件缓存相关配置，1panel 或许也可以考虑加一下 或者 增加可选项
> 
> <img width="608" alt="image" src="https://user-images.githubusercontent.com/40023013/235200708-48bf8b36-fe34-4872-a84a-102c58b7e7d9.png">
> 
> 
> 
> 

您好，我们的1.2版本会增加配置反向代理功能，可以配置缓存

**Comment by wanghe-fit2cloud** [comment]
建议将 1Panel 升级到最新版本，体验全新新增功能。
