### ISSUE TITLE
Red Hat Enterprise 8.7上无法使用

### ISSUE THREAD

**Issue by E8A281E6ACA2** [1Panel-dev/1Panel#832]
### 1Panel 版本

Red Hat Enterprise 8.7

### 问题描述

无法启动1panel

### 重现步骤

是

### 期待的正确结果

是

### 相关日志输出

```shell
是
```

### 附加信息

数字

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续的版本中适配 Red Hat Enterprise 8 操作系统。

**Comment by wanghe-fit2cloud** [comment]
v1.3.5 版本已修复上述问题。
