### ISSUE TITLE
[FEATURE]希望应用商店能支持更多应用。

### ISSUE THREAD

**Issue by chenyueteng** [1Panel-dev/1Panel#833]
### 1Panel 版本

1.3.3

### 请描述您的需求或者改进建议

支持应用太少了无法满足日常使用希望能支持下: naocs、seata、sentinel、activemq、rabbitmq、rocketmq、kafka、elk、skywalking、zookeeper

### 请描述你建议的实现方案

支持应用太少了无法满足日常使用希望能支持下: naocs、seata、sentinel、activemq、rabbitmq、rocketmq、kafka、elk、skywalking、zookeeper

### 附加信息

支持应用太少了无法满足日常使用希望能支持下: naocs、seata、sentinel、activemq、rabbitmq、rocketmq、kafka、elk、skywalking、zookeeper

**Comment by wanghe-fit2cloud** [comment]
https://github.com/1Panel-dev/appstore

appstore 项目提供了提交应用、本地测试的相关教程。

**Comment by wanghe-fit2cloud** [comment]
#250
