### ISSUE TITLE
[QUESTION]安装失败

### ISSUE THREAD

**Issue by azhango** [1Panel-dev/1Panel#834]
### 请描述您的问题

2G内存服务器安装失败。

`
[1Panel Log]: ======================= 开始安装 ======================= 
设置 1Panel 安装目录（默认为/opt）：
[1Panel Log]: 您选择的安装路径为 /opt 
[1Panel Log]: ... 在线安装 docker 
# Executing docker install script, commit: a8a6b338bdfedd7ddefb96fe3e7fe7d4036d945a
+ sh -c 'yum install -y -q yum-utils'
软件包 yum-utils-1.1.31-54.el7_8.noarch 已安装并且是最新版本
+ sh -c 'yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo'
已加载插件：fastestmirror
adding repo from: https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
grabbing file https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo to /etc/yum.repos.d/docker-ce.repo
repo saved to /etc/yum.repos.d/docker-ce.repo
+ '[' stable '!=' stable ']'
+ sh -c 'yum makecache'
已加载插件：fastestmirror
Loading mirror speeds from cached hostfile
元数据缓存已建立
+ sh -c 'yum install -y -q docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-ce-rootless-extras docker-buildx-plugin'
warning: /var/cache/yum/x86_64/7/docker-ce-stable/packages/docker-buildx-plugin-0.10.4-1.el7.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 621e9f35: NOKEY
docker-buildx-plugin-0.10.4-1.el7.x86_64.rpm 的公钥尚未安装
https://mirrors.aliyun.com/docker-ce/linux/centos/7/x86_64/stable/Packages/docker-ce-23.0.5-1.el7.x86_64.rpm: [Errno -1] 软件包与预期下载的不符。建议：运行 yum --enablerepo=docker-ce-stable clean metadata
正在尝试其它镜像。

Error downloading packages:
  3:docker-ce-23.0.5-1.el7.x86_64: [Errno 256] No more mirrors to try.

[1Panel Log]: ... 启动 docker 
Failed to execute operation: No such file or directory
Failed to start docker.service: Unit not found.
[1Panel Log]: docker 安装失败 
`

**Comment by azhango** [comment]
CentOS7.9纯净安装会失败，带Docker可以成功。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，在线安装 docker 报错很有可能是超时了，看报错服务器 yum 源已经指向了 aliyun 仓库，你安装 1Panel 的服务器是在境外吗？

**Comment by azhango** [comment]
> 感谢反馈，在线安装 docker 报错很有可能是超时了，看报错服务器 yum 源已经指向了 aliyun 仓库，你安装 1Panel 的服务器是在境外吗？

国内服务器，我重置过两次系统，两次问题一致。换上带Docker的Linux可以正常安装。

**Comment by wanghe-fit2cloud** [comment]
我们的开发测试环境就是公有云、国内、CentOS 7.9，没有复现安装 Docker 失败的情况。
我们使用的在线安装 Docker 脚本是：
```shell
curl -fsSL https://get.docker.com | bash -s docker --mirror Aliyun
```

**Comment by luo-geng** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/29565303/d7f6f39b-c9fa-468c-bad7-a430dfa01f2c)
我是debian，安装compose失败，docker有插件版的compose，建议也支持下

**Comment by luo-geng** [comment]
![image](https://github.com/1Panel-dev/1Panel/assets/29565303/d7f6f39b-c9fa-468c-bad7-a430dfa01f2c)
我是debian，安装compose失败，docker有插件版的compose，建议也支持下

**Comment by luo-geng** [comment]
> ![image](https://user-images.githubusercontent.com/29565303/238106440-d7f6f39b-c9fa-468c-bad7-a430dfa01f2c.png) 我是debian，安装compose失败，docker有插件版的compose，建议也支持下

我手动创建目录依然是这个问题
