### ISSUE TITLE
[BUG]数据展示有点问题

### ISSUE THREAD

**Issue by azhango** [1Panel-dev/1Panel#835]
### 1Panel 版本

1.1.3

### 问题描述

![](https://jsd.cdn.zzko.cn/gh/jinghua66/klsdnfi@main/images/image.7co6j00mylk0.webp)

### 重现步骤

![](https://jsd.cdn.zzko.cn/gh/jinghua66/klsdnfi@main/images/image.7co6j00mylk0.webp)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，截图中想反馈的问题是上、下行的流量数据颠倒了这个问题吗？

**Comment by azhango** [comment]
> 

对，数据流颠倒了。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
