### ISSUE TITLE
[FEATURE]希望能有pbootcms平台

### ISSUE THREAD

**Issue by Flamingants** [1Panel-dev/1Panel#836]
### 1Panel 版本

v1.1.3

### 请描述您的需求或者改进建议

希望能有pbootcms平台

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们后续版本可能会考虑将该平台添加到应用商店。
当前版本你可以参考 [添加本地应用](https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8) 教程，然后就可以在应用商店中来管理该应用了。

**Comment by wanghe-fit2cloud** [comment]
#250
