### ISSUE TITLE
[QUESTION] 以后会做win版的吗？

### ISSUE THREAD

**Issue by xiaofeiTM233** [1Panel-dev/1Panel#837]
### 请描述您的问题

rt
因为懒，所以选了winserver当服务器系统
但是多数面板都不支持win（bt和xp可以）
1Panel以后会支持嘛
（或者我如何构建一个适用于win的1Panel呢）

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们暂时还没有发布 windows 面板的计划。
