### ISSUE TITLE
[BUG]备份wikijs出现错误

### ISSUE THREAD

**Issue by E8A281E6ACA2** [1Panel-dev/1Panel#838]
### 联系方式

lechunqiu@outlook.com

### 1Panel 版本

v1.1.3

### 问题描述

我想去备份wikijs时，提示：服务内部错误: stderr: tar: /opt/1panel/apps/js//: Cannot open: No such file or directory tar: Error is not recoverable: exiting now。

### 重现步骤

测试过很多次，都不行。

### 期待的正确结果

希望能进行备份。

### 相关日志输出

```shell
[2023-04-29 16:47:47] [DEBUG] tar zcvf /opt/1panel/backup/app/wikijs/wiki/wiki_20230429164747/app.tar.gz  -C /opt/1panel/apps/js// wiki  
[2023-04-29 16:47:47] [ERROR] do handle tar failed, stdout: stderr: tar: /opt/1panel/apps/js//: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
, err: exit status 2  
[2023-04-29 16:49:01] [DEBUG] tar zcvf /opt/1panel/backup/app/wikijs/wiki/wiki_20230429164901/app.tar.gz  -C /opt/1panel/apps/js// wiki  
[2023-04-29 16:49:01] [ERROR] do handle tar failed, stdout: stderr: tar: /opt/1panel/apps/js//: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
, err: exit status 2
```

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。看报错原因是因为没有正确获取到应用名称，麻烦提供一下创建 Wiki.js 时输入的应用名称。

**Comment by E8A281E6ACA2** [comment]
![image](https://user-images.githubusercontent.com/57286240/235309460-22a7455d-bba9-49cc-95ea-ee94f5f9a5e3.png)
![image](https://user-images.githubusercontent.com/57286240/235309503-7f293fa8-408b-467a-af3f-52edf0d01f14.png)

**Comment by wanghe-fit2cloud** [comment]
我刚刚在本地环境没有复现上述问题，请问你安装部署 1Panel 的服务器是什么操作系统：
```shell
cat /etc/os-release
```

**Comment by E8A281E6ACA2** [comment]
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
我刚测试了一下，依然报错。
服务内部错误: stderr: tar: /opt/1panel/apps/js//: Cannot open: No such file or directory tar: Error is not recoverable: exiting now

**Comment by wanghe-fit2cloud** [comment]
收到，我们后续会基于 CentOS Stream 9 操作系统做一下兼容性测试。

**Comment by wanghe-fit2cloud** [comment]
麻烦将 1Panel 升级到 v1.3.0 版本，查看一下是否还存在上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.3.1 版本已发布。
