### ISSUE TITLE
[FEATURE]希望能够支持arm设备：n1 玩客云这些

### ISSUE THREAD

**Issue by pkqpkqpkqwww** [1Panel-dev/1Panel#839]
### 1Panel 版本

暂无

### 请描述您的需求或者改进建议

希望能够支持arm设备：n1 玩客云这些

**Comment by zhengkunwang223** [comment]
您好，arm系列已经支持arm64，其他的arm版本正在陆续支持中

**Comment by Muska-Ami** [comment]
#762

**Comment by DreamConnected** [comment]
我尝试编译了一个，但是还没做arm32位的应用商店支持，这意味着你可能无法使用面板核心功能。
https://github.com/DreamConnected/1Panel-armhf

**Comment by DreamConnected** [comment]
我构建了一个，但手上没有arm32设备，还没测试过。
https://github.com/DreamConnected/1Panel-armhf

**Comment by wanghe-fit2cloud** [comment]
@pkqpkqpkqwww 
麻烦进微信交流群，添加一下我好友。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布，新增支持 armv7l、s390x 和 ppc64le 三种架构。
