### ISSUE TITLE
[QUESTION]MySQL数据库迁移到新机器

### ISSUE THREAD

**Issue by backunderstar** [1Panel-dev/1Panel#840]
### 请描述您的问题

![image](https://user-images.githubusercontent.com/89375248/235356410-208d832b-9722-4356-8bf2-cc1cede3354a.png)
![联想截图_20230430215354](https://user-images.githubusercontent.com/89375248/235356907-b0eb22a6-5bf6-4376-97f6-a7e12b641165.png)

开发者您好，我在使用1panel过程中，想要将MySQL数据进行迁移，我通过直接面板上导出备份，再在另外一台装有1panel服务器上通过面板导入，发生上述报错，显示不匹配。
在此想咨询这种迁移是否可行，（我是外行-_-）
如果不行，我该怎样进行数据迁移，是否是将./1panel/apps/mysql/MySQL/data目录下数据全部移到新服务器上。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们近期会在开发测试环境复现一下该问题。

**Comment by wanghe-fit2cloud** [comment]
可以将 1Panel 升级到最新版本。

但是有两点需要注意：
1、确保 MySQL 应用版本一致，5.7 和 8.0 备份文件不支持混用恢复
2、在新的 1Panel 面板中，创建的 MySQL 应用名称要和备份的 MySQL 应用名称保持一致。
