### ISSUE TITLE
[FEATURE]增加一个离线模式，同宝塔面板

### ISSUE THREAD

**Issue by 357341051** [1Panel-dev/1Panel#841]
### 1Panel 版本

v1.1.3

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/118408640/235358984-16fbf383-c353-4ccc-af84-c64f90e14032.png)
增加一个离线模式，同宝塔面板

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑上述需求。

**Comment by wanghe-fit2cloud** [comment]
暂无计划支持离线模式，望理解。
