### ISSUE TITLE
Wiki.js 不支持部署其他数据库

### ISSUE THREAD

**Issue by E8A281E6ACA2** [1Panel-dev/1Panel#843]
### 1Panel 版本

v1.1.3

### 请描述您的需求或者改进建议

在安装wiki.js的时候，只能选择MySQL，其实是可以选择其他数据库的，因为wiki明确提出未来只使用postgressql数据库。

### 请描述你建议的实现方案

增加对postgres的支持。

### 附加信息

![image](https://user-images.githubusercontent.com/57286240/235409091-317d7b6e-e6b8-4ef4-b5f7-2cbf5db3fdb5.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持该需求。

**Comment by Q2297045667** [comment]
赞成

**Comment by zyyfit** [comment]
希望 Umami 也支持 PostgreSQL 数据库。

**Comment by wanghe-fit2cloud** [comment]
Typecho 也需要支持 PostgreSQL 数据库。

**Comment by wanghe-fit2cloud** [comment]
v1.9.5 版本已发布。
