### ISSUE TITLE
[FEATURE]一些小的建议

### ISSUE THREAD

**Issue by LongC-CN** [1Panel-dev/1Panel#844]
### 1Panel 版本

v1.1.3

### 请描述您的需求或者改进建议

1.面板没套SSL是不是有些不安全
2.是不是要加一些隐藏面板的措施防止被扫到
3.ssh的管理，比如更改端口，开启密钥登入，登入日志
4.docker普通的容器直接更改启动参数
5.备份账户支持webdav（可以的话能不能顺便支持onedrive，Googledrive等）

### 请描述你建议的实现方案

之前用宝塔的，可以学习宝塔

### 附加信息

我的这些建议可能不是很重要的，我只是一个高中生，对网站建设不是太懂，主要是为了搭建一些小工具，还请多多包涵，如有错误欢迎指出

**Comment by LongC-CN** [comment]
前3个好像别人已经发过了，抱歉没看到

**Comment by Muska-Ami** [comment]
ssl这个+1

**Comment by wanghe-fit2cloud** [comment]
> ssl这个+1

v1.2.0 版本会支持开启面板 SSL。

**Comment by heyzqq** [comment]
> > ssl这个+1
> 
> v1.2.0 版本会支持开启面板 SSL。

现在我是直接在 OpenResty 添加 https 代理到面板，然后关掉面板的端口，是否可以呢？

**Comment by wanghe-fit2cloud** [comment]
> > > ssl这个+1
> > 
> > 
> > v1.2.0 版本会支持开启面板 SSL。
> 
> 现在我是直接在 OpenResty 添加 https 代理到面板，然后关掉面板的端口，是否可以呢？

这种实现方式也是可以的。

**Comment by wanghe-fit2cloud** [comment]
建议将 1Panel 升级到最新版本，体验全新新增功能。
