### ISSUE TITLE
应该可以有直接进入容器目录按钮

### ISSUE THREAD

**Issue by E8A281E6ACA2** [1Panel-dev/1Panel#845]
### 1Panel 版本

v1.1.3

### 请描述您的需求或者改进建议

希望有直接进入某个容器的按钮，不然每次去找某个目录真的很麻烦呀。
![image](https://user-images.githubusercontent.com/57286240/235451920-9f83399d-f2db-4b9d-8f7d-2e55b3ee5fdf.png)

### 请描述你建议的实现方案

能直接进入容器目录按钮。

### 附加信息

![image](https://user-images.githubusercontent.com/57286240/235451961-539f2970-2e68-4583-b337-e02d66e9a762.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持容器文件浏览器功能。

**Comment by wanghe-fit2cloud** [comment]
#523
