### ISSUE TITLE
[QUESTION]同时网站状态全部停止

### ISSUE THREAD

**Issue by backunderstar** [1Panel-dev/1Panel#846]
### 请描述您的问题

经历过两次，好像都是晚上凌晨这样子，不知道是OpenResty的自动设置，还是不知道的错误。
没有找到任何报错。

某个时间，这次好像是0点整，网站状态全部显示**已停止**，并且确实无法访问。
查看OpenResty日志没有报错，但是发现日志时间不对，不知道是不是容器时区不对导致，容器里是16:00，但是应该是00:00.

总结问题：
* OpenResty容器时区问题？
* 网站突然全部自动关停。

**Comment by zhengkunwang223** [comment]
您好，感谢反馈，可能是因为获取不到本机时区导致网站过期判断失败，我们后面版本修复这个问题

**Comment by backunderstar** [comment]
![image](https://user-images.githubusercontent.com/89375248/235721731-ed6b111c-8d9e-4a5f-95c7-1c71f8b73b61.png)
现在可以确定是时区问题导致的，设置了7月底证书失效的网站呗关停，永久的没事。也是零点整的时候。
不急，能用，仅来此说明下我所了解的情况。

**Comment by zhengkunwang223** [comment]
> ![image](https://user-images.githubusercontent.com/89375248/235721731-ed6b111c-8d9e-4a5f-95c7-1c71f8b73b61.png)
> 
> 现在可以确定是时区问题导致的，设置了7月底证书失效的网站呗关停，永久的没事。也是零点整的时候。
> 
> 不急，能用，仅来此说明下我所了解的情况。

这个过期时间是网站的过期时间，不是证书的有效期，网站过期时间到了会关闭网站，用户访问网站会出现网站已停止页面

**Comment by backunderstar** [comment]
原来如此😂

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
