### ISSUE TITLE
需要支持微软OneDrive的应用

### ISSUE THREAD

**Issue by E8A281E6ACA2** [1Panel-dev/1Panel#847]
### 1Panel 版本

v1.1.3

### 请描述您的需求或者改进建议

希望增加微软OneDrive应用，有时候备份什么的，用微软OneDrive老方便了。

### 请描述你建议的实现方案

增加微软OneDrive应用。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持在备份账号中开启 OneDrive。

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
