### ISSUE TITLE
[FEATURE]考虑支持非容器模式?

### ISSUE THREAD

**Issue by Muska-Ami** [1Panel-dev/1Panel#850]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

由于系统内核原因，我的设备目前无法运行docker，但1P全部都是容器化的，是否考虑无容器部署?

**Comment by maninhill** [comment]
中短期内我们会聚焦容器化，这样产品架构和实现能够保持一致性。
望理解。
