### ISSUE TITLE
希望增加文件目录收藏夹功能

### ISSUE THREAD

**Issue by youyou-sudo** [1Panel-dev/1Panel#852]
### 1Panel 版本

v1.1.3

### 请描述您的需求或者改进建议

有时候想要快速目录
1panel需要自己记录文件夹路径输入
如果增加个文件夹路径收藏功能会很方便

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本支持文件收藏夹功能。

**Comment by wanghe-fit2cloud** [comment]
重复 #492
