### ISSUE TITLE
希望添加证书列表显示域名

### ISSUE THREAD

**Issue by youyou-sudo** [1Panel-dev/1Panel#853]
### 1Panel 版本

v1.1.3

### 请描述您的需求或者改进建议

用的cloudflare创建证书，有的时候用的通配符
导入后在证书页面发现无法显示证书是哪个域名
![Screenshot_20230504074654](https://user-images.githubusercontent.com/60727068/236074744-bfba7df8-c141-4b16-a645-07bbbdb4924c.jpg)
这导致在创建网站选择本地证书时全部显示一样的名字，选证书完全是在碰运气
![Screenshot_20230504075000](https://user-images.githubusercontent.com/60727068/236075278-cb9d20d6-1379-41e2-ac31-e327c0990754.jpg)

### 请描述你建议的实现方案

可以像BT一样识别证书是哪个域或者给证书添加命名或备注功能

**Comment by zhengkunwang223** [comment]
感谢建议，这个我们在后续版本优化一下

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
