### ISSUE TITLE
[FEATURE] 希望增加cloudflare 的DDNS 功能

### ISSUE THREAD

**Issue by Jengro777** [1Panel-dev/1Panel#859]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

目前ipv6 的动态地址基本都有分配，DDNS功能对一些内部系统 测试https 很有用

参考：https://github.com/jeessy2/ddns-go/

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们初步了解了一下这个项目，是不是可以将其添加到[应用商店](https://github.com/1Panel-dev/appstore)中来管理。

**Comment by cyril-cheng** [comment]
这个项目很好用，我也一直在用

**Comment by Mrered** [comment]
目前我手动用docker安装ddns-go使用的，希望官方尽快支持一下！感谢！

**Comment by wanghe-fit2cloud** [comment]
收到，感谢大家的建议，我们会在近期要发布的版本中支持。

**Comment by Jengro777** [comment]
> 收到，感谢大家的建议，我们会在近期要发布的版本中支持。

如果不是应用商店安装，而是1panel 直接集成 可能会更好

**Comment by wanghe-fit2cloud** [comment]
应用商店中已经支持 [ddns-go](https://github.com/jeessy2/ddns-go/)
> 经讨论，1Panel 暂不支持在系统中增加上述功能。
