### ISSUE TITLE
[FEATURE] 主机端口占用详情查看以及强制kill的功能

### ISSUE THREAD

**Issue by Jengro777** [1Panel-dev/1Panel#862]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

很多时候查看哪个应用占有的端口，在终端还是有些不方便，如果可以增加类似的功能 会更好

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本我们会支持任务管理功能。

**Comment by wanghe-fit2cloud** [comment]
最新版本已经支持上述功能，`主机` - `进程管理` 菜单。
