### ISSUE TITLE
[FEATURE] 容器增加 ports 等展示字段 

### ISSUE THREAD

**Issue by Jengro777** [1Panel-dev/1Panel#864]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/35259040/236154390-718f2dc3-2fca-485f-aa47-bc236a9e0439.png)
1panel 容器列表展示字段太少，建议增加如下图的字段（已经有的字段可以忽略）

### 请描述你建议的实现方案

![image](https://user-images.githubusercontent.com/35259040/236154319-8e83f6f6-dc13-45aa-83ef-eecc62e141b0.png)
参考此图

**Comment by wanghe-fit2cloud** [comment]
下个版本就会支持。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
