### ISSUE TITLE
支持选择连接数据库

### ISSUE THREAD

**Issue by lxsclnb6** [1Panel-dev/1Panel#865]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

能不能更新支持在安装博客程序的时候可以选择连接某个sql数据库，而不是直接在网站目录生成一个.db文件

**Comment by zhengkunwang223** [comment]
请问是 PHP 运行环境安装 应用吗？

**Comment by lxsclnb6** [comment]
是的

**Comment by zhengkunwang223** [comment]
暂不支持选择数据库
