### ISSUE TITLE
[FEATURE] 希望应用商店的wordpress默认有中文语言包

### ISSUE THREAD

**Issue by Star-tears** [1Panel-dev/1Panel#868]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

希望应用商店的wordpress默认有中文语言包，安装后默认英文且无中文语言包，无法切换中文。

**Comment by zhengkunwang223** [comment]
好的，后续增加中文支持

**Comment by zhengkunwang223** [comment]
> ### 1Panel 版本
> 1.1.3
> 
> ### 请描述您的需求或者改进建议
> 希望应用商店的wordpress默认有中文语言包，安装后默认英文且无中文语言包，无法切换中文。
> 
> ### 请描述你建议的实现方案
> _No response_
> 
> ### 附加信息
> _No response_

您好当前版本的 wordpress 6.2.0 已经支持中文，安装的时候选择简体中文即可。  
如果安装的时候选择的是英文，可以在 Settings -> General -> Site Language 处修改为简体中文

**Comment by Star-tears** [comment]
我不知道是我哪里操作有误，可我当前用应用商店的wordpress 6.20版本，启动后初始安装是跳过选择语言的阶段的，在Settings -> General 里也没有Site Language选项
