### ISSUE TITLE
[FEATURE]安装不支持rocky linux9

### ISSUE THREAD

**Issue by king1037** [1Panel-dev/1Panel#885]
### 1Panel 版本

安装不支持rocky linux9

### 请描述您的需求或者改进建议

安装不支持rocky linux9

**Comment by wanghe-fit2cloud** [comment]
是因为 Docker 在线安装脚本不支持该操作系统。在安装 1Panel 之前，可以先手动安装 Docker。

**Comment by wanghe-fit2cloud** [comment]
可以使用以下脚本一键安装 Docker：
```shell
bash <(curl -sSL https://linuxmirrors.cn/docker.sh)
```
