### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by muakeke** [1Panel-dev/1Panel#886]
### 请描述您的问题

![屏幕截图(14)](https://user-images.githubusercontent.com/114546312/236525589-1550eca4-c24c-4b38-8650-c32b8e4f6290.png)
这个是什么原因导致的？

**Comment by wanghe-fit2cloud** [comment]
用户权限问题导致的安装 Docker 失败。你可以切换到 root 用户来安装或者给 baixiong-biu 用户 sudo 权限。
