### ISSUE TITLE
创建数据库时，如果存在用户名重复无法创建，并且没有提示信息 [BUG]

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#888]
### 1Panel 版本

v1.1.3

### 问题描述

创建数据库时，如果存在用户名重复无法创建，并且没有提示信息，日志里面也没有相关内容
![image](https://user-images.githubusercontent.com/30285739/236593256-ffbe62cc-e526-45df-b8d9-e405a5eeaf17.png)

### 重现步骤

1. 创建数据库
2. 创建新的数据库以及重名用户

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下个版本中修复该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
