### ISSUE TITLE
ERROR: Unsupported distribution 'anolis'

### ISSUE THREAD

**Issue by wwtao1024** [1Panel-dev/1Panel#889]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

ERROR: Unsupported distribution 'anolis'
支持下阿里的龙蜥操作系统

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述问题是因为 Docker 在线安装脚本不支持 anolis 操作系统导致的。
可参考阿里云开发者社区提供的 [安装教程](https://developer.aliyun.com/article/838405)

**Comment by wwtao1024** [comment]
我是7.9的 不是8的

**Comment by wanghe-fit2cloud** [comment]
> 我是7.9的 不是8的

针对安装 Docker 来说，教程应该是一样的。
