### ISSUE TITLE
[FEATURE]php项目的终端可以默认cd到项目的目录吗？

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#893]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

php项目的终端可以默认cd到该项目的目录吗？现在是默认到最上层的www目录
每次进终端还是得cd sites/项目/index，经常会忘记cd

**Comment by zhengkunwang223** [comment]
是从 php 容器的终端进入吗？

**Comment by Felmon** [comment]
> 是从 php 容器的终端进入吗？

是呀

**Comment by zhengkunwang223** [comment]
> > 是从 php 容器的终端进入吗？
> 
> 是呀

网站目录已经从容器中挂载到宿主机 所以现在从网站设置-网站目录页面可以直接进入

**Comment by Felmon** [comment]
> > > 是从 php 容器的终端进入吗？
> > 
> > 
> > 是呀
> 
> 网站目录已经从容器中挂载到宿主机 所以现在从网站设置-网站目录页面可以直接进入

我是要在网站目录执行命令
比如flarum安装拓展都是得在网站目录执行composer require *的，为什么php终端的目录不是网站目录而是www目录呢

**Comment by zhengkunwang223** [comment]
> > > > 是从 php 容器的终端进入吗？
> 
> > > 
> 
> > > 
> 
> > > 是呀
> 
> > 
> 
> > 网站目录已经从容器中挂载到宿主机 所以现在从网站设置-网站目录页面可以直接进入
> 
> 
> 
> 我是要在网站目录执行命令
> 
> 比如flarum安装拓展都是得在网站目录执行composer require *的，为什么php终端的目录不是网站目录而是www目录呢

为了以后兼容多网站共用一个php容器

**Comment by Felmon** [comment]
> > > > > 是从 php 容器的终端进入吗？
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 是呀
> > 
> > 
> > > 
> > 
> > 
> > > 网站目录已经从容器中挂载到宿主机 所以现在从网站设置-网站目录页面可以直接进入
> > 
> > 
> > 我是要在网站目录执行命令
> > 比如flarum安装拓展都是得在网站目录执行composer require *的，为什么php终端的目录不是网站目录而是www目录呢
> 
> 为了以后兼容多网站共用一个php容器

我记得你们在群里说过一个站点一个php容器呀，多网站共用一个php现在还没出现吧，要是可以实现多网站一个php是最好了，那样的话站点是不是就可以随意切换php版本了
