### ISSUE TITLE
在定时任务中无法输出结果

### ISSUE THREAD

**Issue by E8A281E6ACA2** [1Panel-dev/1Panel#897]
### 联系方式

lechunqiu@outlook.com

### 1Panel 版本

v1.1.3

### 问题描述

我写了一个访问网站统计平均时间的bash，但是在计划任务中无法输出结果。在控制台上可以。
![image](https://user-images.githubusercontent.com/57286240/236608144-4a11e259-a5a7-4d5b-aa30-d6ca82a20714.png)
![image](https://user-images.githubusercontent.com/57286240/236608160-27c8d4d4-9293-4790-9ecf-b8fbea6b4957.png)

### 重现步骤

![image](https://user-images.githubusercontent.com/57286240/236608140-a4a1c43a-8133-49d4-9da9-80e0475426d7.png)

### 期待的正确结果

希望能看到结果吧。

**Comment by ssongliu** [comment]
感谢反馈，我们在开发测试环境复现一下，方便提供一下脚本内容吗？
