### ISSUE TITLE
[BUG]伪静态 location / {}重复的问题

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#903]
### 1Panel 版本

1.1.3

### 问题描述

伪静态一般有location /{} ，但是创建网站时有些也会在nginx配置里生成包含 / 的部分，这样导致伪静态的配置保存不了，提示已存在location /
不会正则所以不知道在哪里包含了/

### 重现步骤

1

**Comment by zhengkunwang223** [comment]
可以在网站-配置文件中查看 是否有重复的 location
