### ISSUE TITLE
计划任务在task下找不到创建的任务（有些找不到）

### ISSUE THREAD

**Issue by E8A281E6ACA2** [1Panel-dev/1Panel#907]
### 联系方式

lechunqiu@outlook.com

### 1Panel 版本

v1.1.3

### 问题描述

在创建计划任务后，无法在task目录下查看创建的，只有个别的可以看到。

### 重现步骤

如下附件

### 期待的正确结果

希望能查看到创建的任务

### 附加信息

![image](https://user-images.githubusercontent.com/57286240/236613915-956ec799-f28c-4ad0-bcf4-7816f4fb5439.png)
![image](https://user-images.githubusercontent.com/57286240/236613926-57084b9f-1291-4725-a76d-24f46a41ae3e.png)
![image](https://user-images.githubusercontent.com/57286240/236613935-fa723ce6-f08e-47d8-99c1-daa63e03827e.png)
能看到第一个创建的任务
![image](https://user-images.githubusercontent.com/57286240/236613949-94f6f693-8d79-4d40-bc0f-4198d3ce8a6a.png)
![image](https://user-images.githubusercontent.com/57286240/236613978-edf213a7-6577-442b-9f9d-ebede1819f1c.png)
上面这个应该是我没有删除。

**Comment by ssongliu** [comment]
感谢反馈，该问题将在下个版本解决

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
