### ISSUE TITLE
[FEATURE]首页显示的磁盘状态太多了

### ISSUE THREAD

**Issue by MXyaobukeji** [1Panel-dev/1Panel#911]
### 1Panel 版本

v1.1.3

### 请描述您的需求或者改进建议

首页显示的文件夹状态太多了

**Comment by wanghe-fit2cloud** [comment]
请问您反馈的首页文件夹是指状态栏的磁盘数量吗？

**Comment by MXyaobukeji** [comment]
是的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1Panel-dev/1Panel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月6日(星期六) 晚上7:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [1Panel-dev/1Panel] [FEATURE] (Issue #911)





 
请问您反馈的首页文件夹是指状态栏的磁盘数量吗？

**Comment by wanghe-fit2cloud** [comment]
这个问题我们会在下个版本优化。

**Comment by wanghe-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/46734380/236625522-4c5faa33-dfac-4d0d-b40e-bc6dc00b69c5.png)

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
