### ISSUE TITLE
[QUESTION]创建网站[运行环境]服务内部错误: Error response from daemon

### ISSUE THREAD

**Issue by gitzaai** [1Panel-dev/1Panel#912]
### 请描述您的问题

通过创建网站[运行环境]，想迁移wordpress过来，发现了在docker-compose[编排]下该容器无法使用终端：

![Image description](https://r2img.gitzaai.com/memos/assets/2023/05/1683389753_Snipaste_2023-05-06_23-46-39.jpg)

服务内部错误: Error response from daemon: driver failed programming external connectivity on endpoint 1Panel-php-YRPW (d2b72cc3a38e4a93baef5bde4e434bde0330ce9cbddc4f227c356147957a779b): Error starting userland proxy: listen tcp4 127.0.0.1:9001: bind: cannot assign requested address

附上docker ps 情况
![Image description](https://r2img.gitzaai.com/memos/assets/2023/05/1683389757_Snipaste_2023-05-07_00-15-17.jpg)

使用环境：
Debian11
1panel版本：v1.1.3

**Comment by wanghe-fit2cloud** [comment]
看截图中报错应该是自定义链 DOCKER 被清除导致的，手动重启 Docker 试一下。
```shell
systemctl restart docker
```

**Comment by gitzaai** [comment]
> 看截图中报错应该是自定义链 DOCKER 被清除导致的，手动重启 Docker 试一下。
> 
> ```shell
> systemctl restart docker
> ```

重启了服务器，正常了
