### ISSUE TITLE
[BUG] 容器监控 网络和磁盘监控错误 

### ISSUE THREAD

**Issue by muaimingjun** [1Panel-dev/1Panel#913]
### 联系方式

2667004988@qq.com

### 1Panel 版本

1.1.3

## 磁盘和网络都没有这么高，显示错误了
![image](https://user-images.githubusercontent.com/35066516/236650439-af1a2c6f-c429-476c-bf93-7e0ee86ab12e.png)

### 重现步骤

就在容器监控那个地方

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，1Panel 使用的是 Docker 官方的 SDK 获取到的数据，与命令行中执行 docker stats 显示输入保持一致。
