### ISSUE TITLE
[FEATURE] 建议安装应用时，增加自定义数据库地址

### ISSUE THREAD

**Issue by ymslucky** [1Panel-dev/1Panel#914]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

设备环境：Debian-11.6

现状：想要安装 Gitea ，必须在本地主机的 1Panel 中安装 MySQL 

需求：我希望在安装应用 Gitea 时，能够选择另一台主机的 MySQL 作为数据库

问题：
1、无法在本地 1Panel 未安装 MySQL 时，安装 Gitea （或其他需要 MySQL 的程序）
2、我先在 1Panel 安装 MySQL，再安装 Gitea，最后在 Gitea 的安装界面改变数据库地址为其他主机。这时，我无法停止/删除本地安装的 MySQL，我在日志中发现 Gitea 容器会对 MySQL 作校验（Ping）

### 请描述你建议的实现方案

建议安装应用时，增加自定义数据库地址

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本可能会考虑支持外部、远程数据库。

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
