### ISSUE TITLE
[BUG]登录ip的地址的地理位置与面板上显示的地址不一样

### ISSUE THREAD

**Issue by clover1420** [1Panel-dev/1Panel#915]
### 联系方式

748883120@qq.com

### 1Panel 版本

1.1.3

### 问题描述

登录ip的地址的地理位置与面板上显示的地址不一样

### 重现步骤

登录面板

### 附加信息

![image](https://user-images.githubusercontent.com/47273274/236685388-17d44543-dff0-40ce-a753-2c8615d79ad1.png)
![image](https://user-images.githubusercontent.com/47273274/236685415-dfbfb332-0531-4080-a834-1eeb58ed7af0.png)

**Comment by ssongliu** [comment]
感谢反馈！是因为我们的 ip 库很久没有更新了，这个问题会在这周发布的版本解决。

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
