### ISSUE TITLE
[QUESTION]安装的halo存在使用问题

### ISSUE THREAD

**Issue by 2949193550** [1Panel-dev/1Panel#916]
### 请描述您的问题

使用1.1.3面板安装halo，网站时不时就进不了，错误代码ERR_SSLPROTOCOL_ERROR，尝试过更换ssl，一样的问题，希望解决

**Comment by zhengkunwang223** [comment]
请问是 halo 什么版本？

**Comment by 2949193550** [comment]
> 

2.5.1

**Comment by zhengkunwang223** [comment]
> > 
> 
> 2.5.1

我们周四会更新 2.5.2 版本，可以更新之后再试一下

**Comment by wanghe-fit2cloud** [comment]
v1.2.0 版本已发布。
将 1Panel 升级到最新版本后，进入应用商店菜单，点击更新应用列表。

**Comment by 2949193550** [comment]
> v1.2.0 版本已发布。 将 1Panel 升级到最新版本后，进入应用商店菜单，点击更新应用列表。

已解决
