### ISSUE TITLE
[QUESTION]安装失败咨询

### ISSUE THREAD

**Issue by 2949193550** [1Panel-dev/1Panel#917]
### 请描述您的问题

![mmexport1683505635893](https://user-images.githubusercontent.com/63438310/236710431-bf9bf948-f6c8-484a-8ab6-4b1d5fdf5405.png)
出现如图失败，是我设备问题还是？

**Comment by 2949193550** [comment]
我之前安装过一次很正常，后面重装系统再次尝试安装却发现失败

**Comment by 2949193550** [comment]
@zhengkunwang223 请问这个是什么原因

**Comment by zhengkunwang223** [comment]
> @zhengkunwang223 请问这个是什么原因

网络原因或者操作系统原因

**Comment by ChrisVeon** [comment]
尝试在系统部署好之后先使用 `yum update` 命令更新，或者手动安装 docker 后再部署安装 1panel。
