### ISSUE TITLE
[FEATURE]两点小建议

### ISSUE THREAD

**Issue by 2949193550** [1Panel-dev/1Panel#918]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

1.建议在文件管理页面默认排序：
文件夹显示上方，文件夹紧跟其后，否则显示页面杂乱无章，不便操作
2.bug现象：
若压缩文件存在中文名文件，解压后无法删除，会出现报错情况，只能删除夫文件，请修复谢谢

**Comment by zhengkunwang223** [comment]
1. 这个没明白
2. 中文这个我们测试过，没出问题 请提供一下你的截图

**Comment by Felmon** [comment]
> 1. 这个没明白
> 2. 中文这个我们测试过，没出问题 请提供一下你的截图

1 正常文件管理的排序是 文件夹在前面  文件在后面 ，点击时间或者大小排序时，也是文件夹和文件单独排序。现在是文件夹和文件都混一起按字母排序了
2 没试过就不帮忙解答了

**Comment by zhengkunwang223** [comment]
> > 1. 这个没明白
> > 2. 中文这个我们测试过，没出问题 请提供一下你的截图
> 
> 1 正常文件管理的排序是 文件夹在前面 文件在后面 ，点击时间或者大小排序时，也是文件夹和文件单独排序。现在是文件夹和文件都混一起按字母排序了 2 没试过就不帮忙解答了

好的明白了 我们优化一下排序

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
