### ISSUE TITLE
[FEATURE] 将面板申请的证书自动上传至cdn上

### ISSUE THREAD

**Issue by vlssu** [1Panel-dev/1Panel#920]
### 1Panel 版本

1.1.3

### 请描述您的需求或者改进建议

像宝塔面板上的 cdn一样，可以自动上传部署在服务器上的ssl证书，虽然他们是手动点一下上传，如果可以，在服务器续期时最好自动上传
![image](https://user-images.githubusercontent.com/43847794/236661667-9a86e905-ec2e-4035-a7e3-c5c7e1316038.png)

### 请描述你建议的实现方案

![image](https://user-images.githubusercontent.com/43847794/236721487-ccf5f3eb-2d12-4934-8467-e5718d065127.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持上述需求。

**Comment by cyril-cheng** [comment]
已知目前cloudflare是全自动上传网站证书，其他cdn不清楚

**Comment by vlssu** [comment]
我想自动上传腾讯云cdn的，而且域名解析账户与cdn账户不是同一个。

**Comment by swift-fs** [comment]
同样有这个需求，无奈现在自己写的脚本跑的

**Comment by ChishFoxcat** [comment]
其实这个可以提上日程了，各大国内云服务商都降低了免费证书的时长，很希望服务器（本地）证书能上传到各云服务商的

**Comment by wanghe-fit2cloud** [comment]
v1.10.12-beta 版本已经支持在申请证书后执行脚本的功能。要升级到 beta 版本，需进入【面板设置】页面，启用【预览体验计划】。如图所示：
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/d4f4260f-dc70-4cc9-bf49-bf93dd087ddf">

<img width="1475" alt="image" src="https://github.com/user-attachments/assets/c7ea7ccc-06e7-47a7-988d-3f854c1f5bb7">
