### ISSUE TITLE
[FEATURE]建议官方支持1panel在PhotonOS系统（验证安装流程）

### ISSUE THREAD

**Issue by betgar** [1Panel-dev/1Panel#923]
### 1Panel 版本

v1.1.3

### 请描述您的需求或者改进建议

PhotonOS官方使用tdnf来代替yum工具和dnf工具，目前使用CenOS的安装脚本，v1.1.3版本可以正常的安装和使用。
建议官方以后支持PhotonOS这个系统，而且PhotonOS定位就是docker宿主系统，已经内置安装了docker。而且PhotonOS是vmware开发构建的，使用vmware相关虚拟化产品运行时，有资源优化的优势。

### 附加信息

https://github.com/vmware/photon

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中考虑支持 PhotonOS系统。

**Comment by wanghe-fit2cloud** [comment]
近期还没有精力完成上述操作系统的适配，望理解。

**Comment by ljq29** [comment]
在photon上安装1panel成功，但是部署docker时候如果使用了环境变量env，总会提示环境变量未定义。

**Comment by wanghe-fit2cloud** [comment]
> 在photon上安装1panel成功，但是部署docker时候如果使用了环境变量env，总会提示环境变量未定义。

可以尝试手动升级一下 docker 和 docker-compose 版本，看是否是这里的问题。
