### ISSUE TITLE
[FEATURE]建议增加账号权限管理

### ISSUE THREAD

**Issue by Neil-Zhou** [1Panel-dev/1Panel#924]
### 1Panel 版本

1.3

### 请描述您的需求或者改进建议

建议增加账号管理、权限管理；
这样可以将运维管理开放给开发，他们只需要关注服务器目录和容器监控，其他功能由运维管理员来管理。

**Comment by q127981** [comment]
支持 这个功能很方便好用

**Comment by zhengkunwang223** [comment]
1Panel 目前专注于单用户单主机的场景 暂不考虑多账号管理功能
