### ISSUE TITLE
容器进程管理 [FEATURE]

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#927]
### 1Panel 版本

v1.1.3

### 请描述您的需求或者改进建议

希望能够支持容器进程管理，docker top <containerID> 能够查看到。

### 请描述你建议的实现方案

可以把监控内容搞到一个详情页面里面去，现在这种抽屉样式，看得不全，然后把容器进程列表放到一起可能会好一些

### 附加信息

![image](https://user-images.githubusercontent.com/30285739/236758566-ee950b40-4f2c-487f-94d5-31c76e968f02.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持该需求。
