### ISSUE TITLE
两步验证能否支持设置有效时间[FEATURE]

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#928]
### 1Panel 版本

v1.1.3

### 请描述您的需求或者改进建议

现在的两步验证应该是默认的 30 秒，mfa 是基于时间来生成和校验 code 的，在服务器时间出现一些偏差时，很有可能导致验证一直无法通过，建议增加自定义有效时长。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中优化有效时长。

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
