### ISSUE TITLE
概览、监控等界面建议增加单位转换 [FEATURE]

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#929]
### 1Panel 版本

v1.1.3

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/30285739/236760754-8db4c91c-5ace-4b79-b8c1-e55062326977.png)
如图，0.04 KB/s 单位可以直接转换成 B/s

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中持续优化。
