### ISSUE TITLE
[BUG]页面操作会导致MYSQL连接数增加

### ISSUE THREAD

**Issue by huyulong1993** [1Panel-dev/1Panel#934]
### 联系方式

1Panel交流群5-Einstein-huyulong1993@gmail.com

### 1Panel 版本

v1.1.3

### 问题描述

mysql连接数激增

### 重现步骤

页面：数据库-mysql-设置-当前状态
操作：
1、点击“设置”按钮
现象：
1、页面主体内容刷新；
2、页面中数据库连接数等关键指标增长，且不会下降；

每次点击都会触发

### 期待的正确结果

添加刷新状态按钮，或机制可以刷新状态并且不会新增数据库链接，以便监测。

### 附加信息

![image](https://user-images.githubusercontent.com/30071728/236784068-172e9f1a-c647-4ba0-8d8e-cc52edbb9911.png)

**Comment by ssongliu** [comment]
感谢反馈！我们这里使用的是总连接数 Connections，包括已经关闭的连接数和当前正在打开的连接数，所以他的数量会不断的增加。

我们下个版本考虑替换成或者新增一个当前连接数的状态。
