### ISSUE TITLE
[BUG]域名暂停或者移除后无法重新创建该域名

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#935]
### 1Panel 版本

1.1.3

### 问题描述

1 建了站点a.com/*.a.com（项目a）后，暂停这个网站后，无法使用域名a.com创建新站点
![image](https://user-images.githubusercontent.com/19621032/236793458-49e76a3c-d958-4b87-85c8-8b8bcf8abf8a.png)

2 在项目a里删除a.com域名，依旧无法使用域名a.com创建新站点
![image](https://user-images.githubusercontent.com/19621032/236793531-8448f8c3-567a-4af8-b9c5-8207b074ae3f.png)

均提示域名已存在。

希望可以只要该域名未正在使用中（非运行中/域名未被移除）都能使用该域名正常创建网站。
涉及到更改一些内容后方便回调，总不能只能删除项目才能释放出域名来

### 重现步骤

1

**Comment by zhengkunwang223** [comment]
您好 网站的名称不能重复

**Comment by Felmon** [comment]
> 您好 网站的名称不能重复

代号没重复

**Comment by zhengkunwang223** [comment]
> > 您好 网站的名称不能重复
> 
> 代号没重复

不是代号 是网站名称

**Comment by Felmon** [comment]
> > > 您好 网站的名称不能重复
> > 
> > 
> > 代号没重复
> 
> 不是代号 是网站名称

网站名称就是域名？那网站名称是否支持修改呢？毕竟域名不一定是不变的，网站名称采用代号是不是合理一点

**Comment by zhengkunwang223** [comment]
> > > > 您好 网站的名称不能重复
> > > 
> > > 
> > > 代号没重复
> > 
> > 
> > 不是代号 是网站名称
> 
> 网站名称就是域名？那网站名称是否支持修改呢？毕竟域名不一定是不变的，网站名称采用代号是不是合理一点

网站名称现在改不了 后面加个优化吧

**Comment by zyyfit** [comment]
在1.7.0版本中，域名被删除后，可以进入 网站设置 - 基本 - 其他 页面，修改主域名，然后就可以再次使用这个域名创建了
域名没被删掉，只是网站停用的话，还是不可以创建

**Comment by wanghe-fit2cloud** [comment]
v1.7.0 版本已发布。
