### ISSUE TITLE
[FEATURE] 建议增加php函数禁用功能

### ISSUE THREAD

**Issue by michael152630** [1Panel-dev/1Panel#936]
### 1Panel 版本

v1.2.0

### 请描述您的需求或者改进建议

建议增加php函数禁用功能，向宝塔看齐。

### 请描述你建议的实现方案

参考宝塔面板

**Comment by zhengkunwang223** [comment]
感谢建议 下个版本增加php函数禁用功能

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
