### ISSUE TITLE
[FEATURE]夜间模式ui优化

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#938]
### 1Panel 版本

1.2.0

### 请描述您的需求或者改进建议

对比白天模式，夜间模式ui未适配

1 有些地方 黑色字体和黑色背景融为一体了，如二步验证
![1d2d40872c22557bede235b421ba036](https://user-images.githubusercontent.com/19621032/236802174-e50e753e-98e7-4202-b858-4b3858d8b8b4.png)
2 有些地方文档背景为白色，未适配，如应用的文档介绍
![6338e69bd2d8b58826d9516feed4ad0](https://user-images.githubusercontent.com/19621032/236802321-4ac0a77e-b7e3-490f-8bc4-bcd32dfa54bd.png)
3 有些地方的已启动和已暂停//可操作和不能操作的按钮ui 无区别，如容器的操作按钮，文件操作
![image](https://user-images.githubusercontent.com/19621032/236802739-240656e9-ed0f-492d-be27-fc36fa7c5a64.png)

以上各场景的举例非全部

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中优化夜间模式 UI。

**Comment by maninhill** [comment]
v1.2.1 已解决。
