### ISSUE TITLE
[BUG] 1.2.0 新添的反代功能似乎有问题

### ISSUE THREAD

**Issue by yfdoor** [1Panel-dev/1Panel#941]
### 1Panel 版本

1.2.0

### 问题描述

在我的静态站点中添加了一个反代，想把 halo 映射到 https://xxx.com/blog 下，设置如下：
![image](https://user-images.githubusercontent.com/32769281/236829039-e9c394df-6d1f-4f3c-8784-aba498472768.png)

其中 http://127.0.0.1:8080 为 docker 部署的 halo，可是访问 https://xxx.com/blog 却页面显示异常。控制台报错
```      
GET https://xxx.com/blog/ 404        
GET https://xxx.com/themes/theme-earth/assets/dist/style.css?v=1.1.1 net::ERR_ABORTED 404         
GET https://xxx.com/plugins/PluginSearchWidget/assets/static/search-widget.iife.js net::ERR_ABORTED 404      
GET https://xxx.com/themes/theme-earth/assets/dist/main.iife.js?v=1.1.1 net::ERR_ABORTED 404
Uncaught ReferenceError: main is not defined           
GET https://xxx.com/themes/theme-earth/assets/images/default-avatar.svg 404
GET https://xxx.com/themes/theme-earth/assets/images/default-background.png 404
```
![image](https://user-images.githubusercontent.com/32769281/236829541-e0abc05f-3fab-45f2-8aa8-c4fb79796b58.png)

### 重现步骤

如上

**Comment by zhengkunwang223** [comment]
halo 不支持反向代理用二级目录
https://github.com/halo-dev/halo/issues/1132
