### ISSUE TITLE
[BUG] docker 配置关闭 iptables 不生效

### ISSUE THREAD

**Issue by yfdoor** [1Panel-dev/1Panel#942]
### 1Panel 版本

1.2.0

### 问题描述

docker 配置界面中当选择关闭 iptables 时，点击保存并重启后，会提示 “请求失败”，且不能阻止 docker 映射端口的 ip 直接访问
![image](https://user-images.githubusercontent.com/32769281/236833949-f4c0aa01-aa5d-4e5a-80d8-7de2065be458.png)

![image](https://user-images.githubusercontent.com/32769281/236835526-00cdf629-60af-47db-aa9e-c8ad4e5b2999.png)

### 重现步骤

如上

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦提供一下 1Panel 系统日志，【面板日志】 - 【系统日志】。

**Comment by yfdoor** [comment]
> 感谢反馈，麻烦提供一下 1Panel 系统日志，【面板日志】 - 【系统日志】。

系统日志中没有体现
···
```
[2023-05-09 00:00:00] [INFO] The scheduled certificate update task is currently in progress ...  
[2023-05-09 00:00:00] [INFO] The scheduled certificate update task has completed  
[2023-05-09 00:00:00] [INFO] Website scheduled task in progress ...  
[2023-05-09 00:00:00] [INFO] Website scheduled task has completed  
[2023-05-09 02:30:00] [INFO] start to backup database 备份-数据库 to KODO  
[2023-05-09 02:30:00] [INFO] start to mysqldump | gzip > /opt/1panel/backup/database/mysql/MySQL/halo/db_halo_20230509023000.sql.gz.gzip  
[2023-05-09 02:30:03] [INFO] start to handle remove expired, retain copies: 7  
```
···

**Comment by wanghe-fit2cloud** [comment]
你安装 1Panel 使用的是什么操作系统?
我们在本地开发环境中没有复现该问题，操作系统分别为：CentOS 7.9 和 Ubuntu 20.04 。

还有，服务器安装的 Docker 是 1Panel 自动安装还是你手动安装的，版本是多少？

**Comment by yfdoor** [comment]
> 你安装 1Panel 使用的是什么操作系统? 我们在本地开发环境中没有复现该问题，操作系统分别为：CentOS 7.9 和 Ubuntu 20.04 。
> 
> 还有，服务器安装的 Docker 是 1Panel 自动安装还是你手动安装的，版本是多少？

ubuntu-22.04 ,docker 是手动安装的，这个bug 之前 1.* 的时候是没有的，后来不知道从那个版本开始就开始报错了，最近的 1.1.3 和 1.2.0 都出错，没问题的不太记得是那个版本了，肯定是 1.1.3 之前的

**Comment by wanghe-fit2cloud** [comment]
> > 你安装 1Panel 使用的是什么操作系统? 我们在本地开发环境中没有复现该问题，操作系统分别为：CentOS 7.9 和 Ubuntu 20.04 。
> > 还有，服务器安装的 Docker 是 1Panel 自动安装还是你手动安装的，版本是多少？
> 
> ubuntu-22.04 ,docker 是手动安装的，这个bug 之前 1.* 的时候是没有的，后来不知道从那个版本开始就开始报错了，最近的 1.1.3 和 1.2.0 都出错，没问题的不太记得是那个版本了，肯定是 1.1.3 之前的

我们本地复现一下这个问题。

**Comment by yfdoor** [comment]
> > > 你安装 1Panel 使用的是什么操作系统? 我们在本地开发环境中没有复现该问题，操作系统分别为：CentOS 7.9 和 Ubuntu 20.04 。
> > > 还有，服务器安装的 Docker 是 1Panel 自动安装还是你手动安装的，版本是多少？
> > 
> > 
> > ubuntu-22.04 ,docker 是手动安装的，这个bug 之前 1.* 的时候是没有的，后来不知道从那个版本开始就开始报错了，最近的 1.1.3 和 1.2.0 都出错，没问题的不太记得是那个版本了，肯定是 1.1.3 之前的
> 
> 我们本地复现一下这个问题。

这个不但会出错而且 采用 iptables：false的 方法可能会导致其他潜在问题，建议改用这中方案：https://github.com/chaifeng/ufw-docker
最近采用这个方法，比较不错

**Comment by wanghe-fit2cloud** [comment]
> > > > 你安装 1Panel 使用的是什么操作系统? 我们在本地开发环境中没有复现该问题，操作系统分别为：CentOS 7.9 和 Ubuntu 20.04 。
> > > > 还有，服务器安装的 Docker 是 1Panel 自动安装还是你手动安装的，版本是多少？
> > > 
> > > 
> > > ubuntu-22.04 ,docker 是手动安装的，这个bug 之前 1.* 的时候是没有的，后来不知道从那个版本开始就开始报错了，最近的 1.1.3 和 1.2.0 都出错，没问题的不太记得是那个版本了，肯定是 1.1.3 之前的
> > 
> > 
> > 我们本地复现一下这个问题。
> 
> 这个不但会出错而且 采用 iptables：false的 方法可能会导致其他潜在问题，建议改用这中方案：https://github.com/chaifeng/ufw-docker 最近采用这个方法，比较不错

感谢反馈。
