### ISSUE TITLE
[BUG]无法创建PHP运行环境

### ISSUE THREAD

**Issue by Hobr** [1Panel-dev/1Panel#943]
### 1Panel 版本

1.2.0

### 问题描述

如果不选择扩展, 直接安装的结果是![image](https://user-images.githubusercontent.com/13460388/236841670-0c60d883-dffd-404c-8ce9-360a9607d422.png)

如果选择扩展, 结果是![image](https://user-images.githubusercontent.com/13460388/236842070-25cdb3b9-1ba5-477a-92d1-6f823cc236a3.png)
应该是docker构建时内部的报错?

系统是今天下午重新安装的, 理论上系统不会有什么问题

系统: Ubuntu 22.04
内核: 5.15
Docker: 23.0.5

### 重现步骤

![image](https://user-images.githubusercontent.com/13460388/236841467-0d1f58a9-20f0-4072-9be4-31f9a2339800.png)

![image](https://user-images.githubusercontent.com/13460388/236842008-2d6750b6-fd9e-435b-8b82-4bbf53e710a7.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述报错原因应该是容器内访问外网不通导致的。

进入容器 - 配置页面，打开 iptables 开关，然后再重建 PHP 运行环境试一下。

**Comment by Hobr** [comment]
谢谢, 已解决
