### ISSUE TITLE
[FEATURE] 我想卸载怎么卸载它

### ISSUE THREAD

**Issue by muaimingjun** [1Panel-dev/1Panel#945]
### 1Panel 版本

1.1.4

### 请描述您的需求或者改进建议

我现在遇到 web 服务无法启动的情况，如何卸载重新安装呢？
![image](https://user-images.githubusercontent.com/35066516/236967123-6f0442eb-dfbd-4d0d-9c25-e56b48d1e3a3.png)

**Comment by zhengkunwang223** [comment]
应用商店-已安装-删除
