### ISSUE TITLE
[BUG]在 Oracle Linux 中安装程序在线安装 docker 报错

### ISSUE THREAD

**Issue by staoran** [1Panel-dev/1Panel#946]
### 联系方式

staoran@gmail.com

### 1Panel 版本

curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sh quick_start.sh

### 问题描述

在 Oracle Linux 中执行安装程序报错。提示 docker 不支持当前发行版。

### 重现步骤

操作系统信息：
NAME="Oracle Linux Server"
VERSION="8.7"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.7"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:7:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.7
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.7

### 期待的正确结果

更健壮更独立的安装程序，不被其他安装脚本影响，如果是强依赖，那只能是加强兼容性了。

### 相关日志输出

```shell
[1Panel Log]: ======================= 开始安装 ======================= 
设置 1Panel 安装目录（默认为/opt）：
[1Panel Log]: 您选择的安装路径为 /opt 
[1Panel Log]: ... 在线安装 docker 
# Executing docker install script, commit: a8a6b338bdfedd7ddefb96fe3e7fe7d4036d945a

ERROR: Unsupported distribution 'ol'

[1Panel Log]: ... 启动 docker 
Failed to enable unit: Unit file docker.service does not exist.
Failed to start docker.service: Unit docker.service not found.
[1Panel Log]: docker 安装失败
```

### 附加信息

以下是 Chat GPT 的回答：
问：安装docker报错：ERROR: Unsupported distribution 'ol'

答：这个错误是因为 Docker 不支持您当前的 Linux 发行版。通常 Docker 只支持特定的 Linux 发行版和版本，因此请确保您的 Linux 发行版与 Docker 兼容。

如果您使用的是 Oracle Linux 发行版，请尝试使用以下命令来添加 Docker 的存储库：

```
sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
```

如果您使用的是其他 Linux 发行版，请查看 Docker 官方文档以获取适当的安装说明。

另外，您还可以考虑使用另一个容器管理器，如 Podman，它与 Docker 兼容，并且支持更多的 Linux 发行版。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，Docker 安装失败的确是因为 Docker 的在线安装脚本不支持 Oracle Linux 导致的，这种情况你可以预先在服务器上手动安装运行 Docker，之后再运行 1Panel 安装脚本时会自动跳过 Docker 的安装过程。
