### ISSUE TITLE
[BUG]docker监控数据异常不准确

### ISSUE THREAD

**Issue by 52lemon6** [1Panel-dev/1Panel#947]
### 1Panel 版本

1.2.0

### 问题描述

查看docker的监控时，cpu占用不显示，永远显示0%
![image](https://user-images.githubusercontent.com/40059643/236983709-a7ac7dcc-2a90-4d03-8c9c-6ae162cab864.png)
查看docker的监控时，磁盘io和网络显示异常，无论对容器内的应用做什么操作，此监控都不动的，而且和主页的监控有较大出入
![image](https://user-images.githubusercontent.com/40059643/236983830-3f40d9c1-8bad-4c2f-982e-2be50877d96a.png)

### 重现步骤

在容器页面打开容器的监控

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，1Panel 使用的是 Docker 官方的 SDK 获取到的数据，与命令行中执行 docker stats 显示输出保持一致。

**Comment by Dec-QXY** [comment]
> 感谢反馈，1Panel 使用的是 Docker 官方的 SDK 获取到的数据，与命令行中执行 docker stats 显示输出保持一致。

希望考虑将这个地方数据采集优化下

**Comment by wanghe-fit2cloud** [comment]
> > 感谢反馈，1Panel 使用的是 Docker 官方的 SDK 获取到的数据，与命令行中执行 docker stats 显示输出保持一致。
> 
> 希望考虑将这个地方数据采集优化下

我们参考了 Docker 官方项目 Portainer，两边数据是保持一致的。

**Comment by wanghe-fit2cloud** [comment]
可以尝试将 1Panel 升级到最新版本 v1.2.1，看是否还存在 CPU 监控数据永远是 0% 的问题。
