### ISSUE TITLE
[QUESTION] 面板 HTTPS 访问迁移问题

### ISSUE THREAD

**Issue by mx2913** [1Panel-dev/1Panel#949]
### 请描述您的问题

通过网站功能为面板配置了 https 域名访问，升级到 1.2.0 之后要怎么迁移到面板上的 https

**Comment by cyril-cheng** [comment]
没卵用，面板还是没有域名绑定的功能，只能通过反向代理。反向代理，面板有没有ssl完全没有区别。

**Comment by mx2913** [comment]
刚刚尝试直接启用了 https，但是面板就无法通过原先正常的 https 域名访问了，尝试将网站中的 https 反向代理的网站管理也还是一样，最后只能用 https ip 访问在面板中关闭了安全配置中的 https 才恢复正常访问

**Comment by wanghe-fit2cloud** [comment]
> 没卵用，面板还是没有域名绑定的功能，只能通过反向代理。反向代理，面板有没有ssl完全没有区别。

后面版本会支持在面板设置中绑定域名。

**Comment by wanghe-fit2cloud** [comment]
> 刚刚尝试直接启用了 https，但是面板就无法通过原先正常的 https 域名访问了，尝试将网站中的 https 反向代理的网站管理也还是一样，最后只能用 https ip 访问在面板中关闭了安全配置中的 https 才恢复正常访问

需要修改网站 - 反向代理 - 后端代理地址
![image](https://user-images.githubusercontent.com/46734380/237015852-37215119-92d6-4f10-8a57-a0687c2ee1c3.png)

**Comment by mx2913** [comment]
> > 刚刚尝试直接启用了 https，但是面板就无法通过原先正常的 https 域名访问了，尝试将网站中的 https 反向代理的网站管理也还是一样，最后只能用 https ip 访问在面板中关闭了安全配置中的 https 才恢复正常访问
> 
> 需要修改网站 - 反向代理 - 后端代理地址 ![image](https://user-images.githubusercontent.com/46734380/237015852-37215119-92d6-4f10-8a57-a0687c2ee1c3.png)

嗯，那还是等到面板支持直接绑定子域名的版本在切换跳转方式，还是说目前这种形态已经是完整的了

**Comment by wanghe-fit2cloud** [comment]
> > > 刚刚尝试直接启用了 https，但是面板就无法通过原先正常的 https 域名访问了，尝试将网站中的 https 反向代理的网站管理也还是一样，最后只能用 https ip 访问在面板中关闭了安全配置中的 https 才恢复正常访问
> > 
> > 
> > 需要修改网站 - 反向代理 - 后端代理地址 ![image](https://user-images.githubusercontent.com/46734380/237015852-37215119-92d6-4f10-8a57-a0687c2ee1c3.png)
> 
> 嗯，那还是等到面板支持直接绑定子域名的版本在切换跳转方式，还是说目前这种形态已经是完整的了

通过 1Panel 创建反向代理网站和面板设置中开启 https，其实这两种模式都是可以的。

**Comment by wanghe-fit2cloud** [comment]
v1.3 版本已经支持在面板设置页面直接绑定域名。
