### ISSUE TITLE
[BUG]面板申请的证书保存位置是哪里？

### ISSUE THREAD

**Issue by cyril-cheng** [1Panel-dev/1Panel#950]
### 1Panel 版本

1.2.0

### 问题描述

nginx的stream加密隧道需要引用申请的证书，找不到证书的原始存放路径。现在证书只支持绑定站点，stream想使用证书还得先新建个站点才能把证书捞出来，很不方便。

### 重现步骤

nginx的stream加密隧道需要引用申请的证书，找不到证书的原始存放路径。现在证书只支持绑定站点，stream想使用证书还得先新建个站点才能把证书捞出来，很不方便。

### 期待的正确结果

能不能在证书列表界面加一个打开证书存放位置的按钮。

**Comment by mx2913** [comment]
OpenResty 容器内部地址： /www/sites/${你设置的站点名称}/ssl/privkey.pem
虚拟机内实际地址：/opt/1panel/apps/openresty/OpenResty/www/sites/${你设置的站点名称}/ssl

**Comment by zhengkunwang223** [comment]
面板申请的证书保存在数据库中 可以在证书详情页面查看并复制证书

**Comment by cyril-cheng** [comment]
> OpenResty 容器内部地址： /www/sites/${你设置的站点名称}/ssl/privkey.pem 虚拟机内实际地址：/opt/1panel/apps/openresty/OpenResty/www/sites/${你设置的站点名称}/ssl

现在就是这样用的

**Comment by cyril-cheng** [comment]
> 面板申请的证书保存在数据库中 可以在证书详情页面查看并复制证书

好吧

**Comment by cyril-cheng** [comment]
> OpenResty 容器内部地址： /www/sites/${你设置的站点名称}/ssl/privkey.pem 虚拟机内实际地址：/opt/1panel/apps/openresty/OpenResty/www/sites/${你设置的站点名称}/ssl

我说的是nginx的stream隧道，不是建站

**Comment by mx2913** [comment]
> > OpenResty 容器内部地址： /www/sites/${你设置的站点名称}/ssl/privkey.pem 虚拟机内实际地址：/opt/1panel/apps/openresty/OpenResty/www/sites/${你设置的站点名称}/ssl
> 
> 我说的是nginx的stream隧道，不是建站

你不是需要证书的原始存放路径吗，那个就是证书的原始存放路径啊

**Comment by cyril-cheng** [comment]
> > > OpenResty 容器内部地址： /www/sites/${你设置的站点名称}/ssl/privkey.pem 虚拟机内实际地址：/opt/1panel/apps/openresty/OpenResty/www/sites/${你设置的站点名称}/ssl
> > 
> > 
> > 我说的是nginx的stream隧道，不是建站
> 
> 你不是需要证书的原始存放路径吗，那个就是证书的原始存放路径啊

那是转存地址，不新建网站是没有的

**Comment by wfniub** [comment]
是的，不建站，单单添加了证书，路径在哪里？

**Comment by wanghe-fit2cloud** [comment]
> 是的，不建站，单单添加了证书，路径在哪里？

添加证书后数据保存在数据库中，可以在证书详情页面查看并复制证书。

**Comment by wfniub** [comment]
> 

是只有建站，选用了对应的证书才会自动转存为实际的证书文件，只有这样才能再证书到期后自动续期自动转存是吗？

**Comment by wanghe-fit2cloud** [comment]
是的，当前逻辑是这样。

**Comment by wfniub** [comment]
明白了，感谢，如果是泛域名的话，填写*.域名？

**Comment by wanghe-fit2cloud** [comment]
可以的。

**Comment by wanghe-fit2cloud** [comment]
> 明白了，感谢，如果是泛域名的话，填写*.域名？

可以的。

**Comment by wanghe-fit2cloud** [comment]
> > 
> 
> 是只有建站，选用了对应的证书才会自动转存为实际的证书文件，只有这样才能再证书到期后自动续期自动转存是吗？

是的，当前逻辑是这样。

**Comment by rain-xray** [comment]
这个很是需要，泛域名申请的证书复制的话等下次过期还得重新去复制， 如果是路径话，给个路径就完事了。更新证书自动覆盖就ok了。

**Comment by zpengcom** [comment]
需要路径啊

**Comment by 2tof** [comment]
如果没有安装openRestly，证书路径只在/opt/1panel/tmp/ssl/---domain--/目录下面 （我是点了证书下载才出现）原始路径不知道在哪里。全盘搜不到。
看来这个不能代替证书管理功能的，需要自己再装个certbot

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
If not installed
The certificate path is only in the /opt/1panel/tmp/ssl/--domain--/ directory (I clicked on the certificate to download it) I don’t know where the original path is. Can't search the entire disk.
It seems that this cannot replace the certificate management function, so you need to install a certbot yourself.

**Comment by SmartElec** [comment]
找到了 ,安装目录下的`secret`目录
```
/opt/1panel/secret/server.crt
/opt/1panel/secret/server.key
```

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Found
```
/opt/1panel/secret/server.crt
/opt/1panel/secret/server.key
```
