### ISSUE TITLE
[QUESTION]面板内所有链接都无法右键打开

### ISSUE THREAD

**Issue by Felmon** [1Panel-dev/1Panel#955]
### 请描述您的问题

面板内所有可点击的菜单、按钮或者链接都无法通过中键或者右键新标签页打开，想打开多个面板页面只能复制标签页或者复制链接再点击，是否可以支持中键/右键打开呢？

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，上述需求我们在中短期内应该不会支持，望理解。

**Comment by Felmon** [comment]
> 感谢反馈，上述需求我们在中短期内应该不会支持，望理解。

不太理解，应该算是网页操作的基本需求吧。。。[你的 Link Button 能让用户选择新页面打开吗？](https://cloud.tencent.com/developer/beta/article/2223725?areaSource=100001.8&traceId=-qXI7XyOICgY7HWjiHcps)
