### ISSUE TITLE
[FEATURE] 对直接访问phpmyadmin进行限制

### ISSUE THREAD

**Issue by cmmdwl** [1Panel-dev/1Panel#957]
### 1Panel 版本

v1.2.0

### 请描述您的需求或者改进建议

未登录面板前不允许访问

**Comment by zhengkunwang223** [comment]
您好 暂时没有解决方案

**Comment by vlssu** [comment]
> 您好 暂时没有解决方案

那可不可以像宝塔一样，通过面板的反代进入，这样可以在外面关闭 phpmyadmin 端口

**Comment by zhengkunwang223** [comment]
> > 您好 暂时没有解决方案
> 
> 那可不可以像宝塔一样，通过面板的反代进入，这样可以在外面关闭 phpmyadmin 端口

这个我们做一下技术验证
