### ISSUE TITLE
[FEATURE] 希望在文件管理中能添加 “在此处打开终端” 的按钮

### ISSUE THREAD

**Issue by expliyh** [1Panel-dev/1Panel#958]
### 1Panel 版本

v1.2.0

### 请描述您的需求或者改进建议

希望在文件管理中能添加 “在此处打开终端” 的按钮

**Comment by zhengkunwang223** [comment]
感谢建议 后续版本支持此功能

**Comment by zhengkunwang223** [comment]
Refs https://github.com/1Panel-dev/1Panel/issues/958

**Comment by wanghe-fit2cloud** [comment]
v1.8.0 版本已发布。
