### ISSUE TITLE
[QUESTION] 网页备份可不可以选择备份账号？

### ISSUE THREAD

**Issue by expliyh** [1Panel-dev/1Panel#959]
### 请描述您的问题

网页备份可不可以选择备份账号？默认好像是直接备份到服务器磁盘，没找到选择备份账号的地方。

**Comment by zhengkunwang223** [comment]
可以在计划任务中添加备份网站的任务 选择备份账号

**Comment by expliyh** [comment]
> 可以在计划任务中添加备份网站的任务 选择备份账号

好的，谢谢
