### ISSUE TITLE
[FEATURE]建议增加手动选择后端协议或者是根据输入的后端地址自动判断后端协议

### ISSUE THREAD

**Issue by oooldmaozi** [1Panel-dev/1Panel#962]
### 1Panel 版本

v1.2.0

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/49929588/237063220-1aecc381-96a3-43dc-be08-ca537786e02c.png)
建议反向代理后端地址支持选择更多的协议 比如  现在默认http协议 直接更改为grpc协议会报错  需要使用grpc还需要去手动修改配置文件
![image](https://github.com/1Panel-dev/1Panel/assets/49929588/f32115da-bc98-4e9f-9f52-7456af7afd04)

### 请描述你建议的实现方案

nginx代理grpc的配置是
     grpc_pass grpc://grpcservers;
建议增加手动选择后端协议或者是根据输入的后端地址自动判断后端协议，再生成配置文件

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中持续优化网站反向代理功能。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已发布，支持选择 http、https 等协议。
