### ISSUE TITLE
[BUG] 首页数据面板 网络速度出现负值

### ISSUE THREAD

**Issue by Dec-QXY** [1Panel-dev/1Panel#963]
### 1Panel 版本

1.2.0

### 问题描述

首页数据面板 网络速度出现负值

### 重现步骤

突然加大网络请求结束后会出现

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，这个问题我们会在下个版本中修复。

**Comment by maninhill** [comment]
v1.2.1 已解决。
