### ISSUE TITLE
[BUG] 修改 备份 - 服务器磁盘路径 失败

### ISSUE THREAD

**Issue by kookyleo** [1Panel-dev/1Panel#966]
### 1Panel 版本

v1.2.0

### 问题描述

修改 备份 - 服务器磁盘 路径 时出现错误，提示：
"服务内部错误: stderr: cp: cannot stat '/opt/1panel/backup/*': No such file or directory"

其中，/opt/1panel/backup/ 是原目录，执行操作时该目录下没有内容。
另外谨慎起见，在提交本 issues 之前，特意将本软件完全删除、重装了一次，完全重现。
操作系统为 Ubuntu 22.04.2 LTS 

### 重现步骤

安装软件，启动，登陆 web ui，进入 /settings/backupaccount
点击右侧 "编辑" 按钮，"修改" 当前路径，"确定"，
出现提示："服务内部错误: stderr: cp: cannot stat '/opt/1panel/backup/*': No such file or directory"
修改失败

**Comment by ssongliu** [comment]
感谢反馈！确实存在这个问题，预计在下个小版本解决。
