### ISSUE TITLE
[BUG] 网站 - HTTPS - 手动导入证书 无效

### ISSUE THREAD

**Issue by kookyleo** [1Panel-dev/1Panel#967]
### 1Panel 版本

v1.2.0

### 问题描述

网站 - HTTPS - 手动导入证书 无效

访问：/websites/1/config/basic
切换至 HTTPS 配置项，选择 手动导入证书
贴入 key、pem 内容，保存

这个过程涉及两个问题：
1. （算产品建议）key、pem 提交的内容，现在没有做去除折行处理（几乎所有生成的证书文件都是有折行的，现在的处理方式直接贴过来会报错）
2.  (手工 s/\n//g 折行问题后) 提示成功，但，什么都没有生效，依然是 http 状态（且上传内容就"丢"了)

### 重现步骤

访问：/websites/1/config/basic
切换至 HTTPS 配置项，选择 手动导入证书
贴入 key、pem 内容，保存

**Comment by zhengkunwang223** [comment]
可以查看一下网站日志

**Comment by kookyleo** [comment]
> 可以查看一下网站日志

不像是「网站」的问题（这里的网站指 1pannel 产品概念，如 /websites 下的「网站」列表）
我示意的这个「网站」类型是反向代理，源就是 1pannel 自己的  web 服务，我给了一个域名，然后反向到 localhost:[大数字] 端口。
填写秘钥、证书（其它字段均为默认）后，保存，即提示「更新成功」（但前端「启用 https」的小 switch 就自动回到未启用状态了。
重试多次依旧。
网站 - 日志下没有什么特别内容，「错误日志」甚至还在提示「当前没有日志」

**Comment by kookyleo** [comment]
看「网站配置」-「配置文件」没有 https/ssl 相关的配置，还没过去

**Comment by kookyleo** [comment]
面板日志 - 系统日志 中看到了一些 panic 记录

runtime error: invalid memory address or nil pointer dereference
runtime/panic.go:220 (0x45043c)
runtime/signal_unix.go:818 (0x45040c)
github.com/1Panel-dev/1Panel/backend/app/service/website.go:669 (0x25bfd65)
github.com/1Panel-dev/1Panel/backend/app/api/v1/website.go:355 (0x274e1d7)
github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x26abca2)
github.com/1Panel-dev/1Panel/backend/middleware/password_expired.go:24 (0x26ab9d6)
github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x26ac021)
github.com/1Panel-dev/1Panel/backend/middleware/session.go:36 (0x26abf97)
github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x26a99ed)
github.com/1Panel-dev/1Panel/backend/middleware/jwt.go:15 (0x26a98de)
github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x26a9c13)
github.com/1Panel-dev/1Panel/backend/middleware/loading.go:22 (0x26a9b96)
github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x26320cf)
github.com/gin-contrib/gzip@v0.0.6/handler.go:60 (0x26320a8)
github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x26aa2d8)
github.com/1Panel-dev/1Panel/backend/middleware/operation.go:47 (0x26aa2bc)
github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x1c9e441)
github.com/gin-gonic/gin@v1.9.0/recovery.go:102 (0x1c9e42c)
github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x1c9d526)
github.com/gin-gonic/gin@v1.9.0/logger.go:240 (0x1c9d509)
github.com/gin-gonic/gin@v1.9.0/context.go:174 (0x1c9c5b0)
github.com/gin-gonic/gin@v1.9.0/gin.go:620 (0x1c9c218)
github.com/gin-gonic/gin@v1.9.0/gin.go:576 (0x1c9bd5c)
net/http/server.go:2916 (0x77aa7a)
net/http/server.go:1966 (0x775a76)
runtime/asm_amd64.s:1571 (0x46db20)
[0m

但看起来不太像是这块的，
暂时就看了这些

**Comment by zhengkunwang223** [comment]
有手动修改过配置文件 或者 修改网站相关文件夹 文件之类的吗

**Comment by kookyleo** [comment]
> 有手动修改过配置文件 或者 修改网站相关文件夹 文件之类的吗

提 issue 之前，特意（通过 webui ）删掉旧「网站」，重建、测试的

**Comment by zhengkunwang223** [comment]
看了下你提供的 panic 日志，发现是处理证书的时候报错，应该是证书文件不能被解析

**Comment by kookyleo** [comment]
> 看了下你提供的 panic 日志，发现是处理证书的时候报错，应该是证书文件不能被解析

更新版本再试看已经可以了，赞速度

**Comment by 1129921824** [comment]
> > 可以查看一下网站日志
> 
> 不像是「网站」的问题（这里的网站指 1pannel 产品概念，如 /websites 下的「网站」列表） 我示意的这个「网站」类型是反向代理，源就是 1pannel 自己的 web 服务，我给了一个域名，然后反向到 localhost:[大数字] 端口。 填写秘钥、证书（其它字段均为默认）后，保存，即提示「更新成功」（但前端「启用 https」的小 switch 就自动回到未启用状态了。 重试多次依旧。 网站 - 日志下没有什么特别内容，「错误日志」甚至还在提示「当前没有日志」

你的修复了吗？目前我遇到和你一样的问题了 v1.9.3
