### ISSUE TITLE
[FEATURE] 页面显示优化

### ISSUE THREAD

**Issue by cn2chenk** [1Panel-dev/1Panel#972]
### 1Panel 版本

1.2.0

### 请描述您的需求或者改进建议

1、首页 推荐应用 ，不推荐已安装应用。
2、应用商店-->全部 ,已安装应用 显示已安装（目前已安装应用显示 安装）

**Comment by zhengkunwang223** [comment]
感谢建议 现在很多应用是支持重复安装的 比如 wordpress 和 halo    
后续会优化只能安装一次的应用显示
