### ISSUE TITLE
[FEATURE]建议在容器列表右侧抽屉页面中，增加对应的容器名称

### ISSUE THREAD

**Issue by ghost** [1Panel-dev/1Panel#975]
### 1Panel 版本

v1.2.0

### 请描述您的需求或者改进建议

建议在容器列表右侧抽屉页面中，增加对应的容器名称。
![image](https://github.com/1Panel-dev/1Panel/assets/93708226/4bbdb646-46f6-42de-ad9a-a3eadf3fad1b)

### 请描述你建议的实现方案

编排、镜像等页面也需要增加 name 字段

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本持续优化。

**Comment by Felmon** [comment]
> 感谢反馈，后续版本持续优化。

抽屉的其他地方也是，希望都能增加name字段
比如文件操作（权限、压缩等）容器（日志、终端、监控）
现在点击操作后，展开的抽屉都不能确定是不是操作的对象
