### ISSUE TITLE
[QUESTION] 前端 打包 不能成功 出现 codemirror 错误

### ISSUE THREAD

**Issue by PangSanJin-R** [1Panel-dev/1Panel#976]
### 联系方式

1160840143@qq.com

### 1Panel 版本

dev

### 问题描述

使用 npm run build:dev  打包 出现 

[vite]: Rollup failed to resolve import "codemirror" from "node_modules/vue-codemirror/dist/vue-codemirror.esm.js".
This is most likely unintended because it can break your application at runtime.

使打包不成功！！！

切换使用 node 14,16,18 都不可以

### 重现步骤

在 dev 分支 前端打包

### 期待的正确结果

npm run build:dev 可以正常打包

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/68041751/6dc764b9-7820-47c8-b761-ebc32c428670)

**Comment by zhengkunwang223** [comment]
npm info vue-codemirror 查看一下 vue-codemirror 版本

**Comment by PangSanJin-R** [comment]
6.1.1 版本的
![image](https://github.com/1Panel-dev/1Panel/assets/68041751/33409f6a-7afd-4b1e-8105-aeaba8ab1c70)
![image](https://github.com/1Panel-dev/1Panel/assets/68041751/352a8996-664c-48c1-acf9-e0cd0785b9d7)

**Comment by zhengkunwang223** [comment]
vue-codemirror 版本是正确的  
我的 npm 版本 9.6.4 node 版本 v20.1.0

**Comment by PangSanJin-R** [comment]
可以了 建议前端 加一个 .nvmrc 指定 node 版本

**Comment by zhengkunwang223** [comment]
> 可以了 建议前端 加一个 .nvmrc 指定 node 版本

好的
