### ISSUE TITLE
[BUG] 运行环境的镜像名称没有根据应用 tag 修改

### ISSUE THREAD

**Issue by zhengkunwang223** [1Panel-dev/1Panel#978]
### 1Panel 版本

v1.2

### 问题描述

创建的运行环境版本和应用商店中的版本不一致

### 重现步骤

1.创建运行环境
2.选择 PHP 应用
3.切换版本
4.创建网站

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。该问题会在 v1.2.1 版本中修复。
