### ISSUE TITLE
[FEATURE]几点小建议

### ISSUE THREAD

**Issue by vlssu** [1Panel-dev/1Panel#991]
### 1Panel 版本

1.2.0

### 请描述您的需求或者改进建议

- 让面板可以输入 自定义dns服务器，2到3个差不多够了
- 虚拟内存设置
- 是否允许 root 直接连接登录（包括设置密码）
- 防火墙那边，如果系统没开防火墙，那面板只有一个提示，可以不可以增加一个打开防火墙的按钮

- 文件列表添加右键的逻辑，还有选择的效果，类似windows上的文件管理的操作逻辑（这个真的需要，他太影响体验了）
- 还有就是文件列表支持下拖拽上传，不需要点击 上传 按钮，文件直接拖到文件列表上，类似宝塔那种。

**Comment by zhengkunwang223** [comment]
感谢建议 我们讨论一下你的这些需求

**Comment by wanghe-fit2cloud** [comment]
文件列表右键操作的功能暂无计划支持，其他几点建议在最新版本已支持。
