### ISSUE TITLE
[BUG]在手动部署容器时，无法配置挂载卷

### ISSUE THREAD

**Issue by 2944721178** [1Panel-dev/1Panel#992]
### 联系方式

交流一群，蓝色GXL

### 1Panel 版本

1.2.1

### 问题描述

在手动部署容器时，无法配置挂载卷，点添加挂载卷后，点哪都没反应，包括叉掉再点部署容器，极端条件下，必须刷新前往首页，否则防火墙，容器等界面，一点数据都没有，从1.2.0版本开始就有这个情况

### 重现步骤

手动部署容器时，无法配置挂载卷

**Comment by ssongliu** [comment]
感谢反馈，可以试一下谷歌浏览器，应该是浏览器不兼容的问题。
