### ISSUE TITLE
[BUG]php安装不上Imagick扩展

### ISSUE THREAD

**Issue by Kato358** [1Panel-dev/1Panel#993]
### 1Panel 版本

1.2.1

### 问题描述

PHP中的 Imagick 高性能图片处理拓展已在运行环境中正确填写，但始终安装不上。

### 重现步骤

![image](https://github.com/1Panel-dev/1Panel/assets/30019793/68cecc4a-4b83-4906-a602-7be0d154ad22)
![image](https://github.com/1Panel-dev/1Panel/assets/30019793/8ac1e78e-bb43-4259-b297-9654376f5c33)

**Comment by zhengkunwang223** [comment]
您好 扩展需要小写 imagick 
可以参考这个 https://github.com/1Panel-dev/appstore/wiki/PHP-%E5%AE%B9%E5%99%A8%E6%89%A9%E5%B1%95%E6%94%AF%E6%8C%81

**Comment by Kato358** [comment]
> 您好扩展需要小写imagick 可以参考这个[https://github.com/1Panel-dev/appstore/wiki/PHP-%E5%AE%B9%E5%99%A8%E6%89%A9%E5%B1% 95%E6%94%AF%E6%8C%81](https://github.com/1Panel-dev/appstore/wiki/PHP-%E5%AE%B9%E5%99%A8%E6%89%A9%E5%B1%95%E6%94%AF%E6%8C%81)

![image](https://github.com/1Panel-dev/1Panel/assets/30019793/fa06812f-8ef4-483a-9954-8c8f0c045e4c)
![image](https://github.com/1Panel-dev/1Panel/assets/30019793/7e15afa6-3bff-4b0c-847e-e4b431b15d9f)
你好，改成小写同时新建了个网站测试还是不行

**Comment by zhengkunwang223** [comment]
> > 您好扩展需要小写imagick 可以参考这个[https://github.com/1Panel-dev/appstore/wiki/PHP-%E5%AE%B9%E5%99%A8%E6%89%A9%E5%B1% 95%E6%94%AF%E6%8C%81](https://github.com/1Panel-dev/appstore/wiki/PHP-%E5%AE%B9%E5%99%A8%E6%89%A9%E5%B1%95%E6%94%AF%E6%8C%81)
> 
> 
> 
> ![image](https://github.com/1Panel-dev/1Panel/assets/30019793/fa06812f-8ef4-483a-9954-8c8f0c045e4c)
> 
> ![image](https://github.com/1Panel-dev/1Panel/assets/30019793/7e15afa6-3bff-4b0c-847e-e4b431b15d9f)
> 
> 你好，改成小写同时新建了个网站测试还是不行

需要在应用商店，已安装页面重建php 应用

**Comment by Kato358** [comment]
> > > 您好扩展需要小写imagick 可以参考这个[https://github.com/1Panel-dev/appstore/wiki/PHP-%E5%AE%B9%E5%99%A8%E6%89%A9%E5%B1% 95%E6%94%AF%E6%8C%81](https://github.com/1Panel-dev/appstore/wiki/PHP-%E5%AE%B9%E5%99%A8%E6%89%A9%E5%B1%95%E6%94%AF%E6%8C%81)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/30019793/237428636-fa06812f-8ef4-483a-9954-8c8f0c045e4c.png)
> > ![image](https://user-images.githubusercontent.com/30019793/237430323-7e15afa6-3bff-4b0c-847e-e4b431b15d9f.png)
> > 你好，改成小写同时新建了个网站测试还是不行
> 
> 需要在应用商店，已安装页面重建php 应用

已经重建过了，麻烦您测试一下，我这边始终安不上，不知道为什么

**Comment by zhengkunwang223** [comment]
> > > > 您好扩展需要小写imagick 可以参考这个[https://github.com/1Panel-dev/appstore/wiki/PHP-%E5%AE%B9%E5%99%A8%E6%89%A9%E5%B1% 95%E6%94%AF%E6%8C%81](https://github.com/1Panel-dev/appstore/wiki/PHP-%E5%AE%B9%E5%99%A8%E6%89%A9%E5%B1%95%E6%94%AF%E6%8C%81)
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/30019793/237428636-fa06812f-8ef4-483a-9954-8c8f0c045e4c.png)
> > > ![image](https://user-images.githubusercontent.com/30019793/237430323-7e15afa6-3bff-4b0c-847e-e4b431b15d9f.png)
> > > 你好，改成小写同时新建了个网站测试还是不行
> > 
> > 
> > 需要在应用商店，已安装页面重建php 应用
> 
> 已经重建过了，麻烦您测试一下，我这边始终安不上，不知道为什么

您好 我们复现了一下 确实有些版本安装不上 我们处理一下

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
