### ISSUE TITLE
[BUG] 申请证书，多个域名情况下UI异常

### ISSUE THREAD

**Issue by Teletele-Lin** [1Panel-dev/1Panel#996]
### 联系方式

hyl51740740@gmail.com

### 1Panel 版本

1.2.1

### 问题描述

申请证书，填写多个域名情况下UI异常

### 重现步骤

申请证书，填写多个域名情况下UI异常，表格中解析域名值 末尾有 '.' ，是否可以正常使用证书
![image](https://github.com/1Panel-dev/1Panel/assets/44634748/11d2d5c9-8b57-4b07-bf6c-a7ea2660b788)

### 期待的正确结果

排版无误
建议说明“其他域名”具体指代什么

### 附加信息

![image](https://github.com/1Panel-dev/1Panel/assets/44634748/f76fd823-65a3-4f82-86ae-3da2f434ffeb)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中优化上述问题。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0 版本已发布。
