### ISSUE TITLE
[FEATURE] 多域名证书申请

### ISSUE THREAD

**Issue by Teletele-Lin** [1Panel-dev/1Panel#997]
### 1Panel 版本

1.2.1

### 请描述您的需求或者改进建议

目前似乎只能申请单域名证书，后续版本能否添加生成 多域名证书 功能，即一个证书可以在多个子域名中使用

### 请描述你建议的实现方案

BT面板似乎支持

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中支持添加多域名证书这个需求。

**Comment by guclan** [comment]
目前支持泛域名，应该可以满足这个需求吧~
![image](https://github.com/1Panel-dev/1Panel/assets/25996724/d3b7bd53-ab44-49a5-bf77-50d72ab77efa)
