### ISSUE TITLE
应用商店后续能支持rabbitMQ吗[FEATURE]

### ISSUE THREAD

**Issue by faruzanCN** [1Panel-dev/1Panel#998]
### 1Panel 版本

V1.2.2

### 请描述您的需求或者改进建议

希望后续应用商店能支持rabbitMQ
https://hub.docker.com/_/rabbitmq

**Comment by wanghe-fit2cloud** [comment]
感谢反馈
当前版本，你可以将 RabbitMQ 添加为本地应用，测试通过后还可以提交 pull requests 到官方仓库。
具体教程，请参考 [如何提交自己想要的应用](https://github.com/1Panel-dev/appstore/wiki/%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4%E8%87%AA%E5%B7%B1%E6%83%B3%E8%A6%81%E7%9A%84%E5%BA%94%E7%94%A8)
#250

**Comment by wanghe-fit2cloud** [comment]
v1.4.0 版本已发布。
